### PR TITLE
fix(47562): Add option to suppress type hint if variable name matches type name

### LINKED ISSUE #47562: Inlay hints suppression should be case insensitive and look within variable names
# Suggestion
## 🔍 Search Terms

* inlay hints
* suppression

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow suppression of inlay hints to be a bit smarter. Case insensitive and looking within variable names would be nice.

## 📃 Motivating Example

Often times the variable name matches the type, but is just a different case so I get the same name twice.
149641846-c3252031-3acd-4834-a53e-6e6ef27e0506

But also sometimes the name of a parameter is contained within the name of the variable:
149641867-12cdaa5e-97ec-493d-88b1-bca3731af850

As it is right now I get a lot of repetition which makes things more difficult to read.

## 💻 Use Cases

I think the example covers the use cases, or vice versa.

### PR DESCRIPTION
**Pull request by huytd**
Fixes #47562 

The approach I'm proposing here is to add a new option called `includeInlayVariableTypeHintsWhenTypeMatchesName` for the `UserPreferences`.

When the user turns off this option, we will check if the variable name matches the type display string and suppress the hint for this case.

### CODE REVIEW

**Review by gabritto — APPROVED** [review]

**Comment by gabritto** [comment]
@andrewbranch we'd need to add the new option to vscode too, right?

**Comment by andrewbranch** [comment]
Yep.

File: src/services/inlayHints.ts [hunk 1]
```diff
@@ -137,10 +137,18 @@ namespace ts.InlayHints {
 
             const typeDisplayString = printTypeInSingleLine(declarationType);
             if (typeDisplayString) {
+                const isVariableNameMatchesType = !preferences.includeInlayVariableTypeHintsWhenTypeMatchesName && variableDeclarationNameMatchesTypeString(decl.name.getText(), typeDisplayString);
```
Comment (andrewbranch) [inline src/services/inlayHints.ts:140]: I’m not sure how concerned to be that older clients won’t send this preference and so for them, the default behavior will change. Maybe it’s better to see if the preference `=== false` so that `undefined` is like `true`.

File: src/services/inlayHints.ts [hunk 2]
```diff
@@ -137,10 +137,18 @@ namespace ts.InlayHints {
...
             if (typeDisplayString) {
+                const isVariableNameMatchesType = !preferences.includeInlayVariableTypeHintsWhenTypeMatchesName && variableDeclarationNameMatchesTypeString(decl.name.getText(), typeDisplayString);
+                if (isVariableNameMatchesType) {
+                    return;
+                }
                 addTypeHints(typeDisplayString, decl.name.end);
             }
         }
 
+        function variableDeclarationNameMatchesTypeString(declarationName: string, typeDisplayString: string) {
```
Comment (andrewbranch) [inline src/services/inlayHints.ts:148]: I don’t like functions with highly specific names but very general functionality. You can delete this and use `equateStringsCaseInsensitive`.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Comment by huytd** [comment]
Thank you so much for the feedbacks @andrewbranch @gabritto I'll update the PR to fix the issues you mentioned 👍

**Comment by andrewbranch** [comment]
Thanks @huytd! We’re going to discuss this in our meeting with VS Code next week. Hang tight until then 👍

**Comment by andrewbranch** [comment]
We discussed this today, but were missing a few key people on vacation. I think the issue probably needed a little more design specification before asking for a PR—we discussed the possibility of addressing the noisiness of inlay hints with fuzzy string matching a bit more holistically rather than adding a new setting for each one we eliminate. We’re going to bring it up again next week when we have the full group back.

**Comment by huytd** [comment]
Thank you so much for keeping me updated! @andrewbranch

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
Thanks for your patience @huytd!

@mjbvz, the user preference is already in here.
