### PR TITLE
Reduce intersections with conflicting privates, elaborate on reasons

### LINKED ISSUE #37659: [3.9.0-beta] OR'd types seem to get ANDed because of assertions
**TypeScript Version:**  3.9.0-dev.20200327

**Search Terms:**

**Expected behavior:**
No error -- this worked fine in 3.8 (and should)

**Actual behavior:**
Error:
```
Argument of type 'CommitFileNode | ResultsFileNode | (ResultsFileNode & StashFileNode)' is not assignable to parameter of type 'CommitFileNode | ResultsFileNode | StashFileNode | StatusFileNode'.
  Type 'ResultsFileNode & StashFileNode' is not assignable to type 'CommitFileNode | ResultsFileNode | StashFileNode | StatusFileNode'.
    Type 'ResultsFileNode & StashFileNode' is not assignable to type 'StashFileNode'.
      Property '_foo1' has conflicting declarations and is inaccessible in type 'ResultsFileNode & StashFileNode'.(2345)
```

**Related Issues:**

**Code**
```ts
abstract class ViewNode { }
abstract class ViewRefNode extends ViewNode { }
abstract class ViewRefFileNode extends ViewRefNode { }

class CommitFileNode extends ViewRefFileNode {
  private _id: any;
}

class ResultsFileNode extends ViewRefFileNode {
  private _id: any;
}

class StashFileNode extends CommitFileNode { 
  private _id2: any;
}

class StatusFileNode extends ViewNode {
  private _id: any;
}

class Foo {
  private async foo(node: CommitFileNode | ResultsFileNode | StashFileNode) {
		if (
			!(node instanceof CommitFileNode) &&
			!(node instanceof StashFileNode) &&
			!(node instanceof ResultsFileNode)
		) {
			return;
		}

		await this.bar(node);
	}

  private async bar(node: CommitFileNode | ResultsFileNode | StashFileNode | StatusFileNode, options?: {}) {
    return Promise.resolve(undefined);
  }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class ViewNode {
}
class ViewRefNode extends ViewNode {
}
class ViewRefFileNode extends ViewRefNode {
}
class CommitFileNode extends ViewRefFileNode {
}
class ResultsFileNode extends ViewRefFileNode {
}
class StashFileNode extends CommitFileNode {
}
class StatusFileNode extends ViewNode {
}
class Foo {
    async foo(node) {
        if (!(node instanceof CommitFileNode) &&
            !(node instanceof StashFileNode) &&
            !(node instanceof ResultsFileNode)) {
            return;
        }
        await this.bar(node);
    }
    async bar(node, options) {
        return Promise.resolve(undefined);
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-dev.20200327#code/IYIwzgLgTsDGEAJYBthjAgagSwKYHcA5AewBNcEBvBAXwChRIZ4lV0s98AlXAMxPIJcADwi4AdqQw4CAitXqNocRCjTTOPXgDFsyXHKGiJUjgS2GFdOmvYBhYgFtH2CLv2GRYyRvN93BmTydAgIAA5Q2ABuwGIIAPrYpABcCMDiAJ4A3HT0NmwYPGAArsgQYAGexj5m3P56gYKUIeGRMXGJKWmZOXm2GADKEGgAFpVBRt6mDs6u400ILRHRsRSdAEyp6dm51v0IQ7HFFQ1VU75EE82hy+1rSVs9u-nqCNrExFRLbatpYBniWAIXgfAAU4iCqRmLjcpwmAB8EEVSuV5hREYcwGM4eQAJRfACQBOwvAQoLoRIJAEJwRNsOJIOlYLhiKToXMcbh8QAybkUok0iGCemMwEs0mY7EeII8vmUwV0hnDMWspG4EplE7SvH8-HNSlQXAQYpQcQ5Il5InAfDAVwICAjbBgAB0IGAUFpePNeRuPziaABQLdHqFuChThhaIQiORmqjGOGWPjB2Gxq1jVwABoEMQwhBsMQGQB+VKUGh6lqhQ3G00IAAKUCcTtwzsNYGIyCiuFBxUkfHpuFIuJyoXoNCAA)

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we reduce intersections with conflicting private property declarations to `never`. Furthermore, we elaborate on the reasons for `never` reduced intersections, explaining which property is causing the conflict.

This PR supercedes #37724 and #37618 (stealing your thunder, @DanielRosenwasser).

Fixes #37659.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -10428,12 +10433,37 @@ namespace ts {
...
+                return chainDiagnosticMessages(errorInfo, Diagnostics.The_intersection_0_was_reduced_to_never_because_property_1_has_conflicting_types_in_some_constituents,
+                    typeToString(type, /*enclosingDeclaration*/ undefined, TypeFormatFlags.NoTypeReduction), symbolToString(neverProp));
+            }
+            const privateProp = find(getPropertiesOfUnionOrIntersectionType(type), isConflictingPrivateProperty);
+            if (privateProp) {
+                return chainDiagnosticMessages(errorInfo, Diagnostics.The_intersection_0_was_reduced_to_never_because_property_1_exists_in_multiple_constituents_and_is_private_in_some,
+                    typeToString(type, /*enclosingDeclaration*/ undefined, TypeFormatFlags.NoTypeReduction), symbolToString(privateProp));
+            }
+            return errorInfo;
+        }
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:10465]: Consider reporting more than the first conflict

```suggestion
        function tryElaborateIfIntersectionReducedToNever(type: Type, currentErrorInfo: DiagnosticMessageChain | undefined) {
            if (getObjectFlags(type) & ObjectFlags.IsNeverIntersection) {
                const intersectionString = typeToString(type, /*enclosingDeclaration*/ undefined, TypeFormatFlags.PreserveVacuousIntersections);
                const conflictingPropertyNames = map(filter(getPropertiesOfUnionOrIntersectionType(<IntersectionType>type), isDiscriminantWithNeverType), symbolName);
                const maxNumProperties = 3;
                const propertiesToReport = conflictingPropertyNames.length <= maxNumProperties
                    ? conflictingPropertyNames
                    : [...conflictingPropertyNames.slice(0, maxNumProperties), "..."];
                const propertiesString = propertiesToReport.join(", ");
                const diag = conflictingPropertyNames.length === 1
                    ? Diagnostics.The_type_never_was_reduced_from_the_intersection_0_Some_types_of_that_intersection_conflict_in_the_property_1_so_values_of_that_type_can_never_exist
                    : Diagnostics.The_type_never_was_reduced_from_the_intersection_0_Some_types_of_that_intersection_conflict_in_the_properties_1_so_values_of_that_type_can_never_exist;
                return chainDiagnosticMessages(currentErrorInfo, diag, intersectionString, propertiesString);
            }
            return currentErrorInfo;
        }
```

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I looked at doing that but decided it wasn't worth the extra code and error messages. You feel strongly we need it?

File: tests/baselines/reference/mixinAccessModifiers.errors.txt [hunk 2]
```diff
@@ -181,16 +183,18 @@ tests/cases/conformance/classes/mixinAccessModifiers.ts(130,4): error TS2445: Pr
...
-!!! error TS2445: Property 'protectedMethod' is protected and only accessible within class 'ProtectedGeneric<{ a: void; }> & ProtectedGeneric2<{ a: void; b: void; }>' and its subclasses.
+!!! error TS2339: Property 'protectedMethod' does not exist on type 'never'.
+!!! error TS2339:   The intersection 'ProtectedGeneric<{ a: void; }> & ProtectedGeneric2<{ a: void; b: void; }>' was reduced to 'never' because property 'privateMethod' exists in multiple constituents and is private in some.
     }
     
     function f9(x: ProtectedGeneric<{a: void;}> & ProtectedGeneric<{a:void;b:void;}>) {
     	x.privateMethod(); // Error, private constituent makes method inaccessible
     	  ~~~~~~~~~~~~~
-!!! error TS2546: Property 'privateMethod' has conflicting declarations and is inaccessible in type 'ProtectedGeneric<{ a: void; }> & ProtectedGeneric<{ a: void; b: void; }>'.
+!!! error TS2341: Property 'privateMethod' is private and only accessible within class 'ProtectedGeneric<T>'.
```
Comment (weswigham) [inline tests/baselines/reference/mixinAccessModifiers.errors.txt:197]: ? What happened here?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -10476,12 +10481,37 @@ namespace ts {
...
+
+        function elaborateNeverIntersection(errorInfo: DiagnosticMessageChain | undefined, type: IntersectionType) {
+            const neverProp = find(getPropertiesOfUnionOrIntersectionType(type), isDiscriminantWithNeverType);
+            if (neverProp) {
+                return chainDiagnosticMessages(errorInfo, Diagnostics.The_intersection_0_was_reduced_to_never_because_property_1_has_conflicting_types_in_some_constituents,
+                    typeToString(type, /*enclosingDeclaration*/ undefined, TypeFormatFlags.NoTypeReduction), symbolToString(neverProp));
+            }
+            const privateProp = find(getPropertiesOfUnionOrIntersectionType(type), isConflictingPrivateProperty);
+            if (privateProp) {
+                return chainDiagnosticMessages(errorInfo, Diagnostics.The_intersection_0_was_reduced_to_never_because_property_1_exists_in_multiple_constituents_and_is_private_in_some,
```
Comment (weswigham) [inline src/compiler/checker.ts:10509]: Should we add related spans pointing at the location(s) of the private declarations? I imagine one of the possible "fixes" for this error is just making the fields public.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

File: tests/baselines/reference/mixinAccessModifiers.errors.txt (hunk 2 above)
Comment (ahejlsberg) [reply tests/baselines/reference/mixinAccessModifiers.errors.txt:197]: This is an intended change. Error `TS2546` is gone and has been superseded by the reduction of intersections with conflicting privates. In this particular case, however, the error wasn't even correct because there is only one declaration of `privateMethod` in the intersection (and therefore the intersection didn't get reduced to `never`).

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:10509]: We could consider it, but not super high value given that this is a pretty esoteric error.

File: tests/baselines/reference/mixinAccessModifiers.errors.txt (hunk 2 above)
Comment (weswigham) [reply tests/baselines/reference/mixinAccessModifiers.errors.txt:197]: Huh, ok.
