### PR TITLE
ESNext+[[Define]]: reference to param props illegal

### LINKED ISSUE #36410: useDefineForClassFields and parameter properties: missing error or bad emit
**TypeScript Version:**  3.8.0-dev.20200123

**Search Terms:** useDefineForClassFields parameter

**Code**

```ts
// @useDefineForClassFields: true
// @target: esnext
class C {
  bar = this.foo.bar;
  constructor(private foo: {bar: string}) {}
}
```

**Expected behavior:**

Transpiled code works (`bar` is defined in the constructor as it's done for the downlevel emit) OR used-before-assignment error on `this.foo` in the initializer of `bar`.

**Actual behavior:**

Since the initializer of `bar` is run before the assignment of `foo`, there's a runtime error.
This code used to work for ages (of course without native class fields). A lot of code that uses dependency injection looks like this.

**Playground Link:** https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99&ts=3.8.0-dev.20200123&ssl=4&ssc=2&pln=1&pc=1#code/MYGwhgzhAEDC0G8BQ1oCMwCdoF5oBcALASwgDoAzAeyrI0wG4VpgqA7CfTAV2HyswAKAA6ZiANzD4AptGpUAXInpLOYtgHMAvgEpEWpFqA

**Related Issues:** 
I thought this was already discussed somewhere with @RyanCavanaugh and @sandersn, but I couldn't find an issue for that.
Found while looking at #36405. That PR would need an exception if parameter properties are involved IF you want to continue supporting the example code.

### PR DESCRIPTION
**Pull request by sandersn**
When target: "esnext" and useDefineForClassFields: true, property
declaration initialisers should not be able to reference parameter
properties; class fields are initialised before the constructor runs,
but parameter properties are not:

```ts
class C {
  foo = this.bar
  constructor(public bar: string) { }
}
```

emits code that looks like this:

```js
class C {
  bar
  foo = this.bar
  constructor(bar) {
    this.bar = bar
  }
}
new C('x').foo.length // crashes; foo is undefined
```

This PR adds an error on foo's declaration with ESNext+[[Define]].

Fixes #36410

### CODE REVIEW

File: tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// @useDefineForClassFields: true
+// @target: esnext
+class C {
+    qux = this.bar // should error
+    bar = this.foo // should error
+    quiz = this.bar // ok
```
Comment (sandersn) [inline tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts]: Given the code change, I don't understand why the lines with `// ok` don't error. It is *nice* that they don't though.
