### PR TITLE
Esm imports of cjs files should unconditionally have a default patched on

### LINKED ISSUE #47859: TypeScript mjs cjs support
# Bug Report

### 🔎 Search Terms

mjs cjs

### 🕗 Version & Regression Information

4.6.0-dev.20220211

### ⏯ Playground Link

https://github.com/xiaoxiangmoe/typescript-cjs-default-export-bug

### 💻 Code

```ts
// file: src/a.cts
export const a: number = 1
export default 'string'
```

```ts
// file: src/foo.mts
import d, {a} from './a.cjs'
import * as m from './a.cjs'
export {d,a,m}

console.log(d.a)
// Property 'default' does not exist on type 'typeof import("/Users/me/repos/typescript-cjs-default-export-bug/src/a")'.
console.log(m.default.a)
```

### 🙁 Actual behavior

```
Property 'default' does not exist on type 'typeof import("/Users/me/repos/typescript-cjs-default-export-bug/src/a")'.
```

### 🙂 Expected behavior

No error. Because `import d, {a} from './a.cjs'` has no error.

### PR DESCRIPTION
**Pull request by weswigham**
Rather than only in the `esModuleInterop` detected case where the target file has a `default` of its own or call/construct signatures.

Fixes #47859

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3687,12 +3687,18 @@ namespace ts {
                         return cloneTypeAsModuleType(symbol, defaultOnlyType, referenceParent);
                     }
 
-                    if (getESModuleInterop(compilerOptions)) {
+                    const targetFile = moduleSymbol?.declarations?.find(isSourceFile);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:3690]: What about ambient module declarations that use `export =`? They can only be describing CJS modules, right? Shouldn’t they ideally have the same behavior as source files that were definitely CJS?

Comment (weswigham) [reply src/compiler/checker.ts:3690]: I mean... So technically we'd probably wanna consider all ambient modules as cjs modules, for compat's sake, problem being there's no ambient module syntax for a definitively esm ambient module, or for having both module types existing at the same name. It's a bit of a thorny issue that I've been hoping to not need to fix until it was truly required, since the reasons to use ambient modules over modules on disk are pretty small.

Comment (andrewbranch) [reply src/compiler/checker.ts:3690]: Module declaration assertions when? 😄

**Review by andrewbranch — APPROVED** [review]
