### PR TITLE
Fix find-all-refs for import("mod").Foo where Foo is a typedef

### LINKED ISSUE #23863: In JS, typedef rename and find-all-refs doesn't work across files
```js
// @Filename: mod1.js
module.exports = { e: 1, m: 1 }
/** @typedef {number} Foo */

// @Filename: use.js
/** @type {import('./mod1').Foo} */
var foo = 12
```

**Expected behavior:**
Renaming `Foo` in use.js should rename it. Find-all-refs on `Foo` in use.js should list all references

**Actual behavior:**
Neither work. However, goto-def does work.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #23863

Needed to fix a few bugs:
* Previously  the import tracker was just ignoring `ImportType` nodes -- added a `Debug.assertNever` to prevent this from happening in the future.
* We need to consider typedef tags as exports in the import tracker after #23723 
* An `ImportType` should be considered a type reference.

Discovered #23879 while working on this.

### CODE REVIEW

**Comment by weswigham** [comment]
> An ImportType should be considered a type reference.

Specifically, an `ImportType` without `typeof` is effectively a type reference. One with `typeof` is effectively a type query.

File: src/services/utilities.ts [hunk 1]
```diff
@@ -179,6 +179,7 @@ namespace ts {
 
         switch (node.parent.kind) {
             case SyntaxKind.TypeReference:
+            case SyntaxKind.ImportType:
```
Comment (weswigham) [inline src/services/utilities.ts]: This should probably only be true if `!(node.parent as ImportTypeNode).isTypeOf`, otherwise it acts like a type query instead.

File: src/services/importTracker.ts [hunk 2]
```diff
@@ -130,6 +133,19 @@ namespace ts.FindAllReferences {
...
+                                // `import("foo").x` named import
+                                directImports.push(direct);
+                            }
+                            else {
+                                // TODO: GH#23879
+                            }
+                            break;
+
+                        default:
+                            Debug.assertNever(direct);
```
Comment (weswigham) [inline src/services/importTracker.ts]: I'd include a helpful message here as the second parameter to `assertNever`, just in case (if the types drift out of sync with reality because of an invalid cast, for example).

File: src/services/utilities.ts (hunk 1 above)
Comment (andy-ms) [reply src/services/utilities.ts]: We do normally consider `typeof` uses to be references though, e.g.:
```ts
const [|x|] = 0;
const y: typeof [|x|] = 0;
```

Comment (weswigham) [reply src/services/utilities.ts]: Will the results still be classified correctly if that's picked up here and not where type queries are looked at?

Comment (andy-ms) [reply src/services/utilities.ts]: There actually isn't a specific place in find-all-references where we look for type queries -- we basically just look for identifiers with the same name and check for a symbol match.

Comment (sheetalkamat) [reply src/services/utilities.ts]: But this function is called from ```getMeaningFromLocation``` so that means we need to handle this irrespectively to avoid any wrong usage being seeping out.
