### PR TITLE
importModuleSpecifierEnding changes .ts string completions to .js

### LINKED ISSUE #44374: importModuleSpecifierEnding = js doesn't apply for autocomplete within import paths
# Bug Report

I have this workspace setting which works great for auto import:

```json
"typescript.preferences.importModuleSpecifierEnding": "js"
```

But when auto completing the path it still does .ts which requires manually changing:

image

### 🔎 Search Terms

importModuleSpecifierEnding

### 🕗 Version & Regression Information

4.3.0-dev.20210503

### PR DESCRIPTION
**Pull request by jessetrinity**
Fixes #44374

### CODE REVIEW

File: src/services/stringCompletions.ts [hunk 1]
```diff
@@ -418,8 +424,19 @@ namespace ts.Completions.StringCompletions {
...
                 }
 
-                const foundFileName = includeExtensions || fileExtensionIs(filePath, Extension.Json) ? getBaseFileName(filePath) : removeFileExtension(getBaseFileName(filePath));
-                foundFiles.set(foundFileName, tryGetExtensionFromPath(filePath));
+                let foundFileName: string;
+                if (includeExtensionsOption === IncludeExtensionsOption.Exclude && !fileExtensionIs(filePath, Extension.Json)) {
+                    foundFileName = removeFileExtension(getBaseFileName(filePath));
+                    foundFiles.set(foundFileName, tryGetExtensionFromPath(filePath));
+                }
+                else if (includeExtensionsOption === IncludeExtensionsOption.ModuleSpecifierCompletion && fileExtensionIs(filePath, Extension.Ts)) {
```
Comment (andrewbranch) [inline src/services/stringCompletions.ts:432]: What we really need, and I’m not sure whether we have (but we might), is a function that maps input file extensions to emitted file extensions. So we would have

- .ts → .js
- .tsx → ? (I don’t know if this is always .js or if we might emit .jsx with `--jsx=preserve`?)
- .mts → .mjs (someday soon)
- .d.ts → `undefined` because it doesn’t get emitted
- .json → .json (only if `--resolveJsonModule`?)
- .js → .js

If we don’t have that function, we need to (a) figure out what the right thing for TSX is and implement it now, and (b) remember to update it for `.mts` and `.cts` if/when we add those.

File: src/services/stringCompletions.ts [hunk 2]
```diff
@@ -370,10 +371,15 @@ namespace ts.Completions.StringCompletions {
         return flatMap(baseDirectories, baseDirectory => getCompletionEntriesForDirectoryFragment(fragment, baseDirectory, extensionOptions, host, exclude));
     }
 
+    enum IncludeExtensionsOption {
```
Comment (andrewbranch) [inline src/services/stringCompletions.ts:374]:
```suggestion
    const enum IncludeExtensionsOption {
```

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/stringCompletions.ts (hunk 1 above)
Comment (jessetrinity) [reply src/services/stringCompletions.ts:432]: Emitter.ts has [`getOutputExtension`](https://github.com/microsoft/TypeScript/blob/b26f77a703b1f4e9e0cb07c02babbd708408beb0/src/compiler/emitter.ts#L113) which does approximately that, but it works on a sourceFile. Since we're just working working with the paths here we probably just want a new similar function that handle the cases we need.

Comment (andrewbranch) [reply src/services/stringCompletions.ts:432]: 👍 in absence of something better, just leave comments on each function (`getOutputExtension`) and the new function saying to keep them in sync with each other.

Comment (andrewbranch) [reply src/services/stringCompletions.ts:432]: Found it: https://github.com/microsoft/TypeScript/blob/fad9122872a4df92050177edb07ee9cf3efd7e35/src/compiler/moduleSpecifiers.ts#L696

I would maybe just export that function so it doesn’t immediately cause merge conflicts with #44501.

Comment (andrewbranch) [reply src/services/stringCompletions.ts:432]: Actually, you might need to refactor it to return `undefined` instead of throwing on unsupported extensions, and move the debug assertions to its caller, or another wrapped version of it. But otherwise I think this function is exactly the thing we were looking for.

File: src/compiler/moduleSpecifiers.ts [hunk 3]
```diff
@@ -687,13 +687,17 @@ namespace ts.moduleSpecifiers {
...
             case Ending.JsExtension:
-                return noExtension + getJSExtensionForFile(fileName, options);
+                return noExtension + getJSExtensionForFileIfApplicable(fileName, options);
             default:
                 return Debug.assertNever(ending);
         }
     }
 
-    function getJSExtensionForFile(fileName: string, options: CompilerOptions): Extension {
+    function getJSExtensionForFileIfApplicable(fileName: string, options: CompilerOptions): Extension {
```
Comment (andrewbranch) [inline src/compiler/moduleSpecifiers.ts:696]: To me this one sounds like the one that never throws. I would suggest naming the undefined-returning one `tryGetJSExtensionForFile` and the throwing one `getJSExtensionForFile`.

File: src/compiler/moduleSpecifiers.ts [hunk 4]
```diff
@@ -687,13 +687,17 @@ namespace ts.moduleSpecifiers {
...
+        return getJSExtensionForFile(fileName, options) ?? Debug.fail(`Extension ${extensionFromPath(fileName)} is unsupported:: FileName:: ${fileName}`);
+    }
+
+    export function getJSExtensionForFile(fileName: string, options: CompilerOptions): Extension | undefined {
         const ext = extensionFromPath(fileName);
```
Comment (andrewbranch) [inline src/compiler/moduleSpecifiers.ts:701]: I thought it was sketchy that this function didn’t return `undefined`, so I looked and found that it too has an undefined-returning counterpart, and this one throws! This may need to be swapped for `tryGetExtensionFromPath` for good measure. This also makes me realize we should have a test that actually returns completions for a non-source-file file extension, like `index.css` or something.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/compiler/moduleSpecifiers.ts (hunk 4 above)
Comment (jessetrinity) [reply src/compiler/moduleSpecifiers.ts:701]: I don't think we even read other extension types from disk, but I think you mean something like

```ts
//@filename: index.css
body {}

//@filename: index.html
<!DOCTYPE html>

//@filename: foo.ts
import "./
```

And expect nothing at the uncompleted string?

Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts]: Hm, I looked at stringCompletions and saw `tryReadDirectory`, so I assumed we were offering everything we could find, with extension substitutions as appropriate. Not sure what’s going on then 🤔

Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts]: You could certainly be seeing an artifact of the fourslash client 😬. Have you checked the behavior against a Real Editor?

Comment (jessetrinity) [reply src/compiler/moduleSpecifiers.ts]: I was pretty sure that `tryReadDirectory` only returned files that matched its `extensions` argument, if provided. I might be misreading though.

Comment (jessetrinity) [reply src/compiler/moduleSpecifiers.ts]: either way, updated to not use the throwing variant :)

Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts]: Ah, I missed that parameter 🤦‍♂️ 

It might actually be nice to allow all extensions here in the future, since we can no longer seriously claim to believe we’re in a world where people only import things we know how to analyze. This doesn’t even account for `declare module "*.css"` pattern ambient module declarations. But that’s for another day. Thanks!

**Review by andrewbranch — APPROVED** [review]

File: src/compiler/moduleSpecifiers.ts (hunk 4 above)
Comment (jessetrinity) [reply src/compiler/moduleSpecifiers.ts]: Oh geez TIL. Is that a [wildcard module declaration](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations)?
