### PR TITLE
Revert changes to matchFiles/readDirectory made since 4.3

### LINKED ISSUE #46577: 4.5.0-dev.20211029: Does not throw error `TS5056: Cannot write file '/to/file/path' because it would be overwritten by multiple input files.`
# Bug Report

### 🔎 Search Terms

`TS5056`, `because it would be overwritten by multiple input files`

### 🕗 Version & Regression Information

- This changed between versions  4.4.4 and `4.5.0-dev.20211029`

### ⏯ Playground Link

This bug cannot be reproduced in Playground.

### 💻 Code

Sorry this bug cannot be reproduced as as simple code. Instead of I've created the repository to reproduce this.

https://github.com/sosukesuzuki-sandbox/ts-4.5-bug-reproduce

### 🙁 Actual behavior

Does not throw error `TS5056: Cannot write file '/to/file/path' because it would be overwritten by multiple input files.`

### 🙂 Expected behavior

Throw error `TS5056: Cannot write file '/to/file/path' because it would be overwritten by multiple input files.`

### PR DESCRIPTION
**Pull request by andrewbranch**
Reverts #44710, #46086, and #46673.
Fixes #46577.

I have discovered that `ts.matchFiles`/`ts.sys.readDirectory` does a lot of extremely confusing things, none of which are documented and some of which are probably bugs, but nobody seemed to notice until we started messing with it, so I’m reverting back to our 4.3 state. I will post my findings of what’s weird even in 4.3 so we can decide if any of it is worth fixing (done: #46788).

### CODE REVIEW

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -1620,12 +1619,6 @@ namespace ts {
                             options = { persistent: true };
                         }
                     }
-
```
Comment (amcasey) [inline src/compiler/sys.ts:1623]: I understand a full revert is safer at this point in the cycle, but it would be nice to keep (or quickly restore) this part of the change.

File: src/testRunner/unittests/publicApi.ts [hunk 2]
```diff
@@ -182,34 +182,3 @@ describe("unittests:: Public APIs:: getChild* methods on EndOfFileToken with JSD
     assert.equal(endOfFileToken.getChildCount(), 1);
     assert.notEqual(endOfFileToken.getChildAt(0), /*expected*/ undefined);
 });
-
-describe("unittests:: Public APIs:: sys", () => {
```
Comment (amcasey) [inline src/testRunner/unittests/publicApi.ts:186]: Worth keeping?

**Review by amcasey — APPROVED** [review]
Will this re-break the RWC tests?

File: src/testRunner/unittests/publicApi.ts (hunk 2 above)
Comment (andrewbranch) [reply src/testRunner/unittests/publicApi.ts:186]: We’ll bring it back when we decide what the correct thing to assert is

File: src/compiler/sys.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/sys.ts]: Can you review the latest commit and see if this is what you had in mind?

**Comment by amcasey** [comment]
LGTM

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5
