### PR TITLE
Fixes JSDoc @type function with variable args is interpreted incorrectly

### LINKED ISSUE #44386: JSDoc @type function with variable args is interpreted incorrectly
# Bug Report

### 🔎 Search Terms

jsdoc varargs @type function

### 🕗 Version & Regression Information

4.2.4

### 💻 Code

This is in a .js file:
```
/**
 * @type {function(boolean, string, ...*):void}
 */
const warn = "anything" // the value doesnt matter, TS gets the type from the comment
```

When I call this in a .ts file VSCode and WebStorm underlines it, saying that the 3rd parameter is necessary.:

image

The strange thing is that the generated `d.ts` file contains the correct code: `export var warn: (arg0: boolean, arg1: string, ...args: any[]) => void;`

So the issue is that the live type checker (the language server?) types the last rest param to `...[any]` instead of `...any` or  `...any[]`

### 🙁 Actual behavior

error in the IDE (see screenshot). Also it works fine if there is one argument besides the rest arg.

### 🙂 Expected behavior

no error in the IDE, it uses the same signature as the `.d.ts` file.

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #44386

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]

File: tests/cases/fourslash/jsDocVariadicType.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+///<reference path="fourslash.ts" />
+
+// @allowJs: true
+// @checkJs: true
+
+// @Filename: dummy.js
+//// /**
+////  * @type {function(boolean, string, ...*):void}
+////  */
+//// const foo = function (a, b, ...r) { };
```
Comment (sandersn) [inline tests/cases/fourslash/jsDocVariadicType.ts:10]: Does this error repro from the command line `tsc`? It should, and if so, I'd much prefer a test in `tests/conformance/jsdoc/`. Without the fix there should be a new .errors.txt baselines, with the fix there shouldn't be.

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks good, but I'd like a compiler test instead of a fourslash one.

File: tests/cases/fourslash/jsDocVariadicType.ts (hunk 1 above)
Comment (jeanp413) [reply tests/cases/fourslash/jsDocVariadicType.ts]: Thanks for pointing that out, I pushed a commit moving the test to conformance

**Review by sandersn — APPROVED** [review]
