### PR TITLE
Handle noEmit and noEmitOnError with SemanticDiagnosticsBuilder

### LINKED ISSUE #40808: Performance regression in 4.0 with semantics-only `createWatchProgram`?
The wiki here has [a page that outlines ways to programmatically create a watched build](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher), and suggests that `createSemanticDiagnosticsBuilderProgram` is likely preferable to `createEmitAndSemanticDiagnosticsBuilderProgram` for use cases that aren't interested in emit.

The `ember-cli-typescript` package uses the APIs outlined in that wiki page to integrate typechecking results into Ember CLI builds, and [there've been several reports](https://github.com/typed-ember/ember-cli-typescript/issues/1278) of slower re-checks after a file change from folks that have updated to `typescript@4`.

**TypeScript Version:**
 - 3.9.7 (works as expected)
 - 4.0.3 (exhibits slowdown)
 - 4.1.0-dev.20200928 (exhibits slowdown)

**Search Terms:**
 - `createWatchProgram`
 - `createSemanticDiagnosticsBuilderProgram`
 - 4.0 performance

**Code**

```ts
const ts = require('typescript');
const host = ts.createWatchCompilerHost(
  'tsconfig.json',
  { noEmit: true },
  ts.sys,
  ts.createSemanticDiagnosticsBuilderProgram
);

ts.createWatchProgram(host);
```

**Expected behavior:**
Re-checks are at least as fast with `createSemanticDiagnosticsBuilderProgram` as with its counterpart that tracks emit.

**Actual behavior:**
In a project that takes on the order of 15s to typecheck at startup, re-checking takes less than 1s with the above invocation in 3.9, as well as in 4.0 and the most recent 4.1 nightly when using `createEmitAndSemanticDiagnosticsBuilderProgram`.

When using `createSemanticDiagnosticsBuilderProgram` in 4.0 and 4.1, though, re-checking consistently takes around 5s.

### PR DESCRIPTION
**Pull request by sheetalkamat**
This ensures that diagnostics are checked through cache/or cached in builder instead of getting it from Program when emit is called and its going to fail in these two scenarios. We already do this for `EmitAndSemanticDiagnosticsBuilder`
Note that actual emit when succeeds on `SemanticDiagnosticsBuilder` is going to be redirected to program as intended as the emit is not tracked by the builder and would need to typecheck file before emitting as always but this ensures that cases where it fails to emit are handled.
Fixes #40808

### CODE REVIEW

**Review by sandersn — APPROVED** [review]
Looks reasonable although I'm not familiar with this area of the code.

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -1019,31 +1019,56 @@ namespace ts {
...
+                !state.compilerOptions.noEmit &&
+                state.compilerOptions.noEmitOnError) {
+                restorePendingEmitOnHandlingNoEmitSuccess = true;
+                savedAffectedFilesPendingEmit = state.affectedFilesPendingEmit && state.affectedFilesPendingEmit.slice();
+                savedAffectedFilesPendingEmitKind = state.affectedFilesPendingEmitKind && new Map(state.affectedFilesPendingEmitKind);
+                savedAffectedFilesPendingEmitIndex = state.affectedFilesPendingEmitIndex;
+            }
+
+            if (kind === BuilderProgramKind.EmitAndSemanticDiagnosticsBuilderProgram)
                 assertSourceFileOkWithoutNextAffectedCall(state, targetSourceFile);
```
Comment (sheetalkamat) [inline src/compiler/builder.ts:1041]:
```suggestion
            if (kind === BuilderProgramKind.EmitAndSemanticDiagnosticsBuilderProgram) {
                assertSourceFileOkWithoutNextAffectedCall(state, targetSourceFile);
            }
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.0
