### PR TITLE
Report errors correctly in watch mode by invalidating errors from files referencing modules that export from changed file

### LINKED ISSUE #24986: Incremental compilation does not catch type errors in deep imports
It seems watch mode does not check for type errors induced by changes to types in deep imports.
A restart is required to catch these errors.

***TypeScript Version:**** 
Version 3.0.0-dev.20180609 on Windows 10

**Search Terms:** 
watch, incremental, deep

**Code**
Three files> a.ts, b.ts and c.ts + empty tsconfig.json file to please tsc.
```ts
// a.ts:
import {B} from './b'; 
let b = new B(); 
console.log(b.c.d);

// b.ts:
import {C} from './c';
export class B
{
    c = new C();
}

// c.ts:
export class C
{
    d = 1;
}

```

**Expected behavior:**
Running tsc --watch and making a type error in a.ts by inducing a change in c.ts should result in a type error in the console.

e.g. changing 
```ts
    d = 1;
```
to 
```ts
    d2 = 1;
```
should result in a type error in a.ts:
a.ts:3:17 - error TS2339: Property 'd' does not exist on type 'C'.

**Actual behavior:**
Running tsc --watch and making a type error in a.ts by inducing a change in c.ts does not result in a type error. Instead, the compiler happily writes:
Found 0 errors. Watching for file changes.

Restarting tsc in watch mode results in the expected type error:
a.ts:3:17 - error TS2339: Property 'd' does not exist on type 'C'.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #24986

The idea here is that when we calculate the declaration emit output for the file to see if it is valid, we also store the module specifiers and import type nodes written that are needed as the exported members are referenced from those modules. 

The first iteration would not have valid result but we would anyways have all files as changed in that, But during second iteration if file say c.ts is changed, we look for files that are exporting c.ts and then look for the files that reference these modules. So in test scenario of #24986, when c.ts is changed => we find that b.ts has exported module c.ts so any file that references b.ts need to invalidate the semantic diagnostics. (note we don't need to emit that file, just the diagnostics since that's the only change.)

Better approach instead of #25534

### CODE REVIEW

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -30,10 +30,18 @@ namespace ts {
...
+         */
+        currentAffectedFilesExportedModulesMap: BuilderState.ComputingExportedModulesMap | undefined;
         /**
          * Already seen affected files
          */
         seenAffectedFiles: Map<true> | undefined;
+        /**
+         * True if the semantic diagnostics were copied from the old state
+         */
+        semanticDiagnosticsFromOldStateFiles?: number;
```
Comment (weswigham) [inline src/compiler/builder.ts]: This `number` isn't used except as a counting semaphore (it only increments and decrements) and it has a lot of debug asserts around that - this leads me to believe it should more naturally be a `Map<true>` instead. (And then truthiness checks would be on `semanticDiagnosticsFromOldStateFiles.size` instead) Although changing the type of `semanticDiagnosticsPerFile`  from `Map<ReadonlyArray<Diagnostic>>` to `Map<{ fromOldState: boolean, diagnostics: ReadonlyArray<Diagnostic> }>` could be even better and make even more of the sanity checking assertions unnecessary.

File: src/compiler/types.ts [hunk 2]
```diff
@@ -2624,6 +2624,14 @@ namespace ts {
         /* @internal */ pragmas: PragmaMap;
         /* @internal */ localJsxNamespace?: __String;
         /* @internal */ localJsxFactory?: EntityName;
+
+        /*@internal*/ getExportedModulesFromDeclarationEmit?(): ExportedModulesFromDeclarationEmit;
+    }
+
+    /*@internal*/
+    export interface ExportedModulesFromDeclarationEmit {
+        exportedModuleSpecifiers: ReadonlyArray<StringLiteralLike>;
```
Comment (weswigham) [inline src/compiler/types.ts]: From what I can tell, both of these just get mapped to a path eventually, via lookup (string ->) symbol -> sourcefile -> path. Rather than storing both symbols and string literals here, I'd rather we just stored the paths for all kinds directly. Minimally, just one field with symbols for both (from which path can be easily found) - having two fields for different levels of processing of essentially the same thing seems somewhat extraneous. This may necessitate exposing something checker-related on the `EmitResolver`.

Comment (sheetalkamat) [reply src/compiler/types.ts]: I think making it list of Symbols makes sense. ( though they get converted to paths, I would rather do that work in builder since it is shared with how we handle the imports in the module)

**Comment by sheetalkamat** [comment]
@weswigham can you please take a look again.
