### PR TITLE
fix(33511): React Native <Text> component quick fix weird import suggestion

### LINKED ISSUE #33511: React Native <Text> component quick fix weird import suggestion
*Templated added by @mjbvz 

**TypeScript Version**: 3.7.0-dev.20190919

**Search terms**
- React
- quick fix 
- add missing import

*original issue below*

--- 

- VSCode Version: 1.38.1 and 1.39.0
- OS Version: macOS

Very weird issue... In React Native if you write `<Text></Text>` and you use `Quick Fix...` on the first `<Text>` you will get `Import default 'React' from "react"`, but if you use `Quick Fix...` on the second `</Text>` (closing) you will get `Import 'Text' from module "react-native"` (which is correct).

It's hard to describe the issue so these screenshots will explain everything.

Screen Shot 2019-09-18 at 19 33 00
Screen Shot 2019-09-18 at 19 33 04

I expect to get the same behavior like with `</Text>` (closing) if I use Quick Fix on the `<Text>` (opening).

Steps to Reproduce:

1. `yarn add react react-native @types/react @types/react-native`
2. Create `tsconfig.json` with the content below.
3. Create new file `App.tsx` with the content below.
4. Move cursor to the first `<Text>` and press `CMD+.` or use `Quick Fix...` from Command Palette.

tsconfig.json
```
{
  "compilerOptions": {
    "jsx": "react-native",
    "lib": ["es6"],
    "esModuleInterop": true,
    "moduleResolution": "node"
  }
}
```

package.json
```
{
  "dependencies": {
    "@types/react": "^16.9.2",
    "@types/react-native": "^0.60.15",
    "react": "^16.9.0",
    "react-native": "^0.60.5"
  }
}
```

App.tsx
```
import React from 'react';

function App() {
  return <Text>Hello, World!</Text>;
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #33511

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -485,12 +485,7 @@ namespace ts.codefix {
 
     function getFixesInfoForNonUMDImport({ sourceFile, program, cancellationToken, host, preferences }: CodeFixContextBase, symbolToken: Identifier): FixesInfo | undefined {
         const checker = program.getTypeChecker();
-        // If we're at `<Foo/>`, we must check if `Foo` is already in scope, and if so, get an import for `React` instead.
-        const symbolName = isJsxOpeningLikeElement(symbolToken.parent)
-            && symbolToken.parent.tagName === symbolToken
-            && (isIntrinsicJsxName(symbolToken.text) || checker.resolveName(symbolToken.text, symbolToken, SymbolFlags.All, /*excludeGlobals*/ false))
```
Comment (sandersn) [inline src/services/codefixes/importFixes.ts:491]: The new code makes sense, but I don't see why the old code was broken; for the `<Text>` case, I thought that `Text` was not imported, so `checker.resolveName` should return `undefined` (and also `Text` is not an intrinsic, right?). What am I missing here?

Comment (a-tarasyuk) [reply src/services/codefixes/importFixes.ts:491]: @sandersn Thanks for the review 👍! 

If I remember correctly I followed the following steps:
1. Need to handle names from two types of JSX tags (open and close)
1.1. Need to check if there is React if no then need to import `React` (`checker.resolveName(jsxNamespace...)`)
2. If there is React, need to return the name

The previous version just returns React even it exists and does it only for `JsxOpeningLikeElement`.  What do you think does that make sense? Or there is a better way?

Comment (sandersn) [reply src/services/codefixes/importFixes.ts:491]: Well, the previous version only returns React if it *can* resolve `Text` via `checker.resolveName(symbolToken.text,...)`. This seems right, but clearly it produces the wrong results. I just don't understand why.

Comment (a-tarasyuk) [reply src/services/codefixes/importFixes.ts:491]: @sandersn The problem was with `JsxOpeningLikeElement`, which was handled in a previous version :). `JsxClosingElement` worked fine, because the following condition related only to `JsxOpeningLikeElement`. As I understood this condition needs to import default `React` if a name is JSX tag. 
```ts
isJsxOpeningLikeElement(symbolToken.parent) &&
    symbolToken.parent.tagName === symbolToken && 
    (isIntrinsicJsxName(symbolToken.text) ||
     checker.resolveName(symbolToken.text, symbolToken, SymbolFlags.All, /*excludeGlobals*/ false))
```

In the new version, if a token related to JSX, and only if there is no React, we suppose a user needs to import Rect first, otherwise return name. 

```ts
<[|Text|]></[|Text|]> // QF: [there is no React] Import React
```

```ts
import React from 'react'
<[|Text|]></[|Text|]> // QF: [there is React] Import Text
```

```ts
import React from 'react'
import { Text } from 'react-native'
<Text></Text>
```

Comment (a-tarasyuk) [reply src/services/codefixes/importFixes.ts:491]: @sandersn is it answer on your question?

Comment (a-tarasyuk) [reply src/services/codefixes/importFixes.ts:491]: For the `JsxOpeningLikeElement`

```ts
checker.resolveName(symbolToken.text, symbolToken, SymbolFlags.All, /*excludeGlobals*/ false))
```

resolves `Text` and **returns** `jsxNamespace` not `Text`, which causes 



I changed this to check if `jsxNamespace` was added, otherwise use the name

Comment (sandersn) [reply src/services/codefixes/importFixes.ts:491]: I see. I don't understand how `checker.resolveName` is able to resolve `Text` without it being imported. (That's why I thought that it would return `undefined`.)

Comment (a-tarasyuk) [reply src/services/codefixes/importFixes.ts:491]: @sandersn I suppose `/*excludeGlobals*/ false` makes it possible.
