### PR TITLE
Ensure projects are updated for find all references

### LINKED ISSUE #52316: Could not find source file error in find all references in 'remotion'
Issue found in https://github.com/microsoft/TypeScript/issues/52253#issuecomment-1383261965.

```
Error: Could not find source file: '/mnt/ts_downloads/remotion/packages/core/src/loading-indicator.tsx'.
```

</details>

```
Req #524 - references
    at getValidSourceFile (/typescript-5.0.0-dev.20230115/lib/tsserver.js:133833:21)
    at Object.findReferences (/typescript-5.0.0-dev.20230115/lib/tsserver.js:134267:117)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:174396:43
    at searchPosition (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174538:28)
    at getPerProjectReferences (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174515:32)
    at getReferencesWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174388:29)
    at IOSession.getReferences (/typescript-5.0.0-dev.20230115/lib/tsserver.js:176278:24)
    at references (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174810:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177286:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177336:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230115/lib/tsserver.js:178787:14)
```
That is a filtered view of the text. To see the raw error text, go to RepoResults3/remotion-dev.remotion.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":521,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx"}},"skipDestructiveCodeActions":false}}
{"seq":522,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx"}}
{"seq":523,"type":"request","command":"updateOpen","arguments":{"changedFiles":[{"fileName":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx","textChanges":[{"newText":" //comment","start":{"line":1,"offset":50},"end":{"line":1,"offset":50}}]}],"closedFiles":[],"openFiles":[]}}
{"seq":524,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/packages/cli/src/editor/components/MenuBuildIndicator.tsx","line":4,"offset":2}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/remotion-dev/remotion --recurse-submodules</code></li>
<li>In dir <code>remotion</code>, run <code>git reset --hard 170c45549eef651cc3c4796ab36ebbbbe25ad394</code></li>
  <li>In dir <code>remotion</code>, run <code>pnpm install --no-frozen-lockfile --prefer-offline --ignore-scripts --reporter=silent</code></li>
<li>Back in the initial folder, download <code>RepoResults3/remotion-dev.remotion.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./remotion ./remotion-dev.remotion.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #52316.

There are a few places inside the find all references workflow that looks for references across projects, where we have a file `A` and a project `P`, and we assume that file `A` is contained in project `P`. However, the project could be outdated (i.e. it changed but we haven't updated it yet), and in some situations we were using this outdated information to determine that file `A` is contained in project `P`, when it no longer is. This would lead to a crash, because when later in the code we try to validate that file `A` is contained in project `P`, `P` is finally updated, and no longer has file `A`, so we throw an exception saying we couldn't find file `A`.

The fix in this PR is to ensure all projects are updated at the start of the find all references workflow, so that we always use updated information about files and containing projects.

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -954,14 +954,14 @@ export function createModuleResolutionLoader(
 ): ResolutionLoader<StringLiteralLike, ResolvedModuleWithFailedLookupLocations, SourceFile> {
     return {
         nameAndMode: moduleResolutionNameAndModeGetter,
-        resolve: (moduleName, resoluionMode) => resolveModuleName(
```
Comment (gabritto) [inline src/compiler/program.ts:957]: This is just fixing a typo I found while debugging.

**Comment by DanielRosenwasser** [comment]
I'd be curious to know whether larger project references codebases see any regressions as a result of this.

File: tests/baselines/reference/tsserver/projectReferences/finding-local-reference-doesnt-load-ancestor/sibling-projects.js [hunk 2]
```diff
@@ -265,58 +329,22 @@ FsWatches::
   {}
 /user/username/projects/solution/tsconfig.json:
   {}
+/user/username/projects/solution/services/tsconfig.json:
+  {}
 
 FsWatchesRecursive::
 
-Info 29   [00:01:12.000] Finding references to /user/username/projects/solution/compiler/program.ts position 110 in project /user/username/projects/solution/compiler/tsconfig.json
```
Comment (gabritto) [inline tests/baselines/reference/tsserver/projectReferences/finding-local-reference-doesnt-load-ancestor/sibling-projects.js:271]: These baselines changed in a different way than the rest, but what I think is going on is that before we had an `updateGraphWorker` call being logged inside the call to `Finding references to /user/username/projects/solution/compiler/program.ts position 110 in project /user/username/projects/solution/compiler/tsconfig.json`, but now that update is being done and logged above, in the previous call to find all references, so it doesn't show here because the update happens earlier now.

**Review by gabritto — COMMENTED** [review]
I reviewed the baselines changes, and almost all changes are because we now log a call to `ensureProjectForOpenFiles` right before the calls/logging of find all references, since `ensureProjectForOpenFiles` is now called as part of ensuring the projects are up to date before doing the find all references work.
This also causes several diffs that are increments the sequence numbering of the `Info` log messages.

I left a comment on the baseline change that doesn't follow this pattern, but I think the changes make sense.

**Comment by gabritto** [comment]
@typescript-bot perf test this

File: src/server/session.ts [hunk 3]
```diff
@@ -1973,7 +1973,7 @@ export class Session<TMessage = string> implements EventSender {
 
     private getReferences(args: protocol.FileLocationRequestArgs, simplifiedResult: boolean): protocol.ReferencesResponseBody | readonly ReferencedSymbol[] {
         const file = toNormalizedPath(args.file);
-        const projects = this.getProjects(args);
+        const projects = this.getProjects(args, /*getScriptInfoEnsuringProjectsUptoDate*/ true);
```
Comment (sheetalkamat) [inline src/server/session.ts:1976]: I think instead you want to guard against the project being upto date at the usage site. The projects can become dirty at any moement (eg when new project is created because of which open file goes from inferred project to that configured/inferred project - as part of finding original location of a file). This will also avoid having to update all projects and confine the updates to affected oprojects.

You want to use `updateIfDirty`

File: tests/baselines/reference/tsserver/projectReferences/finding-local-reference-doesnt-load-ancestor/sibling-projects.js (hunk 2 above)
Comment (sheetalkamat) [reply tests/baselines/reference/tsserver/projectReferences/finding-local-reference-doesnt-load-ancestor/sibling-projects.js:271]: This is example of why you done want to update all projects.. your solution (eg in our case we could be working on checker) can containing many projects but local find all ref should not load other projects (eg local checker function shouldnt load unittests or server or other projects)

File: src/server/session.ts (hunk 3 above)
Comment (gabritto) [reply src/server/session.ts:1976]: I thought about that, but right here in this call to `this.getProjects(args)`, we already might be using outdated information, because we use the argument's file's `scriptInfo.containingProjects` to decide what projects we pass down to `getReferencesWorker`, so I thought we needed to use the updated information here. Or is it ok to use outdated information here when picking the projects to pass to `getReferencesWorker`, because we will somehow make up for it inside `getReferencesWorker`?

Just to make sure I understand, are you saying that projects can become dirty during the find all references work?
And by "project being up to date at the usage site", do you mean when we enqueue a project+location, when we dequeue a project to use it, or something else?

Comment (sheetalkamat) [reply src/server/session.ts:1976]: > I thought about that, but right here in this call to this.getProjects(args), we already might be using outdated information, because we use the argument's file's scriptInfo.containingProjects to decide what projects we pass down to getReferencesWorker, so I thought we needed to use the updated information here. Or is it ok to use outdated information here when picking the projects to pass to getReferencesWorker, because we will somehow make up for it inside getReferencesWorker?

Yes its ok to not update all the projects as thats lot of work. You want to start with whatever projects are there and then go from there.

>do you mean when we enqueue a project+location, when we dequeue a project to use it, or something else?

Yes at the time of dequeue you want to check if the project can really be used or not. (based on updateIfDirty and file being still part of that project)

File: src/testRunner/unittests/services/findAllReferences.ts [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+    prop: number;
+}
+const bar: Bar = {
+    prop: 1
+}
+`
+            },
+        ];
+        const host = createServerHost(files);
+        const session = createSession(host);
```
Comment (sheetalkamat) [inline src/testRunner/unittests/services/findAllReferences.ts:77]: Can you instead baseline the tsserver log. 
eg of baseline: https://github.com/microsoft/TypeScript/blob/main/src/testRunner/unittests/tsserver/configuredProjects.ts#L55

File: src/testRunner/unittests/services/findAllReferences.ts [hunk 5]
```diff
@@ -128,13 +128,14 @@ const bar: Bar = {
         assert(loadingIndicatorScriptInfo.containingProjects.find(p => p.projectName === "/packages/babel-loader/tsconfig.json"));
```
Comment (sheetalkamat) [inline src/testRunner/unittests/services/findAllReferences.ts:128]:
```suggestion
```

Since you have baseline this is present as part of the log.

**Review by sheetalkamat — APPROVED** [review]

**Comment by gabritto** [comment]
@typescript-bot perf test this
