### PR TITLE
Handle the new js binding element alias symbols in JS declaration emit

### LINKED ISSUE #41182: Re-exporting class on commonjs - JS code + declaration emit leads to tsc crash
**TypeScript Version:**  4.1.0-dev.20201021

**Search Terms:**
Unhandled alias declaration kind in symbol serializer

**Code**
https://gist.github.com/Bnaya/ccb802d892508f3f4ebd81e3350eea05
run `yarn tsc4p1`

**Expected behavior:**
Should compile and emit types

**Actual behavior:**
tsc crash with:
```
/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:86657
                throw e;
                ^

Error: Debug Failure. Unhandled alias declaration kind in symbol serializer!
Node 198 was unexpected.
    at serializeAsAlias (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:40361:45)
    at serializeSymbolWorker (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:40082:25)
    at serializeSymbol (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39987:38)
    at /Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39972:29
    at Map.forEach (<anonymous>)
    at visitSymbolTable (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39971:81)
    at symbolTableToDeclarationStatements (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:39847:17)
    at /Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:38395:106
    at withContext (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:38422:37)
    at Object.symbolTableToDeclarationStatements (/Users/bnaya/.npm/_npx/16389/lib/node_modules/typescript/lib/tsc.js:38395:28)
error Command failed with exit code 1.
```
**Related Issues:** 
#37832

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #41182

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6783,6 +6783,37 @@ namespace ts {
                     const targetName = getInternalSymbolName(target, verbatimTargetName);
                     includePrivateSymbol(target); // the target may be within the same scope - attempt to serialize it first
                     switch (node.kind) {
+                        case SyntaxKind.BindingElement:
+                            if (node.parent?.parent?.kind === SyntaxKind.VariableDeclaration) {
+                                // const { SomeClass } = require('./lib');
+                                const specifier = getSpecifierForModuleSymbol(target.parent || target, context); // 'y'
```
Comment (sandersn) [inline src/compiler/checker.ts:6789]:
```suggestion
                                const specifier = getSpecifierForModuleSymbol(target.parent || target, context); // './lib'
```

I think?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6783,6 +6783,37 @@ namespace ts {
...
+                                    )])),
+                                    factory.createStringLiteral(specifier)
+                                ), ModifierFlags.None);
+                                break;
+                            }
+                            // At present, the below case should be entirely unhit, as, generally speaking, the below case is *usually* bound
+                            // such that the `BinaryExpression` is the declaration rather than the specific, nested binding element
+                            // (because we don't seek to emit an alias in these forms yet). As such, the `BinaryExpression` switch case
+                            // will be what actually handles this form. _However_, in anticipation of binding the below with proper
+                            // alias symbols, I'm _pretty comfortable_ including the case here, even though it is not yet live.
```
Comment (sandersn) [inline src/compiler/checker.ts:6805]: were you able to test this locally to see whether the code worked? 

(I'm not a fan of adding future-code because it tends to be 98% correct, but the first person to rely on it has no idea which code needs to be fixed.)

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6783,6 +6783,37 @@ namespace ts {
...
                     switch (node.kind) {
+                        case SyntaxKind.BindingElement:
+                            if (node.parent?.parent?.kind === SyntaxKind.VariableDeclaration) {
+                                // const { SomeClass } = require('./lib');
+                                const specifier = getSpecifierForModuleSymbol(target.parent || target, context); // 'y'
+                                addResult(factory.createImportDeclaration(
+                                    /*decorators*/ undefined,
+                                    /*modifiers*/ undefined,
+                                    factory.createImportClause(/*isTypeOnly*/ false, /*name*/ undefined, factory.createNamedImports([factory.createImportSpecifier(
+                                        (node as BindingElement).propertyName && isIdentifier((node as BindingElement).propertyName!) ? factory.createIdentifier(idText((node as BindingElement).propertyName as Identifier)) : undefined,
```
Comment (sandersn) [inline src/compiler/checker.ts:6794]: can you make this line shorter? just binding `const propertyName = (node as BindingElement).propertyName` should work:

```suggestion
                                        propertyName && isIdentifier(propertyName) ? factory.createIdentifier(idText(propertyName)) : undefined,
```

**Review by sandersn — APPROVED** [review]
Some style suggestions and one question about how tested the speculative code is.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:6805]: Today we bind
```
module.exports = { SomeClass }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ // this node as the `SomeClass` alias symbol's declaration
```
while in the future we probably
```
module.exports = { SomeClass }
                   ^^^^^^^^^ // should bind this node as the `SomeClass` alias symbol's declaration
```
because as it stands today, if I write
```
module.exports = { SomeClass, SomeClass2 }
```
both the `SomeClass` and `SomeClass2` symbols have the same declaration (the whole binary expression), which probably does bad things to some LS features (like rename?).

This small branch of code (the comment is bigger) will handle if/when we bind to the individual `BindingElement` instead. I figured adding it while I was here would be better, since we evidently forgot to handle serialization when we changed how aliases were bound once already. 😛

Comment (sandersn) [reply src/compiler/checker.ts:6805]: Yep, fair enough =)

**Review by sandersn — APPROVED** [review]
