### PR TITLE
fix(51100): ensure tsserver shuts down when parent process is killed

### LINKED ISSUE #51100: tsserver doesn't shut itself down when the parent process is killed
# Bug Report

When `tsserver.js` is started as a child process with `--useNodeIpc` command line included and the parent process is killed (with `SIGKILL` for example), the child process does not shutdown.

I have only tested this on recent 4.8.4 typescript version but I'm assuming that this issue exists since the `--useNodeIpc` flag was introduced in 4.6.0.

To reproduce this "in the wild" one can start VSCode, open some TS project to trigger typescript service initialization and then kill the parent of the tsserver process which is an extension process:

194655787-e7f1c16f-069e-4bf5-8c7a-6114c55bac19

The tsserver process(es) keep running in the background.

### 🔎 Search Terms

tsserver ipc

### 🕗 Version & Regression Information

- This changed between versions 4.5.5 and 4.6.0

### 🙁 Actual behavior

The child `tsserver` process exits after parent process is killed.

### 🙂 Expected behavior

The child `tsserver` process keeps running in the background.

### PR DESCRIPTION
**Pull request by rchl**
When using IPC channel (`--useNodeIpc`) for communicating with tsserver, the child tsserver process did not shut down on parent process disconnecting (for example due to it being killed).

Call `exit()` on IPC disconnect, same as stdio-based communication does when pipe to the parent process is destroyed.

~~Initially I've moved the `exit` implementation from `IOSession` to the base `Session` to avoid having it duplicated in `IOSession` and `IpcIOSession` but changed so that implementations are duplicated after @sheetalkamat's [comment](https://github.com/microsoft/TypeScript/issues/51100#issuecomment-1272158840). It's unfortunate that this creates duplication that could potentially go out of sync. I guess potentially there could be intermediary class that have this shared logic but that might be overkill.~~
EDIT: `IpcIOSession` inherits `IOSession` so we don't have to duplicate it.

Fixes #51100

### CODE REVIEW

File: src/tsserver/nodeServer.ts [hunk 1]
```diff
@@ -779,10 +779,21 @@ namespace ts.server {
                 return JSON.stringify(message, undefined, 2);
             }
 
+            public exit() {
+                this.logger.info("Exiting...");
+                this.projectService.closeLog();
+                tracing?.stopTracing();
+                process.exit(0);
+            }
```
Comment (sheetalkamat) [inline src/tsserver/nodeServer.ts:787]:
```suggestion
```
Given ` IpcIOSession extends IOSession` we dont need to duplicate this. I think the missing piece was onDisconnect which you have added. Can you pls check if things are working with just that. Thanks

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/tsserver/nodeServer.ts (hunk 1 above)
Comment (rchl) [reply src/tsserver/nodeServer.ts:787]: That's perfect, I've totally missed this fact.
Yes, fix works after removing the override.

**Review by sheetalkamat — APPROVED** [review]
