### PR TITLE
Destructuring declaration prefers type annotation type

### LINKED ISSUE #16970: Destructured argument default value is not type checked
**TypeScript Version:**  2.4.1

**Code**

```ts
function test(n: number,
	{
		method = 'z'
	}: {
		method?: 'x' | 'y',
	} = {
		method: 'y'
	})
{
	console.log('test', n, method);
}

test(1);
test(2, {});
```

**Expected behavior:**

Compile error: `z` is not a possible value for `method`'s type.

**Actual behavior:**

Prints:
test 1 y
test 2 z

### PR DESCRIPTION
**Pull request by sandersn**
Previously, getTypeForBindingElement would always union the declaration's type and the type of the default initializer. Now, if the declaration has a type annotation, it does not union with the initializer type. The type annotation's type is the one used.

Fixes #16970, which was broken by #10577. This is a refinement of #10577 in that it checks for a type annotation on the declaration before unioning  types.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4525,11 +4525,19 @@ namespace ts {
...
             }
-            return declaration.initializer ?
+            return declaration.initializer && !parentDeclarationHasTypeAnnotation(declaration) ?
                 getUnionType([type, checkExpressionCached(declaration.initializer)], UnionReduction.Subtype) :
                 type;
         }
 
+        function parentDeclarationHasTypeAnnotation(binding: BindingElement) {
+            let node: Node = binding;
+            while (node.parent && isBindingPattern(node.parent)) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: `node.parent` test should be unnecessary.
Following is a bit more strongly typed (no need to test `couldHaveType`):
```ts
let node = binding.parent;
while (isBindingElement(node.parent)) {
    node = node.parent.parent;
}
return !!node.parent.type;
```

But actually, shouldn't we no longer access `.type` and use `getEffectiveTypeAnnotationNode` instead?

Comment (sandersn) [reply src/compiler/checker.ts]: Good catch on getEffectiveTypeAnnotationNode!

Unfortunately, I tried your proposed change and `node` ends up 1-too-high after the loop -- that is, it's the node above the ParameterDeclaration in the tests below, so `node.parent.type` ends up looking for the type two nodes above the ParameterDeclaration. Also I still had to use `Node` as the type for binding.parent, since `node.parent.parent` is a big union type that isn't assignable to BindingPattern. The elaboration points out that CallSignatureDeclaration, at least, is wrong.

I did work around the 2-too-high problem by tracking the previous parent on each iteration:

```ts
            let node: Node = binding.parent;
            let decl = binding.parent.parent;
            while (isBindingPattern(node)) {
                decl = node.parent;
                node = node.parent.parent;
            }
            return !!getEffectiveTypeAnnotationNode(decl);
```

But this looks worse to me than the original.

Comment (andy-ms) [reply src/compiler/checker.ts]: That can't be right -- if `node.parent.parent` is the node *above* the `ParameterDeclaration`, then `node.parent` must be the `ParameterDeclaration`. But we just tested `isBindingElement(node.parent)`.

Following passed tests when I tried it:
```ts
function parentDeclarationHasTypeAnnotation(binding: BindingElement) {
    let node = binding.parent;
    while (isBindingElement(node.parent)) {
        node = node.parent.parent;
    }
    return !!getEffectiveTypeAnnotationNode(node.parent);
}
```
Node `node` has a static type of `BindingPattern`. The node above the `ParameterDeclaration` would be some kind of `SignatureDeclaration`.

**Comment by sandersn** [comment]
OK, all the tests passed with the refactorings we worked on. I'll continue with modifications to `isConst` and  `getCombinedModifierFlags` in a new PR.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -903,7 +903,7 @@ namespace ts {
 
     export function isConst(node: Node): boolean {
```
Comment (sandersn) [inline src/compiler/utilities.ts]: for other reviews: all the changes below here are just refactorings based on an improved definition of walkupBindingElementsAndPatterns.

**Comment by sandersn** [comment]
isConst/isLet also apply to VariableDeclarationList, which is handled nicely by getCombinedFlags already, so I don't think it's worth refactoring that. @andy-ms I think I'll push the getCombinedFlags refactoring into this PR since it's not much more churn than is already there.
