### PR TITLE
Spelling correction fixes should not be case-agnostic for two equally weighed options

### LINKED ISSUE #17219: Spelling correction fixes should not be case-agnostic for two equally weighted options
Occurs both as part of the error and as part of the fix.

```ts
class Greeter {
    name: string;

    constructor(name: string) {
        this.name = name;
    }

    greet(otherName: string) {
        conole/**/
    }
}
```

image

### PR DESCRIPTION
**Pull request by Zzzen**
…y weighed options occur.

 fixes #17219

### CODE REVIEW

**Comment by Zzzen** [comment]
@typescript-bot perf test this

File: tests/cases/fourslash/codeFixSpellingShortName2.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+/// <reference path='fourslash.ts' />
+
+////export let ab = 1;
+////abc;
+
+verify.codeFixAvailable([]);
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/codeFixSpellingShortName2.ts:6]: I think there's a `verify.not.codeFixAvailable`

File: tests/cases/fourslash/codeFixSpellingShortName1.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+/// <reference path='fourslash.ts' />
+
+////export let abc = 1;
+////[|abC|] = 1;
+
+verify.rangeAfterCodeFix('abc');
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/codeFixSpellingShortName1.ts:6]: Does this exemplify the length exception? I thought the length had to be less than 3 characters.

File: src/compiler/core.ts [hunk 3]
```diff
@@ -1791,54 +1791,57 @@ namespace ts {
...
-                    return candidate;
-                }
-                if (justCheckExactMatches) {
+                if (candidateName === name) {
                     continue;
                 }
-                if (candidateName.length < 3) {
-                    // Don't bother, user would have noticed a 2-character name having an extra character
+                // Don't bother, user would have noticed a 2-character name having an extra character
+                if (candidateName.length < 3 && candidateNameLowerCase !== nameLowerCase) {
```
Comment (DanielRosenwasser) [inline src/compiler/core.ts:1819]: I *think* I like this new behavior. Leave a comment explaining that

```
Only consider candidates less than 3 characters long when they differ by case.
Otherwise, don't bother, since a user would usually notice differences of a 2-character name.
```

File: tests/cases/fourslash/codeFixSpellingShortName1.ts (hunk 2 above)
Comment (Zzzen) [reply tests/cases/fourslash/codeFixSpellingShortName1.ts]: 😂 yet another off-by-one error.  changed to `ab/aB`

File: src/compiler/core.ts [hunk 4]
```diff
@@ -1805,54 +1805,58 @@ namespace ts {
...
-                if (candidateName.length < 3) {
-                    // Don't bother, user would have noticed a 2-character name having an extra character
+                // Only consider candidates less than 3 characters long when they differ by case.
+                // Otherwise, don't bother, since a user would usually notice differences of a 2-character name.
+                if (candidateName.length < 3 && candidateNameLowerCase !== nameLowerCase) {
                     continue;
                 }
-                // Only care about a result better than the best so far.
-                const distance = levenshteinWithMax(nameLowerCase, candidateNameLowerCase, bestDistance - 1);
+                // Only care about a result better or maybe better than the best so far.
```
Comment (DanielRosenwasser) [inline src/compiler/core.ts:1837]: What does "maybe better" mean in this case?

Comment (Zzzen) [reply src/compiler/core.ts:1837]: 🤦  It was meant to be:

```
Only care about a result better than or at least the same as the best so far in terms of case-insensitive distances.
```

Do you have any suggestions?

Comment (DanielRosenwasser) [reply src/compiler/core.ts:1837]:
```suggestion
                // We only care about results that are clearly better, or which
                // could be better when accounting for case-sensitivity.
```

File: src/compiler/core.ts [hunk 5]
```diff
@@ -1805,54 +1805,58 @@ namespace ts {
...
-                if (distance < 3) {
-                    justCheckExactMatches = true;
+
+                Debug.assert(distance <= bestDistance); // Else `levenshteinWithMax` should return undefined
+
+                if (distance < bestDistance) {
+                    bestDistance = distance;
                     bestCandidate = candidate;
+                    const newBestCaseSensitiveDistance = levenshteinWithMax(name, candidateName, Infinity);
+                    Debug.assert(newBestCaseSensitiveDistance !== undefined);
```
[the remark this answers is not in the document]
Comment (Zzzen) [reply src/compiler/core.ts]: `assertDefined` is deprecated. I've replaced it with `assertIsDefined`

File: src/compiler/core.ts [hunk 6]
```diff
@@ -1805,54 +1805,58 @@ namespace ts {
...
                 }
-                if (distance < 3) {
-                    justCheckExactMatches = true;
+
+                Debug.assert(distance <= bestDistance); // Else `levenshteinWithMax` should return undefined
+
+                if (distance < bestDistance) {
+                    bestDistance = distance;
                     bestCandidate = candidate;
+                    const newBestCaseSensitiveDistance = levenshteinWithMax(name, candidateName, Infinity);
```
[the remark this answers is not in the document]
Comment (Zzzen) [reply src/compiler/core.ts]: 👌 it's lazily initialized now.

**Comment by Zzzen** [comment]
And maybe we can use [Damerau–Levenshtein distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) so that results are more intuitive.

- le_dst('two','tow') returns a value of 2 (changing the w to an o and the o to a w).
- dle_dst('two','tow') returns a value of 1 (transposing the w and o).

**Comment by DanielRosenwasser** [comment]
> When it was opened, I don't think suggestions were filtered by meaning, but now, Console isn't suggested because it's a type. The camelValue/PascalType distinction is standard in JS so the current algorithm will usually get the right answer.

Has it been that long since you used a class @sandersn? 😄

```ts
let node = new Node();

nodes
```

image

**Comment by DanielRosenwasser** [comment]
I'd also say one of the reasons this never worked was because https://github.com/microsoft/TypeScript/issues/40169 was never done.

**Comment by sandersn** [comment]
@Zzzen do you want to keep working on this?

**Comment by Zzzen** [comment]
yeah. I am not sure what to do next though

**Comment by sandersn** [comment]
1. Add a test case with a class named the same as an instance, except for case, like `let node = new Node()`
2. Try making the core levenshtein distance check case-aware. Make the substitution cost cheaper for characters that differ only by case. See what the results look like on various examples.

**Comment by Zzzen** [comment]
👌 got it.

**Comment by Zzzen** [comment]
ping @sandersn @sheetalkamat

File: src/compiler/core.ts [hunk 7]
```diff
@@ -2022,7 +2011,7 @@ namespace ts {
         }
 
         const res = previous[s2.length];
-        return res > max ? undefined : res;
+        return res >= max ? undefined : res;
```
Comment (sandersn) [inline src/compiler/core.ts:2014]: I guess this is the reason `bestDistance - 1` turned into `bestDistance`? Is it also need to support the switch to Math.max and Math.min, or some other reason, like the switch to non-integral values?

File: src/compiler/core.ts [hunk 8]
```diff
@@ -1985,26 +1970,30 @@ namespace ts {
...
-        const big = max + 1;
+        const big = max + 0.000000001;
 
         for (let i = 0; i <= s2.length; i++) {
             previous[i] = i;
         }
 
         for (let i = 1; i <= s1.length; i++) {
             const c1 = s1.charCodeAt(i - 1);
-            const minJ = i > max ? i - max : 1;
```
Comment (sandersn) [inline src/compiler/core.ts:1996]: I think I understand the need for Math.ceil and Math.floor, but why change to Math.max and Math.min?

**Review by sandersn — CHANGES_REQUESTED** [review]
A couple of suggestions, plus some more questions.

File: src/compiler/core.ts [hunk 9]
```diff
@@ -1985,26 +1970,30 @@ namespace ts {
...
+            const maxJ = Math.floor(Math.min(max + i, s2.length));
             current[0] = i;
             /** Smallest value of the matrix in the ith column. */
             let colMin = i;
             for (let j = 1; j < minJ; j++) {
                 current[j] = big;
             }
             for (let j = minJ; j <= maxJ; j++) {
+                // case difference should be insignificant.
+                const substitutionDistance = s1[i - 1].toLowerCase() === s2[j-1].toLowerCase()
```
Comment (sandersn) [inline src/compiler/core.ts:1991]: Would it make sense to cache the lowercase versions of `s1` and `s2` and index into those instead?

This piece of code needs a microbenchmark, since I have no idea. I'm not sure how to do that off the top of my head though.

File: src/compiler/core.ts [hunk 10]
```diff
@@ -1941,41 +1939,28 @@ namespace ts {
...
             const candidateName = getName(candidate);
-            if (candidateName !== undefined && Math.abs(candidateName.length - nameLowerCase.length) <= maximumLengthDifference) {
-                const candidateNameLowerCase = candidateName.toLowerCase();
-                if (candidateNameLowerCase === nameLowerCase) {
-                    if (candidateName === name) {
-                        continue;
-                    }
-                    return candidate;
-                }
-                if (justCheckExactMatches) {
```
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/core.ts:1958]: Never mind, I tried this, and a couple variations, and the tests show that the threshold for "better" is pretty small when taking case into account -- 1.1 in the the test examples. Might as well keep the simpler code in that case.

File: src/compiler/core.ts [hunk 11]
```diff
@@ -1941,41 +1939,28 @@ namespace ts {
      */
     export function getSpellingSuggestion<T>(name: string, candidates: T[], getName: (candidate: T) => string | undefined): T | undefined {
         const maximumLengthDifference = Math.min(2, Math.floor(name.length * 0.34));
-        let bestDistance = Math.floor(name.length * 0.4) + 1; // If the best result isn't better than this, don't bother.
+        let bestDistance = name.length * 0.4 + 0.1; // If the best result is worse than this, don't bother.
```
[the remark this answers is not in the document]
Comment (Zzzen) [reply src/compiler/core.ts:1942]: Removing `Math.floor` is a more accurate implementation of `Whose levenshtein distance is more than 0.4 of the length of the name`. No test is broken by this, so I guess it should be acceptable?

File: src/compiler/core.ts (hunk 8 above)
Comment (Zzzen) [reply src/compiler/core.ts:1996]: `Math.max/min` is more readable for me. Anyway, reverted now.

File: src/compiler/core.ts (hunk 7 above)
Comment (Zzzen) [reply src/compiler/core.ts:2014]: 😏 Actually, it's the result of `bestDistance - 1` turned into `bestDistance`.  `bestDistance - 1` can be replaced with `bestDistance - 0.1`, but it is very fragile since the minimum of distance could be changed to other values like `0.05` in the future.

File: src/compiler/core.ts (hunk 8 above)
Comment (sandersn) [reply src/compiler/core.ts:1996]: OK, makes sense. After this PR is in, maybe you can re-submit that change separately where it would be obvious that Math.max/min are equivalent. I thought it was more readable too, but I prefer to reduce code change per PR in complicated functions like this.

File: src/compiler/core.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/core.ts:1942]: Can you put this in a followup change just like the Math.min/max one? I want this PR to be the minimal change so that future-me has less to read 2 years from now, next time we change this.

[the remark this answers is not in the document]
Comment (Zzzen) [reply src/compiler/core.ts]: 👌

File: src/compiler/core.ts (hunk 9 above)
Comment (Zzzen) [reply src/compiler/core.ts:1991]: How about extracting all symbols from some mostly used type definitions and then apply `getSpellingSuggestion` randomly?

Comment (sandersn) [reply src/compiler/core.ts:1991]: Maybe? One way to stress the system would be to have a scope that fills in all possible neighbours, so that the algorithm has to run on lots of candidates, all under the maximum distance cutoff.

I'm going to run the perf suite on this too, since all those projects compile with lots of errors now -- maybe enough of them are name resolution errors to notice a slowdown.

**Comment by sandersn** [comment]
@typescript-bot perf test this

If the perf test comes back good, this is ready to go. I'd still like a synthetic benchmark before 4.2 releases in January, but it's not urgent. I'm also going to do a before/after comparison of changes with the scope size limiter turned off, to see what changes show up in suggestions from the global scope.

**Review by sandersn — APPROVED** [review]
Performance differences are just noise.

Thanks for your patience and perseverance on this @Zzzen!
