### PR TITLE
Move to new file doesn't maintain prologues directives

### LINKED ISSUE #40292: `Move to new file` does not carry over global 'use strict'
Given a javascript source file that sets strict mode (`'use strict'`),
When using the **Move to a new file** refactoring to extract a function declaration, 
Then the resulting function ends up in a non-strict file.

It is possible for this to change the program's behavior.

- VSCode Version: **1.48.1**
- OS Version: **Windows 10**

Steps to Reproduce:

1. Given `main.js`:
```js
'use strict'
const fs = require('fs')
function foo() { return this }
console.log(foo())
```

2. Running `node main` produces the output:
```console
undefined
```

3. Extract `foo` using the **Move to a new file** refactoring.

This modifies `main.js`:
```js
'use strict'
const fs = require('fs')
const { foo } = require("./foo")
console.log(foo())
```
and generates `foo.js`:
```js
function foo() { return this; }
exports.foo = foo;
```
4. Now running `node main` produces the output:
```console
Object [global] {
  global: [Circular],
  ....
```

Manually adding `'use strict'` to `foo.js` restores the original behavior.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40292 (part of #30478)

### CODE REVIEW

File: src/services/refactors/moveToNewFile.ts [hunk 1]
```diff
@@ -126,25 +139,39 @@ namespace ts.refactor {
...
             ...imports,
             ...body,
         ];
     }
 
+    function getPrologueDirectives(statements: readonly Statement[]): PrologueDirective[] {
+        const prologueDirectives: PrologueDirective[] = [];
+        for (const statement of statements) {
+            if (isPrologueDirective(statement)) {
+                prologueDirectives.push(statement);
```
Comment (DanielRosenwasser) [inline src/services/refactors/moveToNewFile.ts:166]: If you want, consider adding

```ts
function takeWhile<T, U>(array: readonly T[], predicate: (element: T) => element is U): U[];
function takeWhile<T>(array: readonly T[], predicate: (element: T) => boolean): T[];
```

Consider giving it similar semantics to `filter` where it doesn't allocate unless necessary.

File: src/services/refactors/moveToNewFile.ts [hunk 2]
```diff
@@ -126,25 +139,39 @@ namespace ts.refactor {
...
         }
 
         return [
+            ...prologueDirectives,
             ...imports,
             ...body,
         ];
     }
 
+    function getPrologueDirectives(statements: readonly Statement[]): PrologueDirective[] {
```
Comment (DanielRosenwasser) [inline src/services/refactors/moveToNewFile.ts:162]: I think we might already have a utility for this.

**Review by DanielRosenwasser — COMMENTED** [review]
Check with @sheetalkamat

File: src/services/refactors/moveToNewFile.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/refactors/moveToNewFile.ts:162]: I didn't find a similar utility. There is a utility to find only "use strict" directive;

File: src/services/refactors/moveToNewFile.ts [hunk 3]
```diff
@@ -65,20 +65,33 @@ namespace ts.refactor {
...
+        // Imports will be copied to the new file anyway, and may still be needed in the old file.
+        if (isPureImport(statemnt)) {
+            return false;
+        }
+        // Omit prologue directives from the range of statements to move.
+        // Prologue directives will be copied to the new file and should be left in the old file;
+        if (isPrologueDirective(statemnt)) {
+            return false;
+        }
+        return true;
```
Comment (sheetalkamat) [inline src/services/refactors/moveToNewFile.ts:92]:
```suggestion
        // Filters imports and prologue directives out of the range of statements to move.
        // Imports will be copied to the new file anyway, and may still be needed in the old file.
        // Prologue directives will be copied to the new file and should be left in the old file
        return !isPureImport(statemnt) && !isPrologueDirective(statement);
```

File: src/compiler/core.ts [hunk 4]
```diff
@@ -2264,4 +2264,14 @@ namespace ts {
...
+
+    export function takeWhile<T, U extends T>(array: readonly T[], predicate: (element: T) => element is U): U[];
+    export function takeWhile<T>(array: readonly T[], predicate: (element: T) => boolean): T[] {
+        const len = array.length;
+        let index = 0;
+        while (index < len && predicate(array[index])) {
+            index++;
+        }
+        return array.slice(0, index);
+    }
```
Comment (sheetalkamat) [inline src/compiler/core.ts:2276]:
```suggestion
```

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/refactors/moveToNewFile.ts [hunk 5]
```diff
@@ -65,20 +65,26 @@ namespace ts.refactor {
...
 
-    // Filters imports out of the range of statements to move. Imports will be copied to the new file anyway, and may still be needed in the old file.
     function getStatementsToMove(context: RefactorContext): ToMove | undefined {
         const rangeToMove = getRangeToMove(context);
         if (rangeToMove === undefined) return undefined;
         const all: Statement[] = [];
         const ranges: StatementRange[] = [];
         const { toMove, afterLast } = rangeToMove;
-        getRangesWhere(toMove, s => !isPureImport(s), (start, afterEndIndex) => {
+        getRangesWhere(toMove, isAllowedStatementToMove, (start, afterEndIndex) => {
```
Comment (sheetalkamat) [inline src/services/refactors/moveToNewFile.ts:74]: On a second thought this is not a good check.. The prologue directives are marked as expression statement with string literal as the text so we need test which with this change will fail:

```ts
////"use strict";
////[|function b() {
////    return this;
////}|]
////"something that should not be copied to new file";
////b();
```
You would want something like to get statements to move to get start index keeping original condition
```
const index = findIndex(statements, statement => !isPrologueDirective(statement));
```

Comment (a-tarasyuk) [reply src/services/refactors/moveToNewFile.ts:74]: I used `takeWhile` instead of filter to copy only prologue directives from the top of a file and ignore, similar to the following `find*`.

https://github.com/microsoft/TypeScript/blob/ea842c411e190b306bad7c7e0aefe61ab67da7c8/src/compiler/factory/utilities.ts#L332-L344

The following test

```ts
////"use strict";
////[|function b() {
////    return this;
////}|]
////"something that should not be copied to new file";
////b();
```

The new file will look like so

```ts
////"use strict";
////export function b() {
////    return this;
////}
```

or 

https://github.com/microsoft/TypeScript/blob/8cc90b723383d4e8f828f6e555a6420d29f772df/tests/cases/fourslash/moveToNewFile_prologueDirectives6.ts#L1-L38

Comment (andrewbranch) [reply src/services/refactors/moveToNewFile.ts:74]: 👍 bringing back `takeWhile`, or just slicing with `findIndex` sounds like a good plan

Comment (a-tarasyuk) [reply src/services/refactors/moveToNewFile.ts:74]: @andrewbranch Thanks for the review. Oke.

**Review by andrewbranch — APPROVED** [review]

**Review by sheetalkamat — APPROVED** [review]
