### PR TITLE
Fix resolution of named function & class expressions as well as 'arguments'

### LINKED ISSUE #3285: Failed assertion in 1.5 crashes compiler and gets triggered in semantic LS
```TypeScript
var x = function f(x = f(), y = f => f) {
    f(/**/f, f)
}
```

Insert a `<` at the cursor (i.e. replace the `/**/`)

```
getSignatureHelpItems('C:\Users\drosen\AppData\Local\Temp\~vsA6D0.ts', 50)

Error: Debug Failure. False expression: Should only get Alias here.
   at assert (:1373:17)
   at resolveAlias (:11393:13)
   at resolveEntityName (:11503:13)
   at getTypeFromTypeReferenceOrExpressionWithTypeArguments (:13875:21)
   at getTypeFromTypeNode (:14150:21)
   at checkTypeAssertion (:17421:13)
   at checkExpressionWorker (:18214:21)
   at checkExpressionOrQualifiedName (:18156:17)
   at checkExpression (:18141:13)
   at checkExpressionWithContextualType (:18092:13)
   at checkApplicableSignature (:17008:21)
   at chooseOverload (:17221:25)
   at resolveCall (:17146:17)
   at resolveCallExpression (:17300:13)
   at getResolvedSignature (:17380:21)
   at getSignatureHelpItems (:32098:13)
   at getSignatureHelpItems (:40197:13)
   at Anonymous function (:42112:17)
   at simpleForwardCall (:41919:9)
   at forwardJSONCall (:41935:13)
   at forwardJSONCall (:41980:13)
   at getSignatureHelpItems (:42111:13)
```

is the stack from *one* of the several crashes.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
In resolution, we special case the `arguments` object as well as names of function and class expressions.

However, when resolving, we ignore the resolution meaning and special case these unconditionally. That means in the following case, we will always resolve `Foo` as the function rather than the type.

```TypeScript
interface Foo {
}

var x = function Foo() {
    var x: Foo;
}
```

Fixes #3285.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -422,27 +422,32 @@ module ts {
                     case SyntaxKind.SetAccessor:
                     case SyntaxKind.FunctionDeclaration:
                     case SyntaxKind.ArrowFunction:
-                        if (name === "arguments") {
+                        if (meaning & SymbolFlags.Variable && name === "arguments") {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Why not SymbolFlags.Value?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -422,27 +422,32 @@ module ts {
...
                     case SyntaxKind.ArrowFunction:
-                        if (name === "arguments") {
+                        if (meaning & SymbolFlags.Variable && name === "arguments") {
                             result = argumentsSymbol;
                             break loop;
                         }
                         break;
                     case SyntaxKind.FunctionExpression:
-                        if (name === "arguments") {
+                        if (meaning & SymbolFlags.Variable && name === "arguments") {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Same thing here, SymbolFlags.Value?

**Comment by JsonFreeman** [comment]
:+1:
