### PR TITLE
[Master] Fix 11339; using localeCompare cause exception in window 2012 dueto Intl

### LINKED ISSUE #11339: tsc.exe doesn't work on Windows Server 2012
**TypeScript Version:**  2.0.3 

**Repro:**

1) Get a Windows 2012 Server instance.

2) use the following code 

`Test.ts`
```ts
class Test {
    test() {
        console.debug("Hey there!");
    }
}
```

`Test2.ts`
```ts
class Test2 {
    test() {
        console.debug("Hey there!");
    }
}
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es6",
    "module": "amd",
    "outFile": "wwwroot/app/app.js",
    "strictNullChecks": true
  },
  "compileOnSave": true
}
```

3) copy `C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.0\` to the VM (or install `TypeScript_Dev14Full.exe`)

3) run `C:\temp\TypeScript\2.0\tsc.exe`

**Expected behavior:**
To Work. It works fine on 2012 R2 and Windows 10 Client

**Actual behavior:** 

```
Script failed with error: 'JsErrorScriptException (0x30001)'.
Unable to get property 'length' of undefined or null reference
TypeError: Unable to get property 'length' of undefined or null reference
   at compareStrings (Unknown script code:672:17)
   at compareStringsCaseInsensitive (Unknown script code:684:9)
   at Array.prototype.sort (native code)
   at matchFileNames (Unknown script code:39261:9)
   at getFileNames (Unknown script code:39139:13)
   at parseJsonConfigFileContent (Unknown script code:39089:9)
   at parseConfigFile (Unknown script code:39654:13)
   at performCompilation (Unknown script code:39676:21)
   at executeCommandLine (Unknown script code:39627:9)
   at Global code (Unknown script code:39945:1)
```

**Some observations:**
This only happens if you have more than 1 `.ts` file.

### PR DESCRIPTION
**Pull request by yuit**
Fix #11339
@mhegazy  @vladima 

- [ ] Port to release-2.0.5

### CODE REVIEW

File: src/compiler/core.ts [hunk 1]
```diff
@@ -20,6 +20,24 @@ namespace ts {
...
+
+    /**
+     * Use this function instead of calling "String.prototype.localeCompre". This function will preform appropriate check to make sure that
+     *  "typeof Intl" is correct as there are reported issues #11110  nad #11339.
+     * @param a reference string to compare
+     * @param b string to compare against
+     * @param locales string of BCP 47 language tag or an array of string of BCP 47 language tag
+     * @param options an object of Intl.CollatorOptions to specify localeCompare properties
+     */
+    export function localeCompare(a: string, b: string, locales?: string | string[], options?: Intl.CollatorOptions): number | undefined {
```
Comment (mhegazy) [inline src/compiler/core.ts]: I would rather we use `comperStrings` as the only place where we use localeCompare rather than returning undefined, and having every caller check for it

File: src/compiler/core.ts [hunk 2]
```diff
@@ -1029,13 +1033,13 @@ namespace ts {
         return a < b ? Comparison.LessThan : Comparison.GreaterThan;
     }
 
-    export function compareStrings(a: string, b: string, ignoreCase?: boolean): Comparison {
+    export function compareStrings(a: string, b: string, locales?: string | string[], options?: Intl.CollatorOptions): Comparison {
```
Comment (mhegazy) [inline src/compiler/core.ts]: Do we ever use locale? If not I would remove that parameter. 

Also can we just accentSensitivety everywhere? Seems the only place we do not use it is nav bar ordering, but do not think that we need to.. an I missing something?
