### PR TITLE
Fix compileOnSaveEmit when using source of project reference redirect with --out

### LINKED ISSUE #35226: compileOnSave emits referenced compile output
**TypeScript Version:**  3.7.2  (worked with 3.6.2)

**Search Terms:** project references

**Code**
[ts_include_onsave.zip](https://github.com/microsoft/TypeScript/files/3869445/ts_include_onsave.zip)
is a solution archive for visual studio 2019.

**Repro step**
Compile the solution and look at the output file `Controls\SiblingClass\Source.js`.
compileOnSave on the file `Controls\SiblingClass\Source.ts`

**Expected behavior:**
"Solution build" and "compile on save" should generate the same `js` files.
Only logic from `Hmi.Sibling` should be emitted in both compile ways.

**Actual behavior:**
`compileOnSave` emits additional `js` code from `Hmi.buttonClass` which is referenced via project references.

I suspect #32028 is the source of the problem. (cc @sheetalkamat ) even if this was mentioned in the PR:

> compile on save -> do not emit files that are sources of project reference redirects

### PR DESCRIPTION
**Pull request by sheetalkamat**
… Fixes #35226

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot cherry-pick this to release-3.7

File: src/compiler/types.ts [hunk 1]
```diff
@@ -5719,13 +5719,19 @@ namespace ts {
     }
 
     /* @internal */
-    export interface EmitHost extends ScriptReferenceHost, ModuleSpecifierResolutionHost {
+    export interface SourceFileMapBeEmittedHost {
```
Comment (RyanCavanaugh) [inline src/compiler/types.ts]: Name -> `SourceFileMapShouldBeEmittedHost`

**Comment by sheetalkamat** [comment]
@typescript-bot cherry-pick this to release-3.7
