### PR TITLE
Specified error diagnostic for invalid variable names

### LINKED ISSUE #19352: Improve wrong usage of `case` compile errors
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**
```
// This works
for (const cs of [1,2,3]) console.log(cs);

// This doesn't, but the compile error is cryptic
// Variable declaration expected.
// '=' expected.
for (const case of [1, 2, 3]) console.log(case);
```

**Expected behavior:**
Emit an error like `"case" clauses can only appear in a switch statement`

**Actual behavior:**
Emits these errors:
`Variable declaration expected.`
`'=' expected.`

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #19352

This change is pretty small, despite the unfortunate diff detection: it provides a more specific error message when code erroneously attempts to use a reserved keyword as a variable name.

```diff
const case = 123;
- //  ~~~~ Variable declaration expected.
+ //  ~~~~ 'case' is not allowed as a variable declaration name.
```

This only happens when the attempted variable name starts with a `\w+` character, to avoid printing misleading messages on cases like the last `]` in ` var v = /[]/]/`.

This change is really only half of what should be done to address #19352; IMO the parser should ideally be changed to recognize those invalid variable names as identifiers. That way we wouldn't get multiple error messages per case (e.g. [`const case = 123`](https://www.typescriptlang.org/play?#code/MYewdgzgLgBMCGECmMC8MCMAmAzAbiA)) and emit odd JS. But that's an emitter change so I'll a followup issue if & when this PR is merged, unless directed otherwise.

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -2365,33 +2365,37 @@ namespace ts {
             return false;
         }
 
-        function parsingContextErrors(context: ParsingContext): DiagnosticMessage {
+        function parsingContextErrors(context: ParsingContext): [DiagnosticMessage, string?] {
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts:2368]: Nit: I kinda dislike allocating an array on each of these, but maybe it's fine.

**Comment by DanielRosenwasser** [comment]
Does this also fix https://github.com/microsoft/TypeScript/issues/11648‌?

**Comment by DanielRosenwasser** [comment]
> This only happens when the attempted variable name starts with a `\w+` character,

Why not just test whether the token is a keyword? i.e. use `isKeyword`

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -2365,33 +2365,37 @@ namespace ts {
...
-                case ParsingContext.JsxAttributes: return Diagnostics.Identifier_expected;
-                case ParsingContext.JsxChildren: return Diagnostics.Identifier_expected;
-                default: return undefined!; // TODO: GH#18217 `default: Debug.assertNever(context);`
+                case ParsingContext.TypeMembers: return [Diagnostics.Property_or_signature_expected];
+                case ParsingContext.ClassMembers: return [Diagnostics.Unexpected_token_A_constructor_method_accessor_or_property_was_expected];
+                case ParsingContext.EnumMembers: return [Diagnostics.Enum_member_expected];
+                case ParsingContext.HeritageClauseElement: return [Diagnostics.Expression_expected];
+                case ParsingContext.VariableDeclarations:
+                    const tokenString = tokenToString(token());
+                    return tokenString && /\w+/.test(tokenString[0])
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts:2381]: Use `isKeyword` instead.

File: src/compiler/parser.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply src/compiler/parser.ts:2368]: Can do!

**Comment by JoshuaKGoldberg** [comment]
Thanks for the `isKeyword` prompt! `parsingContextErrors` is only ever called by `abortParsingListOrMoveToNextToken` so I had it directly call `parseErrorAtCurrentToken` instead of take in a callback, if that's ok?

And no, this does not improve either of the cases from #11648:

```
index.ts:2:12 - error TS1005: ':' expected.

2 const { in } = data; // <-- [ts] ':' expected.
             ~
index.ts:2:12 - error TS1005: ':' expected.     

2 const { in } = data; // <-- [ts] ':' expected.
             ~

index.ts:4:5 - error TS1005: ';' expected.

4 let delete = 10;
      ~~~~~~

index.ts:4:12 - error TS1109: Expression expected.

4 let delete = 10;
             ~

index.ts:6:7 - error TS1389: 'case' is not allowed as a variable declaration name.

6 const case = 123;
        ~~~~

index.ts:6:12 - error TS1134: Variable declaration expected.

6 const case = 123;
             ~

index.ts:6:14 - error TS1134: Variable declaration expected.

6 const case = 123;
               ~~~
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
It's okay, but jeez! Every refactoring here feels awful!
