### PR TITLE
Handle default class exports when targeting es6 with non-es6 module kinds

### LINKED ISSUE #5594: export default broken for Class expression with target ES6 and commonjs module
Using typescript@next and the following compiler options:
```json
"compilerOptions": {
  "target": "ES6",
  "module": "commonjs",
}
```
A class expression being default exported will be incorrectly compiled into a named export instead.

Example:
```typescript
export default class Foo {}
```
compiles into:
```javascript
class Foo {
}
exports.Foo = Foo;
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #5594.

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -5576,9 +5576,31 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
...
+                        emitDeclarationName(node);
+                        write(";");
+                    }
+                    else if (modulekind === ModuleKind.System) {
+                        write(`${exportFunctionForFile}("default", `);
+                        emitDeclarationName(node);
+                        write(");");
+                    }
+                    else if (modulekind !== ModuleKind.ES6) {
+                        write(`exports.default = `);
```
Comment (mhegazy) [inline src/compiler/emitter.ts]: in ES3 we should emit this as `exports["defualt"]`

Comment (mhegazy) [inline src/compiler/emitter.ts]: never mind.

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -5576,9 +5576,31 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
                     emitDecoratorsOfClass(node);
                 }
 
+                if (!(node.flags & NodeFlags.Export)) {
+                    return;
+                }
                 // If this is an exported class, but not on the top level (i.e. on an internal
                 // module), export it
-                if (!isES6ExportedDeclaration(node) && (node.flags & NodeFlags.Export)) {
+                if (node.parent.kind === SyntaxKind.SourceFile && (node.flags & NodeFlags.Default)) {
```
Comment (mhegazy) [inline src/compiler/emitter.ts]: would not `node.flags & NodeFlags.Default` be sufficient?

File: src/compiler/emitter.ts [hunk 3]
```diff
@@ -5576,9 +5576,31 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
...
+                        emitDeclarationName(node);
+                        write(");");
+                    }
+                    else if (modulekind !== ModuleKind.ES6) {
+                        write(`exports.default = `);
+                        emitDeclarationName(node);
+                        write(";");
+                    }
+                }
+                else if (node.parent.kind !== SyntaxKind.SourceFile || (modulekind !== ModuleKind.ES6 && !(node.flags & NodeFlags.Default))) {
```
Comment (mhegazy) [inline src/compiler/emitter.ts]: just `modulekind !== ModuleKind.ES6` ?

File: src/compiler/emitter.ts (hunk 1 above)
Comment (weswigham) [inline src/compiler/emitter.ts]: :+1:

File: src/compiler/emitter.ts (hunk 2 above)
Comment (weswigham) [inline src/compiler/emitter.ts]: Since `default` is only valid on module level exports, then I suppose so.

File: src/compiler/emitter.ts (hunk 3 above)
Comment (weswigham) [inline src/compiler/emitter.ts]: `(modulekind !== ModuleKind.ES6) || node.parent.kind !== SyntaxKind.SourceFile` is needed, since this handles non-es6 non-default exports and namespace exports.

**Comment by weswigham** [comment]
@mhegazy do we want to merge this fix?

File: src/compiler/emitter.ts (hunk 1 above)
Comment (glen-84) [inline src/compiler/emitter.ts]: Shouldn't this be regular quotation marks? (no embedded variables)

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
sorry for the delay
