### PR TITLE
Fix instanceof narrowing

### LINKED ISSUE #10145: Different narrowing behaviour of user-defined type guards vs discriminated unions
**TypeScript Version:**  nightly (2.1.0-dev.20160804)

**Code**

```ts

interface A { type: 'A' }
interface B { type: 'B' }

function isA(x: A|B): x is A { return x.type === 'A'; }
function isB(x: A|B): x is B { return x.type === 'B'; }

// Using if/else with type guard functions
function foo1(x: A|B): any {
    x // x is A | B
    if (isA(x)) {
        return x; // x is A
    }
    x // x is B |
    if (isB(x)) {
        return x; // x is B
    }
    x // x is B, but should be never                    <===== (1)
}

// Using if/else with discriminated unions
function foo2(x: A|B): any {
    x // x is A | B
    if (x.type === 'A') {
        return x; // x is A
    }
    x // x is B
    if (x.type === 'B') {
        return x; // x is B
    }
    x // x is never                                     <===== (2)
}
```

**Expected behavior:**
`x` is narrowed to `never` at both (1) and (2)

**Actual behavior:** 
`x` is narrowed to `never` at (2), but at (1) it is narrowed to `B`.

**Notes:**
This is carried over from #9260 which is closed. See https://github.com/Microsoft/TypeScript/issues/9260#issuecomment-237564186

### LINKED ISSUE #10167: Narrowing strangeness with instanceof
**TypeScript Version:**  nightly (2.1.0-dev.20160804)

**Code**

```ts
function f(s: Set<string> | Set<number>) {

    // (1)
    s = new Set<number>();
    s // s is Set<number>
    if (s instanceof Set) { } // Clearly no side-effects here. No possible changes to s.
    s // s is Set<number> | Set<any>                                                 <===== (1a)
    s.add(42); // ERROR: Cannot invoke an expression whose type lacks call signature <===== (1b)

    // (2)
    s = new Set<number>();
    s // s is Set<number>
    if (s instanceof Promise) { } // Clearly no side-effects here. No possible changes to s.
    s // s is Set<number> | (Set<number> & Promise<any>)                             <===== (2a)
    s.add(42); // No error this time                                                 <===== (2b)
}

function g(s: Set<string> | Set<number>) {

    // (3)
    s // s is Set<string> | Set<number>
    if (s instanceof Set) {
        s // s is Set<string> | Set<number>
    }
    else {
        s // s is never                                                              <===== (3a)
        s.add(42); // ERROR 'add' does not exist on never                            <===== (3b)
    }

    // (4)
    s = new Set<number>();
    s // s is Set<number>
    if (s instanceof Set) {
        s // s is Set<any>
    }
    else {
        s // s is Set<number>                                                        <===== (4a)
        s.add(42); // no error, but we couldn't possibly have a Set instance here    <===== (4b)
    }
}
```

**Expected behavior:**

- inferred type of `s` at (1a) is `Set<number>`
- inferred type of `s` at (2a) is `Set<number>`
- inferred type of `s` at (3a) is `never`
- inferred type of `s` at (4a) is `never`
- Compiler errors at (3b) and (4b)
- No compiler errors at (1b) and (2b)

**Actual behavior:** 

- inferred type of `s` at (1a) is `Set<number> | Set<any>`
- inferred type of `s` at (2a) is `Set<number> | (Set<number> & Promise<any>)`
- inferred type of `s` at (3a) is `never`
- inferred type of `s` at (4a) is `Set<number>`
- Compiler errors at (1b) and (3b)
- No compiler errors at (2b) and (4b)

**Notes:**

Brought over from #9862 which is closed. See that issue for the discussion leading to the above examples. Cc: @ahejlsberg, @sandersn

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes three issues related to narrowing of types with the instanceof operator and user defined type guards:

* In an operation `x instanceof T` where x is of a non-union type, we now narrow the type of `x` to `never` in the false branch if the type of x is not a subtype of T. Previously we didn't change the type of `x` in the false branch.
* In an operation `x instanceof T` where the types of x and T are both assignable to each other, we now pick T only if it is a subtype of the type of x. Previously we would always pick T.
* Following a branching construct with a type guard that introduces a "foreign" type (i.e. a type that isn't part of a variable's declared type) we now perform subtype reduction to remove the foreign type. Previously the foreign type would accumulate in the control flow type of the variable.

These fixes also affect similar scenarios with user defined type predicates (since the narrowing logic is shared).

Fixes #10145, #10167.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
>  In an operation `x instanceof T` where x is of a non-union type, we now narrow the type of `x` to `never` in the false branch. Previously we didn't change the type of `x` in the false branch.

Does this mean that the comments in this example are accurate?

```ts
class Animal { /* ... */ }
class Dog extends Animal { /* ... */ }
class Cat extends Animal { /* ... */ }

declare var x: Animal;
if (x instanceof Dog) {
    // 'x' has type 'Dog'
}
else {
    // 'x' has type 'never'
}
```

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Actually, no. I missed the part *in italics* in the wording:

* In an operation `x instanceof T` where x is of a non-union type, we now narrow the type of `x` to `never` in the false branch *if the type of x is not a subtype of T*. Previously we didn't change the type of `x` in the false branch.

**Comment by DanielRosenwasser** [comment]
Right, it didn't look like that's what was happening in the implementation, so I just wanted to clarify.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8506,13 +8537,15 @@ namespace ts {
                         return getUnionType(assignableConstituents);
                     }
                 }
-                // If the candidate type is assignable to the target type, narrow to the candidate type.
-                // Otherwise, if the current type is assignable to the candidate, keep the current type.
-                // Otherwise, the types are completely unrelated, so narrow to the empty type.
+                // If the candidate type is a subtype of the target type, narrow to the candidate type.
+                // Otherwise, narrow to whichever of the target type or the candidate type that is assignable
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I think there's a little more precision than the wording lends to here. If the candidate isn't a subtype, but is assignable, we keep the original type in place. (e.g. with `Array.isArray`, you preserve the original type instead of giving back `Array<any>`).

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -8506,13 +8537,15 @@ namespace ts {
...
+                // If the candidate type is a subtype of the target type, narrow to the candidate type.
+                // Otherwise, narrow to whichever of the target type or the candidate type that is assignable
+                // to the other. Otherwise, the types are completely unrelated, so narrow to an intersection
+                // of the two types.
                 const targetType = type.flags & TypeFlags.TypeParameter ? getApparentType(type) : type;
-                return isTypeAssignableTo(candidate, targetType) ? candidate :
+                return isTypeSubtypeOf(candidate, targetType) ? candidate :
                     isTypeAssignableTo(type, candidate) ? type :
-                        getIntersectionType([type, candidate]);
+                    isTypeAssignableTo(candidate, targetType) ? candidate :
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Is there a test where this condition being true is witnessed? You need something where

* the candidate isn't a subtype of the original type
* the original type can't be assigned to the candidate type
* the candidate is *assignable* to the original type

Comment (ahejlsberg) [inline src/compiler/checker.ts]: Added an extra test to cover that case.

**Comment by RyanCavanaugh** [comment]
:+1:
