### PR TITLE
fixAddMissingMember: Improve deduplication in code-fix-all

### LINKED ISSUE #25297: Fix all for add missing member quick fix does not work classes with similar property names
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
class C {
    method() { 
        this.a = 0;
    }
}


class D {
    method() {
        this.a = 0;
    } 
}   
```

**Expected behavior:**

```ts
class C {
    a: number;
    method() { 
        this.a = 0;
    }
}


class D {
    a: number;
    method() {
        this.a = 0;
    } 
}   
```

**Actual behavior:**
```ts
class C {
    a: number;
    method() { 
        this.a = 0;
    }
}


class D {
    method() {
        this.a = 0;
    } 
}   
```
**Playground Link:**  

**Related Issues:** 

Discovered in https://github.com/Microsoft/TypeScript/pull/25182/files#r198680755

Caused by the use of the property name as a key for seen dictionary in the fixall code path.

One interesting problem here is the handling of inherited properties. we probably want to skip declaring a property in a derived class, first for brevity, and second to avoid conflicting type declarations when possible. if so, then the key will need to be a bit more involved than just a string.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #25297

### CODE REVIEW

File: src/services/codefixes/fixAddMissingMember.ts [hunk 1]
```diff
@@ -13,55 +13,104 @@ namespace ts.codefix {
...
-                        addMethodDeclaration(context, changes, classDeclarationSourceFile, classDeclaration, token, call, makeStatic, inJs, preferences);
+            const { program, preferences } = context;
+            const checker = program.getTypeChecker();
+            const seen = createMap<true>();
+
+            const classToMembers = new NodeMap<ClassLikeDeclaration, ClassInfo[]>();
+
+            return createCombinedCodeActions(textChanges.ChangeTracker.with(context, changes => {
+                eachDiagnostic(context, errorCodes, diag => {
+                    const checker = program.getTypeChecker();
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: u already cached `checker` before the lambda.
