### PR TITLE
Fix jsx formatting

### LINKED ISSUE #41925: TypeScript Server Error: "Debug Failure. False expression: Token end is child end"
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2.0-dev.20201210

**Search Terms**
- format
- jsx
- react

---

- VSCode Version: 1.51.1
- OS Version: macOS 11.0.1 (20B50)

Steps to Reproduce:
- Create a `.tsx` file containing the following code (wrong indentation is intentional to demonstrate the formatter's issue):
```tsx
function App() {
  const value = "Oh no";

  return (
  <div>"{value}"</div>
  )
}
```

The `const value = "Oh no";` line can be replace or even erased without any change concerning the issue.

- Use the [`Format Document`](https://code.visualstudio.com/docs/editor/codebasics#_formatting) or `Format Selection` action.

- It doesn't work and outputs the following error in the `Log (Extension Host)` part of the `Output` logs.
```
[2020-12-10 23:31:42.444] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-12-10 23:31:42.444] [exthost] [error] Error: <syntax> TypeScript Server Error (4.0.3)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128163:38)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27255:21)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at processChildNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128233:48)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128097:21
    at visitNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26839:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27235:21)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27042:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27119:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at processChildNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128233:48)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128097:21
    at visitNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26839:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27079:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128095:21
    at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26834:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26964:21)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at processChildNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128170:21)
    at processChildNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128233:48)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128097:21
    at visitNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:26839:24)
    at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:27081:24)
    at processNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:128094:20)
    at formatSpanWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127907:17)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127888:208
    at Object.getFormattingScanner (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:126494:23)
    at formatSpan (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127888:31)
    at Object.formatSelection (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127706:20)
    at Proxy.getFormattingEditsForRange (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:143766:34)
    at IOSession.Session.getFormattingEditsForRange (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154253:45)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153197:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:76476)
	at dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:70351)
	at dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:69210)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:68720
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at g.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:45:60018)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:45:59666)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

The issue is happening when there is JS/TS code inside any quote format (`"`, `'` and `), in TSX code.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by armanio123**
Fixes #41925

This PR  changes on how we scan JSX during formatting. It now limits the jsx text range to the last non-whitespace character (allows the formatting of `</div>` to be correct)
```
<div>|
    text|
</div>
```

Fixes the following issues:
- Jsx not enclosed on parenthesis didn't format correctly. e.g.:
```
const a = 
    <div>
    foo
          </div>
```
- Identifiers on the middle of jsx strings didn't format. e.g.:
```
const b = (
    <div>
  {     foo  }
          </div>
);
```
- Last line on a jsx text didn't format. e.g.:
```
const c = (
    <div>
    foo
  {     foobar  }
  bar
          </div>
);
```

### CODE REVIEW

**Comment by weswigham** [comment]
Issue link in the OP links to another PR - typo?

**Comment by armanio123** [comment]
> Issue link in the OP links to another PR - typo?

Typo. Got it fixed now. Give it another try.

File: tests/baselines/reference/tsxReactEmitEntities.js [hunk 1]
```diff
@@ -23,7 +23,9 @@ declare var React: any;
 <div>&#x1F408;&#x1F415;&#128007;&#128017;</div>;
 
 //// [file.js]
-React.createElement("div", null, "Dot goes here: \u00B7 &notAnEntity; ");
+React.createElement("div", null,
+    "Dot goes here: \u00B7 &notAnEntity;",
+    " ");
```
Comment (RyanCavanaugh) [inline tests/baselines/reference/tsxReactEmitEntities.js:28]: Changing the arity of `createElement` here is going to be a runtime break. This needs to be preserved.

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]

File: tests/baselines/reference/tsxReactEmitEntities.js (hunk 1 above)
Comment (armanio123) [reply tests/baselines/reference/tsxReactEmitEntities.js:28]: Based on React's documentation this would not create an issue. https://reactjs.org/docs/react-api.html#createelement

Nonetheless, I do agree that the syntax is weird. In my small set of tests, I found no difference in adding the empty line in a single string than as an extra parameter.

Comment (RyanCavanaugh) [reply tests/baselines/reference/tsxReactEmitEntities.js:28]: https://codepen.io/SeaRyanC/pen/eYBZOLJ

It's an observable runtime change that could break someone's app
```js
function myComp(props) {
  if (typeof props.children === "string") {
    return <div>Good</div>
  } else {
    return <div>Bad</div>
  }
}

ReactDOM.render(React.createElement(myComp, {}, "one "), document.getElementById("good"));
ReactDOM.render(React.createElement(myComp, {}, "one", " "), document.getElementById("bad"));

```

Comment (armanio123) [reply tests/baselines/reference/tsxReactEmitEntities.js:28]: I see. It makes sense, working on this then.

File: tests/cases/fourslash/formattingJsxTexts2.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
+/// <reference path='fourslash.ts' />
```
Comment (andrewbranch) [inline tests/cases/fourslash/formattingJsxTexts2.ts:1]: I’m going to take a closer look at this implementation today, but first thing to note is that this test doesn’t actually generate the crash at #41925. I haven’t checked yet to see whether your changes do in fact fix that crash, but it seems like the test doesn’t actually prove that the linked bug is fixed.

File: tests/cases/fourslash/formattingJsxTexts2.ts [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+//@Filename: file.tsx
+//// const a = (
+////     <div>
+////   foo
+////           </div>
+//// );
+//// 
+//// const b = (
+////     <div>
+////   {     foo  }
```
Comment (andrewbranch) [inline tests/cases/fourslash/formattingJsxTexts2.ts:12]: Huh, how did you fix this? It seems like the changes are only related to JsxText, but these spaces fall within a JsxExpression.

Comment (armanio123) [reply tests/cases/fourslash/formattingJsxTexts2.ts:12]: This got fixed because I have changed how we rescan jsx text and parenthesis. I believe in the failure case, it didn't actually identify any rescan the JsxText, this leaving the code unchanged. Now JsxText is rescaned allowing the JsxExpression to be identified and formatted correctly.

File: tests/cases/fourslash/formattingJsxTexts2.ts (hunk 2 above)
Comment (armanio123) [reply tests/cases/fourslash/formattingJsxTexts2.ts:1]: Agree, I have missed that test. Added.

File: tests/cases/fourslash/formattingJsxTexts2.ts (hunk 3 above)
Comment (andrewbranch) [reply tests/cases/fourslash/formattingJsxTexts2.ts:12]: Ah, I didn’t see there is actually a rule for `NoSpaceAfterBraceInJsxExpression`

File: src/services/formatting/formatting.ts [hunk 4]
```diff
@@ -759,9 +759,15 @@ namespace ts.formatting {
...
-                        const previousNode = siblings[currentIndex - 1];
+                        let tempNode: Node;
+                        let previousNode: Node | undefined;
+                        forEachChild(parent, childNode => {
+                            if (childNode.pos === child.pos) {
+                                previousNode = tempNode;
+                                return true;
+                            }
+                            tempNode = childNode;
+                        });
```
Comment (andrewbranch) [inline src/services/formatting/formatting.ts:770]: What is this change for?

**Review by andrewbranch — COMMENTED** [review]
Ok, so, I think this approach is generally correct. This PR basically fixes two very loosely related bugs at the same time:

1. The crash in the linked bug, along with the whitespace not being trimmed from inside the braces in `JsxExpressions`, is the really bad bug here caused by the formatting scanner returning the completely wrong token kind. That was fixed by your change to `shouldReScanJsxText` and seems to be exactly the right fix.
2. You’ve also fixed indentation of multiline JsxText. This seems unrelated to me, but I’m guessing the reason it’s in this PR is because fixing the bug in (1) caused an existing indentation test to fail.

If I understand correctly, the formatter basically has no mechanism to adjust the indentation _within_ multiline tokens. It generally assumes that line breaks and indentation only fall _between_ tokens, but that’s not true for JsxText, which can span multiple lines. So there are two ways you could approach this problem:

1. Build some special logic into the formatter to split JsxText into lines and rewrite process indentation for each line.
2. Make the scanner pretend that one single line JsxText token is actually a series of consecutive JsxText tokens separated by trivia. That way, the core formatter logic Just Works™. 

You’ve chosen the second option here. I don’t really have a strong opinion on which way is better, though I think option (2) is definitely more creative and unexpected, therefore needs to be well-documented in comments. What I’m interested in is seeing if it’s possible to move this token-faking from the proper scanner into the formatting scanner. Would it be possible to let the scanner return something multiline, but then split it up by line in the formatting scanner after the fact? I’m just a little hesitant to mix this formatting concern into a function also used for normal scanning.

File: src/services/formatting/formatting.ts (hunk 4 above)
Comment (armanio123) [reply src/services/formatting/formatting.ts:770]: It fixes a bug for when the `JsxElement` contains multiple nodes. It used to be that only the first node would be formatted. 

In the scenario below only `some text` would be formatted before the fix:
```
const foo = <div>
             some text
                            {bar}
                    more text
</div>
```

**Comment by armanio123** [comment]
> You’ve also fixed indentation of multiline JsxText. This seems unrelated to me, but I’m guessing the reason it’s in this PR is because fixing the bug in (1) caused an existing indentation test to fail.

It's exactly what happened. Once the crash was fixed indentation still didn't worked as expected, so I started fixing that.

> Build some special logic into the formatter to split JsxText into lines and rewrite process indentation for each line.

That's not entirely true, as on [indentMultilineCommentOrJsxText](https://github.com/microsoft/TypeScript/blob/3c32f6e154ead6749b76ec9c19cbfdd2acad97d6/src/services/formatting/formatting.ts#L1076) function there is already special logic for indenting each of the `JsxText` lines. Also, I tried this approach first, but I found it more challenging to change it for this scenario since it was not designed to behave like this.

> Make the scanner pretend that one single line JsxText token is actually a series of consecutive JsxText tokens separated by trivia. That way, the core formatter logic Just Works™.

Only the last portion of the `JsxText` is considered trivia if it is a break line followed by whitespace. Not all of the tokens will behave like this due to whitespace restrictions on jsx text.
In this example the JsxClosingElement `</div>` will not contain any trivia:
```
const foo = <div>text with trailing with space                          </div>
```

> Would it be possible to let the scanner return something multiline, but then split it up by line in the formatting scanner after the fact?

I consider this as well. I could let the scanner work as is and in the formatting scanner iterate back the `startPos` of the scanner until a non-whitespace is found. I choose not to go this path tho, as I wasn't sure of the rules of whitespace I need to follow. I can take a deeper look if you feel really strong about it, just let me know.

Working on doing a better job in documentation.

File: src/services/formatting/formatting.ts (hunk 4 above)
Comment (andrewbranch) [reply src/services/formatting/formatting.ts:770]: I guess I mean, I don't understand how the new code manages to do something different from the old code. They look like they should do the same thing, except that `forEachChild` doesn’t include non-node children (like punctuation tokens). But it seems like that doesn’t matter in your example.

**Comment by andrewbranch** [comment]
> Make the scanner pretend that one single line JsxText token is actually a series of consecutive JsxText tokens separated by trivia. That way, the core formatter logic Just Works™.

Oops, I said this wrong. I meant

> Make the scanner pretend that one single **multiline** JsxText token is actually a series of consecutive JsxText tokens (**one per line**), separated by trivia.

E.g.

```ts
const foo = <div>
  one
    two
      three
  </div>
```

You want to treat `one`, `two`, and `three` as separate tokens in the formatting scanner, right? Just checking if I understood that correctly.

> I can take a deeper look if you feel really strong about it, just let me know.

> Working on doing a better job in documentation.

I actually think your code comments are good, they’re just hard to find because they’re two whole files away from the formatter. You wouldn’t really know in `formatting.ts` or `formattingScanner.ts` that you were going to create “synthesized” tokens, so to speak, unless you actually went into the scanner itself. This is part of the reason why I do think it’s worthwhile to at least investigate moving that logic out of the scanner.

File: src/services/formatting/formatting.ts (hunk 4 above)
Comment (armanio123) [reply src/services/formatting/formatting.ts:770]: Got it. Before it used to search for the siblings of `JsxText` using the `getChildren` method of the parent. This will result in not being able to find the correct sibling as is will be looking for `JsxOpeningElement`, `JsxClosingElement` and in this example a `SyntaxList`. Non of them is really a sibling.

Instead, I have changed it to use `ForEachChild` which now the search will include the missing `JsxExpression` and `JsxText`, thus being able to correctly format the source code.

Just for visualization
With getChildren:
image

With forEachChild:
image

Comment (andrewbranch) [reply src/services/formatting/formatting.ts:770]: Ah, I didn’t realize `getChildren()` was returning a SyntaxList. That makes sense. Just as a small readability optimization, I would write it like this:

```ts
if (isJsxText(child)) {
    const range: TextRange = { pos: child.getStart(), end: child.getEnd() };
    if (range.pos !== range.end) { // don't indent zero-width jsx text
        const previousNode = child.parent.children[child.parent.children.indexOf(child) - 1] || child.parent.openingElement;
```

You can simplify a lot because you know that `child` is `JsxText` here.

File: src/compiler/scanner.ts [hunk 5]
```diff
@@ -2242,7 +2242,7 @@ namespace ts {
             return token = SyntaxKind.QuestionToken;
         }
 
-        function scanJsxToken(): JsxTokenSyntaxKind {
+        function scanJsxToken(isFormatting?: boolean): JsxTokenSyntaxKind {
```
Comment (andrewbranch) [inline src/compiler/scanner.ts:2245]: I would suggest renaming and flipping this boolean (and the one in `reScan`) so it’s explicit about what it’s doing:

```suggestion
        function scanJsxToken(allowMultilineJsxText = true): JsxTokenSyntaxKind {
```

File: src/compiler/scanner.ts [hunk 6]
```diff
@@ -2401,7 +2395,7 @@ namespace ts {
                     if (text.charCodeAt(pos) === CharacterCodes.lineFeed) {
                         pos++;
                     }
-                    // falls through
+                // falls through
```
Comment (andrewbranch) [inline src/compiler/scanner.ts:2398]: Stray auto-format

**Review by andrewbranch — APPROVED** [review]
Wow, I love how much simpler this got. Nice work! A couple suggestions but overall good to go.

File: src/compiler/scanner.ts (hunk 6 above)
Comment (armanio123) [reply src/compiler/scanner.ts:2398]: I hate this ones. Fixed.

File: src/compiler/scanner.ts (hunk 5 above)
Comment (armanio123) [reply src/compiler/scanner.ts:2245]: Renamed.

**Comment by andrewbranch** [comment]
API baselines need to be updated

**Review by RyanCavanaugh — APPROVED** [review]
