### PR TITLE
Prefer elaborating on expressions which could be called to produce a correct type by suggesting such

### LINKED ISSUE #25308: "Did you forget to call 'X'?" for assignability errors
Discussed at #25306

We noticed a relatively high-occurring instance of an error:

```
Type X is not assignable to type () => X.
Type () => X is not assignable to type X.
```

Similarly, you can find users reporting issues on

```
Type Date is not assignable to type DateConstructor.
Type DateConstructor is not assignable to type Date.
```

We should see if the user forgot to call (or construct) one of the respective types if we can pull apart the context.

### PR DESCRIPTION
**Pull request by weswigham**
didyoumean

Fixes #25308

(Note that this adds the messages, not a potential quickfix. A quickfix should be more narrow than the suggestion, as only a 0-argument call/construct has an obvious quickfix)

### CODE REVIEW

**Comment by weswigham** [comment]
cc @DanielRosenwasser

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -10606,6 +10609,29 @@ namespace ts {
             return false;
         }
 
+        function elaborateDidYouMeanToCallOrConstruct(node: Expression, source: Type, target: Type): boolean {
+            const callSignatures = getSignaturesOfType(source, SignatureKind.Call);
+            const constructSignatures = getSignaturesOfType(source, SignatureKind.Construct);
+            for (const signatures of [constructSignatures, callSignatures]) {
+                if (length(signatures)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Do you need the `length()` call with `some`?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -10585,6 +10585,9 @@ namespace ts {
 
         function elaborateError(node: Expression | undefined, source: Type, target: Type): boolean {
             if (!node || isOrHasGenericConditional(target)) return false;
+            if (!isTypeAssignableTo(source, target) && elaborateDidYouMeanToCallOrConstruct(node, source, target)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: This should ideally be cheap since the original call will have some of the relationships cached, right?

Also, technically I think you should be using the original relationship, not assignability, right?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -10606,6 +10609,29 @@ namespace ts {
...
+            const callSignatures = getSignaturesOfType(source, SignatureKind.Call);
+            const constructSignatures = getSignaturesOfType(source, SignatureKind.Construct);
+            for (const signatures of [constructSignatures, callSignatures]) {
+                if (length(signatures)) {
+                    if (some(signatures, s => {
+                        const returnType = getReturnTypeOfSignature(s);
+                        return !(returnType.flags & (TypeFlags.Any | TypeFlags.Never)) && isTypeAssignableTo(returnType, target);
+                    })) {
+                        const resultObj: { error?: Diagnostic } = {};
+                        checkTypeAssignableTo(source, target, node, /*errorMessage*/ undefined, /*containingChain*/ undefined, resultObj);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: TIL `errorOutputContainer`

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -10606,6 +10609,29 @@ namespace ts {
...
+                        const diagnostic = resultObj.error!;
+                        addRelatedInfo(diagnostic, createDiagnosticForNode(
+                            node,
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Kind of funny that the "related span" is the same span.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Yes and yes.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Probably not.

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Yeah, I added that awhile ago. Not the happiest about it, but a side channel's a side channel, since most callers just need the boolean return.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts]: I think it's still probably the best place to put it. Wanna do something else?

File: src/compiler/diagnosticMessages.json [hunk 5]
```diff
@@ -3716,6 +3716,14 @@
         "category": "Message",
         "code": 6211
     },
+    "Did you mean to call this expression?": {
+        "category": "Message",
+        "code": 6212
+    },
+    "Did you mean to use `new` with this expression?": {
```
Comment (amcasey) [inline src/compiler/diagnosticMessages.json]: >`new` [](start = 25, length = 5)

Elsewhere, "new" is in single quotes.
