### PR TITLE
Fix reference marking of values merged with unresolvable type-only imports

### LINKED ISSUE #54526: transpileModule: not preserving exports
# Bug Report

The output of `transpileModule`  did not preserve the value exports from the input module when the identifier also matches a type. This does not happen when compiling the project using `tsc`  or with `verbatimModuleSyntax` enabled.

### 🔎 Search Terms

- transpileModule
- exports
- preserve

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about module emit.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=5.1.3#code/LAKAlgtgDg9gTgFwAQIJ5QKZIN5IMIzQwB2GxyAvkgGZyFIBEcGAhgMYIMDcoobJAZ2QEipcgC58hWGOQBeHFRYCkAV2IBrYjADuxJMqmiyCHiFAYAHrEQ4jMk0gpmgA)

Interestingly the error that is appearing in the playground

> Import declaration conflicts with local declaration of 'Component'.(2440)

Is not appearing for the same code in VSCode for a repo version of the issue: https://github.com/acutmore/transpile-module-bug

### 💻 Code

```ts
// exports.ts
import fooValue from "./values";
import type {Foo} from "./types";

const Foo: Foo = fooValue as any as Foo;

export {Foo};
```

```js
import tsc from "typescript";
import * as fs from "node:fs";

const result = tsc.transpileModule(fs.readFileSync("./exports.ts", "utf-8"), {
    compilerOptions: {
        "verbatimModuleSyntax": false,
        "importsNotUsedAsValues": "error",
        "ignoreDeprecations": "5.0",
        "module": "ESNext"
    }
});
```

### 🙁 Actual behavior

```js
import fooValue from "./values";
var Foo = fooValue;
```

### 🙂 Expected behavior

```js
import fooValue from "./values";
var Foo = fooValue;
export { Foo };
```

### PR DESCRIPTION
**Pull request by andrewbranch**
In #50853, I identified several cases where a symbol was incorrectly being reported as unusable in emit locations due to being a type-only import, when it was actually a local value merged with a type-only import:

```ts
// @Filename: a.ts
export interface A {}

// @Filename: b.ts
import type { A } from "./a";
const A = {};
A; // Error: A cannot be used as a value because it was imported with 'import type' 👎
```

The original code simply looked to see if the symbol resolved to any type-only import or export, which was obviously insufficient for merged symbols. Ideally, we wanted to know which declarations contributed which meanings to the merged symbol’s flags. That information isn’t tracked, though, so in #50853 I implemented a bit of proxy logic to get close: if the yet-unresolved alias symbol has a value meaning, and the type-only import symbol doesn’t, then we know the value meaning could not have come from the type-only import, so it’s safe to use. In code, that was something like

```ts
symbol.flags & SymbolFlags.Value &&
!(resolveAlias(getTypeOnlyAliasDeclaration(symbol).symbol).flags & SymbolFlags.Value)
```

So in the example above, `symbol.flags` would have `Alias|Variable` (and `Variable` counts as a Value), and the resolution of `A` starting at the type-only import would have `Interface`. The new logic correctly allowed `A` to be referenced as a value.

So we were kind of picking apart the pieces of the merged symbol, performing some alias resolution independently on the parts, and using the process of elimination to determine where the `SymbolFlags.Value` meaning must have come from. (The key thing that makes this work is that separate values are not allowed to merge across modules through an import—e.g., even though a function and a namespace can merge in the same file, you can’t _import_ a function `f` and then declare an instantiated `namespace f`. That’s always been an error.)

_However_, this logic breaks down if the type-only import cannot be resolved, as in `ts.transpileModule`. The symbol returned by `resolveAlias` for an unresolvable alias is `unknownSymbol`, which has all symbol flags, to denote that it _could_ be anything. So looking at the example through the old code again:

```ts
symbol.flags & SymbolFlags.Value &&
!(resolveAlias(getTypeOnlyAliasDeclaration(symbol).symbol).flags & SymbolFlags.Value)
```

`symbol.flags & SymbolFlags.Value` is still true, but this time, `resolveAlias(getTypeOnlyAliasDeclaration(symbol).symbol)` is `unknownSymbol`, which _also_ has `SymbolFlags.Value`, so the incorrect assumption is that the value meaning for `A` must have come from the type-only import.

This PR replaces that strategy with one that collects flags starting at the merged symbol, and stops just before it gets to the resolution of the type-only import.

Fixes #54526

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4457,32 +4457,37 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+    function getAllSymbolFlags(symbol: Symbol, excludeTypeOnlyMeanings?: boolean): SymbolFlags {
+        const typeOnlyDeclaration = excludeTypeOnlyMeanings && getTypeOnlyAliasDeclaration(symbol);
+        const typeOnlyResolution = typeOnlyDeclaration && resolveAlias(typeOnlyDeclaration.symbol);
+        let flags = symbol.flags;
+        let seenSymbols;
+        while (symbol.flags & SymbolFlags.Alias) {
+            const target = resolveAlias(symbol);
+            if (target === typeOnlyResolution) {
+                break;
+            }
```
Comment (andrewbranch) [inline src/compiler/checker.ts:4469]: The indentation on this function was messed up, so I recommend viewing it with whitespace changes hidden. These few lines are the core change that I mentioned in the PR description.

Comment (jakebailey) [reply src/compiler/checker.ts:4469]: (dprint when?)

Comment (andrewbranch) [reply src/compiler/checker.ts:4469]: My thoughts exactly 👀

File: tests/baselines/reference/importEquals3.js [hunk 2]
```diff
@@ -33,7 +33,9 @@ exports.A = A;
 //// [b.js]
 "use strict";
 Object.defineProperty(exports, "__esModule", { value: true });
-exports.x = void 0;
+exports.x = exports.A = void 0;
+var A = a.A; // Error
+exports.A = A;
```
Comment (andrewbranch) [inline tests/baselines/reference/importEquals3.js:38]: Some illegal merges that were previously counted as unreferenced for purposes of emit are now counted as referenced. Stuff is going to crash either way, and I don’t really think one is particularly more correct than the other.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -4457,32 +4457,44 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
-      }
-      return flags;
+    function getSymbolFlags(symbol: Symbol, excludeTypeOnlyMeanings?: boolean, excludeLocalMeanings?: boolean): SymbolFlags {
+        const typeOnlyDeclaration = excludeTypeOnlyMeanings && getTypeOnlyAliasDeclaration(symbol);
+        const typeOnlyDeclarationIsExportStar = typeOnlyDeclaration && isExportDeclaration(typeOnlyDeclaration);
+        const typeOnlyResolution = typeOnlyDeclaration && (
+            typeOnlyDeclarationIsExportStar
+                ? resolveExternalModuleName(typeOnlyDeclaration.moduleSpecifier, typeOnlyDeclaration.moduleSpecifier, /*ignoreErrors*/ true)
+                : resolveAlias(typeOnlyDeclaration.symbol));
+        const typeOnlyExportStarTargets = typeOnlyDeclarationIsExportStar && typeOnlyResolution ? getExportsOfModule(typeOnlyResolution) : undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts:4467]: This name is a little confusing since it's hard to notice that it's the exports of a module. But maybe the property that it's targets of resolution is more important.

**Review by sandersn — APPROVED** [review]
I *think* I understood what is going on here. At least, enough for me to make comments about function naming.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -4457,32 +4457,44 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
-              }
-              else {
-                  seenSymbols = new Set([symbol, target]);
-              }
-          }
-          flags |= target.flags;
-          symbol = target;
-      }
-      return flags;
+    function getSymbolFlags(symbol: Symbol, excludeTypeOnlyMeanings?: boolean, excludeLocalMeanings?: boolean): SymbolFlags {
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/compiler/checker.ts:4460]: I tried to audit all uses of `symbol.flags` when I first wrote `getAllSymbolFlags` and did make many substitutions. The remaining uses, as best I could tell, intentionally only look at local meanings. The name `getAllSymbolFlags` no longer felt appropriate with arguments that explicitly filter them down from “all.” Perhaps a way to say `getSymbolFlagsIncludingNonLocalOnes` would make a better name.
