### PR TITLE
Don't delete comments when deleting unused declarations

### LINKED ISSUE #34568: Do not delete comments when removing unused declarations
- VSCode Version: 1.39.2
- OS Version: macOS 10.14.6

demo

Steps to Reproduce:

1. Write a comment
2. Declare some JS variables and use them
3. Declare some unused JS variables
4. Click the tooltip and select "Delete al unused declarations

Expected:

- Comments are not deleted
- Unused declarations are removed

Actual

- Comments **are** deleted

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by jessetrinity**
Fixes #34568

Do not delete preceding comments when removing an unused declaration.

```ts
// section comment
const ununsed = 0;
// other comment
const used = 0;
```
becomes
```ts
// section comment
// other comment
const used = 0;
```

I've only addressed the variable statement case here because I would like feedback on which other cases this should apply to. In particular, should we do the same for imports?

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -42,6 +42,10 @@ namespace ts.textChanges {
          * include all trivia between the node and the previous token
          */
         IncludeAll,
+        /**
+         * Only delete trivia one the same line as getStart()
+         */
+        StartLineOnly,
```
Comment (jessetrinity) [inline src/services/textChanges.ts]: This should maybe be called `Include` vs the existing `IncludeAll`, whatever reads best to others.

**Comment by andrewbranch** [comment]
> I've only addressed the variable statement case here because I would like feedback on which other cases this should apply to. In particular, should we do the same for imports?

My JSDoc example wasn’t a variable statement, but it applies to variable statements. I can’t really think of any reason not to extend the logic to all kinds of declarations... definitely function and class declarations. Notably, a file-header-like comment is already preserved, so for import declarations you’d only be changing the behavior of ones that aren’t the first non-comment syntax in the file. But I think if the logic you wrote holds for variable statements, I don’t see why it wouldn’t for imports too?

One additional idea would be to try to look at where blank lines occur and use that as a heuristic. Consider the difference between these three:

```ts
const a = 0;
// comment here
const unused = 1;
if (a) {
  return;
}
```

```ts
const a = 0;

// comment here
const unused = 1;
if (a) {
  return;
}
```

```ts
const a = 0;

// comment here
const unused = 1;

if (a) {
  return;
}
```

- **First example.** This one gives me basically no information about the relevance of the comment. Best to leave it alone (which this PR currently does).

- **Second example.** Maybe the comment is about `unused`, but it’s quite possible it’s about the next group of non-blank lines as a whole, so it’s safer to leave it (which this PR does).

- **Third example.** To me, this looks clearly like the comment belongs to `unused`. I would delete it along with the declaration.

I don’t know if that logic is too fuzzy; I’ll leave it to you to consider.

**Comment by mjbvz** [comment]
Thanks for taking a look. A few thoughts on the behavior:

- I believe this should apply to imports as well

- It's probably best to be conservative when choosing to delete a comment (JSDoc being the one clear example where we should delete comments). I would not mind preserving the comments in all three cases @andrewbranch outlined. I'm not sure if it would feel odd to have different behavior in these three cases or if could make it just feel natural

**Comment by jessetrinity** [comment]
Thanks for the feedback!

I agree that the single line comment directly preceding the unused declaration seems like it belongs to it, and I would probably want it deleted. I'm hesitant about it though, because I think it does assume judicious use of whitespace. Surely both of these people exist:

```ts
// Section Header
function f1(){
}

function f2(){
}
```

```ts
// Section Header

function f1(){
}

function f2(){
}
```

I wonder if making this decision goes against the spirit of the issue, which is that a user expects this fix to remove unused code, not comments (JSDoc comments being the exception).

**Comment by andrewbranch** [comment]
I think that’s fine, and like Matt said, deleting less is better when in doubt.

**Comment by jessetrinity** [comment]
The only issue that I'm still running into is `convertFunctionToEs6Class-server.ts` failing because the `\r` after `// Comment` gets deleted:
```ts
// Comment\r
class fn {\r
    constructor() {\r
        this.baz = 10;\r
    }\r
    bar() {\r
        console.log('hello world');\r
    }\r
}\r
```

There is probably some issue with the whitespace on the synthetic node because the new logic to preserve the start line shouldn't touch the new line characters from the previous line.

**Comment by jessetrinity** [comment]
The type I added did change the public api. I don't know how strict we are about that...

File: src/compiler/types.ts [hunk 2]
```diff
@@ -2479,6 +2479,8 @@ namespace ts {
         moduleSpecifier: Expression;
     }
 
+    export type ImportLikeDeclaration = ImportDeclaration | ImportEqualsDeclaration;
```
Comment (sheetalkamat) [inline src/compiler/types.ts]: There is already `AnyImportSyntax` and `isAnyImportSyntax`

File: src/services/textChanges.ts [hunk 3]
```diff
@@ -1296,6 +1305,11 @@ namespace ts.textChanges {
                     deleteNode(changes, sourceFile, node, { leadingTriviaOption: LeadingTriviaOption.Exclude });
                     break;
 
+                case SyntaxKind.ClassDeclaration:
+                case SyntaxKind.FunctionDeclaration:
+                    deleteNode(changes, sourceFile, node, { leadingTriviaOption: hasJSDocNodes(node) ? LeadingTriviaOption.IncludeAll : LeadingTriviaOption.StartLineOnly });
```
Comment (andrewbranch) [inline src/services/textChanges.ts]: The conditional between `IncludeAll` and `StartLineOnly` makes me think you might need to take a look at cases like this:

```ts
// don't want to delete this comment

/** @param p delete this comment */
function unusedFunction(p) { }
```

Comment (jessetrinity) [reply src/services/textChanges.ts]: Good catch - I'm thinking about this wrong.

Comment (jessetrinity) [reply src/services/textChanges.ts]: I added another leading trivia option `JSDoc` to remove all JSDoc comments which belong to a node.

```ts
// singleLine1
/**
* JSDoc1
*/
// singleLine2
/**
* JSDoc2
*/
function f(){}
```

now becomes

```ts|
// singleLine1
```

Seems like removing `singleLine2` is appropriate if we remove all JSDoc comments belonging to that node. Otherwise, only deleting `JSDoc2` (and leaving `JSDoc2`) also seems sane...

Comment (andrewbranch) [reply src/services/textChanges.ts]: Yeah, the weirder the scenario, the more approaches there are that seem reasonable. If in doubt I’d go conservative and delete less, but 🤷‍♂
