### PR TITLE
fix(45917): String literal completions missing when last argument of a call is followed by a comma

### LINKED ISSUE #45917: String literal completions missing when last argument of a call is followed by a comma
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: win 10 version 2004

Steps to Reproduce:
Suggestions not shown if arguments of a method are on multiple lines and the last argument is followed by a comma

image
image

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45917

### CODE REVIEW

File: src/services/stringCompletions.ts [hunk 1]
```diff
@@ -261,9 +261,12 @@ namespace ts.Completions.StringCompletions {
 
         const uniques = new Map<string, true>();
         const candidates: Signature[] = [];
-        checker.getResolvedSignature(argumentInfo.invocation, candidates, argumentInfo.argumentCount);
+        const invocation = argumentInfo.invocation as NewExpression | CallExpression;
+        // omit trailing comma from the argument count
+        const argumentCount = argumentInfo.argumentCount - (invocation.arguments?.hasTrailingComma ? 1 : 0);
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:266]: There's something a little bit backwards here - we are leveraging a bunch of the logic of signature help, which I'm pretty sure gives us the wrong `argumentCount` because it has to account for signature help for when a user is in the last position of a signature and you intend to add an argument; but because of that, we have to then re-adjust the argument count. So we're just hacking on the hack of signature help.

I would love to separate completions logic out from `SignatureHelp` more, but I'd rather not see the full refactor in this PR. It seems like the adjustment should actually happen in `signatureHelp.ts` - specifically in `getArgumentInfoForCompletions` (https://github.com/microsoft/TypeScript/blob/1fe9bfdd0ee0ecf9dff23a40c0066645719e46b9/src/services/signatureHelp.ts#L166).

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

File: src/services/stringCompletions.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/stringCompletions.ts:266]: @DanielRosenwasser Could you look at my previous comment?

Comment (DanielRosenwasser) [reply src/services/stringCompletions.ts:266]: Well I think that `getArgumentInfoForCompletions` is the place that should be doing the decrementing - only string literal completions relies on it right?

Comment (a-tarasyuk) [reply src/services/stringCompletions.ts:266]: Also, `completions.ts` relies on it

Comment (a-tarasyuk) [reply src/services/stringCompletions.ts]: Added changes to `signatureHelp`. If the position is in the string "/**/", then the comma of the last child element is ignored. Does that make sense?

File: src/services/signatureHelp.ts [hunk 2]
```diff
@@ -372,7 +372,7 @@ namespace ts.SignatureHelp {
         return argumentIndex;
     }
 
-    function getArgumentCount(argumentsList: Node) {
+    function getArgumentCount(argumentsList: Node, skipTrailingComma: boolean) {
```
Comment (DanielRosenwasser) [inline src/services/signatureHelp.ts:375]:
```suggestion
    function getArgumentCount(argumentsList: Node, ignoreTrailingComma: boolean) {
```

File: src/services/signatureHelp.ts [hunk 3]
```diff
@@ -387,10 +387,9 @@ namespace ts.SignatureHelp {
         const listChildren = argumentsList.getChildren();
 
         let argumentCount = countWhere(listChildren, arg => arg.kind !== SyntaxKind.CommaToken);
-        if (listChildren.length > 0 && last(listChildren).kind === SyntaxKind.CommaToken) {
+        if (!skipTrailingComma && listChildren.length > 0 && last(listChildren).kind === SyntaxKind.CommaToken) {
```
Comment (DanielRosenwasser) [inline src/services/signatureHelp.ts:390]:
```suggestion
        if (!ignoreTrailingComma && listChildren.length > 0 && last(listChildren).kind === SyntaxKind.CommaToken) {
```

File: src/services/signatureHelp.ts [hunk 4]
```diff
@@ -169,12 +169,12 @@ namespace ts.SignatureHelp {
...
     }
 
-    function getArgumentOrParameterListInfo(node: Node, sourceFile: SourceFile): { readonly list: Node, readonly argumentIndex: number, readonly argumentCount: number, readonly argumentsSpan: TextSpan } | undefined {
+    function getArgumentOrParameterListInfo(node: Node, position: number, sourceFile: SourceFile): { readonly list: Node, readonly argumentIndex: number, readonly argumentCount: number, readonly argumentsSpan: TextSpan } | undefined {
         const info = getArgumentOrParameterListAndIndex(node, sourceFile);
         if (!info) return undefined;
         const { list, argumentIndex } = info;
 
-        const argumentCount = getArgumentCount(list);
+        const argumentCount = getArgumentCount(list, isInString(sourceFile, position, node));
```
Comment (DanielRosenwasser) [inline src/services/signatureHelp.ts:177]:
```suggestion
        const argumentCount = getArgumentCount(list, /*ignoreTrailingComma*/ isInString(sourceFile, position, node));
```

Comment (DanielRosenwasser) [reply src/services/signatureHelp.ts:177]: Maybe alternatively
```suggestion
        const argumentCount = getArgumentCount(list, /*trailingCommaAffectsArity*/ 
 !isInString(sourceFile, position, node));
```

with the same corresponding changes elsewhere

File: src/services/signatureHelp.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/services/signatureHelp.ts:375]: alternative

```suggestion
    function getArgumentCount(argumentsList: Node, trailingCommaAffectsArity: boolean) {
```

File: src/services/signatureHelp.ts (hunk 3 above)
Comment (DanielRosenwasser) [reply src/services/signatureHelp.ts:390]: alternative

```suggestion
        if (trailingCommaAffectsArity && listChildren.length > 0 && last(listChildren).kind === SyntaxKind.CommaToken) {
```

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/stringCompletions.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/stringCompletions.ts]: @DanielRosenwasser I've renamed the parameter.
