### PR TITLE
Optimize intersections of unions of unit types

### LINKED ISSUE #23977: indexing with T extends keyof <Large Union> causes OOM
This breaks `glimmer`, and thereby our RWC (once sufficiently fixed in other ways)

**Code**

Isolated repro (needs `dom` lib for `ElementTagNameMap` and associated types):
```ts
export function assertIsElement(node: Node | null): node is Element {
    let nodeType = node === null ? null : node.nodeType;
    return nodeType === 1;
}
  
export function assertNodeTagName<
    T extends keyof ElementTagNameMap,
    U extends ElementTagNameMap[T]>(node: Node | null, tagName: T): node is U {
    if (assertIsElement(node)) {
        const nodeTagName = node.tagName.toLowerCase();
         return nodeTagName === tagName;
    }
    return false;
}
  
export function assertNodeProperty<
    T extends keyof ElementTagNameMap,
    P extends keyof ElementTagNameMap[T],
    V extends HTMLElementTagNameMap[T][P]>(node: Node | null, tagName: T, prop: P, value: V) {
    if (assertNodeTagName(node, tagName)) {
        node[prop];
    }
}
```

**Expected behavior:**
No crash.

**Actual behavior:**
OOM crash after a _very_ long delay.

Preliminary investigation shows the OOM occurs when we try to get the distributed form of `keyof <Large Union>` - namely the process is defined recursively, so when the union has ~170 members, we create _170 intermediate types_ (flattening one member at a time, while also wasting time recalculating type flags and other bits we will never need) before getting the final, distributed result. Now, picture doing this on every relation comparison operation for `P` (this distribution is uncached), and _multiplying it_ for `V` in `assertNodeProperty` - the complexity is huge.

cc @DanielRosenwasser since I think you care about when we break glimmer.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR optimizes creation of intersection types containing unions of unit types. Such types occur for example when obtaining `keyof X` where `X` is large union of object types with many properties.

Fixes #23977.

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -3674,6 +3674,8 @@ namespace ts {
         ContainsAnyFunctionType = 1 << 26,  // Type is or contains the anyFunctionType
         NonPrimitive            = 1 << 27,  // intrinsic object type
         /* @internal */
+        UnionOfUnitTypes        = 1 << 28,  // Type is union of unit types
```
Comment (weswigham) [inline src/compiler/types.ts]: With this, `TypeFlags` is full. We're going to need a new field for flags like this (very) soon (as I don't see any that are obviously `ObjectFlags`).

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -8441,6 +8441,27 @@ namespace ts {
...
+            while (i > unionIndex) {
+                const t = types[i];
+                if (t.flags & TypeFlags.UnionOfUnitTypes) {
+                    intersection = filter(intersection, u => containsType((<UnionType>t).types, u));
+                    orderedRemoveItemAt(types, i);
+                }
+                i--;
+            }
+            if (intersection !== unionType.types) {
+                types[unionIndex] = getUnionTypeFromSortedList(intersection, unionType.flags & TypeFlags.UnionOfUnitTypes);
```
Comment (weswigham) [inline src/compiler/checker.ts]: It's worth a comment that we skip over `getUnionType` and call `getUnionTypeFromSortedList` directly here because we believe we've already replicated its work in a more efficient fashion.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -8359,7 +8359,7 @@ namespace ts {
         }
 
         // This function assumes the constituent type list is sorted and deduplicated.
-        function getUnionTypeFromSortedList(types: Type[], aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
+        function getUnionTypeFromSortedList(types: Type[], unionOfUnitTypes: TypeFlags, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Possible optimization: `unionOfUnitTypes` should just be `additionalFlags`, and we should calculate `getPropagatingFlagsOfTypes` piece-wise while doing `includes`, and just pass them in (rather then making _another_ pass over the type here to calculate them).... although I know right now to save flag space we re-purpose the propagating flags during include calculation, which could make that.... hard.

**Comment by weswigham** [comment]
Ah! before i forget! This has the same downside my PR has (which I asked about being worth doing): It doesn't handle a union containing `symbol` or `number` (or other primitives), which is potentially problematic, since `keyof` (the easiest way to make a huge union) will return at least `number`. For example:
```ts
// @strict: true
// Modified repro from #23977

declare global {
    interface ElementTagNameMap {
        [index: number]: HTMLElement
    }

    interface HTMLElement {
        [index: number]: HTMLElement;
    }
}

export function assertIsElement(node: Node | null): node is Element {
    let nodeType = node === null ? null : node.nodeType;
    return nodeType === 1;
}
  
export function assertNodeTagName<
    T extends keyof ElementTagNameMap,
    U extends ElementTagNameMap[T]>(node: Node | null, tagName: T): node is U {
    if (assertIsElement(node)) {
        const nodeTagName = node.tagName.toLowerCase();
         return nodeTagName === tagName;
    }
    return false;
}
  
export function assertNodeProperty<
    T extends keyof ElementTagNameMap,
    P extends keyof ElementTagNameMap[T],
    V extends HTMLElementTagNameMap[T][P]>(node: Node | null, tagName: T, prop: P, value: V) {
    if (assertNodeTagName(node, tagName)) {
        node[prop];
    }
}
```
will still happily spin forever.

It's probably worth fixing - it doesn't take too deep an object structure before this becomes problematic, and a single numeric indexer foiling the optimization is not great.

File: src/compiler/types.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/types.ts]: Well, `TypeFlags` being full is nothing new. Seems like it has been for the last many years. I actually think it is fine to put all of the flags to good use and then work out alternate solutions as the need arises. This particular flag could easily be moved to a property local to union types, but there's no reason to do so now.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, but I don't really want to mess with that now.

**Comment by ahejlsberg** [comment]
@mhegazy @weswigham Adding generalized support for `string`, `number`, and `symbol` is going to add a non-trivial amount of complexity. I'm still mulling over the best algorithm, but meanwhile I think we should merge the PR as it sits now and get the real world bug resolved.

**Comment by mhegazy** [comment]
sounds good to me.
