### PR TITLE
Enhance type argument completions

### LINKED ISSUE #34771: No IntelliSense for generic literal types
From https://github.com/microsoft/vscode/issues/83375

**TypeScript Version:**  typescript@3.8.0-dev.20191026

**Search Terms:**
- suggest / completions
- intellisense
- generic

**Repo**
For the typescript:

```ts
function test<T extends "x" | "y">() {}

test<''>
```

1. Trigger intellisense inside the quotes in `test<''>`

**Expected behavior:**
Suggestions for `x` and `y` returned. 

**Actual behavior:**
No suggestions returned

### LINKED ISSUE #52898: No string completions in type arguments where constrained to string literal union
A friend of mine recently tried using JSX generics and it seems like the fix in #34958 did not work for them.

Here is an oversimplified code snippet that replicates the issue. We've tried this in two different machines and neither worked:

```
import * as React from "react"

type Variations = "hello" | "baaaaa" | "click"

const MyGeneric = <T extends Variations>({  }) => {
  return <div></div>
}

const Issue = () => {
  return <MyGeneric<"ctrl+space should bring up suggestions here">></MyGeneric>
}
```

_Originally posted by @varemenos in https://github.com/microsoft/TypeScript/issues/34110#issuecomment-1436055385_

### LINKED ISSUE #56299: No completions from `tsserver` for property values in generic type arguments
### 🔎 Search Terms

"tsserver", "generic object completion", "generic intellisense", "generic typeahead", "generic completion", "generic object properties", "object property completion", "typescript server", "typescript lsp"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about typeahead support for generic type arguments.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEEEA8MoQB7AgOwCYGcoByAe2wiKgB9jgB3EogPigF5YAoUSWeAIRRpMOAlADeUMACcSYAFzEyFarQaUAvi3YwOHAPR6ogUHIoAcRIlcCgMIkAtmAA2EYAEsyhaSQBur3BFwueCgAUXQAQwdnBDZeSGQiZl0DKEAZcig+cKsoWyiXd2xCADkAeVQvX39A7mgwyKcIPli4SAEJL3liDSYgA

### 💻 Code

```ts
type TypeA<T extends 'one' | 'two'> = T
type TypeB<T extends { prop: 'one' | 'two' }> = T

// ✅ Good: Completions provided
type ExampleA = TypeA<''>

// ❌ Bad: Completions NOT provided
type ExampleB = TypeB<{ prop: '' }>
```

### 🙁 Actual behavior

Getting completions between the quotes on line 5 (using `Control + Space` on Mac OS) correctly provides `'one'` and `'two'` as options.

Screenshot 2023-11-02 at 5 38 51 PM

However, doing the same between the quotes on line 8 provides no completions.

Screenshot 2023-11-02 at 5 39 05 PM

### 🙂 Expected behavior

Getting completions between the quotes on both lines 5 and 8 (using `Control + Space` on Mac OS) correctly provides `'one'` and `'two'` as options.

### Additional information about the issue

The type of `prop` is correct (`'one' | 'two'`) and if you enter an invalid value you get the correct type error. Therefore, TypeScript should have sufficient information to provide the exact same completions in both examples.

Screenshot 2023-11-02 at 5 44 00 PM

I enabled verbose `tsserver` logging in Visual Studio Code and captured the requests and responses for these completion requests.

**Line 5 Request:**
```json
{
    "seq":12,
    "type":"request",
    "command":"completionInfo",
    "arguments":{
        "file":"/Users/ryan.palmer/Desktop/Test.ts",
        "line":5,
        "offset":24,
        "includeExternalModuleExports":true,
        "includeInsertTextCompletions":true,
        "triggerKind":1
    }
}
```

**Line 5 Response:**
```json
{
    "seq":0,
    "type":"response",
    "command":"completionInfo",
    "request_seq":12,
    "success":true,
    "body":{
        "isGlobalCompletion":false,
        "isMemberCompletion":false,
        "isNewIdentifierLocation":false,
        "optionalReplacementSpan":{
            "start":{
                "line":5,
                "offset":24
            },
            "end":{
                "line":5,
                "offset":24
            }
        },
        "entries":[
            {
                "name":"one",
                "kind":"string",
                "kindModifiers":"",
                "sortText":"11",
                "replacementSpan":{
                    "start":{
                        "line":5,
                        "offset":24
                    },
                    "end":{
                        "line":5,
                        "offset":24
                    }
                }
            },
            {
                "name":"two",
                "kind":"string",
                "kindModifiers":"",
                "sortText":"11",
                "replacementSpan":{
                    "start":{
                        "line":5,
                        "offset":24
                    },
                    "end":{
                        "line":5,
                        "offset":24
                    }
                }
            }
        ]
    }
}
```

**Line 8 Request:**
```json
{
    "seq":9,
    "type":"request",
    "command":"completionInfo",
    "arguments":{
        "file":"/Users/ryan.palmer/Desktop/Test.ts",
        "line":8,
        "offset":32,
        "includeExternalModuleExports":true,
        "includeInsertTextCompletions":true,
        "triggerKind":1
    }
}
```

**Line 8 Response:**
```json
{
    "seq":0,
    "type":"response",
    "command":"completionInfo",
    "request_seq":9,
    "success":false,
    "message":"No content available."
}
```

**Line 8 Logs:**
```
Info 451  [17:32:09.801] getCompletionData: Get current token: 0.018829017877578735
Info 452  [17:32:09.801] getCompletionData: Is inside comment: 0.007900983095169067
Info 453  [17:32:09.801] getCompletionData: Get previous token: 0.10709202289581299
Info 454  [17:32:09.802] getCompletionsAtPosition: isCompletionListBlocker: 0.03820300102233887
Info 455  [17:32:09.802] Returning an empty list because completion was requested in an invalid position.
```

As you can see, the requests are both identical except for position. But the response for the request on line 8 is empty, and there is a message indicating the position is invalid.

### LINKED ISSUE #61751: Completions for type arguments of expressions
### 🔍 Search Terms

generic, function, class, call, apply, construct, "type parameter", "type argument", completion, suggestion, autocomplete, intellisense

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

#43526 implemented completions within type arguments of generic types. It would be nice to extend that behavior to the expression level, suggesting completions within type arguments of generic function calls, `new` expressions, etc.

### 📃 Motivating Example

In this code, `foo` is suggested:
```typescript
type A<T extends { foo: unknown }> = T
type _ = A<{/* trigger completions here */}>
```
([Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggPAFShAHsCA7AJgZygbygDMB7EgLigFcMBrDEgdwygF8A+KAXigQChQkKACFusOPgD0AKijAATgEsA5sojyoAYxIBbMABsIwRSQx4AFuujTJHIA))

In this code it's not:
```typescript
function f<T extends { foo: unknown }>() {}
f<{/* trigger completions here */}>()
```
([Playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMAPAFUQUwB5U2AEwGdEBvZOOALkXAGsw4B3JAXwD4AKASjNYChUpAPQAqRFABOMAOYzMkxBDgBbAA4AbTLAQkAFgsyJRwjjyA))

### Related Issues
- #52898 and #34771 both focus specifically on completions in string literals within type arguments.
- #56299 is about completions of property _values_ within type arguments, which #43526 did not implement (it only handled property names).

### PR DESCRIPTION
**Pull request by mkantor**
#43526 implemented limited support for completions within type arguments, but only for type arguments of _types_ (not values like generic function calls), and only for specific locations within the type literal (e.g. property names of object types). This pull request generalizes type argument completions such that suggestions now appear in many more scenarios, including:

- Type arguments of expressions:
  - function calls (`f<…>()`)
  - `new` expressions (`new Foo<…>()`)
  - tagged templates (``` tag<…>`blah` ```)
  - JSX elements (`<Component<…>/>`)
  - decorators (`@decorator<…> class {}`)
  - instantiation expressions (`f<…>`)
- Types of property values within type arguments (`Foo<{ x: … }>`)
- String literal types (`Foo<"…">`)
- Tuple types (`Foo<[…]>`)

Suggested completions are derived from the relevant type parameter's constraint.

This pull request subsumes #61758 and includes the additional enhancements mentioned in that pull request's description.

Fixes #61751.
Fixes #56299.
Fixes #52898.
Fixes #34771.

### CODE REVIEW

**Comment by i-ayushh18** [comment]
🤖 **AI Assistant**: Task completed: PR #62170: Enhance type argument completions

URL: https://github.com/microsoft/TypeScript/pull/6217...

**Comment by i-ayushh18** [comment]
🤖 **AI Assistant**: Task completed: PR #62170: Enhance type argument completions

URL: https://github.com/microsoft/TypeScript/pull/6217...

**Comment by mkantor** [comment]
@i-ayushh18 I don't know if this is intentional, but it seems that you have a bot which is spamming a bunch of nonsense comments across many pull requests. If it is intentional, please cut it out.

**Comment by i-ayushh18** [comment]
> @i-ayushh18 I don't know if this is intentional, but it seems that you have a bot which is spamming a bunch of nonsense comments across many pull requests. If it is intentional, please cut it out.

Sorry for the thing,a bot was responsible for that,will suspend that at latest!

**Comment by edperetokin** [comment]
I have tested this changes locally, and it works well for me.

Looking forward to seeing it merged and released soon.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -42662,12 +42704,62 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
     function getTypeArgumentConstraint(node: TypeNode): Type | undefined {
-        const typeReferenceNode = tryCast(node.parent, isTypeReferenceType);
-        if (!typeReferenceNode) return undefined;
-        const typeParameters = getTypeParametersForTypeReferenceOrImport(typeReferenceNode);
-        if (!typeParameters) return undefined;
-        const constraint = getConstraintOfTypeParameter(typeParameters[typeReferenceNode.typeArguments!.indexOf(node)]);
-        return constraint && instantiateType(constraint, createTypeMapper(typeParameters, getEffectiveTypeArguments(typeReferenceNode, typeParameters)));
+        let typeArgumentPosition;
+        if (
+            "typeArguments" in node.parent && // eslint-disable-line local/no-in-operator
```
Comment (jakebailey) [inline src/compiler/checker.ts:42709]: We typically avoid these kinds of checks; is there no helper that achieves the same thing? Or at least, a switch case?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -42624,6 +42624,48 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return undefined;
     }
 
+    function getSignaturesFromCallLike(node: CallLikeExpression): readonly Signature[] {
```
Comment (jakebailey) [inline src/compiler/checker.ts:42627]: It feels suspicious that this is the first time we'd need a func like this; there's nothing else that does this? Not just `getResolvedSignature`?

File: src/compiler/checker.ts (hunk 1 above)
Comment (mkantor) [reply src/compiler/checker.ts:42709]: I was originally calling [`hasTypeArguments`](https://github.com/microsoft/TypeScript/blob/e39d5775b68800a3f8b57aab4734a770c4383a80/src/compiler/utilities.ts#L4766-L4768) here, but noticed that it's buggy and dropped it. For details, see the commit message of 53d3f29846c8f4d2085a840c8851797b51b0e4d8 and the commentary in https://github.com/microsoft/TypeScript/pull/61758#discussion_r2104722665 (note that 53d3f29846c8f4d2085a840c8851797b51b0e4d8 isn't included in this branch).

However, some code change I made in the meantime must have sidestepped those issues, as I just tried `hasTypeArguments` here again and everything seems copacetic.

I'll push a commit switching back to `hasTypeArguments`, but since we're on the subject: should anything be done about its sketchiness? Maybe it's made moot by the Go rewrite (where a `hasTypeArguments` equivalent would presumably work differently).

File: src/compiler/checker.ts (hunk 2 above)
Comment (mkantor) [reply src/compiler/checker.ts:42627]: I need the original un-instantiated generic signatures, but `getResolvedSignature` always gives me concrete ones, even with `CheckMode.SkipGenericFunctions`.

When asking for completions there is a (possibly-incomplete) type argument already present (the node looks something like `f<{}>()`). I tried artificially clearing out the type argument list before calling `getResolvedSignature`, but that still gives me concrete signatures (with type parameters substituted for their constraints). I traced the logic for regular function calls and in that case concretion occurs within `resolveCall` (the call stack is `getResolvedSignature` → `resolveSignature` → `resolveCallExpression` → `resolveCall`).

I searched for other existing utilities that would meet my needs but came up empty. It's entirely possible I missed something though; I wasn't sure exactly what to look for.

Maybe I could rename `getSignaturesFromCallLike` to clarify how it's different from `getResolvedSignature`. Something like `getUninstantiatedSignatures`, perhaps? A docblock might also help. Let me know if you have any specific suggestions on these fronts.

File: src/compiler/checker.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/checker.ts:42709]: `hasTypeArguments` doesn't even exist in the Go codebase. Notably `hasTypeArguments` is actually entirely unused in this repo, so I think nobody has ever even noticed it's broken and tried to fix it.

File: src/compiler/checker.ts (hunk 2 above)
Comment (mkantor) [reply src/compiler/checker.ts:42627]: I went ahead and renamed this function to `getUninstantiatedSignatures` and added a docblock. I rebased while I was at it.

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by mkantor** [comment]
Thanks for reviewing/merging!
