### PR TITLE
fix quickinfo of narrowed private filed

### LINKED ISSUE #43346: Tooltip on private fields not showing the correct type after narrowing
# Bug Report

### 🔎 Search Terms

private field, class, narrow, narrowing

### 🕗 Version & Regression Information
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210316#code/MYGwhgzhAEAqCmEAuBhcVoG8CwAoaB0AxAA4BOAlgG5hLwAKZA9ifGUgJ4Bc0ylAdgHMA2gF1oAH2j8AriBABuPIWgkZAIxAVgjFm048+FIWMnS5ivMsLAm-PjOBImZABQBKLNZUEkACwoIADpSSho6XVZ2DmgAXnN5JXwfXwDgtU1tSP0Y+NlE72gAXytk30QkAFl4fyYAEw8vMp8KADNoV39AkPJqWgZmKM44vIt3QpSCMhqZMn4kyeg2jq70jS0dQZyRhJBx5sXppFn50sXVnrD+7OiFaAB6e94kARFxKXyQCcILjI2bzh3R7PV5iM6TWz2JDQMBxaAXUJ9CJbW7fAhgIFPIwmUSFEq4IpAA)

### 💻 Code

```ts
class TestClass {
    #privateProperty: string[] | null;
    publicProperty: string[] | null;

    constructor() {
        this.#privateProperty = null;
        this.publicProperty = null;
    }

    testMethod() {
        if (this.#privateProperty === null)
            return;
        if (this.publicProperty === null)
            return;

        this.#privateProperty; // string[] | null
        this.publicProperty; // string[]

        const a = this.#privateProperty;
        a; // string[]
    }
}
```

### 🙁 Actual behavior

`this.#privateProperty` is `string[] | null` even after narrowing down the type from `if`. Also assigning `this.#privateProperty` to other variable fixes the type.

### 🙂 Expected behavior

`this.#privateProperty` should be `string[]` after narrowing down

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #43346

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
This PR is similar. https://github.com/microsoft/TypeScript/pull/40014

File: tests/cases/fourslash/quickInfoOnNarrowedType.ts [hunk 1]
```diff
@@ -18,13 +18,26 @@
 ////   /*6*/s;
 ////}
 
+////class TestClass {
```
Comment (hantatsang) [inline tests/cases/fourslash/quickInfoOnNarrowedType.ts:21]: Use generic _Foo/Bar/Baz_ for test class name instead?

Comment (ShuiRuTian) [reply tests/cases/fourslash/quickInfoOnNarrowedType.ts:21]: Good suggestion, why not?

**Review by sandersn — APPROVED** [review]
