### PR TITLE
Fix `insertNodeAtClassStart` for empty class with comment

### LINKED ISSUE #23333: Typescript: Code action implement inherited abstract class will override the class body
_From @yaohaizh on April 11, 2018 1:54_

- VSCode Version:  1.22
- OS Version: Windows 10 

Steps to Reproduce:

1.  Typescript code: 
```typescript
abstract class Base {
    abstract getProperty() : void;
}


class Subclass extends Base {
    // This is comment
}
```
2. Select the SubClass and trigger the code action, invoke it 

Expected:  The new code should insert after the comment or other existing code

Actually: The existing code is overwrote. 

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#47623_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #23333
**Review #23343 before reviewing this**

### CODE REVIEW

File: tests/cases/fourslash/codeFixClassImplementInterfaceComments.ts [hunk 1]
```diff
@@ -36,9 +36,9 @@ verify.codeFix({
         /**close-brace prefix*/ }
 /**close-brace prefix*/ }
 class C implements N.I {
-    /** property prefix */ a /** colon prefix */: N.E.a;
```
Comment (andy-ms) [inline tests/cases/fourslash/codeFixClassImplementInterfaceComments.ts]: This was accidentally changed in #20338 to include the comments -- but we really shouldn't be copying the comments over from the base class. The change to `helpers.ts` makes us no longer copy the comments, and is a basically independent change to the rest of this PR. Discovered this because the presence of a comment made the formatter no longer insert indentation for some reason.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -4020,12 +4020,14 @@ namespace ts {
     }
 
     /** Add a value to a set, and return true if it wasn't already present. */
-    export function addToSeen(seen: Map<true>, key: string | number): boolean {
+    export function addToSeen(seen: Map<true>, key: string | number): boolean;
+    export function addToSeen<T>(seen: Map<T>, key: string | number, value: T): boolean;
+    export function addToSeen<T>(seen: Map<T>, key: string | number, value: T = true as any): boolean {
```
Comment (amcasey) [inline src/compiler/utilities.ts]: For my own edification, why not use `{}` as the default value?

File: src/services/textChanges.ts [hunk 3]
```diff
@@ -435,21 +433,20 @@ namespace ts.textChanges {
...
-                if (newMembers) {
-                    Debug.assert(newMembers.sourceFile === sourceFile && newMembers.cls === cls);
-                    newMembers.members.push(newElement);
+            const clsStart = cls.getStart(sourceFile);
+            let prefix = "";
+            let suffix = this.newLineCharacter;
+            if (addToSeen(this.classesWithNodesInsertedAtStart, getNodeId(cls), cls)) {
+                prefix = this.newLineCharacter;
+                // For `class C {\n}`, don't add the trailing "\n"
+                if (cls.members.length === 0 && !(positionsAreOnSameLine as any)(...getClassBraceEnds(cls, sourceFile), sourceFile)) { // TODO: GH#4130 remove 'as any'
```
Comment (amcasey) [inline src/services/textChanges.ts]: Does the number of members matter?  It seems like you want to omit the linebreak as long as the class is on a single line.

File: src/services/textChanges.ts [hunk 4]
```diff
@@ -435,21 +433,20 @@ namespace ts.textChanges {
...
                 }
-                else {
-                    this.nodesInsertedAtClassStarts.set(id, { sourceFile, cls, members: [newElement] });
-                }
-            }
-            else {
-                this.insertNodeBefore(sourceFile, firstMember, newElement);
             }
+
+            const indentation = formatting.SmartIndenter.findFirstNonWhitespaceColumn(getLineStartPositionForPosition(clsStart, sourceFile), clsStart, sourceFile, this.formatContext.options)
```
Comment (amcasey) [inline src/services/textChanges.ts]: Should the indentation be omitted if the class is on a single line?

File: src/services/textChanges.ts [hunk 5]
```diff
@@ -601,12 +598,14 @@ namespace ts.textChanges {
...
-            this.nodesInsertedAtClassStarts.forEach(({ sourceFile, cls, members }) => {
-                const newCls = cls.kind === SyntaxKind.ClassDeclaration
-                    ? updateClassDeclaration(cls, cls.decorators, cls.modifiers, cls.name, cls.typeParameters, cls.heritageClauses, members)
-                    : updateClassExpression(cls, cls.modifiers, cls.name, cls.typeParameters, cls.heritageClauses, members);
-                this.replaceNode(sourceFile, cls, newCls);
+        private finishClassesWithNodesInsertedAtStart(): void {
+            this.classesWithNodesInsertedAtStart.forEach(cls => {
+                const sourceFile = cls.getSourceFile();
+                const [openBraceEnd, closeBraceEnd] = getClassBraceEnds(cls, sourceFile);
+                // For `class C { }` remove the whitespace inside the braces.
```
Comment (amcasey) [inline src/services/textChanges.ts]: 1) Why?  I like having a space there.
 2) Shouldn't this be handled by the formatter (or at least consume the formatting options)?

File: src/compiler/utilities.ts (hunk 2 above)
Comment (andy-ms) [reply src/compiler/utilities.ts]: I've been using `Map<true>` everywhere for sets; to me `Map<{}>` would imply actually being a map from `string` to something, where we didn't specify that something.

File: src/services/textChanges.ts (hunk 3 above)
Comment (andy-ms) [reply src/services/textChanges.ts]: It's the opposite -- if the class *is* on a single line I want to add line breaks on both sides to get `{\n 
   member\n}`; if the class is already multiline I only want the first line break.

File: src/services/textChanges.ts (hunk 4 above)
Comment (andy-ms) [reply src/services/textChanges.ts]: It's about to be multiline since we're adding a member, and that new member should be indented.

File: src/services/textChanges.ts (hunk 5 above)
Comment (andy-ms) [reply src/services/textChanges.ts]: Leaving the space would result in the class ending in `\n }` instead of just `\n}` The formatter won't handle this since it only formats the new nodes we're adding, not the existing whitespace surrounding them.

**Comment by andy-ms** [comment]
@amcasey Could you update your review?
