### PR TITLE
Strip "/index" from import fix module specifiers

### LINKED ISSUE #19957: FEATURE: auto import or import missing index correctly
**TypeScript Version:**  2.6.1

**Code**
```ts
import {type} from './myFeatureDir/index';
```

```ts
import {type} from './myFeatureDir';
```

**Expected behavior:**
If you have directory containing index.ts (used for reexports types), because directory has many files with exported types and you do not want to have many imports, but only one index will come handy. I would expect that *auto import* or *fix missing import* would generate import like this `import {type} from './myFeatureDir';` instead of `import {type} from './myFeatureDir/index';`

**Actual behavior:**
Currently when i use quick fix to import missing type i get `import {type} from './myFeatureDir/index';`, which works but without that index it would be much better :).

Thank you.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19957

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -322,7 +322,7 @@ namespace ts.codefix {
             tryGetModuleNameAsNodeModule(options, moduleFileName, host, getCanonicalFileName, sourceDirectory) ||
             tryGetModuleNameFromBaseUrl(options, moduleFileName, getCanonicalFileName) ||
             options.rootDirs && tryGetModuleNameFromRootDirs(options.rootDirs, moduleFileName, sourceDirectory, getCanonicalFileName) ||
-            removeFileExtension(getRelativePath(moduleFileName, sourceDirectory, getCanonicalFileName));
+            removeExtensionAndIndexPostFix(getRelativePath(moduleFileName, sourceDirectory, getCanonicalFileName));
```
Comment (sheetalkamat) [inline src/services/codefixes/importFixes.ts]: You shouldnt be removing file ```index``` when module resolution is not node_modules right? Because classicModuleResolver doesnt auto lookup for file with name of index in moduleName directory?

**Comment by sheetalkamat** [comment]
Needs test case for classic node resolver for
- when it has node_modules folder and contains index file and its not part of the import fix
- normal case where the import fix is suggested correctly
