### PR TITLE
Fix import statement completions followed by interface declaration

### LINKED ISSUE #48904: import Suggestions don't work if typed before the interface declaration Typescript
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.66.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create typescript file with minimal code and one import:

```typescript
import { Accordion } from "@mui/material";


interface Props {
    opened: boolean;
    onClose: (ko: string) => void;
}


export { }
```

2. start typing `import`  something before the interface declaration and try auto complete. Says 'no suggestions':
image

3. try the same, but this time before the first import line you already have. Import is suggesting:
image

4. Try the same after the interface declaration. Also working:
image

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #48904

### CODE REVIEW

File: tests/cases/fourslash/importStatementCompletions1.ts [hunk 1]
```diff
@@ -22,37 +22,37 @@
...
-//       name: "type",
-//       sortText: completion.SortText.GlobalsOrKeywords,
-//     }] : []],
-//     preferences: {
-//       includeCompletionsForImportStatements: true,
-//       includeInsertTextCompletions: true,
-//       includeCompletionsWithSnippetText: true,
-//     }
-//   });
-// });
```
Comment (andrewbranch) [inline tests/cases/fourslash/importStatementCompletions1.ts:55]: I guess I had previously commented this out while debugging so I could skip straight to the later tests, then forgot to uncomment. Luckily they were all still passing 😅

File: src/services/completions.ts [hunk 2]
```diff
@@ -4299,6 +4298,34 @@ namespace ts.Completions {
             }
             return undefined;
         }
+
+    }
+
+    function getSingleLineReplacementSpanForImportCompletionNode(node: ImportDeclaration | ImportEqualsDeclaration | ImportSpecifier | Token<SyntaxKind.ImportKeyword> | undefined) {
+        if (!node) return undefined;
+        const top = (findAncestor(node, or(isImportDeclaration, isImportEqualsDeclaration)) || node) as ImportDeclaration | ImportEqualsDeclaration | Token<SyntaxKind.ImportKeyword>;
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:4306]: Would be cool if `or` combined type predicates

also

```suggestion
        const top = (findAncestor(node, or(isImportDeclaration, isImportEqualsDeclaration)) ?? node) as ImportDeclaration | ImportEqualsDeclaration | Token<SyntaxKind.ImportKeyword>;
```

File: src/services/completions.ts [hunk 3]
```diff
@@ -4299,6 +4298,34 @@ namespace ts.Completions {
...
+        if (!node) return undefined;
+        const top = (findAncestor(node, or(isImportDeclaration, isImportEqualsDeclaration)) || node) as ImportDeclaration | ImportEqualsDeclaration | Token<SyntaxKind.ImportKeyword>;
+        const sourceFile = top.getSourceFile();
+        if (rangeIsOnSingleLine(top, sourceFile)) {
+            return createTextSpanFromNode(top, sourceFile);
+        }
+        // Import keyword alone was necessarily on one line
+        Debug.assert(top.kind !== SyntaxKind.ImportKeyword);
+        const withoutModuleSpecifier: TextRange = {
+            pos: top.getFirstToken()!.getStart(),
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:4314]:
```suggestion
            pos: top.getFirstToken(sourceFile)!.getStart(sourceFile),

```

File: src/services/completions.ts [hunk 4]
```diff
@@ -4299,6 +4298,34 @@ namespace ts.Completions {
             }
             return undefined;
         }
+
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:4301]: Intentional?

```suggestion
        }
```

or

```suggestion
        }
        return undefined;
```

File: src/services/completions.ts [hunk 5]
```diff
@@ -4299,6 +4298,34 @@ namespace ts.Completions {
...
+        const withoutModuleSpecifier: TextRange = {
+            pos: top.getFirstToken()!.getStart(),
+            end: top.kind === SyntaxKind.ImportDeclaration ? top.moduleSpecifier.pos : top.moduleReference.pos,
+        };
+        // The module specifier/reference was previously found to be missing, empty, or
+        // not a string literal - in this last case, it's likely that statement on a following
+        // line was parsed as the module specifier of a partially-typed import, e.g.
+        //   import Foo|
+        //   interface Blah {}
+        // This appears to be a multiline-import, and editors can't replace multiple lines.
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:4322]: > editors can't replace multiple lines

Is this detail actually relevant to the change? It sounds like even if editors could do that, you would still want to assume that the next line is a separate statement and recover appropriately, right?

File: src/services/completions.ts (hunk 3 above)
Comment (andrewbranch) [reply src/services/completions.ts:4314]: It’s necessarily a parse tree node, so this is never needed IIUC.

File: src/services/completions.ts (hunk 5 above)
Comment (andrewbranch) [reply src/services/completions.ts:4322]: Yeah, fair; but it explains why the failure mode is “no completions” rather than “overwriting later declarations.”

File: src/services/completions.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/completions.ts:4306]: I thought I had looked at that before and found it was impossible for some reason (???) but I guess it was only impossible to do it variadically. I added overloads for 2 and 3 unary type predicate functions. It eliminated one more type assertion on another call just like this, also written by me 😅

File: src/services/completions.ts (hunk 3 above)
Comment (DanielRosenwasser) [reply src/services/completions.ts:4313]: It's more of an efficiency thing - if you don't pass in the `sourceFile` and the children aren't cached, `getFirstToken` needs to run up the parents to get the `sourceFile` to get the source text. Then `getStart` needs to run back up the tree to get the source text as well.

I guess for an import node, it doesn't matter much though. 😅

**Review by sandersn — APPROVED** [review]
Basically looks good, but I can't tell if an unclosed import list would behave the same as the two existing test cases.

File: tests/cases/fourslash/importStatementCompletions2.ts [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+// @Filename: /button.ts
+//// export function Button() {}
+
+// @Filename: /index1.ts
+//// [|import Butt/*0*/|]
+////
+//// interface Props {}
+
+// @Filename: /index2.ts
+//// [|import { Butt/*1*/ }|]
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply tests/cases/fourslash/importStatementCompletions2.ts:12]: It does matter, and it is a little trickier to fix. I don’t think there are any silver bullets when trying to make sense of the parser recovery state for half-typed code, but maybe I can do something with the fact that non-contextual keywords can’t possibly be valid import specifiers even if they were parsed that way.

File: src/services/completions.ts [hunk 7]
```diff
@@ -4241,7 +4238,9 @@ namespace ts.Completions {
         isKeywordOnlyCompletion: boolean;
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/completions.ts:4238]: I defined it where it’s constructed rather than where it’s first referenced.

File: tests/cases/fourslash/importStatementCompletions2.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (andrewbranch) [reply tests/cases/fourslash/importStatementCompletions2.ts:13]: Latest commit handles this if you’re interested
