### PR TITLE
Revert #54442 and add a testcase

### LINKED ISSUE #61438: I triggered the Debug assertion `Revert #54442 and add a testcase with whatever triggered this` when running with `--diagnostics`
### 🔎 Search Terms

"54442", "diagnostics"

### 🕗 Version & Regression Information

- This changed between versions before and 5.8.2
- This changed in commit or PR e79b644
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about issue #54442
- I was unable to test this on prior versions because it is related to a previous issue.

### ⏯ Playground Link

_No response_

### 💻 Code

```ps1
# Almost do nothing but run this command on tests/cases/compiler
tsc --diagnostics
```

### 🙁 Actual behavior

It shows 
```
Error: Debug Failure. False expression: Revert #54442 and add a testcase with whatever triggered this
```

### 🙂 Expected behavior

compiling the project correctly

### Additional information about the issue

It seems it's related to the previous issue #54442

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #61438, reverts #54442

*Maybe* it's possible to get into this codepath in a way that doesn't trigger a different error elsewhere, thus the error isn't technically needed, but I wouldn't really want to bet on it. Issuing two errors is nonharmful.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test it

**Review by jakebailey — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -36414,7 +36414,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         // reorderCandidates fills up the candidates array directly
         reorderCandidates(signatures, candidates, callChainFlags);
         if (!isJsxOpenFragment) {
-            Debug.assert(candidates.length, "Revert #54442 and add a testcase with whatever triggered this");
+            if (!candidates.length) {
+                if (reportErrors) {
+                    diagnostics.add(getDiagnosticForCallNode(node, Diagnostics.Call_target_does_not_contain_any_signatures));
+                }
+                return resolveErrorCall(node);
+            }
```
Comment (Andarist) [inline src/compiler/checker.ts:36422]: FWIW, 2 years later, I probably agree with the sentiment shared in https://github.com/microsoft/TypeScript/pull/54442#issuecomment-3011654217

But also playing a little bit of devil's advocate - if this diagnostic did never exist, I somewhat doubt this would be the preferred fix for the reported crash. But, of course, it's not particularly important issue and it's better to fix the crash promptly without worrying about it all too much.

I took a look at what happens here:
1. `getBaseConstructorTypeOfClass` returns `typeof SomeBaseClass` (static side of the class)
2. so the `superType` computed by `resolveCallExpression` **is not** an `errorType`
3. but given there is no matching signature for those type arguments `getInstantiatedConstructorsForTypeArguments` returns an empty array

Other paths in this function specifically prevent entering `resolveCall` when the signatures are empty, so it feels like this one should do the same. Something like this would do the trick:
```diff
            if (!isErrorType(superType)) {
                // In super call, the candidate signatures are the matching arity signatures of the base constructor function instantiated
                // with the type arguments specified in the extends clause.
                const baseTypeNode = getEffectiveBaseTypeNode(getContainingClass(node)!);
                if (baseTypeNode) {
                    const baseConstructors = getInstantiatedConstructorsForTypeArguments(superType, baseTypeNode.typeArguments, baseTypeNode);
+                    if (!baseConstructors.length) {
+                        return resolveErrorCall(node);
+                    }
                    return resolveCall(node, baseConstructors, candidatesOutArray, checkMode, SignatureFlags.None);
                }
            }
            return resolveUntypedCall(node);
```

The error on the super call produced by a simple revert is slightly confusing with what quick info shows at this `super` call:
```ts
/// <reference path="fourslash.ts" />

//// export class SomeBaseClass {}
//// export interface SomeInterface {}
//// export interface MergedClass extends SomeInterface {}
//// export class MergedClass extends SomeBaseClass<any> {
////   public constructor() {
////     super/**/();
////   }
//// }

verify.quickInfoAt("", "constructor SomeBaseClass(): SomeBaseClass");
```

But also, truth to be told, the above patch doesn't change it anyhow either and it can still lead to confusing situations in which the above is still displayed but the code doesn't produce any errors for invalid super calls that don't match the display constructor signature, for example:
```ts
super('foo');
```

Why does the user would see a signature without any arguments that doesn't error on a call with arguments? Perhaps this is an extra quick info issue (or just quirk) that it prefers information from the base type over the resolved signature at the super call location?

Without any changes to the quick info's behavior an extra error at this location makes more sense but perhaps a more specialized message would make it better.

Comment (Andarist) [reply src/compiler/checker.ts:36422]: Note - I mainly posted the above because I was just curious to learn why this has happened + I think I promised to investigate any fallout from this :P So it was my duty to do so 😉 

And, of course, I'm sorry for introducing the crash in the first place
