### PR TITLE
Fix destructuring control flow analysis

### LINKED ISSUE #26379: Uncaught implicit any for computed property in destructure
**TypeScript Version:**  3.1.0-dev.20180810

**Code**

```ts
let x: boolean;
({ ["a" + "b"]: x } = 0);
x = 0["a" + "b"];
```

**Expected behavior:**

Error on both lines.

**Actual behavior:**

Error only on `0["a" + "b"]`.

### LINKED ISSUE #28792: Regression in type inference for Promise.all()
**TypeScript Version:**  3.2.1 & 3.3.0-dev.20181201

**Search Terms:**
type inference, promise, tuple

**Code**

```ts
async function f(x: number): Promise<number>{
    return x + 1;
}

async function g(s: string): Promise<string>{
    return s + "\n";
}

async function h(): Promise<string> {
    const [a, b] = await Promise.all([f(1), g("x")]).catch(() => [null, null]);
    if (a === null || b === null) throw new Error();
    return b.trim();
}
```

**Expected behavior:**
no compile error, as in TS3.1

**Actual behavior:**
```
test.ts:12:12 - error TS2339: Property 'trim' does not exist on type 'string | number'.
  Property 'trim' does not exist on type 'number'.

12   return b.trim();
              ~~~~

```

In TS3.1:
```
a: number | null
b: string | null
```

In TS3.2:
```
a: string | number | null
b: string | number | null
```

**Playground Link:** 
[here](http://www.typescriptlang.org/play/#src=async%20function%20f(x%3A%20number)%3A%20Promise%3Cnumber%3E%7B%0D%0A%20%20%20%20return%20x%20%2B%201%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20g(s%3A%20string)%3A%20Promise%3Cstring%3E%7B%0D%0A%20%20%20%20return%20s%20%2B%20%22%5Cn%22%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20h()%3A%20Promise%3Cstring%3E%20%7B%0D%0A%20%20%20%20const%20%5Ba%2C%20b%5D%20%3D%20await%20Promise.all(%5Bf(1)%2C%20g(%22x%22)%5D).catch(()%20%3D%3E%20%5Bnull%2C%20null%5D)%3B%0D%0A%20%20%20%20if%20(a%20%3D%3D%3D%20null%20%7C%7C%20b%20%3D%3D%3D%20null)%20throw%20new%20Error()%3B%0D%0A%20%20%20%20return%20b.trim()%3B%0D%0A%7D%0D%0A)
(Enable strictNullChecks to reproduce it)

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes multiple issues related to control flow analysis of destructuring declarations and assignments. Intuitively, for type checking purposes the following should always be true:

* `obj.x` is equivalent to `obj["x"]` (property access vs. element access)
* `let { x } = obj` is equivalent to `let x = obj.x` (destructuring declaration)
* `{ x } = obj` is equivalent to `x = obj.x` (destructuring assignment)

However, there were several situations where this was not the case:

```ts
function f1(obj: { a: string | undefined }) {
    if (obj.a) {
        obj = { a: undefined };
        let a1 = obj["a"];  // string (Incorrect)
        let a2 = obj.a;  // string | undefined
    }
}

function f2(obj: [number, string] | null[]) {
    let a0 = obj[0];  // number | null
    let a1 = obj[1];  // string | null
    let [b0, b1] = obj;  // string | number | null (Incorrect)
    ([a0, a1] = obj);  // Error (Incorrect)
    if (obj[0] && obj[1]) {
        let c0 = obj[0];  // number
        let c1 = obj[1];  // string
        let [d0, d1] = obj;  // string | number | null (Incorrect)
        ([c0, c1] = obj); // Error (Incorrect)
    }
}

function f3(obj: { a?: number, b?: string }) {
    if (obj.a && obj.b) {
        let { a, b } = obj;  // number, string
        ({ a, b } = obj);  // Error (Incorrect)
    }
}

function f4() {
    let x: boolean;
    ({ x } = 0);
    ({ ["x"]: x } = 0);
    ({ ["x" + ""]: x } = 0);  // No error (Incorrect)
}
```

This PR fixes all of the above. The PR changes type checking for destructuring declarations and assignments to consistently use `getIndexedAccessType` to compute the destructured type and `getFlowTypeOfReference` on a synthetic element access expression to compute the control flow type. Furthermore, the PR properly unifies all handing of property access expressions (`obj.x`) and element access expressions (`obj["x"]`) in control flow analysis, and removes the increasingly convoluted logic we needed to handle binding elements from destructuring declarations and object and array literals from destructuring assignments (they now become synthetic element access expressions).

Fixes #26379.
Fixes #28792.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14624,68 +14653,49 @@ namespace ts {
...
                 return getTypeOfSymbol(getResolvedSymbol(<Identifier>expr));
             }
-            if (expr.kind === SyntaxKind.PropertyAccessExpression) {
-                const type = getDeclaredTypeOfReference((<PropertyAccessExpression>expr).expression);
-                return type && getTypeOfPropertyOfType(type, (<PropertyAccessExpression>expr).name.escapedText);
+            if (isAccessExpression(expr)) {
+                const type = getDeclaredTypeOfReference(expr.expression);
+                if (type) {
+                    const propName = getAccessedPropertyName(expr);
+                    return propName && getTypeOfPropertyOfType(type, propName);
```
Comment (weswigham) [inline src/compiler/checker.ts]: `""` is falsy, and `getAccessedPropertyName` returns a stringish thing. This needs to use `typeof`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14704,8 +14714,8 @@ namespace ts {
             return false;
         }
 
-        function isDiscriminantProperty(type: Type | undefined, name: __String) {
-            if (type && type.flags & TypeFlags.Union) {
+        function isDiscriminantProperty(type: Type | undefined, name: __String | undefined) {
+            if (type && name && type.flags & TypeFlags.Union) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: `""` is falsy~

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -15631,19 +15641,17 @@ namespace ts {
...
             function isMatchingReferenceDiscriminant(expr: Expression, computedType: Type) {
-                if (!(computedType.flags & TypeFlags.Union) ||
-                    expr.kind !== SyntaxKind.PropertyAccessExpression && expr.kind !== SyntaxKind.ElementAccessExpression) {
+                if (!(computedType.flags & TypeFlags.Union) || !isAccessExpression(expr)) {
                     return false;
                 }
-                const access = expr as PropertyAccessExpression | ElementAccessExpression;
-                const name = getAccessedPropertyName(access);
+                const name = getAccessedPropertyName(expr);
                 if (!name) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: `""` is falsy

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -15631,19 +15641,17 @@ namespace ts {
...
                     return false;
                 }
-                return isMatchingReference(reference, access.expression) && isDiscriminantProperty(computedType, name);
+                return isMatchingReference(reference, expr.expression) && isDiscriminantProperty(computedType, name);
             }
 
-            function narrowTypeByDiscriminant(type: Type, access: PropertyAccessExpression | ElementAccessExpression, narrowType: (t: Type) => Type): Type {
+            function narrowTypeByDiscriminant(type: Type, access: AccessExpression, narrowType: (t: Type) => Type): Type {
                 const propName = getAccessedPropertyName(access);
                 if (!propName) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: `""` is falsy

File: tests/baselines/reference/unionsOfTupleTypes1.errors.txt [hunk 5]
```diff
@@ -41,18 +41,18 @@ tests/cases/conformance/types/tuple/unionsOfTupleTypes1.ts(41,18): error TS2339:
     function f1(t1: T1, t2: T2, t3: T3, t4: T4, x: number) {
         let [d10, d11, d12] = t1;  // string, number
                        ~~~
-!!! error TS2493: Tuple type '[string, number]' with length '2' cannot be assigned to tuple with length '3'.
```
Comment (weswigham) [inline tests/baselines/reference/unionsOfTupleTypes1.errors.txt]: This error message change is a regression, I believe. An explicit tuple length error here is quite desirable.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -14624,68 +14653,49 @@ namespace ts {
...
+                        isMatchingReference((<AccessExpression>source).expression, target.expression);
             }
             return false;
         }
 
-        function getAccessedPropertyName(access: PropertyAccessExpression | ElementAccessExpression): __String | undefined {
-            return isPropertyAccessExpression(access) ? access.name.escapedText :
+        function getAccessedPropertyName(access: AccessExpression): __String | undefined {
+            return access.kind === SyntaxKind.PropertyAccessExpression ? access.name.escapedText :
                 isStringLiteral(access.argumentExpression) || isNumericLiteral(access.argumentExpression) ? escapeLeadingUnderscores(access.argumentExpression.text) :
```
Comment (weswigham) [inline src/compiler/checker.ts]: While we're here, we should probably change this to `isStringOrNumericLiteralLike` so `NoSubstitutionTemplateLiteral`s can act like string literals.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Ya, that's a problem.

File: tests/baselines/reference/unionsOfTupleTypes1.errors.txt (hunk 5 above)
Comment (ahejlsberg) [reply tests/baselines/reference/unionsOfTupleTypes1.errors.txt]: I think the new error is just as good, if not better, and certainly more consistent. I always found this particular message strange as there isn't actually a tuple being assigned to. If we think it is important, we could instead improve the message we give when accessing an out-of-range tuple element in `getIndexedAccessType`.

Comment (weswigham) [reply tests/baselines/reference/unionsOfTupleTypes1.errors.txt]: We _explicitly_ added the tuple length error message to override the message it regressed to. Changing `getIndexedAccessType` to use it seems kinda appropriate.

File: tests/baselines/reference/api/typescript.d.ts [hunk 7]
```diff
@@ -3350,6 +3351,7 @@ declare namespace ts {
     function isObjectLiteralExpression(node: Node): node is ObjectLiteralExpression;
     function isPropertyAccessExpression(node: Node): node is PropertyAccessExpression;
     function isElementAccessExpression(node: Node): node is ElementAccessExpression;
+    function isAccessExpression(node: Node): node is AccessExpression;
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/api/typescript.d.ts]: Do we really need to export this from the public API?

File: tests/baselines/reference/unionsOfTupleTypes1.errors.txt (hunk 5 above)
Comment (DanielRosenwasser) [reply tests/baselines/reference/unionsOfTupleTypes1.errors.txt]: I think it would be nice to give a more specific error message if it can still be rewired into `getIndexedAccessType`:

```
Tuple type '{0}' of length '{1}' has no element at index '{2}'.

Seems pretty reasonable.

Comment (j-oliveras) [reply tests/baselines/reference/unionsOfTupleTypes1.errors.txt]: I think, like Daniel, that will be better message to avoid issues like #29058.

**Comment by ahejlsberg** [comment]
@DanielRosenwasser @weswigham Now with new and improved error message.
