### PR TITLE
Contextual typing of partially annotated signatures

### LINKED ISSUE #4241: Parameter signatures of functions in object literals are not always inferred correctly.
Hi, I ran into an issue where the types don't seem to be inferred correctly.  Consider this:
```
interface ITestHandler { (a: string, ...args: any[]) }
interface ITestHandlers { [index: string]: ITestHandler; }
class Test { Events: ITestHandlers; }
var t = new Test();
t.Events = {
     handler1: (a) => { }, // <= this works fine, 'a' is 'string'
     handler2: (a, b: string) => { } // <= 'a' is 'any', but 'b' is optional in the interface!
};
```
I expect "a" for "handler2" to be "string", but instead it is "any".  Shouldn't "a" be interred from the signature, since the "args" are of type "any", which should match any type?

Thanks.

### LINKED ISSUE #9648: Strange `this` parameter behaviour
**TypeScript Version:**  2.0.0 beta with `"noImplicitThis":  true`

**Code**

```ts
interface String {
     contains(this: string, str: string): boolean;
}

 // OK
String.prototype.contains = function (this: string, str: string): boolean { 
    return this.indexOf(element) != -1;
};

//Error: 'this' implicitly has type 'any' because it does not have a type annotation.	
String.prototype.contains = function (str: string) {
    return this.indexOf(str) != -1;
};

// OK
String.prototype.contains = function (str): boolean { 
    return this.indexOf(str) != -1;
};

// OK
String.prototype.contains = function (str) { 
    return this.indexOf(str) != -1;
};
```

Look like once you type some parameters you have to type all of them, including the `this`. 

What's the reason?

### LINKED ISSUE #9846: Allow quoted names in ambient contexts
The node module `yargs` is callable (`typeof require('yargs') === 'function'`). It also has a property named `default` that is a function.

This makes writing a definition file very difficult. You'd be inclined to write
```ts
declare function yargs(): void;
declare namespace yargs {
  /* dozens of other things */
  function default(): void; // syntax error
}
export = yargs;
```
There's not an obvious workaround that doesn't have bad side effects (e.g. rewriting the whole mess as a `var` doesn't really work in the case where there's a nested class), possibly requiring a massive restructuring of the entire file.

Wherever an identifier appears in an *ambient* context where it could have been initialized as a property, it should be allowed to be quoted. For example
```ts
export const "default": string;
declare namespace foo {
  function "with"(): string;
}
```

### LINKED ISSUE #10850: thisType of callback parameter isn't enforced if the callback has another parameter
**TypeScript Version:**  2.1.0-dev.20160910

**Code**

```ts
declare function foo(cb: (this: number, arg: string) => void): void;

foo(function (): void { this.length; }); // (1)
foo(function (arg: string): void { this.length; }); // (2)
```

`tsc -t es5 ./foo.ts`

**Expected behavior:**

Both (1) and (2) should complain about `length` not existing on `number`

**Actual behavior:** 
(1) correctly complains: `foo.ts(3,30): error TS2339: Property 'length' does not exist on type 'number'.` But there is no error for (2).

Adding `--noImplicitAny` doesn't change the result.

Adding `--noImplicitThis` gives `foo.ts(4,36): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.` which confirms that `this` in (2) is getting inferred as `any`

### LINKED ISSUE #10972: This typing for callbacks typed as any
I don't quite understand why below code is typed as `any`(I'm using nightly with `--noImplicitThis`)?
```ts
interface A {
    a: string;
}
declare function test(callback: (this: A) => void): void;
test(function() {
    this.a;// typed as any?
});
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR supersedes #11529 and #11600. Thanks to @HerringtonDarkholme for the original idea regarding type inference and contextual typing of partially annotated signatures.

We probably want to move the tests over from #11529. @sandersn Maybe you want to look at that?

Fixes #4241.
Fixes #9648.
Fixes #10850.
Fixes #10972.

### CODE REVIEW

**Comment by sandersn** [comment]
OK, I merged the tests from #11529.

**Comment by sandersn** [comment]
I also merged in the fourslash test from #11600, which is a regression test for #10972.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6101,9 +6097,24 @@ namespace ts {
...
+            // For arrow functions we now know we're not context sensitive.
+            if (node.kind === SyntaxKind.ArrowFunction) {
+                return false;
+            }
+            // If the first parameter is not an explicit 'this' parameter, then the function has
+            // an implicit 'this' parameter which is subject to contextual typing. Otherwise we
+            // know that all parameters (including 'this') have type annotations and nothing is
+            // subject to contextual typing.
+            const parameter = firstOrUndefined(node.parameters);
+            return !(parameter && parameter.name.kind === SyntaxKind.Identifier && (<Identifier>parameter.name).text === "this");
```
Comment (sandersn) [inline src/compiler/checker.ts]: This can be written as `!parameterIsThisKeyword(firstOrUndefined(node.parameters))`
