### PR TITLE
Fix emit/formatting issues in refactors

### LINKED ISSUE #37941: 'move to new file' refactoring should add add newline between imports and moved symbol
**TypeScript Version:**  3.9.0-dev.20200413

**Search Terms:**
- move to new file
- refactor / refactoring

**Code**
For a TS project:

`add.ts`
```ts
export function add(x: number, y: number) { return x + y; }
```

`index.ts`
```ts
import { add } from "./add";

function foo() {
    return add(1, 2);
}

export const a = foo();
```

1. Select `foo` and run `move to new file`

**Bug:**
The new file is missing a newline between the imports and the symbol:

```ts
import { add } from "./add";
export function foo() {
    return add(1, 2);
}
```

### LINKED ISSUE #37944: 'move to new file' can use wrong indent style on some lines
**TypeScript Version:**  3.9.0-dev.20200413

**Search Terms:**
- move to new file
- refactor / refactoring

**Code**
For a TS file indented using tabs:

```ts
export class Foo {
	constructor(
		public readonly a: number,

		/**
		 * Docs!
		 */
		public readonly b: number,
	) { }
}

export const a = new Foo(1, 2);
```

1. Select `Foo` and run `move to new file`

**Bug:**
The new file is a mix of spaces and tabs:

```ts
export class Foo {
	constructor(
		public readonly a: number,

        /**
         * Docs!
         */

		public readonly b: number) { }
}
```

Specifically, the doc comment is using spaces for indent.

### LINKED ISSUE #37948: 'move to new file' can add two new lines between methods
**TypeScript Version:**  3.9.0-dev.20200413

**Search Terms:**
- move to new file
- refactor / refactoring

**Code**
For a TS file:

```ts
class Foo {

	constructor() {
	}

	public runCommand(): void {
		let focusedEditor = 1;
		// Only if editor text focus (i.e. not if editor has widget focus).
		if (focusedEditor) {
			return;
		}
	}

	public run(): void { }
}
export const a = new Foo();
```

1. Select `Foo` and run `move to new file`

**Bug:**
The new file duplicates the new line between the methods in the class

```ts
export class Foo {
	constructor() {
	}


	public runCommand(): void {
		let focusedEditor = 1;
		// Only if editor text focus (i.e. not if editor has widget focus).
		if (focusedEditor) {
			return;
		}
	}


	public run(): void { }
}
```

### PR DESCRIPTION
**Pull request by andrewbranch**
The three commits fix three separate bugs, but each is pretty small. They’re all in this PR because at a glance I thought they’d all have a similar root cause, but they’re fairly separate.

Fixes #37948
Fixes #37944
Fixes #37941

### CODE REVIEW

File: tests/cases/fourslash/moveToNewFile.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ a; y;`,
         "/y.ts":
 `import { b } from './other';
 import { p } from './a';
+
```
Comment (sheetalkamat) [inline tests/cases/fourslash/moveToNewFile.ts:26]: This new line addition seems unnecessary

Comment (andrewbranch) [reply tests/cases/fourslash/moveToNewFile.ts:26]: #37941 claims it should be inserted. This file is brand new so I don’t see why it shouldn’t match our default auto-import styling, which adds a blank line between imports and following statements.
