### PR TITLE
Fix decorator design:types emit for type variables.

### LINKED ISSUE #25189: Decorator `design:type` emit fails to resolve TypeVariable objects
**TypeScript Version:**  3.0.0-dev.201xxxxx (current master)

**Search Terms:** decorator design:types variable undeclared

**Code**

```ts
// @experimentalDecorators: true
// @emitDecoratorMetadata: true

// Unused, but could collide with the named type argument below.
class TypeVariable {}

export class C<TypeVariable = string> {
  @Decorate
  member: TypeVariable;
}
```

**Expected behavior:**

Emit something like:

```js
// Unused, but could collide with the named type argument below.
var TypeVariable = /** @class */ (function () {
    function TypeVariable() {
    }
    return TypeVariable;
}());
var C = /** @class */ (function () {
    function C() {
    }
    __decorate([
        Decorate,
        __metadata("design:type", Object)
    ], C.prototype, "member");
    return C;
}());
exports.C = C;
```

**Actual behavior:**

```js
// Unused, but could collide with the named type argument below.
var TypeVariable = /** @class */ (function () {
    function TypeVariable() {
    }
    return TypeVariable;
}());
var C = /** @class */ (function () {
    function C() {
    }
    __decorate([
        Decorate,
        __metadata("design:type", TypeVariable)
    ], C.prototype, "member");
    return C;
}());
exports.C = C;
```

**Playground Link:**

Does not reproduce on the playground, possibly introduced in TS 2.9.2?

http://www.typescriptlang.org/play/#src=%2F%2F%20%40experimentalDecorators%3A%20true%0D%0A%2F%2F%20%40emitDecoratorMetadata%3A%20true%0D%0A%0D%0A%2F%2F%20Unused%2C%20but%20could%20collide%20with%20the%20named%20type%20argument%20below.%0D%0Aclass%20TypeVariable%20%7B%7D%0D%0A%0D%0Aexport%20class%20C%3CTypeVariable%20%3D%20string%3E%20%7B%0D%0A%20%20%40Decorate%0D%0A%20%20member!%3A%20TypeVariable%3B%0D%0A%7D%0D%0A

### PR DESCRIPTION
**Pull request by mprobst**
Fix decorator design:types emit for type variables.

Previously, TypeScript would resolve the reified types for the
`design:types` decorator emit in the regular `currentScope`. That scope
does not include class declaration bodies.

However when reifying types, class declarations do introduce a new scope
for any `TypeVariable`s declared on them. Because TS resolved the
EntityName for such types against the parent scope (e.g. the source
file), not the class scope, TypeScript would either fail to resolve the type (giving `TypeReferenceSerializationKind.Unknown`), or
incorrectly resolve to a different, accidentally matching symbol in the outer scope (giving `TypeWithConstructSignatureAndValue`).

This would result in an emit referencing an undeclared symbol, or
mis-referencing the wrong symbol.

    __metadata("design:type", typeof (_a = typeof TypeVariable !== "undefined" && TypeVariable) === "function" && _a || Object)
    __metadata("design:type", TypeVariable)

This change special cases `currentScope` for
`serializeTypeReferenceNode` to use a class scope, if present. This
changes the emit for a `TypeVariable` back to `Object`:

    __metadata("design:type", Object)

### CODE REVIEW

**Comment by mprobst** [comment]
Let me know if this is remotely reasonable, or feel free to just take the tests and fix based on them.

/CC @weswigham touched the code last, I think.

File: src/compiler/transformers/ts.ts [hunk 1]
```diff
@@ -1969,7 +1969,16 @@ namespace ts {
          * @param node The type reference node.
          */
         function serializeTypeReferenceNode(node: TypeReferenceNode): SerializedTypeNode {
-            const kind = resolver.getTypeReferenceSerializationKind(node.typeName, currentScope);
+            // node might be a reference to type variable, which can be scoped to a class declaration, in addition to the regular
+            // TypeScript scopes. Walk up the AST to find the next class and use that as the lookup scope.
+            let scope: Node = node;
+            while (scope.parent && scope !== currentScope) {
```
Comment (weswigham) [inline src/compiler/transformers/ts.ts]: We shouldn't be using `.parent` in a transform, as a `before` transform can unset parent pointers. The correct scope should be captured, like `currentScope`, as the transform descends through the tree.

Comment (weswigham) [reply src/compiler/transformers/ts.ts]: Given how `currentScope` is used, I think it is acceptable simply to add the class body to the list of things captured by the transform as a possible `currentScope`, I believe, since it is just used for resolving names (like for this serialization) and checking if we're at the top level of a file.

Comment (mprobst) [reply src/compiler/transformers/ts.ts]: That was my first idea, too. That does however break variable merging in emit, i.e. it adds in a duplicated var declaration:

```
class C {
    constructor() {
        this.foo = 10;
    }
}
C.bar = 20;
var C;  // <-- ADDED
(function (C) {
    C.x = 10;
})(C || (C = {}));
```

I tried debugging, and got lost somewhere in merge declaration markers. plz send help ;-)

**Comment by mhegazy** [comment]
@mprobst a few failing baselines that need updating.

**Comment by mprobst** [comment]
@mhegazy I think my change is incorrect, and the baselines should not be updated. Problem is I don't know how to fix correctly, I don't understand the merge declaration markers.

**Comment by mprobst** [comment]
Thanks @weswigham. As I said, feel free to take the tests and do whatever works :-)

**Comment by mhegazy** [comment]
thanks!
