### PR TITLE
Do not create multiple sourceFile to single outputFile with project redirect as the output file is included by default

### LINKED ISSUE #30591: Debug Failure. False expression
Trying to do a composite build modeled after microsoft/typescript but generating AMD modules fails:

```
Error: Debug Failure. False expression.
    at mergeSymbol (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:26088:26)
    at H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:26187:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:26185:20)
    at initializeTypeChecker (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:49309:21)
    at Object.createTypeChecker (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:25950:9)
    at Object.getTypeChecker (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:72860:79)
    at getReferencedFiles (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:74290:43)
    at Object.create (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:74329:41)
    at createBuilderProgramState (H:\code\ca0v\speech-lab\node_modules\typescript\lib\tsc.js:74572:37)
```

You can find a link to the project on https://stackoverflow.com/questions/55348498/problems-building-with-typescript-transpiler-tsc-using-the-build-flag, but basically if you set the module to "amd" it fails to transpiler (works fine when outFile -> outDir).

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #30591

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -2266,8 +2266,13 @@ namespace ts {
 
             let redirectedPath: Path | undefined;
             if (refFile) {
```
Comment (andrewbranch) [inline src/compiler/program.ts]: What is `refFile` in this function?

File: src/compiler/program.ts [hunk 2]
```diff
@@ -2266,8 +2266,13 @@ namespace ts {
 
             let redirectedPath: Path | undefined;
             if (refFile) {
-                const redirect = getProjectReferenceRedirect(fileName);
-                if (redirect) {
+                const redirectProject = getProjectReferenceRedirectProject(fileName);
+                if (redirectProject) {
+                    if (redirectProject.commandLine.options.outFile || redirectProject.commandLine.options.out) {
+                        // Shouldnt create many to 1 mapping file in --out scenario
+                        return undefined;
```
Comment (andrewbranch) [inline src/compiler/program.ts]: Trying to see if I understand:

Normally, if you call `findSourceFile` for say `subproject/a.ts` which is part of a referenced project, you'd return (after updating caches) the source file for `subproject/a.d.ts`. But if that referenced project has an `outFile` option, there won't be a `subproject/a.d.ts`, there will be a single concatenated definition file, let's say `subproject/built.d.ts`.

So you return early here because `subproject/built.d.ts` has already been processed, and doing it again causes problems. That makes sense to me, but why not return the SourceFile for `subproject/built.d.ts`?

Comment (sheetalkamat) [reply src/compiler/program.ts]: You do not want to return `subproject/built.d.ts` because normally file is 1:1 mapping and breaking that could lead to more severe breaks down the line somewhere. Technically there is no `single` file with `subproject/a.ts` but its mix of multiple files in subproject

File: src/compiler/program.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/program.ts]: refFile is normally passed in if its trying to resolve imports/ or reference directives etc. thats the file in which import exists and hence the file is being added. The root files passed to program, when processed have refile as undefined.
