### PR TITLE
Implicit index signatures for enum object types

### LINKED ISSUE #30977: False positive error report for enum and class instance type missing index signature, thus not assignable to object type with `unknown` values.
**TypeScript Version:**  `3.5.0-dev.20190410`, (`v3.4.3` doesn't have this bug)

**Search Terms:**
enum, class, assignable, index signature

**Code**

```ts
enum Enum { A }

const e0: { [key: string]: any     } = Enum; // ok
const e1: { [key: string]: unknown } = Enum; // produces an unexpected error report

//

const obj = { A: 0 };

const o0: { [key: string]: any     } = obj; // ok
const o1: { [key: string]: unknown } = obj; // ok

// 

class Class {}

export const cl0: { [key: string]: any     } = new Class; // ok
export const cl1: { [key: string]: unknown } = new Class; // produces an unexpected error report
```

**Expected behavior:**
This code should compile with no errors.

**Actual behavior:**
Error near the definition of `e1` and `cl1`: 

```
Type 'typeof Enum/Class' is not assignable to type '{ [key: string]: unknown; }'.
Index signature is missing in type 'typeof Enum/Class'.
```

**Playground Link:**
This works well in the playground as it uses the stable version of `tsc`, but this bug appears in dev build. [Klick me](https://www.typescriptlang.org/play/index.html#src=enum%20Enum%20%7B%20A%20%7D%0D%0A%0D%0Aconst%20e0%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%20%20%20%20%7D%20%3D%20Enum%3B%20%20%20%20%20%20%2F%2F%20ok%0D%0Aconst%20e1%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20unknown%20%7D%20%3D%20Enum%3B%20%2F%2F%20produces%20an%20unexpected%20error%20report%0D%0A%0D%0A%2F%2F%0D%0A%0D%0Aconst%20obj%20%3D%20%7B%20A%3A%200%20%7D%3B%0D%0A%0D%0Aconst%20o0%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%20%20%20%20%7D%20%3D%20obj%3B%20%2F%2F%20ok%0D%0Aconst%20o1%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20unknown%20%7D%20%3D%20obj%3B%20%2F%2F%20ok%0D%0A%0D%0A%2F%2F%20%0D%0A%0D%0Aclass%20User%20%7B%7D%0D%0A%0D%0Aexport%20const%20cl0%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%20%20%20%20%7D%20%3D%20new%20User%3B%20%2F%2F%20ok%0D%0Aexport%20const%20cl1%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20unknown%20%7D%20%3D%20new%20User%3B%20%2F%2F%20produces%20an%20unexpected%20error%20report).

**Related Issues:** 
None.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Types representing object literals or modules have inferable index signatures because their exact set of properties is known. This PR implements the same behavior for types representing enum objects since these also have exact and close ended sets of properties.

* The enum object type of an enum with at least one numerically valued member has an implicit string index signature of type `string | X`, where `X` is a union of the types of all numerically valued members, and an implicit numeric index signature of type `string`.

* The enum object type of an enum with only string valued members has an implicit string index signature of type `string` and no implicit numeric index signature.

In the above, `X` reflects the reverse mapping from strings to numeric enum values included in the generated code that initializes the enum object.

Fixes #30977 (to the extent we can fix it).

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
@typescript-bot test this

File: tests/cases/compiler/implicitIndexSignatures.ts [hunk 1]
```diff
@@ -43,3 +43,15 @@ function f4() {
...
+
+function f5() {
+    enum E1 { A, B }
+    enum E2 { A = "A", B = "B" }
+    enum E3 { A = 0, B = "B" }
+    const v1 = getStringIndexValue(E1);
+    const v2 = getStringIndexValue(E2);
+    const v3 = getStringIndexValue(E3);
+    const v4 = getNumberIndexValue(E1);
+    const v5 = getNumberIndexValue(E2);
```
Comment (weswigham) [inline tests/cases/compiler/implicitIndexSignatures.ts]: Why is this `unknown` and not an error? (Is it just because inference fails and "a thing with an inferrable index" is assignable to a `{[x: number]: unknown}`?) I'd think that yeah, `E2` has an inferrable index type, sure, but we know that it has no numbers in it at all. But, from the stance that the number index signature (were it present in the type) would need to be assignable to the string index, this'd need to be `E2`.

Comment (ahejlsberg) [reply tests/cases/compiler/implicitIndexSignatures.ts]: Because we infer nothing for `T` in the call to `getNumberIndexValue`. Keep in mind we're not doing an assignment here, we're just doing inference.

Comment (weswigham) [reply tests/cases/compiler/implicitIndexSignatures.ts]: Well, we are doing an assignment - we're saying that a `{[x: string]: E2}` is assignable to a `{[x: number]: unknown}`. I guess the output type here just irks me a tad - it could only possibly be an `E2` or `keyof typeof E2`, rather than an `unknown`.

Like, if I write `enum StrNum { Zero = "0", One = "1" }`, indexing by `0` or `1` is gunna get me `Zero` or `One`, likewise if I write `enum NumStr { "0" = "Zero", "1" = "One" }`, indexing by `Zero` or `One` is gunna get me `"0"` or `"1"`.

Comment (ahejlsberg) [reply tests/cases/compiler/implicitIndexSignatures.ts]: No, indexing your `StrNum` by `0` or `1` is going to get you `undefined` (there's no reverse mapping for string valued members), and `NumStr` is an error because members can't have numeric names.

Comment (ahejlsberg) [reply tests/cases/compiler/implicitIndexSignatures.ts]: Anyway, the `unknown` type is consistent with what we infer for object literal types that have no numerically named members. In some sense it would be more consistent to return `undefined` since that's what you're going to get, but that really is an orthogonal issue.

Comment (weswigham) [reply tests/cases/compiler/implicitIndexSignatures.ts]: > there's no reverse mapping for string valued member

I always forget about that.

> Anyway, the unknown type is consistent with what we infer for object literal types that have no numerically named members

Oh, ick. Ok.
