### PR TITLE
Better JS container binding

### LINKED ISSUE #24110: Assert in getTypeOfVariableOrParameterOrProperty when merging variables and functions
**TypeScript Version:** master

**Search Terms:** getTypeOfVariableOrParameterOrProperty 

**Code**

file2.d.ts
```ts
declare class C {
    static x: C;
    bar(): C;
}
declare namespace C {
    function bar(): void;
}

```

file1.js
```ts
C.prototype = {};
C.prototype.bar = C;
C.x = C;
C.bar = C;
```

**Expected behavior:**

**Actual behavior:**
```
Error: Debug Failure. Unhandled declaration kind! FunctionDeclaration
    at getTypeOfVariableOrParameterOrProperty (C:\github\TypeScript\built\local\tsc.js:29478:30)
    at getTypeOfSymbol (C:\github\TypeScript\built\local\tsc.js:29651:24)
    at propertiesRelatedTo (C:\github\TypeScript\built\local\tsc.js:35023:55)
    at structuredTypeRelatedTo (C:\github\TypeScript\built\local\tsc.js:34912:38)
    at recursiveTypeRelatedTo (C:\github\TypeScript\built\local\tsc.js:34704:64)
    at isRelatedTo (C:\github\TypeScript\built\local\tsc.js:34393:38)
    at checkTypeRelatedTo (C:\github\TypeScript\built\local\tsc.js:34213:26)
    at checkTypeAssignableTo (C:\github\TypeScript\built\local\tsc.js:33898:20)
    at checkAssignmentOperator (C:\github\TypeScript\built\local\tsc.js:43320:25)
    at checkBinaryLikeExpression (C:\github\TypeScript\built\local\tsc.js:43273:21)
```

**Playground Link:** N/A

**Related Issues:** Found when looking for a stack overflow related to #24015

### LINKED ISSUE #24111: Assert failure in forEachIdentifierInEntityName with prototype assignment + prototype property assignment
**TypeScript Version:** master

**Search Terms:** forEachIdentifierInEntityName

**Code**

file1.js
```ts
C.prototype = {};
C.prototype.bar = { };
C.prototype.bar.foo = { };
```

file2.d.ts
```ts
declare class C {
    static x: C;
    bar(): { m: C };
}
```

**Expected behavior:**

**Actual behavior:**
```
C:\github\TypeScript\built\local\tsc.js:4213
            throw e;
            ^

Error: Debug Failure. False expression.
    at forEachIdentifierInEntityName (C:\github\TypeScript\built\local\tsc.js:23034:26)
    at bindPropertyAssignment (C:\github\TypeScript\built\local\tsc.js:22993:17)
    at bindStaticPropertyAssignment (C:\github\TypeScript\built\local\tsc.js:22976:13)
    at bindSpecialPropertyAssignment (C:\github\TypeScript\built\local\tsc.js:22967:17)
    at bindWorker (C:\github\TypeScript\built\local\tsc.js:22645:29)
    at bind (C:\github\TypeScript\built\local\tsc.js:22533:13)
    at visitNode (C:\github\TypeScript\built\local\tsc.js:13972:24)
    at Object.forEachChild (C:\github\TypeScript\built\local\tsc.js:14204:24)
    at bindEachChild (C:\github\TypeScript\built\local\tsc.js:21346:16)
    at bindChildrenWorker (C:\github\TypeScript\built\local\tsc.js:21438:21)
```

**Playground Link:** N/A

**Related Issues:** Another offshoot of #24015

### PR DESCRIPTION
**Pull request by sandersn**
This PR improves the binding of JS containers. It no longer binds function expressions, class expressions, object literals or IIFEs as declarations. Instead, the actual declaration is the one that merges with subsequent special assignment.

For example,

```js
var C = function() {
  this.x = 1
}
C.prototype.y = 3
C.z = 2
```

Previously put x and y on the members of the function expression and z on its exports. Now, it puts x on the members of the function expression (since it is declared there), y on the members of C and z on the exports of C. When the checker requests the type of the function expression, `getTypeOfFuncClassEnumModule` checks whether the declaration (C in this case) has any special exports or members and merges them if so. The resulting type is the type of the function expression as well as C.

This has three advantages:
1. Better type printing in many cases.
1. Simpler code in bindPropertyAssignment.
2. Simpler code in mergeSymbol.

Both these pieces of code were previously bug farms.

Also, since the checker now produces the combined types instead of the binder, IIFE type checking is better; the returned type of the IIFE is intersected with an anonymous type containing exports produced by special JS assignments.

Fixes #24110 
Fixes #24111

### CODE REVIEW

**Comment by sandersn** [comment]
Running [Ryan's fuzzer](https://github.com/RyanCavanaugh/ts-merge-fuzz) in its original editor-mode configuration doesn't show any oomemory or crashes for over 1,000,000 iterations. I'll run it in get-diagnostics-mode configuration once I change the checker to handle more kinds of Javascript merges in my next PR. (Right now our pre-existing lack of handling crazy merges causes us to hit asserts in various branches of `getTypeOfSymbol`.)

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5047,8 +5014,25 @@ namespace ts {
         }
 
         function getTypeOfFuncClassEnumModule(symbol: Symbol): Type {
-            const links = getSymbolLinks(symbol);
+            let links = getSymbolLinks(symbol);
             if (!links.type) {
+                const jsDeclaration = getDeclarationOfJSInitializer(symbol.valueDeclaration);
+                if (jsDeclaration) {
+                    const jsSymbol = getMergedSymbol(jsDeclaration.symbol);
+                    if (jsSymbol && (jsSymbol.exports && jsSymbol.exports.size || jsSymbol.members && jsSymbol.members.size)) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: If `jsSymbol === symbol` (somehow) does this work need to be done?

Comment (sandersn) [reply src/compiler/checker.ts]: No, and it would be really bad because you would be merging symbols with themselves. But it would hit the new assert in mergeSymbol, so it doesn’t happen in our tests at least.

But you make a valid point; getDeclarationOfJSInitializer should (1) check that its node is in a js file (2) check that the provided value declaration is the initializer of the js declaration that it returns.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5047,8 +5014,25 @@ namespace ts {
         }
 
         function getTypeOfFuncClassEnumModule(symbol: Symbol): Type {
-            const links = getSymbolLinks(symbol);
+            let links = getSymbolLinks(symbol);
             if (!links.type) {
+                const jsDeclaration = getDeclarationOfJSInitializer(symbol.valueDeclaration);
+                if (jsDeclaration) {
+                    const jsSymbol = getMergedSymbol(jsDeclaration.symbol);
```
Comment (sandersn) [inline src/compiler/checker.ts]: This should just be a call to getsymbolofnode I think.

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Fixed. (As is the call to getSymbolOfNode.)

**Comment by sandersn** [comment]
I ran Ryan's fuzzer with getSemanticDiagnostics after every iteration after fixing the asserts it found. It didn't show any crashes, oomemory or asserts after 2,500 iterations (it runs a *lot* slower since in this mode, it checks each generated program.) The fix is small, so I threw it into this PR as well.

**Comment by sandersn** [comment]
ping @weswigham @mhegazy

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -888,11 +888,17 @@ namespace ts {
...
+         */
+        function mergeSymbol(target: Symbol, source: Symbol): Symbol {
             if (!(target.flags & getExcludedSymbolFlags(source.flags)) ||
                 (source.flags | target.flags) & SymbolFlags.JSContainer) {
-                const targetValueDeclaration = target.valueDeclaration;
-                Debug.assert(!!(target.flags & SymbolFlags.Transient));
+                if (!(target.flags & SymbolFlags.Transient)) {
+                    target = cloneSymbol(target);
+                }
+                Debug.assert(source !== target);
```
Comment (weswigham) [inline src/compiler/checker.ts]: Should this be above the `Transitent` check, or is it OK for a nontransient target to merge into "itself" (its transient copy)?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -5047,8 +5016,25 @@ namespace ts {
         }
 
         function getTypeOfFuncClassEnumModule(symbol: Symbol): Type {
-            const links = getSymbolLinks(symbol);
+            let links = getSymbolLinks(symbol);
             if (!links.type) {
+                const jsDeclaration = getDeclarationOfJSInitializer(symbol.valueDeclaration);
+                if (jsDeclaration) {
+                    const jsSymbol = getSymbolOfNode(jsDeclaration);
+                    if (jsSymbol && (jsSymbol.exports && jsSymbol.exports.size || jsSymbol.members && jsSymbol.members.size)) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Style: Maybe we should add a `size` helper function that handles `undefined` like how we have `length` for arrays?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -19121,7 +19106,17 @@ namespace ts {
             if (returnType.flags & TypeFlags.ESSymbolLike && isSymbolOrSymbolForCall(node)) {
                 return getESSymbolLikeTypeForNode(walkUpParenthesizedExpressions(node.parent));
             }
-            return returnType;
+            let jsAssignmentType: Type | undefined;
+            if (isInJavaScriptFile(node)) {
+                const decl = getDeclarationOfJSInitializer(node);
+                if (decl) {
+                    const jsSymbol = getMergedSymbol(decl.symbol);
```
Comment (weswigham) [inline src/compiler/checker.ts]: Use `getSymbolOfNode(decl)` - unless you're intentionally avoiding the late bound node check for some reason.

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Strictly speaking, it doesn't matter, because source will never equal target just after running cloneSymbol. I think it is clearer beforehand though.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Let me see how many times we check for null before accessing size. The level of inconvenience seems worth about 5-6 checks before making a helper.

Later: it's over 10 now. I'll add the helper.

File: src/compiler/checker.ts (hunk 5 above)
Comment (sandersn) [reply src/compiler/checker.ts]: No, I just forgot again. Thanks.
