### PR TITLE
Eliminate well known symbols as a concept in the checker and rely on unique symbols

### LINKED ISSUE #21603: Use unique symbol for well-known symbols
**Expected behavior:**

```ts
interface SymbolConstructor {
    readonly iterator: unique symbol;
}
```

**Actual behavior:**

```ts
interface SymbolConstructor {
    readonly iterator: symbol;
}
```

### LINKED ISSUE #24622: keyof does not include well known symbols
**TypeScript Version:**  2.9.1

**Search Terms:** 
keyof well known symbol

**Code**

```ts
const s = Symbol("s");

interface I {
    n: number;
    [s]: string;
    [Symbol.iterator](): IterableIterator<[string, string]>;
}

type K = keyof I;
type T = I[K];
```

**Expected behavior:**
```ts
type K = keyof I; // type K = typeof s | "n" | typeof Symbol.iterator
type T = I[K]; // type T = string | number | () => IterableIterator<[string, string]>
```

**Actual behavior:**
```ts
type K = keyof I; // type K = typeof s | "n"
type T = I[K]; // type T = string | number
```

### LINKED ISSUE #27525: Make Symbol.* (e.g. Symbol.iterator) unique symbols
## Suggestion

Use this:

```typescript
declare function Symbol (x?: string | number): symbol

declare namespace Symbol {
  const prototype: symbol
  const iterator: unique symbol
}
```

Or this:

```typescript
interface SymbolConstructor {
  (x?: string | number): symbol
  readonly prototype: symbol
  readonly iterator: unique symbol
}

declare var Symbol: SymbolConstructor
```

Instead of this:

```typescript
interface SymbolConstructor {
  (x?: string | number): symbol
  readonly prototype: symbol
  readonly iterator: symbol
}

declare var Symbol: SymbolConstructor
```

## Use Cases

Right now, I can do this for custom `unique symbol`:

```typescript
const foo = Symbol() // unique symbol
const bar: typeof foo = foo

const baz: {
	[foo]: number
} = {
	[bar]: 123
}
```

But not for `Symbol.*`

```typescript
// Expecting 'typeof Symbol.iterator' but received 'symbol'
const iterator: typeof Symbol.iterator = Symbol.iterator

// This is not working
const iterable: Iterable<number> = {
  * [iterator] () {
    yield * [0, 1, 2, 3]
  }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

---

[Playground Link](https://www.typescriptlang.org/play/#src=declare%20function%20FakeSymbol%20()%3A%20symbol%0D%0A%0D%0Adeclare%20namespace%20FakeSymbol%20%7B%0D%0A%20%20const%20prototype%3A%20symbol%0D%0A%20%20const%20iterator%3A%20unique%20symbol%0D%0A%7D%0D%0A%0D%0Aconst%20iterator%3A%20typeof%20FakeSymbol.iterator%20%3D%20FakeSymbol.iterator%0D%0A%0D%0Aconst%20foo%3A%20%7B%0D%0A%20%20%5BFakeSymbol.iterator%5D%3A%20number%0D%0A%7D%20%3D%20%7B%0D%0A%20%20%5Biterator%5D%3A%20123%0D%0A%7D%0D%0A) ([This](https://www.typescriptlang.org/play/#src=interface%20FakeSymbolConstructor%20%7B%0D%0A%20%20(x%3F%3A%20number%20%7C%20string)%3A%20symbol%0D%0A%20%20readonly%20prototype%3A%20symbol%0D%0A%20%20readonly%20iterator%3A%20unique%20symbol%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20FakeSymbol%3A%20FakeSymbolConstructor%0D%0A%0D%0Aconst%20iterator%3A%20typeof%20FakeSymbol.iterator%20%3D%20FakeSymbol.iterator%0D%0A%0D%0Aconst%20foo%3A%20%7B%0D%0A%20%20%5BFakeSymbol.iterator%5D%3A%20number%0D%0A%7D%20%3D%20%7B%0D%0A%20%20%5Biterator%5D%3A%20123%0D%0A%7D%0D%0A) also works)

[Related Issue](https://github.com/Microsoft/TypeScript/issues/27524)

### LINKED ISSUE #31253: Readonly<Float32Array> not assignable to Float32Array
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
function update(b: Readonly<Float32Array>) {
    const c = copy(b);
    add(c, c);
}

function add(a: Float32Array, b: Float32Array, c: Float32Array = a) {
    c[0] = a[0] + b[0];
}

function copy(a: Float32Array) {
    return new Float32Array(a);
}
```

**Expected behavior:**

No error.

_Though I would expect not to be able to pass a Readonly value to a function which can mutate it but that's [another issue](https://github.com/Microsoft/TypeScript/issues/13347)_.

**Actual behavior:**

Error on line 2:

```
Argument of type 'Readonly<Float32Array>' is not assignable to parameter of type 'Float32Array'.
  Type 'Readonly<Float32Array>' is missing the following properties from type 'Float32Array': [Symbol.iterator], [Symbol.toStringTag]
```

**Playground Link:** 

[See in playground](https://www.typescriptlang.org/play/index.html#src=function%20update(b%3A%20Readonly%3CFloat32Array%3E)%20%7B%0D%0A%20%20%20%20const%20c%20%3D%20copy(b)%3B%0D%0A%20%20%20%20add(c%2C%20c)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20add(a%3A%20Float32Array%2C%20b%3A%20Float32Array%2C%20c%3A%20Float32Array%20%3D%20a)%20%7B%0D%0A%20%20%20%20c%5B0%5D%20%3D%20a%5B0%5D%20%2B%20b%5B0%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20copy(a%3A%20Float32Array)%20%7B%0D%0A%20%20%20%20return%20new%20Float32Array(a)%3B%0D%0A%7D)

Note I can workaround the issue by using mappable types on the function arguments but this is pretty verbose and not something I will want to litter a codebase with - Also not going to work with third-party libraries. See that [here](https://www.typescriptlang.org/play/index.html#src=function%20update(b%3A%20Readonly%3CFloat32Array%3E)%20%7B%0D%0A%20%20%20%20const%20c%20%3D%20copy(b)%3B%0D%0A%20%20%20%20add(c%2C%20c)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20add(a%3A%20Mutable%3CFloat32Array%3E%2C%20b%3A%20Mutable%3CFloat32Array%3E%2C%20c%3A%20Mutable%3CFloat32Array%3E%20%3D%20a)%20%7B%0D%0A%20%20%20%20c%5B0%5D%20%3D%20a%5B0%5D%20%2B%20b%5B0%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20copy(a%3A%20Readonly%3CFloat32Array%3E)%20%7B%0D%0A%20%20%20%20return%20new%20Float32Array(a)%3B%0D%0A%7D%0D%0A%0D%0Atype%20Mutable%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20-readonly%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%3B%0D%0A%7D%3B). Edit: Actually seen another way to do it which is much less verbose [here](https://www.typescriptlang.org/play/index.html#src=function%20update(b%3A%20Readonly%3CFloat32Array%3E)%20%7B%0D%0A%20%20%20%20const%20c%20%3D%20copy(b%20as%20Float32Array)%3B%0D%0A%20%20%20%20add(c%2C%20c)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20add(a%3A%20Float32Array%2C%20b%3A%20Float32Array%2C%20c%3A%20Float32Array%20%3D%20a)%20%7B%0D%0A%20%20%20%20c%5B0%5D%20%3D%20a%5B0%5D%20%2B%20b%5B0%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20copy(a%3A%20Float32Array)%20%7B%0D%0A%20%20%20%20return%20new%20Float32Array(a)%3B%0D%0A%7D). _This however loops again back to [this issue](https://github.com/Microsoft/TypeScript/issues/13347) since it really should be raising an error (if in strict mode)._

**Related Issues:** 

N/A

### LINKED ISSUE #37182: Readonly<T> miss all internal symbol keys
**TypeScript Version:**  3.8.3

**Search Terms:** readonly internal symbol

**Code**

```ts
const sym = Symbol();
const x :{
	readonly str :any
	readonly [sym] :any
	readonly [Symbol.iterator] :any
	readonly [Symbol.toStringTag] :any
} = {} as Readonly<{
	str :any
	[sym] :any
	[Symbol.iterator] :any
	[Symbol.toStringTag] :any
}>;
```

**Expected behavior:**

no error

**Actual behavior:**

`TS2739` (missing properties `Symbol.iterator` and `Symbol.toStringTag`)

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
#24738, but for 2021 and not 2018.

The parts from the original PR description that still hold:
>Interestingly, there is some fallout here in some odd places:
>* First of all, some small changes needed to occur to replicate old behavior. Right now, a computed name of type `any` produces a `number` index signature. With this change, we make a `string` index signature instead (it's more broad and closer to correct).
>* Lastly, some emit changes - specifically, where previously we'd elide `Symbol.iterator` when it appeared as a property name (and assume that the expression had no sideffects), now we retain and emit it (and potentially cache it), as we generally do not assume property access expressions are safe to elide or copy.

>Fixes #24622

>An important implementation note: As we discussed in person, Inside the checker, if we see members of the global `SymbolConstructor` of type `symbol`, we also _assume_ you meant to say `unique symbol`. In this way, we retain compatibility with older libs or definition files (even as they update), which is how this can build (at all), given node is shimming `Symbol.iterator` as a `symbol`.

Fixes #24622
Fixes #27525
Fixes #31253
Fixes #21603
Fixes #37182
Fixes half of #36468 (indirect calls to `Symbol()` still do not produce fresh `unique symbol`s like direct calls do - but that should be a separate change, IMO)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3677,11 +3678,25 @@ namespace ts {
...
                 const reexportContainers = enclosingDeclaration && getAlternativeContainingModules(symbol, enclosingDeclaration);
                 const objectLiteralContainer = getVariableDeclarationOfObjectLiteral(container, meaning);
-                if (enclosingDeclaration && getAccessibleSymbolChain(container, enclosingDeclaration, SymbolFlags.Namespace, /*externalOnly*/ false)) {
+                if (enclosingDeclaration && container.flags & getQualifiedLeftMeaning(meaning) && getAccessibleSymbolChain(container, enclosingDeclaration, SymbolFlags.Namespace, /*externalOnly*/ false)) {
                     return append(concatenate(concatenate([container], additionalContainers), reexportContainers), objectLiteralContainer); // This order expresses a preference for the real container if it is in scope
                 }
+                // we potentially a symbol which is a member of the instance side of something - look for a variable in scope with the container's type
+                // which may be acting like a namespace
+                const firstVariableMatch = !(container.flags & getQualifiedLeftMeaning(meaning))
```
Comment (weswigham) [inline src/compiler/checker.ts:3686]: This bit and the following modify our symbol container lookup to prefer, eg, `Symbol.iterator` to `SymbolConstructor.iterator` when doing printback for where the specified `SymbolFlags` say the first is allowable. Now, this isn't _specific_ to symbols or `Symbol` in any way - other dynamic names from namespace-ish things should work similarly, too! So `ArrayConstructor`, `Int8ArrayConsturctor`.... anything with the split namespace pattern the DOM uses a lot.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5104,8 +5119,9 @@ namespace ts {
                         }
                     }
                 }
-                context.enclosingDeclaration = saveEnclosingDeclaration;
+                context.enclosingDeclaration = propertySymbol.valueDeclaration || propertySymbol.declarations?.[0] || saveEnclosingDeclaration;
```
Comment (weswigham) [inline src/compiler/checker.ts:5122]: If we don't set a specific `enclosingDeclaration` when serializing the name, in cases where we don't pass a contextual one (eg, error reporting), we'd print a name like `[iterator]` instead of `[Symbol.iterator]` (because symbol chain lookup bails entirely if there's no enclosing declaration provided). I think we much prefer the later, so now we actually specify an enclosing declaration for the name whenever we can.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -8704,8 +8717,18 @@ namespace ts {
...
 
+        function isGlobalSymbolConstructor(node: Node) {
+            const symbol = getSymbolOfNode(node);
+            const globalSymbol = getGlobalESSymbolConstructorTypeSymbol(/*reportErrors*/ false);
+            return globalSymbol && symbol && symbol === globalSymbol;
+        }
+
         function widenTypeForVariableLikeDeclaration(type: Type | undefined, declaration: any, reportErrors?: boolean) {
             if (type) {
+                // TODO: Remove the following SymbolConstructor special case when back compat with pre-3.0 libs isn't required
```
Comment (weswigham) [inline src/compiler/checker.ts:8728]: Realistically maybe this isn't a "TODO" and more of a wishful thought - the compat behavior is probably a permanent thing, given our ecosystem.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -13919,13 +13946,13 @@ namespace ts {
...
                 let type = getSymbolLinks(getLateBoundSymbol(prop)).nameType;
-                if (!type && !isKnownSymbol(prop)) {
+                if (!type) {
                     if (prop.escapedName === InternalSymbolName.Default) {
                         type = getLiteralType("default");
                     }
                     else {
                         const name = prop.valueDeclaration && getNameOfDeclaration(prop.valueDeclaration) as PropertyName;
-                        type = name && getLiteralTypeFromPropertyName(name) || getLiteralType(symbolName(prop));
+                        type = name && getLiteralTypeFromPropertyName(name) || (!isKnownSymbol(prop) ? getLiteralType(symbolName(prop)) : undefined);
```
Comment (weswigham) [inline src/compiler/checker.ts:13955]: Perhaps confusingly, `isKnownSymbol` has almost nothing to do with well-known symbols, and actually just checks if the checker Symbol has a symbol-y name (eg, it's `escapedName` starts with `__@`). It's _mostly_ gone, since we _were_, intent-wise, actually using it to proxy for well-known-symboly-ness in places; however a handful of select locations remain where we actually want to check for normal symbol-ness.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -25321,7 +25342,10 @@ namespace ts {
                 }
 
                 if (computedNameType && !(computedNameType.flags & TypeFlags.StringOrNumberLiteralOrUnique)) {
-                    if (isTypeAssignableTo(computedNameType, stringNumberSymbolType)) {
+                    if (isTypeAny(computedNameType)) {
```
Comment (weswigham) [inline src/compiler/checker.ts:25345]: Technically, I can push this change through without this change, if we'd prefer. However, that means when you write, eg
```ts
const obj = {
  [Symbol.whatever]: 0
};
```
`obj` would get a `number` index signature (since `Symbol.whatever` is going to be `any` from the error of it not existing), whereas with this it gets a `string` index signature (which, IMO, makes much more sense for an `any` computed name). It mostly only matters, in the context of unique symbols, for follow-on errors to nonexistant symbols which were previously "well known" and thus entirely unchecked.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -35198,6 +35180,12 @@ namespace ts {
             }
         }
 
+        function getPropertyNameForKnownSymbolName(symbolName: string): __String {
+            const ctorType = getGlobalESSymbolConstructorSymbol(/*reportErrors*/ false);
+            const uniqueType = ctorType && getTypeOfPropertyOfType(getTypeOfSymbol(ctorType), escapeLeadingUnderscores(symbolName));
+            return uniqueType && isTypeUsableAsPropertyName(uniqueType) ? getPropertyNameFromType(uniqueType) : `__@${symbolName}` as __String;
```
Comment (weswigham) [inline src/compiler/checker.ts:35186]: The `__@${symbolName} as __String;` case is reachable in scenarios where our internals request a name for a symbol which doesn't exist in the lib. Eg, requesting `Symbol.asyncIterator` in a `lib` target where it doesn't exist. No construct can _make_ a property symbol name in that format anymore (unique symbol names have the form `__@desc@###`), so it's guaranteed to result in an `undefined` result from `getPropertyOfType`, resulting in a `noIterationTypes` result (as you may expect when the core iteration protocol types are missing!).

File: src/compiler/transformers/utilities.ts [hunk 7]
```diff
@@ -269,8 +269,7 @@ namespace ts {
      * any such locations
      */
     export function isSimpleInlineableExpression(expression: Expression) {
-        return !isIdentifier(expression) && isSimpleCopiableExpression(expression) ||
-            isWellKnownSymbolSyntactically(expression);
+        return !isIdentifier(expression) && isSimpleCopiableExpression(expression);
```
Comment (weswigham) [inline src/compiler/transformers/utilities.ts:272]: This change is pretty much single-handedly responsible for the .js emit changes in this PR. `Symbol.iterator` and it's ilk aren't "simple copyable expressions" since, technically, accessing it could produce side effects (like any other property access). Now... at some point, we added `Identifier`s to `isSimpleCopiableExpression`'s domain (which isn't technically safe, since the identifier may get reassigned between the copied references), so maybe property accesses which only consist of `Identifier`s wouldn't be terribly unreasonable, either. 🤷

File: src/lib/es2015.iterable.d.ts [hunk 8]
```diff
@@ -5,7 +5,7 @@ interface SymbolConstructor {
      * A method that returns the default iterator for an object. Called by the semantics of the
      * for-of statement.
      */
-    readonly iterator: symbol;
+    readonly iterator: unique symbol;
```
Comment (weswigham) [inline src/lib/es2015.iterable.d.ts:8]: Fun fact! I didn't actually need to make any of these lib changes to make the PR work, what with the compat code in place! But I've updated them anyway, so they serve as examples of what `unique symbol`s really are to anyone reading the definitions.

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot user test this
@typescript-bot test this

**Comment by rbuckton** [comment]
I'm not sure if it will affect this PR or not, but I'm investigating changes to `unique symbol` to possibly add the same "freshness" concept we use for literal types in an effort to fix https://github.com/microsoft/TypeScript/issues/32408 as well as to make our widening for `unique symbol` more consistent with other places where we widen.

**Comment by weswigham** [comment]
Nah, I don't think it'd affect this. Freshness is for types from "literals" (so, `Symbol()`) - `Symbol.iterator` and friends would all go on being the unfresh type.

**Comment by weswigham** [comment]
Perf and user runs look fine. DT has two packages that look like some improvements, but I'll take a deeper look later. RWC has one project (a sample) with new errors because we reference es6+ symbols in the sample, but don't include the es6 lib (and prioe to this we never checked that). So all in all tests look good.

File: src/lib/es2015.iterable.d.ts (hunk 8 above)
Comment (DanielRosenwasser) [reply src/lib/es2015.iterable.d.ts:8]: Hm - and that won't conflict with a separate "polyfill" definition right? In other words, if someone separately declares it as

```ts
interface SymbolConstructor {
    readonly iterator: symbol;
}
```

and these merge, they won't end up conflicting, right?

Comment (weswigham) [reply src/lib/es2015.iterable.d.ts:8]: Nope - and there's already a test to that effect on the diff.

File: src/compiler/checker.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:5122]: What's an example where `propertySymbol.declarations?.[0]` is useful?

File: src/compiler/checker.ts (hunk 5 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:25345]: From the comment here, it sounds like this mostly to cater to the "degenerate" case of `Symbol.thingThatDoesNotExist` which can happen in a loosely configured JavaScript project - is that the use-case you have in mind? And 

That does loosen the behavior of this by quite a bit. I think I would be willing to go the *opposite* way and take a break on this behavior.

File: src/compiler/checker.ts (hunk 6 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:35186]: Can you give a little more context on the significance? Are you saying this is handled well in the existing code, that other code needs to be careful, that there's a fundamental architectural issue, or that this now has a user-facing impact? (or all?)

File: src/compiler/transformers/utilities.ts (hunk 7 above)
Comment (DanielRosenwasser) [reply src/compiler/transformers/utilities.ts:272]: @rbuckton is probably the best judge of that.

File: tests/baselines/reference/ES5SymbolProperty1.types [hunk 9]
```diff
@@ -19,8 +19,8 @@ var obj = {
 }
 
 obj[Symbol.foo];
->obj[Symbol.foo] : any
->obj : { [Symbol.foo]: number; }
+>obj[Symbol.foo] : number
+>obj : { [x: string]: number; }
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/ES5SymbolProperty1.types:23]: Sad! Maybe we should continue to auto-synthesize un-declared symbols.

File: tests/baselines/reference/ES5SymbolProperty2.errors.txt [hunk 10]
```diff
@@ -1,15 +1,12 @@
...
 
-==== tests/cases/conformance/Symbols/ES5SymbolProperty2.ts (2 errors) ====
+==== tests/cases/conformance/Symbols/ES5SymbolProperty2.ts (1 errors) ====
     module M {
         var Symbol: any;
     
         export class C {
             [Symbol.iterator]() { }
-             ~~~~~~~~~~~~~~~
-!!! error TS2471: A computed property name of the form 'Symbol.iterator' must be of type 'symbol'.
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/ES5SymbolProperty2.errors.txt:12]: This used to be close to giving a good error. Do we have any strictness flag that disallows this?

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -3677,11 +3678,25 @@ namespace ts {
                 const additionalContainers = mapDefined(container.declarations, fileSymbolIfFileSymbolExportEqualsContainer);
                 const reexportContainers = enclosingDeclaration && getAlternativeContainingModules(symbol, enclosingDeclaration);
                 const objectLiteralContainer = getVariableDeclarationOfObjectLiteral(container, meaning);
-                if (enclosingDeclaration && getAccessibleSymbolChain(container, enclosingDeclaration, SymbolFlags.Namespace, /*externalOnly*/ false)) {
+                if (enclosingDeclaration && container.flags & getQualifiedLeftMeaning(meaning) && getAccessibleSymbolChain(container, enclosingDeclaration, SymbolFlags.Namespace, /*externalOnly*/ false)) {
                     return append(concatenate(concatenate([container], additionalContainers), reexportContainers), objectLiteralContainer); // This order expresses a preference for the real container if it is in scope
                 }
+                // we potentially a symbol which is a member of the instance side of something - look for a variable in scope with the container's type
+                // which may be acting like a namespace
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:3685]: Like `Symbol` in the global scope acts like a namespace you look up `Symbol.iterator` from even through it's actually a `var`.

File: tests/baselines/reference/ES5SymbolProperty2.errors.txt (hunk 10 above)
Comment (weswigham) [reply tests/baselines/reference/ES5SymbolProperty2.errors.txt:12]: Nope? Pretty sure we allow computed named with completely arbitrary (key compatible) types and just infer an index signature.

File: tests/baselines/reference/ES5SymbolProperty1.types (hunk 9 above)
Comment (weswigham) [reply tests/baselines/reference/ES5SymbolProperty1.types:23]: Eck, no, I don't think we should. `Symbol.foo` definitely doesn't exist, so you're actually using `undefined` as a key name, if you wanna follow the coercions... That means you actually have a field by the name `"undefined"`. A string indexer is definitely more accurate than the old behavior, of manufacturing a key with a name type that doesn't actually exist.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:5122]: `valueDeclaration` is unset in two cases - one: when the symbol doesn't have a value meaning (as when it comes from an interface), two: when two value symbols merge and have differing value declarations. In both cases, we'd like a context node for the name here.

File: tests/baselines/reference/ES5SymbolProperty2.errors.txt (hunk 10 above)
Comment (DanielRosenwasser) [reply tests/baselines/reference/ES5SymbolProperty2.errors.txt:12]: Yeah, but what do you want to do when you have a key of type `any`? I can't imagine why you'd want that behavior under `--strict`.

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts:25345]: You definitely don't wanna go the opposite way, because the numeric index signature we otherwise make makes very little sense, IMO. I actually think `any` producing a `number` index signature just feels a bit like a bug that we aight to fix.

File: tests/baselines/reference/ES5SymbolProperty1.types (hunk 9 above)
Comment (DanielRosenwasser) [reply tests/baselines/reference/ES5SymbolProperty1.types:23]: Yeah, never mind, I actually misread this test. Plus, for the case I was thinking of, we should consider that as a separate issue.

File: src/compiler/checker.ts (hunk 6 above)
Comment (weswigham) [reply src/compiler/checker.ts:35186]: I'm saying that properties with a name like that can no longer be constructed, so when the proper name cannot be found, returning a name like that will always make a follow-up property lookup fail, which has the desired outcome.

File: src/compiler/checker.ts (hunk 5 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:25345]: I get that, but I think the `any` behavior is already pretty undesirable, and is exacerbated if you're not using `--noUncheckedIndexedAccess`.

File: tests/baselines/reference/ES5SymbolProperty2.errors.txt (hunk 10 above)
Comment (weswigham) [reply tests/baselines/reference/ES5SymbolProperty2.errors.txt:12]: I mean, when `Symbol` isn't typed `any`, as in this test, we issue a lookup error...

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts:25345]: ???? That flag is about accessing keys and the types accessed keys are assigned, where here the issue is solely weather or not we make a key at all, and what slot that key should go in; that seems wholly unrelated to that flag.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:25345]: Sorry, I meant `--noPropertyAccessFromIndexSignature`.

Comment (weswigham) [reply src/compiler/checker.ts:25345]: > I get that, but I think the any behavior is already pretty undesirable

Yes! Which is why this improves it, so
```ts
const s = {["str" as any]: "str"}
```
s can be indexed by `"str"` rather than only objective nonsense whose lookup would never work like `12`. And let's be perfectly clear here: you've used an `any` (or have one derived from an error) - _some part_ of type checking is going to be turned off. We shouldn't _ignore_ an `any`-typed computed property key (and I'm definitely not going to do that in this PR, that's for sure - that'd be a massive breaking change) - then you'd just end up with `{}` which is _really_ going to hurt a _lot_ of common uses.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:25345]: But

```ts
const s = {["str" as any]: "str"}
```

can now be indexed by a wider variety of nonsense that would never work either, like `s["uh oh"]`. You're allowing a much more optimistic type to be formed which you can't take back after the fact.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:25345]: And in fact, I think that's why the numeric index signature was chosen - because at the time we also felt the behavior it supported was *more* desirable even if it wasn't good.

The point of the numeric index signature isn't to support indexing with `number`s - it's to support indexing with `any` and still getting the appropriate type out. It's a hack, but it doesn't widen the net to every possible non-numeric property.

Comment (weswigham) [reply src/compiler/checker.ts:25345]: But the point of `any` _is_ to "widen the net".

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:25345]: At best this isn't something we need to change with this feature. I don't find the "well known symbol that doesn't exist" thing to be a use-case that should fundamentally change what happens when you use `any` as a computed property key.

Comment (weswigham) [reply src/compiler/checker.ts:25345]: Alright 🤷‍♂️

**Review by sandersn — CHANGES_REQUESTED** [review]
Some questions while I look at the rest of the tests

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -3677,11 +3678,25 @@ namespace ts {
...
+                    return forEachEntry(t, s => {
+                        if (s.flags & getQualifiedLeftMeaning(meaning) && getTypeOfSymbol(s) === getDeclaredTypeOfSymbol(container)) {
+                            return s;
+                        }
+                    });
+                }) : undefined;
                 const res = append(append(additionalContainers, container), objectLiteralContainer);
-                return concatenate(res, reexportContainers);
+                const resWithReexports = concatenate(res, reexportContainers);
+                return firstVariableMatch ? [firstVariableMatch, ...resWithReexports] : resWithReexports;
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:3699]: I don't think a bunch of `.push` or `.unshift` calls make it that much nicer. Plus, it makes the final ordering less clear, imo.

[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:3699]: It might not be too bad

```ts
const res = firstVariableMatch ? [firstVariableMatch, ...additionalContainers] : additionalContainers;
append(res, container);
append(res, objectLiteralContainer);
addRange(res, reexportContainers);
return res;
```

I guess the thing you lose is the distinction between which ones are re-exports?

[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:3699]: Alternatively

```ts
return (emptyArray as Node[]).concat(
    firstVariableMatch,
    additionalContainers,
    container,
    objectLiteralContainer,
    reexportContainers,
);
```

which might be able to pre-allocate.

File: tests/baselines/reference/ES5SymbolProperty5.types [hunk 13]
```diff
@@ -14,8 +14,8 @@ class C {
 }
 
 (new C)[Symbol.iterator](0) // Should error
```
[the remark this answers is not in the document]
Comment (weswigham) [reply tests/baselines/reference/ES5SymbolProperty5.types:16]: `Symbol.iterator` in this case comes from an anonymous type on a `Symbol` variable declaration, so the interop `symbol` -> `unique symbol` code path doesn;t take effect. So the `Symbol.iterator` in the class body makes an index signature, and that index signature doesn't handle symbols because they never do, hence the failed lookup here. It's not a problem that arises in the real world, since in the real world, the `lib` defines the global `Symbol` type using the `SymbolConstructor` type which we apply interop logic to.

File: src/compiler/checker.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:3699]: For the later, it doesn't handle the possible-`undefined`-ness that many of those members have, which is the entire reason `concatenate` is in use here - it handles `undefined`. `reexportContainers` is possibly `undefined`, which means that `concat` call would add an `undefined` to the end of the array, which would be bad.

File: tests/baselines/reference/ES5SymbolProperty5.types (hunk 13 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply tests/baselines/reference/ES5SymbolProperty5.types:16]: So....what is this test testing? Anything useful? Maybe it could be removed?

**Review by sandersn — APPROVED** [review]
Looks good; still need to figure out why es5for-oftypecheck10 stopped getting a special-cased error.

And maybe es5symbolproperty5 can be deleted? I couldn't tell.

File: tests/baselines/reference/ES5SymbolProperty5.types (hunk 13 above)
[the remark this answers is not in the document]
Comment (weswigham) [reply tests/baselines/reference/ES5SymbolProperty5.types:16]: If/when we get proper symbol index signature support, its behavior should change, so I don't think it should be removed.

File: tests/baselines/reference/ES5For-ofTypeCheck10.errors.txt [hunk 14]
```diff
@@ -20,4 +20,4 @@ tests/cases/conformance/statements/for-ofStatements/ES5For-ofTypeCheck10.ts(14,1
     
     for (var v of new StringIterator) { }
                   ~~~~~~~~~~~~~~~~~~
-!!! error TS2569: Type 'StringIterator' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
\ No newline at end of file
+!!! error TS2495: Type 'StringIterator' is not an array type or a string type.
```
[the remark this answers is not in the document]
Comment (weswigham) [reply tests/baselines/reference/ES5For-ofTypeCheck10.errors.txt:23]: > !!! error TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

The `Symbol.iterator` member no longer exists, because `Symbol.iterator` doesn't exist (this is an ES5 target project).

**Comment by coreh** [comment]
Should `Symbol.prototype` also be affected by this change?

https://github.com/microsoft/TypeScript/blob/616e6e6ca3e87313cc111413ad74d0b49a6cf667/src/lib/es2015.symbol.d.ts#L5

Right now it's a `Symbol` and not a `symbol`, so it doesn't seem to get the `unique symbol` treatment.

**Comment by ExE-Boss** [comment]
@coreh `Symbol.prototype` is the [Symbol prototype object](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-properties-of-the-symbol-prototype-object).

**Comment by coreh** [comment]
Yeah... only after posting my comment I realized that I had gotten it mixed up with `Symbol.species`. Edited.
