### PR TITLE
Fix organizeImports with type-only imports

### LINKED ISSUE #36798: [3.8] Organize imports combines `export` and `export type` declarations
**TypeScript Version:**  3.8-rc1 / 3.9.0-dev.20200214

**Search Terms:** organize, organize imports

**Code**

```ts
// These are types
export type {
    UpdateRecognitionProps
} from "./mutations";

// These are methods
export {
    updateRecognitionCurrentUserMutation,
    updateRecognitionMutation
} from "./mutations";
```

**Expected behavior:** Organizing the import should keep type and non-type exports separate. 

**Actual behavior:** Organizing the imports causes the two to combine into a single `export {}` declaration. The behaviour of whether or not it becomes an `export {}` or `export type {}` is determined by which type of `export` comes first. For example, in the above code the two are combined into a single `export type {}`, since `export type` is first. 

Example output:

```ts
// These are types
export type { updateRecognitionCurrentUserMutation, updateRecognitionMutation, UpdateRecognitionProps } from "./mutations";
```

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.8-Beta#code/PTAEBUAsFMGdtAQwE4IC4E8AOcCwAoaADywHtk1RMdQBvA0R0AVSwBNE1oAlaAY1IBzAHYBLNKNLCACslJZYBAL6gAZnIC2oAEQA6YBoCuaTpOGxtAbgIEQEGPCSpQG6Gkik2iwiXKV6+EyghuycPPxCYhJSAMKGyKjCaMzwyACyxqZSADQMTCEcXLwCIuJmGSbRwspqmjr6RpVmFtb4QA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/36102#issuecomment-584062955

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #36798 

Not sure how I missed this originally 😱 

There is room for opinions on how type-only imports should be sorted relative to non-type-only imports, but I’d suggest the time for those opinions is not 80 minutes before our release build 😄 

Tip: review ignoring whitespace

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.8

**Comment by DanielRosenwasser** [comment]
Fine I'll do it myself you annoying robot

File: src/testRunner/unittests/services/organizeImports.ts [hunk 1]
```diff
@@ -168,6 +168,28 @@ namespace ts {
...
+                    `import { z } from "lib";`,
+                    `import type { x, y } from "lib";`);
+                assertListEqual(actualCoalescedImports, expectedCoalescedImports);
+            });
+
+            it("Do not combine type-only default, namespace, or named imports with each other", () => {
+                const sortedImports = parseImports(
+                    `import type { x } from "lib";`,
+                    `import type * as y from "lib";`,
+                    `import type z from "lib";`);
```
Comment (sheetalkamat) [inline src/testRunner/unittests/services/organizeImports.ts]: Why cant this mix with `import type { x, default as z} from "lib` just like normal import statement ?

Comment (amcasey) [reply src/testRunner/unittests/services/organizeImports.ts]: I believe we decided it would be ambiguous what the "type" keyword applied to and forced explicitness.

Comment (andrewbranch) [reply src/testRunner/unittests/services/organizeImports.ts]: It could, but I’m not confident that’s desirable. My personal preference for readability would probably be what’s represented here in the test.

Comment (amcasey) [reply src/testRunner/unittests/services/organizeImports.ts]: @andrewbranch Consider adding a comment about this: `// Type-only imports are not allowed to combine (for readability)`.  Maybe on the test too.

Comment (DanielRosenwasser) [reply src/testRunner/unittests/services/organizeImports.ts]: Probably possible at a later pass, but seems reasonable to leave it the way it is now until we get further feedback.

Comment (amcasey) [reply src/testRunner/unittests/services/organizeImports.ts]: If this is a stylistic choice in organizeImports, I don't think "allowed" is the right word - I definitely read that as a language restriction.

Comment (andrewbranch) [reply src/testRunner/unittests/services/organizeImports.ts]: My comment in the implementation was actually referring to the language restriction, ignoring the possibility of rewriting the default as a named import. I’ll follow up to clarify.
