### PR TITLE
fix(44179): disentangle the meaning of `SymbolLinks.target`

### LINKED ISSUE #44179: The inferred return type of a function with a generic that spreads an `import * as` doesn't include some exports when they're exported seperately to the declaration
# Bug Report

### 🔎 Search Terms

export, import as, generic, spread

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this and none seem to relate to this behavior 

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKAzgFwK6SQB0u2AUOSDgO7IAO90iA5qLgBbyiT6IDGuaAHtEoACbx+sZACdkQ0aBrRO7Ltm6z42fLDKhm67tjTd4s2cNlUw05Nmw5h6TszYBvAL63Q-UXjOrhzuoAC8oB4AHhi4svjwXgDclNSoyADWoaqgyKD0stCoqtAAbtziwjqIAOS4ftoK3MhiFlay6sL4LBy+-oiB2C7wbqzhoDU1KeS8AopiQ8HuABQAlJE+5PBR9Nb1HkEjIWPJlNu7svWzgiKtO3vw4gAi0NqCsACeaxupYFBwSDMWGYkiipAoRQu9QAVLknHhCJAeFZUKAAETEYAIoho6bUGjWDIUbEkRZHdwpEnEc4PZ6vKS4T7Ta7zUAsEYAZQIRAAPAAVAB83w85FAfgC9VGbAiB2IcpJoFOYvxhIoYqlxDJUpSYqpNMujxeb0ZHx1oG0BFkYm15E21AAClZ6BZcB8JmSAGJ8fhPKSwGoSKpORDCerbaCBJSu50TA6e72+6QAUXuBrpxs+aywpWE0HESUVNWI5HZuC5iLWmuGNpVsiJJc53Mglf1uEN9PepqAA)

### 💻 Code

```ts repro
// @filename: stuff.ts

// swapping the function declaration with these results in the same error
// class something {}
// const something = {x:true};

// making it a primitive doesn't create an error though
// const something = '';

function something() {}

export { something };

export function exportedDirectly() {}

// @filename: index.ts
import * as stuff from "./stuff";

// works
stuff.something;
stuff.exportedDirectly;

function getStuff<T>() {
  const thing = { ...stuff };
  // works
  thing.something;
  stuff.exportedDirectly;
  return thing;
}

// Property 'something' does not exist on type '{ exportedDirectly(): void; }'.
getStuff().something;
// works
getStuff().exportedDirectly;
```

### 🙁 Actual behavior

Declarations that are exported separately to the declaration aren't included in the inferred return type with the exception of primitives (though maybe there are others that work as well?). This is wrong since the property exists at runtime and exists if the generic isn't there.

### 🙂 Expected behavior

All the exports are included since that's what happens at runtime and what happens when there isn't a generic on the function.

### PR DESCRIPTION
**Pull request by lowr**
Fixes #44179

FWIW, there are several other places in checker (L.21013, L.27167, L.27391 as of 48228b810fcac58003c8342f577fa2ea414367bc) where "unresolved" Symbol is set to `target` of newly created Symbol. I ran all tests but couldn't find any code in which alias Symbol is substituted to `target` like the issue, so I left them intact.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16496,7 +16496,7 @@ namespace ts {
             const result = createSymbol(symbol.flags, symbol.escapedName, CheckFlags.Instantiated | getCheckFlags(symbol) & (CheckFlags.Readonly | CheckFlags.Late | CheckFlags.OptionalParameter | CheckFlags.RestParameter));
             result.declarations = symbol.declarations;
             result.parent = symbol.parent;
-            result.target = symbol;
+            result.target = resolveSymbol(symbol);
```
Comment (weswigham) [inline src/compiler/checker.ts:16499]: `instantiateSymbol` should absolutely not be eagerly resolving symbols like this, much as it may fix an issue like this, it's liable to cause other (performance) issues elsewhere. Instead, the code doing the spread copying needs to be resolving the symbols it's copying the members of, otherwise it can't guarantee they're all present.

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (lowr) [reply src/compiler/checker.ts:16499]: It seems the code doing the spread copying is already resolving the symbols it's copying the members of, but not the members themselves, which may be aliases and set to `target`, causing the problem. Resolving every member of a symbol upon checking the spread copying isn't what we want either, right?

I do understand now that `instantiateSymbol` shouldn't be resolving those symbols. How about not setting `result.target` when `symbol` is an alias? This fixes the issue in proper way, I believe, in that it also defers the resolution of member symbols maximally.

Comment (weswigham) [reply src/compiler/checker.ts:16499]: Hmm, I think the fundamental issue is that symbol instantiation and alias resolution shouldn't both be using the same field (for referring to the original symbol and for caching the alias resolution result, respectively). Maybe there was a time when it was safe because instantiated (or copied) alias symbols couldn't exist, but that time is certainly not now. IMO, we should swap the usage in `resolveAlias` to use a new member (`aliasTarget`?) to cache results, rather than `.target`, and see if we can fix up what breaks and disentangle the two meanings of a `.target`. Something like https://gist.github.com/weswigham/22acfad2595f1c1eab3d357385907e90 looks like a promising start to that, though some more changes may be needed to fixup some assumptions in the language service.

Comment (lowr) [reply src/compiler/checker.ts:16499]: Disentangling the meanings of `target` sounds really nice and would make the code cleaner! Thanks for the patch, I've applied it and saw some fourslash tests failing as you anticipated. Let me fix things up in the coming days.

**Comment by sandersn** [comment]
Do you want to keep working on this? Otherwise I'd like to close it to reduce the number of open PRs.

**Comment by lowr** [comment]
Sorry for the huge delay. I'll work on this over the weekend.

**Review by weswigham — APPROVED** [review]
Nice, thanks for helping wrap this up.

@sandersn and @andrewbranch you wanna be extra eyes on this for a merge, since I helped author it?

**Review by andrewbranch — APPROVED** [review]
Ah, this is great. The overloading of this property definitely caused me confusion before I learned to expect it.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -42137,11 +42137,11 @@ namespace ts {
                 const { leftSpread, rightSpread, syntheticOrigin } = symbol as TransientSymbol;
                 return leftSpread ? [leftSpread, rightSpread!]
                     : syntheticOrigin ? [syntheticOrigin]
-                    : singleElementArray(tryGetAliasTarget(symbol));
+                    : singleElementArray(tryGetTarget(symbol));
             }
             return undefined;
         }
-        function tryGetAliasTarget(symbol: Symbol): Symbol | undefined {
+        function tryGetTarget(symbol: Symbol): Symbol | undefined {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:42144]: Seems like this function didn't need to be renamed?

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:42144]: It was renamed because it handles `.target` rather than `.aliasTarget` lookups, for clarity.

Comment (andrewbranch) [reply src/compiler/checker.ts:42144]: Ack, my comment was misguided because of GitHub's silent truncation of the diff. It looked like this function was handling `.aliasTarget` still. All good.
