### PR TITLE
fix(39836): `unknown` type declaration for catch argument doesn't work in js

### LINKED ISSUE #39836: `unknown` type declaration for catch argument doesn't work in js
From #36775, `unknown` doesn't work in JS with a jsdoc comment:

```ts
try {
	// something
} catch (/** @type {unknown} */ err) {
	// `err` is still typed as `any`:
	err; // $ExpectType unknown
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39836

### CODE REVIEW

File: tests/baselines/reference/api/tsserverlibrary.d.ts [hunk 1]
```diff
@@ -686,7 +686,7 @@ declare namespace ts {
         readonly kind: SyntaxKind.ConstructSignature;
     }
     export type BindingName = Identifier | BindingPattern;
-    export interface VariableDeclaration extends NamedDeclaration {
+    export interface VariableDeclaration extends NamedDeclaration, JSDocContainer {
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/api/tsserverlibrary.d.ts:689]: @sandersn is the best person to judge if this is appropriate

File: tests/cases/conformance/jsdoc/jsdocCatchClauseWithTypeAnnotation.ts [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    try { } catch (/** @type {Error} */ err) { }                     // error in the type
+    try { } catch (/** @type {object} */ err) { }                    // error in the type
+
+    try { console.log(); }
+    // @ts-ignore
+    catch (/** @type {number} */ err) { // e should not be a `number`
+        console.log(err.toLowerCase());
+    }
+
+	// minor bug: shows that the `catch` argument is skipped when checking scope
```
Comment (DanielRosenwasser) [inline tests/cases/conformance/jsdoc/jsdocCatchClauseWithTypeAnnotation.ts:38]: Wait, what do you mean? And is this a TS bug too?

Comment (a-tarasyuk) [reply tests/cases/conformance/jsdoc/jsdocCatchClauseWithTypeAnnotation.ts:38]: @DanielRosenwasser Thanks for the feedback. This comment form the original test which handles `unknown` in TypeScripthttps://github.com/microsoft/TypeScript/blob/4c62f6e7d62188d8fecb92300c72d1435924cb64/tests/cases/conformance/statements/tryStatements/catchClauseWithTypeAnnotation.ts#L28-L31

File: tests/baselines/reference/api/tsserverlibrary.d.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/baselines/reference/api/tsserverlibrary.d.ts:689]: @DanielRosenwasser Yes, you are right. Quick note: `try {} catch (/** @type {unknown} */ e) {}` - `e` is a `VariableDeclaration`, and in the current implementation, JSDoc comment is not attached to `e`. To have the opportunity to add type declaration we node has to have JSDoc, these changes related to that. Does that make sense?  If there is a better way to do this, I can change that.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -35601,10 +35603,11 @@ namespace ts {
                 // Grammar checking
                 if (catchClause.variableDeclaration) {
                     const declaration = catchClause.variableDeclaration;
-                    if (declaration.type) {
-                        const type = getTypeForVariableLikeDeclaration(declaration, /*includeOptionality*/ false);
+                    const typeNode = getEffectiveTypeAnnotationNode(getRootDeclaration(declaration));
+                    if (typeNode) {
+                        const type = getTypeFromTypeNode(typeNode);
```
Comment (sandersn) [inline src/compiler/checker.ts:35608]: I think you should call getTypeForVariableLikeDeclaration here instead of getTypeFromTypeNode. If that doesn't work right now, then getTypeOfVariableOrParameterOrPropertyWorker should be fixed.

File: tests/baselines/reference/api/tsserverlibrary.d.ts (hunk 1 above)
Comment (sandersn) [reply tests/baselines/reference/api/tsserverlibrary.d.ts:689]: No, I think this is the best way.
In fact, in normal `var` declarations, we don't currently look for jsdoc on VariableDeclarations, meaning that `x: boolean` and `y: boolean` below, instead of `string` and `number` (or error, because of the conflict).

```js
/** @type {boolean} */
var /** @type {string} */ x, /** @type {number} */ y;
```

Actually, can you add the above as a test? I wonder how much of that will Just Work after this change. It's likely that quite a bit of it will, because there's no walking up the tree required.

If it *doesn't*, that's fine; we haven't had anybody ask for it, nor have we gone looking whether it's a common pattern (my guess is No).

**Review by sandersn — CHANGES_REQUESTED** [review]
Requested a couple of changes

File: tests/baselines/reference/api/tsserverlibrary.d.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/baselines/reference/api/tsserverlibrary.d.ts:690]: > Actually, can you add the above as a test? 

@sandersn I've added a test and the other tests seem to work fine.

**Review by sandersn — APPROVED** [review]
