### PR TITLE
fix(45919): TS2775 when using arrow function for type predicate

### LINKED ISSUE #45919: TS2775 when using arrow function for type predicate
# Bug Report

Our shop prefers arrow function style and JSDoc annotations. I've got a type predicate that works as a function declaration but as an arrow function, I get 2775

### 🔎 Search Terms

 - arrow function
 - type predicate
 - TS2775

### 🕗 Version & Regression Information

Version 4.2.3 (and whatever version the playground runs)

- This is the behavior in every version I tried

### ⏯ Playground Link

[error](https://www.typescriptlang.org/play?ts=4.4.2&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJIBPAB2QBNkAzUAb3tABtkBzaALlADsBXALYAjZACdQAXwmgAgjwCWAgIbMCOYFlz5CxclVoNZC5c1AAyQ9CUkuoAORClotHamgAIgHs2ajdjxqEGROSgIMcooq0tAU8IrIPIHgosiQfKI80IZK0NBiMKAxqPE8oPJZXmySvhjIAB5knqKQoPCemS3wSgo8yKAAvIWxJQMAfAwEZXQAFFq6FIaVkoRg00VxAgkAlAB0VjagAIT9gw5OLlugkIiingDuoAAqegCiorei01sA3JMpaRlQHweNQaPJepRfhJfv4iOBgqJQpZIKJwWwANoAXWWTjYADcVrUGk1Ou1oC1lOCBqBcQT+uN6JM5lA9IYIiZlupJm0OkNipseABGakAKQAygB5AByOwReWmtPRAGZMT9ud1wcg1sMBYK1aBWmTPKwdsxvNr+QlBXtrNA1dCMEA)

### 💻 Code

```ts
// @ts-check

/**
 * @typedef {{ legs: number }} Animal
 */

/**
 * @typedef { Animal & { says: 'bark'}} Dog
 */

/**
 * @param {Animal} specimen
 * @returns { asserts specimen is Dog }
 */
export const canine = specimen => {
  if (/** @type { Dog } */ (specimen).says !== 'bark') throw TypeError();
  return undefined;
};

/** @param { string[] } argv */
export const main = argv => {
  /** @type { Animal } */
  const specimen1 = JSON.parse(argv[3]);
  canine(specimen1);
  console.log(specimen1.says);
};
```

### 🙁 Actual behavior

```
Assertions require every name in the call target to be declared with an explicit type annotation.(2775)
```

### 🙂 Expected behavior

same as when I change the arrow function to a function declaration:

[no error](https://www.typescriptlang.org/play?ts=4.4.2&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJIBPAB2QBNkAzUAb3tABtkBzaALlADsBXALYAjZACdQAXwmgAgjwCWAgIbMCOYFlz5CxclVoNZC5c1AAyQ9CUkuoAORClotHamgAIgHs2ajdjxqEGROSgIMcooq0tAU8IrIPIHgosiQfKI80IZK0NBiMKAxqPE8oPJZXmySvhjIAB5knqKQoDR8PPCQ8p6l8EoKPMgAFEVxAgkAlAwEZXRDWroUhpWShGAjsSUTAHRWNqAAhAC8R-aOznZTkIiingDuoAAqegCioreiQxMA3DMpaRlQO1qDR5INKL8JL9-ERwMFRKFLJBRGC2ABtAC6qycbAAbmtag0mi14D1oC1lGDQKccfijgA+aagUALKB6QwREyrdQzUmZFqjEoARmpoAAUgBlADyADltvC8kNaWiAMwYn68-pg4aC8Y8IUa5l86CeVjbZjeDbFPVC3bWaAaqEYIA)

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45919

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22983,10 +22983,10 @@ namespace ts {
...
         }
 
-        function isDeclarationWithExplicitTypeAnnotation(declaration: Declaration) {
-            return (declaration.kind === SyntaxKind.VariableDeclaration || declaration.kind === SyntaxKind.Parameter ||
-                declaration.kind === SyntaxKind.PropertyDeclaration || declaration.kind === SyntaxKind.PropertySignature) &&
-                !!getEffectiveTypeAnnotationNode(declaration as VariableDeclaration | ParameterDeclaration | PropertyDeclaration | PropertySignature);
+        function isDeclarationWithExplicitTypeAnnotation(node: Declaration) {
+            return (isVariableDeclaration(node) || isPropertyDeclaration(node) || isPropertySignature(node) || isParameter(node)) &&
+                !!(getEffectiveTypeAnnotationNode(node) ||
+                    isInJSFile(node) && hasInitializer(node) && node.initializer && isFunctionExpressionOrArrowFunction(node.initializer) && getEffectiveReturnTypeNode(node.initializer));
```
Comment (sandersn) [inline src/compiler/checker.ts:22989]: `getEffectiveReturnTypeNode` already does the correct check for JS files, and I don't think this needs to be restricted to function/arrow expressions:
```suggestion
                    hasInitializer(node) && node.initializer && getEffectiveReturnTypeNode(node.initializer));
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -26322,10 +26322,6 @@ namespace ts {
             return !hasEffectiveRestParameter(signature) && getParameterCount(signature) < targetParameterCount;
         }
 
-        function isFunctionExpressionOrArrowFunction(node: Node): node is FunctionExpression | ArrowFunction {
```
Comment (sandersn) [inline src/compiler/checker.ts:26325]: (and this move doesn't need to happen if the first comment is correct)

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks good, although I think it can be slightly more general.

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:22989]: @sandersn Thanks. It seems `isInJSFile` is useless. I used `isFunctionExpressionOrArrowFunction` to follow a type signature that is compatible with `getEffectiveReturnTypeNode` in order to avoid type casting. Can `node.initializer` contain more than just function/arrow expressions?

Comment (a-tarasyuk) [reply src/compiler/checker.ts:22989]: One note about `isInJSFile`. Is it valid to allow the following case? 
```ts
const assert = (value: unknown): asserts value => {}
assert(typeof x === "string"); 
```

TS throws an error for that case.
```
error TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.```

Comment (sandersn) [reply src/compiler/checker.ts:22989]: Looking at [the original PR](https://github.com/microsoft/TypeScript/pull/32695):

> This particular rule exists so that control flow analysis of potential assertion calls doesn't circularly trigger further analysis.)

So I think neither the TS nor the equivalent JS is safe:

```js
const assert = /** @param {unknown} value @returns {asserts value} */(value) => {}
```

**Review by sandersn — APPROVED** [review]
No further changes are needed, and I don't think a test for the excluded JS form is either -- it's very unlikely for somebody to write that form.

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:22989]: @sandersn Thanks
