### PR TITLE
Fixed multiple prologue directives with parameter properties

### LINKED ISSUE #48671: No-op string in constructor is repeated and reordered when constructor assignment is used
# Bug Report

The TypeScript code
```ts
class Example {
    constructor(private A: string) {
        "ngInject";
    }
}
```

when compiled with TS 4.6.2 yields:
```js
"use strict";
class Example {
    constructor(A) {
        this.A = A;
        "ngInject";
        "ngInject";
    }
}

```
when compiled with TS 4.5.5 yields:
```js
"use strict";
class Example {
    constructor(A) {
        "ngInject";
        this.A = A;
    }
}
```

The differences are:
* the string `"ngInject;"` is repeated
* the string appears after the constructor assignment, not before as in 4.5.

For our use case, the repetition is probably not a real problem, however the re-ordering is. If any of these two are by design now, we can work around - but I wanted to double check with the TypeScript developers because it seems to be a bit unexpected.

### 🕗 Version & Regression Information

We observed errors in a AngularJS-based project using `ng-annotate-patched` which relies on the string to annotate classes for AngularJS. It works wiht TS 4.5 and broke with TS 4.6.

TS 4.6.2 (broken)
TS 4.5.5 (good)

### ⏯ Playground Link

https://www.typescriptlang.org/play?removeComments=true&target=2&ts=4.5.5#code/MYGwhgzhAECiAeYC2AHEBTaBvAUASGAHsA7CAFwCcBXYMwigChQoEsA3MMzAQQC5pyrYgHMAlNnx4ARCICSxAFbpaUgNz4Avji1A

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Two issues:

* Parameter properties should be inserted _after_ any prologue directives
* Prologue directives were getting copied over twice when there wasn't a `super()`

Fixes #48671

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -35405,7 +35405,7 @@ namespace ts {
                                         superCallStatement = statement;
                                         break;
                                     }
-                                    if (!isPrologueDirective(statement) && nodeImmediatelyReferencesSuperOrThis(statement)) {
+                                    if (nodeImmediatelyReferencesSuperOrThis(statement)) {
```
Comment (JoshuaKGoldberg) [inline src/compiler/checker.ts:35408]: This change isn't necessary for the PR; I just had only noticed the check is unnecessary _after_ #29374 was merged 😄

File: src/compiler/transformers/ts.ts [hunk 2]
```diff
@@ -1938,14 +1938,14 @@ namespace ts {
 
             resumeLexicalEnvironment();
 
-            const indexAfterLastPrologueStatement = factory.copyPrologue(body.statements, statements, /*ensureUseStrict*/ false, visitor);
-            const superStatementIndex = findSuperStatementIndex(body.statements, indexAfterLastPrologueStatement);
+            const prologueStatementCount = factory.copyPrologue(body.statements, statements, /*ensureUseStrict*/ false, visitor);
+            const superStatementIndex = findSuperStatementIndex(body.statements, prologueStatementCount);
```
Comment (JoshuaKGoldberg) [inline src/compiler/transformers/ts.ts:1942]: I'm nitpicking the variable name here. Both variable names are correct; `prologueStatementCount` just makes more sense to me -- especially in the context of the new array spread below.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Thanks for fixing this!

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-4.6

**Comment by jakebailey** [comment]
Sent #48782 manually. This PR is needed for the other PRs thanks to this PR affecting the base `ts.ts` transform.
