### PR TITLE
For import fix, prefer symlink over a real path

### LINKED ISSUE #19893: Auto imports import error module name with cnpm.
_From @Lxxyx on November 9, 2017 6:13_

cnpm: npm client for China mirror of npm.

Github: https://github.com/cnpm/cnpm

- VSCode Version: 1.18

Steps to Reproduce:

1. download this repo: https://github.com/Lxxyx/auto-imports-cnpm
2. install cnpm by: `npm i cnpm -g`
3. use `cnpm i` to install dependencies.
4. in index.js
image
5. but in text.js when I type render:
image

And I Get: `import { render } from "_rax@0.4.20@rax";`

6.  The directory structrue in cnpm installed node_modules:

image

Reproduces without extensions: No

_Copied from original issue: Microsoft/vscode#37882_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19893
Replaces #19910

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -4228,6 +4228,8 @@ namespace ts {
      * If changing this, remember to change `moduleResolutionIsEqualTo`.
      */
     export interface ResolvedModuleFull extends ResolvedModule {
+        /* @internal */
+        readonly originalPath: string | undefined;
```
Comment (sheetalkamat) [inline src/compiler/types.ts]: you would want to add check for originalPath in ```moduleResolutionIsEqualTo``` as well

Comment (sheetalkamat) [reply src/compiler/types.ts]: Why is originalPath not just optional? Also why is it in ResolvedModuleFull and not in ResolvedModule?

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -317,7 +321,7 @@ namespace ts.codefix {
     ): string[] {
         const { baseUrl, paths, rootDirs } = options;
         const choicesForEachExportingModule = mapIterator(arrayIterator(moduleSymbols), moduleSymbol => {
-            const moduleFileName = moduleSymbol.valueDeclaration.getSourceFile().fileName;
+            const moduleFileName = getOriginalModulePath(program, moduleSymbol.valueDeclaration.getSourceFile());
```
Comment (sheetalkamat) [inline src/services/codefixes/importFixes.ts]: Also this doesnt seem right... If the sourceFile2(from firstDefined call from getOriginalModulePath) which included this moduleSymbol is in different folder than the sourceFile this fix is asked for it might not be correct right? The sourceFile could refer to the symlinked location through some other node_modules symlink... (in the sense orignalFilePath for referencing this moduleSymbol could be different while resolving through sourceFile and sourceFile2?

Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: It's possible that there are multiple symlinks to the same module, although it's not technically *wrong* to use one or the other since it works either way; we could iterate over all known symlinks though and take the best, would that be better?

File: src/compiler/types.ts (hunk 1 above)
Comment (andy-ms) [reply src/compiler/types.ts]: The only reason we have both `ResolvedModule` and `ResolvedModuleFull` is backwards compatibility. Since this is an internal property it doesn't really matter where it goes.

Comment (sheetalkamat) [reply src/compiler/types.ts]: Why is it then string|undefined.. Looking at the changes it seems like it could be made optional instead to avoid setting it to undefined in all the other cases except 1

File: src/compiler/moduleNameResolver.ts [hunk 3]
```diff
@@ -752,17 +752,23 @@ namespace ts {
...
                 // For node_modules lookups, get the real path so that multiple accesses to an `npm link`-ed module do not create duplicate files.
-                return { value: resolvedValue && { resolved: resolvedValue, isExternalLibraryImport: true } };
+                return { value: resolvedValue && { resolved: resolvedValue, originalPath, isExternalLibraryImport: true } };
             }
             else {
                 const { path: candidate, parts } = normalizePathAndParts(combinePaths(containingDirectory, moduleName));
                 const resolved = nodeLoadModuleByRelativeName(extensions, candidate, failedLookupLocations, /*onlyRecordFailures*/ false, state, /*considerPackageJson*/ true);
                 // Treat explicit "node_modules" import as an external library import.
-                return resolved && toSearchResult({ resolved, isExternalLibraryImport: contains(parts, "node_modules") });
+                return resolved && toSearchResult({ resolved, originalPath: undefined, isExternalLibraryImport: contains(parts, "node_modules") });
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts]: Do not set originalPath property

**Comment by andy-ms** [comment]
@sheetalkamat Good to go?
