### PR TITLE
Align the ShimMap iterator behavior with native Maps

### LINKED ISSUE #26090: TypeScript 3.0 language service isn't working properly in IE 11 (in Monaco Editor)
**TypeScript Version:**  3.0.1-insiders.20180726

**Search Terms:** IE11, language service, monaco editor

**Code**

Open the [TypeScript Playground](http://www.typescriptlang.org/Playground) (Monaco Editor using the language service of current TypeScript version `3.0.1-insiders.20180726`) in **IE 11** (on Windows 10, 8.1 or 7) and enter the following code:

```ts
// In IE 11, this doesn't show an error:
let f = function () {
    let g = function() {
        Math.xxxxxxxyyyyzzzz(aaaaaa, bbbbbb, ccccc);
    };
};

// This correctly shows an error:
Math.xxxxxxxyyyyzzzz(aaaaaa, bbbbbb, ccccc);
```

**Expected behavior:**
The unknown properties and variables should be shown as error (which works in other browsers like Edge, Firefox, Chrome):
tsissue-edge

**Actual behavior:**
For the inner function, unknown properties/variables are not shown as error in **IE 11**:
tsissue-ie11

With the previous playground version (I think 2.9.x), this worked correctly. I don't know what could cause this behavior in IE 11, since the console also doesn't show any errors.

Additionally, if you enable `noUnusedLocals` in the Monaco Editor, the editor will sometimes show variables as unused even though they are used (I currently don't have a screenshot of that).

Unfortunately, for a software product at work we still need to use IE 11 (as WebBrowser control in a .NET app), so it would be nice if TypeScript with Monaco Editor would still work properly on IE 11.

**Playground Link:** http://www.typescriptlang.org/play/#src=%2F%2F%20In%20IE%2011%2C%20this%20doesn't%20show%20an%20error%3A%0D%0Alet%20f%20%3D%20function%20()%20%7B%0D%0A%20%20%20%20let%20g%20%3D%20function()%20%7B%0D%0A%20%20%20%20%20%20%20%20Math.xxxxxxxyyyyzzzz(aaaaaa%2C%20bbbbbb%2C%20ccccc)%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20This%20correctly%20shows%20an%20error%3A%0D%0AMath.xxxxxxxyyyyzzzz(aaaaaa%2C%20bbbbbb%2C%20ccccc)%3B%0D%0A%0D%0A

Thank you!

### LINKED ISSUE #29193: Missed imports when transpiling in IE11 (but not in Chrome/Edge/FF)
**TypeScript Version:**  3.2.2
**Browser**: IE11

**Search Terms:**

**Code**

```ts
// Source
import * as theModule from 'someModule';
let myObj = {
    handler: () => {
        let f = function(val) {
            return theModule.someFunction();
        }
        f();
    }
};    

// Output in IE11 begins with (missed dependency, incorrect):
System.register([], function (exports_1, context_1) {
// Output in Chrome/Edge/FF begins with (dependency is present, correct):
System.register(["someModule"], function (exports_1, context_1) {
```

**Expected behavior:**
Source code is transpiled in run-time in a browser. It imports 'someModule' module, and uses a function from it (theModule.someFunction()), so the transpiled code for the System module type should reference 'someModule' in the System.register call, like here:
```ts
System.register(["someModule"], ...
```
**Actual behavior:**
This is how it works in Chrome/Edge/FF browsers, but not in IE11. In IE11 the module reference is missed, like here:
```ts
System.register([], ...
```

**Repro sample:** 
Clone the following repo:
[https://github.com/alexi2014/TS-IE-Missed-Import](https://github.com/alexi2014/TS-IE-Missed-Import)
> npm install
> npm run start

The page will be opened in the default browser. The top text area contains source code, and the bottom one contains transpiled code.
Depending on the browser where you open the page (Chrome/Edge/FF vs IE11), the transpiled result will be different.

**Related Issues:**

### PR DESCRIPTION
**Pull request by kpreisser**
Hi,

this PR adjusts the [`shimMap`](https://github.com/Microsoft/TypeScript/blob/5fb39769ada9ff72d905c62069aab136c93f38a8/src/compiler/core.ts#L117) that is used by `createMap<T>()` for IE 11/ES 5 environments (instead of a native `Map`) to visit values that are added while an iteration or `forEach()` is running (which is documented for a native `Map`). Previously, new values during iteration would not be visited, causing problems in **IE 11** as described in #26090.
I used the same mechanism for both the `forEach` call and iterators created with `.entries()`.

<del>**Note:** With this PR, the `shimMap` does not support deleting values while an iteration is still running - in this case, when the iterator/forEach loop continues after the delete operation, it will throw an error.</del>

<del>I think it is possible to also support deleting values while an iteration is active using a linked list, but with the caveat that a memory leak could occur if you keep a reference to an non-finished iterator, and then continuously add and delete values from the map. Additionally, as long as there are unfinished iterators (that may or may not be reachable), delete operations on the map would be slow, as they would need to search the iterator key elements.</del>

**Update:** I have reworked the implementation so that the `shimMap` should now have the same behavior as a native map for iterators and `forEach()` loops (see comment below). This means that entries are iterated in insertion order, values added during iteration will be visited, and values removed during iteration (before they were visited) will not be visited.

- [x] Add a test that verifies the new behavior of the `shimMap`.

Fixes #26090
Fixes #29193

### CODE REVIEW

**Comment by weswigham** [comment]
> TODO: Add a test that verifies the new behavior of the shimMap (I wasn't sure where to put such a test).

A unit test in the `unittests` folder. You'd probably need to make `shimMap` `export`'d to test it. In runtimes with a real map (aka, everything we CI on) we should probably be testing that it does the same thing as the builtin `Map`.

File: src/compiler/core.ts [hunk 1]
```diff
@@ -121,29 +121,55 @@ namespace ts {
...
 
-        return class <T> implements Map<T> {
-            private data = createDictionaryObject<T>();
-            public size = 0;
+        class ShimMap<T> implements Map<T> {
+            size = 0;
+
+            data = createDictionaryObject<T>();
+
+            currentIteratoKeys?: string[];
```
Comment (weswigham) [inline src/compiler/core.ts]: Typo: `currentIteratoKeys` -> `currentIteratorKeys`

Comment (kpreisser) [reply src/compiler/core.ts]: Fixed.

**Comment by kpreisser** [comment]
Done: The `shimMap` should now have the same behavior for iterators and `forEach` loops as with native maps.
A minor performance drawback is that when calling `.clear()`, all entries (from the linked list) need to be iterated in order to adjust their references, but I think this shouldn't have a visible impact.

**Comment by kpreisser** [comment]
Sorry, I think there is still a minor bug in the `delete()` method. I will look at this tomorrow.

**Comment by kpreisser** [comment]
OK, fixed: The backward reference of the next entry was not correctly adjusted in `delete()`. I think it is ready now.

File: src/compiler/core.ts [hunk 2]
```diff
@@ -174,23 +262,47 @@ namespace ts {
             clear(): void {
                 this.data = createDictionaryObject<T>();
```
Comment (rbuckton) [inline src/compiler/core.ts]: The type `T` here is wrong. The compiler didn't catch that because `MapLike<T>` is a very weak type.

Comment (kpreisser) [reply src/compiler/core.ts]: Thank you, fixed.

**Comment by rbuckton** [comment]
Thanks for the contribution!
