### PR TITLE
 Use the value symbol for decorator purpose only if it is same as type symbol

### LINKED ISSUE #13155: export interface with a property decorator not working
**TypeScript Version:**  2.1.4

**Code**

Interface definition:

```ts
export interface Event { title: string };
```

Decorated property:

```ts
import { Event } from './event.ts';
import { Input } from '@angular/core';

export class SomeClass {
  @Input() event: Event;
}
```

**Expected behavior:**

In the generated code it should be able to find the event module.

**Actual behavior:**

It compiles and in the browser, the Input function is looking for a variable named Event which doesn't exist on the module.

The error is this:

    Uncaught ReferenceError: event_1 is not defined

And the code generated looks like this:

```javascript
    __decorate([
	    core_1.Input(),
	    __metadata("design:type", event_1.Event)
	]
```

Leaving out the type declaration for the decorated property or declare it as an `any` type works. Is there a better workaround than this? Perhaps declaring the type of that property in a declarations file?

*edit:* I found another workaround, I can declare an extra variable, export it from the event.ts and then import it and do a console.log (just to make sure it isn't compiled out). There's a bunch of logs in the console but it does load up.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #13155

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20518,18 +20518,21 @@ namespace ts {
...
-            }
-
-            const constructorType = valueSymbol ? getTypeOfSymbol(valueSymbol) : undefined;
-            if (constructorType && isConstructorType(constructorType)) {
-                return TypeReferenceSerializationKind.TypeWithConstructSignatureAndValue;
-            }
 
             // Resolve the symbol as a type so that we can provide a more useful hint for the type serializer.
             const typeSymbol = resolveEntityName(typeName, SymbolFlags.Type, /*ignoreErrors*/ true, /*dontResolveAlias*/ false, location);
+            if (valueSymbol && valueSymbol === typeSymbol) {
```
Comment (omouse) [inline src/compiler/checker.ts]: just wanna be enlightened about how Typescript type checker works:

if there's already a value called "Event" (like the DOM.Event class) and there is a type declared that is named "Event" and they are equal, we will assume that the reference is to the type rather than to the value?

**Comment by omouse** [comment]
thanks for fixing this bug!! :champagne: 💯

File: src/compiler/checker.ts (hunk 1 above)
Comment (mhegazy) [inline src/compiler/checker.ts]: declarations do merge in TS, see http://www.typescriptlang.org/docs/handbook/declaration-merging.html for more details.
