### PR TITLE
fix(46615): Incorrect assertion in quick fix code

### LINKED ISSUE #38062: Error: Debug Failure. add-name-to-nameless-parameter operates on identifiers, but got a DotDotDotToken in 'makeChange' during 'getCodeFixes'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.8.3
**VSCode version**: 1.44.1
**Command requested**: getCodeFixes
**Hitting sessions**: 1909
**Five line hash**: beadcb30e40dd9ab2dd46d4b21396d61
**Stack**:
```
    at makeChange (tsserver.js:125092:33)
    at <anonymous> (tsserver.js:125083:96)
    at ChangeTracker.with (tsserver.js:123413:17)
    at getCodeActions (tsserver.js:125083:64)
    at <anonymous> (tsserver.js:124540:77)
    at flatMap (tsserver.js:465:25)
    at getFixes (tsserver.js:124540:23)
    at <anonymous> (tsserver.js:135666:35)
    at flatMap (tsserver.js:465:25)
    at getCodeFixesAtPosition (tsserver.js:135664:23)
    at unknown (suppressed.js)
    at Session.getCodeFixes (tsserver.js:145753:64)
    at _a.<computed> (tsserver.js:144510:61)
    at <anonymous> (tsserver.js:146003:88)
    at Session.executeWithRequestId (tsserver.js:145994:28)
    at Session.executeCommand (tsserver.js:146003:33)
    at Session.onMessage (tsserver.js:146027:35)
    at <anonymous> (tsserver.js:147342:27)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
```

### LINKED ISSUE #46615: Incorrect assertion in quick fix code
Extracted from https://github.com/microsoft/TypeScript/issues/38062

```ts
// @noImplicitAny: true

type Rest = (...string) => void;
type Public = (public string) => void;
```

Request quick fixes for this code snippet.

**Expected** Correct quick fixes

**Actual**

```
Error: Debug Failure. add-name-to-nameless-parameter operates on identifiers, but got a DotDotDotToken
    at makeChange (TYPESCRIPT_DIR\lib\tsserver.js:145716:33)
    at TYPESCRIPT_DIR\lib\tsserver.js:145707:96
    at Function.ChangeTracker.with (TYPESCRIPT_DIR\lib\tsserver.js:143896:17)
    at Object.getCodeActions (TYPESCRIPT_DIR\lib\tsserver.js:145707:64)
    at TYPESCRIPT_DIR\lib\tsserver.js:145087:77
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Object.getFixes (TYPESCRIPT_DIR\lib\tsserver.js:145087:23)
    at TYPESCRIPT_DIR\lib\tsserver.js:159943:35
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Proxy.getCodeFixesAtPosition (TYPESCRIPT_DIR\lib\tsserver.js:159941:23)
    at IOSession.Session.getCodeFixes (TYPESCRIPT_DIR\lib\tsserver.js:171425:64)
```

```
Error: Debug Failure. add-name-to-nameless-parameter operates on identifiers, but got a PublicKeyword
    at makeChange (TYPESCRIPT_DIR\lib\tsserver.js:145716:33)
    at TYPESCRIPT_DIR\lib\tsserver.js:145707:96
    at Function.ChangeTracker.with (TYPESCRIPT_DIR\lib\tsserver.js:143896:17)
    at Object.getCodeActions (TYPESCRIPT_DIR\lib\tsserver.js:145707:64)
    at TYPESCRIPT_DIR\lib\tsserver.js:145087:77
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Object.getFixes (TYPESCRIPT_DIR\lib\tsserver.js:145087:23)
    at TYPESCRIPT_DIR\lib\tsserver.js:159943:35
    at Object.flatMap (TYPESCRIPT_DIR\lib\tsserver.js:522:25)
    at Proxy.getCodeFixesAtPosition (TYPESCRIPT_DIR\lib\tsserver.js:159941:23)
    at IOSession.Session.getCodeFixes (TYPESCRIPT_DIR\lib\tsserver.js:171425:64)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #46615
Fixes #38062

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21203,9 +21203,10 @@ namespace ts {
                         (isCallSignatureDeclaration(param.parent) || isMethodSignature(param.parent) || isFunctionTypeNode(param.parent)) &&
                         param.parent.parameters.indexOf(param) > -1 &&
                         (resolveName(param, param.name.escapedText, SymbolFlags.Type, undefined, param.name.escapedText, /*isUse*/ true) ||
-                         param.name.originalKeywordKind && isTypeNodeKind(param.name.originalKeywordKind))) {
+                        param.name.originalKeywordKind && isTypeNodeKind(param.name.originalKeywordKind))) {
                         const newName = "arg" + param.parent.parameters.indexOf(param);
-                        errorOrSuggestion(noImplicitAny, declaration, Diagnostics.Parameter_has_a_name_but_no_type_Did_you_mean_0_Colon_1, newName, declarationNameToString(param.name));
+                        const typeName = declarationNameToString(param.name) + (param.dotDotDotToken ? "[]" : "");
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:21208]: There's technically some nuance because in theory the name can refer to a type that is actually an array type; however, I think that's pretty unlikely, and overall this is nice polish.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.5
