### PR TITLE
Correctly cache tagged template objects in modules

### LINKED ISSUE #17956: Tagged template literals compiled incorrectly, TemplateStringsArray not cached
**TypeScript Version:**  2.4.1

**Code**

```ts
let previousStrings;

function test(strings, ...value) {
  if (previousStrings !== undefined && previousStrings !== strings) {
    window.alert('failure');
  }
  previousStrings = strings;
}

function go(n) {
  return test`literal ${n}`;
}
```

**Expected behavior:**

According to the ECMAScript spec, every time a template tag is evaluated, the _same_ strings object should be passed as the first argument:

> Each TemplateLiteral in the program code of a realm is associated with a unique template object that is used in the evaluation of tagged Templates (12.2.9.6). The template objects are frozen and the same template object is used each time a specific tagged Template is evaluated.

https://tc39.github.io/ecma262/#sec-gettemplateobject

**Actual behavior:**

The above snippet compiles to:

```ts
var previousStrings;
function test(strings) {
    var value = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        value[_i - 1] = arguments[_i];
    }
    if (previousStrings !== undefined && previousStrings !== strings) {
        window.alert('failure');
    }
    previousStrings = strings;
}
function go(n) {
    return (_a = ["literal ", ""], _a.raw = ["literal ", ""], test(_a, n));
    var _a;
}
```

You can see that `_a` is going to have a new identity for each call of go().

FWIW, Babel compiles this correctly:

```js
'use strict';

var _templateObject = _taggedTemplateLiteral(['literal ', ''], ['literal ', '']);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var previousStrings = void 0;

function test(strings) {
  if (previousStrings !== undefined && previousStrings !== strings) {
    window.alert('failure');
  }
  previousStrings = strings;
}

function go(n) {
  return test(_templateObject, n);
}
```

This is breaking lit-html when used in TypeScript: https://github.com/PolymerLabs/lit-html/issues/58

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
This PR is a work in progress at the moment

Remaining things to work on:

- [x] Bikeshed on helper name.
- [x] Bikeshed on helper semantics
- [x] Bikeshed on template object initialization location
- [x] Add helper for tslib
- [x] Add test for tslib
- [ ] Investigate adding behavioral tests
- [x] Fix weird case with un-parenthesized `new` expressions

Fixes #17956

### CODE REVIEW

File: tests/baselines/reference/taggedTemplateStringsWithManyCallAndMemberExpressions.js [hunk 1]
```diff
@@ -16,6 +16,13 @@ var x = new new new f `abc${ 0 }def`.member("hello")(42) === true;
...
+var __getTemplateObject = (this && this.__getTemplateObject) || function (cooked, raw) {
+    if (Object.freeze && Object.defineProperty) {
+        return Object.freeze(Object.defineProperty(cooked, "raw", { value: Object.freeze(raw) }));
+    }
+    cooked.raw = raw;
+    return cooked;
+};
 var f;
-var x = new new new (_a = ["abc", "def"], _a.raw = ["abc", "def"], f(_a, 0)).member("hello")(42) === true;
+var x = new new new f(_a || (_a = __getTemplateObject(["abc", "def"], ["abc", "def"])), 0).member("hello")(42) === true;
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/taggedTemplateStringsWithManyCallAndMemberExpressions.js]: This is a regression.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16664,6 +16664,9 @@ namespace ts {
         }
 
         function checkTaggedTemplateExpression(node: TaggedTemplateExpression): Type {
+            if (languageVersion < ScriptTarget.ES2015) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Apparent change in file permissions?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -24019,6 +24022,7 @@ namespace ts {
                 case ExternalEmitHelpers.AsyncDelegator: return "__asyncDelegator";
                 case ExternalEmitHelpers.AsyncValues: return "__asyncValues";
                 case ExternalEmitHelpers.ExportStar: return "__exportStar";
+                case ExternalEmitHelpers.MakeTemplateObject: return "__makeTemplateObject";
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Not added in this PR, but all of the strings here are duplicated elsewhere in the emitter -- could we move this function to there?

File: src/compiler/transformers/es2015.ts [hunk 4]
```diff
@@ -279,6 +279,16 @@ namespace ts {
         let currentSourceFile: SourceFile;
         let currentText: string;
         let hierarchyFacts: HierarchyFacts;
+        let taggedTemplateStringDeclarations: VariableDeclaration[];
+        function recordTaggedTemplateString(temp: Identifier) {
+            const decl = createVariableDeclaration(temp);
```
Comment (andy-ms) [inline src/compiler/transformers/es2015.ts]: `taggedTemplateStringDeclarations = append(taggedTemplateStringDeclarations, createVariableDeclaration(temp));`

File: src/compiler/transformers/es2015.ts [hunk 5]
```diff
@@ -3636,11 +3652,15 @@ namespace ts {
             // Visit the tag expression
             const tag = visitNode(node.tag, visitor, isExpression);
 
-            // Allocate storage for the template site object
-            const temp = createTempVariable(hoistVariableDeclaration);
+            // Allocate storage for the template site object if we're in a module.
+            // In the global scope, any variable we currently generate could conflict with
+            // variables from outside of the current compilation.
+            const temp = isExternalModule(currentSourceFile) ? createTempVariable(recordTaggedTemplateString) : undefined;
```
Comment (andy-ms) [inline src/compiler/transformers/es2015.ts]: Could this variable be created closer to its use, or is there some side effect I'm missing?
If you do move it next to its use, you could just replace `!temp ? ...` with `!isExternalModule(currentSourceFile) ? ...`

File: src/compiler/transformers/es2015.ts [hunk 6]
```diff
@@ -4052,4 +4089,19 @@ namespace ts {
...
     };
+
+    const templateObjectHelper: EmitHelper = {
+        name: "typescript:makeTemplateObject",
+        scoped: false,
+        priority: 0,
+        text: `
+            var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
+                if (Object.defineProperty) {
+                    return Object.defineProperty(cooked, "raw", { value: raw });
```
Comment (andy-ms) [inline src/compiler/transformers/es2015.ts]: Would be more readable if both branches shared `return cooked;`:
```ts
if (Object.defineProperty) {
    Object.defineProperty(cooked, "raw", { value: raw });
} else {
    cooked.raw = raw;
}
return cooked;
```

File: src/compiler/types.ts [hunk 7]
```diff
@@ -4304,7 +4306,7 @@ namespace ts {
         SpreadIncludes = Read | Spread,
 
         FirstEmitHelper = Extends,
-        LastEmitHelper = ExportStar
+        LastEmitHelper = ExternalEmitHelpers[" LastPlusOne"] - 1
```
Comment (andy-ms) [inline src/compiler/types.ts]: You could also just move this next to the last one to make it obvious that these should be updated together.

File: src/compiler/transformers/es2015.ts [hunk 8]
```diff
@@ -3658,16 +3678,21 @@ namespace ts {
...
-                    createAssignment(createPropertyAccess(temp, "raw"), createArrayLiteral(rawStrings)),
-                    createCall(tag, /*typeArguments*/ undefined, templateArguments)
-                ])
-            );
+            const helperCall = createTemplateObjectHelper(context, createArrayLiteral(cookedStrings), createArrayLiteral(rawStrings));
+
+            // If we're in the global scope, we risk having conflicting variables.
+            // Since we currently lack the infrastructure to create sufficiently unique names,
+            // we'll fall back to creating the template object on every invocation.
+            templateArguments[0] = !temp ?
```
Comment (sandersn) [inline src/compiler/transformers/es2015.ts]: if isExternalModule is cheap to call, it would be nice to do so here; much easier to read.

Comment (sandersn) [reply src/compiler/transformers/es2015.ts]: Also consider flipping the conditional.

File: src/compiler/transformers/es2015.ts (hunk 6 above)
Comment (weswigham) [reply src/compiler/transformers/es2015.ts]: Alternatively, you can go for even less readable, and do `return Object.defineProperty ? Object.defineProperty(cooked, "raw", { value: raw }) : (cooked.raw = raw, cooked);`. Can cram the entire helper into one line and it's not bad, actually:
```
var __makeTemplateObject = (this && this.__makeTemplateObject) || (cooked, raw) => Object.defineProperty ? Object.defineProperty(cooked, "raw", { value: raw }) : (cooked.raw = raw, cooked);
```
Too bad we don't transpile helpers 👅

File: tests/baselines/reference/printerApi/printsNodeCorrectly.newExpressionOnConditionalExpression.js [hunk 9]
```diff
@@ -0,0 +1 @@
+new (x ? y : z)
```
Comment (weswigham) [inline tests/baselines/reference/printerApi/printsNodeCorrectly.newExpressionOnConditionalExpression.js]: Was this a drive-by new test and fix?

Comment (weswigham) [reply tests/baselines/reference/printerApi/printsNodeCorrectly.newExpressionOnConditionalExpression.js]: Ah, yes:
>  Fix weird case with un-parenthesized new expressions

File: src/compiler/checker.ts (hunk 3 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: https://github.com/Microsoft/TypeScript/issues/18863

File: src/compiler/transformers/es2015.ts (hunk 6 above)
Comment (DanielRosenwasser) [reply src/compiler/transformers/es2015.ts]: Spoke with Wesley; apparently Uglify can do a better job on the following thanks to ternary/comma precedence rules:

```ts
function __makeTemplateObject(cooked, raw) {
    if (Object.defineProperty) {
        Object.defineProperty(cooked, "raw", { value: raw });
    }
    else {
        cooked.raw = raw;
    }
    return cooked;
};
```

File: src/compiler/types.ts [hunk 10]
```diff
@@ -4217,22 +4217,23 @@ namespace ts {
...
-        Generator = 1 << 7,         // __generator (used by ES2015 generator transformation)
-        Values = 1 << 8,            // __values (used by ES2015 for..of and yield* transformations)
-        Read = 1 << 9,              // __read (used by ES2015 iterator destructuring transformation)
-        Spread = 1 << 10,           // __spread (used by ES2015 array spread and argument list spread transformations)
-        Await = 1 << 11,            // __await (used by ES2017 async generator transformation)
-        AsyncGenerator = 1 << 12,   // __asyncGenerator (used by ES2017 async generator transformation)
-        AsyncDelegator = 1 << 13,   // __asyncDelegator (used by ES2017 async generator yield* transformation)
-        AsyncValues = 1 << 14,      // __asyncValues (used by ES2017 for..await..of transformation)
-        ExportStar = 1 << 15,       // __exportStar (used by CommonJS/AMD/UMD module transformation)
+        Extends = 1 << 0,               // __extends (used by the ES2015 class transformation)
```
[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/compiler/types.ts]: :(

File: src/compiler/checker.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: Should be fixed.

**Comment by rbuckton** [comment]
I won't have time to look at this until Monday, but be aware that there was a Needs Consensus PR regarding [template literal cache lifetime](https://github.com/tc39/ecma262/pull/890) last week that reached consensus. I don't know yet whether this affects this change.

**Comment by DanielRosenwasser** [comment]
@rbuckton within a module, this PR reflects those semantics. At the global scope, we continue to do the same thing as we've always done until we have a better mechanism.

File: src/compiler/types.ts (hunk 7 above)
Comment (rbuckton) [reply src/compiler/types.ts]: Agreed. 👎 for the magic string in the enum.

File: src/compiler/transformers/es2015.ts [hunk 11]
```diff
@@ -4052,4 +4085,21 @@ namespace ts {
                 };
             })();`
     };
+
+    const templateObjectHelper: EmitHelper = {
+        name: "typescript:makeTemplateObject",
+        scoped: false,
+        priority: 0,
+        text: `
+            var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
```
Comment (rbuckton) [inline src/compiler/transformers/es2015.ts]: What about:
```js
cooked.raw = raw;
if (Object.freeze) Object.freeze(cooked);
return cooked;
```

Or, the one-line alternative:
```js
return Object.defineProperty ? Object.defineProperty(cooked, "raw", { value: raw }) : (cooked.raw = raw, cooked);
```

File: src/compiler/checker.ts (hunk 3 above)
Comment (rbuckton) [inline src/compiler/checker.ts]: Would it be worth considering a shorter name than `__makeTemplateObject`?

Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: @rbuckton Babel uses `_taggedTemplateLiteral` which is two characters longer. If you can think of something by Monday afternoon before I merge this in, I will consider it 😄

File: src/compiler/transformers/es2015.ts (hunk 11 above)
Comment (DanielRosenwasser) [reply src/compiler/transformers/es2015.ts]: Uglify already produces a shorter output given this current implementation.

Comment (weswigham) [reply src/compiler/transformers/es2015.ts]: _Slightly_ better one-liner (two less characters, just as readable and correct):
```ts
return Object.defineProperty ? Object.defineProperty(cooked, "raw", { value: raw }) : cooked.raw = raw, cooked;
```
Which is, coincidentally, how uglify restructures what daniel has right now when it minifies it.

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts]: `__template`? (I like this since it doesn't have any camel-casing)
`__templatize`?
`__intoTemplate`?
`__addRaw`?
`__createTemplateArg`? (not _really_ shorter, I know)
