### PR TITLE
Constructor function methods:Add two missing tag lookups

### LINKED ISSUE #46618: Failing to resolve multiple JSDOC @template tags
# Bug Report

Using generics on both an ES5 class and methods results in incomplete type resolution.

### 🔎 Search Terms
jsdoc, template, generic

### 🕗 Version & Regression Information
Typescript 4.4.4, 4.5.0-beta
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSDoc/generics/templates

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta&filetype=js#code/FAegVGwARlACAXApgWwA4BsCGyoG8BnBAJwEsA7AcwF8oAVaWONLYrFfO2hRkYAMwCu5AMYJSAe3JQAwhgIAKBAEp80KBoQALUgQB0CKAF4oCANzBqwUBEbxk6bLkIkKNKADU7zVu07cobxY2DjwPWgA3QJg+OX00YgkEJIBPNCQ9IVEARmMoLLFJaSUAGigI1TxLC2s4vQSk1PTM4REAJmN1DXBIDT6mB0wcJHwiMipaLz6NJmC-PC5TaOnZ31Dw8uX+vmmC8SkoUvLKrqhqGojWKBE88iQAd1l5BQByLBflCxEWnNf3speACMPmYoCAQDIsOQXoZiEgCBIMBERh4oJQkHcyCJgN8Cm0-i8AcDPmCIVCYfQ0RikFioBQoKxKIIUBieEA)

### 💻 Code

```ts

/**
 * @template {string} T
 * @param {T} t
 */
function Cls(t) {
    this.t = t;
}

/**
 * @template {string} V
 * @param {T} t 
 * @param {V} v 
 */
Cls.prototype.func1 = function (t, v) {
};


Cls.prototype.func2 =
    /**
     * @template {string} V
     * @param {T} t 
     * @param {V} v 
     */
    function (t, v) {
    };

var c = new Cls('a');
c.func1('a', 'b'); //Can't resolve V generic
c.func2('a', 'b'); //Can't T generic in argument

```

### 🙁 Actual behavior

Unable to resolve type for all generics defined in the JSDOC
### 🙂 Expected behavior

All generics should resolve to actual types.

### PR DESCRIPTION
**Pull request by sandersn**
1. During name resolution, `@param` and `@return` tags should walk up through the jsdoc comment and then jump to the host function. Previously they did not, which would cause them to not resolve type parameters bound in the scope of a host that was not a sibling of the comment. The example from #46618 is a prototype method:

```js
/**
 * @template {T}
 * @param {T} t
 */
C.prototype.m = function (t) {
}
```

2. During name resolution, prototype methods are supposed to resolve types both from the host function's location and from the containing class' location. The containing class lookup happens in a separate call to `resolveName`. Previously, the code that finds the containing class only worked for the above style of comment, which is on the outer ExpressionStatement, but not for the below style, which is on the function expression itself:

```js
C.prototype.m =
  /**
   * @template {T}
   * @param {T} t
   */
  function (t) {
}
```

Fixes #46618

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3374,16 +3376,20 @@ namespace ts {
                 return;
             }
             const host = getJSDocHost(node);
-            if (host &&
-                isExpressionStatement(host) &&
-                isBinaryExpression(host.expression) &&
-                getAssignmentDeclarationKind(host.expression) === AssignmentDeclarationKind.PrototypeProperty) {
-                // X.prototype.m = /** @param {K} p */ function () { } <-- look for K on X's declaration
```
Comment (sandersn) [inline src/compiler/checker.ts:3381]: This comment was wrong before. The *new* code implements this.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3374,16 +3376,20 @@ namespace ts {
...
+            if (host && isExpressionStatement(host) && isPrototypePropertyAssignment(host.expression)) {
+                // /** @param {K} p */ X.prototype.m = function () { } <-- look for K on X's declaration
                 const symbol = getSymbolOfNode(host.expression.left);
                 if (symbol) {
                     return getDeclarationOfJSPrototypeContainer(symbol);
                 }
             }
+            if (host && isFunctionExpression(host) && isPrototypePropertyAssignment(host.parent) && isExpressionStatement(host.parent.parent)) {
+                // X.prototype.m = /** @param {K} p */ function () { } <-- look for K on X's declaration
```
Comment (gabritto) [inline src/compiler/checker.ts:3387]: not sure if this is something we have to worry about here in this function, but what happens if we have conflicting tags with the same name in the top-level and nested scopes?

**Review by gabritto — APPROVED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:3387]: The nearest tag to the parameter, the one on the function expression, resolves first. You can also put a `@type` on the parameter itself, and that resolves before any `@param` tag.

Conflicting tags in the same comment should resolve to the first tag.
