### PR TITLE
feat(37409): Fixing `>` character in JSX text should have a "fix all in file"

### LINKED ISSUE #37409: Fixing `>` character in JSX text should have a "fix all in file"
We introduced a breaking change in #36636 so that `>` in JSX text would become an error as per the JSX spec:

```
Unexpected token. Did you mean `{'>'}` or `&gt;`?
```

I hit this several times on the new website's `src/templates/pages/download.tsx` even though the code was just working. Users shouldn't have to fix them one-by-one, so it'd probably be a good idea to auto-fix them all.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37409

### CODE REVIEW

File: src/services/codeFixProvider.ts [hunk 1]
```diff
@@ -90,6 +90,10 @@ namespace ts.codefix {
     }
 
     function getDiagnostics({ program, sourceFile, cancellationToken }: CodeFixContextBase) {
-        return program.getSemanticDiagnostics(sourceFile, cancellationToken).concat(computeSuggestionDiagnostics(sourceFile, program, cancellationToken));
+        return [
+            ...program.getSemanticDiagnostics(sourceFile, cancellationToken),
+            ...program.getSyntacticDiagnostics(sourceFile, cancellationToken),
```
Comment (andrewbranch) [inline src/services/codeFixProvider.ts]: Huh, I guess we’ve never offered code fixes for syntactic errors before.
