### PR TITLE
[Experiment] Some tweaking to handle project references for auto import

### LINKED ISSUE #55879: Auto import suggestion across referenced composite projects
Type: <b>Bug</b>

I am trying to make auto-import suggestions to work when using composite projects via typescripts tsconfig. I've set up a small repo where my issue can be reproduced.

Here is the repo: https://github.com/ekr3peeK/vscode-autoimport-bug

**What is happening**
When trying to use `TestClass` in a file inside `projectA`, I get no auto-import suggestions for the class. Auto-import suggestions work for files from which there was something manually imported at least once inside `projectA`.

**What I am expecting**
I am expecting that if `projectA` is referencing `projectB` via `tsconfig.json`, I should receive auto import suggestion for things exported from `projectB`, even if no file was added beforehand.

If I add the folder of `projectB` to the `includes` inside `projectA/tsconfig.json` auto-import suggestions work, but the projects are not buildable anymore.

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-1160.90.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.90.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8300 Eight-Core Processor            (8 x 3315)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.97GB (0.91GB free)|
|Process Argv|--crash-reporter-id 8cc944fc-3735-4ff7-8e33-3469996bd4a8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: adam.blue.foxgray.com|
|OS|Linux x64 3.10.0-1160.90.1.el7.x86_64|
|CPUs|AMD FX(tm)-6100 Six-Core Processor (6 x 1400)|
|Memory (System)|7.60GB (4.85GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: adam.blue.foxgray.com|
|OS|Linux x64 3.10.0-1160.90.1.el7.x86_64|
|CPUs|AMD FX(tm)-6100 Six-Core Processor (6 x 1400)|
|Memory (System)|7.60GB (4.85GB free)|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
LogFileHighlighter|emi|2.16.0
mysql-syntax|jak|1.3.1
vscode-peacock|joh|4.2.2
theme-karyfoundation-themes|kar|34.3.0
remote-ssh|ms-|0.106.4
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vscode-intelephense-client|bme|1.9.5
vscode-php-getters-setters-cv|cve|1.6.1
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
gitlens|eam|14.3.0
vscode-mysql|for|0.4.1
gitlab-workflow|Git|3.78.0
vscode-test-explorer|hbe|2.21.1
path-autocomplete|ion|1.25.0
rainbow-csv|mec|3.7.1
vscode-html-format|moh|0.1.2
vscode-scss|mrm|0.10.0
test-adapter-converter|ms-|0.1.8
vsliveshare|ms-|1.0.5883
vscode-jest|Ort|5.2.3
vscode-xml|red|0.26.1
gitblame|wad|10.5.1
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

### PR DESCRIPTION
**Pull request by sheetalkamat**
- Add directly referenced project's root files to the auto import provider if "paths" are setup in options which kind of indicates willingness to use module resolution
- Allow auto import if paths is present in options or symlink cache has any symlinks discovered (as part of say calculating auto import root names)

Fixes #55879

### CODE REVIEW

**Comment by sheetalkamat** [comment]
May be we also need some tweaking if referenced project was discovered while `node_modules` were detected and we ignored everything but entry point.

**Comment by sheetalkamat** [comment]
We also could get info from opened referenced project instead of adding to auto import provider but I wanted to first check if we want something like this which understands referenced project or not before adding anything more to this experiment

**Comment by andrewbranch** [comment]
> We also could get info from opened referenced project instead of adding to auto import provider

This was the approach I took in https://github.com/microsoft/TypeScript/pull/47690 which ended up being problematic for the export info and module specifier caches. I forgot about this distinction when we talked the other day. I think using the `AutoImportProvider` is slightly less efficient but avoids these caching pitfalls, and is overall a more promising approach. I spent a little while trying to break the export info cache invalidation on this branch and it looked good. That said, `exportMapCache.ts` and `moduleSpecifierCache.ts` could be updated to exercise this new functionality.

**Comment by sheetalkamat** [comment]
@andrewbranch ready for review

File: src/server/project.ts [hunk 1]
```diff
@@ -2504,16 +2506,29 @@ export class AutoImportProviderProject extends Project {
...
+                    dependenciesAdded += addRootNames(entrypoints);
                 }
             }
         }
 
-        if (rootNames?.length) {
-            hostProject.log(`AutoImportProviderProject: found ${rootNames.length} root files in ${dependenciesAdded} dependencies in ${timestamp() - start} ms`);
+        const references = program.getResolvedProjectReferences();
+        let referencesAddded = 0;
+        if (references?.length && program.getCompilerOptions().paths) {
```
Comment (andrewbranch) [inline src/server/project.ts:2516]: What’s the reason for blocking this on `paths`?

Comment (andrewbranch) [reply src/server/project.ts:2516]: `shouldOfferImportCompletions` is ~~pretty sus tbh~~ something I’ve considered deleting in favor of just relying on the user preference to disable auto-imports. I was just thinking of examples like our own codebase, where we have project references set up, but reference into them with relative paths rather than `paths` aliases or node_modules symlinks.

Comment (sheetalkamat) [reply src/server/project.ts:2516]: Then should I test emit module kind is not none ? Is that better ? We do need to check if project is modules or not right

Comment (andrewbranch) [reply src/server/project.ts:2516]: `--module none` is basically meaningless; see https://github.com/microsoft/TypeScript/issues/39603 and https://github.com/microsoft/TypeScript/issues/55256#issuecomment-1706823298

IMO disabling auto-imports for the project via settings is the way to go.

Comment (sheetalkamat) [reply src/server/project.ts:2516]: But currently there is no such setting.. i would prefer not to merge these two things. Do i create this unconditionally for now and when we have disable auto import preference we could add it ?

Comment (andrewbranch) [reply src/server/project.ts:2516]: This is what I’m referring to. Does this control only VS Code’s behavior?

image

Comment (sheetalkamat) [reply src/server/project.ts:2516]: i dont see anything changing in tsserver log by enabling or disabling this. Not sure. Is this same as `includePackageJsonAutoImports` ? if that is it we can include by default since we have already figured out we need to create auto import provider

Comment (sheetalkamat) [reply src/server/project.ts:2516]: Yeah but right now vscode doesnt send this as part of their initial configure. Its only in completions request..

Here is what vscode sends:
```
{
      "seq": 0,
      "type": "request",
      "command": "configure",
      "arguments": {
        "hostInfo": "vscode",
        "preferences": {
          "providePrefixAndSuffixTextForRename": true,
          "allowRenameOfImportPath": true,
          "includePackageJsonAutoImports": "auto",
          "excludeLibrarySymbolsInNavTo": true
        },
        "watchOptions": {}
      }
    }
```

Comment (andrewbranch) [reply src/server/project.ts:2516]: I would propose we check that UserPreference anyway as the condition here (other clients might send it?) and then update VS Code to start sending it in Configure. We can discuss that next week at the editor sync.

**Review by andrewbranch — APPROVED** [review]

**Comment by sheetalkamat** [comment]
@andrewbranch i had missed the editor services to update to check for same flag when i first pushed commit .. didn’t realize you already looked at it or I would I have made separate commit .. i will also add a test when that option is not set in host preferences just for completeness when I get to desk

**Comment by joeuy** [comment]
@sheetalkamat @andrewbranch I am having the problem that autoimport is not working for project references. 

Example: project A -> project B
however inside project A autoimport is not finding dependencies inside project B. 

Can you point me to some reference /explain how to get this to work?

**Comment by andrewbranch** [comment]
@joeuy please file a new issue with full repro steps. Thanks!
