### PR TITLE
fix: avoid downleveled dynamic import closing over specifier expression

### LINKED ISSUE #48285: dynamic import closes over the module specifier argument
# Bug Report

Dynamic import JSON compiled into js code with closures. What does not look like what was expected. 

### 🔎 Search Terms

Dynamic import JSON

### 🕗 Version & Regression Information

TypeScript Version 4.6.2
- I was unable to test this on prior versions because I think there is the same 

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "strict": true,
    "newLine": "LF",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "esModuleInterop": true
  }
}
```

### 💻 Code

1.json
```json
[1]
```

2.json
```json
[2]
```

import_test.ts
```ts
function load() {
  let fileName = '1';
  const promises = [import(`./${fileName}.json`)];
  fileName = '2';
  promises.push(import(`./${fileName}.json`));
  
  Promise.all(promises).then(results => console.log(results));
}

load();
```

Compiled js
```javascript
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
function load() {
    let fileName = '1';
    const promises = [Promise.resolve().then(() => __importStar(require(`./${fileName}.json`)))];
    fileName = '2';
    promises.push(Promise.resolve().then(() => __importStar(require(`./${fileName}.json`))));
    Promise.all(promises).then(results => console.log(results));
}
load();
```

### 🙁 Actual behavior

```
0 { '0': [Getter], default: [ 2 ] }
1 { '0': [Getter], default: [ 2 ] }
```

### 🙂 Expected behavior

```
0 { '0': [Getter], default: [ 1 ] }
1 { '0': [Getter], default: [ 2 ] }
```

### LINKED ISSUE #49652: Missing `async` keyword when using `import()` while outputting CommonJS modules
# Bug Report

### 🔎 Search Terms

missing, await, async, commonjs, import, dynamic import, syntax error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the dynamic import function
- TypeScript versions: `next`, `4.7.4`, `4.6.4`, `3.9.19`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?declaration=false&target=99&jsx=0&module=1&ssl=12&ssc=1&pln=1&pc=1#code/MYewdgzgLgBA5gUygBQIZQBYwLw1RATzGBgAoBKHAPhgG8AoASAHoAqGASzBgCcFUANhygEYmDhBgB3EAFcBAExgKQMCCAC2CPIWIwAYgGUYIAA4Ie6DuAA0JnnmkIARrwQBHWQmgxWzJnxQsjzcAETMPCAgUMwaBMygIALMpugYoQDc9AC+WfSgkLDqWvqyxFDW3Lj4RCQU1HRMBT58EPKw1VKowpwapiA8UKSoXT2IKGkU5FmMzUkIAHQCIHCkre3TOXnFCKXllRRZQA)

### 💻 Code

```ts
const getPath = async () => {
	/* in reality this would do some async FS operation, or a web request */
	return "/root/my/cool/path";
};

const someFunction = async () => {
	const result = await import(await getPath());
	console.log(result);
};

someFunction();
```

Generated JavaScript:
```js
const getPath = async () => {
    /* in reality this would do some async FS operation, or a web request */
    return "/root/my/cool/path";
};
const someFunction = async () => {
    const result = await Promise.resolve().then(() => require(await getPath()));
    console.log(result);
};
someFunction();
```

The issue also occurs when both functions are exported:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.someFunction = exports.getPath = void 0;
const getPath = async () => {
    /* in reality this would do some async FS operation, or a web request */
    return "/root/my/cool/path";
};
exports.getPath = getPath;
const someFunction = async () => {
    const result = await Promise.resolve().then(() => require(await (0, exports.getPath)()));
    console.log(result);
};
exports.someFunction = someFunction;
(0, exports.someFunction)();
```

### 🙁 Actual behavior

`tsc` emits code without the `await` keyword, causing a SyntaxError at runtime:

```js
const result = await Promise.resolve().then(() => require(await getPath()));
```

```
/Users/xxx/Projects/testing/test-ts/src/index.js:6
    const result = await Promise.resolve().then(() => require(await getPath()));
                                                              ^^^^^
SyntaxError: missing ) after argument list
```

### 🙂 Expected behavior

`tsc` emits code with an `await` included before the promise callback definition:
```js
const result = await Promise.resolve().then(async () => require(await getPath()));
```
Or an equivalent promise chain:
```js
const result = getPath().then((path) => require(path));
```

### PR DESCRIPTION
**Pull request by Josh-Cena**
Fixes #49652 
Fixes #48285

### CODE REVIEW

File: src/compiler/transformers/module/module.ts [hunk 1]
```diff
@@ -837,7 +847,11 @@ namespace ts {
                 func = factory.createArrowFunction(
                     /*modifiers*/ undefined,
                     /*typeParameters*/ undefined,
-                    /*parameters*/ [],
+                    /*parameters*/ isStringLiteralSpecifier || !arg ? [] : [factory.createParameterDeclaration(
+                        /*modifiers*/ undefined,
+                        /*dotDotDotToken*/ undefined,
+                        "c",
+                    )],
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts:854]: This won't be needed if you use the suggestion above.

File: src/compiler/transformers/module/module.ts [hunk 2]
```diff
@@ -848,16 +862,15 @@ namespace ts {
                     /*asteriskToken*/ undefined,
                     /*name*/ undefined,
                     /*typeParameters*/ undefined,
-                    /*parameters*/ [],
+                    /*parameters*/ isStringLiteralSpecifier ? [] : [factory.createParameterDeclaration(
+                        /*modifiers*/ undefined,
+                        /*dotDotDotToken*/ undefined,
+                        "c",
+                    )],
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts:869]: This won't be needed if you use the suggestion above.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/compiler/transformers/module/module.ts [hunk 3]
```diff
@@ -820,14 +820,24 @@ namespace ts {
...
+            // import(x)
             // emit as
-            // Promise.resolve().then(function () { return require(x); }) /*CommonJs Require*/
+            // Promise.resolve(x).then(c => require(c)) /*CommonJs Require*/
             // We have to wrap require in then callback so that require is done in asynchronously
             // if we simply do require in resolve callback in Promise constructor. We will execute the loading immediately
-            const promiseResolveCall = factory.createCallExpression(factory.createPropertyAccessExpression(factory.createIdentifier("Promise"), "resolve"), /*typeArguments*/ undefined, /*argumentsArray*/ []);
-            let requireCall: Expression = factory.createCallExpression(factory.createIdentifier("require"), /*typeArguments*/ undefined, arg ? [arg] : []);
+            // For import("StringLiteral"), we prefer to emit require("StringLiteral") so that bundlers can analyze this.
+            const isStringLiteralSpecifier = arg?.kind === SyntaxKind.StringLiteral;
```
[the remark this answers is not in the document]
Comment (Josh-Cena) [reply src/compiler/transformers/module/module.ts:830]: I thought about it—didn't think of strong arguments for anything other than string literals (and possibly string-literal-like) since they aren't statically analyzable anyway (and importing number literals seems weird). ``import(`./data/${foo}.json`)`` is also statically analyzable, but we don't have a helper for that😅

**Comment by Josh-Cena** [comment]
I realized Babel is transpiling it to ``Promise.resolve(`${arg}`).then(c => require(c))`` where the template literal forces synchronous evaluation. This avoids the creation of the temp variable. I wonder—for the purpose of <ES6 emit—if there's any problem if we use `String()`.

**Comment by rbuckton** [comment]
> I realized Babel is transpiling it to `` Promise.resolve(`${arg}`).then(c => require(c)) `` where the template literal forces synchronous evaluation. This avoids the creation of the temp variable. I wonder—for the purpose of <ES6 emit—if there's any problem if we use `String()`.

Is there a reason to do that over what you're already doing in this PR? I'm not so concerned about the temp variable in this case.

**Comment by Josh-Cena** [comment]
No—no _adverse_ effects that I can think of (apart from some micro-optimizations, maybe?) If you think they both work I'll stay with the current solution.

File: src/compiler/transformers/module/module.ts [hunk 4]
```diff
@@ -851,16 +862,13 @@ namespace ts {
...
                     factory.createBlock([factory.createReturnStatement(requireCall)]));
-
-                // if there is a lexical 'this' in the import call arguments, ensure we indicate
-                // that this new function expression indicates it captures 'this' so that the
-                // es2015 transformer will properly substitute 'this' with '_this'.
-                if (containsLexicalThis) {
-                    setEmitFlags(func, EmitFlags.CapturesThis);
-                }
+                // Note: because non-literal expressions are already evaluated
+                // synchronously, we don't need to capture `this`.
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts:866]:
```suggestion
```

The comment is not necessary.

File: tests/baselines/reference/dynamicImportWithNestedThis_es2015.js [hunk 5]
```diff
@@ -29,8 +29,8 @@ c.dynamic();
             this._path = './other';
         }
         dynamic() {
-            var _a;
-            return _a = this._path, __syncRequire ? Promise.resolve().then(() => require(_a)) : new Promise((resolve_1, reject_1) => { require([_a], resolve_1, reject_1); });
+            var _a, _b;
+            return _a = this._path, __syncRequire ? (_b = _a, Promise.resolve().then(() => require(_b))) : new Promise((resolve_1, reject_1) => { require([_a], resolve_1, reject_1); });
```
Comment (rbuckton) [inline tests/baselines/reference/dynamicImportWithNestedThis_es2015.js:33]: The additional aliasing here is unnecessary.

File: tests/baselines/reference/importCallExpressionInUMD5.js [hunk 6]
```diff
@@ -51,9 +51,9 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, ge
     // https://github.com/microsoft/TypeScript/issues/36780
     function func() {
         return __awaiter(this, void 0, void 0, function* () {
-            var _a;
+            var _a, _b;
             const packageName = '.';
-            const packageJson = yield (_a = packageName + '/package.json', __syncRequire ? Promise.resolve().then(() => require(_a)) : new Promise((resolve_1, reject_1) => { require([_a], resolve_1, reject_1); }));
+            const packageJson = yield (_a = packageName + '/package.json', __syncRequire ? (_b = _a, Promise.resolve().then(() => require(_b))) : new Promise((resolve_1, reject_1) => { require([_a], resolve_1, reject_1); }));
```
Comment (rbuckton) [inline tests/baselines/reference/importCallExpressionInUMD5.js:56]: The additional aliasing here is unnecessary.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: tests/baselines/reference/dynamicImportWithNestedThis_es2015.js (hunk 5 above)
Comment (Josh-Cena) [reply tests/baselines/reference/dynamicImportWithNestedThis_es2015.js:33]: You're correct. However I'm not sure if it's possible to be fixed on a generic level, since the temp variable created from the UMD transformer may be mutated. I've committed the new baseline, but there are some places where it looks suspicious. I can't really read the output to tell if it's unsafe, so I'll appreciate if you can help to review here.

File: tests/baselines/reference/importCallExpressionGrammarError.js [hunk 7]
```diff
@@ -10,8 +10,9 @@ const p2 = import();
 const p4 = import("pathToModule", "secondModule");
 
 //// [importCallExpressionGrammarError.js]
+var _a, _b;
 var a = ["./0"];
-Promise.resolve().then(() => require(...["PathModule"]));
-var p1 = Promise.resolve().then(() => require(...a));
+_a = (...["PathModule"]), Promise.resolve().then(() => require(_a));
+var p1 = (_b = (...a), Promise.resolve().then(() => require(_b)));
```
Comment (Josh-Cena) [inline tests/baselines/reference/importCallExpressionGrammarError.js:16]: This is invalid grammar, but the input is invalid grammar as well. I assume we can safely treat it as garbage in, garbage out?

**Review by rbuckton — APPROVED** [review]
