### PR TITLE
Fix 'as const'-like behavior in JSDoc type cast

### LINKED ISSUE #30445: const assertions in JSDoc
## Search Terms

const jsdoc

## Suggestion

v3.4 added support for `as const` to mark a literal expression as immutable and disable type widening. This feature uses the TypeScript type assertion syntax `{} as const` or `<const>{}`.

In JS files you can use JSDoc to do type assertions: `/** @type {T} */(v)`
Unfortunately that doesn't work with const assertions.

```js
// @ts-check
const foo = /** @type {const} */([1]); // Error: cannot find name 'const'
```

This proposes adding support for `/** @type {const} */([1])`.

An alternative could be `/** @const */([1])`.

## Use Cases

The same as for const assertions in TS files.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### LINKED ISSUE #45463: JSDoc Type cast to `const` does not work in variable-like initializers
# Bug Report

### 🔎 Search Terms

jsdoc cast as const

### 🕗 Version & Regression Information

- We have half-supported `as const` in JSDoc since it was added to TypeScript (~v3.5)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&filetype=js#code/PTAEAEGMAsFNINYCkDOAuUAXATgV1gLABQIEAhgDYUD2A7qhjvsaeCjgJaSaN6FEVYmUAA9QAXlDAAVNIiYAngAdYoAN6RqAO3YBfUNOAAKAIwBKANzERVosUHCFthRKmz5y1Ru16Dx88629kKgAF6uRjJy4Ioq6po6mPqGpmaWxKEWQA)

### 💻 Code

```ts
// @checkJs: true
// @allowJs: true
// @strict: true

let x = /** @type {const} */(1); // error: cannot find name 'const'
x; // any

let y;
y = /** @type {const} */(1); // works
y; // 1

let z = (/** @type {const} */(1)); works
z; // 1
```

### 🙁 Actual behavior

In a JavaScript file, using a `/** @type {const} */( expr )` cast in the *initializer* of any variable-like declaration reports a "Cannot find name 'const'" error:
- VariableDeclaration
- PropertyDeclaration
- PropertyAssignment
- BindingElement
- ParameterDeclaration

In any other position, the cast correctly behaves like a TypeScript `as const` assertion.

### 🙂 Expected behavior

In a JavaScript file, using a `/** @type {const} */( expr )` cast should behave like TypeScript's `as const` in any position, not just random arguments.

### Workaround:

While `let x = /** @type {const} */({a: 1})` does not work, `let x = (/** @type {const} */({a: 1}))` does. This is because our logic to get the effective type annotation node for a variable-like declaration treats the type cast in the initializer as part of the declaration.

### PR DESCRIPTION
**Pull request by rbuckton**
We *almost* support `as const` like casts in JavaScript files, but end up reporting errors because we either pick up the `/** @type {} */` from the parenthesized expression when looking for effective type nodes, or by not handling it at all for contextual types. This fixes both scenarios.

Fixes #45463
Fixes #30445

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -25858,7 +25858,9 @@ namespace ts {
                 case SyntaxKind.ParenthesizedExpression: {
                     // Like in `checkParenthesizedExpression`, an `/** @type {xyz} */` comment before a parenthesized expression acts as a type cast.
                     const tag = isInJSFile(parent) ? getJSDocTypeTag(parent) : undefined;
-                    return tag ? getTypeFromTypeNode(tag.typeExpression.type) : getContextualType(parent as ParenthesizedExpression, contextFlags);
+                    return !tag ? getContextualType(parent as ParenthesizedExpression, contextFlags) :
```
Comment (rbuckton) [inline src/compiler/checker.ts:25861]: I inverted the order here so that we have one condition per branch (i.e., `!a ? x : b ? y : z`) instead of nested conditions (i.e., `a ? b ? y : x : z`).

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -2656,6 +2656,26 @@ namespace ts {
         return result || emptyArray;
     }
 
+    function filterOwnedJSDocTags(hostNode: Node, jsDoc: JSDoc | JSDocTag) {
+        if (isJSDoc(jsDoc)) {
+            const ownedTags = filter(jsDoc.tags, tag => ownsJSDocTag(hostNode, tag));
+            return jsDoc.tags === ownedTags ? [jsDoc] : ownedTags;
```
Comment (sandersn) [inline src/compiler/utilities.ts:2662]: why isn't the true branch `ownedTags` too?

File: tests/baselines/reference/importTypeInJSDoc.types [hunk 3]
```diff
@@ -37,14 +37,14 @@ export = MyClass;
  */
 
 let a = /** @type {Foo} */(/** @type {*} */(undefined)); 
->a : import("tests/cases/conformance/types/import/externs")
+>a : any
```
Comment (weswigham) [inline tests/baselines/reference/importTypeInJSDoc.types:40]: ? There's a typedef for `Foo` right above this - so why is it `any` now?

File: tests/baselines/reference/jsdocTypeTagCast.types [hunk 4]
```diff
@@ -209,4 +209,18 @@ if(/** @type {numOrStr is string} */(numOrStr === undefined)) { // Error
 }
 
 
+var asConst1 = /** @type {const} */(1);
+>asConst1 : 1
+>(1) : 1
+>1 : 1
 
+var asConst2 = /** @type {const} */({
+>asConst2 : { x: number; }
```
Comment (weswigham) [inline tests/baselines/reference/jsdocTypeTagCast.types:218]: This isn't the expected `as const` result of this expression? It should be `{readonly x: 1}`.

**Review by weswigham — COMMENTED** [review]
Conceptually this looks OK, except for the odd baseline changes. But I could swear we discussed weather we should support `const` casts in JS back when we first added `const` casts, and the original answer was "no" (meaning the fix would have been properly parsing `const` as a type reference/erroring on the keyword if we wanted to stick with that).

File: tests/baselines/reference/importTypeInJSDoc.types [hunk 5]
```diff
@@ -37,14 +37,14 @@ export = MyClass;
  */
 
 let a = /** @type {Foo} */(/** @type {*} */(undefined));
```
Comment (sandersn) [inline tests/baselines/reference/importTypeInJSDoc.types:39]: This seems to contradict the intention of this test, which I think was to translate `let a = undefined as any as Foo` to JS. If there's a new way to translate this, I think it's fine to change the source, but I don't think the type of `a` should change.

File: tests/baselines/reference/jsdocTypeTagCast.types [hunk 6]
```diff
@@ -209,4 +209,18 @@ if(/** @type {numOrStr is string} */(numOrStr === undefined)) { // Error
...
 
+var asConst1 = /** @type {const} */(1);
+>asConst1 : 1
+>(1) : 1
+>1 : 1
 
+var asConst2 = /** @type {const} */({
+>asConst2 : { x: number; }
+>({    x: 1}) : { x: number; }
+>{    x: 1} : { x: number; }
```
Comment (sandersn) [inline tests/baselines/reference/jsdocTypeTagCast.types:220]: This should be `{ readonly x: 1 }` if it's the equivalent of `var asConst2 = { x: 1 } as const`, right?

**Review by sandersn — CHANGES_REQUESTED** [review]
Couple of things in the tests need to be changed, plus I didn't understand one branch of filterOwnedJSDocTags

File: src/compiler/utilities.ts (hunk 2 above)
Comment (rbuckton) [reply src/compiler/utilities.ts:2662]: `ts.filter` returns the same array if all elements are included. If `ownedTags` is the same array as `jsDoc.tags`, then we just return `jsDoc` (since that's what we included in the result before this). Otherwise, we return the filtered list of tags.

This may be overkill, but the reason why we return both `JSDoc` and `JSDocTag` entries isn't clear so I felt safer returning the original node if no filtering occurred.

File: tests/baselines/reference/importTypeInJSDoc.types (hunk 3 above)
Comment (rbuckton) [reply tests/baselines/reference/importTypeInJSDoc.types:40]: Previously we were incorrectly treating `/** @type {Foo} */` as a type annotation for the `let a` rather than as a cast. Now it looks like `getTypeForVariableLikeDeclaration` doesn't get a type from `tryGetTypeFromEffectiveTypeNode` (which it shouldn't), but then escapes early returning `autoType` because `isNullOrUndefined` skips parentheses (ignoring type casts). Quickinfo shows `any` at the declaration site, but shows the correct type in any position immediately afterwards.

I can augment `isNullOrUndefined` to check whether any of the parenthesis are JSDoc type casts.

File: tests/baselines/reference/jsdocTypeTagCast.types (hunk 4 above)
Comment (rbuckton) [reply tests/baselines/reference/jsdocTypeTagCast.types:218]: Yeah, it looks like I missed a required change to `isConstContext`, will update shortly.

File: tests/baselines/reference/importTypeInJSDoc.types (hunk 3 above)
Comment (weswigham) [reply tests/baselines/reference/importTypeInJSDoc.types:40]: Yeah, that's sounds right. I image we probably shouldn't ignore casts.

**Review by sandersn — APPROVED** [review]

**Review by orta — APPROVED** [review]
Love it, thanks - I'll get this added to the JSDoc reference when it's in 👍🏻

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by orta** [comment]
As this is definitely going to get asked in the future, is it possible for both of these to work?

```ts
const isConst = /** @type {const} */ ({
    hello: "world, not string"
})

isConst
// ^? - { readonly hello: "world, not string" }

const isString = /** @type {const} */ {
    hello: "world, not string"
}

isString
// ^? - { hello: string }
```

**Comment by sandersn** [comment]
Probably yes -- but it's an expansion of the Clojure cast syntax that no other tool would recognise, so we should really consider the entire design space if we decide to make casts easier to write.

**Comment by rbuckton** [comment]
The parens are also useful for performance reasons, otherwise we'd have to check every leading JSDoc comment of every expression in a JS file.

What I'd like is a shorter cast syntax (even with the parens). Something like `/** {type} */(expr)` (removing the `@type`). I know we allow you to write `/** @type type */(expr)` (dropping the `{}`), but that still feels awkward.

I'd also like a way to emulate postfix-`!` in JSDoc, because the only options currently are a cast (which could be difficult to write from an inferred type), or a generic identity function that removes `null | undefined`. Not sure what a good jsdoc syntax might be for that though, since there really isn't precedent in Clojure or jsdoc.app. 

Something like one of these:

```js
/** @type {!} */(foo.bar).baz; // just the `!` prefix
/** @notnull */(foo.bar).baz; // a keyword-like tag
/** @! */(foo.bar).baz; // or some type of shorthand
/** {!} */(foo.bar).baz;
```

I'll have to see if there's an open issue for this and, if not, create one.

**Comment by rbuckton** [comment]
@typescript-bot test this
@typescript-bot user test this

Checking rwc and community tests, though I don't think this should affect anything currently.

**Comment by rbuckton** [comment]
user test baselines are fine (changes are minor and unrelated)

**Comment by rbuckton** [comment]
rwc baselines look fine.

**Comment by sandersn** [comment]
I like `/** @! */(e)` quite a bit.

**Comment by mohd-akram** [comment]
Any idea on when this will be available in TypeScript? It's very useful and hopefully could be released soon.

**Comment by orta** [comment]
TypeScript has a set release schedule, the next release details are here: https://github.com/microsoft/TypeScript/issues/45418

**Comment by mohd-akram** [comment]
Ah, I was hoping this could be released as part of a 4.4 bugfix release.

**Comment by phil294** [comment]
What's the reasoning for not leveraging JSDoc's (currently unused) `@constant` (short: `@const`) identifier for this?

**Comment by sandersn** [comment]
TS treats Closure cast syntax as the JSDoc cast syntax, so it's feature parity with TS `as const` casts.

If `@const` is truly unused in JSDoc, and likely to remain that way, it might be worth adding it as an alternate syntax. But you'd need to open a new issue with a proposal and exploration of the design problems. A couple I can think of:

- would `@const` only apply to declarations, like most tags?
- do people have existing uses of `@const` that would break in TS?
- will JSDoc ever want to use `@const` for some other meaning?

**Comment by gaurav5430** [comment]
> TypeScript has a set release schedule, the next release details are here: https://github.com/microsoft/TypeScript/issues/45418

can't see it in the plans for 4.5
is that right or am I missing something ?

**Comment by sandersn** [comment]
@gaurav5430 Fixes don't show up in the iteration plan as far as I know.

**Comment by chunjin666** [comment]
Not working in v4.7.4, how can i get this feature.

**Comment by orta** [comment]
Confirming that it [is working in 4.7.4](https://www.typescriptlang.org/play?filetype=js#code/MYewdgzgLgBAlhAwuaMC8MD0AqbMACUAngA4CmMA3qJFAL4zaYwAUlAUDFzABZkA2-EAC4YAIgDuIAE78AJgBoYYELGjS4YAOZj2dAJTt2CZLXaZmAPQD8RmqgQBlKBu3oqnbn0EjxU2YrKqjDqmjp6Rk4uYeZWtkA)

image

I'd recommend filing a full bug report if you have a case where it is not working as expected

**Comment by chunjin666** [comment]
I'm very sorry, It's my fault.
8 month ago I learned this feature and try a lot times not work (now I find out the reason is my ts verstion is 4.4.4 that time). And recently I tried agin, but it was in a ts enviroment, and I find this pr.
Thanks very mutch, My type programing experience in js project is perfectly satisfied.



At 2022-07-02 21:09:48, "Orta Therox" ***@***.***> wrote:

Confirming that it is working in 4.7.4

I'd recommend filing a full bug report if you have a case where it is not working as expected
