### PR TITLE
Skip resolving files directly inside node_modules

### LINKED ISSUE #52695: Reduce number of fs.stat call for files under node modules
# Bug Report

### 🔎 Search Terms

- fs.stat
- statSync
- performance

### Problem

While working on web project wide IntelliSense, I noticed that TS makes a number of `fs.statSync` calls for files stored under the global typings cache. At least some of these calls seem to be unnecessary, such as here where we check for files called `mkdirp.ts`, `mkdirp.tsx`, `mkdirp.d.ts` directly under `node_modules`:

```
/Users/matb/Library/Caches/typescript/4.9/node_modules/mkdirp
/Users/matb/Library/Caches/typescript/4.9/node_modules
/Users/matb/Library/Caches/typescript/4.9/node_modules/mkdirp.ts
/Users/matb/Library/Caches/typescript/4.9/node_modules/mkdirp.tsx
/Users/matb/Library/Caches/typescript/4.9/node_modules/mkdirp.d.ts
/Users/matb/Library/Caches/typescript/4.9/node_modules/mkdirp
```

I don't think these specific files would ever exist, would they?

These calls are relatively fast on desktop but do have more of an overhead on web. Even on desktop, I see around 250ms total spent on all the stat calls when starting TS Server in a simple project

Can we avoid making these calls?

### PR DESCRIPTION
**Pull request by sandersn**
Although the node module resolution algorithm looks for .js files there, they would never be there in correctly configured node_modules. So it should be safe to skip *.ts, *.js, *.tsx, etc.

- Also skips looking for files directly in node_modules/@types.
- Also skips looking for any module name containing a colon, since those look like absolute URIs.

Fixes #52695

### CODE REVIEW

**Review by sheetalkamat — APPROVED** [review]

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -2839,6 +2839,12 @@ function loadModuleFromImmediateNodeModulesDirectory(extensions: Extensions, mod
 
 function loadModuleFromSpecificNodeModulesDirectory(extensions: Extensions, moduleName: string, nodeModulesDirectory: string, nodeModulesDirectoryExists: boolean, state: ModuleResolutionState, cache: ModuleResolutionCache | undefined, redirectedReference: ResolvedProjectReference | undefined): Resolved | undefined {
     const candidate = normalizePath(combinePaths(nodeModulesDirectory, moduleName));
+    if (moduleName.indexOf(":") > -1) {
```
Comment (andrewbranch) [inline src/compiler/moduleNameResolver.ts:2842]: This should go at a higher level, in the `tryResolve` of `nodeModuleNameResolverWorker`...

File: tests/baselines/reference/nodeColonModuleResolution.trace.json [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+    "Skipping module '/a/node_modules/@types/node:ph' that looks like an absolute URI.",
+    "Directory '/node_modules' does not exist, skipping all lookups in it.",
+    "Skipping module '/node_modules/node:ph' that looks like an absolute URI.",
+    "Skipping module '/node_modules/@types/node:ph' that looks like an absolute URI.",
+    "Loading module 'node:ph' from 'node_modules' folder, target file types: JavaScript.",
+    "Skipping module '/a/b/node_modules/node:ph' that looks like an absolute URI.",
+    "Directory '/a/node_modules' does not exist, skipping all lookups in it.",
+    "Skipping module '/a/node_modules/node:ph' that looks like an absolute URI.",
+    "Directory '/node_modules' does not exist, skipping all lookups in it.",
+    "Skipping module '/node_modules/node:ph' that looks like an absolute URI.",
```
Comment (andrewbranch) [inline tests/baselines/reference/nodeColonModuleResolution.trace.json:18]: ...so that all these traces, representing lots of unnecessary zipping around and checking for `node_modules` directory existence, collapse into a single trace.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Comment by andrewbranch** [comment]
It would also be good to add a test that uses tsconfig `paths` that includes a key with a `:` to show that those lookups doesn’t get skipped.

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:2842]: wont that affect export import mapping

File: src/compiler/moduleNameResolver.ts [hunk 3]
```diff
@@ -2839,6 +2839,12 @@ function loadModuleFromImmediateNodeModulesDirectory(extensions: Extensions, mod
 
 function loadModuleFromSpecificNodeModulesDirectory(extensions: Extensions, moduleName: string, nodeModulesDirectory: string, nodeModulesDirectoryExists: boolean, state: ModuleResolutionState, cache: ModuleResolutionCache | undefined, redirectedReference: ResolvedProjectReference | undefined): Resolved | undefined {
     const candidate = normalizePath(combinePaths(nodeModulesDirectory, moduleName));
+    if (moduleName.indexOf(":") > -1) {
+        if (state.traceEnabled) {
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts:2843]: I think you want this if `nodeModulesDirectoryExists`

Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:2843]: Or skip if onlyRecordFailures

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts:2842]: I’m not sure I understand. Can you give an example?

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by sandersn** [comment]
@andrewbranch I moved the node:stuff skip to tryResolve, although you should take another look because I'm not sure I put it in the right place there.

**Review by andrewbranch — APPROVED** [review]
Looks good, but since I didn’t understand @sheetalkamat’s response to my suggestion that you’ve implemented, you might want to wait for a review from her in case I missed something.

**Comment by weswigham** [comment]
> they would never be there in correctly configured node_modules

You're absolutely right that npm will never install anything that puts loose files in the `node_modules` directory, and I'll even go so far as to say that node's [esm lookup](https://github.com/nodejs/node/blob/0084fc799425ff173b9e282f1a72bb49ae5f6c80/lib/internal/modules/esm/resolve.js#L758) doesn't look for these loose files either (a subtle difference between esm and cjs our resolver probably doesn't currently respect, actually). But it's definitely a core requirement of the old bog standard commonjs resolution algorithm - a very stable algorithm, as evidenced by how much we use it as a shorthand in our _very old_ tests. It's definitely not a good idea to diverge from it; we use it in our tests a ton because it's a nice shorthand, and older node projects have definitely made use of it, too. Can we not just replace the many-stat calls with some psuedo-stat-calls fuelled by a single `readdir` per directory? IIRC, the cost is in the syscall count, not the number of filesystem entries we inspect. Plus, we can disable it for esm-mode lookups entirely and still be algorithm compliant, and, in theory, those lookups will make up a greater percentage of lookups over time.

**Comment by weswigham** [comment]
Like, it's not frequent, but you can [definitely](https://github.com/seanf/galNum-galFly/tree/master/src/node_modules) [find](https://github.com/xtao/smartos-live/tree/master/src/node_modules) [projects](https://github.com/webinos/Webinos-Platform/tree/master/node_modules) that make use of this old cjs resolution pattern on github (usually on the older side, ofc).

**Comment by andrewbranch** [comment]
It doesn’t feel outlandish for us to say that this pattern is not recommended, but if you rely on it, simply add an entry to `paths`.

**Comment by DanielRosenwasser** [comment]
I'm not opposed to that - but also

> Can we not just replace the many-stat calls with some psuedo-stat-calls fuelled by a single `readdir` per directory?

I thought we already did this. https://github.com/microsoft/TypeScript/pull/35286

**Comment by weswigham** [comment]
@DanielRosenwasser that just made our directory iterator much more efficient (so it didn't use any extra stat calls) - it didn't swap us to _using_ that directory iterator to prefill file existence cache entries in the module name resolver.

**Comment by weswigham** [comment]
In fact, our `fileExists` calls as used in `moduleNameResolver` are, as far as I can tell, wholly uncached - we'll repeatedly try lookups for the same file paths within the same compilation. The `host` in use (for the commandline at least) is just a barebones `CompilerHost` wrapping over our default `node` `sys`.

**Comment by arvinzojaji** [comment]
Approved!

**Comment by gabritto** [comment]
@typescript-bot run DT

File: src/compiler/moduleNameResolver.ts [hunk 4]
```diff
@@ -1770,6 +1770,12 @@ function nodeModuleNameResolverWorker(features: NodeResolutionFeatures, moduleNa
                 resolved = loadModuleFromSelfNameReference(extensions, moduleName, containingDirectory, state, cache, redirectedReference);
             }
             if (!resolved) {
+                if (moduleName.indexOf(":") > -1) {
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts:1773]: I think this condition needs to be more specific.. 
theorotically module name could be `"c:./filename"` ?

File: tests/cases/compiler/requireOfJsonFileNonRelative.ts [hunk 5]
```diff
@@ -1,26 +0,0 @@
-// @module: commonjs
```
Comment (sheetalkamat) [inline tests/cases/compiler/requireOfJsonFileNonRelative.ts:1]: Why are we deleting this test case

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
I think we should add test where "node_modules/a.d,ts" can  be resolved with path mapping so we know what to suggest to user as  a work aorund

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts]: I cant remember exactly what i meant here

File: src/compiler/moduleNameResolver.ts (hunk 4 above)
Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:1798]: Sorry i keep forgetting the rooted disk path are "relative module name"

File: src/compiler/moduleNameResolver.ts [hunk 6]
```diff
@@ -2896,7 +2902,7 @@ function loadModuleFromSpecificNodeModulesDirectory(extensions: Extensions, modu
 
     const loader: ResolutionKindSpecificLoader = (extensions, candidate, onlyRecordFailures, state) => {
         let pathAndExtension =
-            loadModuleFromFile(extensions, candidate, onlyRecordFailures, state) ||
+            (rest || !(state.features & NodeResolutionFeatures.EsmMode)) && loadModuleFromFile(extensions, candidate, onlyRecordFailures, state) ||
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts:2905]: Can you point me to trace that chnged or you added for this. i couldnt find it.. probably missed it.

Comment (sandersn) [reply src/compiler/moduleNameResolver.ts:2905]: These are the tests in nodeNextModuleResolution1 and 2. 1, especially, shows that in EsmMode, there has to be a `rest` -- that is, a subdirectory inside node_modules -- in order to call loadModeFromFile. That means a file like /a/node_modules/foo.d.ts doesn't show up in the trace.

CommonJS traces are not supposed to change, so I reverted the hundreds of trace changes from earlier.

**Review by andrewbranch — APPROVED** [review]

**Review by sheetalkamat — APPROVED** [review]
