### PR TITLE
Skip files from package.json "main" or "types" if they have an unsupported extension.

### LINKED ISSUE #13004: Error: Debug Failure. False expression: File normalize.css/normalize.css has unknown extension.
**TypeScript Version:**  2.1.4 and nightly (2.2.0-dev.201xxxxx)

**Code**
```ts
import 'normalize.css';
```

**tsconfig**
```json
{
  "compilerOptions": {
    "moduleResolution": "node"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Expected behavior:**
Tsc should compile without error as ts 2.0.10 does.
This kind of import are handled by webpack that injects the css at runtime. 

**Actual behavior:**
Running tsc 2.1.4 fails with the following error
```
Error: Debug Failure. False expression: File /home/sarod/dev/git/tsloader-ts2-1/node_modules/normalize.css/normalize.css has unknown extension.
    at Object.assert (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:1796:23)
    at Object.fail (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:1801:19)
    at Object.extensionFromPath (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:1912:15)
    at resolvedFromAnyFile (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:18928:44)
    at loadNodeModuleFromDirectory (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19382:28)
    at loadModuleFromNodeModulesFolder (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19411:13)
    at loadModuleFromNodeModulesOneLevel (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19428:53)
    at /home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19422:24
    at forEachAncestorDirectory (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19480:26)
    at loadModuleFromNodeModulesWorker (/home/sarod/dev/git/tsloader-ts2-1/node_modules/typescript/lib/tsc.js:19420:16)
```

I initially thought it was a ts-loader issue that fails with another error on the same code (see https://github.com/TypeStrong/ts-loader/issues/416)

This public repro can be used to reproduce https://github.com/sarod/ts-loader-issue416

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #13004 
The problem there is that the `normalize.css` module lists a file "normalize.css" as its "main" entry point.

### CODE REVIEW

**Comment by andy-ms** [comment]
Will need to rebase onto #13025 (when it's merged) to fix tests.

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -678,18 +674,21 @@ namespace ts {
...
+            if (mainOrTypesFile) {
+                const onlyRecordFailures = !directoryProbablyExists(getDirectoryPath(mainOrTypesFile), state.host);
                 // A package.json "typings" may specify an exact filename, or may choose to omit an extension.
-                const fromFile = tryFile(typesFile, failedLookupLocations, onlyRecordFailures, state);
-                if (fromFile) {
-                    // Note: this would allow a package.json to specify a ".js" file as typings. Maybe that should be forbidden.
-                    return resolvedFromAnyFile(fromFile);
+                const fromExactFile = tryFile(mainOrTypesFile, failedLookupLocations, onlyRecordFailures, state);
+                if (fromExactFile) {
+                    const resolved = fromExactFile && resolvedFromSuspiciousFile(extensions, fromExactFile);
```
Comment (vladima) [inline src/compiler/moduleNameResolver.ts]: nit: I'd name it `resolveIfExtensionMatches`
