### PR TITLE
Use a symbol for untyped modules to distinguish from unknownSymbol

### LINKED ISSUE #12329: Difference between untyped module and ambient shorthand module used as superclass
**TypeScript Version:**   nightly (2.2.0-dev.20161117)

**Code**

```ts
// @Filename: /node_modules/foo/index.js
This file is not read.

// @Filename: /declarations.d.ts
declare module "bar";

// @Filename: /a.ts
import Foo from "foo";
import Bar from "bar";

class A extends Foo { }

class B extends Bar { }

declare var x: any;
class C extends x {}

const y = Foo;
class D extends y {}
```

**Expected behavior:**

No errors? All errors?

**Actual behavior:**

Classes `B` and `C` fail with `error TS2507: Type 'any' is not a constructor function type.`

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #12329

`getBaseConstructorTypeOfClass` specifically checks for `unknownType` before issuing an error.

We actually undid this (and just used `unknownSymbol`) in #11962. So we should be sure this is what we want.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1427,15 +1427,19 @@ namespace ts {
...
                     error(errorNode,
                         Diagnostics.Could_not_find_a_declaration_file_for_module_0_1_implicitly_has_an_any_type,
                         moduleReference,
                         resolvedModule.resolvedFileName);
+                    return undefined;
                 }
-                // Failed imports and untyped modules are both treated in an untyped manner; only difference is whether we give a diagnostic first.
-                return undefined;
+                // Unlike a failed import, an untyped module produces a dummy symbol. This is checked for by `isUntypedOrShorthandAmbientModuleSymbol`.
+                const untypedSymbol = createSymbol(SymbolFlags.ValueModule, `"${moduleName}"`);
```
Comment (mhegazy) [inline src/compiler/checker.ts]: why not return `unknownSymbol` here instead?

creating a new symbol with no backing declaration would cause other issues in the future.

Comment (andy-ms) [inline src/compiler/checker.ts]: Returning `undefined` effectively does that. But if we return `unknownSymbol`, then `getBaseConstructorTypeOfClass` will see that and won't create an error message.

Comment (mhegazy) [inline src/compiler/checker.ts]: how about a new `unknownModule` instead?
