### PR TITLE
Fix accessing `toString` of features map

### LINKED ISSUE #52334: "TypeError: array is not iterable" in `getSuggestedLibForNonExistentProperty`
Found at https://github.com/microsoft/TypeScript/issues/52253#issuecomment-1383261962.

## [pubkey/rxdb](https://github.com/pubkey/rxdb)

```
Req #1598 - completionInfo
    at contains (/typescript-5.0.0-dev.20230115/lib/tsserver.js:2826:21)
    at getSuggestedLibForNonExistentProperty (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72354:50)
    at reportNonexistentProperty (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72303:31)
    at checkPropertyAccessExpressionOrQualifiedName (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72136:11)
    at checkPropertyAccessExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:71927:94)
    at checkExpressionWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77122:16)
    at checkExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77047:32)
    at checkExpressionForMutableLocation (/typescript-5.0.0-dev.20230115/lib/tsserver.js:76810:18)
    at checkPropertyAssignment (/typescript-5.0.0-dev.20230115/lib/tsserver.js:76826:12)
    at checkObjectLiteral (/typescript-5.0.0-dev.20230115/lib/tsserver.js:71023:71)
    at checkExpressionWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77120:16)
    at checkExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77047:32)
    at checkExpressionWithContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:76703:18)
    at getSignatureApplicabilityError (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73067:25)
    at chooseOverload (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73525:13)
    at resolveCall (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73384:16)
    at resolveCallExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:73800:12)
    at resolveSignature (/typescript-5.0.0-dev.20230115/lib/tsserver.js:74183:16)
    at getResolvedSignature (/typescript-5.0.0-dev.20230115/lib/tsserver.js:74203:20)
    at getContextualTypeForArgumentAtIndex (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70051:112)
    at getContextualTypeForArgument (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70042:39)
    at getContextualType2 (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70479:16)
    at getApparentTypeOfContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70415:120)
    at getContextualTypeForObjectLiteralElement (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70276:18)
    at getContextualType2 (/typescript-5.0.0-dev.20230115/lib/tsserver.js:70487:16)
    at Object.getContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:46825:14)
    at getContextualType (/typescript-5.0.0-dev.20230115/lib/tsserver.js:148459:19)
    at getCompletionData (/typescript-5.0.0-dev.20230115/lib/tsserver.js:148690:43)
    at Object.getCompletionsAtPosition (/typescript-5.0.0-dev.20230115/lib/tsserver.js:146977:26)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.0.0-dev.20230115/lib/tsserver.js:134099:35)
    at IOSession.getCompletions (/typescript-5.0.0-dev.20230115/lib/tsserver.js:176530:54)
    at completionInfo (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174929:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177286:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177336:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230115/lib/tsserver.js:178787:14)
```
That is a filtered view of the text. To see the raw error text, go to RepoResults3/pubkey.rxdb.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":1595,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":180,"offset":34}}
{"seq":1596,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":184,"offset":6,"includeExternalModuleExports":false,"includeInsertTextCompletions":true,"triggerKind":1}}
{"seq":1597,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":184,"offset":6,"entryNames":["@abstract"]}}
{"seq":1598,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/dist/es/rx-query.js","line":188,"offset":11,"includeExternalModuleExports":false,"includeInsertTextCompletions":true,"triggerKind":1}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/pubkey/rxdb --recurse-submodules</code></li>
<li>In dir <code>rxdb</code>, run <code>git reset --hard 2196f118285768022b7ca79f7931ecd4c94d1750</code></li>
<li><details><summary>Install packages (exact steps are below, but it might be easier to follow the repo readme)</summary><ol>
  <li>In dir <code>rxdb/docs-src/files/logo</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/docs/files/files/logo</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/docs/files/logo</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/angular</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/electron</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/flutter/javascript</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/graphql</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/ionic2</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/node</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/react-native</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/react</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/supabase</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/svelte</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/vanilla</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/vite-vanilla-ts</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/examples/vue</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/attachments</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/backup</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/cleanup</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/crdt</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/dev-mode</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/electron</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/encryption</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/flutter</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/json-dump</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/key-compression</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/leader-election</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/local-documents</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/migration</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/query-builder</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-couchdb-new</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-couchdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-firestore</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-graphql</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-p2p</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication-websocket</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/replication</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/server-couchdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-dexie</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-foundationdb</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-lokijs</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-memory</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-remote-websocket</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/storage-remote</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/update</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/utils</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/validate-ajv</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/validate-is-my-json-valid</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/plugins/validate-z-schema</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
  <li>In dir <code>rxdb/test/tutorials</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
</ol></details>
<li>Back in the initial folder, download <code>RepoResults3/pubkey.rxdb.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=142763&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./rxdb ./pubkey.rxdb.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #52334.

The crash happened because we were accessing an object's `toString` property, which was a function (the one every object has by default), and not an array like expected.

### CODE REVIEW

**Comment by gabritto** [comment]
well, linter tells me I can't use `Object.hasOwnProperty` 🤷‍♀️

File: tests/cases/fourslash/completionsWithToStringMissingProperty.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+////         var stringObj = sortObject({
+////             op: /**/this.op,
+////             query: this.mangoQuery,
+////             other: this.other
+////         }, true);
+////         var value = JSON.stringify(stringObj, stringifyFilter);
+////         this.toString = () => value;
+////         return value;
+////     }
+//// }
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionsWithToStringMissingProperty.ts:20]: Here's something a little bit more simplified

```ts
function SomeClass() {
}
var _proto = SomeClass.prototype;
_proto.toString = function toString() {
    this.yadda/*quickinfo*/
    let someValue = "";
    this.toString = () => someValue;
    return someValue;
}
```

Comment (DanielRosenwasser) [reply tests/cases/fourslash/completionsWithToStringMissingProperty.ts:20]: Or just request diagnostics I guess.

**Comment by DanielRosenwasser** [comment]
This still feels off - why are we reporting a missing property in the first place?

**Comment by gabritto** [comment]
> This still feels off - why are we reporting a missing property in the first place?

We are? As far as I could tell, in the end we don't actually report the error, we just run into this piece of code which happens to crash. Is there an example of code where we actually do surface this error?

**Comment by DanielRosenwasser** [comment]
Yes, the stack trace is

```ts
Req #1598 - completionInfo
    at contains (/typescript-5.0.0-dev.20230115/lib/tsserver.js:2826:21)
    at getSuggestedLibForNonExistentProperty (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72354:50)
    at reportNonexistentProperty (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72303:31)
    at checkPropertyAccessExpressionOrQualifiedName (/typescript-5.0.0-dev.20230115/lib/tsserver.js:72136:11)
    at checkPropertyAccessExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:71927:94)
    at checkExpressionWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77122:16)
    at checkExpression (/typescript-5.0.0-dev.20230115/lib/tsserver.js:77047:32)
```

Another way to trigger this is diagnostics:

```
TypeError: array is not iterable
    at contains ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:2837:21)
    at getSuggestedLibForNonExistentProperty ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:72458:50)
    at reportNonexistentProperty ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:72407:31)
    at checkPropertyAccessExpressionOrQualifiedName ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:72240:11)
    at checkPropertyAccessExpression ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:72031:94)
    at checkExpressionWorker ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:77240:16)
    at checkExpression ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:77160:32)
    at checkExpressionStatement ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:79675:5)
    at checkSourceElementWorker ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82532:16)
    at checkSourceElement ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82392:7)
    at forEach ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:2703:22)
    at checkBlock ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:79280:7)
    at checkSourceElementWorker ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82528:16)
    at checkSourceElement ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82392:7)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:75576:9)
    at checkDeferredNode ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82693:9)
    at Set.forEach (<anonymous>)
    at checkDeferredNodes ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82672:27)
    at checkSourceFileWorker ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82760:7)
    at checkSourceFile ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82725:5)
    at checkSourceFileWithEagerDiagnostics ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82819:5)
    at getDiagnosticsWorker ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82827:7)
    at Object.getDiagnostics2 [as getDiagnostics] ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:82804:14)
    at [user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115208:76
    at runWithCancellationToken ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115178:14)
    at getBindAndCheckDiagnosticsForFileNoCache ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115196:12)
    at getAndCacheDiagnostics ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115453:20)
    at getBindAndCheckDiagnosticsForFile ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115193:12)
    at getSemanticDiagnosticsForFile ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115188:33)
    at getDiagnosticsHelper ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115126:44)
    at Object.getSemanticDiagnostics ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:115139:12)
    at Object.getSemanticDiagnostics ([user-dir]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202301190/node_modules/typescript/lib/tsserver.js:134273:41)
```

Something is off - I feel like this has to do with how circular types are handled (deferred node type checking) and how certain JavaScript properties are assigned to (specifically, prototype properties). But I haven't had the chance to dive in.

**Comment by gabritto** [comment]
> Something is off - I feel like this has to do with how circular types are handled (deferred node type checking) and how certain JavaScript properties are assigned to (specifically, prototype properties). But I haven't had the chance to dive in.

I see. I was confused because even though we call `reportNonexistentProperty`, it seems to me we don't surface an error diagnostic to the editor (or maybe I just haven't set the example correctly). So you think we shouldn't be calling `reportNonexistentProperty` for these example JS programs? I'll look into that, and maybe open a different issue, but in any case I think the code I'm changing in the PR inside `getSuggestedLibForNonExistentProperty` is definitely wrong and prone to crashing.

File: tests/cases/fourslash/completionsWithToStringMissingProperty.ts (hunk 1 above)
Comment (gabritto) [reply tests/cases/fourslash/completionsWithToStringMissingProperty.ts:20]: Thanks for the example, I'll replace the test to use that.

**Comment by DanielRosenwasser** [comment]
I respect that the logic in the diagnostic reporter was wrong. If we think that's a sufficient fix, for now, I'm not entirely against it; however, I think this is a result of some uninitialized/resolving state. It reminds me a bit of https://github.com/microsoft/TypeScript/pull/46471.

When I looked at the surrounding call site, I noticed this line:

https://github.dev/microsoft/TypeScript/blob/19d2d9ec0174fc3d96d4e70800d9fbc18d1a0aa7/src/compiler/checker.ts#L30985

So I played around, and I think I found a hint for what might be going wrong in the first place:

```ts
// @ts-check

class SomeClass {}

const _proto = SomeClass.prototype;

// Uncomment this:
// /**
//  * @this {SomeClass}
//  */
_proto.toString = function toString() {
    this.yadda/*quickinfo*/
    let someValue = "";
    this.toString = () => someValue;
    return someValue;
}
```

**Comment by DanielRosenwasser** [comment]
More minimal repro (which is actually more confusing????)

```ts
// @ts-check

function toString() {
    this.yadda
    this.blah = "";
}
```

**Comment by gabritto** [comment]
I've talked to Daniel and looked into this bug again because it wasn't clear to us why `getSuggestedLibForNonExistentProperty` was being called for the examples in the first place.
What I know so far:

- `getSuggestedLibForNonExistentProperty` is called inside `reportNonexistentProperty`. Basically, inside `reportNonexistentProperty` we go through a bunch of heuristics seeing if they apply, to give possible fix suggestions for a nonexistent property error. One of these heuristics is to check if the user can fix the error by changing the target library, e.g. if you have `"foo".replaceAll` and we can't find `String.replaceAll`, we suggest you to change your target lib to es2021 or higher, where type `String` does have a `replaceAll` property.
- The crash happens inside `getSuggestedLibForNonExistentProperty`, which ends up being called for the examples because none of the previous suggestion heuristics in `reportNonexistentProperty` apply.
- `getSuggestedLibForNonExistentProperty` receives the missing property name, and the type which we tried to access the property from. So in the last example, `this.yadda` leads to us calling `reportNonexistentProperty` for `yadda` property name, with whatever the type of `this` is. Because there's also a line with `this.blah = ""` inside the function, we think we're in a constructor function, so the type of `this` becomes this class-like type, whose symbol name is `toString`. And then we use the type's symbol's name, `toString`, to incorrectly look up the feature set object, leading to the crash.

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Review by andrewbranch — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
> so the type of `this` becomes this class-like type, whose symbol name is `toString`. And then we use the type's symbol's name, `toString`, to incorrectly look up the feature set object, leading to the crash.

🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮🤮

**Review by DanielRosenwasser — APPROVED** [review]

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -1193,108 +1193,407 @@ export function getInternalEmitFlags(node: Node): InternalEmitFlags {
...
+            es2022: [
+                "at"
+            ],
+            es2023: [
+                "findLastIndex",
+                "findLast"
+            ],
+        })),
+        Iterator: new Map(Object.entries({
+            es2015: emptyArray,
```
Comment (sandersn) [inline src/compiler/utilities.ts:1230]: this dual use is stil pretty confusing. 
I don't think I'd prefer a two-level map `Type -> property -> lib` and a separate one-level map `Type -> lib`, because it would involve more typing, but it would definitely be easier to understand.

**Review by sandersn — APPROVED** [review]
