### PR TITLE
Make specifier generation from export map information conditional on module resolution mode

### LINKED ISSUE #46659: v4.5 regression: The inferred type of '…' cannot be named without a reference to '…'
# Bug Report

### 🔎 Search Terms

- rxjs
- re-export
- declaration
- composite
- project references

### 🕗 Version & Regression Information

- This changed between versions 4.4.4 and 4.5.1-rc

### ⏯ Playground Link

N/A

### 💻 Code

`package.json`:
```json
{
  "dependencies": {
    "rxjs": "^7.4.0",
    "typescript": "^4.5.1-rc"
  }
}

```

`tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "CommonJS",
        "declaration": true,
        "outDir": "./target/"
    },
    "files": ["./src/main.ts"],
}
```

`src/facade.ts`:
```ts
export { connectable, EMPTY } from 'rxjs';

```

`src/main.ts`:
```ts
import * as Rx from './facade';

export const myConnectable = Rx.connectable(Rx.EMPTY);

```

Steps to reproduce:

- Run `yarn`
- Run `tsc`

### 🙁 Actual behavior

No error, as it behaved in 4.4.4.

### 🙂 Expected behavior

Error:

```sh-session
$ tsc
src/main.ts:3:14 - error TS2742: The inferred type of 'myConnectable' cannot be named without a reference to '../node_modules/rxjs/dist/types'. This is likely not portable. A type annotation is necessary.

3 export const myConnectable = Rx.connectable(Rx.EMPTY);
               ~~~~~~~~~~~~~


Found 1 error.
```

---

I am able to workaround this by modifying `src/facade.ts` like so:

```diff
 export { connectable, EMPTY } from 'rxjs';
+export * from 'rxjs/internal/types'
```

Note also that the error doesn't reproduce if we import directly from `rxjs`:

`src/main.ts`:

```ts
import { EMPTY, connectable } from 'rxjs';

export const myConnectable = connectable(EMPTY);
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #46659

This fixes the regression on our part in `moduleResolution: node`, however `rxjs` does legitimately have the problem that their types aren't directly visible in their export map, which makes locating a valid specifier for them when export maps are respected rather difficult.

### CODE REVIEW

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -707,13 +707,15 @@ namespace ts.moduleSpecifiers {
...
                 const packageJsonContent = JSON.parse(host.readFile!(packageJsonPath)!);
                 // TODO: Inject `require` or `import` condition based on the intended import mode
-                const fromExports = packageJsonContent.exports && typeof packageJsonContent.name === "string" ? tryGetModuleNameFromExports(options, path, packageRootPath, packageJsonContent.name, packageJsonContent.exports, ["node", "types"]) : undefined;
-                if (fromExports) {
-                    const withJsExtension = !hasTSFileExtension(fromExports.moduleFileToTry) ? fromExports : { moduleFileToTry: removeFileExtension(fromExports.moduleFileToTry) + tryGetJSExtensionForFile(fromExports.moduleFileToTry, options) };
-                    return { ...withJsExtension, verbatimFromExports: true };
-                }
-                if (packageJsonContent.exports) {
-                    return { moduleFileToTry: path, blockedByExports: true };
+                if (getEmitModuleResolutionKind(options) === ModuleResolutionKind.Node12 || getEmitModuleResolutionKind(options) === ModuleResolutionKind.NodeNext) {
```
Comment (weswigham) [inline src/compiler/moduleSpecifiers.ts:710]: I made the whole of the exports map logic conditional - I could just make the failure modes conditional, but then we might make some specifiers that won't roundtrip through declaration emit (because we use an export map that we won't read in when we build the program), so this is probably better.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.5

File: src/compiler/moduleSpecifiers.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts:710]: Yeah, I think being symmetrical is the right call.

**Review by andrewbranch — APPROVED** [review]
> however `rxjs` does legitimately have the problem that their types aren't directly visible in their export map, which makes locating a valid specifier for them when export maps are respected rather difficult.

Yeah, my understanding is that it’s fully expected that the layout of RxJS (export map not mentioning types and types in a completely different directory) means it’s basically unusable under the new resolution modes—they either need to move their types to be colocated with their JS or add a `"types"` condition to their export map.
