### PR TITLE
Prevent merged class/namespace from overlapping with `Record<string, unknown>`

### LINKED ISSUE #43754: "sufficiently overlaps" on class instance depends on class statics
# Bug Report

### 🔎 Search Terms

sufficiently overlaps class namespace

### 🕗 Version & Regression Information

TS 4.2, TS v4.3.0-dev.20210420 

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about compatibility

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210420#code/FAYwNghgzlAEDCBGWBvWAzA9pgFASlQF9ZDhgA7AUwHcFF9ZpYAlSkTAJwBMAeKAFw4BLcgHMANLACu5ANblM1cgD4A3LFgB6TbEocOnSU0oAPAA5t+lLmTLhoceACZUGbAxTFS5CAFtKUGYQIJQILmimZpz8sOzkAtLkHJSQVlywALywAMzqpBQ0YQxMrOzcfIIiEonyiirqWjoQYGCK1gCEAPzAQA)

### 💻 Code

```ts
class C1 { foo() {} }
new C1() as Record<string, unknown>;  // error, as expected

class C2 { foo() {} }
namespace C2 { export const unrelated = 3; }
new C2() as Record<string, unknown>;  // allowed!?
```

### 🙁 Actual behavior

The existence of the field in the C2 namespace somehow affects the assignability calculation of the instance.

### 🙂 Expected behavior

I would expect these namespace-level properties to not get involved (?) in the assignability of instances.

Either both succeed or both fail.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #43754

If a class is merged with a namespace, we don't want treat values of that type as overlapping with `Record<string, unknown>`.

Additionally, reformat the expression a little; it was wrapped weirdly and it was not very clear where the parens were (namely, the `typeHasCallOrConstructSignatures` check appears to be part of the second expression, when it is in fact in the first).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21000,9 +21000,14 @@ namespace ts {
...
         function isObjectTypeWithInferableIndex(type: Type): boolean {
-            return type.flags & TypeFlags.Intersection ? every((type as IntersectionType).types, isObjectTypeWithInferableIndex) :
-                !!(type.symbol && (type.symbol.flags & (SymbolFlags.ObjectLiteral | SymbolFlags.TypeLiteral | SymbolFlags.Enum | SymbolFlags.ValueModule)) !== 0 &&
-                !typeHasCallOrConstructSignatures(type)) || !!(getObjectFlags(type) & ObjectFlags.ReverseMapped && isObjectTypeWithInferableIndex((type as ReverseMappedType).source));
+            return type.flags & TypeFlags.Intersection
+                ? every((type as IntersectionType).types, isObjectTypeWithInferableIndex)
+                : !!(
+                    type.symbol
+                    && (type.symbol.flags & (SymbolFlags.ObjectLiteral | SymbolFlags.TypeLiteral | SymbolFlags.Enum | SymbolFlags.ValueModule)) !== 0
+                    && !((type.symbol.flags & SymbolFlags.Class) && (type.symbol.flags & SymbolFlags.ValueModule))
```
Comment (andrewbranch) [inline src/compiler/checker.ts:21008]: Is there a reason not to just use `!(type.symbol.flags & SymbolFlags.Class)` (dropping the “and is also a value module”)? It looks to me like we believe namespaces generally have an inferable index, and classes don’t, and we want the classiness property to trump the namespacey property in this calculation. It doesn’t seem to need the specificity of “classes merged with namespaces.”

Comment (jakebailey) [reply src/compiler/checker.ts:21008]: Probably not; things still work as expected with that simplification. I just took the solution suggested in the issue and thumbs-up'd by Ryan.

Comment (jakebailey) [reply src/compiler/checker.ts:21008]: Switched it over.

**Review by andrewbranch — APPROVED** [review]
