### PR TITLE
fix issue where duplicate default exports aren't detected

### LINKED ISSUE #46865: no error on redeclared default export when there's also a default exported interface
# Bug Report

when a default export has both a class and an interface, no error occurs when a third default export is present

### 🔎 Search Terms

redeclare default export interface

### 🕗 Version & Regression Information

4.6.0-dev.20211118

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211118#code/MYewdgzgLgBAZiEMC8MCMAoDBTAHgBxACdYATbOAQwFcAbWBELPQkmcqu2ASzCmyJVg2GADFEMAN4BfZgWJkKNejGC1KECGIkygA)

### 💻 Code

```ts
const foo = 1

export default foo

export default interface Foo {}

export default class Foo {}
```

### 🙁 Actual behavior
no error

### 🙂 Expected behavior
error on the default exported const or class (but not the interface)

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #46865

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
We'll definitely want a testcase or two. This stuff is very easy to unintentionally break when modifying the binder.

**Comment by DetachHead** [comment]
@RyanCavanaugh done

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -40095,10 +40095,10 @@ namespace ts {
                         }
                         // ECMA262: 15.2.1.1 It is a Syntax Error if the ExportedNames of ModuleItemList contains any duplicate entries.
                         // (TS Exceptions: namespaces, function overloads, enums, and interfaces)
-                        if (flags & (SymbolFlags.Namespace | SymbolFlags.Interface | SymbolFlags.Enum)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:40098]: does this mean `export interface I { }; export interface I { }` is no longer allowed?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -40095,10 +40095,10 @@ namespace ts {
                         }
                         // ECMA262: 15.2.1.1 It is a Syntax Error if the ExportedNames of ModuleItemList contains any duplicate entries.
                         // (TS Exceptions: namespaces, function overloads, enums, and interfaces)
```
Comment (sandersn) [inline src/compiler/checker.ts:40097]: it doesn't look like exported function overloads are handled here. can you add a test case and update the comment if needed?

File: tests/cases/compiler/exportDefaultInterfaceClassAndValue.ts [hunk 3]
```diff
@@ -0,0 +1,4 @@
+const foo = 1
+export default foo
+export default class Foo {}
+export default interface Foo {}
```
Comment (sandersn) [inline tests/cases/compiler/exportDefaultInterfaceClassAndValue.ts:4]: can you please add tests for

- non-default exports,
- export list with duplicate entries
- a file without `interface Foo`, since just const and class should be enough to give an error
- a version with type alias instead of interface
- actually, several different combinations of interfaces and other values/types/namespaces

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (DetachHead) [reply src/compiler/checker.ts:40098]: i just checked and that still works, i assume there's already a test for this somewhere but i can't find it. if not, i can add one if you'd like

File: src/compiler/checker.ts (hunk 2 above)
Comment (DetachHead) [reply src/compiler/checker.ts:40097]: added a couple tests for this and it seems to be working correctly. i believe it's handled [here](https://github.com/microsoft/TypeScript/pull/46871/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R40101)

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts:40098]: Yes, please. I'm not confident in our existing test coverage.

Comment (DetachHead) [reply src/compiler/checker.ts:40098]: done
