### PR TITLE
system: fix emit for enums and exported non-top level items

### LINKED ISSUE #3107: Declaration merging broken when targeting 'system' module loader.
tsconfig
```json
    "compilerOptions": {
        "target": "es5",
        "module": "system",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
```
TS
```ts
export enum Foo {
	Bar
}

export module Foo {
	export function parse(input: string): Foo {
		throw new Error(`Failed to parse ${input} as a Foo.`);
	}
}
```
JS
```js
System.register([], function(exports_1) {
    var Foo;
    return {
        setters:[],
        execute: function() {
            (function (Foo) {
                Foo[Foo["Bar"] = 0] = "Bar";
            })(Foo || (Foo = {}));
            var Foo = Foo;
            (function (Foo) {
                function parse(input) {
                    throw new Error("Failed to parse " + input + " as a Foo.");
                }
                exports_1("parse", parse);
            })(Foo = Foo || (Foo = {}));
            exports_1("Foo", Foo)
        }
    }
});
```

Notice how `parse` is added to `exports_1` rather than being added to `Foo`.

### PR DESCRIPTION
**Pull request by vladima**
for some reason emit for enums was missing - added it in this PR.
Also it fixes #3107

### CODE REVIEW

**Comment by vladima** [comment]
I think this fix should go into 1.5

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -5153,7 +5181,6 @@ var __param = (this && this.__param) || function (paramIndex, decorator) {
                     }
 
                     if (node.kind === SyntaxKind.ClassDeclaration) {
-                        // TODO: rename block scoped classes
```
Comment (vladima) [inline src/compiler/emitter.ts]: Comment is remove since it is not relevant - only top level classes should be hoisted and they are not renamed

**Comment by DanielRosenwasser** [comment]
Can we get two more tests for
* const enums (`tests/cases/compiler/systemModuleNonTopLevelConstEnums.ts`)
* declared/ambient entities (`tests/cases/compiler/systemModuleNonTopLevelAmbientDeclarations.ts`)

**Comment by DanielRosenwasser** [comment]
:+1:
