### PR TITLE
Produce source maps for local typescriptServices build

### LINKED ISSUE #41439: Produce correct sourcemaps for local builds of tsc/typescriptServices
**TypeScript Version:**  master branch

**Search Terms:**
- typescriptServices
- sourcemap

**Code**

Imagine the following program with a breakpoint on the last line. "Stepping in" doesn't show the original file, because source maps are not working.

```ts
import ts from 'typescript';

ts.createProgram(undefined, {}); // <- breakpoint on this line
```

**Expected behaviour**

Source maps should work.

**Actual behaviour**

Source maps for `built/local/typescriptServices.out.js` are disabled as you can see here: https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/src/tsconfig-library-base.json#L5

It's especially confusing because the Gulpfile assumes that they are enabled and produces **broken sourcemaps** for the downstream files (`typescriptServices.js` and `typescript.js`):

https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/Gulpfile.js#L132-L139

https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/Gulpfile.js#L149-L155

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #41439. Confirmed `gulp lkg` doesn’t put any new map files in `lib`.

### CODE REVIEW

File: Gulpfile.js [hunk 1]
```diff
@@ -590,6 +590,7 @@ task("LKG").description = "Makes a new LKG out of the built js files";
 task("LKG").flags = {
     "   --built": "Compile using the built version of the compiler.",
 };
+task("lkg", series("LKG"));
```
Comment (andrewbranch) [inline Gulpfile.js:593]: Gets me every time

**Comment by sheetalkamat** [comment]
> Confirmed gulp lkg doesn’t put any new map files in lib.

Just checking.. even though sourcemaps are not copied wouldnt js file have ///sourcemap link ? or is that also managed in the gulp script somewhere.

**Comment by andrewbranch** [comment]
Hmm, good question, but they already have that... https://unpkg.com/typescript@4.0.5/lib/typescript.js

**Comment by andrewbranch** [comment]
@sheetalkamat any ideas whether this needs changes? The outputs seem to match what already exists, but I’m open to improving that if necessary.

**Review by sheetalkamat — APPROVED** [review]
