### PR TITLE
Fix find-all-references for destructured getter

### LINKED ISSUE #16922: VS2017 Find all references doesn't detect Object destructuring with accessors
**TypeScript Version:**  2.4.1

**Code**

```ts
class Test {
    get testProp(): string {return "test";}
}
let obj: Test;
let { testProp } = obj;
```

**Expected behavior:**
Find all references on ```get testProp()``` should detect the last line ```let { testProp } = obj;``` as a reference (just the same way it works if ```testProp``` is a simple field or a method)

**Actual behavior:**
Find all references on ```get testProp()``` does not detect the last line ```let { testProp } = obj;``` as a reference

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #16922

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -604,11 +604,16 @@ namespace ts.FindAllReferences.Core {
...
     function getPropertySymbolOfObjectBindingPatternWithoutPropertyName(symbol: Symbol, checker: TypeChecker): Symbol | undefined {
         const bindingElement = getObjectBindingElementWithoutPropertyName(symbol);
-        if (bindingElement) {
-            const typeOfPattern = checker.getTypeAtLocation(bindingElement.parent);
-            return typeOfPattern && checker.getPropertyOfType(typeOfPattern, (<Identifier>bindingElement.name).text);
+        if (!bindingElement) return undefined;
+
+        const typeOfPattern = checker.getTypeAtLocation(bindingElement.parent);
+        const propSymbol = typeOfPattern && checker.getPropertyOfType(typeOfPattern, (<Identifier>bindingElement.name).text);
+        if (propSymbol && propSymbol.flags & SymbolFlags.GetAccessor) {
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts]: Should check both Get and Set assessors as the below sample is not error?
```TypeScript
class test1 {
    set x(a: number) {
    }
}

const { x } = new test1(); 
```

Comment (andy-ms) [inline src/services/findAllReferences.ts]: Good catch! I didn't realize that was possible.

File: src/services/findAllReferences.ts [hunk 2]
```diff
@@ -604,11 +604,16 @@ namespace ts.FindAllReferences.Core {
...
     function getPropertySymbolOfObjectBindingPatternWithoutPropertyName(symbol: Symbol, checker: TypeChecker): Symbol | undefined {
         const bindingElement = getObjectBindingElementWithoutPropertyName(symbol);
-        if (bindingElement) {
-            const typeOfPattern = checker.getTypeAtLocation(bindingElement.parent);
-            return typeOfPattern && checker.getPropertyOfType(typeOfPattern, (<Identifier>bindingElement.name).text);
+        if (!bindingElement) return undefined;
+
+        const typeOfPattern = checker.getTypeAtLocation(bindingElement.parent);
+        const propSymbol = typeOfPattern && checker.getPropertyOfType(typeOfPattern, (<Identifier>bindingElement.name).text);
+        if (propSymbol && propSymbol.flags & (SymbolFlags.GetAccessor | SymbolFlags.SetAccessor)) {
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts]: Nit: just use SymbolFlags.Accessor
