### PR TITLE
Fix crash in type resolution in JS IIFEs

### LINKED ISSUE #22973: typescript version 2.8.1 bug
```sh
/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:27263
                    if (namespace.valueDeclaration &&
                                  ^
TypeError: Cannot read property 'valueDeclaration' of undefined
    at resolveEntityName (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:27263:35)
    at resolveTypeReferenceName (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:32085:20)
    at getTypeFromTypeReference (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:32232:30)
    at checkTypeReferenceNode (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:44202:24)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47664:28)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47706:28)
    at checkJSDocParameterTag (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:45056:13)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47691:28)
    at Object.forEach (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:1762:30)
    at checkSourceElement (/Users/tomato/Sites/okoer/okoer-api/node_modules/typescript/lib/typescript.js:47625:24)
```

There is no problem using typescript 2.7.2 for the project, but upgrade to 2.8.1 to run the error

### PR DESCRIPTION
**Pull request by sandersn**
We recognise IIFEs as JS special assignment initialisers, but not as containers otherwise. That means that IIFEs will not have a symbol unless they have an *outside* assignment.

The permanent fix will be to make IIFEs a container, based on the containership of the value that they return. This fix does not do that; it just makes type resolution return undefined instead of crashing.

Fixes #22973 

This fix is bound for 2.8 since it's a fairly bad regression.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2063,6 +2063,9 @@ namespace ts {
                     if (initializer) {
                         namespace = getSymbolOfNode(initializer);
                     }
+                    if (!namespace) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: i would add a comment here as well.

Comment (sandersn) [reply src/compiler/checker.ts]: Done

**Comment by mhegazy** [comment]
Please port to release-2.8 as well.

**Comment by sandersn** [comment]
This is in 2.8 now too.
