### PR TITLE
Fix runaway recursion in object type member resolution

### LINKED ISSUE #25291: Stack overflow when spread a tuple type alias inside itself  (with conditional type and generic default)
**TypeScript Version:**  Version 3.0.0-dev.20180628

**Search Terms:**  tuple types

**Code**

```ts
type PromisedTuple<L extends any[], U = (...args: L) => void> =
    U extends (h: infer H, ...args: infer R) ? [Promise<H>, ...PromisedTuple<R>] : []

type Promised = PromisedTuple<[1, 2, 3]> 
// expect [Promise<1>, Promise<2>, Promise<3>]
```

**Expected behavior:**
Either produce type in comment above, or produce a compile error.

**Actual behavior:**

RangeError: Maximum call stack size exceeded at `getTypeFromTypeNode`

**Related Issues:** https://github.com/Microsoft/TypeScript/pull/24897#issuecomment-400549996

Extended explanation:

This code tries to model the `Array#map` on a heterogeneous tuple type . It uses conditional type and generic default to work around recursion.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #25291.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5514,7 +5517,7 @@ namespace ts {
                 // (otherwise there'd be an error from hasBaseType) - this is fine, but `.members` should be reset
                 // as `getIndexedAccessType` via `instantiateType` via `getTypeFromClassOrInterfaceReference` forces a
                 // partial instantiation of the members without the base types fully resolved
-                (type as Type as ResolvedType).members = undefined!; // TODO: GH#18217
+                type.members = undefined; // TODO: GH#18217
```
Comment (mhegazy) [inline src/compiler/checker.ts]: no need for the comment now.
