### PR TITLE
Use type-only imports in auto-imports when it would be an error not to, and use auto-imports in “implement interface” fix

### LINKED ISSUE #34995: Implementing interface puts relative imports
**TypeScript Version:**  `3.7.2`

**Code**

* `git clone https://github.com/microsoft/vscode.git`
* `yarn`
* open VSCode on `anythingQuickAccess.ts`
* type in the top:

```ts
class FooHandler implements IEditorGroup {

}
```

* fix the error by letting it implement the interface

**Expected behavior:**
Code that gets generated does not use inline imports.

**Actual behavior:**
Code that gets generated adds inline imports:

```ts
class FooHandler implements IEditorGroup {
	onDidGroupChange: Event<IGroupChangeEvent>;
	onWillDispose: Event<void>;
	id: number;
	index: number;
	label: string;
	ariaLabel: string;
	activeEditorPane: import("../../../common/editor").IVisibleEditorPane | undefined;
	activeEditor: IEditorInput | null;
	previewEditor: IEditorInput | null;
	count: number;
	stickyCount: number;
	editors: readonly IEditorInput[];
	getEditors(order: EditorsOrder, options?: { excludeSticky?: boolean | undefined; } | undefined): readonly IEditorInput[] {
		throw new Error('Method not implemented.');
	}
	getEditorByIndex(index: number): IEditorInput | undefined {
		throw new Error('Method not implemented.');
	}
	getIndexOfEditor(editor: IEditorInput): number {
		throw new Error('Method not implemented.');
	}
	openEditor(editor: IEditorInput, options?: import("../../../../platform/editor/common/editor").IEditorOptions | ITextEditorOptions | undefined): Promise<import("../../../common/editor").IEditorPane | null> {
		throw new Error('Method not implemented.');
	}
	openEditors(editors: import("../../../common/editor").IEditorInputWithOptions[]): Promise<import("../../../common/editor").IEditorPane | null> {
		throw new Error('Method not implemented.');
	}
	isOpened(editor: IEditorInput): boolean {
		throw new Error('Method not implemented.');
	}
	isPinned(editor: IEditorInput): boolean {
		throw new Error('Method not implemented.');
	}
	isSticky(editorOrIndex: number | IEditorInput): boolean {
		throw new Error('Method not implemented.');
	}
	isActive(editor: IEditorInput): boolean {
		throw new Error('Method not implemented.');
	}
	moveEditor(editor: IEditorInput, target: IEditorGroup, options?: import("../../../services/editor/common/editorGroupsService").IMoveEditorOptions | undefined): void {
		throw new Error('Method not implemented.');
	}
	copyEditor(editor: IEditorInput, target: IEditorGroup, options?: import("../../../services/editor/common/editorGroupsService").ICopyEditorOptions | undefined): void {
		throw new Error('Method not implemented.');
	}
	closeEditor(editor?: IEditorInput | undefined, options?: import("../../../services/editor/common/editorGroupsService").ICloseEditorOptions | undefined): Promise<void> {
		throw new Error('Method not implemented.');
	}
	closeEditors(editors: IEditorInput[] | import("../../../services/editor/common/editorGroupsService").ICloseEditorsFilter, options?: import("../../../services/editor/common/editorGroupsService").ICloseEditorOptions | undefined): Promise<void> {
		throw new Error('Method not implemented.');
	}
	closeAllEditors(options?: import("../../../services/editor/common/editorGroupsService").ICloseAllEditorsOptions | undefined): Promise<void> {
		throw new Error('Method not implemented.');
	}
	replaceEditors(editors: import("../../../services/editor/common/editorGroupsService").IEditorReplacement[]): Promise<void> {
		throw new Error('Method not implemented.');
	}
	pinEditor(editor?: IEditorInput | undefined): void {
		throw new Error('Method not implemented.');
	}
	stickEditor(editor?: IEditorInput | undefined): void {
		throw new Error('Method not implemented.');
	}
	unstickEditor(editor?: IEditorInput | undefined): void {
		throw new Error('Method not implemented.');
	}
	focus(): void {
		throw new Error('Method not implemented.');
	}
	invokeWithinContext<T>(fn: (accessor: import("../../../../platform/instantiation/common/instantiation").ServicesAccessor) => T): T {
		throw new Error('Method not implemented.');
	}

}
```

### LINKED ISSUE #35078: Add option to disable TS using inline import types in quick fixes
**TypeScript Version:**  3.8.0-dev.20191112

**Search Terms:**
- Implement interface
- quick fix
- code action
- add missing imports

**Code**
For a small project:

`iface.ts`
```ts
export interface IValue {
    value: number;
}

export interface IFace {
    do(value: IValue): void;
}
```

`index.ts`
```ts
import { IFace } from "./iface";

export class Foo implements IFace {}
```

1. Run `implement interface` on `Foo `

**Current Behavior:**
The generated code is:

```ts
import { IFace } from "./iface";

export class Foo implements IFace {
    do(value: import("./iface").IValue): void {
        throw new Error("Method not implemented.");
    }
}
```

**Request**
We would like an option to tell TypeScript to not use inline imports and instead always add normal imports at the top of the file.

```ts
import { IFace, IValue } from "./iface";

export class Foo implements IFace {
    do(value: IValue): void {
        throw new Error("Method not implemented.");
    }
}
```

/cc @bpasero Since I know you were passionate about this issue

### PR DESCRIPTION
**Pull request by andrewbranch**
1. When `importsNotUsedAsValues` is `"error"`, an auto-import at a type position will use a type-only import if a regular import would result in an error.
2. Encapsulates the fix-all logic for auto-imports in order to use it in other code fixes that would otherwise write type annotations with ImportTypeNodes, like “infer from usage,” “implement interface,” and “implement abstract class members.” (Infer from usage had an ad-hoc fix to use auto-imports already back at #33915, but I realized that if it needs to import more than one type (or the same type multiple times), it would write duplicate imports since the code fix was being reevaluated fresh for each ImportTypeNode.)

Fixes #34995
Fixes #35078 but doesn’t create a new option—I would rather wait and see if anyone is actually asking for an opt-out than start by introducing another option that nobody wants.

### CODE REVIEW

File: tests/cases/fourslash/codeFixInferFromUsageContextualImport4.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
+/// <reference path="fourslash.ts" />
+
+// @strict: true
+// @noImplicitAny: true
+// @noLib: true
+
+// @Filename: /types.d.ts
+////declare function getEmail(user: import('./a').User, settings: import('./a').Settings): string;
```
Comment (sandersn) [inline tests/cases/fourslash/codeFixInferFromUsageContextualImport4.ts]: this example is weird, in that it reflects how we would do things but not how an npm package would do things. Probably a more realistic test would be:

```ts
// @filename: index.ts
import { User, Settings } from './a'
export function getEmail(user: User, settings: Settings): string
```

It probably tests exactly the same code paths internally, so I'd prefer to see it if you only want to put one test like this in.

File: tests/cases/fourslash/importNameCodeFix_typeOnly2.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+// @Filename: index.ts
+////const a: A = new A();
+
+goTo.file("index.ts");
+verify.codeFixAll({
+  fixAllDescription: ts.Diagnostics.Add_all_missing_imports.message,
+  fixId: "fixMissingImport",
+  newFileContent:
+`import { A } from "./types";
```
Comment (sandersn) [inline tests/cases/fourslash/importNameCodeFix_typeOnly2.ts]: why does this test file end with "_typeOnly2"?

File: tests/cases/fourslash/codeFixClassImplementInterfaceAutoImports2.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+////type A = {};
+////export default A;
+
+// @Filename: types2.ts
+////export type B = {};
+////export type C = {};
+////export type D<T> = {};
+
+// @Filename: interface.ts
+////import type A from './types1';
```
Comment (sandersn) [inline tests/cases/fourslash/codeFixClassImplementInterfaceAutoImports2.ts]: `import type` is the only difference I could see between 1 and 2. Can you call it out in the filename?

File: src/services/completions.ts [hunk 4]
```diff
@@ -559,16 +559,6 @@ namespace ts.Completions {
         }) || { type: "none" };
     }
 
-    function getSymbolName(symbol: Symbol, origin: SymbolOriginInfo | undefined, target: ScriptTarget): string {
-        return origin && originIsExport(origin) && (
-            (origin.isDefaultExport && symbol.escapedName === InternalSymbolName.Default) ||
-            (symbol.escapedName === InternalSymbolName.ExportEquals))
-            // Name of "export default foo;" is "foo". Name of "export default 0" is the filename converted to camelCase.
```
Comment (sandersn) [inline src/services/completions.ts]: I would convert this into jsdoc instead of deleting it

(It seems incomplete since it doesn't mention export=)

File: src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts [hunk 5]
```diff
@@ -41,7 +41,9 @@ namespace ts.codefix {
         // so duplicates cannot occur.
         const abstractAndNonPrivateExtendsSymbols = checker.getPropertiesOfType(instantiatedExtendsType).filter(symbolPointsToNonPrivateAndAbstractMember);
 
-        createMissingMemberNodes(classDeclaration, abstractAndNonPrivateExtendsSymbols, context, preferences, member => changeTracker.insertNodeAtClassStart(sourceFile, classDeclaration, member));
+        const importAdder = createImportAdder(sourceFile, context.program, preferences, context.host);
```
Comment (sandersn) [inline src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts]: This pattern feels like dynamic scope (or, a specialisation of the state monad) that's not enforced by the compiler. I'm not a fan, although I don't know an easy way to improve it. Is it really necessary to be able to write the fixes out at the end? (the code in inferFromUsage is an uglier example of this)

Comment (andrewbranch) [reply src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts]: > Is it really necessary to be able to write the fixes out at the end?

Yes—the whole point of this PR is the acknowledgment that to auto-import more than one name at a time, you have to consider them together in order to combine and deduplicate them properly. I think part of the problem is that `changeTracker` is _also_ a state container that gets passed around getting state incrementally tacked onto it, so we’re already operating in a mode where deep call stacks mutate shared state and return nothing. And what’s more, that existing state lacks any semantic meaning that would let us derive the necessary imports changes from it (i.e., ChangeTracker works only in strings and nodes, not in symbols or types, which are needed for auto imports). Hence, another mutable state container to complement `ChangeTracker`.

File: src/services/codefixes/inferFromUsage.ts [hunk 6]
```diff
@@ -304,38 +310,17 @@ namespace ts.codefix {
...
-                );
-                if (action.codeAction.changes.length && changes.tryInsertTypeAnnotation(sourceFile, declaration, createTypeReferenceNode(typeNode.qualifier, typeNode.typeArguments))) {
-                    for (const change of action.codeAction.changes) {
-                        const file = sourceFile.fileName === change.fileName ? sourceFile : Debug.assertDefined(program.getSourceFile(change.fileName));
-                        changes.pushRaw(file, change);
-                    }
-                    return true;
-                }
-            }
+    function tryReplaceImportTypeNodeWithAutoImport(typeNode: TypeNode, changes: textChanges.ChangeTracker, importAdder: ImportAdder, sourceFile: SourceFile, declaration: textChanges.TypeAnnotatable, type: Type, scriptTarget: ScriptTarget): boolean {
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/codefixes/inferFromUsage.ts]: I think ImportAdder belongs nearby ChangeTracker, but otherwise these parameters are in kind of a weird order

File: tests/cases/fourslash/importNameCodeFix_typeOnly2.ts (hunk 2 above)
Comment (andrewbranch) [reply tests/cases/fourslash/importNameCodeFix_typeOnly2.ts]: Since there is `@importsNotUsedAsValues: error`, when we see `const a: A`, we register the import fix as type-only. Then, we get to `new A()`, and we register an import fix as _not_ type-only. The point of this test is to ensure that when there is a conflict, we _don’t_ write the final import clause as type-only. It’s the natural next test case after `importNameCodeFix_typeOnly.ts` verifies the positive, though I see how the name might look confusing taken alone.

File: src/services/codefixes/helpers.ts [hunk 7]
```diff
@@ -359,4 +414,47 @@ namespace ts.codefix {
     export function findJsonProperty(obj: ObjectLiteralExpression, name: string): PropertyAssignment | undefined {
         return find(obj.properties, (p): p is PropertyAssignment => isPropertyAssignment(p) && !!p.name && isStringLiteral(p.name) && p.name.text === name);
     }
+
+    export function tryGetAutoImportableReferenceFromImportTypeNode(importTypeNode: TypeNode | undefined, type: Type | undefined, scriptTarget: ScriptTarget) {
+        if (importTypeNode && isLiteralImportTypeNode(importTypeNode) && importTypeNode.qualifier && (!type || type.symbol)) {
+            // Replace 'import("./a").SomeType' with 'SomeType' and an actual import if possible
```
Comment (sandersn) [inline src/services/codefixes/helpers.ts]: seems like this should be a jsdoc

File: src/services/codefixes/importFixes.ts [hunk 8]
```diff
@@ -167,14 +199,20 @@ namespace ts.codefix {
...
+        const moduleSpecifier = first(getNewImportInfos(program, sourceFile, position, preferTypeOnlyImport, exportInfos, host, preferences)).moduleSpecifier;
+        const fix = getImportFixForSymbol(sourceFile, exportInfos, moduleSymbol, symbolName, program, position, preferTypeOnlyImport, host, preferences);
         return { moduleSpecifier, codeAction: codeFixActionToCodeAction(codeActionForFix({ host, formatContext, preferences }, sourceFile, symbolName, fix, getQuotePreference(sourceFile, preferences))) };
     }
 
+    function getImportFixForSymbol(sourceFile: SourceFile, exportInfos: readonly SymbolExportInfo[], moduleSymbol: Symbol, symbolName: string, program: Program, position: number | undefined, preferTypeOnlyImport: boolean, host: LanguageServiceHost, preferences: UserPreferences) {
+        Debug.assert(exportInfos.some(info => info.moduleSymbol === moduleSymbol), "Some exportInfo should match the specified moduleSymbol");
+        // We sort the best codefixes first, so taking `first` is best.
+        return first(getFixForImport(exportInfos, symbolName, position, preferTypeOnlyImport, program, sourceFile, host, preferences));
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts]: The names in this file are, at least to me, confusing, repetitive, and unexpressive, but they’re roughly consistent in including an unnecessary “for.” Someday I’d like to do some housekeeping in here, but I think renaming just one function now might not be a useful step forward.

**Comment by jamiebuilds** [comment]
@andrewbranch I think I'm gonna be the person to ask for an explicit option again. I keep having `import("module").Type` types generated whenever I have a file with zero other imports in the file, and I don't ever want that behavior. 

I think these are all the relevant options I have set:

```json
{
  "target": "es2017",
  "module": "esnext",
  "isolatedModules": true,
  "importsNotUsedAsValues": "error",
  "moduleResolution": "node",
  "allowSyntheticDefaultImports": true,
  "esModuleInterop": true
}
```
