### PR TITLE
Optimize substitution types

### LINKED ISSUE #50290: `RangeError: Map maximum size exceeded` with `typescript@4.8.1-rc`
# Bug Report

### 🔎 Search Terms

Map maximum size exceeded

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ~4.7.2 and 4.8.1-rc

### ⏯ Playground Link

~[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)~
I don't know what causes this exactly, but the repo isn't too big:
https://github.com/adazzle/react-data-grid/pull/2988

### 💻 Code

I don't know what code causes the crash. Please see this branch:
https://github.com/adazzle/react-data-grid/pull/2988

### 🙁 Actual behavior

```
> tsc

D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:98414
                throw e;
                ^

RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at recursiveTypeRelatedTo (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:55247:42)
    at isRelatedTo (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:54809:25)
    at eachTypeRelatedToType (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:55098:35)
    at unionOrIntersectionRelatedTo (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:54990:25)        
    at structuredTypeRelatedToWorker (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:55321:34)       
    at structuredTypeRelatedTo (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:55261:30)
    at recursiveTypeRelatedTo (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:55230:30)
    at isRelatedTo (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:54809:25)
    at eachTypeRelatedToType (D:\repos\react-data-grid\node_modules\typescript\lib\tsc.js:55098:35)

Node.js v18.7.0
```

### 🙂 Expected behavior

No crash.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR optimizes creation and instantiation of substitution types. Two main changes:

* Substitution types previously stored the substitute type as an intersection between the base type and the constraint being added. These components are now stored separately (in `baseType` and `constraint` properties) and intersected when needed. The separation enables a more efficient check for whether an instantiated substitution type should be preserved or resolved to its base type: Peviously this check compared the base type to the full substitution intersection, it now just compares the base type to the constraint. This turned out to be the origin of the relation cache overflow in #50290.

* Due to some erroneous logic in `getTypeFromIndexedAccessTypeNode`, previously we would stack two substitution types on top of each other for indexed access types. This created a lot of unnecessary work.

With these optimizations, the check time for the repro in #50290 drops from 11.2s to 5.2s, a greater than 50% reduction! I imagine other projects that contain complicated conditional types may see a similar benefit.

Fixes #50290.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13881,22 +13881,28 @@ namespace ts {
             return links.resolvedJSDocType;
         }
 
-        function getSubstitutionType(baseType: Type, substitute: Type) {
-            if (substitute.flags & TypeFlags.AnyOrUnknown || substitute === baseType) {
+        function getSubstitutionType(baseType: Type, constraint: Type) {
+            if (constraint.flags & TypeFlags.AnyOrUnknown || constraint === baseType ||
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:13885]: > `constraint === baseType`

Is this just when someone writes

```ts
T extends T ? TrueType : FalseType
```

?

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
Would you be able to write a few tests that are known to trigger the new behavior? This gives a few good example cases to better understand the changes now and in the future too, and ensure we don't regress.

**Comment by ahejlsberg** [comment]
@typescript-bot user test this inline

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:13885]: I presume so. The check was already there.

**Comment by ahejlsberg** [comment]
> Would you be able to write a few tests that are known to trigger the new behavior?

There isn't really any new behavior, we're just more efficient. It's not trivial to produce a test that uses substitution types to force a relation cache overflow, the repros we have are somewhat involved.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -19539,7 +19546,11 @@ namespace ts {
                         }
                     }
                     if (sourceFlags & TypeFlags.Substitution) {
-                        return isRelatedTo((source as SubstitutionType).substitute, (target as SubstitutionType).substitute, RecursionFlags.Both, /*reportErrors*/ false);
+                        if (result = isRelatedTo((source as SubstitutionType).baseType, (target as SubstitutionType).baseType, RecursionFlags.Both, /*reportErrors*/ false)) {
+                            if (result &= isRelatedTo((source as SubstitutionType).constraint, (target as SubstitutionType).constraint, RecursionFlags.Both, /*reportErrors*/ false)) {
+                                return result;
```
Comment (weswigham) [inline src/compiler/checker.ts:19551]: This is a meaningful break in behavior, right? Previously `type FilterNever<T> = T extends never ? T : never` would have allowed `FilterNever<A>` to be assignable to `FilterNever<B>` (where A and B are both type parameters), since `T & never` is just `never`, and eliminated the need to relate the type parameter part, no?

**Comment by ahejlsberg** [comment]
Latest commit fixes restrictive type parameters to appear to have no constraint instead of an `unknown` constraint. Evidently the distinction matters when obtaining constraints for distributive conditional types applied to such type parameters. With that fixed we can now resolve more substitution types to their base type, reducing the check time for the original repro down to 4.2s (better than 60% reduction).

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:19551]: This is in the code path for `identityRelation`, so hardly matters. In your particular example the types wouldn't relate anyway because the type parameters aren't identical.

Comment (weswigham) [reply src/compiler/checker.ts:19551]: That's what would technically make it a break, right? Previously this related substitutions only, so `A` sub `A & never` and `B` sub `B & never` both looked identically like `never`?

Comment (ahejlsberg) [reply src/compiler/checker.ts:19551]: Yeah, that's true. But they definitely shouldn't be related, so I guess this fixes a bug as well.

**Review by amcasey — COMMENTED** [review]
My high-level understanding is that, in the case of substitution types, it is commonly faster to deal with two intersected types separately than it is to deal with their normalized intersection.  Is there a more general version of this sort of lazy normalization where we do fast pre-tests against the constituent types?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -12344,7 +12344,7 @@ namespace ts {
                     return constraint && getBaseConstraint(constraint);
                 }
                 if (t.flags & TypeFlags.Substitution) {
-                    return getBaseConstraint((t as SubstitutionType).substitute);
+                    return getBaseConstraint(getSubstitutionIntersection(t as SubstitutionType));
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts:12347]: Probably not. The intersection itself will be cached by `getIntersectionType`, so all we'd save is the cache lookup.

**Comment by andrewbranch** [comment]
@typescript-bot pack this please and thank you

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
With the latest commits everything now looks good. All tests pass except for one DT case (more on that). Check time of the original repro is about 50% improved, and check time of `material-ui` is 3.5% improved.

The one DT failure is in `types/three/examples/jsm/nodes/shadernode/ShaderNode.d.ts`. The issue here is that our fix to `getRestrictiveTypeParameter` now causes the constraint of `OverloadedConstructorsOf<T>` to be a union of all the possible outcomes (correct) instead of just the first possible outcome (see comment [here](https://github.com/microsoft/TypeScript/pull/50397#issuecomment-1223247122)). That in turn reveals that `ConstructorUnion<T>` isn't a distributive type (which it ought to be) and therefore it doesn't get evaluated on constraints and thus doesn't remove `undefined` as expected. The easy fix is to change `ConstructorUnion<T>` to

```ts
type ConstructorUnion<T extends AnyConstructors> =
    | Exclude<T['a'], undefined>
    | Exclude<T['b'], undefined>
    | Exclude<T['c'], undefined>
    | Exclude<T['d'], undefined>
```

**Comment by jakebailey** [comment]
Given this was a regression in 4.8, are we going to backport it to a point release of 4.8?

**Comment by jakebailey** [comment]
Given this was a regression in 4.8, are we going to backport it to a point release of 4.8?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -17018,9 +17019,9 @@ namespace ts {
         }
 
         function getRestrictiveTypeParameter(tp: TypeParameter) {
-            return tp.constraint === unknownType ? tp : tp.restrictiveInstantiation || (
+            return !tp.constraint && !getConstraintDeclaration(tp) || tp.constraint === noConstraintType ? tp : tp.restrictiveInstantiation || (
                 tp.restrictiveInstantiation = createTypeParameter(tp.symbol),
-                (tp.restrictiveInstantiation as TypeParameter).constraint = unknownType,
+                (tp.restrictiveInstantiation as TypeParameter).constraint = noConstraintType,
```
Comment (weswigham) [inline src/compiler/checker.ts:17024]: I think you mentioned it in person, but remind me again: Why does this need to be `noConstraintType`? `AFAIK, `noConstraintType` should mostly just be used as a marker to make `getBaseConstraintOfType` return `undefined`, but a type parameter constrained to `unknown` and a type parameter without a constraint are supposed to be functionally identical nowadays. So if this change was required somewhere, I think it implies something is subtly broken. In any case, we should probably make `noConstraintType` an `unknown` variant at some point (since it's still an empty object), even if it's never supposed to actually be used as a type.

**Review by weswigham — APPROVED** [review]
A test would be nice, so something breaks if we ever decide it's better to flipflop the representation back, but I've thought this representation for a substitution type was nicer for awhile and just didn't have an excuse to change it, so I'm for this.

File: src/compiler/checker.ts (hunk 4 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:17024]: The one difference I an into is in `getConstraintOfDistributiveConditionalType`. It does nothing for type parameters declared without a constraint, but applies a distributive conditional type to a declared type parameter constraint, even if that constraint is `unknown`. Changing this would definitely be a breaking change.

Making matters worse, for a restrictive type parameter we used to jam in an `unknown` constraint even for a type parameter declared without a constraint--which effectively changed the observed constraint for a distributive conditional type.

**Comment by ahejlsberg** [comment]
> Given this was a regression in 4.8, are we going to backport it to a point release of 4.8?

It's a pretty esoteric break and there is a workaround [here](https://github.com/microsoft/TypeScript/issues/50290#issuecomment-1221331939). I'd prefer getting some bake time in the 4.9 branch before we release this.

**Comment by jakebailey** [comment]
> > Given this was a regression in 4.8, are we going to backport it to a point release of 4.8?
> 
> It's a pretty esoteric break and there is a workaround [here](https://github.com/microsoft/TypeScript/issues/50290#issuecomment-1221331939). I'd prefer getting some bake time in the 4.9 branch before we release this.

Sure, I'm just mirroring the ask in https://github.com/microsoft/TypeScript/issues/50290#issuecomment-1227860037

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts:17024]: Ew, icky. Distributive constraints behaving differently for `T` vs `T extends unknown` is definitely pretty bad - do we know which direction's behavior is better? Given the direction of this PR, I'm led to think we should adopt the unconstrained `T` behavior for a `T extends unknown`.
