### PR TITLE
Combine multiple overloads into a single contextual signature

### LINKED ISSUE #42504: Possible breaking change: assigning array to 1-tuple
# Bug Report

### 🔎 Search Terms

dom, tuple, assignability

### 🕗 Version & Regression Information

Repros in 4.2 Beta and nightly

- This changed between versions 4.1.3 and 4.2 beta

**Important caveat:** The code was originally building against 4.1 and had polyfills for types that are in lib.dom.d.ts in 4.2.

### ⏯ Playground Link

TS 4.1.3 with polyfills: [Playground](https://www.typescriptlang.org/play?ts=4.1.3#code/JYOwLgpgTgZghgYwgAgEoQM7AF4QPIBGG0AbtAMJwA2VBiA1sgN4BQyyAFBOFMJgFxpMOfEVLQAojwCeAbQC6AGmQB7MVDJRB6LLkLEN0AJSCSK4ABMA3CwC+LFqEixEKHSP3ioUsFGnM2ZCgIOAsVECp-MDgoAHMIMEEJKggAW24wG3Zg0PDI5ARwyHB0BETkABE8AFlSsHRQvAjpG3tHcGh4JCFdUQNNAPY1fogOaLiEpJT08BNkM0ss5ABXEGHxMZj48uS0jLmF60CLYAxCkBAIMo4D8yO2p07XHo91TQBJEAxokG7WbJCYWayAADlAVGAIdIQRBtMI9G9oEtLgB3TgIai0Bhw3qeQxQSg0OgIehzdwIkZQVoOCxXKgxFApMAvCleHGvSmfb5wX4QGztZxdFAAdVAYTR-yCgLy-nJfTZLPl+K5PyQ1JY52+UtxiKgyAAvMhUYq8ZoOBxZBk-PJ2az8T4-AojAaAHyDZBW6R2IxWIA)

TS 4.2 beta with re-declaration of lib.dom.d.ts interface: [Playground](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/JYOwLgpgTgZghgYwgAgEoQM7AF4QPIBGG0AbtAMJwA2VBiA1sgN4BQyyAFBOFMJgFxpMOfEVLQAojwCeAbQC6AGmQB7MVDJRB6LLkLEN0AJSCSK4ABMA3CwC+LFghUgMYZFGF71m5AF5kIBAA7kK6ogaaHByy3GBQ0vJGfgB8zGzIsfF2RlZAA)

### 💻 Code

```ts
interface ResizeObserverCallback {
  (entries: ResizeObserverEntry[], observer: ResizeObserver): void;
}

const resizeObserver = new ResizeObserver(([entry]) => {
  entry
});
```

### 🙁 Actual behavior

```
Argument of type '([entry]: [any]) => void' is not assignable to parameter of type 'ResizeObserverCallback'.
  Types of parameters '__0' and 'entries' are incompatible.
    Type 'ResizeObserverEntry[]' is not assignable to type '[any]'.
      Target requires 1 element(s) but source may have fewer.(2345)
```

### 🙂 Expected behavior

The fact that the repro depends on re-declaring a dom interface is suspicious, but the re-declaration appears to be identical, so it's not obvious to me why this error would be produced.

Also, note that the (as a result of sensible variance reasons), the lambda parameter is listed before the callback parameter on line 2 of the error and the types are in the _opposite_ order on line 3 of the error.  I found this confusing.

### PR DESCRIPTION
**Pull request by weswigham**
With this PR, we combine multiple overloads into a single contextual signature when `noImplcitAny` is set (for backwards compatibility, since otherwise these positions had type `any`). The rules for signature combining are similar to union signature combining, but swapping union/intersection rules where applicable; Either no generics, or identical generic lists, Parameters (and `this` parameters) union together, return types (and predicates) intersect (return types/predicates are likely visible via return type inference, so do need sensible rules).

With the caveat that this only changes our behavior when `noImplicitAny` is set, this:
Fixes #42559
Fixes #42504
Doesn't change #38625 - since the signatures in question have a mix of type parameters and no type parameters.
Doesn't change #35641 - there's no contextual typing involved; generic signature resolution has a similar drawback where it doesn't handle overloads which this PR does not touch.
Fixes [this comment](https://github.com/microsoft/TypeScript/issues/35501#issuecomment-566692617) though not the containing issue (which is moreso a dupe/precursor of #35641)

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot test this

**Comment by weswigham** [comment]
Perf is good, rwc looks good (1 change removing an implicit `any` exactly where this should), user tests look clean, and DT brought up one change which is somewhat interesting - a function contextually typed by a type like:
```
((match: { x: string; }) => void) | { (form: "NFC" | "NFD" | "NFKC" | "NFKD"): string; (form?: string | undefined): string; } | undefined
```
previously, that 2-overload union member would produce no contextual information (since it had two overloads), making the 1-overload union the only union member with a visible contextual signature. Now, both union members produce a signature, they aren't identical, and the contextual signature is dropped entirely. I can preserve our current behavior here (dropping the two-overload's contextual information), but I'm unsure if we should? Certainly, we feel justified giving no contextual type for
```
((match: { x: string; }) => void) | { (form: "NFC" | "NFD" | "NFKC" | "NFKD"): string; } | undefined
```
so why should the addition of an overload spoil that?

**Comment by weswigham** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -24924,16 +24937,102 @@ namespace ts {
             }
         }
 
+        function getIntersectedSignatures(signatures: readonly Signature[]) {
+            return !getStrictOptionValue(compilerOptions, "noImplicitAny") ? undefined : reduceLeft(signatures, (left, right) => left === right || !left ? left : (!!left.typeParameters && !!right.typeParameters && compareTypeParametersIdentical(left.typeParameters, right.typeParameters)) || (!left.typeParameters && !right.typeParameters) ? combineSignaturesOfIntersectionMembers(left, right) : undefined, signatures[0]);
```
Comment (sandersn) [inline src/compiler/checker.ts:24941]:
```suggestion
            return getStrictOptionValue(compilerOptions, "noImplicitAny")
                : reduceLeft(
                    signatures,
                    (left, right) =>
                        left === right || !left ? left
                        : compareTypeParametersIdentical(left.typeParameters, right.typeParameters) ? combineSignaturesOfIntersectionMembers(left, right)
                        : undefined)
                ? undefined;
```

1. rely on reduceLeft's `initial` behaviour to do the right thing
2. invert getStrictOptionValue
3. Simplify call to compareTypeParametersIdentical by pushing some code in there.

Note that this relies on pushing the both-or-neither-defined check down into compareTypeParametersIdentical

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -24924,16 +24937,102 @@ namespace ts {
...
+        }
+
+        function combineIntersectionThisParam(left: Symbol | undefined, right: Symbol | undefined, mapper: TypeMapper | undefined): Symbol | undefined {
+            if (!left || !right) {
+                return left || right;
+            }
+            // A signature `this` type might be a read or a write position... It's very possible that it should be invariant
+            // and we should refuse to merge signatures if there are `this` types and they do not match. However, so as to be
+            // pessimistic when contextual typing, for now, we'll union the `this` types.
```
Comment (sandersn) [inline src/compiler/checker.ts:24950]: what would cause us to change this? (not a big fan of 'for now'-style comments because they don't have enough context with them)

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -24924,16 +24937,102 @@ namespace ts {
...
+                restParamSymbol.type = createArrayType(getTypeAtPosition(shorter, longestCount));
+                if (shorter === right) {
+                    restParamSymbol.type = instantiateType(restParamSymbol.type, mapper);
+                }
+                params[longestCount] = restParamSymbol;
+            }
+            return params;
+        }
+
+        function combineSignaturesOfIntersectionMembers(left: Signature, right: Signature): Signature {
```
Comment (sandersn) [inline src/compiler/checker.ts:25001]: this should probably come before `combineIntersectionParameters` and `combineIntersectionThisParam`

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -24924,16 +24937,102 @@ namespace ts {
...
+                declaration,
+                typeParams,
+                thisParam,
+                params,
+                /*resolvedReturnType*/ undefined,
+                /*resolvedTypePredicate*/ undefined,
+                minArgCount,
+                (left.flags | right.flags) & SignatureFlags.PropagatingFlags
+            );
+            result.compositeKind = TypeFlags.Intersection;
```
Comment (sandersn) [inline src/compiler/checker.ts:25022]: stupid efficiency question: Is it more efficient to have `createSignature` set these? (I'm guessing not, since probably composite signatures (1) are rare (2) have their own internal class.)

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -24924,16 +24937,102 @@ namespace ts {
...
+            // pessimistic when contextual typing, for now, we'll union the `this` types.
+            const thisType = getUnionType([getTypeOfSymbol(left), instantiateType(getTypeOfSymbol(right), mapper)]);
+            return createSymbolWithType(left, thisType);
+        }
+
+        function combineIntersectionParameters(left: Signature, right: Signature, mapper: TypeMapper | undefined) {
+            const leftCount = getParameterCount(left);
+            const rightCount = getParameterCount(right);
+            const longest = leftCount >= rightCount ? left : right;
+            const shorter = longest === left ? right : left;
```
Comment (sandersn) [inline src/compiler/checker.ts:24959]: could they be named longest/shortest or longer/shorter?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -24924,16 +24937,102 @@ namespace ts {
...
+                const unionParamType = getUnionType([longestParamType, shorterParamType]);
+                const isRestParam = eitherHasEffectiveRest && !needsExtraRestElement && i === (longestCount - 1);
+                const isOptional = i >= getMinArgumentCount(longest) && i >= getMinArgumentCount(shorter);
+                const leftName = i >= leftCount ? undefined : getParameterNameAtPosition(left, i);
+                const rightName = i >= rightCount ? undefined : getParameterNameAtPosition(right, i);
+
+                const paramName = leftName === rightName ? leftName :
+                    !leftName ? rightName :
+                    !rightName ? leftName :
+                    undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts:24982]: uhhhhhhhhh, why not just `leftName || rightName`? I'm not even sure it's observable, but even if it is, some name is better than `arg0`.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:24950]: also: `this` is basically a parameter, so it should union just like the other parameters.

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks pretty good. I have a couple of questions and a lot of minor style suggestions.

File: tests/baselines/reference/redefineArray.types [hunk 7]
```diff
@@ -1,8 +1,8 @@
 === tests/cases/compiler/redefineArray.ts ===
 Array = function (n:number, s:string) {return n;};
->Array = function (n:number, s:string) {return n;} : (n: number, s: string) => number
+>Array = function (n:number, s:string) {return n;} : <T>(n: number, s: string) => number
```
[the remark this answers is not in the document]
Comment (weswigham) [reply tests/baselines/reference/redefineArray.types:3]: `Array`'s call signature has type parameters (and multiple overloads, hence why we only now pick it up), so our contextual signature logic says to persist those type parameters onto the inferred signature (so they can be inferred and used at the parameter types). That type parameter just happens to end up unused, since the parameters are all annotated with types that override the inferred ones. Specifically, it has the signatures:
```
    (arrayLength?: number): any[];
    <T>(arrayLength: number): T[];
    <T>(...items: T[]): T[];
```
so it used to be that you'd get no contextual signature whatsoever, whereas now the contextual signature is something like `<T>(arrayLengthOrItem?: number | T, ...items: T[]): T[]`. Technically any time a contextually typed signature has all the parameter types specified, we could probably omit these type parameters. Probably. You can see similar behavior in the `types` baselines today with only one overload and something like:
```ts
// @strictFunctionTypes: false
interface MyCallable {
    <T>(a: T | number): T[];
}

const x: MyCallable = function (arg: number) { return null as any };
```
(`strictFunctionTypes` has to be off for the assignment to succeed, in both cases). I don't know _why_, but we also only do this for _function expressions_ and not _arrow functions_... that's probably indicative of some bug somewhere; but it's a preexisting one.

File: tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.errors.txt [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+        validate: string | RegExp | Validate;
+        normalize?: (match: {x: string}) => void;
+    }
+    
+    type Rule = string | FullRule;
+    
+    const obj: {field: Rule} = {
+        field: {
+            validate: (_t, _p, _s) => false,
+            normalize: match => match.x,
```
[the remark this answers is not in the document]
Comment (weswigham) [reply tests/baselines/reference/contextualOverloadListFromUnionWithPrimitiveNoImplicitAny.errors.txt:17]: This is a test capturing [this change](https://github.com/microsoft/TypeScript/pull/42620#issuecomment-773558828) I describe from DT - that comment contains the explanation, and is the bulk of what I was trying to discuss at the design meeting.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -12045,13 +12049,17 @@ namespace ts {
                     findIndex(signature.parameters, p => p.escapedName === parameterName.escapedText), type);
         }
 
+        function getUnionOrIntersectionType(types: Type[], kind: TypeFlags | undefined, unionReduction?: UnionReduction) {
+            return kind !== TypeFlags.Intersection ? getUnionType(types, unionReduction) : getIntersectionType(types);
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:12053]: I intentionally made all the comparisons `kind !== TypeFlags.Intersection` this was the `kind` being `undefined` is synonymous with `Union` (to preserve the existing structure where there is no `kind`). Now, I don't _intentionally_ leave `kind` `undefined` anywhere, but _just in case_, I've written the comparisons to be resilient to it.

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -24830,7 +24843,7 @@ namespace ts {
                     }
                     results.push(propType);
                 }
-                return getIntersectionType(results);
+                return getIntersectionType(results); // Same result for both union and intersection signatures
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:24846]: The _actual_ surprising thing _is_ that nothing changed here. This code path handled union composite signatures... and now we're handling intersection composite signatures _in the same way_ (rather than inverting anything), which is _odd_.  The reason for that is explained in this comment (namely that for compat reasons we intentionally do "the wrong thing" for union signatures here, which happens to be "the right thing" for intersection signatures)

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:24950]: > so it should union just like the other parameters.

And so we are, the comment is just an inversion of the comment that already exists in `combineUnionThisParam` which does the opposite.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts:25022]: `createSignature` sets them to `undefined` already, along with every other optional field on signatures~

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts:24959]: This follows the same terminology we already use in `combineUnionParameters`, which `combinedIntersectionParameters` _really closely_ mirrors.

File: src/compiler/checker.ts (hunk 6 above)
Comment (weswigham) [reply src/compiler/checker.ts:24982]: Because that's what we merged for `combineUnionParameters` in https://github.com/microsoft/TypeScript/pull/32056 :V

Also, "some name is better than arg0" isn't really true. Names carry semantic meaning, so let's say you have `(index: number) => any` and `(object: Whatever): any ` - calling the result `index` where's it's type is `number | Whatever` has the potential to be misleading. Particularly problematic is when the types are the _same_, but semantically different, like
`(length: number): any[]` and `(firstElement: number): any[]` - yeah, `number` is the type of both, but there're not semantically the same! So calling both "length" or "firstElement" would be dead wrong. Now, I had a _super old_ version of this that concatenated the names in cases like this, to `lengthOrFirstElement`, but that was shot down as too easily producing names that are unwieldy as unions grow. And thus, the preference for `arg0` was born. It carries no information, thus you can draw no (potentially inaccurate) conclusion as to the usage of the parameter.

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts:25001]: This is in the same order that the very similar `combineUnionParameters` and `combineUnionThisParam` are~

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [reply src/compiler/checker.ts]: If @dragomirtitian cares enough to fix it, that's good enough for me. =)

File: tests/baselines/reference/redefineArray.types (hunk 7 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply tests/baselines/reference/redefineArray.types:3]: OK, I figured it was pre-existing.

**Review by sandersn — APPROVED** [review]
Looks good to me...with the caveat that the minor style issues that stem from combineUnionParameters precedent should be fixed there *and* here in a followup PR =P

**Comment by weswigham** [comment]
@DanielRosenwasser I assume you want this to hit 4.3 and not 4.2 at this point - will you LMK when I should merge?

**Comment by jcalz** [comment]
[SO Question](https://stackoverflow.com/q/71096084/2887218) asks about this strange behavior:

```ts
interface Ovld {
    (): void;
    (x: string): void;
}
const oNo: Ovld = x => { }
// error! Type '(x: string) => void ' is not assignable to type 'Ovld'.

const ok: Ovld = (x?: string) => { } // okay
```
[Playground link](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgPIDcA2ATZBvAKGWOQAoBKALmXQHthsBuIk0gD2oGcwpQBzKjXpMCAXwIJaIbsloA5WtQw5kAXmRs1APnzJxAen3JoUWlACEyACoBPAA4oA5Oy49+5bUIbJHyYJ2QQWjBkOE5OYD4QOAAjTBQwWmQweydlbEcAOlIAJgBmHJzyAgkpGVoAayUsXHV2AH5XXhABTzw9ZENZCrgbIA)

Looks like the contextual signature isn't what I'd expect in the face of differing parameter list lengths.  Wondering if this behavior is intended or unintended as per this PR, and if there should be a new issue filed about it.

**Comment by forresthopkinsa** [comment]
For the sake of search, this also fixes an unmentioned bug (though somewhat similar to the comment from 35641):

```ts
const obj = {
    a: ['x'],
    b: ['y'],
} as const;

type Obj = typeof obj;
type Key = keyof Obj;
type Val = Obj[Key];
type Item = Val[number];

const keys = Object.keys(obj) as Key[];

keys.forEach(key => {
    obj[key].forEach(item => { // Parameter 'item' implicitly has an 'any' type. (7006)
        console.log(item);
    });
    
    for (const item of obj[key]) { // no error, type inferred correctly
        console.log(item);
    }
});
```

[Playground](https://www.typescriptlang.org/play?strictPropertyInitialization=false&target=5&module=1&inlineSourceMap=true&inlineSources=true&ts=4.2.3#code/MYewdgzgLgBCBGArGBeGBvAUDHMCGAXDANoDkAHqQLoA02u8RZAntXQL74QyiRQDcmTFGYAHAKYwA8klQwREkADM4SQQskBpcczkBrHculrhYyQDU8AGzkzExbcyrqzMAJJRxAWzmWrxMABXL3hxACdnIV5oGANmbjQ7cWAoADo4iAAKBEQASi4YR2JIzAzUpRAwgFE8YAALTLjUAD4Mehwc4jiqcsqa+syAS08fFFasXEmecAgQK3FUqxAAcyGR3MFJ9g32mF2KsJhM6Nhh7zgVTu78iamcaLmFpdWzrx2tzG3+IA)
