### PR TITLE
Narrowing from truthy unknown to object

### LINKED ISSUE #36870: Truthy check loses effect based on position in "&&" chain
I have three checks in a "&&" chain.  The order of the first two checks seems to have an effect on whether I can perform the third check.  Am I missing something?

```typescript
function f1(x: unknown): any {
    return x && typeof x === 'object' && x.hasOwnProperty('x');
    //                                   ^  TS reports error: Object is possibly 'null'
}

function f2(x: unknown): any {
    return typeof x === 'object' && x && x.hasOwnProperty('x');  // no error
}
```

Reproduced in 3.8-beta ([playground link](http://www.typescriptlang.org/play/?ts=3.8-Beta#code/GYVwdgxgLglg9mABMAjACgB4C5HgNZhwDuYAlDgIZgCeiA3gFCLOIBOAplCK0hogGT9EUagAd2cYIj4BeOYgDkcAEYArdtAUChGAHQALCgGcA8iQAKrOONYi0CjAtIBuJiwD07lt5++--5gA9ZgAVAGU2dlE4WyNEdlYrVhwTNQ0oRBg46KMjGGUAG1oFMBACgoUGAF8GBlBIWARkACZMHHxCEnJEKlpGbw4uHmExCSlZeSU0zW1pWb1DUwsrGzsHJ2dmT0RCeMSY6qA))

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR, given a variable `x` of type `unknown`, the pattern `x && typeof x === 'object'` narrows `x` to `object`. Previously we'd narrow to `object | null` because a truthiness check applied to `unknown` is still `unknown` (and `unknown` includes `null`).

Note that this is a targeted fix for a relatively common pattern. In an ideal world we'd be able to accurately represent types that are known to be truthy, but we currently don't have that ability.

Fixes #36870.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20343,15 +20349,22 @@ namespace ts {
                 if (type.flags & TypeFlags.Any && literal.text === "function") {
                     return type;
                 }
+                if (assumeTrue && type.flags & TypeFlags.Unknown && literal.text === "object") {
+                    // The pattern x && typeof x === 'object', where x is of type unknown, narrows x to type object.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Would be nice to note here that you don't need to check both directions because the `typeof x === "object" && x` is narrowed as two separate steps. I don't think that would be obvious to a casual reader.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -18947,6 +18947,12 @@ namespace ts {
             return false;
         }
 
+        function containsTruthyCheck(source: Node, target: Node) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: A comment here that this specifically deals the binary operator precedence. would also be useful. The implementation looks good here, but this function is named something much more general than it actually is and that's going to be confusing in the future.
