### PR TITLE
Fix "Cannot find name 'global'. Did you mean 'global'?"

### LINKED ISSUE #42209: ﻿Incorrect suggestion: "Cannot find name 'global'. Did you mean 'global'?"
# Bug Report

### 🔎 Search Terms

"declare global", "error suggestion", "cannot find name", "did you mean"

### 🕗 Version & Regression Information

This is the behavior in every version I tried (3.3.3-4.1.3 and 4.2.0-dev.20210104), and I reviewed the FAQ for entries about error messages.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4CgAmwDGAbAhlYOAc2wgCNdtE5MIA7AZ3hAC45c6BPOVE8ygHQggA)

### 💻 Code

```ts
export {}
declare global { const x: any }
global.x
```

### 🙁 Actual behavior

The error message is `Cannot find name 'global'. Did you mean 'global'? ts(2552)`. This is a legit error, but the suggestion is wrong.

### 🙂 Expected behavior

An error message that doesn't have an incorrect suggestion. Perhaps just `Cannot find name 'global'.` with no suggestion at all?

### PR DESCRIPTION
**Pull request by mkantor**
Avoid suggesting the `global` keyword (from global scope augmentation declarations) as typo fix when resolving names.

Fixes #42209.

### CODE REVIEW

**Comment by mkantor** [comment]
As I noted in [a comment on #42209](https://github.com/microsoft/TypeScript/issues/42209#issuecomment-754921935) this is my first foray into the compiler so I'm not sure this is the best approach. This check could also happen inside `getSuggestedSymbolForNonexistentSymbol`, for example, or maybe there's a more general notion of "things that shouldn't be suggested for value positions" that should be captured somewhere, or maybe some other fix I haven't considered.

Let me know!

File: tests/cases/compiler/spellingSuggestionGlobal1.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export {}
+declare global { const x: any }
+global.x // should not suggest `global` (GH#42209)
```
Comment (ExE-Boss) [inline tests/cases/compiler/spellingSuggestionGlobal1.ts:3]: In this case, it should probably suggest `globalThis`.

Comment (mkantor) [reply tests/cases/compiler/spellingSuggestionGlobal1.ts:3]: Did you miss [my reply](https://github.com/microsoft/TypeScript/issues/42209#issuecomment-754903122) after you suggested that on the issue?

[`globalThis.x` is not valid here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4CgAmwDGAbAhlYOAc2wgCNdtE5MIA7AZ3hAC45c6BPOVE8ygCoALAJYMAdCCA).

Comment (ExE-Boss) [reply tests/cases/compiler/spellingSuggestionGlobal1.ts:3]: It is valid when you do:
```ts
declare global { var x: any }
```

Comment (mkantor) [reply tests/cases/compiler/spellingSuggestionGlobal1.ts:3]: Let's make sure we're on the same page:

**Are you saying `spellingSuggestionGlobal1.ts` (as written, with `const x`) should produce the error message `Cannot find name 'global'. Did you mean 'globalThis'?`?**

If so, I disagree. Users will follow that suggestion and change `global.x` to `globalThis.x`, then get another error (`Property 'x' does not exist on type 'typeof globalThis'.`), then be confused/frustrated and have to research why it doesn't work, then probably end up ignoring the suggestion anyway and write `x` instead of `globalThis.x`.

**Or are you saying that in situations where `x` is a known property of `globalThis` and the user writes `global.x` that it would be nice to say `Cannot find name 'global'. Did you mean 'globalThis'?`?**

If so, I agree, but unfortunately that would be tricky to implement (unless I'm missing something). I'd bet that this situation occurs rarely in the wild, so it might not be worth the complexity cost to maintain a dedicated suggestion for it. I could be wrong, though.

In any case it seems orthogonal to the bugfix in this pull request. Currently [if you write something like `global.Math` the error message won't suggest `globalThis`](https://www.typescriptlang.org/play?#code/OYGw9gRghiB0CyUAuALIA), either.

---

Regardless, I should add a test case that uses `var` in the global declaration. I'll push a commit for that soon.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2028,6 +2028,10 @@ namespace ts {
                         let suggestion: Symbol | undefined;
                         if (suggestedNameNotFoundMessage && suggestionCount < maximumSuggestionCount) {
                             suggestion = getSuggestedSymbolForNonexistentSymbol(originalLocation, name, meaning);
+                            // Avoid suggesting "global" if it refers to a global scope augmentation declaration.
+                            if (suggestion && suggestion.valueDeclaration && isAmbientModule(suggestion.valueDeclaration) && isGlobalScopeAugmentation(suggestion.valueDeclaration)) {
+                                suggestion = undefined;
+                            }
                             if (suggestion) {
```
Comment (sandersn) [inline src/compiler/checker.ts:2035]: Since `getSuggestedLibForNonExistentName` doesn't make sense for `global`, I would just invert the predicate and move it here. Or possibly `return undefined`.

Either way, I think it would be better to extract the predicate to its own variable -- that way you can probably delete the comment on the first line of the change.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -2028,6 +2028,10 @@ namespace ts {
                         let suggestion: Symbol | undefined;
                         if (suggestedNameNotFoundMessage && suggestionCount < maximumSuggestionCount) {
                             suggestion = getSuggestedSymbolForNonexistentSymbol(originalLocation, name, meaning);
+                            // Avoid suggesting "global" if it refers to a global scope augmentation declaration.
+                            if (suggestion && suggestion.valueDeclaration && isAmbientModule(suggestion.valueDeclaration) && isGlobalScopeAugmentation(suggestion.valueDeclaration)) {
```
[the remark this answers is not in the document]
Comment (mkantor) [reply src/compiler/checker.ts:2032]: > you don't need `isAmbientModule` since it's implied by `isGlobalScopeAugmentation`

[`isGlobalScopeAugmentation` takes a `ModuleDeclaration`](https://github.com/microsoft/TypeScript/blob/9d286a21aef56a2d9687198daa23ac224d10ad37/src/compiler/utilities.ts#L748), so `isAmbientModule` is there to narrow `suggestion.valueDeclaration`.

> is it possible to get other ambient modules as suggestions? They all have string names, so I suspect not.

I don't think so. I tried and failed to make it happen, anyway.

File: src/compiler/checker.ts (hunk 2 above)
Comment (mkantor) [reply src/compiler/checker.ts:2035]: It's true that `getSuggestedLibForNonExistentName` doesn't make sense for `global`, but execution needs to fall through to the `else` case on line 2049/2053 in order to get any error message at all.

I don't like overwriting `suggestion` in-place either, though. Maybe it'd be better to duplicate the `error` call up here?

```typescript
const isGlobalScopeAugmentationDeclaration = suggestion && suggestion.valueDeclaration && isAmbientModule(suggestion.valueDeclaration) && isGlobalScopeAugmentation(suggestion.valueDeclaration);
if (isGlobalScopeAugmentationDeclaration) {
    if (nameArg) {
        error(errorLocation, nameNotFoundMessage, diagnosticName(nameArg));
    }
}
else if (suggestion) {
    // ...
}
```

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -2028,6 +2028,10 @@ namespace ts {
                         let suggestion: Symbol | undefined;
                         if (suggestedNameNotFoundMessage && suggestionCount < maximumSuggestionCount) {
                             suggestion = getSuggestedSymbolForNonexistentSymbol(originalLocation, name, meaning);
+                            const isGlobalScopeAugmentationDeclaration = suggestion && suggestion.valueDeclaration && isAmbientModule(suggestion.valueDeclaration) && isGlobalScopeAugmentation(suggestion.valueDeclaration);
```
Comment (mkantor) [inline src/compiler/checker.ts:2031]: In hindsight I wish I'd named this `suggestionIs...`, but it's already obnoxiously long.

Maybe `suggestionIsGlobalDeclaration`? `suggestionIsGlobalModule`? Something else?

File: src/compiler/checker.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/checker.ts:2032]: oh, makes sense. I didn't load this code in an editor.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [reply src/compiler/checker.ts:2031]: in context, I think this is a pretty good name.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:2035]: ooh, I forgot that there weren't any other `error` calls afterward. I guess it's better to keep it the way it is.

**Review by sandersn — APPROVED** [review]
