### PR TITLE
[Transform]: fix emit __extends within system.registry

### LINKED ISSUE #7912: [Transforms] `System.register` doesn't wrap around emitted `__extends` variable
**Expected**:

```js
//// [bar.js]
System.register(['./foo'], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
    var foo_1;
    var Bar;
    return {
        setters:[
            function (foo_1_1) {
                foo_1 = foo_1_1;
            }],
        execute: function() {
            Bar = (function (_super) {
                __extends(Bar, _super);
                function Bar() {
                    _super.apply(this, arguments);
                }
                return Bar;
            }(foo_1.Foo));
            exports_1("Bar", Bar);
        }
    }
});
```

**Actual**:

```js
//// [bar.js]
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
System.register(["./foo"], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var foo_1, Bar;
    return {
        setters: [
            function (foo_1_1) {
                foo_1 = foo_1_1;
            }
        ],
        execute: function () {
            Bar = (function (_super) {
                __extends(Bar, _super);
                function Bar() {
                    _super.apply(this, arguments);
                }
                return Bar;
            }(foo_1.Foo));
            exports_1("Bar", Bar);
        }
    };
});
```

Failed tests:
* tests\cases\compiler\systemModuleWithSuperClass.ts

### PR DESCRIPTION
**Pull request by yuit**
fix #7912

### CODE REVIEW

File: src/compiler/transformers/module/system.ts [hunk 1]
```diff
@@ -130,6 +131,10 @@ namespace ts {
                     )
                 )
             ]);
+
+            // Reset the sourcefile's nodeFlag to not emit helpers because we already set one in the body
+            setNodeEmitFlags(updated, ~NodeEmitFlags.EmitEmitHelpers & getNodeEmitFlags(updated));
```
Comment (mhegazy) [inline src/compiler/transformers/module/system.ts]: can we pass this as an argument to updateSourceFile instead?

Comment (yuit) [inline src/compiler/transformers/module/system.ts]: yes

File: src/compiler/transformers/module/system.ts [hunk 2]
```diff
@@ -120,6 +121,8 @@ namespace ts {
             );
 
             // Write the call to `System.register`
+            // Reset the source-file's nodeFlag to not emit helpers because we already set one in the body
```
Comment (DanielRosenwasser) [inline src/compiler/transformers/module/system.ts]: `Reset the source-file's nodeFlag` -> `Clear the emit-helpers flag for later passes since we'll have already used it in the module body`

File: src/compiler/transformers/module/system.ts [hunk 3]
```diff
@@ -120,6 +121,8 @@ namespace ts {
             );
 
             // Write the call to `System.register`
+            // Reset the source-file's nodeFlag to not emit helpers because we already set one in the body
+            // So the helper will be emit at the correct position instead of at the top of the source-file
```
Comment (DanielRosenwasser) [inline src/compiler/transformers/module/system.ts]: Consider creating a variable named `updatedNodeFlags` to keep this comment and the new flags nearby each other.

**Comment by DanielRosenwasser** [comment]
Other than my comment, looks like a nice clean change :cookie:
