### PR TITLE
Fix discriminated unions with primtive types

### LINKED ISSUE #10257: Regression in discriminated unions unioned with primitive
From `master`
```ts
interface Foo {
  kind: "foo";
  name: string;
}
interface Bar {
  kind: "bar";
  length: string;
}

let x: string | Foo | Bar = <any>undefined;
if(typeof x === 'string') {

} else {
  switch(x.kind) {
    case 'foo':
      console.log(x.name); // <-- Error, Property 'name' does not exist on type 'Foo | Bar'.
  }
}
```
Compiles without error in 2.1.0-dev.20160729

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #10257.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8172,9 +8187,26 @@ namespace ts {
         }
 
         function filterType(type: Type, f: (t: Type) => boolean): Type {
-            return type.flags & TypeFlags.Union ?
-                getUnionType(filter((<UnionType>type).types, f)) :
-                f(type) ? type : neverType;
+            if (!(type.flags & TypeFlags.Union)) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: The rewrite here makes sense (I'm assuming this is a perf thing?) but deserves a comment as to why it isn't using the existing filter code so that a maintainer doesn't just undo this change later.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -7848,17 +7849,24 @@ namespace ts {
...
-                    if (prop && prop.flags & SymbolFlags.SyntheticProperty) {
-                        if ((<TransientSymbol>prop).isDiscriminantProperty === undefined) {
-                            (<TransientSymbol>prop).isDiscriminantProperty = !(<TransientSymbol>prop).hasCommonType &&
-                                isUnitUnionType(getTypeOfSymbol(prop));
-                        }
-                        return (<TransientSymbol>prop).isDiscriminantProperty;
+            if (type && type.flags & TypeFlags.Union) {
+                let prop = getPropertyOfType(type, name);
+                if (!prop) {
+                    // The type may be a union that includes nullable or primtive types. If filtering
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Spelling (primtive => primitive)

**Comment by RyanCavanaugh** [comment]
:+1:

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Yes, it is an optimization to avoid doing any work if the filter function returns true for all constituents. But now that you mention it, it would make more sense to push the optimization into the `filter` function itself. Similar to how `concatenate` doesn't allocate a new array unless it has to, so could `filter` just return the argument array when the predicate is true for all elements.
