### PR TITLE
moduleDetection: auto makes cjs/cts files parse as modules, and ...

### LINKED ISSUE #49207: `.cts` files are should not share the same top-level scope
# Bug Report

**NOTE**: There are already multiple (open or closed) issues about this topic. However, this issue is specifically about the behavior in `.cts` files and not in `.ts` files.

`.ts` files disallow using top-level block-scoped variables with the same name because they would conflict when loaded with a `<script>` tag.

`.cts` files currently have the same restriction, however:
- This extension is [explicitly documented](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#new-file-extensions) as referring to CommonJS files. CommonJS doesn't share a single top-level scope, because every file is wrapped in a function. This means that top-level variables with the same name will not conflict.
- When using CommonJS files, it's common to use the same variable name when importing the same dependency in multiple files. This error makes it impossible to do so.

For these reasons, I think that this restriction should be removed.

A real word example: I'm updating `typescript` to 4.7 in the Babel repository, and I hoped to be able to convert our remaining JavaScript files to TypeScript. They are still JS because we needed to use the `.cjs` extension: https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser/src. However, most of those files use the same variables names to import other files, so I'm unable to do so.

### 🔎 Search Terms

cts top-level Cannot redeclare block-scoped variable

### 🕗 Version & Regression Information

- Tested in TS4.7, where `.cts` has been introduced

### ⏯ Playground Link

n/a (it requires multiple files)

### 💻 Code

`file1.cts`:
```ts
const { getVisitorKeys } = require("./ast-info.cjs");
```

`file2.cts`:
```ts
const { getVisitorKeys } = require("./ast-info.cjs");
```

### 🙁 Actual behavior

```
eslint/babel-eslint-parser/src/worker/maybeParse.cts:3:25 - error TS2451: Cannot redeclare block-scoped variable 'getVisitorKeys'.

3 const { getVisitorKeys } = require("./ast-info.cjs");
          ~~~~~~~~~~~~

  eslint/babel-eslint-parser/src/worker/handle-message.cts:3:25
    3 const { getVisitorKeys } = require("./ast-info.cjs");
              ~~~~~~~~~~~~
    'getTokLabels' was also declared here.
```

### 🙂 Expected behavior

No error

### PR DESCRIPTION
**Pull request by weswigham**
`module: node` sets `moduleDetection: force`, per our discussion at yesterday's design meeting.

Fixes #49207

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Nice, no API change

**Comment by weswigham** [comment]
Does @DanielRosenwasser want @typescript-bot cherrypick this into release-4.7 ?

**Comment by robpalme** [comment]
Today, if a user has sloppy-mode CJS files, they can use `"alwaysStrict: false"` to ensure the emit remains non-strict to preserve semantics.

Does that escape hatch still work after this change?  Should we have a baseline test to check this case?

(I'm not sure how much to care about this scenario - mostly I'm just checking that any changes here are intentional).

File: tests/cases/conformance/node/allowJs/nodeModulesAllowJsExportlessJsModuleDetectionAuto.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// @module: node16,nodenext
+// @allowJs: true
+// @outDir: ./out
+// @moduleDetection: auto
+// @filename: foo.cjs
```
Comment (sheetalkamat) [inline tests/cases/conformance/node/allowJs/nodeModulesAllowJsExportlessJsModuleDetectionAuto.ts:5]: Does this also need change to `isExternalOrCommonJsModule` i think during incremental buildInfo doesnt mark bar.js as affecting global scope and that is a bug ?

**Comment by weswigham** [comment]
Yeah - if you set moduleDetection to legacy you get our old extension-ignorant behavior.

File: tests/cases/conformance/node/allowJs/nodeModulesAllowJsExportlessJsModuleDetectionAuto.ts (hunk 1 above)
Comment (weswigham) [reply tests/cases/conformance/node/allowJs/nodeModulesAllowJsExportlessJsModuleDetectionAuto.ts:5]: Afaik that just reads the two marker fields, which are all that get set to determine module-ness.

Comment (sheetalkamat) [reply tests/cases/conformance/node/allowJs/nodeModulesAllowJsExportlessJsModuleDetectionAuto.ts:5]: can you add test and ensure that bar.js will be marked as affects global scope and foo.cjs as module so no affectsGlobalScope in buildInfo. I am pretty certain that it is broken right now.
