### PR TITLE
fix(51225): Go-to-definition on case or default should jump to the containing switch statement if available.

### LINKED ISSUE #51225: Go-to-definition on `case` or `default` should jump to the containing `switch` statement if available.
```ts
/*END*/switch (null) {
  /*START*/case null: break;
}
```

```ts
/*END*/switch (null) {
  /*START*/default: break;
}
```

Those should work.

The following should not have issues.

```ts
export /*a*/default {}
```

```ts
export default { /*a*/case }
/*b*/default;
/*c*/case 42;
```

### PR DESCRIPTION
**Pull request by sviat9440**
Fixes #51225

### CODE REVIEW

**Comment by sviat9440** [comment]
@microsoft-github-policy-service agree [company="IE Zaytsev Svyatoslav Vladimirovich"]

**Comment by sviat9440** [comment]
@microsoft-github-policy-service agree agree company="IE Zaytsev Svyatoslav Vladimirovich"

**Comment by sviat9440** [comment]
@microsoft-github-policy-service agree

**Comment by sviat9440** [comment]
@microsoft-github-policy-service agree

File: src/services/goToDefinition.ts [hunk 1]
```diff
@@ -32,6 +32,13 @@ namespace ts.GoToDefinition {
             return functionDeclaration ? [createDefinitionFromSignatureDeclaration(typeChecker, functionDeclaration)] : undefined;
         }
 
+        if ([SyntaxKind.CaseKeyword, SyntaxKind.DefaultKeyword].indexOf(node.kind) !== -1) {
+            const switchStatement = findAncestor(node.parent, n => n.kind === SyntaxKind.SwitchStatement) as SwitchStatement | undefined;
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:36]:
```suggestion
            const switchStatement = findAncestor(node.parent, isSwitchStatement);
```

File: src/services/goToDefinition.ts [hunk 2]
```diff
@@ -32,6 +32,13 @@ namespace ts.GoToDefinition {
             return functionDeclaration ? [createDefinitionFromSignatureDeclaration(typeChecker, functionDeclaration)] : undefined;
         }
 
+        if ([SyntaxKind.CaseKeyword, SyntaxKind.DefaultKeyword].indexOf(node.kind) !== -1) {
```
Comment (RyanCavanaugh) [inline src/services/goToDefinition.ts:35]:
```suggestion
        if (node.kind === SyntaxKind.CaseKeyword || node.kind === SyntaxKind.DefaultKeyword) {
```

File: src/services/goToDefinition.ts [hunk 3]
```diff
@@ -510,4 +517,22 @@ namespace ts.GoToDefinition {
                 return false;
         }
     }
+
+    function createDefinitionInfoFromSwitchStatement(statement: SwitchStatement): DefinitionInfo {
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:521]: Maybe we just need a `createDefinitionInfoFromStatement` since we don't need to make this specific to any keyword.

File: src/services/goToDefinition.ts [hunk 4]
```diff
@@ -510,4 +517,22 @@ namespace ts.GoToDefinition {
                 return false;
         }
     }
+
+    function createDefinitionInfoFromSwitchStatement(statement: SwitchStatement): DefinitionInfo {
+        const switchKeyword = find(statement.getChildren(), n => n.kind === SyntaxKind.SwitchKeyword);
+        const sourceFile = statement.getSourceFile();
+        return {
+            fileName: sourceFile.fileName,
+            textSpan: createTextSpanFromNode(switchKeyword!),
```
[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/services/goToDefinition.ts:526]: Actually, `createTextSpanFromNode` takes an optional `sourceFile`. Pass that in so it avoids a double-traversal.

```suggestion
            textSpan: createTextSpanFromNode(switchStatement, sourceFile),
```

File: src/services/goToDefinition.ts (hunk 3 above)
Comment (sviat9440) [reply src/services/goToDefinition.ts:521]:
```

File: src/services/goToDefinition.ts [hunk 5]
```diff
@@ -32,6 +32,13 @@ namespace ts.GoToDefinition {
             return functionDeclaration ? [createDefinitionFromSignatureDeclaration(typeChecker, functionDeclaration)] : undefined;
         }
 
+        if (node.kind === SyntaxKind.CaseKeyword || node.kind === SyntaxKind.DefaultKeyword) {
+            const switchStatement = findAncestor(node.parent, isSwitchStatement) as SwitchStatement | undefined;
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:36]: You shouldn't need the type assertion anymore.

```suggestion
            const switchStatement = findAncestor(node.parent, isSwitchStatement);
```

File: tests/cases/fourslash/goToDefinitionSwitch1.ts [hunk 6]
```diff
@@ -0,0 +1,7 @@
+/// <reference path="fourslash.ts" />
+
+/////*end*/switch (null) {
+////  [|/*start*/case|] null: break;
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/goToDefinitionSwitch1.ts:4]: I don't think this needs a `[|range|]` does it?

Comment (DanielRosenwasser) [reply tests/cases/fourslash/goToDefinitionSwitch1.ts:4]: Please remove these from the tests if they're not necessary

Comment (sviat9440) [reply tests/cases/fourslash/goToDefinitionSwitch1.ts:4]:
```

Comment (sviat9440) [reply tests/cases/fourslash/goToDefinitionSwitch1.ts:4]: You mean like this? It doesn't work.

```
/////*end*/switch (null) {
////  /*start*/case null: break;
////}
```

Comment (DanielRosenwasser) [reply tests/cases/fourslash/goToDefinitionSwitch1.ts:4]: Really? That's very weird, but I'm only a little surprised. 😅

Comment (sviat9440) [reply tests/cases/fourslash/goToDefinitionSwitch1.ts:4]: the tests from the previous pull request are taken as a basis
https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/goToDefinitionReturn1.ts

Comment (sviat9440) [reply tests/cases/fourslash/goToDefinitionSwitch1.ts:4]: This test passes:
```
/////*end*/switch (null) {
////  [|/*start*/case|] null: break;
////}
```

But this:
```
/////*end*/switch (null) {
////  /*start*/case null: break;
////}
```
Give error: 
```
     Error: At marker 'start': goToDefinitionsAndBoundSpan failed. Found a starting TextSpan around 'case' in '/tests/cases/fourslash/goToDefinitionSwitch1.ts' (at position 18). If this is the correct input span, put a fourslash range around it: 

      switch (null) {
        [|/*start*/case|] null: break;
      }

```

**Comment by sviat9440** [comment]
```
/////*c*/export default { [|/*a*/case|] };
////[|/*b*/default|];
```

Is it normal that *b* and goes to *c*? This is how it works now. It looks like a bug.

**Comment by DanielRosenwasser** [comment]
It's questionable, but I wouldn't get hung up on fixing that specific case.

File: src/services/goToDefinition.ts [hunk 7]
```diff
@@ -32,6 +32,13 @@ namespace ts.GoToDefinition {
             return functionDeclaration ? [createDefinitionFromSignatureDeclaration(typeChecker, functionDeclaration)] : undefined;
         }
 
+        if (node.kind === SyntaxKind.CaseKeyword || node.kind === SyntaxKind.DefaultKeyword) {
+            const switchStatement = findAncestor(node.parent, n => isExportAssignment(n) ? "quit" : isSwitchStatement(n)) as SwitchStatement | undefined;
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:36]: This might work; however, here's how I might write it:

```ts
switch (node.kind) {
    case SyntaxKind.ReturnKeyword:
        // copy from above
        break;
    case SyntaxKind.DefaultKeyword:
        if (!isDefaultClause(node.parent)) {
            break;
        }
        // fallthrough
    case SyntaxKind.CaseKeyword:
        // current logic below
        break;
}
```

Comment (sviat9440) [reply src/services/goToDefinition.ts:36]: Looks prettier

**Comment by sviat9440** [comment]
hm Sorry, I thought I needed to request a review from everyone. But only one allowed.

File: src/services/goToDefinition.ts [hunk 8]
```diff
@@ -510,4 +522,21 @@ namespace ts.GoToDefinition {
                 return false;
         }
     }
+
+    function createDefinitionInfoFromNode(node: Node, name: string): DefinitionInfo {
+        const sourceFile = node.getSourceFile();
+        return {
+            fileName: sourceFile.fileName,
+            textSpan: createTextSpanFromNode(node, sourceFile),
+            kind: ScriptElementKind.label,
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:531]: ScriptElementKind.keyword ?

File: src/services/goToDefinition.ts [hunk 9]
```diff
@@ -26,10 +26,22 @@ namespace ts.GoToDefinition {
...
+                return functionDeclaration ? [createDefinitionFromSignatureDeclaration(typeChecker, functionDeclaration)] : undefined;
+            case SyntaxKind.DefaultKeyword:
+                if (!isDefaultClause(node.parent)) {
+                    break;
+                }
+                // falls through
+            case SyntaxKind.CaseKeyword:
+                const switchStatement = findAncestor(node.parent, isSwitchStatement);
+                if (switchStatement) {
+                    return [createDefinitionInfoFromNode(switchStatement, "switch")];
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:42]: This is setting definition as whole switch block. want only keyword switch i think or switch expression ?

File: src/services/goToDefinition.ts [hunk 10]
```diff
@@ -510,4 +522,21 @@ namespace ts.GoToDefinition {
...
+    function createDefinitionInfoFromNode(node: Node, name: string): DefinitionInfo {
+        const sourceFile = node.getSourceFile();
+        return {
+            fileName: sourceFile.fileName,
+            textSpan: createTextSpanFromNode(node, sourceFile),
+            kind: ScriptElementKind.label,
+            name,
+            containerKind: ScriptElementKind.unknown,
+            containerName: "",
+            contextSpan: createTextSpanFromNode(node, sourceFile),
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:535]: contextSpan needs to be undefined or switch keyword + expression ?

File: src/services/goToDefinition.ts [hunk 11]
```diff
@@ -510,4 +522,21 @@ namespace ts.GoToDefinition {
...
     }
+
+    function createDefinitionInfoFromNode(node: Node, name: string): DefinitionInfo {
+        const sourceFile = node.getSourceFile();
+        return {
+            fileName: sourceFile.fileName,
+            textSpan: createTextSpanFromNode(node, sourceFile),
+            kind: ScriptElementKind.label,
+            name,
+            containerKind: ScriptElementKind.unknown,
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:533]: `undefined! ` just like in `createDefinitionInfoFromName`

File: src/services/goToDefinition.ts [hunk 12]
```diff
@@ -510,4 +522,21 @@ namespace ts.GoToDefinition {
...
+            containerName: "",
+            contextSpan: createTextSpanFromNode(node, sourceFile),
+            isLocal: false,
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:536]: `isLocal: true`

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/goToDefinition.ts (hunk 11 above)
Comment (DanielRosenwasser) [reply src/services/goToDefinition.ts:533]: Should `containerKind` just be optional or something?

File: src/services/goToDefinition.ts (hunk 10 above)
Comment (DanielRosenwasser) [reply src/services/goToDefinition.ts:535]: @sheetalkamat why can't it be the node itself?

File: src/services/goToDefinition.ts (hunk 9 above)
Comment (DanielRosenwasser) [reply src/services/goToDefinition.ts:42]: Sorry, that was my suggestion.

File: src/services/goToDefinition.ts [hunk 13]
```diff
@@ -510,4 +522,26 @@ namespace ts.GoToDefinition {
...
         }
     }
+
+    interface StatementWithExpression extends Statement {
+        readonly expression: Expression
+    }
+
+    function createDefinitionInfoFromStatement<K extends KeywordSyntaxKind>(statement: StatementWithExpression, keywordKind: K, name: string): DefinitionInfo {
+        const sourceFile = statement.getSourceFile();
+        const [keyword] = statement.getChildren().filter((node): node is Token<K> => node.kind === keywordKind);
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:532]: We have a `find` helper you can use instead of `filter`.

```suggestion
        const keyword = find(statement.getChildren(sourceFile), (node): node is Token<K> => node.kind === keywordKind)!;
```

As an aside, it's a little "risky" always assuming the `switch` keyword is around - the language service has a tendency to find places where the parser generates nodes that we would never have expected; however, I think it should be okay in this case since I cannot imagine how else we would end up with a switch statement otherwise.

File: src/services/goToDefinition.ts [hunk 14]
```diff
@@ -510,4 +522,26 @@ namespace ts.GoToDefinition {
                 return false;
         }
     }
+
+    interface StatementWithExpression extends Statement {
+        readonly expression: Expression
+    }
+
+    function createDefinitionInfoFromStatement<K extends KeywordSyntaxKind>(statement: StatementWithExpression, keywordKind: K, name: string): DefinitionInfo {
+        const sourceFile = statement.getSourceFile();
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:531]: The caller of `createDefinitionInfoFromStatement` already has a `sourceFile`. Also, `getChildren` implicitly gets the `sourceFile` of a node.

I think you should pass along the `sourceFile` to `createDefinitionInfoFromStatement`, and then pass it through to `statement.getChildren()` as well.

Comment (sviat9440) [reply src/services/goToDefinition.ts]: fixed

File: src/services/goToDefinition.ts (hunk 13 above)
Comment (sviat9440) [reply src/services/goToDefinition.ts]: fixed

File: src/services/goToDefinition.ts [hunk 15]
```diff
@@ -510,4 +522,25 @@ namespace ts.GoToDefinition {
                 return false;
         }
     }
+
+    interface StatementWithExpression extends Statement {
+        readonly expression: Expression
+    }
+
+    function createDefinitionInfoFromStatement<K extends KeywordSyntaxKind>(statement: StatementWithExpression, keywordKind: K, sourceFile: SourceFile, name: string): DefinitionInfo {
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:530]:
```suggestion
    function createDefinitionInfoFromStatement(statement: StatementWithExpression, keywordKind: KeywordSyntaxKind, sourceFile: SourceFile, name: string): DefinitionInfo {
```

File: src/services/goToDefinition.ts [hunk 16]
```diff
@@ -510,4 +522,25 @@ namespace ts.GoToDefinition {
                 return false;
         }
     }
+
+    interface StatementWithExpression extends Statement {
+        readonly expression: Expression
+    }
+
+    function createDefinitionInfoFromStatement<K extends KeywordSyntaxKind>(statement: StatementWithExpression, keywordKind: K, sourceFile: SourceFile, name: string): DefinitionInfo {
+        const keyword = find(statement.getChildren(sourceFile), (node): node is Token<K> => node.kind === keywordKind)!;
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:531]:
```suggestion
        const keyword = find(statement.getChildren(sourceFile), node => node.kind === keywordKind)!;
```

I don't think you need the type predicate signature, do you?

Comment (sviat9440) [reply src/services/goToDefinition.ts]: fixed

File: src/services/goToDefinition.ts (hunk 15 above)
Comment (sviat9440) [reply src/services/goToDefinition.ts]: fixed

**Review by DanielRosenwasser — APPROVED** [review]

**Review by sheetalkamat — COMMENTED** [review]
This looks good but the tests dont verify contextSpan is coming out correct. 

Also should context be switch keyword plus expression or just expression.. Probably expression is fine but i am not sure if editor works out ok if context span is mutually exclusive with definition span.. (dont think we have had that)

**Comment by sviat9440** [comment]
@sandersn I change contextSpan to keyword + expression, but i can't find any examples for testing contextSpan with fourslash

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Good to go @sheetalkamat?

**Comment by sviat9440** [comment]
Any progress? @sheetalkamat

**Comment by sheetalkamat** [comment]
@typescription pack this

**Comment by sheetalkamat** [comment]
@typescript-bot  pack this

**Comment by sheetalkamat** [comment]
I am working on framework to test contextSpan with goto def which we should merge and then rebase this PR so its clearer on what is the context that is being set for contextSpan. Will link PR here once i have it ready

**Comment by sheetalkamat** [comment]
@sviat9440 #52576 is up and once that is merged you should be able to update your PR with the baselines that verify context,
Having said that, i completely mis-read context Span to be first line of declaration. It is infact the complete declaration. With that in mind i think your earlier change of having `contextSpan` as complete switch statement was correct and you would want to go back to that behavior. Sorry for misdirecting you on that one.

**Comment by sheetalkamat** [comment]
#52576 is merged. Feel free to merge changes from main and baseline

File: tests/baselines/reference/goToDefinitionSwitchCase1.baseline.jsonc [hunk 17]
```diff
@@ -0,0 +1,17 @@
+// === goToDefinition ===
+// === /tests/cases/fourslash/goToDefinitionSwitchCase1.ts ===
+// [|{| contextId: 0 |}switch|] (<|null|>) {
```
Comment (sheetalkamat) [inline tests/baselines/reference/goToDefinitionSwitchCase1.baseline.jsonc:3]: i think contextSpan should be `switch (null)` instead of  just `null`

Comment (sandersn) [reply tests/baselines/reference/goToDefinitionSwitchCase1.baseline.jsonc:3]: Was the previous commit correct then?

Comment (sheetalkamat) [reply tests/baselines/reference/goToDefinitionSwitchCase1.baseline.jsonc:3]: kind of.. probably needs closing paren as well part of context ?

File: src/services/goToDefinition.ts [hunk 18]
```diff
@@ -710,3 +738,25 @@ function isConstructorLike(node: Node): boolean {
...
+): DefinitionInfo {
+    const keyword = find(statement.getChildren(sourceFile), node => node.kind === keywordKind)!;
+    return {
+        fileName: sourceFile.fileName,
+        textSpan: createTextSpanFromNode(keyword, sourceFile),
+        kind: ScriptElementKind.keyword,
+        name,
+        containerKind: undefined!,
+        containerName: "",
+        contextSpan: createTextSpanFromBounds(keyword.getStart(sourceFile), statement.caseBlock.getFullStart()),
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:756]: This needs to be moved to `getContextNode` which handled `SwitchStatement`then `...FindAllReferences.getContextSpan()` so that all places where we will use context span are in single place.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/goToDefinition.ts (hunk 18 above)
Comment (sandersn) [reply src/services/goToDefinition.ts:756]: Looking at createDefinitionInfoFromName above, it looks like the right way to use this is first to call getContextNode to get the start/end tokens, then to use toContextSpan to turn it into a context span (see code below). Unfortunately, my `getFullStart` hack (which grabs the closing paren) gets lost since getContextNode returns a node pair, not a location pair. And toContextSpan currently always calls getEnd, but my hack uses getFullStart.

```ts
    const keyword = FindAllReferences.getContextNode(statement)!;
    const textSpan = createTextSpanFromNode(isContextWithStartAndEndNode(keyword) ? keyword.start : keyword, sourceFile)
    return {
        fileName: sourceFile.fileName,
        textSpan,
        kind: ScriptElementKind.keyword,
        name: "switch",
        containerKind: undefined!,
        containerName: "",
        ...FindAllReferences.toContextSpan(textSpan, sourceFile, keyword),
        isLocal: true,
        isAmbient: false,
        unverified: false,
        failedAliasResolution: undefined,
    };
```

Any ideas? I'm going to try hacking toContextSpan to special case switches to see how bad that is.

Comment (sandersn) [reply src/services/goToDefinition.ts:756]: OK, the hack isn't too bad; there's a special case for strin gliterals there already, so I added it after that.

**Review by sheetalkamat — APPROVED** [review]
