### PR TITLE
Generate names for type parameter declarations in inferred types

### LINKED ISSUE #16313: Declaration emit is incorrect when type parameter names collide
```ts
function f<T>(p: T) {
    let g: <T>(x: T) => typeof p = null as any;
    return g;
}
```

Calling `f(10)` will produce something of type `<T>(x: T) => number`, however, the declaration emit is the following:

```ts
declare function f<T>(p: T): <T>(x: T) => T;
```

But calling that `f` produces the type `<T>(x: T) => T`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #16313

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -3031,7 +3031,7 @@ namespace ts {
         // Options
         NoTruncation                            = 1 << 0,   // Don't truncate result
         WriteArrayAsGenericType                 = 1 << 1,   // Write Array<T> instead T[]
-        // empty space
+        GenerateNamesForShadowedTypeParams      = 1 << 2,   // When a type parameter T is shadowing another T, generate a name for it so it can still be referenced
```
Comment (andy-ms) [inline src/compiler/types.ts]: Why does this need a flag?

File: tests/baselines/reference/api/tsserverlibrary.d.ts [hunk 2]
```diff
@@ -3444,6 +3445,7 @@ declare namespace ts {
     function createFileLevelUniqueName(text: string): Identifier;
     /** Create a unique name generated for a node. */
     function getGeneratedNameForNode(node: Node): Identifier;
+    function getOptimisticScopedGeneratedNameForName(node: Identifier): Identifier;
```
Comment (andy-ms) [inline tests/baselines/reference/api/tsserverlibrary.d.ts]: Does this need to be public?

File: src/compiler/emitter.ts [hunk 3]
```diff
@@ -3445,10 +3455,15 @@ namespace ts {
          * makeUniqueName are guaranteed to never conflict.
          * If `optimistic` is set, the first instance will use 'baseName' verbatim instead of 'baseName_1'
          */
-        function makeUniqueName(baseName: string, checkFn: (name: string) => boolean = isUniqueName, optimistic?: boolean): string {
+        function makeUniqueName(baseName: string, checkFn: (name: string) => boolean = isUniqueName, optimistic?: boolean, scoped?: boolean): string {
             if (optimistic) {
                 if (checkFn(baseName)) {
-                    generatedNames.set(baseName, true);
+                    if (scoped) {
```
Comment (rbuckton) [inline src/compiler/emitter.ts]: Anything that goes in `generatedNames` is already reserved throughout the entire generated output, so scoping these doesn't seem to make any sense. Why was this needed?

File: src/compiler/factory.ts [hunk 4]
```diff
@@ -197,6 +197,15 @@ namespace ts {
         return name;
     }
 
+    export function getOptimisticScopedGeneratedNameForName(node: Identifier): Identifier {
```
Comment (rbuckton) [inline src/compiler/factory.ts]: Do we need a special factory function for this? Couldn't we just add the extra flags to `autoGenerateflags` after calling one of the existing factory functions?

File: src/compiler/types.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/types.ts]: We don't wanna bother renaming the conflicts in quickinfo and signature help, at least in my opinion.

File: src/compiler/emitter.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/emitter.ts]: `scoped` causes it to go into `reservedNames` instead of `generatedNames`; this allows, eg, `T_1` to be reused in adjacent scopes.

File: src/compiler/factory.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/factory.ts]: Probably? But I'd also probably still write that into a function so it stays as an inline call as the use site.

Comment (rbuckton) [reply src/compiler/factory.ts]: I'd rather we just change the signature of `getGeneratedNameForNode` to something like:

`export function getGeneratedNameForNode(node: Node, flags?: GeneratedIdentifierFlags): Identifier`

Also, the existing `getGeneratedNameForNode` actually defers reading the text of the node until emit. This is important so you could correctly handle a case where the node you are generating a name from is itself a generated name. What happens if you need to end up with `<T>(x: T) => <T_1>(y: T_1) => T_1_1`?

**Comment by weswigham** [comment]
@rbuckton Do you wanna update your status and give more comments?
