### PR TITLE
Only functions can be constructor functions

### LINKED ISSUE #27345: TypeError: Cannot read property 'flags' of undefined at isRelatedTo
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/0xfe/vexflow
cd vexflow
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
TypeError: Cannot read property 'flags' of undefined
    at isRelatedTo (node_modules\typescript\lib\tsc.js:33794:28)
    at compareSignaturesRelated (node_modules\typescript\lib\tsc.js:33533:25)
    at signatureRelatedTo (node_modules\typescript\lib\tsc.js:34639:24)
    at signaturesRelatedTo (node_modules\typescript\lib\tsc.js:34614:30)
    at structuredTypeRelatedTo (node_modules\typescript\lib\tsc.js:34403:43)
    at recursiveTypeRelatedTo (node_modules\typescript\lib\tsc.js:34190:53)
    at isRelatedTo (node_modules\typescript\lib\tsc.js:33875:38)
    at checkTypeRelatedTo (node_modules\typescript\lib\tsc.js:33709:26)
    at isTypeRelatedTo (node_modules\typescript\lib\tsc.js:33691:24)
    at isTypeSubtypeOf (node_modules\typescript\lib\tsc.js:33172:20)
```

### PR DESCRIPTION
**Pull request by sandersn**
`@constructor` put on anything incorrectly makes it a JS constructor. This is a problem for actual constructors, because getJSClassType doesn't work on actual classes. The fix is to make isJSConstructor require that its declaration is a function.

Fixes #27345

### CODE REVIEW

**Comment by weswigham** [comment]
@sandersn Why about an odd pattern like:
```ts
/**
* @constructor
*/
var MyClass = mixin(MyClassBaseCtor, MyMixin);
```
?

**Comment by weswigham** [comment]
Something like that yeah. Or like `mixin` itself doesn't have a strong return type at all.

**Comment by sandersn** [comment]
@weswigham Since you took a look earlier, mind signing off on this one?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20272,18 +20272,20 @@ namespace ts {
          * file.
          */
         function isJSConstructor(node: Declaration | undefined): boolean {
-            if (node && isInJSFile(node)) {
+            if (!node || !isInJSFile(node)) {
+                return false;
+            }
+            const func = isFunctionDeclaration(node) || isFunctionExpression(node) ? node :
+                isVariableDeclaration(node) && node.initializer && isFunctionExpression(node.initializer) ? node.initializer :
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: What about node.initializer = some Conditional expression that uses functionExpression in each branch?

Comment (sandersn) [reply src/compiler/checker.ts]: Good point, but that doesn't actually work today either, and you can put the annotation on the individual function expressions like so:

```js
const Weird = b ?
    /** @constructor */
    function () { this. x = 1 } :
    /** @constructor */
    function () { this.y = 'yes' };
```

I'd rather address that as a new feature instead of as a 3.1 bugfix.

**Comment by sandersn** [comment]
This is now in master as well.
