### PR TITLE
Call `getTypeOfSymbol` in `getNarrowedTypeOfSymbol` to avoid running into circularities when computing types

### LINKED ISSUE #48313: Getting type information for a node causes other nodes to return any for their type
# Bug Report

### 🔎 Search Terms

Compiler API, unexpected any

### 🕗 Version & Regression Information

- This changed between versions 4.5.x and 4.6.x

This does not repro on 4.5.5, but repros against v4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&useUnknownInCatchVariables=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwObAwBiSMSUwAasFAM7YoAUARgIa1U304D8AXHFowomFHgCUAlEgC2zGgG0AunADeAKDhw0OIXBgQASsAA2wdsCmz5UZXAC8cZQG5N23fDYdjZi1bmKKo4ubhRkULhewD7mHAB0MqxgjIwA+gA0cKIAJqDiDgB8am5aOih6BgAKrLAO+kamscAKOaAqPDxwAAyuWlqYCHCMrSBwADxwAIz5Gn19YeS4VTUwvX0AviVZg8MouaP2h1MzW1rLsGtzAPRXWgB6PKf11bBxJhAmznA3cJVQEGAaDAAJ5wADk7xMYLg2QgwFocBQEHgoEwehw+mBgPB0gCUDBcUYACYAMwkgCc4iePzgDyeCwizxWcAA1EMotQ6AwHEdULkEKJgNk4J0unABNMvltNnMGbgem51uJXOsgA)

### 💻 Code

```ts
export function getFutureVersion(baseVersion?: string): number[] {
  const toRelease: number[] = [];
  const baseRelease: number[] = [];
  return baseRelease.map((_, index) => {
    const toPart = toRelease[index] ?? 0;
    if (index < 1) {
      return toPart;
    }
    if (index === 1) {
      toPart;
      //  ^? any
      toPart.lol; // Property 'lol' does not exist on type 'number'.(2339)
      //  ^? any
      return toPart + (baseVersion === undefined ? 0 : 1); 
    }
    return 0;
  });
}
```

### 🙁 Actual behavior

You can see that in this repro intellisense reports the type of `toPart` as `any` even though TS also knows that it must be a number.

If I attempt to get the type of `toPart`:
```js
window.sandbox.createTSProgram().then(program => {
  program.emit()
  const ast = program.getSourceFile('/input.tsx');
  console.log(
    program.getTypeChecker().getTypeAtLocation(
      ast.statements[0].body.statements[2].expression.arguments[0].body.statements[2].thenStatement.statements[0].expression,
    ),
  );
});

// -> {checker: {…}, flags: 1, id: 1, intrinsicName: 'any', objectFlags: 0}
```

Hazarding a guess intellisense and the `^?` playground token both just use `checker.getTypeAtLocation(node)` to get the type (and `checker.typeToString` to print it).

If you switch the TS version to 4.5 then you'll see that the type is correctly printed as `number` and the above snippet logs:
```js
{checker: {…}, flags: 8, id: 14, intrinsicName: 'number', objectFlags: 0}
```

### 🙂 Expected behavior

The 4.5 behaviour is correct - `getTypeAtLocation` should return a `number` type.

### Related

https://github.com/typescript-eslint/typescript-eslint/issues/4689

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #48313.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -27028,6 +27028,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     }
 
     function getNarrowedTypeOfSymbol(symbol: Symbol, location: Identifier) {
+        const type = getTypeOfSymbol(symbol);
```
Comment (gabritto) [inline src/compiler/checker.ts:27031]: @ahejlsberg is that at all acceptable? I couldn't really come up with a way to break the dependency between the type computations that arise in the issue, so I'm trying to come up with a way to fix it by changing the order in which we compute things, but I don't know if I can get away with that.

Comment (gabritto) [reply src/compiler/checker.ts:27031]: I have also been wondering about the type resolution stack and how it detects circularity... In the case of this issue for instance, the circularity arises from starting to compute the type of `toPart`, then computing the type of `index`, and then starting to compute the type of `toPart` again.
We detect a circularity even though in between the first push of `toPart` and the second push, we have computed and cached the type of `index`, and `toPart`'s type depends on `index`'s type, so technically the second time we try to compute `toPart` would succeed if we allowed it to proceed, because we made progress in between the two attempts to compute `toPart`'s type.
But we don't detect this progress when deciding if we have a circularity or not, and I don't really understand why, even though I understand how it happens.

Comment (ahejlsberg) [reply src/compiler/checker.ts:27031]: Interesting that an initial `getTypeOfSymbol` fixes the issue. I think it is a reasonable fix, particularly since it restores the order of resolution that would normally occur.

You're likely right that we'd succeed if we allowed a second attempt at computing `toPart`'s type to succeed (because we've assigned a contextual type of `index` in the process), but it's not easy to know that's the case.

**Review by weswigham — APPROVED** [review]
