### PR TITLE
Fix "Union types are not being narrowed down correctly in 4.3 #44401"

### LINKED ISSUE #44401: Union types are not being narrowed down correctly in 4.3
# Bug Report

Potentially related to #44382.

### 🔎 Search Terms

- union types
- narrowing
- 4.3

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210601#code/JYOwLgpgTgZghgYwgAgBrIN4FgBQzlwD8AXJgQApQD2ADqQM5hSgDmyAvgNy74BGJZXpVoMmrDtxztcYAJ40UAQSpQAQsgC8ZOKSq8AVhARhOyXqQCuIACYQYoCNY7IAPtss27D66fPI9hsYSuLi2CAA2cFAoCFQgjMgAjqToAGTIymqSuMAwyAAUiQB0cMgAhBpaVrb2II4AlJg8SSUlwjSS7MgQ4fQo2HjIAPRDLbzIwPQTILFQ0cbhstMw0NFOcFM0VJDgwHDhi8jVXnXWxM3FvEVC1B240jhAA)

### 💻 Code

```ts
interface X {
  a?: { aProp: string };
  b?: { bProp: string };
}
type AorB = { a: object; b: undefined } | { a: undefined; b: object };

declare const q: X & AorB;

if (q.a !== undefined) {
  q.a.aProp;
} else {
  // q.b is incorrectly inferred as potentially undefined:
  q.b.bProp;
}
```

### 🙁 Actual behavior

`q.b` is inferred as potentially undefined in the `else` block. Given that `q` conforms with `AorB`, and `q.a` is known to be undefined in the else block, this is incorrect.

### 🙂 Expected behavior

`q.b` should be inferred as present. In particular, it should be `{ bProp: string }`.

### PR DESCRIPTION
**Pull request by caojoshua**
Fixes #44401 

The regression occurred in [this commit](https://github.com/microsoft/TypeScript/commit/a21f61f746ded34b67a1d6e25ba59ed634dddd0b)

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
I originally opened #44101 because it prevented a [project of mine](https://github.com/grammyjs/grammy) from compiling. I can confirm that this PR fixes the issue. I cloned this fork and could compile my project with the local compiler without touching my code in any way. Looking forward to having this merged, thank you so much @caojoshua!

**Comment by RyanCavanaugh** [comment]
@ahejlsberg 👍/👎?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18359,9 +18359,9 @@ namespace ts {
                     if (relation === comparableRelation && target.flags & TypeFlags.Primitive) {
                         const constraints = sameMap((source as IntersectionType).types, t => t.flags & TypeFlags.Primitive ? t : getBaseConstraintOfType(t) || unknownType);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:18360]: I think the correct fix is to change this line to

```suggestion
                        const constraints = sameMap((source as IntersectionType).types, getBaseConstraintOrType);
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -18359,9 +18359,9 @@ namespace ts {
                     if (relation === comparableRelation && target.flags & TypeFlags.Primitive) {
                         const constraints = sameMap((source as IntersectionType).types, t => t.flags & TypeFlags.Primitive ? t : getBaseConstraintOfType(t) || unknownType);
                         if (constraints !== (source as IntersectionType).types) {
-                            source = getIntersectionType(constraints);
-                            if (!(source.flags & TypeFlags.Intersection)) {
-                                return isRelatedTo(source, target, /*reportErrors*/ false);
+                            const newSource = getIntersectionType(constraints);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:18362]: These three lines should just be left unchanged. The intent is to overwrite the original intersection with the new and more specific intersection, and we rely on this substitution in the code the follows.

**Review by ahejlsberg — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (caojoshua) [reply src/compiler/checker.ts]: Makes sense. Can confirm is passing the test. Just pushed this change.

**Review by ahejlsberg — APPROVED** [review]

**Comment by KnorpelSenf** [comment]
Is there any chance that this will land in 4.4?

**Comment by RyanCavanaugh** [comment]
@KnorpelSenf yep, this will be in 4.4 (not in the Beta, which is already out, but any subsequent release)
