### PR TITLE
fix(47582): Debug assertion violation for extract type refactoring

### LINKED ISSUE #47582: Debug assertion violation for extract type refactoring
Manifestation of https://github.com/microsoft/TypeScript/issues/45744

```ts
export declare function yadda<T extends { next?: /*$*/T }>(): void;
```

Request the "extract type" refactoring at `/*$*/`.

```
[Trace  - 20:42:59.406] <semantic> Response received: getEditsForRefactor (827). Request took 3 ms. Success: false . Message: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at consumeTokenAndAdvanceScanner ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143766:30)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143679:25)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143629:21
    at visitNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29727:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29807:21)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143696:21)
    at processChildNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143743:48)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143631:21
    at visitNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29732:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29872:24)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143696:21)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143629:21
    at visitNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29727:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29773:21)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at processChildNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143696:21)
    at processChildNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143743:48)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143631:21
    at visitNodes ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:29732:24)
    at Object.forEachChild ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:30065:21)
    at processNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143628:20)
    at formatSpanWorker ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143429:17)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143393:140
    at Object.getFormattingScanner ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:142020:23)
    at Object.formatNodeGivenIndentation ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:143393:31)
    at getFormattedTextOfNode ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145776:45)
    at format ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145747:52)
    at computeNewText ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145750:23)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145714:39
    at Object.mapDefined ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:599:30)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145712:42
    at Object.mapDefined ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:599:30)
    at Object.getTextChangesFromChanges ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145698:27)
    at ChangeTracker.getChanges ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145637:45)
    at Function.ChangeTracker.with ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:145067:32)
    at Object.getRefactorEditsToExtractType [as getEditsForAction] ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:157447:62)
    at Object.getEditsForRefactor ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:146362:41)
    at Object.getEditsForRefactor ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:161707:32)
    at IOSession.Session.getEditsForRefactor ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:172742:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:171446:61)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173105:88
    at IOSession.Session.executeWithRequestId ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173096:28)
    at IOSession.Session.executeCommand ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173105:33)
    at IOSession.Session.onMessage ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:173131:35)
    at Interface.<anonymous> ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220118\node_modules\typescript\lib\tsserver.js:175736:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47582

### CODE REVIEW

File: src/services/refactors/extractType.ts [hunk 1]
```diff
@@ -147,6 +147,11 @@ namespace ts.refactor {
                     const symbol = checker.resolveName(node.typeName.text, node.typeName, SymbolFlags.TypeParameter, /* excludeGlobals */ true);
                     const declaration = tryCast(symbol?.declarations?.[0], isTypeParameterDeclaration);
                     if (declaration) {
+                        if (declaration.name.escapedText === node.typeName.escapedText && rangeContainsSkipTrivia(declaration, selection, file)) {
```
Comment (DanielRosenwasser) [inline src/services/refactors/extractType.ts:150]: Are we always certain that the files are the same between the use-site and the declaration?

Comment (andrewbranch) [reply src/services/refactors/extractType.ts:150]: `resolveName` doesn’t resolve aliases (well, it does in order to check that the target matches the flags you asked for, but it doesn’t return the target), so yes.

**Review by andrewbranch — APPROVED** [review]

File: src/services/refactors/extractType.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/refactors/extractType.ts:150]: Well, a better answer is the fact that it’s a type parameter

Comment (DanielRosenwasser) [reply src/services/refactors/extractType.ts:150]: > Well a better answer is the fact that it's a type parameter.

Boy, do I have a surprise for you!

```ts
// @Filename: a.ts
interface Foo<T extends { prop: T }> {}

// @Filename: b.ts
interface Foo<T extends { prop: T }> {}
```

Comment (gabritto) [reply src/services/refactors/extractType.ts:150]: does it mean instead of checking the first declaration only (`symbol?.declarations?.[0]`), we need to check all of them and see if any falls into the same range?

would be nice to at least add that as a test case.

**Review by gabritto — CHANGES_REQUESTED** [review]
As per Daniel's comment, would be nice to have a test case with symbol merging, and see what happens then.

File: src/services/refactors/extractType.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/refactors/extractType.ts:150]: > Boy, do I have a surprise for you!

@DanielRosenwasser I've added a test for this case.

Comment (andrewbranch) [reply src/services/refactors/extractType.ts:150]: homer receding into hedges

File: tests/cases/fourslash/refactorExtractType73.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+// @Filename: a.ts
+////interface Foo<T extends { prop: T }> {}
+
+// @Filename: b.ts
+////interface Foo<T extends { prop: /*a*/T/*b*/ }> {}
+
+goTo.file("b.ts");
+goTo.select("a", "b");
+verify.not.refactorAvailable("Extract type", "Extract to type alias");
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/refactorExtractType73.ts:11]: Is the reason that that test works because the file contents are identical? Consider this test case.

```ts
/// <reference path="./fourslash.ts" />

// @Filename: a.ts
///// interface Foo<T extends { prop: [|T|] }> {}

// @Filename: b.ts
//// // Some initial comments.
//// // We need to ensure these files have different contents,
//// // so their ranges differ, so we'll start a few lines below in this file.
//// interface Foo<T extends { prop: [|T|] }> {}

for (const range of test.ranges()) {
    goTo.selectRange(range);
    verify.not.refactorAvailable("Extract type", "Extract to type alias");
}
```

File: src/services/refactors/extractType.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/services/refactors/extractType.ts:150]: Good start with that test case, but I think there's a lurking bug.

File: tests/cases/fourslash/refactorExtractType74.ts [hunk 3]
```diff
@@ -0,0 +1,12 @@
+/// <reference path='fourslash.ts' />
+
+// @Filename: a.ts
+//// interface Foo<T extends { prop: [|T|] }> {}
+
+// @Filename: b.ts
+//// interface Foo<T extends { prop: [|T|] }> {}
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/refactorExtractType74.ts:7]:
```suggestion
//// // Some initial comments.
//// // We need to ensure these files have different contents,
//// // so their ranges differ, so we'll start a few lines below in this file.
//// interface Foo<T extends { prop: [|T|] }> {}
```

File: src/services/refactors/extractType.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/services/refactors/extractType.ts:150]: I hate to drag this out longer, but does this work for if the same file has multiple declarations too?

```ts
interface Foo<T extends { prop: T }> {}
interface Foo<T extends { prop: [|T|] }> {}
```

Seems like you want something along the lines of

```ts
declarations.some(declaration => isTypeParameterDeclaration(d) && declaration.name.escapedText === node.typeName.escapedText && d.getSourceFile() === file && rangeContainsSkipTrivia(declaration, selection, file))
```

as your check

Comment (a-tarasyuk) [reply src/services/refactors/extractType.ts]: Ouch! Will add changes.

loop

**Review by gabritto — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
WooHooGIF
