### PR TITLE
fix(51198): The 'this' context of type 'T' is not assignable to method's 'this' of type 'this'

### LINKED ISSUE #51198: The 'this' context of type 'T' is not assignable to method's 'this' of type 'this'.
# Bug Report

> The 'this' context of type 'T' is not assignable to method's 'this' of type 'this'.
>   'this' could be instantiated with an arbitrary type which could be unrelated to 'T'.(2684)

### 🔎 Search Terms

class this parameter inheritance super

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about class

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/KYDwDg9gTgLgBAYwDYEMDOa4BU4G8BQccARusABQwAWAlmgFxzV0CUeAvvp8uplgExxQMYADsAJnzyE4AM0q0GTRWwJEiaAK5hgUAHSk0FFjM7sgA)

### 💻 Code

```ts
export class T {
  base(this: this) {}
}
class T2 extends T {
  f(this: this) {
    super.base()
//  ~~~~~
//  The 'this' context of type 'T' is not assignable to method's 'this' of type 'this'.
//    'this' could be instantiated with an arbitrary type which could be unrelated to 'T'.(2684)
  }
}
```

### 🙁 Actual behavior

Not works

### 🙂 Expected behavior

Works

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51198

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -30988,7 +30987,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             return undefined;
         }
         const thisType = getThisTypeOfSignature(signature);
-        if (thisType && thisType !== voidType && node.kind !== SyntaxKind.NewExpression) {
+        if (thisType && thisType !== voidType && !(isNewExpression(node) || isCallExpression(node) && isSuperProperty(node.expression))) {
             // If the called expression is not of the form `x.f` or `x["f"]`, then sourceType = voidType
             // If the signature's 'this' type is voidType, then the check is skipped -- anything is compatible.
             // If the expression is a new expression, then the check is skipped.
```
Comment (sandersn) [inline src/compiler/checker.ts:30993]: should add to this comment

**Review by iisaduan — APPROVED** [review]
