### PR TITLE
Don't issue implicit any when obtaining the implied type for a binding pattern

### LINKED ISSUE #59936: Binding element incorrectly reported as having `any` type in JS with JSDoc starting with 5.6.2
### 🔎 Search Terms

Binding element implicitly has an any type 7031

### 🕗 Version & Regression Information

- This changed between versions 5.5.4 and 5.6.2

### ⏯ Playground Link

https://www.typescriptlang.org/play/?strictNullChecks=true&target=9&suppressImplicitAnyIndexErrors=true&ts=5.6.2&filetype=js#code/PQKhCgAIUgBAHAhgJ0QW0gbwPICMBWApgMYAuAvpANrED2AdgGYCWA5gLpQwIrpYAKKUs0QAbADwAlErWQATcQHJ8AZwaLIAH0jK19Yhu26GAVkUAaSCtLJm9VlXYA+J5RoMWrAHSI5c5sIMYgBizKKEKpzQwOCEAB7wsqSQjACu+oH0kPDIhEi5AMIebAAUmFCQlb7+mSFhEQBcWBWVrZCqDJAAvNRRrZQ9mOTgA1jkAJTNbXT0auFeorSsJR304yNAA

### 💻 Code

```js
/**
 * @param {Object} [config]
 * @param {Partial<Record<'json' | 'jsonc' | 'json5', string[]>>} [config.additionalFiles]
 */
export function prepareConfig({
    additionalFiles: {
        json = []
    } = {}
} = {}) {
    console.log(json)
}
```

### 🙁 Actual behavior

`json` is errored as `Binding element 'json' implicitly has an 'any[]' type.(7031)` even though it's typed as `string[]`

image

### 🙂 Expected behavior

No error expected, as `json` is typed as `string[]`

### Additional information about the issue

This worked well in 5.5.4 but broke with upgrade to 5.6.2. It works correctly in .ts file, but breaks in .js file with JSDoc.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #59936. See my comment [here](https://github.com/microsoft/TypeScript/issues/59936#issuecomment-2379317269).

@Andarist Borrowed tests from #59975. Thanks!

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -40770,7 +40770,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     }
 
     function widenTypeInferredFromInitializer(declaration: HasExpressionInitializer, type: Type) {
-        const widened = getCombinedNodeFlagsCached(declaration) & NodeFlags.Constant || isDeclarationReadonly(declaration) ? type : getWidenedLiteralType(type);
+        const widened = getWidenedLiteralTypeForInitializer(declaration, type)
```
Comment (jakebailey) [inline src/compiler/checker.ts:40773]:
```suggestion
        const widened = getWidenedLiteralTypeForInitializer(declaration, type);
```

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.6

**Review by jakebailey — APPROVED** [review]
