### PR TITLE
Quick fix to correct qualified names to indexed access types

### LINKED ISSUE #17461: Add quick fix for error on qualified names instead of indexed access types
Give a quick fix for the error that #17459 issues.

Root issue: #17458.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #17461

qnwithiat

### CODE REVIEW

File: src/services/codefixes/correctQualifiedNameToIndexedAccessType.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
+/* @internal */
+namespace ts.codefix {
+    registerCodeFix({
+        errorCodes: [Diagnostics.Cannot_access_0_1_because_0_is_a_type_but_not_a_namespace_Did_you_mean_to_retrieve_the_type_of_the_property_1_in_0_with_0_1.code],
+        getCodeActions: (context: CodeFixContext) => {
+            const sourceFile = context.sourceFile;
+            const token = getTokenAtPosition(sourceFile, context.span.start, /*includeJsDocComment*/ false);
+            const qualifiedName = getAncestor(token, SyntaxKind.QualifiedName) as QualifiedName;
+            Debug.assert(!!qualifiedName, "Expected position to be owned by a qualified name.");
+            if (!isIdentifier(qualifiedName.left)) {
```
Comment (aozgaa) [inline src/services/codefixes/correctQualifiedNameToIndexedAccessType.ts]: This example doesn't seem to trigger the right error, though we can apply the fix manually to fix the issue:
```
module M {
    export interface I {
         foo: string;
    }
}
let a: M.I.foo;
```
Please add a test.

File: src/services/codefixes/fixes.ts [hunk 2]
```diff
@@ -1,3 +1,4 @@
+/// <reference path="correctQualifiedNameToIndexedAccessType.ts" />
 /// <reference path="fixClassIncorrectlyImplementsInterface.ts" />
```
Comment (aozgaa) [inline src/services/codefixes/fixes.ts]: Looks like there is an analogous entry to this in `src/harness/tsconfig.json`. Not sure why it's there, or if we might want to remove it. Or alternatively, add a reference to `correctQualifiedNameToIndexedAccessType.ts`.

@weswigham do you know if building for tests will correctly trigger a rebuild when we make changes to `correctQualifiedNameToIndexedAccessType.ts`?

**Comment by DanielRosenwasser** [comment]
@aozgaa no, I didn't generalize the check, but I can at a later point. I did add a negative fourslash test, and augmented the tests added in #17459.
