### PR TITLE
Filter primitives from union when checking for mismatched excess props if nonprimitive type is present

### LINKED ISSUE #31668: Apparent properties in union of primitive and object causes incorrect error
**TypeScript Version:**  3.5.1

**Search Terms:** sub blink sup bold HTML Element String.prototype methods

**Code**

```ts
type sign = (payload: string | object) => void;
const sign: sign = (payload) => { console.log(payload)}
sign({ sub: null })
```

**Expected behavior:** Ok

**Actual behavior:**

```
$ ./node_modules/.bin/tsc --version
Version 3.5.1
$ ./node_modules/.bin/tsc --lib es2015 --strict ./repro.ts
repro.ts:5:6 - error TS2326: Types of property 'sub' are incompatible.
  Type 'null' is not assignable to type '(() => string) | undefined'.

5 sign({ sub: null })
       ~~~~~~~~~~~~~


Found 1 error.
```

```
$ ./node_modules/.bin/tsc --version
Version 3.6.0-dev.20190530
$ ./node_modules/.bin/tsc --lib es2015 --strict ./repro.ts
repro.ts:5:6 - error TS2326: Types of property 'sub' are incompatible.
  Type 'null' is not assignable to type '(() => string) | undefined'.

5 sign({ sub: null })
       ~~~~~~~~~~~~~


Found 1 error.
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #31668

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12869,6 +12869,16 @@ namespace ts {
                 return bestMatch;
             }
 
+            function filterPrimitivesIfContainsNonPrimitive(type: UnionType) {
+                if (some(type.types, t => !!(t.flags & TypeFlags.NonPrimitive))) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Pretty sure there's a `someTypeHasFlags` or something

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this

**Comment by weswigham** [comment]
ping @DanielRosenwasser @sandersn
