### PR TITLE
Track type recusion and symbol instantiation depth seperately in createAnonymousTypeNode

### LINKED ISSUE #26228: Using inferred return type of function as argument to same function breaks type inference
**TypeScript Version:**  3.0.1

**Search Terms:** return type inference

**Code**

My specific instance of this problem can be found [here](https://github.com/AnyhowStep/schema-decorator/blob/f5a3d13aed658ab4771be8751a59ab20f783cbe6/src/main/schema.ts)
Scroll to the very bottom to see a comment about it.

I couldn't figure out a minimal example but it looks like,

```ts
const result1 = foo(/*arg*/); //Inferred type is correct
const result2 = foo(result1); //Inferred type is wrong; shows `any`
```

However, if I explicitly declare the type of `result1`, it works,

```ts
const result1 : number = foo(/*arg*/); //Explicitly declared
const result2 = foo(result1); //Inferred type is correct
```

Or, if I do this very weird thing,

```ts
//Both foo1<>() and foo2<>() are the same, I just copy pasted foo<>() and renamed
declare function foo1</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;
declare function foo2</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;

const result1 = foo1(/*arg*/); //Inferred type is correct
const result2 = foo2(result1); //Inferred type is correct
```

Trying a type alias fails,

```ts
declare function foo</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;
type FooDelegate = </*Complicated Type*/>(/*Params*/) => /*Complicated Type*/;

const foo1 : FooDelegate = foo;
const foo2 : FooDelegate = foo;

const result1 = foo1(/*arg*/); //Inferred type is correct
const result2 = foo2(result1); //Inferred type is wrong; shows any
```

But this also works,

```ts
declare function foo</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;

const foo1 : </*Complicated Type*/>(/*Params*/) => /*Complicated Type*/ = foo;
const foo2 : </*Complicated Type*/>(/*Params*/) => /*Complicated Type*/ = foo;

const result1 = foo1(/*arg*/); //Inferred type is correct
const result2 = foo2(result1); //Inferred type is correct
```

It seems like if I rely on return type inference, I have to copy-paste the function type, and cannot re-use a previous declaration.

So, if I wanted to nest the results 4 times, I'd need `foo1, foo2, foo3, foo4`

Right now, I just either declare the return-type explicitly, every time the function is used, or I don't use the function at all.

**Expected behavior:**

Inferred type to not have `any`

**Actual behavior:**

Inferred type contains `any`

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #26228 by increasing the symbol depth limit from an implied 1 to an explicit 10 repetitions of the same symbol (an individual type can still only be visited once before being printed with `any`). This does mean that the behavior in #26228 will recur if you chain 10+ calls.... but this will make it way less noticeable.

Also use `...` for recursive locations in quick info instead of `any`, to (hopefully) reduce confusion as to what's being printed in the future.

### CODE REVIEW

File: tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/// <reference path="fourslash.ts" />
+
+////declare function schema<T> (value : T) : {field : T};
+////
+////declare const b: boolean;
+////const obj/*1*/ = schema(b);
+////const actualTypeOfNested/*2*/ = schema(obj);
```
Comment (sheetalkamat) [inline tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts]: Interesting. This is not circular generic type though so this shouldn't run into the circularity print in the first place. So to me it feels like we are missing something else that we can account in ID (eg. instantiations of the type as well?)

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3455,19 +3457,35 @@ namespace ts {
...
+                            if (!context.symbolDepth) {
+                                context.symbolDepth = createMap<number>();
                             }
 
-                            context.visitedSymbols.set(id, true);
+                            const depth = context.symbolDepth.get(id) || 0;
+                            if (depth > 10) {
+                                context.approximateLength += 3;
+                                if (!(context.flags & NodeBuilderFlags.NoTruncation)) {
+                                    return createTypeReferenceNode(createIdentifier("..."), /*typeArguments*/ undefined);
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: Hmm this might cause problem with quick Info or something similar where it uses display part kinds where it will coincide with spread operator thus colorization might be odd?

File: tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts (hunk 1 above)
Comment (weswigham) [reply tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts]: Right, so we track how many times we visit the same symbol, since we don't know if the symbol is generative or not (ie, does each member produce a type whose member is a new instantiation of the type) and we have tests to that effect. In this case, we do produce a type with a member of the same symbol as the overall type, but it's finite - just 2 levels deep. The explicit `depth` check helps distinguish these cases.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: We already use `...` in arbitrary places for truncation, and have for around 2 releases? The `displaypartKind` isn't based on the text, but on the function used to print the text, and this is being passed off as an `identifier`, so will be `text`, not `punctuation`.

File: tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts (hunk 1 above)
Comment (sheetalkamat) [reply tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts]: I understand why you are tracking depth but what i meant was why not add (symbol.links.instatiations.typeId) to determine if we are recuring into symbol + type combination. Thus we would still not have to print something like `z : { y2: { y2: { y2: { y2: { y2: { y2: { y2: { y2: { y2: { y2: { y2: any; }; }; }; }; }; }; }; }; }; }; }`

Comment (weswigham) [reply tests/cases/fourslash/quickInforForSucessiveInferencesIsNotAny.ts]: Every `y2` in that type is within a differently id'd object literal type backed by the same (well, 1 of 2, the test is mutual recursion) symbol. No `symbol + type` id pair will ever repair because it generates new `type` ids infinitely as it recurs.
