### PR TITLE
fix(43559): no-default-lib causes 'You cannot rename elements that are defined in the standard TypeScript library'

### LINKED ISSUE #43559: no-default-lib causes 'You cannot rename elements that are defined in the standard TypeScript library'
# Bug Report

### 🔎 Search Terms
- rename
- f2

### 🕗 Version & Regression Information

4.3.0-dev.20210325

### 💻 Code

For the JavaScript:

```ts
// @ts-check

/// <reference no-default-lib="true"/>

const someName = 12;
```

Trigger rename on `someName` using `F2`

### 🙁 Actual behavior

You see the error: `You cannot rename elements that are defined in the standard TypeScript library.`

Screen Shot 2021-04-06 at 2 14 43 PM

### 🙂 Expected behavior

You should be able to rename this symbol

If I remove `/// <reference no-default-lib="true"/>`, then I can rename

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43559

### CODE REVIEW

File: src/services/rename.ts [hunk 1]
```diff
@@ -55,6 +55,11 @@ namespace ts.Rename {
         return getRenameInfoSuccess(displayName, fullDisplayName, kind, SymbolDisplay.getSymbolModifiers(typeChecker,symbol), node, sourceFile);
     }
 
+    function isDefinedInLibraryFile(program: Program, declaration: Node) {
+        const sourceFile = declaration.getSourceFile();
+        return sourceFile.hasNoDefaultLib ? false : program.isSourceFileDefaultLibrary(sourceFile);
```
Comment (DanielRosenwasser) [inline src/services/rename.ts:60]: Could this always just be `program.isSourceFileDefaultLibrary(sourceFile);`?

Comment (a-tarasyuk) [reply src/services/rename.ts:60]: Actually, it has 

```ts
if (file.hasNoDefaultLib) {
    return true;
}
```

Comment (a-tarasyuk) [reply src/services/rename.ts:60]: @DanielRosenwasser I mean that `isSourceFileDefaultLibrary` return `true` if file has `hasNoDefaultLib`

https://github.com/microsoft/TypeScript/blob/970554733a3578cd854606ebcb316f291632b118/src/compiler/program.ts#L1708-L1712

Maybe we need to ignore JS files instead of checking `hasNoDefaultLib`., what do you think?

Comment (sheetalkamat) [reply src/services/rename.ts:60]: I think you should check if file is not d.ts file

Comment (a-tarasyuk) [reply src/services/rename.ts]: @sheetalkamat Thanks

**Review by sheetalkamat — APPROVED** [review]
