### PR TITLE
Reset partial memberlist on defered circularity to calculate the correct members

### LINKED ISSUE #16861: tsc TypeError: Cannot read property 'flags' of undefined
**TypeScript Version:**  2.4.1

**Code**

```ts
// This is minimal chunk of code
class BaseType<T> {
    bar: T
}

class NextType<C extends { someProp: any }, T = C['someProp']> extends BaseType<T> {
}

class Foo extends NextType<Foo> {
    someProp: {
        test: true
    }
}

const foo = new Foo();
foo.bar.test
```

**Expected behavior:**
Just to compile and run. May be this code violates TypeScript rules, but the actual result is unexpected, anyway
Both atom-typescript and WebStorm EAP consider this code as valid, and even correctly auto-complete "foo.bar.test"

**Actual behavior:**
```
$ tsc
/usr/lib/node_modules/typescript/lib/tsc.js:55776
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at Object.getCheckFlags (/usr/lib/node_modules/typescript/lib/tsc.js:7996:22)
    at getTargetSymbol (/usr/lib/node_modules/typescript/lib/tsc.js:37957:23)
    at checkKindsOfPropertyMemberOverrides (/usr/lib/node_modules/typescript/lib/tsc.js:37975:31)
    at checkClassLikeDeclaration (/usr/lib/node_modules/typescript/lib/tsc.js:37915:21)
    at checkClassDeclaration (/usr/lib/node_modules/typescript/lib/tsc.js:37858:13)
    at checkSourceElement (/usr/lib/node_modules/typescript/lib/tsc.js:38767:28)
    at Object.forEach (/usr/lib/node_modules/typescript/lib/tsc.js:298:30)
    at checkSourceFileWorker (/usr/lib/node_modules/typescript/lib/tsc.js:38836:20)
    at checkSourceFile (/usr/lib/node_modules/typescript/lib/tsc.js:38821:13)
    at getDiagnosticsWorker (/usr/lib/node_modules/typescript/lib/tsc.js:38874:17)
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #16861

We've had this bug since we released generic defaults, according to my `bisect` test. The root cause of the assertion violation is an `undefined` symbol which we expect to be present because of its presence in the class inheritance heirarchy. It is missing because the `.members` cache of members was calculated while the `baseType` of the class was still resolving (as the generic default `C["someProp"]` forces a resolution of them), and that partial list is kept around and reused even once the fully resolved inheritance hierarchy is known. In this PR, I simply clear that cache when I know it is missing values, as the recurrence is valid if the index does not access a member whose type is itself recursive (which will trigger a different recursion guard).

Another option (rather than resetting the cache we know is bad) is to issue a circularity error - however since the circularity is indirect (via the index access), I believe it's fine to allow it so long as we acknowledge the partially created member cache we create prior to knowing that the type affects its own base - then deal with it appropriately. The _most_ correct thing to do would probably be making `instantiateType` for an indexed access not instantiate the whole object type (and thereby any base types it may have) before calling `getPropertyOfType` on it, and instead attempt to just instantiate the single target symbol - there may even be a perf benefit to doing so.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5057,11 +5057,11 @@ namespace ts {
             return type.resolvedBaseTypes;
         }
 
-        function resolveBaseTypesOfClass(type: InterfaceType): void {
-            type.resolvedBaseTypes = emptyArray;
+        function resolveBaseTypesOfClass(type: InterfaceType): BaseType[] {
```
Comment (rbuckton) [inline src/compiler/checker.ts]: It doesn't look like you are using this return type.

Comment (weswigham) [reply src/compiler/checker.ts]: No, I was just using it to ensure I set `resolvedBaseType` at each exit point. I can replace it with `void` if you'd like.
