### PR TITLE
fix completions protected members in recursive generic types (#19192)

### LINKED ISSUE #19192: Language Service don't show protected members in recursive generic types
**TypeScript Version:**  2.6.0-dev.20171015

```ts
export class TestBase<T extends TestBase<T>>
{
    private privateMethod(p: any): void { }
    protected protectedMethod(p: any): void { }

    public publicMethod1(t: T): void
    {
        t. /* <---- press Ctrl+Space here, ts language service only shows private and public methods, protectedMethod is hidden */

        t.protectedMethod(null/* if I write the method name by myself, the method arguments shown here is fine */);
        //no error, ts compiler knows that I can call protectedMethod
    }

    public publicMethod2(t: TestBase<T>): void
    {
        t. /* <---- press Ctrl+Space here, it's OK, it shows me everithing */
    }
}
```

**Expected behavior:**
To show protectedMethod when I press Ctrl+Space

**Actual behavior:**
Don't show protectedMethod when I press Ctrl+Space

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #19192

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
This fix might be an overkill. 

Note `hasBaseType` has already checked `TypeFlags`, we can simplify the code like 

            if (type.flags & TypeFlags.TypeParameter) {
                // get the original type -- represented as the type constraint of the 'this' type
                type = getConstraintOfTypeParameter(<TypeParameter>type);
            }
            if (!hasBaseType(type, enclosingClass)) {
                error(errorNode, Diagnostics.Property_0_is_protected_and_only_accessible_through_an_instance_of_class_1, symbolToString(prop), typeToString(enclosingClass));
                return false;
            }

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14956,11 +14956,14 @@ namespace ts {
                 return true;
             }
             // An instance property must be accessed through an instance of the enclosing class
-            if (type.flags & TypeFlags.TypeParameter && (type as TypeParameter).isThisType) {
-                // get the original type -- represented as the type constraint of the 'this' type
-                type = getConstraintOfTypeParameter(<TypeParameter>type);
-            }
-            if (!(getObjectFlags(getTargetType(type)) & ObjectFlags.ClassOrInterface && hasBaseType(type, enclosingClass))) {
+            if (type.flags & TypeFlags.TypeParameter) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: consider writing it as:
```ts
  if (type.flags & TypeFlags.TypeParameter) {
                // get the original type -- represented as the type constraint of the 'this' type
                type = (type as TypeParameter).isThisType ? getConstraintOfTypeParameter(<TypeParameter>type) : getBaseConstraintOfType(<TypeParameter>type);
            }
            if (!type || !hasBaseType(type, enclosingClass)) {
                error(errorNode, Diagnostics.Property_0_is_protected_and_only_accessible_through_an_instance_of_class_1, symbolToString(prop), typeToString(enclosingClass));
                return false;
            }
            return true;
```
