### PR TITLE
Infer a rest parameter for javascript function that uses 'arguments'

### LINKED ISSUE #14232: [Salsa] Infer functions using `arguments` as `(...args: any[])`
```js
// a.js
function trace() {
    console.log(arguments.length);
}
```
```ts
//b.ts
trace("error", 1, 2, 3); // Error: Supplied parameters do not match any call signature
```

Since there is no way in a .js (pre ES6) file to express var args, the compiler should infer from the use of `arguments` in the function body the usage.

### PR DESCRIPTION
**Pull request by rbuckton**
When resolving a call signature for a function in a JavaScript file, infer a `...args` parameter if the function body includes an `arguments` reference.

Fixes #14232

### CODE REVIEW

**Comment by sandersn** [comment]
Looks like the CI failure is just some lint.

File: tests/cases/fourslash/signatureHelpCallExpressionJs.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+/// <reference path='fourslash.ts'/>
+
+// @checkJs: true
+// @allowJs: true
+
+// @Filename: main.js
+////function fnTest() { arguments; }
+////fnTest(/*1*/);
```
Comment (sandersn) [inline tests/cases/fourslash/signatureHelpCallExpressionJs.ts]: can you add a call like `fnTest(1,2,3)` plus verify that semantic diagnostics count is 0?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6170,6 +6174,37 @@ namespace ts {
             }
         }
 
+        function containsArgumentsReference(declaration: FunctionLikeDeclaration): boolean {
+            const links = getNodeLinks(declaration);
+            if (links.containsArgumentsReference === undefined) {
+                if (links.flags & NodeCheckFlags.CaptureArguments) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: why do we need `traverse` if we have `CaptureArguments`. Is it that not all identifiers are checked in the services case? Or does `CaptureArguments` miss some uses of `arguments`?

File: src/compiler/types.ts [hunk 3]
```diff
@@ -2870,6 +2870,7 @@ namespace ts {
     /* @internal */
     export interface TransientSymbol extends Symbol, SymbolLinks {
         checkFlags: CheckFlags;
+        isRestParameter?: boolean;
```
Comment (sandersn) [inline src/compiler/types.ts]: This seems kind of invasive for a small change, and the property is only checked one place. Is it possible to use some other predicate in buildParameterDisplay? Would `isTransientSymbol` be enough?

File: src/compiler/checker.ts (hunk 2 above)
Comment (rbuckton) [inline src/compiler/checker.ts]: CaptureArguments is only set if we are checking the function, which is not always the case when we are resolving a call.

File: src/compiler/types.ts (hunk 3 above)
Comment (rbuckton) [inline src/compiler/types.ts]: No, we create symbols for all kinds of reasons. This is cheaper than creating an entire synthetic node just to trick `buildParameterDisplay`. At one point I was looking into creating purely synthetic types, and this was one of the required changes to make this work.

File: src/compiler/checker.ts (hunk 2 above)
Comment (rbuckton) [inline src/compiler/checker.ts]: I will clarify. When we resolve a call, we do not necessarily check the body of the function. As a result, we must traverse the body of the function to discover whether `arguments` is used in an expression. *As an optimization*, we can use the pre-existing `CaptureArguments` flag if the function was checked *prior* to resolving the call. We cannot guarantee that `CaptureArguments` has already been set.

Comment (sandersn) [inline src/compiler/checker.ts]: OK, makes sense. I see my question wasn't very clear now that I re-read it.
