### PR TITLE
Fix `node.getStart()` for nodes spanning multiline JSDoc comments

### LINKED ISSUE #43442: JSDoc @typedef object literal property rename text includes leading '*' and space
# Bug Report

### 🔎 Search Terms

JSDoc typedef property rename

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useJavaScript=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIG9dQySRYD2pAXJAM7wBOAlgHYDmA3IcZAEYCGdVJgFcAtt1R0O0SAF8ZkAGLlCwcOFAwEKVHiWl5IVQGNSTWpAAekALx4oXMpUgAiZwBp7xPgMgAWAEyQwMCQADwAtOE0qDropEaiqEzwkAAWDCypADYZqSm8TOiQdEm8IjqmkADk3lXgMmxAA)

### 💻 Code

```ts
/**
 * @typedef {{
 *   foo: string;
 *   bar: number;
 * }} Foo
 */

/** @type {Foo} */
const x = {
    foo: "",
    bar: 42 // <-- see document highlight and rename on 'bar'
};
```

### 🙁 Actual behavior

1. After renaming a property in `x`, the `*   ` (including spaces) get deleted from the `@typedef`.
2. (VS Code only, not Playground) Renaming in the `@typedef` treats the `*   ` as part of the name, and leaving it in adds `*   ` to the property declaration in `x`:

    Kapture 2021-03-30 at 12 21 00

### 🙂 Expected behavior

Rename works without breaking source code or comment formatting. Document highlight does not highlight the leading `*   `.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #43442

`skipTrivia` needs to skip a leading `*` inside JSDoc.

### CODE REVIEW

File: src/compiler/scanner.ts [hunk 1]
```diff
@@ -613,13 +617,23 @@ namespace ts {
...
                     if (pos === 0 && isShebangTrivia(text, pos)) {
                         pos = scanShebangTrivia(text, pos);
+                        canConsumeStar = false;
+                        continue;
+                    }
+                    break;
+
+                case CharacterCodes.asterisk:
+                    if (canConsumeStar) {
+                        pos++;
```
Comment (sheetalkamat) [inline src/compiler/scanner.ts:635]: Dont you need to set canConsumeStar to false in the default case as well?

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -478,7 +478,12 @@ namespace ts {
             return getTokenPosOfNode((<SyntaxList>node)._children[0], sourceFile, includeJsDoc);
         }
 
-        return skipTrivia((sourceFile || getSourceFileOfNode(node)).text, node.pos);
```
Comment (sandersn) [inline src/compiler/utilities.ts:481]: this looks like an OK fix, but I don't think skipTrivia is called on the inside of jsdoc anywhere else. Maybe there should be a completely separate code path?

I haven't thought about it deeply, so it's likely that skipTrivia is 98% right and just needed this tweak to work.

**Review by sandersn — CHANGES_REQUESTED** [review]
One question about whether skipTrivia is suitable in the first place.

File: src/compiler/utilities.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/utilities.ts:481]: Well, it’s definitely true that I didn’t pass the parameter anywhere else. It occurred to me that I could accomplish the same thing by wrapping `skipTrivia` and calling it in a loop with `stopAfterLineBreak`, but I felt like it was a little less clear what was happening. But I can go back to that—I’m pretty ambivalent about it.

Comment (sandersn) [reply src/compiler/utilities.ts:481]: Ummm, me too. Neither one of these functions are specific to jsdoc, so jsdoc-specific code is surprise in both.

Probably means that this is good enough.

**Review by sandersn — APPROVED** [review]

File: src/compiler/scanner.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/scanner.ts:635]: I don’t think so—the default case is either whitespace (which doesn’t change whether we can consume a leading `*`) or it breaks and returns.
