### PR TITLE
fix(53181): Overloads Are Not Generated as Expected When Using JsDocOverload Tag to Declare Overloads of Functions Assigned to a Prototype

### LINKED ISSUE #53181: Overloads Are Not Generated as Expected When Using `@Overload` Tag to Declare Overloads of Functions Assigned to a Prototype
# Bug Report

When using the [`@overload`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#overload-support-in-jsdoc) tag to declare overloads of functions assigned to a prototype (e.g. `Foo.prototype.bar`) the overloads are not generated as expected. However, for functions that are not assigned to a prototype it works.

### 🔎 Search Terms

`overload`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `overload`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230309&filetype=js#)

### 💻 Code

Type declarations are generated for the following code:

```ts
export function Foo() {}

/**
 * @overload
 * @param {string} a
 *
 * @return {void}
 */

/**
 * @overload
 * @param {number} a
 * @param {string} b
 *
 * @return {void}
 */

/**
 * @param {string|number} a
 * @param {string} [b]
 *
 * @return {void}
 */
Foo.prototype.bar = function(a, b) {}
```

### 🙁 Actual behavior

```typescript
export function Foo(): void;
export class Foo {
    /**
     * @overload
     * @param {string} a
     *
     * @return {void}
     */
    /**
     * @overload
     * @param {number} a
     * @param {string} b
     *
     * @return {void}
     */
    /**
     * @param {string|number} a
     * @param {string} [b]
     *
     * @return {void}
     */
    bar(a: string | number, b?: string): void;
}
```

### 🙂 Expected behavior

```typescript
export function Foo(): void;
export class Foo {
    /**
     * @overload
     * @param {string} a
     *
     * @return {void}
     */
    /**
     * @overload
     * @param {number} a
     * @param {string} b
     *
     * @return {void}
     */
    /**
     * @param {string|number} a
     * @param {string} [b]
     *
     * @return {void}
     */
    bar(a: string): void;

    bar(a: number, b?: string): void;
}
```

Compare this to generating type declarations for the following code:

```javascript
/**
 * @overload
 * @param {string} a
 *
 * @return {void}
 */

/**
 * @overload
 * @param {number} a
 * @param {string} b
 *
 * @return {void}
 */

/**
 * @param {string|number} a
 * @param {string} [b]
 *
 * @return {void}
 */
export function bar(a, b) {}
```

Result:

```ts
export function bar(a: string): void;
export function bar(a: number, b: string): void;
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #53181

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -4179,14 +4182,14 @@ export function canHaveJSDoc(node: Node): node is HasJSDoc {
 export function getJSDocCommentsAndTags(hostNode: Node, noCache?: boolean): readonly (JSDoc | JSDocTag)[] {
     let result: (JSDoc | JSDocTag)[] | undefined;
     // Pull parameter comments from declaring function as well
-    if (isVariableLike(hostNode) && hasInitializer(hostNode) && hasJSDocNodes(hostNode.initializer!)) {
-        result = addRange(result, filterOwnedJSDocTags(hostNode, last((hostNode.initializer as HasJSDoc).jsDoc!)));
+    if (isVariableLike(hostNode) && hasInitializer(hostNode) && hostNode.initializer && hasJSDocNodes(hostNode.initializer) && hostNode.initializer.jsDoc) {
+        result = addRange(result, filterOwnedJSDocTags(hostNode, hostNode.initializer.jsDoc));
```
Comment (sandersn) [inline src/compiler/utilities.ts:4186]: I don't want to change the behaviour of other tags, which are only valid in the jsdoc immediately before a node.

When I changed this before (4 years ago?), it made it much easier to write and compile a correct sequence of

```ts
/** @template T @typedef ... */
/** @templete T @param ... */
function f...
```

And it's easier to explain. The only reason that multiple jsdocs are allowed for `@overload` is that the end of the last overload signature is ambiguous with the beginning of the implementation signature:

```ts
/**
 * @overload   
 * @param {number} x
 * @overload 
 * @param {string} x
 * -beginning of implementation-
 * @param {string | number} x
 */
function f (x) ...
```

**Review by sandersn — CHANGES_REQUESTED** [review]

**Review by sandersn — APPROVED** [review]
