### PR TITLE
Auto-include types for the jsx import source in the new jsx transforms

### LINKED ISSUE #40502: The presence of a `jsxImportSource` pragma or compiler option should implicitly include the types of the target module
This is a followup for #39199. If the pragma or compiler option is present, we should append the values to the `types` we look up, to reduce the duplication required in the compiler options.

### LINKED ISSUE #41118: TypeScript 4.1 + Preact: TypeScript does not pick up JSX.IntrinsicElements w. jsx: react-jsx
This is Re: #40502 cc @weswigham @DanielRosenwasser 

Using the new JSX transform and Preact as import source, TypeScript doesn't seem to pick up the JSX types that are shipped by Preact. It works as described in #40502 with additionally installed `@types/react`, but not with the types that come with Preact itself. Daniel suggested filing a new bug 😄 

**TypeScript Version:**  4.1.0-dev.20201015

**Search Terms:** Preact, JSX, JSX Transform

**Code**

```json
{
  "compilerOptions": {
    ...
    "jsx": "react-jsx", 
    "jsxImportSource": "preact",
    "types": ["preact/jsx-runtime"],
  }
}
```

This is the `d.ts` file that contains the JSX definitions: https://github.com/preactjs/preact/blob/master/jsx-runtime/src/index.d.ts

```ts
import { render } from "preact";

function App() {
  return (
    <>
      <h1>Hello World</h1>
    </>
  );
}

const node = document.querySelector("#app");
if (node) {
  render(<App />, node);
}

export default {};
```

**Note**: The JSX definitions are in the `jsx` and `jsxDEV`namespaces. I thought this might be an issue. But If I move JSX into the global namespace with

```ts
declare global {
  export import JSX = JSXInteral;
}
```
I get a compile error: **Cannot read property 'get' of undefined**

**Expected behavior:** Since TypeScript knows to pull in jsx from `preact/jsx-runtime`, I'd expect it to pull in JSX types from `preact/jsx-runtime/src/index.d.ts`. 

**Actual behavior:** JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)

**Playground Link:** I have a branch in a repo: https://github.com/ddprrt/preact-typescript-starter/tree/jsx-transform

**Related Issues:** #40502

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #41118
Fixes #40502

A note on #41118 for @ddprrt - `preact`'s source, in that case, is currently (re)exporting a `JSX` namespace under each factory function (multiple factory functions are used within a compilation). That's not quite what I'm looking for, for local JSX namespaces on implicit jsx runtime imports with this PR - a single top-level `JSX` export, alongside all those factory functions, is instead what I want to find. This should simplify the file a bit, as a single `export {JSXInternal as JSX} from "../../"` should suffice.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot user test this
@typescript-bot perf test this
@typescript-bot test this
@typescript-bot run dt

**Comment by ddprrt** [comment]
Oh cool, thank you! Is this something we should carry over to Preact? (I assume it's similar to tests/cases/compiler/jsxNamespaceImplicitImportJSXNamespace.tsx) -- I can work on a PR and maybe @marvinhagemeister is willing to guide me 😄

**Comment by weswigham** [comment]
Yeah, probably! For the implicitly added imports, the full factory is `jsx_import_source.jsx` or `jsx_import_source.jsxs` or `ksx_import_source.jsxDEV`, so the place we look for the JSX namespace within is the `jsx_import_source` itself. The change to preact is pretty small - adding `export {JSXInternal as JSX};` to the bottom is sufficient, but it can be cleaned up more from there (as you _probably_ don't need all the other reexports).

**Review by sandersn — APPROVED** [review]
I looked at the checker changes and they seem reasonable. I don't know enough about the program.ts change, but the comment's explanation makes sense to me.

**Review by orta — APPROVED** [review]
Mostly looked over the test cases, and this works like I'd expect 👍🏻

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -402,8 +402,10 @@ namespace ts {
      */
     export function getAutomaticTypeDirectiveNames(options: CompilerOptions, host: ModuleResolutionHost): string[] {
         // Use explicit type list from tsconfig.json
+        // jsxImportSource, if present and in use, creates implicit imports
+        const implicitImport = getJSXRuntimeImport(getJSXImplicitImportBase(options), options);
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts:406]: I am not sure we should be adding anything implicit if `types` is specified.  Thats exactly why that option exists.

File: src/compiler/program.ts [hunk 2]
```diff
@@ -3882,14 +3887,19 @@ namespace ts {
...
+    function getModuleNames(file: SourceFile, options: CompilerOptions): string[] {
+        const { imports, moduleAugmentations } = file;
         const res = imports.map(i => i.text);
         for (const aug of moduleAugmentations) {
             if (aug.kind === SyntaxKind.StringLiteral) {
                 res.push(aug.text);
             }
             // Do nothing if it's an Identifier; we don't need to do module resolution for `declare global`.
         }
+        const jsxRuntimeImport = getJSXRuntimeImport(getJSXImplicitImportBase(options, file), options);
```
Comment (sheetalkamat) [inline src/compiler/program.ts:3899]: You need test for incremental build and need to be handled in builder to store the file reference with this import.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -6009,8 +6009,8 @@ namespace ts {
         return jsx === JsxEmit.React || jsx === JsxEmit.ReactJSX || jsx === JsxEmit.ReactJSXDev;
     }
 
-    export function getJSXImplicitImportBase(compilerOptions: CompilerOptions, file: SourceFile): string | undefined {
-        const jsxImportSourcePragmas = file.pragmas.get("jsximportsource");
+    export function getJSXImplicitImportBase(compilerOptions: CompilerOptions, file?: SourceFile): string | undefined {
+        const jsxImportSourcePragmas = file?.pragmas.get("jsximportsource");
```
Comment (sheetalkamat) [inline src/compiler/utilities.ts:6013]: You would also need to mark `jsxImportSource` as affects module resolution  and `jsx` as well ? can you add test cases to make sure update in that reflects change in program.

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/moduleNameResolver.ts:406]: I add it to the `types` list because I don't think there's a great reason to make people repeat the same (or nearly the same) module name for both the `jsxImportSource` and the `types` flags - it just seems to me to make sense to include it in the `types` list, if present.

Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:406]: Question for @DanielRosenwasser then. If we are always going to implicitly add this we should process this separately in processTypeReferenceDirective in program.ts instead of modifying list here. 

I think apart from incremental we should add test where the file is added and later goes missing for this implicit import with and without types specified because we handle them specifically for watching in resolutionCache

Comment (DanielRosenwasser) [reply src/compiler/moduleNameResolver.ts:406]: Isn't this sort of a similar concept to how `tslib` is added with `importHelpers`? You've got an implicit import injected and we do some resolution to see if it's vaguely compatible, right?

@RyanCavanaugh and @andrewbranch might want to weigh in here as well.

**Comment by weswigham** [comment]
@sheetalkamat I've added the affixes to the compiler options to make them affect incremental emit, and added an incremental emit test.

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/moduleNameResolver.ts:406]: Yeah, I guess so - primary difference being we actually end up pulling the types from the module for checking things.

Comment (DanielRosenwasser) [reply src/compiler/moduleNameResolver.ts:406]: Looks like we might do the same for tslib?

```ts
function checkExternalEmitHelpers(location: Node, helpers: ExternalEmitHelpers) {
    if ((requestedExternalEmitHelpers & helpers) !== helpers && compilerOptions.importHelpers) {
        const sourceFile = getSourceFileOfNode(location);
        if (isEffectiveExternalModule(sourceFile, compilerOptions) && !(location.flags & NodeFlags.Ambient)) {
            const helpersModule = resolveHelpersModule(sourceFile, location);
            if (helpersModule !== unknownSymbol) {
                const uncheckedHelpers = helpers & ~requestedExternalEmitHelpers;
                for (let helper = ExternalEmitHelpers.FirstEmitHelper; helper <= ExternalEmitHelpers.LastEmitHelper; helper <<= 1) {
                    if (uncheckedHelpers & helper) {
                        const name = getHelperName(helper);
                        const symbol = getSymbol(helpersModule.exports!, escapeLeadingUnderscores(name), SymbolFlags.Value);
                        if (!symbol) {
                            error(location, Diagnostics.This_syntax_requires_an_imported_helper_named_1_which_does_not_exist_in_0_Consider_upgrading_your_version_of_0, externalHelpersModuleNameText, name);
                        }
                    }
                }
            }
            requestedExternalEmitHelpers |= helpers;
        }
    }
}
```

Comment (weswigham) [reply src/compiler/moduleNameResolver.ts:406]: Hm, for `importHelpers` we make a synthetic `import` within `collectExternalModuleReferences` - I could do that; hopefully it doesn't have other effects?

Comment (DanielRosenwasser) [reply src/compiler/moduleNameResolver.ts:406]: Not sure - @rbuckton might know more here too.

Comment (weswigham) [reply src/compiler/moduleNameResolver.ts]: I've changed the implementation to use the same synthetic-import method that we use for `importHelpers`.

File: src/compiler/program.ts [hunk 4]
```diff
@@ -2216,16 +2225,18 @@ namespace ts {
...
-                imports = [externalHelpersModuleReference];
+                if (options.importHelpers) {
+                    // synthesize 'import "tslib"' declaration
+                    imports = [createSyntheticImport(externalHelpersModuleNameText, file)];
+                }
+                const jsxImport = getJSXRuntimeImport(getJSXImplicitImportBase(options, file), options);
+                if (jsxImport) {
+                    // synthesize `import "base/jsx-runtime"` declaration
+                    imports ||= [];
+                    imports.push(createSyntheticImport(jsxImport, file));
```
Comment (sheetalkamat) [inline src/compiler/program.ts:2238]: Like this!

Comment (sheetalkamat) [inline src/compiler/program.ts:2238]:
```suggestion
                    (imports ||= []).push(createSyntheticImport(jsxImport, file));
```

File: src/testRunner/unittests/tscWatch/incremental.ts [hunk 5]
```diff
@@ -276,5 +276,33 @@ export interface A {
...
+            files: () => [
+                { path: libFile.path, content: libContent },
+                { path: `${project}/node_modules/react/jsx-runtime/index.d.ts`, content: jsxLibraryContent },
+                { path: `${project}/node_modules/react/package.json`, content: JSON.stringify({ name: "react", version: "0.0.1" }) },
+                { path: `${project}/node_modules/preact/jsx-runtime/index.d.ts`, content: jsxLibraryContent.replace("propA", "propB") },
+                { path: `${project}/node_modules/preact/package.json`, content: JSON.stringify({ name: "preact", version: "0.0.1" }) },
+                { path: `${project}/index.tsx`, content: `export const App = () => <div propA={true}></div>;` },
+                { path: configFile.path, content: JSON.stringify({ compilerOptions: jsxImportSourceOptions }) }
+            ],
+            modifyFs: host => host.writeFile(configFile.path, JSON.stringify({ compilerOptions: { ...jsxImportSourceOptions, jsxImportSource: "preact" } }))
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tscWatch/incremental.ts:305]: Can you add another case hen preact\*.d.ts file is missing and added.
And another when it is present and as incremental change goes missing.

**Comment by DanielRosenwasser** [comment]
btw I'm assuming I should wait on this for 4.1 RC - is that reasonable?

**Comment by weswigham** [comment]
Yeah, I'd rather this get into the RC than go out in 4.1 post-RC, since it affects the usability of the `react-jsx` transform quite a bit.

**Comment by sheetalkamat** [comment]
@weswigham the change now looks good and adding tests for https://github.com/microsoft/TypeScript/pull/41330#discussion_r515420969 should make it ready to merge

**Comment by DanielRosenwasser** [comment]
If we can get the tests in and passing as above, I'll merge this in and kick off the appropriate builds.

**Review by sheetalkamat — APPROVED** [review]
discussed offline with @weswigham that there is existing bug with incremental build with missing react files being available later which he will work on later  and is not related to this change.

**Comment by weswigham** [comment]
(specifically there's an issue with synthetic `imports` like the one used here and in `importHelpers` output that causes incremental emit to not pick up the dependency relationship between the files)

**Comment by DanielRosenwasser** [comment]
So what's the idea? Cherry-pick that to 4.1 but leave it out of 4.1 RC?

**Comment by weswigham** [comment]
Well, I got a fix for that underlying issue together pretty quickly, since the issue was actually pretty trivial - our public API sanitity checks forbid answering questions on synthetic declarations like those _we'd_ made - https://github.com/microsoft/TypeScript/pull/41346 is out. Up to you. If you can get a review from people you're happy with in a timeframe you're OK with, it can make it into the RC, otherwise saving the fix for post-RC cherry-pick is fine.

**Comment by Andarist** [comment]
@weswigham is there a way to make this work:
```ts
import { createElement } from 'react'
import { EmotionJSX } from './jsx-namespace'

export const jsx: typeof createElement
export namespace jsx {
  export import JSX = EmotionJSX
}
```
It complains about "Cannot redeclare block-scoped variable 'jsx'.ts(2451)" even though [this works](https://github.com/emotion-js/emotion/blob/0d3420034561908776024b2e3a3bfc5907804350/packages/react/types/index.d.ts#L109-L132) so it's clearly that `export import` syntax triggering this error here.

I've tried to make it work for several hours already and can't do it so far.

**Comment by weswigham** [comment]
It's a limitation of our alias-following logic in the binder, if I'm reading it right. If the `EmotionJSX` namespace was defined in the same file, it'd probably work, because then the binder would be able to know that `EmotionJSX` only refers to a namespace containing only types (by following the aliases within the file), which then means `jsx` contains only types, which is consequently safe to merge with `const jsx`. Across files, we don't know what `EmotionJSX` consists of until much later during checking, so we conservatively disallow the merge (since it might have some value member which could conflict with some value in the `const`)... at least that's my read on it.
Naively, I'd hope that
```ts
import type { EmotionJSX } from './jsx-namespace'
```
would cause it to work, but I don't know if we adjusted the alias following logic in the _binder_ to allow that to work when we added `import type`. (Consequently, if _that_ doesn't work, I think an isolated repro of the merge using `import type` and a new issue would be welcome)

**Comment by Andarist** [comment]
@weswigham thanks for the tip! I'm afraid it doesn't work though. It also gives me one additional error and that is:
> An import alias cannot reference a declaration that was imported using 'import type'

If I find the time I will create a repro case for this and report the appropriate issue. In the meantime I've filled a followup PR to this one: https://github.com/microsoft/TypeScript/pull/41476 , please take a look at it when you have time, would be great to fix the issue mentioned there before the final release.
