### PR TITLE
fix(43347): Exception occured when export type to existing commonJs imported name

### LINKED ISSUE #43347: Exception occured when `export type` to existing commonJs imported name
# Bug Report

### 🔎 Search Terms

`Node 216 was unexpected`

### 🕗 Version & Regression Information

```bash
tsc --version
Version 4.2.3

node --version
v14.16.0
```

#### `src/test.js`
```js
module.exports = {
  message: 'Hello world!',
}
```

#### `src/typtes.ts`
```ts
import test from './test';

export type test and.. exception occurs..
```
tsc doesn't care words after `export type test`.
#### `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es5",                               
    "module": "commonjs",                      
    "checkJs": true,   
    "outDir": "dist",  
    "rootDir": "./",            
    "strict": true,                 
    "baseUrl": "./",                       
    "esModuleInterop": true,                    
    "skipLibCheck": true,                    
    "forceConsistentCasingInFileNames": true  
  },
  "include": ["src/**/*"],
}

```

### 🙁 Actual behavior

Exception occurs.

```
/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:88055
                throw e;
                ^

Error: Debug Failure. Unexpected node.
Node 216 was unexpected.
    at getDeclarationSpaces (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:61876:41)
    at /home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:61867:85
    at Object.forEach (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:128:30)
    at getDeclarationSpaces (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:61867:28)
    at checkExportsOnMergedDeclarations (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:61808:41)
    at checkTypeAliasDeclaration (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:64285:13)
    at checkSourceElementWorker (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:65174:28)
    at checkSourceElement (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:65014:17)
    at Object.forEach (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:128:30)
    at checkSourceFileWorker (/home/taehoon/.nvm/versions/node/v14.16.0/lib/node_modules/typescript/lib/tsc.js:65332:20)
```

### 🙂 Expected behavior

I expect some proper error message.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43347

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -33565,11 +33565,14 @@ namespace ts {
                     case SyntaxKind.SourceFile:
                         return DeclarationSpaces.ExportType | DeclarationSpaces.ExportValue | DeclarationSpaces.ExportNamespace;
                     case SyntaxKind.ExportAssignment:
+                    case SyntaxKind.BinaryExpression:
+                        const node = <ExportAssignment | BinaryExpression>d;
```
Comment (sandersn) [inline src/compiler/checker.ts:33569]:
```suggestion
                        const node = d as ExportAssignment | BinaryExpression;
```

File: tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+==== tests/cases/compiler/test.js (0 errors) ====
+    module.exports = {
+       message: ""
+    }
+    
+==== tests/cases/compiler/types1.ts (2 errors) ====
+    import test from "./test";
+    export type test
+
```
Comment (sandersn) [inline tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt:15]: any idea what the error spans are here? (2,17) looks like it's *after* the last character of this line. Maybe the span needs to be adjusted in this case

**Review by sandersn — CHANGES_REQUESTED** [review]
Question about error span, plus a tiny style request

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:33569]: @sandersn what do you think about adding `consistent-type-assertions` rule to `eslint`?

Comment (sandersn) [reply src/compiler/checker.ts:33569]: might be worth a try -- for a while it was 50/50 but by now there might be many more new-style assertions than old-style ones, so the PR might not be *too* large.

File: tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt (hunk 2 above)
Comment (a-tarasyuk) [reply tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt:15]: @sandersn It seems for this case TS parser throws an error on the next `line(3,1): error TS1005: '=' expected.`. https://www.typescriptlang.org/play?#code/C4TwDgpgBMEM7ALACgVA

Comment (sandersn) [reply tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt:15]: For `Type expected.` as well? For that, I thought the span should cover `test` in `export type test`.

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:33569]: Do we need to create an issue for this? Or is it a normal open PR without issue?

Comment (sandersn) [reply src/compiler/checker.ts:33569]: Just a PR -- I'll mark it with the Housekeeping label. (The bot doesn't know about Housekeeping iirc, so it will still probably comment, unfortunately.)

File: tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt (hunk 2 above)
Comment (a-tarasyuk) [reply tests/baselines/reference/commonJsExportTypeDeclarationError.errors.txt:15]: Yes.

```ts
// @Filename: ./types1.ts
import test from "./test";
export type test

// @Filename: ./types4.ts
type test
```

```ts
tests/cases/compiler/types1.ts(2,17): error TS1110: Type expected.
tests/cases/compiler/types1.ts(3,1): error TS1005: '=' expected.
tests/cases/compiler/types4.ts(1,10): error TS1110: Type expected.
tests/cases/compiler/types4.ts(2,1): error TS1005: '=' expected.

    
==== tests/cases/compiler/types1.ts (2 errors) ====
    import test from "./test";
    export type test
                    
!!! error TS1110: Type expected.
    
    
!!! error TS1005: '=' expected.
==== tests/cases/compiler/types4.ts (2 errors) ====
    type test
             
!!! error TS1110: Type expected.
    
    
!!! error TS1005: '=' expected.
```

**Review by sandersn — APPROVED** [review]
