### PR TITLE
Fix abstract assignability restriction2

### LINKED ISSUE #4190: Abstract Constructor Assignability Not Restricted Enough
Consider the following code snippet:

```ts
abstract class A {}
class B extends A {}

var A2: new () => A;
var BCtor: typeof B;

A2 = A;
BCtor = A1;

```

The first assignment should fail because `A2` is new-able (it isn't an abstract constructor type), but no error is reported.

EDIT: simplified the sample.

### PR DESCRIPTION
**Pull request by aozgaa**
Fixes #4190

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5090,30 +5092,24 @@ namespace ts {
...
+                    // Note that in an extends-clause, targetSignatures is stripped, so the check never proceeds.
+                    let sourceSig = sourceSignatures[0];
+                    let targetSig = targetSignatures[0];
 
-                    if (sourceIsAbstract && !targetIsAbstract) {
-                        if (reportErrors) {
-                            reportError(Diagnostics.Cannot_assign_an_abstract_constructor_type_to_a_non_abstract_constructor_type);
-                        }
-                        return Ternary.False;
+                    result &= abstractSignatureRelatedTo(source, sourceSig, target, targetSig);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I think you could just make this `=`

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5137,6 +5133,40 @@ namespace ts {
...
+
+                        let sourceReturnType = sourceErasedSignature && getReturnTypeOfSignature(sourceErasedSignature);
+                        let targetReturnType = targetErasedSignature && getReturnTypeOfSignature(targetErasedSignature);
+
+                        let sourceReturnDecl = sourceReturnType && sourceReturnType.symbol && getDeclarationOfKind(sourceReturnType.symbol, SyntaxKind.ClassDeclaration);
+                        let targetReturnDecl = targetReturnType && targetReturnType.symbol && getDeclarationOfKind(targetReturnType.symbol, SyntaxKind.ClassDeclaration);
+                        let sourceIsAbstract = sourceReturnDecl && sourceReturnDecl.flags & NodeFlags.Abstract;
+                        let targetIsAbstract = targetReturnDecl && targetReturnDecl.flags & NodeFlags.Abstract;
+
+                        if (sourceIsAbstract && !(targetIsAbstract && targetDecl)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can you distribute the `!` so that its the following?

```TypeScript
if (sourceIsAbstract && (!targetIsAbstract || !targetDecl)) {
```

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -5137,6 +5133,40 @@ namespace ts {
...
+                        let sourceErasedSignature = getErasedSignature(sourceSig);
+                        let targetErasedSignature = getErasedSignature(targetSig);
+
+                        let sourceReturnType = sourceErasedSignature && getReturnTypeOfSignature(sourceErasedSignature);
+                        let targetReturnType = targetErasedSignature && getReturnTypeOfSignature(targetErasedSignature);
+
+                        let sourceReturnDecl = sourceReturnType && sourceReturnType.symbol && getDeclarationOfKind(sourceReturnType.symbol, SyntaxKind.ClassDeclaration);
+                        let targetReturnDecl = targetReturnType && targetReturnType.symbol && getDeclarationOfKind(targetReturnType.symbol, SyntaxKind.ClassDeclaration);
+                        let sourceIsAbstract = sourceReturnDecl && sourceReturnDecl.flags & NodeFlags.Abstract;
+                        let targetIsAbstract = targetReturnDecl && targetReturnDecl.flags & NodeFlags.Abstract;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can you wrap the `&` in parentheses?

**Comment by DanielRosenwasser** [comment]
:+1: after feedback
