### PR TITLE
Fix empty object intersections

### LINKED ISSUE #20225: Intersection of empty object type with empty object type is missing index signature
**TypeScript Version:**  2.7.0-dev.20171122

**Code**

```ts
type Dictionary = { [name: string]: string };

const intersectDictionaries = <F1 extends Dictionary, F2 extends Dictionary>(
  d1: F1,
  d2: F2,
): F1 & F2 => Object.assign({}, d1, d2);

const testDictionary = <T extends Dictionary>(_value: T) => { };

const d1 = {};
testDictionary(d1); // OK, d1 is inferred to be {}
const d2 = intersectDictionaries(d1, d1);
testDictionary(d2); // error, d2 is inferred to be {}
// compile error on the above line:
// ts-braces-not-assignable.ts(13,16): error TS2345: Argument of type '{}' 
//  is not assignable to parameter of type 'Dictionary'.
//   Index signature is missing in type '{}'.

const d3 = {
  s: '',
};
testDictionary(d3); // OK
const d4 = intersectDictionaries(d1, d3);
testDictionary(d4); // OK
const d5 = intersectDictionaries(d3, d1);
testDictionary(d5); // OK
const d6 = intersectDictionaries(d3, d3);
testDictionary(d6); // OK
```

**Expected behavior:**
No error

**Actual behavior:**
Error: 
```
ts-braces-not-assignable.ts(13,16): error TS2345: Argument of type '{}' is not assignable to parameter of type 'Dictionary'.
  Index signature is missing in type '{}'.
```

### LINKED ISSUE #27044: Index signature lost with empty intersections
**TypeScript Version:**  3.0.1 [TS Playground @ 12 SEP 2018]

**Search Terms:**
Index signature lost 
inconsistent intersections
empty intersections

**Code**
This is a dumbed-down version of what I have experienced.

Whenever 2 empty-object types are merged, the assumption of a type signature is lost.

```ts
type choices<IChoiceList extends {
    [key: string]: boolean;
}> = IChoiceList & {
    shoes:boolean;
    food:boolean;
};

type IMyChoiceList = {
    car: true
};

type IUnknownChoiceList = {};

var defaultChoices: choices<{}>;
var defaultChoicesAndEmpty: choices<{} & {}>;
/*
Type '{}' does not satisfy the constraint '{ [key: string]: boolean; }'.
  Index signature is missing in type '{}'.
*/

var myChoices: choices<IMyChoiceList>;
var myChoicesAndEmpty: choices<IMyChoiceList & {}>;

var unknownChoices: choices<IUnknownChoiceList>;
var unknownChoicesAndEmpty: choices<IUnknownChoiceList & {}>;
/*
Type '{}' does not satisfy the constraint '{ [key: string]: boolean; }'.
*/

```

**Expected behaviour:**
If `{}` is assumed to have a compliant type signature, then surely `{} & {}` should have the same.

**Actual behaviour:**
Whenever 2 empty-object types are merged, the assumption of a type signature is lost.
Errors commented above are for the single line of code above them.

**Playground Link:**
[TS Playground](https://www.typescriptlang.org/play/#src=type%20choices%3CIChoiceList%20extends%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20boolean%3B%0D%0A%7D%3E%20%3D%20IChoiceList%20%26%20%7B%0D%0A%20%20%20%20shoes%3Aboolean%3B%0D%0A%20%20%20%20food%3Aboolean%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20IMyChoiceList%20%3D%20%7B%0D%0A%20%20%20%20car%3A%20true%0D%0A%7D%3B%0D%0A%0D%0Atype%20IUnknownChoiceList%20%3D%20%7B%7D%3B%0D%0A%0D%0Avar%20defaultChoices%3A%20choices%3C%7B%7D%3E%3B%0D%0Avar%20defaultChoicesAndEmpty%3A%20choices%3C%7B%7D%20%26%20%7B%7D%3E%3B%0D%0A%2F*%0D%0AType%20'%7B%7D'%20does%20not%20satisfy%20the%20constraint%20'%7B%20%5Bkey%3A%20string%5D%3A%20boolean%3B%20%7D'.%0D%0A%20%20Index%20signature%20is%20missing%20in%20type%20'%7B%7D'.%0D%0A*%2F%0D%0A%0D%0Avar%20myChoices%3A%20choices%3CIMyChoiceList%3E%3B%0D%0Avar%20myChoicesAndEmpty%3A%20choices%3CIMyChoiceList%20%26%20%7B%7D%3E%3B%0D%0A%0D%0Avar%20unknownChoices%3A%20choices%3CIUnknownChoiceList%3E%3B%0D%0Avar%20unknownChoicesAndEmpty%3A%20choices%3CIUnknownChoiceList%20%26%20%7B%7D%3E%3B%0D%0A%2F*%0D%0AType%20'%7B%7D'%20does%20not%20satisfy%20the%20constraint%20'%7B%20%5Bkey%3A%20string%5D%3A%20boolean%3B%20%7D'.%0D%0A*%2F%0D%0A)

**Related Issues:** 
`Identity: A & A is equivalent to A.` [#3622](https://github.com/Microsoft/TypeScript/pull/3622)

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we properly preserve the origin of empty object literal types in intersections such that the logic that automatically infers index signatures for object literal types continues to work.

Fixes #20225.
Fixes #27044.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9097,8 +9097,11 @@ namespace ts {
             if (flags & TypeFlags.Intersection) {
                 return addTypesToIntersection(typeSet, includes, (<IntersectionType>type).types);
             }
-            if (getObjectFlags(type) & ObjectFlags.Anonymous && isEmptyObjectType(type)) {
-                includes |= TypeFlags.EmptyObject;
+            if (isEmptyAnonymousObjectType(type)) {
+                if (!(includes & TypeFlags.EmptyObject)) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: There's never a situation where we'd need to preserve multiple different empty types... Right?

**Comment by ahejlsberg** [comment]
I don't expect this to affect performance in any measurable way.

Regarding preservation of multiple empty object types, there are just two facts that matter for empty object types in intersections, one being whether the intersection contains _any_ empty object types, and the other being whether any of those object types originate in an object literal type (for which we can automatically infer an index signature). We didn't track the second fact at all before. With this PR we do because we preserve the (first) actual empty object type as opposed to substituting our generic `emptyObjectType`. Now, technically we should track whether _any_ (instead of the first) empty object type originated in an object literal type, but I honestly think this fix is good enough.

**Comment by weswigham** [comment]
Theoretically there's also the JSLiteral and JSXAttributes object flags (which can both appear on empty object literal types from JS files and jsx attributes, respectively) that affect noImplicitAny and excess property errors, respectively.
