### PR TITLE
fix(39022): If exported variable is renamed, tsc will generate code with a syntax error

### LINKED ISSUE #39022: If exported variable is renamed, tsc will generate code with a syntax error
**TypeScript Version:**  typescript@4.0.0-dev.20200611 (also 3.9.5)

**Search Terms:** exported variable renamed

**Code**

```ts
// a.ts
let foo = 1
export { foo as fooValue }
export const testFoo = (val: number) => {
  if (val <= ++foo) {
    return val
  }
  return foo
}
```

And then run this in a terminal:

``` bash
npx tsc a.ts && cat a.js
```

**Expected behavior:**

The command should output:

``` JavaScript
"use strict";
exports.__esModule = true;
exports.testFoo = exports.fooValue = void 0;
var foo = 1;
exports.fooValue = foo;
exports.testFoo = function (val) {
    if (val <= (exports.fooValue = ++foo)) {
        return val;
    }
    return foo;
};
```

**Actual behavior:**

The actual output is as the below, and `require('./a.js')` in Node.JS throws a `SyntaxError`

``` javascript
"use strict";
exports.__esModule = true;
exports.testFoo = exports.fooValue = void 0;
var foo = 1;
exports.fooValue = foo;
exports.testFoo = function (val) {
    if (val <= exports.fooValue = ++foo) {
        return val;
    }
    return foo;
};
```

If I run `require("./a.js")` in `node`, then it outputs:
```
Thrown:
R:\working\2\a.js:7
    if (val <= exports.fooValue = ++foo) {
        ^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid left-hand side in assignment
```

**Playground Link:** https://www.staging-typescript.org/play?target=1&module=1#

**Related Issues:** None

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39022

### CODE REVIEW

File: src/compiler/transformers/module/module.ts [hunk 1]
```diff
@@ -1872,8 +1872,8 @@ namespace ts {
                         // Mark the node to prevent triggering this rule again.
                         noSubstitution[getNodeId(expression)] = true;
                         expression = createExportExpression(exportName, expression);
+                        expression = isBinaryExpression(node.parent) ? factory.createParenthesizedExpression(expression) : expression;
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts:1875]: You cannot rely on parents in transformers, prior transformations may not set them so they are likely to be `undefined`.

**Review by rbuckton — CHANGES_REQUESTED** [review]
It would be better to always parenthesize. I am also considering whether it would be feasible to introduce our auto-parenthesization from the node factory into the substitution performed by the printer.

File: src/compiler/transformers/module/module.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/transformers/module/module.ts:1875]: > It would be better to always parenthesize.

@rbuckton Thanks for the feedback. Do you mean that `factory.create Parenthesized Expression (expression)` should be used without a preceding `if` condition? Or do you mean to consider adding changes to the `parenthesizerRules`?

**Review by rbuckton — APPROVED** [review]
The places where parens are unnnecessary is unavoidable at the moment. I'm investigating a change to the emitter that handles substitution as part of a transformation before printing which would remove the need for this fix, but unfortunately the change I'm investigating is not likely to be ready for 4.2.

Thanks for the effort on this!
