### PR TITLE
Properly propagate ObjectFlags.NonInferrableType, clean up non-inferrable code paths

### LINKED ISSUE #43962: Incorrectly inferred type for union types
# Bug Report

### 🔎 Search Terms

infer, never, union types, error TS2345

### 🕗 Version & Regression Information

- This changed between versions 3.5.1 and all newer versions up to 4.3.0-beta. 3.5.1 doesn't throw such error, there is the error in 3.6.2
  
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=3.6.3#code/C4TwDgpgBAKgFgSwHYHMA8MB8UC8UDeAUFCVAG4CGANgK4QBcsA3MaWApGgIIA0UAQnwDCmABStSpAPZgujAPJgMfLph4TJUGfwVLeAtRskyhutIKgiNASkbxk6ESwC+LUJCiK0AST7zseKLAiKh2IejemNa42PaoaP4shAAmEADGVBQATtAAZjRIacAIUkhQaTkUwBBx6FiiOQDONFTAdraw4RiYLKkZ2XkFRSVlALYUSjB8AEpiYFlSAFbpbVCilLQMsNE42NMdXlNQs73pmTlQ+YXFpVDAE92iSBAAHqvr1HTtMeRSCMkHSZ8LBJZDVLK5ChpaAAdSyE0gyTQADVsERJMkqhRGMiWJJ5jJGgB+RhSABGyyKLhSZwGlyGNzKCEacIRECR9XJi0YFCQIA6XKgzKgrLAiO6p36Fyuw1uBQA7vDJmIuXYoAAfEVK8VYDowJLuWHa9neJC5CBZHLJAAiWO6uFgUFe1SQyUaWrZSOQ5qyx2wROOUDsbnARs9prANGAKICax2sS6qKSfXOg2uIygFGSyQAyhBgMVUI0Y+IMVicRqPWL2TH1PiFmBGqSKStCB1ReKOyazRarbb7ijK12kajMD1CIQ0qVGsB6enSjCEMEYOAHN5Gs1oHgS5CilIsiBGMOI1HB5rhzGomEHDGfujSDlgDQsmVd8B9yBRNYAHTsSCicYwFEUQlwgUZ4ygBUlRA6pwOsPhAJgsCflA8CEImJDRh+KCMNQ6x8OpSdp1nYJmXXGBshQfNkU+LcoAARiSKckBnTMABIHRlRlF2XVdUHXTdgIg+8SGY1jSNQB0KggKoanCIJEEacjKOo2jrDxB982fMoJJQX8OAgUtNBIRDRExe4IKzXN80LFBGjMrE+HwTM+QABQbRh6KgZx8LrYyoFM8yKAgoL4KMUh7iA9YILIawbBcdSJwoNjvw2OgmCgAB6TKoEaOApBaZIoDJaApFyO5QzuRTlKyKjgBozYgA)

### 💻 Code

```ts
type Thing<T> = {
    value: T;
    pipe<A, B, C>(
        opA: Op<T, A>,
        opB: Op<A, B>,
        opC: Op<B, C>
    ): Thing<C>;
};
type Op<I, O> = (thing: Thing<I>) => Thing<O>;

declare function createThing<T>(result: T): Thing<T>;
declare function map<T, R>(project: (value: T) => R): Op<T, R>;
declare function tap<T>(next: (value: T) => void): Op<T, T>;

interface Wrapped<V> {
    data: V;
    props?: object;
}
declare function isWrapped<T>(obj: any): obj is Wrapped<T>;
declare function unwrap<T>(obj: T | Wrapped<T>): T;

type WrappedInferredData<T> = T extends Wrapped<infer R> ? R : T;
type WrappedInput<V> = () => Thing<V>;

declare function addSettings<V>(
    data: V | Wrapped<V>,
    props: object
): Wrapped<WrappedInferredData<V | Wrapped<V>>>;

const functionWithTypingIssue = <V>(factory: WrappedInput<V | Wrapped<V>>): Thing<V> => {
    return factory().pipe(map((item) => unwrap(item)), map(item => item), map(item => unwrap(item)));
}

const thisIsTargetValue = 1;

const a$ = functionWithTypingIssue(() => {
    const thing = createThing(thisIsTargetValue);
    return thing.pipe(
        map((data) => addSettings(data, { anyProp: 1 })),
        map((data) => data), // error here
        tap((v) => v)
    );
});

a$.value; // should be of type thisIsTargetValue
```
```
Argument of type 'Op<Wrapped<number>, Wrapped<number>>' is not assignable to parameter of type 'Op<Wrapped<number>, Wrapped<never>>'.
  Type 'Wrapped<number>' is not assignable to type 'Wrapped<never>'.
    Type 'number' is not assignable to type 'never'. 
```

### 🙁 Actual behavior

Type incorrectly infers from union type 

### 🙂 Expected behavior

Type should be resolved correctly. `typeof thisIsTargetValue === number` for this example

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #43962

The original bug required to changes to fix:

- The `NonInferrableType` flag needs to be propagated from `aliasTypeArguments` to the type they're used in, but this was missed in at least one place.
- Inference returns `silentNeverType` as its marker type to say "don't infer from this", but it only checked for `source === silentNeverType`, which doesn't work when you use that type in another type. So this needs to be `NonInferrableType` too.

The rest of the changes are cleanups and documentation improvements.

- It turns out that `nonInferrableType` is redundant with `silentNeverType`, and there are other types like `anyFunctionType`, `autoType`, and `autoArrayType` which are also used as marker types for this same purpose. They all can just use the flag without any changes in behavior.
- `nonInferrableAnyType` looks like it should be `NonInferrableType`, but making it have that flag breaks things. It turns out that if you just use `anyType`, nothing breaks.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this faster

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -786,10 +786,10 @@ namespace ts {
 
         const anyType = createIntrinsicType(TypeFlags.Any, "any");
         const autoType = createIntrinsicType(TypeFlags.Any, "any");
+        autoType.objectFlags |= ObjectFlags.NonInferrableType;
```
Comment (weswigham) [inline src/compiler/checker.ts:789]:
```suggestion
        const autoType = createIntrinsicType(TypeFlags.Any, "any", ObjectFlags.NonInferrableType);
```

Comment (jakebailey) [reply src/compiler/checker.ts:789]: Oops!

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -17196,6 +17191,7 @@ namespace ts {
             result.mapper = mapper;
             result.aliasSymbol = aliasSymbol || type.aliasSymbol;
             result.aliasTypeArguments = aliasSymbol ? aliasTypeArguments : instantiateTypes(type.aliasTypeArguments, mapper);
+            result.objectFlags |= result.aliasTypeArguments ? getPropagatingFlagsOfTypes(result.aliasTypeArguments, /*excludeKinds*/ 0) : 0;
```
Comment (weswigham) [inline src/compiler/checker.ts:17194]: Huh, this is interesting because this is redundant for `TypeReference` anonymous types (since those internally collect propagating flags from their type arguments), but required for any other anonymous object type with an alias. Go figure. I wonder if we should be propagating these object flags through conditional types, too... We already preserve them through intersections and unions. (We probably should be, since conditionals are "smart unions"...)

Comment (jakebailey) [reply src/compiler/checker.ts:17194]: Yes, I think they should. Right now I'm trying to go by hand to every `createAnonymousType`, `createObjectType`,... etc and see if there's anything missed, and it's a bit daunting because there's like 100 of them to verify, and nothing I've changed so far as actually changed any test.

I want to have something I can run while I'm debugging that'll observe each type during inference and walk down to see if there was a `NonInferrableType` flag that was missed, but I get stuck in stack overflows, so I don't quite know how I can do my sanity check.

Comment (jakebailey) [reply src/compiler/checker.ts:17194]: I think for this PR, I'm inclined to not try and go everywhere and add some more flag propagation without a way for me to check these; I just don't trust that I'm getting it right, and I don't have any way to observe the result.

This PR at least improves the one case I can test, and has a good amount of cleanup, so I'm happy with it (but I'll rerun the testing since I changed the structure of this quite a bit).

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this

**Review by weswigham — APPROVED** [review]
Assuming rwc and DT are good, this seems like a good consolidation.

**Comment by jakebailey** [comment]
Hm, those fp-ts things seem relevant. I was hoping those would go away, but I guess not.

**Comment by jakebailey** [comment]
Yeah, the actual fix in this PR breaks fp-ts's `Either` type, which looks a lot like one of the other types I saw break when I was working on propagating flags. I'll port a test.

**Comment by jakebailey** [comment]
Figured this out; we basically just needed to revert #26678, which worked around problems with non-inferrable types before the current non-inferrable flag and proper propagation was implemented.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this faster

**Review by weswigham — APPROVED** [review]

**Comment by jakebailey** [comment]
All the tests look clean, phew.
