### PR TITLE
Fix missing file name of extended source file in synchronizeProjectList when it is missing on disk

### LINKED ISSUE #40136: synchronizeProjectList returns an entry with an undefined fileName if there is a missing base tsconfig.json
When a folder contains a tsconfig.json with an `extends` property, and the base tsconfig is missing, `synchronizeProjectList` will return malformed data. The response contains a file entry that doesn't have a `fileName` property. This breaks the editor.

TS version: Can repro from 3.8 through current (4.1)

Repro steps:

1. Clone https://github.com/minestarks/repro-base-tsconfig.git
2. Open in Visual Studio using the Open Folder feature
3. Open index.ts
4. Observe that all language service features are broken

Log contains a `synchronizeProjectList` response like the following (the error is expected, the last file entry isn't)
```
   {
    "seq": 0,
    "type": "response",
    "command": "synchronizeProjectList",
    "request_seq": 230,
    "success": true,
    "body": [
        {
            "info": {
                "projectName": "E:/temp/repro_bas_tsconfig/tsconfig.json",
                "version": 1,
                "isInferred": false,
                "options": {
                    "configFilePath": "E:/temp/repro_bas_tsconfig/tsconfig.json",
                    "allowNonTsExtensions": true
                },
                "languageServiceDisabled": false
            },
            "files": [
                {
                    "fileName": "C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.d.ts",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "fileName": "C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.es5.d.ts",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "fileName": "C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.dom.d.ts",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "fileName": "C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.webworker.importscripts.d.ts",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "fileName": "C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.scripthost.d.ts",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "fileName": "E:/temp/repro_bas_tsconfig/index.ts",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "fileName": "E:/temp/repro_bas_tsconfig/tsconfig.json",
                    "isSourceOfProjectReferenceRedirect": false
                },
                {
                    "isSourceOfProjectReferenceRedirect": false
                }
            ],
            "projectErrors": [
                {
                    "message": "Cannot read file 'E:/temp/repro_bas_tsconfig/tsconfig_base.json'.",
                    "category": "error",
                    "code": 5083
                }
            ]
        }
    ]
}
```

Full log:
<details>
Info 0    [12:4:19.754] Starting TS Server
Info 1    [12:4:19.756] Version: 4.0.1-rc
Info 2    [12:4:19.756] Arguments: C:\vs\intpreview.16\MSBuild\Microsoft\VisualStudio\NodeJs\node.exe C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.0\tsserver.js --cancellationPipeName \\.\pipe\tsserver-cancellation-ProjectHost-169420 --useSingleInferredProject --locale en-US --suppressDiagnosticEvents --enableTelemetry --allowLocalPluginLoads --npmLocation C:\vs\intpreview.16\MSBuild\Microsoft\VisualStudio\NodeJs\npm.cmd --globalPlugins @vsintellicode/typescript-intellicode-plugin --pluginProbeLocations c:\vs\intpreview.16\common7\ide\commonextensions\microsoft\typescript --typingSafeListLocation c:\vs\intpreview.16\common7\ide\commonextensions\microsoft\typescript\typingSafeList.json --eventPort 7183
Info 3    [12:4:19.756] Platform: win32 NodeVersion: 12 CaseSensitive: false
Info 4    [12:4:19.756] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [12:4:19.761] Binding...
Info 6    [12:4:19.796] eventPort: event "typingsInstallerPid" queued, but socket not yet initialized
Info 7    [12:4:19.798] request:
    {"seq":218,"command":"status"}
Perf 8    [12:4:19.799] 218::status: elapsed time (in milliseconds) 0.4921
Info 9    [12:4:19.799] response:
    {"seq":0,"type":"response","command":"status","request_seq":218,"success":true,"body":{"version":"4.0.1-rc"}}
Info 10   [12:4:19.802] request:
    {"seq":222,"command":"configure","arguments":{"preferences":{"includeAutomaticOptionalChainCompletions":true,"includeCompletionsForModuleExports":true,"includeCompletionsWithInsertText":true,"allowTextChangesInNewFiles":true,"lazyConfiguredProjectsFromExternalProject":false,"currentTSServerVersion":"4.0","quotePreference":"auto","importModuleSpecifierPreference":"relative"},"extraFileExtensions":[{"extension":".js","scriptKind":1,"isMixedContent":false},{"extension":".ts","scriptKind":3,"isMixedContent":false},{"extension":".ascx","scriptKind":1,"isMixedContent":true},{"extension":".aspx","scriptKind":1,"isMixedContent":true},{"extension":".cshtml","scriptKind":1,"isMixedContent":true},{"extension":".htm","scriptKind":1,"isMixedContent":true},{"extension":".html","scriptKind":1,"isMixedContent":true},{"extension":".master","scriptKind":1,"isMixedContent":true},{"extension":".vbhtml","scriptKind":1,"isMixedContent":true},{"extension":".vue","scriptKind":7,"isMixedContent":true}]}}
Info 11   [12:4:19.802] reload projects.
Info 12   [12:4:19.803] Before ensureProjectForOpenFiles:
Info 13   [12:4:19.803] Open files: 
Info 13   [12:4:19.803] After ensureProjectForOpenFiles:
Info 14   [12:4:19.803] Open files: 
Info 14   [12:4:19.803] Host file extension mappings updated
Info 15   [12:4:19.803] response:
    {"seq":0,"type":"response","command":"configure","request_seq":222,"success":true}
Perf 16   [12:4:19.803] 222::configure: async elapsed time (in milliseconds) 0.9077
Info 17   [12:4:19.803] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":36148}}
Info 18   [12:4:19.804] request:
    {"seq":223,"command":"configurePlugin","arguments":{"pluginName":"@vsintellicode/typescript-intellicode-plugin","configuration":{"returnLookupKey":true,"timeout":500}}}
Info 19   [12:4:19.805] response:
    {"seq":0,"type":"response","command":"configurePlugin","request_seq":223,"success":true}
Perf 20   [12:4:19.805] 223::configurePlugin: async elapsed time (in milliseconds) 0.4345
Info 21   [12:4:19.805] request:
    {"seq":224,"command":"openExternalProjects","arguments":{"projects":[{"projectFileName":"E:/temp/repro_bas_tsconfig/repro_bas_tsconfig","rootFiles":[{"fileName":"E:\\temp\\repro_bas_tsconfig\\index.ts","scriptKind":3},{"fileName":"E:\\temp\\repro_bas_tsconfig\\tsconfig.json","scriptKind":0}],"options":{"allowJs":false,"allowNonTsExtensions":false,"allowSyntheticDefaultImports":false,"allowUnreachableCode":false,"allowUnusedLabels":false,"alwaysStrict":false,"checkJs":false,"compileOnSave":true,"declaration":false,"declarationMap":false,"downlevelIteration":false,"emitBOM":false,"emitDeclarationOnly":false,"emitDecoratorMetadata":false,"esModuleInterop":false,"experimentalAsyncFunctions":false,"experimentalDecorators":false,"forceConsistentCasingInFileNames":false,"importHelpers":false,"inlineSourceMap":false,"inlineSources":false,"isolatedModules":false,"jsx":2,"keyofStringsOnly":false,"noEmit":false,"noEmitHelpers":false,"noEmitOnError":true,"noFallthroughCasesInSwitch":false,"noImplicitAny":false,"noImplicitReturns":false,"noImplicitThis":false,"noImplicitUseStrict":false,"noLib":false,"noResolve":false,"noStrictGenericChecks":false,"noUnusedLocals":false,"noUnusedParameters":false,"preserveConstEnums":false,"preserveSymlinks":false,"removeComments":false,"resolveJsonModule":false,"skipDefaultLibCheck":false,"skipLibCheck":false,"sourceMap":true,"strict":false,"strictBindCallApply":false,"strictFunctionTypes":false,"strictNullChecks":false,"strictPropertyInitialization":false,"stripInternal":false,"suppressExcessPropertyErrors":false,"suppressImplicitAnyIndexErrors":false,"target":1}}]}}
Info 22   [12:4:19.807] Opened configuration file E:/temp/repro_bas_tsconfig/tsconfig.json
Info 23   [12:4:19.810] FileWatcher:: Added:: WatchInfo: E:/temp/repro_bas_tsconfig/tsconfig.json 2000 undefined Project: E:/temp/repro_bas_tsconfig/tsconfig.json WatchType: Config file
Info 24   [12:4:19.811] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"E:/temp/repro_bas_tsconfig/tsconfig.json","reason":"Creating configured project in external project: E:/temp/repro_bas_tsconfig/repro_bas_tsconfig"}}
Info 25   [12:4:19.830] Config: E:/temp/repro_bas_tsconfig/tsconfig.json : {
 "rootNames": [
  "E:/temp/repro_bas_tsconfig/index.ts"
 ],
 "options": {
  "configFilePath": "E:/temp/repro_bas_tsconfig/tsconfig.json"
 }
}
Info 26   [12:4:19.831] DirectoryWatcher:: Added:: WatchInfo: e:/temp/repro_bas_tsconfig 1 undefined Project: E:/temp/repro_bas_tsconfig/tsconfig.json WatchType: Wild card directory
Info 27   [12:4:19.831] e for path e:/temp/repro_bas_tsconfig not found in cache...
Info 28   [12:4:19.831] Starting C:\vs\intpreview.16\MSBuild\Microsoft\VisualStudio\NodeJs\node.exe with args:
    ["C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/watchGuard.js","e:/temp/repro_bas_tsconfig"]
Info 29   [12:4:19.924] WatchGuard for path e:/temp/repro_bas_tsconfig returned: OK
Info 30   [12:4:19.926] Elapsed:: 95ms DirectoryWatcher:: Added:: WatchInfo: e:/temp/repro_bas_tsconfig 1 undefined Project: E:/temp/repro_bas_tsconfig/tsconfig.json WatchType: Wild card directory
Info 31   [12:4:19.926] Local plugin loading enabled; adding e:/temp/repro_bas_tsconfig to search paths
Info 32   [12:4:19.927] Loading global plugin @vsintellicode/typescript-intellicode-plugin
Info 33   [12:4:19.927] Enabling plugin @vsintellicode/typescript-intellicode-plugin from candidate paths: c:\vs\intpreview.16\common7\ide\commonextensions\microsoft\typescript,C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/tsserver.js/../../..
Info 34   [12:4:19.927] Loading @vsintellicode/typescript-intellicode-plugin from c:\vs\intpreview.16\common7\ide\commonextensions\microsoft\typescript (resolved to c:/vs/intpreview.16/common7/ide/commonextensions/microsoft/typescript/node_modules)
Info 35   [12:4:19.966] IntelliCode plugin: starting configuration: {"returnLookupKey":true,"timeout":500,"name":"@vsintellicode/typescript-intellicode-plugin"}
Info 36   [12:4:19.966] Plugin validation succeded
Info 37   [12:4:19.967] FileWatcher:: Added:: WatchInfo: E:/temp/repro_bas_tsconfig/index.ts 500 undefined Project:  WatchType: Closed Script info
Info 38   [12:4:19.970] Starting updateGraphWorker: Project: E:/temp/repro_bas_tsconfig/tsconfig.json
Info 39   [12:4:19.982] FileWatcher:: Added:: WatchInfo: C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.d.ts 500 undefined Project:  WatchType: Closed Script info
Info 40   [12:4:20.1] FileWatcher:: Added:: WatchInfo: C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.es5.d.ts 500 undefined Project:  WatchType: Closed Script info
Info 41   [12:4:20.269] FileWatcher:: Added:: WatchInfo: C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.dom.d.ts 500 undefined Project:  WatchType: Closed Script info
Info 42   [12:4:20.876] FileWatcher:: Added:: WatchInfo: C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.webworker.importscripts.d.ts 500 undefined Project:  WatchType: Closed Script info
Info 43   [12:4:20.893] FileWatcher:: Added:: WatchInfo: C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.scripthost.d.ts 500 undefined Project:  WatchType: Closed Script info
Info 44   [12:4:21.334] DirectoryWatcher:: Added:: WatchInfo: E:/temp/repro_bas_tsconfig/node_modules/@types 1 undefined Project: E:/temp/repro_bas_tsconfig/tsconfig.json WatchType: Type roots
Info 45   [12:4:21.334] watchDirectory for E:/temp/repro_bas_tsconfig/node_modules/@types uses cached drive information.
Info 46   [12:4:21.335] Elapsed:: 1ms DirectoryWatcher:: Added:: WatchInfo: E:/temp/repro_bas_tsconfig/node_modules/@types 1 undefined Project: E:/temp/repro_bas_tsconfig/tsconfig.json WatchType: Type roots
Info 47   [12:4:21.336] Finishing updateGraphWorker: Project: E:/temp/repro_bas_tsconfig/tsconfig.json Version: 1 structureChanged: true Elapsed: 1365ms
Info 48   [12:4:21.336] Project 'E:/temp/repro_bas_tsconfig/tsconfig.json' (Configured)
Info 49   [12:4:21.336] 	Files (6)
	C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.d.ts
	C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.es5.d.ts
	C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.dom.d.ts
	C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.webworker.importscripts.d.ts
	C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.scripthost.d.ts
	E:/temp/repro_bas_tsconfig/index.ts

Info 50   [12:4:21.336] -----------------------------------------------
Info 51   [12:4:21.338] event:
    {"seq":0,"type":"event","event":"projectLoadingFinish","body":{"projectName":"E:/temp/repro_bas_tsconfig/tsconfig.json"}}
Info 52   [12:4:21.340] event:
    {"seq":0,"type":"event","event":"telemetry","body":{"telemetryEventName":"projectInfo","payload":{"projectId":"3f502759f642092971bbd228d9008f18ff3e36b61d6fc6b82166662401f61e63","fileStats":{"js":0,"jsSize":0,"jsx":0,"jsxSize":0,"ts":1,"tsSize":24,"tsx":0,"tsxSize":0,"dts":5,"dtsSize":1053382,"deferred":0,"deferredSize":0},"compilerOptions":{},"typeAcquisition":{"enable":false,"include":false,"exclude":false},"extends":true,"files":false,"include":false,"exclude":false,"compileOnSave":false,"configFileName":"tsconfig.json","projectType":"configured","languageServiceEnabled":true,"version":"4.0.1-rc"}}}
Perf 53   [12:4:21.340] 224::openExternalProjects: elapsed time (in milliseconds) 1534.9992
Info 54   [12:4:21.341] response:
    {"seq":0,"type":"response","command":"openExternalProjects","request_seq":224,"success":true,"performanceData":{"updateGraphDurationMs":1365},"body":true}
Info 55   [12:4:21.341] request:
    {"seq":225,"command":"compilerOptionsForInferredProjects","arguments":{"options":{"noLib":false,"removeComments":false,"noImplicitAny":false,"declaration":false,"sourceMap":true,"noResolve":false,"target":2,"jsx":2,"module":0,"emitBOM":false,"noEmit":false,"noEmitOnError":true,"preserveConstEnums":false,"suppressImplicitAnyIndexErrors":false,"allowNonTsExtensions":true,"isolatedModules":false,"compileOnSave":false,"noEmitHelpers":false,"inlineSourceMap":false,"inlineSources":false,"emitDecoratorMetadata":false,"experimentalDecorators":false,"experimentalAsyncFunctions":false,"suppressExcessPropertyErrors":false,"skipDefaultLibCheck":false,"allowUnusedLabels":false,"noImplicitReturns":false,"noFallthroughCasesInSwitch":false,"allowUnreachableCode":false,"forceConsistentCasingInFileNames":false,"allowSyntheticDefaultImports":false,"allowJs":false,"noImplicitUseStrict":false,"noImplicitThis":false,"skipLibCheck":false,"strictNullChecks":false,"noUnusedLocals":false,"noUnusedParameters":false,"alwaysStrict":false,"importHelpers":false,"stripInternal":false,"checkJs":false,"downlevelIteration":false,"strict":false,"strictFunctionTypes":false,"noStrictGenericChecks":false,"preserveSymlinks":false,"strictPropertyInitialization":false,"esModuleInterop":false,"emitDeclarationOnly":false,"keyofStringsOnly":false,"declarationMap":false,"resolveJsonModule":false,"strictBindCallApply":false}}}
Info 56   [12:4:21.342] Scheduled: *ensureProjectForOpenFiles*
Perf 57   [12:4:21.342] 225::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.7337
Info 58   [12:4:21.342] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":225,"success":true,"body":true}
Info 59   [12:4:21.343] request:
    {"seq":226,"command":"applyChangedToOpenFiles","arguments":{"openFiles":[{"fileName":"E:\\temp\\repro_bas_tsconfig\\index.ts","scriptKind":3,"content":"\r\nconsole.log(\"foo\"); \r\n"}]}}
Info 60   [12:4:21.344] FileWatcher:: Close:: WatchInfo: E:/temp/repro_bas_tsconfig/index.ts 500 undefined Project:  WatchType: Closed Script info
Info 61   [12:4:21.344] Search path: E:/temp/repro_bas_tsconfig
Info 62   [12:4:21.345] ConfigFilePresence:: Current Watches: Config file:: File: E:/temp/repro_bas_tsconfig/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: E:/temp/repro_bas_tsconfig/index.ts Status: File added to open files impacted by this config file
Info 63   [12:4:21.345] For info: E:/temp/repro_bas_tsconfig/index.ts :: Config file name: E:/temp/repro_bas_tsconfig/tsconfig.json
Info 64   [12:4:21.346] Project 'E:/temp/repro_bas_tsconfig/tsconfig.json' (Configured)
Info 64   [12:4:21.346] 	Files (6)

Info 64   [12:4:21.346] -----------------------------------------------
Info 64   [12:4:21.346] Open files: 
Info 64   [12:4:21.346] 	FileName: E:/temp/repro_bas_tsconfig/index.ts ProjectRootPath: undefined
Info 64   [12:4:21.346] 		Projects: E:/temp/repro_bas_tsconfig/tsconfig.json
Perf 64   [12:4:21.346] 226::applyChangedToOpenFiles: elapsed time (in milliseconds) 3.3272
Info 65   [12:4:21.346] response:
    {"seq":0,"type":"response","command":"applyChangedToOpenFiles","request_seq":226,"success":true,"body":true}
Info 66   [12:4:21.347] request:
    {"seq":227,"command":"synchronizeProjectList","arguments":{"knownProjects":[],"includeProjectReferenceRedirectInfo":true}}
Perf 67   [12:4:21.348] 227::synchronizeProjectList: elapsed time (in milliseconds) 1.3018
Info 68   [12:4:21.348] response:
    {"seq":0,"type":"response","command":"synchronizeProjectList","request_seq":227,"success":true,"body":[{"info":{"projectName":"E:/temp/repro_bas_tsconfig/tsconfig.json","version":1,"isInferred":false,"options":{"configFilePath":"E:/temp/repro_bas_tsconfig/tsconfig.json","allowNonTsExtensions":true},"languageServiceDisabled":false},"files":[{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.es5.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.dom.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.webworker.importscripts.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.scripthost.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"E:/temp/repro_bas_tsconfig/index.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"E:/temp/repro_bas_tsconfig/tsconfig.json","isSourceOfProjectReferenceRedirect":false},{"isSourceOfProjectReferenceRedirect":false}],"projectErrors":[{"message":"Cannot read file 'E:/temp/repro_bas_tsconfig/tsconfig_base.json'.","category":"error","code":5083}]}]}
Info 69   [12:4:23.342] request:
    {"seq":228,"command":"openExternalProjects","arguments":{"projects":[{"projectFileName":"E:/temp/repro_bas_tsconfig/repro_bas_tsconfig","rootFiles":[{"fileName":"E:\\temp\\repro_bas_tsconfig\\index.ts","scriptKind":3},{"fileName":"E:\\temp\\repro_bas_tsconfig\\tsconfig.json","scriptKind":0}],"options":{"allowJs":false,"allowNonTsExtensions":false,"allowSyntheticDefaultImports":false,"allowUnreachableCode":false,"allowUnusedLabels":false,"alwaysStrict":false,"checkJs":false,"compileOnSave":true,"declaration":false,"declarationMap":false,"downlevelIteration":false,"emitBOM":false,"emitDeclarationOnly":false,"emitDecoratorMetadata":false,"esModuleInterop":false,"experimentalAsyncFunctions":false,"experimentalDecorators":false,"forceConsistentCasingInFileNames":false,"importHelpers":false,"inlineSourceMap":false,"inlineSources":false,"isolatedModules":false,"jsx":2,"keyofStringsOnly":false,"noEmit":false,"noEmitHelpers":false,"noEmitOnError":true,"noFallthroughCasesInSwitch":false,"noImplicitAny":false,"noImplicitReturns":false,"noImplicitThis":false,"noImplicitUseStrict":false,"noLib":false,"noResolve":false,"noStrictGenericChecks":false,"noUnusedLocals":false,"noUnusedParameters":false,"preserveConstEnums":false,"preserveSymlinks":false,"removeComments":false,"resolveJsonModule":false,"skipDefaultLibCheck":false,"skipLibCheck":false,"sourceMap":true,"strict":false,"strictBindCallApply":false,"strictFunctionTypes":false,"strictNullChecks":false,"strictPropertyInitialization":false,"stripInternal":false,"suppressExcessPropertyErrors":false,"suppressImplicitAnyIndexErrors":false,"target":1}}]}}
Perf 70   [12:4:23.343] 228::openExternalProjects: elapsed time (in milliseconds) 0.5764
Info 71   [12:4:23.343] response:
    {"seq":0,"type":"response","command":"openExternalProjects","request_seq":228,"success":true,"body":true}
Info 72   [12:4:23.343] request:
    {"seq":229,"command":"synchronizeProjectList","arguments":{"knownProjects":[],"includeProjectReferenceRedirectInfo":true}}
Perf 73   [12:4:23.344] 229::synchronizeProjectList: elapsed time (in milliseconds) 0.2643
Info 74   [12:4:23.344] response:
    {"seq":0,"type":"response","command":"synchronizeProjectList","request_seq":229,"success":true,"body":[{"info":{"projectName":"E:/temp/repro_bas_tsconfig/tsconfig.json","version":1,"isInferred":false,"options":{"configFilePath":"E:/temp/repro_bas_tsconfig/tsconfig.json","allowNonTsExtensions":true},"languageServiceDisabled":false},"files":[{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.es5.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.dom.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.webworker.importscripts.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.scripthost.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"E:/temp/repro_bas_tsconfig/index.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"E:/temp/repro_bas_tsconfig/tsconfig.json","isSourceOfProjectReferenceRedirect":false},{"isSourceOfProjectReferenceRedirect":false}],"projectErrors":[{"message":"Cannot read file 'E:/temp/repro_bas_tsconfig/tsconfig_base.json'.","category":"error","code":5083}]}]}
Info 75   [12:4:23.853] Running: *ensureProjectForOpenFiles*
Info 76   [12:4:23.853] Before ensureProjectForOpenFiles:
Info 77   [12:4:23.853] Project 'E:/temp/repro_bas_tsconfig/tsconfig.json' (Configured)
Info 77   [12:4:23.853] 	Files (6)

Info 77   [12:4:23.853] -----------------------------------------------
Info 77   [12:4:23.853] Open files: 
Info 77   [12:4:23.853] 	FileName: E:/temp/repro_bas_tsconfig/index.ts ProjectRootPath: undefined
Info 77   [12:4:23.853] 		Projects: E:/temp/repro_bas_tsconfig/tsconfig.json
Info 77   [12:4:23.853] After ensureProjectForOpenFiles:
Info 78   [12:4:23.853] Project 'E:/temp/repro_bas_tsconfig/tsconfig.json' (Configured)
Info 78   [12:4:23.853] 	Files (6)

Info 78   [12:4:23.853] -----------------------------------------------
Info 78   [12:4:23.853] Open files: 
Info 78   [12:4:23.853] 	FileName: E:/temp/repro_bas_tsconfig/index.ts ProjectRootPath: undefined
Info 78   [12:4:23.853] 		Projects: E:/temp/repro_bas_tsconfig/tsconfig.json
Info 78   [12:4:23.854] got projects updated in background, updating diagnostics for E:/temp/repro_bas_tsconfig/index.ts
Info 79   [12:4:23.854] event:
    {"seq":0,"type":"event","event":"projectsUpdatedInBackground","body":{"openFiles":["E:/temp/repro_bas_tsconfig/index.ts"]}}
Info 80   [12:4:25.867] request:
    {"seq":230,"command":"synchronizeProjectList","arguments":{"knownProjects":[],"includeProjectReferenceRedirectInfo":true}}
Perf 81   [12:4:25.867] 230::synchronizeProjectList: elapsed time (in milliseconds) 0.3291
Info 82   [12:4:25.867] response:
    {"seq":0,"type":"response","command":"synchronizeProjectList","request_seq":230,"success":true,"body":[{"info":{"projectName":"E:/temp/repro_bas_tsconfig/tsconfig.json","version":1,"isInferred":false,"options":{"configFilePath":"E:/temp/repro_bas_tsconfig/tsconfig.json","allowNonTsExtensions":true},"languageServiceDisabled":false},"files":[{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.es5.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.dom.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.webworker.importscripts.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"C:/Program Files (x86)/Microsoft SDKs/TypeScript/4.0/lib.scripthost.d.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"E:/temp/repro_bas_tsconfig/index.ts","isSourceOfProjectReferenceRedirect":false},{"fileName":"E:/temp/repro_bas_tsconfig/tsconfig.json","isSourceOfProjectReferenceRedirect":false},{"isSourceOfProjectReferenceRedirect":false}],"projectErrors":[{"message":"Cannot read file 'E:/temp/repro_bas_tsconfig/tsconfig_base.json'.","category":"error","code":5083}]}]}
Perf 83   [12:4:26.890] GC::before 40667416, after 40391640
</details>

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #40136

### CODE REVIEW

File: src/testRunner/unittests/tsserver/projects.ts [hunk 1]
```diff
@@ -1481,6 +1481,48 @@ namespace ts.projectSystem {
...
+            };
+            const host = createServerHost([file, config, libFile]);
+            const projectService = createProjectService(host);
+            projectService.openClientFile(file.path);
+            const knownProjects = projectService.synchronizeProjectList([], /*includeProjectReferenceRedirectInfo*/ true);
+            assert.deepEqual(knownProjects[0].files, [
+                { fileName: libFile.path, isSourceOfProjectReferenceRedirect: false },
+                { fileName: file.path, isSourceOfProjectReferenceRedirect: false },
+                { fileName: config.path, isSourceOfProjectReferenceRedirect: false },
+                { fileName: `${tscWatch.projectRoot}/tsconfig_base.json`, isSourceOfProjectReferenceRedirect: false },
```
Comment (uniqueiniquity) [inline src/testRunner/unittests/tsserver/projects.ts:1522]: Why include it instead of removing it from the response? Are there other cases where TSServer could tell us to expect a file that doesn't actually exist?

Comment (uniqueiniquity) [reply src/testRunner/unittests/tsserver/projects.ts:1522]: That is, where we're not expected to then create it? Of course, move to file probably gives a non-existent file path but expects us to go create it - I'm not sure about that though.

Comment (sheetalkamat) [reply src/testRunner/unittests/tsserver/projects.ts:1522]: I am not sure. but i am certain that extendedSourceFiles should contain source file name that wasnt present. It would need another file exists check or another field just to return information if file is present or not and that seems unnecessary just to let project structure information. Let me know if you think its necessary. If it is we would probably need another field on tsconfig source files

Comment (sheetalkamat) [reply src/testRunner/unittests/tsserver/projects.ts:1522]: Ping @uniqueiniquity

Comment (uniqueiniquity) [reply src/testRunner/unittests/tsserver/projects.ts:1522]: Sorry for the delay.
After further thought, it's probably fine.
If you send VS a file here that doesn't exist, the user will see a somewhat strange diagnostic in the error list complaining that the file doesn't exist, but it won't break or crash. 
If we ask for semantic diagnostics for the tsconfig that does exist, will we get one complaining about the missing referenced file?

Comment (sheetalkamat) [reply src/testRunner/unittests/tsserver/projects.ts:1522]: thats correct

**Review by uniqueiniquity — APPROVED** [review]
