### PR TITLE
fix 'fileExists' check by using stat directly

### LINKED ISSUE #7037: 'big.js': EISDIR: illegal operation on a directory, read
When trying to import [big.js](https://github.com/MikeMcl/big.js/) package, TypeScript attempts to read it as file, resulting in EISDIR error.

For repro, create the following tsconfig.json:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "outDir": "lib",
    "module": "commonjs",
    "target": "es5",
    "baseUrl": ".",
    "paths": {
      "*": [
        "*", 
        "node_modules/*"
      ]
    }
  },
  "files": ["test.js"]
}
```

and source file:
```javascript
import 'big.js';
```

And execute:
```sh
npm install big.js
tsc
```

The result:
```log
test.js(1,8): error TS5012: Cannot read file 'C:/Test/ts-eisdir/node_modules/big.js': EISDIR: illegal operation on a directory, read
```

The [npm package name rules](https://docs.npmjs.com/files/package.json) say the name can't start with a period, but it seems it's allowed to contain a period. And although it's recommended not to have "js" in the name, it's not disallowed.

### PR DESCRIPTION
**Pull request by vladima**
fixes #7037

### CODE REVIEW

**Comment by mhegazy** [comment]
any perf impact?

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -462,6 +462,31 @@ namespace ts {
                 return useCaseSensitiveFileNames ? path : path.toLowerCase();
             }
 
+            const enum FileSystemEntryKind {
+                File,
+                Directory
+            }
+            function fileSystemEntryExists(path: string, entryKind: FileSystemEntryKind): boolean {
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: Add a newline

File: src/compiler/sys.ts [hunk 2]
```diff
@@ -462,6 +462,31 @@ namespace ts {
...
+                File,
+                Directory
+            }
+            function fileSystemEntryExists(path: string, entryKind: FileSystemEntryKind): boolean {
+                try {
+                    const stat = _fs.statSync(path);
+                    switch (entryKind) {
+                        case FileSystemEntryKind.File: return stat.isFile();
+                        case FileSystemEntryKind.Directory: return stat.isDirectory();
+                    }
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: I think this should be moved out of the `try`

Comment (vladima) [inline src/compiler/sys.ts]: moving it out of try wont make any difference since `try` prevents optimization for the entire function. I've considered extracting this into a separate function but given that I don't see any perf differences when compiling Monaco I don't think we need to do this.

**Comment by vladima** [comment]
got an offline signoff by @mhegazy
