### PR TITLE
Demote priority of JS completions

### LINKED ISSUE #48498: IntelliSense in JavaScript is broken when documenting a context for a function in argument (`this` replaced by `globalThis`)

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #48498

Unchecked JS files gather identifier-based completions. Currently, this search happens instead of `getCompletionEntriesFromSymbols` for TS/checked JS files. However, identifier-based completions are much lower quality and can be ignored by some editors.

Identifier-based completions should be gathered last, after gathering other completions. That's what this PR does.

### CODE REVIEW

**Comment by andrewbranch** [comment]
Ah, I think your code is basically right but your description is off a bit. There’s a big chunk of completions that already _does_ run first and doesn’t discriminate much between checked and unchecked files: `getCompletionData` which gathers relevant symbols. `getCompletionEntriesFromSymbols` runs both for checked and unchecked files too, converting those symbols to actual completion entries. The part you shifted forwards is just about _keywords_. Those were indeed getting shadowed by the identifiers in the file. It sounded like you were saying that unchecked JS files don’t get any symbol-based / semantic completions whatsoever, which would have been extremely surprising, but thankfully turns out not to be the case.

File: src/services/completions.ts [hunk 1]
```diff
@@ -535,14 +539,30 @@ namespace ts.Completions {
...
             }
+        }
 
-            getCompletionEntriesFromSymbols(
+        for (const literal of literals) {
+            insertSorted(entries, createCompletionEntryForLiteral(sourceFile, preferences, literal), compareCompletionEntries, /*allowDuplicates*/ true);
+        }
+
+        if (!isChecked) {
+            const uniqueNames = getCompletionEntriesFromSymbols(
```
Comment (andrewbranch) [inline src/services/completions.ts:565]: So this actually changes the order for unchecked files from

1. symbols
2. identifiers
3. keywords

to

1. keywords
2. symbols
3. identifiers

and I think we still want symbols first.

The (pre-existing) two huge calls to `getCompletionEntriesFromSymbols` are identical—can we lift and deduplicate that from the if/else? Then, let’s maintain `uniqueNames` from the result of that throughout the rest of this function so we don’t have to repeatedly regenerate it from `entries`.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 1 above)
Comment (sandersn) [reply src/services/completions.ts:565]: Ah, that makes sense. When I was moving the code around, I missed that `entries` was side-effected by `getCompletionEntriesFromSymbols`, and I assumed that the two calls were different since there would be no good reason to duplicate calls like that.

The code is much more elegant now, although reading it raises more questions than before. But those were questions that were hidden by the previous structure, in my opinion.

Comment (andrewbranch) [reply src/services/completions.ts]: Yeah, the important work is done by mutation and the return value is bonus info... not the best

Comment (andrewbranch) [reply src/services/completions.ts]: Yeah, the important work is done by mutation and the return value is bonus info... not the best

File: src/services/completions.ts [hunk 2]
```diff
@@ -507,68 +507,36 @@ namespace ts.Completions {
...
+            importCompletionNode,
+            recommendedCompletion,
+            symbolToOriginInfoMap,
+            symbolToSortTextMap,
+            isJsxIdentifierExpected,
+            isRightOfOpenTag,
+        );
 
         if (keywordFilters !== KeywordCompletionFilters.None) {
             const entryNames = new Set(entries.map(e => e.name));
```
Comment (andrewbranch) [inline src/services/completions.ts:542]: Isn’t this now equivalent to `uniqueNames`? And if you add to it inside the loop, you can use it in place of line 550 too, I think.

**Comment by sandersn** [comment]
@typescript-bot run dt

(Trying to fix the on-demand DT run)

**Comment by sandersn** [comment]
@typescript-bot run dt 

trying again

File: src/services/completions.ts [hunk 3]
```diff
@@ -668,6 +642,7 @@ namespace ts.Completions {
         uniqueNames: UniqueNameSet,
         target: ScriptTarget,
         entries: SortedArray<CompletionEntry>): void {
+        const entryNames = new Set(entries.map(e => e.name));
```
Comment (andrewbranch) [inline src/services/completions.ts:645]: GitHub isn’t showing me where this function gets called, but is this one redundant with `uniqueNames` too?

Comment (sandersn) [reply src/services/completions.ts:645]: Yep! I forgot to update that one, but it's the JS identifier-based completion path that I moved to the end of the function.
(So technically it's not required to add items to uniqueNames, but I'm going to, in order to avoid future surprises.)
