### PR TITLE
Error on invalid uses of namespace export

### LINKED ISSUE #37012: Intellisense breaks when using "export * as ns from"
**TypeScript Version:**  3.9.0-dev.20200224
**VSCode Version:** 1.42.1

**Search Terms:**
export * as from

**Expected behavior:**
`export * as ns from` should report error when reference to a non-existent path.

image

**Actual behavior:**
However, if any change has been made to the file, the error disappears.

image

The error information from console Log(Window) is:

```
[2020-02-25 20:51:22.034] [renderer3] [error] TreeError [MarkersView] Tree element not found: [object Object]: Error: TreeError [MarkersView] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:135:14)
    at t.ObjectTreeModel.isCollapsed (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:134:122)
    at H.isCollapsed (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:1070:430)
    at K.autoReveal (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:6311:830)
    at K.onActiveEditorChanged (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:6308:1005)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:6307:862
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:113:203
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at e.doHandleActiveEditorChangeEvent (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5780:290)
    at e.handleActiveEditorChange (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5780:88)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5779:583
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at e.doSetGroupActive (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5956:1001)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5956:516
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5931:915
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:4109:519
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2805:688
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at o (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:294:938)
    at c.fire (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:116:845)
    at HTMLDivElement.s (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:122:368)
    at v.setSelectionRange (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:598:466)
    at o.writeToTextArea (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:578:711)
    at m._setAndWriteTextAreaState (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:595:747)
    at m.writeScreenReaderContent (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:595:877)
    at m._setHasFocus (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:595:576)
    at m.focusTextArea (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:594:907)
    at C.focusTextArea (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2121:912)
    at V.focus (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2147:23)
    at Object.focusTextArea (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2142:111)
    at h (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2034:732)
    at g._onMouseDown (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2034:766)
    at file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2032:559
    at HTMLDivElement.<anonymous> (file:///D:/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:561:292)
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by andrewbranch**
- Check module specifier of `export * as ns from './specifier'`
- Check for emit helpers presence
- Check that `export * as ns from './specifier'` does not target an `export =` module

Fixes #37012

### CODE REVIEW

**Comment by andrewbranch** [comment]
@rbuckton can you confirm whether the import helpers check is correct/sufficient here? I noticed via the [playground](https://www.typescriptlang.org/play/?target=1&module=1#code/KYDwDg9gTgLgBAKjgQwM5wGYQpqEC2cA5GgCYZFA) that `export * as ns` actually uses the `__importStart` helper, whereas `export *` uses `__export`.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -33961,16 +33961,10 @@ namespace ts {
 
             checkGrammarExportDeclaration(node);
             if (!node.moduleSpecifier || checkExternalImportOrExportDeclaration(node)) {
-                if (node.exportClause) {
```
Comment (sandersn) [inline src/compiler/checker.ts:33964]: which part checks for the helper?

Comment (andrewbranch) [reply src/compiler/checker.ts:33964]: Line 33985. Previously, `export * as ns` took the true side of the if statement on line 33964. Much of what what needed to happen (resolving the module specifier target, checking for helpers) was already happening in the false/else side, so the change here is primarily just routing `export * as ns` through the same code path as `export *`.
