### PR TITLE
fix(36238): No spelling suggestion/quick fix for misspelled uses of an import

### LINKED ISSUE #36238: No spelling suggestion/quick fix for misspelled uses of an import
```ts
// ./foo.ts

export class SomeThing {
    
}
```

```ts
// ./bar.ts

import { SomeClass } from "./foo.js";

SomeClas
```

**Expected**: "Cannot find name 'SomeClas'. Did you mean 'SomeClass'?"
**Actual**: Standard "Cannot find name 'SomeClas'." error.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #36238

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -23922,12 +23922,26 @@ namespace ts {
...
+                if (startsWith(candidateName, "\"")) {
+                    return undefined;
+                }
+
+                if (candidate.flags & meaning) {
+                    return candidateName;
+                }
+
+                if (candidate.flags & SymbolFlags.Alias) {
+                    const target = resolveAlias(candidate);
```
Comment (andrewbranch) [inline src/compiler/checker.ts]: I guess you only want to do this if the symbol’s `links.target !== resolvingSymbol`. I would probably write a `tryResolveAlias` which checks for that and then returns either `resolveAlias(symbol)` or `undefined`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -23922,12 +23922,35 @@ namespace ts {
...
+                        return candidateName;
+                    }
+                }
+
+                return undefined;
             }
         }
 
-        function markPropertyAsReferenced(prop: Symbol, nodeForCheckWriteOnly: Node | undefined, isThisAccess: boolean) {
+        function tryResolveAlias(symbol: Symbol): Symbol | undefined {
```
Comment (andrewbranch) [inline src/compiler/checker.ts]: Nit: can we move this to be right next to `resolveAlias` itself for visibility?

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: @andrewbranch Oke.
