### PR TITLE
Fix #7397: Remove error checks for noEmit and out* compiler options combined.

### LINKED ISSUE #7397: noEmit should be allowed with outDir
And possibly with other `out` variations. Ideally, `noEmit` should have priority over output related options.

Reasoning: I have a syntax checking script that should not actually write files. My build script relies on `tsconfig.json` which has `outDir` compiler option set.

Syntax check command: 
```
> tsc --noEmit 2>&1 | pipe_it_somewhere_for_syntax_checking
```

Build command:
```
> tsc
```

tsconfig.json
```
{
   ...
   "outDir": "build/"
   ...
}
```

Error: `error TS5053: Option 'noEmit' cannot be specified with option 'outDir'.`

### PR DESCRIPTION
**Pull request by anilanar**
Fixes #7397.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@anilanar thanks for the PR. Can you add a set of tests in `tests/cases/compiler` to demonstrate the combination of `noEmit` with `outFile`, `outDir`, and `declaration`?

**Comment by anilanar** [comment]
@DanielRosenwasser Done. I'm not sure if file names fit to a general philosophy (if any?) of naming them.

File: src/compiler/program.ts [hunk 1]
```diff
@@ -1746,24 +1746,7 @@ namespace ts {
...
-                    programDiagnostics.add(createCompilerDiagnostic(Diagnostics.Option_0_cannot_be_specified_with_option_1, "noEmit", "outDir"));
-                }
-
-                if (options.declaration) {
-                    programDiagnostics.add(createCompilerDiagnostic(Diagnostics.Option_0_cannot_be_specified_with_option_1, "noEmit", "declaration"));
-                }
-            }
-            else if (options.allowJs && options.declaration) {
+            if (options.allowJs && options.declaration) {
                 programDiagnostics.add(createCompilerDiagnostic(Diagnostics.Option_0_cannot_be_specified_with_option_1, "allowJs", "declaration"));
```
Comment (mhegazy) [inline src/compiler/program.ts]: && !options.noEmit

Comment (anilanar) [inline src/compiler/program.ts]: @mhegazy That would reflect the old behaviour. But I gave this a thought and I chose to do it this way because:

Is `allowJs` incompatible with `declaration`? Then why does the compiler try to hide the error when `noEmit` is true? Maybe I should add `&& !options.noEmit` and let this be discussed somewhere else.

**Comment by mhegazy** [comment]
Thanks!
