### PR TITLE
fix(43444): Make JSDoc function signatures work on returned function expressions

### LINKED ISSUE #43444: Make JSDoc function signatures work on returned function expressions
# Suggestion

## 🔍 Search Terms

JSDoc function return

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Make [this](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=10&pc=1&useJavaScript=true#code/BTCUAIF4D5wbwFDmeA9AKnUl53gAIAOAhgE7EC28AzgC6kCWAdgOYC+4x2KeRZlNes3bgARt2TpUE0gFNaAV1JNwAMwVMAxrQYB7Fat27gxADRiIiHDjmLlncAGoxAbglsEbUGDdA) work:

```ts
(() => {
    /**
     * @param {string} a
     * @param {string} b
     */
    return function foo(a, b) {
        return a + b;
    }
})();
```

Current behavior is that the JSDoc comment has no effect, leaving `a` and `b` to be implicit `any` errors.

Semi-related: #39588

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43444

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Thanks @a-tarasyuk! 🙌

File: tests/baselines/reference/jsdocSignatureOnReturnedFunction.js [hunk 1]
```diff
@@ -0,0 +1,50 @@
+//// [jsdocSignatureOnReturnedFunction.js]
+function f1() {
+    /**
```
Comment (sandersn) [inline tests/baselines/reference/jsdocSignatureOnReturnedFunction.js:3]: can you add a test with `@type` as well?

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -2600,7 +2600,9 @@ namespace ts {
             parent.kind === SyntaxKind.PropertyDeclaration ||
             parent.kind === SyntaxKind.ExpressionStatement && node.kind === SyntaxKind.PropertyAccessExpression ||
             getNestedModuleDeclaration(parent) ||
-            isBinaryExpression(node) && node.operatorToken.kind === SyntaxKind.EqualsToken) {
+            isBinaryExpression(node) && node.operatorToken.kind === SyntaxKind.EqualsToken ||
+            isReturnStatement(parent) && parent.expression && (isFunctionExpression(parent.expression) || isArrowFunction(parent.expression))
```
Comment (sandersn) [inline src/compiler/utilities.ts:2604]: 1. You don't need to check the expression, just allow all return statements to be checked for jsdoc. This means that all jsdoc searches will walk up through return statements, but all searches should. (Especially since most jsdoc searches originate from functions.)
2. If I'm wrong, then this should be rewritten like so:
```suggestion
            isReturnStatement(parent) && node === parent.expression && (isFunctionExpression(node) || isArrowFunction(node))
```

**Review by sandersn — CHANGES_REQUESTED** [review]

File: tests/baselines/reference/jsdocSignatureOnReturnedFunction.js (hunk 1 above)
Comment (a-tarasyuk) [reply tests/baselines/reference/jsdocSignatureOnReturnedFunction.js:3]: I've added tests with `@type`

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -2600,7 +2600,9 @@ namespace ts {
             parent.kind === SyntaxKind.PropertyDeclaration ||
             parent.kind === SyntaxKind.ExpressionStatement && node.kind === SyntaxKind.PropertyAccessExpression ||
             getNestedModuleDeclaration(parent) ||
-            isBinaryExpression(node) && node.operatorToken.kind === SyntaxKind.EqualsToken) {
+            isBinaryExpression(node) && node.operatorToken.kind === SyntaxKind.EqualsToken ||
+            isReturnStatement(parent) && node === parent.expression && (isFunctionExpression(node) || isArrowFunction(node))
```
Comment (sandersn) [inline src/compiler/utilities.ts:2604]: I'm pretty sure this is OK:

```suggestion
            isReturnStatement(parent))
```

Since any node that starts a jsdoc walk will want to see all relevant jsdocs, and a jsdoc on a return statement will always (I think?) be relevant.

**Review by sandersn — APPROVED** [review]
