### PR TITLE
fix(49629): Crash in find-all-refs/rename when using module.exports/export= with arrays/primitives

### LINKED ISSUE #49629: Crash in find-all-refs/rename when using module.exports/export= with arrays/primitives
```json5
// @filename: tsconfig.json
{
    "compilerOptions": {
        "target": "esnext",
        "strict": true,
        "outDir": "./out",
        "allowSyntheticDefaultImports": true
    }
}
```

```js
// @filename: a-js.js
module.exports = [];
```

```js
// @filename: b-js.js
module.exports = 123;
```

```ts
// @filename: a-ts.ts
export = [];
```

```ts
// @filename: b-ts.ts
export = 123;
```

```ts
// @filename: root.ts
import * as /*0*/ajsNamespace from "./a-js.js"
import /*1*/ajsDefault from "./a-js.js"
import * as /*2*/bjsNamespace from "./a-js.js"
import /*3*/bjsDefault from "./a-js.js"

import * as /*4*/atsNamespace from "./a-ts.js"
import /*5*/atsDefault from "./a-ts.js"
import * as /*6*/btsNamespace from "./a-ts.js"
import /*7*/btsDefault from "./a-ts.js"
```

Rename at each marker.

```
Response received: rename (220). Request took 12 ms. Success: false . Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at getExportEqualsLocalSymbol (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:137691:33)
    at getImport (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:137662:38)
    at Object.getImportOrExportSymbol (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:137573:68)
    at getImportOrExportReferences (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:139266:56)
    at getReferencesAtLocation (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:139196:17)
    at getReferencesInContainer (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:139130:21)
    at getReferencesInContainerOrFiles (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:138629:21)
    at getReferencedSymbolsForSymbol (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:138620:21)
    at Object.getReferencedSymbolsForNode (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:138370:34)
    at Object.findReferenceOrRenameEntries (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:138025:47)
    at getReferencesWorker (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:166524:41)
    at Object.findRenameLocations (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:166511:24)
    at c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:176651:102
    at searchPosition (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:176886:38)
    at getPerProjectReferences (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:176854:42)
    at getRenameLocationsWorker (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:176650:37)
    at IpcIOSession.Session.getRenameLocations (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:178257:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:177132:61)
    at c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:179260:96
    at IpcIOSession.Session.executeWithRequestId (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:179251:28)
    at IpcIOSession.Session.executeCommand (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:179260:41)
    at IpcIOSession.Session.onMessage (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:179288:35)
    at process.<anonymous> (c:/Users/drosen/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220621/node_modules/typescript/lib/tsserver.js:183454:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49629

### CODE REVIEW

File: src/services/importTracker.ts [hunk 1]
```diff
@@ -577,22 +578,22 @@ namespace ts.FindAllReferences {
         }
     }
 
-    function getExportEqualsLocalSymbol(importedSymbol: Symbol, checker: TypeChecker): Symbol {
+    function getExportEqualsLocalSymbol(importedSymbol: Symbol, checker: TypeChecker): Symbol | undefined {
         if (importedSymbol.flags & SymbolFlags.Alias) {
-            return Debug.checkDefined(checker.getImmediateAliasedSymbol(importedSymbol));
```
Comment (gabritto) [inline src/services/importTracker.ts:582]: I'm not sure why those `Debug.checkDefined` calls were here originally, but it seems like a good change to remove them to avoid crashes. As far as I understand, at least in the `export = _` and `module.exports = _` cases, it makes no sense to expect a symbol to always be defined.

**Review by gabritto — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
