### PR TITLE
Don’t create expando declarations on alias symbols

### LINKED ISSUE #26912: JS should allow merging/expando properties on imports
```js
// Filename: mod.js
export const Ns = function () { }

// @Filename: use.js
import { Ns } from './mod'
Ns.expando = 1
```

**Expected behavior:**
No error, and Ns has property 'expando'

**Actual behavior:**
Error, 'expando' not found on 'Ns'.

This merge shouldn't be allowed in Typescript, but it will work in Javascript, so it should be allowed there.

### LINKED ISSUE #38218: Adding property to 'import Vue from 'vue'' import makes 'Vue' no longer constructible
*TS Template added by @mjbvz*

**TypeScript Version**: 3.9.0-dev.20200427

**Search Terms**
- Vue
- constructor
- javascript

---

- VSCode Version: 1.44.2
- OS Version: Win10

Does this issue occur when all extensions are disabled?: Yes

Intellisense broken after added property.

Steps to Reproduce:

In a _test_ directory :
```bash
yarn init -y
yarn add vue
```

Create a javascript file _index.js_ :
```javascript
import Vue from 'vue';
Vue.config.productionTip = true;
const vm = new Vue("");
```

Intellisense work :

index jsOK

Intellisense broken :

index jsNOK

____

### A second test with another module (dayjs)

Intellisense work : 

dayjs_test_OK

Intellisense broken :

dayjs_test

____

### A third test with a function constructor in index.js
It always works, _test_ property exists.

plain_object

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #38218

This is also the antifix of #26912 🤷‍♂️. #32626 didn’t actually solve #26912; it just stopped reporting errors on it. #38218 shows that when an expando merges with an alias in JS, the alias target is actually unreachable. It looks like going in the other direction and making expandos on aliases actually work would be a bit more effort. I’m not sure anyone is asking for that anyway.

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -2986,7 +2986,9 @@ namespace ts {
                 const excludeFlags = SymbolFlags.ValueModuleExcludes & ~SymbolFlags.Assignment;
                 namespaceSymbol = forEachIdentifierInEntityName(entityName, namespaceSymbol, (id, symbol, parent) => {
                     if (symbol) {
-                        addDeclarationToSymbol(symbol, id, flags);
+                        if (!(symbol.flags & SymbolFlags.Alias)) {
```
Comment (sandersn) [inline src/compiler/binder.ts:2989]: should it also early-exit here? I can't remember how, or if, you can signal this from forEachIdentifierInEntityName.

**Comment by sandersn** [comment]
Also maybe other callers of forEachIdentifierInEntityName should not work on aliases either.

**Comment by andrewbranch** [comment]
You’re right; the check can actually be moved to the top of `bindPotentiallyMissingNamespaces`. I wasn’t thinking about the fact that the nested namespaces in the entity name can’t possibly be alias symbols.
