### PR TITLE
Instantiating a signature in the context of another should infer from return type predicates if they match up

### LINKED ISSUE #29819: JSX defaultProps fails with generic user-defined type guards that are static class members
**TypeScript Version:**  3.3.1

**Search Terms:** JSX React type guard generic static class member property

**Code**

Doesn't work (example 1):

```ts
class TestComponent extends React.Component<{ isAny: <T>(obj: any) => obj is T }> {
  static defaultProps = {
    isAny: TestComponent.isAny
  }

  // Type guard is defined as a static class property
  static isAny<T>(obj: any): obj is T {
    return true;
  }
}

const TestRender = () => <TestComponent /> // ERROR
```

Does work (example 2):

```ts
// Refactored type guard out of class
function isAny<T>(obj: any): obj is T {
    return true;
  }

class TestComponent extends React.Component<{ isAny: <T>(obj: any) => obj is T }> {
  static defaultProps = {
    isAny: isAny
  }
}

const TestRender = () => <TestComponent /> // no error
```

**Expected behavior:**

Example 1 should work without errors.

**Actual behavior:**

Error on `<TestComponent />`: `Property 'isAny' is missing in type '{}' but required in type 'Readonly<{ isAny: <T>(obj: any) => obj is T; }>'. [2741]`

**Playground Link:**  N/A (examples 1 and 2 both work at runtime but tsc reports an error at compile time).

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #29819

As it turns out, it's super important when the type parameter only appears in the return predicate position (however rare that may be).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20042,6 +20042,12 @@ namespace ts {
             });
             if (!contextualMapper) {
                 inferTypes(context.inferences, getReturnTypeOfSignature(contextualSignature), getReturnTypeOfSignature(signature), InferencePriority.ReturnType);
+                const signaturePredicate = getTypePredicateOfSignature(signature);
+                const contextualPredicate = getTypePredicateOfSignature(sourceSignature);
+                if (signaturePredicate && contextualPredicate && signaturePredicate.kind === contextualPredicate.kind &&
+                    (signaturePredicate.kind !== TypePredicateKind.Identifier || signaturePredicate.parameterIndex === (contextualPredicate as IdentifierTypePredicate).parameterIndex)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: would probably be a little safer to check `signaturePredicateKind === TypePredicateKind.This ||`, in case we add more kinds in the future.

In the meantime, it's quite a bit easier to read.

Comment (weswigham) [inline src/compiler/checker.ts]:
```suggestion
                    (signaturePredicate.kind === TypePredicateKind.This || signaturePredicate.parameterIndex === (contextualPredicate as IdentifierTypePredicate).parameterIndex)) {
```

Comment (weswigham) [reply src/compiler/checker.ts]: The "apply suggestion" feature of GH does not seem to work too well on `checker.ts`. @sandersn you know if we have someone we can complain at about things like that yet? 😄
