### PR TITLE
Enforce identical type constraints

### LINKED ISSUE #6210: Enforce type parameter identical-ness when class+interface merging
This should be an error:
```ts
class Foo<T extends Function> {
	n: T;
}
interface Foo<T extends Window> {
	y: T;
}
```
Currently whichever constraint came first wins

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #6210 and #6211.

Before class/interface merging, only interfaces needed to be checked for differing type parameter lists. Now classes and interfaces all need to be checked. Refactor the check into its own function as well.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14031,6 +14031,23 @@ namespace ts {
             }
         }
 
+        /** Check that type parameter lists are identical across multiple declarations */
+        function checkTypeParameterListsIdentical(node: ClassLikeDeclaration | InterfaceDeclaration, symbol: Symbol) {
+            let firstDecl: ClassLikeDeclaration | InterfaceDeclaration;
+            if (symbol.declarations.length > 1) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]:
```ts
if (symbol.declarations.length === 1) {
    return;
}
const firstDecl = symbol.declarations[0];
for (const declaration of symbol.declarations) {
    if (declaration === firstDecl) {
        continue;
    }

    // etc.
}
```

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -1311,7 +1311,7 @@
         "category": "Error",
         "code": 2427
     },
-    "All declarations of an interface must have identical type parameters.": {
+    "All declarations must have identical type parameters.": {
```
Comment (DanielRosenwasser) [inline src/compiler/diagnosticMessages.json]: This error message is only vaguely helpful at a glance. All class and interface declarations are named unless they are default exports (in which case they shouldn't get merged anyway), so let's use the name in the message.

```json
"All declarations of '{0}' must have identical type parameters."
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]: The second simplification is not safe because firstDecl needs to be `ClassLikeDecl | InterfaceDecl`, which might not be true if there's a module in there too.

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (sandersn) [inline src/compiler/diagnosticMessages.json]: Nice improvement.

**Comment by DanielRosenwasser** [comment]
:+1:
