### PR TITLE
Fix arrow expressions in conditional expressions, take N+1

### LINKED ISSUE #16241: [bug] Ternary + arrow function is not correctly parsed
**TypeScript Version:**  Online repl

**Code**

```ts
var a = b ? (c) : d => e;
```
https://www.typescriptlang.org/play/index.html#src=var%20a%20%3D%20b%20%3F%20(c)%3A%20d%20%3D%3E%20e%3B

**Expected behavior:**
It is valid javascript, thus it should be parsed correctly

**Actual behavior:**
It is parsed as
```js
var consequent = (c) : d => e
var a = b ? consequent
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #16241
See also: #48733

This is a revert of PR #48940 with #48788 applied.

I previously described #48788 as "permissive"; this is accurate in the sense that all of the existing TS code that we found in the wild is parsed correctly without a change in meaning. However, this does not compromise on the ideal that if it's legal JS, then we should parse it as such; the effect of this PR should be to get everything working as expected.

I recommend ignoring the first commit for sake of viewing the diff, as it's just setting up the tests in such a way to make sure we can view the JS and TS code side by side with the output.

---

If it's legal JS, we want to parse it as such. This means that in cases where the code is legal JS, we should see that:

1. The input JS should match the output JS.
2. The output of the TS file (containing the same code) should match the output of the JS file.

If it's a syntax error in JS, then we are free to interpret it how we need, i.e. to support TS features. Many of the tests are not legal JS.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot run dt

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -4343,10 +4343,10 @@ namespace ts {
             }
 
             const pos = getNodePos();
-            let expr = parseAssignmentExpressionOrHigher();
+            let expr = parseAssignmentExpressionOrHigher(/*disallowReturnTypeInArrowFunction*/ false);
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts:4346]: Note: the `disallow` is throwingme off. Consider `allow`, especially since technically TypeScript scenarios (where we usually allow) are the exception.

Comment (jakebailey) [reply src/compiler/parser.ts:4346]: Yeah, I need to rename this to something more reasonable. I think this is like the third name choice and it's still not good enough.

Comment (jakebailey) [reply src/compiler/parser.ts:4346]: Maybe `canParseReturnTypeInArrowFunction`?

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -4840,10 +4866,10 @@ namespace ts {
                 factory.createConditionalExpression(
                     leftOperand,
                     questionToken,
-                    doOutsideOfContext(disallowInAndDecoratorContext, parseAssignmentExpressionOrHigher),
+                    doOutsideOfContext(disallowInAndDecoratorContext, () => parseAssignmentExpressionOrHigher(/*disallowReturnTypeInArrowFunction*/ true)),
                     colonToken = parseExpectedToken(SyntaxKind.ColonToken),
                     nodeIsPresent(colonToken)
-                        ? parseAssignmentExpressionOrHigher()
+                        ? parseAssignmentExpressionOrHigher(/*disallowReturnTypeInArrowFunction*/ true)
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts:4872]: Is it intentional that you're being conservative in the false branch? If not, shouldn't this propagate an outer `disallowReturnTypeInArrowFunction`?

File: src/compiler/parser.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/parser.ts:4346]: `allowXxxYyyZzz` seems to be the more common naming scheme, so I'll just do that.

File: src/compiler/parser.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/parser.ts]: The problem here is when the conditional expression is nested but flat, as in this expression:

```ts
a ? b ? c : (d) : e => f
```

The intent is that it's parsed like this:

```ts
a ? (b ? c : (d)) : e => f
```

When parsing left to right, we'll be parsing the "false" side, and our scanner will contain:

```ts
(d) : e => f
```

If we aren't careful, we'll eat the colon because the caller said it was okay to parse it as an arrow expression with a return type.

But, I do think there's an improvement here; I should just inherit `allowReturnTypeInArrowFunction` from the caller. For most calls, it'll be `true` and allow the return type. Otherwise, we'll just remember downward that somewhere above, we're on the true side of a conditional expression.

Comment (jakebailey) [reply src/compiler/parser.ts]: I can't however figure out a test case that this matters for, but I think modifying it is correct.

Comment (jakebailey) [reply src/compiler/parser.ts]: FWIW the snippet `a ? b ? c : (d) : e => f` does not parse in today's TS, so I'm not worried about changing it.

Comment (DanielRosenwasser) [reply src/compiler/parser.ts]: Well it's something like this that breaks in the "conservative" case, right?

```ts
a ? b : (c): Type => c
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

File: src/compiler/parser.ts [hunk 3]
```diff
@@ -4840,10 +4867,10 @@ namespace ts {
                 factory.createConditionalExpression(
                     leftOperand,
                     questionToken,
-                    doOutsideOfContext(disallowInAndDecoratorContext, parseAssignmentExpressionOrHigher),
+                    doOutsideOfContext(disallowInAndDecoratorContext, () => parseAssignmentExpressionOrHigher(/*allowReturnTypeInArrowFunction*/ false)),
                     colonToken = parseExpectedToken(SyntaxKind.ColonToken),
                     nodeIsPresent(colonToken)
-                        ? parseAssignmentExpressionOrHigher()
+                        ? parseAssignmentExpressionOrHigher(allowReturnTypeInArrowFunction)
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts:4873]: We had a discussion over at https://github.com/microsoft/TypeScript/pull/49531#discussion_r900542195 about whether or not consistency between the true/false branches should win, or whether backwards compatibility should win for the false case.

In other words, should the following continue to parse?

```ts
a ? b : (c): Type => c
```

While we can propagate the flag here, having the two branches differ is confusing, and could make naive refactorings fail. I have a soft vote for disallowing in conditional types, but explicitly document it.

What do you think @ahejlsberg @sandersn?

Comment (jakebailey) [reply src/compiler/parser.ts:4873]: I am pro-backwards-compatibility; this was an oversight in that I had it this way in a previous change, but while working on one of the newer examples from the wild, I switched it back until I found the "real" fix as the token === ":" check in the arrow function parsing function.

File: src/compiler/parser.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/parser.ts]: Add the above as `parserArrowFunctionExpression17.ts`.

File: src/compiler/parser.ts (hunk 3 above)
Comment (jakebailey) [reply src/compiler/parser.ts:4873]: The relevant test case is [`e76fe4c` (#49531)](https://github.com/microsoft/TypeScript/pull/49531/commits/e76fe4c669b7d9a1d041c9f191d801b805ad9d23), which I fixed in [`8675dc1` (#49531)](https://github.com/microsoft/TypeScript/pull/49531/commits/8675dc142f78c784663e814dd4b57afe8669b428) before I had a test case.

File: tests/baselines/reference/parserArrowFunctionExpression10.js [hunk 4]
```diff
@@ -1,8 +0,0 @@
-//// [parserArrowFunctionExpression10.ts]
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/parserArrowFunctionExpression10.js:1]: Ugh, this is a rename, not a deletion.

Comment (jakebailey) [reply tests/baselines/reference/parserArrowFunctionExpression10.js:1]: Yeah, that's why I wanted to have my first commit be only test changes, so the following commits were clear as to what changed.

File: tests/baselines/reference/parserArrowFunctionExpression14(target=es3).errors.txt [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileJs.js(1,32): error TS8010: Type annotations can only be used in TypeScript files.
+tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileJs.js(1,40): error TS2304: Cannot find name 'd'.
+tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileJs.js(1,46): error TS2304: Cannot find name 'e'.
+tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileTs.ts(1,1): error TS2304: Cannot find name 'a'.
+tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileTs.ts(1,40): error TS2304: Cannot find name 'd'.
+tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileTs.ts(1,46): error TS2304: Cannot find name 'e'.
+
+
+==== tests/cases/conformance/parser/ecmascript5/ArrowFunctionExpressions/fileJs.js (7 errors) ====
+    a() ? (b: number, c?: string): void => d() : e; // Not legal JS; "Unexpected token ':'" at first colon
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/parserArrowFunctionExpression14(target=es3).errors.txt:14]: Is this comment supposed to reflect the runtime error?

Comment (jakebailey) [reply tests/baselines/reference/parserArrowFunctionExpression14(target=es3).errors.txt:14]: Yes, that's the parser error I get from the browser. I can drop these if they are confusing, I only had them in there to convince myself that in every case, the only ones with TS-y meanings were ones that were not valid JavaScript.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by jakebailey** [comment]
RWC and DT look good, perf is fine as well. Going to merge this to get this in for the beta.
