### PR TITLE
fix(37877): Export default child items not included in 'navtree'

### LINKED ISSUE #37877: Export default child items not included in 'navtree'
From https://github.com/microsoft/vscode/issues/94630

**TypeScript Version:**  3.9.0-dev.20200409

**Search Terms:**
- tsserver
- navtree

**Code**

```ts
export default {
    foo: 1,
  };
  export const hello = {
    world: 2,
  }; 
```

**Bug:**
The nav tree does not include an entry for `foo` in it:

```
[Trace  - 23:25:07.33] <syntax> Response received: navtree (6). Request took 4 ms. Success: true 
Result: {
    "text": "\"test\"",
    "kind": "module",
    "kindModifiers": "",
    "spans": [
        {
            "start": {
                "line": 1,
                "offset": 1
            },
            "end": {
                "line": 6,
                "offset": 6
            }
        }
    ],
    "childItems": [
        {
            "text": "default",
            "kind": "const",
            "kindModifiers": "export",
            "spans": [
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 3,
                        "offset": 5
                    }
                }
            ]
        },
        {
            "text": "hello",
            "kind": "const",
            "kindModifiers": "export",
            "spans": [
                {
                    "start": {
                        "line": 4,
                        "offset": 16
                    },
                    "end": {
                        "line": 6,
                        "offset": 4
                    }
                }
            ],
            "nameSpan": {
                "start": {
                    "line": 4,
                    "offset": 16
                },
                "end": {
                    "line": 4,
                    "offset": 21
                }
            },
            "childItems": [
                {
                    "text": "world",
                    "kind": "property",
                    "kindModifiers": "",
                    "spans": [
                        {
                            "start": {
                                "line": 5,
                                "offset": 5
                            },
                            "end": {
                                "line": 5,
                                "offset": 13
                            }
                        }
                    ],
                    "nameSpan": {
                        "start": {
                            "line": 5,
                            "offset": 5
                        },
                        "end": {
                            "line": 5,
                            "offset": 10
                        }
                    }
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37877

### CODE REVIEW

File: src/services/navigationBar.ts [hunk 1]
```diff
@@ -307,7 +307,18 @@ namespace ts.NavigationBar {
                 addNodeWithRecursiveChild(node, getInteriorModule(<ModuleDeclaration>node).body);
                 break;
 
-            case SyntaxKind.ExportAssignment:
+            case SyntaxKind.ExportAssignment: {
+                const expression = (<ExportAssignment>node).expression;
+                if (isObjectLiteralExpression(expression)) {
```
Comment (sheetalkamat) [inline src/services/navigationBar.ts:312]: Array?

Comment (a-tarasyuk) [reply src/services/navigationBar.ts:312]: @sheetalkamat I think it can be a new feature, however, in the current implementation Array elements are not available in NavigationBar for both cases not only for default exported arrays. 
Screenshot 2020-05-04 at 08 49 07
