### PR TITLE
Use minimal endings when generating declarations for js

### LINKED ISSUE #34624: module name mismatch in declaration
**TypeScript Version:**  3.7.0-dev.20191021

**Search Terms:**
- declaration
- modules

**Code**

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro

**Expected behavior:**

A valid `index.d.ts` file should be emitted.

**Actual behavior:**

The module is declared as `"versions.static"` on line 1, but is imported below as `"versions.static.js"` on line 10 (and not found).

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/blob/master/js/index.d.ts#L1

https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/blob/master/js/index.d.ts#L10

**Steps to reproduce**

1. Clone https://github.com/andyfleming/typescript-module-declaration-mismatch-repro
2. Run `npm install`
3. Run `npm run generate-types`
4. Observe declared `"versions.static"` module and import attempt as `"versions.static.js"`.

## Code from Repo

**package.json**

```json
{
  "name": "@example-org/example-package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "generate-types": "rm js/index.d.ts && tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/andyfleming/typescript-module-declaration-mismatch-repro.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/andyfleming/typescript-module-declaration-mismatch-repro/issues"
  },
  "homepage": "https://github.com/andyfleming/typescript-module-declaration-mismatch-repro#readme",
  "devDependencies": {
    "typescript": "3.7.0-dev.20191021"
  }
}
```

**tsconfig.json**

```js
/* Generated with tsc --init via TypeScript 3.7.0-beta */
{
  "compilerOptions": {
    "module": "commonjs",
    "allowJs": true,
    "declaration": true,
    "outFile": "./js/index.js",
    "emitDeclarationOnly": true,
    "strict": true,
    "esModuleInterop": true
  },
  "include": [
    "js/**/*"
  ]
}
```

**js/index.js**

```javascript
import versions from './versions.static.js';

export {
    versions
};
```

**js/versions.static.js**

```javascript
export default {
    "@a/b": "1.0.0",
    "@a/c": "1.2.3"
};
```

**js/index.d.ts** (sample output)

```typescript
declare module "versions.static" {    // <-- declared one way here
    var _default: {
        "@a/b": string;
        "@a/c": string;
    };
    export default _default;
}
declare module "index" {
    export { versions };
    import versions from "versions.static.js";   // <-- and different way here
}
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #34624

Fun fact! This was _mostly_ fixed with the addition of the `bundledPackageName` flag. All that was missing was passing in an option to our specifier generator for (bundled) js declaration emit. The declaration file we generate (when you add `"bundledPackageName": "mylib"`) now looks like
```ts
declare module "mylib/versions.static" {
    var _default: {
        "@a/b": string;
        "@a/c": string;
    };
    export default _default;
}
declare module "mylib" {
    export { versions };
    import versions from "mylib/versions.static";
}
```

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5479,7 +5479,7 @@ namespace ts {
                         specifierCompilerOptions,
                         contextFile,
                         moduleResolverHost,
-                        { importModuleSpecifierPreference: isBundle ? "non-relative" : "relative" },
+                        { importModuleSpecifierPreference: isBundle ? "non-relative" : "relative", importModuleSpecifierEnding: isBundle ? "minimal" : undefined },
```
Comment (sandersn) [inline src/compiler/checker.ts:5482]: Maybe this is easier to read? But maybe not, I just wanted to write it out for comparison.

```suggestion
                        isBundle ? { importModuleSpecifierPreference: "non-relative", importModuleSpecifierEnding: "minimal" } : { importModuleSpecifierPreference: "relative" },
```

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:5482]: Eh, I think I prefer having the single object literal, even if the condition happens to be the same for both fields.
