### PR TITLE
fix(43160): improve error location for functions without explicit return

### LINKED ISSUE #43160: JS typings, missing file reference for error TS2355 when tyiping functions with @type
# Bug Report

In javascript when defining a callback and applying the type to a function which doesn't return anything, an error of type TS2355 is raised. And this is the correct behavior.

However `tsc` fails to show both the file and the line number of the problem. This can be quite annoying when dealing with a very big project :D

### 🔎 Search Terms

* TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.
* jsdoc @type @callback

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about javascript

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useJavaScript=true#code/PQKhCgAIUgBAzAlgGwKaUQZ0wV1QOgCtMoZYBbAewBMc0Ns9gtdVS4BDHAFwAtKATpAAiHAHaJU9AEJTkHAG5ZuHUsHAAiHJnSZuAxAGNuGgNzhwoCNDiGOyZACMOhgNaQAYjjGH2sAajcOAJimJAA3gAKApTkWKgAPGI45I6oAgB8AL5qFlZw3ACeAA7o4V4+WdDq8N7GiJRikNyoegAUAJQRUJCGjZiUaPjIlADmbRoAcpSlGh3mOZZgBSVlFYZVIOocmIU+kLU+3A1NLXoATJ3dkJABQSGQGjvUZuBZQA)

### 💻 Code

```javascript
/**
 * @callback Func
 * @returns {Promise<number>}
 */

/** @type {Func} */
function test() {
  console.log("Nope");
}
```

### 🙁 Actual behavior

- The error TS2355 is correctly detected but the line number (and also the file when dealing with a project) is not reported

### 🙂 Expected behavior

- The tsc compiler should correctly report both line number and file

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #43160

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -30362,8 +30362,8 @@ namespace ts {
             else if (type && !hasExplicitReturn) {
                 // minimal check: function has syntactic return type annotation and no explicit return statements in the body
                 // this function does not conform to the specification.
-                // NOTE: having returnType !== undefined is a precondition for entering this branch so func.type will always be present
-                error(getEffectiveReturnTypeNode(func), Diagnostics.A_function_whose_declared_type_is_neither_void_nor_any_must_return_a_value);
+                // NOTE: returnType may not exist when func.type is denoted by jsdoc
+                error(getEffectiveReturnTypeNode(func) || func, Diagnostics.A_function_whose_declared_type_is_neither_void_nor_any_must_return_a_value);
```
Comment (sandersn) [inline src/compiler/checker.ts:30366]: all 4 four branches of this if at the end of the function now have `getEffectiveReturnTypeNode(func) || func`, so I'd lift it out before the first if as `const errorNode = getEffectiveReturnTypeNode(func) || func`

If you can, you should find or write a new test for the `type.flags & TypeFlags.Never` case above as well.

**Review by sandersn — CHANGES_REQUESTED** [review]
Very nice improvement. One request to make the function even easier to read.

File: src/compiler/checker.ts (hunk 1 above)
Comment (Zzzen) [reply src/compiler/checker.ts:30366]: 👌 👌 Got it.

**Review by sandersn — APPROVED** [review]
