### PR TITLE
fix(38081): 'Debug Failure. Invalid cast.' for convert import quick fix

### LINKED ISSUE #38081: 'Debug Failure. Invalid cast.' for convert import quick fix
From https://github.com/microsoft/vscode/issues/95398

**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
- quick fix
- code action

**Code**
For the TS:

```ts
const { foo } = require('bar');
```

1. Notice a suggestion to convert to an import.
1. Try triggering quick fixes for this suggestion

**Bug**
Exception:

```
[Trace  - 23:23:03.487] <semantic> Response received: getCodeFixes (211). Request took 1 ms. Success: false . Message: Error processing request. Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
    at Object.cast (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:1375:25)
    at getInfo (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133111:95)
    at doChange (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133101:22)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133094:96
    at Function.ChangeTracker.with (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:125643:17)
    at Object.getCodeActions (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:133094:64)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126791:77
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:465:25)
    at Object.getFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:126791:23)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:138580:35
    at Object.flatMap (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:465:25)
    at Proxy.getCodeFixesAtPosition (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:138578:23)
    at IOSession.Session.getCodeFixes (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:148674:64)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #38081

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
Tests failed due to linter errors (#38360) which are not related to changes

File: src/services/codefixes/requireInTs.ts [hunk 1]
```diff
@@ -5,25 +5,69 @@ namespace ts.codefix {
...
+            namedImports,
+            statement: cast(decl.parent.parent, isVariableStatement),
+            required: first(parent.arguments)
+        };
+    }
+
+    function tryCreateNamedImportsFromObjectBindingPattern(node: ObjectBindingPattern): NamedImports | undefined {
+        const elements: ImportSpecifier[] = [];
+        for (const element of node.elements) {
+            if (isIdentifier(element.name)) {
```
Comment (sandersn) [inline src/services/codefixes/requireInTs.ts:64]: so this will drop any nested elements? I would prefer that test 3 show this instead of showing that the code fix isn't available (or perhaps it would be better to add a test):

`const { a: { b }, c } = require('a')` will produce `import { c } from 'a'`, right?

File: tests/cases/fourslash/codeFixRequireInTs2.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+/// <reference path='fourslash.ts' />
+
+// @Filename: /a.ts
+////const { a } = [|require("a")|];
+
+verify.not.codeFixAvailable();
```
Comment (andrewbranch) [inline tests/cases/fourslash/codeFixRequireInTs2.ts:6]: I feel like maybe I’m missing something or my morning coffee hasn’t kicked in yet, but at first glance I don’t understand the connection between `allowSyntheticDefaultImports` and named bindings making the codefix not available. Since we don’t know anything about module `"a"`, it seems like it could be shaped like

```ts
export const a: string;
```

Which from JS we’d let you use `const { a } = require("a")` and in TS we’d let you use `import { a } from "a"` regardless of allowSynthetic/esModuleInterop, right?

File: src/services/codefixes/requireInTs.ts (hunk 1 above)
Comment (sandersn) [reply src/services/codefixes/requireInTs.ts:64]: Actually, I think the right behaviour would be to not offer the codefix if any element is not an identifier.

Comment (a-tarasyuk) [reply src/services/codefixes/requireInTs.ts:64]: > Actually, I think the right behaviour would be to not offer the codefix if any element is not an identifier.

Oke

File: tests/cases/fourslash/codeFixRequireInTs2.ts (hunk 2 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/codeFixRequireInTs2.ts:6]: I think your coffee is good 👍.

Comment (andrewbranch) [reply tests/cases/fourslash/codeFixRequireInTs2.ts:6]: So why isn’t this one available as a codefix now? Shouldn’t we get `import { a } from "a"` on this?

Comment (a-tarasyuk) [reply tests/cases/fourslash/codeFixRequireInTs2.ts:6]: > Actually, I think the right behaviour would be to not offer the codefix if any element is not an identifier.

I removed logic which tried to convert `ObjectBindingPattern` to named `NamedImports`.

File: src/services/codefixes/requireInTs.ts (hunk 1 above)
Comment (sandersn) [reply src/services/codefixes/requireInTs.ts]: Sorry, I wasn't clear on what I thought the codefix should do. I think it should trigger on

```js
const a = require('a')
const { a } = require('a')
```

and it should not trigger on

```js
const { a: { b } } = require('ab')
```

However, the current state is fine too -- it fixes the bug and does so with a less-complicated arbitrary cutoff. Do you want to merge as-is or go back to supporting a single level of destructuring?

Comment (a-tarasyuk) [reply src/services/codefixes/requireInTs.ts]: I'll add a single level of destructuring
