### PR TITLE
Fix type parameter lookup for TypeAlias LibraryManagedAttributes

### LINKED ISSUE #42240: Types used in JSX.LibraryManagedAttributes have to accept both provided type parameters
# Bug Report

### 🔎 Search Terms

LibraryManagedAttributes

### 🕗 Version & Regression Information

This issue manifests itself at least since 3.9 but I strongly suspect that it has been here since `JSX.LibraryManagedAttributes` were introduced to TS. It also happens in the latest nightly build.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSX/React

### ⏯ Playground Link

1. [Extra prop directly provided in LibraryManagedAttributes](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3ACUBTAQwGMSAzAvLcAcgKtpbTQBNzqANpXbhqeAHawSyAFzgiATxzk8dMhyIA6au0pFyAUQHks5cUTTjKp2DhrkkCcAG804d+HLx8xcFZt21A4AUgDKABoubh4xXj4kGObkBHT24EYmZiTOAL7RMe5xhAlJKWkZpuYAwkKwsC55BR5Fvon6ZUHpxpVEAIJERAQYAEYArvqwAAqMysQKDfkFLSXtqZ0VWVUAFhgCPOzi-YMj4w65i7HexeBtyWsOAJLmQ5IY1EdDYxMLTYVXraV7uAnsdXtQapQ6h8ThMADwAFQAfD9fst5EpHs9ErA3htzPUALxRX4FHgYABucmcolqsAActZyHIpC8AObgRq-TlNNGKZTgAAyIwIwgUAFlKFZWeQeNCvuRYLCqgAacCTZFEybgABkLlEdWZoPZ3I5aDyvH4QhEYkkJCqTBwcgAFI69YJIfTGQB+Q1sjkASnABOR4lGAgE3AA3EqHfrYASAERiASEGRbPBEHCJADWkYT4GAiKAA) (working)
2. [Extra prop indirectly provided in LibraryManagedAttributes](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3ACUBTAQwGMSAzAvLcAcgKtpbTSIE8dy4AOoYiACwDCAZSkAFRjgA8sgHzgAvOFngAZOADe4arFgAucLCIEMAOwDm4AL7cAJuWoAbSuyN4blpARzPgE8OjIOIgA6anZKInIAUQ9yLHIbIjQbSjTYHBpBZAM0cFLwcnh8YnBs3PzqQQApKQANYrKO8srCElsEgjoC8GTU9JJ9Z06yiqrejPIBoZG0jIkvEwNJqa7Z8D6FwYbhlJWiAEEiKwwAIwBXBNh5PAFiXk2S7ZmevfnFo+WxhIxBgPC52DYLlc7gl3tsdt99n9BABJDLWfwYaiQ6zQ8iwWGfbrVRGHFFo2ywTFrSgmbE3e54xQAFTUEw+Uy+1RCZKuGOoAIy+M0+nZcPALgwADdzIZPDTYAA5HLkcyWdEOLZTTWdTkkbngAAyNwI3l4AFlKNk7OQXHTcbBFBIADRaNSaETiaRyBTKFSi5zONBuOU+ah+AISJg4cwACmjBiM60VyoA-KreRqAJQaNQ2W4eDzcADcjqjRhM6gARGGPIRTGI8EQcLYANZFyvgYAqIA) (not working)
3. [Unused C type passed to indirect version](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210106#code/PQKhAIAECsGcA9x0SYAoAlgWwA4HsAnAF3ACUBTAQwGMSAzAvLcAcgKtpbTSIE8dy4AOoYiACwDCAZSkAFRjgA8sgHzgAvOFngAZOADe4arFgAucLCIEMAOwDm4AL7cAJuWoAbSuyN4blpARzPgE8OjIOIgA6anZKInIAUQ9yLHIbIjQbSjTYHBpBZAM0cFLwcnh8YnBs3PzqQQApKQANYrKO8srCElsEgjoC8GTU9JJ9Z06yiqrejPIBoZG0jIkvEwNJqa7Z8D6FwYbhlJWiAEEiKwwAIwBXBNh5PAFiXk2S7ZmevfnFo+WxhIxBgPC52DYLlc7gl3tsdt99n9BABJDLWfwYaiQ6zQ8iwWGfbrVRGHFFo2ywTFrSgmbE3e54xQAFTUEw+Uy+1RCZKuGOoAIy+M0+nZcPALgwADdzIZPDTYAA5HLkcyWdEOLZTTWdTkkbngAAyNwI3l4AFlKNk7OQXHTcbBFBIADRaNSaETiaRyBTKFSi5zONBuOU+ah+AISJg4cwACmjBiM60VyoA-KreRqAJQaNQ2W4eDzcADcjqjRhM6gARGGPIRTGI8EQcLYANZFyvgYAqIA) (working again)

### 💻 Code

I've stumbled upon this because in Emotion (CSS-in-JS library) we provide support for a "pseudo" css prop - to do that we have a conditional type like:

```ts
type WithConditionalCSSProp<P> = 'className' extends keyof P
  ? string extends P['className' & keyof P]
    ? P & { css?: Interpolation<Theme> }
    : P
  : P
```
which we use in the `LibraryManagedAttributes` type. However, as this is React-based library we want to only extend what React types offers and not replace them entirely. So we've tried this:
```ts
type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<
  ReactJSXLibraryManagedAttributes<C, P>
>
```
and for some weird reason this didn't work as expected. We've managed to work around by doing this:
```ts
type LibraryManagedAttributes<C, P> = ReactJSXLibraryManagedAttributes<C, P> & WithConditionalCSSProp<P>
```
I couldn't wrap my head around why the "composed" type doesn't work though - I've tested that TS is able to resolve it correctly! Even when it was used in the `LibraryManagedAttributes` type (I've assigned result to some extra prop and the produced types were *as expected*).

After more investigation I've discovered that we could make the version with types composition work by making `WithConditionalCSSProp` accept `C` - even if it has stayed unused in its implementation:
```ts
type WithConditionalCSSProp<C, P> = 'className' extends keyof P
  ? string extends P['className' & keyof P]
    ? P & { css?: Interpolation<Theme> }
    : P
  : P

type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<
  C,
  ReactJSXLibraryManagedAttributes<C, P>
>
```

and this has lead me to narrow down the issue to even weirder scenarios - I've linked all of them in the "Playground Link" section.

### 🙁 Actual behavior

Types used by LibraryManagedAttributes that do not accept both provided type parameters are **ignored** which leads to obscure observable effects because one can think that their changes are reflected by the affected type is not used at all - it doesn't error or anything, it's just skipped over.

### 🙂 Expected behavior

Types used by `LibraryManagedAttributes` should be able to accept any amount of type arguments.

### PR DESCRIPTION
**Pull request by weswigham**
For some reason we were looking up the `aliasTypeArguments` on the declared type of the alias, and using those as a proxy for the declared type parameters on the alias itself. Now we fetch the actual type parameter list for the alias instead.

Fixes #42240

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot user test this

**Comment by weswigham** [comment]
Cool - user tests look fine. Lemme also @typescript-bot run dt to try out on any JSX there.

**Comment by weswigham** [comment]
DT also looks fine.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -24551,16 +24551,19 @@ namespace ts {
...
+                const declaredManagedType = getDeclaredTypeOfSymbol(managedSym); // fetches interface type, or initializes symbol links type parmaeters
                 const ctorType = getStaticTypeOfReferencedJsxConstructor(context);
+                if (managedSym.flags & SymbolFlags.TypeAlias) {
+                    const params = getSymbolLinks(managedSym).typeParameters;
+                    if (length(params) >= 2) {
+                        const args = fillMissingTypeArguments([ctorType, attributesType], params, 2, isInJSFile(context));
+                        return getTypeAliasInstantiation(managedSym, args);
+                    }
+                }
                 if (length((declaredManagedType as GenericType).typeParameters) >= 2) {
```
Comment (Andarist) [inline src/compiler/checker.ts:24563]: Hi, I'm the reporter of this issue - thanks for the swift fix! I was really curious why this has been happening (because seemingly it didn't really look that much different from other code that has been working) and I got into reading this PR to see how it got fixed.

I'm obviously just a bystander and I lack *a lot* of context but understanding this fix probably would allow me to understand the TS compiler better. I'm wondering if you would be able to share a little bit more in-depth explanation behind this? I will totally understand if you won't have time for that though.

I suspect that `SymbolFlags.TypeAlias` checks if this is a `type` type and not the `interface` - does it mean that one could use the `interface` for `LibraryManagedAttributes`? I kinda assumed that this is not possible but maybe I was wrong - I can't quite check this quickly myself because this has not been yet released to the nightly channel.

This change later checks the `typeParameters.length >= 2` - this looks quite odd for me because the given code uses exactly 2 type parameters, so why this is even relevant for this fix? I would more expect that this piece of code would provide exactly as many type parameters as the `managedSym` accepts (up to 2 as no more will be ever provided). Shouldn't also maybe `JSX.LibraryManagedAttributes` with more than 2 type parameters result in an error since those extras won't ever be provided? And how "fillMissingTypeArguments" is relevant here for the "top most" `managedSym`? Will this fix the other case that I've mentioned (albeit without repro because I've concluded that the underlying issue is probably the same):
```ts
type LibraryManagedAttributes<C, P> = WithConditionalCSSProp<
  ReactJSXLibraryManagedAttributes<C, P>
>
```
This snippet is using both type parameters so I would expect that nothing is missing here but yet it doesn't work either.

I was wondering about an additional thing for quite a bit - maybe you could describe this shortly as well. What's the difference between `aliasTypeArguments` and `typeArguments`, between `symbol` and `aliasSymbol`, between `type` and `typeAlias`? 🤔

Comment (weswigham) [reply src/compiler/checker.ts:24563]: The `aliasTypeArguments` list is the type arguments plugged in to the type alias symbol associated with the type - which, in many cases, is the `LibraryManagedAttributes` symbol, _however_, if the target of the type alias already has an alias symbol itself (eg, `WithConditionalCSSProp` is a type alias), then it'll be the arguments for _that_, since the type is first made via that alias.

**Review by sandersn — APPROVED** [review]
