### PR TITLE
Fix module resolution for import call emit

### LINKED ISSUE #37429: System or AMD module with outFile and dynamic import incorrect
**TypeScript Version:**  3.8.3

**Search Terms:**

dynamic import, system, outFile

**Code**

_index.ts_

```ts
import * as foo from "./mod1";

(async () => {
  const foo1 = await import("./mod1");
  console.log(foo, foo1);
})();
```

_mod1.ts_

```ts
export const foo = "foo";
```

```
$ tsc index.ts --outFile bundle.js --module system --target esnext
```

_or_

```
$ tsc index.ts --outFile bundle.js --module amd --target esnext
```

**Expected behavior:**

With System, it is expected that the dynamic `import()` statement would be converted to `import("mod1")` instead of staying as `import("./mod1")` since all modules are now registered with absolute specifiers instead of resolved specifiers.  This is mostly because the compiler determines what the specifiers are named, and shouldn't presume relative resolution can be applied by the loader.

**Actual behavior:**

_for System module_

```js
System.register("mod1", [], function (exports_1, context_1) {
    "use strict";
    var foo;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            exports_1("foo", foo = "foo");
        }
    };
});
System.register("index", ["mod1"], function (exports_2, context_2) {
    "use strict";
    var foo;
    var __moduleName = context_2 && context_2.id;
    return {
        setters: [
            function (foo_1) {
                foo = foo_1;
            }
        ],
        execute: function () {
            (async () => {
                const foo1 = await context_2.import("./mod1");
                console.log(foo, foo1);
            })();
        }
    };
});
```

cc/ @guybedford

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes `import()` emit for bundled SystemJS/AMD output.

Fixes #37429

### CODE REVIEW

**Review by weswigham — APPROVED** [review]

File: src/compiler/transformers/module/module.ts [hunk 1]
```diff
@@ -609,7 +609,10 @@ namespace ts {
         }
 
         function visitImportCallExpression(node: ImportCall): Expression {
-            const argument = visitNode(firstOrUndefined(node.arguments), moduleExpressionElementVisitor);
+            const externalModuleName = getExternalModuleNameLiteral(factory, node, currentSourceFile, host, resolver, compilerOptions);
+            const firstArgument = visitNode(firstOrUndefined(node.arguments), moduleExpressionElementVisitor);
+            // Only use the external module name if it differs from the first argument. This allows us to preserve the quote style of the argument on output.
```
Comment (weswigham) [inline src/compiler/transformers/module/module.ts:614]: If we really wanted to, couldn't we copy the quote style from the first argument string, if present?

Comment (rbuckton) [reply src/compiler/transformers/module/module.ts:614]: We don't preserve quote-style on parse, and this is how we handle strings everywhere else (copy from source text if possible).
