### PR TITLE
fix(40257): Remove type parameters quick fix forgets the trailing > 

### LINKED ISSUE #40257: Remove type parameters quick fix forgets the trailing >
**TypeScript Version:**  4.1.0-dev.20200826

**Search Terms:** remove parameter fix

**Code**

```ts
export type CCResponsePredicate<
	TSent extends CommandClass = CommandClass,
	TReceived extends CommandClass = CommandClass
> = (sentCommand: CommandClass, receivedCommand: CommandClass) => CCResponseRole;
```
1. Cursor after `CCResponsePredicate<`
2. Trigger "remove all type parameters" quick fix

**Expected behavior:**
```ts
export type CCResponsePredicate = (sentCommand: CommandClass, receivedCommand: CommandClass) => CCResponseRole;
```

**Actual behavior:**
```ts
export type CCResponsePredicate> = (sentCommand: CommandClass, receivedCommand: CommandClass) => CCResponseRole;
```

**Playground Link:** The playground doesn't offer this quick fix

**Related Issues:** none found

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40257

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -64,6 +64,13 @@ namespace ts.textChanges {
         return skipTrivia(text, start, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
     }
 
+    function rangeOfTypeParameters(text: string, typeParameters: NodeArray<TypeParameterDeclaration>): TextRange {
```
Comment (sandersn) [inline src/services/textChanges.ts:67]: I think you should make this fix in utilities.ts instead of making a copy and fixing it.

File: src/services/textChanges.ts [hunk 2]
```diff
@@ -64,6 +64,13 @@ namespace ts.textChanges {
         return skipTrivia(text, start, /*stopAfterLineBreak*/ false, /*stopAtComments*/ true);
     }
 
+    function rangeOfTypeParameters(text: string, typeParameters: NodeArray<TypeParameterDeclaration>): TextRange {
+        // Include the `<>`
+        const pos = typeParameters.pos - "<".length;
```
Comment (sandersn) [inline src/services/textChanges.ts:69]: when is `"<".length !== 1` ?

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/services/textChanges.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/textChanges.ts:69]: Screenshot 2020-09-08 at 21 47 05
Seems this question related to this code too :).

File: src/services/textChanges.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/textChanges.ts:67]: The `checker.ts` uses `rangeOfTypeParameters()` from `compiller/utilities` without `sourceFile`, which is required in service.

**Review by sandersn — APPROVED** [review]
