### PR TITLE
Fix #41800 correctly.

### LINKED ISSUE #41800: Generated declaration for a JavaScript file refers to non-existing module
**TypeScript Version:**  4.1.2
**Search Terms:** javascript, javascript declaration, eventemitter (and bunch of others)

**Code**

```javascript
import { EventEmitter } from 'events';

export default class Foo extends EventEmitter {}
```

With tsconfig:

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "outDir": "./dist",
    "declaration": true,
    "strict": false,
    "rootDir": "./src"
  },
  "include": [
    "src/*.js",
    "src/**/*.js"
  ]
}
```

**Expected behavior:**

The generated declaration file should contain:

```typescript
import { EventEmitter } from "events"
export default class Flowtrace extends EventEmitter {}
```

**Actual behavior:**

```typescript
import { EventEmitter } from "node/events"
export default class Flowtrace extends EventEmitter {}
```

Which produces the following error:

> File '<project root>/node_modules/@types/node/events.d.ts' is not a module.ts(2306)

For now the fix appears to be to search-and-replace the `node/events` instances.

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #41816

### CODE REVIEW

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -376,6 +376,26 @@ namespace ts.moduleSpecifiers {
...
+         *     }
+         *     export = ns;
+         * }
+         */
+        // `import {c} from "m";` is valid, in which case, moduleSymbol is "ns", but the module name should be "m"
+        const exportModuleDeclare = find(moduleSymbol.declarations,
+            d => isModuleDeclaration(d)
+            && d?.parent?.parent?.parent
+            && isModuleBlock(d.parent) && isAmbientModule(d.parent.parent) && isSourceFile(d.parent.parent.parent)
+            && ((d.parent.parent.symbol.exports?.get("export=" as __String)?.valueDeclaration as ExportAssignment).expression as Identifier).escapedText === getTextOfIdentifierOrLiteral(d.name)
```
Comment (weswigham) [inline src/compiler/moduleSpecifiers.ts:394]: Hm. The text comparison is a little too specific - for example, what if 
```ts
declare module m {
  namespace a.b {
    class c {}
  }
  export = a.b;
}
```
? I think we need to do a symbol identity comparison here. In the checker, this'd ne easy using some `resolveEntityName` or `getSymbolOfNode` machinery - in `moduleSpecifiers.ts` it's maybe a bit more awkward? There's a `getSymbolIfSameReference` function in the checker for seeing if two symbols really refer to the same thing that is what I'd have considered using if it was available. Maybe we need some more context from the checker available? Or just more internals exported from the checker?

Comment (ShuiRuTian) [reply src/compiler/moduleSpecifiers.ts:394]: it is a good sugestion, but I am little worried about something
these functions(`getsymbolofNode`) are in the function `createTypeChecker`, so they could not be exported directly. What about match namespace directly? 
Find the namespace unitil it is not nested namespace -- if module symbol is "b"(it is a nested namespace) and we find its parent "a"(it is namespace and not nested), so the path is "a.b", which matches default export("a.b")

Comment (ShuiRuTian) [reply src/compiler/moduleSpecifiers.ts:394]: > Hm. The text comparison is a little too specific - for example, what if
> 
> ```ts
> declare module m {
>   namespace a.b {
>     class c {}
>   }
>   export = a.b;
> }
> ```
> 
> ? I think we need to do a symbol identity comparison here. In the checker, this'd be easy using some `resolveEntityName` or `getSymbolOfNode` machinery - in `moduleSpecifiers.ts` it's maybe a bit more awkward? There's a `getSymbolIfSameReference` function in the checker for seeing if two symbols really refer to the same thing that is what I'd have considered using if it was available. Maybe we need some more context from the checker available? Or just more internals exported from the checker?

it is a good sugestion, but I am little worried about something
these functions(getsymbolofNode) are in the function createTypeChecker, so they could not be exported directly. What about match namespace directly?
Find the namespace unitil it is not nested namespace -- if module symbol is "b"(it is a nested namespace) and we find its parent "a"(it is namespace and not nested), so the path is "a.b", which matches default export("a.b")

Comment (weswigham) [reply src/compiler/moduleSpecifiers.ts:394]: Nah, I'm pretty sure you gotta do symbol resolution and matching - otherwise you'll miss renames like
```ts
declare module m {
  namespace a.b {
    class c {}
  }
  import d = a.b;
  export = d;
}
```

Comment (ShuiRuTian) [reply src/compiler/moduleSpecifiers.ts]: Thanks a lot for the kind suggestion
Now using getSymbolAtLocation and getAliasedSymbol to get the original symbol of the default export , then compare it with `moduleSymbol`, is this way OK? Did I miss something again?

File: src/compiler/moduleSpecifiers.ts [hunk 2]
```diff
@@ -369,13 +370,49 @@ namespace ts.moduleSpecifiers {
...
+        /**
+         * declare module "m" {
+         *     namespace ns {
+         *         class c {}
+         *     }
+         *     export = ns;
+         * }
+         */
+        // `import {c} from "m";` is valid, in which case, `moduleSymbol` is "ns", but the module name should be "m"
+        const ambientModuleDeclareCandidates = map(moduleSymbol.declarations,
```
Comment (weswigham) [inline src/compiler/moduleSpecifiers.ts:391]:
```suggestion
        const ambientModuleDeclareCandidates = mapDefined(moduleSymbol.declarations,

```
should simplify the lines below a bit. (Namely you should just be able to pull the first element out, rather than `find`ing a defined element).

**Review by weswigham — CHANGES_REQUESTED** [review]
This looks pretty good to me - just two small nits.

**Review by weswigham — APPROVED** [review]
