### PR TITLE
Explicitly typed special assignments are context sensitive

### LINKED ISSUE #25571: Expressions in JS special assignments don't use jsdoc for contextual type
**TypeScript Version:**  3.0.0-dev.20180710

**Search Terms:** tagged discriminated union property this jsdoc checkjs allowjs literal

The following typescript works great:
```ts
type DoneStatus = {
  status: 'done';
  count: number;
};

type ErrorStatus = {
  status: 'error';
  error: Error;
};

type Status = DoneStatus | ErrorStatus;

class Thing {
  s: Status;
  constructor() {
    this.s = { status: 'done', count: 3 };
  }

  fail() {
    this.s = { status: 'error', error: new Error() };
  }
}
```

However, the equivalent JS does not:

```js
/**
 * @typedef DoneStatus
 * @property {'done'} status
 * @property {number} count
 */

/**
 * @typedef ErrorStatus
 * @property {'error'} status
 * @property {Error} error
 */

/** @typedef {DoneStatus | ErrorStatus} Status */

class Thing {
  constructor() {
    /** @type {Status} */
    this.s = { status: 'done', count: 3 }; // ts error
  }

  fail() {
    this.s = { status: 'error', error: new Error() }; // ts error
  }
}
```
Both assignments give the error:
```
[ts] Type 'string' is not assignable to type '"error" | "done"'.
test.js(3, 4): The expected type comes from property 'status' which is declared here on type 'DoneStatus | ErrorStatus'
(property) status: string
```
**Expected behavior:**
JS behaves the same as TS version

### PR DESCRIPTION
**Pull request by sandersn**
Explicitly typed special assignments should be context sensitive if they have an explicit type tag. Previously no special assignments were context sensitive because they are declarations, and in the common, untyped, case we inspect the right side of the assignment to get the type of the left side, and inspect the right side of the assignment to get the type of the left side, etc etc.

Note that some special assignments still return `any` from checkExpression, so still don't get the right type. Those test cases have a noImplicitAny error in the new test I added. I will look at improving type checking of `module.exports` and `X.prototype` next.

Fixes #25571

### CODE REVIEW

File: tests/cases/conformance/salsa/contextualTypedSpecialAssignment.ts [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+ns.x = {
+    status: 'done',
+    m(n) { }
+}
+ns.x
+
+
+// this-property assignment
+class Thing {
+  constructor() {
```
Comment (andy-ms) [inline tests/cases/conformance/salsa/contextualTypedSpecialAssignment.ts]: Nit: Use 4 space indents

Comment (sandersn) [reply tests/cases/conformance/salsa/contextualTypedSpecialAssignment.ts]: oops, cut-and-paste from the issue.
