### PR TITLE
Cache resolved project references and watch wild card directories from them to update them

### LINKED ISSUE #37304: TypeScript: New class in second project is only recognized by intellisense after restart
Issue Type: <b>Bug</b>

- Load a folder with multiple typescript projects
- e.g.: folder structure: 
   - projects
      - project1
      - project2
- e.g.: project2 references project1 via project references in tsconfig
- Add a new class in an new .ts file in project1
- Try  to use this class in project2
- Intellisence does not know about this class and it is reported as error if you just type it.

Workaround:
- Restart VSCode
- After restart the new class is available via intellisense and not reported as error any more

Fix: 
- This should work without a restart...

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
formate|Mik|1.1.4
team|ms-|1.161.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

### LINKED ISSUE #42607: Project references decrease performance of language service by a factor of 10
# Bug Report

We have a large mono repo with around 10000 `tsconfig.json` projects in a nested directory structure configured with project references. We've been finding the performance of type checking and suggestions in both VSCode and Intellij is becoming unbearably slow, especially in projects that have a lot project ref dependencies (including transitive). For example, it's common for type errors and suggestions to take greater than 20 seconds to update and appear. I have tried doing a `tsc -b` on the root projects so the `d.ts` files are available on disk, but that doesn't seem to help.

However, I found after deleting the `references` field in the tsconfig files, the IDE response time reduces to 500ms, a huge improvement that makes editing a lot easier. This surprises me as I thought project references would improve performance, not  decrease it. Keeping the `references` field but setting composite to false is still slow.

I verified the times by looking at `updateGraphWorker` events in the VSCode ts server logs, but the difference is also very visible without the logs.

Thanks for your help!

A sample project:

```
{
  "include": [
    "../../../../declarations/css_modules.d.ts",
    "./**/*.*"
  ],
  "compilerOptions": {
    "types": []
  },
  "references": [
    { "path": "../../../base" },
    { "path": "../../../base/foo" },
    { "path": "./banana" },
  ],
  "exclude": [
    "banana",
    "stories",
    "tests"
  ],
  "extends": "../../../../tsconfig.build.json"
}

```

The inherited `tsconfig.build.json` config:

```
{
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "baseUrl": "./src",
    "experimentalDecorators": true,
    "importHelpers": true,
    "jsx": "react",
    "lib": [
      "dom",
      "dom.iterable",
      "es2018",
      "es2019.array"
    ],
    "moduleResolution": "node",
    "rootDir": ".",
    "outDir": "target",
    "strict": true,
    "skipLibCheck": true,
    "target": "ES2019",
    "sourceMap": true,
    "inlineSources": true,
    "module": "ESNext",
    "types": [],
    "paths": {
      "base": ["../node_modules/base/"],
      "mobx": ["../declarations/mobx"]
    }
  },
  // Don't include any source files in the base build.
  "include": []
}
```

### 🔎 Search Terms

language service intellisense project references performance 

### 🕗 Version & Regression Information

Version 4.1.2

### 🙁 Actual behavior

Language service performance degrades when project references are defined.

### 🙂 Expected behavior

Language service performance does not degrade when project references are defined.

### PR DESCRIPTION
**Pull request by sheetalkamat**
When creating program, we have two methods to get resolved project reference. Through `CompilerHost.getParsedCommandLine` or getting `host.getSourceFile` and using tsconfig parsing on that source file. Previously only `tsc -b` used `getParsedCommandLine` that cached the command lines for the projects. With this change `tsserver` as well as `tsc -w` set those methods on `CompilerHost`.
The change involves:
1. Program now handles releasing of `ParsedCommandLines` if they are not needed in new program just like we release source files. This is to enable handling and releasing of the parsed command lines between multiple programs that is used by `tsserver` and `tsc -w`
2. When checking program upto date ness, checking only source file is not enough, we also need to check files names in the command line for resolved project references since they can change without changing source file when host caches the ParsedCommandLine (on addition or deletion of file in wild card directory we just update file names instead of having to parse complete config file again)
3. Our current utility method `isIgnoredFileFromWildCardWatching` can take root file names so it can ignore the output file names for those and ignore them.
4. In `tsc -w` and `tsserver` scenario, we cache the `ParsedCommandLine` for the referenced projects and its invalidated only if there is change in config file, change in extended files or new files are added or removed
5. Because extended config files are watched, we now use extended config cache map when parsing config files and invalidate this cache if extended config files change (or file that is exteneded directly/indirectly) changes
6. Language service uses `getParsedCommandLine` on `LanguageServiceHost` if present or get source file and parses the command line (just like it would have been done by `program` before this change)
7. In tsserver, project service the cache of config file existence is updated to contain parsed command line and watching of config file is unified in the existence cache (Before this change watcher would present in cache only if there is no configured project is around for that config file). So if there are parsed command lines needed by any project or if there is a open script info which is root of inferred project that depends on changes to config file, it is watched.
8. The wild card directory and extended config file watching also is cached in config file existence cache so it can be unified for all projects that use parsed command line for that confg file

Fixes #37304
Probably fixes #42607

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

File: src/compiler/watchPublic.ts [hunk 1]
```diff
@@ -792,22 +893,110 @@ namespace ts {
...
+                sharedExtendedConfigFileWatchers ||= new Map(),
+                (extendedConfigFileName, extendedConfigFilePath) => watchFile(
+                    extendedConfigFileName,
+                    (_fileName, eventKind) => {
+                        updateCachedSystemWithFile(extendedConfigFileName, extendedConfigFilePath, eventKind);
+                        // Update extended config cache
+                        if (extendedConfigCache) cleanExtendedConfigCache(extendedConfigCache, extendedConfigFilePath, toPath);
+                        // Update projects
+                        const projects = sharedExtendedConfigFileWatchers.get(extendedConfigFilePath)?.projects;
+                        if (!projects?.size) return;
```
Comment (RyanCavanaugh) [inline src/compiler/watchPublic.ts:909]: A comment explaining this return would be nice

**Review by RyanCavanaugh — APPROVED** [review]
