### PR TITLE
Format destructuring by brace format option

### LINKED ISSUE #12239: Destructuring does not auto-format whitespace
_From @marcomorain on November 4, 2016 15:39_

- VSCode Version: 1.7.1 `02611b40b24c9df2726ad8b33f5ef5f67ac30b44` 2016-11-03T13:44:00.572Z
- OS Version: OSX 10.12.1 (16B2657)

## Issue

The whitespace on the LHS of a destructuring assignment is not formatted.

## Steps to Reproduce:

1. Add the following to a typescript file:

```JS
const {NoSpaces} = { NoSpaces: 1 }
const { WithSpaces } = { WithSpaces: 1 }
const {OneSpace } = { OneSpace: 1 };
```

2. Format the document.

## Expected

I would expect the whitespace on the LHS of the assignment to be consistent. I would expect either:

```JS
const {NoSpaces} = { NoSpaces: 1 }
const {WithSpaces} = { WithSpaces: 1 }
const {OneSpace} = { OneSpace: 1 };
```

or 

```JS
const { NoSpaces } = { NoSpaces: 1 }
const { WithSpaces } = { WithSpaces: 1 }
const { OneSpace } = { OneSpace: 1 };
```

## Actual Output

Whitespace of the LHS is inconsistent:

```JS
const {NoSpaces} = { NoSpaces: 1 }
const { WithSpaces } = { WithSpaces: 1 }
const {OneSpace } = { OneSpace: 1 };
```

_Copied from original issue: Microsoft/vscode#14996_

### PR DESCRIPTION
**Pull request by SaschaNaz**
Fixes #12239

Input:

```ts
var  {a,b  }    = {   a: 'sw',  b:'r'   }; 
```

Output:

```ts
var { a,b } = { a: 'sw', b:'r' }; 
// or
var {a,b} = {a: 'sw', b:'r'}; 
```

### CODE REVIEW

File: src/harness/fourslash.ts [hunk 1]
```diff
@@ -3524,11 +3524,8 @@ namespace FourSlashInterface {
             this.state.formatOnType(this.state.getMarkerByName(posMarker).position, key);
         }
 
-        public setOption(name: string, value: number): void;
-        public setOption(name: string, value: string): void;
-        public setOption(name: string, value: boolean): void;
-        public setOption(name: string, value: any): void {
-            (<any>this.state.formatCodeSettings)[name] = value;
+        public setOption(name: keyof ts.FormatCodeSettings, value: number | string | boolean): void {
```
Comment (mhegazy) [inline src/harness/fourslash.ts]: 👍
