### PR TITLE
Use comparability for discriminant properties when narrowing types for a default switch clause

### LINKED ISSUE #61207: Discriminated Union is not narrowed to never when all types are checked in default case if discriminator field is literal type
### 🔎 Search Terms

switch default discriminated Unions 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about discriminated unions

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.3#code/KYOwrgtgBAgiCWECGAbAKgTwA7CgbwCgooBjJAFygF4oByM82gGiKgBMB7Ac2rs69oEAvgQLlsuOIlS9CxcTgBcUAAYASPFOToJAOgZCVAblYRgHAO7KAzuQBO8EFxNCoAH3ysFwZes0JtTBxdfkMTYgAjJDsAaxt7R2dhUQAzMBAScngOEFIAC2ASGIAKLGUQYAA3YDsASk95PLtLKAqLKABRO2a7YtounoBCWlrkgjSMrJyoJEzskGKkANRlLVR6uSgAei2oAGEOCCx4FGBrVngUqEXllF1vaioaNZ1ghg3WYhIc6w5T3RQ3Bu0juZkstXCUFcwBQ1lwl2uSxB9wkj2etyCwBC3A+xC+Pz+WMBXGB2l0UViENY0NhuE2XwKRVJ62pomIO32h2Op3OxGsFng5BIeURtxROFxeLIcNUGhemP0FEMik+UoJ-2JzNB5gsVLxeIidmASBikK+SBlfnlelCKhV+vxIF+GqBSLJFJieodhuNptVbGAKSQYBQ5HtDuFhRKbvWkJErA5ABEOGdWhxKN8jidgKx+YLhaLkd5JeaZda3hRw-rvk7CQDXWKwbqzQajSaW9LJBibdwq2ray6STG7h6vfqfe3-YHg6G+wyo1qIdtdgAeAC0a9gdi4kFAlA4VwetBetCg8GsacoFus8C4ICQEVOUHIHCgWGiSDM5BqUAPz9RtAVNUdiCMQIhCEAA

### 💻 Code

```ts
enum AnimalType {
  cat = 'cat',
  dog = 'dog'
}

type Animal = {
  type: `${AnimalType.cat}`;
  meow: string;
} | {
  type: `${AnimalType.dog}`;
  bark: string;
}

function check(p: never) {
  throw new Error('Error!')
}

function action(animal: Animal) {
  // Compiles
  if (animal.type === AnimalType.cat) {
    console.log(animal.meow);
  } else if (animal.type === AnimalType.dog) {
    console.log(animal.bark);
  } else {
    check(animal)
  }

  // Compiles
  switch (animal.type) {
    case `${AnimalType.cat}`:
      console.log(animal.meow);
      break;
    case `${AnimalType.dog}`:
      console.log(animal.bark);
      break;
    default:
      check(animal);
  }

  // Does not compile
  switch (animal.type) {
    case AnimalType.cat:
      console.log(animal.meow);
      break;
    case AnimalType.dog:
      console.log(animal.bark);
      break;
    default:
      check(animal); // <-- Argument of type 'Animal' is not assignable to parameter of type 'never'
  }
}
```

### 🙁 Actual behavior

The last example does not compile

### 🙂 Expected behavior

To my understanding all three examples do exactly the same and all should compile.

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/61207

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -29113,7 +29113,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             if (!hasDefaultClause) {
                 return caseType;
             }
-            const defaultType = filterType(type, t => !(isUnitLikeType(t) && contains(switchTypes, t.flags & TypeFlags.Undefined ? undefinedType : getRegularTypeOfLiteralType(extractUnitType(t)))));
+            const defaultType = filterType(type, t => !(isUnitLikeType(t) && contains(switchTypes, t.flags & TypeFlags.Undefined ? undefinedType : getRegularTypeOfLiteralType(extractUnitType(t)), (t1, t2) => isUnitType(t1) && areTypesComparable(t1, t2))));
```
Comment (Andarist) [inline src/compiler/checker.ts:29116]: This essentially matches the logic used by `narrowTypeByEquality` [here](https://github.dev/microsoft/TypeScript/blob/0f4737e0d55363ac40198b33a80fff0d01c1d8cf/src/compiler/checker.ts#L29042-L29044)
```ts
            if (isUnitType(valueType)) {
                return filterType(type, t => !(isUnitLikeType(t) && areTypesComparable(t, valueType)));
            }
```

As we can see, the `valueType` has to pass `isUnitType` there and the equivalent of the `valueType` here are all the types in `switchTypes`. Note that in the case of switch/case here that check mainly ensures we ignore `neverType` as that's comparable to everything. `neverType` is specifically used within `switchTypes` to indicate that this switch statement has a default case (see `getTypeOfSwitchClause` [here](https://github.dev/microsoft/TypeScript/blob/0f4737e0d55363ac40198b33a80fff0d01c1d8cf/src/compiler/checker.ts#L27712-L27717) and `hasDefaultClause` [here](https://github.dev/microsoft/TypeScript/blob/0f4737e0d55363ac40198b33a80fff0d01c1d8cf/src/compiler/checker.ts#L29088))

**Comment by DanielRosenwasser** [comment]
@typescript-bot test it

**Review by jakebailey — APPROVED** [review]

**Comment by Yavanosta** [comment]
Hi @Andarist 

Is there anything blocking this pull request?
