### PR TITLE
Only apply global augmentations before globals are available

### LINKED ISSUE #21556: Crash while running dt tests with `esModuleInterop`
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**
Run the tests for `moment-strftime2` on `dt`, with the `esModuleInterop` flag set to `true`.

```
E:\Github\TypeScript\src\compiler\checker.ts:5976
            if (type.flags & TypeFlags.Object) {
                     ^
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (E:\Github\TypeScript\src\compiler\checker.ts:5976:22)
    at getPropertyOfType (E:\Github\TypeScript\src\compiler\checker.ts:6308:36)
    at resolveExportByName (E:\Github\TypeScript\src\compiler\checker.ts:1657:19)
    at canHaveSyntheticDefault (E:\Github\TypeScript\src\compiler\checker.ts:1668:21)
    at getTypeWithSyntheticDefaultImportType (E:\Github\TypeScript\src\compiler\checker.ts:17597:49)
    at resolveESModuleSymbol (E:\Github\TypeScript\src\compiler\checker.ts:2126:48)
    at getTargetOfNamespaceImport (E:\Github\TypeScript\src\compiler\checker.ts:1718:20)
    at getTargetOfAliasDeclaration (E:\Github\TypeScript\src\compiler\checker.ts:1831:28)
    at resolveAlias (E:\Github\TypeScript\src\compiler\checker.ts:1862:32)
    at getSymbol (E:\Github\TypeScript\src\compiler\checker.ts:963:40)
```

**Expected behavior:**
No crash

**Actual behavior:**
Crash

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #21556

While doing module augmentations, we can need to resolve the `export=` member of a module to see what it looks at. In doing so, we can need to look at the type of the module to see if it has a `default` member in order to create its type. In looking at those properties, we try fallbacks to `globalFunctionType` if it is callable to see if it is on the apparent type. `globalFunctionType` was not yet set (since it was set after module augmentation), causing the error.

This PR splits module application up. First global augmentations are applied (they are simple symbol table merges, and must be done first for the global type lookups to be able to find global types augmented by global augmentations), then global variables are defined, _then_ module augmentations are applied (and now the global types exist as expected).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -25257,6 +25258,17 @@ namespace ts {
             globalReadonlyArrayType = <GenericType>getGlobalTypeOrUndefined("ReadonlyArray" as __String, /*arity*/ 1);
             anyReadonlyArrayType = globalReadonlyArrayType ? createTypeFromGenericGlobalType(globalReadonlyArrayType, [anyType]) : anyArrayType;
             globalThisType = <GenericType>getGlobalTypeOrUndefined("ThisType" as __String, /*arity*/ 1);
+
+            if (augmentations) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: please add some detailed explanation on why we need to do this..
