### PR TITLE
Limit type argument inference from binding patterns

### LINKED ISSUE #43605: Presence of a binding pattern changes inference for callback function parameters
# Bug Report

### 🕗 Version & Regression Information

This bugs occurs in typescript 4.2.3, 4.2.4 and 4.3.0-beta, I didn't test the older typescripts.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/PTAEBcE8AcFNQCawGYEsB2ryoPboM6j6oC20ANqmrAqMgE44mgAGAAvTQK4AeAVvmDgcOcgGssLADStOAQwDG4FqDnpaLeUoC0nBLxYBYAFAmocUABFU+aHPAKAFgB4AgqAC8oAN4QYsAC5VdEgAblAAbVgecHo5AAVGaHwg-FiMAHMAXSC1SFAAXwA+Tx9QZwAVUGjwWHVCVyKACkVsPCCKgEoOwtCTJAVyOU46LnQlXHRQLnxYAFlYEhxK5uRWnHpIIKbOzxKKmSRkoIAlWDkEPHJIV3o4yGc8koAfafUUDBpu0Aq+4wGhiNkGMJnhprNrLZ7E5KpC7A5HKU4dCXE9mt8KsiEX8TCBQABJSywNL0LhKLj0TKgABkVmJsTJ4ApmRMZn8BIAYiDCF5fPJLuhrpExLAtkR0uhstsAHSy6C5EK7DwlABuOFQtAKOOM5nghPppPJlMllWqMTqCEI+K543wJV5oH5V3yERF+QwoDdOGQPyyAH4ZXKgvFhnISLBavR8JVXaKskUlar1Zrtbq6STGcyTVUaharTaFPgZABVM21eoEokZo2ZFb20BNBA2eFOIJYmFPGTA20dROgYvavHd0EEVnGBR4NKjW0ARlK3hMoCX04Urm2ciCACMRORzuhvmqNXsfAUpIvl8OAELbTepCUZGSb2-i40ZA-J4-eU-npfDgDC2wKEE6BcCQm6wPQMgKEBoAgWBEFQdBW47nu75HsqJ5nsYWomBOBDgCu+AAEzzj+K6WNsCDIaIqFBIetAYV+WHLiuACi2yBC+mQyLAnEkpkaEMSUTFkcOHLbMgwGgeBkF0JJsHSQhcnyduNFqIJn7fthqbshUBb4HOXi6t6hEzn8aZ6dyJFGf4JnDsRg5gFoBGOCIYj4GOw5tFMMywGc+g8O2jgzqauYVvq1ZMq+lT6TORTNEgkVZhkbYGpm0WWbOMgVAmPQLsYLGcFFPmzAsSxNDsx5NL4srSolDI1pKTS+UFOxdtyM67AUnQyBEWSdH8BSeSC3ngn53CBc2KJEZUc5hZalZpY1GQxR1RTZSR81WlWDVRbWmWFkR8VNGR9WGntkozqlSUZbF2Vxcxy5nelmREddu3JattpERt60mBic60hUJH5YVEYUiV8yLDgFV9tVoC1c9y0zs1EJTQibWmT1COykjF0ZERqOwK12P2URXXY31A0mENpjGHitRTtEYYUMSY6+f5vBBSjZGNl2cO+MOa4NrV0B9ggTTINKQtNKLnSkyCAEi3K4uS9LiuyyrFP-dqeFTgA+qUHMTdzJ0FcufN0ALK7C5r0pi8eEtSzLcsK+M17K-bqvOyCl522L2vGNTdN6wRgsgq47Xu1HCh-oURuzJzk1QgiPPm0ulvINbQuBl7jtq1e-vyzHHtF-nPvu0Xbux7nDsYU76vjH+VeFJ0Ovs4nJvo04hO8wg-NVeH7u197jcKH7rsx0rZf1wXGuu63j0Z-3VuD+RI-l2PlhVzH4me3XJQN2JLfdVhwe4ZOYc20E+tC1PN--jHrG7-HXjGwFQW9+nDYr1na85-vUeLstb30AZvf8J8ep9wHhheGw52JgNnhXBQrEd4rj3jPQ+c9xgckgWfP4QA)

### 💻 Code

```ts
// type definitions simplified from `@reduxjs/toolkit`, `react` and `react-redux`

type Dispatch<A = { type: any; [extraProps: string]: any }> = { <T extends A>(action: T): T };
declare function useMemo<T>(factory: () => T, deps: ReadonlyArray<any> | undefined): T;
declare function useDispatch<TDispatch = Dispatch<any>>(): TDispatch;

// IDestructuring & Destructuring

type IFuncs = { readonly [key: string]: (...p: any) => void };

type IDestructuring<T extends IFuncs> = { readonly [key in keyof T]?: (...p: Parameters<T[key]>) => void };

type Destructuring<T extends IFuncs, U extends IDestructuring<T>> = (dispatch: Dispatch<any>, funcs: T) => U;

// functions

const funcs1 = {
    funcA: (a: boolean): void => {},
    funcB: (b: string, bb: string): void => {},
    funcC: (c: number, cc: number, ccc: boolean): void => {},
};
const funcs2 = {
    funcD: (d: boolean): void => {},
    funcE: (e: string, ee: string): void => {},
    funcF: (f: number, ff: number, fff: boolean): void => {},
};

type TFuncs1 = typeof funcs1;
type TFuncs2 = typeof funcs2;

// react hooks

function useReduxDispatch1<T extends IDestructuring<TFuncs1>>(destructuring: Destructuring<TFuncs1, T>): T {
    return useMemo(() => ({ ...destructuring(useDispatch(), funcs1) }), []);
}

function useReduxDispatch2<T1 extends IDestructuring<TFuncs1>, T2 extends IDestructuring<TFuncs2>>(
    destructuring1: Destructuring<TFuncs1, T1>,
    destructuring2: Destructuring<TFuncs2, T2>,
): T1 & T2 {
    return useMemo(() => ({ ...destructuring1(useDispatch(), funcs1), ...destructuring2(useDispatch(), funcs2) }), []);
}

// test examples

useReduxDispatch1(
    (d, f) => ({ funcA: (...p) => d(f.funcA(...p)), funcC: (...p) => d(f.funcC(...p)) })
);

const _ = useReduxDispatch1(
    (d, f) => ({ funcA: (...p) => d(f.funcA(...p)), funcB: (...p) => d(f.funcB(...p)) })
);

const { funcA, funcB, funcC } = useReduxDispatch1(
    (d, f) => ({ funcA: (...p) => d(f.funcB(...p)), funcB: (...p) => d(f.funcB(...p)), funcC: (...p) => d(f.funcC(...p)) })
);

useReduxDispatch2(
    (d, f) => ({ funcB: (...p) => d(f.funcB(...p)), funcC: (...p) => d(f.funcC(...p)) }),
    (d, f) => ({ funcD: (...p) => d(f.funcD(...p)), funcF: (...p) => d(f.funcF(...p)) }),
);

const { funcA: _funcA, funcC: _funcC, funcE, funcF } = useReduxDispatch2(
    (d, f) => ({ funcA: (...p) => d(f.funcA(...p)), funcC: (...p) => d(f.funcC(...p)) }),
    (d, f) => ({ funcE: (...p) => d(f.funcE(...p)), funcF: (...p) => d(f.funcF(...p)) }),
);
```

### 🙁 Actual behavior

In the function call on line 55, typescript cannot infer the parameters of array functions `funcA`, `funcB` and `funcC`, actually it thinks the parameters `...args` is `any[]`.

But this bugs doesn't occur in function calls on line 46, 50, 58 and 63.
### 🙂 Expected behavior

No compilation errors.

Typescript should infer the parameters `...args` of array function `funcA`, `funcB` and `funcC` correctly.

### LINKED ISSUE #45074: Generic inference from LHS of assignment when destructuring can lead to unexpected `any`s
# Bug Report

### 🔎 Search Terms

Generic inference, destructuring, binding patterns

### 🕗 Version & Regression Information

Exists in 4.3.5

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5&ssl=3&ssc=24&pln=1&pc=1&strict=true#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMRUQYswAxNMAHgBUA+ACgEoAueOgbgCgw8AzhngBveACNY8AL7wAvIWKlyVdK14B6DfAAGkmDvhYBuqKgCehgBakQAOh5A)

### 💻 Code

```ts
declare function genericFunc<T>(): T;
const { bar } = genericFunc();
// `bar` is `any` here.
```

### 🙁 Actual behavior

`bar` is `any` and `T` is inferred to be `{ bar: any }`.

### 🙂 Expected behavior

The inferred type of `T` should be `unknown` and there should be an error from trying to destructure it.
(Or, `T` could still be inferred as `{ bar: any }` but then `noImplicitAny` should trigger an error. This seems at a glance less desirable to me than the former, but I don't know enough how generic inference works to make a more informed recommendation. Anyways, some sort of error no matter how it happens is what would be ideal!)

Notes: see https://github.com/microsoft/TypeScript/issues/43371#issuecomment-881641347 for the original context.

### LINKED ISSUE #45663: When using generic pick, object deconstruction does not provide valid keys to select
# Bug Report

### 🔎 Search Terms

Generic pick on object, type part of object, deconstructing of pick shows all keys of object

### 🕗 Version & Regression Information

- This is a crash
- This first occured today when trying to make some generic object picker
- It was tested on TS 4.3.5 and 4.4.2
- It occures both in TypescriptPlayground and Visual Studio Code
- It decrease developer experience as deconstruction can't be used

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgLJwA4egHgCrIC8ycIAngDTIBKRJ5AfMgN4BQyHyAFHFAOYAuZHgCUQ6gG5WAX1asYAVxAIwwAPYhkGYAgDWOAPJUCEAB6QQAEwDOyXRDJqYyAwy72y1oXgDaAXSo1ACMAKwB+IQMxZAAFHX0jYQYpRWVVDS14-DcPL2F-aPQsaBSlFXVNbT1DY2QzCxs7BycXHIc83wDkYPDIkRZ2TgQNazBMvWghIuwoGpZkHwBpZFBhP0ifPD9kaSZiAH0eoiYDUIgVADoIcChgCGsuQ9CRC6gISwUkLi41Kh8PKgANzgABs-P1CEw2JwYStnO52hdQAgQQpLPcEWQSLZRP01P8HNi1nRgSCpLDOG8wAooJo1OTONIqMxpES4tVEngGCIpIMOFSaXTQsgwuN7FAfs9kEIquKpLJWMMQKN5nAqEEdnRZVwfAByIK6rrMEhCXVwXXq00Gnb9AD0toAFtAUGAnSQFGA1NYFHw+PcxtYHWoFCDLMhA2oAO7IDUaEFkRUjMZHYjavUGo0m5Bmi0xq26m2sHoXODIe3IJ1vFZjYC2SNqKC6UB8LRQNQzeNExwKZAIUjdECd6wQEHnMZBOSsIA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
interface Mapper<T = any, R = any> {
    (arg: T): R;
}

function pick<O, T extends keyof O>(keys: T[], obj?: O): Pick<O, T>;
function pick<T>(keys: T[]): Mapper;
function pick<O, T extends keyof O>(keys: T[], obj?: O) {
    const picker: Mapper<O, { [K in T]: O[T] }> = _obj => Object.entries(_obj).reduce((o, [key, val]) => {
        if (keys.includes(key as T)) o[key as T] = val;
        return o;
    }, {} as Pick<O, T>);

    return obj ? picker(obj) : picker;
}

const { a, b } = pick(['b'], { a: 'a', b: 'b' }) //here the autosuggest should show b only
const obj = pick(['b'], { a: 'a', b: 'b' })
obj.a // here it is working properly as you can only select b
```

### 🙁 Actual behavior

When using the deconstruction construction after pick, I can select b as well as a. But the a is not in object returned from pick.
When first assigning the return value to const, in later code I can only select b, which is expected.

### 🙂 Expected behavior

In deconstruction I should be able to select only keys, that I declared in pick function. The behaviour should be same as in second example, where the return object is first assigned to `obj` var and then refered.

### PR DESCRIPTION
**Pull request by andrewbranch**
Second attempt of #45719 (and #46009)

Fixes #43605
Fixes #45074
Fixes #45663

In the past, when we made inferences to type arguments in return types, we did two things with those inferences: (1) put them in the primary inference context with a low priority, and (2) put them in a secondary inference context that gets used solely for instantiating contextual types of arguments in the same call expression. The consequence of (1) is easily observable when no other inference sources are present to overwrite the low-priority return type inference made from a binding pattern:

```ts
declare function f<T>(): T;
const { foo } = f(); // T: { foo: any }
```

#45719 fixed this by preventing return type inferences from binding patterns altogether, i.e., it stopped both (1) and (2) above. This turned out to be a problem, because (2) produces very desirable behavior with array binding patterns:

```ts
declare function f<T>(cb: () => T): T;
const [e1, e2, e3] = f(() => [1, "hi", true]); T: [number, string, boolean]
```

The binding pattern provides a tuple contextual type for the array literal in the return expression, allowing `e1`, `e2`, and `e3` to have separate types rather than all having `string | number | boolean`. To preserve this desirable behavior, I tried #46009 which only prevented inferences from _object_ binding patterns. However, it was later discovered that this still wasn’t a complete fix, because it still allowed:

```ts
declare function f<T>(): T;
const [e1, e2, e3] = f(); // T: [any, any, any]
```

I ended up reverting all these attempts to reevaluate, with the conclusion

> While it _may_ be true that object binding patterns never contribute anything useful to type argument inference, it is _not_ true that array binding patterns _always_ contribute usefully to type argument inference. What we really want is for binding patterns to contribute contextual typing information to other inference sources, while never being allowed to stand on their own as inference sources.

So that’s what _this_ PR does. Rather than make any distinctions between object and array binding patterns, I make a distinction between inference passes into separate contexts (1) and (2) above. If a contextual type for the return type came from a binding pattern, we make no inferences into (1), but we always make inferences into (2) so that other arguments can benefit from that contextual type (primarily for the array → tuple case—it does happen in other cases but I haven’t found any that are useful).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21248,11 +21248,15 @@ namespace ts {
...
+        function getWidenedLiteralLikeTypeForContextualType(type: Type, contextualType: Type | undefined, node?: Node) {
+            if (isLiteralOfContextualType(type, contextualType)) {
+                return type;
             }
-            return type;
+            const instantiatedContextualType = node && instantiateContextualType(contextualType, node) || contextualType;
+            if (instantiatedContextualType !== contextualType && isLiteralOfContextualType(type, instantiatedContextualType)) {
+                return type;
+            }
+            return getWidenedUniqueESSymbolType(getWidenedLiteralType(type));
```
Comment (andrewbranch) [inline src/compiler/checker.ts:21259]: This change, allowing us to check if `type` is a literal of either the uninstantiated or instantiated contextual type, was necessary to fix this case:

```ts
declare function pick<O, T extends keyof O>(keys: T[], obj?: O): Pick<O, T>;
const _    = pick(['b'], { a: 'a', b: 'b' }); // T: "b"
const {  } = pick(['b'], { a: 'a', b: 'b' }); // T: "b" | "a" ??? (before fix)
```

When the binding pattern is `{}`, we infer `never` for `T` and use that to instantiate the contextual type `T[]` → `never[]` for the argument `['b']`. Because `"b"` is not a “literal of contextual type `never`,” we widen to `string`, which eventually gets replaced with the constraint `keyof O` → `"b" | "a"`.

The change here checks to see if `"b"` is a literal of contextual type `T extends keyof O`, which is already handled by substituting the base constraint, which allows us to see that we should not widen from the literal `"b"`.

Comment (andrewbranch) [reply src/compiler/checker.ts:21259]: As a side note, the reason fixing this is important even given the obvious uselessness of the construct `const {} = anything` is that we ought to be able to deliver accurate completions inside the `{}`. Prior to this fix, you got both `a` and `b` since that’s what `T` had in its domain, but as soon as you accept the `a` completion, the contextual type changes and therefore the inference changes and it becomes an error, which is a terrible experience.

**Comment by andrewbranch** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Review by weswigham — APPROVED** [review]
I'm curious if other callers of `getWidenedLiteralLikeTypeForContextualType` need to be passing `node` (`checkPropertyAssignment`? AFAIK that maybe handles the assignment pattern case `({x} = f())`...?), and some fourslash examples for the completions-relevant examples (to verify those still work using the LS overrides for signature resolution despite these changes), but the core changes themselves look good to me.

**Comment by andrewbranch** [comment]
An example mentioned in the design meeting is broken by this:

```ts
declare function id<T>(x: T): T;
const { f = (x: string) => x.length } = id({ f: x => x.charAt });
```

When getting the type of the function expression inside the call to draw inferences from, we have the contextual type from the binding pattern available, but we don’t use it because we’re skipping context-sensitive functions and return `anyFunctionType` from `checkFunctionExpressionOrObjectLiteralMethod` 😕. Any advice there?

**Comment by weswigham** [comment]
Usually that just means we'll pick up the better type in the next inference pass - the `SkipContextSensitive` pas implies there'll be a context-sensitive second pass that picks up the context-sensitive type.

**Comment by andrewbranch** [comment]
Doh, of course. That was a red herring. Still debugging.

**Comment by andrewbranch** [comment]
Ah, I see what the problem is. I mistook how the `combineTypeMappers` I added in `instantiateContextualType` would handle the first mapper having no inference candidates—I intended it to delegate to the second, but instead the first mapper produces the constraint/default/`unknown` and we just go with that. I think adding a `cloneInferredPartOfContext` would fix this, but I can probably accomplish the same with less object cloning.

**Comment by andrewbranch** [comment]
Hm, ok. I’m actually still having trouble combining these type mappers in a way that works for every case, and I’m not sure if it’s possible.

The issue is that for instantiating contextual _signatures_, we actually do use those low-priority return type inferences as well as other inferences made so far. So when I completely separated those inferences, I attempted recombine them from the two contexts, but I don’t think that’s going to work.

An earlier iteration of this PR, rather than removing binding pattern return type inferences from the primary context, flagged them with another priority flag and then avoided returning  those from `getInferredType`. Maybe I need to go back to something like that 😕

**Comment by andrewbranch** [comment]
@ahejlsberg do you want to take a look at what I have so far before I go down a rabbit hole trying to solve ☝️? Maybe you’ll have an idea for that.

**Comment by andrewbranch** [comment]
@ahejlsberg the changes we discussed yesterday are up. That approach actually fixed this test case:

```ts
declare function id<T>(x: T): T;
const { f = (x: string) => x.length } = id({ f: x => x.charAt });
```

Seems like the best outcome we could have hoped for!

**Comment by sandersn** [comment]
Is this still waiting on a review or is it ready to merge?

**Review by weswigham — APPROVED** [review]

**Comment by andrewbranch** [comment]
I think @ahejlsberg may have wanted a final look at it.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -27051,22 +27051,20 @@ namespace ts {
...
-                if (inferenceContext && some(inferenceContext.inferences, hasInferenceCandidates)) {
+                if (inferenceContext && contextFlags! & ContextFlags.Signature && some(inferenceContext.inferences, hasInferenceCandidates)) {
                     // For contextual signatures we incorporate all inferences made so far, e.g. from return
                     // types as well as arguments to the left in a function call.
-                    if (contextFlags && contextFlags & ContextFlags.Signature) {
-                        return instantiateInstantiableTypes(contextualType, inferenceContext.nonFixingMapper);
-                    }
+                    return instantiateInstantiableTypes(contextualType, inferenceContext.nonFixingMapper);
+                }
+                if (inferenceContext?.returnMapper) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:27059]: This `if` statement now runs even when there are no inference candidates. Is that intended?

**Review by ahejlsberg — APPROVED** [review]
