### PR TITLE
Numeric literals assignable to enum literals only when values match

### LINKED ISSUE #51466: Inconsistent behavior between assignment and "as" with object literals after enums unification
# Bug Report

### 🔎 Search Terms

Conversion may be a mistake enum unification object literal as

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.9 and 5.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221109#code/KYOwrgtgBAYg9nKBvAsAKCpqA5OJhQC8UA1AAwA06WUAgkVAIxUZYBCDATCzQMIMAWFgF906AJYgALsABOAMwCGAYwIBVAM7AN8RKlaZ5CAFywEAbnSi0YtMrwapUAB4MkUaliNxTAditQihpQmtq6ljZ2Dk4AnqahOghuHgZQ3n5W5kA)

### 💻 Code

```ts
enum Foo {
    None = +0,
    A = 1,
    B = 2,
    C = 4,
}

interface UsesFoo {
    foo: Foo;
}


const x = { 
    foo: 7
} as UsesFoo;

const y: UsesFoo = { 
    foo: 7
};
```

### 🙁 Actual behavior

There's an error on the first assignment and no error on the second assignment.

### 🙂 Expected behavior

Probably, no errors on either? Or something consistent?

This is a method suggested by https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#union-enums-cannot-be-compared-to-arbitrary-numbers (and I minimized this from OWA).

### PR DESCRIPTION
**Pull request by ahejlsberg**
For purposes of representing collections of bit flags as enum types we have always permitted type `number` to be assigned to any numeric enum literal type (because `number` is the type that results when bit flags are or'd and and'ed using the `|` and `&` operators). However, we have also permitted _any_ numeric literal type to be assigned to _any_ numeric enum literal type, even when the underlying numeric values differ. This rule makes little sense and is revoked by this PR.

The general effect of this change is that when a numeric type value is _known_ not to match any of the declared members of an enum type (because the numeric value has a literal type that doesn't have a match in the enum type), the numeric type value is not assignable to that enum type. This in particular means that the literal value `0` cannot be used to initialize a bit flags enum type unless the enum type declares a member with the value `0`.

```ts
const enum Flags1 {
    A = 1 << 0,
    B = 1 << 1,
    C = 1 << 2,
}

const enum Flags2 {
    None = 0,
    A = 1 << 0,
    B = 1 << 1,
    C = 1 << 2,
}

let a: Flags1 = 0;  // Error
let b: Flags1 = 0 as Flags1;  // Ok
let c: Flags2 = Flags2.None;  // Ok
```

Note above that it is always possible to use an `as` assertion to coerce an arbitrary numeric value to an enum type.

Fixes #51466.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8659,7 +8660,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
 
     function formatUnionTypes(types: readonly Type[]): Type[] {
         const result: Type[] = [];
-        let flags: TypeFlags = 0;
+        let flags = 0 as TypeFlags;
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:8663]: Consider adding `TypeFlags.Uninitialized` ?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
