### PR TITLE
Fix implied constraints in conditional types

### LINKED ISSUE #22985: Can't dereference array type in conditional type
**TypeScript Version:**  2.8.1 and 2.9.0-dev.20180329

**Search Terms:** 

I tried actually a **lot** of terms around mapped types, arrays, conditional types, array member dereferencing in mapped types etc..

**Code**

```ts
export type RecursivePartial<T> = {
  [P in keyof T]?: T[P] extends Array<any> ? {[index: number]: RecursivePartial<T[P][0]>} :
    T[P] extends object ? RecursivePartial<T[P]> : T[P];
};

var a = {o: 1, b: 2, c: [{a: 1, c: '213'}]}
function assign<T>(o: T, a: RecursivePartial<T>) { }
assign(a, {o: 2, c: {0: {a: 2, c: '213123'}}})
```

**Expected behavior:**

`T[P][0]` is usable and doesn't produce an error, since T[P] extends any[] and should thus be indexable on [0] (it seems this is the way to dereference an array)

**Actual behavior:**
I am getting `type 0 cannot be used to index type T[P]`.

The odd part is that behaviour-wise it seems to be working ! I can't change the type of the nested `c` to anything other than string and I can't create random properties or what.

Am I missing something ?

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #22985.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7395,7 +7395,7 @@ namespace ts {
 
         function getConstrainedTypeVariable(typeVariable: TypeVariable, node: Node) {
             let constraints: Type[];
-            while (isPartOfTypeNode(node)) {
+            while (node && !isStatement(node)) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Is `isExpression` preferable to `isStatement` here?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: No, there might not be an enclosing expression anywhere in the parent chain.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: We could *additionally* check for `!isExpression(node)` but it isn't really necessary, we'll eventually hit a statement (which could be a declaration statement) or the very top node.
