### PR TITLE
Fix crash when binding jsdoc-style inner namepaths

### LINKED ISSUE #25104: Crash when typedef references a jsdoc-style inner-class namepath
From [discussion on a bug with related symptoms](https://github.com/Microsoft/TypeScript/issues/22702#issuecomment-398871461).

```js
class C {
    /**
     * @typedef {C~A} C~B
     * @typedef {object} C~A
     */
    /** @param {C~A} o */
    constructor(o) {
    }
}
```

**Expected behavior:**
No crash, although `o: any` because we don't parse namepaths.

**Actual behavior:**

```
        return node.kind === 71 /* Identifier */;
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (/home/nathansa/ts/built/local/tsc.js:12193:21)
    at getDeclarationIdentifier (/home/nathansa/ts/built/local/tsc.js:11954:19)
    at nameForNamelessJSDocTypedef (/home/nathansa/ts/built/local/tsc.js:11916:20)
    at getNameOfJSDocTypedef (/home/nathansa/ts/built/local/tsc.js:11957:36)
    at Object.getNameOfDeclaration (/home/nathansa/ts/built/local/tsc.js:12002:24)
    at Object.hasDynamicName (/home/nathansa/ts/built/local/tsc.js:9844:23)
    at declareSymbol (/home/nathansa/ts/built/local/tsc.js:25659:33)
    at bindBlockScopedDeclaration (/home/nathansa/ts/built/local/tsc.js:26949:21)
    at delayedBindJSDocTypedefTag (/home/nathansa/ts/built/local/tsc.js:26974:21)
    at bindSourceFile (/home/nathansa/ts/built/local/tsc.js:25532:17)
```

### PR DESCRIPTION
**Pull request by sandersn**
getNameOfDeclaration actually doesn't handle all declarations, only those that produce names that could be reasonably used as an identifier.  Until now, getDeclarationIdentifier assumed that getNameOfDeclaration always returned a name. This caused crashes whenever we tried to get the name of something like a Constructor.

Fixes #25104

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -4847,7 +4847,7 @@ namespace ts {
 
     function getDeclarationIdentifier(node: Declaration | Expression): Identifier | undefined {
         const name = getNameOfDeclaration(node);
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: can we fix `getNameOfDeclaration` as well to return nullable type? i do not know where else our assumptions are wrong, and this seems like a good time as any to fix them once and for all.

Comment (sandersn) [reply src/compiler/utilities.ts]: I'll try. It's used a lot of places without checking, but many of these follow a similar error-reporting pattern that might be supportable with a non-nullable overload or something.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -22814,11 +22814,7 @@ namespace ts {
             addDiagnostic(UnusedKind.Local, createDiagnosticForNode(node, message, name));
         }
 
-        function parameterNameStartsWithUnderscore(parameterName: DeclarationName) {
-            return parameterName && isIdentifierThatStartsWithUnderScore(parameterName);
-        }
-
-        function isIdentifierThatStartsWithUnderScore(node: Node) {
+        function isIdentifierThatStartsWithUnderscore(node: Node) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: I also eliminated the now-redundant `parameterNameStartsWithUnderscore` and fixed the capitalisation of `isIdentifierThatStartsWithUnderscore`.
