### PR TITLE
fix(60563):@import * as namespace cannot be used with @implements

### LINKED ISSUE #60563: `@import * as namespace` cannot be used with `@implements`
### 🔎 Search Terms

- `cannot be used as a value because it was imported using 'import type'`
- `implements`

### 🕗 Version & Regression Information

- I was unable to test this on prior versions (to v4.1.5) because `every-ts` failed to build them.

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&allowJs=true&moduleResolution=3&target=9&module=100&ts=5.6.3#code/PTAEAEEMBtoewO4CkDOAoEEDGALAplgNapoZjgBmAltHgHaQC2eAXKA8ygA6RZ4B0AF3R4AHlzgAnQaCp1BeSRV55QAMThxIAI1qgA3mlCgKmgBQBKNgDc4VACYBuNAF9SZCNVodWoYQFoqRglpIXQgkJlBAE8uVQAqUEgUUAA5AGUTSThGUAAifmAfbhU85zQxSNAsaGSUgBUcOQBzRshBAGFIOg04WWDaZnkUjP5enT19N1JMShp6Jl8AKxRA4KlBfhWMePijRPAIjdBE5LTMimzcgHJC4p4+a-3gGd2ICMH6YQNR8d08FwnF6VY41OqgRotNqdbq9AxuIA

### 💻 Code

```ts repro
// @allowJs
// @checkJs

// @filename: namespace.ts
export interface Fooable {
  foo(): void;
}


// @filename: ts-import.ts
import type * as NS from "./namespace";

export class ThingThatCanFoo implements NS.Fooable {}


// @filename: js-import.js
/**
 * @import * as NS from './namespace'
 */

/** @implements {NS.Fooable} */
export class ThingThatCanFoo {}

```

### 🙁 Actual behavior

* `/** @implements {NS.Fooable} */` has error: `'NS' cannot be used as a value because it was imported using 'import type'.`
* Both versions of `ThingThatCanFoo` correctly report that they do not fully implement `Fooable`.

### 🙂 Expected behavior

* `/** @implements {NS.Fooable} */` should not have an error, exactly like `implements NS.Fooable` above.
* Both versions of `ThingThatCanFoo` should still report that they do not fully implement `Fooable`.

### Additional information about the issue

Notably, in the JSDoc version, using a non-type import removes the error:

```
import * as NS from "./namespace";
```

However, this causes a runtime import that's only used for type information.

**Related issues**

- https://github.com/microsoft/TypeScript/issues/36428 (The same issue using `import type` in TS instead of `@import` in JSDoc)

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #60563

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -10492,7 +10493,8 @@ function isIdentifierInNonEmittingHeritageClause(node: Node): boolean {
                 return "quit";
         }
     }) as HeritageClause | undefined;
-    return heritageClause?.token === SyntaxKind.ImplementsKeyword || heritageClause?.parent.kind === SyntaxKind.InterfaceDeclaration;
+    if (heritageClause === undefined) return false;
+    return isJSDocImplementsTag(heritageClause) || heritageClause.token === SyntaxKind.ImplementsKeyword || heritageClause.parent.kind === SyntaxKind.InterfaceDeclaration;
```
Comment (jakebailey) [inline src/compiler/utilities.ts:10497]: `isIdentifierInNonEmittingHeritageClause` is only used for `isValidTypeOnlyAliasUseSite`. Is is the case we could instead make `isValidTypeOnlyAliasUseSite` just _always_ allow use from JSDoc? After all, those are necessarily non-JS-code-emitting nodes.

Comment (a-tarasyuk) [reply src/compiler/utilities.ts]: @jakebailey I’ve updated it to _always_ allow usage from JSDoc and removed the specific case with the implements tag. Thanks

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot test it
