### PR TITLE
Avoid crash for import code fixes with dotted require

### LINKED ISSUE #47428: Crash in completionEntryDetails with existing `require("...").foo`
```ts
// @allowJs: true
// @Filename: library.js
export function aaa() {}
export function bbb() {}

// @Filename: foo.js
var a = require("./library").aaa
/**/
```

Go to the marker `/**/` and request completion details on `bbb`.

```
Response received: completionEntryDetails (523). Request took 5 ms. Success: false . Message: Error processing request. Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at getModuleSpecifierExpression ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:137533:93)
    at compareImportsOrRequireStatements ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:137555:44)
    at binarySearchKey ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:1200:21)
    at Object.binarySearch ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:1178:16)
    at Object.getImportDeclarationInsertionIndex ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:137545:28)
    at Object.insertImports ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:124647:57)
    at codeActionForFixWorker ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:148939:24)
    at [NODE_MODULES_PATH]/typescript/lib/tsserver.js:148911:24
    at Function.ChangeTracker.with ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:144341:17)
    at codeActionForFix ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:148910:60)
    at Object.getImportCompletionAction ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:148426:55)
    at getCompletionEntryCodeActionsAndSourceDisplay ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:129176:33)
    at Object.getCompletionEntryDetails ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:129120:30)
    at Object.getCompletionEntryDetails ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:160080:35)
    at [NODE_MODULES_PATH]/typescript/lib/tsserver.js:171575:57
    at Object.mapDefined ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:619:30)
    at IOSession.Session.getCompletionEntryDetails ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:171573:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:170398:61)
    at [NODE_MODULES_PATH]/typescript/lib/tsserver.js:172193:88
    at IOSession.Session.executeWithRequestId ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:172184:28)
    at IOSession.Session.executeCommand ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:172193:33)
    at IOSession.Session.onMessage ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:172219:35)
    at Interface.<anonymous> ([NODE_MODULES_PATH]/typescript/lib/tsserver.js:174824:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #47428.

Okay, here's the summary:

First, we have a type predicate in our services layer that determines whether something is an `import` statement or a variable initialized with a `require` call.

https://github.com/microsoft/TypeScript/blob/0f1496f3546dd51b64099732ddac1e59a0367905/src/services/utilities.ts#L2032

That type predicate is wrong because it takes a dependency on `isRequireVariableStatement`...

https://github.com/microsoft/TypeScript/blob/0f1496f3546dd51b64099732ddac1e59a0367905/src/compiler/utilities.ts#L2123-L2127

which relies on `isRequireVariableDeclaration`...

https://github.com/microsoft/TypeScript/blob/0f1496f3546dd51b64099732ddac1e59a0367905/src/compiler/utilities.ts#L2116-L2121

which returns `true` a variable like in `const foo = require("yadda").foo`.

Because the type predicate is wrong, we eventually end up crashing because we think we have a `CallExpression` on the initializer and can't access the first argument, resulting in:

> TypeError: Cannot read property '0' of undefined

So my solution here is to split up the usages of the function - some for when a consumer can tolerate the property access version (`require("yadda").foo`), and some for tolerating the bare `require("yadda")` version. `isRequireVariableStatement` can safely be changed to rely on the bare version because it's only called by the type predicate function.

This at the very least avoids crashing for code-fixes without impacting go-to-definition, and other functionality in the type-checker itself.

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -4668,6 +4668,11 @@ namespace ts {
         readonly initializer: RequireOrImportCall;
     }
 
+    /* @internal */
+    export interface AccessedOrBareRequireVariableDeclaration extends VariableDeclaration {
```
Comment (sandersn) [inline src/compiler/types.ts:4672]: I think I prefer RequireVariableDeclarationOrExpression

**Review by sandersn — APPROVED** [review]
The fix seems good, I just don't like the new name at all.
I suggested a slightly less bad name, although it's still not good.

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -3274,15 +3274,15 @@ namespace ts {
             return isEnumConst(node)
                 ? bindBlockScopedDeclaration(node, SymbolFlags.ConstEnum, SymbolFlags.ConstEnumExcludes)
                 : bindBlockScopedDeclaration(node, SymbolFlags.RegularEnum, SymbolFlags.RegularEnumExcludes);
-        }
+            }
```
Comment (jakebailey) [inline src/compiler/binder.ts:3277]: This looks like an accidental change.

File: src/compiler/types.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/types.ts:4672]: I'd agree (less easy to miss if you're doing completion and were about to use the old one, too).

Comment (andrewbranch) [reply src/compiler/types.ts:4672]: It’s not a “declaration or expression” though—it’s always a variable declaration, and the initializer of that variable declaration is always an expression. The thing that changes is whether that expression is a special call expression or a property access expression off that special call expression. I don’t like either of these names and don’t have a better suggestion ready, but I don’t understand what `RequireVariableDeclarationOrExpression` is supposed to mean.

Comment (DanielRosenwasser) [reply src/compiler/types.ts:4672]: I think I'm going to go with `VariableDeclarationInitializedTo<T>` with `CallExpression` and `AccessExpression | CallExpression`.

**Comment by DanielRosenwasser** [comment]
I've renamed both functions uniformly so you can't miss them, though I've left `isRequireVariableStatement` alone. That can be a follow-up if people feel strongly enough about it.

**Review by jakebailey — APPROVED** [review]
Seems okay to me, but someone else may object to the naming, of course.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.5
