### PR TITLE
Fixes rename for destructuring, named imports and default imports

### LINKED ISSUE #6312: Unable to rename the property of destructuring assignment
Rename `a` to `b`.

``` ts
function f({a}: {a}) {
    f({a});
}
```

expected:

``` ts
function f({b}: {b}) {
    f({b});
}
```

actual:

``` ts
// rename the variable
function f({b}: {a}) {
    f({b});
}
// rename the declaration
function f({a}: {b}) {
    f({b});
}
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #6312,  #7708 and #7024

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -5624,8 +5624,34 @@ namespace ts {
                 };
             }
 
-            function isImportSpecifierSymbol(symbol: Symbol) {
-                return (symbol.flags & SymbolFlags.Alias) && !!getDeclarationOfKind(symbol, SyntaxKind.ImportSpecifier);
+            function getImportOrExportSpecifierPropertyNameSymbolSpecifier(symbol: Symbol, location: Node): ImportOrExportSpecifier {
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: `getImportOrExportSpecifierForPropertyNameSymbol`?

**Comment by DanielRosenwasser** [comment]
Is there a way to open the scope of this for object assignment patterns?

```ts
interface I {
    x: number;
}

var a: I;
var x;

({ /*renameHere*/x: x } = a);
```

File: src/services/services.ts (hunk 1 above)
Comment (sheetalkamat) [inline src/services/services.ts]: done

**Comment by sheetalkamat** [comment]
That eg. gets handled by ad916ab. I added the test case for it just now.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11839,44 +11844,49 @@ namespace ts {
...
-                            checkDestructuringAssignment(e, type, contextualMapper);
+                checkArrayLiteralDestructuringElementAssignment(node, sourceType, elements[i], i, elementType, contextualMapper);
+            }
+            return sourceType;
+        }
+
+        function checkArrayLiteralDestructuringElementAssignment(node: ArrayLiteralExpression, sourceType: Type,
+            element: Expression, index: number, elementType: Type, contextualMapper?: TypeMapper) {
+            const elements = node.elements;
+            if (element.kind !== SyntaxKind.OmittedExpression) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Does this implicitly return `undefined`? Invert the conditions here to reduce nesting and make the returns explicit.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -11839,44 +11844,49 @@ namespace ts {
...
-                                : elementType;
-                        if (type) {
-                            checkDestructuringAssignment(e, type, contextualMapper);
+                checkArrayLiteralDestructuringElementAssignment(node, sourceType, elements[i], i, elementType, contextualMapper);
+            }
+            return sourceType;
+        }
+
+        function checkArrayLiteralDestructuringElementAssignment(node: ArrayLiteralExpression, sourceType: Type,
+            element: Expression, index: number, elementType: Type, contextualMapper?: TypeMapper) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I'd consider just passing in the index instead of the element itself and renaming `index` to `elementIndex`

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -16549,6 +16559,34 @@ namespace ts {
             return unknownType;
         }
 
+        function getTypeOfArrayLiteralOrObjectLiteralDestructuringAssignment(expr: Expression): Type {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Is `expr` the initializer? Or the assignment expression? Can you document that explicit with a comment and using a slightly more precise type than `Expression`?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -16549,6 +16559,34 @@ namespace ts {
...
+            //     for ({a } = elems[0];.....) { }
+            if (expr.parent.kind === SyntaxKind.BinaryExpression) {
+                const iteratedType = checkExpression((<BinaryExpression>expr.parent).right);
+                return checkDestructuringAssignment(expr, iteratedType || unknownType);
+            }
+            // If this is from nested object binding pattern
+            //     for ({ skills: { primary, secondary } } = multiRobot, i = 0; i < 1; i++) {
+            if (expr.parent.kind === SyntaxKind.PropertyAssignment) {
+                const typeOfParentObjectLiteral = getTypeOfArrayLiteralOrObjectLiteralDestructuringAssignment(<Expression>expr.parent.parent);
+                return checkObjectLiteralDestructuringPropertyAssignment(typeOfParentObjectLiteral, <ObjectLiteralElement>expr.parent);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Do you need to sub in `unknownType` in case `typeOfParentObjectLiteral` is undefined?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -16549,6 +16559,34 @@ namespace ts {
...
+            }
+            // Array literal assignment - array destructuring pattern
+            Debug.assert(expr.parent.kind === SyntaxKind.ArrayLiteralExpression);
+            //    [{ property1: p1, property2 }] = elems;
+            const typeOfArrayLiteral = getTypeOfArrayLiteralOrObjectLiteralDestructuringAssignment(<Expression>expr.parent);
+            const elementType = checkIteratedTypeOrElementType(typeOfArrayLiteral, expr.parent, /*allowStringInput*/ false) || unknownType;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You only use `|| unknownType` above when you called into other functions, so I would keep it consistent

File: src/services/services.ts [hunk 7]
```diff
@@ -5624,8 +5624,34 @@ namespace ts {
...
+                        declaration => (declaration.kind === SyntaxKind.ImportSpecifier ||
+                            declaration.kind === SyntaxKind.ExportSpecifier) ? declaration : undefined);
+                    if (importOrExportSpecifier &&
+                        // export { a } 
+                        (!importOrExportSpecifier.propertyName ||
+                            // export {a as class } where a is location
+                            importOrExportSpecifier.propertyName === location)) {
+                        return importOrExportSpecifier;
+                    }
+                }
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: Use an explicit return

File: src/services/services.ts [hunk 8]
```diff
@@ -5624,8 +5624,34 @@ namespace ts {
...
+                    bindingElement.parent.kind === SyntaxKind.ObjectBindingPattern &&
+                    !bindingElement.propertyName;
+            }
+
+            function getPropertySymbolIfObjectBindingPatternWithoutPropertyName(symbol: Symbol) {
+                if (isObjectBindingPatternElementWithoutPropertyName(symbol)) {
+                    const bindingElement = <BindingElement>getDeclarationOfKind(symbol, SyntaxKind.BindingElement);
+                    const typeOfPattern = typeChecker.getTypeAtLocation(bindingElement.parent);
+                    return typeOfPattern && typeChecker.getPropertyOfType(typeOfPattern, (<Identifier>bindingElement.name).text);
+                }
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: Explicit returns

File: src/services/services.ts [hunk 9]
```diff
@@ -6197,32 +6256,49 @@ namespace ts {
...
-                        return aliasedSymbol;
-                    }
-                }
 
                 // If the reference location is in an object literal, try to get the contextual type for the
                 // object literal, lookup the property symbol in the contextual type, and use this symbol to
                 // compare to our searchSymbol
                 if (isNameOfPropertyAssignment(referenceLocation)) {
-                    return forEach(getPropertySymbolsFromContextualType(referenceLocation), contextualSymbol => {
+                    const contexualSymbol = forEach(getPropertySymbolsFromContextualType(referenceLocation), contextualSymbol => {
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: contextualSymbol

File: src/services/services.ts [hunk 10]
```diff
@@ -6197,32 +6256,49 @@ namespace ts {
...
                         return forEach(typeChecker.getRootSymbols(contextualSymbol), s => searchSymbols.indexOf(s) >= 0 ? s : undefined);
                     });
+
+                    if (contexualSymbol) {
+                        return contexualSymbol;
+                    }
+
+                    // If the reference location is name of property symbol from object literal destructuring pattern
+                    // Compare it to search symbol something similar to 'property' from
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: I don't understand this second line off the bat

File: src/services/services.ts [hunk 11]
```diff
@@ -6197,32 +6256,49 @@ namespace ts {
...
+                    //      for ( { property: p2 } of elems) { }
+                    if (isArrayLiteralOrObjectLiteralDestructuringPattern(referenceLocation.parent.parent)) {
+                        // Do work to determine if this is property symbol corresponding to the search symbol
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: a property symbol

File: src/services/services.ts [hunk 12]
```diff
@@ -6197,32 +6256,49 @@ namespace ts {
...
-                    return forEach(getPropertySymbolsFromContextualType(referenceLocation), contextualSymbol => {
+                    const contexualSymbol = forEach(getPropertySymbolsFromContextualType(referenceLocation), contextualSymbol => {
                         return forEach(typeChecker.getRootSymbols(contextualSymbol), s => searchSymbols.indexOf(s) >= 0 ? s : undefined);
                     });
+
+                    if (contexualSymbol) {
+                        return contexualSymbol;
+                    }
+
+                    // If the reference location is name of property symbol from object literal destructuring pattern
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: the name

File: tests/cases/fourslash/findAllRefsObjectBindingElementPropertyName03.ts [hunk 13]
```diff
@@ -6,7 +6,7 @@
 ////}
 ////
 ////var foo: I;
-////var [{ [|property1|]: prop1 }, { property1, property2 } ] = [foo, foo];
+////var [{ [|property1|]: prop1 }, { [|property1|], property2 } ] = [foo, foo];
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/findAllRefsObjectBindingElementPropertyName03.ts]: Nice!

File: src/services/services.ts (hunk 9 above)
Comment (sheetalkamat) [inline src/services/services.ts]: ahh! thanks for catching this

File: tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts [hunk 14]
```diff
@@ -0,0 +1,20 @@
+/// <reference path='fourslash.ts' />
+
+////interface I {
+////    property1: number;
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts]: So why exactly wouldn't `property1` cascade to this declaration?

Comment (sheetalkamat) [inline tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts]: Becauyse you are finding ref on var property1 which is different from property property1

Comment (DanielRosenwasser) [inline tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts]: We should fix that at some point, but not here

File: src/services/services.ts [hunk 15]
```diff
@@ -5624,8 +5624,36 @@ namespace ts {
...
+            }
+
+            function isObjectBindingPatternElementWithoutPropertyName(symbol: Symbol) {
+                const bindingElement = <BindingElement>getDeclarationOfKind(symbol, SyntaxKind.BindingElement);
+                return bindingElement &&
+                    bindingElement.parent.kind === SyntaxKind.ObjectBindingPattern &&
+                    !bindingElement.propertyName;
+            }
+
+            function getPropertySymbolIfObjectBindingPatternWithoutPropertyName(symbol: Symbol) {
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: `getPropertySymbolIfObjectBindingPatternLacksPropertyName`

Comment (DanielRosenwasser) [inline src/services/services.ts]: Or did you mean `Of` instead of `If`

Comment (sheetalkamat) [inline src/services/services.ts]: I meant of :)

File: tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts (hunk 14 above)
Comment (sheetalkamat) [inline tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts]: Don't think you want to combine that.. Just because you happen to rename the name of variable (say so it contains all types of properties at various instances) doesn't mean you want to rename the properties. So current behavior is what you want there

Comment (DanielRosenwasser) [inline tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts]: Potentially, but then you end up breaking code in at least one other place.

Comment (sheetalkamat) [inline tests/cases/fourslash/renameDestructuringAssignmentInForOf2.ts]: Which would need intentional rename which is good.

File: tests/cases/fourslash/findAllRefsObjectBindingElementPropertyName06.ts [hunk 16]
```diff
@@ -23,6 +23,7 @@ let ranges = test.ranges();
 for (let range of ranges) {
     goTo.position(range.start);
 
+    debugger;
```
Comment (mhegazy) [inline tests/cases/fourslash/findAllRefsObjectBindingElementPropertyName06.ts]: remove

File: src/services/services.ts [hunk 17]
```diff
@@ -6068,18 +6102,36 @@ namespace ts {
...
+                //     export {a}
+                // If the symbol is an alias to default declaration, add what it aliases to the list
+                //     declare "mod" { export default class B { } }
+                //     import B from "mod";
+                //// For export specifiers, the exported name can be referring to a local symbol, e.g.:
+                ////     import {a} from "mod";
+                ////     export {a as somethingElse}
+                //// We want the *local* declaration of 'a' as declared in the import,
+                //// *not* as declared within "mod" (or farther)
+                const importOrExportSpecifier = getImportOrExportSpecifierForPropertyNameSymbol(symbol, location);
```
Comment (mhegazy) [inline src/services/services.ts]: i would push this logic in getImportOrExportSpecifierForPropertyNameSymbol instead of duplicating it twice

File: src/services/services.ts [hunk 18]
```diff
@@ -6068,18 +6102,36 @@ namespace ts {
...
-                // If the symbol is an alias, add what it aliases to the list
-                if (isImportSpecifierSymbol(symbol)) {
-                     result.push(typeChecker.getAliasedSymbol(symbol));
+                // If the location is name of property symbol from object literal destructuring pattern
+                // Search the property symbol
+                //      for ( { property: p2 } of elems) { }
+                if (isNameOfPropertyAssignment(location) &&
+                    location.parent.kind !== SyntaxKind.ShorthandPropertyAssignment &&
+                    isArrayLiteralOrObjectLiteralDestructuringPattern(location.parent.parent)) {
+                    const typeOfObjectLiteral = typeChecker.getTypeOfArrayLiteralOrObjectLiteralDestructuringAssignment(<Expression>location.parent.parent);
```
Comment (mhegazy) [inline src/services/services.ts]: You jsut need the symbol here, so i would say this should return a symbol and possibly be named: `getSoruceSymbolOfBindingPatternAssignment`

File: src/compiler/checker.ts [hunk 19]
```diff
@@ -16549,6 +16561,40 @@ namespace ts {
             return unknownType;
         }
 
+        // Gets the type of object literal or array literal of destructuring assignment.
+        // { a } from 
+        //     for ( { a } of elems) {
+        //     }
+        // [ a ] from 
+        //     [a] = [ some array ...]
+        function getTypeOfArrayLiteralOrObjectLiteralDestructuringAssignment(expr: Expression): Type {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: is not this the same as `getTypeFromBindingPattern`

Comment (sheetalkamat) [inline src/compiler/checker.ts]: Its kind of higher level and gets the type of binding patterns object literal or array literal from binding pattern assignment. ```GetTypeFromBindingPattern``` needs ```BindingPattern```. These are object literals and array literals from assignment so different node kinds

Comment (mhegazy) [inline src/compiler/checker.ts]: we should then change the entry point to return a targetSymbol for a bindingPattern instead of a type.

Comment (sheetalkamat) [inline src/compiler/checker.ts]: @mhegazy done.

**Comment by mhegazy** [comment]
:+1:
