### PR TITLE
Fix indexed access constraint

### LINKED ISSUE #31385: type infer failed with a pathological case in 3.5.0, but in 3.4.0 it works
**TypeScript Version:**  3.5.0-dev.20190509

**Search Terms:**
generic, keyof
**Code**

```ts
type Foo<T> = {
  [key: string]: { [key_ in keyof T]: key_ }[keyof T]
}
type Bar<T> = {
  [key: string]: { [key_ in keyof T]: [key_] }[keyof T]
}

type Baz<T, Q extends Foo<T>> = {
  [key in keyof Q]: T[Q[key]]
}

type Qux<T, Q extends Bar<T>> = {
  [key in keyof Q]: T[Q[key]["0"]] // error!
}
```

**Expected behavior:**
Qux is also a valid generic definition.
**Actual behavior:**
Type 'Q[key]["0"]' cannot be used to index type 'T'.ts(2536)
**Playground Link:** 
https://www.typescriptlang.org/play/#src=type%20Foo%3CT%3E%20%3D%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20%7B%20%5Bkey_%20in%20keyof%20T%5D%3A%20key_%20%7D%5Bkeyof%20T%5D%0D%0A%7D%0D%0Atype%20Bar%3CT%3E%20%3D%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20%7B%20%5Bkey_%20in%20keyof%20T%5D%3A%20%5Bkey_%5D%20%7D%5Bkeyof%20T%5D%0D%0A%7D%0D%0A%0D%0Atype%20Baz%3CT%2C%20Q%20extends%20Foo%3CT%3E%3E%20%3D%20%7B%0D%0A%20%20%5Bkey%20in%20keyof%20Q%5D%3A%20T%5BQ%5Bkey%5D%5D%0D%0A%7D%0D%0A%0D%0Atype%20Qux%3CT%2C%20Q%20extends%20Bar%3CT%3E%3E%20%3D%20%7B%0D%0A%20%20%5Bkey%20in%20keyof%20Q%5D%3A%20T%5BQ%5Bkey%5D%5B%220%22%5D%5D%20%2F%2F%20error!%0D%0A%7D
> Baz gives the same error here, Qux is ok. Typescript version matters?

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #31385.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7657,15 +7657,20 @@ namespace ts {
             return hasNonCircularBaseConstraint(type) ? getConstraintFromIndexedAccess(type) : undefined;
         }
 
+        function getSimplifiedTypeOrConstraint(type: Type) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Line 13065 in the checker could also be using an invocation of this helper.

**Comment by ahejlsberg** [comment]
DT issues are unrelated to this PR, so I think it's good to merge.
