### PR TITLE
fix(36385): tsc should return a failed exit code (ie: 1) when it can't build due to no config file

### LINKED ISSUE #36385: tsc should return a failed exit code (ie: 1) when it can't build due to no config file
**tsc version**
Version 3.7.5

**Impact**
This caused our docker builds to pass and go into a test environment when they should have failed. For various reasons, the tsconfig.json file wasn't copied into the docker container - having tsc fail in this case would have blocked us deploying and made the root cause of the failing containers more obvious.

**Search Terms:** 
exit value
exit config missing

**Code**

when no tsconfig.json file:
tsc
echo $?

**Expected behavior:**
returns a non-0 exit code

**Actual behavior:**
returns a 0 exit code

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/33849

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #36385

### CODE REVIEW

File: src/testRunner/unittests/tsc/runWithoutArgs.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+namespace ts {
+    describe("unittests:: tsc:: runWithoutArgs::", () => {
+        verifyTsc({
+            scenario: "runWithoutArgs",
+            subScenario: "show help with ExitStatus.DiagnosticsPresent_OutputsSkipped",
+            fs: () => loadProjectFromDisk("tests/projects/runWithoutArgs"),
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tsc/runWithoutArgs.ts]: You want to use `loadProjectFromFiles({})` instead.

Comment (a-tarasyuk) [reply src/testRunner/unittests/tsc/runWithoutArgs.ts]: @sheetalkamat oke, thanks.
