### PR TITLE
Fix prototype property type lookup

### LINKED ISSUE #33013: JS: Prototype property assignment prevents property lookup from type reference
```js
var Validator = function Validator(parser) {
    this.flags = "gim"
};

Validator.prototype.num = 12
/**
 * @param {Validator} state
 */
var validateRegExpFlags = function(state) {
    return state.flags
};
```

**Expected behavior:**
`state.flags: string`

**Actual behavior:**
Property 'flags' does not exist on type 'Validator'

Note that if you use a value like `new Validator().flags`, the property is resolved just fine. If you remove the prototype property assignment, the property also resolves.

Seems like an interaction of the contructor-functions-as-classes  + stricter-jsdoc-type-references PR.

### PR DESCRIPTION
**Pull request by sandersn**
This removes over half of the weird code for supporting JS in getTypeReferenceType. Lookup of commonjs aliases is still there and still weird, but I improved the documentation a little.

Fixes #33013

### CODE REVIEW

**Comment by sandersn** [comment]
@andrewbranch @PranavSenthilnathan you might be interested in this. Pranav, I remember you made the last edit to the documentation of getTypeFromJSAlias. It's used only for aliases now, so much of the previous text didn't apply anymore.

**Comment by andrewbranch** [comment]
@orta might be interested in looking at it too after he gets back, since he fixed a couple expando-related bugs recently.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9209,62 +9228,34 @@ namespace ts {
...
-                isJSConstructor(symbol.valueDeclaration)) {
-                const resolved = resolveStructuredTypeMembers(<ObjectType>getTypeOfSymbol(symbol));
-                if (resolved.callSignatures.length === 1) {
-                    return getReturnTypeOfSignature(resolved.callSignatures[0]);
-                }
+        function getTypeFromJSAlias(node: NodeWithTypeArguments, symbol: Symbol): Type | undefined {
+            const valueType = getTypeOfSymbol(symbol);
+            const typeType =
+                valueType.symbol &&
+                valueType.symbol !== symbol && // Make sure this is a commonjs export by checking that symbol -> type -> symbol doesn't roundtrip.
```
Comment (weswigham) [inline src/compiler/checker.ts]: We do have tests that still fall thru and use this function, right?

Comment (sandersn) [reply src/compiler/checker.ts]: Yes, about 6. None of them are classes anymore, though.

Comment (sandersn) [reply src/compiler/checker.ts]: Believe me, I tried deleting it to make sure. =P

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9195,10 +9211,13 @@ namespace ts {
             if (symbol === unknownSymbol) {
                 return errorType;
             }
+            symbol = getExpandoSymbol(symbol) || symbol;
 
-            const type = getTypeReferenceTypeWorker(node, symbol, typeArguments);
-            if (type) {
-                return type;
+            if (symbol.flags & (SymbolFlags.Class | SymbolFlags.Interface)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: these two cases are all that's left of getTypeReferenceTypeWorker

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -9195,10 +9211,13 @@ namespace ts {
             if (symbol === unknownSymbol) {
                 return errorType;
             }
+            symbol = getExpandoSymbol(symbol) || symbol;
```
Comment (sandersn) [inline src/compiler/checker.ts]: getExpandoSymbol takes care of the JS special cases that used to be in getTypeReferenceTypeWorker; then you just treat them like normal symbols afterward.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -9209,62 +9228,34 @@ namespace ts {
...
-            }
-
-            if (symbol.flags & SymbolFlags.Function &&
-                isJSDocTypeReference(node) &&
-                isJSConstructor(symbol.valueDeclaration)) {
-                const resolved = resolveStructuredTypeMembers(<ObjectType>getTypeOfSymbol(symbol));
-                if (resolved.callSignatures.length === 1) {
-                    return getReturnTypeOfSignature(resolved.callSignatures[0]);
-                }
+        function getTypeFromJSAlias(node: NodeWithTypeArguments, symbol: Symbol): Type | undefined {
```
Comment (sandersn) [inline src/compiler/checker.ts]: new name for getJSDocTypeReference, reflecting its reduced responsibilities.
