### PR TITLE
Remove service's jsdoc parser and enhance parser's jsdoc parser

### LINKED ISSUE #6810: JsDoc optional params with [] syntax breaks JSDoc comments in signature help
The last two parameters below don't show the description in the signature help for that parameter, the first two do. It appears to be the `[name]` syntax that breaks this.

```javascript
/**
 * @param {string} p1 - A string param
 * @param {string?} p2 - An optional param 
 * @param {string} [p3] - Another optional param
 * @param {string} [p4="test"] - An optional param with a default value
 */
function f1(p1, p2, p3, p4){}
```

### LINKED ISSUE #6992: Optional parameter with jsdoc does not be respected by salsa intellisense
When I use jsdoc to create constructor the intellisense work well. Except a bug that it must obey parameter. It will not know type if the parameter is not all passed in. even it marked as optional by jsdoc

screen shot 2559-02-10 at 12 02 13 pm

As the screenshot. air is optional by jsdoc

screen shot 2559-02-10 at 11 56 43 am

this work but

screen shot 2559-02-10 at 11 54 19 am

not

### LINKED ISSUE #7136: Jsdoc tooltip showing raw tags
_From @madcampos on February 17, 2016 8:49_

The tooltip is showing all the jsdoc information except for the `@param` tags.
Eg. jsdoc:
```javascript
/**
 * Filters a path based on a regexp or glob pattern.
 * @param {String} basePath The base path where the search will be performed.
 * @param {String} pattern A string defining a regexp of a glob pattern.
 * @param {String} type The search pattern type, can be a regexp or a glob.
 * @param {Object} options A object containing options to the search.
 * @return {Array} A list containing the filtered paths.
 */
function pathFilter(basePath, pattern, type, options){
//...
}
```
The tooltip shows like this:
Tooltip

I'm using the january version without Salsa enabled.

_Copied from original issue: Microsoft/vscode#3073_

### LINKED ISSUE #7243: JSDoc @constructor shows up in IntelliSense
_From @chrisdias on February 24, 2016 22:46_

related to #3186?

Testing #3170 and the `@ constructor` JSDoc comment text shows up in the IntelliSense prompt. 

``` javascript
/**
 * Represents a person
 * @constructor
 * @param {string} name The name of the person
 * @param {number} age The age of the person
 */
function Person(name, age) {
    this.name = name;
    this.age = age;
}
var p = new Person
```

image

image

_Copied from original issue: Microsoft/vscode#3432_

### LINKED ISSUE #9809: @template is not recognized as JSDoc token
tsc: 1.8.9, 2.0.0, and nightly

```ts
/**
 * Do some foo things
 * @template T A Foolish template
 */
function foo<T>(): void {
}

foo()
```

image

The `@template` should be recognized and not consider as part of summary/description.

Ref:
#1178

### LINKED ISSUE #9882: different type between the type declared in jsDoc and the actual type
**TypeScript Version:**  2.0.0 beta

**Code**

```ts
/**
 * @type {{ [name: string]: string; }} variables
 */
const variables = {};
```

**Expected behavior:**
from VSCode(hover the variable), the type of the `variables` is `{ [name: string]: string; }`
**Actual behavior:** 
from VSCode(hover the variable), the type of the `variables` is `{}[]`

Seems the feature is powered bu salsa from typescript, so commit this here.

### LINKED ISSUE #9971: JSDoc syntax for optional parameter causes description to disappear from intellisense
**TypeScript Version:**  within VS Code 1.3.1

JSDoc syntax for optional parameters (e.g. `{number} [parameterName] Description`) seems to cause the parameter description to not get picked up for intellisense.

Closure Compiler syntax (e.g. `{number=} parameterName Description`) does not cause the same problem.

**Code**

```js
/**
 * @param {number} [x] Description
 */
function foo (x) { }
```

**Expected behavior:**

Hovering over `x` in the function declaration shows "Description", like this:

description-for-required-parameter

**Actual behavior:** 

no-description-for-optional-parameter

### LINKED ISSUE #10535: Salsa does not recognize JSDoc parameter properties in object literal format on multiple lines
When calling a function with object parameters documented with JSDoc, Visual Studio Code will not give intellisense completions if the parameter was documented using the object literal format with the comment broken up over multiple lines. 

This type of formatting allows for better readability when documenting objects with a lot of properties, so it would be helpful if this was supported.

**TypeScript Version:**  2.1.0-dev.20160824

**Code**

**Expected behavior:**

The properties of an object parameter should be recognized when it is documented using the JSDoc object literal @param syntax, even if the comment spans multiple lines.

**Actual behavior:** 

No properties of the object are recognized unless the JSDoc comment is only a single line.

### PR DESCRIPTION
**Pull request by sandersn**
Previously, the services code parsed the comment part of jsdoc and the parser parsed the type information of jsdoc. This change makes the parser parse both comments and type information from jsdoc. The parser now parses jsdoc for both TypeScript and JavaScript.

It doesn't add much coverage of other jsdoc tags, and it doesn't fix all the annoying architectural problems, but it closes almost all of the jsdoc bugs people have found so far:

Fixes #7136
Fixes #6810
Fixes #6992
Fixes #7243
Fixes #9809
Fixes #9882
Fixes #9971 
Fixes #10535

### CODE REVIEW

**Comment by sandersn** [comment]
@RyanCavanaugh you may be interested in this change if you like parsers (because I improved one), or if you don't (because I got rid of another one).

**Comment by sandersn** [comment]
@yuit you said you wanted to read parser code for some reason, so here it is. :] :gift:

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -6178,76 +6168,133 @@ namespace ts {
...
-                        let canParseTag = true;
-                        let seenAsterisk = true;
+                // + 3 for leading /**, - 5 in total for /** */
+                scanner.scanRange(start + 3, length - 5, () => {
+                    // Initially we can parse out a tag.  We also have seen a starting asterisk.
+                    // This is so that /** * @type */ doesn't parse.
+                    let advanceToken = true;
+                    let state = JSDocState.SawAsterisk;
+                    let margin: number | undefined = undefined;
+                    let indent = start - Math.max(content.lastIndexOf("\n", start), 0) + 4;
```
Comment (sandersn) [inline src/compiler/parser.ts]: Oh. That part is embarassing. `4 === '/** '.length`, basically. I should add a comment like the one on line 6179
