### PR TITLE
Use project relative preference for declaration emit

### LINKED ISSUE #39117: With project references, some cross-package imports of inferred types are emitted with relative paths
**TypeScript Version:**  3.9.5 (also repros with nightly)

**Search Terms:** project references, declaration files, tsconfig paths, inferred types

**Code**

The repro requires a monorepo with project references plus `paths` in the tsconfig. Full repro with the problematic compiled output checked in here: https://github.com/ecraig12345/learn-a/tree/inferred-relative-imports (it's fairly minimal but may still include a few settings which turn out to be tangential to the issue, sorry)

Here's a summary...

`@fluentui/pkg2` depends on `@fluentui/pkg1`, and both live in the same monorepo under a `packages` folder.

[`pkg2`'s tsconfig](https://github.com/ecraig12345/learn-a/blob/inferred-relative-imports/packages/pkg2/tsconfig.json) has a project reference pointing to `pkg1`, and both build with `composite: true`.

They inherit from a [shared tsconfig](https://github.com/ecraig12345/learn-a/blob/inferred-relative-imports/tsconfig.json) which has a path config like this (to allow imports directly from the root of each package):
```
"baseUrl": ".",
"paths": {
  "@fluentui/*": ["packages/*/src"]
}
```

The problem comes when you have a file in one package ([`pkg2/src/index.ts`](https://github.com/ecraig12345/learn-a/blob/inferred-relative-imports/packages/pkg2/src/index.ts) in the repro) which has an implicit/inferred reference to a type from another local project-referenced package. 
```ts
import { IThings } from '@fluentui/pkg1';

export function fn4() { // inferred return type: IThings from pkg1
  const a: IThings = { thing1: { a: 'b' } };
  return a.thing1;
}
```
This inferred type need not be stated locally, but it will show up in the declaration file as an inline `import()`.

**Expected behavior:**

Compile each package with `tsc` (or in the repro, run `yarn build` from the root).

`pkg2`'s `index.d.ts` looks like this:
```ts
export declare function fn4(): import("@fluentui/pkg1").IThing;
```

**Actual behavior:**

[`pkg2`'s `index.d.ts`](https://github.com/ecraig12345/learn-a/blob/inferred-relative-imports/packages/pkg2/lib/src/index.d.ts) looks like this, which will break consumers:
```ts
export declare function fn4(): import("../../pkg1/src").IThing;
```

`pkg2/src/index.ts` output also adds an `src` folder under `lib`, which I wouldn't expect (`pkg2/lib/src/index.{js,d.ts}`), but this is probably unrelated.

Variants:
- Same behavior if `-b` is added to the build command.
- Same behavior if using `rootDir` instead of `include`, just different output directory structure.
- Same behavior if the config inheritance is removed and `paths` config is moved to each project.
- Without project references, you end up with a directory structure like this, which I also don't understand, but is not the same issue:
```
pkg2/
  lib/
    pkg1/src/<files>
    pkg2/src/<files>
```

**Playground Link:**  can't be shown on playground

**Related Issues:**  didn't see anything else quite like this

### LINKED ISSUE #42349: With project references, some cross-package imports of inferred types are emitted with relative paths
# Bug Report

Repro: https://github.com/eps1lon/ts-monorepo-type-import-paths

### 🔎 Search Terms

I was asked to open this as a new issue: https://github.com/microsoft/TypeScript/issues/39117#issuecomment-760470118

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

Unable to do this in the playground

### 💻 Code

See https://github.com/eps1lon/ts-monorepo-type-import-paths
```tsx
// ArrowLeft.tsx

import * as React from "react";
import { createSvgIcon } from "@material-ui/core/utils";

export default createSvgIcon(
  <path d="M15.41 16.59L10.83 12l4.58-4.59L14 6l-6 6 6 6 1.41-1.41z" />,
  "ArrowLeft"
);

// @material-ui/core/utils.d.ts

import * as React from "react";
import SvgIcon from "./SvgIcon";

export function createSvgIcon(
  path: React.ReactNode,
  displayName: string
): typeof SvgIcon;

// @material-ui/core/SvgIcon.d.ts

import * as React from "react";
import { StyledComponentProps } from "@material-ui/styles";

export interface SvgIconProps extends StyledComponentProps<"root"> {
  children?: React.ReactNode;
}

declare const SvgIcon: React.JSXElementConstructor<SvgIconProps>;
export default SvgIcon;

// @material-ui/styles/index.d.ts
export interface StyledComponentProps<ClassKey extends string> {
  classes?: Record<ClassKey, string>;
}
``` 

### 🙁 Actual behavior

Generated `ArrowLeft.d.ts`
```ts
import * as React from "react";
declare const _default: React.JSXElementConstructor<import("../../core/src/SvgIcon").SvgIconProps>;
export default _default;
//# sourceMappingURL=ArrowLeft.d.ts.map
```

### 🙂 Expected behavior

```ts
import * as React from "react";
declare const _default: React.JSXElementConstructor<import("@material-ui/core/SvgIcon").SvgIconProps>;
export default _default;
//# sourceMappingURL=ArrowLeft.d.ts.map
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #42349

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot test this
@typescript-bot user test this

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -191,7 +191,9 @@ namespace ts.moduleSpecifiers {
         }
 
         if (relativePreference === RelativePreference.ExternalNonRelative) {
-            const projectDirectory = host.getCurrentDirectory();
+            const projectDirectory = compilerOptions.configFilePath ?
```
Comment (sheetalkamat) [inline src/compiler/moduleSpecifiers.ts:194]: This change is so that it actually uses directory of tsconfig file and not random directory where tsc is invoked from. (eg in test added the current directory is "/")

**Review by andrewbranch — COMMENTED** [review]
I added `project-relative` as a way to use somewhat looser heuristics for auto-import paths than we do in the compiler generally, namely the existence of package.json files in source directories, which otherwise `tsc` would never care about unless node module resolution for a bare specifier resolved to that directory. Does #42224 not fully solve the issue? That is a much more _explainable_ fix, if nothing else, and seems to fit nicely with an existing ethos of reusing input nodes and paths elsewhere in the transformers/emitter.

**Comment by sheetalkamat** [comment]
It does solve the issue but only if file was imported in the file, not otherwise. This would give use better paths in declaration emit. interesting thing is it didn't break anything so i wonder if this is better behavior for those derived paths. may be it is better option if importing file is project reference redirect?

**Comment by robpalme** [comment]
> may be it is better option if importing file is project reference redirect?

Please try to avoid making declaration emit dependent on whether the source/destination crosses a boundary expressed specifically as a *project reference.*

Our higher-level tooling (think Lerna etc) constructs multi-project workspaces dynamically.  The workspace is just a list of packages you want to develop together live - and the user adds and removes packages frequently in the course of developing or debugging an issue.  Meaning a project might have no project references one minute (because it is being built in isolation and so only links to static/published declarations for dependencies via `"paths"`).  Then the next minute the user wants to experiment by adding another project to the workspace, and so the tooling injects a *project reference* into `tsconfig` (causing the parent project to now consume declarations generated live from the child project's source code).

It would be odd if this lightweight switching action resulted in different behavior in declaration emit.

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
@sheetalkamat is this obsolete now that https://github.com/microsoft/TypeScript/pull/42224 is in? Or is it worth continuing on? If so, is it ready for review? I couldn't tell from skimming the conversation.

**Comment by sheetalkamat** [comment]
I dont think this is absolete. There is #42349 which might need this so need to investigate further and add test before this is ready for review.

**Comment by sheetalkamat** [comment]
@andrewbranch @weswigham i think we should take this PR as this does help many scenarios.. Eg #42349 where there are no project references or `node_modules` involved .. its all path mapping. I think declaration emit to use non relative module specifier if project crosses boundary is good thing rather than always using relative path.
Please review and weigh in again.
Thanks
