### PR TITLE
Preserve the homomorphism of inlined mapped types in declaration emit

### LINKED ISSUE #46655: Declaration emit can change type semantics when inlining internal types
# Bug Report

This is a cut-down repro for an issue I encountered while fixing a bug in [rtti](https://github.com/yortus/rtti). What I saw was the same types behaving differently when consumed _inside_ this package (ie referencing the types directly in `src/`) vs in downstream deps (ie referencing the emitted `.d.ts` types in `dist/`). 

### 🔎 Search Terms

mapped type over union
mapped type over generic

### 🕗 Version & Regression Information

v4.4.4
v4.5 beta
v4.6 nightly (2 Nov 2021)

This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types / homomorphic mapped types

### ⏯ Playground Link

Can't demonstrate in a single playground file.

### 💻 Code

```ts
/// file: test.ts
import {mappedUnionWithExportedType, mappedUnionWithPrivateType} from './api';
const a = mappedUnionWithExportedType({foo: 42}, {bar: 'bar'}); // type is {foo: number} | {bar: number}
'foo' in a ? a.foo.toFixed : a.bar.padStart;                    // OK
const b = mappedUnionWithPrivateType({foo: 42}, {bar: 'bar'});  // type is {}
'foo' in b ? b.foo.toFixed : b.bar.padStart;
//             ^^^             ^^^                              // ERRORS: 'foo' and 'bar' don't exist on {}

/// file: api.ts
import {useExportedType, usePrivateType} from './internal';
export const mappedUnionWithExportedType = <T extends unknown[]>(...args: T) => useExportedType(...args);
export const mappedUnionWithPrivateType = <T extends unknown[]>(...args: T) => usePrivateType(...args);


/// file: internal.ts
export declare function useExportedType<T extends unknown[]>(...args: T): ExportedMapped<T[any]>;
export declare function usePrivateType<T extends unknown[]>(...args: T): PrivateMapped<T[any]>;

export type ExportedMapped<Obj> = {[K in keyof Obj]: Obj[K]};
type PrivateMapped<Obj> = {[K in keyof Obj]: Obj[K]};
```

### 🙁 Actual behavior

As shown in `test.ts` above, declaration emit type semantics change depending on whether an internal type is marked with `export` or not. In the above example, the declarations emitted for `api.d.ts` are:

```ts
export declare const mappedUnionWithExportedType: <T extends unknown[]>(...args: T) => import("./internal").ExportedMapped<T[any]>;
export declare const mappedUnionWithPrivateType: <T extends unknown[]>(...args: T) => { [K in keyof T[any]]: T[any][K]; };
```

### 🙂 Expected behavior

Mapping over a union type seems silly to begin with (indeed that was the rtti bug I was fixing), but regardless of that, I would expect declaration emit semantics to be preserved whether or not `tsc` preserves an internal type in the emit, or expands it directly into a type expression.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #46655 - declaration emit now preserves the homomorphism of mapped types by emitting a conditional type with an `infer` type parameter when needed. So instead of, eg, `{ [K in keyof T[any]]: T[any][K]; }` we now emit `T[any] extends infer T_1 ? { [K in keyof T_1]: T[any][K]; } : never`.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5079,10 +5079,16 @@ namespace ts {
...
                     let appropriateConstraintTypeNode: TypeNode;
+                    let newTypeVariable: TypeReferenceNode | undefined;
                     if (isMappedTypeWithKeyofConstraintDeclaration(type)) {
                         // We have a { [P in keyof T]: X }
                         // We do this to ensure we retain the toplevel keyof-ness of the type which may be lost due to keyof distribution during `getConstraintTypeFromMappedType`
-                        appropriateConstraintTypeNode = factory.createTypeOperatorNode(SyntaxKind.KeyOfKeyword, typeToTypeNodeHelper(getModifiersTypeFromMappedType(type), context));
+                        if (!(getModifiersTypeFromMappedType(type).flags & TypeFlags.TypeParameter) && context.flags & NodeBuilderFlags.GenerateNamesForShadowedTypeParams) {
+                            const newParam = createTypeParameter(createSymbol(SymbolFlags.TypeParameter, "T" as __String));
+                            const name = typeParameterToName(newParam, context);
```
Comment (sandersn) [inline src/compiler/checker.ts:5088]: how does this end up with the name `T_1` instead of `T`? (I think `T` could conflict with names in `type`, so it's a good thing that the renaming happens, I just don't understand how when it's hard-coded as `"T" as __String`.)

**Review by sandersn — CHANGES_REQUESTED** [review]
Couple of background questions, plus a couple of high-level comments:

1. I think this is a good approach. Are there others you thought of?
2. How often will this apply to mapped types? Are nearly all of them both homomorphic and inlined? Does inlining only happen when a private type is used in an exported type?

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:5088]: `typeParameterToName` when used when the node builder flag also checked here generates unique names for the parameters it generates. It's primarily used for generic signature instantiations, but it works fine for this, too.

**Comment by weswigham** [comment]
> I think this is a good approach. Are there others you thought of?

They key issue is that we need to emit a type parameter in the mapped type keyof position to preserve homomorphism. So something like inline type aliases may also be usable to generate similar emit, pending exact implementation. But this is where what's possible with existing type constructors.

> How often will this apply to mapped types? Are nearly all of them both homomorphic and inlined? Does inlining only happen when a private type is used in an exported type?

Any time we have a generic mapped type that would lose its homomorphism otherwise. Generally it requires inlining a private or otherwise unnammed type in a still-generic position, yes. The node builder flags check prevents us from applying the logic for quick info or error type printback, so it'll only print like this in declaration emit.

**Review by sandersn — APPROVED** [review]
