### PR TITLE
Add support to infer the quote style for import code fix

### LINKED ISSUE #13270: make the quote symbol configurable for import codefix
currently the import codefix uses double quotes for the module path string literal which makes our linter unhappy, i wish the choice of a quote was configurable

### PR DESCRIPTION
**Pull request by rbuckton**
This adds the ability to determine whether to use single or double quotes for new imports added via code fixes. When a new import is added, we scan the top-most statements of the source file for existing import or export declarations with module specifiers. We then use the quote style of the first one we find. If there are no existing imports in the file we fall back to using double quotes.

Fixes #13270

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -999,6 +999,7 @@ namespace ts {
     export interface StringLiteral extends LiteralExpression {
         kind: SyntaxKind.StringLiteral;
         /* @internal */ textSourceNode?: Identifier | StringLiteral | NumericLiteral; // Allows a StringLiteral to get its text from another node (used by transforms).
+        /* @internal */ singleQuote?: boolean;
```
Comment (amcasey) [inline src/compiler/types.ts]: Are backtick strings uninteresting?  Would it make sense to store a quote character?

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -435,6 +437,23 @@ namespace ts.codefix {
...
+                            case SyntaxKind.ImportDeclaration:
+                                return (<ImportDeclaration>node).moduleSpecifier;
+                            case SyntaxKind.ImportEqualsDeclaration:
+                                const moduleReference = (<ImportEqualsDeclaration>node).moduleReference;
+                                return moduleReference.kind === SyntaxKind.ExternalModuleReference ? moduleReference.expression : undefined;
+                            case SyntaxKind.ExportDeclaration:
+                                return (<ExportDeclaration>node).moduleSpecifier;
+                        }
+                    });
+                    if (firstModuleSpecifier && isStringLiteral(firstModuleSpecifier)) {
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Keep looking if it's not a string literal?

File: src/compiler/types.ts (hunk 1 above)
Comment (rbuckton) [inline src/compiler/types.ts]: A `StringLiteral` can't be quoted using backtick. If it is quoted using backtick in source, then it would be a `NoSubstitutionTemplateLiteral`

File: src/services/codefixes/importFixes.ts [hunk 3]
```diff
@@ -435,6 +437,23 @@ namespace ts.codefix {
...
+                        return sourceFile.text.charCodeAt(skipTrivia(sourceFile.text, firstModuleSpecifier.pos)) === CharacterCodes.singleQuote;
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Is `skipTrivia(sourceFile.text, firstModuleSpecifier.pos)` the same as `firstModuleSpecifier.getStart()`?

File: src/services/codefixes/importFixes.ts (hunk 2 above)
Comment (rbuckton) [inline src/services/codefixes/importFixes.ts]: Hmm. I did this check because we might parse an invalid module specifier but we treat it as a grammar error rather than a parse error.

File: src/services/codefixes/importFixes.ts (hunk 3 above)
Comment (rbuckton) [inline src/services/codefixes/importFixes.ts]: I suppose. I'm not generally used to working in services :)

File: tests/cases/fourslash/importNameCodeFixNewImportFile6.ts [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+
+// @Filename: module.ts
+//// export function f1() {}
+//// export var v1 = 5;
+
+// @Filename: module2.ts
+//// export var v2 = 6;
+
+verify.importFixAtPosition([
+`import { v2 } from './module2';
```
Comment (amcasey) [inline tests/cases/fourslash/importNameCodeFixNewImportFile6.ts]: Would it be interesting to add a pair of tests where two existing imports have different quote types and, in each case, the first one wins?

Comment (rbuckton) [inline tests/cases/fourslash/importNameCodeFixNewImportFile6.ts]: Sure

Comment (amcasey) [inline tests/cases/fourslash/importNameCodeFixNewImportFile6.ts]: Thanks!

**Comment by felixfbecker** [comment]
Does this also apply the `import` snippet suggestion? That currently always uses double quotes

**Comment by Maximaximum** [comment]
@felixfbecker indeed, the tooltip seems to always use the double quotes. Not a big problem, but I guess it would be nice to fix it too.
