### PR TITLE
fix(44738): build-eslint-rules failed after setup

### LINKED ISSUE #44738: `build-eslint-rules` failed after setup
# Bug Report

### 🕗 Version & Regression Information

- This is a crash

Clone and run yarn on main branch:

image

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #44738

### CODE REVIEW

File: scripts/eslint/rules/no-double-space.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export = createRule({
         };
 
         const isRegexLiteral = (node: TSESTree.Node | null): boolean => {
-            return !!(node && node.type === AST_NODE_TYPES.Literal && node.regex);
+            return !!(node && node.type === AST_NODE_TYPES.Literal && Object.prototype.hasOwnProperty.call(node, "regex"));
```
Comment (Kingwl) [inline scripts/eslint/rules/no-double-space.ts:33]: how about just use `in`.

Comment (a-tarasyuk) [reply scripts/eslint/rules/no-double-space.ts:33]: I think that in this case, we don't need to check the `regex` in the inheritance chain.

**Review by Kingwl — APPROVED** [review]
Okay. LGTM.
