### PR TITLE
Don't elide imports when transforming JS files

### LINKED ISSUE #48588: Used import elided from emit where source is JavaScript
# Bug Report

### 🔎 Search Terms
import elided javascript used detect unused 6133

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [elided imports](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit)
- I was unable to test this on prior versions because the Playground is only for TypeScript, not JavaScript that's supposed to just be copied through

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAZgzgFXNAvFUkD2MoEsC2YmATsABQDk8FAlANwBQG0CxArjDADYQDCmAO2DEAhgGNg-AXGFsJJJJChpm2PIRLkKAAVmceAejGDh44LUYEipdMiisO3PidETYxTPig69Toy7MKSw0bZigAbygpUwkAeQAjACsINwBfd09vXXZ9CH8hV2AAWjgxAAsIfBEDOEgxIIYIAA9rYChjaTbcAVxJALc0GDYBCVxBMgYoKfb+4AApAGVYgDkALijZhOS3AB8I1IAaKAMDYbGBWyUqgGsIOChmkUIeKDgqrh5iSemHXOjCqQydjyYhQda-Jz-MyA2QgxQQA7fKbwAAiEBg3V653W8HhxwMMBIUAAJpVBECRMBzngLmIRB9ugBzGZCZrABg0MH2HKQ2YAOihbnCSLwMDIqhwEJ4gr6nWBwCJAEIUGgqMNRoJaBERdN0GUPAB3SjLTBQABu9NwxO5jmlsxh8qJYBEcDgEGtCppvRlfIsItSIuIEGAbGIFylzgK0PJsIVxDIHRi8yWy3oDFSQA)

### 💻 Code

Suppose the following JavaScript calls a function defined in TypeScript:
caller.**j**s:
```js
import * as fs from 'fs';
import TruffleContract from '@truffle/contract'; //Runtime err: this line dropped when JS is copied
import { initContract } from './functions.js';
initContract({}, fs, TruffleContract);
console.log('TruffleContract is ', typeof TruffleContract, TruffleContract); //still 'unused'
```
In functions.ts:
```ts
type fsType = typeof import('fs');
type TruffleContractConstructorType = typeof import('@truffle/contract');
import type TruffleContract from '@truffle/contract';
import type { ContractObject } from '@truffle/contract-schema/spec';
export const initContract = function(
    contractJSON: ContractObject | {}, //union type makes example smaller
    TruffleContractConstructor : TruffleContractConstructorType,
    fsDefinition: fsType //for demonstration in calling context
) : TruffleContract.Contract {
    if(typeof TruffleContractConstructor !== 'function') {
        throw('No valid TruffleContractConstructor passed to initContract.');
    }
    return TruffleContractConstructor(contractJSON);
}
```
A subset of tsConfig.js:
```json
"compilerOptions": {
    "module": "ES2020",
    "moduleResolution": "node",
    "allowJs": true,
    "checkJs": false,
}
```
package.json has `"type":"module"` needed for other project requirements, so `require` is not available.  Changing the import syntax to
`import { TruffleContract } from '@truffle/contract';` causes TypeScript to maintain the import line but there is an (expected) runtime 
>SyntaxError: Named export 'TruffleContract' not found. The requested module '@truffle/contract' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from '@truffle/contract';
const { TruffleContract } = pkg;

That again requires manually re-inserting the import statement because TypeScript drops the line falsely asserting that it's not used even when it's used in an expression in the very next line, and it's undefined at runtime because the original syntax is the correct one to use. 

### 🙁 Actual behavior
The TruffleContract import is dropped from the JavaScript file as part of copying that into the target location, leading to a runtime error that TruffleContract is not defined in the expression where it is used.  Manually re-adding it to the copied JavaScript file after every transpilation avoids the runtime error.

### 🙂 Expected behavior

The documentation for [allowJs](https://www.typescriptlang.org/tsconfig#allowJs) does not give any indication that the TypeScript transpiler will break existing JavaScript, instead of just copying it through.  Instead, it says: 
>This flag can be used as a way to incrementally add TypeScript files into JS projects by allowing the .ts and .tsx files to live along-side existing JavaScript files.

The [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit) states that TypeScript "removes module imports that aren't used in any *expression.*"  This one is, so by the reasoning in the FAQ, it isn't being elided, but in practice, it is, breaking what used to be running code.

The workaround discussed there and [here](https://github.com/Microsoft/TypeScript/issues/9191#issuecomment-226260645) is to include a general import line, such as `import '@truffle/contract';` and while this does make it through to the target location, it doesn't overcome the runtime error. `require` is not available for use but the documentation indicates a single use of what's imported should suffice and there is one here.

Overall, the expected behavior is that the JavaScript file is copied directly with no alterations, and certainly no breaking changes.
More specifically, the expected behavior is that an import which is actually used (in this case, it is used for passing a module implementation as a parameter) is not removed.  In this case, TypeScript appears to be wrongly detecting that the import is unused (ts(6133)), as the 'unused import' formatting/warning shows up in the editor as well.  This incorrect 'unused' status detection even triggers when the imported module is used in e.g. a console.log statement on the very next line, by itself or with the `typeof` operator.

The implementation is not imported and used directly in functions.ts because different sources of implementations are used at runtime depending on factors which do not appear relevant to a minimal example.  This is not in Angular.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #48588.

The fix, as discussed in the [design meeting](https://github.com/microsoft/TypeScript/issues/49444), is to never elide imports when transforming JS files.

Note that this breaks some assumptions that were being made by further transforms, such as looking up only value symbols when finding whether an identifier was an import.

Also note: this change is when transforming *JS* files only. And it only updates our transforms to not eliding *imports*. Exports in JS files will still be elided as before.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this

File: tests/baselines/reference/elidedJSImport1.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
+//// [tests/cases/compiler/elidedJSImport1.ts] ////
+
+//// [caller.js]
+import * as fs from 'fs';
+import TruffleContract from '@truffle/contract'; // Runtime err: this import is elided in transform
```
Comment (gabritto) [inline tests/baselines/reference/elidedJSImport1.js:5]: This import used to be elided, but now it isn't.

File: tests/baselines/reference/elidedJSImport1.errors.txt [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+tests/cases/compiler/caller.js(4,60): error TS2708: Cannot use namespace 'TruffleContract' as a value.
+
+
+==== tests/cases/compiler/caller.js (4 errors) ====
+    import * as fs from 'fs';
+                        ~~~~
+!!! error TS2307: Cannot find module 'fs' or its corresponding type declarations.
+    import TruffleContract from '@truffle/contract'; // Runtime err: this import is elided in transform
+           ~~~~~~~~~~~~~~~
+!!! error TS18042: 'TruffleContract' is a type and cannot be imported in JavaScript files. Use 'import("@truffle/contract").TruffleContract' in a JSDoc type annotation.
```
Comment (gabritto) [inline tests/baselines/reference/elidedJSImport1.errors.txt:13]: Note that if `checkJs` is `true`, the user will still get the errors because we believe `TruffleContract` is a type and not a value.

File: tests/baselines/reference/allowImportClausesToMergeWithTypes.js [hunk 3]
```diff
@@ -45,7 +45,7 @@ b_1["default"];
 "use strict";
 exports.__esModule = true;
 var x = { x: "" };
-zzz;
+a_1["default"];
```
Comment (gabritto) [inline tests/baselines/reference/allowImportClausesToMergeWithTypes.js:48]: This change looks weird, but it is correct. However, there should be an `import a_1 = require("./a")` here, which is elided because of another bug: https://github.com/microsoft/TypeScript/issues/50455

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -1850,7 +1851,8 @@ namespace ts {
             isUse: boolean,
             excludeGlobals: boolean,
             getSpellingSuggestions: boolean,
-            lookup: typeof getSymbol): Symbol | undefined {
+            lookup: typeof getSymbol,
+            reportErrors = true): Symbol | undefined {
```
Comment (gabritto) [inline src/compiler/checker.ts:1855]: `resolveNameHelper` used to report errors even if `nameNotFoundMessage` was `undefined`. Since we now call `resolveNameHelper` in `getReferencedValueOrAliasSymbol` when skipping the cached resolved symbol, without this change we would get different number of pre-emit and post-emit reported errors, and they'd be useless/repeated errors anyways.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -43474,6 +43481,41 @@ namespace ts {
...
         }
 
+        /**
+         * Get either a value-meaning symbol or an alias symbol.
+         * Unlike `getReferencedValueSymbol`, if the cached resolved symbol is the unknown symbol,
+         * we call `resolveName` to find a symbol.
+         * This is because when caching the resolved symbol, we only consider value symbols, but here
+         * we want to also get an alias symbol if one exists.
+         */
+        function getReferencedSymbol(reference: Identifier, startInDeclarationContainer?: boolean): Symbol | undefined {
```
Comment (gabritto) [inline src/compiler/checker.ts:43491]: We need to call `resolveName` here when the resolved symbol is unknown (i.e. there's a cache miss), because the resolved symbol is cached by doing a call to `resolveName` that only looks for symbols that have a value meaning.
Since we stopped eliding imports in JS files, that means some of the import symbols we want to find won't have a value meaning, but we still want to find them anyways, e.g. imports of types. Since those are imports, they'll have an alias meaning, hence we call `resolveName` with value or alias meaning.

File: tests/cases/compiler/elidedJSImport2.ts [hunk 6]
```diff
@@ -0,0 +1,35 @@
+// @allowJs: true
+// @checkJs: false
+// @module: ES2022, commonjs
+// @moduleResolution: node16
+// @esModuleInterop: true
+// @isolatedModules: true
```
Comment (gabritto) [inline tests/cases/compiler/elidedJSImport2.ts:6]: I think those compiler options work ok with my current changes, but I am not sure. I also don't think any other compiler option could interact badly with this change, but I have limited knowledge of the many things that could go wrong with emit and imports, so please, let me know if there's something else I should be testing here.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -43474,6 +43481,31 @@ namespace ts {
...
+         * This is because when caching the resolved symbol, we only consider value symbols, but here
+         * we want to also get an alias symbol if one exists.
+         */
+        function getReferencedValueOrAliasSymbol(reference: Identifier): Symbol | undefined {
+            const resolvedSymbol = getNodeLinks(reference).resolvedSymbol;
+            if (resolvedSymbol && resolvedSymbol !== unknownSymbol) {
+                return resolvedSymbol;
+            }
+
+            return resolveName(
```
Comment (gabritto) [inline src/compiler/checker.ts:43497]: Since we're calling `resolveName` if the cache returns `unknownSymbol`, there could be a perf increase in emit time for JS files. I'm not sure if that is a big concern, or how to measure it, or even how to address it, so I'm looking for opinions here.

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
> Exports in JS files will still be elided as before.

Can you give an example of an export that would be elided?

**Comment by gabritto** [comment]
> > Exports in JS files will still be elided as before.
> 
> Can you give an example of an export that would be elided?

It's the same rule as for TS files, since we don't seem to distinguish between JS and TS when transforming. If there's an export for something that resolves to a symbol that doesn't have a value meaning, then we elide it. If you consider the example from the issue/in `elideJSImport.ts` test, if you have something like this:

```ts
// @Filename: caller.js
import * as fs from 'fs';
import TruffleContract from '@truffle/contract'; // TruffleContract resolves to a namespace only
console.log(fs);
console.log('TruffleContract is ', typeof TruffleContract, TruffleContract);
export { TruffleContract }; // This export will be elided
```

so the `TruffleContract` export will be elided since `TruffleContract` resolves to a namespace, i.e. no value meaning.

**Comment by andrewbranch** [comment]
I feel like the rationale that we applied for keeping the imports applies equally well to exports. Is it as simple as adding the `isInJsFile` condition in another transform function?

**Comment by gabritto** [comment]
> I feel like the rationale that we applied for keeping the imports applies equally well to exports. Is it as simple as adding the `isInJsFile` condition in another transform function?

No, I'd have to go and change some checker and transform functions that have the same assumption that symbols will have a value meaning. I'd rather do it in a different PR, if that's the case.
I've considered doing it, but I wasn't sure where to draw the line of "fix weird things we do when transforming JS because we treat it the same as TS".

**Comment by andrewbranch** [comment]
> I wasn't sure where to draw the line

I think the best we can do is come up with principles that define an explainable mental model. “No type-directed emit” is a good one, but unfortunately imports and exports break it. So I think “Really actually no type-directed emit for JS files,” or put another way, “never elide syntactically valid JS from JS files,” is a better strategy than drawing a distinction between imports and exports.

**Comment by gabritto** [comment]
> > I wasn't sure where to draw the line
> 
> I think the best we can do is come up with principles that define an explainable mental model. “No type-directed emit” is a good one, but unfortunately imports and exports break it. So I think “Really actually no type-directed emit for JS files,” or put another way, “never elide syntactically valid JS from JS files,” is a better strategy than drawing a distinction between imports and exports.

That makes sense, thanks. I'll work on the export elision problem in another PR. :)

**Review by andrewbranch — APPROVED** [review]
Looks good to me. Would like to run the `reportErrors` change by @weswigham before merging.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts:1855]: `resolveEntityName` already takes an `ignoreErrors` flag and is seemingly what we use to resolve type names elsewhere - it just passes an `undefined` `nameNotFoundMessage` in those cases. Instead of adding a new parameter that also needs to be passed in at the `resolveEntityName` and maybe other callsites, maybe checking the existing `nameNotFoundMessage` parameter in more places works?

Comment (gabritto) [reply src/compiler/checker.ts:1855]: Isn't the existing code in the checker somehow relying on the fact that we report some errors even when `nameNotFoundMessage` is `undefined`? I thought this was intentional and the check for an undefined `nameNotFoundMessage` just kept us from reporting some "not found" errors.

Comment (weswigham) [reply src/compiler/checker.ts:1855]: *probably* not. I'd change it and see if it breaks anything.

**Comment by gabritto** [comment]
@amcasey I'm interested in your opinions on this change because it affects emit perf.

**Review by weswigham — APPROVED** [review]

File: src/compiler/transformers/ts.ts [hunk 8]
```diff
@@ -2455,9 +2455,11 @@ namespace ts {
         }
 
         function shouldEmitAliasDeclaration(node: Node): boolean {
-            return compilerOptions.preserveValueImports
-                ? resolver.isValueAliasDeclaration(node)
-                : resolver.isReferencedAliasDeclaration(node);
+            return isInJSFile(node)
```
Comment (amcasey) [inline src/compiler/transformers/ts.ts:2458]: Is this just `||`?

File: src/compiler/checker.ts (hunk 5 above)
Comment (amcasey) [reply src/compiler/checker.ts:43491]: Could we know during cache construction whether we'll eventually want alias symbols?  Would that interfere with other cache consumers?

File: src/compiler/checker.ts (hunk 7 above)
Comment (amcasey) [reply src/compiler/checker.ts:43497]: Can this new call happen in any scenario that wasn't broken before your change?

Comment (amcasey) [reply src/compiler/checker.ts:43497]: If I understand the change correctly (dubious), it sounds like the worst case is a file containing only unused imports?  If so, could you make such a file with the top 100 npm packages and then measure before and after tsc time?

File: src/compiler/checker.ts (hunk 5 above)
Comment (gabritto) [reply src/compiler/checker.ts:43491]: For (1), I think maybe that could be done. We want aliases for every identifier that goes through a module transform, worst case we need it for every identifier that survived the type erasure transform. But for (2) I think we would need a different cache, because changing it to cache alias-meaning symbols would interfere with the way the checker uses this cache.

File: src/compiler/checker.ts (hunk 7 above)
Comment (gabritto) [reply src/compiler/checker.ts:43497]: Not unused imports, but identifiers that would resolve to unknown symbol in the cache before, which I think means identifiers that either don't have a value meaning (I guess in JS that would be imports we think refer to types), or identifiers that we couldn't resolve (i.e. imports we couldn't resolve).

By file with the top 100 npm packages do you mean a file that imports from the top 100 npm packages?

File: src/compiler/transformers/ts.ts (hunk 8 above)
Comment (gabritto) [reply src/compiler/transformers/ts.ts:2458]: yep, but I guess I wanted to keep using ternaries since that was already there. I'll try to fix.

File: src/compiler/checker.ts (hunk 5 above)
Comment (amcasey) [reply src/compiler/checker.ts:43491]: Probably not worth the extra complexity of maintaining another cache (conditional on no-emit?), especially before we measure a problem.

File: src/compiler/checker.ts (hunk 7 above)
Comment (amcasey) [reply src/compiler/checker.ts:43497]: > Not unused imports, but identifiers that would resolve to unknown symbol in the cache before, which I think means identifiers that either don't have a value meaning (I guess in JS that would be imports we think refer to types), or identifiers that we couldn't resolve (i.e. imports we couldn't resolve).

From your tests, it looks like you could just `typeof` each imported symbol?

> By file with the top 100 npm packages do you mean a file that imports from the top 100 npm packages?

Yes, that's what I meant.

Comment (amcasey) [reply src/compiler/checker.ts:43497]: @gabritto What does your thumbs-up above mean?  "No, it can't happen"?

**Comment by gabritto** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts (hunk 7 above)
Comment (gabritto) [reply src/compiler/checker.ts:43497]: Turns out I was wrong, and we hit the cache for unresolved imports. We don't hit the cache for unresolved identifiers.
