### PR TITLE
Fix JS-inferred rest parameters

### LINKED ISSUE #16139: Crash with JS function that uses arguments and returns an instance of itself
**TypeScript Version:**  next (`2.4.0-dev.20170530`)

**Code**
This function in a JavaScript file:
```js
function Foo() {
  arguments;
  return new Foo();
}
```
is causing a compiler crash:
```
C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:68480
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at checkNonNullExpression (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:39031:37)
    at resolveNewExpression (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:40336:34)
    at resolveSignature (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:40542:28)
    at getResolvedSignature (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:40572:26)
    at checkCallExpression (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:40599:29)
    at checkExpressionWorker (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:42069:28)
    at checkExpression (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:42021:42)
    at checkExpressionCached (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:41902:38)
    at C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:40961:32
    at traverse (C:\Users\redacted\ts-bug\node_modules\typescript\lib\typescript.js:7371:28)
```

If I remove or rename `arguments`, remove the return statement, or change `new Foo()` into something else, the file transpiles successfully.

**To quickly reproduce:**
```
mkdir ts-bug
cd ts-bug
npm init --yes
npm install typescript@next
cat >test.js # copy-paste below file

node test.js
```

test.js:
```js
var ts = require("typescript");
var fs = require("fs");

var program = `
function Foo() {
  arguments;
  return new Foo();
}
`;

var transpileOptions = {
  compilerOptions: {
    allowJs: true
  },
  fileName: "./foo.js"
};
ts.transpileModule(program, transpileOptions);

```

### PR DESCRIPTION
**Pull request by sandersn**
Create js-inferred rest parameters in `getSignatureOfDeclaration`. Previously they were created too late, in `resolveCall`, via mutation. The mutation of the signature caused bug #16139 because recursion detection in type checking didn't work.

The earlier addition of the synthetic rest parameters means that it gets used even more places, so I had to add another special case, in `symbolToParameterDeclaration`.

Fixes #16139

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6420,14 +6440,14 @@ namespace ts {
             }
         }
 
-        function containsArgumentsReference(declaration: FunctionLikeDeclaration): boolean {
+        function containsArgumentsReference(declaration: SignatureDeclaration): boolean {
```
Comment (rbuckton) [inline src/compiler/checker.ts]: Was there a specific need to change the type? Introducing the cast on line 6450 seems to indicate the original type here was correct.

Comment (sandersn) [inline src/compiler/checker.ts]: `containsArgumentReference` is only called once, and the caller did the cast before. Since the same assumption gets made in the same order either way, I moved it to shorten an overlong line.
