### PR TITLE
Error when property is specified more than once via a spread

### LINKED ISSUE #27355: Missing excess property error with spread
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Code**

```ts
function f(o: { a: number, b: number }): { a: number } {
    return { b: 0, ...o };
}
```

**Expected behavior:**

Error on `b`.

**Actual behavior:**

No error.

Broken by #26798.

**Related Issues:** #27166, #23340

### PR DESCRIPTION
**Pull request by sandersn**
Add an error when we can be certain that a property declaration in an object literal will be overwritten by a later spread in the same object literal.
Updated from #27645

Notably, we can't be certain when:

1. The spread element includes undefined in its type.
2. The property from the spread element includes undefined in its type.
3. strictNullChecks is off.

Also, duplicate property declarations in a property declaration *without* spreads is track

This PR currently has some cleanup and open questions:

1. Is the removal of JSX errors correct? I thought I could unify them, but instead the errors don't happen at all; the previous version of this PR in #27645 it turns out the spread error message isn't correct for JSX anyway, so probably the correct change is not to try to unify the messages.
2. I hate passing yet another flag into `getSpreadType`.
2. Need to see whether `?.` syntax applies in one place.

Edit: It's not just that strictNullChecks needs to be on -- the JSX errors are gone for some other reason.

Fixes #27355

### CODE REVIEW

**Comment by sandersn** [comment]
@andrewbranch Mind taking a look at this, especially with an eye on the JSX errors?

File: tests/cases/conformance/types/spread/spreadOverwritesPropertyStrict.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// @strict: true
+declare var ab: { a: number, b: number };
+declare var abq: { a: number, b?: number };
+var unused1 = { b: 1, ...ab } // error
+var unused2 = { ...ab, ...ab } // ok, overwritten error doesn't apply to spreads
+var unused3 = { b: 1, ...abq } // ok, abq might have b: undefined
```
Comment (andrewbranch) [inline tests/cases/conformance/types/spread/spreadOverwritesPropertyStrict.ts]: It would be nice to add

```ts
var unused4 = { ...ab, b: 1 };
var unused5 = { ...abq, b: 1 };
```

just so the scope of the new error is clear to someone reading this test (me) (these should not be errors, right?)

**Comment by weswigham** [comment]
> Is the removal of JSX errors correct? 

Definitely not - having a `children` explicit attribute and providing child elements is definitely an error.

**Comment by weswigham** [comment]
I would just not remove the extra JSX error - it's there because it's essentially like you wrote `{x: 12, x: 12}` which we'd normally flag in the binder under strict mode checks, and won;t be flagged by the spread logic because the parenting structure isn't the same as a real spread.

**Comment by sandersn** [comment]
I couldn't write code that produced the JSX error in my editor. It's not dependent on a particular version of React being installed is it? Maybe I was just using the wrong language service...

File: tests/baselines/reference/checkJsxChildrenProperty13.errors.txt [hunk 2]
```diff
@@ -1,33 +0,0 @@
...
-        b: string,
-        children: Button;
-    }
-    
-    class Button extends React.Component<ButtonProp, any> {
-        render() {
-            // Error children are specified twice
-            return (<InnerButton {...this.props} children="hi">
-                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-!!! error TS2710: 'children' are specified twice. The attribute named 'children' will be overwritten.
```
Comment (andrewbranch) [inline tests/baselines/reference/checkJsxChildrenProperty13.errors.txt]: It’s unclear what this test was supposed to be testing. `children` are actually specified three times: first in the spread, then in the named attribute, then in the JSX children. IMO, it should never be an error to overwrite a spread property with a named declaration (in JSX props _or_ object literals), but it would be quite reasonable to issue an error when a) a named declaration overwrites a named declaration, or b) a spread property overrides a named declaration (which is what this PR is about). And I’m counting JSX children (like the tag contents) as _named_, even though the name is implicit.

By way of example, here are the tests I think should probably exist at some point:

```ts
interface AnchorProps { href: string; children: string }
declare const props: AnchorProps;

const a1 = <a {...props} href="#" />; // ok: analgous to `p = { ...props, href: '#' }`
const a2 = <a {...props} children="Link" />; // ok: same as above
const a3 = <a {...props}>Link</a>; // ok: same as above

const a4 = <a href="#" {...props} />; // not ok (as of this PR): analgous to `p = { href: '#', ...props }`
const a5 = <a children="Link" {...props} />; // not ok: same as above

const a6 = <a children="Link">Link</a>; // I guess not ok, but kinda linty and unrelated to this PR
```

Comment (weswigham) [reply tests/baselines/reference/checkJsxChildrenProperty13.errors.txt]:
```
const a6 = <a children="Link">Link</a>; // I guess not ok, but kinda linty and unrelated to this PR
```
is the case the old error was mostly concerned with catching~

File: tests/cases/conformance/types/spread/spreadOverwritesPropertyStrict.ts (hunk 1 above)
Comment (sandersn) [reply tests/cases/conformance/types/spread/spreadOverwritesPropertyStrict.ts]: Yep, those are not errors. I added the cases.

File: tests/baselines/reference/checkJsxChildrenProperty13.errors.txt (hunk 2 above)
Comment (sandersn) [reply tests/baselines/reference/checkJsxChildrenProperty13.errors.txt]: Yeah, I just reverted the JSX changes since it's just going to hold up this PR to try to unify what appears to be an actually-quite-different-and-complex check.

File: src/compiler/diagnosticMessages.json [hunk 3]
```diff
@@ -2683,7 +2683,7 @@
         "category": "Error",
         "code": 2733
     },
-    "It is highly likely that you are missing a semicolon.": {
+    "Are you missing a semicolon?": {
```
Comment (andrewbranch) [inline src/compiler/diagnosticMessages.json]: “$20 says you’re missing a semicolon”

**Comment by sandersn** [comment]
Because the error reporting distributes across unions, this gives an extraneous error for types like `{ a } | {}`, which should really have `a` optional. I don't want to do a second pass over the properties for this error, but I'm not yet sure how to.
