### PR TITLE
Assertions in control flow analysis

### LINKED ISSUE #8655: Control flow based type narrowing for assert(...) calls
Now that TypeScript does [control flow based type analysis](https://github.com/Microsoft/TypeScript/pull/8010), and there is a [`never` type](https://github.com/Microsoft/TypeScript/pull/8652) in the works, is it possible to consider providing better type checking around `assert(...)` function calls that assert that a variable has a certain type at runtime? TL;DR example:

```ts
assert(typeof s is "string");
s.length; // s is narrowed to string here...
```

### Problem

Asserts are common in contract-based programming, but I've also been coming across this scenario regularly whilst traversing JavaScript ASTs based on the [Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) (I'm using babel to produce/traverse ASTs).

For example, consider the `MemberExpression`:

memberexpression

Note we can assume `property` is an `Identifier` if `computed===false`. This is what I'd like to write:

```ts
function foo(expr: MemberExprssion) {
	if (expr.computed) {
		// handle computed case
	}
	else {
		// since computed===false, we know property must be an Identifier
		assert(isIdentifier(expr.property));

		let name = expr.property.name;  // ERROR: name doesn't exist on Identifier|Expression
	}
}
```

Unfortunately that doesn't compile, because `expr.property` does not get narrowed after the `assert(...)` call.

To get the full benefit of control flow analysis currently, you have to expand the assert call inline:

```ts
...
else {
    if (!isIdentifier(expr.property)) {
        throw new AssertionError(`Expected property to be an Identifier`);
    }

    let name = expr.property.name;  // OK
}
...
```

While preparing the typings for [`babel-core`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/babel-core/babel-core.d.ts), [`babel-types`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/babel-types/babel-types.d.ts) and friends, I noticed that using asserts this way is the norm. `babel-types` actually provides an `assertXXX` method for every `isXXX` method. These `assertXXX` functions are really just type guards that signal via `return`/`throw` rather than `true`/`false`.
 

### Possible Solutions?

Not sure if it's feasible at all! But the new work on `never` in #8652 suggests a few possibilities.

#### Specific assertions: assertIsT(...)

```ts
// normal type guard
function isIdentifier(n: Node): n is Identifier {
	return n.type === 'Identifier';
}

// PROPOSED SYNTAX: assert type guard
function assertIdentifier(n: Node): n is Identifier | never {
	if (n.type !== 'Identifier') {
        throw new AssertionError(`Expected an Identifier`);
	}
}

```

The compiler would reason that if this assert call returns at all, then it can safely narrow the variable type in following code.

#### General assertions used with type guards: assert(isT(...))

The more general `assert(cond: boolean)` function would need a different approach and might not be feasible, but here's an idea: 

```ts

	// General case
	declare function assert(cond: boolean): void;

	// PROPOSED SYNTAX: Special overload for expressions of the form assert(isT(x))
	declare function assert<T>(guard: guard is T): void | never;

```

For that second `assert` overload to work, the compiler on seeing `assert(isT(x))` would have to somehow forward the `x is T` narrowing from the `isT(x)` expression to the `assert(...)` expression at compile-time.

Would be great if it also detected/handled things like `assert(typeof x == 'string')`.

Not sure if any of this would meet the cost/benefit bar, but it's just an idea.

### LINKED ISSUE #11572: CFA: control flow for `switch` is defeated by outer `if-else`
**TypeScript Version:**  nightly (2.1.0-dev.20161012)

**Code**

``` ts
enum E { A, B }

function f(e: E): number {
    switch (e) {
        case E.A: return 0
        case E.B: return 1
    }
}

function g(e: E): number {
    if (!true)
        return -1
    else
        switch (e) {
            case E.A: return 0
            case E.B: return 1
        }
}
```

**Expected behavior:**

Both functions succeed.

**Actual behavior:** 

`a.ts(10,19): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.`

If I remove the `else` keyword (which makes an equivalent program), it compiles without errors.

If I put an `e` access under the `switch`, I see `(parameter) e: never` on hover, so that part is working.

### LINKED ISSUE #12668: Exhaustiveness checking doesn't work with variables
**TypeScript Version:**  2.1.1

If you have exhaustiveness checking where a result is a return from a function it works.
But if result is assigning value to a variable exhaustiveness checking basically does nothing.

**Code**

```ts
interface Square { kind: "square"; size: number; }

interface Rectangle { kind: "rectangle"; width: number; height: number; }

interface Circle { kind: "circle"; radius: number; }

interface Triangle { kind: "triangle"; side: number; }

type Shape = Square | Rectangle | Circle | Triangle;

function area(s: Shape): number {
    let area;
    switch (s.kind) {
        case "square": area = s.size * s.size; break;
        case "rectangle": area = s.width * s.height; break;
        case "circle": area = Math.PI * s.radius * s.radius; break;
        case "triangle": area = Math.sqrt(3) / 4 * s.side * s.side; break;
        //default: area = -1; break;
    }
    //Error because area is number | undefined
    return area;
}

function areaWrapped(s: Shape): number {
    let area;
    area = (() => {
        switch (s.kind) {
            case "square": return s.size * s.size;
            case "rectangle": return s.width * s.height;
            case "circle": return Math.PI * s.radius * s.radius;
            case "triangle": return Math.sqrt(3) / 4 * s.side * s.side;
        }
    })();
    return area;
}
```

**Expected behavior:**

Function `area`: variable `aria` should be `number` because the check is exhaustive. 
Sidenotes:
1. If I uncomment `default` then `tsc` believes that check is exhaustive.
2. `areaWrapped` uses IIFE to achieve the same effect and it works.

**Actual behavior:**

Variable `area` is of type `number | undefined` while it can't be `undefined`.

### LINKED ISSUE #13241: switch on enum exhaustive for direct return but not for indirect return
**TypeScript Version:**  2.1.4 

**Code**

```ts
enum MyEnum {
	A,
	B
}

function thisGivesError(e: MyEnum): string {
	let s: string;
	switch (e) {
		case MyEnum.A: s = "it was A"; break;
		case MyEnum.B: s = "it was B"; break;
	}
	return s; // Variable 's' is used before being assigned
}

function good1(e: MyEnum): string {
	let s: string;
	switch (e) {
		case MyEnum.A: s = "it was A"; break;
		case MyEnum.B: s = "it was B"; break;
		default: s = "it was something else"; break;
	}
	return s; // ok
}

function good2(e: MyEnum): string {
	switch (e) {
		case MyEnum.A: return "it was A";
		case MyEnum.B: return "it was B";
	}
}

```

tsconfig.json:
```json
{
	"compilerOptions": {
		"alwaysStrict": true,
		"declaration": true,
		"forceConsistentCasingInFileNames": false,
		"inlineSourceMap": true,
		"inlineSources": true,
		"module": "commonjs",
		"noFallthroughCasesInSwitch": true,
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noLib": false,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"outDir": "./dist",
		"preserveConstEnums": true,
		"pretty": true,
		"removeComments": false,
		"strictNullChecks": true,
		"suppressImplicitAnyIndexErrors": true,
		"target": "es5"
	},
}
```

**Expected behavior:**

Compiles

**Actual behavior:**

In the first function, returns 'Variable s is used before being assigned'. On the one hand, the compiler knows that the switch statment is exhaustive (see both functions below) and on the other hand it doesn't know that therefore the variable is assigned.

Might be related to #12771

### LINKED ISSUE #18362: TS2454 after assigning a value from an exhaustive switch statement
**TypeScript Version:**  2.4.2

**Code**

```ts
enum Level {
  One,
  Two,
}

const doSomethingWithLevel = (level: Level) => {
  let next: Level;
  switch (level) {
    case Level.One:
      next = Level.Two;
      break;
    case Level.Two:
      next = Level.One;
      break;
  }
  return next; // <-- Error here
};
```

**Expected behavior:**
Since the switch statement is exhaustive over the enum, the compiler should correctly infer that `next` is always set and this works without error.

**Actual behavior:**
(16,10): error TS2454: Variable 'next' is used before being assigned.

Note: replacing the variable assignment with inline `return`s (e.g. `case Level.One: return Level.Two;`) appears to negate the problem in this instance, but that isn't an option in the code that this example was derived from since there's additional code that uses the value of `next`.

### LINKED ISSUE #20409: Problem with exhaustiveness check for tagged unions
**TypeScript Version:** 2.7.0-dev.20171202

**Code**

```ts
interface Square {
    kind: "square";
    size: number;
}

interface Circle {
    kind: "circle";
    radius: number;
}

type Shape = Square | Circle;

function withDefault(s1: Shape, s2: Shape): string {
    switch (s1.kind) {
        case "square":
            return "1";
        case "circle":
            switch (s2.kind) {
                case "square":
                    return "2";
                case "circle":
                    return "3";
                default:
                    return "never";
            }
    }
}

function withoutDefault(s1: Shape, s2: Shape): string {
    switch (s1.kind) {
        case "square":
            return "1";
        case "circle":
            switch (s2.kind) {
                case "square":
                    return "2";
                case "circle":
                    return "3";
            }
    }
}
```
run with `tsc  --strict`

**Expected behavior:**
Shape has two kinds only, there is no error with `withoutDefault`.

**Actual behavior:**
`error TS2366: Function lacks ending return statement and return type does not include 'undefined'.`

### LINKED ISSUE #20823: Definite assignment for exhaustive switch statements.
Consider the following code

```ts
function test4(value: 1 | 2) {
    let x: string;
    switch (value) {
    case 1: x = "one"; break;
    case 2: x = "two"; break;
    }
    return x; //There is no path through the switch so x is alwayes assigned here.
}
```
**Expected behavior:**
The code should type check under --strict

**Actual behavior:**
Definite assignment does not realize that the switch is exhaustive and that all paths assign to x, so we get an error.

Checked with 2143a3f439aea887b2078e21e7585e4fa712f5fa

### LINKED ISSUE #22470: Initializing `let` variables and exhaustiveness checking
```
let tagName;
switch (kind) {
  case ListKind.Ordered:
    tagName = 'ol';
    break;
  case ListKind.Unordered:
    tagName = 'ul';
    break;
  default:
    assertNever(kind);
}
```

* The inferred type of `tagName` is `string|undefined`, but should be `string`, AFAICT.
* Similarly: If I give `tagName` the type `string`, I get the error: “Variable 'tagName' is used before being assigned”.

### LINKED ISSUE #27388: enum exhaustiveness checking with --noImplicitReturns doesn't work for nested switches
**TypeScript Version:**  3.2.0-dev.20180927

**Search Terms:**

enum nested switch

**Code**

```ts
enum E {
  A = 'A', B = 'B', C = 'C'
};

function one(e: E): number {
  switch (e) {
    case E.A: return 1;
    case E.B: return 2;
    case E.C: return 3;
  }
}

function two(e: E, f: E): number {
  switch (e) {
  case E.A: return 1;
  case E.B: return 2;
  case E.C:
    switch (f!) {
    case E.A: return 31;
    case E.B: return 32;
    case E.C: return 33;
    }
  }
}
```

**Expected behavior:**

Successful compilation: if `one` is OK, then so is `two`.

**Actual behavior:**

```
flutterby:tmp ariels$ tsc --noImplicitReturns x.ts
x.ts:13:27 - error TS7030: Not all code paths return a value.

13 function two(e: E, f: E): number {
```

**Playground Link:**
https://www.typescriptlang.org/play/#src=enum%20E%20%7B%0D%0A%20%20A%20%3D%20'A'%2C%20B%20%3D%20'B'%2C%20C%20%3D%20'C'%0D%0A%7D%3B%0D%0A%0D%0Afunction%20one(e%3A%20E)%3A%20number%20%7B%0D%0A%20%20switch%20(e)%20%7B%0D%0A%20%20%20%20case%20E.A%3A%20return%201%3B%0D%0A%20%20%20%20case%20E.B%3A%20return%202%3B%0D%0A%20%20%20%20case%20E.C%3A%20return%203%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20two(e%3A%20E%2C%20f%3A%20E)%3A%20number%20%7B%0D%0A%20%20switch%20(e)%20%7B%0D%0A%20%20%20%20case%20E.A%3A%20return%201%3B%0D%0A%20%20%20%20case%20E.B%3A%20return%202%3B%0D%0A%20%20%20%20case%20E.C%3A%0D%0A%20%20%20%20%20%20switch%20(f!)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20E.A%3A%20return%2031%3B%0D%0A%20%20%20%20%20%20%20%20case%20E.B%3A%20return%2032%3B%0D%0A%20%20%20%20%20%20%20%20case%20E.C%3A%20return%2033%3B%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:** 

Possibly a simpler case of #23572

### LINKED ISSUE #27909: strictNullChecks false positive when all possible conditions have been defined
**TypeScript Version:**  `v3.1.3`

**Search Terms:**
strictNullChecks, switch, case, condition, if, variable is used before being assigned.

**Code**
```ts
const enum Test {
  A, B
}

function test(x: Test) {
  let bork: string;

  switch (x) {
    case Test.A: {
      bork = 'a';

      break;
    }

    case Test.B: {
      bork = 'b';

      break;
    }
  }
  
  return bork;
  //     ^^^^
  //     Variable 'bork' is used before being assigned.
}
```

**Expected behavior:**
No errors here.

TS should know about all possible checks. Right now we can get some kind of error: `Not all code paths return a value.` in cases when we didn't define all possible `case`s or when `default` has been omited.

**Actual behavior:**
We got an error `Variable is used before being assigned`. It also happens with `if-else-if` variant.

**Playground Link:**
[Click Me!](https://www.typescriptlang.org/play/index.html#src=const%20enum%20Test%20%7B%0D%0A%20%20A%2C%20B%0D%0A%7D%0D%0A%0D%0Afunction%20test(x%3A%20Test)%20%7B%0D%0A%20%20let%20bork%3A%20string%3B%0D%0A%0D%0A%20%20switch%20(x)%20%7B%0D%0A%20%20%20%20case%20Test.A%3A%20%7B%0D%0A%20%20%20%20%20%20bork%20%3D%20'a'%3B%0D%0A%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20case%20Test.B%3A%20%7B%0D%0A%20%20%20%20%20%20bork%20%3D%20'b'%3B%0D%0A%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%20%20%0D%0A%20%20return%20bork%3B%0D%0A%7D)

**Related Issues:** 
Possible related issue: #27239. But this one is out of the loop.

### LINKED ISSUE #30000: Always assigning to an un-initialized variable in an exhaustive switch
**TypeScript Version:** 3.4.0-dev.20190220

**Search Terms:**
switch case exhaustive assignment assign undefined TS2322

**Code**
Compile with the flags `--noImplicitReturns --noImplicitAny --strictNullChecks`

```ts
enum Test {
    A,
    B,
    C
}

// this example correctly understands that all possible values of t are handled
function foo(t: Test): number {
    switch (t) {
        case Test.A:
            return 1;
        case Test.B:
            return 2;
        case Test.C:
            return 3;
    }
}

// this should be identical to foo, since a is always assigned as the switch is exhaustive
function bar(t: Test): number {
    let a;
    switch (t) {
        case Test.A:
            a = 1;
        case Test.B:
            a = 2;
        case Test.C:
            a = 3;
    }
    return a; // I don't expect an error here
}
```

**Expected behavior:**
Code compiles with no errors. When `a` is returned in `bar`, its type is `number`. Typescript understands that an exhaustive switch with each case assigning to a type-inferred variable means that the variable's type is the union of each assigned value's type. I'd expect this to work because returns within an exhaustive switch are understood in a similar manner.

**Actual behavior:**
When `a` is returned in `bar`, its type is `number | undefined`
```
TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

**Playground Link:**
[link here](https://www.typescriptlang.org/play/#src=enum%20Test%20%7B%0D%0A%20%20%20%20A%2C%0D%0A%20%20%20%20B%2C%0D%0A%20%20%20%20C%0D%0A%7D%0D%0A%0D%0A%2F%2F%20this%20example%20correctly%20understands%20that%20all%20possible%20values%20of%20t%20are%20handled%0D%0Afunction%20foo(t%3A%20Test)%3A%20number%20%7B%0D%0A%20%20%20%20switch%20(t)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Test.A%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.B%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%202%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.C%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%203%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20this%20should%20be%20identical%20to%20foo%2C%20since%20a%20is%20always%20assigned%20as%20the%20switch%20is%20exhaustive%0D%0Afunction%20bar(t%3A%20Test)%3A%20number%20%7B%0D%0A%20%20%20%20let%20a%3B%0D%0A%20%20%20%20switch%20(t)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Test.A%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%201%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.B%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%202%3B%0D%0A%20%20%20%20%20%20%20%20case%20Test.C%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20a%20%3D%203%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20a%3B%20%2F%2F%20I%20don't%20expect%20an%20error%20here%0D%0A%7D)
Turn on `noImplicitReturns`, `noImplicitAny`, and `strictNullChecks`.

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/22470 (different, since the default doesn't assign)
- https://github.com/Microsoft/TypeScript/issues/18362 (this is pretty old, from TS 2.4.2. Since `foo` in my example works I think the closure reason might be invalid)

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we reflect the effects of calls to `assert(...)` functions and never-returning functions in control flow analysis. We also improve analysis of the effects of exhaustive switch statements, and report unreachable code errors for statements that follow calls to never-returning functions or exhaustive switch statements that return or throw in all cases.

The PR introduces a new `asserts` modifier that can be used in type predicates:

```ts
declare function assert(value: unknown): asserts value;
declare function assertIsArrayOfStrings(obj: unknown): asserts obj is string[];
declare function assertNonNull<T>(obj: T): asserts obj is NonNullable<T>;
```

An `asserts` return type predicate indicates that the function returns only when the assertion holds and otherwise throws an exception. Specifically, the `assert x` form indicates that the function returns only when `x` is truthy, and the `assert x is T` form indicates that the function returns only when `x` is of type `T`. An `asserts` return type predicate implies that the returned value is of type `void`, and there is no provision for returning values of other types.

The effects of calls to functions with `asserts` type predicates are reflected in control flow analysis. For example:

```ts
function f1(x: unknown) {
    assert(typeof x === "string");
    return x.length;  // x has type string here
}

function f2(x: unknown) {
    assertIsArrayOfStrings(x);
    return x[0].length;  // x has type string[] here
}

function f3(x: string | undefined) {
    assertNonNull(x);
    return x.length;  // x has type string here
}
```

From a control flow analysis perspective, a call to a function with an `asserts x` return type is equivalent to an `if` statement that throws when `x` is falsy. For example, the control flow of `f1` above is analyzed equivalently to

```ts
function f1(x: unknown) {
    if (!(typeof x === "string")) {
        throw ...;
    }
    return x.length;  // x has type string here
}
```

Similarly, a call to a function with an `asserts x is T` return type is equivalent to an `if` statement that throws when a call to a function with an `x is T` return type returns false. In other words, given

```ts
declare function isArrayOfStrings(obj: unknown): obj is string[];
```

the control flow of `f2` above is analyzed equivalently to

```ts
function f2(x: unknown) {
    if (!isArrayOfStrings(x)) {
        throw ...;
    }
    return x[0].length;  // x has type string[] here
}
```

Effectively, `assertIsArrayOfStrings(x)` is just shorthand for `assert(isArrayOfStrings(x))`.

In addition to support for `asserts`, we now reflect effects of calls to never-returning functions in control flow analysis.

```ts
function fail(message?: string): never {
    throw new Error(message);
}

function f3(x: string | undefined) {
    if (x === undefined) fail("undefined argument");
    x.length;  // Type narrowed to string
}

function f4(x: number): number {
    if (x >= 0) return x;
    fail("negative number");
}

function f5(x: number): number {
    if (x >= 0) return x;
    fail("negative number");
    x;  // Unreachable code error
}
```

Note that `f4` is considered to not have an implicit return that contributes `undefined` to the return value. Without the call to `fail` an error would have been reported.

A function call is analyzed as an assertion call or never-returning call when

* the call occurs as a top-level expression statement, and
* the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
* each identifier in the function name references an entity with an explicit type, and
* the function name resolves to a function type with an `asserts` return type or an explicit `never` return type annotation.

An entity is considered to have an explicit type when it is declared as a function, method, class or namespace, or as a variable, parameter or property with an explicit type annotation. (This particular rule exists so that control flow analysis of potential assertion calls doesn't circularly trigger further analysis.)

EDIT: Updated to include effects of calls to never-returning functions.

Fixes #8655.
Fixes #11572.
Fixes #12668.
Fixes #13241.
Fixes #18362.
Fixes #20409.
Fixes #20823.
Fixes #22470.
Fixes #27909.
Fixes #27388.
Fixes #30000.

### CODE REVIEW

**Comment by acutmore** [comment]
Really like this!

Curious if instead of ‘asserts x’ it was considered to special case ‘asserts x is true’? Might be easier for people to learn/read for the cost of more complexity in the compiler

**Comment by ahejlsberg** [comment]
> Curious if instead of `asserts x` it was considered to special case `asserts x is true`?

No, because the two are not equivalent. `asserts x` reflects the full effects of a logical expression when `x` is truthy, similar to an equivalent `if` statement. `assert x is true` simply narrows the type of a variable passed for `x`, similar to the effects of passing `x` to an equivalent user defined type predicate function.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by dragomirtitian** [comment]
@ahejlsberg Just curios, the official position when multiple such issues were raise was that adding all potential call expressions will grow the CF graph to much and thus it was not really feasible to add this feature. My question is what changed ? Was the reasoning flawed, other performance improvements now make this less of a perf concern this, or this is still experimental and could still be axed if performance does meet expected values ?

**Comment by acutmore** [comment]
Ah! So `asserts x` declares it’s checking ‘truthy' rather than ‘true’

```
declare function assert(x): asserts x;
declare const x: string | null;
assert(x);
x.length; // x narrowed to string
```

**Comment by ahejlsberg** [comment]
> Ah! So asserts x declares it’s checking ‘truthy' rather than ‘true’

It's not just that.

`asserts x` reflects the full effects of the logical expression passed as an argument. E.g. `assert(typeof x === "string" || typeof x === "number")` narrows `x` to `string | number` in the following statements.

`assert x is true` however *only* affects a variable passed as an argument, i.e. `assertIsTrue(x)` narrows `x` to type `true` in the following, but does not reflect the effects of a logical expression passed as an argument.

**Comment by ahejlsberg** [comment]
@dragomirtitian What changed? First realizing that the CFA node to AST node ratio is pretty low (about 10% for the compiler itself, for example), and further that we can restrict ourselves to only including top-level expression statement call nodes in the CFA graph. Again, using the compiler itself as an example, this PR only increases the number of CFA nodes by 7.5%. So, overall we're talking less than 1% of additional memory overhead. And execution time overhead is very low when CFA call nodes turn out to not be assertions.

The perf test bot numbers appear to confirm this. Less that 0.1% memory overhead and zero execution time overhead. If anything, I would actually have expected more impact.

I guess it's sometimes good to question conventional wisdom. Even when it's your own!

**Comment by acutmore** [comment]
> asserts x reflects the full effects of the logical expression passed as an argument.

This I understand :-). What I am doing a poor job of expressing was that in my mind the `reflection` is a detail of the call site, and theoretically a function that `asserts x is true` could be completely obviously to this. Though the more I think about this, the more I can see how that would involve a lot of complexity. As it would almost be similar to supporting something like this:

```ts
declare const x: string | number;
const isString = typeof x === 'string'; // isString: (false & x is number) | (true & x is string);

if (isString) {
    x; // x: string;
}
```

So I retract all I have said, and have fully joined the `asserts x` fanclub!

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1276,6 +1284,22 @@ namespace ts {
             activeLabels!.pop();
         }
 
+        function isDottedName(node: Expression): boolean {
```
Comment (ajafff) [inline src/compiler/binder.ts]: what's the difference to `isEntityNameExpression`?

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -1276,6 +1284,22 @@ namespace ts {
             activeLabels!.pop();
         }
 
+        function isDottedName(node: Expression): boolean {
+            return node.kind === SyntaxKind.Identifier || node.kind === SyntaxKind.PropertyAccessExpression && isDottedName((<PropertyAccessExpression>node).expression);
```
Comment (ajafff) [inline src/compiler/binder.ts]: Is there a reason not to include `this` and `super` in property access expressions?

File: src/compiler/parser.ts [hunk 3]
```diff
@@ -3225,6 +3228,16 @@ namespace ts {
             }
         }
 
+        function parseAssertsTypePredicate(): TypeNode {
+            const node = <TypePredicateNode>createNode(SyntaxKind.TypePredicate);
+            node.assertsModifier = parseExpectedToken(SyntaxKind.AssertsKeyword);
+            node.parameterName = parseIdentifier();
+            if (parseOptional(SyntaxKind.IsKeyword)) {
+                node.type = parseType();
```
Comment (ajafff) [inline src/compiler/parser.ts]: This makes this type of object polymorphic. Could you instead always assign the property and use `undefined` if there is no type?

File: src/compiler/parser.ts [hunk 4]
```diff
@@ -3225,6 +3228,16 @@ namespace ts {
             }
         }
 
+        function parseAssertsTypePredicate(): TypeNode {
+            const node = <TypePredicateNode>createNode(SyntaxKind.TypePredicate);
+            node.assertsModifier = parseExpectedToken(SyntaxKind.AssertsKeyword);
```
Comment (ajafff) [inline src/compiler/parser.ts]: adding this property here and not assigning it in `parseTypeOrTypePredicate` where regular `TypePredicate` nodes are constructed, create yet another hidden class that hinders optimization at runtime.
Either assign it last in this function or (even better) assign it in both functions in the same order

Comment (ajafff) [inline src/compiler/parser.ts]: Is there a possibility that there will be more modifiers in the future? If so, would it make sense to put this into `Node#modifiers`?

File: src/compiler/factory.ts [hunk 5]
```diff
@@ -667,17 +667,18 @@ namespace ts {
         return <KeywordTypeNode>createSynthesizedNode(kind);
     }
 
-    export function createTypePredicateNode(parameterName: Identifier | ThisTypeNode | string, type: TypeNode) {
+    export function createTypePredicateNode(assertsModifier: AssertsToken | undefined, parameterName: Identifier | ThisTypeNode | string, type: TypeNode | undefined) {
```
Comment (ajafff) [inline src/compiler/factory.ts]: this is a breaking API change.
typically there is a new overload added to maintain backwards compatibility. the old signature can be marked as deprecated right away and could be removed later.

**Comment by felixfbecker** [comment]
Love this as it would make input validation (even against something like a JSON schema) a lot less clunky!

What makes me think though: Have you thought about expressing this with return types instead?

```ts
assertString(value: unknown): value extends string ? void : never
```

Assertion functions are really just functions that throw errors in certain cases. A function returning `never` means it is always throwing. If a function returns `never` exactly when the input is a string (i.e. always throws when the input is a string), we know that after that call the value _must_ be a string.

The only thing a conditional `never` types cannot express is a manual type checking boolean expression:

```ts
assert(typeof x === 'string')
```

but I think that is actually a good thing. People should use specialized assertion functions, because they would throw an assertion error like
```
Expected type of value to be string, got number
```
instead of
```
Expected false to be true
```
which is not helpful. Plain `assert()` should always be avoided.

It also seems like `asserts` would not work with the popular `expect()` assertion style (used in Jest):

```ts
expect(someValue).toBeString()


function expect<T>(value: T): Matcher<T>
interface Matcher<T> {
  toBeString(): asserts ??? is string; // can't reference value here anymore
}
```

while that would work great with `never` return types:

```ts
function expect<T>(value: T): Matcher<T>
interface Matcher<T> {
  toBeString(): T extends string ? void : never;
}
```

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -16845,23 +16820,62 @@ namespace ts {
             return isLengthPushOrUnshift || isElementAssignment;
         }
 
-        function maybeTypePredicateCall(node: CallExpression) {
+        function isDeclarationWithExplicitTypeAnnotation(declaration: Declaration | undefined) {
```
Comment (ajafff) [inline src/compiler/checker.ts]: should this handle JSDoc as well?

File: src/compiler/binder.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/binder.ts]: Good catch! No difference, will change to use the existing function.

File: src/compiler/binder.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/binder.ts]: I *think* that would be okay, but I'll have to convince myself it can't trigger circularities in control flow analysis.

File: src/compiler/parser.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/parser.ts]: Yup

File: src/compiler/parser.ts (hunk 4 above)
Comment (ahejlsberg) [reply src/compiler/parser.ts]: Agreed

Comment (ahejlsberg) [reply src/compiler/parser.ts]: It's possible, but for now I'm going to keep it the way it is.

**Comment by treybrisbane** [comment]
It looks as though this can be used to track mutations, e.g.:

```ts
class Foo {
  constructor(public bar: boolean) {}

  setBar<T extends boolean>(newBar: T): asserts this is Foo & { bar: T } {
    this.bar = newBar;
  }
}

const Foo = new Foo(false);
// foo is Foo
foo.setBar(true);
// foo is Foo & { bar: true }
```

Or

```ts
type Foo = { bar: boolean };

function setBar<T extends boolean>(foo: Foo, newBar: T): asserts foo is Foo & { bar: T } {
  foo.bar = newBar;
}

const foo: Foo = { bar: false };
// foo is Foo
setBar(foo, true);
// foo is Foo & { bar: true }
```

Is this correct?

**Comment by j-f1** [comment]
Another advantage to using the `never` type instead as suggested above is that it would also add support for calling e.g. `process.exit` in a conditional to narrow the type.

**Comment by zenozen** [comment]
Really nice!

Maybe we could use “asserts false” to represent a function that does not return? (Throws exception) This could help a bunch of case like assertNever, or unimplemented? Or maybe just “assert x is never” works?

**Comment by krzkaczor** [comment]
@ahejlsberg I have a couple of questions:

1. Does it work with async assert as well? Ie. function resolving/rejecting a promise.
2. Does it work with assertions on `this`? I wonder if this can help implement linear types (related: https://github.com/microsoft/TypeScript/issues/16148). My dummy example:
```typescript
class Socket {
    public async open() asserts this is CloseableSocket {
        console.log("Opening...")
    }

    public async close() asserts this is OpenableSocket {
        console.log("Closing...")
    }
}

interface CloseableSocket{
    close() asserts this is OpenableSocket;
}

interface OpenableSocket{
    open() asserts this is CloseableSocket;
}
```
Now it would be impossible to call open on the already opened socket and close the already closed socket. This would be really cool to see!

**Comment by goodmind** [comment]
How to write `invariant` with it?

**Comment by jack-williams** [comment]
@treybrisbane Your second example works, but your first does not because `this` is not supported in an assert predicate (not sure if that is by-design). So you can track mutations, but this only really works for monotonic references.

@krzkaczor Pre-emptive apology for the pedantry, sorry. What you implement there is known as type-state. Linear (or affine) types are required to soundly implement type-state, but that code does not actually guarantee there is only one reference to a given object. That still looks like an interesting use of this PR though, and if you assume that the user is careful with their aliasing you might be able to add a lot of type-safety.

@felixfbecker

The syntax:
```
assertString(value: unknown): value extends string ? void : never
```
also relies on new concepts, specifically having an expression (identifier) appearing in the check-type of a conditional type. On the surface I think it looks familiar to existing ideas, but there may be a non-trivial amount of new concepts required to implement and explain that feature thoroughly.

 I think if you want meaningful assertion messages (which is definitely desirable), it could be written like:
```ts
function assertString(value: unknown): asserts value is string {
    if (typeof value !== "string") {
        throw "Expected 'string', got ${typeof value}";
    }
}
```

**Comment by felixfbecker** [comment]
@jack-williams sorry, updated my comment, what I meant was:
```ts
assertString<T>(value: T): T extends string ? void : never
```
which does not require any new concepts. In fact, I would argue, it is almost a bit unexpected that this does not work already, because the semantics of `never` would lead to this conclusion. TypeScript already infers the `never` type for functions that always throw, and flags unreachable code after the `throw` statement. One would think that the fact that the function returns `never` would also make TS flag code after a call of such function (but doesn't atm). Then by using conditional types we can intuitively model assertions.

**Comment by alexreardon** [comment]
This is needed to move `tiny-invariant` to typescript: https://github.com/alexreardon/tiny-invariant/issues/45

We also use `invariant` heavily for `react-beautiful-dnd`, so having this style of guard would making moving `rbd` over to Typescript much easier https://github.com/atlassian/react-beautiful-dnd/issues/982

**Comment by ahejlsberg** [comment]
@felixfbecker The difference between the two forms

```ts
assertString(value: unknown): asserts value extends string;
```
```ts
assertString<T>(value: T): T extends string ? void : never
```

is that that we cannot necessarily make conclusions about an argument passed for `value` from a type argument for `T`. For example, imagine a type argument was explicitly specified for `T`, or that multiple parameters reference `T`, or that `T` is only referenced in a composite type and not as a naked type parameter. In those it is not meaningful to make conclusions for `value` and we would need rules to exclude them. Which ultimately leads you to the current form.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this again to observe effects of including `this.xxx(...)` calls in control flow graph.

**Comment by felixfbecker** [comment]
@ahejlsberg do you have an example? I tried to reproduce what you mean in the [playground](https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAQwM6oKYCcoGUpYxgDmAPACoB8AFAG7IA2IGAXIuQJRvmIYAeUDGAAmqRKgJFiiAPyJacGMMRswGWtkQBvALAAoRIhjBE1KAE8ADhjgn6TDIgCEAXheIA5BMIkPHbfqGhlAAFlhwAO6eEeG+gYgAvvpJevrCGBAMyFiODBhQ8tkAjKogALYARtj6aJg4+D5kYOVVWDT0WEX+APTdiBBwWDnQDOaIahpYADS8k2MD6SjAgliIoTBiG4jgOcgQIcgVefppGVk5iHkFHQBMpZXVerXYeJIkpB6HEB7t2Tc9fTAcAKjAYkQwwhOenSmWyuXyhSwAGY2OAANZAiJgGroF4NKSkbxSX7IgHjYEoBhgiIQqEw87w67ZAAsbA8FW+OLqr0ahLexBJzLJNMpu2EYwxkSMUC8KHE-LpZzhlwRHQArKiwJKsVy8fy6Nk1WTQeDhDN1YgInAQAxlFV5Y0lis1iENvogA) but couldn't find a case that seemed wrong to me.

Is there any other path to supporting `expect()` assertions?

**Comment by shicks** [comment]
@krzkaczor My understanding is that type assertions only result in narrowing.  So even outside the issue about `this` not being available (i.e. you could factor these out to top-level functions), I think it would end up typed as `CloseableSocket & OpenableSocket`, which doesn't give the extra safety you're looking for from "deleting" the uncallable method.

@felixfbecker The `asserts` syntax also builds into it the restriction that assert calls must be at top level.  In particular, one might assume that `declare function assert<T>(x: T): T extends Truthy ? T : never;` could _also_ be used as `foo(assert(x))`, but as currently implemented, any given function can only be one or the other (i.e. either control-flow assertion *or* narrowed return type).  For what it's worth, Closure's goog.asserts.assert currently does double-duty here, though it's by no means required.

@ahejlsberg Given that this is new syntax, it should be safe to actually have the compiler check that an `asserts` function is called in a valid/checked way.  Is there a compelling reason not to?

In general, it shouldn't be necessary, since correctly analyzing it should 99% of the time cause code to pass that would otherwise have failed, but one can imagine a contrived situation like

```
declare function f<T>(x: T): T extends string ? string : number;
declare function assertString(x: unknown): asserts x is string;
declare const x: unknown;
assertString(x);
useNumber(f(x));
```

If the CFA fails to narrow on `assertString` then you miss the type error from useNumber.

**Comment by polmabri** [comment]
Absolutely cool feature, which replaces my hacky type guard implementations:

```ts
function isType(value: unknown): value is Type { ...}

const a: unknown = x
if (!isType(a)) throw new Error()
const b: Type = a
```

**Comment by osyrisrblx** [comment]
Would be super useful if this allows us to model functions that always error:
`function error(message: string): asserts never`

**Comment by weswigham** [comment]
> @felixfbecker The difference between the two forms

We _could_ choose to recognize
```ts
assertString<T>(value: T): typeof value extends string ? void : never
```
though, since that can be interpreted to tie back to the specific argument symbol, rather than just the type of that symbol (as it does today). It's essentially the same as `asserts value is string`, but allows for non-void returns.

**Comment by weswigham** [comment]
> Would be super useful if this allows us to model functions that always error

Technically that's already just
```ts
function error(message: string): never;
```
- we have a `Debug.fail` in our compile that already has such a signature. The downside today is that you need to `return` it for it to affect control flow - I imagine we could (maybe?) include plain never-returning functions in the control flow along with this change?

**Comment by osyrisrblx** [comment]
> The downside today is that you need to `return` it for it to affect control flow
Ah yes I knew about this trick! It's just a bit awkward.

> I imagine we could (maybe?) include plain never-returning functions in the control flow along with this change?
That would be great. 😄

**Comment by jdom** [comment]
This seems useful, but couldn't we expand this so that it's supported not just in return types? Effectively, what I'd like is something like what is discussed in #10421, so that we don't have to emit additional JavaScript when compiled (either by creating a dummy function so that we can use `asserts`, or just doing an old school type assertion (aka cast) by copying the value to a redundant scoped variable).

Something of the sort:
```
const value: Foo = fetchData();
if (this.treatAsBar) {
    // I want to temporarily treat value as if it's of the Bar type for some reason.
    // The following line should not emit any code, it's just typing information
    asserts (value as any) is Bar;
    // now treat `value` as Bar within this scope
    value.barProp = true;
}

// value is Foo once again in this scope
```

Of course that's just a convoluted example as a straw-man to gauge whether the `asserts` keyword would be appropriate here, but the referenced issue has more down-to-Earth scenarios, where the dev knows more about the type and wants to skip 10 type assertions in a row just to read/modify an object that they know should be treated as a different type.

**Comment by ahejlsberg** [comment]
> Would be super useful if this allows us to model functions that always error

Agreed. As @weswigham points out, we already have syntax for that (i.e. returning `never`), but we would need to add special reasoning in control flow analysis.

**Comment by ahejlsberg** [comment]
> Effectively, what I'd like is something like what is discussed in #10421

It definitely would be nice to be able to explicitly assert a control flow type for a variable instead of having to cast on each reference. You *can* get the same effect with a call to an `asserts` function, but of course that call ends up in the emitted code. Still, JavaScript VMs are pretty decent at reducing away the cost of calls to empty functions.

**Comment by shicks** [comment]
> > Would be super useful if this allows us to model functions that always error
> 
> Agreed. As @weswigham points out, we already have syntax for that (i.e. returning `never`), but we would need to add special reasoning in control flow analysis.

Shouldn't `asserts false` do this already?

> @ahejlsberg
> 
> > @felixfbecker The difference between the two forms
> 
> We _could_ choose to recognize
> 
> ```ts
> assertString<T>(value: T): typeof value extends string ? void : never
> ```
> 
> though, since that can be interpreted to tie back to the specific argument symbol, rather than just the type of that symbol (as it does today). It's essentially the same as `asserts value is string`, but allows for non-void returns (and a negation of the assertion, when you do `? never : void`).

Allowing non-void returns only invites misuse.  One of the primary assumptions was that the function call needed to be a statement, so there would be no way to use the result and still get the narrowing.

**Comment by ahejlsberg** [comment]
With latest commit we now reflect effects of calls to never-returning functions in control flow analysis.

```ts
function fail(message?: string): never {
    throw new Error(message);
}

function f1(x: string | undefined) {
    if (x === undefined) fail("undefined argument");
    x.length;  // Type narrowed to string
}

function f2(x: number): number {
    if (x >= 0) return x;
    fail("negative number");
    x;  // Type narrowed to never
}
```

Note that `f2` is considered to not have an implicit return that contributes `undefined` to the return value. Without the call to `fail` an error would have been reported.

A function call is considered to terminate flow of control when

* the call occurs as a top-level expression statement, and
* the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
* each identifier in the function name references an entity with an explicit type, and
* the function name resolves to a function type with an explicit `never` return type annotation.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this to observe effects of including calls with no arguments in control flow graph.

**Comment by xiaoxiangmoe** [comment]
@typescript-bot perf test this to observe effects of including calls with no arguments in control flow graph.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this to observe effects of making CFA nodes more monomorphic.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this with less aggressive monomorphism for CFA nodes, since the previous changes just increased memory usage without improving perf.

**Comment by xiaoxiangmoe** [comment]
What's the difference between `never` and bottom type?
Is it good for we write `never` in parameter's type?

**Comment by magnushiie** [comment]
Could this somehow be unified with #7481? It feels kind of the same thing, just in expression context rather than statement context.

**Comment by jack-williams** [comment]
While the behaivour is clearly specified in the PR notes, I wonder how many people are going to be bitten by missing annotations:
```ts
interface Foo<T extends number> {
    value: T;
    assertZero(): asserts this is Foo<0>;
}

function example<T extends number>(choice: boolean, left: Foo<T>, right: Foo<T>): 0 {
    const picked = choice ? left : right;
    picked.assertZero();
    return picked.value; // error, why?.
}
```

Is there anyway to help guide users to the right solution?
```ts
const picked: Foo<T> = choice ? left : right;
```
When checking a call expression is it easy (and cheap) the check whether the call returns an assertion predicate but the call is _not_ bound in the CFG? It might be nice to have some warning or lint rule that flags assertion calls with no effect.

**Comment by rbuckton** [comment]
We discussed in a design meeting the possibility of a function return type defining both an *assertion* as well as a regular return type. I may have a use case where we could leverage this.

We recently introduced stricter Generator type inference and the `Generator<T, TReturn, TNext>` type, which dramatically improves our ability to strongly type generator functions, however we still lack the ability to model a type for "generator trampolines" like `co` or `redux-saga`. This deficiency is due to the fact that we currently have no way to indicate that the return type of one call to `generator.next()` should flow into the argument type of a subsequenct call to `generator.next(value)`.

If we introduce the ability to apply both an assertion *and* a return type, then we get closer to solving this deficiency:

```ts
// initial state
interface Start<TReturn> {
    next<T>(): IteratorResult<T, TReturn>
        & asserts this is Resume<TResult, T>;
}

// subsequent state
interface Resume<TResult, TNext> {
    next<T>(next: TNext): IteratorResult<T, TReturn>
        & asserts this is Resume<TResult, T>;
}

function trampoline<TResult>(gen: Start<TResult>) {
    let result = gen.next<A>();
    // result is `IteratorResult<A, TResult>`
    // gen is `Resume<TResult, A>`
    while (!result.done) {
        // first time: result.value is `A` and `TNext` is `A`
        // second time: result.value is `B` and `TNext` is `B`
        result = gen.next<B>(result.value);
        // result is `IteratorResult<B, TResult>`
        // gen is `Resume<TResult, B>`
    }
    return result.value;
}

trampoline(function * () {
    let a: A = ...;
    let b: B = yield a;
});
```

For example, an async trampoline could be defined as follows:

```ts
type AwaiterResult<T, TReturn> =
    IteratorResult<PromiseLike<T> | T, PromiseLike<TReturn> | TReturn>;

interface AsyncStart<TReturn> {
    next<T>(): AwaiterResult<T, TReturn> & asserts this is AsyncResume<TReturn, T>;
}

interface AsyncResume<TReturn, TNext> {
    next<T>(value: TNext): AwaiterResult<T, TReturn> & asserts this is AsyncResume<TReturn, T>;
}

declare function co<TReturn>(gen: AsyncStart<TReturn>): Promise<TReturn>;

co(function* gen() {
    let x = yield Promise.resolve(1);
    // x is `number`

    let y = yield "hi";
    // y is `string`
});
```

**Comment by Jessidhia** [comment]
That almost seems like an obvious improvement in retrospect; not even with generators, but I remember having difficulty writing correct types for a pattern where a "self-modifying this" would have helped immensely.

**Comment by Igorbek** [comment]
@rbuckton I came here with the intention to write almost exactly what you did! :+1:

**Comment by shicks** [comment]
@rbuckton I see two big problems with that proposal. First, it's my understanding that one of the requirements to make this viable in the first place was that the CFA was only happening on top-level call expression statements. If the return value is consumed then the narrowing isn't going to happen (unless that assumption changed somewhere along the way)?

Second, while using narrowing in that way is clever (I initially really liked the idea), I don't think it's compatible with how the type system actually works. My understanding is that if you narrow `this` twice, the second one will stack on top of the first, rather than replace it.

I couldn't quite figure out what your generator example was doing (it seemed like some generics were missing).  But I put together [a more contrived example][1] with mutating state (manually throwing after a normal `is` check to simulate the `asserts` keyword).  Effectively,

```ts
interface Holder<T> {
    set<V>(v: V): asserts this is Holder<V>;
    get(): T;
}

declare const holder: Holder<unknown>;

holder.set(42);
const a: number = holder.get();

holder.set('x');
const b: string = holder.get();
const c: number = holder.get();
```

But what ends up happening is that `holder` ends up with the nonsense type `Holder<number> & Holder<string>` and because the signatures conflict, `get` ends up just returning `number`.  There's also problems with extra non-narrowed copies of the reference float around, etc.

Do you have solutions to these?

[1]: https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgBIHsA2ATaAeAFQD5kBvAKGSuQGcIw8A1IgCgDcAuZRgSi7AAWwGsmFosuKEyIBuStQDm9Fn2QE5AX3LlcCTHCgoE6EDTDIBE6Fww58AVxABrEOgDuIWduAxkLAISWdlAAdHRgLAAsAEw8PMiCUO7IAAxyxqbmcFwg9gC2AEbQyAC8FlahShE8cuQ+foEVYcoA5AAeLXEJAkluqekmZsgFXGZQoAql5cEhVSoDmcgIOflFUFNBkrPKNeRAA

**Comment by treybrisbane** [comment]
In contrast, a big potential win with @rbuckton 's suggestion is the ability to define order-dependent relationships between the type of the `yield`ed value and the type of the `yield` expression.

That is, instead of just being able to say
>When the `yield`ed value is a `Promise<T>`, the type of the `yield` expression is `T`
We can actually say things like
>When the _first_ `yield`ed value is a `Promise<T>`, the type of the `yield` expression is `T`
>When the _second_ `yield`ed value is a `Promise<Array<T> | T>`, the type of the `yield` expression is `Array<T>`

(I'd give code examples, but I'm currently on my phone)

**Comment by ztplz** [comment]
Great work~

**Comment by sethfowler** [comment]
> Second, while using narrowing in that way is clever (I initially really liked the idea), I don't think it's compatible with how the type system actually works. My understanding is that if you narrow `this` twice, the second one will stack on top of the first, rather than replace it.
> 
> (...)
>
> But what ends up happening is that `holder` ends up with the nonsense type `Holder<number> & Holder<string>` and because the signatures conflict, `get` ends up just returning `number`. 

I'd really like to see TypeScript support a pattern like the one @rbuckton proposed; this would essentially give us typestate. The problem you're pointing out here does seem to be the chief issue that still remains to be solved. Even if we can update the type of `this`, it's not enough if the only operation we can use is intersection. (i.e., we need more than type narrowing) We'd ideally want to be able to _set_ the type of `this`, discarding the previous type completely.

It doesn't seem like that's a capability that this PR gives us, which is a bit unfortunate because it's tantalizingly close to what we need. Perhaps we need a second variety of type predicate; `foo is exactly Bar`?

**Comment by xiaoxiangmoe** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -11134,7 +11121,7 @@ namespace ts {
                 case SyntaxKind.TypeReference:
                     return getTypeFromTypeReference(<TypeReferenceNode>node);
                 case SyntaxKind.TypePredicate:
-                    return booleanType;
+                    return (<TypePredicateNode>node).assertsModifier ? voidType : booleanType;
```
Comment (weswigham) [inline src/compiler/checker.ts]: I, too, would also still love to see a non-void returning `asserts` function. Having the shorthand for the `void`-returning common case is fine, but I do think there's plenty of uses (see: every other petitioner in this PR) for a "returning" assertion (especially if in the future we maybe bind them in expression positions). Syntax for that is 🚲 🏠 able all day long, though I definitely think there's some overlap with the intent of `typeof` when used within a conditional.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -14628,16 +14604,18 @@ namespace ts {
             if (!ignoreReturnTypes) {
                 const sourceTypePredicate = getTypePredicateOfSignature(source);
                 const targetTypePredicate = getTypePredicateOfSignature(target);
-                result &= sourceTypePredicate !== undefined || targetTypePredicate !== undefined
-                    ? compareTypePredicatesIdentical(sourceTypePredicate, targetTypePredicate, compareTypes)
-                    // If they're both type predicates their return types will both be `boolean`, so no need to compare those.
-                    : compareTypes(getReturnTypeOfSignature(source), getReturnTypeOfSignature(target));
+                result &= sourceTypePredicate || targetTypePredicate ?
+                    compareTypePredicatesIdentical(sourceTypePredicate, targetTypePredicate, compareTypes) :
```
Comment (weswigham) [inline src/compiler/checker.ts]: I see the team is split on ternary style (trailing punctuation vs leading). Should we enforce one via linter?

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -16871,23 +16848,60 @@ namespace ts {
...
+                (declaration as VariableDeclaration | ParameterDeclaration | PropertyDeclaration | PropertySignature).type);
+        }
+
+        function getExplicitTypeOfSymbol(symbol: Symbol) {
+            return symbol.flags & (SymbolFlags.Function | SymbolFlags.Method | SymbolFlags.Class | SymbolFlags.ValueModule) ||
+                symbol.flags & (SymbolFlags.Variable | SymbolFlags.Property) && isDeclarationWithExplicitTypeAnnotation(symbol.valueDeclaration) ?
+                getTypeOfSymbol(symbol) : undefined;
+        }
+
+        function getTypeOfDottedName(node: Expression) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: This.... deserves remarks on why we can't just call `checkPropertyAccessExpression` or even `checkExpression` (at a glace, `getTypeOfDottedName` in no way indicates that it's only looking up declared types and refraining from resolving anything else).

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -16871,23 +16848,60 @@ namespace ts {
             return isLengthPushOrUnshift || isElementAssignment;
         }
 
-        function maybeTypePredicateCall(node: CallExpression) {
-            const links = getNodeLinks(node);
-            if (links.maybeTypePredicate === undefined) {
-                links.maybeTypePredicate = getMaybeTypePredicate(node);
+        function isDeclarationWithExplicitTypeAnnotation(declaration: Declaration | undefined) {
+            return !!(declaration && (
```
Comment (weswigham) [inline src/compiler/checker.ts]: This should handle `jsdoc` declarations, which means checking for the jsdoc node kinds and using `getEffectiveTypeAnnotation`.

File: src/compiler/binder.ts [hunk 11]
```diff
@@ -1278,6 +1279,23 @@ namespace ts {
...
+        function isDottedName(node: Expression): boolean {
+            return node.kind === SyntaxKind.Identifier || node.kind === SyntaxKind.ThisKeyword ||
+                node.kind === SyntaxKind.PropertyAccessExpression && isDottedName((<PropertyAccessExpression>node).expression);
+        }
+
+        function bindExpressionStatement(node: ExpressionStatement): void {
+            bind(node.expression);
+            // A top level call expression with a dotted function name and at least one argument
+            // is potentially an assertion and is therefore included in the control flow.
+            if (node.expression.kind === SyntaxKind.CallExpression) {
```
Comment (weswigham) [inline src/compiler/binder.ts]: Before I forget: Even if we don't support them, we'll need tests for our behavior of:
* Assertion constructors (arguably reasonable to support, just because construction is just calling with a replaced return value, minimally in the context of callable constructors a la js functions, it should be tested)
* Assertion tagged templates (a tagged template is _actually_ just a call, but given a valid template type signature, the most you could say is something like `function html(text: TemplateStringsArray, holes: any[]): asserts holes[0] is Something` which is... interesting.)
* Assertion decorators (I don't even know what someone would expect here - asserting the type of the class your wrapping?)
* Assertion JSX tags (lolwut - jsx tags are fake calls, so at best you could assert something about one of the props you're passed in?)
* Getter/setter pairs with assertion predicates

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -17083,6 +17104,38 @@ namespace ts {
...
+                    const predicate = getTypePredicateOfSignature(signature);
+                    if (predicate && (predicate.kind === TypePredicateKind.AssertsThis || predicate.kind === TypePredicateKind.AssertsIdentifier)) {
+                        const flowType = getTypeAtFlowNode(flow.antecedent);
+                        const type = getTypeFromFlowType(flowType);
+                        const narrowedType = predicate.type ? narrowTypeByTypePredicate(type, predicate, flow.node, /*assumeTrue*/ true) :
+                            predicate.kind === TypePredicateKind.AssertsIdentifier ? narrowTypeByAssertion(type, flow.node.arguments[predicate.parameterIndex]) :
+                            type;
+                        return narrowedType === type ? flowType : createFlowType(narrowedType, isIncomplete(flowType));
+                    }
+                    if (getReturnTypeOfSignature(signature).flags & TypeFlags.Never) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: I feel like this is one of those changes that we kinda obviously _want_, and have always imagined it working this way, but might break people in the wild. We'll have to check. We could always opt-in to this new behavior if it turns out it's a problem with a different `never` variant as the return type (eg, `throws`), though ofc that increases complexity a bit.

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -16871,23 +16848,60 @@ namespace ts {
...
+                symbol.flags & (SymbolFlags.Variable | SymbolFlags.Property) && isDeclarationWithExplicitTypeAnnotation(symbol.valueDeclaration) ?
+                getTypeOfSymbol(symbol) : undefined;
+        }
+
+        function getTypeOfDottedName(node: Expression) {
+            // We require the dotted function name in an assertion expression to be comprised of identifiers
+            // that reference function, method, class or value module symbols; or variable, property or
+            // parameter symbols with declarations that have explicit type annotations. Such references are
+            // resolvable with no possibility of triggering circularities in control flow analysis.
+            switch (node.kind) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: We should consider handling `ParenthesizedExpression` (both in binding and here) - I can't justify why `(this).assert()` shouldn't assert, other than "just because". It also might be worth renaming to `getDeclaredTypeOfFlowReference` and mimicking the traversals we support in `isMatchingReference`, this way we can know that if we can detect it as a reference, we can assert on it. At least, that kind of consistency would be nice.

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -8452,12 +8456,8 @@ namespace ts {
             return isBracketed || !!typeExpression && typeExpression.type.kind === SyntaxKind.JSDocOptionalType;
         }
 
-        function createIdentifierTypePredicate(parameterName: string, parameterIndex: number, type: Type): IdentifierTypePredicate {
-            return { kind: TypePredicateKind.Identifier, parameterName, parameterIndex, type };
-        }
-
-        function createThisTypePredicate(type: Type): ThisTypePredicate {
-            return { kind: TypePredicateKind.This, type };
+        function createTypePredicate(kind: TypePredicateKind, parameterName: string | undefined, parameterIndex: number | undefined, type: Type | undefined): TypePredicate {
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: > I would much rather we just added a modifiers or isAssert field to the existing two kinds

I'm not opposed to the representation you suggest, but things aren't quite as simple as you imply. Specifically, an `asserts` predicate allows the type to be omitted, whereas a regular type predicate doesn't. So, for `asserts` predicates we want the `type` property to include `undefined`, but not for regular type predicates. That led me to the current representation which accurately represents all of the cases.

> None of these predicates have similar handling in anything other than storage

Not correct. There are several places that were simplified by having a uniform set of properties (i.e. having `parameterName` and `parameterIndex` properties always be present but possibly `undefined`). For example, we now have unified and simpler logic to compare type predicates, create predicates from union types, and instantiate type predicates. Previously all of those had separate, and more complex, code paths.

File: src/compiler/checker.ts (hunk 7 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: The case for non-void returning `asserts` functions is much less compelling and not part of the motivating scenarios. I don't want to go there in this PR.

File: src/compiler/checker.ts (hunk 8 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: In my original implementation of the compiler it was all consistently trailing punctuation and it still is in the majority of the code base. I'd prefer to just standardize on that.

File: src/compiler/checker.ts (hunk 9 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Agreed.

File: src/compiler/checker.ts (hunk 10 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, I suppose.

File: src/compiler/checker.ts (hunk 8 above)
Comment (rbuckton) [reply src/compiler/checker.ts]: I generally prefer to have trailing punctuation when there are multiple cases (similar to a switch), but leading punctuation when there is a single condition (like an if/else).

File: src/compiler/checker.ts (hunk 9 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Actually, there's already a comment to that effect, but I'll add some more wording.

Comment (weswigham) [reply src/compiler/checker.ts]: Preferably on the function jsdoc style, rather than in the body. At least named as-is, it's tempting to use elsewhere.

File: src/compiler/checker.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: > Specifically, an asserts predicate allows the type to be omitted, whereas a regular type predicate doesn't. 

On that note, don't you find it odd that
```
asserts Foo
```
and
```
this is Bar
```
share a representation and AST node when they have zero syntax in common? I feel like the shorthand probably shouldn't reuse the same AST structure (shorthand property declarations aren't just a different configuration of properties on a property declaration)... though it ultimately doesn't matter much.

File: src/compiler/checker.ts (hunk 13 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Agreed.

**Comment by sschultze** [comment]
I'm already using these improvements in my codebase and at least the `asserts` modifier works perfectly fine. Really like it.

However, effects of calls to never-returning functions don't always seem to be reflected correctly in control flow analysis. Example:

```typescript
function fail(): never {
  throw new Error();
}

function demo(): number {
  let n = getSomeRandomNumber();
  if (n < 10) {
    return n;
  } else {
    fail();
  }
}
```

In my opinion, this should compile because this function either returns a number or throws an error. Instead, I get a compiler error:

"error TS2366: Function lacks ending return statement and return type does not include 'undefined'."

**Comment by artalar** [comment]
Hi! Thanks for this new awesome feature!

Why you purpose that assert must return bool (if I right understood it)?
My experience with runtime contracts say that assertion must return passing value - it is very useful! Here example with [runtypes](https://github.com/pelotom/runtypes):

example

**Comment by shicks** [comment]
@artalar my understanding is that in order for this to be viable, the call needs to be the entire statement - the value cannot be used.  You can't get both a usable return value _and_ type narrowing because then every function call in the entire program would turn into a potential node in the control flow graph, whereas with this restriction, only "call statements" are.

**Comment by mheiber** [comment]
The following code errors on TS 3.5 and 3.6, but not on this branch:

```ts
declare const x: string | undefined;
const z: string = x;
```

**Comment by mheiber** [comment]
I noticed that with this PR it is not possible to have the return type be an intersection of a regular return value and a user-defined type assertion.

Being able to do such intersections would really help us in the following situation, where calling a specific method on an object changes its shape:

```ts
// adding a button to a container gives it a 'layout' property
const button = new Button();
button.layout; // error because we don't know if it is added to a container yet
if (shouldAdd) {
    container.addChild(button);
    button.layout; // ok because of the `Ensures` type (defined below)
}
else {
    button.layout; // error because control flow didn't hit anything that ensures `button.layout` defined
}

// definitions
class Component { /* ... */ }
class Container extends Component {
    children: Component[] = [];
    addChild<T extends Component>(child: T): this & Ensures<T is T & { layout: Layout }> {
        this.children.push(child)
    }
}
```

> I previously posted the example in [a comment](https://github.com/microsoft/TypeScript/issues/17760#issuecomment-498755410) on issue #17760.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this to see effects of `isReachableFlowNode` function.

**Comment by mheiber** [comment]
updated the [example](https://github.com/microsoft/TypeScript/pull/32695#issuecomment-531291309) of intersection a user-defined assertion with a normal type

**Comment by ahejlsberg** [comment]
The latest commits integrate analysis of exhaustive switch statements into the control flow analyzer. As a result, we now appropriately reflect the effects of exhaustive switch statements when they're nested in other statements, and we appropriately recognize variables as initialized when they're initialized in every path of exhustive switch statements.

```ts
function f1(x: 1 | 2, b: boolean) {
    if (b) {
        return 42;
    }
    else {
        switch (x) {
            case 1: return 10;
            case 2: return 20;
        }
    }
}

function f2(x: 1 | 2) {
    let z: number;
    switch (x) {
        case 1: z = 10; break;
        case 2: z = 20; break;
    }
    z;  // Considered definitely assigned here
}
```

Both functions above would previously generate control flow analysis related errors.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
With the latest commits, we behave the same whether code unreachability is deduced from grammatical analysis in the binder or type analysis in the checker.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot perf test this

**Comment by mheiber** [comment]
Would it be possible to add support for intersecting user-defined assertions with regular return values?

I gave an example here: https://github.com/microsoft/TypeScript/pull/32695#issuecomment-531291309

**Comment by shicks** [comment]
@mheiber In the current state of this PR, that is not reasonably feasible - flow calls are only created from "expression statements", so any return value cannot be used.  This restriction was put into place because adding additional nodes to the control flow graph is expensive, and it was found that only a small minority of function calls are expression statements (the number cited above is 10% based on tsc), so it only increased the control flow graph by 7.5% in that example.  We can therefore conclude that lifting the restriction would increase the graph by 75%, which is infeasible, since control flow analysis is certainly the lion's share of compilation time.

Given that this restriction is in place, I would argue that it's a very bad idea to have assertion functions serve this "double duty", where they return a value if called as a subexpression, but only perform narrowing when called as an expression statement.  It's too unexpected that `foo();` and `x = foo();` should behave differently.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 15]
```diff
@@ -23692,9 +23828,11 @@ namespace ts {
...
-                return false;
-            }
+            const links = getNodeLinks(node);
+            return links.isExhaustive !== undefined ? links.isExhaustive : (links.isExhaustive = computeExhaustiveSwitchStatement(node));
+        }
+
+        function computeExhaustiveSwitchStatement(node: SwitchStatement): boolean {
             if (node.expression.kind === SyntaxKind.TypeOfExpression) {
                 const operandType = getTypeOfExpression((node.expression as TypeOfExpression).expression);
                 // This cast is safe because the switch is possibly exhaustive and does not contain a default case, so there can be no undefined.
```
Comment (jack-williams) [inline src/compiler/checker.ts]: I wonder whether this needs addressing in any way. Previously `node.possiblyExhaustive` was only true when there was no default clause (plus other conditions). Now, we assume that every call to `isExhaustiveSwitchStatement` is guarded by `flow.clauseStart === flow.clauseEnd`, but if someone were to forget that the cast would no longer be safe. Maybe as a change?
```ts
function getSwitchClauseTypeOfWitnesses(switchStatement: SwitchStatement): (string | undefined)[];
function getSwitchClauseTypeOfWitnesses(switchStatement: SwitchStatement, retainDefault: false): string[];
function getSwitchClauseTypeOfWitnesses(switchStatement: SwitchStatement, retainDefault: boolean): (string | undefined)[];
function getSwitchClauseTypeOfWitnesses(switchStatement: SwitchStatement, retainDefault: boolean = true): (string | undefined)[] {
    const witnesses: (string | undefined)[] = [];
    for (const clause of switchStatement.caseBlock.clauses) {
        if (clause.kind === SyntaxKind.CaseClause) {
            if (clause.expression.kind === SyntaxKind.StringLiteral) {
                witnesses.push((clause.expression as StringLiteral).text);
                continue;
            }
            return emptyArray;
        }
        if (retainDefault) witnesses.push(/*explicitDefaultStatement*/ undefined);
    }
    return witnesses;
}
```

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by drew-gross** [comment]
I read about this feature in the release notes and was excited to adopt it into my codebase, but it doesn't actually seem to help with the most common pattern I have. Was this feature intended to prevent errors in this snippet?

```js
let alwaysThrow = (): never => {
    throw "always throw"
}

let whyNotOk = (a: string | number): undefined => {
    if (typeof a == 'string') alwaysThrow();
    a + 1;
    return undefined;
}

let ok = (a: string | number): undefined => {
    if (typeof a == 'string') return alwaysThrow();
    a + 1;
    return undefined;
}   
```
[plauground](https://www.typescriptlang.org/play/#code/DYUwLgBAhsDuUE8DOAVAFgJwPawgXggAoBKALggDsQA3EDfAPggG8BYAKAi4jExwgBEMeMh59YAjgF8OHUJFhoEAOSxgA8gGt8RKOSRgMASwoBzCAB9KAVwC2AIzpkI1igBMQAMxMg3jFhzcEEaeRGAIAA4gWKFQ+AQA5AbGZgnE0HCIqOIkANyB3HEA1BAAjPmc3Bjg1hgULu5ePm4VMuxy4BBY2gSEehDJJuZWFHaOGM6uHt5UfnhMbJVcIWGR0bHxEEmGQ2kQ1WC19cJZ6NiweQVcxWUVQQdHDdPNrdxAA)

**Comment by MicahZoltu** [comment]
@drew-gross It appears it doesn't work with functions in variables.  If you change your `alwaysThrow` to:
```typescript
function alwaysThrow(): never { throw new Error() }
```
Then it will check correctly.

**Comment by AlCalzone** [comment]
@drew-gross @MicahZoltu 
It works if you add a type annotation to the variable holding the function: [playground](
https://www.typescriptlang.org/play/#code/DYUwLgBAhsDuUE8DOAVAFgJwPawFwQAoBKCAXgD4IA7EANxAzMJIogG8BYAKAl4jEw4IAIhjxk-QbGHcAvt26hIsNAgByWMAHkA1kwJR8SMBgCWVAOYQAPtQCuAWwBGDIvjtUAJiABm5kJ5klJw8fKY+hGAIAA4gWBFQZKQQAOTGZpYpJGKIqFLEANzcfNAQANQQAIxFobwY4HYYVBAe3n40njXyXIrgEFh6yQZGJuZWtlSOLhhuLV6+-oGsISXhkTFxCUmp6WNZEPVgjc05yOjYsIXFfIkV1dd1DU1zbYtdfEA)

If I remember correctly, this is also mentioned in the PR and/or release notes.

**Comment by thealjey** [comment]
```ts
export function assertArray<T>(
  actual: T,
  message: string = "expected value to be an array"
): asserts actual is any[] {
  assert<T>(actual, isArray, message);
}
```

A type predicate's type must be assignable to its parameter's type.
  Type 'any[]' is not assignable to type 'T'.
    'any[]' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.

How can I assert that something is an array of any?

**Comment by acutmore** [comment]
@thealjey


```ts
export function assertArray(
  actual: any,
  message: string = "expected value to be an array"
): asserts actual is any[] {
  assert<any>(actual, isArray, message);
}
```

**Comment by thealjey** [comment]
@acutmore 
yes, like I said in my comment, it is because of the generic type
it does compile like that
but, it's like covering your eyes and pretending the problem does not exist
I'm just saying that this new feature, unlike what the documentation leads one to believe, is not up to par with the rest of the language when it comes to type inference

**Comment by zakm** [comment]
Is it possible to use these assertions when type checking plain javascript files?

**Comment by Bnaya** [comment]
@zakm 
```js
/**	
 * @template T	
 * @param {T} v	
 * @return {asserts v is NonNullable<T>}	
 */	
export function assertNonNull(v) {	
  if (v === undefined || v === null) {	
    throw new Error("assertNonNull");	
  }	
}
```

**Comment by Universal-Invariant** [comment]
I just started learning typescript and reading the documents from:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

It says: "These assertion signatures are very similar to writing type predicate signatures:"

and it begs the question if one can combine the assert with the predicate?

E.g., given:
function isString(val: any): val is string {
  return typeof val === "string";
}

function assertIsString(val: any): asserts val is string {
  if (typeof val !== "string") {
    throw new AssertionError("Not a string!");
  }
}

The natural thing is to generalize this in some way:

// Generic assertion function
function assert<T>(value: unknown, message: string = "Assertion failed"): asserts value is T {
  if (!predicate(value)) {
    throw new Error(message);
  }
}

But it would be nice if we didn't have to pass the predicate as an argument but use it's name as a special type:
assert<isString>(msg)

or possibly 

assertIs<String>(msg)

and the compiler does a few checks to determine if T has a predict with the same name and starting with "is" "backing it" and then uses that.

This would allow one to have to leverage using both guard predicates and assertion guards together in a convenient way.

Maybe there is already a way to achieve this?
