### PR TITLE
Issue correct errors for missing JSX closing tags

### LINKED ISSUE #6280: Improve error message when there is `input` is not closed in `tsx`
The case is: I copied something from `html` file to `tsx` file, there is some `input`s that are not closed(which is legal in html, but not in jsx):

```ts
let TestComponent = React.createClass({
    getInitialState: function() {
        return {
            name: ""
        };
    },
    render: function() {
        return (
            <div>
                <input type="text" name="name">
            </div>
        );
    },
});
```

When compiled, the error message is:

```
components/test.tsx(17,1): error TS17002: Expected corresponding JSX closing tag for 'div'.
```

The line number is wrong, and it's not `div` that is not closed. 

It is easy to find the error for this code, but it's hard to find which tags are not closed when there are too much code.

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #6280

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7938,31 +7938,12 @@ namespace ts {
...
-                tagNamesAreEquivalent((<QualifiedName>lhs).left, (<QualifiedName>rhs).left);
-        }
-
         function checkJsxElement(node: JsxElement) {
             // Check attributes
             checkJsxOpeningLikeElement(node.openingElement);
 
-            // Check that the closing tag matches
-            if (!tagNamesAreEquivalent(node.openingElement.tagName, node.closingElement.tagName)) {
-                error(node.closingElement, Diagnostics.Expected_corresponding_JSX_closing_tag_for_0, getTextOfNode(node.openingElement.tagName));
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I don't think this diagnostic is used anymore, so it needs to be removed.

Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: It's used on line 3525

Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: (in parser.ts)

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I deleted my comment, but yeah, I realized after.

File: tests/baselines/reference/jsxAndTypeAssertion.errors.txt [hunk 2]
```diff
@@ -1,14 +1,20 @@
...
 tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(13,36): error TS1005: '}' expected.
+tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(15,17): error TS17008: JSX element 'foo' has no corresponding closing tag.
 tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(15,45): error TS1005: '}' expected.
+tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(19,2): error TS17008: JSX element 'foo' has no corresponding closing tag.
+tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(19,8): error TS17008: JSX element 'foo' has no corresponding closing tag.
+tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(19,13): error TS17008: JSX element 'foo' has no corresponding closing tag.
 tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(22,1): error TS1005: ':' expected.
-tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(22,1): error TS17002: Expected corresponding JSX closing tag for 'any'.
-tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(22,1): error TS17002: Expected corresponding JSX closing tag for 'foo'.
+tests/cases/conformance/jsx/jsxAndTypeAssertion.tsx(22,1): error TS1005: '</' expected.
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/jsxAndTypeAssertion.errors.txt]: Is there any way to avoid reporting this in addition to the `'foo' has no corresponding closing tag.` message?

Comment (RyanCavanaugh) [inline tests/baselines/reference/jsxAndTypeAssertion.errors.txt]: I actually like getting both errors in this case because the two locations make clear what's going on -- that you have one more open tag than closing tag, and that the offending unclosed tag is at some other location. When you only give the first error, it makes it sound like you have the *wrong* closing tag somewhere else; when you only give the second error, you have no idea what tag needs closing.

Comment (DanielRosenwasser) [inline tests/baselines/reference/jsxAndTypeAssertion.errors.txt]: > When you only give the first error, it makes it sound like you have the wrong closing tag somewhere else

I'm not sure I agree, but I don't think this is such a big deal.

**Comment by DanielRosenwasser** [comment]
:+1:
