### PR TITLE
Discard union types before considering weak type checks on unit-like types

### LINKED ISSUE #50360: Investigate Regression in Compilers-Unions
Our perf dashboard has a \~230ms regression on the compilers-unions benchmark starting at 4e33e0eb6c0e3173dbed1d4a825965f44b2b9e09 introduced in #49865.

image

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
This change has us do less work when deciding whether to apply weak type checks on a union source. `isRelatedTo` comes back around when it hits a union type anyway, which meant that we were doing extra work, and can get effectively the same wins without ever possibly triggering subtype reduction/apparent type calculation (which would possibly be even more expensive).

But according to @andrewbranch, we were never even hitting the true side of this condition, so it is extremely surprising that the iteration added up that quickly. So as a follow-up, maybe it's worth considering other places where we might be doing similar work.

Fixes #50360

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test faster

**Comment by DanielRosenwasser** [comment]
Welp - that's kinda insane.

**Comment by andrewbranch** [comment]
I thought about this, but I’m not sure it’s actually desirable behavior. If we take a slight modification of my test case from #49865:

```ts
type LiteralsAndWeakTypes = 
  | 'A'
  | 'B'
  | { optional?: true }
  | { toLowerCase?(): string }
  | { toUpperCase?(): string, otherOptionalProp?: number };

declare let aOrB: 'A' | 'B';

const h = (arg: LiteralsAndWeakTypes) => {
    if (arg === aOrB) {
      arg; // ⬅️ excludes `{ optional?: true }`
    } else {
      arg;
    }
}
```

I’m pretty sure this change will break that. Not the end of the world, but there’s no non-performance reasons to exclude unions.

**Comment by andrewbranch** [comment]
Alright, well clearly I don’t know what I’m talking about

**Comment by DanielRosenwasser** [comment]
@andrewbranch I added the test case and validated that reverting the exclusion doesn't change them at all.

I don't think that there should be any differences. The only possible place where I think you would run into this is a hypothetical scenario where all apparent types of primitives are also weak - and in fact, [with `Boolean`, we specifically made that not the case](https://github.com/microsoft/TypeScript/pull/1400). Otherwise, the apparent members of a union will only be weak if all of its constituents are also weak - and we'll hit that case when we go back around and distribute on the source given how comparability works.

I may have missed something, but that's my current assessment of the situation.

**Comment by DanielRosenwasser** [comment]
Actually, I am confusing the source and the target side in that last comment - but regardless, we were going to come back around in `isRelatedTo` when distributing on each of the source types anyway.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18901,7 +18901,7 @@ namespace ts {
                         }
                     }
 
-                    const isPerformingCommonPropertyChecks = (relation !== comparableRelation || relation === comparableRelation && isLiteralType(source)) &&
+                    const isPerformingCommonPropertyChecks = (relation !== comparableRelation || !(source.flags & TypeFlags.Union) && isLiteralType(source)) &&
```
Comment (andrewbranch) [inline src/compiler/checker.ts:18904]: I think this is equivalent

```suggestion
                    const isPerformingCommonPropertyChecks = (relation !== comparableRelation || isUnitType(source)) &&
```

**Review by andrewbranch — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:18904]: Are enums unit types?

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:18904]: They are

https://github.com/microsoft/TypeScript/pull/51140#discussion_r993857211
