### PR TITLE
fix(55946): Errant case causes crash in switch/case snippet completions

### LINKED ISSUE #55946: Errant `case` causes crash in `switch`/`case` snippet completions
```ts
switch (Math.random() ? 123 : 456) {
     case "oops!":
     case$
}
```

Ensure you have snippet completions enabled and request completions at `$`.

Request completion entry details for the snippet completion `case 123...`

```
TypeError: Cannot destructure property 'entry' of 'getExhaustiveCaseSnippets(...)' as it is undefined.
    at Object.getCompletionEntryDetails (.../node_modules/typescript/lib/tsserver.js:158306:15)
    at Object.getCompletionEntryDetails2 [as getCompletionEntryDetails] (.../node_modules/typescript/lib/tsserver.js:144582:35)
    at .../node_modules/typescript/lib/tsserver.js:184151:43
    at mapDefined (.../node_modules/typescript/lib/tsserver.js:2668:22)
    at IpcIOSession.getCompletionEntryDetails (.../node_modules/typescript/lib/tsserver.js:184149:20)
    at completionEntryDetails (.../node_modules/typescript/lib/tsserver.js:182478:43)
    at .../node_modules/typescript/lib/tsserver.js:184857:69
    at IpcIOSession.executeWithRequestId (.../node_modules/typescript/lib/tsserver.js:184849:14)
    at IpcIOSession.executeCommand (.../node_modules/typescript/lib/tsserver.js:184857:29)
    at IpcIOSession.onMessage (.../node_modules/typescript/lib/tsserver.js:184899:51)
    at process.<anonymous> (.../node_modules/typescript/lib/tsserver.js:186480:14)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #55946

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -2824,16 +2824,18 @@ export function getCompletionEntryDetails(
...
                 preferences,
                 program.getCompilerOptions(),
                 host,
                 program,
                 /*formatContext*/ undefined,
-            )!;
-            if (importAdder.hasFixes()) {
+            );
+
+            if (snippets && snippets.importAdder.hasFixes()) {
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:2837]:
```suggestion
            if (snippets?.importAdder.hasFixes()) {
```
