### PR TITLE
Fix relative path completions when self package.json has typesVersions

### LINKED ISSUE #54674: Relative path completion does not work when `typesVersions` is specified
# Bug Report

### 🔎 Search Terms

relative, typesVersions, module, path, autocomplete, suggestion

### 🕗 Version & Regression Information

[Simplest Reproduce Repository](https://github.com/tjx666/ts-path-autocomplete)

### 💻 Code

project structure:

```txt
❯ tree .
.
├── README.md
├── node_modules
│   └── typescript -> .pnpm/typescript@4.8.4/node_modules/typescript
├── package.json
├── pnpm-lock.yaml
├── src
│   ├── add.ts
│   └── index.ts
└── tsconfig.json
```

`src/index.ts`:

```ts
import {} from './';
```

`package.json`:

```json
{
    "name": "ts-path-autocomplete",
    "typesVersions": {
        "*": {
            "*": [
                "./src/*"
            ]
        }
    },
    "devDependencies": {
        "typescript": "4.7.4"
    }
}
```

`tsconfig.json`:

```json
{
    "compilerOptions": {},
    "include": ["src/**/*.ts"]
}

```

### 🙁 Actual behavior

can't get `'./add'` suggestion from ts `4.8.4`.

image

### 🙂 Expected behavior

The suggestion list show `add` in ts `4.7.4`

image

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #54674

### CODE REVIEW

File: src/services/stringCompletions.ts [hunk 1]
```diff
@@ -598,7 +598,7 @@ function getCompletionEntriesForRelativeModules(literalValue: string, scriptDire
             compilerOptions.rootDirs, literalValue, scriptDirectory, extensionOptions, compilerOptions, host, scriptPath);
     }
     else {
-        return arrayFrom(getCompletionEntriesForDirectoryFragment(literalValue, scriptDirectory, extensionOptions, host, /*moduleSpecifierIsRelative*/ false, scriptPath).values());
+        return arrayFrom(getCompletionEntriesForDirectoryFragment(literalValue, scriptDirectory, extensionOptions, host, /*moduleSpecifierIsRelative*/ true, scriptPath).values());
```
Comment (andrewbranch) [inline src/services/stringCompletions.ts:601]: Literally the function we’re in is `getCompletionEntriesForRelativeModules` 😅

**Review by jakebailey — APPROVED** [review]
