### PR TITLE
fix(49719): Incorrect error 2301 when using ES standard class properties

### LINKED ISSUE #49719: Incorrect error 2301 when using ES standard class properties
As explained in https://github.com/Microsoft/TypeScript/issues/2548, the following code is not correct when `useDefineForClassFields: false`, the default for targets before ES2021, or when target <= ES2020.

```ts
const x = 1
class C {
    p = x
    constructor(x: string) { }
}
```

However, when `useDefineForClassFields: true` and target >= ES2021, there shouldn't be an error here.

Expected: No error 2301 on `private p = x`, and `p: number`
Actual: Error on `private p = x` and `p: any`

Edit: @fatcerberus pointed out that the error is only incorrect when `useDefineForClassFields: true` and target >= ES2021, because downlevel define for class fields still happens in the constructor.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49719

### CODE REVIEW

File: tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    p = x
+    constructor(x: string) { }
+}
+
+
+//// [classMemberInitializerScoping2.js]
+const x = 1;
+class C {
+    constructor(x) {
+        Object.defineProperty(this, "p", {
```
Comment (sandersn) [inline tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).js:13]: this still incorrectly refers to the outer `x` in the scope of the constructor's `x`, so target=es2017,usedefineforclassfields=true needs an error too

**Review by sandersn — CHANGES_REQUESTED** [review]
as @fatcerberus points out, target=es2017,usedefineforclassfields=true still needs to have the error

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2210,7 +2210,7 @@ m2: ${(this.mapper2 as unknown as DebugTypeMapper).__debugToString().split("\n")
             // 1. When result is undefined, after checking for a missing "this."
             // 2. When result is defined
             function checkAndReportErrorForInvalidInitializer() {
-                if (propertyWithInvalidInitializer && !(getEmitScriptTarget(compilerOptions) === ScriptTarget.ESNext && useDefineForClassFields)) {
+                if (propertyWithInvalidInitializer && !(useDefineForClassFields && getEmitScriptTarget(compilerOptions) >= ScriptTarget.ESNext)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:2213]: sorry, missed this earlier, but class fields shipped in es2022:

```suggestion
                if (propertyWithInvalidInitializer && !(useDefineForClassFields && getEmitScriptTarget(compilerOptions) >= ScriptTarget.ES2022)) {
```

**Review by sandersn — CHANGES_REQUESTED** [review]

**Review by sandersn — APPROVED** [review]
