### PR TITLE
Fix intersection inference

### LINKED ISSUE #18354: Merged type not inferred as a mapped type argument
**TypeScript Version:**  2.5.x, 2.6.0-dev.20170908

When passed as an argument, `T & U` evaluates to `T`, and the type `U` is discarded.
```ts
declare function f<T, Key extends keyof T>(obj: {[K in keyof T]: T[K]}, key: Key): T[Key];

declare const obj: { a: string } & { b: string };
f(obj, 'a');
f(obj, 'b'); // error
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=declare%20function%20f%3CT%2C%20Key%20extends%20keyof%20T%20%3E(obj%3A%20%7B%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%7D%2C%20key%3A%20Key)%3A%20T%5BKey%5D%3B%0D%0A%0D%0Adeclare%20const%20obj%3A%20%7B%20a%3A%20string%20%7D%20%26%20%7B%20b%3A%20string%20%7D%3B%0D%0Af(obj%2C%20'a')%3B%0D%0Af(obj%2C%20'b')%3B%0D%0A%0D%0Atype%20Fix%3CT%3E%20%3D%20%7B%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%7D%0D%0A%0D%0Adeclare%20const%20obj2%3A%20Fix%3C%7B%20a%3A%20string%20%7D%20%26%20%7B%20b%3A%20string%20%7D%3E%3B%0D%0Af(obj2%2C%20'a')%3B%0D%0Af(obj2%2C%20'b')%3B%0D%0A)

---
**Workarounds**

Specify the type arguments explicitly:
```ts
f<typeof obj, keyof typeof obj>(obj, 'b');
```

An identity type mapping can be used to create an intermediate type
```ts
type Fix<T> = {[P in keyof T]: T[P]}

declare const obj: Fix<{ a: string } & { b: string }>;
f(obj, 'a');
f(obj, 'b');

```

Related issue typed-ember/ember-typings#32

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #18354.

Verified that there are no changes to RWC baselines.

@RyanCavanaugh Would you mind giving the fourslash changes (related to JSX inference) a look? Best I can tell they are correct.

### CODE REVIEW

File: tests/cases/conformance/types/intersection/intersectionTypeInference2.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+declare function f<T>(x: { prop: T }): T;
+
+declare const a: { prop: string } & { prop: number };
+declare const b: { prop: string & number };
+
+f(a);  // string & number
```
Comment (DanielRosenwasser) [inline tests/cases/conformance/types/intersection/intersectionTypeInference2.ts]: Consider using more realistic types for this test given that we've already been thinking about removing uninhabitable types.

**Comment by jwbay** [comment]
Does this change affect or undo https://github.com/Microsoft/TypeScript/issues/14829#issuecomment-320754731 ?

**Comment by ahejlsberg** [comment]
@jwbay This PR has no effect on #14829.
