### PR TITLE
[Release-2.1] Fix declaration emit when using type parameters

### LINKED ISSUE #11855: Generated declarations file omits generic parameter when a recursive type is implied as the return value
**TypeScript Version:**  2.0.6

**Code**

**app.ts**

``` ts
type Foo<T> = {

    foo<U>(): Foo<U>
};

function foo() {

    return {} as Foo<number>;
}
```

**Expected behavior:**

**app.d.ts**

``` ts
declare type Foo<T> = {
    foo<U>(): Foo<U>;
};
declare function foo(): Foo<number>;
```

**Actual behavior:** 

``` ts
declare type Foo<T> = {
    foo<U>(): Foo<U>;
};
declare function foo(): {
    foo<U>(): Foo;
};
```

The generated declarations file cannot be referenced by other code because `Foo` is missing the generic parameter. Furthermore, hovering over function foo in app.ts shows the return value as the expanded type (i.e. shows the whole body of the declaration).

The workaround is to declare `Foo` as an interface or to annotate the return value for function foo.

### PR DESCRIPTION
**Pull request by yuit**
Fix #11855

### CODE REVIEW

File: tests/baselines/reference/declarationEmitTypeAliasWithTypeParameters6.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    return {};
+}
+
+
+//// [declarationEmitTypeAliasWithTypeParameters6.d.ts]
+declare type Foo<T, Y> = {
+    foo<U, J>(): Foo<U, J>;
+};
+declare type SubFoo<R, S> = Foo<S, R>;
+declare function foo(): Foo<number, string>;
```
Comment (mhegazy) [inline tests/baselines/reference/declarationEmitTypeAliasWithTypeParameters6.js]: this does not look right. this should be `Foo<string, number>`

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2180,54 +2180,105 @@ namespace ts {
                         writer.writeKeyword(!(globalFlags & TypeFormatFlags.WriteOwnNameForAnyLike) && isTypeAny(type)
                             ? "any"
                             : (<IntrinsicType>type).intrinsicName);
+                        return;
```
Comment (mhegazy) [inline src/compiler/checker.ts]: can you keep the `else if` for this change. it makes it easier to understand the extent of the change here.

**Comment by mhegazy** [comment]
@yuit can you please port this to master as well.
