### PR TITLE
fix(51170): Completing an unimplemented property overwrites rest of line

### LINKED ISSUE #51170: Completing an unimplemented property overwrites rest of line
*TS Template added by @mjbvz*

**TypeScript Version**: 4.9.0-dev.20221013
**Search Terms**
- suggest / suggestions
- compeltions
- replacementSpan

---

Another case is completing an unimplemented property:

Recording 2022-10-13 at 15 37 04

It's a good thing that this is happening, but not when there it content on the right.

_Originally posted by @Tyriar in https://github.com/microsoft/TypeScript/issues/51169#issuecomment-1278280222_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51170

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -764,7 +764,7 @@ namespace ts.Completions {
         if (preferences.includeCompletionsWithClassMemberSnippets &&
             preferences.includeCompletionsWithInsertText &&
             completionKind === CompletionKind.MemberLike &&
-            isClassLikeMemberCompletion(symbol, location)) {
+            isClassLikeMemberCompletion(symbol, location) && !hasInitializer(location.parent)) {
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:767]: Seems like you want something more like

```ts
location.parent.children().some(child => child.pos > location.end)
```

since you could lose a more-specific type annotation, or trivia. For example:

```ts
////interface I {
////    prop: string;
////}
////class C implements I {
////    public pr/**/: "foo" | "bar";
////}
```

**Review by gabritto — APPROVED** [review]

**Review by DanielRosenwasser — APPROVED** [review]
