### PR TITLE
fix(35069): Fix all missing imports inserts blank lines between imports

### LINKED ISSUE #35069: Fix all missing imports inserts blank lines between imports
From https://github.com/microsoft/vscode/issues/84335

**TypeScript Version:** 3.8.0-dev.20191112

**Search Terms:**
- fix all
- missing import / missing imports

**Repo**
1. `git clone https://github.com/mjbvz/ts-add-missing-fixall-bug`
1. Open `index.ts` in VS Code
1. Try using the `fix all missing imports` quick fix

**Expected behavior:**

```ts
import { a } from "./a";
import { b } from "./b";

console.log(a, b);
```

**Actual behavior:**
```ts
import { a } from "./a";

import { b } from "./b";

console.log(a, b);
```

```
[Trace  - 3:06:38 PM] <semantic> Response received: getCombinedCodeFix (12). Request took 3 ms. Success: true 
Result: {
    "changes": [
        {
            "fileName": "/Users/matb/projects/san/index.ts",
            "textChanges": [
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 1
                    },
                    "newText": "import { a } from \"./a\";\n\n"
                },
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 1
                    },
                    "newText": "import { b } from \"./b\";\n\n"
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #35069

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -101,7 +103,9 @@ namespace ts.codefix {
                     doAddExistingFix(changes, sourceFile, importClause, defaultImport, namedImports, canUseTypeOnlyImport);
                 });
                 newImports.forEach((imports, moduleSpecifier) => {
-                    addNewImports(changes, sourceFile, moduleSpecifier, quotePreference, imports);
+                    // Add blank line after last new import statement
+                    const blankLineBetween = lastModuleSpecifier === moduleSpecifier;
+                    addNewImports(changes, sourceFile, moduleSpecifier, quotePreference, imports, blankLineBetween);
```
Comment (sandersn) [inline src/services/codefixes/importFixes.ts]: I think this is clear enough, and shorter.

```suggestion
                    addNewImports(changes, sourceFile, moduleSpecifier, quotePreference, imports, /*blankLineBetween*/ lastModuleSpecifier === moduleSpecifier);
```

Comment (a-tarasyuk) [reply src/services/codefixes/importFixes.ts]: @sandersn Thanks for the feedback. Done.
