### PR TITLE
Optimize import fixes for projects with many symlinks

### LINKED ISSUE #40584: Typescript: TSServer: Code Fixes: Import missing imports with a symlinked node_modules folder is very slow
**TypeScript Version:** 3.9.7

PS: I am using Angular and therefor cannot try to use a later version of Typescript at this time.

**Search Terms:**
PNPM Typescript import slow

**System**
OS: Windows 10
Disk: SSD

**Expected behavior:**
When using PNPM or another packagemanager that uses a symlinked node_modules folder, the code Auto Import fixes like "Imports x from modules" and "import all missing imports" are performed within a reasonable delay. Preferably on par with NPM. With NPM as packagemanager, the code fixes "Imports x from modules" or "import all missing imports" are much faster.

**Actual behavior:**
The upgrade to Angular 10, also upgraded Typescript to version 3.9.7. In 3.9, support for code Auto Import fixes for imports from [symlinked node_modules folder](https://github.com/microsoft/TypeScript/issues/36104) were added.  

So I replaced npm with pnpm, and yes indeed, code Auto Imports fixes do function, however extremely slow.

In [PNPM TSServer.log](https://github.com/microsoft/TypeScript/files/5232159/TSServer.log), you can see I performed 2 actions

1. Import OnInit from @angular/core
In Visual Studio Code, the yellow lightblub appeared; I selected OnInit from @angular/core, the import statement was generated after approximately 
PNPM: **3 seconds**
NPM: **< 1 second**

PS: Also please note that with NPM, the Yellow Lightblub did not appear but the blue one did.

2. Import all missing imports
In Visual Studio Code, I selected a missing import and from the blue lightblub, I selected "Import all missing imports", the import statements were generated after approximately
PNPM: **51 seconds**
NPM: **2 seconds**

This is the [NPM TSServer.log](https://github.com/microsoft/TypeScript/files/5232365/TSServer.npm.log).

When doing each action, CPU was at 100%. cpu
.

**Related Issues:**

### PR DESCRIPTION
**Pull request by andrewbranch**
This is a separate follow-up to #42095, incorporating and building on @walkerburgin’s investigations. The main difference between this PR and @walkerburgin’s experiment (besides the inclusion of #42095) is that this tries directories from the imported filename to key into the realpath->symlink map instead of iterating through all entries of the map.

Fixes #40584

Forgot to share perf numbers. Scenario: private repo [shared here](https://github.com/microsoft/TypeScript/issues/40584#issuecomment-721405647). Opened file shown in screenshot. Restart TS Server with that file open. Move cursor to `OnInit` to trigger `getCodeFixes`. From fixes menu, choose “Add all missing imports” to trigger `getCombinedCodeFix`.

|  | updateOpen (ms) | getCodeFixes (ms) | getCombinedCodeFix (ms) |
|--|-------------:|---------------:|-----------------------:|
| **master pre-#42095 merge** | 5958 | 2235 | 70447 |
| **#42095** | 4796 | 890 | 24150 |
| **This PR** | 5865 | 258 | 5483 |

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@typescript-bot pack this

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -299,22 +300,24 @@ namespace ts.moduleSpecifiers {
...
-            if (resolved === false) return undefined;
-            if (startsWithDirectory(importingFileName, resolved.realPath, getCanonicalFileName)) {
-                return undefined; // Don't want to a package to globally import from itself
+        const symlinkedDirectories = links.getSymlinkedDirectoriesByRealpath();
+        const result = symlinkedDirectories && forEachAncestorDirectory(getDirectoryPath(importedPath), realPathDirectory => {
+            const symlinkDirectories = symlinkedDirectories.get(ensureTrailingDirectorySeparator(realPathDirectory));
+            if (!symlinkDirectories) return undefined; // Continue to ancestor directory
+
+            // Don't want to a package to globally import from itself (importNameCodeFix_symlink_own_package.ts)
+            if (startsWithDirectory(importingFileName, realPathDirectory, getCanonicalFileName)) {
```
Comment (sheetalkamat) [inline src/compiler/moduleSpecifiers.ts:309]: Use `importedPath` which is already canonicalized?

File: src/compiler/moduleSpecifiers.ts [hunk 2]
```diff
@@ -299,22 +300,24 @@ namespace ts.moduleSpecifiers {
...
             : discoverProbableSymlinks(host.getSourceFiles(), getCanonicalFileName, cwd);
 
-        const symlinkedDirectories = links.getSymlinkedDirectories();
-        const useCaseSensitiveFileNames = !host.useCaseSensitiveFileNames || host.useCaseSensitiveFileNames();
-        const result = symlinkedDirectories && forEachEntry(symlinkedDirectories, (resolved, path) => {
-            if (resolved === false) return undefined;
-            if (startsWithDirectory(importingFileName, resolved.realPath, getCanonicalFileName)) {
-                return undefined; // Don't want to a package to globally import from itself
+        const symlinkedDirectories = links.getSymlinkedDirectoriesByRealpath();
+        const result = symlinkedDirectories && forEachAncestorDirectory(getDirectoryPath(importedPath), realPathDirectory => {
```
Comment (sheetalkamat) [inline src/compiler/moduleSpecifiers.ts:304]: Using `importedPath` here isn't correct as all paths will be lowercased and you will loose the user casing on case insensitive file system

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

**Comment by sandersn** [comment]
I don't know the code well enough to have detailed comments, but since this is a perf fix, any idea what the difference in memory usage is? Is the scale of the cache going to remain small enough not to matter?

**Comment by andrewbranch** [comment]
@sandersn I didn’t measure it, partly because since it’s just path strings, it’s obviously dependent upon the length of the paths but you can do the estimation in your head, and it would take quite a lot of path strings to add up to anything appreciable. And since non-pnpm users tend not to have more than a handful of symlinks in the first place, the typical memory impact will be near-zero. Only users who are currently getting absolutely miserable time performance should see anything approaching a few kB.

File: src/compiler/moduleSpecifiers.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts:309]: This is import**ing**FileName, not import**ed**FileName

File: src/compiler/moduleSpecifiers.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts]: This may have been an existing bug as it turns out all values in the cache populated by `discoverProbableSymlinks` were already being lowercased. Added a test and fixed.

File: src/compiler/moduleSpecifiers.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/moduleSpecifiers.ts:310]: sorry about that..

**Review by sheetalkamat — APPROVED** [review]
