### PR TITLE
go-to-type-definition, and find-all-refs should work for import.meta

### LINKED ISSUE #24353: go-to-type-definition, and find-all-refs not working for `import.meta`
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
import.meta; 
```

**Expected behavior:**

- go-to-def should fail
- go-to-type-def should jump to `ImportMeta` in lib.es5.d.ts
- find-all-refs / occurrences should highlight all references of import.meta
- rename should fail

**Actual behavior:**

- go-to-type-def fails
- find-all-refs / occurrences fails

**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #24353

IIUC, `import.meta` have no corresponding symbol, and the general algorithm (find the symbol of node, find the type/references of symbol) will not work. So I just intercept them in the services.

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -1425,6 +1429,20 @@ namespace ts.FindAllReferences {
             }
         }
 
+        function getAllReferencesForImportMeta(sourceFiles: readonly SourceFile[], cancellationToken: CancellationToken): SymbolAndEntries[] | undefined {
+            const references = flatMap(sourceFiles, sourceFile => {
+                cancellationToken.throwIfCancellationRequested();
+                return mapDefined(getPossibleSymbolReferenceNodes(sourceFile, "import.meta", sourceFile), node => {
```
Comment (DanielRosenwasser) [inline src/services/findAllReferences.ts:1435]: This doesn't work in the presence of whitespace.

```ts
let x = import
  .  // hai :)
    meta;
```

I would change your search string to `meta` instead.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

File: src/services/findAllReferences.ts [hunk 2]
```diff
@@ -1425,6 +1429,19 @@ namespace ts.FindAllReferences {
...
+            const references = flatMap(sourceFiles, sourceFile => {
+                cancellationToken.throwIfCancellationRequested();
+                return mapDefined(getPossibleSymbolReferenceNodes(sourceFile, "meta", sourceFile), node => {
+                    const parent = node.parent;
+                    if (isImportMeta(parent)) {
+                        return nodeEntry(parent);
+                    }
+                });
+            });
+            return references.length ? [{ definition: { type: DefinitionKind.Keyword, node: references[0].node }, references }] : undefined;
```
Comment (DanielRosenwasser) [inline src/services/findAllReferences.ts:1442]: I don't exactly know if you should be considering anything a "definition" location apart from the global `ImportMeta` interface.

Even that one is a little weird, because that's what you'd want if you requested "go-to-type". Do all responses require a `definition`? @jessetrinity and @andrewbranch might have more knowledge here.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
This looks good! I think I mostly just have a nit regarding what we consider a "definition" reference.

File: src/services/findAllReferences.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/findAllReferences.ts:1442]: The types imply that a definition isn’t required. My intuition is that this shouldn’t be one.

Comment (Zzzen) [reply src/services/findAllReferences.ts:1442]: It's copied from `getAllReferencesForKeyword`, which searches primitive types like `string/number/any`. They should have no definition either?

```ts
function getAllReferencesForKeyword(sourceFiles: readonly SourceFile[], keywordKind: SyntaxKind, cancellationToken: CancellationToken, filter?: (node: Node) => boolean): SymbolAndEntries[] | undefined {
    // ...
    return references.length ? [{ definition: { type: DefinitionKind.Keyword, node: references[0].node }, references }] : undefined;
}
```

Comment (andrewbranch) [reply src/services/findAllReferences.ts:1442]: I’m not 100% sure what the implications are for removing it—we should check with @mjbvz ad @uniqueiniquity.

Comment (andrewbranch) [reply src/services/findAllReferences.ts:1442]: Let’s get rid of the `definition`

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/findAllReferences.ts (hunk 2 above)
Comment (Zzzen) [reply src/services/findAllReferences.ts]: `findReferencedSymbols` won't work if `definition` is absent.
https://github.com/microsoft/TypeScript/blob/29c7ae23cadd3ef866ebddc3923423eec27fc531/src/services/findAllReferences.ts#L207-L219

File: tests/baselines/reference/findAllRefsImportMeta.baseline.jsonc [hunk 3]
```diff
@@ -0,0 +1 @@
+[]
```
[the remark this answers is not in the document]
Comment (Zzzen) [reply tests/baselines/reference/findAllRefsImportMeta.baseline.jsonc]: Ooops, it's empty because `definition` is removed. Currently `definition` is required. It might break vscode if we make it optional.

https://github.com/microsoft/TypeScript/blob/733eff2b104540648dfe0c661f08b019165bdd09/src/services/types.ts#L1042-L1045

File: src/services/findAllReferences.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/findAllReferences.ts:1452]: 🤦 I swear all this stuff was just made up on the spot

**Review by andrewbranch — APPROVED** [review]
