### PR TITLE
Don't trace bindSourceFile cache hits

### LINKED ISSUE #47565: Omitting tracing spans for bindSourceFile?
In https://github.com/elastic/kibana, we have a lot of projects that have 1000s of files. When tracing is enabled (for the language server), it seems there is significant overhead from creating `bindSourceFile` spans, which makes it harder to isolate measurements of performance improvements/regressions. I was wondering if these should be turned off, but I'm not sure what the value is of the invididual spans (compared to creating one `bindSourceFiles` span).

### PR DESCRIPTION
**Pull request by amcasey**
Writing the trace entry takes longer than returning the cached value.

Fixes #47565

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -253,7 +251,9 @@ namespace ts {
             Debug.attachFlowNodeDebugInfo(reportedUnreachableFlow);
 
             if (!file.locals) {
+                tracing?.push(tracing.Phase.Bind, "bindSourceFile", { path: file.path }, /*separateBeginAndEnd*/ true);
```
Comment (amcasey) [inline src/compiler/binder.ts:254]: I considered renaming this but I'm pretty sure the old tracepoint had no consumers and it's a good  name.

**Review by jakebailey — APPROVED** [review]
