### PR TITLE
Fix implicit glob detection when ancestor directory contains `.`

### LINKED ISSUE #45721: Newly created files don't belong to typescript project on MacOS
# Bug Report

### 🔎 Search Terms

Maybe `ts`, `vscode`, `file is not part of ts project`, `newly created`?

### 🕗 Version & Regression Information

Tested on the following typescript versions:
- 4.5.0-dev.20210904
- 4.4.2
- 4.4.1-rc
- 4.3.5

vscode version: 1.60.0

### ⏯ Playground Link

https://github.com/yifanwww/ts-bug-repo

This is a very simple project...

### 🙁 Actual behavior

Open that project via vscode(whatever open folder directly or open the workspace file).
Open the file `src/index.ts` to get tsserver started, then create a new file `src/test.ts`.

There should be an error `cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.ts(1208)`, but actually it got no error.

Execute vscode command `Typescript: Go to Project Configuration`, a panel appears with info `File is not part of a Typescript project. Click here to learn more.`

In that new ts file, no auto-completion and no auto-import to use the function `fn` which is declared in `src/index.ts`.

I have to restart tsserver or reload vscode.

I have checked these issues but still don't know how to solve this problem.
- https://github.com/microsoft/TypeScript/issues/43290
- https://github.com/microsoft/TypeScript/issues/36532
- https://github.com/microsoft/TypeScript/issues/35794
- https://github.com/microsoft/TypeScript/issues/33564

**This bug never happens on my win laptop, but does always happen on my mac laptop.**

### 🙂 Expected behavior

The file gets added into the existing typescript project.

BTW, If you need `tsserver.log`, please tell me how to get it.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #45721 

Big thanks to @lgarron 🌟

### CODE REVIEW

File: src/testRunner/unittests/config/tsconfigParsing.ts [hunk 1]
```diff
@@ -412,5 +412,14 @@ namespace ts {
...
         });
+
+        it("parses wildcard directories even when parent directories have dots", () => {
+            const parsed = parseConfigFileTextToJson("/foo.bar/tsconfig.json", JSON.stringify({
+                include: ["src"]
+            }));
+
+            const parsedCommand = parseJsonConfigFileContent(parsed.config, sys, "/foo.bar");
+            assert.deepEqual(parsedCommand.wildcardDirectories, { "/foo.bar/src": WatchDirectoryFlags.Recursive });
+        });
```
Comment (lgarron) [inline src/testRunner/unittests/config/tsconfigParsing.ts:423]: Would it be worth adding a test for `/repo/src/example.com` as well? (Dot in the include path, but not in the repo path.)

**Review by RyanCavanaugh — APPROVED** [review]

File: src/testRunner/unittests/config/tsconfigParsing.ts (hunk 1 above)
Comment (andrewbranch) [reply src/testRunner/unittests/config/tsconfigParsing.ts:423]: A dot in the last component of the include path is still going to cause a problem—I’m not sure we’ve settled on what the expected behavior for that is.

**Comment by lgarron** [comment]
Thanks for the fix! ❤️
