### PR TITLE
Make sure type parameters stay fixed throughout the inference process

### LINKED ISSUE #2127: Bug: Cannot read property 'flags' of undefined
Trying to compile

    interface IBar {
        [barId: string]: any;
    }

    interface IFoo {
        foo<TBar extends IBar>(bar: TBar, bar1: (bar: TBar)=>any, bar2: (bar: TBar)=>any);
    }

    var foo: IFoo;
    foo.foo({bar: null}, bar => null, bar => null);

leads to the following error

    if (source.flags & 128 /* Enum */ && target === numberType
              ^
    TypeError: Cannot read property 'flags' of undefined
        at isRelatedTo (tsc.js:13077:31)
        at checkTypeRelatedTo (tsc.js:13048:26)
        at checkTypeSubtypeOf (tsc.js:13029:20)
        at reportNoCommonSupertypeError (tsc.js:13618:13)
        at resolveCall (tsc.js:14945:21)
        at resolveCallExpression (tsc.js:15075:20)
        at getResolvedSignature (tsc.js:15125:47)
        at checkCallExpression (tsc.js:15140:29)
        at checkExpressionWorker (tsc.js:15648:28)
        at checkExpressionOrQualifiedName (tsc.js:15605:42)

tsc version 1.4.1.0

You can also put this code into the typescript [Playground](http://www.typescriptlang.org/Playground), which does not complie it as well.

### LINKED ISSUE #2182: Type inference algorithm in compiler differs from spec?
4.12.2 spec says:
> Proceeding from left to right, each argument expression e is inferentially typed
> ...
> When a function expression is inferentially typed (section 4.9.3) and a type assigned to a
> parameter in that expression references type parameters for which inferences are being made, the
> corresponding inferred type arguments to become fixed and no further candidate inferences are
> made for them.

But it works differently in compiler. For example:
```ts
    function f<T, U>(y: T, f: (x: T) => U, x: T): [T, U] { return [y, f(x)]; }
    interface A { a: A; }
    interface B extends A { b; }

    var a: A, b: B;

    var d = f(b, x => x.a, a); // type [A, A]
    var d2 = f(b, x => x.a, null); // type [B, A]
```
If "no further candidate inferences were made", then types of d and d2 would be the same. But they are different.

### PR DESCRIPTION
**Pull request by JsonFreeman**
This fixes #2182 and fixes #2127.

The problem is essentially that after we fix a type parameter during type argument inference, we may unfix it later. This happens because the inference context that we use to store the results gets forgotten on every iteration of type argument inference. The main part of this change is to make the inference context persist throughout the processing of signature.

As an example, if you have:
```ts
declare function f<T>(x: T, y: (p: T) => T, z: (p: T) => T): T;
f(0, x => null, x => null);
```
Right now, T will be inferred to any, because we do 3 passes (one for each argument in this case). The results from each pass are as follows:

1. T is inferred to be number because of the 0
2. T is fixed because we pass a lambda for the second argument, so we do not infer from the null
3. T eventually gets fixed when we get to z for a similar reason, but we've forgotten that it got fixed in parameter y, so we've inferred from the null in the first lambda, and so we get any

This also had a very unusual effect with constraints, which led to a crash. Namely, when it comes time to fix a type parameter, and the type we were going to infer is not assignable to the constraint, we infer the constraint instead, and we fix the type parameter. Then later we may infer back from that constraint, thereby adding an inference candidate that should never have been added. As a result, we have no common supertype among candidates, when really we should only have had one candidate.

The moral of the story is that when a type parameter gets fixed, it should stay fixed. This change is not totally complete, in that fixedness does not get persisted between overloads, but that is a phenomenon for another day.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4723,21 +4726,32 @@ module ts {
...
                     // Infer widened union or supertype, or the undefined type for no common supertype
                     let unionOrSuperType = context.inferUnionTypes ? getUnionType(inferences) : getCommonSupertype(inferences);
-                    inferredType = unionOrSuperType ? getWidenedType(unionOrSuperType) : inferenceFailureType;
+                    inferredType = unionOrSuperType ? getWidenedType(unionOrSuperType) : unknownType;
+                    inferenceSucceeded = !!unionOrSuperType;
                 }
                 else {
                     // Infer the empty object type when no inferences were made
                     inferredType = emptyObjectType;
+                    inferenceSucceeded = true;
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: This seems odd. No inferences were made, but inference succeeded?  Can you provide some some explnatories comments on this?  Thanks!

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4723,21 +4726,32 @@ module ts {
...
                 }
-                if (inferredType !== inferenceFailureType) {
+
+                // Only do the constraint check if inference succeeded (to prevent cascading errors)
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Great comment, thanks.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -4723,21 +4726,32 @@ module ts {
...
+                if (inferenceSucceeded) {
                     let constraint = getConstraintOfTypeParameter(context.typeParameters[index]);
                     inferredType = constraint && !isTypeAssignableTo(inferredType, constraint) ? constraint : inferredType;
                 }
+                // If inference failed, it is necessary to record the index of the failed type parameter (the one we are on).
+                // It might be that inference has already failed on a later type parameter on a previous call to inferTypeArguments.
+                // So if this failure is on preceding type parameter, this type parameter is the new failure index.
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: I'd prefer if we don't put comments before 'else'.  it makes the 'if' portion appear 'done', and makes it easy to miss htat this side is an 'else' vs just hte code that runs once the 'if' is done.  Can we put the comments 'inside' the 'else' block instead?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -6334,11 +6348,22 @@ module ts {
...
 
-        function inferTypeArguments(signature: Signature, args: Expression[], excludeArgument: boolean[]): InferenceContext {
+        function inferTypeArguments(signature: Signature, args: Expression[], excludeArgument: boolean[], context: InferenceContext): void {
             let typeParameters = signature.typeParameters;
-            let context = createInferenceContext(typeParameters, /*inferUnionTypes*/ false);
             let inferenceMapper = createInferenceMapper(context);
 
+            // Clear out all the inference results from the last time inferTypeArguments was called on this context
+            for (let i = 0; i < typeParameters.length; i++) {
+                // As an optimization, we don't have to clear (and later recompute) inferred types
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Is this actually an optimization?  Or is this necessary to get correct results?   I thought it was the latter.

File: src/compiler/types.ts [hunk 5]
```diff
@@ -1485,6 +1485,8 @@ module ts {
     export interface TypeInferences {
```
Comment (CyrusNajmabadi) [inline src/compiler/types.ts]: Might want to consider marking this as @internal   so it doesn't affect the API tests.

File: src/compiler/checker.ts (hunk 1 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Sure, but this is just a rule of the language. If there were no inferences, inference still succeeds. I don't love it. But @DanielRosenwasser has a PR where he issues an error for this case under a compiler flag.

File: src/compiler/checker.ts (hunk 3 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Yup, totally reasonable.

File: src/compiler/checker.ts (hunk 4 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: It's not an optimization that we reset it. It's an optimization that we skip resetting it if the type parameter was already fixed. It would be just as correct to reset all of them. But then we'd be repeating the same work for the type parameters that were fixed. Namely the work done by getInferredType.

File: src/compiler/types.ts (hunk 5 above)
Comment (JsonFreeman) [inline src/compiler/types.ts]: We should just add a keyword for this instead of having this comment annotation thing. But sure.

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: It's not yet a PR; I'd like to make it a PR if we could solve some of the original concerns in #360.

To clarify, when inference for a type argument fails, the process falls back to using `{}` as a type argument. :+1: for explaining what a failure scenario would be in contrast to no inferences being found.

Comment (JsonFreeman) [inline src/compiler/checker.ts]: Ok, I'll add a comment.

File: src/compiler/checker.ts (hunk 4 above)
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Good to explain in the code.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -4379,6 +4379,8 @@ module ts {
                     }
                 }
 
+                Debug.assert(!!downfallType, "If there is no common supertype, each type should have a downfallType");
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: downfallType? Is this supposed to be like a fallbackType? Rename it so. downfallType sounds like it encompasses revolutions, lost wars, etc.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -4613,11 +4614,13 @@ module ts {
...
-                            let candidates = inferiority ?
-                                inferences.secondary || (inferences.secondary = []) :
-                                inferences.primary || (inferences.primary = []);
-                            if (!contains(candidates, source)) candidates.push(source);
-                            break;
+                            if (!inferences.isFixed) {
+                                let candidates = inferiority ?
+                                    inferences.secondary || (inferences.secondary = []) :
+                                    inferences.primary || (inferences.primary = []);
+                                if (!contains(candidates, source)) candidates.push(source);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Curlies

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Also newline above.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -4613,11 +4614,13 @@ module ts {
                     for (let i = 0; i < typeParameters.length; i++) {
                         if (target === typeParameters[i]) {
                             let inferences = context.inferences[i];
-                            let candidates = inferiority ?
-                                inferences.secondary || (inferences.secondary = []) :
-                                inferences.primary || (inferences.primary = []);
-                            if (!contains(candidates, source)) candidates.push(source);
-                            break;
+                            if (!inferences.isFixed) {
+                                let candidates = inferiority ?
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: There's no documentation for inferiority.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Also, the documentation for `primary` and `secondary` are a bit lacking; elaborate on the distinctions and *why* we make these distinctions.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -6334,11 +6351,22 @@ module ts {
...
         }
 
-        function inferTypeArguments(signature: Signature, args: Expression[], excludeArgument: boolean[]): InferenceContext {
+        function inferTypeArguments(signature: Signature, args: Expression[], excludeArgument: boolean[], context: InferenceContext): void {
             let typeParameters = signature.typeParameters;
-            let context = createInferenceContext(typeParameters, /*inferUnionTypes*/ false);
             let inferenceMapper = createInferenceMapper(context);
 
+            // Clear out all the inference results from the last time inferTypeArguments was called on this context
+            for (let i = 0; i < typeParameters.length; i++) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: for..of

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -6334,11 +6351,22 @@ module ts {
...
+                // As an optimization, we don't have to clear (and later recompute) inferred types
+                // for type parameters that have already been fixed on the previous call to inferTypeArguments
+                if (!context.inferences[i].isFixed) {
+                    context.inferredTypes[i] = undefined;
+                }
+            }
+            if (context.failedTypeParameterIndex >= 0 && !context.inferences[context.failedTypeParameterIndex].isFixed) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Comment what this does.

File: src/compiler/checker.ts (hunk 4 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Ok, I'm basically adding my comment from above as a comment in the code

File: src/compiler/checker.ts (hunk 10 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]:
```ts
            // On this call to inferTypeArguments, we may get more inferences for certain type parameters that were not
            // fixed last time. This means that a type parameter that failed inference last time may succeed this time,
            // or vice versa. Therefore, the failedTypeParameterIndex is useless if it points to an unfixed type parameter,
            // because it may change. So here we reset it. However, getInferredType will not revisit any type parameters
            // that were previously fixed. So if a fixed type parameter failed previously, it will fail again because
            // it will contain the exact same set of inferences. So if we reset the index from a fixed type parameter,
            // we will lose information that we won't recover this time around.

```

**Comment by danquirk** [comment]
Is there a bug logged for the overload portion?

File: src/compiler/checker.ts (hunk 8 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]:
```ts
// Any inferences that are made to a type parameter in a union type are inferior
// to inferences made to a flat (non-union) type. This is because if we infer to
// T | string[], we really don't know if we should be inferring to T or not (because
// the correct constituent on the target side could be string[]). Therefore, we put
// such inferior inferences into a secondary bucket, and only use them if the primary
// bucket is empty.
```

File: src/compiler/checker.ts (hunk 7 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Okay

File: src/compiler/checker.ts (hunk 6 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: It *is* supposed to be downfallType. It *is* supposed to sound like it describes revolutions and lost wars, but in particular tragic heroes.

The downfallType is the type that caused a particular candidate to not be the common supertype. So if it weren't for this one downfallType, the type in question could have been the common supertype.

Note that downfallType is the first type that is not a subtype of type. It's not necessarily the only one.

**Comment by JsonFreeman** [comment]
@danquirk I have not seen one. I can try to file one if I can cook up a good repro.

**Comment by JsonFreeman** [comment]
I've logged #2378 for the remaining work in this area.

File: src/compiler/checker.ts (hunk 6 above)
Comment (yuit) [inline src/compiler/checker.ts]: Can we add this explanation in the code  
```
The downfallType is the type that caused a particular candidate to not be the common supertype. So if it weren't for this one downfallType, the type in question could have been the common supertype.
```

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -4570,12 +4572,11 @@ module ts {
...
             for (let unused of typeParameters) {
-                inferences.push({ primary: undefined, secondary: undefined });
+                inferences.push({ primary: undefined, secondary: undefined, isFixed: false });
             }
             return {
                 typeParameters: typeParameters,
                 inferUnionTypes: inferUnionTypes,
-                inferenceCount: 0,
                 inferences: inferences,
                 inferredTypes: new Array(typeParameters.length),
```
Comment (yuit) [inline src/compiler/checker.ts]: Should this have ```failedTypeParameterIndex``` as a property? It is optional though I find it will be easier to read through

File: src/compiler/checker.ts (hunk 8 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: :clap:

File: src/compiler/checker.ts (hunk 11 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I think I'm going to leave it out. The reason it's optional is because it is always initially undefined, and undefined means that there have been no failures (yet).
