### PR TITLE
Fix crash on attempting to suggest a ts import for a synthetic js resolution

### LINKED ISSUE #41410: 4.1 RC crashes when new JSX factory is used with incremental mode
**TypeScript Version:**  `4.1.1-rc` (also reproduces in `4.2.0-dev.20201104`)

**Search Terms:** JSX factory incremental

**Code**

index.tsx:

```tsx
export default function Foo(): JSX.Element {
  return <div />;
}
```

tsconfig.json:

```json
{
  "compilerOptions": {
    "incremental": true,
    "jsx": "react-jsx"
  }
}
```

package.json:

```json
{
  "scripts": {
    "test": "tsc"
  },
  "devDependencies": {
    "typescript": "4.1.1-rc"
  },
  "dependencies": {
    "@types/react": "^16.9.55",
    "react": "^16.14.0"
  }
}
```

**Expected behavior:**

Running `tsc` shouldn't crash.

**Actual behavior:**

```
/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:8489
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:8489:19)
    at Object.createTextSpanFromBounds (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:8498:16)
    at getErrorSpanForNode (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:10803:19)
    at Object.createDiagnosticForNodeFromMessageChain (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:10711:20)
    at errorOrSuggestion (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:36053:141)
    at errorOnImplicitAnyModule (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:37798:13)
    at resolveExternalModule (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:37757:21)
    at resolveExternalModuleNameWorker (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:37711:19)
    at resolveExternalModuleName (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:37706:20)
    at getSymbolAtLocation (/Users/billy/work/ts-bug/node_modules/typescript/lib/tsc.js:64910:32)
```

**Playground Link:** 

Can't make a playground because `4.1.1-rc` isn't available there yet but [here](https://github.com/billyjanitsch/ts-bug)'s a minimal repo.

**Related Issues:** 

Seems related to https://github.com/microsoft/TypeScript/pull/41330 and prior PRs.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #41410

After looking at it a bit, I realized we _were_ checking if `ignoreErrors` was set, but were unconditionally making a diagnostic because we wanted to try and offer a suggestion (namely, a suggestion to try to install types for it when the js seems to be present, but not any types). I simply changed our suggestion-or-error adding function to more gracefully handle the psuedo-synthetic nodes we use for some compiler-option-added imports. Now that I know how it works, I can say it was _theoretically_ possible to trigger the same issue with `importHelpers`, but you'd have needed to have a `tslib` on disk with no accompanying types, which is obviously not what we distribute (therefore very unlikely to occur).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1091,6 +1091,16 @@ namespace ts {
             }
         }
         function errorOrSuggestion(isError: boolean, location: Node, message: DiagnosticMessage | DiagnosticMessageChain, arg0?: string | number, arg1?: string | number, arg2?: string | number, arg3?: string | number): void {
+            if (location.pos < 0 || location.end < 0) {
+                // Psuedo-synthesized input node
```
Comment (sandersn) [inline src/compiler/checker.ts:1095]:
```suggestion
            // Pseudo-synthesized input node
            if (location.pos < 0 || location.end < 0) {
```

**Review by sandersn — APPROVED** [review]

**Review by sheetalkamat — APPROVED** [review]

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this into release-4.1
