### PR TITLE
Include all flow nodes made within `try` blocks as antecedents for `catch` or `finally` blocks

### LINKED ISSUE #28153: In finally block, local variable is incorrectly typed as never with return in try block.
**TypeScript Version:**  3.1.3

**Search Terms:** try finally block 

**Code**

```ts
async function test(): Promise<string> {
    let browser: puppeteer.Browser | undefined = undefined;
    let page: puppeteer.Page | undefined = undefined;
    try {
        browser = await test1();
        page = await test2(browser);
        return await page.content();;
    } finally {
        if (page) {
            await page.close();
        }

        if (browser) {
            await browser.close();
        }
    }
}

async function test1(): Promise<puppeteer.Browser> {
    return await puppeteer.launch();
}

async function test2(browser: puppeteer.Browser): Promise<puppeteer.Page> {
    return await browser.newPage();
}
```

**Expected behavior:**
page and browser can be of type puppeteer.Page and puppeteer.Browser

**Actual behavior:**
compile error message:
error TS2339: Property 'close' does not exist on type 'never'.

**Related Issues:** 
#11665(The different is current issue's code contains a return in try block)

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #28153 (And removes a TODO)

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1080,21 +1085,49 @@ namespace ts {
         function bindTryStatement(node: TryStatement): void {
             const preFinallyLabel = createBranchLabel();
             const preTryFlow = currentFlow;
-            // TODO: Every statement in try block is potentially an exit point!
+            const tryPriors: FlowNode[] = [];
+            const oldFlowNodeCreated = flowNodeCreated;
+            // We hook the creation of all flow nodes within the `try` scope and store them so we can add _all_ of them
+            // as possible antecedents of the start of the `catch` or `finally` blocks.
+            // Don't bother intercepting the call if there's no finally or catch block that needs the information
+            if (node.catchClause || node.finallyBlock) {
```
Comment (ajafff) [inline src/compiler/binder.ts]: Does this condition make sense? It's only false if there is a syntax error.

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -1080,21 +1085,49 @@ namespace ts {
...
+                    currentFlow = finishFlowLabel(preCatchFlow);
+                }
+
                 bind(node.catchClause);
                 addAntecedent(preFinallyLabel, currentFlow);
 
                 flowAfterCatch = currentFlow;
             }
             if (node.finallyBlock) {
+                // We add the nodes within the `try` block to te `finally`'s antecedents if there's no catch block
```
Comment (ajafff) [inline src/compiler/binder.ts]: Typo: "te" should be "the"

File: src/compiler/binder.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/binder.ts]: We still parse code with syntax errors 🤷‍♂️
