### PR TITLE
Don't leak EvolvingArray out of code flow

### LINKED ISSUE #49942: Crash in narrowing when using for-in
```ts
var C = [];
for (var a in C)
    if (C.hasOwnProperty(a)) {
    }
}
```

```
TypeError: Cannot read properties of undefined (reading 'length')
    at isFunctionObjectType (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:70256:47)
    at getTypeFacts (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:70302:21)
    at isNullableType (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:75165:23)
    at getNonNullableTypeIfNeeded (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:75168:20)
    at getTypeAtFlowAssignment (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:71169:28)
    at getTypeAtFlowNode (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:71049:32)
    at getFlowTypeOfReference (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:71003:51)
    at checkIdentifier (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:72433:28)
    at checkExpressionWorker (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:80598:28)
    at checkExpression (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:80547:38)
    at checkNonNullExpression (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:75162:37)
    at checkPropertyAccessExpression (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:75207:85)
    at getSymbolOfNameOrPropertyAccessExpression (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:87207:25)
    at getSymbolAtLocation (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:87314:32)
    at Object.getSymbolAtLocation (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:48831:31)
    at getSymbolAtLocationForQuickInfo (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:167703:24)
    at Object.getQuickInfoAtPosition (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:166736:26)
    at IpcIOSession.Session.getQuickInfoWorker (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:178739:62)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:177461:61)
    at c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:179575:96
    at IpcIOSession.Session.executeWithRequestId (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:179566:28)
    at IpcIOSession.Session.executeCommand (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:179575:41)
    at IpcIOSession.Session.onMessage (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:179603:35)
    at process.<anonymous> (c:/Users/Daniel/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.8.20220717/node_modules/typescript/lib/tsserver.js:183769:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

Either https://github.com/microsoft/TypeScript/pull/49887 (@jakebailey) or https://github.com/microsoft/TypeScript/pull/49625 (@ahejlsberg) likely caused this since it appears consistently and happened after Friday.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #49942

([I have no idea what I'm doing](https://user-images.githubusercontent.com/5341706/179630287-6d6b9fa8-7c15-4b13-96c3-73c471ea6b0b.png) in the code flow engine)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11896,13 +11896,19 @@ namespace ts {
...
                     resolveUnionTypeMembers(type as UnionType);
                 }
                 else if (type.flags & TypeFlags.Intersection) {
                     resolveIntersectionTypeMembers(type as IntersectionType);
                 }
+                else {
+                    Debug.fail("Unhandled type " + Debug.formatTypeFlags(type.flags));
+                }
             }
             return type as ResolvedType;
```
Comment (jakebailey) [inline src/compiler/checker.ts:11913]: Maybe this should assert each of the things that `ResolvedType` is assuming are defined, but I don't know how expensive that would be.

File: tests/cases/fourslash/quickInfoEvolvingArrayType.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+// @outDir: ./dist
+
+// filename: index.js
+//// var C = [];
+//// for (var a in C)
+////     if (C.hasOwn/*1*/Property(a)) {
+////     }
+//// }
+
+verify.baselineQuickInfo();
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/quickInfoEvolvingArrayType.ts:15]: I'd strongly prefer that this be a compiler test over a fourslash test.

File: tests/cases/fourslash/quickInfoEvolvingArrayType.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+///<reference path="fourslash.ts" />
+
+// @strict: true
+// @checkJs: true
+// @allowJs: true
+// @outDir: ./dist
+
+// filename: index.js
+//// var C = [];
+//// for (var a in C)
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/quickInfoEvolvingArrayType.ts:10]: Also, my bad, this should probably have an opening `{`, the trailing `}` is unmatched.

Comment (jakebailey) [reply tests/cases/fourslash/quickInfoEvolvingArrayType.ts:10]: I figured that was part of the test, hah.

File: tests/cases/fourslash/quickInfoEvolvingArrayType.ts (hunk 2 above)
Comment (jakebailey) [reply tests/cases/fourslash/quickInfoEvolvingArrayType.ts:15]: Yeah, I had issues making it a real test, but I think my problem was actually not making it a JS test. Let me switch it.

Comment (DanielRosenwasser) [reply tests/cases/fourslash/quickInfoEvolvingArrayType.ts:15]: Yeah, it doesn't necessarily have to be JS. It can also be `noImplicitAny` I believe.

**Review by DanielRosenwasser — APPROVED** [review]

File: tests/cases/fourslash/quickInfoEvolvingArrayType.ts (hunk 2 above)
Comment (jakebailey) [reply tests/cases/fourslash/quickInfoEvolvingArrayType.ts]: Yeah, also noticed that (because I had a typo in the test when I copied the fourslash over and forgot to add the @ before "filename"). I can make it regular TS instead; it's probably cleaner that way.
