### PR TITLE
Fix mapper used to instantiate distributive conditional manufactured in declaration emit

### LINKED ISSUE #49572: Function involving FlatArray is transformed in declaration in an incompatible type.
# Bug Report

### 🔎 Search Terms

FlatArray declaration unknown
### 🕗 Version & Regression Information

- This changed between versions 4.7.0-dev.20220406 and 4.7.0-dev.20220408 (still present in 4.7.3)

### ⏯ Playground Link

[Playground link with relevant code (target: es2019)](https://www.typescriptlang.org/play?target=6&ssl=18&ssc=32&pln=1&pc=1#code/PTAEBUAsEsGdQGYFcB2BjALtA9ig5PBgJ4AOApqHKGpAIYoDmZAJqLqM2WgDa0BOtLLgBQZAB4lsfDNVywZyFKAC8oABTCAkLCQAjAGKoAXKAA8AYWzduXISgA0ofdDLdW4jGRTN4AazJE2Aiglta2OCgAfGoAlFqaypFOvBgAgnwCRBZWNpgRANrOrswAuo4ADJH5JTEqSQDeoAC+ANzCwiAQMPD8DEgAtl4ysJDYSG6g-YI0oBiQFMTkbMG9A0OgSLAsoLpEiKjCaHLDeoYoAKJitP0kNipmobl2jkUTHl4+oP6BwY-huNE4ppNCZ9Cl0plsmE8rhCi43GVQJVqnVQNU2h0wOBSGRYGg+NASDJmNhcaAUNgZHM+NgAO6geh7MgZKSzeZ8MjCRRqHQGVCXa63MgxDGdKBUKhzBY4xBjbyyvj7JTQJRSjhcXgCOyIaA2AB0oAAksNRuNWLoKGQAI5IaAAN1oNhQVOwbOlSwQrMUesOxyVAH1ODx+IIIiYeadjA8cv8HE54e4xJ5vH4AkEQjGYVFYqi1H8s3DiiVQO8U5QUAhmRBQAB+aulz75uyFhG1+tJj7wDm0Ekobh7VC+Cm0lAouuD4dKEzgUAmFBkO1VucL5kxaq1RKgO3YaCsLSqNT+jcNVrtMU4vEEolsmm0npKZk0xVSjk+xSBjUhuwRvkXK43GwRWEIA)

### 💻 Code

```ts
// This function's type is changed on declaration
export const fun = (
	subFun: <Collection, Field extends keyof Collection>()
		=> FlatArray<Collection[Field], 0>[]) => { };

// This argument should match the type of argument used by fun
const subFunExample = <Collection, Field extends keyof Collection>()
		: FlatArray<Collection[Field], 0>[] => [];

// Typescript does not throw any error there
fun(subFunExample);

// This is the type found for fun in the declaration file. It should be equivalent to the type for fun.
const fun_declaration: (subFun: <Collection, Field extends keyof Collection>() => (Collection[Field] extends infer T ? T extends Collection[Field] ? T extends readonly unknown[] ? unknown : T : never : never)[]) => void 
	= (_) => {};

// Typescript throws an error there.
fun_declaration(subFunExample);
```

### 🙁 Actual behavior

When the declaration is created, the type of fun is transformed to `(subFun: <Collection, Field extends keyof Collection>() => (Collection[Field] extends infer T ? T extends Collection[Field] ? T extends readonly unknown[] ? unknown : T : never : never)[]) => void;`.

This declaration type does not recognize arguments that were matched by the original type.

### 🙂 Expected behavior

No error. Declaration type should be equivalent to the original type: if typescript does not raise an error with the original type, it should raise an error for the declaration type.

I've tried to find a simpler type exhibiting this behavior, but didn't find any.

### PR DESCRIPTION
**Pull request by weswigham**
And refactor type mapper creation just a tad to give them a nice debug printback for when you're trying to track down issues involving them.

Fixes #49572.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5124,7 +5153,7 @@ namespace ts {
                         const name = typeParameterToName(newParam, context);
                         const newTypeVariable = factory.createTypeReferenceNode(name);
                         context.approximateLength += 37; // 15 each for two added conditionals, 7 for an added infer type
-                        const newMapper = prependTypeMapping(type.root.checkType, newParam, type.combinedMapper || type.mapper);
+                        const newMapper = prependTypeMapping(type.root.checkType, newParam, type.mapper);
```
Comment (weswigham) [inline src/compiler/checker.ts:5156]: This line's the only one that was needed to fix the related issue - the rest was just nice refactoring I used to make this change evident while debugging.

**Comment by weswigham** [comment]
@typescript-bot perf test this just in case - debug only code shouldn't change much, but you never know

**Comment by weswigham** [comment]
@typescript-bot perf test this again since someone canceled the build

**Review by andrewbranch — APPROVED** [review]
