### PR TITLE
Treat hoisted temp variables as a custom prologue.

### LINKED ISSUE #30653: Rest arguments in recursive generator functions are broken when targetting es5
**Search Terms:** rest arguments generator downlevel iteration

**Code**

```ts
function isIterable(i: any): i is Iterable<any> {
  return Boolean(i && typeof i[Symbol.iterator] === "function");
}

function* mergeStringLists(...strings: unknown[]): IterableIterator<string> {
  for (const str of strings) {
    if (typeof str === "string") {
      if (str) yield str;
    } else if (isIterable(str)) {
      yield* mergeStringLists(...str);
    }
  }
}
```

The tsconfig.json used:

```json
{
  "compilerOptions": {
    "downlevelIteration": true,
    "target": "es5",
    "lib": ["es2017"]
  }
}
```

**Expected behavior:**

Well in Typescript 3.3.4000 this is what got outputted. Notice how the `arguments` are *not* in the generator method in `mergeStringList()`

```js
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __values = (this && this.__values) || function (o) {
    var m = typeof Symbol === "function" && o[Symbol.iterator], i = 0;
    if (m) return m.call(o);
    return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
};
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spread = (this && this.__spread) || function () {
    for (var ar = [], i = 0; i < arguments.length; i++) ar = ar.concat(__read(arguments[i]));
    return ar;
};
function isIterable(i) {
    return Boolean(i && typeof i[Symbol.iterator] === "function");
}
function mergeStringLists() {
    var _i, e_1, _a, strings_1, strings_1_1, str, e_1_1;
    var strings = [];
    for (_i = 0; _i < arguments.length; _i++) {
        strings[_i] = arguments[_i];
    }
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                _b.trys.push([0, 8, 9, 10]);
                strings_1 = __values(strings), strings_1_1 = strings_1.next();
                _b.label = 1;
            case 1:
                if (!!strings_1_1.done) return [3 /*break*/, 7];
                str = strings_1_1.value;
                if (!(typeof str === "string")) return [3 /*break*/, 4];
                if (!str) return [3 /*break*/, 3];
                return [4 /*yield*/, str];
            case 2:
                _b.sent();
                _b.label = 3;
            case 3: return [3 /*break*/, 6];
            case 4:
                if (!isIterable(str)) return [3 /*break*/, 6];
                return [5 /*yield**/, __values(mergeStringLists.apply(void 0, __spread(str)))];
            case 5:
                _b.sent();
                _b.label = 6;
            case 6:
                strings_1_1 = strings_1.next();
                return [3 /*break*/, 1];
            case 7: return [3 /*break*/, 10];
            case 8:
                e_1_1 = _b.sent();
                e_1 = { error: e_1_1 };
                return [3 /*break*/, 10];
            case 9:
                try {
                    if (strings_1_1 && !strings_1_1.done && (_a = strings_1.return)) _a.call(strings_1);
                }
                finally { if (e_1) throw e_1.error; }
                return [7 /*endfinally*/];
            case 10: return [2 /*return*/];
        }
    });
}
```

**Actual behavior:**

In TS3.4.1 and beyond this is what is outputted. In the `mergeStringLists()` method, the `arguments` variable can be found inside the generator function which is the wrong set of arguments.

```js
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __values = (this && this.__values) || function (o) {
    var m = typeof Symbol === "function" && o[Symbol.iterator], i = 0;
    if (m) return m.call(o);
    return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
};
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spread = (this && this.__spread) || function () {
    for (var ar = [], i = 0; i < arguments.length; i++) ar = ar.concat(__read(arguments[i]));
    return ar;
};
function isIterable(i) {
    return Boolean(i && typeof i[Symbol.iterator] === "function");
}
function mergeStringLists() {
    var e_1, _a, _i, strings_1, strings_1_1, str, e_1_1;
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                var strings = [];
                for (_i = 0; _i < arguments.length; _i++) {
                    strings[_i] = arguments[_i];
                }
                _b.label = 1;
            case 1:
                _b.trys.push([1, 9, 10, 11]);
                strings_1 = __values(strings), strings_1_1 = strings_1.next();
                _b.label = 2;
            case 2:
                if (!!strings_1_1.done) return [3 /*break*/, 8];
                str = strings_1_1.value;
                if (!(typeof str === "string")) return [3 /*break*/, 5];
                if (!str) return [3 /*break*/, 4];
                return [4 /*yield*/, str];
            case 3:
                _b.sent();
                _b.label = 4;
            case 4: return [3 /*break*/, 7];
            case 5:
                if (!isIterable(str)) return [3 /*break*/, 7];
                return [5 /*yield**/, __values(mergeStringLists.apply(void 0, __spread(str)))];
            case 6:
                _b.sent();
                _b.label = 7;
            case 7:
                strings_1_1 = strings_1.next();
                return [3 /*break*/, 2];
            case 8: return [3 /*break*/, 11];
            case 9:
                e_1_1 = _b.sent();
                e_1 = { error: e_1_1 };
                return [3 /*break*/, 11];
            case 10:
                try {
                    if (strings_1_1 && !strings_1_1.done && (_a = strings_1.return)) _a.call(strings_1);
                }
                finally { if (e_1) throw e_1.error; }
                return [7 /*endfinally*/];
            case 11: return [2 /*return*/];
        }
    });
}
```

**Playground Link:** *Playground isn't updated yet.*

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
When transforming a generator function with a rest parameter for ES2015, we insert the `VariableStatement` we generate to hoist variables at the top of the resulting statement list after any standard prologues.

However, when we perform the generator transform, we move every node in the statement list after (and including) the first node not marked with `EmitFlags.CustomPrologue` into the generator state machine. Since the hoisted `VariableStatement` was not marked as a custom prologue, we would stop at that statement and would inadvertently move any trailing custom prologues.

This change marks the hoisted variable statement with `EmitFlags.CustomPrologue` since it is, in effect a custom prologue entry that we insert at the top of a function similar to rest argument handling, this parameter, capturing, etc.

Fixes #30653

### CODE REVIEW

File: src/compiler/transformers/es2015.ts [hunk 1]
```diff
@@ -1760,6 +1760,7 @@ namespace ts {
          * @param node a FunctionDeclaration node.
          */
         function visitFunctionDeclaration(node: FunctionDeclaration): FunctionDeclaration {
+            debugger;
```
Comment (weswigham) [inline src/compiler/transformers/es2015.ts]: ???

Comment (rbuckton) [reply src/compiler/transformers/es2015.ts]: Oops. :/

**Comment by weswigham** [comment]
> inadvertently move any trailing custom prologues.

Erm, can you give any examples that actually use prologue directives? Because in
```ts
"some prologue";
var _a;
"other prologue";
```
`"other prologue"` isn't _actually_ a prologue, since there's an intervening declaration; so I'm confused as to how we could ever get a variable declaration into the _middle_ of a prologue list.

**Comment by weswigham** [comment]
Unless ofc `EmitFlags.CustomPrologue` at this point actually has nothing to do with prologue directives, ofc, at which point it should probably be renamed to something like `EmitFlags.LexicallyStickyStatement` or something.

**Comment by rbuckton** [comment]
We consider any string-literal expression statement a "standard prologue" per `isPrologueDirective`.

**Comment by rbuckton** [comment]
@weswigham any other comments?

**Comment by sheetalkamat** [comment]
@rbuckton can you please wait on merge , I would like to look at this from —out scenario with prepend

File: tests/baselines/reference/asyncArrowFunction8_es5.js [hunk 2]
```diff
@@ -6,7 +6,8 @@ var foo = async (): Promise<void> => {
 //// [asyncArrowFunction8_es5.js]
 var _this = this;
 var foo = function () { return __awaiter(_this, void 0, void 0, function () {
-    var _a, v;
+    var v;
```
Comment (sheetalkamat) [inline tests/baselines/reference/asyncArrowFunction8_es5.js]: Interestingly combining these declaration into one looked much better.
