### PR TITLE
Complete `constructor` keyword after property declaration

### LINKED ISSUE #43650: Constructor keyword not suggested
# Bug Report

From https://github.com/microsoft/vscode/issues/120881

### 🔎 Search Terms

- suggest
- Intellisense 

### 🕗 Version & Regression Information

4.3.0-dev.20210412

### 💻 Code

```ts
// @ts-check

class Foo {
    abc;
    constructor(name) { }
}
```

Trigger suggest right after `constructor `

### 🙁 Actual behavior

A suggestion for the `constructor` keyword is returned.

### 🙂 Expected behavior
No such suggestion is included

### PR DESCRIPTION
**Pull request by z0gSh1u**
Fixes #43650
and more.

This is my first pull-request here. Help and suggestions are appreciated.

All these various situations are fixed, expanding the case in original issue:

- implicit any property, property with type, property with initializer...
- literal initializer, object initializer, array initializer, identifier initializer, function execution initializer...
- fully present `constructor`, partly present `constructor`, no presence...
- different semicolon styles...
- w/ or w/o semicolon or newline...
- and so on.

Please refer to the test case for detail:

`tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts`

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
This seems like an oddly-specific fix, and I'm not sure if it really identifiers the root problem. Why weren't we offering up completions before?

**Comment by z0gSh1u** [comment]
In my opinion, this is a missing case of getting completions during class declaration.

The function `tryGetObjectTypeDeclarationCompletionContainer` checks the `contextToken` to give a completion.
https://github.com/microsoft/TypeScript/blob/f74f9cac1344f6c88078c65d89a4d496bd5a8525/src/services/completions.ts#L2835

However, it doesn't consider the `implicit any` case like:
```ts
class Foo {
   bar; // <- context token
   constructor/**/()
}
```
since there is no switch-case for `contextToken` as an `Identifier`. So it fall back to `default`, and check the `contextToken` using
https://github.com/microsoft/TypeScript/blob/f74f9cac1344f6c88078c65d89a4d496bd5a8525/src/services/completions.ts#L2737

This function doesn't consider the situation that `contextToken` is an `Identifier` either (but does for `AsyncKeyword`), resulting an `undefined` (no suggestion) return for completions.

What's more, for case with a `TypeReference` like:
```ts
class Foo {
  bar: number // <- context token w/o semicolon
  consturctor/**/()
}
```
The completion is blocked by https://github.com/microsoft/TypeScript/blob/f74f9cac1344f6c88078c65d89a4d496bd5a8525/src/services/completions.ts#L1816
which is a different case from the previous one.

The fix for this is made referring to a similar issue:
https://github.com/microsoft/TypeScript/blob/f74f9cac1344f6c88078c65d89a4d496bd5a8525/src/services/completions.ts#L2377

**Comment by andrewbranch** [comment]
You need to actually check for an ASI-triggering newline if you want to prevent a completion at

```ts
class C {
  blah /*| constructor*/
}
```

I don’t know how important that is, though.

**Comment by z0gSh1u** [comment]
Hi, I'm not very sure of what you mean. I'm basically allowing instead of preventing completions. And the behavior for cursur at that position should be unchanged. Do these changes affect ASI in some way?

File: tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
+/// <reference path="fourslash.ts" />
+
+////class A {
+////  bla
+////  constructor/*1*/(props) {}
```
Comment (andrewbranch) [inline tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts:5]: The presence of the full `constructor` keyword is changing the behavior of the completions. It seems like what you really want to test is

```ts
class A {
  bla
  /**/
}
```

and

```ts
class A {
  bla
  co/**/
}
```

right? Those currently _don’t_ work.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts (hunk 1 above)
Comment (andrewbranch) [reply tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts:5]: We’ll have to revisit my comment about newlines after this issue is fixed—you’re right that the behavior is currently unchanged, but I think it’s because of this issue.

Comment (z0gSh1u) [reply tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts:5]: Got it. This is a more universal situation. And I've found that completions are not working either for snippet like this:

```ts
class C {
  blah = 123 // property with an immediate assignment
  constructor/**/
}
```

I'll take a deeper dive into these problems.

**Comment by z0gSh1u** [comment]
Updated. New fix available now.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
Ok, so this is what I meant about checking newlines: https://www.staging-typescript.org/play?ts=4.3.0-pr-43654-9#code/MYGwhgzhAEDC0G8BQ1oCNwAtrAPQCp9ckBfIA

If you trigger completions at the comment, you now get a completion for `constructor` which is invalid due to the lack of a semicolon or newline. Because of ASI, _either_ a semicolon or a newline makes `constructor` a valid next token, but it’s not valid here.

**Comment by z0gSh1u** [comment]
I've adopted a validation using newline or semicolon. The completions for these two cases are blocked now as the original behavior in 4.3.0-beta:

```ts
class A {
  blah /*|con*/
}
class B {
  blah: number /*|con*/
}
```

And `constructor` will not be suggested for this:

```ts
class C {
  blah
  /**/
}
```

since

```ts
class C {
  blah
   = 123
}
```

is legal. Unless user types a `c` at that position.

During the debugging, I've found another issue of property with an initializer that might be controversial. In 4.3.0-beta, completions of `private` / `protected` / `public` / `constructor` can be triggered like this:

```ts
class C {
  blah = blah /*|p*/
}
// PLAYGROUND: https://www.staging-typescript.org/play?jsx=0&ts=4.3.0-beta#code/MYGwhgzhAEDC0G8BQ1oCNwAtoF51egAcB6AKlOKQF8g
```

It looks unlike an intended one. But I'm not sure and haven't fix this since it is guaranteed by some test cases like `tests\cases\fourslash\completionsClassPropertiesAssignment.ts`.

File: src/services/completions.ts [hunk 2]
```diff
@@ -2370,6 +2370,24 @@ namespace ts.Completions {
                     return isPropertyDeclaration(contextToken.parent);
             }
 
+            function isPreviousPropertyDeclarationTerminated(contextToken: Node, previousToken: Node) {
+                return getLinesBetweenPositions(sourceFile, contextToken.end, previousToken.end) > 0 ||
+                    contextToken.kind === SyntaxKind.SemicolonToken;
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/completions.ts:2375]: Also, can you move this function declaration outside of the flow of its parent function? Our loosely-enforced convention is to put helper functions at the bottom of their parent, but it looks like this one could move outside of `isSolelyIdentifierDefinitionLocation` entirely.

File: src/services/completions.ts [hunk 3]
```diff
@@ -2831,6 +2849,27 @@ namespace ts.Completions {
...
+        // class c { prop: number \n constructor| }
+        // class c { prop = somewhat \n constructor| }
+        // and also for `;` replacing `\n`
+        if (location.kind === SyntaxKind.ConstructorKeyword && (
+            isIdentifier(contextToken) ||
+            isTypeKeyword(contextToken.kind) ||
+            isPropertyBeforeConstructorInitalized(getAncestor(location, SyntaxKind.ClassDeclaration) as ClassDeclaration, location.parent as ClassElement) ||
+            contextToken.kind === SyntaxKind.SemicolonToken
+        )) {
+            return getAncestor(contextToken, SyntaxKind.ClassDeclaration) as ObjectTypeDeclaration;
```
Comment (andrewbranch) [inline src/services/completions.ts:2870]: I _believe_ we will not produce a `ConstructorKeyword` outside a class (it will just be an `Identifier` if it appears), but the class node could be a `ClassExpression`, not only a `ClassDeclaration`.

File: src/services/completions.ts [hunk 4]
```diff
@@ -2831,6 +2849,27 @@ namespace ts.Completions {
...
+                return true;
+            }
+            return isInitializedProperty(classDecl.members[indexOfConstructor - 1]);
+        }
+
+        // class c { prop \n constructor| }
+        // class c { prop: number \n constructor| }
+        // class c { prop = somewhat \n constructor| }
+        // and also for `;` replacing `\n`
+        if (location.kind === SyntaxKind.ConstructorKeyword && (
```
Comment (andrewbranch) [inline src/services/completions.ts:2864]: It looks like this whole condition applies only once you’ve typed the entire `constructor` keyword, and stops applying as soon as you’ve typed the open parenthesis afterwards, which is not really a time when completions are likely to be triggered, or when they will be valuable. This might be technically correct, but I’m confused about what purpose it’s serving.

File: src/services/completions.ts [hunk 5]
```diff
@@ -2370,6 +2370,24 @@ namespace ts.Completions {
...
+                return getLinesBetweenPositions(sourceFile, contextToken.end, previousToken.end) > 0 ||
+                    contextToken.kind === SyntaxKind.SemicolonToken;
+            }
+
+            // If we are inside a class declaration and typing `constructor` after property declaration...
+            if (contextToken !== previousToken
+                && isClassLike(previousToken.parent.parent)
+                && isPropertyDeclaration(contextToken.parent)
+                // After considering different contextToken...
+                && (isIdentifier(contextToken) || isTypeKeyword(contextToken.kind))
```
Comment (andrewbranch) [inline src/services/completions.ts:2383]: Is this condition necessary/correct? If the previous property declaration has a type annotation or an initializer, there are lots of ways it might be something other than an identifier or type keyword. But those cases seem to work already... are we able to just drop this line?

File: tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+////   blah: number; con/*5*/
+//// }
+//// class F {
+////   blah = 123
+////   con/*6*/
+//// }
+//// class G {
+////   blah = 123; con/*7*/
+//// }
+//// // situations that `constructor` is fully present
```
Comment (andrewbranch) [inline tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts:29]: All of these are fine to have, and correct, but as far as I understand, essentially pointless. I don’t think they’re particularly important to test, and I definitely think that little to no implementation code should be written to make these cases pass.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (z0gSh1u) [reply src/services/completions.ts:2375]: Got it.
```diff
+ return contextToken.kind === SyntaxKind.SemicolonToken ||
+     !positionsAreOnSameLine(contextToken.end, previousToken.end, sourceFile);
      ^
```
exactly.

File: src/services/completions.ts (hunk 5 above)
Comment (z0gSh1u) [reply src/services/completions.ts:2383]: Correct. This is already supported by some other code. Cases like
```ts
type SomeType = number
class C {
  blah: SomeType; /**/
}
```
are already working in 4.3.0-beta.

File: tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+////   blah = return1()
+////   constructor/*16*/
+//// }
+//// // situations that `constructor` isn't present
+//// class Q {
+////   blah; /*17*/ 
+//// }
+//// class R {
+////   blah
+////   /*18*/ // dont complete since `blah \n = 123` is legal
```
[the remark this answers is not in the document]
Comment (z0gSh1u) [reply tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts:75]: That's right.

File: src/services/completions.ts (hunk 4 above)
Comment (z0gSh1u) [reply src/services/completions.ts:2864]: This is the fix for the most original issue. https://github.com/microsoft/TypeScript/issues/43650
Manually triggered completion (Ctrl+Space in Windows) doesn't offer `constructor` for this:
```ts
class C {
  blah // w/ w/o semicolon, type, initializer
  constructor/**/ // must be fully present
}
```
The cause seems to be a missing case in `tryGetObjectTypeDeclarationCompletionContainer`.

File: src/services/completions.ts (hunk 3 above)
Comment (z0gSh1u) [reply src/services/completions.ts:2870]: Got it.

File: tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts (hunk 6 above)
Comment (z0gSh1u) [reply tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts:29]: Kindly refer to https://github.com/microsoft/TypeScript/pull/43654#discussion_r619398932 maybe.

File: src/services/completions.ts (hunk 4 above)
Comment (andrewbranch) [reply src/services/completions.ts:2864]: I think I disagree with the premise that #43650 is worth more than a line of code to fix. From the original issue opened against VS Code, it looks like someone was just hunting for inconsistencies, not experiencing a legitimate UX issue. I’m not against fixing it, but I am against fixing it if no one can explain why it matters and it takes a multiline `if` statement, a bunch of explanatory comments, and a dozen fourslash tests.

Comment (z0gSh1u) [reply src/services/completions.ts]: :laughing: Yep. The latest fix is of 4 LOC.

**Comment by z0gSh1u** [comment]
`constructor` should not but is now still suggested at:
```ts
class T {
  blah: number con/**/
}
const SomeConst = 123
class U {
  blah = SomeConst con/**/
}
```
I'm still working on this.

**Comment by andrewbranch** [comment]
The simplifications are looking great. Let me know when you’re ready for another review. Thanks!

**Comment by z0gSh1u** [comment]
The fix should be all-rounded and reliable enough now. Please refer to the test case:

https://github.com/microsoft/TypeScript/blob/70adf96ed0b9445ec0468ff038588247f87a7c81/tests/cases/fourslash/completionConstructorKeywordAfterPropertyDeclaration.ts

for detail.

What's more, we've got a byproduct that, for 15-21 in the test case of situations that constructor should not be suggested, completions for private / public / protected are also blocked, which should be reasonable. (See https://github.com/microsoft/TypeScript/pull/43654#issuecomment-825549637)

At last, kindly ping @andrewbranch .

File: src/services/completions.ts [hunk 8]
```diff
@@ -2370,6 +2370,31 @@ namespace ts.Completions {
                     return isPropertyDeclaration(contextToken.parent);
             }
 
+            // If `constructor` is totally not present, but we request a completion manually at a space...
+            if (contextToken === previousToken && isPreviousPropertyDeclarationTerminated(contextToken, position)) {
+                return false; // Don't block completions.
```
Comment (andrewbranch) [inline src/services/completions.ts:2375]: Do we even know that the current location is in a class right here?

Comment (z0gSh1u) [reply src/services/completions.ts:2375]: Agree. Narrowing this fix to be inside a `ClassLike` should be more reliable.

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by z0gSh1u** [comment]
Thanks for your help. Have a nice day!
