### PR TITLE
fix(45221): Unresolved import aliases are not suggested in type positions

### LINKED ISSUE #45221: Unresolved import aliases are not suggested in type positions
```ts
import { ThisDoesNotExist } from "module-that-does-not-exist ;o";

let x: /**/
```

Request completions at `/**/`

**Expected**: `ThisDoesNotExist` is provided as a completion item.
**Actual**: `ThisDoesNotExist` is **not** in the completion list.

Basically we have some filtering in our completion list logic that says that if we're pretty certain that we're in a type position, then  only provide completions for types. This works great unless you end up with an alias (`ThisDoesNotExist`) to a module that hasn't resolved to anything.

This is kind of a pain if you're in a partial-semantic context, where only the files that are open in the editor can be analyzed. For that reason, in cases where an import hasn't resolved to anything, it makes sense to keep it in the completion list.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45221

### CODE REVIEW

**Review by gabritto — APPROVED** [review]
looks good, thanks.

File: src/services/completions.ts [hunk 1]
```diff
@@ -3309,10 +3309,9 @@ namespace ts.Completions {
     /** True if symbol is a type or a module containing at least one type. */
     function symbolCanBeReferencedAtTypeLocation(symbol: Symbol, checker: TypeChecker, seenModules = new Map<SymbolId, true>()): boolean {
```
Comment (gabritto) [inline src/services/completions.ts:3310]: @andrewbranch I think you worked on this and related functions not long ago.  As far as I can tell it's all looking good, but if you want to take a look, this change impacts the caller functions `getTypeScriptMemberSymbols` and `shouldIncludeSymbol` (called by `getCompletionEntriesFromSymbols` to filter out symbols), in completions.

**Review by andrewbranch — APPROVED** [review]
