### PR TITLE
fix: const enums + isolatedModules emit invalid code

### LINKED ISSUE #40499: const enum imports are stripped even with isolatedModules
First of all, `isolatedModules` seems to imply `preserveConstEnums` but it doesn't look like this is documented: https://www.typescriptlang.org/tsconfig#isolatedModules.

---

Repro:

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "isolatedModules": true
  }
}
```
`temp2.ts`:
```ts
export const enum a {
  b = 1,
  c = 2,
};
```
`temp.ts`:
```ts
import { a } from "./temp2";
console.log(a.b);
```

---

`temp2.js` (enum is generated, so `preserveConstEnums` is implied?):
```js
export var a;
(function (a) {
    a[a["b"] = 1] = "b";
    a[a["c"] = 2] = "c";
})(a || (a = {}));
;
```

`temp.js` (the import is left out, even though no inlining is done??):
```js
console.log(a.b);
export {};
```
This module is invalid and will throw a reference error at runtime. Expected the import from the TS source to be preserved.

---

I've checked that the same thing will happen with `preserveConstEnums` specified explicitly. The equivalent issue occurs without `"target": "esnext"`.

Version 3.8.3.

Ref https://github.com/denoland/deno/issues/7326#issuecomment-691190964.

cc @bartlomieju @lucacasonato @kitsonk

### PR DESCRIPTION
**Pull request by FauxFaux**
In `isolatedModules` mode, the compiler does not inline const enums, but also decides not to `import` them, leaving invalid code that throws a `ReferenceError` at runtime.

This code:

```ts
import { SomeEnum } from './bar';
sink(SomeEnum.VALUE);
```

..should compile to either:

```js
var { SomeEnum } = require('./bar');
sink(SomeEnum.VALUE);
```

..or (with const enum inlining):

```js
sink(1 /* VALUE */);
```

..but actually compiles to:
```js
sink(SomeEnum.VALUE);
```

..with no imports, which throws a ReferenceError at runtime.

---

The compiler has already realised that the symbol is a referenced const enum, it just doesn't use this information when it comes to deciding whether to emit an import. This commit additionally checks that information, if we are compiling in isolatedModules mode.

---

In my opinion, this is not the correct fix, but it is the simplest. In `isolatedModules` mode, `const enum` should probably be a compile error (because there are no benefits and the complexity is high, and, apparently, buggy). If not, the compiler should not be checking whether something is a const enum, and should just be treating it as a regular enum, and checking as if it was?

Fixes #40499.

### CODE REVIEW

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Can we add a test for only using the type side of a const enum too? Like

```ts
// @isolatedModules: true

// @Filename: /enum.ts
export const enum Foo { Bar }

// @Filename: /index.ts
import { Foo } from "./enum";
function f(foo: Foo) { return; }
```

**Comment by andrewbranch** [comment]
I think it’s worth considering adding an error too, but that can be done separately. I see no reason not to take this fix regardless of whether we add an error in the future.

**Comment by FauxFaux** [comment]
That test is simple enough, and does what I expect (the import, which is only used in type context, is deleted). It doesn't even run the new code. Added.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -38211,7 +38211,8 @@ namespace ts {
         function isReferencedAliasDeclaration(node: Node, checkChildren?: boolean): boolean {
             if (isAliasSymbolDeclaration(node)) {
                 const symbol = getSymbolOfNode(node);
-                if (symbol && getSymbolLinks(symbol).referenced) {
+                const links = symbol && getSymbolLinks(symbol);
+                if (links?.referenced || (compilerOptions.isolatedModules && links?.constEnumReferenced)) {
```
Comment (sheetalkamat) [inline src/compiler/checker.ts:38215]: This is incorrect fix. without `preserveConstEnums` alias is not treated as imported . the fix should be to error instead.

Comment (sheetalkamat) [reply src/compiler/checker.ts:38215]: Wait isolatedModules is suppose to treat it as `preserveConstEnums` ? 
We have descripency in how we handle thsese two flags and that should be fixed instead

Comment (andrewbranch) [reply src/compiler/checker.ts:38215]: Yeah, see https://github.com/microsoft/TypeScript/blob/9dfbf07d8a63a8d6145cb67aa33d7486ad176152/src/compiler/transformers/ts.ts#L2317-L2321. I didn’t realize that either until #40499 pointed it out, but it seems to be intentional. That’s why I think this fix is ok, and making it an error needs a discussion. It seems weird, but there could be people relying on this behavior.

Comment (sheetalkamat) [reply src/compiler/checker.ts:38215]: i think this fix is not ok.. We should may be have function preserverConstEnums(options) = options.preserveConstEnums || options.isolatedModules;  and use it everywhere we intend to use options.preserverConstEnum to ensure that all the flag setting take place in either mode.

Comment (sheetalkamat) [reply src/compiler/checker.ts:38215]: Eg,. markAliasReferenced needs to handle that. that would be correct fix

Comment (andrewbranch) [reply src/compiler/checker.ts:38215]: Yes, that would be a good addition.

Comment (andrewbranch) [reply src/compiler/checker.ts:38215]: We also need a config error for `--isolatedModules` combined with `--preserveConstEnums=false`

Comment (FauxFaux) [reply src/compiler/checker.ts]: I've pushed a commit which adds the config error.

I don't know anything about the config system, or even really the compiler (I'm only here because this bug caused an outage), but.. would it not be easier to make `isolatedModules` just imply `--preserveConstEnums=true` at the config level, and leave everything else alone? There's a lot of references to both options, and some of them aren't obviously correct either way around.

Comment (andrewbranch) [reply src/compiler/checker.ts]: We tend not to make `compilerOptions` belie the actual config in case there’s a need to separate out what options the user actually specified later. I already searched through every usage of `preserveConstEnums` and verified they can pretty much all be replaced with `getPreserveConstEnums(compilerOptions)`. Note we do the same thing with `getAllowSyntheticDefaultImports(compilerOptions)`, `getEmitDeclarations(compilerOptions)`, and several others.

Comment (FauxFaux) [reply src/compiler/checker.ts]: Okay, understood.

Do you want me to have a go too, or do you have a commit to push?

Comment (andrewbranch) [reply src/compiler/checker.ts]: I don’t have a commit—if you want to do it, awesome; if this is getting to be more than you signed up for, I can finish it out.

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -3789,6 +3789,10 @@
         "category": "Error",
         "code": 5090
     },
+    "Option 'isolatedModules' requires 'preserveConstEnum', as constants are not inlined in this mode.": {
```
Comment (andrewbranch) [inline src/compiler/diagnosticMessages.json:3792]:
```suggestion
    "Option 'preserveConstEnums' cannot be disabled when 'isolatedModules' is enabled.": {
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (FauxFaux) [reply src/compiler/checker.ts]: I've pushed that change, which doesn't seem to break any tests, and isn't sufficient to fix my new tests; we still need the other commits.

File: src/compiler/program.ts [hunk 3]
```diff
@@ -3156,6 +3156,10 @@ namespace ts {
                     createDiagnosticForOptionName(Diagnostics.Option_isolatedModules_can_only_be_used_when_either_option_module_is_provided_or_option_target_is_ES2015_or_higher, "isolatedModules", "target");
                 }
 
+                if (options.preserveConstEnums === false) {
+                    createDiagnosticForOptionName(Diagnostics.Option_preserveConstEnums_cannot_be_disabled_when_isolatedModules_is_enabled, "preserveConstEnums", "isolatedModules");
```
Comment (andrewbranch) [inline src/compiler/program.ts:3160]: Let’s get a test that shows this, and then we should be good to go. Thanks!

Comment (FauxFaux) [reply src/compiler/program.ts:3160]: I added a "compiler" test, because I couldn't find any other ways to test command line arguments, and/or I couldn't get any of the other test frameworks to work.

**Review by andrewbranch — APPROVED** [review]
Thanks @FauxFaux!

**Comment by sandersn** [comment]
@andrewbranch @sheetalkamat is this ready to go in? From the comment history, it looks like @sheetalkamat 's comments were addressed and @andrewbranch reviewed them, but I want to make sure before merging.

**Comment by andrewbranch** [comment]
I believe it’s ready, just wanted another team member to review.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -38263,13 +38263,14 @@ namespace ts {
...
```
Comment (sheetalkamat) [inline src/compiler/checker.ts:38267]: I am not sure why this change is needed ? Replacing `shouldPreserveConstEnums` instead of `options.preserveConstEnums` should mark things correctly if not why is it not a issue with preserveConstEnums? Does necessity of this change means somewhere we are not using `shouldPreserveConstEnums`

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 4 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:38267]: I missed this—I think it may be left over from before and could be changed now. @FauxFaux?

Comment (FauxFaux) [reply src/compiler/checker.ts:38267]: This is still the actual bug fix, the only code that needed to be changed.

`--preserveConstEnums` stops the compiler deleting the enum definition (but still inlines uses)
`--isolatedModules` prevents the inlining of the const enum, so requires the enum definition to be not deleted, *and* the reference imported?

This line implements the "and imported" fix.

On the released compiler:

```
% tsc --version
Version 4.1.3
```

### inlined
```
% tsc --target es2018 file1.ts; head -n 10 file?.js
==> file1.js <==
console.log(0 /* BAR */);
export {};

==> file2.js <==
export {};
```

### still inlined
```
% tsc --preserveConstEnums file1.ts; head -n 10 file?.js
==> file1.js <==
"use strict";
exports.__esModule = true;
console.log(0 /* BAR */);

==> file2.js <==
"use strict";
exports.__esModule = true;
exports.Foo = void 0;
var Foo;
(function (Foo) {
    Foo[Foo["BAR"] = 0] = "BAR";
})(Foo = exports.Foo || (exports.Foo = {}));
```

### not inlined but not imported
```
% tsc --isolatedModules file1.ts; head -n 10 file?.js   
==> file1.js <==
"use strict";
exports.__esModule = true;
console.log(file2_1.Foo.BAR);

==> file2.js <==
"use strict";
exports.__esModule = true;
exports.Foo = void 0;
var Foo;
(function (Foo) {
    Foo[Foo["BAR"] = 0] = "BAR";
})(Foo = exports.Foo || (exports.Foo = {}));
```

This PR behaves exactly like the released compiler if you take this hunk out.

(The relevant decision appears to be inside `markAliasReferenced` on a five digit line number in `checker.ts`, a file so big I apparently can't link to it, and can barely edit.)

Comment (sheetalkamat) [reply src/compiler/checker.ts:38267]: `isolatedModules` should behave exactly like `preserveConstEnums`

Comment (andrewbranch) [reply src/compiler/checker.ts:38267]: IIUC `isolatedModules` should behave like a _superset_ of `preserveConstEnums`—`preserveConstEnums` doesn’t prevent the inlining of const enum values, it only prevents the erasure of the declaration. `isolatedModules` must do both. Or in other words, `isolatedModules` is the _only_ option that prevents the inlining of const enums. Therefore, for a const enum alias to be considered referenced, it _must_ be referenced under `isolatedModules`. This line is correct—sorry it took me a minute to remember the nuances after the holidays 😅

Comment (FauxFaux) [reply src/compiler/checker.ts:38267]: Yes, that's what I was trying to say! :+1:

Comment (sheetalkamat) [reply src/compiler/checker.ts:38267]: If thats the case this is not the correct place to fix it ? shouldnt it be handled in `checkPropertyAccessExpressionOrQualifiedName` when isolatedModules is set

Comment (sheetalkamat) [reply src/compiler/checker.ts:38267]: `constEnumReferenced` is for typeonly imports and shouldnt be mixed

Comment (andrewbranch) [reply src/compiler/checker.ts:38267]: Hmm, I forgot I did add that property for the purpose of type-only imports, but I think it’s a reasonably good fit for this. But it may make just as much sense to mark const enum aliases as `referenced`, not just `constEnumReferenced`, under `isolatedModules` in `markAliasReferenced`.

That said, the condition in `checkPropertyAccessExpressionOrQualifiedName` probably does cause a bug in this implementation, though, so that will need to be addressed one way or another. `tests/cases/compiler/constEnumNamespaceReferenceCausesNoImport.ts` should be duplicated and tested under `isolatedModules` as well.

Comment (andrewbranch) [reply src/compiler/checker.ts:38267]: (Instead of duplicating, you can add `// @isolatedModules: true,false` to the top)

Comment (FauxFaux) [reply src/compiler/checker.ts:38267]: That test is indeed bad under isolatedModules:true.

I do not understand any of the other methods you referenced, so I am not intending to make any further changes to this PR.

File: tests/baselines/reference/constEnumNamespaceReferenceCausesNoImport2.js [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+    var ConstFooEnum;
+    (function (ConstFooEnum) {
+        ConstFooEnum[ConstFooEnum["Some"] = 0] = "Some";
+        ConstFooEnum[ConstFooEnum["Values"] = 1] = "Values";
+        ConstFooEnum[ConstFooEnum["Here"] = 2] = "Here";
+    })(ConstFooEnum = ConstEnumOnlyModule.ConstFooEnum || (ConstEnumOnlyModule.ConstFooEnum = {}));
+})(ConstEnumOnlyModule = exports.ConstEnumOnlyModule || (exports.ConstEnumOnlyModule = {}));
+//// [reexport.js]
+"use strict";
+var Foo = require("./foo");
```
Comment (andrewbranch) [inline tests/baselines/reference/constEnumNamespaceReferenceCausesNoImport2.js:40]: A bit of a separate bug, but closely inspecting `checkPropertyAccessExpressionOrQualifiedName` led me to discover that this import was missing until I added the check for `isExportOrExportExpression`.

**Review by sheetalkamat — APPROVED** [review]

**Comment by andrewbranch** [comment]
Thanks @FauxFaux! Sorry this ended up being more complicated than you bargained for 😅
