### PR TITLE
fix(48445): import { type X } not flagged in JavaScript

### LINKED ISSUE #48445: import { type X } not flagged in JavaScript
# Bug Report

### 🔎 Search Terms

import type javascript error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?filetype=js#code/PTAEDkHsBdQMwDYEMDmKCmATAUASwLYAOkATrAN6jQCeh6oAwpEZAHbqvQAqt9AvvBLNQAchLokAY2giA3NhCgAYsjRY8LMlV6hKAJQnSomfoOFjDM+UA)

### 💻 Code

```ts
// Not flagged
import { type ComponentType } from 'react';
// Flagged
import type { ReactNode } from 'react';
```

### 🙁 Actual behavior

`import { type X }` is not flagged as "can only be used in TypeScript files" but crashes at runtime

### 🙂 Expected behavior

It should be an error

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #48445

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -2273,6 +2273,13 @@ namespace ts {
                                 return "skip";
                             }
                             break;
+                        case SyntaxKind.ImportSpecifier:
+                        case SyntaxKind.ExportSpecifier:
+                            if ((node as ImportOrExportSpecifier).isTypeOnly) {
+                                diagnostics.push(createDiagnosticForNode(node, Diagnostics._0_declarations_can_only_be_used_in_TypeScript_files, getSourceTextOfNodeFromSourceFile(sourceFile, node)));
```
Comment (DanielRosenwasser) [inline src/compiler/program.ts:2279]:
```suggestion
                                diagnostics.push(createDiagnosticForNode(node, Diagnostics._0_declarations_can_only_be_used_in_TypeScript_files, node.kind === SyntaxKind.ImportSpecifier ? "import...type" : "export...type");
```

**Review by DanielRosenwasser — APPROVED** [review]
