### PR TITLE
Fix alias naming and structure bugs in js declarations

### LINKED ISSUE #33626: JS declarations for an export assigned class expression can conflict with local names
Per [this comment](https://github.com/microsoft/TypeScript/pull/32372#discussion_r328390227) on the PR, the JS declaration emitter currently has a known issue where an export assigned class expression with a name can cause a conflict with another named declaration in the file and produce an invalid declaration file.

So, for example, this:
```ts
class A { member = new Q(); };
class Q { x = 12 };
module.exports = class Q { x = new A(); }
```
currently emits along the lines of
```ts
declare class A { member: Q; };
declare class Q { x: number };
declare class Q { x: A; }
exports = Q;
```
(because it reused the anonymous class's name for the hoisted class declaration) which isn't quite right.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #33626

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5333,29 +5344,40 @@ namespace ts {
...
+                    const members = getNamespaceMembersForSerialization(symbol);
                     // Split NS members up by declaration - members whose parent symbol is the ns symbol vs those whose is not (but were added in later via merging)
                     const locationMap = arrayToMultiMap(members, m => m.parent && m.parent === symbol ? "real" : "merged");
                     const realMembers = locationMap.get("real") || emptyArray;
                     const mergedMembers = locationMap.get("merged") || emptyArray;
                     // TODO: `suppressNewPrivateContext` is questionable -we need to simply be emitting privates in whatever scope they were declared in, rather
-                    // than whatever scope we traverse to them in. That's a bit of a complex rewrite, since we're not _actually_ tracking privates at all in advance,
+                    // than whatever scope we traverse to them in. That's a bit ofgetUnusedName a complex rewrite, since we're not _actually_ tracking privates at all in advance,
```
Comment (sandersn) [inline src/compiler/checker.ts]: ???
```suggestion
                    // than whatever scope we traverse to them in. That's a bit of a complex rewrite, since we're not _actually_ tracking privates at all in advance,
```

**Comment by weswigham** [comment]
@sandersn one more line of change and an additional test for that new case~

**Comment by weswigham** [comment]
@typescript-bot pack this again just cuz

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this into release-3.7
