### PR TITLE
Fix #5430: Use FileMap to store file list in tsserver

### LINKED ISSUE #5430: TypeScript language service breaks down when wrong casing is used for imports
Copied from: https://code.visualstudio.com/Issues/Detail/20178

I was experiencing a bizarre issue where the TS language service broke down and wouldn't underline errors in my code. After pulling my hair out for half an hour, I figured out it was because I was doing a file import with the wrong case e.g.

import Engine from "./Engine"

instead of

import Engine from "./engine"

The default class exported was named 'Engine' which I think might have also had something to do with it.

Open the attached folder in VS Code, then pick the "engine.ts" file and notice that there is an undefined symbol ("jjj_this_is_an_error") that is not red underlined.

I would expect a better error on the erroneous import instead of the imported file no longer having proper language services. :)

### PR DESCRIPTION
**Pull request by mhegazy**
Fixes #5430

### CODE REVIEW

File: src/server/editorServices.ts [hunk 1]
```diff
@@ -386,7 +384,7 @@ namespace ts.server {
         }
 
         getFileNames() {
-            let sourceFiles = this.program.getSourceFiles();
+            var sourceFiles = this.program.getSourceFiles();
```
Comment (vladima) [inline src/server/editorServices.ts]: Should stay as `let`.

Comment (mhegazy) [inline src/server/editorServices.ts]: i will get this in a different change in master.

**Comment by vladima** [comment]
:+1:
