### PR TITLE
Handle different default export forms the same way in import code fixes

### LINKED ISSUE #19115: Import hints not working when using export default after class definition
_From @methyl on October 10, 2017 7:25_

- VSCode Version: 1.17.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Open a JS project with `jsconfig.json` having checkJs: true in compilerOptions
2. Create a `test.js` with following content:
```js
class Test {}
export default Test
```
3. Create a `test2.js` with following content:
```js
class Test2 extends Test {}
```

Actual behavior:
- No lightbulb with hint to `import Test from './test` appear.

Correct behavior
- Lightbulb with hint to `import Test from './test` appear, just like when `test.js` have `export default` inlined:
```
export default class Test {}
```

_Copied from original issue: Microsoft/vscode#35966_

### PR DESCRIPTION
**Pull request by amcasey**
`export default C` and `export { C as default }` should be handled the same as `export default class C { }`.

Fixes #19115

### CODE REVIEW

File: src/services/rename.ts [hunk 1]
```diff
@@ -38,9 +38,17 @@ namespace ts.Rename {
                     return undefined;
                 }
 
-                const displayName = stripQuotes(getDeclaredName(typeChecker, symbol, node));
                 const kind = SymbolDisplay.getSymbolKind(typeChecker, symbol, node);
-                return kind ? getRenameInfoSuccess(displayName, typeChecker.getFullyQualifiedName(symbol), kind, SymbolDisplay.getSymbolModifiers(symbol), node, sourceFile) : undefined;
+                if (!kind) {
```
Comment (andy-ms) [inline src/services/rename.ts]: This change could use a test.

File: tests/cases/fourslash/importNameCodeFixDefaultExport2.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
+/// <reference path="fourslash.ts" />
+
+// @allowJs: true
```
Comment (andy-ms) [inline tests/cases/fourslash/importNameCodeFixDefaultExport2.ts]: Is it necessary that this test be JS? Should work exactly the same in TS?

File: src/services/findAllReferences.ts [hunk 3]
```diff
@@ -510,6 +510,8 @@ namespace ts.FindAllReferences.Core {
         /** @param allSearchSymbols set of additinal symbols for use by `includes`. */
         createSearch(location: Node, symbol: Symbol, comingFrom: ImportExport | undefined, searchOptions: { text?: string, allSearchSymbols?: Symbol[] } = {}): Search {
             // Note: if this is an external module symbol, the name doesn't include quotes.
+            // Note: getLocalSymbolForExportDefault handles `export default class C {}`, but not `export default C` or `export { C as default }`.
+            // The other two forms seem to be handled downstream (i.e. special-casing the first form here appears to be intentional).
```
Comment (andy-ms) [inline src/services/findAllReferences.ts]: This may be because we don't get a default export alias symbol here. See for example `skipPastExportOrImportSpecifier`.

File: src/services/codefixes/importFixes.ts [hunk 4]
```diff
@@ -784,6 +787,24 @@ namespace ts.codefix {
                 const symbolId = getUniqueSymbolId(exportSymbolWithIdenticalName, checker);
                 symbolIdActionMap.addActions(symbolId, getCodeActionForImport(moduleSymbol, { ...context, kind: ImportKind.Named }));
             }
+
+            function getEscapedNameForExportDefault(symbol: Symbol): __String | undefined {
+                const declarations = symbol.declarations;
+                if (length(declarations) > 0) {
```
Comment (andy-ms) [inline src/services/codefixes/importFixes.ts]: Might was well `return firstDefined(symbol.declarations, declaration => ...`

File: tests/cases/fourslash/importNameCodeFixDefaultExport2.ts (hunk 2 above)
Comment (amcasey) [reply tests/cases/fourslash/importNameCodeFixDefaultExport2.ts]: This test matches the repro steps in the bug.  If a TS test would be preferable, I can change it (it should be equivalent).

File: src/services/rename.ts (hunk 1 above)
Comment (amcasey) [reply src/services/rename.ts]: We don't have a good way to test that it shows up in the right place in the UI, but I can try to add a lower-level test of the rename info.

File: src/services/codefixes/importFixes.ts (hunk 4 above)
Comment (amcasey) [reply src/services/codefixes/importFixes.ts]: That's not equivalent, is it?  It'll check subsequent declarations if the lambda returns `undefined` for the first one?

File: src/services/findAllReferences.ts (hunk 3 above)
Comment (amcasey) [reply src/services/findAllReferences.ts]: Supplemented the comment with that information.

File: src/services/codefixes/importFixes.ts (hunk 4 above)
Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: You're right, it's not exactly equivalent, but I don't think it hurts to loop through declarations (and there is usually only one).

File: src/services/rename.ts (hunk 1 above)
Comment (andy-ms) [reply src/services/rename.ts]: Just to clarify, what is the expected change to rename behavior due to this PR?

Comment (amcasey) [reply src/services/rename.ts]: Different strings are displayed in VS dialogs.  No impact on renaming.

Comment (andy-ms) [reply src/services/rename.ts]: There must be some function that returns a different value than before in some situation?

Comment (amcasey) [reply src/services/rename.ts]: Yes, of course.  And I believe I've found a fourslash helper for testing it.  I just meant that the same user actions would result in the same result (i.e. renaming) after the change.

File: src/services/codefixes/importFixes.ts (hunk 4 above)
Comment (amcasey) [reply src/services/codefixes/importFixes.ts]: And the advantage is removing one bounds check?

File: tests/cases/fourslash/importNameCodeFixDefaultExport2.ts (hunk 2 above)
Comment (andy-ms) [reply tests/cases/fourslash/importNameCodeFixDefaultExport2.ts]: If it's exactly the same with these lines removed I would do that.

File: src/services/codefixes/importFixes.ts (hunk 4 above)
Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: If you like it this way that's fine, I just find it suspicious when we depend on `declarations[0]` being something particular, although that should be work in this case since the symbol for an export assignment or export specifier should always have exactly one declaration.

Comment (amcasey) [reply src/services/codefixes/importFixes.ts]: I can check that the length is one if that would be more robust.

File: tests/cases/fourslash/importNameCodeFixDefaultExport2.ts (hunk 2 above)
Comment (amcasey) [reply tests/cases/fourslash/importNameCodeFixDefaultExport2.ts]: Assuming you also meant to update the file extensions (so that diagnostics are produced at all), it would still not be exactly the same since the suppression fixes would not be offered (though that distinction is not important to the test/change).

File: src/services/codefixes/importFixes.ts (hunk 4 above)
Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: I don't think that's necessary, it shouldn't really matter whether it has other declarations or not.

File: tests/cases/fourslash/importNameCodeFixDefaultExport2.ts (hunk 2 above)
Comment (andy-ms) [reply tests/cases/fourslash/importNameCodeFixDefaultExport2.ts]: Yeah, I agree it's OK to remove the JS-specific suppression codefixes from this test since that's not what the point of the test is.

File: tests/cases/fourslash/importNameCodeFixDefaultExport3.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
+/// <reference path="fourslash.ts" />
+
+// @allowJs: true
```
Comment (andy-ms) [inline tests/cases/fourslash/importNameCodeFixDefaultExport3.ts]: This doesn't really need to be a JS test, right?

Comment (amcasey) [reply tests/cases/fourslash/importNameCodeFixDefaultExport3.ts]: While I can no longer recall my original motivation, it appears to be a JS version of the TS test in `importNameCodeFixDefaultExport2.ts`.

Comment (andy-ms) [reply tests/cases/fourslash/importNameCodeFixDefaultExport3.ts]: Well, I don't think we need the same test twice -- the same services code will be tested either way.
