### PR TITLE
Fix error messeage

### LINKED ISSUE #20585: Give better error message on consecutive numeric separators
From https://github.com/Microsoft/TypeScript/pull/20324#discussion_r155889852, and contingent on #20324 first getting merged.

```ts
let x = 123__456;
```

Note the double underscores.

Actual: `Numeric separators are not allowed here.`

* `A numeric literal cannot contain multiple consecutive separators.`
* `Multiple consecutive numeric separators are not permitted.`

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
Fixes #20585

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
LGTM, can you take a look @weswigham?

File: src/compiler/scanner.ts [hunk 1]
```diff
@@ -1287,13 +1299,19 @@ namespace ts {
...
+            let isPreviousTokenSeparator = false;
             while (true) {
                 const ch = text.charCodeAt(pos);
                 // Numeric seperators are allowed anywhere within a numeric literal, except not at the beginning, or following another separator
                 if (ch === CharacterCodes._) {
                     tokenFlags |= TokenFlags.ContainsSeparator;
                     if (separatorAllowed) {
                         separatorAllowed = false;
+                        isPreviousTokenSeparator = true;
+                    // tslint:disable-next-line:next-line
```
Comment (weswigham) [inline src/compiler/scanner.ts]: Why is there a lint rule disabled here?

Comment (YuichiNukiyama) [reply src/compiler/scanner.ts]: Simple mistake. I remove extra lint.
