### PR TITLE
Don’t offer `this.` completions on `self`, `window`, `global`, `globalThis`. Disambiguate `this.` completions from others in details requests.

### LINKED ISSUE #37091: Method added to `window` prefer using `this.` for console and other global properties
Issue Type: <b>Bug</b>

I'm not the only one with this issue, someone else pointed it out [on Reddit 7 months ago ](https://www.reddit.com/r/vscode/comments/cjoe4u/vs_code_adds_this_to_consolelog_and_it_kills_me/) but I haven't been able to find a report on here. Here's me reproducing it with no extensions on:

[LawfulHealthyDugong](https://gfycat.com/lawfulhealthydugong)
LawfulHealthyDugong

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.49GB free)|
|Process Argv|E:\code\cloverleaf\web\cloverleaf.code-workspace|
|Screen Reader|no|
|VM|0%|

### LINKED ISSUE #37651: Completion details are wrong for 'this.' member when a global exists by the same name
We allow a global and a `this.`-inserting completion by the same name to coexist, but they aren’t disambiguated in the details request, so we return the global’s details for both entries.

Kapture 2020-03-26 at 17 18 49

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37091
Fixes #37651

#37091 is interesting, because it exposes that the symbols for, say, `console` and `window.console` are completely different symbols that just happen to have the same type. There’s really no way to know generally that a member on a given `this` type is _actually_ the same thing as a symbol that’s declared globally. And as far as I can tell, there’s nothing special in the type system about symbols like `window`, `self`, or `global`, so there’s no mechanism to determine that a given type _is_ the global object type.

So, I’ve introduced a special case heuristic to reject `this.` completions when the `this` type is the type of a global by the name `self`, `global`, or `globalThis`. It’s possible to construct a strange environment for yourself where this is wrong, but the stakes are fairly low—you won’t get `this.`-inserting completions in methods on that type.

I also discovered and fixed #37651 along the way.

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -429,7 +435,12 @@ namespace ts.Completions {
     }
 
     function getSourceFromOrigin(origin: SymbolOriginInfo | undefined): string | undefined {
-        return origin && originIsExport(origin) ? stripQuotes(origin.moduleSymbol.name) : undefined;
+        if (originIsExport(origin)) {
+            return stripQuotes(origin.moduleSymbol.name);
+        }
+        if (origin?.kind === SymbolOriginInfoKind.ThisType) {
+            return "" + SymbolOriginInfoKind.ThisType;
+        }
```
[the remark this answers is not in the document]
Comment (amcasey) [reply src/services/completions.ts]: @uniqueiniquity Might have thoughts too.

File: src/services/completions.ts [hunk 2]
```diff
@@ -52,6 +52,11 @@ namespace ts.Completions {
         return !!(origin.kind & SymbolOriginInfoKind.Nullable);
     }
 
+    interface UniqueNameSet {
+        add(name: string): void;
```
Comment (amcasey) [inline src/services/completions.ts]: Some collection types return a boolean from insertion indicating whether the collection was updated.  This has the advantage that you can add-if-not-present in a single call.

File: src/services/completions.ts [hunk 3]
```diff
@@ -11,7 +11,7 @@ namespace ts.Completions {
     }
     export type Log = (message: string) => void;
 
-    const enum SymbolOriginInfoKind {
+    export const enum SymbolOriginInfoKind {
```
Comment (amcasey) [inline src/services/completions.ts]: If this is exported just for tests, should it be internal?

File: src/harness/fourslashImpl.ts [hunk 4]
```diff
@@ -334,6 +342,14 @@ namespace FourSlash {
                 if (!compilationOptions.noLib) {
                     this.languageServiceAdapterHost.addScript(Harness.Compiler.defaultLibFileName,
```
Comment (Qiyu8) [inline src/harness/fourslashImpl.ts]: The below code is identical to the front, is there any possibilities to reuse it?

File: src/services/completions.ts (hunk 3 above)
Comment (andrewbranch) [reply src/services/completions.ts]: The containing namespace declaration is already internal.

Comment (amcasey) [reply src/services/completions.ts]: Gets me every time. :smile:

File: src/services/completions.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/completions.ts]: The purpose of this type is just to obscure the value type and prevent consumers from testing the result of the underlying Map’s `get` method for truthiness, since `false` indicates something very different from `undefined`. I was actually hoping to just _use_ the Map object and obscure its value type with this interface, but I couldn’t do that because the `set` method needs two arguments, one of which is a value.

**Comment by andrewbranch** [comment]
> I was expecting two entries here. Did I misunderstand?

@amcasey for the purposes of this PR, at least, forget about the conversation I started in Teams. I didn’t really sense that any of us were in agreement about the best behavior, so I left the sorting and the shadowing as it’s always been. There is a rule baked into the architecture of `getCompletionEntriesFromSymbols` that locals shadow everything else.

This PR does only two things, despite being related to the other ideas we talked about:

1. It special-cases methods where the type of `this` is the type of `self`, `global`, or `globalThis` to prevent offering completions like `parseInt` -> `this.parseInt`, since every member symbol is probably available as a global, and preferable to access globally.
2. In the case where there’s a `foo` -> `this.foo` completion _and_ a global `foo`, fix the details request (#37651).

File: src/services/completions.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/completions.ts]: All good in VS - we never display the source property on `CompletionEntry`, but we do display the source property on `CompletionEntryDetails`, as allowed by the comment there.

[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/services/completions.ts]: I am not sure how vscode uses source property..  @mjbvz might know but I don't think we should use `SymbolOriginaInfoKind` for that since its a enum with number values.

[the remark this answers is not in the document]
Comment (mjbvz) [reply src/services/completions.ts]: VS Code also renders the `source` in the suggestion details: https://github.com/microsoft/vscode/blob/9d25faad7fbf3255ca32959be47466107555cb08/extensions/typescript-language-features/src/features/completions.ts#L715

[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/completions.ts]: That `source` is from the completion details response, which is calculated separately and intended to be human-readable. It will remain blank for `this.` completion details. Looks like `source` on the `CompletionEntry` itself is never displayed. I’ve replaced the `SymbolOriginInfoKind` stringification with a dedicated string enum per @sheetalkamat’s feedback.

File: src/services/completions.ts [hunk 5]
```diff
@@ -11,6 +11,22 @@ namespace ts.Completions {
...
+     * comprise `CompletionEntryIdentifier` in `getCompletionEntryDetails`.
+     *
+     * When the completion item is an auto-import suggestion, the source
+     * is the module specifier of the suggestion. To avoid collisions,
+     * the values here should not be a module specifier we would ever
+     * generate for an auto-import.
+     */
+    export enum CompletionSource {
+        /** Completions that require `this.` insertion text */
+        ThisProperty = "ThisProperty/"
```
Comment (sheetalkamat) [inline src/services/completions.ts]: is "/" intentional at the end?

Comment (andrewbranch) [reply src/services/completions.ts]: Yeah, it’s explained in the comment—we need these values to be impossible values for an auto-import specifier. If someone had a folder named `ThisProperty` and a `baseUrl` set, we could conceivably generate an auto-import suggestion whose `source` is `ThisProperty`.
