### PR TITLE
fix: no variable suggestions without semicolon

### LINKED ISSUE #54654: Code comlpetion not working for variables
# Bug Report

### 🔎 Search Terms

Completion, IntelliSense

### 🕗 Version & Regression Information

Tested in 'Nightly' version - the problem is not fixed.

- This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/DYUwLgBAZg9jBcEB2BXAtgIxAJwgXggEYAoWIA)

### 💻 Code

```ts
let foo: number = 1
fo
```

### 🙁 Actual behavior

Completion list ater `fo` does not contain `foo` item.

### 🙂 Expected behavior

Completion list ater `fo` contains `foo` item.

### PR DESCRIPTION
**Pull request by zardoy**
don't use contextToken for finding closest variable declaration

Fixes #54654

I think there could be a better fix (rather than using location and contextToken at the same time)

### CODE REVIEW

**Comment by zardoy** [comment]
I'm not sure, probably `contextToken` shouldn't be `1` in the following example?
```ts
const a = 1
/**/
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100

**Review by gabritto — APPROVED** [review]

File: src/services/completions.ts [hunk 1]
```diff
@@ -5516,14 +5516,18 @@ function isModuleSpecifierMissingOrEmpty(specifier: ModuleReference | Expression
...
     if (!contextToken) return;
 
-    const declaration = findAncestor(contextToken, node =>
+    const possiblyParameterDeclaration = findAncestor(contextToken, node =>
         isFunctionBlock(node) || isArrowFunctionBody(node) || isBindingPattern(node)
             ? "quit"
-            : isVariableDeclaration(node) || ((isParameter(node) || isTypeParameterDeclaration(node)) && !isIndexSignatureDeclaration(node.parent)));
-    return declaration as ParameterDeclaration | TypeParameterDeclaration | VariableDeclaration | undefined;
+            : ((isParameter(node) || isTypeParameterDeclaration(node)) && !isIndexSignatureDeclaration(node.parent)));
+    const possiblyVariableDeclaration = findAncestor(location, (node) => {
```
Comment (MariaSolOs) [inline src/services/completions.ts:5526]: Nit:
```suggestion
    const possiblyVariableDeclaration = findAncestor(location, node => {

```

File: src/services/completions.ts [hunk 2]
```diff
@@ -5516,14 +5516,18 @@ function isModuleSpecifierMissingOrEmpty(specifier: ModuleReference | Expression
     return !tryCast(isExternalModuleReference(specifier) ? specifier.expression : specifier, isStringLiteralLike)?.text;
 }
 
-function getVariableOrParameterDeclaration(contextToken: Node | undefined) {
+function getVariableOrParameterDeclaration(contextToken: Node | undefined, location: Node) {
     if (!contextToken) return;
 
-    const declaration = findAncestor(contextToken, node =>
+    const possiblyParameterDeclaration = findAncestor(contextToken, node =>
```
Comment (MariaSolOs) [inline src/services/completions.ts:5522]: I know that the existing code already uses `findAncestor`, but is this really needed @DanielRosenwasser? Can't we restrict the scope of this search?

File: src/services/completions.ts (hunk 1 above)
Comment (zardoy) [reply src/services/completions.ts]: I formatted code so these two blocks match

File: src/services/completions.ts [hunk 3]
```diff
@@ -5516,14 +5516,18 @@ function isModuleSpecifierMissingOrEmpty(specifier: ModuleReference | Expression
     return !tryCast(isExternalModuleReference(specifier) ? specifier.expression : specifier, isStringLiteralLike)?.text;
 }
 
-function getVariableOrParameterDeclaration(contextToken: Node | undefined) {
+function getVariableOrParameterDeclaration(contextToken: Node | undefined, location: Node) {
     if (!contextToken) return;
```
[the remark this answers is not in the document]
Comment (zardoy) [reply src/services/completions.ts:5520]: Actually I didn't think about it when I opened this PR. Though for me its obvious that it can be `undefined` only when there is nothing behind the requesting position (as [essentially `contextToken` is `previousToken`](https://github.com/a-tarasyuk/typescript/blob/4c2bcc935563e509add094cc86ed5fb7eb82f51f/src/services/completions.ts#L4911)). Otherwise it will be something like OpenBraceToken.

File: src/services/completions.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/services/completions.ts:5522]: Do you mean do we really need two walks? I'm not sure; we could probably rewrite this to only do the second walk if the first fails though.

Comment (DanielRosenwasser) [reply src/services/completions.ts:5522]: Another way to do this is to check whether the `contextToken` ever becomes the `location`, and only then to start checking for variable declarations.

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

File: src/services/completions.ts (hunk 2 above)
Comment (zardoy) [reply src/services/completions.ts:5522]: > Do you mean do we really need two walks? I'm not sure; we could probably rewrite this to only do the second walk if the first fails though.

I'm not sure I'm following initial request here. Why we can't have two walks here? (since it uses existing ast and we also do it only once per completionInfo request)

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.1
