### PR TITLE
fixes #48630 array binding pattern with only OmittedExpressions does not check RHS of for-of loop

### LINKED ISSUE #48630: Array binding pattern with only OmittedExpressions does not check RHS of for-of loop
# Bug Report

### 🔎 Search Terms
array binding patterns for-of loop omittedexpression binding elements

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEBMHsFMGcDsDkAXU0BO7LoLACgAzbUACgGNJ5ZUBtAGgF1RICIYFkBRADwEtqSASlDAAvKABMwgN758AXzl4QbOGkzZ8RdKQpVaAfTrGmLVRx79kQkeKmhZeBfiA)

### 💻 Code

```ts
// doesn't error
for (const [,] of doesntExist() /= 2) {

}

// does error
for (const [_,,,] of doesntExist() /= 2) {

}

```

### 🙁 Actual behavior

The right hand side of the for-of loop is not checked at all. 

This appears to be because `OmittedExpression` is not actually a `BindingElement` and the right hand side's type is only checked whenever encountering a `BindingElement` in `checkVariableLikeDeclaration` or when there are no elements in the pattern.

### 🙂 Expected behavior

The right hand side of the for-of loop to be checked.

### PR DESCRIPTION
**Pull request by bentongxyz**
fixes #48630

Fixes #

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -37830,6 +37830,12 @@ namespace ts {
             return checkVariableLikeDeclaration(node);
         }
 
+        function checkOmittedExpression(node: OmittedExpression) {
+            if (node.parent.parent?.parent?.parent.kind === SyntaxKind.ForOfStatement) {
+                checkRightHandSideOfForOf(node.parent.parent.parent.parent as ForOfStatement);
```
Comment (Fireboltofdeath) [inline src/compiler/checker.ts:37835]: `checkVariableLikeDeclaration` already has logic for evaluating the right side of the for-of loop (when encountering a *binding pattern*) when there are no elements. I think it might make more sense to update that code to account for omitted expressions?

Comment (bentongxyz) [reply src/compiler/checker.ts:37835]: Hi @Fireboltofdeath, thank you for your review!

> checkVariableLikeDeclaration already has logic for evaluating the right side of the for-of loop (when encountering a binding pattern) when there are no elements. I think it might make more sense to update that code to account for omitted expressions?

This is good point. I did try to update that piece of code to  account for `OmittedExpression`, however here is what I encountered:
- In the logic that you referred to, `checkRightHandSideOfForOf` is called _inside_ `getWidenedTypeForVariableLikeDeclaration` by `getTypeForVariableLikeDeclaration` almost like a side-effect.
- Since our fix is really "check RHS of `for..of` statement _too_ if a node is a  `BindingPattern`, has no `BindingElement`, but does have `OmittedExpression(s)`", it seems a kind of a stretch to fit our fix into logic that check `WidenedType`.

So it seemed more straightforward to "if we encounter `OmittedExpression` in `checkSourceElementWorker`, check RHS of `For..Of` Statement if it is in one".

An alternative approach to work with `checkVariableLikeDeclaration` maybe:
if `node.name.elements > 0` and `node.name.elements` does _not_ contain `BindingElement`, do a check of RHS of `For..Of`.

What do you think? I would love to know you comment on this.

Thanks a lot for your time!

Comment (andrewbranch) [reply src/compiler/checker.ts:37835]: I think `needsCheckWidenedType` just needs to be updated so that it’s `true` if all elements are OmittedExpressions; let me give you that since the best expression of it uses several utilities you’re probably not aware of: `!some(node.name.elements, not(isOmittedExpression))`.

You’ll also want to add a couple more test cases:

```ts
for (const [,] of undefined) {
}

for (const [,] of []) {
}
```

This will ensure that we’re also checking that the RHS is iterable, and that its iterated type is also iterable. (Both of these should be errors.)

Thanks!

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Comment by bentongxyz** [comment]
Thank you, I will work on a new commit

File: src/compiler/checker.ts (hunk 1 above)
Comment (bentongxyz) [reply src/compiler/checker.ts:37835]: Thank you, I will work on a new commit

**Comment by bentongxyz** [comment]
Hi @andrewbranch, just want to say that your help is very useful so thank you very much.

Note that there is no error produced for this test case: 

```ts
for (const [,] of []) {
}
```

Nor this one below without the omitted expression, e.g.: 

```ts
for (const [] of []) {
}
```

So it seems to me unrelated to this PR issue at hand.

File: tests/cases/compiler/omittedExpressionForOfLoop.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
+for (const [,] of doesNotExist) {
+}
+
+for (const [,] of undefined) {
+}
+
+for (const [,] of []) {
+}
+
+for (const [] of []) {
```
Comment (andrewbranch) [inline tests/cases/compiler/omittedExpressionForOfLoop.ts:10]: Can you add `// @strict: true` at the top of this test? These last two should be an error under `strictNullChecks`—without that enabled, we’re not really seeing if error reporting works on both.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Comment by bentongxyz** [comment]
@andrewbranch much appreciated for your review, code updated as per your suggestion :)

**Review by andrewbranch — APPROVED** [review]
It turns out we also needed `// @target: es2015` to see the error I was expecting. I went ahead and pushed that change. Thank you!
