### PR TITLE
Get packageId for relative import within a package

### LINKED ISSUE #20945: Dependencies linked with a symbolic link (by `lerna`) break the transpilation when using `rxjs`
**Setup**
The issue happens in a repository containing two npm packages
```
.
|-- lerna.json
|-- package.json
|-- packages
    |-- lerna-typescript-demo-base:
          A project implemented in plain JavaScript, exporting a class (constructor function) with two functions.
          Also contains an index.d.ts with the typings.
    |-- lerna-typescript-demo-ts:
          A TypeScript project referencing lerna-typescript-demo-base.
          And lerna will set up the dependency in node_modules as a symlink to the other folder.
```

The class exported from `lerna-typescript-demo-base`, `Foo` has two functions, one is returning `Bar[]`, and the other is returning an rxjs `Observable`, specifically `Observable<Bar[]>`.

In `lerna-typescript-demo-ts` we try to use both functions, and the transpilation of the usage of the one returning the `Observable` fails.

**Code**
A repro is uploaded here: https://github.com/markvincze/lerna-typescript-demo
The steps to reproduce are in the README.

**Expected behavior:**
Transpilation should succeed.

**Actual behavior:**
Transpilation fails with

```
error TS2345: Argument of type 'UnaryFunction<Observable<Bar[]>, Observable<Bar[]>>' is not assignable to parameter of type 'UnaryFunction<Observable<Bar[]>, Observable<Bar[]>>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<Bar[]>' is not assignable to type 'Observable<Bar[]>'. Two different types with this name exist, but they are unrelated.
```

**Comments**:
I tried also with `typescript@next`, but get the same error.
I suspect this is related to the symlink dependency, because if I replace that with the ordinary in-place dependency, the error goes away. Also, this is only happening with the function returning an `Observable`, so it might also be related to `rxjs` somehow.
(I've seen a number of other issues about symlinks, but they were either closed as fixed, outdated, or just didn't have a clear repro.)

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20945 (tested with the sample repository provided)

If we're loading relatively from a file, we will parse the result path to see if we're currently in a `node_modules`; if so, we will look for a packageId for the current package.

### CODE REVIEW

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -816,6 +818,33 @@ namespace ts {
         return loadNodeModuleFromDirectory(extensions, candidate, failedLookupLocations, onlyRecordFailures, state, considerPackageJson);
     }
 
+    function parseNodeModuleFromPath(path: string): { packageDirectory: string, subModuleName: string } | undefined {
+        const nodeModules = "/node_modules/";
```
Comment (amcasey) [inline src/compiler/moduleNameResolver.ts]: Is this case-sensitive even on Windows?

File: src/compiler/moduleNameResolver.ts [hunk 2]
```diff
@@ -816,6 +818,33 @@ namespace ts {
...
+            indexAfterPackageName = indexOfNextSlash(path, indexAfterPackageName);
+        }
+        const packageDirectory = path.slice(0, indexAfterPackageName);
+        const subModuleName = removeExtensionAndIndex(path.slice(indexAfterPackageName));
+        return { packageDirectory, subModuleName };
+    }
+
+    function indexOfNextSlash(s: string, pos: number): number {
+        const x = s.indexOf(directorySeparator, pos);
+        return x === -1 ? pos : x;
```
Comment (amcasey) [inline src/compiler/moduleNameResolver.ts]: This special case makes sense for this application, but probably not in general.  Would it make sense to move this helper into `parseNodeModuleFromPath`?

File: src/compiler/moduleNameResolver.ts [hunk 3]
```diff
@@ -816,6 +818,33 @@ namespace ts {
...
+    }
+
+    function removeExtensionAndIndex(fileName: string): string {
+        const noExtension = removeFileExtension(fileName);
+        return noExtension === "index" ? "" : removeSuffix(noExtension, "/index");
```
Comment (amcasey) [inline src/compiler/moduleNameResolver.ts]: Presumably, we won't reach here for (e.g.) "index.vb"?

Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: `removeFileExtension` only removes the supported file extensions (and also correctly removes all of `.d.ts` and not just `.ts`. Although it's also true that `fileName` shouldn't have a `.vb` extension since we'd never resolve a module to a `.vb` file.

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: Should be fixed if we normalize the path first.

File: src/compiler/moduleNameResolver.ts (hunk 2 above)
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: I'm not a fan of moving things into closures if they don't need to close over any variables, but this could be named better.

**Comment by andy-ms** [comment]
@amcasey Good to merge?

**Comment by amcasey** [comment]
No objections here, but it might be nice to have a second set of eyes.

**Comment by andy-ms** [comment]
@aozgaa @sheetalkamat

File: src/compiler/moduleNameResolver.ts [hunk 4]
```diff
@@ -816,6 +818,34 @@ namespace ts {
...
+        const subModuleName = removeExtensionAndIndex(path.slice(indexAfterPackageName));
+        return { packageDirectory, subModuleName };
+    }
+
+    function moveToNextDirectorySeparatorIfAvailable(path: string, pos: number): number {
+        const indexOfSlash = path.indexOf(directorySeparator, pos);
+        return indexOfSlash === -1 ? pos : indexOfSlash;
+    }
+
+    function removeExtensionAndIndex(fileName: string): string {
```
Comment (aozgaa) [inline src/compiler/moduleNameResolver.ts]: Do we have a convention where `fileName` is a path? If it someone were to input just the last part of a path here (eg: `"index.d.ts"`) then the result we would get would be `"index"`. Is that okay?

File: src/compiler/moduleNameResolver.ts [hunk 5]
```diff
@@ -816,6 +818,34 @@ namespace ts {
...
+        const nodeModules = "/node_modules/";
+        const idx = path.indexOf(nodeModules);
+        if (idx === -1) {
+            return undefined;
+        }
+
+        const indexAfterNodeModules = idx + nodeModules.length;
+        let indexAfterPackageName = moveToNextDirectorySeparatorIfAvailable(path, indexAfterNodeModules);
+        if (path.charCodeAt(indexAfterNodeModules) === CharacterCodes.at) {
+            indexAfterPackageName = moveToNextDirectorySeparatorIfAvailable(path, indexAfterPackageName);
```
Comment (aozgaa) [inline src/compiler/moduleNameResolver.ts]: How does the method work with submodules under `@types` (eg: `"@types/someModule/Submodule"`)? Or is that not a valid input here?

File: src/compiler/moduleNameResolver.ts (hunk 4 above)
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: I'll rename the parameter to `path`.

File: src/compiler/moduleNameResolver.ts [hunk 6]
```diff
@@ -816,6 +818,34 @@ namespace ts {
...
+        }
+        const packageDirectory = path.slice(0, indexAfterPackageName);
+        const subModuleName = removeExtensionAndIndex(path.slice(indexAfterPackageName));
+        return { packageDirectory, subModuleName };
+    }
+
+    function moveToNextDirectorySeparatorIfAvailable(path: string, pos: number): number {
```
[the remark this answers is not in the document]
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: :+1:

File: src/compiler/moduleNameResolver.ts [hunk 7]
```diff
@@ -816,6 +818,34 @@ namespace ts {
...
+            return undefined;
+        }
+
+        const indexAfterNodeModules = idx + nodeModules.length;
+        let indexAfterPackageName = moveToNextDirectorySeparatorIfAvailable(path, indexAfterNodeModules);
+        if (path.charCodeAt(indexAfterNodeModules) === CharacterCodes.at) {
+            indexAfterPackageName = moveToNextDirectorySeparatorIfAvailable(path, indexAfterPackageName);
+        }
+        const packageDirectory = path.slice(0, indexAfterPackageName);
+        const subModuleName = removeExtensionAndIndex(path.slice(indexAfterPackageName));
```
[the remark this answers is not in the document]
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: subModuleName is the name of a path within a package, so for `@angular/core/foo.d.ts` it would be "foo" and for `@angular/core/index.d.ts` it would be the empty string "".

File: src/compiler/moduleNameResolver.ts (hunk 5 above)
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: In that case `subModuleName` would be "Submodule".

[the remark this answers is not in the document]
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: A path should be a complete file path like `/node_modules/@asdf/pkg/index.d.ts`, not just `/node_modules/@asdf`.

File: src/compiler/moduleNameResolver.ts [hunk 8]
```diff
@@ -816,6 +818,34 @@ namespace ts {
         return loadNodeModuleFromDirectory(extensions, candidate, failedLookupLocations, onlyRecordFailures, state, considerPackageJson);
     }
 
+    function parseNodeModuleFromPath(path: string): { packageDirectory: string, subModuleName: string } | undefined {
+        path = normalizePath(path);
+        const nodeModules = "/node_modules/";
```
[the remark this answers is not in the document]
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: :+1:

File: src/compiler/moduleNameResolver.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (aozgaa) [reply src/compiler/moduleNameResolver.ts]: Are we concerned with malformed paths and packages? As a scenario, do we care if someone is mucking about and makes a malformed entry manually? I personally think tsserver shouldn't crash, and ideally we would surface a message to a user.

Do we have some way of handling situations like this gracefully?

File: src/compiler/moduleNameResolver.ts [hunk 9]
```diff
@@ -816,6 +818,42 @@ namespace ts {
         return loadNodeModuleFromDirectory(extensions, candidate, failedLookupLocations, onlyRecordFailures, state, considerPackageJson);
     }
 
+    const nodeModulesPathPart = "/node_modules/";
+
+    /**
+     * packageDirectory is the directory of the package itself.
+     * subModuleName is the path within the package.
+     *   For `foo/index.d.ts` this is { packageDirectory: "foo", subModuleName: "" }.
```
Comment (aozgaa) [inline src/compiler/moduleNameResolver.ts]: Should these examples start with `"/node_modules/"`?

File: src/compiler/moduleNameResolver.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: > I personally think tsserver shouldn't crash

That's just, like, your opinion, man. 😜 

But we shouldn't get a malformed path here because this is only called after a successful module resolution. And even if we did, I don't see a place where this function would crash.

File: src/compiler/moduleNameResolver.ts [hunk 10]
```diff
@@ -816,6 +818,45 @@ namespace ts {
...
+    function parseNodeModuleFromPath(path: string): { packageDirectory: string, subModuleName: string } | undefined {
+        path = normalizePath(path);
+        const idx = path.indexOf(nodeModulesPathPart);
+        if (idx === -1) {
+            return undefined;
+        }
+
+        const indexAfterNodeModules = idx + nodeModulesPathPart.length;
+        let indexAfterPackageName = moveToNextDirectorySeparatorIfAvailable(path, indexAfterNodeModules);
+        if (path.charCodeAt(indexAfterNodeModules) === CharacterCodes.at) {
```
Comment (mhegazy) [inline src/compiler/moduleNameResolver.ts]: can you add a test for scoped packages as well

File: src/compiler/moduleNameResolver.ts [hunk 11]
```diff
@@ -816,6 +818,45 @@ namespace ts {
...
+     *
+     * packageDirectory is the directory of the package itself.
+     * subModuleName is the path within the package.
+     *   For `blah/node_modules/foo/index.d.ts` this is { packageDirectory: "foo", subModuleName: "" }. (Part before "/node_modules/" is ignored.)
+     *   For `/node_modules/foo/bar.d.ts` this is { packageDirectory: "foo", subModuleName": "bar" }.
+     *   For `/node_modules/@types/foo/bar/index.d.ts` this is { packageDirectory: "@types/foo", subModuleName: "bar" }.
+     */
+    function parseNodeModuleFromPath(path: string): { packageDirectory: string, subModuleName: string } | undefined {
+        path = normalizePath(path);
+        const idx = path.indexOf(nodeModulesPathPart);
```
Comment (mhegazy) [inline src/compiler/moduleNameResolver.ts]: should not this be `lastIndexOf` instead? you want the last node_modules in the list right?

File: tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.trace.json [hunk 12]
```diff
@@ -0,0 +1,45 @@
+[
+    "======== Resolving module 'foo/use' from '/index.ts'. ========",
+    "Module resolution kind is not specified, using 'NodeJs'.",
+    "Loading module 'foo/use' from 'node_modules' folder, target file type 'TypeScript'.",
+    "Found 'package.json' at '/node_modules/foo/package.json'.",
+    "File '/node_modules/foo/use.ts' does not exist.",
+    "File '/node_modules/foo/use.tsx' does not exist.",
+    "File '/node_modules/foo/use.d.ts' exist - use it as a name resolution result.",
+    "Resolving real path for '/node_modules/foo/use.d.ts', result '/node_modules/foo/use.d.ts'.",
+    "======== Module name 'foo/use' was successfully resolved to '/node_modules/foo/use.d.ts'. ========",
```
Comment (mhegazy) [inline tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.trace.json]: this is not related to this PR, but just a thought that came to me, we are not logging the packageid anywhere. we should probably to make these tests more statically verifiable

Comment (andy-ms) [reply tests/baselines/reference/duplicatePackage_relativeImportWithinPackage.trace.json]: #21232

File: src/compiler/moduleNameResolver.ts (hunk 11 above)
Comment (andy-ms) [reply src/compiler/moduleNameResolver.ts]: :+1:
