### PR TITLE
Fixes renaming not affecting JSX closing tags (#4093)

### LINKED ISSUE #4093: JSX element renaming issues
I just noticed that renaming an JSX element doesn't rename the end tag. I also expect renaming an intrinsic element would be local, when in fact, it renames all elements of that type and even the interface member of `JSX.IntrinsicElements`. Renaming intrinsic elements is quite destructive for a project.

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #4093

We weren't wiring up the closing tags to their corresponding symbols.

This does have a side effect of causing "name not found" errors on closing tags that will always match the opening tag names. We could probably fix this if it's problematic, but would require plumbing through another boolean fairly deep into the core identifier resolution functions.

### CODE REVIEW

File: tests/cases/fourslash/tsxRename4.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+////   props: {
+////     name?: string;
+////     size?: number;
+//// }
+//// 
+//// 
+//// var x = <[|MyC/**/lass|] name='hello'></[|MyClass|]>;
+
+goTo.marker();
+debugger;
```
Comment (danquirk) [inline tests/cases/fourslash/tsxRename4.ts]: linter save us

Comment (RyanCavanaugh) [inline tests/cases/fourslash/tsxRename4.ts]: I thought I removed this :cry:

File: tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt [hunk 2]
```diff
@@ -30,6 +30,7 @@ tests/cases/conformance/jsx/jsxInvalidEsprimaTestSuite.tsx(11,12): error TS2304:
 tests/cases/conformance/jsx/jsxInvalidEsprimaTestSuite.tsx(11,16): error TS1109: Expression expected.
 tests/cases/conformance/jsx/jsxInvalidEsprimaTestSuite.tsx(12,2): error TS2304: Cannot find name 'a'.
 tests/cases/conformance/jsx/jsxInvalidEsprimaTestSuite.tsx(12,5): error TS1003: Identifier expected.
+tests/cases/conformance/jsx/jsxInvalidEsprimaTestSuite.tsx(12,10): error TS2304: Cannot find name 'a'.
```
Comment (mhegazy) [inline tests/baselines/reference/jsxInvalidEsprimaTestSuite.errors.txt]: it is unfortunate that we report the same error twice.

**Comment by mhegazy** [comment]
:+1:
