### PR TITLE
Fix `lib.includes('dom')` check in `containerSeemsToBeEmptyDomElement`

### LINKED ISSUE #61466: `containerSeemsToBeEmptyDomElement` does not check correctly for lib.dom.d.ts
### 🔎 Search Terms

"compiler option to include", "containerSeemsToBeEmptyDomElement"

### 🕗 Version & Regression Information

- This changed in commit 31374d2 when this diagnostic was added

### ⏯ Playground Link

https://github.com/frodi-karlsson/lib-dom-example

### 💻 Code

```json5
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["es5", "dom"],
    "noEmit": true
  },
  "files": ["index.ts"]
}
```

```ts
// index.ts
interface HTMLXYZElement {}

const a = {} as HTMLXYZElement;

// gives us Property_0_does_not_exist_on_type_1_Try_changing_the_lib_compiler_option_to_include_dom
// when it should give Property_0_does_not_exist_on_type_1
a.innerText = "hello";
```

### 🙁 Actual behavior

Property 'innerText' does not exist on type 'HTMLXYZElement'. Try changing the 'lib' compiler option to include 'dom'.

### 🙂 Expected behavior

Property 'innerText' does not exist on type 'HTMLXYZElement'.

### Additional information about the issue

Bit of a duplicate of #54484 which did not have sufficient adherence to issue template. Noticed by @jakebailey [here](https://github.com/microsoft/typescript-go/pull/691#discussion_r2008826121)

There's a check for "dom" that should be "lib.dom.d.ts"

### PR DESCRIPTION
**Pull request by frodi-karlsson**
Fixes #61466, just barely passing `provide commensurate value.` (:
There are no other lib.includes(...)-like checks I could find that would be similarly bugged

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -34454,7 +34454,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     }
 
     function containerSeemsToBeEmptyDomElement(containingType: Type) {
-        return (compilerOptions.lib && !compilerOptions.lib.includes("dom")) &&
+        return (compilerOptions.lib && !compilerOptions.lib.includes("lib.dom.d.ts")) &&
```
Comment (MartinJohns) [inline src/compiler/checker.ts:34457]: Do these compiler options at runtime **really** contain `lib.dom.d.ts`? That seems very weird, because in the actual settings you just provide `dom`: https://www.typescriptlang.org/tsconfig/#lib

Comment (jakebailey) [reply src/compiler/checker.ts:34457]: Yes: https://github.com/microsoft/typescript-go/pull/691#discussion_r2008826121

**Review by jakebailey — APPROVED** [review]
