### PR TITLE
Fix deferred export of array binding pattern

### LINKED ISSUE #10778: Nightly error
After @mhegazy's [comment](https://github.com/Microsoft/TypeScript/issues/1664#issuecomment-245340547) I wanted to give the new codegen a try and downloaded `2.1.0-dev.20160907` (I am currently using Babel js).

The result on my codebase is a compiler crash:
```
TypeError: Cannot read property 'text' of undefined
    at addExportMemberAssignmentsForBindingName (D:\****\node_modules\typescript\lib\typescript.js:45135:95)
    at addExportMemberAssignmentsForBindingName (D:\****\node_modules\typescript\lib\typescript.js:45131:21)
    at visitVariableStatement (D:\****\node_modules\typescript\lib\typescript.js:45119:17)
    at visitor (D:\****\node_modules\typescript\lib\typescript.js:44882:28)
    at Object.visitNodes (D:\****\node_modules\typescript\lib\typescript.js:40012:48)
    at transformAsynchronousModuleBody (D:\****\node_modules\typescript\lib\typescript.js:44836:40)
    at transformAsynchronousModule (D:\****\node_modules\typescript\lib\typescript.js:44822:41)
    at transformAMDModule (D:\****\node_modules\typescript\lib\typescript.js:44757:20)
    at transformSourceFile (D:\****\node_modules\typescript\lib\typescript.js:44719:31)
    at D:\****\node_modules\typescript\lib\typescript.js:51196:89
```

I am sorry but I can't put up a repro our codebase is large and confidential :(

### PR DESCRIPTION
**Pull request by rbuckton**
We parse the missing element as an `OmittedExpression` but cast it to a `BindingElement` even though it does not have the same shape. The result was an issue where the module transformer did not account for this case and code like the following would result in an exception:

```ts
const [a, , b] = [1, 2, 3];
export { a, b };
```

This PR makes the expected types more explicit and fixes the incorrect case.

Fixes #10778

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -3701,6 +3701,12 @@ namespace ts {
         return node.kind === SyntaxKind.BindingElement;
     }
 
+    export function isArrayBindingElement(node: Node): node is ArrayBindingElement {
+        const kind = node.kind;
+        return kind === SyntaxKind.BindingElement
+            || kind === SyntaxKind.OmittedExpression;
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: It's kind of weird that a binding element uses an omitted *expression*

**Comment by DanielRosenwasser** [comment]
Looks good to me :+1:
