### PR TITLE
Retain name and propertyName in declaration emit copies of binding patterns if property name is a keyword

### LINKED ISSUE #50483: Isssue generating declaration files with object containing keywords as property
TS playground does not have 4.8.2 yet, but this issue can happends in 4.8 beta:

https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=199&ts=4.8.0-beta#code/C4TwDgpgBAMg9gYwIYBsIBEnCVAvFAJQgTgCcATAHgGdhSBLAOwHMAaKRiANwlID4AUKEhQAwnEY9SweMjTjGAM3rNKAFSgQAHsAiNy1WIlQYsOfLJOZsfPIWJkqAqFFoMWrZ1DUC+AbiFwaEt5CWVVDW1dfUMQ02w7OOskW3wiEgoaOiY2KAAFJGl6VHU+fwEBbTAyYCgmXVJFJARoAHEIGWM0agB5MGB6CWp1TR09AyM5eJSoAG8vFyQwMAAuKABXRgBrRjgAd0YAlxdyCCb1lGA1hSlOqYVw0qPjkiUVAH41uIeVUqgAHw2+jOTAg5GeLkYSAAthBPq5siwAgBfCpVGpQV60KDMDpxQz4EZRcaxLrTPgACnmxygSzAnhpUNhDOOp3OlzWbKQFzuJmoPzYC0xYRUa3W1F4+IFdlmyM8yLW7V53T6AyGpQAlNcJLdviKIqlbNTjqQOutSIwoFyeVL9SiAkA

The DTS result is wrong because default is a keyword:

```ts
export declare const getLocales: <T extends LocaleData>({ app, name, default, config, }: GetLocalesOptions<T>) => ConvertLocaleConfig<T>;
```

Meanwhile older ts versions work well:

https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=199&ts=4.7.4#code/C4TwDgpgBAMg9gYwIYBsIBEnCVAvFAJQgTgCcATAHgGdhSBLAOwHMAaKRiANwlID4AUKEhQAwnEY9SweMjTjGAM3rNKAFSgQAHsAiNy1WIlQYsOfLJOZsfPIWJkqAqFFoMWrZ1DUC+AbiFwaEt5CWVVDW1dfUMQ02w7OOskW3wiEgoaOiY2KAAFJGl6VHU+fwEBbTAyYCgmXVJFJARoAHEIGWM0agB5MGB6CWp1TR09AyM5eJSoAG8vFyQwMAAuKABXRgBrRjgAd0YAlxdyCCb1lGA1hSlOqYVw0qPjkiUVAH41uIeVUqgAHw2+jOTAg5GeLkYSAAthBPq5siwAgBfCpVGpQV60KDMDpxQz4EZRcaxLrTPgACnmxygSzAnhpUNhDOOp3OlzWbKQFzuJmoPzYC0xYRUa3W1F4+IFdlmyM8yLW7V53T6AyGpQAlNcJLdviKIqlbNTjqQOutSIwoFyeVL9SiAkA

```ts
export declare const getLocales: <T extends LocaleData>({ app, name, default: defaultLocalesConfig, config: userLocalesConfig, }: GetLocalesOptions<T>) => ConvertLocaleConfig<T>;
```

I think this is a critial bug and should be fixed in 4.8.3 asap

---

Also I was curious:

1. why could this happends? Is related test cases missing?  Maybe the team should check test cases and add some releated test into it.
2. When will you update your website? Hours passes after releasing 4.8 to stable, maybe the team can update ts playground faster, and that DOES help developers.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #50483

### CODE REVIEW

File: scripts/authors.js [hunk 1]
```diff
@@ -0,0 +1,163 @@
+"use strict";
```
Comment (jakebailey) [inline scripts/authors.js:1]: This was mistakenly checked in.

**Comment by jakebailey** [comment]
LGTM besides the old checked in file. Sorry about that; I considered leaving it gitignored for a while after I removed it so it'd be harder to do that, but decided against it.

**Comment by weswigham** [comment]
cc @RyanCavanaugh to follow
@typescript-bot cherry-pick this into release-4.8

**Review by andrewbranch — APPROVED** [review]
