### PR TITLE
fix(52061): Constructor parameters exported as type included in emitted metadata

### LINKED ISSUE #52061: Constructor parameters exported as type included in emitted metadata
# Bug Report

### 🔎 Search Terms

emitDecoratorMetadata, export type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Classes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
class Foo {}

export type { Foo };
```

```ts
import { Foo } from 'somewhere';

const Decorator: ClassDecorator = () => undefined;

@Decorator
class Bar {
    constructor(par: Foo) {}
}
```

### 🙁 Actual behavior

```ts
Bar = __decorate([
    Decorator,
    __metadata("design:paramtypes", [Foo]) // Foo not available during runtime
], Bar);
```

### 🙂 Expected behavior

```ts
Bar = __decorate([
    Decorator,
    __metadata("design:paramtypes", [Object])
], Bar);
```
The same with `import type` is also broken.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #52061

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -44868,7 +44868,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         }
         const valueSymbol = resolveEntityName(typeName, SymbolFlags.Value, /*ignoreErrors*/ true, /*dontResolveAlias*/ true, location);
         const resolvedSymbol = valueSymbol && valueSymbol.flags & SymbolFlags.Alias ? resolveAlias(valueSymbol) : valueSymbol;
-        isTypeOnly ||= !!valueSymbol?.declarations?.every(isTypeOnlyImportOrExportDeclaration);
+        isTypeOnly ||= !!(valueSymbol && (valueSymbol.declarations?.every(isTypeOnlyImportOrExportDeclaration) || getTypeOnlyAliasDeclaration(valueSymbol, SymbolFlags.Value)));
```
Comment (andrewbranch) [inline src/compiler/checker.ts:44871]: I think `valueSymbol.declarations?.every(isTypeOnlyImportOrExportDeclaration)` is actually redundant with `getTypeOnlyAliasDeclaration(valueSymbol, SymbolFlags.Value)`, and only the latter is needed. Since values can’t merge cross-module, if there is a type-only alias declaration resolving to a value, it’s guaranteed that the _only_ value meaning in the symbol is type-only, and therefore there can be no runtime value to reference.

**Review by andrewbranch — APPROVED** [review]
Thanks!

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: @andrewbranch thanks
