### PR TITLE
fixes microsoft/TypeScript#41286

### LINKED ISSUE #41286: Poor deprecated messages - types should almost never be displayed.
```ts
/** @deprecated - this is bad advice */
declare function crossTheStreams(): void

crossTheStreams()
```

**Expected:** `'crossTheStreams' is deprecated.`
**Actual:** `'(): void' is deprecated`

Notice the type in place of the entity name, notice the lack of a period at the end.

image

### PR DESCRIPTION
**Pull request by AnyhowStep**
Please verify that:
* [x] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `gulp runtests` locally
* [x] There are new or updated unit tests validating the change

Fixes #41286

How do I test the `relatedInformation` property in a `fourslash` test?

Right now, I just updated the existing tests but did not add any tests for https://github.com/microsoft/TypeScript/issues/41286#issuecomment-717612925

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1107,6 +1107,24 @@ namespace ts {
...
+                if (deprecatedTag) {
+                    addRelatedInfo(
+                        diagnostic,
+                        createDiagnosticForNode(deprecatedTag, Diagnostics.The_declaration_was_marked_as_deprecated_here)
+                    );
+                    break;
+                }
+            }
+            //We call `addRelatedInfo()` before adding the diagnostic
+            //to prevent duplicates.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:1123]:
```suggestion
            // We call `addRelatedInfo()` before adding the diagnostic
            // to prevent duplicates.
```

Comment (DanielRosenwasser) [inline src/compiler/checker.ts:1123]: I don't understand which duplicates you had in mind. Can you elaborate on what you're trying to avoid?

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -1107,6 +1107,24 @@ namespace ts {
             return diagnostic;
         }
 
+        function addDeprecatedSuggestion(location: Node, declarations: Node[], deprecatedEntity: string) {
+            const diagnostic = createDiagnosticForNode(location, Diagnostics._0_is_deprecated, deprecatedEntity);
+            for (const declaration of declarations) {
```
Comment (gurunars) [inline src/compiler/checker.ts:1112]: It seems like you semantically want to find the first encounter of a deprecated tag and add diagnostics info to it. I would rather extract finding an element based on predicate into a standalone function (aka `Array.find()` from ES6) and then do an `if (deprecatedTag)` check with a return value of that function.

**Review by gurunars — CHANGES_REQUESTED** [review]

File: src/compiler/diagnosticMessages.json [hunk 3]
```diff
@@ -3059,6 +3059,10 @@
         "category": "Error",
         "code": 2796
     },
+    "The declaration was marked as deprecated here.": {
```
Comment (sandersn) [inline src/compiler/diagnosticMessages.json:3062]: I think it's misleading for the top-line message of a function with some non-deprecated signatures to be "'f' is deprecated". I'd rather see a new message "The signature '(): void' of 'f' is deprecated."

(The message should still be "f is deprecated" for functions where every signature is deprecated.)

**Review by sandersn — CHANGES_REQUESTED** [review]
I think a separate error message, not an elaboration, is the right fix here.

**Comment by DanielRosenwasser** [comment]
@sandersn if the error message is too long, I think it's handy to to jump to the location. Why not make it a related span with the signature printed out?

**Comment by sandersn** [comment]
The initial message "f is deprecated" is misleading if only one signature of an overloaded function is deprecated. This is pretty common -- at least it came up in bugs multiple times after shipping `@deprecated` support.

I don't think the message is too long -- don't we print signatures in error messages quite a bit? If it is too long, then an elaboration (for the signature type) or related span (to the signature itself) makes sense. But there should still be a different message for partly-deprecated functions.

**Comment by AnyhowStep** [comment]
I know the original issue specified,
> Expected: `'crossTheStreams' is deprecated.`
> Actual: `'(): void' is deprecated`

And we want `The signature '(): void' of 'f' is deprecated.` if only some overloads are deprecated.

But I'm wondering if `The signature '{0}' of '{1}' is deprecated.` should just be the message as long as we have a signature.
So, non-overloaded functions, partially-deprecated overloaded functions, and fully-deprecated overloaded functions.

And everything else without a signature can just use `'{0}' is deprecated.`

**Comment by AnyhowStep** [comment]
image

I just added some changes that implements the above.

I don't mind adding the checks for partially-deprecated vs fully-deprecated signatures, if it's required, though.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -1107,6 +1107,24 @@ namespace ts {
             return diagnostic;
         }
 
+        function addDeprecatedSuggestion(location: Node, declarations: Node[], arg0: string | number | undefined) {
```
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/checker.ts:1110]: can you please replace Impl -> Worker? That's our usual naming scheme.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -1107,6 +1107,35 @@ namespace ts {
             return diagnostic;
         }
 
+        function addDeprecatedSuggestionImpl(declarations: Node[], diagnostic: DiagnosticWithLocation) {
+            for (const declaration of declarations) {
+                const deprecatedTag = getJSDocDeprecatedTag(declaration);
```
Comment (sandersn) [inline src/compiler/checker.ts:1112]: re @gurunars suggestion:

```suggestion
            const deprecatedTag = forEach(declarations, getJSDocDeprecatedTag);
```

I think `Array.find` and our similar `find` function would also work. though the types are less permissive than `forEach`.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -28413,7 +28442,10 @@ namespace ts {
         function checkDeprecatedSignature(signature: Signature, node: CallLikeExpression) {
             if (signature.declaration && signature.declaration.flags & NodeFlags.Deprecated) {
                 const suggestionNode = getDeprecatedSuggestionNode(node);
-                errorOrSuggestion(/*isError*/ false, suggestionNode, Diagnostics._0_is_deprecated, signatureToString(signature));
+                const expr = getInvokedExpression(node);
+                const name = tryGetPropertyAccessOrIdentifierToString(expr);
+                const signatureString = signatureToString(signature);
+                addDeprecatedSuggestionWithSignature(suggestionNode, [signature.declaration], name, signatureString);
```
Comment (sandersn) [inline src/compiler/checker.ts:28448]: I'm not a fan of unnecessary allocations. Can you rewrite addDeprecatedSuggestionWithSignature to work with a single declaration, and addDeprecatedSuggestionWorker to work with single or multiple declarations?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -28413,7 +28442,10 @@ namespace ts {
         function checkDeprecatedSignature(signature: Signature, node: CallLikeExpression) {
             if (signature.declaration && signature.declaration.flags & NodeFlags.Deprecated) {
                 const suggestionNode = getDeprecatedSuggestionNode(node);
-                errorOrSuggestion(/*isError*/ false, suggestionNode, Diagnostics._0_is_deprecated, signatureToString(signature));
+                const expr = getInvokedExpression(node);
+                const name = tryGetPropertyAccessOrIdentifierToString(expr);
```
Comment (sandersn) [inline src/compiler/checker.ts:28446]: I would inline `expr`:
```suggestion
                const name = tryGetPropertyAccessOrIdentifierToString(getInvokedExpression(node));
```

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [inline src/compiler/checker.ts:28448]: also inline `signatureString`:
```suggestion
                addDeprecatedSuggestionWithSignature(suggestionNode, [signature.declaration], name, signatureToString(signature));
```

**Review by sandersn — CHANGES_REQUESTED** [review]
I really like the new behaviour. All that's left are some stylistic and minor perf requests (plus merging from master to renumber error messages). 

I realise that I dropped this review. Plus, now that this is slated to be fixed in 4.2, I can finish those tasks up if you want.

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts]: I don't understand this either -- when I call addRelativeInfo second, one test suddenly has 9 suggestions instead of 5.

**Review by sandersn — APPROVED** [review]

**Comment by AnyhowStep** [comment]
I'm sorry I didn't get back sooner. I haven't been checking my GitHub notifications =(

Again, terribly sorry for not fixing it in time

**Comment by sandersn** [comment]
Not a problem, all the changes were cosmetic and didn't take me much time.
