### PR TITLE
fix use-before-init error when targeting ES2022

### LINKED ISSUE #50971: useDefineWithClassFields should use-before-init error when class property initializer refers to parameter property
# Bug Report

This bug exists in my project, not only playground, but playground seem to also have bugs, because i can't even seem to reliably reproduce it in the playground – sometimes it does not react on `Target` change. But right now i have an opened playground tab with this bug.

I will duplicate the MRE code right here as a text.
This is the source code

```typescript
class Helper {
    create(): boolean {
        return true
    }
}

export class Broken {

    constructor(readonly facade: Helper) {
        console.log(this.bug)
    }
    bug = this.facade.create()

}

new Broken(new Helper)
```

This is the compiled code with `target: ES2022` and `module: CommonJS`

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Broken = void 0;
class Helper {
    create() {
        return true;
    }
}
class Broken {
    facade;
    constructor(facade) {
        this.facade = facade;
        console.log(this.bug);
    }
    bug = this.facade.create();
}
exports.Broken = Broken;
new Broken(new Helper);
```

If run this JS – we will get TypeError

```error
Cannot read properties of undefined (reading 'create') 
```

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=9&module=1&ts=4.8.2&noImplicitUseStrict=true#code/MYGwhgzhAEASCmIAO8BO0DeAoavrFXjABd4AKASgC5oAjAe3pCIDtMc9PDiBXVN4qh7wOuAL5YJWeAA8k9VMXzgo0AEKp6Aa3htso-PRYRBPYMQVlCYACZGQAT2gAzMMFvwaCZGgrtOnMBGEEzwAHQg9ADmZMQAFgCWEGG0PFEUBhKcqVHQALzQ8Ulhru424QREpJRYkrVYLPAA7uqaOixkjS3eKKgUQA)

I'm also sharing the playground link, but i assume it could produce the right code for you if you open it first time.
To reliable reproduce – change `module` to `Node16` and then to `CommonJS`. You should see this result

Screen Shot 2022-09-27 at 19 54 16

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #50971

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2782,8 +2782,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 return !isPropertyImmediatelyReferencedWithinDeclaration(declaration, usage, /*stopAtAnyPropertyDeclaration*/ false);
             }
             else if (isParameterPropertyDeclaration(declaration, declaration.parent)) {
-                // foo = this.bar is illegal in esnext+useDefineForClassFields when bar is a parameter property
-                return !(getEmitScriptTarget(compilerOptions) === ScriptTarget.ESNext && useDefineForClassFields
+                // foo = this.bar is illegal in es2022+useDefineForClassFields when bar is a parameter property
+                return !(getEmitScriptTarget(compilerOptions) >= ScriptTarget.ES2022 && useDefineForClassFields
```
Comment (jakebailey) [inline src/compiler/checker.ts:2786]: @sandersn Was this just a case of #36425 not being updated once 

Actually, I'm pretty sure that this should just be `useDefineForClassFields` and _not_ check the script target. It seems like `getUseDefineForClassFields` already has the check for the script target and may have been missed in #42663.

Honestly, I suspect that there are other uses of the `useDefineForClassFields` which get this wrong or are at least redundant. Skimming, these are at least redundant:

- `isBlockScopedNameDeclaredBeforeUse`
- `checkAndReportErrorForInvalidInitializer`
- `getFirstTransformableStaticClassElement`

And these might be wrong and would be fixed like in this PR:

- `checkConstructorDeclarationDiagnostics`

Comment (jakebailey) [reply src/compiler/checker.ts:2786]: There of course may be a nuance I'm totally missing here.

Comment (Zzzen) [reply src/compiler/checker.ts:2786]: I completely agree with you. The checks for the emit target are unnecessary and should be removed.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -38634,7 +38634,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                     //   or the containing class declares instance member variables with initializers.
 
                     const superCallShouldBeRootLevel =
-                        (getEmitScriptTarget(compilerOptions) !== ScriptTarget.ESNext || !useDefineForClassFields) &&
+                        (!useDefineForClassFields) &&
```
Comment (jakebailey) [inline src/compiler/checker.ts:38637]:
```suggestion
                        !useDefineForClassFields &&
```

File: tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.errors.txt [hunk 3]
```diff
@@ -30,6 +31,9 @@ assignParameterPropertyToPropertyDeclarationES2022.ts(12,17): error TS2729: Prop
 !!! error TS2729: Property 'baz' is used before its initialization.
 !!! related TS2728 assignParameterPropertyToPropertyDeclarationES2022.ts:13:5: 'baz' is declared here.
         baz = this.foo; // should error
+                   ~~~
+!!! error TS2729: Property 'foo' is used before its initialization.
+!!! related TS2728 assignParameterPropertyToPropertyDeclarationES2022.ts:11:17: 'foo' is declared here.
```
Comment (jakebailey) [inline tests/baselines/reference/assignParameterPropertyToPropertyDeclarationES2022.errors.txt:36]: This seems good!

File: tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).errors.txt [hunk 4]
```diff
@@ -1,12 +0,0 @@
-classMemberInitializerScoping2.ts(3,9): error TS2301: Initializer of instance member variable 'p' cannot reference identifier 'x' declared in the constructor.
-
-
-==== classMemberInitializerScoping2.ts (1 errors) ====
-    const x = 1
-    class C {
-        p = x
-            ~
-!!! error TS2301: Initializer of instance member variable 'p' cannot reference identifier 'x' declared in the constructor.
```
Comment (jakebailey) [inline tests/baselines/reference/classMemberInitializerScoping2(target=es2017,usedefineforclassfields=true).errors.txt:9]: This test has the combo of es2017/esnext and useDefineForClassFields=true/false. Before, es2017 always errored, and esnext only errored when useDefineForClassFields=false.

Now, es2017 with useDefineForClassFields=false also no longer errors.

Is that correct? I'm not totally sure. @sandersn

File: tests/cases/conformance/classes/propertyMemberDeclarations/initializationOrdering1.ts [hunk 5]
```diff
@@ -0,0 +1,18 @@
+// @target: esnext, es2021, es2022
+// @useDefineForClassFields: true
```
Comment (jakebailey) [inline tests/cases/conformance/classes/propertyMemberDeclarations/initializationOrdering1.ts:2]:
```suggestion
// @target: esnext, es2021, es2022
// @useDefineForClassFields: false, true
```

This should work and let you eliminate that other file, and make the baselines more clear, I think.

**Review by jakebailey — COMMENTED** [review]
Theoretically I think that this is okay, but I definitely want @sandersn / @rbuckton to double check this as even though my gut tells me that all of these other changed things (in the most recent commit) are actual fixes, I'm not totally confident in knowing the entire semantics.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot pack this

**Review by sandersn — CHANGES_REQUESTED** [review]
As far as I can tell, tsc almost worked correctly before this PR: it provides an error for ES2022 standard class fields and does not when they're downleveled via Object.defineProperty or simple assignment: 

https://www.typescriptlang.org/play?moduleResolution=99&module=1&useDefineForClassFields=true#code/MYGwhgzhAECqDmALaBvAUNT0BWBXCALtALzQBEA7ogJ5kZYAOIAppMydABQCUJAfNAKIAlhAB0TVhGb1MAE2EAnZsCKkhosQA9Z0YAHsAdoUW5V+xZwa4ARiGHBoWgFzRDuALY3mi3uizQAL662GAAbmAAZhwa4jrBaKCQMAASzCAMPqi6wMpgBMw8rjb6+ixghtkBAcoEuIqVBKYyAcHBSVDQAEKK+gDWzJXoOUYmZgQWnHlyRiDU0JFgwGByzK5pGT5+ugEGxmXMYiD68JyxYja48Ny6wQGX8DEi4ovLq2K5rAU8aGgJhswKN1egNDJwAUCNplfEA

The only problem is that (===ESNext) needs to change to (>=ES2022) everywhere in the code.

I also suggested that `var useDefineForForClassFields` should maybe include the ES2022 check so that it's used consistently everywhere.

File: src/compiler/checker.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/checker.ts:2786]: > Maybe it would be a good idea to introduce a new variable `emitStandardClassFields` that combines ES2022+ and useDefineForClassFields. Actually, useDefineForClassFields is combined with the ES2022 check often enough that it's likely that `var emitStandardClassFields` should _replace_ `var useDefinedForClassFields`.

I'm confused; isn't that what the `useDefineForClassFields` variable is after #42663?


```
var useDefineForClassFields = getUseDefineForClassFields(compilerOptions);

// ...
export function getUseDefineForClassFields(compilerOptions: CompilerOptions): boolean {
    return compilerOptions.useDefineForClassFields === undefined ? getEmitScriptTarget(compilerOptions) >= ScriptTarget.ES2022 : compilerOptions.useDefineForClassFields;
}
```

Comment (sandersn) [reply src/compiler/checker.ts:2786]: Almost, but when `{ useDefineForClassFields: true, target: "ES2017" }`, getUseDefineForClassFields is true but emitStandardClassFields would be false.

Comment (sandersn) [reply src/compiler/checker.ts:2786]: (emitStandardClassFields would be `compilerOptions.useDefineForClassFields !== false && getEmitScriptTarget(compilerOptions) >= ScriptTarget.ES2022`)

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this

**Review by sandersn — APPROVED** [review]
I wish we didn't still need `useDefineForClassFields`, but I checked the 3 remaining uses and they're all still (reasonably) correct.

Even more wishful thinking: someday it would be nice to drop `--useDefineForClassFields`, but I think a few big projects may still use it for some time.

**Comment by rbuckton** [comment]
I'm still of the opinion the underlying issue is with the emit, which I [mentioned in the linked bug](https://github.com/microsoft/TypeScript/issues/50971#issuecomment-1301484544). I've been meaning to circle back on that after finishing the class fields emit-related changes for ES Decorators following 5.1, but haven't had time yet.

I suppose it's fine to issue an error for now in lieu of actually fixing the emit issue, but I do think we should take the time to fix the emit issue in the future and remove this restriction. If we ever plan to fix this, it would probably be a good idea to either *not* mark this as fixing #50971, or leave it as fixing #50971 and create a new issue that recommends an emit fix so that we don't lose track of the issue.

**Comment by fatcerberus** [comment]
@rbuckton Not sure I can agree with the proposed emit in the linked comment - moving the initializer from a classfield into the constructor observably changes runtime behavior of JS code which violates design goals, and in a way that can’t be justified by inaccurate downleveling (`bug` isn’t actually being downleveled, it’s still a native classfield).

**Comment by sandersn** [comment]
@fatcerberus let's have that discussion on a new bug: #55132 

@rbuckton Are you OK to merge this? It is at least a fix for an existing restriction, even if that restriction is incorrect.
