### PR TITLE
Don't treat an instantiation expression as an assertion in skipOuterExpressions

### LINKED ISSUE #59535: Instantiation expressions shouldn't be allowed in write positions
### 🔎 Search Terms

instantiation expression write read positions type arguments functions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240805#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChnIhwC2EAXMumFKAOYDc+yct5hArsQEbSMC+uXKEixEKAPJcAVjiYwQAHgAqAPgAUASgpL+uACYQEAGzhQUCAPYgqyC9IqSpjfYZNnkl62GTtMUALIWCADWFJrIALwqaH7OAPRxyGAAFsDolMkW7EZ6IADk3jzMRkYWAO4Qerh2UgB08goY0NERPn6BIc4GxqYoRhDe8hTK6hqR0UqCCUmp6eiZ2bkFyEVwJeWVyBDAKdC4DU1QLW3QHcG4QA

### 💻 Code

```ts
interface User {
  name: string;
  age: number;
}

interface Obj {
  fn<T>(): T;
}
declare const obj: Obj;

declare const userMock: () => User;

// this shouldn't be allowed
obj.fn<User> = userMock;

declare let fn: <T>() => T

// this shouldn't be allowed either
fn<User> = userMock
```

### 🙁 Actual behavior

Those instantiation expressions are allowed

### 🙂 Expected behavior

They shouldn't be

### Additional information about the issue

it has been "discovered" here: https://x.com/kettanaito/status/1820456054724993191 😅

### PR DESCRIPTION
**Pull request by jakebailey**
#50820 added `ExpressionWithTypeArguments` to `isOuterExpression` but treated it as an assertion, which then caused the checker to skip past it in reference checking. Split that out so we can skip past it in transforms like we did previously, which feels better because an instantiation is not really an assertion.

Also, while here, fix the fact that other `OuterExpression` related code was not `ExpressionWithTypeArguments` either.

Fixes #59535

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

File: src/compiler/factory/nodeFactory.ts [hunk 1]
```diff
@@ -6553,6 +6553,8 @@ export function createNodeFactory(flags: NodeFactoryFlags, baseFactory: BaseNode
                 return updateSatisfiesExpression(outerExpression, expression, outerExpression.type);
             case SyntaxKind.NonNullExpression:
                 return updateNonNullExpression(outerExpression, expression);
+            case SyntaxKind.ExpressionWithTypeArguments:
+                return updateExpressionWithTypeArguments(outerExpression, expression, outerExpression.typeArguments);
```
Comment (jakebailey) [inline src/compiler/factory/nodeFactory.ts:6557]: I will note that most of the cases here are uncovered by tests: 
image

**Review by weswigham — APPROVED** [review]
