### PR TITLE
fix(44693): Overriden properties in jsdoc annotation are not picked up in declaration file

### LINKED ISSUE #44693: Overriden properties in jsdoc annotation are not picked up in declaration file
# Bug Report

### 🔎 Search Terms

typescript jsdoc declaration override method property signature

### 🕗 Version & Regression Information

- This changed between versions  3.8.3 and 3.9.7.

### ⏯ Playground Link

[Example JavaScript with JSDoc](https://www.typescriptlang.org/play?strictFunctionTypes=false&ts=4.3.2&filetype=js#code/PQKhFgCgAIWgBALgTwA4FMAm6Bm0CCUsCqATgPYakrQDeAzoqQJYB2A5gL7QCGRIwKFFAQYcJGiy5oAIX4kKVGrVYBXALYAjdKW6b+gyFADGAGx716si+jpFoDkfYfEJGOvk7OHA7wDceU1V0AG4oLyNIMwsrABV0Rmh0AA9EdFZMKxkbOxgXJzyXcRR3WnxoADJZCJcfQ1qAoNDwoSjyVkTEaABeaFZ0AHdoeMYACgBKMMggA)

### 💻 Code

```js
/**
 * @typedef A
 * @property {string} a
 */

/**
 * @typedef B
 * @property {number} b
 */

class Base {
    /**
     * @type {A}
     */
    value;
}

class Test extends Base {
    /**
     * @type {A & B}
     */
    value;
}
```

### 🙁 Actual behavior

The declaration file does not contain a typing for the narrower type for value in class Test.

```
declare class Test extends Base {
}
```

### 🙂 Expected behavior

The declaration file should contain the narrower type for value.

```
declare class Test extends Base {
    /**
     * @type {A & B}
     */
    value: A & B;
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #44693

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -39048,7 +39048,7 @@ namespace ts {
                 const properties = getPropertiesOfType(getTypeWithThisArgument(base, type.thisType));
                 for (const prop of properties) {
                     const existing = seen.get(prop.escapedName);
-                    if (existing && !isPropertyIdenticalTo(existing, prop)) {
+                    if (existing && prop.parent === existing.parent && !isPropertyIdenticalTo(existing, prop)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:39051]: I don't understand this fix. For the test cases, I thought that the existing check `!isPropertyIdenticalTo` would 

* remove C2.value because its type `A` is identical to C1.value's type.
* keep C3.value because `A & B` isn't identical to C1.value's type.

Why isn't that true?

I also thought that `prop.parent === existing.parent` would be false for any base property with an override, meaning that both C2.value and C3.value would be kept. But this isn't the case. Why not?

**Review by sandersn — CHANGES_REQUESTED** [review]
I don't understand why this fix works. Can you explain?

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:39051]:
```ts
class C1 {
    /**
     * @type {A}
     */
    value;
}

class C2 extends C1 {
    /**
     * @type {A & B}
     */
    value;
}
```

We set properties from `C2` to `seen`,
```ts
Map({ value /* A & B */ })
```

then we iterate over all the properties of the base types. In this case, we only have one property `[value / * A * /]`.

```ts
!isPropertyIdenticalTo(existing /* value: A & B*/, prop /* A */)
```
props are not identical, so we drop value from `seen`, as a result, `seen` is empty. 
```ts
arrayFrom(seen.values()); // []
```

I found that we can filter properties based on property `parent`

```ts
class C1 {
    /**
     * @type {A}
     */
    value;
}

class C2 extends C1 {
}
```

```ts
const seen = Map({ value /* A */ })
```

```ts
const baseProps = [value /* A */ ]
```

if props / * existing / prop * / refer to the same `parent`, it can be inherited in the child class, then we compare with the identity. Maybe it is a completely wrong way and needs to use another one. In this case, I'm really sorry that you wasted time reviewing this PR., I'll close the PR later.

Comment (sandersn) [reply src/compiler/checker.ts:39051]: I think I am confused about the purpose of getNonInheritedProperties as a while. I rewrote it with names that match what is happening, as far as I can tell, and:

1. It seems to do the *opposite* of what its name is -- it gets all properties of the derived class and removes the ones that are *not* identical to some base property. That is, it removes the *non*-inherited ones and returns the inherited ones.
2. But this makes no sense -- when emitting a class, the correct properties to emit are the non-inherited ones.

```ts
        function getInheritedProperties(type: InterfaceType) {
            const derivedProperties = getPropertiesOfType(type)
            const baseTypes = getBaseTypes(type) // this is cached; the function is easier to read with fewer parameters
            if (!length(baseTypes)) {
                return derivedProperties;
            }
            const inherited = new Map<__String, Symbol>();
            forEach(derivedProperties, p => {
                inherited.set(p.escapedName, p);
            });

            for (const baseType of baseTypes) {
                for (const base of getPropertiesOfType(getTypeWithThisArgument(baseType, type.thisType))) {
                    const derived = inherited.get(base.escapedName);
                    if (derived && !isPropertyIdenticalTo(derived, base)) {
                        // derived is not overriden, but inherited (or overridden with the exact same type)
                        inherited.delete(base.escapedName);
                    }
                }
            }

            return arrayFrom(inherited.values());
        }
```

3. I re-ran tests with `!isPropertyIdenticalTo` reversed to `isPropertyIdenticalTo` and the test is from #37970, which fixes `this`-typed methods.

I'm out of my depth here. @weswigham, can you take a look at this PR?

Comment (weswigham) [inline src/compiler/checker.ts:39051]:
```suggestion
                    if (existing && prop.parent === existing.parent) {

```

You can do away with the identity check entirely - the `.parent` similarity check is sufficient. Dunno why I didn't think of that originally.

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:39051]: @weswigham Thanks.

**Review by weswigham — APPROVED** [review]
