### PR TITLE
Refrain from attempting to perform parameter fixing on a generic signature multiple times

### LINKED ISSUE #43833: Contextually inferred generic function with generic rest parameter not assignable to itself
# Bug Report

### 🔎 Search Terms

contextual, generic, inference, rest parameter, ts2345

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcA8BBRBTAHlbMAEwGdEBDMATwG0BdAPgAoBYAKEQoCcBzALkRoAKjnyFSiAN4UBYEAFsARti6IAvsygChAGkQA6Q12wktiDAEpEAXgaI5SleyvS17dijhMmUPSFkKylxWtohQ+uQW7AD0AFTmvAqEUIhwwGFUAA7Y7JwA5MKiBMRk0uQBjlwA3Oqa2n4VQSF2DkF5iDBkYHAp5CQkMDxg5IoANthhcIiZ5Fzk8tgEqmkZ2bmIBSJ4xRJljSo1Gj71iP72gSrN55V5+uuAfBuAKLtPT+yx0UA)

### 💻 Code

```ts
function foo<A extends any[]>(
  arg: <T extends { a: number }>(t: T, ...rest: A) => number
) { }

foo((t, u: number) => t.a)
/* Argument of type
  '<T extends { a: number; }>(t: T, u: number) => number' is not assignable to parameter of type
  '<T extends { a: number; }>(t: T, u: number) => number'.
  🤔🤔🤔
*/
```

### 🙁 Actual behavior

The compiler infers that `(t, u: number) => t.a` is of type `<T extends {a: number}>(t: T, u: number) => number`, but then complains that this type is not assignable to itself (or at least an identically written type).  The problem seems to be that the two generic `T`'s can't be unified for some reason.

### 🙂 Expected behavior

The compiler should infer the function type as it's doing now, but without futher complaint.

---

Comes from [this Stack Overflow question](https://stackoverflow.com/questions/67271869/using-rest-parameters-syntax-causes-errors).  I don't really quite get the use case; presumably a real world application would have more than one site where `T` appears, like `<T extends { a: number }>(t: T, ...rest: A) => T`, which has the same problem.

Is there an existing issue that mentions this?  Is it intended?  Limitation?  Genuine bug?

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #43833

We would perform contextual parameter fixing twice on the same signature (against different instantiations of the target signature) - once during generic propagation, and again later when doing contextual typing. This caused the `typeParameters` of the signature being fixed to get mutated, while the cached calculated type of each parameter was unchanged, causing a type parameter mismatch leading to inference failure. Since signatures are supposed to be immutable-ish, I  disallowed the second fixing pass if the first fixing pass has occurred. Additionally, there is now a debug assertion in parameter fixing for if we attempt to fix a type to a parameter and it already has a cached type which differs from the type we want to fix. Logically, we never want this to happen (since we can only contextually fix a given signature once), so the assertion should only be triggered if we've broken this subtle invariant somewhere.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -30395,6 +30402,9 @@ namespace ts {
                     assignBindingElementTypes(declaration.name);
                 }
             }
+            else if (type) {
+                Debug.assertEqual(links.type, type);
```
Comment (sandersn) [inline src/compiler/checker.ts:30406]: This is a good idea, but I think I'd wait until after the beta to merge this assertion.

(based on my experience putting a subtle assertion into overload error reporting)

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -30345,7 +30345,14 @@ namespace ts {
         }
 
         function assignContextualParameterTypes(signature: Signature, context: Signature) {
-            signature.typeParameters = context.typeParameters;
+            if (context.typeParameters) {
```
Comment (sandersn) [inline src/compiler/checker.ts:30348]: Is context.typeParameters ever `undefined`? Was that the bug here?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -30345,7 +30345,14 @@ namespace ts {
         }
 
         function assignContextualParameterTypes(signature: Signature, context: Signature) {
-            signature.typeParameters = context.typeParameters;
+            if (context.typeParameters) {
+                if (!signature.typeParameters) {
+                    signature.typeParameters = context.typeParameters;
+                }
+                else {
+                    return; // This signature has already has a contextual inference performed and cached on it!
```
Comment (sandersn) [inline src/compiler/checker.ts:30353]: Double-checking my understanding; is this correct?: it's enough to bail after seeing that typeParameters is set, because a normal run of this function sets both typeParameters and parameters. So you don't have to check parameters as well.

**Review by sandersn — CHANGES_REQUESTED** [review]
One comment and some background questions.

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts:30353]: Aye. Moreover, if a function somehow has type parameters set already, but not parameters, fixing parameters which contain a separate set of type parameters would be bad, too. (It'd be like the inverse of the original issue that caused the report)

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:30348]: I mean, I don't want to overwrite a signature's type parameters with `undefined`, and there's no reason to do anything if they're _both_ `undefined`.
