### PR TITLE
Fix type when annotated with a JSDoc function type

### LINKED ISSUE #22080: Required parameters are not checked in JS files
**TypeScript Version:**  2.8.0-dev.20180220

**Search Terms:** 
* jsdoc
* checkJs
* function type
* arguments

**Code**

```js
/** @type {function(string): void} */
const func = (value) => {
    // ...
}

// Following line should raise an error as 'func' invocation
// is missing required parameter, but it doesn't happen.
func();
```

**Expected behavior:**
An error `Expected 1 argument, but got 0.` should be thrown.

**Actual behavior:**
No error is thrown. TypeScript allows to invoke former function without passing arguments to it.

### PR DESCRIPTION
**Pull request by sandersn**
Previously,
1. A variable annotated with a JSDoc function type would not require all its parameters to be provided. This should only apply to functions without a type annotation.
2. A parameter in a function with a JSDoc function type annotation would still have the type 'any'.
3. Two `var` declarations in a Typescript and Javascript file, respectively, would error even when they had identical function types.

Fixes #22080

I don't think there are bugs filed for (2) or (3).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6699,7 +6699,13 @@ namespace ts {
                 let hasThisParameter: boolean;
                 const iife = getImmediatelyInvokedFunctionExpression(declaration);
                 const isJSConstructSignature = isJSDocConstructSignature(declaration);
-                const isUntypedSignatureInJSFile = !iife && !isJSConstructSignature && isInJavaScriptFile(declaration) && !hasJSDocParameterTags(declaration);
+                const isUntypedSignatureInJSFile = !iife &&
+                    !isJSConstructSignature &&
+                    isInJavaScriptFile(declaration) &&
+                    declaration.kind !== SyntaxKind.FunctionType &&
```
Comment (weswigham) [inline src/compiler/checker.ts]: `ConstructorType`?

**Comment by sandersn** [comment]
Yep, good catch. Also I forgot to update baselines. A few of them changed now that more types are available.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6699,7 +6699,14 @@ namespace ts {
                 let hasThisParameter: boolean;
                 const iife = getImmediatelyInvokedFunctionExpression(declaration);
                 const isJSConstructSignature = isJSDocConstructSignature(declaration);
-                const isUntypedSignatureInJSFile = !iife && !isJSConstructSignature && isInJavaScriptFile(declaration) && !hasJSDocParameterTags(declaration);
+                const isUntypedSignatureInJSFile = !iife &&
```
Comment (weswigham) [inline src/compiler/checker.ts]: What case is handling when the declaration is an object literal with construct signatures, (ie, `{(): void}`)?

Comment (sandersn) [reply src/compiler/checker.ts]: `!getJSDocType(declaration)`. I'll add a test case. Note that the new code in `getJSDocType` doesn't look deep enough to get type of the parameter out of the method declaration inside the object literal type.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6699,7 +6699,14 @@ namespace ts {
                 let hasThisParameter: boolean;
                 const iife = getImmediatelyInvokedFunctionExpression(declaration);
                 const isJSConstructSignature = isJSDocConstructSignature(declaration);
-                const isUntypedSignatureInJSFile = !iife && !isJSConstructSignature && isInJavaScriptFile(declaration) && !hasJSDocParameterTags(declaration);
+                const isUntypedSignatureInJSFile = !iife &&
+                    !isJSConstructSignature &&
```
Comment (andy-ms) [inline src/compiler/checker.ts]: `!isJSConstructSignature` is redundant if we test `declaration.kind !== SyntaxKind.FunctionType` anyway.

File: src/compiler/utilities.ts [hunk 4]
```diff
@@ -4510,6 +4510,15 @@ namespace ts {
         let tag: JSDocTypeTag | JSDocParameterTag | undefined = getFirstJSDocTag(node, isJSDocTypeTag);
         if (!tag && isParameter(node)) {
             tag = find(getJSDocParameterTags(node), tag => !!tag.typeExpression);
+            if (!tag && isFunctionLike(node.parent)) {
+                const typeTag = getJSDocTypeTag(node.parent);
+                if (typeTag && typeTag.typeExpression && isFunctionLike(typeTag.typeExpression.type)) {
+                    const i = node.parent.parameters.indexOf(node);
+                    if (i > -1) {
+                        return typeTag.typeExpression.type.parameters[i].type;
```
Comment (andy-ms) [inline src/compiler/utilities.ts]: Needs a length check -- we don't know that `typeTag.typeExpression.type` has the same # parameters as the actual function.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -14191,49 +14199,49 @@ namespace ts {
...
-                    const cached = links.resolvedSignature;
-                    links.resolvedSignature = anySignature;
-                    const type = indexOfParameter < iife.arguments.length ?
-                        getWidenedLiteralType(checkExpression(iife.arguments[indexOfParameter])) :
-                        parameter.initializer ? undefined : undefinedWideningType;
-                    links.resolvedSignature = cached;
-                    return type;
+            if (!isContextSensitiveFunctionOrObjectLiteralMethod(func)) {
+                return undefined;
+            }
```
Comment (sandersn) [inline src/compiler/checker.ts]: This change is just an inversion of the guard and a subsequent un-indent.

**Comment by sandersn** [comment]
@weswigham I moved the change from `getJSDocType` to `getContextualSignature` after our discussion this morning.

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Nice catch. Removed.

File: tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt [hunk 6]
```diff
@@ -22,21 +20,19 @@ tests/cases/conformance/jsdoc/0.js(22,22): error TS2345: Argument of type '"0"'
...
+!!! error TS2322: Type '(n1: number) => string' is not assignable to type '(arg0: number) => number'.
 !!! error TS2322:   Type 'string' is not assignable to type 'number'.
       /** @type {function(number): number} */
       arrowFunc: (num="0") => num + 42,
-      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-!!! error TS2322: Type '(num?: string) => string' is not assignable to type '(arg0: number) => number'.
-!!! error TS2322:   Types of parameters 'num' and 'arg0' are incompatible.
-!!! error TS2322:     Type 'number' is not assignable to type 'string | undefined'.
+                  ~~~~~~~
+!!! error TS2322: Type '"0"' is not assignable to type 'number'.
```
Comment (weswigham) [inline tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt]: Do you know why we infer a literal type here now? AFAIK we only generate a literal if the contextual type of the literal is the same domain as the literal itself, which would imply that the contextual type here is `string`, which seems wrong, given the annotation above.

Comment (sandersn) [reply tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt]: The inferred type of "0" is for the initialiser, which was already of type "0" (see the type baselines below). You get the same error in Typescript with an type annotation, too:

```ts
function f(x: number = "hi") {
}
```

Gives the error "Type "hi" is not assignable to type 'number'." This error is expected now that `num` is of type `number` from contextual typing. Previously the arrow was typed with no contextual type, then assigned to `arrowFunc` and checked against its type annotation.

Comment (weswigham) [reply tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt]: Hm. OK.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -6699,7 +6699,13 @@ namespace ts {
                 let hasThisParameter: boolean;
                 const iife = getImmediatelyInvokedFunctionExpression(declaration);
                 const isJSConstructSignature = isJSDocConstructSignature(declaration);
-                const isUntypedSignatureInJSFile = !iife && !isJSConstructSignature && isInJavaScriptFile(declaration) && !hasJSDocParameterTags(declaration);
+                const isUntypedSignatureInJSFile = !iife &&
+                    isInJavaScriptFile(declaration) &&
+                    declaration.kind !== SyntaxKind.FunctionType &&
```
Comment (weswigham) [inline src/compiler/checker.ts]: Rather than skipping (some of the) the type-space signature declaration kinds, can we just check if it _is_ a concrete declaration kind? That is the point here, right; to exclude type-space declaration kinds?

```ts
export type ConcreteSignatureDeclaration =
        | FunctionDeclaration
        | MethodDeclaration
        | ConstructorDeclaration
        | AccessorDeclaration
        | FunctionExpression
        | ArrowFunction;

export function isConcreteSignatureDeclaration(declaration: Node): node is ConcreteSignatureDeclaration {
    return isFunctionExpression(declaration) || isArrowFunction(declaration) || isMethodOrAccessor(declaration) || isFunctionDeclaration(declaration) || isConstructorDeclaration(declaration);
}
```

File: tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt (hunk 6 above)
Comment (sandersn) [reply tests/baselines/reference/checkJsdocTypeTagOnObjectProperty2.errors.txt]: It's not great, but it's consistent with the rest of the the compiler. Note that our baselines have gone back and forth on this in the last year or two.

File: src/compiler/checker.ts (hunk 7 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Yes, a type signature is by definition not untyped, even if it's in a JS file. I used your code in the new commit.

**Comment by brendankenny** [comment]
@sandersn Not sure how your point releases work exactly, but any chance of this being pulled into 2.8.2 or whatever is next? It appears it didn't make it into 2.8.1 and it unlocks a lot of type checking goodness via jsdocs :)

**Comment by sandersn** [comment]
Chances are not good. We keep point releases down to fixing regressions from the major release, and the bugs fixed in this PR have been around for ages. We have a major release every 6-8 weeks, so 2.9 should at least have a release candidate by then. :)

**Comment by brendankenny** [comment]
Got it, no problem. Thanks! And thanks for all the work getting these working.
