### PR TITLE
Fix parsing of parenthesized JSDoc parameters

### LINKED ISSUE #25779: Parens on union type fail for function arguments (JSDoc style)
**TypeScript Version:**  typescript@3.1.0-dev.20180717

**Search Terms:** function arguments grouped union type

**Code**

I notice that if a union type is grouped with `(` and `)` it works as a return type but not as an argument type.  For example, this does not work:

```js
/**
 * @typedef {function((string|undefined)): (string|undefined)} SomeType
 */
```

While this does work:

```js
/**
 * @typedef {function(string|undefined): (string|undefined)} SomeType
 */
```

**Expected behavior:**

With this `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ES2017",
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,
    "strict": false,
  },
  "include": [
    "src/**/*.js"
  ]
}
```

I expected `tsc` to succeed.

**Actual behavior:**

```

src/main.js:2:23 - error TS1138: Parameter declaration expected.

2  * @typedef {function((string|undefined)): (string|undefined)} SomeType
                        ~

src/main.js:2:41 - error TS1005: '}' expected.

2  * @typedef {function((string|undefined)): (string|undefined)} SomeType
                                          ~
```

Perhaps this is a known limitation.  I can remove the parens.  But I thought it might also be a parsing bug.

### LINKED ISSUE #25800: JSDoc function type doesn't parse jsdoc function types as parameters
In other words, higher order functions don't work using only closure syntax:

```js
/** @type {function(string[], function(string): string): string[]} */
var stringmap = function(strings, f) {
    // ...
}
```

**Expected behavior:**
`stringmap: (arg0: string[], arg1: (arg0: string) => string) => string[]`

**Actual behavior:**
Parse error at the second function keyword: "Parameter expected".

### PR DESCRIPTION
**Pull request by sandersn**
Parenthesis can start a jsdoc function parameter since it is just a type, and parenthesis can start a type:

```js
/** @type {function(((string))): void} */
```

However, this is not legal in other parameter lists:

```ts
function x((((a))): string) { }
```

This change makes jsdoc function parameter lists parse differently than normal parameter lists by allowing parenthesis as a start character of jsdoc parameters.

Fixes #25779 
Fixes #25800

### CODE REVIEW

File: tests/cases/conformance/jsdoc/jsdocParseHigherOrderFunction.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// @noemit: true
+// @allowjs: true
+// @checkjs: true
+// @strict: true
+// @Filename: paren.js
+/** @type {function((string), function((string)): string): string} */
+var x = s => s.toString()
```
Comment (andy-ms) [inline tests/cases/conformance/jsdoc/jsdocParseHigherOrderFunction.ts]: Would be nice to give the arrow function 2 parameters to verify that the contextual type is correct.

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -1509,7 +1509,9 @@ namespace ts {
                 case ParsingContext.ArgumentExpressions:
                     return token() === SyntaxKind.DotDotDotToken || isStartOfExpression();
                 case ParsingContext.Parameters:
-                    return isStartOfParameter();
+                    return isStartOfParameter(/*isJSDocParameter*/ false);
+                case ParsingContext.JSDocParameters:
+                    return isStartOfParameter(/*isJSDocParameter*/ true);
```
Comment (andy-ms) [inline src/compiler/parser.ts]: Does anything bad happen if we just always treat `(` as the start of a parameter? It's a parse error anyway, right?

File: tests/cases/conformance/jsdoc/jsdocParseHigherOrderFunction.ts (hunk 1 above)
Comment (sandersn) [reply tests/cases/conformance/jsdoc/jsdocParseHigherOrderFunction.ts]: Oops, I forgot to copy over the newer version of my in-editor test buffer. Fixed.

File: src/compiler/parser.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/parser.ts]: Let me try it ...

Comment (sandersn) [reply src/compiler/parser.ts]: It disrupts parsing quite a bit. I'm not sure why, but it appears to cause type parameter lists to be parsed as parameter lists in arrow functions, and it also breaks function expressions inside object literal property assignments.
