### PR TITLE
Fix bug: only getCompletionEntriesFromTypings if completions are for top-level directory

### LINKED ISSUE #27033: Don't return node modules in path intellisense after directory
From https://github.com/Microsoft/vscode/issues/58340

**TypeScript Version:**  3.1.0-dev.20180907

**Search Terms:**
- Path intellisense
- node modules

**Code**
In a new project, run:

```
npm i @types/node
```

Then trigger suggestions after the `/` in a file:

```ts
import {} from 'no/such/dir/'
```

**Expected behavior:**
No suggestions returned

**Actual behavior:**
Suggestions for node modules returned here:

screen shot 2018-09-11 at 11 54 58 am

```
[Trace  - 11:49:15 AM] Response received: completionInfo (71). Request took 2 ms. Success: true 
Result: {
    "isGlobalCompletion": false,
    "isMemberCompletion": false,
    "isNewIdentifierLocation": true,
    "entries": [
        {
            "name": "node",
            "kind": "external module name",
            "kindModifiers": "",
            "sortText": "0"
        },
        {
            "name": "prop-types",
            "kind": "external module name",
            "kindModifiers": "",
            "sortText": "0"
        },
        {
            "name": "react",
            "kind": "external module name",
            "kindModifiers": "",
            "sortText": "0"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #27033

### CODE REVIEW

File: tests/cases/fourslash/completionsPaths_fromTypings_notIfComponentAlreadyTyped.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+/// <reference path="fourslash.ts" />
+
+// @Filename: /node_modules/@types/foo/index.d.ts
+////
+
+// @Filename: /a.ts
+////import {} from "unrelated//**/";
+
```
Comment (sheetalkamat) [inline tests/cases/fourslash/completionsPaths_fromTypings_notIfComponentAlreadyTyped.ts]: Is there a test for `import {} from "foo//**/"`?

**Comment by andy-ms** [comment]
@sheetalkamat Please re-review
