### PR TITLE
fix(36102): fix extra new line in Organize Imports

### LINKED ISSUE #36102: TypeScript Organize Imports inserts extra newline
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20200108

**Search Terms**
- Organize imports

---

In TypeScript / JavaScript, the command `Organize Imports` inserts up to two newlines if `export { ... };` is at the end of a file. This does not happen with other forms of `export`.

- VSCode Version: 1.41.1
- OS Version: Windows 10 (1803)

Steps to Reproduce:
1. Have a list / renamed export as the last line of your file, e.g.:
```
import { Router } from 'express';
const router = Router();
// ... other code
export { router as namedRouter }; // also happens with `export { router };`
```
2. Run the `Organize Imports` command. It will insert a newline after the `export { ... };`
3. Run the `Organize Imports` command again. It will insert another newline, resulting in two empty lines at the end of the file.

**Expected behavior**
Only one newline is inserted / kept after the `export { ... };`.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by sacgrover**
Organize Imports was inserting extra newline.

Fixes #36102

### CODE REVIEW

**Comment by sandersn** [comment]
@elibarzilay mind taking a look at this PR?

**Comment by sandersn** [comment]
@andrewbranch is this related to #36688 ?

**Comment by andrewbranch** [comment]
It is not.

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -889,7 +889,7 @@ namespace ts.textChanges {
                 : format(change.node);
             // strip initial indentation (spaces or tabs) if text will be inserted in the middle of the line
             const noIndent = (options.preserveLeadingWhitespace || options.indentation !== undefined || getLineStartPositionForPosition(pos, sourceFile) === pos) ? text : text.replace(/^\s+/, "");
-            return (options.prefix || "") + noIndent + (options.suffix || "");
+            return (options.prefix || "") + noIndent + (((options.suffix && noIndent.match(options.suffix+"$")) || !options.suffix) ? "" : options.suffix);
```
Comment (elibarzilay) [inline src/services/textChanges.ts]: I don't like the implicit coercion of a string to a regexp without quoting, but it seems that this only checks for a suffix, so maybe something like the following?  Also, a single line is very hard to read, the following is a reorg + some simplification of the condition.

```suggestion
            return (options.prefix || "") + noIndent
                 + ((!options.suffix || endsWith(noIndent, options.suffix))
                    ? "" : options.suffix);
```

Comment (sacgrover) [reply src/services/textChanges.ts]: modified

Comment (elibarzilay) [reply src/services/textChanges.ts]: Do you mind also indenting the `+ ...` part so it's not on the same level as the `return`?
