### PR TITLE
Fix initialization error when destructuring from object literal that includes a spread assignment

### LINKED ISSUE #36214: Supposedly uninitialised default object destructing value in case where that value is obviously known
**TypeScript Version:**  3.7.2 (any version in reality)

**Search Terms:** Initializer provides no value for this binding element and the binding element has no default value

**Code**

```ts
// This simulates a situation where function's param can be either a string, or an options object with that string as one of the values
const stringOrObjectParam = Math.random() > .5 ? 'string param' : { baz: 'object param' }

const isStringParam = (param: string | {}): param is string => typeof param === 'string'

// One of the typical ways in JS to provide default values
const { foo, bar } = {
  bar: 'default value',
  ...(isStringParam(stringOrObjectParam) ? { foo: stringOrObjectParam } : stringOrObjectParam),
}
```

**Expected behavior:** No error (`bar` is always known as either derived from `stringOrObjectParam` or being `'default value'`).

**Actual behavior:** Error: `Initializer provides no value for this binding element and the binding element has no default value.` for `bar` in `const { foo, bar } = {`

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=2#code/MYewdgzgLgBNBOBLMBzA8vNAjAVgU2CgAUBDeEgWxgF4YBZEqACwDpywATECgCgEoYAPhgsArDAD8MAOQJkMAA5lK0mAC4YAbxhYSALw3SQuArCXkKqgL4AoG6EixEEAMpQkqUhZowe5yhpyqDAAPlpWfBr+VM5w7sgoNMJQAJ4KeCAAZorKVNT5MkEo0nYO0FowmSAgADQ6ZDBWPpo2MPXwhhx4mSQArgA2sABuJP29eNI1rSIsLDzObh4oXpQ8RRjY+IQrFAJS2lUggfGoGybbuY3qcUtnW8S5fFNWQA

**Related Issues:** There are a lot of issues that report this error as a bug, in which it's proved that bug it was not. In this case, however, I don't see how `bar` could be considered uninitialised.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #36214

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22469,9 +22469,11 @@ namespace ts {
 
             // If object literal is contextually typed by the implied type of a binding pattern, augment the result
             // type with those properties for which the binding pattern specifies a default value.
-            if (contextualTypeHasPattern) {
+            // If the object literal is spread into another object literal, skip this step and let the top-level object
+            // literal handle it instead.
+            if (contextualTypeHasPattern && !(node.parent.kind === SyntaxKind.SpreadAssignment && node.parent.parent.kind === SyntaxKind.ObjectLiteralExpression)) {
                 for (const prop of getPropertiesOfType(contextualType!)) {
-                    if (!propertiesTable.get(prop.escapedName) && !(spread && getPropertyOfType(spread, prop.escapedName))) {
+                    if (!propertiesTable.get(prop.escapedName) && !getPropertyOfType(spread, prop.escapedName)) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts]: Drive-by fix

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -22469,9 +22469,11 @@ namespace ts {
 
             // If object literal is contextually typed by the implied type of a binding pattern, augment the result
             // type with those properties for which the binding pattern specifies a default value.
-            if (contextualTypeHasPattern) {
+            // If the object literal is spread into another object literal, skip this step and let the top-level object
+            // literal handle it instead.
+            if (contextualTypeHasPattern && !(node.parent.kind === SyntaxKind.SpreadAssignment && node.parent.parent.kind === SyntaxKind.ObjectLiteralExpression)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: can you ever have a SpreadAssignment whose parent isn't an ObjectLiteralExpression?

Comment (andrewbranch) [reply src/compiler/checker.ts]: Doh, good call. You cannot (validated by the `parent` property type on `ts.SpreadAssignment`). Updated.
