### PR TITLE
fix(47670): "Organize imports" should remove import any alias that are aliased as the same name as the export

### LINKED ISSUE #47670: "Organize imports" should remove import any alias that are aliased as the same name as the export
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Darwin arm64 21.2.0

Steps to Reproduce:

1. Write the following code:
```ts
import {item as item} from 'mod';
```
2. Run 'Organize Imports' on the file
3. Notice that the import's alias is not removed despite being the same name (unnecessary, unorganized). Expected to see
```ts
import {item} from 'mod';
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47670

### CODE REVIEW

File: src/services/organizeImports.ts [hunk 1]
```diff
@@ -492,4 +491,14 @@ namespace ts.OrganizeImports {
                 return 6;
         }
     }
+
+    function getNewImportSpecifiers(namedImports: ImportDeclaration[]) {
+        return flatMap(namedImports, namedImport =>
+            map((namedImport.importClause?.namedBindings as NamedImports).elements, importSpecifier =>
```
Comment (DanielRosenwasser) [inline src/services/organizeImports.ts:497]: Should this still be `namedImport.importClause!.namedBindings`? The way it's currently been rewritten, if `importClause` is `undefined`, the access to `elements` will break at runtime, so it seems like `!` was fine.

**Review by DanielRosenwasser — APPROVED** [review]

**Review by DanielRosenwasser — COMMENTED** [review]
Sorry, accidentally hit approve instead of "comment"

File: src/services/organizeImports.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/organizeImports.ts:497]: `map` accepts [] | undefined

Comment (a-tarasyuk) [reply src/services/organizeImports.ts:497]: https://github.com/microsoft/TypeScript/blob/2172e1964f6e03a4912c11a7c133f3b95d86ccb4/src/compiler/core.ts#L308-L319

https://github.com/microsoft/TypeScript/blob/2172e1964f6e03a4912c11a7c133f3b95d86ccb4/src/compiler/core.ts#L380-L396

> ...if importClause is undefined

`map` returns `undefined`, and `flatMap` returns `empty array`

Comment (DanielRosenwasser) [reply src/services/organizeImports.ts:497]: What I mean is that in the following code

```
(namedImport.importClause?.namedBindings as NamedImports).elements
```

if the assertion is wrong, then this has the potential to crash before the call to `map`, because you'll end up running `undefined.elements`.

But it was already similarly the case for the old code:

```
(namedImport.importClause!.namedBindings as NamedImports).elements
```

where you'd end up running `undefined.namedBindings`.

So I guess I don't understand the need to switch to a `?.`.

Maybe it's unclear, but [a parenthesized type assertion *does* break the optional chain](https://www.typescriptlang.org/play?#code/DYUwLgBAHhC8EAoCGB+AdAIwkgztgdgJ4CUaAxkA).

Comment (a-tarasyuk) [reply src/services/organizeImports.ts]: I've moved this logic to `tryGetNamedBindingElements`. Is it ok?

File: tests/cases/fourslash/organizeImports8.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+/// <reference path="fourslash.ts" />
+
+////import { foo as foo } from "foo";
+////foo;
+
+verify.organizeImports(
+`import { foo } from "foo";
+foo;`
+);
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/organizeImports8.ts:9]: Maybe add another test that includes dropping imports, and consolidating multiple renames.

```ts
/// <reference path="fourslash.ts" />

////import { foo as foo, bar, baz, bizzle as bizzle, frizzle as frizzle } from "mod";
////foo(bar, frizzle);

verify.organizeImports(
`import { foo, bar, frizzle } from "mod";
foo(bar, frizzle);`
);
```

**Review by DanielRosenwasser — COMMENTED** [review]
Looks good! I think one more test case would be good to have.

File: tests/cases/fourslash/organizeImports8.ts (hunk 2 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/organizeImports8.ts:9]: I've added test
