### PR TITLE
Fix issue #22923

### LINKED ISSUE #22923: Check if element types of Promises contain a property when issuing a missing property error
```ts
function f(x: Promise<string>) {
  x.toLowerCase()
}
```
**Expected**: `Property 'toLowerCase' does not exist on type 'Promise<string>'. Did you forget to await the 'Promise<string>'?`

**Actual**: `Property 'toLowerCase' does not exist on type 'Promise<string>'.`

### PR DESCRIPTION
**Pull request by gagoman**
Fixes #22923

I'm still not sure that `isPromiseLike` should use `isReferenceToType` or something more smart (e.g. `getPromisedTypeOfPromise` to resolve actual types)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16409,6 +16409,9 @@ namespace ts {
             if (suggestion !== undefined) {
                 errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_does_not_exist_on_type_1_Did_you_mean_2, declarationNameToString(propNode), typeToString(containingType), suggestion);
             }
+            else if (isPromiseLike(containingType)) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: call `getPromisedTypeOfPromise` instead. this will return you the type of the `T` in `Promise<T>`. this should handle unions and custom promises, etc.. if it is `undefined` then it was not a promise.

you also need to check if the property exists on the promisedType. in other words:

```ts
var p: Pomise<number>;
p.toExponential;  // should report error `Property toExponential does not exist on type 'Promise<number>' did you forget `await`?`

var x: Promise<string>;
p.toExponential;  // should not report the `did you forget await` part.
```

**Comment by gagoman** [comment]
So, I've fixed a check plus have dropped tests for `Union` and `Intersection` and closed https://github.com/Microsoft/TypeScript/pull/23058

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -2000,7 +2000,10 @@
         "category": "Error",
         "code": 2569
     },
-
+    "Property '{0}' does not exist on type '{1}'. Did you forget to await the '{1}'?": {
```
Comment (mhegazy) [inline src/compiler/diagnosticMessages.json]: how about `Property '{0}' does not exist on type '{1}'. Did you forget 'await' ?`

Comment (mhegazy) [reply src/compiler/diagnosticMessages.json]: @DanielRosenwasser can i get your input on this error message as well.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -16406,9 +16406,13 @@ namespace ts {
                 }
             }
             const suggestion = getSuggestionForNonexistentProperty(propNode, containingType);
+            const promisedType = getPromisedTypeOfPromise(containingType);
             if (suggestion !== undefined) {
                 errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_does_not_exist_on_type_1_Did_you_mean_2, declarationNameToString(propNode), typeToString(containingType), suggestion);
             }
+            else if (promisedType && getPropertyOfType(promisedType, propNode.escapedText)) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: nit, consider moving `const promisedType = getPromisedTypeOfPromise(containingType);` inside an `else` block for `if (suggestion !== undefined)`. it just makes sure we only compute it if we need it.

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (DanielRosenwasser) [reply src/compiler/diagnosticMessages.json]: `Property '{0}' does not exist on type '{1}'. Did you forget to use 'await'?` is probably the best one actually.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -16410,7 +16410,13 @@ namespace ts {
                 errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_does_not_exist_on_type_1_Did_you_mean_2, declarationNameToString(propNode), typeToString(containingType), suggestion);
             }
             else {
-                errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_does_not_exist_on_type_1, declarationNameToString(propNode), typeToString(containingType));
+                const promisedType = getPromisedTypeOfPromise(containingType);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I would say that you should do the promise check before any sort of spelling checks because if a property exists on the awaited type, that's almost always a preferable suggestion.

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (gagoman) [reply src/compiler/diagnosticMessages.json]: I had this at https://github.com/Microsoft/TypeScript/pull/23058. So which message?

* Property '{0}' does not exist on type '{1}'. Did you forget to use 'await'?
* Property '{0}' does not exist on type '{1}', but does exist on type '{2}'. Did you forget to use 'await'?

**Comment by gagoman** [comment]
> try accessing a string property on string | Promise<string>

this is clear

> use an element access to access a property on the awaited type.

What do you mean by element access?

File: src/compiler/checker.ts (hunk 4 above)
Comment (gagoman) [reply src/compiler/checker.ts]: Will do

**Comment by mhegazy** [comment]
element access is `a[expression]`, property access is `a.name`

**Comment by gagoman** [comment]
Ok, I've updated a message and have added the case for `string | Promise<string>`. Latest results in:

```
!!! error TS2339: Property 'toLowerCase' does not exist on type 'string | Promise<string>'.
!!! error TS2339:   Property 'toLowerCase' does not exist on type 'Promise<string>'.
```

----

As for element access I can not see how is it related, e.g.

```
function f(x: Promise<string>) {
    return x["toString"]();
}
```

will not emit even an old error, as they are in different branches - `checkPropertyAccessExpression` and `checkIndexedAccess`.

Or do you mean something like this?

```
function f(x: Promise<string>, y: any) {
    return y[x.toString()];
}
```

**Comment by DanielRosenwasser** [comment]
I meant something like `x["toLowerCase"]()` which should use the same error handling branch if I'm not mistaken.

**Comment by mhegazy** [comment]
> I meant something like x["toLowerCase"]() which should use the same error handling branch if I'm not mistaken

there is no error here for using a property that does not exist. the only error is under `--noImplicitAny`. so do not think this is an issue.

**Comment by mhegazy** [comment]
thanks @gagoman!

**Comment by gagoman** [comment]
Yes, I've tested this case. It is not covered by this branch.
