### PR TITLE
Fix named export/import formatting

### LINKED ISSUE #4516: Support formatting for named imports/export clauses
```TypeScript
export{x,y as yy,z}from "foo"
```

Should be fixed to

```TypeScript
export { x, y as yy, z } from "foo"
```

Similarly, 

```TypeScript
import{x,y as yy,z}from "foo"
```

Should be fixed to

```TypeScript
import { x, y as yy, z } from "foo"
```

### LINKED ISSUE #6924: Format code unindents multi-line import statement
Take this code snippet:
```
import {Obj1, Obj2, Ob3, SomeVeryLongObjName, etc} as SomeVeryLong
    from 'some/file/with/a/very/very/very/very/long/path';
```
When the TS formatter is run on it, the second line is unindented and becomes this:

```
import {Obj1, Obj2, Ob3, SomeVeryLongObjName, etc} as SomeVeryLong
from 'some/file/with/a/very/very/very/very/long/path';
```

That seems incorrect behavior to me. I would have expected the formatter to ensure that multi-line imports are indented. 

Originally reported here: https://github.com/vvakame/typescript-formatter/issues/33

### PR DESCRIPTION
**Pull request by SaschaNaz**
Fixes #4516, fixes #6924.

- [x] Fix indentation inside export/import pseudo-block
- [x] Remove newline between export/import keyword and open brace token
- [x] Add tests (and replace current dummy one)
- [x] Wait #4757

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@SaschaNaz `tests/cases/fourslash/formatNamedExportImport.ts` seems to test templates, not imports (or exports).

**Comment by SaschaNaz** [comment]
@DanielRosenwasser I just fixed it, sorry! ;)

**Comment by mhegazy** [comment]
looks like we have  a marge conflict with the other formatting changes.

File: src/services/formatting/rules.ts [hunk 1]
```diff
@@ -213,25 +213,15 @@ namespace ts.formatting {
         public NoSpaceBetweenYieldKeywordAndStar: Rule;
         public SpaceBetweenYieldOrYieldStarAndOperand: Rule;
 
-        // Async-await
+        // Async functions
         public SpaceBetweenAsyncAndFunctionKeyword: Rule;
-        public NoSpaceBetweenAsyncAndFunctionKeyword: Rule;
-        public SpaceAfterAwaitKeyword: Rule;
-        public NoSpaceAfterAwaitKeyword: Rule;
```
Comment (DanielRosenwasser) [inline src/services/formatting/rules.ts]: I'm having trouble understanding why these were removed.

Comment (SaschaNaz) [inline src/services/formatting/rules.ts]: The SpaceAfterAwaitKeyword and SpaceAfterTypeKeyword rules are merged into SpaceAfterCertainKeywords and SpaceAfterCertainTypeScriptKeywords rules respectively.

Comment (DanielRosenwasser) [inline src/services/formatting/rules.ts]: What about the `NoSpaceAfterAwaitKeyword` one? Is that just encompassed by `SpaceAfterCertainKeywords`?

Comment (SaschaNaz) [inline src/services/formatting/rules.ts]: The other `NoSpace` ones should not exist. I once thought it will work together with `Space` rules but then found they should only exist when there are some valid formatting options.

Comment (SaschaNaz) [inline src/services/formatting/rules.ts]: I once thought `NoSpace` rules would first remove those whitespaces and after that `Space` rules would add one. However, a `Space` rule can remove excessive whitespaces by itself.

Comment (DanielRosenwasser) [inline src/services/formatting/rules.ts]: > I once thought `NoSpace` rules would first remove those whitespaces and after that `Space` rules would add one. However, a `Space` rule can remove excessive whitespaces by itself.

That's what I thought as well - it does make sense that one doesn't necessarily need the other.

**Comment by DanielRosenwasser** [comment]
Looks good to me - @vladima can you take a quick peek?

File: src/services/formatting/smartIndenter.ts [hunk 2]
```diff
@@ -464,9 +471,29 @@ namespace ts.formatting {
...
                 case SyntaxKind.SetAccessor:
                     return child !== SyntaxKind.Block;
+                case SyntaxKind.ExportDeclaration:
+                    return child !== SyntaxKind.NamedExports;
                 default:
                     return false;
             }
         }
+
+        function hasBraceShell(node: Node) {
```
Comment (vladima) [inline src/services/formatting/smartIndenter.ts]: Not sure why this is needed? Can we just do what is done for all other kinds of blocks, namely:
- add `SyntaxKind.NamedImports`, `SyntaxKind.NamedExports` to the list in `shouldIndentChildNode` function so its content will be indented
- update `isCompletedNode` function to correctly process case when cursor is in incompleted `NamesImport` / `NamedExport` node by using `hasChildOfKind(n, SyntaxKind.CloseBraceToken, sourceFile);`

Comment (SaschaNaz) [inline src/services/formatting/smartIndenter.ts]: `hasBraceShell` function is not to check completeness as `ImportClause` node can omit its optional braces. I think `isCompletedNode` function is to check a node has its required children.

Comment (SaschaNaz) [inline src/services/formatting/smartIndenter.ts]: @vladima I was wrong and the braces are not optional. I just removed `hasBraceShell` and added a simpler check.

File: src/services/formatting/smartIndenter.ts [hunk 3]
```diff
@@ -464,9 +471,22 @@ namespace ts.formatting {
...
                 default:
                     return false;
             }
         }
+
+        export function isIndentationPrevented(node: TextRangeWithKind) {
+            switch (node.kind) {
+                case SyntaxKind.NamedExports:
+                    return true;
+                // Allow indentation only when namedBindings is NamespaceImport.
```
Comment (DanielRosenwasser) [inline src/services/formatting/smartIndenter.ts]: Can you move this comment down? Also, is it correct?

File: src/services/formatting/smartIndenter.ts [hunk 4]
```diff
@@ -464,9 +471,22 @@ namespace ts.formatting {
...
                 case SyntaxKind.SetAccessor:
                     return child !== SyntaxKind.Block;
+                case SyntaxKind.ExportDeclaration:
+                    return child !== SyntaxKind.NamedExports;
                 default:
                     return false;
             }
         }
+
+        export function isIndentationPrevented(node: TextRangeWithKind) {
```
Comment (DanielRosenwasser) [inline src/services/formatting/smartIndenter.ts]: Can you add a JSDoc comment explaining what you mean by "prevented"?

File: src/services/formatting/smartIndenter.ts (hunk 2 above)
Comment (vladima) [inline src/services/formatting/smartIndenter.ts]: @SaschaNaz currently `nodeIsCompleted` handles cases when code is incomplete i.e.
```ts
import {$ // hit enter at $, caret on the next line should be indented
```.

I would expect imports and export to follow the same technique that we already use for all other blocks\block like constructions

File: src/services/formatting/smartIndenter.ts (hunk 3 above)
Comment (SaschaNaz) [inline src/services/formatting/smartIndenter.ts]: I later changed it to `// NamedImports has its own braces as Block does` `(so do not give it additional indentation)`

File: src/services/formatting/smartIndenter.ts (hunk 4 above)
Comment (SaschaNaz) [inline src/services/formatting/smartIndenter.ts]: I just tried adding one.

Comment (SaschaNaz) [inline src/services/formatting/smartIndenter.ts]: BTW, do you have any better name? `shouldInheritParentIndentation`? Hmm.

File: src/services/formatting/smartIndenter.ts [hunk 5]
```diff
@@ -464,9 +471,25 @@ namespace ts.formatting {
...
+        /**
+         * Function returns true if a node should not get additional indentation in its parent node.
+         */
+        export function isIndentationPrevented(node: TextRangeWithKind) {
+            switch (node.kind) {
+                case SyntaxKind.NamedExports:
+                    return true;
+                case SyntaxKind.ImportClause:
+                    // NamedImports has its own braces as Block does
+                    return (<ImportClause>node).namedBindings.kind === SyntaxKind.NamedImports;
```
Comment (SaschaNaz) [inline src/services/formatting/smartIndenter.ts]: @vladima Former `hasBraceShell` (and current `namedBindings` check) is needed to prevent unwanted excessive indentation. Consider this code:

```typescript
import
{
    x as xx
}
from "foo"
import
    * as Foo from "foo"
```

ImportDeclaration has ImportClause node and then ImportClause node can have two different kind of nodes: `NamedImports` and `NamespaceImport`.

`NamedImports`, as you noted, looks like a block, but `NamespaceImport` doesn't. If I decide to always indent `ImportClause` or always not to do it, formatting will look bad:

```typescript
import
    {
        x as xx
    } // when ImportClause is always indented
from "foo"

import
* as Foo from "foo" // when always not
```

Thus I added this check.

Anyway I agree that isCompletedNode should be updated. I'll push a change for it.

File: src/services/formatting/formatting.ts [hunk 6]
```diff
@@ -282,19 +282,19 @@ namespace ts.formatting {
      */
     function getOwnOrInheritedDelta(n: Node, options: FormatCodeOptions, sourceFile: SourceFile): number {
         let previousLine = Constants.Unknown;
-        let childKind = SyntaxKind.Unknown;
+        let child: Node = null;
```
Comment (vladima) [inline src/services/formatting/formatting.ts]: we don't use nulls - use `undefined` instead

File: src/services/formatting/formatting.ts [hunk 7]
```diff
@@ -386,34 +386,19 @@ namespace ts.formatting {
...
-                    }
-                    else {
-                        indentation = parentDynamicIndentation.getIndentation() + parentDynamicIndentation.getDelta();
-                    }
+                    indentation = parentDynamicIndentation.getIndentation() + parentDynamicIndentation.getDelta();
                 }
             }
 
-            var delta = SmartIndenter.shouldIndentChildNode(node.kind, SyntaxKind.Unknown) ? options.IndentSize : 0;
+            var delta = SmartIndenter.shouldIndentChildNode(node, null) ? options.IndentSize : 0;
```
Comment (vladima) [inline src/services/formatting/formatting.ts]: `null` => `undefined`

File: src/services/formatting/formatting.ts [hunk 8]
```diff
@@ -503,7 +489,7 @@ namespace ts.formatting {
                             indentation -= options.IndentSize;
                         }
 
-                        if (SmartIndenter.shouldIndentChildNode(node.kind, SyntaxKind.Unknown)) {
+                        if (SmartIndenter.shouldIndentChildNode(node, null)) {
```
Comment (vladima) [inline src/services/formatting/formatting.ts]: `null` => `undefined`

**Comment by vladima** [comment]
LGTM after comments are addresses

**Comment by SaschaNaz** [comment]
@vladima Can you also review #4757? `shouldInheritParentIndentation` part of this PR is in fact duplication of that one. I'll remove the duplication after #4757 is merged.

**Comment by mhegazy** [comment]
looks good. please address the comments about use of null.

**Comment by SaschaNaz** [comment]
I want to format export/imports and object destructuring with similar rules but I'm not sure what should I do in this case:

```typescript
export
{ // Export block currently can optionally have a newline before open brace as `if` block can
    x, y
} from "foo"

let
{ // Will anyone want this?
    x, y
} = foo;
```

**Comment by mhegazy** [comment]
:+1: 
@vladima can you take a look.

**Comment by mhegazy** [comment]
thanks @SaschaNaz. can you also add a condition for #9224 to allow users to opt in/out.
