### PR TITLE
Fix undefined error for diagnostic for instantiating an abstract class

### LINKED ISSUE #19782: Cannot read property 'end' of undefined at getFullWidth
**TypeScript Version:** Version 2.7.0-dev.20171104

**Code**

```ts
// index.ts
import Bar from "./bar";
const bar = new Bar();

// bar.ts
export default abstract class  { }
```

See: https://github.com/shaunluttin/reproduce-tsc-issue-19782

**Expected behavior:**

The compiler emits an error about instantiating an abstract class. 

**Actual behavior:**

```
PS C:\src> .\node_modules\.bin\tsc
C:\src\node_modules\typescript\lib\tsc.js:58287
                throw e;
                ^

TypeError: Cannot read property 'end' of undefined
    at getFullWidth (C:\src\node_modules\typescript\lib\tsc.js:5496:20)
    at Object.declarationNameToString (C:\src\node_modules\typescript\lib\tsc.js:5871:16)
    at resolveNewExpression (C:\src\node_modules\typescript\lib\tsc.js:32028:102)
    at resolveSignature (C:\src\node_modules\typescript\lib\tsc.js:32172:28)
    at getResolvedSignature (C:\src\node_modules\typescript\lib\tsc.js:32190:26)
    at checkCallExpression (C:\src\node_modules\typescript\lib\tsc.js:32233:29)
    at checkExpressionWorker (C:\src\node_modules\typescript\lib\tsc.js:33520:28)
    at checkExpression (C:\src\node_modules\typescript\lib\tsc.js:33463:42)
    at checkExpressionCached (C:\src\node_modules\typescript\lib\tsc.js:33375:38)
    at getTypeOfExpression (C:\src\node_modules\typescript\lib\tsc.js:33448:28)  
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19782

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16725,7 +16725,13 @@ namespace ts {
                 // only the class declaration node will have the Abstract flag set.
                 const valueDecl = expressionType.symbol && getClassLikeDeclarationOfSymbol(expressionType.symbol);
                 if (valueDecl && hasModifier(valueDecl, ModifierFlags.Abstract)) {
-                    error(node, Diagnostics.Cannot_create_an_instance_of_the_abstract_class_0, declarationNameToString(getNameOfDeclaration(valueDecl)));
+                    const name = getNameOfDeclaration(valueDecl);
+                    if (name) {
+                        error(node, Diagnostics.Cannot_create_an_instance_of_the_abstract_class_0, declarationNameToString(name));
```
Comment (rbuckton) [inline src/compiler/checker.ts]: Would it make sense to get the name from the import alias or local variable (for class expressions) if the class doesn't have a name?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16725,7 +16725,13 @@ namespace ts {
                 // only the class declaration node will have the Abstract flag set.
                 const valueDecl = expressionType.symbol && getClassLikeDeclarationOfSymbol(expressionType.symbol);
                 if (valueDecl && hasModifier(valueDecl, ModifierFlags.Abstract)) {
-                    error(node, Diagnostics.Cannot_create_an_instance_of_the_abstract_class_0, declarationNameToString(getNameOfDeclaration(valueDecl)));
+                    const name = getNameOfDeclaration(valueDecl);
+                    if (name) {
+                        error(node, Diagnostics.Cannot_create_an_instance_of_the_abstract_class_0, declarationNameToString(name));
+                    }
+                    else {
+                        error(node, Diagnostics.Cannot_create_an_instance_of_an_abstract_class);
```
Comment (rbuckton) [inline src/compiler/checker.ts]: Alternatively, we can just use this diagnostic and remove the named one.

Comment (andy-ms) [reply src/compiler/checker.ts]: That's probably better since it means having only one diagnostic and it's obvious from the error location what you're trying to construct. Also, it might not be an identifier so we can't reliably get a name from the use site either.
