### PR TITLE
Use `import().T` for import completions/fixes of pure types in JS files

### LINKED ISSUE #23407: Add `import(...)` for types in jsdoc completions instead of import
Similar to how we do auto import in completion list. we should not add imports in jsdoc completions, instead use the new `import(...).type` syntax.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #23407

Note: converted importFixes from passing around `symbolToken` to `position` because we may get an import completion at a location with no Identifier there yet.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -169,32 +181,36 @@ namespace ts.codefix {
...
         exportInfos: ReadonlyArray<SymbolExportInfo>,
         symbolName: string,
-        symbolToken: Node | undefined,
+        position: number | undefined,
         program: Program,
         sourceFile: SourceFile,
         host: LanguageServiceHost,
         preferences: UserPreferences,
     ): ReadonlyArray<ImportFix> {
         const checker = program.getTypeChecker();
```
Comment (sheetalkamat) [inline src/services/codefixes/importFixes.ts]: Why not exit early here when position is undefined ? without doing any of the work.

Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: We actually might return a result if we don't need to add a qualifier to the use. We would add an import at the top of the file and not need `position`.
