### PR TITLE
Remove undefined from the type of default  initialised parameters when narrowing

### LINKED ISSUE #14236: strictNullChecks and nullable parameters with defaults
**TypeScript Version:**  2.2.1

It seems that TS 2.2.1 changed the behavior of nullable parameters (NOTE: `null` specifically, not `undefined`) with defaults when compiling with `--strictNullChecks`.  Was this change intentional?  It's a breaking change.

I imagine this is a consequence of #12033, but AFAICT affecting `null` was likely an unintentional side effect.

**Code**

```ts
type OptionalString = string | null | undefined;

function hasDefault(val: OptionalString = "") {
  // TS 2.1.6, type of val is OptionalString
  // TS 2.2.1, type of val is string
}

// TS 2.1.6, next line compiled fine
// TS 2.2.1, error TS2345: Argument of type 'null' is not assignable to parameter of type 'string | undefined'.
hasDefault(null);
```

**Expected behavior:**
Type of val to be `OptionalString` (or `string | null`) and for `null` to be an accepted parameter.

**Actual behavior:**
Type of val is `string` and `null` is not accepted as an argument to the function.

### LINKED ISSUE #14425: Type 'undefined' is not assignable to type 'string' (reduced from a null-able function parameter)
**TypeScript Version:**  2.2.1

**Code**

```ts
function foo(bar: string | undefined = '') {
    bar = undefined;
//  ^ Type 'undefined' is not assignable to type 'string'.
}
```

Possibly related to #13826.

### LINKED ISSUE #14487: TypeScript 2.2.1 generates surprising null checking error
**TypeScript Version:**  2.2.1 

Effective type of argument `p` below seems to not match explicit declaration under tsc 2.2.1

**Code**

```ts
interface RuleContext  {
    _parent: RuleContext | undefined;
};

var  _ctx = { _parent: undefined};

function walk( p: RuleContext | undefined = _ctx ) {
    while (p) {
        p = p._parent; // Error w/ "strictNullChecks": true !
    }
}
```

**Expected behavior:**
Compiled w/o error under 2.1
**Actual behavior:**
Generates error:
```
index.ts(9,4): error TS2322: Type 'RuleContext | undefined' is not assignable to type 'RuleContext'.
  Type 'undefined' is not assignable to type 'RuleContext'.
```

### PR DESCRIPTION
**Pull request by sandersn**
When narrowing, remove optionality from the initial type of parameters with initialisers. Note that the type of the initialiser is not used; its presence just means that the initial type of the parameter
can't contain undefined. It could contain any other member of a declared union type.

This fix builds on the previous fix #12033, but is slightly more complex in that it changes the initial type before control flow analysis rather than just throwing undefined away from the declared type.

The code refactors most of the complexity into `checkIdentifier`, out of `getFlowTypeOfReference`, since it's only needed there. Suggestions on simplifying the mess of conditionals are welcome!

Fixes #14487 
Fixes #14425 
Fixes #14236

### CODE REVIEW

**Comment by sandersn** [comment]
@ahejlsberg can you take a look?

**Comment by Kovensky** [comment]
That is, it's only removed specifically when narrowing?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -10934,6 +10922,16 @@ namespace ts {
...
         }
 
+        /** remove undefined from the annotated type of a parameter when there is an initializer (that doesn't include undefined) */
+        function removeOptionalityFromDeclaredType(declaredType: Type, declaration: VariableLikeDeclaration): Type {
+            const annotationIncludesUndefined = strictNullChecks &&
+                declaration.kind === SyntaxKind.Parameter &&
+                declaration.initializer &&
+                getFalsyFlags(declaredType) & TypeFlags.Undefined &&
+                !(getFalsyFlags(checkExpression(declaration.initializer)) & TypeFlags.Undefined);
+            return annotationIncludesUndefined ? getNonNullableType(declaredType) : declaredType;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This line is the source if the issue with `null` I mentioned. It removes both `undefined` and `null`. You need to use `getTypeWithFacts(declaredType, TypeFacts.NEUndefined)` instead.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11052,7 +11050,10 @@ namespace ts {
             const assumeInitialized = isParameter || isOuterVariable ||
                 type !== autoType && type !== autoArrayType && (!strictNullChecks || (type.flags & TypeFlags.Any) !== 0 || isInTypeQuery(node)) ||
                 isInAmbientContext(declaration);
-            const flowType = getFlowTypeOfReference(node, type, assumeInitialized, flowContainer);
+            const initialType = assumeInitialized ? (isParameter ? removeOptionalityFromDeclaredType(type, getRootDeclaration(declaration) as VariableLikeDeclaration) : type) :
+                type === autoType || type === autoArrayType ? undefinedType :
+                includeFalsyTypes(type, TypeFlags.Undefined);
+            const flowType = isFlowNarrowable(node, type, !assumeInitialized) ? getFlowTypeOfReference(node, type, initialType, flowContainer) : type;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I would keep the `isFlowNarrowable` logic inside `getFlowTypeOfReference`, even if it means adding another parameter. Otherwise, you have to always write this combined pattern which is even more complicated.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This is the cause of #14236.

Comment (sandersn) [inline src/compiler/checker.ts]: Done

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -10248,14 +10238,15 @@ namespace ts {
...
 
-        function getFlowTypeOfReference(reference: Node, declaredType: Type, assumeInitialized: boolean, flowContainer: Node) {
+        function isFlowNarrowable(reference: Node, type: Type, couldBeUninitialized?: boolean) {
+            return reference.flowNode && (type.flags & TypeFlags.Narrowable || couldBeUninitialized);
+        }
+
+        function getFlowTypeOfReference(reference: Node, declaredType: Type, initialType = declaredType, flowContainer?: Node, couldBeUninitialized?: boolean) {
             let key: string;
-            if (!reference.flowNode || assumeInitialized && !(declaredType.flags & TypeFlags.Narrowable)) {
+            if (!isFlowNarrowable(reference, declaredType, couldBeUninitialized)) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Just inline the function here. It's not called anywhere else best I can tell.

Comment (sandersn) [inline src/compiler/checker.ts]: Done
