### PR TITLE
Fix assertion -- an import may come from a require() call

### LINKED ISSUE #19629: Auto imports does not work for extensions
_From @bpasero on October 31, 2017 13:37_

Testing: https://github.com/Microsoft/vscode/issues/37177

1. create a hello world JS extension
2. open extension.js
3. start to type `RelativePattern`
4. complete it

=> no import is added

Imho if there is no import action after accepting a proposal, we should also not show it in the IntelliSense window. 

_Copied from original issue: Microsoft/vscode#37282_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19629

### CODE REVIEW

File: tests/cases/fourslash/completionsImport_require.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
+/// <reference path="fourslash.ts" />
+
+// @allowJs: true
+
+// @Filename: /a.ts
+////export const foo = 0;
+
+// @Filename: /b.js
+////const a = require("./a");
```
Comment (mhegazy) [inline tests/cases/fourslash/completionsImport_require.ts]: also add a test for `import("./a");`

**Comment by mhegazy** [comment]
Please port this to release-2.6
