### PR TITLE
Remove trailing whitespace from JSDoc comments

### LINKED ISSUE #25916: Doc comment has trailing space
**TypeScript Version:**  master

**Code**

```ts
/// <reference path='fourslash.ts'/>

// @Filename: quickInfoJsDocTags.ts
/////** Doc */
////const /**/x = 0;

verify.quickInfoAt("", "const x: 0", "Doc");
```

**Expected behavior:**

Test passes.

**Actual behavior:**

Test fails. Doc comment is actually `"Doc "`.

### PR DESCRIPTION
**Pull request by tschaub**
This removes trailing whitespace from JSDoc comments.  I'll add additional tests after confirming that this is going in a direction you agree with.

Fixes #25916

### CODE REVIEW

**Comment by tschaub** [comment]
I was initially only running `npx jake runtests tests=JsDoc`.  I see that this is causing other failures when running the complete test suite.  I'll dig around more later.

File: tests/cases/fourslash/quickInfoJsDocTags1.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+/// <reference path='fourslash.ts'/>
```
Comment (andy-ms) [inline tests/cases/fourslash/quickInfoJsDocTags1.ts]: The new test is probably not necessary given the number of other tests updated here.

File: tests/cases/fourslash/completionsInJsxTag.ts [hunk 2]
```diff
@@ -11,17 +11,17 @@
...
-////    render() {
-////        <div /*1*/ ></div>;
-////        <div  /*2*/ />
-////    }
+////}
+////class Foo {
+////    render() {
+////        <div /*1*/ ></div>;
+////        <div  /*2*/ />
+////    }
```
Comment (tschaub) [inline tests/cases/fourslash/completionsInJsxTag.ts]: I think this change was due to mixed line endings in the file.  I can remove this part of the change if needed.

**Comment by tschaub** [comment]
I've updated the remaining tests to reflect the new behavior.  Let me know if you think the addition of the `quickInfoJsDocTags1.ts` test is unnecessary or if you'd like to see additional syntax covered.
