### PR TITLE
noUnusedLocals: Destructuring assignment is a write

### LINKED ISSUE #26345: Variable assignment with destructuring incorrectly marks locals as read
**TypeScript Version:**  3.1.0-dev.20180809

**Search Terms:**
noUnusedLocals
destructuring assignment
declared but its value is never read

**Code**

```ts
// Compile with --noUnusedLocals

{
    const abc = 1 // 'abc' is declared but its value is never read.
    let def: number // 'def' is declared but its value is never read.
    def = 2
}
{
    const {abc} = {abc: 1} // 'abc' is declared but its value is never read.
    let def: number // no compiler error
    ({def} = {def: 2})
}
{
    const [abc] = [1] // 'abc' is declared but its value is never read.
    let def: number // no compiler error
    [def] = [2]
}
```

**Expected behavior:**
All 6 variable declarations should cause a compiler error because they are declared but never read. It should not matter whether the variable is assigned to where it is declared, or afterwards.

**Actual behavior:**
Destructuring assignments to variables after they are declared marks them as read, even though they are only written to. Direct assignments work as expected.

**Playground Link:**
N/A; playground doesn't support `noUnusedLocals`

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #26345

### CODE REVIEW

File: tests/baselines/reference/noUnusedLocals_writeOnly.js [hunk 1]
```diff
@@ -3,11 +3,15 @@ function f(x = 0) {
     x = 1;
     x++;
     x /= 2;
+    ([x] = [1]);
+    ({ x } = { x: 1 });
+    ({ x: x } = { x: 1 });
```
Comment (sheetalkamat) [inline tests/baselines/reference/noUnusedLocals_writeOnly.js]: I think you need tests for more levels in destructuring (nested object literal)

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -4205,13 +4214,35 @@ namespace ts {
...
             case SyntaxKind.PropertyAccessExpression:
                 return (parent as PropertyAccessExpression).name !== node ? AccessKind.Read : accessKind(parent);
+            case SyntaxKind.PropertyAssignment: {
+                const parentAccess = accessKind(parent.parent);
+                // In `({ x: varname }) = { x: 1 }`, the left `x` is a read, the right `x` is a write.
+                return node === (parent as PropertyAssignment).name ? reverseAccessKind(parentAccess) : parentAccess;
+            }
+            case SyntaxKind.ShorthandPropertyAssignment:
+                // Assume it's the local variable being accessed, since we don't check public properties for --noUnusedLocals.
+                return accessKind(parent.parent);
```
Comment (ajafff) [inline src/compiler/utilities.ts]: this needs to handle `objectAssignmentInitializer` as that is always read.
consider adding a test case for that, too.

**Comment by andy-ms** [comment]
@sheetalkamat Please re-review

File: tests/baselines/reference/noUnusedLocals_writeOnly.js (hunk 1 above)
Comment (sheetalkamat) [reply tests/baselines/reference/noUnusedLocals_writeOnly.js]: shouldnt each test be moved to their own function to guarantee used is getting marked correctly for each expression type usage of x?

Comment (andy-ms) [reply tests/baselines/reference/noUnusedLocals_writeOnly.js]: Every one of these tests only writes to `x`, so we're testing that *none* of these marks `x` as used. If a single test failed the baseline would change since `x` was used.
