### PR TITLE
Deprioritize import paths made up of only dots and slashes

### LINKED ISSUE #45953: Auto-import prefers parent index.ts which leads to circular reference
# Bug Report

This appears to be recently changed behaviour. I have a package with an index.ts at the root:

1. I write a file `a/Foo.ts` which contains `export const Foo = 'Foo'`
2. I write a root `index.ts` which contains `export * from './a/Foo'`
3. I write a file `b/Bar.ts` and attempt to auto-import `Foo`
4. The import is written as `import { Foo } from '..'`.

I think that importing from an index directly above the file like this is highly likely to lead to a circular reference.

### 🔎 Search Terms

`auto-import` `auto-import relative`

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.2

### ⏯ Playground Link

See simple repro.

### 💻 Code

```ts
// index.ts
export * from './a/Foo';
```

```ts
// a/Foo.ts
export const Foo = 'Foo';
```

```ts
// b/Bar.ts
import { Foo } from '..'; // this is the resulting import

const Bar = Foo; // try to auto-import this
```

### 🙁 Actual behavior

Imports from parent index.ts. This file is highly likely to also import the importing file, causing a circular reference.

### 🙂 Expected behavior

Import from `'./a/Foo'` instead. Or, put another way, prefer not to import from a path which has only one or more `..` in it.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #45953 

Paths like `"."` and `".."` are still available in the codefix dropdown, but sorted to the end of the list. Completions takes only the first module specifier from the list, so they should be gone from completions entirely.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -678,11 +678,16 @@ namespace ts.codefix {
...
             return compareBooleans(allowsImportingSpecifier(b.moduleSpecifier), allowsImportingSpecifier(a.moduleSpecifier))
                 || compareNodeCoreModuleSpecifiers(a.moduleSpecifier, b.moduleSpecifier, importingFile, program)
+                || compareBooleans(isOnlyDotsAndSlashes(a.moduleSpecifier), isOnlyDotsAndSlashes(b.moduleSpecifier))
                 || compareNumberOfDirectorySeparators(a.moduleSpecifier, b.moduleSpecifier);
         }
         return Comparison.EqualTo;
     }
 
+    function isOnlyDotsAndSlashes(path: string) {
+        return !/[^.\/]/g.test(path);
```
Comment (RyanCavanaugh) [inline src/services/codefixes/importFixes.ts:688]: `/^[.\/]+$/g.test` would short-circuit faster, I think?

**Review by RyanCavanaugh — APPROVED** [review]

**Review by gabritto — APPROVED** [review]

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/services/codefixes/importFixes.ts:688]: Just avoid the regex

```suggestion
        for (let i = 0; i < path.length; i++) {
            const ch = path.charCodeAt(i);
            if (i !== CharacterCodes.dot && i !== CharacterCodes.slash) return false;
        }
        return true;
```

Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:688]: Set up a test on https://jsbench.me (can't share without giving them my email) and that's 25% slower.

Comment (DanielRosenwasser) [reply src/services/codefixes/importFixes.ts:688]: Fair.

Comment (DanielRosenwasser) [reply src/services/codefixes/importFixes.ts:688]: If you do care about perf though, consider hoisting the regex out though.

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:688]: I tested that too, and it was only 5% faster 😉 I’ll probably do it anyway.

Comment (DanielRosenwasser) [reply src/services/codefixes/importFixes.ts:688]: SanicTheHedgehobGIF
