### PR TITLE
Check for type parameters on original type when getting type argument completions

### LINKED ISSUE #32874: TypeError: Cannot read property '0' of undefined in 'getTypeArgumentConstraint' during 'completionInfo'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.5.3
**VSCode version**: 1.36.1
**Command requested**: completionInfo
**Hitting sessions**: 141
**Five line hash**: 2102806d5656b80c3ba01afefeac947e
**Stack**:
```
    at getTypeArgumentConstraint (tsserver.js:54599:73)
    at getTypeArgumentConstraint (tsserver.js:31614:32)
    at getStringLiteralCompletionEntries (tsserver.js:98912:104)
    at getStringLiteralCompletions (tsserver.js:98830:59)
    at getCompletionsAtPosition (tsserver.js:99530:67)
    at getCompletionsAtPosition (tsserver.js:122111:35)
    at Session.getCompletions (tsserver.js:131153:64)
    at _a.<computed> (tsserver.js:130103:61)
    at <anonymous> (tsserver.js:131671:88)
    at Session.executeWithRequestId (tsserver.js:131662:28)
    at Session.executeCommand (tsserver.js:131671:33)
    at Session.onMessage (tsserver.js:131693:35)
    at <anonymous> (tsserver.js:132984:27)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #32874

### CODE REVIEW

File: tests/cases/fourslash/stringLiteralTypeCompletionsInTypeArgForNonGeneric1.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+////interface Foo {}
+////type Bar = {};
+////
+////let x: Foo<"/*1*/">;
+////let y: Bar<"/*2*/">;
+
+verify.completions({ marker: test.markers() });
+
+
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/stringLiteralTypeCompletionsInTypeArgForNonGeneric1.ts:11]:
```suggestion
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.5
