### PR TITLE
Don't crash if there's no JSX.Element during SFC resolution

### LINKED ISSUE #7286: Undefined JSX.Element crashes typechecker with function in element
**TypeScript Version:** 

1.8.2

**Code**

tsconfig.json:
```
{
    "compilerOptions": {
        "jsx": "react"
    },
    "files": [
        "app.tsx"
    ]
}
```

app.tsx:
```tsx
function Test() { }
<Test></Test>
```

**Expected behavior:**

Successful compilation, because undefined JSX.Element should be treated as any type.

**Actual behavior:** 

Throws exception:
typescript/lib/tsc.js:32989
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at isRelatedTo (typescript\lib\tsc.js:15954:32)
    at checkTypeRelatedTo (typescript\lib\tsc.js:15882:26)
    at checkTypeAssignableTo (typescript\lib\tsc.js:15760:20)
    at isTypeAssignableTo (typescript\lib\tsc.js:15754:20)
    at getJsxElementAttributesType (typescript\lib\tsc.js:18394:47)
    at checkJsxOpeningLikeElement (typescript\lib\tsc.js:18495:40)
    at checkJsxElement (typescript\lib\tsc.js:18200:13)
    at checkExpressionWorker (typescript\lib\tsc.js:20367:28)
    at checkExpression (typescript\lib\tsc.js:20279:42)
    at checkExpressionStatement (typescript\lib\tsc.js:21539:13)

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #7286

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8797,18 +8797,20 @@ namespace ts {
...
-                        const callSignatures = elemType && getSignaturesOfType(elemType, SignatureKind.Call);
-                        const callSignature = callSignatures && callSignatures.length > 0 && callSignatures[0];
-                        const callReturnType = callSignature && getReturnTypeOfSignature(callSignature);
-                        let paramType = callReturnType && (callSignature.parameters.length === 0 ? emptyObjectType : getTypeOfSymbol(callSignature.parameters[0]));
-                        if (callReturnType && isTypeAssignableTo(callReturnType, jsxElementType)) {
-                            // Intersect in JSX.IntrinsicAttributes if it exists
-                            const intrinsicAttributes = getJsxType(JsxNames.IntrinsicAttributes);
-                            if (intrinsicAttributes !== unknownType) {
-                                paramType = intersectTypes(intrinsicAttributes, paramType);
+                        if (jsxElementType) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Use an explicit return and invert this condition to reduce nesting.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Actually there might be an explicit return below but I can't easily see it on mobile.

File: tests/cases/conformance/types/contextualTypes/jsxAttributes/contextuallyTypedStringLiteralsInJsxAttributes01.tsx [hunk 2]
```diff
@@ -2,9 +2,12 @@
 // @declaration: true
 
 namespace JSX {
-    interface IntrinsicElements {
+    export interface IntrinsicElements {
```
Comment (sandersn) [inline tests/cases/conformance/types/contextualTypes/jsxAttributes/contextuallyTypedStringLiteralsInJsxAttributes01.tsx]: Why does this change to `export` and why add `export interface Element`? Does this somehow make them undefined for this test?

**Comment by mhegazy** [comment]
:+1:

File: tests/cases/conformance/types/contextualTypes/jsxAttributes/contextuallyTypedStringLiteralsInJsxAttributes01.tsx (hunk 2 above)
Comment (RyanCavanaugh) [inline tests/cases/conformance/types/contextualTypes/jsxAttributes/contextuallyTypedStringLiteralsInJsxAttributes01.tsx]: The test was invalid because `IntrinsicElements` wasn't actually exposed to the code below
