### PR TITLE
Fix js missing type arguments on existing nodes and jsdoc object literal declaration emit

### LINKED ISSUE #38356: Regression: DTS emit
Works in TS `3.9.0 beta` but not in `nightly (4.0.0-dev.20200505)`

Code:
```js
class X {
    /**
      * Cancels the request, sending a cancellation to the other party
      * @param {Object} error __auto_generated__
      * @param {string?} error.reason the error reason to send the cancellation with
      * @param {string?} error.code the error code to send the cancellation with
      * @returns {Promise.<*>} resolves when the event has been sent.
      */ 
    async cancel({reason = "User declined", code = "m.user"} = {}) {}
}
```

Playground:

https://www.typescriptlang.org/v2/en/play?ts=4.0.0-dev.20200505&useJavaScript=true#code/MYGwhgzhAEAa0G8CwAoa7oHoBU3UY22gGEwA7YAUxBgBcALS6AJ0oEcBXSiWgGmgiUyAEwCWZAObQw0YOSohwtUQHsy0Wio2NoKhpWbQADmGa0AnvgLQiAARPMwAW0QB5AEYArSsFoBfaANmFUMAfVCwDk1QiSEDMFpKYXCrAjsHZ0QeZnEJAH4AoJCAOlZINW0mIsMyiArNASFhStl5aiVVdQB3UQZUwmh7U0yEbNyCwOZg5mLgFWEmfUnp2XnFrUERFrkKdoTO6B6+tGs7VloOZjIYBAAFYKdRQWKAHmwAPgDWOpAAN25Dox1EtKP8yLRoPRINB3JQhI1wcV+uhsJhoP1IOYKK1diAABQIWoVAC80AARABVQSGBagcRJMn8OYLaCkslOYocalkgKkhB+ACUiD8qFQfiAA

Old output:
```ts
declare class X {
    /**
      * Cancels the request, sending a cancellation to the other party
      * @param {Object} error __auto_generated__
      * @param {string?} error.reason the error reason to send the cancellation with
      * @param {string?} error.code the error code to send the cancellation with
      * @returns {Promise.<*>} resolves when the event has been sent.
      */
    cancel({ reason, code }?: {
        reason: string;
        code: string;
    }): Promise<any>;
}
```

New output (invalid): 
```ts
declare class X {
    /**
      * Cancels the request, sending a cancellation to the other party
      * @param {Object} error __auto_generated__
      * @param {string?} error.reason the error reason to send the cancellation with
      * @param {string?} error.code the error code to send the cancellation with
      * @returns {Promise.<*>} resolves when the event has been sent.
      */
    cancel({ reason, code }?: 
     * @param {?string} error.reason the error reason to send the cancellation with
     * @param {?string} error.code the error code to send the cancellation with
    ): Promise<any>;
}
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #38356

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Not sure if we baseline outputs for .d.ts files but

@typescript-bot test this
@typescript-bot user test this

**Comment by weswigham** [comment]
> Not sure if we baseline outputs for .d.ts files

We do not. Extended test suites are entirely useless for observing changes in jsdoc declaration emit~

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this to release-3.9

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5503,6 +5503,10 @@ namespace ts {
                 return symbol.declarations && find(symbol.declarations, s => !!getEffectiveTypeAnnotationNode(s) && (!enclosingDeclaration || !!findAncestor(s, n => n === enclosingDeclaration)));
             }
 
+            function getExistingNodeHasNoTypeParametersOrMatchingTypeParameters(existing: TypeNode, type: Type) {
+                return !(getObjectFlags(type) & ObjectFlags.Reference) || !isTypeReferenceNode(existing) || length(existing.typeArguments) >= getMinTypeArgumentCount((type as TypeReference).target.typeParameters);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:5507]: This is kinda surprising to me - this checks whether the existing type has *more* type arguments which I'd assume to be the opposite condition.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5503,6 +5503,10 @@ namespace ts {
                 return symbol.declarations && find(symbol.declarations, s => !!getEffectiveTypeAnnotationNode(s) && (!enclosingDeclaration || !!findAncestor(s, n => n === enclosingDeclaration)));
             }
 
+            function getExistingNodeHasNoTypeParametersOrMatchingTypeParameters(existing: TypeNode, type: Type) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:5506]: Should this start with the word `get`?

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:5507]: Yeah, if the existing declaration provides the minimum required or more, it's good to reuse; how's that surprising?

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:5506]: By convention, yes - pretty much all of our functions start with verbs, `get`, `create`, `serialize`, and so on.

**Comment by Jack-Works** [comment]
Hi! @weswigham There're also some invalid JSDoc basic type generation, can you also check this out?

```js
/** @type {Boolean} */const bool = true;
/** @type {bool} */const bool2 = true;

/** @type {Object} */const obj = true;

/** @type {String} */const str = true;

/** @type {Function} */const f = true;
/** @type {function} */const f2 = true;

/** @type {class} */const clz = true;

/** @type {int} */const x3 = true;
/** @type {float} */const x4 = true;
/** @type {Number} */const x5 = true;
/** @type {integer} */const x6 = true;
```

Code

```ts
/** @type {Boolean} */ declare const bool: Boolean; // expect boolean
/** @type {bool} */ declare const bool2: bool; // expect boolean

/** @type {Object} */ declare const obj: Object; // expect object

/** @type {String} */ declare const str: String; // expect string

/** @type {Function} */ declare const f: Function; // expect (...args:  any[]) => any
/** @type {function} */ declare const f2: function; // ! Invalid output ! expect (...args:  any[]) => any

/** @type {class} */ declare const clz: any; // expect { new (...args: any[]): any }

/** @type {int} */ declare const x3: any; // expect number
/** @type {float} */ declare const x4: any; // expect number
/** @type {Number} */ declare const x5: Number; // expect number
/** @type {integer} */ declare const x6: any; // expect number
```

I found this when I generate types for a real world JSDoc project, it's nice if TypeScript can handle this.

(My code generation project)
image

File: src/compiler/checker.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:5506]: What about predicate functions like `typeHasCallOrConstructSignatures`? Doesn't seem appropriate.

**Comment by weswigham** [comment]
I... Don't think we recognize `int` or `float`. But the others... Yeah, ok.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:5506]: but emacs doesn't show completions until I've typed 3 characters!

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:5507]: Maybe it's a naming issue? What is the meaning of `hasNoTypeParameters` in this case?

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:5506]: I renamed it to `existingTypeNodeIsNotReferenceOrIsReferenceWithCompatibleTypeArgumentCount` which _surely_ isn't a mouthful. I hope the removal of the verb is to your liking?

**Comment by weswigham** [comment]
@Jack-Works I've added an explicit testcase for our declaration emit for all the special lookups (as enumerated in our codebase), and included extra entries for the types you mention which we don't currently recognize, including `class`, `bool`, `int`, `integer`, `float`, and `event` (all of which are lookup failures, except `event` which is coincidentally the name of a global we return the type of, `Event | undefined`).

File: tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+/** @type {Number} */ declare const b: number;
+/** @type {Boolean} */ declare const c: boolean;
+/** @type {Void} */ declare const d: void;
+/** @type {Undefined} */ declare const e: undefined;
+/** @type {Null} */ declare const f: null;
+/** @type {Function} */ declare const g: Function;
+/** @type {function} */ declare const h: Function;
+/** @type {array} */ declare const i: any[];
+/** @type {promise} */ declare const j: Promise<any>;
+/** @type {Object<string, string>} */ declare const k: {
```
Comment (Jack-Works) [inline tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js:74]: What about `Object` => `object`?

File: tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types [hunk 4]
```diff
@@ -40,14 +40,14 @@ lf.Transaction = function() {};
  * @return {!IThenable}
  */
 lf.Transaction.prototype.begin = function(scope) {};
->lf.Transaction.prototype.begin = function(scope) {} : (scope: Array<lf.schema.Table>) => any
+>lf.Transaction.prototype.begin = function(scope) {} : (scope: Array<any>) => any
```
Comment (Jack-Works) [inline tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types:43]: Is it a regression?

File: tests/baselines/reference/jsdocTypeReferenceToValue.types [hunk 5]
```diff
@@ -1,7 +1,7 @@
 === tests/cases/conformance/jsdoc/foo.js ===
 /** @param {Image} image */
 function process(image) {
->process : (image: Image) => HTMLImageElement
+>process : (image: new (width?: number, height?: number) => HTMLImageElement) => HTMLImageElement
```
Comment (Jack-Works) [inline tests/baselines/reference/jsdocTypeReferenceToValue.types:4]: 👀

File: tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js (hunk 3 above)
Comment (weswigham) [reply tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js:74]: That's actually not a thing we interpret - `Object` with type arguments is interpreted as an index signature, without isn't recognized special (so it looks up the global `Object` constructor type, which is the apparent type of... pretty much everything except `null` and `undefined`) _except_ when `noImplicitAny` is false, where it is `any`.

`getIntendedTypeFromJSDocTypeReference` in the checker has the special jsdoc types that we lookup in it.

File: tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types (hunk 4 above)
Comment (weswigham) [reply tests/baselines/reference/prototypePropertyAssignmentMergeWithInterfaceMethod.types:43]: `lf.schema.Table` doesn't actually exist in the test, so we were preserving a node that failed to resolve anyway. Technically we could keep it (since it's an error anyway), but since i changed the default for jsdoc type which fail to resolve in not-jsdoc to serialize the resolved type, it now prints back as the `any` the failed resolution returns.

File: tests/baselines/reference/jsdocTypeReferenceToValue.types (hunk 5 above)
Comment (weswigham) [reply tests/baselines/reference/jsdocTypeReferenceToValue.types:4]: Yeah, `Image` is a constructor with no associated `interface`, and jsdoc lookup is strange. So, in TS, `(image: Image) => HTMLImageElement` will issue a `Image is not a type` error (because it's not). So we gotta serialize the type the jsdoc resolver resolved to instead of keeping the input node.

File: tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js (hunk 3 above)
Comment (Jack-Works) [reply tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js:74]: Hmm, but the handbook says

> Don’t ever use the types Number, String, Boolean, Symbol, or Object These types refer to non-primitive boxed objects that are almost never used appropriately in JavaScript code.

> Instead of Object, use the non-primitive object type (added in TypeScript 2.2).

File: src/compiler/checker.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:5506]: named perfectly!

File: tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js (hunk 3 above)
Comment (DanielRosenwasser) [reply tests/baselines/reference/jsDeclarationsJSDocRedirectedLookups.js:74]: The point is to test out stuff people write in JSDoc, because people write terrible stuff in JSDoc because it was terribly specified.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.9
