### PR TITLE
fix(54266): Navtree doesn't return computed class members

### LINKED ISSUE #54266: Navtree doesn't return computed class members
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1

**Search Terms**
- `navtree`
- outline

---

* have the TS file below
* open outline, breadcrumbs, or quick outline
* :bug: the members `[State.WAIT_FOR_INPUT]` and `[State.INIT_UI]` are missing

```ts



const enum State {
	INIT_UI = 'INIT_UI',
	WAIT_FOR_INPUT = 'WAIT_FOR_INPUT',
}

class AAAAA {

    [State.INIT_UI]() {
        return 23;
    }

    [State.WAIT_FOR_INPUT](){
        return 43;
    }

    bbbbb() {
        return 333;
    }
}

```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #54266

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

File: src/services/navigationBar.ts [hunk 1]
```diff
@@ -306,19 +309,16 @@ function addNodeWithRecursiveInitializer(node: VariableDeclaration | PropertyAss
...
-            isIdentifier(node.name.expression.expression) &&
-            idText(node.name.expression.expression) === "Symbol"
-        );
+    const name = getNameOfDeclaration(node);
+    if (name === undefined) return false;
+
+    if (isComputedPropertyName(name)) {
+        const expression = name.expression;
+        return (isPropertyAccessExpression(expression) && isIdentifier(expression.expression) && idText(expression.expression) === "Symbol")
+            || isEntityNameExpression(expression) || isNumericLiteral(expression) || isStringOrNumericLiteralLike(expression);
```
Comment (rbuckton) [inline src/services/navigationBar.ts:319]:
```suggestion
        return isEntityNameExpression(expression) || isNumericLiteral(expression) || isStringOrNumericLiteralLike(expression);
```

We no longer need to special case `Symbol.` if we allow any entityname-like expression in the next condition.

**Review by rbuckton — CHANGES_REQUESTED** [review]

**Review by rbuckton — APPROVED** [review]
Looks good, thanks!

**Review by jakebailey — APPROVED** [review]

**Review by DanielRosenwasser — APPROVED** [review]
