### PR TITLE
Fixes non-null assertion applied to type narrowed to never not issuing an error.

### LINKED ISSUE #35431: `!` type assertion on `never` changes the type
**TypeScript Version:**  3.8.0-dev.20191128

**Search Terms:** ! type assertion, never, wrong type 

**Code**

```ts
type A = { kind: "abc" } | { kind: "def" };

function f(a: A) {
  switch (a.kind) {
    case "abc":
      return 1;
    case "def":
      return 2;
    default:
      throw new Error("Bad kind: " + a!?.kind);
      // Hover over `a`:             ^
  }
}
```

**Expected behavior:**

Hovering gives the type `never`.

**Actual behavior:**

Hovering gives the type `A`.

**Playground Link:** The TS playground doesn't work for me

**Related Issues:**  https://github.com/typescript-eslint/typescript-eslint/issues/1282

-----

**More context:** This is a problem for TypeScript ESLint's "no-unnecessary-type-assertion" rule, which relies on the `!` operator not changing the type of the underlying expression.
(@bradzacher, please correct me if I'm misrepresenting anything.)

In the following example, hovering the `a`s always gives the same type:

```ts
declare const a: { kind: string } | undefined;

console.log(a!?.kind);
console.log(a?.kind);
```

### PR DESCRIPTION
**Pull request by dragomirtitian**
Fixed issue where non null assertion caused `getFlowTypeOfReference` to return the declared type if the type was already narrowed to never.

This was caused by the fact that `getTypeWithFacts(resultType, TypeFacts.NEUndefinedOrNull)` will return never both if `resultType` was already `never` and if `resultType` does not contain `undefined` or `null`. In the latter case returning the declaring type is correct, in the former case this causes something narrowed to `never` to still be typed as the original declared type.

Fixes #35431

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22185,7 +22185,7 @@ namespace ts {
             // on empty arrays are possible without implicit any errors and new element types can be inferred without
             // type mismatch errors.
             const resultType = getObjectFlags(evolvedType) & ObjectFlags.EvolvingArray && isEvolvingArrayOperationTarget(reference) ? autoArrayType : finalizeEvolvingArrayType(evolvedType);
-            if (resultType === unreachableNeverType || reference.parent && reference.parent.kind === SyntaxKind.NonNullExpression && getTypeWithFacts(resultType, TypeFacts.NEUndefinedOrNull).flags & TypeFlags.Never) {
+            if (resultType === unreachableNeverType || reference.parent && reference.parent.kind === SyntaxKind.NonNullExpression && resultType !== neverType && getTypeWithFacts(resultType, TypeFacts.NEUndefinedOrNull).flags & TypeFlags.Never) {
```
Comment (weswigham) [inline src/compiler/checker.ts:22188]: This should probably be a check for `TypeFlags.Never`, unless we have a good reason to ignore the `silentNeverType`?

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (dragomirtitian) [reply src/compiler/checker.ts:22188]: Thanks for the feedback. Changed it to use type flags.

**Review by weswigham — APPROVED** [review]
