### PR TITLE
Skip derived override assignment declarations

### LINKED ISSUE #51191: In JS, property assignment incorrectly overrides accessor from base
# Bug Report

### 🔎 Search Terms

inferring properties from assignments

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _inferring properties from assignments_

### ⏯ Playground Link

N/A

### 💻 Code

Steps to reproduce:

`test.js`
```js
export class Element {
  /**
   * @returns {String}
   */
  get textContent() {
    return  ''
  }
  set textContent(x) {}
  cloneNode() { return this}
}
export class HTMLElement extends Element {}
export class TextElement extends HTMLElement {
  get innerHTML() { return this.textContent; }
  set innerHTML(html) { this.textContent = html; }
  toString() {
    const outerHTML = toString.call(this.cloneNode());
    return outerHTML.replace(/></, `>${this.textContent}<`);
  }
}
```

Run
```bash
tsc --declaration --allowJs test.js --outDir types
```

### 🙁 Actual behavior

`types/test.d.ts` is generated as:
```ts
export class Element {
    set textContent(arg: string);
    /**
     * @returns {String}
     */
    get textContent(): string;
    cloneNode(): Element;
}
export class HTMLElement extends Element {
}
export class TextElement extends HTMLElement {
    set innerHTML(arg: any);
    get innerHTML(): any;
    textContent: any;
    toString(): any;
}
```

This is incorrect:

```ts
error TS2610: 'textContent' is defined as an accessor in class 'HTMLElement', but is overridden here in 'TextElement' as an instance property.

2     textContent: any;
      ~~~~~~~~~~~
```

### 🙂 Expected behavior

`types/test.d.ts` should be:
```ts
export class Element {
    set textContent(arg: string);
    /**
     * @returns {String}
     */
    get textContent(): string;
    cloneNode(): Element;
}
export class HTMLElement extends Element {
}
export class TextElement extends HTMLElement {
    set innerHTML(arg: any);
    get innerHTML(): any;
    toString(): any;
}
```

### Workaround:
```js
  set innerHTML(html) {
    /** @type {string} */
    this.textContent = html;
  }
```

### PR DESCRIPTION
**Pull request by sandersn**
In JS, assignment declarations outside a constructor (or `static` block) no longer override a base property if one exists. For example:

```js
class B {
  p = 1
}
class C extends B {
  m() {
    this.p = 1
  }
}
```

Would previously create a derived property `C#p`, but no longer does. Now C's property is `B#p`, because `this.p = 1` is no longer treated as a declaration.

Fixes #51191

### CODE REVIEW

**Comment by sandersn** [comment]
@jakebailey I believe you were interested in a case where our symbol baselines were useful. Here, the diff in inferringClassMembersFromAssignment shows the transfer of `p`'s declaration from Derived to Base. Though a find-all-refs baseline diff would be easier to read.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12073,8 +12073,22 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                        && !isConstructorDeclaredProperty(derived)
+                        && !findAncestor(derived.valueDeclaration, n => isClassLike(n) ? "quit" : isClassStaticBlockDeclaration(n))) {
+                        symbols.set(s.escapedName, s);
+                    }
+                    // otherwise let the derived property override the base property
+                }
+                else {
+                    symbols.set(s.escapedName, s);
+                }
             }
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:12092]:
```suggestion
            if (isStaticPrivateIdentifierProperty(s)) {
                continue;
            }
            const derived = symbols.get(s.escapedName);
            if (derived) {
                // non-constructor/static-block assignment declarations are ignored here; they're not treated as overrides
                if (derived.valueDeclaration
                    && isBinaryExpression(derived.valueDeclaration)
                    && !isConstructorDeclaredProperty(derived)
                    && !findAncestor(derived.valueDeclaration, n => isClassLike(n) ? "quit" : isClassStaticBlockDeclaration(n))) {
                    symbols.set(s.escapedName, s);
                }
                // otherwise let the derived property override the base property
            }
            else {
                symbols.set(s.escapedName, s);
            }
```

Comment (sandersn) [reply src/compiler/checker.ts:12092]: Welp, github's Apply Suggestion is broken, so I guess I'll have to do it manually.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -12073,7 +12073,21 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            if (isStaticPrivateIdentifierProperty(s)) {
+                continue;
+            }
+            const derived = symbols.get(s.escapedName);
+            if (derived) {
+                // non-constructor/static-block assignment declarations are ignored here; they're not treated as overrides
+                if (derived.valueDeclaration
+                    && isBinaryExpression(derived.valueDeclaration)
+                    && !isConstructorDeclaredProperty(derived)
+                    && !findAncestor(derived.valueDeclaration, n => isClassLike(n) ? "quit" : isClassStaticBlockDeclaration(n))) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:12085]: Could you use this?

```suggestion
                    && !getContainingClassStaticBlock(derived.valueDeclaration))
```

The semantics are slightly different because it quits on function-like nodes.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -12073,7 +12073,21 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
     function addInheritedMembers(symbols: SymbolTable, baseSymbols: Symbol[]) {
         for (const s of baseSymbols) {
-            if (!symbols.has(s.escapedName) && !isStaticPrivateIdentifierProperty(s)) {
+            if (isStaticPrivateIdentifierProperty(s)) {
+                continue;
+            }
+            const derived = symbols.get(s.escapedName);
+            if (derived) {
+                // non-constructor/static-block assignment declarations are ignored here; they're not treated as overrides
+                if (derived.valueDeclaration
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:12082]: Do you only need to do these checks if the valueDeclaration is in a JS file?

Comment (sandersn) [reply src/compiler/checker.ts:12082]: Oh wait, only JS files have symbols whose valueDeclaration is a BinaryExpression. If TS had such a symbol, we'd want it to follow these rules too.
In fact, isConstructorDeclaredProperty checks all the right things so I don't have to do it here.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:12085]: Yep, quitting on function-like nodes makes sense for function declarations and expressions since they bind `this`. Thanks for pointing this out.

**Review by jakebailey — APPROVED** [review]
