### PR TITLE
For import completion, if multiple re-exports exist, choose the one with the shortest path

### LINKED ISSUE #19888: Autoimport does not respect TS re-export files
_From @artaommahe on November 9, 2017 11:25_

- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:
1. e.x. angular app, write `Component`
2. press enter for autocomplete/autoimport
3. see
```ts
import { Component } from "@angular/core/src/metadata/directives";
```

expected
```ts
import { Component } from "@angular/core";
```

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#37926_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19888

### CODE REVIEW

File: src/compiler/core.ts [hunk 1]
```diff
@@ -394,6 +394,14 @@ namespace ts {
         return result;
     }
 
+    export function mapIter<T, U>(iter: Iterator<T>, mapFn: (x: T) => U): Iterator<U> {
```
Comment (armanio123) [inline src/compiler/core.ts]: I'll suggest not abbreviating. Instead of mapIter -> mapIterator.

Same for the parameter: iter -> iterator

File: src/compiler/core.ts [hunk 2]
```diff
@@ -917,6 +925,36 @@ namespace ts {
...
+            if (done) {
+                return best;
+            }
+            if (isBetter(value, best)) {
+                best = value;
+            }
+        }
+    }
+
+    export function arrayIter<T>(array: ReadonlyArray<T>): Iterator<T> {
```
Comment (armanio123) [inline src/compiler/core.ts]: Same name abbreviation
