### PR TITLE
fix(42678): detect access to uninitialized variable in IIFE

### LINKED ISSUE #42678: Undetected access to uninitialized variable
### 🔎 Search Terms

* ReferenceError: can't access lexical declaration before initialization
* undetected access uninitialized variable
* used before assignment

### 🕗 Version & Regression Information

Reproducible in Playground with versions > 3.3.3333 including

* 4.1.3
* 4.2.0-dev20210206
* ...

*Not* reproducible with 3.3.3333

This changed between versions 3.3.3333 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3#code/MYewdgzgLgBA2gKBsmBDANElAjTBdGAXhgAoSBKALnjAFcBbbAUwCd0Y7HWDCA+GAN5ZkAehEwAqmAAmTKE2DzpaYMCYQIMKCBi0wASwNR9qADb6AXk2UA3VCxPZTTYTFCQQzgHSmQAcxJUcgBuVxY5WhYweFcUGAAGTDi4xNc8UIBfcgpgoA)

### 💻 Code

```ts
const [
    a,
    b,
] = ((): [number, number] => {
    // Undetected access to uninitialized variable
    console.log(a);
    return [
        0,
        0,
    ];
})();
```

### 🙁 Actual behavior

Undetected access of uninitialized variable.  Crash at JavaScript runtime.

### 🙂 Expected behavior

Compile time error:  "Variable 'a' is used before being asigned."

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #42678

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2439,10 +2439,24 @@ namespace ts {
...
         function isSameScopeDescendentOf(initial: Node, parent: Node | undefined, stopAt: Node): boolean {
-            return !!parent && !!findAncestor(initial, n => n === stopAt || isFunctionLike(n) ? "quit" : n === parent);
+            return !!parent && !!findAncestor(initial, n => {
+                if (n === stopAt) {
+                    return "quit";
+                }
+                else if (n === parent) {
+                    return true;
+                }
+                else if(isFunctionLike(n)) {
```
Comment (jakebailey) [inline src/compiler/checker.ts:2453]:
```suggestion
                else if (isFunctionLike(n)) {

```

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by jakebailey** [comment]
I've gone and merged main into this and fixed the one coding style thing to move this forward.

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot user test this

**Comment by jakebailey** [comment]
@typescript-bot user test this

**Comment by jakebailey** [comment]
@typescript-bot user test this

**Comment by jakebailey** [comment]
Sorry about the noise on this; lots of build issues. 🙂

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2533,10 +2533,24 @@ namespace ts {
 
         /* Starting from 'initial' node walk up the parent chain until 'stopAt' node is reached.
          * If at any point current node is equal to 'parent' node - return true.
+         * If current node is an IIFE, continue walking up.
          * Return false if 'stopAt' node is reached or isFunctionLike(current) === true.
          */
         function isSameScopeDescendentOf(initial: Node, parent: Node | undefined, stopAt: Node): boolean {
-            return !!parent && !!findAncestor(initial, n => n === stopAt || isFunctionLike(n) ? "quit" : n === parent);
+            return !!parent && !!findAncestor(initial, n => {
```
Comment (sandersn) [inline src/compiler/checker.ts:2540]: Isn't this equivalent? I *think* I like it better simply because it's so much shorter, although I'm not 100% sure.
```suggestion
            return !!parent && !!findAncestor(initial, n => n === stopAt || isFunctionLike(n) && !getImmediatelyInvokedFunctionExpression() : n === parent);
```

Comment (Zzzen) [reply src/compiler/checker.ts:2540]: Yeah, it works. But I wonder if we should have `n === parent` before `isFunctionLike(n) && !getImmediatelyInvokedFunctionExpression()` because `n` might be a function.

**Review by sandersn — APPROVED** [review]
