### PR TITLE
fix(47158): Removes comments when line variable declaration

### LINKED ISSUE #47158: TypeScript removes comments even when `removeComments: false`
# Bug Report

TypeScript removes comments when transpiling even when `removeComments: false`.

### 🔎 Search Terms

removeComments; comments;

### 🕗 Version & Regression Information

Seems to happen on all versions (at least from 3.x to latest).

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.3#code/DYUwLgBAhhC8EHoBUBtFASA3gSwHbbAAUoAnKAWwGcBfAXVqQQk2oG4BYAKFEgCMAuCAHteAKxABjSPGRoseAsTJU6DJiw6cgA)

### 💻 Code

Specifying a type on `b` causes the problem to manifest,

```ts
let a = /*[[${something}]]*/ {};
let b: any = /*[[${something}]]*/ {};
```

### 🙁 Actual behavior

Produces the following output when `removeComments` is set to `false` on tsconfig.json:

```js
"use strict";
let a = /*[[${something}]]*/ {};
let b = {};
```

### 🙂 Expected behavior

Should  keep the comments on both lines:

```js
"use strict";
let a = /*[[${something}]]*/ {};
let b = /*[[${something}]]*/ {};
```

### PR DESCRIPTION
**Pull request by islandryu**
Fixes #47158

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -3102,7 +3102,7 @@ namespace ts {
             emit(node.name);
             emit(node.exclamationToken);
             emitTypeAnnotation(node.type);
-            emitInitializer(node.initializer, node.type ? node.type.end : node.name.end, node, parenthesizer.parenthesizeExpressionForDisallowedComma);
+            emitInitializer(node.initializer, node.type ? node.type.end : node.name.emitNode?.typeNode ? node.name.emitNode.typeNode.end : node.name.end, node, parenthesizer.parenthesizeExpressionForDisallowedComma);
```
Comment (jakebailey) [inline src/compiler/emitter.ts:3105]: Seems like this could be:

```suggestion
            emitInitializer(node.initializer, node.type?.end ?? node.name.emitNode?.typeNode?.end ?? node.name.end, node, parenthesizer.parenthesizeExpressionForDisallowedComma);

```

Which feels less confusing to me than a one liner conditional expression.

File: src/compiler/transformers/ts.ts [hunk 2]
```diff
@@ -2209,12 +2209,16 @@ namespace ts {
...
 
         function visitVariableDeclaration(node: VariableDeclaration) {
-            return factory.updateVariableDeclaration(
+            const updated = factory.updateVariableDeclaration(
                 node,
                 visitNode(node.name, visitor, isBindingName),
                 /*exclamationToken*/ undefined,
                 /*type*/ undefined,
                 visitNode(node.initializer, visitor, isExpression));
+            if(node.type){
```
Comment (jakebailey) [inline src/compiler/transformers/ts.ts:2218]: Nit

```suggestion
            if (node.type){

```

File: src/compiler/factory/emitNode.ts [hunk 3]
```diff
@@ -279,4 +279,14 @@ namespace ts {
...
+
+    export function setTypeNode<T extends Node>(node: T, type: TypeNode): T {
+        const emitNode = getOrCreateEmitNode(node);
+        emitNode.typeNode = type;
+        return node;
+    }
+
+    export function getTypeNode<T extends Node>(node: T): TypeNode | undefined {
+        return node.emitNode?.typeNode;
+    }
```
Comment (jakebailey) [inline src/compiler/factory/emitNode.ts:291]: I think these should both be marked `@internal` like the functions above.

**Review by jakebailey — CHANGES_REQUESTED** [review]
Left a few comments.

File: src/compiler/emitter.ts [hunk 4]
```diff
@@ -5325,6 +5326,10 @@ namespace ts {
                 commentsDisabled = false;
             }
             emitTrailingCommentsOfNode(node, emitFlags, commentRange.pos, commentRange.end, savedContainerPos, savedContainerEnd, savedDeclarationListContainerEnd);
+            const typeNode = getTypeNode(node);
+            if(typeNode){
```
Comment (jakebailey) [inline src/compiler/emitter.ts:5330]:
```suggestion
            if (typeNode) {

```

File: src/compiler/transformers/ts.ts [hunk 5]
```diff
@@ -2209,12 +2209,17 @@ namespace ts {
...
 
         function visitVariableDeclaration(node: VariableDeclaration) {
-            return factory.updateVariableDeclaration(
+            const updated = factory.updateVariableDeclaration(
                 node,
                 visitNode(node.name, visitor, isBindingName),
                 /*exclamationToken*/ undefined,
                 /*type*/ undefined,
                 visitNode(node.initializer, visitor, isExpression));
+            if (node.type){
```
Comment (jakebailey) [inline src/compiler/transformers/ts.ts:2218]:
```suggestion
            if (node.type) {
```

**Review by jakebailey — COMMENTED** [review]
Must have typo'd my suggestion, sorry! There's another one I noticed later.

File: src/compiler/emitter.ts [hunk 6]
```diff
@@ -5325,6 +5326,11 @@ namespace ts {
                 commentsDisabled = false;
             }
             emitTrailingCommentsOfNode(node, emitFlags, commentRange.pos, commentRange.end, savedContainerPos, savedContainerEnd, savedDeclarationListContainerEnd);
+            const typeNode = getTypeNode(node);
+            if (typeNode) {
+
```
Comment (jakebailey) [inline src/compiler/emitter.ts:5331]:
```suggestion
```

**Comment by islandryu** [comment]
I'm sorry.
I checked and committed this time.

File: src/compiler/emitter.ts [hunk 7]
```diff
@@ -3102,7 +3102,8 @@ namespace ts {
             emit(node.name);
             emit(node.exclamationToken);
             emitTypeAnnotation(node.type);
-            emitInitializer(node.initializer, node.type ? node.type.end : node.name.end, node, parenthesizer.parenthesizeExpressionForDisallowedComma);
+            emitInitializer(node.initializer, node.type?.end ?? node.name.emitNode?.typeNode?.end ?? node.name.end, node, parenthesizer.parenthesizeExpressionForDisallowedComma);
+
```
Comment (jakebailey) [inline src/compiler/emitter.ts:3106]:
```suggestion
```

Sorry, seems like there's another. Apologies for not flagging these consistently.

**Review by jakebailey — COMMENTED** [review]
LGTM with the formatting change, but there's a baseline update that should be made before approval and merge as those public APIs got dropped so their definitions have to be reverted.

**Review by jakebailey — APPROVED** [review]
