### PR TITLE
Fix type keyword completions

### LINKED ISSUE #28737: completions don't include primitives for type arguments inside a function
- VSCode Version: 1.29.1 (1.29.1)
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. create a node typescript project
2. `npm install querystring`
3. `type let m = new Map<string,`

**Expected:**
I would have a Map with string key.  No autocomplete would be preformed since I already have a valid statement

**Result:**
When you type the `,` vscode will autocomplete to `let spMap = new Map<stringify,` and add an import for `import { stringify } from 'querystring';`.

I haven't tested this with other primitive types, so I only know for sure that it fails with `string`. 

Does this issue occur when all extensions are disabled?: Yes

wrong import

### PR DESCRIPTION
**Pull request by sandersn**
1. In functions, type keywords were omitted.
2. In All context, no keywords were omitted.

(1) fixes #28737
(2) removes 17 keywords that should not be suggested, even at the
toplevel of a typescript file:

* private
* protected
* public
* static
* abstract
* as
* constructor
* get
* infer
* is
* namespace
* require
* set
* type
* from
* global
* of

I don't know whether we have a bug tracking this or not.

### CODE REVIEW

**Comment by sandersn** [comment]
Unless somebody knows how to un-update a submodule, I'm going to leave prettier in there. It's a result of `git add *` inside `~/ts/tests/cases`

File: tests/cases/fourslash/completionInFunctionLikeBody.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ verify.completions(
         includes: ["async", "await"].map(
             name => ({ name, sortText: completion.SortText.GlobalsOrKeywords })
         ),
-        excludes: ["public", "private", "protected", "constructor", "readonly", "static", "abstract", "get", "set"],
+        excludes: ["public", "private", "protected", "constructor", "static", "abstract", "get", "set"],
```
Comment (sheetalkamat) [inline tests/cases/fourslash/completionInFunctionLikeBody.ts]: Why is `readonly` ok in at position 1 and 2 ?

File: src/harness/fourslash.ts [hunk 2]
```diff
@@ -4968,8 +4951,20 @@ namespace FourSlashInterface {
             "let",
             "package",
             "yield",
+            "any",
             "async",
             "await",
+            "boolean",
```
Comment (sheetalkamat) [inline src/harness/fourslash.ts]: Why? I don't think we should be showing these here

File: tests/cases/fourslash/completionInFunctionLikeBody.ts (hunk 1 above)
Comment (sandersn) [reply tests/cases/fourslash/completionInFunctionLikeBody.ts]: we allow now type keywords there and readonly is a type keyword with things like `readonly T[]`

File: src/harness/fourslash.ts (hunk 2 above)
Comment (sheetalkamat) [reply src/harness/fourslash.ts]: I think you want to check if 
`let m = new Map<string/**/` is  isPossiblyTypeArgumentPosition and add type keywords + function value keywords

Comment (sandersn) [reply src/harness/fourslash.ts]: As far as I can tell, there's no more precise context than "inside a function" for completions. I think if we show things like `class, var, interface` there then type keywords make sense too.

Comment (sheetalkamat) [reply src/harness/fourslash.ts]: don't think so. `class, var, interface ` can really be used in the function context to start local declarations? why would you want types?

Comment (sandersn) [reply src/harness/fourslash.ts]: `filterGlobalCompletion` has code that looks like it tries to do this, but it relies exclusively on `isTypeOnlyCompletion`. Is that a good place to add a check for isPossiblyTypeArgumentPosition, do you think?

**Comment by sandersn** [comment]
OK, the PR is updated with my better understanding of KeywordCompletionFilters.TypeKeywords, which is now set when the context is possibly a type argument.

I'm going to see if the two variants of `isType*` in filterGlobalCompletion can be simplified to one now.

**Comment by sandersn** [comment]
Looks like No, because the distinction allows us to continue to suggest values when something *might* be a type argument (that is, when the brackets are unclosed), and to only suggest types when something is *definitely* a type argument (when the brackets are correctly matched).

File: src/harness/fourslash.ts [hunk 3]
```diff
@@ -5041,40 +5024,23 @@ namespace FourSlashInterface {
...
-            "set",
             "string",
             "symbol",
-            "type",
             "unique",
             "unknown",
-            "from",
-            "global",
             "bigint",
-            "of",
```
Comment (andrewbranch) [inline src/harness/fourslash.ts]: This is awesome. What was the change that actually made all these disappear from globals though?

File: src/services/completions.ts [hunk 4]
```diff
@@ -1182,7 +1182,7 @@ namespace ts.Completions {
         function filterGlobalCompletion(symbols: Symbol[]): void {
             const isTypeOnly = isTypeOnlyCompletion();
             const allowTypes = isTypeOnly || !isContextTokenValueLocation(contextToken) && isPossiblyTypeArgumentPosition(contextToken, sourceFile, typeChecker);
-            if (isTypeOnly) {
+            if (allowTypes) {
                 keywordFilters = isTypeAssertion()
                     ? KeywordCompletionFilters.TypeAssertionKeywords
                     : KeywordCompletionFilters.TypeKeywords;
```
Comment (sandersn) [inline src/services/completions.ts]: note that this means we no longer offer *other* keywords in completions; `new, this, typeof` are the useful ones I saw from scanning the list. Probably `this` and `typeof` should be added to the list `typeKeywords`. Suggesting `new` isn't very useful since it only saves 3 characters (or less).

For example,

```ts
return x < this.property;
```

will not suggest `this` any more.

File: src/services/completions.ts [hunk 5]
```diff
@@ -2060,16 +2060,18 @@ namespace ts.Completions {
                 case KeywordCompletionFilters.None:
                     return false;
                 case KeywordCompletionFilters.All:
-                    return kind === SyntaxKind.AsyncKeyword || SyntaxKind.AwaitKeyword || !isContextualKeyword(kind) && !isClassMemberCompletionKeyword(kind) || kind === SyntaxKind.DeclareKeyword || kind === SyntaxKind.ModuleKeyword
```
Comment (sandersn) [inline src/services/completions.ts]: @andrewbranch Here! `SyntaxKind.AwaitKeyword` isn't compared `===kind` and since it's truthy it caused `.All` to let *all* keywords through.

File: src/services/completions.ts (hunk 4 above)
Comment (andrewbranch) [reply src/services/completions.ts]: > Probably `this` and `typeof` should be added to the list `typeKeywords`.

Agreed. That seems objectively correct, since those _are_ valid in a type position.

But why wouldn’t we show both type and non-type keywords here, given the uncertainty? Related questions:

1. Are we trying to avoid semantic work here? It seems possible to differentiate between an `x` that can’t possibly accept type parameters (so we’re definitely not in a type position) vs. an `x` that’s generic (so we may or may not be).
2. If we are trying to avoid semantic work, would it be reasonable to use whitespace as a heuristic? `Map <string, number>` seems extraordinarily uncommon, and `x<3` fairly uncommon too.

I’m not sure whether these are practical or not, but I don’t think they’re necessary for this PR—seems like an improvement already. Just food for thought. (I do think adding `this` and `typeof` now is probably worth it, though.)

**Comment by DanielRosenwasser** [comment]
Does this fix #27955? (it's okay if it doesn't, but just close it if it doesn)

File: src/services/completions.ts (hunk 4 above)
Comment (sandersn) [reply src/services/completions.ts]: Hmm. Both the simple "show all" idea and "be smarter about possible type arguments" idea are good.

For the second, isPossiblyTypeArgumentPosition *already* calls `getTypeAtLocation`, so it's just a matter of querying the returned value.

I added `this` and `typeof` as types and it broke find all refs of global `this` horribly. I haven't looked at why, but it means that I'll probably keep them where they are for now.

**Comment by sandersn** [comment]
@DanielRosenwasser pretty sure it can't possibly, because `implements` isn't one of the keywords that are no longer suggested.

Also, there are some JS-specific checks that happen. They might avoid this fix entirely; I haven't tested that.

File: src/services/completions.ts (hunk 4 above)
Comment (sandersn) [reply src/services/completions.ts]: Yep, `isPossiblyTypeArgumentPosition` already is smarter about possible type arguments. My tests just don't show it.

Comment (sandersn) [reply src/services/completions.ts]: In any case, my original example, `x < this.property`, is wrong -- it *does* suggest `this`. It just doesn't when the identifier to the left of `<` is a generic signature. 

So I think making `this` and `typeof` type keywords is best fixed in a separate PR, since it requires more knowledge of services than I have now, and only affects things that are genuinely type contexts. I filed a bug #32486 to track it.

Comment (andrewbranch) [reply src/services/completions.ts]: Ah, that sounds better. I was a little concerned that you’d be missing those _any_ time you were in the RHS of a less-than arithmetic comparison. 👍

File: src/services/completions.ts [hunk 6]
```diff
@@ -1182,7 +1182,7 @@ namespace ts.Completions {
         function filterGlobalCompletion(symbols: Symbol[]): void {
             const isTypeOnly = isTypeOnlyCompletion();
             const allowTypes = isTypeOnly || !isContextTokenValueLocation(contextToken) && isPossiblyTypeArgumentPosition(contextToken, sourceFile, typeChecker);
-            if (isTypeOnly) {
+            if (allowTypes) {
```
Comment (sheetalkamat) [inline src/services/completions.ts]: I don't think this is correct change. `KeywordFilters = KeywordCompletionFilters.TypeKeywords` would only offer type keywords? but that's not what you want here. I think you want isTypeOnly => `KeywordCompletionFilters.TypeKeywords`, otherwise if you have `allowTypes` then you want global + type keywords and rest of the time only global keywords ?

Comment (sandersn) [reply src/services/completions.ts]: After some discussion, we decided that isPossiblyTypeArgumentPosition is smart enough to rely on *only* providing types when it's true.

This simplifies code that relies on isPossiblyTypeArgumentPosition, as well as some tests. We no longer fall back to types+values, instead suggesting one or the other. isPossiblyTypeArgumentPosition should have a very low false positive rate since it relies on types, which means that people could see values-only completions a little more than before. The most common failure case I can think of is when a variable that should have a generic signature type actually has type `any`. I think this is acceptable.
