### PR TITLE
Fix infinite recursion in union type reduction

### LINKED ISSUE #2997: Compiler error - "Maximum call stack size exceeded"
(1.5 beta)

This is the most I can reduce it while still having it crash:

```typescript
class Module {
	public members: Class[];
}

class Namespace {
	public members: (Class | Property)[];
}

class Class {
	public parent: Namespace;
}

class Property {
	public parent: Module | Class;
}

var t: Class | Property;
t.toString();
```

`tsc foo.ts -t es5`

```
G:\src\libjass\node_modules\typescript\bin\tsc.js:0
(function (exports, require, module, __filename, __dirname) { /*! ************
^
RangeError: Maximum call stack size exceeded
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js)
    at unionTypeRelatedToType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11862:35)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11787:42)
    at stringIndexTypesRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:12195:35)
    at objectTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11955:43)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11811:34)
    at propertiesRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:12042:43)
    at objectTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11949:30)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11811:34)
    at typeRelatedToUnionType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11850:35)
```

Alternative call stack for the crash (same code):

```
G:\src\libjass\node_modules\typescript\bin\tsc.js:11929
                    sourceStack = [];
                    ^
RangeError: Maximum call stack size exceeded
    at objectTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11929:21)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11811:34)
    at checkTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11723:26)
    at checkTypeSubtypeOf (G:\src\libjass\node_modules\typescript\bin\tsc.js:11703:20)
    at isTypeSubtypeOf (G:\src\libjass\node_modules\typescript\bin\tsc.js:11697:20)
    at isSubtypeOfAny (G:\src\libjass\node_modules\typescript\bin\tsc.js:11363:43)
    at removeSubtypes (G:\src\libjass\node_modules\typescript\bin\tsc.js:11373:21)
    at getUnionType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11410:17)
    at getReducedTypeOfUnionType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11426:36)
    at getApparentType (G:\src\libjass\node_modules\typescript\bin\tsc.js:10824:24)
```

The original code from which this test case is derived is [here.](https://github.com/Arnavion/libjass/blob/8e12db7/gulplib/typescript/ast.ts)

Edit: Reduced the case some more - removed the `fullName` getters and simplified the types of `member`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #2997 and #3152. Subsumes #3071.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3643,9 +3630,17 @@ module ts {
...
             if (!type.reducedType) {
-                type.reducedType = getUnionType(type.types, /*noSubtypeReduction*/ false);
+                type.reducedType = resolvingType;
+                let reducedType = getUnionType(type.types, /*noSubtypeReduction*/ false);
+                if (type.reducedType === resolvingType) {
+                    type.reducedType = reducedType;
+                }
+            }
+            else if (type.reducedType === resolvingType) {
+                type.reducedType = type;
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: 1. No error when we hit the circularity?  Or is that handled elsewhere?  If handled elsewhere, can you comment in the code where.
2.  It seems like you're setting the reduced type to the type itself.  That seems... odd.  What's the intuition for why that's the appropriate type.

Comment (ahejlsberg) [inline src/compiler/checker.ts]: Subtype reduction is basically an optimization we do to avoid excessively large union types, which take longer to process and look strange in quick info and error messages. Semantically there is no difference between the reduced type and the type itself. So, when we detect a circularity we simply say that the reduced type is the type itself.

Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: That makes sense.  We should definitely state this in the code itself with a comment of some sort.  It's not at all evident, and it's definitely important for the code to make this clear that this is expected and desirable behavior.

**Comment by CyrusNajmabadi** [comment]
:+1: with the change to document the behavior/invariants more clearly in the code.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3643,9 +3630,17 @@ module ts {
         }
 
         function getReducedTypeOfUnionType(type: UnionType): Type {
-            // If union type was created without subtype reduction, perform the deferred reduction now
+            // If union type was created without subtype reduction, perform the deferred reduction now. If a circularity
+            // is detected, simply use the type itself.
             if (!type.reducedType) {
-                type.reducedType = getUnionType(type.types, /*noSubtypeReduction*/ false);
+                type.reducedType = resolvingType;
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Sorry, I know we talked about this, but why do you not have to use the type resolution stack for this? What if it participates in a cycle that other functions have to know about, in order to report errors?

Comment (ahejlsberg) [inline src/compiler/checker.ts]: The kind of cycles detected by the type resolution stack has nothing to do with reduced union types and would never involve union type reduction. This is a distinct and unrelated kind of recursion. It so happens to use a marker type called `resolvingType` for cycle detection, but that's just a name. Maybe it should be renamed `markerType` or `circularType` since it isn't actually used by type resolution anymore (we have the resolution stack for that).

Comment (JsonFreeman) [inline src/compiler/checker.ts]: I think circularType is good

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I don't get it, we always use `resolvingType` to detect other circularities, why would we be different here?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -3643,9 +3630,17 @@ module ts {
         }
 
         function getReducedTypeOfUnionType(type: UnionType): Type {
-            // If union type was created without subtype reduction, perform the deferred reduction now
+            // If union type was created without subtype reduction, perform the deferred reduction now. If a circularity
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can you change this to "If **a** union type was created", and move the second sentence to the next line?

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: The `resolvingType` marker was removed in #2991. This introduces a similar marker, but used for detecting a different kind of circularity.
