### PR TITLE
recompute character to column when comparing indentations

### LINKED ISSUE #12175: Formatter is broken when using tabs
**TypeScript Version:**  2.0.8

In VS Code I have configured tabs to be 2 characters wide (`"editor.tabSize": 2`). I noticed that some lines of code are incorrectly ignored by the formatter when using this setting.

For example, the formatter should outdent line two in the following snippet to 1 tab only, which initially has 2 tabs, and it fails to do so:

```ts
const foo = [
		1
];
```

Any other indentation on that line makes the formatter behave properly and format it with a single tab. It's only when using 2 tabs that it stays put.

It feels like the tab size is incorrectly taken into account when indenting using tabs, when it should simply be ignored. This is confirmed by setting `tabSize` to 3 and indenting line two with 3 tabs: the formatter will ignore that line. It also reproduces with `tabSize` of 4 (default) and indenting line two with 4 tabs. And so on...

cc @jrieken

### PR DESCRIPTION
**Pull request by vladima**
we always compute indentation as column so in order to compare it with character position in line - character position must be converted to column as well.

fixes #12175

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -886,12 +886,20 @@ namespace ts.formatting {
...
+                if (indentation !== characterToColumn(startLinePosition, tokenStart.character) || indentationIsDifferent(indentationString, startLinePosition)) {
                     recordReplace(startLinePosition, tokenStart.character, indentationString);
                 }
             }
         }
 
+        function characterToColumn(startLinePosition: number, characterInLine: number): number {
+            let column = 0;
+            for (let i = 0; i < characterInLine; i++) {
+                column += sourceFile.text.charCodeAt(startLinePosition + i) === CharacterCodes.tab ? options.tabSize : 1;
```
Comment (CyrusNajmabadi) [inline src/services/formatting/formatting.ts]: This doesn't seem quite right.  If i have ```<space><tab>``` then this math tells me i'm at ```(tabSize + 1)``` when i should be at ```tabSize```.

Comment (CyrusNajmabadi) [inline src/services/formatting/formatting.ts]: Roslyn's algorithm:

```c#
public static int ConvertTabToSpace(this string textSnippet, int tabSize, int initialColumn, int endPosition)
        {
            Contract.Requires(tabSize > 0);
            Contract.Requires(endPosition >= 0 && endPosition <= textSnippet.Length);

            int column = initialColumn;

            // now this will calculate indentation regardless of actual content on the buffer except TAB
            for (int i = 0; i < endPosition; i++)
            {
                if (textSnippet[i] == '\t')
                {
                    column += tabSize - column % tabSize;
                }
                else
                {
                    column++;
                }
            }

            return column - initialColumn;
        }
```

Comment (vladima) [inline src/services/formatting/formatting.ts]: fair enough, thanks for catching this

**Comment by vladima** [comment]
failure on the CI server is not related to this PR and caused by API changes in tslint - https://github.com/Microsoft/TypeScript/pull/12376 should address it

**Comment by mhegazy** [comment]
@vladima can you port this to release-2.1

**Comment by vladima** [comment]
already done
