### PR TITLE
Remove duplicate signatures in intersections

### LINKED ISSUE #32038: 3.5 regression: union type as property accessor break function parameter inference
**TypeScript Version:**  3.5.2 (it works with 3.4.4). Also tested on 3.6.0-dev.20190622

**Search Terms:**

**Code** (not real-life, just a repro)

```ts
const actions = ['resizeTo', 'resizeBy'] as const;
for (const action of actions) {
	window[action] = (x, y) => {
		window[action](x, y);
	}
}
```

**Expected behavior:**

`x` and `y` are of type `number` (like in 3.4)

**Actual behavior:**

`x` and `y` are of type `any`

**Playground Link:** (enable `noImplicitAny`, but it seems to be on 3.4)

https://www.typescriptlang.org/play/#src=%0D%0Aconst%20actions%20%3D%20%5B'resizeTo'%2C%20'resizeBy'%5D%20as%20const%3B%0D%0Afor%20(const%20action%20of%20actions)%20%7B%0D%0A%09window%5Baction%5D%20%3D%20(x%2C%20y)%20%3D%3E%20%7B%0D%0A%09%09window%5Baction%5D(x%2C%20y)%3B%0D%0A%09%7D%0D%0A%7D

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/32037

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #32038.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
DT run is clean (error is unrelated and exists with master branch as well).

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7257,13 +7257,22 @@ namespace ts {
...
                 stringIndexInfo = intersectIndexInfos(stringIndexInfo, getIndexInfoOfType(t, IndexKind.String));
                 numberIndexInfo = intersectIndexInfos(numberIndexInfo, getIndexInfoOfType(t, IndexKind.Number));
             }
-            setStructuredTypeMembers(type, emptySymbols, callSignatures, constructSignatures, stringIndexInfo, numberIndexInfo);
+            setStructuredTypeMembers(type, emptySymbols, callSignatures || emptyArray, constructSignatures || emptyArray, stringIndexInfo, numberIndexInfo);
+        }
+
+        function appendSignatures(signatures: Signature[] | undefined, newSignatures: readonly Signature[]) {
+            for (const sig of newSignatures) {
+                if (!signatures || every(signatures, s => !compareSignaturesIdentical(s, sig, /*partialMatch*/ false, /*ignoreThisTypes*/ false, /*ignoreReturnTypes*/ false, compareTypesIdentical))) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Uhhhh, it's probably worth noting that `compareSignaturesIdentical` needs some TLC - it currently erases constraints to `any` like `compareSignatures` used to, which causes spurious false positives. Concretely, that means that if I have a:
```ts
type Foo = (<T extends number>(x: T) => T) & (<T extends string>(x: T) => T)
```
I don't think we'll be happy with the result here... (I looked into this around https://github.com/microsoft/TypeScript/pull/31023 )

**Comment by ahejlsberg** [comment]
With latest commits we now properly compare type parameters, constraints, and defaults when checking signature identity. Baseline changes nicely reflect cases that should fail but previously didn't because we just erased type parameters.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14313,20 +14322,25 @@ namespace ts {
...
-            target = getErasedSignature(target);
+            // Check that type parameter constraints and defaults match. If they do, instantiate the source
+            // signature with the type parameters of the target signature and continue the comparison.
+            if (target.typeParameters) {
+                const mapper = createTypeMapper(source.typeParameters!, target.typeParameters);
+                for (let i = 0; i < target.typeParameters.length; i++) {
+                    const s = source.typeParameters![i];
+                    const t = target.typeParameters[i];
+                    if (!(s === t || compareTypes(instantiateType(getConstraintFromTypeParameter(s), mapper) || unknownType, getConstraintFromTypeParameter(t) || unknownType) &&
+                        compareTypes(instantiateType(getDefaultFromTypeParameter(s), mapper) || unknownType, getDefaultFromTypeParameter(t) || unknownType))) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Yeah, I don't think we can consider defaults when checking identity - if we do, then two conditional extends clauses that only differ in a local type parameter default (which doesn't affect relationship checking) will fail to be seen as identical.

Comment (weswigham) [reply src/compiler/checker.ts]: Eg, `(A extends <T = {}>() => T ? 1 : 0) extends (A extends <T = unknown>() => T ? 1 : 0) ? true : false` should resolve to `true`, I think, not `false`.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I'm not sure I understand how that example is relevant. Best I can tell at no point will we compare signatures for identity in the example.

**Comment by ahejlsberg** [comment]
@weswigham I don't see a compelling reason for why defaults shouldn't be included in identity checking. After all, we're checking whether the signatures are semantically *identical*, meaning that you get identical results no matter which one you pick. With different defaults that isn't the case.

**Comment by ahejlsberg** [comment]
The DT test run looks clean (the one failure appears completely unrelated).

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Conditional `extends` clauses are compared using `isTypeIdenticalTo` when checking if one conditional extends the other in the above example. Apparently this is already in use in the wild as a way to observe type "identity" in complex type toolbelt libraries.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: Ok, I see that logic in `structuredTypeRelatedTo`. Still, as far as I'm concerned, those two types aren't identical and I can't think of a meaningful definition of "identical" that would make it true for them, but not for the other cases we care about. It would just seem really odd to make an exception for local type parameter defaults, but nothing else.

Comment (weswigham) [reply src/compiler/checker.ts]: I mean, we let you _assign_ a function with a default to a function with a different default and vice-versa - it's just the typesystem equivalent of aliasing. Generally defaults aren't observable up until the point where inference fails - this exposes them into relationship checking before inference is ever invoked, success or no.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I still don't think that merits a special exception to identity checking. The identity relation should be concerned with accurately identifying semantically identical types, and it does a better job of that now. I think we need to get this merged.

**Comment by weswigham** [comment]
DT is clean, but RWC is [strange](https://mseng.visualstudio.com/DefaultCollection/_git/Typescript/pullrequest/482156?path=%2Fbaselines%2Frwc%2Freference%2Fglimmer%2Fc_%2Ftest%2Fglimmer-vm%2Fpackages%2F%40glimmer%2Fobject-model%2Ftest%2Fcomputed-test.ts.errors.txt&_a=overview). A bunch of errors were eliminated in `fp-ts` (unsure why), while in `glimmer` we got a bunch of new errors.
