### PR TITLE
Fix contextual typing for post-spread tuple elements

### LINKED ISSUE #52684: False-positive errors regarding string array const
# Bug Report

### 🕗 Version & Regression Information

It's not a regression, the same behaviour can be observed on TS 4 and 5. (for TS 4, using [ts-toolbelt](https://github.com/millsp/ts-toolbelt)'s Narrow function gives equivalent results)

### 💻 Code

```ts
const staticPath1Level = ["home"] as const;
const staticPath2Level = ["home", "user"] as const;
const staticPath3Level = ["home", "user", "downloads"] as const;

const randomID = 'id' as string;

// TS 5
declare function foo<const T extends string[] | readonly string[]>(path: T): T;
// TS 4
// declare function foo<T extends string[] | readonly string[]>(path: F.Narrow<T>): T;

const a1 = foo([...staticPath1Level, randomID, 'doc.pdf']);
const a2 = foo([...staticPath2Level, randomID, 'doc.pdf']);
const a3 = foo([...staticPath3Level, randomID, 'doc.pdf']);

const b1 = foo([...staticPath1Level, randomID, 'folder', 'doc.pdf']);
const b2 = foo([...staticPath2Level, randomID, 'folder', 'doc.pdf']);
const b3 = foo([...staticPath3Level, randomID, 'folder', 'doc.pdf']);

const c1 = foo([...staticPath1Level, randomID, 'folder', 'subfolder', 'doc.pdf']);
const c2 = foo([...staticPath2Level, randomID, 'folder', 'subfolder', 'doc.pdf']);
const c3 = foo([...staticPath3Level, randomID, 'folder', 'subfolder', 'doc.pdf']);

const d1 = foo([...staticPath1Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);
const d2 = foo([...staticPath2Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);
const d3 = foo([...staticPath3Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);

```

### 🙁 Actual behavior

All return types are correct, e.g.:
```ts
const b3: readonly ["home", "user", "downloads", string, "folder", "doc.pdf"]
```

The call for a2 has the following error (b3, c3 also have the same error type, adjusted for their parameters):
> ts(2345)
> Argument of type '["home", "user", string, string]' is not assignable to parameter of type 'readonly ["home", "user", string, "doc.pdf"]'.
>  Type at position 3 in source is not compatible with type at position 3 in target.
>    Type 'string' is not assignable to type '"doc.pdf"'.

The call for b2 has the following error (c2, d2, d3 also have the same error type, adjusted for their parameters):
> ts(2322)
> Type 'string' is not assignable to type '"folder"'.

### 🙂 Expected behavior

Don't generate false-positive errors. Also, it's odd that there is no apparent pattern to when one of the errors is shown.

### Workaround

To silence these errors, `as const` can be used, but again, it's not really obvious where or how many times.
This partial code sample generates no errors:
```ts
const b2 = foo([...staticPath2Level, randomID, 'folder' as const, 'doc.pdf']);
const b3 = foo([...staticPath3Level, randomID, 'folder', 'doc.pdf' as const]);
```
This partial code sample still has false-positive errors:
```ts
const b2 = foo([...staticPath2Level, randomID, 'folder', 'doc.pdf' as const]);
const b3 = foo([...staticPath3Level, randomID, 'folder' as const, 'doc.pdf']);
```

### LINKED ISSUE #52760: Variadic Tuples that end in a literal type require explicit as const narrowing
# Bug Report

### 🔎 Search Terms

variadic, tuple, literal, spread

### 🕗 Version & Regression Information

First saw in v4.9.5; have tested back to 4.4.4 and still present.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about variadic.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.9.5#code/MYewdgzgLgBCDWAuGBtAdB6AnAlmA5igLoA0MYArgLYBGAplkTALyoDkAhm2WzdzAEYiAbgBQogPQSYAASgQAtHQAeABzrAoSrFhBZRoSLApgV6zXQAmydJii4CxHgEI2TVik782rkeMPQMADuevAcuibWqBho2HiEpDA+bizsXC5sMBwQMAFQfgbggSFY8BA2cQQZ7mnevmJAA

### 💻 Code

```ts
const ok: [...string[], number] = ['a', 'b', 1];

// @ts-expect-error
const unexpected: [...string[], '!'] = ['a', '!'];

const workaround: [...string[], '!'] = ['a', '!' as const];

const works: [string, '!'] = ['a', '!'];
```

### 🙁 Actual behavior

For Variadic Tuples that _end_ in a literal type, assigning a matching Tuple gives

> Type '[string, string]' is not assignable to type '[...string[], "!"]'.
>  Type at position 1 in source is not compatible with type at position 1 in target.
>    Type 'string' is not assignable to type '"!"'.

### 🙂 Expected behavior

For normal Tuples and Variadic Tuples that only _begin_ with a literal type, assignments do not need `as const` to prevent widening.

For example this works:

```ts
const works2: ['!', ...string[], ] = ['!', 'x'];
```

It would be more intuitive if all Tuples behaved in the same way.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #52684.
Fixes #52760.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

File: tests/cases/compiler/spreadsAndContextualTupleTypes.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+const b2 = foo([...staticPath2Level, randomID, 'folder', 'doc.pdf']);
+const b3 = foo([...staticPath3Level, randomID, 'folder', 'doc.pdf']);
+
+const c1 = foo([...staticPath1Level, randomID, 'folder', 'subfolder', 'doc.pdf']);
+const c2 = foo([...staticPath2Level, randomID, 'folder', 'subfolder', 'doc.pdf']);
+const c3 = foo([...staticPath3Level, randomID, 'folder', 'subfolder', 'doc.pdf']);
+
+const d1 = foo([...staticPath1Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);
+const d2 = foo([...staticPath2Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);
+const d3 = foo([...staticPath3Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);
```
Comment (Andarist) [inline tests/cases/compiler/spreadsAndContextualTupleTypes.ts:35]: I thought that this PR might also fix [this issue](https://github.com/microsoft/TypeScript/issues/52760) but it doesn't. Perhaps it's something to work looking into here? The problem is similar but it's kinda a reverse one. This PR fixes contextual types for post-spread elements at the expression/runtime level and this other case is about post-spread elements at the type level.

The problem is that `getTypeOfPropertyOfContextualType` is still used here without any modifications as the primary source for the contextual type. The logic was only adjusted in the "else" branch here. The contextual type for this case is successfully retrieved through [those lines](https://github.dev/microsoft/TypeScript/blob/d8e81bbf6e6614bab7a0c5fba1e88a173943d22d/src/compiler/checker.ts#L28844-L28847) and since this doesn't take the position in the array expression into account - it's just `string`.

```suggestion
const d3 = foo([...staticPath3Level, randomID, 'folder', 'subfolder', 'another-subfolder', 'doc.pdf']);

// repro from #52760
const e1: [...string[], '!'] = ['a', '!'];

```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -28883,10 +28883,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     // type of T.
     function getContextualTypeForElementExpression(arrayContextualType: Type | undefined, index: number): Type | undefined {
         return arrayContextualType && (
-            getTypeOfPropertyOfContextualType(arrayContextualType, "" + index as __String)
-            || mapType(
-                arrayContextualType,
-                t => getIteratedTypeOrElementType(IterationUse.Element, t, undefinedType, /*errorNode*/ undefined, /*checkAssignability*/ false),
+            index >= 0 && getTypeOfPropertyOfContextualType(arrayContextualType, "" + index as __String) ||
```
Comment (Andarist) [inline src/compiler/checker.ts:28886]: I know that it's not exactly 100% related to this case - but I was touching this function just recently [here](https://github.com/microsoft/TypeScript/pull/52589/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R28839). It would be cool if that improvement (if correct) could also go into 5.0 - both would make for a nice "batch" of improvements for contextual types for element expressions. 😉

File: tests/cases/compiler/spreadsAndContextualTupleTypes.ts (hunk 1 above)
Comment (ahejlsberg) [reply tests/cases/compiler/spreadsAndContextualTupleTypes.ts:43]: This would require us to reason about elements at a fixed offset from the end of a tuple. We currently only reason about elements at a fixed offset from the start. It adds some more complexity, but it is certainly possible to do.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
Tests and performance all look good.

File: tests/baselines/reference/variadicTuples2.types [hunk 3]
```diff
@@ -465,7 +465,7 @@ fn1([1, 'abc']);  // [number, string]
 fn1([1, 'abc', true]);  // [string, boolean]
 >fn1([1, 'abc', true]) : [string, boolean]
 >fn1 : <T, U>(t: [...unknown[], T, U]) => [T, U]
->[1, 'abc', true] : [number, string, boolean]
+>[1, 'abc', true] : [number, string, true]
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply tests/baselines/reference/variadicTuples2.types:468]: Following inference and instantiation, the contextual type for the array literal is `[...unknown[], string, boolean]`. The contextual type for the `true` literal is the is computed from `unknown | string | boolean` which previously would reduce to just `unknown`. With this PR we don't perform subtype reduction, so `boolean` survives in the contextual union type and causes the `true` literal to stay `true`. But the change doesn't really matter since we've already inferred `boolean` for `U`.
