### PR TITLE
simply quick fix for import type missing typeof

### LINKED ISSUE #24172: Provide a quick fix for 'module does not refer to a type'
```ts
// ./foo.ts

export async function bar() {
    let foo: import("./foo") = await import("./foo");
//           ^^^^^^^^^^^^^^^
// Module './foo' does not refer to a type, but is used as a type here.
}
```

We should give a quick fix in this scenario.

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #24172 #24192

### CODE REVIEW

**Comment by Kingwl** [comment]
@mhegazy 
sorry about this,
i have do these change and i forget to commit it

File: src/services/codefixes/fixAddModuleReferTypeMissingTypeof.ts [hunk 1]
```diff
@@ -7,26 +7,24 @@ namespace ts.codefix {
...
         getAllCodeActions: context => codeFixAll(context, errorCodes, (changes, diag) =>
             doChange(changes, context.sourceFile, getImportTypeNode(diag.file, diag.start!))),
     });
 
-    function getImportTypeNode(sourceFile: SourceFile, pos: number): ImportTypeNode | undefined {
+    function getImportTypeNode(sourceFile: SourceFile, pos: number): ImportTypeNode {
         const token = getTokenAtPosition(sourceFile, pos, /*includeJsDocComment*/ false);
         Debug.assert(token.kind === SyntaxKind.ImportKeyword);
         Debug.assert(token.parent.kind === SyntaxKind.ImportType);
         return <ImportTypeNode>token.parent;
```
Comment (andy-ms) [inline src/services/codefixes/fixAddModuleReferTypeMissingTypeof.ts]: Could be `cast(token.parent, isImportTypeNode)`.
