### PR TITLE
Fix check for `get`/`set` recommendation

### LINKED ISSUE #34884: "Did you mean 'get'/'set'?" errors have issues
Follow-up from https://github.com/microsoft/TypeScript/issues/26098 (PR at https://github.com/microsoft/TypeScript/pull/26446)

Current logic:

* Doesn't ever suggest the identifier/property access in the message (this was requested)
* Only works when the arity of a `set` is 1 (means it actually doesn't work with `Map`s)
* Only works when the parameter type's string representation is `string`.

Each of these is a bug.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #34884

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -4244,9 +4244,12 @@ namespace ts {
 
     export function tryGetPropertyAccessOrIdentifierToString(expr: Expression): string | undefined {
         if (isPropertyAccessExpression(expr)) {
-            return tryGetPropertyAccessOrIdentifierToString(expr.expression) + "." + expr.name;
+            const baseStr = tryGetPropertyAccessOrIdentifierToString(expr.expression);
+            if (baseStr !== undefined) {
+                return baseStr + "." + expr.name;
```
Comment (orta) [inline src/compiler/utilities.ts]: This is great 👍
