### PR TITLE
import statement from "node" in js source file could produce correct declaration path. 

### LINKED ISSUE #41800: Generated declaration for a JavaScript file refers to non-existing module
**TypeScript Version:**  4.1.2
**Search Terms:** javascript, javascript declaration, eventemitter (and bunch of others)

**Code**

```javascript
import { EventEmitter } from 'events';

export default class Foo extends EventEmitter {}
```

With tsconfig:

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "outDir": "./dist",
    "declaration": true,
    "strict": false,
    "rootDir": "./src"
  },
  "include": [
    "src/*.js",
    "src/**/*.js"
  ]
}
```

**Expected behavior:**

The generated declaration file should contain:

```typescript
import { EventEmitter } from "events"
export default class Flowtrace extends EventEmitter {}
```

**Actual behavior:**

```typescript
import { EventEmitter } from "node/events"
export default class Flowtrace extends EventEmitter {}
```

Which produces the following error:

> File '<project root>/node_modules/@types/node/events.d.ts' is not a module.ts(2306)

For now the fix appears to be to search-and-replace the `node/events` instances.

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #41800

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
Wait a minute, a little strange!

Trying to add test
```
// @target: esnext
// @module: commonjs
// @allowJs: true
// @checkJs: true
// @declaration: true
// @outDir: ./dist
// @filename: node_modules/@types/node/index.d.ts
/// <reference path="events.d.ts" />
// @filename: node_modules/@types/node/fs.d.ts
declare module "events" {
    export class EventEmitter {
        constructor();
    }
}
// @filename: /a.ts
/// <reference types="node" />
import { EventEmitter } from 'events';
class Foo extends EventEmitter {
    constructor(){
        super();
    }
}
export default Foo;
// @filename: /b.js
/// <reference types="node" />
import { EventEmitter } from 'events';
class Foo extends EventEmitter {
    constructor(){
        super();
    }
}
export default Foo;
```

But produced baseline reference file is correct!

A minimal repo that reproduce this issue is here  https://github.com/ShuiRuTian/TS_41800

File: tests/baselines/reference/importDeclFromTypeNodeInJsSource.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    }
+}
+exports.default = Foo;
+
+
+//// [b.d.ts]
+export default Foo;
+declare class Foo extends EventEmitter {
+}
+import { EventEmitter } from "events";
```
Comment (orta) [inline tests/baselines/reference/importDeclFromTypeNodeInJsSource.js:40]: I see, so the key point to this test is that this `.d.ts` doesn't turn into `node/events` because it's a special case global 👍🏻

**Review by orta — APPROVED** [review]

**Comment by orta** [comment]
Thanks!

File: tests/baselines/reference/importDeclFromTypeNodeInJsSource.js (hunk 1 above)
Comment (weswigham) [reply tests/baselines/reference/importDeclFromTypeNodeInJsSource.js:40]: This fix seems incorrect and an odd special case. We expect in cases like this one, to use the module name specified by the ambient module declaration, _not_ one from a filepath. Since the module is declared as `declare module "events"` we should only be using `"events"` to refer to it, and should never have looked at a filepath to begin with.

Comment (sheetalkamat) [reply tests/baselines/reference/importDeclFromTypeNodeInJsSource.js:40]: This change needs to be reverted and correctly fixed as @weswigham points out correctly.

Comment (ShuiRuTian) [reply tests/baselines/reference/importDeclFromTypeNodeInJsSource.js:40]: Oh.... Sorry for the misleading...
And, I am a little confused, if there is not any special folder, according to the module resolution https://www.typescriptlang.org/docs/handbook/module-resolution.html. How could file find the correct modules? Did I miss something?

Comment (ShuiRuTian) [reply tests/baselines/reference/importDeclFromTypeNodeInJsSource.js:40]: Auh, I find this https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#-reference-ing-a-module
So, I guess the expected code is not just
```
export default Foo;
declare class Foo extends EventEmitter {
}
import { EventEmitter } from "events";
```

but
```
/// <reference types="node" />
export default Foo;
declare class Foo extends EventEmitter {
}
import { EventEmitter } from "events";
```
Right?

Comment (ShuiRuTian) [reply tests/baselines/reference/importDeclFromTypeNodeInJsSource.js:40]: https://github.com/microsoft/TypeScript/pull/41895 this one!
