### PR TITLE
Fix union type partial signature matching

### LINKED ISSUE #5401: Incorrect partial union signature matching
```
function g1(b?: string, ...a: string[]) { }
function g2(a?: string, b?: string) { }

var s: typeof g1 | typeof g2;

s("a", "b", "c") // should be an error: 0..2 parameters are allowed
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #5401.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@sandersn This is the best way to fix the issue. We were a bit too permissive in partial signature matches involving rest parameters.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5603,18 +5603,29 @@ namespace ts {
...
             }
-            if (source.parameters.length !== target.parameters.length ||
-                source.minArgumentCount !== target.minArgumentCount ||
-                source.hasRestParameter !== target.hasRestParameter) {
-                if (!partialMatch ||
-                    source.parameters.length < target.parameters.length && !source.hasRestParameter ||
-                    source.minArgumentCount > target.minArgumentCount) {
-                    return Ternary.False;
-                }
+            if (!(isMatchingSignature(source, target) || partialMatch && isPartiallyMatchingSignature(source, target))) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: Why does a partial match return Ternary.False when partialMatch === true?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5603,18 +5603,29 @@ namespace ts {
             return compareTypes(getTypeOfSymbol(sourceProp), getTypeOfSymbol(targetProp));
         }
 
+        // A source signature matches a target signature if the two signatures have the same number of required,
+        // optional, and rest parameters.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Just use JSDoc

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I don't believe that's what actually happens. If both sides of the `||` are `Ternary.False`, you'll return `Ternary.False`

Comment (sandersn) [inline src/compiler/checker.ts]: Ah, I didn't see the parentheses surrounding the whole thing. I thought it was `!isMatchingSignature(...) ||`. Now it makes sense.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -5603,18 +5603,29 @@ namespace ts {
...
+        function isMatchingSignature(source: Signature, target: Signature) {
+            return source.parameters.length === target.parameters.length &&
+                source.minArgumentCount === target.minArgumentCount &&
+                source.hasRestParameter === target.hasRestParameter;
+        }
+
+        // A source signature partially matches a target signature if the target signature has no fewer required
+        // parameters and no more overall parameters than the source signature (where a signature with a rest
+        // parameter is always considered to have more overall parameters than one without).
+        function isPartiallyMatchingSignature(source: Signature, target: Signature) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Since it's already ambiguous what "partially" means, why don't you make `partial` a parameter of `isMatchingSignature`

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -5603,18 +5603,29 @@ namespace ts {
             return compareTypes(getTypeOfSymbol(sourceProp), getTypeOfSymbol(targetProp));
         }
 
+        // A source signature matches a target signature if the two signatures have the same number of required,
+        // optional, and rest parameters.
+        function isMatchingSignature(source: Signature, target: Signature) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Since this only considers the argument list length and restiness\*, this should be something like `hasMatchingArity`

\* *unrelated to RESTfulness*

**Comment by sandersn** [comment]
:+1: with the comment that I like Daniel's name change idea.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: That wouldn't make sense. I broke it into two separate tests, one that is always performed (`isMatchingSignature`) and one that is *additionally* performed when we do partial matching (`isPartiallyMatchingSignature`).

File: src/compiler/checker.ts (hunk 4 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Not sure "arity" conveys it either. It's about more than the number of parameters. I'm inclined to leave it as is unless there's a better suggestion.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `hasCompatibleMinimumArity`? In any case, `isMatchingSignature` implies you're checking whether the signatures are entirely compatible (including type compatibility).

File: src/compiler/checker.ts (hunk 3 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I don't exactly see why it doesn't make sense. You'd return `true` if ordinary matched-ness worked, and then if `allowPartialMatches` was given in, you'd just perform the extra check. Otherwise you'd return false.
