### PR TITLE
fix(46589): Extra ? added to method in method signature completion for optional method

### LINKED ISSUE #46589: Extra `?` added to method in method signature completion for optional method
# Bug Report

### 🔎 Search Terms
- Method signature completions
- suggest / suggestions
- completions

### 🕗 Version & Regression Information
4.5.0-dev.20211029

### 💻 Code

For the code:

```ts
interface IFoo {
    barOpt?(x: number): void;
}

class Foo implements IFoo {
    |
 }
```

Complete `barOpt` inside `Foo`

### 🙁 Actual behavior

`barOpt ` gets added with a `?`

```ts
interface IFoo {
    barOpt?(x: number): void;
}

class Foo implements IFoo {
    barOpt?(x: number): void {
        
    }
}
```

### 🙂 Expected behavior

Since we have implemented the method, I'd expect us the remove the `?`

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #46589

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
🌟 Thanks!

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -63,7 +63,6 @@ namespace ts.codefix {
         const visibilityModifier = createVisibilityModifier(getEffectiveModifierFlags(declaration));
         const modifiers = visibilityModifier ? factory.createNodeArray([visibilityModifier]) : undefined;
         const type = checker.getWidenedType(checker.getTypeOfSymbolAtLocation(symbol, enclosingDeclaration));
-        const optional = !!(symbol.flags & SymbolFlags.Optional);
```
Comment (gabritto) [inline src/services/codefixes/helpers.ts:66]: I think we still need this, since if the new member is a property declaration, we need to preserve optionality.
I think we can either check if we should preserve optionality here, or have this function take a `preserveOptional` parameter or something like that.

**Review by gabritto — CHANGES_REQUESTED** [review]
We shouldn't get rid of `optional` altogether in the codefix helper function, I think that is why there are tests failing on CI. Left a comment with possible solutions.

File: src/services/codefixes/helpers.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/codefixes/helpers.ts:66]: Oke, thanks

File: src/services/completions.ts [hunk 2]
```diff
@@ -912,6 +912,7 @@ namespace ts.Completions {
                 completionNodes.push(node);
             },
             body,
+            /*preserveOptional*/ false,
```
Comment (gabritto) [inline src/services/completions.ts:915]: I think we want this to be true if we are offering a property, and false if we are offering methods. My reasoning is that when we offer a property declaration in completions, we don't also offer an initialization for the property. So all properties added via completions will be uninitialized, and so it makes more sense for them to be optional if the original property was also declared optional. This also minimizes the number of errors that could be introduced by a property declaration.

**Review by gabritto — CHANGES_REQUESTED** [review]
I think this is closer to being what we want, just left a comment for one case left to consider. Thanks :)

File: src/services/codefixes/helpers.ts [hunk 3]
```diff
@@ -37,6 +37,12 @@ namespace ts.codefix {
 
     type AddNode = PropertyDeclaration | GetAccessorDeclaration | SetAccessorDeclaration | MethodDeclaration | FunctionExpression | ArrowFunction;
 
+    export const enum PreserveOptionalFlags {
+        Method  = 1 << 0,
+        Propery = 1 << 1,
```
Comment (gabritto) [inline src/services/codefixes/helpers.ts:42]: typo: this should be `Property`

**Review by gabritto — APPROVED** [review]
Left a comment for a typo, but I think other than that we're good to go now. Thanks! ✨

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5
