### PR TITLE
Avoid rewriting homomorphic mapped types with homomorphic instantiations

### LINKED ISSUE #53109: [Bug] Required in `[K in keyof Required<T>]` differ when using arrow function and normal function
# Bug Report

### 🔎 Search Terms

- required
- arrow

### 🕗 Version & Regression Information

In typecript generated type (d.ts) they is an error while using `Required` in `[K in keyof Required<T>]` in a arrow function definition

- This changed between versions 4.6.4 and newer version of typescript

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0&ts=4.6.4#code/KYDwDg9gTgLgBAYwgOwM7xsdAmOBeOAHgBV84AlYJKAE0PSgEtkBzAGjmWADdgoA+fgApUCABbAAtgEMAXHADeAKDiq4AbQDScZnADWwAJ4QAZhWABHAK6MowOsX4BdecS1OA3EoC+ASnz8iipqSGgQADbAAHThECwi4lLSvl7eSkqgkLBwJlbICDCMKHCY6ACMJGSU1HQMzOycPHyCCRIy8spqGtq6BsZmlNa29iTOru6p-p0hKKgR0bHxom3JqR5AA

### 💻 Code

```ts
export const test2 = <T = Record<string, never>>(schema: {
    [K in keyof Required<T>]: T[K];
}) => {
    console.log(schema);
}

export function test1<T = Record<string, never>>(schema: {
    [K in keyof Required<T>]: T[K];
}) {
    console.log(schema);
};
```

### 🙁 Actual behavior

In typescript 4.6.4 the d.ts file look like this:

```ts
export declare const test2: <T = Record<string, never>>(schema: { [K in keyof Required<T>]: T[K]; }) => void;
export declare function test1<T = Record<string, never>>(schema: {
    [K in keyof Required<T>]: T[K];
}): void;
```
And starting from 4.7 the d.ts file look like this:

```ts
export declare const test2: <T = Record<string, never>>(schema: Required<T> extends infer T_1 ? { [K in keyof T_1]: T[K]; } : never) => void;
export declare function test1<T = Record<string, never>>(schema: {
    [K in keyof Required<T>]: T[K];
}): void;
```

### 🙂 Expected behavior

This should be compiled to the same output as the 4.6 version

### PR DESCRIPTION
**Pull request by Andarist**
fixes #53109

I'm not 100% sure of this change but I can't find why a non-aliased mapped type would have to be rewritten. The PR that introduced this rewriting also mentions explicitly that it's about "inlined mapped types" ([PR here](https://github.com/microsoft/TypeScript/pull/48091)) so I think that the ones that are already inline can be just left as-is.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6616,7 +6616,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
 
             function isHomomorphicMappedTypeWithNonHomomorphicInstantiation(type: MappedType) {
                 return isMappedTypeWithKeyofConstraintDeclaration(type)
-                    && !(getModifiersTypeFromMappedType(type).flags & TypeFlags.TypeParameter);
+                    && !(getModifiersTypeFromMappedType(type).flags & TypeFlags.TypeParameter)
+                    && !!type.aliasSymbol;
```
Comment (weswigham) [inline src/compiler/checker.ts:6620]: This shouldn't have anything to do with the alias symbol as by the time we're trying to print with this function, the alias symbol has already been discarded as an option for printing the mapped type. Instead, what we care about is if the type will be picked up as a homomorphic type variable (or not). Type parameters always are, so were a conservative initial choice - it's generally safe to wrap anything else which is still recognized as a homomorphic type variable up and present it as a type parameter, too - all you get is unnecessarily verbose printback sometimes. Instead of checking the alias symbol here (which seems pretty unrelated), you want to check, rather than if the modifiers type is still a type parameter, if an index on the modifiers type still produces a homomorphic type variable. In this case, an index of a mapped type just returns the inner mapped type's constraint type, which can then be unwrapped, so it is recognized as homomorphic. So, instead of the simple, conservative `!(getModifiersTypeFromMappedType(type).flags & TypeFlags.TypeParameter)` check, you want something to more closely mirror `getHomomorphicTypeVariable`'s conditions like
```ts
                let index: Type;
                return isMappedTypeWithKeyofConstraintDeclaration(type)
                    && (index = getIndexType(getModifiersTypeFromMappedType(type)), !(index.flags & TypeFlags.Index && (index as IndexType).type.flags & TypeFlags.TypeParameter)))
```

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (Andarist) [reply src/compiler/checker.ts:6620]: I applied the suggested change but it reverted the change to the emit of this thing ([TS playground](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230315#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbAeQFsBLGAHgBUAaOAaTlBmADsEBnOAa2FwgBmcKgD44AXjgAFUsm7U6AURBoArkgq9+Q2gxEiA3AChQkWIhQYsOfNimYYpdKilQIBWKWAcFDJiBZ2Li1BYTFJe09nChk5X3p9OAAyOBJyeMMTcGh4AVVWZEcIVkQIAGUIYmAYAAtSVgBzAH0AQULVaKp-QM44AG8jOCG4MDcwAC44DhgoeobjAF8RAAp0SaoASn7B4eRi6bgQSb64AG0pOHqePlDIx2dXd2BPb18AIlH3N5EAXUm7pwuMbPRyvXQfMbfc4-AxwBYSOCsVSoVBwdBcdCsXDGYZwLAwVRQEogRZAA)):
```ts
export declare type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
export declare type PartialProperties<T, K extends keyof T> = Partial<Pick<T, K>> & Omit<T, K>;
export function doSomething_Actual<T extends {
    prop: string;
}>(a: T) {
    const x: { [P in keyof PartialProperties<T, "prop">]: PartialProperties<T, "prop">[P]; } = null as any;
    return x;
}
```

Does this one have to be rewritten? 🤔

Comment (weswigham) [reply src/compiler/checker.ts:6620]: Probably not, since, in that case, I don't think `PartialProperties` is homomorphic, so the wrapping mapped type shouldn't be either. Right now we're using `isMappedTypeWithKeyofConstraintDeclaration` as a proxy for was-this-declared-as-homomorphic - we probably need to swap that out for something a bit more accurate, too. Potentially the same check we're doing on `type` but on `type.target` (and negated)?

Comment (weswigham) [reply src/compiler/checker.ts:6620]: Indeed, it's not actually homomorphic - 
```ts
doSomething_Actual<{prop: string, propb: string} | {prop: string, propa: string}>(null as any);
```
ends up with type 
```ts
{
    prop?: string | undefined;
}
```
so we just need to tighten up that side of the check, too.

Comment (Andarist) [reply src/compiler/checker.ts]: This particular mapped type doesn't have a `.target` property - I might have misunderstood your recommendation for the proposed changes but for now, I've chosen to just avoid rewriting in case of `!type.target`. I think this is correct (it yields the expected result for this case and the rest of the test suite) but maybe I'm missing some further details.

Comment (weswigham) [reply src/compiler/checker.ts]: Actually, that's perfect - if the mapped type doesn't have a `.target`, then leaving it as-is is always correct - it's still it's declared form, uninstantiated.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6625,8 +6625,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             }
 
             function isHomomorphicMappedTypeWithNonHomomorphicInstantiation(type: MappedType) {
-                return isMappedTypeWithKeyofConstraintDeclaration(type)
-                    && !(getModifiersTypeFromMappedType(type).flags & TypeFlags.TypeParameter);
+                if (!type.target || !isMappedTypeWithKeyofConstraintDeclaration(type)) {
+                    return false;
+                }
+                const index = getIndexType(getModifiersTypeFromMappedType(type));
+                return !(index.flags & TypeFlags.Index && (index as IndexType).type.flags & TypeFlags.TypeParameter);
```
Comment (weswigham) [inline src/compiler/checker.ts:6632]: So I was thinking something like
```ts
function isMappedTypeHomomorphic(type: MappedType) {
    return !!getHomomorphicTypeVariable(type);
}

function isHomomorphicMappedTypeWithNonHomomorphicInstantiation(type: MappedType) {
    return !type.target ? false : isMappedTypeHomomorphic(type.target) && !isMappedTypeHomomorphic(type);
}
```

Looks easier to reason about a bit, too, by replacing the complex check I proposed before with a direct `getHomomorphicTypeVariable` call on the type and its' target.

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (Andarist) [reply src/compiler/checker.ts]: nice, this is definitely is easier to reason about 👍 pushed out the suggested change

**Review by weswigham — APPROVED** [review]
let's just double check the tests...

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this
