### PR TITLE
Widen reverse mapped type properties to fix them being treated as EPC-valid sources

### LINKED ISSUE #62720: Conditional type inference fails when generic parameter has Readonly<T> in function parameter position
### 🔎 Search Terms

Readonly generic parameter conditional type inference conditional type matching with Readonly parameter generic constraint Readonly intersection type mapped type readonly conditional inference failure Readonly parameter affects return type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types,
  generic inference, mapped types, and readonly

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/PTAEF5K7NBlApgFwK4AdQGMD2ATBEMRRAUEgJ5oEAqlCAYigHaZICW2TAPAErIoAnJrSoRQzANZNsAdyYA+MQAoAdGoCGAgOYBnAFyh1TcgG0AugEoIivqiEiEAbjJ1Q9ADbrdYgN4lQAaAmAGaeWgBy6gC2CAY6SAJsTFpmBn6BGaAUVAYOjCzsnM6ZgfjB6ijuSAD8BpLScsWBAL7OrS6ieWFccJgAFghR6jqgCAAeSAhMuCMeXjqK4KDpgSFhoEmgEgjk2MHw-YPDqQcDQzprXmajE1Mzy1l0uXT5rBzcScEIAqDU8o6gZr+Eqgaq-YElAxMBAAN2+JHaJBAhGIUFAAHVsAIJCMZGwkH1sCgkOIdEktKA+OpcJx3OQuItUUySCR8JhPAICMFmG9OKBgkxMdjyVwAPJoQpMEbjSbTWZhBZKCGgbAS976UDiyU6EgWZ5UOZaMVqzgLZw4KUkzk6SpIIUScliAX28lKFYBABG2Gw7gQRkNaUeOVAACFvb6jICADTKr0+v1MQ0AEQQ5VtaWVGWysVD4YTMZBoDKFSqBnK7h0CALLRjzQszmttpdyRUcYjibCSLAhcCAD1qiRG1Vm1pW3n-WEU2mql2e32ByzZ0y0SGUBSZAMmKTHVSaUw6QyUcuYCy2RyuTzJfymKujVr1TdZfdDYrlartQZd7T6ffTfJdfqDDdL+Ur-CQFrxKAQ5ILeTo3mubqxuOHZeIG2YGGG8aRs01aeshyapiWSAZoW6G5lhTC4Zkxbpvy6gVlWyo4Qi9aDggNpVLeY4UYas5zqA-ZsRxMFrtx7YEdOSB8XOglAA

### 💻 Code

```ts
// ============ Setup code ==================
type TypeFunction<ReturnType = unknown> = (...args: any[]) => ReturnType;
type Flags = {
    [flagName: string]: {
        type: TypeFunction;
        default?: unknown;
    };
};
type TypeFlag<Schemas extends Flags> = {
    [flag in keyof Schemas]: Schemas[flag] extends { type: TypeFunction<infer T>; }
        ? T
        : never
};

// ============ Works without using Readonly<> ==================

declare function fnWorking<Options extends Flags>(
    options: Options
): TypeFlag<Options>;
const resultWorking = fnWorking({
    booleanFlag: { type: Boolean },
    booleanFlagDefault: {
        type: Boolean,
        default: false,
    },
});
resultWorking.booleanFlag
//            ^? (property) booleanFlag: boolean
resultWorking.booleanFlagDefault
//            ^? (property) booleanFlagDefault: boolean



// ============ Bug when using Readonly<> ==================

declare function fnBug<Options extends Flags>(
    options: Readonly<Options>
): TypeFlag<Options>;
const resultBug = fnBug({
    booleanFlag: { type: Boolean },
    booleanFlagDefault: {
        type: Boolean,
        default: false,
    },
});
resultBug.booleanFlag
//            ^? (property) booleanFlag: boolean
resultBug.booleanFlagDefault
//            ^? (property) booleanFlagDefault: never

```

### 🙁 Actual behavior

When a generic function has `Readonly<T>` in the parameter position, conditional type matching in the return type fails even though `T` itself is not `readonly`:

```ts
declare function fnBug<Options extends Flags>(
    options: Readonly<Options>
): TypeFlag<Options>; // Options is NOT readonly here

type Test = typeof resultBug. booleanFlagDefault; // Returns `never` (incorrect)
```

The conditional type `Schemas[flag] extends { type: TypeFunction<infer T> }` fails to match and falls through to the `never` branch.

This happens even though:
1. `Options` itself is not `Readonly` in the return type `TypeFlag<Options>`
2. The inferred type from the argument has the correct structure
3. The same pattern works perfectly without `Readonly<Options>` in the parameter

### 🙂 Expected behavior

The conditional type should match successfully regardless of whether the parameter is `Readonly<Options>` or `Options`, since the return type `TypeFlag<Options>` uses `Options` directly (not `Readonly<Options>`).

Expected result:
```ts
type Test = typeof resultBug. booleanFlagDefault; // Should be `boolean`
```

The `Readonly` modifier in the parameter position should not affect type inference in the return type when the generic parameter `Options` itself is not `readonly`.

#### Structural typing inconsistency
The types are structurally compatible:
`{ type: BooleanConstructor; default: false }` should match `{ type: TypeFunction<infer T> }`

but TypeScript's conditional type matching fails when `Readonly<Options>` appears in the parameter.

#### Workaround exists
Adding an intersection to the conditional pattern fixes the issue, proving this is a pattern-matching bug rather than a semantic issue:
```ts
Schemas[flag] extends ({ type: TypeFunction<infer T> } & Record<PropertyKey, unknown>)
```

This workaround doesn't change the logical meaning but helps TypeScript's matcher recognize the types as compatible.

[TS Playground](https://www.typescriptlang.org/play/?#code/PTAEF5K7NBlApgFwK4AdQGMD2ATBEMRRAUEgJ5oEAqlCAYigHaZICW2TAPAErIoAnJrSoRQzANZNsAdyYA+MQAoAdGoCGAgOYBnAFyh1TcgG0AugEoIivqiEiEAbjJ1Q9ADbrdYgN4lQAaAmAGaeWgBy6gC2CAY6SAJsTFpmBn6BGaAUVAYOjCzsnM6ZgfjB6ijuSAD8BpLScsWBAL7OrS6ieWFccJgAFghR6jqgCAAeSAhMuCMeXjqK4KDpgSFhoEmgEgjk2MHw-YPDqQcDQzprXmajE1MzoEo+WXS5dPmsHNxJwQgCoNTyRygZqgABkoD4OAEuC4AAUBNgqAIKABpHYAGnETCksgUFn8JVA1X+BJKBiYCAAbr8SO0SCBCMQoKAAOrYAQSEYyNhIPrYFBIcQ6JJaCEIdS4TjuchcRZM+UkEj4TCeAQEYLMD6cUDBJhsjkirgAeTQhSYI3Gk2mszCCyUpNAiLN+lAJudJAsryocy0xtNnwWzhw5sFap0lSQ+okIrEuqjIseDoARthsO5xUwfWlnjlQAAhVPpozA9HJwsZn0AEQQ5QjaQdGWysXz5aMpcJoDKFSqBnK7h0CHbLVLzQszjDEfjyRUKbTFbC9LAHcCAD1qiQJ1Up1oZ63M2Fq7Wqovl6v14qT-LmXmUKKZAMmEKY3wJVKZXKr6QlQgVZp1ZqzR1Jgb19N0AxuK17h9O0HSdAMDBfSUmGlP1nXkD0vQYbowM4QMSGDeJQE3JAQNjYDb0TDJZyLfcvGzJsDALOdi2aIcAmo+cvEPbskHrDsGJbZimDYzIuzrHV1H7QcHVY2kxw3BBwyqEDdyEn0T1PUA1wUpSSNvVSaKrGseI009tKAA)

#### Real world Impact
This bug affects any library that wants to accept readonly parameters while using conditional type inference, forcing authors to use syntactic workarounds that pollute the type definitions.

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/62720

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -26431,7 +26431,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         const templateType = getTemplateTypeFromMappedType(target);
         const inference = createInferenceInfo(typeParameter);
         inferTypes([inference], sourceType, templateType);
-        return getTypeFromInference(inference) || unknownType;
+        return getWidenedType(getTypeFromInference(inference) || unknownType);
```
Comment (Andarist) [inline src/compiler/checker.ts:26439]: note for reviewers: this is what `getCovariantInference` already does

**Review by jakebailey — APPROVED** [review]
