### PR TITLE
Control flow based type analysis

### LINKED ISSUE #2388: Use control flow analysis for type guards
**TS 1.4**

Type guard fails to narrow the union type when returning early.

```ts
function foo(x: number | string) {
	if (typeof x === 'string') {
		return;
	}
	// x should now be a number
	if (2 % x !== 0) {
		// do something
	}
}
```

Unfortunately, I get the following compiler error:
> The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

Clearly, the compiler should know at this point that it can't possibly be dealing with a `string`, as that scenario has already been returned.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR introduces *control flow based type analysis* for local variables and parameters as initially suggested in #2388 and prototyped in #6959. Previously, the type analysis performed for type guards was limited to `if` statements and `?:` conditional expressions and didn't include effects of assignments and control flow constructs such as `return` and `break` statements. With this PR, the type checker analyses all possible flows of control in statements and expressions to produce the most specific type possible (the *narrowed type*) at any given location for a local variable or parameter that is declared to have a union type.

Some examples:

```typescript
function foo(x: string | number | boolean) {
    if (typeof x === "string") {
        x; // type of x is string here
        x = 1;
        x; // type of x is number here
    }
    x; // type of x is number | boolean here
}

function bar(x: string | number) {
    if (typeof x === "number") {
        return;
    }
    x; // type of x is string here
}
```

Control flow based type analysis is particuarly relevant in `--strictNullChecks` mode because nullable types are represented using union types:

```typescript
function test(x: string | null) {
    if (x === null) {
        return;
    }
    x; // type of x is string in remainder of function
}
```

Furthermore, in `--strictNullChecks` mode, control flow based type analysis includes *definite assignment analysis* for local variables of types that don't permit the value `undefined`.

```typescript
function mumble(check: boolean) {
    let x: number; // Type doesn't permit undefined
    x; // Error, x is undefined
    if (check) {
        x = 1;
        x; // Ok
    }
    x; // Error, x is possibly undefined
    x = 2;
    x; // Ok
}
```

The narrowed type of a local variable or parameter at a given source code location is computed by starting with the initial type of the variable and then following each possible code path that leads to the given location, narrowing the type of the variable as appropriate based on type guards and assignments.

* The initial type of local variable is `undefined`.
* The initial type of a parameter is the declared type of the parameter.
* The initial type of an outer local variable or a global variable is the declared type of that variable.
* A type guard narrows the type of a variable in the code path that follows the type guard.
* An assignment (including an initializer in a declaration) of a value of type S to a variable of type T changes the type of that variable to T *narrowed by* S in the code path that follows the assignment.
* When multiple code paths lead to a particular location, the narrowed type of a given variable at that location is the union type of the narrowed types of the variable in those code paths.

The type T *narrowed by* S is computed as follows:

* If T is not a union type, the result is T.
* If T is a union type, the result is the union of each constituent type in T to which S is assignable.

Thanks to @ivogabe for providing inspiration and tests for this PR.

Fixes #2388.

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -567,174 +570,501 @@ namespace ts {
...
-            bind(n.expression);
-
-            currentReachabilityState = preWhileState;
-            const postWhileLabel = pushImplicitLabel();
-            bind(n.statement);
-            popImplicitLabel(postWhileLabel, postWhileState);
+        function isNarrowableReference(expr: Expression): boolean {
+            return expr.kind === SyntaxKind.Identifier ||
+                expr.kind === SyntaxKind.ThisKeyword ||
+                expr.kind === SyntaxKind.PropertyAccessExpression && isNarrowableReference((<PropertyAccessExpression>expr).expression);
```
Comment (weswigham) [inline src/compiler/binder.ts]: Should `ElementAccessExpression`s be considered narrowable if their expression is narrowable, just like `PropertyAccessExpression`s?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -7365,16 +7277,237 @@ namespace ts {
...
+
+        function getFlowTypeCache(flow: FlowNode): Map<Type> {
+            if (!flow.id) {
+                flow.id = nextFlowId;
+                nextFlowId++;
+            }
+            return flowTypeCaches[flow.id] || (flowTypeCaches[flow.id] = {});
+        }
+
+        function isNarrowableReference(expr: Node): boolean {
```
Comment (weswigham) [inline src/compiler/checker.ts]: This function is duplicated both here and in the binder. Should it be shared?

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -1504,7 +1529,7 @@ namespace ts {
     }
 
     // True if the given identifier, string literal, or number literal is the name of a declaration node
-    export function isDeclarationName(name: Node): name is Identifier | StringLiteral | LiteralExpression {
+    export function isDeclarationName(name: Node): boolean {
```
Comment (weswigham) [inline src/compiler/utilities.ts]: Why was the type-guardiness of this function removed?

File: src/compiler/parser.ts [hunk 4]
```diff
@@ -1811,7 +1811,7 @@ namespace ts {
         function parseEntityName(allowReservedWords: boolean, diagnosticMessage?: DiagnosticMessage): EntityName {
             let entity: EntityName = parseIdentifier(diagnosticMessage);
             while (parseOptional(SyntaxKind.DotToken)) {
-                const node = <QualifiedName>createNode(SyntaxKind.QualifiedName, entity.pos);
+                const node: QualifiedName = <QualifiedName>createNode(SyntaxKind.QualifiedName, entity.pos);  // !!!
```
Comment (weswigham) [inline src/compiler/parser.ts]: What's the new type annotation and `// !!!` comment for?

File: src/compiler/parser.ts [hunk 5]
```diff
@@ -3643,7 +3643,7 @@ namespace ts {
             let elementName: EntityName = parseIdentifierName();
             while (parseOptional(SyntaxKind.DotToken)) {
                 scanJsxIdentifier();
-                const node = <QualifiedName>createNode(SyntaxKind.QualifiedName, elementName.pos);
+                const node: QualifiedName = <QualifiedName>createNode(SyntaxKind.QualifiedName, elementName.pos);  // !!!
```
Comment (weswigham) [inline src/compiler/parser.ts]: Same comment as above:
> What's the new type annotation and `// !!!` comment for?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -16326,7 +16328,7 @@ namespace ts {
             }
 
             if (entityName.parent.kind === SyntaxKind.ExportAssignment) {
-                return resolveEntityName(<Identifier>entityName,
+                return resolveEntityName(<Identifier><EntityName>entityName,
```
Comment (weswigham) [inline src/compiler/checker.ts]: This new cast seems unneeded.

**Comment by jods4** [comment]
> If T is not a union type, the result is T.

Would it be interesting to consider sub-classes narrowing? Just thinking out loud, not sure if it has value:
```typescript
class Human { };

class Wizard extends Human {
  void castSpell();
};

let x: Human;
x = new Wizard();
x.castSpell(); // <- statically ok?
```

I guess I'll be the one to start the heated discussion, please don't hate me:
> Furthermore, in `--strictNullChecks` mode, control flow based type analysis includes definite assignment analysis for local variables of types that don't permit the value `undefined`.

Should you do the same check for a variable that permit the value `undefined`? I am personnally OK with the answer "no", but some people want to use `undefined` as their "empty" value, maybe even promote some sugar for it (either `var x?: number` or `var x: number?`). Under those assumptions, I would find the following code suspicious in a strongly-typed language:
```typescript
let x?: number;
// lots of fancy logic with a single unassigned code path
return x; // did we intend x to be undefined here, or did we forget one code path?
```
I won't be championing that as I'm using `null` for my empty values anyway. But to be fair with the `undefined` fans I think it has to be asked.

**Comment by RyanCavanaugh** [comment]
@jods4 we were discussing the exact `Human` / `Wizard` scenario earlier and have some theories about what might work.

The problem with directly narrowing is cases like this:
```ts
interface Options {
  name: string;
  length?: number;
  width?: number;
}
let x: Options = { name: 'a' }; // 1
x = { name: 'other', length: 10 }; // 2
x.width = 32; // 3
```
On line 2, we can't blindly take the RHS type and overwrite the declared type of x, because it'd break line 3.

It hasn't been implemented yet, but using intersection may solve this problem (in your example, we'd assign the type `Human & Wizard` to `x` and allow the method call).

One open question from that discussion was whether or not this code ought to be an error:
```ts
let x: { a?: string; b?: number };
let y: { a: string; } = { a: 'foo' };
x = y;
x.b = 30;
```

File: src/compiler/parser.ts (hunk 4 above)
Comment (ivogabe) [inline src/compiler/parser.ts]: Since `Entity` is a type alias of a union, it will be narrowed after its assignment. This creates a circular dependency during the type analysis. Because of this, `node` would be typed as `any` if the type annotation was not given.

@ahejlsberg Would it be possible to give the inference of the type of the initializer precedence over the narrowing after assignments?

File: src/compiler/utilities.ts (hunk 3 above)
Comment (ivogabe) [inline src/compiler/utilities.ts]: Probably because this function can also return `true` if the node is some identifier, but not used as a declaration. With the control flow checks, the code after an `if` with a return will be considered to be the else block, which might have caused some issues.

**Comment by ivogabe** [comment]
@jods4 @RyanCavanaugh You can also get issues with generics:
```typescript
let x: Array<string | number>;
x = ["a", "b"];
x.push(42)
```
If `x` would be narrowed to `Array<string>`, the last line would give an error. I think narrowing only union types after an assignment would support most use cases.

**Comment by jods4** [comment]
@RyanCavanaugh Structural typing with optional members is indeed more complicated: reading is ok, but you may want to assign missing optional parent members!

I think your `&` idea would work fine: the initial variable keeps its declared type, yet is extended with additionnal members that are provably there by definite assignment.

The `Wizard` was "real" inheritance, which seems easy as you can't hide/miss existing members.
`Wizard extends Human` => `Human & Wizard` simplifies to just `Wizard`, right?

I think your `x / y` example ought to work. `x` was declared as having an optional member `b`, so you should be allowed to assign `x.b` no matter what the underlying object is.
If there should be an error then it would be the assignment `x = y`, but under current TS structural typing rules it's fine. I think the saying `y` has the shape `{ a: string }` doesn't exclude the fact that it may have other members, or prevent it from gaining new members in other ways than manipulating `y`... Types in TS are not closed.
Applying `&` logic in this case would yield this result.

**Note that your code is unsafe for another reason, though:**
```typescript
let x: { a?: string; b?: number };
let y: { a: string; } = { a: 'foo' };
x = y;
x.a = undefined;
y.a.length; // oops!
```
On what line is this an error?

@ivogabe This is a different case... `Array<string>` is not a subclass of `Array<string | number>` (which was my initial suggestion). And if we apply @RyanCavanaugh's extended logic to all types, then we get `x: Array<string> & Array<string | number>` which would work just fine in your example?

**Comment by ivogabe** [comment]
@ahejlsberg In my branch, I only tried to figure out the type of an assignment if the variable was of a union type. In this branch, you always try to get the type, and then only narrow if the variable is a union type. For non-union variables, I only check whether it was assigned, not what. That might prevent some issues, for instance issues similar to the one with the `// !!!` comment. And it might improve the performance of the language service a bit.

@jods4 @RyanCavanaugh Sorry, I thought you were talking about subtypes instead of subclasses. Though in a structural type system, subclasses do not really exist, strictly spoken. I think that intersection types would be a better way to model this, but they can still have issues with generics:
```typescript
function sum(xs: number[]) { return xs.reduce(...) }
let x: Array<string | number>;
x = [1, 4];
// x: Array<number> & Array<string | number>
x.push("");
sum(x);
```
This would compile with the proposed behavior. Also error messages would be uglier with this change. I think this would be something to consider after this PR.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (weswigham) [inline src/compiler/utilities.ts]: If that was the case, then wouldn't the name of the function be misleading?

**Comment by ivogabe** [comment]
@ahejlsberg Would the following code show an error that `x` might not be assigned (eg, might be `null`)?
```typescript
let x: string;
x = "";
for (;;) {
    x = x;
    x.substring; // <-- here
}
```
I'm asking this because of the loop, which causes the narrowing after the assignment to fail (due to recursion). Though I think that that should not break assignment checking, as an assigned value should not be `null`.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (ivogabe) [inline src/compiler/utilities.ts]: Not in my opinion, it checks whether a node is a declaration name, but not every identifier is a declaration name. So the type annotation was wrong, not the name.

Comment (weswigham) [inline src/compiler/utilities.ts]: Seems fair.

File: src/compiler/binder.ts (hunk 1 above)
Comment (ivogabe) [inline src/compiler/binder.ts]: That could be done, but only if the expression between the brackets is a constant (string/number literal, enum value etc)

**Comment by jods4** [comment]
@ivogabe Your example is already broken in TS today, because we have array covariance like in C# and Java... Without any narrowing:
```typescript
var x: (string | number)[];
var y = [0, 1];
x = y;
x.push("two");
y[2].toPrecision(3); // runtime fail: y[2] is not a number
```

And the same happens with nullables, because reading is covariant and writing contra-variant but the language just goes for co- all the time, copied from my comment above:
```typescript
let x: { a?: string; b?: number };
let y: { a: string; } = { a: 'foo' };
x = y;
x.a = undefined;
y.a.length; // oops!
```

The `&` idea just extends how the language already works. Not saying we _must_ have it, I was just submitting some random thoughts about the narrowing description by @ahejlsberg.

File: src/compiler/binder.ts (hunk 1 above)
Comment (weswigham) [inline src/compiler/binder.ts]: I think we do that kind of special-casing for literal element access expressions elsewhere - we should probably do it here, as well.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (ahejlsberg) [inline src/compiler/utilities.ts]: Yes, @ivogabe is exactly right about why I removed the type predicate annotation.

File: src/compiler/parser.ts (hunk 4 above)
Comment (ahejlsberg) [inline src/compiler/parser.ts]: The exact problem here is the following: We infer the type of `node` from the call to `createNode`. To evaluate that call we need to know the type of `entity` so we can find the type of the `pos` property. To find the type of `entity` we look at the preceding code paths. One leads from the top of the function. In that code path, `entity` has type `Identifier`, which is less than its full declared type (`Identifier | QualifiedName`). Therefore we need to also analyze the second code path that comes from the bottom of the while statement (the loop around case). In that code path, we have the assignment `entity = finishNode(node)` which requires us to know the type of `node`. Boom! Circularity. Not exactly clear what rule we'd introduce to break that circularity.

File: src/compiler/parser.ts (hunk 5 above)
Comment (ahejlsberg) [inline src/compiler/parser.ts]: Same issue.

File: src/compiler/checker.ts (hunk 6 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Yes, that extra cast was a left over from a work around for the earlier issue with the `isDeclarationName` user defined type guard.

**Comment by ahejlsberg** [comment]
@ivogabe If you look at the code in `checkIdentifier` starting [here](https://github.com/Microsoft/TypeScript/blob/controlFlowTypes/src/compiler/checker.ts#L7898) you'll see that if the initial type of a variable is its declared type, and if the variable is not of a "narrowable" type (i.e. not a union type but for example a primitive type), then I don't compute the narrowed type. This is definitely an important optimization.

There is no error in your example:

```typescript
let x: string;
x = "";
for (;;) {
    x = x;
    x.substring; // Ok
}
```

Since the declared type of `x` is `string` and the narrowed type of `x` is `string` in the first code path into the loop, we never even examine the back branch because there is nothing it could do to further affect the type of `x`. Specifically, when there are multiple code paths leading to a given location, if one of the code paths already yields the declared type (the least specific type the variable could have), then no other code path could affect the result because we're going to union the types together in the end.

File: src/compiler/binder.ts [hunk 7]
```diff
@@ -567,174 +570,501 @@ namespace ts {
...
+                kind: FlowKind.Condition,
+                antecedent,
+                expression,
+                assumeTrue
+            };
+        }
 
-            currentReachabilityState = ifTrueState;
+        function createFlowAssignment(antecedent: FlowNode, node: Expression | VariableDeclaration | BindingElement): FlowNode {
+            return <FlowAssignment>{
```
Comment (DanielRosenwasser) [inline src/compiler/binder.ts]: Could you simply use these types as return types instead of using a type assertion?

File: src/compiler/binder.ts [hunk 8]
```diff
@@ -567,174 +570,501 @@ namespace ts {
...
+                        (<BinaryExpression>node).operatorToken.kind === SyntaxKind.BarBarToken);
+                }
             }
         }
 
-        function bindReturnOrThrow(n: ReturnStatement | ThrowStatement): void {
-            // bind expression (don't affect reachability)
-            bind(n.expression);
-            if (n.kind === SyntaxKind.ReturnStatement) {
+        function isTopLevelLogicalExpression(node: Node): boolean {
```
Comment (DanielRosenwasser) [inline src/compiler/binder.ts]: What exactly makes something top-level? I can pretty much figure if out if I dig into this, but can you document the intent?

File: src/compiler/binder.ts (hunk 7 above)
Comment (ahejlsberg) [inline src/compiler/binder.ts]: Yes.

File: src/compiler/binder.ts (hunk 8 above)
Comment (ahejlsberg) [inline src/compiler/binder.ts]: A logical expression (an && or || expression) is top-level if it has no effect on control flow beyond itself. Examples include logical expressions used as statement expressions and logical expressions passed as arguments.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -191,32 +193,82 @@ namespace ts {
...
-            }
+        const enum TypeFacts {
+            None = 0,
+            TypeofEQString = 1 << 0,      // typeof x === "string"
+            TypeofEQNumber = 1 << 1,      // typeof x === "number"
+            TypeofEQBoolean = 1 << 2,     // typeof x === "boolean"
+            TypeofEQSymbol = 1 << 3,      // typeof x === "symbol"
+            TypeofEQObject = 1 << 4,      // typeof x === "object"
+            TypeofEQFunction = 1 << 5,    // typeof x === "function"
+            TypeofEQHostObject =  1 << 6, // typeof x === "xxx"
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Extra space after `=`

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -191,32 +193,82 @@ namespace ts {
...
-            },
-            "symbol": {
-                type: esSymbolType,
-                flags: TypeFlags.ESSymbol
-            },
-            "undefined": {
-                type: undefinedType,
-                flags: TypeFlags.ContainsUndefinedOrNull
-            }
+        const enum TypeFacts {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `TypeFacts` is an odd name for this. Maybe `TypeNarrowFlags`?

Comment (weswigham) [inline src/compiler/checker.ts]: I dunno, `TypeFacts` seems right to me - it's a flag which aggregates the facts (is truthy, is not null, etc) a program has proven about a type at a given location.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Maybe, though, when I think `____Facts`, I either think of [SyntaxFacts](http://source.roslyn.codeplex.com/Microsoft.CodeAnalysis.CSharp/Syntax/SyntaxFacts.cs.html) (which we also used to have) or [this](http://imgur.com/gallery/rsQ93).

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -191,32 +193,82 @@ namespace ts {
...
+            TypeofEQObject = 1 << 4,      // typeof x === "object"
+            TypeofEQFunction = 1 << 5,    // typeof x === "function"
+            TypeofEQHostObject =  1 << 6, // typeof x === "xxx"
+            TypeofNEString = 1 << 7,      // typeof x !== "string"
+            TypeofNENumber = 1 << 8,      // typeof x !== "number"
+            TypeofNEBoolean = 1 << 9,     // typeof x !== "boolean"
+            TypeofNESymbol = 1 << 10,     // typeof x !== "symbol"
+            TypeofNEObject = 1 << 11,     // typeof x !== "object"
+            TypeofNEFunction = 1 << 12,   // typeof x !== "function"
+            TypeofNEHostObject = 1 << 13, // typeof x !== "xxx"
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: What is HostObject?

File: src/compiler/parser.ts (hunk 4 above)
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: Would just assuming the declared type of `entity` be good enough.

Comment (JsonFreeman) [inline src/compiler/parser.ts]: One other idea is that while doing the analysis, if you hit a type assertion, ignore the RHS, and just use the type associated with the type assertion.

File: src/compiler/checker.ts (hunk 11 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Objects defined by the ECMAScript standard are called native objects. Other objects, such as DOM objects, are called host objects. From a TS point of view, anything for which `typeof` returns a value other than `string`, `number`, `boolean`, `symbol`, `object`, or `function` is considered a host object.

File: src/compiler/parser.ts (hunk 4 above)
Comment (ahejlsberg) [inline src/compiler/parser.ts]: @DanielRosenwasser But by exactly what mechanism would we sometimes just use the declared type and other times compute the narrowed type?

@JsonFreeman Yes, but we'd then have to introduce a distinction between *resolving* the type of an expression (in which case we could defer and ignore the RHS) and *checking* the type of an expression. We don't have such a distinction currently.

Comment (weswigham) [inline src/compiler/parser.ts]: @ahejlsberg - this doesn't seem circular to me, it seems sequential. I'm imagining if the first iteration of the loop were unrolled - don't we just need to take the partially resolved type for entity from the first iteration and use it as input for the type of entity for the second iteration? Once you've reached a stable signature (or cycle of signatures) by this method of loop-unrolling, you'd just need the union of all types made in each iteration for the overall type at that location, no?

Comment (ahejlsberg) [inline src/compiler/parser.ts]: @weswigham Yes, but the compiler is by and large constructed with the assumption that once we compute a symbol's *declared* type, that type can and will be cached and never changes. However, to do what you suggest we'd have to compute a new declared type for the `node` symbol in each iteration because `entity` depends on `node`, which depends on `entity`, etc. We're simply not equipped to do that currently.

File: src/compiler/binder.ts [hunk 12]
```diff
@@ -134,6 +129,9 @@ namespace ts {
         let Symbol: { new (flags: SymbolFlags, name: string): Symbol };
         let classifiableNames: Map<string>;
 
+        const unreachableFlow: FlowNode = { kind: FlowKind.Unreachable };
+        const reportedUncreachableFlow: FlowNode = { kind: FlowKind.Unreachable };
```
Comment (sandersn) [inline src/compiler/binder.ts]: typo: reportedUnreachableFlow

**Comment by ivogabe** [comment]
@ahejlsberg Thanks for the explanations. I have played a bit with it and it works pretty good. Though I found two issues. First, the assignment checks report multiple errors for the same issue. In this example, the compiler reports an error that `x` is not assigned and that `substring` does not exist on the empty type. I would say that even though `x` will be `undefined` there, it would be better to type it as the initial type there, since you already got the real error.
```typescript
    let x: string;
    x.substring;
//  ~            Used before assigned
//    ~~~~~~~~~  `substring` does not exist on `{}`
```
In unreachable code, you will get a lot of not-assigned errors:
```typescript
let x = "";
while (true);
x = ""; // Unreachable
x; // Used before assigned
```
I think that you shouldn't get the error there. Also, I think that if the third line would be absent, it should still not give an error that `x` is not assigned since you already have the unreachable code error. Instead, it can fall back to the initial type.

A more serious issue is that the back flow of a loop only works if the condition is a type guard. In the first example, `y` is narrowed to `string`, so `number` is missing. The second example works correctly.
```typescript
let y: string | number | boolean;
y = "";
while (true) {
	y; // string
	y = 1;
}
```
```typescript
let y: string | number | boolean;
y = "";
while (typeof x === "string") {
	y; // string | number
	y = 1;
}
```

File: src/compiler/checker.ts (hunk 11 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Oh yes, like the DOMElements

**Comment by ahejlsberg** [comment]
@ivogabe The problem with the missing back flow is caused by an overly aggressive optimization in the `finishFlow` function in the binder. Good catch. I'll have a fix for it shortly.

File: src/compiler/parser.ts (hunk 4 above)
Comment (JsonFreeman) [inline src/compiler/parser.ts]: I think the problem of circularities isn't new, this is just a new instance of it. We've looked at this in the past with regard to inferring types of symbols that recursively reference themselves. For these cases, I believe we decided that it's sometimes helpful to resolve an expression without fully diving into it. But it was a challenge to formalize and implement. I think this boils down to the same thing.

**Comment by aleksey-bykov** [comment]
might be relevant
https://github.com/Microsoft/TypeScript/issues/4040

File: src/compiler/parser.ts (hunk 4 above)
Comment (weswigham) [inline src/compiler/parser.ts]: Just to make the issue into a concrete, self-contained test, I'll drop this here:
```ts
interface First {first: 'first'}
interface Second {second: 'second'}
interface Third {third: 'third'}

declare function next(obj: Third): undefined;
declare function next(obj: Second): Third;
declare function next(obj: First): Second;

declare function isThird(x: any): x is Third;

var x: First | Second | Third;
x = {first: 'first'};
x.first;
while (true) {
    x = next(x);
    x.second; // Should be forbidden (x is Third in the second iteration), but is allowed
    if (isThird(x)) {
        break;
    }
}

x.third; // Should be allowed (loop always exits when x is Third), but is forbidden
```
Even if we don't _fix_ the issue, the current behavior can be awkward. (`x` ends up typed as `Second` after the loop, which is incorrect.)

Comment (JsonFreeman) [inline src/compiler/parser.ts]: @weswigham good example! I think even if it the system is not always correct, it's better if it is conservative. So in your example, I could envision an acceptable solution where at the two property accesses, `x` is of type `Second | Third`. That way the implementation could get to a point where it is always either correct, or is too conservative because of a reassignment in a loop. And then loops could be fixed up later while people try out the feature.

Comment (weswigham) [inline src/compiler/parser.ts]: @JsonFreeman we can't be too conservative, though - for example, in my example above, if I omitted 
```ts
    if (isThird(x)) {
        break;
    }
```
from the while loop, then `next(x)` could return `undefined` (as `x` could be `Three` at the start of the loop) - which isn't assignable to `x` under strict null mode - which should cause an error within the loop! Making it non-cumbersome to use overloads like this could be difficult without a complete fix for the issue.

Comment (JsonFreeman) [inline src/compiler/parser.ts]: Yes that's a good point. It's not a simple matter of using the declared type. But I think the overloaded `next` function wouldn't even accept a union type as an argument.

Comment (weswigham) [inline src/compiler/parser.ts]: No, it wouldn't with how TS resolves signatures at present - at least not without another signature declaring it as taking a parameter of type `any` or a union of the other types. (Which, for some reason feels off to me - if every member of a union of argument types can be fulfilled by an overload and there's no better match, why can't the return be the union of those overloads' return values? Question for another time.)

Comment (JsonFreeman) [inline src/compiler/parser.ts]: (Answer for another time ;)

**Comment by ahejlsberg** [comment]
@ivogabe Improved the error reporting as you suggested. It does indeed reduce the noise.

File: src/compiler/parser.ts (hunk 4 above)
Comment (ahejlsberg) [inline src/compiler/parser.ts]: @weswigham @JsonFreeman There are actually several issues being debated here:

* Circularities occurring because we're more eager than we need to when *resolving* (as opposed to *checking*) the type of an expression. As Jason points out, that's not a new issue. We could make progress on this issue by making a distinction between *resolving* and *checking* an expression, and only evaluate as much as we need to when resolving. Indeed, we could solve the actual cases in the compiler by doing this for type assertion expressions.

* Inability for symbols to have evolving *declared* types. This one is much harder. I really don't want to go there unless we absolutely have to.

* Compute *narrowed* types by iterating to a fixed point. We only do this in limited form today and, as Wes' example shows, we may need to do more here. I'm not super concerned with crazy examples that walk up a ladder of overloads, but I can indeed imagine real world examples where it occurs without overloading. Although I haven't actually seen any in the wild yet. I will continue to think about this issue.

Comment (JsonFreeman) [inline src/compiler/parser.ts]: Thanks Anders, I think that's a great breakdown. I'll add that (if I'm not mistaken), this separation of resolution and checking *is* in place for bodies of function expressions. The idea here would be to generalize it for other expressions.

I agree that iterating to a fixed point may be necessary for loops in which the variable is reassigned in the loop body.

File: src/compiler/binder.ts (hunk 1 above)
Comment (mhegazy) [inline src/compiler/binder.ts]: literals and well-known symbols as well.

File: src/compiler/binder.ts [hunk 13]
```diff
@@ -570,174 +573,498 @@ namespace ts {
...
-            // - for(..;true;..)
-            const isInfiniteLoop = (!n.condition || n.condition.kind === SyntaxKind.TrueKeyword);
-            const postForState = isInfiniteLoop ? Reachability.Unreachable : preForState;
-            popImplicitLabel(postForLabel, postForState);
+        function isNarrowingBinaryExpression(expr: BinaryExpression) {
+            switch (expr.operatorToken.kind) {
+                case SyntaxKind.EqualsEqualsToken:
+                case SyntaxKind.ExclamationEqualsToken:
+                case SyntaxKind.EqualsEqualsEqualsToken:
+                case SyntaxKind.ExclamationEqualsEqualsToken:
```
Comment (mhegazy) [inline src/compiler/binder.ts]: CommaToken?

File: src/compiler/binder.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/binder.ts]: Yes, it would be good to support element access expressions with string literals and well known symbols. I think we can cover it in a separate PR though.

**Comment by ahejlsberg** [comment]
Latest commit implement what I think is a reasonable compromise for the "evolving types" issue discussed [here](https://github.com/Microsoft/TypeScript/pull/8010#discussion_r59493546). Now, when computing the narrowed type of a variable reference leads to resolving call signatures (for example because the variable is assigned the result of a function call along the control flow path), we don't cache the result of those call signature resolutions. Thus, in the subsequent actual type check of the call, we'll re-check with the further evolved type of the variable. Effectively, this handles evolving types as long as the types settle out after the first iteration. It does not handle cycles or ladders of overloads by exhaustively iterating to a fixed point, but I don't really consider those to be real world scenarios anyway.

Here's an example that is now handled correctly:

```typescript
declare function foo(s: string | number): number;

function f() {
    let x: string | number | boolean;
    x = "";
    while (cond) {
        x; // string | number
        x = foo(x);
        x; // number
    }
    x; // string | number
}
```

Determination of the type of the first reference to `x` within the loop proceeds as follows: First we visit the code path leading to the loop. That produces type `string` for `x` (which is cached). Next we examine the loop-back code path. That requires us to resolve the call to `foo(x)`. This in turn requires us to determine the type of `x`, which leads us back to the top of the loop. Here we see `string` cached from the first code path and an indication that we're processing the loop-back path, so we consider the type of `x` to simply be `string`. This is used to resolve `foo(x)` to type `number`, and the result of the outer resolution of the loop-back path becomes `number` (which is cached). Now, the subsequent actual type check of `foo(x)` will see `string | number` as the type of `x`.

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -11079,26 +11098,23 @@ namespace ts {
...
-                }
-                else {
-                    Debug.fail("Branch in 'getResolvedSignature' should be unreachable.");
-                }
-            }
-            return links.resolvedSignature;
+        function getResolvedOrAnySignature(node: CallLikeExpression) {
+            // If we're already in the process of resolving the given signature, don't resolve again as
+            // that could cause infinite recursion. Instead, return anySignature.
+            return getNodeLinks(node).resolvedSignature === anySignature ? anySignature : getResolvedSignature(node);
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Here, we are using `anySignature` to signal that we are in the middle of a flow analysis. Why not use `inFlowCheck`?

File: src/compiler/checker.ts [hunk 15]
```diff
@@ -11079,26 +11098,23 @@ namespace ts {
...
+            const cached = links.resolvedSignature;
+            if (cached && cached !== anySignature && !candidatesOutArray) {
+                return cached;
+            }
+            links.resolvedSignature = anySignature;
+            const result = resolveSignature(node, candidatesOutArray);
+            // If signature resolution originated in control flow type analysis (for example to compute the
+            // assigned type in a flow assignment) we don't cache the result as it may be based on temporary
+            // types from the control flow analysis.
+            links.resolvedSignature = inFlowCheck ? cached : result;
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Why does assigning `cached` mean we are not caching, but assigning `result` means we are caching?

**Comment by JsonFreeman** [comment]
@ahejlsberg I think this is the right compromise.

File: src/compiler/checker.ts (hunk 14 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: No, we're using `anySignature` to signal that we're in the process of resolving the call signature (for any reason, flow analysis or not). When obtaining contextual types we never want to kick off resolution if we're already in the process of resolving, so we return `anySignature` in circular scenarios. Effectively there are two circular scenarios interacting here, flow analysis and contextual typing, and only the flow analysis scenario can kick off resolution when resolution is already ongoing.

File: src/compiler/checker.ts (hunk 15 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: The `cached` variable contains what was already cached, and in flow check scenarios we restore that value instead of recording the result.

File: src/compiler/checker.ts (hunk 14 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Oh ok, got it

File: src/compiler/checker.ts (hunk 15 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I see, so if the call has never been processed yet, the value of `cached` will be undefined at this point. We will restore the undefined if we are in a flow analysis. So if we revisit the call later, it will look unprocessed.

One thing that occurs to me is the following. Suppose one of the call arguments is a lambda. In that case, we will type the lambda according to the first visit in the flow analysis. Any lambda parameters we type will stick, and they will permanently reflect the typing of the first pass. To piggy back on your example:
```ts
declare function foo<T, U>(s: T, func: (x: T) => U): U;

function f() {
    let x: string | number | boolean;
    x = "";
    while (cond) {
        x; // string | number
        x = foo(x, y => y.length); // Should be an error, string | number has no property length
        x; // number
    }
}
```
It is essentially the same issue that we see with overloads, where a lambda parameter is typed according to the first overload that binds it. In this case, instead of different overloads, it's different iterations of the loop that pass an argument of a different type.

**Comment by thebanjomatic** [comment]
I've been playing around with this branch the past couple of days and I've noticed that `any` doesn't narrow on control-flow assignments. Is this expected behavior?

For example:
```typescript
let a: any;
a = "10";
a; // a: any ... expected a: string
a.toFixed(2); // no compile error!
```

We are using noImplicitAny in our codebase, and try to avoid explicit any as much as humanly possible, but it seems like a generally good thing to continue to catch errors when using any (implicitly or explicitly).

**Comment by ahejlsberg** [comment]
@thebanjomatic That is the expected behavior currently. There are simple cases (such as your example) where we know the *exact* type of a value assigned to an `any`, but typically we only know parts of the truth. For example:

```TypeScript
declare function foo(): { x: number };

let a: any;
a = foo();
let y = a.y;  // Can't error here
```

It would be a breaking change from the current behavior to give an error above. That said, we're thinking about ways we can do better with `any` and control flow analysis, but it probably won't be in the initial PR.

**Comment by thebanjomatic** [comment]
I found another issue in my code-base relating to destructuring assignments when noImplicitAny is enabled. It can be simplified to the following:

```typescript
let [a, b, c] = [1, 2, 3];
```

The control flow appears to work correctly, however, 3 errors is produced saying that `a`, `b`, and `c` have an implicit type of any.

**Comment by thebanjomatic** [comment]
Nevermind, that appears to also be the case in master, I will file a separate issue for that.

**Comment by kristian-puccio** [comment]
Just trying out typescript now and working out for to get type check actions in redux. Looks like this feature could be very helpful for this?

https://github.com/reactjs/redux/issues/992

File: src/compiler/binder.ts (hunk 8 above)
Comment (birbilis) [inline src/compiler/binder.ts]: is it just for logical expressions or for other expressions too? cause I was wondering (language agnostically) what happens if something always raises an exception but isn't a throw statement (like dividing by zero), should one be clever enough to handle it? And should they also resolve constant values first or other statements that are calculatable at checking time, then check for such a case? Or would it be too far fetched, behaving like an AI coprogrammer?
