### PR TITLE
Fix use-before-def with methods on esnext+useDefineForClassFields

### LINKED ISSUE #37573: False positive for TS2729 (use before initialization) in 3.8.3, nightly
**TypeScript Version:**  3.8.3, nightly

**Search Terms:** used before initialization

**Code**

Reproduction requires both `--target esnext` and `--useDefineForClassFields` to be enabled.

```ts
class Foo {
    constructor (readonly foo: boolean) {}
}

class Bar extends Foo {
    bar = this.calculateBar(this.foo)

    private calculateBar(positive: boolean) {
        return positive ? 1 : -1
    }
}
```

**Expected behavior:**

Code to build.

Even if TypeScript was doing some kind of flow analysis here (which could flag `this.foo` instead of `this.calculateBar`), `Foo`'s constructor is guaranteed to finish executing before `bar`'s initializer gets a chance to run; and a prototype method is never _not_ initialized.

**Actual behavior:**

```
Property 'calculateBar' is used before its initialization.(2729)
input.ts(8, 13): 'calculateBar' is declared here.
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99&ts=3.9.0-dev.20200323#code/MYGwhgzhAEBiD29oG8BQ0PWPAdhALgE4Cuw+8h0AFIQKZgAmuIAntAGaIBc0ARoiHo4AlCgC+qCalCQYAITCVaAD3y0cDGAiRpMfRdAC80fAAsAlhAB0wMCGDFwahYSpnLVzvGGp0mAA6E5gBuYGpYdg5OtC5U-vAQ5vghtDz88IJgIih+ehh0+MSEONDxicnBtNAA-NAAjNA8ALR1udASEkA)

**Related Issues:** This seems related to #37287, just happens on different conditions

### PR DESCRIPTION
**Pull request by sandersn**
It was incorrectly flagging methods as used before their definition, but this is allowed under any emit.
The esnext+useDefineForClassFields-specific error should only apply to properties, but incorrectly applied to any declaration. This change makes it only apply to properties.

Fixes #37573

### CODE REVIEW

File: tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ class C {
     qux = this.bar // should error
     bar = this.foo // should error
     quiz = this.bar // ok
+    quench = this.m1() // ok
```
Comment (elibarzilay) [inline tests/cases/conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts:7]: (Maybe add a similar case with `m3 = function() ...` which should error, as a reminder that it's different and in case some rewrites are added in the future?)
