### PR TITLE
Multiple improvements to watching with --build option

### LINKED ISSUE #26524: tsc --build --watch does not watch wild card directories correctly
`updateWatchingWildcardDirectories` is normally used for single project and it mutates map to have new watch directories, Since we have single `existingWatchersForWildcards` among all projects this is incorrect and not watching wild card directories correctly.
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsbuild.ts#L569

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #26524, #26989

### CODE REVIEW

File: tests/baselines/reference/api/typescript.d.ts [hunk 1]
```diff
@@ -4183,14 +4182,11 @@ declare namespace ts {
...
     function createProgram(rootNames: ReadonlyArray<string>, options: CompilerOptions, host?: CompilerHost, oldProgram?: Program, configFileParsingDiagnostics?: ReadonlyArray<Diagnostic>): Program;
-    interface ResolveProjectReferencePathHost {
-        fileExists(fileName: string): boolean;
-    }
     /**
      * Returns the target config filename of a project reference.
      * Note: The file might not exist.
      */
-    function resolveProjectReferencePath(host: ResolveProjectReferencePathHost, ref: ProjectReference): ResolvedConfigFileName;
+    function resolveProjectReferencePath(ref: ProjectReference): ResolvedConfigFileName;
```
Comment (ajafff) [inline tests/baselines/reference/api/typescript.d.ts]: this is worth documenting as a breaking change. I'll need to update my use of that function or write my own that works for all TypeScript versions I want to support

Comment (sheetalkamat) [reply tests/baselines/reference/api/typescript.d.ts]: @RyanCavanaugh May be I can just revert the api change and make it such that first parameter is any so we don't break others

Comment (ajafff) [reply tests/baselines/reference/api/typescript.d.ts]: Maybe you could just add an overload that takes two parameters and discards the first one. This could be marked `@deprecated`
