### PR TITLE
fix(49566): Implicit this.property completions not returned while writing property

### LINKED ISSUE #49566: Implicit this.property completions not returned while writing property
# Bug Report

### 🔎 Search Terms

- suggest / suggestions
- completions 
- insertText

### 🕗 Version & Regression Information

4.8.0-dev.20220614, not a regression

### 💻 Repo

For the following code:

```ts
class Foo { 
    private _prop = 123;
    public prop = _pr // trigger suggest here
}
```

Trigger suggestions on the public version of prop

### 🙁 Actual behavior

No suggestions shown.

### 🙂 Expected behavior

We should return a suggestion for `_prop` that inserts `this._prop` when accepted. This is what happens when you trigger suggestions inside of method bodies

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49566

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -2616,7 +2616,8 @@ namespace ts.Completions {
 
             // Need to insert 'this.' before properties of `this` type, so only do that if `includeInsertTextCompletions`
             if (preferences.includeCompletionsWithInsertText && scopeNode.kind !== SyntaxKind.SourceFile) {
-                const thisType = typeChecker.tryGetThisTypeAt(scopeNode, /*includeGlobalThis*/ false);
+                const thisType = typeChecker.tryGetThisTypeAt(scopeNode, /*includeGlobalThis*/ false,
+                    isClassLike(scopeNode.parent) ? scopeNode : getThisContainer(scopeNode, /*includeArrowFunctions*/ false));
```
Comment (jakebailey) [inline src/services/completions.ts:2620]: I would consider defaulting to `undefined` here rather than duplicating the code; the right side is what the type checker does by default if you don't provide the argument, so I think piggybacking on that is going to be the right choice.

Comment (jakebailey) [inline src/services/completions.ts:2620]: Also, would it make more sense to move this logic into `getThisContainer`? Is this something that's just broken everywhere?

**Review by jakebailey — COMMENTED** [review]
LGTM but I am curious whether or not it's `getThisContainer` that's broken here.

File: src/services/completions.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/completions.ts]: @jakebailey I think this case is more related to the `completions`. `scopeNode` refers to `PropertyDeclaration` and the parent for it is  `ClassDeclaration` - `getThisContainer` doesn't treat class-like declarations like `this` container - which seems correct. So for this case `container` will be `SourceFile` and `tryGetThisTypeAt` returns `undefined`. So for the case where this is located in `PropertyDeclaration` and the parent is class-like we can use `PropertyDeclaration` as a container to get a type of `this`.

```ts
if (isClassLike(container.parent)) {
    const symbol = getSymbolOfNode(container.parent);
    const type = isStatic(container) ? getTypeOfSymbol(symbol) : (getDeclaredTypeOfSymbol(symbol) as InterfaceType).thisType!;
    return getFlowTypeOfReference(node, type);
}
```
 Does that make sense?

Comment (jakebailey) [reply src/services/completions.ts]: That sounds reasonable, yeah.

**Review by jakebailey — APPROVED** [review]
