### PR TITLE
fix(41818): Detached JSDoc class docstring using @extends crashes tsc

### LINKED ISSUE #41818: Detached JSDoc class docstring using @extends crashes tsc
**TypeScript Version:** 4.1.2

**Search Terms:** JSDoc, extends

If a detached JSDoc class docstring which uses `@extends` is placed in a `.js` file, `tsc` will crash. This does not happen when the `@extends` tag is not present.

**Code**

_widget.js_

```ts
class Widget {
    constructor() {

    }
}

/**
 * @class SpecialWidget
 * @extends Widget
 *
 * This class exposes a Special widget.
 */

/**
 * @constructor
 *
 * Create a `specialWidget`.
 */
class SpecialWidget extends Widget {
    constructor() {

    }
}

export default SpecialWidget;
```

_tsc command_

```
$ tsc widget.js --allowJs --outDir out
```

**Exepected behavior:**

Even though the docstring for the constructor is misplaced, this should not cause `tsc` to fail. 

**Actual behavior:**

```
$ tsc widget.js --allowJs --outDir out

C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:87001
                throw e;
                ^

Error: Debug Failure. False expression.
    at checkJSDocAugmentsTag (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:61428:22)
    at checkSourceElementWorker (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:64209:28)
    at checkSourceElement (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:64128:17)
    at Object.forEach (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:130:30)
    at C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:64136:31
    at Object.forEach (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:130:30)
    at checkSourceElementWorker (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:64134:20)
    at checkSourceElement (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:64128:17)
    at Object.forEach (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:130:30)
    at checkSourceFileWorker (C:\Users\Juda-OzbayEmilia\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:64445:20)
```

**Workbench link:**

https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKA7tAJgObwAuAdAFYDOAUAMazKWWgDq+RxoA3taH6LQD2iSsQBOAV1rFBYgBQBKbtV78AvtQ3VgAKh28dEeo2YBlAA7xa0ZLDaESBiPAAexJHmb2OBpwBUAC2hmYyZQV3NBSnhmZFALKxtYHHYSUgNgFV19UENwIRFxKRkxX1zQAGExeGR3UDiAA0pLa1tvEgb03MzQsxak9s5Xd0RPVlTOHn4BYVFJaVlFZVU+DS0I2U48eEhkCVhOBNa7CYBuIA

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41818

> In case of multiple documentation comments before a JavaScript symbol, JSDoc only associates the last comment with the symbol.

```ts
/**
 * @constructor
 */
class A {
    constructor() {}
}

/**
 * @extends {A}
 */

/**
 * @constructor
 */
class B extends A {
    constructor() {
        super();
    }
}
```

<details>
  <summary>checkJSDocAugmentsTag checks</summary>

  ```ts
  function checkJSDocAugmentsTag(node: JSDocAugmentsTag): void {
      const classLike = getEffectiveJSDocHost(node);
      if (!classLike || !isClassDeclaration(classLike) && !isClassExpression(classLike)) {
          error(classLike, Diagnostics.JSDoc_0_is_not_attached_to_a_class, idText(node.tagName));
          return;
      }
      const augmentsTags = getJSDocTags(classLike).filter(isJSDocAugmentsTag);
      Debug.assert(augmentsTags.length > 0);
  }
  ```
</details>

```ts
/**
 * @extends {A}
 */
```

`getEffectiveJSDocHost` returns node related to `class B extends A {}`. `getJSDocTags(classLike)` uses the comment associates with `class B extends A {}`
```ts
/**
 * @constructor
 */
```
that doesn't have `@extends`. For that reason TS throws `Debug.assert(augmentsTags.length > 0);`.

I suppose in this case `getEffectiveJSDocHost` should return `undefined`, to throw error  `JSDoc_0_is_not_attached_to_a_class`
```ts
/**
 * @extends {A}
 */
```

Or do we need to check `isJSDocAugmentsTag` in all JSDoc comments?

/cc @sandersn

### CODE REVIEW

**Comment by sandersn** [comment]
Your first solution is the right one. `getEffectiveJSDocHost` needs to understand that only the jsdoc immediately before a node is used for tags. And `checkJSDocAugmentsTag` should log the error for the example above.

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -2599,14 +2599,20 @@ namespace ts {
...
+            return getSourceOfDefaultedAssignment(host)
+                || getSourceOfAssignment(host)
+                || getSingleInitializerOfVariableStatementOrPropertyDeclaration(host)
+                || getSingleVariableOfVariableStatement(host)
+                || getNestedModuleDeclaration(host)
+                || host;
+        }
     }
 
     /** Use getEffectiveJSDocHost if you additionally need to look for jsdoc on parent nodes, like assignments.  */
```
Comment (sandersn) [inline src/compiler/utilities.ts:2618]: can you also look through uses of `getJSDocHost` and see what happens if we get rid of `checkDefined` and instead return `undefined` sometimes? Clearly there are unhosted jsdocs.

(Unfortunately this will be a change to the public API too.)

**Review by sandersn — CHANGES_REQUESTED** [review]
I like the checking you added to `getEffectiveJSDocHost` but it should be pushed down to `getJSDocHost`, if possible.

File: src/compiler/utilities.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/utilities.ts:2618]: I was able to make the changes myself, so I think getJSDocHost should instead have the check that you added in this PR and should add undefined to its return type.

Comment (a-tarasyuk) [reply src/compiler/utilities.ts:2618]: @sandersn Thanks for the review 👍🏻. I wanted to add these changes to `getJSDocHost`, however, I had one _failed_ test, so I decided to extend `getEffectiveJSDocHost` which is used in `checkJSDocAugmentsTag`. 

The following test fails

https://github.com/microsoft/TypeScript/blob/0d8a868e91ce5ae2fe0c26de7dbf7d6f7120d17f/tests/cases/conformance/jsdoc/typedefTagTypeResolution.ts#L17-L18

```shell
error TS2322: Type 'number' is not assignable to type 'U'.
  'U' could be instantiated with an arbitrary type which could be unrelated to 'number'.
```
Not sure if these changes are acceptable for all cases where `getJSDocHost` is used.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2172,7 +2175,7 @@ namespace ts {
             for (const decl of symbol.declarations) {
                 if (decl.kind === SyntaxKind.TypeParameter) {
                     const parent = isJSDocTemplateTag(decl.parent) ? getJSDocHost(decl.parent) : decl.parent;
-                    if (parent === container) {
+                    if (parent && parent === container) {
```
Comment (sandersn) [inline src/compiler/checker.ts:2178]: container can never be `=== undefined`, so this additional check isn't needed.

File: src/compiler/utilities.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/utilities.ts]: You worked around this in your latest commit, right?

File: src/compiler/checker.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: @sandersn done

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: > you worked around this in your latest commit, right?

Yes, I moved logic to `getJSDocHost`

File: src/compiler/utilities.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/utilities.ts]: @sandersn Yes.

**Review by sandersn — APPROVED** [review]
