### PR TITLE
Fixed a false positive related to binding patterns and spread expressions

### LINKED ISSUE #49585: Destructured immediately-invoked function with spread raises false errors
# Bug Report

### 🔎 Search Terms
destructured spread iife 

### 🕗 Version & Regression Information
- This changed between versions v4.4.4 and v4.5.5

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/MYewdgzgLgBA3jAbgQwDYFcCmMC+MC8MAZumMFAJbgAUAlPALABQMrMATplOu2Iy20EoMmAFwwARBIA0zQYIB0SqOywwA-PDzi4OWQNY4A3Mxx0TTIA)

### 💻 Code
```ts
const { value } = function() {
    return {
        value: "",
        ...true ? {} : {},
    };
}();
```

### 🙁 Actual behavior
This raises two errors:
- Line 1: Initializer provides no value for this binding element and the binding element has no default value.
- Line 3: 'value' is specified more than once, so this usage will be overwritten.

If you remove the `...true ? {} : {}` spread then it compiles successfully.

### 🙂 Expected behavior
I wouldn't expect any errors in this code. Especially the second error which is definitely not true.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #49585

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Trying again 😵‍💫

@typescript-bot perf test this faster

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -27970,7 +27970,8 @@ namespace ts {
             // type with those properties for which the binding pattern specifies a default value.
             // If the object literal is spread into another object literal, skip this step and let the top-level object
             // literal handle it instead.
-            if (contextualTypeHasPattern && node.parent.kind !== SyntaxKind.SpreadAssignment) {
+            const spreadOrOutsidePossibleObjectParent = findAncestor(node, n => n.kind === SyntaxKind.SpreadAssignment || isStatement(n) || isArrowFunction(n))!;
```
Comment (andrewbranch) [inline src/compiler/checker.ts:27973]: Failing test:

```ts
const { value } = {
  value: "",
  ...(() => true ? {} : {})(),
};
```

I could be missing a subtlety with nested binding patterns, but I think the question we want to answer is, as we are looking up the tree, do we pass a SpreadAssignment before we pass the `contextualType.pattern`? By choosing specific syntax kinds to stop at, you’re essentially trying to write an ad-hoc one-liner to represent what syntaxes contextual types can flow through.

If we wanted to be really sure we arrived at the right answer, we could do something like this:

- walk up the parents, again aborting if we pass the common ancestor of `node` and `contextualType.pattern`
- again stop at a `SpreadAssignment`, but also check to see if its parent’s `getContextualType(parent).pattern === contextualType.pattern`

I’m actually not sure whether it’s possible for that equality check to be false. But if I knew it was true, I’d feel _really_ confident that the check was going to happen on the parent object literal.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:27973]: Related nit: the outer IIFE is totally irrelevant to the repro, so the test name is perhaps a bit misleading.

Comment (Andarist) [reply src/compiler/checker.ts]: Thanks for the review! I believe that I've addressed the feedback. Could you take another look?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -28086,15 +28086,20 @@ namespace ts {
...
-                    if (!propertiesTable.get(prop.escapedName) && !getPropertyOfType(spread, prop.escapedName)) {
-                        if (!(prop.flags & SymbolFlags.Optional)) {
-                            error(prop.valueDeclaration || (prop as TransientSymbol).bindingElement,
-                                Diagnostics.Initializer_provides_no_value_for_this_binding_element_and_the_binding_element_has_no_default_value);
-                        }
-                        propertiesTable.set(prop.escapedName, prop);
-                        propertiesArray.push(prop);
+            if (contextualTypeHasPattern) {
+                const rootPatternParent = findAncestor(contextualType.pattern!.parent, n => n.kind === SyntaxKind.VariableDeclaration || n.kind === SyntaxKind.BinaryExpression || n.kind === SyntaxKind.Parameter);
+                const spreadOrOutsideRootObject = findAncestor(node, n => n === rootPatternParent || (n.kind === SyntaxKind.SpreadAssignment && getContextualType(n.parent as Expression, /*contextFlags*/ undefined)!.pattern === contextualType.pattern))!;
```
Comment (andrewbranch) [inline src/compiler/checker.ts:28091]: Were you able to determine that checking for the equality of these two contextual type patterns was actually necessary?

Either way, we may want to expand on the comment above to give a more rigorous definition of “If the object literal is spread into another object literal.”

**Review by andrewbranch — APPROVED** [review]

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (Andarist) [reply src/compiler/checker.ts:28091]: > Were you able to determine that checking for the equality of these two contextual type patterns was actually necessary?

I've removed this now since the whole test suite passes without it. It's hard for me to tell if there is any missing test case to be written that would prove that it's needed though since I don't fully understand how contextual typing works in the implementation.

> Either way, we may want to expand on the comment above to give a more rigorous definition of “If the object literal is spread into another object literal.”

The only thing that comes to my mind that could be added is adding something like "(even transitively)" to this comment.

> I agree. I don't understand how the new code implements the comment now. 

From my PoV, I didn't really change the code in a way that would require any major changes to this comment. Conceptually the previous code was just checking if the direct parent of the node is a spread assignment and now I'm checking if there is any spread assignment ancestor (up to the parent of the contextualType's parent). There are no other changes beyond that - so unless I'm missing something, or unless the comment was confusing in the first place, this change shouldn't require any major changes. The only thing that comes to my mind is what I've mentioned in the answer to Andrew's comment - I could add something like "(even transitively)". Would this make it better from your PoV? Or were you thinking about some other changes?

> And I'm worried about the number of upward tree walks in this part of the code now.

I see your point and I've tried to experiment with "context flag" and I think that I've managed to get this to work (https://github.com/microsoft/TypeScript/pull/49684/commits/be387e3bbf8a5cce2bc4c31fd77b061ea6cf8e0b). The solution isn't overly pretty but it resembles some other places in the codebase (for instance I've seen similar code with "awaited stacks" when detectecting circular `Awaited` types)

My only concern here is that now the logic depends on the top-down order of checking (which is probably a safe bet when performing full check). It was already insufficient when checking deferred nodes and that's why I had to introduce `objectsWithinSpread` set - this still relies on the "full check" being performed before checking deferred nodes (I don't quite understand why both check expressions within functions, what's the point of deferring the nodes if they are already checked during the "full check"?). So I'm somewhat worried that this might not be sufficient to check this correctly when using APIs like `getTypeAtLocation`. Thoughts?

> Also, please reformat the new code. The lines are too long.

Would it be worthwhile to introduce a related ESLint rule to the codebase? Or maybe even Prettier? :sweat_smile:

Comment (andrewbranch) [reply src/compiler/checker.ts:28091]: I almost suggested setting a flag at the top of the check, but I decided against it when I realized that it’s non-trivial to decide where to _unset_ the flag—essentially, it requires the exact same logic you had looking up the tree, but split into multiple places to maintain the state (set on the way into an object literal, unset on the way into ???, unset on the way out of the object literal). And that doesn’t make it any easier to determine what "???" is. I’m not sure whether you have it correctly handled now or not. I also agree with your concern about possibly missing the context flag in calls to `getTypeAtLocation`.

I ran the perf suite after your change that included the probably-superfluous `getContextualType` addition, and it was clean. I’m pretty sure it was only calling `getContextualType` on nodes whose contextual type was already computed or was going to be computed later. Either way, I’m happy with it removed—I think we can assume it’s not necessary until proven otherwise. With that gone, I’m definitely not worried about any perf impact.

When I suggested updating the comment, I just meant for you to explain how you decide on a stopping point the same way I explained it in my first review of the PR—that it’s not enough to look at parents' `kind` since IIFEs and conditional expressions flowed the type through in a non-obvious way (this was the bug), but that we know the stopping point because we know where the binding pattern that created the contextual type is.

Comment (Andarist) [reply src/compiler/checker.ts:28091]: @andrewbranch I've reverted the code back to the ancestor traversal variant and added more info to the discussed comment. Would you mind taking another look?

**Review by andrewbranch — APPROVED** [review]
Looks good, thanks!

**Comment by Andarist** [comment]
@andrewbranch friendly 🏓 anything else that has to be done to land this PR?

**Comment by andrewbranch** [comment]
I was giving @sandersn another opportunity to look at it since he had requested changes.

**Comment by sandersn** [comment]
Sorry about that, this fell off my radar. It looks fine to me.

**Review by sandersn — APPROVED** [review]
