### PR TITLE
propagate back assignments to block scoped binding from the loop body

### LINKED ISSUE #6877: Incorrect behavior of loop contains block-scoped variables in es5 and es3
TypeScript needs to fix or revert this polyfill.

```ts
// index.ts
(function () {
  'use strict'
  for (let i = 0; i < 9; ++i) {
    (() => console.log(++i))();
  }
})();
```

expected:

```
> (function () {
  'use strict'
  for (let i = 0; i < 9; ++i) {
    (() => console.log(++i))();
  }
})();
1
3
5
7
9
```

actual:

```
$ node index.js
1
2
3
4
5
6
7
8
9
```

### PR DESCRIPTION
**Pull request by vladima**
fixes #6877.
NOTE: it will be cleaner to emit loop body as 
```ts
let loop = function(...) {
    try { loop body }
    finally { copy local values to out parameters }
}
```
instead of writing copy snippet at every point where control flow exits loop. However currently V8 does not optimize [protected regions](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax) so between prettiness and perf of generated code I'd prefer to favor the second one

### CODE REVIEW

File: tests/baselines/reference/blockScopedBindingsReassignedInLoop1.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+//// [blockScopedBindingsReassignedInLoop1.js]
+(function () {
+    'use strict';
+    var _loop_1 = function(i) {
+        (function () { return use(++i); })();
+        out_i_1 = i;
+    };
+    var out_i_1;
+    for (var i = 0; i < 9; ++i) {
+        out_i_1 = i;
```
Comment (mhegazy) [inline tests/baselines/reference/blockScopedBindingsReassignedInLoop1.js]: i do not think we need this, since the function is guaranteed to set the correct value.

**Comment by mhegazy** [comment]
:+1: with the removal of the extra assignment.

File: tests/baselines/reference/blockScopedBindingsReassignedInLoop1.js (hunk 1 above)
Comment (vladima) [inline tests/baselines/reference/blockScopedBindingsReassignedInLoop1.js]: true, will do
