### PR TITLE
Fix `readonly` occurrences highlighting

### LINKED ISSUE #32199: Thrown Invalid container kind. SyntaxKind: InterfaceDeclaration / TypeLiteral
**TypeScript Version:**  3.5.1 (Monaco editor 0.17.1)

**Search Terms:** Invalid container kind SyntaxKind InterfaceDeclaration TypeLiteral

Original issue: https://github.com/microsoft/monaco-editor/issues/1501

**Code**

```ts
class SomeClass {
  // Here it works (note that the `readonly` modifier also gets highlighted 
  //  in Monaco editor):
  readonly prop: string = "xxx";
}

interface SomeInterface1 {
  // Case 1: "Invalid container kind. SyntaxKind: InterfaceDeclaration"
  readonly prop: string;
}

interface SomeInterface2 {
  readonly nested: {
    // Case 2: "Invalid container kind. SyntaxKind: TypeLiteral"
    readonly prop: string;
  };
}
```

**Expected behavior:** No crash

**Actual behavior:**

* Thrown error `Debug Failure. Invalid container kind. SyntaxKind: InterfaceDeclaration`
* Thrown error `Debug Failure. Invalid container kind. SyntaxKind: TypeLiteral`

**Playground Link:** 

https://www.typescriptlang.org/play/#code/MYGwhgzhAEDKD2BbApgYXFaBvAUNaA9AdABLIBOy0AlgC7QDu85A1jABQB28tVtAFmHoCqAA0pgAJvE4gAnqOiJ4k6gDNqFaGBAR40AObJaMftQP8Q5-r0nQ8hYjU7QAsjLDB9yVbWYBKAC4HCWlZOWgAB3J4SMDoCFpyak4DaABeaAAiAA88rIBuHABfHBwU3nI1TyoEFABJTkrq4GQARmwHImhUSCo2+KzGgDcdajsvJrAUrRYUyQA6ODkpnIBpefjG5pqAEWRQMHIhahkskOQpGXkomLiEpJSDItLypooW2qRkbY+agCZOvhQtcIpxkIkfPFcPh8N1ehAqP9BiMxhMZLRpuDyNA5pxFstVht8fEACpySLIAAydAoOnOsOgIPCt1i8USyVSRXwxReQA

=> Open the F12 tools and move the cursor to one of the `readonly` modifiers.

... these cases don't seem to be handled in `getNodesToSearchForModifier`:

https://github.com/microsoft/TypeScript/blob/f89165d0727d818eb3afd780bd1ea6fb834a9354/src/services/documentHighlights.ts#L194

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #32199

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -709,10 +709,26 @@ namespace ts.FindAllReferences.Core {
         return references.length ? [{ definition: { type: DefinitionKind.Symbol, symbol }, references }] : emptyArray;
     }
 
+    /** As in a `readonly prop: any` or `constructor(readonly prop: any)`, not a `readonly any[]`. */
+    function isMemberModifyingReadonlyKeyword(node: Node): boolean {
```
Comment (andrewbranch) [inline src/services/findAllReferences.ts]: My internalization of @sandersn PR reviews is starting to develop, and I could already hear the voice in the back of my head saying that he wasn’t sold on the name. I’m not either, but I struggled to come up with something more accurate and pithy. In `readonly string[]`, it’s not strictly a “modifier” but an “operator,” so technically I could just mention “modifier” without “member” as a disambiguation, but I think `readonly` in `readonly string[]` kinda _looks_ like a modifier... I went back and forth for 10 minutes or so before deciding I needed to move on with my life.

File: tests/cases/fourslash/documentHighlightsInvalidModifierLocations.ts [hunk 2]
```diff
@@ -4,7 +4,12 @@
...
 ////function f([|readonly|] p) {}
+////
+////class D {
+////    m([|public|] p) {}
+////}
+////function g([|public|] p) {}
 
 for (const r of test.ranges()) {
-    verify.documentHighlightsOf(r, test.ranges());
+    verify.documentHighlightsOf(r, [r]);
```
Comment (andrewbranch) [inline tests/cases/fourslash/documentHighlightsInvalidModifierLocations.ts]: I changed the assertion here—the original assertion didn’t make a lot of sense and it was inconsistent with `public` and `private` modifiers. I expanded the test file content to show that.

File: src/services/findAllReferences.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/services/findAllReferences.ts]: `isReadonlyKeywordOnProperty`

Comment (DanielRosenwasser) [reply src/services/findAllReferences.ts]: isReadonlyModifierForMemberDeclaration

File: tests/cases/fourslash/getOccurrencesReadonly1.ts [hunk 3]
```diff
@@ -0,0 +1,7 @@
+/// <reference path="fourslash.ts" />
+
+////interface I {
+////  [|readonly|] prop: string;
+////}
+
+verify.rangesAreOccurrences(false);
```
Comment (orta) [inline tests/cases/fourslash/getOccurrencesReadonly1.ts]: It might be because I don't quite get what an occurrence is, but this function name seems really strange to me`verify.rangesAreOccurrences `

Comment (andrewbranch) [reply tests/cases/fourslash/getOccurrencesReadonly1.ts]: Yeah, I think it's supposed to mean something like “the contents of each of these ranges is another occurrence of the contents of every other range”

File: src/services/findAllReferences.ts [hunk 4]
```diff
@@ -709,10 +709,26 @@ namespace ts.FindAllReferences.Core {
...
+        return node.kind === SyntaxKind.ReadonlyKeyword && hasReadonlyModifier(node.parent);
+    }
+
     /** getReferencedSymbols for special node kinds. */
     function getReferencedSymbolsSpecial(node: Node, sourceFiles: ReadonlyArray<SourceFile>, cancellationToken: CancellationToken): SymbolAndEntries[] | undefined {
         if (isTypeKeyword(node.kind)) {
-            return getAllReferencesForKeyword(sourceFiles, node.kind, cancellationToken);
+            // A modifier readonly (like on a property declaration) is not special;
+            // a readonly type keyword (like `readonly string[]`) is.
+            if (isMemberModifyingReadonlyKeyword(node)) {
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts]: I think instead of checking node.parent modifiers you should check if this is readonly operator on Type.
````ts
export interface TypeOperatorNode extends TypeNode {
        kind: SyntaxKind.TypeOperator;
        operator: SyntaxKind.KeyOfKeyword | SyntaxKind.UniqueKeyword | SyntaxKind.ReadonlyKeyword;
        type: TypeNode;
    }
```

Comment (andrewbranch) [reply src/services/findAllReferences.ts]: That works, but I feel like it’s a weird way to write the function `isReadonlyModifierForMemberDeclaration`—if the function name implies that we’re checking if it’s used as a modifier, I’d rather check that it _is_ a modifier than check that it’s _not_ a type operator.

Comment (sheetalkamat) [reply src/services/findAllReferences.ts]: You could name it to be isReadonlyTypeOperator and that would work. I think that's what you want to allow so you would want to check that.

File: src/compiler/core.ts [hunk 5]
```diff
@@ -2151,6 +2151,10 @@ namespace ts {
         return arg => f(arg) || g(arg);
     }
 
+    export function not<T extends unknown[]>(f: (...args: T) => boolean): (...args: T) => boolean {
```
Comment (sheetalkamat) [inline src/compiler/core.ts]: Remove this function since it’s not used anymore ?

Comment (andrewbranch) [reply src/compiler/core.ts]: Hah, I left it because I feel fairly certain I’ll add it again before long, but I guess I’ll just do it again then 😁

Comment (andrewbranch) [inline src/compiler/core.ts]:
```suggestion
```

File: src/compiler/core.ts [hunk 6]
```diff
@@ -2151,6 +2151,10 @@ namespace ts {
         return arg => f(arg) || g(arg);
     }
 
+    export function not<T extends unknown[]>(f: (...args: T) => boolean): (...args: T) => boolean {
+        return (...args) => !f(...args);
```
Comment (andrewbranch) [inline src/compiler/core.ts]:
```suggestion
```

File: src/compiler/core.ts [hunk 7]
```diff
@@ -2151,6 +2151,10 @@ namespace ts {
         return arg => f(arg) || g(arg);
     }
 
+    export function not<T extends unknown[]>(f: (...args: T) => boolean): (...args: T) => boolean {
+        return (...args) => !f(...args);
+    }
```
Comment (andrewbranch) [inline src/compiler/core.ts]:
```suggestion
```

File: src/compiler/core.ts [hunk 8]
```diff
@@ -2151,6 +2151,10 @@ namespace ts {
         return arg => f(arg) || g(arg);
     }
 
+    export function not<T extends unknown[]>(f: (...args: T) => boolean): (...args: T) => boolean {
+        return (...args) => !f(...args);
+    }
+
```
Comment (andrewbranch) [inline src/compiler/core.ts]:
```suggestion
```
