### PR TITLE
Avoid bogus circularity error on context sensitive constructor property assignments

### LINKED ISSUE #44581: Class attribute inference with template literals
# Bug Report

### 🔎 Search Terms

template literals class attribute 7022

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.2

### ⏯ Playground Link

Working with TypeScript 4.2.3:
https://www.typescriptlang.org/play?ts=4.2.3#code/MYGwhgzhAECyCeBhcVoG8BQ1oAcBOA9jgKZ4Au8A3FroSefAEzU3AEB2EZeArsGQTwAKAJToa2NpzLQAbmDwBLMACMQxaAF5oAcggEAtsTIALRewDmOjBOinFEAHT4ipClugADAGYECn6mxseycXegpGDx8-AFoAEjR5JVV1AF8A21spLmgQAmAwEAAFOjd4KN8CeMSFZTVidMDoVIxUoA

Not anymore in TypeScript 4.3.2:
https://www.typescriptlang.org/play?ts=4.3.2#code/MYGwhgzhAECyCeBhcVoG8BQ1oAcBOA9jgKZ4Au8A3FroSefAEzU3AEB2EZeArsGQTwAKAJToa2NpzLQAbmDwBLMACMQxaAF5oAcggEAtsTIALRewDmOjBOinFEAHT4ipClugADAGYECn6mxseycXegpGDx8-AFoAEjR5JVV1AF8A21spLmgQAmAwEAAFOjd4KN8CeMSFZTVidMDoVIxUoA

### 💻 Code

```ts
class MyClass {
  property;
  property2;

  constructor() {
    const variable = 'something'

    this.property = `foo`; // Correctly inferred as `string`
    this.property2 = `foo-${variable}`; // Causes an error
    
    const localProperty = `foo-${variable}`; // Correctly inferred as `string`
  }
}
```

### 🙁 Actual behavior

It raises the following error on `property2`:
```
'property2' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer. (7022)
```

### 🙂 Expected behavior

`property2` should be inferred as `string`

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #44581

### CODE REVIEW

**Review by orta — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -25248,12 +25248,46 @@ namespace ts {
...
+                return getResolvedSymbol(e);
+            }
+            if (isPropertyAccessExpression(e)) {
+                const lhsType = getTypeOfExpression(e.expression);
+                const prop = isPrivateIdentifier(e.name) ? tryGetPrivateIdentifierPropertyOfType(lhsType, e.name) : getPropertyOfType(lhsType, e.name.escapedText);
+                return prop;
+            }
+            return undefined;
+
+            function tryGetPrivateIdentifierPropertyOfType(type: Type, id: PrivateIdentifier) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:25269]: Why is this nested (it doesn't capture `e`) ?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -25248,12 +25248,46 @@ namespace ts {
...
+                return prop;
+            }
+        }
+
         // In an assignment expression, the right operand is contextually typed by the type of the left operand.
         // Don't do this for assignment declarations unless there is a type tag on the assignment, to avoid circularity from checking the right operand.
         function getContextualTypeForAssignmentDeclaration(binaryExpression: BinaryExpression): Type | undefined {
             const kind = getAssignmentDeclarationKind(binaryExpression);
             switch (kind) {
                 case AssignmentDeclarationKind.None:
```
Comment (sandersn) [inline src/compiler/checker.ts:25281]: I thought the problem was with `AssignmentDeclarationKind.ThisProperty`. Why is the new code in `None` instead? Is it because there's an existing PropertyDeclaration? 

The new code in `getSymbolForExpression` kind of looks like it's a fallback mode for when syntactic detection fails in the checker, which it shouldn't if it has succeeded in the binder. So maybe the fix needs to be to iron out some mismatch between the binder and checker.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:25281]: `ThisProperty` assignments don't exist in TS - or at least these aren't flagged as such. Moreover, when we don't find an annotation for those, we still fallback to the `getTypeOfExpression` call, which is what triggers a circularity warning. The symbol lookup code is essentially what `checkPropertyAccessExpression` does, except without eagerly materializing the type of the property. In the past, we've just done a simple `getPropertyOfType` inline, but in a post-private-symbol era, that's no longer sufficient.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -25248,12 +25248,46 @@ namespace ts {
...
+            if (e.symbol) {
+                return e.symbol;
+            }
+            if (isIdentifier(e)) {
+                return getResolvedSymbol(e);
+            }
+            if (isPropertyAccessExpression(e)) {
+                const lhsType = getTypeOfExpression(e.expression);
+                const prop = isPrivateIdentifier(e.name) ? tryGetPrivateIdentifierPropertyOfType(lhsType, e.name) : getPropertyOfType(lhsType, e.name.escapedText);
+                return prop;
```
Comment (sandersn) [inline src/compiler/checker.ts:25265]:
```suggestion
                return isPrivateIdentifier(e.name) ? tryGetPrivateIdentifierPropertyOfType(lhsType, e.name) : getPropertyOfType(lhsType, e.name.escapedText);
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:25269]: Just because it wasn't used outside of this function. :)

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:25281]: > `ThisProperty` assignments don't exist in TS - or at least these aren't flagged as such. 
Wellll, I guess that makes sense, since these technically evolve the type of an existing PropertyDeclaration. It's just a bit confusing since they're so similar.

However, I think they'll get marked as ThisProperty assignments in JS, so this PR needs a matching JS test to find out.

**Review by sandersn — CHANGES_REQUESTED** [review]
OK, I'm convinced about the approach. Just needs a test in JS, since I think that evolving class properties work in JS, and may incorrectly get marked as ThisProperty assignments there.

**Comment by weswigham** [comment]
@sandersn done, there's now a JS test, and the code's been shuffled a bit to cover the JS case as well.

**Review by sandersn — APPROVED** [review]
