### PR TITLE
Store symbol table map key in CachedSymbolExportInfo

### LINKED ISSUE #45101: Auto import doesn't work when re-export alias merges with augmentation
Follow-up to #45055

### LINKED ISSUE #45200: TS Server: Debug Failure. (VSCode completions don't work)
# Bug Report

I assume this is a duplicate of [this issue](https://github.com/microsoft/TypeScript/issues/45030) which has been closed already, but I have a bit more information that may or may not be relevant.

Code suggestions don't work for me most of the time. Curiously, commenting/uncommenting the line `"typescript.tsserver.log": "normal"` in my VSCode `settings.json` fixes this temporarily.

[I was redirected from this issue.](https://github.com/microsoft/vscode-typescript-next/issues/20#issuecomment-887060993)

4nIJJg3pWn

### 🔎 Search Terms

completion, completionInfo, "debug failure", 54, rehydrateCachedInfo

### 🕗 Version & Regression Information

Version: 4.4.0-dev.20210726

I just tried testing it with 4.3.2 and it seems to be working just fine.

### Logs & Configuration

`tsserver.log`:

```
Info 0    [11:18:49.537] Starting TS Server
Info 1    [11:18:49.538] Version: 4.4.0-dev.20210726
Info 2    [11:18:49.538] Arguments: C:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\rasna\AppData\Local\Temp\vscode-typescript\45dd3c9b5fbf43ecf60d\tscancellation-b9fe775fac40ba774bf5.tmp* --logVerbosity normal --logFile c:\Users\rasna\AppData\Roaming\Code\logs\20210727T091851\exthost1\vscode.typescript-language-features\tsserver-log-0EPlX4\tsserver.log --globalPlugins typescript-vscode-sh-plugin,typescript-styled-plugin,@vsintellicode/typescript-intellicode-plugin --pluginProbeLocations c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features,c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6,c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [11:18:49.538] Platform: win32 NodeVersion: 14 CaseSensitive: false
Info 4    [11:18:49.538] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [11:18:49.557] Host information vscode
Info 6    [11:18:49.557] Host watch options changed to undefined, it will be take effect for next watches.
Info 7    [11:18:49.559] Search path: c:/Users/rasna/Projects/vx-doc/layout
Info 8    [11:18:49.559] For info: c:/Users/rasna/Projects/vx-doc/layout/e.tsx :: Config file name: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 9    [11:18:49.560] Creating configuration project c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 10   [11:18:49.624] Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json : {
 "rootNames": [
  "c:/Users/rasna/Projects/vx-doc/next-env.d.ts",
  "c:/Users/rasna/Projects/vx-doc/global.d.ts",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/use-filter-tags.ts",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/use-selection-model.ts",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/types.d.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/constants.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/magic-constants.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/documents.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/endpoints.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/index.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/keyword-entries.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/keyword-lists.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/reports.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/tags.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/config/axios.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/config/headers.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/config/swr.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/schema/formatting.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/schema/index.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/schema/schema.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/schema/types.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/schema/validation.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/schema/config/yup.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/types/index.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/types/shared/index.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/types/shared/server-response.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/types/shared/swr-error.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/types/utils/dto.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/types/utils/index.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/utils/generic.ts",
  "c:/Users/rasna/Projects/vx-doc/lib/api-client/utils/index.ts",
  "c:/Users/rasna/Projects/vx-doc/mock/server.ts",
  "c:/Users/rasna/Projects/vx-doc/styles/global.ts",
  "c:/Users/rasna/Projects/vx-doc/styles/index.ts",
  "c:/Users/rasna/Projects/vx-doc/utils/capitalize.ts",
  "c:/Users/rasna/Projects/vx-doc/utils/parse-id.ts",
  "c:/Users/rasna/Projects/vx-doc/utils/use-cache.ts",
  "c:/Users/rasna/Projects/vx-doc/utils/use-mirage.ts",
  "c:/Users/rasna/Projects/vx-doc/utils/use-mutate-context.ts",
  "c:/Users/rasna/Projects/vx-doc/components/DevNav.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/ListItemLink.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/LoginDialog.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/NextLink.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/RegisterDialog.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/Spacer.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/TagsDrawer.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/UploadButton.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/icons.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/index.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/AddTagPopover.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/KeywordGrid.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/TagChip.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/index.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/Toolbar/AddTagsActionDialog.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/Toolbar/CopyActionDialog.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/Toolbar/FilterPanel.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/Toolbar/Toolbar.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/KeywordGrid/Toolbar/index.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED2/TextField.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED2/index.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/Anchor.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/Button.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/Dialog.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/TextField.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/Typography.tsx",
  "c:/Users/rasna/Projects/vx-doc/components/REDACTED/index.tsx",
  "c:/Users/rasna/Projects/vx-doc/layout/DefaultLayout.tsx",
  "c:/Users/rasna/Projects/vx-doc/layout/Header.tsx",
  "c:/Users/rasna/Projects/vx-doc/layout/KeywordListsNav.tsx",
  "c:/Users/rasna/Projects/vx-doc/layout/NavDrawer.tsx",
  "c:/Users/rasna/Projects/vx-doc/layout/e.tsx",
  "c:/Users/rasna/Projects/vx-doc/pages/_app.tsx",
  "c:/Users/rasna/Projects/vx-doc/pages/_document.tsx",
  "c:/Users/rasna/Projects/vx-doc/pages/index.tsx",
  "c:/Users/rasna/Projects/vx-doc/pages/report.tsx",
  "c:/Users/rasna/Projects/vx-doc/pages/upload.tsx",
  "c:/Users/rasna/Projects/vx-doc/pages/keywords/[klid].tsx",
  "c:/Users/rasna/Projects/vx-doc/utils/withoutSWRRevalidateOnFocus.tsx"
 ],
 "options": {
  "baseUrl": "c:/Users/rasna/Projects/vx-doc",
  "target": 99,
  "lib": [
   "lib.dom.d.ts",
   "lib.dom.iterable.d.ts",
   "lib.esnext.d.ts"
  ],
  "allowJs": true,
  "skipLibCheck": true,
  "strict": true,
  "strictFunctionTypes": false,
  "forceConsistentCasingInFileNames": true,
  "noEmit": true,
  "esModuleInterop": true,
  "module": 99,
  "moduleResolution": 2,
  "resolveJsonModule": true,
  "isolatedModules": true,
  "jsx": 1,
  "paths": {
   "@REDACTED": [
    "components/REDACTED"
   ],
   "@REDACTED2": [
    "components/REDACTED2"
   ]
  },
  "pathsBasePath": "c:/Users/rasna/Projects/vx-doc",
  "configFilePath": "c:/Users/rasna/Projects/vx-doc/tsconfig.json"
 }
}
Info 11   [11:18:49.695] Loading global plugin typescript-vscode-sh-plugin
Info 12   [11:18:49.695] Enabling plugin typescript-vscode-sh-plugin from candidate paths: c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features,c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6,c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14,c:/Users/rasna/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210726/node_modules/typescript/lib/tsserver.js/../../..
Info 13   [11:18:49.695] Loading typescript-vscode-sh-plugin from c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features (resolved to c:/Users/rasna/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/typescript-language-features/node_modules)
Info 14   [11:18:49.701] typescript-vscode-sh-plugin active for version < 4.2 and JS/JSX files. Current version : 4.4.0-dev.20210726
Info 15   [11:18:49.701] Intercepting getEncodedSemanticClassifications and getEncodedSyntacticClassifications.
Info 16   [11:18:49.701] Plugin validation succeeded
Info 17   [11:18:49.701] Loading global plugin typescript-styled-plugin
Info 18   [11:18:49.701] Enabling plugin typescript-styled-plugin from candidate paths: c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features,c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6,c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14,c:/Users/rasna/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210726/node_modules/typescript/lib/tsserver.js/../../..
Info 19   [11:18:49.701] Loading typescript-styled-plugin from c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features (resolved to c:/Users/rasna/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/typescript-language-features/node_modules)
Info 20   [11:18:49.715] Loading typescript-styled-plugin from c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6 (resolved to c:/Users/rasna/.vscode/extensions/jpoissonnier.vscode-styled-components-1.6.6/node_modules)
Info 21   [11:18:49.807] [ts-styled-plugin] config: {"tags":["styled","css","extend","injectGlobal","createGlobalStyle"],"validate":true,"lint":{"emptyRules":"ignore"},"emmet":{}}
Info 22   [11:18:49.808] Plugin validation succeeded
Info 23   [11:18:49.808] Loading global plugin @vsintellicode/typescript-intellicode-plugin
Info 24   [11:18:49.808] Enabling plugin @vsintellicode/typescript-intellicode-plugin from candidate paths: c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features,c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6,c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14,c:/Users/rasna/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210726/node_modules/typescript/lib/tsserver.js/../../..
Info 25   [11:18:49.808] Loading @vsintellicode/typescript-intellicode-plugin from c:\Users\rasna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features (resolved to c:/Users/rasna/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/typescript-language-features/node_modules)
Info 26   [11:18:49.809] Loading @vsintellicode/typescript-intellicode-plugin from c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6 (resolved to c:/Users/rasna/.vscode/extensions/jpoissonnier.vscode-styled-components-1.6.6/node_modules)
Info 27   [11:18:49.810] Loading @vsintellicode/typescript-intellicode-plugin from c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14 (resolved to c:/Users/rasna/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.14/node_modules)
Info 28   [11:18:49.817] IntelliCode plugin: starting configuration: {"name":"@vsintellicode/typescript-intellicode-plugin","global":true}
Info 29   [11:18:49.817] Plugin validation succeeded
Info 30   [11:18:49.880] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 31   [11:18:53.110] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 1 structureChanged: true structureIsReused:: Not Elapsed: 3230.0011999607086ms
Info 32   [11:18:53.110] Project 'c:/Users/rasna/Projects/vx-doc/tsconfig.json' (Configured)
Info 33   [11:18:53.110] 	Files (744)

Info 34   [11:18:53.110] -----------------------------------------------
Info 35   [11:18:53.146] Starting updateGraphWorker: Project: /dev/null/autoImportProviderProject1*
Info 36   [11:18:53.174] Finishing updateGraphWorker: Project: /dev/null/autoImportProviderProject1* Version: 1 structureChanged: true structureIsReused:: Not Elapsed: 27.683200001716614ms
Info 37   [11:18:53.174] Project '/dev/null/autoImportProviderProject1*' (AutoImportProvider)
Info 38   [11:18:53.174] 	Files (17)

Info 39   [11:18:53.174] -----------------------------------------------
Info 40   [11:18:53.180] Search path: c:/Users/rasna/Projects/vx-doc/layout
Info 41   [11:18:53.180] For info: c:/Users/rasna/Projects/vx-doc/layout/KeywordListsNav.tsx :: Config file name: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 42   [11:18:53.180] Project 'c:/Users/rasna/Projects/vx-doc/tsconfig.json' (Configured)
Info 42   [11:18:53.180] 	Files (744)

Info 42   [11:18:53.180] -----------------------------------------------
Info 42   [11:18:53.180] Project '/dev/null/autoImportProviderProject1*' (AutoImportProvider)
Info 42   [11:18:53.180] 	Files (17)

Info 42   [11:18:53.180] -----------------------------------------------
Info 42   [11:18:53.180] Open files: 
Info 42   [11:18:53.180] 	FileName: c:/Users/rasna/Projects/vx-doc/layout/e.tsx ProjectRootPath: c:/Users/rasna/Projects/vx-doc
Info 42   [11:18:53.180] 		Projects: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 42   [11:18:53.180] 	FileName: c:/Users/rasna/Projects/vx-doc/layout/KeywordListsNav.tsx ProjectRootPath: c:/Users/rasna/Projects/vx-doc
Info 42   [11:18:53.180] 		Projects: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 42   [11:18:53.184] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2462 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 43   [11:18:53.184] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2462
Info 44   [11:18:53.184] Elapsed:: 0.22630000114440918ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2462 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 45   [11:18:53.184] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2462 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 46   [11:18:53.184] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2462
Info 47   [11:18:53.184] Elapsed:: 0.03630000352859497ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2462 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 48   [11:18:53.184] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2463 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 49   [11:18:53.184] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2463
Info 50   [11:18:53.184] Elapsed:: 0.042600035667419434ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2463 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 51   [11:18:53.185] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2463 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 52   [11:18:53.185] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2463
Info 53   [11:18:53.185] Elapsed:: 0.04249995946884155ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2463 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 54   [11:18:53.185] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2464 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 55   [11:18:53.185] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2464
Info 56   [11:18:53.185] Elapsed:: 0.0648999810218811ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2464 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 57   [11:18:53.185] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2464 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 58   [11:18:53.185] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2464
Info 59   [11:18:53.185] Elapsed:: 0.029699981212615967ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2464 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 60   [11:18:53.186] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/objects/maintenance.lock :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 61   [11:18:53.186] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/objects/maintenance.lock
Info 62   [11:18:53.186] Elapsed:: 0.034399986267089844ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/objects/maintenance.lock :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 63   [11:18:53.186] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/objects/maintenance.lock :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 64   [11:18:53.186] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/objects/maintenance.lock
Info 65   [11:18:53.186] Elapsed:: 0.027099967002868652ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/objects/maintenance.lock :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 66   [11:18:53.186] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2465 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 67   [11:18:53.186] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2465
Info 68   [11:18:53.186] Elapsed:: 0.03359997272491455ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2465 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 69   [11:18:53.187] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2465 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 70   [11:18:53.187] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2465
Info 71   [11:18:53.187] Elapsed:: 0.03140002489089966ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2465 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 72   [11:18:53.187] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2466 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 73   [11:18:53.187] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2466
Info 74   [11:18:53.187] Elapsed:: 0.02959996461868286ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2466 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 75   [11:18:53.187] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2466 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 76   [11:18:53.187] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2466
Info 77   [11:18:53.187] Elapsed:: 0.02379995584487915ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2466 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 78   [11:18:53.187] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2467 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 79   [11:18:53.187] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2467
Info 80   [11:18:53.188] Elapsed:: 0.04880005121231079ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2467 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 81   [11:18:53.188] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2467 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 82   [11:18:53.188] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2467
Info 83   [11:18:53.188] Elapsed:: 0.02640002965927124ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2467 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 84   [11:18:53.188] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2468 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 85   [11:18:53.188] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2468
Info 86   [11:18:53.188] Elapsed:: 0.0372999906539917ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2468 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 87   [11:18:53.188] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2468 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 88   [11:18:53.188] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2468
Info 89   [11:18:53.188] Elapsed:: 0.024100005626678467ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2468 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 90   [11:18:53.189] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2469 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 91   [11:18:53.189] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2469
Info 92   [11:18:53.189] Elapsed:: 0.033699989318847656ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2469 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 93   [11:18:53.189] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2469 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 94   [11:18:53.189] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2469
Info 95   [11:18:53.189] Elapsed:: 0.024399995803833008ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2469 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 96   [11:18:53.190] received configuration command: {"modelPath":"c:\\Users\\rasna\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.14\\cache\\1A3F919CD5B7725108B03C349630A1C82B03_4A84987F2428442A9EC84563BB2BC063"}
Info 97   [11:18:54.299] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2470 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 98   [11:18:54.299] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2470
Info 99   [11:18:54.299] Elapsed:: 0.07700002193450928ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2470 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 100  [11:18:54.301] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2470 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 101  [11:18:54.301] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2470
Info 102  [11:18:54.301] Elapsed:: 0.04519999027252197ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2470 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 103  [11:18:54.302] Host configuration update for file c:/Users/rasna/Projects/vx-doc/layout/e.tsx
Info 104  [11:18:54.303] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 105  [11:18:54.321] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 2 structureChanged: false structureIsReused:: Completely Elapsed: 18.722000002861023ms
Info 106  [11:18:54.321] Different program with same set of files
Info 107  [11:18:54.324] getCompletionData: Get current token: 0.006900012493133545
Info 108  [11:18:54.324] getCompletionData: Is inside comment: 0.01789999008178711
Info 109  [11:18:54.324] getCompletionData: Get previous token: 0.020500004291534424
Info 110  [11:18:54.327] getExportInfoMap: cache miss or empty; calculating new results
Info 111  [11:18:54.456] forEachExternalModuleToImportFrom autoImportProvider: 2.3633999824523926
Info 112  [11:18:54.456] getExportInfoMap: done in 128.7263999581337 ms
Info 113  [11:18:54.490] collectAutoImports: resolved 0 module specifiers, plus 170 ambient and 1746 from cache
Info 114  [11:18:54.490] collectAutoImports: response is incomplete
Info 115  [11:18:54.490] collectAutoImports: 34.410199999809265
Info 116  [11:18:54.490] getCompletionData: Semantic work: 166.10820001363754
Info 117  [11:18:54.538] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 46.60299998521805
Info 118  [11:18:54.656] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 119  [11:18:54.673] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 3 structureChanged: false structureIsReused:: Completely Elapsed: 17.438300013542175ms
Info 120  [11:18:54.673] Different program with same set of files
Info 121  [11:18:54.689] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 122  [11:18:54.703] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 4 structureChanged: false structureIsReused:: Completely Elapsed: 13.061299979686737ms
Info 123  [11:18:54.703] Different program with same set of files
Info 124  [11:18:54.732] getCompletionData: Get current token: 0.019500017166137695
Info 125  [11:18:54.732] getCompletionData: Is inside comment: 0.005900025367736816
Info 126  [11:18:54.732] getCompletionData: Get previous token: 0.03380000591278076
Info 127  [11:18:54.734] getCompletionData: Semantic work: 1.7985999584197998
Info 128  [11:18:54.877] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 129  [11:18:54.890] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 5 structureChanged: false structureIsReused:: Completely Elapsed: 12.767800033092499ms
Info 130  [11:18:54.890] Different program with same set of files
Info 131  [11:18:54.895] getCompletionData: Get current token: 0.004800021648406982
Info 132  [11:18:54.895] getCompletionData: Is inside comment: 0.024299979209899902
Info 133  [11:18:54.895] getCompletionData: Get previous token: 0.033699989318847656
Info 134  [11:18:54.895] getCompletionsAtPosition: isCompletionListBlocker: 0.10709995031356812
Info 135  [11:18:54.895] Returning an empty list because completion was requested in an invalid position.
Info 136  [11:18:55.505] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 137  [11:18:55.516] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 6 structureChanged: false structureIsReused:: Completely Elapsed: 10.609499990940094ms
Info 138  [11:18:55.516] Different program with same set of files
Info 139  [11:18:55.518] getCompletionData: Get current token: 0.003600001335144043
Info 140  [11:18:55.518] getCompletionData: Is inside comment: 0.019999980926513672
Info 141  [11:18:55.518] getCompletionData: Get previous token: 0.03280001878738403
Info 142  [11:18:55.518] getCompletionsAtPosition: isCompletionListBlocker: 0.09530001878738403
Info 143  [11:18:55.520] getExportInfoMap: cache hit
Err 144   [11:18:55.534] Exception on executing command {"seq":28,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":12,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 145  [11:18:55.697] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 146  [11:18:55.711] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 7 structureChanged: false structureIsReused:: Completely Elapsed: 14.694199979305267ms
Info 147  [11:18:55.711] Different program with same set of files
Info 148  [11:18:55.835] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2471 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 149  [11:18:55.835] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2471
Info 150  [11:18:55.835] Elapsed:: 0.05820000171661377ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2471 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 151  [11:18:55.835] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2471 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 152  [11:18:55.835] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2471
Info 153  [11:18:55.835] Elapsed:: 0.05610001087188721ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2471 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 154  [11:18:55.842] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2472 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 155  [11:18:55.843] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2472
Info 156  [11:18:55.843] Elapsed:: 0.05260002613067627ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2472 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 157  [11:18:55.843] DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2472 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 158  [11:18:55.843] Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Detected ignored path: c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2472
Info 159  [11:18:55.843] Elapsed:: 0.02369999885559082ms DirectoryWatcher:: Triggered with c:/users/rasna/projects/vx-doc/.git/fsmonitor--daemon/cookies/3540-2472 :: WatchInfo: c:/users/rasna/projects/vx-doc 1 undefined Config: c:/Users/rasna/Projects/vx-doc/tsconfig.json WatchType: Wild card directory
Info 160  [11:18:56.788] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 161  [11:18:56.796] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 8 structureChanged: false structureIsReused:: Completely Elapsed: 8.273599982261658ms
Info 162  [11:18:56.796] Different program with same set of files
Info 163  [11:18:56.797] getCompletionData: Get current token: 0.003600001335144043
Info 164  [11:18:56.797] getCompletionData: Is inside comment: 0.016099989414215088
Info 165  [11:18:56.797] getCompletionData: Get previous token: 0.03100001811981201
Info 166  [11:18:56.797] getCompletionsAtPosition: isCompletionListBlocker: 0.011299967765808105
Info 167  [11:18:56.799] getExportInfoMap: cache hit
Err 168   [11:18:56.804] Exception on executing command {"seq":38,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":15,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 169  [11:18:56.805] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 170  [11:18:56.816] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 9 structureChanged: false structureIsReused:: Completely Elapsed: 10.445299983024597ms
Info 171  [11:18:56.816] Different program with same set of files
Info 172  [11:18:56.866] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 173  [11:18:56.875] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 10 structureChanged: false structureIsReused:: Completely Elapsed: 8.022899985313416ms
Info 174  [11:18:56.875] Different program with same set of files
Info 175  [11:18:56.877] getCompletionData: Get current token: 0.0048999786376953125
Info 176  [11:18:56.877] getCompletionData: Is inside comment: 0.017099976539611816
Info 177  [11:18:56.877] getCompletionData: Get previous token: 0.0363999605178833
Info 178  [11:18:56.877] getCompletionsAtPosition: isCompletionListBlocker: 0.01500004529953003
Info 179  [11:18:56.878] getExportInfoMap: cache hit
Err 180   [11:18:56.882] Exception on executing command {"seq":43,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":17,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 181  [11:18:57.127] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 182  [11:18:57.137] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 11 structureChanged: false structureIsReused:: Completely Elapsed: 10.838799953460693ms
Info 183  [11:18:57.137] Different program with same set of files
Info 184  [11:18:57.140] getCompletionData: Get current token: 0.004400014877319336
Info 185  [11:18:57.140] getCompletionData: Is inside comment: 0.016099989414215088
Info 186  [11:18:57.140] getCompletionData: Get previous token: 0.0294000506401062
Info 187  [11:18:57.140] getCompletionsAtPosition: isCompletionListBlocker: 0.009999990463256836
Info 188  [11:18:57.141] getExportInfoMap: cache hit
Err 189   [11:18:57.145] Exception on executing command {"seq":46,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":18,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 190  [11:18:57.226] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 191  [11:18:57.234] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 12 structureChanged: false structureIsReused:: Completely Elapsed: 8.007700026035309ms
Info 192  [11:18:57.234] Different program with same set of files
Info 193  [11:18:57.237] getCompletionData: Get current token: 0.0037000179290771484
Info 194  [11:18:57.237] getCompletionData: Is inside comment: 0.016299962997436523
Info 195  [11:18:57.237] getCompletionData: Get previous token: 0.030099987983703613
Info 196  [11:18:57.237] getCompletionsAtPosition: isCompletionListBlocker: 0.00839996337890625
Info 197  [11:18:57.238] getExportInfoMap: cache hit
Err 198   [11:18:57.242] Exception on executing command {"seq":49,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":19,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 199  [11:18:57.351] Starting updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json
Info 200  [11:18:57.359] Finishing updateGraphWorker: Project: c:/Users/rasna/Projects/vx-doc/tsconfig.json Version: 13 structureChanged: false structureIsReused:: Completely Elapsed: 7.6983999609947205ms
Info 201  [11:18:57.359] Different program with same set of files
Info 202  [11:18:57.361] getCompletionData: Get current token: 0.004100024700164795
Info 203  [11:18:57.361] getCompletionData: Is inside comment: 0.017199993133544922
Info 204  [11:18:57.361] getCompletionData: Get previous token: 0.029799997806549072
Info 205  [11:18:57.361] getCompletionsAtPosition: isCompletionListBlocker: 0.009400010108947754
Info 206  [11:18:57.364] getExportInfoMap: cache hit
Err 207   [11:18:57.367] Exception on executing command {"seq":52,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":20,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Info 208  [11:18:58.343] getCompletionData: Get current token: 0.004199981689453125
Info 209  [11:18:58.343] getCompletionData: Is inside comment: 0.017099976539611816
Info 210  [11:18:58.344] getCompletionData: Get previous token: 0.030900001525878906
Info 211  [11:18:58.344] getCompletionsAtPosition: isCompletionListBlocker: 0.012099981307983398
Info 212  [11:18:58.345] getExportInfoMap: cache hit
Err 213   [11:18:58.346] Exception on executing command {"seq":54,"type":"request","command":"completionInfo","arguments":{"file":"c:/Users/rasna/Projects/vx-doc/layout/e.tsx","line":1,"offset":20,"includeExternalModuleExports":true,"includeInsertTextCompletions":true}}:

    Debug Failure.

    Error: Debug Failure.
        at rehydrateCachedInfo (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123469:66)
        at Array.map (<anonymous>)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123414:33
        at Map.forEach (<anonymous>)
        at Object.forEach (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:123412:28)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127107:32
        at resolvingModuleSpecifiers (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125728:26)
        at collectAutoImports (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127106:17)
        at getGlobalCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:127018:17)
        at tryGetGlobalSymbols (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126924:25)
        at getCompletionData (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:126696:22)
        at Object.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:125793:34)
        at Proxy.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:156521:35)
        at Proxy.<anonymous> (c:\Users\rasna\.vscode\extensions\jpoissonnier.vscode-styled-components-1.6.6\node_modules\typescript-template-language-service-decorator\lib\template-language-service-decorator.js:84:24)
        at c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:3222
        at Object.l.getCompletionsAtPosition (c:\Users\rasna\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:2:8139)
        at IOSession.Session.getCompletions (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:167965:64)
        at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:166812:61)
        at c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:88
        at IOSession.Session.executeWithRequestId (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168605:28)
        at IOSession.Session.executeCommand (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168614:33)
        at IOSession.Session.onMessage (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:168640:35)
        at Interface.<anonymous> (c:\Users\rasna\.vscode\extensions\ms-vscode.vscode-typescript-next-4.4.20210726\node_modules\typescript\lib\tsserver.js:171239:31)
        at Interface.emit (events.js:315:20)
        at Interface._onLine (readline.js:337:10)
        at Interface._normalWrite (readline.js:482:12)
        at Socket.ondata (readline.js:194:10)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #45101, fixes #45200.

### CODE REVIEW

File: src/services/exportInfoMap.ts [hunk 1]
```diff
@@ -160,12 +168,10 @@ namespace ts {
...
                 ? checker.getMergedSymbol(info.moduleFile.symbol)
                 : checker.tryFindAmbientModule(info.moduleName));
-            const symbolName = exportKind === ExportKind.Default
-                ? InternalSymbolName.Default
-                : info.symbolName;
             const symbol = info.symbol || cachedSymbol || Debug.checkDefined(exportKind === ExportKind.ExportEquals
                 ? checker.resolveExternalModuleSymbol(moduleSymbol)
-                : checker.tryGetMemberInModuleExportsAndProperties(symbolName, moduleSymbol));
+                : checker.tryGetMemberInModuleExportsAndProperties(unescapeLeadingUnderscores(info.symbolTableKey), moduleSymbol),
+                `Could not find symbol '${info.symbolName}' by key '${info.symbolTableKey}' in module ${moduleSymbol.name}`);
```
Comment (andrewbranch) [inline src/services/exportInfoMap.ts:174]: Double checking with @amcasey that this is ok to put in an error message. `info.symbolName` may be a variable name written by a user and `moduleSymbol.name` may be most of a file path. This info will help discover a repro if a user sees it in their TS Server log and can share it.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3530,6 +3531,24 @@ namespace ts {
...
+                if (!isReservedMemberName(key)) {
+                    cb(symbol, key);
+                }
+            });
+            const exportEquals = resolveExternalModuleSymbol(moduleSymbol);
+            if (exportEquals !== moduleSymbol) {
+                const type = getTypeOfSymbol(exportEquals);
+                if (shouldTreatPropertiesOfExternalModuleAsExports(type)) {
+                    getPropertiesOfType(type).forEach(symbol => {
+                        cb(symbol, symbol.escapedName);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:3546]: I would have had to refactor or duplicate a lot of checker code to get the actual map key of `symbol.members` here, so I’m _hoping_ that the map key for a _property_ is always `symbol.escapedName`, which is not always true for an _export_. I added a debug assertion here while running tests and it never triggered, but I don’t want to leave it in production code because this is an extremely hot path (can easily hit tens of thousands of times while building a large export info map).

**Comment by andrewbranch** [comment]
@typescript-bot pack this

File: src/services/exportInfoMap.ts (hunk 1 above)
Comment (amcasey) [reply src/services/exportInfoMap.ts:174]: Obviously, the less customer content, the better but, as we've discussed, we have reason to believe this will be broadly useful and the telemetry for the resulting exception will be sanitized appropriately.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
Confirmed this fixes #45200

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -3289,6 +3289,10 @@ namespace ts {
         return startsWith(symbol.escapedName as string, "__@");
     }
 
+    export function isPrivateIdentifierSymbol(symbol: Symbol): boolean {
```
Comment (sandersn) [inline src/compiler/utilities.ts:3292]: hmm. I had to figure this out recently and I thought the Right Way was `symbol.valueDeclaration?.kind === SyntaxKind.PrivateIdentifier` or something similar. But I guess this way works too.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:3546]: What's the penalty for providing the wrong key in this PR?

**Review by sandersn — COMMENTED** [review]
As far as I understand auto imports/module exports, this seems like an improvement. I have a question about what happens if the key isn't `symbol.escapedName`.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/utilities.ts:3292]: I would readily believe, or at least hope, that those are equivalent, but this implementation gets to the core of what went wrong in the linked crash. You cannot ask for a name starting with `__#` in `checker.tryGetInModuleExportsAndProperties` and expect to get the private identifier symbol it came from back out, because the checker will underscore-escape that string and try to find a property whose _actual name_ starts with `__#`.

**Review by sandersn — APPROVED** [review]
