### PR TITLE
[Experiment] feat(47558): Warning 6133 ignores @link tags

### LINKED ISSUE #47558: Warning 6133 ignores @link tags
# Bug Report

### 🔎 Search Terms

* "@link"
* is declared but its value is never read. (6133)

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3. The problem  concerns the `@link` tag, which was introduced in version 4.3.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5&multiFile=true#code/PTAEAEDMEsBsFMB2BDAtvAXKA7gC3vLAHQAuAzgFAUigAqu0Zos0i8ouyTJ+OyATolYBzUACIA5AGEBE0I1AATeAGNYA+ItAAjAK4l55UADdksXewVtj8fqH7xkiogAoAbAEYAzF4CUY6jB4G0RQHgB7XWFcAwADGX5Y+SYHSFskFU0dAE8w3nAWRABrMORhIgpoVAAHcP4DEmzq9gBvUATQAF9QSH5w1FAJImAVWQBuKmAAKinQAEEcfEIeutBdMnZsaB5QZFAWgtYShM6iUCngCngAD1r6+UQSW0hkTNAAdSXYfYpQUBoiICKJ1JmAoHAkGhMKBRvxSJQrrc6gZWE9+C83h0Wr9-mBARUQUA)

### 💻 Code

```ts
// @filename: wheel.ts

import type { Car } from './car';

/** A wheel for use with a {@link Car}. */
export interface Wheel {
  // ...
}

// @filename: car.ts

export interface Car {
  // ...
}
```

### 🙁 Actual behavior

The line `import type { Car } from './car';` has the following compiler warning:

> 'Car' is declared but its value is never read. (6133)

### 🙂 Expected behavior

There should be no compiler warning for the type import. The purpose of this warning is to indicate superfluous imports, and this type import isn't superfluous: It is required for the `@link` tag to work property.

Without the type import, TypeScript could not resolve the target of the link. As a result, the tooltip in VS code would contain the `Car` reference in plain text rather than as a link.

Compare the following screenshots:

*With type import:*

*Without type import:*

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47558

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -36284,6 +36290,15 @@ namespace ts {
             }
         }
 
+        function markJSDocLinkNameAsReferenced(name: EntityName | JSDocMemberName) {
+            if (isEntityName(name)) {
+                resolveEntityName(name, SymbolFlags.Type | SymbolFlags.Namespace | SymbolFlags.Value, /*ignoreErrors*/ true, /*dontResolveAlias*/ true);
```
Comment (sandersn) [inline src/compiler/checker.ts:36295]: for the non-experimental version of this, `resolveEntityName` will need to add the ad-hoc lookup semantics from resolveJSDocMemberName. I'm not sure what this will mean for supporting the syntax `Class#method`.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:36295]: > I'm not sure what this will mean for supporting the syntax Class#method

Do we need to set `isReferenced` on both `Class` and `method`? Or will only `Class` be sufficient? 

> for the non-experimental version of this, resolveEntityName will need to add the ad-hoc lookup semantics from resolveJSDocMemberName.

Do I need to use `resolveJSDocMemberName` directly in `resolveEntityName`? I used `resolveEntityName` for two reasons: 1. I think we can skip resolving `"prototype"` for this case (it looks like ts doesn't handle unused prototype members), 2. Second reason related to the first one is `ignoreErrors`, extending `resolveJSDocMemberName` with new argument `ignoreErrors ` and keep checking `"prototype"` seems useless. What do you think?

Comment (sandersn) [reply src/compiler/checker.ts:36295]: > Do we need to set isReferenced on both Class and method? Or will only Class be sufficient?

I'm pretty sure `Class` will be sufficient although I could be wrong.

> Do I need to use resolveJSDocMemberName directly in resolveEntityName?

I think it might actually be the other way around, because after I think about it, I don't want the `@link` resolution rules to apply anywhere else. So the call you added to `resolveEntityName` should probably turn into a call to `resolveJSDocMemberName`, which itself will call `resolveEntityName`.
However, it may need some improvement to work right in that location. I don't have all the details of that code in my head, I just remember that it was pretty ad-hoc.

File: tests/cases/conformance/jsdoc/jsdocLinkTag2.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+// @target: esnext
+// @noEmit: true
+
+// @filename: /a.js
+export class A {}
+
+// @filename: /b.js
+import { A } from "./a";
+
+/** {@link A} */
```
Comment (sandersn) [inline tests/cases/conformance/jsdoc/jsdocLinkTag2.ts:13]: what happens with bad references? Are those errors now? We need some tests of that -- or there might already be some.

**Review by sandersn — CHANGES_REQUESTED** [review]
I think this does the right thing, but I'd like some tests to show that we don't start issuing errors on unresolved links.

File: tests/cases/conformance/jsdoc/jsdocLinkTag2.ts (hunk 2 above)
Comment (a-tarasyuk) [reply tests/cases/conformance/jsdoc/jsdocLinkTag2.ts:13]: @sandersn I've added this [test](https://github.com/microsoft/TypeScript/blob/c46a01d38bf5c73890785a2ce43d3b3debb7739d/tests/cases/conformance/jsdoc/jsdocLinkTag5.ts) with unresolved link. With unresolved links, errors will be [ignored](https://github.com/microsoft/TypeScript/pull/47822/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R36960)

**Review by sandersn — APPROVED** [review]
