### PR TITLE
Transform nested dynamic imports

### LINKED ISSUE #18982: Nested dynamic import statements in async functions are not transpiled correctly
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// @skipLibCheck: true
// @lib: es6
// @filename: foo.ts
export default "./foo";

// @filename: index.ts
async function foo() {
    return await import((await import("./foo")).default);
}
```

**Expected behavior:**
Functional output containing no `import` keyword.

**Actual behavior:**
```js
function foo() {
    return __awaiter(this, void 0, void 0, function () {
        var _a;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0:
                    _a = (import); // This is wrong
                    return [4 /*yield*/, Promise.resolve().then(function () { return require("./foo"); })];
                case 1: return [4 /*yield*/, _a.apply(void 0, [(_b.sent())["default"]])];
                case 2: return [2 /*return*/, _b.sent()];
            }
        });
    });
}
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #18982

There was both a bug in the `module` and `system` transforms where the argument for an import call when unvisited; then there was also a bug in the `generators` transform which heartlessly ripped apart poor import call expressions like such a common call expression (producing invalid syntax), then there was also an issue where the UMD module emit was duplicating expression trees in its output - which is potentially safe (since only one branch is ever executed), but incredibly verbose. (Feedback on the contents of `isSimpleCopiableExpression` would be much appreciated)

With this PR, all these of these things are fixed.

### CODE REVIEW

File: src/compiler/transformers/generators.ts [hunk 1]
```diff
@@ -1124,6 +1124,18 @@ namespace ts {
                 //  .mark resumeLabel
                 //      _b.apply(_a, _c.concat([%sent%, 2]));
 
+                // The `ImportCall` Expression isn't really a call expression, and the import keyword cannot be removed from its arguments
```
Comment (rbuckton) [inline src/compiler/transformers/generators.ts]: The generators transform was written to expect only ES5-compatible code in a function body. However, we moved the module transformer to the end of the transformation pipeline, which is where `import` is handled. I'm ok with this change, though I wonder what the effect of moving generators (but not the es2015 transform) after the module transformer...

File: src/compiler/transformers/generators.ts [hunk 2]
```diff
@@ -1124,6 +1124,18 @@ namespace ts {
                 //  .mark resumeLabel
                 //      _b.apply(_a, _c.concat([%sent%, 2]));
 
+                // The `ImportCall` Expression isn't really a call expression, and the import keyword cannot be removed from its arguments
+                if (isImportCall(node)) {
+                    const elements = visitElements(node.arguments);
+                    Debug.assert(elements.kind === SyntaxKind.ArrayLiteralExpression);
+                    // Import call should always have one argument
```
Comment (rbuckton) [inline src/compiler/transformers/generators.ts]: This should be an assert. Also, do we need to visit the other elements if we are just going to drop them?

File: src/compiler/transformers/generators.ts [hunk 3]
```diff
@@ -1124,6 +1124,18 @@ namespace ts {
...
 
+                // The `ImportCall` Expression isn't really a call expression, and the import keyword cannot be removed from its arguments
+                if (isImportCall(node)) {
+                    const elements = visitElements(node.arguments);
+                    Debug.assert(elements.kind === SyntaxKind.ArrayLiteralExpression);
+                    // Import call should always have one argument
+                    const firstExpression = (elements as ArrayLiteralExpression).elements[0];
+                    return setOriginalNode(createCall(
+                        node.expression,
+                        node.typeArguments,
```
Comment (rbuckton) [inline src/compiler/transformers/generators.ts]: Type arguments should probably be `undefined`.

File: src/compiler/transformers/module/module.ts [hunk 4]
```diff
@@ -519,18 +520,22 @@ namespace ts {
         }
 
         function visitImportCallExpression(node: ImportCall): Expression {
+            let argument = node.arguments && node.arguments[0];
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: `firstOrUndefined(node.arguments)`

File: src/compiler/transformers/module/module.ts [hunk 5]
```diff
@@ -519,18 +520,22 @@ namespace ts {
         }
 
         function visitImportCallExpression(node: ImportCall): Expression {
+            let argument = node.arguments && node.arguments[0];
+            if (argument) {
+                argument = visitNode(argument, importCallExpressionVisitor);
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: `visitNode` does an `undefined` check for you. No sense in doing it twice.

File: src/compiler/transformers/utilities.ts [hunk 6]
```diff
@@ -178,4 +178,12 @@ namespace ts {
         }
         return values;
     }
+
+    export function isSimpleCopiableExpression(expression: Expression) {
```
Comment (rbuckton) [inline src/compiler/transformers/utilities.ts]: Document this. The name of the function is to general compared to its purpose.

File: src/compiler/transformers/module/module.ts [hunk 7]
```diff
@@ -545,14 +550,24 @@ namespace ts {
             //          : new Promise(function (_a, _b) { require([x], _a, _b); }); /*Amd Require*/
             // });
             needUMDDynamicImportHelper = true;
-            return createConditional(
-                /*condition*/ createIdentifier("__syncRequire"),
-                /*whenTrue*/ transformImportCallExpressionCommonJS(node),
-                /*whenFalse*/ transformImportCallExpressionAMD(node)
-            );
+            if (isSimpleCopiableExpression(arg)) {
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: Its generally safer to _always_ clone (or cache in a temp at runtime) an expression that is used more than once, unless that expression is a `GeneratedIdentifier`.

File: src/compiler/transformers/module/system.ts [hunk 8]
```diff
@@ -1495,7 +1495,7 @@ namespace ts {
                     createIdentifier("import")
                 ),
                 /*typeArguments*/ undefined,
-                node.arguments
+                node.arguments && node.arguments.length ? [visitNode(node.arguments[0], destructuringAndImportCallVisitor)] : []
```
Comment (rbuckton) [inline src/compiler/transformers/module/system.ts]: `some(node.arguments)`

File: src/compiler/transformers/generators.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/transformers/generators.ts]: It's not an assert because we parse more than one argument for error reporting reasons (and keep them around in the tree) - we just ignore any arguments after the first.

Comment (weswigham) [reply src/compiler/transformers/generators.ts]: And I'm using `visitElements` since it handles local declarations and such potentially required for the argument - recurring into `visitor` directly doesn't do enough :(

Is it worth making a copy of `visitElements` which only visites a single element?

Comment (rbuckton) [reply src/compiler/transformers/generators.ts]: `visitElements` is only necessary in `visitCallExpression` because we are passing the output into `Function.prototype.apply`. This is because we capture the target for cases like: `foo(await replaceFooAsync())` where `replaceFooAsync` might replace the value of `foo` at runtime. Since you can't cache `import`, you are probably fine with just calling `visitNode` on the argument and recreating the import call with the result.

File: src/compiler/transformers/module/module.ts [hunk 9]
```diff
@@ -545,14 +547,24 @@ namespace ts {
...
-            return createConditional(
-                /*condition*/ createIdentifier("__syncRequire"),
-                /*whenTrue*/ transformImportCallExpressionCommonJS(node),
-                /*whenFalse*/ transformImportCallExpressionAMD(node)
-            );
+            if (isSimpleCopiableExpression(arg)) {
+                return createConditional(
+                    /*condition*/ createIdentifier("__syncRequire"),
+                    /*whenTrue*/ createImportCallExpressionCommonJS(arg),
+                    /*whenFalse*/ createImportCallExpressionAMD(isGeneratedIdentifier(arg) ? arg : getSynthesizedClone(arg)) // TODO (weswigham): Use getSynthesizedDeepClone instead of getSynthesizedClone once #18979 is merged
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: I wouldn't use `getDeepSynthesizedClone` for this. Any property-access can have side-effects.

File: src/compiler/transformers/utilities.ts [hunk 10]
```diff
@@ -178,4 +178,17 @@ namespace ts {
...
+     * Used in the module transformer to check if an expression is reasonably without sideeffect,
+     *  and thus better to copy into multiple places rather than to cache in a temporary variable
+     *  - this is mostly subjective beyond the requirement that the expression not be sideeffecting
+     */
+    export function isSimpleCopiableExpression(expression: Expression) {
+        return expression.kind === SyntaxKind.StringLiteral ||
+            expression.kind === SyntaxKind.NumericLiteral ||
+            expression.kind === SyntaxKind.NoSubstitutionTemplateLiteral ||
+            isKeyword(expression.kind) ||
+            isEntityNameExpression(expression);
```
Comment (rbuckton) [inline src/compiler/transformers/utilities.ts]: Any property access can have side effects. I would only recommend reusing something that is a `PrimaryExpression` (e.g. not property-access/entity name).

File: tests/baselines/reference/importCallExpressionAsyncES3UMD.js [hunk 11]
```diff
@@ -82,7 +82,7 @@ var __generator = (this && this.__generator) || function (thisArg, body) {
             var req;
             return __generator(this, function (_a) {
                 switch (_a.label) {
-                    case 0: return [4 /*yield*/, __syncRequire ? Promise.resolve().then(function () { return require('./test'); }) : new Promise(function (resolve_1, reject_1) { require(['./test'], resolve_1, reject_1); })]; // ONE
+                    case 0: return [4 /*yield*/, __syncRequire ? Promise.resolve().then(function () { return require('./test'); }) : new Promise(function (resolve_1, reject_1) { require(["./test"], resolve_1, reject_1); })]; // ONE
```
Comment (rbuckton) [inline tests/baselines/reference/importCallExpressionAsyncES3UMD.js]: The quote character changed here.

File: src/compiler/transformers/module/module.ts (hunk 9 above)
Comment (rbuckton) [reply src/compiler/transformers/module/module.ts]: Also, while calling `getSynthesizedClone` is correct, when `arg` is a string literal with single quotes, this results in a string literal with double quotes which you can see in the test result below. Generally we try to preserve the quote style, and you can achieve that by calling `setTextRange` on the clone. To avoid duplicating comments you can also call `setNodeEmitFlags(..., NodeEmitFlags.NoComments)`

File: src/compiler/transformers/generators.ts (hunk 2 above)
Comment (rbuckton) [reply src/compiler/transformers/generators.ts]: Actually, all you need to do is change line 1115 (https://github.com/Microsoft/TypeScript/pull/18998/files/5d5fa0d49afb9a4c3b36ed48c8961a10b7eaed6e#diff-7c8a35e1da8c32e5aa5fd22d015c443dR1115) to be `if (!isImportCall(node) && forEach(...)` and let the default behavior of `visitEachChild` below do all the work for you.

File: src/compiler/transformers/utilities.ts (hunk 10 above)
Comment (weswigham) [reply src/compiler/transformers/utilities.ts]: Teeeeeechnically even accessing an `Identifier` can have sideeffects within the context of a `with` statement. I get where you're coming from and will dial it back to just `Identifier`, though. The relevant bits of primary expression are all here, and there is not a `isPrimaryExpression` (and if there were, it'd include parenthesized expressions and object/array literals), so this is about as good as it gets.

File: src/compiler/transformers/module/module.ts (hunk 9 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: Done

**Comment by weswigham** [comment]
@rbuckton merged with master. Anymore changes needed?

File: src/compiler/transformers/module/module.ts [hunk 12]
```diff
@@ -545,14 +548,28 @@ namespace ts {
...
             needUMDDynamicImportHelper = true;
-            return createConditional(
-                /*condition*/ createIdentifier("__syncRequire"),
-                /*whenTrue*/ transformImportCallExpressionCommonJS(node),
-                /*whenFalse*/ transformImportCallExpressionAMD(node)
-            );
+            if (isSimpleCopiableExpression(arg)) {
+                const argClone = isGeneratedIdentifier(arg) ? arg : setEmitFlags(setTextRange(getSynthesizedClone(arg), arg), EmitFlags.NoComments);
+                if (argClone.kind === SyntaxKind.StringLiteral && typeof (argClone as StringLiteral).singleQuote === "undefined") {
+                    (argClone as StringLiteral).singleQuote = getSourceTextOfNodeFromSourceFile(currentSourceFile, arg).charCodeAt(0) === CharacterCodes.singleQuote;
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: You can use `createLiteral(arg)` if `arg` is a string literal and it will create a fresh literal that gets its content from the provided literal.

Alternatively, we should consider just setting `singleQuote` when we parse a string literal...

File: src/compiler/transformers/module/module.ts [hunk 13]
```diff
@@ -593,27 +610,29 @@ namespace ts {
                     /*typeParameters*/ undefined,
                     parameters,
                     /*type*/ undefined,
+
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: excess whitespace

File: src/compiler/transformers/module/module.ts (hunk 12 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: I want to keep using `getSynthesizedClone` since `undefined`, `null`, `Infinity`, and other identifiers/keywords are valid here.

We really should consider setting the singleQuote bit on all string literals...

File: src/compiler/transformers/module/module.ts (hunk 13 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: @rbuckton done.

File: src/compiler/transformers/generators.ts [hunk 14]
```diff
@@ -1124,6 +1124,18 @@ namespace ts {
                 //  .mark resumeLabel
                 //      _b.apply(_a, _c.concat([%sent%, 2]));
 
+                // The `ImportCall` Expression isn't really a call expression, and the import keyword cannot be removed from its arguments
+                if (isImportCall(node)) {
```
Comment (rbuckton) [inline src/compiler/transformers/generators.ts]: I don't think https://github.com/Microsoft/TypeScript/pull/18998#discussion_r143319421 was addressed successfully:
> Actually, all you need to do is change line 1115 (https://github.com/Microsoft/TypeScript/pull/18998/files/5d5fa0d49afb9a4c3b36ed48c8961a10b7eaed6e#diff-7c8a35e1da8c32e5aa5fd22d015c443dR1115) to be `if (!isImportCall(node) && forEach(...)` and let the default behavior of `visitEachChild` below do all the work for you.

File: src/compiler/transformers/module/module.ts (hunk 12 above)
Comment (rbuckton) [reply src/compiler/transformers/module/module.ts]: I understand that for non-string-literals, but as I said above: "you can use `createLiteral(arg)` if `arg` is a **string literal**". That will return a fresh string literal, but its source text is pulled from the original string literal when printed.

Basically:

```ts
const argClone = isGeneratedIdentifier(arg) ? arg :
    isStringLiteral(arg) ? createLiteral(arg) :
    setEmitFlags(setTextRange(getSynthesizedClone(arg), arg), EmitFlags.NoComments);
```

File: src/compiler/transformers/generators.ts (hunk 14 above)
Comment (weswigham) [reply src/compiler/transformers/generators.ts]: Ah! You're right! (For some reason I thought this comment was on one of the other import call PRs.) Got it!

File: src/compiler/transformers/module/module.ts (hunk 12 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: Oh, instead of inspecting the content here! Understood, will do.

**Comment by weswigham** [comment]
@rbuckton Sorry about that, got 'em.

File: tests/baselines/reference/asyncImportNestedYield.errors.txt [hunk 15]
```diff
@@ -0,0 +1,16 @@
+error TS2318: Cannot find global type 'AsyncIterableIterator'.
```
Comment (rbuckton) [inline tests/baselines/reference/asyncImportNestedYield.errors.txt]: I'd fix the errors since they're not relevant to the test, then this looks good.
