### PR TITLE
CommonJS imports support destructuring+property access

### LINKED ISSUE #40578: Commonjs import with destructuring ignores trailing property access
Discovered in https://github.com/prettier/prettier/pull/9207, where @brodybits is investigating whether #40143 works.

```js
// @filename: mod1.js
var o = {
    concat() { }
}
exports.builders = o
// @filename: test.js
const { concat } = require('./mod1').builders;
```

**Expected behavior:**

`concat: () => void`

**Actual behavior:**

Error: module "mod1" has no exported member 'concat'.

Looks like we miss the trailing property access and don't fall back to the faked import type.

### PR DESCRIPTION
**Pull request by sandersn**
CommonJS imports now support destructuring a require that is part of a property access expression:

```js
const { x } = require('m').o
```

Previously either worked alone but not together:

```js
const o = require('m').o
```

```js
const { o } = require('m')
```

Fixes #40578 for prettier; I didn't think anybody did this, so I let the tests fail earlier. Turns out prettier does!

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2682,10 +2691,14 @@ namespace ts {
                     else {
                         symbolFromVariable = getPropertyOfVariable(targetSymbol, name.escapedText);
                     }
-
                     // if symbolFromVariable is export - get its final target
                     symbolFromVariable = resolveSymbol(symbolFromVariable, dontResolveAlias);
-                    let symbolFromModule = getExportOfModule(targetSymbol, specifier, dontResolveAlias);
+
+                    const commonJSPropertyAccess = getCommonJSPropertyAccess(node);
```
Comment (weswigham) [inline src/compiler/checker.ts:2697]: Shouldn't all this work be under `getTargetOfAliasDeclaration` (which `resolveSymbol` eventually calls out to), and not in `getExternalModuleMember` directly?

Comment (sandersn) [reply src/compiler/checker.ts:2697]: in the test case below, resolveSymbol is called first on the BindingElement `a`, which goes to getTargetOfImportSpecifier. Do you mean that function? I put the code in getExternalModuleMember because it seemed similar to the `export=` code above, and because `getExternalModuleMember` is called several places.

But looking again, it's only two other places, both exports where this wouldn't apply.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2773,11 +2770,23 @@ namespace ts {
...
+            const name = node.propertyName || node.name;
+            if (commonJSPropertyAccess && resolved && isIdentifier(name)) {
+                return getPropertyOfType(getTypeOfSymbol(resolved), name.escapedText);
+            }
             markSymbolOfAliasDeclarationIfTypeOnly(node, /*immediateTarget*/ undefined, resolved, /*overwriteEmpty*/ false);
             return resolved;
         }
 
+        function getCommonJSPropertyAccess(node: Node) {
+            if(isVariableDeclaration(node) && node.initializer && isPropertyAccessExpression(node.initializer)) {
```
Comment (weswigham) [inline src/compiler/checker.ts:2785]:
```suggestion
            if (isVariableDeclaration(node) && node.initializer && isPropertyAccessExpression(node.initializer)) {

```

**Review by weswigham — APPROVED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts:2785]: I tried to commit your suggestion directly but github kept claiming the PR was recently updated =(

**Comment by ExE-Boss** [comment]
**Fun fact:** This is also what **Node** recommends for using the `*.promises` namespaced APIs before **Node v15**, which added a large number of `*/promises` alias modules.
