### PR TITLE
Check for parse errors in emitted JS

### LINKED ISSUE #2818: Add a step to verify the JS emitted by the tests is valid
... to prevent tests with broken emit getting checked in, like the original one in https://github.com/Microsoft/TypeScript/commit/55af7b3#diff-5a553969b7d75b3baab89d60e61bcd5b.

Running the output will require too much effort in the test as well as setting up the environment, so I think only parsing is feasible. It'd require a parser that understands ES6, or perhaps the TS parser itself (with the risk of not noticing bugs that also affect the parser.)

It would also require some way of marking tests as "expected to emit valid JS regardless of type errors", since the presence of a .errors.txt doesn't indicate whether the errors are of syntax or type.

### PR DESCRIPTION
**Pull request by weswigham**
(When the input is error-free)

Fixes #2818

We have two tests which produce output JS with errors, which probably indicate bugs which need fixing.

There is a small cost to doing this validation, but not too much in aggregate since our parser is fast - only about 5% longer test times. (ofc, if a test is marked `@noEmit: true` we won't be doing it for that test - so tests where the emit doesn't matter should probably use that option more aggressively). And it already found some bugs, so clearly it is a good thing to check.

### CODE REVIEW

File: tests/baselines/reference/emitBOM.js [hunk 1]
```diff
@@ -2,10 +2,18 @@
...
-var x;
-//# sourceMappingURL=emitBOM.js.map
+tests/cases/compiler/emitBOM.js(1,2): error TS1127: Invalid character.
+tests/cases/compiler/emitBOM.js(1,3): error TS1127: Invalid character.
+
+
+==== tests/cases/compiler/emitBOM.js (2 errors) ====
+    ï»¿// JS and d.ts output should have a BOM but not the sourcemap
+     
+!!! error TS1127: Invalid character.
```
Comment (weswigham) [inline tests/baselines/reference/emitBOM.js]: @rbuckton you know what's up with the BOM here? I suspect it's actually an issue with the test harness not roundtripping the BOM correctly (maybe by not reading the output string with the correct encoding) and not a parse/emit bug, but I can't be sure.

**Comment by weswigham** [comment]
I've merged this so we catch future failure-to-roundtrip bugs. I still don't know what's up with that BOM roundtrip, though.
