### PR TITLE
Make `never` inferences with template literal types only in special cases

### LINKED ISSUE #45906: Type parameter in template literal type is inferred as never
# Bug Report

### 🔎 Search Terms

Template Literal Type
Default Value of Generic
Property Chain

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____Template Literay Type_____

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&noLib=true&jsx=0&module=1&isolatedModules=false&allowSyntheticDefaultImports=true&keyofStringsOnly=true&ts=4.3.5#code/C4TwDgpgBAygxgCwgWwIZQLxQN4FgBQURUqAXDgcVVAEbl6HVNzkB2ArsjRAE6VNQAvvyLD8YggDN2rOMACWAe1ZREqeawA8AMSgQAHsAisAJgGcoAawghFk2IhTosMkxEkaIJgDRRtARj1DY3MrGzsHJDQAbW0AXUwoV3dPHz8AJiCjUwtrW3t4KNRYuNj-BJdTFNYvKAA+AAoPCAAbE3JdAB8oAAMAEmxtQQA6AYDBHqhu-sGRsf85wfSJgEoKfAIxaVkFZVUEdVZ0nSyQ3PCCxzRE5I8atIDTnLD8yKcSm6q7r19tTINsqE8hFCu94mUKkkvql6k15K12n5fJJ-AB+Dr+ZHpdEZNYMTYEAhqDQNABEqFJKyJBxJ5OGNEpUAA9EyMlAAObGXjyOBQeQWDSSXi1VAWGoAN14vho7GAfLl-KCkDktWAilo0FuqWphzJqHpwzglMJ+GJRz1xtNNPN5NJvlJDLWLLZiq19xIFgMyqMJh1GnSFvtDPtRpWQA)

### 🙁 Actual behavior
1. `F, F1, F2` in function `chain` is infered wrongly as `never, never, never` when only first level property `field` is passed
2. `F2` in function `chain("a.b")` is infered as `never`

### 🙂 Expected behavior
1. `F` in function `chain` is infered correctly as `"a", undefined, undefined` when only one argument `field` is passed
2. `F2` in function `chain("a.b")` is infered as `undefined`

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #45906.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21890,8 +21890,16 @@ namespace ts {
...
                 const matches = inferTypesFromTemplateLiteralType(source, target);
                 const types = target.types;
-                for (let i = 0; i < types.length; i++) {
-                    inferFromTypes(matches ? matches[i] : neverType, types[i]);
+                // When the target template literal contains only placeholders (meaning that inference is intended to extract
+                // single characters and remainder strings) and inference fails to produce matches, we want to infer 'never' for
+                // each placeholder such that instantiation with the inferred value(s) produces 'never', a type for which an
+                // assignment check will fail. If we make no inferences, we'll likely end up with the constraint 'string' which,
+                // upon instantiation, would collapse all the placeholders to just 'string', an an assignment check wouldn't
+                // fail. That would be a pointless and confusing outcome.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:21898]:
```suggestion
                // upon instantiation, would collapse all the placeholders to just 'string', and an assignment check might
                // succeed. That would be a pointless and confusing outcome.
```

**Review by DanielRosenwasser — APPROVED** [review]
