### PR TITLE
Fix #8162 and #8173: Add root symbols to search in find all referecnes

### LINKED ISSUE #8162: "Find all references" is broken for overriding in sub class [visual studio 2015 update 2]
Repro code. It used to work fine in vs2013.

```ts
class A {
    a = 1;
}
class B extends A {
    a = 2; // rename B.a does not rename A.a
}
```

### LINKED ISSUE #8173: Find references on overloaded/abstract class method
It would be nice for "Find references" to also report usages of the overloads / implementations of the base method.

Example:
```ts
abstract class Base {
    abstract someMethod(): void; // <-- find references here should also find MyClass#someMethod
}

class MyClass extends Base {
    someMethod() {
        alert('test");
    }
}
```

EDIT: This is also a problem with refactoring (method rename) since it would rename the base class method, but not the overrides in the child classes.

### PR DESCRIPTION
**Pull request by mhegazy**
This is a regression caused by the polymorphic this type, since all classes are now generic. Make sure to include the target symbols of any symbols we get to the search.

Fixes #8162 
Fixes #8173

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -6286,7 +6286,7 @@ namespace ts {
                         if (type) {
                             const propertySymbol = typeChecker.getPropertyOfType(type, propertyName);
                             if (propertySymbol) {
-                                result.push(propertySymbol);
+                                result.push(...typeChecker.getRootSymbols(propertySymbol));
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: I thought we were avoiding this pattern because there can often be many elements in the list - though I guess in practice this probably doesn't come up all that often.

**Comment by DanielRosenwasser** [comment]
So this was a regression that we knew was there when we added `this` types, but didn't follow up on with an issue? We need to be more careful in the future.

:+1:

**Comment by mhegazy** [comment]
> So this was a regression that we knew was there when we added this types, but didn't follow up on with an issue?

No. i do not think we knew about it.
