### PR TITLE
Set impliedNodeFormat on sourceFile we get from host to ensure the field is set correctly

### LINKED ISSUE #50872: Incorrect tsc --build compilation that is dependent on project references (using NPM workspaces)
# Bug Report
I am getting results from tsc --build that I don't expect that change depending on the order of the project references order. I have included a repo to best showcase the error.
https://github.com/JSin/ts-bug-project-references

### 🔎 Search Terms
Compilation differs based on project references order even for projects that do not link.

### 🕗 Version & Regression Information
- This is the behavior in every version I tried (4.7.4 and 4.8.3), and I reviewed the FAQ for entries about project references

### ⏯ Playground Link
Can't be done in Playground, included repo below.
https://github.com/JSin/ts-bug-project-references

### 💻 Code

**Grab repo:**
```bash
git clone git@github.com:JSin/ts-bug-project-references.git
cd ts-bug-project-references
npm i
```

**To run the issue tsconfig:**
```bash
npx tsc --build --clean tsconfig.build.issue.json # only needed to run to clean start
npx tsc --build --verbose tsconfig.build.issue.json
```

**To run the working tsconfig but with a different project references order:**
```bash
npx tsc --build --clean tsconfig.build.working.json # only needed to run to clean start
npx tsc --build --verbose tsconfig.build.working.json
```

### 🙁 Actual behavior
Actual behaviour of the tsconfig that causes an error (running `npx tsc --build --verbose tsconfig.build.issue.json` with a clean repo)

```bash
[10:57:52 p.m.] Projects in this build: 
    * packages/b/tsconfig.json
    * packages/a/tsconfig.json
    * tsconfig.build.issue.json

[10:57:52 p.m.] Project 'packages/b/tsconfig.json' is out of date because output file 'packages/b/dist/tsconfig.tsbuildinfo' does not exist

[10:57:52 p.m.] Building project '/development/ts-bug-project-references/packages/b/tsconfig.json'...

[10:57:53 p.m.] Project 'packages/a/tsconfig.json' is out of date because output file 'packages/a/dist/tsconfig.tsbuildinfo' does not exist

[10:57:53 p.m.] Building project '/development/ts-bug-project-references/packages/a/tsconfig.json'...

packages/a/index.ts:1:8 - error TS1192: Module '"/development/ts-bug-project-references/node_modules/@types/pg/index"' has no default export.

1 import pg from "pg";
         ~~


Found 1 error.
```

### 🙂 Expected behavior
Can be seen by running `npx tsc --build --verbose tsconfig.build.working.json` in a clean repo

```bash
[11:00:05 p.m.] Projects in this build: 
    * packages/a/tsconfig.json
    * packages/b/tsconfig.json
    * tsconfig.build.working.json

[11:00:05 p.m.] Project 'packages/a/tsconfig.json' is out of date because output file 'packages/a/dist/tsconfig.tsbuildinfo' does not exist

[11:00:05 p.m.] Building project '/development/ts-bug-project-references/packages/a/tsconfig.json'...

[11:00:06 p.m.] Project 'packages/b/tsconfig.json' is out of date because output file 'packages/b/dist/tsconfig.tsbuildinfo' does not exist

[11:00:06 p.m.] Building project '/development/ts-bug-project-references/packages/b/tsconfig.json'...
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
This fixes issue with using same source file between two programs when impliedNodeFormat was different in tsbuild mode.
Fixes #50872

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]

File: src/harness/virtualFileSystemWithWatch.ts [hunk 1]
```diff
@@ -987,6 +987,7 @@ interface Array<T> { length: number; [n: number]: T; }`
         }
 
         write(message: string) {
+            if (Debug.isDebugging) console.log(message);
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/harness/virtualFileSystemWithWatch.ts:990]: These were when adding test.. its easier for debugging..

File: src/testRunner/unittests/tsbuild/moduleResolution.ts [hunk 2]
```diff
@@ -86,4 +86,36 @@ namespace ts.tscWatch {
             commandLineArgs: ["-b", "/src/packages/pkg1.tsconfig.json", "/src/packages/pkg2.tsconfig.json", "--verbose", "--traceResolution"],
         });
     });
-}
+
+    describe("unittests:: tsbuild:: moduleResolution:: impliedNodeFormat differs between projects for shared file", () => {
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/testRunner/unittests/tsbuild/moduleResolution.ts:90]: The options that are marked as `affectsModuleResolution` wouldnt have issues in general because tsbuild does not cache sourceFiles as of now beyond current build time.. So program is never reused and the resolution is done from scratch.
The impliedNodeFormat was the only thing that mattered because that field gets stuffed onto source file and is not updated at all. Infact i changed my fix to set it on the source File just like we set the other properties to ensure they are correct (like path, resolvedPath, packageJson locations etc)

Btw we have a test when two projects differ in module resolution option
Eg https://github.com/microsoft/TypeScript/blob/main/src/testRunner/unittests/tsbuild/moduleResolution.ts#L69
https://github.com/microsoft/TypeScript/blob/main/src/testRunner/unittests/tsbuild/transitiveReferences.ts#L31

[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/testRunner/unittests/tsbuild/moduleResolution.ts:90]: > The options that are marked as `affectsModuleResolution` wouldnt have issues in general because tsbuild does not cache sourceFiles as of now beyond current build time

But don't the `module` and `moduleResolution` options have `affectsModuleResolution`? Shouldn't they have not had issues? Maybe I'm missing something.

[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/testRunner/unittests/tsbuild/moduleResolution.ts:90]: Okay, I just read the fix - let me think about it a bit more.

**Review by DanielRosenwasser — APPROVED** [review]

File: src/compiler/program.ts [hunk 3]
```diff
@@ -1734,6 +1734,7 @@ namespace ts {
                 if (!newSourceFile) {
                     return StructureIsReused.Not;
                 }
+                newSourceFile.impliedNodeFormat = sourceFileOptions.impliedNodeFormat;
```
Comment (weswigham) [inline src/compiler/program.ts:1737]: Isn't the `getSourceFile` call on the prior lines supposed to handle this? It uses the options impliedNodeFormat to set weather a new source file is supposed to be returned by the call.

File: src/compiler/program.ts [hunk 4]
```diff
@@ -2968,6 +2969,7 @@ namespace ts {
                 file.path = path;
                 file.resolvedPath = toPath(fileName);
                 file.originalFileName = originalFileName;
+                file.impliedNodeFormat = sourceFileOptions.impliedNodeFormat;
```
Comment (weswigham) [inline src/compiler/program.ts:2972]: Likewise, wasn't the file supposed to be (re)created with the correct format by the `getSourceFile` call above?

Comment (sheetalkamat) [reply src/compiler/program.ts:2972]: This might not be handled in all calls and just like we ensuring say file paths, resolved paths etc its much easier to ensure that it is set.. (eg. in our repro - tsbuild uses sourceFile caching and it is irrespective of impliedNodeFormat .. the sharing of source file really just helps us with not having to reparse.. everything else including module resolution is redone any ways) so just setting the impliedNodeFormat here is better from perf standpoint

Comment (sheetalkamat) [reply src/compiler/program.ts:2972]: We do this for eg for fileName, path etc properties  that we really care about being correct

Comment (weswigham) [reply src/compiler/program.ts:2972]: But that just means the program mutates the files when built, if two programs are actually getting used _at the same time_, this means one of them will have incorrect members and generate really really weird results, which is why it's critical that a separate source file be cached for each option value. For things like `filePath` it may not change much, maybe a path in an error message; but the `impliedNodeFormat` can change errors, emit, and how imports are handled - that's a _lot_ to suddenly get wrong when the language service (or any other multi-program environment) dumps a file into multiple programs.

Comment (sheetalkamat) [reply src/compiler/program.ts:2972]: But that’s the thing .. in our scenario , ls creates new file but tsbuild is serialized operation and does not have two programs at the same time and helps with perf so I would like to keep same source file in this scenario ..

Comment (amcasey) [reply src/compiler/program.ts:2972]: This code is new to me, but Wesley's point is very compelling: it seems like this code is already trying to handle changes to `impliedNodeFormat`.  If that's not just a bug (I think Sheetal might be saying we might want to bypass the normal check for perf reasons?), it seems like the place that used to check the option ought to be the place that determines that a copy isn't necessary and the old node can just be updated.

Having said that, it looks like we're already clobbering a bunch of other properties on the reused node?  Maybe @weswigham is saying that those properties are less dangerous and this one needs special handling?

Comment (amcasey) [reply src/compiler/program.ts:2972]: Assuming this change makes sense, should we also set `languageVersion`?
```ts
newSourceFile.languageVersion = sourceFileOptions.languageVersion;
```

Comment (sheetalkamat) [reply src/compiler/program.ts]: Because we dont know what all might be impacted because of `impliedNodeFormat` differing i am reverting to my original fix of cache handling different `impliedNodeFormat`.

File: src/compiler/program.ts [hunk 5]
```diff
@@ -171,7 +171,7 @@ namespace ts {
         const readFileCache = new Map<string, string | false>();
         const fileExistsCache = new Map<string, boolean>();
         const directoryExistsCache = new Map<string, boolean>();
-        const sourceFileCache = new Map<string, SourceFile>();
+        const sourceFileCache = new Map<string, ESMap<SourceFile["impliedNodeFormat"], SourceFile>>();
```
Comment (amcasey) [inline src/compiler/program.ts:174]: Seems like you might end up with fewer map instances if impliedNodeFormat were the outer key.

**Review by amcasey — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.9

**Comment by DanielRosenwasser** [comment]
I don't know if this will work after-the-fact but

@typescript-bot user test tsserver
@typescript-bot test tsserver top100
