### PR TITLE
Disallow partial matches for discriminant properties when generating error messages

### LINKED ISSUE #37506: Error message indicates incorrect union discriminant
**TypeScript Version:**  3.8.3 (and Nightly)

**Search Terms:**

- discriminated union
- incorrect discriminant
- union error message

**Code**

```ts
type A = {
    type: 'a',
    data: { a: string }
};

type B = {
    type: 'b',
    data: null
};

type C = {
    type: 'c',
    payload: string
};

type Union = A | B | C;

// error
const foo: Union = {
    type: 'a',
    data: null
};
```

**Expected behavior:**

Error should appear on `data` property of `foo`, e.g.:

```
Type 'null' is not assignable to type '{ a: string; }'.(2322)
```

**Actual behavior:**

Error appears on `foo`, and seems to indicate that `data`, not `type`, is being used as the discriminant:

```
Type '{ type: "a"; data: null; }' is not assignable to type 'Union'.
  Type '{ type: "a"; data: null; }' is not assignable to type 'B'.
    Types of property 'type' are incompatible.
      Type '"a"' is not assignable to type '"b"'.(2322)
```

Note that removing `C` from `Union` has no effect on the error message. `C` was only provided to show that `data` is not common to all union members.

Additional variations are included in the playground link.

**Playground Link:** 

https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=68&pc=1#code/C4TwDgpgBAglC8UDeAoK6qkgLigcgEM8AaNDAEwOANyShqgGdgAnASwDsBzKAXxV4BuFCizQAQgmRl0Y3HgBGJGVErVcHAK4AbbQOGjw0AMJTUGTEfkBjZRbAEQ2gPYFyuZu276RIsVABVDjZnDgBGKTgAHyhJGOMDa1DmKAAzZ2cw3CCQ8LMVOXwiUgs1Bi1dH19fAHoaqAAlCABbZwA3Th5TVJZnZsDg0KgACwJGKA5nKAhU1IhrYCgACggWXpYmYDZdKE4ktfngAEpDSAHcgCZIqBjxROTF9OcL7MGOK8RzDELCOwoqco6PRCaq1epNVodbixNK9fo5IZgTTAcbAYbQVbrXYcTDoqD7FiHKAuaxUXKnaAIjgAZmu8XuHBST2pr1ytM+BSsRT+6DKGiBVVBdSgAHV0TiyrtxgRtIwpgQcc4FAArQ7EXEYtbODZsaWyqYEw4UqAAEXyFh+5B5qgBtFUHlYnT4Aj8RnOoQALHTTQymRkPazPebvlzfiV-upkPb8FbnSCgA

**(Potentially) Related Issues:** 

- #30648

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #37506

In the example given, `data` is marked as a discriminable property, because _for the members it exists on_, it can discriminate between them; so, taken with another (potentially partial) discriminant, it may discriminate the whole union (we have tests to that effect). Unfortunately, allowing such partial discriminants when choosing error targets makes us pick some suboptimal error messages; so in this PR, we disallow "partial" union properties from being enumerated as possible discriminant properties when fetching a discriminated union member for error elaboration purposes.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -37852,13 +37856,13 @@ namespace ts {
         }
 
         // Keep this up-to-date with the same logic within `getApparentTypeOfContextualType`, since they should behave similarly
-        function findMatchingDiscriminantType(source: Type, target: Type, isRelatedTo: (source: Type, target: Type) => Ternary) {
+        function findMatchingDiscriminantType(source: Type, target: Type, isRelatedTo: (source: Type, target: Type) => Ternary, skipPartial?: boolean) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: When do you not want to `skipPartial` discriminants?

Comment (weswigham) [reply src/compiler/checker.ts]: So we report excess property errors on something like
```
type Group = {a: 1, b: 1, field: string, data: string}; | {a: 2, field: string} | {b: 2, data: string};
const x: Group = {a: 1, b: 1, field: "ok", data: "ok", excess: "not ok"};
```
`a` and `b` are both partial discriminants, but taken together, can discriminate to the first member. We have a test expecting this.
