### PR TITLE
Fix non-toplevel prototype assignment

### LINKED ISSUE #27095: This-type fix for prototypes only works at top-level
#26925 only works at top-level:

```js
(function () {
    function Brunch(children) {
        this.parent = null;
    }

    Brunch.prototype = {
        removeInner: function(at, n) {
            this.collapse();
        },

        collapse: function() {
        },
    };
});
```

**Expected behavior:**
No error on `this.collapse` and `this: Brunch & { removeInner, collapse }`

**Actual behavior:**
Error on `this.collapse` and `this: Brunch`.

### PR DESCRIPTION
**Pull request by sandersn**
#26925 didn't fix prototype assignment when not at the toplevel. The binder was using the wrong node to lookup the containing class type for prototype assignment, so it incorrectly put the prototype declaration on the class' symbol.

This correction to the binder in turn required a change in getJSClassType in the checker. It now has to look at the "prototype" property for the prototype instead of looking on the class symbol's exports (which makes no sense).

Note that, like the previous fix, the new test baselines exhibit #26923 since they have noImplicitAny on.

Fixes #27095

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -2522,7 +2522,7 @@ namespace ts {
             const isToplevel = isBinaryExpression(propertyAccess.parent)
                 ? getParentOfBinaryExpression(propertyAccess.parent).parent.kind === SyntaxKind.SourceFile
                 : propertyAccess.parent.parent.kind === SyntaxKind.SourceFile;
-            if (!isPrototypeProperty && (!namespaceSymbol || !(namespaceSymbol.flags & SymbolFlags.Namespace)) && isToplevel) {
+            if (isToplevel && !isPrototypeProperty && (!namespaceSymbol || !(namespaceSymbol.flags & SymbolFlags.Namespace))) {
```
Comment (sandersn) [inline src/compiler/binder.ts]: This is an unrelated change. I moved this condition to the front because it's the most important check, and it was buried behind the complex predicate at the end.

Comment (sandersn) [inline src/compiler/binder.ts]: This is an unrelated change. I moved this condition to the front because it's the most important check, and it was buried behind the complex predicate at the end.

File: tests/cases/conformance/salsa/typeFromPrototypeAssignment2.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
+// @noEmit: true
+// @allowJs: true
+// @checkJs: true
+// @Filename: a.js
+// @strict: true
+
+// non top-level:
```
Comment (andy-ms) [inline tests/cases/conformance/salsa/typeFromPrototypeAssignment2.ts]: Why not just change the old test? This seems identical to that but not top-level.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -20179,10 +20179,10 @@ namespace ts {
                 (isFunctionDeclaration(decl) && getSymbolOfNode(decl) ||
                  isBinaryExpression(decl.parent) && getSymbolOfNode(decl.parent.left) ||
                  isVariableDeclaration(decl.parent) && getSymbolOfNode(decl.parent));
-            if (assignmentSymbol) {
-                const prototype = forEach(assignmentSymbol.declarations, getAssignedJSPrototype);
-                if (prototype) {
-                    return checkExpression(prototype);
+            if (assignmentSymbol && assignmentSymbol.exports && assignmentSymbol.exports.has("prototype" as __String)) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Nit: I would avoid `has`-then-`get`and just do:
```ts
const prototype = assignmentSymbol && assignmentSymbol.exports && assignmentSymbol.exports.get("prototype" as __String);
const init = prototype && getAssignedJSPrototype(prototype.valueDeclaration);
return init && checkExpression(init);
```

File: tests/cases/conformance/salsa/typeFromPrototypeAssignment2.ts (hunk 2 above)
Comment (sandersn) [reply tests/cases/conformance/salsa/typeFromPrototypeAssignment2.ts]: I prefer duplicating tests because even though this bug didn't depend on the isToplevel code path, one of the two tests may catch some future regression there.
