### PR TITLE
convertToAsync: Fix variable name collisions

### LINKED ISSUE #28530: Convert to async refactoring can introduce name collision with parameter
**TypeScript Version:**  typescript@3.2.0-dev.20181114

**Repo**
For the code. 
```ts
async function foo<T>(x: T): Promise<T> {
    return x;
}

function bar<T>(x: T): Promise<T> {
    return foo(x).then(foo)
}
```

1. Return `convert to async` on `bar`

**bug** 
This results in:

```ts
async function foo<T>(x: T): Promise<T> {
    return x;
}

async function bar<T>(x: T): Promise<T> {
    const x = await foo(x);
    return foo(x);
}
```

With an error because the new `const x` in `bar` collides with the `x` parameter

### PR DESCRIPTION
**Pull request by andrewbranch**
As I’ve grown to expect, the more code I delete from this refactor, the more bugs are fixed.

Fixes #28530

### CODE REVIEW

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 1]
```diff
@@ -160,7 +149,6 @@ namespace ts.codefix {
         It then checks for any collisions and renames them through getSynthesizedDeepClone
     */
     function renameCollidingVarNames(nodeToRename: FunctionLikeDeclaration, checker: TypeChecker, synthNamesMap: Map<SynthIdentifier>, sourceFile: SourceFile): FunctionLikeDeclaration {
-        const variableNames: SymbolAndIdentifier[] = [];
```
Comment (andrewbranch) [inline src/services/codefixes/convertToAsyncFunction.ts:163]: This array was never read 🙃
