### PR TITLE
Fix export path patterns with .d.ts target extensions in AutoImportProvider

### LINKED ISSUE #53116: Offer auto-imports for all files in package.json `exports` wildcard directories
My npm lib module's package.json
```
  "name": "my-lib",
  "exports": {
        ".": {
            "require": "./dist/index.js",
            "types": "./dist/index.d.ts"
        },
        "./*": {
            "require": "./dist/*.js",
            "types": "./dist/*.d.ts"
        },
        "./**/*": {
            "require": "./dist/**/*.js",
            "types": "./dist/**/*.d.ts"
        }
    },
```

An app depends on this npm module and install it.
The vscode auto import only support types in `import {A} from "my-lib"` resolve to `my-lib/dist/index.d.ts`, and could not find the symbol and type in something like `import {B} from "my-lib/utils"` resolve to `my-lib/dist/utils.d.ts`.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #53116 (a corner case of the 5.2 feature not working)

### CODE REVIEW

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -2212,7 +2212,11 @@ function loadEntrypointsFromExportMap(
                     scope.packageDirectory,
                     extensionsToExtensionsArray(extensions),
                     /*excludes*/ undefined,
-                    [changeAnyExtension(target.replace("*", "**/*"), getDeclarationEmitExtensionForPath(target))],
```
Comment (andrewbranch) [inline src/compiler/moduleNameResolver.ts:2215]: This was turning `*.d.ts` into `*.d.d.ts`

File: src/compiler/moduleNameResolver.ts [hunk 2]
```diff
@@ -2212,7 +2212,11 @@ function loadEntrypointsFromExportMap(
                     scope.packageDirectory,
                     extensionsToExtensionsArray(extensions),
                     /*excludes*/ undefined,
-                    [changeAnyExtension(target.replace("*", "**/*"), getDeclarationEmitExtensionForPath(target))],
+                    [
+                        isDeclarationFileName(target)
+                            ? target.replace("*", "**/*")
+                            : changeAnyExtension(target.replace("*", "**/*"), getDeclarationEmitExtensionForPath(target)),
```
Comment (jakebailey) [inline src/compiler/moduleNameResolver.ts:2218]: Can't wait for CodeQL to complain about these

**Review by jakebailey — APPROVED** [review]

**Review by sheetalkamat — APPROVED** [review]
