### PR TITLE
fix(52277): switch/case completions fail when has a negative literal type

### LINKED ISSUE #52277: `switch`/`case` completions fail when has a negative literal type
Found from https://github.com/microsoft/TypeScript/issues/52253#issuecomment-1383261940

```ts
export function foo(position: -1 | 0 | 1) {
  switch (position) {
    /**/
  }
}
```

Request completions with snippet text (`includeInsertTextCompletions`) at `/**/`

This currently errors:

```
Response received: completionInfo (2114). Request took 186 ms. Success: false . Message: Error processing request.
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (/typescript-5.0.0-dev.20230115/lib/tsserver.js:165065:17)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:164996:9
    at visitNode2 (/typescript-5.0.0-dev.20230115/lib/tsserver.js:29188:18)
    at forEachChildInCaseClause (/typescript-5.0.0-dev.20230115/lib/tsserver.js:29453:12)
    at forEachChild (/typescript-5.0.0-dev.20230115/lib/tsserver.js:29701:35)
    at processNode (/typescript-5.0.0-dev.20230115/lib/tsserver.js:164993:5)
    at formatSpanWorker (/typescript-5.0.0-dev.20230115/lib/tsserver.js:164801:5)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:164741:105
    at getFormattingScanner (/typescript-5.0.0-dev.20230115/lib/tsserver.js:163557:15)
    at Object.formatNodeGivenIndentation (/typescript-5.0.0-dev.20230115/lib/tsserver.js:164741:10)
    at Object.printAndFormatNode (/typescript-5.0.0-dev.20230115/lib/tsserver.js:147969:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:147313:57
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:147318:17
    at map (/typescript-5.0.0-dev.20230115/lib/tsserver.js:2896:19)
    at getExhaustiveCaseSnippets (/typescript-5.0.0-dev.20230115/lib/tsserver.js:147314:24)
    at completionInfoFromData (/typescript-5.0.0-dev.20230115/lib/tsserver.js:147240:19)
    at Object.getCompletionsAtPosition (/typescript-5.0.0-dev.20230115/lib/tsserver.js:146995:24)
    at Object.getCompletionsAtPosition2 [as getCompletionsAtPosition] (/typescript-5.0.0-dev.20230115/lib/tsserver.js:134099:35)
    at IOSession.getCompletions (/typescript-5.0.0-dev.20230115/lib/tsserver.js:176530:54)
    at completionInfo (/typescript-5.0.0-dev.20230115/lib/tsserver.js:174929:43)
    at /typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177286:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177294:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230115/lib/tsserver.js:177336:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230115/lib/tsserver.js:178787:14)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #52277

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -1053,7 +1053,7 @@ function getExhaustiveCaseSnippets(
                         elements.push(factory.createBigIntLiteral(type.value));
                         break;
                     case "number":
-                        elements.push(factory.createNumericLiteral(type.value));
+                        elements.push(type.value < 0 ? factory.createPrefixUnaryExpression(SyntaxKind.MinusToken, factory.createNumericLiteral(-type.value)) : factory.createNumericLiteral(type.value));
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:1056]: Annoyingly, you'll have to do the same thing for `bigint`.

```ts
export function foo(position: -1n | 0n) {
   switch (position) {
       
   }
}
```

Comment (DanielRosenwasser) [reply src/services/completions.ts:1056]: You can probably fold them into the same test case you just added.

**Review by gabritto — APPROVED** [review]

**Review by DanielRosenwasser — APPROVED** [review]
