### PR TITLE
[Release 2.0] fix10625

### LINKED ISSUE #10625: Unexpected type reference between divided modules
**TypeScript Version:**  2.0.2

**Code**

sampleA.ts
```ts
{
    // local types
    type Data = string | boolean;
    let obj: Data = true;
    console.log(obj);
}
export { }
```

sampleB.ts
```
let v = "str" || true;

export { v }
```

tsconfig.json
```
{
    "compilerOptions": {
        "declaration": true,
        "skipDefaultLibCheck": true
    },
    "include": [
        "sample*.ts"
    ]
}
```
This is minimal settings.
When `"declaration": true` and `"skipDefaultLibCheck": true`, this issue is occured.

**Expected behavior:**

We can compile this code.

**Actual behavior:** 

```
$ tsc -v
Version 2.0.2
$ tsc -p ./
sampleB.ts(1,5): error TS4023: Exported variable 'v' has or is using name 'Data' from external module "/private/tmp/hogehogehoge/sampleA" but cannot be named.
```

### PR DESCRIPTION
**Pull request by yuit**
Fix #10625

### CODE REVIEW

File: src/compiler/declarationEmitter.ts [hunk 1]
```diff
@@ -327,7 +327,7 @@ namespace ts {
             }
             else {
                 errorNameNode = declaration.name;
-                resolver.writeTypeOfDeclaration(declaration, enclosingDeclaration, TypeFormatFlags.UseTypeOfFunction, writer);
```
Comment (mhegazy) [inline src/compiler/declarationEmitter.ts]: you need to do this in all places where we call `resolver.write*`, e.g. `writeReturnTypeAtSignature`

File: src/compiler/types.ts [hunk 2]
```diff
@@ -1946,6 +1946,7 @@ namespace ts {
         UseFullyQualifiedType           = 0x00000080,  // Write out the fully qualified type name (eg. Module.Type, instead of Type)
         InFirstTypeArgument             = 0x00000100,  // Writing first type argument of the instantiated type
         InTypeAlias                     = 0x00000200,  // Writing type in type alias declaration
+        UseTypeAliasValue               = 0x00000400,  // Writing infered type alias as its value. This is used when we emit declaration file
```
Comment (mhegazy) [inline src/compiler/types.ts]: how about `If there is a type alias declaration matching the type use it instead of serializing the type.`

**Comment by mhegazy** [comment]
manually merged.
