### PR TITLE
Fix self-name input linking for --allowJs --declaration projects

### LINKED ISSUE #54299: importing own package from test fails with error TS5055: Cannot write file
# Bug Report

I had been running into #14538 and turns out it is caused by the fact that my test files import the package by it's name (as opposed to relative path). Which as far as I can tell causes TS to look into `exports` of the `package.json` which in my case looks like

```json
"exports": {
    ".": {
      "types": "./dist/src/lib.d.ts",
      "import": "./src/lib.js"
    }
  }
```

Which in turn confuses compiler into trying to compile `dist/src/lib.d.ts` file even though `dist` is listed under `exclude` of the `tsconfig.json`.

Here is the [CI flow](https://github.com/web3-storage/data-segment/actions/runs/5007306522/jobs/8973742561?pr=1) that was failing illustrating the problem. and exact [git revision](https://github.com/web3-storage/data-segment/tree/047ea5120de095ff60a4df00698b4736fcaf2cc5)

Changing import in the test to use [relative impart path fixes the problem](https://github.com/web3-storage/data-segment/pull/1/commits/62db74b6ac9110e3f7771c22a7c653a4a0a9aac6), however that is an unfortunate limitation.

### 🔎 Search Terms

- TS5055: Cannot write file

### 🕗 Version & Regression Information

This is a first time I'm able to try `"moduleResolution": "nodenext"` and is the issue I'm encountering.

### 💻 Code

https://github.com/web3-storage/data-segment/tree/047ea5120de095ff60a4df00698b4736fcaf2cc5

### 🙁 Actual behavior

As you can see in [CI flow](https://github.com/web3-storage/data-segment/actions/runs/5007306522/jobs/8973742561?pr=1)  output

```
Using local typescript@5.0.4
Error: Cannot write file '/home/runner/work/data-segment/data-segment/dist/src/api.d.ts' because it would overwrite input file.
Error: Cannot write file '/home/runner/work/data-segment/data-segment/dist/src/lib.d.ts' because it would overwrite input file.
Error: Cannot write file '/home/runner/work/data-segment/data-segment/dist/src/merkletree.api.d.ts' because it would overwrite input file.
Error: Cannot write file '/home/runner/work/data-segment/data-segment/dist/src/node.d.ts' because it would overwrite input file.
Error: Cannot write file '/home/runner/work/data-segment/data-segment/dist/src/proof.d.ts' because it would overwrite input file.
Error: Found 5 errors!
```

### 🙂 Expected behavior

`tsc --bulid` should pass without any errors.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #54299
Related: #52185

### CODE REVIEW

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -2420,7 +2421,16 @@ function loadModuleFromSelfNameReference(extensions: Extensions, moduleName: str
     // in order to be consistent with (non-self) library-name loading in
     // `loadModuleFromNearestNodeModulesDirectoryWorker`, which uses two passes in order
     // to prioritize `@types` packages higher up the directory tree over untyped
-    // implementation packages.
+    // implementation packages. See the selfNameModuleAugmentation.ts test for why this
+    // matters.
+    //
+    // However, there's an exception. If the user has `allowJs` and `declaration, we need
```
Comment (jakebailey) [inline src/compiler/moduleNameResolver.ts:2427]: drive-by nit

```suggestion
    // However, there's an exception. If the user has `allowJs` and `declaration`, we need
```

File: src/compiler/moduleNameResolver.ts [hunk 2]
```diff
@@ -2420,7 +2421,16 @@ function loadModuleFromSelfNameReference(extensions: Extensions, moduleName: str
...
     // to prioritize `@types` packages higher up the directory tree over untyped
-    // implementation packages.
+    // implementation packages. See the selfNameModuleAugmentation.ts test for why this
+    // matters.
+    //
+    // However, there's an exception. If the user has `allowJs` and `declaration, we need
+    // to ensure that self-name imports of their own package can resolve back to their
+    // input JS files via `tryLoadInputFileForPath` at a higher priority than their output
+    // declaration files, so we need to do a single pass with all extensions for that case.
+    if (getAllowJSCompilerOption(state.compilerOptions) && !pathContainsNodeModules(directory)) {
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts:2431]: I think with this we need to add affectsModuleResolution to "checkJs" in commandline options declaration.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/compiler/moduleNameResolver.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts:2431]: Ooh, yikes. I can do that for now, but maybe it would be better to update `getCompilerOptionValue` (called by `compilerOptionsAffect**` functions) to use all the computed compiler option getter functions.

Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts:2431]: `checkJs` doesn’t even have `affectsSemanticDiagnostics`. Does it need it?

Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:2431]: it does. #53403 never made it in i guess.

Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts:2431]: I’ll leave it off of this one and then we should revisit #53403

**Review by sheetalkamat — APPROVED** [review]
