### PR TITLE
Cache results of expensive repetitive type operations

### LINKED ISSUE #49622: Investigate 4.8 perf regression from "Use NonNullable<T> in more scenarios"
https://github.com/microsoft/TypeScript/pull/49330 added about 100ms to `Compiler-Unions`

image

We should investigate the root cause and any mitigations if possible.

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/49330#issuecomment-1145473780_

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #49622.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
Nice 12% improvement in check time for `compiler-unions` test.

**Review by aroramrinaal — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -774,6 +774,7 @@ namespace ts {
         const stringMappingTypes = new Map<string, StringMappingType>();
         const substitutionTypes = new Map<string, SubstitutionType>();
         const subtypeReductionCache = new Map<string, Type[]>();
+        const cachedTypes = new Map<string, Type>();
```
Comment (jakebailey) [inline src/compiler/checker.ts:777]: Why one cache for multiple calls rather than one per? I would have thought that would be more efficient because you don't have to make special keys (and could just use the type ids as keys) and for locality reasons, so I'm curious is there's some perf thing I'm missing.

Comment (ahejlsberg) [reply src/compiler/checker.ts:777]: In two of the three cases we have to create composite keys anyways, so just by making sure the keys don't overlap we can share the same cache and access helpers. In the third case we could just go by type id, but would save us very little time and could add more lines of code.

Comment (jakebailey) [reply src/compiler/checker.ts:777]: Ah, I missed the composite key.
