### PR TITLE
Consider identical instances of the same symbol equivalent when creating union and intersection properties

### LINKED ISSUE #43237: Incorrect error when using generic, class and conditional typing
# Bug Report

Incorrect error is reported when using generic, class and conditional typing

### 🕗 Version & Regression Information

The incorrect error is introduced in version 3.9 and exists in nightly

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?noLib=true&ts=4.2.3#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQDEFgAbAEwBFh0AoAb1rmbgG0lMBbYALjgGcYUZAHMAun0xIAngG5aAX1q1QkWHGylM-fnABKwbNHIAeACoHscUKiTldREhWroAfAyYswwgG6ZUcJgAFACUPBaGAD5IAK6kpHCMLMlwUMAwMVBIcLHx8slKyd4QqNio5HAARqHhltFxCUkpzGkZWTkN+SyFXjGVpAhW2KGJns2tmdkwABYI-AB0wSFdzD3MYH0DVuQjTePpk3Azc-PVy2NwSgpwyqrQ8JraugDK6eav8DbAdrqWxiaOMhUGiudx7OAbfqDRCoTg1OBmD71eKjZotA7tXKkFaXRS3cD3I7SMB4SjPcyWawgWz2fSGf6A5wguCRRJsADWwGkPEEwiQ4h4Umkl1ccAAvAjKV8fnSjFBTIzgW44AB+OAfCmGUV8CLYVhieRAA)

### 💻 Code

```typescript
export interface IFieldDef
{
    [name: string]: any;
}

export class Record<TRec extends IFieldDef>
{
    private a():TRec|null {
        return null;
    }
    protected b():TRec|null {
        return null;
    }
    public c() {
        return this.a();
    }
    public d() {
        return this.b();
    }
} 

export class Set<TSet extends Record<IFieldDef>>
{
    public item(): TSet|null {
        return null;
    }
}

export type DS<TRec extends Record<IFieldDef> | { [key:string]:any }> = TRec extends Record<IFieldDef> ? Set<TRec> : TRec[];
```

### 🙁 Actual behavior

Error: Type 'Record<IFieldDef> & TRec' does not satisfy the constraint 'Record<IFieldDef>'. Type 'Record<IFieldDef> & TRec' is missing the following properties from type 'Record<IFieldDef>': a, b

### 🙂 Expected behavior

No error

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #43237

This change walks a bit of a fine line, compatibility-wise - our services layer ends up being able to observe if we combined symbols in union/intersection property creation, so to keep our behavior there the same, we have to make some slight concessions for it.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11678,7 +11691,19 @@ namespace ts {
                 return undefined;
             }
             if (!propSet && !(checkFlags & CheckFlags.ReadPartial) && !indexTypes) {
-                return singleProp;
+                if (mergedInstantiations) {
+                    // No symbol from a union/intersection should have a `.parent` set (since unions/intersections don't act as symbol parents)
+                    // Unless that parent is "reconsituted" from the "first value declaration" on the symbol (which is likely different than its instantiated parent!)
+                    // They also have a `.containingType` set, which affects some services endpoints behavior
+                    const clone = createSymbolWithType(singleProp, (singleProp as TransientSymbol).type);
```
Comment (sandersn) [inline src/compiler/checker.ts:11698]: The normal return path of this function sets CheckFlags.Deferred on the return value. Is that needed here too?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11638,13 +11639,25 @@ namespace ts {
...
+                                if (!propSet.has(id)) {
+                                    propSet.set(id, prop);
+                                }
                             }
-                            const id = getSymbolId(prop);
-                            if (!propSet.has(id)) {
-                                propSet.set(id, prop);
+                            else {
+                                // If we merged instantiations of a generic type, we replicate the symbol parent resetting behavior we used
+                                // to do when we recorded multiple distinct symbols so that we still get, eg, `Array<T>.length` printed
```
Comment (sandersn) [inline src/compiler/checker.ts:11658]: Is the symbol parent resetting done anywhere else? If it's only in the past, I'd drop the reference and just describe it as it works now.

It could be `Array<string | number>.length` instead of `Array<T>.length`, right? How hard would that be?
Edit: Looking at the tests, it looks like the former is already what you get, at least for arrow types.

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks like a good idea. I have some questions about the implementation.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -11678,7 +11691,19 @@ namespace ts {
                 return undefined;
             }
             if (!propSet && !(checkFlags & CheckFlags.ReadPartial) && !indexTypes) {
-                return singleProp;
+                if (mergedInstantiations) {
+                    // No symbol from a union/intersection should have a `.parent` set (since unions/intersections don't act as symbol parents)
+                    // Unless that parent is "reconsituted" from the "first value declaration" on the symbol (which is likely different than its instantiated parent!)
+                    // They also have a `.containingType` set, which affects some services endpoints behavior
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:11697]: `getRootSymbol` ends up looking at the containing type to walk up symbols, which, I think is used for some nav stuff in services?

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:11698]: Nope - the symbol, as a clone of another symbol, has a deferred type by default (lazy calculation of the .type field is the norm) and we don't need to override that type, like we do for the composited symbols.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:11658]: Yes, we do it today - you'll see we do the same thing when we make the composited symbol just a few lines below.

File: src/compiler/checker.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/checker.ts:11697]: That seems like a good one to put in

**Review by sandersn — APPROVED** [review]
