### PR TITLE
Fix incorrect suggestion for package that bundles types

### LINKED ISSUE #43488: Do not suggest installing @types for packages that have `types`
```ts
// @Filename: node_modules/foo/package.json
{ "types": "index.d.ts" }

// @Filename: node_modules/foo/index.d.ts
declare const foo: any;
export = foo;

// @Filename: node_modules/foo/other.js
module.exports = {};

// @Filename: index.ts
import {} from "foo/other";
```

You get a `Could not find a declaration file for module 'foo/other'` error message here, which is good, but you also get the related error:

> Try `npm i --save-dev @types/foo` if it exists or add a new declaration (.d.ts) file containing `declare module 'foo/other';`

which is bad advice, because `foo` clearly ships its own types, it just doesn’t have a declaration file at that subpath.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #43488

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -6513,6 +6513,8 @@ namespace ts {
         subModuleName: string;
         /** Version of the package, e.g. "1.2.3" */
         version: string;
+        /** Whether the package bundles its own type declarations. */
+        bundlesTypes?: boolean;
```
Comment (gabritto) [inline src/compiler/types.ts:6517]: if there's a more official naming for this option, I'm open to renaming it

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -6027,6 +6027,11 @@
         "category": "Error",
         "code": 7057
     },
+    "Try adding a new declaration (.d.ts) file containing `declare module '{0}';`": {
```
Comment (gabritto) [inline src/compiler/diagnosticMessages.json:6030]: I added the new message based on the old one described in the issue ("Try `npm i --save-dev @types/foo` if it exists or add a new declaration (.d.ts) file containing `declare module 'foo/other'`;"), but without the "Try npm..." part.

File: src/compiler/moduleNameResolver.ts [hunk 3]
```diff
@@ -18,7 +18,8 @@ namespace ts {
                 packageId = {
                     name: packageJsonContent.name,
                     subModuleName: r.path.slice(packageInfo.packageDirectory.length + directorySeparator.length),
-                    version: packageJsonContent.version
+                    version: packageJsonContent.version,
+                    bundlesTypes: typeof packageJsonContent.types === "string" || typeof packageJsonContent.typings === "string"
```
Comment (andrewbranch) [inline src/compiler/moduleNameResolver.ts:22]: The problem is that root `index.d.ts` files implicitly count, even if `types` or `typings` isn’t set. I think instead of changing `PackageId`, take a look at how `typesPackageExists` works in the function you changed in checker.ts, then follow it to the implementation of `getPackagesSet`, which is _only_ used in `typesPackageExists`.

```ts
const getPackagesSet = memoize(() => {
    const set = new Set<string>();
    host.getSourceFiles().forEach(sf => {
        if (!sf.resolvedModules) return;

        forEachEntry(sf.resolvedModules, r => {
            if (r && r.packageId) set.add(r.packageId.name);
        });
    });
    return set;
});
```

The resolved module `r` has an `extension` field. You could change this Set to a Map whose values are true/false based on whether you saw any resolved modules from that package with .d.ts extensions. It’s not perfect because only modules that are referenced somewhere in the program will show up, but I think that’s close enough. It’s also nice because it will catch non-index `.d.ts` files for the package, like for a package that has no root typings file for some reason but has all its sub-modules typed.

Don’t take this as the only solution; there are almost certainly other good ways to go about this.

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/diagnosticMessages.json:6030]: Suggestion: I really like the “If the '{0}' package actually exposes this module” from the message you get when the types package exists. If we’ve detected other .d.ts files when issuing this message, we have reason to be at least a _little_ skeptical that the referenced module does in fact exist at runtime here. It might be nice to hedge our suggestion and make sure the user knows that this is a solution only if they’re really sure that this module exists.

```suggestion
    "If the '{0}' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '{1}';`": {
```

**Review by andrewbranch — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]
