### PR TITLE
Properly compute `SymbolFlags.Optional` for intersected properties

### LINKED ISSUE #50954: 4.9 regression with `in` operator: object is incorrectly narrowed to `never`
# Bug Report

### 🕗 Version & Regression Information

- This changed between versions 4.8 and 4.9

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220921#code/KYDwDg9gTgLgBAYwgOwM7wQC2Ag1gSVQBUIBXLAEWADcBLBYOAXjgAoBKZgPgFgAoOILgAiFDDJZ0AQ1jC4tZHADuCgCYQlcAD5b+QkQFtUAWSkgS5TAAUICmKjkK9+oQHpXcQDLkcAKrJQYDgwwKpwRADKcMBQUNAAXHBWsYGwAJ5wAOTIUnQA5lLiUBlw6sCocMgQ8KC06HAocDCpgZn+1NEZzi7KahoAdNl5BdAA3EA)

### 💻 Code

```ts
export const checkIsTouchDevice = () =>
    "ontouchstart" in window ||
    "msMaxTouchPoints" in
        // ❌ Unexpected TS error: Property 'navigator' does not exist on type 'never'
        window.navigator;

```

I've reduced it down to this:

```ts
declare const obj: { a: unknown; b: unknown };

"a" in obj ||
    "prop" in
        // ❌ Unexpected TS error: Property 'b' does not exist on type 'never'
        obj.b;
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR, we ignore properties originating in non-property declarations (such as exported members of modules or the members of `globalThis`) for purposes of computing `SymbolFlags.Optional` for intersected properties. Non-property declarations can't specify optionality and therefore shouldn't affect the outcome.

Fixes #50954.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot test top100

File: tests/cases/compiler/inKeywordTypeguard.ts [hunk 1]
```diff
@@ -273,10 +273,69 @@ function f9(x: object) {
     }
 }
 
+function f10(x: { a: unknown }) {
+    if ("a" in x) {
+        x;
+    }
+    else {
+        x;
```
Comment (Andarist) [inline tests/cases/compiler/inKeywordTypeguard.ts:281]: I don't quite understand why this would **not** be `never` here. Those calls are invalid:
```ts
declare const o4: { a?: number }
f10(o4) // error
declare const o5: {}
f10(o5) // error
```
So how, type-wise, could this be reached? After all, `in` should check the presence of a property and not that it can possibly be `undefined` 🤔

File: tests/baselines/reference/inKeywordTypeguard(strict=true).errors.txt [hunk 2]
```diff
@@ -240,8 +239,6 @@ tests/cases/compiler/inKeywordTypeguard.ts(186,21): error TS2638: Type 'NonNulla
             window.ontouchstart
         } else {
             window.ontouchstart
-                   ~~~~~~~~~~~~
```
Comment (Andarist) [inline tests/baselines/reference/inKeywordTypeguard(strict=true).errors.txt:243]: if you decide to land this PR then I think that it would best to adjust the "title" of this test - the containing function is named `negativeIntersectionTest` and that name was targeting the previous behavior

File: tests/cases/compiler/inKeywordTypeguard.ts (hunk 1 above)
Comment (ahejlsberg) [reply tests/cases/compiler/inKeywordTypeguard.ts:281]: This was an attempt to make feature detection code easier to write, but it seems to just trade one set of problems for another. See my comment [here](https://github.com/microsoft/TypeScript/issues/50954#issuecomment-1258856194). I'm rolling the change back and just fixing the issue with `SymbolFlags.Optional` computation for intersections.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot test top100

**Comment by Andarist** [comment]
@ahejlsberg if needed - i can change the code in XState (im actually its maintainer). But the reported error looks dubious for me - this should be assignable, right?

**Comment by ahejlsberg** [comment]
@Andarist Yeah, those assignments should be permitted. When checking assignability for a property that originates in a non-property declaration, we shouldn't check optionality because there is no way of controlling it.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot test top100

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
All tests look good and performance is unaffected. This one is ready to merge.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -12520,11 +12520,14 @@ namespace ts {
                     const prop = getPropertyOfType(type, name, skipObjectFunctionPropertyAugment);
                     const modifiers = prop ? getDeclarationModifierFlagsFromSymbol(prop) : 0;
                     if (prop) {
-                        if (isUnion) {
-                            optionalFlag |= (prop.flags & SymbolFlags.Optional);
-                        }
-                        else {
-                            optionalFlag &= prop.flags;
+                        if (prop.flags & SymbolFlags.ClassMember) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:12523]: We should really rename this flag. “Class” threw me off.

```ts
ClassMember = Method | Accessor | Property,
```

**Review by andrewbranch — APPROVED** [review]

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:12523]: Yeah, I wanted to rename it, but its not `/* @internal */` so that would be a breaking change. Which I didn't much care to introduce.
