### PR TITLE
Elide type reference comments which are also imported

### LINKED ISSUE #19874: unexpected reference..types directive emitted when --types is not specified
**TypeScript Version:**  2.7.0-dev.20171109

When generating declaration files that depend on `@types` that are imported in the source code as modules, the resulting `.d.ts` files contain both an `import dep = require("dep")` and a `/// <reference types="dep" /> directive unless the `--types` is explicitly specified with a value excluding `"dep"`.

Repro at https://github.com/aluanhaddad/typescript-issue-19874

**Code**
To reproduce first run
```shell
> tsc --init
> npm install --save minimist @types/minimist @types/node
```
then create `parse-args.ts`
```ts
import minimist = require('minimist');
import process = require('process');

export default function parseArgs(): minimist.ParsedArgs {
  return minimist(process.argv.slice(2));
}
```
and finally run
```shell
> tsc --declaration --project .\tsconfig.json
```

**Expected behavior:**
`parse-args.d.ts` contains
```ts
import minimist = require('minimist');
export default function parseArgs(): minimist.ParsedArgs;
```
**Actual behavior:**
`parse-args.d.ts` contains
```ts
/// <reference types="minimist" />
import minimist = require('minimist');
export default function parseArgs(): minimist.ParsedArgs;
```

The following, however, produces the expected output.

```shell
> tsc --declaration --project .\tsconfig.json --types node
```

**Remarks:**
There is a workaround, specifying `--types` explicitly, but I find the behavior surprising especially since `@types/minimist` only exposes itself using `export =`.

This implies that many declaration files needlessly emit both an `import` and a `/// <reference types="dep" />` which makes them incompatible with `--paths`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #19874

@mhegazy this is a little different than what you suggested; but I think this is better - the references only get added in the first place if an identifier or entity name references something in the module; so we just want to avoid referencing the module in two different ways unnecessarily.

### CODE REVIEW

File: src/compiler/transformers/declarations.ts [hunk 1]
```diff
@@ -188,17 +188,30 @@ namespace ts {
...
-                return necessaryTypeRefernces ? map(arrayFrom(necessaryTypeRefernces.keys()), getFileReferenceForTypeName) : [];
+                return necessaryTypeRefernces ? mapDefined(arrayFrom(necessaryTypeRefernces.keys()), getFileReferenceForTypeName) : [];
             }
 
             function getFileReferenceForTypeName(typeName: string): FileReference {
+                // Elide type references for which we have imports
+                for (const importStatement of emittedImports) {
+                    if (isImportEqualsDeclaration(importStatement) && isExternalModuleReference(importStatement.moduleReference)) {
+                        const expr = importStatement.moduleReference.expression;
+                        if (isStringLiteralLike(expr) && expr.text === typeName) {
```
Comment (mhegazy) [inline src/compiler/transformers/declarations.ts]: nit. `return undefined` and return type should be `FileReference | undefined`
