### PR TITLE
Ensure we don't overwrite computed CouldContainTypeVariables in new optimization

### LINKED ISSUE #54348: TS 5.1.1-rc: RangeError: Maximum call stack size exceeded
# Bug Report

Tried an upgrade to 5.1.1-rc from 5.0.4 and got a `RangeError: Maximum call stack size exceeded` for one of the app of the monorepo (nextjs, mui, i18next,...). Others apps and packages works. 

You'll find a reproduction here: https://github.com/belgattitude/nextjs-monorepo-example/pull/3826 with explanation.

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git --branch typescript-5.1.1-rc 
yarn install
cd apps/nextjs-app
yarn typecheck
```

Note that this repo uses yarn 4.0.0-rc.44 with node_modules linker.The cause might be linked to that as well. But in general this example repo used to work across ts updates quite well.

The error is visible on the CI https://github.com/belgattitude/nextjs-monorepo-example/actions/runs/5049578076/jobs/9059197251?pr=3826 and reproduced locally on linux / node 18.16

Just wanted to let you know, didn't had time to investigate. 

Huge thx for ts team, I really appreciate what you're doing :heart: 

### 🔎 Search Terms

```
RangeError: Maximum call stack size exceeded
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63011:28)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)

```

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0.4 and 5.1.1-rc

### ⏯ Playground Link

https://github.com/belgattitude/nextjs-monorepo-example/pull/3826 with explanation.

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git --branch typescript-5.1.1-rc 
yarn install
cd apps/nextjs-app
yarn typecheck
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #54348

In this branch (added in #53246), we checked that `result` didn't already have `CouldContainTypeVariables` calculated. If not, then we instead calculate it directly by only checking `typeArguments`.

However, if `result` happens to be mentioned in `typeArguments`, the call to `couldContainTypeVariables` may change `result.objectFlags`. When this happens, we stomp over the previous computation with our own.

Normally, this is harmless because `CouldContainTypeVariables` is realistically just an optimization to prevent unnecessary type traversals.

However, `result` can in fact be `neverType` or `wildcardType` (and maybe others)! If we accidentally overwrite the previously computed result with "true" (a more conservative calculation), this can actually cause a problem later, as seen in #54348. This is because `inferTypes` may end up with two identical source and targets.

In the bug's case, `source == target == wildcardType`. `wildcardType` is a special case for `inferTypes`, which for "reasons" can only stop infinitely recursing by seeing that `wildcardType` cannot contain type variables. So, if we stomp over a previously calculated "false" answer here with a more conservative "true", what was just a missing optimization turns into a stack overflow. (Theoretically, I think we should also make `inferTypes` _not_ depend on this optimization flag and just directly check for the infinite recursion. But, it did catch this bug...)

This PR "fixes" the problem by double checking that someone else hasn't already calculated the value while we were. If it's already calculated, then we just skip over. I also verified that the speedup in material-ui is not broken by this fix (phew).

I haven't been able to produce a decent test case. There are actually 15 test cases in our test suite which hit this new branch, but none with observable behavior differences. All provided tests in the issue are massive and I can't minimize them.

I am also not 100% sure of this fix; most of the time, the optimization from #53246 is operating on a freshly instantiated type (which is why the optimization is valid). But sometimes, it's not actually operating on a new type. Perhaps the "right" fix is to skip this code when the type isn't a newly created one just for this section? Because those types shouldn't be involved in this optimization anyway?

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18800,8 +18800,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
                 if (result.flags & TypeFlags.ObjectFlagsType && !((result as ObjectFlagsType).objectFlags & ObjectFlags.CouldContainTypeVariablesComputed)) {
-                    (result as ObjectFlagsType).objectFlags |= ObjectFlags.CouldContainTypeVariablesComputed |
-                        (some(typeArguments, couldContainTypeVariables) ? ObjectFlags.CouldContainTypeVariables : 0);
+                    const resultCouldContainTypeVariables = some(typeArguments, couldContainTypeVariables);
+                    // The above check may have caused the result's objectFlags to update if the result is referenced via typeArguments.
+                    if (!((result as ObjectFlagsType).objectFlags & ObjectFlags.CouldContainTypeVariablesComputed)) {
+                        (result as ObjectFlagsType).objectFlags |= ObjectFlags.CouldContainTypeVariablesComputed |
+                            (resultCouldContainTypeVariables ? ObjectFlags.CouldContainTypeVariables : 0);
+                    }
                 }
```
Comment (jakebailey) [inline src/compiler/checker.ts:18809]: This could also have been:

```ts
if ((result as ObjectFlagsType).objectFlags & ObjectFlags.CouldContainTypeVariablesComputed) {
    resultCouldContainTypeVariables &&= !!((result as ObjectFlagsType).objectFlags & ObjectFlags.CouldContainTypeVariables);
}
(result as ObjectFlagsType).objectFlags |= ObjectFlags.CouldContainTypeVariablesComputed |
    (resultCouldContainTypeVariables ? ObjectFlags.CouldContainTypeVariables : 0);
```

e.g., merge the result. But that felt wrong. But, my current fix doesn't feel all correct either. I'm going to investigate and see if there's a specific class of types that we're hitting.

Comment (jakebailey) [reply src/compiler/checker.ts:18809]: I also have a version which does something... clever. Grab `typeCount` before obtaining the result, and if its `id` is greater than the saved `typeCount`, then you know it's a new type and we can do the calculation. This stems from my thought that this optimization can only possibly be valid on newly created types.

But, that feels really unusual.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

File: src/compiler/checker.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/checker.ts:18809]: Honestly, with that latter solution (given guidance on how to determine what a "new type" is), we could simplify things a bit and just force calculate the value unconditionally, dropping the change in instantiateAnonymousType.

**Comment by capaj** [comment]
I can confirm this does fix our infinite recursion problem on our 85k LOC codebase where both 5.0.4 and 5.1.3 fail  with infinite recursion.

**Review by weswigham — APPROVED** [review]
I have some gripes after some review about the comment above not matching the actual implementation below (which I totally didn't notice when I reviewed the original PR), and that mismatch is probably causing us to do extra work on unions and intersections that we may not need to do, but that's not necessarily related to this fix. As we discussed, since you can clearly have an input type argument that's the same type as `result` (eg, an argument to a noop mapped type), you need to conditionalize the check like this. :)

**Comment by jakebailey** [comment]
> As we discussed, since you can clearly have an input type argument that's the same type as `result` (eg, an argument to a noop mapped type), you need to conditionalize the check like this. :)

Just to be clear, you're suggesting keeping my "if the computed flag gets set, bail out" condition?

I am also totally happy to integrate your patch from our DMs; it seems more complete and still safe in general I think.

**Comment by weswigham** [comment]
> Very likely this is superseded by https://github.com/microsoft/TypeScript/pull/54538, which covers what I have but better.

It just already includes this change (verbatim) - this change is, itself, clearly needed and an appropriate fix for the linked issue (moreso than the type id thing, I feel, after looking into our behaviors here); feel free to merge it.

**Comment by jakebailey** [comment]
> > Very likely this is superseded by #54538, which covers what I have but better.
> 
> It just already includes this change (verbatim) - this change is, itself, clearly needed and an appropriate fix for the linked issue (moreso than the type id thing, I feel, after looking into our behaviors here); feel free to merge it.

Gotcha, thanks!

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.1
