### PR TITLE
Parse quoted constructors as constructors, not methods

### LINKED ISSUE #31020: TypeScript doesn’t properly handle a constructor with a quoted name
**TypeScript Version:**  3.5.0-dev.20190418

**Search Terms:** typescript quoted constructor

**Code**

```ts
class Foo {
    constructor(name: string) {
      this.name = name
    }
}
class Bar {
    "constructor"(name: string) {
      this.name = name
    }
}

new Foo("hello")
new Bar("hello")
```

**Expected behavior:**
Compiles without error

**Actual behavior:**
The `new Foo` call compiles properly, but the `new Bar` call produces a type checking error:

```ts
test.ts:9:9 - error TS2554: Expected 0 arguments, but got 1.

9 new Bar("hello")
          ~~~~~~~
```

Note that running the code (with the type assertions stripped) [results in both constructors being called](https://observablehq.com/d/9ed31ae49ec56ac8), but TypeScript’s ES5 transpilation instead sets the second constructor as a method named `constructor`, which causes it not to be run.

**Playground Link:** [Open playground ↗️](https://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%20%20%20%20constructor(name%3A%20string)%20%7B%7D%0D%0A%7D%0D%0Aclass%20Bar%20%7B%0D%0A%20%20%20%20%22constructor%22(name%3A%20string)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Anew%20Foo(%22hello%22)%0D%0Anew%20Bar(%22hello%22)%0D%0A)

**Related Issues:** Encountered in https://github.com/prettier/prettier/issues/6063.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #31020, part 2. We now properly parse `class A { "constructor"() {} }` as a constructor, not as a method. Part 1 was issuing an error to warn people that the behavior was changing: #31119

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -5650,9 +5650,27 @@ namespace ts {
             return finishNode(node);
         }
 
+        function tryParseStringConstructorDeclaration(node: ConstructorDeclaration): ConstructorDeclaration | undefined {
+            return tryParse(() => {
+                const stringLiteral = parseLiteralNode();
+                if (isStringLiteral(stringLiteral)
+                    && stringLiteral.text === "constructor"
```
Comment (ajafff) [inline src/compiler/parser.ts]: Is the string literal allowed to contain escapes?

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -5650,9 +5650,27 @@ namespace ts {
...
 
+        function tryParseStringConstructorDeclaration(node: ConstructorDeclaration): ConstructorDeclaration | undefined {
+            return tryParse(() => {
+                const stringLiteral = parseLiteralNode();
+                if (isStringLiteral(stringLiteral)
+                    && stringLiteral.text === "constructor"
+                    && token() === SyntaxKind.OpenParenToken
+                ) {
+                    node.kind = SyntaxKind.Constructor;
+                    node.name = stringLiteral;
```
Comment (ajafff) [inline src/compiler/parser.ts]: Regular constructors don't have a `name` property. To avoid polymorphism you could
* explicitly set it to undefined in parseConstructorDeclaration
* set it after parseConstructorDeclarationEnd (not preferred as it still introduces a new object shape)

**Comment by ajafff** [comment]
Should be labeled as breaking change to the API

File: src/compiler/parser.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/parser.ts]: True; I guess we don’t need to set that property. I was setting it just because we already have the node and it would allow you to disambiguate the exact structure of the declaration if needed, but that should be covered by `getChildren()`.

File: src/compiler/parser.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/parser.ts]: Yes, escapes are handled in the lexical grammar. `text` is the unescaped version, so it should be fine.

File: src/compiler/parser.ts [hunk 3]
```diff
@@ -5861,6 +5879,13 @@ namespace ts {
                 return parseAccessorDeclaration(<AccessorDeclaration>node, SyntaxKind.SetAccessor);
             }
 
+            if (token() === SyntaxKind.StringLiteral) {
```
Comment (rbuckton) [inline src/compiler/parser.ts]: Why not just check the token text here and call parseConstructorDeclaration, and have parseConstructorDeclaration handle whether its a string or keyword? The public fields proposal disallows public fields with the name `constructor` or `"constructor"`.

**Comment by andrewbranch** [comment]
> Probably needs changes to forEachChild, transform visitor and factory APIs, too.

> Regular constructors don't have a name property.

I think if we want to preserve the quoted string constructor in refactors, emit, etc., the easiest thing to do is probably to keep the `name` property, and in that case you’re right that we need a couple more changes here.

Alternatively, if we want to drop the `name` property, we’d just treat quoted constructors exactly the same as non-quoted constructors, and at a glance it looks like in that case the existing `getChildren()`, visitors, and factories will work, just may not preserve the quotes in refactors/emit.

Curious to get @rbuckton’s opinion here.

File: src/compiler/parser.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/parser.ts]: Just because we already give a better error at the grammar checking stage for fields named `constructor`—it says `Classes may not have a field named 'constructor'.` instead of `'(' expected`.

**Comment by rbuckton** [comment]
I'm not sure how important it is to preserve whether the constructor name was quoted.

File: src/compiler/parser.ts (hunk 1 above)
Comment (ajafff) [reply src/compiler/parser.ts]: I asked because I wasn't sure if the spec allowed escapes in the string literal. Tested it with Chrome and it recognizes it as constructor.

Comment (andrewbranch) [reply src/compiler/parser.ts]: Sorry, I’m not completely following—can you show me exactly what you tried with Chrome?

Comment (ajafff) [reply src/compiler/parser.ts]: To test whether ES6 classes allow escapes in the sting literal `"constructor"` I executed the following code:
```js
new (class C {"\x63onstructor"(param) {console.log(param)}})(1)
```

I was just curious because `"use strict"` is only recognized if it does not contain escapes.

Comment (andrewbranch) [reply src/compiler/parser.ts]: I actually don’t see anything in the grammar that prohibits that from being a proper constructor, so maybe we should be looking at escaped text. But I could be missing something. Was looking around [this area](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-static-semantics-constructormethod) and [here](https://www.ecma-international.org/ecma-262/9.0/index.html#prod-LiteralPropertyName). I’m leaning toward assuming Node and Chrome are doing the correct thing.

Comment (andrewbranch) [reply src/compiler/parser.ts]: Handled escaped constructors in the latest commit. I think this is ready now.

**Comment by RyanCavanaugh** [comment]
> I'm not sure how important it is to preserve whether the constructor name was quoted.

I would say it's quite unimportant - it's not possibly subject to minification, which is the only thing people seem to care about in terms of preserving quotedness
