### PR TITLE
Minor fixes to "Convert To Async" refactor

### LINKED ISSUE #35192: "Convert to async function" produces incorrect code for .catch()
**TypeScript Version:**  3.7.2 (refactoring in VSCode 1.40.1 using 3.6.3)

**Search Terms:** Convert to async function catch

**Code**

```ts
// Original function
function combine1(a: Promise<any>, b: Promise<any>) {
  return a.catch(() => b)
}

// Result of "Convert to async function" in VSCode
async function combine2(a: Promise<any>, b: Promise<any>) {
  try {
    return a;
  }
  catch (e) {
    return await b;
  }
}

async function test() {
  const a1 = Promise.reject('nay1')
  const b1 = Promise.resolve('yay1')
  console.log("combine1:", await combine1(a1, b1))
  const a2 = Promise.reject('nay2')
  const b2 = Promise.resolve('yay2')
  console.log("combine2:", await combine2(a2, b2))
}
test()
```

**Expected behavior:**

Converted code should be functionally equivalent to original code.  I believe `return await a` would be correct.

**Actual behavior:**

Converted code is not equivalent as the example shows.

**Playground Link:** 

https://www.typescriptlang.org/play/#code/PTAEHkCcEsHNoHYEMA2oBmBXBBjALtAPYICwAUFrgcaDoQLYBGiApgIwAUSAXKAAqQG0AM4sAPEgQBPAHwAaUI14ChoidJkBKUAG9yoUJBZ5MkBKCQA6HEjw4AFhw7aAvDMWbyAX3LkQoACUWYUwUPFBCdFAAIgBhYgA3FkhwvEILYSlcDGx8IgRo0ERQADUAZXiAExZyJEzsyjyaOiZWACYuZUF6EXFJWQUlfm7e9VltPTIDPEgpXX0DQ2NTcyQAbgWfKdpbB1AOFgmFgyMTMwsAdyRocMYN7a2t2vqcHKp80DxgvGd57boEMJwkg2KAXMNVCxLEYAFYsfAcADkyCkbERnn+xCBilB4JUPVE0OChBQSSRUiQqPRCwBwhJUJQhFgHGiLWYCHY3GiCiQVxutAY7PYXDYgzYmgxBlpwLaYIhBKhsPhP2RlLa1MxgNusrxI0JRjppJY5LVGqlWPplkZzNZgvaXJ5fPCbPaXDagzaEu85C+QOc5CAA

**Related Issues:** 

Related to async refactoring: #27641, #27621

**VSCode info:**

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Sorry if this should be reported on VSCode, I saw similar bugs have been transferred from there to here.

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes some corner cases in the "Convert to Async" refactor:

- Correctly awaiting return value inside of a `catch`
- Eliding empty `.then()`, `.then(null)`, `.then(undefined)`, etc.
- Eliding empty `.catch()`, `.catch(null)`, etc.
- Eliding catch variable when unused (i.e., `.catch(() => { })`).
- Support `.finally()` using `try { } finally { }`.
- Use awaited type in `Promise.resolve(1).then(x => Promise.resolve(x + 1)).then(y => { ... })` (type of `y` is now `number` instead of `number | Promise<number>`).

Fixes #35192

### CODE REVIEW

**Review by amcasey — APPROVED** [review]

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_LocalReturn.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ function /*[#|*/f/*|]*/() {
 async function f() {
     let x = fetch("https://typescriptlang.org").then(res => console.log(res));
     try {
-        return x;
+        return await x;
```
[the remark this answers is not in the document]
Comment (rbuckton) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_LocalReturn.js:14]: Not if you're in a `try/catch`. If you `return` the promise and it rejects, the `catch` will never be triggered because you've already exited the function.

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 2]
```diff
@@ -236,30 +248,103 @@ namespace ts.codefix {
...
+            return transformPromiseExpressionOfPropertyAccess(returnContextNode, node, transformer, prevArgName);
         }
 
         return silentFail();
     }
 
-    function transformCatch(node: CallExpression, transformer: Transformer, prevArgName?: SynthBindingName): readonly Statement[] {
-        const func = singleOrUndefined(node.arguments);
-        const argName = func ? getArgBindingName(func, transformer) : undefined;
+    function isNullOrUndefinedOrMissing({ checker }: Transformer, node: Expression) {
```
[the remark this answers is not in the document]
Comment (rbuckton) [reply src/services/codefixes/convertToAsyncFunction.ts:275]: I had it checking for `undefined` on `node`, but backed that out. I'll rename.

**Comment by rbuckton** [comment]
I found a small issue I need to investigate, as one of my fixes is a bit over aggressive. Essentially I was trying to fix this case:

```ts
function f2() {
    return foo().then(() => {
        if (!0) {
            return 1;
        }
        console.log("other");
    }).then(a => {
        return a;
    });
}
```

Which currently gets refactored to this:

```ts
async function f2() {
    await foo();
    if (!0) {
        return 1;
    }
    console.log("other");
    const a = undefined;
    return a;
}
```
Which is incorrect, because the `if` branch shouldn't exit the function. To resolve this I started injecting labeled blocks:
```ts
async function f2() {
    await foo();
    let a;
    block_1: {
        if (!0) {
            a = 1;
            break block_1;
        }
        console.log("other");
    }
    return a + 1;
}
```

However it is too aggressive in cases where branches are exhaustive.

**Comment by andrewbranch** [comment]
@rbuckton where we’ve landed in discussions about Convert To Async before is that if we can't produce code that a reasonable human would write, the refactor should be unavailable. Labeled blocks would be a hard dealbreaker for me as a user of this refactor.

**Comment by rbuckton** [comment]
> @rbuckton where we’ve landed in discussions about Convert To Async before is that if we can't produce code that a reasonable human would write, the refactor should be unavailable. Labeled blocks would be a hard dealbreaker for me as a user of this refactor.

While I can understand and agree with this sentiment (and will happily remove that part), unfortunately I still have to solve the underlying problem, unless we want to also make the refactor unavailable for a common scenario like this:

```ts
function f() {
  return foo().then(a => {
    if (a) {
      return 1;
    }
    else {
      return 2;
    }
  }).then(b => {
    return b;
  });
}
```
This could be refactored without labeled blocks, but also fails to refactor, producing this currently:
```ts
async function f() {
    const a = await foo();
    if (a) {
        return 1;
    }
    else {
        return 2;
    }
    const b = undefined;
    return b;
}
```
When the result should be:
```ts
async function f() {
    const a = await foo();
    let b: number;
    if (a) {
        b = 1;
    }
    else {
        b = 2;
    }
    return b;
}
```

**Comment by andrewbranch** [comment]
Makes sense. Your expected behavior there looks reasonable enough, but if it’s wildly difficult to get it working for some reason, I’m not too concerned about targeted disabling of the refactor.

**Comment by rbuckton** [comment]
@amcasey, @andrewbranch can you take another look with these last changes?

**Review by andrewbranch — APPROVED** [review]

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRejRef.ts [hunk 3]
```diff
@@ -1,37 +0,0 @@
...
-function catch_err(err){
-    console.log(err);
-}
-// ==ASYNC FUNCTION::Convert to async function==
-
-async function f():Promise<void> {
-    try {
-        try {
-            const result = await fetch('https://typescriptlang.org');
-            return res(result);
```
Comment (amcasey) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRejRef.ts:21]: What was wrong here?  Does this belong outside the try-catch?

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRej.ts [hunk 4]
```diff
@@ -1,19 +0,0 @@
...
-
-function /*[#|*/f/*|]*/():Promise<void> {
-    return fetch('https://typescriptlang.org').then(result => { console.log(result); }, rejection => { console.log("rejected:", rejection); }).catch(err => { console.log(err) });
-}
-// ==ASYNC FUNCTION::Convert to async function==
-
-async function f():Promise<void> {
-    try {
-        try {
-            const result = await fetch('https://typescriptlang.org');
```
Comment (amcasey) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRej.ts:11]: What was wrong here?

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_NoRes.ts [hunk 5]
```diff
@@ -8,7 +8,7 @@ function /*[#|*/f/*|]*/():Promise<void | Response> {
 
 async function f():Promise<void | Response> {
     try {
-        await fetch('https://typescriptlang.org');
+        return await fetch('https://typescriptlang.org');
```
Comment (amcasey) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_NoRes.ts:11]: Not returning was just a bug?

**Review by amcasey — APPROVED** [review]
Baselines LGTM

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRejRef.ts (hunk 3 above)
Comment (rbuckton) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRejRef.ts:21]: In #38152 we removed support for applying the code fix if both an `onfulfilled` and an `onrejected` handler are present for the same call to `.then`, however we never removed some of the code for that refactor and it was inadvertently being called. If you look at both of these tests in https://github.com/microsoft/TypeScript/pull/45536/files/da1d25c4f7460212ba6e40b47ccebb07703f2d63#diff-8eb4fd66983b9bab0f035c7dabf674c0d05e08266a0fd1b0f09dde1ab1a8a840 you'll see that they both have both handlers present.

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRej.ts (hunk 4 above)
Comment (rbuckton) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_CatchAndRej.ts:11]: See https://github.com/microsoft/TypeScript/pull/45536#discussion_r699866399

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_NoRes.ts (hunk 5 above)
Comment (rbuckton) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_NoRes.ts:11]: Correct. Passing `null` or `undefined` to the `onfulfilled` handler is essentially the same as passing `v => { return v; }`, the value still flows through.  Similarly, passing `null` or `undefined` to an `onrejected` handler is essentially the same as passing `e => { throw e; }`.
