### PR TITLE
Small fix in `getIsContextSensitiveAssignmentOrContextType`

### LINKED ISSUE #38532: Naming conflict ends up in unhandled compiler error
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**
It seems, that the combination of importing `Debug`, redefining it as a function and then setting a property on that function (`Debug.enable`) breaks the compiler.

```ts
import Debug from 'debug'

const cache: any[] = []

const MAX_LOGS = 100

const namespaces: string[] = []

// for our use-case, map is faster, as retrieving values is faster than with Set or Object
const enabledNamespaces: Map<string, true> = new Map<string, true>()

export default function Debug(namespace: string): Debug.Debugger {
  const debug: any = Debug(namespace)
  namespaces.push(namespace)

  Debug.enable(namespaces.join(','))

  debug.log = (...args) => {
    cache.push(args)
    // keeping 100 logs is just a heuristic. The real truncating comes later
    if (cache.length > MAX_LOGS) {
      cache.shift()
    }
    if (enabledNamespaces.has(namespace)) {
      console.error(...args)
    }
  }

  return debug
}

Debug.enable = (namespace) => {
  enabledNamespaces.set(namespace, true)
}
```

**Expected behavior:** The compiler should give me a readable error message, that I have a naming conflict.

**Actual behavior:**
```
errors.ts:22 Uncaught Error: Cannot read property 'kind' of undefined

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isFunctionDeclaration (tsWorker.js:21)
    at Object.$n [as getEffectiveTypeAnnotationNode] (tsWorker.js:21)
    at tsWorker.js:21
    at Vm (tsWorker.js:21)
    at Qm (tsWorker.js:21)
    at Jm (tsWorker.js:21)
    at a_ (tsWorker.js:21)
    at tsWorker.js:21
    at Gy (tsWorker.js:21)
    at tsWorker.js:21
    at errors.ts:22
```

[**Playground Link**](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=35&pc=1#code/JYWwDg9gTgLgBAEQKYCMCuBzOAzKERwDkAJqpoQFAUDGEAdgM7zUCG1AFkgFxwt0CeAbQC6cALxwRVWo3gBZAIIANAPoAZAPIBxAMri4ARgAMR6fSZw6LEEgZg2tnkyjA6GEfqkUA9N5zQ4CDQoODQGJABaVnCAGjgQFjA4YAYcFiYkKDj0uCgkGBckADdXLCKWABs0W2TU7HSYTLgYdj44AHdgFrgdfMCQjRQAKyRqGBpzeCQrFAqkYgA5a1t7akc4OUSAHmdSuILqgD59OiR2je3dt32oI4AKAEoqJAAPSFg4Unq0CvhsNDoY2A9EQZAwdysNjsDicBVKDx4yHQGAAdEjMBgmgBvChwOAyCykZE8Pj8fTo8GQlYOJ54qnQtYMFFgMLsCHLBlIJ640HIlHTFizJDsqGrWwooYQVx3QgxQgPbl4omYFEVCBYCR3FHalhQDAMB7iY44vF41gcJDM1l3XX62mm3xwADWSCQYFKhhMcDV+tqcCGYXgLDgnGCKRgwGoKLgABVOLkkJVmrdASwI258fgahU05keXjgNg4HdzZxVdMMN1jopVJpdIaTaazWwywx2IWYI983AAL7dwvFgVCxYcsVM1oMEXUtYKuCNpsEiBzflQPBQLU6vUG7t9vF9nl5GDBOifMEUfcU-kzOb6Kecw1iY08odzEeihxM8Kd+lim7VJ59kAA)

### PR DESCRIPTION
**Pull request by elibarzilay**
Test that `parentSymbol.valueDeclaration` exists.

Fixes #38532

### CODE REVIEW

**Comment by elibarzilay** [comment]
I'm not sure about the name of the test file...

File: tests/cases/compiler/expandoFunctionContextualTypesNoValue.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// GH #38532
+import Foo from "blah";
+
+export function Foo() { }
+
+Foo.bar = () => { };
```
Comment (weswigham) [inline tests/cases/compiler/expandoFunctionContextualTypesNoValue.ts:6]: Does this need to actually have a parameter to invoke the contextual typing machinery?

Comment (elibarzilay) [reply tests/cases/compiler/expandoFunctionContextualTypesNoValue.ts:6]: The bug report had one, but it got there with or without an argument.  (And adding a second test file seems like an overkill for a tiny fix...)
