### PR TITLE
Stop erroneous match of midfile sourceMappingUrl, fix runtests-browser

### LINKED ISSUE #19075: `gulp browserify` broken
```
Error: ENOENT: no such file or directory, open '/home/andy/TypeScript_1/TypeScript/src/harness/unittests/${outFileName}.map`);'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.readFileSync (/home/andy/TypeScript_1/TypeScript/node_modules/sander/src/methodMakers/standardMethod.js:47:27)
    at getMapFromUrl (/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/utils/getMapFromUrl.js:32:22)
    at getMap (/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/utils/getMap.js:19:10)
    at Node.loadSync (/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/Node.js:70:15)
    at /home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/Node.js:89:10
    at Array.map (<anonymous>)
    at Node.loadSync (/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/Node.js:83:31)
    at /home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/Node.js:89:10
    at Array.map (<anonymous>)
    at Node.loadSync (/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/Node.js:83:31)
    at Object.loadSync (/home/andy/TypeScript_1/TypeScript/node_modules/sorcery/src/index.js:15:7)
    at /home/andy/TypeScript_1/TypeScript/Gulpfile.ts:818:35
    at /home/andy/TypeScript_1/TypeScript/node_modules/browserify/index.js:779:13
    at ConcatStream.<anonymous> (/home/andy/TypeScript_1/TypeScript/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/home/andy/TypeScript_1/TypeScript/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/home/andy/TypeScript_1/TypeScript/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/home/andy/TypeScript_1/TypeScript/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at Readable.onend (/home/andy/TypeScript_1/TypeScript/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Readable.emit (events.js:207:7)
    at endReadableNT (/home/andy/TypeScript_1/TypeScript/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The [readme](https://github.com/Rich-Harris/sorcery#sorceryjs) for sorcery does indicate that it's a work in progress, so maybe we shouldn't be using it.
@weswigham Do you know what might have caused this to change? It was working fairly recently, although it might be broken now because I updated my `node_modules`.

### PR DESCRIPTION
**Pull request by weswigham**
[As you can see](https://github.com/Microsoft/TypeScript/search?l=TypeScript&q=sourceMappingURL&type=&utf8=%E2%9C%93), this is not the first time we have had to contend with our build tools being a little loose with what they'll consider as a valid `sourceMappingURL` comment. Twas not a dependeny update that broke us, but the introduction of another such psuedo-comment.

Fixes #19075

### CODE REVIEW

File: src/harness/unittests/compileOnSave.ts [hunk 1]
```diff
@@ -619,7 +619,7 @@ namespace ts.projectSystem {
             assert.isTrue(host.fileExists(expectedOutFileName));
             const outFileContent = host.readFile(expectedOutFileName);
             verifyContentHasString(outFileContent, file1.content);
-            verifyContentHasString(outFileContent, `//# sourceMappingURL=${outFileName}.map`);
+            verifyContentHasString(outFileContent, `//# ${"sourceMappingURL"}=${outFileName}.map`); // Sometimes tools can sometimes see this line as a source mapping url comment, so we obfuscate it a little
```
Comment (mihailik) [inline src/harness/unittests/compileOnSave.ts]: Sometimes tools can sometimes?
