### PR TITLE
Import statement completions

### LINKED ISSUE #31658: Provide full import statement text from auto-import suggestions
*Edit from @DanielRosenwasser*

Given

```ts
import { someThi/**/
```

or

```ts
import { someThi/**/ }
```

The suggestion is to look for auto-imports to and to fully complete the paths with

```ts
import { someThing } from "./some/path"
```

____

- VSCode Version: Version 1.35.0-insider (1.35.0-insider)
- OS Version: macos 10.14.5

Steps to Reproduce:

1. I'm working on a react project. I have a file that does export const Buttons
2.In another file I do import { Button... and I expect auto-complete to display Buttons and hitting enter to complete the path. 

But intelliSense just shows the text Buttons (with abc in front of it) and hitting enter doesn't add the path to the import.

If I try to directly import the component from a function - then auto-import correctly adds the Component to the top of the file with an import {Button} from 'correct_path'

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by andrewbranch**
<details>
<summary><strong>Screen capture demo</strong></summary>

Kapture 2021-03-12 at 16 21 03
</details>

Enables auto-import-style completions on import statements themselves, e.g.

```ts
import useS|
```

can offer a completion to

```ts
import { useState| } from "react";
```

(The `|` indicates the position of the cursor both before and after the completion.)

This PR is large because, although the feature appears very similar to existing auto imports, it requires us to resolve module specifiers immediately instead of in a subsequent completion details request. Being able to do that with any reasonable amount of code reuse required quite a bit of untangling. The implementation is explained in some detail in code review comments, but note that a large amount of the PR diff is just functions being shuffled around.

Note also this feature is opt-in via a user preference (`includeCompletionsForImportStatements`) because it requires corresponding editor changes. So, you won’t be able to test this yourself without building my VS Code PR as well.

### Design

- When these completions are offered, they are generally the same as the auto-imports you’d get elsewhere in the file:
  - Same list of modules and exports are considered, but we require the first character of what you’ve typed so far to match the first character of the export name, instead of just the “contains characters in order” check. This significantly reduces the number of matches we see after you type a single character, which lets us return results way faster.
  - Quote preference is respected and semicolon usage is inferred
  - Inference of preferred import style is same as normal auto-import rules (i.e., when `esModuleInterop` introduces ambiguity we try to give you what you want)
- Does not work on `const foo = require("mod")`; only works on imports (though `import foo = require("mod")` is supported in TS)
- Does not work on imports where there’s already a module specifier, for I think obvious reasons
- Does not work on imports where there’s already another identifier in the declaration, like `import foo, { bar|` or `import { foo, bar|`. This could be relaxed a bit later, but it was complicated and seemed fairly low value.
- Inserts a snippet, so your cursor snaps to the end of the identifier you were completing, then you can tab to the end of the statement.
- Due to client limitations (`replacementRange` must be a single line), does not work on imports that already span multiple lines, e.g.
   ```ts
   import {
     foo|
   }
   ```

### Performance

<details>
<summary>Following measurements assume these dependencies</summary>

```json
"dependencies": {
    "@angular/core": "^10.0.7",
    "@types/eslint": "^7.2.5",
    "@types/lodash": "^4.14.165"
    "@angular/material": "^11.2.5",
    "@reduxjs/toolkit": "^1.5.0",
    "@types/node": "^14.14.17",
    "@types/puppeteer": "^5.4.2",
    "@types/react": "^17.0.3",
    "@types/serverless": "^1.78.17",
    "aggregate-error": "^3.1.0",
    "antd": "^4.5.1",
    "aws-sdk": "*",
    "eslint": "^7.14.0",
    "lodash": "4.17.15",
    "mobx": "^5.15.4",
    "moment": "2.24.0",
    "puppeteer": "^6.0.0",
    "react": "16.12.0",
    "typescript": "^4.3.0-dev.20210322",
  }
```
</details>

#### Import statement completions

Stress-tested with `aws-sdk` installed, which has just a ridiculous number of exports. First draft took several seconds without caches, which was too much, so I decided to require the first character of the identifier to match the first character of the export name before continuing the fuzzy match. So whereas regular auto imports will offer `useState` when you have just typed `state`, import statement completions require you to start with `u`.

* `import a|`: 865 ms (3604 entries)
* `import b|`: 456 ms(1279 entries) (some cache benefit from previous request)
* `import a|`: 625 ms (max cache benefit)

After `npm rm aws-sdk`:

* `import a|`: 116 ms (197 entries)
* `import b|`: 44 ms (105 entries)
* `import a|`: 70 ms

#### Normal auto imports

The first draft of this PR incurred about a 15% performance penalty on all auto-imports; that has now been reduced to zero or has improved performance in some scenarios. The auto import cache has been split into two pieces that are independently more durable and more reusable than they were combined.

Previously, the process went something like this:

1. For each module in the program:
2. Can we come up with a module specifier from the importing file to that module without crossing someone else’s node_modules?
3. If that module specifier is a bare specifier (e.g. `"lodash"`), do the package.json files visible to the importing file list that package?
4. If the answer to both of those are yes, proceed with adding info about that module's exports to a big array, deduplicating re-exports along the way.
5. Save all that info in a cache.
6. Iterate the big map of info and pull out the exports whose names match the partial identifier typed so far.

The main problem with this process is that steps (2) and (3) are pretty expensive, and that work might go to waste after the filter in step (6) is applied. The other problem is that they are dependent on the location of the importing file and the contents of any package.jsons visible to that file, which makes us have to invalidate the cache a lot. Too many inputs combined into a single cache means that when we invalidate the cache, a lot of work that isn’t actually invalid has to be thrown away. Now, we cache “what are the exports and re-exports of every module” and “is file A importable from file B, and by what module specifier” separately. So the process becomes more like:

1. For each module in the program:
2. Add info about that module’s exports to a big map (_not_ throwing away info about re-exports)
3. Cache that big map
4. Iterate the big map of info and pull out the exports whose names match the partial identifier typed so far.
5. For each name match, see if the module is importable by the importing file (both by module specifier validity and package.json filtering)
6. Add that module specifier / importability info to a cache.

This means for subsequent auto imports, we have better chances of getting cache hits, _and_ we do less expensive work up front, even with the caches are totally empty.

Triggering auto import completions in a project with

| | dev.20210322 (ms) | This PR (ms) |
|-|------------------:|--------------:|
| `completionInfo` (cold) | 259 | 264 |
| `completionEntryDetails` | 102 | 74 |
| `completionInfo` (cached) | 68 | 63 |
| `completionEntryDetails` | 44 | 35 |

### To-do

- [x] Do we need a separate user preference for enabling snippet-formatted completions? **Yes, done**.
- [x] Do some profiling to make sure normal completions / auto imports are not slower
- [x] Check performance when there are huge numbers of possible modules to import from (e.g. with `aws-sdk` installed) and probably implement some limits/mitigations there. **Increased strictness of filter to make list smaller.**
- [x] Get approval on corresponding [VS Code PR](https://github.com/microsoft/vscode/pull/119009)
- [ ] Finish and merge corresponding TypeScript-VS PR (need help from @uniqueiniquity on this one 🙏)

Fixes #31658

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot shush it’s just a draft

**Comment by andrewbranch** [comment]
@typescript-bot pack this

File: src/services/completions.ts [hunk 1]
```diff
@@ -598,8 +619,55 @@ namespace ts.Completions {
             has: name => uniques.has(name),
             add: name => uniques.set(name, true),
         };
+
+        function shouldIncludeSymbol(symbol: Symbol, symbolToSortTextMap: SymbolSortTextMap): boolean {
```
Comment (andrewbranch) [inline src/services/completions.ts:623]: This was just moved from a separate filter statement elsewhere into this spot where we already iterate through the whole list. Should be a small performance improvement, but I moved it because of some order-of-operations change that I honestly don’t remember anymore.

File: src/services/completions.ts [hunk 2]
```diff
@@ -1153,7 +1249,7 @@ namespace ts.Completions {
             Debug.assertEachIsDefined(tagSymbols, "getJsxIntrinsicTagNames() should all be defined");
             tryGetGlobalSymbols();
             symbols = tagSymbols.concat(symbols);
-            completionKind = CompletionKind.MemberLike;
+            completionKind = CompletionKind.Global;
```
Comment (andrewbranch) [inline src/services/completions.ts:1251]: AFAICT this `completionKind` had no effect prior to me moving the aforementioned filtering code, but was conceptually wrong, and changing it to be conceptually right allowed me to move the filter.

File: src/services/completions.ts [hunk 3]
```diff
@@ -1349,13 +1446,24 @@ namespace ts.Completions {
                 const nameSymbol = leftMostName && typeChecker.getSymbolAtLocation(leftMostName);
                 // If this is nested like for `namespace N { export const sym = Symbol(); }`, we'll add the completion for `N`.
                 const firstAccessibleSymbol = nameSymbol && getFirstSymbolInChain(nameSymbol, contextToken, typeChecker);
-                if (firstAccessibleSymbol && !symbolToOriginInfoMap[getSymbolId(firstAccessibleSymbol)]) {
+                if (firstAccessibleSymbol && addToSeen(seenPropertySymbols, getSymbolId(firstAccessibleSymbol))) {
```
Comment (andrewbranch) [inline src/services/completions.ts:1448]: Small tweaks here due to changing the origin info map to be keyed by index instead of by symbol id—we now need a Map for deduplication here, since symbol duplication is explicitly allowed in other cases.

File: src/services/completions.ts [hunk 4]
```diff
@@ -1667,134 +1687,52 @@ namespace ts.Completions {
...
+            exportInfo.forEach((info, key) => {
+                const [symbolName] = key.split("|");
+                if (!detailsEntryId && isStringANonContextualKeyword(symbolName)) return;
+                const isCompletionDetailsMatch = detailsEntryId && some(info, i => detailsEntryId.source === stripQuotes(i.moduleSymbol.name));
+                if (isCompletionDetailsMatch || stringContainsCharactersInOrder(symbolName.toLowerCase(), lowerCaseTokenText)) {
+                    // If we don't need to resolve module specifiers, it doesn't matter which SymbolExportInfo
+                    // we use. Each is importable by the same name and resolves to the same declaration.
+                    const { moduleSpecifier, exportInfo } = resolveModuleSpecifiers
+                        ? codefix.getBestImportFixForExports(info, sourceFile, /*position*/ undefined, /*preferTypeOnlyImport*/ false, /*useRequire*/ false, program, host, preferences)
+                        : { moduleSpecifier: undefined, exportInfo: info[0] };
```
Comment (andrewbranch) [inline src/services/completions.ts:1706]: This is the real crux of the PR. In `getSymbolsFromOtherSourceFileExports`, we deduplicated re-exports on the fly, since they don’t matter until we need module specifiers. But for import statement completions, we need to resolve module specifiers up front (for reasons discussed beginning around https://github.com/microsoft/TypeScript/issues/31658#issuecomment-738455502), so `getSymbolsFromOtherSourceFileExports` was utterly unusable.

Now, instead of tossing out re-exports, we let `codefix.getSymbolToExportInfoMap` group exports (the grouping strategy is discussed in an earlier review comment). Then, if we are being asked to eagerly resolve module specifiers, we can send all the re-exports in the group to `codefix.getBestImportFixForExports`, and if we are just being asked to show an auto-import completion as we’ve always done, we simply pick the first export in the group, since they’re interchangeable until we need module specifiers. This lets us use 90% of the same code between import statement completions (the new feature in this PR) and regular auto imports.

File: src/server/project.ts [hunk 5]
```diff
@@ -1214,54 +1242,6 @@ namespace ts.server {
...
-            for (const ambientModuleName of newSourceFile.ambientModuleNames) {
-                const isMatchingModuleDeclaration = (node: Statement) => isNonGlobalAmbientModule(node) && node.name.text === ambientModuleName;
-                oldFileStatementIndex = findIndex(oldSourceFile.statements, isMatchingModuleDeclaration, oldFileStatementIndex + 1);
-                newFileStatementIndex = findIndex(newSourceFile.statements, isMatchingModuleDeclaration, newFileStatementIndex + 1);
-                if (oldSourceFile.statements[oldFileStatementIndex] !== newSourceFile.statements[newFileStatementIndex]) {
-                    return false;
-                }
-            }
-            return true;
-        }
```
Comment (andrewbranch) [inline src/server/project.ts:1263]: Moved into the cache itself in utilities.ts

File: src/server/protocol.ts [hunk 6]
```diff
@@ -2308,9 +2316,14 @@ namespace ts.server.protocol {
...
         /**
-         * Human-readable description of the `source` from the CompletionEntry.
+         * @deprecated Use `sourceDisplay` instead.
          */
         source?: SymbolDisplayPart[];
+
+        /**
+         * Human-readable description of the `source` from the CompletionEntry.
+         */
+         sourceDisplay?: SymbolDisplayPart[];
```
Comment (andrewbranch) [inline src/server/protocol.ts:2326]: Aiming to stop overloading the meaning of `source` between `CompletionEntry` and `CompletionEntryDetails`. In an ideal world, `source` is the machine-readable module name for the auto-import, and `sourceDisplay` is the human-readable module specifier for it, no matter whether you’re looking at `CompletionEntry` or `CompletionEntryDetails`. In reality, we will continue to set `CompletionEntryDetails["source"]` to the human-readable module specifier for backward compatibility, but I’ve marked it as deprecated.

File: src/services/completions.ts [hunk 7]
```diff
@@ -103,62 +122,6 @@ namespace ts.Completions {
...
-        symbolName: string;
-        origin: SymbolOriginInfoExport;
-    }
-    export interface ImportSuggestionsForFileCache {
-        clear(): void;
-        get(fileName: string, checker: TypeChecker, projectVersion?: string): readonly AutoImportSuggestion[] | undefined;
-        set(fileName: string, suggestions: readonly AutoImportSuggestion[], projectVersion?: string): void;
-        isEmpty(): boolean;
-    }
-    export function createImportSuggestionsForFileCache(): ImportSuggestionsForFileCache {
```
Comment (andrewbranch) [inline src/services/completions.ts:117]: Cache has moved to utilities, and its underlying format has been slightly tweaked to be suitable for resolving module specifiers when needed, which will also let us use it for code fixes in the future.

File: src/services/completions.ts [hunk 8]
```diff
@@ -1667,134 +1690,75 @@ namespace ts.Completions {
...
+            exportInfo.forEach((info, key) => {
+                const symbolName = key.substring(0, key.indexOf("|"));
+                if (!detailsEntryId && isStringANonContextualKeyword(symbolName)) return;
+                const isCompletionDetailsMatch = detailsEntryId && some(info, i => detailsEntryId.source === stripQuotes(i.moduleSymbol.name));
+                if (isCompletionDetailsMatch || stringContainsCharactersInOrder(symbolName.toLowerCase(), lowerCaseTokenText)) {
+                    // If we don't need to resolve module specifiers, we can use any re-export that is importable at all
+                    // (We need to ensure that at least one is importable to show a completion.)
+                    const { moduleSpecifier, exportInfo } = resolveModuleSpecifiers
+                        ? codefix.getModuleSpecifierForBestExportInfo(info, sourceFile, program, host, preferences)
+                        : { moduleSpecifier: undefined, exportInfo: find(info, isImportableExportInfo) };
```
Comment (andrewbranch) [inline src/services/completions.ts:1716]: This is the real crux of the PR. In `getSymbolsFromOtherSourceFileExports`, we deduplicated re-exports on the fly, since they don’t matter until we need module specifiers. But for import statement completions, we need to resolve module specifiers up front (for reasons discussed beginning around https://github.com/microsoft/TypeScript/issues/31658#issuecomment-738455502), so `getSymbolsFromOtherSourceFileExports` was utterly unusable.

Now, instead of tossing out re-exports, we let `codefix.getSymbolToExportInfoMap` group exports (the grouping strategy is discussed in an earlier review comment). Then, if we are being asked to eagerly resolve module specifiers, we can send all the re-exports in the group to `codefix.getModuleSpecifierForBestExportInfo`, and if we are just being asked to show an auto-import completion as we’ve always done, we simply pick the first usable export in the group, since they’re interchangeable until we need module specifiers. This lets us use 95% of the same code between import statement completions (the new feature in this PR) and regular auto imports.

File: src/services/utilities.ts [hunk 9]
```diff
@@ -2808,6 +2809,125 @@ namespace ts {
         }
     }
 
+    export interface PackageJsonImportFilter {
```
Comment (andrewbranch) [inline src/services/utilities.ts:2812]: All this added stuff is just moved from completions.ts, importFixes.ts, or project.ts with very little change. The sharing between those three was ad-hoc and getting unwieldy.

File: src/services/utilities.ts [hunk 10]
```diff
@@ -2956,5 +3076,211 @@ namespace ts {
...
+                return cache ? cache.size : 0;
+            }
+        };
+        if (Debug.isDebugging) {
+            Object.defineProperty(wrapped, "__cache", { get: () => cache });
+        }
+        return wrapped;
+    }
+
+    export function isImportableFile(
```
Comment (andrewbranch) [inline src/services/utilities.ts:3233]: This function is somewhat changed in its move from importFixes.ts. It now takes advantage of the new module specifier cache, and combines the previously separate checks of “can I come up with a module specifier” and “do the package.jsons I can see let me use that module specifier.”

File: src/server/protocol.ts (hunk 6 above)
Comment (DanielRosenwasser) [reply src/server/protocol.ts:2347]: The editor only pulls on these one at a time right?

File: src/services/completions.ts [hunk 11]
```diff
@@ -176,6 +139,14 @@ namespace ts.Completions {
             return undefined;
         }
 
+        if (triggerCharacter === " ") {
+            // `isValidTrigger` ensures we are at `import |`
+            if (!(preferences.includeCompletionsForImportStatements && preferences.includeCompletionsWithInsertText)) {
+                return undefined;
+            }
+            return { isGlobalCompletion: true, isMemberCompletion: false, isNewIdentifierLocation: true, isIncomplete: true, entries: [] };
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:147]: Consider

```suggestion
            if (preferences.includeCompletionsForImportStatements && preferences.includeCompletionsWithInsertText) {
                return { isGlobalCompletion: true, isMemberCompletion: false, isNewIdentifierLocation: true, isIncomplete: true, entries: [] };
            }
            return undefined;

```

File: src/server/project.ts [hunk 12]
```diff
@@ -966,6 +970,10 @@ namespace ts.server {
                 info.detachFromProject(this);
             }
 
+            if (info.getRealpathIfDifferent()) {
```
Comment (sheetalkamat) [inline src/server/project.ts:973]: I think it would be better to take info as parameter in `onFileAddedOrRemoved` and do it there so that its always done consistently?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/server/project.ts (hunk 12 above)
Comment (andrewbranch) [reply src/server/project.ts:973]: That’s what exactly what I tried first, but that function isn’t called in a lot of cases! I found `this.hasAddedOrRemovedFiles` to be pretty unreliable in general. The problem is that it never gets called only when `info.detachFromProject()` gets called, so when the `detachFromProject` parameter here is false, this was the closest place I could get.

Comment (sheetalkamat) [reply src/server/project.ts:973]: Thats because you need to pick  dc6f9b428b360c49f443f643f90faab0cca4859d which was missed before.

Comment (andrewbranch) [reply src/server/project.ts:973]: Ah perfect, thank you! Let me take a look.

Comment (andrewbranch) [reply src/server/project.ts]: Fixed 👍

**Review by sheetalkamat — APPROVED** [review]

**Comment by jasonwilliams** [comment]
Hey @andrewbranch this doesn't appear to be working for me am I doing something wrong?
styledNoComplete

**Comment by andrewbranch** [comment]
It looks like something might have broken on the VS Code side. It doesn't work for me either at the moment, but I can see TS Server returning the right things in the log. I'll take a look. Thanks!

**Comment by rchl** [comment]
Have it been considered to add support for that in the LSP spec? Or is it already supported?

That question maybe belongs better in https://github.com/microsoft/vscode/pull/119009 but that one is locked.

**Comment by andrewbranch** [comment]
I made sure that everything we’re doing with VS Code can also be done over LSP so that this will work in VS once their TS completions support swaps over to LSP. I actually have a draft PR up for that in the TypeScript-VS codebase (which is not open source). I’m not sure if that answers your question—let me know if you have more specific questions, and I can try to answer or pull in @uniqueiniquity who is our resident LSP expert.

**Comment by jasonwilliams** [comment]
> It looks like something might have broken on the VS Code side. It doesn't work for me either at the moment, but I can see TS Server returning the right things in the log. I'll take a look. Thanks!

Hey @andrewbranch was that issue ever fixed? Or is that what you need to change in the VSCode repo?

**Comment by andrewbranch** [comment]
@jasonwilliams it was fixed at https://github.com/microsoft/vscode/pull/121975

**Comment by rchl** [comment]
> I’m not sure if that answers your question—let me know if you have more specific questions, and I can try to answer or pull in @uniqueiniquity who is our resident LSP expert.

I guess the more specific question I have is whether that functionality requires changes to the LSP spec (https://github.com/microsoft/language-server-protocol) and if so whether those were proposed or even already implemented?

**Comment by andrewbranch** [comment]
No, this feature can be implemented with LSP 3.16 (and likely earlier versions) without changes. From the protocol standpoint, this is actually a good bit simpler than normal auto imports (though those are possible with LSP too). The only somewhat interesting thing about this feature is the tab stop at the end, which is supported via [snippet text](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax). The only caveat is that I made the space character a trigger character _only when preceded by_ `/^import/` via some special logic in VS Code’s TypeScript support layer, which I don’t think is possible in LSP. However, that was only to work around a conflict with a snippet completion whose name is `import statement` preventing a new completions request triggering on `import s`. It’s a little kludgy and if it came down to it, we could find other workarounds (the easiest one being ensuring that snippet completions don’t have multi-word names, since they can unexpectedly block new requests anywhere).
