### PR TITLE
Fix generic mapped type relationships

### LINKED ISSUE #18201: T[K] not assignable to Partial<T[K]>
**TypeScript Version:**  2.5.2

**Code**

```ts
function f<T, K extends keyof T>(t: T, k: K): Partial<T[K]> {
  return t[k];
}
```

**Expected behavior:**
No error. In my understanding, `X` should always be assignable to `Partial<X>`.

**Actual behavior:**
```
TS2322: Type 'T[K]' is not assignable to type 'Partial<T[K]>'.
  Type 'T[string]' is not assignable to type 'Partial<T[K]>'.
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #18201.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@mhegazy This fix makes T related to Partial<T> for any generic T (as opposed to just a type parameter).

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9454,32 +9454,30 @@ namespace ts {
                         }
                     }
                 }
+                else if (isGenericMappedType(target) && !isGenericMappedType(source) && getConstraintTypeFromMappedType(<MappedType>target) === getIndexType(source)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: There's a branch lower down that checks whether `target` is a generic mapped type. Can this be performed there?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: No because that particular section of code is only entered if `source` is an object or intersection type.
