### PR TITLE
fix(53722): Overloaded constructors: 'TValue' not assignable to 'string'

### LINKED ISSUE #53722: Overloaded constructors: 'TValue' not assignable to 'string'
# Bug Report

### 🔎 Search Terms

constructor, overload, TValue, jsdoc

### 🕗 Version & Regression Information

- This changed between versions "recent"? and ~1.77.1-ish
- I was unable to test this on prior versions because PR #52577 was not implemented (there was no reliable way to define overloads for class constructors)

Recent PR fixed the use of jsdoc-defined overloads for class constructors
* Bug report: #52477
* Bug fix (for jsdoc `@overload`): #52577

That seems to have made it in to recent VS Code release; I'm using:

- Version: 1.77.1 (user setup)
- Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
- Date: 2023-04-04T23:21:11.906Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Windows_NT x64 10.0.19045
- Sandboxed: Yes

### ⏯ Playground Link

(Updated to exhibit error): [Playground link](https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=100&ts=5.1.0-dev.20230410&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJJkBbABwBsBDE0AFQDVrKBXZAoqAT3OVADeAZUgAnAJYA7AOYBpZNwCy1cgB4mLdgD4Avp2AZkAD3IB7UZFDwa0aKBESZ8pStDGSkgCZ3l5QQVBA3HxA0K54U0loMVZ4SHMAsIhTADdkUUpTak9EwK5yalFqUkEASRIigCNKZFUAbWjHaQAaBmY2ZABdXVBxCupqjlC8iAKikoFGqWkdUAAzc1JcwhA8ZfDIxtj40XXktIysnOHCUcLiwSmZWYXRJZOcVZDhjaiYuISH-fTM7L3wMYXATldIDGr1K4tNqaLo9PqgwbrJ7-CJvUTbT4vb6HP4PAzDVFbD6iAAUAEFWgAhACU-hOoWgrD4pOpy1CIFAADpubk9Llgv9UukJJ4hliAecJpDZmgFP9ARMNB1ZikYf9RMhIKxRFFBJBEOJoHo8bloJqSbLuK1VR1aQI2UEwJJFixxAAvfiW0AkjWkIWeebmUCVDUpPrcVn0wIarU60CM5mcs2QC0Ka0wyOhPR87B4Yi8fjCMTTZy+VSSVikSrpHqPDCEywLUygAC8oEkyAA7vZi04FL4SbSOapYLArKZRaADZJLMKgyo+IU7CgNUA)

### 💻 Code

```es6
// @ts-check

/**
 * @template TValue
 * @type {StringKeyMap<TValue>}
 */
export class StringKeyMap extends Map {
    /**
     * @constructor
     * @overload
     * @param {Iterable<[string, TValue]>} iterable
     * @param {string} form
     *//**
     * @constructor
     * @overload
     * @param {string} form
     *//**
     * @constructor
     * @overload
     * @param {Iterable<[string, TValue]>} iterable
     *//**
     * @constructor
     * @overload
     */
    constructor(A, B) {
        super()
        // ...
    }

    /**
     * @override
     * @param {string} key
     * @param {TValue} value
     * @returns {this}
     */
    set(key, value) {
        // normalize key (removed for brevity)
        return super.set(key, value)
    }
}


/** @type {StringKeyMap<number>} */
const foo = new StringKeyMap() // <-- code hint error appears here
```

### 🙁 Actual behavior

In VS Code editor, if I try and instantiate my class using code like this:

```es6
class foo {
    // ...

    /** @type {StringKeyMap<string>} */
    #tags

    /**
     * @param {Iterable<string>} tags
     */
    constructor(tags) {
        this.#tags = new StringKeyMap() // <-- error shows here
    }

    // ....
}
```

This happens:

image

Hovering the error shows:

image

The code still works fine when used in node, the issue is constrained to the VS Code editor which seems to think `TValue` is a type rather than a template.

Possibly related to comment here about type checking being broken: https://github.com/microsoft/TypeScript/issues/52477#issuecomment-1414165166

### 🙂 Expected behavior

`TValue` is a template and thus should adopt the `@type {StringKeyMap<string>}` defined for `#tags` .

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #53722

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14541,9 +14541,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 }
             }
 
-            const classType = declaration.kind === SyntaxKind.Constructor ?
-                getDeclaredTypeOfClassOrInterface(getMergedSymbol((declaration.parent as ClassDeclaration).symbol))
-                : undefined;
+            const constructorDeclaration = tryGetConstructorDeclaration(declaration);
+            const classType = constructorDeclaration ? getDeclaredTypeOfClassOrInterface(getMergedSymbol((constructorDeclaration.parent as ClassDeclaration).symbol)) : undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts:14545]: this line is pretty long. Can you return to the original formatting?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14559,6 +14558,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return links.resolvedSignature;
     }
 
+    function tryGetConstructorDeclaration(declaration: SignatureDeclaration | JSDocSignature) {
+        const node = isJSDocSignature(declaration) ? getEffectiveJSDocHost(declaration) : declaration;
```
Comment (sandersn) [inline src/compiler/checker.ts:14562]: isJSDocSignature is checking for declarations like `@callback`, right? Or is it closure signature syntax like `function(string): string`?

Either way, do we have tests that fail without this check? I don't see them in the new test, so if not, we'll need to expand it.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -14541,9 +14541,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 }
             }
 
-            const classType = declaration.kind === SyntaxKind.Constructor ?
-                getDeclaredTypeOfClassOrInterface(getMergedSymbol((declaration.parent as ClassDeclaration).symbol))
-                : undefined;
+            const constructorDeclaration = tryGetConstructorDeclaration(declaration);
```
Comment (sandersn) [inline src/compiler/checker.ts:14544]: I'd like to inline tryGetConstructorDeclaration because
- is only two lines long and used once
- its name doesn't mention jsdoc, even though that's half of the code.

The overhead of the function declaration, especially since it needs a longer name, makes inlining it desirable.

**Review by sandersn — CHANGES_REQUESTED** [review]
Test and style requests

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:14545]: Reverted

File: src/compiler/checker.ts (hunk 3 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:14544]: Removed unnecessary helper

File: src/compiler/checker.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: I think the key here is to check if the host is a constructor to get the local type parameters of the class.

**Review by sandersn — APPROVED** [review]
