### PR TITLE
Ensure whitespace jsx elements are not counted when determining if a jsx child is the only child

### LINKED ISSUE #40774: Unexpected JSX output for children with jsx: react-jsx
**TypeScript Version:**  4.1.0-dev.20200925

**Search Terms:** jsx

**Code**

```ts
import type * as React from 'react';

console.log(
  <div>
    <div />
  </div>
)

console.log(
  <div>
    <div />
    <div />
  </div>
)

console.log(
  <div>
    {[1, 2].map(i => <div key={i}>{i}</div>)}
  </div>
)
```

**Expected behavior:**
Something closer to Babel's output, notice the lack of arrays for the `children` prop:
```js
import { jsxs as _jsxs } from "react/jsx-runtime";
import { jsx as _jsx } from "react/jsx-runtime";
console.log( /*#__PURE__*/_jsx("div", {
  children: /*#__PURE__*/_jsx("div", {})
}));
console.log( /*#__PURE__*/_jsxs("div", {
  children: [/*#__PURE__*/_jsx("div", {}), /*#__PURE__*/_jsx("div", {})]
}));
console.log( /*#__PURE__*/_jsx("div", {
  children: [1, 2].map(i => /*#__PURE__*/_jsx("div", {
    children: i
  }, i))
}));
```

**Actual behavior:**
```js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
console.log(_jsxs("div", { children: [_jsx("div", {}, void 0)] }, void 0));
console.log(_jsxs("div", { children: [_jsx("div", {}, void 0),
        _jsx("div", {}, void 0)] }, void 0));
console.log(_jsxs("div", { children: [[1, 2].map(i => _jsx("div", { children: i }, i))] }, void 0));
```
- On the first line, `jsxs` is used, and the one child is wrapped in an array, unlike in Babel's output. I believe this will break code that expect a single child node as the `children` prop.
- The second line looks good.
- On the third line, the children are incorrectly wrapped in an array. This can break code expecting `children` to be an array of jsx nodes, instead I get an extra array wrapping my array of nodes.
- The `void 0` for `key`-less nodes is also unnecessary.

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.0-insiders.20200925#code/JYWwDg9gTgLgBDAnmApnAVHAhgZzgJRSwGN4AzKCEOAciiNJoG4AoF4iAOxwgBsUAdLwgBzABQs4cADwATYADcAfJKkz5CuAHoVU6Vo0qAlGw7c+g4eNVzFutbc07Vejdvv7DLE+y49+QqISrnYucADeANoAjAA0cABMALoCIFhgYsBwALxK6opwANYoiNnhwAC+SuUVnnZGFTYGoUZAA
I can't configure `jsx` to be `react-jsx` in the playground.

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #40774

### CODE REVIEW

File: tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+)
+
+//// [jsxJsxsCjsTransformNestedSelfClosingChild.js]
+"use strict";
+exports.__esModule = true;
+var jsx_runtime_1 = require("react/jsx-runtime");
+console.log(jsx_runtime_1.jsxs("div", { children: jsx_runtime_1.jsx("div", {}, void 0) }, void 0));
+console.log(jsx_runtime_1.jsxs("div", { children: [jsx_runtime_1.jsx("div", {}, void 0),
+        jsx_runtime_1.jsx("div", {}, void 0)] }, void 0));
+console.log(jsx_runtime_1.jsxs("div", { children: [1, 2].map(function (i) { return jsx_runtime_1.jsx("div", { children: i }, i); }) }, void 0));
```
Comment (nstepien) [inline tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js:31]: Should the first and third examples use `jsx` instead of `jsxs`? Babel does it, so I'm curious.

**Review by RyanCavanaugh — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

File: tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js (hunk 1 above)
Comment (weswigham) [reply tests/baselines/reference/jsxJsxsCjsTransformNestedSelfClosingChild(jsx=react-jsx).js]: I've updated it to do so - we can always change back if that's not desirable for some reason.
