### PR TITLE
Disambiguate same-named refactors using actionName

### LINKED ISSUE #18844: Two refactors with the same name are hard to test
**TypeScript Version:**  nightly (2.6.0-dev.20170929)

**Code**

```ts
/// <reference path='fourslash.ts' />

////function f() { /*a*/1/*b*/; }

goTo.select("a", "b");
edit.applyRefactor({
    refactorName: "?",
    actionName: "?",
    actionDescription: "?",
    newContent: "?",
});
```

Running this test with the change in #18843 prints:
```
     Error: At line 1, col 15: The expected refactor: ? is not available at the marker location.
Available refactors: Extract Symbol,Extract Symbol
```

Problem: The way `applyRefactor` in `fourslash.ts` is written, there's no way we can assert things about the second refactor, since we match them by name and we'll always find the first one first. (Also, this seems to uncover that we have no tests of it.)

Instead of making the test runner more complicated, we should probably have one refactor with multiple actions, or two refactors with different names.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #18844

### CODE REVIEW

File: src/harness/fourslash.ts [hunk 1]
```diff
@@ -2846,17 +2846,17 @@ Actual: ${stringify(fullActual)}`);
             }
         }
 
-        public applyRefactor({ refactorName, actionName, actionDescription, newContent: newContentWithRenameMarker }: FourSlashInterface.ApplyRefactorOptions) {
+        public applyRefactor({ refactorName, description, actionName, actionDescription, newContent: newContentWithRenameMarker }: FourSlashInterface.ApplyRefactorOptions) {
             const range = this.getSelection();
             const refactors = this.languageService.getApplicableRefactors(this.activeFile.fileName, range);
-            const refactor = refactors.find(r => r.name === refactorName);
+            const refactor = refactors.find(r => r.name === refactorName && description === undefined || description === r.description);
```
Comment (amcasey) [inline src/harness/fourslash.ts]: I don't have a detailed knowledge of precedence in JS, but I would have guessed you needed parens for the `||`.

File: tests/cases/fourslash/extract-const1.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
+/// <reference path='fourslash.ts' />
+
+////const x = /*a*/0/*b*/;
+
+goTo.select("a", "b");
+edit.applyRefactor({
+    refactorName: "Extract Symbol",
+    description: "Extract constant",
```
Comment (amcasey) [inline tests/cases/fourslash/extract-const1.ts]: Is the description necessary?  The action name should be unique.
