### PR TITLE
fix(44466): Fixes parsing contextual keyword casts as arrow functions

### LINKED ISSUE #44466: Parse error on type assertion with contextual keyword in parentheses (override as Type)
# Bug Report

### 🔎 Search Terms

typecast, parentheses, override

### 🕗 Version & Regression Information

Started to see the issue after updating from TypeScript 4.2 to 4.3, initially noticing this when running prettier after updating it https://github.com/prettier/prettier/issues/11018

It also is happening in current 'Nightly' version in the playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2#code/MYewdgzgLgBCBuBTATsglgE0TAvDA3gL4DcAUKJLAEa4wAUCK6WMAhhG2AJ4CUZQA)

### 💻 Code

```ts
const override = {};
const b = (override as any);
```

### 🙁 Actual behavior

Code results in a syntax error.

However it works fine when renaming variable `override` to something else.

### 🙂 Expected behavior

Code above should work

### LINKED ISSUE #49021: Regression with 'out' in `(out as number)`
# Bug Report

### 🔎 Search Terms

regression 4.6 4.7 4.8 out as

### 🕗 Version & Regression Information

This bug is present in "Nightly 4.8.0-dev20220508", it is not in 4.6.2

- This changed between versions 4.6.2 and 4.7.0-dev.20220415 (including 4.8.0-dev.20200508)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220508#code/DYUwLgBA9grpC8ECsBuAsAKAMZQHYGdIBDCRAClmPwlxgFsAjEAJwEp0NNRIooFkOOApAakIFPhCLVajFuyA)

### 💻 Code

```ts
let out = 5;
const a = (out as number);
```

This is reduced from a larger expression, where the parens are necessary to nest the cast inside a ternary operation.

```
class Foo {
  constructor(
    outs: (string | { id: string; start: number })[],
  ) {
    for (const out of outs) {
      const { id, start = 1 } =
        (out as {id: string}).id !== undefined
        ? (out as { id: string; start: number })
        : parse(out as string);
      console.log(id, start);
    }
  }
}
```

### 🙁 Actual behavior

Compiles to
```
let out = 5;
const a = (as, number) => ;
```

This looks like the new [Optional Variance](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#optional-variance-annotations-for-type-parameters) rules are identifying these parentheses as an arrow function, when they are just nesting the cast.

### 🙂 Expected behavior

```
let out = 5;
const a = out;
```

This is a paren-wrapped cast, not a function declaration.

### PR DESCRIPTION
**Pull request by DavidSouther**
Fixes #44466
Fixes #49021

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Can you use the test provided in the #49021?

`tests/cases/conformance/expressions/typeAssertions/variablesWithModifierNamesInAsTypeAssertions01.ts`

```ts
// @declaration: true

let readonly: any = undefined;
let override: any = undefined;
let out: any = undefined;
let declare: any = undefined;

export const a = (readonly as number);
export const b = (override as number);
export const c = (out as number);
export const d = (declare as number);
```

**Comment by DavidSouther** [comment]
@DanielRosenwasser done

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -4538,6 +4538,10 @@ namespace ts {
                 // isn't actually allowed, but we want to treat it as a lambda so we can provide
                 // a good error message.
                 if (isModifierKind(second) && second !== SyntaxKind.AsyncKeyword && lookAhead(nextTokenIsIdentifier)) {
```
Comment (jakebailey) [inline src/compiler/parser.ts:4540]: The fact that `nextTokenIsIdentifier` checks for `async` and `yield` itself makes me feel like there should be some sort of context for `as`, rather than special casing, but like you said on https://github.com/microsoft/TypeScript/issues/44466#issuecomment-1121378110, I'm not entirely certain that there's another expression that can behave like this.

This whole "does this look like an arrow function" is effectively a heuristic and continues to bite us (see: #16241), so I think it's likely ok to disable this heuristic here like you've done.

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -4538,6 +4538,10 @@ namespace ts {
                 // isn't actually allowed, but we want to treat it as a lambda so we can provide
                 // a good error message.
                 if (isModifierKind(second) && second !== SyntaxKind.AsyncKeyword && lookAhead(nextTokenIsIdentifier)) {
+                    if (lookAhead(() => nextToken() === SyntaxKind.AsKeyword)) {
```
[the remark this answers is not in the document]
Comment (DavidSouther) [reply src/compiler/parser.ts:4541]: Done. Thanks for pointing that out!

File: src/compiler/parser.ts (hunk 1 above)
Comment (DavidSouther) [reply src/compiler/parser.ts:4540]: I think the other option is reworking this along the lines Daniel suggested earlier in #44466, but looking for a matched close paren followed by an arrow? But doing that leaves a lot of lookahead for errors to accumulate, and you're not guaranteed to find the matching paren, much less the arrow itself.

Comment (jakebailey) [reply src/compiler/parser.ts:4540]: Yeah, I think that this fix is good as-is; this block (as commented above) is to do better error recovery if someone writes code like `(foo number) => ...`, which is guaranteed to fail to parse later. The likelihood of that broken code appearing _and_ someone legitimately naming a type `as` seems very, very low, so I'm happy with just not having recovery in this case.

**Review by jakebailey — APPROVED** [review]

File: src/compiler/parser.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/parser.ts:4540]: I suppose though, that one could write a test that is `(foo as) => 1234` or something, and see if you should actually return `TriState.Unknown` here instead.

Or, that this should be a `lookAhead` in the if statement before the code you've added (the "isn't actually allowed" one), to better fit with the heuristic.

Comment (jakebailey) [reply src/compiler/parser.ts:4540]: I have tested both, and they both pass the tests in the PR, though they all differ on a test like:

```ts
let out: any = undefined;
type as = any;

export const e = (declare as) => 1234;
```

With the two lookahead versions, you get an emitted `exports.e = declare;`, but with `Unknown`, it actually tries to parse that broken code as an arrow function again and complains about the modifier, and emits:

```js
var e = function (as) { return 1234; };
exports.e = e;
```

Maybe that's better in the error case, preserving the recovery?

@DanielRosenwasser curious as to what you think; I'm not convinced it matters either way if both fix the bug, just an esoteric recovery.

Comment (DanielRosenwasser) [reply src/compiler/parser.ts:4540]: I think this is an okay fix; however, if we add `satisfies` (or any other new infix keyword) then we'll have another similar bug in the future.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
I'm going to cherry-pick this manually.

**Comment by DanielRosenwasser** [comment]
No I'm not, I accidentally merged instead of sqaushed.

@typescript-bot cherry-pick this to release-4.7

**Comment by DanielRosenwasser** [comment]
I guess I am 🙄
