### PR TITLE
check usage before declaration for decorators

### LINKED ISSUE #50349: "used before its declaration" errors not reported when variable/enum/class is used as decorator parameter on class member
# Bug Report

### 🔎 Search Terms
decorator
enum
used before its declaration
TS2448, TS2449, TS2450
isolatedModules
preserveConstEnums

### 🕗 Version & Regression Information

- This is a crash: In the transpiled JavaScript, not in tsc itself.
- This is the behavior in every version I tried (3.1 through 4.7), and I reviewed the FAQ for entries about decorators (https://github.com/Microsoft/TypeScript/wiki/FAQ#decorators)

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=1&ssl=18&ssc=2&pln=3&pc=1#code/PTAEAEFMA8AdIE4EsC2kB2AXAhgGwCKQDGA9gtpmQM4BcomCArpALABQ7AZo+kZkiXSg0mABYkAJoVLlKCABQA3PMzpUGSdAHMAlHWzoAnqADe7AJAJImRgiHydoALwA+UwF8A3O3ft2qWDJMU2FrcSliMgoyUHdQTgQSFFAAIgA6YBFw6Si5FO8ONhBwLMkc2TJ5AFlDAFF0RhQ05VxmAEZHEFAAYTIrPlxjK0CETCpQesbQAHIayZRp0EYqSAlQACNITjJIUCQx0AliXGxZAXsAFQBlACYAFgBWAAYddhgR4KITqnGa7u-xmY2KAQRBShEZNEFHMGk0Wu1OmAAHIkUCIRIIUDDIKrdig0CwRjrXBIIjxEgkBx0RQkJBrIH43xsJlvWGgGFTBmg+GQNrOVI8topAA0PiAA)

### 💻 Code

```ts repro
// @experimentalDecorators: true

function methodDecorator(value: string): any {
	return () => {};
}

//@methodDecorator(MyEnum.value1) // Correctly reports Enum 'MyEnum' used before its declaration (TS2450)
export class MyClass {
    @methodDecorator(MyEnum.value1) // No error reported
    public foo(): void {
    }
}

enum MyEnum {
    value1 = "value1",
}
```

### 🙁 Actual behavior

- No TS2450 "Enum 'MyEnum' used before its declaration" is reported.
- At runtime, this code crashes during the initial script execution:
```
C:\repos\TS2450_decorator_repro\program.js:19
        methodDecorator(MyEnum.value1) // No error reported
                               ^

TypeError: Cannot read properties of undefined (reading 'value1')
    at C:\repos\TS2450_decorator_repro\program.js:19:32
    at Object.<anonymous> (C:\repos\TS2450_decorator_repro\program.js:22:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

### 🙂 Expected behavior

TS2450 (and other similar errors like 2448 for Block-scoped variables or 2449 for classes) should be correctly reported.

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #50349

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1672,13 +1672,17 @@ namespace ts {
...
+            }
+
+            function isUsedInFunctionOrInstancePropertyWorker(usage: Node, declaration: Node): boolean {
                 return !!findAncestor(usage, current => {
                     if (current === declContainer) {
                         return "quit";
                     }
                     if (isFunctionLike(current)) {
-                        return true;
+                        return !getImmediatelyInvokedFunctionExpression(current);
```
Comment (Zzzen) [inline src/compiler/checker.ts:1685]: Enum is not checked properly.  [playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcCMB2AFASkQbwFgAoRMxAGwFMpEBDRAXkS1yYD5EBRMEAWwB0ATSoBnHLgDcZAPQzEogBZwQFACaIqAJy1wtJcpt59uxggcPkAcnCaIADABoLlxCNF20z0uQC+Jf2ISFHRsHCA)

```ts
function foo17() {
    let a = (() => Enum.Yes)();  // should error
    enum Enum {
        No = 0,
        Yes = 1,
    }
}

foo17()
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by sandersn** [comment]
@typescript-bot test this

**Review by sandersn — APPROVED** [review]

**Review by gabritto — APPROVED** [review]

**Comment by Renegade334** [comment]
~~This approach appears to conflict with #57933 (which had already been merged), in that the later PR deliberately avoided changing the behaviour of experimental decorators on the grounds that it caused too much ecosystem breakage.~~

**Comment by jakebailey** [comment]
I'm confused; wouldn't our extended tests have caught a bad break?

**Comment by Renegade334** [comment]
Actually, my read is wrong. #57933 only applied to passing the declared _class_ variable to decorators used within that class, which is kosher given that the transformer injects the decorator call after the class is declared. The example from #62083, passing a block-scoped variable declared after the class to a decorator within the class body, would lead to runtime errors if transpiled by TypeScript itself – clearly the custom transpilation used there is doing something different.
