### PR TITLE
feat(33792): Add quick fix for `This condition will always return true since the function is always defined. Did you mean to call it instead

### LINKED ISSUE #33792: Add quick fix for `This condition will always return true since the function is always defined. Did you mean to call it instead`
**TypeScript Version:**  3.7.0-dev.20191003

**Search Terms:**
- quick fix
- code action
- function
- missing call

**Code**

```ts
const val = {
    isTrue() { return true; }
}

if (val.isTrue) {
    console.log(true);
}
```

This code produces the error: `This condition will always return true since the function is always defined. Did you mean to call it instead?` for the conditional

**Expected behavior:**
A quick fix to add the missing call is returned. This would change the code to:

```ts
const val = {
    isTrue() { return true; }
}

if (val.isTrue()) {
    console.log(true);
}
```

**Actual behavior:**
No quick fixes

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #33792

### CODE REVIEW

**Comment by j-oliveras** [comment]
Fixes #37149?

File: src/services/codefixes/fixMissingCallInCondition.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+            return [createCodeFixAction(fixId, changes, Diagnostics.Add_missing_call, fixId, Diagnostics.Add_all_missing_calls)];
+        },
+        getAllCodeActions: context => codeFixAll(context, errorCodes, (changes, diag) => {
+            const callName = getCallName(diag.file, diag.start);
+            if (callName) doChange(changes, diag.file, callName);
+        })
+    });
+
+    function doChange(changes: textChanges.ChangeTracker, sourceFile: SourceFile, name: Identifier | PrivateIdentifier): void {
+        changes.replaceNode(sourceFile, name, createCall(createIdentifier(name.text), /*typeArguments*/ undefined, /*argumentsArray*/ undefined));
```
Comment (amcasey) [inline src/services/codefixes/fixMissingCallInCondition.ts]: I can't think of a case where this won't work (as demonstrated by your lovely test cases below), but this syntax tree is technically incorrect and could easily break in the future.  The actual expression of the new call should be the one identified by `context.span` above, not just the last identifier.  For example, in crude pseudo-code, `a.b()` should be `call(a.b)`, not `a.call(b)`.  That's why you had to (effectively) cast away `PrivateIdentifier` here.

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -5357,6 +5357,14 @@
         "category": "Message",
         "code": 95066
     },
+    "Add missing call": {
```
Comment (amcasey) [inline src/compiler/diagnosticMessages.json]: "Add missing argument list" or "Add missing call parentheses"?

File: src/services/codefixes/fixMissingCallInCondition.ts (hunk 1 above)
Comment (rbuckton) [reply src/services/codefixes/fixMissingCallInCondition.ts]: `textChanges` technically just does string replacements, so replacing the string at `name` with a call to `name` is "technically" ok (since we're not actually building up a tree). If this were a tree mutation, you would need wrap the `createCall​​​​​​​` around the entire access expression. Either way, you should be able to reuse `name` here.

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/diagnosticMessages.json]: +1 for the latter

File: src/services/codefixes/fixMissingCallInCondition.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/codefixes/fixMissingCallInCondition.ts]: @amcasey @rbuckton Thanks for the feedback :+1:.

File: src/services/codefixes/fixMissingCallParentheses.ts [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+            return [createCodeFixAction(fixId, changes, Diagnostics.Add_missing_call_parentheses, fixId, Diagnostics.Add_all_missing_call_parentheses)];
+        },
+        getAllCodeActions: context => codeFixAll(context, errorCodes, (changes, diag) => {
+            const callName = getCallName(diag.file, diag.start);
+            if (callName) doChange(changes, diag.file, callName);
+        })
+    });
+
+    function doChange(changes: textChanges.ChangeTracker, sourceFile: SourceFile, name: Identifier | PrivateIdentifier): void {
+        changes.replaceNodeWithText(sourceFile, name, `${ name.text }()`);
```
Comment (amcasey) [inline src/services/codefixes/fixMissingCallParentheses.ts]: Much clearer.  Thanks! 👍

**Comment by amcasey** [comment]
@rbuckton @andrewbranch Last call for comments

**Comment by orta** [comment]
Good work on the tests 👍
