### PR TITLE
Fix exit code on bogus build file

### LINKED ISSUE #33849: Command line argument validation returns incorrect process exit code
**TypeScript Version:**  3.6.3, 3.6.2 and typescript@next

**Search Terms:**
build option file not found
**Code**
```shell
tsc -b bogus.json
echo $?
```

**Expected behavior:**
In 3.5.3, this still prints the following:
```
> tsc -b bogus.json
< error TS6053: File 'bogus.jon/tsconfig.json' not found.
> echo $?
< 1
```

**Actual behavior:**
Since 3.6.2, this prints the following:
```
> tsc -b bogus.json
< error TS6053: File 'bogus.jon/tsconfig.json' not found.
> echo $?
< 0
```

As such, it is not possible to detect for infastructure scripts (that invoke `tsc`) to know when `tsc` was not able to find the `tsconfig.json` file.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by elibarzilay**
Fixes missing error exit code when a bogus input file is specified

Fixes #33849.

### CODE REVIEW

File: tests/baselines/reference/api/tsserverlibrary.d.ts [hunk 1]
```diff
@@ -1964,7 +1964,7 @@ declare namespace ts {
         DiagnosticsPresent_OutputsSkipped = 1,
         DiagnosticsPresent_OutputsGenerated = 2,
         InvalidProject_OutputsSkipped = 3,
-        ProjectReferenceCycle_OutputsSkupped = 4
```
Comment (sheetalkamat) [inline tests/baselines/reference/api/tsserverlibrary.d.ts]: Need to mark the incorrect one as `@deperecated` instead of removing since its api change.

File: src/compiler/tsbuild.ts [hunk 2]
```diff
@@ -1788,31 +1788,25 @@ namespace ts {
...
         startWatching(state, buildOrder);
 
         return isCircularBuildOrder(buildOrder) ?
-            ExitStatus.ProjectReferenceCycle_OutputsSkupped :
-            errorProjects ?
-                successfulProjects ?
-                    ExitStatus.DiagnosticsPresent_OutputsGenerated :
-                    ExitStatus.DiagnosticsPresent_OutputsSkipped :
-                ExitStatus.Success;
+                 ExitStatus.ProjectReferenceCycle_OutputsSkipped
```
Comment (sheetalkamat) [inline src/compiler/tsbuild.ts]: Can you please use same pattern that either puts `?` and `:` at the end of the line or beginning of the line.

File: src/compiler/tsbuild.ts [hunk 3]
```diff
@@ -1788,31 +1788,25 @@ namespace ts {
...
             if (!invalidatedProject) break;
             reportQueue = false;
             invalidatedProject.done(cancellationToken);
-            if (state.diagnostics.has(invalidatedProject.projectPath)) {
-                errorProjects++;
-            }
-            else {
-                successfulProjects++;
-            }
+            if (!state.diagnostics.has(invalidatedProject.projectPath)) successfulProjects++;
```
Comment (sheetalkamat) [inline src/compiler/tsbuild.ts]: Need test for this.. you can look at tests in `src/testRunner/unittests/tsbuild` for how to write them.

File: tests/baselines/reference/api/tsserverlibrary.d.ts (hunk 1 above)
Comment (elibarzilay) [reply tests/baselines/reference/api/tsserverlibrary.d.ts]: Done.

File: src/compiler/tsbuild.ts (hunk 2 above)
Comment (elibarzilay) [reply src/compiler/tsbuild.ts]: Done.

File: src/compiler/tsbuild.ts (hunk 3 above)
Comment (elibarzilay) [reply src/compiler/tsbuild.ts]: Done.

File: src/compiler/tsbuild.ts [hunk 4]
```diff
@@ -1788,31 +1788,25 @@ namespace ts {
...
         startWatching(state, buildOrder);
 
-        return isCircularBuildOrder(buildOrder) ?
-            ExitStatus.ProjectReferenceCycle_OutputsSkupped :
-            errorProjects ?
-                successfulProjects ?
-                    ExitStatus.DiagnosticsPresent_OutputsGenerated :
-                    ExitStatus.DiagnosticsPresent_OutputsSkipped :
-                ExitStatus.Success;
+        return isCircularBuildOrder(buildOrder)
```
Comment (sheetalkamat) [inline src/compiler/tsbuild.ts]: This is how we format things:
image

File: tests/baselines/reference/api/typescript.d.ts [hunk 5]
```diff
@@ -1964,7 +1964,7 @@ declare namespace ts {
         DiagnosticsPresent_OutputsSkipped = 1,
         DiagnosticsPresent_OutputsGenerated = 2,
         InvalidProject_OutputsSkipped = 3,
-        ProjectReferenceCycle_OutputsSkupped = 4
```
Comment (sheetalkamat) [inline tests/baselines/reference/api/typescript.d.ts]: you need to call `gulp runtests --t="Public API"` and  then `gulp baseline-accept`

File: src/compiler/tsbuild.ts (hunk 4 above)
Comment (elibarzilay) [reply src/compiler/tsbuild.ts]: Done, reluctantly.

File: tests/baselines/reference/api/typescript.d.ts (hunk 5 above)
Comment (elibarzilay) [reply tests/baselines/reference/api/typescript.d.ts]: Done, properly.
