### PR TITLE
Fix namespace name conflict detection in "Convert named imports to namespace import" action

### LINKED ISSUE #44267: "Convert named imports to namespace import" adds redundant underscore suffix
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about refactorings

### ⏯ Playground Link

N/A

### 💻 Code

`main.ts`:

```ts
import { Foo } from './Foo';
Foo;
```

`Foo.ts`:

```ts
export const Foo = 1;
```

1. Highlight `import { Foo } from './Foo';`
2. Run refactoring "Convert named imports to namespace import"

### 🙁 Actual behavior

```ts
import * as Foo_1 from './Foo';
Foo_1.Foo;
```

### 🙂 Expected behavior

```ts
import * as Foo from './Foo';
Foo.Foo;
```

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #44267

### CODE REVIEW

File: src/services/refactors/convertImport.ts [hunk 1]
```diff
@@ -153,10 +176,8 @@ namespace ts.refactor {
                 if (isShorthandPropertyAssignment(id.parent)) {
                     changes.replaceNode(sourceFile, id.parent, factory.createPropertyAssignment(id.text, access));
                 }
-                else if (isExportSpecifier(id.parent) && !id.parent.propertyName) {
-                    if (!neededNamedImports.some(n => n.name === element.name)) {
-                        neededNamedImports.push(factory.createImportSpecifier(element.propertyName && factory.createIdentifier(element.propertyName.text), factory.createIdentifier(element.name.text)));
-                    }
+                else if (isExportSpecifier(id.parent)) {
```
Comment (gabritto) [inline src/services/refactors/convertImport.ts:179]: Old code disregarded named export clauses that aliased the reference to the named import, so code such as 
```ts
import { a } from "m";
export { a as b };
```
was in fact incorrectly refactored into
```ts
import { a } from "m";
export { m.a as b };
```

File: src/services/refactors/convertImport.ts [hunk 2]
```diff
@@ -138,13 +138,36 @@ namespace ts.refactor {
...
+                return false; // There is no symbol with the same name as the preferred namespace name, so no conflict.
+            });
+        }
+        const namespaceNameConflicts = toConvert.elements.some(hasNamespaceNameConflict);
         const namespaceImportName = namespaceNameConflicts ? getUniqueName(preferredName, sourceFile) : preferredName;
 
-        const neededNamedImports: ImportSpecifier[] = [];
+        // Imports that need to be kept as named imports in the refactored code, to avoid changing the semantics.
+        // More specifically, those are named imports that appear in named exports in the original code, e.g. `a` in `import { a } from "m"; export { a }`.
+        const neededNamedImports: Set<ImportSpecifier> = new Set();
```
Comment (gabritto) [inline src/services/refactors/convertImport.ts:170]: Changed to use a set instead of an array. The old code used the array as a set by comparing the named imports' `name` properties (of type `Identifiers`) (`element.name` in for loop below), but it pushed into the array a node with a newly-created `Identifier` as `name`, so in fact this new node's `name` would never be equal to the named imports' `name`, and therefore the same named import could be repeated, as in:
```ts
import { a, b } from "m";
export { b };
export { b as c };
```
would become
```ts
import * as m from "m";
import { b, b } from "m"; // Duplicate b import
export { b };
export { b as c };
```

**Review by andrewbranch — APPROVED** [review]
🌟 Thanks for the great code comments! Made it really easy to understand.
