### PR TITLE
More special declaration types in JS

### LINKED ISSUE #7632: can't navigate javascript with manual namespaces
_From @chadbr on March 22, 2016 0:18_

I have large legacy codebase with "manual" style namespacing like this:

```
//namespaces
var my = my || {};
my.app = my.app || {};
```

and "classes" declared like this:

my.app.Application` = (function () {
    var Application = function () {
...
    };
    return Application;
})();

I've tried several combinations of jsconfig.json parameters and none allow me to navigate this style of code. Should this work?
- VSCode Version: 0.10.11, 0.10.12-insider
- OS Version: OSX 10.11.3

Steps to Reproduce:
1. Open attached project or github repo https://github.com/chadbr/vscodeTestJS

[vscodeTestJS.zip](https://github.com/Microsoft/vscode/files/183295/vscodeTestJS.zip)
1. Open folder in vscode
2. open src/app/application.js 
3. try to go to declaration of my.app.SomeView() -- nothing happens.

_Copied from original issue: Microsoft/vscode#4533_

### PR DESCRIPTION
**Pull request by sandersn**
# Object literals as declarations in JS

Starting in 2.7, Typescript supported empty object literals as namespace declarations in Javascript. Before that, it supported functions and classes as namespace declarations:

```js
// before 2.7
var callable = function() {
}
callable.constant = 1

// after 2.7
var ns = {}
ns.constant = 1
```

This PR adds support for top-level assignments as declarations. A var or const declaration is not required.

```js
app = {} // does NOT need to be “var app = {}”
app.C = class {
}
app.f = function() {
}
app.prop = 1
```

## IIFEs as namespace declarations

This PR assumes that the IIFE returns a function, class or empty object literal, but does not verify it:

```js
var C = (function () {
  function C(n) {
    this.p = n
  }
  return C;
})();
C.staticProperty = 1
```

## Defaulted declarations

"Defaulted declarations" allow initializers that reference the declared name in the left side of a logical or:

```js
my = window.my || {}
my.app = my.app || {}
```

## Prototype assignment

You can assign an object literal directly to the prototype property. Invididual prototype assignments still work too:

```ts
var C = function (p) {
  this.p = p
}
C.prototype = {
  m() {
    console.log(this.p)
  }
}
C.prototype.q = function(r) {
  return this.p === r
}
```

## Nested and merged declarations

Nesting works to any level now, and merges correctly across files. Previously neither was the case. The binder now speculatively creates nested symbols for top-level assignments and then the checker performs an extra merge of symbols with the new JSContainer flag.

 ## Fix function containers

Previously functions weren't marked as a JS container when they didn't have any nested properties. This meant that type resolution didn't work:

```ts
var Outer = {}
Outer.Inner = function () { }

/** @type {Outer.Inner} */ // ok, Inner is treated as a type just like class { } is
var inner
```

Fixes #7632

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -1529,22 +1596,22 @@ namespace ts {
...
-                const innerPropertyAccessIdentifier = <Identifier>innerPropertyAccess.expression;
-                if (innerPropertyAccessIdentifier.escapedText === "module" && innerPropertyAccess.name.escapedText === "exports") {
+                if (lhs.expression.expression.escapedText === "module" && lhs.expression.name.escapedText === "exports") {
                     return SpecialPropertyAssignmentKind.ExportsProperty;
                 }
-                if (innerPropertyAccess.name.escapedText === "prototype") {
+                if (lhs.expression.name.escapedText === "prototype") {
                     return SpecialPropertyAssignmentKind.PrototypeProperty;
                 }
             }
```
Comment (sandersn) [inline src/compiler/utilities.ts]: The preceding changes in this function are just a refactor, *except* for the following 3 lines.

**Comment by sandersn** [comment]
I updated the chrome devtools baseline. This change removes about 8000 errors and changes about 2000. The changes seem to be from different kinds of special prototype assignments that are unrecognised or miscategorised as special static assignments. I'll investigate those next.

**Comment by sandersn** [comment]
The latest commit actually fixes the assert from the chrome-devtools code base instead of working around it; you can now assign nested prototype declarations like so:

```ts
Outer.Inner.prototype.p = 1;
```

Previously prototype assignments didn't recognise nested assignments and the binder would mistakenly treat this as a static assignment to a container named `prototype`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -1995,21 +2002,7 @@ namespace ts {
...
             else if (name.kind === SyntaxKind.QualifiedName || name.kind === SyntaxKind.PropertyAccessExpression) {
-                let left: EntityNameOrEntityNameExpression;
-
-                if (name.kind === SyntaxKind.QualifiedName) {
-                    left = name.left;
-                }
-                else if (name.kind === SyntaxKind.PropertyAccessExpression) {
-                    left = name.expression;
-                }
-                else {
```
Comment (sandersn) [inline src/compiler/checker.ts]: this else clause can never happen because on line 2004 we just checked that name.kind is QualifiedName or PropertyAccessExpression. So I deleted it.

File: tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts [hunk 3]
```diff
@@ -0,0 +1,19 @@
+// @noEmit: true
+// @allowJs: true
+// @checkJs: true
+// @Filename: a.js
+var Outer = {};
+
+Outer.Inner = function () {}
+Outer.Inner.prototype = {
+    x: 1,
+    m() { }
```
Comment (weswigham) [inline tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts]: We should also check/enforce that a `__proto__` member in the RHS acts as a base type for the class type (this is also present in the devtools codebase).

Comment (Kovensky) [reply tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts]: Ah, Annex B... 😭

Comment (weswigham) [reply tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts]: `__proto__` was sensible ish in a pre-`Object.setPrototypeOf` world. :P

Comment (Kovensky) [reply tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts]: But there was `Object.create` :(

Comment (sandersn) [reply tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts]: I’ll add it to the Big List of JavaScript We Could Do Better. I don’t wa t to put it in this PR though — I have t touched the inheritance code for a while.

Comment (weswigham) [reply tests/cases/conformance/salsa/typeFromPropertyAssignment16.ts]: K.

File: src/compiler/binder.ts [hunk 4]
```diff
@@ -2347,103 +2364,125 @@ namespace ts {
...
+                return lookupSymbolForNameWorker(container, node.escapedText);
+            }
+            else {
+                const symbol = getJSInitializerSymbol(lookupSymbolForPropertyAccess(node.expression));
+                return symbol && symbol.exports && symbol.exports.get(node.name.escapedText);
+            }
+        }
+
+        function forEachIdentifierInEntityName(e: EntityNameExpression, action: (e: Identifier, symbol: Symbol, k: EntityNameExpression) => Symbol): Symbol {
+            if (isIdentifier(e)) {
```
Comment (sandersn) [inline src/compiler/binder.ts]: should handle module.exports and exports as a terminal case instead of in the callers

File: src/compiler/binder.ts [hunk 5]
```diff
@@ -2300,7 +2303,21 @@ namespace ts {
             // When we create a property via 'exports.foo = bar', the 'exports.foo' property access
             // expression is the declaration
             setCommonJsModuleIndicator(node);
-            declareSymbol(file.symbol.exports, file.symbol, <PropertyAccessExpression>node.left, SymbolFlags.Property | SymbolFlags.ExportValue, SymbolFlags.None);
+            const lhs = node.left as PropertyAccessEntityNameExpression;
+            const symbol = forEachIdentifierInEntityName(lhs.expression, (id, original, e) => {
+                if (isExportsOrModuleExportsOrAlias(file, e) || (isIdentifier(e) && e.escapedText === "module" && original === undefined)) {
```
Comment (mhegazy) [inline src/compiler/binder.ts]: I do not think we need to handle "module" in a special way. we probably should make forEachIdentifierInEntityName handle the terminal case correctly being `identifier` | `exports`  | `module.exports`, and return the correct symbol in each case.

File: src/compiler/utilities.ts [hunk 6]
```diff
@@ -1471,14 +1471,75 @@ namespace ts {
...
+    export function getAssignedJavascriptInitializer(node: Node) {
+        return node &&
+            (isBinaryExpression(node) && node.operatorToken.kind === SyntaxKind.BarBarToken || isPropertyAccessExpression(node)) &&
+            node.parent && isBinaryExpression(node.parent) &&
+            node.parent.operatorToken.kind === SyntaxKind.EqualsToken &&
+            (getJavascriptInitializer(node.parent.right) || getDefaultedJavascriptInitializer(node.parent.left as EntityNameExpression, node.parent.right));
+    }
+
+    export function getJavascriptInitializer(initializer: Expression) {
+        if (isCallExpression(initializer)) {
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: we have a function `getImmediatelyInvokedFunctionExpression` that is almost the same

File: src/compiler/utilities.ts [hunk 7]
```diff
@@ -1471,14 +1471,75 @@ namespace ts {
...
+            const e = skipParentheses(initializer.expression);
+            return e.kind === SyntaxKind.FunctionExpression || e.kind === SyntaxKind.ArrowFunction ? initializer : undefined;
+        }
+        if (initializer.kind === SyntaxKind.FunctionExpression || initializer.kind === SyntaxKind.ClassExpression) {
+            return initializer;
+        }
+        if (isObjectLiteralExpression(initializer) &&
+            (initializer.properties.length === 0 ||
+             isBinaryExpression(initializer.parent) && isPropertyAccessExpression(initializer.parent.left) && initializer.parent.left.name.escapedText === "prototype")) {
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: kinda weird to be checking up the parent chain here.. can we do it higher up instead, e.g. getDeclaredJavascriptInitializer

File: src/compiler/utilities.ts [hunk 8]
```diff
@@ -1471,14 +1471,75 @@ namespace ts {
...
+
+    export function getAssignedJavascriptInitializer(node: Node) {
+        return node &&
+            (isBinaryExpression(node) && node.operatorToken.kind === SyntaxKind.BarBarToken || isPropertyAccessExpression(node)) &&
+            node.parent && isBinaryExpression(node.parent) &&
+            node.parent.operatorToken.kind === SyntaxKind.EqualsToken &&
+            (getJavascriptInitializer(node.parent.right) || getDefaultedJavascriptInitializer(node.parent.left as EntityNameExpression, node.parent.right));
+    }
+
+    export function getJavascriptInitializer(initializer: Expression) {
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: Please add a comment listing the patterns that his function is supporting.

File: src/compiler/utilities.ts [hunk 9]
```diff
@@ -1471,14 +1471,75 @@ namespace ts {
...
+    }
+
+    export function getDeclaredJavascriptInitializer(node: Node) {
+        if (node && isVariableDeclaration(node) && node.initializer) {
+            return getJavascriptInitializer(node.initializer) ||
+                isIdentifier(node.name) && getDefaultedJavascriptInitializer(node.name, node.initializer);
+        }
+    }
+
+    export function getAssignedJavascriptInitializer(node: Node) {
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: where else do we need the BarBartoken handling that is not in getDefaultedJavascriptInitializer? can we consolidate this in one place.

File: src/compiler/utilities.ts [hunk 10]
```diff
@@ -1471,14 +1471,75 @@ namespace ts {
...
+            return initializer;
+        }
+        if (isObjectLiteralExpression(initializer) &&
+            (initializer.properties.length === 0 ||
+             isBinaryExpression(initializer.parent) && isPropertyAccessExpression(initializer.parent.left) && initializer.parent.left.name.escapedText === "prototype")) {
+            return initializer;
+        }
+    }
+
+    function getDefaultedJavascriptInitializer(name: EntityNameExpression, initializer: Expression) {
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: can you add comments on all of these functions.. they have very similar names.
