### PR TITLE
Fixes to @augments handling

### LINKED ISSUE #18740: Ignores @augments tag on a class without an explicit `extends`
**TypeScript Version:**  nightly (2.6.0-dev.20170923)

**Code**

```ts
class A {
    a() {}
}

/** @augments {A} */
class B {
    b() {
        this.a();
    }
}

// @ts-ignore
inherit(A, B);
```

**Expected behavior:**

Either:
* An error on the `@augments` tag.
* The `@augments` tag is accepted and I can access methods from `A` inside `B`.

**Actual behavior:**

`@augments` is ignored unless we actually see `extends`.

Noticed while working on #18739.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #18740

We will now get a superclass from `@augments` even if there is no `extends`.

Allows us to parse `/** @augments A */` without the curly braces, because that [seems](http://usejsdoc.org/tags-augments.html) to be the style.

We will no longer parse arbitrary types, only a class (qualified) name followed by type arguments. So you can't declare to inherit from `() => void` without parse errors.

Adds errors for:
* `@augments` tag not on a class
* `@augments A` but `extends B`

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19789,6 +19789,36 @@ namespace ts {
...
         }
 
+        function checkJSDocAugmentsTag(node: JSDocAugmentsTag): void {
+            const cls = getNodeCommentedByJSDocTag(node);
+            if (!isClassDeclaration(cls) && !isClassExpression(cls)) {
+                error(cls, Diagnostics.JSDoc_augments_tag_will_be_ignored_if_not_attached_to_a_class_declaration);
+                return;
+            }
+
+            const name: Identifier = node.class.expression.kind === SyntaxKind.PropertyAccessExpression ? (node.class.expression as PropertyAccessExpression).name : (node.class.expression as Identifier);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Waiting on #18774 to get rid of these casts

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -19789,6 +19789,36 @@ namespace ts {
...
+                const className = getClassName(extend.expression);
+                if (className && name.escapedText !== className.escapedText) {
+                    error(name, Diagnostics.JSDoc_augments_tag_declares_to_extend_0_but_actual_class_augments_1,
+                        unescapeLeadingUnderscores(name.escapedText),
+                        unescapeLeadingUnderscores(className.escapedText));
+                }
+            }
+        }
+
+        function getClassName(node: Expression): Identifier | undefined {
```
Comment (sandersn) [inline src/compiler/checker.ts]: This feels like it already exists. Either way, `getClassName` is too vague+specific a name for something that treats an Expression like a `QualifiedName` and then gets the identifier at the bottom. `getIdentifierFromExpressionAsQualifiedName`? That's horrible in a different way. I'm not sure what the best name is.

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -1591,6 +1590,11 @@ namespace ts {
         return parameter && parameter.symbol;
     }
 
+    export function getNodeCommentedByJSDocTag(node: JSDocTag): Node {
```
Comment (sandersn) [inline src/compiler/utilities.ts]: we should really make up a name for "the node that this jsdoc is attached to". Commentee? Given that the parameter name and type could be `tag: JSDocTag`, I think `getCommentee` would be a fine name, given a good word for "Commentee".

File: src/compiler/diagnosticMessages.json [hunk 4]
```diff
@@ -3511,6 +3511,14 @@
         "category": "Error",
         "code": 8021
     },
+    "JSDoc '@augments' tag will be ignored if not attached to a class declaration.": {
+        "category": "Error",
+        "code": 8022
+    },
+    "JSDoc '@augments' tag declares to extend '{0}', but actual class augments '{1}'.": {
```
Comment (sandersn) [inline src/compiler/diagnosticMessages.json]: JSDoc '@augments {0}' does not match the 'extends {1}' clause.

File: src/compiler/diagnosticMessages.json [hunk 5]
```diff
@@ -3511,6 +3511,14 @@
         "category": "Error",
         "code": 8021
     },
+    "JSDoc '@augments' tag will be ignored if not attached to a class declaration.": {
```
Comment (sandersn) [inline src/compiler/diagnosticMessages.json]: JSDoc '@augments' tag is not attached to a class declaration.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -19789,6 +19789,36 @@ namespace ts {
...
         }
 
+        function checkJSDocAugmentsTag(node: JSDocAugmentsTag): void {
+            const cls = getNodeCommentedByJSDocTag(node);
+            if (!isClassDeclaration(cls) && !isClassExpression(cls)) {
+                error(cls, Diagnostics.JSDoc_augments_tag_will_be_ignored_if_not_attached_to_a_class_declaration);
+                return;
+            }
+
+            const name = node.class.expression.kind === SyntaxKind.PropertyAccessExpression ? node.class.expression.name : node.class.expression;
```
Comment (sandersn) [inline src/compiler/checker.ts]: why isn't this a call to `getClassName` too?

File: src/compiler/scanner.ts [hunk 7]
```diff
@@ -1856,6 +1856,12 @@ namespace ts {
                 case CharacterCodes.closeBracket:
                     pos++;
                     return token = SyntaxKind.CloseBracketToken;
+                case CharacterCodes.lessThan:
```
Comment (sandersn) [inline src/compiler/scanner.ts]: can you make sure that we have some tests that use < and > inside jsdoc comments in various places? it should be allowed everywhere in comment text, especially in misaligned cases like

```
  /**
   * @param x hi
< > still part of the previous comment
   */
```

And of course it should cause error in places like the tag name, etc.

File: src/compiler/types.ts [hunk 8]
```diff
@@ -2161,7 +2161,7 @@ namespace ts {
 
     export interface JSDocAugmentsTag extends JSDocTag {
         kind: SyntaxKind.JSDocAugmentsTag;
-        typeExpression: JSDocTypeExpression;
+        class: ExpressionWithTypeArguments & { expression: Identifier | PropertyAccessEntityNameExpression };
```
Comment (sandersn) [inline src/compiler/types.ts]: don't you want a subclass of ExpressionWithTypeArguments that has the override `expression: Identifier | PropertyAccessEntityNameExpression` ? Seems like intersection would be too permissive.

File: src/compiler/parser.ts [hunk 9]
```diff
@@ -6604,15 +6607,36 @@ namespace ts {
...
-
                     const result = <JSDocAugmentsTag>createNode(SyntaxKind.JSDocAugmentsTag, atToken.pos);
                     result.atToken = atToken;
                     result.tagName = tagName;
-                    result.typeExpression = typeExpression;
+                    result.class = parseValidExpressionWithTypeArguments();
                     return finishNode(result);
                 }
 
+                function parseValidExpressionWithTypeArguments(): ExpressionWithTypeArguments & { expression: Identifier | PropertyAccessEntityNameExpression } {
```
Comment (sandersn) [inline src/compiler/parser.ts]: this doesn't parse all valid expressions, only PropertyAccessEntityNameExpressions, right? This name is confusing.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/utilities.ts]: I've been calling it the "host" node in my internal monologue.

File: src/compiler/types.ts (hunk 8 above)
Comment (andy-ms) [reply src/compiler/types.ts]: How is intersection permissive where `extends` isn't? Could you give an example?

Comment (sandersn) [reply src/compiler/types.ts]: I forgot that `Identifier` is assignable to `Expression & Identifier` but (for example) `BinaryExpression` isn't. Never mind.

File: src/compiler/utilities.ts [hunk 10]
```diff
@@ -1591,6 +1590,11 @@ namespace ts {
         return parameter && parameter.symbol;
     }
 
+    export function getJSDocHost(node: JSDocTag): Node {
```
Comment (weswigham) [inline src/compiler/utilities.ts]: This can have a return type of `HasJSDoc` instead of `Node`. 😉

File: src/compiler/scanner.ts (hunk 7 above)
Comment (andy-ms) [reply src/compiler/scanner.ts]: Added a test.

**Comment by minestarks** [comment]
@andy-ms `<>` aren't legal characters on Windows file systems. I can't git pull after this commit:

```
E:\src\TypeScript>git pull upstream master
From https://github.com/Microsoft/TypeScript
 * branch                  master     -> FETCH_HEAD
error: unable to create file tests/baselines/reference/JSDocParsing/DocComments.parsesCorrectly.<> characters.json: Invalid argument
```

**Comment by minestarks** [comment]
Note: i can just update my `.gitignore` but FYI

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -19789,6 +19789,38 @@ namespace ts {
             }
         }
 
+        function checkJSDocAugmentsTag(node: JSDocAugmentsTag): void {
+            const cls = getJSDocHost(node);
+            if (!isClassDeclaration(cls) && !isClassExpression(cls)) {
+                error(cls, Diagnostics.JSDoc_augments_is_not_attached_to_a_class_declaration);
```
Comment (aozgaa) [inline src/compiler/checker.ts]: Should this message mention class expressions?
