### PR TITLE
Protect watcher from double close

### LINKED ISSUE #49961: Cannot read properties of undefined (reading 'close')
# Bug Report

### 🔎 Search Terms
- watcher
- crash
- 

### 🕗 Version & Regression Information

4.8.0-dev.20220711

Seems like a regression as I do not remember seeing this in TS 4.7

### Details

When closing editors in VS Code, recently I've been seeing the following crash:

```ts
  ERR <semantic> TypeScript Server Error (4.8.0-dev.20220711)
Cannot read properties of undefined (reading 'close')
TypeError: Cannot read properties of undefined (reading 'close')
    at Object.close (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:6834:29)
    at Object.close (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:116840:29)
    at closeFileWatcherOf (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:116891:32)
    at Map.forEach (<anonymous>)
    at Object.clearMap (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:19668:13)
    at Object.clear (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:122531:16)
    at ConfiguredProject.Project.close (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:171446:38)
    at ConfiguredProject.close (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:172930:40)
    at ProjectService.removeProject (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:173991:25)
    at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:175861:86
    at Map.forEach (<anonymous>)
    at ProjectService.removeOrphanConfiguredProjects (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:175861:44)
    at ProjectService.cleanupAfterOpeningFile (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:175805:22)
    at ProjectService.applyChangesInOpenFiles (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:176009:26)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:177372:46)
    at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:179564:96
    at IpcIOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:179555:28)
    at IpcIOSession.Session.executeCommand (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:179564:41)
    at IpcIOSession.Session.onMessage (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:179592:35)
    at process.<anonymous> (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:183758:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21): Error: <semantic> TypeScript Server Error (4.8.0-dev.20220711)

```

I can't repo this reliably but here's the complete log of a session the crashed (it's quite large)
[tsserver.log.zip](https://github.com/microsoft/TypeScript/files/9144974/tsserver.log.zip)

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #49961

### CODE REVIEW

**Review by sheetalkamat — APPROVED** [review]
I am not confident in if we should take this or not.. 
Normally this exception is either because the state is messed up because of other exception (in which case this fix is ok as it shuts down the noise) but there could be some legitimate issues with watcher ref counting etc that we might not be able to detect easily. So i am more on the side of not taking this fix rather than taking but not totally against.

**Comment by sheetalkamat** [comment]
Eg. in the tsserver log there were some exceptions that could result in projects being in incorrect state

**Comment by jakebailey** [comment]
Well, at least in the case of #49961, if the error in the log before this one was in fact #49310, then I at least have a fix for that already.

But, I think in the context of this code, it feels like we should at least either make the watcher potentially undefined and conditionally close it, or make it always required and remove the `undefined!` and allow `close` to proceed if it's called a second time. (Both of which are type safe.)

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -1088,14 +1088,16 @@ namespace ts {
...
             }
             /** Watcher for the file system entry depending on whether it is missing or present */
-            let watcher = !fileSystemEntryExists(fileOrDirectory, entryKind) ?
+            let watcher: FileWatcher | undefined = !fileSystemEntryExists(fileOrDirectory, entryKind) ?
                 watchMissingFileSystemEntry() :
                 watchPresentFileSystemEntry();
             return {
                 close: () => {
                     // Close the watcher (either existing file system entry watcher or missing file system entry watcher)
-                    watcher.close();
```
Comment (sheetalkamat) [inline src/compiler/sys.ts:1097]: What i am saying is that this should be `watcher!.close() ` closing same watcher multiple times is potentially issue somewhere else. 

Watcher is set to undefined because we want to update them if its not closed look for  `updateWatcher` right below this

Comment (jakebailey) [reply src/compiler/sys.ts:1097]: That's exactly what the code is today, though. We have `let watcher: FileWatcher = ...`.

If we leave this code as it is now, it will crash if `close` is called, because it sets the watcher to undefined.

This PR doesn't change the fact that the watcher can be undefined, it only declares that `watcher` can be undefined (which makes it clear that `watcher.close()` is a type error), then ignores all closes but the first by skipping if it's already been set to `undefined`. `watcher` is still set to `undefined` so `updateWatcher` will behave identically and not perform any updates if the watcher has been closed.

Comment (jakebailey) [reply src/compiler/sys.ts:1097]: But, my suggestion of

> make it always required and remove the `undefined!` and allow `close` to proceed if it's called a second time

Doesn't work, of course, if we are trying to avoid `updateWatcher` from creating a new watcher even if it's closed.

So, we can either ignore the double close (this PR), or I guess we can do a debug assert and figure out who is closing this a second time and shouldn't be (which is the thing I was unsure was correct, given there are watchers out there that are refcounted and intend to be closed more than once).

Comment (sheetalkamat) [reply src/compiler/sys.ts:1097]: > given there are watchers out there that are refcounted and intend to be closed more than once).

This is not one of the watcher thats ref counted ones close over physical watcher and are suppose to close only once when ref count is 0

Comment (jakebailey) [reply src/compiler/sys.ts:1097]: So, we should do what this PR does then, and ignore a second close?

Comment (sheetalkamat) [reply src/compiler/sys.ts:1097]: I gave more thought to this.. I think Debug.assert would be ideal but given its more likely to cause it in case of other exceptions i think your fix is good. Sorry for going back and forth on this one..

Comment (jakebailey) [reply src/compiler/sys.ts:1097]: All good, just wanted to ensure I understood the right thing here.

I did try and add some debug asserts to every `close` implementation I could find (considering ref counting too), but didn't actually hit any asserts either. I guess that's what happens without a repro.
