### PR TITLE
Fixes emit of type predicate in declaration files

### LINKED ISSUE #3761: Declaration emitter does not emit type predicate
For the source:
```ts
function f(x: any): x is string {
  return typeof x === "string";
}
```
The declaration output is:
```
declare function f(x: any): ;
```

But it should be:
```ts
declare function f(x: any): x is string;
```

### PR DESCRIPTION
**Pull request by tinganho**
Fixes #3761.

### CODE REVIEW

**Comment by yuit** [comment]
lgtm

File: src/compiler/declarationEmitter.ts [hunk 1]
```diff
@@ -396,6 +398,12 @@ namespace ts {
                 }
             }
 
+            function emitTypePredicate(type: TypePredicateNode) {
+                writeEntityName(type.parameterName);
```
Comment (DanielRosenwasser) [inline src/compiler/declarationEmitter.ts]: Couldn't you have just used `emit(type.parameterName)`?

Comment (DanielRosenwasser) [inline src/compiler/declarationEmitter.ts]: Why didn't you use `emitEntityName` instead of `writeEntityName`?

Comment (rbuckton) [inline src/compiler/declarationEmitter.ts]: I looked at this, emitEntityName checks the visibility of the entity name, which is primarily for testing type visibility and does not understand that the parameterName is in the value space. As a result, you get errors that the signature references a private type.

Comment (rbuckton) [inline src/compiler/declarationEmitter.ts]: That said, a parameter name cannot be a qualified name, so I would just use `writeTextOfNode` here instead of adding a new `writeEntityName`.

**Comment by JsonFreeman** [comment]
You also need to modify buildSignatureDisplay in the checker to do something similar. To test this, write an example where a variable has its type inferred, and the type includes a signature with a type predicate.

**Comment by danquirk** [comment]
A few more tests would be nice. Type predicates with multiple parameters, generics, rest params, etc.

File: src/compiler/declarationEmitter.ts (hunk 1 above)
Comment (tinganho) [inline src/compiler/declarationEmitter.ts]: @rbuckton is right it caused on error being outputted. The parameter of the type predicates is referencing a local variable to the function. 

>That said, a parameter name cannot be a qualified name, so I would just use writeTextOfNode here instead of adding a new writeEntityName.

I can use `writeTextOfNode` then we skip one if statement check.

I broke up `writeEntityName` from `emitEntityName` because I thought it was more performant if it doesn't get evaluated every time we encounter `emitEntityName`, which I guess is quite frequent. So I guess I can keep that change?

Comment (JsonFreeman) [inline src/compiler/declarationEmitter.ts]: What is the difference between writeEntityName and emitEntityName? Can you encode this difference into the names of the respective functions?

Comment (tinganho) [inline src/compiler/declarationEmitter.ts]: >What is the difference between writeEntityName and emitEntityName?

`emitEntityName` checks for error. `writeEntityName` doesn't check.

>Can you encode this difference into the names of the respective functions?

Then I need to change `emitEntityName` which break naming consistency with other emit functions.

Comment (JsonFreeman) [inline src/compiler/declarationEmitter.ts]: Fair enough. Thanks for explaining.

**Comment by tinganho** [comment]
@JsonFreeman I guess you mean the the current functionality doesn't work:
```typescript
/// <reference path="fourslash.ts" />

//// function /*1*/f(a: any): a is number {}

goTo.marker("1");
verify.signatureHelpCountIs(1);
verify.currentSignatureHelpIs("f(x: any): a is number");
```

**Comment by tinganho** [comment]
I have been getting some issue with running the fourslash tests. I'm not being able to select any tests when I run:
```
jake runtests t=signatureHelpOnTypePredicate
```

**Comment by danquirk** [comment]
@tinganho I thought @RyanCavanaugh fixed that fourslash issue. It had to do with a bad dependency in the order the test runners were created iirc. Did it never get checked in?

**Comment by tinganho** [comment]
I use master from yesterday. Though I have seen the issue before. Then, I could just configure my `test.config` file and include `fourslash`. But now that strategy doesn't seem to work.

**Comment by JsonFreeman** [comment]
@tinganho Yes, quick info is one such consumer of buildSignatureDisplay. But you could run into the issue even in declaration emit.

My strategy for fourslash tests is to specify the test I want, and run it in the browser using `jake runtests-browser t=signatureHelpOnTypePredicate`. I think that works in Chrome, not sure about other browsers.

**Comment by tinganho** [comment]
@JsonFreeman I got this error:

```
jake runtests-browser t=declFileFunction browser=chrome
rm -rf tests/baselines/local/
rm -rf internal/baselines/rwc/local
Running test(s): declFileFunction
node tests/webTestServer.js 8888 chrome declFileFunction
Static file server running at
  => http://localhost:8888/
CTRL + C to shutdown
Using browser: chrome
events.js:85
      throw er; // Unhandled 'error' event
```

**Comment by tinganho** [comment]
I could maybe checkout what is wrong with the normal fourslash task.

**Comment by tinganho** [comment]
Turns out the fourslash bug was the old maximum call stack error bug in #3273,  but without any error message which let me think it wasn't selecting any tests.

**Comment by RyanCavanaugh** [comment]
I never actually did get to the bottom of that test issue.

We need to rewrite most of that whole mess :cry:

**Comment by JsonFreeman** [comment]
:+1:

**Comment by JsonFreeman** [comment]
Thanks @tinganho

**Comment by tinganho** [comment]
@JsonFreeman fixed the space issue

**Comment by mhegazy** [comment]
Thanks!
