### PR TITLE
Fixed auto completion after a < token to return types not values.

### LINKED ISSUE #29769: Generic auto-completion missing primitive types
**TypeScript Version:**  3.2.4

This is kinda hard to reproduce, but I was working on a slower laptop for a while now and repeatedly ran into the following issue:
1. Type the following quicker than autocompletion can keep up (its easier on slow machines):  
`const foo = Record<string`
2. Press `,` to enter the 2nd type argument

**Expected behavior:**
`const foo = Record<string,`

**Actual behavior:**
`const foo = Record<stringify,`

It seems like `string` is being added to the autocompletion list later, so by the time I press `,` it is not there yet and autocompletion resorts to filling `stringify`.

### PR DESCRIPTION
**Pull request by dragomirtitian**
Fixes #29769

Right now immediately after the `<` token the suggestions do not include types. This PR changes `isContextTokenTypeLocation` to recognize that if the `<` token is encountered inside a `TypeReference`, types should be suggested. 

Interestingly there is a test that specifically tested that values are included  in the suggestions for a type reference. I can't think of a case where this would be valid. This change removes values  from completions here. I would say this is an improvement but I am unsure what the original intent was.

```ts
const something: C<{| "valueOnly": false |}; // failed here, because of  missing values
const something2: C<C<{| "valueOnly": false |}; // failed here, because of  missing values
```

### CODE REVIEW

**Comment by andrewbranch** [comment]
This has been on my personal list of annoyances for quite some time—I’m incredibly excited to test this out!

File: tests/cases/fourslash/completionsIsPossiblyTypeArgumentPosition.ts [hunk 1]
```diff
@@ -20,7 +20,10 @@
 ////new callAndConstruct<callAndConstruct</*callAndConstruct*/
 
 for (const marker of test.markers()) {
-    if (marker.data && marker.data.valueOnly) {
+    if (marker.data && marker.data.typeOnly) {
+        verify.completions({ marker, includes: "T", excludes: "x" });
```
Comment (diguifi) [inline tests/cases/fourslash/completionsIsPossiblyTypeArgumentPosition.ts]: Sorry for the noob question: does `"T"` and `"x"` stand for "Type" and "Value" respectively? I'm trying to understand a little bit of the code by checking some PR's (yours is pretty cool!)

Comment (dragomirtitian) [reply tests/cases/fourslash/completionsIsPossiblyTypeArgumentPosition.ts]: @diguifi They do not intrinsically stand for type and value. In this test they are used as stand-ins  for  type and value, but only before they are defined as such above:
```ts
////const x = 0;
////type T = number;
```
