### PR TITLE
Avoid bogus circularity error on context sensitive expando assingment

### LINKED ISSUE #49944: "Expando assingment" for Javascript namespace stopped working.
Looks that the "declare a namespace with a function inside and expand the function with expando assignments" [workaround](https://github.com/microsoft/TypeScript/issues/37321#issuecomment-599812917) for my "JS namespaces" stopped working in TS 4.5

### 💻 Code
```
declare namespace app {
  function foo(): void;
}

app.foo.bar = (function () {
  const someFun = (arg: number) => {};
  return { someFun };
})();

app.foo.bar.someFun(1);
```

This works in [4.4.2](https://www.typescriptlang.org/play?ts=4.4.4#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3Ll8mAHRVO8gEax4AXnhda9Zm209i5SmDboG8dCzQAxOpu2wA5gMQ0UKkDCMaAfMSSEhTwcAw0MOxEVjYg9uxBUjy8wbIEispqMPLWdnRcAIw8YkA).
This doesn't work in [4.5.5](https://www.typescriptlang.org/play?ts=4.5.5#code/CYUwxgNghgTiAEA7KBbEBnADlMCqc3gG8BYAKHngDMBXRMAFwEsB7RallgCgEoAueADcWTYAG5yAX3Ll8mAHRVO8gEax4AXnhda9Zm209i5SmDboG8dCzQAxOpu2wA5gMQ0UKkDCMaAfMSSEhTwcAw0MOxEVjYg9uxBUjy8wbIEispqMPLWdnRcAIw8YkA)

### 🙁 Actual behavior

Compiler error:
```
 Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
 ```

### 🙂 Expected behavior

No error with proper inference.

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #49944

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -27139,7 +27139,7 @@ namespace ts {
                                 return undefined;
                             }
                         }
-                        return isInJSFile(decl) ? undefined : getTypeOfExpression(binaryExpression.left);
+                        return undefined;
```
Comment (ProKashif) [inline src/compiler/checker.ts:27142]:
```suggestion
                        return;

```

**Comment by sandersn** [comment]
This is probably the right change, except I wish I knew why TS files previously called `getTypeOfExpression`. What was the previous change, what break did it fix, and would the tests for it apply to TS now?

**Comment by Zzzen** [comment]
Oh sure. After a brief look at the code, I can see why you care about this deletion. It does look innocent.
