### PR TITLE
Always check index type validity for all types when an error node is present so we always issue an error

### LINKED ISSUE #26714: Regression - able to use union containing non-indexing type as index
**TypeScript Version:** master at bd40583beb10165fd9

**Search Terms:** array index union error

**Code**

```ts
declare const arr1: (string | string[])[];
declare const arr2: number[];
const j = arr2[arr1[0]];
```

**Expected behavior:** Error - Type `string[]` cannot be used as an index type

**Actual behavior:** No error

**Playground Link:** [Link](http://www.typescriptlang.org/play/#src=declare%20const%20arr1%3A%20(string%20%7C%20string%5B%5D)%5B%5D%3B%0D%0Adeclare%20const%20arr2%3A%20number%5B%5D%3B%0D%0Aconst%20j%20%3D%20arr2%5Barr1%5B0%5D%5D%3B%0D%0A)

**Related Issues:** Regressed during fix of #26409 (**edit**: #26281 ?)

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #26714

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9361,13 +9361,24 @@ namespace ts {
             const apparentObjectType = getApparentType(objectType);
             if (indexType.flags & TypeFlags.Union && !(indexType.flags & TypeFlags.Boolean)) {
                 const propTypes: Type[] = [];
+                let wasMissingProp: boolean | undefined;
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Use `false` instead of `undefined` ?
