### PR TITLE
fix(41526): Infer parameter types from usage inserts JSDoc type at wrong location for arrow function

### LINKED ISSUE #41526: Infer parameter types from usage inserts JSDoc type at wrong location for arrow function
**TypeScript Version:**  4.2.0-dev.20201113

**Search Terms:**
- Quick fix
- Code action
- suggestion
- jsdoc

**Code**
For the JavaScript:

```js
// @ts-check

export function filter(names) {
    return names.filter(name => name.startsWith(''))
}
```

Run the `infer parameter types from usage` quick fix on `name` inside the function body

**Expected behavior:**
Something like:

```js
export function filter(names) {
    return names.filter((/** @type {string} */ name) => name.startsWith(''))
}
```

**Actual behavior:**
```js
export function filter(names) {
    /**
     * @param {string} name
     */
    return names.filter(name => name.startsWith(''))
}
```

The added JSDoc annotation is not valid so the type is not used by TypeScript. We continue to show the `infer parameter types from usage` on `name`

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41526

### CODE REVIEW

File: src/services/codefixes/inferFromUsage.ts [hunk 1]
```diff
@@ -333,21 +333,50 @@ namespace ts.codefix {
     }
 
     function annotateJSDocParameters(changes: textChanges.ChangeTracker, sourceFile: SourceFile, parameterInferences: readonly ParameterInference[], program: Program, host: LanguageServiceHost): void {
-        const signature = parameterInferences.length && parameterInferences[0].declaration.parent;
```
Comment (sandersn) [inline src/services/codefixes/inferFromUsage.ts:336]: why not keep using `[0]` here? The code just checked that `parameterInferences.length > 0`, which is the only other thing that `first` does.

File: src/services/codefixes/inferFromUsage.ts [hunk 2]
```diff
@@ -333,21 +333,50 @@ namespace ts.codefix {
...
+                return { name: factory.cloneNode(param.name), param, isOptional: !!inference.isOptional, typeNode };
+            }
         });
-        addJSDocTags(changes, sourceFile, signature, paramTags);
+
+        if (!inferences.length) {
+            return;
+        }
+
+        if ((isArrowFunction(signature) || isFunctionExpression(signature)) && isCallExpression(signature.parent)) {
```
Comment (sandersn) [inline src/services/codefixes/inferFromUsage.ts:359]: Doesn't this need to happen everywhere except the initialiser of a variable declaration? That might not quite be right, but I expected to see some negated condition instead of `isCallExpression`.

File: src/services/codefixes/inferFromUsage.ts [hunk 3]
```diff
@@ -333,21 +333,50 @@ namespace ts.codefix {
...
+            const needParens = isArrowFunction(signature) && !findChildOfKind(signature, SyntaxKind.OpenParenToken, sourceFile);
+            if (needParens) {
+                changes.insertNodeBefore(sourceFile, first(signature.parameters), factory.createToken(SyntaxKind.OpenParenToken));
+            }
+
+            forEach(inferences, ({ typeNode, param }) => {
```
Comment (sandersn) [inline src/services/codefixes/inferFromUsage.ts:365]: I'm not sure if it's better, but you could also generate:

```ts
return names.filter(/** 
 * @param {string} name
 * @param {number} index
 */ (string, index ) => ....)
```

That's probably what a human would write, but it's way harder to format properly.

Did you consider that option? Do you think it would work?
```

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/services/codefixes/inferFromUsage.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/codefixes/inferFromUsage.ts:359]: Based on the issue description, I thought that we need to use this kind of type of definition, to arrow functions or function expressions that used as arguments in call expressions. Like so

```ts
foo((a) => {})
```

```ts
foo(function (a) => {})
```

File: src/services/codefixes/inferFromUsage.ts (hunk 3 above)
Comment (a-tarasyuk) [reply src/services/codefixes/inferFromUsage.ts:365]: No, I didn't. I just used the option from the `Expected behavior` section. If the proposed option better, I can try to change. I think we can ask the author of the issue if it is an acceptable option for him.

Maybe comment should be formatted like so

```ts
return names.filter(
    /**
     * @param {string} name
     * @param {number} index
     */
    (string, index) => index
);
```

Comment (sandersn) [reply src/services/codefixes/inferFromUsage.ts:365]: I commented on the bug, but let's proceed with what you have now.

File: src/services/codefixes/inferFromUsage.ts (hunk 2 above)
Comment (sandersn) [reply src/services/codefixes/inferFromUsage.ts:359]: I think the codefix will also generate incorrect code for the following case, for example:

```ts
/** @type {} */
let fs = [x => x + 1, y => y + 2]
```

Though perhaps the codefix wouldn't even apply with or without the `@type` annotation.

File: src/services/codefixes/inferFromUsage.ts (hunk 3 above)
Comment (a-tarasyuk) [reply src/services/codefixes/inferFromUsage.ts:365]: Oke

**Review by sandersn — APPROVED** [review]
