### PR TITLE
fix(44639): Transpilation of optional chaining combined with type casting results in function call losing its context

### LINKED ISSUE #44639: Transpilation of optional chaining combined with type casting results in function call losing its context
# Bug Report

### 🔎 Search Terms

optional chaining, type casting, transpiling

### 🕗 Version & Regression Information

When transpiling the optional chaining feature on a method class and combining it to a type casting, the generated code makes the function call loses its context (`this`).

The same does not occur when transpiling the optional chaining feature without the type casting, or if you use type casting without transpiled optional chaining.

The behavior is the same since optional chaining was introduced to TypeScript since version 3.7. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&ts=3.7.5&strict=true#code/MYGwhgzhAEAqCmEAu9oG8BQ1vRc+AFAJTpY7kBO8SArhQHbQBsLA3GdgL4bfAD29ZLmgBeaPXgB3OIhTF2GAPSLoAIRoBzDQE9oAI3gALMADcAlnwoAuJSqTaADqmCQkZ+huhh6AE2h8HNwEwEGhgY3d3T34AWz13eD8YsABrRGgAMxp6YCDGFxBQkD4IdPdkb2BnARQADyQMAiQAOjwULxhvbSIAfmb5DFtoAGFLKlz9I1MLCggbZVxDVAgwGNQM+DBaKhgaUr93HzNzHxoQkF0fPnT6PiRoZLTF9ezci3zz6GLSmHKkSuq9DqDSarVkqEgXno3QGoLa8F6-SI7CAA)

### 💻 Code

Original TypeScript code:

```ts
class Teste {
    teste() {
        return 666;
    }
}
const t = new Teste();

// Buggy behavior:
// type casting and optional chaining combined makes function call loses instance context
(t.teste as any)?.();

// Correct behaviors:
// the same features used individually does not make the function call loses instance context
(t.teste as any)();
(t.teste)?.();
```

Transpiles to:

```js
"use strict";
var _a, _b, _c;
class Teste {
    teste() {
        return 666;
    }
}
const t = new Teste();

// Buggy behavior:
// type casting and optional chaining combined makes function call loses instance context
(_a = t.teste) === null || _a === void 0 ? void 0 : _a();

// Correct behaviors:
// the same features used individually does not make the function call loses instance context
t.teste();
(_c = ((_b = t).teste)) === null || _c === void 0 ? void 0 : _c.call(_b);
```

### 🙂 Expected behavior

I believe that type casting should not make transpilation generates different code with different behavior for optional chaining or any other feature.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #44639

### CODE REVIEW

File: src/compiler/transformers/es2020.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ namespace ts {
                 Debug.assertNotNode(chain, isNonNullChain);
                 links.unshift(chain);
             }
-            return { expression: chain.expression, chain: links };
+            return { expression: skipPartiallyEmittedExpressions(chain.expression), chain: links };
```
Comment (rbuckton) [inline src/compiler/transformers/es2020.ts:57]: This will result in a loss of some leading or trailing comments. I'd recommend doing this in `visitOptionalExpression` instead, and using `factory.restoreOuterExpressions` to preserve comments:

```ts
// visitOptionalExpression
const left = visitNonOptionalExpression(skipPartiallyEmittedExpressions(expression), isCallChain(chain[0]), /*isDelete*/ false);
//                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- Skip here
const leftThisArg = isSyntheticReference(left) ? left.thisArg : undefined;
let capturedLeft = isSyntheticReference(left) ? left.expression : left;
//  ^^^^^^^^^^^^- Swap assignment order for capturedLeft/leftExpression
let leftExpression = factory.restoreOuterExpressions(expression, capturedLeft, OuterExpressionKinds.PartiallyEmittedExpressions);
//                           ^^^^^^^^^^^^^^^^^^^^^^^- Restore here
if (!isSimpleCopiableExpression(capturedLeft)) {
    //                          ^^^^^^^^^^^^- Swap argument to capturedLeft
    capturedLeft = factory.createTempVariable(hoistVariableDeclaration);
    leftExpression = factory.createAssignment(capturedLeft, leftExpression);
}
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/compiler/transformers/es2020.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/es2020.ts:57]: I would also add a test for comment preservation, something like this:
```ts
/*a1*/(/*a2*/foo.m as any/*a3*/)/*a4*/?.();
/*b1*/(/*b2*/<any>foo.m/*b3*/)/*b4*/?.();
```

Comment (a-tarasyuk) [reply src/compiler/transformers/es2020.ts:57]: It seems with both options comments `/*a2*/` and `/*b2*/` will be lost. Will check that case 
```js
// return { expression: skipPartiallyEmittedExpressions(chain.expression), chain: links };

/*a1*/ foo.m /*a3*/ /*a4*/?.();
/*b1*/ foo.m /*b3*/ /*b4*/?.();
````

```js
// factory.restoreOuterExpressions
/*a1*/ foo.m /*a3*/ /*a4*/?.();
/*b1*/ foo.m /*b3*/ /*b4*/?.();
```

Comment (a-tarasyuk) [reply src/compiler/transformers/es2020.ts]: @rbuckton Thanks for the feedback. How TS should emit comments for that case? 

```js
// es2015
/*a1*/ (_c = foo.m /*a3*/ /*a4*/) === null || _c === void 0 ? void 0 : _c.call(/*a2*/ foo);
/*b1*/ (_d = foo.m /*b3*/ /*b4*/) === null || _d === void 0 ? void 0 : _d.call(foo);
```

```js
// esnext
/*a1*/ foo.m /*a3*/ /*a4*/?.(); 
/*b1*/ foo.m /*b3*/ /*b4*/?.();
```
Do we need to attach `/*a2*/`/`/*b2*/` after `/*a1*/`/`/*b1*/`?

Comment (rbuckton) [reply src/compiler/transformers/es2020.ts]: For both I would expect `/*a2*/`/`/*b2*/` to be attached after `/*a1*/`/`/*b1*/`, however the fact those comments aren't present in `esnext` is an issue with how `PartiallyEmittedExpression` nodes are handled in the emitter. I can push a fix to this PR that handles that and this should be good to merge.

**Comment by rbuckton** [comment]
I should be able to merge this shortly.

@weswigham: Can you take a quick look at the changes in https://github.com/microsoft/TypeScript/pull/44666/commits/d7d04343215d93fde4fcc6fb99809873945b844f since this changes something you fixed a few years ago?

**Comment by rbuckton** [comment]
@DanielRosenwasser, @andrewbranch: Should we take this for 4.5? If so, I can cherry pick once this is merged.

**Review by rbuckton — APPROVED** [review]
Looks good, though I'd like to get a review from someone else on the TS team for my changes in _emitter.ts_ and _ts.ts_ around ASI and comment handling.

**Comment by andrewbranch** [comment]
I think this should target 4.6 at this point.

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -2971,9 +2971,49 @@ namespace ts {
...
+
+        function willEmitLeadingNewLine(node: Expression): boolean {
+            if (!currentSourceFile) return false;
+            if (some(getLeadingCommentRanges(currentSourceFile.text, node.pos), commentWillEmitNewLine)) return true;
+            if (some(getSyntheticLeadingComments(node), commentWillEmitNewLine)) return true;
+            if (isPartiallyEmittedExpression(node)) {
+                if (node.pos !== node.expression.pos) {
+                    if (some(getTrailingCommentRanges(currentSourceFile.text, node.expression.pos), commentWillEmitNewLine)) return true;
+                }
+                return willEmitLeadingNewLine(node.expression);
```
Comment (weswigham) [inline src/compiler/emitter.ts:2986]: Technically this condition could be checked without `currentSourceFile` and so could happen before that check so as to make it work for weird no-source-file printer invocations (as could one or two other conditions here), but that's probably not something that matters.

**Review by weswigham — APPROVED** [review]
