### PR TITLE
Error for abstract property with initialiser

### LINKED ISSUE #42287: Inconsistent error for initialization of abstract property
# Bug Report

### 🔎 Search Terms

abstract property initializer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `abstract`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210111#code/IYIwzgLgTsDGEAJYBthjAgwgg3gWACgFiFRIZ4EAHKAeyoQF4EBGAbkJKVoDtyBXeLSgAKAJS5OXEhAAWASzAA6GvSasOREgF9C2oA)

### 💻 Code

```ts
abstract class C {
    abstract prop = 1; // this is allowed
    constructor() {
        this.prop = 1; // this is not allowed
    }
}
```

### 🙁 Actual behavior

No error on the property initializer, but on the assignment in constructor. Though the initializer is not emitted.

Aside: what is an "abstract property" anyway? There's nothing the derived class can implement about that property in terms of actual executable code. It cannot even implement it as accessor, because that's no longer allowed since `useDefineForClassFields` was introduced.

### 🙂 Expected behavior

The initializer should be an error too, because the property declaration including its initializer is NOT emitted.

/cc @sandersn who seems to be responsible for all the things abstract and recently looked into this.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #42287 

Abstract properties should not allow initialisers in the same way that abstract methods do not.

I did a quick survey of my usual user test+DT corpora and found no instances of this, so I don't think it's going to break anybody's code.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -33089,8 +33093,7 @@ namespace ts {
             // Grammar checking for modifiers is done inside the function checkGrammarFunctionLikeDeclaration
             checkFunctionOrMethodDeclaration(node);
 
-            // Abstract methods cannot have an implementation.
-            // Extra checks are to avoid reporting multiple errors relating to the "abstractness" of the node.
+            // method signatures already report "implementation not allowed in ambient context" elsewhere
```
Comment (sandersn) [inline src/compiler/checker.ts:33096]: This is the code I copied. While here, I deleted the first comment line because it restates the code itself, and reworded the second comment line because I couldn't figure out what it meant until I read the comments on the original PR.

**Comment by sandersn** [comment]
Ping: This is a small change, I just need an opinion on whether it's a good idea.

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -879,6 +879,10 @@
         "category": "Error",
         "code": 1266
     },
+    "Property '{0}' cannot have an initializer because it is marked abstract.": {
```
Comment (DanielRosenwasser) [inline src/compiler/diagnosticMessages.json:882]:
```suggestion
    "Property '{0}' cannot have an initializer because it is marked 'abstract'.": {
```

Maybe? Then https://github.com/microsoft/TypeScript/actions?query=workflow%3A%22Accept+Baselines+and+Fix+Lints%22

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Please add some content to https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes if/when you merge this. Slight preference for 4.4.

**Comment by sandersn** [comment]
It was late to put a breaking change into 4.3 9 days ago, and it's even later now. I'm going to hold this for 4.4.
