### PR TITLE
Fix crash when importsNotUsedAsValues is set alongside verbatimModuleSyntax

### LINKED ISSUE #53302: adding typescript 5 option "verbatimModuleSyntax": true in tsconfig causes crash
# Bug Report

### 🔎 Search Terms
- verbatimModuleSyntax

### 🕗 Version & Regression Information

- This is a crash using the new `verbatimModuleSyntax` option in typescript version `5.0.2`

### ⏯ Playground Link

This doesn't seem code related, it seems related to the compiler options
### 💻 Code

tsconfig.json
```
{
    "extends": "@tsconfig/node18-strictest-esm/tsconfig.json",
    "compilerOptions": {
        "outDir": "dist",
        "module": "node16",
        "moduleResolution": "node16",
        "moduleDetection": "force",
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": false,
        "declaration": true,
        "pretty": true,
        "newLine": "lf",
        "removeComments": true,
        "noEmitOnError": true,
        "useDefineForClassFields": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "exactOptionalPropertyTypes": false,
        "verbatimModuleSyntax": true,
        "ignoreDeprecations": "5.0" // TODO: when node18-strictest-esm is updated for typescript 5 remove this
    },
    "include": ["src"],
    "exclude": ["node_modules", "dist"]
}
```

### 🙁 Actual behavior

```
> tsc

/Projects/mysql-query/node_modules/typescript/lib/tsc.js:113959
      throw e;
      ^

Error: Debug Failure. False expression.
    at isReferencedAliasDeclaration (/Projects/mysql-query/node_modules/typescript/lib/tsc.js:80348:11)
    at canConvertImportDeclarationToTypeOnly (/Projects/mysql-query/node_modules/typescript/lib/tsc.js:78887:175)
    at checkImportsForTypeOnlyConversion (Projects/mysql-query/node_modules/typescript/lib/tsc.js:78902:11)
    at checkSourceFileWorker (/Projects/mysql-query/node_modules/typescript/lib/tsc.js:79465:9)
    at checkSourceFile (//Projects/mysql-query/node_modules/typescript/lib/tsc.js:79413:5)
    at checkSourceFileWithEagerDiagnostics (/Projects/mysql-query/node_modules/typescript/lib/tsc.js:79507:5)
    at getDiagnosticsWorker (/Projects/mysql-query/node_modules/typescript/lib/tsc.js:79515:7)
    at Object.getDiagnostics (/ /Projects/mysql-query/node_modules/typescript/lib/tsc.js:79492:14)
    at / /Projects/mysql-query/node_modules/typescript/lib/tsc.js:113984:76
    at runWithCancellationToken (/Projects/mysql-query/node_modules/typescript/lib/tsc.js:113954:14)

Node.js v18.15.0`
```

Note that if I set `"verbatimModuleSyntax": false`  it doesn't crash. The build runs.

### 🙂 Expected behavior

A clean build or an error message about what is incompatible with setting `"verbatimModuleSyntax": true`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #53302

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1472,6 +1472,9 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     var argumentsSymbol = createSymbol(SymbolFlags.Property, "arguments" as __String);
     var requireSymbol = createSymbol(SymbolFlags.Property, "require" as __String);
     var isolatedModulesLikeFlagName = compilerOptions.verbatimModuleSyntax ? "verbatimModuleSyntax" : "isolatedModules";
+    // It is an error ro use `importsNotUsedAsValues` alongside `verbatimModuleSyntax`, but we still need to not crash.
```
Comment (jakebailey) [inline src/compiler/checker.ts:1475]: Shameful nit:

```suggestion
    // It is an error to use `importsNotUsedAsValues` alongside `verbatimModuleSyntax`, but we still need to not crash.
```

Comment (jakebailey) [reply src/compiler/checker.ts:1475]: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FTypeScript%2Fpull%2F53383%23pullrequestreview-1349124507&data=05%7C01%7CJacob.Bailey%40microsoft.com%7C22bfbfc87d50418fcd2208db296c39f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638149317029984634%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J3Cfl5%2BXXEWqTJNep4aVpRuqUFC%2FdAjuXR2QHZVaTmM%3D&reserved=0

Comment (jakebailey) [reply src/compiler/checker.ts:1475]: (removed "shameful", i meant shameful that I'd send a 1 character diff, but I realized after I sent it that it sounded like I was shaming the typo which is absolutely NOT what I meant, sorry)

**Review by andrewbranch — APPROVED** [review]
