### PR TITLE
Make export var or export *'s with duplicate identifiers an error

### LINKED ISSUE #4527: TS Doesn't handle multiple exports with the same name correctly
```ts
export var seven = 7;
export var seven = 7;
```
This is ~~valid~~_invalid_, and TS doesn't error on it.

```ts
export var seven = 7;
export var seven = 8;
```
This is _invalid_, and TS doesn't error on it.

[The spec:](http://www.ecma-international.org/ecma-262/6.0/#sec-resolveexport)
> 1. For each ExportEntry Record e in module.[[StarExportEntries]], do
>    1. Let importedModule be HostResolveImportedModule(module, e.[[ModuleRequest]]).
>    2. ReturnIfAbrupt(importedModule).
>    3. Let resolution be importedModule.ResolveExport(exportName, resolveSet, exportStarSet).
>    4. ReturnIfAbrupt(resolution).
>    5. If resolution is "ambiguous", return "ambiguous".
>    6. If resolution is not null, then
>      1. If starResolution is null, let starResolution be resolution.
>      2. Else
>        1. Assert: there is more than one * import that includes the requested name.
>         2. If resolution.[[module]] and starResolution.[[module]] are not the same Module Record or SameValue(resolution.[[exportName]], starResolution.[[exportName]]) is false, return "ambiguous".

~~A module is free to export the same value (as in the same value spec function) multiple times, but exporting different values under the same identifier should be a syntax error.~~ This should also be an error:
```ts
export var state = {};
export var state = {};
```
Because unique objects do not pass the `SameValue()` test. (It is not currently reported as an error.)

~~Given that we don't want to attempt to evaluate RHS expressions to resolve the same value functions, we're pretty much stuck using type information to infer the same thing. Or we could just forbid the re-declaration of exports, given that since you're forced the reexport the exact same value or error, there's no _real_ value in doing so.~~

And perhaps [the more relevant part of the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-module-semantics-static-semantics-early-errors) that I found:

> 15.2.1.1 Static Semantics: Early Errors
> It is a Syntax Error if the ExportedNames of ModuleItemList contains any duplicate entries.

 We do forbid multiple default exports already, but don't check other names if the types match for some reason?

### PR DESCRIPTION
**Pull request by weswigham**
Closes #4527. The relevant spec points were referenced in that issue. Namespaces, interfaces, and function overloads (so TS constructs) are exempt from the duplicate identifier check.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1020,38 +1020,62 @@ namespace ts {
...
+                            let exportedSymbols = visit(resolvedModule);
+                            extendExportSymbols(
+                                nestedSymbols,
+                                exportedSymbols,
+                                lookupTable,
+                                node as ExportDeclaration
+                            );
+                        }
+                        for (let id in lookupTable) {
+                            if (id !== "export=" && lookupTable[id].exportsWithDuplicate.length && !(id in symbols)) { // It's not an error if the file with multiple export *'s with duplicate names exports a member with that name itself
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Move the comment onto a line above

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -1020,38 +1020,62 @@ namespace ts {
...
+                                for (let node of lookupTable[id].exportsWithDuplicate) {
+                                    diagnostics.add(createDiagnosticForNode(node, Diagnostics.An_export_Asterisk_from_0_declaration_has_already_exported_a_member_named_1_Consider_explicitly_re_exporting_to_resolve_the_ambiguity, lookupTable[id].specifierText, id));
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Break this into multiple lines

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -13698,13 +13722,33 @@ namespace ts {
 
         function checkExternalModuleExports(node: SourceFile | ModuleDeclaration) {
             let moduleSymbol = getSymbolOfNode(node);
-            let links = getSymbolLinks(moduleSymbol);
+            let links: SymbolLinks = getSymbolLinks(moduleSymbol);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Why did you need this type annotation?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -13698,13 +13722,33 @@ namespace ts {
...
             if (!links.exportsChecked) {
                 let exportEqualsSymbol = moduleSymbol.exports["export="];
                 if (exportEqualsSymbol && hasExportedMembers(moduleSymbol)) {
                     let declaration = getDeclarationOfAliasSymbol(exportEqualsSymbol) || exportEqualsSymbol.valueDeclaration;
                     error(declaration, Diagnostics.An_export_assignment_cannot_be_used_in_a_module_with_other_exported_elements);
                 }
+                let exports = getExportsOfModule(moduleSymbol); // Checks for export * conflicts
+                for (let id in exports) {
+                    if (id === "__export") continue;
+                    if (!(exports[id].flags & SymbolFlags.Namespace || exports[id].flags & SymbolFlags.Interface) && exports[id].declarations.length > 1) { // 15.2.1.1 It is a Syntax Error if the ExportedNames of ModuleItemList contains any duplicate entries. (TS Exceptions: namespaces, function overloads, and interfaces)
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Move the comment above

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: What about enums?

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Extract `exports[id]` to a variable so you avoid multiple lookups on `id`

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [inline src/compiler/checker.ts]: I don't. :3 I wrote it in to use go to definition on it, and forgot to remove it.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [inline src/compiler/checker.ts]: Good point about enums - they do merge, don't they. I'll add them to the conditional and to the test.

**Comment by weswigham** [comment]
@DanielRosenwasser updated.

File: src/compiler/checker.ts (hunk 3 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: https://github.com/dotnet/roslyn/issues/2505

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -1020,38 +1020,68 @@ namespace ts {
             return links.resolvedExports || (links.resolvedExports = getExportsForModule(moduleSymbol));
         }
 
-        function extendExportSymbols(target: SymbolTable, source: SymbolTable) {
+        interface ExportStarDiagnosticsLookupTable {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Why not just make this a `Map<ExportDeclaration[]>` and use the `id` as the text?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -1020,38 +1020,68 @@ namespace ts {
...
+            [id: string]: {specifierText: string, exportsWithDuplicate: ExportDeclaration[]};
+        }
+
+        function extendExportSymbols(target: SymbolTable, source: SymbolTable, lookupTable?: ExportStarDiagnosticsLookupTable, exportNode?: ExportDeclaration) {
             for (let id in source) {
                 if (id !== "default" && !hasProperty(target, id)) {
                     target[id] = source[id];
+                    if (lookupTable && exportNode) {
+                        lookupTable[id] = {
+                            specifierText: getTextOfNode(exportNode.moduleSpecifier),
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I'd prefer to use the`.text` because the message will look awkward if you use single quotes.

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [inline src/compiler/checker.ts]: That's fine, but naming the type yields more informative documentation, no?

File: src/compiler/checker.ts (hunk 6 above)
Comment (weswigham) [inline src/compiler/checker.ts]: ...What if I change the message to use backticks around the code quote, markdown style? I'd rather not change the user's text on the import in the error where possible - makes it less ctrl-f'able.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Maybe, though that always looks odd somehow. Bring it up with @mhegazy.

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [inline src/compiler/checker.ts]: Also, the text isn't the id of the symbol in the map - the map key id is the duplicated symbol's id, the text is the text of the export specifier it was first found in.

**Comment by weswigham** [comment]
@mhegazy I've refreshed this PR  - we'd probably still want it so we align with the spec, right?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -13978,6 +14009,28 @@ namespace ts {
                     const declaration = getDeclarationOfAliasSymbol(exportEqualsSymbol) || exportEqualsSymbol.valueDeclaration;
                     error(declaration, Diagnostics.An_export_assignment_cannot_be_used_in_a_module_with_other_exported_elements);
                 }
+                const exports = getExportsOfModule(moduleSymbol); // Checks for export * conflicts
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Move comment above

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -13978,6 +14009,28 @@ namespace ts {
                     const declaration = getDeclarationOfAliasSymbol(exportEqualsSymbol) || exportEqualsSymbol.valueDeclaration;
                     error(declaration, Diagnostics.An_export_assignment_cannot_be_used_in_a_module_with_other_exported_elements);
                 }
+                const exports = getExportsOfModule(moduleSymbol); // Checks for export * conflicts
+                for (const id in exports) {
+                    if (id === "__export") continue;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Curlies

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -1055,38 +1055,69 @@ namespace ts {
...
+                            extendExportSymbols(
+                                nestedSymbols,
+                                exportedSymbols,
+                                lookupTable,
+                                node as ExportDeclaration
+                            );
+                        }
+                        for (const id in lookupTable) {
+                            // It's not an error if the file with multiple export *'s with duplicate names exports a member with that name itself
+                            if (id !== "export=" && lookupTable[id].exportsWithDuplicate.length && !(id in symbols)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Instead of nesting the `for`, negate the condition and bail out

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Also, declare a variable for `lookupTable[id].exportsWithDuplicate`

**Comment by weswigham** [comment]
@DanielRosenwasser feedback incorporated

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -1093,38 +1093,71 @@ namespace ts {
...
+                            extendExportSymbols(
+                                nestedSymbols,
+                                exportedSymbols,
+                                lookupTable,
+                                node as ExportDeclaration
+                            );
+                        }
+                        for (const id in lookupTable) {
+                            const { exportsWithDuplicate } = lookupTable[id];
+                            // It's not an error if the file with multiple export *'s with duplicate names exports a member with that name itself
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: no apostrophe

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -14040,8 +14073,29 @@ namespace ts {
...
                     error(declaration, Diagnostics.An_export_assignment_cannot_be_used_in_a_module_with_other_exported_elements);
                 }
+                // Checks for export * conflicts
+                const exports = getExportsOfModule(moduleSymbol);
+                for (const id in exports) {
+                    if (id === "__export") {
+                        continue;
+                    }
+                    const exportedSymbol = exports[id];
+                     // 15.2.1.1 It is a Syntax Error if the ExportedNames of ModuleItemList contains any duplicate entries. (TS Exceptions: namespaces, function overloads, enums, and interfaces)
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Prefix this with the spec you're quoting (i.e. TS or ECMA262)

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Should we be allowing these exceptions?

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -14040,8 +14073,29 @@ namespace ts {
...
+                    if (!(exportedSymbol.flags & SymbolFlags.Namespace || exportedSymbol.flags & SymbolFlags.Interface || exportedSymbol.flags & SymbolFlags.Enum) && exportedSymbol.declarations.length > 1) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `exportedSymbol.flags & (SymbolFlags.NameSpace | SymbolFlags.Interface | SymbolFlags.Enum)`

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -14040,8 +14073,29 @@ namespace ts {
                     const declaration = getDeclarationOfAliasSymbol(exportEqualsSymbol) || exportEqualsSymbol.valueDeclaration;
                     error(declaration, Diagnostics.An_export_assignment_cannot_be_used_in_a_module_with_other_exported_elements);
                 }
+                // Checks for export * conflicts
+                const exports = getExportsOfModule(moduleSymbol);
+                for (const id in exports) {
+                    if (id === "__export") {
+                        continue;
+                    }
+                    const exportedSymbol = exports[id];
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Consider destructuring `flags` and `declarations`

File: src/compiler/checker.ts (hunk 11 above)
Comment (weswigham) [inline src/compiler/checker.ts]: Based on the way we do should ES6 exports for namespaces and enums, I believe so (the others are types and are fine). Namespaces and enums should end up roughly like this in ES6 forms:
```js
var Namespace_1;
(function(Namespace_1){
 // ...
})(Namespace_1 = Namespace_1 || {});
var Namespace_1;
(function(Namespace_1){
 // ...
})(Namespace_1 = Namespace_1 || {});
export var Namespace = Namespace_1;
```

*checks*
Our present emit is actually
```js
export var Foo;
(function (Foo) {
    Foo.cat = 2;
})(Foo || (Foo = {}));
export var Foo;
(function (Foo) {
    Foo.dog = 2;
})(Foo || (Foo = {}));
```
Which is in this case incorrect (it introduces duplicated exported identifiers) - I'll need to change the emit.

**Comment by weswigham** [comment]
@DanielRosenwasser I've incorporated your feedback and in response to your feedback about weather namespaces should be exempt or not and corrected their emit - I still need to check enums, though.

**Comment by weswigham** [comment]
Handled enums correctly - now enums and namespaces will have only one exported binding when targeting ES6 modules, no matter how many declarations they have. :+1:

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -14040,8 +14073,29 @@ namespace ts {
...
+                                diagnostics.add(createDiagnosticForNode(declaration, Diagnostics.Cannot_redeclare_exported_variable_0, id));
+                            }
+                        }
+                    }
+                }
                 links.exportsChecked = true;
             }
+
+            function isNotOverload(declaration: Declaration): boolean {
+                return (declaration.kind !== SyntaxKind.FunctionDeclaration || typeof (declaration as FunctionDeclaration).body !== "undefined");
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Remove parens - also do you need to use `typeof`?

File: src/compiler/diagnosticMessages.json [hunk 15]
```diff
@@ -836,6 +836,10 @@
         "category": "Error",
         "code": 2307
     },
+    "An `export * from {0}` declaration has already exported a member named '{1}'. Consider explicitly re-exporting to resolve the ambiguity.": {
```
Comment (DanielRosenwasser) [inline src/compiler/diagnosticMessages.json]: Module {0} has already exported a member named '{1}'. Consider explicitly re-exporting to resolve the ambiguity."

File: src/compiler/checker.ts [hunk 16]
```diff
@@ -1093,38 +1093,71 @@ namespace ts {
             return links.resolvedExports || (links.resolvedExports = getExportsForModule(moduleSymbol));
         }
 
-        function extendExportSymbols(target: SymbolTable, source: SymbolTable) {
+        interface ExportedSymbolDiagnostics {
+            specifierText: string;
+            exportsWithDuplicate: ExportDeclaration[];
+        }
+
+        function extendExportSymbols(target: SymbolTable, source: SymbolTable, lookupTable?: Map<ExportedSymbolDiagnostics>, exportNode?: ExportDeclaration) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: At a cursory glance, it's hard for me to understand exactly what's going on. Can you add a quick comment for what this is and what it's used for?

For instance, what does `lookupTable` do? Which of these are you going to modify?

File: src/compiler/checker.ts [hunk 17]
```diff
@@ -1093,38 +1093,71 @@ namespace ts {
             return links.resolvedExports || (links.resolvedExports = getExportsForModule(moduleSymbol));
         }
 
-        function extendExportSymbols(target: SymbolTable, source: SymbolTable) {
+        interface ExportedSymbolDiagnostics {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: It's not clear what this is; "diagnostics" typically implies something to do with error messages.

File: src/compiler/checker.ts (hunk 14 above)
Comment (weswigham) [inline src/compiler/checker.ts]: ...probably not. For some reason I thought body was a `string`, when it should be `FunctionBody`.

File: src/compiler/checker.ts (hunk 17 above)
Comment (weswigham) [inline src/compiler/checker.ts]: It's an structure used just to collect data to generate an error message from, so Diagnostics seems appropriate.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: What about `ExportCollisionTracker`?

Comment (weswigham) [inline src/compiler/checker.ts]: Sure.

**Comment by weswigham** [comment]
@DanielRosenwasser any further comments?

File: src/compiler/emitter.ts [hunk 18]
```diff
@@ -6209,9 +6209,11 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
 
                 if (!shouldHoistDeclarationInSystemJsModule(node)) {
                     // do not emit var if variable was already hoisted
-                    if (!(node.flags & NodeFlags.Export) || isES6ExportedDeclaration(node)) {
+
+                    const isES6ExportedEnum = isES6ExportedDeclaration(node);
+                    if ((!(node.flags & NodeFlags.Export)) || (isES6ExportedEnum && isFirstDeclarationOfKind(node, node.symbol && node.symbol.declarations, SyntaxKind.EnumDeclaration))) {
```
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts]: I think there's an extra nested paren

File: src/compiler/emitter.ts [hunk 19]
```diff
@@ -6321,15 +6327,18 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
                 const emitVarForModule = !hoistedInDeclarationScope && !isModuleMergedWithES6Class(node);
 
                 if (emitVarForModule) {
-                    emitStart(node);
-                    if (isES6ExportedDeclaration(node)) {
-                        write("export ");
+                    const isES6ExportedNamespace = isES6ExportedDeclaration(node);
+                    if ((!isES6ExportedNamespace) || isFirstDeclarationOfKind(node, node.symbol && node.symbol.declarations, SyntaxKind.ModuleDeclaration)) {
```
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts]: Is it appropriate to assume that a node has a a symbol? Maybe just `Debug.assert(!!node.symbol)`

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by weswigham** [comment]
Ran RWC tests for this change and found it only affected angular - _however_ it exposed a bug in my check, it is _valid_ to reexport the same thing via multiple `export *`'s provided those bindings are to the same value within the same module (eg, module A reexports foo from C and foo from B, while module B is reexporting foo from C) - this is okay because the resolution is not "ambiguous", as both bindings are the same value from the same module. (ECMA 262 [15.2.1.16.3](http://www.ecma-international.org/ecma-262/6.0/#sec-resolveexport) 10.f.ii.2) Once this is accounted for in this PR, I don't think angular (or anything else in our RWC tests) will have any errors with this change.

**Comment by weswigham** [comment]
Now all rwc tests pass with this change. :+1:

File: src/compiler/emitter.ts (hunk 19 above)
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts]: Remvoe extra paren

File: src/compiler/checker.ts [hunk 20]
```diff
@@ -14095,8 +14132,29 @@ namespace ts {
                     const declaration = getDeclarationOfAliasSymbol(exportEqualsSymbol) || exportEqualsSymbol.valueDeclaration;
                     error(declaration, Diagnostics.An_export_assignment_cannot_be_used_in_a_module_with_other_exported_elements);
                 }
+                // Checks for export * conflicts
+                const exports = getExportsOfModule(moduleSymbol);
+                for (const id in exports) {
+                    if (id === "__export") {
+                        continue;
+                    }
+                    const {declarations, flags} = exports[id];
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Space inside of `{ }`

File: src/compiler/checker.ts [hunk 21]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
+                            extendExportSymbols(
+                                nestedSymbols,
+                                exportedSymbols,
+                                lookupTable,
+                                node as ExportDeclaration
+                            );
+                        }
+                        for (const id in lookupTable) {
+                            const { exportsWithDuplicate } = lookupTable[id];
+                            // Its not an error if the file with multiple export *'s with duplicate names exports a member with that name itself
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: It's

File: src/compiler/checker.ts [hunk 22]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
+            function visit(symbol: Symbol): SymbolTable {
                 if (symbol && symbol.flags & SymbolFlags.HasExports && !contains(visitedSymbols, symbol)) {
                     visitedSymbols.push(symbol);
-                    if (symbol !== moduleSymbol) {
-                        if (!result) {
-                            result = cloneSymbolTable(moduleSymbol.exports);
-                        }
-                        extendExportSymbols(result, symbol.exports);
-                    }
+                    const symbols: SymbolTable = cloneSymbolTable(symbol.exports);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Do you need this type annotation?

File: src/compiler/checker.ts [hunk 23]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
+                                nestedSymbols,
+                                exportedSymbols,
+                                lookupTable,
+                                node as ExportDeclaration
+                            );
+                        }
+                        for (const id in lookupTable) {
+                            const { exportsWithDuplicate } = lookupTable[id];
+                            // Its not an error if the file with multiple export *'s with duplicate names exports a member with that name itself
+                            if (id === "export=" || !exportsWithDuplicate.length || id in symbols) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Use `hasProperty`

Comment (weswigham) [inline src/compiler/checker.ts]: Is this a rule for us?

File: src/compiler/checker.ts (hunk 22 above)
Comment (weswigham) [inline src/compiler/checker.ts]: Probably not.

File: src/compiler/checker.ts (hunk 23 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Maybe it should be, but there are places where we probably use `in` *in*tentionally

Comment (weswigham) [inline src/compiler/checker.ts]: :clap:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by weswigham** [comment]
@vladima would you go over this PR?

File: src/compiler/checker.ts [hunk 24]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
         }
 
-        function extendExportSymbols(target: SymbolTable, source: SymbolTable) {
+        interface ExportCollisionTracker {
+            specifierText: string;
+            exportsWithDuplicate: ExportDeclaration[];
+        }
+
+        /**
+         * Extends one symbol table with abother while collecting information on name collisions for error message generation into the `lookupTable` argument
```
Comment (vladima) [inline src/compiler/checker.ts]: another

File: src/compiler/checker.ts [hunk 25]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
                 if (id !== "default" && !hasProperty(target, id)) {
                     target[id] = source[id];
+                    if (lookupTable && exportNode) {
+                        lookupTable[id] = {
+                            specifierText: getTextOfNode(exportNode.moduleSpecifier),
+                            exportsWithDuplicate: []
+                        };
+                    }
+                }
+                else if (lookupTable && exportNode && id !== "default" && hasProperty(target, id) && resolveSymbol(target[id]) !== resolveSymbol(source[id])) {
```
Comment (vladima) [inline src/compiler/checker.ts]: feels like the same condition ` id !== "default" && hasProperty(target, id)` is already checked above. Can you lift it to a variable?

File: src/compiler/checker.ts [hunk 26]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
             const visitedSymbols: Symbol[] = [];
-            visit(moduleSymbol);
-            return result || moduleSymbol.exports;
+            return visit(moduleSymbol) || moduleSymbol.exports;
 
             // The ES6 spec permits export * declarations in a module to circularly reference the module itself. For example,
             // module 'a' can 'export * from "b"' and 'b' can 'export * from "a"' without error.
-            function visit(symbol: Symbol) {
+            function visit(symbol: Symbol): SymbolTable {
                 if (symbol && symbol.flags & SymbolFlags.HasExports && !contains(visitedSymbols, symbol)) {
```
Comment (vladima) [inline src/compiler/checker.ts]: can this condition be inverted to reduce nesting?

File: src/compiler/checker.ts [hunk 27]
```diff
@@ -1093,38 +1093,75 @@ namespace ts {
...
+         * Not passing `lookupTable` and `exportNode` disables this collection, and just extends the tables
+         */
+        function extendExportSymbols(target: SymbolTable, source: SymbolTable, lookupTable?: Map<ExportCollisionTracker>, exportNode?: ExportDeclaration) {
             for (const id in source) {
                 if (id !== "default" && !hasProperty(target, id)) {
                     target[id] = source[id];
+                    if (lookupTable && exportNode) {
+                        lookupTable[id] = {
+                            specifierText: getTextOfNode(exportNode.moduleSpecifier),
+                            exportsWithDuplicate: []
```
Comment (vladima) [inline src/compiler/checker.ts]: can we defer array allocation until it is actually needed?

File: src/compiler/checker.ts (hunk 6 above)
Comment (vladima) [inline src/compiler/checker.ts]: since `getTextOfNode(exportNode.moduleSpecifier)` is the same on every iteration can we get it once when it is necessary and then reuse?
