### PR TITLE
Don't use text change's `createNewFile` for existing empty file

### LINKED ISSUE #54285: Move to file fails when selecting existing with: Expected isNewFile for (only) new files
# Bug Report

### 🔎 Search Terms
- refactor
- refactoring

### 🕗 Version & Regression Information

5.1.0-dev.20230509

### Repo

1. For the code:

```ts
export const a = 1;
const b = 2;
console.log(a, b);
```

2. Select the first line and try running `move to existing file`
3. Select an existing file (in this case, an empty file)

### bug
See the following error for the request:

```
2023-05-16 17:02:06.057 [trace] <semantic> Sending request: getEditsForRefactor (119). Response expected: yes. Current queue length: 0 {
    "file": "/Users/matb/projects/san/x.ts",
    "startLine": 1,
    "startOffset": 1,
    "endLine": 1,
    "endOffset": 20,
    "action": "Move to file",
    "refactor": "Move to file",
    "interactiveRefactorArguments": {
        "targetFile": "/Users/matb/projects/san/other.ts"
    }
}
2023-05-16 17:02:06.061 [trace] <semantic> Response received: getEditsForRefactor (119). Request took 3 ms. Success: false . Message: Error processing request. Debug Failure. Expected isNewFile for (only) new files. {"isNewFile":true,"hasScriptInfo":true}
Error: Debug Failure. Expected isNewFile for (only) new files. {"isNewFile":true,"hasScriptInfo":true}
    at IpcIOSession.mapTextChangeToCodeEdit (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:181970:13)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:181962:46
    at Array.map (<anonymous>)
    at IpcIOSession.mapTextChangesToCodeEdits (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:181962:25)
    at IpcIOSession.getEditsForRefactor (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:181842:21)
    at getEditsForRefactor (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:180076:43)
    at /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:182201:69
    at IpcIOSession.executeWithRequestId (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:182193:14)
    at IpcIOSession.executeCommand (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:182201:29)
    at IpcIOSession.onMessage (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:182243:51)
    at process.<anonymous> (/Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js:183823:14)
    at process.emit (node:events:513:28)
    at process.emit (/Users/matb/projects/vscode/node_modules/source-map-support/source-map-support.js:395:21)
    at emit (node:internal/child_process:939:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #54285.

This fix updates our handling of move to file when the target file already exists, but doesn't yet have any statements (i.e. is "empty"). Previously, we'd treat this empty file as a new file for the purposes of writing text changes to it, but this caused the reported crash, and it also had the consequence of us overwriting possibly existing comments in this empty target file.

This fix, however, uncovered a problem with how new lines are handled when we insert imports into a target file in move to file. The issue was already present, but now it also occurs when the target is an empty file. The issue is that we end up with extra new lines between the import statements the refactoring inserts, as witnessed by the test baselines that changed in this PR. There is also an inconsistency between choice of quotes that shows up in the tests. Both problems seem to be caused by us using `ImportAdder` to add some of the imports in the target file, but also adding imports not using the `ImportAdder`, and it seems like ideally we'd unify that so that we're consistent with new lines and quotes.

### CODE REVIEW

File: src/harness/client.ts [hunk 1]
```diff
@@ -787,11 +790,25 @@ export class SessionClient implements LanguageService {
         return { file, line, offset, endLine, endOffset };
     }
 
-    getApplicableRefactors(fileName: string, positionOrRange: number | TextRange): ApplicableRefactorInfo[] {
-        const args = this.createFileLocationOrRangeRequestArgs(positionOrRange, fileName);
-
+    getApplicableRefactors(
```
Comment (gabritto) [inline src/harness/client.ts:793]: Fourslash server tests previously didn't work with move to file

File: src/services/types.ts [hunk 2]
```diff
@@ -652,7 +652,7 @@ export interface LanguageService {
      * arguments for any interactive action before offering it.
      */
     getApplicableRefactors(fileName: string, positionOrRange: number | TextRange, preferences: UserPreferences | undefined, triggerReason?: RefactorTriggerReason, kind?: string, includeInteractiveActions?: boolean): ApplicableRefactorInfo[];
-    getEditsForRefactor(fileName: string, formatOptions: FormatCodeSettings, positionOrRange: number | TextRange, refactorName: string, actionName: string, preferences: UserPreferences | undefined, includeInteractiveActions?: InteractiveRefactorArguments): RefactorEditInfo | undefined;
```
Comment (gabritto) [inline src/services/types.ts:655]: Drive-by fix, I thought this parameter had a misleading name, since it's not a boolean.

File: src/services/refactors/moveToFile.ts [hunk 3]
```diff
@@ -218,6 +226,9 @@ function getNewStatementsAndRemoveFromOldFile(
         if (targetFile.statements.length > 0) {
             changes.insertNodesAfter(targetFile, targetFile.statements[targetFile.statements.length - 1], body);
         }
+        else {
+            changes.insertNodesAtEndOfFile(targetFile, body, /*blankLineBetween*/ false);
+        }
         if (imports.length > 0) {
             insertImports(changes, targetFile, imports, /*blankLineBetween*/ true, preferences);
```
Comment (gabritto) [inline src/services/refactors/moveToFile.ts:233]: Regarding the extra new lines, we could also change this code to pass `blankLineBetween: false`, and the consequence would be that we'd sometimes not have an empty line between the import blocks and the moved statements in the target file, e.g.:
```ts
import { a } from "./a";
const x = 2;
```
instead of

```ts
import { a } from "./a";

const x = 2;
```

File: src/harness/client.ts [hunk 4]
```diff
@@ -1,3 +1,4 @@
+import { GetApplicableRefactorsRequestArgs, GetEditsForRefactorRequestArgs } from "../server/protocol.js";
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply src/harness/client.ts:1]: Why did a .js extension show up here?

(I would use the existing import if possible)

[the remark this answers is not in the document]
Comment (gabritto) [reply src/harness/client.ts]: Yep, I had `importModuleSpecifierEnding` set to `js` on my user settings (I think I accidentally changed the user one while trying to repro a bug in the past). Thanks for pointing that out

**Comment by gabritto** [comment]
Issue that tracks the problems I uncovered and mentioned in this PR description: #54375, #54376.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.1
