### PR TITLE
Only copy non error values in array when converting the json

### LINKED ISSUE #27432: Debug Failure. at resolveTypeReferenceDirectiveNamesWorker in openExternalProjects (tsserver)
TypeScript Version: 3.1.1

- `git clone https://github.com/vuejs/vue-cli.git`
- Open Folder in Visual Studio 2017

```
Exception on executing command {"seq":3,"command":"openExternalProjects",

....

  Debug Failure.

    Error: Debug Failure.
    at assertDefined (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:1430:24)
    at Object.assertEachDefined (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:1437:17)
    at resolveTypeReferenceDirectiveNamesWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:84449:156)
    at Object.createProgram (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:84498:35)
    at synchronizeHostData (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:114649:26)
    at Object.getProgram (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:114732:13)
    at ConfiguredProject.Project.updateGraphWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:118778:53)
    at ConfiguredProject.Project.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:118726:42)
    at ConfiguredProject.updateGraph (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:119099:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:120234:25)
    at ProjectService.openExternalProject (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:121129:38)
    at ProjectService.openExternalProjects (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:120923:26)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:121503:46)
    at C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123045:88
    at IOSession.Session.executeWithRequestId (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123036:28)
    at IOSession.Session.executeCommand (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123045:33)
    at IOSession.Session.onMessage (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:123065:35)
    at Interface.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js:124328:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:638:20)
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #27432

### CODE REVIEW

File: src/testRunner/unittests/convertCompilerOptionsFromJson.ts [hunk 1]
```diff
@@ -539,5 +555,99 @@ namespace ts {
...
+}
+`, "tsconfig.json",
+                {
+                    compilerOptions: {
+                        target: undefined,
+                        module: ModuleKind.ESNext,
+                        types: []
+                    },
+                    errors: [
+                        "tsconfig.json(5,5): error TS1136: Property assignment expected.\n",
```
Comment (weswigham) [inline src/testRunner/unittests/convertCompilerOptionsFromJson.ts]: This test seems brittle given that it now depends on the exact positions of a huge number of parse errors. Maybe it should just be a test that we don't throw/crash on it?
