### PR TITLE
Fix default property assigned prototype

### LINKED ISSUE #39167: Prototype assignment doesn't work on default-assigned constructor functions
Bug seen in actual VS customer code.

**TypeScript Version:**  3.9.2

**Search Terms:** ES5 class javascript prototype assignment constructor function

**Expected behavior:** In the example below, I expect the `test.class` properties include the one from the prototype. The behavior shouldn't depend on whether or not `test.class` was default-assigned or not.

**Actual behavior:** The prototype assignment doesn't seem to work when default assignment is used. @sandersn thinks this is a bug but isn't surprised.

**Related Issues:** #39166 from same user code

**Code**
```ts
var test = {};

test.class = test.class || function (name) {

    function getName() {
        return name;
    }

    this.name = getName();
}

test.class.prototype = {
    add: function (i) {
    }
}; 

var t = new test.class("test");
t.name
t.add // EXPECTED: Binds to `add` from the prototype, ACTUAL: doesn't


//
// Same pattern works with a straightforward assignment:
//

var test2 = {};

// Removed `test.class ||` 
test2.class = function (name) {

    function getName() {
        return name;
    }

    this.name = getName();
}

test2.class.prototype = {
    add: function (i) {
    }
}; 

var t2 = new test2.class("test");
t2.name
t2.add // ACTUAL: `add` bound correctly

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?useJavaScript=true#code/G4QwTgBALgpgzlCBeCBvAvgbgFDdggOgGMAbEOOZaeKYsiiAH0YgDMBXAOyKgEsB7ThAAUnEAFsYASjS4I8tlx4ChAcxhQAchJjCZqbAqMQwG9mCFjJOI+jkKoAC15wCVmFXVadenHbw0dOSuAA5g-FARAJ4hHigGRiAAJkkAXIrcfIIivPqGCnZYELigkIgonDAA7tSEpMHCAET4UI1SOLTueATJSRAA9P0QAKIAGgAKwwDCACrDACLpAEK8nEmUkRAABr1bbOHi0I4eYRHRsQA0EACCswCq1wAy6Un88JwA5FC42IO-QwBlHQQEIgKCwCwQKr8MAAa0oVV4TggIAgCDAIF4qkcUFYMKq4D6wSxnEknCgqX+JXAtSgACYqBgcP8IAAlGDifjAGB9LYtIIMZh7AIIOkCygoDiZFQidx5fLyKXKbJebSSPSyYwKUxQcyWHQ2Ar2eROFxuYEoVU+drYfwtMX1CgEU6RKAxOKahS9dJKrJCYS5T3yQqYYrYUrQBkVaq0h30OBNFptDpirr0nopAZDW4zB7Pba7CAAI34XD6RBhph4JCi2CAA)

### PR DESCRIPTION
**Pull request by sandersn**
The check in getAssignedClassSymbol forgot to allow for default-property assignment declarations, in part because it wasn't using a utility function to do so.

Fixes #39167

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -24828,7 +24829,7 @@ namespace ts {
                     const exprType = checkJsxAttribute(attributeDecl, checkMode);
                     objectFlags |= getObjectFlags(exprType) & ObjectFlags.PropagatingFlags;
 
-                    const attributeSymbol = createSymbol(SymbolFlags.Property | SymbolFlags.Transient | member.flags, member.escapedName);
```
Comment (sandersn) [inline src/compiler/checker.ts:24831]: this is a drive-by fix; createSymbol always adds `Transient`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -28076,15 +28077,59 @@ namespace ts {
         }
 
         function getAssignedClassSymbol(decl: Declaration): Symbol | undefined {
-            const assignmentSymbol = decl && decl.parent &&
-                (isFunctionDeclaration(decl) && getSymbolOfNode(decl) ||
-                 isBinaryExpression(decl.parent) && getSymbolOfNode(decl.parent.left) ||
-                 isVariableDeclaration(decl.parent) && getSymbolOfNode(decl.parent));
-            const prototype = assignmentSymbol && assignmentSymbol.exports && assignmentSymbol.exports.get("prototype" as __String);
-            const init = prototype && prototype.valueDeclaration && getAssignedJSPrototype(prototype.valueDeclaration);
+            const assignmentSymbol = decl && getSymbolOfExpando(decl, /*allowDeclaration*/ true);
```
Comment (sandersn) [inline src/compiler/checker.ts:28080]: this is the actual fix

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -28076,15 +28077,59 @@ namespace ts {
...
-                 isVariableDeclaration(decl.parent) && getSymbolOfNode(decl.parent));
-            const prototype = assignmentSymbol && assignmentSymbol.exports && assignmentSymbol.exports.get("prototype" as __String);
-            const init = prototype && prototype.valueDeclaration && getAssignedJSPrototype(prototype.valueDeclaration);
+            const assignmentSymbol = decl && getSymbolOfExpando(decl, /*allowDeclaration*/ true);
+            const prototype = assignmentSymbol?.exports?.get("prototype" as __String);
+            const init = prototype?.valueDeclaration && getAssignedJSPrototype(prototype.valueDeclaration);
             return init ? getSymbolOfNode(init) : undefined;
         }
 
+        function getSymbolOfExpando(node: Node, allowDeclaration?: boolean): Symbol | undefined {
```
Comment (sandersn) [inline src/compiler/checker.ts:28086]: changes from the move:

1. Return a Symbol instead of a Node, since all callers immediately do that anyway. This is why I moved it into the checker.
2. Add a parameter `allowDeclaration` that allows `node` to be *either* the expando or its declaration. The parameter disables the checks that assert that `node` is the `expando` initialiser.
3. Add a FunctionDeclaration case when `allowDeclaration` is true.

**Review by andrewbranch — APPROVED** [review]
