### PR TITLE
Fast path for negative case when relating to unions of primtives

### LINKED ISSUE #53191: Relating large unions of literal types performs poorly
### 🕗 Version & Regression Information

All versions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230309#code/C4TwDgpgBAIglgczsAzlAvFA5ABi1AH2wEZ8isAmM7AZmqwBZ6BWegNnoHZ6AOegTiwBuAFChIUACr8AGnJkYoAA34ASAN7wkqAL4atyFHs2JDxg7qWjx0SfLmKlGgKIAPAMYAbAK4ATCAA8FigANNh4AHzmprr6MUZx2gkmSTpWIiKeEMBQrgBcUG5efoF29mHS9hGKWDx1dcIiQA)

### 💻 Code

```ts
type Digits = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
type T9XXXX = `9${Digits}${Digits}${Digits}${Digits}`;
type TXXXXX = `${Exclude<Digits, '0'>}${Digits}${Digits}${Digits}${Digits}`;

let x: Exclude<TXXXXX, T9XXXX> = '88888';
```

### 🙁 Actual behavior

The example above takes ~45s to compile on a reasonably fast machine. The underlying issue is that as we relate large unions of primitive types, we have a fast path for matches, but not for mismatches. Because the majority of the constituents of `TXXXXX` are not present in `T9XXXX`, we spend a lot of time in the slow path that attempts to find matches by iterating through all constituents.

### 🙂 Expected behavior

We can do much better by implementing a fast path for mismatches.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements a fast path for the negative case of relating a literal type to a union of primtive types. This reduces the check time of the example in #53191 from ~45s to ~0.4s.

Fixes #53191.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
RE: DT above, the results are still compared against nightly, so some of those are preexisting breaks caused elsewhere today and can be ignored. I think @gabritto is looking switching that to compare against main.

(In particular, DOM was updated which is most of the breaks, plus a dts emit change I need to go update in ramda.)

**Comment by Andarist** [comment]
This likely supersedes https://github.com/microsoft/TypeScript/pull/50640 and thus fixes https://github.com/microsoft/TypeScript/issues/47511 and https://github.com/microsoft/TypeScript/issues/47481

I tested the case from #47481 and the check time went from 12s to 0.5s on my machine

**Comment by gabritto** [comment]
@typescript-bot run DT

**Comment by ahejlsberg** [comment]
> Should we add the test cases from https://github.com/microsoft/TypeScript/issues/47511, https://github.com/microsoft/TypeScript/issues/47481, and https://github.com/microsoft/TypeScript/issues/53191?

All that's interesting about those tests is their performance, and we don't measure that. So don't think so.

**Comment by jakebailey** [comment]
If they "fail", then they'll take long enough to take out the runner, or at least be suspiciously slow. Maybe that's enough, but I don't feel strongly.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20837,6 +20833,21 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 if (containsType(targetTypes, source)) {
                     return Ternary.True;
                 }
+                if (getObjectFlags(target) & ObjectFlags.PrimitiveUnion && !(source.flags & TypeFlags.EnumLiteral) && (
+                    source.flags & (TypeFlags.StringLiteral | TypeFlags.BooleanLiteral | TypeFlags.BigIntLiteral) ||
```
Comment (weswigham) [inline src/compiler/checker.ts:20837]: This can be expanded to cover `unique symbol` literals, too.

**Review by weswigham — APPROVED** [review]
IMO, we should add the test cases from the other issues, since, while we don't collect test perf metrics right now, we've talked about starting to collect them, once we have some more perf CI machine bandwidth, since the metrics are actually collected already. You can already `require("./.parallelperf.json")` to get an object with the timing data from your last run, so you can already anecdotally use the data today.

**Comment by Andarist** [comment]
The regression reported [here](https://github.com/microsoft/TypeScript/issues/53359#issuecomment-1475390601) can be traced back to this PR. The minimal~ repro case for it is this:
```ts
enum AutomationMode {
  NONE = "",
  TIME = "time",
  SYSTEM = "system",
  LOCATION = "location",
}

interface ThemePreset {
  id: string;
}

interface Automation {
  mode: AutomationMode;
}

interface UserSettings {
  presets: ThemePreset[];
  automation: Automation;
}

interface ExtensionData {
  settings: UserSettings;
}

export function getMockData(): ExtensionData {
  return {
    settings: {
      presets: [],
      automation: {
        mode: "",
      },
    } as UserSettings,
  }
}
```

[TS playground](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230320#code/KYOwrgtgBAgmAuB7CBDeBLRICyiAmwUA3gFBRQByA8hQKJQC8UARMwDRlQAqAktvU2YYIwdpwDKATXFda2RiwDOAT0XxgEMeQAyVAMIxeNBcwA2iAMZpMIMQF8SJdCHUAnAGYoLhLgAsNwAAKrsCKwPDEnOh4AFxQaq7OAOYA3CQOTi7AHl6EcEioGFiR5BD4wHH5yNZYuARpGc5unt5QAKphruLhGCBJiiVQAA4hYfCKcX4BwaHhANoAumnkKAjVRSCVa4U2DY5N2S2EtAAe6iCKNgAiaCiDY739cR3Z3fCPinskwCdDiK4RdxgEAWDZQJLhXAWADWN3gKAAFABKOKnc6XLBwu6kcgheBgVwgQbkB7JCbE8jDUbhcmLDiUymrAo1TYUhllAhxVj0hlQOw88h2KAoAYvLo9Mk8hwOIA)

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16719,12 +16715,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
                     result = getIntersectionType(typeSet, aliasSymbol, aliasTypeArguments);
                 }
-                else if (eachIsUnionContaining(typeSet, TypeFlags.Undefined)) {
+                else if (every(typeSet, t => !!(t.flags & TypeFlags.Union && (t as UnionType).types[0].flags & TypeFlags.Undefined))) {
                     const containedUndefinedType = some(typeSet, containsMissingType) ? missingType : undefinedType;
                     removeFromEach(typeSet, TypeFlags.Undefined);
                     result = getUnionType([getIntersectionType(typeSet), containedUndefinedType], UnionReduction.Literal, aliasSymbol, aliasTypeArguments);
                 }
-                else if (eachIsUnionContaining(typeSet, TypeFlags.Null)) {
+                else if (every(typeSet, t => !!(t.flags & TypeFlags.Union && ((t as UnionType).types[0].flags & TypeFlags.Null || (t as UnionType).types[1].flags & TypeFlags.Null)))) {
```
Comment (SlurpTheo) [inline src/compiler/checker.ts:16723]: (`lines:-5+0`)

Why does this **only** need to check?
 - `types[0]` for `TypeFlags.Undefined`
 - `types[0] | types[1]` for `TypeFlags.Null`

Is there some rule/convention that `null` is first in `UnionType#types` if it's part of the union, _unless_ `undefined` is in the union (which is _really_ always first if it is part of the union)?

Comment (Andarist) [reply src/compiler/checker.ts:16723]: Yes, union types are sorted like this internally - so if a union contains `undefined` it has to be the first element etc.
