### PR TITLE
Strict optional properties

### LINKED ISSUE #13195: Distinguish missing and undefined
**TypeScript Version:**  2.1.4

**Code**

Current, with `--strictNullChecks` on, the typescript compiler seems to treat

```
interface Foo1 {
  bar?: string;
}
```
and
```
interface Foo2 {
  bar?: string | undefined;
}
```
as being the same type - in that `let foo: Foo1 = {bar: undefined};` is legal.  However, this does not seem to be the original intent of the language - while some people have used `?` as a shortcut for `| undefined` (e.g. https://github.com/Microsoft/TypeScript/issues/12793#issuecomment-266095767), it seems that the intent of the operator was to signify that the property either did not appear, or appeared and is of the specified type (as alluded in https://github.com/Microsoft/TypeScript/issues/12793#issuecomment-266092763) - which might not include `undefined` - and in particular it would let us write types that either have a property that, if enumerable is not undefined, or is not present on the object.

In other places it might make sense for `?` to keep serving as a shorthand for `| undefined`, e.g. for function parameters.  (or maybe for consistency it would make sense to stick with it meaning "always pass something undefined if you pass anything"? not sure what's best there.  Happy to discuss.)

**Expected behavior:**

```
interface Foo1 {
  bar?: string;
}
function baz(bar: string) {};

let foo: Foo1 = {bar: undefined}; // type error: string? is incompatible with undefined

if (foo.hasOwnProperty("bar")) {
  baz(foo.bar); // control flow analysis should figure out foo must have a bar attribute here that's not undefined
}
if ("bar" in foo) {
  baz(foo.bar); // control flow analysis should figure out foo must have a bar attribute here that's not undefined
}
```

**Actual behavior:**

```
interface Foo1 {
  bar?: string;
}
function baz(bar: string) {};

let foo: Foo1 = {bar: undefined}; // compiler is happy

if (foo.hasOwnProperty("bar")) {
  baz(foo.bar); /*  error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.  Type 'undefined' is not assignable to type 'string'*/

}
if ("bar" in foo) {
  baz(foo.bar); /* error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.  Type 'undefined' is not assignable to type 'string'*/
}
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we introduce a new strict mode, `--strictOptionalProperties`, in which optional properties declared without an explicit `undefined` in their type do not permit assigning a possibly `undefined` value. This makes it possible to ensure that optional properties are never `undefined` when they're present on an object, and that `undefined` values read from optional properties unequivocally indicate that the properties are not present. The new compiler switch is in the `--strict` family of switches and this PR is therefore a breaking change for code compiled in `--strict` mode (unless, of course, the switch is explicitly set to `false`).

```ts
// Compile in --strictOptionalProperties mode
function f1(obj: { a?: string, b?: string | undefined }) {
    let a = obj.a;  // string | undefined
    let b = obj.b;  // string | undefined
    obj.a = 'hello';
    obj.b = 'hello';
    obj.a = undefined;  // Error, 'undefined' not assignable to 'string'
    obj.b = undefined;
}
```

In `--strictOptionalProperties` mode, assigning `undefined` to `obj.a` is considered an error because the declared type of `a` doesn't explicitly include `undefined`. However, when reading `obj.a` the type is still `string | undefined` to account for the possibility that the object doesn't have an `a` property.

The `b` property above explicitly includes `undefined` in its type and is thus unaffected by `--strictOptionalProperties`.

In `--strictOptionalProperties` mode, for an optional property declared without `undefined` in its type, control flow analysis accepts the `in` operator and the `hasOwnProperties` method as proof that the property is present, and consequently excludes `undefined` from the property value.

```ts
// Compile in --strictOptionalProperties mode
function f2(obj: { a?: string }) {
    obj = obj;
    obj.a = obj.a;  // Error,  'string | undefined' not assignable to 'string'
    if ('a' in obj) {
        obj.a = obj.a;  // Ok
    }
    if (obj.hasOwnProperty('a')) {
        obj.a = obj.a;  // Ok
    }
}
```

Note above that `obj.a` is not assignable to itself unless it is guarded by a check that the property is present. While initially surprising, this makes sense because, if the property is not present, it would become present with the value `undefined` following the assignment.

In `--strictOptionalProperties` mode, the `Partial<T>` utility type produces strictly checked optional properties as expected. For example:

```ts
// Compile in --strictOptionalProperties mode
function f3(obj: Partial<{ a: string, b: string | undefined }>) {
    let a = obj.a;  // string | undefined
    let b = obj.b;  // string | undefined
    obj.a = 'hello';
    obj.b = 'hello';
    obj.a = undefined;  // Error, 'undefined' not assignable to 'string'
    obj.b = undefined;
}
```

In `--strictOptionalProperties` mode, optional elements in tuple types are strictly checked when they don't explicitly include `undefined` in their type. For example:

```ts
// Compile in --strictOptionalProperties mode
function f4(t: [string?]) {
    let x = t[0];  // string | undefined
    t[0] = 'hello';
    t[0] = undefined;  // Error, 'undefined' not assignable to 'string'
}
```

Fixes #13195.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by tom-sherman** [comment]
I'm getting unexpected type information when playing around with [this example](https://github.com/microsoft/TypeScript/issues/13195#issuecomment-373178677) from the linked issue. Does this require further work in the language server to rectify?

image

```ts
type Props = {
  foo: string;
  bar: string
}

type InputProps = {
  foo?: string;
  bar: string;
}

const defaultProps = { foo: 'foo' };
// Hover over foo here
const inputProps: InputProps = { foo: undefined, bar: 'bar' };
```

**Comment by Andarist** [comment]
I love the change and couldn't be happier about it ❤️ 

I have a minor question/concern though: what about types coming from external dependencies? narrowing down based on the `in` operator or `hasOwnProperty` might not be sound in that case, right? Since the external dependency could be compiled without this strict flag.

**Comment by ahejlsberg** [comment]
@tom-sherman In the new `--strictOptionalProperties` mode, for optional properties we have two possible types we could display: The type you get when reading the property, or the type you're permitted to write to the property. You can observe the difference by hovering over each `foo` in the the statement `inputProps.foo = inputProps.foo ?? ''`. In your particular example I agree it makes more sense to display the type you're permitted to write.

**Comment by m-rutter** [comment]
> I love the change and couldn't be happier about it heart
> 
> I have a minor question/concern though: what about types coming from external dependencies? narrowing down based on the `in` operator or `hasOwnProperty` might not be sound in that case, right? Since the external dependency could be compiled without this strict flag.

Also think about dependently typed. I don't think anyone is going to individually verify that every js implementation will obey the new strict version of `?:`? Maybe it might make sense to do a blanket `| undefined` codemod to definitely typed?

**Comment by OliverJAsh** [comment]
@ahejlsberg I expected [this example](https://github.com/microsoft/TypeScript/issues/13195#issuecomment-775930240) would now compile but it doesn't seem to unfortunately. Do you know why that is?

```ts
type Dict<T> = { [key: string]: T };
interface F extends Dict<string> {
    // Property 'foo' of type 'string | undefined' is not assignable to string index type 'string'.
    foo?: string;
}
```

**Comment by ahejlsberg** [comment]
@OliverJAsh I see it was already discussed [here](https://github.com/microsoft/TypeScript/pull/41921#issuecomment-778100579), and I'm not sure the issue particularly relates to `--strictOptionalProperties`. I will readily agree it's odd that `{ foo?: string }` is assignable to `Dict<string>` (because of #41921) but that it is an error do derive from `Dict<string>` and introduce a `{ foo?: string }` property. I think it should be allowed, but I'm not sure if this PR is the right place to correct it.

@andrewbranch Opinions on this?

**Comment by andrewbranch** [comment]
I still think @OliverJAsh’s example is a _little_ suspicious with `--strictNullChecks` but without `--noUncheckedIndexedAccess`. The inheritance I think is immaterial; what we’re asking is, under what circumstances does it make sense to allow

```ts
interface  Foo {
  [key: string]: string;
  foo?: string;
}
```

With _just_ `--strictNullChecks`, the type of the property signature of `foo` _is_ `string | undefined`, but reading an arbitrary string key will give you a `string`. Everyone knows that you’ll actually often get an `undefined` value at runtime (in absence of a Proxy or something), but our stance has always been one of _consistently_ ignoring the possibility of `undefined`—your other properties must be assignable to the index signature type, not the index signature type or `undefined`. That way, when you read an arbitrary key and get the result `string`, at least we don’t _know_ of any property names that would give you something different. This is a pretty weak defense in my opinion, but it’s the historical status quo. I think it wouldn’t be totally unreasonable to change our stance and allow optional properties alongside non-nullable index signatures. Then, when you read an arbitrary property and we give you a `string`, well, it’s wrong, but the undefined-ness of `foo?: string` doesn’t make it _more_ wrong than the undefined-ness of the infinite number of missing properties.

If we add `--noUncheckedIndexedAccess`, it starts to make more sense. Now, reading an arbitrary key of `Foo` will give you `string | undefined`, so the read type of the index signature and the read type of `foo?: string` agree. Having thought about it for a while now, I have no reservations about allowing this.

If we _also_ add `--strictOptionalProperties`, it feels like all the remaining holes can be plugged:

```ts
interface Foo1 {
  [key: string]: string;
  foo?: string; // ok, because like the index signature, this means if the property is present, its type is 'string'
}

interface Foo2 {
  [key: string]: string;
  foo?: string | undefined; // error, because unlike the index signature, this property may be set to 'undefined'
}

declare let dict: { [key: string]: string };
declare let foo1: { foo?: string };
declare let foo2: { foo?: string | undefined };

dict = foo1; // ok, because `foo` is 'string' if present
dict = foo2; // error, because it may introduce a present-but-undefined property
```

This gets to the essence of #41921—when you’re assigning an object with optional `string` properties to an object with a `string` index signature, we wanted to give you the benefit of the doubt that what you _mean_ is that those properties are either `string`s or _not present_. We had no way of enforcing that, and needed to reduce the breakiness of fixing #41418, so we chose to allow the unsoundness, given the rest of the unsoundness around index signatures. But if we had had a way to distinguish undefined and missing properties from the beginning, I think it would have worked the way I wrote it above. Unfortunately, the examples in that last code block really depend on _both_ `--noUncheckedIndexedAccess` and `--strictOptionalProperties` being set to make sense, and I don’t know if it’s worth it in practice to treat that unique combination specially. But conceptually, it really does feel like they complement each other nicely and finally make sense out of the index signature story.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
`Object.hasOwn` has reached stage 3; maybe worth considering for a follow-up.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Review by weswigham — APPROVED** [review]
This looks good - I am curious what our new behavior for this:
```ts
const x = [1,,,] as const;
function f<T extends typeof x>(p: T) {
    if ("1" in x) {
        const y1 = x[1];
    }
    else {
        const y2 = x[1];
    }
    if ("1" in p) {
        const z1 = p[1];
    }
    else {
        const z2 = p[1];
    }
}
```
is, however (since we have new code for `in` narrowing `missing` and new code adding `missing` into tuples). Maybe it warrants addition to the test suite?

**Comment by weswigham** [comment]
Oh, declaration emit for the tuples with `missing` members would also be nice to have documented in a test, eg, `export const arr = [,,42] as const;` and just `export const arr = [,,42];`. Specifically with those, it might also be worth adding incremental-mode tests to document our behavior there, since the type isn't going to roundtrip correctly under this new flag (since the declaration file can't (?) serialize the missing type as such).

Something like
```ts
// @filename: source.ts
export const a = [,,42];
export const b = [,,42] as const;
// @filename: usage.ts
import type {a, b} from "./source";
const a2: typeof a = [,,42];
const b2: typeof b = [,,42];
```
but run under the incremental harness (so `usage` is checked against `source`'s generated declaration file on second run) I think should highlight the current shortcoming.

**Comment by ahejlsberg** [comment]
> I am curious what our new behavior for this

Omitted elements in tuple types are equivalent to writing `never?`. In other words, an element that has no possible values (and therefore is impossible to assign to) and therefore always reads back as `undefined` (i.e. the `missingType` that represents a missing property). Each of the variable declarations in your example will have type `undefined`. We don't narrow to `never` in the true branches because we never narrow just `null`, `undefined` or `void` (we never have).

> ... since the type isn't going to roundtrip correctly under this new flag

The types roundtrip just fine and we already have many examples of them in the existing tests. Just search for `never?` in the baseline changes to see examples.

**Comment by weswigham** [comment]
> The types roundtrip just fine and we already have many examples of them in the existing tests. Just search for never? in the baseline changes to see examples.

I don't see any declaration emit baselines containing inferred tuple types that we serialized - they're all explicitly annotated? (Unless you mean the type baselines, which don't _quite_ go through the same pipeline, so I'd prefer to see some explicit declaration emit tests, myself)

**Comment by ahejlsberg** [comment]
Summary of test runs:

* Definitely Typed looks to be clean (very few of the DT tests are `--strict` mode).
* Community code tests have new errors in several projects. Particularly notable are a number of new errors in `office-ui-fabric` and `pyright`. Easy fix is to include a `"strictOptionalProperties": false"` entry in their `tsconfig.json` files.
* Real world code tests are clean (I guess none of then are `--strict` mode).

**Comment by nelson6e65** [comment]
What version of TS will include this feature?

**Comment by dwelle** [comment]
image

**Comment by simeyla** [comment]
Just in case anyone was wondering, it is possible to use `undefined!` to bypass this check on a case by case basis if needed. (tested in playground 4.4 beta)

```
type Cat = {
    meow?: 'loud' | 'quiet'
}

const cat: Cat = {
     meow: undefined!    // without the '!' this would be an error in TS 4.4
};
```

**Comment by Kingwl** [comment]
@simeyla 

>to bypass this check

It's not type safe. `undefined!` is never.
We may just turn off thr option for a while.

**Comment by simeyla** [comment]
Excited about this option and glad to see it officially in TS 4.4 :-)

Just a suggestion for docs, that you may want to remind people they can use the [delete](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) operator to remove a property (since [exactOptionalPropertyTypes ](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#exact-optional-property-types)of course means you can't set it undefined). I feel like a lot of people probably don't know about this operator - or need reminding about it if they're accustomed to setting things undefined. I think it would be important to mention in any documentation on this new flag.

```
interface Person {
    name: string,
    age?: number;
}

const person: Person = {
    name: "Daniel",
    age: 27
};

p.age = undefined;    // Error! undefined isn't a number
```
Instead, to clear the property with the `exactOptionalPropertyTypes` flag enabled use:
```
delete person.age;
```

---

**Caveat:** At this point in time [this gives an error (playground link)](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.4.0-beta#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyxyIcAthAFzIZhSgDmANESXIxAPw0gCu5AEbQA3AQC+BAghx1kAB0w4a6KNlwBefG2JlKNAEQAROCGAQANgdYlkHasgBMAdgliCAE0sRICpSAA6exFiAHpQ5AAVAAsULEUoUw9kLBg7ZAByLwsfCAyUhLgwLChkcj45YQKwYBw4CwCpAiA)  which I'm assuming is a temporary issue?


**Also:** Despite the URL parameter in this playground link, you must manually enable `exactOptionalPropertyTypes` under tsoptions to turn iton (does that mean I found two bugs)

**Comment by DanielRosenwasser** [comment]
@simeyla maybe that's a suggestion worth bringing into @sandersn's change at #45032. When directly assigning `undefined` to an existing property, we can give some diagnostic that suggests using `delete`.

On the other hand, I don't know how much we recommend that pattern in the first place, and we might be more inclined to tell users to add `undefined` to the property type.

**Comment by sandersn** [comment]
@simeyla Actually, can you open a second bug? #45032 covers a slightly different error (values with properties that are undefined) and is pretty big already. Just copy your example into a new bug -- it captures the request precisely. At that point we can decide whether to handle it in the same codefix or not.

**Comment by simeyla** [comment]
@DanielRosenwasser @sanders
1) Looks like the issue is already taken care of in the nightly build. After I posted this I actually found a test case for exactly this that presumably must have been failing and was since fixed.

2) I've created an issue https://github.com/microsoft/TypeScript/issues/45058

3) I realize that this isn't under `--strict` but it's literally in the URL parameters for the above playground link - and isn't being respected when I reload the page.

    eg. https://www.typescriptlang.org/play?ts=4.4.0-dev.20210715& **exactOptionalPropertyTypes=true** #code

**Comment by sandersn** [comment]
@simeyla can you file another bug about the playground bug and assign it to @orta?

**Comment by craigphicks** [comment]
`optional` and `undefined` are separate, orthogonal dimensions.   If, in the course of internal Typescript type processing they get squished into a single dimension (e.g., unconditionally assigning an `undefined` to every `optional`'s type as a union member), then later on in processing it is impossible to get back the original information (unless it stored in a separate channel, e.g., referring back to the original node declaration.).

- `optional` -> `optional`+ `undefined`
- `optional`+`undefined` -> `optional`+ `undefined`

When interacting with the API using `getTypeOfSymbolAtLocation` or `getDeclaredTypeOfSymbol`, will it still ALWAYS be possible to determine, independently of the compiler, whether a particular assignment to a type is legal, or not?   Without `exactOptionsPropertyTypes`, the presence of `undefined` as a union member meant that `undefined` was a legal assignment.

With `exactOptionsPropertyTypes`, so far as my testing goes, it appears the presence of `undefined` as a union member from a type obtained via `getTypeOfSymbolAtLocation` or `getDeclaredTypeOfSymbol` APIs no longer ensures that the compiler will accept `undefined`.  It seems like the compiler might be using different logic not available through the API.

I gave an example at the bottom of #45764 in a section "Tangent topic yet critical - Type API may have changed - is it still possible to determine behavior from exposed Type API ?".  

How about a different strategy of never adding in redundant `undefined` in the first place?  That would be much cleaner.  The documentation even implies that is what is being done:

> In TypeScript 4.4, the new flag --exactOptionalPropertyTypes specifies that optional property types should be interpreted exactly as written, meaning that | undefined is not added to the type:

**Comment by MartinJohns** [comment]
> then `fieldName?: TypeName && not undefined` might be a better option?

TypeScript has no way to represent a "not"-type. This would require #29317.

**Comment by Offirmo** [comment]
Hi, I'm coming here from the docs and I'm not sure about the value of this property. It seems to be "true | false | undefined" but it's not stated clearly in the doc: https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes

Also which is the strictest option? Is it "true" ?

**Comment by Andarist** [comment]
It defaults to false and if u want this strict behavior then u can opt into it using true

**Comment by Kay-Yuan** [comment]
Hi, I tried `exactOptionalPropertyTypes` flag on my Angular project. It works fine in my .ts file. The optional property type is `type-example` only without `undefined`. But the .html file still showed the optional property type as `type-example | undefined`. Do you guys have any idea about this? Any feedback would be appreciated.

**Comment by MartinJohns** [comment]
@Kay-Yuan That's an issue with Angular and should be addressed there. TypeScript has nothing to do with .html files.

**Comment by Kay-Yuan** [comment]
> @Kay-Yuan That's an issue with Angular and should be addressed there. TypeScript has nothing to do with .html files.

Thanks a lot! Just not sure which part of the error belong. I will comment this to Angular. Cheers.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19252,7 +19238,7 @@ namespace ts {
                     if (!(targetProp.flags & SymbolFlags.Prototype) && (!numericNamesOnly || isNumericLiteralName(name) || name === "length")) {
                         const sourceProp = getPropertyOfType(source, name);
                         if (sourceProp && sourceProp !== targetProp) {
-                            const related = propertyRelatedTo(source, target, sourceProp, targetProp, getTypeOfSymbol, reportErrors, intersectionState, relation === comparableRelation);
+                            const related = propertyRelatedTo(source, target, sourceProp, targetProp, getNonMissingTypeOfSymbol, reportErrors, intersectionState, relation === comparableRelation);
```
Comment (HansBrende) [inline src/compiler/checker.ts:19241]: @ahejlsberg question: did you miss a spot on line 19919 in `compareProperties`, i.e., should 
```typescript
compareTypes(getTypeOfSymbol(sourceProp), getTypeOfSymbol(targetProp));
```
have been replaced by 

```typescript
compareTypes(getNonMissingTypeOfSymbol(sourceProp), getNonMissingTypeOfSymbol(targetProp));
```
, thus preventing `{a?: string}` from comparing identical to `{a?: string | undefined}`?

Or was that intentional?

Comment (jakebailey) [reply src/compiler/checker.ts:19241]: This is a 5 year old PR; I would suggest commenting on an issue or filing a new one instead.

Comment (HansBrende) [reply src/compiler/checker.ts:19241]: @jakebailey thanks! I did comment on #61547 but since it was closed as "not a defect", I was hoping to understand very simply whether this behavior, when it was implemented, was intentional or non-intentional (to deduce whether the close reason was correct). If the behavior was _not_ intentional (which is my guess, since it seems very strange for an "identical" comparison to be _less strict_ than an assignment comparison), then that would provide evidence that the issue should be re-opened with this simple fix in mind. I could open a new issue but that seems strange when one already exists so it would effectively be a duplicate. Hope my reasoning makes sense here?
