### PR TITLE
fix(51245): Class with parameter decorator in arrow function causes "convert to default export" refactoring failure

### LINKED ISSUE #51245: Class with parameter decorator in arrow function causes "convert to default export" refactoring failure
```ts
[|export|] const f = () => {
    return class InnerClass {
        constructor(@Inject() param: any) { }
    }
};

function Inject(...args: any[]): any {}
```

Request `Convert named export to default export`

<details>

<summary>Stack Trace</summary>

```
Response received: getEditsForRefactor (8292). Request took 185 ms. Success: false . Message: Error processing request. Cannot read properties of undefined (reading 'kind')
TypeError: Cannot read properties of undefined (reading 'kind')
    at Object.isExpressionNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:16361:22)
    at nodeIsInDecoratorContext ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:149858:23)
    at isEndOfDecoratorContextOnSameLine ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:149854:17)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150046:109
    at Object.every ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:309:22)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150046:67
    at processPair ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150911:29)
    at processRange ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150900:29)
    at consumeTokenAndAdvanceScanner ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150819:38)
    at processChildNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150724:29)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150659:21
    at visitNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31214:24)
    at forEachChildInPropertyDeclaration ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31301:17)
    at Object.forEachChild ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31997:47)
    at processNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150658:20)
    at processChildNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150730:21)
    at processChildNodes ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150785:48)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150661:21
    at visitNodes ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31219:24)
    at forEachChildInClassDeclarationOrExpression ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31940:13)
    at Object.forEachChild ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31997:47)
    at processNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150658:20)
    at processChildNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150730:21)
    at processChildNodes ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150785:48)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150661:21
    at visitNodes ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31219:24)
    at forEachChildInBlock ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31930:16)
    at Object.forEachChild ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31997:47)
    at processNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150658:20)
    at processChildNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150730:21)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150659:21
    at visitNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31214:24)
    at forEachChildInArrowFunction ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31424:17)
    at Object.forEachChild ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31997:47)
    at processNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150658:20)
    at processChildNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150730:21)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150659:21
    at visitNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31214:24)
    at forEachChildInExportAssignment ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31749:17)
    at Object.forEachChild ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:31997:47)
    at processNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150658:20)
    at formatSpanWorker ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150437:17)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150399:140
    at Object.getFormattingScanner ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:149019:23)
    at Object.formatNodeGivenIndentation ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:150399:31)
    at getFormattedTextOfNode ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152872:45)
    at format ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152843:52)
    at computeNewText ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152846:23)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152810:39
    at Object.mapDefined ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:621:30)
    at [USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152808:42
    at Object.mapDefined ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:621:30)
    at Object.getTextChangesFromChanges ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152794:27)
    at ChangeTracker.getChanges ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152733:45)
    at ChangeTracker.with ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:152153:32)
    at Object.getRefactorEditsToConvertBetweenNamedAndDefaultExports [as getEditsForAction] ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:162781:62)
    at Object.getEditsForRefactor ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:153461:41)
    at Object.getEditsForRefactor ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:169759:32)
    at Session.getEditsForRefactor ([USER_DIR]/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-4.9.20221014/node_modules/typescript/lib/tsserver.js:181467:59)
```

</details>

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51245

### CODE REVIEW

File: src/services/formatting/rules.ts [hunk 1]
```diff
@@ -725,17 +725,7 @@ namespace ts.formatting {
...
-            nodeIsInDecoratorContext(context.currentTokenParent) &&
-            !nodeIsInDecoratorContext(context.nextTokenParent);
-    }
-
-    function nodeIsInDecoratorContext(node: Node): boolean {
-        while (isExpressionNode(node)) {
-            node = node.parent;
-        }
-        return node.kind === SyntaxKind.Decorator;
+        return context.TokensAreOnSameLine() && hasDecorators(context.contextNode) && isDecorator(context.currentTokenParent);
```
Comment (rbuckton) [inline src/services/formatting/rules.ts:728]: Wouldn't this falsely identify the following as the end of a decorator context:
```ts
class C {
  constructor(@Foo @Bar param: any) {}
           //  ^^^
}
```

If for some reason the current token is `Foo`, its parent will be a decorator, but the next token is *also* in a decorator context.

File: src/services/formatting/rules.ts [hunk 2]
```diff
@@ -725,17 +725,7 @@ namespace ts.formatting {
...
 
     function isEndOfDecoratorContextOnSameLine(context: FormattingContext): boolean {
-        return context.TokensAreOnSameLine() &&
-            hasDecorators(context.contextNode) &&
-            nodeIsInDecoratorContext(context.currentTokenParent) &&
-            !nodeIsInDecoratorContext(context.nextTokenParent);
-    }
-
-    function nodeIsInDecoratorContext(node: Node): boolean {
-        while (isExpressionNode(node)) {
```
Comment (rbuckton) [inline src/services/formatting/rules.ts:735]: `isExpressionNode` checks `.parent` in some cases to determine whether the node is, in fact, part of an expression. However, in the linked issue this is being used in tandem with `ChangeTracker`, which often means new synthetic nodes are added to the tree that don't have a valid `.parent`. Since TypeScript's own `Node` type lies about `parent (it's not always set despite not having an `| undefined` in its definition), functions that depend on `.parent` aren't always reliable except when working with original parse tree nodes.

One potential fix is to leave this in and use `while (node && isExpressionNode(node))` to guard against a missing parent. In addition, it might be better to use the more general `isExpression` test instead of `isExpressionNode`, since `isExpression` doesn't check `.parent` (at the cost of potentially misattributing `Identifier`, `this`, `true`, `false`, or `null` in a non-expression position as an expression). Given how this function is used, `isExpression` (along with the `node && ...` guard) is probably fine.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/services/formatting/rules.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/formatting/rules.ts:728]: @rbuckton Thanks for the review. I just thought [formattingDecorators](https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/formattingDecorators.ts) covered most cases. The rule was [added](https://github.com/microsoft/TypeScript/commit/eec39c2fc50fdeee05b385e8c83fd54992e03d87) without tests, so it's difficult to understand what cases it covers.

File: src/services/formatting/rules.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/formatting/rules.ts:735]: > However, in the linked issue this is being used in tandem with ChangeTracker, which often means new synthetic nodes are added to the tree that don't have a valid .parent.

This is the root cause :). We can try to add more tests to [formattingDecorators](https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/formattingDecorators.ts), or just use `node && ...` to skip this rule for synthetic nodes. Both ways are ok for me :)

Comment (a-tarasyuk) [reply src/services/formatting/rules.ts:735]: @rbuckton I've changed the condition to `node && ...`.

**Review by DanielRosenwasser — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]
