### PR TITLE
nullish coalescing commit

### LINKED ISSUE #26578: Nullish coalescing operator (??)
## Search Terms

- **nullish coalescing**

## Suggestion

A nullish coalescing operator, which is essentially an alternative to `||` that will only return the right-side expression if the left-side is `null` or `undefined` (`||` returns the right-side if the left-side is falsy, i.e. `null | undefined | "" | 0 | false | NaN`).

## Use Cases

This would be extremely useful anywhere where defaults are needed for potentially omitted inputs, but empty strings or `0`, and so forth, are valid inputs that shouldn't be defaulted. My particular use case is AngularJS component bindings. Whenever bindings are updated, I would like to provide a default for a string or boolean binding only when they are straight up omitted (`undefined`), but I have to do a full-fledged ternary expression with `typeof` to handle the falsy input corner-case.

In conjunction with the *safe chaining operator* (#16), handling optionals would be trivial.

## Examples

```TypeScript
export interface Configuration {
    // Default: "(no name)"; empty string IS valid
    name?:  string;

    // Default: -1; 0 is valid
    items?:  number;

    // Default: true
    active?: boolean;
}

function configureSomething(config: Configuration) {
    // With null-coalescing operator
    config.name = config.name ?? "(no name)";
    config.items = config.items ?? -1;
    config.active = config.active ?? true;

    // Current solution
    config.name = typeof config.name === "string" ? config.name : "(no name)";
    config.items = typeof config.items === "number" ? config.items : -1;
    config.active = typeof config.active === "boolean" ? config.active : true;

    // Using || operator (INCORRECT)
    config.name = config.name || "(no name)"; // does not allow for "" input
    config.items = config.items || -1; // does not allow for 0 input
    config.active = config.active || true; // really bad, always true
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

### PR DESCRIPTION
**Pull request by Kingwl**
follow https://tc39.es/proposal-nullish-coalescing/

> Introduction
> This document specifies the nullish coalescing operator ??. See the explainer for an introduction.
>
> The main design decisions made in this specification are:
>
> The right argument of ?? is evaluated only if needed ("short circuiting").
> ?? has **lower** precedence than ||.
> ?? **cannot** immediately contain, or be contained within, an && or || operation.
> The right argument is selected if the left argument is null or undefined.

Fixes #26578 

TODO:
- [x] migrate & regression by @Kingwl @dragomirtitian 
- [x] scanner & parser, by @rbuckton 
- [x] binder, by @rbuckton 
- [x] checker, by @rbuckton 
- [x] grammar checker by @Kingwl 
- [x] transformer, by @rbuckton @dragomirtitian 
- [x] factory by @Kingwl 
- [x] quick fix & refactor @dragomirtitian @Kingwl 
- [ ] tests, tests, tests, tests by @Kingwl @dragomirtitian 
- [x] vscode highlight (https://github.com/microsoft/TypeScript-TmLanguage/issues/522)
- [ ] ? new quick fix

### CODE REVIEW

**Comment by AlCalzone** [comment]
Is this the real life? :heart_eyes:

**Comment by Kingwl** [comment]
@typescript-bot test this.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -23917,6 +23918,10 @@ namespace ts {
                     return getTypeFacts(leftType) & TypeFacts.Falsy ?
                         getUnionType([removeDefinitelyFalsyTypes(leftType), rightType], UnionReduction.Subtype) :
                         leftType;
+                case SyntaxKind.QuestionQuestionToken:
+                    return getTypeFacts(leftType) & TypeFacts.EQUndefinedOrNull ?
+                        getUnionType([getNonNullableType(leftType), rightType], UnionReduction.Subtype) :
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Does it make sense to also return a union type for when `strictNullChecks` is off?

File: src/compiler/factory.ts [hunk 2]
```diff
@@ -3044,6 +3044,10 @@ namespace ts {
         return createBinary(left, SyntaxKind.BarBarToken, right);
     }
 
+    export function createNullishCoalescing(left: Expression, right: Expression) {
```
Comment (DanielRosenwasser) [inline src/compiler/factory.ts]: Nit: `createNullishCoalesce`? I dunno, what do you think @rbuckton?

File: tests/baselines/reference/nullishCoalescingOperator1.js [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+const cc4 = c4 ?? true;
+
+const dd1 = d1 ?? {b: 1};
+const dd2 = d2 ?? {b: 1};
+const dd3 = d3 ?? {b: 1};
+const dd4 = d4 ?? {b: 1};
+
+//// [nullishCoalescingOperator1.js]
+"use strict";
+var aa1 = typeof a1 !== "undefined" && a1 !== null ? a1 : 'whatever';
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/nullishCoalescingOperator1.js]: I think this condition is reversed. 😄 

You either want equality or to reverse the branches. I'd prefer just switching to `===`/`==`.

Comment (DanielRosenwasser) [reply tests/baselines/reference/nullishCoalescingOperator1.js]: Just as a heads up, we might want to just go with `a1 == null`, since `document.all` is a weird anomaly of the language anyway that should ideally never be used in a `??` expression.

**Comment by DanielRosenwasser** [comment]
`.js` emit test cases I'd like you to consider when targeting ESNext:

```ts
declare let a: any, b: any, c: any;

let x1 = (a ?? b as unknown) || c;
let x2 = c || (a ?? b as unknown);
let x3 = ((a ?? b) as unknown) || c;

let x = (a ?? b as unknown) && c;
let x = c && (a ?? b as unknown);


```

**Comment by dragomirtitian** [comment]
@DanielRosenwasser I've added the tests, emit appears to work as expected keeping the `()` around the `a ?? b`. So as to conform to the grammar requirement that: 
> `??` cannot immediately contain, or be contained within, an `&&` or `||` operation. 

Hope I didn't miss the point of the tests 😅

@rbuckton or @DanielRosenwasser 
One thing I noticed was that emit is using the actual identifier in the down level version of `??`. So `x ?? 0` becomes `typeof x !== undefined && x !== null ? x : 0`. 

But if `x` comes from an import, because of the order in which the transformations are applied, we might get side effects on the access to `x`:

```ts
//test2.ts
let x = { y: 1, x: 0 }
let v = 0;
Object.defineProperty(x, "x", {
    get() {
        return v++;
    }
})
export = x;
//usage.ts
import { x, y } from './test2'
let xo = x ?? "NO"
console.log(xo);
let yo = y ?? "NO"
console.log(yo);
```
This will output `2` and `1` because `let xo = x ?? "NO"` becomes `var xo = typeof test2_1.x !== "undefined" && test2_1.x !== null ? test2_1.x : "NO";` which will call the getter multiple times.

I would just use the approach babel uses, use a temporary variable always [ex](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBBDOELwQB4QPwogTwgH2xAXhEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=7.5.5&externalPlugins=). Thoughts ?

**Comment by DanielRosenwasser** [comment]
I think "use a temporary unless it's an identifier" is usually the approach we take.

**Comment by dragomirtitian** [comment]
@DanielRosenwasser Mkay 😕, so ignore the corner case above ?

Just to make sure I was clear in what I was trying to say `x ?? "NO"` is seen as using an identifier in the `esnext` transform, but the `commonJS` transformation will effectively turn it into `test2_1.x ?? "NO"` (with the actual result being `typeof test2_1.x !== "undefined" && test2_1.x !== null ? test2_1.x : "NO"; `)

**Comment by Kingwl** [comment]
@dragomirtitian 
I prefer it to be a side effect (or feature) of cjs. 
not only this one but also many other syntaxes.

File: src/compiler/checker.ts (hunk 1 above)
Comment (Kingwl) [reply src/compiler/checker.ts]: I'd like to say yes, every value could be null/undefined if strictNullChecks is off and we cannot detect that.

same as:
```ts
declare const a: string
let b = a || 1 // b is string || number
```

**Comment by Kingwl** [comment]
@typescript-bot test this.

**Comment by weswigham** [comment]
@typescript-bot test this.

**Comment by Kingwl** [comment]
Ping @DanielRosenwasser @weswigham 
Could you show me the failed test case please? That seems the internal case.

**Comment by weswigham** [comment]
@Kingwl sync with master and run again - it looks like the RWC diff is mostly in bits that have changed in `master`, like the multi-overload error and the object.assign emit change. (also maybe un-draft so normal tests run - looks like pipelines no longer triggers for draft PRs)

**Comment by Kingwl** [comment]
```ts
// global-ish prefixes
var min = window.min ?? {};
min.nest = this.min.nest ?? function () { };
min.nest.other = self.min.nest.other ?? class { };
min.property = global.min.property ?? {};
```
I found this in `typeFromPropertyAssignment9_1.ts` Take a look soon

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -24437,16 +24438,29 @@ namespace ts {
...
         }
 
+        function checkGrammarNullishCoalesceWithLogicalExpression (node: BinaryExpression) {
+            const { left, operatorToken, right } = node;
+            if (operatorToken.kind === SyntaxKind.QuestionQuestionToken) {
+                if (isBinaryExpression(left) && (left.operatorToken.kind === SyntaxKind.BarBarToken || left.operatorToken.kind === SyntaxKind.AmpersandAmpersandToken)) {
+                    error(left, Diagnostics.Operator_0_cannot_immediately_contain_or_be_contained_within_an_1_operation, tokenToString(left.operatorToken.kind), tokenToString(operatorToken.kind));
+                }
+                if (isBinaryExpression(right) && (right.operatorToken.kind === SyntaxKind.BarBarToken || right.operatorToken.kind === SyntaxKind.AmpersandAmpersandToken)) {
+                    error(right, Diagnostics.Operator_0_cannot_immediately_contain_or_be_contained_within_an_1_operation, tokenToString(right.operatorToken.kind), tokenToString(operatorToken.kind));
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: @DanielRosenwasser  Is this enough or should we add did you mean to parenthesize the expression? Do we need code fix for that?

File: src/compiler/scanner.ts [hunk 5]
```diff
@@ -2016,6 +2022,12 @@ namespace ts {
             return token;
         }
 
+        function reScanQuestionQuestionToken(): SyntaxKind {
```
Comment (sheetalkamat) [inline src/compiler/scanner.ts]: This should be named `reScanQuestionToken` since thats what we are rescanning?

File: src/compiler/checker.ts (hunk 4 above)
Comment (sheetalkamat) [reply src/compiler/checker.ts]: Also i am not sure if this is suppose to be error? Where does it say its error?

File: src/compiler/utilities.ts [hunk 6]
```diff
@@ -1957,7 +1962,9 @@ namespace ts {
      * 'window.', 'global.' or 'self.' The second Lhs is otherwise ignored by the binder and checker.
      */
     function getDefaultedExpandoInitializer(name: EntityNameExpression, initializer: Expression, isPrototypeAssignment: boolean) {
-        const e = isBinaryExpression(initializer) && initializer.operatorToken.kind === SyntaxKind.BarBarToken && getExpandoInitializer(initializer.right, isPrototypeAssignment);
+        const e = isBinaryExpression(initializer)
+            && (initializer.operatorToken.kind === SyntaxKind.BarBarToken || initializer.operatorToken.kind === SyntaxKind.QuestionQuestionToken)
+            && getExpandoInitializer(initializer.right, isPrototypeAssignment);
         if (e && isSameEntityName(name, (initializer as BinaryExpression).left as EntityNameExpression)) {
             return e;
```
Comment (sheetalkamat) [inline src/compiler/utilities.ts]: Handle `getNameOfExpando` as well?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -24607,6 +24621,10 @@ namespace ts {
                     return getTypeFacts(leftType) & TypeFacts.Falsy ?
                         getUnionType([removeDefinitelyFalsyTypes(leftType), rightType], UnionReduction.Subtype) :
                         leftType;
+                case SyntaxKind.QuestionQuestionToken:
+                    return getTypeFacts(leftType) & TypeFacts.EQUndefinedOrNull ?
+                        getUnionType([getNonNullableType(leftType), rightType], UnionReduction.Subtype) :
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: We are getting type here without `null` or `undefined` but when we downlevel we only check for `null` is this intended. cc: @DanielRosenwasser

File: src/compiler/checker.ts (hunk 4 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: I think it should be

```
'{0}' and '{1}' operations cannot be mixed without parentheses.
```

Quick fixes would be lovely, but aren't required for this iteration.

* `Rewrite as '(a {0} b) {1} c'.`
* `Rewrite as 'a {0} (b {1} c)'.`

If you introduce quick fixes, please ensure that they have differentiated quick fix IDs so we can tell when `??` is the operation people intend to occur first.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: > Also i am not sure if this is suppose to be error? Where does it say its error?

The grammar doesn't make it clear (it used to when it was a grammar flag), but you can see it on https://tc39.es/proposal-nullish-coalescing/#sec-intro

image

File: src/compiler/checker.ts (hunk 7 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: `== null` checks for both `null` and `undefined`. So `x == null` is almost equivalent to `x === null || x === undefined`.

The only gotcha is that `document.all == null` is true but `document.all === null || document.all === undefined` is false.

Comment (sheetalkamat) [reply src/compiler/checker.ts]: Somehow I missed `==` and thought of that as `===`

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -18887,6 +18887,7 @@ namespace ts {
                     }
                     return contextSensitive === true ? getTypeOfExpression(left) : contextSensitive;
                 case SyntaxKind.BarBarToken:
+                case SyntaxKind.QuestionQuestionToken:
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Do you have a test case for this?

```ts
// @strict: true

declare let f: null | (x: string) => void;

let g = f ?? abc => { void abc.toLowerCase() }
```

Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: Here, `abc` should be contextually typed with `string`

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -24607,6 +24621,10 @@ namespace ts {
                     return getTypeFacts(leftType) & TypeFacts.Falsy ?
                         getUnionType([removeDefinitelyFalsyTypes(leftType), rightType], UnionReduction.Subtype) :
                         leftType;
+                case SyntaxKind.QuestionQuestionToken:
```
[the remark this answers is not in the document]
Comment (Kingwl) [reply src/compiler/checker.ts]: IMO，`DestructuringAssignment` never be `QuestionQuestion` or `BarBar` or `AmpersandAmpersand` . Does it?

**Comment by Kingwl** [comment]
@typescript-bot pack this.

File: src/compiler/types.ts [hunk 10]
```diff
@@ -1502,6 +1503,7 @@ namespace ts {
     export type LogicalOperator
```
Comment (DanielRosenwasser) [inline src/compiler/types.ts]: This is actually kind of strange because it's not *really* a LogicalOperator. Should it be moved out?

File: src/compiler/binder.ts [hunk 11]
```diff
@@ -943,7 +943,8 @@ namespace ts {
                 else {
                     return node.kind === SyntaxKind.BinaryExpression && (
                         (<BinaryExpression>node).operatorToken.kind === SyntaxKind.AmpersandAmpersandToken ||
-                        (<BinaryExpression>node).operatorToken.kind === SyntaxKind.BarBarToken);
+                        (<BinaryExpression>node).operatorToken.kind === SyntaxKind.BarBarToken ||
+                        (<BinaryExpression>node).operatorToken.kind === SyntaxKind.QuestionQuestionToken);
```
Comment (rbuckton) [inline src/compiler/binder.ts]: `??` isn't really a logical operator. This results in control-flow treating the branch as something "truthy" not something defined/undefined. 

I'd like to see some tests for control flow.

**Comment by Kingwl** [comment]
I’ll update that today

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -26247,16 +26248,29 @@ namespace ts {
             if (isInJSFile(node) && getAssignedExpandoInitializer(node)) {
                 return checkExpression(node.right, checkMode);
             }
+            checkGrammarNullishCoalesceWithLogicalExpression(node);
             return checkBinaryLikeExpression(node.left, node.operatorToken, node.right, checkMode, node);
         }
 
+        function checkGrammarNullishCoalesceWithLogicalExpression (node: BinaryExpression) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: (Nit: stray space after function name)

File: src/compiler/scanner.ts [hunk 13]
```diff
@@ -1828,6 +1831,9 @@ namespace ts {
                         pos++;
                         return token = SyntaxKind.GreaterThanToken;
                     case CharacterCodes.question:
+                        if (text.charCodeAt(pos + 1) === CharacterCodes.question) {
```
Comment (robpalme) [inline src/compiler/scanner.ts]: Nit: If you re-order the `pos++` before the `if`, the code become marginally simpler.

Comment (Kingwl) [reply src/compiler/scanner.ts]: I prefer to be consistent with the existed code.

File: src/compiler/binder.ts [hunk 14]
```diff
@@ -1461,12 +1469,15 @@ namespace ts {
 
         function bindBinaryExpressionFlow(node: BinaryExpression) {
             const operator = node.operatorToken.kind;
-            if (operator === SyntaxKind.AmpersandAmpersandToken || operator === SyntaxKind.BarBarToken) {
+            if (operator === SyntaxKind.AmpersandAmpersandToken || operator === SyntaxKind.BarBarToken || operator === SyntaxKind.QuestionQuestionToken) {
```
[the remark this answers is not in the document]
Comment (Kingwl) [reply src/compiler/binder.ts]: I prefer to keep this because of so many other code similar to that.

**Comment by rbuckton** [comment]
@Kingwl: Thanks for the contribution! 

My changes were mostly to merge the control-flow behavior of nullish-coalesce with the control-flow behavior of optional chaining and to resolve merge conflicts so that this could be merged with master for the 3.7 beta. Thanks again for all of the hard work!

**Comment by wsmd** [comment]
Thank you all for your hard work on this and congrats on the 3.7 release! 

I have a small question out of curiosity. For `foo ?? bar`, was `document.all` the reason for choosing `foo !== null && foo !== void 0` as the conditional expression in the compiled output, as opposed to the [abstract equality comparison](https://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3) `foo != null`? 😅 

```js
let x = (foo !== null && foo !== undefined) ? foo : bar;
// vs
let x = foo != null ? foo : bar;
```

**Comment by Kingwl** [comment]
> was document.all the reason for  
@wsmd 
https://github.com/microsoft/TypeScript/pull/32883#discussion_r314205657
https://github.com/microsoft/TypeScript/pull/32883#discussion_r328841610

File: tests/baselines/reference/nullishCoalescingOperator1.js (hunk 3 above)
Comment (arusakov) [reply tests/baselines/reference/nullishCoalescingOperator1.js]: @DanielRosenwasser
Sorry for late comment after TypeScript 3.7 release.
But what about a shorter implementation of `??` operator that you suggest?
This implementation with less code is better for all of us, I think.
