### PR TITLE
Disallow calls on never type

### LINKED ISSUE #11412: Calling and indexing on type 'never' is allowed
Given that a property accesses and `new`ing isn't allowed on something of type `never`,

``` ts
declare var f: never;

// Error: Cannot use 'new' with an expression which lacks a construct signature.
new f();

// Error: Property 'x' does not exist on type 'never'.
f.x;
```

I was surprised to find that `never` is still callable and indexable.

``` ts
declare var f: never;

// All okay
f();
f[100]
f["x"]
```

Is this intentional?

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #11412.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16631,21 +16631,9 @@ namespace ts {
...
-                // no common signatures.
-                if (funcType.flags & TypeFlags.Union) {
-                    return false;
-                }
-                return isTypeAssignableTo(funcType, globalFunctionType);
-            }
-            return false;
+            // We exclude union types because we may have a union of function types that happen to have no common signatures.
+            return isTypeAny(funcType) || isTypeAny(apparentFuncType) && funcType.flags & TypeFlags.TypeParameter ||
+                !numCallSignatures && !numConstructSignatures && !(funcType.flags & (TypeFlags.Union | TypeFlags.Never)) && isTypeAssignableTo(funcType, globalFunctionType);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Strongly prefer the old style, but seems reasonable.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: You're too imperative, Daniel!
