### PR TITLE
fix quick fix infer parameter types from usage in js file

### LINKED ISSUE #29072: JavaScript infer types from usage inserts jsdoc in wrong location for const arrow function
**TypeScript Version:**  3.3.0-dev.20181214

**Search Terms:**
- javascript
- jsdocs
- quick fix
- infer types from usage

**Code**
For the JavaScript:

```ts
// @ts-check

const a = (x) => x.y + 1;
```
1. Run the infer types from usage quick fix on `x`

**Expected behavior:**

```ts
// @ts-check

/**
 * @param {{ y: number; }} x
 */
const a =  (x) => x.y + 1;
```

**Actual behavior:**

```ts
// @ts-check

const a = /**
 * @param {{ y: number; }} x
 */
 (x) => x.y + 1;
```
**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by fuafa**
Fixes #29072

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -340,7 +340,9 @@ namespace ts.textChanges {
         }
 
         public insertJsdocCommentBefore(sourceFile: SourceFile, node: HasJSDoc, tag: JSDoc): void {
-            const fnStart = node.getStart(sourceFile);
+            const fnStart = node.kind === SyntaxKind.ArrowFunction
```
Comment (RyanCavanaugh) [inline src/services/textChanges.ts]: It should be the caller's responsibility to set the parent node higher in this situation - `textChanges` should always behave as instructed.

Comment (fuafa) [reply src/services/textChanges.ts]: I hoisted the code to `addJSDocTags`, is it the right place? I added another check for arrow function in class property declaration as well, since I think most programmers would want jsdoc in these two places.

**Comment by RyanCavanaugh** [comment]
Thanks!
