### PR TITLE
Fix Add all missing imports when ordered alphabetically

### LINKED ISSUE #42527: Trying to add multiple alphabetically adjacent imports from the same module results in assertion fail
# Bug Report

### 🔎 Search Terms

- add all missing imports
- debug failure
- false expression
- changes overlap

### 🕗 Version & Regression Information

This bug exists in v4.1.2 and v4.1.3 according to my testing.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about imports.

### ⏯ Playground Link

This is a bug with the TypeScript Server itself. It cannot be shown in the Playground.

### 💻 Code

This bug can be replicated in VSCode by making two files:

`exports.ts`
```ts
export interface Test1 {}
export interface Test2 {}
export interface Test3 {}
export interface Test4 {}
```
`importer.ts`
```ts
import { Test1, Test4 } from './exports';
interface Testing {
    test1: Test1;
    test2: Test2;
    test3: Test3;
    test4: Test4;
}
```

### 🙁 Actual behavior

Expectedly, the server correctly reports that it cannot find `Test2` or `Test3`. Attempting to use the _Add all missing imports_
feature results in no change to the file. If the Developer Tools are used, an error is printed, similar to the one mentioned in #40065. In fact, this is likely the root of the previous issue.

The server fails at this assert statement:
https://github.com/microsoft/TypeScript/blob/517f32940ad44933f8bb3b5d07e8c830cbfc40ea/src/services/textChanges.ts#L909-L910

(which appears to have been introduced by this commit: https://github.com/microsoft/TypeScript/commit/f4af74aae182629c6615c39325b92915e7f9ac79)

The assert statement appears to be trying to catch edits that target the same area of text. Commenting out the assert and running this modified version of the TypeScript server fixes the issue and the imports are added correctly, showing that its use, at least in this context, is unnecessary. I am not sure though of the further ramifications of removing this assert, though.

**I believe this bug happens in this case because the two imports, `Test2` and `Test3`, are adjacent to each other alphabetically, and thus the server would be placing them both in the same spot, after `Test1`. It then gets confused and thinks it's trying to add conflicting edits and stops before it can do the deed. This behavior does not exist when trying to add imports for `Test3` and `Test4` (or for  `Test1` and `Test2`), which makes me believe that the two adjacent imports have to also be sandwiched between existing imports for this bug to happen.**

_TL;DR:_
_The server fails at adding multiple imports from the same module if, when added to the existing imports list,_
- _Two or more of the imports to be added will be alphabetically adjacent to each other_
- _One or more already-existing imports will be alphabetically before all of the imports to be added_
- _One or more already-existing imports will be alphabetically after all of the imports to be added_

### 🙂 Expected behavior
It is expected that the imports be added correctly, as they do when the assert statement is commented out.

### PR DESCRIPTION
**Pull request by armanio123**
Fixes #42527

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -916,7 +927,7 @@ namespace ts.textChanges {
                 const normalized = stableSort(changesInFile, (a, b) => (a.range.pos - b.range.pos) || (a.range.end - b.range.end));
                 // verify that change intervals do not overlap, except possibly at end points.
                 for (let i = 0; i < normalized.length - 1; i++) {
-                    Debug.assert(normalized[i].range.end <= normalized[i + 1].range.pos, "Changes overlap", () =>
+                    Debug.assert(normalized[i].range.end <= normalized[i + 1].range.pos || normalized[i].kind === ChangeKind.ReplaceWithList, "Changes overlap", () =>
```
Comment (andrewbranch) [inline src/services/textChanges.ts:930]: Could you paste the two JSON/debugger output of the two changes (`normalized[i]` and `normalized[i + 1]`) that trigger this assertion? I have some thoughts, but want to make sure I understand what’s happening correctly.

Comment (armanio123) [reply src/services/textChanges.ts:930]: They are pretty big nodes. But here it goes:
```
normalized[i] = {
  "kind": 4,
  "sourceFile": {
    "pos": 0,
    "end": 133,
    "flags": 0,
    "modifierFlagsCache": 0,
    "transformFlags": 1,
    "kind": 298,
    "statements": [
      {
        "pos": 0,
        "end": 39,
        "flags": 0,
        "modifierFlagsCache": 536870912,
        "transformFlags": 0,
        "kind": 262,
        "importClause": {
          "pos": 6,
          "end": 23,
          "flags": 0,
          "modifierFlagsCache": 0,
          "transformFlags": 0,
          "kind": 263,
          "isTypeOnly": false,
          "namedBindings": {
            "pos": 6,
            "end": 23,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 265,
            "elements": [
              {
                "pos": 8,
                "end": 14,
                "flags": 0,
                "modifierFlagsCache": 536870912,
                "transformFlags": 0,
                "kind": 266,
                "name": {
                  "pos": 8,
                  "end": 14,
                  "flags": 0,
                  "modifierFlagsCache": 0,
                  "transformFlags": 0,
                  "kind": 78,
                  "escapedText": "Test1",
                  "flowNode": {
                    "flags": 2
                  }
                },
                "symbol": {
                  "flags": 2097152,
                  "escapedName": "Test1",
                  "declarations": [
                    null
                  ],
                  "id": 14,
                  "isReferenced": 788968
                }
              },
              {
                "pos": 15,
                "end": 21,
                "flags": 0,
                "modifierFlagsCache": 536870912,
                "transformFlags": 0,
                "kind": 266,
                "name": {
                  "pos": 15,
                  "end": 21,
                  "flags": 0,
                  "modifierFlagsCache": 0,
                  "transformFlags": 0,
                  "kind": 78,
                  "escapedText": "Test4"
                },
                "symbol": {
                  "flags": 2097152,
                  "escapedName": "Test4",
                  "declarations": [
                    null
                  ],
                  "id": 17,
                  "isReferenced": 788968
                },
                "_children": [
                  null
                ]
              }
            ],
            "_children": [
              {
                "pos": 6,
                "end": 8,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 18
              },
              {
                "pos": 8,
                "end": 21,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 338,
                "_children": [
                  null,
                  {
                    "pos": 14,
                    "end": 15,
                    "flags": 0,
                    "modifierFlagsCache": 0,
                    "transformFlags": 0,
                    "kind": 27
                  },
                  null
                ]
              },
              {
                "pos": 21,
                "end": 23,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 19
              }
            ]
          },
          "_children": [
            null
          ],
          "id": 16
        },
        "moduleSpecifier": {
          "pos": 28,
          "end": 38,
          "flags": 0,
          "modifierFlagsCache": 0,
          "transformFlags": 0,
          "kind": 10,
          "text": "./file1",
          "hasExtendedUnicodeEscape": false
        },
        "_children": [
          {
            "pos": 0,
            "end": 6,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 99
          },
          null,
          {
            "pos": 23,
            "end": 28,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 153
          },
          null,
          {
            "pos": 38,
            "end": 39,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 26
          }
        ]
      },
      {
        "pos": 39,
        "end": 133,
        "flags": 524288,
        "modifierFlagsCache": 536870912,
        "transformFlags": 1,
        "kind": 254,
        "symbol": {
          "flags": 64,
          "escapedName": "Testing",
          "declarations": [
            null
          ],
          "members": {},
          "id": 19
        },
        "name": {
          "pos": 49,
          "end": 57,
          "flags": 524288,
          "modifierFlagsCache": 0,
          "transformFlags": 0,
          "kind": 78,
          "escapedText": "Testing"
        },
        "members": [
          {
            "pos": 59,
            "end": 77,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test1",
              "declarations": [
                null
              ],
              "id": 20
            },
            "name": {
              "pos": 59,
              "end": 69,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test1"
            },
            "type": {
              "pos": 70,
              "end": 76,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 70,
                "end": 76,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test1"
              },
              "id": 12
            }
          },
          {
            "pos": 77,
            "end": 95,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test2",
              "declarations": [
                null
              ],
              "id": 21
            },
            "name": {
              "pos": 77,
              "end": 87,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test2"
            },
            "type": {
              "pos": 88,
              "end": 94,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 88,
                "end": 94,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test2"
              },
              "id": 13,
              "_children": [
                null
              ]
            },
            "_children": [
              null,
              {
                "pos": 87,
                "end": 88,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 58
              },
              null,
              {
                "pos": 94,
                "end": 95,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 26
              }
            ]
          },
          {
            "pos": 95,
            "end": 113,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test3",
              "declarations": [
                null
              ],
              "id": 22
            },
            "name": {
              "pos": 95,
              "end": 105,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test3"
            },
            "type": {
              "pos": 106,
              "end": 112,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 106,
                "end": 112,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test3"
              },
              "id": 14,
              "_children": [
                null
              ]
            },
            "_children": [
              null,
              {
                "pos": 105,
                "end": 106,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 58
              },
              null,
              {
                "pos": 112,
                "end": 113,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 26
              }
            ]
          },
          {
            "pos": 113,
            "end": 131,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test4",
              "declarations": [
                null
              ],
              "id": 23
            },
            "name": {
              "pos": 113,
              "end": 123,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test4"
            },
            "type": {
              "pos": 124,
              "end": 130,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 124,
                "end": 130,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test4"
              },
              "id": 15
            }
          }
        ],
        "_children": [
          {
            "pos": 39,
            "end": 49,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 117
          },
          null,
          {
            "pos": 57,
            "end": 59,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 18
          },
          {
            "pos": 59,
            "end": 131,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 338,
            "_children": [
              null,
              null,
              null,
              null
            ]
          },
          {
            "pos": 131,
            "end": 133,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 19
          }
        ]
      }
    ],
    "endOfFileToken": {
      "pos": 133,
      "end": 133,
      "flags": 0,
      "modifierFlagsCache": 0,
      "transformFlags": 0,
      "kind": 1
    },
    "fileName": "/tests/cases/fourslash/file2.ts",
    "text": "import { Test1, Test4 } from './file1';\ninterface Testing {\n    test1: Test1;\n    test2: Test2;\n    test3: Test3;\n    test4: Test4;\n}",
    "languageVersion": 1,
    "languageVariant": 0,
    "scriptKind": 3,
    "isDeclarationFile": false,
    "hasNoDefaultLib": false,
    "bindDiagnostics": [],
    "pragmas": {},
    "referencedFiles": [],
    "typeReferenceDirectives": [],
    "libReferenceDirectives": [],
    "amdDependencies": [],
    "nodeCount": 28,
    "identifierCount": 11,
    "identifiers": {},
    "parseDiagnostics": [],
    "version": "1",
    "scriptSnapshot": {
      "scriptInfo": {
        "fileName": "/tests/cases/fourslash/file2.ts",
        "content": "import { Test1, Test4 } from './file1';\ninterface Testing {\n    test1: Test1;\n    test2: Test2;\n    test3: Test3;\n    test4: Test4;\n}",
        "isRootFile": true,
        "version": 1,
        "editRanges": []
      },
      "textSnapshot": "import { Test1, Test4 } from './file1';\ninterface Testing {\n    test1: Test1;\n    test2: Test2;\n    test3: Test3;\n    test4: Test4;\n}",
      "version": 1
    },
    "path": "/tests/cases/fourslash/file2.ts",
    "resolvedPath": "/tests/cases/fourslash/file2.ts",
    "originalFileName": "/tests/cases/fourslash/file2.ts",
    "imports": [
      null
    ],
    "moduleAugmentations": [],
    "resolvedModules": {},
    "symbol": {
      "flags": 512,
      "escapedName": "\"/tests/cases/fourslash/file2\"",
      "declarations": [
        null
      ],
      "exports": {},
      "id": 24
    },
    "locals": {},
    "symbolCount": 8,
    "classifiableNames": {},
    "id": 11,
    "_children": [
      {
        "pos": 0,
        "end": 133,
        "flags": 0,
        "modifierFlagsCache": 0,
        "transformFlags": 0,
        "kind": 338,
        "_children": [
          null,
          null
        ]
      },
      null
    ],
    "lineMap": [
      0,
      40,
      60,
      78,
      96,
      114,
      132
    ]
  },
  "range": {
    "pos": 15,
    "end": 16
  },
  "options": {
    "prefix": " ",
    "suffix": ", "
  },
  "node": {
    "pos": -1,
    "end": -1,
    "flags": 8,
    "modifierFlagsCache": 0,
    "transformFlags": 0,
    "kind": 266,
    "name": {
      "pos": -1,
      "end": -1,
      "flags": 8,
      "modifierFlagsCache": 0,
      "transformFlags": 0,
      "kind": 78,
      "escapedText": "Test2"
    }
  }
}
```
```
normalized[i + 1] = {
  "kind": 4,
  "sourceFile": {
    "pos": 0,
    "end": 133,
    "flags": 0,
    "modifierFlagsCache": 0,
    "transformFlags": 1,
    "kind": 298,
    "statements": [
      {
        "pos": 0,
        "end": 39,
        "flags": 0,
        "modifierFlagsCache": 536870912,
        "transformFlags": 0,
        "kind": 262,
        "importClause": {
          "pos": 6,
          "end": 23,
          "flags": 0,
          "modifierFlagsCache": 0,
          "transformFlags": 0,
          "kind": 263,
          "isTypeOnly": false,
          "namedBindings": {
            "pos": 6,
            "end": 23,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 265,
            "elements": [
              {
                "pos": 8,
                "end": 14,
                "flags": 0,
                "modifierFlagsCache": 536870912,
                "transformFlags": 0,
                "kind": 266,
                "name": {
                  "pos": 8,
                  "end": 14,
                  "flags": 0,
                  "modifierFlagsCache": 0,
                  "transformFlags": 0,
                  "kind": 78,
                  "escapedText": "Test1",
                  "flowNode": {
                    "flags": 2
                  }
                },
                "symbol": {
                  "flags": 2097152,
                  "escapedName": "Test1",
                  "declarations": [
                    null
                  ],
                  "id": 14,
                  "isReferenced": 788968
                }
              },
              {
                "pos": 15,
                "end": 21,
                "flags": 0,
                "modifierFlagsCache": 536870912,
                "transformFlags": 0,
                "kind": 266,
                "name": {
                  "pos": 15,
                  "end": 21,
                  "flags": 0,
                  "modifierFlagsCache": 0,
                  "transformFlags": 0,
                  "kind": 78,
                  "escapedText": "Test4"
                },
                "symbol": {
                  "flags": 2097152,
                  "escapedName": "Test4",
                  "declarations": [
                    null
                  ],
                  "id": 17,
                  "isReferenced": 788968
                },
                "_children": [
                  null
                ]
              }
            ],
            "_children": [
              {
                "pos": 6,
                "end": 8,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 18
              },
              {
                "pos": 8,
                "end": 21,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 338,
                "_children": [
                  null,
                  {
                    "pos": 14,
                    "end": 15,
                    "flags": 0,
                    "modifierFlagsCache": 0,
                    "transformFlags": 0,
                    "kind": 27
                  },
                  null
                ]
              },
              {
                "pos": 21,
                "end": 23,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 19
              }
            ]
          },
          "_children": [
            null
          ],
          "id": 16
        },
        "moduleSpecifier": {
          "pos": 28,
          "end": 38,
          "flags": 0,
          "modifierFlagsCache": 0,
          "transformFlags": 0,
          "kind": 10,
          "text": "./file1",
          "hasExtendedUnicodeEscape": false
        },
        "_children": [
          {
            "pos": 0,
            "end": 6,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 99
          },
          null,
          {
            "pos": 23,
            "end": 28,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 153
          },
          null,
          {
            "pos": 38,
            "end": 39,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 26
          }
        ]
      },
      {
        "pos": 39,
        "end": 133,
        "flags": 524288,
        "modifierFlagsCache": 536870912,
        "transformFlags": 1,
        "kind": 254,
        "symbol": {
          "flags": 64,
          "escapedName": "Testing",
          "declarations": [
            null
          ],
          "members": {},
          "id": 19
        },
        "name": {
          "pos": 49,
          "end": 57,
          "flags": 524288,
          "modifierFlagsCache": 0,
          "transformFlags": 0,
          "kind": 78,
          "escapedText": "Testing"
        },
        "members": [
          {
            "pos": 59,
            "end": 77,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test1",
              "declarations": [
                null
              ],
              "id": 20
            },
            "name": {
              "pos": 59,
              "end": 69,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test1"
            },
            "type": {
              "pos": 70,
              "end": 76,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 70,
                "end": 76,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test1"
              },
              "id": 12
            }
          },
          {
            "pos": 77,
            "end": 95,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test2",
              "declarations": [
                null
              ],
              "id": 21
            },
            "name": {
              "pos": 77,
              "end": 87,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test2"
            },
            "type": {
              "pos": 88,
              "end": 94,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 88,
                "end": 94,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test2"
              },
              "id": 13,
              "_children": [
                null
              ]
            },
            "_children": [
              null,
              {
                "pos": 87,
                "end": 88,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 58
              },
              null,
              {
                "pos": 94,
                "end": 95,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 26
              }
            ]
          },
          {
            "pos": 95,
            "end": 113,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test3",
              "declarations": [
                null
              ],
              "id": 22
            },
            "name": {
              "pos": 95,
              "end": 105,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test3"
            },
            "type": {
              "pos": 106,
              "end": 112,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 106,
                "end": 112,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test3"
              },
              "id": 14,
              "_children": [
                null
              ]
            },
            "_children": [
              null,
              {
                "pos": 105,
                "end": 106,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 58
              },
              null,
              {
                "pos": 112,
                "end": 113,
                "flags": 0,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 26
              }
            ]
          },
          {
            "pos": 113,
            "end": 131,
            "flags": 524288,
            "modifierFlagsCache": 536870912,
            "transformFlags": 1,
            "kind": 163,
            "symbol": {
              "flags": 4,
              "escapedName": "test4",
              "declarations": [
                null
              ],
              "id": 23
            },
            "name": {
              "pos": 113,
              "end": 123,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 0,
              "kind": 78,
              "escapedText": "test4"
            },
            "type": {
              "pos": 124,
              "end": 130,
              "flags": 524288,
              "modifierFlagsCache": 0,
              "transformFlags": 1,
              "kind": 174,
              "typeName": {
                "pos": 124,
                "end": 130,
                "flags": 524288,
                "modifierFlagsCache": 0,
                "transformFlags": 0,
                "kind": 78,
                "escapedText": "Test4"
              },
              "id": 15
            }
          }
        ],
        "_children": [
          {
            "pos": 39,
            "end": 49,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 117
          },
          null,
          {
            "pos": 57,
            "end": 59,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 18
          },
          {
            "pos": 59,
            "end": 131,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 338,
            "_children": [
              null,
              null,
              null,
              null
            ]
          },
          {
            "pos": 131,
            "end": 133,
            "flags": 0,
            "modifierFlagsCache": 0,
            "transformFlags": 0,
            "kind": 19
          }
        ]
      }
    ],
    "endOfFileToken": {
      "pos": 133,
      "end": 133,
      "flags": 0,
      "modifierFlagsCache": 0,
      "transformFlags": 0,
      "kind": 1
    },
    "fileName": "/tests/cases/fourslash/file2.ts",
    "text": "import { Test1, Test4 } from './file1';\ninterface Testing {\n    test1: Test1;\n    test2: Test2;\n    test3: Test3;\n    test4: Test4;\n}",
    "languageVersion": 1,
    "languageVariant": 0,
    "scriptKind": 3,
    "isDeclarationFile": false,
    "hasNoDefaultLib": false,
    "bindDiagnostics": [],
    "pragmas": {},
    "referencedFiles": [],
    "typeReferenceDirectives": [],
    "libReferenceDirectives": [],
    "amdDependencies": [],
    "nodeCount": 28,
    "identifierCount": 11,
    "identifiers": {},
    "parseDiagnostics": [],
    "version": "1",
    "scriptSnapshot": {
      "scriptInfo": {
        "fileName": "/tests/cases/fourslash/file2.ts",
        "content": "import { Test1, Test4 } from './file1';\ninterface Testing {\n    test1: Test1;\n    test2: Test2;\n    test3: Test3;\n    test4: Test4;\n}",
        "isRootFile": true,
        "version": 1,
        "editRanges": []
      },
      "textSnapshot": "import { Test1, Test4 } from './file1';\ninterface Testing {\n    test1: Test1;\n    test2: Test2;\n    test3: Test3;\n    test4: Test4;\n}",
      "version": 1
    },
    "path": "/tests/cases/fourslash/file2.ts",
    "resolvedPath": "/tests/cases/fourslash/file2.ts",
    "originalFileName": "/tests/cases/fourslash/file2.ts",
    "imports": [
      null
    ],
    "moduleAugmentations": [],
    "resolvedModules": {},
    "symbol": {
      "flags": 512,
      "escapedName": "\"/tests/cases/fourslash/file2\"",
      "declarations": [
        null
      ],
      "exports": {},
      "id": 24
    },
    "locals": {},
    "symbolCount": 8,
    "classifiableNames": {},
    "id": 11,
    "_children": [
      {
        "pos": 0,
        "end": 133,
        "flags": 0,
        "modifierFlagsCache": 0,
        "transformFlags": 0,
        "kind": 338,
        "_children": [
          null,
          null
        ]
      },
      null
    ],
    "lineMap": [
      0,
      40,
      60,
      78,
      96,
      114,
      132
    ]
  },
  "range": {
    "pos": 15,
    "end": 16
  },
  "options": {
    "prefix": " ",
    "suffix": ", "
  },
  "node": {
    "pos": -1,
    "end": -1,
    "flags": 8,
    "modifierFlagsCache": 0,
    "transformFlags": 0,
    "kind": 266,
    "name": {
      "pos": -1,
      "end": -1,
      "flags": 8,
      "modifierFlagsCache": 0,
      "transformFlags": 0,
      "kind": 78,
      "escapedText": "Test3"
    }
  }
}
```

Comment (andrewbranch) [reply src/services/textChanges.ts:930]: Edited ^ to remove the `sourceFile` node so we can look at this. The source file text was:

```ts
import { Test1, Test4 } from './file1';
interface Testing {
    test1: Test1;
    test2: Test2;
    test3: Test3;
    test4: Test4;
}
```

Comment (andrewbranch) [reply src/services/textChanges.ts:930]: What’s happening is that both fixes are attempting to delete the space between `Test1,` and `Test4` with their inserted node. They make up for the deletion of the space by including it in the `prefix` of their insertion. But it’s the deletion of the space that’s the alleged problem, because overlapping deletes might be problematic. It seems like the simplest fix would just be to ensure that this insertion is performed with an empty range, so it doesn’t try to delete anything.

File: src/services/textChanges.ts [hunk 2]
```diff
@@ -769,7 +780,7 @@ namespace ts.textChanges {
 
                     // write separator and leading trivia of the next element as suffix
                     const suffix = `${tokenToString(nextToken.kind)}${sourceFile.text.substring(nextToken.end, containingList[index + 1].getStart(sourceFile))}`;
-                    this.replaceRange(sourceFile, createRange(startPos, containingList[index + 1].getStart(sourceFile)), newNode, { prefix, suffix });
+                    this.replaceRangeWithList(sourceFile, createRange(startPos, containingList[index + 1].getStart(sourceFile)), newNode, { prefix, suffix });
```
Comment (andrewbranch) [inline src/services/textChanges.ts:783]: This is the problematic call, because the range is non-empty. It feels like you could just move `startPos` forward such that `prefix` is never needed, and create an empty range.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Comment by armanio123** [comment]
Done, the fix was actually super easy once you noticed that the problem is that is replacing the same text. Now instead of replacing it will insert in x position and uses the next node trivia for formatting.

File: src/services/textChanges.ts [hunk 3]
```diff
@@ -727,49 +719,24 @@ namespace ts.textChanges {
...
-                        //  |    |     |-next element
-                        //  |    |-new inserted node padded with spaces
-                        //  |-separator
-                        startPos = nextToken.end;
-                        prefix = spaces(lineAndCharOfNextElement.character - lineAndCharOfNextToken.character);
-                    }
-                    else {
-                        // next element is located on different line that separator
-                        // let insert position be the beginning of the line that contains next element
-                        startPos = getStartPositionOfLine(lineAndCharOfNextElement.line, sourceFile);
```
Comment (andrewbranch) [inline src/services/textChanges.ts:767]: There are a couple failing tests now; I’m guessing some of this was still important. If I had to guess, I would say that this `else` block needs to be preserved for insertions where the next element is on a different line.

Comment (armanio123) [reply src/services/textChanges.ts:767]: I really thought I have run the tests. Anyway is fixed now. We still don't need all of that we just need to consider the trivia.

**Review by andrewbranch — APPROVED** [review]
This is awesome! Gotta love fixing bugs by deleting code, especially code so complicated it needed ASCII diagramming to explain it.
