### PR TITLE
Handle unresolved baseType when trying to get completions for static member

### LINKED ISSUE #38067: TypeError: Cannot read property 'exportSymbol' of undefined in 'getTypeOfSymbolAtLocation' during 'completionInfo'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.8.3
**VSCode version**: 1.44.0
**Command requested**: completionInfo
**Hitting sessions**: 1742
**Five line hash**: 7333f71566327ab9a2402256aaaa04e7
**Stack**:
```
    at getTypeOfSymbolAtLocation (tsserver.js:52745:29)
    at getTypeOfSymbolAtLocation (tsserver.js:34280:35)
    at <anonymous> (tsserver.js:111028:130)
    at flatMap (tsserver.js:465:25)
    at tryGetClassLikeCompletionSymbols (tsserver.js:111026:42)
    at tryGetGlobalSymbols (tsserver.js:110416:24)
    at getCompletionData (tsserver.js:110215:22)
    at getCompletionsAtPosition (tsserver.js:109575:34)
    at getCompletionsAtPosition (tsserver.js:135360:35)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at Session.getCompletions (tsserver.js:145435:64)
    at _a.<computed> (tsserver.js:144383:61)
    at <anonymous> (tsserver.js:146003:88)
    at Session.executeWithRequestId (tsserver.js:145994:28)
    at Session.executeCommand (tsserver.js:146003:33)
    at Session.onMessage (tsserver.js:146027:35)
    at <anonymous> (tsserver.js:147342:27)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes  #38067

### CODE REVIEW

File: tests/cases/fourslash/completionEntryForClassMembers_StaticWhenBaseTypeIsNotResolved.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+////         setState<K extends keyof S>(
+////             state: ((prevState: Readonly<S>, props: Readonly<P>) => (Pick<S, K> | S | null)) | (Pick<S, K> | S | null),
+////             callback?: () => void
+////         ): void;
+////     }
+//// }
+
+// @Filename: /a.ts
+//// import React from 'react'
+//// class Slider extends React.Component {
```
Comment (sheetalkamat) [inline tests/cases/fourslash/completionEntryForClassMembers_StaticWhenBaseTypeIsNotResolved.ts:22]: React here is unknown because there is no `default` export

File: src/services/completions.ts [hunk 2]
```diff
@@ -2012,7 +2012,10 @@ namespace ts.Completions {
                 // List of property symbols of base type that are not private and already implemented
                 const baseSymbols = flatMap(getAllSuperTypeNodes(decl), baseTypeNode => {
                     const type = typeChecker.getTypeAtLocation(baseTypeNode);
-                    return type && typeChecker.getPropertiesOfType(classElementModifierFlags & ModifierFlags.Static ? typeChecker.getTypeOfSymbolAtLocation(type.symbol, decl) : type);
+                    return type &&
+                        classElementModifierFlags & ModifierFlags.Static ?
```
Comment (sandersn) [inline src/services/completions.ts:2016]: I think it's a tiny bit more readable to join the predicate into a single line:
```suggestion
                    return type && classElementModifierFlags & ModifierFlags.Static ?
```
