### PR TITLE
Do not watch child directories of the sym link folders

### LINKED ISSUE #22668: Bug: watch mode does not work since 2.8.0-dev.20180314
**TypeScript Version:**  2.8.0-dev.20180316

**Search Terms:** 

**Code**

tsc -w

**Expected behavior:**

Starting compilation in watch mode...
Compilation complete. Watching for file changes.

**Actual behavior:**
Starting compilation in watch mode...

and no files generated

**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #22668 and maintains same feature set as fs.watch on windows when node supports it.

### CODE REVIEW

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -392,9 +393,12 @@ namespace ts {
         function watchChildDirectories(parentDir: string, existingChildWatches: ChildWatches, callback: DirectoryWatcherCallback): ChildWatches {
             let newChildWatches: DirectoryWatcher[] | undefined;
             enumerateInsertsAndDeletes<string, DirectoryWatcher>(
-                host.directoryExists(parentDir) ? host.getAccessileSortedChildDirectories(parentDir) : emptyArray,
```
Comment (mhegazy) [inline src/compiler/sys.ts]: i am guessing this shoudl be `getAccessibleSortedChildDirectories`

File: src/compiler/sys.ts [hunk 2]
```diff
@@ -392,9 +393,12 @@ namespace ts {
         function watchChildDirectories(parentDir: string, existingChildWatches: ChildWatches, callback: DirectoryWatcherCallback): ChildWatches {
             let newChildWatches: DirectoryWatcher[] | undefined;
             enumerateInsertsAndDeletes<string, DirectoryWatcher>(
-                host.directoryExists(parentDir) ? host.getAccessileSortedChildDirectories(parentDir) : emptyArray,
+                host.directoryExists(parentDir) ? mapDefined(host.getAccessileSortedChildDirectories(parentDir), child => {
+                    const childFullName = getNormalizedAbsolutePath(child, parentDir);
+                    return host.filePathComparer(childFullName, host.realpath(childFullName)) === Comparison.EqualTo ? childFullName : undefined;
```
Comment (mhegazy) [inline src/compiler/sys.ts]: can you add a comment on why we are filtering here.

**Comment by mhegazy** [comment]
Please port to release-2.8 as well
