### PR TITLE
Ensure async code fix renaming can do more than one rename

### LINKED ISSUE #26376: Async / Await Refactoring - Catch Block Parameter are not checked for collisions
**Search Terms:**
Async, Await, Refactoring, Code Fix, 

**Code**
```ts
function f() {
	return Promise.resolve().then(x => 1).catch(x => "a").then(x => !!x); 
}
```

**Expected behavior:**
The refactor generates the following code with a unique catch parameter.
```ts
async function f() {
	let x_1: string | number;
    try {
        const x = await Promise.resolve();
        x_1 = 1;
    }
    catch (x_2) {
        x_1 = "a";
    }
    return !!x_1; 
}
```

**Actual behavior:**
The refactor generates the following code with a conflicting catch parameter. "a" is not assigned to the correct x_1.
```ts
async function f() {
	let x_1: string | number;
    try {
        const x = await Promise.resolve();
        x_1 = 1;
    }
    catch (x_1) {
        x_1 = "a";
    }
    return !!x_1; 
}
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by uniqueiniquity**
Fixes #26376.
Currently, if we are performing an async code fix, we inspect each variable to see if it will collide with any other variables used after the code has been changed. However, for a conflicting variable `foo`, we will always rename it `foo_1`, even if another variable has also been renamed to `foo_1`. This PR stores the original names of variables during the rename operation so that the numbering can be done correctly.

### CODE REVIEW

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 1]
```diff
@@ -448,7 +442,7 @@ namespace ts.codefix {
         return createNodeArray([]);
     }
 
-    function getLastCallSignature(type: Type, checker: TypeChecker): Signature {
+    function getLastCallSignature(type: Type, checker: TypeChecker): Signature | undefined {
```
Comment (andy-ms) [inline src/services/codefixes/convertToAsyncFunction.ts]: The reason this compiled before is that `type` is declared non-optional. But it's tested for. Either the test is unnecessary, or `type` should be optional and some argument to this function is typed as non-optional when it shouldn't be.

File: src/services/utilities.ts [hunk 2]
```diff
@@ -1671,7 +1671,7 @@ namespace ts {
         }
 
         if (clone && !includeTrivia) suppressLeadingAndTrailingTrivia(clone);
-        if (callback && node) callback(node!, clone);
+        if (callback && node && clone) callback(node!, clone);
```
Comment (andy-ms) [inline src/services/utilities.ts]: Looks like this wasn't detected due to a compiler bug. #27050

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts [hunk 3]
```diff
@@ -13,5 +13,5 @@ function /*[#|*/f/*|]*/(): Promise<string> {
 async function f(): Promise<string> {
     const resp = await fetch("https://typescriptlang.org");
     var blob = resp.blob().then(blob_1 => blob_1.byteOffset).catch(err => 'Error');
-    return blob_1.toString();
+    return blob_2.toString();
```
Comment (andy-ms) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts]: This isn't right, `blob_2` was never declared.

Comment (uniqueiniquity) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts]: FWIW, the previous name of `blob_1` wasn't correct either. This is a different bug, but I can wrap it in here too so we leave it in a good state.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 1 above)
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: @andy-ms If `callSignatures` exists, is it guaranteed to have non-zero length? That was more of my motivation for the return value possibly being `undefined`.

Comment (andy-ms) [reply src/services/codefixes/convertToAsyncFunction.ts]: Oh, right. I wouldn't count on it. There is a `lastOrUndefined` function which has the correct type for potentially empty arrays.

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 4]
```diff
@@ -81,19 +82,14 @@ namespace ts.codefix {
...
-                forEachChild(statement, function visit(node: Node) {
-                    if (isCallExpression(node)) {
-                        startTransformation(node, statement);
-                    }
-                    else if (!isFunctionLike(node)) {
-                        forEachChild(node, visit);
-                    }
-                });
-            }
+            forEachChild(statement, function visit(node: Node) {
```
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Removed.

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 5]
```diff
@@ -182,26 +178,27 @@ namespace ts.codefix {
                 // if the identifier refers to a function we want to add the new synthesized variable for the declaration (ex. blob in let blob = res(arg))
                 // Note - the choice of the last call signature is arbitrary
                 if (lastCallSignature && lastCallSignature.parameters.length && !synthNamesMap.has(symbolIdString)) {
+                    const name = lastCallSignature.parameters[0].name;
                     const synthName = getNewNameIfConflict(createIdentifier(lastCallSignature.parameters[0].name), allVarNames);
```
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Replaced. Still investigating if the new identifier is strictly needed here.

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts (hunk 3 above)
Comment (uniqueiniquity) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts]: Fixed.

**Comment by amcasey** [comment]
>     export function getSynthesizedDeepCloneWithRenames<T extends Node | undefined>(node: T, includeTrivia = true, renameMap?: Map<Identifier>, checker?: TypeChecker, callback?: (originalNode: Node, clone: Node) => any): T {

Maybe return early if `node` is undefined?

---
Refers to: src/services/utilities.ts:1657 in 95e5f7d. [](commit_id = 95e5f7d55a5a75581093024b5c8419625db2ff9b, deletion_comment = False)

File: src/testRunner/unittests/convertToAsyncFunction.ts [hunk 6]
```diff
@@ -1194,6 +1194,20 @@ const [#|foo|] = function () {
...
 `);
 
+    _testConvertToAsyncFunction("convertToAsyncFunction_catchBlockUniqueParams", `
+function [#|f|]() {
+	return Promise.resolve().then(x => 1).catch(x => "a").then(x => !!x); 
+} 
+`);
+
+    _testConvertToAsyncFunction("convertToAsyncFunction_bindingPattern", `
+function [#|f|]():Promise<void> {
```
Comment (amcasey) [inline src/testRunner/unittests/convertToAsyncFunction.ts]: >:Promise<void> [](start = 17, length = 14)

Is the return type important?  It appears to be preventing the creation of a corresponding JS test.

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_bindingPattern.ts [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+    return fetch('https://typescriptlang.org').then(res);
+}
+function res({ status, trailer }){
+    console.log(status);
+} 
+
+// ==ASYNC FUNCTION::Convert to async function==
+
+async function f():Promise<void> {
+    const __0 = await fetch('https://typescriptlang.org');
```
Comment (amcasey) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_bindingPattern.ts]: >__0 [](start = 10, length = 3)

This name seems less than ideal.

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_catchBlockUniqueParams.js [hunk 8]
```diff
@@ -0,0 +1,19 @@
+// ==ORIGINAL==
+
+function /*[#|*/f/*|]*/() {
+	return Promise.resolve().then(x => 1).catch(x => "a").then(x => !!x); 
+} 
+
+// ==ASYNC FUNCTION::Convert to async function==
+
+async function f() {
+	let x_2;
```
Comment (amcasey) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_catchBlockUniqueParams.js]: >x_2 [](start = 5, length = 3)

Nit: It's kind of weird that the catch parameter got "1".

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts (hunk 3 above)
Comment (amcasey) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_InnerVarNameConflict.ts]: I would have guessed `blob_2` was of type `void` (based only on my intuition and not any knowledge of TS or promises).

---
In reply to: [217201225](https://github.com/Microsoft/TypeScript/pull/27031#discussion_r217201225) [](ancestors = 217201225)

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_MultipleReturns2.ts [hunk 9]
```diff
@@ -21,6 +21,6 @@ async function f(): Promise<void> {
     }
     const resp = await x;
     var blob = resp.blob().then(blob_1 => blob_1.byteOffset).catch(err => 'Error');
-    const res_1 = await fetch("https://micorosft.com");
+    const res_2 = await fetch("https://micorosft.com");
```
Comment (amcasey) [inline tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_MultipleReturns2.ts]: >micorosft [](start = 39, length = 9)

Nit: typo

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_catchBlockUniqueParams.js (hunk 8 above)
Comment (uniqueiniquity) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_catchBlockUniqueParams.js]: That's just because we rename from left to right in the pre-fixed form. Not sure if that's worth fixing at this point.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Now only creating new identifier if existing can't be reused.

File: src/testRunner/unittests/convertToAsyncFunction.ts (hunk 6 above)
Comment (uniqueiniquity) [reply src/testRunner/unittests/convertToAsyncFunction.ts]: Removed.

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_bindingPattern.ts (hunk 7 above)
Comment (uniqueiniquity) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_bindingPattern.ts]: Fixed.

File: tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_MultipleReturns2.ts (hunk 9 above)
Comment (uniqueiniquity) [reply tests/baselines/reference/convertToAsyncFunction/convertToAsyncFunction_MultipleReturns2.ts]: Fixed.

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 10]
```diff
@@ -182,26 +178,27 @@ namespace ts.codefix {
...
                 else if (node.parent && (isParameter(node.parent) || isVariableDeclaration(node.parent))) {
 
                     // if the identifier name conflicts with a different identifier that we've already seen
-                    if (allVarNames.some(ident => ident.identifier.text === node.text && ident.symbol !== symbol)) {
+                    if (allVarNames.some(ident => ident.originalName === node.text && ident.symbol !== symbol)) {
                         const newName = getNewNameIfConflict(node, allVarNames);
                         identsToRenameMap.set(symbolIdString, newName.identifier);
                         synthNamesMap.set(symbolIdString, newName);
-                        allVarNames.push({ identifier: newName.identifier, symbol });
+                        allVarNames.push({ identifier: newName.identifier, symbol, originalName: node.text });
```
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Extracted reused property access to local.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 1 above)
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Changed to use `lastOrUndefined`.
