### PR TITLE
fix(44880): Control Flow Analysis of Aliased Conditions doesn't work with --useUnknownInCatchVariables

### LINKED ISSUE #44880: Control Flow Analysis of Aliased Conditions doesn't work with `--useUnknownInCatchVariables`
# Bug Report

### 🔎 Search Terms
Control Flow Analysis try catch unknown

### 🕗 Version & Regression Information
v4.4.0-dev.20210702

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useUnknownInCatchVariables=true&ts=4.4.0-dev.20210702#code/PTAEAEFcGcFMFUB2BrRB7A7ogkogwgIYAuAxgBYBqBATgJYEBGANrNAFyhHWSwBQvXAJ6gA3vwC+oEsXIAKWAEpRvUKqlpE0IqFrQAyl1qIA5qAC8nQQAdYaAGahY5sxYDkWuidcq1tB7N0DT2MlMTVwxwA6IjR4KxtqQjhZJRBQAHkGACtYEm1dUHtLG1BXSBR0LG9w8R9VP1BZImtbBycXNw8jY1dQuojYaNj42ESCZNSwdEdqajRqftrxIA)

### 💻 Code

```ts
try {

} catch(e) {
    const isString = typeof e === 'string'
    if (isString) {
        e.toUpperCase() // Object is of type 'unknown'
    }
    if (typeof e === 'string') {
        e.toUpperCase() // no error
    }
}
```

### 🙁 Actual behavior

`e` isn't narrowed to `string`

### 🙂 Expected behavior

`e` should be narrowed like it does when the condition is inline, as described [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#cfa-aliased-conditions)

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #44880

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -23132,9 +23132,17 @@ namespace ts {
...
-                case SyntaxKind.Identifier:
+                case SyntaxKind.Identifier: {
                     const symbol = getResolvedSymbol(node as Identifier);
-                    return isConstVariable(symbol) || !!symbol.valueDeclaration && getRootDeclaration(symbol.valueDeclaration).kind === SyntaxKind.Parameter && !isParameterAssigned(symbol);
+                    if (isConstVariable(symbol)) {
+                        return true;
+                    }
+                    if (symbol.valueDeclaration) {
+                        const decl = getRootDeclaration(symbol.valueDeclaration);
+                        return isParameter(decl) && !isParameterAssigned(symbol) || isVariableDeclaration(decl) && isCatchClause(decl.parent);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:23142]: Catch variables can be reassigned too. What happens with a test like

```ts
try {} catch (err) {
  const isString = typeof err === "string";
  err = 0;
  if (isString) {
    err;
  }
}
```

Comment (a-tarasyuk) [reply src/compiler/checker.ts:23142]: @andrewbranch Yes, can be. This is a bit tricky case, with a catch clause. Currently, CFA supports only constants.

```ts
declare const a;
const isString = typeof a === "string";
if (isString) {
    a; // string
}
```

```ts
declare let a;
const isString = typeof a === "string";
if (isString) {
    a; // any
}
```

```ts
declare let a;
const isString = typeof a === "string";
a = 1;
if (isString) {
    a; // still any
}
```

I don't know what the best way to resolve this issue. What do you think?

Comment (andrewbranch) [reply src/compiler/checker.ts:23142]: I read `isParameter(decl) && !isParameterAssigned(symbol)` to mean that CFA also works for function parameters, which feel very similar to catch clause variables, as long as they’re not reassigned anywhere in the function body. It would be nice if catch clause variables worked the same way as function parameters, but I don’t know how easy it would be to reuse `isParameterAssigned` for catch clauses.

Comment (a-tarasyuk) [reply src/compiler/checker.ts:23142]: Oke, I'll check, thanks

**Review by andrewbranch — APPROVED** [review]

**Comment by yseymour** [comment]
Does this fix the case where the catch variable remains `unknown` after being reassigned?

([Playground](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210910#code/GYVwdgxgLglg9mABABwE4zFAFAU1auVALkQFF9CBKRAb0QgQGc4AbHAOjwNVwtXYC2ORowCGAcxzUAvgChQkWAkTA4cLNRqzEOxFFQBPWtt2moACwIB3RAHJRiRvozjbAbhM65piKKgRzRF5uTU9TRC5CRABeRDAcG3JuLAADABIaSNRpFMoPcN00DGwsvLC5aSA))

**Comment by andrewbranch** [comment]
No, that’s https://github.com/microsoft/TypeScript/issues/43584

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -24272,37 +24277,39 @@ namespace ts {
...
+                (isFunctionLike(node) || isCatchClause(node)) && !!(getNodeLinks(node).flags & NodeCheckFlags.AssignmentsMarked));
         }
 
-        function markParameterAssignments(node: Node) {
+        function markNodeAssignments(node: Node) {
             if (node.kind === SyntaxKind.Identifier) {
                 if (isAssignmentTarget(node)) {
                     const symbol = getResolvedSymbol(node as Identifier);
-                    if (symbol.valueDeclaration && getRootDeclaration(symbol.valueDeclaration).kind === SyntaxKind.Parameter) {
+                    const decl = symbol.valueDeclaration ? getRootDeclaration(symbol.valueDeclaration): undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts:24305]: I find this easier to read, but it's fine to leave it if you disagree:
```suggestion
                    const decl = symbol.valueDeclaration && getRootDeclaration(symbol.valueDeclaration);
```

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -23132,9 +23132,14 @@ namespace ts {
...
             switch (node.kind) {
-                case SyntaxKind.Identifier:
+                case SyntaxKind.Identifier: {
                     const symbol = getResolvedSymbol(node as Identifier);
-                    return isConstVariable(symbol) || !!symbol.valueDeclaration && getRootDeclaration(symbol.valueDeclaration).kind === SyntaxKind.Parameter && !isParameterAssigned(symbol);
+                    if (isConstVariable(symbol)) {
+                        return true;
+                    }
+                    const decl = symbol.valueDeclaration ? getRootDeclaration(symbol.valueDeclaration) : undefined;
+                    return !!decl && (isParameter(decl) || isCatchClauseVariableDeclaration(decl)) && !isSymbolAssigned(symbol);
```
Comment (sandersn) [inline src/compiler/checker.ts:23141]: This predicate (except `!isSymbolAssigned`) is now duplicated. Do you think it's worth extracting to a function?

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks good.
Just a couple of minor refactoring suggestions; let me know what you think about them.

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts (hunk 3 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Good point. Thanks. I've moved it to function.
