### PR TITLE
Find Source Definition

### LINKED ISSUE #6209: Enable Go to Implementation in Typescript Editors
Could you provide a way for Typescript Editors to list the implementations of a type?
This would definitely help developer productivity to be able to find implementations of types faster. 

For example, in the Atom Editor atom-typescript plugin you can press F12 to 'Go to Declaration' which as currently implemented you often arrive at the typescript .d.ts file which has the function signature but not the actual implementation. 

Since the Typescript parser often generates the d.ts files from the .ts implementation files. Could that association between the d.ts and .ts files be preserved (perhaps output with a typescript compiler option) so that Typescript editors could take developers to a list of the implementing classes or functions?

I opened a similar request for the Atom-typescript editor, but they indicate that they cannot implement this without Typescript parser support:
TypeStrong/atom-typescript#790

### LINKED ISSUE #38474: Go to definition for nodejs javascript file broken by existance of `.d.ts`
- VSCode Version: 1.44.2
- OS Version:  Ubuntu

Steps to Reproduce:

1. Go to a nodejs project that has multiple dependencies in node_modules
2. Hit go to definition on a javascript `require` statement
3. Expect to be taken to javascript source code for that module
4. Sometimes taken to foreign `.d.ts` file.

Does this issue occur when all extensions are disabled?: Yes

## Example go to definition that works

uuid-works

## Example of go to definition thats broken

promise-broken

## Example of go to definition can be made to work for `is-promise`

The `is-promise` javascript library has an `index.d.ts` file which breaks go to definition because it exists.

I can remove this file by running `rm node_modules/is-promise/index.d.ts`

promise-working

It's really frustrating that `go to definition` only works if the `index.d.ts` does not exist.

One work around would be to `rm ./node_modules/**/*.d.ts` 

## Possible duplicate 

https://github.com/microsoft/vscode/issues/82054

This issue is very similar to the above.

It was closed because

> The reason why we cannot jump to 3rd party JS is that JS's dynamic nature makes it impossible

This is not correct, i manually deleted the `index.d.ts` file from `node_modules/is-promise` and got exactly the behavior that i wanted.

The vscode go to definition for nodejs javascript works in almost all cases except when a `.d.ts` file exists.

It would be great if vs code has a flag to ignore `*.d.ts` files for when going to definition in a javascript project.

### PR DESCRIPTION
**Pull request by andrewbranch**
This PR adds a new command similar to Go To Definition, but includes locations in JS files that would normally not be considered, excludes all ambient locations, and potentially uses some heuristics to find likely results in JS files that cannot be analyzed with our binder and type checker due to complex module wrappers or other constructs we don’t understand. The process when invoked is:

1. Run go-to-definition on something. If it returns only ambient definitions that are alias targets, or stops at import aliases that couldn’t resolve to anything, continue with next steps. Otherwise, return any non-ambient definitions found.
2. Spin up a temporary project with a single root file, the one in the requesting location, using a new internal compiler setting that prevents module resolution from considering .d.ts files. This lets us resolve to JS files that would normally be “shadowed” by .d.ts declarations.
3. With that project, try go-to-def again, this time skipping any non-alias work and returning best-effort file results for things like imports where the module specifier resolved, but the specific export wasn’t found, or the target file wasn’t even recognized as a module.
4. For any results that were “unverified” (those best-effort file results), see if the requesting location gave us a strong indicator of what the declaration name we’re looking for is (i.e., can we locally resolve to a named import). If so, try a find-all-refs-like text search on the file returned, and from those results get the top-most declarations by that name. (This is obviously _highly_ approximate and needs some vetting as to whether it’s worth doing at all—at the very least, it needs corresponding editor UI to indicate that these results are not much better than a text search. I attempted to filter these declarations further by symbol flags and/or basic type analysis, but that immediately proved unreliable in the face of exports created by factory functions with poor JSDoc annotations.)

I attempted to tack this onto go-to-implementation instead of its own command, but go-to-implementation is extremely weird and did not play nicely with this code. This is much more go-to-definition-like, but I don’t think we can simply augment or replace go-to-definition because we want go-to-def to be super fast and reliable, and I think we _don’t_ want this command returning anything ambient. However, for purposes of gathering public feedback in the meantime, I think I’m going to make a build that replaces go-to-def with this logic. (Otherwise, users would have to use a special build of VS Code in order to send the new command.)

Fixes #6209
Fixes #38474

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by amcasey** [comment]
One case to consider as we think about how this functionality should be triggered is what ctrl-click should do.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@amcasey I’m not sure I understand. Ctrl+click is go-to-definition, with a fallback to find-all-refs, right? (It’s ⌘+click for me.) There are no cases where go-to-definition returns nothing but this command returns something. So unless we decide to simply merge these results with go-to-definition, I’m not sure there’s an opportunity to do anything different with ctrl+click. Due to the need to spin up a new project and do some module resolution, this new command is noticeably slower than go-to-definition, so the behavior where you get near-instant feedback as to what is ctrl+clickable in the form of an underline while you hover doesn’t feel as good with this.

**Comment by andrewbranch** [comment]
If we can't find some specific declaration, but we have good reason to believe it exists somewhere in a particular package we can find, should we just open the `main` entrypoint of that package?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9098,7 +9098,7 @@ namespace ts {
                         }
                     }
                     const sourceTypes = some(constructorTypes, t => !!(t.flags & ~TypeFlags.Nullable)) ? constructorTypes : types; // TODO: GH#18217
-                    type = getUnionType(sourceTypes!, UnionReduction.Subtype);
+                    type = getUnionType(sourceTypes!);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:9101]: If you have a JS file like:

```js
if (process.env.NODE_ENV === "production") {
  module.exports = require("./foo.min.js");
} else {
  module.exports = require("./foo.js");
}
```

If one module is a subtype of the other, go-to-definition on an import/require of this file was previously going straight into the supertype module. By not eagerly doing subtype reduction here, the services are able to retain the information that the export branches off into these two separate modules. I traced this line of code all the way back to the beginning of JS support, long before `UnionReduction.Literal` existed. At the time it was introduced, `getUnionType` did subtype reduction by default. Later, that default was flipped, and this call site opted into it as a mechanical migration of the default. Even later, the default became `UnionReduction.Literal`, but this call site was of course ignored. No pre-existing tests were impacted by my changing it now, so my assumption is this does not actually have an intentional reason to do something other than the default.

File: src/compiler/moduleNameResolver.ts [hunk 2]
```diff
@@ -69,7 +69,8 @@ namespace ts {
         JavaScript, /** '.js' or '.jsx' */
         Json,       /** '.json' */
         TSConfig,   /** '.json' with `tsconfig` used instead of `index` */
-        DtsOnly /** Only '.d.ts' */
+        DtsOnly,    /** Only '.d.ts' */
+        TsOnly,     /** '.[cm]tsx?' but not .d.ts variants */
```
Comment (amcasey) [inline src/compiler/moduleNameResolver.ts:73]: `\.` 😛

Comment (amcasey) [inline src/compiler/moduleNameResolver.ts:73]: I'm sure you've already bike-shedded this, but I think I'd prefer "TypeScriptNoDts".

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -2563,14 +2567,14 @@ namespace ts {
         return decl.kind === SyntaxKind.FunctionDeclaration || isVariableDeclaration(decl) && decl.initializer && isFunctionLike(decl.initializer);
     }
 
-    export function tryGetModuleSpecifierFromDeclaration(node: AnyImportOrRequire): string | undefined {
+    export function tryGetModuleSpecifierFromDeclaration(node: AnyImportOrBareOrAccessedRequire): StringLiteralLike | undefined {
         switch (node.kind) {
             case SyntaxKind.VariableDeclaration:
-                return node.initializer.arguments[0].text;
+                return findAncestor(node.initializer, (node): node is RequireOrImportCall => isRequireCall(node, /*requireStringLiteralLikeArgument*/ true))?.arguments[0];
```
Comment (amcasey) [inline src/compiler/utilities.ts:2573]: Would it be worthwhile to short-circuit the search when you get to `node`?

File: src/compiler/utilities.ts [hunk 4]
```diff
@@ -3154,6 +3168,7 @@ namespace ts {
             case SyntaxKind.ExportSpecifier:
             case SyntaxKind.ExportAssignment:
             case SyntaxKind.ImportEqualsDeclaration:
+            case SyntaxKind.NamespaceExport:
```
Comment (amcasey) [inline src/compiler/utilities.ts:3171]: This is just a bug fix?

File: src/server/project.ts [hunk 5]
```diff
@@ -5,6 +5,7 @@ namespace ts.server {
         Configured,
         External,
         AutoImportProvider,
+        SingleCommand,
```
Comment (amcasey) [inline src/server/project.ts:8]: ❤️

File: src/server/project.ts [hunk 6]
```diff
@@ -1773,6 +1774,39 @@ namespace ts.server {
...
+                lib: ts.emptyArray,
+                noLib: true,
+            };
+            const project = new SingleCommandProject(this.projectService, this.documentRegistry, options);
+            for (const fileName of rootFileNames) {
+                project.addRoot(this.getScriptInfo(fileName)!);
+            }
+            cb(
+                project,
+                fileName => {
```
Comment (amcasey) [inline src/server/project.ts:1798]: Why is this provided as a callback?  It looks like something the caller could handle since, AFAICT, it only closes over `project`?

File: src/server/protocol.ts [hunk 7]
```diff
@@ -83,6 +83,9 @@ namespace ts.server.protocol {
         SignatureHelp = "signatureHelp",
         /* @internal */
         SignatureHelpFull = "signatureHelp-full",
+        SourceDefinitionAndBoundSpan = "sourceDefinitionAndBoundSpan",
```
Comment (amcasey) [inline src/server/protocol.ts:86]: I think we may already have discussed this but, unfortunately, I've forgotten.  Why wouldn't this be modelled on `definition[-full]`?  I believe the primary (only?) difference is that `definitionAndBoundSpan` includes the span for underlining, which this command seems unlikely to require, given the expected perf.

File: src/services/findAllReferences.ts [hunk 8]
```diff
@@ -1337,6 +1337,30 @@ namespace ts.FindAllReferences {
...
+            const candidates = filter(getPossibleSymbolReferenceNodes(sourceFile, declarationName), name => !!getDeclarationFromName(name));
+            return candidates.reduce((topMost, decl) => {
+                const depth = getDepth(decl);
+                if (!some(topMost.declarationNames) || depth === topMost.depth) {
+                    topMost.declarationNames.push(decl);
+                }
+                else if (depth < topMost.depth) {
+                    topMost.declarationNames = [decl];
+                }
+                topMost.depth = depth;
```
Comment (amcasey) [inline src/services/findAllReferences.ts:1350]: I might be blanking, but it seems like you wouldn't want to do this if `depth > topMost.depth`?

File: src/server/session.ts [hunk 9]
```diff
@@ -1219,6 +1220,145 @@ namespace ts.server {
...
+                    const jsDefinitions = ls
+                        .getDefinitionAndBoundSpan(file, position, /*searchOtherFilesOnly*/ true)
+                        ?.definitions
+                        ?.filter(d => toNormalizedPath(d.fileName) !== file);
+                    if (some(jsDefinitions)) {
+                        for (const jsDefinition of jsDefinitions) {
+                            if (jsDefinition.unverified) {
+                                const refined = tryRefineDefinition(jsDefinition, project.getLanguageService().getProgram()!, ls.getProgram()!);
+                                if (some(refined)) {
+                                    for (const def of refined || emptyArray) {
```
Comment (amcasey) [inline src/server/session.ts:1251]: `some` doesn't make the `|| emptyArray` redundant?

File: src/server/session.ts [hunk 10]
```diff
@@ -1219,6 +1220,145 @@ namespace ts.server {
...
+                                        pushIfUnique(definitions, def, documentSpansEqual);
```
Comment (amcasey) [inline src/server/session.ts:1252]: https://github.com/microsoft/TypeScript/pull/48169

File: src/server/session.ts [hunk 11]
```diff
@@ -1219,6 +1220,145 @@ namespace ts.server {
...
+                        }
+                    }
+                    else {
+                        const ambientCandidates = definitions.filter(d => toNormalizedPath(d.fileName) !== file && d.isAmbient);
+                        for (const candidate of ambientCandidates) {
+                            const fileNameToSearch = findImplementationFileFromDtsFileName(candidate.fileName, file, noDtsProject);
+                            if (!fileNameToSearch || !ensureRoot(fileNameToSearch)) {
+                                continue;
+                            }
+                            const auxiliaryProgram = ls.getProgram()!;
```
Comment (amcasey) [inline src/server/session.ts:1267]: Nit: singleCommandProgram

File: src/services/goToDefinition.ts [hunk 12]
```diff
@@ -28,36 +28,69 @@ namespace ts.GoToDefinition {
...
-        const symbol = getSymbol(node, typeChecker);
+        let { symbol, failedAliasResolution } = getSymbol(node, typeChecker);
+        let fallbackNode = node;
+
+        if (searchOtherFilesOnly && failedAliasResolution) {
+            // We couldn't resolve the specific import, try on the module specifier.
+            const importDeclaration = findAncestor(node, isAnyImportOrBareOrAccessedRequire);
+            const moduleSpecifier = importDeclaration && tryGetModuleSpecifierFromDeclaration(importDeclaration);
+            if (moduleSpecifier) {
+                ({ symbol, failedAliasResolution } = getSymbol(moduleSpecifier, typeChecker));
```
Comment (amcasey) [inline src/services/goToDefinition.ts:51]: Nit: what's up with the parens?

**Review by amcasey — COMMENTED** [review]
Initial comments.  Generally LGTM

File: src/server/project.ts (hunk 6 above)
Comment (andrewbranch) [reply src/server/project.ts:1798]: To make extra sure nobody tries to keep `project` open (or forgets to close it) beyond the synchronous execution of the single command.

File: src/services/goToDefinition.ts (hunk 12 above)
Comment (andrewbranch) [reply src/services/goToDefinition.ts:51]: The binding pattern parses as a block without them. This construct needs to be forced into an expression construct.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/server/project.ts [hunk 13]
```diff
@@ -1773,6 +1774,39 @@ namespace ts.server {
...
+                    const info = project.getScriptInfo(fileName);
+                    if (!info) return false;
+                    if (!project.containsScriptInfo(info)) {
+                        project.addRoot(info);
+                        project.updateGraph();
+                    }
+                    return true;
+                }
+            );
+            project.close();
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/project.ts:1815]: We can, but I was concerned about increasing the complexity and the potential for mistakes with respect to the project’s lifecycle. It would also add more file watchers for failed lookups, which I’ve currently short-circuited since the project exists only for a moment in a synchronous function. But if you think it’s worth it, I’m open to trying it.

**Comment by andrewbranch** [comment]
@sheetalkamat I’m now keeping the auxiliary project alive as you suggested. I’m not sure if I need to do anything else with its lifecycle besides close it when the main project is closed. Maybe handle when the main project’s compiler options change? What else?

File: src/server/project.ts [hunk 14]
```diff
@@ -1780,6 +1788,46 @@ namespace ts.server {
...
+            enumerateInsertsAndDeletes<NormalizedPath, NormalizedPath>(
+                rootFileNames.map(toNormalizedPath),
+                this.noDtsResolutionProject.getRootFiles(),
+                compareStringsCaseInsensitive,
+                pathToAdd => {
+                    const info = this.noDtsResolutionProject!.getScriptInfo(pathToAdd);
+                    if (info) {
+                        this.noDtsResolutionProject!.addRoot(info, pathToAdd);
+                    }
+                },
```
Comment (sheetalkamat) [inline src/server/project.ts:1819]: File change will cause it to schedule update graph.. You probably just dont want to schedule it and do it on demand instead.

File: src/server/project.ts [hunk 15]
```diff
@@ -1780,6 +1788,46 @@ namespace ts.server {
...
+                pathToRemove => {
+                    // It may be preferable to remove roots only once project grows to a certain size?
+                    const info = this.noDtsResolutionProject!.getScriptInfo(pathToRemove);
+                    if (info) {
+                        this.noDtsResolutionProject!.removeRoot(info);
```
Comment (sheetalkamat) [inline src/server/project.ts:1824]: can you add a test where file opened from this project moves to inferred project and out of it correctly..

File: src/server/project.ts [hunk 16]
```diff
@@ -1780,6 +1788,46 @@ namespace ts.server {
         getIncompleteCompletionsCache() {
             return this.projectService.getIncompleteCompletionsCache();
         }
+
+        /*@internal*/
```
Comment (sheetalkamat) [inline src/server/project.ts:1792]: In project.setCompilerOptions you would need to update the options for this project as well?

File: src/server/project.ts [hunk 17]
```diff
@@ -1780,6 +1788,46 @@ namespace ts.server {
         getIncompleteCompletionsCache() {
             return this.projectService.getIncompleteCompletionsCache();
         }
+
+        /*@internal*/
+        getNoDtsResolutionProject(rootFileNames: readonly string[]): Project {
```
Comment (sheetalkamat) [inline src/server/project.ts:1793]: May be assert this is happening only in SemanticMode ?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/server/project.ts (hunk 14 above)
Comment (andrewbranch) [reply src/server/project.ts:1819]: I’m not sure I understand—any time this runs, we are about to query the language service, so I need `updateGraph` to run after this batch of inserts/deletes.

Comment (sheetalkamat) [reply src/server/project.ts:1819]: Sorry for not being clear..  I am not talking about this file add and delete. I mean that after this operation if say you change a file thats included in this project, editor services will schedule update graph.. you would want to change ScheduleUpdateGraph as noop so its not updating in background.. i forget if we are already doing it for auto import provider but it would benefit from that too.. (you still want to mark project dirty etc but not schedule things)
There is scheduling for invalidating failed lookup locations as well which can be deferred till needed. 

So https://github.com/microsoft/TypeScript/blob/main/src/server/editorServices.ts#L993 and https://github.com/microsoft/TypeScript/blob/main/src/server/project.ts#L527

Comment (andrewbranch) [reply src/server/project.ts:1819]: Ah, that makes sense. Will look into that, thanks.

File: src/server/project.ts (hunk 15 above)
Comment (andrewbranch) [reply src/server/project.ts:1824]: Hm, I had forgotten about this part of making the AutoImportProviderProject, but for that one, a ScriptInfo can be part an InferredProject _and_ the AutoImportProviderProject since the latter is something used in the background; it shouldn’t change the experience for a user opening a random file that happens to be part of the auto-imports processing. I think we want to do the same thing for this kind of project.

Comment (sheetalkamat) [reply src/server/project.ts:1824]: If i remember correctly it might need some extra work as it checks if scriptinfo is part of any project all all.. (containingProjects) on script info so if we havent done something special it might result in some wierd state
The state would be interesting is when you open file thats in AutoImport or auxillary project 

There is also some place where we try to refresh(collect script info or something when we close some other file ) and see if file needs to be moved out or in to inferred project and that would need update too.. because all of those used containingProjects.length or something like that.

Comment (andrewbranch) [reply src/server/project.ts:1824]: I believe I handled all of this for AutoImportProvider; it’s pretty simple to update it.

File: src/server/project.ts (hunk 14 above)
Comment (andrewbranch) [reply src/server/project.ts:1819]: I’m not quite sure what to do with `scheduleInvalidateResolutionsOfFailedLookupLocations`. `updateGraphWorker` ultimately calls `resolutionCache.invalidateResolutionsOfFailedLookupLocations()`, so can I just make `AuxiliaryProject.scheduleInvalidateResolutionsOfFailedLookupLocations` a no-op, since the work it’s supposed to schedule seems to happen as part of `updateGraph`?

File: src/server/project.ts (hunk 15 above)
Comment (andrewbranch) [reply src/server/project.ts:1825]: Added a unit test that covers at least some of this if you want to take a look.

File: src/compiler/moduleNameResolver.ts [hunk 18]
```diff
@@ -1899,6 +1920,8 @@ namespace ts {
                 return extension === Extension.Json;
             case Extensions.TypeScript:
                 return extension === Extension.Ts || extension === Extension.Tsx || extension === Extension.Dts;
+            case Extensions.TsOnly:
+                return extension === Extension.Ts || extension === Extension.Tsx;
```
Comment (weswigham) [inline src/compiler/moduleNameResolver.ts:1924]: This is probably unrelated to this change, per sey, but this function probably needs to include the `.mts` and `.cts` flavor extensions in its logic. It was probably missed because it's only used in one place. :S

File: src/testRunner/unittests/tsserver/auxiliaryProject.ts [hunk 19]
```diff
@@ -0,0 +1,38 @@
...
+            assert(bJsScriptInfo.isOrphan());
+            assert(bJsScriptInfo.isContainedByBackgroundProject());
+            assert.deepEqual(bJsScriptInfo.containingProjects, [auxProject]);
+            assert.throws(() => bJsScriptInfo.getDefaultProject());
+
+            openFilesForSession([bJs], session);
+            assert(!bJsScriptInfo.isOrphan());
+            assert(bJsScriptInfo.isContainedByBackgroundProject());
+            assert.equal(bJsScriptInfo.getDefaultProject().projectKind, server.ProjectKind.Inferred);
+        });
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tsserver/auxiliaryProject.ts:36]: May be instead use baseline? 
I think instead of this you probably want to use baselines.. this becomes hard to maintain later on.. 

```ts
const session = createSession(host, { canUseEvents: true, logger: createLoggerWithInMemoryLogs() });
// Do your things here
baselineTsserverLogs("auxiliaryProject", "does not remove scrips from InferredProject", session);
```

File: src/server/project.ts (hunk 14 above)
Comment (sheetalkamat) [reply src/server/project.ts:1820]: Yes Thats the correct way to handle it..

File: src/testRunner/unittests/tsserver/auxiliaryProject.ts (hunk 19 above)
Comment (andrewbranch) [reply src/testRunner/unittests/tsserver/auxiliaryProject.ts:45]: I find this much easier to read than a server baseline because the assertions are checking exactly what's important. I added a bunch of comments to this test to help understand what's happening and why.

File: src/compiler/moduleNameResolver.ts (hunk 18 above)
Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts]: Updated

File: src/server/project.ts [hunk 20]
```diff
@@ -1780,6 +1789,51 @@ namespace ts.server {
...
+            Debug.assert(this.projectService.serverMode === LanguageServiceMode.Semantic);
+            if (!this.noDtsResolutionProject) {
+                this.noDtsResolutionProject = new AuxiliaryProject(this.projectService, this.documentRegistry, this.getCompilerOptionsForNoDtsResolutionProject());
+            }
+
+            enumerateInsertsAndDeletes<NormalizedPath, NormalizedPath>(
+                rootFileNames.map(toNormalizedPath),
+                this.noDtsResolutionProject.getRootFiles(),
+                getStringComparer(!this.useCaseSensitiveFileNames),
```
Comment (sheetalkamat) [inline src/server/project.ts:1803]: Isnt `useCaseSensitiveFileNames` function and not property

File: src/server/project.ts [hunk 21]
```diff
@@ -1920,6 +1974,31 @@ namespace ts.server {
...
+                /*watchOptions*/ undefined,
+                projectService.host,
+                /*currentDirectory*/ undefined);
+        }
+
+        isOrphan(): boolean {
+            return true;
+        }
+
+        scheduleInvalidateResolutionsOfFailedLookupLocations(): void {
```
Comment (sheetalkamat) [inline src/server/project.ts:1996]: Can we add this to AutoImportProviderProject too.. Thanks

File: src/server/project.ts [hunk 22]
```diff
@@ -1920,6 +1977,31 @@ namespace ts.server {
...
```
Comment (sheetalkamat) [inline src/server/project.ts:1999]: Internal?

File: src/server/project.ts [hunk 23]
```diff
@@ -2129,6 +2211,11 @@ namespace ts.server {
             return hasSameSetOfFiles;
         }
 
+        scheduleInvalidateResolutionsOfFailedLookupLocations(): void {
```
Comment (sheetalkamat) [inline src/server/project.ts:2214]: Internal ?

**Review by sheetalkamat — APPROVED** [review]
Just need to make some of the methods internal

**Comment by andrewbranch** [comment]
Latest commits

- make `_./*|*/add` work when `_` itself can only be resolved with heuristics
- rename the command `FindSourceDefinition`, dropping the bound span part of the response as it’s not needed.

**Comment by johnsoncodehk** [comment]
Could we expose `findSourceDefinition` for language service API to make it available for LSP?

**Comment by johnsoncodehk** [comment]
@andrewbranch I hope it can use in embedded typescript language for Vue. (For example: https://github.com/johnsoncodehk/volar-starter/blob/e4f6d9808181f4533811c1aafc4b6afea1f68598/src/components/HelloWorld.vue#L26-L30)

For `Go to Definition` and `Go to Type Definition` features, I using `getDefinitionAndBoundSpan` and `getTypeDefinitionAtPosition` API of TS language service implemented.
- https://github.com/johnsoncodehk/volar/blob/90d370e82817afe011c8b8bd0a7d645464d45101/packages/typescript-language-service/src/services/definition.ts#L21
- https://github.com/johnsoncodehk/volar/blob/90d370e82817afe011c8b8bd0a7d645464d45101/packages/typescript-language-service/src/services/typeDefinition.ts#L20

I'm also expected a new `getSourceDefinitionAndBoundSpan` or `getSourceDefinitionAtPosition` API.

(btw `Go to Source Definition` is not specification of LSP, so I need to implement it bypass LSP.)

**Comment by andrewbranch** [comment]
It’s simply not possible to put this functionality on the LanguageService object (or, it would be a significant violation of the LS’s scope of concerns). At minimum you would need to create a _second_ language service (which creates a second Program and TypeChecker!). It would take a bit of work on our end to abstract what I put directly into TS Server into some kind of public API that could be used independently of the project system. This is an experimental API so it’s not going to happen right now, but if you want to open a new suggestion issue for doing this, we’ll keep an eye on it and could discuss some of the design challenges. Thanks!

**Comment by johnsoncodehk** [comment]
> At minimum you would need to create a second language service (which creates a second Program and TypeChecker!).

Actually this is absolutely acceptable 😅, we already have multiple language server & language service instances in order to prevent auto-complete request from being blocked by incomplete diagnostics request. (https://github.com/johnsoncodehk/volar/discussions/393#discussioncomment-1213736)

Great to see it experimentally added to the language service API, this feature will be very welcome in the Vue community, it solves some common DX issues in Vue projects (For example: https://github.com/johnsoncodehk/volar/issues/1226). It doesn't matter if it will be removed anytime in the future, I can adapt the code quickly.

> if you want to open a new suggestion issue for doing this, we’ll keep an eye on it and could discuss some of the design challenges.

Of course, thanks in advance!
