### PR TITLE
Adjust scanning of keywordy jsx namespace names, add grammar error for jsx dotted names containing namespace names

### LINKED ISSUE #42963: Jsx namespaced name and attributes
# Bug Report

### 🔎 Search Terms

- jsx
- ast
- syntax
- JSXNamespacedName
- typescript 4.2

### 🕗 Version & Regression Information

- This changed between versions 4.2.0 and 4.3.x

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=next#code/CYUwxgNghgTiAEA7KBbEBnADlMCBSAygBrwDeAsAFDzwCWiALiDAGY4ICSjM96tYAUQgg0jdGSo0aAcgYALWugBcAI2lL4URAE8A3JKnSVSsOonUplgB4at2gzQC++izKiqzdl06qOqVAB53FQA+AIB6YJCXQOMwADorMPC4xOj-SgD5RVVk7OVQlyA)
https://github.com/typescript-eslint/typescript-eslint/pull/3112

### 💻 Code

```ts
declare namespace JSX {
  interface IntrinsicElements {
    'this:b': any;
    'b:c': {
        x: any
    };
    'a:b': any;
  }
}

<a:b></a:b>;  // is working
<b:c.x></b:c.x>;  // should fail, there is no syntax error reported, and only issue is related to incorrect type
<this:b></this:b>; // its failing but there is no syntax error reported
```

### 🙁 Actual behavior

Invalid syntax is not reported as such. 

`this:b` in AST is reporter as `ThisExpression`, and has range of `this:b`

when code above is run in preserve mode, this syntax is generated
```ts
<a:b></a:b>;
<b:c.x></b:c.x>;
<this></this>;
```

this syntax is not allowed according to spec
```ts
<b:c.x>
```

```js
JSXMemberExpression :
    JSXIdentifier . JSXIdentifier
    JSXMemberExpression . JSXIdentifier
```
https://github.com/facebook/jsx

### 🙂 Expected behavior

We should receive some sort of error or `this:b` should be parsed as `Identifier`

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #42963

The JSX spec doesn't visibly forbid namespace names where a component of the namespace is a keyword, so those are adjusted to parse as `Identifier`s (so they then typecheck), and I've also added a grammar error on `a:b.c` and the like.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -40559,6 +40560,29 @@ namespace ts {
...
+                    }
+                    propName = propName.expression;
+                } while (isPropertyAccessExpression(propName));
+                const check = checkGrammarJsxNestedIdentifier(propName);
+                if (check) {
+                    return check;
+                }
+            }
+
+            function checkGrammarJsxNestedIdentifier(name: MemberName | ThisExpression) {
```
Comment (sandersn) [inline src/compiler/checker.ts:40579]: This doesn't have a strong reason to be nested, I think.

**Review by sandersn — APPROVED** [review]
One nit that's more of an observation in case you want to change it.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:40579]: Mostly just to avoid pollution in the containing scope, since it's only needed here. Since it doesn't close over anything, it should be just as effective as a function in the surrounding scope.
