### PR TITLE
handle union properties in when doing getOccurences\findAllReferences

### LINKED ISSUE #1772: Visual Studio crash on particular code in editor
```javascript
function f(s: string | number |  boolean) {
  s.constructor   
}
```

Copy-paste this to an empty editor => VS crashes.
VS2015 CTP5.

### PR DESCRIPTION
**Pull request by vladima**
Fixes #1772

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -3903,7 +3903,8 @@ module ts {
                 }
 
                 // if this symbol is visible from its parent container, e.g. exported, then bail out
-                if (symbol.parent) {
+                // if symbol correspond to the union property - bail out
+                if (symbol.parent || (symbol.getFlags() & SymbolFlags.UnionProperty)) {
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: This seems inappropriate; if we're in a union type, don't we want the union of scopes?

Comment (vladima) [inline src/services/services.ts]: because it will make things more complicated and we will not win a lot

Comment (DanielRosenwasser) [inline src/services/services.ts]: Alright; seems like a good short term strategy. Something to experiment with down the road.

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by mhegazy** [comment]
i would be safe and add an assert that the scope is computed correctly, i.e. the computed scope sourceFile is the same as the same as the search node sourceFile.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
@vladima  we need to take that to 1.4 as well.

File: src/services/services.ts (hunk 1 above)
Comment (JsonFreeman) [inline src/services/services.ts]: Why is symbol.parent not defined here? Doesn't the checker give union properties a parent?

Comment (vladima) [inline src/services/services.ts]: no, it does not

Comment (JsonFreeman) [inline src/services/services.ts]: Why? Maybe it should (for a long term fix).

Comment (vladima) [inline src/services/services.ts]: I believe because union property consists of multiple components (where every component might have a parent) and it makes no sense to speak about a single parent (unless it will be something new to represent union of parents for all constituents)

Comment (JsonFreeman) [inline src/services/services.ts]: I thought the parent should just be the union type.

Comment (vladima) [inline src/services/services.ts]: parent should be symbol and union type does not have associated symbol

Comment (JsonFreeman) [inline src/services/services.ts]: Ah, you're right, the property I was thinking of was SymbolLinks.unionType

**Comment by JsonFreeman** [comment]
:+1:
