### PR TITLE
Use emptyObjectType for omitted members instead of unknownType

### LINKED ISSUE #20872: Destructuring assignment makes any types when it skips some elements (regression)
cc @andy-ms 

**TypeScript Version:**  2.7.0-dev.20171223

**Code**

```ts
const [, a = ''] = ''.match('') || [];
```

**Expected behavior:**

`a` is string.

**Actual behavior:**

`a` is any.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #20872

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14507,7 +14507,7 @@ namespace ts {
                                 if (patternElement.kind !== SyntaxKind.OmittedExpression) {
                                     error(patternElement, Diagnostics.Initializer_provides_no_value_for_this_binding_element_and_the_binding_element_has_no_default_value);
                                 }
-                                elementTypes.push(unknownType);
+                                elementTypes.push(emptyObjectType);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: What about `strictNullChecks ? silentNeverType : undefinedWideningType`? Similar to what we do several lines below.

Comment (weswigham) [reply src/compiler/checker.ts]: Mmm, good call. I think I like that behavior more.
