### PR TITLE
Fix `isInJsxText` after JSXOpeningElement with type arguments

### LINKED ISSUE #34110: Generic react component (TSX) and intellisense not working
from https://github.com/microsoft/vscode/issues/82276

**TypeScript Version:**  3.7.0-dev.20191011

**Search Terms:**
- completions / suggestions
- react

**Code**
For a simple typescript react file:

```tsx
import * as React from 'react';

type Props = {
    name: string;
    isActive: boolean;
};

export const CustomComponent = <T extends {}>(props: Props) => {
    return <React.Fragment>{props.name}</React.Fragment>;
};

export const TestComponent = () => {
    return (
        <CustomComponent<string> |>
            <div></div>
        </CustomComponent>
    );
};
```

1. Place cursor at `|` in `<CustomComponent<string>`
1. Trigger completions

**Expected behavior:**
Completions for `name` and `isActive` returned

**Actual behavior:**
No completions are returned.

If you add a property such as `isActive={true}`, then a completion for `name` is returned

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #34110

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -1688,7 +1688,16 @@ namespace ts.Completions {
 
             if (contextToken.kind === SyntaxKind.GreaterThanToken && contextToken.parent) {
                 if (contextToken.parent.kind === SyntaxKind.JsxOpeningElement) {
-                    return true;
+                    // Two possibilities:
+                    //   1. <div>/**/
```
Comment (amcasey) [inline src/services/completions.ts]: Is `/**/` an existing convention for cursor location?  I missed it until I got to the explanatory text (I'd usually expect a `|` somewhere).

File: src/services/completions.ts [hunk 2]
```diff
@@ -1688,7 +1688,16 @@ namespace ts.Completions {
...
+                    // Two possibilities:
+                    //   1. <div>/**/
+                    //      - contextToken: GreaterThanToken (before cursor)
+                    //      - location: JSXElement
+                    //      - different parents (JSXOpeningElement, JSXElement)
+                    //   2. <Component<string> /**/>
+                    //      - contextToken: GreaterThanToken (before cursor)
+                    //      - location: GreaterThanToken (after cursor)
+                    //      - same parent (JSXOpeningElement)
+                    return location.parent !== contextToken.parent;
```
Comment (amcasey) [inline src/services/completions.ts]: Personally, I find parent equality a confusing way to think about this.  Would it be clearer to check whether `location.parent.kind !== SyntaxKind.JsxOpeningElement`?

File: src/services/completions.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/completions.ts]: Yeah, because it’s working fourslash syntax, and it doesn’t mess up syntax highlighting in a markdown codeblock.

File: src/services/completions.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/completions.ts]: I think both are confusing, but I’m not attached to my way. What I really wanted to do was see if `contextToken` was contained in `contextToken.parent.typeArguments`, but `typeArguments` doesn’t contain the angle brackets at all.

Comment (amcasey) [reply src/services/completions.ts]: Hmm, I thought a nicer comment would be possible for the kind check, but I've utterly failed to come up with one.  Agreed that neither is obviously clearer than the other.
