### PR TITLE
Fix bug: support non-Identifier previousToken in importFixes

### LINKED ISSUE #21499: Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isIdentifier'. at Object.cast during 'getCodeFixes'
**TypeScript Version Prefix**:
2.7.0
Note that this exception comes from an insiders builds. Since there are multiple insiders builds with the same version prefix, line numbers may be difficult to track down.

**VSCode Version**
1.20.0-insider
**command requested**
getCodeFixes
**hitting sessions**
5975
**proportion of all sessions**
0.105487094382261
**stack**
```
Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isIdentifier'.
at Object.cast in tsserver.js (line: 2438, column: 15)
at convertToImportCodeFixContext in tsserver.js (line: 78601, column: 34)
at Object.getImportCodeActions [as getCodeActions] in tsserver.js (line: 79006, column: 36)
at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:77479:3 in  (line: undefined, column: )
at Object.forEach in tsserver.js (line: 1429, column: 30)
at Object.getFixes in tsserver.js (line: 77478, column: 16)
at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83649:3 in  (line: undefined, column: )
at Object.flatMap in tsserver.js (line: 1693, column: 25)
at Object.getCodeFixesAtPosition in tsserver.js (line: 83647, column: 23)
at IOSession.Session.getCodeFixes in tsserver.js (line: 90193, column: 64)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) in tsserver.js (line: 89110, column: 61)
at IOSession.Session.executeWithRequestId in tsserver.js (line: 90349, column: 28)
at IOSession.Session.executeCommand in tsserver.js (line: 90358, column: 33)
at IOSession.Session.onMessage in tsserver.js (line: 90378, column: 35)
at Interface.<anonymous> in tsserver.js (line: 91579, column: 27)
at emitOne in events.js (line: 96, column: 13)
at Interface.emit in events.js (line: 191, column: 7)
at Interface._onLine in readline.js (line: 241, column: 10)
at Interface._normalWrite in readline.js (line: 384, column: 12)
at Socket.ondata in readline.js (line: 101, column: 10)
at emitOne in events.js (line: 96, column: 13)
at Socket.emit in events.js (line: 191, column: 7)
at readableAddChunk in _stream_readable.js (line: 178, column: 18)
at Socket.Readable.push in _stream_readable.js (line: 136, column: 10)
at Pipe.onread in net.js (line: 560, column: 20)
```

EDIT: fixed stats.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #21499
If we're at a JSX start and 'React' is missing, the current node may not be an identifier.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -726,29 +728,16 @@ namespace ts.codefix {
...
-            // The error wasn't for the symbolAtLocation, it was for the JSX tag itself, which needs access to e.g. `React`.
-            symbol = checker.getAliasedSymbol(checker.resolveName(checker.getJsxNamespace(), symbolToken.parent.tagName, SymbolFlags.Value, /*excludeGlobals*/ false));
-            symbolName = symbol.name;
-        }
-        else {
-            throw Debug.fail("Either the symbol or the JSX namespace should be a UMD global if we got here");
-        }
-
-        return getCodeActionForImport(symbol, { ...context, symbolName, kind: getUmdImportKind(compilerOptions) });
+    function getActionsForUMDImport(context: ImportCodeFixContext, isJsxNamespace: boolean): ImportCodeAction[] {
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: I'm still getting used to the way we use intersection types in TS, so pardon me if this is a dumb question: why return the extra property using an intersection type and then pass it on as a separate parameter?  Also, why not actually add it to the type?  To avoid modifying the exported interface?

File: tests/cases/fourslash/importNameCodeFixUMDGlobalReact2.ts [hunk 2]
```diff
@@ -17,5 +17,8 @@
 ////[|<div/>|]
 
 goTo.file("/a.tsx");
-verify.not
-verify.importFixAtPosition([]);
+verify.importFixAtPosition([
+`import { factory } from "./factory";
```
Comment (amcasey) [inline tests/cases/fourslash/importNameCodeFixUMDGlobalReact2.ts]: I assume that this suggestion is correct?

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: Probably shouldn't have used an intersection type. `convertToImportCodeFixContext` returns 2 values, the `ImportCodeFixContext` and `isJsxNamespace`. Will update.

File: tests/cases/fourslash/importNameCodeFixUMDGlobalReact2.ts (hunk 2 above)
Comment (andy-ms) [reply tests/cases/fourslash/importNameCodeFixUMDGlobalReact2.ts]: Yeah -- it imports the `export function factory` that was defined in `factory.ts`.
