### PR TITLE
Fix declaration emit for `typeof` default export

### LINKED ISSUE #19428: Symbols for default exports are not printed correctly
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**
Initially, this was visible in our type baselines for an internal project, however I have a minimal sample here:

```ts
// @declaration: true
// @filename: component.ts
class Foo {}
export default Foo;

// @filename: test.ts
import * as Component from "./component";
export default Component.default;
```

**Expected behavior:**
```ts
// component.d.ts
declare class Foo {
}
export default Foo;
// test.d.ts
import * as Component from "./component";
declare const _default: typeof Component.default;
export default _default;
```
**Actual behavior:**
```ts
// component.d.ts
declare class Foo {
}
export default Foo;
// test.d.ts
import * as Component from "./component";
declare const _default: typeof Component.Foo;
export default _default;
```

Mentioned this to @andy-ms the other day, since it looks like this behavior appeared awhile ago; I've bisected, and the issue first appears in 71f885212451e09da16c8808361c46f3fc3822 (so a result of #18616), @andy-ms care to take a look?

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19428

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3174,7 +3174,7 @@ namespace ts {
              * ensuring that any names written with literals use element accesses.
              */
             function appendPropertyOrElementAccessForSymbol(symbol: Symbol, writer: SymbolWriter): void {
-                const symbolName = getNameOfSymbol(symbol);
+                const symbolName = symbol.escapedName === "default" ? "default" : getNameOfSymbol(symbol);
```
Comment (weswigham) [inline src/compiler/checker.ts]: This feels somewhat unfortunate/ad-hoc. Under which use-cases did we want the internal name of the exported symbol versus the `default` symbol name?

If this is how this is going to be fixed, can `getNameOfSymbol` be documented in a comment saying that it returns the internal symbol name for a `default` exported symbol, along with any other interesting special cases it performs? (This way when it is used hopefully we remember to check if all those cases are OK in that scenario)
