### PR TITLE
fix(58399): [isolatedDeclarations][5.5] Autofix does not work when JSX prop contains a dash

### LINKED ISSUE #58399: [isolatedDeclarations][5.5] Autofix does not work when JSX prop contains a dash `-`
### 🔎 Search Terms

isolated declarations, jsx, autofix

### 🕗 Version & Regression Information

- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/58260

### ⏯ Playground Link

_No response_

### 💻 Code

```ts
export const x = <div aria-label="hello" />
```

### 🙁 Actual behavior

No autofix suggestion

### 🙂 Expected behavior

Autofix to add explicit type annotation

### Additional information about the issue

This is with `"jsx": "react-jsx"` in tsconfig

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #58399

### CODE REVIEW

File: src/services/codefixes/fixMissingTypeAnnotationOnExports.ts [hunk 1]
```diff
@@ -392,7 +392,7 @@ function withContext<T>(
                 sourceFile,
                 targetNode,
                 createSatisfiesAsExpression(
-                    getSynthesizedDeepClone(targetNode),
```
Comment (a-tarasyuk) [inline src/services/codefixes/fixMissingTypeAnnotationOnExports.ts:395]: The `formattingScanner` requires the Identifier to have `parent` for scanning attributes with a dash (data-foo). When we clone the node, we lose the `parent` node, which causes issues. I think in this case, we can avoid deep cloning. Are there any cases where deep cloning is necessary? @jakebailey

Comment (jakebailey) [reply src/services/codefixes/fixMissingTypeAnnotationOnExports.ts:395]: I think deep cloning is always the correct thing to do here, because we're creating new AST stuff and don't want to reuse old nodes. Can we just `setParentRecursive`?

Comment (jakebailey) [reply src/services/codefixes/fixMissingTypeAnnotationOnExports.ts:395]: I actually just checked if we could add `return setParentRecursive(clone, false);` to `getSynthesizedDeepClone` itself and it acutally worked, actually _improving_ another test's output. Makes me wonder if that's a better fix (at the cost of us doing this more).

Comment (jakebailey) [reply src/services/codefixes/fixMissingTypeAnnotationOnExports.ts:395]: @andrewbranch Do you have any thoughts about this?

Comment (andrewbranch) [reply src/services/codefixes/fixMissingTypeAnnotationOnExports.ts]: Seems fine to me?

Comment (jakebailey) [reply src/services/codefixes/fixMissingTypeAnnotationOnExports.ts]: Ah, just noticed the PR was changed to set parents for all cloned nodes; that's what I was askng about, yeah. (though tests need to be updated)

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Review by jakebailey — APPROVED** [review]
Assuming perf is fine, LGTM. Doubt it will say anything; the function very clearly says:

```ts
/**
 * Creates a deep, memberwise clone of a node with no source map location.
 *
 * WARNING: This is an expensive operation and is only intended to be used in refactorings
 * and code fixes (because those are triggered by explicit user actions).
 *
 * @internal
 */
export function getSynthesizedDeepClone<T extends Node | undefined>(node: T, includeTrivia = true): T {
```
