### PR TITLE
Fix handling of `aruments` in the emitter

### LINKED ISSUE #38594: "arguments" incorrectly munged to "arguments_1" in numerous circumstances in a for loop targeting ES5
**TypeScript Version:**  Nightly (also, 3.9.2, 3.7.4, and probably others)

**Search Terms:**
arguments property, arguments_1 renamed

**Expected behavior:**
When targeting ES5, an object declared like so:
`{arguments: "foo"}` 
is emitted to javascript as:
`{arguments: "foo"}`

**Actual behavior:**
The object is emitted to javascript as: 
`{arguments_1: "foo"}`

See below code sample for more related bugs.

**Related Issues:**

A similar variant was reported and correctly fixed here:
https://github.com/microsoft/TypeScript/issues/13586

This exact bug was previously reported here, and closed as "fixed" by the reporter. (I don't think it was actually fixed though). 
https://github.com/microsoft/TypeScript/issues/33540

**Code**
```ts
// Compile with ES5 target
function myFunc(_param: string) {
    for (let x = 0; x < 1; ++x){
        let i : number;
        // It's essential to have an inner function declared that references a variable defined in the loop
        [].forEach(function () { i })

        let brokenObj1 = {
            arguments: 0
        }
        // Actual:   {"arguments_1":0}
        // Expected: {"arguments":0}
        console.log(JSON.stringify(brokenObj1)); 

        let brokenObj2 = {
            arguments
        }
        // Actual:   {"arguments":{"0":0}}
        // Expected: {"arguments":{"0":"paramValue"}}
        // (Becuase it erroneously references the arguments of the generated loop function `_loop_1`)
        console.log(JSON.stringify(brokenObj2)); 
        

        let brokenObj3 = {
            arguments: arguments
        }
        // Actual:   {"arguments_1":{"0":"paramValue"}}
        // Expected: {"arguments":{"0":"paramValue"}}
        console.log(JSON.stringify(brokenObj3)); 
    }
}

myFunc("paramValue");
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// Compile with ES5 target
function myFunc(_param) {
    var _loop_1 = function (x) {
        var i;
        // It's essential to have an inner function declared that references a variable defined in the loop
        [].forEach(function () { i; });
        var brokenObj1 = {
            arguments_1: 0
        };
        // Actual:   {"arguments_1":0}
        // Expected: {"arguments":0}
        console.log(JSON.stringify(brokenObj1));
        var brokenObj2 = {
            arguments: arguments
        };
        // Actual:   {"arguments":{"0":0}}
        // Expected: {"arguments":{"0":"paramValue"}}
        // (Becuase it erroneously references the arguments of the generated loop function `_loop_1`)
        console.log(JSON.stringify(brokenObj2));
        var brokenObj3 = {
            arguments_1: arguments_1
        };
        // Actual:   {"arguments_1":{"0":"paramValue"}}
        // Expected: {"arguments":{"0":"paramValue"}}
        console.log(JSON.stringify(brokenObj3));
    };
    var arguments_1 = arguments;
    for (var x = 0; x < 1; ++x) {
        _loop_1(x);
    }
}
myFunc("paramValue");

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?target=1&ts=4.0.0-dev.20200514&ssl=1&ssc=1&pln=34&pc=22#code/PTAEGEHsFsAcEsA2BTUB3eAXAFqAogMoCsomAhgE4DmymAUAGYCuAdgMabyQujQCeAMVZsAFAH1YlMtABcoAM6YK8FlQCUoAN51Qu0A0gVQIlJlAAPUAF5QABgDcF0AB5QARkcBqT+bXa9AaCmoPCgcixM0ABGyBT2OoG6IKAAkpgA5PKgyPLyyCycZIikkKDYZABuqGQ8Kiyx+sKc3KAAJshsiJTIraTlZhTIDLH5bDmgZKAVlPBkUShtQyo9ITw4qIiQkLAJiQDaALoAdAYUeGRs2CLM7M08IhqaIaAAvmp0u4HBURSQANb5ADyUQAVm5rFpPoldJQqJF8ph5HJbFC9C8PtDQMkAIIcJhFOS6TQAIlh8IK8jEbmJMls6MxyTw5lgHUwPTkJLJ0AR8hpdNRujY3HkkBQR02VBEACkCICAHJHRTKVTwBh8EQ-f5A0FuNRqRwY6HfX4AljAkEAJgh-kxei5PIFr0dOLxBL0nOo5MRNJJtj5L3p0MZzNZ7K0pM93IpPuJfpkxMkFGkADUikxkMSA86wCIAEIdfF5EJmWK-eqQJjyRB8UCDYaDdjjdYTSM80CQBh9VA0epJtm9TbbRq3Lg8AAGYkHsCpY-emKFLBFYol0tlCqVKioqvVmtN5oteoNmMNiWNWrNoIAzNbHQF7RS5PfEY7A4kXZh8YhCeGn5TqTJfRpBMpGgVNEHTTNX0CYMWQ4MMPThKNvQA2MgMTFM0wzLN52FUVkHFSBJRleVFSUTdtw1E1tRBS9D1AT50XROh+CEdgRGApNQMw4l9SAA)
     
P.S. Typescript is awesome. We ❤️Typescript!

### PR DESCRIPTION
**Pull request by elibarzilay**
Two problems are fixed:

* `isArgumentsLocalBinding` did only `PropertyAccessExpression`, now it's also doing `PropertyAssignment` (doesn't affect other files, since it's only used in the emitter).

* `visitShorthandPropertyAssignment` should call `visitIdentifier` on the synthesized id.  (For completion it might be better to make it visit the the original?)

Fixes #38594.

Also, simplify `visitObjectLiteralExpression` (I ran into it and the comment at the top tripped me, then I proceeded to simplify the code.  Patched a bit more of the function to make sure that the indentation doesn't change, and added tests.)  This is in a separate commit since it's only loosely related.

### CODE REVIEW

File: tests/baselines/reference/es5-asyncFunctionObjectLiterals.js [hunk 1]
```diff
@@ -75,8 +75,8 @@ function objectLiteral1() {
             switch (_b.label) {
                 case 0:
                     _a = {
-                        a: y
-                    };
+                            a: y
```
Comment (rbuckton) [inline tests/baselines/reference/es5-asyncFunctionObjectLiterals.js:78]: This indentation change seems unintentional, possibly from merging the computed property and `yield` indices in `visitObjectLiteralExpression`?

Comment (rbuckton) [reply tests/baselines/reference/es5-asyncFunctionObjectLiterals.js:78]: I think the quickest way to address it would be to not set `EmitFlags.Indented` if there were no computed property names above.

Comment (rbuckton) [reply tests/baselines/reference/es5-asyncFunctionObjectLiterals.js:78]: We set indented so the downlevel emit for computed properties looks like this:
```js
// ts
obj = { a: 1, [x]: 2 };

// js
obj = (_a = {
    a: 1,
  },
  _a[x] = 2,
  _a);
```

However when we are downleveling generators only, we don't need the indent:
```js
// ts
obj = { a: 1, b: yield z };
// js
...
switch (_b.label) {
  case 0:
    _a = {
      a: 1
    };
    return [4, z];
  case 1:
    obj = (_a.b = _b.sent(),
      _a);
  ...
}
```

File: src/compiler/transformers/es2015.ts [hunk 2]
```diff
@@ -2569,62 +2566,53 @@ namespace ts {
...
+            // Write out the first non-computed properties, then emit the rest through indexing on the temp variable.
+            const expressions: Expression[] = [];
+            const assignment = createAssignment(
+                temp,
+                setEmitFlags(
+                    createObjectLiteral(
+                        visitNodes(properties, visitor, isObjectLiteralElementLike, 0, numInitialProperties),
+                        node.multiLine
+                    ),
+                    EmitFlags.Indented
```
Comment (rbuckton) [inline src/compiler/transformers/es2015.ts:2600]: Per [this discussion](https://github.com/microsoft/TypeScript/pull/38880/files#r438944416), we shouldn't set `EmitFlags.Indented` if there were no computed property names in the set of properties.

File: src/compiler/transformers/es2015.ts [hunk 3]
```diff
@@ -2569,62 +2566,54 @@ namespace ts {
...
-            for (let i = 0; i < numProperties; i++) {
+            let numInitialProperties = -1, hasComputed = false;
+            for (let i = 0; i < properties.length; i++) {
                 const property = properties[i];
-                if ((property.transformFlags & TransformFlags.ContainsYield && hierarchyFacts & HierarchyFacts.AsyncFunctionBody)
-                    && i < numInitialPropertiesWithoutYield) {
-                    numInitialPropertiesWithoutYield = i;
-                }
-                if (Debug.checkDefined(property.name).kind === SyntaxKind.ComputedPropertyName) {
+                hasComputed = Debug.checkDefined(property.name).kind === SyntaxKind.ComputedPropertyName;
```
Comment (rbuckton) [inline src/compiler/transformers/es2015.ts:2576]: Note that https://github.com/microsoft/TypeScript/pull/38880/files#diff-e060748c3972d7c43ccd394a12566242R186 still has the excess indentation. I would try this instead:
```ts
if (property.transformFlags & TransformFlags.ContainsYield && hierarchyFacts & HierarchyFacts.AsyncFunctionBody) {
  numInitialProperties = i;
  break;
}
if (Debug.checkDefined(property.name).kind === SyntaxKind.ComputedPropertyName) {
  numInitialProperties = i;
  hasComputed = true;
  break;
}
```
This we we only add the indentation if we aren't yielding.

File: tests/baselines/reference/es5-yieldFunctionObjectLiterals.js [hunk 4]
```diff
@@ -0,0 +1,200 @@
...
+    });
+}
+function objectLiteral5() {
+    var x, _a;
+    var _b;
+    return __generator(this, function (_c) {
+        switch (_c.label) {
+            case 0:
+                _b = {
+                        a: 1
```
Comment (rbuckton) [inline tests/baselines/reference/es5-yieldFunctionObjectLiterals.js:150]: We still seem to have excess indentation. At this point it doesn't seem worth the extra time to keep digging into this. We can just remove the `hasComputed` check and possibly come back to it later.
