### PR TITLE
Fix declaration emit when the packages are included through symlinks

### LINKED ISSUE #36866: Type resolution in linked packages - Updated Repro
I am still suffering from the issue described in microsoft/TypeScript#32970 

I that issue I provided a repro and that repro was resolved by microsoft/TypeScript#33567

However in my actual application I still face the original issue described (the repro was intentionally simplified). Get `error TS2742: The inferred type of 'actions' cannot be named without a reference to 'drive-common/node_modules/typescript-fsa'. This is likely not portable. A type annotation is necessary.` when using `yarn link` to link packages for dev.

I have updated my original repro to re-expose the problem. Follow steps below...
clone https://github.com/simonfox/repro-plugin-one 
clone https://github.com/simonfox/repro-plugin-two 
run `yarn` for both
run `yarn link` in plugin two root
run `yarn link plugin-two` in plugin one root
you will see the issue in src/features/feature-one/actions.ts (you may need to reload the VS Code window after linking).

cc @sheetalkamat

### PR DESCRIPTION
**Pull request by sheetalkamat**
- Earlier when looking at the redirects, we didnt use `Path` which is the key so in cases of symlink having different cases, we were not including the redirects resulting in the errors during decl emit
Fixes #36866
- Converted symlink tests to virtualFileSystemWithWatch since mounting fs used in tscwatch baseline scenarios did not preserve symlinks correctly.
- So when doing that realised that one of the test case where package is included as a dependency of package included, we werent reporting error as expected. (It worked earlier because symlink realpath always came out to be same as actual path instead of translating to actual path during mounting of fs scenarios) To fix this, exclude paths that dont have `node_modules` if any of the paths for the given module is through `node_modules` 
- Refactored ModuleSpecifierResolutionHost which shouldn't have been in Public API

### CODE REVIEW

File: src/services/utilities.ts [hunk 1]
```diff
@@ -1701,12 +1701,26 @@ namespace ts {
         return !!compilerOptions.module || compilerOptions.target! >= ScriptTarget.ES2015 || !!compilerOptions.noEmit;
     }
 
-    export function hostUsesCaseSensitiveFileNames(host: { useCaseSensitiveFileNames?(): boolean; }): boolean {
-        return host.useCaseSensitiveFileNames ? host.useCaseSensitiveFileNames() : false;
+    export function createModuleSpecifierResolutionHost(program: Program, host: LanguageServiceHost): ModuleSpecifierResolutionHost {
+        // Mix in `getProbablySymlinks` from Program when host doesn't have it
```
Comment (andrewbranch) [inline src/services/utilities.ts]:
```suggestion
        // Mix in `getProbableSymlinks` from Program when host doesn't have it
```

I think this was originally my typo but I just noticed it 😄

File: src/compiler/moduleSpecifiers.ts [hunk 2]
```diff
@@ -179,26 +169,24 @@ namespace ts.moduleSpecifiers {
...
         preferSymlinks: boolean,
         cb: (fileName: string) => T | undefined
     ): T | undefined {
-        const redirects = redirectTargetsMap.get(importedFileName);
-        const importedFileNames = redirects ? [...redirects, importedFileName] : [importedFileName];
-        const cwd = host.getCurrentDirectory ? host.getCurrentDirectory() : "";
+        const getCanonicalFileName = hostGetCanonicalFileName(host);
+        const cwd = host.getCurrentDirectory();
+        const redirects = host.redirectTargetsMap.get(toPath(importedFileName, cwd, getCanonicalFileName)) || emptyArray;
+        const importedFileNames = [importedFileName, ...redirects];
```
Comment (andrewbranch) [inline src/compiler/moduleSpecifiers.ts]: What’s the significance of changing `importedFileName` to go at the beginning instead of the end of the array?

File: src/compiler/moduleSpecifiers.ts [hunk 3]
```diff
@@ -251,7 +239,10 @@ namespace ts.moduleSpecifiers {
             let pathsInDirectory: string[] | undefined;
             allFileNames.forEach((canonicalFileName, fileName) => {
                 if (startsWith(canonicalFileName, directoryStart)) {
-                    (pathsInDirectory || (pathsInDirectory = [])).push(fileName);
+                    // If the importedFile is from node modules, use only paths in node_modules folder as option
+                    if (!importedFileFromNodeModules || pathContainsNodeModules(fileName)) {
+                        (pathsInDirectory || (pathsInDirectory = [])).push(fileName);
+                    }
```
Comment (andrewbranch) [inline src/compiler/moduleSpecifiers.ts]: I see the explanation of this change in the PR description. It looks like everything outside this file is just cleanup/refactoring or test changes—is that right, or is there somewhere else I should look for behavior changes?

File: src/compiler/moduleSpecifiers.ts (hunk 2 above)
Comment (sheetalkamat) [reply src/compiler/moduleSpecifiers.ts]: There is no significance.. I don't know why we had it other way around but it doesn't change any of the tests we have

File: src/compiler/moduleSpecifiers.ts (hunk 3 above)
Comment (sheetalkamat) [reply src/compiler/moduleSpecifiers.ts]: Thats correct.. The real change is two changes in this file (casing and node_modules behaviour) everything else was just refactoring for cleaner interface and potential new additions needed from program..
