### PR TITLE
Leave files from `node_modules` out when calculating `getCommonSourceDirectory`

### LINKED ISSUE #11977: Inferred base path is wrong when there is a `.ts` file in `node_modules`
**TypeScript Version:**  2.1.0-dev.20161101

### Code

**node_modules/foo/index.ts**: (note the `.ts`)

```ts
export const x = 0;
```

**app/index.ts**:

```ts
import * as foo from "foo"; foo.x + 1;
```

**app/tsconfig.json**:

```json
{
    "compilerOptions": {
        "outDir": "bin"
    }
}
```

**Expected behavior:**

Writes to `bin/index.js`.

**Actual behavior:** 

Writes to `bin/app/index.js`.

The problem is that `getCommonSourceDirectory` considers all files, not just the ones that will actually be emitted.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #11977

### CODE REVIEW

**Comment by sandersn** [comment]
I think @vladima should take a look too.

File: src/compiler/program.ts [hunk 1]
```diff
@@ -430,13 +430,14 @@ namespace ts {
         return program;
 
         function getCommonSourceDirectory() {
-            if (typeof commonSourceDirectory === "undefined") {
-                if (options.rootDir && checkSourceFilesBelongToPath(files, options.rootDir)) {
+            if (commonSourceDirectory === undefined) {
+                const emittedFiles = filterSourceFilesInDirectory(files, isSourceFileFromExternalLibrary);
```
Comment (sheetalkamat) [inline src/compiler/program.ts]: This is ignoring .d.ts files in the own compilation as well ? (not from external library)

File: src/compiler/program.ts [hunk 2]
```diff
@@ -430,13 +430,14 @@ namespace ts {
         return program;
 
         function getCommonSourceDirectory() {
-            if (typeof commonSourceDirectory === "undefined") {
-                if (options.rootDir && checkSourceFilesBelongToPath(files, options.rootDir)) {
+            if (commonSourceDirectory === undefined) {
```
Comment (sheetalkamat) [inline src/compiler/program.ts]: This is also used by maproot and sourceroot.. So not doing this for bundle emit has effect on how the paths would be represented... Because --mapRoot --sourceRoot --outFile is a valid option

Comment (andy-ms) [inline src/compiler/program.ts]: Could you write a test case?

File: src/compiler/program.ts (hunk 1 above)
Comment (andy-ms) [inline src/compiler/program.ts]: Yes. For the `--outDir` case that makes sense since we are just emitting `.ts` files. Can you provide another case where we would want the `.d.ts` files included?

Comment (sheetalkamat) [inline src/compiler/program.ts]: But right now we didnt ignore .d.ts files from our own program to compute the common source directory? So this is intended change?

Comment (andy-ms) [inline src/compiler/program.ts]: I've added a `.d.ts` file to the test.

File: src/compiler/program.ts (hunk 2 above)
Comment (andy-ms) [inline src/compiler/program.ts]: If `--sourceRoot` is specified, then the `"sourceRoot"` property in the source map is exactly what you specified.

Comment (sheetalkamat) [inline src/compiler/program.ts]: yes but the paths are relative to common source directory and with this change the commonsourcedirectory would be different from what it used to be if say eg your sources are in ./src/ and ./node_modules/ which means the sources will be just relative to ./src/ instead or ./

Comment (mhegazy) [inline src/compiler/program.ts]: I think this is the section @sheetalkamat is referring to: https://github.com/Microsoft/TypeScript/blob/4a906143c62fcbfe113bf3f1cc607c488df47400/src/compiler/sourcemap.ts#L171-L180

Comment (andy-ms) [inline src/compiler/program.ts]: I wrote a test case. @sheetalkamat could you look at the baselines and tell me if they're what you would expect?

File: src/compiler/program.ts (hunk 1 above)
Comment (sheetalkamat) [inline src/compiler/program.ts]: you need a new test case:
```
//@filename: app/src/index.ts

//@filename: app/lib/bar.d.ts

//@filename: app/tsconfig.json
```

To make sure common source directory is still ```app```

File: src/compiler/program.ts (hunk 2 above)
Comment (sheetalkamat) [inline src/compiler/program.ts]: I think test case is ok, and realized that scenario I was talking about sourceroot and maproot works because  --out is only allowed with ```amd``` or ```system``` and hence there is no way to get bundled emit that includes modules from ```node_modules``` folder.

File: src/compiler/program.ts (hunk 1 above)
Comment (andy-ms) [inline src/compiler/program.ts]: OK, I added a test `commonSourceDirectory_dts.ts `. This appears to already be the behavior of the current compiler -- the referenced file does not become part of the output.
