### PR TITLE
Use other files when necessary to determine import style in JS

### LINKED ISSUE #29038: VSCode mixes import and require syntaxes on auto-import
In this particular instance I encountered the bug with moment.js. 

- VSCode Version: 1.30.0-insider, 1.29.1
- OS Version: Windows 10 (1803), macOS 10.14.1

Steps to Reproduce:

1. Begin typing usage of an un-imported module
2. Press enter on auto-import intellisense suggestion

Does this issue occur when all extensions are disabled?: Yes

Above recording is on fresh Insiders install with extensions disabled and being reproduced in a fresh project with just React and moment installed through yarn.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #29038 (even more)

### CODE REVIEW

**Review by sheetalkamat — APPROVED** [review]

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -362,10 +362,31 @@ namespace ts.codefix {
...
+        }
+
+        // 4. Match the first other JS file in the program that's unambiguously CJS or ESM
+        for (const otherFile of program.getSourceFiles()) {
+            if (otherFile === sourceFile || !isSourceFileJS(otherFile) || program.isSourceFileFromExternalLibrary(otherFile)) continue;
+            if (otherFile.commonJsModuleIndicator && !otherFile.externalModuleIndicator) return true;
+            if (otherFile.externalModuleIndicator && !otherFile.commonJsModuleIndicator) return false;
+        }
+
+        // 5. Literally nothing to go on
```
Comment (sandersn) [inline src/services/codefixes/importFixes.ts:388]:
```suggestion
        // 5. Literally nothing to go on, why not zoidberg?
```

**Review by sandersn — APPROVED** [review]
