### PR TITLE
Validate symbol-named properties against symbol index signatures

### LINKED ISSUE #44793: Excess property checks still appear in presence of index signature
```ts
interface A {
    a?: string
    b?: number
    [key: symbol]: string
}

const symbolKey = Symbol('key')

const a: A = {
    [symbolKey]: '123',
}
```

`symbol` still not working：[ts playground](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210627#code/PTAEiJrQ5+MU3NAYlUAqBPADgUwMoGMBOBLFAF1EA47QBTlAudUBh-gKBFEE34wejNAAOUCo5QTb9ADeUAXjQbPlAaP6BMxSqAwJUDVcoBiVQGbagAzlEqTLgLFAIW6BFf0CbXoCAGGnTCAKg0D3yoFO5E4CDNQNBygSDlAs56BO00Dw+oH95QBSugYO1AWP-79oUAFpQdkBYOUAseUAWD0B5dUBvuUBVeUAcOUB-SNU5BXRsfCJQVUAGdXtdegCgtkBleUAYrLSlTOJAW+jAVZtANz1AODlAaojALrkJXPzfIvZXQDi5QGlbQFXo4MAYFUqMlVABQEXowHxzQHylQF+A1UBMm0BG710aPAA7QjQcADMAQyw0UABBUABvGj8-E4B+AC5QAGdCfF2Ac3uHgBGr1AuwArgBbAGHf5+ADaAGs0Eg3gADAAe-gAJDdPt8fgBfFGgAA+HyQkIA9gAbAC6b1xez++L0WApu0+ZMpVIA0kjQABeUAYckA6kACgA5IikBKAJQstkck5va6Cu4PUASjEnCVvCUARgATABmCUAGhhoFh7xF1N5SDpmqNppozN8pkAnQ6Ab8VAFBy9lUoEAOASALk9ANHygFwCUCANCMg4AG00A36nhqgmQBhcoBjyMAL2aALE1AM6K-RqgAAo1SAQ-lAPYG2gARL4o4BQAMABEqAEzSGIBsuUAFzaAKcSGoAUOUAAPqAac03FRAC6mbHIFFUgDQ5QAyroBfhMAejr9Li6IA)

_Originally posted by @liuweiGL in https://github.com/microsoft/TypeScript/issues/44512#issuecomment-869415311_

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we properly validate symbol-named properties against symbol index signatures in excess property checking. For backwards compatibility, we also validate symbol-named properties against string index signatures. Removal of this exception is covered by #44794.

Fixes #44793.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12106,7 +12106,7 @@ namespace ts {
         }
 
         function getApplicableIndexInfoForName(type: Type, name: __String): IndexInfo | undefined {
-            return getApplicableIndexInfo(type, getStringLiteralType(unescapeLeadingUnderscores(name)));
+            return getApplicableIndexInfo(type, isLateBoundName(name) ? esSymbolType : getStringLiteralType(unescapeLeadingUnderscores(name)));
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:12109]: Is a late-bound-name always an ES Symbol? @weswigham says not.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:12109]: Maybe we need to rename this to `isUnresolvedLateBoundName` or something like that.

**Review by DanielRosenwasser — APPROVED** [review]
