### PR TITLE
Unify representation of tuples and other generic types

### LINKED ISSUE #10431: Compiler hangs or crashes by a few code
I believe TypeScript must not hang by the following small code.

**TypeScript Version:**  2.1.0-dev.20160819

**Code**

```ts
export class Sequence<a, z> {
  constructor(
    cons: (z: z, cons: (a?: a, z?: z) => Sequence.Data<a, z>) => Sequence.Data<a, z>,
    memory?: Map<number, Sequence.Data<a, z>>
  ) {
  }
}
export namespace Sequence {
  export type Data<a, z> = [a, z];
  export namespace Data {
    export function cons<a, z>(a?: a, b?: z): Sequence.Data<a, z> {
      switch (arguments.length) {
        case 0:
          return <Sequence.Data<a, z>>[];
        case 1:
          return <Sequence.Data<a, z>><any[]>[a];
        case 2:
          return <Sequence.Data<a, z>>[a, b];
        default:
          throw Sequence.Exception.invalidConsError(arguments);
      }
    }
  }
  export type Thunk<a> = [a, Iterator<a>, number];
  export namespace Thunk {
    export function value<a>(thunk: Thunk<a>): a {
      return thunk[0];
    }
    export function iterator<a>(thunk: Thunk<a>): Iterator<a> {
      return thunk[1];
    }
    export function index<a>(thunk: Thunk<a>): number {
      return thunk[2];
    }
  }
  export type Iterator<a> = () => Thunk<a>;
  export namespace Iterator {
    export const done: Sequence.Iterator<any> = () => <Sequence.Thunk<any>>[void 0, done, -1];
    export function when<a, b>(
      thunk: Thunk<a>,
      caseDone: (thunk: Thunk<a>) => b,
      caseIterable: (thunk: Thunk<a>, recur: () => b) => b
    ): b {
      return Sequence.isIterable(thunk)
        ? caseIterable(thunk, () => when(Thunk.iterator(thunk)(), caseDone, caseIterable))
        : caseDone(thunk);
    }
  }
  export function isIterable(thunk: Thunk<any>): boolean {
    return Thunk.iterator(thunk) !== Iterator.done;
  }
  export namespace Exception {
    export function invalidConsError(args: IArguments): TypeError {
      console.error(args, args.length, args[0], args[1]);
      return new TypeError(`Spica: Sequence: Invalid parameters of cons.`);
    }
    export function invalidDataError(data: Sequence.Data<any, any>): TypeError {
      console.error(data);
      return new TypeError(`Spica: Sequence: Invalid data.`);
    }
    export function invalidThunkError(thunk: Sequence.Thunk<any>): TypeError {
      console.error(thunk);
      return new TypeError(`Spica: Sequence: Invalid thunk.`);
    }
  }
}
```

**Expected behavior:**

It can compile quickly.

**Actual behavior:** 

Too slow. In my actual case, compiler will be crashed.

```
$ $(npm bin)/tsc --noEmit -t es5 --lib es6,dom --diagnostics src/lib/monad/sequence/core.ts
Files:              13
Lines:           20588
Nodes:          102533
Identifiers:     37365
Symbols:       1679795
Types:          787098
Memory used:  1285938K
I/O read:        0.03s
I/O write:       0.00s
Parse time:      0.91s
Bind time:       0.67s
Check time:     94.28s
Emit time:       0.00s
Total time:     95.87s
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we unify the internal representation of tuple types and other generic types. Tuple types are now represented as regular type references to synthesized generic types of the form:

```ts
interface Tuple<T0, T1, T2, ...> extends Array<T0 | T1 | T2 | ...> { 0: T0, 1: T1, 2: T2, ... }
```

With these changes it is no longer necessary to special case tuple types throughout the type checker. All of the optimizations we have in place for regular generic type references now also apply to tuple types.

Fixes #10431. The compile time for the example drops from 1.2s to 0.08s with `--lib es5` and from 30.5s to 0.11s with `--lib es6`.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Will this be developed into https://github.com/Microsoft/TypeScript/issues/5453 ?

 Synthesized generic types and tuple types looks much like variadic kinds.

**Comment by weswigham** [comment]
I quite like the changes in the error baselines. Feels neater.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2214,6 +2211,11 @@ namespace ts {
                         writePunctuation(writer, SyntaxKind.OpenBracketToken);
                         writePunctuation(writer, SyntaxKind.CloseBracketToken);
                     }
+                    else if (type.target.flags & TypeFlags.Tuple) {
+                        writePunctuation(writer, SyntaxKind.OpenBracketToken);
+                        writeTypeList(type.typeArguments.slice(0, getTypeReferenceArity(type)), SyntaxKind.CommaToken);
```
Comment (sandersn) [inline src/compiler/checker.ts]: Why copy this list? Or are there extra type arguments that `slice` omits?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5234,17 +5224,47 @@ namespace ts {
             return links.resolvedType;
         }
 
-        function createTupleType(elementTypes: Type[], thisType?: Type) {
-            const id = getTypeListId(elementTypes) + "," + (thisType ? thisType.id : 0);
-            return tupleTypes[id] || (tupleTypes[id] = createNewTupleType(elementTypes, thisType));
+        // We represent tuple types as type references to synthesized generic interface types created by
```
Comment (sandersn) [inline src/compiler/checker.ts]: Can you use a jsdoc comment here?

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: When a generic type has a `this` parameter other than itself it is represented as an extra type parameter.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -5234,17 +5224,47 @@ namespace ts {
...
 
-        function createTupleType(elementTypes: Type[], thisType?: Type) {
-            const id = getTypeListId(elementTypes) + "," + (thisType ? thisType.id : 0);
-            return tupleTypes[id] || (tupleTypes[id] = createNewTupleType(elementTypes, thisType));
+        // We represent tuple types as type references to synthesized generic interface types created by
+        // this function. The types are of the form:
+        //
+        //   interface Tuple<T0, T1, T2, ...> extends Array<T0 | T1 | T2 | ...> { 0: T0, 1: T1, 2: T2, ... }
+        //
+        // Note that the generic type created by this function has no symbol associated with it. The same
```
Comment (sandersn) [inline src/compiler/checker.ts]: > has no symbol associated with it [](start = 62, length = 33)

Is that because the generic type is reused for all tuples of a certain length? Or some other reason?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -7301,11 +7318,8 @@ namespace ts {
                 if (type.flags & TypeFlags.Union) {
                     return getUnionType(map((<UnionType>type).types, getWidenedConstituentType));
                 }
-                if (isArrayType(type)) {
-                    return createArrayType(getWidenedType((<TypeReference>type).typeArguments[0]));
-                }
-                if (isTupleType(type)) {
-                    return createTupleType(map(type.elementTypes, getWidenedType));
+                if (isArrayType(type) || isTupleType(type)) {
+                    return createTypeReference((<TypeReference>type).target, map((<TypeReference>type).typeArguments, getWidenedType));
```
Comment (sandersn) [inline src/compiler/checker.ts]: ><TypeReference> [](start = 48, length = 15)

Could you make `isArrayType` and `isTupleType` both return `x is TypeReference`? It would clean up this line, although I don't know if the overall effect would be less confusing.

Comment (sandersn) [inline src/compiler/checker.ts]: half the uses of `isArrayType` require the type assertion, so I think it's worth it.

---
In reply to: [75712577](https://github.com/Microsoft/TypeScript/pull/10466#discussion_r75712577) [](ancestors = 75712577)

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -4992,6 +4971,17 @@ namespace ts {
             return type;
         }
 
+        function cloneTypeReference(source: TypeReference): TypeReference {
```
Comment (sandersn) [inline src/compiler/checker.ts]: >cloneTypeReference [](start = 17, length = 18)

Does this do anything meaningful for non-tuple types?

File: src/compiler/checker.ts (hunk 4 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: But there are many type references that aren't arrays, so it isn't correct to say `x is TypeReference` because we'll take that to mean `x` *isn't* a type reference when the function returns false.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Yes, the generic type is reused for all tuples of a certain arity, but that's not the reason. Basically, we don't have a symbol because we don't have a manifest declaration for the type anywhere--it is synthesized on demand by the compiler.

File: src/compiler/checker.ts (hunk 5 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: It clones any type reference, regardless of what it is a reference to. There's no particular use for that currently, but also no reason to special case for tuples.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [inline src/compiler/checker.ts]: oh, right. I forgot about that. :/

---
In reply to: [75714919](https://github.com/Microsoft/TypeScript/pull/10466#discussion_r75714919) [](ancestors = 75714919)

**Comment by mhegazy** [comment]
👍
