### PR TITLE
fix(48887) exposing rest helper functions externally

### LINKED ISSUE #48887: Expose `isRestParameter` in internal API
Currently, ts.isRestParameter is marked as internal only.
However, it is a useful function that I need while writing an ESLint rule.
Thus, I think it should be marked as not being internal, and am opening this issue as a suggestion from Nathan Sanders.

### PR DESCRIPTION
**Pull request by Zamiell**
Fixes #48887.

Also, as a tiny other change, this improves the obscure/confusing error message about baselines, adding a hint for the end-user to run the appropriate gulp command. In order to avoid duplicating the hint, I added a new function to generate the string, which makes the code slightly more DRY.

### CODE REVIEW

File: src/harness/harnessIO.ts [hunk 1]
```diff
@@ -1389,22 +1389,27 @@ namespace Harness {
...
                     else {
-                        throw new Error(`The baseline file ${relativeFileName} has changed.`);
+                        throw new Error(errorMessage);
                     }
                 }
             }
         }
 
+        function getBaselineFileChangedErrorMessage(relativeFileName: string): string {
+            return `The baseline file ${relativeFileName} has changed. (You must run "gulp baseline-accept" to confirm that this baseline change as a result of your code change was intended.)`;
```
Comment (sandersn) [inline src/harness/harnessIO.ts:1410]: I'd prefer that this be shorter, preferably <80 characters. Maybe:

```suggestion
            return `The baseline file ${relativeFileName} has changed. (Run "gulp baseline-accept" if the new baseline is correct.)`;
```

That's 109 (with `${relativeFileName}` probably shorter than the eventual filename), which is pretty good.

**Review by sandersn — CHANGES_REQUESTED** [review]
I think this is good idea, although

1. I want to double-check with the rest of the team for objections.
2. The error message should be shorter.

**Review by sandersn — APPROVED** [review]
