### PR TITLE
parser: Fix testing for missing list

### LINKED ISSUE #25034: [REGRESSION] Unable to compile TypeScript since 2.9.2
**TypeScript Version:**  2.9.2 & 3.0.0-dev.20180616

**Search Terms:** Unable to compile TypeScript, generics, complex return type

**Code**
```ts
export let returnConstant = <T>(arg: T): (() => T) => () => arg;
```

**Expected behavior:**
The provided TypeScript code should compile.

**Actual behavior:**
The TypeScript code does not compile.
In TypeScript 2.9.1, this worked fine.
Since TypeScript 2.9.2 (including 3.0.0-dev.20180616), this will provide a TSError / Unable to compile TypeScript:

```
Error:(1, 30) TS2304: Cannot find name 'T'.
Error:(1, 33) TS2304: Cannot find name 'arg'.
Error:(1, 61) TS2304: Cannot find name 'arg'.
Error:(1, 36) TS1005: ')' expected.
Error:(1, 39) TS1005: ',' expected.
Error:(1, 40) TS1134: Variable declaration expected.
Error:(1, 42) TS1134: Variable declaration expected.
Error:(1, 52) TS1005: ';' expected.
```

**Playground Link:**  Sorry, but the playground has an outdated TypeScript version.

**Related Issues:**

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #25034

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -2090,8 +2090,18 @@ namespace ts {
...
+            isMissingList: true;
+        }
+
+        function createMissingList<T extends Node>(): MissingList<T> {
+            const list = createNodeArray<T>([], getNodePos()) as MissingList<T>;
+            list.isMissingList = true;
+            return list;
+        }
+
+        function isMissingList(arr: NodeArray<Node>): boolean {
```
Comment (ajafff) [inline src/compiler/parser.ts]: the return type is actually `boolean | undefined`
