### PR TITLE
Compare enums semi-structurally.

### LINKED ISSUE #1748: Enum Equality
```ts
/// <reference path="./node_modules/typescript/bin/typescript.d.ts"/>
/// <reference path="./node_modules/typescript/bin/typescriptServices.d.ts"/>

import typescript = require('typescript');

var foo: typescript.CompilerOptions;
var bar: ts.CompilerOptions;

foo = bar; // Error: ModuleKind is not assignable to type ModuleKind
```

I expected the two `CompilerOptions` to be type compatible.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #1748.

1. Unqualified names must match.
2. Target contains members with same names as all source members.

### CODE REVIEW

**Comment by weswigham** [comment]
Could you add some tests with `const` enums and enums with computed properties, just so they have some coverage? Otherwise seems great, :+1:

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5750,6 +5755,25 @@ namespace ts {
...
+            function enumRelatedTo(source: Type, target: Type) {
+                if (source.symbol.name !== target.symbol.name) {
+                    return Ternary.False;
+                }
+                const sourceDecl = <EnumDeclaration>getMergedSymbol(source.symbol).valueDeclaration;
+                const targetDecl = <EnumDeclaration>getMergedSymbol(target.symbol).valueDeclaration;
+                const targetMembers = arrayToMap(targetDecl.members, member => getTextOfPropertyName(<PropertyName>member.name));
+                for (const member of sourceDecl.members) {
+                    const name = getTextOfPropertyName(<PropertyName>member.name);
+                    if (!targetMembers[name]) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: This is not correct, you need to use `hasProperty`

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5750,6 +5755,25 @@ namespace ts {
...
                 return Ternary.False;
             }
+
+            function enumRelatedTo(source: Type, target: Type) {
+                if (source.symbol.name !== target.symbol.name) {
+                    return Ternary.False;
+                }
+                const sourceDecl = <EnumDeclaration>getMergedSymbol(source.symbol).valueDeclaration;
+                const targetDecl = <EnumDeclaration>getMergedSymbol(target.symbol).valueDeclaration;
+                const targetMembers = arrayToMap(targetDecl.members, member => getTextOfPropertyName(<PropertyName>member.name));
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You never use `targetMembers`, so there's no need to initialize it like this. I'd recommend just passing in `x => x` or `x => true`

Comment (weswigham) [inline src/compiler/checker.ts]: `targetMembers` is used on line 5768, 3 lines below.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I meant the mapped members, I reworded my comment.

Comment (sandersn) [inline src/compiler/checker.ts]: `arrayToMap` uses the array elements themselves as values. The second argument provides the *keys* of the map.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -5750,6 +5755,25 @@ namespace ts {
                 }
                 return Ternary.False;
             }
+
+            function enumRelatedTo(source: Type, target: Type) {
+                if (source.symbol.name !== target.symbol.name) {
+                    return Ternary.False;
+                }
+                const sourceDecl = <EnumDeclaration>getMergedSymbol(source.symbol).valueDeclaration;
```
Comment (vladima) [inline src/compiler/checker.ts]: using `valueDeclaration` does not look correct given that enums are open-ended and can be merged

Comment (sandersn) [inline src/compiler/checker.ts]: done

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]: done

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -5750,6 +5755,27 @@ namespace ts {
...
                 return Ternary.False;
             }
+
+            function enumRelatedTo(source: Type, target: Type) {
+                if (source.symbol.name !== target.symbol.name ||
+                    source.symbol.flags & SymbolFlags.ConstEnum ||
+                    target.symbol.flags & SymbolFlags.ConstEnum) {
+                    return Ternary.False;
+                }
+                const sourceDecl = <EnumDeclaration>getDeclarationOfKind(source.symbol, SyntaxKind.EnumDeclaration);
```
Comment (vladima) [inline src/compiler/checker.ts]: what is means it that with this code
```ts
enum A { X }
enum A { Y }
```
you will see only `X` member, but you won't see `Y` since you are using one declaration to obtain property names.

Comment (sandersn) [inline src/compiler/checker.ts]: Is there already a right way to get all members of enums? Otherwise I'll need to write getDeclaration**s**OfKind and then look at all members from those symbols.

Comment (vladima) [inline src/compiler/checker.ts]: well, you already have types on hand, so you can get its members that has flag `SymbolFlag.EnumMember`. Open question is if you need to pay attention to the order of member since it can directly affect values of enum members

Comment (sandersn) [inline src/compiler/checker.ts]: I believe in the discussion around #1748 last week, we decided to ignore values of members. So as long as the enums are not const, we will just check for existence of matching property names.

Comment (sandersn) [inline src/compiler/checker.ts]: The type object for enums don't actually have members defined, so there are no members to check for `EnumMember`.

Comment (vladima) [inline src/compiler/checker.ts]: symbol for a enum type should have exports that contain all enum members

Comment (vladima) [inline src/compiler/checker.ts]: `resolveStructuredTypeMembers(rightType).members` should do the trick

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -5750,6 +5755,26 @@ namespace ts {
...
+
+            function enumRelatedTo(source: Type, target: Type) {
+                if (source.symbol.name !== target.symbol.name ||
+                    source.symbol.flags & SymbolFlags.ConstEnum ||
+                    target.symbol.flags & SymbolFlags.ConstEnum) {
+                    return Ternary.False;
+                }
+                const sourceMembers = resolveStructuredTypeMembers(getTypeOfSymbol(source.symbol)).properties;
+                const targetMembers = resolveStructuredTypeMembers(getTypeOfSymbol(target.symbol)).properties;
+                const targetNames = arrayToMap(targetMembers, member => member.name);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Sorry, given what Wesley said, I think it was correct to do what you were doing before when creating the map. If `member.name` isn't a`string `, how is this working?

Comment (sandersn) [inline src/compiler/checker.ts]: `member.name` is a string:

```ts
    function Symbol(flags: SymbolFlags, name: string) {
        this.flags = flags;
        this.name = name;
        this.declarations = undefined;
    }
```

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -5750,6 +5755,26 @@ namespace ts {
...
+                for (const member of sourceMembers) {
```
Comment (vladima) [inline src/compiler/checker.ts]: you still have to filter list to use only elements with `SymbolFlags.EnumMember` otherwise you'll pick members from merged module declarations which is presumably not desirable.
```ts
enum A { X }
module A {
    export let Y = () => 42;
}
A.$ // A has both X and Y

```

File: src/compiler/checker.ts (hunk 5 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Ah, it's the symbol, not the member itself. This is fine then.

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Done

Comment (sandersn) [inline src/compiler/checker.ts]: done

**Comment by sandersn** [comment]
@vladima any more comments?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -5750,6 +5755,26 @@ namespace ts {
...
+
+            function enumRelatedTo(source: Type, target: Type) {
+                if (source.symbol.name !== target.symbol.name ||
+                    source.symbol.flags & SymbolFlags.ConstEnum ||
+                    target.symbol.flags & SymbolFlags.ConstEnum) {
+                    return Ternary.False;
+                }
+                for (const property of getPropertiesOfType(getTypeOfSymbol(source.symbol))) {
+                    if (property.flags & SymbolFlags.EnumMember) {
+                        const targetProperty = getPropertyOfType(getTypeOfSymbol(target.symbol), property.name);
```
Comment (vladima) [inline src/compiler/checker.ts]: lift it to a variable so it is not refetched on every iteration (cost of it is probably low but still)

**Comment by vladima** [comment]
:+1: after minor nit from comment is addressed

**Comment by DanielRosenwasser** [comment]
Keywords: enum identical names relate related to assignable compatible compatibility
