### PR TITLE
Numeric enums as key types in mapped types

### LINKED ISSUE #31771: Index signature error for mapped type when keyed on `declare enum`
**TypeScript Version:**  3.2.4 plus whatever's on the Playground

**Search Terms:** enum mapped index signature 

**Code**

```ts
enum E1 { ONE, TWO, THREE }
declare enum E2 { ONE, TWO, THREE }

type Bins1 = { [k in E1]?: string; }
type Bins2 = { [k in E2]?: string; }

const b1: Bins1 = {};
const b2: Bins2 = {};

const e1: E1 = E1.ONE;
const e2: E2 = E2.ONE;

// These are fine
b1[1] = "a";
b1[e1] = "b";

// Fails (correctly) because we can't know that `1` is a valid index at compile time
b2[1] = "a";
// Gives "Element implicitly has an 'any' type because type 'Bins2' has no index signature." but shouldn't
b2[e2] = "b";
```

**Expected behavior:** Indexed access to a mapped type should be possible as long as we guarantee ahead of time that the index value is of the correct key type.

**Actual behavior:** Compiler allows indexed access only if it knows that the enum value is a literal.

**Playground Link:** [Here](https://www.typescriptlang.org/play/#src=enum%20E1%20%7B%20ONE%2C%20TWO%2C%20THREE%20%7D%0D%0Adeclare%20enum%20E2%20%7B%20ONE%2C%20TWO%2C%20THREE%20%7D%0D%0A%0D%0Atype%20B1%20%3D%20%7B%20%5Bk%20in%20E1%5D%3F%3A%20string%3B%20%7D%0D%0Atype%20B2%20%3D%20%7B%20%5Bk%20in%20E2%5D%3F%3A%20string%3B%20%7D%0D%0A%0D%0Aconst%20b1%3A%20B1%20%3D%20%7B%7D%3B%0D%0Aconst%20b2%3A%20B2%20%3D%20%7B%7D%3B%0D%0A%0D%0Aconst%20e1%3A%20E1%20%3D%20E1.ONE%3B%0D%0Aconst%20e2%3A%20E2%20%3D%20E2.ONE%3B%0D%0A%0D%0Ab1%5B1%5D%20%3D%20%22a%22%3B%0D%0Ab1%5Be1%5D%20%3D%20%22b%22%3B%0D%0A%0D%0Ab2%5B1%5D%20%3D%20%22a%22%3B%0D%0Ab2%5Be2%5D%20%3D%20%22b%22%3B), make sure to turn on `noImplicitAny`

**Related Issues:** #13042 appears to work but only addresses locally-defined enums

I'm trying to key on enum-values from a library I depend on so I'm stuck using ambient declarations.  If this is "by design", or allowing enum values whose runtime contents cannot be determined at compile time is too difficult to support, I'd welcome suggestions for an alternate approach.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes a minor issue related to numeric enums as key types in mapped types. We now generate a numeric index signature when a numeric enum type occurs in the key type of a mapped type. Previously we wouldn't generate anything which was inconsistent.

The PR also fixes a crash that is triggered by the following code:

```ts
declare enum E { ONE, TWO, THREE = 'x' }
const e: E = E.ONE;
const x: E.ONE = e;
```

Fixes #31771.

### CODE REVIEW

File: tests/cases/compiler/numericEnumMappedType.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+b2[e2] = "b";
+
+// Multiple numeric enum types accrue to the same numeric index signature in a mapped type
+
+declare function val(): number;
+
+enum N1 { A = val(), B = val() }
+enum N2 { C = val(), D = val() }
+
+type T1 = { [K in N1 | N2]: K };
```
Comment (weswigham) [inline tests/cases/compiler/numericEnumMappedType.ts]: Can you turn on `declarations: true` for this test and export this type (and Bins1 and Bins2 for good measure)? I want to see what our full structural printback for these types is.

Comment (ahejlsberg) [reply tests/cases/compiler/numericEnumMappedType.ts]: Sure
