### PR TITLE
Fix two issues with ConvertToTypeOnlyExport codefix

### LINKED ISSUE #40488: ConvertToTypeOnlyExport codefix breaks when applying all codefixes to an export with 3 re-exported types
**TypeScript Version:**  3.9.6, 4.1.0

**Search Terms:** TS1205 re-exported type-only exports codefix 

**Code**

```ts
// @isolatedModules: true

// @Filename: /a.ts
export type T1 = {};
export const V1 = {};
export type T2 = {};

// @Filename: /b.ts
export type T3 = {};
export const V2 = {};
export type T4 = {};
export type T5 = {};

// @Filename: /c.ts
export { T1, V1, T2 } from './a';
export { T3, V2, T4, T5 } from './b';
```

Create the structure above and apply the 'Convert all re-exported types to type-only exports' codefix via VSCode or by calling through the TS Language Service directly.

**Expected behavior:**

The 3 types that need to be converted to type only exports are handled properly.

```ts
/* Test comment */
export { V1 } from './a';
export type { T1, T2 } from './a';
export { V2 } from './b';
export type { T3, T4, T5 } from './b';
```

**Actual behavior:**

Errors out with 

```
<semantic> TypeScript Server Error (3.9.6) Debug Failure. False expression: Changes overlap Verbose Debug Information: {"pos":281,"end":469} and {"pos":281,"end":469} Error: Debug Failure. False expression: Changes overlap
```
(The pos/end values are wrong for this example as the error message is taken from real code).

**Related Issues:**

### PR DESCRIPTION
**Pull request by Blasz**
Fixes #40488 and #40489.

### CODE REVIEW

**Comment by Blasz** [comment]
Aforementioned issues have been triaged and labelled as bugs

**Comment by sandersn** [comment]
@gabritto is the expert on comment preservation, but until she's able to start, @orta or @andrewbranch, can you take a look? I think you've worked with comments before.

File: src/services/codefixes/convertToTypeOnlyExport.ts [hunk 1]
```diff
@@ -44,7 +44,11 @@ namespace ts.codefix {
                     exportDeclaration.modifiers,
                     /*isTypeOnly*/ true,
                     exportClause,
-                    exportDeclaration.moduleSpecifier));
+                    exportDeclaration.moduleSpecifier),
+                {
```
Comment (andrewbranch) [inline src/services/codefixes/convertToTypeOnlyExport.ts:48]: This particular `changes.replaceNode` is so simple that it really should have been `changes.insertModifierBefore`, which would not only avoid clobbering the comments, but also preserve any other wacky formatting the user had chosen to write in the export declaration. A corresponding test might be converting something like

```ts
export {
  T1,
  T2,
  T3,
};
```

because I’m pretty sure as it is today, that one would get rewritten onto one line and lose its trailing comma.

**Review by keerthana1212 — APPROVED** [review]

File: src/services/codefixes/convertToTypeOnlyExport.ts (hunk 1 above)
Comment (Blasz) [reply src/services/codefixes/convertToTypeOnlyExport.ts:48]: Thanks for the review @andrewbranch. Did you want me to make that change or leave that for another PR?

Comment (andrewbranch) [reply src/services/codefixes/convertToTypeOnlyExport.ts:48]: It would be great if we can go ahead and do it here—I’m suggesting it primarily because it’s a better way to solve the comment problem.

Comment (andrewbranch) [reply src/services/codefixes/convertToTypeOnlyExport.ts]: I went ahead and pushed this change.

**Review by andrewbranch — APPROVED** [review]
Thanks!
