### PR TITLE
Check for undefined `source.symbol` when elaborating unmatched properties

### LINKED ISSUE #37014: Can't affect unknown to class with private field: Cannot read property 'flags' of undefined
**TypeScript Version:**  3.8.2

**Search Terms:** 'flags' of undefined

**Code**

```ts
export class Class {
  #field: any
}

const task: Class = {} as unknown
```

**Expected behavior:**

To give the compile error: Type 'unknown' is not assignable to type 'Class'.

**Actual behavior:**

Crashes with : 
```bash
/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:80993
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at reportUnmatchedProperty (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:40618:38)
    at propertiesRelatedTo (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:40663:25)
    at structuredTypeRelatedTo (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:40349:34)
    at recursiveTypeRelatedTo (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:40096:53)
    at isRelatedTo (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:39777:38)
    at checkTypeRelatedTo (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:39487:26)
    at checkTypeRelatedToAndOptionallyElaborate (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:38806:24)
    at checkTypeAssignableToAndOptionallyElaborate (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:38800:20)
    at checkVariableLikeDeclaration (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:52072:25)
    at checkVariableDeclaration (/Users/valentin/Zenika/Projects/cuillere/node_modules/typescript/lib/tsc.js:52136:20)
```

**Playground Link:** I didn't found a way to reproduce this behaviour in the playground.

**Related Issues:** #36871 and #36677

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #37014

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Forgot to include baselines 🤦‍♂️

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-3.8

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16239,6 +16239,7 @@ namespace ts {
                 if (unmatchedProperty.valueDeclaration
                     && isNamedDeclaration(unmatchedProperty.valueDeclaration)
                     && isPrivateIdentifier(unmatchedProperty.valueDeclaration.name)
+                    && source.symbol
```
Comment (a-tarasyuk) [inline src/compiler/checker.ts]: `source` uses the type `Type`. Based on the `Type` definition property `symbol` cannot be `undefined`.
https://github.com/microsoft/TypeScript/blob/56b6d0d6663b71588dea2cb5ccdd88ba904b0795/src/compiler/types.ts#L4365

Are there are other cases when `symbol` can be `undefined`? Maybe make sense to change type definition from `symbol: Symbol;` to `symbol: Symbol | undefined` in order to avoid such bugs?

What do you @DanielRosenwasser @RyanCavanaugh @weswigham think?
