### PR TITLE
Fix for incorrect 'this' type for optional call

### LINKED ISSUE #33798: Incorrect "'this' context of type" error on optional call
**TypeScript Version:**  3.7.0-dev.20101003

**Search Terms:**
this type optional call

**Code**

```ts
// @strictNullChecks: true
// @noImplicitAny: true
// @noImplicitThis: true
// @strictBindCallApply: false

function maybeBind<T, A extends any[], R>(
    obj: T,
    fn: ((this: T, ...args: A) => R) | undefined): ((...args: A) => R
) | undefined {
    return fn?.bind(obj);
}
```

**Expected behavior:**

Compiles successfully.

**Actual behavior:**

Reports the following error:
```
main.ts(2,12): error TS2684: The 'this' context of type '((this: T, ...args: A) => R) | 
undefined' is not assignable to method's 'this' of type 'Function'.
  Type 'undefined' is not assignable to type 'Function'.
```

**Playground Link:** http://www.typescriptlang.org/play/index.html?strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitReturns=false&alwaysStrict=false&ts=3.7-Beta#code/GYVwdgxgLglg9mABAWwIYE8BGBTAQjMAEwB4AVAGkQEFFsAPKbIgZ0VTHQG0BdSgJQB8ACjiYAVgC5EFRMDBShQqAAsYzKTIB021ACcA5uuoBKRAF4BiPqYA+icIWzAC2QsYVDtmvYalVTFla29kROLoSIAN4AUIhxiLrYUCC6SHIA-JqYBIQi4sYA3NEAvkA

### PR DESCRIPTION
**Pull request by rbuckton**
The `getSignatureApplicabilityError` function was not correctly handling optional method calls of the form `a?.b()`.

Fixes #33798

### CODE REVIEW

**Comment by rbuckton** [comment]
Found when I tried to change `maybeBind` in core.ts to use an optional property access: `fn?.bind(obj)`.

**Comment by rbuckton** [comment]
Build failure seems to be a lint rule that isn't failing locally. Did the definitions for `@types/node` change underneath us? Lint is warning that the `!` in `process.stdout.columns!` is unnecessary, but as far as I can tell it is still `number | undefined`.

File: src/testRunner/parallel/host.ts [hunk 1]
```diff
@@ -147,7 +147,7 @@ namespace Harness.Parallel.Host {
                 }
 
                 cursor.hide();
-                readline.moveCursor(process.stdout, -process.stdout.columns!, -this._lineCount);
+                readline.moveCursor(process.stdout, -process.stdout.columns!, -this._lineCount); // eslint-disable-line @typescript-eslint/no-unnecessary-type-assertion
```
Comment (weswigham) [inline src/testRunner/parallel/host.ts]: Un-suppress this lint - I think it was defs node updating under us, and we've since merged https://github.com/microsoft/TypeScript/pull/33784 which just fixed the lint.

**Comment by rbuckton** [comment]
Fixed the lint thing.
