### PR TITLE
Fix template string refactoring and nodeFactory bug

### LINKED ISSUE #40625: VSCode "Convert to template" refactor unescapes literals unexpectedly
**TypeScript Version:**  4.0, I think -- this is an issue with TS as bundled in VSCode
**VSCode Version:** 1.49.0

**Search Terms:** VSCode template string refactor

**Code**

Run the "convert to template string" refactor action in VSCode on a string concatenation with escape sequences like `"\b" + foo + "\f";`

**Expected behavior:**  Escape sequences are preserved, like `\b${foo}\f`;

**Actual behavior:** Escape sequences are converted to literal ASCII non-printable equivalents, resulting in "missing character" or other placeholders depending on font.

**Related Issues:** None, but might have been introduced by #37743 -- the author said to file a new issue.

### PR DESCRIPTION
**Pull request by elibarzilay**
Fix template string refactoring and nodeFactory bug

Instead of letting `createTemplate*` generate a broken raw string from
the cooked one, grab the source code for it.

Also, add a missing bit to `\`-quote `$`s.  As the comment in the code
says, it could just `\`-quote `${` since other `$`s are valid, but I
think that it's less confusing to always quote $s (but the change is in
the comment if minimalism is preferred).

Also, a small-but-confusing bug in `getCookedText()`.

Many tests for all of this.

Fixes #40625

### CODE REVIEW

**Comment by elibarzilay** [comment]
### Question

This is using `JSON.stringify` to do the escaping, which is generally fine but one possible improvement is handling NUL characters.  As is, they're converted to `\u0000`.  It might be better to make these convert to `\0` instead unless it's followed by a digit.  But this is rare and I'm not sure if it's worth the extra code.

**Comment by RyanCavanaugh** [comment]
ping @rbuckton

File: tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+// @Filename: /c.ts
+////let s = /*c1*/'${}' + text + "\\"/*c2*/;
+
+goTo.select("c1", "c2");
+edit.applyRefactor({
+    refactorName: "Convert to template string",
+    actionName: "Convert to template string",
+    actionDescription: ts.Diagnostics.Convert_to_template_string.message,
+    newContent: 'let s = `\\${}${text}\\\\`;'
```
Comment (andrewbranch) [inline tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts:33]: This is an incorrect result (it’s invalid syntax). It should be

```suggestion
    newContent: 'let s = `\${}${text}\\\\`;'
```

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts (hunk 1 above)
Comment (elibarzilay) [reply tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts:33]: @andrewbranch: I think that the quotes here are confusing: that `\\` is needed since the whole thing is in a ``'...`...`...'``, so it's actually `'`-quoted which needs the `\\`.  And to make it more confusing, that output is for the fourslash input which is quoted differently...  Two ways to see it more mechanically:

* Removing that `\` will leave a string that has a bad escape.

* Another way is to evaluate the code:

  ```ts
  > let text = "text";
  undefined
  > let s1 = /*c1*/'${}' + text + "\\"/*c2*/;     // the original form from the fourslash test w/ s1
  undefined
  > console.log('let s = `\\${}${text}\\\\`;');   // the string from this line, copied as-is
  let s = `\${}${text}\\`;
  > let s2 = `\${}${text}\\`;                     // copy it w/ s2
  undefined
  > s1 === s2
  true
  ```

Comment (andrewbranch) [reply tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts:33]: 🤦 of course. I’ve written my own fair share of double-escaped tests but totally read this one literally. My bad!

File: src/compiler/factory/nodeFactory.ts [hunk 2]
```diff
@@ -2843,6 +2843,8 @@ namespace ts {
         // @api
         function createTemplateLiteralLikeNode(kind: TemplateLiteralToken["kind"], text: string, rawText: string | undefined, templateFlags: TokenFlags | undefined) {
             const node = createBaseToken<TemplateLiteralLikeNode>(kind);
+            rawText ??= JSON.stringify(text).slice(1,-1).replace(/\\.|\$/g, s =>
```
Comment (rbuckton) [inline src/compiler/factory/nodeFactory.ts:2846]: I don't think we should try to synthesize `rawText` here. Generally when `rawText` is `undefined` we intend to pull the "raw" version of the template literal from the source file during emit. `rawText` was added to allow API consumers to pass their own "raw" text, and in those cases it goes through `createTemplateLiteralLikeNodeChecked` which verifies that the "cooked" text matches the supplied "raw" text.

If someone were to pass the string `"\t	"` (byte sequence `5c 74 09`) for `text`, this would generate a "raw" text of `"\t\t"`. There's no way to be 100% sure what the user intended, so its better to be explicit.

I think the issue is actually in the implementation of the refactor, which should be reading the raw source text of the string literal rather than `node.text`.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/compiler/factory/nodeFactory.ts (hunk 2 above)
Comment (rbuckton) [reply src/compiler/factory/nodeFactory.ts:2846]: Its also important that `rawText` remains `undefined` for our tagged template transform to accurately get the actual raw text from the source file for non-user-created nodes:

https://github.com/microsoft/TypeScript/blob/eb3645f16b66ed05110ea957c77773cea739bae8/src/compiler/transformers/taggedTemplate.ts#L78-L84

File: src/compiler/factory/nodeFactory.ts [hunk 3]
```diff
@@ -6133,7 +6133,7 @@ namespace ts {
         }
 
         let token = rawTextScanner.scan();
-        if (token === SyntaxKind.CloseBracketToken) {
+        if (token === SyntaxKind.CloseBraceToken) {
```
Comment (rbuckton) [inline src/compiler/factory/nodeFactory.ts:6136]: Obvious typo I wish I'd caught sooner 😔. Good catch.

File: src/services/refactors/convertStringOrTemplateLiteral.ts [hunk 4]
```diff
@@ -147,47 +147,66 @@ namespace ts.refactor.convertStringOrTemplateLiteral {
...
+    function concatConsecutiveString(index: number, nodes: readonly Expression[]): [number, string, string, number[]] {
         const indexes = [];
-        let text = "";
+        let text = "", rawText = "";
         while (index < nodes.length) {
             const node = nodes[index];
             if (isStringLiteralLike(node)) { // includes isNoSubstitutionTemplateLiteral(node)
-                text = text + node.text;
+                text = text + escapeStringForTemplate(node.text);
+                rawText = rawText + escapeStringForTemplate(getTextOfNode(node).slice(1, -1));
```
Comment (rbuckton) [inline src/services/refactors/convertStringOrTemplateLiteral.ts:174]:
```suggestion
                text += escapeStringForTemplate(node.text);
                rawText += escapeStringForTemplate(getTextOfNode(node).slice(1, -1));
```

File: src/services/refactors/convertStringOrTemplateLiteral.ts [hunk 5]
```diff
@@ -147,47 +147,66 @@ namespace ts.refactor.convertStringOrTemplateLiteral {
...
                 indexes.push(index);
                 index++;
             }
             else if (isTemplateExpression(node)) {
                 text = text + node.head.text;
+                rawText = rawText + getRawTextOfTemplate(node.head);
```
Comment (rbuckton) [inline src/services/refactors/convertStringOrTemplateLiteral.ts:180]:
```suggestion
                text += node.head.text;
                rawText += getRawTextOfTemplate(node.head);
```

File: src/services/refactors/convertStringOrTemplateLiteral.ts [hunk 6]
```diff
@@ -147,47 +147,66 @@ namespace ts.refactor.convertStringOrTemplateLiteral {
...
+        // but `\$${foo}` is likely more clear than the more-confusing-but-still-working `$${foo}`.
+    }
+
+    function getRawTextOfTemplate(node: TemplateHead | TemplateMiddle | TemplateTail) {
+        // in these cases the right side is ${
+        const rightShaving = isTemplateHead(node) || isTemplateMiddle(node) ? -2 : -1;
+        return getTextOfNode(node).slice(1, rightShaving);
+    }
+
+    function concatConsecutiveString(index: number, nodes: readonly Expression[]): [number, string, string, number[]] {
```
Comment (rbuckton) [inline src/services/refactors/convertStringOrTemplateLiteral.ts:167]: Just a suggestion for readability on the consumer side:

```suggestion
    function concatConsecutiveString(index: number, nodes: readonly Expression[]): [nextIndex: number, text: string, rawText: string, usedIndexes: number[]] {
```

File: src/services/refactors/convertStringOrTemplateLiteral.ts [hunk 7]
```diff
@@ -196,12 +215,17 @@ namespace ts.refactor.convertStringOrTemplateLiteral {
                     copyExpressionComments(span);
                     const nextSpan = currentNode.templateSpans[index + 1];
```
Comment (rbuckton) [inline src/services/refactors/convertStringOrTemplateLiteral.ts:216]: This is somewhat of a preexisting issue, but its better to do a bounds check (i.e. `index + 1 < currentNode.templateSpans.length`) rather than over-index, since an out-of-range indexed access results in a deopt in V8.

**Review by rbuckton — APPROVED** [review]
A few minor nits but this looks good.

File: src/services/refactors/convertStringOrTemplateLiteral.ts (hunk 4 above)
Comment (elibarzilay) [reply src/services/refactors/convertStringOrTemplateLiteral.ts:174]: That was the existing style in that code...  But anyway -- fixed.

File: src/services/refactors/convertStringOrTemplateLiteral.ts (hunk 7 above)
Comment (elibarzilay) [reply src/services/refactors/convertStringOrTemplateLiteral.ts:216]: Good to know; I further simplified it to just a boolean since the value wasn't used.
