### PR TITLE
Fixes making changes on JS imports 

### LINKED ISSUE #31312: Same code got error in js file but no error in ts file
- VSCode Version: 1.31.1
- OS Version: win10 family

Steps to Reproduce:

test.js
```
import axios from 'axios' // Import declaration conflicts with local declaration of 'axios'.ts(2440)
axios.defaults.timeout = 22
```
In js file, the second line causes an error showing on first line. 
But if this two lines are in ts file (change file suffix to ts), there is no error.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by orta**
Fixes #31312  ( and #26912 )

The longer story can be found in https://github.com/microsoft/TypeScript/issues/26912 - but essentially this short-circuits the check for alias symbols when making assignments to an import in JavaScript code

4145fef aims to address https://github.com/microsoft/TypeScript/issues/26912#issuecomment-436419283

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -30004,7 +30004,9 @@ namespace ts {
         function checkImportBinding(node: ImportEqualsDeclaration | ImportClause | NamespaceImport | ImportSpecifier) {
             checkCollisionWithRequireExportsInGeneratedCode(node, node.name!);
             checkCollisionWithGlobalPromiseInGeneratedCode(node, node.name!);
-            checkAliasSymbol(node);
+            if (!isInJSFile(node) || languageVersion < ScriptTarget.ES2020) {
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: I think you want to skip reporting error and not checking the symbol.

Comment (orta) [reply src/compiler/checker.ts]: I see, move it closer to the error emission 👍

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -29973,8 +29973,11 @@ namespace ts {
         function checkAliasSymbol(node: ImportEqualsDeclaration | ImportClause | NamespaceImport | ImportSpecifier | ExportSpecifier) {
             const symbol = getSymbolOfNode(node);
             const target = resolveAlias(symbol);
-            if (target !== unknownSymbol) {
-                // For external modules symbol represent local symbol for an alias.
+
+            const shouldSkipWithJSRequireTargets = !isInJSFile(node) && moduleKind !== ModuleKind.ES2015;
```
Comment (weswigham) [inline src/compiler/checker.ts]: I find an ad-hoc change like this suspect (despite our JS support being littered with them). You [said](https://github.com/microsoft/TypeScript/issues/31312#issuecomment-516441263) the differences were caused by the symbol being bound with different flags in JS vs in TS - would that not imply that the appropriate fix lies in adjusting what flags the symbol is bound with, or using the symbol flags that are already different to change the behavior (and not walking up the node tree to find the context file)?

Comment (orta) [reply src/compiler/checker.ts]: OK makes sense, I've changed it - I'm a *little* worried now that before I felt like I definitely got what was going on previously, and now I partially get the change.

Comment (weswigham) [reply src/compiler/checker.ts]: The only flag you should need to check here is `Assignment` - `Module` comes from the thing being a module, and `Alias` (`AliasExcludes === Alias`, so, y'know, if you see `AliasExcludes` in the debug otuput it means `Alias`) from the thing being an import. Also, you should be able to check for that _instead_ of `isInJSFile(node) && moduleKind !== ModuleKind.ES2015`, not in addition to.

Comment (orta) [reply src/compiler/checker.ts]: Ergh, I'm so sure I tried that earlier and got a tonne of fails. Thanks yeah, that's exactly what it needed.

Comment (weswigham) [reply src/compiler/checker.ts]: Yeah, the `Assignment` symbol flag is used to mean "allow unusual symbol merges, don't issue an error, deal with the result", since what you wanna suppress here is an error, checking just for that flag means sense.
