### PR TITLE
fix paste edits range: include all completely selected identifiers

### LINKED ISSUE #60246: No paste edits returned
From #59539

### 🔎 Search Terms

- paste imports

### 🕗 Version & Regression Information

5.7.0-dev.20241015

### 💻 Code

1. Using a VS Code starter extension created with `yo code`

```ts
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import { log } from 'console';
import * as vscode from 'vscode';

// This method is called when your extension is activated
// Your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "test-ext" is now active!');



}

// This method is called when your extension is deactivated
export function deactivate() { }
```

2. Create a second file `other.ts`:

```ts
import { window } from "vscode";

window.createWebviewPanel({});
```

3. Enable paste with imports
3. In `other.ts` copy `window.createWebviewPanel({});` and paste it into into the body of `activate`

### 🙁 Actual behavior
No edits returned from `getPasteEdits`:

```
    {"seq":0,"type":"response","command":"getPasteEdits","request_seq":34,"success":true,"performanceData":{"updateGraphDurationMs":6.14574999999968},"body":{"edits":[],"fixId":"providePostPasteEdits"}}
```

Here's the full log: [tsserver.log](https://github.com/user-attachments/files/17400770/tsserver.log)

### PR DESCRIPTION
**Pull request by iisaduan**
Fixes #60246

When checking usage info for paste edits, adjust the range to be node-based instead of purely position based, so identifiers at the edges of the copied range can be correctly resolved. Because of how whitespace/trivia is included in nodes, before, if trivia wasn't completely copied, some identifiers were skipped when checking for usage.

Only the first commit is the bug fix, the rest are tests and a small refactor in `pasteEdits`.

### CODE REVIEW

File: src/services/pasteEdits.ts [hunk 1]
```diff
@@ -167,3 +175,16 @@ function pasteEdits(
         );
     });
 }
+
+function getUsageInfoRangeForPasteEdits({ file: sourceFile, range }: CopiedFromInfo) {
+    // This function adjusts the range so that identifiers at the edges of the copied text are correctly included for imports.
+    // We do not need to adjust range when the tokens at the edges are not identifiers.
```
Comment (sandersn) [inline src/services/pasteEdits.ts:181]: This should be jsdoc. At least, it seems like the comments are intended for callers of the function.

**Review by sandersn — APPROVED** [review]
