### PR TITLE
[Release-2.0.5] Address how Chakra load globalization dll

### LINKED ISSUE #11110: TypeScript Tools for VS 2015 2.0.2.0 Beta not working (on Windows Server 2012??)
**TypeScript Version:**  2.0.2.0

I was using VS2015 Update 3 with the built-in TypeScript tool, version 1.8.6 succesfully. 

Today I tried to upgrade it using TypeScript Tools for VS 2015 2.0.2.0 Beta. After installing the tools successfully, there's no more auto-completion in VS (the syntax highlight is still there). And the Build command exits with error.

I decided to roll back to 1.8.6 so I uninstalled 2.0.2.0 Beta. I checked that the TypeScript folder under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft` and `C:\Program Files (x86)\Microsoft SDKs` are gone. But executing the TypeScript_Dev14Full.exe (1.8 version) doesn't recreate those folders again.

So I had to switch back to 2.0 again. I installed it once again. Now after opening my TypeScript project there is even no syntax highlighting, not to mention auto completion and Build, and upon open project properties it shows
```
An error occurred trying to load the page.
No exports were found that match the constraint: 
	ContractName	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
	RequiredTypeIdentity	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
```
I've been Googling for hours but I haven't found any workable solutions. One of the issues I found at https://github.com/Microsoft/TypeScript/issues/7519 bears the most similar symptoms and it suggests delete the `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache` folder. I did that and it did not work and it shows a message saying 'An exception has been encountered. This may be caused by an extension.' and it asks me to check the ActivityLog.xml 
[ActivityLog.txt](https://github.com/Microsoft/TypeScript/files/490784/ActivityLog.txt) here is the txt version since github doesn't support xml. Please take a look if it's helpful.

I haven't seen any other posts that describe situations similar to mine.

Please help.

**Expected behavior:**
TypeScript Tools for VS 2015 2.0.2.0 Beta work properly.

**Actual behavior:** 
It does not. See descriptions above.

### PR DESCRIPTION
**Pull request by yuit**
Fix #11110

### CODE REVIEW

File: src/services/navigationBar.ts [hunk 1]
```diff
@@ -326,7 +326,7 @@ namespace ts.NavigationBar {
     }
 
     // More efficient to create a collator once and use its `compare` than to call `a.localeCompare(b)` many times.
-    const collator: { compare(a: string, b: string): number } = typeof Intl === "undefined" ? undefined : new Intl.Collator();
+    const collator: { compare(a: string, b: string): number } = typeof Intl === "object" && typeof Intl.Collator === "function" ? new Intl.Collator() : undefined;
```
Comment (mihailik) [inline src/services/navigationBar.ts]: Incomplete check, `typeof null==="object"` too.

I'll submit a PR.
