### PR TITLE
Fix array spread with sideeffects

### LINKED ISSUE #32959: Destructuring array polyfill isn't equivalent to new JS
Same deal as https://github.com/microsoft/TypeScript/issues/31469

**Search Terms:** Destructuring array Polyfill concat

**Code**

```ts
const k = [1, 2];
const o = [3, ...k, k[0]++];
console.log(o.join(", "));
```

**Compiles to**
```js
var k = [1, 2];
var o = [3].concat(k, [k[0]++]);
console.log(o.join(", "));
```
Or, on latest:
```js
"use strict";
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var k = [1, 2];
var o = __spreadArrays([3], k, [k[0]++]);
console.log(o.join(", "));
```
**Expected behavior:** 3, 1, 2, 1

**Actual behavior:** 3, 2, 2, 1

**Playground Link:** https://www.typescriptlang.org/play/index.html?target=1#code/MYewdgzgLgBA1jAvDA2gRgDQwEwF0DcAUKJLCEqgMxYB0dcWcKADLgNRsHHgQgA2AUxp8QAcwAUIGgCsQASzDiARFiUBKNfiA

**Related Issues:** https://github.com/microsoft/TypeScript/issues/31469

The solution is the same as https://github.com/microsoft/TypeScript/pull/32514. You can only `concat`/`__spreadArrays` one array at a time.

Also applies to call stacks:
```ts
let arr = [0];
console.log(...arr, arr[0]++);
```
Expected: 0, 0
Got: 1, 0

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes array spread when there may be side effects, using a similar approach as #31469. As a result of these changes, both the `__spread` and `__spreadArrays` helpers are now deprecated as they are no longer used. The helpers remain in _emitHelpers.ts_ in case they are needed as part of `--build`.

Fixes #32959

### CODE REVIEW

File: src/compiler/factory/emitHelpers.ts [hunk 1]
```diff
@@ -886,6 +888,7 @@ namespace ts {
             templateObjectHelper,
             spreadHelper,
```
Comment (rbuckton) [inline src/compiler/factory/emitHelpers.ts:889]: @sheetalkamat, do I need to leave these in for project references leveraging `.tsbuildinfo`, or can I safely remove them?

Comment (sheetalkamat) [reply src/compiler/factory/emitHelpers.ts:889]: you dont need to leave these since new version = new tsbuildinfo.

File: tests/baselines/reference/tsbuild/outfile-concat/initial-build/multiple-emitHelpers-in-different-projects.js [hunk 2]
```diff
@@ -304,26 +304,6 @@ sourceFile:../second/second_part2.ts
 >>>//# sourceMappingURL=second-output.d.ts.map
 
 //// [/src/2/second-output.js]
-var __read = (this && this.__read) || function (o, n) {
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsbuild/outfile-concat/initial-build/multiple-emitHelpers-in-different-projects.js:307]: can you please modify the test case to use multiple emit helpers given this one removes it completely.

**Review by nitish-awasthi — APPROVED** [review]

**Comment by rbuckton** [comment]
@sheetalkamat did you have any other feedback?

**Comment by rbuckton** [comment]
NOTE: The `tslib` change for this is here: https://github.com/microsoft/tslib/pull/133

**Review by weswigham — APPROVED** [review]

**Comment by rbuckton** [comment]
The `tslib` changes probably need to be merged and shipped before this is merged and goes in a nightly.

**Review by sheetalkamat — APPROVED** [review]

**Comment by rbuckton** [comment]
A new tslib has shipped. I will merge this once I resolve some new merge conflicts.
