### PR TITLE
fix(42714): "Infer function return type" is annoyingly suggested in function bodies

### LINKED ISSUE #42714: "Infer function return type" is annoyingly suggested in function bodies
```ts
function foo() {
    let x = 123;
    return x;
}
```

If your cursor is *anywhere* in the body of this function, you will get a code action to "Infer function return type".

This is annoying because it always provides a lightbulb in the editor

image

and that is doubly-annoying in cases where you think you have a quick fix but it ends up being the same useless code action.

image

I'm not exactly sure what the right way is to surface this refactoring in a way that's not intrusive. Maybe by only providing it on `return` statements and the function signature itself? Thoughts @jessetrinity @sandersn?

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #42714

### CODE REVIEW

File: tests/cases/fourslash/refactorInferFunctionReturnType16.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/// <reference path='fourslash.ts' />
+
+////function /*a*/f/*c*/()/*d*//*b*/ /*e*/{
+////    /*g*/return { x: 1, y: 1 };/*h*/
+////}/*f*/
+
+goTo.select("a", "b");
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/refactorInferFunctionReturnType16.ts:7]: Can we have a few tests (you can reuse these files) for positions rather than ranges?

Comment (a-tarasyuk) [reply tests/cases/fourslash/refactorInferFunctionReturnType16.ts:7]: Do you mean 1 selection range per file?

File: src/services/refactors/inferFunctionReturnType.ts [hunk 2]
```diff
@@ -59,7 +59,9 @@ namespace ts.refactor.inferFunctionReturnType {
         if (isInJSFile(context.file) || !refactorKindBeginsWith(inferReturnTypeAction.kind, context.kind)) return;
 
         const token = getTokenAtPosition(context.file, context.startPosition);
-        const declaration = findAncestor(token, isConvertibleDeclaration);
+        const declaration = findAncestor(token, n =>
+            isBlock(n) || isParameter(n) || n.parent && isArrowFunction(n.parent) && (n.kind === SyntaxKind.EqualsGreaterThanToken || n.parent.body === n) ? "quit" :
```
Comment (jessetrinity) [inline src/services/refactors/inferFunctionReturnType.ts:63]: I would want the refactor to show up if the cursor were anywhere inside the parameters (I think just removing the quit `isParameter` should do that). It would be pretty awkward to have to select the whole list to see it.

**Review by jessetrinity — CHANGES_REQUESTED** [review]

File: tests/cases/fourslash/refactorInferFunctionReturnType16.ts (hunk 1 above)
Comment (jessetrinity) [reply tests/cases/fourslash/refactorInferFunctionReturnType16.ts:16]: You can use zero width spans for checking if the refactor is offered when the cursor is at a position but no span is selected,

```ts
////function f1(/*a*//*b*/x, y) {
////    return x + y;
////}
```

There are some verifiers for trigger reason if you want different behavior when `ctrl` + `shift` + `r` is invoked, but I don't think there is a case for that here (maybe on the return statement?)
`verify.not.refactorAvailableForTriggerReason("implicit", Infer function return type);`
`verify.refactorAvailableForTriggerReason("invoked", Infer function return type);`

File: tests/cases/fourslash/refactorKind_rewriteFunction.ts [hunk 3]
```diff
@@ -7,6 +7,5 @@ verify.refactorKindAvailable("refactor.rewrite",
 [
     "refactor.rewrite.arrow.braces.add",
     "refactor.rewrite.function.named",
-    "refactor.rewrite.function.anonymous",
-    "refactor.rewrite.function.returnType"
```
Comment (jessetrinity) [inline tests/cases/fourslash/refactorKind_rewriteFunction.ts:11]: Can you add another example in this test that will work for `"refactor.rewrite.function.returnType"`? This is here to make sure that requesting this refactor by name gives us what we want.

File: tests/cases/fourslash/refactorInferFunctionReturnType16.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/refactorInferFunctionReturnType16.ts:16]: @jessetrinity Thanks for the detailed clarification. ;), I didn't know about it.

File: tests/cases/fourslash/refactorKind_rewriteFunction.ts (hunk 3 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/refactorKind_rewriteFunction.ts]: @jessetrinity Changed code sample to have `"refactor.rewrite.function.returnType"`.

**Review by jessetrinity — APPROVED** [review]
Looks good, thank you!
