### PR TITLE
Fix initializer widening

### LINKED ISSUE #29189: Default values don't widen types of destructed values in function parameters (regression)
**TypeScript Version:**  3.3.0-dev.20181228

**Search Terms:**

**Code**

```ts
declare function f(g: (as: string[]) => void): void
f(([_1, _2 = undefined]) => undefined)
```

**Expected behavior:**

pass

**Actual behavior:**

Error at `_2`:

```
Error TS2322: Type 'undefined' is not assignable to type 'string'.
```
**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #29189.

### CODE REVIEW

**Comment by weswigham** [comment]
You didn't add a test for #29189 - you set `strict: true`, but the report is for non-strict mode. And the behavior is _very_ different here, so it matters.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4919,7 +4919,7 @@ namespace ts {
             if (strictNullChecks && declaration.initializer && !(getFalsyFlags(checkDeclarationInitializer(declaration)) & TypeFlags.Undefined)) {
                 type = getTypeWithFacts(type, TypeFacts.NEUndefined);
             }
-            return declaration.initializer && !getContextualTypeForVariableLikeDeclaration(walkUpBindingElementsAndPatterns(declaration)) ?
+            return declaration.initializer && !getEffectiveTypeAnnotationNode(walkUpBindingElementsAndPatterns(declaration)) ?
```
Comment (weswigham) [inline src/compiler/checker.ts]: I not sure think this is right to change. Outside of strict mode, isn't this is going to make an `undefined` initializer (with a contextual type) be `any` instead of the correct contextual type.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: It's the right change (it basically just reverts the change that you had made). In classic checking mode this makes a variable of type `string` as expected.

**Comment by ahejlsberg** [comment]
> You didn't add a (full) test for #29189 - you set strict: true, but the report is also for non-strict mode (as far as I can tell). And the behavior is very different here, so it matters.

I added `--strict` because the issue only shows up with strict null checks enabled.
