### PR TITLE
Fix object spread+async emit

### LINKED ISSUE #12203: Async Fn with fat arrows fail when it contains an object spread
**TypeScript Version:**  2.2.0-dev.20161112

An async function returning an object with an object spread creates the yield but the wrapping function isn't a generator:

**Code**

```ts
function rootConnection(name: string) {
  return {
    resolve: async (context, args) => {
      const { objects } = await apiService.getMany(name);
      return {
        ...connectionFromArray(objects, args)
      };
    }
  };
}
rootConnection('test');
```

**Compiled into:**
```js
function rootConnection(name) {
    return __assign({ resolve: (context, args) => {
            const { objects } = yield apiService.getMany(name);
            return __assign({}, connectionFromArray(objects, args));
        } });
}
rootConnection('test');
```

If I remove the object spread, the compiled code creates a generator wrapper for the yield

**Code**
```ts
function rootConnection(name: string) {
  return {
    resolve: async (context, args) => {
      const { objects } = await apiService.getMany(name);
      return {
        // ...connectionFromArray(objects, args)
      };
    }
  };
}
rootConnection('test');
```

**Compiled into:**
```js
function rootConnection(name) {
    return {
        resolve: (context, args) => __awaiter(this, void 0, void 0, function* () {
            const { objects } = yield apiService.getMany(name);
            return {};
        })
    };
}
rootConnection('test');
```

**Expected behavior:**
Generator to wrap the yield

**Actual behavior:** 
No generator, so get an error that yield is a strict reserved word:
```
const { objects } = yield apiService.getMany(name);
                    ^^^^^
SyntaxError: Unexpected strict mode reserved word
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #12203 

1. Retain function modifiers. They were previously dropped, breaking async transforms in ES2017.
2. Do not emit __assign for object literals with no spreads, just visit children.
3. Call aggregateTransformFlags after creating an __assign call.

### CODE REVIEW

**Comment by mhegazy** [comment]
@rbuckton can you take a look.

File: src/compiler/transformers/esnext.ts [hunk 1]
```diff
@@ -256,7 +260,7 @@ namespace ts {
                 visitEachChild(node.body, visitor, context);
             return setOriginalNode(
                 createFunctionExpression(
-                    /*modifiers*/ undefined,
+                    node.modifiers,
```
Comment (rbuckton) [inline src/compiler/transformers/esnext.ts]: You don't seem to be visiting methods or accessors in this transformer.

Comment (sandersn) [inline src/compiler/transformers/esnext.ts]: Hmm. Good point. I'll confirm that they don't work and put them in a separate PR I think.
