### PR TITLE
25667 - getModifiedTime has wrong return type

### LINKED ISSUE #25667: ts.sys.getModifiedTime has wrong return type
Tiny issue. `ts.sys.getModifiedTime` has the following signature:
```ts
getModifiedTime?(path: string): Date;
```
But it actually returns `undefined` for invalid paths.

**TypeScript Version:**  2.9.2

**Search Terms:** 
getModifiedTime

**Code**

```ts
const modifiedTime = ts.sys.getModifiedTime(`/invalid/path`)
```

**Expected behavior:**
Signature should match implementation. In this case:
```ts
getModifiedTime?(path: string): Date | undefined;
```
**Actual behavior:**
Return type can be undefined
**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #25667

### CODE REVIEW

**Comment by mhegazy** [comment]
@sheetalkamat and @andy-ms can you please review this change.

File: src/compiler/tsbuild.ts [hunk 1]
```diff
@@ -1058,7 +1063,7 @@ namespace ts {
             }
 
             const inputTime = host.getModifiedTime(inputFile);
-            if (inputTime > newestInputFileTime) {
+            if (inputTime !== undefined && inputTime > newestInputFileTime) {
```
Comment (DanielRosenwasser) [inline src/compiler/tsbuild.ts]: Can you do a single check up-front? Plus, it doesn't seem like we're now actually handling `undefined`, we're just doing observably nothing.

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: Ok, will move.

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: Ok, will move. Maybe would be better to set a default value in order to avoid checking on undefined, like it was done in this case https://github.com/a-tarasyuk/TypeScript/blob/550710d2a2ce019dfc7ba8120b112e635fb5d9dc/src/compiler/sys.ts#L306. what do you think?

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: This condition was changed because program uses https://github.com/a-tarasyuk/TypeScript/blob/550710d2a2ce019dfc7ba8120b112e635fb5d9dc/src/compiler/program.ts#L194 `sys.getModifiedTime` where was added `undefined`

Comment (andy-ms) [reply src/compiler/tsbuild.ts]: If we haven't run into `undefined` errors before, we're likely always be passing valid paths. So dropping every exception at the implementation of `function getModifiedTime` using `catch (e) { return undefined; }` was probably the wrong choice in the first place.

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: This condition has been changed because the program uses https://github.com/a-tarasyuk/TypeScript/blob/550710d2a2ce019dfc7ba8120b112e635fb5d9dc/src/compiler/program.ts#L194 `sys.getModifiedTime` where has been added `undefined`

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: @andy-ms Thanks. 

> So dropping every exception at the implementation of `function getModifiedTime` using `catch (e) { return undefined; }` was probably the wrong choice in the first place.

Do I need to remove this `catch`? If yes, how to handle incorrect file modified time? What do you think which the best option for this case?

Comment (andy-ms) [reply src/compiler/tsbuild.ts]: @sheetalkamat Thoughts?

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: @sheetalkamat could you check these changes? thanks in advance.

Comment (sheetalkamat) [reply src/compiler/tsbuild.ts]: @andy-ms we shouldnt assume that getModifiedTime would be called only on present files.
@a-tarasyuk You are on right track. Please use ```inputTime = host.getModifiedTime(inputFile) || missingFileModifiedTime;``` instead of additional checks.

Comment (a-tarasyuk) [reply src/compiler/tsbuild.ts]: @sheetalkamat thank you very much. I'll add changes and re-open PR.

File: src/compiler/tsbuild.ts [hunk 2]
```diff
@@ -843,14 +843,21 @@ namespace ts {
...
+                buildHost.verbose(Diagnostics.Updating_output_timestamps_of_project_0, proj.options.configFilePath!);
+            }
+
             const now = new Date();
             const outputs = getAllProjectOutputs(proj);
             let priorNewestUpdateTime = minimumDate;
             for (const file of outputs) {
                 if (isDeclarationFile(file)) {
-                    priorNewestUpdateTime = newer(priorNewestUpdateTime, compilerHost.getModifiedTime!(file));
+                    const fileModifiedTime = compilerHost.getModifiedTime!(file);
```
Comment (sheetalkamat) [inline src/compiler/tsbuild.ts]: Why cant you have this or with missingFileModifiedTime ?

**Comment by a-tarasyuk** [comment]
@sheetalkamat thanks, fixed.
