### PR TITLE
In insertNodeAfter, handle file with no trailing newline

### LINKED ISSUE #23728: Error with insertNodeAfter in file with no trailing newline
To reproduce, go to `moveToNewFile_updateUses.ts` (as of #23726) and remove the line that's only `////`. You will then get the text `import·{·x·}·from·"./a";import·{·y·}·from·"./y";` for `/user.ts`.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #23728

### CODE REVIEW

File: tests/cases/fourslash/convertFunctionToEs6Class_commentOnVariableDeclaration.ts [hunk 1]
```diff
@@ -8,7 +8,8 @@
 verify.codeFix({
     description: "Convert function to an ES2015 class",
     newFileContent:
-`/** Doc */
+`
```
Comment (amcasey) [inline tests/cases/fourslash/convertFunctionToEs6Class_commentOnVariableDeclaration.ts]: This doesn't seem great.  What is the comment being inserted after that is resulting in the blank line?

Comment (andy-ms) [reply tests/cases/fourslash/convertFunctionToEs6Class_commentOnVariableDeclaration.ts]: The way `convertFunctionToEs6Class` works, we are deleting the function and adding a class node after it. In textChanges we don't know that the function is going to be deleted, so we add a newline to separate the old function and the new class. Added an issue at #23871
