### PR TITLE
Disallow expression with type parameters as left side of property access

### LINKED ISSUE #49293: Different behavior for `a?.b<c>.d` depending on the compilation target
# Bug Report

### 🔎 Search Terms

instantiation expression optional chaining target

### 🕗 Version & Regression Information

This feature has been introduced in 4.7. I tested 4.7.0-dev.20220528

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&ts=4.8.0-dev.20220528#code/IYfgdARgPAxgfGAJkA)

### 💻 Code

```ts
a?.b<c>.d
```

### 🙁 Actual behavior

When targeting <=ES2019 it generates `(a === null || a === void 0 ? void 0 : a.b).d`, while when targeting >=ES2020 it generates `a?.b.d`.

They have different behaviors: in the ES2019 output it always reads `.d`, while in the ES2020 output it only reads `.d` if `a` is not nullish.

### 🙂 Expected behavior

They should have the same behavior.

The ES2020 behavior feels more useful, but "adding `<c>` to an optional chain ends the optional context" (as wrapping it in parentheses does) would be ok too as long as it's consistent. You would then have to write `a?.b<c>?.d`.

(Babel's implementation has the same different behavior depending on the target, so this is apparently something very easy to overlook while implementing instantiation expressions :grimacing:)

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #49293

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -5605,6 +5605,10 @@ namespace ts {
                 }
 
                 if (isPropertyAccess) {
+                    // TODO: issue a better error?
+                    if (expression.kind === SyntaxKind.ExpressionWithTypeArguments) {
```
Comment (jakebailey) [inline src/compiler/parser.ts:5609]: This might not be right; I think I need to do a lookahead parse above instead so this doesn't return having consumed the `.` or `?.`.

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -1493,6 +1493,10 @@
         "category": "Message",
         "code": 1476
     },
+    "Instantiation expression cannot be followed by property access.": {
```
Comment (jakebailey) [inline src/compiler/diagnosticMessages.json:1496]: Should this instead complain on the type arguments and say they should be removed? And quickfix?

**Comment by sandersn** [comment]
Can you remind me why we decided to make this a grammar check?

**Comment by jakebailey** [comment]
This was the suggestion by @ahejlsberg, as a potentially better recovery method. But, I think #49645's method here is better; the tree is the same in both cases, but it correctly fires when it's done in the parser (whereas grammar checks do not always fire).

**Comment by jakebailey** [comment]
Updated to be in the parser, and to move the error message onto the type parameters.

**Review by sandersn — APPROVED** [review]
