### PR TITLE
Fix indexing and destructuring of unions of tuple types

### LINKED ISSUE #27543: Union of tuple types destructures incorrectly
**TypeScript Version:**  3.2.0-dev.20181004
**Search Terms:** union tuple array destructuring
**Code**

```ts
type Unioned = [string] | [string, number]
const ex: Unioned = ["hi"] as Unioned

// unexpected: y is typed as string | number, instead of number | undefined
const [x, y] = ex;
```

**Expected behavior:**
`y` typed as `number | undefined`

**Actual behavior:**
`y` typed as `string | number`

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=type%20Unioned%20%3D%20%5Bstring%5D%20%7C%20%5Bstring%2C%20number%5D%0Aconst%20ex%3A%20Unioned%20%3D%20%5B%22hi%22%5D%20as%20Unioned%0A%0A%2F%2F%20unexpected%3A%20y%20is%20typed%20as%20string%20%7C%20number%0Aconst%20%5Bx%2C%20y%5D%20%3D%20ex%3B)

**Related Issues:** Not really

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes several issues relating to indexing and destructuring of unions of tuple types. In particular, we now reflect that elements beyond the end of a fixed length tuple are known to be `undefined`, and we properly account for rest elements in unions of typle types. Some examples:

```ts
type T = [boolean] | [string, number];
type T0 = T[0];  // string | boolean
type T1 = T[1];  // number | undefined
type T2 = T[2];  // *Error*
type TX = T[number];  // string | number | boolean

type U = [boolean] | [string, ...number[]];
type U0 = U[0];  // string | boolean
type U1 = U[1];  // number | undefined
type U2 = U[2];  // number | undefined
type UX = U[number];  // string | number | boolean
```

Note that when indexing with a constant (thus selecting an element at a known index), we properly account for the possibility of `undefined`, but when indexing with a non-constant (as in `T[number]`), we assume that the index value is within range.

Fixes #27543.

### CODE REVIEW

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -36,23 +36,6 @@ namespace ts {
...
     }
 
-    function getPriorityValues(highPriorityValue: number): [number, number, number] {
-        const mediumPriorityValue = highPriorityValue * 2;
-        const lowPriorityValue = mediumPriorityValue * 4;
-        return [highPriorityValue, mediumPriorityValue, lowPriorityValue];
-    }
-
-    function pollingInterval(watchPriority: PollingInterval): number {
-        return pollingIntervalsForPriority[watchPriority];
```
Comment (ahejlsberg) [inline src/compiler/sys.ts]: The line above causes an error with this PR because we now correctly include `undefined` in the type because `watchPriority` is one of the values 250, 500, or 2000, all of which are out of range of the tuple type. This code is basically bogus, but also never used.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9311,11 +9311,8 @@ namespace ts {
                         getFlowTypeOfReference(accessExpression, propType) :
                         propType;
                 }
-                if (isTupleType(objectType)) {
-                    const restType = getRestTypeOfTupleType(objectType);
-                    if (restType && isNumericLiteralName(propName) && +propName >= 0) {
-                        return restType;
-                    }
+                if (everyType(objectType, isTupleType) && isNumericLiteralName(propName) && +propName >= 0) {
+                    return mapType(objectType, t => getRestTypeOfTupleType(<TupleTypeReference>t) || undefinedType);
```
Comment (weswigham) [inline src/compiler/checker.ts]: Hm, this isn't using a `undefinedWideningType` which means outside of `strict` mode, the new types are going to be strictly less permissive than they were before. Are we OK with that?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: They're going to be less permissive no matter which `undefined` we use because previously, when the object type was a union type, we'd just fall back to the numeric index signature. For example:

```ts
type T = [boolean] | [string, number];
type T0 = T[0];  // Unchanged, string | boolean
type T1 = T[1];  // Now number | undefined, previously number | boolean
type T2 = T[2];  // Now undefined, previously string | number | boolean
```

I would argue that the non-widening `undefined` is the right choice above. In non-strict mode, the only time you'd ever observe a difference is when it is not in a union with something else, i.e. `T2` above. I don't think we'd help anybody if `T2` was magically going to widen to `any`.

**Comment by ajafff** [comment]
Why is `type T2 = T[2];` not an error? It will never be defined, so why allow access to that element using a constant?

**Comment by ahejlsberg** [comment]
> Why is type T2 = T[2]; not an error? It will never be defined, so why allow access to that element using a constant?

Indeed. It is already an error in an expression position, but inconsistently so (and with a different message from what we use elsewhere). With the latest commits we now have common error reporting for expression and type positions.

**Comment by ahejlsberg** [comment]
@RyanCavanaugh You want to give this a look?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -9311,11 +9311,13 @@ namespace ts {
                         getFlowTypeOfReference(accessExpression, propType) :
                         propType;
                 }
-                if (isTupleType(objectType)) {
-                    const restType = getRestTypeOfTupleType(objectType);
-                    if (restType && isNumericLiteralName(propName) && +propName >= 0) {
-                        return restType;
+                if (everyType(objectType, isTupleType) && isNumericLiteralName(propName) && +propName >= 0) {
+                    const restType = mapType(objectType, t => getRestTypeOfTupleType(<TupleTypeReference>t) || undefinedType);
+                    if (restType === undefinedType && accessNode) {
```
Comment (weswigham) [inline src/compiler/checker.ts]:
```ts
type UndefinedTuple = [string, ...undefined[]]; // ???
```

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -12877,9 +12879,17 @@ namespace ts {
...
-            return isTupleType(type) ?
-                index < getLengthOfTupleType(type) ? type.typeArguments![index] : getRestTypeOfTupleType(type) :
-                getTypeOfPropertyOfType(type, "" + index as __String);
+            const propType = getTypeOfPropertyOfType(type, "" + index as __String);
+            if (propType) {
+                return propType;
+            }
+            if (everyType(type, isTupleType)) {
+                const restType = mapType(type, t => getRestTypeOfTupleType(<TupleTypeReference>t) || undefinedType);
+                if (restType !== undefinedType) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Yeah, same remark - this needs to use a unique marker and not the `undefinedType` to signal the `restType`'s return, as it prevents a legitimate `undefined` rest type from functioning.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Now fixed.

Comment (weswigham) [reply src/compiler/checker.ts]: `getTupleElementType` still handles `undefinedType` incorrectly.

**Comment by weswigham** [comment]
@ahejlsberg we might not want to return `undefined` in all cases and might prefer the passed in `missingType` instead, since always using `undefined` gives follow-on errors like this:
```ts
                    noticeModel.attachments[0].content.buttons[1] = secondButton;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!! error TS2322: Type '{ readonly title: string; readonly actionUri: string; readonly actionTarget?: "" | "browser" | "inappbrowser" | undefined; } & { title: string; }' is not assignable to type 'undefined'.
                                                               ~
!!! error TS2339: Property '1' does not exist on type '[{ readonly title: string; readonly actionUri: string; readonly actionTarget?: "" | "browser" | "inappbrowser" | undefined; }]'.
```
(snipped from RWC)
