### PR TITLE
correctly merge const enum only and instantiated modules irregardless of order

### LINKED ISSUE #2381: Imports are incorrectly elided in the presence of const enums
```ts
module Outer {
    export var x = 1;
}

module Outer {
    export const enum A { X }
}

module B {
    import O = Outer;
    var x = O.A.X;
    var y = O.x;
}
```

Output:
```javascript
var Outer;
(function (Outer) {
    Outer.x = 1;
})(Outer || (Outer = {}));
var B;
(function (B) {
    var x = 0 /* X */;
    var y = O.x; // import for O is elided
})(B || (B = {}));

```

### PR DESCRIPTION
**Pull request by vladima**
Fixes #2381

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -322,13 +322,14 @@ module ts {
...
+                    if (node.symbol.constEnumOnlyModule === undefined) {
+                        // non-merged case - use the current state
+                        node.symbol.constEnumOnlyModule = currentModuleIsConstEnumOnly;
                     }
-                    else if (node.symbol.constEnumOnlyModule) {
-                        // const only value module was merged with instantiated module - reset flag
-                        node.symbol.constEnumOnlyModule = false;
+                    else {
+                        // merged case: module is const enum only if all its pieces are non-instantiated or const enum
+                        node.symbol.constEnumOnlyModule = node.symbol.constEnumOnlyModule && currentModuleIsConstEnumOnly;
```
Comment (JsonFreeman) [inline src/compiler/binder.ts]: Seems like in the following case, node.symbol.constEnumOnlyModule would be false, but should be true:
```ts
module M {
    export interface I { }
}
module M {
    export const enum E { x }
}
```

Comment (vladima) [inline src/compiler/binder.ts]: it will be true; 
- binding first module - it is not instantiated so node.symbol.constEnumOnlyModule remains undefined,
- binding second module - it is is const-enum-only - node.symbol.constEnumOnlyModule will be set to true

Comment (JsonFreeman) [inline src/compiler/binder.ts]: RIght

**Comment by JsonFreeman** [comment]
:+1:
