### PR TITLE
Force inner indexed access simplification during inference, if possible

### LINKED ISSUE #28394: JSX generic types that are themselves props are being incorrectly inferred in TS@next
**TypeScript Version:**  3.2.0-dev.20181107

**Search Terms:** I was told to make an issue 🤷‍♀️

**Code**

This is something I encountered while working on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30331; there are at least two instances of generics that are incorrectly inferred on TS@next.

It seems the compiler is overly eager to add things to the generic parameter that are not actually necessary, with incomplete types (they're just `{}`) and thus they end up causing errors instead. For example,

```tsx
                            <FieldArray
                                name="field9"
                                component={ MyArrayField }
                            />
```

is inferring `FieldArray` as `FieldArray<{ name: {}; component: {} }>` even though `name` and `component` are already present in `FieldArray<{}>`; this in turn causes `MyArrayField` to be expected to receive `{ name: {}; component: {} }` as props, while it only receives `{}`.

A similar issue happened with `<Button {...props}/>` in the reactstrap test, [see comment chain](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30331/files#r231380553). The spread of `props` caused `Button` to basically infer its own props as being `& Record<keyof props, {}>`, which more obviously broke the type of `children`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #28394

This is effectively an extension of #27953 - `getSimplifiedType` refrains from simplifying indexed accesses whose index is still generic, as it might later be instantiated and require outer distribution; however since we're in the middle of inference, we're just interested in breaking down our types as far as they'll go to find matching patterns; we're not concerned with the `target` side's ability to be further instantiated, since we're just looking for one of our goal type variables.

### CODE REVIEW

File: tests/baselines/reference/tsxReactPropsInferenceSuceedsOnIntersections.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
+//// [tsxReactPropsInferenceSuceedsOnIntersections.tsx]
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/tsxReactPropsInferenceSuceedsOnIntersections.js]: Succeeds

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -13833,10 +13833,22 @@ namespace ts {
...
+                            inferFromTypesOnce(source, simplified);
+                        }
+                        else if (target.flags & TypeFlags.IndexedAccess) {
+                            const indexType = getSimplifiedType((target as IndexedAccessType).indexType);
+                            // Generally simplifications of instantiable indexes are avoided to keep relationship checking correct, however if our target is an access, we can consider
+                            // that key of that access to be "instantiated", since we're looking to find the infernce goal in any way we can.
+                            if (indexType.flags & TypeFlags.Instantiable) {
+                                const objectType = getSimplifiedType((target as IndexedAccessType).objectType);
+                                // (T | U)[K] -> T[K] | U[K]
+                                if (objectType.flags & TypeFlags.Union) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: pls test

Comment (weswigham) [reply src/compiler/checker.ts]: I've rewritten it to use functionality we use elsewhere to make synchronize it and make it evident that the union case is for consistency (as now it's just a call to the underlying distribution method). It's not actually possible to (meaningfully) take the union branch, since a reverse mapped type with a union for a key type would be an intersection of keys, which we do not currently produce inferences for (unlike unions, which we now do).

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -9526,6 +9526,17 @@ namespace ts {
             return type.flags & TypeFlags.IndexedAccess ? getSimplifiedIndexedAccessType(<IndexedAccessType>type) : type;
         }
 
+        function distributeIndexOverObjectType(objectType: Type, indexType: Type) {
+            // (T | U)[K] -> T[K] | U[K]
+            if (objectType.flags & TypeFlags.Union) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You're a bad person for not testing this branch.

Comment (weswigham) [reply src/compiler/checker.ts]: Excuse me, I'm just reusing an operation already in use elsehwere ☑️
