### PR TITLE
Fix #20805

### LINKED ISSUE #20805: Error: Debug Failure. Either the symbol or the JSX namespace should be a UMD global if we got here in `getActionsForUMDImport` during `getCodeFixes`
tsserver version: 2.6.1
hitting sessions: 1374
stack:
```
Error: Debug Failure. Either the symbol or the JSX namespace should be a UMD global if we got here
    at getActionsForUMDImport (tsserver.js:76222:26)
    at Object.getImportCodeActions [as getCodeActions] (tsserver.js:76205:19)
    at tsserver.js:74988:33
    at Object.forEach (tsserver.js:1312:30)
    at Object.getFixes (tsserver.js:74987:16)
    at tsserver.js:80109:35
    at Object.flatMap (tsserver.js:1550:25)
    at Object.getCodeFixesAtPosition (tsserver.js:80107:23)
    at IOSession.Session.getCodeFixes (tsserver.js:86515:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85423:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### LINKED ISSUE #21607: Exception from convertToImportCodeFixContext
**TypeScript Version:**  2.7.0-insiders.20180117
**VSCode Version:** 1.20.0-insider

Exception in `convertToImportCodeFixContext` when the TS extension runs `getCodeFixes`.

**Repro Steps:**

1. Open a new TS file with the following content:
  ```ts
  const x = y;
  ```
1. Ensure the Output Pane is open with the TypeScript extension output selected.
1. Select the contents of the entire file (e.g. Ctrl+A on Windows)
1. Comment the selected range (e.g. Ctrl+/ on Windows)

**Expected Behavior:**
No output to extension log.

**Actual Behavior:**
The following is output to the extension log:

```
Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isIdentifier'.
    at Object.cast (c:\dev\TypeScript\built\local\tsserver.js:2445:15)
    at convertToImportCodeFixContext (c:\dev\TypeScript\built\local\tsserver.js:78598:34)
    at Object.getImportCodeActions [as getCodeActions] (c:\dev\TypeScript\built\local\tsserver.js:79002:36)
    at c:\dev\TypeScript\built\local\tsserver.js:77474:33
    at Object.forEach (c:\dev\TypeScript\built\local\tsserver.js:1430:30)
    at Object.getFixes (c:\dev\TypeScript\built\local\tsserver.js:77473:16)
    at c:\dev\TypeScript\built\local\tsserver.js:83621:35
    at Object.flatMap (c:\dev\TypeScript\built\local\tsserver.js:1700:25)
    at Object.getCodeFixesAtPosition (c:\dev\TypeScript\built\local\tsserver.js:83619:23)
    at IOSession.Session.getCodeFixes (c:\dev\TypeScript\built\local\tsserver.js:90643:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\dev\TypeScript\built\local\tsserver.js:89547:61)
    at c:\dev\TypeScript\built\local\tsserver.js:90808:88
    at IOSession.Session.executeWithRequestId (c:\dev\TypeScript\built\local\tsserver.js:90799:28)
    at IOSession.Session.executeCommand (c:\dev\TypeScript\built\local\tsserver.js:90808:33)
    at IOSession.Session.onMessage (c:\dev\TypeScript\built\local\tsserver.js:90828:35)
    at Interface.<anonymous> (c:\dev\TypeScript\built\local\tsserver.js:92029:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### LINKED ISSUE #21767: Debug Failure. Invalid cast. The supplied OpenBracketToken did not pass the test 'isIdentifier'.
```ts
type MappedOutputs<O> = {
    <T>[K in keyof O ] : T
}
```

hover over `K`

```log
[Error  - 10:24:18 AM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure. Invalid cast. The supplied OpenBracketToken did not pass the test 'isIdentifier'.
Error: Debug Failure. Invalid cast. The supplied OpenBracketToken did not pass the test 'isIdentifier'.
    at Object.cast (C:\ls\tsserver.js:2843:19)
    at convertToImportCodeFixContext (C:\ls\tsserver.js:94783:81)
    at Object.getImportCodeActions [as getCodeActions] (C:\ls\tsserver.js:95280:22)
    at C:\ls\tsserver.js:93647:33
    at Object.forEach (C:\ls\tsserver.js:1665:30)
    at Object.getFixes (C:\ls\tsserver.js:93646:16)
    at C:\ls\tsserver.js:100537:35
    at Object.flatMap (C:\ls\tsserver.js:1957:25)
    at Object.getCodeFixesAtPosition (C:\ls\tsserver.js:100535:23)
    at IOSession.Session.getCodeFixes (C:\ls\tsserver.js:108701:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\ls\tsserver.js:107571:61)
    at C:\ls\tsserver.js:108871:88
    at IOSession.Session.executeWithRequestId (C:\ls\tsserver.js:108862:28)
    at IOSession.Session.executeCommand (C:\ls\tsserver.js:108871:33)
    at IOSession.Session.onMessage (C:\ls\tsserver.js:108891:35)
    at Interface.<anonymous> (C:\ls\tsserver.js:110152:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

```

### PR DESCRIPTION
**Pull request by mhegazy**
React fragments are one of the cases that were not handled correctly. we assume all umd imports are identifiers, and fail otherwise. this change:
* adds support for react fragements
* changes the flow to resemble `checkJsxOpeningLikeElementOrOpeningFragment` logic that reports the error in the first place
* Adds a check for #21607 to avoid crashing if the token is not an identifier

Fixes #20805
Fixes #21767
Mitigates #21607

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -647,19 +642,43 @@ namespace ts.codefix {
...
+                umdSymbol = checker.resolveName(checker.getJsxNamespace(),
+                    isNodeOpeningLikeElement ? (<JsxOpeningLikeElement>parent).tagName : parent, SymbolFlags.Value, /*excludeGlobals*/ false);
+            }
+        }
+
+        if (isUMDExportSymbol(umdSymbol)) {
+            const symbol = checker.getAliasedSymbol(umdSymbol);
+            if (symbol) {
+                return getCodeActionsForImport([{ moduleSymbol: symbol, importKind: getUmdImportKind(context.program.getCompilerOptions()) }],
+                    convertToImportCodeFixContext(context, isIdentifier(token) ? token : undefined, umdSymbol.name));
```
Comment (andy-ms) [inline src/services/codefixes/importFixes.ts]: `context.symbolToken` is currently typed as `Node | undefined` and we check if it's an identifier when using it. So there is currently redundant checking. We could change its type to `Identifier | undefined` and remove the check at its use, or remove the check here.

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -684,8 +703,19 @@ namespace ts.codefix {
         }
     }
 
-    function getActionsForNonUMDImport(context: ImportCodeFixContext, allSourceFiles: ReadonlyArray<SourceFile>, cancellationToken: CancellationToken): CodeAction[] {
-        const { sourceFile, checker, symbolName, symbolToken } = context;
+    function getActionsForNonUMDImport(context: CodeFixContext): CodeAction[] {
+        // This will always be an Identifier, since the diagnostics we fix only fail on identifiers.
+        const { sourceFile, span, program, cancellationToken } = context;
+        const checker = program.getTypeChecker();
+        const symbolToken = getTokenAtPosition(sourceFile, span.start, /*includeJsDocComment*/ false);
```
Comment (andy-ms) [inline src/services/codefixes/importFixes.ts]: It looks like this is the same in both UMD and non-UMD cases.

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (mhegazy) [reply src/services/codefixes/importFixes.ts]: done.

File: src/services/codefixes/importFixes.ts (hunk 2 above)
Comment (mhegazy) [reply src/services/codefixes/importFixes.ts]: yes. but i wanted to defer the call to convertContext untill i had the name.
