### PR TITLE
Fix JsDocTags inheritage and setter/getter quickInfo

### LINKED ISSUE #45508: @returns documentation gets lost when inheriting getter
# Bug Report

### 🔎 Search Terms

@returns documentation gets lost when inheriting getter

### 🕗 Version & Regression Information

4.3.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1oHoBUGWo9AIgKYTABOAlgA4Au5A9gHYB0O0ereAAqYdQK6kGMAMrUKDAOYtUbNDgm9oADwAUASgBc0CGPKTEraD36DoAIjMBuHAF8kOTNhl4iJCjXrMO0b914ChaFFxKQ45VAAzdS0dEIMZI39TC2tUGx87JFBIGAAhaEIlakIGABMYeGRUBWplaO1dfSqZYwDzK1t7SPrYvQl4lqSGdtTodNQkOyA

### 💻 Code

```ts
class A {
  /**
   * Description.
   * 
   * @returns String.
   */
  get x(): string {
    return "";
  }

  /**
   * Description.
   * 
   * @returns String.
   */
  f(): string {
    return "";
  } 
}

class B extends A {
  get x(): string {
    return "";
  }

  f(): string {
    return "";
  }   
}
```

### 🙁 Actual behavior

Typescript shows @returns documentation for inheritted function but looses it for getter inside class B:
Screen1
Screen2

Inside class A it shows @returns both for getter and function.

### 🙂 Expected behavior

Since typescript shows @returns for getter in class A, it should also show it for inheritted getter.

### LINKED ISSUE #46572: JSDoc tags does not included in derived classes
# Bug Report

JSDoc tags in abstract class method descriptions do not visible in derived classes when those methods implemented as arrow functions. 
### 🔎 Search Terms

jsdoc, vscode, intellisense

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/IYIwzgLgTsDGEAJYBthjAgQmgpgg3gLABQCCA9AFSUlkKUIAqOEtZDAAgA7AwC2CAPZcIAfV4wAnggCCUKUIBmCVJJxQMACgiCEIHG3pk+ggCYBLReZymE5gHYIuqWDgCUAOkOcoLAK5QjnIKgsqq6mBepOzkbKCQMPAIAOYsADLAahrBmQBcCJrCYhKZbggAvAB8CMD2kgDaALoA3CQAviQkKGgYACLq5gBuNsGCAO52fM44fDj2EBjYYHhExGzk5AgA8o4AFoLDULnrm8ys0akQGVlgOdLlBUXi8qUV1at0dL4QAY5NrdEOsQgSQNggAKIADy4OHgNj0OF2wEG5kEAS6qHQCH6UCGNgAYn57PBUY5zFNkDM5gssLgCCdtnsDuoGWcGdxeMABE8StJACgEshe0lCKkyEQKOgRCBMFis8IcThc7iiZDBHG+vwQAruSlFNxVKXSYuyQsKImeUjKH0+CA1gQQ-zYQLaQA)

### 💻 Code

```ts
abstract class Base {
  /**
   * Tet
   * @param opt_array Array of layers (to be
   *  modified in place).
   * @return Array of layers.
   */
  abstract getLayersArray: (opt_array) => any[];
}

class DerivedArrow implements Base {

  // On hover:
  // Tet
  getLayersArray = (opt_array) => {
      return [];
  }
}

// Expected behaviour
class DerivedFunction implements Base {
  // On hover
  // Tet
  // @param opt_array — Array of layers (to be modified in place).
  // @return — Array of layers.
  getLayersArray(opt_array) {
      return [];
  }
}
```

### 🙁 Actual behavior

When derived class implements methods as arrow function when typescript miss all jsdoc tags and I can see only description:
tet

### 🙂 Expected behavior

Tags should be included in description:
Tet
@param opt_array — Array of layers (to be modified in place).
@return — Array of layers.

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #45508 
Fixes #46572

1. property and getter/setter could inherit jsDoc tags
2. the quick info of getter/setter in the class shows "(getter/setter)" rather than "property", but for property access of getter/setter, it still shows "property".
3. getter/setter inherits correspond getter/setter if none of getter/setter is overridden, or nothing if one of getter/setter is overridden. And for property access of getter/setter, it inherit its getter and setter JsDoc tags
4. add JsDocTags parameter to fourslash `quickInfoAt` and `quickInfoIs`. Note that if this parameter is not given, the check is skipped now. Maybe we should create one issue to always compare JsDocTags?

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
Up!

**Comment by ShuiRuTian** [comment]
up!

**Comment by ShuiRuTian** [comment]
up

File: src/services/symbolDisplay.ts [hunk 1]
```diff
@@ -164,9 +166,24 @@ namespace ts.SymbolDisplay {
 
         // Class at constructor site need to be shown as constructor apart from property,method, vars
         if (symbolKind !== ScriptElementKind.unknown || symbolFlags & SymbolFlags.Class || symbolFlags & SymbolFlags.Alias) {
-            // If it is accessor they are allowed only if location is at name of the accessor
+            // If symbol is accessor, they are allowed only if location is at declaration identifier of the accessor
             if (symbolKind === ScriptElementKind.memberGetAccessorElement || symbolKind === ScriptElementKind.memberSetAccessorElement) {
-                symbolKind = ScriptElementKind.memberVariableElement;
+                const declaration = find(symbol.declarations as ((GetAccessorDeclaration | SetAccessorDeclaration)[]), declaration => declaration.name === location);
+                if (!!declaration) {
```
Comment (gabritto) [inline src/services/symbolDisplay.ts:172]: minor: that could just be `if (declaration) {`

File: src/services/symbolDisplay.ts [hunk 2]
```diff
@@ -164,9 +166,24 @@ namespace ts.SymbolDisplay {
...
+                            break;
+                        case SyntaxKind.SetAccessor:
+                            symbolKind = ScriptElementKind.memberSetAccessorElement;
+                            break;
+                        default:
+                            Debug.assertNever(declaration);
+                        }
+                }
+                else {
+                    symbolKind = ScriptElementKind.memberVariableElement;
```
Comment (gabritto) [inline src/services/symbolDisplay.ts:185]: for my understanding: do we need to "fix" `symbolKind` again because we might have `ScriptElementKind.memberGetAccessorElement` at a setter location, because of the way `getSymbolKindOfConstructorPropertyMethodAccessorFunctionOrVar` is implemented above?

**Review by gabritto — CHANGES_REQUESTED** [review]
left some minor comments and some questions, but I think otherwise this PR looks great.

File: src/services/symbolDisplay.ts (hunk 2 above)
Comment (ShuiRuTian) [reply src/services/symbolDisplay.ts]: Yes, I guess so. Do you mean I should move the logic to `getSymbolKindOfConstructorPropertyMethodAccessorFunctionOrVar`? I remember that I try to do this, but I forgot the reason why I did not do this finally.

Comment (ShuiRuTian) [reply src/services/symbolDisplay.ts]: Aha, I remember the reason now. I thought `getSymbolKindOfConstructorPropertyMethodAccessorFunctionOrVar` tells us the kind of the symbol, and it is indeed getter/setter, then `getSymbolDisplayPartsDocumentationAndSymbolKind` decides how we display it by the location.

Comment (ShuiRuTian) [reply src/services/symbolDisplay.ts]: But it seems there are already some logics in the function. So it is a better choice to move logic here?

Comment (gabritto) [reply src/services/symbolDisplay.ts]: I think it's fine as it is, just wanted to make sure I understood it right. :)

File: tests/cases/fourslash/quickInfoJsDocGetterSetter.ts [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+////      * @param value foo D
+////      */
+////     set /*5*/x(val: string) { }
+//// }
+//// new A()./*6*/x = "1";
+//// new B()./*7*/x = "1";
+//// new C()./*8*/x = "1";
+//// new D()./*9*/x = "1";
+
+verify.quickInfoAt("1", "(getter) A.x: string", 'getter A', [{ name: "returns", text: "return A" }]);
```
[the remark this answers is not in the document]
Comment (sandersn) [reply tests/cases/fourslash/quickInfoJsDocGetterSetter.ts:48]: Also, I'd like to see a test of inherited jsdoc for other symbols like properties and methods.
It would be especially good to test inheritance from multiple bases, and inheritance from symbols that have multiple declarations. (I'm not sure what the latter would be -- maybe a type and namespace and property that all share the same name?)

**Review by sandersn — CHANGES_REQUESTED** [review]
I agree, looks good. Just needs some non-accessor tests.

File: tests/cases/fourslash/quickInfoJsDocGetterSetter.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (ShuiRuTian) [reply tests/cases/fourslash/quickInfoJsDocGetterSetter.ts:48]: property is test here `quickInfoOnParameterProperties.ts` (its baseline file is updated in this PR)
method is test here `quickInfoJsDocTags5.ts`

So I guess there is no need to test the simple case?

As for the complex case, is it OK to add (There are same name methods and property in all interface and class, the property might be function or not)
- a class extends from base class and implement an interface
- a class implement two interfaces, then declare one namespace with all things with same name
Is this enough?

[the remark this answers is not in the document]
Comment (ShuiRuTian) [reply tests/cases/fourslash/quickInfoJsDocGetterSetter.ts:48]: Ooops, it is an error to have static method and namespace exported method with same name at the same time.
Then I guess namespace could not be used as a source of multiple declarations? I do not know much about namespace, or is there some method?

[the remark this answers is not in the document]
Comment (sandersn) [reply tests/cases/fourslash/quickInfoJsDocGetterSetter.ts:48]: I couldn't think of a way to merge a namespace and a class either. So it's probably fine to skip that case.

**Review by sandersn — APPROVED** [review]
