### PR TITLE
fix(49392): classMemberSnippets not working with optional method and strictNullChecks

### LINKED ISSUE #49392: classMemberSnippets not working with optional method and strictNullChecks
# Bug Report

### 🔎 Search Terms

* method autocomplete
* classMemberSnippets
* method snippets
* optional method

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### 💻 Code

With `strictNullChecks` and `typescript.suggest.classMemberSnippets.enabled: true`

```ts
interface IFoo {
    foo?(arg: string): number;
}

class Foo implements IFoo {
    | // attempt to autocomplete foo
}
```

### 🙁 Actual behavior

Attempting to autocomplete `foo` results in:

```ts
class Foo implements IFoo {
    foo|
}
```

### 🙂 Expected behavior

Attempting to autocomplete `foo` results in:

```ts
class Foo implements IFoo {
    foo(arg: string): number {
        |
    }
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49392

### CODE REVIEW

File: tests/cases/fourslash/completionsOverridingMethod14.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
+/// <reference path="fourslash.ts" />
+
+// @Filename: a.ts
+// @strictNullChecks: true
+// @newline: LF
```
Comment (sandersn) [inline tests/cases/fourslash/completionsOverridingMethod14.ts:5]: TIL

**Review by sandersn — APPROVED** [review]
