### PR TITLE
Fix inferences between alias type arguments and defaulted alias type arguments

### LINKED ISSUE #51698: On DT, lambda-tester is broken by better alias preservation
lambda-tester is broken by #51152.

Conditional type instantiation seems to proceed differently for an alias when it was constructed without type parameters that are later defaulted:

```ts
type Actual = lambdaTester.Verifier<lambdaTester.HandlerResult<Handler>>
type Expected = lambdaTester.Verifier<lambdaTester.HandlerResult<Handler<any, any>>>

// from lambda-tester's index.d.ts:
type HandlerResult<T extends Handler> = T extends Handler<any, infer TResult> ? TResult : never;
type Verifier<S> = S extends HandlerError<Handler>
    ? (S extends string ? VerifierFn<string>
       : S extends Error ? VerifierFn<Error>
       : never)
    : VerifierFn<S>;
class LambdaTester<T extends Handler> {
    // ....
    expectSucceed(verifier: Verifier<HandlerResult<T>>): Promise<any>;
    // ....
}
// from aws-lambda's index.d.ts:
export type Handler<TEvent = any, TResult = any> = (
    event: TEvent,
    context: Context,
    callback: Callback<TResult>,
) => void | Promise<TResult>;
```

`Actual` and `Expected` are both `VerifierFn<string> | VerifierFn<Error> | VerifierFn<any>` before #51152. Afterwards, `Actual` is `VerifierFn<unknown>`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #51698

As I mentioned in the related issue, contrary to speculation during post-standup, the issue _wasn't_ that we were missing the alias identity (actually, to ensure that isn't an issue, we use the target symbol on construction of the alias already), but rather was that we ignored alias type argument defaults during inference. With this, we actually apply the defaults to the alias type argument lists we compare during inference, fixing the issue~

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot user test this inline
@typescript-bot test this
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot test top100

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -23698,8 +23698,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
                 if (source.aliasTypeArguments) {
                     // Source and target are types originating in the same generic type alias declaration.
-                    // Simply infer from source type arguments to target type arguments.
-                    inferFromTypeArguments(source.aliasTypeArguments, target.aliasTypeArguments!, getAliasVariances(source.aliasSymbol));
+                    // Simply infer from source type arguments to target type arguments, with defaults applied.
+                    const params = getSymbolLinks(source.aliasSymbol).typeParameters!;
+                    const minParams = getMinTypeArgumentCount(params);
+                    const sourceTypes = fillMissingTypeArguments(source.aliasTypeArguments, params, minParams, /*isJs*/ false);
+                    const targetTypes = fillMissingTypeArguments(target.aliasTypeArguments, params, minParams, /*isJs*/ false);
+                    inferFromTypeArguments(sourceTypes, targetTypes!, getAliasVariances(source.aliasSymbol));
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:23706]: Hmm, I wasn't even aware that the type argument list could be incomplete at this point, and I'm not sure that was ever intended. It's fine for type arguments to be missing at the lexical level, but once we're dealing with types we pretty much assume that the length of a type argument list matches the length of the corresponding type parameter list. That assumption is pretty pervasive throughout the compiler (modulo the `this` type argument that sometimes isn't present). I think it would make more sense to find the origin of the incomplete list and put the call to `fillMissingTypeArguments` there.

Comment (weswigham) [reply src/compiler/checker.ts:23706]: Right, so, our old logic for giving an alias symbol instantiation an alias symbol didn't fill missing type arguments, which is why the new condition I added also didn't - it didn't seem required, since our existing usage didn't fill them. Obviously, broader usage of these unfilled lists reveals the flaw, namely inference (and probably comparison checking) not going well, since, as you said, they currently expect filled lists. Thing is, I think trafficking the unfilled lists has an advantage - it may be worth handling incomplete lists in inference/comparison checking. If we start filling them eagerly, rather than getting the user-supplied list, when we printback, we don't printback the user supplied list anymore. Meaning, even though you wrote `Component`, we print back and serialize `Component<{}, any, any>`. For complex defaults, this means we can muddy the printback unnecessarily quite a bit. So I _could_ fix this by passing in filled lists at the now 2 locations we supply an alias for an alias symbol instantiation, the UX is _much_ nicer if instead we update inference and comparison checking to handle incomplete type alias argument lists, imo.

**Comment by weswigham** [comment]
@ahejlsberg Rather than ensuring we pass filled lists at every callsite, after an audit, I've ensured we handled unfilled lists everywhere we did comparisons of type alias type argument lists. This is better UX, since then when we printback the aliases, we print them back in the same way the user wrote them (ie, relying on defaults). In either case, there were only 2 places that needing updating. There were 2 places we made lists that needed filling (at a minimum; we make some impromptu aliases out of type references that probably also need filling, but I didn't investigate those too much), but there's also only 2 places we compare alias type argument lists where the list needs to be filled (at most) - inference and variance comparison checking.

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -23698,8 +23702,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             if (source.aliasSymbol && source.aliasSymbol === target.aliasSymbol) {
                 if (source.aliasTypeArguments) {
                     // Source and target are types originating in the same generic type alias declaration.
-                    // Simply infer from source type arguments to target type arguments.
-                    inferFromTypeArguments(source.aliasTypeArguments, target.aliasTypeArguments!, getAliasVariances(source.aliasSymbol));
+                    // Simply infer from source type arguments to target type arguments, with defaults applied.
+                    const params = getSymbolLinks(source.aliasSymbol).typeParameters!;
+                    const minParams = getMinTypeArgumentCount(params);
+                    const sourceTypes = fillMissingTypeArguments(source.aliasTypeArguments, params, minParams, isInJSFile(source.aliasSymbol.valueDeclaration));
+                    const targetTypes = fillMissingTypeArguments(target.aliasTypeArguments, params, minParams, isInJSFile(source.aliasSymbol.valueDeclaration));
```
Comment (JoostK) [inline src/compiler/checker.ts:23709]: Similarly here.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -20763,7 +20763,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 if (variances === emptyArray) {
                     return Ternary.Unknown;
                 }
-                const varianceResult = relateVariances(source.aliasTypeArguments, target.aliasTypeArguments, variances, intersectionState);
+                const params = getSymbolLinks(source.aliasSymbol).typeParameters!;
+                const minParams = getMinTypeArgumentCount(params);
+                const sourceTypes = fillMissingTypeArguments(source.aliasTypeArguments, params, minParams, isInJSFile(source.aliasSymbol.valueDeclaration));
+                const targetTypes = fillMissingTypeArguments(target.aliasTypeArguments, params, minParams, isInJSFile(source.aliasSymbol.valueDeclaration));
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:20769]: Nope, intentional - we know the two are `===` identical, so reusing `source` for both is fewer cache hits with less work on the JIT.

**Review by DanielRosenwasser — APPROVED** [review]
> I think trafficking the unfilled lists has an advantage

I tend to agree with this, though could be persuaded if we forget to do this in so many places that it's a problem. If we want, we can do a follow-up PR that pre-emptively fills type argument defaults, but this seems like a very straightforward fix for now.

**Review by ahejlsberg — APPROVED** [review]

**Comment by ahejlsberg** [comment]
Turns out that in _most_ cases we do fill the type parameter defaults early and print them back even if they weren't written explicitly. So, we're basically in an inconsistent state. I think it would make sense to create a separate PR to see what the effect would be of _always_ preserving type references as written.
