### PR TITLE
Unify substitution type `any` handling into costruction and instantiation

### LINKED ISSUE #30489: 3.4.0-rc - behaviour changed from 3.3 (regression?)
I found a case where types yielded differ between 3.3 and 3.4, but I'm not sure if it is a regression or it is intended

```ts
interface I<T> {
    a: T
}

// this is different between 3.3 and 3.4
type O<T> = T extends I<any> ? T : never
type B = O<I<number>> // I<number> in TS3.3, I<any> & I<number> in TS3.4 (which boils down to I<any>

// this however is the same
type O2<T> = T extends I<infer _> ? T : never
type B2 = O2<I<number>> // I<number> in both
```

### LINKED ISSUE #30569: Possible regression in 3.4 with distributive conditional types
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
type UnionKeys<T> = T extends any ? keyof T : never;
type BugHelper<T, TAll> = T extends any ? Exclude<UnionKeys<TAll>, keyof T> : never
type Bug<TAll> =  BugHelper<TAll, TAll>
type R = Bug<{ a : any } | { b: any }> // "a" | "b" in 3.3, never in 3.4
```

**Expected behavior:**
`R` should be `"a" | "b"` (as it previously was in 3.3) 

**Actual behavior:**
`R` is `never` in 3.4

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=type%20UnionKeys%3CT%3E%20%3D%20T%20extends%20any%20%3F%20keyof%20T%20%3A%20never%3B%0D%0Atype%20BugHelper%3CT%2C%20TAll%3E%20%3D%20T%20extends%20any%20%3F%20Exclude%3CUnionKeys%3CTAll%3E%2C%20keyof%20T%3E%20%3A%20never%0D%0Atype%20Bug%3CTAll%3E%20%3D%20%20BugHelper%3CTAll%2C%20TAll%3E%0D%0Atype%20R%20%3D%20Bug%3C%7B%20a%20%3A%20any%20%7D%20%7C%20%7B%20b%3A%20any%20%7D%3E%20%2F%2F%20%22a%22%20%7C%20%22b%22%20in%203.3%2C%20never%20in%203.4)

**Related Issues:** Probably cause by #29437, #30489

The code above is a simplification of the `StrictUnion` type I posted on SO, and this issue was reported there as a [comment](https://stackoverflow.com/questions/52677576/typescript-discriminated-union-allows-invalid-state/52678379?noredirect=1#comment97380819_52678379). The type was also included by another SO user in [SimplyTyped](https://github.com/andnp/SimplyTyped/issues/76#issue-396291343)

**Workaround**
For the `StrictUnion` type a simple workaround is to pass in union keys to `StrictUnionHelper`. This will achieve the same result as in 3.4:

```ts
type StrictUnionHelper<T, TAllKeys extends PropertyKey> = T extends any ? T & Partial<Record<Exclude<TAllKeys, keyof T>, never>> : never;
type StrictUnion<T> = StrictUnionHelper<T, UnionKeys<T>>
```

If breaking change is intended, I would like some guidance on whether the workaround version is likely to remain stable in the next releases or if there is a fundamental issue with the idea behind the type.

### PR DESCRIPTION
**Pull request by weswigham**
And clean up conditional types a little to match. The changes to conditional `resolvedTrueType`/`resolvedFalseType` aren't strictly required, per sey, but they clean up a lot and reduce complexity. We were choosing not to cache types we'd already computed (for no real reason other than a misunderstanding on my part as to when the `combinedMapper` was used).

Fixing the creation of substitutes to `any` exposed an issue where we'd generate infinitely expanding types in our `infiniteConstraints.ts` test (which previously were never expanded because their assignment to a substituted `any` simply succeeded) - I had to both introduce type-parameter like circularity guards into `getConstraintOfType` for conditionals and indexed accesses (it was missing them), _and_ further penalize deep instantiations of conditionals within `computeBaseConstraint` (to capture the exponential explosion of types instantiated by circularly referential conditionals).

Fixes #30569
Fixes #30489

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt go go go

File: src/compiler/types.ts [hunk 1]
```diff
@@ -4310,8 +4310,10 @@ namespace ts {
         root: ConditionalRoot;
         checkType: Type;
         extendsType: Type;
-        resolvedTrueType?: Type;
-        resolvedFalseType?: Type;
+        resolvedTrueType: Type;
+        resolvedFalseType: Type;
+        /* @internal */
+        inferredTrueType?: Type; // The `trueType` instantiated with the `combinedMapper`, if present
```
Comment (ahejlsberg) [inline src/compiler/types.ts]: I suggest renaming to `trueType`, `falseType`, and `resolvedInferredTrueType`. Elsewhere we use the "resolvedXXX" pattern to indicate a lazily computed entity.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -7488,24 +7492,14 @@ namespace ts {
...
-        function getDefaultConstraintOfTrueBranchOfConditionalType(root: ConditionalRoot, combinedMapper: TypeMapper | undefined, mapper: TypeMapper | undefined) {
-            const rootTrueType = root.trueType;
-            const rootTrueConstraint = !(rootTrueType.flags & TypeFlags.Substitution)
-                ? rootTrueType
-                : instantiateType(((<SubstitutionType>rootTrueType).substitute), combinedMapper || mapper).flags & TypeFlags.AnyOrUnknown
-                    ? (<SubstitutionType>rootTrueType).typeVariable
-                    : getIntersectionType([(<SubstitutionType>rootTrueType).substitute, (<SubstitutionType>rootTrueType).typeVariable]);
-            return instantiateType(rootTrueConstraint, combinedMapper || mapper);
-        }
-
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Never did understand what this was for. Happy to see it gone!

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -7684,8 +7682,11 @@ namespace ts {
                     return baseIndexedAccess && baseIndexedAccess !== errorType ? getBaseConstraint(baseIndexedAccess) : undefined;
                 }
                 if (t.flags & TypeFlags.Conditional) {
-                    const constraint = getConstraintOfConditionalType(<ConditionalType>t);
-                    return constraint && getBaseConstraint(constraint);
+                    const constraint = getConstraintFromConditionalType(<ConditionalType>t);
+                    constraintDepth++; // Penalize repeating conditional types (this captures the recursion within getConstraintFromConditionalType and carries it forward)
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Why the extra bump? Not that I mind, just curious.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -11182,7 +11180,11 @@ namespace ts {
                     return getSubstitutionType(maybeVariable as TypeVariable, instantiateType((<SubstitutionType>type).substitute, mapper));
                 }
                 else {
-                    return maybeVariable;
+                    const sub = instantiateType((<SubstitutionType>type).substitute, mapper);
+                    if (sub.flags & TypeFlags.AnyOrUnknown || isTypeSubtypeOf(getRestrictiveInstantiation(maybeVariable), getRestrictiveInstantiation(sub))) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: When would the `isTypeSubtypeof` check be true?

Comment (weswigham) [reply src/compiler/checker.ts]: When `typeVariable = string[]` and `substitute = any[] & string[]`, for example. Likewise when `typeVariable = { a, b }` and `substitute = { a }`.

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts]: As I mentioned in the OP, the new circularity checking isn't quite enough to stop the crashes in `infiniteConstraints` - bottoming out the base constraint at depth 50 just takes too long, since `getConstraintFromConditionalType` is recursive into `getConstraintOfType` (in the distributive case), except it doesn't return the constraint it finds - it returns a conditional distributing over that constraint. In effect, we get an instance there, dive to depth 50, unwind, inject it into a new instance, then dive down to 50 again. The added depth just penalizes this pattern so it runs out of gas faster. Once the distributive constraint is gone (since it just simulates generic negations), we might not need it.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: We just do the work on substitution construction/instantiation now. It is much cleaner this way, yeah.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Pretty much cases where supertype reduction in the substitute would be nice. :)

It's worth noting that doing this actually brings us back to pre-3.4 behavior for our output olwhen conditionals simplify. While the intersections with extra supertypes are generally equivalent, they delete information when they contain `any` which can poison further comparisons, so including them in the conditional results was altering some outputs. There was another issue where someone was mentioning it, but I think we marked it as intentional? I can't find the exact issue, but a user had a condition like `T extends I<any> ? T : never` - with `T` as `I<number`, we produced `I<number> & I<any>` - we'd actually broadened the type with the intersection rather than narrowed it. This supertype reduction check fixes that issue (and some of our test cases which changed to reflect the intersections when we added the simplifications).

**Comment by weswigham** [comment]
The egg-mock and protractor DT failures are also from `master`, however the `react-redux` failure I'll need to look into. It _looks_ like we're assigning something a default inference in a place we don't want to be (or at least weren't before) - will need to check it.

**Comment by weswigham** [comment]
RWC diff is actually nil - test only failed because there's an unaccepted RWC diff on `master` right now. (Looks like we accepted making the JSON global into a var instead of a const)

File: src/compiler/checker.ts (hunk 4 above)
Comment (jack-williams) [reply src/compiler/checker.ts]: @weswigham This one I think #30489

**Comment by weswigham** [comment]
Wow, so the `react-redux` break is indicative of a IIRC known issue in our subtyping rules. `(payload: boolean) => { type: string; payload: boolean; }` is _not_ seen as a subtype of `(...args: any[]) => any)`, because the parameter `any` is _not_ a subtype of `boolean` (just assignable - the position is contravariant, so `never` is the needed bound there, not `unknown`). (Thus we produce an intersection and materialize an `any` in the return position, creating a type with `any`'s in it which passes a following check which it should not) `any` not behaving as the correct bound for the context it's in for the subtype relation here is painful.

I can definitely special-case the all-any signature inside `signaturesRelatedTo` such that an any-ish signature has all other signatures as subtypes, but that's only a partial fix (since `any` in other contravariant positions will still behave undesirably under the subtype relationship).

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt - I've confirmed `react-redux` is now clean locally, but let's check the state of the world with the small change to subtyping.

**Comment by weswigham** [comment]
Remaining two DT failures are the two from `master` - this change is now clean :+1:

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -11727,6 +11729,15 @@ namespace ts {
 
         type ErrorReporter = (message: DiagnosticMessage, arg0?: string, arg1?: string) => void;
 
+        /**
+         * Returns true if `s` is `(...args: any[]) => any` or `(this: any, ...args: any[]) => any`
+         */
+        function isAnySignature(s: Signature) {
+            return !s.typeParameters && (!s.thisParameter || isTypeAny(getTypeOfParameter(s.thisParameter))) && s.parameters.length === 1 &&
+                s.hasRestParameter && getTypeOfParameter(s.parameters[0]) === anyArrayType &&
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Also allow for `(...args: any) => any`.

**Comment by weswigham** [comment]
@ahejlsberg done.

@typescript-bot test this & @typescript-bot run dt because this is an immediately-before-release fix and we like making sure we're not breaking people~

**Comment by weswigham** [comment]
DT's just as clean as before, this is good. ❤️ 

@ahejlsberg can you update your review status?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -3492,8 +3492,8 @@ namespace ts {
                     context.inferTypeParameters = (<ConditionalType>type).root.inferTypeParameters;
                     const extendsTypeNode = typeToTypeNodeHelper((<ConditionalType>type).extendsType, context);
                     context.inferTypeParameters = saveInferTypeParameters;
-                    const trueTypeNode = typeToTypeNodeHelper(getTrueTypeFromConditionalType(<ConditionalType>type), context);
-                    const falseTypeNode = typeToTypeNodeHelper(getFalseTypeFromConditionalType(<ConditionalType>type), context);
+                    const trueTypeNode = typeToTypeNodeHelper((<ConditionalType>type).trueType, context);
+                    const falseTypeNode = typeToTypeNodeHelper((<ConditionalType>type).falseType, context);
```
Comment (mihailik) [inline src/compiler/checker.ts]: I thought `<`angle brackets`>` casting is meant to be phased out in favour of `as` casting?

Comment (weswigham) [reply src/compiler/checker.ts]: The angle brackets were already here~
