### PR TITLE
Fix invalid JSXExpressions having identifier-ish things in their trivia, improve error messages for comma expressions in JSX

### LINKED ISSUE #25487: Debug Failure. Did not expect JsxExpression to have an Identifier in its trivia
**TypeScript Version:**  2.9.2
Can't use ts@next because of #25484 that happens every 5min

**Search Terms:** 

**Code**

```ts
Error: Debug Failure. Did not expect JsxExpression to have an Identifier in its trivia
    at addSyntheticNodes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89462:30)
    at createChildren (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89451:9)
    at NodeObject.getChildren (/usr/local/lib/node_modules/typescript/lib/tsserver.js:89400:56)
    at getTokenAtPositionWorker (/usr/local/lib/node_modules/typescript/lib/tsserver.js:71215:43)
    at Object.getTokenAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:71206:16)
    at getInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:85133:28)
    at Object.getCodeActions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:85095:28)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:83738:121
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:1802:25)
    at Object.getFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:83738:23)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:90750:35
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:1802:25)
    at Object.getCodeFixesAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:90748:23)
    at IOSession.Session.getCodeFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:97423:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:96250:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:97580:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:97571:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:97580:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:97600:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:98831:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:** 

tsserver logs id: 1660483066

### PR DESCRIPTION
**Pull request by andrewbranch**
I'm not totally sure why that debug assertion was there and specific to identifiers, but removing it only seems to require that the synthetically added identifier get its `escapedText` set.

Fixes #25487

### CODE REVIEW

**Comment by weswigham** [comment]
While that may be what's wrong with the node, based on the PR the assertion was added in ( https://github.com/microsoft/TypeScript/pull/21581 ) there absolutely should not be an identifier within a trivia span as far as we know - meaning the node `end` position is incorrect for the preceding node (since it includes this `identifier`-parseable span). AFAIK we should only have a stream of tokens (eg, parens or keywords) when scanning over this range.

Which makes sense - since this only occurs in incremental parsing scenarios (ie, in the editor), together it implies that something may be wrong with how we incrementally parse and update these nodes.

**Comment by andrewbranch** [comment]
I mean, how else would you parse this?

```jsx
<div>{<div />x}</div>
```

The parser hits the `x` when doing a `parseExpected(SyntaxKind.CloseBraceToken)` and then moves on. The end of the node is set to after `x`, so when the language service adds synthetic nodes, it scans `x` as an identifier. I can't see any reason to treat this differently than, say

```jsx
<div>{<div />""}</div>
```

which parses the same, but since it's a token, doesn't hit the debug assertion.

> This can cause a problem if we scan an `Identifier` because we don't give it any text here

So I gave it text here ¯\_(ツ)_/¯

File: tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/// <reference path="fourslash.ts" />
+
+//@Filename: jsxExpressionFollowedByIdentifier.tsx
+////declare var React: any;
+////declare var x: string;
+////const a = <div>{<div />/*1*/x/*2*/}</div>
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: Instead of two markers, you can use a range with `[|` and `|]`

**Comment by weswigham** [comment]
`parseExpected` only advances if a match was found - the issue is the `scanJsxText` inside `parseJsxExpression` that's forcing the cursor forward without assigning the intervening text to a real node (because we do _actually_ parse JSX text out). There's no discussion of it in https://github.com/microsoft/TypeScript/pull/4228 (which introduced it) so it's a bit of an exercise in software archaeology.

**Comment by andrewbranch** [comment]
> synthesizing a binary expression with a comma operator

A-ha, this is exactly what I was missing. I can do that.

So as a general rule, what kinds of syntax is the parser allowed to skip over? To me, it feels just as odd for a string literal token to end up in another syntax's trivia as it does for an identifier. But the debug assertion _only_ cares about identifiers. I'm trying to figure out how I could have known, without feedback, that this solution is better than “fixing” synthetic identifiers, which also does seem to solve the problem. Is it that the parser should try as hard as possible to create a node for everything it sees, even when invalid?

**Comment by weswigham** [comment]
> So as a general rule, what kinds of syntax is the parser allowed to skip over?

Keywords/punctuation, whitespace and comments. (There is still some punctuation we capture for transformer reasons.) Things we don't make real AST nodes for when parsing well-formed code.

> But the debug assertion only cares about identifier

I think the assertion is just an early error to warn about the crash on access - finding a string literal or almost anything that would usually have a real AST node in the trivia is an error. The category of "trivia" is primarily just comments and whitespace and is expanded to include unparsed keywords and punctuation in this context.

> Is it that the parser should try as hard as possible to create a node for everything it sees, even when invalid?

Yeah, usually I think we just stuff invalid junk we want to consume into a "missing node" which is marked appropriately for incremental reparsing.

> I'm trying to figure out how I could have known, without feedback, that this solution is better than “fixing” synthetic identifiers, which also does seem to solve the problem. 

Deep software archaeology. When editing code I didn't write, I'm in the habit of looking up the blames of relevant code (in this case, both the PR adding the assertion and the PR adding the scanning in jsx expression parsing) I want to change to find the justification for it being as it is and seeing if the current state is well-reasoned or apparently ad-hoc. In the case of the later, finding and fixing the root cause of the prior ad-hoc change is often able to create higher quality code than stacking more ad-hoc fixes (which is what I'm suggesting here).

**Comment by andrewbranch** [comment]
🕵 related: #31510

File: tests/baselines/reference/jsxParsingError1.js [hunk 2]
```diff
@@ -16,5 +16,4 @@ const elem = <div className={class1, class2}/>;
 // This should be a parse error
 var class1 = "foo";
 var class2 = "bar";
-var elem = <div className={class1} class2/>;
-/>;;
+var elem = <div className={class1, class2}/>;
```
Comment (andrewbranch) [inline tests/baselines/reference/jsxParsingError1.js]: This emit is invalid although slightly less so than the previous? We could potentially put these inside a ParenthesizedExpression, but we're already emitting a grammar error, and it seems like there's no requirement for the emit to be totally valid if the input wasn't totally valid.

File: tests/baselines/reference/tsxErrorRecovery1.errors.txt [hunk 3]
```diff
@@ -1,26 +1,14 @@
...
     declare namespace JSX { interface Element { } }
     
     function foo() {
     	var x = <div>  { </div>
-    	         ~~~
-!!! error TS17008: JSX element 'div' has no corresponding closing tag.
     	                 ~~
 !!! error TS1109: Expression expected.
     }
     // Shouldn't see any errors down here
```
Comment (andrewbranch) [inline tests/baselines/reference/tsxErrorRecovery1.errors.txt]: _Now_ we don't. I think this gets significantly better.

File: tests/baselines/reference/jsxInvalidEsprimaTestSuite.js [hunk 4]
```diff
@@ -123,7 +123,7 @@ var x = <div>one</div>, <div>two</div>;
 var x = <div>one</div> /* intervening comment */, /* intervening comment */ <div>two</div>;
 ;
 //// [20.jsx]
-<a>{"str"}}</a>;
+<a>{"str"};}</a>;
```
Comment (andrewbranch) [inline tests/baselines/reference/jsxInvalidEsprimaTestSuite.js]: This is weird, but barely weirder than the previous

File: tests/baselines/reference/jsxAndTypeAssertion.js [hunk 5]
```diff
@@ -28,18 +28,21 @@ var foo = /** @class */ (function () {
     return foo;
 }());
 var x;
-x = <any> {test} <any></any> };
+x = <any> {test}: <any></any> };
```
Comment (andrewbranch) [inline tests/baselines/reference/jsxAndTypeAssertion.js]: The TypeScript generating this was `x = <any> { test: <any></any> };`. Garbage in, garbage out?

File: tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts [hunk 6]
```diff
@@ -0,0 +1,12 @@
+/// <reference path="fourslash.ts" />
+
+//@Filename: jsxExpressionFollowedByIdentifier.tsx
+////declare var React: any;
+////const a = <div>{<div />[|x|]}</div>
+////const b = <div x={<div />[|x|]} />
+
+test.ranges().forEach(range => {
+  verify.errorExistsAtRange(range, 1005, "'}' expected.");
```
Comment (weswigham) [inline tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: Maybe `ts.Diagnostics.<message>.code` (or equivalent reexposed to the test environment) would be better, so we avoid hardcoding an error code into the test.

File: tests/baselines/reference/jsxParsingError1.errors.txt [hunk 7]
```diff
@@ -15,10 +14,8 @@ tests/cases/conformance/jsx/file.tsx(11,46): error TS1161: Unterminated regular
...
-                                       ~
-!!! error TS1005: '}' expected.
-                                               ~
-!!! error TS1003: Identifier expected.
-                                                 
-!!! error TS1161: Unterminated regular expression literal.
+                                 ~~~~~~
+!!! error TS2695: Left side of comma operator is unused and has no side effects.
+                                 ~~~~~~~~~~~~~~
+!!! error TS18007: JSX expressions may not use the comma operator. Did you mean to write an array?
```
Comment (andrewbranch) [inline tests/baselines/reference/jsxParsingError1.errors.txt]: These two errors make a lot more sense to me than the previous three, although I could do without the first. I considered making the error range start on the comma operator instead of at the beginning of the expression. Thoughts?

File: src/compiler/parser.ts [hunk 8]
```diff
@@ -4430,14 +4430,18 @@ namespace ts {
 
             if (token() !== SyntaxKind.CloseBraceToken) {
                 node.dotDotDotToken = parseOptionalToken(SyntaxKind.DotDotDotToken);
-                node.expression = parseAssignmentExpressionOrHigher();
+                // Only an AssignmentExpression is valid here per the JSX spec,
+                // but we can unambiguously parse a comma sequence and provide
+                // a better error message in grammar checking.
+                node.expression = parseExpression();
```
Comment (andrewbranch) [inline src/compiler/parser.ts]: When we successfully parse something we know is illegal, is that always a grammar error, or is there ever a reason why that should be a parse error? I know a parse error will prevent the node from being reused incrementally—in this case the tree should be well-formed, so I think reusing it isn’t a problem.

**Comment by andrewbranch** [comment]
> Also it looks like we usually more gracefully handle similar parse errors by synthesizing a binary expression with a comma operator - see `parseJsxElementOrSelfClosingElementOrFragment`

Thinking this was going to be the way forward, I improved error messages for comma expressions as JSX expressions.

However, I don't think it's quite feasible to parse extra stuff in a `JSXExpression` as the right-hand side of a binary expression, because we have no idea how much extra stuff there might be, what kind of stuff it is, or if the closing `}` will indeed ever be found. The trick we do for `<div /><div />` only works because it’s a special case where a JSX element follows a JSX element—that kind of logic wouldn't work very well if we needed to couple a JSX element and _N_ other subsequent syntaxes.

By conditionally scanning for more JSX text based on whether the expected `}` was found, we still end up with a pretty gross parse tree, but in `<div>{<div />x}</div>` the `x}` becomes `JSXText` instead of trivia, so the crash is avoided and every token is accounted for.

File: tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts (hunk 6 above)
Comment (andrewbranch) [reply tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: Humm, this would be easy enough if the generated diagnostics were a module, but it’s currently an `@internal` slice of the `ts` namespace. Changing/ammending how those get generated might be beyond what I want to cover in the scope of this PR. Writing it down to revisit later. FWIW, I don't like it, but all the existing error stuff in fourslash uses hardcoded messages and codes 😬 Maybe I'll come back and give all those methods a little TLC.

Comment (weswigham) [reply tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: A triple-slash ref to `diagnosticInformationMap.generated.ts` in the `tests/cases/fourslash/fourslash.ts` file aughta do it, but I dunno how that'll affect performance of the foruslash tests.

Comment (andrewbranch) [reply tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: Whaaaaat you can triple slash `@internal` things?! 😮

Comment (weswigham) [reply tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: Well, yeah - the file's not internal or anything, just the namespace inside it. The `@internal` annotation only affects declaration emit.

Comment (andrewbranch) [reply tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: Before:
```
real    1m13.848s
user    9m52.079s
sys     0m23.487s
```

After:
```
real    1m13.816s
user    9m55.116s
sys     0m23.758s
```

Think it's worth the performance hit? 😛

Comment (weswigham) [reply tests/cases/fourslash/jsxExpressionFollowedByIdentifier.ts]: oh, well that's like nothing. yeah, seems fine.

**Comment by andrewbranch** [comment]
@weswigham did you ever have a chance to look at my second iteration of this? I think it’s much more aligned with your initial recommendation.
