### PR TITLE
Don't go past import in cross-project renaming

### LINKED ISSUE #45659: Renaming namespace import from another project will rename its first symbol
# Bug Report

Renaming namespace (star) imports to a file in a different project than the current file will cause the first unexported symbol (variable, function, import, …) to be renamed to the same name as the import itself, if that project was either opened in the editor or referenced by the current `tsconfig.json`.

### 🔎 Search Terms

Rename refactor, Namespace import, project, composite, tsconfig, folders, directories

### 🕗 Version & Regression Information

This was not fixed in the most recent nightly version `4.5.0-dev.20210831`.

- This changed between versions 3.7.7 and 3.8.2
- This changed between nightly versions 3.8.0-dev.20200131 and 3.8.0-dev.20200201

### ⏯ Playground Link

Typescript workbench apparently does not support JSON files, therefore it can not create multiple projects required to reproduce this bug.

Here is the link to [GitHub MWE Repo](https://github.com/esdmr/ts-bug-mwe-rename).

### 💻 Code

1. Create two directories. One at `lib`, and the other at `src`.
2. In both directories create a `tsconfig.json` with any content. An empty object will do.
3. At `lib/lib.ts` create a file with the following content:
   ```ts
   const unrelatedLocalVariable = 123;
   export const someExportedVariable = unrelatedLocalVariable;
   ```
4. At `src/main.ts` create a file with the following content:
   ```ts
   import * as lib from '../lib/lib.js';
   ```
5. Close all tabs.
6. Open `lib/lib.ts` and then open `src/main.ts`.
7. Rename `lib` in `src/main.ts`.

### 🙁 Actual behavior

If `lib/lib.ts` has an unexported symbol at the very top of the file (`unrelatedLocalVariable`), it will rename it to the same name as the import in `src/main.ts`.

### 🙂 Expected behavior

Renaming a namespace import should not modify any external files.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #45659.

The bug seemed to be caused by the cross-project part of "find all references": in `session.ts`, we try to find references in each project in the solution, other than the original project where the request was made. To accomplish this, we call `getDefinitionAtLocation`, and then try to find references to the resulting definition in other projects.
This meant that, in a situation like:
```ts
// lib/lib.ts
const unrelatedLocalVariable = 123;
export const someExportedVariable = unrelatedLocalVariable;
```
```ts
// src/index.ts
import * as lib from '../lib/lib.js';
```
when we tried to rename `lib` in `import * as lib from ...`, we found the original definition (which points to the module/file `lib/lib.ts`), and then tried to rename *that*.

The main thing about the bug, in my perspective, is that we should not try to rename the *original* definition and references to it, and should instead just rename the alias, in this case the namespace import itself (`lib`).
This PR accomplishes that by having `getDefinitionAtLocation` stop at aliases, instead of skipping them. The idea is that now we will find cross-project references to the *alias that is being renamed*, not to the original thing that was aliased.

P.S.: the other thing that seemed weird to me is that, when we try to get the definition of the `lib` namespace in `import * as lib ...`, we get a reference to the `lib/lib.ts` file, at position 0 (references are represented as a file + position). This PR doesn't fix that, so when invoking find all references on `import * as |lib| ...`, we still get one entry pointing to the `lib` file at position 0. But I thought that was a minor problem and something to be fixed in a different PR, if that's the case.

### CODE REVIEW

File: tests/cases/fourslash/server/renameNamedImport.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+// @Filename: /lib/index.ts
+//// const unrelatedLocalVariable = 123;
+//// export const someExportedVariable = unrelatedLocalVariable;
+
+// @Filename: /src/tsconfig.json
+//// {}
+
+// @Filename: /src/index.ts
+//// import { /*i*/someExportedVariable } from '../lib/index';
```
Comment (gabritto) [inline tests/cases/fourslash/server/renameNamedImport.ts:14]: the bug (incorrectly renaming the original thing and not just the local import) also happened for named imports, besides namespace imports.

File: src/services/types.ts [hunk 2]
```diff
@@ -474,7 +474,7 @@ namespace ts {
 
         /*@internal*/
         // eslint-disable-next-line @typescript-eslint/unified-signatures
-        getDefinitionAtPosition(fileName: string, position: number, searchOtherFilesOnly: boolean): readonly DefinitionInfo[] | undefined;
+        getDefinitionAtPosition(fileName: string, position: number, searchOtherFilesOnly: boolean, skipAlias: boolean): readonly DefinitionInfo[] | undefined;
```
Comment (gabritto) [inline src/services/types.ts:477]: I'm not sure this is the best way to add this new parameter, open to feedback on this

File: src/server/session.ts [hunk 3]
```diff
@@ -430,7 +433,7 @@ namespace ts.server {
 
         // After initial references are collected, go over every other project and see if it has a reference for the symbol definition.
         if (initialLocation) {
-            const defaultDefinition = getDefinitionLocation(defaultProject, initialLocation);
```
Comment (gabritto) [inline src/server/session.ts:433]: that's where the logic changed: if we're renaming, we don't skip past aliases when getting the definition, because we want to rename the alias itself (I think), and not the original thing (e.g. we don't want to rename the original variable, just its import)

File: src/services/goToDefinition.ts [hunk 4]
```diff
@@ -40,15 +40,15 @@ namespace ts.GoToDefinition {
...
+        let { symbol, failedAliasResolution } = getSymbol(node, typeChecker, skipAlias);
         let fallbackNode = node;
 
         if (searchOtherFilesOnly && failedAliasResolution) {
             // We couldn't resolve the specific import, try on the module specifier.
             const importDeclaration = forEach([node, ...symbol?.declarations || emptyArray], n => findAncestor(n, isAnyImportOrBareOrAccessedRequire));
             const moduleSpecifier = importDeclaration && tryGetModuleSpecifierFromDeclaration(importDeclaration);
             if (moduleSpecifier) {
-                ({ symbol, failedAliasResolution } = getSymbol(moduleSpecifier, typeChecker));
+                ({ symbol, failedAliasResolution } = getSymbol(moduleSpecifier, typeChecker, skipAlias));
```
Comment (gabritto) [inline src/services/goToDefinition.ts:51]: @andrewbranch I'd like you to take a look at this case and the interaction between `searchOtherFilesOnly` and the new `skipAlias`

File: tests/cases/fourslash/server/renameNamedImport.ts (hunk 1 above)
Comment (andrewbranch) [reply tests/cases/fourslash/server/renameNamedImport.ts:14]: So, I don’t think this one should have changed, or at least, the change here is incomplete. The big difference between import specifiers and every other kind of import alias is that import specifiers must reflect the name of something being exported. If you rename this without renaming the export, you’ll get an error. A default or namespace import is freely nameable. The only ways you can correctly rename an import specifier are by renaming the corresponding export or introducing a local name binding, e.g. `someExportedVariable as foo`. Which one you want to do is subjective/circumstantial, so I’m not sure what the right solution is. We have a preference for the same issue with object literal shorthand properties:

image

I believe this controls whether a rename on

```ts
const x = 0;
const obj = { x/*HERE*/ };
```

becomes

```ts
const renamed = 0;
const obj = { renamed };
```

or

```ts
const x = 0;
const obj = { renamed: x };
```

which are essentially the two options I just outlined for import specifiers, but cross-file. I have never liked this preference because it’s not a _user_ preference per se; sometimes I want one and sometimes I want the other, and it’s annoying that I can’t select the behavior without editing my preferences. Unless we’re willing to take the time to invest in a better solution, I would suggest not changing the import specifier behavior.

File: tests/cases/fourslash/server/renameNamespaceImport.ts [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+
+// @Filename: /lib/index.ts
+//// const unrelatedLocalVariable = 123;
+//// export const someExportedVariable = unrelatedLocalVariable;
+
+// @Filename: /src/tsconfig.json
+//// {}
+
+// @Filename: /src/index.ts
+//// import * as /*i*/lib from '../lib/index';
```
Comment (andrewbranch) [inline tests/cases/fourslash/server/renameNamespaceImport.ts:14]: I’m surprised this is doing the multi-project thing without `references` in `src/tsconfig.jon`. You’re sure this test is doing what you think it is?

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/types.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/types.ts:477]: Small nit but I think I would make it `stopAtAlias` so you can just make it optional instead of defaulting to `true`. But wait until the end of the PR review to do this, because the implication of my other feedback may be that not all aliases should be stopped at / skipped.

File: tests/cases/fourslash/server/renameNamespaceImport.ts (hunk 5 above)
Comment (gabritto) [reply tests/cases/fourslash/server/renameNamespaceImport.ts:14]: I think so, yes. If I revert my change, it fails in exact the same way as the bug does, and debugging it, it seems the same code path is executed. Why are you surprised it works? I'm not sure I understand.

Comment (andrewbranch) [reply tests/cases/fourslash/server/renameNamespaceImport.ts:14]: My mental model of this test is that `/lib/tsconfig.json` would never come into play because `/src/tsconfig.json` directly includes all source files; in other words, you could delete `/lib/tsconfig.json` and the shape of the `/src/tsconfig.json` project would be unaffected. @amcasey can probably explain my mistake in this thinking.

Comment (amcasey) [reply tests/cases/fourslash/server/renameNamespaceImport.ts:14]: We look for the "default" tsconfig, even if we know the file is in a configured project.

**Comment by gabritto** [comment]
> I wish I'd known you were working on the rename logic _in session.ts_ because you probably want to build on top of #48619. It almost certainly doesn't address this problem, and may even make it worse, but it should be much easier to reason about and fix.

Does that mean I should wait for #48619 to be merged and reimplement this on top of that?

**Comment by amcasey** [comment]
> > I wish I'd known you were working on the rename logic _in session.ts_ because you probably want to build on top of #48619. It almost certainly doesn't address this problem, and may even make it worse, but it should be much easier to reason about and fix.
> 
> Does that mean I should wait for #48619 to be merged and reimplement this on top of that?

I was tentatively planning to hold #48619 until 4.8 since it's a bit risky, but I don't think that's essential.  If your change needs to get in for 4.7, I don't mind merging it into my branch later - I just got the impression that there were a lot of open questions and I thought I'd jump in and suggest that any rewrite happen on top for #48619.

Thoughts on sequencing, @andrewbranch?

**Comment by andrewbranch** [comment]
I suspect this can go in for 4.7, and the I’m guessing the merge conflict will likely just be some of the calls you passed the new parameter to in session.ts get deleted altogether. I’ll plan to take a close look at this tomorrow. I want to investigate why `shouldSkipAlias` in goToDefinition.ts wasn’t already working here, as I think it’s supposed to handle exactly this case. I’m guessing it’s due to the complexities of triggering in another project, but that’s so confusing to me that I want to understand it before approving.

**Comment by andrewbranch** [comment]
> I want to investigate why `shouldSkipAlias` in goToDefinition.ts wasn’t already working here, as I think it’s supposed to handle exactly this case.

Ah ok, what I had missed was that the rename location was actually _on_ the namespace import name itself. Go To Definition has the behavior where it will stop at a NamespaceImport but only if you don’t _start_ on the NamespaceImport (that way you can do one jump from a reference to the import, and then another jump to the module it refers to).

File: src/services/goToDefinition.ts (hunk 4 above)
Comment (andrewbranch) [reply src/services/goToDefinition.ts:51]: `skipAlias` should always be `true` when `serachOtherFilesOnly` is `true`.

**Review by andrewbranch — COMMENTED** [review]
I think this is pretty much good—I was confused by the baseline format not showing the `prefixText`/`suffixText`. It would be great if we could make `renameNamedImport.baseline` show up as

```
/*====== /src/index.ts ======*/

import { [|someExportedVariable as RENAME|] } from '../lib/index';
RENAME;
```

I also still think I would recommend naming the new go-to-def parameter `stopAtAlias` or just keep it as `isForRename` since it’s internal.

**Review by andrewbranch — APPROVED** [review]
