### PR TITLE
Fix ternaries where "true" is a parenthesized variable and "false" is a function expression

### LINKED ISSUE #30635: Incorrect parse of parenthesized expression in second ternary operator operand
**TypeScript Version:**  3.4.0-dev.20190328

**Search Terms:**
expression expected, Ternary operation, shorthand

**Code**

```ts
let a;
let b;
const c = true ? (a = 1, b = 2) : function () { return true; };
```

**Expected behavior:**
```javascript
var a;
var b;
var c = true ? (a = 1, b = 2) : function () { return true; };
```

**Actual behavior:**
```javascript
var a;
var b;
var c = true ? function (a, b) {
    if (a === void 0) { a = 1; }
    if (b === void 0) { b = 2; }
    return true;
} : ;
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=let%20a%3B%0D%0Alet%20b%3B%0D%0Aconst%20c%20%3D%20true%20%3F%20(a%20%3D%201%2C%20b%20%3D%202)%20%3A%20function%20()%20%7B%20return%20true%3B%20%7D%3B

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/16241
https://github.com/Microsoft/TypeScript/issues/11582

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #30635

~Decided to try parsing JSDoc function types (e.g. `/** @type {function(): void} */`) only inside JSDoc per @weswigham’s suggestion, see what breaks, and gather feedback.~

~Looks like what breaks is the error message on code like~

```ts
var g: function(number, number): number = (n,m) => n + m;
```

~Previously, the error was `JSDoc types can only be used inside documentation comments`. With this change, it becomes a series of nasty parse errors and `Cannot find name 'function'`. 😕~

Possible simple options off the top of my head:

- Go with this because people probably don't often try to write code like the snippet above
- Try to disable JSDoc function keyword parsing only when parsing the `whenTrue` of a conditional expression: super magically edge-casey but keeps all existing nice error messages.

Thoughts?

---

**EDIT**

Updated with a different approach. Typically, arrow functions parse successfully even if they're missing the `=>` token, since in _most_ cases it's still unambiguously an arrow function that's just missing a `=>`. When parsing the true side of a conditional expression, combined with the fact that `function()` parses as a _type_ for JSDoc compatibility, it's not unambiguously an arrow function.

So, when the arrow function in-progress has a `JSDocFunctionType` type, I don't allow a missing `=>` token.

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -2919,7 +2919,7 @@ namespace ts {
                 case SyntaxKind.QuestionToken:
                     return parseJSDocUnknownOrNullableType();
                 case SyntaxKind.FunctionKeyword:
-                    return parseJSDocFunctionType();
+                    return contextFlags & NodeFlags.JSDoc ? parseJSDocFunctionType() : parseTypeReference();
```
Comment (weswigham) [inline src/compiler/parser.ts]: IMO, rather than falling back to a `parseTypeReference` here, I think we'd rather have `isStartOfType`'s `SyntaxKind.FunctionKeyword` case be predicated on the context and not have `function` be the start of a type outside of a `JSDoc` context. Maybe.

Comment (andrewbranch) [reply src/compiler/parser.ts]: Sounds reasonable, but it turns out that `isStartOfType` is never hit in this path. Here's the relevant call stack:

Pasted Graphic

Comment (andrewbranch) [reply src/compiler/parser.ts]: Another thing we could potentially try to work with is that `tryParseParenthesizedArrowFunctionExpression` only succeeds because it generously ignores a missing `=>` and goes on to parse the arrow function body. If we disable that looseness in this special case, everything after the `?` wouldn't be interpreted as an arrow function, and I bet the next path the parser tries will be correct.

File: src/compiler/types.ts [hunk 2]
```diff
@@ -553,6 +553,7 @@ namespace ts {
         /* @internal */ Ambient                       = 1 << 22, // If node was inside an ambient context -- a declaration file, or inside something with the `declare` modifier.
         /* @internal */ InWithStatement               = 1 << 23, // If any ancestor of node was the `statement` of a WithStatement (not the `expression`)
         JsonFile                                      = 1 << 24, // If node was parsed in a Json
+        /* @internal */ InConditionalWhenTrue         = 1 << 25, // If node was parsed in the true side of a ConditionalExpression
```
Comment (andrewbranch) [inline src/compiler/types.ts]: Is it ok to add this? Is there a better way to look up the tree we're currently creating to see if we're in a special case?

Comment (andrewbranch) [reply src/compiler/types.ts]: Removed; I only needed to look at the current node in the end.
