### PR TITLE
Fix issue #5444

### LINKED ISSUE #5444: Assertion error with if-else-if inside class
Type-checking the following (broken) program:
```
class C {
    if (a) {}
    else if (0) {}
}
```
results in an assertion error:
```
Error: Debug Failure. False expression: 
    at Object.assert (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:724:23)
    at reportImplementationExpectedError (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:18530:38)
    at checkFunctionOrConstructorSymbol (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:18580:25)
    at checkFunctionLikeDeclaration (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:18943:21)
    at checkMethodDeclaration (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:18251:13)
    at checkSourceElement (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:20413:28)
    at Object.forEach (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:90:30)
    at checkClassDeclaration (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:19663:16)
    at checkSourceElement (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:20477:28)
    at Object.forEach (/home/jeffrey/TypeScript-1.6.2/lib/tsc.js:90:30)
```

### PR DESCRIPTION
**Pull request by jeffreymorlan**
reportImplementationExpectedError: The next node in the tree is not
necessarily consecutive. This happens due to syntax errors, e.g.

    class C { foo(), foo(); }

_____________
*Edit by @DanielRosenwasser: Fixes #5444*

### CODE REVIEW

**Comment by mhegazy** [comment]
Can you please add unit tests.

**Comment by DanielRosenwasser** [comment]
To be clear, @mhegazy does't mean a unit test, he means an end-to-end test. Check out [Adding a Test](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#adding-a-test) in our [CONTRIBUTING.md](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md).

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11205,7 +11205,7 @@ namespace ts {
                         seen = c === node;
                     }
                 });
-                if (subsequentNode) {
+                if (subsequentNode && subsequentNode.pos === node.end) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can you add a comment that you need this test because garbage declarations may be introduced between overloads and cause issues with overloads.

**Comment by DanielRosenwasser** [comment]
:+1: @vladima could you take a look?

**Comment by vladima** [comment]
:+1: after @DanielRosenwasser note about the comment is addressed

File: src/compiler/checker.ts (hunk 1 above)
Comment (jeffreymorlan) [inline src/compiler/checker.ts]: Done
