### PR TITLE
`arguments` should not be allowed in class static block

### LINKED ISSUE #48152: `arguments` should not be allowed class static block
# Bug Report

### 🔎 Search Terms
arguments class static block error 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEQMwAoCUiDeBYAKEUQCcBTKEEpCAGwEMBnRxAFV0OOMantgg5EuxAO4ALGLTLoAjNnxDhxeiQDmIALZkwUFgHo9iRmLghaAE0RkSJOCU5KAvg+LOhbx0A)

### 💻 Code

```ts
function D3() {
  return class T {
    static {
      while(1) {
        arguments // should error
      }
    }
  }
}
```

### 🙁 Actual behavior

no error reported.

### 🙂 Expected behavior
a syntax error should be reported.

image

related to #44269

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #48152

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -28898,6 +28898,20 @@ namespace ts {
             });
         }
 
+        function isArgumentsInPropertyInitializerOrClassStaticBlock(node: Node): boolean {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:28901]: Why not update `isInPropertyInitializerOrClassStaticBlock`? The logic in there seems questionable, as it `"quit"`s in as soon as it hits a block body that's not part of an arrow function or class static block. I think that meant something like

```ts
declare function condition(): boolean;
declare function doSomething(x: unknown): void;

class C {
    static {
        if (condition()) {
            doSomething(arguments);
        }
    }
}
```

Comment (Zzzen) [reply src/compiler/checker.ts:28901]: No, [it doesn't fail](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzD2C2zwAoBKALngCMccIQpUBuAKFElgRXVPzAcAZRwBbEBgAWWVAHMyADxpoA1qhwB3VNXgA3HFmAd2fTLnyJK8AN7t4D+HAzIY+bgGcP8AMK37joEeGFDYYP6BkY5YiPBkhKjEApQUEVHpDkKiEtKyCrByyBKoGB4UHBmBAL4BUTXV7DVAA). And I find another issue of current implemetation [playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDC0G8BQ1XQgFzBglsRKaRGAFjhAHQBGhRqOAZtABQCMAlAXd9KedQG5oAemHoSAewCuIACbQApgCclEpbToBfDdo2ZseaFWgBeaKwFJNQA). Guess I can update `isInPropertyInitializerOrClassStaticBlock` and fix both issues

```ts
class C {
    static {
        this.b
        if (1) {
            this.b; // should error
        }
    }

    static b = 1;
}
```

**Review by sandersn — APPROVED** [review]

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -3767,7 +3767,7 @@
         "category": "Error",
         "code": 2814
     },
-    "'arguments' cannot be referenced in property initializers.": {
+    "'arguments' cannot be referenced in property initializers or class static initialization block.": {
```
Comment (jakebailey) [inline src/compiler/diagnosticMessages.json:3770]: Typo here?

```suggestion
    "'arguments' cannot be referenced in property initializers or class static initialization blocks.": {
```

Comment (Zzzen) [reply src/compiler/diagnosticMessages.json]: Oops, nice catch!

**Review by sandersn — APPROVED** [review]
