### PR TITLE
Filter possible contextual return types from unions for async functions and generators

### LINKED ISSUE #41428: 4.1.1-rc strange Type is not assignable to type never with yield & generators
**TypeScript Version:**  4.1.0-beta (4.1.1-rc too)

//cc @mjbvz 

**Expected behavior:**
No error on the following line
```ts
const selection = yield step;
```

As it works fine in TypeScript 4.0.5, and I'm unsure where the `never` is even coming from. Here is the actual source if it is interesting: https://github.com/eamodio/vscode-gitlens/blob/787bc8f3a976135d51032547e209b93267e14b2f/src%2Fcommands%2FquickCommand.steps.ts#L1794-L1814

**Actual behavior:**
Error on the line
```
Type 'QuickPickStep<QuickPickItem>' is not assignable to type 'never'.(2322)
```

**Related Issues:**

**Code**
```ts
export enum Directive {
	Back,
	Cancel,
	LoadMore,
	Noop,
}

export namespace Directive {
	export function is<T>(value: Directive | T): value is Directive {
		return typeof value === 'number' && Directive[value] != null;
	}
}

export interface QuickPickItem {
	label: string;
	description?: string;
	detail?: string;
	picked?: boolean;
	alwaysShow?: boolean;
}


export interface QuickInputStep {

	placeholder?: string;
	prompt?: string;
	title?: string;
}

export interface QuickPickStep<T extends QuickPickItem = QuickPickItem> {
	placeholder?: string;
	title?: string;
}

export type StepGenerator =
	| Generator<QuickPickStep | QuickInputStep, StepResult<void | undefined>, any | undefined>
	| AsyncGenerator<QuickPickStep | QuickInputStep, StepResult<void | undefined>, any | undefined>;

export type StepItemType<T> = T extends QuickPickStep<infer U> ? U[] : T extends QuickInputStep ? string : never;
export namespace StepResult {
	export const Break = Symbol('BreakStep');
}
export type StepResult<T> = typeof StepResult.Break | T;
export type StepResultGenerator<T> =
	| Generator<QuickPickStep | QuickInputStep, StepResult<T>, any | undefined>
	| AsyncGenerator<QuickPickStep | QuickInputStep, StepResult<T>, any | undefined>;
export type StepSelection<T> = T extends QuickPickStep<infer U>
	? U[] | Directive
	: T extends QuickInputStep
	? string | Directive
	: never;
export type PartialStepState<T = unknown> = Partial<T> & { counter: number; confirm?: boolean; startingStep?: number };
export type StepState<T = Record<string, unknown>> = T & { counter: number; confirm?: boolean; startingStep?: number };

export function canPickStepContinue<T extends QuickPickStep>(
	_step: T,
	_state: PartialStepState,
	_selection: StepItemType<T> | Directive,
): _selection is StepItemType<T> {
	return false;
}

export function createPickStep<T extends QuickPickItem>(step: QuickPickStep<T>): QuickPickStep<T> {
	return step;
}

export function* showStep<
	State extends PartialStepState & { repo: any },
	Context extends { repos: any[]; title: string; status: any }
>(state: State, _context: Context): StepResultGenerator<QuickPickItem> {
	const step: QuickPickStep<QuickPickItem> = createPickStep<QuickPickItem>({
		title: '',
		placeholder: ''
	});
	const selection: StepSelection<typeof step> = yield step;
	return canPickStepContinue(step, state, selection) ? selection[0] : StepResult.Break;
}
```

<details><summary><b>Output</b></summary>

```ts
export var Directive;
(function (Directive) {
    Directive[Directive["Back"] = 0] = "Back";
    Directive[Directive["Cancel"] = 1] = "Cancel";
    Directive[Directive["LoadMore"] = 2] = "LoadMore";
    Directive[Directive["Noop"] = 3] = "Noop";
})(Directive || (Directive = {}));
(function (Directive) {
    function is(value) {
        return typeof value === 'number' && Directive[value] != null;
    }
    Directive.is = is;
})(Directive || (Directive = {}));
export var StepResult;
(function (StepResult) {
    StepResult.Break = Symbol('BreakStep');
})(StepResult || (StepResult = {}));
export function canPickStepContinue(_step, _state, _selection) {
    return false;
}
export function createPickStep(step) {
    return step;
}
export function* showStep(state, _context) {
    const step = createPickStep({
        title: '',
        placeholder: ''
    });
    const selection = yield step;
    return canPickStepContinue(step, state, selection) ? selection[0] : StepResult.Break;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2019",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=6&jsx=0&ts=4.1.0-beta#code/KYDwDg9gTgLgBMAdgVwLZwCIEsrAMYxYBuwcA3gFACQAQgIZ4DWANNQMJ2J7AA2rVAGQh0AJgFlowfgDkIEMKwC+FCqEiw4iOqmABnMA1LZcBYqUpU10eADNkXQhERwsugDwAVAHwAKInR5kYAAuTBx8QhI4AB84DwBKUP9A0lcwk0jzaipcGGQoZxgATzBgCBs4ZKC4AF46uAByFFQAI2AoBrgAMi70iLMAbSrgAF04AEIazWQeHgBuamVlVXBrF0QYdptDOABFZCwmAAVDxgBJTfQLHjo2nlDdGCgsRABzBaoRPTxnsEdEAD8DyeL3e1C+MDoWB4QLgj2ebw+YFOwBEsJach4wE4HwCAHc6EVdABlAAWEDx6Mx2MQC2WK3U8Bemyg224ewOTDOiDAyBgxM2YHIKioYBu3HJPC+UFh8NBSKgEFQf1lIMR1EIMCxqoRYOWVg0zK2O32pxOTAFwDAngQIE2iBEug5ZtOF2A6CmpuOrsuXmFovFwEl0p18o1WC1wFD6v1qw0xVKcEtYAA4kh2nQYNBatRYmnEBms1A3F7GObGMmYs6uTy+cnmEnBQAlPQzGBuIgQLAiKv2L42F6orwNzhFXsO4ADgsiLy5uAAQV0RS4+cL0BLnLLp0rsVL3N5-MFDeTLd0bY7XZ7sT7k8HM5HiDH14nU6HCwZawTpGTbtQHhKwCeH6UweLa9qOtWW4WoKbgvDY7RwAAqn6AJIQMYyhKBoDgU6e61oeVpwKhcpvHAoQFiQUALAa8BaDo+g7CerY8PAFg0XAeBOI8cA0LgdCMLUSZFK0EA8D4DS8diFaCg08R0h+8YAY2Vqnue3iCV+5TKWAqksQAdJJ-FVh41FxvAX7abpMCrlAmbrupNRzjZdnFqW5Y7pB+51kelnMe23gPk+cA3q+M5zouy54M5RYbi60GEbum5eQRCi+WeLFAYF479neXimYycAWcmxK8P0ThAYJWF2kgEFuduMFwQhyHUKhiHoVWxj9CQ1CYWBNW4Ul+HJi1cJqq8HXhKY3VUORwCUfln5KUcdCwFgATFZCmw2lM9iMIgFKIMBcDLatAQVb0ZAcRA9gsuRaBtFRV2IAOUCoFSok0nMo0rYQbzJrCzQPXAigLYpiYbZmgGgVMLacVAIhuCRrwNrt+14odR2gRdV03e0d2tO0X2cc9OBvaEGIfTi32rX9goA-dCEgyo7F2A4WBOBxnDuYKbBOL9QQ2th-WQdzVq+NQAD6jxWph-BS5tITHT9a08BDmxy7opWmE4oQ-pc-6lBVsSdVNUgUIkcBS1r-wuE6evugbUN+hYuT5M42w8Jr8kKbY9ja84PzYpsovWlVOEiz67q+NLYChHV8Wh14Fvx9JVoVS7wB5AUo1Wt7LN+-8ABUcLkniyZuNQAqQ31DpOidhDrYKVebN05BwLgkChKOwP8LzGzYTXEGXR3EC6F3j7oV9mpYsCupfY8mbIGPcDd8o0cK7rCsNhLxObHaoR93vMAW0x6XWemtkxSnv7O9QxPcTHcebiHsXelyvqCYHkMv9fvo+BYVBp6KwaA0fgAZDDBjxo0Boiw5J3y4vATWWJ-abytCVZB-w3CaQqDHI6RQsC8B7DHD4rts54C5vVK0h8XhBB8DHBsC91ZwmtuzRA8QiLMIwawgYAAGDCaU2wGT4owOkQA)

### LINKED ISSUE #42439: Union of Generator and AsyncGenerator introduces spurious undefined next() value path
# Bug Report

I was creating a coroutine-based interactive prompt library. It can consume either synchronous or asynchronous co-routines. 

There doesn't seem to be any runtime issue associated with this approach, (in some configurations the library harmlessly awaits on a synchronous generator.next()). 

However, any function which is declared as fulfilling a union of async+sync generators faces a compile error when a spurious `undefined` value is indicated as possible from a `yield` even though the next() call only accepts strings.

### 🔎 Search Terms

yield, undefined, typescript, asyncgenerator, generator

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about AsyncGenerator

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=5#code/C4TwDgpgBAyiB2BjGECOBXCSIDECGiwA9gE4hQC8UAFAJSUB8UA4lhCXsSQDwDOwJAJbwA5gBoo-IaIlThIhgG4AUMtCQoAQV4JkaTNnyFS5KnUZadSVvHadSfAfNlOZk1wpVrw0FBiyIuARcprC6fgaBRiFQAD6W4foBQcZkqohE8PySutEmAFxhSBHJeWSUUABm6EjAgpkAVDS0AN7KUFAANhDAUPB4ALbQVABEIyodAO4AFoLd1ACE-UOt7R19g8NQIIIQnQAmUCMA6tOcUIK820ToJBtDAPwjawC+ayQ9t-BQAAYAKmdgAByK7AabQLCHIiVKBg6AiTYSAAkLWWEBeP2ULyg6Uy2TwVkQZRAhW0iX8hmCJgqBN0VRqhHq8CadDaHW6vTRFTGEygMzmEEWaNW63uWx2e0OJ0BFyuIBudzRT1e70+JG+-0BINh4KgkKg0J18MRUBRaIxWJxygyWV6nSIRF47DgSGJhRKlNSoWqtSZLJFXR6Yu54zW-PmS02AY6XKoEoOR1O50u11uYuVHTeHQ+wC+vwBnG1cL18ChMOLCKGyNRmwt2Nxtq6DqdJDJrqpZHdSU9MSotKQ9N9jWabMDnM2Id54cFkZWo5jE7juwT0uTcoV6eemdVufV+a1oN1+sNFZNZtrmPrQA)

### 💻 Code

```ts
type SyncSequenceFactory = () => Generator<string, string, string>;

type AsyncSequenceFactory = () => AsyncGenerator<string, string, string>;

type SequenceFactory = SyncSequenceFactory | AsyncSequenceFactory

const syncFactory: SyncSequenceFactory = function* (){
  let name = "";
  while(!name){
    name = yield "What is your name?"
  }
  return `That's the end of the game, ${name}`
} 

const asyncFactory: AsyncSequenceFactory = async function* (){
  let name = "";
  while(!name){
    name = yield "What is your name?"
  }
  return `That's the end of the game, ${name}`
} 

const looserSyncFactory: SequenceFactory = function* (){
  let name = "";
  while(!name){
    name = yield "What is your name?"
  }
  return `That's the end of the game, ${name}`
} 

const looserAsyncFactory: SequenceFactory = async function* (){
  let name = "";
  while(!name){
    name = yield "What is your name?"
  }
  return `That's the end of the game, ${name}`
} 

```

### 🙁 Actual behavior

Compiler reports `Type 'string | undefined' is not assignable to type 'string'.`

### 🙂 Expected behavior

I don't believe this possible execution path is actually made possible by the union, since it is not possible in either of the unioned cases.

### LINKED ISSUE #47682: Contextual generic return type of an async function includes union members from the context that it shouldn't
# Bug Report

### 🔎 Search Terms

contextual typing, generic, async, return type, union

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[TS playground (latest)](https://www.typescriptlang.org/play?ts=4.5.4#code/CYUwxgNghgTiAEkoGdnwMoBcqZAWSjAAsBLAOxAB4AVAPngG8BYAKHngHsyARLkALngAKKIOoBKeAF56ANw4lgAblYBfVq1BI48AGYBXMmEwkuiODnyFSFGrSEkAtgAcIIRyDLYTXZIOZs8MggMLIkYCB+8ABK4BwwwJTImDDkAOYANMKSMvAACjAcjiTBdvAAPhjeVsTkVHS0Kiyq4oLyik2sYBa4BLW2DIgchpiCZPqOAEYh8Kr2AezBoeGR-qzs7LjJgigAnkbZ0vQFRSUgAHRwAFbgmEIARMhFCCEw9+IZ6xt7B1uYAExCSQLDbsOCYfQwMj5QrFYKXEA3YwPJ4eeCvd5NUGqT6BHFqcSdFgGIw+aG6MgARiBgiBRxhp1KgzAwy8Ywm0xgs3olSwlj6NiozNZo3g4ymMzmjC+4Mh0J+YEOuROcIu11uQgA5KiXjAYJrxGogA)
[TS playground (nightly)](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/CYUwxgNghgTiAEkoGdnwMoBcqZAWSjAAsBLAOxAB4AVAPngG8BYAKHngHsyARLkALngAKKIOoBKeAF56ANw4lgAblYBfVq1BI48AGYBXMmEwkuiODnyFSFGrSEkAtgAcIIRyDLYTXZIOZs8MggMLIkYCB+8ABK4BwwwJTImDDkAOYANMKSMvAACjAcjiTBdvAAPhjeVsTkVHS0Kiyq4oLyik2sYBa4BLW2DIgchpiCZPqOAEYh8Kr2AezBoeGR-qzs7LjJgigAnkbZ0vQFRSUgAHRwAFbgmEIARMhFCCEw9+IZ6xt7B1uYAExCSQLDbsOCYfQwMj5QrFYKXEA3YwPJ4eeCvd5NUGqT6BHFqcSdFgGIw+aG6MgARiBgiBRxhp1KgzAwy8Ywm0xgs3olSwlj6NiozNZo3g4ymMzmjC+4Mh0J+YEOuROcIu11uQgA5KiXjAYJrxGogA)

### 💻 Code

```ts
declare class StateMachine<T> {
  onDone: (a: T) => void;
}

declare function createMachine<T>(implementations: {
  services: Record<string, () => Promise<T> | StateMachine<T>>;
}): void;

// this is close to my original issue found in the real-world in XState
createMachine<{ count: number }>({
  services: {
    test: async () => Promise.reject("some err"),
    async test2() {
      return Promise.reject("some err");
    },
  },
});

// this is an additional test case I've figured out that behaves in a similar way.
function fn1(): () => Promise<{ count: number }> | StateMachine<{ count: number }> {
  return async () => Promise.reject('some err')
}
```

### 🙁 Actual behavior

Both tests fail to compile and the reported error looks bizzare(-ish):
```
Type '() => Promise<{ count: number; } | StateMachine<{ count: number; }>>' is not assignable to type '() => Promise<{ count: number; }> | StateMachine<{ count: number; }>'.
  Type 'Promise<{ count: number; } | StateMachine<{ count: number; }>>' is not assignable to type 'Promise<{ count: number; }> | StateMachine<{ count: number; }>'.
    Type 'Promise<{ count: number; } | StateMachine<{ count: number; }>>' is not assignable to type 'Promise<{ count: number; }>'
```

For some reason, the return type here didn't narrow the contextual union to include only Promise(-like?) members and dragged the whole `Awaited<Union>` to the computed contextual type. And this has caused an assignability problem.

Note that this "only" happens with `Promise.reject`, it's not reproducible with `Promise.resolve` and other similar types. My guess is that it's because `Promise.reject` contains a generic only at the return type position and this is what makes this issue manifest somehow.

### 🙂 Expected behavior

No error should be reported because this is valid code and it looks like sufficient information has been provided in the context for this to be narrowed down properly~.

--- 

While looking into this problem I've poked around the internals of TS and figured out that this might be a potential fix for this issue: https://github.com/microsoft/TypeScript/pull/47683

### LINKED ISSUE #51187: Bug: incorrect contextual typing on yield expression of generator function as discriminate of a union
# Bug Report

### 🔎 Search Terms

generator function union contextual typing yield expression

### 🕗 Version & Regression Information

4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHZQLxQBQEpMB8OA4hKhAE4CGwyFAPAM7AWKoDmANFM6x97zbsA2gF0iAHx4shuAFBy4aZlABGALlgIU6LADMArqm1oAVDnwBvBTah2oS1CriYoIRBAA2AEygByPzl7KAoIYAMKdAC5AF85IA)

image

### 💻 Code

```ts
type Action = () => (Generator<string, string, string[]> | string)

const b: Action = function* () {
    // expect `string[]`, actual `never`
    const c = yield ''
    return ''
}

```

### 🙁 Actual behavior

`never`

### 🙂 Expected behavior

`string[]`

### PR DESCRIPTION
**Pull request by Andarist**
fixes #51187
fixes #47682
fixes #41428
supersedes #47683
fixes #42439

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -27181,7 +27181,17 @@ namespace ts {
...
-                return getReturnTypeOfSignature(signature);
+                const functionFlags = getFunctionFlags(functionDecl);
+
+                return filterType(getReturnTypeOfSignature(signature), returnType => {
+                    if (functionFlags & FunctionFlags.Generator) {
+                        return checkGeneratorInstantiationAssignabilityToReturnType(returnType, functionFlags, /*errorNode*/ undefined);
+                    }
+                    if (functionFlags & FunctionFlags.Async) {
+                        return !!getAwaitedTypeOfPromise(returnType);
+                    }
```
Comment (Andarist) [inline src/compiler/checker.ts:27192]: This block supersedes [my other attempt from a couple of months back](https://github.com/microsoft/TypeScript/pull/47683/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8) at fixing #47682 . I think that the fix here is better but perhaps that older one might be still interesting for reviewers

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -27181,7 +27181,17 @@ namespace ts {
...
             if (signature && !isResolvingReturnTypeOfSignature(signature)) {
-                return getReturnTypeOfSignature(signature);
+                const functionFlags = getFunctionFlags(functionDecl);
+
+                return filterType(getReturnTypeOfSignature(signature), returnType => {
+                    if (functionFlags & FunctionFlags.Generator) {
+                        return checkGeneratorInstantiationAssignabilityToReturnType(returnType, functionFlags, /*errorNode*/ undefined);
+                    }
+                    if (functionFlags & FunctionFlags.Async) {
+                        return !!getAwaitedTypeOfPromise(returnType);
```
Comment (Andarist) [inline src/compiler/checker.ts:27191]: This is a `isPromise` check based on the existing one in the codebase:
https://github.dev/microsoft/TypeScript/blob/98c19cbbbe83c2ae3c89a4e08317a4b9ccbcb206/src/compiler/checker.ts#L38691

File: tests/baselines/reference/contextualTypeOnYield2.types [hunk 3]
```diff
@@ -5,7 +5,7 @@ type OrGen = () => (number | Generator<string, (arg: number) => void, undefined>
 
 const g: OrGen = function* () {
 >g : OrGen
->function* () {    return (num) => console.log(num);} : () => Generator<never, (num: number) => void, unknown>
+>function* () {    return (num) => console.log(num);} : () => Generator<never, (num: number) => void, undefined>
```
Comment (Andarist) [inline tests/baselines/reference/contextualTypeOnYield2.types:8]: All 3 affected baselines are directly related to the change and they are improvements/fixes

**Comment by Andarist** [comment]
@jakebailey what would you say about being nerd-sniped into reviewing this one? 😅

**Comment by jakebailey** [comment]
I can at least be nerd sniped into running the tests.

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by Andarist** [comment]
> I can at least be nerd sniped into running the tests.

I'll take it, thanks!

**Comment by jakebailey** [comment]
Yay npm timeouts

@typescript-bot run dt

**Comment by Andarist** [comment]
Thanks for that test run! It seems that all of the reported failures might be related to promise-likes/thenables, I will dig into this. I prepared minimal repro cases for all 3: [TS playground](https://www.staging-typescript.org/play?ts=5.1.0-pr-51196-8#code/PTAEEYCgBMFMGMA2BDATrUTkGdugBICW2ALgPaoCeAkibALagDekoohAdgA4CuJAXM1ZtQiMvGQlCZDoJYiRPVIUGllHAOYBuYWwC+O-Tr2RInOqgBmyeBgAqAC1gdkAI0SwAPHYB8QtiROHN4ASrDYPIgkPgAUuqAylpGWhIge0AD8gjEAbsiIPLCCdgCUoAC8fnZhEVGgAD6gjs5uHqHhkdEANPEy6ABWCHSZ2eg4MoLIHJRllU01nQ1NQa1e1R1RPsIlxSvuawubhqCBzu210XEKicmp6VmgufmFxbNVhyRLzS77550+PWuHAGQ1gI0eY2wE1AUxmFT8OTIhGg212LV+6wuPmMplgAA8uBRPnAsOhQEkOPApDJQPiEHxYABhMj0ehTaDeCqgHgcADWHDIAHcOLFhPAWWyONBVCR1BpAaAAHTK9CkSbTADaAF1IDtlui2r4dJB8YTUMSECgyRSqdIOKB0BpiBZmaz2VdMBL2TK5QqJGlXDZedllYq0BpsOrKNq3jDpgrAsQAIKoDQPWG6wSI5HGx3O2CoV2S6AxABEAH10JYC85bNgALQ5QiwQWK7AOIVEUgUGh0eilrow7CUSmPQh92PydiWMd99gcUhTWxkGdd8hUWgMMpTtjoEhKe10+AMovu0s5bDiuCKshcZwD9h9xWcXgkRViCTUjiKpSEErHEw9H-UwQFAAAmGBLTQDAsFwUBmQ4Og8U+KcuGUPI6FASseR+DwcRISg71AAARGQMHKR4C1QdNpljbNoB0AiiIAMR5eAuRiRNI3gmQkJIQdoDIwRSI4WA6KRBjICYjAk2HSlWNHCjOIcYhBAQvjYwABVQFliFgAAZQheS8WFsVMcwC2sWwmnCEgFNtGkpxiSxZFAey9Xo45nNc2SR3gdyswkrypBIDwfU4eVyQ4B4AtATzhE48cwtANQIsHFyHl8+S2I8oLIBMSDSRgmRSBOWzils+yv2NCyrBsDBtPEcJsDsdBYAAOTIOB-FALhkUEDgeHoVwC2OFx6CKFLZQi44JvoHsHkG4bRrFL0pUM0SHlSzRjngFTEGgdBXMausWrazq4G1HETQJIlQBJK0MBtL9QA0WASBO5rWtgWAPR0sgPv60AlpG1A-XyRBA3gYNHllH7BE+3Bvo6rqxPhOKJMzDGc1MOhSDLQVOEEwUGzQprcHrOHYAfHA-MeSdhD3A9gZbUBGvoPSYhiVUyEQHJYEHEEqQZhQ3o+nTTuRmJwDAgBmQdOLakWFGnWGlZ6lWHXCXn+ZiYDNb0WlEGwDAdxVoWSBiUTBVAABRVAdNQAmiaFUmJeaym2tLEp9ZVkwFCAgDgMDkCwFlsxEMs+rQGofTxHyW3kOcbA7R65MuC4RBCE-O0AGVxTvaVQFcMhedgKZjl4dxiCcVBqCL7aNCWQa0nwwiMAAWXe5BoEkZAuSnHguF74ZBBLsuK-ynQHug8k2Jey8pi7kge77j0P3yQRY-jxBE7oBc7Sx9m9M8ZfV5XpYeTgFJROgMzIFp0dntTgvKD35O7WwD1LB0+h34PkqW847+n-inGQ2oj6-xPvRPwU5xQLk+PifeYCFyCA1NvEBScAEcEHGfEe-dGhX1gDfMEWptQVHiMgQUyBxxsygSbMMaQPQKB-iyUBn94gKEVCkKIBYuZozmAAQlgM+bASYM5ZxzjIfOt4wQlE4SIRUbIuAxEfuxGIAi-AagFjCahtDF4cDwWvMSWp5EKGDpAIAA)

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -28733,7 +28733,17 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+
+            return filterType(getReturnTypeOfSignature(signature), returnType => {
+                if (functionFlags & FunctionFlags.Generator) {
+                    return checkGeneratorInstantiationAssignabilityToReturnType(returnType, functionFlags, /*errorNode*/ undefined);
+                }
+                if (functionFlags & FunctionFlags.Async) {
+                    return !!getAwaitedTypeOfPromise(returnType);
+                }
+                return true;
+            });
```
Comment (rbuckton) [inline src/compiler/checker.ts:28746]: I would change it to something like the following so that you don't call `filterType` when it's not needed:

```suggestion
            const functionFlags = getFunctionFlags(functionDecl);
            const returnType = getReturnTypeOfSignature(signature);
            if (functionFlags & FunctionFlags.Generator) {
                return filterType(returnType, t => checkGeneratorInstantiationAssignabilityToReturnType(t, functionFlags, /*errorNode*/ undefined));
            }
            if (functionFlags & FunctionFlags.Async) {
                return filterType(returnType, t => !!getAwaitedTypeOfPromise(returnType);
            }
            return returnType;
```

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -36957,7 +36967,10 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         // There is no point in doing an assignability check if the function
         // has no explicit return type because the return type is directly computed
         // from the yield expressions.
-        const returnType = getReturnTypeFromAnnotation(func);
+        let returnType = getReturnTypeFromAnnotation(func);
+        if (returnType && returnType.flags & TypeFlags.Union) {
+            returnType = filterType(returnType, t => checkGeneratorInstantiationAssignabilityToReturnType(t, functionFlags, /*errorNode*/ undefined));
+        }
```
Comment (rbuckton) [inline src/compiler/checker.ts:36973]: Is this necessary? I think it makes sense to be more forgiving for contextual types, but if you write:
```ts
function * f(): Generator<A, B, C> | string {}
```
then you'll probably have other issues with assignability. I'm not sure we should filter the return type of an explicit type annotation.

Is this to support #41428? If so, I'm not sure we should try to handle a case of

```ts
function * f(): Generator<A> | AsyncGenerator<A> {}
```

since a normal generator is incapable of producing an async generator.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 5 above)
Comment (Andarist) [reply src/compiler/checker.ts:36973]: > Is this to support https://github.com/microsoft/TypeScript/issues/41428? If so, I'm not sure we should try to handle a case of

Yes, it was added in this commit: ["Filter annotated return type within `checkYieldExpression`"](https://github.com/microsoft/TypeScript/pull/51196/commits/dfe955a861eec22029dc12bd5fc2f0db881ede12)

> since a normal generator is incapable of producing an async generator.

That is true, I just assumed that this might be wanted to handle mixed unions. The `function*` is just sugar and with regular functions, we are free to assign wider return types than what is required to be covered. So, from my PoV, this was meant as a convenience - it's more about type reusability than about actually wanting to write a union like this directly as the return type annotation, usually it would come from an alias.

File: tests/cases/compiler/noImplicitReturnsExclusions.ts [hunk 6]
```diff
@@ -58,3 +58,39 @@ function f16(b: boolean) {  // Error
...
+  ...rest: any[]
+): Thenable<T>;
+
+export declare function registerCommand(
+  command: string,
+  callback: (...args: any[]) => any,
+  thisArg?: any
+): void;
+
+registerCommand("_references-view.showHistoryItem", async (item) => { // Error, contextual return type of Promise<unknown>
```
Comment (Andarist) [inline tests/cases/compiler/noImplicitReturnsExclusions.ts:92]: When I created this PR, this code wasn't erroring. My initial changes created a regression with this code and it started to error (problem caught by the extended test suite). However, right now it is **supposed** to error as per the change [here](https://github.com/microsoft/TypeScript/pull/53607/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R35668-R35670). I decided to add this as an extra regression test.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -28932,7 +28932,19 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         // and that call signature is non-generic, return statements are contextually typed by the return type of the signature
         const signature = getContextualSignatureForFunctionLikeDeclaration(functionDecl as FunctionExpression);
         if (signature && !isResolvingReturnTypeOfSignature(signature)) {
-            return getReturnTypeOfSignature(signature);
+            const returnType = getReturnTypeOfSignature(signature);
+            const functionFlags = getFunctionFlags(functionDecl);
+            if (functionFlags & FunctionFlags.Generator) {
+                return filterType(returnType, t => {
+                    return !!(t.flags & (TypeFlags.AnyOrUnknown | TypeFlags.Void | TypeFlags.InstantiableNonPrimitive)) || checkGeneratorInstantiationAssignabilityToReturnType(t, functionFlags, /*errorNode*/ undefined);
```
Comment (Andarist) [inline src/compiler/checker.ts:28939]: I'm not super fond of this check here (talking mainly about `TypeFlags.InstantiableNonPrimitive` check, the rest is OK).

I analyzed all of the core logic behind this change and I think it's sound. This particular check might be slightly off though. In addition to that, I think that this logic could be improved further for instantiable types **but** I don't know how to do it right now. I think that this PR is an improvement already though and that it could be merged without fixing it right now.

I only have a single idea to fix this: create copies of instantiable types here with the same~ filtering logic applied to their constraints (perhaps the filtering could stay deferred so we wouldn't have to compute it until requested). I'm not sure how feasible this is and if it's the right approach so I'm not even taking a stab at this right now.

The overall idea behind this part of the fix is that we want to reject contextual types that are guaranteed to not match the given function's criteria (non-promises/non-generators). We also need to keep the types that poison the type (like any/unknown/void).

We need to do this here, for example, because `getContextualTypeForReturnExpression` uses the result of this function (`getContextualReturnType`). Let's consider this example:
```ts
declare function load(): Promise<boolean>;
type LoadCallback = () => Promise<boolean> | string;
const cb1: LoadCallback = async () => load().then(m => m);
```
In a case like this, we shouldn't allow `string` to be used as the contextual type for this return expression (of the inner arrow function). If we don't reject it soon enough then we end up with `Promise<string | boolean>` as the result of `getContextualTypeForReturnExpression` and thus we end up with an assignability problem as that's not assignable to `Promise<boolean>`.

Initially, I was trying to fix this by filtering in the `getContextualTypeForReturnExpression` [here](https://github.com/microsoft/TypeScript/pull/47683/files) but I found out that filtering in `getContextualReturnType` gives better results for some of the other added test cases in this PR here.

**Comment by Andarist** [comment]
@rbuckton friendly 🏓
