### PR TITLE
Treat any mix of element/prop access as declaration in JS

### LINKED ISSUE #34642: TS3.7 regression: crash checking JS assigning properties in array literal
**TypeScript Version:**  3.7.0-beta

**Code**

```ts
function fun() {
  var arr = [];
  var mean = [
    arr[0].prop[0] = 1,
  ];
}
```

**Expected behavior:**

Pass.

**Actual behavior:**

Crash:

```
node_modules/typescript/lib/tsc.js:1808
            throw e;
            ^

Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isBindableStaticAccessExpression'.
    at Object.cast (node_modules/typescript/lib/tsc.js:1268:25)
    at bindSpecialPropertyAssignment (node_modules/typescript/lib/tsc.js:25709:53)
    at bindWorker (node_modules/typescript/lib/tsc.js:25329:29)
    at bind (node_modules/typescript/lib/tsc.js:25221:13)
    at bindEach (node_modules/typescript/lib/tsc.js:23997:21)
    at visitNodes (node_modules/typescript/lib/tsc.js:14079:24)
    at Object.forEachChild (node_modules/typescript/lib/tsc.js:14237:24)
    at bindEachChild (node_modules/typescript/lib/tsc.js:24005:16)
    at bindChildrenWorker (node_modules/typescript/lib/tsc.js:24102:21)
    at bindChildren (node_modules/typescript/lib/tsc.js:23975:17)
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #34642 but, notably, doesn't actually make the assignment into a working declaration. It just fixes the crash.

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -2061,26 +2061,30 @@ namespace ts {
...
-        || isBindableStaticElementAccessExpression(node, excludeThisKeyword);
+            || isBindableStaticElementAccessExpression(node, excludeThisKeyword);
+    }
+
+    /** Any series of property and element accesses, ending in a literal element access */
+    export function isBindableStaticElementAccessExpression(node: Node, excludeThisKeyword?: boolean): node is BindableStaticElementAccessExpression {
+        return isLiteralLikeElementAccess(node)
+            && ((!excludeThisKeyword && node.expression.kind === SyntaxKind.ThisKeyword) ||
+                isEntityNameExpression(node.expression) ||
+                isBindableStaticAccessExpression(node.expression, /*excludeThisKeyword*/ true));
```
Comment (sandersn) [inline src/compiler/utilities.ts]: the fix is actually here: previously it called `isBindableStaticElementAccessExpression`, which meant that element accesses had to be trailing; they were not allowed to be interspersed.

**Comment by sandersn** [comment]
@RyanCavanaugh this needs to be cherry-picked into release-3.7, right? I'm not sure what the RC release state is.

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this to release-3.7

And next time reply with syntax help
