### PR TITLE
fix(48542): Crash in signature help in declaration list contextually typed by union

### LINKED ISSUE #48542: Crash in signature help in declaration list contextually typed by union
Repro for https://github.com/microsoft/TypeScript/issues/46898

```ts
declare const doIt: (fn?: ((x: string) => string) | ((y: number) => number)) => void;

doIt((/*$*/) => {
    return undefined;
});
```

Request signature help at `/*$*/`

```
Response received: signatureHelp (1956). Request took 2 ms. Success: false . Message: Error processing request. Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at chooseBetterSymbol ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142314:22)
    at tryGetParameterInfo ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142283:120)
    at getImmediatelyContainingArgumentOrContextualParameterInfo ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142265:20)
    at _loop_9 ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142438:36)
    at getContainingArgumentInfo ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142444:31)
    at Object.getSignatureHelpItems ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:142043:32)
    at Object.getSignatureHelpItems ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:163690:37)
    at IpcIOSession.Session.getSignatureHelpItems ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175198:62)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:173939:61)
    at [NODE_MODULES_DIR]/typescript/lib/tsserver.js:175829:88
    at IpcIOSession.Session.executeWithRequestId ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175820:28)
    at IpcIOSession.Session.executeCommand ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175829:33)
    at IpcIOSession.Session.onMessage ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:175855:35)
    at process.<anonymous> ([NODE_MODULES_DIR]/typescript/lib/tsserver.js:178490:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #48542

### CODE REVIEW

File: src/services/signatureHelp.ts [hunk 1]
```diff
@@ -307,10 +307,13 @@ namespace ts.SignatureHelp {
         // for optional function condition.
         const nonNullableContextualType = contextualType.getNonNullableType();
 
-        const signatures = nonNullableContextualType.getCallSignatures();
-        if (signatures.length !== 1) return undefined;
+        const symbol = nonNullableContextualType.symbol;
+        if (symbol === undefined) return undefined;
 
-        const invocation: ContextualInvocation = { kind: InvocationKind.Contextual, signature: first(signatures), node: startingToken, symbol: chooseBetterSymbol(nonNullableContextualType.symbol) };
+        const signature = firstOrUndefined(nonNullableContextualType.getCallSignatures());
```
Comment (DanielRosenwasser) [inline src/services/signatureHelp.ts:313]: If I'm not mistaken, it looks like this is also changing some other behavior for examples like the following:

```ts
interface MultiSignatureCallback {
    (x: string): string;
    (x: number): number;
    (x: string | number): string | number;
}

declare function doIt(callback: MultiSignatureCallback): void;

doIt((/*$*/) => {});
```

We should add some sort of test for this. Technically that function will never be contextually typed, but it is often helpful to see the signature help when typing it out. So I think it's useful to show *some* signature in these cases.

If we want to do that right, I think we should probably switch to the last signature rather than the first. We generally make the assumption that the last signature is always the most-general.

```suggestion
        const signature = lastOrUndefined(nonNullableContextualType.getCallSignatures());
```

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
Can we add a test and switch to the last overload?

**Review by DanielRosenwasser — APPROVED** [review]
