### PR TITLE
Code fix to remove unused named import should preserve default import 

### LINKED ISSUE #14164: Remove unused import for single named import incorrectly removes default import as well
```ts
// ./a.ts

export default 10;
export var x = 10;
```

```ts
// ./b.ts
import A, { x } from './a'

console.log(A)
```

Expected: The available quick fix to remove the unused variable `x` removes only the named import clause.
Actual: The quick fix removes the entire import statement.

### PR DESCRIPTION
**Pull request by minestarks**
Fixes #14164

### CODE REVIEW

File: src/harness/fourslash.ts [hunk 1]
```diff
@@ -2348,7 +2352,7 @@ namespace FourSlash {
         private applyCodeActions(actions: ts.CodeAction[], index?: number): void {
             if (index === undefined) {
                 if (!(actions && actions.length === 1)) {
-                    this.raiseError(`Should find exactly one codefix, but ${actions ? actions.length : "none"} found.`);
+                    this.raiseError(`Should find exactly one codefix, but ${actions ? actions.length : "none"} found. ${actions ? actions.map(a => `"${a.description}"`).join(", ") : "" }`);
```
Comment (amcasey) [inline src/harness/fourslash.ts]: "found:"?

File: src/harness/fourslash.ts [hunk 2]
```diff
@@ -1797,6 +1797,10 @@ namespace FourSlash {
                 // this.languageService.getScriptLexicalStructure(fileName);
             }
 
+            if (this.currentCaretPosition < 0) {
+                this.currentCaretPosition = 0;
```
Comment (amcasey) [inline src/harness/fourslash.ts]: Why is this okay?  Shouldn't it be an error to make the position go negative?

File: tests/cases/fourslash/unusedImports13FS.ts [hunk 3]
```diff
@@ -0,0 +1,12 @@
+/// <reference path='fourslash.ts' />
```
Comment (amcasey) [inline tests/cases/fourslash/unusedImports13FS.ts]: What's "13FS"?

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 4]
```diff
@@ -118,25 +116,34 @@ namespace ts.codefix {
...
+                if ((<ImportClause>namedBindings.parent).name) {
+                    // Delete named imports while preserving the default import
+                    // import d|, * as ns| from './file'
+                    // import d|, { a }| from './file'
+                    const previousToken = getTokenAtPosition(sourceFile, namedBindings.pos - 1, /*includeJsDocComment*/ false);
+                    if (previousToken && previousToken.kind === SyntaxKind.CommaToken) {
+                        const startPosition = textChanges.getAdjustedStartPosition(sourceFile, previousToken, {}, textChanges.Position.FullStart);
+                        return [deleteRange({ pos: startPosition, end: namedBindings.end })];
+                    }
+                    return undefined;
```
Comment (amcasey) [inline src/services/codefixes/fixUnusedIdentifier.ts]: The caller declares that it can return `undefined`, but it's not clear that that ever happened or that it would work if it did.

There also appear to be cases where it returns `[undefined]`, which seems even weirder.

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 5]
```diff
@@ -118,25 +116,34 @@ namespace ts.codefix {
...
 
+            function deleteNamedImportBinding(namedBindings: NamedImportBindings): CodeAction[] | undefined {
+                if ((<ImportClause>namedBindings.parent).name) {
+                    // Delete named imports while preserving the default import
+                    // import d|, * as ns| from './file'
+                    // import d|, { a }| from './file'
+                    const previousToken = getTokenAtPosition(sourceFile, namedBindings.pos - 1, /*includeJsDocComment*/ false);
+                    if (previousToken && previousToken.kind === SyntaxKind.CommaToken) {
+                        const startPosition = textChanges.getAdjustedStartPosition(sourceFile, previousToken, {}, textChanges.Position.FullStart);
+                        return [deleteRange({ pos: startPosition, end: namedBindings.end })];
```
Comment (amcasey) [inline src/services/codefixes/fixUnusedIdentifier.ts]: What happens if there are comments in and around the names?

File: src/harness/fourslash.ts (hunk 2 above)
Comment (minestarks) [inline src/harness/fourslash.ts]: It's an effect of this code to adjust caret position as we apply edits:
```ts
if (offsetStart <= this.currentCaretPosition) {
    this.currentCaretPosition += editDelta;
}
```
```editDelta``` can be negative. If you delete a span that contains the current caret position (perfectly valid), the caret position may end up going negative. 

There are alternative ways of fixing this (e.g. make sure the caret position remains positive _inside_ the for loop instead of fixing it afterwards) but I didn't see a compelling reason to prefer one over the other.

File: src/harness/fourslash.ts (hunk 1 above)
Comment (minestarks) [inline src/harness/fourslash.ts]: Yeah, I had it that way at first, but it looks silly when ```actions.length``` is zero. Instead of adding fancy formatting logic I went with something that looks sort of okay in either case :)

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 5 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: ```import /* foo */ A, { x } from './a'``` => ```import /* foo */ A from './a'``` 
```import A, { /* foo */ x } from './a'``` => ```import A from './a'```
```import A,  /* foo */ { x } from './file2'``` => ```import A from './file2'```
```import A /* foo */, { x } from './file2'``` => ```import A from './file2'```

Comment (amcasey) [inline src/services/codefixes/fixUnusedIdentifier.ts]: I'm not sure I agree with the last one.  The others look good.

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 4 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: I had my questions about this too. 

My understanding is that ultimately this undefined will be returned from ```getCodeActions``` which is treated by the ```codeFixProvider``` to mean no code fixes are available. So I'm pretty confident returning ```undefined``` is valid and will be handled gracefully.

However I am confused about how to handle seemingly impossible cases (like this one). I don't expect to ever reach this branch and I don't have any test coverage for it. I returned ```undefined``` here to avoid deleting code in an unexpected case. But the previous version of the code would have returned ```return [deleteRange(namespaceImport)];``` and I'm not sure why. Asking @aozgaa ...

I'm not sure about ```[undefined]```  -- I have a feeling VS would not take that too well.

File: tests/cases/fourslash/unusedImports13FS.ts (hunk 3 above)
Comment (minestarks) [inline tests/cases/fourslash/unusedImports13FS.ts]: It's the 13th in a series of files that have that exact naming convention.... I think FS stands for fourslash.

File: src/harness/fourslash.ts (hunk 2 above)
Comment (aozgaa) [inline src/harness/fourslash.ts]: If the caret is in the middle of some range that is deleted, should the caret go to the beginning of the range? Or be invalidated?

I'm unsure this can happen in a real editing scenario, but it can make sense for sequencing checks in tests.

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 6]
```diff
@@ -100,7 +98,7 @@ namespace ts.codefix {
                     // or "'import {a, b as ns} from './file'"
```
Comment (aozgaa) [inline src/services/codefixes/fixUnusedIdentifier.ts]: Can you change this to use the `|` delimiters like the other comments in this file?

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 7]
```diff
@@ -118,25 +116,34 @@ namespace ts.codefix {
...
             }
 
+            function deleteNamedImportBinding(namedBindings: NamedImportBindings): CodeAction[] | undefined {
+                if ((<ImportClause>namedBindings.parent).name) {
+                    // Delete named imports while preserving the default import
+                    // import d|, * as ns| from './file'
+                    // import d|, { a }| from './file'
+                    const previousToken = getTokenAtPosition(sourceFile, namedBindings.pos - 1, /*includeJsDocComment*/ false);
+                    if (previousToken && previousToken.kind === SyntaxKind.CommaToken) {
+                        const startPosition = textChanges.getAdjustedStartPosition(sourceFile, previousToken, {}, textChanges.Position.FullStart);
```
Comment (aozgaa) [inline src/services/codefixes/fixUnusedIdentifier.ts]: this doesn't appear to be called anywhere outside of `textChanges.ts`. Can you explain why it is used here/what happens if it we just use `previousToken.getStart(sourceFile)`?

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 5 above)
Comment (aozgaa) [inline src/services/codefixes/fixUnusedIdentifier.ts]: Using `Position.Start` instead of `Position.FullStart` on the comma token should change the behavior to agree with @amcasey's thoughts on the last case while preserving the other cases.

Please add a fourslash test documenting this behavior.

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 4 above)
Comment (aozgaa) [inline src/services/codefixes/fixUnusedIdentifier.ts]: I wasn't aware we would return `[undefined]` in any cases before. Regardless of whether or not the VS extension throws an exception when that happens today (I'd be mildly surprised if it didn't), we definitely should not return an arrays with null values.

We should standardize and agree to only return undefined, even though `ts.codefix.getFixes` doesn't care.

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 8]
```diff
@@ -118,25 +116,34 @@ namespace ts.codefix {
                         }
 
                     case SyntaxKind.NamespaceImport:
-                        const namespaceImport = <NamespaceImport>parent;
-                        if (namespaceImport.name === identifier && !(<ImportClause>namespaceImport.parent).name) {
```
Comment (aozgaa) [inline src/services/codefixes/fixUnusedIdentifier.ts]: It looks like the first check was removed. Why?

File: src/harness/fourslash.ts (hunk 1 above)
Comment (aozgaa) [inline src/harness/fourslash.ts]: This is great!

maybe `...but actually got ${actions ? actions.length : 0} actions, namely\n${...`?

Also, would splitting with a newline be more readable?

File: src/harness/fourslash.ts (hunk 2 above)
Comment (minestarks) [inline src/harness/fourslash.ts]: > If the caret is in the middle of some range that is deleted, should the caret go to the beginning of the range?

@aozgaa yes. This was also the conclusion we arrived with @amcasey after discussing offline. Will make that change.
Perfectly valid scenario - this happens in remove unused quickfix, for instance (which is I guess why I was hitting the invalid caret situation)

File: src/harness/fourslash.ts (hunk 1 above)
Comment (minestarks) [inline src/harness/fourslash.ts]: Okay, since I got two comments on this, I'll rearrange this into a better string

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 7 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: Good question. It's just carried over from the method I was refactoring, so I'm not sure why it was used specifically. I'll investigate.

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 8 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: I believed ```namespaceImport.name !== identifier``` is an unreachable condition. So it seemed like an arbitrary extra check. If we have an identifier whose parent is a ```NamespaceImport```, then by definition ```namespaceImport.name``` has to be that identifier. Is that not right?

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 5 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: Great, agreed on the desired behavior - I just wasn't sure how to achieve it. Thanks.

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 6 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: actually this comment is wrong. I'm removing it. The correct cases are already articulated in inline comments just below.

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 7 above)
Comment (minestarks) [inline src/services/codefixes/fixUnusedIdentifier.ts]: OK actually ```previousToken.getStart()``` is the one to use here, to avoid the comment problem called out below. Using fullStart would wipe out comments leading up to the comma.

File: src/harness/fourslash.ts [hunk 9]
```diff
@@ -1790,17 +1790,20 @@ namespace FourSlash {
...
                 const editDelta = edit.newText.length - edit.span.length;
                 if (offsetStart <= this.currentCaretPosition) {
-                    this.currentCaretPosition += editDelta;
+                    if (offsetEnd <= this.currentCaretPosition) {
+                        // The entirety of the edit span falls before the caret position, shift the caret accordingly
+                        this.currentCaretPosition += editDelta;
+                    }
+                    else {
+                        // The span being replaced includes the caret position, place the caret at the beginning of the span
+                        this.currentCaretPosition = offsetStart;
```
Comment (amcasey) [inline src/harness/fourslash.ts]: Would it make sense to put the caret at the end of the new text?  It should have the same behavior as this code when the new text is empty.

File: src/harness/fourslash.ts [hunk 10]
```diff
@@ -2352,7 +2355,7 @@ namespace FourSlash {
         private applyCodeActions(actions: ts.CodeAction[], index?: number): void {
             if (index === undefined) {
                 if (!(actions && actions.length === 1)) {
-                    this.raiseError(`Should find exactly one codefix, but ${actions ? actions.length : "none"} found. ${actions ? actions.map(a => `"${a.description}"`).join(", ") : "" }`);
+                    this.raiseError(`Should find exactly one codefix, but ${actions ? actions.length : "none"} found. ${actions ? actions.map(a => `\r\n "${a.description}"`) : "" }`);
```
Comment (amcasey) [inline src/harness/fourslash.ts]: Is there a helper for retrieving the platform-specific newline?  (i.e. does this work on Linux?)

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 11]
```diff
@@ -25,15 +25,15 @@ namespace ts.codefix {
                     return [deleteNode(token.parent)];
 
                 default:
-                    return [deleteDefault()];
+                    return deleteDefault();
```
Comment (amcasey) [inline src/services/codefixes/fixUnusedIdentifier.ts]: Thanks for fixing this!

File: tests/cases/fourslash/unusedImports14FS.ts [hunk 12]
```diff
@@ -0,0 +1,12 @@
+/// <reference path='fourslash.ts' />
+
+// @noUnusedLocals: true
+// @Filename: file2.ts
+//// [| import /* 1 */ A /* 2 */, /* 3 */ { x } from './a'; |]
```
Comment (amcasey) [inline tests/cases/fourslash/unusedImports14FS.ts]: `{ /* 4 */ x /* 5 */ } /* 6 */`?

File: src/harness/fourslash.ts (hunk 9 above)
Comment (minestarks) [inline src/harness/fourslash.ts]: In practice, the test cases only hit this when the caret is already at the start of the span (i.e. ```this.currentCaretPosition === offsetStart``` already). So it makes sense not to move it in that case. When the caret is in the middle, it's kind of arbitrary which way to go. I chose the route with the least logic. (Note: I checked VS it does something different altogether. When the caret is in the middle, it only repositions the caret if it would end up outside the range of the new text. Which makes sense. But we literally never hit this case in tests, so I'm not going to spend any more time on it).

File: src/harness/fourslash.ts (hunk 10 above)
Comment (minestarks) [inline src/harness/fourslash.ts]: Ah right.

File: tests/cases/fourslash/unusedImports14FS.ts (hunk 12 above)
Comment (minestarks) [inline tests/cases/fourslash/unusedImports14FS.ts]: Ha, I guess I got tired of typing out comments. I didn't think it was interesting to test since we're removing the ```{ x }``` node altogether.  But might as well.

Comment (minestarks) [inline tests/cases/fourslash/unusedImports14FS.ts]: The other thing is, I can't decide if that ```/* 6 */``` should stay or go. I think either way is fine, so I don't want to necessarily codify the existing behavior in tests.

Comment (amcasey) [inline tests/cases/fourslash/unusedImports14FS.ts]: My preference, in such cases, is to capture the current behavior but add a comment in the test (which will fail if it changes) explaining that the test is descriptive, rather than normative (i.e. the failure can be addressed by updating the baseline).

**Comment by minestarks** [comment]
@aozgaa do I have your approval?

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 8 above)
Comment (aozgaa) [inline src/services/codefixes/fixUnusedIdentifier.ts]: Yes, according to `types.ts`, it is a redundant check
