### PR TITLE
Fix unicode escapes in jsx identifiers and extended unicode characters in jsdoc

### LINKED ISSUE #32701: Insonsistent parsing of JsxIdentifier
**TypeScript Version:**  3.6.0-dev.20190804

**Search Terms:**

**Code**

```tsx
let a = <\u0061></a>; // works
let ab = <\u0061-b></a-b>; // works
let ac = <a-\u0063></a-c>; // reports mismatching closing tag
```

**Expected behavior:**

Consistent parsing of escaped characters in JSX Identifiers.
I don't know the JSX spec, so I cannot tell whether all should be valid or all should be invalid

**Actual behavior:**

`parseJsxIdentifier` is only responsible for everything after the first dash. It wasn't changed to support unicode characters. Therefore the regular Identifier parsing allows escaped characters in the first part.

**Related Issues:**

#32096 forgot to change `parseJsxIdentifier`. cc @weswigham

### PR DESCRIPTION
**Pull request by weswigham**
Which are the two _other_ places we used `isIdentifierStart` in the scanner.

Fixes #32701

### CODE REVIEW

File: src/compiler/scanner.ts [hunk 1]
```diff
@@ -2117,8 +2122,9 @@ namespace ts {
             }
 
             if (isIdentifierStart(ch, ScriptTarget.Latest)) {
-                while (isIdentifierPart(text.charCodeAt(pos), ScriptTarget.Latest) && pos < end) {
-                    pos++;
+                let nextChar: number;
+                while (isIdentifierPart(nextChar = codePointAt(text, pos), ScriptTarget.Latest) && pos < end) {
```
Comment (ajafff) [inline src/compiler/scanner.ts]: is it intentional not to allow unicode escape sequences in JSDoc identifiers?

Comment (weswigham) [reply src/compiler/scanner.ts]: I believe so, but I dunno. Given that it's a comment, it just means that we'll interpret the `\u0061`  verbatim. @sandersn would be the authority here.

File: src/compiler/scanner.ts [hunk 2]
```diff
@@ -2117,8 +2122,9 @@ namespace ts {
             }
 
             if (isIdentifierStart(ch, ScriptTarget.Latest)) {
-                while (isIdentifierPart(text.charCodeAt(pos), ScriptTarget.Latest) && pos < end) {
-                    pos++;
+                let nextChar: number;
+                while (isIdentifierPart(nextChar = codePointAt(text, pos), ScriptTarget.Latest) && pos < end) {
+                    pos += charSize(nextChar);
```
Comment (sandersn) [inline src/compiler/scanner.ts]: stupid question: why isn't `charSize(c) === 2 when c >= 0x10000` instead of `c > 0x10000`?

File: src/compiler/scanner.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/scanner.ts]: I'm confused. Doesn't this change cause us to allow escape sequences in JSDoc identifiers?

jsdoc.app doesn't mention unicode as far as google can tell, so we are free to do whatever we want. I vote that JSDoc identifiers work the same as normal ones, which should mean allowing unicode escape sequences.

**Comment by weswigham** [comment]
> he tests make it seems like unicode identifiers (and escapes?) now work, but his question implies that it doesn't.

Unicode characters now scan as identifiers in jsdoc, escapes are still not parsed.

**Comment by weswigham** [comment]
> Doesn't this change cause us to allow escape sequences in JSDoc identifiers?

No.

**Comment by sandersn** [comment]
That makes sense. It would be nice to have JSDoc support escapes as well, but I think the right way to do that is to make JSDoc use the normal scanner. That's a complete rewrite of the low-level parsing code too, so I'm not sure it's worth it to us.

**Comment by weswigham** [comment]
@sandersn Oh, too late. I already pushed a commit that adds unicode escape support into jsdoc.

**Comment by orta** [comment]
I'm pretty sure this deprecates https://github.com/microsoft/TypeScript/pull/32631 - can someone double check me?

**Comment by weswigham** [comment]
I don't think so - is jsdoc, at least, we're still going to stop parsing before the hyphen.

**Comment by HiEv** [comment]
> I don't think so - is jsdoc, at least, we're still going to stop parsing before the hyphen.

I'm a bit confused by this reply.  In JSDoc you shouldn't stop parsing at the hyphen if there's no space.
`
/**
 * @typedef {object} node
 * @property {string} aria-activedescendant - Description.
 */
/** @type {node} */
var node;
`
If you hover the mouse over the "node" on the "@typedef" line, it _should_ show:
`
type node = {
	aria-activedescendant: string;
}
`
However, instead you get:
`
type node = {
	aria: string;
}
`
with the "-activedescendant" part missing.

If you put quotes around "aria-activedescendant", then you get this instead:
`
type node = {
	(Missing): string;
}
`
The [JSDoc documentation](https://jsdoc.app/about-namepaths.html) says that it should be able to handle dashes in its member names.

#32631 was supposed to fix that problem.
