### PR TITLE
Fix #8795: make properties defined in optional constructor parameters optional

### LINKED ISSUE #8795: `public` constructor sugar allows promoting field type to optional in subclass
**TypeScript Version:** 
 nightly (1.9.0-dev.20160217)

**Code**

```ts
export class A {
  s: string;
}

export class B extends A {
  constructor(public s?: string) {
    super();
  }
}
```

**Expected behavior:**
My understanding is that `constructor(public s?: string)` is interpreted to mean the field is optional, i.e. desugars to:

```ts
  s?: string;
  constructor(s?: string) {
    this.s = s;
  }
```

Since subclasses can only override fields with subtypes and `string  | undefined` is a *supertype* of `string`, this should be an error.

**Actual behavior:** 
The code is accepted. Moreover the produced d.ts file is the following:
```ts
declare class A {
    s: string;
}
declare class B extends A {
    s?: string;
    constructor(s?: string);
}
```
which itself is rejected in further compilations with `t.d.ts(4,15): error TS2415: Class 'B' incorrectly extends base class 'A'.`

### PR DESCRIPTION
**Pull request by mhegazy**
Fixes #8795

### CODE REVIEW

**Comment by ahejlsberg** [comment]
:+1:

File: tests/baselines/reference/propertyParameterWithQuestionMark.js [hunk 1]
```diff
@@ -3,11 +3,11 @@ class C {
...
 
-// x should not be an optional property
-var v: C = {}; // Should fail
+// x should be an optional property
+var v: C = {}; // Should succeed
 var v2: { x? }
-v = v2; // Should fail
-var v3: { x } = new C; // Should succeed
+v = v2; // Should succeed
+var v3: { x } = new C; // Should fail
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/propertyParameterWithQuestionMark.js]: Every time these comments need to be updated, I wonder if they ever should have been there to begin with. You have already have the error messages.
