### PR TITLE
Fix javascript signature instantiation

### LINKED ISSUE #18254: Debug Failure. False expression.
**TypeScript Version:**  2.6.0-dev.20170904

Trace:
```
/usr/local/lib/node_modules/typescript/lib/tsc.js:56399
                throw e;
                ^

Error: Debug Failure. False expression.
    at createTypeMapper (/usr/local/lib/node_modules/typescript/lib/tsc.js:24927:22)
    at checkTypeArguments (/usr/local/lib/node_modules/typescript/lib/tsc.js:30509:38)
    at resolveCall (/usr/local/lib/node_modules/typescript/lib/tsc.js:30794:17)
    at resolveCallExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:30962:20)
    at resolveSignature (/usr/local/lib/node_modules/typescript/lib/tsc.js:31138:28)
    at getResolvedSignature (/usr/local/lib/node_modules/typescript/lib/tsc.js:31158:26)
    at checkCallExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:31201:29)
    at checkExpressionWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:32490:28)
    at checkExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:32430:42)
    at checkExpressionCached (/usr/local/lib/node_modules/typescript/lib/tsc.js:32346:38)
    at getTypeOfExpression (/usr/local/lib/node_modules/typescript/lib/tsc.js:32415:28)
    at checkDeclarationInitializer (/usr/local/lib/node_modules/typescript/lib/tsc.js:32356:24)
    at getTypeForVariableLikeDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:21839:28)
    at getWidenedTypeForVariableLikeDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:21954:24)
    at getTypeOfVariableOrParameterOrProperty (/usr/local/lib/node_modules/typescript/lib/tsc.js:22002:28)
    at checkVariableLikeDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:34111:41)
    at checkVariableDeclaration (/usr/local/lib/node_modules/typescript/lib/tsc.js:34161:20)
    at checkSourceElement (/usr/local/lib/node_modules/typescript/lib/tsc.js:35739:28)
    at Object.forEach (/usr/local/lib/node_modules/typescript/lib/tsc.js:275:30)
    at checkVariableStatement (/usr/local/lib/node_modules/typescript/lib/tsc.js:34169:16)
    at checkSourceElement (/usr/local/lib/node_modules/typescript/lib/tsc.js:35708:28)
    at Object.forEach (/usr/local/lib/node_modules/typescript/lib/tsc.js:275:30)
    at checkSourceFileWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:35812:20)
    at checkSourceFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:35797:13)
    at getDiagnosticsWorker (/usr/local/lib/node_modules/typescript/lib/tsc.js:35850:17)
    at Object.getDiagnostics (/usr/local/lib/node_modules/typescript/lib/tsc.js:35839:24)
    at /usr/local/lib/node_modules/typescript/lib/tsc.js:56414:85
    at runWithCancellationToken (/usr/local/lib/node_modules/typescript/lib/tsc.js:56392:24)
    at getSemanticDiagnosticsForFileNoCache (/usr/local/lib/node_modules/typescript/lib/tsc.js:56406:20)
    at getAndCacheDiagnostics (/usr/local/lib/node_modules/typescript/lib/tsc.js:56614:26)
    at getSemanticDiagnosticsForFile (/usr/local/lib/node_modules/typescript/lib/tsc.js:56403:20)
    at /usr/local/lib/node_modules/typescript/lib/tsc.js:56360:24
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsc.js:507:25)
    at getDiagnosticsHelper (/usr/local/lib/node_modules/typescript/lib/tsc.js:56356:56)
    at Object.getSemanticDiagnostics (/usr/local/lib/node_modules/typescript/lib/tsc.js:56367:20)
    at compileProgram (/usr/local/lib/node_modules/typescript/lib/tsc.js:59366:43)
    at compile (/usr/local/lib/node_modules/typescript/lib/tsc.js:59323:26)
    at performCompilation (/usr/local/lib/node_modules/typescript/lib/tsc.js:59212:33)
    at Object.executeCommandLine (/usr/local/lib/node_modules/typescript/lib/tsc.js:59155:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsc.js:59513:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #18254

`getSignatureInstantation` takes a parameter that tells whether the signature comes from Javascript and therefore is allowed to pass fewer than the required number of type arguments. (Defaults are chosen if this is the case.)

Previously, `getInstantiatedConstructorsForTypeArguments` forgot to provide this argument, and constructors with insufficient type arguments would cause a crash because `getSignatureInstantiation` would not know to fill in the missing type arguments.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6361,11 +6361,10 @@ namespace ts {
          * @param typeParameters The requested type parameters.
          * @param minTypeArgumentCount The minimum number of required type arguments.
          */
-        function fillMissingTypeArguments(typeArguments: Type[] | undefined, typeParameters: TypeParameter[] | undefined, minTypeArgumentCount: number, location?: Node) {
+        function fillMissingTypeArguments(typeArguments: Type[] | undefined, typeParameters: TypeParameter[] | undefined, minTypeArgumentCount: number, isJavaScript?: boolean) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Probably better to just make `isJavascript` required (same for other one)

Comment (sandersn) [reply src/compiler/checker.ts]: I agree that required parameters are generally better; I'm not convinced that they're an improvement for `fillMissingTypeArguments`. There are 7 calls, 2 of which are so deep in instantiation that they have to call `isInJavascriptFile` on a node that may or may not be relevant. One of the 6 calls to `getSignatureInstantiation` is like this too.

I pushed the change so we can look at it and decide if it's worthwhile.
