### PR TITLE
Fix #20873: Enforce strictNullChecks for RHS of empty destructuring assignment

### LINKED ISSUE #20873: strictNullChecks doesn't work with empty destructuring assignment
**TypeScript Version:**  2.7.0-dev.20171223

**Code**

```ts
const [] = null;
```

**Expected behavior:**

error

**Actual behavior:**

pass

### PR DESCRIPTION
**Pull request by jack-williams**
When strictNullChecks is on, check the RHS of the following destructuring assignments for possible null or undefined:

const {} = ...
const [] = ...
let {} = ...
let [] = ...
({} = ...)

Fixes #20873

### CODE REVIEW

**Comment by mhegazy** [comment]
@sandersn can you please review this change.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21833,7 +21836,11 @@ namespace ts {
             if (isBindingPattern(node.name)) {
                 // Don't validate for-in initializer as it is already an error
                 if (node.initializer && node.parent.parent.kind !== SyntaxKind.ForInStatement) {
-                    checkTypeAssignableTo(checkExpressionCached(node.initializer), getWidenedTypeForVariableLikeDeclaration(node), node, /*headMessage*/ undefined);
+                    let initializerType = checkExpressionCached(node.initializer);
+                    if (strictNullChecks && node.name.elements.length === 0) {
+                        initializerType = checkNonNullType(initializerType, node);
+                    }
+                    checkTypeAssignableTo(initializerType, getWidenedTypeForVariableLikeDeclaration(node), node, /*headMessage*/ undefined);
```
Comment (sandersn) [inline src/compiler/checker.ts]: Is checkTypeAssignableTo needed if there aren't any elements? Seems like it could in an `else`, and then `initializerType` wouldn't need to be updated in the `if` block.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -18908,6 +18908,9 @@ namespace ts {
                 target = (<BinaryExpression>target).left;
             }
             if (target.kind === SyntaxKind.ObjectLiteralExpression) {
+                if (strictNullChecks && (<ObjectLiteralExpression>target).properties.length === 0) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: I would move this code into `checkObjectLiteralAssignment`.

File: src/compiler/checker.ts (hunk 1 above)
Comment (jack-williams) [reply src/compiler/checker.ts]: Good point. I did consider whether it would be possible to just return (or use an else) immediately after the null check. I was just unsure if `checkTypeAssignableTo` performs some side-effects (like caching in `checkTypeRelatedTo`) that might give different results if skipped.

Making that change doesn't break any tests so from what I can tell I think this would be ok. I'm still learning the details of the internals so I may be missing something.

Comment (sandersn) [reply src/compiler/checker.ts]: You're right, the cache might be filled earlier this way, but there's no point in doing work that isn't needed.

You can't return because the code still needs to `checkParameterInitalizer`, although maybe that's redundant with the new call to `checkExpressionCached`.

Comment (jack-williams) [reply src/compiler/checker.ts]: I don't think `checkParameterInitalizer` gets called via `checkExpressionCached`, so unless it does some equivalent work, I need to move the call after the if-then-else, rather than in the else branch. My most recent commit got this wrong - will fix now.

File: src/compiler/checker.ts (hunk 2 above)
Comment (jack-williams) [reply src/compiler/checker.ts]: Done!

**Comment by jack-williams** [comment]
Just pinging @sandersn to say that I've addressed the suggested changes (I hope). I appreciate this is low priority so just look over it when you can (I just wanted to indicate that I hadn't forgotten about the PR).

Is there a workflow for marking review comments as addressed/resolved?

**Comment by sandersn** [comment]
Thanks for the ping. I missed the new commits. We don't have an established workflow for marking comment state. I sometimes reply "done" but I think we are basically waiting for github to add that feature.

Anyway, thanks for the change. Looks good!

**Comment by jack-williams** [comment]
No problem! Thanks for reviewing it
