### PR TITLE
Report a semantic error for an arrow function with a "this" parameter.

### LINKED ISSUE #9744: This type parsing error and incorrect type inference
**TypeScript Version:**  2.0.0 (I suppose beta, though tsc -v just reports 2.0.0)

**Code**

``` ts
function test(e: HTMLElement): void {
    e.onclick = (this: HTMLElement, event) => { }; // error TS1005: ')' expected.
                                                   // error TS1005: ';' expected.
                                                   // error TS1128: Declaration or statement expected.

    e.onclick = function(this: HTMLElement, event) { }; // error TS7006: Parameter 'event' implicitly has an 'any' type
}
```

**Expected behavior:**
1st: no parsing error.
2nd: event: MouseEvent inference, as for `e.onclick = function(event) { };`

**Actual behavior:**

### PR DESCRIPTION
**Pull request by mattmccutchen**
Fixes #9744.

### CODE REVIEW

File: tests/baselines/reference/thisTypeInFunctionsNegative.js [hunk 1]
```diff
@@ -174,9 +176,13 @@ function initializer(this: C = new C()): number { return this.n; }
 
 // can't name parameters 'this' in a lambda.
 c.explicitProperty = (this, m) => m + this.n;
+const f2 = <T>(this: {n: number}, m: number) => m + this.n;
+const f3 = async (this: {n: number}, m: number) => m + this.n;
+const f4 = async <T>(this: {n: number}, m: number) => m + this.n;
 
 
 //// [thisTypeInFunctionsNegative.js]
+// @target es6
```
Comment (ajafff) [inline tests/baselines/reference/thisTypeInFunctionsNegative.js]: This seems to have no effect. Otherwise the `__extends` helper wouldn't be emitted.

Comment (mattmccutchen) [reply tests/baselines/reference/thisTypeInFunctionsNegative.js]: Good catch.  I assumed this was working because I didn't get an error about Promise not being defined, but there may be a different reason that error doesn't occur in the context of the test suite.  It looks like I messed up the syntax.  Fixed.
