### PR TITLE
convertToAsyncFunction: Disable for `.then` with both fulfillment and rejection handlers

### LINKED ISSUE #37833: Auto-import failure: Cannot read property 'length' of undefined
tsconfig.json
```json
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
    }
}
```
test.js
```js
class Abcde {
    x
}

module.exports = {
    Abcde
};
```
index.ts
```ts
export var foo = 1
declare module "./test" {
    interface Abcde { b: string }
}

Abcde// Invoke completion here to trigger auto-import
```

Expected: `Abcde` is imported from `test`.
Actual:
```
Exception has occurred: TypeError
TypeError: Cannot read property 'length' of undefined
    at getLocalTypeParametersOfClassOrInterfaceOrTypeAlias (e:\ts_gh\src\compiler\checker.ts:8292:32)
    at typeParametersToTypeParameterDeclarations (e:\ts_gh\src\compiler\checker.ts:5002:62)
    at e:\ts_gh\src\compiler\checker.ts:4098:82
    at withContext (e:\ts_gh\src\compiler\checker.ts:4130:39)
    at Object.symbolToTypeParameterDeclarations (e:\ts_gh\src\compiler\checker.ts:4098:21)
    at e:\ts_gh\src\services\symbolDisplay.ts:634:44
    at Object.mapToDisplayParts (e:\ts_gh\src\services\utilities.ts:2091:13)
    at writeTypeParametersOfSymbol (e:\ts_gh\src\services\symbolDisplay.ts:633:40)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (e:\ts_gh\src\services\symbolDisplay.ts:289:13)
    at E:\ts_gh\built\local\tsserver.js:111800:41
    at Object.runWithCancellationToken (e:\ts_gh\src\compiler\checker.ts:662:28)
    at createCompletionDetailsForSymbol (e:\ts_gh\src\services\completions.ts:678:15)
    at Object.getCompletionEntryDetails (e:\ts_gh\src\services\completions.ts:659:24)
    at Proxy.getCompletionEntryDetails (e:\ts_gh\src\services\services.ts:1476:32)
    at e:\ts_gh\src\server\session.ts:1683:53
    at Object.mapDefined (e:\ts_gh\src\compiler\core.ts:475:32)
    at IOSession.Session.getCompletionEntryDetails (e:\ts_gh\src\server\session.ts:1681:28)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (e:\ts_gh\src\server\session.ts:2455:51)
    at e:\ts_gh\src\server\session.ts:2665:69
    at IOSession.Session.executeWithRequestId (e:\ts_gh\src\server\session.ts:2655:25)
    at IOSession.Session.executeCommand (e:\ts_gh\src\server\session.ts:2665:29)
    at IOSession.Session.onMessage (e:\ts_gh\src\server\session.ts:2694:23)
    at Interface.<anonymous> (e:\ts_gh\src\tsserver\server.ts:577:22)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

TS version: c47aca0da321663415b7fc2ed000f66c4d7bcb5d

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37833 

After talking with @amcasey about #37588, I am convinced that the output code for two-argument then (where neither argument is null/undefined) is too often unconventional and possibly wrong.

### CODE REVIEW

File: src/services/suggestionDiagnostics.ts [hunk 1]
```diff
@@ -156,7 +156,29 @@ namespace ts {
...
+            hasPropertyAccessExpressionWithName(node, "catch"));
+    }
+
+    function hasZeroOrOneNonNullArguments(node: CallExpression) {
+        if (node.arguments.length < 2) return true;
+        let seenArg = false;
+        for (const arg of node.arguments) {
+            switch (arg.kind) {
+                case SyntaxKind.NullKeyword:
+                    continue;
```
Comment (uniqueiniquity) [inline src/services/suggestionDiagnostics.ts:170]: Why can't you just break the loop at this point? Is there a three argument version?

File: src/services/suggestionDiagnostics.ts [hunk 2]
```diff
@@ -156,7 +156,29 @@ namespace ts {
...
+                case SyntaxKind.Identifier:
+                    if ((arg as Identifier).escapedText === "undefined") {
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts:172]: In Roslyn, we had the option asking for the constant value of an expression.  I don't know if that's possible in TS, but it would be more accurate (e.g. `const noCatch = undefined`).

File: src/services/suggestionDiagnostics.ts [hunk 3]
```diff
@@ -156,7 +156,29 @@ namespace ts {
     }
 
     function isPromiseHandler(node: Node): node is CallExpression {
-        return isCallExpression(node) && (hasPropertyAccessExpressionWithName(node, "then") || hasPropertyAccessExpressionWithName(node, "catch"));
+        return isCallExpression(node) && (
+            hasPropertyAccessExpressionWithName(node, "then") && hasZeroOrOneNonNullArguments(node) ||
+            hasPropertyAccessExpressionWithName(node, "catch"));
+    }
+
+    function hasZeroOrOneNonNullArguments(node: CallExpression) {
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts:164]: I'm going to quibble with the name because it appears to return true for `then(null)`.  Maybe "secondArgumentIsNullOrAbsent"?

Also, it's not clear to me what having more than two arguments does - can I call `then(handler, undefined, undefined)`?  Are the extras just ignored?  What if the third argument is non-null?

File: src/services/suggestionDiagnostics.ts [hunk 4]
```diff
@@ -156,7 +156,29 @@ namespace ts {
...
     function isPromiseHandler(node: Node): node is CallExpression {
-        return isCallExpression(node) && (hasPropertyAccessExpressionWithName(node, "then") || hasPropertyAccessExpressionWithName(node, "catch"));
+        return isCallExpression(node) && (
+            hasPropertyAccessExpressionWithName(node, "then") && hasZeroOrOneNonNullArguments(node) ||
+            hasPropertyAccessExpressionWithName(node, "catch"));
+    }
+
+    function hasZeroOrOneNonNullArguments(node: CallExpression) {
+        if (node.arguments.length < 2) return true;
+        let seenArg = false;
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts:166]: Is the flag because we want to support `then(undefined, handler)`?

File: src/services/suggestionDiagnostics.ts [hunk 5]
```diff
@@ -156,7 +156,29 @@ namespace ts {
     }
 
     function isPromiseHandler(node: Node): node is CallExpression {
-        return isCallExpression(node) && (hasPropertyAccessExpressionWithName(node, "then") || hasPropertyAccessExpressionWithName(node, "catch"));
+        return isCallExpression(node) && (
+            hasPropertyAccessExpressionWithName(node, "then") && hasZeroOrOneNonNullArguments(node) ||
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts:160]: Unless passing all but one argument as `undefined` is a common pattern, I'd probably just count them and disallow anything other than 1.

File: src/services/suggestionDiagnostics.ts (hunk 1 above)
Comment (amcasey) [reply src/services/suggestionDiagnostics.ts:170]: I had the same question and my guess was `then(undefined, handler)`.

File: src/services/suggestionDiagnostics.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/suggestionDiagnostics.ts:172]: I have a type checker available, but the parent function has never used it. It has always worked purely on syntax, and I don’t see a compelling reason to break from that here. (FWIW I don’t think we have anything built in to say “get me the type of this if it’s easy.” If it’s an identifier, I can call `checker.resolveName` on it to get the referenced symbol, but 99% of the time it’s going to be a function or variable declaration. If it’s a variable declaration, then you need even more semantic work to get the type of the variable.)

File: src/services/suggestionDiagnostics.ts (hunk 3 above)
Comment (andrewbranch) [reply src/services/suggestionDiagnostics.ts:164]: > I'm going to quibble with the name because it appears to return true for `then(null)`.

In `then(null)`, there are zero non-null arguments, so returning true is consistent with the name.

Arguments after the second have always been totally ignored (read: removed) by the refactor, but I’m guessing that was more accidental than intentional. It seems reasonable to disable the refactor to prevent code loss.

File: src/services/suggestionDiagnostics.ts (hunk 5 above)
Comment (andrewbranch) [reply src/services/suggestionDiagnostics.ts:160]: There are existing tests that assert the refactor works with `.then(undefined).then(...)`, which is absurd, but easy to keep supporting 🤷‍♂️

File: src/services/suggestionDiagnostics.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/suggestionDiagnostics.ts]: That was in the back of my mind, but it makes more sense to disable the refactor if there are more than two arguments since we can’t understand what that’s supposed to mean.
