### PR TITLE
fix(41295): Passing deprecated function as callback does not give deprecation suggestion

### LINKED ISSUE #41295: Passing deprecated function as callback does not give deprecation suggestion
**TypeScript Version:**  4.1.0-dev.20201027

**Search Terms:** Deprecated tag, callback

**Code**

```ts
/**
 * @deprecated
 */
function foo () {}

/**
 * Expected: Deprecation warning
 * Actual: Deprecation warning
 */
foo;

function bar (x : () => void) {
    x();
}


/**
 * Expected: Deprecation warning
 * Actual: No deprecation warning (?)
 */
bar(foo);

/**
 * @deprecated - Not random enough
 */
const x = 4;

/**
 * Expected: Deprecation warning
 * Actual: Deprecation warning
 */
x;

function baz (x : number) {

}

/**
 * Expected: Deprecation warning
 * Actual: Deprecation warning
 */
baz(x);
```

**Expected behavior:**

`bar(foo);` should trigger deprecation suggestion

**Actual behavior:**

`bar(foo);` does not have suggestion

**Playground Link:** [Playground](https://www.typescriptlang.org/play?ts=4.1.0-dev.20201027#code/PQKhCgAIUgBATApgBwE6IMYEMAuj5QjDgBmArgHYY4CWA9hZCXXZABQCUkA3gL7jhQEaJACiAD2SY88AFyQAIinTZaDSAHcsqCjQoBzQpACC1MlgA28pWky56jLTr2HoxZnQDcA8lTWMAI212cUh5TkgAXgA+SAA3Ohp4Lm4oSHTxTm9+ASEjCSlqfGtlO39NbV0DI1MccytIADlWJFtVBwrnA3YAfg5CYiDUNg8Ob0EwIwRS1XxIAFomuhxIVCwKeDoAW0hECjoyfQALAfAMBgBnFdDIyAAWcbyRAulixRn7dScq1xha+pKbU+jkqLlO4nGvmoHSCAC8QmFIBQyFsAohUCkBDknjAXkU5O8geVvmCRP9LICVMDOj9TnC2OIxkA)

**Related Issues:** None

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41295

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22804,7 +22809,7 @@ namespace ts {
 
             const localOrExportSymbol = getExportSymbolOfValueSymbolIfExported(symbol);
             const sourceSymbol = localOrExportSymbol.flags & SymbolFlags.Alias ? resolveAlias(localOrExportSymbol) : localOrExportSymbol;
-            if (getDeclarationNodeFlagsFromSymbol(sourceSymbol) & NodeFlags.Deprecated && isUncalledFunctionReference(node.parent, sourceSymbol)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:22807]: don't you need to update the other callers of `isUncalledFunctionReference` too?

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks good except for one question

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:22807]: Other callers of `isUncalledFunctionReference` don't use parent and use the _original node_, only in `checkIdentifier` uses `node.parent`.

**Review by sandersn — APPROVED** [review]
