### PR TITLE
Do not rely on ElementAttributeProperty if it is not present

### LINKED ISSUE #22874: typeArgument of JsxOpeningLikeElement ignored while checking JsxAttributes
**TypeScript Version:**  2.9.0-dev.20180328

**Search Terms:** jsx generic type arguments

**Code**

```ts
export {};

declare namespace JSX {
    interface Element {
        render(): Element | string | false;
    }
}

function SFC<T>(props: Record<string, T>) {
    return '';
}

/*1*/<SFC<string> prop={1}></SFC>;
```

**Expected behavior:**

Error on the `prop` attribute, because number is not assignable to string.

**Actual behavior:**

No error. Signature help incorrectly shows `function SFC<number>(props: Record<string, number>): string`

**Playground Link:**  

**Related Issues:**

#22873

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #22874.

We can now typecheck JSX without it by relying on how the first parameter of an SFC/class is the props type, so we don't need to rely on its presence.

Unfortunately, some definition files (and tests) may be predicated on the constructor parameter not existing and rely on the prop name (which is why we must retain support for the old way), or rely on their types being different. React actually relies on their types being different to hide `children` from users' props type (you can pass `children` through attributes, and `this.props.children` exists, but if you have a constructor and check `props.children`, according to React's types it isn't there (AFAIK at runtime it is)) unless they explicitly specify it in their own props type (they also always intersect children of type `ReactNode` with whatever children your specify, which probably isn't helping). ☹️ The react .d.ts can do better now if this is desirable (eg, using conditionals), but we need to keep supporting old versions.

### CODE REVIEW

**Comment by sandersn** [comment]
Hmm. I think I need to talk to you in person to understand the motivation for this one.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18452,8 +18433,13 @@ namespace ts {
                 pos < signature.parameters.length ? getTypeOfParameter(signature.parameters[pos]) : anyType;
         }
 
+
         function getTypeOfFirstParameterOfSignature(signature: Signature) {
-            return signature.parameters.length > 0 ? getTypeAtPosition(signature, 0) : neverType;
+            return getTypeOfFirstParameterOfSignatureWithFallback(signature, neverType);
+        }
+
+        function getTypeOfFirstParameterOfSignatureWithFallback(signature: Signature, fallackType: Type) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: typo:fallback

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14745,77 +14745,63 @@ namespace ts {
...
 
-            const propsName = getJsxElementPropertiesName(getJsxNamespaceAt(context));
-            if (propsName === undefined) {
-                // There is no type ElementAttributesProperty, return 'any'
-                return anyType;
+        function getJsxPropsTypeFromClassType(sig: Signature, isJs: boolean, context: Node) {
+            const forcedLookupLocation = getJsxElementPropertiesName(getJsxNamespaceAt(context));
+            const attributesType = forcedLookupLocation === undefined 
+                ? getTypeOfFirstParameterOfSignatureWithFallback(sig, emptyObjectType)
+                : forcedLookupLocation === ""
```
Comment (sandersn) [inline src/compiler/checker.ts]: There used to be comments here about when the props property is `=== ""` vs `=== undefined`. They helped me the *second* time I read them, so could you bring them back?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -27528,7 +27514,7 @@ namespace ts {
         export const JSX = "JSX" as __String;
         export const IntrinsicElements = "IntrinsicElements" as __String;
         export const ElementClass = "ElementClass" as __String;
-        export const ElementAttributesPropertyNameContainer = "ElementAttributesProperty" as __String;
+        export const ElementAttributesPropertyNameContainer = "ElementAttributesProperty" as __String; // TODO: Deprecate and remove support
```
Comment (sandersn) [inline src/compiler/checker.ts]: not a fan of checking in TODOs. Maybe it's justified here though.

**Comment by sandersn** [comment]
Also CI caught some lint somewhere :(
