### PR TITLE
fix(53011): Illegal declaration file can be emitted (duplicate parameter names) when spreading tuples into parameter positions

### LINKED ISSUE #53011: Illegal declaration file can be emitted (duplicate parameter names) when spreading tuples into parameter positions
# Bug Report

### 🔎 Search Terms

parameter spread duplicate identifier parameter tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAFASkQbwFCL4qATwAcBTRAQUQF5EBtAZwC5EGoAnGMAcwF0BuXPiJlEAYRr0AdDIoAaRDKkUB2IXnakoIdklCRYCZGBRKAhu27NxGTIgC+2R0A)

### 💻 Code

```ts
function f() {
    // n.b. not illegal
    type C = [s: string, s: string]; 

    return function fn(...args: C) { }
}
```

Less-degenerate form where you can't just not make that mistake:
```ts
function f() {
    type A = [s: string];
    type C = [...A, ...A];

    return function fn(...args: C) { }
}
```

declaration emit in either case becomes
```ts
declare function f(): (s: string, s: string) => void;
```
which we consider a syntax error:
```
error TS2300: Duplicate identifier 's'.

1 declare function f(): (s: string, s: string) => void;
```

### 🙁 Actual behavior

Multiple parameters with the same name get printed

### 🙂 Expected behavior

Probably something like `(s: string, s_0: string) => void` instead

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #53011

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12643,6 +12642,24 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             });
             return concatenate(sig.parameters.slice(0, restIndex), restParams);
         }
+
+        function getUniqAssociatedNamesFromTupleType(type: TupleTypeReference): __String[] {
+            const associatedNamesMap = new Map<__String, number>();
+            const associatedNames: __String[] = [];
+            forEach(type.target.labeledElementDeclarations, (labeledElement, i) => {
```
Comment (jakebailey) [inline src/compiler/checker.ts:12649]: Could this just be a `map` call?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -12643,6 +12643,22 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            return map(type.target.labeledElementDeclarations, labeledElement => {
+                const name = getTupleElementLabel(labeledElement);
+                const prevCounter = associatedNamesMap.get(name);
+                if (prevCounter === undefined) {
+                    associatedNamesMap.set(name, 1);
+                    return name;
+                }
+                else {
+                    associatedNamesMap.set(name, prevCounter + 1);
+                    return `${name}_${prevCounter}` as __String;
```
Comment (jakebailey) [inline src/compiler/checker.ts:12658]: Probably not for this PR, but I feel like I've seen this sort of thing a few times before, e.g. for renaming type variables in emit, other parameter name generation. I wonder if we can deduplicate this.

**Review by jakebailey — APPROVED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/checker.ts:12658]: Hm, also, we do have existing code for this sort of thing, except it starts at 0.

But, type variable renamings start at `1`. Oops. (I feel like starting at 1 is correct, but maybe that's because I was more recently working on the type variable code.)
