### PR TITLE
fix(37781): 'declare method' quick fix adds inline import

### LINKED ISSUE #37781: 'declare method' quick fix adds inline import
From https://github.com/microsoft/vscode/issues/94118

**TypeScript Version:**  3.9.0-dev.20200330

**Search terms**
- quick fix
- declare method
- import

**Repro**
For a project:

`foo.ts`
```ts
export interface Foo {
    abc: number;
}

export function doFoo(callback: (x: Foo) => void) { }
```

`index.ts`
```ts
import { doFoo } from "./foo";

class Bar {
    bar() {
        doFoo(x => this.baz(x))
    }
}
```

1. Trigger the `declare method` quick fix on `baz`

**Expected behavior:**
An import for `Foo` is added to the top of the file:

```ts
import { doFoo, Foo } from "./foo";

class Bar {
    bar() {
        doFoo(x => this.baz(x))
    }
    baz(x: Foo): void {
        throw new Error("Method not implemented.");
    }
}
```

**Actual behavior:**
An inline import is added:

```ts
import { doFoo } from "./foo";

class Bar {
    bar() {
        doFoo(x => this.baz(x))
    }
    baz(x: import("./foo").Foo): void {
        throw new Error("Method not implemented.");
    }
}
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37781

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Related to #29410.

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -218,16 +218,26 @@ namespace ts.codefix {
...
+        const scriptTarget = getEmitScriptTarget(context.program.getCompilerOptions());
         const checker = context.program.getTypeChecker();
         const tracker = getNoopSymbolTrackerWithResolver(context);
-        const types = map(args, arg =>
-            // Widen the type so we don't emit nonsense annotations like "function fn(x: 3) {"
-            checker.typeToTypeNode(checker.getBaseTypeOfLiteralType(checker.getTypeAtLocation(arg)), contextNode, /*flags*/ undefined, tracker));
+        const types = map(args, arg => {
+            const type = checker.getBaseTypeOfLiteralType(checker.getTypeAtLocation(arg));
+            const typeNode = checker.typeToTypeNode(type, contextNode, /*flags*/ undefined, tracker);
+            if (typeNode?.kind === SyntaxKind.ImportType) {
```
Comment (weswigham) [inline src/services/codefixes/helpers.ts:232]: Say you get back `import("a").Cls<import("b").Other>` - shouldn't you visit the type node tree and attempt to autoimport all the import type nodes, rather than just the top-level one?

Comment (a-tarasyuk) [reply src/services/codefixes/helpers.ts:232]: @weswigham Thanks for the feedback 👍. I've added additional tests.
