### PR TITLE
Fix acquiring format options for getEditsForRefactor

### LINKED ISSUE #18328: Extract function doesn't respect indentation settings
_From @dbaeumer on August 30, 2017 8:35_

Testing: #33282 

```ts
function foo() {
	console.log('Hello World');
}
```
- observe: console.log is indented using tabs
- select `console.log('Hello World');`
- run extract function
- you get
```ts
function foo() {
    newFunction();
}
function newFunction() {
    console.log('Hello World');
}
```
Observe: spaces are used as indentation.

_Copied from original issue: Microsoft/vscode#33492_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #18328.
Thanks @sheetalkamat for the help spotting this fix.
Also removed `formatOptions` from `GetEditsForRefactorRequestArgs` since that should be sent only once, not once per refactor. (This was added only recently so should be fine to remove before anyone uses it.)

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Needs test

File: src/harness/unittests/tsserverProjectSystem.ts [hunk 1]
```diff
@@ -4245,4 +4245,66 @@ namespace ts.projectSystem {
             }
         });
     });
+
+    describe("refactors", () => {
+        it("abcdefg", () => {
```
Comment (sheetalkamat) [inline src/harness/unittests/tsserverProjectSystem.ts]: Please describe the text here instead so its easy to figure out when test fails

File: src/harness/unittests/tsserverProjectSystem.ts [hunk 2]
```diff
@@ -4245,4 +4245,66 @@ namespace ts.projectSystem {
...
+                arguments: {
+                    formatOptions: {
+                        indentSize: 2,
+                    },
+                },
+            };
+            const response0 = session.executeCommand(command0).response;
+            assert.deepEqual(response0, /*expected*/ undefined);
+
+            const command: server.protocol.GetEditsForRefactorRequest = {
```
Comment (sheetalkamat) [inline src/harness/unittests/tsserverProjectSystem.ts]: Consider using ```executeCommandSeq``` instead so you don't need to write the type, sequence etc
