### PR TITLE
Fixes to handle file names in module resolution watching and createGetCanonicalFileName

### LINKED ISSUE #31819: createGetCanonicalFileName yields non-existent paths on Windows if the path contains certain unicode letters
**TypeScript Version:**  3.1.2 Grabbed from the file `C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.1\tsserver.js`:

```js
// WARNING: The script `configureNightly.ts` uses a regexp to parse out these values.
// If changing the text in this section, be sure to test `configureNightly` too.
ts.versionMajorMinor = "3.1";
/** The version of the TypeScript compiler release */
ts.version = ts.versionMajorMinor + ".2";
```

But the issue is present in the latest version, too.

**Search Terms:**

* unicode
* unicode path
* turkish

**Code**

I don't know TypeScript yet. Still, I've tried, but I couldn't figure out how the `ts` global variable is used.

The function with the problem is here:

https://github.com/microsoft/TypeScript/blob/94f19c7edd741ea7fe985c57541dcf233677d22b/src/compiler/core.ts#L2093

If we're on Windows, this function returns a function that returns the lowercased version of the parameter given. So `C:/Users/Serhan/Desktop/İ` returns `c:/users/serhan/desktop/i̇`.

**Expected behavior:**

All I can say is that the use of `toLowerCase` is not the expected behavior here. Because these two paths are not the same on Windows.

**Related Issues:** 

* https://developercommunity.visualstudio.com/content/problem/586418/javascript-language-service-has-issues-with-unicod.html (Original issue)
* https://github.com/nodejs/node/issues/27534 (A similar issue)

### PR DESCRIPTION
**Pull request by sheetalkamat**
- Uses directory separators to decide which directory to watch in resolution cache to handle Unicode file names
- Handle lower casing of special characters in file names to ensure that those are not converted to the lower case.
Fixes #31819 and #35559

### CODE REVIEW

File: src/compiler/core.ts [hunk 1]
```diff
@@ -1399,6 +1399,32 @@ namespace ts {
     /** Returns lower case string */
     export function toLowerCase(x: string) { return x.toLowerCase(); }
 
+    const fileNameLowerCaseRegExp = /[^İi̇ıßa-z0-9\\/:\-_\. ]+/g;
+    export function toFileNameLowerCase(x: string) {
```
Comment (weswigham) [inline src/compiler/core.ts]: Can we document why we're unconditionally handling this ourselves and not deferring to `string.toLocaleLowercase`, as we do in `compareStringsCaseSensitiveUI`, where possible (namely what cases that fails to handle)?

File: src/compiler/core.ts [hunk 2]
```diff
@@ -1399,6 +1399,32 @@ namespace ts {
     /** Returns lower case string */
     export function toLowerCase(x: string) { return x.toLowerCase(); }
 
+    const fileNameLowerCaseRegExp = /[^İi̇ıßa-z0-9\\/:\-_\. ]+/g;
```
Comment (weswigham) [inline src/compiler/core.ts]: @DanielRosenwasser may have more opinions here (since he brought it up the last time I tried to add one in a PR), but ostensibly including Unicode characters in our source has the potential to slow down parsing our source (which is very annoying when Unicode characters are appropriate in comments), so it may be appropriate to remove the characters from the comments and use hexadecimal character references in the regex.

Comment (weswigham) [reply src/compiler/core.ts]: Although I note we've probably already blown this in `core.ts`, so it's probably best to enforce via a lint rule if we actually think it's a problem.

@DanielRosenwasser  ?

File: src/compiler/core.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/core.ts]: https://github.com/microsoft/TypeScript/pull/36106/files#diff-66cec844e251a1918deb897eabca206bR1404 is this not good enough ?

Comment (weswigham) [reply src/compiler/core.ts]: It explains what's being done, but not why using locale lower case is insufficient.

File: src/compiler/core.ts [hunk 3]
```diff
@@ -1399,27 +1399,30 @@ namespace ts {
     /** Returns lower case string */
     export function toLowerCase(x: string) { return x.toLowerCase(); }
 
-    const fileNameLowerCaseRegExp = /[^İi̇ıßa-z0-9\\/:\-_\. ]+/g;
+    // We convert the file names to lower case as key for file name on case insensitive file system
+    // While doing so we need to handle special characters (eg \u0130) to ensure that we dont convert
+    // it to lower case, fileName with its lowercase form can exist along side it.
```
Comment (weswigham) [inline src/compiler/core.ts]: Is this windows specific (does this need to live in `sys` and keyed off of `process.os`), or is this also important on mac?

Comment (minestarks) [reply src/compiler/core.ts]: This is a feature of the standard Windows filesystem (NTFS). It's not affected by system locale - the upcase table is hardcoded into the filesystem. In theory, other case-insensitive filesystems could behave differently re: casing. 

I'm a lot less clear on the Mac OS system specifics but I just tried out creating some files on my Macbook, and a similar issue exists - (I,i) , (İ) and (ı) are all distinct filenames even though the filesystem is case insensitive. Note this is slightly different than Windows which treats İ and ı as equivalent.

Comment (weswigham) [reply src/compiler/core.ts]: Is the behavior on Windows different if the active drive is backed by FAT32 instead of NTFS (eg, an old thumb drive)? Or do FAT and NTFS have the same filename case handling in windows?

Comment (minestarks) [reply src/compiler/core.ts]: I'm like 99.99% sure FAT32 behaves exactly the same but I'm speaking from memory.

**Comment by sheetalkamat** [comment]
@weswigham @minestarks is this good to go?

**Comment by weswigham** [comment]
@sheetalkamat 

@minestarks comment [here](https://github.com/microsoft/TypeScript/pull/36106#discussion_r365978912) seems to indicate the osx behavior is different than the windows behavior, so we may need to make the functionality platform-specific.

**Comment by minestarks** [comment]
I didn't code review this, but validated that it fixes the Turkish issues on Windows. Thanks!

File: src/compiler/core.ts (hunk 3 above)
Comment (orta) [reply src/compiler/core.ts]: This is what it looks like on node for Mac:

```sh
❯ node
> "İi̇ı".toLowerCase()
'i̇i̇ı'
> "İi̇ı".toUpperCase()
'İİI'
```

Comment (weswigham) [reply src/compiler/core.ts]: We're interested in filesystem behavior (what's equivalent to what on disk) - `toLowerCase` and `toUpperCase` in the language are specified :P

Comment (sheetalkamat) [reply src/compiler/core.ts]: Thanks orta for looking into that.
I don't think, we should depend on the os to determine how to get canonical file name at all.. Considering `İı` as unique(that is not changing file casing for those) is right thing to do.. In worst cases we wont recognize that file with `İ` and `i̇` are not same which would be really a small group. The `GetCanonicalFileName` is internal compiler thing that currently is based on if file system is case sensitive or not and we shouldn't change that fact. It is an ok trade off to do in my opinion

cc: @RyanCavanaugh  and @DanielRosenwasser to see if they agree.

Comment (sheetalkamat) [reply src/compiler/core.ts]: Also we do not want to use `toUpperCase` since in most cases file name is lowercase so not having to store duplicate strings just for case swapping is more performant

Comment (weswigham) [reply src/compiler/core.ts]: > I don't think, we should depend on the os to determine how to get canonical file name at all

No, I'm not saying query the OS - i'm saying check `process.os` (in `sys.ts`, as that's where we do things like that) to swap between a windows implementation of `toFileNameLowerCase` and a mac implementation of `toFileNameLowerCase`, since their handling of turkish i differs. As-is, this might fix turkish i on windows, but will potentially break it on mac, since our existing `toLowerCase` call _happened_ to already to the right thing for the mac's implementation of case-insensitivity.

Pretty much: we shouldn't break one platform to fix another - we gotta handle both.

Comment (weswigham) [reply src/compiler/core.ts]: The argument is pretty much that our discussion here has made it evident that, as it relates to filesystems, there isn't just `case sensitive` vs `case insensitive` - there's `case sensitive` vs `windows case insensitive` vs `mac case insensitive` (probably vs `linux bespoke filesystem case insensitive` but we care about that way, way less), and while the later two are they same in the ASCII range, they differ in some of the edge cases, as @minestarks pointed out. We should strive to handle them both.

**Comment by RyanCavanaugh** [comment]
@minestarks can you try out this build in Mac and see what happens?

**Comment by minestarks** [comment]
@RyanCavanaugh well, I'm not sure why I mentioned Mac in #35559  but I can't repro the original issue on VSCode+Mac anymore 🤷‍♀  I have no concept of how common this issue is for Mac users nor any insight into the internals of the Mac OS filesystem.

**Comment by sheetalkamat** [comment]
@andrewbranch or @orta can you please run the below js file on mac and let me know the result:

```js
const fs = require("fs");
const fileName = "İ";
try {
    fs.writeFileSync(fileName, "FileContents", "utf8");
}
catch (e) {
    console.log(`Error when writing file: ${fileName}:: ${e}`);
}
readFile(fileName);
readFile(fileName.toLowerCase());


function readFile(fileName) {
    try {
        const contents = fs.readFileSync(fileName, "utf8");
        console.log(`${fileName} contents: ${contents}`);
    }
    catch (e) {
        console.log(`Error when reading file: ${fileName}:: ${e}`);
    }
}
```

**Comment by andrewbranch** [comment]
```
andrew ~/Desktop/x
$ node index.js
İ contents: FileContents
i̇ contents: FileContents

andrew ~/Desktop/x
$ ls
index.js İ

andrew ~/Desktop/x
$ cat İ
FileContents
andrew ~/Desktop/x
```

image

**Comment by minestarks** [comment]
@andrewbranch  That.... is a heck of a weird looking lowercase i, but if it matches filesystem behavior I can't complain!

**Comment by andrewbranch** [comment]
Well, the uppercase `İ` has a dot added on top of it, so... the lowercase `i̇` has a dot added on top of it. That’s totally how alphabets work, right?

**Comment by sheetalkamat** [comment]
We are going ahead with making Turkish İ in file name as case sensitive and wont change its name on any platfrom. I have added note for the intent of this function and why we make this compromise. 
Fyi from (From the code comment)
```ts
    /**
     * Case insensitive file systems have descripencies in how they handle some characters (eg. turkish Upper case I with dot on top - \u0130)
     * This function is used in places where we want to make file name as a key on these systems
     * It is possible on mac to be able to refer to file name with I with dot on top as a fileName with its lower case form
     * But on windows we cannot. Windows can have fileName with I with dot on top next to its lower case and they can not each be referred with the lowercase forms
     * Technically we would want this function to be platform sepcific as well but
     * our api has till now only taken caseSensitive as the only input and just for some characters we dont want to update API and ensure all customers use those api
     * We could use upper case and we would still need to deal with the descripencies but
     * we want to continue using lower case since in most cases filenames are lowercasewe and wont need any case changes and avoid having to store another string for the key
     * So for this function purpose, we go ahead and assume character I with dot on top it as case sensitive since its very unlikely to use lower case form of that special character
     */
```

**Comment by sheetalkamat** [comment]
@RyanCavanaugh Added note as we discussed offline, let me know if we need any changes before merging in.
