### PR TITLE
Formatting: fix unwanted space between closing parenthesis and string template

### LINKED ISSUE #23047: New option to remove spaces after Template Literals
**VSCode Version:**  1.21.1

**TypeScript Version:**  2.9.0-dev.20180401

**Search Terms:** "Template literals format", "Template strings format", "Tagged template literals format"

**Code:**

1. Declare a template literals function:
```ts
function aFunctionWhichReturnsAnotherTemplateLiterals() {
  return (templateStringsArr: TemplateStringsArray) => {
    console.log(templateStringsArr);
  };
}

aFunctionWhichReturnsAnotherTemplateLiterals()`123`;
```

2. Use VSCode auto format:
```ts
function aFunctionWhichReturnsAnotherTemplateLiterals() {
  return (templateStringsArr: TemplateStringsArray) => {
    console.log(templateStringsArr);
  };
}

aFunctionWhichReturnsAnotherTemplateLiterals() `123`; // <---  Why vscode add this extra space?
```

**In another situation:**

1. Styling components through [styled-component](https://www.styled-components.com/docs/basics#styling-any-components)
```ts
const StyledLink = styled(Link)`
  color: palevioletred;
  font-weight: bold;
`;
```

2. After auto format:
```ts
const StyledLink = styled(Link) ` // <--- This is kinda annoying :(
  color: palevioletred;
  font-weight: bold;
`;
```

**After I comment out this code, VSCode will not add the annoying space anymore!**
```js
// Line 76663 ~ 76665 in node_modules/typescript/lib/tsserver.js

rule("SpaceBetweenForAndAwaitKeyword", 88, 121, [isNonJsxSameLineTokenContext], 2),
// rule("SpaceBetweenStatements", [20, 81, 82, 73], anyToken, [isNonJsxSameLineTokenContext, isNonJsxElementOrFragmentContext, isNotForContext], 2),
rule("SpaceAfterTryFinally", [102, 87], 17, [isNonJsxSameLineTokenContext], 2),
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=function%20aFunctionWhichReturnsAnotherTemplateLiterals()%20%7B%0D%0A%20%20return%20(templateStringsArr%3A%20TemplateStringsArray)%20%3D%3E%20%7B%0D%0A%20%20%20%20console.log(templateStringsArr)%3B%0D%0A%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0AaFunctionWhichReturnsAnotherTemplateLiterals()%60123%60%3B)

Maybe TS team can provide a new option for this situation?

### PR DESCRIPTION
**Pull request by Ken703**
Fixes #23047

### CODE REVIEW

File: src/services/formatting/rules.ts [hunk 1]
```diff
@@ -129,6 +129,9 @@ namespace ts.formatting {
             // template string
             rule("NoSpaceBetweenTagAndTemplateString", SyntaxKind.Identifier, [SyntaxKind.NoSubstitutionTemplateLiteral, SyntaxKind.TemplateHead], [isNonJsxSameLineTokenContext], RuleAction.Delete),
 
+            // No space between closing parenthesis and template string
+            rule("NoSpaceBetweenCloseParenAndTemplateString", SyntaxKind.CloseParenToken, SyntaxKind.NoSubstitutionTemplateLiteral, [isNonJsxSameLineTokenContext], RuleAction.Delete),
```
Comment (DanielRosenwasser) [inline src/services/formatting/rules.ts]: @mhegazy should this just be folded into the above rule?

Comment (mhegazy) [reply src/services/formatting/rules.ts]: yes please. it should be something like:

```ts
rule("NoSpaceBetweenTagAndTemplateString", [SyntaxKind.Identifier, SyntaxKind.CloseParenToken], [SyntaxKind.NoSubstitutionTemplateLiteral, SyntaxKind.TemplateHead], [isNonJsxSameLineTokenContext], RuleAction.Delete),
```

File: tests/cases/fourslash/formatNoSpaceBetweenClosingParenAndTemplateString.ts [hunk 2]
```diff
@@ -0,0 +1,10 @@
+/// <reference path="fourslash.ts"/>
+
+//// foo() `abc`;
+//// bar()`def`;
+
+format.document();
+verify.currentFileContentIs(
+`foo()\`abc\`;
+bar()\`def\`;`
```
Comment (mhegazy) [inline tests/cases/fourslash/formatNoSpaceBetweenClosingParenAndTemplateString.ts]: also add a test for a template with substitutions, since these are parsed diffrentlly e.g.

```ts
baz()`a${x}b`;
```

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

**Comment by mhegazy** [comment]
thanks @Ken703!
