### PR TITLE
Fix references to path-mapped ambient modules in declaration files

### LINKED ISSUE #26863: Relative reference in generated .d.ts file in a monorepo
When generating a .d.ts file, typescript is including a relative reference for an import, which is imported as a module.

```
import { a } from "@ts-bug/a";

export function b(text: string) {
  return a(text);
}
```

generated a definition file:

```
/// <reference path="../../a/index.d.ts" />
export declare function b(text: string): import("@ts-bug/a").AText;
```

In this case it is in a mono-repo which may be confusing things, but the reference should be the same as the import. 

**TypeScript Version:**  
3.0.3, but also happens with 3.1.0-dev.20180901

**Search Terms:**
relative reference paths
generated reference relative

**Code**
I have created a repo with a simple reproduction here https://github.com/wgcrouch/ts-bug

**Expected behavior:**
The reference `/// <reference types="@ts-bug/a" />`

**Actual behavior:**
The reference generated is `/// <reference path="../../a/index.d.ts" />`

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/26439

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #26863

With this change, we now attempt to use a non-relative reference to a declaration file, if possible, before emitting a relative reference.

### CODE REVIEW

File: tests/baselines/reference/declarationEmitPathMappingMonorepo.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+var a_1 = require("@ts-bug/a");
+function b(text) {
+    return a_1.a(text);
+}
+exports.b = b;
+
+
+//// [index.d.ts]
+/// <reference types="@ts-bug/a" />
+export declare function b(text: string): import("@ts-bug/a").AText;
```
Comment (weswigham) [inline tests/baselines/reference/declarationEmitPathMappingMonorepo.js]: As an aside, since the import is `import("@ts-bug/a")`, we don't _need_ the `/// <reference types="@ts-bug/a" />`, since they refer to the "same" thing (or at least cause the same file to be found and included). However since the import could be something like `@ts-bug/a/b` (which could be an ambient module in `@ts-bug/a`), we can't generally elide the reference. A cleanup pass where we remove `types` directives which exactly match an `import` somewhere in the file may be pertinent.

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this into release-3.6
