### PR TITLE
Codefix: Don’t return a `fixId` if there’s definitely nothing else that can be fixed

### LINKED ISSUE #32901: Include additional metadata about which error codes a fix-all quick fix can fix
**TypeScript Version:**  3.6.0-dev.20190810

**Search Terms:**
- quick fix
- code action
- fix all
- tsserver

**Repo**
For the example ts:

```ts
async function init() {
	const result = fetch('url');
	if (result.status === 200) {
		foo((await result).text());
	}
}

function foo(status: string) { }
```

There are two errors related to missing awaits. One has the error code of 2339, while the second has the error code of 2345. However both have a fix all action that will fix both errors. 

**Problem**
VS Code tries to be smart and will only show a fix all action in the UI if there are multiple diagnostics with the same error code in the file. However because these two diagnostics have different error codes, we end up not showing the fix all action even though it really will fix both error

**Proposal:**
I think we should either:

* Only have the TS server return a `fix all` if it knows there are multiple errors that can be fixed in a given file

* Have the existing fix all response (which is returned even if there is just a single error in a file)  include additional metadata about which error code it can fix. Something like:

```
    {
        "fixName": "addMissingAwait",
        "description": "Add 'await'",
        "changes": [
           ...
        ],
        "fixId": "addMissingAwait",
        "fixAllDescription": "Fix all expressions possibly missing 'await'",
        "fixAllCodes": [2345, 2339]
    }
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #32901

- Renames `createCodeFixActionNoFixId` to be `createCodeFixActionWithoutFixAll`.
- When `createCodeFixAction` is used, looks for other diagnostics listed in the fix’s `errorCodes` in the file, and if there are none, strips `fixId` and `fixAllDescription` from the response. This will let VS Code remove their own logic that guesses whether a fix-all might exist, because they don’t have access to that `errorCodes` list—they instead assume the fix only applies to the error code that triggered the request.

### CODE REVIEW

File: src/services/codefixes/addMissingConst.ts [hunk 1]
```diff
@@ -104,6 +104,8 @@ namespace ts.codefix {
             return every([expression.left, expression.right], expression => expressionCouldBeVariableDeclaration(expression, checker));
         }
 
-        return isIdentifier(expression.left) && !checker.getSymbolAtLocation(expression.left);
+        return expression.operatorToken.kind === SyntaxKind.EqualsToken
+            && isIdentifier(expression.left)
+            && !checker.getSymbolAtLocation(expression.left);
```
Comment (andrewbranch) [inline src/services/codefixes/addMissingConst.ts]: Semi-unrelated, but converting `verify.codeFixAll` to `verify.codeFix` in a fourslash test that contained `yield* this.y()` in a non-generator function revealed that we were offering to add `const` before _any_ binary expression with unresolved names, not just binary expressions with `=` operators.

**Comment by andrewbranch** [comment]
@mjbvz could you take a look when you get a chance?

I also should have pinged @amcasey and @minestarks for awareness from the beginning (I think in my mind this was a protocol change, but in fact the protocol was already correct and we weren’t adhering to it correctly)

File: src/services/codeFixProvider.ts [hunk 2]
```diff
@@ -65,11 +81,15 @@ namespace ts.codefix {
...
+    export function eachDiagnostic(context: CodeFixAllContext, errorCodes: readonly number[], cb: (diag: DiagnosticWithLocation) => void): void {
+        for (const diag of getDiagnostics(context)) {
             if (contains(errorCodes, diag.code)) {
                 cb(diag as DiagnosticWithLocation);
             }
         }
     }
+
+    function getDiagnostics({ program, sourceFile, cancellationToken }: CodeFixContextBase) {
+        return program.getSemanticDiagnostics(sourceFile, cancellationToken).concat(computeSuggestionDiagnostics(sourceFile, program, cancellationToken));
```
Comment (amcasey) [inline src/services/codeFixProvider.ts]: Does this do work or just retrieve the diagnostics from a cache?  Are syntactic diagnostics implicitly included in one of these categories?

Comment (amcasey) [inline src/services/codeFixProvider.ts]: Currently, we only support document scope for fix-all, but we left open the option of supporting project or solution.  Is this going to give us mysterious false negatives if we ever light that up?

File: tests/cases/fourslash/codeFixAddMissingAwait_initializer4.ts [hunk 3]
```diff
@@ -15,14 +15,3 @@ verify.codeFix({
   x + y;
 }`
 });
-
-verify.codeFixAll({
```
Comment (amcasey) [inline tests/cases/fourslash/codeFixAddMissingAwait_initializer4.ts]: Would it be worthwhile to explicitly confirm that fix-all is unavailable?

File: src/services/codeFixProvider.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/codeFixProvider.ts]: It does work if necessary, but the way this flow goes, the additional time I’m calling it will always hit the cache.

Comment (andrewbranch) [reply src/services/codeFixProvider.ts]: I’m not sure I understand the scenario you’re concerned about, but I don’t think that feature could be enabled without doing work in this area in the first place, since all the code fix context types include a source file.

File: tests/cases/fourslash/codeFixAddMissingAwait_initializer4.ts (hunk 3 above)
Comment (andrewbranch) [reply tests/cases/fourslash/codeFixAddMissingAwait_initializer4.ts]: Added a new fourslash command for it 👍

File: src/services/codeFixProvider.ts (hunk 2 above)
Comment (amcasey) [reply src/services/codeFixProvider.ts]: I read this as only looking for diagnostics in the current file.  What if there are diagnostics in other documents that could be corrected with fix-all?

Comment (amcasey) [reply src/services/codeFixProvider.ts]: That was my guess.  Thanks!

Comment (amcasey) [reply src/services/codeFixProvider.ts]: That was my guess.  Thanks!

Comment (andrewbranch) [reply src/services/codeFixProvider.ts]: Then this would have to change, along with lots of other stuff in the code fix infrastructure—but it’s unrelated to this PR. I just moved this existing functionality into a new function for reuse.
