### PR TITLE
Triple slash references must resolve against the resolved file name (.d.ts and not original source file) since they are rewritten in the .d.ts emit

### LINKED ISSUE #37928: Declaration file has wrong reference path for composite projects
**TypeScript Version:** 3.9.0-dev.20200413, 3.8.3

**Search Terms:** composite projects, declaration files, paths, reference, baseUrl

**Code**

1. Download zip with the project [ts-bug.zip](https://github.com/microsoft/TypeScript/files/4469787/ts-bug.zip)
1. `npm install`
1. `npm run build-non-composite` - it should be fine

Then, if you run `npm run build` - there are 2 errors:
```
lib/src/common/nominal.d.ts:2:55 - error TS2304: Cannot find name 'MyNominal'.

2 export declare type Nominal<T, Name extends string> = MyNominal<T, Name>;
                                                        ~~~~~~~~~

lib/src/common/nominal.d.ts:1:22 - error TS6053: File 'C:/projects/src/common/types.d.ts' not found.

1 /// <reference path="../../../src/common/types.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And if you run `npm run build-baseUrl` - there are another 2 errors:
```
lib/src/common/nominal.d.ts:2:55 - error TS2304: Cannot find name 'MyNominal'.

2 export declare type Nominal<T, Name extends string> = MyNominal<T, Name>;
                                                        ~~~~~~~~~

lib/src/common/nominal.d.ts:1:23 - error TS2688: Cannot find type definition file for 'types'.

1 /// <reference types="types" />
                        ~~~~~
````

This is pretty similar to #31696. In this case we have 2 bugs:

1. For `npm run build` incorrect generated path for `reference path` (it exits for 1 more folder).
1. For `npm run build-baseUrl` (which is differ from `build` case in the only `baseUrl` compiler option in `common` sub-project) incorrectly replaced `refernce path` with `reference types`, so no project could use it because they might (and will) not have the same `baseUrl` option.

**Related Issues:** #31696, #25600

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #37928 partially.. The report consists of two issues and this one fixes one.

### CODE REVIEW

File: tests/baselines/reference/tsbuild/declarationEmit/initial-build/when-declaration-file-is-referenced-through-triple-slash-and-uses-baseUrl.js [hunk 1]
```diff
@@ -0,0 +1,209 @@
...
+[[90m12:00:00 AM[0m] Building project '/src/solution/src/subProject/tsconfig.json'...
+
+[96msrc/solution/lib/src/common/nominal.d.ts[0m:[93m2[0m:[93m55[0m - [91merror[0m[90m TS2304: [0mCannot find name 'MyNominal'.
+
+[7m2[0m export declare type Nominal<T, Name extends string> = MyNominal<T, Name>;
+[7m [0m [91m                                                      ~~~~~~~~~[0m
+
+[96msrc/solution/lib/src/common/nominal.d.ts[0m:[93m1[0m:[93m23[0m - [91merror[0m[90m TS2688: [0mCannot find type definition file for 'types'.
+
+[7m1[0m /// <reference types="types" />
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsbuild/declarationEmit/initial-build/when-declaration-file-is-referenced-through-triple-slash-and-uses-baseUrl.js:77]: This is the one thats not fixed in this PR but will be a separate one.
