### PR TITLE
Fix globalThis completions

### LINKED ISSUE #30387: No completions on `globalThis`
```ts
const x = 10;

globalThis./*$*/
```

Expect: completions
Actual: no competions

### PR DESCRIPTION
**Pull request by sandersn**
globalThis has two special properties that are relevant here:

1. No declarations.
2. Both namespace and value flags are set.

Since it has a value flag but no declarations, it crashed the check in completions.ts. Adding a declarations list is not the right fix because that causes the completions list to be duplicated: once from the value side and once from the namespace side. The right fix is to skip the value side.

Fixes #30387

### CODE REVIEW

File: tests/cases/fourslash/completionAfterGlobalThis.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+/// <reference path='fourslash.ts'/>
+
+////globalThis./**/
+
+// TODO: This is right except for globalThis and undefined
```
Comment (weswigham) [inline tests/cases/fourslash/completionAfterGlobalThis.ts]: ?

Comment (sandersn) [reply tests/cases/fourslash/completionAfterGlobalThis.ts]: This comment is out of date!

Comment (sandersn) [reply tests/cases/fourslash/completionAfterGlobalThis.ts]: Removed.
