### PR TITLE
Fix completion details auto-imports crashes

### LINKED ISSUE #52661: Completion entry details on re-export in fs-extra causes assertion failure ("some exportInfo should match...")
Repro is pretty consistent. Clone Adonis and request completions in a file with the words `access`. Navigate the completion list to request completion entry details on `access` or `accessSync` from `fs-extra` rather than `fs` or `fs/promises`.

Here's what you should get

```
Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol
Error: Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol
    at getImportFixForSymbol (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:140921:9)
    at Object.getImportCompletionAction (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:140898:34)
    at getCompletionEntryCodeActionsAndSourceDisplay (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:149073:62)
    at Object.getCompletionEntryDetails (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:148959:46)
    at Object.getCompletionEntryDetails2 [as getCompletionEntryDetails] (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:134801:35)
    at USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:178463:43
    at mapDefined (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:2626:22)
    at IpcIOSession.getCompletionEntryDetails (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:178461:20)
    at completionEntryDetails (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:176807:43)
    at USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:179151:69
    at IpcIOSession.executeWithRequestId (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:179143:14)
    at IpcIOSession.executeCommand (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:179151:29)
    at IpcIOSession.onMessage (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:179193:51)
    at process.<anonymous> (USER_DIR/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-5.0.202302060/node_modules/typescript/lib/tsserver.js:180761:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

Error in [adonisjs/core](https://github.com/adonisjs/core)

<details>
<summary>:warning: Note that typescript-4.9.5 also had errors :warning:</summary>

```
Req #297 - completionEntryDetails
    at getImportFixForSymbol (/typescript-4.9.5/lib/tsserver.js:156523:22)
    at Object.getImportCompletionAction (/typescript-4.9.5/lib/tsserver.js:156506:45)
    at getCompletionEntryCodeActionsAndSourceDisplay (/typescript-4.9.5/lib/tsserver.js:136327:33)
    at Object.getCompletionEntryDetails (/typescript-4.9.5/lib/tsserver.js:136266:30)
    at Object.getCompletionEntryDetails (/typescript-4.9.5/lib/tsserver.js:169156:35)
    at /typescript-4.9.5/lib/tsserver.js:181347:57
    at Object.mapDefined (/typescript-4.9.5/lib/tsserver.js:621:30)
    at IOSession.Session.getCompletionEntryDetails (/typescript-4.9.5/lib/tsserver.js:181345:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.9.5/lib/tsserver.js:179982:61)
    at /typescript-4.9.5/lib/tsserver.js:182034:96
    at IOSession.Session.executeWithRequestId (/typescript-4.9.5/lib/tsserver.js:182025:28)
    at IOSession.Session.executeCommand (/typescript-4.9.5/lib/tsserver.js:182034:41)
    at IOSession.Session.onMessage (/typescript-4.9.5/lib/tsserver.js:182062:35)
    at Interface.<anonymous> (/typescript-4.9.5/lib/tsserver.js:186188:31)
```

</details>

```
Req #297 - completionEntryDetails
    at getImportFixForSymbol (/typescript-5.0.0-dev.20230207/lib/tsserver.js:141001:9)
    at Object.getImportCompletionAction (/typescript-5.0.0-dev.20230207/lib/tsserver.js:140978:34)
    at getCompletionEntryCodeActionsAndSourceDisplay (/typescript-5.0.0-dev.20230207/lib/tsserver.js:149095:62)
    at Object.getCompletionEntryDetails (/typescript-5.0.0-dev.20230207/lib/tsserver.js:148981:46)
    at Object.getCompletionEntryDetails2 [as getCompletionEntryDetails] (/typescript-5.0.0-dev.20230207/lib/tsserver.js:134895:35)
    at /typescript-5.0.0-dev.20230207/lib/tsserver.js:178454:43
    at mapDefined (/typescript-5.0.0-dev.20230207/lib/tsserver.js:2627:22)
    at IOSession.getCompletionEntryDetails (/typescript-5.0.0-dev.20230207/lib/tsserver.js:178452:20)
    at completionEntryDetails (/typescript-5.0.0-dev.20230207/lib/tsserver.js:176798:43)
    at /typescript-5.0.0-dev.20230207/lib/tsserver.js:179142:69
    at IOSession.executeWithRequestId (/typescript-5.0.0-dev.20230207/lib/tsserver.js:179134:14)
    at IOSession.executeCommand (/typescript-5.0.0-dev.20230207/lib/tsserver.js:179142:29)
    at IOSession.onMessage (/typescript-5.0.0-dev.20230207/lib/tsserver.js:179184:51)
    at Interface.<anonymous> (/typescript-5.0.0-dev.20230207/lib/tsserver.js:180728:14)
```
That is a filtered view of the text. To see the raw error text, go to RepoResults4/adonisjs.core.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=145888&view=artifacts&type=publishedArtifacts">artifact folder</a></li>

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":294,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/providers/AppProvider.ts","line":87,"offset":24,"entryNames":[{"name":"access","source":"fs-extra","data":{"exportName":"access","moduleSpecifier":"fs-extra","fileName":"/mnt/ts_downloads/core/node_modules/@types/fs-extra/index.d.ts"}}]}}
{"seq":295,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/providers/AppProvider.ts","line":87,"offset":24,"entryNames":[{"name":"access","source":"fs/promises","data":{"exportName":"access","moduleSpecifier":"fs/promises","ambientModuleName":"fs/promises"}}]}}
{"seq":296,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/providers/AppProvider.ts","line":87,"offset":24,"entryNames":[{"name":"accessSync","source":"fs","data":{"exportName":"accessSync","moduleSpecifier":"fs","ambientModuleName":"fs"}}]}}
{"seq":297,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/providers/AppProvider.ts","line":87,"offset":24,"entryNames":[{"name":"accessSync","source":"fs-extra","data":{"exportName":"accessSync","moduleSpecifier":"fs-extra","fileName":"/mnt/ts_downloads/core/node_modules/@types/fs-extra/index.d.ts"}}]}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/adonisjs/core --recurse-submodules</code></li>
<li>In dir <code>core</code>, run <code>git reset --hard 70a661296d5b85a526a7abb2d22b678265574d61</code></li>
  <li>In dir <code>core</code>, run <code>npm install --prefer-offline --no-audit --no-progress --legacy-peer-deps --ignore-scripts -q</code></li>
<li>Back in the initial folder, download <code>RepoResults4/adonisjs.core.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=145888&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./core ./adonisjs.core.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

_Originally posted by @typescript-bot in https://github.com/microsoft/TypeScript/issues/52660#issuecomment-1421528725_

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #52661

The ExportInfoMap is a multimap that contains information about every way that every export is re-exported from different places. Usually, a single symbol that gets re-exported multiple times has a single key pointing to an array of each place it’s exported from. When auto-imports are displayed in completions, we show one completion per key, and we simply pick the “best” re-exporting location out of that array. This lets us prefer short import paths over deep imports. (When and whether this is actually a good heuristic is beside the point.)

The exception is when a single symbol is exported by an ambient module. Ambient modules are considered a stronger signal that the name of the module is significant. For example, when `"node:fs"` re-exports everything from `"fs"`, we don’t want to be forced to pick which module is the “better” place to import `readFile` from—we’d rather show a completion for both, even though the exported symbol is the same in both. So each of these get their own keys in the multimap.

When `completionEntryDetails` is called and we have to re-find the export we showed in the previous `completionInfo` request, we never used to check the module symbol when searching the ExportInfoMap—instead, we asserted on it later, issuing the message seen in the telemetry bug. The fix is simply to check that the module symbol matches as part of our search instead of returning the first export info where just the export symbol itself matches.

The fix sounds obvious, so why was this not _more_ broken before? Well, when `completionEntryDetails` is called for an import from an ambient module, we were able to take shortcut that skips this search through the ExportInfoMap containing the faulty code. So the only way for the bug to manifest is when we request details for a symbol that a _non-ambient_ module re-exports from an ambient module, _and_ the iteration order mattered—it could have been correct by coincidence sometimes.

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot user test tsserver

**Comment by andrewbranch** [comment]
> we were able to take shortcut that skips this search through the ExportInfoMap containing the faulty code

Actually, that shortcut is the other stack trace that shows up in the user tests. I suspect they’re different root causes, but maybe I’ll try to tackle that one too in this PR.

**Comment by andrewbranch** [comment]
@typescript-bot user test tsserver
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot user test tsserver

**Comment by andrewbranch** [comment]
Hm, my last commit fixed the npm repro I was able to get locally. Not sure what’s going on there now.

**Comment by andrewbranch** [comment]
I can’t repro those last two crashes locally, so I’m giving up on them for now. This fixes the large majority of the ones reported at #52660.

File: tests/cases/fourslash/completionsImport_named_didNotExistBefore.ts [hunk 1]
```diff
@@ -31,9 +31,7 @@ verify.completions({
         },
     ], { noLib: true }),
     preferences: { includeCompletionsForModuleExports: true },
-});
-
-verify.applyCodeActionFromCompletion("", {
+}).andApplyCodeAction({
```
Comment (andrewbranch) [inline tests/cases/fourslash/completionsImport_named_didNotExistBefore.ts:34]: This is a new fourslash API for calling `completionEntryDetails` with the exact `data` that was returned in the `completionInfo` response, as an editor would do. I was considering making sending `data` for auto-import completion details requests mandatory, breaking super old editors and about 40 old tests like this one, but ultimately decided against it.

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -542,17 +552,17 @@ function codeFixActionToCodeAction({ description, changes, commands }: CodeFixAc
     return { description, changes, commands };
 }
 
-function getAllExportInfoForSymbol(importingFile: SourceFile, symbol: Symbol, symbolName: string, preferCapitalized: boolean, program: Program, host: LanguageServiceHost, preferences: UserPreferences, cancellationToken: CancellationToken | undefined): readonly SymbolExportInfo[] | undefined {
+function getAllExportInfoForSymbol(importingFile: SourceFile, symbol: Symbol, symbolName: string, moduleSymbol: Symbol, preferCapitalized: boolean, program: Program, host: LanguageServiceHost, preferences: UserPreferences, cancellationToken: CancellationToken | undefined): readonly SymbolExportInfo[] | undefined {
     const getChecker = createGetChecker(program, host);
     return getExportInfoMap(importingFile, host, program, preferences, cancellationToken)
         .search(importingFile.path, preferCapitalized, name => name === symbolName, info => {
-            if (skipAlias(info[0].symbol, getChecker(info[0].isFromPackageJson)) === symbol) {
+            if (skipAlias(info[0].symbol, getChecker(info[0].isFromPackageJson)) === symbol && info.some(i => i.moduleSymbol === moduleSymbol || i.symbol.parent === moduleSymbol)) {
```
Comment (jakebailey) [inline src/services/codefixes/importFixes.ts:559]: Can't recall but I think our own utility for checking if something is in an array is faster.

**Review by jakebailey — APPROVED** [review]
LGTM from airplane wifi :D
