### PR TITLE
fix: `[Symbol.iterator]()` lost on union with `never`

### LINKED ISSUE #62462: `T[] | { t: 'a' } & { t: 'b' }` is not iterable (TS2488)
### 🔎 Search Terms

TS2488

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7 (tested with the playground)
- I was unable to test this with every-ts because this issue seems to affect only the editor, not `tsc`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=3.9.7#code/CYUwxgNghgTiAEA3W8AeAueA7ArgWwCMQYBtAXXgB94BveAF0wHIon4BfeAMloeYLbsAUBBD14JEKLwUAvGiA

### 💻 Code

```ts
declare var x: number[] | { t: 'a' } & { t: 'b' }
let [elem] = x
```

### 🙁 Actual behavior

The array destructure fails with this error:

```
Type 'number[]' must have a '[Symbol.iterator]()' method that returns an iterator.(2488)
```

### 🙂 Expected behavior

No error should be present.

Since an object cannot have a field `t` that holds both `'a'` and `'b'`, `{ t: 'a' } & { t: 'b' }` reduces to `never`. And `number[] | never` decays to `number[]`, which is iterable by definition.

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by nrainhart**
Fixes https://github.com/microsoft/TypeScript/issues/62462

A type's `[Symbol.iterator]()` method is "lost" when union-ing that type with another type that's reducible to `never`.

The reason is that `getReducedType` was not getting called by `getIterationTypesOfIterable`, so non-iterable types that are reducible to `never` were not being erased out.

### CODE REVIEW

**Comment by nrainhart** [comment]
@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Comment by RyanCavanaugh** [comment]
This seems right. I can't construct anything that didn't error before but does now due to a circularity

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -45863,6 +45863,9 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
 
         let allIterationTypes: IterationTypes[] | undefined;
         for (const constituent of (type as UnionType).types) {
+            if (!!(getReducedType(constituent).flags & TypeFlags.Never)) {
```
Comment (Andarist) [inline src/compiler/checker.ts]: q: what if all union members reduce to never? wouldn't this break a case like this?
```ts
declare const o2: ({ a: "foo" } & { a: "bar" }) | ({ b: "qwe" } & { b: "rty" });
const [el2] = o2; // error
```

File: tests/cases/compiler/iterableWithNeverAsUnionMember.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
+// @strict: true
+// @noEmit: true
+// @target: es5,esnext
```
Comment (Andarist) [inline tests/cases/compiler/iterableWithNeverAsUnionMember.ts:3]: I think the `es5` target should produce similar errors but right now it doesnt produce any

File: src/compiler/checker.ts (hunk 1 above)
Comment (nrainhart) [reply src/compiler/checker.ts]: You're right, in that case TS allows the destructuring and types `el2` as `never`.

I went with an alternative solution: reduce the whole iterable-like type instead of the union members: [`93fb716` (#62661)](https://github.com/microsoft/TypeScript/pull/62661/commits/93fb71660d59be63750cd09324639f06ab08b194).

Added this case to the test as well

**Comment by jakebailey** [comment]
@typescript-bot test it
@typescript-bot pack this

File: tests/cases/compiler/iterableWithNeverAsUnionMember.ts (hunk 2 above)
Comment (nrainhart) [reply tests/cases/compiler/iterableWithNeverAsUnionMember.ts:3]: This is not something that's related to this PR in particular, right? Lmk if you think this is something I can address from my end

**Comment by nrainhart** [comment]
@Andarist I addressed [your comment](https://github.com/microsoft/TypeScript/pull/62661#discussion_r2453426999), let me know if you have any others

File: tests/cases/compiler/iterableWithNeverAsUnionMember.ts (hunk 2 above)
Comment (Andarist) [reply tests/cases/compiler/iterableWithNeverAsUnionMember.ts:3]: I feel the issue is slightly more broad, it's about inconsistencies related to never and reduced nevers in unions etc. With that in mind, you have fixed up those inconsistencies for the es2015+ targets but they are still there for the es5 target. That's demonstrated by those error baseline differences and by this (that might overlap with the existing tests):
```ts
// @target: es5
declare const o2: ({ a: "foo" } & { a: "bar" }) | ({ b: "qwe" } & { b: "rty" });
//            ^? const o2: never
const [el3] = o2; // no error ???

declare const o3: never
//            ^? const o3: never
const [el4] = o3; // Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator.(2488)
```

**Comment by Andarist** [comment]
> @Andarist I addressed https://github.com/microsoft/TypeScript/pull/62661#discussion_r2453426999, let me know if you have any others

Note that I only review here as an external contributor. I'm not a team member and I can't approve/reject PRs.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -45830,19 +45830,20 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
      * the `[Symbol.asyncIterator]()` method first, and then the `[Symbol.iterator]()` method.
      */
     function getIterationTypesOfIterable(type: Type, use: IterationUse, errorNode: Node | undefined) {
-        if (type === silentNeverType) {
+        const reducedType = getReducedType(type);
```
Comment (jakebailey) [inline src/compiler/checker.ts]: Why not just `type = getReducedType(type)`?

File: tests/cases/compiler/iterableWithNeverAsUnionMember.ts (hunk 2 above)
Comment (nrainhart) [reply tests/cases/compiler/iterableWithNeverAsUnionMember.ts:3]: `Symbol.iterator` was not a part of [ES5](https://262.ecma-international.org/5.1/), it was introduced in [ES2015](https://262.ecma-international.org/6.0/#sec-iteration). Indeed none of the cases in the new test file cause a type error with the ES5 target: [Playground link](https://www.typescriptlang.org/play/?target=1&noEmit=true#code/CYUwxgNghgTiAEYD2A7AzgF3kgjALngG94oCAiAMySTPgF94AyIk8gI1lroG4AoZdFgDaICDgC68ALzYc3eAHoF8EDBhIYvXkvgALDBgAOaPEoDmASwy6ArmwB0yALYKnFsOrRIKGBQBUAT0MQAGUPC0NfCzQ0GxA0BQA2ACYAFhTeUEhYBAA3WHgADwIUGyc2VSFJAB94AApiDHIoLiYWJvgyNi4ASj4IEGFRZMkZQvkdJABrLSoYeoFMFQGnbAoinpZJmfhlkCd7DCQAMQtCkGA6vt46LQwghBDdKGDpXl3a4imLFGByMAsMEgIDI8hgUGAFhsJngpXKqno73gn3g31+5DgYAwUBQZgGoPgAHcLMBrCUyhUYPJdCALGZ9OT4fMeHcHvAAMKA4HSeBPF4IZhfH5-ToAoH4+h8XgUGwoLEWVDwYBIEIYGwUCgAdSsuk54pAdVgZgIeu5tSEpoGABp6igQISAGpQCBxE1cgabKQAPnguSQJPEm0ISIs6zqAEE1FAAvZopHwQFDTAzD0g0jdgNhPkXSAbWhBk6c6MSMmJsppkjbrdpbL5YqKDgADx+FSFDAgX5oFikTpUGj0NrEHtdTj0L11YrwPxpjODeBCALF8aKZSqdSaatZaBwRCoJZIZIEBqsXvUVqCk8jmC9ZH1YhscgAR0JIIHF4fnRg916fEWQwgADMxYHmWKhqBoQA).

I think addressing this issue is beyond the scope of this PR, but happy to discuss this further.

File: src/compiler/checker.ts (hunk 3 above)
Comment (nrainhart) [reply src/compiler/checker.ts]: Done: [`a0a3bb4` (#62661)](https://github.com/microsoft/TypeScript/pull/62661/commits/a0a3bb44121eb932deb190588e607d3312547531)

**Review by jakebailey — APPROVED** [review]
