### PR TITLE
Fix to use string literal type in ArrayBuffer's `Symbol.toStringTag`

### LINKED ISSUE #60149: Use string literal type in `ArrayBuffer`'s `Symbol.toStringTag`
### ⚙ Compilation target

ES2023

### ⚙ Library

N/A

### Missing / Incorrect Definition

For ES2023 or lower targets, it is acceptable to assign `SharedArrayBuffer` to an `ArrayBuffer` type. On the other hand, the reverse is not possible because `Symbol.toStringTag` of `SharedArrayBuffer` is a string literal type. 

This problem can be solved by making `Symbol.toStringTag` of `ArrayBuffer` a string literal type. `Set`, `Map`, and `Promise` use the `string` type for library compatibility (#19006), while `ArrayBuffer` is not intended to be extended by the user, and indeed `Symbol.species` support for `InitializeTypedArrayFromTypedArray` has been removed (https://github.com/tc39/ecma262/pull/2719), so there should be no problem.

This issue was reported by #59417 and has been addressed by making TypedArrays generic for the ES2024 target.

### Sample Code

```TypeScript
// ES2023 or lower targets, no type error
const buffer: ArrayBuffer = new SharedArrayBuffer(256);
```

### Documentation Link

_No response_

### PR DESCRIPTION
**Pull request by petamoriken**
Fixes #60149

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by petamoriken** [comment]
I haven't figured it out yet, but maybe we need to update the `Buffer` type in @types/node.

**Comment by petamoriken** [comment]
Apparently the package maintainers need to update @types/node.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#typedarrays-are-now-generic-over-arraybufferlike

File: src/harness/vfsUtil.ts [hunk 1]
```diff
@@ -632,12 +632,6 @@ export class FileSystem {
         return realpath;
     }
 
-    /**
-     * Read from a file.
-     *
-     * NOTE: do not rename this method as it is intended to align with the same named export of the "fs" module.
-     */
-    public readFileSync(path: string, encoding?: null): Buffer; // eslint-disable-line no-restricted-syntax
```
Comment (petamoriken) [inline src/harness/vfsUtil.ts:640]: I deleted this type because CI failed, but it might be better to revert it.

**Comment by petamoriken** [comment]
@rbuckton IMO, this PR should be included in TypeScript 5.7, but is it possible?

**Comment by rbuckton** [comment]
No, this will need to wait for 5.8

**Comment by petamoriken** [comment]
@rbuckton Will this PR be included in TypeScript 5.8?

**Comment by rbuckton** [comment]
@typescript-bot test it

**Comment by rbuckton** [comment]
- `effect` - These two failures seem to be due to how `Match.instanceOf` determines the instance type of a constructor function. The constructor type used is only able to pick the first overload of the overload list, which results in the type `Uint8Array<ArrayBuffer>`. `effect` would need to update their tests.
- `puppeteer` - These are due to out of date `@types/node` definitions.
- `webpack` - These seem to be due to out of date `@types/node` definitions referenced in the `yarn.lock` file.
- `xterm` - Also due to out of date `@types/node` defininitions in both `package.json` and `yarn.lock`.
- `actualbudget/actual` - Looks to be due to out of date `@types/node` definitions in `yarn.lock`.

With the exception of `effect`, most of the reported issues I've reviewed so far seem to be due to out-of-date `@types/node` definitions which would need to be addressed by the individual project maintainers. I'm still reviewing the various failures, however.

**Comment by rbuckton** [comment]
This did not make the cut for 5.8, but should be in 5.9. I plan to merge to `main` once we release the 5.8 RC and `main` transitions to 5.9 work.

**Review by rbuckton — APPROVED** [review]

**Comment by dasa** [comment]
I'm also seeing issues caused by this in 5.9.0-beta as described in #62083.

**Comment by jakebailey** [comment]
Please file an issue; closed PRs are not the best place to discuss issues.
