### PR TITLE
Make it a parse error for an `@type` jsdoc tag to not include a type

### LINKED ISSUE #16947: Handle @type without curly braces
**TypeScript Version:**  nightly (2.5.0-dev.20170629)

**Code**

```js
// @ts-check

/** @type number */
const x = "";
```

**Expected behavior:**

Syntax error: `@type` needs curly braces.

**Actual behavior:**

No error.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #16947

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -6136,10 +6136,14 @@ namespace ts {
...
             // Parses out a JSDoc type expression.
             /* @internal */
-            export function parseJSDocTypeExpression(): JSDocTypeExpression {
+            export function parseJSDocTypeExpression(): JSDocTypeExpression;
+            export function parseJSDocTypeExpression(mayBail: true): JSDocTypeExpression | undefined;
+            export function parseJSDocTypeExpression(mayBail?: boolean): JSDocTypeExpression | undefined {
                 const result = <JSDocTypeExpression>createNode(SyntaxKind.JSDocTypeExpression, scanner.getTokenPos());
 
-                parseExpected(SyntaxKind.OpenBraceToken);
+                if (!parseExpected(SyntaxKind.OpenBraceToken) && mayBail) {
```
Comment (sandersn) [inline src/compiler/parser.ts]: `requireBraces` is a lot better name.
