### PR TITLE
fix(53735): Definition file generated from javascript is missing getter

### LINKED ISSUE #53735: Definition file generated from javascript is missing getter
# Bug Report

### 🔎 Search Terms

javascript jsdoc getter declaration .d.ts

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.8.4, 4.9.5, 5.0.4, 5.1.0-dev.20230411), and I reviewed the FAQ for entries about [Common "Bugs" That Aren't Bugs](https://github.com/microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=0&filetype=js#code/KYDwDg9gTgLgBAYwgOwM7wgIwFbAfAXjgG8AoOOMKCMYWATwC44ByANwEMAbAV2BYA05OAHNg8MTBh0AFAEoSwilHE8oyVp178A3MIC+Q-aSA)

note that `filetype` is set to `js`

### 💻 Code

```
export const object = {
  property: 'value',
  get getter() {
    return 'value';
  },
}
```

### 🙁 Actual behavior

The generated `.d.ts` is
```
export namespace object {
    const property: string;
}
```

### 🙂 Expected behavior

The `getter` is included in the generated `.d.ts`

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #53735

### CODE REVIEW

File: tests/cases/compiler/accessorDeclarationEmitJs.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+// @checkJs: true
+// @declaration: true
+// @emitDeclarationOnly: true
+// @filename: /a.js
+export const object = {
+    property: 'value',
+    get getter() {
+        return 'value';
+    },
+}
```
Comment (RyanCavanaugh) [inline tests/cases/compiler/accessorDeclarationEmitJs.ts:11]:
```suggestion
}

export const object2 = {
    property: 'value',
    set setter(v) {
    },
}
```

**Review by RyanCavanaugh — APPROVED** [review]

**Review by sandersn — APPROVED** [review]
