### PR TITLE
Make removeSubtypes resilient to reentry

### LINKED ISSUE #2997: Compiler error - "Maximum call stack size exceeded"
(1.5 beta)

This is the most I can reduce it while still having it crash:

```typescript
class Module {
	public members: Class[];
}

class Namespace {
	public members: (Class | Property)[];
}

class Class {
	public parent: Namespace;
}

class Property {
	public parent: Module | Class;
}

var t: Class | Property;
t.toString();
```

`tsc foo.ts -t es5`

```
G:\src\libjass\node_modules\typescript\bin\tsc.js:0
(function (exports, require, module, __filename, __dirname) { /*! ************
^
RangeError: Maximum call stack size exceeded
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js)
    at unionTypeRelatedToType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11862:35)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11787:42)
    at stringIndexTypesRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:12195:35)
    at objectTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11955:43)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11811:34)
    at propertiesRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:12042:43)
    at objectTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11949:30)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11811:34)
    at typeRelatedToUnionType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11850:35)
```

Alternative call stack for the crash (same code):

```
G:\src\libjass\node_modules\typescript\bin\tsc.js:11929
                    sourceStack = [];
                    ^
RangeError: Maximum call stack size exceeded
    at objectTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11929:21)
    at isRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11811:34)
    at checkTypeRelatedTo (G:\src\libjass\node_modules\typescript\bin\tsc.js:11723:26)
    at checkTypeSubtypeOf (G:\src\libjass\node_modules\typescript\bin\tsc.js:11703:20)
    at isTypeSubtypeOf (G:\src\libjass\node_modules\typescript\bin\tsc.js:11697:20)
    at isSubtypeOfAny (G:\src\libjass\node_modules\typescript\bin\tsc.js:11363:43)
    at removeSubtypes (G:\src\libjass\node_modules\typescript\bin\tsc.js:11373:21)
    at getUnionType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11410:17)
    at getReducedTypeOfUnionType (G:\src\libjass\node_modules\typescript\bin\tsc.js:11426:36)
    at getApparentType (G:\src\libjass\node_modules\typescript\bin\tsc.js:10824:24)
```

The original code from which this test case is derived is [here.](https://github.com/Arnavion/libjass/blob/8e12db7/gulplib/typescript/ast.ts)

Edit: Reduced the case some more - removed the `fullName` getters and simplified the types of `member`.

### PR DESCRIPTION
**Pull request by JsonFreeman**
Fixes #2997

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3572,7 +3572,18 @@ module ts {
             return false;
         }
 
+        // Since removeSubtypes checks the subtype relation, and the subtype relation on a union
+        // may attempt to reduce a union, it is possible that removeSubtypes could be called
+        // recursively on the same set of types.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: For a future reader, this comment might leave them thinking "and...?"

Explain further that the stack is used to detect when subtype reduction is currentlytaking place for a given union type.

Comment (JsonFreeman) [inline src/compiler/checker.ts]:
```
// Since removeSubtypes checks the subtype relation, and the subtype relation on a union
// may attempt to reduce a union, it is possible that removeSubtypes could be called
// recursively on the same set of types. The removeSubtypesStack is used to track which
// sets of types are currently undergoing subtype reduction.
```

**Comment by DanielRosenwasser** [comment]
Since we have a tendency to add related tests with similar names, in the future suffix test names with `01`.

:+1:
