### PR TITLE
Formatter: fix indentation of comments at end of range

### LINKED ISSUE #54243: Formatter: comment at end of selection (or document) doesn't get indented
# Bug Report
Typescript's formatter doesn't indent comments when they appear at the end of the selection (or at the end of the document when formatting the whole document).

### 🔎 Search Terms
comment indentation

### 🕗 Version & Regression Information
5.0.4 (AFAICT this has always been broken)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about formatting and indentation

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYMwBAFALgTgrgUwJRgN4CgD0mxQQZyjAGMB7AW3IQDsp0BfdIA)

### 💻 Code

```ts
if (true) {
// test comment
}
```

### 🙁 Actual behavior

Select all of line 2 (the comment), right click and run "Format selection". The line does not get indented.

### 🙂 Expected behavior

The line should get indented (the same way a non-comment line, or a comment line not at the end of the selection, would get indented).

### Additional Info
Another very common way to trigger this bug: in VS Code, with the "Format on Paste" setting enabled, cut or copy a comment line, then paste it into a different block with different indentation. The indentation should be changed to match the new block (like it does if you do this with a non-comment line), but it doesn't because of this bug.

### PR DESCRIPTION
**Pull request by russelldavis**
Fixes #54243

This builds on top of the fix at #5983, which fixed indentation of whitespace at the end of a range, but didn't handle comments.

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -515,17 +515,22 @@ function formatSpanWorker(
         processNode(enclosingNode, enclosingNode, startLine, undecoratedStartLine, initialIndentation, delta);
     }
 
-    if (!formattingScanner.isOnToken()) {
```
Comment (russelldavis) [inline src/services/formatting/formatting.ts:518]: We really only care if there's any trivia remaining, regardless of whether we ended up on a token. This condition was causing another bug, illustrated in formatSelectionWithTrivia8.ts

**Comment by gabritto** [comment]
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot perf test this
