### PR TITLE
Don't suggest import completions for /a/node_modules if we're in /b

### LINKED ISSUE #19878: Bug in auto import feature
_From @sseppola on November 9, 2017 9:54_

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.17.0
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.3
gitlens|eam|6.0.0
Go|luk|0.6.67
java|red|0.13.0
transpose|v4r|0.0.5
vscode-java-debug|vsc|0.2.0
vscode-java-pack|vsc|0.2.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Restarted VSCode
2. Typed 'log' + enter in a javascript project to trigger a console.log snippet

This triggered VSCode to include the following import statement at the top of my file:
```js
import { log } from '../../../../../../../../../../../../../../Library/Caches/typescript/2.6/node_modules/@types/gulp-util';
```

Reproduces without extensions: Yes

Only reproducible once after launching the application.

_Copied from original issue: Microsoft/vscode#37907_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19878
Relative imports into `node_modules` are bad, especially `../../../../../../../../../../../../../../Library/Caches/typescript/2.6/node_modules/@types/gulp-util`.

### CODE REVIEW

File: tests/cases/fourslash/importNameCodeFixNewImportNodeModules5.ts [hunk 1]
```diff
@@ -1,25 +0,0 @@
-/// <reference path="fourslash.ts" />
-
-//// [|f1/*0*/('');|]
-
-// @Filename: package.json
-//// { "dependencies": { "package-name": "latest" } }
-
-// @Filename: node_modules/package-name/node_modules/package-name2/bin/lib/libfile.d.ts
```
Comment (andy-ms) [inline tests/cases/fourslash/importNameCodeFixNewImportNodeModules5.ts]: Don't think we should have been getting imports from here -- it's fishy to directly import a dependency of a dependency.

Comment (armanio123) [reply tests/cases/fourslash/importNameCodeFixNewImportNodeModules5.ts]: Agreed it's fishy, but this tests seems it's a regression from something that can be done.

I recommend leaving the test in place to check for any regressions.

Comment (andy-ms) [reply tests/cases/fourslash/importNameCodeFixNewImportNodeModules5.ts]: I deleted it file *because* the test started failing, so it's an intentional regression -- I really think we shouldn't have been doing this.
This test was added in #17302 -- @minestarks is this OK to delete?

Comment (minestarks) [reply tests/cases/fourslash/importNameCodeFixNewImportNodeModules5.ts]: yep seems fine to quit doing this. You could just change the expectation of the test case though...

**Comment by andy-ms** [comment]
@armanio123 @minestarks Please re-review
