### PR TITLE
Reparse top level 'await' in modules

### LINKED ISSUE #36817: [3.8] [BUG] TLA top-level await breaks with parenthesis
**TypeScript Version:**  3.8.1-rc

**Search Terms:**

**Code**

```ts
// works:
const DBService = await import('./DBService')
await DBService.start()

// doesn't work
await (await import('./DBService')).start()
await (1 + 1)

// works:
async function foo() {
    await (await import('./DBService')).start()
}

export {}
```

**Expected behavior:**

no error on the `await` word

**Actual behavior:**

TS thinks it is an identifier.

**Playground Link:** 

[Playground link](http://www.typescriptlang.org/v2/en/play?ts=3.8.0-beta#code/PTAEHcHsCcGsGcBcAoAxpAdvALqAIgEIDKAptAG4CWqJoAvKAIbiOW6UC2ADjNgBQByAHTBCpCtRICAlMmatcYslRpCcjaP1nIQoACaQS8DANxQ4clm1B951zj02CRSiTRnS12DVssKbAIygANSgAdq65ggojPAAnhiooABmAK6J2JSYKZCQfNKgAN7IoKVMVri2FaAOvM6ixMqSHl4++cgAvsjIJAAejriFHUA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/35276

### PR DESCRIPTION
**Pull request by rbuckton**
This adds support to the parser to re-parse expressions containing `await` as an identifier *after* we have parsed a source file and determined it to be a module. Cases covered include:

- Parses correctly:
  - `await (x)`
  - `await <T>(x)`
  - `await `` `
  - `await <T>`` `
  - `await[x]`
- Parses with appropriate errors:
  - `await ()` - Expression expected at `)`
  - `await (x, )` - Expression expected at `)`
  - `await <T, U>(x)` - `>` expected at `,`
  - `await .x` - Expression expected at `.`
  - `await ?.x` - Expression expected at `?.`
  - `await ?.[x]` - Expression expected at `?.`
  - `const await = ...` - Identifier expected at `await`
  - And various others

This depends on #35282

Fixes #36817

### CODE REVIEW

**Comment by rbuckton** [comment]
The relevant commits start at https://github.com/microsoft/TypeScript/pull/39084/commits/8ab882aae755e84b50e3afe6e169461b5cc510dd

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -1021,6 +1052,121 @@ namespace ts {
...
         }
 
+        function reparseTopLevelAwait(sourceFile: SourceFile) {
+            return visitEachChild(sourceFile, visitor, reparseContext);
+
+            function visitor(node: Node): VisitResult<Node> {
+                if (!(node.transformFlags & TransformFlags.ContainsPossibleTopLevelAwait)) {
+                    return node;
+                }
+                switch (node.kind) {
```
Comment (weswigham) [inline src/compiler/parser.ts:1062]: This is essentially every non-expression node which contains an expression node, yeah? Can we add a comment to that effect? The requirement for inclusion here is nonobvious.

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -4028,20 +4181,20 @@ namespace ts {
             let parameters: NodeArray<ParameterDeclaration>;
             if (!parseExpected(SyntaxKind.OpenParenToken)) {
                 if (!allowAmbiguity) {
-                    return undefined;
+                            return undefined;
```
Comment (weswigham) [inline src/compiler/parser.ts:4184]: This whitespace and the below whitespace changes seem off.

File: src/compiler/parser.ts [hunk 3]
```diff
@@ -1032,8 +1178,15 @@ namespace ts {
...
             // code from createNode is inlined here so createNode won't have to deal with special case of creating source files
             // this is quite rare comparing to other nodes and createNode should be as fast as possible
-            const sourceFile = factory.createSourceFile(statements, endOfFileToken, flags);
+            let sourceFile = factory.createSourceFile(statements, endOfFileToken, flags);
             setTextRangePosWidth(sourceFile, 0, sourceText.length);
+            setExternalModuleIndicator(sourceFile);
+
+            // If we parsed this as an external module, it may contain top-level await
+            if (isExternalModule(sourceFile) && sourceFile.transformFlags & TransformFlags.ContainsPossibleTopLevelAwait) {
+                sourceFile = reparseTopLevelAwait(sourceFile);
```
Comment (weswigham) [inline src/compiler/parser.ts:1187]: Hm. Should we do something smarter when we're doing an incremental parse, like only visiting and reparsing the changed subtree?

File: src/compiler/parser.ts [hunk 4]
```diff
@@ -1021,6 +1052,121 @@ namespace ts {
...
+                }
+            }
+
+            function reparse<T extends Node>(node: T, parse: () => T): T | Expression;
+            function reparse<T extends Node>(node: T | undefined, parse: () => T): T | Expression | undefined;
+            function reparse<T extends Node>(node: T | undefined, parse: () => T) {
+                if (node && node.transformFlags & TransformFlags.ContainsPossibleTopLevelAwait) {
+                    if (isExpression(node)) {
+                        return speculationHelper(() => {
+                            scanner.setTextPos(node.pos);
```
Comment (weswigham) [inline src/compiler/parser.ts:1090]: Would using `initializeState` and passing in a syntax cursor here allow us to reuse the initially parsed nodes where possible, even in the case of a partial reparse? (Reparse due to context invalidation and incremental reparsing I would think seem similar)

File: src/compiler/types.ts [hunk 5]
```diff
@@ -2722,7 +2722,7 @@ namespace ts {
 
     export interface ThrowStatement extends Statement {
         readonly kind: SyntaxKind.ThrowStatement;
-        readonly expression?: Expression;
+        readonly expression: Expression;
```
Comment (weswigham) [inline src/compiler/types.ts:2725]: Do we need to handle emitting an arbitrary non-empty expression for empty identifiers in the emitter for this? Or is it OK to just let the empty identifier get emitted?

File: src/compiler/parser.ts (hunk 4 above)
Comment (rbuckton) [reply src/compiler/parser.ts:1090]: Possibly. I'm on the fence as to whether I wanted to set `original` pointers for these nodes. I need to add some incremental parse test cases.

File: src/compiler/types.ts (hunk 5 above)
Comment (rbuckton) [reply src/compiler/types.ts:2725]: We already handle that. There was one test difference showing the change, as we went from `throw;` to `throw ;`. 

I think this is better to do now because one of these days I want to propose `throw;` to TC39 as a means to rethrow an exception in a `catch {}` block (without a reachable binding), in which case having a missing expression would have a different meaning...

File: src/compiler/parser.ts (hunk 3 above)
Comment (rbuckton) [reply src/compiler/parser.ts:1187]: The biggest issue with incremental parse is that it depends in part on differences in the context flags, and whether the top-level is an `Await` context is dependent on whether we treat it as a module. What happens when the changed subtree includes a new `export {}` that turns the file into a module? What I might do is hold onto a pointer for the non-reparsed source file to pass to incremental parse, and then just handle reparse individually as needed. We might not get as much node reuse inside of expressions, but incremental parse node reuse only applies to a limited set of list contexts (statements, class members, switch clauses, etc.) and is ignored at the expression level.

File: src/compiler/parser.ts (hunk 4 above)
Comment (rbuckton) [reply src/compiler/parser.ts:1090]: I considered using incremental parse, but it doesn't apply at the expression level, only at certain list context levels (see https://github.com/microsoft/TypeScript/pull/39084#discussion_r441770690). I might have been able to leverage it by reparsing the statement itself, but some of the necessary incremental parse machinery isn't currently accessible from within `Parser`, and would be fairly complex to wire up properly.

**Comment by rbuckton** [comment]
@weswigham would you mind giving this one more look over now that I've added some additional tests and a few changes?

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
I'll add one.
