### PR TITLE
Changed error for setter when emitting declaration with private param…

### LINKED ISSUE #1976: Incorrect error in declaration emit for set accessors
Compile the following with -declaration:

``` ts
module M {
    interface I { }
    export class C {
        set foo(x: I) { }
    }
}
```

The error says, "Parameter 'foo' of public property setter from exported class has or is using private name 'I'."

But it should not be parameter 'foo', it should be parameter 'x'.

### PR DESCRIPTION
**Pull request by NaridaL**
… type

so that error message refers to prop name instead of param name.

Changed getter errors for similar case so they also refer to prop name.

Fixed bug where static getters wouldn't output their specific error.

Fixes #1976

### CODE REVIEW

File: src/compiler/declarationEmitter.ts [hunk 1]
```diff
@@ -1429,45 +1429,40 @@ namespace ts {
             function getAccessorDeclarationTypeVisibilityError(symbolAccessibilityResult: SymbolAccessibilityResult): SymbolAccessibilityDiagnostic {
                 let diagnosticMessage: DiagnosticMessage;
                 if (accessorWithTypeAnnotation.kind === SyntaxKind.SetAccessor) {
-                    // Setters have to have type named and cannot infer it so, the type should always be named
-                    if (hasModifier(accessorWithTypeAnnotation.parent, ModifierFlags.Static)) {
```
Comment (NaridaL) [inline src/compiler/declarationEmitter.ts]: Not sure what was up with the `.parent`, it didn't output the static error message when appropriate: https://github.com/Microsoft/TypeScript/pull/18593/files#diff-a085a7cb8abe9e3fd72630f034bbe686L165

**Comment by NaridaL** [comment]
Alternate impl: XD
```

                const staticOrNot = hasModifier(accessorWithTypeAnnotation, ModifierFlags.Static) ? "_static" : "";
                const getterOrSetter = accessorWithTypeAnnotation.kind === SyntaxKind.SetAccessor
                    ? "Parameter_type_of_public" + staticOrNot + "_setter"
                    : "Return_type_of_public" + staticOrNot + "_getter";
                const propEnd = symbolAccessibilityResult.errorModuleName ?
                    symbolAccessibilityResult.accessibility === SymbolAccessibility.CannotBeNamed ?
                        "_from_exported_class_has_or_is_using_name_1_from_external_module_2_but_cannot_be_named" :
                        "_from_exported_class_has_or_is_using_name_1_from_private_module_2" :
                    "_from_exported_class_has_or_is_using_private_name_1";
                return {
                    diagnosticMessage: (<any>Diagnostics)[getterOrSetter + "_0" + propEnd],
                    errorNode: <Node>accessorWithTypeAnnotation.name,
                    typeName: accessorWithTypeAnnotation.name
                };
```

**Comment by NaridaL** [comment]
I also have a related commit which changes references to "private module" to the more up-to-date "private namespace" https://github.com/NaridaL/TypeScript/commit/e692f83a8169389873601c346cbacd216bafae4f, let me know if you want me to add it to this PR.

**Comment by mhegazy** [comment]
build break addressed in https://github.com/Microsoft/TypeScript/commit/ca181a7952a5f51d6f1fff2b4ffe5e236bf81cec
