### PR TITLE
fix(52444): "... is a type and must be imported using a type-only import ..." should have a quick fix

### LINKED ISSUE #52444: "... is a type and must be imported using a type-only import ..." should have a quick fix
# Suggestion

## 🔍 Search Terms

verbatimModuleSyntax type quick fix

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I am trying out the beta, and got this message when enabling `verbatimModuleSyntax` (as expected). However, the only quick fix available to me was the one to convert the import to a namespace import.

## 📃 Motivating Example

```ts
import { ImAType, NotAType } from "foo";
```

Becomes:

```ts
import { type ImAType, NotAType } from "foo";
```

Or:

```ts
import { type ImAType } from "foo";
import { NotAType } from "foo";
```

I thought we had it (maybe it only works for `preserveValueImports`?)

## 💻 Use Cases

People switching these new stricter flags on.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #52444

### CODE REVIEW

File: src/services/codefixes/convertToTypeOnlyImport.ts [hunk 1]
```diff
@@ -1,67 +1,69 @@
...
-                importClause.name,
-                /*namedBindings*/ undefined),
-            importDeclaration.moduleSpecifier,
-            /*assertClause*/ undefined));
+    else {
+        const importClause = declaration.importClause as ImportClause;
+        if (importClause.name && importClause.namedBindings) {
+            changes.replaceNodeWithNodes(sourceFile, declaration, [
+                factory.createImportDeclaration(declaration.modifiers, factory.createImportClause(/*isTypeOnly*/ true, importClause.name, /*namedBindings*/ undefined), declaration.moduleSpecifier, declaration.assertClause),
+                factory.createImportDeclaration(declaration.modifiers, factory.createImportClause(/*isTypeOnly*/ true, /*name*/ undefined, importClause.namedBindings), declaration.moduleSpecifier, declaration.assertClause),
```
Comment (DanielRosenwasser) [inline src/services/codefixes/convertToTypeOnlyImport.ts:60]: Is it safe to reuse `declaration.moduleSpecifier` and `declaration.assertClause`? I believe our refactoring infrastructure has issues if you share nodes while formatting. @andrewbranch might know more.

Comment (DanielRosenwasser) [reply src/services/codefixes/convertToTypeOnlyImport.ts:60]: (Maybe add a test for this?)

Comment (andrewbranch) [reply src/services/codefixes/convertToTypeOnlyImport.ts:60]: I don’t 100% know exactly when/why problems occur, but I would say to be safe, if you’re duplicating a Node, it’s best to clone it. I suspect this is fine, but it’s hard to say.

Comment (jakebailey) [reply src/services/codefixes/convertToTypeOnlyImport.ts:60]: I suspect it'd be fine since this just goes into textChanges... but I can't say for sure. A test would be nice (unless I've missed an explicit test for this particular code; I'm a little confused by the array).

Comment (andrewbranch) [reply src/services/codefixes/convertToTypeOnlyImport.ts:60]: The emitter will sometimes try to look at original positions of a node to figure out how many line breaks to include, so it's possible something in that could get weird.

**Review by jakebailey — APPROVED** [review]

File: src/services/codefixes/convertToTypeOnlyImport.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/services/codefixes/convertToTypeOnlyImport.ts]: Well, it's more that when we format the nodes, we will have some synthetic `pos`/`end` onto nodes.

Then it typically triggers a debug assert in `consumeTokenAndAdvanceScanner`/`processChildNodes`.

https://github.com/microsoft/TypeScript/blob/2a8436c529640327a3460463fc945694584ff1c3/src/services/formatting/formatting.ts#L968-L969

See #44301 and #44523.

File: src/services/codefixes/convertToTypeOnlyImport.ts [hunk 2]
```diff
@@ -55,9 +57,12 @@ function doChange(changes: textChanges.ChangeTracker, sourceFile: SourceFile, de
     else {
         const importClause = declaration.importClause as ImportClause;
         if (importClause.name && importClause.namedBindings) {
+            const modifiers = getSynthesizedDeepClones(declaration.modifiers, /*includeTrivia*/ true);
+            const moduleSpecifier = getSynthesizedDeepClone(declaration.moduleSpecifier, /*includeTrivia*/ true);
+            const assertClause = getSynthesizedDeepClone(declaration.assertClause, /*includeTrivia*/ true);
```
Comment (DanielRosenwasser) [inline src/services/codefixes/convertToTypeOnlyImport.ts:62]: I *think* that even for cloned nodes, these can't be shared. So each import needs to get its own clones of the `modifiers`, the `moduleSpecifier`, and the `assertClause`.

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
Uh oh, was this supposed to get into 5.0 to pair with the new options?

**Comment by andrewbranch** [comment]
Yeah 😕

**Comment by jakebailey** [comment]
@DanielRosenwasser can we cherry-pick this to 5.0? 😄 

(once the conflicts are fixed)

**Comment by jakebailey** [comment]
Thanks for the prompt merge from main!

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.0

**Comment by jakebailey** [comment]
Making it for discussion, but mainly so I know if I have to do it manually.

**Comment by jakebailey** [comment]
Dangit
