### PR TITLE
Fix implement interface quickfix import types

### LINKED ISSUE #29406: Absolute `import(...)` path used in type for the implement interface quick fix
From https://github.com/Microsoft/vscode/issues/66191

**TypeScript Version:**  3.3.0-dev.20190112

**Search Terms:**
- Implement interface
- quick fix
- code action

**Repo**
(see comment for simpler repo)

1. In the VS Code codebase
1. Open `src/vs/workbench/browser/parts/editor/editor.ts`
1. At the top of the file, add the code:

```ts
class Foo implements ISerializableView {

}
```

1. Trigger the `implement interface` quick fix on `Foo`

**Bug:**
`priority` uses an `import` type with an absolute path:

```ts
class Foo implements ISerializableView {
	toJSON(): object {
		throw new Error('Method not implemented.');
	}	element: HTMLElement;
	minimumWidth: number;
	maximumWidth: number;
	minimumHeight: number;
	maximumHeight: number;
	onDidChange: Event<{ width: number; height: number; }>;
	priority?: import("/Users/matb/projects/vscode/src/vs/base/browser/ui/splitview/splitview").LayoutPriority;
	snapSize?: number;
	layout(width: number, height: number): void {
		throw new Error('Method not implemented.');
	}


}
```

This seems related to `ISerializableView` extending another interface which uses types defined in other files

### PR DESCRIPTION
**Pull request by weswigham**
The `implments` quick fixes were not providing the host required to generate good paths for import types into the type node helpers they used, so they were always generating absolute paths (or amd module names).

Fixes #29406

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -3037,8 +3037,10 @@ namespace ts {
...
         /** Note that the resulting nodes cannot be checked. */
         signatureToSignatureDeclaration(signature: Signature, kind: SyntaxKind, enclosingDeclaration?: Node, flags?: NodeBuilderFlags): SignatureDeclaration & {typeArguments?: NodeArray<TypeNode>} | undefined;
+        /* @internal */ signatureToSignatureDeclaration(signature: Signature, kind: SyntaxKind, enclosingDeclaration?: Node, flags?: NodeBuilderFlags, tracker?: SymbolTracker): SignatureDeclaration & {typeArguments?: NodeArray<TypeNode>} | undefined;  // tslint:disable-line unified-signatures
         /** Note that the resulting nodes cannot be checked. */
         indexInfoToIndexSignatureDeclaration(indexInfo: IndexInfo, kind: IndexKind, enclosingDeclaration?: Node, flags?: NodeBuilderFlags): IndexSignatureDeclaration | undefined;
+        /* @internal */ indexInfoToIndexSignatureDeclaration(indexInfo: IndexInfo, kind: IndexKind, enclosingDeclaration?: Node, flags?: NodeBuilderFlags, tracker?: SymbolTracker): IndexSignatureDeclaration | undefined;
```
Comment (sheetalkamat) [inline src/compiler/types.ts]: Should we be doing this for `symbolToParameterDeclaration`, `typeParameterToDeclaration` where we call it from signatureHelp to have tracker in there?

Comment (weswigham) [reply src/compiler/types.ts]: Possibly, yeah. Unless they always print unqualified names, and so don't need to bother.

**Comment by weswigham** [comment]
@sheetalkamat the `symbolDisplay` files always specifies `UseAliasDefinedOutsideCurrentScope`, so it should never need to use import types (it'll use aliases not in scope), so signature help shouldn't need any adjustment AFAIK.
