### PR TITLE
Object spread rest fixes

### LINKED ISSUE #12200: Object spread with rest arguments causes compile error
**TypeScript Version:**  2.2.0-dev.20161112

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
export class ToggleTests {
  state: any = {};

  toggle1(key: string) {
    console.log({ ...this.state, [key]: !this.state[key] });
  }

  toggle2(...keys: string[]) {
    console.log({ ...this.state, [keys[0]]: !this.state[keys[0]] });
  }

  toggle3(...keys: string[]) {
    console.log(keys.reduce((dict, key) => ({ ...dict, [key]: !this.state[key] }), {}));
  }

  toggle4(...keys: string[]) {
    console.log(keys.reduce((dict, key) => {
      dict[key] = !this.state[key];
      return dict;
    }, {}));
  }
}

```

**Expected behavior:**
It should work (;
**Actual behavior:** 
This code won't compile. If I delete/comment `toggle2()` and `toggle3()` methods it will compile and `toggle1()` and `toggle4()` methods work as expected.

Here's full error stack:
```
TypeError: Cannot read property 'kind' of undefined
    at isNumericName (~\node_modules\typescript\lib\typescript.js:33945:24)
    at getObjectLiteralIndexInfo (~\node_modules\typescript\lib\typescript.js:34000:48)
    at createObjectLiteralType (~\node_modules\typescript\lib\typescript.js:34137:67)
    at checkObjectLiteral (~\node_modules\typescript\lib\typescript.js:34128:52)
    at checkExpressionWorker (~\node_modules\typescript\lib\typescript.js:37309:28)
    at checkExpression (~\node_modules\typescript\lib\typescript.js:37268:42)
    at checkExpressionWorker (~\node_modules\typescript\lib\typescript.js:37320:28)
    at checkExpression (~\node_modules\typescript\lib\typescript.js:37268:42)
    at checkExpressionCached (~\node_modules\typescript\lib\typescript.js:37184:38)
    at getReturnTypeFromBody (~\node_modules\typescript\lib\typescript.js:36190:24)
    at getReturnTypeOfSignature (~\node_modules\typescript\lib\typescript.js:28554:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (~\node_modules\typescript\lib\typescript.js:36439:21)
    at checkDeferredNodes (~\node_modules\typescript\lib\typescript.js:40914:25)
    at checkSourceFileWorker (~\node_modules\typescript\lib\typescript.js:40948:17)
    at checkSourceFile (~\node_modules\typescript\lib\typescript.js:40928:13)
    at Object.forEach (~\node_modules\typescript\lib\typescript.js:1276:30)
```

http://plnkr.co/edit/NIz1MhKpK28Afyf5fsbx?p=preview

### LINKED ISSUE #12211: Object spread rename issue
```ts
const test = {
    a: 1
}

const d = { ...test }
```

Rename `test` on line `1` to `foo`

Result:
```ts
const foo = {
    a: 1
}

const d = { ...test }  // <-- Not renamed
```

### LINKED ISSUE #12227: Incorrect test in __rest helper for Object rest
**TypeScript Version:**  2.2.0-dev.20161114
The emit for `__rest` uses `!e.indexOf(p)` to check as to whether a property name should be excluded. This test is incorrect as `Array.prototype.indexOf` return `-1` if an element is not found, or a zero-bounded index if an element is found, for example:

```js
const e = ["a", "b"];
!e.indexOf("a") === !(0)  === true  // fail, we want 'false' here`
!e.indexOf("b") === !(1)  === false // ok, we want 'false' here`
!e.indexOf("c") === !(-1) === false // fail, we want 'true' here`
```

A concise and correct test should instead be `!~e.indexOf(p)`, as unary `~` will give the twos-complement of `e.indexOf(p)`:

```js
const e = ["a", "b"];
!~e.indexOf("a") === !~(0)  === !(-1) === false // ok, we want 'false' here
!~e.indexOf("b") === !~(1)  === !(-2) === false // ok, we want 'false' here
!~e.indexOf("c") === !~(-1) === !(0)  === true  // ok, we want 'true' here
```

**Expected emit:**
```js
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && !~e.indexOf(p))
        t[p] = s[p];
    return t;
};
```
**Actual emit:** 
```js
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && !e.indexOf(p))
        t[p] = s[p];
    return t;
};
```

### LINKED ISSUE #12228: Object rest issue with computed property names
**TypeScript Version:**  2.2.0-dev.20161114

When emitting Object Rest in `--target es5` with a binding or assignment pattern containing a computed property name, we emit "undefined" instead of the value of the computed property name converted to a string. As a result, the `e.indexOf(p)` check results in a false negative in the `__rest` helper. *NOTE: we must ensure the value of the computed property we pass to `__rest` is converted to a string otherwise `e.indexOf(p)` will still result in a false negative.*

Also, `!e.indexOf(p)` is wrong, see #12227 for details.

**Code**
```ts
const x = 1;
const { [x]: a, ...b } = { 1: "a", 2: "b" };
```

**Expected emit:**
```js
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && !~e.indexOf(p))
        t[p] = s[p];
    return t;
};
var x = 1;
var _a = { 1: "a", 2: "b" }, _b = x, a = _a[_b], b = __rest(_a, [_b + ""]);
```
**Actual emit:** 
```js
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && !e.indexOf(p))
        t[p] = s[p];
    return t;
};
var x = 1;
var _a = { 1: "a", 2: "b" }, _b = x, a = _a[_b], b = __rest(_a, ["undefined"]);
```

### LINKED ISSUE #12252: Object rest does not preserve enumerable Symbol keys
Checked with the improved `__rest` helper from [this PR](https://github.com/Microsoft/TypeScript/pull/12248), but also applies to `master`.

The [`CopyDataProperties` operation](https://sebmarkbage.github.io/ecmascript-rest-spread/#AbstractOperations-CopyDataProperties) that is used to define object rest uses the `[[OwnPropertyKeys]]` operation, which does return `Symbol`s (https://tc39.github.io/ecma262/#sec-ordinaryownpropertykeys).

`for .. in`, however, [skips over `Symbol` keys](https://tc39.github.io/ecma262/#sec-enumerate-object-properties); a potential fix it so do a second copy loop with the result of `Object.getOwnPropertySymbols` if available.

Screenshot of a Chrome REPL session comparing `__rest`'s behavior with `Object.assign`, which is supposed to have (almost) the same [copying behavior](https://tc39.github.io/ecma262/#sec-object.assign):

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #12211 
Fixes #12200 
Fixes #12227 
Fixes #12228 

New:
Fixes #12252

1. Rename finds identifiers in spread assignment expressions.
2. Spreads with computed properties of type number or any no longer crash the compiler.
3. Rest emit uses indexOf === -1 instead of !indexOf to filter properties.
4. Rest emit correctly refers to computed properties' generated temps.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11193,7 +11193,10 @@ namespace ts {
             let hasComputedStringProperty = false;
             let hasComputedNumberProperty = false;
 
-            for (const memberDecl of node.properties) {
+            let i = 0;
```
Comment (rbuckton) [inline src/compiler/checker.ts]: This looks like it can probably be part of the following `for` declaration rather than on its own.

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -45,7 +45,7 @@ var __assign = (this && this.__assign) || Object.assign || function(t) {
         const restHelper = `
 var __rest = (this && this.__rest) || function (s, e) {
     var t = {};
-    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && !e.indexOf(p))
+    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) === -1)
```
Comment (rbuckton) [inline src/compiler/emitter.ts]: Wouldn't `>= 0` be a few less chars?

File: src/compiler/transformers/destructuring.ts [hunk 3]
```diff
@@ -413,17 +419,28 @@ namespace ts {
...
                     continue;
                 }
-                const str = <StringLiteral>createSynthesizedNode(SyntaxKind.StringLiteral);
-                str.pos = location.pos;
-                str.end = location.end;
-                str.text = getTextOfPropertyName(getPropertyName(elements[i]));
-                propertyNames.push(str);
+                if (isComputedPropertyName(getPropertyName(element))) {
+                    // get the temp name and put that in there instead, like `_tmp + ""`
+                    const stringifiedTemp = <StringLiteral>createSynthesizedNode(SyntaxKind.StringLiteral);
```
Comment (rbuckton) [inline src/compiler/transformers/destructuring.ts]: Do we need the location for the literal? Also, why not just use `createLiteral("", location)`?

File: src/compiler/transformers/destructuring.ts [hunk 4]
```diff
@@ -413,17 +419,28 @@ namespace ts {
...
+                    stringifiedTemp.pos = location.pos;
+                    stringifiedTemp.end = location.end;
+                    stringifiedTemp.text = "";
+                    propertyNames.push(createBinary(computedTempVariables.shift(), SyntaxKind.PlusToken, stringifiedTemp));
+                }
+                else {
+                    const str = <StringLiteral>createSynthesizedNode(SyntaxKind.StringLiteral);
```
Comment (rbuckton) [inline src/compiler/transformers/destructuring.ts]: For `StringLiteral` and `Identifier` you can just call `createLiteral(element)`, which creates a StringLiteral that reads its literal text from the original identifier. That way you can preserve unicode escape sequences.  We could probably add support for `NumericLiteral` to `createLiteral` as well.

File: src/compiler/transformers/destructuring.ts [hunk 5]
```diff
@@ -548,8 +569,13 @@ namespace ts {
                         bindingElements = [];
                     }
                     // Rewrite element to a declaration with an initializer that fetches property
+                    // TODO: Probably save the result of createDestructuringPropertyAccess if propName is a computed property
```
Comment (rbuckton) [inline src/compiler/transformers/destructuring.ts]: Is this TODO something you still have yet to do for this PR or is it for future work?

File: src/compiler/transformers/destructuring.ts [hunk 6]
```diff
@@ -548,8 +569,13 @@ namespace ts {
                         bindingElements = [];
                     }
                     // Rewrite element to a declaration with an initializer that fetches property
+                    // TODO: Probably save the result of createDestructuringPropertyAccess if propName is a computed property
                     const propName = element.propertyName || <Identifier>element.name;
-                    emitBindingElement(element, createDestructuringPropertyAccess(value, propName));
+                    const propAccess = createDestructuringPropertyAccess(value, propName);
+                    if (isComputedPropertyName(propName)) {
+                        (computedTempVariables = computedTempVariables || []).push((propAccess as ElementAccessExpression).argumentExpression);
```
Comment (rbuckton) [inline src/compiler/transformers/destructuring.ts]: See `append` in `core.ts`:
```ts
computedTempVariables = append(computedTempVariables, (propAccess as ElementAccessExpression).argumentExpression);
```

File: tests/baselines/reference/objectRest.symbols [hunk 7]
```diff
@@ -1,42 +1,42 @@
 === tests/cases/conformance/types/rest/objectRest.ts ===
-let o = { a: 1, b: 'no' }
->o : Symbol(o, Decl(objectRest.ts, 0, 3))
+var o = { a: 1, b: 'no' }
```
Comment (rbuckton) [inline tests/baselines/reference/objectRest.symbols]: Why are these suddenly `var` and not `let`?

File: src/compiler/transformers/destructuring.ts [hunk 8]
```diff
@@ -413,17 +419,28 @@ namespace ts {
...
-                str.end = location.end;
-                str.text = getTextOfPropertyName(getPropertyName(elements[i]));
-                propertyNames.push(str);
+                if (isComputedPropertyName(getPropertyName(element))) {
+                    // get the temp name and put that in there instead, like `_tmp + ""`
+                    const stringifiedTemp = <StringLiteral>createSynthesizedNode(SyntaxKind.StringLiteral);
+                    stringifiedTemp.pos = location.pos;
+                    stringifiedTemp.end = location.end;
+                    stringifiedTemp.text = "";
+                    propertyNames.push(createBinary(computedTempVariables.shift(), SyntaxKind.PlusToken, stringifiedTemp));
```
Comment (Kovensky) [inline src/compiler/transformers/destructuring.ts]: This will crash at runtime if the `typeof` of the key is `Symbol`.

File: src/compiler/emitter.ts (hunk 2 above)
Comment (timsuchanek) [inline src/compiler/emitter.ts]: Even less chars would be `!~e.indexOf(p)`

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Fixed, left over from an earlier single-variable attempt.

File: src/compiler/emitter.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/emitter.ts]: The test is for *not* found. But I guess i could use `< 0`.

@timsuchanek Typescript's emit tries to balance readability, speed and brevity. Brevity is the least important of the three, though, and I think `!~e.indexOf(p)` is less readable than `e.indexOf(p) < 0`.

Comment (sandersn) [inline src/compiler/emitter.ts]: Switched to `< 0`.

File: src/compiler/transformers/destructuring.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/transformers/destructuring.ts]: Weird, last time I looked I thought `createLiteral` said that it returns `NumericLiteral`. You're right, that's much better.

Comment (sandersn) [inline src/compiler/transformers/destructuring.ts]: I don't know what location is used for -- source maps, right? I'll leave it out of the `createLiteral("")` call for now and leave it in elsewhere.

File: src/compiler/transformers/destructuring.ts (hunk 5 above)
Comment (sandersn) [inline src/compiler/transformers/destructuring.ts]: It's already done. I delete the TODO.

File: src/compiler/transformers/destructuring.ts (hunk 6 above)
Comment (sandersn) [inline src/compiler/transformers/destructuring.ts]: Thanks for the reminder. I keep forgetting about `append`.

File: src/compiler/transformers/destructuring.ts (hunk 8 above)
Comment (sandersn) [inline src/compiler/transformers/destructuring.ts]: Do you suggest `toString` instead?

File: tests/baselines/reference/objectRest.symbols (hunk 7 above)
Comment (sandersn) [inline tests/baselines/reference/objectRest.symbols]: I changed the source declaration (line 2) so I could reuse `o` in a destructuring assignment below.

File: src/compiler/transformers/destructuring.ts (hunk 8 above)
Comment (Kovensky) [inline src/compiler/transformers/destructuring.ts]: That would crash with `"number"` / `"undefined"` / `null` instead :(

A workaround could be to use `String()` instead, as that will work with anything (and hopefully nobody _actually_ has a string key like that), but it would prevent easily improving `__rest` into being able to preserve (and filter) `Symbol`...

The most correct option would be `typeof x == "symbol" ? x : String(x)`.
