### PR TITLE
Inspect all possible module paths when looking for the best one to create a specifier with

### LINKED ISSUE #25511: In certain cases TS 2.9 outputs incorrect definitions (.d.ts)
**TypeScript Version:**  2.9.2 and 3.0.0-dev.201xxxxx

**Search Terms:** relaxed, declarations

**Expected behavior:**
Definitions have correct import statements.

**Actual behavior:**

In certain cases e.g. monorepo structure where dependencies are linked inside packages from the root `node_modules` folder (you can read about that more here: [bolt](https://github.com/boltpkg/bolt)) output .d.ts files contain pretty weird paths...

**Code**: https://github.com/d4rkr00t/tsc29-test-relaxed-resolve

```ts
// packages/package-a/src/index.ts
import { css } from 'styled-components';

export const styles = css`
	display: table;
`;
```

Outputs definition file:
```ts
// packages/package-a/dist/index.d.ts
export declare const styles: import("../../../../../../../../Users/username/tsc29-test-relaxed-resolve/packages/package-a/node_modules/styled-components").InterpolationValue[];
```

I've also tried that with TS 3.0 it's a little bit better, first file gets correct deffinitions:
```ts
// packages/package-a/dist/index.d.ts
export declare const styles: import("styled-components").InterpolationValue[];
```

But another module that imports the previous one still gets wrong definitions (even though, they look sort of reasonable, but probably the fact that package-a is inside node_modules should indicate that this is a module, i'm not sure if it's fair to assume that :) ):
```ts
export declare function getStyles(): import("../../package-a/node_modules/styled-components/typings/styled-components").InterpolationValue[];
```

In version below 2.9 we had to import those things manually and it used to work, but now we can't do it manually anymore as it has no difference...

### PR DESCRIPTION
**Pull request by weswigham**
This allows us to look at both the real and (potentially multiple) symlink paths available for a module and choose the one that gives the "best" specifier from among all of them (since a symlinked path isn't always the best one!).

In the case of the linked issue, we were finding a symlink from the other module that was symlinked into the project we were compiling, causing us to forgo both the real path (which would give us a nice global specifier) and the  project-local symlink path (which would also yield a global specifier).

Fixes #25511.

Also fixes a bug in our test harness where symlinks and json files weren't carried over into the `.d.ts` validation build, which was causing some unnecessary `.d.ts` error baselines.

### CODE REVIEW

File: tests/cases/compiler/symbolLinkDeclarationEmitModuleNamesImportRef.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+// @filename: Folder/node_modules/styled-components/typings/styled-components.d.ts
+export interface InterpolationValue {}
+// @filename: Folder/monorepo/core/index.ts
+import { styles } from "package-a";
+
+export function getStyles() {
+	return styles;
+}
+
+// @link: tests/cases/compiler/Folder/node_modules/styled-components -> tests/cases/compiler/Folder/monorepo/package-a/node_modules/styled-components
```
Comment (andy-ms) [inline tests/cases/compiler/symbolLinkDeclarationEmitModuleNamesImportRef.ts]: It looks like some tests use `@link` and some use `@symlink`, do you know why?

File: src/compiler/moduleSpecifiers.ts [hunk 2]
```diff
@@ -194,7 +194,12 @@ namespace ts.moduleSpecifiers {
         const symlinks = mapDefined(files, sf =>
             sf.resolvedModules && firstDefinedIterator(sf.resolvedModules.values(), res =>
                 res && res.resolvedFileName === importedFileName ? res.originalPath : undefined));
-        return symlinks.length === 0 ? getAllModulePathsUsingIndirectSymlinks(files, getNormalizedAbsolutePath(importedFileName, host.getCurrentDirectory ? host.getCurrentDirectory() : ""), getCanonicalFileName, host) : symlinks;
+        const cwd = host.getCurrentDirectory ? host.getCurrentDirectory() : "";
```
Comment (andy-ms) [inline src/compiler/moduleSpecifiers.ts]: I'm not sure I follow all the logic here, but there may be some duplicated effort. A few lines above this we get symlinks, then in `discoverProbableSymlinks` there is some nearly identical (copy-pasted?) code to do the same thing.

File: tests/cases/compiler/symbolLinkDeclarationEmitModuleNamesImportRef.ts (hunk 1 above)
Comment (weswigham) [reply tests/cases/compiler/symbolLinkDeclarationEmitModuleNamesImportRef.ts]: @symlink links the below file to another filepath. @link links one place (like a folder) to another - like an ntfs junction.

@link is strictly more powerful - I added it because @symlink couldn't be used to repro the issues I was seeing.

File: src/compiler/moduleSpecifiers.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/moduleSpecifiers.ts]: As far as I know, it's not duplicated at all. Here we find files whose realpath differed from their actual path, _provided those files refer to the imported file_. In `discoverProbableSymlinks`, we crawl _all_ files looking for common parts among all files with symlinks to find probable directory junction links. If I remember correctly, anyway.

**Comment by mhegazy** [comment]
@weswigham can you also port to release-3.0
