### PR TITLE
Ensure createProgram stops referencing rootNamesOrOptions to ensure oldProgram is GC'd

### LINKED ISSUE #58137: Memory Leak disposing oldProgram
### 🔎 Search Terms

memory leak

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

_No response_

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

In safari (Webkit/JavaScriptCore). Old Program never gets GCed because of reference on it.

Memory build up really quickly.

### 🙂 Expected behavior

Unreferenced and gc

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by jakebailey**
~This is practically the same as #58138, since that seems to be the only thing that works, along with some code to make `createProgram` less likely to _accidentally_ be changed such that this hack breaks something.~

~This is still 100% for sure a JSC GC bug, but I cannot find any reasonable way to fix this besides the original proposed solution.~

The parameter `rootNamesOrOptions` holds a reference to `oldProgram`; we force overwrote `oldProgram` in the local scope, but `rootNamesOrOptions` appears to stay in scope in JSC, so overwrite that too. That and `createProgramOptions` also referenced the variable, so that has to also go.

Fixes #58137

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by tmm1** [comment]
Thank you!!

I also tried several other variations and this is the only thing that seems to work. Clearly a JSC bug, but it is severe enough that a workaround is warranted.

File: src/compiler/program.ts [hunk 1]
```diff
@@ -1512,9 +1512,10 @@ export function createProgram(createProgramOptions: CreateProgramOptions): Progr
...
 export function createProgram(rootNamesOrOptions: readonly string[] | CreateProgramOptions, _options?: CompilerOptions, _host?: CompilerHost, _oldProgram?: Program, _configFileParsingDiagnostics?: readonly Diagnostic[]): Program {
-    const createProgramOptions = isArray(rootNamesOrOptions) ? createCreateProgramOptions(rootNamesOrOptions, _options!, _host, _oldProgram, _configFileParsingDiagnostics) : rootNamesOrOptions; // TODO: GH#18217
-    const { rootNames, options, configFileParsingDiagnostics, projectReferences, typeScriptVersion } = createProgramOptions;
+    let createProgramOptions = isArray(rootNamesOrOptions) ? createCreateProgramOptions(rootNamesOrOptions, _options!, _host, _oldProgram, _configFileParsingDiagnostics) : rootNamesOrOptions; // TODO: GH#18217
+    const { rootNames, options, configFileParsingDiagnostics, projectReferences, typeScriptVersion, host: createProgramOptionsHost } = createProgramOptions;
     let { oldProgram } = createProgramOptions;
+    createProgramOptions = undefined!; // Stop referencing this object to ensure GC collects it.
```
Comment (jakebailey) [inline src/compiler/program.ts:1518]: This is the new code; I am forcing this to be deleted so that any accidental new uses below will crash.

**Comment by jakebailey** [comment]
Hmmm, actually, I have an idea...

**Comment by jakebailey** [comment]
Aha, I found a more explainable fix.

**Comment by jakebailey** [comment]
@typescript-bot pack this

This fix is _way_ more explainable. I only realized it after I sent the PR.

**Comment by tmm1** [comment]
Wow nice find.

**Review by andrewbranch — APPROVED** [review]
