### PR TITLE
Lower priority for speculative variadic tuple inferences

### LINKED ISSUE #39253: TS 4.0 Variadic tuple types: type inference with optional element not working as expected
**TypeScript Version:**  4.0.0-dev.20200624 (Nightly)

**Search Terms:** variadic tuple optional element type inference

**Code**

```ts
type Foo<T extends string[]> = [...T, number?]

// These are the expected types
const v11: Foo<[]> = [] // [(number | undefined)?]
const v12: Foo<["bar"]> = ["bar"] // ["bar", (number | undefined)?]
const v13: Foo<["bar"]> = ["bar", 42] // ["bar", (number | undefined)?]

// inferring types with helper function produces different results
function foo<T extends string[]>(t: [...T, number?]): [...T, number?] { return t }
const v21 = foo([]) // (string | number | undefined)[]  //❓
const v22 = foo(["bar"]) // [(number | undefined)?]   // error,❓
const v23 = foo(["bar", 42]) // ["bar", (number | undefined)?] // ✅
```

**Expected behavior:**
The inferred types via `foo` helper function (`v21` etc.) are the same as explicitly annotated types (`v11` etc.).

I would expect the passed in array literal value in `foo` to be narrowed to a tuple type, as explained in the [PR](https://github.com/microsoft/TypeScript/pull/39094#Spreads-in-array-literals):

> When the contextual type of an array literal is a tuple type, a tuple type is inferred for the array literal. The type [...T], where T is an array-like type parameter, can conveniently be used to indicate a preference for inference of tuple types

**Actual behavior:**
Either the resulting type is an array (`v21`) or does not take the variadic type into account (`v22`), despite explicit `[...T, number?]` return type for `foo`. Also `v22` errors now.

I could live with `v21`, but shouldn't it be clear to the compiler in `v22`, that the resulting type is akin to `["bar", undefined?]`? 

**Playground Link:** 
[here](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200624&ssl=4&ssc=25&pln=4&pc=51#code/C4TwDgpgBAYg9nAPAFShAHsCA7AJgZyn2ACcBLbAcwG0BdAPigF4pqA6D5AGimwFcAtgCMIJAPy0AUJID0MqMgAWEfNACGJaMGVp0kAMZZcUUJHyT9cbMSgA3AIz2AXLASI6jFnSgWrNhwBMLvBI1ABEQhphDMysEVG0PpbWwHb2AMzBbuGRJNGecblhPAAsAYnSclAUAGai5FQm4CpQAO5k2lDKADaQJFA1fNiGZFZQYCRwuHz6LbhkNXWa2Kma+HzdwOaDw8Cj2ANuqBhYeITEDTQMABTALuycPPzCohIAlPccbNy8giLiiQA3lBNMA+CQDqkAL6+FJ2AL2WI1BDXOhvJJ+VK2AIBJEonIJN6w-wBdJ4uCo+J5UrldFAA)

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR reverts #39281 and #39614 and instead implements the originally envisioned solution of giving higher priority to inferences made to `[...T, X]` than inferences made to `[...T, X?]` (because the latter speculates that the optional element is present). For example:

```ts
declare function ft<T extends unknown[]>(t1: [...T], t2: [...T, number?]): T;

ft([1, 2, 3], [1, 2, 3]);  // [1, 2, 3]
ft([1, 2], [1, 2, 3]);  // [1, 2]
ft(['a', 'b'], ['c', 'd']);  // ['a', 'b']
ft(['a', 'b'], ['c', 'd', 42]);  // ['a', 'b']
```

Fixes #39253.

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -5424,15 +5424,16 @@ namespace ts {
...
-        HomomorphicMappedType        = 1 << 1,  // Reverse inference for homomorphic mapped type
-        PartialHomomorphicMappedType = 1 << 2,  // Partial reverse inference for homomorphic mapped type
-        MappedTypeConstraint         = 1 << 3,  // Reverse inference for mapped type
-        ContravariantConditional     = 1 << 4,  // Conditional type in contravariant position
-        ReturnType                   = 1 << 5,  // Inference made from return type of generic function
-        LiteralKeyof                 = 1 << 6,  // Inference made from a string literal to a keyof T
-        NoConstraints                = 1 << 7,  // Don't infer from constraints of instantiable types
-        AlwaysStrict                 = 1 << 8,  // Always use strict rules for contravariant inferences
-        MaxValue                     = 1 << 9,  // Seed for inference priority tracking
+        SpeculativeTuple             = 1 << 1,  // Speculative tuple inference
```
Comment (DanielRosenwasser) [inline src/compiler/types.ts:5427]: I think without the explanation, this is unclear.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -19819,7 +19819,10 @@ namespace ts {
                                 }
                                 else if (middleLength === 1 && elementFlags[startLength] & ElementFlags.Variadic) {
                                     // Middle of target is exactly one variadic element. Infer the slice between the fixed parts in the source.
-                                    inferFromTypes(isTupleType(source) ? sliceTupleType(source, startLength, sourceEndLength) : createArrayType(sourceRestType!), elementTypes[startLength]);
+                                    // If target ends in optional element(s), make a lower priority a speculative inference.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:19822]: If the documentation is going to be sparse on `SpeculativeTuple`, I think showing a concrete example here is worthwhile. Your explanation on the PR would be great.
