### PR TITLE
Fixed an issue with contextual type for intersection properties (take 2)

### LINKED ISSUE #48812: Contextual type can't be provided to a mapped type intersected with an object type
# Bug Report

### 🔎 Search Terms

intersection, mapped type, contextual type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAggxsAlgewHYB4AqBRAbhVYKCAD2AIBMBnKAbylEgC4orgAnRVAcygF8AfFAC8UABQRcLHPkIBKEUNzJEFANwAoDV3LsAZgEM40ALJGAFlwgBhNHsTcseAkVLlU1Og3AQWbTjz8QrQaUKxw5hAAtgYsIWFhki5U0s6EmmF8GVBoAPxxoQkA2gDSUFxQMi5FAESMEDUAuo35sAgoGFWExGSUNPT1LGV8ULmVaUQsqEnsAtkjAGR0hWE1AFQ1rfBIaE6ywHOFWRp8WhQQcAA2BuzQegCuqO1oUHC3BuRmEVZ7Lj3ungGPj8HC4vEEYkKcDsDhYX0s01sqHsji6Bw0chYylUmg0bwgHwg8KsYni4UiMQKCWI+xSdBGBn63mYUBqADEAPIcmr8KAAHy8g1ZACEYAAlHl8AA0RxlYTQVISnI5LAkuAUwmCKwSkgAdPU1FAAPRG1jmZD3S4UKAAI2gAHJlfbtdLZSc5JogA)

### 💻 Code

```ts
type Action<TEvent extends { type: string }> = (ev: TEvent) => void;

interface MachineConfig<TEvent extends { type: string }> {
  schema: {
    events: TEvent;
  };
  on?: {
    [K in TEvent["type"]]?: Action<TEvent extends { type: K } ? TEvent : never>;
  } & {
    "*"?: Action<TEvent>;
  };
}

declare function createMachine<TEvent extends { type: string }>(
  config: MachineConfig<TEvent>
): void;

createMachine({
  schema: {
    events: {} as { type: "FOO" } | { type: "BAR" },
  },
  on: {
    FOO: (ev) => {
      ev.type; // should be 'FOO', but `ev` is typed implicitly as `any`
    },
  },
});

```

### 🙁 Actual behavior

An implicit any pop-ups when the contextual type could be, somewhat easily, provided.

### 🙂 Expected behavior

This should just work 😜 I know a workaround for this issue - the workaround is to use a single mapped type instead of an intersection and just "dispatch" to the correct value in the template~ part of the mapped type, like [here](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAggxsAlgewHYB4AqBRAbhVYKCAD2AIBMBnKAbylEgC4orgAnRVAcygF8AfFAC8UABQRcLHPkIBKEUNzJEFANwAoDV3LsAZgEM40ALJGAFlwgBhNHsTcseAkVLlU1Og3AQWbTjz8QrQaUKxw5hAAtgYsIWFhki5U0s6EmmF8GVBoAPxxoQkA2gDSUFxQMi5FAESMEDUAulAAPlA1AFRN+VBlbpQ0nTWFCVC5sAgoGFWEAiMJLPBIaE6yrmQDXvUsZXxjlWlELKhJ7ALZWRp8WhQQcAA2BuzQegCuqJNoUHDPBuRmESsqxcxA2Hho9G2rA4XF4gjEhTgdgcLABlhOtlQ9kcM2AczkLGUqk0Gh+ED+EDRVjE8XCkRiBVGSUIKToewMEO8zHaADEAPJ8mr8VpbHwsGoAIRgACUhXwADSFBWFNCMhL8vksCS4BTCYLzRK4AB09TUUAA9ObykREDQNQBCebKzKKvhyTRAA). However, this is way less ergonomic than an intersection AND the mapped type is no longer homomorphic which could matter for some cases (well, the original mapped type here is not homomorphic either, but it could be)

I already have a draft PR open to fix this issue, [here](https://github.com/microsoft/TypeScript/pull/48668). I only need some help with the stuff mentioned in the comment [here](https://github.com/microsoft/TypeScript/pull/48668#discussion_r849531475)

### LINKED ISSUE #55150: Contextual property type from a mapped type fails to be provided in JSX
# Bug Report

### 🔎 Search Terms

contextual type property mapped type inference jsx

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230720#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkiTAApQRgDOA6sDABbIBm2AogDZIjkYAFQCeYJHAC+cdjRBwARFFQYFAbgBQG9gFcSGYKTgBVEgHcoKMOIAmAGWAkA1gB4hcJAA8Y5G3Ti8-IKi4nAAvAF8AhQhSAB8ABQacHBgNPQAXHAA8iDMLoTEZBTUtIzMbEjsLoHRwmISXj4kfnDuAPyKKApwWUJx2AoodApxGgCUuMlwyjA6UCRwLihxLgD0K5qSWqYWVrYOzgk406T4PMBoTlkJSJNhcVMpKWtrz88Aeu3TkpgakuNNBoXLtLNYkPZHE5TiRzpcnGEcLd7o8Tu9Xu8Ul8fts1nFNEA)

### 💻 Code

```ts
import React, { ComponentPropsWithRef, ElementType } from "react";

function UnwrappedLink<T extends ElementType = ElementType>(
  props: Omit<ComponentPropsWithRef<ElementType extends T ? "a" : T>, "as">
) {
  return <a></a>;
}

UnwrappedLink({
  onClick: (e) => {
    //      ^? (parameter) e: React.MouseEvent<HTMLAnchorElement, MouseEvent>
  },
});

<UnwrappedLink
  onClick={(e) => {
    //      ^? (parameter) e: any
  }}
/>;

```

### 🙁 Actual behavior

Contextual signature for `onClick` fails to be computed here when using JSX but it works just fine with a regular function call.

The problem here is that the contextual type of JSX attributes is an intersection as it includes `IntrinsicAttributes`. Because of that `getTypeOfPropertyOfContextualType` fails to call `substituteIndexedMappedType` appropriately - this is something that is being already fixed by https://github.com/microsoft/TypeScript/pull/52095

### 🙂 Expected behavior

Since JSX is roughly meant to be a sugar for function calls both of those should behave the same way.

### LINKED ISSUE #59473: Literal inference causes unexpected errors on a values that trivially satisfy compound type intersections containing any
### 🔎 Search Terms

object intersection literal inference any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about intersections and inference

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSB6CuGAC2AGc41ckntc4UA7OCAGwAmcAG5IoDYBF4RMcALIBVAJKkYATzBI4AIQgAPAAo4wTALxwA3qThwQ-APwAuLt3VwqcZXEHBB3fHgiFH5gAC9tOkYaTW0AdxQmHnVSAF9yTwAVeiZBCDYA+AYAVzQ0NgZMYv5+dwgxKCg-SNptMBNxDRitV2FvNB44TGB9OGAYADpKah1i+DptcRwoOwqUAHMW6IHihiRhBKYWbirJbnXeuG4kfaZQdvqkECRuGDVYhXVjCFM4Cz0jCYmAAyKw2OyOFz4fabfBwAA+V2KIAARuI0uRjgx4PJ1ABhXBgP5wAAUD1MLlx31MAEo-gA+JE1cgaHqZYlUoEAbXw9nwAF0PNRkpjpNi4KMLAAeXEE8AQswAIhhSEVHkZWViTFkcHJnXcvP4cJQRDG3BY4BQMGAKP4SCmtk1PXw2Ka5zh0W4EHgiUk624KFtkQg3W0+G4yLRK0RysEmzViOK3EESGG10E+AmJIATABmbPZmkZagAdXoaFoYzuMActmUTAABvYXMkG3wVtFxnAGxHUeIEXBY-GB0mU2n9g2HEA

### 💻 Code

**EDIT**: simplified examples:

```ts
const a: [any] & [1] = [1] // Type '[number]' is not assignable to type '[1]'
const b: { ml: any } & { ml: 'edge' } = { ml: 'edge' } // Type '{ ml: string; }' is not assignable to type '{ ml: any; } & { ml: "edge"; }'
```

Original example:

```ts
import React from 'react'

// this comes from an old version of MUI
type BoxProps = {
  ml?: any // I didn't realize this type was any
}

// This doesn't successfully override the property type and I can fix it.
// But the error message this caused was nonsensical and needs improvement
type MyProps = BoxProps & {
  ml?: 'edge' | number
}

const MyComp = (props: MyProps) => null

type T = MyProps['ml'] // any

const x = <MyComp ml="edge" /> // Types of property 'ml' are incompatible.
  // Type 'string' is not assignable to type 'number | "edge" | undefined'.(2322)

// Which is it?  Is `ml: any` or is it `number | "edge" | undefined`?
```

### 🙁 Actual behavior
```
Type '{ ml: string; }' is not assignable to type '{ ml?: number | "edge" | undefined; }'.
  Types of property 'ml' are incompatible.
    Type 'string' is not assignable to type 'number | "edge" | undefined'.(2322)
```
### 🙂 Expected behavior

No error and no difference in the reported type for the `ml` property in JSX and `MyProps['ml']`

### Additional information about the issue

I hope that literal inference can be improved to handle this case without an error:
```ts
const x: { ml: any } & { ml: 'edge' } = { ml: 'edge' }
```
Two potential solutions I proposed below are:
1. Run a separate literal inference on each half of the required intersection type, then intersect the inferred types
2. Fall back to unwidened type if it satisfies the required type but literal inference doesn't

### PR DESCRIPTION
**Pull request by Andarist**
fixes #48812
fixes #55150
fixes #59473

This PR is another take on what already has been approved and merged: https://github.com/microsoft/TypeScript/pull/48668 . It later got [reverted](https://github.com/microsoft/TypeScript/pull/50279) to give time for further investigation of https://github.com/microsoft/TypeScript/issues/49307 since that PR broke Redux Toolkit's types.

This PR adds **adjusted** test cases that were discovered in #49307. [The minimal repro](https://github.com/microsoft/TypeScript/issues/49307#issuecomment-1196014488) case posted by @andrewbranch was this:
```ts
type Validate<T> = T & { [K in keyof T]: object }
declare function f<S, T extends Record<string, (state: S) => any>>(s: S, x: Validate<T>): void;

f(0, {
  foo: s => s + 1, // contextual type for `s` provided, no implicit any reported
})
```

I decided to treat indexed mapped type substitutions within intersections differently. Now they are intersected with either concrete property types or with applicable index info types. 

They are not treated as "concrete" - so they don't take precedence over applicable index info types. They are always uses, if we find any concrete property types then we intersect them with those. If we don't have any concrete property types then we find applicable index info types and we intersect with those.

Usually, concrete properties take precedence over index signatures. Through experimentation (and thanks to user/topXXX tests 😉 ), I found out that generic mapped type substitutions are neither. They can resolve to both and while they are generic we can't tell how "important" they are (if they should take precedence over index signatures or not, etc). 

With coherent types, concrete properties should always be compatible with index signatures. So if we think about it, even sourcing the contextual property type from all intersection constituents and intersecting those results should be OK. And from that PoV, intersecting those mapped type substitutions with either concrete properties or applicable index infos is still OK (since we should be able to just intersect all 3 categories together).

If we intersect all of the categories we fail [this test case](https://github.com/microsoft/TypeScript/blob/8daac14aa4e4ab5b6426bc9f1ac88ff50104981b/tests/cases/compiler/contextualTypeShouldBeLiteral.ts#L98-L122) with [this error](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgCoQM5gPICMBWECYyA3gFDLJgCeADhAPwBcyA5APYFFhsDclZMEgBbDKwpUqAbQDWrLFFABzALqt0WAOIQQ0YAgFUAvgOPlyoSLEQpNYAMpglIZWUG0GrNopX9y5uSedphgOnpKCMgAvMgAFPZOLm4APmiheITEAJTIAGRkyHIKzirqyHAgNHzIphYIHCBY1KEaoeH6UbEUAPQ9UsgAfsOD5H3IAIRTyNBQHFBoDgBMAMxLSxr0KGykQqLihQAWEAA2JxwS1FslyTWmyADu8ycAJpfCEGKXelgQb4XBG4qO4g2qg4xsIQYZAgDgkOAYDDAZQgOC4E4oMAcK4Mdj2DqRNgAOjG-SmExmUDmC1QyzWGykqC27F2Hy+R1O50ugOQvlcoKeUFe73231Cf25115pX5YLl9wVkOA0Nh8MRyNR6Mx2OCeNCSRU+UKxWlyXKlWqtWJpMm01m80Wq3WrAGAAU5gwoLR2MEldCRMqka4hCAcdtWaKOWcLgCpXzlALnv8I58DrsfpBk2GgbKFeC7pDcABXEhQCAARyLwDLLxDYb1WANrmt43JyDLJzgmcdAHYlgAOZANcAQAAeYCLcBOTIYDkOHCLrwAQhAADIfKBTolgcQARgADD3mCtvL6ocgXkROzXkMcyySqGy04IqMdo5KvOx45DjAAaF+PEmEgAY+kaSAMUgZhKsafj4MrKD+IG1AB5gmAEfBAA). This happens because the index signature there (`{ [k: string]: any; }`) spoils the result - `any` is contagious. A simple solution to that is to... discard `any`. it doesn't provide any new information for the contextual type and any type that results from other "hints" will be compatible with it. 

This particular issue is even manifested in much simpler scenarios, like the ones reported in #59473: 
```ts
// Type '{ prop: string; }' is not assignable to type '{ prop: "foo"; } & { prop: any; }'.
const test: { prop: "foo" } & { prop: any } = { prop: "foo" };
```

There is an extra complication with the generic mapped type substitutions. At times, a property might be filtered out by a generic `Omit` or similar. This isn't a new problem and we can see it at play without intersections [here](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240730#code/C4TwDgpgBAkgdsATgSzgZ2QYwKIBsIC2ECaUAvFAN4BQUUAJsgG4BcVtdUA9nAMIAWAQzgBzCGwAUEVlGxNiwAJTkAfFCZdk9ANwcAvrrpowwtjU7c+Q0eKhSZchcrJqNWw1APUv1UJFn4RAgAKuDQFADWECBcAGawCCjoWHiECmi61PjAUAAi2ABiAIIAqgAywQD6wUUAQgDK1UUA4uRQAESMTO1QgqSYPGjAmX7QAAqIXGBoADzBwYIiUBAAHsDE9KSpQcChkAA0UADy8ogo9BCkFJR6ahRHBMjAMxzwSKgYOIHpANrziwBdfYcKIxeInCBnLSXagqagAenhdAAZMdTudLiMwlAFgAjZqTACuYAmU1m-yWq3WcE2ATSIWxFFGcTyhVKFSaDSazTuUFJ0xedApwLo5k4PAEwjEAH5JKgLis2HBCQRcZDnK5NDp9LDMqh1ohYoJMNBKvrIXBBLhKrwuAQwDwFHiCVxiew6HMFpS1hstt8Gf4mWEWfliuUqjUuTUeRIOHQwJNpmxnUSSYnyV6VCKoIolYTcLhdHpqNQLphcIJENBsjjBPjU2wzQgLVabXaHXAnXWXcTMinXWAJGKJdYxHKaasNe7OIioAB3fiQ6DIUjARdQAAG8tWG6go2W8jgUAGj1EUFikwIUDgXDn0rjUFnTygaH4rtw9Cgat6R+Q9twWDPsIIAPgM6A5MgeaqpCbTbisHh6MCeiKLoQA). This example isn't wrong per se since the resulting type is still compatible with the constraint and all. It's just moderately surprising that the contextual parameter type was assigned to this parameter.

Previously, this wasn't a problem as `substituteIndexedMappedType` was not called within intersections. It becomes a bigger problem now since for some properties we shouldn't use indexed mapped type substitutions - they could spoil the overall result if we intersect something that shouldn't be there with some other type that should be there and that was meant to "shadow" over the the one provided by an `Omit`ting mapped type.

Negated types aren't a thing in TS, but we can still prove that some properties are filtered out by mapped type constraints that are conditional types with `never` true type and properties assignable to their `extendsType`. 

And last but not least, we need to exclude index info types when a concrete property type is found in any constituent. The previous version of the code used resolved structured members so intersections members were resolved and concrete properties were correctly "shadowing over" index infos. Without it, we'd break this:
```ts
const test: { prop: (arg: number) => void } & {
  [k: string]: (arg: any) => void;
} = {
  prop: (arg) => {
    arg; // number
  },
};
```

That's why all of this requires custom intersection handling and a two-pass iteration through those constituents.

TLDR requirements:
- all intersection constituent types should contribute to contextual typing, so all contained mapped types can potentially go through `substituteIndexedMappedType`
- in presence of concrete properties index info types should not be used (including when they are contained in different constituent types)
- `any` has to be remapped to `unknown` as otherwise it spoils results given `T & any // any`
- `Omit`-like generic mapped types should be skipped when it's provable that a certain property is meant to be omitted by them

cc @andrewbranch @RyanCavanaugh @phryneas @markerikson

### CODE REVIEW

**Comment by fatcerberus** [comment]
> At the moment RTK uses an index signature for their SliceCaseReducers type ([here](https://github.com/reduxjs/redux-toolkit/blob/6a7879f26e0337fc3a1c33adea16c89f9dee0953/packages/toolkit/src/createSlice.ts#L164-L168)) and this PR breaks that. @andrewbranch has reasonable doubts (starting from https://github.com/microsoft/TypeScript/issues/49307#issuecomment-1176562527) if that should ever work.

From experience with the larger TS community, I can say with some confidence that `IndexSignature & SpecificProps` is a *very* common workaround in the wild for https://github.com/microsoft/TypeScript/issues/17867.  I have to grit my teeth every time I encounter it and have actively tried to steer people away from it, but most people tend to insist they need it anyway despite the footguns.  So any change to the behavior of that pattern is likely to break people, unfortunately.

**Comment by phryneas** [comment]
> Also aren't `Record<string, T>` and `{ [x: string]: T }` the exact same type?

One is `{ [K in string]: T }` and the other is `{ [x: string]: T }` - while they describe the same thing (in the case of the full `string` type, but not in any other case), they have always behaved differently.

**Comment by fatcerberus** [comment]
@phryneas Hmm, if they behave differently then that makes this rather misleading:
image

**Comment by phryneas** [comment]
That indeed seems to be a bit misleading. The definition of `Record` definitely uses a mapped type though.

```ts
type Record<K extends keyof any, T> = {
    [P in K]: T;
};
```

**Comment by fatcerberus** [comment]
Yeah, I was aware that was the implementation.  I just thought that `{ [K in string]: T }` automatically reduced to an index signature, thanks mostly to the above tooltip.

@matheusiacono I'm... not sure why you 👎'd my comment?  That the hover tip displays an index signature when the actual type behaves differently from what's displayed is factual and not just my opinion.

**Comment by Andarist** [comment]
> From experience with the larger TS community, I can say with some confidence that IndexSignature & SpecificProps is a very common workaround in the wild for https://github.com/microsoft/TypeScript/issues/17867 (as a matter of fact, it's the very first reply in that issue!). I have to grit my teeth every time I encounter it and have actively tried to steer people away from it, but most people tend to insist they need it anyway despite the footguns. So any change to the behavior of that pattern is likely to break people, unfortunately.

Note that this PR doesn't necessarily have to break patterns like this. It's hard to tell though - I would have to examine a concrete example, with a concrete use case in mind (contextual typing, completions, etc).

As to the difference between `Record<string, T>` and `{ [x: string]: T }`. Those are 2 different types, type displays can sometimes be confusing like that - but TS at times tracks how a given type originated and might utilize this information. For example `PlainFormFields` and `MappedFormFields` display exactly the same [here](https://www.typescriptlang.org/play?ssl=28&ssc=6&pln=28&pc=22#code/C4TwDgpgBACgNgQwJYDsBiB7ATgWzUiOAEwGcoBeKKAbwCgBIBAcwgC4aH6A3BOAVzZQUfHACMIWADScecJEQTBs7ABSz2wsRICUFAHxRRGDHAgIUDAL7T6KBDkF163XgPYlgWVExsu5CpSxVdSgPLxQmXXIDIxMzC3pLWiTaADM+FABjYCQMFChZeUUIeGQUAB4AaSgIAA9gCBRSKABrCBAMVNhEVExcfEJSPRU2kHZKyShU7BwSdlLemYHiEl06KmncEgBtUYBdADpCgOwVTdnd9sPZAW1k2lpQSCgAWRAXhDAKDipmQU1xFJaFQ7A53J5vPdHuBoAAlCA4T7lAAqBko6yg22qqFa7U6UGRe3YGKoN0EyKxe2kVFJvCKgWCvHYFMqeyiMWMpnMwKgSRST2gHzAkCIfTwBBW33hiLA5TeQr0tAA9EqaQA9AD8D3SWRyeQKdICECFIqqNXqjWao3xJogoqWEqGI3a40m5zmr0+IrFy1Iax57suIGuhsUp0D+yOrggd0sQA) but yet they behave differently.

It's helpful to check out the TS AST Viewer and the flags contained on those types (link [here](https://ts-ast-viewer.com/#code/C4TwDgpgBAglC8UDeUDaBrCIBcUDOwATgJYB2A5gLq6kCuAtgEYSFQC+AUKJFAEIJQAShADGAe0IATADwESFADRQ6TFgD4u4aAGEBKVAGkoZfETJUaDZqzZA)). Also note that their types have different IDs - which is the ultimate no answer to the question if they are the same.
```ts
// flags: Object (2 ^ 19) | DefinitelyNonNullable | StructuredType | StructuredOrInstantiable | ObjectFlagsType | Narrowable | IncludesMask | NotPrimitiveUnion
// objectFlags: Anonymous (2 ^ 4) | ObjectTypeKindMask
type A = { [key: string]: number }
// flags: Object (2 ^ 19) | DefinitelyNonNullable | StructuredType | StructuredOrInstantiable | ObjectFlagsType | Narrowable | IncludesMask | NotPrimitiveUnion
// objectFlags: Mapped (2 ^ 5) | Instantiated (2 ^ 6) | CouldContainTypeVariablesComputed (2 ^ 19) | CouldContainTypeVariables (2 ^ 20) | ObjectTypeKindMask
type B = Record<string, number>
// flags: Object (2 ^ 19) | DefinitelyNonNullable | StructuredType | StructuredOrInstantiable | ObjectFlagsType | Narrowable | IncludesMask | NotPrimitiveUnion
// objectFlags: Mapped (2 ^ 5) | ObjectTypeKindMask
type C = { [K in string]: number }
```

We might notice here that all of them have the same flags but they are all different when it comes to `objectFlags`. `B` and `C` are roughly the same though, `B` just have some extra `objectFlags` since it's coming from an instantiated type alias.

That being said - I can't be sure if the proposed change is how this whole fix should look like. It's a conversation starter, maybe I will have to tweak this based on the TS team feedback.

**Comment by andrewbranch** [comment]
Does this PR _create_ an observable difference between `Record<string, T>` and `{ [x: string]: T }` or did you just discover an existing one that lets you work around the other effects of the PR?

**Comment by Andarist** [comment]
@andrewbranch it creates an observable difference in getting the type of the property of a contextual type. Some of the the new test cases wouldn't infer correctly with the generic constraint of `{ [x: string]: T }` but they infer OK with `Record<string, T>`. You could change the definition of this [`SliceCaseReducers`](https://github.com/microsoft/TypeScript/blob/6bb681ef2c60f7c2d8988693c96efc7f28a1286f/tests/cases/compiler/contextualTypeFunctionObjectPropertyIntersection.ts#L57) back and forth to observe the difference

**However**, I'm not saying - by any means - that this is what I want to land. This whole PR is meant to restart the conversation around this since the original PR landed and got reverted later. 

When discussing the regression in https://github.com/microsoft/TypeScript/issues/49307, both you and @RyanCavanaugh said that the original PR had merit and that contextual properties coming from index signatures are dubious (when a concrete property is available) and that cases like this were handled inconsistently by TS. The original PR was reverted to give you more time to think about this - it has been half a year and I just hope to revive this conversation.

There are some important things to note down here - we don't need to create any observable difference between both of those. This is **not** required to fix what this PR is fixing.

So to move this PR forward we can either:
1. ignore index signatures in presence of concrete properties. This would likely reintroduce the regression from #49307. It's even possible that wouldn't necessarily be a bad thing (I'm not super clear on that though) but it's unknown to me how RTK could rewrite their types today to fix their types. I proposed a solution [here](https://github.com/microsoft/TypeScript/issues/49307#issuecomment-1212585148) but it was dismissed because it doesn't work in older TS versions. I just rechecked this playground and it seems that it doesn't work on TS 3.5 (!) but it already works with TS 3.6. IMHO, at this point, this is a fair game for RTK to break compat with TS 3.5 if they don't want to hussle with the `typesVersions` complexity. Of course, this doesn't even mean that this solution would work for them - as I only validated it with that slimmed down repro. I just created [a PR to RTK with this change](https://github.com/reduxjs/redux-toolkit/pull/3097) to check out the CI results. It also doesn't necessarily mean that their current types shouldn't work - they are certainly unusual but maybe they don't abuse the implementation and are aligned with TS design. That's something that the TS team would have to decide on.
2. never ignore those index signatures. This PR would still fix what it is fixing. I just didn't do it because you had doubts about index signatures behavior in https://github.com/microsoft/TypeScript/issues/49307
3. use a mixed approach - but I'm not sure what exact heuristics should be used. Perhaps we should check if the contextual type is part of the generic constraint? If it is - then it would make sense to use its "index signature", when the contextual type would be concrete then the index signature could be ignored. I'm not sure what the exact condition for such a check would be preferred but I could experiment with something if you decide that this is what your team wants to have implemented.

**Comment by markerikson** [comment]
For the record we already only support TS 4.2+ as of RTK 1.9.

**Comment by Andarist** [comment]
Your CI job just reported that the proposed solution doesn't work for you 🤣 it seems that there is more to this there than what was captured by the slimmed-down repro

**Comment by Andarist** [comment]
@andrewbranch @RyanCavanaugh would there be a chance to put this on 5.2 agenda since the work on that has just started? I would gladly tweak the content of this PR however you see fit - but right now it's not entirely obvious how this should behave when index signatures are involved. This probably warrants a design meeting or something.

**Comment by Andarist** [comment]
To get the ball rolling I made some changes to this PR. I decided to treat indexed mapped type substitutions within intersections differently. Now they are intersected with either concrete property types or with applicable index info types. 

They are not treated as "concrete" - so they don't take precedence over applicable index info types. They are always used though, if we find any concrete property types then we intersect them with those. If we don't have any concrete property types then we find applicable index info types and we intersect with those.

It is somewhat strange... but it maintains backward compatibility.

**Comment by Andarist** [comment]
@ahejlsberg @gabritto friendly 🏓

**Comment by Andarist** [comment]
@jakebailey would u mind creating a playground for this one?

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by Andarist** [comment]
@ahejlsberg @gabritto @RyanCavanaugh any chance that this could be considered for 5.5? It fixes one of the "Help wanted" issues - let me help you! 😉

**Comment by Andarist** [comment]
5.6 development has begun...

Bernie sanders meme saying 'I am once again asking you humbly for a review'

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by gabritto** [comment]
@typescript-bot test top800

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by Andarist** [comment]
@jakebailey @gabritto I'd appreciate a user tests + top 800 rerun here :)

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by Andarist** [comment]
The latest simplification revealed new issues in the extended tests. I went back to my previous approach and added more tests. Could I ask for a rerun? :)

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by Andarist** [comment]
The break above seems to be related to how contextual `any` is eliminated from intersections here. On `main` contextual `this` gets reduced to `any` (see the TS playground [here](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240803#code/C4TwDgpgBAwg9gWzAV2BAJgcQsNAnAHgBUA+KAXigAo4AbdANQENbkIB+ALiiIEoKyRANwAoUJFiIUadAHkwwAJZwAdgGcKUAEoQAxnDzoCa4HkUqA5gBpJSVBmy4IhJipAkSoseGgBRAB6mTLrA8HYyOsDIeOrEUBCBECroGq7umgDeIlBQANoA1hAgUOZQhSBwAGY8ALrcRAVFNfGJyRpUAHRdTHgWatxpuTX85GTmlc48kdEq2TlQ7FM4M3M53CoQAG7OogC+Xub4lcHQYWCqScDySqpqAEJMahAEACI2MC1obbbSGNfK6jIWRy6CYwCYXCgL1EOX04QwkJgexE3gkZwuKmAAAVkAAjWiKXQASXU4JUumeL0yu3enySKR+9jkCgBGkoGV2ZEoVIAZHMAkEQmcmdMYmoCDBPCjxKcpBirizbgQ5lTKGkrHMPgkvgzhTJ-rdNOqRFyfvKDeoHk9Xu8yDyeAALRRqIg+CVyjaYnH4wkkkyuCk22AeA6Y5zHClQACCYDAUGBUAQin85ioSZTKm46M9Cpu6l43GATrUyJEh3DJygJIAVno8wBpIrEMja+kaADKIAQuLo8d2KPLeAj0B0lWb8bmAH1NvVS+g9LQetBKshyXmoHgIMElNs4q3vnBcbWQiQqODejh6gXtBAx6RQ0dK0QHRAEBA-WTIwnN0x0KpaMUKhMG+3A6L+-4gAQo7GKY5gWCGIj9iI866Ium5QPopKOq+ECdt2dDcDWdYAo2kHPjhH4BhAUrIQuS5QCua4AiUKjHsAVBzEWzpZh6lzegSxKklRGo5OUhGscRqikQQaRkAAPlAJhmJYGrXmkXgoWh0CYSYUBMLG3AxmAoj6WAHTpqmCZwr86DcAmOQACSbGwSiVCAVD8PZ8xcSWUAAPR+XpbirPMm5RDEG5biEijbFQXnzFARY4dw5hsR0ugsLQZ7FjY5FvnhPa0LwIkJVAuy8DC8w0nM1XlV4CTnHgwB9qIQA)) and it doesn't happen with the code in this PR.

`this` is a contextual *parameter* and regular contextual parameters are not ignoring `any` so it also shouldn't be ignored for `this`. I'll fix this soon.

**Comment by Andarist** [comment]
@jakebailey would you be so kind to rerun the tests? :)

**Comment by jakebailey** [comment]
@typescript-bot test it

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -31577,33 +31577,103 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return !!(getCheckFlags(symbol) & CheckFlags.Mapped && !(symbol as MappedSymbol).links.type && findResolutionCycleStartIndex(symbol, TypeSystemPropertyName.Type) >= 0);
     }
 
+    function isFilteredOutMappedPropertyName(constraint: Type, propertyNameType: Type): boolean {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:31580]: I think a better name would be `isExcludedMappedPropertyName`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -31577,33 +31577,103 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return !!(getCheckFlags(symbol) & CheckFlags.Mapped && !(symbol as MappedSymbol).links.type && findResolutionCycleStartIndex(symbol, TypeSystemPropertyName.Type) >= 0);
     }
 
+    function isFilteredOutMappedPropertyName(constraint: Type, propertyNameType: Type): boolean {
+        if (constraint.flags & TypeFlags.Conditional) {
+            return !!(getReducedType(getTrueTypeFromConditionalType(constraint as ConditionalType)).flags & TypeFlags.Never) && isTypeAssignableTo(propertyNameType, (constraint as ConditionalType).extendsType);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:31582]: To correctly identify instantiations of `Exclude`-like types, I think you also need to ensure that the check type is the same as the type parameter of the containing mapped type. Currently it looks like the check type could be anything.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -31577,33 +31577,103 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
-                        return restType;
+                if (indexInfoCandidates) {
+                    for (const candidate of indexInfoCandidates) {
+                        const indexInfoType = getTypeFromIndexInfosOfContextualType(candidate, name, nameType);
+                        types = appendContextualPropertyTypeConsitutent(types, indexInfoType);
                     }
                 }
-                return findApplicableIndexInfo(getIndexInfosOfStructuredType(t), nameType || getStringLiteralType(unescapeLeadingUnderscores(name)))?.type;
+                if (!types) {
+                    return unknownType;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:31623]: This means we'll _always_ return a contextual type and never return `undefined`. I think it would be better to just map `any` to `unknown` when it occurs as an intersection constituent so that we still return `undefined` in cases where no match was found.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -31577,33 +31577,103 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            return isGenericMappedType(t) && !t.declaration.nameType
+                ? getIndexedMappedTypeSubstitutedTypeOfContextualType(t, name, nameType)
+                : getTypeOfConcretePropertyOfContextualType(t, name) ?? getTypeFromIndexInfosOfContextualType(t, name, nameType);
         }, /*noReductions*/ true);
     }
 
+    function appendContextualPropertyTypeConsitutent(types: Type[] | undefined, type: Type | undefined) {
+        // any doesn't provide any contextual information but could spoil the overall result by nullifying contextual information provided by other intersection constituents
+        // at the same time, all types computed based on the contextual information provided by other consistuents are still assignable to any
+        return isTypeAny(type) ? types : append(types, type);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:31642]: Change to `return type ? append(types, type.flags & TypeFlags.Any ? unknownType : type) : types;`.

**Review by ahejlsberg — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -31579,7 +31579,10 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
 
     function isExcludedMappedPropertyName(constraint: Type, propertyNameType: Type): boolean {
         if (constraint.flags & TypeFlags.Conditional) {
-            return !!(getReducedType(getTrueTypeFromConditionalType(constraint as ConditionalType)).flags & TypeFlags.Never) && isTypeAssignableTo(propertyNameType, (constraint as ConditionalType).extendsType);
+            const type = constraint as ConditionalType;
+            return !!(getReducedType(getTrueTypeFromConditionalType(type)).flags & TypeFlags.Never) &&
+                isTypeAssignableTo(getFalseTypeFromConditionalType(type), type.checkType) &&
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:31584]: Actually, I think you want to check `===` here.

Comment (Andarist) [reply src/compiler/checker.ts:31584]: I thought about it but then some weird conditionals like this one don't seem to break the rule. Or do they? 😅 
```ts
T extends "bar" ? never : T & ExtraFilter
```

Comment (ahejlsberg) [reply src/compiler/checker.ts:31584]: We have similar code in `getSimplifiedConditionalType` and there we check for identity. I'd prefer that.

Comment (Andarist) [reply src/compiler/checker.ts:31584]: Ok, I pushed out a change that uses similar code to the one in `getSimplifiedConditionalType`

**Comment by ahejlsberg** [comment]
@typescript-bot test it

**Review by ahejlsberg — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot test it
@typescript-bot pack this

**Review by gabritto — APPROVED** [review]
