### PR TITLE
[Master] Fix 13893: Fix runtime crash when class is used before declaration

### LINKED ISSUE #13893: Runtime crash because wrong order of definitions is not detected
**TypeScript Version:**  2.1.5
**Code**

```ts
export const bar = new Foo()

export class Foo {
}
```

**Expected behavior:**

Either a compilation error is thrown or working code is generated

**Actual behavior:**

The following code is generated:

```js
"use strict";
exports.bar = new Foo();
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
```

It fails at runtime both in Edge and Node because `var Foo` is not yet defined.

### PR DESCRIPTION
**Pull request by yuit**
Fix #13893 

- [x] This issue #11935 is in similar area as well but for enum. I am going to handle it here

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1056,9 +1056,10 @@ namespace ts {
                 // block-scoped variable and namespace module. However, only when we
                 // try to resolve name in /*1*/ which is used in variable position,
                 // we want to check for block-scoped
-                if (meaning & SymbolFlags.BlockScopedVariable) {
+                if (meaning & SymbolFlags.BlockScopedVariable ||
+                    ((meaning & SymbolFlags.Class || meaning & SymbolFlags.Enum) && (meaning & SymbolFlags.Value) === SymbolFlags.Value)) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: `(meaning & SymbolFlags.Value)` instead of `(meaning & SymbolFlags.Value) === SymbolFlags.Value`

Comment (yuit) [inline src/compiler/checker.ts]: We have to check that the meaning flag is strictly looking for symbolFlags.value because other we will also issue an error when used in type location as well

Comment (mhegazy) [inline src/compiler/checker.ts]: U are correct. Sorry about that.
