### PR TITLE
Avoid circularly resolving names when looking up type members using resolveName

### LINKED ISSUE #23828: Unnecessary reference checks with ambient classes (regression)
cc @weswigham 

**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
// index.d.ts
export class C extends Object {
  static readonly p: unique symbol;
  [C.p](): void;
}
// index.ts
declare class C extends Object {
  static readonly p: unique symbol;
  [C.p](): void;
}
```

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js index.d.ts -t esnext
index.d.ts:1:14 - error TS2506: 'C' is referenced directly or indirectly in its own base expression.

1 export class C extends Object {
               ~
```

**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
`getMembersOfType` causes computed late bound names to be evaluated and bound, which shouldn't happen during name resolution, as it is used.... during computed name and base type resolution (which must finish before late bound names are actually bindable).

Fixes #23828

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1312,7 +1312,7 @@ namespace ts {
                     case SyntaxKind.ClassDeclaration:
                     case SyntaxKind.ClassExpression:
                     case SyntaxKind.InterfaceDeclaration:
-                        if (result = lookup(getMembersOfSymbol(getSymbolOfNode(location as ClassLikeDeclaration | InterfaceDeclaration)), name, meaning & SymbolFlags.Type)) {
+                        if (result = lookup(getSymbolOfNode(location as ClassLikeDeclaration | InterfaceDeclaration).members || emptySymbols, name, meaning & SymbolFlags.Type)) {
```
Comment (rbuckton) [inline src/compiler/checker.ts]: We should document _why_ we shouldn't resolve the members of the symbol here.
