### PR TITLE
Fix 10408 : Better error message for set/get with noImplicitAny error

### LINKED ISSUE #10408: Strange error: Property 'message' implicitly has type 'any', because its 'set' accessor lacks a type annotation
**TypeScript Version:**  release-2.0_mergeMaster branch from 15-8-2016 

**Code**

```ts
abstract class Parent
{
    public abstract get message();
}

class Child extends Parent {
    public get message() {
        return "";
    }
}
```
**Build options:**
 -noEmitOnError -noImplicitAny -target es5 -lib es5,dom bug.ts
two first flags are required, removing any of them will remove error

**Expected behavior:**
Compile without error or provide clear error message.

**Actual behavior:** 
error TS7016: Property 'message' implicitly has type 'any', because its 'set' accessor lacks a type annotation.
Two problems with this message:
- it has no file name and line number
- message property has no set accessor at all

### PR DESCRIPTION
**Pull request by yuit**
Fix #10408

### CODE REVIEW

**Comment by yuit** [comment]
:bell: @MaceWindu @RyanCavanaugh

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3346,7 +3346,12 @@ namespace ts {
                         // Otherwise, fall back to 'any'.
                         else {
                             if (compilerOptions.noImplicitAny) {
-                                error(setter, Diagnostics.Property_0_implicitly_has_type_any_because_its_set_accessor_lacks_a_type_annotation, symbolToString(symbol));
+                                if (setter) {
+                                    error(setter, Diagnostics.Property_0_implicitly_has_type_any_because_its_set_accessor_lacks_a_parameter_type_annotation, symbolToString(symbol));
+                                }
+                                else if (getter) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: There has to be `getter` or `setter`, right? If so we should just make this `else {` and `assert` that `getter` exists

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -2872,26 +2872,30 @@
         "category": "Error",
         "code": 7015
     },
-    "Property '{0}' implicitly has type 'any', because its 'set' accessor lacks a type annotation.": {
+    "Property '{0}' implicitly has type 'any', because its set accessor lacks a parameter type annotation.": {
         "category": "Error",
         "code": 7016
     },
-    "Index signature of object type implicitly has an 'any' type.": {
+    "Property '{0}' implicitly has type 'any', because its get accessor lacks a return type annotation.": {
```
Comment (RyanCavanaugh) [inline src/compiler/diagnosticMessages.json]: We shouldn't re-number more errors than we have to (it'll create RWC noise, etc). Maybe move both of these to a different error code if we really want them to have adjacent numbers.

Comment (sandersn) [inline src/compiler/diagnosticMessages.json]: In fact, why not just use `{1}` to add a get/set parameter and re-use error 7016?

Comment (yuit) [inline src/compiler/diagnosticMessages.json]: @sandersn  I was doing that (i.e sharing the error message) but getter and setter actually has slightly different error (getter error because no return type annotation while setter error because no parameter type annotation) since this is to improve that I think it is worth it to separate the two.

**Comment by RyanCavanaugh** [comment]
:+1:
