### PR TITLE
fix inconsistencies in import UMD code fixes adapting to module format

### LINKED ISSUE #17860: Quick Fix info inconsistent when offering to import a UMD declaration.
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.20170816)

**To Reproduce:**
```bash
C:\Source\import-quick-fix-issue> npm install -D typescript@next
C:\Source\import-quick-fix-issue> tsc --init
C:\Source\import-quick-fix-issue> npm install --save lodash @types/lodash
C:\Source\import-quick-fix-issue> 'export const chain = _.chain;'> index.ts
C:\Source\import-quick-fix-issue> code-insiders .
```

Open in Visual Studio Code, move cursor to `_`, click the 💡, and observe that the following quick fix info is displayed
image

**Expected behavior:**
If `--allowSyntheticDefaultImports` is `true` the quick fix info remains the same and the result is
```ts
import _ from "lodash";
export const chain = _.chain;
```
If `--allowSyntheticDefaultImports` is `false` the quick fix info changes to
image
and the result is
```ts
import * as _ from "lodash";
export const chain = _.chain;
```
**Actual behavior:**

Regardless of the values specified for `--module` and `--allowSyntheticDefaultImports`, the quick fix info is always
image

and the result is always 
```ts
import * as _ from "lodash";
export const chain = _.chain;
```

**Ideal behavior:** 😃

If `--allowSyntheticDefaultImports` is `true` the quick fix info remains the same and the result is
```ts
import _ from "lodash";
export const chain = _.chain;
```
If `--allowSyntheticDefaultImports` is `false` and `--module` is either `commonjs`, `amd`, or `umd` the quick fix info is changed to
image
and the result is
```ts
import _ = require("lodash");
export const chain = _.chain;
```

### PR DESCRIPTION
**Pull request by aluanhaddad**
As described in #17860, the import code fix for UMD modules has been updated such that it
 - uses `import m from "specifier";` import under --allowSyntheticDefaultImports
 - uses `import m = require("specifier");` syntax where supported
 - falls back to `import * as m from "specifier";` syntax where necessary
 - displays a diagnostic message matching the import that results from applying it

Fixes #17860

I'm not sure how to go about writing unit tests for this.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -644,6 +665,19 @@ namespace ts.codefix {
             Debug.fail("Either the symbol or the JSX namespace should be a UMD global if we got here");
         }
 
+        const { module, allowSyntheticDefaultImports } = context.compilerOptions;
+
+        // Prefer to import as a synthetic `default` if available.
+        if (allowSyntheticDefaultImports || module === ModuleKind.System && allowSyntheticDefaultImports !== false) {
```
Comment (mhegazy) [inline src/services/codefixes/importFixes.ts]: Add a function to `src\core.ts` to `getAllowSyntheticDefaultImports(compilerOptions)` that has this logic, and share it with the checker as well.

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -644,6 +665,19 @@ namespace ts.codefix {
             Debug.fail("Either the symbol or the JSX namespace should be a UMD global if we got here");
         }
 
+        const { module, allowSyntheticDefaultImports } = context.compilerOptions;
```
Comment (mhegazy) [inline src/services/codefixes/importFixes.ts]: consider moving `compilerOptions` to top destructuring declaration.

File: src/services/codefixes/importFixes.ts [hunk 3]
```diff
@@ -644,6 +665,19 @@ namespace ts.codefix {
...
 
+        const { module, allowSyntheticDefaultImports } = context.compilerOptions;
+
+        // Prefer to import as a synthetic `default` if available.
+        if (allowSyntheticDefaultImports || module === ModuleKind.System && allowSyntheticDefaultImports !== false) {
+            return getCodeActionForImport(symbol, { ...context, symbolName, kind: ImportKind.Default });
+        }
+
+        // When a synthetic `default` is unavailable, use `import..require` if the module kind supports it.
+        if (module === ModuleKind.AMD || module === ModuleKind.CommonJS || module === ModuleKind.UMD) {
```
Comment (mhegazy) [inline src/services/codefixes/importFixes.ts]: not sure i agree we need this change.

**Comment by mhegazy** [comment]
For tests, take a look at tests/cases/fourslash/importNameCodeFixNewImportFileDetachedComments.ts

File: src/services/codefixes/importFixes.ts (hunk 3 above)
Comment (aluanhaddad) [reply src/services/codefixes/importFixes.ts]: The argument here is that if `require` is available, it is a reliable away to obtain `module.exports` even when it is callable. I am happy to remove this as requested but believe it is valuable.

Comment (aluanhaddad) [reply src/services/codefixes/importFixes.ts]: This change is actually what's causing the build failures because of expectations in the four slash tests.

Would you like me to remove the `require` changes? I'd be happy to open a separate issue for them.

File: src/services/codefixes/importFixes.ts [hunk 4]
```diff
@@ -644,6 +665,20 @@ namespace ts.codefix {
             Debug.fail("Either the symbol or the JSX namespace should be a UMD global if we got here");
         }
 
+        const allowSyntheticDefaultImports = getAllowSyntheticDefaultImports(compilerOptions);
+
+        // Prefer to import as a synthetic `default` if available.
+        if (allowSyntheticDefaultImports) {
```
Comment (mhegazy) [inline src/services/codefixes/importFixes.ts]: @weswigham this is another place for your new change in https://github.com/Microsoft/TypeScript/pull/19675 to be plugged in. we would like to always show the `default` import in this case and never fallback to `import  .. = require`

**Comment by mhegazy** [comment]
@aluanhaddad can you please address the test failures.

File: src/services/codefixes/importFixes.ts (hunk 4 above)
Comment (aluanhaddad) [reply src/services/codefixes/importFixes.ts]: Roger. Thank you!

**Comment by aluanhaddad** [comment]
I updated it to always uses the synthetic defaults for UMD modules unless `--getAllowSyntheticDefaultImports(compilerOptions)` returns `false` in which case it suggests a namespace import. This also resolves the test failures.

**Comment by mhegazy** [comment]
thanks @aluanhaddad!

Want to redo the `import .. =require` support for AMD/CommonJS/UMD? I think we should do that as well.

**Comment by aluanhaddad** [comment]
@mhegazy I will create a PR for that shortly.

**Comment by mhegazy** [comment]
thanks!

File: src/services/codefixes/importFixes.ts [hunk 5]
```diff
@@ -237,6 +237,8 @@ namespace ts.codefix {
                 return parent as ImportDeclaration;
             case SyntaxKind.ExternalModuleReference:
                 return (parent as ExternalModuleReference).parent;
+            case SyntaxKind.ImportEqualsDeclaration:
```
Comment (andy-ms) [inline src/services/codefixes/importFixes.ts]: This will never be the parent of a `LiteralExpression`. Removing in #19667.
