### PR TITLE
fix(40817): Dts compiled from anonymous arrow functions cannot be automatically imported

### LINKED ISSUE #40817: Dts compiled from anonymous arrow functions cannot be automatically imported
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.3

**Search Terms**
- d.ts
- auto import
- intellisense

---

- Version: 1.49.1
- Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
- Date: 2020-09-16T23:21:17.533Z (4 days ago)
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.3.0

Steps to Reproduce:

I am using a library called ahooks, but this is not the point, I found such a thing: dts compiled from anonymous arrow functions cannot be automatically imported ...

1. yarn add ahooks
2. typing `useMouse` in the vscode
3. hit `enter` .. nothing happend

Screen Shot 2020-09-21 at 11 33 31 AM

Need to manually click to import

image

I looked at the [source code for `export default`](https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useMouse/index.ts#L21) and it looks like this

``` ts
export default () => {}
```

It will be compiled into dts like this

``` ts
declare const _default: () => void;
export default _default;
```

Anything types like this cannot be imported automatically

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40817

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -535,8 +535,9 @@ namespace ts.codefix {
             const checker = program.getTypeChecker();
             cancellationToken.throwIfCancellationRequested();
 
-            const defaultInfo = getDefaultLikeExportInfo(sourceFile, moduleSymbol, checker, program.getCompilerOptions());
-            if (defaultInfo && defaultInfo.name === symbolName && symbolHasMeaning(defaultInfo.symbolForMeaning, currentTokenMeaning)) {
+            const compilerOptions = program.getCompilerOptions();
+            const defaultInfo = getDefaultLikeExportInfo(sourceFile, moduleSymbol, checker, compilerOptions);
+            if (defaultInfo && (defaultInfo.name === symbolName || moduleSymbolToValidIdentifier(moduleSymbol, compilerOptions.target) === symbolName) && symbolHasMeaning(defaultInfo.symbolForMeaning, currentTokenMeaning)) {
```
Comment (andrewbranch) [inline src/services/codefixes/importFixes.ts:540]: We need the same change on line 242

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
Thanks!
