### PR TITLE
Do not list output files that just change their modified time when using --listEmittedFiles

### LINKED ISSUE #35605: Build not emitting files, but listing them
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
build out
no files build
emitted files
list emitted files incorrect

**Expected behavior:**
1. Expect `tsc --build` to compile files after outDir is deleted.
2. And expect `tsc --build --listEmittedFiles` to list files emitted

**Actual behavior:**
**Steps to replicate:**
1. Compile a composite project with `yarn tsc -b`
2. Remove outDir (dist or lib for example)
3. Recompile with `yarn tsc -b` (optionally with `--listEmittedFiles`)
4.a. Observe no new compiled files
4.b. Observe `--listEmittedFiles` listing files that aren't actually emitted.

See demo repo:
https://github.com/TimVosch/TS-Build-Bug

**Related Issues:** 
Unfortunately no.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #35605

### CODE REVIEW

File: src/testRunner/unittests/tsbuild/sample.ts [hunk 1]
```diff
@@ -358,18 +358,33 @@ export class cNew {}`);
             });
         });
 
+        const coreChanges: TscIncremental[] = [
+            {
+                buildKind: BuildKind.IncrementalDtsChange,
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tsbuild/sample.ts]: This is the change that's made on top of sample (from tests/projects/sample1) and  the baseline goes into` incremental-declaration-changes/scenario name`. The baseline contains output on the command line and the changes in file system

File: tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js [hunk 2]
```diff
@@ -0,0 +1,209 @@
+//// [/lib/incremental-declaration-changesOutput.txt]
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js]: This is the output from running the below command when the change is made.

File: tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js [hunk 3]
```diff
@@ -0,0 +1,209 @@
...
+exports.multiply = multiply;
+var someClass = /** @class */ (function () {
+    function someClass() {
+    }
+    return someClass;
+}());
+exports.someClass = someClass;
+
+
+//// [/src/core/index.ts]
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js]: This file represents the change.. Others are output files written

File: tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listFiles.js [hunk 4]
```diff
@@ -0,0 +1,211 @@
+//// [/lib/incremental-declaration-changesOutput.txt]
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listFiles.js]: This one is after making change that doesnt change the d.ts file from `core`

File: tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listFiles.js [hunk 5]
```diff
@@ -0,0 +1,211 @@
...
+exports.multiply = multiply;
+var someClass = /** @class */ (function () {
+    function someClass() {
+    }
+    return someClass;
+}());
+exports.someClass = someClass;
+
+
+//// [/src/core/index.ts]
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listFiles.js]: This is the change  that was made.

File: tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js (hunk 2 above)
Comment (andrewbranch) [reply tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js]: So are there other filenames that are _not_ being printed because only their timestamp changed?

Comment (sheetalkamat) [reply tests/baselines/reference/tsbuild/sample1/incremental-declaration-changes/listEmittedFiles.js]: Correct
