### PR TITLE
fix(51072): ts.preProcessFile finds import in template string after conditional expression with template strings

### LINKED ISSUE #51072: ts.preProcessFile finds import in template string after conditional expression with template strings
# Bug Report

### 🔎 Search Terms

preProcessFile template string conditional expression

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### 💻 Code

```ts
a ? `&${a}` : `#${b}`;

`import("${moduleSpecifier}").${id}`;
```

### 🙁 Actual behavior

```
{
  referencedFiles: [],
  typeReferenceDirectives: [],
  libReferenceDirectives: [],
  importedFiles: [ { fileName: '${moduleSpecifier}', pos: 32, end: 50 } ],
  isLibFile: false,
  ambientExternalModules: undefined
}
```

### 🙂 Expected behavior

```
{
  referencedFiles: [],
  typeReferenceDirectives: [],
  libReferenceDirectives: [],
  importedFiles: [],
  isLibFile: false,
  ambientExternalModules: undefined
}
```

This is somewhat similar to #47597 or #30878. I found this while fixing monaco for the module transform, which has a higher emit target that enables template strings. See: https://github.com/microsoft/TypeScript-Make-Monaco-Builds/actions/runs/3187364358/jobs/5198859864#step:7:343

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51072

### CODE REVIEW

File: src/services/preProcess.ts [hunk 1]
```diff
@@ -346,8 +346,8 @@ namespace ts {
                 }
 
                 if (scanner.getToken() === SyntaxKind.TemplateHead) {
-                    const stack = [scanner.getToken()];
-                    let token = scanner.scan();
+                    let token = scanner.getToken();
+                    const stack = [token];
```
Comment (jakebailey) [inline src/services/preProcess.ts:350]: If the starting token is `TemplateHead`, then we get down to the switch below and then it will push it onto the stack a second time. It seems like the old code was correct, so I'm not sure what I'm missing here that would make this change fix the bug...

Comment (a-tarasyuk) [reply src/services/preProcess.ts:350]: oke

Comment (a-tarasyuk) [reply src/services/preProcess.ts]: It seems we need to skip moving forward to the next token when the `stack` is empty.

**Review by jakebailey — APPROVED** [review]
Thanks for fixing this!

**Review by sheetalkamat — APPROVED** [review]
