### PR TITLE
Completion for default export should be '.default'

### LINKED ISSUE #16706: Incorrect completion offered for `export default` of named function/class
**TypeScript Version:**  2.5.0-dev.20170622

**Code**

```ts
// a.ts
export default function foo () {}

// b.ts
import * as a from './a'

a./* request completion */
```

**Expected behavior:**
`default` to be offered as the completion options.

**Actual behavior:**
`foo` is offered as the completion option.

image

Fortunately, the type checker correctly expects `default` as the key. Calling `a.default()` will work, but `a.foo()` (as suggested by the completions) will error with "Property 'foo' does not exist on type".

Also possibly related is that `import { /* request completion */ } from './a'` does not list `default` as an option (it should), but it at least does not list `foo`.

### LINKED ISSUE #16741: Don't return empty string from `getNameTable`
I think the check in `getCompletionEntryDisplayName` would be unnecessary if we didn't have the empty string in the name table in the first place.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #16706 and #12957

Just use `symbol.name` instead of `getDeclaredName`, since `getDeclaredName` intentionally gets the declared name of a default export instead of just "default".

This change apparently also affects completions for unicode escapes, but I think the change is good. In this code:
```ts
function \u0042() {
    /**/
}
```
We will now give you a completion for `B`, which is correct -- `B` is in scope because `\u0042` is equivalent to it.

**Update**: Also fixed #16741.
**Update**:
We must also change the behavior for `getSymbolsInScope()` to return *local* symbols, not exported symbols. We need different behavior based on whether the symbols are in scope or from an export; today's example being that an export is accessed with '.default' while a local symbol is accessed by its name. Also fixed a bug where `getSymbolAtLocation` couldn't handle a local symbol.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22226,11 +22228,6 @@ namespace ts {
                     }
 
                     switch (location.kind) {
-                        case SyntaxKind.SourceFile:
```
Comment (sandersn) [inline src/compiler/checker.ts]: I don't understand why this case goes away.

File: tests/cases/fourslash/completionsDefaultExport.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+// @Filename: /a.ts
+////export default function f() {}
+
+// @Filename: /b.ts
+////import * as a from "./a";
+////a./**/;
+
+goTo.marker();
+verify.completionListContains("default", "function f(): void");
```
Comment (sandersn) [inline tests/cases/fourslash/completionsDefaultExport.ts]: Interesting, is `a.f` legal here?

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -3549,6 +3549,11 @@ namespace ts {
         }
         return previous[previous.length - 1];
     }
+
+    /** See comment on `declareModuleMember` in `binder.ts`. */
+    export function getCombinedLocalAndExportSymbolFlags(symbol: Symbol): SymbolFlags {
+        return symbol.exportSymbol ? symbol.exportSymbol.flags | symbol.flags : symbol.flags;
```
Comment (sandersn) [inline src/compiler/utilities.ts]: why combine flags in the true case instead of just returning `symbol.exportSymbol.flags`?

File: src/harness/fourslash.ts [hunk 4]
```diff
@@ -949,6 +949,22 @@ namespace FourSlash {
             this.verifySymbol(symbol, declarationRanges);
         }
 
+        public symbolsInScope(range: Range): ts.Symbol[] {
+            const node = this.goToAndGetNode(range);
+            return this.getChecker().getSymbolsInScope(node, ts.SymbolFlags.Value | ts.SymbolFlags.Type | ts.SymbolFlags.Namespace);
```
Comment (sandersn) [inline src/harness/fourslash.ts]: nit: doesn't SymbolFlags have an alias defined like `SymbolFlags.All` that's equivalent?

File: src/harness/fourslash.ts [hunk 5]
```diff
@@ -3720,6 +3740,10 @@ namespace FourSlashInterface {
             this.state.verifySymbolAtLocation(startRange, declarationRanges);
         }
 
+        public typeOfSymbolAtLocation(range: FourSlash.Range, symbol: ts.Symbol, expected: string) {
```
Comment (sandersn) [inline src/harness/fourslash.ts]: can't we get this from the quick info? I don't know whether we need a separate method for comparing the stringified type of a symbol.

File: src/services/services.ts [hunk 6]
```diff
@@ -2090,42 +2090,30 @@ namespace ts {
...
+        });
+    }
 
-        function setNameTable(text: string, node: ts.Node): void {
-            nameTable.set(text, nameTable.get(text) === undefined ? node.pos : -1);
-        }
+    // We want to store any numbers/strings if they were a name that could be
+    // related to a declaration.  So, if we have 'import x = require("something")'
+    // then we want 'something' to be in the name table.  Similarly, if we have
+    // "a['propname']" then we want to store "propname" in the name table.
```
Comment (sandersn) [inline src/services/services.ts]: should be jsdoc

File: tests/cases/fourslash/completionsDefaultExport.ts (hunk 2 above)
Comment (andy-ms) [inline tests/cases/fourslash/completionsDefaultExport.ts]: No, the property name is `default`; `function f(): void` is just the display text.

File: src/compiler/checker.ts (hunk 1 above)
Comment (andy-ms) [inline src/compiler/checker.ts]: This comes from the second `Update` comment -- exported symbols aren't really the same as the symbols in scope.

File: src/harness/fourslash.ts (hunk 4 above)
Comment (andy-ms) [inline src/harness/fourslash.ts]: Not currently; `All` wouldn't be a good name since that's only 3 of 27 flags, but this is often useful; I'm tempted to just name it `ValueTypeNamespace`.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (andy-ms) [inline src/compiler/utilities.ts]: In `findAllRefsForDefaultExport08` (and `findAllRefsForDefaultExport02`), we have an exported class and a non-exported namespace merged with it. So the local symbol will have flags that the exported symbol is lacking; it has `NamespaceModule|ExportValue|ExportType` while the exported symbol just has `Class`.

File: src/harness/fourslash.ts (hunk 5 above)
Comment (andy-ms) [inline src/harness/fourslash.ts]: Well, quick info gets us the type of the symbol under the cursor -- this lets us call `getTypeOfSymbolAtLocation` on *any* symbol, at the current location.

File: tests/cases/fourslash/completionsDefaultExport.ts (hunk 2 above)
Comment (sandersn) [inline tests/cases/fourslash/completionsDefaultExport.ts]: Ah, I misread that as varargs

File: src/compiler/utilities.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/utilities.ts]: Makes sense
