### PR TITLE
fix(60887): Incorrect Formatting on if (a) try {} finally {} 

### LINKED ISSUE #60887: Incorrect Formatting on `if (a) try {} finally {}`
### 🔎 Search Terms

format, formatter, finally

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (it didn't change between TS3.3 and TS5.8).

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play/?ts=5.7.2#code/JYMwBAFALgTgrgUwJRlgTzAbwFBj2AegLADozsBfMEYAOwEMAbRjHfQ4sky7IA)

### 💻 Code

```ts
if (true) try {
    // ...
} finally {
    // ...
}
```

Click "Format Document" from the context menu or via keyboard shortcut (opt+shift+f).

### 🙁 Actual behavior

The format result is
```ts
if (true) try {
    // ...
} finally {
        // ...
    }
```

### 🙂 Expected behavior

Do not add indentation to the finally block.

### Additional information about the issue

Note that `if (a) try {} catch {}` works fine. Maybe there're something related. [Playground Link](https://www.typescriptlang.org/play/?ts=5.7.2#code/JYMwBAFALgTgrgUwJRlgTzAbwFBj2AegLADozsBfMAYwEMpqALLXfI08qkYAO1oBt+GHPlGFiZEqzwVsQA)

Related #3817

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #60887

### CODE REVIEW

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -729,6 +730,12 @@ export namespace SmartIndenter {
                     return false;
                 }
                 break;
+            case SyntaxKind.TryStatement:
+                const tryStatement = parent as TryStatement;
+                if (tryStatement.finallyBlock && tryStatement.finallyBlock === child) {
```
Comment (jakebailey) [inline src/services/formatting/smartIndenter.ts:735]: I'm suspicious about this just because all of the other code in this switch case are only checking syntax kind or position info, not node equality.

Comment (a-tarasyuk) [reply src/services/formatting/smartIndenter.ts:735]: @jakebailey thanks for the feedback. I found that in this case, the `finallyBlock` should not be handled as a child of the try block to ensure the correct delta calculation 

https://github.com/microsoft/TypeScript/blob/5170645f4e4b395891fad823bfe03ac628411afb/src/services/formatting/formatting.ts#L624

There are other places where we handle the `finallyBlock` in a similar way

https://github.com/microsoft/TypeScript/blob/5170645f4e4b395891fad823bfe03ac628411afb/src/services/outliningElementsCollector.ts#L259-L261

I hope that makes sense., if you have any thoughts or suggestions, I’d be grateful to hear them. thanks

**Comment by jakebailey** [comment]
@typescript-bot pack this

File: src/services/formatting/smartIndenter.ts (hunk 1 above)
Comment (jakebailey) [reply src/services/formatting/smartIndenter.ts:735]: How does this bug not affect the try block or the catch block, then? Maybe I'm missing something...

Comment (a-tarasyuk) [reply src/services/formatting/smartIndenter.ts]: I've modified changes to rely exclusively on checking the syntax kind

**Comment by jakebailey** [comment]
@typescript-bot pack this

File: src/services/formatting/smartIndenter.ts [hunk 2]
```diff
@@ -729,6 +729,11 @@ export namespace SmartIndenter {
                     return false;
                 }
                 break;
+            case SyntaxKind.TryStatement:
```
Comment (jakebailey) [inline src/services/formatting/smartIndenter.ts:732]: After reading this, I was really hoping that putting `TryStatement` above with `ForStatement` but that did not work either.

Comment (a-tarasyuk) [reply src/services/formatting/smartIndenter.ts:732]: Yes, an explicit check is needed to ensure finally isn't treated as a child of the try statement

**Review by jakebailey — APPROVED** [review]
