### PR TITLE
Handle file versioning little better in tsc --watch mode

### LINKED ISSUE #21444: Linux and mac problem with --watch option with a tsconfig.json « "include": ["app/**/*.ts"] »
**TypeScript Version:** 2.8.0-dev.20180127 or 2.6.2

**OS:** Linux x86_64

**Node Version:** 9.4.0

**Search Terms:** 
* "is:issue is:open watch"

**Steps to reproduce:**

1. `mkdir ~/essaiTS && cd $_`

2 . ~/essaiTS/tsconfig.json
```json
{
    "include": [
        "app/**/*.ts"
    ]
}
```
3. ~/essaiTS/app/file.ts
```typescript
console.log('aaa');
```
4. ` node node_modules/typescript/bin/tsc --watch --listEmittedFiles`
    * We could see a new file ~/essaiTS/app/file.js with:
```javascript
console.log('aaa');
```
5.  ~/essaiTS/app/file.ts
```typescript
console.log('aaa');
console.log('bbb');
```
**Expected behavior:**
At  ~/essaiTS/app/file.js. 
we must have:
```javascript
console.log('aaa');
console.log('bbb');
```
**Actual behavior:**
As in step 4., we have instead only:
```javascript
console.log('aaa');
```
With TypeScript 6.2 we could see in terminal : 
```
3:14:46 PM - File change detected. Starting incremental compilation...
3:14:47 PM - Compilation complete. Watching for file changes.
```
~~With TypeScript 2.8.0-dev.20180127 there is no messages.~~ (error on my part, with TypeScript 2.8.* console is just cleared: see my following comment.)
**Notes:**
* No problems with compilation option `--watch` if essaiTS is in folder /tmp. 
    To test you could use command line: `cp -R ~/essaiTS /tmp && cd /tmp/essaiTS && node node_modules/typescript/bin/tsc --watch --listEmittedFiles`, then edit file /tmp/essaiTS/app/file.ts.
* There is no problems with option `--watch` for files in  ~/essaiTS/app/folder/.

**Related Issues:**
Maybe: https://github.com/Microsoft/TypeScript/issues/20739

### PR DESCRIPTION
**Pull request by sheetalkamat**
Root cause:
Earlier the source file cache use to either have { version, sourceFile, fileWatcher } or string.
string meant file is on present on the disk and we wont go ahead and create source file at all for these whenever asked for new source file.
During watch callback, especially during wild card directory callback, if the file wasnt present on the disk, we would just remove the entry from cache..  So in below sequence the file version didnt change even though the content had changed:
1. Watch created, file was on disk, so version is set to inital version = 1
2. File deleted, deleted from the cache
3. File get created
4. Updating the program structure, since file is on the disk, create source file and set the version as initial version (as the entry wasn't there in the cache) = 1
5. During emit since old program and new program had files with same version, they arent marked as changed and hence not emitted

Fix:
Now whenever the file callback is invoked, and cache has file as missing, instead of removing the entry, we would create a temp entry that represents that file may be on the disk = { version++ } 
This ensures that next time program is able to find the file on the disk and create new source file, it wont have initial version. Thus when creating new source file from oldProgram, if the file is changed, it would always have different version than the oldSourceFile from oldProgram.

Fixes #21444

### CODE REVIEW

File: src/compiler/watch.ts [hunk 1]
```diff
@@ -697,20 +718,22 @@ namespace ts {
...
-        function removeSourceFile(path: Path) {
+        function nextSourceFileVersion(path: Path) {
             const hostSourceFile = sourceFilesCache.get(path);
             if (hostSourceFile !== undefined) {
-                if (!isString(hostSourceFile)) {
-                    hostSourceFile.fileWatcher.close();
-                    resolutionCache.invalidateResolutionOfFile(path);
+                if (isFileMissingOnHost(hostSourceFile)) {
+                    // The next version, lets set it as presence unknown file
+                    sourceFilesCache.set(path, { version: Number(hostSourceFile) + 1 });
```
Comment (mhegazy) [inline src/compiler/watch.ts]: can we make it a `number` instead of a `string` since we are using it as a version?

File: src/compiler/watch.ts [hunk 2]
```diff
@@ -721,10 +744,10 @@ namespace ts {
             // there was version update and new source file was created.
             if (hostSourceFileInfo) {
                 // record the missing file paths so they can be removed later if watchers arent tracking them
-                if (isString(hostSourceFileInfo)) {
+                if (isFileMissingOnHost(hostSourceFileInfo)) {
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/compiler/watch.ts]: In the line below the hostSourceFile could be ```FilePresenceUnknownOnHost```  or ```FileMayBePresentOnHost``` . It is kind of redundant to check if ```isFilePresentOnHost``` since it only checks if sourceFile is present on the host and the next check is going to check if sourceFile === oldSourceFile (oldSourceFile is never undefined). Hence the cast

File: src/compiler/watch.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/watch.ts]: Done.

**Comment by JulioJu** [comment]
I confirm it fixes  #21444

**Comment by sheetalkamat** [comment]
@mhegazy Ready for merge pending your approval

File: src/compiler/watch.ts (hunk 1 above)
Comment (mhegazy) [reply src/compiler/watch.ts]: so we do not need the call to `Number`?

**Comment by mhegazy** [comment]
Please port to release-2.7 as well.

**Comment by avbentem** [comment]
Tested on a (slow) Windows 7 with quite a few corporate virus scanners running: `2.8.0-dev.20180215` fixes the issues I had with WebStorm's "safe write" option enabled. (Which creates temporary files, deletes the original and then renames the temporary file.)

Thanks for this fix!
