### PR TITLE
Js constructor function fixes

### LINKED ISSUE #22414: Callable constructor in Javascript and strict mode includes undefined when called without `new`
**Code**

```ts
// @noEmit: true
// @allowJs: true
// @checkJs: true
// @strict: true
// @Filename: a.js

/** @param {number} x */
function A(x) {
    if (!(this instanceof A)) {
        return new A(x)
    }
    this.x = x
}
var k = A(1)
var j = new A(2)
k.x === j.x
```

**Expected behavior:**

The type of `k` and `j` should be `{ x: number | undefined }`. (Actually, `{ x: number }`, but that's a separate bug.)

**Actual behavior:**

`k` has the type `{ x: number | undefined } | undefined`

### LINKED ISSUE #22641: In JS, this assignments in a function add undefined to the resulting property type
This is visible with `--strict`:

```ts
// @noEmit: true
// @allowJs: true
// @checkJs: true
// @strict: true
// @Filename: a.js

function A() {
    this.x = { y : 1 }
}
var a = new A()
a.x.y
```

**Expected behavior:**
No error

**Actual behavior:**
Error "Object is possibly undefined" when accessing `a.x.y`

### PR DESCRIPTION
**Pull request by sandersn**
JS constructors had a couple of bugs with strictNullChecks (which people actually *do* use with checkJs, see [the recent post](https://medium.com/unsplash/how-we-gradually-migrated-to-typescript-at-unsplash-7a34caa24ef1) by @OliverJAsh).

1. this-assignments in a function added `undefined` to the type of all properties:

```ts
function A() {
  this.x = 1
}
```

Incorrectly had `x: number | undefined` not `x: number`.

2. Callable constructors, which have a check to see whether they were called instead of newed, incorrectly unioned undefined to the instance type. This was unneeded and annoying:

```ts
function A() {
  if (!(this instanceof A)) {
    return new A()
  }
  this.x = 1
}
var a = new A()
```

This incorrectly had `a: { x: number } | undefined` when it should have been `a: { x: number }`

Fixes #22414 
Fixes #22641 

Note that the second fix checks two things to distinguish a constructor function from a normal one:
1. Whether the function is a javascript constructor
2. Whether the function returns a type with the symbol of the constructor function itself -- that is, whether it has a statement `return new A()` somewhere inside `function A`. It doesn't check whether this statement is inside a conditional.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4259,7 +4259,12 @@ namespace ts {
                 }
 
                 if (isPropertyAccessExpression(expression.left) && expression.left.expression.kind === SyntaxKind.ThisKeyword) {
-                    if (getThisContainer(expression, /*includeArrowFunctions*/ false).kind === SyntaxKind.Constructor) {
+                    const thisContainer = getThisContainer(expression, /*includeArrowFunctions*/ false);
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: An explanatory comment would be nice to have here

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4259,7 +4259,14 @@ namespace ts {
                 }
 
                 if (isPropertyAccessExpression(expression.left) && expression.left.expression.kind === SyntaxKind.ThisKeyword) {
-                    if (getThisContainer(expression, /*includeArrowFunctions*/ false).kind === SyntaxKind.Constructor) {
+                    const thisContainer = getThisContainer(expression, /*includeArrowFunctions*/ false);
+                    const isPrototypeProperty = isBinaryExpression(thisContainer.parent) &&
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Only used if `thisContainer.kind === SyntaxKind.FunctionExpression`, might want to avoid computing this otherwise.
