### PR TITLE
More thorough node completed-ness checking

### LINKED ISSUE #2380: Smart indent for binding patterns is wrong
Type either of the following and then press enter:
```ts
var [
```
```ts
var {
```

Expected: The cursor is indented.
Actual: The cursor is not indented.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
More thoroughly checks whether a node is considered "completed".

Also fixes #2380.

### CODE REVIEW

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -429,46 +433,79 @@ module ts.formatting {
...
                         return isCompletedNode((<IfStatement>n).elseStatement, sourceFile);
                     }
                     return isCompletedNode((<IfStatement>n).thenStatement, sourceFile);
+
                 case SyntaxKind.ExpressionStatement:
                     return isCompletedNode((<ExpressionStatement>n).expression, sourceFile);
+
                 case SyntaxKind.ArrayLiteralExpression:
+                case SyntaxKind.ArrayBindingPattern:
+                case SyntaxKind.IndexSignature:
```
Comment (CyrusNajmabadi) [inline src/services/formatting/smartIndenter.ts]: This seems wrong for IndexSignature.

Comment (DanielRosenwasser) [inline src/services/formatting/smartIndenter.ts]: Good catch!

**Comment by DanielRosenwasser** [comment]
Verbal sign-off from @CyrusNajmabadi.
