### PR TITLE
use formatting scanner with languageVariant=JSX for .tsx files

### LINKED ISSUE #4511: Debug failure in LS when pasting following code snippet in .tsx file
Copy/paste the following code snippet into a new tsx file

```TypeScript
interface I<T1, T2> {
    next: I</**/
}
```

Assertion failure:
```
Description:

getFormattingEditsForRange('C:\Users\drosen\AppData\Local\Temp\~vs62CC.tsx', 0, 42)

StackTrace:

Error: Debug Failure. False expression: 
   at assert (:1558:17)
   at processChildNode (:40970:25)
   at Anonymous function (:40921:21)
   at visitNode (:7169:13)
   at forEachChild (:7314:17)
   at processNode (:40920:17)
   at processChildNode (:40976:21)
   at Anonymous function (:40921:21)
   at visitNode (:7169:13)
   at forEachChild (:7314:17)
   at processNode (:40920:17)
   at processChildNode (:40976:21)
   at Anonymous function (:40921:21)
   at visitNode (:7169:13)
   at forEachChild (:7341:17)
   at processNode (:40920:17)
   at processChildNode (:40976:21)
   at processChildNodes (:41009:25)
   at Anonymous function (:40923:21)
   at visitNodeArray (:7174:13)
   at forEachChild (:7332:17)
   at processNode (:40920:17)
   at formatSpan (:40752:17)
   at formatSelection (:40559:13)
   at getFormattingEditsForRange (:47293:13)
   at Anonymous ......
```

### PR DESCRIPTION
**Pull request by vladima**
fixed #4511

### CODE REVIEW

File: src/services/formatting/formattingScanner.ts [hunk 1]
```diff
@@ -40,12 +48,17 @@ namespace ts.formatting {
...
+                Debug.assert(scanner !== undefined);
+                
                 lastTokenInfo = undefined;
                 scanner.setText(undefined);
+                scanner = undefined;
             }
         }
 
         function advance(): void {
+            Debug.assert(scanner !== undefined);
```
Comment (mhegazy) [inline src/services/formatting/formattingScanner.ts]: do you still need these asserts?

**Comment by mhegazy** [comment]
:+1:

File: src/services/formatting/formattingScanner.ts (hunk 1 above)
Comment (vladima) [inline src/services/formatting/formattingScanner.ts]: I'd keep them to make sure that contract of interaction with formatting scanner will be kept consistent
