### PR TITLE
findAllReferences: Don't need to check for `symbol.declarations`

### LINKED ISSUE #13690: Find-all-refs for mapped type does not work on access
**TypeScript Version:**   nightly (2.2.0-dev.20170125)

```ts
/// <reference path='fourslash.ts'/>

////interface T { [|a|]: number; }
////type U = { [K in keyof T]: string };
////declare const t: T;
////t.[|a|];
////declare const u: U;
////u.[|a|];

const [r0, r1, r2] = test.ranges();
verify.referencesOf(r2, [r0, r1, r2]);
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #13690

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -285,6 +285,9 @@ namespace ts.FindAllReferences.Core {
             return undefined;
         }
 
+        // If this property is derived from another one, find references on the original property instead.
+        symbol = (symbol as ts.SymbolLinks).syntheticOrigin || symbol;
```
Comment (mhegazy) [inline src/services/findAllReferences.ts]: why not put it under checker.getRootSymbols()?

Comment (andy-ms) [inline src/services/findAllReferences.ts]: There was a check for `if (!symbol.declarations)` which failed for a synthetic symbol, which has no declarations of its own. Removing this check (and another similar one) seems to cause no problems, though.
