### PR TITLE
Fix flow node improper reuse

### LINKED ISSUE #60597: [TypeScript] Revealing `Unreachable code` breaks diagnostics
Steps to Reproduce:

```ts
function test() {
	return abc();
	return;
}

function abc() { }
```
1. create TypeScript file and paste code
2. remove the space in-between `return` and `abc();`
3. readd the space
4. `Cannot find name 'returnabc('.ts(2304)` error remains ❌
5. typing random characters may make the error disappear otherwise it will physically stay in the same place

Image

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3 (and https://insiders.vscode.dev/)
- OS Version: Windows 11

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #60597.

The problem is caused by improper handling of node reuse across different versions of a source file. Say we have the following program:

```ts
function test() {
    returnabc();
    return;
}
function abc() { }
```
We'll get a compiler error saying `returnabc` could not be found. And, when we bind the source file, `return` will have its flow node set to a flow call node (corresponding to `returnabc()`).
If we then edit the file to this:
```ts
function test() {
    return abc();
    return;
}
function abc() { }
```
We will reuse the node for `return`. However, because that node is unreachable, the binder will not assign a new flow node to that node, and it will preserve its old flow node. Now, when we check the source file, we expect it to have no errors, but the `return` node will have a flow node for the old file, and that flow node will have a node that corresponds to the `returnabc()` call, and the checker will error on it when it visits that node.

What this PR does is clean up the old flow node in the binder when a node is unreachable, because otherwise the flow node would not be updated.

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1104,6 +1104,9 @@ function createBinder(): (file: SourceFile, options: CompilerOptions) => void {
         // and set it before we descend into nodes that could actually be part of an assignment pattern.
         inAssignmentPattern = false;
         if (checkUnreachable(node)) {
+            if ((node as HasFlowNode).flowNode) {
+                (node as HasFlowNode).flowNode = undefined;
+            }
```
Comment (jakebailey) [inline src/compiler/binder.ts:1109]:
```suggestion
            if (canHaveFlowNode(node)) {
                node.flowNode = undefined;
            }
```

To avoid casting, but also because I think it'll prevent negative perf effects from speculatively trying to access `flowNode` on all nodes?

Then again, the binder does not currently import this function at all, and it's not used below where `flowNode` is set, so maybe not.

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Review by jakebailey — APPROVED** [review]
This looks good to me, though I am still on the fence about `canHaveFlowNode` a bit. Maybe it was a bad suggestion.

**Comment by jakebailey** [comment]
Well, it at least prevents us from tacking `undefined` onto something that doesn't need it, but, the `.flowNode` check already did that too...

**Comment by gabritto** [comment]
> This looks good to me, though I am still on the fence about `canHaveFlowNode` a bit. Maybe it was a bad suggestion.

I think it probably doesn't matter a lot? I think accesses to node properties in `bindChildren` are megamorphic already, no?
I don't know that I want to go and try to perf test this beyond the standard benchmark, as it would require some setup for changing the file and having reuse and unreachable nodes etc. Maybe @rbuckton has an opinion.

File: src/compiler/binder.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/binder.ts]: Calling `canHaveFlowNode` is better than the cast as it accesses a property that is always present (`kind`), vs. a property that may not be defined (`flowNode`). The latter results in eager deoptimizations as a result of the missing property.
