### PR TITLE
 Reload the text from file if there is pending reload of the script info before determining to use SVC

### LINKED ISSUE #20806: Error: Debug Failure. False expression: ScriptVersionCache should not be set in `getLineMap` during `getApplicableRefactors`
tsserver version: 2.6.1
hitting sessions: 1258
stack:
```
Error: Debug Failure. False expression: ScriptVersionCache should not be set
    at TextStorage.getLineMap (tsserver.js:81599:26)
    at TextStorage.lineOffsetToPosition (tsserver.js:81564:70)
    at ScriptInfo.lineOffsetToPosition (tsserver.js:81784:41)
    at IOSession.Session.getStartAndEndPosition (tsserver.js:86542:48)
    at IOSession.Session.extractPositionAndRange (tsserver.js:86462:35)
    at IOSession.Session.getApplicableRefactors (tsserver.js:86473:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:85436:61)
    at tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (tsserver.js:86660:28)
    at IOSession.Session.executeCommand (tsserver.js:86669:33)
    at IOSession.Session.onMessage (tsserver.js:86689:35)
    at Interface.<anonymous> (tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #20806

### CODE REVIEW

File: src/server/scriptInfo.ts [hunk 1]
```diff
@@ -176,8 +176,13 @@ namespace ts.server {
                 return this.switchToScriptVersionCache();
             }
 
-            // Else if the svc is uptodate with the text, we are good
-            return !this.pendingReloadFromDisk && this.svc;
+            // If there is pending reload from the disk then, reload the text
+            if (this.pendingReloadFromDisk) {
```
Comment (aozgaa) [inline src/server/scriptInfo.ts]: Should `this.pendingReloadFromDisk` be set to false here or in a callee afte the reload completes?

Comment (sheetalkamat) [reply src/server/scriptInfo.ts]: It does get set whenever the text is reloaded into the script info. (https://github.com/Microsoft/TypeScript/pull/22151/files#diff-f56eebffea5b0d2286bb5998c67920e9L78)

Comment (aozgaa) [reply src/server/scriptInfo.ts]: Missed that. Thanks!
