### PR TITLE
Fix missing func modifier

### LINKED ISSUE #40366: Convert to named function drops the async keyword
**TypeScript Version:**  4.0.2

**Search Terms:** "convert to named function"

**Code**

```ts
const getGreeting = async (): Promise<string> => {
  const name = await getName();
  return `Hello ${name}`;
};
```

Cursor on `getGreeting` > "Convert to named function"

**Expected behavior:**

```ts
async function getGreeting(): Promise<string> {
  const name = await getName();
  return `Hello ${name}`;
}
```

**Actual behavior:**

```ts 
function getGreeting(): Promise<string> {
  const name = await getName();
  return `Hello ${name}`;
}
```

**See it in action:** 

2020-09-03 Screenshot-nvNcOX2b

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #40366

### CODE REVIEW

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts [hunk 1]
```diff
@@ -178,7 +178,10 @@ namespace ts.refactor.convertArrowFunctionOrFunctionExpression {
 
         const { variableDeclaration, variableDeclarationList, statement, name } = variableInfo;
         suppressLeadingTrivia(statement);
-        const newNode = factory.createFunctionDeclaration(func.decorators, statement.modifiers, func.asteriskToken, name, func.typeParameters, func.parameters, func.type, body);
+
+        const modifiersFlags = getCombinedModifierFlags(variableDeclaration) | getEffectiveModifierFlags(func);
+        const modifiers = factory.createModifiersFromModifierFlags(modifiersFlags);
+        const newNode = factory.createFunctionDeclaration(func.decorators, length(modifiers) ? modifiers : undefined, func.asteriskToken, name, func.typeParameters, func.parameters, func.type, body);
```
Comment (DanielRosenwasser) [inline src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:184]: Why not just pass in `modifiers`?

```suggestion
        const newNode = factory.createFunctionDeclaration(func.decorators, modifiers, func.asteriskToken, name, func.typeParameters, func.parameters, func.type, body);
```

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts [hunk 2]
```diff
@@ -178,7 +178,10 @@ namespace ts.refactor.convertArrowFunctionOrFunctionExpression {
 
         const { variableDeclaration, variableDeclarationList, statement, name } = variableInfo;
         suppressLeadingTrivia(statement);
-        const newNode = factory.createFunctionDeclaration(func.decorators, statement.modifiers, func.asteriskToken, name, func.typeParameters, func.parameters, func.type, body);
+
+        const modifiersFlags = getCombinedModifierFlags(variableDeclaration) | getEffectiveModifierFlags(func);
```
Comment (DanielRosenwasser) [inline src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:182]: I don't have an intuition on this one - @rbuckton is this necessary?

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts (hunk 1 above)
Comment (Kingwl) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:184]: Actually if i pass `modifiers` in, the `textChanges` does not happy and break an assert.

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts (hunk 2 above)
Comment (sandersn) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:182]: @rbuckton can you weigh in on this? I think this is ready to go otherwise.

**Comment by Kingwl** [comment]
UPpppp

**Comment by Kingwl** [comment]
Uuuup

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:182]: So I took a brief look at it - what sort of modifiers do you need to propagate from the variable declaration?

Comment (rbuckton) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:182]: `export`, basically.

Comment (rbuckton) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:182]: The only other one we would possibly pick up is `declare`, which is valid on a function though the initializer is an error. The result would be a `declare async function` with a body which is *also* an error.

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts (hunk 1 above)
Comment (rbuckton) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:184]: Out of curiosity, which assert? We probably should consider converting an empty modifier list into `undefined` in the factory, since our parser never produces an empty modifier list (if it fails to parse modifiers, it returns `undefined`).

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts (hunk 2 above)
Comment (rbuckton) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:182]: For the sake of clarity, and to future proof against other possibly invalid flags, perhaps this should be changed to:

```suggestion
        const modifiersFlags = (getCombinedModifierFlags(variableDeclaration) & ModifierFlags.Export) | getEffectiveModifierFlags(func);
```

It would remove `declare` in the following case, which arguably is incorrect anyways:
```ts
// before
export declare const x = async () => {}; // error on const initializer in an ambient context
// after
export async function x() {}
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts (hunk 1 above)
Comment (Kingwl) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:184]:
```
Error: Debug Failure. False expression.
      at getPos (src\services\textChanges.ts:10:15)
      at assignPositionsToNodeArray (src\services\textChanges.ts:1030:39)
      at Object.visitEachChild (src\compiler\visitorPublic.ts:876:21)
      at assignPositionsToNode (src\services\textChanges.ts:1016:25)
      at getNonformattedText (src\services\textChanges.ts:999:52)
      at getFormattedTextOfNode (src\services\textChanges.ts:973:36)
      at format (src\services\textChanges.ts:951:41)
      at computeNewText (src\services\textChanges.ts:954:19)
```

**Review by sandersn — APPROVED** [review]
