### PR TITLE
fix for 45006

### LINKED ISSUE #45006: Const typeguard flows into methods but not properties
# Bug Report

### 🔎 Search Terms

type guard get property const

### 🕗 Version & Regression Information

Fails at least on 4.3.5 and 4.4.0-beta.

- I was unable to test this on prior versions because I noticed this behavior very recently.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/MYewdgzgLgBAHgLhtATgSzAcxgHxmAVwFsAjAUxRgF4YBZAQygAsA6FesAExCIAoBKGAB4YABhYBWGAH4YAIlRyYSAIwAmAMwBuALAAoNADMYvKAE8ADmRDG41KjQVR0WOYIDe+mDAA2ZWCAkAFbUMJ563t6Y-jAWKCAWAmEwKP4EKGDwLFAgAKoWVigAwvQQZEkAvgA0XpFE-kwgnEnuKWkZWTn5hSVllbUV+hVAA)

### 💻 Code

```ts
const x: string | number = Math.random() < 0.5 ? "str" : 123;
if (typeof x === "string") {
  let obj = {
    get prop() { return x.toUpperCase() },  // Error: property toUpperCase doesn't exist on number
    method() { return x.toUpperCase() } // Ok
  }
}
```

### 🙁 Actual behavior
The method compiles, the getter raises an error.

### 🙂 Expected behavior
Behaviour should be the same for both.
Given that `x` is a const and its type was narrowed to `string`, no error seems right.

### PR DESCRIPTION
**Pull request by softwareCobbler**
Fixes #45006 
thanks, typescript is great

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1835,6 +1833,8 @@ namespace ts {
                 case SyntaxKind.ClassStaticBlockDeclaration:
                     return ContainerFlags.IsContainer | ContainerFlags.IsControlFlowContainer | ContainerFlags.HasLocals | ContainerFlags.IsFunctionLike;
 
+                case SyntaxKind.GetAccessor:
+                case SyntaxKind.SetAccessor:
```
Comment (sandersn) [inline src/compiler/binder.ts:1837]: This move doesn't seem right -- `get/set` aren't function expressions. Do the tests still pass with this change reverted?

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -3372,7 +3372,7 @@ namespace ts {
                 emitFlags |= NodeFlags.HasAsyncFunctions;
             }
 
-            if (currentFlow && isObjectLiteralOrClassExpressionMethod(node)) {
```
Comment (sandersn) [inline src/compiler/binder.ts:3375]: There are only 3 callers of `isObjectLiteralOrClassExpressionMethod`. Two of them need this addition, and the third is guarded by `case SyntaxKind.MethodDeclaration`. So I'd like to see the new check moved into that function, and the name should be ... uhh ... `isObjectLiteralOrClassExpressionMethodOrAccessor` ???

Maybe there's a better name if there's a term that means "method or accessor".

File: tests/cases/compiler/gettersAndSetters.ts [hunk 3]
```diff
@@ -37,3 +37,13 @@ interface I1 {
 }
 
 var i:I1 = function (n) {return n;}
+
```
Comment (sandersn) [inline tests/cases/compiler/gettersAndSetters.ts:40]: Please add a `// @target: es2020` (or any target newer than es3) at the top of this file. I wish our tests didn't target ES3 by default.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/binder.ts (hunk 1 above)
Comment (softwareCobbler) [reply src/compiler/binder.ts:1837]: reverting just this change causes the new test to fail. The goal here was (admittedly opaquely) to have `bindContainer` bind the getter/setter node to the fresh start flow, which returning these container flags succeeded at doing (the desired flow binding occurs if the `containerFlags` for a given container are either `ContainerFlags.IsFunctionExpression` or `ContainerFlags.IsObjectLiteralOrClassExpressionMethod`). Your comments about consolidating `isObjectLiteralOrClassExpressionMethod` makes it look like moving these switch cases to be with the `MethodDeclaration` case makes sense.

This made me realize I should have made explicit the intent to attach `GetAccessorDeclaration` and `SetAccessorDeclaration`s to `FlowStart.node`; doing so has the possibly unfortunate side effect of changing the shape of the `FlowStart` interface in 2 publicly exposed interface files. Not sure what the policy is on that.

File: src/compiler/binder.ts (hunk 2 above)
Comment (softwareCobbler) [reply src/compiler/binder.ts:3375]: I just went with choice 1, `isObjectLiteralOrClassExpressionMethodOrAccessor`; there was also a `ContainerFlags` by the same name that looked like it could be part of the same renaming effort.

File: tests/cases/compiler/gettersAndSetters.ts (hunk 3 above)
Comment (softwareCobbler) [reply tests/cases/compiler/gettersAndSetters.ts:41]: yes no problem

File: src/compiler/utilities.ts [hunk 4]
```diff
@@ -1526,10 +1526,12 @@ namespace ts {
         return node && node.kind === SyntaxKind.MethodDeclaration && node.parent.kind === SyntaxKind.ObjectLiteralExpression;
     }
 
-    export function isObjectLiteralOrClassExpressionMethod(node: Node): node is MethodDeclaration {
-        return node.kind === SyntaxKind.MethodDeclaration &&
+    export function isObjectLiteralOrClassExpressionMethodOrAccessor(node: Node): node is MethodDeclaration {
+        return (node.kind === SyntaxKind.MethodDeclaration &&
```
Comment (sandersn) [inline src/compiler/utilities.ts:1530]: The parent of a get/set should also have to be an object literal or class expression; they're the same as method declarations in that regard.

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks good except one final tweak in `isObjectLiteralOrClassExpressionMethodOrAccessor`

File: src/compiler/utilities.ts (hunk 4 above)
Comment (softwareCobbler) [reply src/compiler/utilities.ts]: OK, I see that now.

**Review by sandersn — APPROVED** [review]
