### PR TITLE
Fix primitive narrowing

### LINKED ISSUE #7224: type guards strangeness
**TypeScript Version:** 

1.8.0

**Code**

```ts
const enum AsNonBlank {}
export function isNonBlank(value: string) : value is string & AsNonBlank {
    return !/^\s*$/g.test(value);
}
let value: string;
if (isNonBlank(value)) {
    doThis(value); // expected value to be string & AsNonBlank, actual: string
} else {
    doThat(value);
}
function doThis(value: string & AsNonBlank): void {
}
function doThat(value: string) : void {
}
```

**Expected behavior:**
value should either be `string & AsNonBlank`
or there must be a message saying that the type guard is invalid or something
**Actual behavior:** 
value is a `string`

### LINKED ISSUE #7441: Type guard function does not work for string literal types
**TypeScript Version:** 

1.8.2

**Code**

```ts
type Click = 'click';

function isClick(event: string): event is Click {
	return event === 'click';
}

function validateClickEvent(event: string): Click {
	if (isClick(event)) {
		return event; // this line raises a compilation error: Type 'string' is not assignable to type '"click"'
	}
	throw new Error('not click');
}

type Creature = {};
type Animal = {} & Creature;

function isAnimal(creature: Creature): creature is Animal {
	return true;
}

function validateAnimalCreature(creature: Creature): Animal {
	if (isAnimal(creature)) {
		return creature; // this line does not raise any compilation error
	}
	throw new Error('not animal');
}

```

**Expected behavior:**

Can apply type guard to string literal types.

**Actual behavior:** 

Cannot apply type guard to string literal types.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #7224.
Fixes #7441.

This is a re-submission of #7235 without the inversion of the type flag - meaning it simply adds all primitive types and intersection types to the narrowable types list.

@ahejlsberg @sandersn

### CODE REVIEW

File: tests/cases/conformance/expressions/typeGuards/typeGuardNarrowsPrimitiveIntersection.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+let value: string;
+if (isNonBlank(value)) {
+    doThis(value);
+} else {
+    doThat(value);
+}
+
+
+const enum Tag2 {}
+declare function isNonBlank2(value: string) : value is (string & Tag2);
```
Comment (sandersn) [inline tests/cases/conformance/expressions/typeGuards/typeGuardNarrowsPrimitiveIntersection.ts]: how is string & Tag2 structurally different from just string?

Comment (weswigham) [inline tests/cases/conformance/expressions/typeGuards/typeGuardNarrowsPrimitiveIntersection.ts]: Tag2 is a const enum

**Comment by sandersn** [comment]
:+1:

**Comment by sandersn** [comment]
I'll merge since Wesley's still waiting on commit privileges.

**Comment by aleksey-bykov** [comment]
is this approved by @ahejlsberg, can i use it to build upon?

**Comment by sandersn** [comment]
Yes, it turns out there's not much perf hit from this change. However, narrowing will not expand beyond this to methods. That's the performance cliff that @ahejlsberg was thinking of.
