### PR TITLE
Instantiation expressions

### LINKED ISSUE #37181: Allow binding generic functions to a given type
## Search Terms
generic function, parametric function, function type parameter, function type argument

The problem is closely related to #26043, but the proposed solution is different.

## Suggestion

Currently, there is no way of explicitly providing type arguments to generic functions. For example, consider the following function:

```ts
function box<T>(value: T) {
  return { value };
}
```

TypeScript correctly infers the return type `{ value: T }`. However, it's not possible to derive the return type for a particular `T`, say `number`, at least not without ugly workarounds such as creating new functions just to fix the type arguments:

```ts
type Box = ReturnType<typeof box>;  // { value: unknown }
type Box<T> = ReturnType<typeof ???>;  // can't propagate T from Box to box

const numBox = (n: number) => box(n);  // ugly workaround
type NumBox = ReturnType<typeof numBox>;
```

So I suggest to provide a syntax that allows to do just that: fix type arguments of generic functions:

```ts
type Box<T> = ReturnType<typeof box<T>>;
type NumBox = ReturnType<typeof box<number>>;
```

This syntax resembles the existing one for providing type arguments when _calling_ a function:

```ts
const b = box<number>(2);
```

With this proposal implemented, interpreting such a call could be split into two parts:
First fix the type argument of box to `number`, which yields a function that takes a number.
Second, apply that function to `2`.
Hence, it could also be written with parenthesis: `(box<number>)(2)`.
I wouldn't suggest doing that in practice, but it shows that this proposal increases composability of generic functions.

## Use Cases

I tried to come up with a way to implement discriminated unions more succintly. The idea is to start with factory functions and then combine the return types:

```ts
function val<V>(value: V) {
    return { type: "Val", value } as const;
}
function plus<V>(left: V, right: V) {
    return { type: "Plus", left, right } as const;
}
function times<V>(left: V, right: V) {
    return { type: "Times", left, right } as const;
}

type Expr<V> = ReturnType<typeof val<V>>
             | ReturnType<typeof plus<V>>
             | ReturnType<typeof times<V>>;
```

With this approach, you would get convenient factory functions for building instances, without duplicating the object structure.

But it doesn't work, because it relies on the new syntax I just proposed.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### LINKED ISSUE #40542: Apply function generics as part of type definition
## Search Terms

generic typeof functions

## Suggestion

The problem is with the code as below:
```ts
const id = <T>(val: T) => val
type IdType = typeof id
// type IdType = <T>(val: T) => T

type Ret = ReturnType<typeof id>
// type Ret = unknown
```

It would be nice to be able to do something like so:
```ts
const id = <T>(val: T) => val
type IdType<T> = (typeof id)<T>
// type IdType<T> = (val: T) => T

// Or by extension:
type Ret<T> = ReturnType<(typeof id)<T>>
// type Ret<T> = T
```

## Use Cases

This would be useful to use with the [vriad/zod](https://github.com/vriad/zod) library, to implement different field validators depending on a parameter, like so:

```ts
// the dateSchema param could be a schema for an ISO 8601 string or a Date object, or even some custom date-like type
const fooSchema = <T>(dateSchema: z.ZodSchema<T>) => z.object({
  name: z.string(),
  date: dateSchema
})
type Foo<T> = z.infer<ReturnType<(typeof fooSchema)<T>>>
// expected result: type Foo<T> = { name: string, date: T }
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we implement _Instantiation Expressions_ which provide the ability to specify type arguments for generic functions or generic constructors without actually calling them. For example:

```ts
function makeBox<T>(value: T) {
    return { value };
};

const makeStringBox = makeBox<string>;  // (value: string) => { value: string }
const stringBox = makeStringBox('abc');  // { value: string }

const ErrorMap = Map<string, Error>;  // new () => Map<string, Error>
const errorMap = new ErrorMap();  // Map<string, Error>
```

Above, the instantiation expression `makeBox<string>` changes the type of `makeBox` from `<T>(value: T) => { value: T }` to the more specific type `(value: string) => { value: string }`. When emitted to JavaScript, instantiation expressions simply have the type arguments erased.

Instantiation expressions are particularly useful for creating specific instantiations of generic class constructors such as the `ErrorMap` above. Previously, this could only be accomplished with a type annotation or a redundant subclass:

```ts
const makeStringBox: (value: string) => { value: string } = makeBox;
class ErrorMap extends Map<string, Error> {}
```

The argument to the `typeof` type operator can now be an instantiation expression. For example:

```ts
type StringBoxMaker = typeof makeBox<string>;  // (value: string) => { value: string }
type ErrorMapConstructor = typeof Map<string, Error>;  // new () => Map<string, Error>
```

A particularly useful pattern is to create generic type aliases for applications of `typeof` that reference type parameters in type instantiation expressions:

```ts
type BoxFunc<T> = typeof makeBox<T>;  // (value: T) => { value: T }
type Box<T> = ReturnType<typeof makeBox<T>>;  // { value: T }
type StringBox = Box<string>;  // { value: string }
```

Notice how `Box<T>` captures the inferred return type of a generic function without loosing the generic type. This was previously not possible.

The type of an instantiation expression `f<T>` is determined as follows:

* If `f` is an object type, `f<T>` produces an object type in wherein generic signatures for which `<T>` is an applicable type argument list are instantiated with the given type arguments. Non-applicable signatures, including non-generic signatures, are elided, but other object type members (such as properties) are unaffected. An error occurs if `f` has signatures, but none for which `<T>` is an applicable type argument list.
* If `f` is a union or intersection type, `f<T>` produces a union or intersection type where the type argument list `<T>` has been applied to each constituent.
* If `f` is a generic type, `f<T>` applies the type argument list `<T>` to the constraint of the type of `f`.
* If `f` is of any other type, `f<T>` has the same type as `f`.

Note that an instantiation expression can be applied to any type, but that an error occurs if no call or construct signatures are present in the type. For example, an instantiation expression can be applied to a union that includes `undefined`:

```ts
function f(makeBox: (<T>(value: T) => T) | undefined) {
    const makeStringBox = makeBox<string>;  // ((value: string) => string) | undefined
    if (makeStringBox) {
        const box = makeStringBox('abc');
    }
}
```

Fixes #37181.
Fixes #40542.

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
Can we allow apply type parameter partially?

For example:
```ts
const ErrorMap = <T,> Map<T, Error>; // apply second parameter: <T,>( new () =>Map<T, Error>)
const StringErrorMap = ErrorMap<string>; // apply first parameter:  new () =>Map<string, Error>
const errorMap = new StringErrorMap(); // Map<string, Error>
```

Also, we may write some type like this:
```
type MyObject = <T, U>{
    getT: () => T | undefined;
    setT: (x: T) => void;
    getU: () => U[];
    setU: (u: U[]) => void;
}
declare const myObject: MyObject
const myObjectString = <U,> myObject<string, U>
const myObjectStringNumber = myObjectString<number>
myObjectStringNumber.setT('str')
myObjectStringNumber.setU([])
```

**Comment by Harpush** [comment]
@ahejlsberg This is super close to a solution of #37181. Will it will allow us to do:
```ts
function makeBox<T>(value: T) {
    return { value };
};

// Can we do it or something similar? Currently doesn't compile :(
type MakeBox<T> = ReturnType<typeof makeBox<T>>

// As it now allows us to do (no generics though)
const stringMakeBox = makeBox<string>;
type MakeBox = ReturnType<typeof stringMakeBox>

// And even more relevant to support generics if we can now do:
type MakeBox = ReturnType<typeof makeBox<string>>
```

Up to now `makeBox<string>` was illegal without calling it. But now that it is supported allowing `typeof` on it seems to fit nicely.

**Comment by g-plane** [comment]
Building the TypeScript playground for this PR would be better.

**Comment by ahejlsberg** [comment]
> This is super close to a solution of #37181. Will it will allow us to do...

Yes, you can indeed use that pattern to capture a generic return type of a generic function. This is something that previously wasn't possible. I'll update the PR description to include an example.

**Comment by Jack-Works** [comment]
Let's say we have a function f have a call signature `f<T extends number, Q>()` and a construct signature `new f<T extends string>()`

What will this PR behave? They have different argument counts and even different different type constraints

**Comment by ahejlsberg** [comment]
> Let's say we have a function f have a call signature f<T extends number, Q>() and a construct signature new f<T extends string>()

This works just fine:

```ts
declare const f: {
    <T extends number, Q>(): [T, Q];
    new <T extends string>(): [T];
};

type T0 = typeof f<string>;  // new () = [string]
type T1 = typeof f<number, string>;  // () => [number, string]
```

But an error occurs here:

```ts
declare const g: {
    <T extends number>(): [T];
    new <T extends string>(): [T];
};

type T2 = typeof g<string>;  // Error, type 'string' does not satisfy the constraint 'number'
```

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -31399,6 +31404,70 @@ namespace ts {
...
+                hasApplicableSignature = false;
+                const result = getInstantiatedTypeWorker(type);
+                hasSomeApplicableSignature ||= hasApplicableSignature;
+                if (hasSignatures && !hasApplicableSignature) {
+                    nonApplicableType ??= type;
+                }
+                return result;
+            }
+
+            function getInstantiatedTypeWorker(type: Type): Type {
```
Comment (weswigham) [inline src/compiler/checker.ts:31442]: I feel like there should probably also be a deferred version that is instantiated for indexed accesses or type parameters, since if a type parameter is constrained to a thing-with-signatures-with-type-arguments it's arguably reasonable to say you want to instantiate them (later).

Also, not looking into conditionals feels a bit odd - shouldn't it instantiate the conditional, but with the true and false branch types instantiated?

File: tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressions.ts [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+function f35(f: (new <T>(a: T) => T) | (<U>(a: U, b: number) => U[])) {
+    let fs = f<string>;  // (new (a: string) => string) | ((a: string, b: number) => string[]])
+}
+
+function f36(f: (new <T>(a: T) => T) | ((a: string, b: number) => string[])) {
+    let fs = f<string>;  // Error, '(a: string, b: number) => string[]' has no applicable signatures
+}
+
+function f37(f: (<T>(a: T) => T) | (new (a: string, b: number) => string[])) {
+    let fs = f<string>;  // Error, 'new (a: string, b: number) => string[]' has no applicable signatures
```
Comment (weswigham) [inline tests/cases/conformance/types/typeParameters/typeArgumentLists/instantiationExpressions.ts:133]: Can these all return `fs`, so we can double check how declaration emit serializes these types? And ensure we have some cases where function-level generics are involved? (As signature constraints, parameters, and return types)

File: tests/baselines/reference/genericCallsWithoutParens.errors.txt [hunk 3]
```diff
@@ -1,12 +1,9 @@
-tests/cases/compiler/genericCallsWithoutParens.ts(2,18): error TS1005: '(' expected.
 tests/cases/compiler/genericCallsWithoutParens.ts(7,8): error TS1384: A 'new' expression with type arguments must always be followed by a parenthesized argument list.
 
 
-==== tests/cases/compiler/genericCallsWithoutParens.ts (2 errors) ====
+==== tests/cases/compiler/genericCallsWithoutParens.ts (1 errors) ====
     function f<T>() { }
     var r = f<number>; // parse error
```
Comment (jakebailey) [inline tests/baselines/reference/genericCallsWithoutParens.errors.txt:6]: Tiny nit, but this comment (and maybe others like it) could probably be removed since the purpose of this change is to make this legal.

**Comment by sandersn** [comment]
Testing `user test inline` on a PR that *doesn't* intentionally break the build:
@typescript-bot user test this inline

**Comment by paavohuhtala** [comment]
Is there a way to make this work for generic functions where you want to instantiate one or more parameters and keep the rest generic? The specific case I'm interested in is [`createAsyncThunk`](https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk) from Redux Toolkit. Currently you have to manually specify all three type parameters, even though the compiler can always infer two of them.

**Comment by ahejlsberg** [comment]
> Is there a way to make this work for generic functions where you want to instantiate one or more parameters and keep the rest generic?

No, similar to generic function calls, when you specify type arguments you must specify all of them (modulo defaults, of course, which also work in instantiation expressions).

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -31399,6 +31404,70 @@ namespace ts {
...
+                    hasSignatures ||= resolved.callSignatures.length !== 0 || resolved.constructSignatures.length !== 0;
+                    hasApplicableSignature ||= callSignatures.length !== 0 || constructSignatures.length !== 0;
+                    if (callSignatures !== resolved.callSignatures || constructSignatures !== resolved.constructSignatures) {
+                        const result = createAnonymousType(undefined, resolved.members, callSignatures, constructSignatures, resolved.indexInfos) as ResolvedType & InstantiationExpressionType;
+                        result.objectFlags |= ObjectFlags.InstantiationExpressionType;
+                        result.node = node;
+                        return result;
+                    }
+                }
+                else if (type.flags & TypeFlags.Intersection) {
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts:31456]: Instantiable types (including substitution types) with constraint types that have applicable signatures are replaced with instantiations of those constraint types. Otherwise instantiable types are simply left unchanged.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:31442]: See my comment above regarding instantiable types. As we discussed yesterday, it is possible to imagine a deferred type constructor that applies a given type argument list to a given type, but this would (a) require new type syntax that is distinct from existing generic type reference syntax and (b) add a significant amount of complexity to type relations, type instantiation, and type inference. Unless there are some really compelling real world scenarios, I'd rather not go there.

**Comment by xiaoxiangmoe** [comment]
> > Is there a way to make this work for generic functions where you want to instantiate one or more parameters and keep the rest generic?
> 
> No, similar to generic function calls, when you specify type arguments you must specify all of them (modulo defaults, of course, which also work in instantiation expressions).

But if we use class or function, we can specify some type arguments. For example:

```ts
// class
class ErrorMap<T> extends Map<T, Error> {}
class StringErrorMap extends ErrorMap<string> {}
const errorMap = new StringErrorMap();

// function
function makeTuple<First, Second>(first: First, second: Second): [first: First, second: Second] {
    return [first, second];
}
const makeStringToAnyTuple: <Second>(first: string, second: Second) => [first: string, second: Second] = makeTuple;
const makeStringToNumberTuple: (first: string, second: number) => [first: string, second: number] =
    makeStringToAnyTuple;
const stringToNumberTuple = makeStringToNumberTuple('str', 0);
```

**Comment by ahejlsberg** [comment]
> It will be great if we can apply it partially

I guess I'm not convinced particular type argument application is common enough to merit the complexity. As you show in your examples, you can always just use a type annotation or a type assertion.

**Comment by orta** [comment]
( It _might_ need a rebase to build the playground: https://github.com/microsoft/TypeScript-Make-Monaco-Builds/runs/4968925596?check_suite_focus=true#step:7:353 )

**Comment by xiaoxiangmoe** [comment]
> I guess I'm not convinced partial type argument application is common enough to merit the complexity. As you show in your examples, you can always just use a type annotation or a type assertion.

In the StringErrorMap example, it use redundant subclass, so it create useless runtime code.

File: tests/baselines/reference/genericCallsWithoutParens.errors.txt (hunk 3 above)
Comment (ahejlsberg) [reply tests/baselines/reference/genericCallsWithoutParens.errors.txt:6]: Now fixed.

**Comment by ahejlsberg** [comment]
With latest commits, for consistency and better error tolerance, parsing of type argument lists in member expressions is more permissive. For example `f<number>.g<string>` is now permitted (even though the type argument list on `f` affects only signatures and not the member `g`).

File: src/compiler/checker.ts (hunk 1 above)
Comment (treybrisbane) [reply src/compiler/checker.ts:31442]: @ahejlsberg I believe a notable real-world use case for what you're describing is generators, as correctly typing them requires specifying a type-level function to derive a `yield` expression's result type from its operand type. #32523, essentially. That would improve the generator experience significantly for libraries like `co`, `redux-saga`, etc.

I'd personally love to see such a feature at some point, but I agree that it's a tougher sell on the complexity side.

**Comment by xiaoxiangmoe** [comment]
```ts
declare let f: { <T>(): T, g<U>(): U };
f<number>.g<string>
```

It seems that it would be better if we allow 

```ts
declare let f:  <T extends any>{ (): T, g<U>(x: T): U };
f<number>.g<string>
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:31442]: @treybrisbane Actually, I was talking about some new type constructor `F<<T>>` that would represent applying the type argument list `T` to the type `F` (totally made up syntax here). Effectively a deferred version of what this PR implements. What you're talking about, I think, is higher-kinded types, i.e. the ability to have generic types take other generic types as type arguments. That's an even more complex feature request, discussed in #1213.

**Comment by buschtoens** [comment]
Would it be possible to add this ability to generics passed as generic arguments?

I've tried three different approaches with the [build from above](https://github.com/microsoft/TypeScript/pull/47607#issuecomment-1023370466), but none work.

```ts
const users = [
  { id: 'ahejlsberg', name: 'Anders' },
  { id: 'sandersn', name: 'Nathan' },
] as const;

const getId = <T extends { id: string }>(obj: T): T['id'] => obj.id;

// This works, because `getId` is in scope and not passed as a generic.
declare const manuallyKeyedUsers: {
  [Idx in Exclude<keyof typeof users, keyof []>
    as ReturnType<typeof getId<typeof users[Idx]>>
  ]: typeof users[Idx];
};

// All the following don't work.

declare function keyedA<
  TArray extends readonly unknown[],
  TKeyFor extends <TElement extends TArray[number]>(
    element: TElement,
  ) => keyof any,
>(array: TArray, keyFor: TKeyFor): {
    [Idx in Exclude<keyof TArray, keyof []>
      as ReturnType<typeof keyFor<TArray[Idx]>>
    ]: TArray[Idx];
  }

declare function keyedB<
  TArray extends readonly unknown[],
>(
  array: TArray,
  keyFor: <TElement extends TArray[number]>(element: TElement) => keyof any
): {
    [Idx in Exclude<keyof TArray, keyof []>
      as ReturnType<typeof keyFor<TArray[Idx]>>
    ]: TArray[Idx];
  }

declare function keyedC<
  TArray extends readonly unknown[],
  TKeyFor extends <TElement extends TArray[number]>(
    element: TElement,
  ) => keyof any,
>(array: TArray, keyFor: TKeyFor): {
    [Idx in Exclude<keyof TArray, keyof []>
      as TKeyFor extends <TElement extends TArray[number]>(
        element: TElement,
      ) => infer R ? R : never
    ]: TArray[Idx];
  }

const keyedUsersA = keyedA(users, getId);
const keyedUsersB = keyedB(users, getId);
const keyedUsersC = keyedC(users, getId);
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (treybrisbane) [reply src/compiler/checker.ts:31442]: Ahh, my bad! Yeah I slightly misinterpreted your comment. 😅

Apologies!

**Comment by Andarist** [comment]
I have no idea yet how I utilize this but it seems that I can sort of use this to defer the application of the generic type arguments which wasn't previously possible in such a way (as far I know). Thanks for the hard work on this feature!

<details>
<summary>Wonky experiment how to use this syntax (for curious readers)</summary>

```ts
declare function indexEvents<TEvent extends { type: string }>(ev: TEvent): {
  [Ev in TEvent as Ev["type"]]: Ev
}

declare function createMachine<
  TEvent extends { type: string },
  T extends { indexEvents: typeof indexEvents }
>(config: {
  schema: {
    events: TEvent
  }
  tsTypes: T
}): {
  send: <Type extends keyof ReturnType<typeof config.tsTypes.indexEvents<TEvent>>>(
    type: Type,
    payload: Omit<ReturnType<typeof config.tsTypes.indexEvents<TEvent>>[Type], 'type'>
  ) => void;
}

const machine = createMachine({
  schema: {
    events: {} as { type: 'FOO', count: number } | { type: 'BAR', answer: string }
  },
  tsTypes: {} as {
    indexEvents: typeof indexEvents
  }
})

machine.send('FOO', { count: 132 })
// @ts-expect-error
machine.send('BAR', { count: 132 })
```
</details>

**Comment by devanshj** [comment]
I think we're too close to being able to write higher kinded types...

```ts
type List<T> =
  & T[]
  & { __type: <T>(t: T) => List<T> }
  & { __functor: true }

type UnknownAdt = { __type: <T>(t: T) => unknown }
type UnknownFunctor = UnknownAdt & { __functor: true }
declare const map:
  <T extends UnknownFunctor, B>
    ( t: T
    , f: (a: T extends ReturnType<typeof t.__type<infer A>> ? A : never) => B
    ) =>
      ReturnType<typeof t.__type<B>>

let t0: List<"B"> = map({} as List<"A">, t => {
  let _test: "A" = t
  return "B" as const
})
```

But turns out this doesn't work because `t` in the type context is `<T>(t: T) => unknown` instead of `<T>(t: T) => List<T>`.

A minimal version of this would be...

```ts
let xs = {} as string[] & { __type: <T>(t: T) => T[], __comonad: true }
let x: string = extract(xs)

declare const extract:
  <T extends { __type: <T>(t: T) => unknown, __comonad: true }>
    (t: T) =>
      T extends ReturnType<typeof t.__type<infer A>> ? A : never
```

This doesn't compile as `extract(xs)` is `unknown` instead of `string`, but can we do something to make this work?

**Comment by millsp** [comment]
@devanshj we need callback/reference types https://github.com/Microsoft/TypeScript/issues/1213#issuecomment-523245130

**Comment by devanshj** [comment]
Yeah a proper solution would be great ofc but was wondering if we could tweak this PR a bit to make it work.

For static-land style the tweak I'm hoping for still won't be enough as we do `pipe(adt, map(f))` instead of `map(adt, f)`, but nonetheless it could be leveraged elsewhere.

**Comment by n1ru4l** [comment]
@typescript-bot pack this

___

Link is dead I am just trying to re-pack if possible 😇

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Comment by phi0411141** [comment]
Hi, can I know which future typescript version to land this? really hope to have this awesome feature.

**Comment by ahejlsberg** [comment]
@phi0411141 This should land in 4.7.

**Comment by DanielRosenwasser** [comment]
I guess one thing I should ask is whether by doing this, we would still have some potential to grow if we ever wanted to do something like https://github.com/microsoft/TypeScript/issues/35986 or https://github.com/microsoft/TypeScript/issues/22509#issuecomment-372785068.

**Comment by zedryas** [comment]
Not a seasoned typescript programme but will it allow  the same with generics, allowing if we know the expression is a function to add a yet unknown type ?

given a `curry` implementation:

```typescript

const curriedAppend = <A> curry ((a: A, array: Array <A>) => [a, ...A])
```

**Comment by ahejlsberg** [comment]
> I guess one thing I should ask is whether by doing this, we would still have some potential to grow if we ever wanted to do something like https://github.com/microsoft/TypeScript/issues/35986 or https://github.com/microsoft/TypeScript/issues/22509#issuecomment-372785068.

There really isn't such a thing as an instantiation expression for a getter/setter since an access always implies a call. So, I don't think those possible features wouldn't be affected by this feature.

**Comment by jcalz** [comment]
Am I right in thinking that this can't be used purely at the type level (e.g., specify type parameters for generic function *types*) and that we need to drop down to the value level (e.g., specify type parameters for generic function *values*)?  [This SO question](https://stackoverflow.com/q/71337888/2887218) wants to do something like

```ts
type X = Array<string>["map"]<number>; // 👎
``` 

but as far as I know that's impossible and you need to find or pretend to find an actual function of the right type:

```ts
type M = Array<string>["map"];
declare const m: M;
type X = typeof m<number>; // 👍
// type X = (callbackfn: 
//  (value: string, index: number, array: string[]) => number, 
//  thisArg?: any
// ) => number[]
```

[Playground link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302#code/PQKgsAUALgngDgUwAQA0kF4kEEBOOCGMAPAM5Q4CWAdgOYB8A2gEQC2+cTAukVQK4sAjBDjoBuJMGBJAvBuA5HciSksRKgxIAFAGN8AGx0D8mgNYAzKgC4kCqRoBuu3gktlKtADRJqAEwQAPS3yCwh74eITO5NQ0DJwAlBh0SIFCOB7WSEoAFhQkuDQA-Jb4VDDp8eiJycIxkCDAkJDKyACyargExC5RjKzsXKKQPpo6ociaAPZUZEgsls0D0PDIaJhN4yYzPPwpYhJS0oCyO+lNqphauvqGphZWEIp2Dk5IXe6eVD7+SdvBSKEdEa5onEEl8gqlbvcoNlcjgCkUSmUQVUcDUIEA)

Do I have that right or am I missing something?

**Comment by ahejlsberg** [comment]
> Am I right in thinking that this can't be used purely at the type level

Correct, instantiation expressions currently have no equivalent in type land. We can't just co-opt the `T<X>` type instantiation syntax since it already means something else (i.e. apply type arguments to the generic type `T`). At least, if we did, it wouldn't be immediately obvious whether `T<X>` means "apply type arguments to generic type T" or "apply type arguments to generic signatures in type T (without instantiating T itself)".

**Comment by tonyxiao** [comment]
Did this feature get released in 4.7? Somehow when I try the example with ts version `4.7.4` (latest as of today) it complains in the editor. 

CleanShot 2022-07-21 at 09 40 21@2x

**Comment by DrSensor** [comment]
It doesn't works on build-ins method 🤔
https://www.typescriptlang.org/play?jsx=0#code/FAYw9gdgzgLgBCAhiAFgUzgXjhNB3OAdTUQGsBZRABwB5g44BBAGnrgCU0YBXAJwgAqATypoaMEWjAAzOAHkARgCs0IGAG0ARAHMucvBAAKvMKN4SAImigheASyowwvKJoC6NRgD4vcAPR+cGi8JrzAXgAUAJQA3MCgkLBwiFhwAN5wCgBccACMcAC+wBKiTKklUrKI8eDQ8AAm1iCUVKmKKmoAdLow+kYmZpZN9o7OUJ6RiFFAA
```ts
const cache = new WeakMap<
  A,
  ReturnType<typeof Object["getOwnPropertyDescriptors"]<A>> // error
>();

const a = { b: 1 }
type A = typeof a

const descMap = Object.getOwnPropertyDescriptors<A>(a)
```
```error
    'A' only refers to a type, but is being used as a value here.
    Variable 'ReturnType' implicitly has an 'any' type.
    Conversion of type '{ b: number; }' to type '<T>(o: T) => { [P in keyof T]: TypedPropertyDescriptor<T[P]>; } & { [x: string]: PropertyDescriptor; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
      Type '{ b: number; }' provides no match for the signature '<T>(o: T): { [P in keyof T]: TypedPropertyDescriptor<T[P]>; } & { [x: string]: PropertyDescriptor; }'.
    ',' expected.
    '>' expected.
    Expression expected.
    Expression expected.
    Expression expected.
```

**Comment by Andarist** [comment]
You cant use brackets, just qualified names:

https://www.typescriptlang.org/play?jsx=0#code/FAYw9gdgzgLgBCAhiAFgUzgXjhNB3OAdTUQGsBZRABwB5g44BBAGnrgCU0YBXAJwgAqATypoaMEWjAAzOAHkARgCs0IGADoA5lzl4IABV5hRvCQBE0UELwCWVGGF5QajAHyu4wVwAoAlAG5gUEhYOEQsOABvOAUALjgARjgAX2AJUSYI9KlZRCDwaHgAE0sQSioIxRU1LR09Q2M0UyELK1t7R2c3b0RfIA

**Comment by herjiict** [comment]
How to use this feature with overloaded functions ?

```typescript
declare function foo<T extends keyof HTMLElementTagNameMap>(arg: T): HTMLElementTagNameMap[T];
declare function foo<T extends HTMLElement>(arg: T): T;
type FirstFoo = typeof foo<"div">;    // error
const f: ReturnType<FirstFoo> = foo("div");
```

I couldn't get the code to work. The error message is `Type 'string' does not satisfy the constraint 'HTMLElement'.`
Why does it have to satisfy both `foo`s ? How to pick the first `foo` ?

[https://www.typescriptlang.org/play?ts=4.9.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVeEADwxFWAGd4BrEATx0XgAkSBZAGQCiEEAFsaGElADmAOShieUAA4A+ABSwpALngkAlDu78ho8ZNnyQipQG0SAXQDcAKFCRYCFOmx4CxMpTUtAxGgsJiqBjqmjr6sS4YLEoIAGJYMHQYKYTwALzwicnsfkQARMBYAG6lKi5geJlIOgBKIBjIMKgkSSBEaRlZhCp5fmrlVaV6LkA](https://www.typescriptlang.org/play?ts=4.9.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVeEADwxFWAGd4BrEATx0XgAkSBZAGQCiEEAFsaGElADmAOShieUAA4A+ABSwpALngkAlDu78ho8ZNnyQipQG0SAXQDcAKFCRYCFOmx4CxMpTUtAxGgsJiqBjqmjr6sS4YLEoIAGJYMHQYKYTwALzwicnsfkQARMBYAG6lKi5geJlIOgBKIBjIMKgkSSBEaRlZhCp5fmrlVaV6LkA)

**Comment by Thundercraft5** [comment]
Higher-order instantiation expressions don't resolve properly, as they weren't accounted for in the test baseline (#52035).
```ts
declare function transform<
    const A extends readonly any[], 
    F extends <
        V extends A[number], 
        K extends keyof A,
    >(value: V, index: K, array: A) => any
>(array: [...A], func: F): { [K in keyof A]: ReturnType<typeof func<A[K], K>> };

const $2 = transform(["object", "string", "number"], k => ({ type: k }));
    // ^?
    // Should be [{ type: "object" }, { type: "string" }, { type: "number" }], but is [any, any, any]
 ```
https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.0.0-dev.20221220#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxilQGdEcYBbAHgCh4H4w8SN4BBeEADwxFWAl4cKMDwQAnvGISA2gF0ANPHqMAYl179B8Oo33wAapr4Ch7WamSUARiBhKVBxgGkT2oQGsQEnIg6KqgwAfAAUAG5QEMggAFxGylgCPPEuyrBEEvHsAJTwALzB0qgStGEZUFnwsgB0deyOKOjxajnxAN7Vbknw3r7+DfEASiAYyDCoACoSAA4g1BizIH5IaGDUFi6OLsFFAL4A3LS0zKRsACQATAUERKTkVKGyAEQ4NgBW4BjPys+sMEkAOY-eDPKy2ezPRyeApFUKdRZzeIwvY5HJHfQAekx8AAegB+ILwbHwADKAAscMgIMB4HZqgilvFXh8vs94HtlIykaD-kD2Zz4Ny4qDwXYYAL5EA

**Comment by jedwards1211** [comment]
> Correct, instantiation expressions currently have no equivalent in type land. 

Is there any issue tracking a design for a way we could do that?

I've been trying to do something that I'd be able to accomplish if I could have a type like

```ts
// type ApplyFn<Fn, Arg> = (some magic...)
type Applied = ApplyFn<<T>(value: T) => { value: T }, 1 | 2 | 3> // { value: 1 | 2 | 3 }
```

**Comment by iFwu** [comment]
It also solves #20719.

**Comment by darrylnoakes** [comment]
> > Correct, instantiation expressions currently have no equivalent in type land.
> 
> Is there any issue tracking a design for a way we could do that?
> 
> I've been trying to do something that I'd be able to accomplish if I could have a type like
> 
> ```ts
> // type ApplyFn<Fn, Arg> = (some magic...)
> type Applied = ApplyFn<<T>(value: T) => { value: T }, 1 | 2 | 3> // { value: 1 | 2 | 3 }
> ```
> 
> Someone correct me if I'm wrong but it seems there's no way to do this for an arbitrary function.

I don't believe there is. Instantiation expressions only work for values; you can't use a similar method in types.
I tried to work around the lack of higher-order generics by using a generic function type, but I think the core limitations are the same, so it's not supported. The function-type type parameter is said to be not generic.

```typescript
type Fn = <Arg>() => unknown
type ApplyFn<T, F extends Fn> = T extends unknown ? ReturnType<F<T>> : never

const f = <T>(): [T] => ({} as [T])

type t1 = ApplyFn<1 | 2, typeof f>
```

The following (direct instead of the type parameter) works:

```typescript
type ApplyFn<T> = T extends unknown ? ReturnType<typeof f<T>> : never

type t1 = ApplyFn<1 | 2>
//   ^? [1] | [2]
```
