### PR TITLE
Fixed issues with inference from nested tuple types of the same shape

### LINKED ISSUE #48524: Nested array incorrectly infer children type to unknown when given a single element
# Bug Report

### 🔎 Search Terms

nested, infer, inference, unknown

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220402#code/C4TwDgpgBAsghgcwJYGMA8ANAfFAvFDKCAD2AgDsATAZygG06lyAzCAJygE0AaKAOgFNWHAPoBdXgL5D2UcVAD8XKAC4o5CADd2AbgBQe0JCgAlPLESo0DcgFcAtgCN2YsTgD07qIBlyKLfIA1uQA9gDu5Ibg0CYATObwyOg2Ds5svDGuHl6AoOTqKeyRxiYAzPGWSXR2Ti68dJlQnlC5ValAA)

### 💻 Code

```ts
type Magic<X> = X extends [[infer Y, ...infer _], ...infer _] ? Y : never;

type R = Magic<[[number]]> // ❌ unknown
type R2 = Magic<[[number, 2]]> // ✅ number
type R3 = Magic<[[number], []]> // ✅ number
```

### 🙁 Actual behavior

- `Magic<[[whatever]]>` is `unknown`

### 🙂 Expected behavior

- `Magic<[[whatever]]>` should be `whatever`

### LINKED ISSUE #52722: Improve inference of Recursive types
# Suggestion

It would be nice to be able to infer all variants from a recursive type. [Playground link.](https://www.typescriptlang.org/play?#code/PTAEGUFEBUFUAUBQiSkgOgObtAMwPYBOoAdgKYDOALmQCagVkA2ZAxlQIYBGLoTAltQqIqATwAOZUACU2AV0IV+ANzIAeAJK0AfKAC8oAN6JQp0P1oAuUFpNnWAC35NahMiWtuOtfCSaiZeUUVdS1tAG0AXUQAX2RUADE5EnZ+X1AqfFA3KgUSUA4mJnNaCjxCfABbDIcpMUlEXGTU9MwyKi0KTR0ACn4aSopPMm9ff0DWBSVVbojIgEprLSijO1McvNAV1A3CfOVCuSlBUnwqc0rxIk4SKlj4sEgADQBBAFl4ABlIUFhwF4A4pBkKxfNRzAMygZwsZUGZTAA9AD8axK1gA5Bx0QAaVGOZyudzWGGo+EWDFcHGk+xOFxuDxbaLwmLRFkFMqgkjgigcKiCXD8SjZEY+PwBWSTYIzaiEfgkTBzEFg84ELIGNodUp9SHzFBgeHIvVoJ7wSAAYWgkAAItYegAiDh20AAH1Adq4dvmUSAA)

```ts
// SETUP

// E.g. for nested selectable lists
type Recursive<Id> = {
    id: Id
    children: readonly Recursive<Id>[]
}

// Function to return all ids from the type
function getIds<Id>(items: readonly Recursive<Id>[]): Id[] {
    return [] // return value is not important
}

// EXAMPLE USAGE

const items = [{
    id: 'a',
    children: [{
        id: 'b',
        children: []
    }]
}] as const satisfies readonly Recursive<string>[]

const foo = getIds(items)
// EXPECTED: ("a" | "b")[] but returns just "a"[]
```

## 🔍 Search Terms

recursive types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
It might be breaking from types perspective if some code relies on the current behaviour.
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Generics inside recursive types would be expanded.

## 📃 Motivating Example

E.g. for selectable nested lists, we could provide auto-complete for `onSelect(itemId: <union of all ids from recursive type>)`.

## 💻 Use Cases

I haven't found a workaround that would work for the `getIds` function in the example. One semi working workaround is written below - it returns correctly union of all ids literals, but TS shows an error and it cannot be used as return value for `getIds(...)` because then TS show that the type is recursive and possible infinite.

```ts
type GetRecursiveType<T extends readonly Recursive<any>[]> = T[number]['id'] | (T[number]['children'] extends undefined ? never : GetRecursiveType<T[number]['children']>)
```

[Playground link.](https://www.typescriptlang.org/play?#code/PTAEGUFEBUFUAUBQiSkgOgObtAMwPYBOoAdgKYDOALmQCagVkA2ZAxlQIYBGLoTAltQqIqATwAOZUACU2AV0IV+ANzIAeAJK0AfKAC8oAN6JQp0P1oAuUFpNnWAC35NahMiQD81tx1r4STKIy8ooq6lraANoAuogAvsiokAAaAIIAsvAAMpCgsOCpAOKQyKz+1OY0ALYU+qCRxmbmVqAA5BytADR2po7Oru7WDT1NzdatXF0jTX0ubiRDjaPLFuOsU8vLswML9bGboHH7ZnGdRtNmq220G5vb80PHpqfnB1etZLdbTnODeyNHeLRUAcWplEgVCgcKiCXD8SigHx+AJBWSsBRKVRqaiEfgkTBRWIiCRSQpkKhojFhaAktTQUBkAAeNBItFqSP8gWC6NCWI4JFEhN0BmgkRIciqXDIhGikVaFlawIAPqAABSi8WS6Wy1r3dyKhnM9xs0ByVlkOHkegeUhkVTEaxkikhTFkGmSOliiVSmVyvUkRXaACUxMkoGSEbqTspvLdtLEknwuEqZBq2hQYFMAD0PEA)

### PR DESCRIPTION
**Pull request by Andarist**
fixes #48524
fixes #52722

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20929,8 +20929,7 @@ namespace ts {
                     return type.symbol;
                 }
                 if (isTupleType(type)) {
-                    // Tuple types are tracked through their target type
-                    return type.target;
+                    return type;
```
Comment (Andarist) [inline src/compiler/checker.ts:20932]: I'm not overly confident that it's the correct **shape** of this fix but all tests pass. 

The problem was that for the inner tuple the same recursion identity was computed here as the `type.target` was shared between those tuples (as they have the same shape). And thus `invokeOnce` was skipping over `action(source, target)` call there while inferring for the inner tuple.

This check is done within this if statement:
https://github.dev/microsoft/TypeScript/blob/942d2a91c115f22857513a9d3f4bde2fb1521f50/src/compiler/checker.ts#L20918-L20919

However, this still goes into this if statement for a tuple because it doesn't satisfy the `isObjectOrArrayLiteralType(type)` check. I think that perhaps a better fix here would be to make a change to this if condition. I've tried this alternative patch and all tests seem to be passing to:
<details>
<summary>Alternative patch</summary>

```diff
diff --git a/src/compiler/checker.ts b/src/compiler/checker.ts
index 7bcc6f5bdc..efce2901b4 100644
--- a/src/compiler/checker.ts
+++ b/src/compiler/checker.ts
@@ -20916,7 +20916,7 @@ namespace ts {
         // reference the type have a recursion identity that differs from the object identity.
         function getRecursionIdentity(type: Type): object {
             // Object and array literals are known not to contain recursive references and don't need a recursion identity.
-            if (type.flags & TypeFlags.Object && !isObjectOrArrayLiteralType(type)) {
+            if (type.flags & TypeFlags.Object && !isObjectOrArrayLiteralType(type) && !isTupleType(type)) {
                 if (getObjectFlags(type) && ObjectFlags.Reference && (type as TypeReference).node) {
                     // Deferred type references are tracked through their associated AST node. This gives us finer
                     // granularity than using their associated target because each manifest type reference has a
@@ -20928,10 +20928,6 @@ namespace ts {
                     // exclude the static side of classes from this check since it shares its symbol with the instance side.
                     return type.symbol;
                 }
-                if (isTupleType(type)) {
-                    // Tuple types are tracked through their target type
-                    return type.target;
-                }
             }
             if (type.flags & TypeFlags.TypeParameter) {
                 return type.symbol;
```
</details>

The comment above the `isTupleType` suggests that it's checking if the type was written as literal tuple type:
https://github.dev/microsoft/TypeScript/blob/942d2a91c115f22857513a9d3f4bde2fb1521f50/src/compiler/checker.ts#L21278-L21282
and the comment above the mentioned condition suggests that we don't want to go into this block if a type was written as literal (it only mentions arrays and objects though):
https://github.dev/microsoft/TypeScript/blob/942d2a91c115f22857513a9d3f4bde2fb1521f50/src/compiler/checker.ts#L20918

So perhaps this `isTupleType` check shouldn't be inside this if block from the start?

**Comment by ycmjason** [comment]
❤️

**Comment by RyanCavanaugh** [comment]
@ahejlsberg LGTY? This has shown up with a few manifestations

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by Andarist** [comment]
@ahejlsberg do u have a suggested fix for this in mind or should I investigate this?

**Comment by Andarist** [comment]
That doesn't seem to cut it. I'm gonna investigate why sometime later today.

**Comment by weswigham** [comment]
Ah, probably because we call `getNormalizedType` on tuples which replaces them with their normalized form, removing the alias data.

**Comment by ahejlsberg** [comment]
I have a fix for this. We solved a similar problem in `isDeeplyNestedType` by tracking whether type IDs are increasing as we move up the recursion tracking stack. Increasing type IDs indicate newly generated types, and those we want to count, whereas decreasing type IDs indicate manually written instantiations that we don't want to count. However, the circularity checking in `invokeOnce` doesn't use `isDeeplyNestedType`, so it doesn't benefit from this. But with this change it can:

```ts
        function invokeOnce<Source extends Type, Target extends Type>(source: Source, target: Target, action: (source: Source, target: Target) => void) {
            const key = source.id + "," + target.id;
            const status = visited && visited.get(key);
            if (status !== undefined) {
                inferencePriority = Math.min(inferencePriority, status);
                return;
            }
            (visited || (visited = new Map<string, number>())).set(key, InferencePriority.Circularity);
            const saveInferencePriority = inferencePriority;
            inferencePriority = InferencePriority.MaxValue;
            // We stop inferring and report a circularity if we encounter duplicate recursion identities on both
            // the source side and the target side.
            const saveExpandingFlags = expandingFlags;
            (sourceStack ??= []).push(source);
            (targetStack ??= []).push(target);
            if (isDeeplyNestedType(source, sourceStack, sourceStack.length, 2)) expandingFlags |= ExpandingFlags.Source;
            if (isDeeplyNestedType(target, targetStack, targetStack.length, 2)) expandingFlags |= ExpandingFlags.Target;
            if (expandingFlags !== ExpandingFlags.Both) {
                action(source, target);
            }
            else {
                inferencePriority = InferencePriority.Circularity;
            }
            targetStack.pop();
            sourceStack.pop();
            expandingFlags = saveExpandingFlags;
            visited.set(key, inferencePriority);
            inferencePriority = Math.min(inferencePriority, saveInferencePriority);
        }
```

Plus change the declarations of `sourceStack` and `targetStack` to have type `Type[]`.

Best I can tell this takes care of the problem.

**Comment by ahejlsberg** [comment]
I can put up a PR with these changes. Alternatively, @Andarist you can put up a new PR.

**Comment by Andarist** [comment]
@ahejlsberg if u already have the fix then go for it :)
