### PR TITLE
Fix completions when the ts installation and project are on two different windows drive

### LINKED ISSUE #35512: TS Server hangs for project stored on on non c drive on windows
From https://github.com/microsoft/vscode/issues/85889

**TypeScript Version:** 3.7.3 and 3.8.0-dev.20191203

**Search Terms:**
- windows
- drive letters

**Repo**
1. On a drive that is not the c drive on windows:
1. `git clone https://github.com/Cellv2/vscode-insiders-bug-85889.git`
1. `npm i` for project
1. Open project in vs code 
1. Open `app.js` and try triggering suggestions

**Bug:**
TS Server init never completes and responses are not answered. It has constant low level cpu usage while this is happening

Here are my logs for this example:

```
Info 0    [16:37:40.110] Starting TS Server
Info 1    [16:37:40.114] Version: 3.8.0-dev.20191204
Info 2    [16:37:40.114] Arguments: C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe C:\Users\matb\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-3.8.20191204\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\matb\AppData\Local\Temp\vscode-typescript\9c97b768be3daf882608\tscancellation-7ab71b73753edf7124a4.tmp* --logVerbosity verbose --logFile c:\Users\matb\AppData\Roaming\Code - Insiders\logs\20191204T160449\exthost1\vscode.typescript-language-features\tsserver-log-YLV9O7\tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [16:37:40.115] Platform: win32 NodeVersion: 12 CaseSensitive: false
Info 4    [16:37:40.128] Binding...
Info 5    [16:37:40.157] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":10744}}
Info 6    [16:37:40.161] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true}}}
Info 7    [16:37:40.162] Host information vscode
Info 8    [16:37:40.163] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 9    [16:37:40.164] 0::configure: async elapsed time (in milliseconds) 2.8071
Info 10   [16:37:40.164] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Info 11   [16:37:40.167] Scheduled: *ensureProjectForOpenFiles*
Perf 12   [16:37:40.167] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 3.1956
Info 13   [16:37:40.167] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 14   [16:37:40.167] request:
    {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"v:/vscode-insiders-bug-85889/src/App.js","fileContent":"import React from 'react';\r\nimport {\r\n  BrowserRouter as Router,\r\n  Switch,\r\n  Route,\r\n  Link,\r\n  useRouteMatch,\r\n  useParams\r\n} from \"react-router-dom\";\r\n\r\nimport logo from './logo.svg';\r\nimport './App.css';\r\n\r\n//intellisense broken here\r\n\r\n\r\n\r\nfunction App() {\r\n  return (\r\n    <div className=\"App\">\r\n      <header className=\"App-header\">\r\n        <img src={logo} className=\"App-logo\" alt=\"logo\" />\r\n        <p>\r\n          Edit <code>src/App.js</code> and save to reload.\r\n        </p>\r\n        <a\r\n          className=\"App-link\"\r\n          href=\"https://reactjs.org\"\r\n          target=\"_blank\"\r\n          rel=\"noopener noreferrer\"\r\n        >\r\n          Learn React\r\n        </a>\r\n      </header>\r\n    </div>\r\n  );\r\n}\r\n\r\nexport default App;\r\n","projectRootPath":"v:\\vscode-insiders-bug-85889","scriptKindName":"JS"}]}}
Info 15   [16:37:40.170] Search path: v:/vscode-insiders-bug-85889/src
Info 16   [16:37:40.172] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/src/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: v:/vscode-insiders-bug-85889/src/App.js Status: File added to open files impacted by this config file
Info 17   [16:37:40.172] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/src/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: v:/vscode-insiders-bug-85889/src/App.js Status: File added to open files impacted by this config file
Info 18   [16:37:40.173] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: v:/vscode-insiders-bug-85889/src/App.js Status: File added to open files impacted by this config file
Info 19   [16:37:40.173] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: v:/vscode-insiders-bug-85889/src/App.js Status: File added to open files impacted by this config file
Info 20   [16:37:40.173] For info: v:/vscode-insiders-bug-85889/src/App.js :: No config files found.
Info 21   [16:37:40.178] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/src/tsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Open file was set as Inferred root
Info 22   [16:37:40.179] FileWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/src/tsconfig.json 2000 Project:  WatchType: Config file for the inferred project root
Info 23   [16:37:40.183] ConfigFilePresence:: Current Watches: Config file for the inferred project root:: File: v:/vscode-insiders-bug-85889/src/tsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Updated the callback
Info 24   [16:37:40.183] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/src/jsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Open file was set as Inferred root
Info 25   [16:37:40.184] FileWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/src/jsconfig.json 2000 Project:  WatchType: Config file for the inferred project root
Info 26   [16:37:40.185] ConfigFilePresence:: Current Watches: Config file for the inferred project root:: File: v:/vscode-insiders-bug-85889/src/jsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Updated the callback
Info 27   [16:37:40.185] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/tsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Open file was set as Inferred root
Info 28   [16:37:40.185] ConfigFilePresence:: Current Watches: Noop Config file for the inferred project root:: File: v:/vscode-insiders-bug-85889/tsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Updated the callback
Info 29   [16:37:40.185] ConfigFilePresence:: Current Watches: :: File: v:/vscode-insiders-bug-85889/jsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Open file was set as Inferred root
Info 30   [16:37:40.185] ConfigFilePresence:: Current Watches: Noop Config file for the inferred project root:: File: v:/vscode-insiders-bug-85889/jsconfig.json Currently impacted open files: RootsOfInferredProjects: v:/vscode-insiders-bug-85889/src/App.js OtherOpenFiles:  Status: Updated the callback
Info 31   [16:37:40.199] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 32   [16:37:40.692] DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/src 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 33   [16:37:40.692] v for path v:/vscode-insiders-bug-85889/src not found in cache...
Info 34   [16:37:40.692] Starting C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe with args:
    ["C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/watchGuard.js","v:/vscode-insiders-bug-85889/src"]
Info 35   [16:37:40.983] WatchGuard for path v:/vscode-insiders-bug-85889/src returned: OK
Info 36   [16:37:41.4] Elapsed:: 312ms DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/src 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 37   [16:37:41.24] DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/node_modules 1 Project:  WatchType: node_modules for closed script infos in them
Info 38   [16:37:41.24] watchDirectory for v:/vscode-insiders-bug-85889/node_modules uses cached drive information.
Info 39   [16:37:41.57] Elapsed:: 33ms DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/node_modules 1 Project:  WatchType: node_modules for closed script infos in them
Info 40   [16:37:42.823] DirectoryWatcher:: Added:: WatchInfo: C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 41   [16:37:42.823] c for path C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules not found in cache...
Info 42   [16:37:42.823] Starting C:\Users\matb\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe with args:
    ["C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/watchGuard.js","C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules"]
Info 43   [16:37:43.148] WatchGuard for path C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules returned: OK
Info 44   [16:37:43.149] Elapsed:: 326ms DirectoryWatcher:: Added:: WatchInfo: C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 45   [16:37:45.370] DirectoryWatcher:: Added:: WatchInfo: c:/users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules 1 Project:  WatchType: node_modules for closed script infos in them
Info 46   [16:37:45.370] watchDirectory for c:/users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules uses cached drive information.
Info 47   [16:37:45.371] Elapsed:: 1ms DirectoryWatcher:: Added:: WatchInfo: c:/users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules 1 Project:  WatchType: node_modules for closed script infos in them
Info 48   [16:37:47.353] DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/node_modules 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 49   [16:37:47.353] watchDirectory for v:/vscode-insiders-bug-85889/node_modules uses cached drive information.
Info 50   [16:37:47.355] Elapsed:: 2ms DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/node_modules 1 Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 51   [16:37:47.403] DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/node_modules/@types 1 Project: /dev/null/inferredProject1* WatchType: Type roots
Info 52   [16:37:47.403] watchDirectory for v:/vscode-insiders-bug-85889/node_modules/@types uses cached drive information.
Info 53   [16:37:47.410] Elapsed:: 7ms DirectoryWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/node_modules/@types 1 Project: /dev/null/inferredProject1* WatchType: Type roots
Info 54   [16:37:47.412] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: true Elapsed: 7213ms
Info 55   [16:37:47.412] Project '/dev/null/inferredProject1*' (Inferred) 
Info 56   [16:37:47.413] 	Files (51)
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es5.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.scripthost.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.core.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.collection.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.generator.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.promise.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.full.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/global.d.ts
	v:/vscode-insiders-bug-85889/node_modules/csstype/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/prop-types/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/global.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/csstype/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/prop-types/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/DOMUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createBrowserHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createHashHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createMemoryHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/LocationUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/PathUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router-dom/index.d.ts
	v:/vscode-insiders-bug-85889/src/App.js
	v:/vscode-insiders-bug-85889/node_modules/@babel/types/lib/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__generator/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__traverse/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@babel/parser/typings/babel-parser.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__template/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__core/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/eslint-visitor-keys/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-coverage/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-report/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-reports/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/json-schema/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/q/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/stack-utils/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs-parser/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs/index.d.ts

Info 57   [16:37:47.413] -----------------------------------------------
Info 58   [16:37:47.416] Scheduling throttled operation:
    {"projectName":"/dev/null/inferredProject1*","fileNames":["C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es5.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.iterable.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.webworker.importscripts.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.scripthost.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.core.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.collection.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.generator.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.iterable.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.promise.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.proxy.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.reflect.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.array.include.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.full.d.ts","v:/vscode-insiders-bug-85889/src/App.js"],"compilerOptions":{"module":1,"target":3,"jsx":1,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"noEmitForJsFiles":true,"maxNodeModuleJsDepth":2},"typeAcquisition":{"enable":true,"include":[],"exclude":[]},"unresolvedImports":[],"projectRootPath":"v:/vscode-insiders-bug-85889","kind":"discover"}
Info 59   [16:37:47.417] Scheduling request for: /dev/null/inferredProject1*
Info 60   [16:37:47.422] Project '/dev/null/inferredProject1*' (Inferred) 0
Info 60   [16:37:47.422] 	Files (51)
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es5.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.scripthost.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.core.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.collection.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.generator.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.promise.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.full.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/global.d.ts
	v:/vscode-insiders-bug-85889/node_modules/csstype/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/prop-types/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/global.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/csstype/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/prop-types/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/DOMUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createBrowserHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createHashHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createMemoryHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/LocationUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/PathUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router-dom/index.d.ts
	v:/vscode-insiders-bug-85889/src/App.js
	v:/vscode-insiders-bug-85889/node_modules/@babel/types/lib/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__generator/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__traverse/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@babel/parser/typings/babel-parser.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__template/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__core/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/eslint-visitor-keys/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-coverage/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-report/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-reports/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/json-schema/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/q/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/stack-utils/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs-parser/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs/index.d.ts

Info 60   [16:37:47.422] -----------------------------------------------
Info 60   [16:37:47.422] Open files: 
Info 60   [16:37:47.422] 	FileName: v:/vscode-insiders-bug-85889/src/App.js ProjectRootPath: v:/vscode-insiders-bug-85889
Info 60   [16:37:47.422] 		Projects: /dev/null/inferredProject1*
Perf 60   [16:37:47.422] 2::updateOpen: elapsed time (in milliseconds) 7255.1747
Info 61   [16:37:47.423] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":2,"success":true,"body":true}
Info 62   [16:37:47.423] Running: *ensureProjectForOpenFiles*
Info 63   [16:37:47.423] Structure before ensureProjectForOpenFiles:
Info 64   [16:37:47.423] Project '/dev/null/inferredProject1*' (Inferred) 0
Info 64   [16:37:47.424] 	Files (51)
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es5.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.scripthost.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.core.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.collection.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.generator.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.promise.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.full.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/global.d.ts
	v:/vscode-insiders-bug-85889/node_modules/csstype/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/prop-types/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/global.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/csstype/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/prop-types/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/DOMUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createBrowserHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createHashHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createMemoryHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/LocationUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/PathUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router-dom/index.d.ts
	v:/vscode-insiders-bug-85889/src/App.js
	v:/vscode-insiders-bug-85889/node_modules/@babel/types/lib/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__generator/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__traverse/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@babel/parser/typings/babel-parser.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__template/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__core/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/eslint-visitor-keys/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-coverage/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-report/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-reports/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/json-schema/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/q/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/stack-utils/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs-parser/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs/index.d.ts

Info 64   [16:37:47.424] -----------------------------------------------
Info 64   [16:37:47.424] Open files: 
Info 64   [16:37:47.424] 	FileName: v:/vscode-insiders-bug-85889/src/App.js ProjectRootPath: v:/vscode-insiders-bug-85889
Info 64   [16:37:47.424] 		Projects: /dev/null/inferredProject1*
Info 64   [16:37:47.424] Structure after ensureProjectForOpenFiles:
Info 65   [16:37:47.424] Project '/dev/null/inferredProject1*' (Inferred) 0
Info 65   [16:37:47.424] 	Files (51)
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es5.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.scripthost.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.core.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.collection.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.generator.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.iterable.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.promise.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.proxy.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.reflect.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.array.include.d.ts
	C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.full.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/global.d.ts
	v:/vscode-insiders-bug-85889/node_modules/csstype/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/prop-types/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/global.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/csstype/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/prop-types/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/DOMUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createBrowserHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createHashHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/createMemoryHistory.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/LocationUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/PathUtils.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/history/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router/index.d.ts
	C:/Users/matb/AppData/Local/Microsoft/TypeScript/3.8/node_modules/@types/react-router-dom/index.d.ts
	v:/vscode-insiders-bug-85889/src/App.js
	v:/vscode-insiders-bug-85889/node_modules/@babel/types/lib/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__generator/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__traverse/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@babel/parser/typings/babel-parser.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__template/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/babel__core/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/eslint-visitor-keys/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-coverage/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-lib-report/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/istanbul-reports/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/json-schema/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/q/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/stack-utils/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs-parser/index.d.ts
	v:/vscode-insiders-bug-85889/node_modules/@types/yargs/index.d.ts

Info 65   [16:37:47.424] -----------------------------------------------
Info 65   [16:37:47.424] Open files: 
Info 65   [16:37:47.424] 	FileName: v:/vscode-insiders-bug-85889/src/App.js ProjectRootPath: v:/vscode-insiders-bug-85889
Info 65   [16:37:47.424] 		Projects: /dev/null/inferredProject1*
Info 65   [16:37:47.424] got projects updated in background, updating diagnostics for v:/vscode-insiders-bug-85889/src/App.js
Info 66   [16:37:47.424] event:
    {"seq":0,"type":"event","event":"projectsUpdatedInBackground","body":{"openFiles":["v:/vscode-insiders-bug-85889/src/App.js"]}}
Info 67   [16:37:47.427] request:
    {"seq":3,"type":"request","command":"geterr","arguments":{"delay":0,"files":["v:/vscode-insiders-bug-85889/src/App.js"]}}
Perf 68   [16:37:47.428] 3::geterr: async elapsed time (in milliseconds) 1.0041
Info 69   [16:37:47.430] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"v:/vscode-insiders-bug-85889/src/App.js","diagnostics":[]}}
Info 70   [16:37:47.438] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"v:/vscode-insiders-bug-85889/src/App.js","diagnostics":[]}}
Info 71   [16:37:47.639] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":3}}
Info 72   [16:37:47.640] Sending request:
    {"projectName":"/dev/null/inferredProject1*","fileNames":["C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es5.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.dom.iterable.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.webworker.importscripts.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.scripthost.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.core.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.collection.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.generator.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.iterable.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.promise.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.proxy.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.reflect.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.array.include.d.ts","C:/Users/matb/.vscode-insiders/extensions/ms-vscode.vscode-typescript-next-3.8.20191204/node_modules/typescript/lib/lib.es2016.full.d.ts","v:/vscode-insiders-bug-85889/src/App.js"],"compilerOptions":{"module":1,"target":3,"jsx":1,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"noEmitForJsFiles":true,"maxNodeModuleJsDepth":2},"typeAcquisition":{"enable":true,"include":[],"exclude":[]},"unresolvedImports":[],"projectRootPath":"v:/vscode-insiders-bug-85889","kind":"discover"}
Info 73   [16:37:47.642] request:
    {"seq":4,"type":"request","command":"geterr","arguments":{"delay":0,"files":["v:/vscode-insiders-bug-85889/src/App.js"]}}
Perf 74   [16:37:47.642] 4::geterr: async elapsed time (in milliseconds) 0.6562
Info 75   [16:37:47.643] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"v:/vscode-insiders-bug-85889/src/App.js","diagnostics":[]}}
Info 76   [16:37:47.644] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"v:/vscode-insiders-bug-85889/src/App.js","diagnostics":[]}}
Info 77   [16:37:47.816] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"v:/vscode-insiders-bug-85889/src/App.js","diagnostics":[{"start":{"line":2,"offset":1},"end":{"line":9,"offset":27},"text":"All imports in import declaration are unused.","code":6192,"category":"suggestion","reportsUnnecessary":true}]}}
Info 78   [16:37:47.817] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":4}}
Info 79   [16:37:52.715] request:
    {"seq":5,"type":"request","command":"configure","arguments":{"file":"v:/vscode-insiders-bug-85889/src/App.js","formatOptions":{"tabSize":2,"indentSize":2,"convertTabsToSpaces":true,"newLineCharacter":"\n","insertSpaceAfterCommaDelimiter":true,"insertSpaceAfterConstructor":false,"insertSpaceAfterSemicolonInForStatements":true,"insertSpaceBeforeAndAfterBinaryOperators":true,"insertSpaceAfterKeywordsInControlFlowStatements":true,"insertSpaceAfterFunctionKeywordForAnonymousFunctions":true,"insertSpaceBeforeFunctionParenthesis":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces":true,"insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces":false,"insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces":false,"placeOpenBraceOnNewLineForFunctions":false,"placeOpenBraceOnNewLineForControlBlocks":false,"semicolons":"ignore"},"preferences":{"quotePreference":"auto","allowTextChangesInNewFiles":true,"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true}}}
Info 80   [16:37:52.715] Host configuration update for file v:/vscode-insiders-bug-85889/src/App.js
Info 81   [16:37:52.715] response:
    {"seq":0,"type":"response","command":"configure","request_seq":5,"success":true}
Perf 82   [16:37:52.715] 5::configure: async elapsed time (in milliseconds) 0.6855
Info 83   [16:37:52.718] request:
    {"seq":6,"type":"request","command":"completionInfo","arguments":{"file":"v:/vscode-insiders-bug-85889/src/App.js","line":16,"offset":1,"includeExternalModuleExports":true,"includeInsertTextCompletions":true,"includeAutomaticOptionalChainCompletions":true}}
Info 84   [16:37:52.723] getCompletionData: Get current token: 0
Info 85   [16:37:52.723] getCompletionData: Is inside comment: 0
Info 86   [16:37:52.723] getCompletionData: Get previous token 1: 0
Info 87   [16:37:52.723] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 88   [16:37:52.735] getSymbolsFromOtherSourceFileExports: Recomputing list
Info 89   [16:37:52.752] FileWatcher:: Added:: WatchInfo: v:/vscode-insiders-bug-85889/package.json 250 Project:  WatchType: package.json file for import suggestions
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #35512

### CODE REVIEW

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -232,6 +231,14 @@ namespace ts.moduleSpecifiers {
                 }
                 sortedPaths.push(...pathsInDirectory);
             }
+            const newDirectory = getDirectoryPath(directory);
+            if (newDirectory === directory) break;
+            directory = newDirectory;
+        }
+        if (allFileNames.size) {
+            const remainingPaths = arrayFrom(allFileNames.values());
+            if (remainingPaths.length > 1) remainingPaths.sort(comparePathsByNumberOfDirectrorySeparators);
```
Comment (sandersn) [inline src/compiler/moduleSpecifiers.ts]:
```suggestion
            if (remainingPaths.length > 1) remainingPaths.sort(comparePathsByNumberOfDirectorySeparators);
```

**Comment by sheetalkamat** [comment]
@typescript-bot please cherry-pick this to typescript-3.7

**Comment by sheetalkamat** [comment]
@typescript-bot cherry-pick this to release-3.7
