### PR TITLE
Avoid `convertExport` when there's a non-identifier or a bogus one

### LINKED ISSUE #44105: Cannot read property 'length' of undefined
Imported from microsoft/tsserverfuzzer#314

**Repo Name**: https://github.com/yarnpkg/yarn.git

**Revision**: 3119382885ea373d3c13d6a846de743eca8c914b

**TypeScript Version**: 4.3.0-dev.20210410

**Commands**: 

```
{"response":[],"responseRequired":true}
{"command":"format","arguments":{"endLine":3,"endOffset":1,"line":3,"offset":1,"file":"D:/local/Temp/fuzzerWorkingDir/yarn/src/util/normalize-manifest/licenses.js","options":{}},"type":"request","seq":26}
{"response":[],"responseRequired":true}
{"command":"getCodeFixes","arguments":{"errorCodes":[1],"startLine":3,"startOffset":1,"endLine":3,"endOffset":1,"file":"D:/local/Temp/fuzzerWorkingDir/yarn/src/util/normalize-manifest/licenses.js"},"type":"request","seq":27}
{"response":[],"responseRequired":true}
{"command":"getApplicableRefactors","arguments":{"startLine":3,"startOffset":1,"endLine":3,"endOffset":1,"file":"D:/local/Temp/fuzzerWorkingDir/yarn/src/util/normalize-manifest/licenses.js"},"type":"request","seq":27}
{"response":[{"name":"Convert export","description":"Convert default export to named export","actions":[{"name":"Convert default export to named export","description":"Convert default export to named export","kind":"refactor.rewrite.export.named"}]}],"responseRequired":true}
{"command":"getApplicableRefactors","arguments":{"startPosition":30,"endPosition":31,"file":"D:/local/Temp/fuzzerWorkingDir/yarn/src/util/normalize-manifest/licenses.js"},"type":"request","seq":28}
{"response":[{"name":"Convert export","description":"Convert default export to named export","actions":[{"name":"Convert default export to named export","description":"Convert default export to named export","kind":"refactor.rewrite.export.named"}]}],"responseRequired":true}
{"command":"getEditsForRefactor-full","arguments":{"refactor":"Convert export","action":"Convert default export to named export","startPosition":30,"endPosition":31,"file":"D:/local/Temp/fuzzerWorkingDir/yarn/src/util/normalize-manifest/licenses.js"},"type":"request","seq":29}
(Showing last 10 of 96829 commands)
```

**Code** ([`src\util\normalize-manifest\licenses.js`](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/util/normalize-manifest/licenses.js)):

```js
  /* @flow */
  
  /* eslint-disable max-len */
//                 ^
  
  /**
```

**Hash**: 118a1b4b6ad0276ad98f166743ace4f4
**Stack trace**: 
```
Cannot read property 'length' of undefined
    at escapeLeadingUnderscores (tsserverlibrary.js:12173:28)
    at createBaseIdentifier (tsserverlibrary.js:21609:35)
    at createIdentifier (tsserverlibrary.js:21621:24)
    at makeExportSpecifier (tsserverlibrary.js:148021:143)
    at changeExport (tsserverlibrary.js:147894:32)
    at doChange (tsserverlibrary.js:147886:13)
    at <anonymous> (tsserverlibrary.js:147833:94)
    at ChangeTracker.with (tsserverlibrary.js:138743:17)
    at getEditsForAction (tsserverlibrary.js:147833:62)
    at getEditsForRefactor (tsserverlibrary.js:139972:41)
```

### PR DESCRIPTION
**Pull request by elibarzilay**
Fixes #44105

### CODE REVIEW

File: src/services/refactors/convertExport.ts [hunk 1]
```diff
@@ -23,6 +23,9 @@ namespace ts.refactor {
             if (!info) return emptyArray;
 
             if (!isRefactorErrorInfo(info)) {
+                if (!(isIdentifier(info.exportName) && context.program.getTypeChecker().getSymbolAtLocation(info.exportName))) {
+                    return emptyArray;
```
Comment (andrewbranch) [inline src/services/refactors/convertExport.ts:27]: Check with @jessetrinity on this; it might be preferable to edit `getInfo` and return a `notApplicableReason` for this. Also, why do we need to check that we can resolve a symbol here?

Comment (elibarzilay) [reply src/services/refactors/convertExport.ts:27]: Re the question: later in `changeImports`, if `getSymbolAtLocation()` returns undefined, it throws a debugging failure.  (This happens with the third test: `/*[| |]*/ /** x */ export default x;`)

I initially made it just ignore these cases, but then I thought that the assertion means that it really wants to get there only when it can do something so I moved the test to here.  If it makes more sense to do nothing when it sees later that it doesn't resolve, then I'll move it.

File: tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+/////*[| |]*/ /** x */ export default 1;
+
+// @Filename: /b.js
+/////*[| |]*/ /** x */ export default (1);
+
+// @Filename: /c.js
+/////*[| |]*/ /** x */ export default x;
+
+goTo.eachRange(r => {
+    goTo.selectRange(r);
```
Comment (sandersn) [inline tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts:15]: interesting, do you have to select each range? I thought having the cursor there would be enough.

File: src/services/refactors/convertExport.ts [hunk 3]
```diff
@@ -152,8 +156,7 @@ namespace ts.refactor {
         }
     }
 
-    function changeImports(program: Program, { wasDefault, exportName, exportingModuleSymbol }: ExportInfo, changes: textChanges.ChangeTracker, cancellationToken: CancellationToken | undefined): void {
-        const checker = program.getTypeChecker();
+    function changeImports(program: Program, { wasDefault, exportName, exportingModuleSymbol }: ExportInfo, changes: textChanges.ChangeTracker, checker: TypeChecker, cancellationToken: CancellationToken | undefined): void {
```
Comment (sandersn) [inline src/services/refactors/convertExport.ts:159]: Why does changeImports need a checker parameter? No code changed.

**Review by sandersn — CHANGES_REQUESTED** [review]
Couple of additional questions. I personally think returning emptyArray is OK for a bug fix, but I agree that we should get @jessetrinity's opinion.

File: src/services/refactors/convertExport.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/refactors/convertExport.ts:27]: Oh, I completely missed the parentheses wrapping both conditions—I read this as “if it’s not an identifier but there _is_ a symbol there,” hence my confusion. Returning early when there’s _not_ a resolvable symbol makes total sense. My bad.

File: tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts (hunk 2 above)
Comment (elibarzilay) [reply tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts:15]: But there are three ranges in three files...  In any case, existing cases use markers, which I didn't want to mix with a comment.

File: src/services/refactors/convertExport.ts (hunk 3 above)
Comment (elibarzilay) [reply src/services/refactors/convertExport.ts:159]: It was creating the checker locally before (in the line I removed after this line).  The ugly thing is that `changeExport` did require a checker argument, so I made them both symmetric in requiring the argument and using the same one for both (in `doChange`).

File: src/services/refactors/convertExport.ts (hunk 1 above)
Comment (jessetrinity) [reply src/services/refactors/convertExport.ts:27]: Yep, returning a `RefactorErrorInfo` from `getInfo` would be preferable, something like
`{ error: getLocaleSpecificMessage(Diagnostics.Can_only_convert_named_export) }`

File: src/services/refactors/convertExport.ts (hunk 3 above)
Comment (RyanCavanaugh) [reply src/services/refactors/convertExport.ts:159]: Does this function work if the `checker` given to it didn't come from the same `program` ? Seems unlikely (?). Since the function is effectively free I'm not sure what's being gained here.

File: tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts (hunk 2 above)
Comment (jessetrinity) [reply tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts:15]: The cursor there alone is not _supposed_ to be enough unless invoked by the refactor command, because I thought it would be too annoying. See https://github.com/microsoft/TypeScript/blob/master/tests/cases/fourslash/refactorConvertExportForTriggerReason.ts

File: src/services/refactors/convertExport.ts (hunk 3 above)
Comment (elibarzilay) [reply src/services/refactors/convertExport.ts:159]: They're both internal single-use functions, so no gain.  It just looked a little off that `.getTypeChecker` was used outside of one function and inside the other:

    function doChange(...) {
        changeExport(..., program.getTypeChecker());
        changeImports(program, ...);
    }
    function changeExport(..., checker) ...
    function changeImports(program, ...) {
        const checker = program.getTypeChecker();
        ...
    }

so I made it once outside,

    function doChange(...) {
        const checker = program.getTypeChecker();
        changeExport(..., checker);
        changeImports(..., checker);
    }
    function changeExport(..., checker) ...
    function changeImports(..., checker) ...

It's not important so if it's confusing I'll revert it.

**Comment by elibarzilay** [comment]
@jessetrinity: I made it an error now.  I think that there is one minor difference to the previous code where it returns this error instead of `undefined`, but no changes to tests.

File: tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts (hunk 2 above)
Comment (sandersn) [reply tests/cases/fourslash/refactorConvertExport_onlyValidIdentifiers.ts:15]: OK. Some refactors are offered in cases other than explicit invoking of the refactor command, right? I always forget about that.

**Review by sandersn — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Review by jessetrinity — APPROVED** [review]
