### PR TITLE
Fixed trimming comments on the remaining range

### LINKED ISSUE #45526: Format Document doesn't work when .ts file has {tab}{tab}/*{tab} in it
*TS Template added by @mjbvz*

**TypeScript Version**: 4.4.1

**Search Terms**
- format
- formatting
- indent

---

Issue Type: <b>Bug</b>

With the below code in a file named bug.ts, pressing Shift+Alt+F does not format the document. If I delete one of the three tabs, then it does format the document.

```ts
		function foo() {}
}
	/*
		
*/
```

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.95GB free)|
|Process Argv|--disable-extensions --crash-reporter-id f6d40bd1-e748-48ce-9355-576b0aa9ce40|
|Screen Reader|no|
|VM|44%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30351386
vstre464:30350172
bridge0723:30353136
vsdyn321cf:30354108

```

</details>

### PR DESCRIPTION
**Pull request by armanio123**
Fixes #45526 

The bug above happens because the "remaining range" contains all comments that are last in the range. This have already been trimmed in `indentTriviaItems` creating duplicate edits.

This PR fixes that by excluding from the remaining range the comment trivia.

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
I don't understand this very deeply, so it would be nice to get another reviewer

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -432,13 +432,12 @@ namespace ts.formatting {
             if (leadingTrivia) {
                 indentTriviaItems(leadingTrivia, indentation, /*indentNextTokenOrTrivia*/ false,
```
Comment (gabritto) [inline src/services/formatting/formatting.ts:433]: how does `indentTriviaItems` already get rid of trailing whitespace for trivia?

File: src/services/formatting/formatting.ts [hunk 2]
```diff
@@ -432,13 +432,12 @@ namespace ts.formatting {
             if (leadingTrivia) {
                 indentTriviaItems(leadingTrivia, indentation, /*indentNextTokenOrTrivia*/ false,
                     item => processRange(item, sourceFile.getLineAndCharacterOfPosition(item.pos), enclosingNode, enclosingNode, /*dynamicIndentation*/ undefined!));
+                if (options.trimTrailingWhitespace !== false) {
+                    trimTrailingWhitespacesForRemainingRange(leadingTrivia);
```
Comment (gabritto) [inline src/services/formatting/formatting.ts:436]: why don't we need to call `trimTrailingWhitespacesForRemainingRange` in the above case when `isOnToken()` is true?

**Review by gabritto — COMMENTED** [review]
Since I'm not very familiar with this, I left some questions so that I can understand a few things before I can fully review it.

File: src/services/formatting/formatting.ts (hunk 1 above)
Comment (armanio123) [reply src/services/formatting/formatting.ts:433]: If there's leading trivia on the node, we first parse those in `indentTriviaItems`. This method pretty much apply rules for trivia only (i.e. indenting multiline/single line). The later `trimTrailingWhitespacesForRemainingRange`, used to ignore this trivia and cause some changes to conflict between them.

File: src/services/formatting/formatting.ts (hunk 2 above)
Comment (armanio123) [reply src/services/formatting/formatting.ts:436]: `trimTrailingWhitespacesForRemainingRange()` should only be use for leading trivia I believe. By the time `isOnToken()` is false that means we're at the end of the file or at trivia after processing the previous nodes or outside the original range; otherwise we'll require to process the node like we're doing in on the previous lines.

Hope this clarifies it.

**Review by gabritto — APPROVED** [review]
Thanks for the explanations!
