### PR TITLE
`typeof x` now has a string literal union type

### LINKED ISSUE #9506: Typeof comparison expression should check right hand side value
As I understood `typeof` operator can only return `undefined`, `object`, `boolean`, `number`, `string`, `symbol`, `function.`

If the RHS is a string literal, I think it should check against the above values and throw an error on:
```ts
const str = 'str';
if (typeof str === 'd') {// error right hand side can only be `undefined`, `object`, ...
}
```

### LINKED ISSUE #13771: typeof foo === "array" causes type narrowing
**TypeScript Version:**  2.1.5 / nightly (2.2.0-dev.20170130)

**Code**

```ts
function mixedMessages(): string | Array<string> {
    return ["Our relationship is strong", "so we should see other people."];
}

const ourRelationship = mixedMessages();

if (typeof ourRelationship === "array") {
    throw new Error("There can be only one.");
}

console.log(ourRelationship.substring(0, 10));
```

**Expected behavior:**

Compilation should fail with a type error, because in the final line, `ourRelationship` has type `string | Array<string>`, and arrays do not have a `substring` method.

**Actual behavior:**

The if-throw is misinterpreted as a type narrowing from `string | Array<string>` to `string`. Compilation succeeds, and the generated javascript produces the runtime type error `ourRelationship.substring is not a function`.

I'm no pro at javascript, so maybe this is an allowance for some obscure browser/environment which handles `typeof` differently, but in all the environments I looked at, `typeof [] === "object"`.

### PR DESCRIPTION
**Pull request by sandersn**
`typeof x` now has the string literal type `'string' | 'number' | 'boolean' | 'symbol' | 'undefined' | 'object' | 'function'`. This will prevent typos and misunderstandings of `typeof` (eg `typeof a === "array"` or `typeof o === "null"`). And once #13789 is fixed, it will also provide completions.

For implementations that disobey the advice of the standard, it is easy to work around the type, although narrowing no longer works:

```ts
if (typeof x === "ActiveXObject" as string) {
  // no narrowing here
} else {
  // or here
}
```

Fixes #9506 
Fixes #13771 (by making the incorrect narrowing an error)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14609,7 +14609,7 @@ namespace ts {
 
         function checkTypeOfExpression(node: TypeOfExpression): Type {
             checkExpression(node.expression);
-            return stringType;
+            return getUnionType(arrayFromMap(typeofEQFacts.keys(), s => getLiteralTypeForText(TypeFlags.StringLiteral, s)));
```
Comment (vladima) [inline src/compiler/checker.ts]: can this union type be precomputed and cached to avoid doing the same work multiple times?

Comment (sandersn) [inline src/compiler/checker.ts]: Yes. I wasn't sure where to put it though.

Comment (sandersn) [inline src/compiler/checker.ts]: Take a look at the new commit; I added a new `typeofType` that is created when the checker is.

Note that it changes the print order of string literal unions slightly. I think this is because 'string', 'symbol', etc are added to a union very early in the creation of the checker.

File: src/compiler/core.ts [hunk 2]
```diff
@@ -895,6 +895,14 @@ namespace ts {
         return result;
     }
 
+    export function arrayFromMap<T, U>(iterator: Iterator<T>, f: (value: T) => U) {
```
Comment (vladima) [inline src/compiler/core.ts]: I'd say this is `iteratorToArray` to `arrayFromIterator` since there is nothing map specific in the signature

Comment (sandersn) [inline src/compiler/core.ts]: I meant map in the sense of the `map` function not the `Map` type. Maybe `mapIterator`? `mapIteratorToArray`? Something else?

Comment (vladima) [inline src/compiler/core.ts]: maybe `convertToArray`?

Comment (sandersn) [inline src/compiler/core.ts]: I like that one.

File: tests/baselines/reference/typeGuardOfFormTypeOfOther.errors.txt [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+    var boolOrC: boolean | C;
+    var emptyObj: {};
+    var c: C;
+    
+    // A type guard of the form typeof x === s, 
+    // where s is a string literal with any value but 'string', 'number' or 'boolean',
+    //  - when true, removes the primitive types string, number, and boolean from the type of x, or
+    //  - when false, has no effect on the type of x.
+    
+    if (typeof strOrC === "Object") {
```
Comment (vladima) [inline tests/baselines/reference/typeGuardOfFormTypeOfOther.errors.txt]: is intent here to make `C` object in the true branch and string - in false one?

Comment (sandersn) [inline tests/baselines/reference/typeGuardOfFormTypeOfOther.errors.txt]: I believe so. Javascript doesn't work that way, of course, so that's why this PR makes it an error.

Note that since 2.0 it has worked this way. Previously, the false branch had no effect on the type of x.

**Comment by treshugart** [comment]
@mhegazy Hey, got linked to this from the interwebs. Was going to adopt TS in SkateJS but it looks like you're making a breaking change as part of a patch milestone?

**Comment by mhegazy** [comment]
Can you elaborate on how SkateJS would be broken by this change?

**Comment by sandersn** [comment]
2.2.0 is 2.2 RC; 2.2.1 is the release version of 2.2.

**Comment by treshugart** [comment]
> Can you elaborate on how SkateJS would be broken by this change?

We're not using it *yet*, but just breaking Skate doesn't concern me. Possibly breaking every consumer on a minor version does. I could be wrong, but this appears to be a change between the 2.1.x stable, minor range to the 2.2.x stable, minor range, correct? I could have easily missed something here.

> 2.2.0 is 2.2 RC; 2.2.1 is the release version of 2.2.

I apologise for my ignorance, I just couldn't infer that 2.2.1 was the stable after the 2.2 rc. Thanks for clarifying :)

**Comment by mhegazy** [comment]
I see, thanks for the explanation. 

We make *all* changes that could result in an error, if previously was not, as "breaking" changes. We promise no breaking changes in revisions, e.g. `2.2.1` -> `2.2.2`. but not in minor version upgrades e.g. `2.1` -> `2.2`. We recommend that you fix your `package.json` to `major.moinor` of TypeScript. Please see https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes for the full list of breaking changes in the the past.

This change makes the type of `typeof` expressions to be `'string' | 'number' | 'boolean' | 'symbol' | 'undefined' | 'object' | 'function'`, which should cover all values you would get from one of the popular JS engines. The reason it is marked as breaking, is per the ES spec, an engine *could* generate a different value, so this is a "breaking change" if you happen to be running against an engine (that is not v8, chackra, spidermoneky, or Core).

**Comment by BenSayers** [comment]
What the reasoning behind not following [semver](http://semver.org)? [Npm docs recommend](https://docs.npmjs.com/getting-started/semantic-versioning) that modules follow server and will automatically allow minor bumps in a module by default. I'm concerned that by not following this convention will create unnecessary friction for TypeScript consumers who will by default be opted in to having their builds broken whenever typescript releases a minor version.

**Comment by sandersn** [comment]
@BenSayers @treshugart the official semver issue is at #14116. You can read some of our reasoning and continue the discussion there.
