### PR TITLE
Fix double error on invalid delete of readonly property

### LINKED ISSUE #53082: Double error on invalid delete of readonly property
# Bug Report

### 🔎 Search Terms

operand delete operator double diagnostic error

### 🕗 Version & Regression Information

- This changed between versions 3.9 and 4.0

Before 4.0, we only gave one error here. In 4.0 and above, we give two errors.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.9.5#code/MYGwhgzhAEBiD29oG8C+AoAJgUxNgLtnIgHQB2YAttgNxA)

### 💻 Code

```ts
class Foo {}
delete Foo.name;
```

### 🙁 Actual behavior

Two errors

### 🙂 Expected behavior

One error

### PR DESCRIPTION
**Pull request by shinichy**
Fixes #53082. This PR added a unit test based on https://github.com/microsoft/TypeScript/pull/53961.

### CODE REVIEW

**Comment by shinichy** [comment]
@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -36680,7 +36680,9 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             if (isReadonlySymbol(symbol)) {
                 error(expr, Diagnostics.The_operand_of_a_delete_operator_cannot_be_a_read_only_property);
             }
-            checkDeleteExpressionMustBeOptional(expr, symbol);
+            else {
+                checkDeleteExpressionMustBeOptional(expr, symbol);
```
Comment (jakebailey) [inline src/compiler/checker.ts:36684]: I'm somewhat surprised by this; if we ever add code here that calls `getTypeOfSymbol(symbol)` again, then the bug will reappear, so I'm somewhat wondering if this is a band-aid...

Comment (shinichy) [reply src/compiler/checker.ts:36684]: Hmm, what do you think of changing `checkDeleteExpressionMustBeOptional` to a function that only checks the error condition similar to `isReadonlySymbol`? Then the code is more consistent and can prevent the bug from reappearing.

```
        if (symbol) {
            if (isReadonlySymbol(symbol)) {
                error(expr, Diagnostics.The_operand_of_a_delete_operator_cannot_be_a_read_only_property);
            }
            else if (isNonOptionalSymbol(symbol)) {
                error(expr, Diagnostics.The_operand_of_a_delete_operator_must_be_optional);
            }
        }
        return booleanType;
    }

    function isNonOptionalSymbol(symbol: Symbol): boolean {
        const type = getTypeOfSymbol(symbol);
        if (
            strictNullChecks &&
            !(type.flags & (TypeFlags.AnyOrUnknown | TypeFlags.Never)) &&
            !(exactOptionalPropertyTypes ? symbol.flags & SymbolFlags.Optional : getTypeFacts(type) & TypeFacts.IsUndefined)
        ) {
            return true;
        }

        return false;
    }
```

Comment (jakebailey) [reply src/compiler/checker.ts:36684]: That's just the same code refactored to look slightly differently; the thing I'm talking about is the weird part of the bug where we don't see this double error when running `tsc` but do in tsserver. I would expect that a fix for this would include some sort of analysis as to why the two situation differ.

Comment (shinichy) [reply src/compiler/checker.ts:36684]: I see. I misunderstood. We can see this double error in `tsc`. I guess the reason why some people don't see it is missing configuration in tsc.

```
❯ cat double_error.ts
class Foo {}
delete Foo.name;

❯ npx tsc --strict --lib es2015 double_error.ts
double_error.ts:2:8 - error TS2704: The operand of a 'delete' operator cannot be a read-only property.

2 delete Foo.name;
         ~~~~~~~~

double_error.ts:2:8 - error TS2790: The operand of a 'delete' operator must be optional.

2 delete Foo.name;
         ~~~~~~~~


Found 2 errors in the same file, starting at: double_error.ts:2
```

> The operand of a 'delete' operator cannot be a read-only property.

To see this error, we need the type declaration for Function interface that has `name` property. It's defined in https://github.com/Microsoft/TypeScript/blob/main/src/lib/es2015.core.d.ts#L73.

> The operand of a 'delete' operator must be optional.

To see this error, `strictNullChecks` needs to be turned on.

Comment (jakebailey) [reply src/compiler/checker.ts:36684]: Ah, so it is reproducible in tsc; that changes things!

Comment (jakebailey) [reply src/compiler/checker.ts:36684]: In that case, this definitely couldn't be reproduced via a compiler test?

Comment (shinichy) [reply src/compiler/checker.ts:36684]: Yes, I changed the unit test to a compiler test. Would you please take a look?

Comment (jakebailey) [reply src/compiler/checker.ts:36684]: I've confirmed that the compiler test does show the issue; very surprised as I swear this didn't work for me originally. Oh well, thanks!

**Review by jakebailey — APPROVED** [review]
