### PR TITLE
Fixes duplicated comment when executing code fix to add missing enum …

### LINKED ISSUE #28031: The "Add missing enum member" fixer clones all comments above the enum
**TypeScript Version:**  3.2.0-dev.20181020

**Search Terms:** missing enum member comments clone duplicate

**Code**

```ts
// some comments
// wow
enum CoolEnum {
	Foo,
	Bar
}

CoolEnum.Baz
```

**Expected behavior:**
Using the "add missing enum member" fixer on `CoolEnum.Baz` should add the missing enum member.

**Actual behavior:**
It does that, but it also clones the comments, so the file is now:
```ts
// some comments
// wow
// some comments
// wow
enum CoolEnum {
	Foo,
	Bar,
	Baz
}

CoolEnum.Baz
```

One file in a codebase I work in ended up with 513 lines of comments before we noticed. 🤔

### PR DESCRIPTION
**Pull request by sharebear**
…member

Resolves issue #28031 by overriding default value of
`useNonAdjustedStartPosition` option to replaceNode. Test case included
that confirms intended behaviour.

Here's a checklist you might find useful.
* [x] There is an associated issue that is labeled
  'Bug' or 'help wanted' or is in the Community milestone
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `jake runtests` locally
* [x] You've signed the CLA
* [x] There are new or updated unit tests validating the change

Fixes #28031

### CODE REVIEW

File: src/services/codefixes/fixAddMissingMember.ts [hunk 1]
```diff
@@ -297,6 +297,6 @@ namespace ts.codefix {
             enumDeclaration.modifiers,
             enumDeclaration.name,
             concatenate(enumDeclaration.members, singleElementArray(enumMember))
-        ));
+        ), { useNonAdjustedStartPosition: false, useNonAdjustedEndPosition: true });
```
Comment (gabritto) [inline src/services/codefixes/fixAddMissingMember.ts]: Using `useNonAdjustedEndPosition: true` here will cause comments after the enum declaration to be duplicated.
```
const x = 2; // this is x

// this is E
enum E {
} // this was E
E.a;
```
will become
```
const x = 2; // this is x

// this is E
enum E {
    a
} // this was E
 // this was E
E.a;
```
However, using `useNonAdjustedEndPosition: false` will cause trailing whitespace and line breaks to disappear. Example:
```
const x = 2; // this is x

// this is E
enum E {
    a
}
E.a;
```
after the codefix becomes:
```const x = 2; // this is x

// this is E
enum E {
    a
}E.a;
```

**Comment by sharebear** [comment]
Hi, sorry for the slow response. I can try and find time to write a test for the issues you bring up, although one could argue that the solution as it stands does fix the original issue as reported as it only mentions duplicated comments _above_ the enum ;)

**Comment by weswigham** [comment]
@sandersn looks like this merge broke the `master` build a wee bit.

**Comment by a-tarasyuk** [comment]
@weswigham I created new PR that fixes the broken build.

cc @sandersn
