### PR TITLE
To handle d.ts emit errors that could affect other files, in incremental mode use d.ts emit text + diagnostics as signature of the file

### LINKED ISSUE #49527: More stale errors in tsbuildinfo file (with incremental:true)
# Bug Report

@zepumph and I observed incorrect behavior from `tsc` when `incremental` was set to true. A similar behavior was also discussed in https://github.com/microsoft/TypeScript/issues/42769.  It seems like the tsbuildinfo is stale.

### 🔎 Search Terms

incremental, stale, tsbuildinfo

### 🕗 Version & Regression Information

- This is the behavior in 4.6.3 and 4.7.3

### 💻 Code

```ts
// ###################### js/MessageablePerson.ts ##############
const Messageable = () => {
  return class MessageableClass {
    public message = 'hello';
  }
};

const wrapper = () => Messageable();
type MessageablePerson = InstanceType<ReturnType<typeof wrapper>>;
export default MessageablePerson;

// ###################### js/main.ts ##############
import MessageablePerson from './MessageablePerson.js';

function logMessage( person: MessageablePerson ) {
  console.log( person.message );
}

// ###################### ./tsconfig.json ##############
{
  "compilerOptions": {
    "incremental": true,
    "target": "ES2020",
    "module": "ES2020",
    "declaration": false,
    "outDir": "./outDir",
    "composite": false,
    "noEmit": true
  },
  "include": [
    "js/**/*"
  ]
}
```

### 🙁 Actual behavior

1. Set up the 3 files described above, note the relative paths
2. Run `tsc`. Observe that type checking passes, as expected
3. Change `public message = 'hello';` to `protected message = 'hello';` and run `tsc`. Observe that type checking fails, as expected.  The error message is `js/main.ts:5:23 - error TS2445: Property 'message' is protected and only accessible within class 'MessageableClass' and its subclasses.`
4. Change `protected message = 'hello';` back to `public message = 'hello';` and run `tsc`. Observe that type checking fails when it should have succeeded.  Same error message as in prior step.
5. Change `"incremental": true,` to `"incremental": false,` in the tsconfig file and run `tsc`.  Observe that type checking succeeds as expected.

### 🙂 Expected behavior

* In Step 4, we would have expected no type errors, since `message` is `public`.  However, `tsc` reports a type error.
* In Step 5, we would expect no change in behavior whether `incremental` is set to `true` or `false`.
* Note that we experimented with combining main into the MessageablePerson file and could not exhibit the bug in that way
* Note also that the bug appears in both ways: (a) reporting an error when there isn't one and (b) reporting that there is no error when there really is an error.

### PR DESCRIPTION
**Pull request by sheetalkamat**
We use to consider only d.ts emit text as file signature of file which meant if d.ts emit changed we would update other files that reference the file. But d.ts emit can have errors resulting in same .d.ts emit but impacting the other files. So now we consider d.ts file text + diagnostics as a signature of the file
Fixes #49527

### CODE REVIEW

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -1038,8 +1076,30 @@ namespace ts {
...
-    export function computeSignature(text: string, data: WriteFileCallbackData | undefined, computeHash: BuilderState.ComputeHash | undefined) {
-        return BuilderState.computeSignature(data?.sourceMapUrlPos !== undefined ? text.substring(0, data.sourceMapUrlPos) : text, computeHash);
+    function getTextHandlingSourceMapForSignature(text: string, data: WriteFileCallbackData | undefined) {
+        return data?.sourceMapUrlPos !== undefined ? text.substring(0, data.sourceMapUrlPos) : text;
+    }
+
+    export function computeSignatureWithDiagnostics(
+        program: Program,
+        text: string,
+        computeHash: BuilderState.ComputeHash | undefined,
```
Comment (DanielRosenwasser) [inline src/compiler/builder.ts:1086]:
```suggestion
        computeHash: BuilderState.ComputeHash = generateDjb2Hash,
```

File: src/compiler/builder.ts [hunk 2]
```diff
@@ -1170,19 +1230,26 @@ namespace ts {
...
-                                newSignature = computeSignature(text, data, computeHash);
-                                if (newSignature !== file.version) { // Update it
+                                const signature = computeSignatureWithDiagnostics(
+                                    state.program!,
+                                    text,
+                                    computeHash,
+                                    getCanonicalFileName,
+                                    data,
+                                );
+                                if (!data?.diagnostics?.length) newSignature = signature;
```
Comment (DanielRosenwasser) [inline src/compiler/builder.ts:1240]: Why is this conditional?

Comment (sheetalkamat) [reply src/compiler/builder.ts:1240]: I have renamed it to emitSignature and added comment but essence of it is, the signature of file with this change is d.ts emit text + declaration diagnostics while we want to store emitSigature = d.ts emit text in build info to figure out when d.ts file changes between compilations

**Comment by sheetalkamat** [comment]
Ping @andrewbranch @amcasey @weswigham

File: src/compiler/builder.ts [hunk 3]
```diff
@@ -1038,8 +1076,30 @@ namespace ts {
...
+    export function computeSignatureWithDiagnostics(
+        program: Program,
+        text: string,
+        computeHash: BuilderState.ComputeHash | undefined,
+        getCanonicalFileName: GetCanonicalFileName,
+        data: WriteFileCallbackData | undefined
+    ) {
+        text = getTextHandlingSourceMapForSignature(text, data);
+        if (data?.diagnostics?.length) {
+            text += formatDiagnostics(data.diagnostics, {
```
Comment (amcasey) [inline src/compiler/builder.ts:1092]: I don't believe anyone will ever see this string, correct?  If so, can we skip some work?  (Pretty printing, indenting, typeNodeToTypeString, etc)

File: src/compiler/builder.ts [hunk 4]
```diff
@@ -1038,8 +1076,30 @@ namespace ts {
...
+
+    export function computeSignatureWithDiagnostics(
+        program: Program,
+        text: string,
+        computeHash: BuilderState.ComputeHash | undefined,
+        getCanonicalFileName: GetCanonicalFileName,
+        data: WriteFileCallbackData | undefined
+    ) {
+        text = getTextHandlingSourceMapForSignature(text, data);
+        if (data?.diagnostics?.length) {
```
Comment (amcasey) [inline src/compiler/builder.ts:1091]: How much accuracy would we lose if we stored only the count of diagnostics or their line numbers?

File: src/compiler/builder.ts (hunk 3 above)
Comment (amcasey) [reply src/compiler/builder.ts:1092]: Can `getCanonicalFileName` be the identity function?

**Review by amcasey — APPROVED** [review]
Seems sensible, but I have some questions about potential optimizations.

File: src/compiler/builder.ts (hunk 3 above)
Comment (sheetalkamat) [reply src/compiler/builder.ts:1092]: it isnt doing much pretty printing apart from indenting multi line errors but i can get rid of that. 
These diagnostics were already being generated.. we are only using them so `TypeNodeToTypeString` cost isnt extra in this PR. I believe we should retain those for correctness.

File: src/compiler/builder.ts (hunk 4 above)
Comment (sheetalkamat) [reply src/compiler/builder.ts:1091]: I would prefer to keep the diagnostics messages since that achieves correctness and we dont have tests of scenarios in real world where this could break. Anyways we arent storing giant string but a hash of it so shouldnt increase build info size

**Comment by sheetalkamat** [comment]
@amcasey 196d93d should simplify the diagnostics serialization per your suggestion
