### PR TITLE
Preserve the distributivity of inlined conditional types in declaration emit

### LINKED ISSUE #48140: Declaration emit may change type semantics when inlining conditional types
# Bug Report

This issue was reported in a [comment on #46655](https://github.com/microsoft/TypeScript/issues/46655#issuecomment-961599736), but I'm making a separate issue for it since the other issue has a fix available that only covers the mapped type cases but not the conditional type cases.

### 🔎 Search Terms

conditional type over union
distributive conditional type

### 🕗 Version & Regression Information

v4.6.2

This is the behavior in every version I tried, and I reviewed the FAQ for entries about distributive conditional types.

### ⏯ Playground Link

Can't demonstrate in a single playground file.

### 💻 Code

```ts
/// file: test.ts
import {dropPrivateProps1, dropPrivateProps2} from './api';
const a = dropPrivateProps1({foo: 42, _bar: 'secret'}); // type is {foo: number}
//a._bar                                                // error: _bar does not exist           <===== as expected
const b = dropPrivateProps2({foo: 42, _bar: 'secret'}); // type is {foo: number, _bar: string}
//b._bar                                                // no error, type of b._bar is string   <===== NOT expected

/// file: api.ts
import {excludePrivateKeys1, excludePrivateKeys2} from './internal';
export const dropPrivateProps1 = <Obj>(obj: Obj) => excludePrivateKeys1(obj);
export const dropPrivateProps2 = <Obj>(obj: Obj) => excludePrivateKeys2(obj);

/// file: internal.ts
export declare function excludePrivateKeys1<Obj>(obj: Obj): {[K in PublicKeys1<keyof Obj>]: Obj[K]};
export declare function excludePrivateKeys2<Obj>(obj: Obj): {[K in PublicKeys2<keyof Obj>]: Obj[K]};
export type PublicKeys1<T> = T extends `_${string}` ? never : T;
type PublicKeys2<T>        = T extends `_${string}` ? never : T;
```

### 🙁 Actual behavior

To repro this, you need to generate `api.d.ts` and `internal.d.ts` declaration files, and consume those from `test.ts`. The three-file setup is the only way I could get tsc to inline the non-exported type `PublicKeys2` in the .d.ts file. If you import `api.ts` directly from source, everything works as expected. Things only break when consuming from the `api.d.ts` file. So this issue is saying that **the semantics of the emitted `.d.ts` files is not the same as the sources they were emitted from**.

As shown in `test.ts` above, declaration emit type semantics change depending on whether an internal type is marked with `export` or not. In the above example, the declarations emitted for `api.d.ts` are:

```ts
export declare const dropPrivateProps1: <Obj>(obj: Obj) => { [K in import("./internal").PublicKeys1<keyof Obj>]: Obj[K]; };
export declare const dropPrivateProps2: <Obj>(obj: Obj) => { [K in keyof Obj extends `_${string}` ? never : keyof Obj]: Obj[K]; };
```

Specifically, the conditional type in `PublicKeys2` loses its distributivity the way it is inlined above, so the type's meaning changes.

### 🙂 Expected behavior

Declaration emit semantics should be the same as the source code, regardless of whether or not `tsc` preserves an internal type in the emit, or expands it directly into a type expression.

### See also
#46655 (similar issue but for mapped types)

### PR DESCRIPTION
**Pull request by weswigham**
By wrapping them in _two_ more layers of conditionals - one to establish a local type parameter for distributivity, one to constrain said type parameter so it remains usable as the instantiated check type.

This means something like `type PrivateFields<Keys> = Keys extends _${string} ? Keys : undefined;` when used as `PrivateFields<keyof Obj>` will be inlined to `keyof Obj extends infer T ? T extends keyof Obj ? T extends _${string}  ? T : never`, to retain the distributive behavior, rather than the erroneous `keyof Obj extends _${string} ? keyof Obj : never`.

Fixes #48140

### CODE REVIEW

File: tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+};
+export declare function excludePrivateKeys2<Obj>(obj: Obj): {
+    [K in PublicKeys2<keyof Obj>]: Obj[K];
+};
+export declare type PublicKeys1<T> = T extends `_${string}` ? never : T;
+declare type PublicKeys2<T> = T extends `_${string}` ? never : T;
+export {};
+//// [api.d.ts]
+export declare const dropPrivateProps1: <Obj>(obj: Obj) => { [K in import("./internal").PublicKeys1<keyof Obj>]: Obj[K]; };
+export declare const dropPrivateProps2: <Obj>(obj: Obj) => { [K in keyof Obj extends infer T ? T extends keyof Obj ? T extends `_${string}` ? never : T : never : never]: Obj[K]; };
```
Comment (andrewbranch) [inline tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js:55]: 1. Is it not a problem that the middle conditional type (the inner of the two synthesized ones) is distributive itself? It seems like it comes out the same, but in a way the semantics are slightly different here, right?—the ``T extends `_${string}` `` bit will never actually have anything to distribute over because the distribution is done one level up.
2. Whether or not (1) actually matters, you could use Ron’s new infer constraints here instead, which would reduce a level of nesting. That seems preferable to me, unless we’re specifically trying to avoid emitting that for back compat reasons, but... I think that’s a job for downlevel-dts.

Comment (weswigham) [reply tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js:55]: 1. Extra layers of distributivity don't matter, so long as the right type variable is distributed over before the conditional logic occurs.
2. Yeah, I mention that in a comment in the code - we could, but we'd start producing declaration files incompatible with older versions of TS and I don't know if we wanna do that just yet. It's always something we could change down the line.

Comment (andrewbranch) [reply tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js:55]: The other thing I was curious about is whether we could ever just copy the unreachable type alias declaration to a local one. If we’re already copying its contents, why not just drop the whole declaration nearby with a unique name?

Comment (weswigham) [reply tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js:55]: Wherever we can, we do (specifically if we can preserve it as-is, in it's existing location). We only do inlining like this when the type comes from somewhere unreachable or elided (like inside a different module's locals or an elided function body). We don't copy from those scopes into the current scope because then we'd have to do 1. pull in its whole dependency tree of types (which may, in turn, depend on things we just can't copy, like signature type parameters), and 2. ensure everything is renamed in such a way where there's no name conflicts. It's just not something we do much of right now.

Comment (andrewbranch) [reply tests/baselines/reference/declarationEmitInlinedDistributiveConditional.js:55]: > pull in its whole dependency tree of types

This is what I thought at first, but don’t we end up having to do that if we inline it too? Like the only part of the type that we _don’t_ copy is the declaration.

**Review by andrewbranch — APPROVED** [review]
