### PR TITLE
Fix serialisation of static class members in JS

### LINKED ISSUE #37289: Adding a JSDoc @typedef declaration breaks emitting static getter to ".d.ts" files.
**TypeScript Version:**   3.9.0-dev.20200309

**Search Terms:** `static get`, `static get cannot find name`

**Code**

```js
'use strict';

class Handler {
	static get OPTIONS() {
		return 1;
	}

	process() {
	}
}

module.exports = Handler;

/**
 * @typedef {Object} HandlerOptions
 * @property {String} name
 */

```

**Expected behavior:**
```
export = Handler;
declare class Handler {
    static get OPTIONS(): number;
    process(): void;
}
declare namespace Handler {
    export { OPTIONS, HandlerOptions };
}
type HandlerOptions = {
    name: string;
};
```

**Actual behavior:**
```
// Missing `static get OPTIONS` declaration
// And an error is emitted: `TS2304: Cannot find name 'OPTIONS'.`
export = Handler;
declare class Handler {
    process(): void;
}
declare namespace Handler {
    export { OPTIONS, HandlerOptions };
}
type HandlerOptions = {
    name: string;
};
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=18&ssc=1&pln=13&pc=1&useJavaScript=true#)

### PR DESCRIPTION
**Pull request by sandersn**
Previously static class members would be treated the same way as expando
namespace assignments to a class:

```ts
class C {
  static get x() { return 1 }
}
C.y = 12
```

This PR adds a syntactic check to the static/namespace filter that
treats symbols whose valueDeclaration.parent is a class as statics.

Fixes #37289

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6477,10 +6480,11 @@ namespace ts {
                             // need to be merged namespace members
                             return [];
                         }
-                        if (p.flags & SymbolFlags.Prototype || (baseType && getPropertyOfType(baseType, p.escapedName)
-                            && isReadonlySymbol(getPropertyOfType(baseType, p.escapedName)!) === isReadonlySymbol(p)
-                            && (p.flags & SymbolFlags.Optional) === (getPropertyOfType(baseType, p.escapedName)!.flags & SymbolFlags.Optional)
-                            && isTypeIdenticalTo(getTypeOfSymbol(p), getTypeOfPropertyOfType(baseType, p.escapedName)!))) {
+                        if (p.flags & SymbolFlags.Prototype ||
+                            (baseType && getPropertyOfType(baseType, p.escapedName)
```
Comment (sandersn) [inline src/compiler/checker.ts:6484]: this is just a formatting change to make obvious that it's `x || (y && z && ka && ki ...)`

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6193,11 +6198,9 @@ namespace ts {
                         emptyArray;
                     const publicProperties = flatMap<Symbol, ClassElement>(publicSymbolProps, p => serializePropertySymbolForClass(p, /*isStatic*/ false, baseTypes[0]));
                     // Consider static members empty if symbol also has function or module meaning - function namespacey emit will handle statics
-                    const staticMembers = symbol.flags & (SymbolFlags.Function | SymbolFlags.ValueModule)
-                        ? []
-                        : flatMap(filter(
+                    const staticMembers = flatMap(filter(
                             getPropertiesOfType(staticType),
-                            p => !(p.flags & SymbolFlags.Prototype) && p.escapedName !== "prototype"
+                            p => !(p.flags & SymbolFlags.Prototype) && p.escapedName !== "prototype" && p.valueDeclaration && isClassLike(p.valueDeclaration.parent)
```
Comment (weswigham) [inline src/compiler/checker.ts:6203]: Should we extract this predicate to a function, so it's obvious each place is using the same predicate (albeit inverted)?

Comment (sandersn) [reply src/compiler/checker.ts:6203]: yes, although it reveals that this usage is not quite the same as the others, because it needs to (1) accept `static` members (the opposite of the others) but (2) exclude `prototype` (same as the others)

**Comment by robpalme** [comment]
I think this PR may have regressed the ESnext emit for static fields.

https://www.reddit.com/r/typescript/comments/gilb3e/announcing_typescript_39/fqfrqzz
