### PR TITLE
Fixed a crash caused by circularly-reentrant `getEffectsSignature`

### LINKED ISSUE #63015: Regression Crash: RangeError: Maximum call stack size exceeded in isThisInTypeQuery on Nightly
### 🔎 Search Terms

RangeError: Maximum call stack size exceeded

isThisInTypeQuery

Regression

typeof crash

### 🕗 Version & Regression Information

Works in: v5.7.3, v5.8.3, v5.9.3 (Reports standard errors: TS2448, TS2345, etc.)

Crashes in: Nightly

### ⏯ Playground Link

https://www.typescriptlang.org/zh/play/?target=7&ts=6.0.0-dev.20260119#code/K4Owlg9iDyBmAiZawKYCcUgC4CUVeDRABUBPABxQEYAKLNYFASgG4ACAeg7fTQjTZgQbLBRRsIsNuQCGaGQFt86AFABjKAGcsbUJBgIkqDNjwEiZSlQBcbAN4q2TtjRm2ZIUk1shgCgEboLCoAvmwAPvaOzq4+foFo3iJikmzwMlgowSEsQA

### 💻 Code

```ts
unionOfDifferentReturnType1(true); // error in type of parameter
const unionOfDifferentReturnType1: {
    (a: any): number;
} | {
    (a: number): typeof Date;
};
```

### 🙁 Actual behavior

```
.\ts-versions\nightly\node_modules\.bin\tsc.cmd   .\unionTypeCallSignatures_6.ts
D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:123178
      throw e;
      ^

RangeError: Maximum call stack size exceeded
    at isThisIdentifier (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:16646:26)                                                                                                
    at isThisInTypeQuery (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:16656:8)                                                                                                
    at checkIdentifier (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:71968:9)                                                                                                  
    at checkExpressionWorker (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:80857:16)                                                                                           
    at checkExpression (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:80800:32)                                                                                                 
    at checkExpressionWithTypeArguments (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:77806:182)                                                                               
    at getTypeFromTypeQueryNode (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:60457:20)                                                                                        
    at getTypeFromTypeNodeWorker (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:63099:16)                                                                                       
    at getTypeFromTypeNode (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:63055:41)                                                                                             
    at getReturnTypeFromAnnotation (D:\do\typeFuzz\ts-versions\nightly\node_modules\typescript\lib\_tsc.js:59715:14)                                                                                     

Node.js v22.19.0
```

### 🙂 Expected behavior

The compiler should not crash.

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/63015
caused by https://github.com/microsoft/TypeScript/pull/62243/files#r2264931395

With the change above, some of the function-like type-level nodes *lost* `ContainerFlags.IsControlFlowContainer`. It turns out that, despite them being type-level nodes, it was still important for them to be treated as flow containers. Or rather, it was important for them to get their own detached~ flow node as `currentFlow` in the `bindContainer`'s branch handling `ContainerFlags.IsControlFlowContainer`. 

Without that flag on them the nodes received `.flowNode` that was attached to the flow graph of the containing control flow container. Where with the flag they received `FlowFlags.Start` node that usually no other flow nodes would be attached to, unless one would write an incorrect program with narrowing *expressions* within type level nodes (those would attach to that `FlowFlags.Start` as that was set as `currentFlow`) in situations akin to this one:
```ts
type SomeTypeAlias = { [Math.random() ? foo : bar]: string } // error
```

So all of that caused `typeof x` within those function-like type-level nodes to get narrowed by the containing container's flow and the code managed to infinitely recurse in the reported code:
```ts
unionOfDifferentReturnType1(true);
const unionOfDifferentReturnType1: { (a: any): number; } | { (a: number): typeof Date; };
```

In here, the `Date` in the typeof query was being narrowed by `FlowFlags.Call` node but that depends on the annotated type of `unionOfDifferentReturnType1` (it depends on `getEffectsSignature` and that depends on explicitly annotated return types).

It seemed to me it would be possible to create a similar crash in 5.9 and I tried weird things (I added them as tests) but couldn't make it happen. The closest thing I got was this somewhat surprising error:
```ts
function test4(arg: string | number, whatever: any) {
  if (typeof arg === "string") {
    b()
    type First = typeof arg // Type alias 'First' circularly references itself.(2456)
    type Test = () => First
    const b: Test = whatever
    return b
  }
  return undefined;
}
```

I think this means that type aliases have reentrancy protection already implemented and the reported code crashes because it manages to slip through codepaths that don't have it (anonymous type nodes don't implement `pushTypeResolution`+`popTypeResolution` etc). 

All of that led me to exploring the inconsistencies around `typeof` queries, like here:
```ts
function test1(a: number | string) {
  if (typeof a === "number") {
    const fn = (arg: typeof a) => true;
    return fn;
  }
  return;
}

test1(0)?.(100); // ok
test1(0)?.(""); // error

function test2(a: number | string) {
  if (typeof a === "number") {
    const fn: { (arg: typeof a): boolean; } = () => true;
    return fn;
  }
  return;
}

test2(0)?.(100); // ok
test2(0)?.(""); // ok ?
```

So I figured out, I would prefer to keep their behavior change accidentally implemented in https://github.com/microsoft/TypeScript/pull/62243 . It would be nice if they would behave in the same way in the example above. It seemed the easiest to just eagerly set a "zero value" `links.effectsSignature` before resolving the true value. That's a pretty common pattern used across the codebase.

FWIW, I have also briefly explored disabling control flow narrowing within type-only nodes but that broke a couple of existing explicit tests.

Alternative fixes I have considered:
- reverting the `ContainerFlags.IsControlFlowContainer` changes + fine-tuning `seenThisKeyword` tracking
- adding an extra codepath to `bindContainer`, smth like:
```ts
if (ContainerFlags.IsFunctionLike) {
  const saveCurrentFlow = currentFlow;
  currentFlow = createFlowNode(FlowFlags.Start, /*node*/ undefined, /*antecedent*/ undefined);
  bindChildren(node);
  currentFlow = saveCurrentFlow;
}
```
- using `links.effectsSignature = resolvingEffectsSignature` strategy

EDIT:// at the end, I have refactored the PR to choose the first option of"reverting the `ContainerFlags.IsControlFlowContainer` changes + fine-tuning `seenThisKeyword` tracking", as requested [here](https://github.com/microsoft/TypeScript/pull/63026#issuecomment-3790911144)

cc @gabritto

### CODE REVIEW

**Comment by ahejlsberg** [comment]
I'm somewhat queasy about having to put in stopgap recursion limiter where we previously didn't need it. We use a similar pattern in some places, but it always comes with the downside of possibly observing different results from functions that are supposed to just lazily compute immutable values. My preference would be to restore the original `ContainerFlags.IsControlFlowContainer` values and get closer to where we were before.

**Comment by Andarist** [comment]
Thanks for the feedback. I’ll work on the suggested solution

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -28723,6 +28723,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         const links = getNodeLinks(node);
         let signature = links.effectsSignature;
         if (signature === undefined) {
+            links.effectsSignature = unknownSignature;
```
Comment (gabritto) [inline src/compiler/checker.ts]: We don't need this anymore, right? At least for the scenario that caused the issue.

**Review by gabritto — CHANGES_REQUESTED** [review]
Looks good except for the (leftover?) change in `checker.ts`.

File: src/compiler/checker.ts (hunk 1 above)
Comment (Andarist) [reply src/compiler/checker.ts]: Yeah, you are right - the intention was totally to remove it. I just pushed out a commit getting rid of this

**Comment by gabritto** [comment]
@typescript-bot test it

**Review by gabritto — APPROVED** [review]
