### PR TITLE
Produce an error for an augmentation of an untyped module even if `moduleNotFoundError` is not defined

### LINKED ISSUE #12827: Debug.assert for missing module name augmentation
See details https://github.com/Microsoft/TypeScript/issues/10522#issuecomment-266223640

Here is cloneable gist: https://gist.github.com/Ciantic/60e9dbe330922cfc41086e255820df62

```
$ tsc --version
Version 2.2.0-dev.20161210
$ npm install
$ tsc
...\typescript\lib\tsc.js:1796
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^

Error: Debug Failure. False expression:
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #12827

The fix in #11962 asserted that `moduleNotFoundError` would be defined for any module augmentations.
However, if the augmentation is in a declaration file, this is undefined, because we don't validate names of augmentations that are defined in ambient context. See #8200. The reason @vladima mentioned was (https://github.com/Microsoft/TypeScript/issues/8113#issuecomment-211058891):

> it is quite possible that some 3rd party module A that was imported in application also defines an augmentation for some another module B but application itself does not use B and as a consequence does not have dependency on it so resolution for B always will fail and user will always see some errors that he cannot get rid of.

However, if we have an untyped import, that means that we *are* using the library, but don't have typings for it. The problem is that you can't augment typings that don't exist.
We could elide the error, but the augmentation would then have no effect -- you would still get `any` when trying to use functions defined by the augmentation.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1439,9 +1439,8 @@ namespace ts {
              // May be an untyped module. If so, ignore resolutionDiagnostic.
             if (!isRelative && resolvedModule && !extensionIsTypeScript(resolvedModule.extension)) {
                 if (isForAugmentation) {
-                    Debug.assert(!!moduleNotFoundError);
                     const diag = Diagnostics.Invalid_module_name_in_augmentation_Module_0_resolves_to_an_untyped_module_at_1_which_cannot_be_augmented;
-                    error(errorNode, diag, moduleName, resolvedModule.resolvedFileName);
+                    error(errorNode, diag, moduleReference, resolvedModule.resolvedFileName);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: This has no effect on tests but seemed more correct as `moduleName` is escaped, and the below error also uses `moduleReference`.

**Comment by mhegazy** [comment]
@andy-ms, please port this change to release-2.1 as well.
