### PR TITLE
fix(59558): Implement Interface Quick Fix generates duplicate declarations

### LINKED ISSUE #59558: Implement Interface Quick Fix generates duplicate declarations
### 🔎 Search Terms

quick fix implement duplicate

### 🕗 Version & Regression Information

TypeScript Version: 5.6.0-beta

### ⏯ Playground Link

https://github.com/Soarex16/ts-bug-disposable-impl

### 💻 Code

First, you should install `@types/node` and add `ESNext` in `compilerOptions/lib` in `tsconfig.json`. Then try to invoke 'Implement Interface' on the following class:
```ts
class Foo implements Disposable {

}
```

### 🙁 Actual behavior
```ts
class Foo implements Disposable {
    [Symbol.dispose](): void;
    [Symbol.dispose](): void;
    [Symbol.dispose](): void {
        throw new Error("Method not implemented.");
    }

}
```

### 🙂 Expected behavior
```ts
class Foo implements Disposable {
    [Symbol.dispose](): void {
        throw new Error("Method not implemented.");
    }

}
```

### Additional information about the issue

This happens because `Disposable` interface comes from both `@types/node` and `ESNext` lib.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #59558

### CODE REVIEW

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -300,6 +300,9 @@ export function addNewNodeForMemberSymbol(
             }
 
             for (const signature of signatures) {
+                if (signature.declaration && (signature.declaration.flags & NodeFlags.Ambient)) {
```
Comment (DanielRosenwasser) [inline src/services/codefixes/helpers.ts:303]: Is this correct? Does this work for the following two cases?

```ts
declare class Base {
  method(): void;
}

class Derived implements Base {
}
```


```ts
declare abstract class Base {
  abstract method(): void;
}

class Derived extends Base {
}
```

**Review by iisaduan — APPROVED** [review]
