### PR TITLE
fix(41027): recursive private static gets missed in --noUnusedLocals

### LINKED ISSUE #41027: recursive private static gets missed in --noUnusedLocals
**TypeScript Version:**  3.8.3

**Search Terms:**
noUnusedLocals, recursive

**Code**

```ts
class C {
    private static staticFactorial(n: number): number {  // no error
        return (n === 0) ? 1 : (n * C.staticFactorial(n - 1));
    }

    private static foo() {  // unused error
        return 42;
    }
}

function main() {
    function localFactorial(n: number): number {  // unused error
        return (n === 0) ? 1 : (n * localFactorial(n - 1));
    }
}
```

**Expected behavior:**
both `localFactorial` and `staticFactorial` have the same result when compiled with `--noUnusedLocals`

**Actual behavior:**
`localFactorial` triggers error
`staticFactorial` does not

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41027

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -27150,6 +27149,11 @@ namespace ts {
             (getCheckFlags(prop) & CheckFlags.Instantiated ? getSymbolLinks(prop).target : prop)!.isReferenced = SymbolFlags.All;
         }
 
+        function isSelfTypeAccess(name: Expression | QualifiedName, parent: Symbol | undefined) {
+            return name.kind === SyntaxKind.ThisKeyword
+                || !!parent && parent === getNodeLinks(name).resolvedSymbol;
```
Comment (sandersn) [inline src/compiler/checker.ts:27154]: I know it's used all over the place, but `getNodeLinks(name).resolvedSymbol` feels less safe than calling `getResolvedSymbol`, just in case `NodeLinks.resolvedSymbol` hasn't been set yet. Can you use that instead?

**Review by sandersn — CHANGES_REQUESTED** [review]
One small change to `getResolvedSymbol`.

**Review by sandersn — APPROVED** [review]
