### PR TITLE
Miscellaneous fixes to avoid duplicate completions

### LINKED ISSUE #20042: Duplicate completion items
**TypeScript Version:**  typescript@2.7.0-dev.20171115

**Code**

Fourslash tests:
* `completionForStringLiteralNonrelativeImport8.ts`
* `completionInJSDocFunctionNew.ts`
* `completionInJSDocFunctionThis.ts`
* `completionListPrimitives.ts`
* `getJavaScriptCompletions2.ts`

**Expected behavior:**

No duplicate completion items.

**Actual behavior:**

Yes duplicate completion items.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20042

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -24433,6 +24428,10 @@ namespace ts {
             return getNamedMembers(propsByName);
         }
 
+        function typeHasCallOrConstructSignatures(type: Type): boolean {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: why do you need this in the checker API? the type object already has `getCallSignatures` and `getConstructSignatures` and `TypeChecker` already has `getSignaturesOfType`

Comment (andy-ms) [reply src/compiler/checker.ts]: I wanted to reuse the code inside of `checker.ts`, but it would be wierd to have to pass itself into the helper function.
