### PR TITLE
Handle the require call in javascript file for getSymbolAtLocation

### LINKED ISSUE #9251: Go-to-definition doesn't work on path in calls to 'require'
./foo.js:

```js
module.exports = {};
```

./bar.js:

```js
var x = require(/*$*/"./foo");
```

1. Go to definition on `/*$*/`

Expected: Navigate to `foo.js`.
Actual: Nada.

### PR DESCRIPTION
**Pull request by sheetalkamat**
This helps in getting the alias symbol so that it can go to the definition of external module
Fixes #9251

### CODE REVIEW

File: tests/cases/fourslash/goToDefinitionJsModuleName.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/// <reference path='fourslash.ts'/>
+
+// @allowJs: true
+// @Filename: foo.js
+/////*2*/module.exports = {};
+
+// @Filename: bar.js
+////var x = require(/*1*/"./foo");
+
+debugger;
```
Comment (vladima) [inline tests/cases/fourslash/goToDefinitionJsModuleName.ts]: remove it

Comment (sheetalkamat) [inline tests/cases/fourslash/goToDefinitionJsModuleName.ts]: thanks

**Comment by mhegazy** [comment]
@sheetalkamat can you port this to release-2.0.5 as well.
