### PR TITLE
fix(40609): Crash on extract to type alias

### LINKED ISSUE #40609: Crash on extract to type alias
```ts
type WatchedEventListener<T> = {
    addEventListener:
        keyof T extends string ?
            [|(eventName: `${keyof T}Changed`, callback: (propName: keyof T) => void) => void|] :
            never;
};
```

Extract type alias at the above `[|range|]`.

```
<semantic> TypeScript Server Error (4.1.0-insiders.20200829)
Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (\node_modules\TypeScript\lib\tsserver.js:130013:38)
    at \node_modules\TypeScript\lib\tsserver.js:129945:21
    at visitNode (\node_modules\TypeScript\lib\tsserver.js:27435:24)
    at Object.forEachChild (\node_modules\TypeScript\lib\tsserver.js:27498:21)
    at processNode (\node_modules\TypeScript\lib\tsserver.js:129944:20)
    at processChildNode (\node_modules\TypeScript\lib\tsserver.js:130020:21)
    at processChildNodes (\node_modules\TypeScript\lib\tsserver.js:130083:48)
    at \node_modules\TypeScript\lib\tsserver.js:129947:21
    at visitNodes (\node_modules\TypeScript\lib\tsserver.js:27440:24)
    at Object.forEachChild (\node_modules\TypeScript\lib\tsserver.js:27545:21)
    at processNode (\node_modules\TypeScript\lib\tsserver.js:129944:20)
    at processChildNode (\node_modules\TypeScript\lib\tsserver.js:130020:21)
    at \node_modules\TypeScript\lib\tsserver.js:129945:21
    at visitNode (\node_modules\TypeScript\lib\tsserver.js:27435:24)
    at Object.forEachChild (\node_modules\TypeScript\lib\tsserver.js:27769:21)
    at processNode (\node_modules\TypeScript\lib\tsserver.js:129944:20)
    at formatSpanWorker (\node_modules\TypeScript\lib\tsserver.js:129757:17)
    at \node_modules\TypeScript\lib\tsserver.js:129721:140
    at Object.getFormattingScanner (\node_modules\TypeScript\lib\tsserver.js:128344:23)
    at Object.formatNodeGivenIndentation (\node_modules\TypeScript\lib\tsserver.js:129721:31)
    at getFormattedTextOfNode (\node_modules\TypeScript\lib\tsserver.js:131949:45)
    at format (\node_modules\TypeScript\lib\tsserver.js:131919:52)
    at computeNewText (\node_modules\TypeScript\lib\tsserver.js:131922:23)
    at \node_modules\TypeScript\lib\tsserver.js:131887:39
    at Object.mapDefined (\node_modules\TypeScript\lib\tsserver.js:610:30)
    at \node_modules\TypeScript\lib\tsserver.js:131885:42
    at Object.mapDefined (\node_modules\TypeScript\lib\tsserver.js:610:30)
    at Object.getTextChangesFromChanges (\node_modules\TypeScript\lib\tsserver.js:131871:27)
    at ChangeTracker.getChanges (\node_modules\TypeScript\lib\tsserver.js:131839:45)
    at Function.ChangeTracker.with (\node_modules\TypeScript\lib\tsserver.js:131287:32)
    at Object.getEditsForAction (\node_modules\TypeScript\lib\tsserver.js:142337:62)
    at Object.getEditsForRefactor (\node_modules\TypeScript\lib\tsserver.js:132523:41)
    at Proxy.getEditsForRefactor (\node_modules\TypeScript\lib\tsserver.js:146187:32)
    at IOSession.Session.getEditsForRefactor (\node_modules\TypeScript\lib\tsserver.js:156565:59)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (\node_modules\TypeScript\lib\tsserver.js:155308:61)
    at \node_modules\TypeScript\lib\tsserver.js:156910:88
    at IOSession.Session.executeWithRequestId (\node_modules\TypeScript\lib\tsserver.js:156901:28)
    at IOSession.Session.executeCommand (\node_modules\TypeScript\lib\tsserver.js:156910:33)
    at IOSession.Session.onMessage (\node_modules\TypeScript\lib\tsserver.js:156934:35)
    at Interface.<anonymous> (\node_modules\TypeScript\lib\tsserver.js:159150:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40609

### CODE REVIEW

File: src/services/refactors/extractType.ts [hunk 1]
```diff
@@ -130,17 +130,17 @@ namespace ts.refactor {
...
 
         function visitor(node: Node): true | undefined {
             if (isTypeReferenceNode(node)) {
                 if (isIdentifier(node.typeName)) {
                     const symbol = checker.resolveName(node.typeName.text, node.typeName, SymbolFlags.TypeParameter, /* excludeGlobals */ true);
                     if (symbol) {
                         const declaration = cast(first(symbol.declarations), isTypeParameterDeclaration);
-                        if (rangeContainsSkipTrivia(statement, declaration, file) && !rangeContainsSkipTrivia(selection, declaration, file)) {
-                            result.push(declaration);
+                        if (rangeContainsSkipTrivia(statement, declaration, file) && !rangeContainsSkipTrivia(selection, declaration, file) && !result.has(declaration)) {
```
Comment (jessetrinity) [inline src/services/refactors/extractType.ts:142]: If you're just de-duping declarations you could use `result.indexOf(declaration) > 0` if you want to avoid declaring a Set which will ultimately be converted back to an array anyway.

**Comment by jessetrinity** [comment]
Why were duplicate type parameters causing the crash?

**Comment by a-tarasyuk** [comment]
The `visitor` checks all parameters and adds each parameter type to the `result`. for the following example

```ts
type Foo<T> = {
    fn: (a: T, b: T, c: T) => void;
}
```

`ExtractType` tries to create a type `type NewType<T, T, T>` which causes the error. @jessetrinity does that make sense?

**Comment by jessetrinity** [comment]
Yes, that makes sense. Thanks for the explanation and the PR!

**Review by jessetrinity — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
I'm still not clear on why it *crashes* but this seems to fix another future bug.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser The PR contains code (tests/cases/fourslash/refactorExtractType69.ts) from the issue to verify the fix. Do you have another example that needs to cover?

**Comment by andrewbranch** [comment]
At some point it would be good to add a variety of tests that pump template and pattern literal types through codefixes/refactors. When @jessetrinity and I were debugging this, we definitely saw the formatting scanner get tripped up on that node. I still think there might be a missing condition to `reScan` something. I’m surprised this fixes that crash based on the behavior we saw, but the formatter works in mysterious ways 🤷

**Comment by a-tarasyuk** [comment]
@andrewbranch I'm ok to revert these changes, in favor of adding changes to formatter.

**Comment by jessetrinity** [comment]
Strictly speaking it doesn't fix the template bug, #40738 did.

Previous to that, extract type on
```ts
type a = `${a}` 
```
would cause a crash.

You should actually be able to remove the string templates from the tests in this PR and still get the crash previous to this change.

**Comment by andrewbranch** [comment]
> I'm ok to revert these changes, in favor of adding changes to formatter.

Oh no, these changes are clearly correct, I was just surprised they fixed the bug.

> Strictly speaking it doesn't fix the template type bug, #40738 did.

Ah, that makes more sense 👍

**Comment by a-tarasyuk** [comment]
> `#40738 did`

@jessetrinity Yep, I was waiting for the merging of this PR., because my first PR contained changes related to missing `nodes` and duplicated type references.

**Comment by a-tarasyuk** [comment]
@andrewbranch @jessetrinity Does that make sense to drop the test `tests/cases/fourslash/refactorExtractType69.ts`?

**Comment by jessetrinity** [comment]
I thought it was good to have a test on the code that surfaced the bug, but maybe it's a little confusing since there were two bugs..?

If anything, we might want a more minimal test for the template string issue covering with span:
```ts
type a = \*a*\`${extractMe}`\*b*\
```
