### PR TITLE
Fixes some formatting for decorators

### LINKED ISSUE #2660: Incorrect indentation for multiple decorators
Formatting the following document in Visual Studio results in incorrect indentation:

```TypeScript
class C {
    @dec
    @dec
    @dec
    method() { }
}
```

Actual:
```TypeScript
class C {
    @dec
        @dec
        @dec
    method() { }
}
```

Expected:
```TypeScript
class C {
    @dec
    @dec
    @dec
    method() { }
}
```

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #2660 and #2661
* Added rules for spacing around decorators
* Computing the undecorated start line of a node for use as the effectiveParentStartLine

There's still an issue with indentation in formatOnEnter.

### CODE REVIEW

File: src/services/formatting/rules.ts [hunk 1]
```diff
@@ -649,6 +662,28 @@ module ts.formatting {
...
+                Rules.NodeIsInDecoratorContext(context.currentTokenParent) &&
+                !Rules.NodeIsInDecoratorContext(context.nextTokenParent);
+        }
+
+        static NodeIsInDecoratorContext(node: Node): boolean {
+            if (node.parserContextFlags & ParserContextFlags.Decorator) {
+                return true;
+            }
+            while (node) {
+                if (isExpression(node)) {
```
Comment (mhegazy) [inline src/services/formatting/rules.ts]: i made a change to make isExpression return true for decorators.

Comment (mhegazy) [inline src/services/formatting/rules.ts]: can you just walk up until you find a decorator, or just use hasAncestor/getAncestor

File: src/services/formatting/rules.ts [hunk 2]
```diff
@@ -649,6 +662,28 @@ module ts.formatting {
...
 
+        static IsEndOfDecoratorContextOnSameLine(context: FormattingContext): boolean {
+            return context.TokensAreOnSameLine() &&
+                context.contextNode.decorators &&
+                Rules.NodeIsInDecoratorContext(context.currentTokenParent) &&
+                !Rules.NodeIsInDecoratorContext(context.nextTokenParent);
+        }
+
+        static NodeIsInDecoratorContext(node: Node): boolean {
+            if (node.parserContextFlags & ParserContextFlags.Decorator) {
```
Comment (mhegazy) [inline src/services/formatting/rules.ts]: why do we need this check? would not the walk be sufficient?

File: src/services/formatting/rules.ts [hunk 3]
```diff
@@ -344,6 +349,11 @@ module ts.formatting {
...
 
+            // decorators
+            this.SpaceBeforeAt = new Rule(RuleDescriptor.create2(Shared.TokenRange.Any, SyntaxKind.AtToken), RuleOperation.create2(new RuleOperationContext(Rules.IsSameLineTokenContext), RuleAction.Space));
+            this.NoSpaceAfterAt = new Rule(RuleDescriptor.create3(SyntaxKind.AtToken, Shared.TokenRange.Any), RuleOperation.create2(new RuleOperationContext(Rules.IsSameLineTokenContext), RuleAction.Delete));
+            this.SpaceAfterDecorator = new Rule(RuleDescriptor.create4(Shared.TokenRange.Any, Shared.TokenRange.FromTokens([SyntaxKind.Identifier, SyntaxKind.ExportKeyword, SyntaxKind.DefaultKeyword, SyntaxKind.ClassKeyword, SyntaxKind.StaticKeyword, SyntaxKind.PublicKeyword, SyntaxKind.PrivateKeyword, SyntaxKind.ProtectedKeyword, SyntaxKind.GetKeyword, SyntaxKind.SetKeyword, SyntaxKind.OpenBracketToken, SyntaxKind.AsteriskToken])), RuleOperation.create2(new RuleOperationContext(Rules.IsEndOfDecoratorContextOnSameLine), RuleAction.Space));
```
Comment (mhegazy) [inline src/services/formatting/rules.ts]: Can you add a test for space after decorator should not be added
```ts
@x[""]
class c {
}
```
or
```ts
@decorator(arg) 
class  {}
```

Comment (mhegazy) [inline src/services/formatting/rules.ts]: i would add "function" as well

File: src/services/services.ts [hunk 4]
```diff
@@ -149,8 +149,8 @@ module ts {
             return getSourceFileOfNode(this);
         }
 
-        public getStart(sourceFile?: SourceFile): number {
-            return getTokenPosOfNode(this, sourceFile);
+        public getStart(sourceFile?: SourceFile, skipDecorators?: boolean): number {
```
Comment (mhegazy) [inline src/services/services.ts]: does this need to be in getStart? i would think of this as a helper that the formatter would call. not everyone would want to do that.

File: src/services/formatting/rules.ts (hunk 1 above)
Comment (mhegazy) [inline src/services/formatting/rules.ts]: here is the change i referenced earlier: #2659

Comment (rbuckton) [inline src/services/formatting/rules.ts]: Based on our offline discussion, I changed the logic in `isExpression` in #2659. This should no longer be an issue.

File: src/services/formatting/rules.ts (hunk 2 above)
Comment (rbuckton) [inline src/services/formatting/rules.ts]: I thought it might be useful to be able to shortcut and save a few operations, but I can remove this.

File: src/services/formatting/rules.ts (hunk 1 above)
Comment (rbuckton) [inline src/services/formatting/rules.ts]: If we ever add support for decorators on class expressions, function expressions, or arrow functions then hasAncestor/getAncestor is unsafe to use. Consider the following:

```TypeScript
@class { /*A*/ } class C { }
```
At *A* above, a call to `getAncestor(SyntaxKind.Decorator)` would return the decorator for `C`, but it should have stopped at the class body. `hasAncestor` and `getAncestor` don't have a boundary. We could add a boundary check, but this is easy enough.

I may change this to the following, though:
```TypeScript
        static NodeIsInDecoratorContext(node: Node): boolean {
            while (isExpression(node)) {
                node = node.parent;
            }
            return node.kind === SyntaxKind.Decorator;
        }
```

File: src/services/services.ts (hunk 4 above)
Comment (rbuckton) [inline src/services/services.ts]: I'll make a separate helper for this.

File: src/services/formatting/rules.ts (hunk 3 above)
Comment (rbuckton) [inline src/services/formatting/rules.ts]: @mhegazy, can you clarify what you mean by this:
> i would add "function" as well

Comment (rbuckton) [inline src/services/formatting/rules.ts]: @mhegazy, I'm not sure what you're trying illustrate with this:
> Can you add a test for space after decorator should not be added
> ```ts
> @x[""]
> class c {
> }
> ```
> or
> ```ts
> @decorator(arg) 
> class  {}
> ```

Comment (mhegazy) [inline src/services/formatting/rules.ts]: i meant functionKeyword. `@dec function func() {}` thought we can add that when we support it

Comment (mhegazy) [inline src/services/formatting/rules.ts]: i meant the sapceAfterDecorator rule would not apply to decorators expressions.

**Comment by mhegazy** [comment]
:+1:
