### PR TITLE
Avoid replacing last statement of derived constructors if 'this' is referenced.

### LINKED ISSUE #12764: Arrow functions don't work in super calls
Typescript version: 2.1.4

Playground: https://www.typescriptlang.org/play/index.html#src=class%20C%20%7B%0D%0A%09constructor(public%20f%3A%20%7B%20()%3A%20string%20%7D)%20%7B%0D%0A%0D%0A%09%7D%0D%0A%0D%0A%09%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20C%20%7B%0D%0A%09constructor()%20%7B%0D%0A%09%09super(()%20%3D%3E%20%7B%20return%20this.g()%3B%20%7D)%0D%0A%09%7D%0D%0A%0D%0A%09private%20g()%20%7B%0D%0A%09%09return%20%22hello%22%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aalert(new%20B().f())%3B

Source:

```
class C {
	constructor(public f: { (): string }) {
	}	
}

class B extends C {
	constructor() {
		super(() => { return this.g(); })
	}

	private g() {
		return "hello";
	}
}

alert(new B().f());
```
Expected result: "Hello" is alerted.
Actual result: calling f() fails with referenceerror.

The problem is that arrow functions are bound by the use of _this. Unfortunately, when there is a super call with no other this references, Typescript skips emitting the _this variable. _this doesn't exist so when the function is called, it fails.

If somehow this is the intended behaviour, the compiler should error on this references in super calls.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #12764.

### CODE REVIEW

File: src/compiler/transformers/es2015.ts [hunk 1]
```diff
@@ -1024,8 +1024,11 @@ namespace ts {
                 }
             }
 
-            // Return the result if we have an immediate super() call on the last statement.
-            if (superCallExpression && statementOffset === ctorStatements.length - 1) {
+            // Return the result if we have an immediate super() call on the last statement,
+            // but only if the constructor itself doesn't use 'this' elsewhere.
+            if (superCallExpression
+            && statementOffset === ctorStatements.length - 1
+            && !(ctor.transformFlags & (TransformFlags.ContainsLexicalThis | TransformFlags.ContainsCapturedLexicalThis))) {
```
Comment (DanielRosenwasser) [inline src/compiler/transformers/es2015.ts]: Question: Does `ContainsLexicalThisInComputedPropertyName` make sense to check here? I couldn't think of a scenario.

@mhegazy @rbuckton

File: tests/baselines/reference/arrowFunctionContexts.js [hunk 2]
```diff
@@ -116,7 +116,8 @@ var Base = (function () {
 var Derived = (function (_super) {
     __extends(Derived, _super);
     function Derived() {
-        return _super.call(this, function () { return _this; }) || this;
+        var _this = _super.call(this, function () { return _this; }) || this;
```
Comment (markboyall) [inline tests/baselines/reference/arrowFunctionContexts.js]: These baselines don't quite seem correct. Surely, _this should be declared and assigned to `this` first before the `super` call. That way, if the super call invokes the function, it'll still function as expected if the super does not return a new value for `this`.

Comment (DanielRosenwasser) [inline tests/baselines/reference/arrowFunctionContexts.js]: This is intentional - it is an error for `this` to be used before a call to `super(...)` completes.

This means that it shouldn't be an error to *reference* `_this`, but it should be an error to evaluate `_this` in a callback before the `super(...)` call returns.

File: src/compiler/transformers/es2015.ts (hunk 1 above)
Comment (rbuckton) [inline src/compiler/transformers/es2015.ts]: No, it's only used during aggregation to determine whether to promote `ContainsLexicalThis` in a computed property name so that it doesn't get stopped at a method or accessor.

Comment (rbuckton) [inline src/compiler/transformers/es2015.ts]: The indentation of the `if` condition looks a bit odd here.

Comment (rbuckton) [inline src/compiler/transformers/es2015.ts]: So `ContainsLexicalThis` means merely that a `this` keyword was somewhere inside of the function. `ContainsCapturedLexicalThis` means that a `this` keyword was captured by an arrow function inside the function.

File: tests/baselines/reference/arrowFunctionContexts.js (hunk 2 above)
Comment (markboyall) [inline tests/baselines/reference/arrowFunctionContexts.js]: ES2015 doesn't have a bunch of existing TypeScript code that evaluates this in a callback before the super() call returns.
