### PR TITLE
Fix preserveNewlines printer option when a list child has the same start or end as its parent

### LINKED ISSUE #37813: Refactored code that uses ASI is borked
Found from #37814.

```ts
function foo() {
    [|var x: number

    x = 10;
    return x;|]
}
```

Extract `[|` this range `|]` to a function in the global scope.

Expected:

```ts
function foo() {
    return yadda();
}

function yadda() {
    var x: number;
    
    x = 10;
    return x;
}
```

or

```ts
function foo() {
    return yadda();
}

function yadda() {
    var x: number
    
    x = 10;
    return x;
}
```

Actual:

```ts
function foo() {
    return yadda();
}

function yadda() {
    var x: number

        ;

    x = 10;
    return x;
}
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37813

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -4397,6 +4396,21 @@ namespace ts {
             return lines;
         }
 
+        function writeLineSeparatorsAndIndentBefore(node: Node, parent: Node): boolean {
```
Comment (andrewbranch) [inline src/compiler/emitter.ts:4399]: These functions are extracted from `emitParenthesizedExpression` because fixing the actual bug revealed that a JSX example was only working by accident because of the bug, and needed to borrow this code from `emitParenthesizedExpression`.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -4776,19 +4776,19 @@ namespace ts {
         return positionIsSynthesized(range.pos) ? -1 : skipTrivia(sourceFile.text, range.pos, /*stopAfterLineBreak*/ false, includeComments);
     }
 
-    export function getLinesBetweenPositionAndPrecedingNonWhitespaceCharacter(pos: number, sourceFile: SourceFile, includeComments?: boolean) {
+    export function getLinesBetweenPositionAndPrecedingNonWhitespaceCharacter(pos: number, stopPos: number, sourceFile: SourceFile, includeComments?: boolean) {
         const startPos = skipTrivia(sourceFile.text, pos, /*stopAfterLineBreak*/ false, includeComments);
-        const prevPos = getPreviousNonWhitespacePosition(startPos, sourceFile);
-        return getLinesBetweenPositions(sourceFile, prevPos || 0, startPos);
+        const prevPos = getPreviousNonWhitespacePosition(startPos, stopPos, sourceFile);
+        return getLinesBetweenPositions(sourceFile, prevPos ?? stopPos, startPos);
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts:4782]: Instead of doing this, why not just have `getPreviousNonWhitespacePosition` just return the `stopPos` instead of `undefined`?

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
🔔 other reviewers, my familiarity with the emitter is rusty

File: src/compiler/utilities.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/utilities.ts:4782]: I thought about that, but if someone wanted to use this elsewhere without looking at the implementation, I think returning a position that's not actually non-whitespace would be really surprising.
