### PR TITLE
Fix checker initialization crash

### LINKED ISSUE #46587: TS Server fatal error:  Cannot read property 'flags' of undefined
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.5.0-dev.20211028

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'flags' of undefined
    at getPropertyOfObjectType (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:56925:22)
    at getPropertyOfType (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:57585:24)
    at resolveESModuleSymbol (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49731:54)
    at getTargetOfNamespaceImport (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:48933:28)
    at getTargetOfAliasDeclaration (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49167:28)
    at resolveAlias (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49212:30)
    at getSymbol (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47770:38)
    at resolveNameHelper (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:48062:34)
    at resolveName (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:48045:20)
    at resolveEntityName (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49384:42)
    at resolveEntityName (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49392:33)
    at getSymbolOfPartOfRightHandSideOfImportEquals (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49344:24)
    at getTargetOfImportEqualsDeclaration (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:48796:28)
    at getTargetOfAliasDeclaration (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49163:28)
    at resolveAlias (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49212:30)
    at resolveSymbol (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:49202:67)
    at mergeSymbol (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47556:42)
    at /Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47671:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47669:20)
    at mergeSymbol (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47580:21)
    at /Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47671:47
    at Map.forEach (<anonymous>)
    at mergeSymbolTable (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47669:20)
    at mergeModuleAugmentation (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47685:17)
    at initializeTypeChecker (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:84884:25)
    at Object.createTypeChecker (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:47327:9)
    at Object.getTypeChecker (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:114201:79)
    at synchronizeHostData (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:159447:21)
    at Proxy.getProgram (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:159568:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:164578:53)
    at ConfiguredProject.Project.updateGraph (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:164507:42)
    at ConfiguredProject.updateGraph (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:165500:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:167224:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:168307:44)
    at /Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:168647:97
    at Object.flatMap (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:522:25)
    at ProjectService.applyChangesInOpenFiles (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:168647:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:169805:46)
    at /Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:171738:88
    at IOSession.Session.executeWithRequestId (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:171729:28)
    at IOSession.Session.executeCommand (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:171738:33)
    at IOSession.Session.onMessage (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:171764:35)
    at Interface.<anonymous> (/Users/fernandorojo/.vscode/extensions/ms-vscode.vscode-typescript-next-4.5.20211028/node_modules/typescript/lib/tsserver.js:174369:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|64.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id 3c85877a-7b27-4764-80da-510a866ec58a|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-apollo|apo|1.19.7
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
codespaces|Git|1.3.3
copilot|Git|1.6.3533
todo-tree|Gru|0.0.214
vscode-env|Iro|0.1.0
vscode-typescript-next|ms-|4.5.20211028
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.10.0
cobalt9|pyd|1.4.1
typescript-mono-repo-import-helper|q|0.0.6
synthwave-vscode|Rob|0.1.10
vscode-wakatime|Wak|17.1.0
fig|wit|0.0.5
material-theme|zhu|3.13.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200cf:30386380
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #46587

The auto import provider was trying to generate spelling suggestions for `IArguments` since it runs with `noLib: true`. Not sure why this happens only sometimes, but (a) there’s no point in trying to come up with spelling suggestions for global symbols, and (b) there’s no point in trying to come up with spelling suggestions for anything inside a non-diagnostics-producing checker.

### CODE REVIEW

**Review by weswigham — APPROVED** [review]
The work we do when producing diagnostics sometimes has side effects, like pushing things into caches, which can affect other calculations down the line, so I'm usually wary against `produceDiagnostics` checks that aren't _immediately_ around an `error` call, as it can the a source of reeeeeaaally hard to track bugs where hover info and error info on a symbol don't match (hover data comes from a non-diagnostics producing checkers, while errors do). Specifically here, there's a nested conditional `checkResolvedBlockScopedVariable` that might toss something into a cache which now we'd avoid doing - it's probably fine until proven otherwise, since everything in the guarded branch is _supposed_ to just be to generate an error message, I'd just keep it in mind in case something weird crops up in the future.

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1781,8 +1781,9 @@ namespace ts {
             nameNotFoundMessage: DiagnosticMessage | undefined,
             nameArg: __String | Identifier | undefined,
             isUse: boolean,
-            excludeGlobals = false): Symbol | undefined {
-            return resolveNameHelper(location, name, meaning, nameNotFoundMessage, nameArg, isUse, excludeGlobals, getSymbol);
+            excludeGlobals = false,
+            getSpellingSuggstions = true): Symbol | undefined {
```
Comment (minestarks) [inline src/compiler/checker.ts:1785]: I'm obviously very late to this PR but is this argument ironically named? 😛
