### PR TITLE
Fix rename for type symbols imported as a different name

### LINKED ISSUE #37188: Rename does not update aliased imports
From https://github.com/microsoft/vscode/issues/91940

**TypeScript Version:**  3.9.0-dev.20200303

**Search Terms:**

**Code**

`foo.ts`
```ts
export interface IFoo { 
    bla(): void;
}
```

`bar.ts`
```ts
import { IFoo as SomeAlias } from './index'

export class K implements SomeAlias {
    bla(): void { }
}
```

1. In `foo.ts`, rename `IFoo` to IFoo

**Expected behavior:**
Reference to `IFoo` in `bar.ts` is updated

**Actual behavior:**
The reference is not updated

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37188

### CODE REVIEW

File: src/services/utilities.ts [hunk 1]
```diff
@@ -92,7 +92,11 @@ namespace ts {
         if (node.kind === SyntaxKind.SourceFile) {
             return SemanticMeaning.Value;
         }
-        else if (node.parent.kind === SyntaxKind.ExportAssignment || node.parent.kind === SyntaxKind.ExternalModuleReference) {
+        else if (node.parent.kind === SyntaxKind.ExportAssignment
+            || node.parent.kind === SyntaxKind.ExternalModuleReference
+            || node.parent.kind === SyntaxKind.ImportSpecifier
+            || node.parent.kind === SyntaxKind.ImportClause
+            || isImportEqualsDeclaration(node.parent) && node === node.parent.name) {
```
Comment (andrewbranch) [inline src/services/utilities.ts:99]: The rename was bailing because it was calling `getMeaningFromLocation` on the import specifier’s identifier, and it was making it all the way to the bottom of the function, returning `SemanticMeaning.Value`. Seems like identifier serving as an import alias should be `SemanticMeaning.All`.
