### PR TITLE
Fixes JSX attribute escaping when parent pointers are missing

### LINKED ISSUE #35054: Printer breaks when there is \ in string literal in jsx attrs
**TypeScript Version:**  typescript@3.8.0-dev.20191105

**Search Terms:**
compilar api

**Code**

```ts
fs.writeFileSync(
  "out",
  ts
    .createPrinter()
    .printFile(
      ts.createSourceFile(
        "test.ts",
        fs.readFileSync("in", { encoding: "utf8" }),
        ts.ScriptTarget.ESNext,
        undefined,
        ts.ScriptKind.TSX
      )
    )
)
```

in
```
<a x="\\"/>
```

**Expected behavior:**

out
```
<a x="\\"/>
```

**Actual behavior:**
out
```
<a x="\\\\"/>
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
This ensures we use the correct character escaping mechanism when emitting a synthetic or unparented `StringLiteral` that is the initializer of a `JsxAttribute`.

Fixes #35054

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -637,8 +643,8 @@ namespace ts {
     export function isEffectiveModuleDeclaration(node: Node) {
         return isModuleDeclaration(node) || isIdentifier(node);
     }
-
     /** Given a symbol for a module, checks that it is a shorthand ambient module. */
+
```
Comment (sandersn) [inline src/compiler/utilities.ts]: look like this diff happened by mistake

**Comment by sandersn** [comment]
@rbuckton is this ready to go in?
