### PR TITLE
Ensure call return() for an abrupt completion at for await of loop

### LINKED ISSUE #52936: for await of loops don't call AsyncIterator.return() on early exit
# Bug Report

### 🔎 Search Terms

Async return AsyncIterator

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/MYewdgzgLgBAMgSQLIICowLwwMwG4CwAUEaJLAIYQCeYwCUApgE7kBGANg5jAN5EwwA2gGUqAW1Yh2AOko06jFlBBMAugAoAlL34CYnWAEtuABgKE9MJgygBXJmB0XLMMAwAeULU5d7S0GAATcC4sYwwI+GQ0c18Bf1gAN3J2W1CgkJgAfhhbMECGADNDN0CYAC4YQwBqati46zsHGAAFJhAxQwgGaWsIKUSGdR4YZNSGABoMtxgAX016y1mJ3UtG+zBvPmdffyke9hAAc3UAIgAlAFFUAFVzgDlThdWXAHpXmFQACy6YAHdDOx2DBWFxrORgF8GGVDIUYFAoTB-LYxMwkSlOGUAOSscEAayxMBUMCx6wchIY5CY7CoVUcCK4hxAAAdpC81jYNrxpgxKlAmGkpmM0pU8gViqU5os9MsXrN6rLCPKiER1HJaDBvBgAHw+GCFYnkP7kQywdQJVwoolw9UKZhsTjabaWPacaSHE5gFHPHYg-EKojzLS4IA)

### 💻 Code

```ts
const LIMIT = 3;

const asyncIterable = {
  [Symbol.asyncIterator]() {
    let i = 0;
    return {
      next() {
        const done = i === LIMIT;
        const value = done ? undefined : i++;
        return Promise.resolve({ value, done });
      },
      return() {
        console.log("RETURN");
        // This will be reached if the consumer called 'break' or 'return' early in the loop.
        return { done: true, value: undefined };
      },
    };
  },
};

(async () => {
  for await (const num of asyncIterable) {
    console.log(num);
    break;
  }
})();
```

### 🙁 Actual behavior

Outputted "0", the return function of the async iterator was never called.

### 🙂 Expected behavior

Output "0" and "RETURN" to the log. This would show that the return() function was called.

### LINKED ISSUE #53106: async iterator does not call return() for an abrupt completion at for await of loop
# Bug Report

### 🔎 Search Terms

async iterator, for await loop

### 🕗 Version & Regression Information

- This changed after version [v4.9.3](https://github.com/microsoft/TypeScript/releases/tag/v4.9.3)

### ⏯ Playground Link

Target: ES2017 (with actual result)
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhhAnmYBJKBTATnARgGwxgF4YBvAKBhgG0BlRAW1xHwDoFk1McoQsAugAoAlOSrUYWDFACuWMOMmSwGAB5RRS5ZNCRWGNvhABzIQHJVG0eZEBuCTqkz5isjABucfLIwAuGHMAQnMAGhgAE3B-GAAzbwgiAF8HJyTQx0lpOQUhLx8Y6CwASzATMUonaj0IAyNTC2zXG3tM5SaFck9vX3Co1QCoLF8YFLbRjOUx6iSKMYoa2EY4UpJ4JBQYLWIAPm1Y-ngAdxXYIUWYNRgQWPWudGw8QgrMmrrjMzVW5VxpOABrVKjOYUCjLUqiOxAA)

Target: ES2018 (with expected result)
[Playground link with relevant code](https://www.typescriptlang.org/play?target=5#code/MYewdgzgLgBAhhAnmYBJKBTATnARgGwxgF4YBvAKBhgG0BlRAW1xHwDoFk1McoQsAugAoAlOSrUYWDFACuWMOMmSwGAB5RRS5ZNCRWGNvhABzIQHJVG0eZEBuCTqkz5isjABucfLIwAuGHMAQnMAGhgAE3B-GAAzbwgiAF8HJyTQx0lpOQUhLx8Y6CwASzATMUonaj0IAyNTC2zXG3tM5SaFck9vX3Co1QCoLF8YFLbRjOUx6iSKMYoa2EY4UpJ4JBQYLWIAPm1Y-ngAdxXYIUWYNRgQWPWudGw8QgrMmrrjMzVW5VxpOABrVKjOYUCjLUqiOxAA)

### 💻 Code

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2017",
  }
}
```

index.ts

```ts
const asyncIterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        console.log('next()');
        return { value: '!', done: false };
      },
      return(value: string) {
        console.log('return()');
        return { value, done: true };
      },
    };
  }
};

const main = async () => {
  for await (const x of asyncIterable) {
    console.log(x);
    break;
  }
}

main();
```

Thanks to @kbridge for making [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

### 🙁 Actual behavior

```
next()
!
```

Should call `return()` for an abrupt completion at for await of loop (e.g. `break`, `throw`). This happens when `for-await-loop` code is transformed to target equal or lower than `ES2017`.

### 🙂 Expected behavior

```
next()
!
return()
```

If target for compilation is equal or higher than `ES2018`, It works as expected. This is also aligned with javascript specification.

### PR DESCRIPTION
**Pull request by niceandneat**
After #51297, early exit(e.g. `throw`) from `for await...of` statement body does not trigger `.return()` of the asyncIterator. This PR removes `try/finally` block to prevent a `nonUserCode` variable from being set `true` when code exit early.

**Before**
```ts
for (...) {
    _nonUserCode = false;
    try {
        const x = _value;
        // for statement body comes here
    }
    finally {
        // early exit at try block always reach this
        _nonUserCode = true;
    }
}
```

**After**
```ts
for (...) {
    _nonUserCode = false;
    {
        const x = _value;
        // for statement body comes here
    }
    // early exit at try block never reach this
    _nonUserCode = true;
}
```

It makes iterator call `.return()` after for loop exits early and fits more with the specification.

Fixes #53106
Fixes #52936

### CODE REVIEW

**Comment by niceandneat** [comment]
@microsoft-github-policy-service agree

**Comment by kbridge** [comment]
An [MCVE](https://stackoverflow.com/help/minimal-reproducible-example):

`package.json`

```json
{
  "devDependencies": {
    "@types/node": "18.14.0",
    "typescript": "4.9.5"
  },
  "type": "module"
}
```

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2017",
    "rootDir": ".",
    "outDir": "dist",
    "module": "Node16"
  }
}
```

`index.ts`

```ts
const asyncIterable = {
  [Symbol.asyncIterator]() {
    return {
      next() {
        console.log('next()');
        return { value: '!', done: false };
      },
      return(value) {
        console.log('return()');
        return { value, done: true };
      },
    };
  }
};

for await (const x of asyncIterable) {
  console.log(x);
  break;
}
```

code generated:

```js
var __asyncValues = (this && this.__asyncValues) || function (o) {
    if (!Symbol.asyncIterator) throw new TypeError("Symbol.asyncIterator is not defined.");
    var m = o[Symbol.asyncIterator], i;
    return m ? m.call(o) : (o = typeof __values === "function" ? __values(o) : o[Symbol.iterator](), i = {}, verb("next"), verb("throw"), verb("return"), i[Symbol.asyncIterator] = function () { return this; }, i);
    function verb(n) { i[n] = o[n] && function (v) { return new Promise(function (resolve, reject) { v = o[n](v), settle(resolve, reject, v.done, v.value); }); }; }
    function settle(resolve, reject, d, v) { Promise.resolve(v).then(function(v) { resolve({ value: v, done: d }); }, reject); }
};
var _a, e_1, _b, _c;
const asyncIterable = {
    [Symbol.asyncIterator]() {
        return {
            next() {
                console.log('next()');
                return { value: '!', done: false };
            },
            return(value) {
                console.log('return()');
                return { value, done: true };
            },
        };
    }
};
try {
    for (var _d = true, asyncIterable_1 = __asyncValues(asyncIterable), asyncIterable_1_1; asyncIterable_1_1 = await asyncIterable_1.next(), _a = asyncIterable_1_1.done, !_a;) {
        _c = asyncIterable_1_1.value;
        _d = false;
        try {
            const x = _c;
            console.log(x);
            break;
        }
        finally {
            _d = true;
        }
    }
}
catch (e_1_1) { e_1 = { error: e_1_1 }; }
finally {
    try {
        // _d is always true
        if (!_d && !_a && (_b = asyncIterable_1.return)) await _b.call(asyncIterable_1);
    }
    finally { if (e_1) throw e_1.error; }
}
export {};
```

**Comment by sandersn** [comment]
@niceandneat Can you please open a bug first? Please include @kbridge 's repro if it matches your problem.

**Comment by niceandneat** [comment]
@sandersn Thanks for the guide! I made a https://github.com/microsoft/TypeScript/issues/53106 and add it on the PR comment. Please check the issue.

**Review by rbuckton — COMMENTED** [review]
Unfortunately, the proposed changes break `continue`. I have an alternative solution I'm investigating, however.

**Comment by rbuckton** [comment]
I experimented a bit, and we can definitely drop the inner `try-finally` and instead switch back to non-user code in the incrementor of the `for` loop we emit. For example:

```ts
// source
for await (const x of y) {
  console.log(x);
}

// generated
var _a, e_1, _b, _c;
try {
    for (
      // start in non-user code
      /*initializer*/ var _d = true, y_1 = __asyncValues(y), y_1_1;
      /*condition*/   y_1_1 = await y_1.next(), _a = y_1_1.done, !_a;
      /*incrementor*/ _d = true // <- switch back to non-user code
    ) {
        _c = y_1_1.value;
        _d = false; // <- switch to user code
        const x = _c;

        // we can remove the inner try..finally and just inline the original body:
        console.log(x);
    }
}
catch (e_1_1) { e_1 = { error: e_1_1 }; }
finally {
    try {
        if (!_d && !_a && (_b = y_1.return)) await _b.call(y_1);
    }
    finally { if (e_1) throw e_1.error; }
}
```

This will allow local `continue` to still work, while treating other abrupt completions as user code.

@niceandneat: do you want to update this PR with this change, or should I create a new one?

**Comment by niceandneat** [comment]
@rbuckton Thanks a lot! I will update this PR with your changes and let you know.

**Comment by niceandneat** [comment]
@rbuckton I applied some changes to inline the original body. If It has any problem, please let me know.

File: src/compiler/transformers/es2018.ts [hunk 1]
```diff
@@ -765,48 +765,27 @@ export function transformES2018(context: TransformationContext): (x: SourceFile
...
-                    setTextRange(factory.createNodeArray(statements), statementsLocation),
-                    /*multiLine*/ true
-                ),
-                bodyLocation
+        return setEmitFlags(
+            factory.createBlock(
+                setTextRange(factory.createNodeArray(statements), statementsLocation),
+                /*multiLine*/ true
             ),
             EmitFlags.NoSourceMap | EmitFlags.NoTokenSourceMaps
```
Comment (rbuckton) [inline src/compiler/transformers/es2018.ts:787]: We should preserve `bodyLocation` and avoid setting these flags.

File: src/testRunner/unittests/evaluation/forAwaitOf.ts [hunk 2]
```diff
@@ -106,6 +106,62 @@ describe("unittests:: evaluation:: forAwaitOfEvaluation", () => {
...
+        }
+        export async function main() {
+            try { await f(); } catch { }
+            return returnCalled;
+        }
+        `, { target: ts.ScriptTarget.ES2015 });
+        assert.isTrue(await result.main());
+    });
+
+    it("don't call return when user code continue (es2015)", async () => {
```
Comment (rbuckton) [inline src/testRunner/unittests/evaluation/forAwaitOf.ts:137]: Can you add tests for `break`, `return`, and non-local `continue` (i.e., a labeled `continue` pointing to a label in an outer loop)?

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/testRunner/unittests/evaluation/forAwaitOf.ts (hunk 2 above)
Comment (niceandneat) [reply src/testRunner/unittests/evaluation/forAwaitOf.ts:211]: I also added local label `continue` case.

**Review by rbuckton — APPROVED** [review]
