### PR TITLE
Move JSX props support check and make syntactic

### LINKED ISSUE #22948: TypeError: Cannot read property 'length' of undefined
**TypeScript Version:**  2.9.0-dev.20180328

**Code**

```ts
import * as React from 'react';

const Test123 = () => <div/>;

function testComponent(props) {
    return <Test123 {...props}/>;
}
```

**Expected behavior:**
No errors

**Actual behavior:**
Exceptions:
```
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (/node_modules/typescript/lib/typescript.js:12280:19)
    at checkJsxAttributesAssignableToTagNameAttributes (/typescript/lib/typescript.js:40117:146)
    at checkJsxOpeningLikeElementOrOpeningFragment (/node_modules/typescript/lib/typescript.js:40052:17)
    at checkJsxSelfClosingElement (/node_modules/typescript/lib/typescript.js:39449:13)
    at checkExpressionWorker (/node_modules/typescript/lib/typescript.js:43637:28)
    at checkExpression (/node_modules/typescript/lib/typescript.js:43530:42)
    at checkExpressionCached (/node_modules/typescript/lib/typescript.js:43396:38)
    at getReturnTypeFromBody (/node_modules/typescript/lib/typescript.js:42348:24)
    at getReturnTypeOfSignature (/node_modules/typescript/lib/typescript.js:31762:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/node_modules/typescript/lib/typescript.js:42632:21)
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #22948. We can get `emptyObjectType` out of `resolveCustomJsxElementAttributesType` via `tryGetAllJsxStatelessFunctionAttributesType` via `getApparentType`, so it wan't really a great indicator for tracking the procedural error the comment by the offending check claims it was tracking. Now I've moved the error to where its conditions are initially checked, and perform the check syntactically rather than with types (meaning `<Obj {...{}}/>` will now error if `Obj` does not specify that it has props, which seems sensible) to facilitate this.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14767,7 +14767,7 @@ namespace ts {
             return propsType;
         }
 
-        function getJsxPropsTypeFromClassType(hostClassType: Type, isJs: boolean, context: Node) {
+        function getJsxPropsTypeFromClassType(hostClassType: Type, isJs: boolean, context: JsxOpeningLikeElement, reportErrors?: boolean) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Probably safer to make `reportErrors` non-optional?
