### PR TITLE
Fix equality narrowing and comparable relation for intersections with {}

### LINKED ISSUE #50706: 4.8.2 regression: type narrowing bug
# Bug Report

Instead of words, just the code. The comments say what is wrong and what used to work in 4.7.4.

```javascript
// Arguments are set to "unknown" because they receive data from network requests
// so runtime checks are mandatory to narrow type before use.
function SendBlob(data: unknown, encoding: unknown) {
    if (encoding !== undefined && encoding !== 'utf8') {
        throw new Error('encoding');
    }

    // Mouse hover to see detected type 
    // When using TS v4.8.2 it is {} | undefined
    // When using TS v4.7.4 it is "utf8" | undefined
    encoding;
};
```

### 🔎 Search Terms

"4.8.2" and I found a few but was told to file a new issue because I'm told it wasn't similar to the ones that I found and fought were similar.

I thought e.g. #50671 looks similar, not for the code but possibly for the deeper cause, since I don't think _that_ many things changed in exactly this part of TS since 4.7.4.

### 🕗 Version & Regression Information

4.7.4 works

4.8.2 doesn't work

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABAZQKZgCYCEA2cBGAFBgIZQkBci4A1mHAO5gA0i6EcGMYA5lbfSYBKRAG8AsAChEMxDGCJC7Ttx6IAhAF5N1TKmDdUGRADITbSCt4btiAOQgowABx2RE6bK9QAFgCdGRDBUBkQAUT8Av0I7ZS5eNwBuKS8AXykU2QB6LMQAWTgQAGdURB84ADdUP0QoOEQS0oxUKFRoI1qATwAHUsyZHMQAdR90aiLVRAAVZEQKgBYAOmdFgCY5KDkisVTEAB9dZoNgjH7EQZGx4smZuaWAdkX5ja3EACJHFzf9w-1DU88MjiqmSklSoKAA

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes both the original issue in #50706 and the issue reported [here](https://github.com/microsoft/TypeScript/issues/50706#issuecomment-1242366269). It also fixes an issue in control flow analysis of the false branch of `!=` (which should always yield the same result as the true branch of `==`, but didn't). Specifically, in [this test](https://github.com/microsoft/TypeScript/pull/50735/commits/a992a68deb6167edbffb036d764c20b46faac6ea#diff-e4e72b0b9fb71ec93b849c6a7f19ddeb711de8f9b061fee3997ba05b6916d5a8R363), `x` was wrongly narrowed to `number` in the last branch.

Fixes #50706.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
Tests and perf all look good. This one is ready to merge.

**Comment by ahejlsberg** [comment]
@andrewbranch Ping for review.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19191,11 +19191,15 @@ namespace ts {
                 // parameter 'T extends 1 | 2', the intersection 'T & 1' should be reduced to '1' such that it doesn't
                 // appear to be comparable to '2'.
                 if (relation === comparableRelation && target.flags & TypeFlags.Primitive) {
-                    const constraints = sameMap((source as IntersectionType).types, getBaseConstraintOrType);
+                    const constraints = sameMap((source as IntersectionType).types, t => t.flags & TypeFlags.Instantiable ? getBaseConstraintOfType(t) || unknownType : t);
                     if (constraints !== (source as IntersectionType).types) {
                         source = getIntersectionType(constraints);
+                        if (source.flags & TypeFlags.Never) {
+                            return Ternary.False;
+                        }
```
Comment (andrewbranch) [inline src/compiler/checker.ts:19199]: Where do these changes come into play?

Comment (ahejlsberg) [reply src/compiler/checker.ts:19199]: From the comment right above:

```ts
// Source is an intersection. For the comparable relation, if the target is a primitive type we hoist the
// constraints of all non-primitive types in the source into a new intersection. We do this because the
// intersection may further constrain the constraints of the non-primitive types. For example, given a type
// parameter 'T extends 1 | 2', the intersection 'T & 1' should be reduced to '1' such that it doesn't
// appear to be comparable to '2'.
```

The code previously didn't properly handle unconstrained type parameters, and it didn't properly handle the case where the hoisting causes the constraint to be `never` (meaning the types have no overlap).

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.8
