### PR TITLE
Trim empty line whitespaces

### LINKED ISSUE #4984: Trailing whitespace is not removed by formatter on 'empty' lines
The following test fails:

```typescript
/// <reference path='fourslash.ts' />

////    /*1*/
////	/*2*/

format.document();
verify.currentFileContentIs("\n");
````

_(where the contents before marker 2 are a `\t` character)_

I notice trailing whitespace is not removed from comments; whilst I would argue trailing whitespace should be removed across the board, I think it should at least be removed from lines only containing whitespace. 

Thoughts?

### PR DESCRIPTION
**Pull request by SaschaNaz**
(Replacing #5154 with no code change, now from a non-master branch)

Fixes #4984.

(Whitespaces are indicated by trailing /// below)

```typescript
  
// whitespace below   
    ///<- will now be removed
// whitespace above   
    ///<- will now be removed
let x;
  ///<- will now be removed
// abc
  ///<- will now be removed
let y;
  ///<- will now be removed
// whitespace above again
   ///<- will now be removed
while (true) {
    while (true) {
    }
      ///<- will now be removed
    // whitespace above   
}
  ///<- will now be removed
// whitespace above again  
   ///<- will now be removed
      ///<- will now be removed
```

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -341,6 +341,14 @@ namespace ts.formatting {
             processNode(enclosingNode, enclosingNode, startLine, undecoratedStartLine, initialIndentation, delta);
         }
 
+        if (!formattingScanner.isOnToken()) {
+            let leadingTrivia = formattingScanner.readTokenInfo(undefined).leadingTrivia;
```
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: this is not a supported way of using readTokenInfo, i guess you need a new API on the formattingScanner to getCurrrentLeadingTriva instead.

File: src/services/formatting/formatting.ts [hunk 2]
```diff
@@ -840,8 +848,8 @@ namespace ts.formatting {
 
                 // We need to trim trailing whitespace between the tokens if they were on different lines, and no rule was applied to put them on the same line
                 trimTrailingWhitespaces =
-                (rule.Operation.Action & (RuleAction.NewLine | RuleAction.Space)) &&
-                rule.Flag !== RuleFlags.CanDeleteNewLines;
+                    (rule.Operation.Action & (RuleAction.NewLine | RuleAction.Space | RuleAction.Ignore)) &&
```
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: may be just `!(rule.Operation.Acgtion & RuleAction.Delete)`

File: src/services/formatting/formatting.ts [hunk 3]
```diff
@@ -940,17 +948,49 @@ namespace ts.formatting {
...
+         * @param end The position of the last character in range
+         */
+        function getTrailingWhitespaceStartPosition(start: number, end: number) {
+            let pos = end;
+            while (pos >= start && isWhiteSpace(sourceFile.text.charCodeAt(pos))) {
+                pos--;
+            }
+            if (pos !== end) {
+                // pos must be out of range or non-whitespace
+                Debug.assert(pos === start - 1 || !isWhiteSpace(sourceFile.text.charCodeAt(pos)));
```
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: i would move this next to recordDelete, this is the whole point of this assert, and separating them makes it easy to break it.

File: src/services/formatting/formatting.ts [hunk 4]
```diff
@@ -940,17 +948,49 @@ namespace ts.formatting {
...
+            let endLine = sourceFile.getLineAndCharacterOfPosition(originalRange.end).line;
+
+            let endLineStartPosition = getStartPositionOfLine(endLine, sourceFile);
+            let endLineEndPosition = getEndLinePosition(endLine, sourceFile);
+
+            if (getTrailingWhitespaceStartPosition(endLineStartPosition, endLineEndPosition) === endLineStartPosition) {
+                // Trim the whole last line when it has whitespaces only
+                endLine++;
+            }
+            trimTrailingWhitespacesForLines(startLine, endLine, previousRange);
```
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: it should be safe to always call `endLine+1`, we should harden getEndLinePosition to make sure it handles correctly line numbers past the end of the file.

Comment (SaschaNaz) [inline src/services/formatting/formatting.ts]: @mhegazy  Calling always `endLine+1` formats unselected range and I'm not sure this will be desirable behavior:
```typescript
$/*selection start*/
    /// whitespaces
if $/*selection end*/(true) {     ///<- whitespaces here will be removed
```
What do you think?

**Comment by mhegazy** [comment]
Thanks @SaschaNaz!
