### PR TITLE
Widening and non-widening computed enum types

### LINKED ISSUE #52531: Type inference for declared enum member assignment
# Bug Report

### 🔎 Search Terms

enum, declare enum, union enum

### 🕗 Version & Regression Information

- This changed between versions 4.9 and 5.0

Noticed this change when testing the 5.0 beta, specifically in the wake of #50528.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230131#code/KYOwrgtgBAsgngUXNA3lAggGigIWwYSgF8BYAKHIBtgAXKANwENKBGKAXlkWQDp0Buck1YcuSSDxyCKZACbAAxpUYAnYFFCQuAEUXK1s8agzY8UQqRnU6wgEyj4upauCHeAoc3udHel24kpciA)

### 💻 Code

```ts
enum MyEnum { A, B, C }

let val1 = MyEnum.A;
//  ^? MyEnum
val1 = MyEnum.B;

declare enum MyDeclaredEnum { A, B, C }

let val2 = MyDeclaredEnum.A;
//  ^? MyDeclaredEnum.A
val2 = MyDeclaredEnum.B;
// ^ Type 'MyDeclaredEnum.B' is not assignable to type 'MyDeclaredEnum.A'.(2322)
```

### 🙁 Actual behavior

Assigning a declared enum member to a variable with `let` infers the type to be exactly the type of that specific enum member.

### 🙂 Expected behavior

The declared enum assignment should be the same as the regular enum assignment, where the type is inferred as the enum itself (a union of all enum members).

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #52531.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18026,25 +18037,25 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
     }
 
     function getRegularTypeOfLiteralType(type: Type): Type {
-        return type.flags & TypeFlags.Literal ? (type as LiteralType).regularType :
+        return type.flags & TypeFlags.Freshable ? (type as FreshableType).regularType :
             type.flags & TypeFlags.Union ? ((type as UnionType).regularType || ((type as UnionType).regularType = mapType(type, getRegularTypeOfLiteralType) as UnionType)) :
             type;
     }
 
     function isFreshLiteralType(type: Type) {
```
Comment (Andarist) [inline src/compiler/checker.ts:18057]: perhaps this "family" of functions could be renamed now? they all (`isFreshLiteralType`, `getRegularTypeOfLiteralType`, `getFreshTypeOfLiteralType`, `getRegularTypeOfLiteralType`) mention "literal" type but now they will also handle enums and enums are not literal types

Comment (ahejlsberg) [reply src/compiler/checker.ts:18057]: Yeah, but `isFreshFreshableType` and `getFreshTypeOfFreshableType` are pretty awful. 😮

**Comment by ahejlsberg** [comment]
Tests and performance all look good.

File: src/compiler/checker.ts (hunk 1 above)
Comment (Andarist) [reply src/compiler/checker.ts:18057]: Yeah, can't argue that 😅 OTOH, those names would be more correct - they sound a little bit weird at first but if we focus on their meaning, it makes sense.

**Review by weswigham — COMMENTED** [review]
I think since these are freshable now, we need a declaration emit test that validates we write out initializers for the fresh variant in declaration emit, eg,
```ts
declare function computed(x: number): number;

enum E {
    A = computed(0),
    B = computed(1),
    C = computed(2),
    D = computed(3),
}

export class A {
  prop = E.A;
}
```
needs to emit
```ts
export declare class A {
  prop = E.A;
}
```
rather than
```ts
export class A {
  prop: E;
}
```
(and that needs to not read back in as an error in a declaration file if it does right now, since it does serve a semantic purpose - preserving freshness)

File: tests/baselines/reference/computedEnumTypeWidening.js [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+var val1 = MyEnum.A;
+val1 = MyEnum.B;
+var val2 = MyDeclaredEnum.A;
+val2 = MyDeclaredEnum.B;
+
+
+//// [computedEnumTypeWidening.d.ts]
+declare function computed(x: number): number;
+declare enum E {
+    A,
```
Comment (weswigham) [inline tests/baselines/reference/computedEnumTypeWidening.js:131]: Uh, thinking about it, doesn't this declaration emit output for this enum imply it's auto-numbered rather than computed? Seems like another bug in declaration emit, actually. Probably need to emit _something_ with an initializer to preserve the computed-ness (and therefore freshability) of the member like
```ts
declare enum E {
  A = E as any as number
}
```
or some other perhaps less confusing pattern.

Comment (ahejlsberg) [reply tests/baselines/reference/computedEnumTypeWidening.js:131]: No, in an ambient context (`declare` or a `.d.ts` file) an enum member with a missing initializer implies computed (and we don't support auto-numbered members in ambient contexts). We shouldn't need any changes in emit.

**Comment by ahejlsberg** [comment]
> I think since these are freshable now, we need a declaration emit test that validates we write out initializers for the fresh variant in declaration emit

Agreed, though your example wouldn't validate that since class properties are mutable locations and their inferred types are always widened. But we should have an example of a `const` declaration with a fresh enum initializer.

File: tests/baselines/reference/computedEnumTypeWidening.js [hunk 3]
```diff
@@ -52,6 +52,16 @@ function f4() {
...
 }
 
+const c1 = E.B;
+const c2 = E.B as const;
+let v1 = E.B;
+let v2 = E.B as const;
+
+class C {
+  p1 = E.B;
+  p2 = E.B as const;
```
Comment (weswigham) [inline tests/baselines/reference/computedEnumTypeWidening.js:62]: A `readonly p3 = E.B` would be another good addition, since that one should be like a `const` declaration, iirc.

File: src/compiler/checker.ts (hunk 1 above)
Comment (fatcerberus) [reply src/compiler/checker.ts:18057]: The fresh type of bel-air!

I suppose it could be argued that `Enum.A` is an “enum literal”, even if it’s not a literal in the grammatical sense.  The compiler *is* treating it as one in a way by giving it its own nominal type (`Enum`)

Comment (Andarist) [reply src/compiler/checker.ts:18057]: The main problem from my PoV, is that "literal" is already used in the codebase and it often doesn't include enums:
https://github.com/microsoft/TypeScript/blob/30993855fd418a116ad92e821f7b6d4e52a3ca60/src/compiler/types.ts#L6042

I see now though that `EnumLiteral` also exist so maybe it isn't a big deal.

File: src/compiler/types.ts [hunk 4]
```diff
@@ -6028,7 +6028,8 @@ export const enum TypeFlags {
     /** @internal */
     Nullable = Undefined | Null,
     Literal = StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral,
-    Unit = Literal | UniqueESSymbol | Nullable,
+    Unit = Enum | Literal | UniqueESSymbol | Nullable,
+    Freshable = Enum | Literal,
```
Comment (DanielRosenwasser) [inline src/compiler/types.ts:6032]:
```suggestion
    /** @internal */
    Freshable = Enum | Literal,
```

File: src/compiler/types.ts [hunk 5]
```diff
@@ -6122,22 +6123,20 @@ export interface NullableType extends IntrinsicType {
     objectFlags: ObjectFlags;
 }
 
-/** @internal */
-export interface FreshableIntrinsicType extends IntrinsicType {
-    freshType: IntrinsicType;     // Fresh version of type
-    regularType: IntrinsicType;   // Regular version of type
+export interface FreshableType extends Type {
+    freshType: FreshableType;     // Fresh version of type
+    regularType: FreshableType;   // Regular version of type
```
Comment (andrewbranch) [inline src/compiler/types.ts:6128]: Was this intended to be public API now?

Comment (ahejlsberg) [reply src/compiler/types.ts:6128]: Yes.

**Comment by ahejlsberg** [comment]
I think all feedback has been addressed, can I get another review please?

**Review by weswigham — APPROVED** [review]
