### PR TITLE
Prevent crash on code fixes on default keyword 

### LINKED ISSUE #48008: Inappropriate assertion failure in 'getFixesInfoForNonUMDImport'
```ts
export { /**/default };
```

Request code fixes on `/**/`

```
<semantic> Response received: getCodeFixes (64). Request took 13 ms. Success: false . Message: Error processing request. Debug Failure. False expression: 'default' isn't a legal identifier and couldn't occur here
Error: Debug Failure. False expression: 'default' isn't a legal identifier and couldn't occur here
    at getFixesInfoForNonUMDImport ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:150288:22)
    at getFixesInfo ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:150156:24)
    at Object.getCodeActions ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:149633:28)
    at [USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:146935:77
    at Object.flatMap ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:508:25)
    at Object.getFixes ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:146935:23)
    at [USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:162162:35
    at Object.flatMap ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:508:25)
    at Object.getCodeFixesAtPosition ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:162160:23)
    at IpcIOSession.Session.getCodeFixes ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:173727:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:172360:61)
    at [USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174040:88
    at IpcIOSession.Session.executeWithRequestId ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174031:28)
    at IpcIOSession.Session.executeCommand ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174040:33)
    at IpcIOSession.Session.onMessage ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:174066:35)
    at process.<anonymous> ([USER_DIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220211\node_modules\typescript\lib\tsserver.js:176701:31)
    at process.emit (node:events:394:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #48008

`default` appears as an identifier in the AST, which appears to be expected. Just return `undefined` to skip the symbol rather than asserting that it's not legal.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -847,9 +847,10 @@ namespace ts.codefix {
         const checker = program.getTypeChecker();
         const compilerOptions = program.getCompilerOptions();
         const symbolName = getSymbolName(sourceFile, checker, symbolToken, compilerOptions);
-        // "default" is a keyword and not a legal identifier for the import, so we don't expect it here
-        Debug.assert(symbolName !== InternalSymbolName.Default, "'default' isn't a legal identifier and couldn't occur here");
-
+        // "default" is a keyword and not a legal identifier for the import, but appears as an identifier.
+        if (symbolName === InternalSymbolName.Default) {
+            return undefined;
```
Comment (14h) [inline src/services/codefixes/importFixes.ts:852]:
```suggestion
            return;

```

Comment (jakebailey) [reply src/services/codefixes/importFixes.ts:852]: While technically equivalent, I don't think an implicit undefined return is very clear (and this codebase doesn't really do this).

**Review by sandersn — APPROVED** [review]
