### PR TITLE
Fix crash in extract type and generate get/set refactors

### LINKED ISSUE #52751: 'Extract type' from property signature with erroneous initializer causes assertion failure
```ts
type Foo = [|{
    x: string = someString;
}|]
```

Request an "extract to type alias" refactoring on the specified `[|range|]`:

```
 Debug Failure. False expression: Token end is child end
Error: Debug Failure. False expression: Token end is child end
    at processChildNode (typescript/lib/tsserver.js:165873:17)
    at typescript/lib/tsserver.js:165804:9
    at visitNode2 (typescript/lib/tsserver.js:29284:18)
    at forEachChildInPropertySignature (typescript/lib/tsserver.js:29340:167)
    at forEachChild (typescript/lib/tsserver.js:29798:35)
    at processNode (typescript/lib/tsserver.js:165801:5)
    at processChildNode (typescript/lib/tsserver.js:165880:7)
    at processChildNodes (typescript/lib/tsserver.js:165923:32)
    at typescript/lib/tsserver.js:165817:9
    at visitNodes (typescript/lib/tsserver.js:29289:14)
    at forEachChildInTypeLiteral (typescript/lib/tsserver.js:29399:12)
    at forEachChild (typescript/lib/tsserver.js:29798:35)
    at processNode (typescript/lib/tsserver.js:165801:5)
    at processChildNode (typescript/lib/tsserver.js:165880:7)
    at typescript/lib/tsserver.js:165804:9
    at visitNode2 (typescript/lib/tsserver.js:29284:18)
    at forEachChildInTypeAliasDeclaration (typescript/lib/tsserver.js:29575:144)
    at forEachChild (typescript/lib/tsserver.js:29798:35)
    at processNode (typescript/lib/tsserver.js:165801:5)
    at formatSpanWorker (typescript/lib/tsserver.js:165609:5)
    at typescript/lib/tsserver.js:165549:105
    at getFormattingScanner (typescript/lib/tsserver.js:164365:15)
    at Object.formatNodeGivenIndentation (typescript/lib/tsserver.js:165549:10)
    at getFormattedTextOfNode (typescript/lib/tsserver.js:163762:43)
    at format (typescript/lib/tsserver.js:163742:27)
    at computeNewText (typescript/lib/tsserver.js:163743:219)
    at typescript/lib/tsserver.js:163704:25
    at mapDefined (typescript/lib/tsserver.js:2627:22)
    at typescript/lib/tsserver.js:163702:28
    at mapDefined (typescript/lib/tsserver.js:2627:22)
    at Object.getTextChangesFromChanges (typescript/lib/tsserver.js:163696:12)
    at ChangeTracker.getChanges (typescript/lib/tsserver.js:163585:35)
    at ChangeTracker.with (typescript/lib/tsserver.js:163083:20)
    at Object.getRefactorEditsToExtractType [as getEditsForAction] (typescript/lib/tsserver.js:156988:60)
    at Object.getEditsForRefactor (typescript/lib/tsserver.js:156469:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (typescript/lib/tsserver.js:135592:32)
    at IpcIOSession.getEditsForRefactor (typescript/lib/tsserver.js:178779:49)
    at getEditsForRefactor (typescript/lib/tsserver.js:177034:43)
```

### PR DESCRIPTION
**Pull request by rbuckton**
This PR fixes two crashes in refactors related to an attempt to refactor in the presence of a grammar error. This also removes `FunctionType` from the list of nodes that can have illegal modifiers, since `isStartOfFunctionOrConstructorType` already guards against a function type having modifiers.

Fixes #52751

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -863,7 +864,7 @@ function formatSpanWorker(
                 // if child node is a token, it does not impact indentation, proceed it using parent indentation scope rules
                 const tokenInfo = formattingScanner.readTokenInfo(child);
                 // JSX text shouldn't affect indenting
-                if (child.kind !== SyntaxKind.JsxText) {
+                if (child.kind !== SyntaxKind.JsxText && !isGrammarError(parent, child)) {
```
Comment (jakebailey) [inline src/services/formatting/formatting.ts:867]: Trying to understand the impact of this; if we format code that contains a grammar error node, will we now drop it?

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -265,6 +266,7 @@ import {
     isFunctionLike,
     isFunctionLikeDeclaration,
     isFunctionLikeOrClassStaticBlockDeclaration,
+    isFunctionTypeNode,
```
Comment (jakebailey) [inline src/compiler/utilities.ts:269]: This appears to be unused.

**Review by jakebailey — COMMENTED** [review]
LGTM besides the compile error.

File: src/services/codefixes/generateAccessors.ts [hunk 3]
```diff
@@ -258,7 +259,14 @@ function updatePropertyDeclaration(changeTracker: textChanges.ChangeTracker, fil
...
 
 function updatePropertyAssignmentDeclaration(changeTracker: textChanges.ChangeTracker, file: SourceFile, declaration: PropertyAssignment, fieldName: AcceptedNameType) {
-    const assignment = factory.updatePropertyAssignment(declaration, fieldName, declaration.initializer);
+    let assignment = factory.updatePropertyAssignment(declaration, fieldName, declaration.initializer);
+    // Remove grammar errors from assignment
+    if (assignment.modifiers || assignment.questionToken || assignment.exclamationToken) {
+        if (assignment === declaration) assignment = factory.cloneNode(assignment);
+        (assignment as Mutable<PropertyAssignment>).modifiers = undefined;
+        (assignment as Mutable<PropertyAssignment>).questionToken = undefined;
+        (assignment as Mutable<PropertyAssignment>).exclamationToken = undefined;
```
Comment (DanielRosenwasser) [inline src/services/codefixes/generateAccessors.ts:268]: Is this because `update` doesn't necessarily create a new node, but the result should still omit error recovery children?

**Review by DanielRosenwasser — APPROVED** [review]
Not a huge fan that formatting now has to be resilient against every weird grammar recovery node like this. I wish we could just get rid of these nodes from the tree itself - but this seems like a reasonable work-around.

File: src/services/codefixes/generateAccessors.ts (hunk 3 above)
Comment (rbuckton) [reply src/services/codefixes/generateAccessors.ts:268]: Yes, `update` only conditionally replaces the node.

**Review by jakebailey — APPROVED** [review]
