### PR TITLE
imporve conditional operator if  missing colon

### LINKED ISSUE #6127: Completion fails to find subsequent declaration in incomplete ternary
``` ts
1 ? f // does not work the autocompletion, `func` cannot select.
1 ? 1 : f // work the autocompletion, `func` can select.

function func() {}
```

Divides #6079.

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #6127 

ps: 
1. `createMissingNode` with `Identifier` type if `colonToken` is missing because `parseAssignmentExpressionOrHigher` with empty return it.  have there got any better solution？ 
2. `jsxAndTypeAssertion` is changed but i have no idea about that

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -1189,26 +1189,30 @@ namespace ts {
...
 
-        function createMissingNode<T extends Node>(kind: T["kind"], reportAtCurrentPosition: boolean, diagnosticMessage: DiagnosticMessage, arg0?: any): T {
-            if (reportAtCurrentPosition) {
-                parseErrorAtPosition(scanner.getStartPos(), 0, diagnosticMessage, arg0);
-            }
-            else {
-                parseErrorAtCurrentToken(diagnosticMessage, arg0);
-            }
-
+        function createMissingNodePlaceholder<T extends Node>(kind: T["kind"]) {
```
Comment (RyanCavanaugh) [inline src/compiler/parser.ts]: We don't need a new kind of missing node to handle this one case. Please work with the existing infrastructure for missing nodes

Comment (Kingwl) [reply src/compiler/parser.ts]: updated 😄
