### PR TITLE
Array cleanup

### LINKED ISSUE #13840: map on tuples with more than 5 elements
**TypeScript Version:**  2.1.1

**Code**

```ts
const a: [number, number, number, number, number, number] = [1,2,3,4,5,6];
const b = a.map(x => x)

```

**Expected behavior:**
`b` should have the same type as `a`, i.e. a tuple of 6 `number`s
**Actual behavior:**
`b` has the type of a tuple of 5 `number`s. Not only is this unexpected, it also doesn't match what happens at runtime where `b.length == a.length` as expected.

It seems to me that the problem comes from the tuple overloads of `map` added in https://github.com/Microsoft/TypeScript/pull/11252.
If I understand this correctly, https://github.com/Microsoft/TypeScript/issues/5453 would be needed in order to these overloads correctly for the general case.
In the meantime if there was some way of falling back to an array for map on longer tuples, that would work, e.g. adding an overload like this maybe?
```ts
map<Q extends [T, T, T, T, T, T], U>(this: Q, callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[];
```

### PR DESCRIPTION
**Pull request by mhegazy**
This change unifies ReadOnlyArray and Array interface methods; it also removes generic signatures from both interfaces that were only used to propagate the type of `thisArg` parameter. This reverts the changes in https://github.com/Microsoft/TypeScript/pull/12784, and unfixes #12548; the removal of the generic signatures saves a good chunk of time of building the compiler and some 30 K symbols created.

before
```sh
> node built\local\tsc.js --diagnostics --p src\compiler\tsconfig.json
Files:            34
Lines:         90626
Nodes:        443548
Identifiers:  167732
Symbols:       93831
Types:         37620
Memory used: 390453K
I/O read:      0.00s
I/O write:     0.05s
Parse time:    0.88s
Bind time:     0.86s
Check time:    4.31s
Emit time:     3.11s
Total time:    9.16s

```

after: 
```sh
>node built\local\tsc.js --diagnostics --p src\compiler\tsconfig.json
Files:            34
Lines:         90421
Nodes:        438317
Identifiers:  165477
Symbols:       63565
Types:         27751
Memory used: 376816K
I/O read:      0.00s
I/O write:     0.05s
Parse time:    0.88s
Bind time:     0.97s
Check time:    3.69s
Emit time:     2.34s
Total time:    7.87s
```

Also fixes #13840

### CODE REVIEW

File: src/lib/es5.d.ts [hunk 1]
```diff
@@ -1597,7 +1549,7 @@ interface Int8Array {
       */
     every(callbackfn: (this: void, value: number, index: number, array: Int8Array) => boolean): boolean;
     every(callbackfn: (this: void, value: number, index: number, array: Int8Array) => boolean, thisArg: undefined): boolean;
-    every<Z>(callbackfn: (this: Z, value: number, index: number, array: Int8Array) => boolean, thisArg: Z): boolean;
+    every<Z>(callbackfn: ( value: number, index: number, array: Int8Array) => boolean, thisArg: Z): boolean;
```
Comment (ahejlsberg) [inline src/lib/es5.d.ts]: Something isn't right here. All of the native array types still have three overloads per method, all that changed was that the `this` parameter disappeared from the last overload (and got replaced with a blank).

**Comment by ahejlsberg** [comment]
Maybe add a description that explains why we're simplifying this and include a link(s) to the issues that introduced the overloads in the first place.
