### PR TITLE
Disallow `[await] using` statements under case/default clauses

### LINKED ISSUE #62708: Should reject using / await using in a switch case / default clause
### 🔎 Search Terms

explicit resource management, using, await using, switch, case clause, default clause

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&ts=6.0.0-dev.20251030#code/M4dwlgLgxgFgBACgLIEMIwHQCcUDsAmA9gLYICUZcA3gFBxxQrACmcADAFx31wCuwYXAHM4+AExs4AXmpwA2gGUAnsQBGhADYZ8YYAAdCLALrlqAXzhmA3N3qqszFAGsb3RizgBGLjzgoQKJB8AsKiYp7Ssooq6lo6+obMJpRUFta2cPaOLjRmNDTMAB4GWBDmNEA

### 💻 Code

```ts
switch (Math.random()) {
  case 0:
    using d20 = { [Symbol.dispose]() {} };
    break;

  case 1:
    await using d21 = { [Symbol.dispose]() {} };
    break;
}

export {}
```

### 🙁 Actual behavior

No error happens.

### 🙂 Expected behavior

The error is reported that `using` / `await using` cannot be used here.

### Additional information about the issue

The spec was updated to disallow this (https://github.com/rbuckton/ecma262/pull/14).
Related PRs in other projects:
- https://github.com/babel/babel/pull/17323
- https://github.com/acornjs/acorn/pull/1374

Some tests needs to be updated. For example: https://github.com/microsoft/TypeScript/blob/1654ebfb54facadb3a0468ced0ca779ee323c7e5/tests/cases/conformance/statements/VariableStatements/usingDeclarations/usingDeclarations.1.ts#L98-L113

### PR DESCRIPTION
**Pull request by Renegade334**
As per tc39/ecma262@8e5d501ff76c17aaa79307157ae66cff240699b3, `[await] using` VariableStatements cannot be immediate children of case/default clauses; they must be contained within a block.

Resolves #62708.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -53081,6 +53082,14 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                         Diagnostics.The_left_hand_side_of_a_for_in_statement_cannot_be_an_await_using_declaration,
                 );
             }
+            else if (isVariableStatement(declarationList.parent) && isCaseOrDefaultClause(declarationList.parent.parent)) {
+                return grammarErrorOnNode(
```
Comment (jakebailey) [inline src/compiler/checker.ts:53086]: Surprised that this is not a parser error, but I guess the error above it isn't either. Fun that this means that we leave the bad node in the tree, but, that's what happens already:

```
//// [tests/cases/conformance/statements/VariableStatements/usingDeclarations/awaitUsingDeclarationsInForIn.ts] ////

//// [awaitUsingDeclarationsInForIn.ts]
async function main() {
    for (await using x in {}) {
    }
}


//// [awaitUsingDeclarationsInForIn.js]
async function main() {
    for (await using x in {}) {
    }
}
```

**Review by jakebailey — APPROVED** [review]
I think this is correct to my eye.

**Comment by jakebailey** [comment]
@typescript-bot test it
@typescript-bot pack this

File: src/compiler/checker.ts (hunk 1 above)
Comment (Renegade334) [reply src/compiler/checker.ts:53086]: Aye. Technically it is allowed in the ES grammar, it just triggers an early error.

**Comment by jakebailey** [comment]
Babel and acorn already did this, so I'll merge this. Thanks for the PR!
