### PR TITLE
Use getters to define live export bindings refresh

### LINKED ISSUE #6366: ES6 module variables are copied when re-exported
Given this example:

a.ts

``` js
export var a = 1;
export function changeA() { a = 2; }
```

b.ts

``` js
export * from './a';
```

c.ts

``` js
import { a, changeA } from './b';
console.log(a); // 1
changeA();
console.log(a); // Expected 2 but get 1
```

tsconfig.json

``` json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "out"
  }
}
```

Result of runing c.js:

```
$ node out/c.js
1
1
```

This happens because in b.ts this:

``` js
export * from './a';
```

transpiles to

``` js
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
__export(require('./a'));
```

and the value of variable a is copied and not referenced.

If I run the same example through babel it works because it generates getters that references the original variable. This was also proposed [here](https://github.com/Microsoft/TypeScript/issues/1215#issuecomment-63756746).

I propose that if the target is set to es5 then the generated code for commonjs modules uses getters instead to make sure that re-exported variables are referenced instead of copied.

### LINKED ISSUE #12522: [Bug] Re-exported binding doesn't track the original binding
**TypeScript Version:**  nightly (2.2.0-dev.20161127)

*EDIT: The issue described below is with `--module commonjs`, but as @aluanhaddad points out in a comment below, there are other behaviours with different module emits.*

I looked for an existing issue about this but didn't find one. Apologies if this is a duplicate.

I ran into a problem with TypeScript's emit for _re-exported_ bindings, in particular when the original exported value changes over time.

Importing a binding directly from a source module gets a 'live view' that changes when the export value changes, as it should. But **importing from a re-exported binding gets a snapshot that is no longer a live view of the original export**. This seems not to be spec compliant and leads to my code not working as intended.

## Code

```ts
// file: a.ts
export let liveView = 'foo';
export function changeTo(val: string) { liveView = val; }   // CHANGES THE EXPORT VALUE  



// file: b.ts
import {liveView, changeTo} from './a';     // <===== Import directly from A
console.log(liveView); // outputs 'foo'
changeTo('bar');
console.log(liveView); // outputs 'bar'        <===== GOOD: binding changed as it should

export {liveView, changeTo} from './a';     // <===== Re-export from A



// file: c.ts
import {liveView, changeTo} from './b';     // <===== Import via B's re-export
console.log(liveView); // outputs 'bar'
changeTo('baz');
console.log(liveView); // outputs 'bar'     // <===== BAD: binding is not live anymore
```

## Expected behavior
Emitted code should preserve the live binding to `liveView` when re-exporting from `b.ts`.

Last line of `c.ts` should output `'baz'`.

## Actual behavior
Emitted code exports a 'snapshot' of the `liveView` binding from `b.ts`, so that the import of `liveView` into `c.ts` is no longer a live binding.

Last line of `c.ts` incorrectly outputs `'bar'`.

## What should be the Correct Behaviour?
I found it hard to locate a clear description of correct ES6 behaviour for this situation, but from what I did find I think TypeScript's current emit is not compliant with ES6.

* E.g. from the [Exploring ES6](http://exploringjs.com/es6/index.html#toc_ch_modules) sections about [imports as views](http://exploringjs.com/es6/ch_modules.html#_imports-are-read-only-views-on-exports) and about [re-exports](http://exploringjs.com/es6/ch_modules.html#_re-exporting)

* Babel emits code that preserves the 'live-ness' of re-exports

So for `export { liveView } from 'some-module';` TypeScript emits something like:

```js
var some_module_1 = require("some-module");
exports.liveView = some_module_1.liveView;
```

Whereas babel emits something like:

```js
var _someModule = require('some-module');

Object.defineProperty(exports, 'liveView', {
  enumerable: true,
  get: function get() {
    return _someModule.liveView;
  }
});
```

### PR DESCRIPTION
**Pull request by weswigham**
This is an update/resync of #33587 with the feedback from the recent reviews applied and a merge with `master`. Hopefully you don't mind @mlrawlings.

Fixes #12522
Fixes #6366
Fixes #33587

cc @rbuckton and @ajafff for another review pass so we can get this in.

### CODE REVIEW

File: tests/baselines/reference/ambientShorthand_reExport.js [hunk 1]
```diff
@@ -24,7 +24,18 @@ exports.x = jquery_1.x;
 //// [reExportAll.js]
 "use strict";
 function __export(m) {
-    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
+    for (var p in m) b(p);
+    function b(p) {
+        if (!exports.hasOwnProperty(p))
+            Object.create
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/ambientShorthand_reExport.js]: Any chance you can update this for this feedback? https://github.com/microsoft/TypeScript/pull/33587#discussion_r362659106

> Not a fan of how this gets checked on every iteration of the loop. In other places, we just decide up front what the helper is going to be and use that.

**Comment by mlrawlings** [comment]
@weswigham I don't mind at all.  Thanks for moving this forward 👍

File: tests/baselines/reference/ambientShorthand_reExport.js (hunk 1 above)
Comment (weswigham) [reply tests/baselines/reference/ambientShorthand_reExport.js]: We _could_, but it'd double the helper size. In the case of `__importStar`, we'd go from
```ts
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) b(k);
    result["default"] = mod;
    return result;
    function b(p) {
        if (Object.hasOwnProperty.call(mod, p))
            Object.create
                ? Object.defineProperty(result, p, {
                      enumerable: true,
                      get: function() {
                          return mod[p];
                      }
                  })
                : (result[p] = mod[p]);
    }
};
```

to
```js
var __importStar = (this && this.__importStar) || (Object.create ? (function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) b(k);
    result["default"] = mod;
    return result;
    function b(p) {
        if (Object.hasOwnProperty.call(mod, p))
            Object.defineProperty(result, p, {
                enumerable: true,
                get: function() {
                    return mod[p];
                }
            });
    }
}) : (function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) b(k);
    result["default"] = mod;
    return result;
    function b(p) {
        if (Object.hasOwnProperty.call(mod, p))
             result[p] = mod[p];
    }
}));
```
(you can compress it a bit more with another helper to join the shared bits between the two implementations, but not much, and that's much more complexity)

I think doing the (hopefully fast) check on the (executed only a few times at the top level) import/export helpers is a fair enough tradeoff to make in our default helper implementations. Really: If you have strong execution speed or size concerns, you'll be providing custom helpers that target exactly the runtime you're building for, without any runtime feature testing at all.

File: src/compiler/transformers/module/module.ts [hunk 2]
```diff
@@ -1847,9 +1880,20 @@ namespace ts {
 var __importStar = (this && this.__importStar) || function (mod) {
     if (mod && mod.__esModule) return mod;
     var result = {};
-    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
+    if (mod != null) for (var k in mod) b(k);
     result["default"] = mod;
```
Comment (ajafff) [inline src/compiler/transformers/module/module.ts]: This needs to use `Object.defineProperty` (with `value` instead of `get`), because assignments will fail if `mod` has a `default` property

File: tests/baselines/reference/ambientShorthand_reExport.js (hunk 1 above)
Comment (DanielRosenwasser) [reply tests/baselines/reference/ambientShorthand_reExport.js]: > (you can compress it a bit by moving the property definition into another helper (eg `__setBinding`) but that's way more complexity, and if we wanted to do that, I'd rather do it in a followup)

Yeah, that's what I had in mind. But I guess we can improve in another PR if users ask.

**Comment by weswigham** [comment]
@ajafff @DanielRosenwasser @rbuckton 

I've updated our emit to use an unscoped `__exportStar` helper everywhere, and made both it and the `__importStar` helper rely on a new `__createBinding` helper. `__importStar` also relies on a new `__setModuleDefault` helper to appropriately handle the define vs assignment downlevel for the default member assignment (it could be inlined into `__importStar` if you're willing to feature test on every invocation, but I think it reads better extracted into its own helper).

In addition, our es3 emit for `export {x} from "foo"` uses the `__createBinding` helper, rather than emitting an assignment (so live bindings for those members are appropriately feature tested). Our es5 emit is still an inline `Object.defineProperty` call.

I think that implements all the suggestions from the previous thread and this one? Once we're OK with it, I can open an accompanying tslib PR.

**Comment by DanielRosenwasser** [comment]
Just to be clear, this needs to wait until 3.9 unless we're okay with a break in the RC and not the beta (which I'd prefer we didn't)

**Comment by weswigham** [comment]
I figured as much (but that just means we shan't merge it for about 2 weeks); but we do need to look at getting this in soon - it's one of the blockers to migrating us to modules.

**Comment by ajafff** [comment]
@weswigham @rbuckton there's another thing that needs to be fixed in the module transform: uninitialized bindings are not assigned to the `exports` object until the first assignment.
Since `__importStar` and `__export` only run once and iterate over all existing properties on `exports`, these bindings are never considered:

```ts
// @filename: foo.ts
export let foo: number; // this doesn't write 'exports.foo' until the first call to 'setFoo'
export function setFoo(v: number) {
    foo = v;
}

// @filename: bar.ts
export * from './foo'; // this only re-exports 'setFoo' because 'foo' is not present yet

// @filename: baz.ts
import {foo, setFoo} from './bar';
setFoo(1);
console.log(foo); // should print '1', currently prints 'undefined'
```

To achieve this, exported variables without initializer need to be initialized with `undefined` in the emit, e.g. `exports.foo = undefined;` in the example above.

**Comment by sandersn** [comment]
@weswigham now that master branch is headed toward 3.9, is this ready to go in?

@DanielRosenwasser does your feedback still apply? It looks like it was addressed but I only skimmed the issue.

**Comment by weswigham** [comment]
I hope so; though @ajaff's remark on needing to create getters for uninitialized variables is valid (that we didn't initialize them before was odd, too, so it's not a regression, but it should probably be fixed).

**Comment by DanielRosenwasser** [comment]
Yes, I think this is ready to merge.

**Comment by weswigham** [comment]
ping @rbuckton for a code review~

**Comment by weswigham** [comment]
I've opened #36806 to review once this is in to address @ajafff 's concern about initializerless exported variables.

ping @rbuckton again for a review~

**Comment by ExE-Boss** [comment]
I&nbsp;think we&nbsp;should try&nbsp;to&nbsp;use&nbsp;`Object.prototype.__defineGetter__` if&nbsp;`Object.defineProperty` doesn’t&nbsp;exist, but&nbsp;`__defineGetter__`&nbsp;does.

**Comment by weswigham** [comment]
ping @rbuckton again again~

File: src/compiler/transformers/module/module.ts [hunk 3]
```diff
@@ -1813,21 +1839,61 @@ namespace ts {
...
+        return createCall(getUnscopedHelperName("__createBinding"), /*typeArguments*/ undefined, [createIdentifier("exports"), module, inputName, ...(outputName ? [outputName] : [])]);
+    }
+
+    export const setModuleDefaultHelper: UnscopedEmitHelper = {
+        name: "typescript:commonjscreatevalue",
+        importName: "__setModuleDefault",
+        scoped: false,
+        priority: 1,
+        text: `
+var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: I assume we will need to add this to tslib?

File: src/compiler/transformers/module/module.ts [hunk 4]
```diff
@@ -1813,21 +1839,61 @@ namespace ts {
         }
     }
 
+    export const createBindingHelper: UnscopedEmitHelper = {
+        name: "typescript:commonjscreatebinding",
+        importName: "__createBinding",
+        scoped: false,
+        priority: 1,
+        text: `
+var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: This will also need to be in tslib.

File: tests/baselines/reference/commentsOnRequireStatement.js [hunk 5]
```diff
@@ -32,7 +32,7 @@ Object.defineProperty(exports, "__esModule", { value: true });
 // blah 
 // blah 
 var _0_1 = require("./0");
-exports.subject = _0_1.subject;
+Object.defineProperty(exports, "subject", { enumerable: true, get: function () { return _0_1.subject; } });
```
Comment (rbuckton) [inline tests/baselines/reference/commentsOnRequireStatement.js]: Any reason not to just use the `__createBinding` helper for these cases?

File: src/compiler/transformers/module/module.ts [hunk 6]
```diff
@@ -1813,21 +1839,61 @@ namespace ts {
...
 
+    export const createBindingHelper: UnscopedEmitHelper = {
+        name: "typescript:commonjscreatebinding",
+        importName: "__createBinding",
+        scoped: false,
+        priority: 1,
+        text: `
+var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
+    if (k2 === undefined) k2 = k;
+    Object.defineProperty(o, k2, {
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: nit: This would all fit on one line and still be legible.

File: src/compiler/transformers/module/module.ts [hunk 7]
```diff
@@ -1813,21 +1839,61 @@ namespace ts {
...
         name: "typescript:export-star",
-        scoped: true,
+        importName: "__exportStar",
+        scoped: false,
+        dependencies: [createBindingHelper],
+        priority: 2,
         text: `
-            function __export(m) {
-                for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
+            var __exportStar = (this && this.__exportStar) || function(m, exports) {
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: We will need to update tslib for this as well.

File: src/compiler/transformers/module/module.ts [hunk 8]
```diff
@@ -1813,21 +1839,61 @@ namespace ts {
...
+    }
+
+    export const setModuleDefaultHelper: UnscopedEmitHelper = {
+        name: "typescript:commonjscreatevalue",
+        importName: "__setModuleDefault",
+        scoped: false,
+        priority: 1,
+        text: `
+var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
+    Object.defineProperty(o, "default", {
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: nit: This would fit on a single line and still be legible.

File: src/compiler/transformers/module/module.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: Aye.

File: src/compiler/transformers/module/module.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: Yep.

File: tests/baselines/reference/commentsOnRequireStatement.js (hunk 5 above)
Comment (weswigham) [reply tests/baselines/reference/commentsOnRequireStatement.js]: We use `__createBinding` when targeting es3; we use this when targeting `es5` (since the assumption is when targeting es5, we don't need the conditional behavior of `__createBinding`).

File: src/compiler/transformers/module/module.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: https://github.com/microsoft/tslib/pull/89

File: src/compiler/transformers/module/module.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: https://github.com/microsoft/tslib/pull/89

File: src/compiler/transformers/module/module.ts (hunk 7 above)
Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: https://github.com/microsoft/tslib/pull/89

Comment (weswigham) [reply src/compiler/transformers/module/module.ts]: (`tslib` already has an `__exportStar` helper, we just update it)

File: tests/baselines/reference/ambientShorthand_reExport.js (hunk 1 above)
Comment (rbuckton) [reply tests/baselines/reference/ambientShorthand_reExport.js]: You also could have done this:
```js
var __importStar = (this && this.__importStar) || (function () {
  var setModuleDefault = (Object.create ? (function(o, v) {
        Object.defineProperty(o, "default", { enumerable: true, value: v });
    }) : function(o, v) {
        o["default"] = v;
    });
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
        setModuleDefault(result, mod);
        return result;
    };
})();

Comment (rbuckton) [reply tests/baselines/reference/ambientShorthand_reExport.js]: Or this:
```js
var __importStar = (this && this.__importStar) || (function (setModuleDefault) {
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
        setModuleDefault(result, mod);
        return result;
    };
})(Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
```

Comment (weswigham) [reply tests/baselines/reference/ambientShorthand_reExport.js]: See, it's used by both `__importStar` _and_ `__exportStar`, though, so it actually saves space by being a separate helper.

Comment (rbuckton) [reply tests/baselines/reference/ambientShorthand_reExport.js]: We already do that for `__extends` in tslib. In `src/compiler/transformers/es2015.ts` we have `extendsStatics` inline inside of `__extends`, but in tslib they are two distinct functions.

Comment (rbuckton) [reply tests/baselines/reference/ambientShorthand_reExport.js]: We also defer its value until later in case a polyfill adds `Object.setPrototypeOf`, but you can't properly polyfill `Object.defineProperty` due to IE8.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -35661,6 +35665,8 @@ namespace ts {
                 case ExternalEmitHelpers.MakeTemplateObject: return "__makeTemplateObject";
                 case ExternalEmitHelpers.ClassPrivateFieldGet: return "__classPrivateFieldGet";
                 case ExternalEmitHelpers.ClassPrivateFieldSet: return "__classPrivateFieldSet";
+                case ExternalEmitHelpers.CreateBinding: return "__createBinding";
+                case ExternalEmitHelpers.SetModuleDefault: return "__setModuleDefault";
```
Comment (rbuckton) [inline src/compiler/checker.ts]: Just noticed this: This doesn't need to be checked since its an internal implementation detail of `__importStar`.

Comment (weswigham) [reply src/compiler/checker.ts]: https://github.com/microsoft/TypeScript/pull/36998
