### PR TITLE
🔨 Fix missing "Implement interface" code fix for mapped types with implicit `keyof T` in their definition

### LINKED ISSUE #49811: Implement mapped type
# Suggestion

## 🔍 Search Terms

+ implement mapped type
+ class implements mapped type
+ interface extends mapped type
+ autocomplete for mapped type in class
+ intellisense for mapped type in class

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to implement a mapped type from a class and let Typescript/VS Code implement the methods I just created using template literal types.

``` typescript
export const methods = [
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "OPTIONS",
  "HEAD",
] as const;

export type Method = typeof methods[number];

type MethodMapper = {
  [P in Method as ${Lowercase<string & P>}]: () => void;
};

class Router implements MethodMapper {
}
```

image

Currently the Typescript Playground and Visual Studio Code doesn't implement my new type:

image

## 📃 Motivating Example

Implement a mapped type into a class using template literal types.

## 💻 Use Cases

Currently I'm working in a new routing library and want to type check new methods added in `methods` array. For now the workaround is implement the methods by hand in my class.

Thank you in advance.

### PR DESCRIPTION
**Pull request by babakks**
Fixes #49811

This PR implements the second solution explained in the original thread ([here](https://github.com/microsoft/TypeScript/issues/49811#issuecomment-1192434967)).

### CODE REVIEW

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -88,13 +86,16 @@ namespace ts.codefix {
...
+                    declaration ? name : symbol.getName(),
                     optional && (preserveOptional & PreserveOptionalFlags.Property) ? factory.createToken(SyntaxKind.QuestionToken) : undefined,
                     typeNode,
                     /*initializer*/ undefined));
                 break;
             case SyntaxKind.GetAccessor:
             case SyntaxKind.SetAccessor: {
+                if (!declarations) {
+                    break;
+                }
```
Comment (andrewbranch) [inline src/services/codefixes/helpers.ts:98]: This (and the later one) appear to be impossible, so you can just do `Debug.assertDefined(declarations)` instead.

File: src/services/codefixes/helpers.ts [hunk 2]
```diff
@@ -60,21 +60,19 @@ namespace ts.codefix {
         isAmbient = false,
     ): void {
         const declarations = symbol.getDeclarations();
-        if (!(declarations && declarations.length)) {
-            return undefined;
-        }
+        const declaration = declarations ? declarations[0] : undefined;
```
Comment (andrewbranch) [inline src/services/codefixes/helpers.ts:63]:
```suggestion
        const declaration = declarations?.[0];
```

File: src/services/codefixes/helpers.ts [hunk 3]
```diff
@@ -60,21 +60,19 @@ namespace ts.codefix {
...
     ): void {
         const declarations = symbol.getDeclarations();
-        if (!(declarations && declarations.length)) {
-            return undefined;
-        }
+        const declaration = declarations ? declarations[0] : undefined;
         const checker = context.program.getTypeChecker();
         const scriptTarget = getEmitScriptTarget(context.program.getCompilerOptions());
-        const declaration = declarations[0];
+        const kind = declaration?.kind ?? SyntaxKind.PropertySignature;
```
Comment (andrewbranch) [inline src/services/codefixes/helpers.ts:66]: Can you just add a comment explaining when this would happen (the mapped type case)? It’s a little hard to understand what’s happening when read outside the context of the issue being fixed here.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Just a couple small nits; this looks good overall to me.

**Comment by babakks** [comment]
@andrewbranch The CI failure seems unrelated. I checked the failed test, `objectFreezeLiteralsDontWiden.ts`, on the `main` branch (latest: `9767f51758`) and it failed again.

**Review by andrewbranch — APPROVED** [review]
Thanks!
