### PR TITLE
Get jsdoc host from chained assignment

### LINKED ISSUE #35021: TypeError: Cannot read property 'flags' of undefined
**TypeScript Version:**  3.7.2

**How to reproduce**

- (Step 1) Create file `test.js`
```js
(function () {
  var obj = {};
  /**
   * test test
   * @constructor
   * @remind remind
   * @param { Object } options param
   * @example
   * ```javascript
   * var editor = new UE.Editor();
   * editor.execCommand('blod');
   * ```
   * @see TEST.Config
   */
  var a = obj.a = function (options) {
    console.log(this)
  };
})();
```

- (Step 2) Create file `tsconfig.json`
```json
{
  "compilerOptions": {
    "outDir": "./built",
    "allowJs": true,
    "newLine": "lf",
    "target": "es5"
  },
  "files": [
    "test.js"
  ]
}
```

- (Step 3) Open git bash, run command `tsc`

**Expected behavior:**
no errors

**Actual behavior:**

```
$ tsc
C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:78566
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getFlowTypeOfReference (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:42017:80)
    at tryGetThisTypeAt (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:43171:28)
    at checkThisExpression (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:43135:24)
    at checkExpressionWorker (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48624:28)
    at checkExpression (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48578:38)
    at checkExpressionWithContextualType (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:48319:24)
    at getSignatureApplicabilityError (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:45667:35)
    at chooseOverload (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:46035:25)
    at resolveCall (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:45938:26)
    at resolveCallExpression (C:\Users\talen\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:46256:20)
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by sandersn**
getSourceOfAssignment previously only checked one level of binary
expression instead of following binary expressions all the way to the
right. This meant that binding of `@constructor` would fail in the
following example:

```js
/** @constructor */
a = b = function () { }
```

Fixes #35021

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -2317,11 +2317,14 @@ namespace ts {
...
     function getSourceOfAssignment(node: Node): Node | undefined {
-        return isExpressionStatement(node) &&
-            node.expression && isBinaryExpression(node.expression) &&
-            node.expression.operatorToken.kind === SyntaxKind.EqualsToken
-            ? node.expression.right
-            : undefined;
+        if(isExpressionStatement(node) && isBinaryExpression(node.expression) && node.expression.operatorToken.kind === SyntaxKind.EqualsToken) {
+            let cur = node.expression;
+            while (isBinaryExpression(cur.right) && cur.right.operatorToken.kind === SyntaxKind.EqualsToken) {
+                cur = cur.right;
```
Comment (andrewbranch) [inline src/compiler/utilities.ts]: From a quick glance, I think this is a re-implementation of `getRightMostAssignedExpression`?

Comment (sandersn) [reply src/compiler/utilities.ts]: Looks like it! I found `getInitializerOfBinaryExpression`, but not getRightMostAssignedExpression.

**Comment by usmcgwg** [comment]
Could you sene me a good POC for you
