### PR TITLE
Fix sending correct symbol when using commonjs require and destructuring

### LINKED ISSUE #42828: Debug Failure. False expression: Should only get Alias here. in getImmediateAliasedSymbol
**Repo Name**: https://github.com/hexojs/hexo.git

**Revision**: 09334c0e34e752d4a4ba03611a7bfae801b984ac

**TypeScript Version**: 4.3.0-dev.20210216

**Commands**: 

```
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":10603,"file":"D:/local/Temp/fuzzerWorkingDir/hexo/test/scripts/filters/external_link.js"},"type":"request","seq":25}
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":31,"file":"D:/local/Temp/fuzzerWorkingDir/hexo/test/scripts/filters/external_link.js"},"type":"request","seq":22}
{"response":{"canRename":false,"localizedErrorMessage":"You cannot rename this element."},"responseRequired":true}
{"command":"rename-full","arguments":{"position":10587,"file":"D:/local/Temp/fuzzerWorkingDir/hexo/test/scripts/filters/external_link.js"},"type":"request","seq":24}
{"response":{"canRename":true,"kind":"property","displayName":"external_link","fullDisplayName":"__object.external_link","kindModifiers":"","triggerSpan":{"start":10578,"length":13}},"responseRequired":true}
{"command":"rename-full","arguments":{"position":10587,"file":"D:/local/Temp/fuzzerWorkingDir/hexo/test/scripts/filters/external_link.js"},"type":"request","seq":25}
{"response":{"canRename":true,"kind":"property","displayName":"external_link","fullDisplayName":"__object.external_link","kindModifiers":"","triggerSpan":{"start":10578,"length":13}},"responseRequired":true}
{"command":"renameLocations-full","arguments":{"position":10587,"file":"D:/local/Temp/fuzzerWorkingDir/hexo/test/scripts/filters/external_link.js"},"type":"request","seq":26}
(Showing last 10 of 71781 commands)
```

**Code** ([`test\scripts\filters\external_link.js`](https://github.com/hexojs/hexo/blob/09334c0e34e752d4a4ba03611a7bfae801b984ac/test/scripts/filters/external_link.js)):

```js
      ].join('\n'));
  
      hexo.config.external_link.exclude = '';
//                         ^
    });
  });
```

**Hash**: 2107b96705808be8ca73633f44bc75ce
**Stack trace**: 
```
Debug Failure. False expression: Should only get Alias here.
    at getImmediateAliasedSymbol (tsserverlibrary.js:66934:22)
    at getImport (tsserverlibrary.js:123529:46)
    at getImportOrExportSymbol (tsserverlibrary.js:123449:68)
    at getImportOrExportReferences (tsserverlibrary.js:125051:56)
    at getReferencesAtLocation (tsserverlibrary.js:124981:17)
    at getReferencesInContainer (tsserverlibrary.js:124925:21)
    at getReferencesInSourceFile (tsserverlibrary.js:124912:24)
    at searchForName (tsserverlibrary.js:124706:21)
    at getReferencesInContainerOrFiles (tsserverlibrary.js:124479:25)
    at getReferencedSymbolsForSymbol (tsserverlibrary.js:124463:21)
```

_Originally posted by @typescript-bot in https://github.com/microsoft/tsserverfuzzer/issues/292#issuecomment-779934152_

### PR DESCRIPTION
**Pull request by armanio123**
Fixes #42828

When using destructuring on a commonjs require syntax, the server throws a debug as the symbol is not flagged as "Alias". Instead now we look for the parent symbol which is correctly flagged.

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -1512,6 +1512,11 @@ namespace ts.FindAllReferences {
                     Debug.assertNever(state.specialSearchKind);
             }
 
+            // Use the parent symbol if the location is commonjs require syntax on javascript files only.
+            referenceSymbol = isInJSFile(referenceLocation) && isRequireVariableDeclaration(referenceLocation.parent)
```
Comment (andrewbranch) [inline src/services/findAllReferences.ts:1516]: You should also check the `kind` of `referenceLocation` here, since the `require("whatever")` side’s parent is _also_ the `RequireVariableDeclaration`, and what you’re trying to ask here is if you have the left-hand side.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Small nit, looks good overall

File: src/services/findAllReferences.ts (hunk 1 above)
Comment (armanio123) [reply src/services/findAllReferences.ts]: I have changed it to check if the parent of `referenceLocation` is `BindingElement`. I think this is more accurate if we want to make sure we're checking on the `identifier`.

File: src/services/findAllReferences.ts [hunk 2]
```diff
@@ -1512,6 +1512,11 @@ namespace ts.FindAllReferences {
                     Debug.assertNever(state.specialSearchKind);
             }
 
+            // Use the parent symbol if the location is commonjs require syntax on javascript files only.
+            referenceSymbol = isInJSFile(referenceLocation) && referenceLocation.parent.kind === SyntaxKind.BindingElement && isRequireVariableDeclaration(referenceLocation.parent)
```
Comment (andrewbranch) [inline src/services/findAllReferences.ts:1516]: `referenceLocation.parent` can’t be both a `BindingElement` and a `RequireVariableDeclaration`, right?

_Checks that function..._

Oh no, someone added

```ts
if (node.kind === SyntaxKind.BindingElement) {
   node = node.parent.parent;
}
```

without noticing that the return type of the function is `node is RequireVariableDeclaration` 🤦 

That function is now wrong but you’re not relying on the incorrect results of it, so this is fine.

**Review by andrewbranch — APPROVED** [review]
