### PR TITLE
Pick correct compilerOptions when checking if we can share emitSignatures

### LINKED ISSUE #50902: getCompilerOptionValue can be called with options = undefined after tsconfig#module change
# Bug Report

### 🔎 Search Terms

modules esmodules

### 🕗 Version & Regression Information

v4.8.2
- This is a crash

I am converting some old code from `module=none` to `module=es2015`.
After changing the code and tsconfig I get
````
in folder: C:\tfs\TwinCAT-HMI\TcHmiFramework ...C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:16219
        return option.strictFlag ? getStrictOptionValue(options, option.name) : options[option.name];
                                                                                       ^

TypeError: Cannot read properties of undefined (reading 'outFile')
    at getCompilerOptionValue (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:16219:88)
    at C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:10977:33
    at Array.some (<anonymous>)
    at optionsHaveChanges (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:10976:64)
    at Object.compilerOptionsAffectDeclarationPath (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:16214:16)
    at createBuilderProgramState (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:100565:17)
    at Object.createBuilderProgram (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:101181:21)
    at createEmitAndSemanticDiagnosticsBuilderProgram (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:101554:19)
    at Object.host.createProgram (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:106634:20)
    at createProgram (C:\tfs\TwinCAT-HMI\TcHmiFramework\node_modules\typescript\lib\tsc.js:104850:28)
````
https://github.com/microsoft/TypeScript/blob/16156b1baf26a39ce428423f7106f3ef2b4e98bb/src/compiler/utilities.ts#L6496
Added some debug output in this js file:
````
option:  {
  name: 'outFile',
  type: 'string',
  affectsEmit: true,
  affectsMultiFileEmitBuildInfo: true,
  affectsDeclarationPath: true,
  affectsBundleEmitBuildInfo: true,
  isFilePath: true,
  paramType: {
    code: 6035,
    category: 3,
    key: 'FILE_6035',
    message: 'FILE',
    reportsUnnecessary: undefined,
    elidedInCompatabilityPyramid: undefined,
    reportsDeprecated: undefined
  },
  showInSimplifiedHelpView: true,
  category: {
    code: 6246,
    category: 3,
    key: 'Emit_6246',
    message: 'Emit',
    reportsUnnecessary: undefined,
    elidedInCompatabilityPyramid: undefined,
    reportsDeprecated: undefined
  },
  description: {
    code: 6679,
    category: 3,
    key: 'Specify_a_file_that_bundles_all_outputs_into_one_JavaScript_file_If_declaration_is_true_also_designa_6679',
    message: "Specify a file that bundles all outputs into one JavaScript file. If 'declaration' is true, also designates a file that bundles all .d.ts output.",
    reportsUnnecessary: undefined,
    elidedInCompatabilityPyramid: undefined,
    reportsDeprecated: undefined
  },
  transpileOptionValue: undefined
}  
options:  undefined
````

Changed the line to 
`return option.strictFlag ? getStrictOptionValue(options, option.name) : options?.[option.name];`
and got a working compile. 
After that the unchanged typescript compiler works again. So I suspect a problem with an old `tsconfig.tsbuildinfo`.

### PR DESCRIPTION
**Pull request by sheetalkamat**
OldCompilerOptions is set only if referencemaps are created vs not created. `Module.None` does not create reference map but other values do create it. Which is what determines if we can say copy semantic diagnostics etc..
But emit signatures are purely based on declaration path and their contents so they should only use the compilerOptions directly from old state. 

Fixes #50902

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
The fix works on my project (ported manually in JS code). 
Thanks for the quick reaction.

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -176,7 +176,7 @@ namespace ts {
         const canCopyEmitSignatures = compilerOptions.composite &&
             oldState?.emitSignatures &&
             !outFilePath &&
-            !compilerOptionsAffectDeclarationPath(compilerOptions, oldCompilerOptions!);
+            !compilerOptionsAffectDeclarationPath(compilerOptions, oldState.compilerOptions);
```
Comment (amcasey) [inline src/compiler/builder.ts:179]: I think a comment would help to explain why this one spot doesn't use `oldCompilerOptions`.  (To be honest, I couldn't figure it out from your PR description.)  It's especially disconcerting that we might be dotting into `oldState` when `useOldState` is false, so please consider explaining that as well.

Comment (sheetalkamat) [reply src/compiler/builder.ts:184]: Please check if its more clear now.

Comment (amcasey) [reply src/compiler/builder.ts:184]: It sounds like maybe `useOldState` should be renamed?  Maybe something like `useOldStateFor...`?

I'll attempt to paraphrase - please check my understanding:
We can only reuse emit signatures (i.e. .d.ts signatures) if the .d.ts file is unchanged, which will only be the case if the `declarationDir` and `outDir` options are unchanged.
We need to look in `oldState.compilerOptions`, rather than `oldCompilerOptions` (i.e. we need to disregard `useOldState`) because `oldCompilerOptions` will be undefined if the file references map indicates that the files to be emitted have changed, which isn't relevant for checking signature reuses.

Was I close?

Comment (sheetalkamat) [reply src/compiler/builder.ts:184]: We need to look in oldState.compilerOptions, rather than oldCompilerOptions (i.e. we need to disregard useOldState) it is determined by whether we create reference map to check for files to emit or not. So if say module option changes from `Module.None` to some other `Module` kind then `oldCompilerOptions` will be `undefined` but that shouldn't be taken into account when considering whether to reuse d.ts emit signature

Comment (sheetalkamat) [reply src/compiler/builder.ts:184]: > Maybe something like useOldStateFor...? 

not ideal since  `useOldStateFor` since its everything - like semantic diagnostics, files to emit, changed files and so on except d.ts emit signature

Comment (amcasey) [reply src/compiler/builder.ts:185]: That's much clearer - thanks!  For my own edification: every use case other than signature emit should still use `oldCompilerOptions`, correct?

**Review by amcasey — APPROVED** [review]
Thanks for the explanation!

**Review by andrewbranch — APPROVED** [review]

File: src/compiler/builder.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/builder.ts:185]: Yes

**Comment by HolgerJeromin** [comment]
Can/should this fix be cherrypicked to the 4.8 branch?
Looks quite safe to me and v4.9 will be released in about 8 weeks.

**Comment by sheetalkamat** [comment]
@DanielRosenwasser and @RyanCavanaugh who can decide if it would be fit for 4.8 patch
