### PR TITLE
Fix auto imports in opening JSX tag

### LINKED ISSUE #44657: Auto-imports from within jsx don't work
Auto imports inside jsx stopped working on the latest stable release - worked before.
When I try to use auto import, it show correct info about the identifier, but no way to auto import it:

screencap-Code--2021-06-11--11-00-10

However, whn I use auto import outside of jsx, it works (shows correct path and auto-imports on confirm):

screencap-Code--2021-06-11--11-01-32

Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.57.0
- OS Version: Darwin x64 19.6.0 (Catalina 10.15.7)

Steps to Reproduce:

1. Open any react component
2. Try to use auto import inside jsx

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #44657

Sometime in 4.3 I changed the completion symbol sort text and origin maps to be keyed by the symbol index in the `symbols` array instead of by symbol id (since the same symbol can sometimes be imported in different ways, thus having more than one completion entry). Missed in that refactor was the fact that JSX opening tag completions shift all the intrinsic element symbols onto the beginning of the symbols array, offsetting the indices, such that no origins or sort text were found while creating the final completion entries. Pretty weird that there was no test coverage for that.

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -1297,10 +1297,9 @@ namespace ts.Completions {
             getTypeScriptMemberSymbols();
         }
         else if (isRightOfOpenTag) {
-            const tagSymbols = typeChecker.getJsxIntrinsicTagNamesAt(location);
-            Debug.assertEachIsDefined(tagSymbols, "getJsxIntrinsicTagNames() should all be defined");
+            symbols = typeChecker.getJsxIntrinsicTagNamesAt(location);
+            Debug.assertEachIsDefined(symbols, "getJsxIntrinsicTagNames() should all be defined");
             tryGetGlobalSymbols();
-            symbols = tagSymbols.concat(symbols);
```
Comment (andrewbranch) [inline src/services/completions.ts:1303]: Here’s where all the symbols already in `symbols` got their indices shifted by `tagSymbols.length`, messing up the coordination with the maps that referenced the indices of this array.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.3

**Comment by Ghazgkull** [comment]
This PR introduced a breaking change from the 4.4 branch in a 4.3.x patch release. Upgrading to version 4.3.5, I now see this breaking change: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#using-unknown-in-catch-variables

@DanielRosenwasser Can this change please be reverted asap on the 4.3.x branch?

**Comment by andrewbranch** [comment]
This PR fixes auto imports in JSX tags and nothing else. Moreover, https://unpkg.com/typescript@4.3.5/lib/typescript.js has no reference to `useUnknownInCatchVariables`.

**Comment by Ghazgkull** [comment]
@andrewbranch I was able to consistently break/fix my TS by swapping between version 4.3.4 and 4.3.5. But I'll check again to reconfirm that I didn't do anything goofy.

**Comment by Ghazgkull** [comment]
Went back and carefully did a clean install of my modules, then tried bumping from version 4.3.4 to 4.3.5 and the problem I was seeing yesterday did *not* recur. My steps yesterday involved repeated upgrading and downgrading to different versions (e.g. 4.3.4->4.4.2->4.3.5->...) so something must have gotten messed up in that process. 🤷 Please disregard and sorry for the noise.

**Comment by andrewbranch** [comment]
No problem @Ghazgkull, thanks for confirming 😄
