### PR TITLE
Fix bug: don't call `addIndirectUser` if we're not tracking indirect users

### LINKED ISSUE #22104: Error: Debug Failure. False expression. in 'addIndirectUser' during 'occurrences'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.1
**command requested**: occurrences
**hitting sessions**: 114
**proportion of all sessions**: 0.019601100412654747
**stack**
```
Error: Debug Failure. False expression.
    at addIndirectUser (tsserver.js:69208:26)
    at handleDirectImports (tsserver.js:69173:37)
    at getImportersForExport (tsserver.js:69126:13)
    at State.importTracker (tsserver.js:69103:26)
    at State.getImportSearches (tsserver.js:69967:33)
    at searchForImportsOfExport (tsserver.js:70003:32)
    at getImportOrExportReferences (tsserver.js:70293:21)
    at getReferencesAtLocation (tsserver.js:70231:17)
    at getReferencesInContainer (tsserver.js:70186:21)
    at getReferencesInSourceFile (tsserver.js:70178:24)
    at searchForImportedSymbol (tsserver.js:70038:21)
    at getImportOrExportReferences (tsserver.js:70289:25)
    at getReferencesAtLocation (tsserver.js:70231:17)
    at getReferencesInContainer (tsserver.js:70186:21)
    at getReferencedSymbolsForSymbol (tsserver.js:69904:25)
    at Object.getReferencedSymbolsForNode (tsserver.js:69820:24)
    at Object.getReferenceEntriesForNode (tsserver.js:69660:58)
    at getSemanticDocumentHighlights (tsserver.js:68595:57)
    at Object.getDocumentHighlights (tsserver.js:68584:20)
    at getDocumentHighlights (tsserver.js:83133:42)
    at getOccurrencesAtPositionCore (tsserver.js:83136:46)
    at Object.getOccurrencesAtPosition (tsserver.js:83122:27)
    at IOSession.Session.getOccurrences (tsserver.js:89656:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89272:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes  #22104

@weswigham Is there a way we can avoid calling `addIndirectUser` on every default import -- only if it's acting like a namespace import?

### CODE REVIEW

File: tests/cases/fourslash/esModuleInteropFindAllReferences.ts [hunk 1]
```diff
@@ -6,7 +8,7 @@
 ////}
 
 // @Filename: /b.ts
-////import * as a from "a";
```
Comment (andy-ms) [inline tests/cases/fourslash/esModuleInteropFindAllReferences.ts]: Changed this to be testing what #21703 fixed.

Comment (weswigham) [reply tests/cases/fourslash/esModuleInteropFindAllReferences.ts]: Heh. I had this open in multiple editors with both versions in each to directly compare where their execution differed. I did not notice that the wrong version had been saved 🐈 Thanks.
