### PR TITLE
Fix 53482 : Preserve newline/space behavior

### LINKED ISSUE #53482: Extract refactors break single-line `if` statements into two lines
# Bug Report

### 🔎 Search Terms

extract function single-line if

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about whether Tang was really invented by NASA

### 💻 Code

```ts
function f() {
  return [].filter(x => {
    if (!x) return false;
  });
}
```

### 🙁 Actual behavior

Select the arrow function callback of `filter` and run “Extract to inner function.” The formatting of the function contents should be the same in the extracted function.

### 🙂 Expected behavior

```typescript
function newFunction(): (value: any, index: number, array: any[]) => unknown {
  return x => {
    if (!x)
      return false; // New line added
  };
}
```

### PR DESCRIPTION
**Pull request by iinicole**
Fixes #53482

### CODE REVIEW

**Comment by iinicole** [comment]
@microsoft-github-policy-service agree

**Comment by iinicole** [comment]
> @iinicole please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -4866,20 +4867,27 @@ export function createPrinter(printerOptions: PrinterOptions = {}, handlers: Pri
...
+                    pipelineEmit(EmitHint.EmbeddedStatement, node);
+                }
+                else {
+                    emit(node);
+                }
+                decreaseIndent();
             }
             else {
+                writeSpace();
                 emit(node);
```
Comment (iinicole) [inline src/compiler/emitter.ts:4889]: Instead of changing only the behavior for `if` only, I found that `if, else, do, while, for, forin, forof, with` all calls `emitEmbeddedStatement` and thus should all so have the behavior of preserving newlines/spaces. Thus, changing the general behavior here.

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -4866,20 +4867,27 @@ export function createPrinter(printerOptions: PrinterOptions = {}, handlers: Pri
     }
 
     function emitEmbeddedStatement(parent: Node, node: Statement) {
-        if (isBlock(node) || getEmitFlags(parent) & EmitFlags.SingleLine) {
+        const lines = getLeadingLineTerminatorCount(parent, node, ListFormat.None);
```
Comment (iinicole) [inline src/compiler/emitter.ts:4870]: I use getLeadingLineTerminatorCount to determine if there is any lines/space between the first node and its parent node under the condition that `preserveSourceNewlines` is `true`.

File: src/compiler/emitter.ts [hunk 3]
```diff
@@ -862,6 +862,7 @@ export function emitFiles(resolver: EmitResolver, host: EmitHost, targetSourceFi
             inlineSources: compilerOptions.inlineSources,
             extendedDiagnostics: compilerOptions.extendedDiagnostics,
             writeBundleFileInfo: !!bundleBuildInfo,
+            preserveSourceNewlines: true,
```
Comment (iinicole) [inline src/compiler/emitter.ts:865]: I notice that `preserveSourceNewlines` is not set here would lead to not being able to use `getLeadingLineTerminatorCount` to get the accurate line number in the below and thus setting it here. Also, I am think that this might be the desired behavior to preserve such behaviors over all files.

**Comment by iinicole** [comment]
@andrewbranch Hi! Could you please help review my pull request? I might also need some help in determining whether my changes provide the current behavior and modifying the old test cases to fit such behaviors. Thanks!

File: src/compiler/emitter.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/emitter.ts:865]: `preserveSourceNewlines` is true for the printer that runs refactors, which is what we’re trying to fix. This applies to `tsc` emit, and while it might be nice if it preserved input spacing, it’s too much of a performance hit. This change should be undone, and your test should be one like [this](https://github.com/microsoft/TypeScript/pull/39280/files#diff-69327758976e35d29a55b6d986ca09c9a28f074e982f07d0495051e3cb190d05) not a conformance test. When you debug a test like that, you’ll find that `preserveSourceNewlines` is already true for you. In general, be careful not to change the emitter’s behavior when `preserveSourceNewlines` is _not_ `true`.

Comment (DanielRosenwasser) [reply src/compiler/emitter.ts:865]: See also #37814

**Comment by iinicole** [comment]
@andrewbranch Thanks for your advice! I have changed my code accordingly. Let me know if I got the idea correct this time.

**Comment by andrewbranch** [comment]
@iinicole this looks great! Let’s just run the perf and language server tests:

@typescript-bot perf test this
@typescript-bot test tsserver top100

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
Thanks @iinicole!
