### PR TITLE
Handle linebreaks consistently in code fixes and refactorings

### LINKED ISSUE #18291: Duplicate specification of `newLineCharacter` in RefactorContext
**TypeScript Version:**  master

**Code**

In `convertFunctionToEs6Class.ts`:

```ts
context.rulesProvider.getFormatOptions().newLineCharacter;
```

`RefactorContext` already specifies a `newLineCharacter` direct property; it looks like there are two ways of specifying this that might conflict. @RyanCavanaugh

### LINKED ISSUE #18445: Code fixes adding carriage returns to LF documents
Code fixes are generating files with mixed LF and CRLF line endings. See:
* `codeFixAddMissingMember5`
* `codeFixAddMissingMember7`
* `codeFixSuperAfterThis`
* `codeFixSuperCall`
* `importNameCodeFix*` (see comment in `fourslash.ts` tagged `GH#18445`)

### PR DESCRIPTION
**Pull request by amcasey**
Don't store it on the context; do look in the `EditorSettings` before falling back on the `LanguageServiceHost`.

There's probably a bunch of renaming to do before this goes in.

NOTE: The code change is in the first commit.

Fixes #18291
Fixes #18445

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -1887,23 +1887,21 @@ namespace ts {
...
-                return codefix.getFixes({ errorCode, sourceFile, span, program, newLineCharacter, host, cancellationToken, formatContext });
+                return codefix.getFixes({ errorCode, sourceFile, span, program, host, cancellationToken, formatContext });
             });
         }
 
         function getCombinedCodeFix(scope: CombinedCodeFixScope, fixId: {}, formatOptions: FormatCodeSettings): CombinedCodeActions {
             synchronizeHostData();
             Debug.assert(scope.type === "file");
             const sourceFile = getValidSourceFile(scope.fileName);
-            const newLineCharacter = getNewLineOrDefaultFromHost(host);
```
Comment (mhegazy) [inline src/services/services.ts]: we should mark this function as deprecated, and replace all its uses as well.

Comment (amcasey) [reply src/services/services.ts]: It appears to be internal.  Can we just delete it?

Comment (amcasey) [reply src/services/services.ts]: Actually, the remaining callers look pretty legitimate.  Is there another method they should call instead?

**Comment by amcasey** [comment]
Name suggestions for `RefactorOrCodeFixContext` are welcome since it doesn't really relate to either and doesn't cover their intersection.  I was thinking of something along the lines of `LazyTextChangesContext`, but I thought that might be confusing.

**Comment by amcasey** [comment]
I'm also hoping there's a more idiomatic way to express the conversion from `RefactorOrCodeFixContext` to `TextChangesContext`.

File: src/services/services.ts (hunk 1 above)
Comment (mhegazy) [reply src/services/services.ts]: removign it should be fine then.

File: tests/cases/fourslash/completionsImport_require.ts [hunk 2]
```diff
@@ -24,8 +24,8 @@ verify.applyCodeActionFromCompletion("b", {
     source: "/a",
     description: `Import 'foo' from module "./a"`,
     // TODO: GH#18445
```
Comment (andy-ms) [inline tests/cases/fourslash/completionsImport_require.ts]: Could you remove the TODOs too?

File: src/services/refactorProvider.ts [hunk 3]
```diff
@@ -14,12 +14,28 @@ namespace ts {
...
 
-    export interface RefactorContext extends textChanges.TextChangesContext {
+    export interface RefactorOrCodeFixContext {
+        host: LanguageServiceHost;
+        formatContext: ts.formatting.FormatContext;
+    }
+
+    export function getNewLineFromContext(context: RefactorOrCodeFixContext) {
+        const formatSettings = context.formatContext.options;
+        return formatSettings ? formatSettings.newLineCharacter : context.host.getNewLine();
```
Comment (andy-ms) [inline src/services/refactorProvider.ts]: The `newLineCharacter` property is declared optional, so this should return `context.host.getNewLine()` if that's undefined.
Although it looks like `getNewLine()` is also optional -- see `getNewLineOrDefaultFromHost`.

File: src/services/refactors/annotateWithTypeFromJSDoc.ts [hunk 4]
```diff
@@ -78,7 +78,7 @@ namespace ts.refactor.annotateWithTypeFromJSDoc {
             return Debug.fail(`!decl || !jsdocType || decl.type: !${decl} || !${jsdocType} || ${decl.type}`);
         }
 
-        const changeTracker = textChanges.ChangeTracker.fromContext(context);
+        const changeTracker = textChanges.ChangeTracker.fromContext(toTextChangesContext(context));
```
Comment (andy-ms) [inline src/services/refactors/annotateWithTypeFromJSDoc.ts]: It looks like every call to `fromContext` calls `toTextChangesContext` first -- would be easier to just do that in `fromContext`, and probably inline `toTextChangesContext`.

File: src/services/services.ts (hunk 1 above)
Comment (amcasey) [reply src/services/services.ts]: I'm confused.  This method appears to have callers.  Why are we deprecating/removing it?

**Comment by amcasey** [comment]
Straight rebase to resolve conflicts.  Will address comments in subsequent commits.

File: tests/cases/fourslash/completionsImport_require.ts (hunk 2 above)
Comment (amcasey) [reply tests/cases/fourslash/completionsImport_require.ts]: Done

File: src/services/refactorProvider.ts (hunk 3 above)
Comment (amcasey) [reply src/services/refactorProvider.ts]: Updated

File: src/services/refactors/annotateWithTypeFromJSDoc.ts (hunk 4 above)
Comment (amcasey) [reply src/services/refactors/annotateWithTypeFromJSDoc.ts]: Great idea!

File: src/services/codefixes/importFixes.ts [hunk 5]
```diff
@@ -24,16 +24,14 @@ namespace ts.codefix {
         moduleSpecifier?: string;
     }
 
-    interface SymbolContext extends textChanges.TextChangesContext {
+    interface SymbolContext {
         sourceFile: SourceFile;
         symbolName: string;
+        formatContext: ts.formatting.FormatContext;
```
Comment (andy-ms) [inline src/services/codefixes/importFixes.ts]: Looks like this could be moved to `ImportCodeFixContext`.

Comment (amcasey) [reply src/services/codefixes/importFixes.ts]: It looks like every consumer of `SymbolContext` ands it with `TextChangesContext` anyway, so I'll just make it a subtype.

Comment (amcasey) [reply src/services/codefixes/importFixes.ts]: Do you know why `SymbolContext` exists?  Is it to prevent certain functions from accessing certain members of `ImportCodeFixContext`?

Comment (andy-ms) [reply src/services/codefixes/importFixes.ts]: It's just there to indicate that we don't need everything from `ImportCodeFixContext`.

Comment (amcasey) [reply src/services/codefixes/importFixes.ts]: That seems excessive to me, but not worth changing at the moment.

File: src/services/services.ts (hunk 1 above)
Comment (mhegazy) [reply src/services/services.ts]: looking at this again, seems like in every call to this method, we have an insufficient public API. for instance, in `getDocCommentTemplateAtPosition`, seems like the public API should take a `FormatCodeSettings` just like `getCodeFixesAtPosition` does. 
I do not think this is related to this PR per se, but this is something that we should fix for the long term. unfortunately we can not remove the `getNewLineOrDefaultFromHost` as you noted without breaking our public API, but we should add optional `FormatCodeSettings` in places where we use it to allow the host to override the value.

Comment (amcasey) [reply src/services/services.ts]: @mhegazy Can you please confirm that the latest commit (https://github.com/Microsoft/TypeScript/pull/21158/commits/d97dec85749ce886fcafb9d93082525206b40ec1) is what you had in mind (not counting a bug about reviewing callers of `getNewLineOrDefaultFromHost`)?

Comment (mhegazy) [reply src/services/services.ts]: 👍

Comment (amcasey) [reply src/services/services.ts]: Thanks!  Filed https://github.com/Microsoft/TypeScript/issues/21289.
