### PR TITLE
fix(51202): Circular instantiation expression crashing IDEs

### LINKED ISSUE #51202: Circular instantiation expression crashing IDEs
# Bug Report

### 🔎 Search Terms

instantiation expressions, circular, IntelliSense, quickinfo, crash

### 🕗 Version & Regression Information

- This is a crash (in IntelliSense in editors anyway)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVAPgAoMAueEgSlowE8AHEHRA48gbgChEhCgCIR9XkA)

### 💻 Code

```ts
declare function foo<T>(t: T): typeof foo<T>;
foo("");
```

### 🙁 Actual behavior

Hovering over the call to `foo()` gives "too much recursion" errors in the TS Language server.  Looks like a loop in 
* `signatureToSignatureDeclarationHelper`
* `createTypeNodeFromObjectType`
* `createAnonymousTypeNode`
* `typeToTypeNodeWorker`
* `typeToTypeNodeHelper`
* `serializeReturnTypeForSignature`
* `signatureToSignatureDeclarationHelper`

<details><summary>call stack</summary>

```
    Maximum call stack size exceeded

    RangeError: Maximum call stack size exceeded
        at process.hrtime (node:internal/process/per_thread:79:16)
        at Performance.now (node:internal/perf/utils:14:22)
        at ts.timestamp (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:3634:79)
        at ThrottledCancellationToken.isCancellationRequested (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166867:27)
        at CancellationTokenObject.isCancellationRequested (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166844:43)
        at CancellationTokenObject.throwIfCancellationRequested (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:166847:22)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53001:39)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeTypeForDeclaration (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54543:30)
        at symbolToParameterDeclaration (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53970:41)
        at c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53881:274
        at Array.map (<anonymous>)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53881:240)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
        at typeToTypeNodeHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:52995:32)
        at serializeReturnTypeForSignature (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:54571:24)
        at signatureToSignatureDeclarationHelper (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53901:42)
        at createTypeNodeFromObjectType (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53457:49)
        at createAnonymousTypeNode (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53359:32)
        at typeToTypeNodeWorker (c:\Users\jcalz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:53204:28)
```

</details>

### 🙂 Expected behavior

Maybe a circularity warning, but definitely no crash

This came up when trying to look at the code in [a Stack Overflow question](https://stackoverflow.com/q/74099263/2887218) and wondering why the IDE was acting so strange.

### LINKED ISSUE #52757: Compiler crash on some functions with self-referential types
# Bug Report

### 🔎 Search Terms

"Maximum call stack size exceeded". There are many issues referencing this, but most seem like different bugs from this, and I don't see any that have a simple repro like I provide here.

### 🕗 Version & Regression Information

I tested in these versions:

* Untestable in 4.6.4 and earlier (the repro code causes a syntax error)
* Fails in 4.7.4.
* Fails in 4.8.4.
* **Fails in 4.9.5 (current release as of this report)**
* **Fails in 5.0.0-dev.20230214 (current "next" as of this report)**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/GYVwdgxgLglg9mABMAPAFQHwAoCGAnAcwGcAuRKATwAcBTOYZdDAShLUQG9E8aoQ8k+YgG5EAXyA) Load it up, hit "Run", then look at your browser's dev console to see that the compiler blew the stack.

### 💻 Code

```ts
function f<T>(args: typeof f<T>):T { return args; }
```

### 🙁 Actual behavior

The compiler itself throws `RangeError: Maximum call stack size exceeded`. E.g.:

```text
$ cat temp.ts
function f<T>(args: typeof f<T>):T { return args; }
$ npx tsc temp.ts
/Users/grb/proj/execprog/node_modules/typescript/lib/tsc.js:99612
                throw e;
                ^

RangeError: Maximum call stack size exceeded
```

### 🙂 Expected behavior

The code either compiles or gives a type error.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51202
Fixes #52757

### CODE REVIEW

File: tests/cases/compiler/circularInstantiationExpression.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+declare function foo<T>(t: T): typeof foo<T>;
```
Comment (DanielRosenwasser) [inline tests/cases/compiler/circularInstantiationExpression.ts:1]:
```suggestion
// @declaration: true

declare function foo<T>(t: T): typeof foo<T>;
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5481,6 +5481,12 @@ namespace ts {
                         }
                     }
                     else {
+                        if (getObjectFlags(type) & ObjectFlags.InstantiationExpressionType) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:5484]: I think having a fallback like this is good; still, I wonder if there's any way you can also special-case the logic here for `typeof`.

```ts
const isInstantiationExpression = !!(symbol.flags & SymbolFlags.Function && getObjectFlags(type) & ObjectFlags.InstantiationExpressionType);
const instantiationExpressionType = type as InstantiationExpressionType;
if (isTypeQueryNode(instantiationExpressionType.node)) {
    // deep clone the type query node
}
```

Comment (a-tarasyuk) [reply src/compiler/checker.ts:5484]: Is ok to emit 

```
foo("");
>foo("") : typeof foo<T>
>foo : <T>(t: T) => typeof foo<T>
```

instead of 

```
foo("");
>foo("") : (t: string) => any
>foo : <T>(t: T) => (t: T) => any
>"" : ""
```
?

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:5484]: Personally, I think so - other reviewers might have other thoughts.

Comment (a-tarasyuk) [reply src/compiler/checker.ts:5484]: Oke

**Review by DanielRosenwasser — APPROVED** [review]
I think at least 1-2 more people should take a look.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -5690,6 +5690,17 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                     }
                 }
                 else {
+                    const isInstantiationExpressionType = !!(getObjectFlags(type) & ObjectFlags.InstantiationExpressionType);
+                    if (isInstantiationExpressionType) {
+                        const instantiationExpressionType = type as InstantiationExpressionType;
+                        if (isTypeQueryNode(instantiationExpressionType.node)) {
+                            return factory.cloneNode(instantiationExpressionType.node);
```
Comment (weswigham) [inline src/compiler/checker.ts:5697]: Use `serializeExistingTypeNode` here. Specifically, we may need to do things like remap jsdoc syntax into TS syntax in the subtree (type arguments), fixup module specifiers in import types for the new context, or track if the symbol referenced by a query is still visible within the new context.

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts:5697]: (Specifically, you should probably do checks similar to what occur in `serializeTypeForDeclaration` to see if this type node is safe to reuse)

Comment (a-tarasyuk) [reply src/compiler/checker.ts:5697]: Do you mean the following checks?

```ts
if (!isErrorType(type) && enclosingDeclaration) {
    const declWithExistingAnnotation = getDeclarationWithTypeAnnotation(symbol, enclosingDeclaration);
    if (declWithExistingAnnotation && !isFunctionLikeDeclaration(declWithExistingAnnotation) && !isGetAccessorDeclaration(declWithExistingAnnotation)) {
        // try to reuse the existing annotation
        const existing = getEffectiveTypeAnnotationNode(declWithExistingAnnotation) !;
        if (typeNodeIsEquivalentToType(existing, declWithExistingAnnotation, type) && existingTypeNodeIsNotReferenceOrIsReferenceWithCompatibleTypeArgumentCount(existing, type)) {
            const result = serializeExistingTypeNode(context, existing, includePrivateSymbol, bundled);
            if (result) {
                return result;
            }
        }
    }
}
```

File: tests/cases/compiler/selfReferentialFunctionType.ts [hunk 4]
```diff
@@ -0,0 +1,8 @@
+// @strict: true
+// @declaration: true
+
+function f<T>(args: typeof f<T>): T { return args; }
+
+function g<T = typeof g>(args: T): T { return args; }
+
+function h<T>(): typeof h<T> { return h; }
```
Comment (jakebailey) [inline tests/cases/compiler/selfReferentialFunctionType.ts:8]: I know I wrote these tests, but on second thought, it's probably wiser to write
```suggestion
declare function f<T>(args: typeof f<T>): T;

declare function g<T = typeof g>(args: T): T;

declare function h<T>(): typeof h<T>;
```

And then they'll be error-free.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
@weswigham Do you have any other feedback for this one? (I had a different fix for this via a duplicate bug, but this one seems better and it looks okay to me.)

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
Everything is clean; not surprising of course given it was previously a crash, though I was somewhat expecting to see the result of this PR allowing us to write more typeofs in the output.

**Review by weswigham — APPROVED** [review]
