### PR TITLE
Mark references to dynamically-named properties as used

### LINKED ISSUE #20929: Computed property is firing warning on private members
**TypeScript Version:**  2.7.0-dev.20171226

**Code**

```ts
const foo = Symbol.for("foo");
const baz = Symbol.for("baz");

export class Bar
{
    private [foo]: string;
          // ^^^ '__computed' is declared but its value is never read.
    public  [baz]: string; // OK

    public constructor()
    {
        this[foo] = "foo";
        let foo$ = this[foo];
        foo$.toString();
    }
}
```

**Expected behavior:**
No warnings
**Actual behavior:**
Incorrect warnings

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20929
Uncovered #21009

### CODE REVIEW

**Comment by andy-ms** [comment]
Added a partial fix to #21009 to keep the test deterministic -- there are probably more locations that need to be changed though.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21223,8 +21224,9 @@ namespace ts {
                 if (node.members) {
                     for (const member of node.members) {
                         if (member.kind === SyntaxKind.MethodDeclaration || member.kind === SyntaxKind.PropertyDeclaration) {
-                            if (!member.symbol.isReferenced && hasModifier(member, ModifierFlags.Private)) {
-                                error(member.name, Diagnostics._0_is_declared_but_its_value_is_never_read, symbolName(member.symbol));
+                            const symbol = getSymbolOfNode(member);
+                            if (!symbol.isReferenced && hasModifier(member, ModifierFlags.Private)) {
+                                error(member.name, Diagnostics._0_is_declared_but_its_value_is_never_read, showSymbol(symbol));
```
Comment (mhegazy) [inline src/compiler/checker.ts]: why not just `symbolToString(symbol)`?
