### PR TITLE
Index signatures for symbols and template literal strings

### LINKED ISSUE #1863: Allow indexing with symbols
TypeScript now has a ES6 target mode which includes definitions `Symbol`. However when trying to index an object with a symbol, I get an error (An index expression argument must be of type 'string', 'number', or 'any').

``` javascript
var theAnswer = Symbol('secret');
var obj = {};
obj[theAnswer] = 42; // Currently error, but should be allowed
```

### LINKED ISSUE #26470: Intuitive != expected != actual behaviour when combining string and symbol keys
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:** string index inference, string key inference

**Code**

```ts
// function foo takes an 'options' object that can have:
// (a) any number of string keys whose values are unary functions
// (b) an optional 'directive' unique symbol key with a unrelated type
const directive = Symbol('directive');
declare function foo<TArg, TRet, TDir>(options:
    {[x in string]: (arg: TArg) => TRet}    // all the string keys are unary functions
    & {[directive]?: TDir}                  // there is an optional 'directive' symbol key
): void;

// CASE 1
// ~~~ERROR~~~ - ... prop 'addOne' incompatible with index signature
//               ... 'x' and 'arg' are incompatible
//               ... 'string' not assignable to 'number'
let case1 = foo({
    [directive]: (x: string) => 'str',
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
});

// CASE 2: identical to case 1 except for order of properties
// Compiles OK - infers TArg = number, TRet = number, TDir = (x: string) => string
let case2 = foo({
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
    [directive]: (x: string) => 'str',
});

// CASE 3: identical to case 1 except for type of directive
// Compiles OK - infers TArg = number, TRet = number, TDir = string
let case3 = foo({
    [directive]: 'str',
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
});
```

**Intuitive expected behaviour:**

All three cases compile without errors, with the string and symbol keys typed separately, since the type declaration clearly distinguishes the string keys from the symbol one.

**Expected behavior according to https://github.com/Microsoft/TypeScript/issues/26257#issuecomment-411896593:**

That comment suggests that all three cases should fail to compile, since the string index signature covers all symbol keys too, so any symbol key would have to conform to the string index signature, and they don't conform in any of the three cases in the code above.

**Actual behavior:**

Case 1 fails to compile, but Case 2 and 3 compile fine and in fact do type the string and symbol keys separately as intended by `foo`'s definition.

**Playground Link:** [here](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20function%20foo%20takes%20an%20'options'%20object%20that%20can%20have%3A%0D%0A%2F%2F%20(a)%20any%20number%20of%20string%20keys%20whose%20values%20are%20unary%20functions%0D%0A%2F%2F%20(b)%20an%20optional%20'directive'%20unique%20symbol%20key%20with%20a%20unrelated%20type%0D%0Aconst%20directive%20%3D%20Symbol('directive')%3B%0D%0Adeclare%20function%20foo%3CTArg%2C%20TRet%2C%20TDir%3E(options%3A%0D%0A%20%20%20%20%7B%5Bx%20in%20string%5D%3A%20(arg%3A%20TArg)%20%3D%3E%20TRet%7D%20%20%20%20%2F%2F%20all%20the%20string%20keys%20are%20unary%20functions%0D%0A%20%20%20%20%26%20%7B%5Bdirective%5D%3F%3A%20TDir%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20there%20is%20an%20optional%20'directive'%20symbol%20key%0D%0A)%3A%20void%3B%0D%0A%0D%0A%2F%2F%20CASE%201%0D%0A%2F%2F%20~~~ERROR~~~%20-%20...%20prop%20'addOne'%20incompatible%20with%20index%20signature%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20'x'%20and%20'arg'%20are%20incompatible%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20'string'%20not%20assignable%20to%20'number'%0D%0Alet%20case1%20%3D%20foo(%7B%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20CASE%202%3A%20identical%20to%20case%201%20except%20for%20order%20of%20properties%0D%0A%2F%2F%20Compiles%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20(x%3A%20string)%20%3D%3E%20string%0D%0Alet%20case2%20%3D%20foo(%7B%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%0D%0A%7D)%3B%0D%0A%0D%0A%0D%0A%2F%2F%20CASE%203%3A%20identical%20to%20case%201%20except%20for%20type%20of%20directive%0D%0A%2F%2F%20Compiles%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20string%0D%0Alet%20case3%20%3D%20foo(%7B%0D%0A%20%20%20%20%5Bdirective%5D%3A%20'str'%2C%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A)

**Related Issues:**
Taken directly from https://github.com/Microsoft/TypeScript/issues/26257#issuecomment-411957368. But the issue containing that comment is marked as 'working as intended' so I thought it would be better to open a new issue for this specific case.

### LINKED ISSUE #42192: Template literal types fail in mapped types
TypeScript Version: 4.1.3

Search Terms: template literal types

```
type Pseudo = `&:${string}` 

const AmIPseudo1: Pseudo = '&:test' // Passes as expected
const AmIPseudo: Pseudo = '&' // Fails as expected

type PseudoDeclaration = {
    [key in Pseudo]: string
}

// No Errors
const test: PseudoDeclaration = {
    'someKey' : 'someValue'
}

```

**Expected behavior:**

`test` should not be able to pass the type-checking as its key 'someKey' is not of type `Pseudo`.

**Actual behavior:**

`test` passes the type-checking.

### LINKED ISSUE #44675: Object Indexing with a Template String
# Bug Report

### 🔎 Search Terms

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZuKBlAlgLwKYRgXhgbwCgYYALARgC4YBWABgBpiyAmagFhqZNIGYPGzUu2q8uQmqME8AbNRbiAvoUJQAngAcMMAAoAnEBux4iJADYYAbhjPVyMAD4wWjmL1ftXNVzIDchZUJQSFgAcwwoADFEVExovQAJDABDABMMPVwYAAp8GAtrMxhFan1DCABKXAA+eBj0LABtAANSABJ8AptFZoBdfyDwCBALADozEFDsgHIAFSwoaYYYcKj6uJBElPS9XPyrGztiiorfIA)

### 💻 Code

```ts
const fontSizes = {
  h1: 50,
  h2: 45,
  h3: 40,
  h4: 35,
  h5: 30,
  h6: 25,
}

type Props = {
  level: 1 | 2 | 3 | 4 | 5 | 6;
}

const getFontSizeForHeader = ({ level }: Props) => fontSizes[`h${level}`]; // error

console.log('Test', getFontSizeForHeader({ level: 1 }));
```

### 🙁 Actual behavior

When indexing an object with a template string, the template string is typed just as `string` instead of the proper union, causing an error and requiring a type cast or ts-ignore to rid.

### 🙂 Expected behavior

The template string typing to be used to check for valid indexing

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we implement support for symbol and template literal string index signatures. We furthermore permit index signature declarations to specify union key types, provided all constituents are either `string`, `number`, `symbol`, or template literal types with non-generic placeholders. Some examples:

```ts
type SymbolMap<T> = {
    [key: symbol]: T;
};

type DataProps = {
    [key: `data-${string}`]: string;
};

type PropertyMap = {
    [key: string | number | symbol]: string;
};
```

An index signature declaration that specifies a union key type is exactly equivalent to a set of distinct index signatures for each constituent key. For example, the `PropertyMap` declaration above is exactly equivalent to:

```ts
type PropertyMap = {
    [key: string]: string;
    [key: number]: string;
    [key: symbol]: string;
};
```

Index signature declarations are not permitted to specify literal key types or generic key types. Those kinds of types can only be used with mapped types, which map literals key types to distinct properties and defer resolution of generic key types until they're instantiated with non-generic types. For example:

```ts
type Thing<T> = Record<'a' | `foo${T}` | symbol, string>;

type StringThing = Thing<string>;  // { [a: string, [x: `foo${string}`]: string, [x: symbol]: string }
type BarThing = Thing<'bar'>;  // { [a: string, foobar: string, [x: symbol]: string }
```

This PR supercedes #26797 which was more ambitious but had overlap between regular properties and index signatures with literal key types that is difficult to reconcile, as well as generic index signatures for which type relationships become exceedingly complex to reason about.

Fixes #1863.
Fixes #26470.
Fixes #42192.
Fixes #44675.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12019,47 +11982,99 @@ namespace ts {
...
+                    }
+                    else {
+                        (applicableInfos || (applicableInfos = [applicableInfo])).push(info);
+                    }
+                }
+            }
+            // When more than one index signature is applicable we create a synthetic IndexInfo. Instead of computing
+            // the intersected key type, we just use unknownType for the key type as nothing actually depends on the
+            // keyType property of the returned IndexInfo.
+            return applicableInfos ? createIndexInfo(unknownType, getIntersectionType(map(applicableInfos, info => info.type)),
```
Comment (weswigham) [inline src/compiler/checker.ts:12010]: `unknown` isn't assignable to `string | number | symbol` - maybe it'd be better to use `any` here on the offchance it leaks somewhere in the future?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -12019,47 +11982,99 @@ namespace ts {
...
+            }
+            return stringIndexInfo;
+        }
+
+        function isApplicableIndexType(source: Type, target: Type) {
+            // A 'string' index signature applies to types assignable to 'string' or 'number', and a 'number' index
+            // signature applies to types assignable to 'number' and numeric string literal types.
+            return isTypeAssignableTo(source, target) ||
+                target === stringType && isTypeAssignableTo(source, numberType) ||
+                target === numberType && source.flags & TypeFlags.StringLiteral && isNumericLiteralName((source as StringLiteralType).value);
```
Comment (weswigham) [inline src/compiler/checker.ts:12041]: There's also the type
```ts
type NumericStrings = `${number}`
```
which might warrant special-casing here, as well? It's a bit awkward because `"0.0"` is a "numeric string" but is actually a distinct object key string from `"0"`; but that's already true for the literals themselves, so.... ¯\\_(ツ)_/¯

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -41246,23 +41181,12 @@ namespace ts {
...
-                    return grammarErrorOnNode(parameter.name,
-                        Diagnostics.An_index_signature_parameter_type_cannot_be_a_union_type_Consider_using_a_mapped_object_type_instead);
-                }
-
-                return grammarErrorOnNode(parameter.name, Diagnostics.An_index_signature_parameter_type_must_be_either_string_or_number);
+            const type = getTypeFromTypeNode(parameter.type);
+            if (someType(type, t => !!(t.flags & (TypeFlags.StringOrNumberLiteralOrUnique | TypeFlags.Instantiable)) && !isPatternLiteralType(t))) {
+                return grammarErrorOnNode(parameter.name, Diagnostics.An_index_signature_parameter_type_cannot_be_a_literal_type_or_generic_type_Consider_using_a_mapped_object_type_instead);
+            }
+            if (!everyType(type, t => !!(t.flags & (TypeFlags.String | TypeFlags.Number | TypeFlags.ESSymbol | TypeFlags.TemplateLiteral)))) {
```
Comment (weswigham) [inline src/compiler/checker.ts:41188]: `TypeFlags.StringMapping`?

**Review by weswigham — COMMENTED** [review]
Shouldn't we allow `any` and `never` as index signature key types as well? They're both non-generic intrinsics assignable to `string | number | symbol`, so I don't see why not. `any` is _essentially_ just a short `string | number | symbol`, while `never` would be an index signature that either
* Doesn't actually exist and is immediately removed (which... isn't too useful?), or
* Is an index signature that only handles `never` lookups, eg `{[idx: never]: never; [idx: string]: string}[never]` would be `never` and not `string` (which probably has use for defining error fallbacks for lookup types).

**Comment by DanielRosenwasser** [comment]
> Shouldn't we allow `any` and `never` as index signature key types as well?

My understanding from the last design meeting was that we were limiting the new types of index signatures to match the biggest use-cases that we had, keeping room to generalize for unions, finite types, `any`, `unknown`, `never`, and enum types.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:12010]: To ensure property round-tripping, our guiding principle should be what happens when you feed a particular type through a mapped type. Currently, feeding an `any` through a mapped type produces a `string` index signature. That used to make sense because it was the widest possible index signature, but you could argue we should equate `any` to `string | number | symbol` and have it be shorthand for all three index signatures. That may or may not affect existing code, but we could try.

Comment (ahejlsberg) [reply src/compiler/checker.ts:12010]: Oops, comment above was meant for your general question about `any` and `never`.

Comment (ahejlsberg) [reply src/compiler/checker.ts:12010]: Meanwhile, sure it might be better to use `any` for the key type for synthetic index infos.

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:12041]: I'm not sure there's any meaningful special casing we could do for `` `${number}` `` because, as you already point out, it may or may not contain a round-trippable numeric string.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:12010]: > but you could argue we should equate any to string | number | symbol and have it be shorthand for all three index signatures. That may or may not affect existing code, but we could try.

Yeah, it makes sense, imo, for a mapped type over `any` to make an `any` index signature, since that'll actually handle `symbol`s. (Just like the `any` input could have)

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:41188]: Nope, `TypeFlags.StringMapping` is an instantiable type and it was already barred by the test above.

Comment (weswigham) [reply src/compiler/checker.ts:41188]: Hm, on inspection,

```ts
type A = Uppercase<`${number}`>;
```

Is just

```ts
type A = `${number}`;
```

so they just evaporate around patterns (after affecting the concrete bits, even though, conceptually, they should represent a different, smaller, set of strings in the holes), so I guess we don't need to handle them right now. But if we ever change up mappings over/in patterns to be preserved, we'll need to change this to match, I guess.

**Comment by ahejlsberg** [comment]
> I'm actually surprised to see unions supported in index signatures in this PR.

Unions per se are not the problem as they can trivially be expanded to individual index signatures for each constituent. (Might as well have the convenience of writing `[key: string | number | symbol]: xxx` instead of requiring three distinct declarations.) The trouble comes from (unions of) literal types and generic types as they do *not* become index signatures when fed through mapped types. Those are the ones we need to prohibit.

File: tests/baselines/reference/indexSignatures1.js [hunk 4]
```diff
@@ -0,0 +1,318 @@
...
+    y = x;
+}
+
+// Intersection of multiple applicable index signatures
+
+declare let combo: { [x: `foo-${string}`]: 'a' | 'b' } & { [x: `${string}-bar`]: 'b' | 'c' };
+const x1 = combo['foo-test'];  // 'a' | 'b'
+const x2 = combo['test-bar'];  // 'b' | 'c'
+const x3 = combo['foo-test-bar'];  // 'b' (('a' | 'b') & ('b' | 'c'))
+
```
Comment (weswigham) [inline tests/baselines/reference/indexSignatures1.js:32]: Can we also add a test for
```ts
declare var str: string;
const x4 = combo[`foo-${str}-bar`];
```
? Mostly because element access locations aren't literal locations, per sey, in `main` right now (and that was a change I had to make in my PR).
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [inline src/compiler/checker.ts:12010]: Oh, one other LS-related question this reminds me of (since the composite doesn't preserve declarations in the index info) - when you have

```ts
type A = {[idx: `foo${string}`]: {x: any}} & {[idx: `${string}bar`]: {y: any}}
declare var x: A;
const q1 = x.foobar/**/;
```
and you go-to-def on `foobar`, do we return both index signatures as the definition locations?

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
One thing that's odd is

```ts
type Foo = {
    [x: string | number]: string;
}
```

desugars to

```ts
type Foo = {
    [x: string]: string;
    [x: number]: string;
}
```

even though that's functionally the same as

```ts
type Foo = {
    [x: string]: string;
}
```

right?

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Yes, that is a bit odd, but it's consistent with what happens if you feed `string | number` through a mapped type. For example, `Record<string | number, string>` produces a type with both index signatures.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:41188]: Yeah, we're good there for now. However, it *does* appear we don't properly apply the string mapping to template literal types with non-generic patterns. For example, `` Uppercase<`foo${string}bar`> `` should become `` `FOO${string}BAR` ``, but simply resolves to `` `foo${string}bar` `` now. It's unrelated to this PR, but something we should fix.

**Comment by c69-addepar** [comment]
> We furthermore permit index signature declarations to specify union key types, provided all constituents are either string, number, symbol, or template literal types with non-generic placeholders

are literal string unions allowed inside the template string types ? eg:

```typescript
type CoordinateProps = {
    [key: `${'x'|'y'|'z'}`]: number;
};
```

**Comment by ahejlsberg** [comment]
> are literal string unions allowed inside the template string types

No, the type `` `${'x'|'y'|'z'}` `` is equivalent to `'x' | 'y' | 'z'`, which isn't permitted. But you can of course use `Record<'x' | 'y' | 'z', number>`, which resolves to three distinct properties.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by somysz** [comment]
@ahejlsberg as I understand, this PR, as opposed to https://github.com/microsoft/TypeScript/pull/26797, won't solve following problem with "nominal/brand" types:

```
type Id = string & {__brand: 'Id'};
type Cache = Record<Id, string>;

const cache: Cache = {};
declare const someId: Id;
cache[someId] = '{}'; // TS7053: Element implicitly has an 'any' type because expression of type 'Id' can't be used to index type 'Cache'.
```

If I'm right, are there any plans to solve it in the future?

**Comment by ahejlsberg** [comment]
@somysz The PR currently doesn't permit intersections as key types in index signatures, but there's really no reason it couldn't, provided the intersections include one of `string`, `number`, `symbol`, or a template literal type with placeholders. I'll look at making the change.

File: tests/baselines/reference/indexSignatures1.js (hunk 4 above)
Comment (ahejlsberg) [reply tests/baselines/reference/indexSignatures1.js:32]: Fixed in latest commit.

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -14684,16 +14662,17 @@ namespace ts {
                 if (objectType.flags & (TypeFlags.Any | TypeFlags.Never)) {
                     return objectType;
                 }
-                const stringIndexInfo = getIndexInfoOfType(objectType, IndexKind.String);
-                const indexInfo = isTypeAssignableToKind(indexType, TypeFlags.NumberLike) && getIndexInfoOfType(objectType, IndexKind.Number) || stringIndexInfo;
+                // If no index signature is applicable, we default to the string index signature. In effect, this means the string
+                // index signature applies even when accessing with a symbol-like type.
```
Comment (weswigham) [inline src/compiler/checker.ts:14666]: 😦 Shouldn't we.... fix this?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -26400,9 +26350,10 @@ namespace ts {
             return createObjectLiteralType();
 
             function createObjectLiteralType() {
-                const stringIndexInfo = hasComputedStringProperty ? getObjectLiteralIndexInfo(node, offset, propertiesArray, IndexKind.String) : undefined;
-                const numberIndexInfo = hasComputedNumberProperty ? getObjectLiteralIndexInfo(node, offset, propertiesArray, IndexKind.Number) : undefined;
-                const result = createAnonymousType(node.symbol, propertiesTable, emptyArray, emptyArray, stringIndexInfo, numberIndexInfo);
+                const stringIndexInfo = hasComputedStringProperty ? getObjectLiteralIndexInfo(node, offset, propertiesArray, stringType) : undefined;
+                const numberIndexInfo = hasComputedNumberProperty ? getObjectLiteralIndexInfo(node, offset, propertiesArray, numberType) : undefined;
```
Comment (weswigham) [inline src/compiler/checker.ts:26354]: We should probably support making a `symbol` indexer here, now, too, no (since we finally can)? Having `symbol`s continue to make `string` indexers in computed name positions seems pretty bad.

**Review by weswigham — COMMENTED** [review]
My earlier comment on wanting some fourslash tests on goto-def on accesses that resolve to multiple index signatures still stands - I know that code generally depends on what declarations we attach to the type constructs, and right now we're attaching none to the synthetic indexed access in `findApplicableIndexInfo` (rather than any or all of them), so I suspect it doesn't actually work, which is why I'd like a test to show me wrong~

File: tests/cases/conformance/types/members/indexSignatures1.ts [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+type Tag1 = { __tag1__: void };
+type Tag2 = { __tag2__: void };
+
+type TaggedString1 = string & Tag1;
+type TaggedString2 = string & Tag2;
+
+declare let obj1: { [key: TaggedString1]: string };
+declare let obj2: { [key: TaggedString2]: string };
+declare let obj3: { [key: TaggedString1 | TaggedString2]: string };
+declare let obj4: { [key: TaggedString1 & TaggedString2]: string };
```
Comment (weswigham) [inline tests/cases/conformance/types/members/indexSignatures1.ts:108]: Can we add some lines to this test where we relate these objects to one another (rather than just accessing them) - index signature relating is a special codepath, so it's worth checking that, eg, union and intersection index signatures still have the correct relationships with both one another and with the `number` and `string` index signatures (for unions/intersections of tagged `number`s and `string`s).

File: src/compiler/checker.ts (hunk 5 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:14666]: That was my first thought, but no. It only matters for calls to `getIndexedAccessTypeOrUndefined` with no `accessNode` parameter--if we have an `accessNode`, we will indeed report an error when no property or applicable index signature exists. The scenario it enables is having constraints for index accesses involving type parameters constrained by string index signatures. For example, given a type parameter `T extends { [key: string]: boolean }`, we want `T[keyof T]` to have the constraint `boolean`, even though it _technically_ could have symbol-named properties of other types. The constraint is resolved as `T[string | number | symbol]`, which becomes `T[string] | T[number] | T[symbol]`, and `T[symbol]` would spoil the result here without the fallback to the index signature.

**Comment by ahejlsberg** [comment]
@weswigham @RyanCavanaugh Latest commits address code review feedback.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -27968,7 +27938,7 @@ namespace ts {
          * Return true if the given type is considered to have numeric property names.
          */
         function hasNumericPropertyNames(type: Type) {
-            return getIndexTypeOfType(type, IndexKind.Number) && !getIndexTypeOfType(type, IndexKind.String);
+            return getIndexInfosOfType(type).length === 1 && !!getIndexInfoOfType(type, numberType);
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:27941]: This diff surprised me; I'd like to understand it.

**Review by RyanCavanaugh — APPROVED** [review]

File: src/compiler/checker.ts (hunk 8 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:27941]: Yeah, it's a bit odd. For an element access expression `a[i]`, when `a` has _only_ a numeric index signature and `i` is the iteration variable of a `for (let i in a)`, we consider `i` to have type `number` in the element access expression. Basically, this is what enables `for (let i in a)` to work with arrays. Now that we can have any number of index signatures, it's not enough to just check we don't have a string index signature. Hence the change.

**Comment by kamok** [comment]
Congrats. I look forward to this feature.

File: src/compiler/checker.ts (hunk 8 above)
Comment (RyanCavanaugh) [reply src/compiler/checker.ts:27941]: Ah my confusion came from elsewhere: the diff highlighting made me misread it as `!` instead of `!!`

‼

**Comment by leidegre** [comment]
Thank you for addressing this issue!

**Comment by Repugraf** [comment]
Thanks for this. This was long awaited update.
Is there any intel when this will be released with new version tag?

**Comment by liuweiGL** [comment]
`symbol` still not working：https://www.typescriptlang.org/play?ts=4.4.0-dev.20210627#code/PTAEiJrQ5+MU3NAYlUAqBPADgUwMoGMBOBLFAF1EA47QBTlAudUBh-gKBFEE34wejNAAOUCo5QTb9ADeUAXjQbPlAaP6BMxSqAwJUDVcoBiVQGbagAzlEqTLgLFAIW6BFf0CbXoCAGGnTCAKg0D3yoFO5E4CDNQNBygSDlAs56BO00Dw+oH95QBSugYO1AWP-79oUAFpQdkBYOUAseUAWD0B5dUBvuUBVeUAcOUB-SNU5BXRsfCJQVUAGdXtdegCgtkBleUAYrLSlTOJAW+jAVZtANz1AODlAaojALrkJXPzfIvZXQDi5QGlbQFXo4MAYFUqMlVABQEXowHxzQHylQF+A1UBMm0BG710aPAA7QjQcADMAQyw0UABBUABvGj8-E4B+AC5QAGdCfF2Ac3uHgBGr1AuwArgBbAGHf5+ADaAGs0Eg3gADAAe-gAJDdPt8fgBfFGgAA+HyQkIA9gAbAC6b1xez++L0WApu0+ZMpVIA0kjQABeUAYckA6kACgA5IikBKAJQstkck5va6Cu4PUASjEnCVvCUARgATABmCUAGhhoFh7xF1N5SDpmqNppozN8pkAnQ6Ab8VAFBy9lUoEAOASALk9ANHygFwCUCANCMg4AG00A36nhqgmQBhcoBjyMAL2aALE1AM6K-RqgAAo1SAQ-lAPYG2gARL4o4BQAMABEqAEzSGIBsuUAFzaAKcSGoAUOUAAPqAac03FRAC6mbHIFFUgDQ5QAyroBfhMAejr9Li6IA

**Comment by Repugraf** [comment]
@liuweiGL that is fixed by adding explicit type:
```ts
const symbolKey: symbol = Symbol('key')
```

Without it there is a type error:
Screenshot 2021-06-29 at 10 56 11 AM

**Comment by liuweiGL** [comment]
Is this a transitional plan?

**Comment by Repugraf** [comment]
@liuweiGL I don't know. I'm not a developer in TS team =D
I've just seen your comment and tried to find the solution.

**Comment by huan** [comment]
Thank you very much for the great work on this new feature! It works like a charm in my project.

**Comment by shellscape** [comment]
Something is amiss with this, or it's not been released yet. Still receiving the 'ol `error TS1337: An index signature parameter type cannot be a union type. Consider using a mapped object type instead.` errors. @RyanCavanaugh can you confirm it's been released as of 4.3.5?

**Comment by leidegre** [comment]
> Something is amiss with this, or it's not been released yet. Still receiving the 'ol `error TS1337: An index signature parameter type cannot be a union type. Consider using a mapped object type instead.` errors. @RyanCavanaugh can you confirm it's been released as of 4.3.5?

It's currently in the 4.4 release which is in beta scheduled to be released by the end of August.

**Comment by vepanimas** [comment]
@ahejlsberg Could you please clarify why those cases work differently in terms of assignability ([playground](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210830#code/MYewdgzgLgBBCeBbGBeGBlJAjEAbAFAJQDcAUKQGYCuYwUAluDAObMDM+AHgFwwDeMANoBrAKbxe0AE70wzALqSoMuTAC+AGhgAvXgMEJEimGCqIsoqesL9SMGJ1Q7i9gPSuYAeWGk15WVCWFACGwKIwAOIRACy29vYGSMam5pZkfpQ0dIxgLMzRXHpCYhJwyrIKSirM6lq6kTE2fHYOTtou7jAAolJSIFK+5FDwAA7hUQCsTs3xQobJZhZS6eTUtAxMrBOF-MXiVRXG0hW1OryTTS2OaO0wnd4wAPwAhL5AA))?
```
const sym = Symbol();

function gg3(x: { [key: string]: string }, z: { [sym]: number }) {
  x = z;  // Ok
}

interface GG4 {
    [sym]: number;
}

function gg4(x: { [key: string]: string }, z: GG4) {
  x = z; // Error
}

type GG5 = {
    [sym]: number;
}

function gg5(x: { [key: string]: string }, z: GG5) {
  x = z; // Ok ?!
}
```

**Comment by douglasg14b** [comment]
Is this in and working? I'm sitting on `v4.4.2` and still receiving:

> An index signature parameter type cannot be a union type. Consider using a mapped object type instead

image

**Comment by soffieprincess07** [comment]
> With this PR we implement support for symbol and template literal string index signatures. We furthermore permit index signature declarations to specify union key types, provided all constituents are either `string`, `number`, `symbol`, or template literal types with non-generic placeholders. Some examples:
> 
> ```ts
> type SymbolMap<T> = {
>     [key: symbol]: T;
> };
> 
> type DataProps = {
>     [key: `data-${string}`]: string;
> };
> 
> type PropertyMap = {
>     [key: string | number | symbol]: string;
> };
> ```
> 
> An index signature declaration that specifies a union key type is exactly equivalent to a set of distinct index signatures for each constituent key. For example, the `PropertyMap` declaration above is exactly equivalent to:
> 
> ```ts
> type PropertyMap = {
>     [key: string]: string;
>     [key: number]: string;
>     [key: symbol]: string;
> };
> ```
> 
> Index signature declarations are not permitted to specify literal key types or generic key types. Those kinds of types can only be used with mapped types, which map literals key types to distinct properties and defer resolution of generic key types until they're instantiated with non-generic types. For example:
> 
> ```ts
> type Thing<T> = Record<'a' | `foo${T}` | symbol, string>;
> 
> type StringThing = Thing<string>;  // { [a: string, [x: `foo${string}`]: string, [x: symbol]: string }
> type BarThing = Thing<'bar'>;  // { [a: string, foobar: string, [x: symbol]: string }
> ```
> 
> This PR supercedes #26797 which was more ambitious but had overlap between regular properties and index signatures with literal key types that is difficult to reconcile, as well as generic index signatures for which type relationships become exceedingly complex to reason about.
> 
> Fixes #1863.
> Fixes #26470.
> Fixes #42192.
> Fixes #44675.

**Comment by craigphicks** [comment]
@douglasg14b 

You can do it using `type` and `in`

```typescript
type Test = 'one' | 'two';
type Foo= {
  [key in Test]: any;
}
//type Foo = {
//    one: any;
//    two: any;
//}

type Foo2= {
  [key in `${Test}${Test}`]: any;
}
//type Foo2 = {
//    oneone: any;
//    onetwo: any;
//    twoone: any;
//    twotwo: any;
//}
```

[playground](https://www.typescriptlang.org/play?ssl=2&ssc=1&pln=19&pc=4#code/FAFwngDgpgBAKlAziGBeGByA9gOyhmAH0xAHcsMBuUSWAMSy3QG9gYYBtAayjBgEsc8JCAC6ALhgBDHGGoBfYAHol4aDAZY0MVivbtcUSTLnKl+mGSzHZ1FYprrNAJhZtOPPoJgADACTMCMjyAUEg8j4S0rbAiipq9IzO2rrm+oaGNqZ66XhWWXZp7FaZ0dlFluT5ZYXyQA)

**Comment by craigphicks** [comment]
@ahejlsberg - This is really a great feature, thanks!

I noticed that spaces seem to count as digits with the number type.  How about not allowing that? 
Of course with unquoted literal labels it doesn't matter, but with quoted string indices it does.
```
type TP4 = {[k:`${number}`]:null}
const tp4_1:TP4 = {'1':null}
const tp4_2:TP4 = {' ':null}   // even though there is no number present, it passes
const tp4_3:TP4 = {' 1':null}
const tp4_4:TP4 = {'1 ':null}
const tp4_5:TP4 = {' 1 ':null}
```
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgCgFigXigbwNoGsBcADAEjQDsBXAWwCMIAnAXzwF0cyAbVugKAGMB7YgM7AowMAgD6ARhzwkqNAHJJClqXZc+g4aIkAmGYhToFUFWw49+QkWPEBmA3ONRlq9Za02JCR0cWTTNwtNax1xAFZfeRMAszULIA)

**Comment by 599316527** [comment]
Index signatures for template literal string with generic?

```ts
type Props<T extends string> = {
  renders: {[key in T]: any};
  [key: `render${Capitalize<T>}`]: any;
};
```

**Comment by liuyiqi1999** [comment]
1. If there're **other keys** needing restricting value type, how should I put it?
```
type Test = 'one' | 'two';
type Foo= {
  stringKey: string; // A mapped type may not declare properties or methods.
  numberKey: number;
  [key in Test]: any;
}
```
[playground](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAKlAziGBeGByA9gOyhmAH0xAHcsMBuUSWAMSy3QG9gYZkAnASxwHMA0lDAAuDiB79q7HAFcAtgCMonIaJhylK6TADaAa2Exe8JCAC6YgIY4w1AL7AA9E-DQYDLGhisX7drhQ1rbUfv5kWMF2zk6ONO6eAEwsbHqGYMY4MAAGACTMCMj2+YUg9tmWMDbRji5u9IyJ3r5O-jCBgVGhrf6BEV0xbRGdVSGD4eT9o9Eu9kA)

2. Can this feature be used in **interfaces**?
```
enum Test {
  ONE = 'one',
  TWO = 'two'
}
interface Foo {
  [key: Test]: any; // An index signature parameter type cannot be a literal type or generic type. Consider using a mapped object type instead.
}
```
[playground](https://www.typescriptlang.org/play?#code/FAUwdgrgtgBAKiAzgFxgb2DGB5AcgURgF4YByAezBFIBpN4B1bYs5Ad3NOAF9gBLMMhAAnAGYBDAMYgYAMXLl09ANoBrEAE8AXPCTIAujvFgNAbh7AA9JeQaADjPmKSGa1iyUQRk+bfv25N5mVpa8wLYOcgoATC4q6howAjAABgAkaAgo3BlZyNwphjDGwbzWEY4xLK6W7jCenkG+te6eAU0hdQGNxT6d-hztvcHW3EA)

**Comment by airtonix** [comment]
> 1. If there're **other keys** needing restricting value type, how should I put it?

As [two separate mapped objects](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAYgSygGwCYBVKwLwwORQC2AhgsnjAD74hQAeIF1etDxATlMU-gM4CuAI0IJGVfJ15QxzKcigBjGfgUALRQGtBAezo887YqgTb9qhKlRQAdvuv9CgqOzwBuYKCzxt7QgCF+EBBta0QUVBhcAG9gGBhwaAAueCQ0TGh3OOtiQigAfmTeEHYEawBzTJhkYidkApgikvLKzgBHfgROVHqdbXlia0qIaoUoVT6rdnrG0orgAF8PT2hvXwCgkIB1UVUAGRqUXkiYGLiAbQ0oMBhSmAADABIosLSsef3au4BdZIAFDhACGIyAAPABhADKUPA8gAIopqoZASEAHzuRYJWBwHz+QLBazbECqACS1gggSO0ViMAuVxu1nuTxeGDepPJIG+fwBQNBkOhYDhCI4xGR1jRCw8mNWuI21j8xCkEJhUEpJ2pgjxIS57EBwPBUKVAqg8IUiJFJjFrgA9Fb4uoYBrZdSEAAzQy5bW63kG5Ums2itE2+LaYZQABuKBgLv4yGQDQUnBsNzdOSg1N45kInp5+v5gtNwoD1tt0dj8cTDMExAUGjK7G0-GsqGphG0qGBYJCIFI1mc2b1fMN+f9FsDtoUXZ7zijPhgrfbyAANA1pEcIEZjOUW23gf3vXnjUKkaPizAICH+BA5zulyuQEcM0ZtAB3Zc6diTamAkDyPe5oeHgWx6oqeABEnbWN2SgwAAqrwoHxKI8gwM+OwOtWtb1o2zZxFYvAJggECin+g6+ke5ogUGtQvohP5pnEOioGAJE+kafqFieQbzsCMATpBNggNSLo4hB3alH2MD-DqOakWx5FFkGz6GBARxErAwm+EJOJKiK-C8CxB7scBlpBi6ZDIEcGmELxk7iewKFoUUulHLkvC8MQZT0TOvgGQBRkUSZtpqd51miHILrUtUtS+WRQEBWOVQHBZdoiihykwFwaghVGqQ4fS7IxXJcUKbawJxlZ+UUgsMCSl42JrJq1gAaq9Uyvi8qKsqRwAGTSus+KEnsSU9X1jWDWyVW1SsrX9SE8JmdYogWscpwwNWxENMUsyVN+v6bU0cxxGZ4T6aNsrMmcXyVEURqnVJXogjNjXNeK8zuMssAAIr8FAP2oK1xxnOmW3lIu1JPbK82lEtITAFdHilLQ7AutWsDbE2NGrVZjr4skq1xK0yTfb9UD-Til2VHEAAUFiFCDZTLlYC0w9YyQQ-iUOLaKACUyRhtoFiVG9EoeHxRQwEz0PEezc1QMzoordScTrRayR4KoQQQIkNrCdoAB0E6EHgYNxHEu1QGrADi0j0sG-BqMbSs5SdyRA6bpv4+78RYGrRCkOQJte3EUUoGrACiJBkIkjtB1kqa+5HAdO+7bQdF0yTFD9gdB8MqPjGgEl4GADbsAAAn7ZAG9oRvZ6b8y13Envu5iausN2nDcA3psh8gasALIqu5nnR13ccevgrlD1AMex7noz55MySgZsqgingRwhDAxf8PZIhNnkoFd-XycnN7SR8EIIhiMf7tfLXN3yKdTe0XtUTHyfaiaDodAfKHJw317XWv9e7-xgEGMOAAlCBAB5CBJ8nYAPmEAA)
