### PR TITLE
fix 57215 -- add support for import attributes to OrganizeImports

### LINKED ISSUE #57215: Organize Imports: Incorrect combination of imports with import attributes
### 🔎 Search Terms

"organize imports assert", "organize imports with", "organize imports assertions", "organize imports attributes"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "organize imports"

### ⏯ Playground Link

Playground doesn't support organize imports as far as I can tell.

### 💻 Code

In VSCode run the organize imports command on the following code:

```ts
import { A } from "./file";
import { type B } from "./file";
import { C } from "./file" assert { type: "a" };
import { A as D } from "./file" assert { type: "b" };
import { E } from "./file" with { type: "a" };
import { A as F } from "./file" with { type: "b" };

type G = A | B | C | D | E | F;
```

### 🙁 Actual behavior

Currently, organize imports will combine all the imports to the following line:

```ts
import { A, C, A as D, E, A as F, type B } from "./file";

type G = A | B | C | D | E | F;
```

### 🙂 Expected behavior

As import attributes can change the behavior of the imported module they should stay as separate lines:
```ts
import { A, type B } from "./file";
import { C } from "./file" assert { type: "a" };
import { A as D } from "./file" assert { type: "b" };
import { E } from "./file" with { type: "a" };
import { A as F } from "./file" with { type: "b" };

type G = A | B | C | D | E | F;
```

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by iisaduan**
This fix will prevent import statements from coalescing unless they also have the same import attributes. It does not reorder statements with the same module specifier but different attributes.

Fixes #57215

### CODE REVIEW

File: src/services/organizeImports.ts [hunk 1]
```diff
@@ -322,96 +322,105 @@ function coalesceImportsWorker(importGroup: readonly ImportDeclaration[], compar
...
-            // Add the namespace import to the existing default ImportDeclaration.
-            const defaultImport = defaultImports[0];
-            coalescedImports.push(
-                updateImportDeclarationAndClause(defaultImport, defaultImport.importClause.name, namespaceImports[0].importClause.namedBindings),
-            );
-
-            continue;
+    const importGroupsByAttributes = groupBy(importGroup, decl => {
+        if (decl.attributes) {
+            return decl.attributes.getFullText();
```
Comment (andrewbranch) [inline src/services/organizeImports.ts:327]: Saw some discussion on Teams about this. As you were concerned about, this is sensitive to attribute order, spacing, comments, quote preference, etc. The grammar is simple enough that I think instead of doing something like emitting a normalized version of the text (which would still be sensitive to attribute order), you could pretty easily write something like

```ts
function getImportAttributesId(attributes: ImportAttributes) {
  const keyValuePairs = new Map<string, string>;
  // - iterate over attribute elements
  // - value must be a string literal expression if valid
  // - if invalid, insert something unique?
  let id = "";
  const sorted = sort(
    arrayFrom(keyValuePairs.entries()),
    ([keyA], [keyB]) => compareStringsCaseSensitive(keyA, keyB)
  );
  for (const [key, value] of sorted) {
    // value.length included in case `key` contains `:`,
    // a bit over the top but technically something like
    // this is needed
    id += `${key}:${value}:${value.length}|`;
  }
  return id;
}

File: src/services/organizeImports.ts [hunk 2]
```diff
@@ -322,96 +323,109 @@ function coalesceImportsWorker(importGroup: readonly ImportDeclaration[], compar
...
-            coalescedImports.push(
-                updateImportDeclarationAndClause(defaultImport, defaultImport.importClause.name, namespaceImports[0].importClause.namedBindings),
-            );
-
-            continue;
+    const importGroupsByAttributes = groupBy(importGroup, decl => {
+        if (decl.attributes) {
+            let attrs = decl.attributes.token + " ";
+            for (const x of sort(decl.attributes.elements)) {
+                attrs += x.name + ":" + x.value.getText() + " ";
```
Comment (andrewbranch) [inline src/services/organizeImports.ts:330]: This is still sensitive to quote type since `getText()` includes quotes. Something like ``isStringLiteralLike(x.value) ? `"${x.value.text}"` :  x.value.getText()`` would be better—normalizing quotes without treating `"42"` and (the illegal value) `42` as the same.

File: tests/cases/fourslash/organizeImportsAttributes3.ts [hunk 3]
```diff
@@ -0,0 +1,20 @@
+/// <reference path="fourslash.ts" />
+
+////import { A } from "./a";
+////import { C } from "./a" assert {      type: "a" };
+////import { Z } from "./z";
+////import { A as D } from "./a" assert    { type: "b" };
+////import { E } from "./a" assert { type: /* comment*/ "a"              };
+////import { F } from "./a" assert     {type: "a" };
+////import { Y } from "./a"   assert{ type: "b" /* comment*/};
```
Comment (andrewbranch) [inline tests/cases/fourslash/organizeImportsAttributes3.ts:9]: You could add another test showing that

```ts
import { A } from "./a" assert { foo: "foo", bar: "bar" };
import { B } from "./a" assert { bar: "bar", foo: "foo" };
```

can be combined since you sorted the elements.

Comment (iisaduan) [reply tests/cases/fourslash/organizeImportsAttributes3.ts:9]: Nice idea!

File: src/services/organizeImports.ts [hunk 4]
```diff
@@ -322,96 +323,109 @@ function coalesceImportsWorker(importGroup: readonly ImportDeclaration[], compar
...
-            const defaultImport = defaultImports[0];
-            coalescedImports.push(
-                updateImportDeclarationAndClause(defaultImport, defaultImport.importClause.name, namespaceImports[0].importClause.namedBindings),
-            );
-
-            continue;
+    const importGroupsByAttributes = groupBy(importGroup, decl => {
+        if (decl.attributes) {
+            let attrs = decl.attributes.token + " ";
+            for (const x of sort(decl.attributes.elements)) {
```
Comment (andrewbranch) [inline src/services/organizeImports.ts:329]: I’m not sure this `sort` is doing what you want. `elements` is an array of `Node` objects, which are going to get coerced to strings before sorting. Most likely every element is going to turn into `[object Object]` or `[object Node]` and the sort order will never change.

image

**Review by andrewbranch — APPROVED** [review]
