### PR TITLE
Disable import fix for method of 'export =' value

### LINKED ISSUE #20191: valueOf can be imported from anywhere
so i have `valueOf` function defined in module `xxx.ts`
```ts
export function valueOf<T>(value: { value: T; }): T {
    return value.value;
}
```

then in file `yyy.ts` i am trying to do auto import and this is what i see:

image

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20191

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -720,7 +720,9 @@ namespace ts.codefix {
 
             // check exports with the same name
             const exportSymbolWithIdenticalName = checker.tryGetMemberInModuleExportsAndProperties(symbolName, moduleSymbol);
-            if (exportSymbolWithIdenticalName && checkSymbolHasMeaning(exportSymbolWithIdenticalName, currentTokenMeaning)) {
+            if (exportSymbolWithIdenticalName && checkSymbolHasMeaning(exportSymbolWithIdenticalName, currentTokenMeaning)
+                // Don't auto-import a method of an `export =` module (See GH#20191)
+                && !(exportSymbolWithIdenticalName.flags & SymbolFlags.Method)) {
```
Comment (mhegazy) [inline src/services/codefixes/importFixes.ts]: this is going to break many of the dt definitions.. for instance, JQuery: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/index.d.ts#L28

Comment (weswigham) [reply src/services/codefixes/importFixes.ts]: Instead of just relying on the meaning, I think what's more correct is to check is if the symbol's declarations is part of the global `Object`, `String`, `Number` , or `Symbol` declaration, right? I think you could probably check using our current internal checker APIs by doing something like
```ts
exportSymbolWithIdenticalName.valueDeclaration && checker.getPropertyOfType(checker.getStringType(), exportSymbolWithIdenticalName.name).valueDeclaration === exportSymbolWithIdenticalName.valueDeclaration // repeat for number, symbol, object
```

**Comment by andy-ms** [comment]
@weswigham @mhegazy Please re-review

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -1897,13 +1897,18 @@ namespace ts {
...
-            return symbol;
+
+            const exportEquals = resolveExternalModuleSymbol(moduleSymbol);
+            if (exportEquals === moduleSymbol) {
+                return undefined;
+            }
+
+            const type = getTypeOfSymbol(exportEquals);
+            // If the apparent type is different, this is a primitive, so let's not treat that as an exported symbol.
+            return getApparentType(type) === type ? getPropertyOfType(type, memberName) : undefined;
```
Comment (mhegazy) [inline src/compiler/checker.ts]: why not just `type && type.typeFlags & TypeFlags.Primitive` ?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -1897,13 +1897,18 @@ namespace ts {
...
             }
-            return symbol;
+
+            const exportEquals = resolveExternalModuleSymbol(moduleSymbol);
+            if (exportEquals === moduleSymbol) {
+                return undefined;
+            }
+
+            const type = getTypeOfSymbol(exportEquals);
+            // If the apparent type is different, this is a primitive, so let's not treat that as an exported symbol.
```
Comment (mhegazy) [inline src/compiler/checker.ts]: comment is outdated.
