### PR TITLE
Fixing #442: Impossible to define static 'length' function on class

### LINKED ISSUE #442: Impossible to define static 'length' function on class
The following typescript program is accepted:

``` typescript
class C {
    static length ()  { return "twelve"; }
}
```

However, in the generated code:

``` javascript
var C = (function () {
    function C() {
    }
    C.length = function () {
        return "twelve";
    };
    return C;
})();
```

Here, an attempt is made to assign to the `length` property of a function. This doesn't work (at least in Firefox and Chrome), causing subsequent calls of `C.length()` to crash. Perhaps calling a static class function `length` should just be disallowed?

Migrated from codeplex [issue #1260](http://typescript.codeplex.com/workitem/1260).

### PR DESCRIPTION
**Pull request by about-code**
[x] There is an associated issue that is labelled 'Bug' or 'Accepting PRs' or is in the Community milestone
[x] Code is up-to-date with the `master` branch
[x] You've successfully run `jake runtests` locally
[x] You've signed the CLA
[x] There are new or updated unit tests validating the change

Fixes #442

By accepting this pull request when a static property name conflict is detected a new error message

```
TS2699: Static property 'X' conflicts with built-in property 'Function.X' of constructor function 'Y'
```
will be issued. 

## Conflicting method declarations
For example
```typescript
class Foo {
    static name() {
        return "Bar";
    }
}
```
produces
```
TS2699: Static property 'name' conflicts with built-in property 'Function.name' of constructor function 'Foo'
```
for compile target `es5` or lower. Because ES2015 runtimes seem to be able to handle potentially conflicting static method declarations natively (apart from `prototype`), by internally setting the native function property to `writable: true`, there won't be an error for target `es6` in the current implementation. The absence of an error in this case just indicates, that it will be handled without a runtime error. It may still lead to unexpected results if a user is not aware of overwriting the class constructor's *name* property which he might want to use elsewhere to read the class name (see [examples on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#Examples)). So I leave open to discussions if we should also issue an error for these cases when targeting `es6`.

## Conflicting property declarations

```typescript
class Foo {
    static name = "Bar";
}
```
is impossible to fix for target `es5` because of `Function.name` being non-configurable and non-writable by spec. and at least in some `es5` runtimes. In `es6` targets `Function.name` is configurable but non-writable by default. Without changes to the emitter above value would not be assigned. It seems like it could be made possible *for `es6`* runtimes and above, using an emit like
```
Object.defineProperty(Foo, "name", {
   writable: true,
   value: "Bar"
});
```
Unfortunately I am not able to contribute such change myself. The pragmatic solution will be to also raise a transpile error [which some may favour over a transpile, anyway](https://github.com/Microsoft/TypeScript/issues/442#issuecomment-169883065).

Eventually, here's a matrix of the various static member declarations and when a transpile error will be raised:

### Target `es3`, `es5`:
| member declaration          | configurable | writable |  How handled      
|-----------------------------|--------------|----------|------------------|
| `static prototype = ""`     |      no      |     no   |  error
| `static arguments = ""`     |      no      |     no   |  error
| `static caller = ""`        |      no      |     no   |  error
| `static length = ""`        |      no      |     no   |  error
| `static name = ""`          |      no      |     no   |  error

| method declaration          | configurable | writable | How handled     
|-----------------------------|--------------|----------|------------------|
| `static prototype(){...}`   |      no      |     no   |  error
| `static arguments(){...}`   |      no      |     no   |  error
| `static caller(){...}`      |      no      |     no   |  error
| `static length(){...}`      |      no      |     no   |  error
| `static name(){...}`        |      no      |     no   |  error

### Target `es6` and higher:
| member declaration          | configurable | writable | How handled
|-----------------------------|--------------|----------|------------------|      
| `static prototype = ""`     |      no      |     no   |  error
| `static arguments = ""`     |     yes      |     no   |  error\*
| `static caller = ""`        |     yes      |     no   |  error\*
| `static length = ""`        |     yes      |     no   |  error\*
| `static name = ""`          |     yes      |     no   |  error\*

| method declaration          | configurable | writable | How handled      
|-----------------------------|--------------|----------|------------------|
| `static prototype(){...}`   |      no      |     no   |  error
| `static arguments(){...}`   |     yes      |     no\**   |  ok
| `static caller(){...}`      |     yes      |     no\**   |  ok
| `static length(){...}`      |     yes      |     no\**   |  ok
| `static name(){...}`        |     yes      |     no\**   |  ok

\* could be enabled by changing emitter output
\** property made writable internally by the runtime, once a method declaration exists

## Prior work

TypeScript has been preventing the declaration of a static class member *prototype* since the first public commit by @mhegazy and since then issued a TS2300: Duplicate identifier 'prototype' error.
```typescript
class Foo {
    static property: any;
}
```
There were no changes made to the existing implementation. However, having a static *prototype* property falls into the same category of errors as to be handled for fixing #442. Hence when running the tests for this pull request the baseline for test case tests/cases/conformance/classes/propertyMemberDeclarations/propertyNamedPrototype.ts changed and now also contains a static property conflict error. I accepted this as a new baseline. 

Another attempt to fix #442 is PR GH-5396

### CODE REVIEW

**Comment by basarat** [comment]
Not on the TypeScript dev team. That said, the error message looks fantastic 🌹❤️

**Comment by about-code** [comment]
@basarat you're as visible and active in the TS community as if you were part of the dev team :smile: Have got in touch with TS thanks to you and *atom-typescript*. So this :rose: from :de: is for you. Glad to here, you like the message.

**Comment by about-code** [comment]
Withdrawing the PR. Not yet ready to be merged.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14771,6 +14771,49 @@ namespace ts {
             }
         }
 
+        // Static members may conflict with non-configurable non-writable built-in Function object properties
```
Comment (sandersn) [inline src/compiler/checker.ts]: Please use jsdoc format.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14771,6 +14771,49 @@ namespace ts {
             }
         }
 
+        // Static members may conflict with non-configurable non-writable built-in Function object properties 
+        // see https://github.com/microsoft/typescript/issues/442.
```
Comment (sandersn) [inline src/compiler/checker.ts]: instead of a github issue number, can you reference the spec the way you do below instead?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -14771,6 +14771,49 @@ namespace ts {
             }
         }
 
+        // Static members may conflict with non-configurable non-writable built-in Function object properties 
+        // see https://github.com/microsoft/typescript/issues/442.
+        function checkClassForStaticPropertyNameConflicts(node: ClassLikeDeclaration) {
+            const message = Diagnostics.Static_property_0_conflicts_with_built_in_property_Function_0_of_constructor_function_1;
+            const className = getSymbolOfNode(node).name;
+            for (const member of node.members) {
+                const isStatic = forEach(member.modifiers, (m: Modifier) => m.kind  === SyntaxKind.StaticKeyword);
```
Comment (sandersn) [inline src/compiler/checker.ts]: should be `getModifierFlags(node) & ModifierFlags.Static` -- this calculates the modifiers once and then caches them

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -14771,6 +14771,49 @@ namespace ts {
             }
         }
 
+        // Static members may conflict with non-configurable non-writable built-in Function object properties 
+        // see https://github.com/microsoft/typescript/issues/442.
+        function checkClassForStaticPropertyNameConflicts(node: ClassLikeDeclaration) {
+            const message = Diagnostics.Static_property_0_conflicts_with_built_in_property_Function_0_of_constructor_function_1;
+            const className = getSymbolOfNode(node).name;
```
Comment (sandersn) [inline src/compiler/checker.ts]: `getNameOfSymbol(getSymbolOfNode(node))` would be better here. You may have to move `getNameOfSymbol` to make it accessible outside `getSymbolDisplayBuilder`.

Comment (sandersn) [inline src/compiler/checker.ts]: Or just `node.name`, but that doesn't work for anonymous classes, unfortunately. I think that means some of the other error reporting in `checkClassLikeDeclaration` is broken, because it uses `node.name`.

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Yikes, looks like `checkClassForDuplicateDeclarations` also uses this code. We should change that pretty soon.

**Comment by about-code** [comment]
@sandersn Thanks for your review and comments. I'll try to implement them as soon as possible. I fully agree with your concerns regarding potential confusion about member/method distinction for es6.

**Comment by sandersn** [comment]
I just talked to @rbuckton and we both agree that we should simplify ES6' semantics and get rid of the method/property distinction. Using these names should always be an error.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -15647,6 +15648,54 @@ namespace ts {
...
+         * member with the same name as a non-writable built-in property.
+         * 
+         * @see http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.3
+         * @see http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.5
+         * @see http://www.ecma-international.org/ecma-262/6.0/#sec-properties-of-the-function-constructor
+         * @see http://www.ecma-international.org/ecma-262/6.0/#sec-function-instances
+         */
+        function checkClassForStaticPropertyNameConflicts(node: ClassLikeDeclaration) {
+            const message = Diagnostics.Static_property_0_conflicts_with_built_in_property_Function_0_of_constructor_function_1;
+            const className = getNameOfSymbol(getSymbolOfNode(node));
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can you add a test for default-exported classes and anonymous class expressions?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -15647,6 +15648,54 @@ namespace ts {
...
+            for (const member of node.members) {
+                const isStatic = getModifierFlags(member) & ModifierFlags.Static;
+                const isMethod = member.kind === SyntaxKind.MethodDeclaration;
+                const memberNameNode = member.name;
+                if (isStatic && memberNameNode) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Reduce nesting by negating this:

```ts
if (!isStatic || !memberNameNode) {
    continue;
}
```

File: src/compiler/checker.ts (hunk 5 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Also, I would also only get the information you need when you actually report the error. Consider extracting that into a helper function.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -15647,6 +15648,54 @@ namespace ts {
...
+                    const memberName = getPropertyNameForPropertyNameNode(memberNameNode);
+                    if (languageVersion <= ScriptTarget.ES5) {  // ES3, ES5
+                        if (memberName === "prototype" ||
+                            memberName === "name" ||
+                            memberName === "length" ||
+                            memberName === "caller" ||
+                            memberName === "arguments"
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Consider a `switch`/`case` here instead.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -15647,6 +15648,54 @@ namespace ts {
...
+                        ) {
+                            error(memberNameNode, message, memberName, className);
+                        }
+                    }
+                    else { // ES6+
+                        if (memberName === "prototype") {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]:
```ts
switch (memberName) {
    case "name":
    case "length":
    case "caller":
    case "arguments":
        if (isMethod) {
            continue;
        }
        // fall through
    case "prototype":
        error(/*...*/);
```

**Comment by DanielRosenwasser** [comment]
Just saw @sandersn's feedback - feel free to simplify on top of any style nits I left behind based on that.

**Comment by about-code** [comment]
Like @sandersn noted, by omitting  es6 method/property distinction we eventually resolve any differences between the currently supported targets. So I changed my proposal to implement the following semantics:

### All currently supported targets:
| member declaration       | method declaration          |  How handled      
|---------------------------------|-----------------------------------|------------------|
| `static prototype = ""`     | `static prototype(){...}`      |  error
| `static arguments = ""`  | `static arguments(){...}`     |  error
| `static caller = ""`           | `static caller(){...}`            |  error
| `static length = ""`          | `static length(){...}`           |  error
| `static name = ""`          | `static name(){...}`            |  error

### Future targets:
I recently found out about a [tc39 stage2 proposal about class-public-fields](https://github.com/tc39/proposal-class-public-fields). From your reading of the draft, do you think it correctly addresses potential conflicts? For example would a `[[PublicFields]]` internal slot as defined in the proposal prevent collisions in future versions of ECMAScript - at least for *public* static fields?

**Comment by about-code** [comment]
There's also a [tc39 proposal for private fields](https://github.com/tc39/proposal-private-fields).

**Comment by sandersn** [comment]
I think it's fine to put the error in as-is, and if/when the class-public-fields proposal moves to stage 3, we can remove the error for the --esnext target (or whatever edition the proposal makes it into the official spec).

You might raise your concerns with the spec authors, though. During class initialisation, everything in [[PublicFields]] gets passed to `DefinePropertyOrThrow`, which should have the same behaviour as ES6. I think. I'm not sure I'm reading it correctly.

**Comment by sandersn** [comment]
Thanks @about-code!
