### PR TITLE
Fix Intl.DateTimeFormat.format and Int.NumberFormatOptions signature

### LINKED ISSUE #3521: Incomplete intl.d.ts interfaces
DateTimeFormat.format takes a number or _a date object_.
NumberFormatOptions has some additional fields: minimumIntegerDigits, minimumFractionDigits, ...

### PR DESCRIPTION
**Pull request by piloopin**
Closes #3521.

### CODE REVIEW

File: src/lib/intl.d.ts [hunk 1]
```diff
@@ -103,7 +108,7 @@ declare module Intl {
     }
 
     interface DateTimeFormat {
-        format(date: number): string;
+        format(date?: Date | number): string;
```
Comment (mhegazy) [inline src/lib/intl.d.ts]: The spec only mention number, but not date.

Comment (mhegazy) [inline src/lib/intl.d.ts]: from [section 12.3.2: Intl.DateTimeFormat.prototype.format](http://www.ecma-international.org/ecma-402/1.0/#sec-12.3.2)

>When the FormatDateTime abstract operation is called with arguments dateTimeFormat (which must be an object initialized as a DateTimeFormat) and x **(which must be a Number value)**, it returns a String value representing x (interpreted as a time value as specified in ES5, 15.9.1.1) according to the effective locale and the formatting options of dateTimeFormat.

Comment (mhegazy) [inline src/lib/intl.d.ts]: do we know that all engines support `Date` as well?

Comment (piloopin) [inline src/lib/intl.d.ts]: Thanks for the review.

My understanding from the described algorithm is the following:
```
Intl.DateTimeFormat.prototype.format(date) {
  if (date === undefined)  // do something
  else x = toNumber(date);
  return FormatDateTime(this, x);
}
```
where [toNumber](http://www.ecma-international.org/ecma-262/5.1/#sec-9.3) tries to convert essentially any object to a number and fails with a RangeError if it can't. In other words the correct type for `date` would be `any` according to the specs and the output of the following are the same in all of the browsers that implemented this feature:
`new Intl.DateTimeFormat().format(123456789)`
`new Intl.DateTimeFormat().format('123456789')`

I'm not sure how would you normally treat these cases in d.ts files because I'm sure many functions actually do these toNumber, toBoolean, ... on their inputs as javascript doesn't have a type system by nature. My feeling was you will try to enforce type as much as it makes sense to ensure code sanity, etc. If you think `any` would be the way to go here, let me know.

Comment (mhegazy) [inline src/lib/intl.d.ts]: thanks. I did a quick check on different browsers and seems they all support all values as you mentioned.

**Comment by mhegazy** [comment]
thanks!
