### PR TITLE
Avoid testing `isClassDeclaration` if there's no `valueDeclaration`

### LINKED ISSUE #36059: Compiler crash related to interface extending class with private fields
**TypeScript Version:**  3.8.0-dev.20200107

**Search Terms:** private fields, crash, TypeError

**Code**

```ts
class BoxPrototype<A> {
  #value: A
}
class Box2<A> {
  #something: A
}
interface Box<A> extends BoxPrototype<A> {}
declare const box: Box<number>
const box2: Box2<number> = box
```

**Expected behavior:**
Normal typechecking behaviour.

**Actual behavior:**
Compiler crash with this stack trace:

```
node_modules/typescript/lib/tsc.js:80478
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isClassDeclaration (node_modules/typescript/lib/tsc.js:8362:21)
    at reportUnmatchedProperty (node_modules/typescript/lib/tsc.js:40227:27)
    at propertiesRelatedTo (node_modules/typescript/lib/tsc.js:40272:25)
    at structuredTypeRelatedTo (node_modules/typescript/lib/tsc.js:39958:34)
    at recursiveTypeRelatedTo (node_modules/typescript/lib/tsc.js:39711:53)
    at isRelatedTo (node_modules/typescript/lib/tsc.js:39392:38)
    at checkTypeRelatedTo (node_modules/typescript/lib/tsc.js:39101:26)
    at checkTypeRelatedToAndOptionallyElaborate (node_modules/typescript/lib/tsc.js:38421:24)
    at checkTypeAssignableToAndOptionallyElaborate (node_modules/typescript/lib/tsc.js:38415:20)
    at checkVariableLikeDeclaration (node_modules/typescript/lib/tsc.js:51633:25)
```

**Playground Link:** [Playground Link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200104&ssl=9&ssc=29&pln=1&pc=1#code/MYGwhgzhAEBCD2APACgJ3gF0wTwA4FMAeAQQD5oBvAKGmgGIA3MEAV3wC5piqBfK0SDASIATCXLVadCPAC2+DAAsAlgDsA5p2581GfKgBmYYPjhJx0fIj2qAJkKRpMOAhYp9b+AalPB4qiAxoACMkTmFCVRZZYP1Sfn9AkJFwpDEomLjoAF4QpCA)

**Related Issues:**

### PR DESCRIPTION
**Pull request by elibarzilay**
Avoid testing `isClassDeclaration` if there's no `valueDeclaration`

I'm not sure if this is enough -- perhaps it's better to make the test dig through the interface/s to the class?

Add a similar test for `target.symbol.valueDeclaration` which was similarly broken (with the same question still open).

Fixes #36059.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16009,13 +16009,14 @@ namespace ts {
                     unmatchedProperty.valueDeclaration
                     && isNamedDeclaration(unmatchedProperty.valueDeclaration)
                     && isPrivateIdentifier(unmatchedProperty.valueDeclaration.name)
+                    && source.symbol.valueDeclaration
                     && isClassDeclaration(source.symbol.valueDeclaration)
```
Comment (sandersn) [inline src/compiler/checker.ts]: this would be better instead:

```suggestion
                    && source.symbol.flags & SymbolFlags.Class
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16009,13 +16009,14 @@ namespace ts {
...
+                    && source.symbol.valueDeclaration
                     && isClassDeclaration(source.symbol.valueDeclaration)
                 ) {
                     const privateIdentifierDescription = unmatchedProperty.valueDeclaration.name.escapedText;
                     const symbolTableKey = getSymbolNameForPrivateIdentifier(source.symbol, privateIdentifierDescription);
-                    if (symbolTableKey && !!getPropertyOfType(source, symbolTableKey)) {
+                    if (symbolTableKey && getPropertyOfType(source, symbolTableKey)) {
                         const sourceName = source.symbol.valueDeclaration.name;
-                        const targetName = isClassDeclaration(target.symbol.valueDeclaration) ? target.symbol.valueDeclaration.name : undefined;
+                        const targetName = target.symbol.valueDeclaration && isClassDeclaration(target.symbol.valueDeclaration) ? target.symbol.valueDeclaration.name : undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts]:
```suggestion
                        const targetName = getDeclarationName(target.symbol.valueDeclaration);
```

(and for sourceName too)

Comment (sandersn) [reply src/compiler/checker.ts]: you'll have to change the type of `diagnosticName` to `(nameArg: __String | DeclarationName) => string`, since it currently has a too-narrow type.

File: src/compiler/checker.ts (hunk 1 above)
Comment (elibarzilay) [reply src/compiler/checker.ts]: The problem with that is that it won't know that there is a `unmatchedProperty.valueDeclaration.name` on the next line...?
