### PR TITLE
Skip watching script infos in the global type cache location

### LINKED ISSUE #23183: Intellisense stops returning anything in js project
_From @andreasgruenh on April 5, 2018 16:35_

- VSCode Version: 1.21.1
- OS Version: Win 10 pro

Steps to Reproduce:

1. Initiate a create-react-app project (I cannot reproduce the error in a blank project)
2. Add a jsconfig.json with the content: `{}`
3. Open src/App.js
4. Hover and Intellisense (triggered by ctrl + space) should work
5. Create a new file "src/x.js"
6. Intellisense should still work
7. Type `import React from 'react';`
8. Test if intellisense is still working (if not, delete the file and go back to step 5 and use another filename)

After looping 3-6 times, the error occurs and Intellisense and hover information are broken and will only come back when the tsserver is restarted.

Does this issue occur when all extensions are disabled?: Yes

I uploaded the log when this occured here: https://gist.github.com/andreasgruenh/95dfe15dd23d3dfdb547db088199fdbd

Here is a gif of the reproduction: https://gfycat.com/LavishMasculineDuckbillplatypus
The Window has been reloaded directly before the start of the gif and the bug occurs after the 4th file has been created.

_Copied from original issue: Microsoft/vscode#47248_

### LINKED ISSUE #23234: IntelliSense will crash in large projects that use a lot of node modules
_From @RonanQuigley on April 6, 2018 14:12_

- VSCode Version: 1.22.1
- OS Version: Windows 10 

Steps to Reproduce:

1. clone the following repo and navigate to the test>back-end>routes.test.js file: 
```git clone https://github.com/RonanQuigley/vscode-intellisense-bug .```
2. run ```yarn``` to install the node_modules folder. You do not need to execute any script to see this problem.
3. Adjust the import path as demonstrated in the gif below. Notice that aside from being slow (around 1s to update a path, intellisense eventually hangs on 'Loading...' and won't work without an update. 

intellisense

I've tried to replicate this with a barebones project i.e. just two files but it never happens. I've also managed to narrow it down to the node_modules folder. Intellisense, when scanning that folder, will crash if the project has a lot of modules. Just before the crash I've consistently have had this sort of cpu spike:

spike

If you delete the node modules folder, the issue is gone. If you reduce the number of modules, whilst intellisense is a bit slower, the issue is also gone. If you use require instead of import, the issue is also there. I tried to see if it was a specific module causing it, but my tests have shown that it's not the case. It's just the sheer number of modules being used. 

Is there intellisense logging that I can provide that would help? The only current workaround is to restart vscode, which if like me, you encounter this issue incessantly is a complete pain in the butt to deal with. 

There's loads of other files in this project; I've just left them in in case there's something contributing to the issue that perhaps I'm missing. So whilst I have tried to minimise the project to the least amount of files, it only happens in larger setups unfortunately.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#47327_

### PR DESCRIPTION
**Pull request by sheetalkamat**
Do not watch files in the global type cache location. These files are hardly going to change and if they change and can assume that we are not going to watch. This helps in not watching large set of files that get added to projects (especially by default in all javascript projects) through type acquisition.
Fixes #23183
Fixes #23234

### CODE REVIEW

File: src/server/editorServices.ts [hunk 1]
```diff
@@ -642,7 +646,6 @@ namespace ts.server {
                 return undefined;
             }
             if (isInferredProjectName(projectName)) {
-                this.ensureProjectStructuresUptoDate();
```
Comment (mhegazy) [inline src/server/editorServices.ts]: so why is this removed?

Comment (sheetalkamat) [reply src/server/editorServices.ts]: From the commit info:
There is no need to ensure project structure when trying to get inferred project
The project operations will validate if its valid anyways and throw exception accordingly. So this is just saving us check which is quite costly.

Comment (mhegazy) [reply src/server/editorServices.ts]: I thought we wanted to make sure that the file is not claimed by a configured project that was out-of-date before considering inferred projects.. is not that why we added this in the first place?

Comment (sheetalkamat) [reply src/server/editorServices.ts]: This isnt used for that though. That part is still valid. This findProject is just trying to lookup project with given name, and is used by session to get the project with given name passed in or by updateTypings to get the project for which the typings are updated. Both of these do not need to update the whole project structure. They already have project name, so just passing on the project makes sense.  (eg. when trying to set typings for inferred project, we keep on doing this too frequently if the .js file is in inferred project)
