### PR TITLE
Bugs in missing import codefix

### LINKED ISSUE #16963: Incorrect missing import quick fix suggested for colorful-text
From https://github.com/Microsoft/vscode/issues/30001#issuecomment-313264638

**TypeScript Version:**  2.4.1

**Code**
`package.json`

```json
{
  "name": "sand",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "colorful-text": "0.0.1"
  }
}

```

`index.js`:

```js
// @ts-check
import {bold} from 'colorful-text'
bold('')
```

`other.js`:
```ts
// @ts-check
bold('')
```

In `other.js`, try triggering the fix missing import quick fix on `bold`

**Expected behavior:**
See quick fix for `import from `'colorful-text'`

**Actual behavior:**
See quick fix for importing the `d.ts` file from the full path inside of `colorful-text`

screen shot 2017-07-05 at 6 25 04 pm

Note that colorful-text ships with its own `d.ts` file listed in the `package.json`. However they do not use a module:

```ts
export declare function reset(text: string): string;
export declare function bold(text: string): string;
...
```

Changing the `d.ts` file to use a module fixes things:

```ts
declare module 'colorful-text' {
  export declare function reset(text: string): string;
  export declare function bold(text: string): string;
}
```

### PR DESCRIPTION
**Pull request by minestarks**
- We didn't locate the ```package.json``` correctly in cases where the module to be imported is in a subdirectory of the package
- We didn't look at the ```types``` element in package.json (just ```typings```)
- We didn't remove ```/index.js``` from the path if the main module was in a subdirectory

Fixes #16963

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -504,42 +504,60 @@ namespace ts.codefix {
...
+                            }
+
+                            return fullModulePathWithoutExtension;
                         }
 
-                        return getPackageNameFromAtTypesDirectory(relativeFileName);
+                        function getNodeResolvablePath(path: string): string {
+                            const fullPathUptoNodeModules = moduleFileName.substring(0, indexOfTopNodeModules - 1);
+                            if (sourceDirectory.indexOf(fullPathUptoNodeModules) === 0) {
+                                const indexOfTopPackageName = indexOfTopNodeModules + 13 /* "node_modules\".length */;
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: What's the backslash for?

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -504,42 +504,60 @@ namespace ts.codefix {
...
-                                            relativeFileName = getDirectoryPath(relativeFileName);
+                                            return packageRootPath;
                                         }
                                     }
                                 }
                             }
-                            catch (e) { }
+
+                            // If the file is index.js, it can be imported by its directory name
+                            if (endsWith(fullModulePathWithoutExtension, "/index")) {
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Has the path already been normalized?  If not, do you need to check for backslash as well?

File: src/services/codefixes/importFixes.ts [hunk 3]
```diff
@@ -504,42 +504,60 @@ namespace ts.codefix {
                             return undefined;
                         }
 
-                        const indexOfNodeModules = moduleFileName.indexOf("node_modules");
-                        if (indexOfNodeModules < 0) {
+                        const indexOfTopNodeModules = moduleFileName.indexOf("node_modules");
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Seems like this could produce false positives (e.g. "node_modules2").

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: If I change it to a forward slash it may become clearer.
It's trying to say that the constant 13 corresponds to the length of ```node_modules/```, i.e.
```"node_modules/".length```

File: src/services/codefixes/importFixes.ts (hunk 2 above)
Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: I should check on this. Since ```/index``` was existing code, I relied on the assumption that it was normalized -- but wouldn't hurt to verify.

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Oh, it's a path separator?  Forward slash might be more consistent with the code.

File: src/services/codefixes/importFixes.ts (hunk 3 above)
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Would implementing a path splitter simplify the logic in this method?

File: src/services/codefixes/importFixes.ts [hunk 4]
```diff
@@ -504,42 +504,60 @@ namespace ts.codefix {
...
+                            if (context.host.fileExists(packageJsonPath)) {
+                                const packageJsonContent = JSON.parse(context.host.readFile(packageJsonPath));
                                 if (packageJsonContent) {
-                                    const mainFile = packageJsonContent.main || packageJsonContent.typings;
-                                    if (mainFile) {
-                                        const mainExportFile = toPath(mainFile, moduleDirectory, getCanonicalFileName);
+                                    const mainFileRelative = packageJsonContent.typings || packageJsonContent.types || packageJsonContent.main;
+                                    if (mainFileRelative) {
+                                        const mainExportFile = toPath(mainFileRelative, packageRootPath, getCanonicalFileName);
                                         if (removeFileExtension(mainExportFile) === removeFileExtension(moduleFileName)) {
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Does this mean they're allowed to have different file extensions?  Also, does case matter?

Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Also, use `fullModulePathWithoutExtension`?

Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: Alright, I had to come up with a really contrived case to check the answers to these. Found that a) case _doesn't_ matter but file extensions _do_. Will update the code.

Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: Or rather, case sensitivity is based on the file system's case sensitivity

File: src/services/codefixes/importFixes.ts [hunk 5]
```diff
@@ -504,45 +504,114 @@ namespace ts.codefix {
...
+                        }
                     }
                 }
 
+                function getNodeModulePathParts(fullPath: string) {
+                    // If fullPath can't be valid module file within node_modules, returns undefined.
+                    // Example of expected pattern: /base/path/node_modules/[otherpackage/node_modules/]package/[subdirectory/]file.js
+                    // Returns indices:                       ^            ^                                   ^             ^
+
+                    let nodeModulesIndex = 0;
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: This is the *first* such index?

File: src/services/codefixes/importFixes.ts [hunk 6]
```diff
@@ -504,45 +504,114 @@ namespace ts.codefix {
...
+                    let topLevelPackageNameIndex = 0;
+                    let packageRootIndex = 0;
+                    let fileNameIndex = 0;
+
+                    enum States {
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: `const enum`?

File: src/services/codefixes/importFixes.ts [hunk 7]
```diff
@@ -504,45 +504,114 @@ namespace ts.codefix {
...
+                    }
+
+                    let partStart = 0;
+                    let partEnd = 0;
+                    let state = States.BeforeNodeModules;
+
+                    while (partEnd >= 0) {
+                        partStart = partEnd;
+                        partEnd = fullPath.indexOf("/", partStart + 1);
+                        const part = fullPath.substring(partStart, partEnd);
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: If the goal of doing everything with indices with indices was to avoid creating temporary strings, this should probably be created on demand (e.g. never in `States.NodeModules`) or, better still, "/node_modules" could be detected in-place.

Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: Sure.
