### PR TITLE
Fix getTypeAtLocation for `as const` to not issue a diagnostic

### LINKED ISSUE #34913: Using `getTypeAtLocation` on a const type reference creates a TS2304 diagnostic
**TypeScript Version:** 3.8.0-dev.20191102

**Search Terms:**

**Code**

```js
const ts = require('typescript');

const content = '0 as const';

const host = ts.createCompilerHost({})
const originalReadFile = host.readFile;
host.readFile = (fileName) => fileName === 'main.ts' ? content : originalReadFile(fileName);

const program = ts.createProgram({ host, rootNames: ['main.ts'], options: { types: [] } });
const typeChecker = program.getDiagnosticsProducingTypeChecker();
const sourceFile = program.getSourceFile('main.ts');

typeChecker.getTypeAtLocation(sourceFile.statements[0].expression.type)

console.log(program.getSemanticDiagnostics());
```

**Expected behavior:**

`getSemanticDiagnostics` to return an empty array

**Actual behavior:**

`TS2304: Cannot find name 'const'.`

Because of caching, it has noticeable effects only when `getSemanticDiagnostics` is called after `getTypeAtLocation`.

It happens only when internal `getDiagnosticsProducingTypeChecker` method is used, but I think it still might be undesirable and would be an issue if #28584 would be merged.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #34913

`checkAssertion` in the normal codepath avoids calling into `getTypeFromTypeNode` on the `const` in `as const` expressions, however the checker `getTypeAtLocation` API may invoke it directly. Previously, this'd cause as resolution error, as we'd resolve an (entirely unused) variable named `const` and return its' type. With this change, we instead return the type of the expression associated with the `const` (which should be more useful to API consumers, I hope, and prevents any spurious errors from being added).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11336,6 +11336,11 @@ namespace ts {
         function getTypeFromTypeReference(node: TypeReferenceType): Type {
             const links = getNodeLinks(node);
             if (!links.resolvedType) {
+                // handle LS queries on the `const` in `x as const` by resolving to the type of `x`
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: Instead of this shouldn't `getTypeOfNode` just check if it is `const` of ` as const` expression should forward it to correct node instead?

Comment (weswigham) [reply src/compiler/checker.ts]: Ehhhhhh, it _could_, but I'd rather push the handling to here, to prevent us from ever attempting to resolve the `const` in `as const` as a real type reference, however we may get there in the future.

**Comment by amcasey** [comment]
Is this related to https://github.com/microsoft/TypeScript/pull/36490?  I believe that PR was also about handling LS requests in larger spans (i.e. not just on identifiers).

**Comment by weswigham** [comment]
Not as far as I know - this is just about fixing us giving a bogus result (and adding a diagnostic) for the type of `const` in `x as const` when the LS requests the type at `const`.

**Comment by amcasey** [comment]
So it changes from wrong to right, rather than from nothing to something?  Makes sense.
