### PR TITLE
Fix unassignable properties by adding undefined with exactOptionalPropertyTypes

### LINKED ISSUE #44403: Issue a better error for exactOptionalPropertyTypes
A project under `--strict` will likely break in TypeScript 4.4, and it won't be obvious why.

```
foo/thing.ts:37:5 - error TS2322: Type 'SomeData | undefined' is not assignable to type 'SomeData'.
  Type 'undefined' is not assignable to type 'SomeData'.

37     data: data,
       ~~~~
```

What I would propose is that we give some better error message in these cases such as

```
The source property type 'SomeData | undefined' is not compatible with the target property type 'SomeData' under '--strictOptionalProperties'. Consider adding 'undefined' to the type of the target property.
```

This could then be given a quick fix.

We could give this error when

* The source property is optional and the target type includes `undefined`ness
* The types would otherwise be compatible if you were to remove the `undefined` from the target.

### PR DESCRIPTION
**Pull request by sandersn**
Provide a specific error and codefix for missing `undefined` in target types with `exactOptionalPropertyTypes: true`.

- The codefix skips paths starting with `lib.` and containing `node_modules`
- Codefixes cannot use an elaboration as a trigger code. And the codefix logically needs to fix all of the properties in the target at once. So the resulting error message is a little vague. It still relies on reading the elaboration to find out the *first* erroneous property.

Fixes #44403

### CODE REVIEW

**Comment by sandersn** [comment]
@iisaduan you might be interested in using this in your codefix tool when it's ready.

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+    });
+
+    function getPropertiesToAdd(file: SourceFile, pos: number, checker: TypeChecker): Symbol[] {
+        const sourceTarget = getSourceTarget(getErrorNode(file, pos), checker);
+        if (!sourceTarget) {
+            return [];
+        }
+        const { source: sourceNode, target: targetNode } = sourceTarget;
+        const target = checker.getTypeAtLocation(targetNode);
+        if (target.symbol?.declarations?.some(d => getSourceFileOfNode(d).fileName.match(/(node_modules|^lib\.)/))) {
```
Comment (DanielRosenwasser) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:51]: Pretty sure we have other code actions that know not to touch `node_modules` and `lib`. Is there some way you can look into reusing that logic here?

Comment (andrewbranch) [reply src/services/codefixes/addOptionalPropertyUndefined.ts:51]: There’s `program.isSourceFileFromExternalLibrary` which includes “files found by searching under node_modules” (not sure exactly what the difference is between this and “files in node_modules”).

I would also argue that maybe we shouldn’t run on `.d.ts` files at all since they’re likely to be autogenerated and overwritten during some other compilation or codegen step.

Comment (sandersn) [reply src/services/codefixes/addOptionalPropertyUndefined.ts:51]: In a word: no. There are one-offs scattered throughout the compiler+services but nothing in codefixes. I'll take the code from TODO comment scraping and move it to services/utilities.ts, so at least it'll be a *little* shared.

Comment (sandersn) [reply src/services/codefixes/addOptionalPropertyUndefined.ts:51]: Later: github doesn't always load comments, so I missed @andrewbranch 's and was replying to @DanielRosenwasser 's.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
I was surprised that neither of [these cases](https://www.staging-typescript.org/play?exactOptionalPropertyTypes=true&ts=4.4.0-pr-45032-3#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgFyiLECukAUFxjohQBmCSKACqDCqADeXUPNB4AtpBYM2fAOYBuOQshLYGfAH41GnDq4BfHvFzrQ7ScRYSpAXhl75y1aAAiAEEcABNiSAB3AIAaH1ADI3wWdjDIQT5IULjrXS5nCgA6RONQL1TQ9MzQ3SA) are covered:

```ts
// @exactOptionalPropertyTypes: true

interface User {
    name: string;
    email?: string;
}

const user: User = {
    name: "Andrew",
    email: undefined,
};

user.email = undefined;
```

File: tests/baselines/reference/strictOptionalProperties1.errors.txt [hunk 2]
```diff
@@ -1,44 +1,55 @@
...
         obj.b = undefined;
     }
     
     function f2(obj: { a?: string, b?: string | undefined }) {
         obj = obj;
         obj.a = obj.a;  // Error
         ~~~~~
-!!! error TS2322: Type 'string | undefined' is not assignable to type 'string'.
-!!! error TS2322:   Type 'undefined' is not assignable to type 'string'.
+!!! error TS2412: Type 'string | undefined' is not assignable to type 'string' with exactOptionalPropertyTypes: true. Consider adding 'undefined' to the type of the target.
```
Comment (sandersn) [inline tests/baselines/reference/strictOptionalProperties1.errors.txt:51]: this error is not obvious, but self-assignments of optional properties require adding `undefined`

File: tests/baselines/reference/strictOptionalProperties1.errors.txt [hunk 3]
```diff
@@ -100,8 +111,8 @@ tests/cases/compiler/strictOptionalProperties1.ts(119,5): error TS2411: Property
     function f4a(t1: [number, string?], t2: [number, string?, string?]) {
         t1 = t2;  // Wasn't an error, but should be
         ~~
-!!! error TS2322: Type '[number, string?, string?]' is not assignable to type '[number, string?]'.
-!!! error TS2322:   Target allows only 2 element(s) but source may have more.
+!!! error TS2375: Type '[number, string?, string?]' is not assignable to type '[number, string?]' with exactOptionalPropertyTypes: true. Consider adding 'undefined' to the types of the target's properties.
```
Comment (sandersn) [inline tests/baselines/reference/strictOptionalProperties1.errors.txt:114]: This error needs two fixes, and now we suggest one in the elaboration and the other as a codefix.

This is confusing because they appear to disagree, but I don't know that it's worth fixing.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -16753,24 +16755,29 @@ namespace ts {
                 let sourcePropType = getIndexedAccessTypeOrUndefined(source, nameType);
                 if (!sourcePropType) continue;
                 const propName = getPropertyNameFromIndex(nameType, /*accessNode*/ undefined);
-                const targetIsOptional = !!(propName && (getPropertyOfType(target, propName) || unknownSymbol).flags & SymbolFlags.Optional);
```
Comment (sandersn) [inline src/compiler/checker.ts:16756]: I moved this verbatim inside the new `else`

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -16753,24 +16755,29 @@ namespace ts {
...
-                const sourceIsOptional = !!(propName && (getPropertyOfType(source, propName) || unknownSymbol).flags & SymbolFlags.Optional);
-                targetPropType = removeMissingType(targetPropType, targetIsOptional);
-                sourcePropType = removeMissingType(sourcePropType, targetIsOptional && sourceIsOptional);
                 if (!checkTypeRelatedTo(sourcePropType, targetPropType, relation, /*errorNode*/ undefined)) {
                     const elaborated = next && elaborateError(next, sourcePropType, targetPropType, relation, /*headMessage*/ undefined, containingMessageChain, errorOutputContainer);
-                    if (elaborated) {
-                        reportedError = true;
-                    }
-                    else {
+                    reportedError = true;
```
Comment (sandersn) [inline src/compiler/checker.ts:16760]: driveby fix; reportedError was always set to true in this block, regardless of whether `elaborated` is true, and it's not checked anywhere in this block, so it's fine to set it at the top.

**Review by sandersn — COMMENTED** [review]
There should be 4 comments below unless github lost two.

**Comment by sandersn** [comment]
This is ready to review again; it was a surprising amount of work to add the two other cases that @andrewbranch pointed out.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -19583,6 +19597,15 @@ namespace ts {
             return isUnitType(type) || !!(type.flags & TypeFlags.TemplateLiteral);
         }
 
+        function getExactOptionalUnassignableProperties(source: Type, target: Type) {
+            return getPropertiesOfType(target)
+                .filter(targetProp => isExactOptionalPropertyMismatch(getTypeOfPropertyOfType(source, targetProp.escapedName), getTypeOfSymbol(targetProp)));
+        }
+
+        function isExactOptionalPropertyMismatch(source: Type | undefined, target: Type | undefined) {
+            return !!source && !!target && maybeTypeOfKind(source, TypeFlags.Undefined) && !!containsMissingType(target);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:19606]: I think I just didn’t realize how exactOptionalPropertyTypes was implemented, but it looks like this implies that we never make property types that contain _both_ `missingType` _and_ `undefinedType`. Because if we ever did, `containsMissingType(target)` would be insufficient for this check (you’d need to ensure the target _does_ contain `missingType` and _doesn’t_ contain `undefinedType`).

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+            const seen = new Map<string, true>();
+            return createCombinedCodeActions(textChanges.ChangeTracker.with(context, changes => {
+                eachDiagnostic(context, errorCodes, diag => {
+                    const toAdd = getPropertiesToAdd(diag.file, diag.start, checker);
+                    if (!toAdd.length) {
+                        return;
+                    }
+                    let untouched = true;
+                    for (const add of toAdd) {
+                        if (!addToSeen(seen, add.id + "")) {
```
Comment (andrewbranch) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:35]: Pretty sure I made `addToSeen` work with number keys so we could use symbol ids directly. Either way:

```suggestion
                        if (!addToSeen(seen, getSymbolId(add) + "")) {
```

**Review by andrewbranch — COMMENTED** [review]
Not a blocker, but these new diagnostics seem like perfect candidates for related diagnostics of `'{0}' was declared here.` Presumably “here” would be the result of `getSourceTarget`, and your codefix could actually pull the related diagnostic location out instead of calculating it there.

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [reply src/compiler/checker.ts:19606]: Let me test that.

**Comment by sandersn** [comment]
> seem like perfect candidates for related diagnostics of '{0}' was declared here. 

I'll take a look at how complicated that is. The first draft has some add-related-span code that runs afterward already. The two newer errors are separate from all the drill-down error code, though.

> , and your codefix could actually pull the related diagnostic location out instead of calculating it there.

Codefixes only get an error code and a span, not the actual diagnostic. I could change that but I don't have the time right now.

File: src/compiler/checker.ts (hunk 6 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:19606]: Yeah I believe union reduction specifically watches out for that.

File: src/compiler/diagnosticMessages.json [hunk 8]
```diff
@@ -1738,6 +1738,10 @@
         "category": "Error",
         "code": 2374
     },
+    "Type '{0}' is not assignable to type '{1}' with exactOptionalPropertyTypes: true. Consider adding 'undefined' to the types of the target's properties.": {
```
Comment (DanielRosenwasser) [inline src/compiler/diagnosticMessages.json:1741]: Possibly

```suggestion
    "Type '{0}' is not assignable to type '{1}' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.": {
```

Comment (DanielRosenwasser) [reply src/compiler/diagnosticMessages.json:1741]: here and below

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 9]
```diff
@@ -0,0 +1,137 @@
...
+                    if (!toAdd.length) {
+                        return;
+                    }
+                    let untouched = true;
+                    for (const add of toAdd) {
+                        if (!addToSeen(seen, getSymbolId(add))) {
+                            untouched = false;
+                        }
+                    }
+                    if (untouched) {addUndefinedToOptionalProperty(changes, toAdd);}
```
Comment (DanielRosenwasser) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:39]:
```suggestion
                    if (untouched) { addUndefinedToOptionalProperty(changes, toAdd); }
```

or

```suggestion
                    if (untouched) addUndefinedToOptionalProperty(changes, toAdd);
```

or

```suggestion
                    if (untouched) {
                        addUndefinedToOptionalProperty(changes, toAdd);
                    }
```

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 10]
```diff
@@ -0,0 +1,137 @@
...
+                });
+            }));
+        },
+    });
+
+    function getPropertiesToAdd(file: SourceFile, pos: number, checker: TypeChecker): Symbol[] {
+        const sourceTarget = getSourceTarget(getErrorNode(file, pos), checker);
+        if (!sourceTarget) {
+            return [];
```
Comment (DanielRosenwasser) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:48]:
```suggestion
            return emptyArray;
```

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 11]
```diff
@@ -0,0 +1,137 @@
...
+        }
+        const { source: sourceNode, target: targetNode } = sourceTarget;
+        const target = checker.getTypeAtLocation(targetNode);
+        const source = checker.getTypeAtLocation(sourceNode);
+        if (target.symbol?.declarations?.some(d => getSourceFileOfNode(d).fileName.match(/\.d\.ts$/))) {
+            return [];
```
Comment (DanielRosenwasser) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:54]:
```suggestion
            return emptyArray;
```

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 12]
```diff
@@ -0,0 +1,137 @@
...
+        }
+        const targetPropertyType = getTargetPropertyType(checker, targetNode);
+        if (targetPropertyType && checker.isExactOptionalPropertyMismatch(source, targetPropertyType)) {
+            const s = checker.getSymbolAtLocation((targetNode as PropertyAccessExpression).name);
+            return s ? [s] : [];
```
Comment (DanielRosenwasser) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:59]:
```suggestion
            return s ? [s] : emptyArray;
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
@weswigham can you provide an opinion on the way I've added errors in/around the dril-down error code? I'm not super happy with the way it works.

File: src/services/codefixes/addOptionalPropertyUndefined.ts (hunk 9 above)
Comment (sandersn) [reply src/services/codefixes/addOptionalPropertyUndefined.ts:39]: Argh, I thought our linter had opinions on this! And would fix it for me!

**Comment by sandersn** [comment]
I didn't see any changes in the perf tests.

**Review by andrewbranch — APPROVED** [review]

File: tests/baselines/reference/strictOptionalProperties1.errors.txt [hunk 13]
```diff
@@ -1,44 +1,62 @@
...
+tests/cases/compiler/strictOptionalProperties1.ts(20,9): error TS2412: Type 'undefined' is not assignable to type 'string' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.
+tests/cases/compiler/strictOptionalProperties1.ts(28,9): error TS2412: Type 'undefined' is not assignable to type 'string' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.
+tests/cases/compiler/strictOptionalProperties1.ts(53,5): error TS2412: Type 'undefined' is not assignable to type 'string' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.
 tests/cases/compiler/strictOptionalProperties1.ts(60,5): error TS2322: Type 'undefined' is not assignable to type 'string'.
-tests/cases/compiler/strictOptionalProperties1.ts(64,5): error TS2322: Type '[number, string?, string?]' is not assignable to type '[number, string?]'.
+tests/cases/compiler/strictOptionalProperties1.ts(64,5): error TS2375: Type '[number, string?, string?]' is not assignable to type '[number, string?]' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
```
Comment (weswigham) [inline tests/baselines/reference/strictOptionalProperties1.errors.txt:8]: The suggestion would appear to be not so correct for tuples?

**Review by weswigham — COMMENTED** [review]
Adding a new error code for ease of quickfix seems fine, however the suggestion in the new error message would appear to be sometimes wrong (?) for tuple comparisons (because strict length checks will still make comparisons fail). Does exactOptionalProperties mode need to explicitly prioritize the tuple length error over any member errors?

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Tested this with @iisaduan’s codefix tool on microsoft/playwright and it crashed:

```
Using TypeScript 4.4.0-insiders.20210803
Found 253 diagnostics in 443 files
(node:22973) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at getSourceTarget (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:143993:61)
    at getPropertiesToAdd (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:143931:32)
    at Object.getCodeActions (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:143897:29)
    at /Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:143229:77
    at Object.flatMap (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:713:25)
    at Object.getFixes (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:143229:23)
    at /Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:157708:35
    at Object.flatMap (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:713:25)
    at Object.getCodeFixesAtPosition (/Users/anbranc/Developer/microsoft/playwright/node_modules/typescript/lib/typescript.js:157706:23)
    at /Users/anbranc/Developer/microsoft/ts-fix/dist/index.js:168:28
```

I can get you the code it was processing momentarily.

**Comment by andrewbranch** [comment]
The failure was on an error here: https://github.com/microsoft/playwright/blob/3e05d8e9fa54ea11def912b69228116b3a431f42/src/server/snapshot/snapshotterInjected.ts#L124

The actual error node is the whole LHS of the assignment:

image

but the code assumes that the `errorNode` is the Identifier `ensureCachedData`. Consequently, `errorNode.parent.arguments.indexOf(errorNode)` is `-1`, so crashes at `n.valueDeclaration.parameters[i].name`.

File: tests/baselines/reference/strictOptionalProperties1.errors.txt (hunk 13 above)
Comment (sandersn) [reply tests/baselines/reference/strictOptionalProperties1.errors.txt:8]: I went back and forth on this since at first I thought it was *technically* correct (the best kind) but now I'm not so sure. I put the tuple exclusion back in.

**Comment by sandersn** [comment]
I went poking through other codefix's code and found `getFixableErrorSpanExpression`, so I moved that to services/utilities and started using it.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@sandersn it now crashes here: https://github.com/microsoft/playwright/blob/869f8d541b60fae388637e83243a642b0f225e4b/src/server/network.ts#L352

image

`errorNode` in your codefix is the ObjectLiteralExpression. `i` is `0`. `n.valueDeclaration` is the PropertyDeclaration:

```ts
private _finishedPromiseCallback: (arg: { error?: string }) => void = () => {};
```

**Comment by andrewbranch** [comment]
I wrapped each individual request for codefixes in a try/catch and there was one other place in playwright that failed with the same crash. Otherwise, what became apparent is there are still a lot of assignability errors that this codefix doesn’t cover, because we started out with 253 errors (8 were due to me failing to run some codegen as part of the build, I think), and after applying this codefix across all files _repeatedly until it was no longer offered_ (except for the two places that crashed), we actually went _up_ to 404 errors.

Possible conclusions:

* We should attempt to identify a lot more assignability errors as fixable with this codefix
* #44419 is probably not feasible for large/complex projects (which is where it would be valuable)

If you want to see what unfixable errors remaining after running the tool, I’ve committed them to a fork (one commit per run, and each run actually does two passes of codefixes when it discovers overlapping changes): https://github.com/andrewbranch/playwright/tree/exactOptionalPropertyTypes

**Comment by sandersn** [comment]
Another possible conclusion:

We need more analysis of the new errors to figure out how the codefix causes the new errors. I thought that adding `undefined` wouldn't change anything since that used to be the semantics, but it sounds like I was wrong.

In the meantime, we need to decide between shipping a half-baked codefix or not. We've done this before! But for a new pedantic feature, I don't think we'll do much better than codemods written by the experts who adopt new features. So I'm leaning toward not shipping it.

@DanielRosenwasser do you have an opinion about this?

**Comment by andrewbranch** [comment]
I thought that adding `undefined` wouldn't change anything since that used to be the semantics, but it sounds like I was wrong.

I believe the deal is that if you naively add `| undefined` to _every_ optional property, you wind up with no errors, minus the ones you couldn’t change because they were in node_modules etc. But the codefix doesn’t want to add `| undefined` to every optional property; it just does the ones that it identifies as needing to change. [Here’s](https://www.staging-typescript.org/play?exactOptionalPropertyTypes=true&ts=4.4.0-pr-45032-20#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgFyiLECukAUDxjohQBmCSKACCARlABvLqFCwA-CwZs+Ac1AAfUDnYBbAEYUA3FwC+vfkJHiATDLkLloVcQ3bQhrFnyRYOGaWXHwCxMLwogBCoDACOAAmDOISADT2jvJKKmo46kE8CZDw+LDEon6IXixRZoYAdLCgALyg7ImQgnyQCWZAA) an example of a contrived program with one fixable error that turns into two unfixable ones upon being fixed.

```ts
// @exactOptionalPropertyTypes: true

interface A1 {
  a?: string | number;
}

interface A2 {
  a?: string | boolean;
}

interface B extends A1, A2 {
  a?: string;
}

declare let b: B;
b.a = undefined;
//^^ Type 'undefined' is not assignable to type 'string' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the type of the target.
```

Fixing the property assignment adds an “incorrectly extends” error for each of `B`’s extended interfaces.

**Comment by sandersn** [comment]
I took a look at your branch and got 443 errors (!). 213 of those used the new errors, but I guess didn't offer a codefix.

I'm looking at the errors right now.

**Comment by sandersn** [comment]
I think this is the wrong way to fix exactOptionalPropertyTypes errors. Applying the fix produces errors that (1) occur a long way from the true cause (2) penalises slightly-bad code like having structurally related types with no extends clause, or combining options types with a bunch of type arithmetic.

I think the better fix is to unconditionally add `| undefined` to all optional properties, and then have a human look at the diff and decide which places should not allow undefined.

The new error messages are *often* correct, so it might be worthwhile to leave them. However, I'm not sure their advice is clear enough without a codefix to back them up.

File: src/services/codefixes/addOptionalPropertyUndefined.ts [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+            return emptyArray;
+        }
+        const { source: sourceNode, target: targetNode } = sourceTarget;
+        const target = checker.getTypeAtLocation(targetNode);
+        const source = checker.getTypeAtLocation(sourceNode);
+        if (target.symbol?.declarations?.some(d => getSourceFileOfNode(d).fileName.match(/\.d\.ts$/))) {
+            return emptyArray;
+        }
+        const targetPropertyType = getTargetPropertyType(checker, targetNode);
+        if (targetPropertyType && checker.isExactOptionalPropertyMismatch(source, targetPropertyType)) {
```
Comment (sandersn) [inline src/services/codefixes/addOptionalPropertyUndefined.ts:59]: maybe find parent type and fix all, like the other cases

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
I think this is ready now. I simplified the fix to add `| undefined` to *all* properties in a type, regardless of whether the source could assign undefined to it, because that's more likely to result in a working build afterward.

And I got rid of the fix-all, since it's not a good idea. Thanks @amcasey for suggesting this.

**Comment by andrewbranch** [comment]
@typescript-bot pack this one last time please 🙃
