### PR TITLE
Specified diagnostic for CLI flags mismatched with/out --build

### LINKED ISSUE #43196: Misleading "Unknown compiler option '--clean'" when --build not provided
# Bug Report

### 🔎 Search Terms

unknown clean build option

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the CLI

### ⏯ Playground Link

N/A

### 💻 Code

```
tsc --clean
```

### 🙁 Actual behavior

```
tsc --clean
error TS5023: Unknown compiler option '--clean'.
```

### 🙂 Expected behavior

Something indicating the option is known _but_ requires `--build`?

```
tsc --clean
error TS5023: Compiler option '--clean' may only be used with '-b'/'--build'.
```

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #43196

Goes off the list of flags in https://www.typescriptlang.org/docs/handbook/project-references.html#tsc--b-commandline that require `--build`. That may change soon if #43193 is resolved.

### CODE REVIEW

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
I think it would be better for parse command line worker to take other options map and diagnostics to check of option is from different list so that build and non build both can report errors on options that are only available in other mode

File: src/compiler/types.ts [hunk 1]
```diff
@@ -6123,8 +6123,15 @@ namespace ts {
...
 
+    /* @internal */
+    export interface AlternateModeDiagnostics {
+        diagnostic: DiagnosticMessage;
+        options: ReadonlySet<string>;
+    }
+
     /* @internal */
     export interface DidYouMeanOptionsDiagnostics {
+        alternateMode?: AlternateModeDiagnostics;
```
Comment (sheetalkamat) [inline src/compiler/types.ts:6134]: Optional here but not in `ParseCommandLineWorkerDiagnostics`
Also these can just be two fields:
`alternateOptionsDeclarations` (pass from both compiler and build options (the opposite option declarations) you should need to create new set. 
`alternateOptionDiagnostic`

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/compiler/types.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply src/compiler/types.ts:6134]: @sheetalkamat I'm not following, sorry -- is there a reason the other modes should have this feature as well? I'd made this an optional object with required fields so to not change the type acquisition or watch mode options.

Comment (sheetalkamat) [reply src/compiler/types.ts:6134]: You would need this when running tsc with build and option isnt supported with build?

Comment (JoshuaKGoldberg) [reply src/compiler/types.ts:6134]: Agreed - I can add an _"{0} is only supported in build mode"_ error for those. I think for type acquisition and watch mode options it'd be cleaner to not require this?

Comment (JoshuaKGoldberg) [reply src/compiler/types.ts:6134]: Done, thanks for the feedback @sheetalkamat!

I ended up making granular arrays for the lists of configurations so the CLI parser could use `.map(option => option.name)` in places instead of hardcoded lists.

File: src/compiler/commandLineParser.ts [hunk 2]
```diff
@@ -1456,6 +1468,10 @@ namespace ts {
 
     /*@internal*/
     export const compilerOptionsDidYouMeanDiagnostics: ParseCommandLineWorkerDiagnostics = {
+        alternateMode: {
+            diagnostic: Diagnostics.Compiler_option_0_may_only_be_used_with_build,
```
Comment (sheetalkamat) [inline src/compiler/commandLineParser.ts:1472]: Because this is not going to be normal flow, rather use `getOptionsNameMap` that reuses map instead of creating new set/map

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/compiler/types.ts [hunk 3]
```diff
@@ -6123,8 +6123,15 @@ namespace ts {
         type: ESMap<string, number | string>;  // an object literal mapping named values to actual values
     }
 
+    /* @internal */
+    export interface AlternateModeDiagnostics {
+        diagnostic: DiagnosticMessage;
+        options: ReadonlySet<string>;
```
Comment (sheetalkamat) [inline src/compiler/types.ts:6129]: I meant this should be `getOptionsNameMap` and reuse those maps we create instead of creating new one

File: src/compiler/types.ts [hunk 4]
```diff
@@ -6123,8 +6123,15 @@ namespace ts {
...
 
+    /* @internal */
+    export interface AlternateModeDiagnostics {
+        diagnostic: DiagnosticMessage;
+        options: ReadonlySet<string>;
+    }
+
     /* @internal */
     export interface DidYouMeanOptionsDiagnostics {
+        getAlternateMode?: () => AlternateModeDiagnostics;
```
Comment (sheetalkamat) [inline src/compiler/types.ts:6134]: This doesnt need to be function

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/compiler/types.ts (hunk 3 above)
Comment (JoshuaKGoldberg) [reply src/compiler/types.ts]: Aha! I think I understand, thank you for this!

Comment (JoshuaKGoldberg) [reply src/compiler/types.ts]: (if 660a99e is not what you meant then I am thoroughly stumped and apologetic)

**Review by sheetalkamat — APPROVED** [review]
