### PR TITLE
use 'allowGeneratedIdentifiers' to explicitly tell when identifier can b...

### LINKED ISSUE #2350: Incorrect emit for a property assignment referencing a renamed let
```ts
var x;
if (true) {
    let x;
    var obj1 = { x: x }; // Should be { x: _x }, emits as { _x: _x }
    var obj2 = { x }; // Should be { x: _x }, emits as { _x: x }
}
```

The problem is that we are doing this rename in emitIdentifier, and we are not being picky enough about where we rename. Property names should never be renamed, and identifier references should always be renamed.

### PR DESCRIPTION
**Pull request by vladima**
...e renamed, Fixes #2350

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -2074,19 +2074,19 @@ module ts {
                     sourceMapDir = getDirectoryPath(normalizePath(jsFilePath));
                 }
 
-                function emitNodeWithSourceMap(node: Node) {
+                function emitNodeWithSourceMap(node: Node, allowGeneratedIdentifiers?: boolean) {
                     if (node) {
                         if (nodeIsSynthesized(node)) {
-                            return emitNodeWithoutSourceMap(node);
+                            return emitNodeWithoutSourceMap(node, /*allowGeneratedIdentifiers*/ false);
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: Add comment

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -2074,19 +2074,19 @@ module ts {
...
                         if (node.kind != SyntaxKind.SourceFile) {
                             recordEmitNodeStartSpan(node);
-                            emitNodeWithoutSourceMap(node);
+                            emitNodeWithoutSourceMap(node, allowGeneratedIdentifiers);
                             recordEmitNodeEndSpan(node);
                         }
                         else {
                             recordNewSourceFileStart(<SourceFile>node);
-                            emitNodeWithoutSourceMap(node);
+                            emitNodeWithoutSourceMap(node, /*allowGeneratedIdentifiers*/ false);
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: Add small comment

File: src/compiler/emitter.ts [hunk 3]
```diff
@@ -3897,8 +3917,7 @@ module ts {
                     renameNonTopLevelLetAndConst(name);
                     if (name.parent && (name.parent.kind === SyntaxKind.VariableDeclaration || name.parent.kind === SyntaxKind.BindingElement)) {
                         emitModuleMemberName(<Declaration>name.parent);
-                    }
-                    else {
+                    } else {
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: Fix this

File: src/compiler/emitter.ts [hunk 4]
```diff
@@ -5340,7 +5359,7 @@ module ts {
                 emitLeadingComments(node.endOfFileToken);
             }
 
-            function emitNodeWithoutSourceMapWithComments(node: Node): void {
+            function emitNodeWithoutSourceMapWithComments(node: Node, allowGeneratedIdentifiers?: boolean): void {
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: Use default value

File: src/compiler/emitter.ts [hunk 5]
```diff
@@ -5354,14 +5373,14 @@ module ts {
...
-                emitJavaScriptWorker(node);
+                emitJavaScriptWorker(node, (allowGeneratedIdentifiers === undefined) || allowGeneratedIdentifiers);
 
                 if (emitComments) {
                     emitTrailingComments(node);
                 }
             }
 
-            function emitNodeWithoutSourceMapWithoutComments(node: Node): void {
+            function emitNodeWithoutSourceMapWithoutComments(node: Node, allowGeneratedIdentifiers?: boolean): void {
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: add default value

File: src/compiler/emitter.ts [hunk 6]
```diff
@@ -5400,11 +5419,11 @@ module ts {
                 return true;
             }
 
-            function emitJavaScriptWorker(node: Node) {
+            function emitJavaScriptWorker(node: Node, allowGeneratedIdentifiers: boolean) {
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: I would actually put the default value here instead of the two callers.

**Comment by JsonFreeman** [comment]
:+1:
