### PR TITLE
fix(39676): Default code action for unused function parameter (6133) in non-final position should not delete

### LINKED ISSUE #39676: Default code action for unused function parameter (6133) in non-final position should not delete
**TypeScript Version:**  3.9.6

**Search Terms:**
6133, unused parameter, quick fix, code action, tsserver

**Code**

```ts
const express = require('express')
const unusedImport = require('fs')
const anotherUnusedImport = require('util')
const app = express()
const port = 3000

app.get('/', helloWorld)
app.get('/used', (req, res) => res.send('used'))

function helloWorld(unusedReq, res) {
    return res.send('Hello World!');
}

function unusedFunction() {
}

app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))
```

**Expected behavior:**

If I apply the code action "Delete all unused declarations" to "unusedImport", it, "anotherUnusedImport" and "unusedFunction" should be deleted, but nothing else.

**Actual behavior:**

The parameter "unusedReq" in helloWorld is also deleted, but the line `app.get('/', helloWorld)` is not modified.

The unread `req` parameter in `app.get('/used', (req, res) => res.send('used'))` is correctly not removed.

If I were to change the line to `app.get('/', (req, res, next) => helloWorld(req, res, next))` it would be adjusted correctly, but using the function directly with a changed parameter set changes the behaviour.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39676

### CODE REVIEW

File: src/services/codefixes/fixUnusedIdentifier.ts [hunk 1]
```diff
@@ -238,29 +236,26 @@ namespace ts.codefix {
...
+    function mayDeleteParameter(checker: TypeChecker, sourceFile: SourceFile, parameter: ParameterDeclaration, isFixAll: boolean): boolean {
+        const { parent } = parameter;
         switch (parent.kind) {
             case SyntaxKind.MethodDeclaration:
                 // Don't remove a parameter if this overrides something.
                 const symbol = checker.getSymbolAtLocation(parent.name)!;
                 if (isMemberSymbolInBaseType(symbol, checker)) return false;
                 // falls through
-
             case SyntaxKind.Constructor:
```
Comment (sandersn) [inline src/services/codefixes/fixUnusedIdentifier.ts:247]: don't constructors have the same constraints as functions? I don't understand why the new restriction only applies to named functions used "like a callback".

**Review by sandersn — CHANGES_REQUESTED** [review]
From the bug it looks like the codefix should only ever apply to non-final parameters. Are there cases where non-final parameters are correctly deleted today?

File: src/services/codefixes/fixUnusedIdentifier.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/codefixes/fixUnusedIdentifier.ts:247]:
```ts
declare function fn(cb: (x: number, y: string) => void): void;
```

```ts
fn((a, b) => b);
```
`a` will not be removed, because there is a condition to handle that. however, this condition is not applying to `FunctionDeclaration` which can be used as a callback too.

https://github.com/microsoft/TypeScript/blob/2b0278a88f766e87bd0fb839b1048d1e17894969/src/services/codefixes/fixUnusedIdentifier.ts#L254-L263

```ts
function callback(a: number, b: number) { b; };
fn(callback); 
```
`a` will be removed because when the QF checks the possibility to remove parameters for `FunctionDeclaration` it 
always allows that 

https://github.com/microsoft/TypeScript/blob/2b0278a88f766e87bd0fb839b1048d1e17894969/src/services/codefixes/fixUnusedIdentifier.ts#L251-L252

as a result,  

```ts
function callback(b: number) { b; };
fn(callback); 
```
However, deleting `a` has to be disallowed for that case. About constructors, not sure, maybe there are some cases where we need to apply the same logic as for `FunctionDeclaration`.

Comment (sandersn) [reply src/services/codefixes/fixUnusedIdentifier.ts:247]: ok, that makes sense. I think that eventually we'll want to expand the restrictions, or make parameter deletion smarter.

**Review by sandersn — APPROVED** [review]
