### PR TITLE
Correctly check for 'delete' on optional properties in 'exactOptionalPropertyTypes'.

### LINKED ISSUE #44852: exactOptionalPropertyTypes: delete triggers error on optional property
# Bug Report

The fix in https://github.com/microsoft/TypeScript/pull/44612 doesn't look to work as expected.  When there is an optional property and `exactOptionalPropertyTypes` is enabled, `delete` will now show an error for properties marked with `?`.

### 🔎 Search Terms
exactOptionalPropertyTypes
exactOptionalPropertyTypes

### 🕗 Version & Regression Information

The 6/30 nightly build

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.0-dev.20210701&exactOptionalPropertyTypes=true#code/CYUwxgNghgTiAEYD2A7AzgF3kgRgKwC54BvUAMwEsUKMQIBPACRDgFkp6cQBVFcqkMAD8RFAFcAtlxgBfANwAoBaAgha2fADp+1Wg2ZsOXXjsGKgA

The `exactOptionalPropertyTypes` flag doesn't preserve in the linked example, so you'll need to expand TS Config and select it again.

### 💻 Code

```ts
declare const obj: {definitelyHereMaybeUndefined?: number};

delete obj.definitelyHereMaybeUndefined;
```

### 🙁 Actual behavior

The delete line gives the following error with `exacteOptionalPropertyTypes` enabled.

`The operand of a 'delete' operator must be optional.`

### 🙂 Expected behavior

I don't expect there to be an error on this line since the property being deleted is already marked as optional.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #44852

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
CC @a-tarasyuk

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -31402,16 +31402,16 @@ namespace ts {
...
             return booleanType;
         }
 
-        function checkDeleteExpressionMustBeOptional(expr: AccessExpression, type: Type) {
+        function checkDeleteExpressionMustBeOptional(expr: AccessExpression, symbol: Symbol) {
+            const type = getTypeOfSymbol(symbol);
             if (strictNullChecks &&
                 !(type.flags & (TypeFlags.AnyOrUnknown | TypeFlags.Never)) &&
-                !(exactOptionalPropertyTypes ? 0 : getFalsyFlags(type) & TypeFlags.Undefined)) {
+                !(exactOptionalPropertyTypes ? hasQuestionToken(symbol.valueDeclaration!) : getFalsyFlags(type) & TypeFlags.Undefined)) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:31414]: This isn't going to work for a type such as `Partial<{ a: string }>`. You should just check `symbol.flags & SymbolFlags.Optional`.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:31414]: Just opened https://github.com/microsoft/TypeScript/pull/44862
