### PR TITLE
fix(41868): Infer parameter from usage does not work on arrow functions that are a PropertyDeclaration of a Class

### LINKED ISSUE #41868: Infer parameter from usage does not work on arrow functions that are a PropertyDeclaration of a Class
**Code**

```ts
class MyClass {
    foo = (a, b, c) => {};
}

function bar(x: MyClass) {
    x.foo("a", 2, "hello");
}
```

Request with the code above to infer all types from usage.

**Expected behavior:**
```ts
class MyClass {
    foo = (a: string, b: number, c: string) => {};
}
```

**Actual behavior:**
```ts
class MyClass {
    foo = (a: any, b: any, c: any) => {};
}
```

**Related Issues:**
#41827 

I already have implemented a solution, just creating an issue to keep this documented.

### PR DESCRIPTION
**Pull request by Leulz**
Fixes #41868

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/codefixes/inferFromUsage.ts [hunk 1]
```diff
@@ -161,7 +161,7 @@ namespace ts.codefix {
                     declaration = containingFunction;
                     break;
                 }
-                // falls through
+            // falls through
```
Comment (DanielRosenwasser) [inline src/services/codefixes/inferFromUsage.ts:164]: Can you revert this?

```suggestion
                // falls through
```

Comment (Leulz) [reply src/services/codefixes/inferFromUsage.ts]: Done, thanks for the rev!

**Comment by Leulz** [comment]
@DanielRosenwasser @sandersn Sorry to disturb you, but this is my first PR here and I'm just wondering if there's something missing for it to be reviewed.

**Review by sandersn — APPROVED** [review]
