### PR TITLE
Fix two module specifier ending preference detection issues

### LINKED ISSUE #52167: Typescript file imports being appended with `.js` extensions intermittently
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.74.2
- OS Version: macOS Monterey 12.6

Steps to Reproduce:

1. Commented out all of my `settings.json` file, so uses the default settings
2. Restart VSCode with Extensions Disabled
3. In certain `.ts` files in my project, when I go to import another `.ts` file the autocomplete option for the import adds a `.js` file extension.
4. The same import made in another `.ts` file in the same directory or another directory, does not append the `.js` file extension.
5. Sometimes in the `.ts` file(s) that appends the `.js` file extension on the auto import, when I remove all of the code and then try to import, it does not append the `.js` extension. But if I close the file and re-open it again, it will. But this is intermittent.
6. See Videos below for issue
  - Sorry, had to split in 2 due to file sizes

https://user-images.githubusercontent.com/20436343/210012132-a6682005-5d22-485b-9e1b-cf617f3ffd1f.mov

https://user-images.githubusercontent.com/20436343/210012161-49604216-5ff5-4ee9-b0f8-de3b83458857.mov

Not sure how much the `tsconfig.json` file can affect this but this is my ts config.

```json
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true /* Report errors on unused locals. */,
    "noUnusedParameters": true /* Report errors on unused parameters. */,
    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["next-env.d.ts", "types/**/*.ts", "next-auth.d.ts", "**/*.ts", "**/*.tsx", "**/*.js", "**/*.cjs", "**/*.mjs"],
  "exclude": ["node_modules"]
}
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #52167

### CODE REVIEW

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -147,7 +147,9 @@ function getPreferences(
                 return [ModuleSpecifierEnding.JsExtension];
             }
             if (getEmitModuleResolutionKind(compilerOptions) === ModuleResolutionKind.Classic) {
-                return [ModuleSpecifierEnding.Index, ModuleSpecifierEnding.JsExtension];
+                return preferredEnding === ModuleSpecifierEnding.JsExtension
+                    ? [ModuleSpecifierEnding.JsExtension, ModuleSpecifierEnding.Index]
+                    : [ModuleSpecifierEnding.Index, ModuleSpecifierEnding.JsExtension];
```
Comment (andrewbranch) [inline src/compiler/moduleSpecifiers.ts:152]: This change alone fixes the issue reported by @jespertheend in #52167, which was different from the OP’s issue. When `--moduleResolution` is `classic` (the unfortunate default of `--module esnext`, we simply weren’t respecting the inferred preference. `classic` resolution doesn’t support dropping `/index.js` suffixes, which is why it gets its own if block here that never returns `ModuleSpecifierEnding.Minimal`.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -9156,7 +9158,9 @@ export const enum ModuleSpecifierEnding {
 
 /** @internal */
 export function usesExtensionsOnImports({ imports }: SourceFile, hasExtension: (text: string) => boolean = or(hasJSFileExtension, hasTSFileExtension)): boolean {
-    return firstDefined(imports, ({ text }) => pathIsRelative(text) ? hasExtension(text) : undefined) || false;
+    return firstDefined(imports, ({ text }) => pathIsRelative(text) && !fileExtensionIsOneOf(text, extensionsNotSupportingExtensionlessResolution)
+        ? hasExtension(text)
+        : undefined) || false;
```
Comment (andrewbranch) [inline src/compiler/utilities.ts:9163]: This change, and the similar one below, fixes the main issue of #52167. This code is used to detect a preference for module specifier endings from existing imports in a file. Previously, any relative-path module specifier that included an extension was taken as an indication that the user prefers including extensions. However, only `.js`/`.ts` extensions can ever be omitted—if an extension included `.mjs` or `.cjs`, for example, that cannot indicate a _preference_ of the user because that file extension was _required_ to make the import resolve. So we need to skip those if we’re looking for clues as to what the user prefers; we can only infer a preference if the user had a choice.

If you look at the (video) repro in #52167, one of the existing imports in the big file had a `.mjs` extension, which caused a new import added in that file to include an extension. When the user tried the same auto-import in an empty file, the import excluded the optional extension, because that’s the default in absence of any evidence that the user wants extensions.

**Review by sheetalkamat — APPROVED** [review]

**Review by gabritto — APPROVED** [review]
