### PR TITLE
Fix unwanted constant comparisons potentially causing bugs

### LINKED ISSUE #61654: Unwanted constant comparisons potentially causing bugs
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I was running `npx oxlint src -A all -D const-comparisons` to test oxlint and unintentionally discovered some unwanted constant comparisons potentially causing bugs:

https://github.com/microsoft/TypeScript/blob/d88d3a46810bfae0b072beb023a2b09b8026b82c/src/compiler/resolutionCache.ts#L327

https://github.com/microsoft/TypeScript/blob/d88d3a46810bfae0b072beb023a2b09b8026b82c/src/harness/fourslashImpl.ts#L2603

Both conditions will always be false.

### PR DESCRIPTION
**Pull request by ulrichstark**
Fixes #61654

### CODE REVIEW

**Comment by ulrichstark** [comment]
@microsoft-github-policy-service agree

File: src/harness/fourslashImpl.ts [hunk 1]
```diff
@@ -2600,7 +2600,7 @@ export class TestState {
         sorted.sort((q1, q2) =>
             q1.marker.fileName === q1.marker.fileName
```
Comment (IllusionMH) [inline src/harness/fourslashImpl.ts:2601]: Isn't it the same issue with 2 `q1`? Also, looks like it should prevent reaching fixed line completely.

**Review by andrewbranch — APPROVED** [review]

**Review by sandersn — APPROVED** [review]
