### PR TITLE
Fix jsdoc typedef symbol scope + avoid bind twice if the type has a namespace prefix

### LINKED ISSUE #12233: JSdoc+Intellisense. @typedef include in function description
_From @IgorNovozhilov on November 11, 2016 12:37_

- VSCode Version:

image

- OS Version: win7 pro

Steps to Reproduce:

`@typedef` tag include in a first function description after `@typedef`, and is not included in the function which describes this type
`@typedef` can be re used in other functions, and describe the same type before each function is incorrect.

code:

image

functions:

image

image

_Copied from original issue: Microsoft/vscode#15351_

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #12233

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1298,6 +1304,26 @@ namespace ts {
...
+            forEachChild(node, n => {
+                if (n.kind !== SyntaxKind.JSDocTypedefTag) {
+                    bind(n);
+                }
+            });
+        }
+
+        function bindJSDocTypedefTag(node: JSDocTypedefTag) {
+            forEachChild(node, n => {
+                // if the node has a fullName "A.B.C", that means symbol "C" was already bond
```
Comment (sandersn) [inline src/compiler/binder.ts]: typo:bound

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -1298,6 +1304,26 @@ namespace ts {
...
+                }
+            });
+        }
+
+        function bindJSDocTypedefTag(node: JSDocTypedefTag) {
+            forEachChild(node, n => {
+                // if the node has a fullName "A.B.C", that means symbol "C" was already bound
+                // when we visit "fullName"; so when we visit the name "C" as the next child of
+                // the jsDocTypedefTag, we should skip binding it.
+                if (n === node.name && node.fullName.kind !== SyntaxKind.Identifier) {
```
Comment (vladima) [inline src/compiler/binder.ts]: [this bit](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/parser.ts#L6707) implies that `fullName` can be undefined. Is this case handled?

Comment (zhengbli) [inline src/compiler/binder.ts]: That should be an parsing error. If parsed correctly, `fullName` should always has value. Will update

Comment (zhengbli) [inline src/compiler/binder.ts]: Aha I forgot the following case ... 
```
/* @typedef { string | number } */
var NumberLike;
```

It can be undefined after all.

Comment (vladima) [inline src/compiler/binder.ts]: can you add this as a testcase?

**Comment by zhengbli** [comment]
@vladima further comments?
