### PR TITLE
Bind RHS of comma expressions too

### LINKED ISSUE #44487: Comma Operator breaks Assertion Functions
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ssl=7&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABAOQIYCd1wO4B4AqAfABQBuqANiAKYBciqYAngJT2oDOH16UHi5KtUQx++RAG8AvgCgZoSLASIo1DlGLA4cdswA0iAEYZdrSTMSWUGLHjAgAtoZ4ktcFgbSYcudehhgAOYkxugsANwWVm7hiAD0cYhu9PZOPJFWRhixCVnoppFSQA)
    
### 💻 Code

```ts
function Narrow<T>(value: any): asserts value is T {}

function test(foo: any, bar: any) {
    Narrow<number>(foo), Narrow<string>(bar);
    foo; // foo: number;
    bar; // bar: any;
}
```

### 🙁 Actual behavior

`foo` is asserted as `number`, `bar` is asserted as  `string`. 
The type of `foo` becomes `number`, but the type of `bar` is still `any`.

### 🙂 Expected behavior

Type of `bar` to be narrowed to `string`.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #44487

This is an extension of #41312, applying `maybeBindExpressionFlowIfCall` the RHS too. The argument there was:

> just like lists of statements, they generally only exist to compose lists of possibly-side-effecting actions (like, say, assertions).

I'd argue that this means that the entire chain of items in a comma expression (of any size) should have this applied, since they are being thought of here as a list of statements with potential side effects, and not just the leftmost expression.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this
@typescript-bot user test this

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1574,6 +1574,11 @@ namespace ts {
             function onExit(node: BinaryExpression, state: WorkArea) {
                 if (!state.skip) {
                     const operator = node.operatorToken.kind;
+
+                    if (operator === SyntaxKind.CommaToken) {
```
Comment (weswigham) [inline src/compiler/binder.ts:1578]: Why would this be in `onExit` and not `onRight`?

Comment (jakebailey) [reply src/compiler/binder.ts:1578]: If you look up a bit, the `left` is processed in `onOperator`, presumably because there's some work that is completed after `onLeft` is completed. That's how it was added in #44487.

I tried putting it into `onRight` first and hit infinite recursion, then realized that the other call wasn't in `onLeft` and moved it down.

Comment (jakebailey) [reply src/compiler/binder.ts:1578]: Perhaps I can get away with moving these around, though, and try running them after `maybeBind` in `onLeft` and `onRight` instead. I'll try it. It'd sure look less weird.

Comment (jakebailey) [reply src/compiler/binder.ts:1578]: No, unfortunately this doesn't seem to work:

```ts
            function onLeft(left: Expression, state: WorkArea, _node: BinaryExpression) {
                if (!state.skip) {
                    const node = maybeBind(left);
                    if (left.kind === SyntaxKind.CommaToken) {
                        maybeBindExpressionFlowIfCall(left);
                    }
                    return node;
                }
            }
```

I don't quite understand the mechanics of the `BinaryExpressionStateMachine` thing, but it seems like `maybeBindExpressionFlowIfCall` needs to happen after `onLeft` and `onRight` have fully returned.

Comment (jakebailey) [reply src/compiler/binder.ts:1578]: Ignore this, I'm a fool and am checking the wrong node's kind.

Comment (jakebailey) [reply src/compiler/binder.ts]: I've moved things around to be a little less surprising.

**Review by weswigham — APPROVED** [review]
