### PR TITLE
Fix decorator emit regression for static fields

### LINKED ISSUE #44931: Invalid emit for class using decorators plus static properties that reference other static properties of the same class
# Bug Report

### 🔎 Search Terms

- tsc 
- emit 
- compiled

### 🕗 Version & Regression Information

Regression  from at least 4.4.0-dev.20210701 

Also tested in 4.4.0-dev.20210707

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=5&ts=4.4.0-dev.20210707#code/JYOwLgpgTgZghgYwgAgJIDED2nkG9kC+AUEQCYQIA2cUKCmIAzmGlpgFzJwgCeA3CSpxGjZACEArpQDWAUVLAwABVoA3YBADuKzOvJQ8JZMeTM4YYAmS04pBpR7IAyggAWEALZxkAXmQByVUZ6cgBaACMpaQgFMAAHNQ1NfwEiE1Mwc0tkTziwHhUIdS1fPFM3TwhOSRl5RULi7ShdYH0AOhd3L0JU9PomMCgJBDBMKAAKNPSTAAEMbGQE4FVzFBs7EAdkAH0PTHInaHUkTnnMABop4wBKMuICIA

### 💻 Code

```ts
interface IFoo { }
declare const IFoo: any;

class BulkEditPreviewProvider {

    static readonly Schema = 'vscode-bulkeditpreview';

    static emptyPreview = { scheme: BulkEditPreviewProvider.Schema };

    constructor(
        @IFoo private readonly _modeService: IFoo,
    ) { }
}
```

### 🐛  Bug
The compiled code for this is:

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var _a;
let BulkEditPreviewProvider = (_a = class BulkEditPreviewProvider {
        constructor(_modeService) {
            this._modeService = _modeService;
        }
    },
    _a.Schema = 'vscode-bulkeditpreview',
    _a.emptyPreview = { scheme: BulkEditPreviewProvider.Schema },
    _a);
BulkEditPreviewProvider = __decorate([
    __param(0, IFoo)
], BulkEditPreviewProvider);
```

The bug is that ` _a.emptyPreview = { scheme: BulkEditPreviewProvider.Schema },` uses `BulkEditPreviewProvider` before that variable is defined

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes an over-aggressive transformation for static fields when a class is decorated.

Fixes #44931

### CODE REVIEW

File: src/tsserver/nodeServer.ts [hunk 1]
```diff
@@ -256,7 +256,7 @@ namespace ts.server {
         /* eslint-enable no-restricted-globals */
 
         if (typeof global !== "undefined" && global.gc) {
-            sys.gc = () => global.gc!();
+            sys.gc = () => global.gc?.();
```
Comment (rbuckton) [inline src/tsserver/nodeServer.ts:259]: This is to address a frustrating lint error due to some combination of `@types/node`, TypeScript, and eslint. Without the postfix `!` I'll get a lint error in CI, with the postfix `!` I get a lint error locally. Using `?.()` seems to satisfy both, and we call this infrequently so the overhead of the null check is negligible.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by Kingwl** [comment]
thanks！
