### PR TITLE
Fix indentation of multiline conditional expressions

### LINKED ISSUE #40854: Wrong TSX ternary markup block formatting on save
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1.0-dev.20200930

**Search Terms**
- format
- tsx
- ternary
- Indent 

---

I like 'format on save' VSCode feature very much. But I'm experiencing a very annoying wrong formatting of **tsx** files (my current version is 1.49.2 (Linux), but I've been observing this for more than month).

Here is an example. Here two lines have extra indents ('single' block)

```tsx
import React from 'react';

const TestComponent = (props: { isList: boolean }) => {
  return (
    <div>
      {props.isList ? (
        <div>liiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiist</div>
      ) : (
          <div>siiiiiiiiiiiiiiiiiiiiiiiingle</div>
        )}
    </div>
  );
};

export default TestComponent;
```

the same code in **jsx** file is formatted correctly

```js
import React from 'react';

const TestComponent = props => {
  return (
    <div>
      {props.isList ? (
        <div>liiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiist</div>
      ) : (
        <div>siiiiiiiiiiiiiiiiiiiiiiiingle</div>
      )}
    </div>
  );
};

export default TestComponent;
```
I tried to switch default vscode formatter to `eslint`, `null`, `prettier` (user/workspace level) - doesn't help. 

When I run `prettier --write src/components/TestComponent.tsx` the tsx file is formatted correctly.

I also checked typescript-specific formatting settings in VS Code, but couldn't find anything related (for the test I've removed `.eslint.js` config file and my project doesn't have `.prettierrc` config)

Please let me know what else I should check/try?

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40854

### CODE REVIEW

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -323,6 +323,49 @@ namespace ts.formatting {
...
+        //
+        // (() => {
+        //   return complexCalculationForCondition();
+        // })() ? {
+        //   whenTrue: 'multiline object literal'
+        // } : (
+        //   whenFalse('multiline parenthesized expression')
+        // );
+        //
+        // In these cases, we must discard the indenation increase that would otherwise be applied to the
```
Comment (sandersn) [inline src/services/formatting/smartIndenter.ts:343]:
```suggestion
        // In these cases, we must discard the indentation increase that would otherwise be applied to the

```

**Review by sandersn — APPROVED** [review]
I agree with your teams discussion about this code -- the architecture causes you to write rules backward from the way that they should be specified. The amount of commenting you wrote is an indicator of that.

File: src/services/formatting/smartIndenter.ts [hunk 2]
```diff
@@ -323,6 +323,50 @@ namespace ts.formatting {
...
+        // (() => {
+        //   return complexCalculationForCondition();
+        // })() ? {
+        //   whenTrue: 'multiline object literal'
+        // } : (
+        //   whenFalse('multiline parenthesized expression')
+        // );
+        //
+        // In these cases, we must discard the indentation increase that would otherwise be applied to the
+
```
Comment (andrewbranch) [inline src/services/formatting/smartIndenter.ts:344]:
```suggestion
```
