### PR TITLE
Fix crash in goto-def on `@override`

### LINKED ISSUE #50892: Exception while resolving base type from JSDoc for `references` request
[odoo/odoo](https://github.com/odoo/odoo) [`getDefinitionFromOverriddenMember`](https://github.com/microsoft/TypeScript/blob/08b91f6b827e9ee98407c0eb969579ab77fa9f0c/src/services/goToDefinition.ts#L174) computes the error type (type id 4) for the base type and that type has no associated symbol.  The [node](https://github.com/odoo/odoo/blob/6bf6ce062aa4cfbb7efb96806cbfcfa13868337f/addons/web/static/src/legacy/js/control_panel/control_panel_model_extension.js#L139) in question is from jsdoc.

_Originally posted by @amcasey in https://github.com/microsoft/TypeScript/issues/50836#issuecomment-1254072749_

### PR DESCRIPTION
**Pull request by sandersn**
getDefinitionFromOverriddenMember previously assumed that getTypeOfSymbolAtLocation returned `undefined` for a missing type, not `errorType`. This fixes that.

Fixes #50892

### CODE REVIEW

**Comment by sandersn** [comment]
baselines must use getSymbolAtLocation because lots of them change. I'll look at them after the weekend and see if the changes will affect anything but baselines.

**Comment by sandersn** [comment]
I reverted the change to getSymbolAtLocation and I'll make that a separate PR, since it's more of an improvement in code readability and *possibly* in language service functionality.

**Comment by DanielRosenwasser** [comment]
@typescript-bot test tsserver top100

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/goToDefinition.ts [hunk 1]
```diff
@@ -171,13 +171,15 @@ namespace ts.GoToDefinition {
         if (!baseDeclaration) return;
 
         const baseTypeNode = getEffectiveBaseTypeNode(baseDeclaration);
-        const baseType = baseTypeNode ? typeChecker.getTypeAtLocation(baseTypeNode) : undefined;
-        if (!baseType) return;
+        if (!baseTypeNode) return;
+        const expression = skipParentheses(baseTypeNode.expression);
+        const base = isClassExpression(expression) ? expression.symbol : typeChecker.getSymbolAtLocation(expression);
```
Comment (DanielRosenwasser) [inline src/services/goToDefinition.ts:176]: Actually, why are you checking for `isClassExpression`? Can't you use `getDeclaredTypeOfSymbol`?

Comment (sandersn) [reply src/services/goToDefinition.ts:176]: I have to follow `Node -> Symbol -> Type`, and `getSymbolAtLocation` doesn't support (parenthesised) class expressions right now, although `getTypeAtLocation` does. I happen to know that class expressions have a symbol, though, so I can special-case the `Node -> Symbol` step for now.

I'm going to follow this PR with one that moves the paren/class-expr check into getTypeAtLocation, but it changes lots of our baselines since, apparently, we use it for type baselines.

**Comment by sandersn** [comment]
Half of the top100 failed to run, but the half that did has no new errors. I think that's good enough.
