### PR TITLE
Release the documents from language service using paths and keys

### LINKED ISSUE #37500: TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (c0eea2a712471a4d242d15704cfa968241d63280, 2020-03-19T09:21:46.589Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 7|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|-psn_0_20140852|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.4.10
vscode-mjml|att|1.6.0
markdown-checkbox|bie|0.1.3
markdown-preview-github-styles|bie|0.1.6
githistory|don|0.6.3
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
auto-rename-tag|for|0.1.1
applescript|idl|0.18.1
vscode-styled-components|jpo|0.0.28
python|ms-|2020.3.69010
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|4.0.1
vscode-yaml|red|0.7.2
jinjahtml|sam|0.12.0
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
jinja|who|0.0.8

(2 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by sheetalkamat**
This ensures that we are using correct path for the file as program might be created with different current directory than documentRegistry

Fixes #37500

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -1405,8 +1405,10 @@ namespace ts {
 
         function dispose(): void {
             if (program) {
+                // Use paths to ensure we are using correct key and paths as document registry could bre created with different current directory than host
+                const key = documentRegistry.getKeyForCompilationSettings(program.getCompilerOptions());
                 forEach(program.getSourceFiles(), f =>
-                    documentRegistry.releaseDocument(f.fileName, program.getCompilerOptions()));
+                    documentRegistry.releaseDocumentWithKey(f.resolvedPath, key));
```
Comment (amcasey) [inline src/services/services.ts]: Is this a new approach or just a bug fix?  Is the key already used when the document is added to the registry?

Comment (sheetalkamat) [reply src/services/services.ts]: This is not new approach as you see the method already exists and if you browse of other usages of methods of DocumentRegistry you would notice that they all use path and key.
