### PR TITLE
Fix late bound method name assignment, added tests

### LINKED ISSUE #41749: Crash with Error: Debug Failure. False expression. at getConstructorDefinedThisAssignmentTypes
**TypeScript Version:**  4.1.2, 4.2.0-dev.20201201

**Search Terms:**
Crash, @types/node, symbol, async method
**Code**
Trying to compile this code, while having `@types/node@14.0.13` installed and composite flag enabled causes a crash.
```ts
const symbol = Symbol('foo')

class Foo {
  constructor() {

    this[symbol] = this[symbol].bind(this)
  }

  async [symbol] () {
    
  }
}
```

**Expected behavior:**

Not crash

**Actual behavior:**

Crashes with:
```
Error: Debug Failure. False expression.
    at getConstructorDefinedThisAssignmentTypes (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41664:22)
    at getWidenedTypeForAssignmentDeclaration (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41515:67)
    at getTypeOfVariableOrParameterOrPropertyWorker (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41822:24)
    at getTypeOfVariableOrParameterOrProperty (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:41775:28)
    at getTypeOfSymbol (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:42079:24)
    at getPropertyTypeForIndexType (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:46121:36)
    at getIndexedAccessTypeOrUndefined (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:46427:20)
    at checkElementAccessExpression (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:56168:37)
    at checkIndexedAccess (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:56146:17)
    at checkExpressionWorker (/Users/dmaretskyi/Projects/typescript-bug/node_modules/typescript/lib/tsc.js:60004:28)
```

**Reproduction repo:** https://github.com/Marik-D/typescript-bug

**Related Issues:**

### PR DESCRIPTION
**Pull request by armanio123**
Fixes #41749

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -410,13 +410,17 @@ namespace ts {
...
-            Debug.assert(!hasDynamicName(node));
+        function declareSymbol(symbolTable: SymbolTable, parent: Symbol | undefined, node: Declaration, includes: SymbolFlags, excludes: SymbolFlags, isReplaceableByMethod?: boolean, isComputedName?: boolean): Symbol {
+            Debug.assert(isComputedName || !hasDynamicName(node));
 
             const isDefaultExport = hasSyntacticModifier(node, ModifierFlags.Default) || isExportSpecifier(node) && node.name.escapedText === "default";
 
             // The exported symbol for an export default function/class node is always named "default"
-            const name = isDefaultExport && parent ? InternalSymbolName.Default : getDeclarationName(node);
+            const name = isComputedName
+                ? InternalSymbolName.Computed
```
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/binder.ts:420]: Or are they skipping this call entirely? If so, it's probably better to do the same and port the `if (isReplaceableByMethod) symbol.isReplaceableByMethod = true;` code to wherever the dynamic symbols are being declared.

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -410,13 +410,17 @@ namespace ts {
...
-        function declareSymbol(symbolTable: SymbolTable, parent: Symbol | undefined, node: Declaration, includes: SymbolFlags, excludes: SymbolFlags, isReplaceableByMethod?: boolean): Symbol {
-            Debug.assert(!hasDynamicName(node));
+        function declareSymbol(symbolTable: SymbolTable, parent: Symbol | undefined, node: Declaration, includes: SymbolFlags, excludes: SymbolFlags, isReplaceableByMethod?: boolean, isComputedName?: boolean): Symbol {
+            Debug.assert(isComputedName || !hasDynamicName(node));
 
             const isDefaultExport = hasSyntacticModifier(node, ModifierFlags.Default) || isExportSpecifier(node) && node.name.escapedText === "default";
 
             // The exported symbol for an export default function/class node is always named "default"
-            const name = isDefaultExport && parent ? InternalSymbolName.Default : getDeclarationName(node);
+            const name = isComputedName
```
Comment (sandersn) [inline src/compiler/binder.ts:419]: would it be correct to do this for any node like so? 
```suggestion
            const name = hasDynamicName(node)
```

The assert at the top is suggestive.

**Review by sandersn — CHANGES_REQUESTED** [review]
I want to look at the binder a bit more, but my initial guess is that the replaceable symbol logic needs to be ported over to the dynamic name binding code instead of using declareSymbol to bind a dynamic name in one case.

**Comment by sandersn** [comment]
Looking at binder.ts on my machine, I'm pretty sure the better way to fix this is to change bindDynamicallyNamedThisPropertyAssignment, or perhaps even bindAnonymousDeclaration whenever `name === InternalSymbolName.Computed`. There are two other locations that do so, and might have this bug too.

File: src/compiler/binder.ts [hunk 3]
```diff
@@ -410,13 +410,17 @@ namespace ts {
...
+                ? InternalSymbolName.Computed
+                : isDefaultExport && parent
+                    ? InternalSymbolName.Default
+                    : getDeclarationName(node);
```
[the remark this answers is not in the document]
Comment (armanio123) [reply src/compiler/binder.ts:423]: Changed.

File: src/compiler/binder.ts (hunk 2 above)
Comment (armanio123) [reply src/compiler/binder.ts:419]: I chose not to remove the debug since `declaredMethod` is called on multiple places unrelated to this bug. I'm not sure what other side effects can I cause by removing it.

If you feel strongly on this one I don't mind changing it tho.

**Comment by armanio123** [comment]
I have refactored `bindDynamicallyNamedThisPropertyAssignment` instead as it's only called in two places that seems related. `bindAnonymousDeclaration` on the other hand would be a much bigger impact and I'm unsure that I will actually be fixing any bug. 

Let me know if you agree, otherwise I can spend a some more time analyzing it.

File: src/compiler/binder.ts [hunk 4]
```diff
@@ -460,6 +462,11 @@ namespace ts {
                     // A symbol already exists, so don't add this as a declaration.
                     return symbol;
                 }
+                else if(!isReplaceableByMethod && symbol.isReplaceableByMethod) {
```
Comment (sandersn) [inline src/compiler/binder.ts:465]: this doesn't seem right. I thought the existing replaceable-by-method code in declareSymbol would be good enough for computed names too.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/binder.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/binder.ts]: I'm pretty sure declareSymbol isn't currently called for any dynamic name, and with this change will now be called for some dynamic names. I think it's better to support all dynamic names the same as non-dynamic ones, in case future uses of dynamic names need to declare symbols.

File: src/compiler/binder.ts (hunk 4 above)
Comment (armanio123) [reply src/compiler/binder.ts:465]: This fixes the types and symbols on tests allowJscheckJsTypeParameterNoCrash`. If you feel like this are wrong I can roll it back as without this the crash is fixed.

Comment (sandersn) [reply src/compiler/binder.ts:465]: I vote to roll it back, since that's an incorrect JS program, so there's no real requirement to get binding correct. And we already issue a correct error, so people will be led to the fix.

Comment (armanio123) [reply src/compiler/binder.ts]: Sounds good, done.

**Review by sandersn — APPROVED** [review]
