### PR TITLE
fix(45713) Improve error report summaries

### LINKED ISSUE #45713: [CLI DX] Improve the 'x errors' message in the CLI
# Suggestion

As of 4.4, a run of `tsc` looks like:

```sh
$ /Users/ortatherox/dev/typescript/repros/compilerSamples/node_modules/.bin/tsc
                                                                               
// ...                                                                         
                                                                               
Found 4 errors.                                                                
```

I propose instead we change this message in two key ways, depending on the number of files are raised with errors:

#### Single file

```
$ /Users/ortatherox/dev/typescript/repros/compilerSamples/node_modules/.bin/tsc
                                                                               
// ...                                                                         
                                                                               
Found 1 error in index.ts:4                                                    
``` 

#### Multi file

```
$ /Users/ortatherox/dev/typescript/repros/compilerSamples/node_modules/.bin/tsc
                                                                               
// ...                                                                         

Found 4 errors in 3 files.           
                                     
Errors  Files                        
                                     
     2  index.ts:2                   
     1  other.ts:4                   
     1  third.ts:8
``` 

## Reasoning

For single files, it's a nice quick small dx improvement which lets you click directly to the file. For multi-files, it's a way to understand the entire scope of your compiler errors. Today to understand what files and where the general amount of errors come from you need to scan the entire text, and if that has scrolled off the terminal - then this is hard to do. 

In both cases we only link to the file and line, having the character on the file isn't that useful at this point.

## Exceptions

A PR should _not_ include these changes in watch mode. We think there are third-party apps which rely on the text in watch mode, and we want to make sure we've found those and made sure they can handle the changes to the output. So, to not block PRs we request keeping the watch mode as the same output.

### PR DESCRIPTION
**Pull request by rbargholz**
This PR intends to improve the error report summaries that get generated from diagnostics. Cases where there are multiple errors:  "4 errors in 2 files" as well as single errors, "1 error in testA.ts:4" are accounted for as stated in the issue.

Fixes #45713

### CODE REVIEW

**Comment by rbargholz** [comment]
@orta Code updated:
 - Added tabular data output of files and their errors when there is more than one error.

**Comment by orta** [comment]
This is looking great! It looks feature complete to me? 

@typescript-bot pack this

**Comment by rbargholz** [comment]
> This is looking great! It looks feature complete to me?

@orta Thank you! I am just thoughtful, imagine you had a file with 12 errors, I don't know how common it is, but it could push the table out by one space. Do you think it's an edge case worth handling, or will it likely not occur?

**Comment by orta** [comment]
No worries: for that you would push it in!

```
Errors   Files
     1   /src/project/src/indirectUse.ts:2
    12   /src/project/src/directUse.ts:2
   123   /src/project/src/indirectUse.ts:2
```

It can go pretty high:

```
Errors   Files
     1   /src/project/src/indirectUse.ts:2
    12   /src/project/src/directUse.ts:2
123456   /src/project/src/indirectUse.ts:2
```


But what if you have over 999999 (a million!) errors in a single file? I think at that point it is ok to break the table

```
Errors   Files
     1   /src/project/src/indirectUse.ts:2
    12   /src/project/src/directUse.ts:2
1000000   /src/project/src/indirectUse.ts:2
```

**Comment by rbargholz** [comment]
@orta Code updated

- Fixed lint issues
- Error numbers will now push in til it caps out at 6 digits, if someone has written code that has literally a MILLION errors, the table will be pushed out by one space.

**Comment by rbargholz** [comment]
Untagged WIP

File: src/compiler/watch.ts [hunk 1]
```diff
@@ -101,16 +101,80 @@ namespace ts {
...
+        const BASE_LEFT_PADDING = 6;
+        let tabularData = "";
+        const distinctFiles = filesInError.filter((value, index, self) => index === self.findIndex(file => file!.fileName === value!.fileName));
+        if(distinctFiles.length === 0) return tabularData;
+
+        const headerRow = "Errors   Files\n";
+        tabularData += headerRow;
+        distinctFiles.forEach(file => {
+            const errorCountForFile = countWhere(filesInError, fileInError => fileInError!.fileName === file!.fileName);
+            const errorCountDigitsLength = Math.log(errorCountForFile) * Math.LOG10E + 1 | 0;
```
Comment (orta) [inline src/compiler/watch.ts:170]: a less abstract alternative could be `String(errorCountForFile).length`  (unless I'm missing something)

File: src/compiler/watch.ts [hunk 2]
```diff
@@ -101,16 +101,80 @@ namespace ts {
...
+                errorCount,
+                distinctFileNamesWithLines[0]) :
+            createCompilerDiagnostic(
+                distinctFileNamesWithLines.length === 0 ?
+                    Diagnostics.Found_0_errors :
+                    distinctFileNamesWithLines.length === 1 ?
+                        Diagnostics.Found_0_errors_in_1_file :
+                        Diagnostics.Found_0_errors_in_1_files,
+                errorCount,
+                distinctFileNamesWithLines.length);
```
Comment (orta) [inline src/compiler/watch.ts:156]: This is quite a dense statement, not sure I have any good ideas off the top off my head on how to improve it though

File: tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js [hunk 3]
```diff
@@ -310,8 +310,11 @@ Output::
     'prop1' is declared here.
 
 
-Found 2 errors.
+Found 2 errors in 2 files.
 
+Errors   Files
+     1   /src/project/src/directUse.ts:2
+     1   /src/project/src/indirectUse.ts:2
 exitCode:: ExitStatus.DiagnosticsPresent_OutputsGenerated
```
Comment (orta) [inline tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js:319]: In comparison to the original I think we might need an extra newline _after_ the table to be consistent with our newlines 👍🏻

**Review by orta — COMMENTED** [review]
Great work, only a few ideas for discussion

File: src/compiler/watch.ts [hunk 4]
```diff
@@ -101,16 +101,80 @@ namespace ts {
...
+        return `${newLine}${flattenDiagnosticMessageText(d.messageText, newLine)}${newLine}${newLine}${errorCount > 1 ? createTabularErrorsDisplay(nonNilFiles) : ""}`;
+    }
+
+    function createTabularErrorsDisplay(filesInError: (ReportFileInError | undefined)[]) {
+        const BASE_LEFT_PADDING = 6;
+        let tabularData = "";
+        const distinctFiles = filesInError.filter((value, index, self) => index === self.findIndex(file => file!.fileName === value!.fileName));
+        if(distinctFiles.length === 0) return tabularData;
+
+        const headerRow = "Errors   Files\n";
```
Comment (weswigham) [inline src/compiler/watch.ts:166]: This probably needs to be a localized message~

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/watch.ts (hunk 4 above)
Comment (orta) [reply src/compiler/watch.ts:166]: If we do that, (which I think we probably do need to do) then the numbers about length etc will need to not be hardcoded anymore. For example the Chinese version of "errors" might be 1-2 characters characters wide.

File: src/compiler/watch.ts (hunk 1 above)
Comment (rbargholz) [reply src/compiler/watch.ts:170]: @orta I agree that could also work. I'm happy to update it, it's probably easier to read. I just felt it was a little strange to convert to a string to get the length and nothing else.

File: src/compiler/watch.ts (hunk 2 above)
Comment (rbargholz) [reply src/compiler/watch.ts:156]: I'll have a look back at it and see what I could do. I also try to avoid double ternaries if I can avoid it.

File: tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js (hunk 3 above)
Comment (rbargholz) [reply tests/baselines/reference/tsc/incremental/initial-build/noEmit-changes-composite.js:319]: Got it, I'll add an extra newline.

File: src/compiler/watch.ts (hunk 4 above)
Comment (rbargholz) [reply src/compiler/watch.ts:166]: I didn't think of that, yes this should probably be localised.

@orta 
> If we do that, (which I think we probably do need to do) then the numbers about length etc will need to not be hardcoded anymore
May I ask how you mean by "hardcoded" here? Do you mean we don't need to bother so much about left padding?

File: src/compiler/watch.ts (hunk 2 above)
Comment (rbargholz) [reply src/compiler/watch.ts:156]: What about something like this?
```
        if(distinctFileNamesWithLines.length === 0 && errorCount !== 1) {
            const foundErrorsWithNoFilesDiagnostic = createCompilerDiagnostic(
                Diagnostics.Found_0_errors,
                errorCount);
            return `${newLine}${flattenDiagnosticMessageText(foundErrorsWithNoFilesDiagnostic.messageText, newLine)}${newLine}${newLine}`;
        }
        const d = errorCount === 1 ?
            createCompilerDiagnostic(
                filesInError[0] !== undefined ?
                    Diagnostics.Found_1_error_in_1 :
                    Diagnostics.Found_1_error,
                errorCount,
                distinctFileNamesWithLines[0]) :
            createCompilerDiagnostic(
                distinctFileNamesWithLines.length === 1 ?
                    Diagnostics.Found_0_errors_in_1_file :
                    Diagnostics.Found_0_errors_in_1_files,
                errorCount,
                distinctFileNamesWithLines.length);
        return `${newLine}${flattenDiagnosticMessageText(d.messageText, newLine)}${newLine}${newLine}${errorCount > 1 ? createTabularErrorsDisplay(nonNilFiles) : ""}${newLine}`;
```

File: src/compiler/watch.ts (hunk 4 above)
Comment (orta) [reply src/compiler/watch.ts:166]: By hardcoding, I mean `const BASE_LEFT_PADDING = 6;` only makes sense when 'errors' the string is 6 characters long for example.

Armed with google translate, perhaps this is a reasonable design answer:

```
错误  案卷
  3  build/lib/builtInExtensionsCG.ts
```

```
 错误  案卷
  12  build/lib/builtInExtensionsCG.ts
 123  extensions/html-language-features/client/src/htmlClient.ts
```


```
  错误  案卷
   12  build/lib/builtInExtensionsCG.ts
  123  extensions/html-language-features/client/src/htmlClient.ts
 1234  extensions/html-language-features/client/src/htmlEmptyTagsShared.ts
```

Where tsc pulls out the longest length of a value from either the highest number of errors in a file or the translated word for "errors", allowing people to have a `MAX_INT` amount of errors because it just moves the column to the right once it hits a particular size

```
       错误  案卷
        12  build/lib/builtInExtensionsCG.ts
       123  extensions/html-language-features/client/src/htmlClient.ts
      1234  extensions/html-language-features/client/src/htmlEmptyTagsShared.ts
 123456789  extensions/html-language-features/client/src/tagClosing.ts
```

```
    Errors  Files
        12  build/lib/builtInExtensionsCG.ts
       123  extensions/html-language-features/client/src/htmlClient.ts
      1234  extensions/html-language-features/client/src/htmlEmptyTagsShared.ts
 123456789  extensions/html-language-features/client/src/tagClosing.ts
```

Does that feel reasonable to you?

File: src/compiler/watch.ts (hunk 2 above)
Comment (orta) [reply src/compiler/watch.ts:156]: Works for me, wes also said this is pretty common in the codebase, so the original is also fine 👍🏻

File: src/compiler/watch.ts (hunk 4 above)
Comment (rbargholz) [reply src/compiler/watch.ts:166]: That will work for me too. I'll work on it and see what I can come up with. Thank you for the explanation.

**Comment by orta** [comment]
OK, now it can handle when the number of errors is greater than the length of the title too:

Screen Shot 2021-10-01 at 3 14 40 PM

I also left a note for localizers to try and make sure that message doesn't get mangled in localization in the JSON.

**Comment by rbargholz** [comment]
@orta Apologies for not getting back onto this, life got in the way.

**Comment by orta** [comment]
Never feel guilty for not contributing to OSS in your spare time. I'm here to also help getting it in 👍🏻

**Comment by orta** [comment]
OK, I think this is good to go 👍🏻

**Comment by orta** [comment]
Thanks @rbargholz!
