### PR TITLE
Fix crash in JS declaration emit

### LINKED ISSUE #36273: Cannot read property 'heritageClauses' of undefined
**TypeScript Version:**  3.7.5

**Code**

When I add
```ts
import 'whatwg-fetch';
```
in my project with Webpack and run a command to build it or start watching for changes it fails with error

```ts
TypeError: Cannot read property 'heritageClauses' of undefined
    at getClassExtendsHeritageElement (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:12354:53)
    at Object.getEffectiveBaseTypeNode (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:12342:24)
    at getBaseConstructorTypeOfClass (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:40022:35)
    at serializeAsClass (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:38029:42)
    at serializeSymbolWorker (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:37763:29)
    at serializeSymbol (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:37704:38)
    at /Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:37679:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:37678:33)
    at symbolTableToDeclarationStatements (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:37549:17)
    at /Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:36346:106
    at withContext (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:36367:37)
    at Object.symbolTableToDeclarationStatements (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:36346:28)
    at Object.getDeclarationStatementsForSourceFile (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:64426:60)
    at transformDeclarationsForJS (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:88037:35)
    at transformRoot (/Users/alex/WebstormProjects/rete-tracker/node_modules/typescript/lib/typescript.js:88114:57)
```
But it compiles just fine if add this line later when Webpack is already watching for changes in files.

`whatwg-fetch` has the following in its `package.json`:
```
"main": "./dist/fetch.umd.js",
"module": "./fetch.js",
```
The problem occurs when the module export picked by default, when I point to the script exported as main with
```
import 'whatwg-fetch/dist/fetch.umd';
```
everything works fine.

I have the following tsconfig:
```
{
  "compilerOptions": {
    "target": "es2018",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "outDir": "dist/core", 
    "noEmitOnError": true,
    "sourceMap": true,
    "baseUrl": "src",
    "strictNullChecks": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "typeRoots": [
      "./node_modules/@types",
      "./src/declarations"
    ]
  },
  "include": [
    "src"
  ]
}
```

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/10268

### PR DESCRIPTION
**Pull request by rbuckton**
Our binder has a heuristic that detects `X.prototype.y` assignment in a JS file and treats `X` as a class, even if `X` isn't constructible. That results in a crash in JS declaration emit. This adds a check to ensure that the symbol for `X` actually has valid signatures.

Fixes #36273

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5949,6 +5949,25 @@ namespace ts {
...
+                    if (isInJSFile(symbol.valueDeclaration) && !isClassLike(symbol.valueDeclaration)) {
+                        // For a symbol that isn't syntactically a `class` in a JS file we have heuristics
+                        // that detect prototype assignments that indicate the symbol is *probably* a class.
+                        // Filter out any prototype assignments for non-class symbols, i.e.
+                        //
+                        //     let A;
+                        //     A = {};
+                        //     A.prototype.b = {};
+                        const type = getTypeOfSymbol(symbol);
+                        return some(getSignaturesOfType(type, SignatureKind.Construct))
```
Comment (weswigham) [inline src/compiler/checker.ts:5965]: Hm, thinking about it, is there a way to adjust the binder to only apply the `Class` flag if the thing is actually constructable?

Alternatively, should we still emit this as a class, but with a `private` constructor?

Comment (rbuckton) [reply src/compiler/checker.ts:5965]: Binder has no access to type information, so there's no way to be sure because of augmentations, merging globals, etc.

Comment (weswigham) [reply src/compiler/checker.ts:5965]: What about the `private` constructor suggestion?

Comment (rbuckton) [reply src/compiler/checker.ts:5965]: I can look into it.

**Comment by rbuckton** [comment]
Hmm. Seems like there's more to do here:
```ts
// .js
let A;
A = {};
A.prototype.b = {};
class B extends A {}
const x = (new B()).b;

// .d.ts
declare class A {
    private constructor();
    b: {};
}
declare class B {
}
declare const x: any;
```

The `private constructor` heuristic is only used in declaration emit. We should probably extend it to type checking `class B extends A` to make it an error since the constructor is "private". 

For the equivalent TS, the output is this:
```ts
// .ts
class A {
    private constructor() { }
    b: "x" = "x";
}
// @ts-ignore
class B extends A { }
// @ts-ignore
const x = (new B()).b;

// .d.ts
declare class A {
    private constructor();
    b: "x";
}
declare class B extends A {
}
declare const x: any;
```

So we're consistent on getting `any` for `(new B()).b`, but not in the emit and we don't report errors in JS at the two locations where we do report errors in the TS (labeled above with `// @ts-ignore` comments.

**Comment by weswigham** [comment]
Hm, the emitting errors part is probably important (declaration emit in the presence thereof a little less so). I agree, we should probably add the error. It's certainly odd that we allow it as a base class when it's not actually constructable... The js does error at runtime, too, right?

**Comment by rbuckton** [comment]
Yes, the JS would error at runtime. The JS decl emit differs because the original declaration of `A` isn't actually a class and a lot of our code in the checker for resolving base constructor types depends on it being a class, regardless of what the binder says. Its probably fine to have the decl emit be wrong here if we report an error when you subclass.
