### PR TITLE
Fix symbol merging of augmentations to pattern ambient modules

### LINKED ISSUE #30752: Strange merging behavior of module augmentation and pattern ambient module
**TypeScript Version:**  3.4.1

**Search Terms:**

**Code**

```ts
// @filename: types.ts
declare module '*.foo' {
    let foo: string;
}

// @filename: test.ts
import {foo as a1, bar as a2} from 'a.foo';
import {foo as b1, bar as b2} from 'b.foo'; // expected error: 'b.foo' has no exported member 'bar'

declare module 'a.foo' {
    let bar: number;
}
```

`tsconfig.json` is the default config from `tsc --init`

**Expected behavior:**

I want to augment `a.foo` with an exported member `bar`. Importing `foo` and `bar` from module `a.foo` succeeds while `bar` is not present in module `b.foo`

**Actual behavior:**

The module augmentation `a.foo` merges with the pattern ambient module `*.foo`. Every module matching the pattern now has an exported member `bar`.

To limit the effect to only `a.foo` I need to convert the module augmentation to an ambient module and redeclare all members of the pattern ambient module because there's merging of ambient modules and pattern ambient modules.

*Note: This is not an actual issue in one of my projects, I just happened to notice this surprising behavior while playing around with module resolution.*

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #30752

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -923,7 +924,9 @@ namespace ts {
                     if (!target.exports) target.exports = createSymbolTable();
                     mergeSymbolTable(target.exports, source.exports);
                 }
-                recordMergedSymbol(target, source);
+                if (!unidirectional) {
+                    recordMergedSymbol(target, source);
```
Comment (andrewbranch) [inline src/compiler/checker.ts]: @sandersn you were right that the merged symbols essentially go both ways (target and source don't share a mergeId, but target gets there by `cloneSymbol(resolvedTarget)` and being mutated; then source gets added here.) Introducing a `unidirectonal` option to prevent adding a `mergeId` to `source` accomplishes your suggestion.

Comment (sandersn) [reply src/compiler/checker.ts]: Hm. I've been burned pretty badly in the past by trying to extend the architecture of symbol merging. Merging is where state touches the checker, which is otherwise stateless: 
Symbols from the binder are created when loading a file and only re-created when that file is editted. But merging mutates those symbols. It's important to only do that once, and tricky to make sure that happens as checkers are re-created over and over again and run merge* each time. I'd rather not change the architecture if it's not necessary.

Can you instead investigate copying constituent symbols from `mainModule.exports` and `moduleAugmentation.exports` to a fresh symbol created from `cloneSymbol(moduleAugmentation)` (or maybe it's called createSymbol)? This method is more likely to break symbol sharing, so you'll need to add tests for find-all-refs and rename-symbol to make they work correctly.

The patternAmbientModuleAugmentation map is still probably needed.

File: tests/baselines/reference/ambientDeclarationsPatterns_merging1.errors.txt [hunk 2]
```diff
@@ -0,0 +1,20 @@
+tests/cases/conformance/ambient/testB.ts(1,22): error TS2305: Module '"*.foo"' has no exported member 'onlyInA'.
+
+
+==== tests/cases/conformance/ambient/types.ts (0 errors) ====
+    declare module "*.foo" {
+      let everywhere: string;
```
Comment (sandersn) [inline tests/baselines/reference/ambientDeclarationsPatterns_merging1.errors.txt]: here's a terrifying test case

```
declare module "*.foo" {
  export interface OhNo { star: string }
}
declare module "a.foo" {
  export interface OhNo { a: string }
}
import { OhNo } from "b.foo"
declare let ohno: OhNo;
ohno.a // oh no
```

If we can give an error here, we should. Or we could try to recursively do what this PR does.

File: src/compiler/checker.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/checker.ts]: Not sure I follow—`moduleAgumentation` (the target) isn't transient, so `mergeSymbol` clones it rather than mutates it, and `mainModule` (the source) doesn't get mutated because it's the source. I _think_ the only thing getting mutated here is the `mergedSymbols` array, which is the problem—I need to avoid calling `recordMergedSymbol` with these two symbols, because you should never be able to get from `mainModule` to `moduleAugmentation` via `getMergedSymbol`.

File: tests/baselines/reference/ambientDeclarationsPatterns_merging1.errors.txt (hunk 2 above)
Comment (andrewbranch) [reply tests/baselines/reference/ambientDeclarationsPatterns_merging1.errors.txt]: 😱 OH NO

Comment (andrewbranch) [reply tests/baselines/reference/ambientDeclarationsPatterns_merging1.errors.txt]: image

Doing the "unidirectional" thing recursively fixed this immediately. It feels like I'm on the right track, so ping me if you get a chance to elaborate on your concerns about symbol mutation, and hopefully I can address them in a way that continues to work well recursively like this.

**Comment by andrewbranch** [comment]
@typescript-bot perf test this please and thank you

**Comment by andrewbranch** [comment]
@sandersn the perf test is complaining about this one:

```
‌Monaco - node (v8.9.0, x86) ‌ ‌│‌
────────────┬────────────────────┬────────────────────┬──────────────────┬──────────┬──────────
Emit Time   │    3.01s (± 5.55%) │    3.25s (± 3.03%) │ +0.24s (+ 8.05%) │    2.86s │    3.33s
```

+8% delta but ±5.55% variance measuring master 🤔 I can ignore this, right?

**Comment by sandersn** [comment]
Practically, yes, because it's a minor change in a component you didn't touch. @rbuckton put together those stats and can say whether that notation means it's *technically* statistically significant.
