### PR TITLE
Fully resolve aliases when checking symbol flags

### LINKED ISSUE #44896: `export * as X` cannot be imported when `type X` is exported
# Bug Report

### 🔎 Search Terms

- star-export
- impossible value import
- namespace identifier 
- type value export

Is kinda related to #36704 and #41409.

### 🕗 Version & Regression Information

I test on `typescript@latest` and `typescript@next` at the moment of writing.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type-value exports

### ⏯ Playground Link

[TypeScript Playground](https://www.typescriptlang.org/dev/bug-workbench/?strict=true&ts=4.4.0-dev.20210704&isolatedModules=true&forceConsistentCasingInFileNames=true#code/PTAEAEGcBcCcEsDG0BQKQQGbwDYFMA7AQwFs8AuURAewJiIOkgDomU8APAB2tmitoxQAYQDyAMXEBRKaAC8oAAwBudt178adfgBUpAQXmgAjKrQZw2fMTKUAJggIBrVpDU8+oaAE8ueUAAijk5GiqAAPiaqnB78AFSgRJCBwaCYsNQkoABEzMBa9IyQ2WboYJa4hKQUoPAEdpyuKPAksaAA3il1IQC+aRlZucAO3SVloADkQd0ToLQ43qCweJh4sMnQ1IlevngANKAARgCu-PDJh3h1AOagx5B4donJRKAAbkQ4x-4AFmt4KAK-A4lGmziMYJcen0yiAA)

### 💻 Code

```ts repro
// @strict

// @filename: constants.ts
export const COFFEE = 0;
export const TEA = 1;


// @filename: drink.ts
export type Drink = 0 | 1;
export * as Drink from "./constants";


// @filename: index.ts
import { Drink } from "./drink";
// 'Drink' only refers to a type, but is being used as a value here
const x: Drink = Drink.TEA;
```

### 🙁 Actual behavior

According to TS `Drink` is not imported as a value. 

### 🙂 Expected behavior

No error should occur.

I'm currently using the following workaround:

```ts repro
// @strict

// @filename: constants.ts
export const COFFEE = 0;
export const TEA = 1;


// @filename: drink.ts
import * as DrinkConstants from "./constants";
export type Drink = 0 | 1;
export const Drink = DrinkConstants;


// @filename: index.ts
import { Drink } from "./drink";
const x: Drink = Drink.TEA;
```

### LINKED ISSUE #50455: When aliases and local declarations merge, basically nothing works
Investigating #44896, I have found it is just the tip of a giant iceberg of bugs. The most fundamental operations of the compiler are derailed by a fairly simple merging pattern, which approximately nobody must be using, since as far as I know, #44896 was the first to notice any symptom of the problem. I felt like I should document what I’ve found so far, because it’s so big and widespread I feel sure that any fix I submit will miss some cases, and I want to check my interpretation of the problem against others’ before getting much deeper. Let’s explore the root cause with a simplified version of the example given in the bug:

```ts
// @Filename: value.ts
export const X = 0;

// @Filename: mergeType.ts
import { X } from "./value";
type X = number;
export { X };

// @Filename: index.ts
import { X } from "./mergeType";
const x: X = X;
//           ^ 'X' only refers to a type, but is being used as a value here.ts (2693)
```

So, `value.ts` exports a value `X`; `mergeType.ts` imports that value and merges a local type with it, then exports the result of that merge; finally, the merged symbol is imported by `index.ts`, who tries to access both its type meaning and its value meaning. But, only the type meaning is found.

The code that produces this error does something like

```ts
const symbol = resolveSymbol(resolveName(errorLocation, name, SymbolFlags.Type & ~SymbolFlags.Value));
if (!(symbol.flags & SymbolFlags.Value)) {
  // report error
}
```

1. The `resolveName` call does file-local resolution of the name `X`, returning a result as long as the non-file-local resolution would resolve to a symbol that is a type or interface (potentially merged with other stuff too). That call succeeds in finding `X` in `import { X } from "./mergeType"`, because it peeks out of the file to find the `type X = number` meaning that satisfies the flags.
2. `resolveSymbol` resolves the imported symbol to what it points to. Usually, this is recursive and skips over re-exports all the way to where the symbol is originally exported. However, in the case of `X`, the real symbols being exported are in two different places: a value in `value.ts` and a type in `mergeType.ts`. `resolveSymbol` can’t just skip over the re-export in `mergeType.ts` because that would miss the type meaning altogether. So it returns the merged symbol in `mergeType.ts`, which has symbol flags `TypeAlias` (the local type meaning) and `Alias` (signifying an imported symbol that can be resolved further).
3. The resulting symbol from (2) doesn’t have `SymbolFlags.Value`, so the error is issued.

So what exactly went wrong? It seems that the code assumed `resolveSymbol` would never return something that’s still an alias; that is, a symbol that’s not fully resolved. This code would have to _recursively_ call `resolveAlias` (close relative of `resolveSymbol`) and aggregate all the flags it sees until it resolves to something that’s no longer an alias.

Ok, no problem; that’s what I tried first. I ran the test and the error went away. Success! Except, then I looked at the JS emit. `index.ts` was completely missing an import/require for `mergeType.ts`. The code would crash at runtime, and now it doesn’t have any errors—a decidedly worse state than before. It turns out that the code controlling import elision in emit is full of this same pattern based on the same faulty assumption.

I updated about 10 more places to do recursively-resolving flag checks and fixed emit. However, while I was there, I noticed a few other checks that also fall prey to the same bad assumption. Imports are also elided if the symbol resolves to a type-only import or export, or if the symbol resolves to a const enum or const-enum-only module, since references to those will be inlined, making the import unreferenced. These things also fail to consider aliases merging with locals:

```ts
// @Filename: a.ts
interface A {}
export type { A }

// @Filename: b.ts
import { A } from "./a";
const A = 0;
export { A };

// @Filename: c.ts
import { A } from "./b";
A;
```

In `c.ts`, we got an error for using `A` in an emitting position because it was traced to a type-only export in `a.ts`, and the import was elided for the same reason. In fact, even the export in `b.ts` was elided for that reason. But this is all nonsensical, because the type-only export never actually touched the value meaning declared in `b.ts`. The type-only export, applied to a symbol that is already just a type, should be completely irrelevant.

So I fixed the handling of type-only imports and exports in error reporting and import/export elision next. But then I remembered that some value-having symbols can merge with other value-having symbols—functions and namespaces, for example—and I wondered how a merge between those would work when one of them is exported as type-only. As it turned out, thinking about the type-only behavior for this case may have been jumping the gun, because the normal case can be trivially broken too. I started with a test case like:

```ts
// @Filename: a.ts
function A() {}
export { A };

// @Filename: b.ts
import { A } from "./a";
namespace A {
  export const displayName = "A";
}

A();
A.displayName;
```

Gracefully, this version of the test _does_ put an error on `import { A } from "./a"`: `Import declaration conflicts with local declaration of 'A'.`. So while a function and namespace can merge locally, they can’t across module boundaries, making things slightly easier to reason about. _Except_, by now I have learned a fun and nearly foolproof way to merge almost anything I want by foiling `resolveAlias`. If I just introduce an intervening type merge between `a.ts` and `b.ts`...

```ts
// @Filename: a.ts
function A() {}
export { A };

// @Filename: b.ts
import { A } from "./a";
type A = 0;
export { A };

// @Filename: c.ts
import { A } from "./b";
namespace A {
  export const displayName = "A";
}

A();
A.displayName;
```

Yep! Now there are no symbol merging errors; just an error on `A()` that tells me `A` is not callable! Which at least is consistent with the related emit bugs, because `b.js` has no export and `c.js` has no import, so the function meaning is indeed lost in the emit.

## Conclusion...?

There are 32 references to `resolveSymbol` and 25 references to `resolveAlias` that probably all need to be audited for this mistake. I also haven’t touched the const-enum-related import elision logic yet, which I think is similarly broken.

I’m a bit concerned about potential fallout from attempting a fix because error reporting and import elision are separate code paths, currently both wrong in a consistent, predictable way, and “fixing” error reporting without fixing emit makes the situation much, much worse than it is now. It’s also a bit hard to think about how to prioritize these bugs since they are very old and have received very little attention, but are pretty fundamental and glaringly wrong. I think the best course of action is to try to be thorough and get stuff in early in the release cycle. I wish we could be a bit more restrictive about alias merges, but that would be too big of a breaking change. I’m also considering whether the import elision logic can be simplified in many places by assuming that if a reference to an import appears in an emitting value position, we should consider the alias referenced, whether we think it resolves to a value or not (related to #48588 and similar things @gabritto is working on).

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #44896
Fixes #50455 

I actually don’t think this is a breaking change in any meaningful way. I do have [one test](https://github.com/microsoft/TypeScript/pull/50853/files#diff-557cc72f2b8a2675ba8da5ec553f983b98f1ca3dd6062e429438421743fd9fee) that exhibits new errors, but the scenario is extremely contrived and didn’t exactly work before. Mostly, this removes false errors and false import elisions. The most visible and understandable example is the one from #44896:

```ts
// @filename: constants.ts
export const COFFEE = 0;
export const TEA = 1;


// @filename: drink.ts
export type Drink = 0 | 1;
export * as Drink from "./constants";


// @filename: index.ts
import { Drink } from "./drink";
// 👀 BEFORE: 'Drink' only refers to a type, but is being used as a value here
// 👍 AFTER: No error
const x: Drink = Drink.TEA;
```

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot user test inline
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test top100

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3236,6 +3237,51 @@ namespace ts {
...
+                if (target === unknownSymbol) {
+                    return undefined;
+                }
+
+                // Optimization - avoid creating `seenSymbols` Set in most cases
+                if (target === symbol) {
+                    break;
+                }
+                else if (target.flags & SymbolFlags.Alias && !seenSymbols) {
+                    seenSymbols = new Set([symbol, target]);
```
Comment (JoostK) [inline src/compiler/checker.ts:3274]: This is the only place where `seenSymbols` is populated with values; does this need to be something like

```ts
  else if (target.flags & SymbolFlags.Alias) {
    if (!seenSymbols) {
      seenSymbols = new Set([symbol, target]);
    } else {
      seenSymbols.add(target);
    }
  }
```

**Review by gabritto — APPROVED** [review]

File: tests/baselines/reference/typeOnlyMerge3.errors.txt [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+tests/cases/conformance/externalModules/c.ts(2,1): error TS1362: 'A' cannot be used as a value because it was exported using 'export type'.
+tests/cases/conformance/externalModules/c.ts(3,1): error TS1362: 'A' cannot be used as a value because it was exported using 'export type'.
+tests/cases/conformance/externalModules/c.ts(4,1): error TS1362: 'A' cannot be used as a value because it was exported using 'export type'.
+tests/cases/conformance/externalModules/c.ts(4,1): error TS2349: This expression is not callable.
+  Type 'typeof A' has no call signatures.
+
+
+==== tests/cases/conformance/externalModules/a.ts (0 errors) ====
+    function A() {}
+    export type { A };
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply tests/baselines/reference/typeOnlyMerge3.errors.txt:11]: Someone who imports this is allowed to use `type ASignature = typeof A`

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -2225,8 +2225,8 @@ namespace ts {
                             !checkAndReportErrorForExtendingInterface(errorLocation) &&
                             !checkAndReportErrorForUsingTypeAsNamespace(errorLocation, name, meaning) &&
                             !checkAndReportErrorForExportingPrimitiveType(errorLocation, name) &&
+                            !checkAndReportErrorForUsingNamespaceAsTypeOrValue(errorLocation, name, meaning) &&
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/compiler/checker.ts:2228]: It’s been a while, but I _believe_ it’s this:

A namespace is a value if it exports values. If it’s not a value, it’s not a type per se, but it’s fairly typey. I believe after tweaking the `meaning` flag checks in these functions to be a bit easier to read, the `checkAndReportErrorForUsingTypeAsValue` started reporting an error on typey (uninstantiated) namespaces, which was stepping on the toes of `checkAndReportErrorForUsingNamespaceModuleAsValue`, which wanted to issue essentially the same error, but slightly more precise in mentioning that the non-valuey thing is a namespace. So I simply moved that check first so it would take precedence. So I actually think this order change _isn’t_ reflected in the tests, because it just neutralizes the effect of another readability change. (I also renamed `checkAndReportErrorForUsingNamespaceModuleAsValue` to `checkAndReportErrorForUsingNamespaceAsTypeOrValue` because nobody knows what a “namespace module” is, and it was already issuing errors when using a namespace as a type.)

File: tests/baselines/reference/valuesMergingAcrossModules.errors.txt [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+    
+==== tests/cases/conformance/externalModules/c.ts (2 errors) ====
+    import { A } from "./b";
+             ~
+!!! error TS2440: Import declaration conflicts with local declaration of 'A'.
+    namespace A {
+      export const displayName = "A";
+    }
+    
+    A();
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply tests/baselines/reference/valuesMergingAcrossModules.errors.txt:23]: That’s right, but only because `A` is an alias. Normally, slightly disconcerting though it is, we allow a function to merge with an instantiated namespace: [playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQQBQEpEG8CwAoRQxAJwFMoRiwBufAX3zAEMBbUgZwAcmJSVt8RRBATsoiACYwuAGyYBPAHKs+AXkQAiZBtp46QA). I only learned this in the course of my PR, but the rules are stricter for merges across module boundaries (thankfully). Two values are just not allowed to merge across modules.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -3236,6 +3237,54 @@ namespace ts {
...
+         * import { a } from "./b";
+         * ```
+         * Calling `resolveAlias` on the `a` in c.ts would stop at the merged symbol exported
+         * from b.ts, even though there is still more alias to resolve. Consequently, if we were
+         * trying to determine if the `a` in c.ts has a value meaning, looking at the flags on
+         * the local symbol and on the symbol returned by `resolveAlias` is not enough.
+         * @returns undefined if `symbol` is an alias that ultimately resolves to `unknown`;
+         * combined flags of all alias targets otherwise.
+         */
+        function getAllSymbolFlags(symbol: Symbol): SymbolFlags | undefined {
```
Comment (jakebailey) [inline src/compiler/checker.ts:3260]: I don't know if the perf results are noise, but they do look slightly worse; is this information worth caching in some form, or is it just unlikely because it only affects aliases?

Comment (andrewbranch) [reply src/compiler/checker.ts:3260]: I thought it was noise. I’ll run again and compare.

**Comment by andrewbranch** [comment]
@typescript-bot perf test this faster

File: src/compiler/checker.ts (hunk 5 above)
Comment (jakebailey) [reply src/compiler/checker.ts:3260]: Seems like noise, the new run is positive.

**Review by jakebailey — APPROVED** [review]
LGTM, though I'm not sure I'm a massive fan of the `?? -1`; it seems like most call sites do that but I don't know if I have any better method, besides maybe `SymbolFlags.All` or something, but that still requires the `??`.

**Comment by andrewbranch** [comment]
I might look at making `getAllSymbolFlags` opinionated and say that unresolved aliases return `SymbolFlags.All`, and make a variant that returns `undefined` for the few places that need to do something different. I think it’s probable that a lot of the places that currently see `SymbolFlags.Property` would have the same behavior seeing `SymbolFlags.All`.
