### PR TITLE
Under jsx: preserve, actually preserve expressions which contain only comments

### LINKED ISSUE #41754: Comments within JSX Expressions are not preserved
I found following unexpected behaviour with tsx (v4.1.2):
```javascript
class Component {
    render() {
        return <div>
            {/* missing */}
            {null/* preserved */}
        </div>;
    }
}
```

_Originally posted by @marc3lsk in https://github.com/microsoft/TypeScript/issues/40074#issuecomment-733751798_

### PR DESCRIPTION
**Pull request by weswigham**
And, perhaps more importantly, fixes a crash caused by the interaction of the `module` or `system` transformers and the new `jsx` transforms discovered along the way (in the same test case).

Fixes #41754

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -3378,8 +3379,8 @@ namespace ts {
         }
 
         function emitJsxExpression(node: JsxExpression) {
-            if (node.expression) {
-                writePunctuation("{");
+            if (node.expression || (!commentsDisabled && !nodeIsSynthesized(node) && getTextOfNode(node).length > 2 && getTextOfNode(node).indexOf("/*") > -1)) { // preserve empty expressions if they contain comments!
```
Comment (weswigham) [inline src/compiler/emitter.ts:3382]: `hasCommentAtPosition` isn't a thing we currently have, but this does a, _okay_  job of approximating it. Obviously doesn't handle something like
```ts
const x = <div>
{ // first line 
/*last line*/}
</div>;
```
Maybe it's worth doing a full check with `forEachTrailingCommentRange`? @rbuckton - your opinion?

File: src/compiler/transformers/module/module.ts [hunk 2]
```diff
@@ -1790,7 +1790,7 @@ namespace ts {
                         const name = importDeclaration.propertyName || importDeclaration.name;
                         return setTextRange(
                             factory.createPropertyAccessExpression(
-                                factory.getGeneratedNameForNode(importDeclaration.parent.parent.parent),
+                                factory.getGeneratedNameForNode(importDeclaration.parent?.parent?.parent || importDeclaration),
```
Comment (weswigham) [inline src/compiler/transformers/module/module.ts:1793]: This change (and the similar ones in `system`) are what fix the crash mentioned in the OP. The non-module file has a reference to a synthetic import that, since it's never _actually_ inserted into the file (since it's not a module), is never parented, and thus has no name. We emit a (admittedly type system, rather than grammar/program) error in these cases usually (`module "react/jsx-runtime" not found`), so the emitted JS being nonfunctional is _probably_ fine, but this case might need a more descriptive error added. The emit simply uses an arbitrary name now (`_a`), rather than crashing.

Since this part fixes a crash, I'm wondering if I should (partially?) port this to the 4.1 branch or no? @DanielRosenwasser ?

Comment (weswigham) [reply src/compiler/transformers/module/module.ts:1793]: [This comment](https://github.com/microsoft/TypeScript/issues/41616#issuecomment-735690427) may actually be referring to the crash fixed here (assuming the input file is exactly what the user in that comment says, odd as a top-level `return` is), though the stack is very different than the on the OP of that thread refers to (and is definitely a separate issue).

File: tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=preserve,module=commonjs).js [hunk 3]
```diff
@@ -0,0 +1,27 @@
+//// [commentsOnJSXExpressionsArePreserved.tsx]
+// file is interntionally not a module - this tests for a crash in the module/system transforms alongside the `react-jsx` and `react-jsxdev` outputs
+namespace JSX {
+    interface IntrsinsicElements { [index: string]: any }
```
Comment (sandersn) [inline tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=preserve,module=commonjs).js:4]: is this supposed to be named `IntrinsicElements`?

File: src/compiler/emitter.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/emitter.ts:3382]: do we care about `//` comments? The new check only handles `/**/` comments, right?

File: src/compiler/emitter.ts [hunk 4]
```diff
@@ -2824,7 +2824,8 @@ namespace ts {
             }
             pos = writeTokenText(token, writer, pos);
             if (isSimilarNode && contextNode.end !== pos) {
-                emitTrailingCommentsOfPosition(pos, /*prefixSpace*/ true);
+                const isJsxExprContex = contextNode.kind === SyntaxKind.JsxExpression;
```
Comment (sandersn) [inline src/compiler/emitter.ts:2827]: typo: isJsxExprContext

File: tests/cases/compiler/commentsOnJSXExpressionsArePreserved.tsx [hunk 5]
```diff
@@ -0,0 +1,15 @@
+// @module: system,commonjs
+// @jsx: react,react-jsx,react-jsxdev,preserve
+// file is interntionally not a module - this tests for a crash in the module/system transforms alongside the `react-jsx` and `react-jsxdev` outputs
```
Comment (sandersn) [inline tests/cases/compiler/commentsOnJSXExpressionsArePreserved.tsx:3]:
```suggestion
// file is intentionally not a module - this tests for a crash in the module/system transforms alongside the `react-jsx` and `react-jsxdev` outputs
```

You don't *have* to fix this typo, but there will 100% be a PR for it next October if you don't :laughing:

**Review by sandersn — CHANGES_REQUESTED** [review]
Seems reasonable although (1) I'm not an expert here (2) I'd like to know what happens for

```
{
// comment
}
```

maybe this is nonsensical for JSX though.

File: tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=preserve,module=commonjs).js (hunk 3 above)
Comment (weswigham) [reply tests/baselines/reference/commentsOnJSXExpressionsArePreserved(jsx=preserve,module=commonjs).js:4]: Yep, but I only added it to ensure there wasn't error noise for things I wasn't testing - guess I don't need intrinsic elements for that - an empty JSX namespace will do.

File: src/compiler/emitter.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/emitter.ts:3382]: Yep. That's why I'm asking if it's worth doing a full comment range iteration to check if there are any comments attached to the position.

**Comment by weswigham** [comment]
@sandersn since nobody else weighed in, I opted to change this to do a full comment scan. It's ready for another look.

@typescript-bot perf test this - this hopefully doesn't hurt `material-ui` emit time too bad.

**Comment by weswigham** [comment]
Eyyy, and we don't have emit on for `material-ui` in the perf suite anyway. Nice. Well, it shouldn't be too bad - line information is cached on the source file, and comment iteration is simple character matching.

**Review by sandersn — APPROVED** [review]
