### PR TITLE
fix accessor parse with line terminator

### LINKED ISSUE #22757: Incorrect Parse for accessors in classes
This was brought up in TC39 today:

```ts
class C {
  get
  x() {}
}
```

In the above example, `x` should be parsed as an accessor, but we parse `get` as a field and `x() {}` as a method. There is no `[no LineTerminator here]` restriction in the [grammar](https://tc39.github.io/ecma262/#prod-MethodDefinition).

Related Productions:
```grammarkdown
ClassElement[Yield, Await]: 
    `static` MethodDefinition[?Yield, ?Await]

MethodDefinition[Yield, Await]:
    `get` PropertyName[?Yield, ?Await] `(` `)` `{` FunctionBody[~Yield, ~Await] `}`
    `set` PropertyName[?Yield, ?Await] `(` PropertySetParameterList `)` `{` FunctionBody[~Yield, ~Await] `}`
```

Playground: http://www.typescriptlang.org/play/index.html#src=class%20C%20%7B%0D%0A%20%20%20%20get%0D%0A%20%20%20%20x()%20%7B%20%7D%0D%0A%7D

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #22757

### CODE REVIEW

**Comment by mhegazy** [comment]
@sandersn can you please review

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -1344,26 +1344,26 @@ namespace ts {
...
+                case SyntaxKind.ExportKeyword:
+                    nextToken();
+                    if (token() === SyntaxKind.DefaultKeyword) {
+                        return lookAhead(nextTokenCanFollowDefaultKeyword);
+                    }
+                    return token() !== SyntaxKind.AsteriskToken && token() !== SyntaxKind.AsKeyword && token() !== SyntaxKind.OpenBraceToken && canFollowModifier();
+                case SyntaxKind.DefaultKeyword:
+                    return nextTokenCanFollowDefaultKeyword();
+                case SyntaxKind.StaticKeyword:
+                case SyntaxKind.GetKeyword:
```
Comment (sandersn) [inline src/compiler/parser.ts]: the two new lines are the two GetKeyword/SetKeyword cases. Everything else is a refactor to use `switch` instead of `if`.
