### PR TITLE
fix(50224): Intellisense for strings within a type's Union doesn't work properly for JSX

### LINKED ISSUE #50224: Intellisense for strings within a type's Union doesn't work properly for JSX
# Bug Report

Getting intellisense (auto-complete) from strings literals that belong to a union members in JSX components seems to only work, if we do it inside the "curly braces", if we try to get intellisense from plain "quotes", nothing will come up, even though TS still evaluates well the types.

### 🔎 Search Terms

#intellisense  #string literals

### 🕗 Version & Regression Information

Since version 4.7, according to my tests, this was working correctly in version 4.6.4.

- This changed between versions 4.6.4 and 4.7.4

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgAUcwBnOAXjgG8UBzJAFxwAdgFcQAIyRQAvnAA+3EShCCCEiAA98cGRXIATJGgA2KInEyjhGYBGFwWKsCaQAxYQApzvFkKYQrACUQijC1IbGZhZWNjB2DgDKzq4AwriQwkjCMN5Qvv7MLCFwYRHkAPQVcACSOUgmwCws2S1w9nAwABb0AAbCKki9cGDM0jRwgKDk5Gj2LPAoAIwcjinuXlwDqkL4GtoyQfpVtfWNza30Hd19W0MjY7DUUzNzCwBMKwA8yeBpGfbZeC3dhcfD4OQVAB8lGOADkIHBgKcmi1hG0rj04P1BsNRoFxk9ADLkLzRCwAzF8fi4kOlwACcspVOwwXAoUA)

### 💻 Code

```tsx
type Props = {age: number} | { name: "box" };

declare function sampleFn(args: Props): any
declare function SampleComponent(args: Props): any

// Intelissense on the `name` property ✅
const a1 = sampleFn({name: "box"});

// Intelissense on the `name` property ✅
const a2 = <SampleComponent name={""} />

// No intelissense on the `name` property ❌
const a3 = <SampleComponent name="" />
```

### 🙁 Actual behavior

We don't get intellisense:
 
image

### 🙂 Expected behavior

Intesllisense should be available, since it is for regular TS functions.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #50224

### CODE REVIEW

File: tests/cases/fourslash/stringLiteralCompletionsInJsxAttributeInitializer.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/// <reference path="fourslash.ts" />
+
+// @jsx: preserve
+// @filename: /a.tsx
+////type Props = { a: number } | { b: "b" };
```
Comment (sandersn) [inline tests/cases/fourslash/stringLiteralCompletionsInJsxAttributeInitializer.ts:5]: can you change this to something else so it's obvious that the suggestion is the initialiser, not the property name?
```suggestion
////type Props = { a: number } | { b: "somethingelse" };
```

**Review by sandersn — CHANGES_REQUESTED** [review]
The removal of the fallthrough looks wrong to me.

**Comment by a-tarasyuk** [comment]
Surprisingly, when I re-requested a review from @sandersn, Github removed @gabritto from the reviewers :worried:

**Review by sandersn — APPROVED** [review]
