### PR TITLE
Fix decorator emit crash

### LINKED ISSUE #58269: Debug Failure in transformClassLike in "ghost" after #56955
### 🔎 Search Terms

Error Debug Failure at transformClassLike

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

_No response_

### 💻 Code

```console
$ git clone git@github.com:TryGhost/Ghost.git
$ cd Ghost
$ git rev-parse HEAD
69372d9018f156d56ae271b6d8e378efb9ea3012
$ yarn
$ node --enable-source-maps ~/work/TypeScript/built/local/tsc.js -p ghost/tsconfig.json
```

### 🙁 Actual behavior

```
/home/jabaile/work/TypeScript/src/compiler/program.ts:2918
            throw e;
            ^


Error: Debug Failure.
    at transformClassLike (/home/jabaile/work/TypeScript/src/compiler/transformers/esDecorators.ts:700:19)
    at visitClassDeclaration (/home/jabaile/work/TypeScript/src/compiler/transformers/esDecorators.ts:1094:30)
    at visitor (/home/jabaile/work/TypeScript/src/compiler/transformers/esDecorators.ts:432:24)
    at visitArrayWorker (/home/jabaile/work/TypeScript/src/compiler/visitorPublic.ts:345:57)
    at visitNodes2 (/home/jabaile/work/TypeScript/src/compiler/visitorPublic.ts:258:21)
    at visitLexicalEnvironment (/home/jabaile/work/TypeScript/src/compiler/visitorPublic.ts:383:18)
    at visitEachChildOfSourceFile (/home/jabaile/work/TypeScript/src/compiler/visitorPublic.ts:1779:13)
    at visitEachChild (/home/jabaile/work/TypeScript/src/compiler/visitorPublic.ts:603:38)
    at transformSourceFile (/home/jabaile/work/TypeScript/src/compiler/transformers/esDecorators.ts:317:25)
    at transformSourceFileOrBundle (/home/jabaile/work/TypeScript/src/compiler/transformers/utilities.ts:130:54)

Node.js v20.12.2
```

### 🙂 Expected behavior

No crash.

### Additional information about the issue

This bisects to #56955, at:

```ts
Debug.assertIsDefined(classInfo.classThis);
```

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes a crash when transforming Stage 3 decorators when both class element decorators and class constructor parameter decorators are present.

Fixes #58269

### CODE REVIEW

File: src/compiler/transformers/utilities.ts [hunk 1]
```diff
@@ -679,9 +679,9 @@ function getDecoratorsOfParameters(node: FunctionLikeDeclaration | undefined) {
  *
  * @internal
  */
-export function getAllDecoratorsOfClass(node: ClassLikeDeclaration): AllDecorators | undefined {
+export function getAllDecoratorsOfClass(node: ClassLikeDeclaration, useLegacyDecorators: boolean): AllDecorators | undefined {
     const decorators = getDecorators(node);
-    const parameters = getDecoratorsOfParameters(getFirstConstructorWithBody(node));
+    const parameters = useLegacyDecorators ? getDecoratorsOfParameters(getFirstConstructorWithBody(node)) : undefined;
```
Comment (jakebailey) [inline src/compiler/transformers/utilities.ts:684]: Should `getDecoratorsOfParameters` take the parameter and return undefined instead of copying the ternary to all call sites?

Comment (rbuckton) [reply src/compiler/transformers/utilities.ts:684]: Branching is cheaper at runtime than invocation, so probably not.

**Review by jakebailey — APPROVED** [review]

File: src/compiler/transformers/utilities.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/utilities.ts:684]: In this case specifically, just passing the argument to `getDecoratorsOfParameters` requires iterating over all class elements to find a constructor, which is unnecessary work.
