### PR TITLE
For JSX Attributes, map over unions of props for contextual types

### LINKED ISSUE #17427: Type inference fails in JSX if union type is involved.
**TypeScript Version:**  2.4.2

**Code**

```ts
type Props<T> = PropsBase<string> | PropsWithConvert<T>;

interface PropsBase<T> {
    data: T;
}

interface PropsWithConvert<T> extends PropsBase<T> {
    convert: (t: T) => string;
}

function InferenceFail<T>(props: Props<T>): JSX.Element {
    return <div />;
}

InferenceFail({data: '1'});
const test = <InferenceFail data={'1'} convert={n => '' + n} />;
InferenceFail({data: 2, convert: n => '' + n});
```

**Expected behavior:**

All lines should compile.

**Actual behavior:**

The JSX version does not compile.

Removing the type union, the JSX version is able to compile

Possibly related: #17295

### PR DESCRIPTION
**Pull request by weswigham**
This way an individual attribute can fulfill any of them, rather than failing to get a contextual type unless it fulfills all of them.

Fixes #17427

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13101,7 +13101,12 @@ namespace ts {
 
             if (isJsxAttribute(node.parent)) {
                 // JSX expression is in JSX attribute
-                return getTypeOfPropertyOfType(attributesType, node.parent.name.escapedText);
+                const attributeName = node.parent.name.escapedText;
+                if (attributesType.flags & TypeFlags.Union) {
+                    // The attribute may fulfill any of the members of the union
+                    return getUnionType(compact(map((attributesType as UnionType).types, t => getTypeOfPropertyOfType(t, attributeName))));
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Use `mapDefined` instead of `compact(map())`.

**Comment by andy-ms** [comment]
Do you know why `getPropertyOfType` wasn't working for that? It appears to already have a special case for union types.

**Comment by weswigham** [comment]
@andy-ms Since it's a union and the property only exists on one option of the union, the property gets marked as `CheckFlags.Partial`, then omitted from the `getPropertyOfType` result. Acually, looking into it, I can just use `getTypeOfSymbol` on `getUnionOrIntersectionProperty` rather than what I've got here, which should also enable some cacheing of cacheable results.

**Comment by andy-ms** [comment]
Is there any reason why JSX should differ from object literals here?

**Comment by weswigham** [comment]
@andy-ms Thanks for the prompt - I hadn't realized we were doing something slightly differently for non-jsx-related contextual types. Elsewhere we were using `getTypeOfPropertyOfContextualType` instead of `getTypeOfPropertyOfType`, which fully explains the difference in behavior (`getTypeOfPropertyOfContextualType` does the mapping I had inlined here). Now for all JSX contextual typing, we use `getTypeOfPropertyOfContextualType`, as we should.

File: tests/cases/compiler/tsxInferenceShouldNotYieldAnyOnUnions.tsx [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    return <div />;
+}
+
+// Sanity check: function call equivalent versions work fine
+InferenceShouldNotProduceAny({ data: "1" });
+InferenceShouldNotProduceAny({ data: "1", convert: n => "" + n });
+InferenceShouldNotProduceAny({ data: 2, convert: n => "" + n });
+
+
+const f1 = <InferenceShouldNotProduceAny data={"1"} />;
```
Comment (sandersn) [inline tests/cases/compiler/tsxInferenceShouldNotYieldAnyOnUnions.tsx]: This is tiny, but a positive name like InferenceShouldProduceNumber would be better.

Comment (sandersn) [inline tests/cases/compiler/tsxInferenceShouldNotYieldAnyOnUnions.tsx]: ShouldInferFromData, maybe
