### PR TITLE
[Transforms] Fix the name when synthesized node is clone of auto generate identifier kind

### LINKED ISSUE #7875: [Transforms] incorrect synthesized name for 'default'
**Expected**:

```js
//// [es5ExportDefaultClassDeclaration2.ts]

export default class {
    method() { }
}


//// [es5ExportDefaultClassDeclaration2.js]
"use strict";
var default_1 = (function () {
    function default_1() {
    }
    default_1.prototype.method = function () { };
    return default_1;
}());
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = default_1;
```

**Actual**:

```js
//// [es5ExportDefaultClassDeclaration2.ts]

export default class {
    method() { }
}


//// [es5ExportDefaultClassDeclaration2.js]
"use strict";
var default_1_1 = (function () {
    function default_1_1() {
    }
    default_1_1.prototype.method = function () { };
    return default_1_1;
}());
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = default_1;
```

Failed tests:
*  tests\cases\compiler\es5ExportDefaultClassDeclaration2.ts

### PR DESCRIPTION
**Pull request by sheetalkamat**
This fixes variable declaration created for default exported class without name
Fixes #7875

Fixes baselines:
- tests/cases/compiler/es5ExportDefaultClassDeclaration2.ts
- tests/cases/conformance/es6/moduleExportsSystem/decoratedDefaultExportsGetExportedSystem.ts

### CODE REVIEW

File: src/compiler/printer.ts [hunk 1]
```diff
@@ -2607,8 +2607,10 @@ const _super = (function (geti, seti) {
             function getSourceNodeForGeneratedName(name: Identifier) {
                 let node: Node = name;
                 while (node.original !== undefined) {
+                    const nodeId = node.id;
                     node = node.original;
-                    if (isIdentifier(node) && node.autoGenerateKind === GeneratedIdentifierKind.Node) {
+                    // If this is not the exact clone of identifier use this identifier to generate the name
```
Comment (yuit) [inline src/compiler/printer.ts]: Could you clarify the comment? do you mean `If this "node" is not the same as the given Identifier, "name", use the "node" to generate name`?

File: src/compiler/visitor.ts [hunk 2]
```diff
@@ -461,7 +461,7 @@ namespace ts {
         const edgeTraversalPath = nodeEdgeTraversalMap[node.kind];
         if (edgeTraversalPath) {
             for (const edge of edgeTraversalPath) {
-                const value = (<Map<any>>node)[edge.name];
+                const value = edge && (<Map<any>>node)[edge.name];
```
Comment (yuit) [inline src/compiler/visitor.ts]: Could edge be undefined ?

Comment (vladima) [inline src/compiler/visitor.ts]: question: is it because of trailing commas in `nodeEdgeTraversalMap`?

Comment (sheetalkamat) [inline src/compiler/visitor.ts]: Yes it is because of trailing commas

File: src/compiler/printer.ts (hunk 1 above)
Comment (sheetalkamat) [inline src/compiler/printer.ts]: sure. will update the comment

**Comment by vladima** [comment]
If ES3 compliance is important for us maybe we should get rid of trailing commas then?

File: src/compiler/visitor.ts (hunk 2 above)
Comment (rbuckton) [inline src/compiler/visitor.ts]: @mhegazy has a fix in #7950 that removes the trailing commas.

Comment (mhegazy) [inline src/compiler/visitor.ts]: PR to remove commas manually in https://github.com/Microsoft/TypeScript/pull/8065, issue to add an ES3 transformation and remove them by the compiler in https://github.com/Microsoft/TypeScript/issues/7938

Comment (sheetalkamat) [inline src/compiler/visitor.ts]: Ok I will remove that change from here then

**Comment by mhegazy** [comment]
:+1:
