### PR TITLE
Recursive type references

### LINKED ISSUE #3496: recursive type definitions
I have a recursive type definition for JSON Serializable entities (Exhibit A, edited after discussion with @JsonFreeman ):
```typescript
export type IJSONSerializable = IJSONSerializableObject | number | string | IMaybeRecursiveArray<IJSONSerializableObject | number | string>;

interface IMaybeRecursiveArray<T> {
   [i: number]: T | IMaybeRecursiveArray<T>;
}

interface IJSONSerializableObject {
    [paramKey: string]: IJSONSerializable
}
```

I would like to be able to write the following, but get a circular reference error (Exhibit B):
```typescript
export type IJSONSerializable = {[paramKey: string]: IJSONSerializable} | number | string | Array<IJSONSerializable>;
```

How difficult would it be to address this limitation of the type system?

### LINKED ISSUE #6230: allow recursive generic type aliases
``` typescript

interface A<a> {
    brand: 'a';
    nested: a;
}

interface B<a> {
    brand: 'b';
    nested: a;
}

type C<a> = A<a> | B<a>;

type D = C<D> | string; // <-- i wish

```

### LINKED ISSUE #14174: Type alias circularly references itself
Why does this work:

```ts
type Foo = { x: Foo }
```

but this doesn't:

```ts
type Bar<A> = { x: A }
type Foo = Bar<Foo>
//   ^^^ Type alias 'Foo' circularly references itself
```

Shouldn't they be equivalent?

### LINKED ISSUE #28929: recursive/nested types for arrays
So I had this:

```typescript
type NestedRequestHandler = RequestHandler | Array<RequestHandler> | Array<Array<RequestHandler>>
```
for a certain situation it was actually insufficient and the compiler required me to do this:

```typescript
type NestedRequestHandler = RequestHandler | Array<RequestHandler> | Array<Array<RequestHandler> | RequestHandler>
```

I can't figure out why the compiler forced me to do that, the above seems like a **bug**. Since the second operand in the union type seems like it would have covered it. Am I right or wrong?

Anyway, what I am ultimately looking for is a recursive type for arrays, like so:
https://stackoverflow.com/questions/53646270/declare-arbitrarily-nested-array-recursive-type-definition

### LINKED ISSUE #32967: Recursively-typed array with nth-element typing
## Search Terms

• recursive (tuple|array) of varying length
• differently-typed array elements
• tuple of (generic|unknown) size

## Suggestion

Ability to recursively type the elements of varying-length arrays

## Use Cases

I'm attempting to create a type for hypertext nodes. Consider the following representation of some HTML:

```json
["div", {"id": "parent"},
  ["div", {"id": "first-child"}, "I'm the first child"],
  ["div", {"id": "second-child"}, "I'm the second child"]
]
```

This is similar to the arguments of React's `createElement`. While it's possible to type the arguments array of a function and account for rest spread type... this doesn't seem doable in a standalone array. Meanwhile, tuples must be of fixed length. One solution would be to define this hypertext within call expressions:

```ts
h("div", {id: "parent"},
  h("div", {id: "first-child"}, "I'm the first child"),
  h("div", {id: "second-child"}, "I'm the second child"),
)
```

However, this format is more bloated. It doesn't convey the most minimal format for the data. My sense is that I should––for the time being––make use of `any[]`.

By the way, apologies if this is currently possible and I just did not find it! Looked for quite a while & no approach seemed to do the trick.

## Examples

```ts
export type HypertextNodeStructure<T, P, C> = [T, P, ...C[]];
export interface HypertextNode
  extends HypertextNodeStructure<string, {[key: string]: any}, HypertextNode> {}

const hypertextNode: HypertextNode =
  ["div", {id: "parent"},
    ["div", {id: "first-child"}, "I'm the first child"],
    ["div", {id: "second-child"}, "I'm the second child"]
  ]
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements support for recursive type references. For example:

```ts
type ValueOrArray<T> = T | Array<ValueOrArray<T>>;

const a0: ValueOrArray<number> = 1;
const a1: ValueOrArray<number> = [1, [2, 3], [4, [5, [6, 7]]]];

type HypertextNode = string | [string, { [key: string]: any }, ...HypertextNode[]];

const hypertextNode: HypertextNode =
    ["div", { id: "parent" },
        ["div", { id: "first-child" }, "I'm the first child"],
        ["div", { id: "second-child" }, "I'm the second child"]
    ];

type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

let data: Json = {
  caption: "Test",
  location: { x: 10, y: 20 },
  values: [0, 10, 20]
}
```

Previously, the above would have multiple circularity errors.

The specific change made by this PR is that type arguments are permitted to make circular references in _aliased_ types of the following kinds:

* Instantiations of generic class and interface types (for example `Array<Foo>`).
* Array types (for example `Foo[]`).
* Tuple types (for example `[string, Foo?]`).

A type `T` is said to be an aliased type when

* `T` is the right hand side of a type alias declaration, or
* `T` is a constituent of an aliased union, intersection, indexed access, or conditional type, or
* `T` is an aliased parenthesized type.

For example, in the type alias declaration

```ts
type ValueOrArray<T> = T | Array<ValueOrArray<T>>;
```

the type argument `ValueOrArray<T>` occurs in an aliased type instantiation that is a constituent of an aliased union type that is the right hand side of a type alias declaration, and the type argument is therefore permitted to be a circular reference.

An additional change in this PR is that when an array type, a tuple type, or an instantiation of a generic class or interface type is the right hand side of a type alias declaration, that type alias becomes the name by which the type is referenced in compiler diagnostics and quick info. Previously, such aliased types were always shown in their expanded form.

NOTE: For consumers of the TypeScript compiler APIs this PR is potentially a breaking change because it removes the `typeArguments` property from the `TypeReference` interface and provides a `getTypeArguments` method on the `TypeChecker` interface to be used instead. This change is necessary because resolution of type arguments in type references is now deferred.

Fixes #3496.
Fixes #6230.
Fixes #14174.
Fixes #28929.
Fixes #32967.

### CODE REVIEW

**Comment by falsandtru** [comment]
>with additional work it can be expanded to all type references.

To be clear, do you intend to resolve nested Promise types? Another, do you also intend to improve Array#{flat,flatMap}?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3904,14 +3907,18 @@ namespace ts {
...
 
                 function typeReferenceToTypeNode(type: TypeReference) {
-                    const typeArguments: ReadonlyArray<Type> = type.typeArguments || emptyArray;
+                    const typeArguments: ReadonlyArray<Type> = getTypeArguments(type);
                     if (type.target === globalArrayType || type.target === globalReadonlyArrayType) {
                         if (context.flags & NodeBuilderFlags.WriteArrayAsGenericType) {
-                            const typeArgumentNode = typeToTypeNodeHelper(typeArguments[0], context);
-                            return createTypeReferenceNode(type.target === globalArrayType ? "Array" : "ReadonlyArray", [typeArgumentNode]);
+                            depth++;
+                            const typeArgumentNode = typeToTypeNodeHelper(depth >= 5 ? anyType : typeArguments[0], context);
```
Comment (weswigham) [inline src/compiler/checker.ts]: We don't use straight `any` in situations like this in the node builder. Use `createElidedInformationPlaceholder(context)` (which appropriately swaps between `any` and the slightly more helpful and correct `...` based on context) instead~

Also this depth is a bad heuristic and will break declaration files - since it's counting global nested type references, a `A<B<C<D<E<F<whatever>>>>>>` won't serialize without deleting information, which is hugely problematic. The depth needs to be tracked per-symbol, at least (and ideally only per-type, if viable). There's already a map in `context` for this - `context.visitedTypes` for tracking exact types seen (which should be set on enter and unset on exit), and `context.symbolDepth` for tracking how many times we've visited a single symbol in the current stack (which should be incremented on enter and decremented on exit). The logic to handle them that's currently in `createAnonymousTypeNode` should probably just be extracted and reused here.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3904,14 +3907,18 @@ namespace ts {
...
+                            depth--;
+                            createTypeReferenceNode(type.target === globalArrayType ? "Array" : "ReadonlyArray", [typeArgumentNode]);
```
Comment (weswigham) [inline src/compiler/checker.ts]: This expression is unused - missing a `return` statement, perhaps?

**Comment by weswigham** [comment]
OK, so I expanded enough on this locally to try the 
```
type HypertextNode = string | [string, { [key: string]: any }, ...HypertextNode[]];

const hypertextNode: HypertextNode =
    ["div", { id: "parent" },
        ["div", { id: "first-child" }, "I'm the first child"],
        ["div", { id: "second-child" }, "I'm the second child"]
    ];
```

example out (which is a motivator here), and the approach quickly hits its limits - namely, when we compare tuples, eventually we compare the array methods on the tuple, which have `this` types - this `this` type for the recursive alias then expands _forever_ in instantiation, because `getAnonymousTypeInstantiation` eagerly applies type arguments to the object's captured type parameters (which un-defers them, which isn't an immediate issue, since their containing types now exist, but their structure is then problematic as instantiation doesn't keep any kind of "visited" stack, so will happily spin forever on the type (not knowing it needs to introduce a deferral anywhere). The un-deferal occurs because the `getIndexTypeOfType` call required for a rest parameter forces the type argument to the array to resolve before it's passed forward (while when the reference within the type argument is what is deferred, as in the other PR, this is no problem). [I've opened this with the diff of what I've added](https://github.com/microsoft/TypeScript/pull/33058)

**Comment by fatcerberus** [comment]
> `type ValueOrArray<T> = T | ValueOrArray<T>[];`

So is this an alternative to #33018?

**Comment by ahejlsberg** [comment]
@weswigham Latest commit changes deferred type reference instantiation to use the same logic as anonymous types. This ensures that deferred type references continue to be deferred when instantiated, and it fixes the issues you were seeing with infinite instantiations. The motivating example

```ts
type HypertextNode = string | [string, Record<string, unknown>, ...HypertextNode[]];

const hypertextNode: HypertextNode =
  ["div", {id: "parent"},
    ["div", {id: "first-child"}, "I'm the first child"],
    ["div", {id: "second-child"}, "I'm the second child"]
  ];
```

now works as expected.

I still need to look at pulling in the other changes in your diff. The `depth` stuff was just a quick fix I put in place, I agree it isn't the correct solution.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
RWC and DT runs look good. The baseline changes are expected and solely related to type aliases now being preserved and reported in diagnostics.

I think this PR is ready to merge.

As an aside, I'm actually wondering how to modify the DT tests such that they are insensitive to this PR. I'm not sure it is meaningfully possible.

**Comment by weswigham** [comment]
> As an aside, I'm actually wondering how to modify the DT tests such that they are insensitive to this PR. I'm not sure it is meaningfully possible.

I'm cases like these where essentially only the printback changes, I usually just modify the tests to use an assignment rather than an `ExpectType`.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -3724,11 +3725,17 @@ namespace ts {
...
+                    if (isReservedMemberName(type.aliasSymbol.escapedName) && !(type.aliasSymbol.flags & SymbolFlags.Class)) return createTypeReferenceNode(createIdentifier(""), typeArgumentNodes);
+                    return symbolToTypeNode(type.aliasSymbol, context, SymbolFlags.Type, typeArgumentNodes);
+                }
+
                 const objectFlags = getObjectFlags(type);
 
                 if (objectFlags & ObjectFlags.Reference) {
                     Debug.assert(!!(type.flags & TypeFlags.Object));
-                    return typeReferenceToTypeNode(<TypeReference>type);
+                    return (<TypeReference>type).node ? visitAndTransformType(type, typeReferenceToTypeNode) : typeReferenceToTypeNode(<TypeReference>type);
```
Comment (weswigham) [inline src/compiler/checker.ts]:
```suggestion
                    return !isNonDeferredTypeReference(type) ? visitAndTransformType(type, typeReferenceToTypeNode) : typeReferenceToTypeNode(<TypeReference>type);
```
just to be explicit about what's being checked here

**Comment by ahejlsberg** [comment]
The latest commits implement deferred resolution of type arguments in aliased references to generic classes and interfaces such that they can be self-referential. For example:

```ts
interface Box<T> {
  value: T;
}

type Foo = Box<number | Foo>;  // Previously caused circularity error

let z1: Foo = { value: 5 };
let z2: Foo = { value: { value: { value: 42 }}};
```

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this
@typescript-bot test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
Perf tests still show effectively zero cost and RWC and DT baseline changes are all related to type alias names being preserved in diagnostics. Seems it is fine to extend the feature to generic class and interface type references. It is also more consistent as there will be no difference between types written as `T[]` and `Array<T>`

**Comment by fatcerberus** [comment]
> I like the current syntactic solution because it is easy to reason about when it kicks in.

Easy to reason about, but difficult to abstract over.  I dislike syntactic solutions for that reason, it makes doing higher-order stuff more difficult 🙁 (I wouldn't generally care as much but the type system is already Turing complete which makes these kinds of higher-order abstractions more appealing).

**Comment by isiahmeadows** [comment]
@fatcerberus 

> Easy to reason about, but difficult to abstract over. I dislike syntactic solutions for that reason, it makes doing higher-order stuff more difficult 🙁

No new syntax is technically being added here, and @ahejlsberg was referring to when an implementation detail kicks in. The only thing this does is allow recursive type aliases, which involves zero syntactic changes, only removing a previous semantic restriction.

**Comment by jack-williams** [comment]
This is great.

Been trying to write [this](https://gist.github.com/jack-williams/53b3c5c53f8cef5a4bd856ef4ce0f167) for ages---now it's possible

**Comment by fatcerberus** [comment]
@isiahmeadows I think you misunderstand - I know there’s no new syntax, my point was that determining whether to enable a feature syntactically (i.e. based only on reading the AST without resolving types) *in general* makes it difficult to write higher-order abstractions over such features.

**Comment by fatcerberus** [comment]
@jack-williams To really type that properly I would probably want to use something like a [GADT](https://en.wikipedia.org/wiki/Generalized_algebraic_data_type) but unfortunately AFAICT those are really difficult to realize in TS because they rely on phantom type parameter(s) to enforce full correctness.  TS's structural typing means if you don't use the `T` in the data it might as well not exist.

But of course that's off-topic for this issue 😛

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by isiahmeadows** [comment]
@fatcerberus 

> @isiahmeadows I think you misunderstand - I know there’s no new syntax, my point was that determining whether to enable a feature syntactically (i.e. based only on reading the AST without resolving types) in general makes it difficult to write higher-order abstractions over such features.

I see now. I'll point out what you're referring to, mutual type recursion, is a *far* harder beast, and few languages have this capability outside of the FP world. In particular:

- C++ allows it only because the template system is very loosely typed. But compilers typically limit template instantiation depth to avoid running out of memory quickly, so this isn't usable in practice.
- Rust [has a few restrictions](https://doc.rust-lang.org/reference/types.html#recursive-types) for a mix of theoretical and pragmatic reasons, even though its type system is very much traditional FP at its core. They also have only nominal types with structural type aliases.
- Most FP languages support mutually recursive *nominal types*, but like Rust, don't support mutually recursive type *aliases*. For example, [Elm doesn't](https://github.com/elm/compiler/blob/0.18.0/hints/recursive-alias.md#mutually-recursive-type-aliases) and even [Haskell doesn't](https://stackoverflow.com/questions/8639353/haskell-infinite-types-and-my-fsm-function). I *believe* OCaml does, but don't quote me on it, and 
- Mutually recursive types in general are *very* difficult to implement. And there's entire deeply involved research papers dedicated to this topic, equirecursive types and their subtypes, [like in this 13-page paper about matching equirecursive types themselves](http://cristal.inria.fr/~fpottier/publis/gauthier-fpottier-icfp04.pdf) and [this 14-page paper about higher-order polymorphic lambda calculus extended with equirecursive types, records, and variants](http://ps.informatik.uni-tuebingen.de/research/functors/equirecursion-fomega-popl16.pdf). The second paper is a little further down the vein you're looking for, although it intentionally doesn't touch on subtyping. (Try reading those two papers and maybe a few they cite. It's not exactly as simple as it sounds. 😉)

**Comment by fatcerberus** [comment]
@isiahmeadows Oh, I don’t doubt the complexity of enabling mutual recursion.  I should have been clearer that it seems like *in general* TS is too quick to go for a syntactic solution, which often makes writing type operators harder than it has to be.  It was a general criticism of (what I perceive to be) TS’s overall direction, not only about this feature specifically.

That said I realize going for the syntactic route is often done for performance reasons and may be unavoidable with TS being implemented in an interpreted language like JavaScript so... *c’est la vie*.

**Comment by jack-williams** [comment]
> That said I realize going for the syntactic route is often done for performance reasons and may be unavoidable with TS being implemented in an interpreted language like JavaScript so... c’est la vie.

It's not simply a case of throwing more compute at the problem; with structural types it's not easy to even realise when you are in a divergent scenario.

**Comment by fatcerberus** [comment]
I guess that's true; with regard to this feature in particular, TS has to *know* the type is ultimately self-referential, and that's probably undecidable in general: Turing completeness, halting problem, the whole nine yards.  But since the usual case (direct recursion, i.e. inductive types) is trivially decidable from syntax, we can sidestep that issue.

I could liken it to undefined behavior in programming languages: per the 80/20 rule, you pretend the 20th-percentile stuff just never happens and then you don't have to bother reasoning about it in the compiler.  When your code proceeds to summon demons because you did the weird stuff anyway, that's on you 😅

**Comment by xiaoxiangmoe** [comment]
@typescript-bot pack this

**Comment by Kingwl** [comment]
@typescript-bot pack this

**Comment by steida** [comment]
Suggestion: In the changelog, it should be mentioned that this PR is only syntax sugar. True recursive types are still impossible and probably always will be without nasty hacks. So, for example, making union type from a tree with children is not possible.

**Comment by ahejlsberg** [comment]
@steida Can you give a specific example of a type you can't write?

**Comment by steida** [comment]
@ahejlsberg We have some schema and for render function with the exhaustive switch, it would be great to get the union of all types in a tree.

```ts
interface BaseElement {
  readonly children: readonly (BaseElement | string)[];
}

interface SchemaElement extends BaseElement {
  type: string;
  readonly children: readonly (SchemaElement | string)[];
}

interface LinkElement extends SchemaElement {
  type: 'link';
  readonly children: readonly (string)[];
}

interface HeadingElement extends SchemaElement {
  type: 'heading';
  readonly children: readonly (LinkElement | string)[];
}

interface ParagraphElement extends SchemaElement {
  type: 'paragraph';
  readonly children: readonly (LinkElement | string)[];
}

interface DocumentElement extends SchemaElement {
  type: 'document';
  readonly children: readonly (HeadingElement | ParagraphElement)[];
}

const doc: DocumentElement = {
  type: 'document',
  children: [
    { type: 'heading', children: ['heading'] },
    { type: 'paragraph', children: ['Foo', { type: 'link', children: [''] }] },
  ],
};

type UnionOfDocumentAndAllChildrenTypeRecursive<T> = ...?
type AllSchemaElementTypes = UnionOfDocumentAndAllChildrenTypeRecursive<
  DocumentElement
>;

```

**Comment by ahejlsberg** [comment]
@steida You can get pretty close with a manual unrolling up to some maximum nesting level:

```ts
type ThisAndChildTypes<T1> =
    T1 | (T1 extends { children: readonly (infer T2)[] } ?
    T2 | (T2 extends { children: readonly (infer T3)[] } ?
    T3 | (T3 extends { children: readonly (infer T4)[] } ?
    T4 | (T4 extends { children: readonly (infer T5)[] } ?
    T5 | (T5 extends { children: readonly (infer T6)[] } ?
    T6 | (T6 extends { children: readonly (infer T7)[] } ?
    T7 | (T7 extends { children: readonly (infer T8)[] } ?
    T8 : never) : never) : never) : never) : never) : never) : never);
```

Not super pretty, but it works.

**Comment by steida** [comment]
Thank you for the answer ♥️ I know we can have finite recursion only (and maybe it should be explicitly mentioned in TypeScript error with a warning it can be hacked, but the hack is not recommended, because it's misusing TypeScript because of turing complete types are as bad as turing complete smart contracts in Ethereum, no I am kidding, they are definitely not as bad). 

The question is, use finite recursion or no recursion at all. Anyway, thank you very much :-)

**Comment by steida** [comment]
The second issue I have with recursive types is how to make one prop from BaseElement (the id) recursively optional (partial). As far as I know, we can have recursively partial everything, but not only one prop. Am I correct?

**Comment by mysticatea** [comment]
I have tried the tar in https://github.com/microsoft/TypeScript/pull/33050#issuecomment-529416985 and found that `readonly T[]`  will be recursive errors.

```ts
// Type alias 'Test1' circularly references itself.
type Test1<S extends {items: any}> =
    S["items"] extends {items: any} ? readonly Test1<S["items"]>[] : []
// Fine.
type Test2<S extends {items: any}> =
    S["items"] extends {items: any} ? ReadonlyArray<Test2<S["items"]>> : []
// Fine.
type Test3<S extends {items: any}> =
    S["items"] extends {items: any} ? Test3<S["items"]>[] : []

```

**Comment by fazouane-marouane** [comment]
@steida I think the only hack needed now with the current PR is this
```ts
type Unbox<T> = T extends Array<infer TValue> ? TValue : T;
type ThisAndChildTypes<T> = Unbox<
  | T
  | (T extends {children: readonly (infer TChild)[]}
      ? Array<ThisAndChildTypes<TChild>>
      : never)
>;
```

@ahejlsberg it seems that inference doesn't play nice with `ValueOrArray`
```ts
type ValueOrArray<T> = T | Array<ValueOrArray<T>>;
function displayValueOrArray<T>(v: ValueOrArray<T>) {
  return String(v);
}
displayValueOrArray([5, ["6"]]);
```

Other than that, I could write any recursive type I needed with way less hacks than before
```ts
// Helpers
type PackTuple<T extends [...any[]]> = (...pack: T) => void;
type Prepend<THead, TRest extends [...any[]]> = (
  head: THead,
  ...rest: TRest
) => void;
type Unbox<T> = T extends Array<infer TValue> ? TValue : T;
type UnionToIntersection<U> = (U extends any
  ? (k: U) => void
  : never) extends ((k: infer I) => void)
  ? I
  : never;

// Union and Intersection
type Union<T extends [...any[]]> = Unbox<
  T['length'] extends 0
    ? never
    : PackTuple<T> extends Prepend<infer THead, infer TRest>
    ? Array<THead | Union<TRest>>
    : never
>;

type Intersection<T extends [...any[]]> = UnionToIntersection<Union<T>>;

declare function mixin<T extends [...any[]]>(...args: T): Intersection<T>;

// const testMixin: { x: number; } & { y: string; } & { z: boolean; }
const testMixin = mixin({x: 5}, {y: "hey"}, {z: true});

// Lenses
type LensResult<T, TKeys extends [...string[]]> = Unbox<
  TKeys['length'] extends 0
    ? Array<T>
    : PackTuple<TKeys> extends Prepend<infer THead, infer TRest>
    ? THead extends keyof T
      ? Array<LensResult<T[THead], TRest>>
      : never
    : never
>;

type Lens<TKeys extends [...string[]]> = {
  view: <T>(obj: T) => LensResult<T, TKeys>;
  set: <T>(obj: T, value: LensResult<T, TKeys>) => T;
}

declare function lens<TKeys extends [...string[]]>(...keys: TKeys): Lens<TKeys>;

const someLens = lens('a', 'b');
// const testLens: { c: number; }
const testLens = someLens.view({a: {b: {c: 42}}});
```

**Comment by cah-sberan** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot run dt

**Comment by cah-sberan** [comment]
@typescript-bot pack this

sorry everyone, just wanted to try this out, I'm very excited for this change.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
The issues in the DT test run are all unrelated to this PR.

**Comment by RWalkling** [comment]
Thank you so very much for this feature! Now we can do things like parameterizing a tuple type by its length, without having to hide from the circular conditional type police!
```typescript
export declare type TupleOf<T> = [T] | T[];
export declare type Unshift<Tuple extends TupleOf<unknown>, Head = never> = Parameters<((head: Head, ...args: Tuple) => void)>;

const recursionKey = Symbol();

interface RecursionInterface<T> {
    [recursionKey]: T
}

type Recurse<T> = T | RecursionInterface<Recurse<T>>;

type UnpackRecursion<T> = T extends Recurse<infer R> ? R : never;

type OfLength_<N extends number, Tuple extends TupleOf<never>> =
    Tuple['length'] extends N
        ? Tuple
        : RecursionInterface<OfLength_<N, Unshift<Tuple>>>;
type OfLength<N extends number> = UnpackRecursion<OfLength_<N, []>>;

type Quintuple = OfLength<5>;

```

**Comment by jcalz** [comment]
I don't see anything that says it's okay now to index into the recursive property so as to immediately flatten the nested type.  From what I can tell, this PR is intended to make it easier to create new arbitrarily nested types, not to make it easier to reach down arbitrarily far into a type.  Can @ahejlsberg comment on whether [the above](https://github.com/microsoft/TypeScript/pull/33050#issuecomment-535669967) constitutes an "acceptable" or "supportable" recursive type in TS3.7+?  Can the conditional circular type police really go off-duty? I suspect not, but I'd be happy to turn in my self-made badge if I'm wrong.

**Comment by j-oliveras** [comment]
@jcalz You can test it on playground, selecting version 3.7-beta.

For example, [the code from the comment before yours](https://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbAFQFcxVgB5AMwB5CA+OAXjgG1CBdOAHzkNY4BuALAAoUJFiIUGLDnzYAqgDsAzgAsAllRh1S5OKBjBlCVX32VaxZQGtlEAO7L6AGjgAJYOgTM4y4AA3YChGFgAFTHQAW2BjKFUaAAok9W8EAC5PdPcAOnzMAHNVLJIyYABKZkZAiE0ECvoRUTFkCDV4LGRiBM12gGlgXD8AZVxogCMIVCSK5rFNZXiqdGRsACUUHtU+5QBJJZCVtbpGAG8xOCu2Lu3dwdwOUrEAXzExPAI4Te6E4FO-IQeN8tr12gdlqt-j9tv8GE13qJPkplGBVrYYWDlACWECjCYzCDfqp-osqCFvowAPzfOBZALBKDzJEKODUAAyJkKMHUAH0aAA5QwgYymczKYiTELuMoGfFiizlag0BkhehhS7XWXAVgAcnIym56l1XHlhIFmuu1xp2stVrpRLu4MOUGO-w5XJ5-IF7hUGm0um16oRLK+HsNPMFwtFhIlUtCfhUaOQGNBO3aNHDRu97gE6uZyLgAEViIsYJY-FnIwBWENAA).

**Comment by jcalz** [comment]
Sure, but I’m not asking if it works.  I’m asking if it’s supported.

**Comment by RWalkling** [comment]
🚨 Oh no, I've been found out! 🚨

In my defense: Wasn't the problem with conditional circular types, that circular types should have been forbidden, but the complex conditionality spooked the compiler into looking the other way? If so, then this PR resolves that by explicitly allowing circular type aliases. Although you're right, that the jury is still out on the recursive inference (type flattening). It would be so cool to see it approved though, even if you can only use it for tailrecursive types, it's still extremely simple yet powerful.

**Comment by jack-williams** [comment]
@jcalz What is the type in question, this?
```ts
type OfLength_<N extends number, Tuple extends TupleOf<never>> =
    Tuple['length'] extends N
        ? Tuple
        : RecursionInterface<OfLength_<N, Unshift<Tuple>>>;
```
If my reading of @ahejlsberg's spec is correct, this is legal under the follow points:
> permitted to make circular references in aliased types of the following kinds:
> - Instantiations of generic class and interface types (for example Array<Foo>).

The recursive type appears as a type parameter to the interface `RecursionInterface`.

> A type T is said to be an aliased type when
> - T is the right hand side of a type alias declaration, or
> - T is a constituent of an aliased union, intersection, indexed access, or conditional type, or

`RecursionInterface<OfLength_<N, Unshift<Tuple>>>` is an aliased type as it is a constituent of an aliased conditional type.

...maybe I'm missing something.

The accompanying tests also include circular (but guarded) recursive conditional types.
```ts
type T15<X> = X extends string ? T15<X>[] : never;
```

**Comment by RWalkling** [comment]
@jack-williams 
The controversy is about the type
```Typescript 
type UnpackRecursion<T> = T extends Recurse<infer R> ? R : never;
```
which flattens a (theoretically) arbitrary length cascade of 
```TypeScript
Recurse<Recurse<Recurse<...Recurse<ContainedType>...>>>
```
Into simply `ContainedType`. The question is whether this kind of recursive inference is sanctioned by this PR or if it is an unfortunate side effect that should not be relied upon (just like circular conditional types).

**Comment by Himself65** [comment]
A recursive type example:

```ts
export type UnwrapRef<T> = T extends SomeType<infer V>
  ? UnwrapRef<V>
  : T extends Array<infer V>
    ? Array<UnwrapRef<V>>
    : T
```

this type is incorrect but how to solve it?

**Comment by RWalkling** [comment]
@Himself65 
From the description in the very first post (the PR):
> The specific change made by this PR is that type arguments are permitted to make circular references in aliased types of the following kinds:
>
>* Instantiations of generic class and interface types (for example Array<Foo>).
>* Array types (for example Foo[]).
>* Tuple types (for example [string, Foo?]).

This is violated in the second line of your code.
You can get around this by doing what I did in my previous comment (I simplified it somewhat from the original formulation):
```TypeScript
export interface Plain<T> {}

type Recursive<T> = 
    | T 
    | Plain<Recursive<T>> 
    | SomeType<Recursive<T>>
    // add any other types to unpack here

export type Flatten<T> = T extends Recursive<infer R> ? R : never;
```
And then you can use them like this:
```TypeScript
type UnwrapRef_<T> = T extends SomeType<infer V>
    ? Plain<UnwrapRef_<V>>
    : T extends Array<infer V>
        ? Array<UnwrapRef_<V>>
        : T
export type UnwrapRef<T> = Flatten<UnwrapRef_<T>>
```
But keep in mind, that while this does work at the moment (in TS 3.7), this kind of recursive inference is not (yet) officially confirmed to be supported (see the previous few comments). Hope that helps!

**Comment by RWalkling** [comment]
@Himself65
Additionally, if you want to not only unpack the inner most type, but also keep the containers along the way, you can generalize the `Flatten` type like this:
```TypeScript
type Flatten<T> = T extends Recursive<infer R> ?
    R extends Set<infer S> ? Set<Flatten<S>> :
    R extends Promise<infer S> ? Promise<Flatten<S>>
    R extends SomeType<infer S> ? SomeType<Flatten<S>> :
    // add any other types to unpack here
    R : never
```
This type removes all `Plain` type constructors and passes through `Set`, `Promise` and `SomeType`:
```TypeScript
type ResultOfRecursiveType = Plain<Promise<Plain<Set<Plain<Promise<Promise<Plain<Set<Set<string>>>>>>>>>>
type FlattenedType = Flatten<ResultOfRecursiveType> 
// above is Promise<Set<Promise<Promise<Set<Set<string>>>>>>
```

**Comment by Himself65** [comment]
@RWalkling thanks a lot. I got the point now

**Comment by hmaurer** [comment]
```
type Foo<T> = T[]
type Bar = Foo<Bar> | string;
```
This seems to still throw a circular reference error, even though `type Bar = Bar[] | string` does not throw on 3.7?

**Comment by ahejlsberg** [comment]
@RWalkling @jack-williams @jcalz Make sure to use the actual 3.7-beta in the examples being discussed above. In #33678 we fixed our type inference logic to guard against runaway recursion caused by recursive types, and that definitely has an impact on the patterns above.

**Comment by acewert** [comment]
I'm probably misunderstanding either `Record` or what cases this PR is supposed to fix, but is there a reason why this compiles on 3.7.0-beta:

```typescript
type StringOrKeyedString =
    | string
    | { [key: string]: StringOrKeyedString };
```

But this does not?

```typescript
type StringOrKeyedString =
    | string
    | Record<string, StringOrKeyedString>;
```

The latter still gives a "Type alias 'StringOrKeyedString' circularly references itself."

**Comment by jack-williams** [comment]
In the first example the recursive reference is guarded within an object.

In the second example the recursive reference is an argument to a _type alias_ and is not known to be guarded. TypeScript wont peek inside the type alias to see if it binds an object type.

If you want to get rid of the object literal you can use an interface type instead:
```ts
interface RecordI<T> {
    [k: string]: T;
}

type StringOrKeyedString =
    | string
    | RecordI<StringOrKeyedString>;
```

This basically falls under the requirement:
> Instantiations of generic class and interface types (for example Array<Foo>).

**Comment by RWalkling** [comment]
@acewert 
As per the specification (first post):
> The specific change made by this PR is that type arguments are permitted to make circular references in aliased types of the following kinds:
> - Instantiations of generic class and interface types (for example Array<Foo>).
> - Array types (for example Foo[]).
> - Tuple types (for example [string, Foo?]).

The first example you posted is an interface type, so it works. The `Record` type however is just a type alias (it is defined with `type`), so it does not fulfill the criteria as outlined above. I can only speculate as to why this decision was made, but I guess it's because type aliases can act as type operators (for example they can map over another type), while interfaces are purely declarative, so this way the compiler doesn't have to handle recursive type operators, which are too good to be true and so aren't allowed to 
exist... :cry:
_To be fair though, these beasts are actually pretty hard to tame; there are tons of papers published about recursive type operators and I guess the TS team does not want to get into that rabbit hole, as therein madness lies_

**Comment by pleerock** [comment]
@ahejlsberg unfortunately this PR doesn't fix what I expected (and I guess I'm not alone here). I would like something like this to work:

```ts
type Model<T> = {
}

type Schema<T> =
    T extends String ? string :
    T extends Number ? number :
    T extends Boolean ? boolean :
    T extends Model<infer U> ? Schema<U> :
    never
```

is there opened feature request for this type of recursion or it's not possible to implement it at the moment? [Here is a real world example](https://github.com/pleerock/framework/blob/master/framework/core/src/types/core.ts) how this feature can improve experience (duplication, easy of maintenance and refactoring) by removing half of the code in this file.

**Comment by Himself65** [comment]
@pleerock 

It's the same thing with my issue #34555 🤔

**Comment by jcalz** [comment]
I think #26980 is the open issue for circular conditional types.

**Comment by loganpowell** [comment]
Up until this PR, I've been a TypeScript skeptic. Count me in.

**Comment by Anber** [comment]
Why it's not possible to do something like this?
```typescript
interface IState<
  TResolvables extends {},
  TParent extends IState<any, any>
> {
  parent?: TParent;
  resolve?: {
    [T in keyof TResolvables]: TResolvables[T];
  };
}

type Resolves<T> = T extends IState<infer TResolvables, infer TParent> ? (TResolvables | Resolves<TParent>) : never;
```
It generates two errors:
1. Type alias 'Resolves' circularly references itself.(2456)
2. Type 'Resolves' is not generic.(2315)

**Comment by zheeeng** [comment]
Can we infer the type on recursively passing the function's returned value as closure value to its parameters like this issue: https://github.com/microsoft/TypeScript/issues/34910?

**Comment by zheeeng** [comment]
Is it possible that inferring a type that is referenced by/fed to itself?

```ts
type RefSelf<Input extends Record<string, (...args: any[]) => unknown>> = {
  [k in keyof Input]: () => ReturnType<Input[k]>
}

declare function calculate <
  Input extends Record<string, (self: RefSelf<Input>) => unknown>,
>(input: Input): RefSelf<Input>

const { fourtyTwo, fourtyTwo2 } = calculate({
  fourtyTwo: () => 42,
  // (parameter) self: RefSelf<{fourtyTwo: unknown; fourtyTwo2: unknown;}>
  // (property) fourtyTwo: () => any
  fourtyTwo2: (self) => self.fourtyTwo(),
})
```

**Comment by SamuraiJack** [comment]
I believe 5% performance is very acceptable trade for this feature (is it outside of the margin of error at all?). The recursive type references should just be enabled for all cases.

**Comment by icehaunter** [comment]
@RWalkling hey, sorry to be a bother, but I have a question in regards to your unwarp construct. I have successfully converted a tree-like structure into a recursive nesting of `Plain<Plain<...> | MyType<'a', 'b'>>` values. Unfortunately, using released TS 3.7, your recursive inference
```typescript
type Recursive<T> = 
    | T 
    | Plain<Recursive<T>> 

export type Flatten<T> = T extends Recursive<infer R> ? R : never;
```
did not work for me, instead producing the same type I passed into the `flatten`. Could you advise as to how can I unwrap the nested `Plain` objects? I need a union of all `MyType` instances in the tree. 
Thanks a lot!

**Comment by isiahmeadows** [comment]
@icehaunter Try recursively extracting in `Flatten<T>` instead. That's what I would've normally done before this PR, and it's also simpler.

```ts
export type Flatten<T> = T extends Plain<infer U> ? Flatten<U> : T;
```

**Comment by icehaunter** [comment]
@isiahmeadows that doesn't work, because of error "Type alias 'Flatten' circularly references itself". Because the recursive type usage is not inside an interface.

**Comment by isiahmeadows** [comment]
@icehaunter 🤦‍♀️ Try this. (That was untested, obviously, and so is this.)

```ts
type Flatten<T> = {
	0: T,
	1: T extends Plain<infer U> ? Flatten<U> : never,
}[T extends Plain<any> ? 1 : 0]
```

If it weren't so difficult and time-consuming (as basically every type system more complicated than C or Hindley-Milner is), I'd reimplement TS myself using proper deductive types with `infer` being proper mathematical induction.

**Comment by moshfeu** [comment]
I still get `Type alias ... circularly references itself.` when type created with Intersection. For example:

```ts
type TreeNode = {
//   ^--------^ Type alias 'TreeNode' circularly references itself 
  [key: string]: TreeNode | [string, string],
} & {path: string};
```
[playground](https://www.staging-typescript.org/play?#code/C4TwDgpgBAKgThCA5A9gEwgdQJbABYAKAhvlALxQDeYJeAXFAM7BzYB2A5gL4DcAUKEiwEydNAqU+UKAG0A1hBANmrTgF0G8RKgxQAPrJXsOAGiYtjak3y5QAZFRr5lFzryA)

**Comment by trusktr** [comment]
Doesn't seem to work:

```ts
type UnknownProps = Record<string, UnknownValues>
type UnknownValues = unknown | Record<string, UnknownProps>
```

```
Type alias 'UnknownProps' circularly references itself.ts(2456)
Type alias 'UnknownValues' circularly references itself.ts(2456)
```

**Comment by jack-williams** [comment]
@trusktr 

In the opening comment by Anders the definition of the new kinds of types that can be circularly referenced are defined as:
> Instantiations of generic class and interface types (for example Array<Foo>).
Array types (for example Foo[]).
Tuple types (for example [string, Foo?]).

The type `Record` is a reference to a mapped type from an alias, rather than an interface or class.

It is still the case that TypeScript is not going to resolve arbitrary symbols because there needs to be some indication that the recursion in guarded by something.

**Comment by trusktr** [comment]
Interesting. Also here's another way to write it:

```ts
type UnknownProps2 = {[K in string]: UnknownValues2};
type UnknownValues2 = unknown | Record<string, UnknownProps2>
type StartValues2 = {[K in string]: number | Array<number> | StartValues2};

const test2: UnknownProps = {a: 1, b: {c: 2}}
```

[playground](https://www.typescriptlang.org/play?#code/PTAEBEHsFMGdQHaQC6gO6QE4GsB0AoZATwAdpQBVBbJNBABU0hPgF5QAlaAYywBMAPLGSYAlggDmAGkrVaCAGoBDADYBXOAD5CpclRqQ6y9XFDs1cwwlAAfTj35CR46bIN1GzWNuJlQAZWQlTGRjDTZ7XkxBYTFJGQQ1AFsAI2hMW1AAQUxMJSIBRNT0zUzA4NDVcO18XgRhUGQ4ZAAuN3lPFjNQAG8lNoBGGRS2nu42gCYAXyn8fBBQAElUDBxYAEIdP30OphYJ7p6AbQBpUHFQWJcAXTadqzC4aYBuLb1LIyqn7ot3azsuFEYs54u0rJ1YBMfLoAkEQo9IYdTudrFdJLdEMk0hk7Dk8gUitjSnZyvCvpCpq9apB6qgmsIJncPgw9hE+oNhqNxqBplMgA)

**Comment by RobertFischer** [comment]
This is still throwing a circularity error in 4.0.5.

```typescript
export type Unpromise<T> = T extends PromiseLike<infer U> ? Unpromise<U> : T;
```

**Comment by mindplay-dk** [comment]
I do wish recursive types were possible *with inference* - for example, why can't [this](https://gist.github.com/mindplay-dk/64e1f07028c1749e06c4fc2fa8cea785#file-di-sync-ts) be type-hinted without explicitly having to declare a `ServiceMap`? It doesn't add any new information to what can be inferred from the return-types in the factory functions (line 29-30) so why should I have to declare this up front? The shape and return-types of the object I pass to `Container` can be inferred, so why doesn't that lead to a known type for `$` in those function expressions? So long as `$` doesn't affect the return-type of those closures, there's no "feedback loop" in the definitions of those types, so why doesn't that "just work"?

**Comment by MerwaneHAMADI** [comment]
@mindplay-dk yes I agree I don't see why it wouldn't be possible to infer that. Feel free to create an issue for this.

**Comment by nicobrinkkemper** [comment]
As far as I know, this code can not be implemented recursively. It can be done for the return type, but that would break the inference of the parameters.
```ts
const guardAll = "not implemented" as <A, B, C, D, E, F, G, H, I, J, K>(
	guard1: RefineTypeGuard<unknown, A>,
	guard2?: RefineTypeGuard<A, B>,
	guard3?: RefineTypeGuard<B, C>,
	guard5?: RefineTypeGuard<C, D>,
	guard6?: RefineTypeGuard<D, E>,
	guard7?: RefineTypeGuard<E, F>,
	guard8?: RefineTypeGuard<F, G>,
	guard9?: RefineTypeGuard<G, H>,
	guard10?: RefineTypeGuard<H, I>,
	guard11?: RefineTypeGuard<I, J>,
	guard12?: RefineTypeGuard<J, K>
) => (value: unknown) => value is A & B & C & D & E & F & G & H & I & J & K;

type RefineTypeGuard<A, B> = (
	value: A,
	...args: readonly unknown[]
) => value is B extends A ? B : never;
// create new predicate by combining them in order, 
const isFoobar = guardAll(
        // Don't have to tell TypeScript what the value of val is, it is inferred from the last predicate
	(val): val is string => typeof val === 'string',
	(val): val is `foo${string}` => val.startsWith(val),
	(val): val is 'foobar' => val === 'foobar'
);
const test = {} as unknown;
if (isFoobar(test)) {
	test; // "foobar"
}
```

**Comment by TylorS** [comment]
@nicobrinkkemper Is this the sorta thing you're looking for? [Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBKwBmBLAdsAW2FxgB4BBAGjgCEA+OAXlrlBmIBMBnOcgKDhwA-HAAUAQwBcvAJRMG4uNh40BcaQG81gwcChRo0gNoADAKq5xAIwA2qGBDhQseYCepU4AIgdfqNAF0Abm04AF8QvlBIWARkVAAJYHEOcigAc1IAFQZmLNYQdlxuMQA6cvEMrmk8TD1eKrlGBVxENRE09K4jAAYAtWl8ADc9SOjoeCQUdGAYAFcoXAB5TGzcuHy2Th4MHHwiElJxVupa+rQGETR1OGHRvijwCbjpgBlxLjIcpg2CopLnCkILgbIg4EZyqVRICOMDQXBjogjAEZKdcHUoOh+oIrgNbsARlAxk9YlNUABxOaVDgANXENjmwC4pDU5D+2xmQJBiDSUHEiFIu1cBzIiOoiLodEoamuW2KPBhcLBiORPyMSRSnQovQCdH66zZcoByVh3PBZ0xGo41EhFo24mwNmxwjglOpdIZTJZOh0WQdNnZ8s5ptBvP5gpc+2IopOCNakpdfsdNzuUGlPsEEPKaGoGHmixWpCtetCdDxaGJMUm8TgHuwHHE7A9jOZrMDxq58JVAXT6B+iL4BvbCpNSvN6PqVpt5TtSad7TgVuH6FCIjrDab9Jb2X91GLoU0rH0hnB5kstnsjmcezcueoPggfkXJoC4TxMCgjMrzzJrqpUFSGwbG9XhlwwTseX0cMhSjQ4xTjRBJV7a5mHXRtgGbL03QAzDmXISVBx+WVCg5D9GRdCRpCtLVyB1OgmgYPMFmWVZ3k+CgE2kCsHgAY2BT44HSf9AIDZgKDA0duTDAUYMIaMjljCVJVENRISE6lql4PgZGkbCRI4+Q4C0QRnHzXAxFEbAqJNGi6IYozQkwaAxD43ABPSOAIEwQThK4ORjIzbBvNEABCdJLJkfzQh9UzmLgTB6S4YAQgzN8fTCB4YtmOKyOStQwjkD4-2pcggI4kIIl4-j4GUABlD88A85hRCGelpDmXAAGtcAgAB3XAdLgVqA2UOBPigRrDLJLyhvpJhGGYLxxsarwQlcgTPkqGAuAAdWwGAAAsADEIEcZrhukZbcHSQbhqUHgTCciAABINCu9IwhMeQ1GG0pNtgXb9oOlr6RkNbqvuk6ICsSofhBmxLoa67brm0avCemGoC8Qy7oWxaMcqVaqrcmquChzG9J+dSANKmxLK4eqJuu6h-u2vbDqh04ydOzGweJgTlAAOTmAgrHqc6t2Adqup6-qUc9e7bhFsXMWaF5gBm4byLx7xcGVvQib4dbSYASVwYb60p5hqZE+nGcalmYC2wGOdOrnhdFvQ+aAA)

**Comment by nicobrinkkemper** [comment]
> @nicobrinkkemper Is this the sorta thing you're looking for? [Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBKwBmBLAdsAW2FxgB4BBAGjgCE5QZiATAZznID44BeOACgCGALnYBKHlwFxsbGgCg5oSLATJUACWACm5KAHNSAFS69D9EI1yt+AOjsD9LEXkzAo7R+O6TciOXDgAfg89FgBtAAYAXX84EXwANzcAbgUlaHgkFHRgGABXKFwAeUwjEzgzBmY2DBx8IhJSAV9qFzd0LmC0OLhElLTwDNVsgBkBFjJjHgrzS2soLSYIXAAbRDgwuxs+Be1ltbhmxDCo0VbcV3c0GICu2PjgJKhUxUGVLNQAcTyHJgA1AQrPLAFikWLkWbVHJ7VaIXRQASIUi1PCEYhkI7UI4cDiUWLdKpWNi7Jaww6+E7TMKabS6AzkSJRDgxcoQwnzRb7dZhNruGlMahbXkVATYFY3IJwb6-AFAkFggKKkViyFE6GktbwxHIrCohoYlrkxA4yWGUUrHp9KB4pUBTZ2NDUDD5QolUj85mxAIce7oF7pd5qOCy7BMASMWXA0Hg1UcmEHI4nG3oaZHOSs2PEzlknkXdr8wV2YVmsUS4L8zPoL2SkNhiOAqNGc3UD3VkQAb3oUCg0BEYQABgBVXACABGK1QMAgcAWdWA-ad1AARFOly3FlE4ABfX0wKDA-1vTJB6VQHQrFYK9iVjDxuHd7Uo+ropqG7G4-HTWvh4CR+Wn-4G3lTgfXKAkLChPdgUlQQRH5OkKEZDgvC4Z0CmKUoxgmCgTRENAXgAY2WCY4D0H4z3IC9pgoG9s01B8kSfNFGkxI0cQ4PhYi2Mjficdg5FEEQAMoy9OAkOB21iBYXVwfg+GwODFgQhlomQ8TJKVTBoH4IjcBIvQ4AgTBSPI1hxA021sGMvgAEI9Hk0RzOrJVpPQuBMEBFhgFSW1t2rHdq1cwoEH3bzYi3cRxilUyRJw1It0I4j4BkABlPc8AM3g+ASQERDyXAAGtcAgAB3XBBLgHKLRkOAJigDLxI+IzKsBHhuF4Jc6oypdUl0kiJgcGAWAAdWwGAAAsADEIGnLKqpELrcD0CqqukNh+y0iAABJ20WvQt37CRYiqmwBtgEaxvG7LAVEXqkrW6aIFHBxpmulYFvSpaVtamql0256oCXcTVvajr-ocHqFD65KWEegGAOmHiKIveSWDS+qluoM6htGibHtaWGZoB26ofumQADk8gIUd2jmoC8sK4qyu+uU1t6KmafcbxhmAZqqug0G4CXXAObcSG5GhtaAElcCq0MEd4JHzxWVH0YyrGYEGi68ZmgnKeptwSaAA)

Not exactly. See this example and hover over the functions in `guardAll` and you can see that the predicate of the first is passed to the next and so forth

[https://www.typescriptlang.org/play?#code/PQKhCgAIUhBSAuBPADgU0gewHaQO4AWAlgMYGQAqqGA4gK4CGATgCaQC2DSkaAHgmmwsAdFBDBwLNCQA2zDMnRxsSKunrM2AXkgAKcAEgAbgxl00ALkgMVAGkPDHzAOYBnK0zQMWOGdxtIANoAuuAAlJBaAHyQJmYYRK7WKgDc4OCKGAAKROgsamgarAA8sLaQAEIxOvrGpuZWZQ5OTG4eXj7YfpB02ADW2Jh42CHhkTFx5pCJlTz8gixJ8AD8s1bYaEZoTGngoBDQcIjUiAQMCNaQRWx4RDIy1q6uRM64CJiXJkxEDABGMmhRNAJFJZPJjkprgVitc5gIhEkAtUroxWHCFklapNLD1+oNhvYDI5hC53JBPN5fP4VKMItFYvUEkkiNgAGbbSAAVUMq25BnWm22aUgIsgezAYiuRC2uAY1iYTC4WFZlGoSWurnKt3u5LQCDoTFl02wAiYrmkCCIOGV1h1CAItFRbAKriB4gyJwAwph2L8WYUndDDLAFeiEZAAEodKkhxVIUoqArXKKEqOuOgyC46XoDIbYcDI2Nhxa6yldbijAyrNMZhCGRqhvjwksUzrdQIs9lMSAACQ65WJnY5FAYd1CVcoo4eTYxpbb3Fgieo10rE+9vv9UOoxRHd3KNczkAAZCjNNC+94olFDPzIBstkx63fBTt0vtJTRpYIsBssN32LWuQAqqkJOoiiIKlw5SePqhqIiBjqaKc5yQGQ0h9MyKr2hgzhfrg2IcOcaGIjquEyghp6sK6YgSCQOCuBczhOrA9wAJK4FohgwmBxZJK2VLKKoy5OiEUS6ExmhkhqdLXgYujYlYOb4tgYRWARMzrn6Gxbug3GSdUskGBJVHCKyLIsOxUi8Lo4lOjJkAAITGSw8mMmEdJaDoAC0ACMux0dgDGQM5LEPDoelUbxc4CYuQnqCJwRicSzlSWBMmGCFbHYLZklhLsmSUSwOToAAYhxIqlOUFTlJ65QACLlAAouUJXlDQ5Q9uUrHlAAUuUADSYlQKKzk+VYxVoPkwmaMUSl5uUsApsNIrOQATMs425JNSZOpVlRLaKwVOgAzBtkATVN8UzdVkCegdI1OgArGdF07TNtWQHV90rU6ABsL1bZdAYzQ1kCNd9R2aAA7ADeRvSUzWQCVEPOQAHLD23TSUrVXCjToAJwY0D1wwh1eOaD5AAMRPwywxSdZArHk6wPk+TTWN091kA9czLA+etm1wxzxR9ZAg1jPSrnxIpeJ5vZ6lLMeswnp6St1UrjVKyVSs0ErPZK6xSs9Ur-W7MAwCIGgDHgAFQXORNkSQ6woWPIVE1lWktsXIkJWYJgvzMI79tbbU5sMjIMu5sMhhS6p4fTEkDHfNgzjjBCaCYCqcSRJ5kAAORJyyzh54SYdxFYhcpzHcRx9nMwAAasn7AAkADelfOAAvvXadxMIDHMAgrgAOpEPauh503mB52EpcW+XkCNy37cIMnXf19Xpi16YCf51PAdMHnvc755OiT37B95+Env0RcAhBTored67c3DGkRAqroPsX8wuj3wg7lICt0MP-FIkAw4ACJ97MAgeATu4AgA](Playground Link)

**Comment by TylorS** [comment]
@nicobrinkkemper That's the purpose of `ValidateValues` in my playground link. It goes through the predicate values and fails if the next value is not a subtype of the previous. AFAIK this is the only way to do this kind of thing generically..you have to teach the compiler how to do that validation.

**Comment by nicobrinkkemper** [comment]
What I'm talking about is the limitation to infer the parameters of the Type Guard. In your playground link (which is nice don't get me wrong) you are forced to type your parameters. In my playground I don't have to specify them, and if you hover over them you see the type of the previous predicate. This would mean that any invalid function will be catched right there on the spot and it would show a red line under that specific offending function. 

For example if I add a invalid function to the pipe in my playground example, it shows:
```
Argument of type '(val: `foo${string}`) => val is number' is not assignable to parameter of type 'PipedTypeGuard<`foo${string}`, number>'.
  Type predicate 'val is number' is not assignable to 'value is never'.
```

**Comment by TylorS** [comment]
Ahh, I see now what you mean about the differences and why you might not be interested in that particular implementation. I have some similar code to that playground, and yeah the errors end up being moved to the `if` statements I use them in since `{ error: ...}` is not a boolean expression and its caught by my ESLint configuration

**Comment by 4t4nner** [comment]
With _Record_ still causes error:
`type Obj1 = Record<string, Obj1 | string> // error
type Obj = {
	[key: string]: Obj | string
}; // fine`
