### PR TITLE
fix(3758): Object literals in an assignment pattern do not get completions

### LINKED ISSUE #3758: Object literals in an assignment pattern do not get completions
As mentioned by @JsonFreeman in https://github.com/Microsoft/TypeScript/pull/3698#discussion_r33834234, completion at the cursor in the following example should list `a` and `b` (and I believe with no builder allowed).

``` TypeScript
let x, y;
let z = { a: 10, b: "20" };
let k = (100, { /**/ } = z, 300);
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #3758

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Holy crap, I didn't expect this one to ever get fixed.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I noticed this issue a couple of weeks ago and suddenly found an open issue on GitHub that I had in my _backlog_ :smile:

File: src/services/completions.ts [hunk 1]
```diff
@@ -2830,4 +2832,15 @@ namespace ts.Completions {
...
     }
+
+    function tryGetObjectLiteralContextualType(node: ObjectLiteralExpression, typeChecker: TypeChecker) {
+        const type = typeChecker.getContextualType(node);
+        if (type) {
+            return type;
+        }
+        if (isBinaryExpression(node.parent) && node.parent.operatorToken.kind === SyntaxKind.EqualsToken) {
+            return typeChecker.getTypeAtLocation(node.parent);
+        }
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:2843]: Technically we're relying on the fact that there will be a contextual type on the RHS of an `=`, so that we must be on the left side of the `=`. Not sure if that's an issue long-term.

Comment (a-tarasyuk) [reply src/services/completions.ts:2843]: You are right. I can change to `typeChecker.getTypeAtLocation(node.parent.right);`. Do I need to do it?

Comment (DanielRosenwasser) [reply src/services/completions.ts:2843]: It's not so much that - the `=` will always return the type of the right operand. It's more that you want to check that `node.parent.left === node`, but it's up to you. I don't think it'll be a problem long-term.
