### PR TITLE
fix(39858): "Convert to async function" refactor generates invalid code with imported functions

### LINKED ISSUE #39858: Bug: "Convert to async function" refactor generates invalid code with imported functions
**TypeScript Version:**  3.9.2, 4.0 beta

**Search Terms:**
Convert to async function, refactor, quick fix
**Code**

```ts
import { identity } from "underscore"

function fetchZero() {
  return Promise.resolve(0).then(identity);
}
```

**Expected behavior:**

Running the "Convert to async function" Quick Fix on `fetchZero` should produce
```ts
async function fetchZero() {
  const value=await Promise.resolve(0);
  return identity(value);
}
```
(or something similar). This is the behavior if `identity` is defined in the same file, with a first parameter named `value`.

**Actual behavior:**

Running the "Convert to async function" Quick Fix on `fetchZero` produces
```ts
async function fetchZero() {
  const identity=await Promise.resolve(0);
return identity(identity);
}
```
which produces a TypeError with `identity(identity)`. This is the behavior if `identity` is imported.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?ssl=5&ssc=2&pln=1&pc=1#code/JYWwDg9gTgLgBAbzsAJgUwHY2DAnnAXzgDMoIQ4AiAVw3SgGcBjaNSgKHeNqewgxJoYTABYAtNGQAUASkTs4cKEOpQBABTIhgDNADplDCABsAbmikAGGXpgjMU1Jmx4ZAbnYEgA

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/39589 is another issue with the "Convert to async function" Quick Fix.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39858

### CODE REVIEW

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 1]
```diff
@@ -156,11 +160,8 @@ namespace ts.codefix {
                 forEachChild(node, visit);
                 return;
             }
-
             const symbol = checker.getSymbolAtLocation(node);
-            const isDefinedInFile = symbol && declaredInFile(symbol, sourceFile);
-
-            if (symbol && isDefinedInFile) {
+            if (symbol && (declaredInFile(symbol, sourceFile) || isImported(symbol))) {
```
Comment (sandersn) [inline src/services/codefixes/convertToAsyncFunction.ts:164]: if `symbol` is defined, what other options are there besides imported or declared-in-file? Can we get by with just `if (symbol)` ?

**Review by sandersn — CHANGES_REQUESTED** [review]
Question about the predicate to use.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/codefixes/convertToAsyncFunction.ts:164]: Good question. I thought about that option, however, decided to extend the condition with `isImported`, because `declaredInFile` was added for some reasons, maybe to exclude global declarations - not sure.

Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts:164]: If it is actually excluding things like global declarations, let's leave it, but otherwise, seems fine to take out.

Comment (a-tarasyuk) [reply src/services/codefixes/convertToAsyncFunction.ts:164]: I can try to leave `if (symbol)`, if all tests will work I push changes, otherwise will leave these changes as is. @sandersn  
@uniqueiniquity Is it ok?

Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts:164]: I'm fine with it, but I'll defer to @sandersn here.

Comment (a-tarasyuk) [reply src/services/codefixes/convertToAsyncFunction.ts:164]: I've checked and all tests (`convertToAsyncFunction`)work fine. @sandersn

Comment (a-tarasyuk) [reply src/services/codefixes/convertToAsyncFunction.ts]: I've pushed changes without `declaredInFile`, `isImported`. @sandersn if you think the previous changes are better, I can return them.

**Review by sandersn — APPROVED** [review]
