### PR TITLE
fix(jsx): correct source location when react-jsx and whitespace before jsx

### LINKED ISSUE #61533: Wrong location generated for JSX with whitespace around it when react-jsxdev
### 🔎 Search Terms

react-jsxdev, jsxdev, location

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=5#code/KYDwDg9gTgLgBAYwgOwM7wLIE8DCEC2YcAvHABQCUJAfHAN4BQccUwMArlMuU83ADwATAJYA3OAHpqvCgwC+DIA

### 💻 Code

```tsx
export const MyComp = () => {
  return (
    <div />
  )
}
```

### 🙁 Actual behavior

```js
import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
const _jsxFileName = "file:///input.tsx";
export const MyComp = () => {
    return (_jsxDEV("div", {}, void 0, false, { fileName: _jsxFileName, lineNumber: 2, columnNumber: 11 }, this));
};
```

### 🙂 Expected behavior

```js
import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
const _jsxFileName = "file:///input.tsx";
export const MyComp = () => {
    return (_jsxDEV("div", {}, void 0, false, { fileName: _jsxFileName, lineNumber: 3, columnNumber: 5 }, this));
};
```

### Additional information about the issue

Babel has correct location:
https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM7wLIE8DCEC2YcAvHABQCUJAfHAN4BQccUwMArlMuU83ADwATAJYA3OAHpqvCgwC-DIA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-2&prettier=false&targets=&version=7.27.0&externalPlugins=%40babel%2Fplugin-transform-react-jsx-development%407.25.9&assumptions=%7B%7D

### PR DESCRIPTION
**Pull request by AviVahl**
the code seemed to be using `node.pos` (`node.getFullStart()`) instead of `node.getStart()`, which caused the source location to be off.

now baselines match babel's output (which seems correct).

not sure about using `getTokenPosOfNode()` (used by `getStart()`), but didn't find any better way to do things internally.

fixes #61533

### CODE REVIEW

**Comment by AviVahl** [comment]
I've applied the same fix for fragments as well, as they seemed to use the same pattern for source location handling.

**Comment by AviVahl** [comment]
rebased to latest `main`. accepted new baselines.

EDIT: and again, as `main` changed baselines an additional time.

File: src/compiler/transformers/jsx.ts [hunk 1]
```diff
@@ -283,17 +285,17 @@ export function transformJsx(context: TransformationContext): (x: SourceFile | B
 
     function visitJsxElement(node: JsxElement, isChild: boolean) {
         const tagTransform = shouldUseCreateElement(node.openingElement) ? visitJsxOpeningLikeElementCreateElement : visitJsxOpeningLikeElementJSX;
-        return tagTransform(node.openingElement, node.children, isChild, /*location*/ node);
+        return tagTransform(node.openingElement, node.children, isChild, /*location*/ createRange(getTokenPosOfNode(node, currentSourceFile), node.end));
```
Comment (jakebailey) [inline src/compiler/transformers/jsx.ts]: `getTokenPosOfNode` works, but `skipTrivia` is what I think I would have used for this.

**Comment by jakebailey** [comment]
LGTM but I would switch to `skipTrivia` instead.

File: src/compiler/transformers/jsx.ts (hunk 1 above)
Comment (AviVahl) [reply src/compiler/transformers/jsx.ts]: `getTokenPosOfNode` uses `skipTrivia`. It has additional logic and checks. Are they irrelevant?

Comment (jakebailey) [reply src/compiler/transformers/jsx.ts]: In this case, they are; none of the cases it checks can be hit.

That func is for error reporting in the checker (and misc services uses); you'll note that it's unused within the `transformers` dir, while `skipTrivia` is used.

Comment (AviVahl) [reply src/compiler/transformers/jsx.ts]: done. I hope I got the correct parameters. I'm less sure about these internal functions and their optional parameters. I believe `isInJSDoc` is irrelevant in these cases.

File: src/compiler/transformers/jsx.ts [hunk 2]
```diff
@@ -283,17 +285,20 @@ export function transformJsx(context: TransformationContext): (x: SourceFile | B
 
     function visitJsxElement(node: JsxElement, isChild: boolean) {
         const tagTransform = shouldUseCreateElement(node.openingElement) ? visitJsxOpeningLikeElementCreateElement : visitJsxOpeningLikeElementJSX;
-        return tagTransform(node.openingElement, node.children, isChild, /*location*/ node);
+        const triviaSkippedPosition = skipTrivia(currentSourceFile.text, node.pos, /*stopAfterLineBreak*/ false, /*stopAtComments*/ false);
```
Comment (jakebailey) [inline src/compiler/transformers/jsx.ts]: The stuff you passed in are the defaults; you can just inline it like you had the previous code

Comment (AviVahl) [reply src/compiler/transformers/jsx.ts]: sure. done. :pray:

**Review by jakebailey — APPROVED** [review]

**Comment by AviVahl** [comment]
Thank you. Been waiting for a while for this one to get in.
Btw, are you guys porting these PRs to `typescript-go` at some point?  Are they being tracked?

**Comment by jakebailey** [comment]
Yes, there's a board, and Copilot is good at porting these. We have yet to start targeting 6.0 in the Go code, though, but that will happen ~today
