### PR TITLE
Fix #2214. Support narrowing with typeof in switch condition.

### LINKED ISSUE #2214: Allow switch type guards
I have the following code:

``` ts
function logNumber(v: number) { console.log("number:", v); }
function logString(v: string) { console.log("string:", v); }

function foo1(v: number|string) {
    switch (typeof v) {
        case 'number':
            logNumber(v);
            break;
        case 'string':
            logString(v);
            break;
        default:
            throw new Error("unsupported type");
    }
}
```

Error:

```
Argument of type 'string | number' is not assignable to parameter of type 'number'.
 Type 'string' is not assignable to type 'number'.
```

I was forced to rewrite this using `if` statements.

``` ts
function foo2(v: number|string) {
    if (typeof v === 'number') {
        logNumber(v);
    } else if (typeof v === 'string') {
        logString(v);
    } else {
        throw new Error("unsupported type");
    }
}
```

Please allow using switch statements as type guards.

### PR DESCRIPTION
**Pull request by jack-williams**
#### Enable narrowing support for `typeof` switch conditions. Fixes #2214 

Implement narrow-by-assertion in switch with `typeof`, intending to replicate the equivalent behaviour with `if-then-else`.

@mhegazy Is there any possibility of this making the 3.0 milestone?

#### Basic Example:

```ts
function assertNever(x: never) { return x; }

function switchTypeOf(x: number | string | { x: boolean }): boolean {
    switch (typeof x) {
        case 'number': return x > 0;
        case 'string': return x === "narrowed";
        case 'object': return x.x;
    }
    return assertNever(x);
}
```

#### Exhaustiveness Checking:
Switch exhaustiveness checking is extended to support `typeof`.
```ts
function exhaustiveSwitch(x: number | ((x: string) => number) | symbol): number {
    switch (typeof x) {
        case 'number': return x;
        case 'function': return x('narrowed')
        case 'symbol': return 0;
    }
    // No implicit return
}
```

#### Order sensitive narrowing:
Repeated cases do not get the same narrowing.
```ts
function redundantCases(x: number | string | { x: boolean }): boolean {
    switch (typeof x) {
        case 'number': return x > 0;
        case 'string': return x === "narrowed";
        case 'object': return x.x;
        case 'number':
        case 'object': return assertNever(x);
        case 'string': return assertNever(x);
    }
    return assertNever(x);
}
```

#### 1. Constrained parameters are not narrowed to `never` in `default` / `else`
```ts
function constraintNarrowingSwitch<T extends number | string | boolean>(x: T): boolean {
    switch (typeof x) {
        case 'number': return x > 0;              // x : T & number
        case 'string': return x === "narrowed";   // x : T & string
        case 'boolean': return x;                 // x : (T & true) | (T & false)
    }
    return assertNever(x); // <-- Error
    /* Argument of type 'T' is not assignable to parameter of type 'never'.
       Type 'string | number | boolean' is not assignable to type 'never'.
       Type 'string' is not assignable to type 'never'. [2345]
    */
}

function constraintNarrowingIf<T extends number | string | boolean>(x: T): boolean {
    if (typeof x === 'number') {
        return x > 0;
    }
    if (typeof x === 'string') {
        return x === "narrowed";
    }
    if (typeof x === 'boolean') {
        return x;
    }
    return assertNever(x); // <-- Error
    /* Argument of type 'T' is not assignable to parameter of type 'never'.
       Type 'string | number | boolean' is not assignable to type 'never'.
       Type 'string' is not assignable to type 'never'. [2345]
    */
}
```

#### 2. Unions of constrained generic parameters.
```ts
type L = (x: number) => number;
type R = { x: string }

function genericUnionSwitch<T extends L, U extends R>(x: T | U) {
    switch (typeof x) {
        case 'function': return x; // x: T extends L
        case 'object': return x;   // x: U extends R
    }
}

function genericUnionIf<T extends L, U extends R>(x: T | U) {
    if (typeof x === 'function') {
        return x;  // x: T extends L
    }
    if (typeof x === 'object') {
        return x   // x: U extends R
    }
}
```

### Code Review

The code comments are primarily there for review purposes, they should probably be taken out afterwards. A few things to signpost for the review:
- The function `getSwitchClauseTypeOfWitnesses` performs no caching. The choice for this was because the cache type is `Type[]`, the types of the clause values. In the context of `typeof` the types of the clause values are less important, rather what they represent. There didn't seem to be much use for caching the types. I'd like to get feedback on this, I'm not sure my decision is correct.
- The function `isExhaustiveSwitchStatement` is updated to handle switch statements with `typeof` conditions.
- Can (and should?) `narrowBySwitchOnTypeOf` be moved outside of the scope of reference flow typing?

### CODE REVIEW

**Comment by jack-williams** [comment]
This PR does not update `isExhaustiveSwitchStatement` to handle `typeof` conditions but I don't think it would be too hard to change. If so, I think I'll probably want to try and cache the statement types.

**Comment by jack-williams** [comment]
It it possible to use `Extract` and `Exclude` for narrowing types of the form `T extends A | B | C`?

**Comment by jack-williams** [comment]
ping @mhegazy @RyanCavanaugh 

Sorry for the ping, just wondering if this got lost under a pile of other stuff.

I'm not expecting anyone to drop what they're doing and look at this; I just want to make sure that it's clear I'm still actively wanting to try and merge this.

**Comment by mhegazy** [comment]
@weswigham can you please review this change

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13549,6 +13567,57 @@ namespace ts {
...
+                // switch (typeof x) {
+                //     case 'number':
+                //     case 'string': break;
+                //     default: break;
+                //     case 'number':
+                //     case 'boolean': break
+                // }
+                //
+                // The implied type of the first clause number | string.
+                // The implied type of the second clause is string (but this doesn't get used).
```
Comment (weswigham) [inline src/compiler/checker.ts]: Is this comment correct? It seems a little off. Also could use a test which validates fallthrough behaviors, ie,
```ts
let x: string | number | boolean | object;
switch (typeof x) {
    case 'number':
        assertNumber(x)
    case 'string':
        assertStringOrNumber(x)
        break;
    default:
        assertObject(x);
    case 'number':
    case 'boolean':
        assertBooleanOrObject(x);
        break;
 }
```

Comment (jack-williams) [reply src/compiler/checker.ts]: Yes, the comment is wrong. The line for the second clause should read something like:

_"The implied type of the second clause is never, but this does not get just because it includes a default case"_

**Comment by jack-williams** [comment]
After making some changes the CI failed due to strictNullChecks that weren't enabled when I initially developed the fix.

The source of the problem was using undefined to mark the `default` case in the list of types tested against. E.g.
```ts
switch(typeof x) {
    case "number": ...
    case "string"...
    default: ...
}
```
is represented as the array `["number", "string", undefined]`. I'm not sure it's possible to completely ignore the default case, as you need to know where it is to correctly fix the `clauseStart` and `clauseEnd`. However, I have tried to limit the used of undefined by removing it once all the necessary information is computed.

I'm not convinced it's the most elegant solution, and would be more than happy to readdress the issue based on any feedback.

**Comment by mhegazy** [comment]
@weswigham can you take another look.

**Comment by abraham** [comment]
I'm currently implementing a RemoteData pattern in TS and I think this would greatly help to simplify my [`fold` method](https://github.com/abraham/remotedata/blob/c340b21/src/index.ts#L31:L50).

**Comment by jack-williams** [comment]
I'm looking to add some more tests to this. If anyone has some examples that would be great!

**Comment by jack-williams** [comment]
Pinging @RyanCavanaugh for visibility because I think mhegazy was the only one watching this and I believe they've left the TS team.

**Comment by RyanCavanaugh** [comment]
@weswigham can you review the current iteration? Thanks

**Comment by weswigham** [comment]
@jack-williams @RyanCavanaugh  even though there's no conflicts, a merge with master in the branch prior to us pulling it in would be good - a few months passing may mean someone's added a test this may affect.

**Comment by jack-williams** [comment]
@weswigham @RyanCavanaugh Thanks! Master merged. CI failed on node 6 because of missing jake, I'm not sure if this was caused by my changes. Just let me know if I need fix anything.
