### PR TITLE
Ensure formatter can always get a newline character

### LINKED ISSUE #38548: 3.9 Regression: `organizeImports` prepends/appends "undefined" when there are 2+ named imports
**TypeScript Version:**  3.9.2

**Search Terms:** organizeImports, imports, undefined

**Code**

```ts
import {
  stat,
  statSync,
} from "fs";

export function fakeFn() {
  stat;
  statSync;
}
```

Run through `ts.organizeImports`.

**Expected behavior:**

```ts
import { stat, statSync } from "fs";

export function fakeFn() {
  stat;
  statSync;
}
```

**Actual behavior:**

```ts
import { undefinedstat, statSyncundefined } from "fs";

export function fakeFn() {
  stat;
  statSync;
}
```

Doesn't happen if there's only one import:

```ts
import { stat } from "fs";

export function fakeFn() {
  stat;
}
```

Only happens at the start and end of the block:

```ts
import {
  lstatSync,
  stat,
  statSync,
} from "fs";

export function fakeFn() {
  lstatSync;
  stat;
  statSync;
}
```

will yield:

```ts
import { undefinedlstatSync, stat, statSyncundefined } from "fs";

export function fakeFn() {
  lstatSync;
  stat;
  statSync;
}
```

**Playground Link:**  https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=9&pc=1#code/JYWwDg9gTgLgBAbwFBzgZxgQxgGherGAZQE8A7AYzwF84AzKCEOAIjrRYG4kkBTAD0ix6AV0oxgEMvUwBrXgDEyACgCUifBmzdUW4uQrdqSIA

Don't think it can run the programmatic API.

https://ts-ast-viewer.com/#code/JYWwDg9gTgLgBAbwFBzgZxgQxgGherGAZQE8A7AYzwF84AzKCEOAIjrRYG4kkBTAD0ix6AV0oxgEMvUwBrXgDEyACgCUifBmzdUW4uQrdqSIA

Doesn't have TS 3.9 yet.

I setup a demo repo with both TS 3.8.7 and TS 3.9.2 here:

https://github.com/mathieumg/organize-imports/blob/v3.8.3/index.js yields:

```shell
TypeScript 3.8.3
Text Changes [
  {
    span: { start: 0, length: 55 },
    newText: 'import { lstatSync,stat,statSync } from "fs";\r\n'
  }
]
Failure? NO
```

and https://github.com/mathieumg/organize-imports/blob/v3.9.2/index.js yields:

```shell
TypeScript 3.9.2
Text Changes [
  {
    span: { start: 0, length: 55 },
    newText: 'import {undefinedlstatSync,\r\nstat,\r\nstatSyncundefined} from "fs";\r\n'
  }
]
Failure? YES
```

It's a simplified version of https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/f590b06c382aeeeeb3dadd9191c31aab9284d68c/index.js (which my use case emanates from), so it's not impossible they could be misusing the Language Service API. (but I wouldn't know) I imagine it could also be there was an undocumented breaking change there.

**Possibly Related Issues:**  https://github.com/microsoft/TypeScript/issues/38507

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #38548

It looks like this was always a problem, but didn’t surface itself (at least not where anyone noticed) until we started preserving source newlines in refactors and codefixes. Also, I don’t think this bug was ever observable from VS or VS Code because AFAIK they always populate `formattingSettings.newLineCharacter`. The bug report stemmed from programmatic language service usage.

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -3,6 +3,7 @@ namespace ts.formatting {
     export interface FormatContext {
         readonly options: FormatCodeSettings;
         readonly getRules: RulesMap;
+        readonly host?: FormattingHost;
```
Comment (sheetalkamat) [inline src/services/formatting/formatting.ts:6]: Why is this optional ? Should t it always be there to ensure that any new line related operations are handled correctly

Comment (andrewbranch) [reply src/services/formatting/formatting.ts:6]: I made it optional because I was thinking it was a public API, and a programmatic user really doesn’t need to supply this because they can just set `options.newLineCharacter`. But since it’s internal, I think it’s fine to put it back to required.

**Comment by amcasey** [comment]
FYI @jessetrinity who is also working in this area

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-3.9
