### PR TITLE
Fix 'var' hoisting in 'if' in CJS/AMD emit

### LINKED ISSUE #54017: CommonJS/AMD transforms fail to export top-level `var` inside nested blocks.
# Bug Report

### 🔎 Search Terms

commonjs amd if var

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&module=1&ts=5.0.4#code/CYUwxgNghgTiAEA3W8D6AueUB2BPA3AFCEDeh8FSKU8AvPAIxEC+xAlgGbwAUqAlPDKUqMeACM6jFoRAQAzgiGVkosJKaFWhOQHc2AFzAALHgAYBSimCgL4p9OWEj4wdUWGgOUAK4R9Dp2cEeg0tHSM2CAReC0cKFXguEOlCYAB7QTjnAHM3TUJwyOj+IkIONNFuBJNk+HxY4TE4KABrFPLK-DqG5RQ2PMbmtvyyip4EgCt4Nmw0HoomkFb2sd5p2f5M4QSWvK0O8ZQIeDSuTctxIZXK1BOz+ecAWz3iEAAPAAcK-UEsABpxACwADgACQACOADsgCjAC2ACJgCWgCIADnsx8EA)

### 💻 Code

```ts
declare var _: any;

{
    var a = 1;
}

if (_) {
    var b = 1;
}
else {
    var c = 1;
}

switch (0) {
    case 0:
      var d = 1;
    default:
      var e = 1;
}

while (_) {
    var f = 1;
}

do {
    var g = 1;
}
while (_);

for (var h = 1; ;) {
    break;
}

for (; ;) {
    var i = 1;
    break;
}

for (var j in _) {
    break;
}

for (_ in _) {
    var k = 1;
}

for (var l of _) {
    break;
}

for (_ of _) {
    var m = 1;
}

export { a, b, c, d, e, f, g, h, i, j, k, l, m };
```

### 🙁 Actual behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.m = exports.l = exports.k = exports.j = exports.i = exports.h = exports.g = exports.f = exports.e = exports.d = exports.c = exports.b = exports.a = void 0;
{
    var a = 1;
}
if (_) {
    var b = 1;
}
else {
    var c = 1;
}
switch (0) {
    case 0:
        var d = 1;
    default:
        var e = 1;
}
while (_) {
    var f = 1;
}
do {
    var g = 1;
} while (_);
for (var h = 1;;) {
    break;
}
for (;;) {
    var i = 1;
    break;
}
for (var j in _) {
    break;
}
for (_ in _) {
    var k = 1;
}
for (var l of _) {
    break;
}
for (_ of _) {
    var m = 1;
}
```

- `a`..`m` are not exported.

### 🙂 Expected behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.m = exports.l = exports.k = exports.j = exports.i = exports.h = exports.g = exports.f = exports.e = exports.d = exports.c = exports.b = exports.a = void 0;
{
    var a = exports.a = 1;
}
if (_) {
    var b = exports.b = 1;
}
else {
    var c = exports.c = 1;
}
switch (0) {
    case 0:
        var d = exports.d = 1;
    default:
        var e = exports.e = 1;
}
while (_) {
    var f = exports.f = 1;
}
do {
    var g = exports.g = 1;
} while (_);
for (var h = exports.h = 1;;) {
    break;
}
for (;;) {
    var i = exports.i = 1;
    break;
}
for (var j in _) {
    exports.j = j;
    break;
}
for (_ in _) {
    var k = exports.k = 1;
}
for (var l of _) {
    exports.l = l;
    break;
}
for (_ of _) {
    var m = exports.m = 1;
}
```

- `a`..`m` are exported.

It looks like we are not traversing into top-level statements to discover `var` statements that are exported via `export {}`.

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes a failure to descend into top-level, block-containing statements to properly hoist `var` declarations.

Fixes #54017

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

File: src/compiler/transformers/module/module.ts [hunk 1]
```diff
@@ -668,6 +688,72 @@ export function transformModule(context: TransformationContext): (x: SourceFile
...
+    }
+
+    /**
+     * Visit nested elements at the top-level of a module.
+     *
+     * @param node The node to visit.
+     */
+    function topLevelNestedVisitor(node: Node): VisitResult<Node | undefined> {
+        switch (node.kind) {
+            case SyntaxKind.VariableStatement:
```
Comment (nnnnoel) [inline src/compiler/transformers/module/module.ts:703]: L:682 case can be removed because of this case
