### PR TITLE
🐛 Fix not emitting comments between sibling fields of object literals 

### LINKED ISSUE #49784: Bug report: Comment node is removed after "Extract to function in module scope
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Ubuntu 22.04

NOTE: I couldn't find this option in VSCode Insiders! (Maybe it is removed)

Hi. When I refactor a callback in my JSX, which does something rather complicated, one of my comments are removed.

Code example:
```tsx
//@ts-nocheck
/* eslint-disable */

export default function Something() {
  return (
    <SomeComponent
      aCallbackThatProducesAReactNode={() => {
        // this comment will be kept intact
        const someProps = {
          prop1: props.props1, // BUT THIS COMMENT WILL BE REMOVED :(

          prop2: props.props2 // this comment will be kept intact too
        };

        return <SomeOtherComponent {...someProps} />;
      }}
    />
  );
}
```

Try refactoring the whole callback into a function in module scope.

One:
image

Two:
image

Three:
image

As you see one of my comments are removed.

Thanks.

### PR DESCRIPTION
**Pull request by babakks**
Fixes #49784

### CODE REVIEW

**Comment by babakks** [comment]
This approach breaks many other test cases. So, I close it until I've found a viable solution.

**Comment by babakks** [comment]
@RyanCavanaugh The fix seems working now. However, the changes to the emitter affected 15 other test cases, fortunately, in a good way. That is, some trailing comments which were dropped in the reference baselines can now be retained as they were. Anyway, I totally get it that accepting any kind of change to old test cases requires careful consideration on your side. 

For example, in `assignmentCompatBug3.js`, the comments below are now kept (as stated by the original test case file, `assignmentCompatBug3.ts`):

```diff
// assignmentCompatBug3.js
- get x() { return x; },
- get y() { return y; },
+ get x() { return x; }, // shouldn't be "void"
+ get y() { return y; }, // shouldn't be "void"
```

```ts
// assignmentCompatBug3.ts
get x() { return x;}, // shouldn't be "void"
get y() { return y;}, // shouldn't be "void"
```

## Affected reference baselines

(15 cases)

- `arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js`
- `assignmentCompatBug3.js`
- `bindingPatternCannotBeOnlyInferenceSource.js`
- `callSignaturesWithParameterInitializers2.js`
- `circularResolvedSignature.js`
- `duplicateObjectLiteralProperty.js`
- `excessPropertyCheckWithMultipleDiscriminants.js`
- `excessPropertyCheckWithNestedArrayIntersection.js`
- `indexSignatures1.js`
- `objectLitArrayDeclNoNew.js`
- `objectLiteralShorthandPropertiesErrorFromNoneExistingIdentifier.js`
- `privateNameBadDeclaration.js`
- `thisTypeInFunctions.js`
- `thisTypeInFunctionsNegative.js`
- `variableDeclaratorResolvedDuringContextualTyping.js`

## New test case

I've added a test case, `commentsOnObjectLiteral5.ts` (at `tests/cases/compiler`) to confirm that all comments are emitted as they are:

```ts
const a = {
    p0: 0, // Comment 0
    p1: 0, /* Comment 1
    A multiline comment. */
    p2: 0, // Comment 2
};
```

**Comment by aghArdeshir** [comment]
Nice one :+1: Thanks

File: tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ const test = () => ({
 //// [arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js]
 var test = function () { return ({
     // "Identifier expected." error on "!" and two "Duplicate identifier '(Missing)'." errors on space.
-    prop: !value,
+    prop: !value, // remove ! to see that errors will be gone
```
Comment (jakebailey) [inline tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js:21]: Rather than modifying unrelated tests, can you just add new tests to show that your PR fixes the bug?

It's okay to accept a new baseline for an old test if its output changes (that is very normal), but it's not normal to add comments to old, unrelated test cases to show that an emit bug is fixed.

**Review by jakebailey — CHANGES_REQUESTED** [review]

File: tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js (hunk 1 above)
Comment (babakks) [reply tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js:21]: @jakebailey You're right, and I didn't modify other test cases to confirm this fix. The comments were already there in the original `.ts` files (but were omitted from the reference baselines.)

As I mentioned, I also added a single test case, `commentsOnObjectLiteral5.ts`, to just confirm this fix.

Comment (jakebailey) [reply tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js:21]: Oh shoot, you're totally right. I didn't notice these weren't the original TS files!

Comment (babakks) [reply tests/baselines/reference/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.js:21]: For example, this is the original (intact) test case file for the line you commented on (i.e.,  `tests/cases/compiler/arrowFunctionParsingDoesNotConfuseParenthesizedObjectForArrowHead.ts`):

```ts
// regression test for https://github.com/microsoft/TypeScript/issues/32914
declare var value: boolean;
declare var a: any;

const test = () => ({
    // "Identifier expected." error on "!" and two "Duplicate identifier '(Missing)'." errors on space.
    prop: !value, // remove ! to see that errors will be gone
    run: () => { //replace arrow function with regular function to see that errors will be gone
        // comment next line or remove "()" to see that errors will be gone
        if(!a.b()) { return 'special'; }

        return 'default';
    }
}); 
```

**Review by jakebailey — APPROVED** [review]
Seems good to me (this is a bug I hit on the module transformer, "fixed" by switching to ts-morph entirely), but someone else should take a peek too.
