### PR TITLE
Preserve input key style when writing mapped type keys in declaration emit

### LINKED ISSUE #50358: Numeric string key is being converted to a number in declaration file
# Bug Report

When TS converts a specific type into a static type in a `d.ts` file, it's converting numeric string keys into a number, e.g. `'1'` becomes `1`.  It seems similar to [the issue described here](https://github.com/microsoft/TypeScript/issues/37292), but my value is being re-mapped  with generics and mapped types, so it seems like it's a more complicated version of this. The `.d.ts` tab in the playground link shows what is happening.

### 🔎 Search Terms

numeric string key converted to number 

### 🕗 Version & Regression Information

TS 4.7.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZTFYAOwGsAbNAZwBo4ATNAMyLQAUoIw1ZhK4BfOA3Yg4AcgACANwyFgpUhgC0aAB4woGZDAD0FfETKVRAbgCwAKAvIIhCvHR6bFYJNbtO3XgF46jZmw4uGB4KAAoECzgUG1pgYKcALkRIqLgQCAAjOTQkhD4qFKiYDAzyGFz8wt8KYhgOCoLzKMqm3wYMAFdSGABhGLjgGyTRdKzyUUao-EDPClyq7QAqRaq4RbgAWQwoAHMiOBs4GAALNCOOOGd6ADpVldbU9fF6dq74ACIABne77SqQbZ7QgAFXqyQeqVEn1ESU+k1SUVEAEYYXAAGzwhGiABMqKR2MxkIAzHiAByEloIpb3BFrOAACQgAHcjqc4BkICpLscIF1aOyzrE9AoAJ5oWi3CFrP4QoVgUVJADaolKEGQxAmYiIpGYogAuvCWnwAJRmSzmVSQWDRWzwDkqPAEEjkChwHyoTDYR0GF2hByQWwuNwzYKUU0WbTaWnRgB6AH4LJboPAYCLOHAAEKc73O7xwFjbDAgNDYKAUAA8qc4EAY7Oz+lzFAAfIrPnqzUA)

### 💻 Code

It's an issue with compilation, the playground link above shows it. 

### 🙁 Actual behavior

Conversion of a specific type with mapped keys to a static type is resulting in string numeric keys being converted to numbers. e.g. `'0'`, `'1'`, getting converted to `1`,`2`.

### 🙂 Expected behavior

Keys to remain as strings and not be converted to a number.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #50358

### CODE REVIEW

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6653,23 +6653,23 @@ namespace ts {
...
 
             // See getNameForSymbolFromNameType for a stringy equivalent
-            function getPropertyNameNodeForSymbolFromNameType(symbol: Symbol, context: NodeBuilderContext, singleQuote?: boolean) {
+            function getPropertyNameNodeForSymbolFromNameType(symbol: Symbol, context: NodeBuilderContext, singleQuote?: boolean, stringNamed?: boolean) {
                 const nameType = getSymbolLinks(symbol).nameType;
                 if (nameType) {
                     if (nameType.flags & TypeFlags.StringOrNumberLiteral) {
                         const name = "" + (nameType as StringLiteralType | NumberLiteralType).value;
-                        if (!isIdentifierText(name, getEmitScriptTarget(compilerOptions)) && !isNumericLiteralName(name)) {
+                        if (!isIdentifierText(name, getEmitScriptTarget(compilerOptions)) && (stringNamed || !isNumericLiteralName(name))) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:6672]: Would it make sense to just rewrite this as

```suggestion
                        if (stringNamed || !isIdentifierText(name, getEmitScriptTarget(compilerOptions))) {
```

Comment (weswigham) [reply src/compiler/checker.ts:6672]: Nah, we need the numeric name callout, otherwise we don't prefer writing `[-1]:` over `"-1":`, or `0:` over `"0":` (which is important, since our types for `keyof` key off weather those are strings or not, so we really wanna prefer the non-string form unless it's overridden).

**Review by andrewbranch — APPROVED** [review]
