### PR TITLE
Signature help turns off current-parameter display for non-trailing rest parameters

### LINKED ISSUE #42292: Incorrect signature help position for non-trailing rest arguments
```ts
declare function doStuff(...args: [...names: string[], shouldCapitalize: boolean]): void;
doStuff("fee", "fai"/**/, "foh",  true);
```

Trigger signature help at `/**/`

**Current**: Signature help indicates that we're in the second argument - **shouldCapitalize**.
**Expected**: Signature help indicates that we're still in the first (rest) argument: **names**

### PR DESCRIPTION
**Pull request by sandersn**
With tuple types as rest parameters, you can now create non-trailing rest parameters. However, the simplistic current-parameter index matching just increments right past them. This PR turns off the current-parameter highlight for non-trailing rest parameters.

```ts
declare function loading(...args: [...names: string[], allCaps: boolean, extra: boolean]): void;

leading(/**/
leading('one', /**/
leading('one', 'two', /**/
```

For these calls, there is no current parameter, because signature help doesn't have any code to map multiple arguments to a single rest parameter. But at least it's never wrong!

Fixes #42292

## Scope Creep Time! ##

I improved current-parameter highlighting for trailing rest parameters as well: the highlight now stops at the end.

### CODE REVIEW

**Comment by andrewbranch** [comment]
Wait, we don't look at types here? So in a valid usage like

```ts
loading("name1", "name2", /*allCaps*/ true, /**/
```

you’d always be stuck on `names`?

**Comment by sandersn** [comment]
Yeah, previously, we'd just do overload resolution and then highlight whichever **parameter** matched the count of **arguments**. This is more clever, but only a little. I don't think it's worthwhile to be too clever here.

**Comment by sandersn** [comment]
The checker code that iterates arguments and gets a matching parameter is buried pretty deep. It *might* be possible to expose that to the services layer, but I'm not sure how much scaffolding I'd have to make to make it work.

**Comment by andrewbranch** [comment]
What if we just don’t set a current argument since we know we won’t get it right?

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
Another alternative might be to not flatten the signature if the tuple has a non-trailing rest element.

**Comment by sandersn** [comment]
@andrewbranch `argumentIndex` is required. =(
@DanielRosenwasser That's not a bad idea. Not sure how hard it is to do that. I'll go look.

**Comment by sandersn** [comment]
Well, uh, we don't even try to highlight the current parameter correctly for the last argument of this simple example:

```ts
declare function mcduff(x, y, ...args)
mcduff(1, 2, 3, 4)
```

So I think it's fine to fall back to that behaviour for now. I've got fairly simple code that deactivates the tuple expansion in case of non-trailing rests, which I'll push shortly.

**Comment by DanielRosenwasser** [comment]
> Well, uh, we don't even try to highlight the current parameter correctly for the last argument of this simple example:

!!!

File: src/services/signatureHelp.ts [hunk 1]
```diff
@@ -628,10 +620,12 @@ namespace ts.SignatureHelp {
                 printer.writeList(ListFormat.TypeParameters, args, sourceFile, writer);
             }
         });
-        const lists = checker.getExpandedParameters(candidateSignature);
-        return lists.map(parameterList => {
+        const expansions = checker.getExpandedParameters(candidateSignature);
+        const hasNonTrailingRest = expansions.some(e => e.some((p,i) => (p as TransientSymbol).checkFlags & CheckFlags.RestParameter && i !== e.length - 1));
```
Comment (DanielRosenwasser) [inline src/services/signatureHelp.ts:624]:
```suggestion
        const hasNonTrailingRest = expansions.some(e => e.some((p, i) => (p as TransientSymbol).checkFlags & CheckFlags.RestParameter && i !== e.length - 1));
```

**Review by DanielRosenwasser — COMMENTED** [review]
Can we get an example with a middle spread too?

**Comment by DanielRosenwasser** [comment]
I still feel a bit conflicted because this displays more poorly. Maybe `argumentIndex` can just be set to `-1` or something? Ideally `argumentIndex` could be split into `argumentRange` or something like that.

**Comment by andrewbranch** [comment]
I was wondering about setting `argumentIndex` to -1, but it seems like whether that works will be editor-dependent. If it works in VS and VS Code, do we call that good enough?

**Comment by DanielRosenwasser** [comment]
Well, editors today have to sort of handle the case where there's too many parentheses, right? I don't exactly know what the expected behavior is. Maybe @CyrusNajmabadi has some thoughts from the Roslyn side.

**Comment by sandersn** [comment]
It already works fine to have argumentIndex > parameters.length if you want to turn off current-parameter highlighting. I think that's a pretty good option.

**Comment by sandersn** [comment]
The latest commit:

1. Skips highlighting non-trailing rests by setting `argumentIndex = parameters.length`, which is one past the end.
2. Stops the highlight at the end for trailing rests. (This is new! I can't believe we never tested this before!)

File: src/services/signatureHelp.ts [hunk 2]
```diff
@@ -541,8 +540,19 @@ namespace ts.SignatureHelp {
...
         Debug.assert(selectedItemIndex !== -1); // If candidates is non-empty it should always include bestSignature. We check for an empty candidates before calling this function.
-
-        return { items: flatMapToMutable(items, identity), applicableSpan, selectedItemIndex, argumentIndex, argumentCount };
+        const help = { items: flatMapToMutable(items, identity), applicableSpan, selectedItemIndex, argumentIndex, argumentCount };
+        const selected = help.items[selectedItemIndex];
+        if (selected.isVariadic) {
+            const firstRest = findIndex(selected.parameters, p => !!p.isRest);
+            if (-1 < firstRest && firstRest < selected.parameters.length - 1) {
+                // We don't have any code to get this correct; instead, don't highlight a current parameter AT ALL
+                help.argumentIndex = selected.parameters.length;
```
Comment (andrewbranch) [inline src/services/signatureHelp.ts:549]: We could also make this conditional upon `argumentIndex >= firstRest` if we wanted parameter highlighting to work up until the first rest, where the ambiguity begins. But maybe that would be a worse experience than consistently seeing no highlighting. I personally feel like parameter highlighting is pretty useful when parameters have JSDoc description, and it might be worthwhile to show them as often as we can. But it might be pretty confusing for it to stop working halfway through typing call arguments. Don’t have a super strong opinion here.

**Review by andrewbranch — APPROVED** [review]
