### PR TITLE
Fix values and types merging in JS module exports

### LINKED ISSUE #37833: Auto-import failure: Cannot read property 'length' of undefined
tsconfig.json
```json
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
    }
}
```
test.js
```js
class Abcde {
    x
}

module.exports = {
    Abcde
};
```
index.ts
```ts
export var foo = 1
declare module "./test" {
    interface Abcde { b: string }
}

Abcde// Invoke completion here to trigger auto-import
```

Expected: `Abcde` is imported from `test`.
Actual:
```
Exception has occurred: TypeError
TypeError: Cannot read property 'length' of undefined
    at getLocalTypeParametersOfClassOrInterfaceOrTypeAlias (e:\ts_gh\src\compiler\checker.ts:8292:32)
    at typeParametersToTypeParameterDeclarations (e:\ts_gh\src\compiler\checker.ts:5002:62)
    at e:\ts_gh\src\compiler\checker.ts:4098:82
    at withContext (e:\ts_gh\src\compiler\checker.ts:4130:39)
    at Object.symbolToTypeParameterDeclarations (e:\ts_gh\src\compiler\checker.ts:4098:21)
    at e:\ts_gh\src\services\symbolDisplay.ts:634:44
    at Object.mapToDisplayParts (e:\ts_gh\src\services\utilities.ts:2091:13)
    at writeTypeParametersOfSymbol (e:\ts_gh\src\services\symbolDisplay.ts:633:40)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (e:\ts_gh\src\services\symbolDisplay.ts:289:13)
    at E:\ts_gh\built\local\tsserver.js:111800:41
    at Object.runWithCancellationToken (e:\ts_gh\src\compiler\checker.ts:662:28)
    at createCompletionDetailsForSymbol (e:\ts_gh\src\services\completions.ts:678:15)
    at Object.getCompletionEntryDetails (e:\ts_gh\src\services\completions.ts:659:24)
    at Proxy.getCompletionEntryDetails (e:\ts_gh\src\services\services.ts:1476:32)
    at e:\ts_gh\src\server\session.ts:1683:53
    at Object.mapDefined (e:\ts_gh\src\compiler\core.ts:475:32)
    at IOSession.Session.getCompletionEntryDetails (e:\ts_gh\src\server\session.ts:1681:28)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (e:\ts_gh\src\server\session.ts:2455:51)
    at e:\ts_gh\src\server\session.ts:2665:69
    at IOSession.Session.executeWithRequestId (e:\ts_gh\src\server\session.ts:2655:25)
    at IOSession.Session.executeCommand (e:\ts_gh\src\server\session.ts:2665:29)
    at IOSession.Session.onMessage (e:\ts_gh\src\server\session.ts:2694:23)
    at Interface.<anonymous> (e:\ts_gh\src\tsserver\server.ts:577:22)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

TS version: c47aca0da321663415b7fc2ed000f66c4d7bcb5d

### PR DESCRIPTION
**Pull request by andrewbranch**
I don’t think this is exactly right, but it’s probably closer than what was there before. Opening to create a context to chat about this with @sandersn.

Fixes #37833

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7646,11 +7646,16 @@ namespace ts {
...
-                    if (members.has(name)) {
-                        const exportedMember = exportedType.members.get(name)!;
-                        const union = createSymbol(s.flags | exportedMember.flags, name);
-                        union.type = getUnionType([getTypeOfSymbol(s), getTypeOfSymbol(exportedMember)]);
-                        members.set(name, union);
+                    const exportedMember = members.get(name)!;
+                    if (exportedMember && exportedMember !== s) {
+                        if (s.flags & SymbolFlags.Value) {
+                            const union = createSymbol(s.flags | exportedMember.flags, name);
+                            union.type = getUnionType([getTypeOfSymbol(s), getTypeOfSymbol(exportedMember)]);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:7653]: The problem is that `s` can itself be a type symbol, whether by module augmentation or JS `@typedef`, so `getTypeOfSymbol(s)` would return `errorType` much of the time. In other cases, `exportedMember === s` and so this only served to needlessly create a transient symbol missing `declarations`. (That’s why you see a bunch of symbol baselines gain a value declaration.)

But, this is probably not quite right for value symbols that should be allowed to merge, like a function from JS merged with a namespace from a module augmentation... The only test that demonstrates the intended effect of the union type is [this one](https://github.com/microsoft/TypeScript/blob/795a5c83fe55e002a98ef274e9b8c6b103ef4f74/tests/cases/conformance/salsa/moduleExportWithExportPropertyAssignment3.ts#L22-L23), where both declarations are in the JS file itself. I’m not sure if we’d expect the union type if one of those declarations were in a module augmentation. Would we expect a duplicate identifier error instead?

File: tests/cases/compiler/jsExportMemberMergedWithModuleAugmentation.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+declare module "./test" {
+  interface Abcde { b: string }
+}
+
+new Abcde().x;
+
+// Descriptive, not prescriptive: This is ok,
+// because the type meaning from /test.js does
+// not propagate through the object literal export.
```
Comment (sandersn) [inline tests/cases/compiler/jsExportMemberMergedWithModuleAugmentation.ts:26]: This seems like a bug in our implementation that should be fixed someday, at which point the assignment won't be allowed. I think "currently buggy" is a better description than "Descriptive, not prescriptive" in that case. But, I may have misunderstood your intent.

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts:7653]: > Would we expect a duplicate identifier error instead?

Probably yes, since it's a value. But to some extent we get to decide the semantics here; advanced things like module augmentations don't even necessarily need to work at all, or even have defined behaviour. (It's better if they do of course.)

**Comment by andrewbranch** [comment]
@typescript-bot user test this

File: src/compiler/checker.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:7653]: I added this test for it:

```ts
// @Filename: /test.js
module.exports = {
  a: "ok"
};

// @Filename: /index.ts
import { a } from "./test";
declare module "./test" {
  export const a: number;
}
```

And routed these `a` symbols through the `else` branch so they would go to `mergeSymbol`, thinking it would issue a duplicate identifier error. But, the JS symbol is a `Property`, which has no problem merging with the ambient `BlockScopedVariable`. As a result, the ambient `a` seems to silently overwrite the JS property `a`, at least in terms of the type baseline.

Not sure what the best approach is here. I could issue the error manually, but this is feeling very ad-hoc.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -7646,11 +7647,38 @@ namespace ts {
...
+                                    createDiagnosticForNode(s.valueDeclaration, Diagnostics._0_was_also_declared_here, unescapedName));
+                            }
+                            const union = createSymbol(s.flags | exportedMember.flags, name);
+                            union.type = getUnionType([getTypeOfSymbol(s), getTypeOfSymbol(exportedMember)]);
+                            union.valueDeclaration = exportedMember.valueDeclaration;
+                            union.declarations = concatenate(exportedMember.declarations, s.declarations);
+                            members.set(name, union);
+                        }
+                        else {
+                            members.set(name, mergeSymbol(s, exportedMember));
```
Comment (sandersn) [inline src/compiler/checker.ts:7680]: does this `else` still make sense here, with the ad-hoc error now in place?

Comment (andrewbranch) [reply src/compiler/checker.ts:7680]: Yep, this handles the original issue, where the module augmentation adds a type meaning. I guess we could error on that too, but it seems less obviously wrong to me.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -1115,8 +1115,9 @@ namespace ts {
                 target.flags |= source.flags;
                 if (source.valueDeclaration &&
                     (!target.valueDeclaration ||
-                     isAssignmentDeclaration(target.valueDeclaration) && !isAssignmentDeclaration(source.valueDeclaration) ||
-                     isEffectiveModuleDeclaration(target.valueDeclaration) && !isEffectiveModuleDeclaration(source.valueDeclaration))) {
+                    !(source.valueDeclaration.flags & NodeFlags.Ambient && !(target.valueDeclaration?.flags & NodeFlags.Ambient)) &&
+                     (isAssignmentDeclaration(target.valueDeclaration) && !isAssignmentDeclaration(source.valueDeclaration) ||
+                     isEffectiveModuleDeclaration(target.valueDeclaration) && !isEffectiveModuleDeclaration(source.valueDeclaration)))) {
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/compiler/checker.ts:1120]: Hmm, how would you end up with an ambient declaration in a JavaScript file? Off the top of my head I didn’t think that was possible.

[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/checker.ts:1120]: Well, we'll parse and understand this in JS:

```js
declare function f(): void
f()
```

Just with lots of errors saying "please don't use this".

More practically, I think it would be better if this code and the check inside declareSymbol in the binder were the same -- if they haven't already diverged too far.

**Comment by sandersn** [comment]
Since I'm out tomorrow and the beta is done tomorrow, go ahead and merge this if there's no easy reconciliation between the module priority code in mergeSymbol and declareSymbol. We probably should dedupe the code, but if it's anything but trivial, it's a risky change.

File: src/compiler/checker.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/compiler/checker.ts:1120]: The logic in those two places was identical, so it was safe and easy to move to a utility. That said, I couldn’t actually trigger the same crash by writing ambient code in a JS file, I think because an ambient module declaration is only a module _augmentation_ if the file is an ES module, and if it’s an ES module, `module.exports` is ignored.
