### PR TITLE
fix(48109) - 'Convert to arrow function' refactoring adds extra indent

### LINKED ISSUE #48109: 'Convert to arrow function' refactoring adds extra indent
# Bug Report

### 🔎 Search Terms

- refactor
- refactoring
- vscode

### 🕗 Version & Regression Information

TS 4.7.20220302

### Repro

1. With the code:
```js
console.log(function () {
    console.log(1);
    console.log(2);
    return 3;
})
```

Run the `convert to arrow function` refactoring

### Bug

The ends up indenting the function body:

```js
console.log(() => {
        console.log(1);
        console.log(2);
        return 3;
    })
```

### PR DESCRIPTION
**Pull request by MQuy**
Fixes #48109

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -56,8 +56,8 @@ namespace ts.formatting {
             // for block indentation, we should look for a line which contains something that's not
             // whitespace.
             const currentToken = getTokenAtPosition(sourceFile, position);
-            // for object literal, we want to the indentation work like block
-            // if { starts in any position (can be in the middle of line)
+            // for object literal, we want the indentation work like block ident style
+            // if { starts in any position (can be in the middle of a line)
             // the following indentation should treat { as starting of that line (including leading whitespace)
```
Comment (DanielRosenwasser) [inline src/services/formatting/smartIndenter.ts:61]:
```suggestion
            // For object literals, we want indentation to work just like with blocks.
            // If the `{` starts in any position (even in the middle of a line), then
            // the following indentation should treat `{` as the start of that line (including leading whitespace).
```

**Review by DanielRosenwasser — APPROVED** [review]
