### PR TITLE
fix(37539): Parameter not renamed in JSDoc if it's inside non-prototype-based JS class

### LINKED ISSUE #37539: Parameter not renamed in JSDoc if it's inside non-prototype-based JS class
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.3

**Search Terms**
- jsdoc
- rename
- javascript

---

- VSCode Version: 143.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a JS file with the function
```
function MyClass() {

  /**
   * @param {number} p1
   */
 this.test = function (p1) {
      return p1;
  };
}
```

2. Place cursor on "p1" in the JSDoc
3. Press F2, rename the parameter

Actual result: Parameter will be renamed in method signature and body, but not in JSDoc.

*Edit* Actually this works in plain functions, but not in "class methods" glued to "this" inside class constructor functions. We used this pattern a lot in our old code base. VSCode recognizes the parameter name when cursor is placed inside the JSDoc, but does not include it in the rename action.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37539

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -1204,8 +1204,13 @@ namespace ts.FindAllReferences {
...
 
-                // The search scope is the container node
-                scope = container;
+                if (isFunctionExpression(container)) {
+                    scope = findAncestor(container.parent, n =>
+                        isBinaryExpression(n) || isVariableDeclaration(n) || isVariableDeclarationList(n) ? false : isStatement(n) || "quit") || container;
+                }
+                else {
+                    scope = container;
+                }
```
Comment (sandersn) [inline src/services/findAllReferences.ts:1213]: It would be better to use the existing function for finding jsdoc locations:

```suggestion
                scope = container;
                if (isFunctionExpression(container)) {
                    let next;
                    while (next = getNextJSDocCommentLocation(scope)) {
                        scope = next;
                    }
                }
```

although you'll have to go in and export it from `src/compiler/utilities.ts`

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/services/findAllReferences.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/findAllReferences.ts]: @sandersn I didn't about this util function :). Thanks.

**Review by sandersn — APPROVED** [review]
