### PR TITLE
Fix control flow analysis for property initializers

### LINKED ISSUE #8967: Incorrect "Variable is used before being assigned" when initializing class member (strictNullChecks)
**TypeScript Version:** 

1.9.0-dev.20160604-1.0

**Code**

```ts
const LANG = "Turbo Pascal"

class BestLanguage {
    name = LANG;
}
```

**Expected behavior:**

Compiled without errors.

**Actual behavior:** 

```
$ tsc --strictNullChecks test.ts 
test.ts(4,12): error TS2454: Variable 'LANG' is used before being assigned.
```

Latest version that doesn't have this bug is **Version 1.9.0-dev.20160602-1.0**.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #8967.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8091,13 +8091,22 @@ namespace ts {
             return expression;
         }
 
+        function getControlFlowContainer(node: Node): Node {
+            while (true) {
+                node = node.parent;
+                if (isFunctionLike(node) || node.kind === SyntaxKind.ModuleBlock || node.kind === SyntaxKind.SourceFile || node.kind === SyntaxKind.PropertyDeclaration) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Does this cover computed properties?

```ts
const LANG = "German";
class WurstLanguage {
    [LANG]() {
    }
}
```

Maybe the class itself should be a control flow container.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Actually, it should work since the parent will be a method declaration with a computed property name. It still might be worth adding as a test.

**Comment by RyanCavanaugh** [comment]
:+1:
