### PR TITLE
in noImplicitReturns mode, also disallow "return;"

### LINKED ISSUE #5916: empty return statement should be a compiler error when return type is specified
Currently this function compiles just fine

```.ts
function foo(x): string {
	return;
}
```

I understand that it's happening because `undefined` is a valid result for a variable of type `string`, and this sort of related back to #185, but a midway point could be to simply require the return statement to not be empty.

Similarly, this code fails to compile:

```.ts
function foo(x): string {
}
```

But this one compiles:

```.ts
function foo(x): string {
	if(false) {
		return;
	}
}
```

I think the expected behavior is that every branch should require an explicit return statement.

A side benefit of this is that you can get exhausting matching completeness basically for free:

```.ts
function foo(x: number | string | boolean): string {
	if(typeof x === 'number') {
		return x.toString();
	} else if (typeof x === 'string') {
		return x;
	}
}
```

Currently the above compiles, but if TypeScript required an explicit return in every branch for non void return functions, there would be a compiler error because there are remaining types in the union. However this would compile:

```.ts
function foo(x: number | string | boolean): string {
	if(typeof x === 'number') {
		return x.toString();
	} else if (typeof x === 'string') {
		return x;
	} else if (typeof x === 'boolean') {
		return ''+x;
	}
}
```

This is pretty nice! There is one edge case still -- because of the implicit `void` included in `x`, calling `foo(null)` or `foo(undefined)` will return `undefined`. I don't know what to do about this because it relates pretty heavily to #185. I think for now it can be ignored, and whatever resolution that (hopefully) happens there will take care of it.

### PR DESCRIPTION
**Pull request by martine**
In --noImplicitReturns mode, if a function specifies a return type,
disallow empty "return;" statements.

Fixes #5916.

---

This is my first TypeScript change, so please review with caution.

Some things wasn't sure about, checked off the resolved ones:
- [x] Should I add more tests for other cases?  E.g. a function that is tagged with `void` return etc.
- [ ] Should I use a different error message?
- [x] Maybe my check against Any here is wrong?  I copied it from elsewhere.

### CODE REVIEW

**Comment by martine** [comment]
The Travis build appears to have failed due to a lint error (?).

I don't see any mention of lint in `CONTRIBUTING.md`, suggestions welcome!

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13880,6 +13880,11 @@ namespace ts {
                             checkTypeAssignableTo(exprType, returnType, node.expression);
                         }
                     }
+                } else {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Else on the next line (we link to a style guide in CONTRIBUTING.md)

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -13880,6 +13880,11 @@ namespace ts {
                             checkTypeAssignableTo(exprType, returnType, node.expression);
                         }
                     }
+                } else {
+                  if (compilerOptions.noImplicitReturns && !maybeTypeOfKind(returnType, TypeFlags.Any | TypeFlags.Void)) {
+                    // The function has a return type, but the return statement doesn't have an expression.
+                    error(node, Diagnostics.Not_all_code_paths_return_a_value);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: 4 spaces per indentation

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -13880,6 +13880,11 @@ namespace ts {
                             checkTypeAssignableTo(exprType, returnType, node.expression);
                         }
                     }
+                } else {
+                  if (compilerOptions.noImplicitReturns && !maybeTypeOfKind(returnType, TypeFlags.Any | TypeFlags.Void)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: This can be an `else if`

**Comment by DanielRosenwasser** [comment]
Can you rename the test file? It's not that there's an empty statement, it's that the return statement lacks a return expression.

Other than that and a few style nits, this looks good. @vladima, can you also take a look?

**Comment by DanielRosenwasser** [comment]
Also, `jake lint` will run our linter.

**Comment by martine** [comment]
So embarrassing that I got tabs wrong, it's such a pet peeve of mine when others get it wrong!

I think I have fixed the issues you brought up.  I'm still not quite sure I'm checking for the right thing (e.g. isTypeOfKind vs maybeTypeOfKind) but I added some more test cases to verify it makes some sense.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -13881,6 +13881,10 @@ namespace ts {
                         }
                     }
                 }
+                else if (compilerOptions.noImplicitReturns && !isTypeOfKind(returnType, TypeFlags.Void)) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: void | any

Comment (martine) [inline src/compiler/checker.ts]: With your suggestion, this code is now accepted.  Is that expected?  (I don't have a good intuition about how "any" ought to behave, so I just wanted to double check.)
```    
    function isMissingReturnExpression2(): any {
      return;
    }
```

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -13881,6 +13881,10 @@ namespace ts {
                         }
                     }
                 }
+                else if (compilerOptions.noImplicitReturns && !isTypeOfKind(returnType, TypeFlags.Void | TypeFlags.Any)) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: please use maybeTypeOfKind to support something like `T | void`.

Comment (mhegazy) [inline src/compiler/checker.ts]: also looks like we do not handel this correctelly in 10804:
```ts
if (inferredReturnType === voidType || isTypeAny(inferredReturnType)) {
```

should also use `maybeTypeOfKind` as well.

Comment (mhegazy) [inline src/compiler/checker.ts]: a test would be appreciated as well.

Comment (martine) [inline src/compiler/checker.ts]: Aw, I had a test for that as well.  OK, one more rebaseline...

**Comment by mhegazy** [comment]
also can you add a test for an implicit return type that is inferred from the function body:

```ts
function f(x) {
   if (x) {
       return 0;
   }
   else {
       return;
   }
}
```

**Comment by martine** [comment]
Done.  I also fixed the tabs in my test code (adding the "if" statement made me realize I had it wrong).

**Comment by vladima** [comment]
:+1:

**Comment by mhegazy** [comment]
Wow.. @traviceCI is taking its time for this commit..

**Comment by DanielRosenwasser** [comment]
The suspense...

**Comment by mhegazy** [comment]
thanks @martine!
