### PR TITLE
Fix js declaration emit for inherited and this-typed inherited fields

### LINKED ISSUE #35932: Wrong declaration file generated for JS + subclass
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

> src/tsconfig.json
```jsonc
{
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "declarationDir": "../dts/"
  }
}
```

> src/index.js (Important, this only happens in .js file)
```js
export class A {
  /** @returns {this} */
  method() {}
}
export default class Base extends A {
  // This method is required to reproduce this bug
  verify() {}
}
```

**Expected behavior:**

Generated `.d.ts`:

```ts
export declare class A {
    /** @returns {this} */
    method(): void;
}
export default class Base extends A {
    verify(): void;
}
```

**Actual behavior:**

```ts
export class A {
    /** @returns {this} */
    method(): A;
}
export default class Base extends A {
    verify(): void;
    /** @returns {this} */
    method(): Base;
}
```

The wrong behavior:
1. Methods from the parent class is copied to the subclass
2. The return type of copied class is wrong (should be `this`, actually the class name.)

This behavior cause the error following:

(The parent class is `import('events').EventEmitter`)

image

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #35932

### CODE REVIEW

File: tests/baselines/reference/jsDeclarationsInterfaces.js [hunk 1]
```diff
@@ -135,10 +135,10 @@ export interface B {
 export interface C<T_1, U_1> {
     new (): string;
     new (x: T_1): U_1;
-    new <Q_4>(x: Q_4): T_1 & Q_4;
+    new <Q_6>(x: Q_6): T_1 & Q_6;
     (): number;
     (x: T_1): U_1;
-    <Q_3>(x: Q_3): T_1 & Q_3;
+    <Q_4>(x: Q_4): T_1 & Q_4;
```
Comment (andrewbranch) [inline tests/baselines/reference/jsDeclarationsInterfaces.js:141]: Not 100% sure what triggered these changes, but seems fine?

Comment (weswigham) [reply tests/baselines/reference/jsDeclarationsInterfaces.js:141]: The intervening number got marked as potentially used when traversing the base classes, but then ultimately elided, I believe. I could put in some extra effort to keep the numbers compressed, but because it doesn't particularly matter, I saw no reason to.
