### PR TITLE
Fix cache invalidation

### LINKED ISSUE #22710: Watch mode doesn't correctly invalidate failed subdirectory lookup results
**TypeScript Version:**  2.8.0-dev.20180318

**Search Terms:** watch mode subdirectory

**Code**

You'll need 4 files
```ts
// tsconfig.json
// FOR THIS BUG, ORDER MATTERS IN THE FILE ARRAY
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs"
  },
  "files": [
    "foo/a.ts",
    "foo/bar/b.ts"
  ]
}

// foo/a.ts
import * as q from 'qqq';

// foo/bar/b.ts
import * as q from 'qqq';

// node_modules/qqq/index_.d.ts
export { }
```

Run `tsc -w`:
```
20:37:52 - Starting compilation in watch mode...
foo/a.ts(1,20): error TS2307: Cannot find module 'qqq'.
foo/bar/b.ts(1,20): error TS2307: Cannot find module 'qqq'.
20:37:54 - Compilation complete. Watching for file changes.
```

Rename `index_.d.ts` to `index.d.ts`:
```
20:38:26 - File change detected. Starting incremental compilation...
foo/bar/b.ts(1,20): error TS2307: Cannot find module 'qqq'.
20:38:26 - Compilation complete. Watching for file changes.
```

**Expected behavior:** In the second compilation, `b.ts` should be able to correctly resolve `qqq`.

**Actual behavior:** Failure as shown above. Reversing the order of files in the `files` array produces the expected behavior.

**Playground Link:** N/A

**Related Issues:** None?

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #22710 

Let's say you perform two different resolutions:
```
Look for 'express' from /foo/bar
Look for 'express' from /foo/bar/baz
```
The first search generates search paths, also known as "failed lookup locations", like this:
```
/foo/bar/node_modules/express/index.d.ts
/foo/node_modules/express/index.d.ts
/node_modules/express/index.d.ts
```
As well as a bunch of other variants (like the `@types` packages).

During the second search from `/foo/bar/baz`, we look for e.g. `/foo/bar/baz/node_modules/express`. This generates ~10 failed lookup locations.
Then we go up a directory and see that there's a cached module resolution result from `/foo/bar` for the same module. At that point we immediately abort the search.

We attach the failed lookup locations to the file that was looking for them. Because we aborted the search early, we only stored `/foo/bar/baz/node_modules/express` and its variants for the files that were under a subfolder.

Later when `/foo/bar/node_modules/express` *does* exist (as triggered by the file watcher), we scanned over all the source files to see if they need their resolution re-done. Because the files under `/foo/bar/baz` *didn't* record a failed lookup location for this folder, they got skipped during program recomputation.

The fix is to record the failed lookup locations in the cache along with the resolution outcome, and concat the "local" failed lookup locations to those in the cache when reporting the module resolution results.

cc @aozgaa who helped debug this

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@sheetalkamat review?

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -1202,8 +1206,13 @@ namespace ts {
             if (traceEnabled) {
                 trace(host, Diagnostics.Resolution_for_module_0_was_found_in_cache_from_location_1, moduleName, containingDirectory);
             }
-            return { value: result.resolvedModule && { path: result.resolvedModule.resolvedFileName, extension: result.resolvedModule.extension, packageId: result.resolvedModule.packageId } };
+            return {
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts]: Can we instead pass failed lookup locations here so that we do not create another objects just to unwrap this one and add failed lookup locations at caller site?

Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts]: we also get to keep failed lookup locations as Push<string> then right?

File: src/harness/unittests/tsserverProjectSystem.ts [hunk 2]
```diff
@@ -6178,6 +6182,13 @@ namespace ts.projectSystem {
                 timeoutAfterReloadFs = true;
                 verifyAfterPartialOrCompleteNpmInstall(2);
 
+                if (!timeoutDuringPartialInstallation) {
+                    const project = projectService.configuredProjects.get(tsconfigJson.path);
+                    for (const err of project.getCurrentProgram().getSemanticDiagnostics()) {
+                        assert.fail(`Unexpected semantic error ${err.messageText} in project`);
+                    }
+                }
+
```
Comment (sheetalkamat) [inline src/harness/unittests/tsserverProjectSystem.ts]: Instead of changing this test case can we add separate test case that verifies actual scenario of not invalidating module resolution correctly for subFolder/app2 (by verifying semanticDiagnostics) for both classic and node modules resolution

**Comment by RyanCavanaugh** [comment]
@sheetalkamat updated

File: src/harness/unittests/tsserverProjectSystem.ts [hunk 3]
```diff
@@ -6045,6 +6045,47 @@ namespace ts.projectSystem {
             });
         });
 
+        describe("Subfolder invalidations correctly include parent folder failed lookup locations QJWOP", () => {
```
Comment (sheetalkamat) [inline src/harness/unittests/tsserverProjectSystem.ts]: nit. Remove "QJWOP"

File: src/harness/unittests/tsserverProjectSystem.ts [hunk 4]
```diff
@@ -6045,6 +6045,47 @@ namespace ts.projectSystem {
...
+                const host = createServerHost(files);
+                const service = createProjectService(host);
+                service.openClientFile(file1.path);
+
+                const project = service.configuredProjects.get(tsconfig.path);
+                checkProjectActualFiles(project, files.map(f => f.path));
+                assert.deepEqual(project.getLanguageService().getSemanticDiagnostics(file1.path).map(diag => diag.messageText), ["Cannot find module 'debug'."]);
+                assert.deepEqual(project.getLanguageService().getSemanticDiagnostics(file2.path).map(diag => diag.messageText), ["Cannot find module 'debug'."]);
+
+                const debugTypesFile: FileOrFolder = {
```
Comment (sheetalkamat) [inline src/harness/unittests/tsserverProjectSystem.ts]: Can we have this whole test case as a function and pass in location and compiler options as parameter (with node_modules location and module resolution = node | classic to cover both scenarios )

**Comment by RyanCavanaugh** [comment]
@sheetalkamat OK to check in the 2.8 port without the additional test?

**Comment by sheetalkamat** [comment]
yes
