### PR TITLE
Explicitly exclude . and .. for fs.readdirSync

### LINKED ISSUE #7469: TypeScript language service crashes on projects on a mounted SharePoint WebDav folder
_From @jandersonfcosta on March 8, 2016 15:31_

After update VSC to 0.10.10, javascript intellisense stop working.

VSC show warn message: "**The Typescript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report.**"

Any idea?
Thank you!

_Copied from original issue: Microsoft/vscode#3860_

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #7469

Exclude "." and ".." from the `fs.readdir` result explicitly due to the node bug that in some cases it fails to exclude these two items. (See https://github.com/Microsoft/vscode/issues/3860 and https://github.com/nodejs/node/issues/4002)

### CODE REVIEW

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -495,7 +495,9 @@ namespace ts {
                 visitDirectory(path);
                 return result;
                 function visitDirectory(path: string) {
-                    const files = _fs.readdirSync(path || ".").sort();
+                    // This filtering is necessary because on some file system node fails to exclude 
+                    // "." and "..". See https://github.com/nodejs/node/issues/4002
+                    const files = filter(<string[]>_fs.readdirSync(path || "."), f => f !== "." && f !== "..").sort();
                     const directories: string[] = [];
                     for (const current of files) {
                         const name = combinePaths(path, current);
```
Comment (mhegazy) [inline src/compiler/sys.ts]: how about `if (current === "." || current === "..") continue; ` instead of the filter.

Comment (zhengbli) [inline src/compiler/sys.ts]: Would be better. Updated.

**Comment by mhegazy** [comment]
:+1:
