### PR TITLE
[Master] fix 15463

### LINKED ISSUE #15463: is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes
**TypeScript Version:**  2.3.1

**Code**

With the above mentioned version I can't spread Props objects anymore to child React components, when the Props don't match up 100%.

```ts

/* App.tsx */

interface Props {
    ...
    scopes: any;
}

interface State {}

export class App extends React.Component<Props, State> {
    render() {
         return <Content {...this.props} />; // error
    }
}

/* Content.tsx */

interface Props {
    ...
    // without scopes in Props
}

export default class Content extends React.Component<Props, {}>{
    ...
}
```

**Expected behavior:**
No error and there wasn't any on 2.2.1

**Actual behavior:**

error:
```
ERROR in ./spa/js/comps/App.tsx
(121,49): error TS2322: Type '{ ui?: UIState; session?: SessionState; scopes?: any; users?: any; roles?: any; plugins?: any; us...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Content> & Props & { children?: ReactNode; }'.
  Property 'scopes' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Content> & Props & { children?: ReactNode; }'.
```

### PR DESCRIPTION
**Pull request by yuit**
Fix #15463 We are now checking attributes according to:

1. Only contain explicitly attributes -> no excess properties allowed

2. Contain spread attributes (even with explicit attributes) -> 1. check type assignability (allow access properties) 2. for each explicit attributes check if the attribute name match the target name.

3. we only report that "children" will get overwritten if it is explicitly specified in the attributes and the element contains JSX.children

- [x] Add more tests

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13351,7 +13356,8 @@ namespace ts {
              */
             function createJsxAttributesType(symbol: Symbol, attributesTable: Map<Symbol>) {
                 const result = createAnonymousType(symbol, attributesTable, emptyArray, emptyArray, /*stringIndexInfo*/ undefined, /*numberIndexInfo*/ undefined);
-                const freshObjectLiteralFlag = compilerOptions.suppressExcessPropertyErrors ? 0 : TypeFlags.FreshLiteral;
+                // Spread object doesn't have freshness flag to allow excess attributes as it is very common for parent component to spread its "props" to other components in its render method.
+                const freshObjectLiteralFlag = spread !== emptyObjectType || compilerOptions.suppressExcessPropertyErrors ? 0 : TypeFlags.FreshLiteral;
```
Comment (mhegazy) [inline src/compiler/checker.ts]: so why do we have this flag, should not the check below catch all the cases?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -13904,6 +13910,16 @@ namespace ts {
             }
             else {
                 checkTypeAssignableTo(sourceAttributesType, targetAttributesType, openingLikeElement.attributes.properties.length > 0 ? openingLikeElement.attributes : openingLikeElement);
+                // If sourceAttributesType has spread (e.g the type doesn't have freshness flag) after we check for assignability, we will do another pass to check that
+                // all explicitly specified attributes have correct name corresponding with target (as those will be assignable as spread type allows excess properties)
+                // Note: if the type of these explicitly specified attributes do not match it will be an error during above assignability check.
+                if (sourceAttributesType !== anyType && !(sourceAttributesType.flags & TypeFlags.FreshLiteral)) {
+                    for (const attribute of openingLikeElement.attributes.properties) {
+                        if (isJsxAttribute(attribute) && !getPropertyOfType(targetAttributesType, attribute.name.text)) {
+                            error(attribute, Diagnostics.Property_0_does_not_exist_on_type_1, attribute.name.text, typeToString(targetAttributesType));
```
Comment (mhegazy) [inline src/compiler/checker.ts]: i would break after the first error to avoid cascading errors.

File: src/compiler/checker.ts (hunk 1 above)
Comment (yuit) [inline src/compiler/checker.ts]: yes but I don't think we should do it is all explicitly defined. since that case you should cover by type assignability check

Comment (mhegazy) [inline src/compiler/checker.ts]: not sure i understand

Comment (yuit) [inline src/compiler/checker.ts]: talk offline with @mhegazy  it is being too clever and doing second pass isn't expensive so we should remove this flag and always check for that explicit property has correct name
