### PR TITLE
Remove error on invalid jsdoc tokens

### LINKED ISSUE #32756: Scanner change in #32716 reports errors on jsdoc
```js
/**
 * RegExp to match quoted-pair in RFC 2616
 *
 * quoted-pair = "\" CHAR
 * CHAR        = <any US-ASCII character (octets 0 - 127)>
 * @private
 */
```

**Expected behavior:**
No errors

**Actual behavior:**
Errors on `"\"` (unexpected character) and `@private` ('private' is reserved in strict mode)

### PR DESCRIPTION
**Pull request by sandersn**
In JSDoc:

1. In the scanner, don't issue an error, even for invalid identifiers.
2. In the binder, don't issue an error for reserved (but otherwise valid)
identifiers.

```js
/**
 * Example of 1: "\"
 * Example of 2: @private
 */
```

I'm not sure of the fix in the binder. It might be better to avoid setting originalKeywordKind in the parser for bad identifiers in jsdoc, but that seems wrong because the jsdoc code path really should behave just like the normal one so that it's easy to remove later.

Fixes #32756

### CODE REVIEW

File: src/compiler/scanner.ts [hunk 1]
```diff
@@ -2159,7 +2159,6 @@ namespace ts {
                         tokenValue = String.fromCharCode(cookedChar) + scanIdentifierParts();
                         return token = getIdentifierToken();
                     }
-                    error(Diagnostics.Invalid_character);
                     pos++;
```
Comment (weswigham) [inline src/compiler/scanner.ts]: Should we also be ignoring errors on invalid Unicode escapes, like `\u{1010101010}`? That'll require passing a flag into `scanIdentifierParts` and the other callers of `scanExtendedUnicodeEscape`.

Comment (sandersn) [reply src/compiler/scanner.ts]: I can't get any error with the current code! I compared

```js
/**
 * unicode-escape = \u{abcdefghi} -- should not have error for invalid unicode escape
 */
var hi = "\u{00fa}\u{abcdefghi}"
```

There's an error for the second `abcdefghi` but not the first.

I'll add a test to make sure it stays that way.

Comment (weswigham) [reply src/compiler/scanner.ts]: You should also check, just in case, the scenario when the unicode escape is the second character in the identifier `eg, q\u{abcdefghi}` - The first character is handled inline in `scanJsDocToken` with a non-erroring `peek` (so it can fallback to the `Invalid character` error you just removed), while the second character (and beyond) is handled in `scanIdentifierParts` which, I could always behave different.

Comment (sandersn) [reply src/compiler/scanner.ts]: Done.
