### PR TITLE
Fix auto-imports from auto type acquisition definitions

### LINKED ISSUE #33289: Global completion / Auto import for JavaScript symbols from modules without typings included.
## Search Terms
"auto import",  "completion", "auto import global", "auto import cache"

## Suggestion

Hi, first of all good job for your awesome work.

My suggestion is simple : 
When the completion is triggered, we filter the results to exclude the ones that are not importable. As you can see in https://github.com/microsoft/TypeScript/blob/3c4276076595446ddefd24e16d549e1323a3ed8a/src/services/codefixes/importFixes.ts#L610
However in some cases we want symbols that are not directly importable.
For example, if a JavaScript dependency doesn't include a `.d.ts` file, and there is one available in the TypeScript cache folder (downloaded by VSCode Automatic Type Acquisition).

I think this would fix a lot of users issues.
For example : https://github.com/microsoft/TypeScript/issues/29039

## Use Cases
This would permit, to auto import the symbols from a JavaScript package that does not include a `.d.ts` in his sources.
For example : `react-redux`, `lodash`.

## Examples

I commented the code inside `isImportablePath` to have a hacky prototype.
This looks like this : 
Kapture 2019-09-06 at 23 03 55
But a better version would be this (I simply copied the d.ts from the global cache to the `node_modules`) : 
Kapture 2019-09-06 at 23 10 50
Today it looks like this (you can reproduce it creating a JavaScript project and installing react-redux) :
Kapture 2019-09-06 at 23 07 06

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #33289

### CODE REVIEW

File: src/harness/harnessLanguageService.ts [hunk 1]
```diff
@@ -220,6 +220,10 @@ namespace Harness.LanguageService {
             return !!this.typesRegistry && this.typesRegistry.has(name);
         }
 
+        getGlobalTypingsCacheLocation() {
+            return "/Library/Caches/typescript";
```
Comment (andrewbranch) [inline src/harness/harnessLanguageService.ts]: Anyone have a less kludgy idea for how to test this? I looked into the server fourslash tests, but it would ultimately require the same kind of hard-coded hack, just buried deeper in the infrastructure.

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -669,10 +670,11 @@ namespace ts.codefix {
      * Don't include something from a `node_modules` that isn't actually reachable by a global import.
      * A relative import to node_modules is usually a bad idea.
      */
-    function isImportablePath(fromPath: string, toPath: string): boolean {
+    function isImportablePath(fromPath: string, toPath: string, globalCachePath?: string): boolean {
         // If it's in a `node_modules` but is not reachable from here via a global import, don't bother.
         const toNodeModules = forEachAncestorDirectory(toPath, ancestor => getBaseFileName(ancestor) === "node_modules" ? ancestor : undefined);
-        return toNodeModules === undefined || startsWith(fromPath, getDirectoryPath(toNodeModules));
+        const toNodeModulesParent = toNodeModules && getDirectoryPath(toNodeModules);
+        return toNodeModulesParent === undefined || startsWith(fromPath, toNodeModulesParent) || (!!globalCachePath && startsWith(globalCachePath, toNodeModulesParent));
```
Comment (sheetalkamat) [inline src/services/codefixes/importFixes.ts]: Is comparison to filename correct? You want to compare canonical file Names instead?

Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts]: That’s probably correct—in this case I was just matching suit with the existing code. I don’t think it matters here since `toPath`, `fromPath`, and `globalCachePath` all come properly cased from the file system.

Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts]: @sheetalkamat can you re-validate whether this is ok?

Comment (sheetalkamat) [reply src/services/codefixes/importFixes.ts]: I don't think its ok.. Since those are sourceFile.fileName as fromPath and toPath (these can change path depending on how file was discovered eg. reference, import etc on case insensitive file systems) while `globalCachePath` is from filesystem. So it does need to consider casing..

Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts]: Makes sense, updated 👍
