### PR TITLE
Correctly serialize types with signatures containing binding patterns

### LINKED ISSUE #7222: Incorrect .d.ts generated for destructuring arrow function with default
**TypeScript Version:** 
1.8.2 / nightly (1.9.0-dev.20160224)

#### Code ####
**main.tsx:**

```ts
import React = __React;
namespace A {
    export const Greeter = ({name = 'world'}) => <div>Hello, {name}!</div>;
}
```

**module1.tsx:**

```ts
const B = <A.Greeter/>;
```

**react.d.ts**
```ts
// latest version from the DT repo
```

#### Action ####
I run the following commands:

```
> tsc -d --jsx react react.d.ts main.tsx
> tsc --jsx react react.d.ts main.d.ts module1.tsx
```

#### Expected behavior ####
Both commands successfully complete.

#### Actual behavior ####
On TS 1.9.x:
```
> tsc --jsx react react.d.ts main.d.ts module1.tsx
main.d.ts(3,22): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

On TS 1.8.2:
```
> tsc --jsx react react.d.ts main.d.ts module1.tsx
main.d.ts(3,22): error TS1131: Property or signature expected.
main.d.ts(3,37): error TS1128: Declaration or statement expected.
main.d.ts(4,14): error TS1109: Expression expected.
main.d.ts(5,6): error TS1128: Declaration or statement expected.
main.d.ts(5,8): error TS1128: Declaration or statement expected.
main.d.ts(6,1): error TS1128: Declaration or statement expected.
```

##### Notes #####
It seems that the generated typings file, `main.d.ts`, is invalid:

```
import React = __React;
declare namespace A {
    const Greeter: ({name = 'world'}: {
        name?: string;
    }) => JSX.Element;
}
```

### PR DESCRIPTION
**Pull request by mhegazy**
Fixes #7222.

Before we did not special case binding patterns when serializing a type, and just tried to write then as parameter names, that resulted in getting the string of the node, which may contain initialization/references to local variables, etc..This change adds special handling for binding patterns in signatures. 

Note we could just emit the name as a temp variable, but adding the full context seems more user-friendly and is inline with what we do in the declaration emitter (when we are serializing nodes instead of serializing inferred types in here).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
+            function buildBindingElementDisplay(bindingElement: BindingElement, writer: SymbolWriter, enclosingDeclaration?: Node, flags?: TypeFormatFlags, symbolStack?: Symbol[]) {
+                if (bindingElement.kind === SyntaxKind.OmittedExpression) {
+                    return;
+                }
+                Debug.assert(bindingElement.kind === SyntaxKind.BindingElement);
+                if (bindingElement.propertyName) {
+                    writer.writeSymbol(getTextOfNode(bindingElement.propertyName), bindingElement.symbol);
+                    writePunctuation(writer, SyntaxKind.ColonToken);
+                }
+                if (bindingElement.name) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: When would you not have a name?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
-                            writeSpace(writer);
-                        }
-                        buildTypeParameterDisplay(typeParameters[i], writer, enclosingDeclaration, flags, symbolStack);
-                    }
+                    buildDisplatForCommaSeparatedList(typeParameters, writer, enclosingDeclaration, flags, symbolStack, buildTypeParameterDisplay);
                     writePunctuation(writer, SyntaxKind.GreaterThanToken);
                 }
             }
 
+            function buildDisplatForCommaSeparatedList<T>(list: T[], writer: SymbolWriter, enclosingDeclaration: Node, flags: TypeFormatFlags, symbolStack: Symbol[], action: (item: T, writer: SymbolWriter, enclosingDeclaration: Node, flags: TypeFormatFlags, symbolStack: Symbol[]) => void) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `buildDisplatForCommaSeparatedList` -> `buildDisplayForCommaSeparatedList`

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
+                if (bindingPattern.kind === SyntaxKind.ObjectBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBraceToken);
+                    buildDisplatForCommaSeparatedList(bindingPattern.elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
+                    writePunctuation(writer, SyntaxKind.CloseBraceToken);
+                }
+                else if (bindingPattern.kind === SyntaxKind.ArrayBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBracketToken);
+                    const elements = bindingPattern.elements;
+                    buildDisplatForCommaSeparatedList(bindingPattern.elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
+                    if (elements && elements.hasTrailingComma) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Why would `elements` be undefined?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
+                // We have to explicitly emit square bracket and bracket because these tokens are not store inside the node.
+                if (bindingPattern.kind === SyntaxKind.ObjectBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBraceToken);
+                    buildDisplatForCommaSeparatedList(bindingPattern.elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
+                    writePunctuation(writer, SyntaxKind.CloseBraceToken);
+                }
+                else if (bindingPattern.kind === SyntaxKind.ArrayBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBracketToken);
+                    const elements = bindingPattern.elements;
+                    buildDisplatForCommaSeparatedList(bindingPattern.elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You already have `elements`, use that instead of `bindingPattern.elements`

File: src/compiler/checker.ts (hunk 1 above)
Comment (mhegazy) [inline src/compiler/checker.ts]: you can have an empty object binding batter

**Comment by mhegazy** [comment]
any more comments?

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Discussed offline, I don't think there can be

File: tests/baselines/reference/declarationEmit_bindingPatters.js [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+var a;
+function f(_a, _b, _c) {
+    var _a = a;
+    var _b = a;
+    var _d = (_c === void 0 ? a : _c).p, _e = _d === void 0 ? a : _d;
+}
+
+
+//// [declarationEmit_bindingPatters.d.ts]
+declare const k: ({x:z}: {
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/declarationEmit_bindingPatters.js]: Looks like there should be a space after the colon and before/after the binding elements

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
+            }
+
+            function buildBindingElementDisplay(bindingElement: BindingElement, writer: SymbolWriter, enclosingDeclaration?: Node, flags?: TypeFormatFlags, symbolStack?: Symbol[]) {
+                if (bindingElement.kind === SyntaxKind.OmittedExpression) {
+                    return;
+                }
+                Debug.assert(bindingElement.kind === SyntaxKind.BindingElement);
+                if (bindingElement.propertyName) {
+                    writer.writeSymbol(getTextOfNode(bindingElement.propertyName), bindingElement.symbol);
+                    writePunctuation(writer, SyntaxKind.ColonToken);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Write a space afterwards

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
+                    writePunctuation(writer, SyntaxKind.CloseBraceToken);
+                }
+                else if (bindingPattern.kind === SyntaxKind.ArrayBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBracketToken);
+                    const elements = bindingPattern.elements;
+                    buildDisplayForCommaSeparatedList(elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
+                    if (elements && elements.hasTrailingComma) {
+                        writePunctuation(writer, SyntaxKind.CommaToken);
+                    }
+                    writePunctuation(writer, SyntaxKind.CloseBracketToken);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Emit a space before this

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
                 buildTypeDisplay(getTypeOfSymbol(p), writer, enclosingDeclaration, flags, symbolStack);
             }
 
+            function buildBindingPatternDisplay(bindingPattern: BindingPattern, writer: SymbolWriter, enclosingDeclaration?: Node, flags?: TypeFormatFlags, symbolStack?: Symbol[]) {
+                // We have to explicitly emit square bracket and bracket because these tokens are not store inside the node.
+                if (bindingPattern.kind === SyntaxKind.ObjectBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBraceToken);
+                    buildDisplayForCommaSeparatedList(bindingPattern.elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
+                    writePunctuation(writer, SyntaxKind.CloseBraceToken);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Emit a space before this

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
                 buildTypeDisplay(getTypeOfSymbol(p), writer, enclosingDeclaration, flags, symbolStack);
             }
 
+            function buildBindingPatternDisplay(bindingPattern: BindingPattern, writer: SymbolWriter, enclosingDeclaration?: Node, flags?: TypeFormatFlags, symbolStack?: Symbol[]) {
+                // We have to explicitly emit square bracket and bracket because these tokens are not store inside the node.
+                if (bindingPattern.kind === SyntaxKind.ObjectBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBraceToken);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Space after this

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
 
+            function buildBindingPatternDisplay(bindingPattern: BindingPattern, writer: SymbolWriter, enclosingDeclaration?: Node, flags?: TypeFormatFlags, symbolStack?: Symbol[]) {
+                // We have to explicitly emit square bracket and bracket because these tokens are not store inside the node.
+                if (bindingPattern.kind === SyntaxKind.ObjectBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBraceToken);
+                    buildDisplayForCommaSeparatedList(bindingPattern.elements, writer, enclosingDeclaration, flags, symbolStack, buildBindingElementDisplay);
+                    writePunctuation(writer, SyntaxKind.CloseBraceToken);
+                }
+                else if (bindingPattern.kind === SyntaxKind.ArrayBindingPattern) {
+                    writePunctuation(writer, SyntaxKind.OpenBracketToken);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Space after this

File: tests/baselines/reference/declarationEmit_bindingPatters.js [hunk 11]
```diff
@@ -0,0 +1,26 @@
+//// [declarationEmit_bindingPatters.ts]
```
Comment (sandersn) [inline tests/baselines/reference/declarationEmit_bindingPatters.js]: typo:Patters -> Patterns

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
                 buildTypeDisplay(getTypeOfSymbol(p), writer, enclosingDeclaration, flags, symbolStack);
             }
 
+            function buildBindingPatternDisplay(bindingPattern: BindingPattern, writer: SymbolWriter, enclosingDeclaration?: Node, flags?: TypeFormatFlags, symbolStack?: Symbol[]) {
+                // We have to explicitly emit square bracket and bracket because these tokens are not store inside the node.
```
Comment (sandersn) [inline src/compiler/checker.ts]: are not *stored*

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -2186,20 +2191,64 @@ namespace ts {
...
-                            writeSpace(writer);
-                        }
-                        buildTypeParameterDisplay(typeParameters[i], writer, enclosingDeclaration, flags, symbolStack);
-                    }
+                    buildDisplayForCommaSeparatedList(typeParameters, writer, enclosingDeclaration, flags, symbolStack, buildTypeParameterDisplay);
                     writePunctuation(writer, SyntaxKind.GreaterThanToken);
                 }
             }
 
+            function buildDisplayForCommaSeparatedList<T>(list: T[], writer: SymbolWriter, enclosingDeclaration: Node, flags: TypeFormatFlags, symbolStack: Symbol[], action: (item: T, writer: SymbolWriter, enclosingDeclaration: Node, flags: TypeFormatFlags, symbolStack: Symbol[]) => void) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: why not have `action` capture `enclosingDeclaration, flags, symbolStack` instead of passing them through? It would make the signature much smaller. And 

```ts
buildDisplayForCommaSeparatedList(typeParameters, p => buildTypeParameterDisplay(p, writer, enclosingDeclaration, flags, symbolStack))
``` 
seems easier to read too.

**Comment by sandersn** [comment]
:+1: after the spaces are put back in. I also have an optional style suggestion.

File: src/compiler/checker.ts (hunk 12 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: square brackets and curly braces

File: tests/baselines/reference/declarationEmit_bindingPatters.js (hunk 5 above)
Comment (mhegazy) [inline tests/baselines/reference/declarationEmit_bindingPatters.js]: i agree with the space after the colon, but not with the one after/before the curlies in the binding pattern. we do not do this in formatting, nor in the declaration emit.

File: src/compiler/checker.ts (hunk 7 above)
Comment (mhegazy) [inline src/compiler/checker.ts]: we do not do this in declaration emit nor in formatting.

File: src/compiler/checker.ts (hunk 8 above)
Comment (mhegazy) [inline src/compiler/checker.ts]: we do not do this in declaration emit nor in formatting.

File: tests/baselines/reference/declarationEmit_bindingPatters.js (hunk 5 above)
Comment (DanielRosenwasser) [inline tests/baselines/reference/declarationEmit_bindingPatters.js]: The formatter actually doesn't seem to touch curlies in a binding pattern, and this is how we usually write code in our compiler:

```ts
const { exportsWithDuplicate } = lookupTable[id];
```

So I'd argue that the formatter actually needs to be updated.

Comment (mhegazy) [inline tests/baselines/reference/declarationEmit_bindingPatters.js]: it does not add them if they do not exist. before they were written the same way the user wrote them. now we are serializing them. so i will keep it consistent with the declaration emit, feel free to file an issue for it.

**Comment by sandersn** [comment]
:+1:
