### PR TITLE
Fixes type predicate crash bug

### LINKED ISSUE #3550: Crash on trying to apply invalid type predicate
```typescript
class A {
    constructor(...args) {
        
    }

    q: string;
}

class V extends A {
    m: number;
}


class S extends A {
    m: number;
}

var m = new A(...[1, 3]);

declare function isV(): m is V; 

if (isV()) { 
    m.m; 
}
```

```
C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript>node built\local\tsc.js
 hello.ts
C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\built\local\tsc.js:1720
2
            for (var parent_5 = node.parent; parent_5; parent_5 = parent_5.par
                                    ^
TypeError: Cannot read property 'parent' of undefined
    at resolveLocation (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript
\built\local\tsc.js:17202:37)
    at getSymbolAtLocation (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeSc
ript\built\local\tsc.js:17211:13)
    at narrowTypeByTypePredicate (C:\Users\Anton.Lobov\Desktop\ts-latest-github\
TypeScript\built\local\tsc.js:17409:21)
    at narrowType (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript\buil
t\local\tsc.js:17425:32)
    at getNarrowedTypeOfSymbol (C:\Users\Anton.Lobov\Desktop\ts-latest-github\Ty
peScript\built\local\tsc.js:17248:52)
    at checkIdentifier (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript
\built\local\tsc.js:17469:20)
    at checkExpressionWorker (C:\Users\Anton.Lobov\Desktop\ts-latest-github\Type
Script\built\local\tsc.js:19888:28)
    at checkExpression (C:\Users\Anton.Lobov\Desktop\ts-latest-github\TypeScript
\built\local\tsc.js:19863:42)
    at checkPropertyAccessExpressionOrQualifiedName (C:\Users\Anton.Lobov\Deskto
p\ts-latest-github\TypeScript\built\local\tsc.js:18247:24)
    at checkPropertyAccessExpression (C:\Users\Anton.Lobov\Desktop\ts-latest-git
hub\TypeScript\built\local\tsc.js:18241:20)
```

### PR DESCRIPTION
**Pull request by tinganho**
Fixes #3550.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5761,6 +5761,7 @@ namespace ts {
                 let signature = getResolvedSignature(expr);
 
                 if (signature.typePredicate &&
+                    expr.arguments[signature.typePredicate.parameterIndex] &&
                     getSymbolAtLocation(expr.arguments[signature.typePredicate.parameterIndex]) === symbol) {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Can you change this to call getSymbolOfNode instead of getSymbolAtLocation?

**Comment by JsonFreeman** [comment]
:+1:

File: src/compiler/checker.ts (hunk 1 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Never mind. My suggestion does not work.

**Comment by JsonFreeman** [comment]
Thanks!
