### PR TITLE
Fix some bad jsdoc comment indent

### LINKED ISSUE #15749: JSDoc stripping leading whitespace in code blocks
From: https://github.com/Microsoft/vscode/issues/26415

**TypeScript Version:**  2.3.2

**Code**

```ts
/**
 * @example
 * ```
 * if (true) {
 *     foo()
 * }
 * ```
 */
function foo() {
    return '2';
}
```

**Expected behavior:**
For the `@example` tag, we should return content including any leading whitespace

**Actual behavior:**
In this case, whitespace is stripped: 

```
[Trace - 3:32:54 PM] Response received: quickinfo (120). Request took 2 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "",
    "start": {
        "line": 9,
        "offset": 10
    },
    "end": {
        "line": 9,
        "offset": 13
    },
    "displayString": "function foo(): string",
    "documentation": "",
    "tags": [
        {
            "name": "example",
            "text": "```\nif (true) {\nfoo()\n}\n```"
        }
    ]
}
```

This results in incorrect rendering of the code example:

screen shot 2017-05-10 at 3 33 17 pm

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #15749 plus a few other cases I discovered.

Yes, I know the baseline format is horrible. Sorry.

### CODE REVIEW

**Comment by sandersn** [comment]
I added a few reviewers who might have parsed things in the past.

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -6441,7 +6441,6 @@ namespace ts {
                                     // for malformed examples like `/** @param {string} x @returns {number} the length */`
                                     state = JSDocState.BeginningOfLine;
                                     margin = undefined;
-                                    indent++;
```
Comment (sandersn) [inline src/compiler/parser.ts]: this was just wrong, as far as I can tell, but only was used for tags followed by a newline:

```js
@ex
stuff
```

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -6536,32 +6535,38 @@ namespace ts {
...
                         else if (token() === SyntaxKind.AsteriskToken) {
                             precedingLineBreak = false;
                         }
                         nextJSDocToken();
                     }
+                    return seenLineBreak ? indentText : "";
                 }
 
-                function parseTag(indent: number) {
+                function parseTag(margin: number) {
```
Comment (sandersn) [inline src/compiler/parser.ts]: margin is the thing that's fixed, whereas indent goes up for each line. So this name was wrong before.

File: src/compiler/parser.ts [hunk 3]
```diff
@@ -6646,7 +6659,7 @@ namespace ts {
                                     const whitespace = scanner.getTokenText();
                                     // if the whitespace crosses the margin, take only the whitespace that passes the margin
                                     if (margin !== undefined && indent + whitespace.length > margin) {
-                                        comments.push(whitespace.slice(margin - indent - 1));
```
Comment (sandersn) [inline src/compiler/parser.ts]: this math was also wrong before, for the same reason as the `indent++`

File: src/compiler/parser.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/parser.ts]: That is, all our previous tests cases looked like this:

```js
@param x   comment
           comment
              indent
```

Never like this:

```js
@example
comment
comment
  indent
```

so this erroneous increment was hidden by the fact that `indent` had already passed `margin`.
