### PR TITLE
Fix transpiling when options specify incremental or tsbuildinfofile

### LINKED ISSUE #33184: Unexpected multiple outputs
**TypeScript Version:**  3.6.2
After upgrating to TS 3.6.2, everithing else the same, webpack + ts-loader is not able to generate code anymore. Without **transpileOnly:true** works, but it's a big performance panalty. 

Note: I'm using transpileOnly:true for webpack generation and transpileOnly:false + noEmit in MsBuild/VisualStudio. 

**Code**
https://github.com/signumsoftware/southwind/tree/TS36/Southwind.React
https://github.com/signumsoftware/southwind/blob/TS36/Southwind.React/tsconfig.json

**Expected behavior:**
Generates javascript with webpack, ts-loader and with **transpileOnly:true**

**Actual behavior:**
```
=== undefined. Unexpected multiple outputs, file: D:/Signum/southwind/Southwind.React/ts_out/tsconfig.tsbuildinfo
    at Object.assertEqual (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:2056:17)
    at Object.writeFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:112241:30)
    at Object.__assign.writeFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92029:210)
    at Object.writeFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:12098:14)
    at emitBuildInfo (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:86238:16)
    at emitSourceFileOrBundle (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:86205:13)
    at forEachEmittedFile (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:85999:28)
    at Object.emitFiles (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:86184:9)
    at emitWorker (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92134:33)
    at D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92095:66
    at runWithCancellationToken (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92185:24)
    at Object.emit (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:92095:20)
    at Object.transpileModule (D:\Signum\southwind\Southwind.React\node_modules\typescript\lib\typescript.js:112261:17)
    at getTranspilationEmit (D:\Signum\southwind\Southwind.React\node_modules\ts-loader\dist\index.js:283:74)
    at successLoader (D:\Signum\southwind\Southwind.React\node_modules\ts-loader\dist\index.js:66:15)
    at Object.loader (D:\Signum\southwind\Southwind.React\node_modules\ts-loader\dist\index.js:22:12)
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #33184

### CODE REVIEW

File: src/services/transpile.ts [hunk 1]
```diff
@@ -57,6 +57,8 @@ namespace ts {
         options.rootDirs = undefined;
         options.declaration = undefined;
         options.composite = undefined;
+        options.incremental = undefined;
```
Comment (DanielRosenwasser) [inline src/services/transpile.ts]: Probably not for 3.6.3, but should this sort of thing be declared in `commandLineParser.ts` so that every option has to declare it up front?

Comment (sheetalkamat) [reply src/services/transpile.ts]: good idea and will change that but we should do this for 3.6.3 since it is a regression after fixing a bug where we were not emitting tsbuildinfo file if there was no information to emit which was the case in transpile mode and hence worked correctly in 3.5 but after that bug was fixed the tsbuildinfo file is emitted if this fix is not taken and transpile only expects one file to be written.

Comment (DanielRosenwasser) [reply src/services/transpile.ts]: Oh, I meant I agreed that this should go into 3.6.3, but I didn't want you to go through the effort of updating `commandLineParser.ts`. Thanks for doing it though, great work!

**Comment by DanielRosenwasser** [comment]
👍

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.6
