### PR TITLE
routine update of dom libs

### LINKED ISSUE #7528: ParentNode interface missing from dom.d.ts
The [ParentNode](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode) interface (implemented by `Element`, `Document` and `DocumentFragment`) appears to be missing from the `dom.d.ts` declaration file?

### LINKED ISSUE #8955: Subresource Integrity for HTMLScriptElement and HTMLLinkElement
Subresource Integrity (SRI) is currently a [W3 Proposed Recommendation](https://www.w3.org/TR/SRI/#). [It ships with current versions of Firefox and Chrome.](https://www.chromestatus.com/features/6183089948590080)

Setting the `integrity` property should not hurt other browsers, it is a progressive enhancement.

**TypeScript Version:** 

nightly (1.9.0-dev.20160603)

**Code**

```ts
// A self-contained demonstration of the problem follows...
let script = document.createElement('script');
script.integrity = "sha-256-some-hash"
```

**Expected behavior:**

`integrity` property is defined

**Actual behavior:** 

`integrity` property is not defined

### LINKED ISSUE #9206: keypress e.code is not valid TypeScript, but is valid JavaScript
**TypeScript Version:** 

1.8.10

**Code**

```ts
// A self-contained demonstration of the problem follows...

Grrr - I don't have time for this

in an input element onkeypress, you can't touch e.code. You have to create a plain JS function to read that totally legitimate property on the event argument.

```

**Expected behavior:**

(e.code == "Enter") is valid

**Actual behavior:** 

(e.code == "Enter") is not valid because .code is not recognized as a legit property

### LINKED ISSUE #9617: insertAdjacent* methods should be part of the Element interface
_From @davidkmenta on June 30, 2016 14:16_

TypeScript Version: 1.8.10

Expected behavior: According to the MDN (https://developer.mozilla.org/en-US/docs/Web/API/Element), insertAdjacent* methods should be part of the Element interface.

Actual behavior: insertAdjacent* methods are part of the HTMLElement interface.

_Copied from original issue: Microsoft/TSJS-lib-generator#130_

### LINKED ISSUE #9698: Missing secureConnectionStart on PerformanceTiming interface
See: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/secureConnectionStart

**TypeScript Version:**  1.6.1

**Code**

```ts
let timing: PerformanceTiming;
timing.secureConnectionStart = window.performance.timing.secureConnectionStart;
```

**Expected behavior:**

Everything typechecks.

**Actual behavior:** 

`Error TS2339: Property 'secureConnectionStart' does not exist on type 'PerformanceTiming'.`

### LINKED ISSUE #9712: Update Storage interface for non-nullable types
https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface

**TypeScript Version:**  master

**Code**

```diff
interface Storage {
    readonly length: number;
    clear(): void;
-   getItem(key: string): string;
+   getItem(key: string): string | null;
-   key(index: number): string;
+   key(index: number): string | null;
    removeItem(key: string): void;
    setItem(key: string, data: string): void;
    [key: string]: any;
    [index: number]: string;
}
```

### LINKED ISSUE #9850: The global 'name' variable should be declared as a const of type 'never'
As discussed, the `name` global variable causes certain problems. We decided that it should be changed to a `const` with the type `never`.

### LINKED ISSUE #10379: 2.0: window.opener declared as readonly
When you open a popup window of a page on a different domain, [for security reasons you might want to set its window.opener to null](https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c). This is a type error in 2.0 because the `opener` property is incorrectly declared read-only:

```ts
var newWnd = window.open(...);
newWnd.opener = null;
// Left-hand side of assignment expression cannot be a constant or a read-only property.
```

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #10379 
Fixes #9850 
Fixes #9712
Fixes #9698
Fixes #9617
Fixes #9206 
Fixes #8955
Fixes #7528

### CODE REVIEW

**Comment by mhegazy** [comment]
👍

File: src/lib/dom.generated.d.ts [hunk 1]
```diff
@@ -14278,7 +14313,7 @@ declare var location: Location;
 declare var locationbar: BarProp;
 declare var menubar: BarProp;
 declare var msCredentials: MSCredentials;
-declare var name: string;
+declare const name: never;
```
Comment (ccorcos) [inline src/lib/dom.generated.d.ts]: What is this all about?

Comment (zhengbli) [reply src/lib/dom.generated.d.ts]: See https://github.com/Microsoft/TypeScript/issues/9850
