### PR TITLE
getContainingList: Handle TypeAliasDeclaration

### LINKED ISSUE #25589: tsserver: Debug Failure
**TypeScript Version:**  3.0.0-dev.20180710

**Search Terms:** 

**Code**

```ts
Error: Debug Failure.
    at Object.assertDefined (/usr/local/lib/node_modules/typescript/lib/tsserver.js:1435:24)
    at deleteNodeInList (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103545:43)
    at Object.deleteDeclaration (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103443:29)
    at _loop_10 (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103063:43)
    at ChangeTracker.finishDeleteDeclarations (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103069:21)
    at ChangeTracker.getChanges (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103089:22)
    at Function.ChangeTracker.with (/usr/local/lib/node_modules/typescript/lib/tsserver.js:102667:32)
    at Object.getCodeActions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:105704:65)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:103605:121
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103605:23)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:111467:35
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111465:23)
    at IOSession.Session.getCodeFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119022:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:117896:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119186:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119177:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119186:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119206:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120473:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #25589

### CODE REVIEW

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -351,7 +351,8 @@ namespace ts.formatting {
                             getListIfStartEndIsInListRange((<SignatureDeclaration>node.parent).parameters, start, end);
                     }
                     case SyntaxKind.ClassDeclaration:
-                        return getListIfStartEndIsInListRange((<ClassDeclaration>node.parent).typeParameters, node.getStart(sourceFile), end);
+                    case SyntaxKind.TypeAliasDeclaration:
+                        return getListIfStartEndIsInListRange((<ClassDeclaration | TypeAliasDeclaration>node.parent).typeParameters, node.getStart(sourceFile), end);
```
Comment (sheetalkamat) [inline src/services/formatting/smartIndenter.ts]: What about InterfaceDeclaration?
