### PR TITLE
fix super call from class that has no basetype but with same symbol (#19068)

### LINKED ISSUE #19068: No "'super' can only be referenced in a derived class." error when "interface ClassWithNoParent extends SomeInterface {}"
**TypeScript Version:**  2.5.3 / nightly (2.6.0-dev.20171010)

**Code**

```ts
interface Foo extends Array<number> {}
class Foo {
    constructor() {
        super()
    }
}
```

**Expected behavior:**
`'super' can only be referenced in a derived class.`

**Actual behavior:**
no error

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #19068

### CODE REVIEW

**Comment by ly0** [comment]
Great! It is very helpful to me!

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12982,7 +12983,8 @@ namespace ts {
             const classLikeDeclaration = <ClassLikeDeclaration>container.parent;
             const classType = <InterfaceType>getDeclaredTypeOfSymbol(getSymbolOfNode(classLikeDeclaration));
             const baseClassType = classType && getBaseTypes(classType)[0];
-            if (!baseClassType) {
+
+            if (!(classType && classType.resolvedExtendedType)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Instead of adding a field to `InterfaceType`, what if you just always did the `getClassExtendsClause` check below?

**Comment by mhegazy** [comment]
thanks @Kingwl!
