### PR TITLE
Consistently reduce union types

### LINKED ISSUE #2610: Union types are NOT reduced to the smallest possible set
Spec 3.4 says:
> •	A | B is equivalent to A if B is a subtype of A.
>...
> Union types are reduced to the smallest possible set of constituent types using these rules.

This doesn't work in TS 1.4 for union type literals. For example:
```TypeScript
interface I2 {
    (): number;
    (q): boolean;
}

interface I3 {
    (): number;
}

var i2: I2, i3: I3;

var e: I2 | I3; // not reduced
var e1 = i2 || i3; // reduced
var r = e(); // error
var r1 = e1(); // no error
```

P.S. IMHO, the root of the problem is in the way signatures are selected for union types (3.10.1). Signatures for union types should be the same regardless of whether types are reduced or not.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Union types are now consistently reduced to the smallest possible set before members (properties or signatures) are accessed.

Fixes #2610.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2904,16 +2904,17 @@ module ts {
         }
 
         function getPropertiesOfType(type: Type): Symbol[] {
-            if (type.flags & TypeFlags.Union) {
-                return getPropertiesOfUnionType(<UnionType>type);
-            }
-            return getPropertiesOfObjectType(getApparentType(type));
+            type = getApparentType(type);
+            return type.flags & TypeFlags.Union ? getPropertiesOfUnionType(<UnionType>type) : getPropertiesOfObjectType(type);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Split each branch onto its own line:

```TypeScript
return type.flags & TypeFlags.Union ?
    getPropertiesOfUnionType(<UnionType>type) :
    getPropertiesOfObjectType(type);
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -2986,27 +2987,25 @@ module ts {
...
                 }
-            }
-            let resolved = resolveObjectOrUnionTypeMembers(type);
-            if (hasProperty(resolved.members, name)) {
-                let symbol = resolved.members[name];
-                if (symbolIsValue(symbol)) {
-                    return symbol;
+                if (resolved === anyFunctionType || resolved.callSignatures.length || resolved.constructSignatures.length) {
+                    let symbol = getPropertyOfObjectType(globalFunctionType, name);
+                    if (symbol) return symbol;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]:
```TypeScript
if (symbol) {
    return symbol;
}
```

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -3605,10 +3604,18 @@ module ts {
             if (!type) {
                 type = unionTypes[id] = <UnionType>createObjectType(TypeFlags.Union | getWideningFlagsOfTypes(sortedTypes));
                 type.types = sortedTypes;
+                type.reducedType = noSubtypeReduction ? undefined : type;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: When is `noSubtypeReduction` `true`?

File: tests/cases/fourslash/completionEntryForPropertyFromUnionOfModuleType.ts [hunk 4]
```diff
@@ -2,9 +2,11 @@
 
 ////module E {
 ////    export var n = 1;
+////    export var x = 0;
 ////}
 ////module F {
 ////    export var n = 1;
+////    export var y = 0;
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionEntryForPropertyFromUnionOfModuleType.ts]: Confirm that `x` and `y` are not completion entries (i.e. `verify.not`).

File: src/compiler/checker.ts (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: or, preferably:

```ts
return type.flags & TypeFlags.Union
    ? getPropertiesOfUnionType(<UnionType>type)
    : getPropertiesOfObjectType(type);
```

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: :+1: to @CyrusNajmabadi's suggestion

File: src/compiler/checker.ts (hunk 3 above)
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Could we accomplish this in a simpler manner by just having getUnionType always do subtype reduction?  Would that then ensure that all later parts of the checker see the union as consistently reduced?

**Comment by CyrusNajmabadi** [comment]
Does this fix: https://github.com/Microsoft/TypeScript/issues/1953 as well?

If not, is there something we can do while we're addressing consistent reduction to also address the nondeterminism issue as well?

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Fits just fine on one line, I'd prefer to keep it that way.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: The `noSubtypeReduction` flag is there because it isn't possible to always do subtype reduction. The flag is true when creating a union type from a type node and when instantiating a union type. In both of those cases subtype reduction has to be deferred to properly support recursive union types.

**Comment by ahejlsberg** [comment]
No, this isn't related to #1953. We need a different solution for that.

File: src/compiler/checker.ts (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: The problem with long single lines is github:

image

It's actually harder to read because github is optimized for 80 columns.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -2986,27 +2987,27 @@ module ts {
...
+                    if (symbol) {
+                        return symbol;
+                    }
                 }
+                return getPropertyOfObjectType(globalObjectType, name);
             }
-            if (resolved === anyFunctionType || resolved.callSignatures.length || resolved.constructSignatures.length) {
-                let symbol = getPropertyOfObjectType(globalFunctionType, name);
-                if (symbol) return symbol;
+            if (type.flags & TypeFlags.Union) {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Is it at all significant that this case moved to the end of the function? To my reading, it is not.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -2986,27 +2987,27 @@ module ts {
...
-            if (type.flags & TypeFlags.Union) {
-                return getPropertyOfUnionType(<UnionType>type, name);
-            }
-            if (!(type.flags & TypeFlags.ObjectType)) {
-                type = getApparentType(type);
-                if (!(type.flags & TypeFlags.ObjectType)) {
-                    return undefined;
+            type = getApparentType(type);
+            if (type.flags & TypeFlags.ObjectType) {
+                let resolved = resolveObjectOrUnionTypeMembers(type);
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Why don't we need to call resolveObjectOrUnionTypeMembers for unions as well?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -3581,6 +3582,9 @@ module ts {
             }
         }
 
+        // The noSubtypeReduction flag is there because it isn't possible to always do subtype reduction. The flag
+        // is true when creating a union type from a type node and when instantiating a union type. In both of those
+        // cases subtype reduction has to be deferred to properly support recursive union types.
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Is this because of union types in type aliases?

Comment (JsonFreeman) [inline src/compiler/checker.ts]: I think it'd be useful to put an example of each of the two cases, either here or at the relevant calls to getUnionType

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -3605,10 +3609,18 @@ module ts {
...
                 type = unionTypes[id] = <UnionType>createObjectType(TypeFlags.Union | getWideningFlagsOfTypes(sortedTypes));
                 type.types = sortedTypes;
+                type.reducedType = noSubtypeReduction ? undefined : type;
             }
             return type;
         }
 
+        function getReducedTypeOfUnionType(type: UnionType): Type {
+            if (!type.reducedType) {
+                type.reducedType = getUnionType(type.types);
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I'd explicitly pass false here, just because the purpose of this call is to explicitly reduce subtypes for a union that has already been created in the past.

**Comment by JsonFreeman** [comment]
Do we also need to force subtype reduction in applyToContextualType?

File: tests/cases/fourslash/completionEntryForPropertyFromUnionOfModuleType.ts (hunk 4 above)
Comment (mhegazy) [inline tests/cases/fourslash/completionEntryForPropertyFromUnionOfModuleType.ts]: +1 for the check

**Comment by mhegazy** [comment]
:+1:

File: src/compiler/checker.ts (hunk 5 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: No, it is not significant, but I like handling the union case after the object case (as it is less common).

File: src/compiler/checker.ts (hunk 6 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: We resolve all properties of object types in one go because it is cheap to do so, but we resolve union type properties one by one on demand because it involves a lot more work.

Comment (JsonFreeman) [inline src/compiler/checker.ts]: Sounds reasonable. I think this is worth noting in a comment.

**Comment by ahejlsberg** [comment]
@JsonFreeman Regarding subtype reduction in applyToContextualType... No, I don't think we want to do that. When a contextual type is a union type, keeping the all constituents of the union gives us more information. For example, say you have a contextual type A | B, where B is a subtype of A, for some object literal. If B declares some property foo, then keeping B around allows us to contextually type a foo property in the object literal.

**Comment by JsonFreeman** [comment]
Your argument about applyToContextualType makes sense. However, we cannot take advantage of that capability consistently, because the fact is that normally we *do* collapse the union types when we create them. So in many cases, by the time we get to applyToContextualType, it is already too late and we've lost some of the properties.

**Comment by ahejlsberg** [comment]
@JsonFreeman I think we just need to modify the spec to document exactly when subtype reduction occurs. Or, conversely, when it doesn't occur. The latter may be easier as the only time we defer subtype reduction is in an explicitly written type.

**Comment by JsonFreeman** [comment]
And instantiation, but I guess that is a process that's not explained in the spec.

Yes, I think it makes sense to spec subtype reduction, just like how we spec "depends on" for type aliases.

**Comment by JsonFreeman** [comment]
:+1:
