### PR TITLE
JS declaration emit uses `this` for method returns

### LINKED ISSUE #53051: .d.ts emitted from JS doesn't use `this` for method return types
# Bug Report

### 🔎 Search Terms

- jsdoc
- overload
- return type
- inheritance

### 🕗 Version & Regression Information

- This changed between versions 4.5 and 4.6

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5&filetype=js#code/KYDwDg9gTgLgBAYwDYEMDOa4GEIDsZQRJLBRwDeAUAJAJ5oECuCM0AFAJQU0C+lNAegBUQmnCFwAAlGAxGUXJnIwAFgEs0fauIE1GYACYoYwACIawqAJ6du1ajLkK4qjQG5elPpVCRYiVAw4ACEIImAUXBx8QmJSADkIAFEQAhQAWWAAWwAjUjhQE1wDTGiCIhIyKlp6JhZ2LmrqNH1STg9qb2p9IxNzNEsUG0aaGsVwgDokCABzNgByEwZ5jg6HWXlcF3U0Dr5vX2h4ZHRMUPDIstjKgHU1VRS0zNz8wuBi0rxyuKqaOkU6qwoLYmi0wG1VqNXGgJkt4ABeOAAVj2-G6hmMZgs1hBo3+aEm0zmi2Ay0h9kcm227k8fCAA)

### 💻 Code

NOTE: This is JS, not TS.

```js
export class Controller {
	constructor() {
	}

	/**
	 * @returns {this}
	 */
	updateDisplay() {
		return this;
	}
}

export class BooleanControllerNoExtraMember extends Controller {
	constructor() {
		super();
	}

	updateDisplay() {
		console.log('test');
		return this;
	}
}

export class BooleanControllerWithExtraMember extends Controller {
	constructor() {
		super();
		this.test = 5;
	}

	updateDisplay() {
		console.log('test');
		return this;
	}
}
```

### 🙁 Actual behavior

The resulting declaration file includes `updateDisplay()` in `BooleanControllerWithExtraMember` with a return type of `BooleanControllerWithExtraMember`. This is problematic and causes type errors because the return type for `BooleanControllerWithExtraMember.updateDisplay()` needs to be assignable to `this`. Duplicating the JSDoc to specify that it returns `this` is undesirable since we don't want to have to duplicate the JSDoc for all derived classes.

I included `BooleanControllerNoExtraMember` as well to highlight the inconsistency that it sometimes doesn't specify the method overload due to seemingly unrelated changes to the class.

```ts
export class Controller {
    /**
     * @returns {this}
     */
    updateDisplay(): this;
}
export class BooleanControllerNoExtraMember extends Controller {
}
export class BooleanControllerWithExtraMember extends Controller {
    test: number;
    updateDisplay(): BooleanControllerWithExtraMember;
}
```

### 🙂 Expected behavior

`BooleanControllerWithExtraMember` doesn't specify `updateDisplay()` because it doesn't need to. This is how TypeScript 4.5 behaves.

```ts
export class Controller {
    /**
     * @returns {this}
     */
    updateDisplay(): this;
}
export class BooleanControllerNoExtraMember extends Controller {
}
export class BooleanControllerWithExtraMember extends Controller {
    test: number;
}
```

### PR DESCRIPTION
**Pull request by sandersn**
Previously it used the instantiation of `this`, which is the containing class type.

I'm not at all sure this is right, so I would love to know the right way to do this.

Fixes #53051

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9543,6 +9543,9 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 initializer: Expression | undefined
             ) => T, methodKind: SignatureDeclaration["kind"], useAccessors: boolean): (p: Symbol, isStatic: boolean, baseType: Type | undefined) => (T | AccessorDeclaration | (T | AccessorDeclaration)[]) {
                 return function serializePropertySymbol(p: Symbol, isStatic: boolean, baseType: Type | undefined): (T | AccessorDeclaration | (T | AccessorDeclaration)[]) {
+                    if (methodKind === SyntaxKind.MethodDeclaration && getCheckFlags(p) & CheckFlags.Instantiated) {
```
Comment (weswigham) [inline src/compiler/checker.ts:9546]:
```suggestion
                    if (methodKind === SyntaxKind.MethodDeclaration) {
                        p = getTargetSymbol(p);
                    }
```
But I'm not sure this is 100% right in the first place - symbol instantiation is used for much more than getting rid of a `this` type - it's used for copying type parameters (as you can see in the other baseline change), for instantiating the parameter types of signatures, and generally for instantiating object type members.

Probably a better fix would be finding where we lookup the types/symbols to feed into the serializer at the layer that calls this one and make sure we're getting them w/o an instantiated `this` in the first place.

**Review by weswigham — APPROVED** [review]
