### PR TITLE
Handle strict flag when writing tsbuildinfo

### LINKED ISSUE #44305: Incremental builds with .tsbuildinfo-files are not faster than non incremental builds
# Bug Report

TypeScript version 4.3.2

I am unable to see any measurable performance difference using incremental builds using `tsc --noEmit` with or without `"incremental": true` in `compilerOptions` or the `--incremental` CLI argument. Builds take the same amount of time before and after the `tsconfig.tsbuildinfo` is created.

I have tried this in serveral different projects on both Windows and Linux, the results are the same. I also used the performance tracing feature and the flame graphs look pretty much identical with or without the tsbuildinfo file.

One project takes about 14.5 seconds on my machine without incremental build and about 14.5 seconds with incremental.

Another project takes 3.5 seconds on Windows without and 3.5 seconds with. The same project took 3 seconds on Linux without and 3 seconds with.

First flame graph with no tsbuildinfo
image

Second build with tsbuildinfo present
image

### 🔎 Search Terms

incremental
tsbuildinfo
performance

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because limited time

### ⏯ Playground Link

Not possible.

### 💻 Code

N/A

### 🙁 Actual behavior

Incremental builds perform the same as non incremental builds.

### 🙂 Expected behavior

I expect incremental builds to be at least a little bit faster.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #44305

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@DanielRosenwasser we probably need this patch for 4.3 ?

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -853,8 +853,13 @@ namespace ts {
         const { optionsNameMap } = getOptionsNameMap();
 
         for (const name of getOwnKeys(options).sort(compareStringsCaseSensitive)) {
-            const optionInfo = optionsNameMap.get(name.toLowerCase());
-            if (optionInfo?.affectsEmit || optionInfo?.affectsSemanticDiagnostics || name === "skipLibCheck" || name === "skipDefaultLibCheck") {
+            const optionKey = name.toLowerCase();
+            const optionInfo = optionsNameMap.get(optionKey);
+            if (optionInfo?.affectsEmit || optionInfo?.affectsSemanticDiagnostics ||
+                // Since we should never compare strict directly between options but individual flag, but it does change value of that flag so store it
```
Comment (amcasey) [inline src/compiler/builder.ts:859]: Sorry, I don't understand this comment.

Comment (amcasey) [reply src/compiler/builder.ts:859]: I think it might be saying that we actually make decisions based on the collection of flags that make up `strict` and not based on `strict` itself, but then I don't understand why would need to store `strict`, rather than those component flags.

Comment (amcasey) [reply src/compiler/builder.ts:859]: Oh, maybe deserializing `strict` results in the component flags being set appropriately and then the comparison that looks at those flags and not `strict` behaves correctly?  In which case, maybe something like

> We need to store `strict`, even though it won't be examined directly, so that the flags it controls (e.g. `strictNullChecks`) will be retrieved correctly from the buildinfo

**Review by amcasey — APPROVED** [review]
I think I get it, but please see my comment.

File: src/compiler/builder.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/compiler/builder.ts:859]:
```suggestion
                // We need to store `strict`, even though it won't be examined directly, so that the
                // flags it controls (e.g. `strictNullChecks`) will be retrieved correctly from the buildinfo

File: src/compiler/builder.ts [hunk 2]
```diff
@@ -853,8 +853,13 @@ namespace ts {
...
 
         for (const name of getOwnKeys(options).sort(compareStringsCaseSensitive)) {
-            const optionInfo = optionsNameMap.get(name.toLowerCase());
-            if (optionInfo?.affectsEmit || optionInfo?.affectsSemanticDiagnostics || name === "skipLibCheck" || name === "skipDefaultLibCheck") {
+            const optionKey = name.toLowerCase();
+            const optionInfo = optionsNameMap.get(optionKey);
+            if (optionInfo?.affectsEmit || optionInfo?.affectsSemanticDiagnostics ||
+                // Since we should never compare strict directly between options but individual flag, but it does change value of that flag so store it
+                optionKey === "strict" ||
+                // These affect if lib files need to be rechecked so store them
```
Comment (DanielRosenwasser) [inline src/compiler/builder.ts:861]:
```suggestion
                // We need to store these to determine whether `lib` files need to be rechecked.
```

File: src/compiler/commandLineParser.ts [hunk 3]
```diff
@@ -564,6 +564,8 @@ namespace ts {
         {
             name: "strict",
             type: "boolean",
+            // Though this affects semantic diagnostics, affectsSemanticDiagnostics is not set here
+            // The value of each strictFlag depends on own strictFlag value or this and never accessed directly.
```
Comment (DanielRosenwasser) [inline src/compiler/commandLineParser.ts:568]: I kind of wonder whether it's just worth it to say this always has `affectsSemanticDiagnostics` set to `true` since it's unlikely that you'd toggle this but have no difference in effective strict options.

Comment (sheetalkamat) [reply src/compiler/commandLineParser.ts:568]: I think its better that we dont update unnecessarily so prefer to keep it like this. But not stuck on it so open to changing that if you feel strongly about it.

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

File: src/compiler/commandLineParser.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/commandLineParser.ts:568]: What’s the actual consequence of doing it like this? Like if someone had every individual strict flag enabled, and then toggled `strict` itself, we would be able to correctly identify that it had no effect?

**Review by andrewbranch — APPROVED** [review]

File: src/compiler/commandLineParser.ts (hunk 3 above)
Comment (sheetalkamat) [reply src/compiler/commandLineParser.ts:568]: correct.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by sheetalkamat** [comment]
@typescript-bot cherry pick this to release-4.3 branch

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry pick this to release-4.3

**Comment by DavidZidar** [comment]
@sheetalkamat @DanielRosenwasser Looks like you need a dash in "cherry-pick" for the bot to activate

**Comment by sheetalkamat** [comment]
@typescript-bot cherry-pick this to release-4.3
