### PR TITLE
Properly handle multiply-declared optional properties in JSX attr. type

### LINKED ISSUE #6029: tsx file compile fails on optional properties
Once reported here, https://github.com/TypeStrong/ntypescript/issues/17 but it seems that this problem happens on the current typescript trunk version.

`tsconfig.json`:
````
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "jsx": "react"
  },
  "compileOnSave": false,
  "files": [
    "./main.tsx",
    "./typings/tsd.d.ts"
  ]
}
````

`tsd`:
````
tsd install react-global react-bootstrap --save 
````

`main.tsx`:
````
import * as React from 'react';
import { render } from 'react-dom';
import { Button } from 'react-bootstrap';

class App extends React.Component<{}, {}> {
  render() {
    return <Button bsSize="large" bsStyle="danger" > {"Button Text"} </Button>;
  }
}

render(<App />, document.getElementsByTagName("entrypoint")[0] );
````

`typescript 1.8.0-dev.20151210` tsc fails with these error messages
````
main.tsx(8,12): error TS2324: Property 'key' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonProps, any>> & ButtonProps'.
main.tsx(8,12): error TS2324: Property 'ref' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonProps, any>> & ButtonProps'.
````
The error message says that 'key' and 'props' property must be given, but they are defined as optional on IntrinsicAttributes and IntrinsicClassicAttributes like this. 

in `react.d.ts`, line 2119~2125
````
    interface IntrinsicAttributes {
        key?: string | number;
    }

    interface IntrinsicClassAttributes<T> {
        ref?: string | ((classInstance: T) => void);
    }
````
`typescript 1.7.3` compile succeeds without problem.

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #6029 and removes the bogus restriction on non-intersection prop types (#4362)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3766,11 +3766,13 @@ namespace ts {
         function createUnionOrIntersectionProperty(containingType: UnionOrIntersectionType, name: string): Symbol {
             const types = containingType.types;
             let props: Symbol[];
+            let isOptional = !!(containingType.flags & TypeFlags.Intersection);
             for (const current of types) {
                 const type = getApparentType(current);
                 if (type !== unknownType) {
                     const prop = getPropertyOfType(type, name);
                     if (prop && !(getDeclarationFlagsFromSymbol(prop) & (NodeFlags.Private | NodeFlags.Protected))) {
+                        isOptional = isOptional && !!(prop.flags & SymbolFlags.Optional);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: What about

```ts
let propFlags = SymbolFlags.None;
// ...
propFlags &= prop.flags;
```

and then

```ts
const isIntersection = !!(containingType.flags & TypeFlags.Intersection)
const propertyOptionalFlag = isIntersection ?
    propFlags & SymbolFlags.Optional :
    SymbolFlags.None

const result = <TransientSymbol>createSymbol(
                SymbolFlags.Property |
                SymbolFlags.Transient |
                SymbolFlags.SyntheticProperty |
                propertyOptionalFlag,
                name);
```

Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Good plan

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3766,11 +3766,14 @@ namespace ts {
         function createUnionOrIntersectionProperty(containingType: UnionOrIntersectionType, name: string): Symbol {
             const types = containingType.types;
             let props: Symbol[];
+            // Flags we want to propagate to the result if they exist in all source symbols
+            let commonFlags = (containingType.flags & TypeFlags.Intersection) ? SymbolFlags.Optional : SymbolFlags.None;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Much better than mine

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by myitcv** [comment]
Any chance this can be merged if it's good to go? Will mean the nightly builds are then fixed :+1:

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh was out sick today, hopefully this can go in tomorrow night.

**Comment by RyanCavanaugh** [comment]
@myitcv in. Thanks!

**Comment by DanielRosenwasser** [comment]
Awesome - you'll be able to grab it in a few hours.

**Comment by myitcv** [comment]
@RyanCavanaugh @DanielRosenwasser - thanks both.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -8232,9 +8240,9 @@ namespace ts {
                             // Props is of type 'any' or unknown
                             return links.resolvedJsxType = attributesType;
                         }
-                        else if (!(attributesType.flags & TypeFlags.ObjectType)) {
-                            // Props is not an object type
-                            error(node.tagName, Diagnostics.JSX_element_attributes_type_0_must_be_an_object_type, typeToString(attributesType));
+                        else if (attributesType.flags & TypeFlags.Union) {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I don't think this actually prevents it from being a union type though. It could be a type parameter, which is later instantiated to a union type.
