### PR TITLE
Fix type parameter comparability to consistently allow comparisons on unconstrained type parameters

### LINKED ISSUE #48680: Unconstrained type parameter has stricter comparability rules than `extends unknown`
Fine in 4.7 and 4.6

```ts
function foo<T extends unknown>() {
    let x = {};
    x as T;
}
```

Fine in 4.6, **fails** in 4.7

```ts
function foo<T>() {
    let x = {};
    x as T;
}
```

### PR DESCRIPTION
**Pull request by weswigham**
*unless those comparisons to against other unrelated type parameters, since those are a stronger signal that the types are meant to be separate domains.

This is a change in philosophy to the more permissive side in the general case - comparability now consistently succeeds when relating any two types that overlap, unless the two are type parameters that don't extend one another in some way.

Fixes #48680

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot user test this inline
@typescript-bot test this
@typescript-bot run dt
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19549,7 +19563,7 @@ namespace ts {
                 if (sourceFlags & TypeFlags.TypeVariable) {
                     // IndexedAccess comparisons are handled above in the `targetFlags & TypeFlage.IndexedAccess` branch
                     if (!(sourceFlags & TypeFlags.IndexedAccess && targetFlags & TypeFlags.IndexedAccess)) {
-                        const constraint = getConstraintOfType(source as TypeVariable);
+                        const constraint = getConstraintOfType(source as TypeVariable) || unknownType;
```
Comment (weswigham) [inline src/compiler/checker.ts:19566]: This is the core of this fix. This is really all we need to make it so `T extends unknown` and a bare `T` are actually treated identically.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -19338,6 +19338,20 @@ namespace ts {
                             }
                         }
                     }
+                    if (relation === comparableRelation && sourceFlags & TypeFlags.TypeParameter) {
+                        // This is a carve-out in comparability to essentially forbid comparing a type parameter
+                        // with another type parameter unless one extends the other. (Remember: comparability is mostly bidirectional!)
```
Comment (weswigham) [inline src/compiler/checker.ts:19343]: This, meanwhile, is a change to make is _slightly more strict_ in _all_ circumstances involving comparing one type parameter to another (regardless if one or both are constrained) so we still forbid comparing two unrelated type parameters, despite the below change.

File: tests/baselines/reference/intersectionNarrowing.types [hunk 3]
```diff
@@ -59,11 +59,11 @@ function f4<T>(x: T & 1 | T & 2) {
 
         case 1: x; break;  // T & 1
 >1 : 1
->x : T & 1
+>x : (T & 1) | (T & 2)
 
         case 2: x; break;  // T & 2
 >2 : 2
->x : T & 2
+>x : (T & 1) | (T & 2)
```
Comment (weswigham) [inline tests/baselines/reference/intersectionNarrowing.types:66]: Fallout from permissive comparability: We use comparability in switch-case narrowing (in `narrowTypeBySwitchOnDiscriminant`) and since `T` is unconstrained and thus extends `unknown`, both the `1` and `2` intersections are considered comparable with both `1` and `2` because of the `T` part. Some extra work could possibly be done to prevent this by changing how comparability works over intersections, probably.

Comment (weswigham) [reply tests/baselines/reference/intersectionNarrowing.types:66]: (It's likely a similar change occurs in narrowing assignments, since we also use bidirectional comparability there, and maybe in other places more subtly since we use unidirectional comparability in `narrowTypeByDiscriminant`)

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -19549,7 +19563,7 @@ namespace ts {
                 if (sourceFlags & TypeFlags.TypeVariable) {
                     // IndexedAccess comparisons are handled above in the `targetFlags & TypeFlage.IndexedAccess` branch
                     if (!(sourceFlags & TypeFlags.IndexedAccess && targetFlags & TypeFlags.IndexedAccess)) {
-                        const constraint = getConstraintOfType(source as TypeVariable);
+                        const constraint = getConstraintOfType(source as TypeVariable) || unknownType;
                         if (!strictNullChecks && (!constraint || (sourceFlags & TypeFlags.TypeParameter && constraint.flags & TypeFlags.Any))) {
```
Comment (Andarist) [inline src/compiler/checker.ts:19567]: Since now `constraint` is no longer nullable this can be simplified:
```suggestion
                        if (!strictNullChecks && (sourceFlags & TypeFlags.TypeParameter && constraint.flags & TypeFlags.Any)) {

```

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -19338,6 +19338,20 @@ namespace ts {
                             }
                         }
                     }
+                    if (relation === comparableRelation && sourceFlags & TypeFlags.TypeParameter) {
+                        // This is a carve-out in comparability to essentially forbid comparing a type parameter
+                        // with another type parameter unless one extends the other. (Remember: comparability is mostly bidirectional!)
+                        let constraint = getConstraintOfTypeParameter(source);
+                        if (constraint && hasNonCircularBaseConstraint(source)) {
+                            while (constraint && constraint.flags & TypeFlags.TypeParameter) {
+                                if (result = isRelatedTo(constraint, target, RecursionFlags.Source, /*reportErrors*/ false)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:19347]: How come the elaborations below still report stuff like `Type 'unknown' is not assignable to type 'blahblahblah'.`?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -19558,12 +19572,12 @@ namespace ts {
...
+                        else if (result = isRelatedTo(constraint, target, RecursionFlags.Source, /*reportErrors*/ false, /*headMessage*/ undefined, intersectionState)) {
                             resetErrorInfo(saveErrorInfo);
                             return result;
                         }
                         // slower, fuller, this-instantiated check (necessary when comparing raw `this` types from base classes), see `subclassWithPolymorphicThisIsAssignable.ts` test for example
-                        else if (constraint && (result = isRelatedTo(getTypeWithThisArgument(constraint, source), target, RecursionFlags.Source, reportErrors && !(targetFlags & sourceFlags & TypeFlags.TypeParameter), /*headMessage*/ undefined, intersectionState))) {
+                        else if (result = isRelatedTo(getTypeWithThisArgument(constraint, source), target, RecursionFlags.Source, reportErrors && !(targetFlags & sourceFlags & TypeFlags.TypeParameter), /*headMessage*/ undefined, intersectionState)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:19580]: Maybe avoid elaborating if the constraint is `unknown`

```suggestion
                        else if (result = isRelatedTo(getTypeWithThisArgument(constraint, source), target, RecursionFlags.Source, reportErrors && constraint !== unknownType && !(targetFlags & sourceFlags & TypeFlags.TypeParameter), /*headMessage*/ undefined, intersectionState)) {
```

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts:19567]: Good catch for the wrong reason - this rule's only here for compat in non-strict mode; as such, it probably still needs to check for constraint presence (as inconsistent as that is). Otherwise it should also look for `TypeFlags.Unknown` on the constraint in addition to `Any` (which'd still change the assignability of `T extends unknown` in non-strict mode).

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot user test this inline
@typescript-bot test this
@typescript-bot run dt
@typescript-bot perf test this

**Review by DanielRosenwasser — APPROVED** [review]
Seems reasonable from a glance. I'd get another sign off, and I'd be curious to get Ryan's take on this before 4.7 goes out (though I think the new carve-out was the only thing he and I had ever discussed where the more-restrictive behavior was compelling).

**Comment by DanielRosenwasser** [comment]
@ahejlsberg do you feel comfortable with us bringing this in?

**Review by ahejlsberg — APPROVED** [review]

**Comment by weswigham** [comment]
@DanielRosenwasser do you still want to cherry pick this for 4.7?
