### PR TITLE
Proposal: importModuleSpecifierPreference: project-relative

### LINKED ISSUE #36624: TS importModuleSpecifier could work better for lerna monorepos with libs only
*TS Template added by @mjbvz*

**TypeScript Version**: 3.8.0

**Search Terms**
- importModuleSpecifier
- auto import
- mono repo / monorepo

---

Related issue: https://github.com/microsoft/TypeScript/issues/36181 (I thought was something related to TS itself, but maybe is not).

Right now, the `typescript.preferences.importModuleSpecifier` **auto** option only uses relative paths for files nearer to the actual file than the `basePath` configuration file. But this isn't the best approach for a monorepo full with libs.

I only want to have aliases on imports from other lib folders, but I want to keep every import within a lib as relative imports. The problem is, VSCode suggestions sometimes adds the alias to imports within files of the same lib. When I build and publish everything as is, the service using that lib will crash because doesn't understand the alias.

Thank you in advance!

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #36624 

People often want to use `paths` aliases to refer to “external” code (cross-project/package/some other conceptual boundary), but use relative paths elsewhere. Auto-imports cannot help you do this today.

The problem is that the conceptual boundaries within which people want to use relative imports and across which they want to use `paths` aliases can’t always be inferred. Suppose I have a monorepo structure with a base tsconfig defining `paths` like

```
"paths": {
  "*": "./packages/*"
}
```

Because we are familiar with common monorepo patterns, it’s clear that the package boundaries are the direct subdirectories of `packages`. So within `./packages/foo` I’d use relative imports to import anything in that package, and `"bar"` to import `./packages/bar`. 

However, it’s also common for webpack-bundled apps to have a convenience alias for the project root:

```
"paths": {
  "@/*": "./src/*"
}
```

This is structurally identical, but serves a different purpose—I needn’t treat `./src/utils` and `./src/routes` as separate, siloed directory trees.

My original hope was to be able to split module specifier suggestion behavior based on how `paths` is defined, but I think that is too hand-wavy. Instead, this PR introduces two more conservative heuristics:

1. If the path from an importing file to the imported file goes outside the directory of the importing file’s tsconfig.json (or inferred/unconfigured project root) and a non-relative path is available, use it.
2. If the nearest package.json file to the importing file and the nearest package.json file to the imported file are not the same file, and a non-relative path is available, use it.

For everything else, use a relative path.

This should cover basically all monorepo / project references configurations. I can imagine scenarios where I want to conceptually silo directories within a single project where these heuristics wouldn’t help you, but I haven’t heard user feedback from anyone with a setup like that.

I am proposing renaming `importModuleSpecifierPreference: 'auto'` to `'shortest'` to be more descriptive, leaving it as the default (which means that clients sending `'auto'` will continue to work), and giving this new setting a brief but descriptive name. Right now it’s `'external-non-relative'`, which is terrible.

### CODE REVIEW

**Comment by AlCalzone** [comment]
@andrewbranch should the improved behavior for same-package-imports already be present in 4.1-beta or is this PR required?
Currently, I'm getting this
grafik
instead of auto-importing `./SerialAPICommandMachine` (with `typescript.preferences.importModuleSpecifier: auto`).

**Comment by andrewbranch** [comment]
@AlCalzone that’s probably a case of #40713

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -174,13 +180,34 @@ namespace ts.moduleSpecifiers {
...
-        const nonRelative = fromPaths === undefined ? importRelativeToBaseUrl : fromPaths;
+        const nonRelative = fromPaths === undefined ? importRelativeToBaseUrl : fromPaths.path;
 
         if (relativePreference === RelativePreference.NonRelative) {
             return nonRelative;
         }
 
-        if (relativePreference !== RelativePreference.Auto) Debug.assertNever(relativePreference);
+        if (relativePreference === RelativePreference.ExternalNonRelative) {
+            Debug.assertIsDefined(host.getNearestAncestorDirectoryWithPackageJson);
```
Comment (RyanCavanaugh) [inline src/compiler/moduleSpecifiers.ts:190]: Is this something that's true by construction, or are we checking for a misconfiguration?

File: src/compiler/moduleSpecifiers.ts [hunk 2]
```diff
@@ -174,13 +180,34 @@ namespace ts.moduleSpecifiers {
...
+            const projectDirectory = host.getCurrentDirectory();
+            const modulePath = toPath(moduleFileName, projectDirectory, getCanonicalFileName);
+            const sourceIsInternal = startsWith(sourceDirectory, projectDirectory);
+            const targetIsInternal = startsWith(modulePath, projectDirectory);
+            if (sourceIsInternal && !targetIsInternal || !sourceIsInternal && targetIsInternal) {
+                // 1. The import path crosses the boundary of the tsconfig.json-containing directory.
+                return nonRelative;
+            }
+
```
Comment (RyanCavanaugh) [inline src/compiler/moduleSpecifiers.ts:199]: Some example values in this containing block might be helpful

File: src/compiler/moduleSpecifiers.ts [hunk 3]
```diff
@@ -338,11 +365,11 @@ namespace ts.moduleSpecifiers {
                         endsWith(relativeToBaseUrl, suffix) ||
                         !suffix && relativeToBaseUrl === removeTrailingDirectorySeparator(prefix)) {
                         const matchedStar = relativeToBaseUrl.substr(prefix.length, relativeToBaseUrl.length - suffix.length);
-                        return key.replace("*", matchedStar);
+                        return { key, path: key.replace("*", matchedStar) };
                     }
                 }
                 else if (pattern === relativeToBaseUrl || pattern === relativeToBaseUrlWithIndex) {
-                    return key;
+                    return { key, path: key };
```
Comment (RyanCavanaugh) [inline src/compiler/moduleSpecifiers.ts:372]: Please rename something so that this doesn't happen

Comment (RyanCavanaugh) [reply src/compiler/moduleSpecifiers.ts:372]: "this" being the `{ b, a: b }` form

File: src/server/protocol.ts [hunk 4]
```diff
@@ -3217,7 +3217,7 @@ namespace ts.server.protocol {
          * values, with insertion text to replace preceding `.` tokens with `?.`.
          */
         readonly includeAutomaticOptionalChainCompletions?: boolean;
-        readonly importModuleSpecifierPreference?: "auto" | "relative" | "non-relative";
+        readonly importModuleSpecifierPreference?: "shortest" | "external-non-relative" | "relative" | "non-relative";
```
Comment (RyanCavanaugh) [inline src/server/protocol.ts:3220]: Kind of nervous that `auto` is going away; can you explain?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
Let's bikeshed this name somewhere

File: src/compiler/moduleSpecifiers.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts]: It was necessarily true when TS Server used it, and would never take this branch when the checker/emitter used it, but the assertion could have been violated by an API consumer, so I removed it and provided a fallback.

File: src/compiler/moduleSpecifiers.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/moduleSpecifiers.ts]: This was unneeded after all, reverted the change

File: src/server/protocol.ts (hunk 4 above)
Comment (andrewbranch) [reply src/server/protocol.ts:3220]: I’ve renamed `auto` to `shortest` to be more descriptive. Previously, `auto` was an acceptable name because it would pick between the other options (relative and non-relative) based on some heuristic (number of path separators). Now, there are _two_ options that pick between relative and non-relative based on some heuristic. `auto` becomes a bad name because it no longer encompasses _all_ of the other options, it’s no more or less automatic than the new mode, and its name conveys nothing about the heuristic it uses. Values of `"auto"` will still map to `"shortest"`, by merit of it being the default.

Comment (RyanCavanaugh) [reply src/server/protocol.ts:3220]: 💯

**Comment by andrewbranch** [comment]
Renamed to “project-relative.” How do we feel about this going into 4.1?

**Comment by andrewbranch** [comment]
Since this hasn’t gotten much attention and we’re now quite close to the RC, I think I’d prefer to wait for 4.2 for this. To get user feedback on it, I might see if there’s any interest in running a VS Code Insiders experiment setting `project-relative` as the default.

**Comment by AlCalzone** [comment]
How can one participate in that experiment?

**Comment by andrewbranch** [comment]
@typescript-bot pack this

You can try it out now by installing the tarball that @typescript-bot will post shortly, and adding to `.vscode/settings.json`:

```json
{
  "typescript.tsserver.importModuleSpecifierPreference": "project-relative"
}
```

After this is properly merged, I’ll add a corresponding option to VS Code’s preferences UI.

**Comment by AlCalzone** [comment]
@andrewbranch Do I need to configure project references or the project-specific `tsconfig.json` in some specific way? My first test with `"project-relative"` just yielded an import that is relative to the root `tsconfig`'s `baseUrl` (like it did before).

**Comment by andrewbranch** [comment]
Oops, apparently the TypeScript language support extension in VS Code filters out values it doesn’t recognize. I guess I’ll have to make an update there first.

**Comment by AlCalzone** [comment]
@andrewbranch please let me know when there's something I can test. Not sure how long the process to update the extension takes.

**Comment by andrewbranch** [comment]
@AlCalzone you can use the TypeScript nightly and VS Code Insiders now:

image

**Comment by AlCalzone** [comment]
@andrewbranch I must be missing a puzzle piece...
I've updated the branch I mentioned above, current VSCode insiders, today's TS nightly. The setting in `.vscode/settings.json` is no longer greyed out:
grafik
but the repro above is unchanged:
grafik
Restarted TSServer and VSCode, no dice.

**Comment by andrewbranch** [comment]
Ah, it’s because you have this package symlinked through node_modules... and node_modules dependencies get priority. I didn’t notice that before. I’ll have a separate fix up for that.

**Comment by andrewbranch** [comment]
Wait, this is only allowed to happen because `zwave-js` is in the `dependencies` of the root package.json. I guess you could reasonably argue it’s still a bug for any package to import from itself through node_modules, but the reason I’ve never seen this before is because normally packages cannot look up at a package.json and see themselves listed as a dependency. This is also the first time I’ve noticed that you’re using lerna—lerna tends to work perfectly with project references without `paths` at all, and also without these `file:` dependencies in package.json files. But one thing at a time, what are these dependencies for in the root package.json?

**Comment by AlCalzone** [comment]
> But one thing at a time, what are these dependencies for in the root package.json?

`lerna` adds them when I run `lerna bootstrap`.

> lerna tends to work perfectly with project references without `paths` at all

That would be great news, I've always thought TypeScript needs `paths` to understand the prefixed packages before they are actually being compiled.

**Comment by AlCalzone** [comment]
@andrewbranch FYI I just tried to migrate the project to `npm@7` workspaces. Without the root package dependences, without paths and without baseUrl it works like a charm:
https://github.com/zwave-js/node-zwave-js/tree/workspaces
==> grafik

So I guess if you don't want to support `lerna`'s quirks, this is a documentation issue in the end.

**Comment by andrewbranch** [comment]
Huh, I guess I haven’t been using `lerna link convert`. `lerna bootstrap` already handles symlinking, and I already install common devDependencies in the root. Thanks for the tip... one more monorepo configuration edge case to consider.

**Comment by shrinktofit** [comment]
@andrewbranch How can I prevent import specifier suggestion from suggesting non-entry modules in other "packages(folder)" in same repo?
For example I have:
```
libs
  lib-a/
    index.ts
    internal-a.ts
  lib-b/
    index.ts
    interal-b.ts
```
I hope the specifier suggestion only suggest exports of `lib-a/index.ts` when triggered in `lib-b/*`.

**Comment by andrewbranch** [comment]
Exports available from the package index have the highest priority, but you can’t prevent exports in other files from showing up.
