### PR TITLE
Elide var when emitting a module merged with an ES6 class

### LINKED ISSUE #2458: ES6 clodules need to be renamed
Closely related to #2457 and also in reference to https://github.com/Microsoft/TypeScript/commit/bd4d7fc9eedfb905313b173e284eddf95350e7dc#commitcomment-10328068

A class merging with a module will not work in ES6, because you will end up redeclaring a class and a var (the var is what we emit for the module) in the same scope, which will cause a runtime error. So a class merging with a module needs to be renamed in a similar way as #2457, except as a var instead of a let.

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #2458.

In ES6 it is illegal to redeclare a lexically bound name (such as the name of a `let`, `const`, or `class` declaration). When we merge internal modules with classes, we emit the following for `--target ES6`:

```ts
// a.ts
class C {
}
module C {
  export var x = 1;
}

// a.js
class C {
}
var C; // error: redeclaration of C
(function (C) {
  C.x = 1;
})(C || (C = {}));
```

This change elides the `var` declaration for a module given the following conditions:

* The script target is ES6
* The internal module merges with an existing `class` declaration in the same lexical scope.

As a result, the new output would be:
```ts
class C {
}
(function (C) {
  C.x = 1;
})(C || (C = {}));
```

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -10387,16 +10387,30 @@ module ts {
             }
         }
 
-        function getFirstNonAmbientClassOrFunctionDeclaration(symbol: Symbol): Declaration {
+        function getFirstClassOrFunctionDeclaration(symbol: Symbol, nonAmbientOnly: boolean): Declaration {
             let declarations = symbol.declarations;
             for (let declaration of declarations) {
-                if ((declaration.kind === SyntaxKind.ClassDeclaration || (declaration.kind === SyntaxKind.FunctionDeclaration && nodeIsPresent((<FunctionLikeDeclaration>declaration).body))) && !isInAmbientContext(declaration)) {
+                if ((declaration.kind === SyntaxKind.ClassDeclaration || (declaration.kind === SyntaxKind.FunctionDeclaration && nodeIsPresent((<FunctionLikeDeclaration>declaration).body))) && !(nonAmbientOnly && isInAmbientContext(declaration))) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: This needs to be split up into like 4 more lines

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -10416,15 +10430,22 @@ module ts {
...
+                        if (getSourceFileOfNode(node) !== getSourceFileOfNode(nonAmbientClassOrFunc)) {
                             error(node.name, Diagnostics.A_module_declaration_cannot_be_in_a_different_file_from_a_class_or_function_with_which_it_is_merged);
                         }
-                        else if (node.pos < classOrFunc.pos) {
+                        else if (node.pos < nonAmbientClassOrFunc.pos) {
                             error(node.name, Diagnostics.A_module_declaration_cannot_be_located_prior_to_a_class_or_function_with_which_it_is_merged);
                         }
                     }
+
+                    // if the module merges with a class declaration in the same lexical scope, we need to track this
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: wrap

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -10416,15 +10430,22 @@ module ts {
...
+                    // to ensure the correct emit.
+                    let anyClassOrFunc = getFirstClassOrFunctionDeclaration(symbol, /*nonAmbientOnly*/ false);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I'd rename this to `firstClassOrFunc

File: src/compiler/emitter.ts [hunk 4]
```diff
@@ -4207,6 +4207,10 @@ var __param = this.__param || function(index, decorator) { return function (targ
                 return isInstantiatedModule(node, compilerOptions.preserveConstEnums || compilerOptions.separateCompilation);
             }
 
+            function isModuleMergedWithES6Class(node: ModuleDeclaration) {
+                return languageVersion === ScriptTarget.ES6 && !!(resolver.getNodeCheckFlags(node) & NodeCheckFlags.LexicalModuleMergesWithClass);
```
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts]: If you know that the entity of a certain name exists, do you need the `var` even if you're in ES6?

File: src/compiler/utilities.ts [hunk 5]
```diff
@@ -211,8 +211,9 @@ module ts {
             isCatchClauseVariableDeclaration(declaration);
     }
 
-    export function getEnclosingBlockScopeContainer(node: Node): Node {
-        let current = node;
+    // Gets the nearest enclosing block scope container that has the provided node as a descendant, that is not the provided node.
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: JS Doc, wrap to two lines

File: src/compiler/checker.ts (hunk 1 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: +1, I lose count of the parentheses very quickly

File: src/compiler/checker.ts (hunk 3 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Why can't you just use getDeclarationOfKind for this?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -10387,16 +10387,30 @@ module ts {
...
             for (let declaration of declarations) {
-                if ((declaration.kind === SyntaxKind.ClassDeclaration || (declaration.kind === SyntaxKind.FunctionDeclaration && nodeIsPresent((<FunctionLikeDeclaration>declaration).body))) && !isInAmbientContext(declaration)) {
+                if ((declaration.kind === SyntaxKind.ClassDeclaration || (declaration.kind === SyntaxKind.FunctionDeclaration && nodeIsPresent((<FunctionLikeDeclaration>declaration).body))) && !(nonAmbientOnly && isInAmbientContext(declaration))) {
                     return declaration;
                 }
             }
             return undefined;
         }
 
+        function inSameLexicalScope(node1: Node, node2: Node) {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I don't think this is correct when the containers are internal modules that get merged.
```ts
module container {
    export class clodule { }
}
module container {
    export module clodule { ; }
}
```
These don't have the same block scope container do they? Yet you want to elide the var declaration when you emit the module portion.

File: src/compiler/checker.ts (hunk 3 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Also, why do you need to track this in the checker? Why not do this in the emitter directly? All you need is to examine the declarations associated with a particular symbol. If two declarations do not share the same block scope container they will not be part of the same symbol anyway, right?

File: src/compiler/emitter.ts [hunk 7]
```diff
@@ -4215,15 +4219,19 @@ var __param = this.__param || function(index, decorator) { return function (targ
...
-                emitStart(node);
-                if (isES6ExportedDeclaration(node)) {
-                    write("export ");
+                if (!isModuleMergedWithES6Class(node)) {
+                    emitStart(node);
+                    if (isES6ExportedDeclaration(node)) {
+                        write("export ");
+                    }
+
+                    write("var ");
```
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: Oh interesting. I did not realize that in ES6, you can export a var, and then reassign to it, and it will amend the export binding too.

File: tests/cases/conformance/internalModules/DeclarationMerging/ClassAndModuleWithSameNameAndCommonRootES6.ts [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+    }
+}
+
+// @filename: test.ts
+//var cl: { x: number; y: number; }
+var cl = new X.Y.Point(1,1);
+var cl = X.Y.Point.Origin; // error not expected here same as bug 83996 ?
+
+
+// @filename: simple.ts
```
Comment (JsonFreeman) [inline tests/cases/conformance/internalModules/DeclarationMerging/ClassAndModuleWithSameNameAndCommonRootES6.ts]: Please split this one into a separate test file.

File: src/compiler/checker.ts (hunk 6 above)
Comment (rbuckton) [inline src/compiler/checker.ts]: This should be correct, as the class and module have differing block scopes. I do not want to elide the `var` when I emit the module in your example, otherwise the emit would be:
```js
var container;
(function (container) {
  class clodule { }
  container.clodule = clodule;
})(container || (container = {});

var container;
(function (container) {
  (function (clodule) {
    ;
  })(clodule = container.clodule || (container.clodule = {})); // error: 'clodule' is not defined
})(container || container = {});
```

We need to emit the `var` here, to ensure a local variable for `clodule` is in scope:

```js
var container;
(function (container) {
  class clodule { }
  container.clodule = clodule;
})(container || (container = {});

var container;
(function (container) {
  var clodule; // will not collide with the lexical declaration above.
  (function (clodule) {
    ;
  })(clodule = container.clodule || (container.clodule = {})); 
})(container || container = {});
```

File: src/compiler/checker.ts (hunk 3 above)
Comment (rbuckton) [inline src/compiler/checker.ts]: I didn't want to pollute the emitResolver with methods to support this scenario, a flag seemed sufficient.

Just to clarify, If they are exported, they don't share the same symbol? Then I may not need this check.

File: src/compiler/emitter.ts (hunk 4 above)
Comment (rbuckton) [inline src/compiler/emitter.ts]: I didn't want to introduce a possible complication for ES3/ES5 for a scenario you can only get into for ES6+

File: src/compiler/utilities.ts (hunk 5 above)
Comment (rbuckton) [inline src/compiler/utilities.ts]: While I agree with JSDoc, it doesn't look like we are using it anywhere else in the file.

File: tests/cases/conformance/internalModules/DeclarationMerging/ClassAndModuleWithSameNameAndCommonRootES6.ts (hunk 8 above)
Comment (rbuckton) [inline tests/cases/conformance/internalModules/DeclarationMerging/ClassAndModuleWithSameNameAndCommonRootES6.ts]: This is just a copy of `ClassAndModuleWithSameNameAndCommonRoot.ts` that has its target set for ES6. I can simplify it (remove the cases that should follow the same code path as the ES3 version) but I don't think I'd split it into multiple files.

File: src/compiler/emitter.ts (hunk 7 above)
Comment (rbuckton) [inline src/compiler/emitter.ts]: `var` and `let` declarations are both mutable bindings in the environment record and exported names, `const` declarations are immutable bindings (obviously). Import bindings are immutable as well, but are an indirect binding to the binding in the environment record of the imported module.

* [8.1.1.1.2 - CreateMutableBinding](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-declarative-environment-records-createmutablebinding-n-d)
* [8.1.1.1.3 - CreateImmutableBinding](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-declarative-environment-records-createimmutablebinding-n-s)
* [8.1.1.1.5 - SetMutableBinding](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-declarative-environment-records-setmutablebinding-n-v-s)
* [8.1.1.5 - Module Environment Records](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-module-environment-records)
* [8.1.1.5.5 - CreateImportBinding](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createimportbinding)
* [15.2.3.3 - Static Semantics: ExportedBindings](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports-static-semantics-exportedbindings)

File: src/compiler/emitter.ts (hunk 4 above)
Comment (JsonFreeman) [inline src/compiler/emitter.ts]: I agree with @rbuckton

File: src/compiler/checker.ts (hunk 6 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Oh I see what you mean. I forgot we emit a local for an exported module.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -10390,13 +10390,29 @@ module ts {
...
+                    !isInAmbientContext(declaration)) {
                     return declaration;
                 }
             }
             return undefined;
         }
 
+        function inSameLexicalScope(node1: Node, node2: Node) {
+            let container1 = getEnclosingBlockScopeContainer(node1);
+            let container2 = getEnclosingBlockScopeContainer(node2);
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I wonder if you could just get away with checking the parent

**Comment by JsonFreeman** [comment]
:+1:
