### PR TITLE
Contextual generic function types

### LINKED ISSUE #16293: Incorrect inference for function expression with type annotation and generic
#**TypeScript Version:**  2.3.4

**Code**

```ts
// I can conveniently annotate a function express with a type
// This is good because the types don't litter the implementation

{
    type add = (a: number) => (b: number) => number;
    const add: add = a => b => a + b; // a and b are type number
}

// However, if I try to do the same where the function type has a generic…

{
    type fn = <A>(a: A) => A;
    const fn: fn = a => a; // a is inferred as any, but expected A
}
```

Is there any way to annotate the function expression `fn` with the type `fn` without breaking inference for the parameters?

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we do not erase the type parameters of contextual generic function types. Instead, the type parameters are allowed to propagate into the contextually typed expression. For example:

```ts
const f: <A>(a: A) => A = a => a;  // Type of a is A
```

Previously, contextual generic function types were ignored and `a` would therefore have been of type `any`.

This PR also expands upon #16072 to permit the contextual type of a generic function to itself be a generic function type. For example:

```ts
const arrayMap = <T, U>(f: (x: T) => U) => (a: T[]) => a.map(f);
const arrayFilter = <T>(f: (x: T) => boolean) => (a: T[]) => a.filter(f);

const f1: (a: string[]) => number[] = arrayMap(x => x.length);  // x: string
const f2: <A>(a: A[]) => A[][] = arrayMap(x => [x]);  // x: A
const f3: <A>(a: A[]) => { value: A }[] = arrayMap(value => ({ value }));  // value: A
const f4: (a: string[]) => string[] = arrayFilter(x => x.length > 10);  // x: string
const f5: <T extends { value: number }>(a: T[]) => T[] = arrayFilter(x => x.value > 10);  // x: T
```

Fixes #16293.

### CODE REVIEW

**Comment by aleksey-bykov** [comment]
will miss this shirt https://github.com/Microsoft/TypeScript/issues/13039#issuecomment-268129526

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14981,11 +14981,21 @@ namespace ts {
                     // We clone the contextual mapper to avoid disturbing a resolution in progress for an
                     // outer call expression. Effectively we just want a snapshot of whatever has been
                     // inferred for any outer call expression so far.
-                    const mapper = cloneTypeMapper(getContextualMapper(node));
-                    const instantiatedType = instantiateType(contextualType, mapper);
-                    const returnType = getReturnTypeOfSignature(signature);
-                    // Inferences made from return types have lower priority than all other inferences.
-                    inferTypes(context.inferences, instantiatedType, returnType, InferencePriority.ReturnType);
+                    const instantiatedType = instantiateType(contextualType, cloneTypeMapper(getContextualMapper(node)));
+                    // If the contextual type is a generic pure function type, we instantiate the type with
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: A type that has nothing but a single call signature.
