### PR TITLE
Fix the jsdoc codefix for VariableLike declarations

### LINKED ISSUE #18066: Quick fix for JSDoc types doesn't work on parameters or return types
```ts
function f(x: number?) {
}
```

**Expected**: JSDoc type has a quick fix to correct to `null | undefined | number`.
**Actual**: No quick fix.

### LINKED ISSUE #18068: JSDoc quick fix causes TSServer error
Likely related to any fix to #18066.

```ts
var x = function x(lol: string?) {  
}
```

Put your cursor on `string?` and request a quick fix (`Ctrl`+.``)

```
TypeError: Cannot read property 'getStart' of undefined
    at createAction (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73496:59)
    at Object.getActionsForJSDocTypes [as getCodeActions] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73483:28)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72821:33
    at Object.forEach (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1292:30)
    at Object.getFixes (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72820:16)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76566:35
    at Object.flatMap (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1524:25)
    at Object.getCodeFixesAtPosition (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:76564:23)
    at IOSession.Session.getCodeFixes (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82535:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:81457:61)
    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82679:88
    at IOSession.Session.executeWithRequestId (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82670:28)
    at IOSession.Session.executeCommand (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82679:33)
    at IOSession.Session.onMessage (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:82699:35)
    at Interface.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:83785:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by sandersn**
Provide jsdoc type code fixes for other variable-like declarations. This includes 3 SyntaxKinds I missed earlier: Parameter, PropertyDeclaration and PropertyAssignment.

Fixes #18066 
Fixes #18068

### CODE REVIEW

File: src/services/codefixes/fixJSDocTypes.ts [hunk 1]
```diff
@@ -8,11 +8,16 @@ namespace ts.codefix {
     function getActionsForJSDocTypes(context: CodeFixContext): CodeAction[] | undefined {
         const sourceFile = context.sourceFile;
         const node = getTokenAtPosition(sourceFile, context.span.start, /*includeJsDocComment*/ false);
-        const decl = ts.findAncestor(node, n => n.kind === SyntaxKind.VariableDeclaration);
+        const decl = ts.findAncestor(node,
+                                     n => n.kind === SyntaxKind.VariableDeclaration ||
+                                     n.kind === SyntaxKind.Parameter ||
+                                     n.kind === SyntaxKind.PropertyDeclaration ||
```
Comment (DanielRosenwasser) [inline src/services/codefixes/fixJSDocTypes.ts]: When will you have a `PropertyDeclaration` with a type annotation?

File: src/services/codefixes/fixJSDocTypes.ts [hunk 2]
```diff
@@ -8,11 +8,16 @@ namespace ts.codefix {
     function getActionsForJSDocTypes(context: CodeFixContext): CodeAction[] | undefined {
         const sourceFile = context.sourceFile;
         const node = getTokenAtPosition(sourceFile, context.span.start, /*includeJsDocComment*/ false);
-        const decl = ts.findAncestor(node, n => n.kind === SyntaxKind.VariableDeclaration);
+        const decl = ts.findAncestor(node,
+                                     n => n.kind === SyntaxKind.VariableDeclaration ||
+                                     n.kind === SyntaxKind.Parameter ||
+                                     n.kind === SyntaxKind.PropertyDeclaration ||
+                                     n.kind === SyntaxKind.PropertyAssignment);
```
Comment (DanielRosenwasser) [inline src/services/codefixes/fixJSDocTypes.ts]: When will you have a `PropertyAssignment` with a type annotation?

Comment (sandersn) [reply src/services/codefixes/fixJSDocTypes.ts]: My mistake, I was thinking of PropertySignature
