### PR TITLE
Remove duplicate JSDoc comments

### LINKED ISSUE #35170: Duplicated documentation from common properties in union types
*TS template added by @mjbvz*

**TypeScript Version**: 3.8.0-dev.20191116

**Search Terms**:
- suggest / suggestions
- jsdoc

---

duplicate-description

- VSCode Version: 1.41.0-insider
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Create a typescript union type with descriptions for each type, e.g. 
```typescript
export type DocumentFilter = {
    /** A language id, like `typescript`. */
    language: string;
    /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
    scheme?: string;
    /** A glob pattern, like `*.{ts,js}`. */
    pattern?: string;
} | {
    /** A language id, like `typescript`. */
    language?: string;
    /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
    scheme: string;
    /** A glob pattern, like `*.{ts,js}`. */
    pattern?: string;
} | {
    /** A language id, like `typescript`. */
    language?: string;
    /** A Uri [scheme](#Uri.scheme), like `file` or `untitled`. */
    scheme?: string;
    /** A glob pattern, like `*.{ts,js}`. */
    pattern: string;
};
```

2. When using intellisense, it shows duplicate descriptions

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #35170

### CODE REVIEW

File: src/services/jsDoc.ts [hunk 1]
```diff
@@ -89,17 +89,14 @@ namespace ts.JsDoc {
         // Eg. const a: Array<string> | Array<number>; a.length
```
Comment (minestarks) [inline src/services/jsDoc.ts:89]: Comment on 86 claims it's already deduping? Is the `forEachUnique` meant to do this? Why didn't that work

Comment (DanielRosenwasser) [reply src/services/jsDoc.ts:89]: So I thought the same thing (i.e. "whoever wrote this must be mistaken!) but reading that comment, I understand `forEachUnique` must dedupe across declarations, and something like, say, `(Array<string> | Array<number>)["length"]` has the same declarations between `Array<string>` and `Array<number>` for either of them.

Comment (DanielRosenwasser) [reply src/services/jsDoc.ts:89]: I could *technically* let the "verbatim string" checks handle this instead.
