### PR TITLE
fix(43879): `for ( async of` should be a syntax error

### LINKED ISSUE #43879: `for ( async of` should be a syntax error
# Bug Report

### 🔎 Search Terms

for async of syntax error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/G4QwTgBCDOCeB2BjA3AWAFADMD2kAUMCiE2mEA2gCwBMAugJQQDeAvhotvNNgDYCmAOh7YA5gThJ6yIA)

### 💻 Code

```ts
var async;
for (async of [42]) {}
console.log(async);
```

### 🙁 Actual behavior

no error reported.

### 🙂 Expected behavior

The compiler should throw a syntax error: `Uncaught SyntaxError: The left-hand side of a for-of loop may not be 'async'`.

context: https://github.com/tc39/ecma262/issues/2034

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43879

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -41471,6 +41471,11 @@ namespace ts {
                 }
             }
 
+            if (isForInOrOfStatement(forInOrOfStatement) && isIdentifier(forInOrOfStatement.initializer) && forInOrOfStatement.initializer.escapedText === "async") {
```
Comment (Zzzen) [inline src/compiler/checker.ts:41474]: `for(async in ...)` / `for await ( async of ...)` is legal.

Comment (Zzzen) [reply src/compiler/checker.ts:41474]: Maybe it's better to check it in the parser.

File: tests/cases/conformance/parser/ecmascript6/Iterators/parserForOfStatement22.ts [hunk 2]
```diff
@@ -0,0 +1,4 @@
+// @target: esnext
```
Comment (sandersn) [inline tests/cases/conformance/parser/ecmascript6/Iterators/parserForOfStatement22.ts:1]: we should also have tests for `for (async in ...` and `for await (async of ...` as pointed out by @Zzzen. If those tests already exist, just point them out, no need to duplicate them.

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts:41474]: Given my experience with the parser, and the comments on the similar PR in acornjs, I suspect this is a better place.

**Review by sandersn — CHANGES_REQUESTED** [review]
Request for tests based on @Zzzen 's comments.

File: src/compiler/checker.ts (hunk 1 above)
Comment (Zzzen) [reply src/compiler/checker.ts:41474]: should be checked in parser because `for ((async) of []);` is a valid statement. 
https://github.com/babel/babel/issues/13207

File: src/compiler/diagnosticMessages.json [hunk 3]
```diff
@@ -319,6 +319,10 @@
         "category": "Error",
         "code": 1105
     },
+    "The left-hand side of a for-of statement may not be 'async'.": {
```
Comment (sandersn) [inline src/compiler/diagnosticMessages.json:322]: TIL we actually spell this `'for...of' statement` in other places. I think it should be for-of/for-in, but this PR should be consistent with existing messages, and then we can change the messages all at once if others agree with me.

```suggestion
    "The left-hand side of a 'for...of' statement may not be 'async'.": {
```

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts:41474]: No, it's easier to let the parser accept `async` like any other identifier, and just exclude the single incorrect case in the grammar checks in the checker. The parser would have to decide on a node to return in the error case, and if it *weren't* `Identifier` then the checker and emitter would have to handle that error case.

**Review by sandersn — CHANGES_REQUESTED** [review]
Just one more change -- I noticed that the error message is inconsistent.

**Review by sandersn — APPROVED** [review]
