### PR TITLE
Use control flow to type CommonJS exports

### LINKED ISSUE #40555: Commonjs exports should allow duplicates in some cases
Follow-up to #40513, which surfaced an example of export duplicates that should be allowed:

```js
exports.x = undefined
function x() { }
exports.x = x
```

This pattern is used in the async package's index.js.

**Expected behavior:**
No error; TS' emit uses this pattern too.

**Actual behavior:**
Error: "Cannot redeclare exported variable 'x'."

Currently commonjs exports use excludeFlags of SymbolFlags.None instead of SymbolFlags.Alias as normal aliases do. However, most duplicate alias detection happens in the checker already. All exports should switch to None instead of Alias, and then the above `undefined` exception can be added in one place in the checker.

### PR DESCRIPTION
**Pull request by sandersn**
This allows us to read our own output, plus the times when people manually write exactly the same pattern. It may also allow other patterns in the wild, although I need to look at the user test output to find out if that's the case.

## Implementation notes ##

1. Control flow works with any number of assignments, even though the common case is one assignment from undefined and another from the actual value.
2. I add a `endFlowNode` property to source files in order to run control flow on the statements of a source file. Then I use this node to get the control flow type of an export from outside the file, when it's imported.

Fixes #40555

### CODE REVIEW

**Comment by weswigham** [comment]
> I couldn't think of a simple way remove undefined from the type

Feels like something we could use CFA for, like how we track initializers for class properties through a constructor body.

**Comment by sandersn** [comment]
The problem with control flow is that it doesn't normally persist across aliases. It doesn't actually matter what the type of `exports.x` is inside the defining file -- it only matters when you `const { x } = require('./test')`. I wonder if there's a way for the import alias to provide a different type than the export alias in this case.

**Comment by weswigham** [comment]
I mean, analogously, the externally visible type of a constructor property is the one determined by CFA at the _end_ of the conctructor, yeah? Not the union of the constructor-assigned types.

**Comment by weswigham** [comment]
> To use control flow, maybe I could create a structure to query and capture the type at the bottom of the file.

Yeah; if we don't already have a CFA node at the end of the file (I think we should, though), you'd need to add one like we did for constructor properties.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -26429,7 +26448,10 @@ namespace ts {
             // accessor, or optional method.
             const assignmentKind = getAssignmentTargetKind(node);
             if (assignmentKind === AssignmentKind.Definite ||
-                prop && !(prop.flags & (SymbolFlags.Variable | SymbolFlags.Property | SymbolFlags.Accessor)) && !(prop.flags & SymbolFlags.Method && propType.flags & TypeFlags.Union)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:26432]: Only change here is to exempt `isDuplicatedCommonJSExport` so that it falls through to the autoType case below

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -8359,7 +8374,10 @@ namespace ts {
         }
 
         function getFlowTypeOfProperty(reference: Node, prop: Symbol | undefined) {
-            const initialType = prop && (!isAutoTypedProperty(prop) || getEffectiveModifierFlags(prop.valueDeclaration) & ModifierFlags.Ambient) && getTypeOfPropertyInBaseClass(prop) || undefinedType;
```
Comment (sandersn) [inline src/compiler/checker.ts:8362]: No changes here, I just couldn't read it otherwise

**Comment by sandersn** [comment]
This is a much bigger change, so

1. It needs more tests.
2. It needs performance testing.
3. I need to see if I can stop re-doing `resolveAlias` work in `getTypeOfAlias`.

File: tests/baselines/reference/moduleExportDuplicateAlias.errors.txt [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+==== tests/cases/conformance/salsa/test.js (0 errors) ====
+    const { apply } = require('./moduleExportAliasDuplicateAlias')
+    apply()
+    
+==== tests/cases/conformance/salsa/moduleExportAliasDuplicateAlias.js (1 errors) ====
+    exports.apply = undefined;
+    function a() { }
+    exports.apply()
+    ~~~~~~~~~~~~~
+!!! error TS2722: Cannot invoke an object which is possibly 'undefined'.
```
Comment (weswigham) [inline tests/baselines/reference/moduleExportDuplicateAlias.errors.txt:13]: Oh that's nice. 👍

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
@typescript-bot perf test this
@typescript-bot user test this

**Comment by sandersn** [comment]
Perf run: There's a lot of variance in the node 14 results, but it's both positive and negative. I don't think there's any real impact here.
User tests:

- async uses the undefined`>>`assignment pattern and removes 205 errors, one for each export
- debug uses feature detection and conditional assignment of an export in one place. It doesn't change the type, so technically just the "drop errors" part of this PR is needed.
- npm: *nervous laugh* mutation of exports to indicate initialisation! `npm` is best code base~~~

**Review by weswigham — APPROVED** [review]
