### PR TITLE
fix(35944): Debug failure for spell checking of non-existent private named property access

### LINKED ISSUE #35944: Debug failure for spell checking of non-existent private named property access
**TypeScript Version:**  3.8.0-dev.20191231

**Search Terms:**

**Code**

```ts
let obj = { prop: 1 };
obj.#prop;
```

**Expected behavior:**

- Hover over `#prop`
- Error message suggests using `prop`
- QuickFix is available to fix spelling

**Actual behavior:**

- Hover over `#prop`
- Error message suggests using `prop`
- No QuickFix available, instead there is this error
```
Error: Debug Failure. False expression: Expected an identifier for spelling (property access)
    at r (tsWorker.js:21)
    at Object.getCodeActions (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.n.getFixes (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.getCodeFixesAtPosition (tsWorker.js:21)
    at e.getCodeFixesAtPosition (tsWorker.js:21)
    at t.fmr (workerMain.js:155)
    at errors.ts:22
```

**Playground Link:** https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191231&ssl=2&ssc=11&pln=1&pc=1#code/DYUwLgBA9gRgVhAvBA3hADgJyugXBARggF8BuAKFjgDoBiLHUoA

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #35944

### CODE REVIEW

File: src/services/codefixes/fixSpelling.ts [hunk 1]
```diff
@@ -36,12 +36,13 @@ namespace ts.codefix {
 
         let suggestion: string | undefined;
         if (isPropertyAccessExpression(node.parent) && node.parent.name === node) {
-            Debug.assert(node.kind === SyntaxKind.Identifier, "Expected an identifier for spelling (property access)");
+            Debug.assert(isIdentifierOrPrivateIdentifier(node), "Expected an identifier for spelling (property access)");
```
Comment (ajafff) [inline src/services/codefixes/fixSpelling.ts]: If you use `Debug.assertNode`, you don't need the type assertion below.
