### PR TITLE
fix(39440): No auto implementation refactorings for abstract class with method with explicit this parameter

### LINKED ISSUE #39440: No auto implementation refactorings for abstract class with method with explicit this parameter.
**TypeScript Version:**  4.0.0-dev.20200706

**Search Terms:** refactoring, abstract class, this, suggestions, intellisense, 

**Code**
```ts
abstract class Thing {
  abstract run(): void;
}

class ThingImpl extends Thing {
}

abstract class ThingWithThis {
  abstract run(this: ThingWithThis): void;
}

class ThingWithThisImpl extends ThingWithThis {
}
```

**Expected behavior:**
Refactorings to auto implement ThingWithThisImpl as such:
```ts
abstract class Thing {
  abstract run(): void;
}

class ThingImpl extends Thing {
  run(): void {
    throw new Error("Method not implemented.");
  }
}

abstract class ThingWithThis {
  abstract run(this: ThingWithThis): void;
}

class ThingWithThisImpl extends ThingWithThis {
  run(this: ThingWithThis): void {
    throw new Error("Method not implemented.");
  }
}
```

**Actual behavior:**
Implementing the abstract class is not suggested for ThingWithThis.

image
image

Github doesn't support mp4s, so attached is a zip containing an mp4 of the problem if necessary.
[problem.zip](https://github.com/microsoft/TypeScript/files/4879016/problem.zip)

**Playground Link:** [Playground Link]([Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200703#code/IYIwzgLgTsDGEAJYBthjAgKgCwJYDsBzBAbwCgEFRIZ4EoBXfACgEoAuBANwHtcATANxkAvmTIo0GHAUIBJALYAHZAgCmADwhr8-aXiKlR46tDiJJ6LAcIB1XBGwyM5SqdqJGLR7jCcZRPaOzhzcfELGEqhWAXYOTnhgiirqWjp61rJBCb5GIkA))

**Related Issues:** N/A?

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39440

### CODE REVIEW

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -204,8 +203,9 @@ namespace ts.codefix {
                     typeParameters = setTextRange(factory.createNodeArray(newTypeParameters, typeParameters.hasTrailingComma), typeParameters);
                 }
             }
+            const signatureParameters = signature.thisParameter ? [signature.thisParameter, ...signature.parameters] : signature.parameters;
             const newParameters = sameMap(parameters, (parameterDecl, i) => {
-                const parameter = signature.parameters[i];
+                const parameter = signatureParameters[i];
                 const importableReference = tryGetAutoImportableReferenceFromImportTypeNode(parameterDecl.type, checker.getTypeAtLocation(parameter.valueDeclaration), scriptTarget);
```
Comment (a-tarasyuk) [inline src/services/codefixes/helpers.ts:209]: The root issue was `checker.getTypeAtLocation(parameter.valueDeclaration)` to access `valueDeclaration` from parameter in order to get a type. In the master, this logic was removed
https://github.com/microsoft/TypeScript/blob/8c6b85835f648af3af55261804486d85ece6c8ee/src/services/codefixes/helpers.ts#L206-L207
 so the latest changes should resolve #39440, I can close this PR, or you can merge the updated test for this QF. @DanielRosenwasser what do you think?
