### PR TITLE
Fix alias of module.exports->exports->IIFE

### LINKED ISSUE #27365: Error: Debug Failure. False expression. at mergeSymbol
**TypeScript Version:**  3.1.0-dev.20180925

```
git clone --depth=1 https://github.com/marijnh/Eloquent-JavaScript
cd Eloquent-JavaScript
tsc --init
tsc --allowJs --checkJs
```

Compiler crashes with the callstack:

```
Error: Debug Failure. False expression.
    at mergeSymbol (node_modules\typescript\lib\tsc.js:25294:26)
    at node_modules\typescript\lib\tsc.js:26450:69
    at Map.forEach (<anonymous>)
    at getCommonJsExportEquals (node_modules\typescript\lib\tsc.js:26447:34)
    at resolveExternalModuleSymbol (node_modules\typescript\lib\tsc.js:26436:52)
    at getTypeOfFuncClassEnumModuleWorker (node_modules\typescript\lib\tsc.js:28922:38)
    at getTypeOfFuncClassEnumModule (node_modules\typescript\lib\tsc.js:28908:51)
    at getTypeOfSymbol (node_modules\typescript\lib\tsc.js:28993:24)
    at checkIdentifier (node_modules\typescript\lib\tsc.js:37340:49)
    at checkExpressionWorker (node_modules\typescript\lib\tsc.js:42358:28)
```

### PR DESCRIPTION
**Pull request by sandersn**
In JS, when you assign `module.exports = exports` and the entire module is
wrapped in an IIFE, the resulting `export=` symbol, after following
aliases, is the module itself. This results in trying to merge the
file's exports with itself inside `getCommonJsExportEquals`, since it
thinks that it has found new exports, possibly in an object literal,
that need to be merged with the file's exports.

For example:

```js
(function() {
exports.a = 1
module.exports = exports
})()
```

Fixes #27365

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2353,11 +2353,16 @@ namespace ts {
         function resolveExternalModuleSymbol(moduleSymbol: Symbol, dontResolveAlias?: boolean): Symbol;
         function resolveExternalModuleSymbol(moduleSymbol: Symbol | undefined, dontResolveAlias?: boolean): Symbol | undefined;
         function resolveExternalModuleSymbol(moduleSymbol: Symbol, dontResolveAlias?: boolean): Symbol {
-            return moduleSymbol && getMergedSymbol(getCommonJsExportEquals(resolveSymbol(moduleSymbol.exports!.get(InternalSymbolName.ExportEquals), dontResolveAlias), moduleSymbol)) || moduleSymbol;
+            if (moduleSymbol) {
+                const exportEquals = resolveSymbol(moduleSymbol.exports!.get(InternalSymbolName.ExportEquals), dontResolveAlias);
+                const exported = getCommonJsExportEquals(exportEquals, moduleSymbol);
+                return getMergedSymbol(exported) || moduleSymbol;
```
Comment (sandersn) [inline src/compiler/checker.ts]: This just makes it easier to read -- I found the previous found obtuse and too nested.
