### PR TITLE
Fix find all references of inherited constructor

### LINKED ISSUE #30216: Find all references does not find inherited constructor references
Calling find all references on a constructor will not return references to the constructor for classes that inherit it.

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Code**

```ts
class Foo {
    constructor() { }
}
class Bar extends Foo { }
var bar = new Bar();
var foo = new Foo();
```

**Expected behavior:**
Calling find all references on `Foo`'s constructor should return a reference to `Bar` in `new Bar()`.
**Actual behavior:**
A reference to `Bar` in `new Bar()` is not returned.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #30216

### CODE REVIEW

File: tests/cases/fourslash/findAllRefsOfConstructor.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+////const c = new C();
+////const d = new [|D|]("d");
+////const e = new E();
+
+verify.noErrors();
+const [aCtr, cSuper, aNew, bNew, dNew] = test.ranges();
+verify.referenceGroups(aCtr, [
+    { definition: "class A", ranges: [aCtr, aNew] },
+    { definition: "class B", ranges: [cSuper, bNew]},
+    { definition: "class D", ranges: [dNew]}]);
```
Comment (sheetalkamat) [inline tests/cases/fourslash/findAllRefsOfConstructor.ts]: Can you please add tests for finding constructors for all other classes as well. Also tests for constructor invocation locations as well

File: tests/cases/fourslash/findAllRefsOfConstructor.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+////    }
+////}
+////class D extends B { }
+////class E implements A { }
+////const a = new [|A|]("a");
+////const b = new [|B|]("b");
+////const c = new C();
+////const d = new [|D|]("d");
+////const e = new E();
+
```
Comment (sheetalkamat) [inline tests/cases/fourslash/findAllRefsOfConstructor.ts]: Need another test where class C and D extend for B which has constructor declaration

File: src/services/findAllReferences.ts [hunk 3]
```diff
@@ -1366,6 +1382,17 @@ namespace ts.FindAllReferences.Core {
         }
     }
 
+    function hasOwnConstructor(classDeclaration: ClassLikeDeclaration): boolean {
+        return !!getClassConstructorSymbol(classDeclaration.symbol);
+    }
+
+    function findInheritedConstructorReferences(classDeclaration: ClassLikeDeclaration, state: State): void {
+        if (hasOwnConstructor(classDeclaration)) return undefined;
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts]: Don't you need to look if this class is extending another class and look for its constructor even though this doesn't have constructor?

Comment (gabritto) [reply src/services/findAllReferences.ts]: Yes. The reasoning is that this function will only be called when we are looking for a class' (`A`) constructor and we find a reference that is like `class B extends A`. So I think it is enough to check if `B` doesn't have is own constructor declared.

File: tests/cases/fourslash/findAllRefsOfConstructor.ts (hunk 1 above)
Comment (gabritto) [reply tests/cases/fourslash/findAllRefsOfConstructor.ts]: I tried to do this but find all references only understands that we are looking for a constructor reference if we call it on a constructor declaration. So if we call find all references on a constructor invocation like `new B()`, it will return references to the class `B`. I'm not sure if this is the expected behavior and don't know how to write those tests. Should I open an issue about this? @sandersn @sheetalkamat

Comment (sandersn) [reply tests/cases/fourslash/findAllRefsOfConstructor.ts]: You might as well open an issue, although this seems like something that might have an existing issue.
