### PR TITLE
Fix crash when serializing the return type of a generic call to Array.prototype.flat

### LINKED ISSUE #38298: RangeError when trying to infer type for Array.prototype.flat()
**TypeScript Version:**  3.9.1-rc, 4.0.0-dev.20200430

**Search Terms:** Array flat RangeError Maximum call stack size exceeded

**Code**
```ts
class Foo <T> {
  arr: T[] = [];
    
  bar (
    depth = 1,
  ) {
    return this.arr.flat(depth);
  }
}
```

**Expected behavior:**
Code compiles without errors.

**Actual behavior:**
TSC crashes with `RangeError: Maximum call stack size exceeded`. Edit: Only happens when either `--watch` or `--declaration` flag is set.

**Playground Link:** Couldn't figure out how to add newer libs for Array, and not super useful anyway, as the compiler crashes

**Related Issues:** 
https://github.com/microsoft/TypeScript/pull/32131 seems to be the breaking PR
https://github.com/microsoft/TypeScript/issues/36554 seems related maybe

edit: simplified code example

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #38298

This fix is two-pronged:

* First, node serialization now has a guard during conditional type serialization that issues an error if it attempts to serialize a union within itself (and therefore will repeat endlessly).
* Second, to reduce the likelihood of such a scenario occurring in the first place, we now preserve alias symbols on generic indexed accesses, and on the resulting unions or intersections instantiating those indexed accesses may produce. This creates a number of improvements to our `.types` and error message baselines where many complex types got reduced to `SomeAlias<T>` or the like. That should be an improvement for many situations outside of the crashing one.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot perf test this

**Comment by weswigham** [comment]
RWC and user all look good. Perf is fine. DT needs some text changes to `webpack-config-utils`, but otherwise is unaffected. Everything looks good. @RyanCavanaugh since this was a crash bug, did we want to backport this for the next servicing release?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4415,6 +4415,21 @@ namespace ts {
 
                 return Debug.fail("Should be unreachable.");
 
+
+                function typeToTypeNodeOrCircularityEllision(type: Type) {
+                    if (type.flags & TypeFlags.Union) {
+                        if (context.visitedTypes && context.visitedTypes.has("" + getTypeId(type))) {
+                            if (!(context.flags & NodeBuilderFlags.AllowAnonymousIdentifier)) {
+                                context.encounteredError = true;
+                                context.tracker?.reportCyclicStructureError?.();
```
Comment (andrewbranch) [inline src/compiler/checker.ts:4424]: Since you fixed the failure case separately, can you think of a way to trigger this? Having a test would be nice.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4415,6 +4415,21 @@ namespace ts {
 
                 return Debug.fail("Should be unreachable.");
 
+
+                function typeToTypeNodeOrCircularityEllision(type: Type) {
+                    if (type.flags & TypeFlags.Union) {
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:4420]: Unions can't normally be circularly created - excepting when they appear as the result of a conditional, and that conditional self references as a result of an indexed access on an object (the conditional will defer the evaluation). The union in question here ends up being the result of the indexing operation. We can't do all types because anonymous objects already do a very specialized form of circular reference checking using this cache, so including them would end up checking/inserting the cache twice and cause bogus `any` printbacks. Unions, however, do not use this cache anywhere yet~

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:4424]: I'd have to create an instance where the type doesn't adopt an alias symbol.... Maybe doable by enclosing the indexed access in a union? I'll see if I can add a test.

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this to release-3.9
