### PR TITLE
Exclude mapped types with optionality modifiers and 'as' clauses from constraint logic

### LINKED ISSUE #48157: Possible regression in typechecker for Required type
# Bug Report

Since upgrade to 4.6 from 4.4 I have an error with Required type
full repro here
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIBGcUA-AFzIDOYUoA5rgL664wCuICYw6IyGJgA8AFWQQAHpBAATasgDWEAJ7oYaTAD4AFAAco6PVVEAaQVQBKEAI4dgUCLOEZ0WgJQ58hElB0wAbQMjAF13AG4WNk5uXn5iUh0wKlp6EAZPPEJkBH5qdAAbCAA6AvQGJIiWIA

The error was not happening on 4.4 and seems like also not in 4.5.
I didn't really see something obvious in release notes on what would cause this change.

### 🔎 Search Terms

Went through issues in ts repo to see if there was something already open

### 🕗 Version & Regression Information

4.6

Please keep and fill in the line that best applies:
-->
- This is a crash
- This changed between versions __4.4____ and __4.6_____

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIBGcUA-AFzIDOYUoA5rgL664wCuICYw6IyGJgA8AFWQQAHpBAATasgDWEAJ7oYaTAD4AFAAco6PVVEAaQVQBKEAI4dgUCLOEZ0WgJQ58hElB0wAbQMjAF13AG4WNk5uXn5iUh0wKlp6EAZPPEJkBH5qdAAbCAA6AvQGJIiWIA)

### 💻 Code

```ts
interface Foo {
    bar?: string
}

function foo<T extends keyof Foo>(prop: T, f: Required<Foo>) {
    bar(f[prop]);
}

function bar(t: string) {
    console.log(t);
}
```

### 🙁 Actual behavior

It complains that `f[prop]` can be undefined, but it is wrapped in `Required` which should have all keys from `Foo` as non optional

### 🙂 Expected behavior

Well, I guess it should not complain about undefined, if I properly understand the meaning of the `Required` generic

### LINKED ISSUE #48246: Cannot use mapped types to create new mapped types
# Bug Report
Cannot use mapped types to create new mapped types. I have no idea why this would happen because the types are computed correctly.

### 🔎 Search Terms
- mapped types

### 🕗 Version & Regression Information
This changed between version 4.5.5 and 4.6.2.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7&ts=4.6.2#code/GYVwdgxgLglg9mABAWwIYGsCmBhOyAOANplJgDJxzoj4Cyq++MYA5gDwAqimAHqWABMAzogBKmVAISEAngEEATgtQy2qMDIB8AGkRyoUBdz6ZBIrDLjBEHANpgQyAEaYFAXU0AKALAAoRAGIcPhCAFw22n6BiKgGCuH6hpG+AJThAN5+AJC2AJKkyIjMNvaOLu6oIvmYyLaJ7m7h1cgA3H4AvoiZ-oEKJCAKSADyTgBWmNAAdMAKeACiYIYwmEI+PdEBwUKTaPiewYgAvJqItsG2sYZuusFuMSIQCEJQKcnRKW2+7X5+j2DPejIZAA+gAhOSiADKR1O2XSiDAqGQmHCAHJUKj2sksulEci0U5Mck7pVEH9np9yVBEODRMCyEMhgBpACqAAUYWgsLgCMRSBQqDR6IxmCxPHIgWCIZDdKi8ZhUSk-FAZPhMDTUAoBdR8DCVWqrDSIfTGay2Z9lar1aDUAAvGHw2xMopICyGm1ayg6xoaz2C-BOty2OVIhVuFqIdotIA)

### 💻 Code

```ts
function makeCompleteLookupMapping<T extends ReadonlyArray<any>, Attr extends keyof T[number]>(
    ops: T,
    attr: Attr,
): {
	[Item in T[number]as Item[Attr]]: Item;
} {
    return Object.fromEntries(
        ops.map(op => [op[attr], op] as const),
    );
}

const ALL_BARS = [
	{ name: 'a'},
	{name: 'b'},
] as const;
const BAR_LOOKUP = makeCompleteLookupMapping(ALL_BARS, 'name')
type BarLookup = typeof BAR_LOOKUP;

type Baz = { [K in keyof BarLookup]: BarLookup[K]['name']; };
```

### 🙁 Actual behavior
I cannot use `name` to index `BarLookup[K]` where `K` is a keyof `BarLookup`.
### 🙂 Expected behavior
I expect type `Baz` to be `{a: 'a', b:'b'}`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #48157.
Fixes #48246.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12219,8 +12219,11 @@ namespace ts {
         }
 
         function isMappedTypeGenericIndexedAccess(type: Type) {
-            return type.flags & TypeFlags.IndexedAccess && getObjectFlags((type as IndexedAccessType).objectType) & ObjectFlags.Mapped &&
-                !isGenericMappedType((type as IndexedAccessType).objectType) && isGenericIndexType((type as IndexedAccessType).indexType);
+            let objectType;
+            return !!(type.flags & TypeFlags.IndexedAccess && getObjectFlags(objectType = (type as IndexedAccessType).objectType) & ObjectFlags.Mapped &&
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:12223]: Seems like this would be improved by De Morgan's law
