### PR TITLE
Enforce a size limit in getSpreadType

### LINKED ISSUE #40754: Repeated conditional spreading of object literals results in OOM
**TypeScript Version:**  nightly (fc03982b73ebaabfdfd2ef25bc1538e86a635b7b)

**Search Terms:** spread, union, oom

**Playground Link:** [link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF0S4AueASuEjMADwoCuAtgEYgwA08tSSEIUKAfANwCwAKCEAzSijAYAlqngiAFAEoA3kPjr4Aek3wAKgE8ADgilp4UeOJkp4SEfABMAPXkoAtAEZF8aiDoM0ZgB3AAsGBBtTeAww+Cp-GFt7NEM4KGBbWgArcAw0NQ04DEoYG1VBDUqtHQB1KRikSiwYqNQQZnrEdmhDNBAzDCR4ZQBfeAB+Aqr4ADo5+TAcAG0PAF14ADINqemNReAlh3Wt4Z3d+FSkQwAGfGvGM40RxQfhCt3teDqY2xQES8M8E4YBCHSwyAgPT6AyGFjQUhQAHMOJkcpJ4PIAMQAZgALAAOACs2PGike6jmMwWy2xxw2p3e53UAOxUHwHleTI0LNo7M5u2e-OmlOpB1xdIZXOZMCuuLZ8A55KqANxvIVQqqgqVIv2S0JEvKUouMsMhPlisZTIBhLVFvOWstlR1ywAbAalZUAS7zRrzl7bb6ni9tfNdQB2d2O3YAsM+j3ck1hgNKh3nZ0HfGRo0A-FxqPTHPJ-PwVO7dNLACcWalAIreezJorRftweL5Y812rXIBHfrNZNHebAtbadDyw8a029MN-auE773YHHiH01LwrHBw8Rynktnhi3C6tA4cK81I7LG5WtJ3M8Xc9ZfPj0vvp8qa6q7fFN6fxrncsfxaegOqoAS2gYUpeHj6t+gEJnOZqgXuUGvkG4GzJBbowQ2c7eohd77i6KHqO+TqQRGWFIbGeFHnOSbUW+57rlSuoeJmFH4axh5+gO+JESWjEfpBVbsTR+51vR0YDk2EnEQJpHMcsDidiJ3FXEpXGSWp1x8SRGifOWDiTicyjVPAABiUgwJg8AAPI2QAsswEBIGAUCQvoSqfEBakeBp6heXBhiGXxny6f5OgGduxmeTo3lBQ4fmmXFDgnjJplhaZBnXtFxYBc+QUPuqMXKiaDjYiFOgZfpl4OF+OXnHlv5Bf+RW5bFgW1RV-FodVCkHA40H1R87X5QNiWNQCA1dVVEU1ZhQ3TBNpW4a1DUjU1DiEWloVyXps19Yc5ELVUS1qVRq3DSVZ3Tbt4XoQdDhscdlSnUFubbetk28R93XFQZwnPXtV1BeJF2LZ9pXSWDJ2VbdmWXtiymA3dcWI+NENXIjN09ftopLNiRnTsVqO+T9JPY39CNRUTbXA9iCVk4F9MU7T5bYtlNNrXThV2pdqPlT9M33XjeJdjDdMtbz4MSyzXNs4NnN80zCHQy9GOGNiNqC3DvUi-NivS6jK1S+LRuy5dbNHQbptM+dJtq3TdGq0DQts091sO6j73OyjTPfT76U67jurYgDHtA6joP2xHTNQ9Hd0OsVADCYRgAA1giiLwJgUD6GYIKcIC4jSBA0RhHAADkZgWH8mAgBkSDZLkydINZUCGMYsAwvAiIykE8AQAinAwBA+jwEE9QhGXEQ0PQiR2NP1DFQAogAHhgMAWKAhg-OkwD563GDMLQTTmB3sAgCgGCjwP-QDCEXAD0PsCjyGB0dkj4cFgOK23kaTUeG9B4dkP4RhoTioAviDsewujAPgP+XMIGwOAQHB2YCUwCRGAIQQIwgA)

**Related Issues:** #34853 addressed a related issue

An internal partner team is using this to conditionally override CSS properties (e.g. `...sizeLimited && { width: 100, height: 100 }` and is seeing OOM crashes in tsc and poor editor responsiveness.

### PR DESCRIPTION
**Pull request by amcasey**
When a union is spread into a union, the sizes are multiplied,
potentially resulting in an enormous union (especially if there are
repeated spreads).  This check detects cases that used to run out of
memory.

Fixes #40754

### CODE REVIEW

**Comment by amcasey** [comment]
@typescript-bot user test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14544,6 +14544,17 @@ namespace ts {
                 getIndexInfoWithReadonly(numberIndexInfo, readonly));
             spread.objectFlags |= ObjectFlags.ObjectLiteral | ObjectFlags.ContainsObjectOrArrayLiteral | ObjectFlags.ContainsSpread | objectFlags;
             return spread;
+
+            function errorTypeIfTooLarge(): Type | undefined {
+                if (left.flags & right.flags & TypeFlags.Union) {
+                    const resultSize = (left as UnionType).types.length * (right as UnionType).types.length;
+                    if (resultSize > 100000) {
+                        tracing.instant(tracing.Phase.Check, "getSpreadType_DepthLimit", { leftId: left.id, rightId: right.id });
+                        error(currentNode, Diagnostics.Spread_expression_produces_a_union_type_that_is_too_complex_to_represent);
```
Comment (weswigham) [inline src/compiler/checker.ts:14553]: I think this error is going to be frustrating to encounter with it also providing a suggestion for a workaround. What is the general-form workaround? Casting something somewhere to `any`?

**Review by weswigham — APPROVED** [review]
This code is definitely fine, and, even if we broaden #34853 to fix the reported issue without an error (which I think we should consider), we'll still fundamentally need this as a fallback.

File: src/compiler/checker.ts (hunk 1 above)
Comment (amcasey) [reply src/compiler/checker.ts:14553]: I don't think there's a fix I'm sufficiently confident in to make it a quick fix.  I gave this a new error number so that it would be easier to document/google.

Comment (amcasey) [reply src/compiler/checker.ts:14553]: I did wonder about looking inside the union to figure out whether there's a smaller span we could squiggle.

Comment (amcasey) [reply src/compiler/checker.ts:14553]: For the real code where this arose, the mitigation I suggested was adding a cast to each spread with a pre-existing type that listed all possible properties (optionally).  I imagine `any` would also work, possible at the expense of completions and such.

**Comment by amcasey** [comment]
If we broaden #34853, I'd probably drop the limit substantially.  I based it on what would still compile quickly in my toy example.

**Comment by amcasey** [comment]
@typescript-bot test this

**Comment by amcasey** [comment]
Since there are no occurrences of my new error code in the user test baseline diff, I'm assuming I can ignore the failure.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14544,6 +14544,17 @@ namespace ts {
...
             spread.objectFlags |= ObjectFlags.ObjectLiteral | ObjectFlags.ContainsObjectOrArrayLiteral | ObjectFlags.ContainsSpread | objectFlags;
             return spread;
+
+            function errorTypeIfTooLarge(): Type | undefined {
+                if (left.flags & right.flags & TypeFlags.Union) {
+                    const resultSize = (left as UnionType).types.length * (right as UnionType).types.length;
+                    if (resultSize > 100000) {
+                        tracing.instant(tracing.Phase.Check, "getSpreadType_DepthLimit", { leftId: left.id, rightId: right.id });
+                        error(currentNode, Diagnostics.Spread_expression_produces_a_union_type_that_is_too_complex_to_represent);
+                        return errorType;
```
Comment (amcasey) [inline src/compiler/checker.ts:14554]: @minestarks raised an interesting point: should this be `anyType` so that users have the option of ts-ignoring this error?

**Comment by amcasey** [comment]
This should probably use `checkCrossProductUnion`.
