### PR TITLE
feat(49928): Provide quick fix for a missing callback function

### LINKED ISSUE #49928: Provide quick fix for a missing callback function
# Suggestion

## 🔍 Search Terms

- quick fix
- code action
- callback 
- missing function

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The `fixMissingFunctionDeclaration` quick fix currently only works with a function call. It would be nice if the feature can be extended to support a callback function. It would be especially useful with an event handler when you don't remember the type of event. 

Probably needed to find out the target type of the callback function and use it to provide a quick fix. A shortcoming I can think of is that a function signature might have multiple overloads. So it might be quite impossible to summarize it in a quick fix description/ title. I think it would be ok if it only provides a quick fix when the function signature is apparent. Like only support when there is only one signature match. 

## 📃 Motivating Example

1. function call with callback function parameter
```ts
document.addEventListener('click', handleClick)
```

to

```ts
document.addEventListener('click', handleClick)

function handleClick(e: MouseEvent) {
   throw new Error("Function not implemented.");
}
```

2. object literal with a callback as property
```ts

interface HandleClick {
    onClick(e: Event): void;
}

const a: HandleClick = {
    onClick: handleClick
}
```

to 

```ts

interface HandleClick {
    onClick(e: Event): void;
}

const a: HandleClick = {
    onClick: handleClick
}

function handleClick(e: MouseEvent) {
   throw new Error("Function not implemented.");
}
```

3. similar to the previous one but with JSX

```tsx
<div onClick={onClick}>
```

## 💻 Use Cases

Quickly writes down the callback function declaration when you don't want an inline one. 

### Current behaviour
See the ts playground for the current behaviour. Right now the function call with a callback parameter would yield a wrong function and it's not supported in property assignment.

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgBJxAEwDYQMLbAIDWyA3gFDLXID2IBRxAFBAFzICiAbhOAJQdutYJgDcFAL4UKCegGcwyOB3RZcjEsgC85KjXqbiHABYYc+QiSkyz6y02YgIAd2QBZWgFd5EHnzBmAHIEK2Ig-n4JCkxaBC8AWwCAOjhMTH9wABlgRT5oYNCmIIAaZDsLI34ZWPik8FT0zLAcvOcoQrDS5BRtAD5y8w0w1kigA

### Workaround
There is a workaround for it now. just more verbose and unintuitive. Instead of directly writing down the function, wrap it with an arrow function or a function expression. 

```ts
document.addEventListener('click', e => handleClick(e))
```

This way the current quick fix would be able to pick it up and provide function declaration.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49928

### CODE REVIEW

**Review by ProKashif — APPROVED** [review]

File: src/services/codefixes/fixAddMissingMember.ts [hunk 1]
```diff
@@ -107,8 +112,8 @@ namespace ts.codefix {
         },
     });
 
-    const enum InfoKind { TypeLikeDeclaration, Enum, Function, ObjectLiteral, JsxAttributes }
-    type Info = TypeLikeDeclarationInfo | EnumInfo | FunctionInfo | ObjectLiteralInfo | JsxAttributesInfo;
+    const enum InfoKind { TypeLikeDeclaration, Enum, Function, ObjectLiteral, JsxAttributes, Signature }
```
Comment (sandersn) [inline src/services/codefixes/fixAddMissingMember.ts:115]: this might not be the place to fix it, but 

1. why is this a const enum instead of a normal one? Performance shouldn't be a concern here.
2. I think this should be formatted one entry per line, unless there's a reason not to.
3. It would be *little* easier to read if the enum were declared earlier, before its first use in the file. But I'm not sure about that.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 2]
```diff
@@ -190,8 +203,16 @@ namespace ts.codefix {
             return { kind: InfoKind.JsxAttributes, token, attributes, parentDeclaration: token.parent };
         }
 
-        if (isIdentifier(token) && isCallExpression(parent)) {
-            return { kind: InfoKind.Function, token, call: parent, sourceFile, modifierFlags: ModifierFlags.None, parentDeclaration: sourceFile };
+        if (isIdentifier(token)) {
+            const type = checker.getContextualType(token);
+            if (type && getObjectFlags(type) & ObjectFlags.Anonymous) {
+                const signature = firstOrUndefined(checker.getSignaturesOfType(type, SignatureKind.Call));
```
Comment (sandersn) [inline src/services/codefixes/fixAddMissingMember.ts:209]: internal to the checker is getFirstSignatureOfType, although given that you reimplemented it here, it's probably not exported.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 3]
```diff
@@ -458,6 +479,24 @@ namespace ts.codefix {
...
+        const importAdder = createImportAdder(context.sourceFile, context.program, context.preferences, context.host);
+        const functionDeclaration = createSignatureDeclarationFromSignature(SyntaxKind.FunctionExpression, context, quotePreference, info.signature,
+            createStubbedBody(Diagnostics.Function_not_implemented.message, quotePreference), info.token, /*modifiers*/ undefined, /*optional*/ undefined, /*enclosingDeclaration*/ undefined, importAdder);
+        if (functionDeclaration === undefined) {
+            Debug.fail("fixMissingFunctionDeclaration codefix got unexpected error.");
+        }
+        const returnStatement = isJsxExpression(info.parentDeclaration) ? findAncestor(info.parentDeclaration, isReturnStatement) : undefined;
+        if (returnStatement) {
+            changes.insertNodeBefore(info.sourceFile, returnStatement, functionDeclaration, /*blankLineBetween*/ true);
+        }
```
Comment (sandersn) [inline src/services/codefixes/fixAddMissingMember.ts:493]: Doesn't `addFunctionDeclaration` need this code too?

File: src/services/codefixes/fixAddMissingMember.ts [hunk 4]
```diff
@@ -31,8 +31,9 @@ namespace ts.codefix {
                 const changes = textChanges.ChangeTracker.with(context, t => addJsxAttributes(t, context, info));
                 return [createCodeFixAction(fixMissingAttributes, changes, Diagnostics.Add_missing_attributes, fixMissingAttributes, Diagnostics.Add_all_missing_attributes)];
             }
-            if (info.kind === InfoKind.Function) {
-                const changes = textChanges.ChangeTracker.with(context, t => addFunctionDeclaration(t, context, info));
+            if (info.kind === InfoKind.Function || info.kind === InfoKind.Signature) {
+                const changes = textChanges.ChangeTracker.with(context, t =>
+                    info.kind === InfoKind.Signature ? addFunctionDeclarationFromSignature(t, context, info) : addFunctionDeclaration(t, context, info));
```
Comment (sandersn) [inline src/services/codefixes/fixAddMissingMember.ts:36]: I would move the check for InfoKind.Signature inside addFunctionDeclaration since it would simplify the code. 

From reading addFunctionDeclaration I can't quite tell if you're better off with two different functions or not -- maybe the code could be unified.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/services/codefixes/fixAddMissingMember.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/codefixes/fixAddMissingMember.ts]: Ok, I've changed the formatting.

File: src/services/codefixes/fixAddMissingMember.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/codefixes/fixAddMissingMember.ts:211]: I didn't find this method in the checker. Maybe it has a different name :(.

File: src/services/codefixes/fixAddMissingMember.ts (hunk 4 above)
Comment (a-tarasyuk) [reply src/services/codefixes/fixAddMissingMember.ts]: Oke, moved

File: src/services/codefixes/fixAddMissingMember.ts [hunk 5]
```diff
@@ -451,10 +474,19 @@ namespace ts.codefix {
...
-        changes.insertNodeAtEndOfScope(info.sourceFile, info.parentDeclaration, functionDeclaration);
+        const functionDeclaration = info.kind === InfoKind.Function
+            ? createSignatureDeclarationFromCallExpression(SyntaxKind.FunctionDeclaration, context, importAdder, info.call, idText(info.token), info.modifierFlags, info.parentDeclaration)
+            : createSignatureDeclarationFromSignature(SyntaxKind.FunctionDeclaration, context, quotePreference, info.signature, createStubbedBody(Diagnostics.Function_not_implemented.message, quotePreference), info.token, /*modifiers*/ undefined, /*optional*/ undefined, /*enclosingDeclaration*/ undefined, importAdder);
+        if (functionDeclaration === undefined) {
+            Debug.fail("fixMissingFunctionDeclaration codefix got unexpected error.");
+        }
+
+        isReturnStatement(info.parentDeclaration)
+            ? changes.insertNodeBefore(info.sourceFile, info.parentDeclaration, functionDeclaration, /*blankLineBetween*/ true)
```
Comment (sandersn) [inline src/services/codefixes/fixAddMissingMember.ts:488]: Why does a `return` with JSX inside it cause the function to get inserted before it?
I know the typescript code base is not at all common JS style, but we always write functions after the return statement.

**Review by sandersn — CHANGES_REQUESTED** [review]
Question about JSX inside return statement

File: src/services/codefixes/fixAddMissingMember.ts (hunk 5 above)
Comment (a-tarasyuk) [reply src/services/codefixes/fixAddMissingMember.ts:488]: @sandersn I think this can be changed to write functions after the return. I just followed the most common style for React hooks

Screenshot 2022-07-30 at 11 02 22

Do I need to change that?

Comment (sandersn) [reply src/services/codefixes/fixAddMissingMember.ts:488]: No, following common React style is better than following the TS code base.

**Review by sandersn — APPROVED** [review]
