### PR TITLE
fixClassDoesnotImplementInheritedAbstractMember: Don't perform fix for same class twice

### LINKED ISSUE #21776: getCombinedCodeFix for implement abstract class can generate duplicate entries
From https://github.com/Microsoft/vscode/issues/43181

**TypeScript Version:**  2.8.0-insiders-20180206

**Search Terms:** 
- getCombinedCodeFix
- implement abstract class
- Implement interface

**Code**

```ts
export abstract class Foo {
	abstract a(): void;
	abstract b(): void;
	abstract c(): void;
}

class Bar extends Foo {
	
}
```

Trigger quick fix on `Bar` and select the `implement inherited abstract class (fix all in file)` fix

**Expected behavior:**
```ts
export abstract class Foo {
	abstract a(): void;
	abstract b(): void;
	abstract c(): void;
}

class Bar extends Foo {
	a(): void {
		throw new Error("Method not implemented.");
	}
	b(): void {
		throw new Error("Method not implemented.");
	}
	c(): void {
		throw new Error("Method not implemented.");
	}
}
```

**Actual behavior:**
Duplicate methods are generated:

```ts
export abstract class Foo {
	abstract a(): void;
	abstract b(): void;
	abstract c(): void;
}

class Bar extends Foo {
	a(): void {
		throw new Error("Method not implemented.");
	}
	b(): void {
		throw new Error("Method not implemented.");
	}
	c(): void {
		throw new Error("Method not implemented.");
	}
	a(): void {
		throw new Error("Method not implemented.");
	}
	b(): void {
		throw new Error("Method not implemented.");
	}
	c(): void {
		throw new Error("Method not implemented.");
	}
	a(): void {
		throw new Error("Method not implemented.");
	}
	b(): void {
		throw new Error("Method not implemented.");
	}
	c(): void {
		throw new Error("Method not implemented.");
	}
}
```

Here's the ts server trace

```
[Trace  - 1:00:04 PM] Sending request: getCodeFixes (39). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/src/index.tsx",
    "startLine": 7,
    "startOffset": 7,
    "endLine": 7,
    "endOffset": 10,
    "errorCodes": [
        2515
    ]
}
[Trace  - 1:00:04 PM] Response received: getCodeFixes (39). Request took 6 ms. Success: true 
Result: [
    {
        "description": "Implement inherited abstract class",
        "changes": [
            {
                "fileName": "/Users/matb/projects/san/src/index.tsx",
                "textChanges": [
                    {
                        "start": {
                            "line": 7,
                            "offset": 1
                        },
                        "end": {
                            "line": 9,
                            "offset": 2
                        },
                        "newText": "class Bar extends Foo {\n\ta(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tb(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tc(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n}"
                    }
                ]
            }
        ],
        "fixId": "fixClassDoesntImplementInheritedAbstractMember"
    }
]
[Trace  - 1:00:07 PM] Sending request: getCombinedCodeFix (40). Response expected: yes. Current queue length: 0
Arguments: {
    "scope": {
        "type": "file",
        "args": {
            "file": "/Users/matb/projects/san/src/index.tsx"
        }
    },
    "fixId": "fixClassDoesntImplementInheritedAbstractMember"
}
[Trace  - 1:00:07 PM] Response received: getCombinedCodeFix (40). Request took 12 ms. Success: true 
Result: {
    "changes": [
        {
            "fileName": "/Users/matb/projects/san/src/index.tsx",
            "textChanges": [
                {
                    "start": {
                        "line": 7,
                        "offset": 1
                    },
                    "end": {
                        "line": 9,
                        "offset": 2
                    },
                    "newText": "class Bar extends Foo {\n\ta(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tb(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tc(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\ta(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tb(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tc(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\ta(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tb(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n\tc(): void {\n\t\tthrow new Error(\"Method not implemented.\");\n\t}\n}"
                }
            ]
        }
    ]
}
```
**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #21776

### CODE REVIEW

File: src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts [hunk 1]
```diff
@@ -14,18 +14,22 @@ namespace ts.codefix {
             return changes.length === 0 ? undefined : [{ description: getLocaleSpecificMessage(Diagnostics.Implement_inherited_abstract_class), changes, fixId }];
         },
         fixIds: [fixId],
```
Comment (amcasey) [inline src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts]: I'm probably missing something obvious, but I would have guessed that the solution was to give all the fixes for the same derived-base pair the same fixId.

Comment (andy-ms) [reply src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts]: When we get a combined code fix, we want to get the fix for all classes in the file. The fixId is used only for asking for combined code fixes.

Comment (amcasey) [reply src/services/codefixes/fixClassDoesntImplementInheritedAbstractMember.ts]: Makes sense.  Thanks!
