### PR TITLE
Fix: checkAliasSymbol crash when checking for @deprecated

### LINKED ISSUE #42957: Cannot read property 'jsDocCache' of undefined crash on 4.2.2
# Bug Report

`tsc` crashes with a TypeError when compiling TS code with lots of JSDocs:

```
$ /Users/airhorns/Code/gadget/node_modules/.bin/tsc --noEmit
/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:88051
                throw e;
                ^

TypeError: Cannot read property 'jsDocCache' of undefined
    at getJSDocTagsWorker (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:9124:25)
    at getFirstJSDocTag (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:9144:24)
    at Object.getJSDocDeprecatedTag (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:9066:16)
    at addDeprecatedSuggestionWorker (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:36388:119)
    at addDeprecatedSuggestion (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:36397:20)
    at checkAliasSymbol (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:64716:21)
    at checkImportBinding (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:64723:13)
    at Object.forEach (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:128:30)
    at checkImportDeclaration (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:64754:36)
    at checkSourceElementWorker (/Users/airhorns/Code/gadget/node_modules/typescript/lib/tsc.js:65176:28)
error Command failed with exit code 1.
```

### 🔎 Search Terms

TypeError jsdoccache getJSDocTagsWorker

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.2.1 and 4.2.2

### 💻 Code

I am not sure which file in my project is causing this crash -- is there a hidden verbose compiler option that would indicate which file it's working on?

My tsconfig:

```
{
    "compilerOptions": {
        "strict": true,
        "esModuleInterop": true,
        "allowJs": true,
        "noImplicitAny": true,
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "forceConsistentCasingInFileNames": true,
        "useDefineForClassFields": true,
        "target": "es2020",
        "lib": [
            "es2020",
            "dom"
        ],
        "skipLibCheck": true,
        "resolveJsonModule": true,
        "baseUrl": "./",
        "moduleResolution": "node",
        "module": "commonjs",
        "jsx": "react",
        "types": [
            "jest",
            "@starscream/core/type-extensions/fastify-routes",
            "@starscream/core/type-extensions/pino",
            "@starscream/core/type-extensions/pino-pretty"
        ],
        "noEmit": true
    },
    "files": [ ... ],
    "include": [
        "./src",
        "./tools",
        "./spec",
        "./starscream.config.ts",
        "./types/gadget-fastify-extensions.d.ts"
    ],
    "exclude": [
        "node_modules",
        "spec/integration/typescript-client/fixtures"
    ]
}

```

### 🙁 Actual behavior

`tsc` crashes trying to compile an unspecified file

### 🙂 Expected behavior

`tsc` should succeed compiling the file or log an error to the console

### PR DESCRIPTION
**Pull request by sandersn**
It's possible that we shouldn't be creating symbol with no declarations from non-homomorphic mapped types, but for 4.2, the right fix is to make the @deprecated-check in checkAliasSymbol ensure that target.declarations is defined.

Fixes #42957, test case based on `@types/http-errors`

### CODE REVIEW

**Comment by sandersn** [comment]
@RyanCavanaugh @DanielRosenwasser you are probably interested in this too.

**Comment by sandersn** [comment]
We've been creating symbols this way since at least 3.0. The right thing to do is to put `undefined` into `Symbol.declarations`' type.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -37124,7 +37124,7 @@ namespace ts {
                     error(node, Diagnostics.Re_exporting_a_type_when_the_isolatedModules_flag_is_provided_requires_using_export_type);
                 }
 
-                if (isImportSpecifier(node) && every(target.declarations, d => !!(getCombinedNodeFlags(d) & NodeFlags.Deprecated))) {
```
Comment (weswigham) [inline src/compiler/checker.ts:37127]: Our `every` helper doesn't handle `undefined`? Most of our other array helpers treat `undefined` as an empty array input. Maybe we should change the helper?

Comment (sandersn) [reply src/compiler/checker.ts:37127]: It does handle `undefined`, but `every(undefined, _) ==> true`, and then `addDeprecatedSuggestion` crashes on the next line. 

This fix is shorter and uses the standard utility, so I think it's better.

Comment (weswigham) [reply src/compiler/checker.ts:37127]: Pffffff okay. Yeah.

**Review by weswigham — APPROVED** [review]

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this to 4.2

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this to release-4.2
