### PR TITLE
Fixed false positive circular errors for await expressions with simple non-generic calls in CFA loops

### LINKED ISSUE #51115: Circular type false positive with async/await
# Bug Report

### 🔎 Search Terms

implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer

await

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "referenced directly or indirectly"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/IYZwngdgxgBAZgV2gFwJYHsIwOYFNkD6yAFqhNiABQEBcMECAtgEa4BOMAPjEgCa5wyuXgEoYAbwCwAKBhyYbfAjZYA2gAYAugG4ZAXxkzQkWIhQYscdOmbA2lMVNnyANvhisriugxbsuPBD8ghDCMAC8gcFCvLrOcl6UbsgwqBEw6tqpMAA8MABMWagA1MWOMvKVMFCYICmKIAguyCDpwADuwKgpeIQkZBSUnuiKInFV8sOK6Q1NLRo6FfIG0itAA)

### 💻 Code

```ts
async function get_things(_: number | undefined) {
    return [0];
}

async function foobar() {
    // The error goes away without the `| undefined`
    let before: number | undefined = undefined;
    // The error goes away without the loop
    for(let i = 0; i < 2; i++) {
        // The error goes away without the async/await
        const results = await get_things(before);
        //       ^ 'results' implicitly has type 'any' because it does not have a type annotation
        //          and is referenced directly or indirectly in its own initializer.
        before = results[0];
    }
}

```

### 🙁 Actual behavior

This results in an error
```
'results' implicitly has type 'any' because it does not have a type annotation
and is referenced directly or indirectly in its own initializer.
```

### 🙂 Expected behavior

This should not be an error.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #51115

cc @jeremy-rifkin @garyo @bvallee-thefork

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -35348,20 +35348,20 @@ namespace ts {
                 }
             }
             expr = skipParentheses(node);
+            if (isAwaitExpression(expr)) {
+                const type = getQuickTypeOfExpression(expr.expression);
+                return type ? getAwaitedType(type) : undefined;
+            }
```
Comment (Andarist) [inline src/compiler/checker.ts:35354]: this is the core of the fix

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -35348,20 +35348,20 @@ namespace ts {
...
             // Optimize for the common case of a call to a function with a single non-generic call
             // signature where we can just fetch the return type without checking the arguments.
-            if (isCallExpression(expr) && expr.expression.kind !== SyntaxKind.SuperKeyword && !isRequireCall(expr, /*checkArgumentIsStringLiteralLike*/ true) && !isSymbolOrSymbolForCall(expr)) {
-                const type = isCallChain(expr) ? getReturnTypeOfSingleNonGenericSignatureOfCallChain(expr) :
+            else if (isCallExpression(expr) && expr.expression.kind !== SyntaxKind.SuperKeyword && !isRequireCall(expr, /*checkArgumentIsStringLiteralLike*/ true) && !isSymbolOrSymbolForCall(expr)) {
+                return isCallChain(expr) ? getReturnTypeOfSingleNonGenericSignatureOfCallChain(expr) :
                     getReturnTypeOfSingleNonGenericCallSignature(checkNonNullExpression(expr.expression));
-                if (type) {
-                    return type;
-                }
```
Comment (Andarist) [inline src/compiler/checker.ts:35358]: just removed a somewhat redundant lines, replaced that with direct `return` in the statement above this

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -35348,20 +35348,20 @@ namespace ts {
...
             }
             else if (isAssertionExpression(expr) && !isConstTypeReference(expr.type)) {
                 return getTypeFromTypeNode((expr as TypeAssertion).type);
             }
-            else if (node.kind === SyntaxKind.NumericLiteral || node.kind === SyntaxKind.StringLiteral ||
-                node.kind === SyntaxKind.TrueKeyword || node.kind === SyntaxKind.FalseKeyword) {
+            else if (isLiteralExpression(node)) {
```
Comment (Andarist) [inline src/compiler/checker.ts:35364]: a bonus optimization~ (?), we now handle here all literal expressions - instead of just a subset of them

File: tests/cases/conformance/controlFlow/controlFlowIterationErrorsAsync.ts [hunk 4]
```diff
@@ -0,0 +1,137 @@
+// @strict: true
```
Comment (Andarist) [inline tests/cases/conformance/controlFlow/controlFlowIterationErrorsAsync.ts:1]: I basically just copy-pasted existing [controlFlowIterationErrors](https://github.com/microsoft/TypeScript/blob/d234453328408dd1bbc7858db428b482bfcf0c6b/tests/cases/conformance/controlFlow/controlFlowIterationErrors.ts) test case and I converted all of the functions to be async.

In reality, only [the last two cases](https://github.com/microsoft/TypeScript/blob/d234453328408dd1bbc7858db428b482bfcf0c6b/tests/cases/conformance/controlFlow/controlFlowIterationErrors.ts#L74-L93) changed behavior with this PR so maybe I should limit what had been added to this test case? Either way, happy to clean up if needed - for now I've left those alone.

File: tests/cases/conformance/controlFlow/controlFlowIterationErrorsAsync.ts [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+    x = "0";
+    while (cond) {
+        x;
+        let y = await asNumber(x);
+        x = y + 1;
+        x;
+    }
+}
+
+// repro #51115
```
Comment (Andarist) [inline tests/cases/conformance/controlFlow/controlFlowIterationErrorsAsync.ts:97]: Here, we have the new test cases - based on the reported issues. They are very same-ish, but I've figured out that it still might be worthwhile to commit all of them.

File: tests/cases/compiler/implicitAnyFromCircularInference.ts [hunk 6]
```diff
@@ -39,7 +39,6 @@ interface A {
 function foo(x: A): string { return "abc"; }
 
 class C {
-    // Error expected
```
Comment (Andarist) [inline tests/cases/compiler/implicitAnyFromCircularInference.ts:42]: this was outdated, no error is being reported here (and no error has to be reported here)

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot perf test this faster

**Review by DanielRosenwasser — APPROVED** [review]
Without knowing much about this code path, I think this is reasonable. The only risk is the call to `getAwaitedType` which I think has re-entrance issues - but that issue is open at #42948.

With another sign-off, I would be okay with merging for 4.9, as it feels like a bug-fix.

**Comment by Andarist** [comment]
@DanielRosenwasser huh, luckily... I've fixed that particular issue a couple of months ago in [this PR](https://github.com/microsoft/TypeScript/pull/49677) :) I've created a PR with an extra test case that will close that issue: https://github.com/microsoft/TypeScript/pull/51167

**Comment by sandersn** [comment]
@DanielRosenwasser is this ready to merge now? (Once it's up-to-date with main)

**Comment by DanielRosenwasser** [comment]
You probably want to get @ahejlsberg to take a look at it in case I missed anything.

**Comment by Andarist** [comment]
@sandersn it's up to date now :)

**Comment by Andarist** [comment]
friendly 🏓 since this has been labeled with "Merge/Review for Next Release" and the 5.0 Beta is going to be published in 2 weeks

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -36330,20 +36332,20 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
-            if (type) {
-                return type;
-            }
         }
         else if (isAssertionExpression(expr) && !isConstTypeReference(expr.type)) {
             return getTypeFromTypeNode((expr as TypeAssertion).type);
         }
-        else if (node.kind === SyntaxKind.NumericLiteral || node.kind === SyntaxKind.StringLiteral ||
-            node.kind === SyntaxKind.TrueKeyword || node.kind === SyntaxKind.FalseKeyword) {
+        else if (isLiteralExpression(node)) {
```
Comment (rbuckton) [inline src/compiler/checker.ts:36348]: Why did this change? `isLiteralExpression` doesn't cover `TrueKeyword`/`FalseKeyword` so this isn't an equivalent change.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -36330,20 +36332,20 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
         expr = skipParentheses(node);
+        if (isAwaitExpression(expr)) {
+            const type = getQuickTypeOfExpression(expr.expression);
+            return type ? getAwaitedType(type) : undefined;
+        }
         // Optimize for the common case of a call to a function with a single non-generic call
         // signature where we can just fetch the return type without checking the arguments.
-        if (isCallExpression(expr) && expr.expression.kind !== SyntaxKind.SuperKeyword && !isRequireCall(expr, /*checkArgumentIsStringLiteralLike*/ true) && !isSymbolOrSymbolForCall(expr)) {
-            const type = isCallChain(expr) ? getReturnTypeOfSingleNonGenericSignatureOfCallChain(expr) :
+        else if (isCallExpression(expr) && expr.expression.kind !== SyntaxKind.SuperKeyword && !isRequireCall(expr, /*checkArgumentIsStringLiteralLike*/ true) && !isSymbolOrSymbolForCall(expr)) {
```
Comment (rbuckton) [inline src/compiler/checker.ts:36341]: Since the prior condition unconditionally returns, the `else` isn't really necessary here.

```suggestion
        if (isCallExpression(expr) && expr.expression.kind !== SyntaxKind.SuperKeyword && !isRequireCall(expr, /*checkArgumentIsStringLiteralLike*/ true) && !isSymbolOrSymbolForCall(expr)) {
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 8 above)
Comment (Andarist) [reply src/compiler/checker.ts:36341]: I probably just matched the "style" used by the following `else if`s. Should I just revert this one? Or change all of them?

File: src/compiler/checker.ts (hunk 7 above)
Comment (Andarist) [reply src/compiler/checker.ts:36348]: Sorry for this - I probably assumed that this already covers `TrueKeyword`/`FalseKeyword`. Tests pass without this `else if` branch - so this was probably an optimization or something (it's not an unused code).

I brought back the check for those keywords.

I don't exactly recall why I changed it in the first place - perhaps just to cover for all literal types as that seemed like the right thing to do at the time. If you want me to revert this change entirely, let me know.

Comment (rbuckton) [reply src/compiler/checker.ts:36348]: If it's not relevant to the bug you're fixing, I'd revert the change. The fact that changing it didn't affect any tests makes me more reticent to take the change, since we don't know what we'd be breaking.

File: src/compiler/checker.ts (hunk 8 above)
Comment (rbuckton) [reply src/compiler/checker.ts:36341]: I'd just revert this one.

**Comment by Andarist** [comment]
@rbuckton reverted those unrelated bits

**Review by rbuckton — APPROVED** [review]

**Comment by jeremy-rifkin** [comment]
Awesome to see this fixed and merged, thank you @Andarist!
