### PR TITLE
Fix Diff and Omit

### LINKED ISSUE #21148: Error in Diff / Omit types
**TypeScript Version:**  2.7.0-dev.20180111

**Code**

```ts
type Diff<T extends string, U extends string> = ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T];
type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>;
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(3,43): error TS2344: Type '({ [P in T]: P; } & { [P in U]: never; } & { [x: string]: never; })[keyof T]' does not satisfy the constraint 'keyof T'.
  Type '({ [P in T]: P; } & { [P in U]: never; })[keyof T]' is not assignable to type 'keyof T'.
```

These types were taken from https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-311923766 so are present in a few DefinitelyTyped packages.
There was no error in `typescript@2.7.0-dev.20180110`. Error discovered in `recompose` (among others) on DefinitelyTyped.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #21148 

Turns out `getConstraintOfIndexedAcess` only needs the substitution from the indexed access simplification code. Removing the string indexer makes the new early-exit code incorrectly say that `Diff` has no constraint, when it actually has a constraint `never`, from the string index signature.

Before #17912 this worked entirely by mistake, because the index signature was removed, then `getConstraintOfIndexedAccess` incorrectly returned `any` as the constraint.

```ts
type Diff<T extends string, U extends string> =
    ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T]
type Omit<U, K extends keyof U> = Pick<U, Diff<keyof U, K>>
```

Note that this PR also adds `Diff` and `Omit` to our tests.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8383,6 +8383,11 @@ namespace ts {
                     getIntersectionType(stringIndexTypes)
                 ]);
             }
+            return getSubstitutedIndexedMappedType(type);
+        }
+
+        function getSubstitutedIndexedMappedType(type: IndexedAccessType): Type {
+            const objectType = type.objectType;
```
Comment (Kovensky) [inline src/compiler/checker.ts]: `const { objectType } = type`?

File: tests/baselines/reference/indexedAccessRetainsIndexSignature.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
+//// [indexedAccessRetainsIndexSignature.ts]
+type Diff<T extends string, U extends string> =
+    ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T]
+type Omit<U, K extends keyof U> = Pick<U, Diff<keyof U, K>>
```
Comment (Kovensky) [inline tests/baselines/reference/indexedAccessRetainsIndexSignature.js]: (on many people's wishlist): add these to `lib.d.ts` 💟

File: tests/cases/compiler/indexedAccessRetainsIndexSignature.ts [hunk 3]
```diff
@@ -0,0 +1,6 @@
+type Diff<T extends string, U extends string> =
+    ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T]
+type Omit<U, K extends keyof U> = Pick<U, Diff<keyof U, K>>
+
+
+type O = Omit<{ a: number, b: string }, 'a'>
```
Comment (Kovensky) [inline tests/cases/compiler/indexedAccessRetainsIndexSignature.ts]: Maybe better add this to ensure a type error shows up if this breaks

```ts
const o: O = { b: '' }
```

**Comment by aczekajski** [comment]
Does it also repair 2.6.2 incorrect behaviour aroud `Omit`? Omit written as
```ts
type Omit<U, K extends keyof U> = Pick<U, Diff<keyof U, K>>;
```
is in fact an equivalent of
```ts
type Omit<T, K extends keyof T> = {[P in Diff<keyof T, K>]: T[P]};
```
and since now the latter works incorrectly, both of them should be incorporated in tests and they should also check if Omit maintains optional and readonly fields (refer to https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-357007839 ).

File: tests/baselines/reference/indexedAccessRetainsIndexSignature.js (hunk 2 above)
Comment (sandersn) [reply tests/baselines/reference/indexedAccessRetainsIndexSignature.js]: Diff and Omit might someday be in lib.d.ts once conditional types are in Typescript, but the current implementation is way too hacky.

Comment (aczekajski) [reply tests/baselines/reference/indexedAccessRetainsIndexSignature.js]: In fact, only Diff implementation is way too hacky. But it will be solved if subtraction types make it into typescript (someday).

**Comment by sandersn** [comment]
@aczekajski This fixes the incorrect error message caused by #17912. It does not fix the weird behaviour with optional properties.

**Comment by sandersn** [comment]
Looks like one of the Travis instances timed out. I'm going to merge this after getting verbal signoff from Mohamed and Anders.
