### PR TITLE
[Release-2.0] Fix 9662: Visual Studio 2015 with TS2.0 gives incorrect @types path resolution errors

### LINKED ISSUE #9662: Visual Studio 2015 with TS2.0 gives incorrect @types path resolution errors
@types path resolution and importing is succeeding, but these errors occurred on Visual Studio after a few minutes.

**TypeScript Version:**  2.0.0 with VS2015

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2688	Cannot find type definition file for '[
  "...\\localsocket/node_modules/@types\\empower",
  "...\\localsocket/node_modules/@types\\mocha",
  "...\\localsocket/node_modules/@types\\power-assert",
  "...\\localsocket/node_modules/@types\\power-assert-formatter"
]'.	localsocket		1	Active
Error	TS2688	Cannot find type definition file for '[
  "...\\localsocket/node_modules/@types\\empower",
  "...\\localsocket/node_modules/@types\\mocha",
  "...\\localsocket/node_modules/@types\\power-assert",
  "...\\localsocket/node_modules/@types\\power-assert-formatter"
]'.	localsocket		1	Active
```

I'll share this project for repro if necessary.

### PR DESCRIPTION
**Pull request by yuit**
Fix #9662 and #9740
This is only half the fix; the other half is in the managed-side repo

cc @RyanCavanaugh 

- [ ] Cherry-pick to release-2.0

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -1155,11 +1155,11 @@ namespace ts {
...
 
             // load type declarations specified via 'types' argument or implicitly from types/ and node_modules/@types folders
-            const typeReferences: string[] = getAutomaticTypeDirectiveNames(options, rootNames, host);
+            const typeReferences: string[] = getAutomaticTypeDirectiveNames(options, host);
 
             if (typeReferences) {
-                const inferredRoot = getInferredTypesRoot(options, rootNames, host);
-                const containingFilename = combinePaths(inferredRoot, "__inferred type names__.ts");
+                // This containgFilename needs to matched with the one used in managed-side
+                const containingFilename = "__inferred type names__.ts"
```
Comment (vladima) [inline src/compiler/program.ts]: does it work in VSCode? since this name is now always relative?

File: src/services/shims.ts [hunk 2]
```diff
@@ -72,18 +72,28 @@ namespace ts {
         directoryExists(directoryName: string): boolean;
     }
 
-    /** Public interface of the the of a config service shim instance.*/
-    export interface CoreServicesShimHost extends Logger, ModuleResolutionHost {
+    /** Public interface of the core-services host instance used in managed side */
+    export interface CoreServicesShimHost extends Logger {
```
Comment (vladima) [inline src/services/shims.ts]: most of these members were inherited from the `ModuleResolutionHost`. Is it really necessary to duplicate them?

File: src/compiler/program.ts (hunk 1 above)
Comment (yuit) [inline src/compiler/program.ts]: From talking off line, this is incorrect as it will not be unique to the project of interest. IT will be problematic if more than one project is open. The fix is to use `host.getCurrentDirectory()`

File: src/services/shims.ts (hunk 2 above)
Comment (yuit) [inline src/services/shims.ts]: The return type is actually different for 
```typescript
getDirectories(path: string): string //CoreServicesShimHost
getDirectories(path: string): string[] // ModuleResolutionHost
```

File: src/compiler/program.ts [hunk 3]
```diff
@@ -1155,11 +1151,11 @@ namespace ts {
             forEach(rootNames, name => processRootFile(name, /*isDefaultLib*/ false));
 
             // load type declarations specified via 'types' argument or implicitly from types/ and node_modules/@types folders
-            const typeReferences: string[] = getAutomaticTypeDirectiveNames(options, rootNames, host);
+            const typeReferences: string[] = getAutomaticTypeDirectiveNames(options, host);
 
             if (typeReferences) {
-                const inferredRoot = getInferredTypesRoot(options, rootNames, host);
-                const containingFilename = combinePaths(inferredRoot, "__inferred type names__.ts");
+                // This containgFilename needs to matched with the one used in managed-side
```
Comment (giannic) [inline src/compiler/program.ts]: `matched` -> `match`

**Comment by yuit** [comment]
@RyanCavanaugh @vladima :bell:

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by giannic** [comment]
🎆
