### PR TITLE
Report multiple overload errors

### LINKED ISSUE #27249: Report errors on all plausible overloads
**TypeScript Version:** 3.1

**Search Terms:** overload all errors

**Code**

```ts
declare function render(s: object, opts: { fileName: string }): void;
declare function render(s: string, name: string): void;

declare const obj: object;
// Actual error: cannot convert 'object' to 'string'
// Desired error: fileName / filename mismatch
render(obj, { filename: "foo" });
```

When multiple overloads with very different signatures exist, the ordering is effectively arbitrary. This creates **really bad** error messages when the "last" overload wasn't the one you were trying to call.

While some functions have an extremely large number of overloads, when there are only a few (< 5?) overloads, we should report their failures individually so that hopefully one of the error messages is useful.

e.g. instead of
```
TS2345: Argument of type 'object' is not assignable to parameter of type 'string'.
```
it should be
```
TSXXXX: Failed to find a suitable overload for this call
  When invoking "(s: string, name: stri...":
    TS2345: Argument of type 'object' is not assignable to parameter of type 'string'.
  When invoking "(s: object, opts: { fl...":
    TS2345: Argument of type '{ filename: string; }' is not assignable to parameter of type '{ fileName: string; }'.
      Object literal may only specify known properties, but 'filename' does not exist in type '{ fileName: string; }'. Did you mean to write 'fileName'?
```

**Playground Link:** [Link](http://www.typescriptlang.org/play/#src=declare%20function%20render(s%3A%20object%2C%20opts%3A%20%7B%20fileName%3A%20string%20%7D)%3A%20void%3B%0D%0Adeclare%20function%20render(s%3A%20string%2C%20name%3A%20string)%3A%20void%3B%0D%0A%0D%0Adeclare%20const%20obj%3A%20object%3B%0D%0A%2F%2F%20Actual%20error%3A%20cannot%20convert%20'object'%20to%20'string'%0D%0A%2F%2F%20Desired%20error%3A%20fileName%20%2F%20filename%20mismatch%0D%0Arender(obj%2C%20%7B%20filename%3A%20%22foo%22%20%7D)%3B%0D%0A)

**Related Issues:** #26633, others certainly exist

See also https://github.com/garybernhardt/preact-typescript-component-wont-build

### PR DESCRIPTION
**Pull request by sandersn**
Typescript currently reports assignability errors on the last overload for functions with multiple overloads, and it doesn't tell you that the function has more than one overload. Together, these two problems make fixing type errors on functions with overloads extremely frustrating.

This PR fixes the second problem for all overloaded functions, and addresses the first problem for overloaded functions with 3 or fewer overloads, [which is 99.32% of them](https://twitter.com/sanders_n/status/1141821637219586048) [1].

The resulting error output looks like this (from emacs; the formatting is similar in VS Code and the terminal [3]):

```
Code: 2755 Category: error

No suitable overload for this call.

Related Information: 

app.tsx:17 Overload 1 of 2, '(props: Readonly<{ x?: any; }>): BigGreeter', gave the following error.
  Argument of type '{ ref: (input: BigGreeter) => void; }' is not assignable to parameter of type 'Readonly<{ x?: any; }>'.
    Property 'ref' does not exist on type 'Readonly<{ x?: any; }>'. [2757]

app.tsx:17 Overload 2 of 2, '(props: { x?: any; }, context?: any): BigGreeter', gave the following error.
  Argument of type '{ ref: (input: BigGreeter) => void; }' is not assignable to parameter of type '{ x?: any; }'.
    Property 'ref' does not exist on type '{ x?: any; }'. [2757]
```

If there are more than 3 overloads, there are no related spans. Instead you see a single elaboration, which states that it applies to the last overload:

```
Code: 2755 Category: error

No suitable overload for this call.
  The last overload gave the following error.
    Type 'string' is not assignable to type 'void'.
      Type 'string' is not assignable to type 'void'.
```

Limitations and quirks:

1. We report multiple errors, even when some couldn't reasonably apply. It's also possible to guess a single, best overload to report errors on, and this will be obvious to humans in many cases. It's also complex to get right, and annoying when it's wrong.
2. We only report errors on overloads whose arity could match. This happens as a side effect of the way call resolution exits early for arity mismatch, but is usually the right thing.
4. We report errors as related spans, which don't show up in VS (and require an extra command to expand in emacs).
5. We report related spans of errors as related spans of related spans, which don't show up in any editor (or the terminal). [2]
3. We report multiple errors per overloads when object/array literal elaboration reports multiple errors. In other words words, this program reports four errors, two for each element in the array literal:

```ts
declare function f(ns: number[]): void
declare function f(bs: boolean[]): void
f(['hi', 'there'])
```

I don't think any of these limitations are worth fixing in this PR since it hits a good balance of effort compared to value. Since we do *some* filtering already, as in (2), it is a good idea to play with a bit more of it at some point. For example, I believe the surprising number of 100+ signature overload sets arise from the `on(kind: "string")` pattern, which has to be repeated in subclasses. This is one case where filtering by type, probably literal type only, would help a lot. But it's only a tiny percentage of functions.

Fixes #27249

[1]

histogram of overloads

[2]

philosoraptor: what if your related spans ... have related spans

[3] Indentation of elaborations of related spans is incorrect on the terminal: #32091

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11688,45 +11697,64 @@ namespace ts {
             return !!(type.flags & TypeFlags.Conditional || (type.flags & TypeFlags.Intersection && some((type as IntersectionType).types, isOrHasGenericConditional)));
         }
 
-        function elaborateError(node: Expression | undefined, source: Type, target: Type, relation: Map<RelationComparisonResult>, headMessage: DiagnosticMessage | undefined): boolean {
+        function elaborateError(
```
Comment (sandersn) [inline src/compiler/checker.ts]: the bulk of the lines in this PR go to making elaborateError and children handle `containingMessageChain` and `errorOutputContainer` the way that `checkTypeRelatedTo` already does. These two parameters are the mechanism for *returning* errors rather than immediately *logging* them, which allows me to build a tree of errors. That actually happens near the bottom of this change in checker.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11758,15 +11793,15 @@ namespace ts {
...
                 }
-                const resultObj: { error?: Diagnostic } = {};
-                checkTypeRelatedTo(sourceReturn, targetReturn, relation, returnExpression, /*message*/ undefined, /*chain*/ undefined, resultObj);
-                if (resultObj.error) {
+                const resultObj: { errors?: Diagnostic[] } = errorOutputContainer || {};
+                checkTypeRelatedTo(sourceReturn, targetReturn, relation, returnExpression, /*message*/ undefined, containingMessageChain, resultObj);
+                if (resultObj.errors) {
                     if (target.symbol && length(target.symbol.declarations)) {
-                        addRelatedInfo(resultObj.error, createDiagnosticForNode(
+                        addRelatedInfo(resultObj.errors[resultObj.errors.length - 1], createDiagnosticForNode(
```
Comment (sandersn) [inline src/compiler/checker.ts]: I add related info to the most recently added error. This doesn't display currently.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -21114,24 +21193,40 @@ namespace ts {
...
             // However "context" and "updater" are implicit and can't be specify by users. Only the first parameter, props,
             // can be specified by users through attributes property.
             const paramType = getEffectiveFirstArgumentForJsxSignature(signature, node);
             const attributesType = checkExpressionWithContextualType(node.attributes, paramType, /*inferenceContext*/ undefined, checkMode);
-            return checkTypeRelatedToAndOptionallyElaborate(attributesType, paramType, relation, reportErrors ? node.tagName : undefined, node.attributes);
+            return checkTypeRelatedToAndOptionallyElaborate(attributesType, paramType, relation, reportErrors ? node.tagName : undefined, node.attributes, undefined, containingMessageChain, errorOutputContainer);
         }
 
-        function checkApplicableSignature(
+        function getSignatureApplicabilityError(
```
Comment (sandersn) [inline src/compiler/checker.ts]: the return type of this function flips, from `true=applicable, false=not` to `Diagnostic[]=error(s), undefined=applicable`.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -12355,6 +12427,7 @@ namespace ts {
          * @param errorNode The suggested node upon which all errors will be reported, if defined. This may or may not be the actual node used.
          * @param headMessage If the error chain should be prepended by a head message, then headMessage will be used.
          * @param containingMessageChain A chain of errors to prepend any new errors found.
+         * @param errorOutputContainer Return the diagnostic. Do not log if 'skipLogging' is truthy.
```
Comment (sandersn) [inline src/compiler/checker.ts]: `skipLogging` is new, and prevents immediate logging of the error in checkTypeRelatedTo.

**Comment by DanielRosenwasser** [comment]
# Initial message

> No suitable overload for this call.

I don't like this because it's not idiomatic English. Why are we dropping words? At the very least, I think this would be better.

```diff
- No suitable overload for this call.
+ There is no suitable overload for this call.
```

or maybe even

```
No overload matched with this call.
```

If you have an identifier or property access, you can write

```
No overload of '{0}' was suitable for this call.
```

# Count of candidates

> Overload 1 of 2

Are these always guaranteed to have an order? Do they have some relevant ordering within source code? Maybe it makes more sense to elaborate on the original error messages with something like.

```
There is no suitable overload for this call.
  We found '{0}' likely overloads which you may be trying to use.
```

# Falling back to the last overload

> The last overload gave the following error.

Which overload is that? Give me a related span to point me in the direction of the overload if it wasn't applicable, or tell me the signature of the overload.

# Arity filtering

> We only report errors on overloads whose arity could match. This happens as a side effect of the way call resolution exits early for arity mismatch, but is usually the right thing.

We need to be wary of how this affects editor scenarios. In editor scenarios, we used to check whether a call was still in the process of being typed to make decisions on filtering out higher-arity candidates. That may still be the case.

# Display as bare messages

> We report errors as related spans, which don't show up in VS (and require an extra command to expand in emacs).
> We report errors as related spans, which don't show up in any editor (or the terminal). [2]

I think this might actually be a blocker and we need to find a way to surface this for VS users.

# Duplicates on arrays/object literals

> We report multiple errors per overloads when object/array literal elaboration reports multiple errors. In other words words, this program reports four errors, two for each element in the array literal:

I don't think that's an acceptable experience and I would really like us not to look stupid here. In these cases I think I as a user would prefer that when no overloads apply, TypeScript should pick an overload, link me to it in a related span, and report as we used to.

**Comment by DanielRosenwasser** [comment]
I should also mention, JSX cases seem to need a bit of improvement, but we chatted about that offline.

Apart from that, I'm really excited about this work!

**Comment by sandersn** [comment]
cc @amcasey

**Comment by sandersn** [comment]
After some in-person discussion:

1. Message: I like your wording much better.
2. Count: There is definitely an order, and it's usually easy to understand (except for interface or intersection merging). There might be a better way to word the message.
3. Fallback to the last overload: :+1: on improving the message here.
4. Arity filtering: I will leave as-is for now, but I need to make a reliable way to detect being called from quickinfo and remove the arity filtering in that case.
5. Bare messages: I miswrote the second point, but will talk to @amcasey about the first.
6. Duplicates: We decided to check whether any overload returns multiple errors, and in that case show only one overload -- the one with the fewest errors (or last one if there are multiple with the same number).

**Comment by sandersn** [comment]
After talking to @amcasey in person, it sounds like pre-flattening the error to text will work for VS (and any other editor that doesn't want to support related spans).

I'm going to create a prototype and make sure the experience is OK. 
Then I'll figure out the protocol changes needed and ship that as a separate PR in 3.6.

**Comment by sandersn** [comment]
Fun fact: since this PR changes error reporting for all overloads, I can see that we only have 44 / 13,000 tests with errors on overloaded functions.

**Comment by sandersn** [comment]
After talking to @amcasey: the most likely solution is to change the diagnostic protocol to start flattening related spans text into `text: string`, and add a new property `headText: string` that is what `text` is today -- the error *without* any related spans. That way old editors will see related spans by default in their message text, although editors with related-span support will have to update to use headText instead of text.

**Comment by weswigham** [comment]
> I think this might actually be a blocker and we need to find a way to surface this for VS users.

Could always flatten the related spans at the protocol layer. So instead of
```
Overload 1
  - span 1
  - span 2
Overload 2
  - span 1
  - span 2
```
you get
```
Overload 1
span 1
span 2
Overload 2
span 1
span 2
```
they'll display in-order in the editor, after all.

**Comment by sandersn** [comment]
@weswigham my plan is to do exactly that, but start putting the flattened version in `text` so that old editors will start seeing related spans as flattened text always. New editors will have to switch to `headText` to get the text that excludes related spans.

**Comment by weswigham** [comment]
Isn't that going to regress our UI in every non-VS editor (until they all update in a way that to them is just pointless churn)? Seems like we should be able to deal with it differently, like by adding a VS-specific command or, alternatively, by flattening the text before display, _in VS_...

**Comment by amcasey** [comment]
@weswigham It's not just VS that's affected - it's any _version_ of any editor that consumes the `text` property.  VS is a particularly bad case since people keep using the same version for many years, but any user not on the latest version of their editor (assuming their editor has picked up the changes) will also be affected.

**Comment by sandersn** [comment]
Adding things to VS doesn't fix 3.6 for users of old VS. I believe most of our other users update their editors (or at least their typescript plugins) regularly and that this is not true of VS. I'm going to discuss our options with the VS and VS Code people at our next meeting, so I'll have a better idea after that.

For editors that don't yet support related spans, this will also be an improvement. That includes vim and sublime, as far as I can tell from their respective plugins' source.

**Comment by weswigham** [comment]
> For editors that don't yet support related spans, this will also be an improvement. 

I doubt that can be made as a blanket statement - most of the information in related spans is a related spans precisely because it's _too much_ information for the original error.

I'm going to confidently state that we would never consider such a backwards incompatible reversal of protocol behavior (since that would cause everyone currently displaying related spans to display spans once badly in the message with no linkage and a second time correctly in their own UI) for anything other than the pressure applied by VS... And even with that pressure, this is a huge _UI visible_ break compared to most changes we make, and should not be made lightly. Inlining everything into `text` _will_ break the UI of _every_ current and updated language server client.

**Comment by amcasey** [comment]
My bar is that the experience has to remain reasonable for any editor currently consuming either just `text` or `text` and `relatedSpans`.  From a client perspective, the ideal way to do that would be to retain the current output of those properties and put anything differently formatted in a _new_ property.  In practice, that might result in duplicate work and ugly server code, so I think @sandersn is looking for a compromise.  Without having reviewed the behavior proposed by this PR, I agree that some massaging will probably be required.

**Comment by weswigham** [comment]
Also: why are these overload elaborations related spans anyway? They're not associated with a new location or anything, they're just _a lot of text_ - either they should be displayed, and therefore be inlined in the `error` (which simply necessitates a kind of `flattenDiagnosticInformation` that allows detenting), or not... If we think the error is unsolvable without the information, then it should be in the error message proper.

**Comment by sandersn** [comment]
> I doubt that can be made as a blanket statement - most of the information in related spans is a related spans precisely because it's too much information for the original error.

I disagree. For the UIs we care most about -- VS Code and the terminal -- related spans display every time the error does. Probably the other editors should behave the same.

> Also: why are these overload elaborations related spans anyway? 

I think the error should be a tree structure internally, and related spans are the existing method tree structure, so that's what I used. We could create two kinds of tree structure, one for errors and one for related spans. But the value of that is low if we always display related spans.

> They're not associated with a new location or anything

The declaration of the overload should be the location. Looks like that's wrong right now, though.

**Comment by sandersn** [comment]
OK, I switched from related spans to a tree of elaborations. @weswigham mind taking a look?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -21542,9 +21649,55 @@ namespace ts {
...
+                            }
+                            i++;
+                        }
 
-                if (candidateForArgumentError) {
-                    checkApplicableSignature(node, args, candidateForArgumentError, assignableRelation, CheckMode.Normal, /*reportErrors*/ true);
+                        const related = map(
+                            max > 1 ? allDiagnostics[minIndex] : flatten(allDiagnostics),
+                            d => typeof d.messageText === "string" ? (d as DiagnosticMessageChain) : d.messageText);
+                        diagnostics.add(createDiagnosticForNodeFromMessageChain(node, chainDiagnosticMessages(related, Diagnostics.No_overload_matches_this_call)));
```
Comment (weswigham) [inline src/compiler/checker.ts]:
```suggestion
                        const diags = max > 1 ? allDiagnostics[minIndex] : flatten(allDiagnostics);
                        const related = map(
                            diags,
                            d => typeof d.messageText === "string" ? (d as DiagnosticMessageChain) : d.messageText);
                        diagnostics.add(createDiagnosticForNodeFromMessageChain(node, chainDiagnosticMessages(related, Diagnostics.No_overload_matches_this_call), reduceLeft(diags, (acc, d) => acc.concat(d.relatedInformation || []), [] as DiagnosticRelatedInformation[])));
```
?

File: src/compiler/utilities.ts [hunk 6]
```diff
@@ -7171,30 +7170,70 @@ namespace ts {
         return d1.relatedInformation ? Comparison.LessThan : Comparison.GreaterThan;
     }
 
+    // function compareMessageText(t1: string | DiagnosticMessageChain[], t2: string | DiagnosticMessageChain[]): Comparison {
```
Comment (weswigham) [inline src/compiler/utilities.ts]: Probably shouldn't leave this old code lying around here.

File: src/compiler/utilities.ts [hunk 7]
```diff
@@ -7171,30 +7170,70 @@ namespace ts {
...
+        if (!t1.next && !t2.next) {
+            return Comparison.EqualTo;
+        }
+        if (!t1.next) {
+            return Comparison.LessThan;
+        }
+        if (!t2.next) {
+            return Comparison.GreaterThan;
+        }
+        res = compareValues(t1.next.length, t2.next.length);
```
Comment (weswigham) [inline src/compiler/utilities.ts]: Rather than sorting by length first, I think we should should by "effective alphanumeric concatenation" - so _first_ we sort pairwise over the elements of `next` until either both are exhausted or once side is missing one - if one side is missing one, the side with fewer is then less. This ordering has the effect that
```ts
1. - Message qux
    - Message vaz
2. - Message alph
3. - Message wex
```
will be sorted
```ts
2. - Message alph
1. - Message qux
    - Message vaz
3. - Message wex
```
because we'll sort the `qux` message between `wex` and `alph` before sorting by length (which we won't need to do, since everything will be sorted just by looking at the first message).

File: src/compiler/checker.ts (hunk 5 above)
Comment (sandersn) [reply src/compiler/checker.ts]: DiagnosticRelatedInformation doesn't have a property named relatedInformation, just Diagnostic. I'll see whether a cast is safe here.

File: src/compiler/utilities.ts (hunk 6 above)
Comment (sandersn) [reply src/compiler/utilities.ts]: woooooooops. removed.

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts]: The cast in that suggestion is on an empty array, just so it's not inferred as a `never[]` - or were you referencing something else?

Comment (sandersn) [reply src/compiler/checker.ts]: `acc.concat(d.relatedInformation || [])` : `d: DiagnosticRelatedInformation` has no property `relatedInformation`. Only its subtype `Diagnostic` does.

**Comment by fatcerberus** [comment]
> It's also possible to guess a single, best overload to report errors on, and this will be obvious to humans in many cases. It's also complex to get right

It's so amazing how things that are incredibly obvious to humans can be difficult (or even undecidable!) for computers.
