### PR TITLE
Fix too many watcher instances issue

### LINKED ISSUE #6016: 1.7: TS Server opens a file handle for watching for each file in the project results in EMFILE error
Since we updated from TS server 1.6 to 1.7 we notice sporadic crashes in the TS server for our VS Code code base that has around 1100 typescript files in one project. 

When I compare 1.6 with 1.7 I notice that you changed the strategy for watching for file changes from `fs.watchFile` to `fs.watch`. The latter is recommended because it leverages native file watching while the former is polling for changes (see https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts#L409 in 1.7 and https://github.com/Microsoft/TypeScript/blob/v1.6.2/src/compiler/sys.ts#L286 in 1.6).

Now, since this method is being used for every file of the project, on Unix/Mac you end up with as much open file handles as you have TS files in the project. For VS Code this means > 1000 file handles and eventually I see this in the logs:

`EMFILE: too many open files, open '/Users/bpasero/Development/monaco/src/vs/workbench/services/files/node/watcher/unix/chokidarWatcherService.ts'
Error: EMFILE: too many open files, open '/Users/bpasero/Development/monaco/src/vs/workbench/services/files/node/watcher/unix/chokidarWatcherService.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.readFile (/Users/bpasero/Development/tssdk/built/local/tsserver.js:1904:34)
    at ProjectService.openFile (/Users/bpasero/Development/tssdk/built/local/tsserver.js:53513:60)
    at ProjectService.openConfigFile (/Users/bpasero/Development/tssdk/built/local/tsserver.js:53719:45)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/Users/bpasero/Development/tssdk/built/local/tsserver.js:53583:49)
    at ProjectService.openClientFile (/Users/bpasero/Development/tssdk/built/local/tsserver.js:53564:22)`

I don't see a good work around on my end and will have to go back to 1.6. I think a better solution would be to install a watcher per root directory and then do the filtering on the event instead of installing a watcher for each file upfront.

### PR DESCRIPTION
**Pull request by zhengbli**
Fix #6016.

Instead of creating a watcher for every single file, I create watchers only for the directory that the files are in, and matches the file change event with a list of registered files.

### CODE REVIEW

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -293,6 +293,50 @@ namespace ts {
                     removeFile: removeFile
                 };
             }
+            
+            function createWatchedFileSet() {
+                let watchedDirectories: { [path: string]: FileWatcher } = {};
```
Comment (vladima) [inline src/compiler/sys.ts]: this map does not take case sensitivity\slashes into account

File: src/compiler/sys.ts [hunk 2]
```diff
@@ -293,6 +293,50 @@ namespace ts {
...
                 };
             }
+            
+            function createWatchedFileSet() {
+                let watchedDirectories: { [path: string]: FileWatcher } = {};
+                let watchedFiles: { [fileName: string]: (fileName: string, removed?: boolean) => void; } = {};
+                
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const file: WatchedFile = { fileName, callback };
+                    let watchedPaths = Object.keys(watchedDirectories);
```
Comment (vladima) [inline src/compiler/sys.ts]: not sure that I understand why do we use map-list structure if ultimately it is still doing linear scan over the array of keys (getting those also incur extra array allocation)

File: src/compiler/sys.ts [hunk 3]
```diff
@@ -293,6 +293,50 @@ namespace ts {
...
+                    watchedFiles[fileName] = callback;
+                    return { fileName, callback }
+                }
+                
+                function removeFile(file: WatchedFile) {
+                    delete watchedFiles[file.fileName];
+                }
+                
+                function fileEventHandler(eventName: string, fileName: string) {
+                    if (watchedFiles[fileName]) {
```
Comment (vladima) [inline src/compiler/sys.ts]: hasProperty

File: src/compiler/sys.ts (hunk 1 above)
Comment (mhegazy) [inline src/compiler/sys.ts]: use FileMap instead.

File: src/compiler/sys.ts [hunk 4]
```diff
@@ -293,6 +293,50 @@ namespace ts {
...
+                            pathToWatch, 
+                            (eventName: string, relativeFileName: string) => fileEventHandler(eventName, ts.normalizePath(ts.combinePaths(pathToWatch, relativeFileName)))
+                        );
+                    }
+                    watchedFiles[fileName] = callback;
+                    return { fileName, callback }
+                }
+                
+                function removeFile(file: WatchedFile) {
+                    delete watchedFiles[file.fileName];
```
Comment (mhegazy) [inline src/compiler/sys.ts]: but we are still watching the directory anyways? when do a directory watcher ever dies?

File: src/compiler/sys.ts [hunk 5]
```diff
@@ -293,6 +293,50 @@ namespace ts {
...
+                        let pathToWatch = ts.getDirectoryPath(fileName);
+                        for (let watchedPath in watchedDirectories) {
+                            if (watchedPath.indexOf(pathToWatch) === 0) {
+                                watchedDirectories[watchedPath].close();
+                                delete watchedDirectories[watchedPath];
+                            }
+                        }
+                        watchedDirectories[pathToWatch] = _fs.watch(
+                            pathToWatch, 
+                            (eventName: string, relativeFileName: string) => fileEventHandler(eventName, ts.normalizePath(ts.combinePaths(pathToWatch, relativeFileName)))
```
Comment (mhegazy) [inline src/compiler/sys.ts]: do we need to do this every time? is the relativeFileName expected to change between invocations?

File: src/compiler/sys.ts (hunk 2 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: Because each directory path corresponds to a filewatcher that we may need to call its `close` method later. For better performance maybe I can use a separate string array for searching and a map to look for watcher. Are there better alternatives?

File: src/compiler/sys.ts (hunk 5 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: Thing is we don't know what the relative file name is "relative" to. For example, we may have a watcher for `C:\project\test` and later on replaced by a higher level `C:\project` because turns out we need to watch files in that folder as well, so `_fs.watch` returns different relative path for the same file in the `C:\project\test` folder.

**Comment by zhengbli** [comment]
@mhegazy @vladima due to the approaching release deadline and concerns from @bpasero, I'll revert the polling watchers for all cases and send another PR to address the CR feedbacks after the release.

File: src/compiler/sys.ts [hunk 6]
```diff
@@ -294,6 +294,50 @@ namespace ts {
...
 
+            function createWatchedFileSet() {
+                const watchedDirectories: { [path: string]: FileWatcher } = {};
+                const watchedFiles: { [fileName: string]: (fileName: string, removed?: boolean) => void; } = {};
+
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const file: WatchedFile = { fileName, callback };
+                    const watchedPaths = Object.keys(watchedDirectories);
+                    // Try to find parent paths that are already watched. If found, don't add directory watchers
+                    const watchedParentPaths = watchedPaths.filter(path => fileName.indexOf(path) === 0);
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: Use `ts.filter`

File: src/compiler/sys.ts [hunk 7]
```diff
@@ -294,6 +294,50 @@ namespace ts {
                 };
             }
 
+            function createWatchedFileSet() {
+                const watchedDirectories: { [path: string]: FileWatcher } = {};
+                const watchedFiles: { [fileName: string]: (fileName: string, removed?: boolean) => void; } = {};
+
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const file: WatchedFile = { fileName, callback };
+                    const watchedPaths = Object.keys(watchedDirectories);
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: `Object.keys` is ES5 only, use `ts.forEachKey`

File: src/compiler/sys.ts [hunk 8]
```diff
@@ -294,6 +294,50 @@ namespace ts {
...
+            function createWatchedFileSet() {
+                const watchedDirectories: { [path: string]: FileWatcher } = {};
+                const watchedFiles: { [fileName: string]: (fileName: string, removed?: boolean) => void; } = {};
+
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const file: WatchedFile = { fileName, callback };
+                    const watchedPaths = Object.keys(watchedDirectories);
+                    // Try to find parent paths that are already watched. If found, don't add directory watchers
+                    const watchedParentPaths = watchedPaths.filter(path => fileName.indexOf(path) === 0);
+                    // If adding new watchers, try to find children paths that are already watched. If found, close them.
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: child paths

Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: If adding new watchers, we need to close any existing watchers for subdirectories.

File: src/compiler/sys.ts [hunk 9]
```diff
@@ -294,6 +294,50 @@ namespace ts {
...
+                function fileEventHandler(eventName: string, fileName: string) {
+                    if (watchedFiles[fileName]) {
+                        const callback = watchedFiles[fileName];
+                        callback(fileName);
+                    }
+                }
+
+                return {
+                    addFile: addFile,
+                    removeFile: removeFile
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: Use shorthand properties to avoid repetition

File: src/compiler/sys.ts [hunk 10]
```diff
@@ -294,6 +294,50 @@ namespace ts {
...
+                }
+
+                function fileEventHandler(eventName: string, fileName: string) {
+                    if (watchedFiles[fileName]) {
+                        const callback = watchedFiles[fileName];
+                        callback(fileName);
+                    }
+                }
+
+                return {
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: Move this prior to the function declarations

File: src/compiler/sys.ts [hunk 11]
```diff
@@ -307,7 +351,8 @@ namespace ts {
             // changes for large reference sets? If so, do we want
             // to increase the chunk size or decrease the interval
             // time dynamically to match the large reference set?
-            const watchedFileSet = createWatchedFileSet();
+            const pollingWatchedFileSet = createPollingWatchedFileSet();
+            // const watchedFileSet = createWatchedFileSet();
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: Remove this comment

File: src/compiler/sys.ts [hunk 12]
```diff
@@ -294,6 +294,50 @@ namespace ts {
                 };
             }
 
+            function createWatchedFileSet() {
+                const watchedDirectories: { [path: string]: FileWatcher } = {};
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: `Map<string>`

File: src/compiler/sys.ts [hunk 13]
```diff
@@ -294,6 +294,50 @@ namespace ts {
                 };
             }
 
+            function createWatchedFileSet() {
+                const watchedDirectories: { [path: string]: FileWatcher } = {};
+                const watchedFiles: { [fileName: string]: (fileName: string, removed?: boolean) => void; } = {};
```
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: `Map<(fileName: string, removed?: boolean) => void>`

Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: Actually, consider creating a local type alias named`FileChangedCallback` type and use it here and for the `callback` parameter of `addFile`

File: src/compiler/sys.ts (hunk 12 above)
Comment (vladima) [inline src/compiler/sys.ts]: using Map here is incorrect since it does not deal with case sensitivity

**Comment by bpasero** [comment]
Btw I don't really have concerns about this change it is totally the right way of doing it, but I am a bit nervous because VS Code is shipping next week with TS 1.7 and I want to make sure we are not introducing a regression late in the game. Back to polling for 1.7.x and then this right fix for 1.8 would be nice.

File: src/compiler/sys.ts [hunk 14]
```diff
@@ -294,6 +294,50 @@ namespace ts {
...
+
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const file: WatchedFile = { fileName, callback };
+                    const watchedPaths = Object.keys(watchedDirectories);
+                    // Try to find parent paths that are already watched. If found, don't add directory watchers
+                    const watchedParentPaths = watchedPaths.filter(path => fileName.indexOf(path) === 0);
+                    // If adding new watchers, try to find children paths that are already watched. If found, close them. 
+                    if (watchedParentPaths.length === 0) {
+                        const pathToWatch = ts.getDirectoryPath(fileName);
+                        for (const watchedPath in watchedDirectories) {
```
Comment (vladima) [inline src/compiler/sys.ts]: this part is interesting.correct me please if I'm wrong, here you are saying: "As I see nobody is watching folder 'pathToWatch' so I'm going to install watcher for it. However it is possible that somebody is already watching 'pathToWatch/<some-path>'. If yes - I'm going to shutdown this watcher since watcher for 'pathToWatch' should get the same notifications". 

If the answer is 'yes' then I'm curious how it works since by default `fs.watch` is [not recursive](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener) so if initially you had watcher for '/a/b/c/d' and then you install one for '/a/b' then after closing watcher for '/a/b/c/d' you'll receive no notifications about changes in this file

File: src/compiler/sys.ts (hunk 12 above)
Comment (DanielRosenwasser) [inline src/compiler/sys.ts]: To clarify, that means that this current code is incorrect for the same reason, right @vladima?

Comment (vladima) [inline src/compiler/sys.ts]: exactly. it should use `FileMap`

File: src/compiler/sys.ts (hunk 14 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: You are right, I was trying to use the recursive `fs.watch` but forgot to specify the `{recursive: true}` option. 

Though on a second thought, this logic may be too complex when I need to close a unused directory watcher later. For non-recursive watchers I can just check if the direct parent folder has any files in the watching list, while for recursive watchers it's more complex. It might make more sense to check to the non-recursive version.

Comment (vladima) [inline src/compiler/sys.ts]: I would think twice before completely switching to recursive watchers or at least test it in different scenarios. Effectively it means that if user adds some file that is close to the root of the disk then watcher will receive tons of notifications about files he doesn't care

**Comment by zhengbli** [comment]
@bpasero @vladima @DanielRosenwasser for the approaching release 1.7.5 I sent another PR that rolls back to polling watchers. This PR will be updated according to code reviews and tested after the release to reduce risks.

File: src/compiler/sys.ts (hunk 14 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: Good point, noted. Thanks!

**Comment by bpasero** [comment]
:+1:

File: src/compiler/sys.ts [hunk 15]
```diff
@@ -294,6 +294,50 @@ namespace ts {
...
+                            if (watchedPath.indexOf(pathToWatch) === 0) {
+                                watchedDirectories[watchedPath].close();
+                                delete watchedDirectories[watchedPath];
+                            }
+                        }
+                        watchedDirectories[pathToWatch] = _fs.watch(
```
Comment (mihailik) [inline src/compiler/sys.ts]: Isn't it sloppy in regards of `hasOwnProperty`, `toString` that may exist as files and clash with members on `watchDirectories` object?

Comment (vladima) [inline src/compiler/sys.ts]: true and this is one more argument to switch to `FileMap` which handles this case correctly

**Comment by zhengbli** [comment]
@vladima @DanielRosenwasser @mhegazy Updated this PR using FileMap, please let me know if you have further comments. Thanks!

File: src/compiler/sys.ts [hunk 16]
```diff
@@ -298,6 +298,55 @@ namespace ts {
...
+            function createWatchedFileSet() {
+                const watchedDirectories = createFileMap<FileWatcher>();
+                const watchedFiles = createFileMap<(fileName: string, removed?: boolean) => void>();
+                const currentDirectory = process.cwd();
+
+                return { addFile, removeFile };
+
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const path = toPath(fileName, currentDirectory, getCanonicalPath);
+                    const parentDirPath = toPath(ts.getDirectoryPath(fileName), currentDirectory, getCanonicalPath);
```
Comment (billti) [inline src/compiler/sys.ts]: Shouldn't you getDirectoryPath on the path you just created in the line above, rather than the fileName which may not be a (normalized) full path?

File: src/compiler/sys.ts [hunk 17]
```diff
@@ -298,6 +298,55 @@ namespace ts {
...
+                    }
+                    watchedFiles.set(path, callback);
+                    return { fileName, callback };
+                }
+
+                function removeFile(file: WatchedFile) {
+                    const path = toPath(file.fileName, currentDirectory, getCanonicalPath);
+                    watchedFiles.remove(path);
+
+                    const parentDirPath = toPath(ts.getDirectoryPath(path), currentDirectory, getCanonicalPath);
```
Comment (billti) [inline src/compiler/sys.ts]: See above comment. Seems like you did that here :-)

File: src/compiler/sys.ts [hunk 18]
```diff
@@ -298,6 +298,55 @@ namespace ts {
                 };
             }
 
+            function createWatchedFileSet() {
+                const watchedDirectories = createFileMap<FileWatcher>();
+                const watchedFiles = createFileMap<(fileName: string, removed?: boolean) => void>();
```
Comment (vladima) [inline src/compiler/sys.ts]: make a type alias for the callback type

File: src/compiler/sys.ts [hunk 19]
```diff
@@ -415,9 +465,10 @@ namespace ts {
                     // and is more efficient than `fs.watchFile` (ref: https://github.com/nodejs/node/pull/2649
                     // and https://github.com/Microsoft/TypeScript/issues/4643), therefore
                     // if the current node.js version is newer than 4, use `fs.watch` instead.
-                    const watchedFile = watchedFileSet.addFile(fileName, callback);
+                    const watchSet = isNode4OrLater() ? watchedFileSet : pollingWatchedFileSet;
+                    const watchedFile =  watchSet.addFile(fileName, callback);
                     return {
-                        close: () => watchedFileSet.removeFile(watchedFile)
+                        close: () => watchSet.removeFile(watchedFile)
```
Comment (billti) [inline src/compiler/sys.ts]: "watchDirectory" (line 474 below) also talks about Node 4 or later and uses the 'recursive' option, but doesn't actually check for Node 4 or later. 

I can see in "tsc.ts" and "editorServices.ts" it is called with "recursive: true". Are there potentially issues here if not on Node v4?

File: src/compiler/sys.ts (hunk 16 above)
Comment (vladima) [inline src/compiler/sys.ts]: `toPath` should take care of it, however the valid point here is that separators in `fileName` might still vary and `getDirectoryPath` expects them to be only forward slashes. I agree with @billti that it will be simplier to just call `const parentDirPath = getDirectoryPath(path)`

File: src/compiler/sys.ts [hunk 20]
```diff
@@ -298,6 +298,55 @@ namespace ts {
...
+                const watchedFiles = createFileMap<(fileName: string, removed?: boolean) => void>();
+                const currentDirectory = process.cwd();
+
+                return { addFile, removeFile };
+
+                function addFile(fileName: string, callback: (fileName: string, removed?: boolean) => void): WatchedFile {
+                    const path = toPath(fileName, currentDirectory, getCanonicalPath);
+                    const parentDirPath = toPath(ts.getDirectoryPath(fileName), currentDirectory, getCanonicalPath);
+
+                    if (!watchedDirectories.contains(parentDirPath)) {
```
Comment (billti) [inline src/compiler/sys.ts]: So you add a directory watcher for every directory that contains files being watched? Seems like if we are already watching the directory containing `tsconfig.json`, and you can watch a directory recursively, why would you ever need to watch a subdirectory of the project root? (i.e. if you watch a parent dir recursively, you should never need to also watch a child dir).

File: src/compiler/sys.ts [hunk 21]
```diff
@@ -298,6 +298,55 @@ namespace ts {
...
+                        watchedDirectories.set(parentDirPath, _fs.watch(
+                            parentDirPath,
```
Comment (billti) [inline src/compiler/sys.ts]: The Node docs state "For example, watching files or directories on network file systems (NFS, SMB, etc.) often doesn't work reliably or at all. You can still use fs.watchFile, which uses stat polling, but it is slower and less reliable.". 

Do we detect this and fall back? (Is it even possible to?) If not, how will users know if they get in this state and get things working correctly? I believe we've definitely seen users log issues where they are opening projects off the network.

File: src/compiler/sys.ts (hunk 16 above)
Comment (vladima) [inline src/compiler/sys.ts]: also given that `getDirectoryPath` does not reshape its argument so `Path` should stay `Path` I think we can add an overload to `getDirectoryPath` to avoid redundant conversions: smth like this:
```ts
    export function getDirectoryPath(path: Path): Path;
    export function getDirectoryPath(path: string): string;
    export function getDirectoryPath(path: string): any {
        return path.substr(0, Math.max(getRootLength(path), path.lastIndexOf(directorySeparator)));
    }
```

File: src/compiler/sys.ts (hunk 19 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: I tested before that if not supported then the `recursive: true` would simply be ignored. The recursive directory watcher is used with `tsconfig.json` without files array, so that adding/removing files in the background would be detected. The plan for this feature at the time was to support Node v4 or later only, so I didn't differentiate with the cases with older Node version.

File: src/compiler/sys.ts (hunk 20 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: The recursive watcher is not used for inferred project (loose files without `tsconfig.json`), so it is not always available. Also this function `watchFile` might not always be associated with a project, therefore the design of it may not involve specifying a "project root".

Another concern mentioned by Vlad regarding recursive watchers was that the user might receive too many irrelevant notifications from file activities not watched.

File: src/compiler/sys.ts (hunk 19 above)
Comment (billti) [inline src/compiler/sys.ts]: I'm not sure i follow about the `plan to use the feature`. `watchDirectory` is a public API (exported on interface `System`). If when called, it's not going to be able to do what the API claims it does (via the `recursive` parameter`), then it should error.

Even if not a public API, it's a future bug waiting to happen if it ignores known failure scenarios based on assumptions about how it will be used. Please protect against it.

File: src/compiler/sys.ts (hunk 20 above)
Comment (billti) [inline src/compiler/sys.ts]: I'm not sure I follow. In the loose file scenario, do we ever watch folders, or just the loose files? (Or do we watch the folder also in case a `tsconfig.json` file is added)?

Per your below comment:

 > recursive directory watcher is used with `tsconfig.json` file without `files` array.

So then I assume we never add watchers to project root subdirs in this case? (Which is probably the most common case) What's the point if you are already watching the root dir recursively? Also, doesn't this contradict the concern above that:

> ...concern mentioned by Vlad regarding recursive watchers was that the user might receive too many irrelevant notifications from file activities not watched

If we are adding a recursive directory watcher on a `tsconfig.json` root (when a files array isn't specified), then seems either we have a problem based on this concern, or the concern is unfounded.

Comment (zhengbli) [inline src/compiler/sys.ts]: For loose files, we use non-recursive watchers for the current folder and upper level folders, only to detect added `tsconfig.json` files. E.g. if the loose file is `C:\Desktop\foo.ts`, folders being watched are `C:\` and `C:\Desktop`. And you are right that for configured project we don't have watchers for subdirs. Only one recursive watcher at the project root is used.

I agree that it is more efficient to re-use the watcher if it is already there, though the implementation requires unification of the `watchDirectory` and `watchFile` apis, which weren't talking to each other. It was done in my recent updates.

File: src/compiler/sys.ts [hunk 22]
```diff
@@ -297,6 +304,131 @@ namespace ts {
                 };
             }
 
+            function createWatchedFileSet() {
+                const dirWatchers = createFileMap<DirWatcher>();
+                const recursiveDirWatchers = createFileMap<DirWatcher>();
+                const fileWatcherCallbacks = createFileMap<FileWatcherCallback>();
```
Comment (vladima) [inline src/compiler/sys.ts]: as I see now we store one callback per file, a question: will this work?
```ts
const fileName = "/some/file";
ts.sys.watchFile(fileName, () => console.log(1));
ts.sys.watchFile(fileName, () => console.log(2));
```

File: src/compiler/sys.ts [hunk 23]
```diff
@@ -297,6 +304,131 @@ namespace ts {
...
+                    }
+                }
+
+                function addDirWatcher(dirPath: Path, recursive?: boolean): { watcher: DirWatcher, isRecursive: boolean } {
+                    let watchers: FileMap<DirWatcher>;
+                    const options: { persistent: boolean, recursive?: boolean } = { persistent: true };
+
+                    // Node 4.0 `fs.watch` function supports the "recursive" option on both OSX and Windows
+                    // (ref: https://github.com/nodejs/node/pull/2649 and https://github.com/Microsoft/TypeScript/issues/4643)
+                    if (isNode4OrLater() && recursive === true) {
```
Comment (vladima) [inline src/compiler/sys.ts]: what about Node 4+ on Linux? I guess we should fallback to polling

File: src/compiler/sys.ts [hunk 24]
```diff
@@ -297,6 +304,131 @@ namespace ts {
...
+                        }
+                    }
+                    return { watcher, watcherPath, isRecursive };
+                }
+
+                function addFile(fileName: string, callback: FileWatcherCallback): WatchedFile {
+                    const filePath = toPath(fileName, currentDirectory, getCanonicalPath);
+                    const { watcher } = findDirWatcherForFile(filePath);
+                    if (!watcher) {
+                        addDirWatcher(getDirectoryPath(filePath));
```
Comment (vladima) [inline src/compiler/sys.ts]: is it ok to throw away result of `addDirWatcher` call?

File: src/compiler/sys.ts [hunk 25]
```diff
@@ -297,6 +304,131 @@ namespace ts {
...
+
+                    // Node 4.0 `fs.watch` function supports the "recursive" option on both OSX and Windows
+                    // (ref: https://github.com/nodejs/node/pull/2649 and https://github.com/Microsoft/TypeScript/issues/4643)
+                    if (isNode4OrLater() && recursive === true) {
+                        if (recursiveDirWatchers.contains(dirPath)) {
+                            const watcher = recursiveDirWatchers.get(dirPath);
+                            watcher.referenceCount += 1;
+                            return { watcher, isRecursive: true };
+                        }
+                        watchers = recursiveDirWatchers;
```
Comment (vladima) [inline src/compiler/sys.ts]: not sure that I got this right: here we'll alias `recursiveDirWatchers` as `watchers` and then at the line 365 we'll put fresh watcher in `watchers` so it will end up in `recursiveDirWatchers` however on the next line we'll return `{ watcher, isRecursive: false}`. Since we are using value of  `isRecursive` to pick the map to delete the element it seems we'll use wrong set.

File: src/compiler/sys.ts (hunk 22 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: Ah it wouldn't work now. Maybe a file needs a list of callbacks. Will update later.

File: src/compiler/sys.ts (hunk 23 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: Node 4 on Linux doesn't support the `recursive` option, however `fs.watch` still works. Polling doesn't really solve the problem of recursively detecting changes though. The conservative way might be just ignore the `recursive` option and use a non-recursive one instead when detected Linux.

File: src/compiler/sys.ts (hunk 24 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: The returned `watcher` instance is not used. Would ignoring the returned results yield any side effects?

File: src/compiler/sys.ts (hunk 25 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: You are right, will correct soon. Thanks for pointing out

File: src/compiler/sys.ts (hunk 21 above)
Comment (zhengbli) [inline src/compiler/sys.ts]: We currently don't detect network file systems, and I didn't find a way for it to work. Though if there is a way, we could fallback to polling in that case. In addition, as the outcome of the `fs.watch` not working reliably is failing to detect file changes, it is hard for us to know when to report to users about this state, as we don't know the ground truth.

File: src/compiler/sys.ts (hunk 23 above)
Comment (vladima) [inline src/compiler/sys.ts]: bun in this case scenario: watching directory that has `tsconfig.json` will be silently broken on Linux since it will only watch one level?

Comment (zhengbli) [inline src/compiler/sys.ts]: Yes it wouldn't work. The alternative is to add non-recursive watchers on every sub-folder recursively, which might explode to too many watchers if the recursive watcher is set to an unfortunate place.  Polling doesn't reflect changes in sub-folders as well, therefore can't help with this.

Or in this case should we just return an error message to warn the user?

Comment (mihailik) [inline src/compiler/sys.ts]: Is it a regression? Unless I'm confused, tsc -watch used to work on Linux more or less OK.

Comment (zhengbli) [inline src/compiler/sys.ts]: What works today should still work. The case when it doesn't work on linux is when you have a `tsconfig.json` that doesn't contain a explicit `files` array, and `tsc -watch` wouldn't detect added/removed files in subfolders of the project root path, which I believe doesn't work now either.

File: src/compiler/sys.ts [hunk 26]
```diff
@@ -1,6 +1,9 @@
 /// <reference path="core.ts"/>
 
 namespace ts {
+    export type FileWatcherCallback = (path: string, removed?: boolean) => void;
+    export type DirWatcherCallback = (path: string) => void;
```
Comment (mhegazy) [inline src/compiler/sys.ts]: spell out "Dir" into "DirectoryWatcherCallback"

File: src/compiler/sys.ts [hunk 27]
```diff
@@ -23,14 +26,18 @@ namespace ts {
...
-        mtime: Date;
+        callback: FileWatcherCallback;
+        mtime?: Date;
     }
 
     export interface FileWatcher {
         close(): void;
     }
 
+    export interface DirWatcher extends FileWatcher {
```
Comment (mhegazy) [inline src/compiler/sys.ts]: DirectoryWatcher

File: src/compiler/sys.ts [hunk 28]
```diff
@@ -221,7 +228,7 @@ namespace ts {
 
             // average async stat takes about 30 microseconds
             // set chunk size to do 30 files in < 1 millisecond
-            function createWatchedFileSet(interval = 2500, chunkSize = 30) {
+            function createPollingWatchedFileSet(interval = 2500, chunkSize = 30) {
```
Comment (mhegazy) [inline src/compiler/sys.ts]: so why do we need this Polling one, why can not we just fall back to fs.watchFile?

Comment (zhengbli) [inline src/compiler/sys.ts]: Our polling mechanism is different from `fs.watchFile`. `fs.watchFile` polls each file independently, so if you got many files to watch, it might increase the work load a lot. In our approach, we poll a fixed number of files (`chunkSize`) each number, so if the `chunkSize` is 30 and you have 90 files to watch, the work load is still the same for each polling, only that changes will be detected after 3 interval time instead of just 1. This way we keep the polling work load consistent

**Comment by zhengbli** [comment]
After some offline discussion with @mhegazy, we decided that it would be easier not to mix the recursive watchers and non-recursive watchers together, because the logic for reference counting would be quite complex in that case. Therefore, I rolled back to the implementation with separate directory watchers and file watchers, which might have duplicated watchers for the same folder in some case, but the compatibility across platforms would be better, and the code would be more maintainable.

File: src/compiler/sys.ts [hunk 29]
```diff
@@ -297,6 +305,95 @@ namespace ts {
...
+                function removeFile(watchedFile: WatchedFile) {
+                    const filePath = toPath(watchedFile.fileName, currentDirectory, getCanonicalPath);
+                    if (fileWatcherCallbacks.contains(filePath)) {
+                        const newCallbacks = copyListRemovingItem(watchedFile.callback, fileWatcherCallbacks.get(filePath));
+                        if (newCallbacks.length === 0) {
+                            fileWatcherCallbacks.remove(filePath);
+                            const watchedDir = findWatchedDirForFile(filePath);
+                            if (watchedDir) {
+                                reduceDirWatcherRefCount(watchedDir);
+                            }
```
Comment (mhegazy) [inline src/compiler/sys.ts]: consider replacing these four lines with:
```ts
removeDirWatcher(getDirectoryPath(filePath));
```

File: src/compiler/sys.ts [hunk 30]
```diff
@@ -297,6 +305,95 @@ namespace ts {
...
+                function addFileWatcherCallback(filePath: Path, callback: FileWatcherCallback): void {
+                    if (fileWatcherCallbacks.contains(filePath)) {
+                        fileWatcherCallbacks.get(filePath).push(callback);
+                    }
+                    else {
+                        fileWatcherCallbacks.set(filePath, [callback]);
+                    }
+                }
+
+                function findWatchedDirForFile(filePath: Path): Path {
```
Comment (mhegazy) [inline src/compiler/sys.ts]: if we make the change to removeDirWatcher, we do not need this function.

**Comment by mhegazy** [comment]
:+1:
