### PR TITLE
fix: do not match MySymbol.import("mod")

### LINKED ISSUE #23359: Code `Quill.import('mod');` makes TS think it needs to `import('mod')`
The quill library has a static method called `import` on it's exported symbol, which is used like this:
```js
Quill.import('dependency');
```

These dependencies are not actually imports, they are [strings in a map](https://github.com/quilljs/quill/blob/df1d4e49a3ef6dddb2fc62dd3f5d843e464ae55e/core/quill.js#L27-L32). Unfortunately `ts.preProcessFile` thinks they are valid imports.
I tried fixing the issue, but there is some logic missing and I am unsure how to debug the test I added properly with me being able to look at the scanner state. Maybe someone can give me a hint on how to complete my fix in #23358, please?

**TypeScript Version:**  `master` (edcf08714515f2a9ff5cbe65f4e8c233c11582fa)

**Search Terms:** Quill, .import, static import, preprocessFiles

**Code**

```ts
Quill.import('delta');
```
see https://github.com/Microsoft/TypeScript/pull/23358/files#diff-fa5d406e8b31aa069cd80d9698ca0590R63

**Expected behavior:**
`Quill.import('delta');` is treated like any other code (a function call of the function `import` on a symbol `Quill`)

**Actual behavior:**
TS thinks this is a proper import a la `import('delta')`, ignoring the fact that there is a preceding `Quill.`.

**Playground Link:** See #23358

**Related Issues:**
 #23358

### PR DESCRIPTION
**Pull request by joscha**
The quill library has a static method called `import` on it's exported symbol, which is used like this:
```js
Quill.import('dependency');
```

These dependencies are not actually imports, they are [strings in a map](https://github.com/quilljs/quill/blob/df1d4e49a3ef6dddb2fc62dd3f5d843e464ae55e/core/quill.js#L27-L32). Unfortunately `ts.preProcessFile` thinks they are valid imports.
I tried fixing the issue, but there is some logic missing and I am unsure how to debug the test I added properly with me being able to look at the scanner state. Maybe someone can give me a hint on how to complete my fix, please?

- [ ] There is an associated issue that is labeled
  'Bug' or 'help wanted' or is in the Community milestone
- [x] Code is up-to-date with the `master` branch
- [x] You've successfully run `jake runtests` locally `[But the code fails, and I am unsure why]`
- [x] You've signed the CLA
- [x] There are new or updated unit tests validating the change

Fixes #23359

### CODE REVIEW

File: src/compiler/scanner.ts [hunk 1]
```diff
@@ -1469,6 +1471,7 @@ namespace ts {
                         pos++;
                         return token = SyntaxKind.MinusToken;
                     case CharacterCodes.dot:
+                        tokenFlags |= TokenFlags.PrecedingDot;
```
Comment (joscha) [inline src/compiler/scanner.ts]: this might need to move right before the `return` if we understand the flag to denote a single dot.

File: src/services/preProcess.ts [hunk 2]
```diff
@@ -78,7 +78,7 @@ namespace ts {
          */
         function tryConsumeImport(): boolean {
             let token = scanner.getToken();
-            if (token === SyntaxKind.ImportKeyword) {
+            if (token === SyntaxKind.ImportKeyword && !scanner.hasPrecedingDot()) {
```
Comment (mhegazy) [inline src/services/preProcess.ts]: do not think you need to change the scanner API to do this. this whole function is just a mini parser. it advances the scanner each time it needs to consume a token, so you can do it here, no need to change the scanner implementation.

Comment (joscha) [reply src/services/preProcess.ts]: Okay, sorry for my wording, I used `parser`, because you called it a `mini parser`. So flag in `nextToken` SGTY?

Comment (mhegazy) [reply src/services/preProcess.ts]: yeah. it is already keeping state, one more flag should not harm anyone.

Comment (joscha) [reply src/services/preProcess.ts]: Ok, will give it a spin 👍

Comment (joscha) [reply src/services/preProcess.ts]: changes in ee429ef, but for some reason it doesn't work as expected. I am not even sure if the code is run, as I can't figure out from the docs on how to debug the tests or use the watch mode. Plus, `process.stdout.write` and `console.log` are not available either, so I am unsure on how to debug this - any pointers @mhegazy?

File: src/services/preProcess.ts [hunk 3]
```diff
@@ -25,6 +26,7 @@ namespace ts {
             else if (token === SyntaxKind.CloseBraceToken) {
                 braceNesting--;
             }
+            lastTokenWasDot = token === SyntaxKind.DotToken;
```
Comment (mhegazy) [inline src/services/preProcess.ts]: should not this be before we consume the next token? this just says `token === SyntaxKind.DotToken`

**Comment by mhegazy** [comment]
For debugging, I just use `jake runtests-browser` and use the browser devtools to debug. you can also write a node module that imports typescript.js and calls preprocessfile on it.

**Comment by joscha** [comment]
Tests should go ✅ hopefully, PTAL @mhegazy

**Comment by joscha** [comment]
I don't really understand, the test passes locally:

mocha_tests_and_1__npm_test__node_

**Comment by joscha** [comment]
OK, got it, no hot-reload, need to restart after file-changes:

mocha_tests

**Comment by joscha** [comment]
didn't need to introduce more state after all @mhegazy - tests pass locally after a fresh build via `gulp clean && gulp runtests-browser --browser=chrome --tests=non-imports`, hopefully CI will back me up this time 🤞 😬

File: src/services/preProcess.ts [hunk 4]
```diff
@@ -13,20 +13,20 @@ namespace ts {
         const importedFiles: FileReference[] = [];
         let ambientExternalModules: { ref: FileReference, depth: number }[];
         let braceNesting = 0;
-        let lastTokenWasDot = false;
+        let lastToken: SyntaxKind = null;
```
Comment (mhegazy) [inline src/services/preProcess.ts]: do not use `null`. `undefined` (or unintialized) is what we have used throughout the code base.

File: src/services/preProcess.ts [hunk 5]
```diff
@@ -293,10 +293,18 @@ namespace ts {
...
+            // Do not look for:
+            //    AnySymbol.import("mod")
+
             while (true) {
-                if (scanner.getToken() === SyntaxKind.EndOfFileToken) {
+                const token = scanner.getToken();
+                if (token === SyntaxKind.EndOfFileToken) {
                     break;
                 }
+                if (token === SyntaxKind.DotToken) {
```
Comment (mhegazy) [inline src/services/preProcess.ts]: what about `a.b.import`?

Comment (joscha) [reply src/services/preProcess.ts]: Should still work, because the next token is a literal, which means that it will go into the else came - I will add a test!

File: src/services/preProcess.ts (hunk 4 above)
Comment (joscha) [reply src/services/preProcess.ts]: Yep, I saw, the linter yelled at me :)

File: src/services/preProcess.ts (hunk 5 above)
Comment (joscha) [reply src/services/preProcess.ts]: 4dc9db1e70

File: src/services/preProcess.ts [hunk 6]
```diff
@@ -12,20 +12,25 @@ namespace ts {
...
+        let currentToken: SyntaxKind;
         let braceNesting = 0;
         // assume that text represent an external module if it contains at least one top level import/export
         // ambient modules that are found inside external modules are interpreted as module augmentations
         let externalModule = false;
 
         function nextToken() {
-            const token = scanner.scan();
-            if (token === SyntaxKind.OpenBraceToken) {
+            if (currentToken) {
```
Comment (mhegazy) [inline src/services/preProcess.ts]: do not think you need this check.

**Comment by mhegazy** [comment]
thanks @joscha!
