### PR TITLE
fix(60375): Parameter inlay hint is incorrect when function has a this type

### LINKED ISSUE #60375: Parameter inlay hint is incorrect when function has a `this ` type
### 🔎 Search Terms

inlay hint this

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it requires changing TypeScript version in Visual Studio Code

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQAoAoeeMKCCAIyjAGsAueQqZ1ZAW2pBgBp41ZgGcMMLKgDmASngBeAHzwAbjizBi05qvUBuYsUREU6bHhYYAFlmHsuPfvCgDqsgN7wAvtP1A

### 💻 Code

```ts
declare function fn(
  callback: (a: number, b: string) => void
): void;

fn(function (this: number, a, b) { });

```

### 🙁 Actual behavior

Inlay hint on parameter `a` shows `:string`, but it's actually a `number`:

Image

And inlay hint for `b` is missing

### 🙂 Expected behavior

Should display `a: number, b: string`

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #60375

### CODE REVIEW

File: src/services/inlayHints.ts [hunk 1]
```diff
@@ -437,24 +438,26 @@ export function provideInlayHints(context: InlayHintsContext): InlayHint[] {
...
-                continue;
+        let pos = 0;
+        for (const param of node.parameters) {
+            if (isHintableDeclaration(param)) {
+                addParameterTypeHint(param, parameterIsThisKeyword(param) ? signature.thisParameter : signature.parameters[pos]);
+                if (parameterIsThisKeyword(param)) {
+                    continue;
+                }
             }
+            pos++;
```
Comment (jakebailey) [inline src/services/inlayHints.ts:449]:
```suggestion    
            }
            if (parameterIsThisKeyword(param)) {
                continue;
            }
            pos++;
```

Something like this feels better to me; saves me having to think about whether or not `isHintableDeclaration` will end up false and then we get off by one errors.

Comment (a-tarasyuk) [reply src/services/inlayHints.ts]: Oke, I've changed. Thanks

**Review by jakebailey — APPROVED** [review]
