### PR TITLE
[Master] wip - fix incremental parsing with dynamic import

### LINKED ISSUE #16384: incomplete import statement causes assert in parser:
source

```ts
var x = import(

```
assert:

```txt
 	fail [TypeScript Non Blocking Syntactic Feature Thread_0] Line 3487	Script
	assert [TypeScript Non Blocking Syntactic Feature Thread_0] Line 3482	Script
 	parseUpdateExpression [TypeScript Non Blocking Syntactic Feature Thread_0] Line 19066	Script
 	parseUnaryExpressionOrHigher [TypeScript Non Blocking Syntactic Feature Thread_0] Line 18938	Script
 	parseBinaryExpressionOrHigher [TypeScript Non Blocking Syntactic Feature Thread_0] Line 18755	Script
 	parseAssignmentExpressionOrHigher [TypeScript Non Blocking Syntactic Feature Thread_0] Line 18421	Script
 	parseInitializer [TypeScript Non Blocking Syntactic Feature Thread_0] Line 18380	Script
 	parseVariableDeclaration [TypeScript Non Blocking Syntactic Feature Thread_0] Line 20308	Script
 	parseListElement [TypeScript Non Blocking Syntactic Feature Thread_0] Line 17213	Script
 	parseDelimitedList [TypeScript Non Blocking Syntactic Feature Thread_0] Line 17496	Script
 	parseVariableDeclarationList [TypeScript Non Blocking Syntactic Feature Thread_0] Line 20342	Script
 	parseVariableStatement [TypeScript Non Blocking Syntactic Feature Thread_0] Line 20354	Script
 	parseStatement [TypeScript Non Blocking Syntactic Feature Thread_0] Line 20128	Script
 	parseListElement [TypeScript Non Blocking Syntactic Feature Thread_0] Line 17213	Script
 	parseList [TypeScript Non Blocking Syntactic Feature Thread_0] Line 17196	Script
 	parseSourceFileWorker [TypeScript Non Blocking Syntactic Feature Thread_0] Line 16485	Script
 	parseSourceFile [TypeScript Non Blocking Syntactic Feature Thread_0] Line 16429	Script
 	updateSourceFile [TypeScript Non Blocking Syntactic Feature Thread_0] Line 22060	Script
 	updateSourceFile [TypeScript Non Blocking Syntactic Feature Thread_0] Line 16304	Script
 	updateLanguageServiceSourceFile [TypeScript Non Blocking Syntactic Feature Thread_0] Line 88855	Script
 	SyntaxTreeCache.prototype.getCurrentSourceFile [TypeScript Non Blocking Syntactic Feature Thread_0] Line 88800	Script
 	getBraceMatchingAtPosition [TypeScript Non Blocking Syntactic Feature Thread_0] Line 89430	Script
 	Anonymous function [TypeScript Non Blocking Syntactic Feature Thread_0] Line 90951	Script
 	simpleForwardCall [TypeScript Non Blocking Syntactic Feature Thread_0] Line 90736	Script
 	forwardCall [TypeScript Non Blocking Syntactic Feature Thread_0] Line 90755	Script
 	forwardJSONCall [TypeScript Non Blocking Syntactic Feature Thread_0] Line 90751	Script
 	LanguageServiceShimObject.prototype.forwardJSONCall [TypeScript Non Blocking Syntactic Feature Thread_0] Line 90802	Script
 	LanguageServiceShimObject.prototype.getBraceMatchingAtPosition [TypeScript Non Blocking Syntactic Feature Thread_0] Line 90951	Script

```

### PR DESCRIPTION
**Pull request by yuit**
Fix #16384

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -802,6 +802,10 @@ namespace ts {
                         // moduleAugmentations has changed
                         oldProgram.structureIsReused = StructureIsReused.SafeModules;
                     }
+                    if ((oldSourceFile.flags & NodeFlags.PossiblyContainsDynamicImport) !== (newSourceFile.flags & NodeFlags.PossiblyContainsDynamicImport)) {
+                        // dynamicImport has changed
+                        oldProgram.structureIsReused = StructureIsReused.SafeModules;
```
Comment (yuit) [inline src/compiler/program.ts]: I am still not sure whether this should be StructureIsReused.Not

**Comment by mhegazy** [comment]
@sandersn can you please review this change
