### PR TITLE
Fix uncalled function check usage detection for && expressions

### LINKED ISSUE #49155: Uncalled function in binary expression not silenced by body usage
Found in #49142:

```ts
declare let isActive: boolean;
declare let onChange: () => void;

if (!isActive && onChange) onChange();
```

Expected: no error because `onChange()` is used in the conditional body.
Actual: always-truthy error in the `if` condition.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #49155

I believe we didn't analyze this pattern for uncalled functions at all until #42835, and this case was just never tested.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test faster

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.7

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -38001,7 +38001,7 @@ namespace ts {
                     const childSymbol = getSymbolAtLocation(childNode);
                     if (childSymbol && childSymbol === testedSymbol) {
                         // If the test was a simple identifier, the above check is sufficient
-                        if (isIdentifier(expr)) {
+                        if (isIdentifier(expr) || isIdentifier(testedNode) && isBinaryExpression(testedNode.parent)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:38004]: What doesn't work if you just rewrite this as

```suggestion
                        if (isIdentifier(testedNode) && isBinaryExpression(testedNode.parent)) {
```

Comment (andrewbranch) [reply src/compiler/checker.ts:38004]: `if (onChange) onChange()`
