### PR TITLE
Fix completion disappear after a property declaration with a private modifier

### LINKED ISSUE #30290: Autocompletion in Classes when Implementing an Interface after Initial Fields
**TypeScript Version:**  3.3.1

**Search Terms:** Refactoring, Interface Implementation Autocompletion

**Code**
```ts
interface X {
    bla: string;
}
class Y implements X {
    // autocomplete here (1)
	private readonly blub = "";
    // autocomplete here (2)
}
```
**Expected behavior:**
When autocompleting at 1 in vscode, is suggests the member `foo`.
When autocompleting at 2 in vscode, is suggests the member `foo`.

**Actual behavior:**
When autocompleting at 1 in vscode, is suggests the member `foo`.
When autocompleting at 2 in vscode, is suggests nothing.

image

image

[Playground link](https://www.typescriptlang.org/play/#src=interface%20X%20%7B%0D%0A%20%20%20%20bla%3A%20string%3B%0D%0A%7D%0D%0Aclass%20Y%20implements%20X%20%7B%0D%0A%20%20%20%20%2F%2F%20autocomplete%20here%20(1)%0D%0A%09private%20readonly%20blub%20%3D%20%22%22%3B%0D%0A%20%20%20%20%2F%2F%20autocomplete%20here%20(2)%0D%0A%7D%0D%0A)

It works however, when `blub` is not private.

### PR DESCRIPTION
**Pull request by fuafa**
Fix class member completion disappear after a property declaration with a private modifier.

Fixes #30290

### CODE REVIEW

**Comment by fuafa** [comment]
Hi, @orta , Thanks for your review, any update on this?

File: src/services/completions.ts [hunk 1]
```diff
@@ -1566,7 +1566,7 @@ namespace ts.Completions {
             // If you're in an interface you don't want to repeat things from super-interface. So just stop here.
             if (!isClassLike(decl)) return GlobalsSearch.Success;
 
-            const classElement = contextToken.parent;
+            const classElement = contextToken.kind === SyntaxKind.SemicolonToken ? contextToken.parent.parent : contextToken.parent;
```
Comment (DanielRosenwasser) [inline src/services/completions.ts]: Is this the right fix? I get the sense that `contextToken.parent.parent` isn't actually a useful node, since the point of the check is simply to do nothing if you're not in the middle of the current class element.

Comment (fuafa) [reply src/services/completions.ts]: But the `contextToken.parent.parent` is a `ClassDeclaration` when `context.kind === SyntaxKind.SemicolonToken`. What I attempt to do is making the /\*1\*/ and /\*2\*/ should be in the same context.
```ts
class C {
	/*1*/ // `contextToken.parent` is `ClassDeclaration`
	private a = 1;
	/*2*/ // `contextToken.parent.parent` is `ClassDeclaration`
}
```
Do I miss something else?
