### PR TITLE
JSDoc Instantiation Fixes

### LINKED ISSUE #17377: Crash when JS Doc comment contains uninstantiable type
**TypeScript Version:** 2.5.0 & 2.4.2

**Code**

While compiling my angular 4 project, after upgrading typescript to 2.4.2, I found an error that I could not identify the source of. I avoided the error by reverting to 2.3.4.

Here's the error and stack trace for 2.5.0: 

```
/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:39449
                        var typeParameters = symbol.flags & 524288 /* TypeAlias */ ? getSymbolLinks(symbol).typeParameters : type.target.localTypeParameters;
                                                                                                                                        ^
TypeError: Cannot read property 'localTypeParameters' of undefined
    at checkTypeReferenceNode (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:39449:137)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42629:28)
    at checkVariableLikeDeclaration (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:40735:13)
    at checkParameter (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:38903:13)
    at Object.forEach (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:1496:30)
    at checkSignatureDeclaration (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:39044:16)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42651:21)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42663:28)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42649:28)
    at checkJSDocComment (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:40244:21)
```

I would have no problem creating a fiddle that shows the minimum case to trigger this, but I haven't been able to decipher what code is causing this because I don't understand how to extract a line number from typescript, even while inspecting the code in a debugger. Thanks. 

**Expected behavior:**
Typescript should not error in a way where I can't see what file or code snippet is causing an error. 
**Actual behavior:**
If there is an error, the node that causes this issue should be explained in a somewhat human readable way.

### LINKED ISSUE #17383: Crash in checkTypeReferenceNode when JSDoc tries to instantiate non-generic
Found when trying to reverse engineer a repro for #17377

```ts
/**
 * @param {<T>(m: Boolean<T>) => string} somebody
 */
function sayHello(somebody) {
    alert('Hello ' + somebody);
}
```

```
C:\github\TypeScript\built\local\tsc.js:69844
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at checkTypeReferenceNode (C:\github\TypeScript\built\local\tsc.js:39426:52)
    at checkSourceElement (C:\github\TypeScript\built\local\tsc.js:42606:28)
    at checkVariableLikeDeclaration (C:\github\TypeScript\built\local\tsc.js:40712:13)
    at checkParameter (C:\github\TypeScript\built\local\tsc.js:38879:13)
    at Object.forEach (C:\github\TypeScript\built\local\tsc.js:1463:30)
    at checkSignatureDeclaration (C:\github\TypeScript\built\local\tsc.js:39021:16)
    at checkSourceElement (C:\github\TypeScript\built\local\tsc.js:42594:28)
    at checkSourceElement (C:\github\TypeScript\built\local\tsc.js:42640:28)
    at checkSourceElement (C:\github\TypeScript\built\local\tsc.js:42626:28)
    at checkJSDocComment (C:\github\TypeScript\built\local\tsc.js:40221:21)
```

### LINKED ISSUE #17525: Crash in checkTypeReferenceNode deep inside checkJSDoc on @next
**TypeScript Version:**  2.5.0-dev.20170727

**Stack trace**

```
.../node_modules/typescript/lib/tsc.js:55939
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at checkTypeReferenceNode (.../node_modules/typescript/lib/tsc.js:32628:52)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35245:28)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35278:28)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35265:28)
    at checkJSDocComment (.../node_modules/typescript/lib/tsc.js:33243:21)
    at checkSourceElement (.../node_modules/typescript/lib/tsc.js:35263:28)
    at Object.forEach (.../node_modules/typescript/lib/tsc.js:267:30)
    at checkJSDoc (.../node_modules/typescript/lib/tsc.js:33237:16)
    at checkFunctionOrMethodDeclaration (.../node_modules/typescript/lib/tsc.js:33248:13)
    at checkFunctionDeclaration (.../node_modules/typescript/lib/tsc.js:33224:17)
```

The value of `getNodeLinks(node)` is `{ flags: 0, resolvedSymbol: undefined, resolvedType: Type }`. Calling `typeToString()` on the `resolvedType` produces `any[]`. The crash is caused through unconditionally accessing `resolvedSymbol.flags`.

**Code**

The crash seems to be caused when trying to parse `chai` or `chai/core/assertions.js`, as the `node.parent.parent.parent.comment` is this:

```
### .oneOf(list[, msg])

Asserts that the target is a member of the given array `list`. However,
it's often best to assert that the target is equal to its expected value.

     expect(1).to.equal(1); // Recommended
     expect(1).to.be.oneOf([1, 2, 3]); // Not recommended

Comparisons are performed using strict (`===`) equality.

Add `.not` earlier in the chain to negate `.oneOf`.

     expect(1).to.equal(1); // Recommended
     expect(1).to.not.be.oneOf([2, 3, 4]); // Not recommended

`.oneOf` accepts an optional `msg` argument which is a custom error message
to show when the assertion fails. The message can also be given as the
second argument to `expect`.

     expect(1).to.be.oneOf([2, 3, 4], 'nooo why fail??');
     expect(1, 'nooo why fail??').to.be.oneOf([2, 3, 4]);
```

Given this, I suspect that the crashing line is `@param {Array<*>} list` in the jsdoc comment.

---

This crash does not seem to happen with 2.4.2. Installing `@types/chai` also works around the crash.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #17383. - We now assume that if a symbol does not exist, then we found a builtin, but tried to instantiate it, which does not work.
Fixes #17377. - We now assume that instantiation can fail (ie, if the type doesn't exist as a type) and only look up the type arguments if instantiation was a success.
Fixes #17525. - We now consider `*` the potential start of a type.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18592,6 +18592,11 @@ namespace ts {
                     forEach(node.typeArguments, checkSourceElement);
                     if (produceDiagnostics) {
                         const symbol = getNodeLinks(node).resolvedSymbol;
+                        if (!symbol) {
+                            // There is no resolved symbol cached if the type resolved to a builtin via jsdoc type reference resolution, none of which are generic when they have no associated symbol
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Wrap comment, jsdoc -> JSDoc

Give a specific example of what you mean by JSDoc type reference resolution (e.g. a snippet of when this can happen)

**Comment by Kovensky** [comment]
This same crash is also happening in a snippet that has `{Array<*>}` as its type, which IIUC _is_ supposed to be generic.

See https://github.com/Microsoft/TypeScript/issues/17525

**Comment by weswigham** [comment]
@rbuckton It prevents it from throwing, but doesn't give it the correct behavior. We seem to be parsing `@param {Array<*>} list` as a parameter tag with type `Array`, no type arguments, and a comment on the type of `>} list`. The root issue with that scenario would appear to be in the parser, not here. I'll fix it separately.

**Comment by RyanCavanaugh** [comment]
I think we have three different repros on this, it'd be good to have all of them in the TC

**Comment by weswigham** [comment]
I've also bundled a fix for #17377, which was actually another issue which manifested as a crash on the same line. We assumed that if there was no resolved symbol that we successfully instantiated the type, which is, of course, predicated on the type being instantiable; which in erroneous cases (such as the example), it is not.

**Comment by weswigham** [comment]
And now this fixes #17525, since they were all hidden behind a crash on the same line.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -18592,7 +18592,17 @@ namespace ts {
...
-                        const typeParameters = symbol.flags & SymbolFlags.TypeAlias ? getSymbolLinks(symbol).typeParameters : (<TypeReference>type).target.localTypeParameters;
+                        if (!symbol) {
+                            // There is no resolved symbol cached if the type resolved to a builtin
+                            // via JSDoc type reference resolution (eg, Boolean became boolean), none
+                            // of which are generic when they have no associated symbol
+                            error(node, Diagnostics.Type_0_is_not_generic, typeToString(type));
+                            return;
+                        }
+                        let typeParameters = symbol.flags & SymbolFlags.TypeAlias && getSymbolLinks(symbol).typeParameters;
+                        if (!typeParameters && getObjectFlags(type) & ObjectFlags.Reference) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: this check for `objectFlags.Reference` is new. What if it's false? Won't you still see a crash? When could it be false?

Comment (weswigham) [inline src/compiler/checker.ts]: Previously it was blindly assumed that if it wasn't a type alias, that it must be a type reference. This is not the case - it can just be erroneous (since we just mark a lookup error and return the type for the alternate meaning if the lookup fails); so we must check that we have a type reference before treating the type as such.
