### PR TITLE
Prevent detached diagnostics from running off the end of the file

### LINKED ISSUE #55296: `attachFileToDiagnostics`: Debug Failure crash
### 🔎 Search Terms

Hi TypeScript team,

In an ongoing effort to secure the JS/TS ecosystem, we integrated the TypeScript project into [Google's OSS-Fuzz project recently](https://github.com/google/oss-fuzz/tree/92cbef824dc66722e3e50eca0069e2461f6d6b91/projects/typescript) with our JS/TS fuzzer [Jazzer.js](https://github.com/CodeIntelligenceTesting/jazzer.js).

Looking at the reports, it seems we were able to find another reproducer for what seems to be related to #46364, #44051, and #43832. 

This bug has been found when building TypeScript from the main branch and running the `fuzz_compiler.js` [link](https://github.com/google/oss-fuzz/blob/92cbef824dc66722e3e50eca0069e2461f6d6b91/projects/typescript/fuzz_compiler.js) on it. 

I attached a PoC below that isolates the issue to the call to `ts.createSourceFile(fileName, fileContent, ts.ScriptTarget.Latest);`.

Happy to answer any questions and also discuss the used APIs.

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

_No response_

### 💻 Code

Here's a quick JS reproducer.

```js
const fs = require("fs");
const ts = require("typescript");

const ignored = [
  "is not a function"
];


class StringConsumer {
  constructor(filename) {
    if (filename) {

      this.data = fs.readFileSync(filename); // read file into byte buffer
    } else {
      this.data = Buffer.from([
        0x75, 0x40, 0x00, 0x6d, 0xc0, 0xc0, 0xbc, 0x28,
        0xfb, 0x70, 0xdb, 0xdb, 0xfb, 0x6d, 0x00, 0xdb,
        0x6f, 0x72, 0x74, 0x28, 0x40, 0xbc, 0xdb, 0xdb,
        0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x28, 0x6f,
        0x62, 0x6a, 0x75, 0x32, 0x63, 0x37, 0x37, 0x2c
      ]);
    }
    this.dataPtr = 0; // start index
    this._remainingBytes = this.data.length;
  }

  consumeString(maxLength, encoding = "ascii") {
    if (maxLength < 0) throw new Error("maxLength must be non-negative");
    let result;
    const arrayLength = Math.min(maxLength, this._remainingBytes);

    result = this.data.toString(encoding, this.dataPtr, this.dataPtr + arrayLength);

    this.dataPtr += arrayLength;
    this._remainingBytes -= arrayLength;

    return result;
  }
}

try {
  const provider = new StringConsumer();
  const fileName = provider.consumeString(10) + ".ts";
  const filePath = provider.consumeString(10) + "/" + fileName;
  const fileContent = provider.consumeString(100);
  console.log("fileName", fileName);
  console.log("filePath", filePath);
  console.log("fileContent", fileContent);

  ts.createSourceFile(fileName, fileContent, ts.ScriptTarget.Latest);
} catch (error) {
  if (!ignoredError(error)) {
    throw error;
  }
}

function ignoredError(error) {
  return !!ignored.find((message) => error.message.indexOf(message) !== -1);
}

```

### 🙁 Actual behavior

```shell
node poc.js
fileName u@m@@<({p.ts
filePath [[{m[ort(/u@m@@<({p.ts
fileContent @<[[import(obju2c77,
/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/poc.js:53
    throw error;
    ^

Error: Debug Failure. Expected 21 <= 20
    at attachFileToDiagnostic (/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/node_modules/typescript/lib/typescript.js:17846:17)
    at attachFileToDiagnostics (/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/node_modules/typescript/lib/typescript.js:17858:36)
    at parseSourceFileWorker (/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/node_modules/typescript/lib/typescript.js:28877:41)
    at Object.parseSourceFile (/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/node_modules/typescript/lib/typescript.js:28700:26)
    at Object.createSourceFile (/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/node_modules/typescript/lib/typescript.js:27885:23)
    at Object.<anonymous> (/Users/ci/Git/work/oss-fuzz-onboarding-projects/TypeScript/poc.js:50:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)

Node.js v18.16.0
```

### 🙂 Expected behavior

I assume not crash the Node.js runtime as is with the debug assertion?

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #55296

This is similar to #52450 and #53674; we can create diagnostics with hardcoded range lengths, but if the parse error starts at the end of the file, we'll crash.

I could band-aid this by special casing the one crash, but as you can see in the change, we have quite a few other places which assume it's okay to use a `length=1` diagnostic, when it's possible that it may not work.

So, just set the length to the maximum available (or zero) when this happens.

To make this more obvious, I've restructured things a little so that we check the ranges earlier. The stack trace in #55296 happens late because the diagnostics weren't checked until they were finally attached to the file, after parse was complete. It's possible that I could find a different way to do this that doesn't look so noisy, but I feel like this is more robust.

Realistically, I could just move `createDetachedDiagnostic` into `parser.ts`; it's only used there so that'd avoid some parameters. But, all of its related helpers are still in this utilities file.

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -8152,8 +8149,12 @@ export function getLocaleSpecificMessage(message: DiagnosticMessage) {
 }
 
 /** @internal */
-export function createDetachedDiagnostic(fileName: string, start: number, length: number, message: DiagnosticMessage, ...args: DiagnosticArguments): DiagnosticWithDetachedLocation {
-    assertDiagnosticLocation(/*file*/ undefined, start, length);
+export function createDetachedDiagnostic(fileName: string, sourceText: string, start: number, length: number, message: DiagnosticMessage, ...args: DiagnosticArguments): DiagnosticWithDetachedLocation {
+    if ((start + length) > sourceText.length) {
+        length = sourceText.length - start;
+    }
```
Comment (jakebailey) [inline src/compiler/utilities.ts:8155]: This is the actual fix.

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -2470,7 +2470,7 @@ namespace Parser {
         if (lastError) {
             addRelatedInfo(
                 lastError,
-                createDetachedDiagnostic(fileName, openPosition, 1, Diagnostics.The_parser_expected_to_find_a_1_to_match_the_0_token_here, tokenToString(openKind), tokenToString(closeKind))
+                createDetachedDiagnostic(fileName, sourceText, openPosition, 1, Diagnostics.The_parser_expected_to_find_a_1_to_match_the_0_token_here, tokenToString(openKind), tokenToString(closeKind))
```
Comment (jakebailey) [inline src/compiler/parser.ts:2473]: This set of three detached diagnostics are the trouble; `openPosition` can totally be at the end of the file.

**Review by andrewbranch — APPROVED** [review]
