### PR TITLE
Fix #4277: Ensure we are passing refEnd and not length to findSourceFile

### LINKED ISSUE #4277: Debug Failure. False expression: end must be the bounds of the file
Hi,

when developing on my laptop, I ran into the following error, when trying to compile a project using VS:

```
VSTSC(0,0): error : Debug Failure. False expression: end must be the bounds of the file. 1627 > 881
```

However, out of the blue, I now got the error on my primary development machine. I also get this issue when building using the commandline:

```
VSTSC : tsc.js(688, 17) JavaScript runtime error : Debug Failure. False expression: end must be the bounds of the file. 1627 > 881 [D:\Projekte\padsy\NodeJs\padsy_api\padsy_api.njsproj]
```

I currently try to get a full stacktrace, but no luck so far.

Getting a clean workspace/source files does not help. Using another new Windows user, doesn't help either :( .

Regards, Felix

### PR DESCRIPTION
**Pull request by mhegazy**
Fixes #4277

There was a confusion on the fifth argument to findSoruceFile, some places will send the refEnd, others will send the refLength. this will trigger an assert when writing the diagnostics if the refLength > file text length.

The fix is to ensure we are always calling it with the right argument, also added a more conservative check for empty refPos and refEnd to ensure diagnostic emit does not fail

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -411,8 +405,8 @@ namespace ts {
             }
 
             if (diagnostic) {
-                if (refFile) {
-                    diagnostics.add(createFileDiagnostic(refFile, start, length, diagnostic, ...diagnosticArgument));
+                if (refFile !== undefined && refEnd !== undefined && refPos !== undefined) {
```
Comment (DanielRosenwasser) [inline src/compiler/program.ts]: I think this may have been the cause of some issues I was having with "fancy" diagnostic reporting

File: src/compiler/program.ts [hunk 2]
```diff
@@ -473,8 +467,13 @@ namespace ts {
                 if (file && host.useCaseSensitiveFileNames()) {
                     let sourceFileName = useAbsolutePath ? getNormalizedAbsolutePath(file.fileName, host.getCurrentDirectory()) : file.fileName;
                     if (canonicalName !== sourceFileName) {
-                        diagnostics.add(createFileDiagnostic(refFile, refStart, refLength,
-                            Diagnostics.File_name_0_differs_from_already_included_file_name_1_only_in_casing, fileName, sourceFileName));
+                        if (refFile !== undefined && refPos !== undefined && refEnd !== undefined) {
```
Comment (DanielRosenwasser) [inline src/compiler/program.ts]: Make a helper function for this

**Comment by DanielRosenwasser** [comment]
I think this may have been the cause of some issues I was having with "fancy" diagnostic reporting. I'd like to see how it copes after this change.

**Comment by mhegazy** [comment]
@DanielRosenwasser any more comments?

File: src/compiler/program.ts (hunk 2 above)
Comment (mhegazy) [inline src/compiler/program.ts]: i thought about that, but this seems easier to read and a reminder why we are doing it this way.

**Comment by DanielRosenwasser** [comment]
:+1:
