### PR TITLE
Fix extract symbol crash on unterminated literals; don’t offer to extract `export = ...`

### LINKED ISSUE #32862: Error: Debug Failure. False expression: Token end is child end in 'processChildNode' during 'getCodeFixes'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.5.3
**VSCode version**: 1.37.0
**Command requested**: getCodeFixes
**Hitting sessions**: 413
**Five line hash**: 628aeb13f7f368b660f2c8b37938eec3
**Stack**:
```
    at processChildNode (tsserver.js:110681:34)
    at <anonymous> (tsserver.js:110628:21)
    at visitNode (tsserver.js:16634:24)
    at forEachChild (tsserver.js:16712:21)
    at processNode (tsserver.js:110627:20)
    at processChildNode (tsserver.js:110687:21)
    at processChildNodes (tsserver.js:110738:48)
    at <anonymous> (tsserver.js:110630:21)
    at visitNodes (tsserver.js:16639:24)
    at forEachChild (tsserver.js:16774:24)
    at processNode (tsserver.js:110627:20)
    at processChildNode (tsserver.js:110687:21)
    at <anonymous> (tsserver.js:110628:21)
    at visitNode (tsserver.js:16634:24)
    at forEachChild (tsserver.js:16699:21)
    at processNode (tsserver.js:110627:20)
    at processChildNode (tsserver.js:110687:21)
    at processChildNodes (tsserver.js:110738:48)
    at <anonymous> (tsserver.js:110630:21)
    at visitNodes (tsserver.js:16639:24)
    at forEachChild (tsserver.js:16761:21)
    at processNode (tsserver.js:110627:20)
    at formatSpanWorker (tsserver.js:110445:17)
    at <anonymous> (tsserver.js:110409:140)
    at getFormattingScanner (tsserver.js:109215:23)
    at formatNodeGivenIndentation (tsserver.js:110409:31)
    at getFormattedTextOfNode (tsserver.js:112413:45)
    at format (tsserver.js:112391:52)
    at computeNewText (tsserver.js:112394:23)
    at <anonymous> (tsserver.js:112364:89)
    at unknown (suppressed.js)
    at <anonymous> (tsserver.js:112363:50)
    at unknown (suppressed.js)
    at getTextChangesFromChanges (tsserver.js:112349:86)
    at ChangeTracker.getChanges (tsserver.js:112319:45)
    at ChangeTracker.with (tsserver.js:111862:32)
    at getActionForMethodDeclaration (tsserver.js:116036:60)
    at getCodeActions (tsserver.js:115833:48)
    at <anonymous> (tsserver.js:112847:121)
    at flatMap (tsserver.js:573:25)
    at getFixes (tsserver.js:112847:23)
    at <anonymous> (tsserver.js:122423:35)
    at flatMap (tsserver.js:573:25)
    at getCodeFixesAtPosition (tsserver.js:122421:23)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at Session.getCodeFixes (tsserver.js:131477:64)
    at _a.<computed> (tsserver.js:130227:61)
    at <anonymous> (tsserver.js:131671:88)
    at Session.executeWithRequestId (tsserver.js:131662:28)
    at Session.executeCommand (tsserver.js:131671:33)
    at Session.onMessage (tsserver.js:131693:35)
    at <anonymous> (tsserver.js:132984:27)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #32862, or at least, fixes one manifestation of it

As a bonus, also disables the refactor on export assignments, since that’s invalid.

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -562,10 +562,16 @@ namespace ts {
...
     }
 
-    export function getLiteralText(node: LiteralLikeNode, sourceFile: SourceFile, neverAsciiEscape: boolean | undefined, jsxAttributeEscape: boolean) {
+    export const enum GetLiteralTextFlags {
+        NeverAsciiEscape = 1 << 0,
+        JsxAttributeEscape = 1 << 1,
+        TerminateUnterminatedLiterals = 1 << 2,
+    }
+
+    export function getLiteralText(node: LiteralLikeNode, sourceFile: SourceFile, flags: GetLiteralTextFlags = 0) {
```
Comment (sheetalkamat) [inline src/compiler/utilities.ts:571]: Would suggest not to make flags as optional parameter
