### PR TITLE
fix(59463): Feature that displays method argument names inline does not correctly handle method overloading

### LINKED ISSUE #59463: Feature that displays method argument names inline does not correctly handle method overloading (so variable name is taken from bad overload, probably from the first method definition).
Type: <b>Bug</b>

When having code like this:
``` 
  public async cancelBooking(
    internalBookingId: number,
    company: Companies,
    dataStoreService: DataStoreService,
    bookingsService: BookingsService,
  ): Promise<void>;
  public async cancelBooking(
    booking: ExtendedBookingSystemBooking,
    company: Companies,
    dataStoreService: DataStoreService,
    bookingsService: BookingsService,
  ): Promise<void>;
  public async cancelBooking(
    booking: number | ExtendedBookingSystemBooking,
    company: Companies,
    dataStoreService: DataStoreService,
    bookingsService: BookingsService,
  ) {
    ...
  }
```
And then calling this method from other part in the code && using ExtendedBookingSystemBooking for the first argument, the inline method argument hinting shows "internalBookingId" as method argument name despite VSCode knows the second method definition is used (shows this correctly when hovering over the method call).

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 6.9.9-100.fc39.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|31.23GB (11.54GB free)|
|Process Argv|--crash-reporter-id 42f3b124-3ec4-47eb-9930-f9dae9c4e9d6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|3.0.10
vscode-eslint|dba|3.0.10
gitlens|eam|15.2.3
prettier-vscode|esb|10.4.0
auto-rename-tag|for|0.1.10
lintlens|ghm|7.5.0
copilot|Git|1.219.0
copilot-chat|Git|0.17.1
vscode-pull-request-github|Git|0.92.0
vscode-graphql|Gra|0.11.0
vscode-graphql-syntax|Gra|1.3.6
todo-tree|Gru|0.0.226
intellij-idea-keybindings|k--|1.7.2
vscode-speech|ms-|0.10.0
vscode-yaml|red|1.15.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31101459
pythonrstrctxtcf:31093870
wkspc-onlycs-t:31102394

```

</details>

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #59463

### CODE REVIEW

File: src/services/inlayHints.ts [hunk 1]
```diff
@@ -296,11 +295,8 @@ export function provideInlayHints(context: InlayHintsContext): InlayHint[] {
             return;
         }
 
-        const candidates: Signature[] = [];
-        const signature = checker.getResolvedSignatureForSignatureHelp(expr, candidates);
-        if (!signature || !candidates.length) {
-            return;
-        }
+        const signature = checker.getResolvedSignature(expr);
```
Comment (DanielRosenwasser) [inline src/services/inlayHints.ts:298]: The fact that this function is enough now and doesn't break tests is pretty surprising- I think it relates to some work @Andarist might've done here?

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Review by MariaSolOs — APPROVED** [review]

**Review by Sandra-Amina-Boss — COMMENTED** [review]
Ok

File: src/services/inlayHints.ts (hunk 1 above)
Comment (Sandra-Amina-Boss) [reply src/services/inlayHints.ts:298]: > The fact that this function is enough now and doesn't break tests is pretty surprising- I think it relates to some work @Andarist might've done here.

Comment (Andarist) [reply src/services/inlayHints.ts:298]: I think it's unrelated. I was working on some related-ish stuff at different layers. It might just be that this should have never been using `getResolvedSignatureForSignatureHelp`

If we consider this test case:

```ts
function overloadTest(first: string): unknown
function overloadTest(second: string, extra: boolean): unknown
function overloadTest(...arg: any[]) {}

overloadTest('str',)
```

We get `second` as the inlay hint for our argument but the overload that is successfully resolved is the first one. I think this one should give `first` as the inlay hint and that this PR might have fixed this. It would be good to add this as a new test case.

**Review by gabritto — APPROVED** [review]
