### PR TITLE
Fix trailing formatting edit when range ends mid-token

### LINKED ISSUE #50076: Format selection (and thus format-on-paste) causes destructive edits
Issue Type: <b>Bug</b>

Create a simple template string in a Javascript or Typescript file as below
```javascript
const TEST_STRING = `${TEST_VAR_1}, this is some text`; 
```

Copy any text and paste anywhere after the closing expression bracket "}". All text including the last "}" is deleted. 

In my example I've copied the word "TEST_STRING " by double clicking on it. I've tried pasting  just before the end back tick

```javascript
const TEST_STRING = `${TEST_VAR_1; 
```
If you press undo the expected initial result is shown.

```javascript
const TEST_STRING = `${TEST_VAR_1}, this is some textTEST_STRING`; 
```

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

Extensions: none

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #50076

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -439,12 +440,32 @@ namespace ts.formatting {
...
+            // Formatting edits happen by looking at pairs of contiguous tokens (see `processPair`),
+            // typically inserting or deleting whitespace between them. The recursive `processNode`
+            // logic above bails out as soon as it encounters a token that is beyond the end of the
+            // range we're supposed to format (or if we reach the end of the file). But this potentially
+            // leaves out an edit that would occur *inside* the requested range but cannot be discovered
+            // without looking at one token *beyond* the end of the range: consider the line `x = { }`
+            // with a selection from the beginning of the line to the space inside the curly braces,
+            // inclusive. We would expect a format-selection would delete the space (if rules apply),
+            // but in order to do that, we need to process the pair ["{", "}"], but we stopped processing
+            // just before getting there. This block handles this trailing edit.
```
Comment (andrewbranch) [inline src/services/formatting/formatting.ts:452]: This comment should have been included with #46875.

File: src/services/formatting/formatting.ts [hunk 2]
```diff
@@ -439,12 +440,32 @@ namespace ts.formatting {
...
+                // We need to check that tokenInfo and previousRange are contiguous: the `originalRange`
+                // may have ended in the middle of a token, which means we will have stopped formatting
+                // on that token, leaving `previousRange` pointing to the token before it, but already
+                // having moved the formatting scanner (where we just got `tokenInfo`) to the next token.
+                // If this happens, our supposed pair [previousRange, tokenInfo] actually straddles the
+                // token that intersects the end of the range we're supposed to format, so the pair will
+                // produce bogus edits if we try to `processPair`. Recall that the point of this logic is
+                // to perform a trailing edit at the end of the selection range: but there can be no valid
+                // edit in the middle of a token where the range ended, so if we have a non-contiguous
+                // pair here, we're already done and we can ignore it.
```
Comment (andrewbranch) [inline src/services/formatting/formatting.ts:468]: This comment describes the fix for this bug.

**Review by jakebailey — APPROVED** [review]
LGTM, I'm always suspicious of the `!` but they're at least consistent with the other side-effecty previous variables, so...

**Comment by andrewbranch** [comment]
Yeah, it’s correlated with the existence of `previousRange`.

File: src/services/formatting/formatting.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/services/formatting/formatting.ts:452]:
```suggestion
            // but in order to do that, we need to process the pair ["{", "}"].
            // This block handles this trailing edit by ensuring we continue processing.
            // the pair of tokens that the range intersects.
```

File: src/services/formatting/formatting.ts [hunk 3]
```diff
@@ -439,12 +440,32 @@ namespace ts.formatting {
...
+            // but in order to do that, we need to process the pair ["{", "}"], but we stopped processing
+            // just before getting there. This block handles this trailing edit.
             const tokenInfo =
                 formattingScanner.isOnEOF() ? formattingScanner.readEOFTokenRange() :
                 formattingScanner.isOnToken() ? formattingScanner.readTokenInfo(enclosingNode).token :
                 undefined;
 
-            if (tokenInfo) {
+            if (tokenInfo && tokenInfo.pos === previousRangeTriviaEnd!) {
+                // We need to check that tokenInfo and previousRange are contiguous: the `originalRange`
```
Comment (DanielRosenwasser) [inline src/services/formatting/formatting.ts:459]:
```suggestion
                // We need to check that previousRange and tokenInfo are contiguous: the `originalRange`
```

Comment (DanielRosenwasser) [inline src/services/formatting/formatting.ts:459]:
```suggestion
                // We need to check that previousRange and tokenInfo are contiguous since the `originalRange`
```

**Review by DanielRosenwasser — APPROVED** [review]
