### PR TITLE
fix rename cause import change wrongly

### LINKED ISSUE #38461: Rename folder in different case cause node imports changed wrongly.
**TypeScript Version:**  4.0.0-dev.20200509

**Search Terms:** tss getEditsForFileRename services import

**Code**

// @Filename: /a/b/file1.ts
////import { foo } from "foo";

// @Filename: /a/node_modules/foo/index.d.ts
////export const foo = 0;

use vscode to rename folder from "/a/b" to "/a/B", choose to update imports.

**Expected behavior:**
no change.

**Actual behavior:**
import changes from
`import { foo } from "foo";` to `import { foo } from "./node_modules/foo";` 

**Playground Link:** 
I could not find a way to use or trigger getEditsForFileRename function in Playground.

**Related Issues:** 
I did not find similar question.

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #38461

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
There is another choice to change src/services/getEditsForFileRename.ts rather than src/compiler/moduleSpecifiers.ts.
But I think this can prevent other issues in future.
Anyway, just tell me to change it if this is a bad choice in fact.

File: src/compiler/moduleSpecifiers.ts [hunk 1]
```diff
@@ -347,7 +347,8 @@ namespace ts.moduleSpecifiers {
         // Get a path that's relative to node_modules or the importing file's path
         // if node_modules folder is in this folder or any of its parent folders, no need to keep it.
         const pathToTopLevelNodeModules = getCanonicalFileName(moduleSpecifier.substring(0, parts.topLevelNodeModulesIndex));
-        if (!(startsWith(sourceDirectory, pathToTopLevelNodeModules) || globalTypingsCacheLocation && startsWith(getCanonicalFileName(globalTypingsCacheLocation), pathToTopLevelNodeModules))) {
+        const canonicalSourceDirectory = getCanonicalFileName(sourceDirectory);
+        if (!(startsWith(canonicalSourceDirectory, pathToTopLevelNodeModules) || globalTypingsCacheLocation && startsWith(getCanonicalFileName(globalTypingsCacheLocation), pathToTopLevelNodeModules))) {
```
Comment (sheetalkamat) [inline src/compiler/moduleSpecifiers.ts:351]: Wait this seems incorrect. `sourceDirectory` is already canonical path.
https://github.com/microsoft/TypeScript/pull/38462/files#diff-aa86ac6315ba3e1d25a9a1789f7f5a78L110

File: src/harness/vfsUtil.ts [hunk 2]
```diff
@@ -595,7 +595,10 @@ namespace vfs {
             if (existingNode) {
                 if (isDirectory(node)) {
                     if (!isDirectory(existingNode)) throw createIOError("ENOTDIR");
-                    if (this._getLinks(existingNode).size > 0) throw createIOError("ENOTEMPTY");
+                    // if both old and new arguments point to the same directory, just pass. So we could rename /src/a/1 to /src/A/1 in Win.
+                    // if not and the directory pointed by the new path is not empty, throw an error.
+                    // However, in the link in the description, it says: If the old argument points to the pathname of a file that is not a directory, the new argument shall not point to the pathname of a directory. If the link named by the new argument exists, it shall be removed and old renamed to new. In this case, a link named new shall remain visible to other threads throughout the renaming operation and refer either to the file referred to by new or old before the operation began. Write access permission is required for both the directory containing old and the directory containing new.
```
Comment (rbuckton) [inline src/harness/vfsUtil.ts:600]: This comment is too long to read easily in a PR. Please split this comment across multiple lines.

File: src/harness/vfsUtil.ts [hunk 3]
```diff
@@ -595,7 +595,10 @@ namespace vfs {
...
                     if (!isDirectory(existingNode)) throw createIOError("ENOTDIR");
-                    if (this._getLinks(existingNode).size > 0) throw createIOError("ENOTEMPTY");
+                    // if both old and new arguments point to the same directory, just pass. So we could rename /src/a/1 to /src/A/1 in Win.
+                    // if not and the directory pointed by the new path is not empty, throw an error.
+                    // However, in the link in the description, it says: If the old argument points to the pathname of a file that is not a directory, the new argument shall not point to the pathname of a directory. If the link named by the new argument exists, it shall be removed and old renamed to new. In this case, a link named new shall remain visible to other threads throughout the renaming operation and refer either to the file referred to by new or old before the operation began. Write access permission is required for both the directory containing old and the directory containing new.
+                    if (this.stringComparer(oldpath,newpath)!== 0 && this._getLinks(existingNode).size > 0) throw createIOError("ENOTEMPTY");
```
Comment (rbuckton) [inline src/harness/vfsUtil.ts:601]: nit, whitespace:
```suggestion
                    if (this.stringComparer(oldpath, newpath) !== 0 && this._getLinks(existingNode).size > 0) throw createIOError("ENOTEMPTY");
```

File: src/compiler/moduleSpecifiers.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/moduleSpecifiers.ts:351]: Since this is the only substantive change outside of tests in this PR, is there something we are doing incorrectly when computing `sourceDirectory`? If not, what does this PR change other than the VFS in the test harness and adding a test?

Comment (sheetalkamat) [reply src/compiler/moduleSpecifiers.ts:351]: I think we would need to diagnose why source directory is not canonical already instead.

Comment (ShuiRuTian) [reply src/compiler/moduleSpecifiers.ts:351]: https://github.com/microsoft/TypeScript/pull/38462#issuecomment-626487827
Would it be better to add comment to let users know it is their responsibility to make sure sourceDirectory canonical path?

File: src/harness/vfsUtil.ts (hunk 2 above)
Comment (ShuiRuTian) [reply src/harness/vfsUtil.ts:600]: I would remove it. 
And I want to discuss about this function (renameSync).
In  the link http://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html
It says
_If the old argument points to the pathname of a file that is not a directory, the new argument shall not point to the pathname of a directory. **If the link named by the new argument exists, it shall be removed and old renamed to new.** In this case, a link named new shall remain visible to other threads throughout the renaming operation and refer either to the file referred to by new or old before the operation began. Write access permission is required for both the directory containing old and the directory containing new._
But this function does not behave like this. My understanding is wrong or this is intended or somewhere need to fix?

File: src/services/getEditsForFileRename.ts [hunk 4]
```diff
@@ -126,8 +126,8 @@ namespace ts {
     ): void {
         const allFiles = program.getSourceFiles();
         for (const sourceFile of allFiles) {
-            const newFromOld = oldToNew(sourceFile.path) as Path;
-            const newImportFromPath = newFromOld !== undefined ? newFromOld : sourceFile.path;
+            const newFromOld = oldToNew(sourceFile.path);
```
Comment (sheetalkamat) [inline src/services/getEditsForFileRename.ts:129]: I think it should be `oldToNew(sourceFile.fileName)`

Comment (ShuiRuTian) [reply src/services/getEditsForFileRename.ts]: You are right. 
Keen insight!

**Comment by ShuiRuTian** [comment]
Friendly ping @rbuckton
