### PR TITLE
Fix inference for contextually typed parameters with initializers

### LINKED ISSUE #28816: literal function with structure spread can't be rightly inferred in function's generic type slot
**TypeScript Version:**  3.2.1

**Search Terms:**

strucutre spread + generic

**Code**

```ts
function id<T>(input: T): T { return input }

function getFoo ({ foo = 42 }) {
  return foo
}

const newGetFoo = id(getFoo)
const newGetFoo2 = id(function getFoo ({ foo = 42 }) {
  return foo
})
```

**Expected behavior:**

newGetFoo and newGetFoo2 should have the same signature

**Actual behavior:**

`newGetFoo` is:
```ts
({ foo }: {
    foo?: number | undefined;
}) => number
```

but `newGetFoo2` is
```ts
 ({ foo }: any) => number
```

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=function%20id%3CT%3E(input%3A%20T)%3A%20T%20%7B%20return%20input%20%7D%0A%0Afunction%20getFoo%20(%7B%20foo%20%3D%2042%20%7D)%20%7B%0A%20%20return%20foo%0A%7D%0A%0Aconst%20newGetFoo%20%3D%20id(getFoo)%0Aconst%20newGetFoo2%20%3D%20id(function%20getFoo%20(%7B%20foo%20%3D%2042%20%7D)%20%7B%0A%20%20return%20foo%0A%7D)%0A

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #28816.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5041,8 +5032,11 @@ namespace ts {
                 }
             }
 
-            // Use the type of the initializer expression if one is present
-            if (declaration.initializer) {
+            const isParameterOfContextuallyTypedFunction = declaration.kind === SyntaxKind.Parameter && getContextualType(<Expression>declaration.parent);
+
+            // Use the type of the initializer expression if one is present and the declaration is
+            // not a parameter of a contextually typed function
+            if (declaration.initializer && !isParameterOfContextuallyTypedFunction) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Wouldn't we rather write `declaration.initializer && !(declaration.kind === SyntaxKind.Parameter && getContextualType(<Expression>declaration.parent);)` so we only call `getContextualType` if we absolutely need need?

Comment (weswigham) [reply src/compiler/checker.ts]: Or, since it's used below, write
```ts
const needsShapeAndIsNotParameterOfContextuallyTypedFunction = (declaration.initializer || isBindingPattern(declaration.name)) && !(declaration.kind === SyntaxKind.Parameter && getContextualType(<Expression>declaration.parent));
```

File: tests/cases/compiler/contextuallyTypedParametersWithInitializers.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+// @declaration: true
+
+declare function id1<T>(input: T): T;
+declare function id2<T extends (x: any) => any>(input: T): T;
+declare function id3<T extends (x: { foo: any }) => any>(input: T): T;
+declare function id4<T extends (x: { foo?: number }) => any>(input: T): T;
+declare function id5<T extends (x?: number) => any>(input: T): T;
+
+const f10 = function ({ foo = 42 }) { return foo };
+const f11 = id1(function ({ foo = 42 }) { return foo });  // Implicit any error
```
Comment (weswigham) [inline tests/cases/compiler/contextuallyTypedParametersWithInitializers.ts]: Should we also have a fourslash test for each of these so we can have tests simulating hovering over the different parts in different orders?

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, possibly. The value is precomputed because I use it in two locations. But I supposed I could turn it into a function that we only call when appropriate.

File: tests/baselines/reference/contextuallyTypedParametersWithInitializers.errors.txt [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    declare function id1<T>(input: T): T;
+    declare function id2<T extends (x: any) => any>(input: T): T;
+    declare function id3<T extends (x: { foo: any }) => any>(input: T): T;
+    declare function id4<T extends (x: { foo?: number }) => any>(input: T): T;
+    declare function id5<T extends (x?: number) => any>(input: T): T;
+    
+    const f10 = function ({ foo = 42 }) { return foo };
+    const f11 = id1(function ({ foo = 42 }) { return foo });  // Implicit any error
+                              ~~~~~~~~~~~~
+!!! error TS7022: '{ foo = 42 }' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```
Comment (weswigham) [inline tests/baselines/reference/contextuallyTypedParametersWithInitializers.errors.txt]: How does this binding pattern circularly reference itself? o.O

Comment (ahejlsberg) [reply tests/baselines/reference/contextuallyTypedParametersWithInitializers.errors.txt]: Hmm, strange. This error is caused by declaration file emit, it only appears with `--declaration`. Have no idea why.

Comment (weswigham) [reply tests/baselines/reference/contextuallyTypedParametersWithInitializers.errors.txt]: `getEmitDeclarations`  causes us to conditionally `collectLinkedAliases` on exported names - but this is a binding pattern in an anonymous function expression, not an exported name... o.O

Comment (weswigham) [reply tests/baselines/reference/contextuallyTypedParametersWithInitializers.errors.txt]: Maybe we generate the error while looking up the type of the expression for emitting `declare const f11: something`? We marked `foo` as implicitly `any` within the checker, however did we propagate that up to the binding pattern as a whole?

Comment (ahejlsberg) [reply tests/baselines/reference/contextuallyTypedParametersWithInitializers.errors.txt]: The circularity error is caused by the parameter having itself as its contextual type. It's actually unrelated to this PR. For example, this causes the same error on `master`:

```ts
declare function id<T>(input: T): T;
const f1 = id(function ({ foo }) { return foo });
```
