### PR TITLE
Normalize effective constraint intersection before checking if source is a part of it

### LINKED ISSUE #49937: Type parameters constrained to type alias of generic class can't be used  with instanceof - TypeScript 4.8 regression
# Bug Report

### 🔎 Search Terms

generic type parameters type aliases generic classes instanceof 

### 🕗 Version & Regression Information

- This changed between versions 4.7.3 and 4.8-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta&ssl=15&ssc=1&pln=1&pc=1#code/PTAEEkDNQFQQwEYBsCmoCWBnUA7A9jqAOYo4oBO6AxqBeXuaACZ4rb4AuoeVVAruQBQTFFSRxyaMXEzZ4yFAGFxsgDwBlUAF5QcHAE8AfKFABvQSZMB9SOhRImALlDrBAX0GCUADwAODLg59XzR5VG1YRFRlGUwAbk9IPhwqDnQCUEgcVRhabw5SJjkolEMACjxnGABKMwtLSQ4BQjwMHEwOPSoUPGgwpRVsEFpyekZ0QgAWADoADndPEWlJUCoCDu4qkoTWiY6unr6SmNlQYZgACywMbDwAa1BPJ88gA)

### 💻 Code

```ts repro
// If Table is non generic error does not occur
declare class TableClass<S = any>  {
    _field: S
}

export type Table = TableClass;

function fn<T extends Table>(o: T) {
    return o instanceof TableClass // error in 4.8
}

declare const o: Table;
o instanceof TableClass // This is ok 
```

### 🙁 Actual behavior

`o instanceof TableClass` causes an error when `o` is typed as a generic type parameter constrained to `Table` but not when `o` is typed as `Table`. This behavior is different in 4.7 and 4.8. In 4.7 neither of these was an error.

### 🙂 Expected behavior

`o instanceof TableClass` is valid in both cases

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #49937

During relation checking, we end up with a source type of `TableClass<any> & T`. Because it's an intersection, we try relating the result of `getEffectiveConstraintOfIntersection(source)` against `target` to see if that succeeds.

`getEffectiveConstraintOfIntersection` produces an intersection of types and their contraints (the source type in this example is one such intersection). However, #49119 changed `getConstraintOfType` such that `getConstraintOfType(T)` is `Table`, not `TableClass<any>`, which I believe is correct.

But the caller of `getEffectiveConstraintOfIntersection` checks if the result contains the source type by exact equality. Since the source by this point has been normalized, equality will fail as the constraint is not yet normalized (which in this case would replace `Table` with `TableClass<any>`.

So, make sure that constraint is normalized.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this faster

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19434,7 +19434,7 @@ namespace ts {
                         // the type param can be compared with itself in the target (with the influence of its constraint to match other parts)
                         // For example, if `T extends 1 | 2` and `U extends 2 | 3` and we compare `T & U` to `T & U & (1 | 2 | 3)`
                         const constraint = getEffectiveConstraintOfIntersection(source.flags & TypeFlags.Intersection ? (source as IntersectionType).types: [source], !!(target.flags & TypeFlags.Union));
-                        if (constraint && everyType(constraint, c => c !== source)) { // Skip comparison if expansion contains the source itself
+                        if (constraint && everyType(constraint, c => !isTypeIdenticalTo(c, source))) { // Skip comparison if expansion contains the source itself
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply src/compiler/checker.ts:19437]: If I'm normalizing, I would probably just normalize `constraint`, but given there is work that `isRelatedTo` does before normalizing it itself, maybe that's not right.

[the remark this answers is not in the document]
Comment (jakebailey) [reply src/compiler/checker.ts]: I decided to just normalize the constraint; after following the code, there's no way that any of those early checks would apply, because they don't apply to intersections.

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -12118,7 +12118,7 @@ namespace ts {
                         }
                     }
                 }
-                return getIntersectionType(constraints);
+                return getNormalizedType(getIntersectionType(constraints), /*writing*/ false); // The source types were normalized; ensure the result is normalized too.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:12121]: the `writing` parameter has me a little suspicious here.

Side note, the comment makes this line a bit too long.

```suggestion
                // The source types were normalized; ensure the result is normalized too.
                return getNormalizedType(getIntersectionType(constraints), /*writing*/ false); 
```

Comment (jakebailey) [reply src/compiler/checker.ts:12121]: This function is only called on the source types in relation; this mirrors how the same function calls `getNormalizedType` on the source itself earlier. I had this instead at the one call site, but opted to stick it here because there is only one call site and it's shorter than:

```ts
let constraint = getEffectiveConstraintOfIntersection(source.flags & TypeFlags.Intersection ? (source as IntersectionType).types: [source], !!(target.flags & TypeFlags.Union));
if (constraint) {
    constraint = getNormalizedType(constraint, /*writing*/ false);
}
if (constraint && everyType(constraint, c => c !== source)) { // Skip comparison if expansion contains the source itself
    // ...
}
```

But, I am happy to do so.

Comment (jakebailey) [reply src/compiler/checker.ts:12121]: The other option is maybe to move all of those argument expressions into `getEffectiveConstraintOfIntersection` like

```ts
function getEffectiveConstraintOfIntersection(source: Type, target: Type) {
    const types = source.flags & TypeFlags.Intersection ? (source as IntersectionType).types: [source];
    const targetIsUnion = !!(target.flags & TypeFlags.Union);
    // ...
}
```

And then move it into the relation closure to make it obvious that this should only be used in this one place and not for another purpose?

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this

**Comment by jakebailey** [comment]
The bot's been acting up recently and doesn't seem to respond half the time.

Most of those are run above, if you want to see the results.

I'm happy to shift the code around if you want, of course.

**Comment by jakebailey** [comment]
Oh, no, the perf test absolutely did not run earlier, right.

**Comment by jakebailey** [comment]
@typescript-bot pack this
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Perf looks the same to my eye. Any opinions on where I do the normalization? Hoping to get this one in sooner rather than later just because it's causing so many problems in things like zod (and how bad it is to be allowing assignments of type variables bound by aliases to _any_ union type).

**Review by sandersn — APPROVED** [review]
Looks good to me, but @weswigham or @ahejlsberg should take a look too.

File: src/compiler/checker.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/checker.ts:12121]: FWIW the above is sort of what I'd prefer (accept `source` and `target`). Better yet, move `getEffectiveConstraintOfIntersection` down into relation to make it obvious what you are/aren't supposed to use it for, but the diff won't be followable.

**Review by ahejlsberg — APPROVED** [review]
This looks like a good fix. At some point we may want to do some deeper thinking about normalizing types into forms that don't require the additional `getEffectiveConstraintOfIntersection` check.

**Comment by jakebailey** [comment]
Alright, I'll leave this as-is, then.

File: src/compiler/checker.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/checker.ts:12121]: I've moved the comment per Daniel's comment.
