### PR TITLE
Filter out global keywords of UMD module export declarations in completion providing auto import suggestions

### LINKED ISSUE #41761: Missing auto import suggestions for UMD modules such as `classnames`
- VSCode Version: 1.51.1
- OS Version: 11.0.1

Steps to Reproduce:

```tsx
import * as React from 'react';

const el = <div className={REPLACE_ME}>foo</div>;
```

1. `yarn add @types/classnames`
1. Erase `REPLACE_ME` and begin typing `classNames`

Does this issue occur when all extensions are disabled?: Yes

Expected: VS Code suggests an auto import of `classNames` from module `'classnames`'.

Actual: no suggested auto import.

image

I believe this is something to do with the fact that `classnames` is defined as a UMD module. If I change the type definitions for `classnames` to remove the UMD definition, the auto import does work correctly:

image

---

Note that VS Code does correctly provide import suggestions after we've finished typing the identifier, when we move our cursor.

image

This issue is specifically about auto imports inside the suggestions that appear as you're typing.

### PR DESCRIPTION
**Pull request by aminpaks**
Please verify that:
* [x] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `gulp runtests` locally
* [x] There are new or updated unit tests validating the change

Fixes #41761

### CODE REVIEW

**Comment by sandersn** [comment]
From reading the issue thread, this test *incorrectly* passes, right? As I understood it, you wanted to create a failing test to match your observations in the editor. Is that correct?

**Comment by aminpaks** [comment]
@sandersn

Yes. I don't quite understand why it works in the test but in a real env it fails (or at least in some cases fail.)

I mentioned my observation [here](https://github.com/microsoft/TypeScript/issues/41761#issuecomment-752238194)

**Comment by andrewbranch** [comment]
What Oliver said is that it fails when it’s declared as a UMD module, which this isn’t. You’d need to add `export as namespace classNames` too.

**Comment by andrewbranch** [comment]
@aminpaks it sounds like you’re still working on this—do you want to convert the PR to a draft so it’s clear it’s not done?

**Comment by aminpaks** [comment]
@andrewbranch Done. I'll look into that asap.

**Comment by aminpaks** [comment]
@andrewbranch would you tell me what is the right test case for this issue? I can't seem to reproduce this issue.

**Comment by andrewbranch** [comment]
1. My understanding from #41761 was that the import fix works but the completions suggestion doesn’t. That’s the bug.
2. Auto-import completions don’t need the whole identifier to be typed.

> would you tell me what is the right test case for this issue

Figuring this out tends to be 90% of the work for these kinds of bugs 😄

**Comment by aminpaks** [comment]
@andrewbranch

I think I found the issue. When we add `export as namespace classNames;` to the module the modules carries some extra property called `globalExports` and then at [this line](https://github.com/microsoft/TypeScript/blob/1e4a5c9b37e80408ba6bfebedbd1c01cedde3de0/src/services/completions.ts#L1433) it counts as a global keywords and then at [this line](https://github.com/microsoft/TypeScript/blob/1e4a5c9b37e80408ba6bfebedbd1c01cedde3de0/src/services/completions.ts#L538) it shadows the one that actually carries the `origin` with it and we lose track of the origin and that causes [this line](https://github.com/microsoft/TypeScript/blob/1e4a5c9b37e80408ba6bfebedbd1c01cedde3de0/src/services/completions.ts#L453) to have no action to provide the import.

I just don't have enough insights to provide a fix for it.
I thought we should [exclude it from the global declaration](https://github.com/microsoft/TypeScript/blob/1e4a5c9b37e80408ba6bfebedbd1c01cedde3de0/src/services/completions.ts#L1433) if it already has an export, what do you think?

**Comment by andrewbranch** [comment]
I think for UMD exports, the global should be shadowed / filtered out if the file is already a module, unless `--allowUmdGlobalAccess` is set. If the file is a script or `--allowUmdGlobalAccess` is set, I guess there isn’t a great solution, so I would keep it as is (the global wins).

**Comment by aminpaks** [comment]
Gotcha, so would you tell me if it's okay to remove the module from global symbols if it has exports?
I found this (refer to "^^" down below) in the `checker.ts` that is adding the module to global symbols (apologies github doesn't allow links to that file).
Of course we must add the logic to check for `allowUmdGlobalAccess ` compiler option also that I don't know if that's possible at this spot
```ts
            for (const file of host.getSourceFiles()) {
                if (file.redirectInfo) {
                    continue;
                }
                if (!isExternalOrCommonJsModule(file)) {
                    // It is an error for a non-external-module (i.e. script) to declare its own `globalThis`.
                    // We can't use `builtinGlobals` for this due to synthetic expando-namespace generation in JS files.
                    const fileGlobalThisSymbol = file.locals!.get("globalThis" as __String);
                    if (fileGlobalThisSymbol) {
                        for (const declaration of fileGlobalThisSymbol.declarations) {
                            diagnostics.add(createDiagnosticForNode(declaration, Diagnostics.Declaration_name_conflicts_with_built_in_global_identifier_0, "globalThis"));
                        }
                    }
                    mergeSymbolTable(globals, file.locals!);
                }
                if (file.jsGlobalAugmentations) {
                    mergeSymbolTable(globals, file.jsGlobalAugmentations);
                }
                if (file.patternAmbientModules && file.patternAmbientModules.length) {
                    patternAmbientModules = concatenate(patternAmbientModules, file.patternAmbientModules);
                }
                if (file.moduleAugmentations.length) {
                    (augmentations || (augmentations = [])).push(file.moduleAugmentations);
                }
                if (file.symbol && file.symbol.globalExports) {
                // ^^ this line adds the module as part of global symbols
                // adding !isExternalOrCommonJsModule(file) + the check for allowUmdGlobalAccess would fix it
                    // Merge in UMD exports with first-in-wins semantics (see #9771)
                    const source = file.symbol.globalExports;
                    source.forEach((sourceSymbol, id) => {
                        if (!globals.has(id)) {
                            globals.set(id, sourceSymbol);
                        }
                    });
                }
            }
```

**Comment by andrewbranch** [comment]
Yeah, I’m only talking about changes to completions.ts.

**Comment by aminpaks** [comment]
How do you feel about this fix @andrewbranch?

https://github.com/microsoft/TypeScript/pull/42141/files#diff-4237fd08a5f920543e184b7748bc8ae000d9b1c031810ba375b0053362ec2b6aR1530

File: src/services/completions.ts [hunk 1]
```diff
@@ -1519,7 +1520,20 @@ namespace ts.Completions {
                         return false;
                     }
 
-                    symbol = skipAlias(symbol, typeChecker);
+                    // External modules can have global export declarations that will be
+                    // available as global keywords in all scopes. But if the external module
+                    // already has an explicit export and user only wants to user explicit
```
Comment (andrewbranch) [inline src/services/completions.ts:1525]: I don’t see you checking for whether the file is a module (`sourceFile.externalModuleIndicator`), so it looks like this will apply to scripts as well, which I think we don’t want. You should add another test for that (completions in a file with no imports or exports).

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 1 above)
Comment (aminpaks) [reply src/services/completions.ts:1525]: It seems if the file is a script we never offer auto import at all by running `shouldOfferImportCompletions()`. I'll add the test.

Comment (aminpaks) [reply src/services/completions.ts:1525]: What other case should we cover? I tried something the example below and there was no Auto Import provided
```ts
const el = class/*1*/
```

Comment (andrewbranch) [reply src/services/completions.ts:1525]: > It seems if the file is a script we never offer auto import at all by running `shouldOfferImportCompletions()`

You’ll want to add some other way of making that function return true, like setting `module` to `es2015`.

Comment (aminpaks) [reply src/services/completions.ts:1526]: Ya thanks for pointing that out. It should be ok now with the last commit. Please review that

File: src/services/completions.ts [hunk 2]
```diff
@@ -1519,7 +1521,22 @@ namespace ts.Completions {
...
+                    // module imports then the global keywords will be filtered out so auto
+                    // import suggestions will win in the completion
+                    const symbolOrigin = skipAlias(symbol, typeChecker);
+                    // We only want to filter out the global keywords
+                    // Auto Imports are not available for scripts so this conditional is always false
+                    if (isFileSourceAModule
+                        && symbolToSortTextMap[getSymbolId(symbol)] === SortText.GlobalsOrKeywords
+                        && symbolToSortTextMap[getSymbolId(symbolOrigin)] === SortText.AutoImportSuggestions
+                        && !compilerOptions.allowUmdGlobalAccess) {
```
Comment (andrewbranch) [inline src/services/completions.ts:1535]: Move this condition up two lines since it’s a bit cheaper to calculate

File: src/services/completions.ts [hunk 3]
```diff
@@ -1505,6 +1506,7 @@ namespace ts.Completions {
             }
 
             const variableDeclaration = getVariableDeclaration(location);
+            const isFileSourceAModule = !!location.getSourceFile().externalModuleIndicator;
```
Comment (andrewbranch) [inline src/services/completions.ts:1509]: `sourceFile` is already in scope, so you can just do `sourceFile.externalModuleIndicator` inline in the condition.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Looks good after these small nits

File: src/services/completions.ts (hunk 3 above)
Comment (aminpaks) [reply src/services/completions.ts]: Done.

File: src/services/completions.ts (hunk 2 above)
Comment (aminpaks) [reply src/services/completions.ts]: Done.

**Review by andrewbranch — APPROVED** [review]
Thanks @aminpaks!

**Comment by aminpaks** [comment]
My pleasure @andrewbranch!
