### PR TITLE
Error when LHS of instanceof is Union of Primitives #18519

### LINKED ISSUE #18519: instanceof should error when all constituents of a union are primitives
```ts
function foo(x: number | string) {
    if (x instanceof Number) {
        x
    }
}
```

Expected:

```
The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter
```

Actual:

No error, incorrect narrowing behavior (#14426)

**Edit:** Corrected the example to *actually* be a union.

### PR DESCRIPTION
**Pull request by charlespierce**
Fixes #18519

Added additional check for if the left-hand operand of an `instanceof` is a union of primitives and raise an error in that case as well.

### CODE REVIEW

**Comment by mhegazy** [comment]
@DanielRosenwasser can you review this change.

**Comment by charlespierce** [comment]
@DanielRosenwasser @mhegazy Just wanted to check if there were any issues with this PR, so I can make any needed changes before it goes stale.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -17604,7 +17604,9 @@ namespace ts {
             // and the right operand to be of type Any, a subtype of the 'Function' interface type, or have a call or construct signature.
             // The result is always of the Boolean primitive type.
             // NOTE: do not raise error if leftType is unknown as related error was already reported
-            if (!isTypeAny(leftType) && isTypeAssignableToKind(leftType, TypeFlags.Primitive)) {
+            if (!isTypeAny(leftType) &&
+                (isTypeAssignableToKind(leftType, TypeFlags.Primitive) ||
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I wonder if it makes sense to hae `isTypeAssignableToKind` just work recursively for all constituents if given a union type. Perhaps make an `allTypesAssignableToKind` helper below it to keep the change scoped.

Otherwise, this seems fine.

**Comment by charlespierce** [comment]
@DanielRosenwasser I like keeping the change scoped, since `isTypeAssignableToKind` is used in a lot of places and there may be some unintended consequences of adding support for union types to it. Updated to use an `allTypesAssignableToKind` helper.

Also updated the test to include the case `(number | string) | number`, which would have failed in the previous implementation since it wasn't recursively checking for union types.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -17587,6 +17587,16 @@ namespace ts {
                 (kind & TypeFlags.NonPrimitive && isTypeAssignableTo(source, nonPrimitiveType));
         }
 
+        function allTypesAssignableToKind(source: Type, kind: TypeFlags, strict?: boolean): boolean {
+            if (source.flags & TypeFlags.Union) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]:
```ts
return source.flags & TypeFlags.Union ?  every((source as UnionType).types, subType => allTypesAssignableToKind(subType, kind, strict)) : isTypeAssignableToKind(source, kind, strict);
```

Comment (charlespierce) [reply src/compiler/checker.ts]: Updated

**Comment by charlespierce** [comment]
@mhegazy @DanielRosenwasser Any additional concerns?

**Comment by mhegazy** [comment]
Sorry for the delay.
