### PR TITLE
Move fixed chunk size polling as a watch option and move it out of server

### LINKED ISSUE #41549: TSServer doesn't respect watchOptions for watchFile
This seems to be intentional, but it looks like TSServer always uses fixed polling to watch files regardless of editor configured options.

Screen Shot 2020-11-15 at 9 46 45 PM

The [relevant code was written 4.5 years ago](https://github.com/microsoft/TypeScript/pull/8196). Does the TypeScript team plan on revisiting that decision? If not, should the `watchFile` option have its choices limited to reduce confusion? (I understand that will partly be a VSCode issue if the answer is yes.)

Personally I think it's strange that this is configurable in `tsc` but not `tsserver`.

---

**Technical Details**:

Here's the `watchUtilities.ts` call, which passes a `WatchOptions` arg:

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/watchUtilities.ts#L440

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/types.ts#L5844-L5853

Here's the implemention in `tsserver`, which actually overrides the default implementation and ignores the `options` arg.

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/tsserver/server.ts#L885-L890

`tsserver.log` also reports a `watchFile` option of `3` ([`WatchFileKind.UseFsEvents`](https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/types.ts#L5703)), which is incorrect.

```
Info 40   [19:45:41.986] FileWatcher:: Added:: WatchInfo: /Volumes/git/TypeScript/src/server/types.ts 500 {"watchFile":3,"watchDirectory":0} Project:  WatchType: Closed Script info
```

**TypeScript Version:**  v4.2.0-dev.20201112

**Search Terms:**
- tsserver polling

**Steps to Reproduce**

Add the following to VSCode `settings.json`:

```json
{
  "typescript.tsserver.watchOptions": {
    "watchFile": "useFsEvents",
  }
}
```

**Expected behavior:**
- TSServer watches files through FSEvents.
- Updates to watched source files happen almost immediately.

**Actual behavior:**
- TSServer watches files with fixed polling.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #41549

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Because this needs protocol change in tsserver, i am marking this for 4.3 instead.

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -126,6 +131,64 @@ namespace ts {
...
+            if (watchedFile.isClosed) {
+                // Closed watcher as part of callback
+                queue[pollIndex] = undefined;
+            }
+            else {
+                callbackOnWatchFileStat?.(watchedFile, pollIndex, fileChanged);
+            }
+
+            if (queue[pollIndex]) {
+                // Copy this file to the non hole location
```
Comment (amcasey) [inline src/compiler/sys.ts:167]: Looks like a "move" if we're clearing the old location?  And what's the "non hole location"?

Comment (amcasey) [reply src/compiler/sys.ts:167]: Seems like maybe we're trying to defragment the queue?

File: src/compiler/sys.ts [hunk 2]
```diff
@@ -361,6 +386,45 @@ namespace ts {
...
+                fileName,
+                callback,
+                mtime: getModifiedTime(host, fileName)
+            };
+            watchedFiles.push(file);
+            scheduleNextPoll();
+            return {
+                close: () => {
+                    file.isClosed = true;
+                    // Remove from watchedFiles
```
Comment (amcasey) [inline src/compiler/sys.ts:409]: I suspect this was copy-pasted, but it's not a very helpful comment.

File: src/compiler/sys.ts [hunk 3]
```diff
@@ -361,6 +386,45 @@ namespace ts {
...
+                    unorderedRemoveItem(watchedFiles, file);
+                }
+            };
+        }
+
+        function pollQueue() {
+            pollScheduled = undefined;
+            // Max visit would be all elements of the queue
```
Comment (amcasey) [inline src/compiler/sys.ts:417]: I think this comment ended up inside the helper function and is unnecessary here?

**Review by amcasey — COMMENTED** [review]
I had trouble following the polling code.  Happy to review in person if that's easier.

File: src/compiler/sys.ts [hunk 4]
```diff
@@ -126,6 +131,64 @@ namespace ts {
...
+    function pollWatchedFileQueue<T extends WatchedFileWithIsClosed>(
+        host: { getModifiedTime: NonNullable<System["getModifiedTime"]>; },
+        queue: (T | undefined)[],
+        pollIndex: number, chunkSize: number,
+        callbackOnWatchFileStat?: (watchedFile: T, pollIndex: number, fileChanged: boolean) => void
+    ) {
+        // Max visit would be all elements of the queue
+        let needsVisit = queue.length;
+        let definedValueCopyToIndex = pollIndex;
+        for (let polled = 0; polled < chunkSize && needsVisit > 0; nextPollIndex(), needsVisit--) {
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/compiler/sys.ts:146]: Just pulled it out and not refactored but will do so

File: src/compiler/sys.ts [hunk 5]
```diff
@@ -126,6 +131,64 @@ namespace ts {
...
+            else if (watchedFile.isClosed) {
+                queue[pollIndex] = undefined;
+                continue;
+            }
+
+            polled++;
+            const fileChanged = onWatchedFileStat(watchedFile, getModifiedTime(host, watchedFile.fileName));
+            if (watchedFile.isClosed) {
+                // Closed watcher as part of callback
+                queue[pollIndex] = undefined;
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/compiler/sys.ts:160]: `callbackOnWatchFileStat` can set the ` queue[pollIndex]` to undefined eg in `createDynamicPriorityPollingWatchFile` when it moves the file from one queue to other with lower priority because file has not changed for several polling sessions

[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/compiler/sys.ts:160]: So what i meant was i will continue but we still need to check for the undefined value

File: src/compiler/sys.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/sys.ts:167]: Yes we are defragmenting

Comment (sheetalkamat) [reply src/compiler/sys.ts:167]: Again this is existing thing i just pulled it out so it can be shared for new option

File: src/compiler/sys.ts [hunk 6]
```diff
@@ -126,6 +131,64 @@ namespace ts {
...
+            if (!watchedFile) {
+                continue;
+            }
+            else if (watchedFile.isClosed) {
+                queue[pollIndex] = undefined;
+                continue;
+            }
+
+            polled++;
+            const fileChanged = onWatchedFileStat(watchedFile, getModifiedTime(host, watchedFile.fileName));
```
Comment (sheetalkamat) [inline src/compiler/sys.ts:157]: This is where actual polling happens. and this is the file that gets counted towards the polling. The code was existing just pulled out to helper so that it can be shared.

File: tests/baselines/reference/api/typescript.d.ts [hunk 7]
```diff
@@ -2775,18 +2775,21 @@ declare namespace ts {
         FixedPollingInterval = 0,
         PriorityPollingInterval = 1,
         DynamicPriorityPolling = 2,
-        UseFsEvents = 3,
-        UseFsEventsOnParentDirectory = 4
+        FixedChunkSizePolling = 3,
+        UseFsEvents = 4,
```
Comment (amcasey) [inline tests/baselines/reference/api/typescript.d.ts:2779]: Changing the numeric value of `UseFsEvents` won't break anyone?

**Review by amcasey — APPROVED** [review]

File: tests/baselines/reference/api/typescript.d.ts (hunk 7 above)
Comment (sheetalkamat) [reply tests/baselines/reference/api/typescript.d.ts:2779]: Shouldnt because you are not suppose to use "number", you are suppose to use text in tsconfig file or command line option or in protocol. This is just part of WatchOptions returned by parsing commandline
