### PR TITLE
Async code fix issues concerning underscores and nested promises

### LINKED ISSUE #27112: in async code fix, handle promise handler callbacks that return a promise
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
async, promise, code fix, code action, then

**Code**

```ts
function foo() {
    return Promise.resolve().then(_ => Promise.resolve(4 + 5)).then(y => y + 5);
}
```

**Expected behavior:**
Async code fix produces
```ts
async function foo() {
    await Promise.resolve();
    const y = await Promise.resolve(4 + 5);
    return y + 5;
}
```
**Actual behavior:**
Async code fix produces
```ts
async function foo() {
    await Promise.resolve();
    const y = Promise.resolve(4 + 5);
    return y + 5;
}
```

### PR DESCRIPTION
**Pull request by uniqueiniquity**
Fixes #27112.

If the handler function for a promise itself returns a promise, then the value of the outer promise is resolved to the value of the inner. However, currently the async code fix does not wrap await the inner promise in this situation. This PR changes the behavior so that if the handler of a promise that's being fixed returns a promise, an `await` is added.

Additionally, this PR fixes an issue where if a promise handler doesn't have a bound parameter name (e.g., `_`), then the preceding promise handler would be deleted. This caused issues when the previous promise handler had side effects.

### CODE REVIEW

**Comment by amcasey** [comment]
Would it be interesting to test the case where the handler returns a promise of a promise?

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 1]
```diff
@@ -404,32 +407,34 @@ namespace ts.codefix {
...
                 }
 
-                if (!hasPrevArgName) break;
-
-                const type = transformer.originalTypeMap.get(getNodeId(func).toString());
-                const callSignatures = type && transformer.checker.getSignaturesOfType(type, SignatureKind.Call);
-                const returnType = callSignatures && callSignatures[0].getReturnType();
-                const varDeclOrAssignment = createVariableDeclarationOrAssignment(prevArgName!, createAwait(synthCall), transformer);
-                prevArgName!.types.push(returnType!);
+                const type = transformer.originalTypeMap.get(getNodeId(func).toString()) || transformer.checker.getTypeAtLocation(func);
```
Comment (amcasey) [inline src/services/codefixes/convertToAsyncFunction.ts]: >originalTypeMap [](start = 41, length = 15)

I thought `originalTypeMap` existed because the checked might return undefined (e.g. if `func` were synthesized).

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 2]
```diff
@@ -451,30 +456,34 @@ namespace ts.codefix {
...
                     }
 
-                    if (hasPrevArgName && !shouldReturn) {
+                    if (!shouldReturn) {
                         const type = transformer.checker.getTypeAtLocation(func);
                         const returnType = getLastCallSignature(type, transformer.checker)!.getReturnType();
-                        const varDeclOrAssignment = createVariableDeclarationOrAssignment(prevArgName!, getSynthesizedDeepClone(funcBody) as Expression, transformer);
-                        prevArgName!.types.push(returnType);
+                        const rightHandSide = getSynthesizedDeepClone(funcBody);
+                        const possiblyAwaitedRightHandSide = isPromiseReturningExpression(funcBody, transformer.checker) ? createAwait(rightHandSide) : rightHandSide;
```
Comment (amcasey) [inline src/services/codefixes/convertToAsyncFunction.ts]: >isPromiseReturningExpression(funcBody, transformer.checker) [](start = 61, length = 59)

Is this different from inspecting `type`?

Comment (amcasey) [inline src/services/codefixes/convertToAsyncFunction.ts]: >createAwait [](start = 123, length = 11)

Does `await` unwrap multiple layers of promises?

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 3]
```diff
@@ -451,30 +456,34 @@ namespace ts.codefix {
...
+                        const varDeclOrAssignment = createVariableDeclarationOrAssignment(prevArgName, possiblyAwaitedRightHandSide, transformer);
```
Comment (amcasey) [inline src/services/codefixes/convertToAsyncFunction.ts]: >createVariableDeclarationOrAssignment [](start = 52, length = 37)

What does this do if `prevArgName` is undefined?

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 2 above)
Comment (andy-ms) [reply src/services/codefixes/convertToAsyncFunction.ts]: There shouldn't ever be multiple layers of promises.
```sh
> p = Promise.resolve(1)
Promise { ... }
> Promise.resolve(p) === p
true
```

Comment (amcasey) [reply src/services/codefixes/convertToAsyncFunction.ts]: I have no idea what JS does, but TS makes it easy to construct an expression of type `Promise<Promise<number>>`.

Comment (andy-ms) [reply src/services/codefixes/convertToAsyncFunction.ts]: The type is wrong though, since it will actually be `Promise<number>`.

Comment (amcasey) [reply src/services/codefixes/convertToAsyncFunction.ts]: Shall I file a bug?

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 4]
```diff
@@ -391,9 +389,14 @@ namespace ts.codefix {
         return [createReturn(getSynthesizedDeepClone(node))];
     }
 
-    function createVariableDeclarationOrAssignment(prevArgName: SynthIdentifier, rightHandSide: Expression, transformer: Transformer): NodeArray<Statement> {
+    function createVariableDeclarationOrAssignment(prevArgName: SynthIdentifier | undefined, rightHandSide: Expression, transformer: Transformer): NodeArray<Statement> {
+        if (!prevArgName || prevArgName.identifier.text.length === 0) {
```
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Sure. There's a place in the code here where we explicitly do that, but I can find another way to handle that case.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 2 above)
Comment (andy-ms) [reply src/services/codefixes/convertToAsyncFunction.ts]: Ask @rbuckton if there's already a bug.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 3 above)
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Good spot, I meant to rename this.

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 5]
```diff
@@ -391,9 +389,14 @@ namespace ts.codefix {
...
 
-    function createVariableDeclarationOrAssignment(prevArgName: SynthIdentifier, rightHandSide: Expression, transformer: Transformer): NodeArray<Statement> {
+    function createVariableDeclarationOrAssignment(prevArgName: SynthIdentifier | undefined, rightHandSide: Expression, transformer: Transformer): NodeArray<Statement> {
+        if (!prevArgName || prevArgName.identifier.text.length === 0) {
+            // if there's no argName to assign to, there still might be side effects
+            return createNodeArray([createStatement(rightHandSide)]);
+        }
 
         if (prevArgName.types.length < prevArgName.numberOfAssignmentsOriginal) {
+            // if the variable has already been declared, we don't need "let" or "const"
```
[the remark this answers is not in the document]
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Fixed.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 3 above)
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Renamed.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 1 above)
Comment (amcasey) [reply src/services/codefixes/convertToAsyncFunction.ts]: I guess you ended up deciding this was safe?

Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: I thought I left a comment, but looks like it was deleted or I forgot to submit it...
Yeah, in the worst case, `getTypeAtLocation` will return an `errorType` with no call signatures and the code action will fail to be reported (and won't delete code or anything of that nature).

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 2 above)
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: Fixed for clarity.
