### PR TITLE
fix(49478): TS declare method produces compile errors with noImplicitAny enabled

### LINKED ISSUE #49478: TS declare method produces compile errors with noImplicitAny enabled
*TS Template added by @mjbvz*

**TypeScript Version**: 4.8.0-dev.20220606

**Search Terms**
- quick fix
- code action
- noimplicitany

---

Recording 2022-06-10 at 10 38 38

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49478

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -682,7 +682,7 @@ namespace ts.textChanges {
             return {
                 indentation,
                 prefix: (insertLeadingComma ? "," : "") + this.newLineCharacter,
-                suffix: insertTrailingComma ? "," : ""
+                suffix: insertTrailingComma ? "," : isInterfaceDeclaration(node) && isEmpty ? ";" : ""
```
Comment (DanielRosenwasser) [inline src/services/textChanges.ts:685]: The `;` depends on the preferences, right?

Comment (DanielRosenwasser) [reply src/services/textChanges.ts:685]: I suppose that nowhere else in TypeScript do we generate new code for a semicolonless style.

**Review by DanielRosenwasser — APPROVED** [review]
