### PR TITLE
fix(52212): No member completions, and irrelevant value completions, when class property initializer has no semicolon

### LINKED ISSUE #52212: No member completions, and irrelevant value completions, when class property initializer has no semicolon
```ts
interface Interface {
    method(): void;
}

export class Class implements Interface {
    property = "yadda"
    
    /*$*/
}
```

**Expected**: We should auto-complete `method` and class member keywords - and then *possibly* the usual value completions one would get at the top level scope.
**Actual**: Usual value completions at the top-level!

image

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #52212

### CODE REVIEW

File: tests/cases/fourslash/completionsClassMembers.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+////    method(): void;
+////}
+////
+////export class C implements I {
+////    property = "foo"
+////
+////    /**/
+////}
+
+verify.baselineCompletions();
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionsClassMembers.ts:13]: Can you also baseline completions when snippet completions and class snippet completions are both enabled?

Comment (a-tarasyuk) [reply tests/cases/fourslash/completionsClassMembers.ts:13]: https://github.com/microsoft/TypeScript/blob/5b4a8d4134bbb8947abdb0f916568b2e1ff6b2c0/src/services/completions.ts#L1403-L1404
?

File: src/services/completions.ts [hunk 2]
```diff
@@ -4850,6 +4850,12 @@ function tryGetObjectTypeDeclarationCompletionContainer(sourceFile: SourceFile,
         return findAncestor(contextToken, isClassLike) as ObjectTypeDeclaration;
     }
 
+    // class C { prop = ""\n | }
+    if (contextToken && isPropertyDeclaration(contextToken.parent) && isClassLike(location)
+        && getLineAndCharacterOfPosition(sourceFile, contextToken.getEnd()).line !== getLineAndCharacterOfPosition(sourceFile, position).line) {
+        return location;
+    }
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:4857]: So I was going to ask about a test case like

```ts
interface Interface {
    method(): void;
}

export class Class implements Interface {
    property = "yadda" + "yadda"
    
    /*$*/
}
```

and I have *no idea* why this example has reasonable completions, whereas the code in the original issue doesn't. Do you have an idea right now?

Comment (DanielRosenwasser) [reply src/services/completions.ts:4857]: Is it from the `if (!isFromObjectTypeDeclaration(contextToken)) {` code below? Maybe we should just get rid of that check?

**Comment by DanielRosenwasser** [comment]
Merge conflict 😞

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/completions.ts [hunk 3]
```diff
@@ -4868,16 +4868,17 @@ function tryGetObjectTypeDeclarationCompletionContainer(sourceFile: SourceFile,
         case SyntaxKind.CommaToken: // class c {getValue(): number, | }
             return tryCast(contextToken.parent, isObjectTypeDeclaration);
         default:
-            if (!isFromObjectTypeDeclaration(contextToken)) {
-                // class c extends React.Component { a: () => 1\n| }
-                if (getLineAndCharacterOfPosition(sourceFile, contextToken.getEnd()).line !== getLineAndCharacterOfPosition(sourceFile, position).line && isObjectTypeDeclaration(location)) {
+            if (isObjectTypeDeclaration(location)) {
+                // class C extends React.Component { a: () => 1\n| }
+                // class C { prop = ""\n | }
+                if (isClassLike(location) && getLineAndCharacterOfPosition(sourceFile, contextToken.getEnd()).line !== getLineAndCharacterOfPosition(sourceFile, position).line) {
```
Comment (gabritto) [inline src/services/completions.ts:4874]: Question: why do we need the `isClassLike(location)` check here?

Comment (a-tarasyuk) [reply src/services/completions.ts:4874]: The context of the issue is related to properties declaration, however, I'm not sure if it is valid for `InterfaceDeclaration`, `TypeLiteralNode` contexts.

Comment (gabritto) [reply src/services/completions.ts:4874]: I think we can get away with removing the check. The function doesn't seem to be restricted to classes. I'm not sure removing the check will have an immediate effect anyway, since I tried it around for a bit and we don't seem to offer completions inside interfaces and type literals, but removing it might spare us some future confusion.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test tsserver top100

**Review by gabritto — APPROVED** [review]
