### PR TITLE
fix(43408): JSDoc accessor declaration emit drops undefined when strictNullChecks is off

### LINKED ISSUE #43408: JSDoc accessor declaration emit drops undefined when strictNullChecks is off
# Bug Report

### 🔎 Search Terms

* JSDoc
* getter
* nullable
* undefined
* optional

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "JSDoc" and "getters".

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3&useJavaScript=true#code/PTAEFMFsEsBdfAE1LAngB3KR4DGAbAQwCdDZoB7AOwGdQAzC40ANxOkICN9w6aBXdOiaxQVfviLdwwCunLVC+FBl4BYAFDAAVNtAABNJlABvGrGLQqAcwC8AX1Dbgm3NXMMKFULdAByRgo-AG5NHT1DVVNzSxtQAB9QfioceiskR2dXd1FOEh9-QJCw3QMjLBMAfhira0yXDTdaXMIALwKAr2KtUsjjMwtahLEJfHrs5tAAR34ADw6i0I0wsAALCgB3cBZwYgAaFFXwVFASLCoKUQEhESRQalBrcHhdmlciGjoAMS9TTVBQOEylEBrE7OMNACnqJAgAKACUplAxGe-GIVEKXWCoHs-0BvXK0UGcUSyVS6UQEKhz1AeWICKRKNgaIxnSC2NxkPxEUJVRqNipjxpeVaDJMyNR6Mx7JxeKBfQq-Osw3EkkF0OmczFEuZUrZIVlGk5K0OWBohEgWEIQnw0F4nmY+iZLLejQ+dAAQvkTHLes70XRQbUHE4GtSYV5tf7WYtDQD5dHA0rhmTwGkqBlQ3iNXSo5KY1i49yDInTNViXUs1yc2087qCzLOfG-fmkxWVaN1TSZrM6yzpQbOZygA)

### 💻 Code

See playground link.

### 🙁 Actual behavior

See **.D.TS** tab in playground.

### 🙂 Expected behavior

```ts
// const declarations unchanged...
declare class Foo {
    /** @type {string=} */
    get foo(): string | undefined;
    /** @type {string | undefined} */
    get bar(): string | undefined;
    /** @type {?string} */
    get baz(): string | null;
    /** @type {string | null} */
    get qux(): string | null;
}
declare class Bar {
    /** @returns {string=} */
    get foo(): string | undefined;
    /** @returns {string | undefined} */
    get bar(): string | undefined;
    /** @returns {?string} */
    get baz(): string | null;
    /** @returns {string | null} */
    get qux(): string | null;
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43408

### CODE REVIEW

File: tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.js [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+
+    /** @type {?string} */
+    get p3() {
+        return null;
+    }
+
+    /** @type {string | null} */
+    get p4() {
+        return null;
+    }
```
Comment (sandersn) [inline tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.js:35]: can you add tests for set and get/set pairs, the latter with annotations on each of get/set/get+set?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5962,21 +5962,26 @@ namespace ts {
...
+            }
+
             /**
              * Unlike `typeToTypeNodeHelper`, this handles setting up the `AllowUniqueESSymbolType` flag
              * so a `unique symbol` is returned when appropriate for the input symbol, rather than `typeof sym`
              */
             function serializeTypeForDeclaration(context: NodeBuilderContext, type: Type, symbol: Symbol, enclosingDeclaration: Node | undefined, includePrivateSymbol?: (s: Symbol) => void, bundled?: boolean) {
                 if (type !== errorType && enclosingDeclaration) {
-                    const declWithExistingAnnotation = getDeclarationWithTypeAnnotation(symbol, enclosingDeclaration);
-                    if (declWithExistingAnnotation && !isFunctionLikeDeclaration(declWithExistingAnnotation)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:5972]: As the change currently stands I'm not a huge fan of extracting this function. It makes the diff pretty hard to read.
On the other hand, if adding `set` tests shows that the code needs to be more complex, it might tip the balance more strongly toward having a separate function.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Ok, removed function

File: tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.js (hunk 1 above)
Comment (a-tarasyuk) [reply tests/baselines/reference/jsDeclarationsReusesExistingTypeAnnotations.js:35]: @sandersn I've added tests

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6004,7 +6004,7 @@ namespace ts {
             function serializeTypeForDeclaration(context: NodeBuilderContext, type: Type, symbol: Symbol, enclosingDeclaration: Node | undefined, includePrivateSymbol?: (s: Symbol) => void, bundled?: boolean) {
                 if (type !== errorType && enclosingDeclaration) {
                     const declWithExistingAnnotation = getDeclarationWithTypeAnnotation(symbol, enclosingDeclaration);
-                    if (declWithExistingAnnotation && !isFunctionLikeDeclaration(declWithExistingAnnotation)) {
+                    if (declWithExistingAnnotation && !isFunctionLikeDeclaration(declWithExistingAnnotation) && !isGetAccessorDeclaration(declWithExistingAnnotation)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:6007]: this looks backward from the way it was before, but the PR doesn't have the old commit for comparison, and the tests aren't done running, so I might just be misreading it.

Comment (a-tarasyuk) [reply src/compiler/checker.ts:6007]: @sandersn Tests passed. I've removed the function to simplify the review, as you mentioned before.

**Review by sandersn — APPROVED** [review]
