### PR TITLE
Handle find all references for symbol merged with UMD module and global var

### LINKED ISSUE #29093: Global declaration crashes TypeScript in Visual Studio Code
## Premise

In my work project we are using three.js library from an external compiled source file: three.min.js. Our own codebase is being migrated to typescript, so to more easily use three.js, we try to use typings for it. Since `THREE` is a global namespace variable (that is defined by the library itself), we want to have it accessible in each file without any import statement. For that I am folowing this example: https://github.com/Microsoft/TypeScript/issues/3180

The problem happens if I declare THREE as a global constant. It works if I declare with a different name. The IDE doesn't show any errors and just stops compiling typescript all together.

## Details

**TypeScript Version:**  3.2.2
**Code Version:** 1.30.0 (1.30.0)

**Search Terms:** Error processing request. Debug Failure. Expected a module symbol to be declared by a SourceFile or ModuleDeclaration.

**Code**

```ts
// global.d.ts
import * as _THREE from 'three';

declare global {
  const THREE: typeof _THREE;
}
// index.ts
export const a = {}; // Exporting something to make this file a module

let v = new THREE.Vector3();
```

**Typescript Output (in IDE)**

```
[Error  - 12:03:17] 'references' request failed with error.
Error processing request. Debug Failure. Expected a module symbol to be declared by a SourceFile or ModuleDeclaration.
Error: Debug Failure. Expected a module symbol to be declared by a SourceFile or ModuleDeclaration.
    at getReferencedSymbolsForModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:99136:38)
    at Object.getReferencedSymbolsForNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:99088:40)
    at Object.findReferencedSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:98780:60)
    at Object.findReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117557:41)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124107:68
    at callbackProjectAndLocation (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124160:13)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124134:24
    at forEachProjectInProjects (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124117:17)
    at combineProjectOutputWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124132:13)
    at combineProjectOutputForReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124090:13)
    at IOSession.Session.getReferences (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125124:34)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:124270:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125824:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125815:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125824:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:125846:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:127106:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Expected behavior:** Show an error or work as predicted by exposing a global constant with the name `THREE`.

**Actual behavior:** Getting an error in Typescript Output tab and no syntax highlighting in my files.

**Example project:** https://github.com/Kristonitas/three-typings-test

`package.json` and `tsconfig.json` are included in the example project which reproduces the issue.

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/3180

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #29093 
Created #29533 to handle symbol name.

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -380,23 +385,92 @@ namespace ts.FindAllReferences.Core {
             return getReferencedSymbolsForModule(program, symbol.parent!, /*excludeImportTypeOfExportEquals*/ false, sourceFiles, sourceFilesSet);
         }
 
-        let moduleReferences: SymbolAndEntries[] = emptyArray;
-        const moduleSourceFile = isModuleSymbol(symbol);
-        let referencedNode: Node | undefined = node;
-        if (moduleSourceFile) {
-            const exportEquals = symbol.exports!.get(InternalSymbolName.ExportEquals);
-            // If !!exportEquals, we're about to add references to `import("mod")` anyway, so don't double-count them.
-            moduleReferences = getReferencedSymbolsForModule(program, symbol, !!exportEquals, sourceFiles, sourceFilesSet);
```
Comment (RyanCavanaugh) [inline src/services/findAllReferences.ts]: Please retain the comments

File: tests/cases/fourslash/findAllReferencesUmdModuleAsGlobalConst.ts [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+////        "allowJs": true,
+////        "skipLibCheck": true,
+////        "lib": ["es2016", "dom"],
+////        "typeRoots": ["node_modules/@types/"],
+////        "types": ["three"]
+//// 	},
+////    "files": ["/src/index.ts", "typings/global.d.ts"]
+////}
+
+// TODO:: this should be var THREE: typeof import instead of module name as var but thats existing issue and repros with quickInfo too.
```
Comment (RyanCavanaugh) [inline tests/cases/fourslash/findAllReferencesUmdModuleAsGlobalConst.ts]: Would be good to reference the issue you logged here

File: src/services/findAllReferences.ts [hunk 3]
```diff
@@ -380,23 +385,92 @@ namespace ts.FindAllReferences.Core {
...
+        // If !!exportEquals, we're about to add references to `import("mod")` anyway, so don't double-count them.
+        const moduleReferences = getReferencedSymbolsForModule(program, symbol, !!exportEquals, sourceFiles, sourceFilesSet);
+        if (!exportEquals || !sourceFilesSet.has(moduleSourceFile.fileName)) return moduleReferences;
+        // Continue to get references to 'export ='.
+        const checker = program.getTypeChecker();
+        symbol = skipAlias(exportEquals, checker);
+        return mergeReferences(program, moduleReferences, getReferencedSymbolsForSymbol(symbol, /*node*/ undefined, sourceFiles, sourceFilesSet, checker, cancellationToken, options));
+    }
+
+    function mergeReferences(program: Program, ...referencesToMerge: (SymbolAndEntries[] | undefined)[]): SymbolAndEntries[] | undefined {
```
Comment (RyanCavanaugh) [inline src/services/findAllReferences.ts]: A brief comment explaining more precisely what this does would be nice
