### PR TITLE
Consider the commonjs module indicator as a module indicator

### LINKED ISSUE #17192: Tslib helpers not imported for js files with non ES6 style modules when `importHelpers` is true
The tslib helpers that are generated to allow valid typescript to run for a specific target are not imported when using common JS modules and `importHelpers` set to true. This causes a valid typescript file to fail, as functions like `__extend` will be undefined.

**TypeScript Version:**  2.4.1 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
class Foo {

}

class Bar extends Foo {

}

module.exports = Bar;
```
with the `tsconfig.json`

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "skipLibCheck": true,
    "module": "commonjs",
    "target": "es5",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015.iterable"
    ],
    "noEmitHelpers": true,
    "importHelpers": true
  }
}
```
generates the following code:

```js
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
var Bar = (function (_super) {
    __extends(Bar, _super);
    function Bar() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Bar;
}(Foo));
module.exports = Bar;
```

However, simply switching the typescript code to use es6 style export:

```ts
class Foo {

}

class Bar extends Foo {

}

export {
    Bar
};
```

generates the expected result:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
var Bar = (function (_super) {
    tslib_1.__extends(Bar, _super);
    function Bar() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Bar;
}(Foo));
exports.Bar = Bar;
```

**Expected behavior:**
CommonJS modules also receive the tslib helpers when `importHelpers` is set to true.

**Actual behavior:**
The tslib helpers are not imported, thus the code breaks due to `__extends` not being defined.
`ReferenceError: __extends is not defined`

### PR DESCRIPTION
**Pull request by weswigham**
within the module transformer. This causes us to pick up some js files with `require` or `export.` as modules now, as can be seen in the baseline changes.

Fixes #17192

### CODE REVIEW

File: tests/baselines/reference/dynamicRequire.js [hunk 1]
```diff
@@ -4,6 +4,9 @@ function foo(name) {
 }
 
 //// [a_out.js]
-function foo(name) {
-    var s = require("t/" + name);
-}
+define("a", ["require", "exports"], function (require, exports) {
```
Comment (mhegazy) [inline tests/baselines/reference/dynamicRequire.js]: hmm.. this does not look good. we should not mess up the module output if we can.

Comment (mhegazy) [reply tests/baselines/reference/dynamicRequire.js]: not sure what to do though.. @rbuckton thoughts?

**Comment by weswigham** [comment]
It's also worth noting that our current output is actually correctly handled by including `tslib` with the output, as is evident from discussion [here](https://github.com/Microsoft/tslib/issues/32).

File: tests/baselines/reference/dynamicRequire.js (hunk 1 above)
Comment (weswigham) [reply tests/baselines/reference/dynamicRequire.js]: This file has an explicit `@module: amd` BTW. Our module emit and our global emit for `commonjs` are pretty much identical - the only difference is in how the typechecker sees the top-level scope.

**Comment by mhegazy** [comment]
This is then a bigger change than originally intended.

**Comment by weswigham** [comment]
@mhegazy 👍 👎 Punt? Disable `commonjsModuleIndicator` flag collection when `module` is not `commonjs`?

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -444,7 +444,7 @@ namespace ts {
     }
 
     export function isEffectiveExternalModule(node: SourceFile, compilerOptions: CompilerOptions) {
-        return isExternalModule(node) || compilerOptions.isolatedModules;
+        return isExternalModule(node) || compilerOptions.isolatedModules || !!node.commonJsModuleIndicator;
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: this seems like the best compromise here: 
`(!!node.commonJsModuleIndicator && getEmitModuleKind(compilerOptions) !== ModuleKind.CommonJS)`

Comment (mhegazy) [reply src/compiler/utilities.ts]: so what u think?

Comment (weswigham) [reply src/compiler/utilities.ts]: It seems reasonable. Though anyone with mixed-mode compilations targeting commonjs where they use `require` in some global files is going to get sad when their global files start getting transpiled as modules. Though why we even support mixed mode compilations in the first place...

Comment (mhegazy) [reply src/compiler/utilities.ts]: the other option is to do nothing and leave the current behavior.. which is broken on import helpers + js files (which could be a smaller group affected than by the proposed change)...

Comment (weswigham) [reply src/compiler/utilities.ts]: mmmmmmm I think once limited to commonjs it's likely fine. The only difference other than helpers, which is what this aims to change, for module vs non-module would be that top level declarations are local to the file instead of global. And given that the commonjs module flag is only set in JS files, it's not like there'll be any potential interface or namespace merging going on; so it'd just be weather people expected the `var x` they declared in one file with a `require` to be visible in another file with a `require`.

**Comment by weswigham** [comment]
@mhegazy Accept like so? 👍 👎
