### PR TITLE
 Fixed #5032: tsserver: Format on type broken 

### LINKED ISSUE #5032: tsserver: Format on type broken
See the animated git here: http://pan.baidu.com/s/1kTCNhdX

Format on type deletes valid code on the next line. This is reproducible using VSCode and tsserver from 1.6.2

### PR DESCRIPTION
**Pull request by dbaeumer**
Fixes #5032

The Pull request changes the logic of the indentation correction code as follows:

- computes the preferred indent using getIndentationAtPosition - this is spaces based
- computes the current indent by scanning the line - this is normalized to spaces as well
- if the two are different replace the current indent string with a new one. The newly generated indent string honors tabs and spaces

Although this is might replace a larger string then necessary it is easier to understand. And IMO it doesn't really matter if the edit replace n or m characters with m > n.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

File: src/server/session.ts [hunk 1]
```diff
@@ -21,6 +21,21 @@ namespace ts.server {
         return spaceCache[n];
     }
 
+    export function generateIndentString(n: number, editorOptions: EditorOptions): string {
```
Comment (vladima) [inline src/server/session.ts]: we already have similar function [getIndentationString](https://github.com/Microsoft/TypeScript/blob/master/src/services/formatting/formatting.ts#L1071). Can it be used instead to avoid code duplication?

File: src/server/session.ts [hunk 2]
```diff
@@ -607,27 +622,25 @@ namespace ts.server {
                                 NewLineCharacter: "\n",
                                 ConvertTabsToSpaces: formatOptions.ConvertTabsToSpaces,
                             };
-                            var indentPosition =
-                                compilerService.languageService.getIndentationAtPosition(file, position, editorOptions);
+                            var preferredIndent = compilerService.languageService.getIndentationAtPosition(file, position, editorOptions);
+                            var hasIndent = 0;
                             for (var i = 0, len = lineText.length; i < len; i++) {
```
Comment (vladima) [inline src/server/session.ts]: we should already have something that is kind of doing the same thing [findFirstNonWhitespaceCharacterAndColumn](https://github.com/Microsoft/TypeScript/blob/master/src/services/formatting/smartIndenter.ts#L375). Can you check if it can be reused here?

**Comment by vladima** [comment]
LGTM, assuming that notes about potential code reuse can be addressed

**Comment by mhegazy** [comment]
@dbaeumer can you also add a fourslash test?

**Comment by mhegazy** [comment]
@vladima spent some time yesterday trying to write a test for the original issue, and it does not seem possible given the current test infrastructure. the fourslash test behaves similar to VS, as it will not add indentation before calling format. so i would not bother about adding test for the original issue.

**Comment by mhegazy** [comment]
please add a test for preserving tabs though.
