### PR TITLE
Feed the 'this' type as a type argument to constraints during relation checking

### LINKED ISSUE #7276: Incorrect error in extended interface when base interface has `this` member
**TypeScript Version:** 

master

**Code**

```ts
interface Foo<T extends Bar> { x: T }

interface Bar {
	thing: this;
}

interface Something extends Bar {
	other: Foo<this>;
}
```

**Expected behavior:**
No error

**Actual behavior:** 
Error
> ```
error TS2344: Type 'this' does not satisfy the constraint 'Bar'.
  Type 'Something' is not assignable to type 'Bar'.
    Types of property 'thing' are incompatible.
      Type 'Something' is not assignable to type 'this'.
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #7276.

@ahejlsberg @sandersn @RyanCavanaugh can you take a look?

Right now, the types are being instantiated with their `target`. Is this sufficient?

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5595,9 +5595,14 @@ namespace ts {
 
                 if (source.flags & TypeFlags.TypeParameter) {
                     let constraint = getConstraintOfTypeParameter(<TypeParameter>source);
+
                     if (!constraint || constraint.flags & TypeFlags.Any) {
                         constraint = emptyObjectType;
                     }
+
+                    // The constraint may need to be further instantiated with its 'this' type.
+                    constraint = getTypeWithThisArgument(constraint);
```
Comment (sandersn) [inline src/compiler/checker.ts]: Let me check my understanding: an unconstrained type parameter gets 'any' or '{}' as its constraint, which shouldn't have a this-type, so this is a no-op there. Am I right?

File: tests/baselines/reference/fuzzy.errors.txt [hunk 2]
```diff
@@ -39,7 +38,6 @@ tests/cases/compiler/fuzzy.ts(25,20): error TS2352: Neither type '{ oneI: this;
 !!! error TS2322:   Types of property 'oneI' are incompatible.
 !!! error TS2322:     Type 'this' is not assignable to type 'I'.
 !!! error TS2322:       Type 'C' is not assignable to type 'I'.
-!!! error TS2322:         Property 'alsoWorks' is missing in type 'C'.
```
Comment (sandersn) [inline tests/baselines/reference/fuzzy.errors.txt]: Why does this go away? We instantiate `this` as 'C', then somehow we don't notice that `alsoWorks` is missing now?

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Yup. I could have introduced an `else` branch, but I figured that this would be a little simpler to read. I'm open to changing it.

Comment (sandersn) [inline src/compiler/checker.ts]: No, I think it's fine. Just checking.

File: tests/baselines/reference/fuzzy.errors.txt (hunk 2 above)
Comment (DanielRosenwasser) [inline tests/baselines/reference/fuzzy.errors.txt]: I'm not 100% sure, but I have some thoughts which we can discuss offline.

Comment (sandersn) [inline tests/baselines/reference/fuzzy.errors.txt]: Here's the result of the offline discussion:
The error's already elaborated at line 26. So now that `this` is instantiated as `C`, the compiler knows that it's already reported this error once. (We think :) So it's fine to drop it here.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: You want to instantiate the constraint with `source` as the this-type parameter, so this line should be:

```Typescript
constraint = getTypeWithThisArgument(constraint, source);
```

As you have it now you're instantiating the constraint with its own this-type as the this-type parameter. I think the reason it works with the example in the bug is because the this-type of `Something` is assignable to the this-type of `Bar`, but it's not the right solution.

File: tests/baselines/reference/fuzzy.errors.txt (hunk 2 above)
Comment (ahejlsberg) [inline tests/baselines/reference/fuzzy.errors.txt]: Yes, this looks like a case of an elaboration that was already made and subsequently cached.

**Comment by sandersn** [comment]
:+1:

**Comment by mhegazy** [comment]
@DanielRosenwasser can you update the PR and respond to the remaining comments.
