### PR TITLE
Fix overlapping changes when un-qualifying import use site within transformed export

### LINKED ISSUE #40983: Error: Debug Failure. False expression: Changes overlap
**TypeScript Version:**  4.0.3 and nightly

**Search Terms:** Error: Debug Failure. False expression: Changes overlap

**Code**

I'm not a typescript developer, so I don't have a code snippet to reproduce the error. This error is happening while I edit personal project code while using [coc-tsserver](https://github.com/neoclide/coc-tsserver) for LSP diagnostics. The issue happens when it requests code fixes for the following reduced code snippet:

```js
var Q = require("q");

module.exports = {
  search: function () {
    var deferred = Q.defer();
  }
}
```

From what I can tell, it seems it's being triggered because the code fixes indeed overlap, which is suggestion for unused variable (`deferred`) and the suggestion for converting the module to ES6 module, which reformats it as a whole. This is the stack trace when I hover over the first line and check for quick fixes:

```
Error on request (quickfixes): Vim(return):Error invoking 'quickfixes' on channel 3 (coc):
Error processing request. Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":23,"end":101} and {"pos":85,"end":92}
Error: Debug Failure. False expression: Changes overlap
Verbose Debug Information: {"pos":23,"end":101} and {"pos":85,"end":92}
    at _loop_10 (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:130016:34)
    at /home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:130022:25
    at Object.mapDefined (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:610:30)
    at Object.getTextChangesFromChanges (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:130010:27)
    at ChangeTracker.getChanges (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:129978:45)
    at Function.ChangeTracker.with (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:129426:32)
    at Object.getCodeActions (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:132160:64)
    at /home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:130599:77
    at Object.flatMap (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:513:25)
    at Object.getFixes (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:130599:23)
    at /home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:143796:35
    at Object.flatMap (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:513:25)
    at Object.getCodeFixesAtPosition (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:143794:23)
    at Proxy.<anonymous> (/home/francisco/.config/coc/extensions/node_modules/coc-styled-components/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:144:20)
    at IOSession.Session.getCodeFixes (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:154662:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:153339:61)
    at /home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/home/francisco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:314:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Expected behavior:** No error

**Actual behavior:** Long debug stack trace

**Related Issues:** #27700

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40983

Can’t believe we didn’t get this one before now 🤔

### CODE REVIEW

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 1]
```diff
@@ -199,7 +199,26 @@ namespace ts.codefix {
             }
         });
 
-        return getSynthesizedDeepCloneWithRenames(nodeToRename, /*includeTrivia*/ true, identsToRenameMap, checker);
+        return getSynthesizedDeepCloneWithReplacements(nodeToRename, /*includeTrivia*/ true, original => {
```
Comment (andrewbranch) [inline src/services/codefixes/convertToAsyncFunction.ts:202]: This was, until now, the only consumer of `getSynthesizedDeepCloneWithRenames`, so I moved the bits that had poor reusability out to here.

Comment (sandersn) [reply src/services/codefixes/convertToAsyncFunction.ts:202]: weird that it had an unused optional `callback` parameter

File: src/services/codefixes/convertToEs6Module.ts [hunk 2]
```diff
@@ -98,7 +112,7 @@ namespace ts.codefix {
     /** Whether `module.exports =` was changed to `export default` */
     type ModuleExportsChanged = boolean;
 
-    function convertStatement(sourceFile: SourceFile, statement: Statement, checker: TypeChecker, changes: textChanges.ChangeTracker, identifiers: Identifiers, target: ScriptTarget, exports: ExportRenames, quotePreference: QuotePreference): ModuleExportsChanged {
+    function convertStatement(sourceFile: SourceFile, statement: Statement, checker: TypeChecker, changes: textChanges.ChangeTracker, identifiers: Identifiers, target: ScriptTarget, exports: ExportRenames, useSitesToUnqualify: ESMap<Node, Node> | undefined, quotePreference: QuotePreference): ModuleExportsChanged {
```
Comment (sandersn) [inline src/services/codefixes/convertToEs6Module.ts:115]: please break up this line

File: src/services/codefixes/convertToEs6Module.ts [hunk 3]
```diff
@@ -115,7 +129,7 @@ namespace ts.codefix {
                     }
                     case SyntaxKind.BinaryExpression: {
                         const { operatorToken } = expression as BinaryExpression;
-                        return operatorToken.kind === SyntaxKind.EqualsToken && convertAssignment(sourceFile, checker, expression as BinaryExpression, changes, exports);
+                        return operatorToken.kind === SyntaxKind.EqualsToken && convertAssignment(sourceFile, checker, expression as BinaryExpression, changes, exports, useSitesToUnqualify);
```
Comment (sandersn) [inline src/services/codefixes/convertToEs6Module.ts:132]: is a change to convertAssignment already in this PR? Or did it already take a map of use sites to unqualify?

File: src/services/codefixes/convertToEs6Module.ts [hunk 4]
```diff
@@ -524,4 +572,16 @@ namespace ts.codefix {
             exportSpecifiers && factory.createNamedExports(exportSpecifiers),
             moduleSpecifier === undefined ? undefined : factory.createStringLiteral(moduleSpecifier));
     }
+
+    interface ConvertedImports {
+        newImports: readonly Node[];
+        useSitesToUnqualify?: ESMap<Node, Node>;
+    }
+
+    function convertedImports(newImports: readonly Node[], useSitesToUnqualify?: ESMap<Node, Node>): ConvertedImports {
```
Comment (sandersn) [inline src/services/codefixes/convertToEs6Module.ts:581]: This function seems a bit superfluous to me; there's only one call with a second argument.
I guess it lets you avoid writing casts or explicit return types in some places?

File: src/services/codefixes/convertToEs6Module.ts [hunk 5]
```diff
@@ -200,7 +223,7 @@ namespace ts.codefix {
                 changes.delete(sourceFile, assignment.parent);
             }
             else {
-                const replacement = isObjectLiteralExpression(right) ? tryChangeModuleExportsObject(right)
+                const replacement = isObjectLiteralExpression(right) ? tryChangeModuleExportsObject(right, useSitesToUnqualify)
```
Comment (sandersn) [inline src/services/codefixes/convertToEs6Module.ts:226]: I don't know this code at all, but it seems like there are a lot of potential places that need to be threaded through with `useSitesToUnqualify`. Are you confident you didn't miss any?

**Review by sandersn — APPROVED** [review]
Looks reasonable. A few non-blocking questions; probably the most important is whether convertAssignment already took a set of use sites to unqualify.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/codefixes/convertToAsyncFunction.ts:202]: It was used originally, but I stopped using it a few months back when I greatly simplified convertToAsyncFunction.

File: src/services/codefixes/convertToEs6Module.ts (hunk 4 above)
Comment (andrewbranch) [reply src/services/codefixes/convertToEs6Module.ts:581]: It was because of all the places that _didn’t_ have the second argument that I added this; all those were one-liner returns that would have become four lines in order to add the object literal with `useSitesToUnqualify: undefined` on a line.

File: src/services/codefixes/convertToEs6Module.ts (hunk 3 above)
Comment (andrewbranch) [reply src/services/codefixes/convertToEs6Module.ts:132]: It’s here, GitHub folded over it: https://github.com/microsoft/TypeScript/pull/40987/files#diff-d91b63cfe65f0adf550d61fede06a78dR213

File: src/services/codefixes/convertToEs6Module.ts (hunk 5 above)
Comment (andrewbranch) [reply src/services/codefixes/convertToEs6Module.ts:226]: Yep, pretty confident. I had never seen this code before either, but I ended up reading pretty much all the parts that actually perform text changes.
