### PR TITLE
Handle module node found error reporting in incremental and watch scneario

### LINKED ISSUE #52810: Node10Result on resolvedModule issues
# Bug Report

### 🕗 Version & Regression Information

- #52173 added extra resolution and informtion from it to resolved module and that can interfere with how incremental works

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

- node10Result is present as additional property on resolvedModuleWithFailedlookupLocations but that is not taken into account by builder so changes to only that build will not update incremental errors (eg install `@types` or some such
- The error stored in build info contains the file path for the file that is not changed relative to buildInfo can can make it not portable.

### PR DESCRIPTION
**Pull request by sheetalkamat**
With this, the diagnostic chain has `repopulateInfo` property if present will be used by incremental builder to update the diagnostic chain. 
I didnt think it was right to get new errors again from checker just so error reporting is correct and resulting in more work, so went ahead with approach of diagnostic chain having this info.
This change has following changes to make everything come together:
1. `ModuleNodeFound` chain is now a helper and sets repopulate info which can be used by anyone to get the latest chain.
2.  In the tsbuildinfo we save this info instead of chain message, so that we can get the correct diagnostic when getting the errors from buildinfo for the file.
3. In tsc --watch scenario we need to repopulate using existing diagnostic and source file 
4. failed lookups and affected locations of node10Result are accumulated in the resolution itself so that it can be watched. We also watch node10Result as if it was failed lookup.

Fixes  #52810

### CODE REVIEW

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -448,6 +467,60 @@ function getEmitSignatureFromOldSignature(options: CompilerOptions, oldOptions:
         isString(oldEmitSignature) ? [oldEmitSignature] : oldEmitSignature[0];
 }
 
+function mapArrayIfChanged<T, U>(array: T[], map: (element: T) => U): U[];
+function mapArrayIfChanged<T, U>(array: readonly T[], map: (element: T) => U): readonly U[];
+function mapArrayIfChanged<T, U>(array: readonly T[], map: (element: T) => U): U[] {
```
Comment (jakebailey) [inline src/compiler/builder.ts:472]: Is this the same as `sameMap`?

Comment (sheetalkamat) [reply src/compiler/builder.ts:472]: Yes.. Thank you

File: src/compiler/program.ts [hunk 2]
```diff
@@ -1862,6 +1866,9 @@ export function createProgram(rootNamesOrOptions: readonly string[] | CreateProg
         redirectTargetsMap,
         usesUriStyleNodeCoreModules,
         resolvedLibReferences,
+        getCurrentPackagesMap: () => packageMap,
```
Comment (jakebailey) [inline src/compiler/program.ts:1869]: Is it possible for this call to occur before the package map has been initialized? Would we benefit from keeping the code from `checker.ts` which just memoizes it? Or, I guess just call` getPackagesMap()`?

Comment (jakebailey) [reply src/compiler/program.ts:1869]: Hm, maybe it's intentionally not getting it; I see the `oldProgram` use below.

Comment (sheetalkamat) [reply src/compiler/program.ts:1869]: this is to get it if present so that we can reuse the packageMap if program structure is same as old program., thats why not memoize

File: src/compiler/types.ts [hunk 3]
```diff
@@ -6925,6 +6929,16 @@ export interface DiagnosticMessage {
     elidedInCompatabilityPyramid?: boolean;
 }
 
+/** @internal */
+export interface RepopulateModuleNodeFoundDiagnosticChain {
```
Comment (andrewbranch) [inline src/compiler/types.ts:6933]:
```suggestion
export interface RepopulateModuleNotFoundDiagnosticChain {
```

?

**Review by andrewbranch — APPROVED** [review]
