### PR TITLE
check completions with assignable rather than identity

### LINKED ISSUE #30058: Object literal property completions not working when passed to optional parameter
```ts
// @strict: true

interface Options {
  hello?: boolean;
  world?: boolean;
}
declare function foo(options?: Options): void;

foo({
  hello: true,
  /**/
});
```

**Expected**: Completion for "world"
**Actual**: No completions

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #30058

### CODE REVIEW

File: tests/cases/fourslash/completionsWithOptionalProperties.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/// <reference path="fourslash.ts" />
+// @strict: true
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionsWithOptionalProperties.ts]: Wait, is this how options flags are specified in fourslash @sheetalkamat @RyanCavanaugh @Kingwl?

Comment (sheetalkamat) [reply tests/cases/fourslash/completionsWithOptionalProperties.ts]: Yes
