### PR TITLE
Fixes for type parameter name resolution in JS

### LINKED ISSUE #24230: JSDoc `@template` type parameters aren't resolved on prototype assignments
```js
/**
 * @constructor
 * @template K, V
 */
var Multimap = function() {
  /** @type {!Map.<K, !Set.<!V>>} */
  this._map = new Map();
};

Multimap.prototype = {
  /**
   * @param {K} key // <------ error here, 'K' not found
   * @param {V} value // <---- and here
   */
  set: function(key, value) {
    var set = this._map.get(key);
    if (!set) {
      set = new Set();
      this._map.set(key, set);
    }
    set.add(value);
  }
}
```

**Expected behavior:**
`K` and `V` are resolved to the declaration on `var Multimap = function ...`.

**Actual behavior:**
Cannot find name 'K'. and Cannot find name 'V'.

The js-specific code in resolveEntityName needs to understand prototype assignment the same way that it does prototype *property* assignment. This works fine:

```js
/**
 * @param {K} key // <------ error here, 'K' not found
 * @param {V} value // <---- and here
 */
Multimap.prototype.set = function {
}
```

### LINKED ISSUE #26826: In JS, `@template` types on constructor functions do not resolve in prototype methods
```js
var Multimap = function() {
  /** @type {!Map.<K, !Set.<!V>>} */
  this._map = new Map();
};

/**
 * @param {K} key the key ok
 * @returns {Set<V>} the value ok
 */
Multimap.prototype.get = function (key) {
    return this._map.get(key) || new Set();
}
```

**Expected behavior:**
No errors, and `Multimap<K,V>.get: (key: K) => Set<V>`

**Actual behavior:**
K and V in `@param {K}` and `@returns {Set<V>}` are not found and `get: (key: any) => any`.

Works fine if Multimap is declared as `function Multimap ...`.

Should work with prototype assignments too, eg `Multimap.prototype = { get() { ... } }`. Discovered while fixing #24230

### PR DESCRIPTION
**Pull request by sandersn**
## 1. check for expando initializers in resolveEntityName

...  when resolving type parameters in a prototype property assignment
declaration. For example, this already works:

```js
/** @template T */
function f(x) { this.x = x }
/** @returns {T} */
f.protototype.m = function () { return this.x }
```

This now works too:

```js
/** @template T */
var f = function (x) { this.x = x }
/** @returns {T} */
f.prototype.m = function () { return this.x }
```

Fixes #26826

### 2. Lookup type parameters on prototype-assignment methods  

…In the same way that they're looked up on prototype-property methods.

That is, this previously worked:

```js
/** @template T */
function f() { }
/** @param {T} p */
f.prototype.m = function () { }
```

And this now works too:

```js
/** @template T */
function f() { }
f.prototype = {
  /** @param {T} p */
  m() { }
}
```

Note that the baselines still have errors; I filed #26831 to follow up on those.

Fixes #24230

### CODE REVIEW

**Comment by andy-ms** [comment]
This isn't working when calling the method:
```ts
/**
 * Should work for function declarations
 * @constructor
 * @template {string} K
 * @template V
 */
function Multimap() {
    /** @type {Object<string, V>} TODO: Remove the prototype from the fresh object */
    this._map = {};
};
 /**
 * @param {K} key the key ok
 * @returns {V} the value ok
 */
Multimap.prototype.get = function (key) {
    return this._map[key + ''];
}

/** @type {Multimap<"a" | "b", number>} */
const map = new Multimap();
const n = map.get("a");
```

At the last line, there's an error that `"a"` isn't assignable to `K`, and `n` is of type `V` instead of `number`.

File: tests/cases/conformance/jsdoc/jsdocTemplateTag5.ts [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    /** @type {Object<string, V>} TODO: Remove the prototype from the fresh object */
+    this._map = {};
+};
+
+Multimap.prototype = {
+    /**
+     * @param {K} key the key ok
+     * @returns {V} the value ok
+     */
+    get(key) {
```
Comment (sandersn) [inline tests/cases/conformance/jsdoc/jsdocTemplateTag5.ts]: only works for methods, not properties with function values. That is, `get: function(key) ...` doesn't work

**Comment by sandersn** [comment]
@andy-ms Oof, yeah, that's a bigger limitation of the types we create for JSDoc generics. They're not really generics, and aren't instantiated using the normal instantiation code. That's not related to this fix &mdash; you'll see that the type is always just `Multimap`, although it means that the overall scenario doesn't work. Given that I'll be on vacation and DefinitelyTyped most of the rest of this release, I'm going to create a separate issue to track fixing generic types.

(Note that the 3.0 behaviour is that instances of `Multimap` are completely unaware of type parameters, so that `n: any` in your example.)

Filed #26883 to track this.
