### PR TITLE
Strict function types

### LINKED ISSUE #6102: allow a flag that turns off covariant parameters when checking function assignability
Currently the following flawed code is permitted:

```typescript
interface A { x: nuber; }
interface B { x: number, y: string }
function copyB(value: B) : B {
   return { x: value.x, y: value.y };
}
let values : A[] = [];
let copied= values.map(copyB); // <-- no problem compiling, but a problem at runtime
```

Thank to the following line: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts#L5654

I suggest to give developers a flag that would disable such unsound behavior allowing function subtyping the way it is supposed to be: https://en.wikipedia.org/wiki/Subtyping#Function_types.

An outline of a pull request of how this might look like: https://github.com/aleksey-bykov/TypeScript/commit/34b8f9b5a937cb7bb471771d5c9b9c4d4f629fc8

Related issues: #5961, #3523, #4895, #5741, #3067, #222, #5673

### LINKED ISSUE #7472: Wrongly passed code using generics and string literal types
**TypeScript Version:** 

1.8.7

compiled: `tsc --noImplicitAny error.ts`
(the behavior is exactly the same with or without `--noImplictAny`)

**Code**

```ts
// A self-contained demonstration of the problem follows...
type Greeting = "hello" | "goodbye"

const apply = <T extends string,R>(t: T, f: (t:T) => R): R => f(t)
const f1 = (a: Greeting) => console.log('greetings')
const f2 = (a: number) => console.log(3+a)

apply("hello", f1) /* 1. should be good. is good */
apply("helo", f1) /* 2a. should be error. is good */
apply<Greeting, void>("helo", f1) /* 2b. should be error. is error */

apply("hello", f2) /* 3. should be error. is error */
apply(3, f1) /* 4. should be error. is error */
apply(3, f2) /* 5. should be error. is error */

```

**Expected behavior:**
2-5 should have an error:

2 should have an error because `"helo"` is not a member of `"hello"|"goodbye"`
3 should have an error because `"hello"` is not a `number`
4 should have an error because `3` is not a member of `"hello"|"goodbye"` and because `3` is not a member of type which `extends string`
5 should have an error because `3` is not a member of a type which `extends string`, and because `number` does not `extend string`.

**Actual behavior:** 
1, 2b, 3-5 are correct
2a passes typechecking even though it should be equivalent to 2b

### LINKED ISSUE #9514: Functions with intersection arguments are not always typed coherently
**TypeScript Version:**  1.8.10

**Code**

```ts

// tl;dr: 
// This should give a static error, but does not.
var monkeyAnalyzer: (input: Monkey) => void = (input: Monkey & Robot) => { console.log(input.FurColor, input.MotorCount); }
// Will definitely fail, as we can expect from the incompatible signatures of the declared type of monkeyAnalyzer and what we actually assign to it
monkeyAnalyzer(new Monkey()); 

// Verbose example
class Monkey
{
    public FurColor: string;
}

class Robot
{
    public MotorCount: number;
}

class MonkeyRobotAnalyzer
{
    public static Analyze = (input: Monkey & Robot): void =>
    {
        console.log(input.FurColor, input.MotorCount);
    }
}

class MonkeyManager
{
    constructor(monkeyAnalyzer: (input: Monkey) => void)
    {
        monkeyAnalyzer(new Monkey());
    }
}

MonkeyRobotAnalyzer.Analyze(new Monkey()); // Shows error as it should

var myManager = new MonkeyManager(MonkeyRobotAnalyzer.Analyze); // No error, but should not be allowed, signature of MonkeyRobotAnalyzer.Analyze is not compatible with (input: Monkey) => void

```

**Expected behavior:**

The incompatible signatures should result in a static error

**Actual behavior:** 
We get no static error

### LINKED ISSUE #9765: Function shapes with union typed params incorrectly accept more restrictive functions
**TypeScript Version:**  2.0.0 beta

Functions typed to accept union typed params incorrectly typecheck against functions whose params only match a subset of the union. Example:

```ts
interface Callback {
  (value: string | number): void;
}

// expect this to work
const many: Callback = (value: string | number | boolean) => {
  // ...
}

// expect a type error here
const one: Callback = (value: string) => {
  // ...
}

many(1);       // should work, does work
one(1);        // shouldn't work, does work *
many("hello"); // should work, does work
one("hello");  // should work, does work
many(true);    // shouldn't work, doesn't work
one(true);     // shouldn't work, doesn't work
```

**Expected**
`one` throws a type error, since `string | number` is not assignable to `string`.

**Actual**
`one` compiles fine.

This comes up in real code when declaring a callback whose params may not be defined, e.g.

```ts
interface SomeLib {
  onChange: (callback: (newValue: string | null) => void) => void;
}

const foo: SomeLib = ...;
foo.onChange((newValue: string) => {
  // oops, I forgot newValue may not be defined, but this compiles
});
```

### LINKED ISSUE #12498: Array filter/map predicate not type checking properly
TS 2.0.3

See the comments and last line in the code below for expected/actual.

``` ts
{
    type Foo = { foo: true };
    const isFoo = (foo: Foo) => foo.foo;

    const xs = [{ foo: true }, undefined];

    isFoo(xs[1]) // good, errors
    const x = undefined as Foo | undefined;
    isFoo(x) // good, errors
    xs.filter(isFoo) // bad, didn't fail, expected filter arg to fail, should be Foo | undefined
}
```

### LINKED ISSUE #13248: Incorrect function parameter not detected
**TypeScript Version:**  (maybe 2.1.x - typescriptlang.org playground version as of 2017-1-2)

**Code**
[typescriptlang.org playground](http://www.typescriptlang.org/play/index.html#src=%5B1%2C%202%2C%203%5D.map(mapper)%3B%20%2F%2F%20fine%3F%3F%3F%0D%0A%5B1%2C%202%2C%203%5D.map((obj%2C%20idx)%20%3D%3E%20mapper(obj%2C%20idx))%3B%20%2F%2F%20%3C%3D%20error%0D%0A%0D%0Atype%20Tag%20%3D%20number%20%26%20%7B%20_tagBrand%3A%20any%3B%20%7D%3B%0D%0A%0D%0Afunction%20mapper%3CE%3E(obj%3A%20E%2C%20type%3A%20Tag)%20%7B%0D%0A%20%20%20%20return%20obj%3B%0D%0A%7D)
```ts
[1, 2, 3].map(mapper); // fine???
[1, 2, 3].map((obj, idx) => mapper(obj, idx)); // <= error

type Tag = number & { _tagBrand: any; };

function mapper<E>(obj: E, type: Tag) {
    return obj;
}
```

**Expected behavior:**
The first `map()` call on line 1 should throw the same compile error as the second call, since the second parameter of the mapper function does not match the second parameter of the function expected by Array.map()

**Actual behavior:**
No compile error on the first map() call when it should.

Found while working on nominal types based on [basarat's git book 'Nominal Typings' section](https://basarat.gitbooks.io/typescript/content/docs/tips/nominalTyping.html). 

Reproduced in VS 2015 update 3 TypeScript 2.1.4 and the typescriptlang.org playground.

### LINKED ISSUE #15579: Lack of type checking for callback parameters
**TypeScript Version:**  master

**Code**

```ts
function f(g: (ev: Event) => any) { }
function g(ev: MouseEvent) { }
f(g);
f(ev => g(ev));
```

**Expected behavior:**

```
$ node built/local/tsc.js index.ts --noEmit --strict
index.ts(3,3): error ...
index.ts(4,11): error TS2345: Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'.
  Property 'altKey' is missing in type 'Event'.
```

**Actual behavior:**

```
$ node built/local/tsc.js index.ts --noEmit --strict
index.ts(4,11): error TS2345: Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'.
  Property 'altKey' is missing in type 'Event'.
```

### LINKED ISSUE #18337: Invalid function assignment is not detected
**TypeScript Version:**  2.5.0 

**Code**

```ts
const a: (d: string) => number = (d) => d.length;
const b: (d?: string) => number = a;
b();
```

**Expected behavior:**
When compiled with `--strict`, the assignment of `b` should cause a type error along the lines of:  

> `string | undefined` is not assignable to type `string`.

**Actual behavior:**
The code compiles with `--strict`, then throws an exception at runtime on the expression `d.length`.

### LINKED ISSUE #18466: Typescript type checks passing a callback with non-optional parameter for optional one, but throws error at runtime
**TypeScript Version:**  2.4.1

**Code**
```
function f(callback: (a: string, b?: string) => void) {
    callback("a", undefined);
}

f((a: string, b: string) => {
    console.log(a.length, b.length);
});
```

**Expected behavior:**
Compile error with when compiled with the `strict` flag.
`(a: string, b: string) => void` is not a subtype of `(a: string, b?: string) => void` as `string` is not a supertype of `string | undefined`, I expected a compile error.

**Actual behavior:**
Compiles, but throws error at runtime

```
console.log(a.length, b.length);
                       ^

TypeError: Cannot read property 'length' of undefined
    at /Users/Ali/test.js:11:28
    at f (/Users/Ali/test.js:3:5)
    at Object.<anonymous> (/Users/Ali/test.js:10:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we introduce a `--strictFunctionTypes` mode in which function type parameter positions are checked _contravariantly_ instead of _bivariantly_. The stricter checking applies to all function types, except those originating in method or construcor declarations. Methods are excluded specifically to ensure generic classes and interfaces (such as `Array<T>`) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant (even so, we may continue to explore this stricter mode).

The `--strictFunctionTypes` switch is part of the `--strict` family of switches, meaning that it defaults to on in `--strict` mode. This PR is therefore a breaking change only in `--strict` mode.

Consider the following example in which `Animal` is the supertype of `Dog` and `Cat`:

```ts
declare let f1: (x: Animal) => void;
declare let f2: (x: Dog) => void;
declare let f3: (x: Cat) => void;
f1 = f2;  // Error with --strictFunctionTypes
f2 = f1;  // Ok
f2 = f3;  // Error
```

The first assignment is permitted in default type checking mode, but flagged as an error in strict function types mode. Intuitively, the default mode permits the assignment because it is _possibly_ sound, whereas strict function types mode makes it an error because it isn't _provably_ sound. In either mode the third assignment is an error because it is _never_ sound.

Another way to describe the example is that the type `(x: T) => void` is _bivariant_ (i.e. covariant _or_ contravariant) for `T` in default type checking mode, but _contravariant_ for `T` in strict function types mode.

Another example:

```ts
interface Comparer<T> {
    compare(a: T, b: T): number;
}

declare let animalComparer: Comparer<Animal>;
declare let dogComparer: Comparer<Dog>;

animalComparer = dogComparer;  // Ok because of bivariance
dogComparer = animalComparer;  // Ok
```

In `--strictFunctionTypes` mode the first assignment is still permitted because `compare` is declared as a method. Effectively, `T` is bivariant in `Comparer<T>` because it is used only in method parameter positions. However, changing `compare` to be a property with a function type causes stricter checking to take effect:

```ts
interface Comparer<T> {
    compare: (a: T, b: T) => number;
}

declare let animalComparer: Comparer<Animal>;
declare let dogComparer: Comparer<Dog>;

animalComparer = dogComparer;  // Error
dogComparer = animalComparer;  // Ok
```

The first assignment is now an error. Effectively, `T` is contravariant in `Comparer<T>` because it is used only in function type parameter positions.

By the way, note that whereas some languages (e.g. C# and Scala) require variance annotations (`out`/`in` or `+`/`-`), variance emerges naturally from the actual use of a type parameter within a generic type due to TypeScript's structural type system.

We also improve type inference involving contravariant positions in this PR:

```ts
function combine<T>(...funcs: ((x: T) => void)[]): (x: T) => void {
    return x => {
        for (const f of funcs) f(x);
    }
}

function animalFunc(x: Animal) {}
function dogFunc(x: Dog) {}

let combined = combine(animalFunc, dogFunc);  // (x: Dog) => void
```

Above, all inferences for `T` originate in contravariant positions, and we therefore infer the *best common subtype* for `T`. This contrasts with inferences from covariant positions, where we infer the *best common supertype*. Note that inferences from covariant positions have precedence over inferences from contravariant positions.

Fixes #6102.
Fixes #7472.
Fixes #9514.
Fixes #9765.
Fixes #12498.
Fixes #13248.
Fixes #15579.
Fixes #18337.
Fixes #18466.

Also related are #10717 and #14973.

### CODE REVIEW

**Comment by sandersn** [comment]
I ran RWC on this and saw changes only in elaborations and order of printing union types. No errors were added or removed, and no types changed.

The changes appear to result from better type caching leading to less elaboration. The only interesting result was from the Azure Framework tests, where one incorrectly duplicated error disappeared entirely, maybe because the whole error was already issued just prior.

I'll run DefinitelyTyped next and look for diffs.

**Comment by ahejlsberg** [comment]
@sandersn When running DefinitelyTyped, be sure to run both with and without `--strict`. I'm particularly interested in the results with `--strict`.

**Comment by sandersn** [comment]
Ah, good point. I forgot `--strict` the first time around. First I compiled everything using 0ac8406, the commit before this PR. Then I compiled again with this PR's commits and diffed the changes. Interestingly, a few packages on DefinitelyTyped still have more errors even without `--strictFunctionTypes`. The errors look like they come from tighter variance checking too, so it's likely that some changes are escaping from behind the flag.

Take a look at the test files for recompose, rx-lite and rx.wamp (which depends on rx-lite). Recompose is clearer to see (the rx* errors are obscured by overloads in rx-lite):

```
recompose-tests.tsx(248,7): error TS2345: Argument of type 'InferableComponentEnhancerWithProps<{ count: number; } & { update: (state: number) => number; }, {}>' is not assignable to parameter of type 'ComponentEnhancer<any, any> | InferableComponentEnhancerWithProps<{}, {}>'.
  Type 'InferableComponentEnhancerWithProps<{ count: number; } & { update: (state: number) => number; }, {}>' is not assignable to type 'InferableComponentEnhancerWithProps<{}, {}>'.
    Type '{}' is not assignable to type '{ count: number; } & { update: (state: number) => number; }'.
      Type '{}' is not assignable to type '{ count: number; }'.
        Property 'count' is missing in type '{}'.
```

Notice that the direction of assignability switches, I think because of contravariance.

In total, I noticed changes with
* recompose
* rx-lite
* rx.wamp (for nearly the same reason)
* jasmine
* a few other projects had different line numbers for errors in lib.d.ts, which doesn't make sense to me.

I'll take a look at the results with `--strictFunctionChecks` turned on next. It's only halfway done, but there are already lots of failures, so I'll only provide a summary.

**Comment by ahejlsberg** [comment]
@sandersn With the latest commits we revert to always performing a structural comparison when the relationships indicated by `getVariances` don't hold. In effect, the variance information computed by `getVariances` is now an indication of which relationships to try first as an optimization, but it doesn't preclude other relationships. In the default checking mode we now behave exactly the same way as before, so I would expect no changes to RWC baselines or DefinitelyTyped. I would expect to see new errors only in `--strictFunctionTypes` mode.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2517,7 +2522,7 @@ namespace ts {
                     return typeReferenceToTypeNode(<TypeReference>type);
                 }
                 if (type.flags & TypeFlags.TypeParameter || objectFlags & ObjectFlags.ClassOrInterface) {
-                    const name = symbolToName(type.symbol, context, SymbolFlags.Type, /*expectsIdentifier*/ false);
+                    const name = type.symbol ? symbolToName(type.symbol, context, SymbolFlags.Type, /*expectsIdentifier*/ false) : createIdentifier("?");
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: When does this case occur?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -10060,6 +10129,11 @@ namespace ts {
                 getUnionType(types, /*subtypeReduction*/ true);
         }
 
+        // Return the leftmost type for which no type to the right is a subtype.
+        function getCommonSubtype(types: Type[]) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: We've missed you, old friend

**Comment by RyanCavanaugh** [comment]
LGTM but I'd like to see what happens if we run RWC with this forced on

**Comment by sandersn** [comment]
With the latest commits, both RWC and DT crash much more due to running out of memory. I only get about 2/3 of the RWC tests to succeed, and DT crashes at 'bookshelf'.

**Comment by ahejlsberg** [comment]
@sandersn Is that with or without `--strictFunctionTypes`?

**Comment by sandersn** [comment]
With --strictFunctionTypes

**Comment by ahejlsberg** [comment]
@sandersn It is likely because we do more structural comparisons of types. There are enough edge cases (e.g. `any` or `void` type arguments) where types don't act exactly according to the gathered variance information, so if the optimized first check of the type arguments doesn't succeed we need to do a structural comparison. We'll have to look at the specific cases, but it's not clear what else we could do.

**Comment by sandersn** [comment]
DefinitelyTyped/types/bookshelf is probably smaller than any of the RWC projects -- it depends on Bluebird and lodash, and is itself 300 lines + 1400 lines of test. And it's easy to repro by just cloning DefinitelyTyped and running `tsc --strictFunctionTypes` inside `DefinitelyTyped/types/bookshelf`.

**Comment by sandersn** [comment]
After discussion with @mhegazy, we think it's likely that it's to avoid the structural fallback whenever possible. Probably it's better to 

1. Just issue some errors even when the flag is off, as in 589e1f4
Or
2. Skip the variance information entirely when the flag is off -- just use the old covariance-allowed path.

If we decide to do (1), we can merge this PR and see whether people who are not using the flags hit problems in real usage, since the errors in Definitely Typed seem to be correct. I'll report back on RWC results from 589e1f4 with --strict on, once I have a good summary.

**Comment by ahejlsberg** [comment]
@sandersn @mhegazy As the PR currently stands, when `--strictFunctionTypes` is off the variance computation is bypassed and we just assume covariance as we used to. That's what saves us in `DefinitelyTyped/types/bookshelf` in regular checking mode. The issue with `bookshelf` is actually `lodash`, whose typings contain some infinitely recursive types (the `LoDashXXXWrapper` generic types) that generate enormous amounts of work when compared structurally. And we end up comparing them structurally in `--strictFunctionTypes` mode because they are neither covariant nor contravariant.

**Comment by ahejlsberg** [comment]
Latest commits limit strict function type checking to function types originating in function type literals, constructor type literals, function expressions, arrow functions, and non-overloaded function declarations.

**Comment by ahejlsberg** [comment]
@sandersn Try running DefinitelyTyped through this latest iteration. I would expect no changes in regular type checking mode and better behavior in `--strictFunctionTypes` mode since we no longer fall back to structural comparisons when the variance based checks fail.

**Comment by ahejlsberg** [comment]
@sandersn I ran all of the DefinitelyTyped tests and I'm looking through the results right now. Overall looks good. Most typings are unaffected, and the errors I'm seeing appear correct and so far only occur in tests and not the typings themselves.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: This happens when we have a synthetic type parameter, such as the type parameters we create for tuple types and the `markerXXXType` type parameters we use for variance determination.

**Comment by ahejlsberg** [comment]
@mhegazy @sandersn @RyanCavanaugh Below is a list of the DefinitelyTyped packages that have new errors when compiled in `--strictFunctionTypes` mode. All of the errors occur in the tests associated with the packages, but in some cases the fix is actually in the .d.ts files themselves.

For the vast majority we are looking at one of two fixes: Either change the .d.ts file to use a bivariant function type instead of a contravariant one (e.g. `{ (x: Foo): Bar }` instead of `(x: Foo) => Bar`), or fix the test to pass arguments that are properly contravariant. The former fix is appropriate in cases where the bivariant behavior is actually intended, e.g. with the "covariant event pattern" where an event object type co-varies alongside a class or interface hierarcy.

In some cases the fix is more involved. For example, `lodash` declares some `LoDashXXXWrapper` types that previously were covariant (because _every_ generic interface was covariant) but now become invariant. The types are complicated (to say the least) so there may be a bit of work involved there. It appears to me that a simpler solution might be possible using `this` types.

Beyond that, I think the PR is ready to go. Take a look at let me know what you think.

```
adone
angular
angular-odata-resources
angular-resource
array-foreach
async
aws-serverless-express
backbone.marionette
backgrid
baconjs
blazy
bluebird
bunnymq
c3
csrf
cucumber
d3-array
d3-axis
d3-contour
d3-request
d3-selection
d3-shape
d3-transition
d3.cloud.layout
documentdb
doubleclick-gpt
dygraphs
electron-packager
express
express-brute-redis
express-myconnection
fabric
fs-extra
fs-finder
gl-matrix
globule
gulp-connect
i18next
jasmine
jsforce
jsnox
knockout
leaflet-draw
lockfile
lodash
log4js
mapbox
meteor
mongoose-sequence
ng-file-upload
node
node-statsd
node-zookeeper-client
nvd3
openfin
openlayers
p-event
p-map
passport-saml
phonegap-facebook-plugin
pigpio
pouchdb-core
pouchdb-replication
pouchdb-upsert
q
qlik
ramda
react
react-codemirror
react-datagrid
react-dom
react-list
react-native
react-native-elements
react-native-modalbox
react-native-snap-carousel
react-native-touch-id
react-navigation
react-notification-system
react-router
react-slick
react-virtual-keyboard
react-virtualized
recompose
redlock
redux-actions
redux-form
restful.js
rrc
rx-lite
rx.wamp
saml20
selenium-webdriver
sharepoint
sharp
siesta
steed
stripe-node
stripe-v3
strong-cluster-control
svg-injector
validate.js
voca
voximplant-websdk
webdriverio
webgme
when
ws
xrm
yandex-maps
yog2-kernel
```

**Comment by gcnew** [comment]
I think the method vs non-method distinction is subtle and confusing. Although it seems convenient to use a slight syntactic difference, it by not means conveys any meaningful information. Please, use a more definitive differentiator or better, an explicit cue.

File: tests/cases/compiler/strictFunctionTypes1.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
+// @strict: true
```
Comment (sandersn) [inline tests/cases/compiler/strictFunctionTypes1.ts]: Can you add `@declare: true` so that we get a baseline for d.ts output?

**Comment by ahejlsberg** [comment]
@gcnew I agree the distinction between bivariant `{ (x: Foo): Bar }` and contravariant `(x: Foo) => Bar` is somewhat subtle. On the other hand, it is already the case that methods are bivariant, and signatures look just like methods without a name, so in that sense it is reasonably consistent. We did try to think of other ways to distinguish, but honestly the alternatives just seem worse. I don't think anyone wants to see explicit `bivariant` or `contravariant` modifiers, or cryptic `+` and `-` annotations. As it stands now, you can think of it this way: Functions types that originate within curlys are bivariant, whereas function types declared with arrows are strictly contravariant.

**Comment by ikokostya** [comment]
> I don't think anyone wants to see explicit bivariant or contravariant modifiers

Why do you think so?

**Comment by ahejlsberg** [comment]
> Why do you think so?

Because in the vast majority of cases it is just noise. Variance doesn't matter when a function is called but is relevant only in function assignments, and even then it is typically of no consequence.

**Comment by pelotom** [comment]
@ahejlsberg does this mean an overloaded function type like

```ts
{
   (a: A): void
   (b: B): void
}
```

 can't be checked covariantly?

**Comment by ahejlsberg** [comment]
@pelotom You mean can't be checked contravariantly, yes? 😉 Yes, if you declared a type like that and used it as the target type in an assignment, it would be checked bivariantly (but already we also do type parameter erasure when relating function types with overloads, so there's a limit to how strictly they're checked anyway). The question is, have you ever *explicitly* declared such a type and used it as the type of a callback because that's when the distinction would actually matter?

**Comment by pelotom** [comment]
@ahejlsberg sorry, yes, I meant contravariantly.

Here's a [real world example](https://github.com/callemall/material-ui/blob/1a146b8fcf38df0100e20c23ff692a593300601f/src/styles/withStyles.d.ts#L29-L47). I believe the bivariant treatment of this signature is behind the type unsafety mentioned [here](https://github.com/callemall/material-ui/pull/8399#issuecomment-332177063).

**Comment by aleksey-bykov** [comment]
what a great time to be alive! thank you!

**Comment by goodmind** [comment]
I don't think that `+` and `-` any noisier than anything other in TS

**Comment by ahejlsberg** [comment]
After discussing the feedback on the subtlety of having `{ (x: Foo): Bar }` be bivariant and `(x: Foo) => Bar` be contravariant we've decided to have `--strictFunctionTypes` mode require pure contravariance for all function types except those originating in method and constructor declarations. This causes a few more packages on DefinitelyTyped to have errors in their tests, but still only about 3% of the packages are affected. I have updated the list in my previous comment.

I'm considering implementing the ability to specify variance annotations (or rather variance assertions) on type parameters. We would allow `in` or `out` (or both) to precede a type parameter as an assertion that the type parameter behaves contravariantly or covariantly (or both) and issue an error if the assertion is not true. The error would be helpful in determining *why* the type parameter doesn't have the appropriate variance, which can be quite difficult to determine manually. Just as an example, in `--strictFunctionTypes` mode the `JQuery<T>` and `JQueryStatic<T>` types in the `jquery` package on DefinitelyTyped become invariant. This causes a number of errors and it was quite complicated to determine why.

File: src/compiler/types.ts [hunk 4]
```diff
@@ -3522,9 +3532,10 @@ namespace ts {
     }
 
     export const enum InferencePriority {
```
Comment (sandersn) [inline src/compiler/types.ts]: should probably be `@internal`

File: src/compiler/types.ts [hunk 5]
```diff
@@ -3343,10 +3344,19 @@ namespace ts {
         typeArguments?: Type[];  // Type reference type arguments (undefined if none)
     }
 
+    export const enum Variance {
```
Comment (sandersn) [inline src/compiler/types.ts]: should be probably `@internal`

**Comment by goodmind** [comment]
@ahejlsberg something like this?
```ts
type T = <out T, in U>(x: T) => U
```

**Comment by sandersn** [comment]
As we expected, lodash has been difficult to fix completely. Here's the trickiest problem I ran into (Thanks to @DanielRosenwasser for figuring out why it was going wrong):

```ts
// @Filename: lodash.d.ts
type F = (value: any, srcValue: any, key: string, object: any, source: any) => any;

interface LoDashStatic {
    mergeWith<T, T1>(object: T, source: T1, f: F): T & T1;
    mergeWith<T, T1, T2>(object: T, source1: T1, source2: T2, f: F): T & T1 & T2;
    mergeWith<T, T1, T2, T3>(object: T, source1: T1, source2: T2, source3: T3, f: F): T & T1 & T2 & T3;
    mergeWith<T>(object: any, ...otherArgs: any[]): T;
}

    declare let f: (value: any, srcValue: any, key: string, object: InitialValue, source: MergingValue) => any;

// @Filename: tests.ts
interface InitialValue { a }
interface MergingValue { b }
declare let f: (value: any, srcValue: any, key: string, object: InitialValue, source: MergingValue) => any;

// Test for basic merging
declare let init: InitialValue;
declare let m: MergingValue;
result = _.mergeWith(init, m, f);
result = _.mergeWith(init, {}, m, f);
result = _.mergeWith(init, {}, {}, m, f);

// Once we get to the varargs version, you have to specify the result explicitly
result = _.mergeWith<ExpectedResult>(init, {}, {}, {}, {}, m, f);
```

`mergeWith` is basically similar to object spread. The problem is that when the last, variadic-any[] overload is included, the calls that should match earlier overloads instead match the last overload. We think this is because `f` is compared strictly to `F` and the last two parameters, `object: any, source: any`, hit the odd behaviour of `any`. Specifically, `any` isn't a subtype of `InitialValue` or `MergingValue` (even though it's assignable, of course). So instead the last overload wins.

This doesn't explain why the first three calls work without the variadic-any[] overload, though. 

It's worth noting that (1) if you change  to `object: never, source: never`, then everything works or (2) if you use the bivariance hack then everything works. So the source of the problem is definitely the use of the type `F`.

**Comment by weswigham** [comment]
@sandersn Does the lodash function work better when you use `object` or `{}` instead of `any`?

**Comment by sandersn** [comment]
Nope, same result as any.

File: src/compiler/types.ts (hunk 4 above)
Comment (ahejlsberg) [reply src/compiler/types.ts]: Probably, but not really related to this PR since the type already existed before. I'm going to leave it be for now.

File: src/compiler/types.ts (hunk 5 above)
Comment (ahejlsberg) [reply src/compiler/types.ts]: Fixed

**Comment by ahejlsberg** [comment]
@goodmind Yes, but with the opposite annotations if you don't want errors. 😉

```ts
type F = <in T, out U>(x: T) => U;  // Contravariant T, covariant U
```

BTW, co- and contravariance assertions would just be a convenience and aren't actually required for any of the functionality in this PR. Because the type system is structural, variance simply emerges from the actual use of a type parameter within a type. For this reason, if we end up adding variance assertion support it would be covered in a separate PR.

**Comment by ahejlsberg** [comment]
@mhegazy I think this one is good to go. Let me know if you have comments.

**Comment by ahejlsberg** [comment]
@sandersn Regarding name of the flag, I prefer `--strictFunctionTypes` over `--strictFunctionVariance`. If nothing else because it is shorter and doesn't immediately require you to explain what variance is.

**Comment by Igorbek** [comment]
@ahejlsberg @goodmind My understanding is that `in`/`out` annotations would be useful to declare a promise to use only properties that have given type in specific variance positions. Such as if one uses `Array<out T>` that means he uses methods like `pop` and indexer reads. On other hand, `Array<in T>` would mean that `push` or indexer writes could be used.

That being said, yes `<in T, out U>(x: T) => U` doesn't really make sense. But `<in T, out U>(x: T[]) => U[]` or `<T, U>(x: (in T)[]) => (out U)[];` completely makes sense.

**Comment by ahejlsberg** [comment]
@Igorbek No, I was merely speculating about annotations/assertions that would be checked. For example, `type F<out T> = (x: T) => void` would report an error because the assertion states that `T` is covariant (used in output positions only) but the type uses it in a contravariant manner (in an input position).

**Comment by goodmind** [comment]
@ahejlsberg there's case for this though:

```ts
type TypedLogger<in Text> = (text: Text) => void

type MapLogger<out IN, in OUT> = (logger: TypedLogger<IN>) => TypedLogger<OUT>
```

**Comment by JsonFreeman** [comment]
What a cool feature! And great idea with the best common subtype!

File: tests/cases/compiler/strictFunctionTypes1.ts (hunk 3 above)
Comment (mhegazy) [reply tests/cases/compiler/strictFunctionTypes1.ts]: +1

**Comment by ahejlsberg** [comment]
Latest commits address code review feedback. Also, we improve error elaboration for generic types where one or more type parameters are invariant. In some cases generic types that are covariant in regular type checking mode become invariant in `--strictFunctionTypes` mode because one or more type parameters are used in both co- and contravariant positions with the generic type. In order to make it easier to diagnose *why* such types are invariant, if any of the type parameters are invariant we reset the reported errors and instead force a structural comparison (which will include elaborations that reveal the reason).

**Comment by goodmind** [comment]
@ahejlsberg do you have feedback on my latest example?

**Comment by xnnkmd** [comment]
@ahejlsberg Even though you mention only 3% of type packages are affected, I think the real negative impact is in much higher considering that major packages like angular, express, hapi, cucumber, selenium-webdriver etc. are affected. Hopefully the undocummented "skipLibCheck" option can rescue some projects.

**Comment by ahejlsberg** [comment]
@xnnkmd The list above doesn't show it, but in practically all cases (including all of the ones you mention) the errors are in the *tests* associated with the type package, not in the package itself. So, there should be no need to use `--skipLibCheck`.

**Comment by styfle** [comment]
> the errors are in the tests associated with the type package, not in the package itself

@ahejlsberg Can you post a list of packages where only the package itself is affected? (not the tests)

**Comment by aleksey-bykov** [comment]
gentlemen, pardon me, but i don't understand your attitude towards these mighty new features... even if we break 97% of all code out there, even then:

- it's **under the flag** `--strictFunctionTypes`, so if you are scared of it, stay away from it! so if you did stay away from it, you are in the old safe TypeScript **and nothing brakes**

- secondly, the code that breaks is ill and it's a good thing that you see it breaks, it means you know where you weak parts are, so please be grateful, will you?

**Comment by sandersn** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20219 fixes the packages on DefinitelyTyped that break with --strictFunctionTypes. Plus it updates the tests for many "popular" packages whose tests will break so you can take a look to see how you might have to update your code. (Here, "popular" just means a random selection packages I have heard of.)

Packages fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20219:

* backbone
* bootbox
* cordova-plugin-appbrowser
* ibm-mobilefirst
* jointjs
* jquery
* knockout
* lodash
* ramda
* react


I also fixed tests in
* node
* log4js
* q
* react-native
* react-redux
* sharepoint
* webpack
