### PR TITLE
For completions of union type, get all possible properties

### LINKED ISSUE #6405: Does not work suggestion and autocompletion with union types
``` ts
function f(p: void | PropertyDescriptor) {
}
f({}); // does not suggest parameter object properties.
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #6405 and #15428.

When providing completions for a union type, we will now iterate over all union members to get all possible properties, rather than just those common to the union. So for `{ a, b } | { b, c }` we will give completions for `a, b, c` instead of just `b`.

The implementation of `getAllPossiblePropertiesOfType` could possibly be better, so it needs review from someone familiar with the checker.

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -813,19 +813,16 @@ namespace ts.Completions {
...
-            let typeForObject: Type;
+            let typeMembers: Symbol[];
             let existingMembers: Declaration[];
 
             if (objectLikeContainer.kind === SyntaxKind.ObjectLiteralExpression) {
                 // We are completing on contextual types, but may also include properties
                 // other than those within the declared type.
                 isNewIdentifierLocation = true;
-
-                // If the object literal is being assigned to something of type 'null | { hello: string }',
```
Comment (andy-ms) [inline src/services/completions.ts]: No longer need to explicitly handle `null` unions since we handle *all* unions now.

**Comment by mhegazy** [comment]
thanks!
