### PR TITLE
Explicit `types` should prevent ATA from doing package.json discovery

### LINKED ISSUE #47709: [BUG][javascript] "types" compiler option in jsconfig.json doesn't work
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0-insider
- OS Version: Mac OS 12.1

Steps to Reproduce:

Copy of https://github.com/MicrosoftDocs/intellicode/issues/328.
CC @minestarks @tjx666
 
User reports "types" compiler option in jsconfig.json doesn't work
1. "When I enable this extension, you can see that I can still get the suggest from @types/node."
image
2. "But no issue in typescript project or disable this extension in js project:"
image

We believe that this issue relates more to JS/TS IntelliSense support than IntelliCode.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #47709

This is a much simpler version of #49275 that I’m much happier with. Thanks @sheetalkamat for the suggestion.

Explicit `types` in a jsconfig/tsconfig does not prevent ATA from pulling in typings for unresolved imports, but it does prevent it from automatically pulling in things just because they’re listed in a package.json file.

### CODE REVIEW

File: src/testRunner/unittests/tsserver/typingsInstaller.ts [hunk 1]
```diff
@@ -964,13 +969,49 @@ namespace ts.projectSystem {
...
+            // Explicit types prevent automatic inclusion from package.json listing
+            testConfiguredProjectNodeModules({
+                jsconfigContent: { compilerOptions: { types: [] } },
+                jQueryJsInProjectBeforeInstall: false,
+                jQueryDtsInProjectAfterInstall: false,
+            });
+        });
+
+        it("configured projects discover from node_modules - explicit types", () => {
+            // A type reference directive will not resolve to the global typings cache
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tsserver/typingsInstaller.ts:999]: Should it though especially if `typeRoots` is not specified?

Comment (sheetalkamat) [reply src/testRunner/unittests/tsserver/typingsInstaller.ts:999]: Actually if program has "types" and that type is not present it should be part of unresolved import list right ?. Can you add real tsserver end to end test for this so we can verify.

**Review by zkat — APPROVED** [review]
I think this works well! 👍🏻

File: src/testRunner/unittests/tsserver/typingsInstaller.ts (hunk 1 above)
Comment (andrewbranch) [reply src/testRunner/unittests/tsserver/typingsInstaller.ts:999]: I convinced myself it actually should not [here](https://github.com/microsoft/TypeScript/pull/49275#discussion_r889152599):

> In other words, unresolved imports can trigger special resolution behavior because imports first and foremost are written for use at runtime; bringing in the typings on top of them is an added bonus to help your experience at design time. Type reference directives (including `"types"`) are different because they have no runtime purpose; if you wrote them, you were intentionally using a TypeScript-only feature and you should do so completely by installing the types/dependencies you say you want to reference.

**Review by sheetalkamat — APPROVED** [review]
