### PR TITLE
fix(50435): Duplicate seeming Code Actions for convert const to let

### LINKED ISSUE #50435: Duplicate seeming Code Actions for convert const to let
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

When there are multiple items that need to be quickfixed, seems like it creates duplicate `valdiCodeActions`

Accessible from both `ctrl + .` and from the hover to open the quickfix version of the code action widget.

See below: 

With only one instance of incorrect var:
Screen Shot 2022-08-24 at 2 54

With multiple instances:
Screen Shot 2022-08-24 at 2 53

Gif!
Recording 2022-08-24 at 15 00 12

Error message from Insider Console upon clicking the duplicated option:
Screen Shot 2022-08-24 at 2 59 1

### PR DESCRIPTION
**Pull request by a-tarasyuk**
FIxes #50435

### CODE REVIEW

File: src/services/codefixes/convertConstToLet.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ namespace ts.codefix {
             if (range === undefined) return;
 
             const changes = textChanges.ChangeTracker.with(context, t => doChange(t, sourceFile, range));
-            return [createCodeFixAction(fixId, changes, Diagnostics.Convert_const_to_let, fixId, Diagnostics.Convert_const_to_let)];
+            return [createCodeFixActionWithoutFixAll(fixId, changes, Diagnostics.Convert_const_to_let)];
```
Comment (DanielRosenwasser) [inline src/services/codefixes/convertConstToLet.ts:14]: Does this mean that something like

```ts
const a = 1;
const b = 1;

a = 2;
b = 2;
```

will no longer get a fix-all for both `a` and `b`?

Comment (a-tarasyuk) [reply src/services/codefixes/convertConstToLet.ts:14]: @DanielRosenwasser The current implementation doesn't support `Fix All`, it uses `createCodeFixAction`, however, there is no `getAllCodeActions` implementation, as a result, we get `Fix All` action which does absolutely nothing. So I guess instead of using `createCodeFixAction` we should use `createCodeFixActionWithoutFixAll`.

--- 
It would be nice to have a `Fix All` action, however, there are a couple of questions

```ts
const a = 1;
a = 1; // Convert const to let 
a = 1; // Convert const to let 
```

We get two similar errors, do we need to have a `Fix All` action?

So it looks like we need to group by symbol id, however, which node should have the `Fix All` action?

```ts
const a = 1;
a = 1; // Convert const to let ? Fix All
a = 1; // Convert const to let ? Fix All

const b = 1;
b = 1; // Convert const to let ? Fix All
b = 1; // Convert const to let ? Fix All
```

Comment (DanielRosenwasser) [reply src/services/codefixes/convertConstToLet.ts:14]: I think this is similar to the issue on missing object-like constraints (which @weswigham and you have each worked on a bit).

Are we limited to having a single fix-all on each node? Is it bad to have the same fix-all on each of these?

**Comment by DanielRosenwasser** [comment]
Would you rather I file a separate issue for the fact that this refactoring discards trivia?

```ts
/// <reference path="someFile.d.ts" />

// @ts-check

// all of these comments should be preserved
const x = 123;
x = 456;
```

**Review by DanielRosenwasser — APPROVED** [review]
