### PR TITLE
Project tests update

### LINKED ISSUE #4697: Project baselines sometimes cannot be accepted
If a project test baseline fails, a `jake baseline-accept` doesn't currently seem to work.

### PR DESCRIPTION
**Pull request by mhegazy**
- make project tests run in the browser
- Fix #4697, by ensuring output is always emitted
- some general cleanup

### CODE REVIEW

File: src/harness/runner.ts [hunk 1]
```diff
@@ -40,21 +40,27 @@ let testConfigFile =
     Harness.IO.fileExists(mytestconfig) ? Harness.IO.readFile(mytestconfig) :
     (Harness.IO.fileExists(testconfig) ? Harness.IO.readFile(testconfig) : "");
 
+type TestConfig = {
```
Comment (DanielRosenwasser) [inline src/harness/runner.ts]: `interface`

File: src/harness/projectsRunner.ts [hunk 2]
```diff
@@ -463,33 +463,40 @@ class ProjectRunner extends RunnerBase {
...
 
+                    // it("SourceMapRecord for (" + moduleNameToString(moduleKind) + "): " + testCaseFileName, () => {
+                    //     if (compilerResult.sourceMapData) {
+                    //         Harness.Baseline.runBaseline("SourceMapRecord for (" + moduleNameToString(compilerResult.moduleKind) + "): " + testCaseFileName, getBaselineFolder(compilerResult.moduleKind) + testCaseJustName + ".sourcemap.txt", () => {
+                    //             return Harness.SourceMapRecorder.getSourceMapRecord(compilerResult.sourceMapData, compilerResult.program,
+                    //                 ts.filter(compilerResult.outputFiles, outputFile => Harness.Compiler.isJS(outputFile.emittedFileName)));
+                    //         });
+                    //     }
+                    // });
+
```
Comment (DanielRosenwasser) [inline src/harness/projectsRunner.ts]: This needs to be removed

File: tests/webTestServer.ts [hunk 3]
```diff
@@ -48,6 +48,53 @@ function log(msg: string) {
     }
 }
 
+
+let directorySeparator = "/";
```
Comment (DanielRosenwasser) [inline tests/webTestServer.ts]: `const`

File: src/harness/runner.ts [hunk 4]
```diff
@@ -40,21 +40,27 @@ let testConfigFile =
...
+    const testConfig = <TestConfig>JSON.parse(testConfigFile);
     if (testConfig.light) {
         Harness.lightMode = true;
     }
 
     if (testConfig.stackTraceLimit === "full") {
         (<any>Error).stackTraceLimit = Infinity;
     }
-    else if ((testConfig.stackTraceLimit | 0) > 0) {
+    else if ((+testConfig.stackTraceLimit | 0) > 0) {
```
Comment (DanielRosenwasser) [inline src/harness/runner.ts]: You shouldn't need to use a `+` here, that's what the `|` does.
