### PR TITLE
 Make T[never] = never instead of erroring or being any

### LINKED ISSUE #22042: T[keyof T] should be never for T={}
**TypeScript Version:**  2.8.0-dev.20180216

**Search Terms:** 
- indexed access type
- keyof
- never

**Code**

```ts
type A = {};
type B = A[keyof A];    // B = any
        // ^^^^^^^      // ERROR: 'never' cannot be used as an index type
```

**Expected behavior:**
`A[keyof A]` is a valid indexed access type that evaluated to `never`.

**Actual behavior:**
`A[keyof A]` is treated as an error, and evaluates to `any` (presumably due to compiler bailout).

**Related Issues:**

#11929 describes indexed access types as follows:

> An indexed access type `T[K]` requires `K` to be a type that is assignable to `keyof T` [...] and yields the type of the property or properties in `T` selected by `K`.

In this case `K=never` and `T={}`, so `K` is assignable to `keyof T`, so `T[K]` appears to be a valid type.

The union of zero property keys is `never`, as tsc shows with `keyof {} = never`.

So the result should be the union of zero property types, i.e. also `never`.

**Consequences:**

In more complex generics this leads to meaningful problems, e.g. in #21988 where `RequiredProps<{}>` evalutes to `{[x: string]: any}` when it should be `{}`.

### PR DESCRIPTION
**Pull request by kpdonn**
This change makes it so that when indexing a type with `never`(e.g. `T[never]`), the result is `never`. Previously it was an error to explicitly index a type with `never` and it would non-intuitively become `any` if it was inferred somewhere inside generics. 

There is more discussion about the reasoning for the change and the implications of it from @sandersn and @yortus in #22042.

Fixes #22042

### CODE REVIEW

**Comment by yortus** [comment]
@kpdonn maybe clarify that this change only affects types with no index signature. So for example:
- `{[x: string]: boolean}[never]` is `boolean` (unchanged behaviour)
- `{foo: boolean}[never]` is `never` (new behaviour, previously was an error)

With that qualification, this is a non-breaking change because it only affects cases that are currently errors.

**Comment by mhegazy** [comment]
@ahejlsberg and @sandersn any comments?

**Comment by sandersn** [comment]
After discussing it in person with @ahejlsberg, we didn't like the fact that `({ [n: number]: boolean})[never]` is inconsistent: it's not `never` like everything else, just to make sure that lodash doesn't break. To fix this inconsistency, we are thinking about (finally) introducing the numeric-string type, which would what `keyof { [n: number]: boolean }` would be:

```ts
type Ni = { [n: number]: boolean }
type Kni = keyof Ni // numeric-string
type Nikni = Ni[Kni] // boolean
```

lodash would no longer break because `T[keyof T]` would never end up indexing a numeric-index-only type with `never`, but with `numeric-string`. Then this PR could change so that never-indexing applies to all types, not just those with properties.

**Comment by ahejlsberg** [comment]
I'm actually okay with taking this PR since it moves us closer to where we eventually want to be, i.e. that `T[never]` is always `never` regardless of `T`. Longer term, if and when we fix `keyof { [x: number]: T }` to produce `numeric-string` (or whatever we call it) instead of `never`, we can then also change `{ [x: number]: T }[never]` to be `never`.

That said, we need a small change to the PR. I will review below.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8131,6 +8131,9 @@ namespace ts {
                     return anyType;
                 }
             }
+            if (indexType.flags & TypeFlags.Never) {
+                return neverType;
+            }
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Move these three lines up and insert then before line 8122. That way an `obj[key]` expression where `key` is an expression of type `never` will produce `never` (instead of the `any` it produces now).

**Comment by kpdonn** [comment]
@ahejlsberg Updated with the requested change and also a test for the `obj[key]` case where `key` is `never`.

Not sure why the CI builds failed though, I ran `gulp runtests` locally before committing and did not have failures.

**Comment by sandersn** [comment]
All right, it’s in! Thanks @kpdonn!
