### PR TITLE
No self or forward references in type parameter defaults

### LINKED ISSUE #28873: typesafe-joi blows up TypeScript 3.2+
**TypeScript Version:**  3.3.0-dev.20181205

**Search Terms:**

Maximum call stack size exceeded

**Code Repo:**

https://github.com/hjkcai/typesafe-joi

**Reproduction:**

```bash
mkdir typesafe-joi-issue && cd typesafe-joi-issue
yarn add typescript@next @types/node typesafe-joi joi
echo '{"compilerOptions":{"strict":true}}' > tsconfig.json
echo 'import * as Joi from "typesafe-joi"; console.log(Joi)' > index.ts
npx tsc -p .
```

**Expected behavior:**

tsc should work. 

I admit that typesafe-joi uses lots of type recursion, but it works fine in TypeScript 3.1. After upgrading to TypeScript 3.2, the error comes.

**Actual behavior:**

tsc itself encountered 'Maximum call stack size exceeded' (No stack trace printed)

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR makes it an error for type parameter defaults to reference anything but previously declared type parameters (i.e. type parameters declared to the left). This is analogous to JavaScript's restriction that parameter defaults can only reference parameters to the left, and it makes nonsensical constructs such as the following become errors:

```ts
type Foo<T = T> = T[];
type Bar<T = U, U = T> = [T, U];
```

This is technically a breaking change, but the only known real world case that is affected is #28388. The particular use in that example makes no sense (a type parameter referencing itself in its default) and we should instead fix the .d.ts file on Definitely Typed.

Fixes #28873. Supersedes #28971 and #29150.

### CODE REVIEW

**Comment by rbuckton** [comment]
Type parameter defaults didn't originally support forward references, which is called out specifically in #13487. I'm not certain at what point this restriction was broken.

**Comment by weswigham** [comment]
@rbuckton that comment indicates that they explicitly _are_ supported.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7928,22 +7928,17 @@ namespace ts {
...
-
-                // Map an unsatisfied type parameter with a default type.
-                // If a type parameter does not have a default type, or if the default type
-                // is a forward reference, the empty object type is used.
-                const baseDefaultType = getDefaultTypeArgumentType(isJavaScriptImplicitAny);
-                const circularityMapper = createTypeMapper(typeParameters!, map(typeParameters!, () => baseDefaultType));
+                // Map invalid forward references in default types to the error type
                 for (let i = numTypeArguments; i < numTypeParameters; i++) {
-                    result[i] = instantiateType(getConstraintFromTypeParameter(typeParameters![i]) || baseDefaultType, circularityMapper);
+                    result[i] = errorType;
```
Comment (rbuckton) [inline src/compiler/checker.ts]: This is effectively going back to the [behavior in the original PR](https://github.com/Microsoft/TypeScript/pull/13487/files#diff-c3ed224e4daa84352f7f1abcd23e8ccaR5327). It looks like the circularity was introduced in #28222 and #28423. Though, prior to this we were just defaulting to `{}` in TypeScript (`any` in JavaScript).

**Comment by rbuckton** [comment]
@weswigham: Except we defaulted to `{}` _explicitly_ to avoid this exact case where the _actual constraint_ results in a circular reference. Using `{}` was a silent error, similar to other cases where we silently use `{}` when inference fails.

**Comment by weswigham** [comment]
> Using {} was a silent error, similar to other cases where we silently use {} when inference fails.

Except we don't silently use `{}` when inference fails - we silently use the constraint, which is usually `{}`. My change brought defaults in line with that. Without doing that you'd have defaults which didn't satisfy their constraints!

**Comment by rbuckton** [comment]
@weswigham: Regardless, using a default of the error type (i.e. `any`) and reporting an error strengthens the original design and also solves the issue that the changes in #28222 were intended to solve.

**Comment by ahejlsberg** [comment]
@weswigham The key objective with this PR is to detect and disallow circular references in defaults. They're meaningless and confusing and we already detect and disallow circular constraints for the same reason. A secondary objective is to disallow references in defaults to type parameters for which type arguments are known to have been omitted, since those are just a complicated way of referencing other defaults.

The rule that allows references only to previously declared type parameters accomplishes both. None of the previously suggested solutions accomplish either. Instead we silently revert to `{}` or the type parameter constraint which really is never what the author intended (after all, if it was the intent, then why the extra indirection).

If we end up implementing named type arguments (and that's a big if given the fate of #23696) we can revise these rules accordingly, but as things stand now I think this PR is the right solution.

**Comment by InExtremaRes** [comment]
@ahejlsberg Is this going to disallow this type construction?

```ts
type Constrained<T extends { [P in keyof T]: string }> = T;
```

I have some code like that and it seems to be out there ([example](https://stackoverflow.com/a/52731753/2484624), [example](https://stackoverflow.com/a/53483282/2484624)).

**Comment by xiegeo** [comment]
Did this broke Vuex? https://github.com/championswimmer/vuex-module-decorators/issues/90
```
ERROR in .../node_modules/vuex-module-decorators/dist/types/vuexmodule.d.ts
2:46 Type parameter defaults can only reference previously declared type parameters.
    1 | import { ActionTree, GetterTree, Module as Mod, ModuleTree, MutationTree, Store, ActionContext } from 'vuex';
  > 2 | export declare class VuexModule<S = ThisType<S>, R = any> implements Mod<S, R> {
      |                                              ^
    3 |     static namespaced?: boolean;
    4 |     static state?: any | (() => any);
    5 |     static getters?: GetterTree<any, any>;
```

**Comment by mcastilho** [comment]
@xiegeo Yes. Happening to me now.
