### PR TITLE
List position based formatting

### LINKED ISSUE #5830: fluent api style method chain formatting problem
Seen in 1.8 nightly build (1.8.0-dev.20151130)

```
// given:
new Start()
   .then(
      true,
      false
   ).then(
      1234,
      'xyz'
   ).then(
      'abc',
      '987'
   );
```

```
// actual:
new Start()
   .then(
   true,
   false
   ).then(
   1234,
   'xyz'
   ).then(
   'abc',
   '987'
   );
```

```
// expected:
new Start()
   .then(
      true,
      false
   ).then(
      1234,
      'xyz'
   ).then(
      'abc',
      '987'
   );
```

### LINKED ISSUE #5890: angle brackets formatting problem
```
// given
export type All = Map<
    number, {
        type: zit.Type;
        index: number;
    }
>;
```

```
// actual
export type All = Map<
    number, {
        type: zit.Type;
        index: number;
    }
    >;
```

```
// expected
export type All = Map<
    number, {
        type: zit.Type;
        index: number;
    }
>;
```

### LINKED ISSUE #6252: formatting problem with an object literal as an inlined result type of a function
```
// given / expected
function _uniteVertices<p extends string, a>(
    minority: Pinned<p, Vertex<a>>,
    majorityCounter: number,
    majority: Pinned<p, Vertex<a>>
): {
    majorityCounter: number;
    vertecis: Pinned<p, {
        oldVertexId: VertexId;
        vertex: Vertex<a>;
    }>;
} {
}
```

```
// actual
function _uniteVertices<p extends string, a>(
    minority: Pinned<p, Vertex<a>>,
    majorityCounter: number,
    majority: Pinned<p, Vertex<a>>
): {
        majorityCounter: number;
        vertecis: Pinned<p, {
            oldVertexId: VertexId;
            vertex: Vertex<a>;
        }>;
    } {
}
```

### LINKED ISSUE #6320: unexpected chained "then" method indentation
In VS Code (as it uses the built in formatter, I assume this is the best place to put the issue), the TS formatting produces this:

```
foo()
  .then<void>(
  function(): void {
  },
  function(): void {
  }
  )
  .then<void>(
  function(): void {
  },
  function(): void {
  }
  );
```

I would expect this:

```
foo()
  .then<void>(
    function(): void {
    },
    function(): void {
    }
  )
  .then<void>(
    function(): void {
    },
    function(): void {
    }
  );
```

The former is pretty hard to read.

### LINKED ISSUE #6451: Indentation issues on multiline call expressions
``` typescript
Promise.resolve([
]).then(
    [
    /* indentation expected: 8, actual: 4 */
    ]
    )/* type ';' -> formatter indentation expected: 0, actual: 4  */
```

### LINKED ISSUE #10681: Formatting with method parameters
Should increase the indent level with parameters.

**TypeScript Version:**  2.0-rc

**Expected behavior:**

``` ts
[]
  .reduce(
    b => b,
    0);
```

**Actual behavior:** 

``` ts
[]
  .reduce(
  b => b,
  0);
```

### LINKED ISSUE #26906: Revive PR #13574
Work item to track getting #13574 merged up with master and suitable for checking in

### PR DESCRIPTION
**Pull request by saschanaz**
Revives #13574

Fixes #5830, fixes #5890, fixes #6252, fixes #6320, fixes #6451, fixes #10681, fixes #26906

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ namespace ts.formatting {
      * the first token in line so it should be indented
      */
     interface DynamicIndentation {
-        getIndentationForToken(tokenLine: number, tokenKind: SyntaxKind, container: Node): number;
+        getIndentationForToken(tokenLine: number, tokenKind: SyntaxKind, container: Node, suppressDelta?: boolean): number;
```
Comment (andy-ms) [inline src/services/formatting/formatting.ts]: Since this is internal there's no need to be backwards-compatible. So this should just be `suppressDelta: boolean`.

File: src/services/formatting/formatting.ts [hunk 2]
```diff
@@ -726,6 +735,7 @@ namespace ts.formatting {
 
                 let listDynamicIndentation = parentDynamicIndentation;
                 let startLine = parentStartLine;
+                let indentationOnListStartToken = parentDynamicIndentation.getIndentation();
```
Comment (andy-ms) [inline src/services/formatting/formatting.ts]: It looks like the value written here is never used. It's overwritten in both `if` and `else` branches before its sole use.

File: src/services/formatting/smartIndenter.ts [hunk 3]
```diff
@@ -323,112 +322,109 @@ namespace ts.formatting {
             return false;
         }
 
+        function getListIfVisualStartEndIsInListRange(list: NodeArray<Node> | undefined, start: number, end: number, node: Node) {
```
[the remark this answers is not in the document]
Comment (saschanaz) [reply src/services/formatting/smartIndenter.ts]: NodeArray starts at the previous token's end positions and ends at the last list item's end position. So think about the following code:

```ts
func(
  // visually the list starts at line 0 and ends in line 2, but actually it ends at line 0
);

func(
  1,
  // visually the list starts at line 0 and ends in line 3, but actually it ends at line 1
  // which means the position of these comments does not belong to the list range.
);
```

File: src/services/formatting/smartIndenter.ts [hunk 4]
```diff
@@ -343,28 +343,28 @@ namespace ts.formatting {
...
-            return getListByRange(pos, pos, node);
+            return getListByRange(pos, pos, node, sourceFile);
         }
 
-        function getListByRange(start: number, end: number, node: Node): NodeArray<Node> | undefined {
+        function getListByRange(start: number, end: number, node: Node, sourceFile: SourceFile): NodeArray<Node> | undefined {
             switch (node.kind) {
                 case SyntaxKind.TypeReference:
-                    return getListIfVisualStartEndIsInListRange((<TypeReferenceNode>node).typeArguments, start, end, node);
+                    return getListIfVisualStartEndIsInListRange((<TypeReferenceNode>node).typeArguments, start, end, node, sourceFile);
```
Comment (andy-ms) [inline src/services/formatting/smartIndenter.ts]: You could create a closure so you don't have to repeat the arguments `start, end, node, sourceFile` everywhere.

**Comment by DanielRosenwasser** [comment]
I'm pulling this in, and if we'd like to address any changes related to code cleanliness or perf we can do this after. Thank you so much for sticking it out and sending out these changes again.

**Comment by DanielRosenwasser** [comment]
⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ❤️
