### PR TITLE
Fix spurious circularity caused by removeOptionalityFromDeclaredType, cache result

### LINKED ISSUE #50795: Unexpected circularly references error in VSCode
# Bug Report

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.3

### ⏯ Playground Link

cannot reproduce in playground

### 💻 Code

```ts
function fn(Foo: number) {
    type Foo = typeof Foo;

    return 0 as any as {x: Foo};
}
```

### 🙁 Actual behavior

In vscode with TS version > 4.6.4 it reports `'Foo' is referenced directly or indirectly in its own type annotation.ts(2502)`. But it works well in the playground. 

This is first reported by @TechQuery in https://github.com/microsoft/TypeScript/issues/50792#issuecomment-1248587467, and I realize it may be related to https://github.com/microsoft/TypeScript/issues/50161 and https://github.com/microsoft/TypeScript/issues/50191 since the behavior is quite similar.

### 🙂 Expected behavior

No error.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #50795

The way the `pushTypeResolution` system works is that each `TypeSystemPropertyName` maps to a currently-being-computed property on a `NodeLinks`, `SymbolLinks`, `Type`, etc, with the expectation that the value is set once the resolution stack is popped. If you try to push the same `TypeSystemPropertyName` onto the stack for the same thing, you get a circularity error because the thing isn't ready yet.

#37023 added a `pushTypeResolution` to detect a circularity, but then used `TypeSystemPropertyName.DeclaredType` even though `removeOptionalityFromDeclaredType` never actually sets `declaredType`. This led to spurious circularity errors depending on the order in which we ask for the types. In this bug's case, if we ask for semantic tokens first, we end up hitting what the old code thought was a cycle but is in fact not.

This PR fixes the issue while still emitting the right circularity error added in #37023 by creating a new property on `NodeLinks` which caches the computation that determines whether or not a parameter's initializer contains `undefined`. Then, we can add a `TypeSystemPropertyName` that is associated with that value, which then lets us detect cycles specifically in this part of the code, without reusing an unrelated `TypeSystemPropertyName`.

It also has the benefit of being faster because this computation is now cached rather than being reevaluated each time, and I've also switched it to use `checkDeclarationInitializer` which is the "correct" way to grab the declaration's initializer type (uses `checkExpressionCached`, uses JSDoc when needed, and so on).

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -27294,20 +27297,29 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                return declaredType;
+            }
+
             const annotationIncludesUndefined = strictNullChecks &&
                 declaration.kind === SyntaxKind.Parameter &&
                 declaration.initializer &&
                 getTypeFacts(declaredType) & TypeFacts.IsUndefined &&
-                !(getTypeFacts(checkExpression(declaration.initializer)) & TypeFacts.IsUndefined);
-            popTypeResolution();
+                !(getTypeFacts(checkDeclarationInitializer(declaration, CheckMode.Normal)) & TypeFacts.IsUndefined);
```
Comment (jakebailey) [inline src/compiler/checker.ts:27312]: Alternatively, I could avoid setting this on most nodes (only applies to parameters) and skip this circularity, but that felt dangerous.

Comment (jakebailey) [reply src/compiler/checker.ts:27312]: Nah, this function simply won't be called on anything but params already, so id optimized enough .

**Comment by jakebailey** [comment]
Fixed my oops. I was misled by the variable name used by the old function; it's not related to the annotation entirely anymore.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Review by sandersn — APPROVED** [review]
