### PR TITLE
Discriminate jsx contextual types same as object contextual types

### LINKED ISSUE #26004: React .tsx with Union Type Props reports error. But works in pure TS
**TypeScript Version:**  2.9.2
(also tried typescript@3.1.0-dev.20180727 )

**Search Terms:** React Tsx Union Generics

**Code**

```ts
interface PS {
    multi: false
    value: string | undefined
    onChange: (selection: string | undefined) => void
}

interface PM {
    multi: true
    value: string[]
    onChange: (selection: string[]) => void
}

export function ComponentWithUnion(props: PM | PS) {
    return "foo";
}

// Usage with React tsx
export function HereIsTheError() {
    return (
        <ComponentWithUnion
            multi={false}
            value={'s'}
            onChange={val => console.log(val)} // <- this throws an error
        />
    );
}

// Usage with pure TypeScript
ComponentWithUnion({
    multi: false,
    value: 's',
    onChange: val => console.log(val) // <- this works fine
})
```

**Expected behavior:**
Both should infer the correct type and don't throw an error.

**Actual behavior:**
Throw's the following error:
```
Parameter 'val' implicitly has an 'any' type
```

**Playground Link:** 
https://codesandbox.io/s/w07omnr85k
In file index.ts at line 25 you can see that `val` is of type `any`. But in line 34 it correctly displays type `string`.

**Related Issues:** 
None

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #26004

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Might fix #27211 as well?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16786,6 +16779,57 @@ namespace ts {
             return match || contextualType;
         }
 
+        function discriminateContextualTypeByJSXAttributes(node: JsxAttributes, contextualType: UnionType) {
+            let match: Type | undefined;
+            propLoop: for (const prop of node.properties) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: oh no

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16786,6 +16779,57 @@ namespace ts {
...
+                }
+                else if (isJsxAttributes(node)) {
+                    return discriminateContextualTypeByJSXAttributes(node, contextualType as UnionType);
+                }
+            }
+            return contextualType;
+        }
+
         /**
          * Woah! Do you really want to use this function?
```
Comment (sandersn) [inline src/compiler/checker.ts]: Pretty sure it's spelled "Whoa" *@DanielRosenwasser*

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -16755,22 +16755,15 @@ namespace ts {
...
-        // Return the contextual type for a given expression node. During overload resolution, a contextual type may temporarily
-        // be "pushed" onto a node using the contextualType property.
-        function getApparentTypeOfContextualType(node: Expression): Type | undefined {
-            let contextualType = getContextualType(node);
-            contextualType = contextualType && mapType(contextualType, getApparentType);
-            if (!(contextualType && contextualType.flags & TypeFlags.Union && isObjectLiteralExpression(node))) {
-                return contextualType;
-            }
+        function discriminateContextualTypeByObjectMembers(node: ObjectLiteralExpression, contextualType: UnionType) {
             // Keep the below up-to-date with the work done within `isRelatedTo` by `findMatchingDiscriminantType`
```
Comment (sandersn) [inline src/compiler/checker.ts]: Since this applies to two functions now, enumerate the functions.

Actually, if you can extract the core of this algorithm and call it, that would be better. I'm not sure what you can do with that *hilarious* use of `break propLoop` in there. Maybe that could become a `return`?

**Comment by sandersn** [comment]
Looks like there is some assertion lint.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -16771,37 +16780,69 @@ namespace ts {
...
+                }
+                else {
+                    const simpleInitializer = isStringLiteral(prop.initializer) ? prop.initializer : prop.initializer.expression;
+                    possiblyDiscriminant = !!(simpleInitializer && isPossiblyDiscriminantValue(simpleInitializer) && isDiscriminantProperty(contextualType, prop.symbol.escapedName));
+                    if (possiblyDiscriminant) {
+                        discriminatingType = checkExpression(simpleInitializer!);
+                    }
+                }
+                if (possiblyDiscriminant) {
+                    const result = getDiscriminationResultForProperty(contextualType, discriminatingType!, prop.symbol.escapedName, match, isTypeAssignableTo);
```
Comment (sandersn) [inline src/compiler/checker.ts]: You could get rid of the nullable assertion if you dropped `possiblyDiscriminant` and checked `discriminatingType` above. The no-initialiser case would need to change to `discriminatingType = !!isDiscr... && trueType`.

Not sure if it's worth the change. Probably?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -12476,6 +12471,20 @@ namespace ts {
             }
         }
 
+        function getDiscriminationResultForProperty(target: UnionType, discriminatingType: Type, propertyName: __String, match: Type | undefined, related: (source: Type, target: Type) => boolean | Ternary) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: Please break this line. And it might be nice to give the return type since it has the ooband value "mismatch".

**Comment by weswigham** [comment]
@sandersn I did better; you probably wanna look again (again), since AFAIK none of your last set of comments apply anymore.
