### PR TITLE
someTypeRelatedToType now passes isIntersectionConstituent

### LINKED ISSUE #33133: 3.6 regression: `Error: Debug Failure. No error for last overload signature`
**TypeScript Version:**  3.6.2

**Search Terms:** debug failure overload signature

After upgrading our large app from TS 3.5.2 to to TS 3.6.2, we get the following error when running `tsc`:

```sh-session
$ tsc  --project tsconfig.json
/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:75634
                throw e;
                ^

Error: Debug Failure. No error for last overload signature
    at resolveCall (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:43576:38)
    at resolveJsxOpeningLikeElement (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:44148:20)
    at resolveSignature (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:44169:28)
    at getResolvedSignature (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:44180:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:42398:27)
    at checkJsxSelfClosingElementDeferred (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:42042:13)
    at checkDeferredNode (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:50211:21)
    at Map.forEach (<anonymous>)
    at checkDeferredNodes (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:50189:37)
    at checkSourceFileWorker (/Users/oliverash/Development/unsplash-web/node_modules/typescript/lib/tsc.js:50249:17)
```

### PR DESCRIPTION
**Pull request by sandersn**
The quick check for intersection sources doesn't pass isIntersectionConstituent, which incorrectly causes excess property checking to happen on intersection constituents.

In this example, the quick check happens when checking `g(CC)`, and incorrectly finds that `CP` is not assignable to `{ children?: boolean }` even though the latter is part of `CP & { children?: boolean }`. The result is the cached, which breaks the assignability check on the next line: `<CC {...(null as CP) }/>`.

This is a 3.6 regression, but the example is so complex that I'm not sure how hard it is to reproduce.

```ts
interface F<P> {
    (props: P & { children?: boolean }): void;
    propTypes: { [K in keyof P]: null extends P ? K : K };
}
declare function g(C: F<unknown>): string;
export function wu<CP extends { o: object }>(CC: F<CP>) {
    class WU {
        m() {
            g(CC)
            return <CC {...(null as unknown as CP)} />;
        }
    }
}
```

Fixes #33133

Edit: Added commentary from the issue:

The basic problem is that the flag `isIntersectionConstituent`, which is used to exempt intersection constituents from common-property checks ("weak types"), isn't threaded through one particular intersection call in assignability checking. I missed it when threading that flag through more calls in 3.6 (https://github.com/microsoft/TypeScript/pull/32582), and my new assertion in overload error reporting caught the mistake. It's quite likely that this assert would have fired a lot more before #32582.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22018,7 +22018,7 @@ namespace ts {
                         }
                     }
                     else {
-                        const allDiagnostics: DiagnosticRelatedInformation[][] = [];
+                        const allDiagnostics: Array<ReadonlyArray<DiagnosticRelatedInformation>> = [];
```
Comment (weswigham) [inline src/compiler/checker.ts]:
```suggestion
                        const allDiagnostics: (readonly DiagnosticRelatedInformation[])[] = [];
```
to fix that lint failure.

Comment (sandersn) [reply src/compiler/checker.ts]: Our parsing for `readonly T[][]` is so bad, and yet we have a lint rule requiring.

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this to release-3.6
