### PR TITLE
Visit EOF to collect jsdoc import types

### LINKED ISSUE #23508: JSDoc: can't resolve import(...) if it's defined at the bottom of a file
**TypeScript Version:** 2.9.0-dev.20180418

**Search Terms:**
 - JSDoc
 - import
 - types

**Code**

```ts
// @filename: interfaces.d.ts
export interface Bar {
    prop: string
}

// @filename: usage.js
/** @type {Bar} */
export let bar;

// TS raises following error:
// TS2307: Cannot find module './interfaces'
/** @typedef {import('./interfaces').Bar} Bar */
```

**Expected behavior:**
TS successfully resolves requested module. No errors should be thrown.

**Actual behavior:**
TS can't find a requested module if `import` is used at the bottom of a file.

### PR DESCRIPTION
**Pull request by weswigham**
Trailing jsdoc comments are attached to the EOF token, which we had not been visiting when collecting module resolutions.

Fixes #23508

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -1624,6 +1624,9 @@ namespace ts {
                     collectDynamicImportOrRequireCalls(node);
                 }
             }
+            if ((file.flags & NodeFlags.PossiblyContainsDynamicImport) || isJavaScriptFile) {
```
Comment (mhegazy) [inline src/compiler/program.ts]: should be `&&` instead of `||`. in a .ts file this is going to be a node, and not a comment.

Comment (weswigham) [reply src/compiler/program.ts]: It's always a node. it just may have `.jsDoc` nodes attached.

Comment (weswigham) [reply src/compiler/program.ts]: @mhegazy You say that, and I've said that, but that's not true. We parse and bind `jsdoc` in TS files for the LS - we just don't consider them as part of the types of any associated nodes. Seriously - `addJSDocComment` in `parser.ts` is unconditional.

**Comment by weswigham** [comment]
@mhegazy I've added a condition in `processImportedModules` to prevent import types in jsdoc from affecting the set of files included in the compilation (but it still gets resolved). Does that allay your concerns (we already did this for a few other things, like js files outside allowJs and node modules beyond max module depth)?
