### PR TITLE
fix(60484): Implementing a prim type in a class expression should report error

### LINKED ISSUE #60484: Implementing a prim type in a class expression should report error
### 🔎 Search Terms

class expression implement primitive type

### 🕗 Version & Regression Information

- This changed between versions __5.2.2____ and __5.3.3_____

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.3.3#code/MYewdgzgLgBAgjAvDYAbAhhCMBCMCWAtgA6oCmhZYU2YAroQEZkBOMA3gL4BQ3am2AMIES5StVoNmbLkA

### 💻 Code

```ts
class C implements number {} // report that class cannot implement primitive type

const A = class B implements number {} // this code should report the same error, but it actually does not.
```

### 🙁 Actual behavior

Refer to the comment above

### 🙂 Expected behavior

Refer to the comment above

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #60484

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3458,10 +3458,10 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                     if (containerKind === SyntaxKind.InterfaceDeclaration && heritageKind === SyntaxKind.ExtendsKeyword) {
                         error(errorLocation, Diagnostics.An_interface_cannot_extend_a_primitive_type_like_0_It_can_only_extend_other_named_object_types, unescapeLeadingUnderscores(name));
                     }
-                    else if (containerKind === SyntaxKind.ClassDeclaration && heritageKind === SyntaxKind.ExtendsKeyword) {
+                    else if (isClassLike(grandparent.parent) && heritageKind === SyntaxKind.ExtendsKeyword) {
```
Comment (Andarist) [inline src/compiler/checker.ts:3461]: If I'm not mistaken this change wasn't covered by the new tests, there are no new `extends`-based tests - just ones using `implements`

Comment (a-tarasyuk) [reply src/compiler/checker.ts:3461]: thanks for pointing that out. I've added more tests.

**Review by jakebailey — APPROVED** [review]
