### PR TITLE
Expand auto-import to all package.json dependencies

### LINKED ISSUE #36042: Automatic imports don't work for packages that provide their own types
- VSCode Version: 1.41.0
- OS Version: Fedora 30

Steps to Reproduce:

1. Add a module dependency which includes it's own types
2. Start writing out a named export of the added module
3. No suggestion will be given 

Suggestions won't show until you've actually imported the dependency.
This is different from how `@types` modules work, which will show in suggestions without any prior use.

I've created an [example project](https://github.com/robbiespeed/suggestion-test)

1. `yarn install`
2. open `src/main.ts`
3. type `use` and you will get suggestions for React `useCallback`, etc.
4. type `watch` and you will get no suggestion for Kappi `watch`

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #37812: Expand auto-import to all dependencies in package.json
# Background

TypeScript's auto-import functionality has some really unpredictable behavior today where the feature doesn't work on for a package until a user manually imports from that package. This experience only affects projects that provide their own types because, by default, TypeScript always includes `@types` packages as part of every compilation; however, it doesn't include other packages in `node_modules`<sup>[1]</sup>. Apart from being unfair to TypeScript library authors, this is just plain surprising for users.

For a while now, we've received consistent feedback that this is a confusing experience.

* https://github.com/microsoft/TypeScript/issues/37222
* https://github.com/microsoft/TypeScript/issues/28773#issuecomment-444780234
* https://github.com/microsoft/TypeScript/issues/30033
* https://github.com/microsoft/TypeScript/issues/29629
* https://github.com/microsoft/TypeScript/issues/28773
* https://github.com/microsoft/TypeScript/issues/38176
* https://twitter.com/alephnaught2tog/status/1245026801564467203

[Additionally, we've been seeing weird hacks in projects like Angular CLI](https://github.com/microsoft/TypeScript/issues/37187#issuecomment-594237946), where `typeRoots` are set to `node_modules` and `node_modules/@types` to try to fix auto-imports.

# Proposal

In https://github.com/microsoft/TypeScript/pull/31893 and https://github.com/microsoft/TypeScript/pull/32517, we improved some rough areas of completions by making sure that we *only* provided completions from packages that are listed in `package.json`. That way `clearTimeout` doesn't appear in your completion list unless you specifically list `@types/node` as a dependency.

What I'd like to suggest is an *expansion* of completions sources to those in `package.json`. Specifically what I'm looking for is that for every dependency in `package.json`, we should try to provide auto-imports. This could be done by changing the default behavior for `typeRoots` (potentially breaking) or by adding an editor-specific behavior for  automatic package inclusion.

There's things to keep in mind as we do this:

* we don't want to accidentally load up 100s of `.d.ts` files unnecessarily
* we don't want to have duplicate entries when a package ships its own `.d.ts` files but a user has `@types` packages installed
* we don't want to add new logic that affects module resolution and changes the behavior of go-to-definition
* we don't want to drastically diverge in behavior from the command-line

Maybe for the general case, this won't cause a drastic increase in memory usage - most packages with explicit dependencies might get installed/eventually used anyway. But if it is, there might be some workarounds to consider:

* only go through 2-3 levels of imports for these expanded completions
    * this might not work well for "barrels" (i.e. files with a lot of `export * from` statements), but it might just be good enough.
* only expand auto-completions to `dependencies` and not `devDependencies`
    * this would be really confusing for utilities and test code, but not application code.

I'd like to get people's thoughts on whether an approach like this would even be possible, and if so, whether we could implement it without degrading the current experience.

______

<sup>[1]</sup> The reason for this is the asumption that having an `@types` package in your `node_modules` directory is a pretty good sign that you intend to use it (with caveats - see https://github.com/microsoft/TypeScript/pull/31893 and https://github.com/microsoft/TypeScript/issues/32273). But in order to save on time/memory, we don't load up `.d.ts` files from other `node_modules` packages unless we really need to.

### PR DESCRIPTION
**Pull request by andrewbranch**
This PR creates an auxiliary program in the language service layer that contains node_modules packages that are specified as a direct dependency (including ~~devDependencies~~ peerDependencies) in a package.json file visible to the project’s root directory and not already present in the main program. This program is then supplied to the auto-imports machinery as a provider of additional modules that can be used for auto-import. Effectively, this means that packages that ship their own types should be available for auto-import immediately after `npm install`ing them, lifting a long-despised limitation of “you have to write out the import manually once in your project before auto-imports will work, unless it’s in `@types`, because `@types` is special.”

## Performance

I compared a few operations against master on the output of @angular/cli (with routing). (I chose this as a test because it’s a realistic scenario where a user’s package.json will contain more dependencies with self-shipped types than are actually used in the program. For example, `@angular/forms` is a listed dependency but isn’t used in the boilerplate.) Measurements are an average of three trials run in VS Code 1.46.0-insider (b1ef2bf) with extensions disabled.

|                                | master | PR      | Diff                  |
|-------------------|--------|-------|---------------|
| Startup time (ms) | 2729    | 2636  | -92 ms (-3%) |
|                                                                                      |
| __Type “P”*__                                                               |
| updateGraph        | 18         | 15        | -4 ms (-20%) |
| completionInfo     | 102       | 115      | +13 ms (+13%) |
|                                                                                      |
| __Backspace, Type “P”**__                                         |
| completionInfo     | 44        | 38        | -6 ms (-13%) |
|                                                                                      |
| __Comment out import***__                                        |
| getApplicableRefactors | 44 | 62   | +18 ms (+42%) |

<sup>* This triggers completions, including import suggestions for `PatternValidator` from `@angular/forms` in the PR trials, a suggestion that is not included in the master trials.</sup>

<sup>** This triggers completions again without disrupting the auto-import cache populated in the previous action.</sup>

<sup>*** This changes the structure of the primary program, which triggers an update of the auto-import provider program. The time it takes to do so is included in the subsequent `getApplicableRefactors` measurement.</sup>

Observations:

- Editing operations that don’t change the structure of the program are unaffected (looking at `updateGraph` time)
- When generating completions, there’s an added cost associated with looking through more modules and generating auto-import suggestions for them. The penalty isn’t huge, though, and seems to be worth it for the added utility.
- When something happens that triggers an update of the auto-import provider, there’s an associated cost that scales with the number of typed dependencies in package.json files that are not already in the main program (i.e., the size of the auto-import provider program). Because the Angular CLI generates boilerplate that has more unused typed dependencies than most real codebases (normally when you install a dependency, you import it shortly thereafter), I suspect that it will be rare for users to see much more delay than the 18 ms measured here.

## Limitations

- Only package.jsons found in the project’s `currentDirectory` and upward are considered. So in an unusual project structure like

   ```
   tsconfig.json
   project/
     node_modules/
     package.json
     index.ts
   ```

  the `project/package.json` file won’t be found.

- This doesn’t currently resolve to JavaScript files—that is, to get auto imports, the package has to have `.d.ts` files. Processing plain JS for auto-imports could be explored if demand were high, but when I tried it, most of the added packages were CLI tools and plugins, not things people want to import from, so it was a performance hit for little (or even negative) utility.

## Memory considerations

The auxiliary program is configured to be as light as possible, but in a project references editing scenario, it’s possible to have many projects open at once. Each project has its own language service, so each open project will typically have one of these auxiliary programs. Some possibilities for mitigating high memory usage in these scenarios: _(**updated**: decided to [exclude devDependencies](https://github.com/microsoft/TypeScript/pull/38923#issuecomment-639659024) for UX reasons)_

- The auxiliary program won’t be created if there are no packages listed that aren’t already in the main program, ~~but an analysis of around 500 popular open source TypeScript repos shows that this rarely happens, largely due to devDependencies that ship their own types but are never used in the program (prominent example: typescript). Excluding devDependencies significantly increases the chances that creation an auxiliary program can be skipped, at the cost of those devDependencies being unavailable for auto-import (which can be useful when writing build scripts and tests).~~
- The auxiliary program isn’t created until there’s an open file that belongs&sup1; to the project. This prevents us from creating these programs as we do a cross-project find-all-references.
- If we detect that memory usage is a problem, we could dispose or stop creating these programs. I think @sheetalkamat has looked into this in the past.
- ~~We could either hard-code into TypeScript or indicate in third-party projects that a package should opt out of being eagerly auto-importable. In one real-world project I tested, the contents of the auxiliary programs were limited to typescript, typescript-eslint, ts-jest, jest, and prettier, none of which are commonly imported.~~

However, at this point I’m not convinced that any of these mitigations are necessary. The size of these programs is usually in the ballpark of a browser tab (around 50 MB from one early test). But we have avenues to explore if needed.

Fixes #37812 
Fixes #36042

---

&sup1; “file that belongs to the project” here means “file whose default project is the project in question,” in contrast to “file that is contained by the project”

### CODE REVIEW

File: src/server/editorServices.ts [hunk 1]
```diff
@@ -3671,6 +3689,83 @@ namespace ts.server {
...
+        /*@internal*/
+        private updateAutoImportProvidersWithPackageJson(packageJsonPath: Path) {
+            if (this.usePackageJsonAutoImportProvider) {
+                this.configuredProjects.forEach(project => {
+                    if (project.packageJsonsForAutoImport?.has(packageJsonPath)) {
+                        project.markAutoImportProviderAsDirty();
+                    }
+                });
+            }
+        }
```
Comment (andrewbranch) [inline src/server/editorServices.ts:3768]: This bit is the only new code in this chunk of added lines. It ensures every project that encountered a given package.json file while constructing its auto-import provider program gets updated when that package.json file is edited.

File: src/server/scriptInfo.ts [hunk 2]
```diff
@@ -294,6 +294,11 @@ namespace ts.server {
          * All projects that include this file
          */
         readonly containingProjects: Project[] = [];
+        /**
+         * @internal
+         * Projects whose auto-import providers include this file
+         */
+        private auxiliaryFileContainingProjects: Project[] | undefined;
```
Comment (andrewbranch) [inline src/server/scriptInfo.ts:301]: ScriptInfo needs to track what projects’ auto-import provider programs contain it so they can be updated when edited manually. We can’t track this in `containingProjects`, because it would mess up the calculation of a script’s “default project.” (When a file is in the auto-import program but not the main program, and you open that file in your editor for some reason, it should be part of an InferredProject, not the ConfiguredProject that might eventually auto-import it.) Thanks @sheetalkamat for advising me to look into this scenario.

File: src/services/codefixes/importFixes.ts [hunk 3]
```diff
@@ -786,18 +790,34 @@ namespace ts.codefix {
...
         filterByPackageJson: boolean,
-        cb: (module: Symbol) => void,
+        cb: (module: Symbol, moduleFile: SourceFile | undefined, program: Program) => void,
+    ) {
+        forEachExternalModuleToImportFromInProgram(program, host, from, filterByPackageJson, (module, file) => cb(module, file, program));
+        if (autoImportProvider) {
+            const start = timestamp();
+            forEachExternalModuleToImportFromInProgram(autoImportProvider, host, from, filterByPackageJson, (module, file) => cb(module, file, autoImportProvider));
+            host.log?.(`forEachExternalModuleToImportFrom autoImportProvider: ${timestamp() - start}`);
+        }
```
Comment (andrewbranch) [inline src/services/codefixes/importFixes.ts:804]: There were surprisingly few changes necessary to the auto-import logic itself 🤷‍♂️

File: src/services/services.ts [hunk 4]
```diff
@@ -992,9 +994,13 @@ namespace ts {
...
         }
 
-        public getOrCreateEntryByPath(fileName: string, path: Path): HostFileInformation {
-            const info = this.getEntryByPath(path) || this.createEntry(fileName, path);
-            return isString(info) ? undefined! : info; // TODO: GH#18217
+        public getOrCreateEntryByPath(fileName: string, path: Path, isAuxiliaryFile: boolean): HostFileInformation {
+            let info = this.getEntryByPath(path) || this.createEntry(fileName, path, isAuxiliaryFile);
+            if (isString(info)) return undefined!; // TODO: GH#18217
+            if (isAuxiliaryFile !== info.isAuxiliaryFile) {
+                info = this.createEntry(fileName, path, isAuxiliaryFile);
```
Comment (andrewbranch) [inline src/services/services.ts:1001]: I think I need to revisit this after some recent changes. Ignore this `isAuxiliaryFile` in HostCache for now.

File: src/services/services.ts [hunk 5]
```diff
@@ -1306,39 +1376,8 @@ namespace ts {
             if (host.useSourceOfProjectReferenceRedirect) {
                 compilerHost.useSourceOfProjectReferenceRedirect = () => host.useSourceOfProjectReferenceRedirect!();
             }
-            host.setCompilerHost?.(compilerHost);
```
Comment (andrewbranch) [inline src/services/services.ts:1309]: A lot of fairly uninteresting refactors through this section that creates a big diff. The compiler host creation was moved into a function so it can be used both for the main program and for the auto import provider. Small tweaks within some of the host functions were necessary to ensure, e.g., that we don’t release source files from one program that are still being used by the other, and that ScriptInfo creation knows whether it’s being created as a real part of the project or just as an auto-importable file.

File: src/services/services.ts [hunk 6]
```diff
@@ -1416,6 +1449,91 @@ namespace ts {
...
+        }
+
+        function onReleaseOldSourceFileFromAutoImportProvider(oldSourceFile: SourceFile, oldOptions: CompilerOptions) {
+            if (!program.getSourceFileByPath(oldSourceFile.path)) {
+                const oldSettingsKey = documentRegistry.getKeyForCompilationSettings(oldOptions);
+                documentRegistry.releaseDocumentWithKey(oldSourceFile.resolvedPath, oldSettingsKey);
+            }
+        }
+
+        function createPackageJsonAutoImportProvider(compilerHost: CompilerHost, compilerOptions: CompilerOptions): Program | undefined {
```
Comment (andrewbranch) [inline src/services/services.ts:1476]: This function is where the actual auto-import program gets created.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
After further thought, I do think devDependencies should be excluded by default (we could add a configuration option to include them if enough people really want them). Including them by default means that virtually every project written in TypeScript would get auto-imports for the compiler, which nobody wants. If you _do_ want to import the compiler API, `typescript` is either going to be in your `"dependencies"` or `"peerDependencies"`—and we _should_ include peer dependencies by default.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by amcasey** [comment]
For anyone else buddy testing this, here's a list of packages that include their own types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/notNeededPackages.json

File: src/services/codefixes/fixAddMissingMember.ts [hunk 7]
```diff
@@ -315,7 +315,7 @@ namespace ts.codefix {
         sourceFile: SourceFile,
         isJSFile: boolean
     ): void {
-        const importAdder = createImportAdder(sourceFile, context.program, context.preferences, context.host);
+        const importAdder = createImportAdder(sourceFile, context.program, context.autoImportProvider, context.preferences, context.host);
```
Comment (amcasey) [inline src/services/codefixes/fixAddMissingMember.ts:318]: I don't think this can actually require auto-imports.  Probably the same is true for some of the other code fixes.

**Comment by andrewbranch** [comment]
The default is `exclude-dev`, since `all` will contain a lot of noise for most users (e.g., anyone who has `typescript` as a `devDependency` would get auto-imports from the compiler). In fact, I’m not even sure that `all` needs to be exposed in VS Code’s UI, but it was trivial to add on our side.

File: src/server/protocol.ts [hunk 8]
```diff
@@ -2158,6 +2162,11 @@ namespace ts.server.protocol {
          * and therefore may not be accurate.
          */
         isFromUncheckedFile?: true;
+        /**
+         * If true, this completion was for an auto-import of a module not yet in the program, but listed
+         * in the project package.json.
+         */
+        isPackageJsonImport?: true;
```
Comment (andrewbranch) [inline src/server/protocol.ts:2169]: This is sent so editors can report telemetry on how often this feature is actually useful. @uniqueiniquity, I heard you set something very similar up for IntelliCode completions? Does this seem like a reasonable approach, and would you be able to help me out with making the changes I need to make on the editor side?

File: src/server/session.ts [hunk 9]
```diff
@@ -606,7 +606,7 @@ namespace ts.server {
         protected projectService: ProjectService;
         private changeSeq = 0;
 
-        private updateGraphDurationMs: number | undefined;
+        private performanceData: protocol.PerformanceData | undefined;
```
Comment (andrewbranch) [inline src/server/session.ts:609]: @amcasey, you might be interested in the minor changes to perf reporting I made in this file after our conversation

Comment (amcasey) [reply src/server/session.ts:609]: LGTM.  You'll want to create bugs against the editors to start reporting corresponding telemetry.

File: src/services/services.ts (hunk 5 above)
Comment (sheetalkamat) [reply src/services/services.ts:1310]: I think instead of just moving compilerHost into the new function you should move program creation and  setting hostCache to undefined to avoid using it later on and getting typechecker to ensure that files are bound and have correct parent pointers..  here as well.. So that its one unit that does everything right for getting you program

File: src/server/project.ts [hunk 10]
```diff
@@ -364,7 +369,7 @@ namespace ts.server {
             return addRange(result, this.typingFiles) || ts.emptyArray;
         }
 
-        private getOrCreateScriptInfoAndAttachToProject(fileName: string) {
+        private getOrCreateScriptInfoAndAttachToProject(fileName: string, isAuxiliaryFile?: boolean) {
```
Comment (sheetalkamat) [inline src/server/project.ts:372]: Did you think about creating auxillary project and calling methods on that project (new project kind that probably derives from inferred project)  and handling that.. THat might be simple than having to track two types of contianingProjects etc.. Also better to investigate where what is attached.

File: src/services/services.ts [hunk 11]
```diff
@@ -1223,6 +1231,31 @@ namespace ts {
             return sourceFile;
         }
 
+        function synchronizeAutoImportProvider(hostCache?: HostCache) {
+            Debug.assert(!syntaxOnly);
+
+            const dependencySelection = host.includePackageJsonAutoImports?.();
```
Comment (sheetalkamat) [inline src/services/services.ts:1237]: Another thought is that given that project is sufficient to handle the creation of program, you want something like host.getAutoImportProviderHost which is subset of LanguageServiceHost to create a program.. You can then use that to create the program so you are ensuring not using same host. I have not thought about this enough but it seems like you want to get AuxillaryProject here as a host and createProgram instead.. THat way someone is not subscribing to breaking behaviour with getScriptSnapshot and similar)

File: src/server/protocol.ts (hunk 8 above)
Comment (uniqueiniquity) [reply src/server/protocol.ts:2169]: yep, let's plan to discuss. happy to help with consuming this in both vs and vscode.

Comment (DanielRosenwasser) [reply src/server/protocol.ts:2169]: Maybe `packageJsonImportSource: "dependencies" | "devDependencies" | undefined`

File: src/server/editorServices.ts [hunk 12]
```diff
@@ -1186,7 +1194,7 @@ namespace ts.server {
                         (fsResult && fsResult.fileExists || !fsResult && this.host.fileExists(fileOrDirectoryPath))
                     ) {
                         this.logger.info(`Project: ${configFilename} Detected new package.json: ${fileOrDirectory}`);
-                        project.onAddPackageJson(fileOrDirectoryPath);
+                        this.onAddPackageJson(fileOrDirectoryPath, watchOptions);
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/editorServices.ts:1197]: Hmm, I didn’t realize that. This code is almost a year old, though. I might want to rethink this in a subsequent PR.

File: src/services/services.ts [hunk 13]
```diff
@@ -992,9 +994,13 @@ namespace ts {
             return !isString(entry) ? entry : undefined;
         }
 
-        public getOrCreateEntryByPath(fileName: string, path: Path): HostFileInformation {
-            const info = this.getEntryByPath(path) || this.createEntry(fileName, path);
-            return isString(info) ? undefined! : info; // TODO: GH#18217
+        public getOrCreateEntryByPath(fileName: string, path: Path, isAuxiliaryFile: boolean): HostFileInformation {
+            let info = this.getEntryByPath(path) || this.createEntry(fileName, path, isAuxiliaryFile);
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/services.ts:998]: I wanted to update the program as early as possible so it’s not happening while the user waits for completions. In practice we’re only seeing ~20ms updates so I can try this. I think  we’ll want to do the initial program creation eagerly (maybe triggered from Project) but for future updates I think doing it on demand makes sense.

File: src/server/project.ts (hunk 10 above)
Comment (andrewbranch) [reply src/server/project.ts:372]: I thought a Project subclass is probably a lot heavier of an object than I need, but I agree the ScriptInfo changes (and Project/LanguageServiceHost API changes that work with ScriptInfo) is the worst part of this PR, so maybe that would simplify things a lot.

File: src/services/services.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/services/services.ts:998]: I dont think we should create it eagerly.. Since many times project gets opened only for navigation purposes and creating this would add to the cost.. Instead doing it during completion will impact performance of first completion but later should be ok..  we already have issues with us opening project /creating project when opening the file instead of first request..

File: src/server/project.ts (hunk 10 above)
Comment (sheetalkamat) [reply src/server/project.ts:372]: Project shouldnt be that heavier than having a program. (ignore all watching in this new kind of project and other extra stuff and you should have blackbox around the program thats not that heavy) I am inclined for this because project has already handled all sorts of reclaimation and update of project/scriptinfo../ Having another kind adds to complexity and issues with correct handling of attaching/detaching and removing program etc.

Comment (andrewbranch) [reply src/server/project.ts:372]: The main part that looks unwieldy to me is that the `Project` base class unconditionally creates a LanguageService, which should never be used. The compiler options for the program to keep it lightweight (`noLib: true`, `diagnostics: false`) mean we don’t actually want to use this LanguageService for anything. (We could never return this kind of project from `scriptInfo.getDefaultProject`; we’d still need to create an InferredProject if an auto-importable script inside node_modules was opened by the client.)

Comment (sheetalkamat) [reply src/server/project.ts:372]: But even if you create LS , it will jsut create program in there since you wont use this for anything else.. If fact there is getLanguageService method on project which you can override and throw error so we know its used in unexpected ways... You can get the program from `project.getIntentionalLS().getProgram()` .. The inferred project thing shoul;d work if you accomodate exclusion of the new kind of project in all places where it shouldnt.. 
The thing i like about it is the script info/project/LS management is already sorted in these scenario and would be easy to diagnose since we already have logs in the server for changes to program and updates so just looking at the log you should be able to track if project was updated/ what files were added and so on

File: src/services/services.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/services/services.ts]: The navigation case is already handled by checking for open files in the project. There’s a unit test validating that. Creating the project on the first completions request took the response time from ~100ms to ~400ms.

File: src/server/project.ts [hunk 14]
```diff
@@ -1777,6 +1775,139 @@ namespace ts.server {
         }
     }
 
+    export class AutoImportProviderProject extends Project {
+        private static readonly newName = createProjectNameFactoryWithCounter(makeAutoImportProviderProjectName);
+
+        /*@internal*/
+        static getRootFileNames(dependencySelection: PackageJsonAutoImportPreference, hostProject: Project, compilerOptions: CompilerOptions): string[] {
+            if (!dependencySelection) {
+                return [];
```
Comment (sheetalkamat) [inline src/server/project.ts:1784]: emptyArray?

File: src/server/project.ts [hunk 15]
```diff
@@ -1777,6 +1775,139 @@ namespace ts.server {
...
+            const packageJsons = hostProject.getPackageJsonsForAutoImport(combinePaths(hostProject.currentDirectory, rootFileName));
+            for (const packageJson of packageJsons) {
+                packageJson.dependencies?.forEach((_, dependenyName) => addDependency(dependenyName));
+                packageJson.peerDependencies?.forEach((_, dependencyName) => addDependency(dependencyName));
+                if (dependencySelection === PackageJsonAutoImportPreference.All) {
+                    packageJson.devDependencies?.forEach((_, dependencyName) => addDependency(dependencyName));
+                }
+            }
+
+            if (dependencyNames) {
```
Comment (sheetalkamat) [inline src/server/project.ts:1799]: Instead of doing this why not set options.types = dependencyNames here for this project so program constructution auto includes them ?

Comment (sheetalkamat) [reply src/server/project.ts:1799]: You can modify program's getAutoTypeDirectiveNames to this instead..
```ts
// Thats correct solution project
const typeReferences: string[] = !rootNames.length && projectReferences ?  emptyArray : getAutomaticTypeDirectiveNames(options, host) ;
```

File: src/services/completions.ts [hunk 16]
```diff
@@ -179,7 +185,7 @@ namespace ts.Completions {
             return getLabelCompletionAtPosition(contextToken.parent);
         }
 
-        const completionData = getCompletionData(program, log, sourceFile, isUncheckedFile(sourceFile, compilerOptions), position, preferences, /*detailsEntryId*/ undefined, host);
+        const completionData = getCompletionData(program, log, sourceFile, isUncheckedFile(sourceFile, compilerOptions), position, preferences, /*detailsEntryId*/ undefined, host, autoImportProvider);
```
Comment (sheetalkamat) [inline src/services/completions.ts:188]: Should getStringLiteralCompletions use autoImportProvider if present ?

File: src/services/completions.ts [hunk 17]
```diff
@@ -627,6 +635,7 @@ namespace ts.Completions {
         formatContext: formatting.FormatContext,
         preferences: UserPreferences,
         cancellationToken: CancellationToken,
+        autoImportProvider: Program | undefined,
```
Comment (sheetalkamat) [inline src/services/completions.ts:638]: I think instead of passing autoImportProvider, completions should get it when using to avoid having to update/get it in cases when the completion is for eg class method or something that doesnt need auto imports

File: src/services/types.ts [hunk 18]
```diff
@@ -485,6 +504,7 @@ namespace ts {
         getProgram(): Program | undefined;
 
         /* @internal */ getNonBoundSourceFile(fileName: string): SourceFile;
+        /* @internal */ getAutoImportProvider(ensureSynchronized?: boolean): Program | undefined;
```
Comment (sheetalkamat) [inline src/services/types.ts:507]: I dont think you want ensureSynchronized parameter at all here

File: src/testRunner/unittests/services/hostNewLineSupport.ts [hunk 19]
```diff
@@ -12,7 +12,7 @@ namespace ts {
                 getCompilationSettings: () => settings,
                 getScriptFileNames: () => map(files, f => f.unitName),
                 getScriptVersion: () => "1",
-                getScriptSnapshot: name => snapFor(name),
+                getScriptSnapshot: (name: string) => snapFor(name),
```
Comment (sheetalkamat) [inline src/testRunner/unittests/services/hostNewLineSupport.ts:15]: Is this change needed?

File: src/testRunner/unittests/services/languageService.ts [hunk 20]
```diff
@@ -29,7 +29,7 @@ export function Component(x: Config): any;`
                 getScriptVersion(_fileName) {
                     return "";
                 },
-                getScriptSnapshot(fileName) {
+                getScriptSnapshot(fileName: string) {
```
Comment (sheetalkamat) [inline src/testRunner/unittests/services/languageService.ts:32]: Same? Are changes in this file needed

File: src/testRunner/unittests/tsserver/autoImportProvider.ts [hunk 21]
```diff
@@ -0,0 +1,237 @@
...
+            ]);
+
+            openFilesForSession([indexTs], session);
+            assert.isUndefined(projectService.configuredProjects.get(tsconfig.path)!.getLanguageService().getAutoImportProvider());
+
+            host.writeFile(packageJson.path, packageJson.content);
+            assert.ok(projectService.configuredProjects.get(tsconfig.path)!.getLanguageService().getAutoImportProvider());
+        });
+
+        it("Reuses autoImportProvider when program structure is unchanged", () => {
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tsserver/autoImportProvider.ts:108]: Some tests are needed to ensure that autoImport project is closed and removed with project close

File: src/server/project.ts [hunk 22]
```diff
@@ -1777,6 +1775,139 @@ namespace ts.server {
...
+                lib: ts.emptyArray,
+                sourceMap: false
+            };
+
+            const rootNames = this.getRootFileNames(dependencySelection, hostProject, compilerOptions);
+            if (!rootNames.length) {
+                return undefined;
+            }
+
+            return new AutoImportProviderProject(hostProject, rootNames, documentRegistry, compilerOptions);
```
Comment (sheetalkamat) [inline src/server/project.ts:1843]: Wonder if its good idea to keep list of autoImportProviderProjects just like inferred projects so we know whats going on and what projects exist and easy debugging?

File: src/server/editorServices.ts [hunk 23]
```diff
@@ -1078,6 +1080,7 @@ namespace ts.server {
                 this.logger.msg(`Error: got watch notification for unknown file: ${fileName}`);
             }
             else {
+                info.getContainingAutoImportProviderProjects().forEach(p => p.markAsDirty());
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/server/editorServices.ts:1083]: Actually you dont need this since info.containingProjects should handle this

File: src/server/editorServices.ts [hunk 24]
```diff
@@ -3673,6 +3686,96 @@ namespace ts.server {
...
+        private invalidateProjectAutoImports(packageJsonPath: Path | undefined) {
+            if (this.includePackageJsonAutoImports()) {
+                this.configuredProjects.forEach(invalidate);
+                this.inferredProjects.forEach(invalidate);
+                this.externalProjects.forEach(invalidate);
+            }
+            function invalidate(project: Project) {
+                if (!packageJsonPath || project.packageJsonsForAutoImport?.has(packageJsonPath)) {
+                    project.getImportSuggestionsCache().clear();
+                    project.markAutoImportProviderAsDirty();
```
Comment (sheetalkamat) [inline src/server/editorServices.ts:3775]: Do  you think getImportSuggestionsCache should clear from AutoImportProviderProject::markAsDirty instead? 
Also do you think it should clear if there is program change in AutoImportProvider instead.

File: src/server/editorServices.ts [hunk 25]
```diff
@@ -2827,7 +2840,7 @@ namespace ts.server {
             if (!firstProject.isOrphan() &&
                 isInferredProject(firstProject) &&
                 firstProject.isRoot(info) &&
-                forEach(info.containingProjects, p => p !== firstProject && !p.isOrphan())) {
+                forEach(info.containingProjects, p => p !== firstProject && p.projectKind !== ProjectKind.AutoImportProvider && !p.isOrphan())) {
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/editorServices.ts:2843]: I noticed that would usually work, but I didn’t totally understand what `isOrphan` is supposed to mean. What is the underlying concept that makes a project an orphan?

File: src/testRunner/unittests/services/hostNewLineSupport.ts (hunk 19 above)
Comment (andrewbranch) [reply src/testRunner/unittests/services/hostNewLineSupport.ts:15]: Not anymore. It was when there was an internal overload.

File: src/server/editorServices.ts (hunk 24 above)
Comment (andrewbranch) [reply src/server/editorServices.ts:3775]: No, because `AutoImportProvider` only includes files from `node_modules` that aren’t in the main program, whereas the completions cache contains all auto imports, including from local files.

File: src/server/project.ts (hunk 22 above)
Comment (andrewbranch) [reply src/server/project.ts:1843]: I thought about this at first, but you can easily get them from the list of other projects, and I didn’t end up needing to use it anyway. I think the logs already show the presence of the projects. But I’m not against it if it’s useful.

File: src/server/project.ts [hunk 26]
```diff
@@ -989,6 +990,7 @@ namespace ts.server {
 
             if (hasNewProgram) {
                 this.projectProgramVersion++;
+                this.autoImportProviderHost?.markAsDirty();
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/project.ts:993]: I think that would work, good idea 👍

File: src/services/types.ts (hunk 18 above)
Comment (andrewbranch) [reply src/services/types.ts:507]: You’re right, this is old.

File: src/server/project.ts (hunk 15 above)
Comment (andrewbranch) [reply src/server/project.ts:1799]: Oh, I had to use this approach back when I was trying a single program for all projects’ dependencies because there was no suitable `currentDirectory` that could resolve types in sibling projects with their own node_modules. But now that there’s one program per project, I think this will work.

File: src/server/editorServices.ts (hunk 24 above)
Comment (sheetalkamat) [reply src/server/editorServices.ts:3775]: So it main project contains auto import suggestions from auto import provider too? If yes when we souvenir file in auto import provider changes or say resolved module changes, shouldn’t it clear the cache of main project ? If not what do we need to clear it from invalidate when host config changes for the import preferences

File: src/server/editorServices.ts [hunk 27]
```diff
@@ -1965,6 +1969,7 @@ namespace ts.server {
         private createLoadAndUpdateConfiguredProject(configFileName: NormalizedPath, reason: string) {
             const project = this.createAndLoadConfiguredProject(configFileName, reason);
             project.updateGraph();
+            project.getPackageJsonAutoImportProvider(); // Preload AutoImportProviderProject to avoid creating it on first completions request
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/editorServices.ts:1972]: Is it ok to move that event out of `ConfiguredProject.updateGraph()`? Can it ever happen outside of `createLoadAndUpdateConfiguredProject`?

[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/editorServices.ts:1972]: Answering my own question: apparently so, because a bunch of tests fail. I’ll work around it.

File: src/services/completions.ts (hunk 16 above)
Comment (andrewbranch) [reply src/services/completions.ts:188]: It already uses package.json data, so there’s nothing to add. I still have a long-term to-do for myself to switch it to use the PackageJsonCache, though.

File: src/server/project.ts (hunk 15 above)
Comment (andrewbranch) [reply src/server/project.ts:1799]: Well... I think I would still need to resolve them here, because I need to check if the main program already contains that dependency, which is really easy when you have a resolved fileName (this happens just a few lines below your comment). Is there a better way to do that?

File: src/services/completions.ts (hunk 17 above)
Comment (andrewbranch) [reply src/services/completions.ts:638]: 👍 this is possible now that it’s exposed on `LanguageServiceHost` instead of created in the services layer.

File: src/server/project.ts (hunk 15 above)
Comment (sheetalkamat) [reply src/server/project.ts:1799]: On AutoImportProvider Projhect override resolveTypeReferenceDirective to do `super.` thing and then if file is in main project return unresolved result otherwise return actual result?

Comment (sheetalkamat) [reply src/server/project.ts:1799]: You want to do it only for inferredTypeContainingFile though... if depA has typeReferenceDirective to depB and depB is already in project, you still want depA in the auto import provider to get correct types for depA as it probably depends on it

Comment (andrewbranch) [reply src/server/project.ts:1799]: The reason I initially stopped using `Project.resolveTypeReferenceDirective` was because it created a weird watch state via the resolution cache, which ended up breaking things. When I switched to these utility methods it only slowed down by a couple ms per package.json and the watch issues were fixed. This approach seems to be working well, so I’m hesitant to reintroduce that complexity.

File: src/server/editorServices.ts (hunk 24 above)
Comment (andrewbranch) [reply src/server/editorServices.ts:3775]: If the structure of the main program changes, we already clear the cache. The only way the structure of the auto import program can change is if the structure of the main program changes (which is handled), a change occurs in node_modules or a package.json (which is handled right here), or if project/user settings change—there could possibly be a bug there, but it would be a year-old bug that no one has ever reported.

Comment (sheetalkamat) [reply src/server/editorServices.ts:3780]: WatchFailedLookupLocations, onSourceFileChanged, WatchMissingFile, watchTypeRootsDirectory, dont call this though.. which is why i think probably you want to clear importSuggestionCache whenever there is program update in the AutoImportProvider.. Again if it depends on only fileNames in the program then you can use filesAddedOrRemoved in updateGraphWorker otherwise hasNewProgram

File: src/server/editorServices.ts [hunk 28]
```diff
@@ -1973,7 +1975,9 @@ namespace ts.server {
         /* @internal */
         private createLoadAndUpdateConfiguredProject(configFileName: NormalizedPath, reason: string) {
             const project = this.createAndLoadConfiguredProject(configFileName, reason);
-            project.updateGraph();
+            project.updateGraph(/*skipEvents*/ true); // Defer telemetry and loading event until after AutoImportProvider is created
+            project.getPackageJsonAutoImportProvider(); // Preload AutoImportProviderProject to avoid creating it on first completions request
+            project.onFinishedLoading(); // Fire skipped events
```
Comment (sheetalkamat) [inline src/server/editorServices.ts:1980]: I dont think this is right way to do it.. You want to  handle it in updateGraph of main project instead.
Here are scenarios when project is created but not loaded right away but loaded when file is opened for that project

- Opening external project with lazyConfiguredProjectsFromExternalProject preference set to true
- config project structure like
serivices/tsconfig
services/compiler/tsconfig
Then you open a file from compiler and then open file from services

File: src/server/project.ts (hunk 15 above)
Comment (sheetalkamat) [reply src/server/project.ts:1805]: I think it was because you were watching at wrong time.. Infact resolutionCache is suppose to handle the caching/updates so i think its worth the try for cleaner approach. I dont think we should use main project to do resolutions for this as it may have some additional logics on when and what to resolve or which files to assume as present etc and that shouldnt play role into it.. If it shoiuld, it needs to be more explicit

File: src/server/project.ts [hunk 29]
```diff
@@ -744,12 +746,10 @@ namespace ts.server {
                 clearMap(this.missingFilesMap, closeFileWatcher);
                 this.missingFilesMap = undefined!;
             }
-            if (this.packageJsonFilesMap) {
-                clearMap(this.packageJsonFilesMap, closeFileWatcher);
-                this.packageJsonFilesMap = undefined;
-            }
             this.clearGeneratedFileWatch();
             this.clearInvalidateResolutionOfFailedLookupTimer();
+            this.autoImportProviderHost?.close();
```
Comment (sheetalkamat) [inline src/server/project.ts:751]: Sorry i forgot to mention yesterday but you need to close and release the program even from disableLanguageService

File: src/testRunner/unittests/services/languageService.ts [hunk 30]
```diff
@@ -97,7 +97,7 @@ export function Component(x: Config): any;`
                     getProjectVersion: !useProjectVersion ? undefined : () => projectVersion,
                     getScriptFileNames: () => ["/project/root.ts"],
                     getScriptVersion: path => files.get(path)?.version || "",
-                    getScriptSnapshot: path => {
+                    getScriptSnapshot: (path: string) => {
```
Comment (sheetalkamat) [inline src/testRunner/unittests/services/languageService.ts:100]: another nit to revert the change

File: src/server/editorServices.ts (hunk 24 above)
Comment (andrewbranch) [reply src/server/editorServices.ts:3780]: Ah, I see what you mean. Ok, I think that makes sense then.

File: src/server/project.ts (hunk 15 above)
Comment (andrewbranch) [reply src/server/project.ts:1805]: The next problem with this is that it means we can’t skip creating the AutoImportProviderProject if the main program already contains the dependencies, because we need a project instance to call `resolveTypeReferenceDirectives` from, but if it ends up returning an array of all `undefined` because the main program contained everything, we just wasted a lot of allocations creating the project in the first place 😕

File: src/server/protocol.ts (hunk 8 above)
Comment (andrewbranch) [reply src/server/protocol.ts:2170]: Hmm, we don’t trivially know whether the module came from dependencies or devDependencies. It would have to be a separate lookup. Do the editors have telemetry on configuration settings?

File: src/server/project.ts [hunk 31]
```diff
@@ -1779,6 +1789,144 @@ namespace ts.server {
...
+                    packageJson.devDependencies?.forEach((_, dependencyName) => addDependency(dependencyName));
+                }
+            }
+
+            if (dependencyNames) {
+                const resolutions = map(arrayFrom(dependencyNames.keys()), name => resolveTypeReferenceDirective(
+                    name,
+                    rootFileName,
+                    compilerOptions,
+                    hostProject));
```
Comment (sheetalkamat) [inline src/server/project.ts:1818]: I have concern with using hostProject here as the host if project overrides fileExist and other things to mimic presence of some files etc? Probably just needs to be this project itself as `host`

File: src/server/project.ts [hunk 32]
```diff
@@ -1572,69 +1594,59 @@ namespace ts.server {
...
+            return this.projectService.includePackageJsonAutoImports();
+        }
+
+        /*@internal*/
+        getPackageJsonAutoImportProvider(): Program | undefined {
+            if (this.autoImportProviderHost) {
+                updateProjectIfDirty(this.autoImportProviderHost);
+                if (!this.autoImportProviderHost.hasRoots()) {
+                    this.autoImportProviderHost.close();
+                    this.autoImportProviderHost = undefined;
```
Comment (sheetalkamat) [inline src/server/project.ts:1629]: I think instead of setting this as undefined here you want to set it to false or something so that next time some one asks for project, you dont have to go through dependencies, resolving type references etc unless there is some change. So you want this to autoImportProviderHost to be undefined if not calculated, false if calculated but shouldnt use and Actual project if it should

File: src/server/project.ts [hunk 33]
```diff
@@ -1914,9 +2062,14 @@ namespace ts.server {
                     result = super.updateGraph();
             }
             this.compilerHost = undefined;
+            this.onFinishedLoading();
+            return result;
+        }
+
+        /*@internal*/
+        onFinishedLoading() {
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/project.ts:2070]: Nope 👍

File: src/server/project.ts (hunk 31 above)
Comment (andrewbranch) [reply src/server/project.ts:1818]: This is a static method so there is no “this project,” but I can add a parameter for ModuleResolutionHost specifically, and pass in the project service’s host.

Comment (sheetalkamat) [reply src/server/project.ts:1818]: Well you want some changes that are different than project service's host
getCurrentDirectory
Trace:: `if (this.projectService.logger.loggingEnabled()) {
                this.trace = s => this.writeLog(s);
            }
            else if (host.trace) {
                this.trace = s => host.trace!(s);
            }`

File: src/server/project.ts [hunk 34]
```diff
@@ -1779,6 +1789,144 @@ namespace ts.server {
...
+            if (!rootFileNames) {
+                rootFileNames = AutoImportProviderProject.getRootFileNames(
+                    this.hostProject.includePackageJsonAutoImports(),
+                    this.hostProject,
+                    this.getCompilationSettings());
+            }
+
+            this.projectService.setFileNamesOfAutoImportProviderProject(this, rootFileNames);
+            this.rootFileNames = rootFileNames;
+            this.hostProject.getImportSuggestionsCache().clear();
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/server/project.ts:1899]: It depends on more that just that. In the unit test for this, I simply rename an exported class, which I believe would still be `StructureIsReused.Completely`. Keep in mind this `updateGraph()` will realistically only ever be run after a package.json change and/or `npm install`. It will also be run when people edit declaration files inside node_modules, but that’s not a common scenario—it needs to work, but it doesn’t need to be optimized with an auto-import cache.

File: src/server/project.ts [hunk 35]
```diff
@@ -989,9 +1004,17 @@ namespace ts.server {
                 this.lastCachedUnresolvedImportsList = undefined;
             }
 
+            const isFirstLoad = this.projectProgramVersion === 0;
             if (hasNewProgram) {
                 this.projectProgramVersion++;
             }
+            if (hasAddedorRemovedFiles && this.autoImportProviderHost) {
+                this.autoImportProviderHost.markAsDirty();
+            }
```
Comment (sheetalkamat) [inline src/server/project.ts:1013]:
```suggestion
            if (hasAddedorRemovedFiles) {
                if (!this.autoImportProviderHost) this.autoImportProviderHost = undefined;
                this.autoImportProviderHost?.markAsDirty();
            }
```

Comment (sheetalkamat) [reply src/server/project.ts:1013]: You would also want test the condition where your project contains everything from package json so no auto import provider and then you update your project code to not import one of the dependency.

File: src/server/project.ts [hunk 36]
```diff
@@ -1815,7 +1815,7 @@ namespace ts.server {
                     name,
                     rootFileName,
                     compilerOptions,
-                    hostProject));
+                    moduleResolutionHost));
```
Comment (sheetalkamat) [inline src/server/project.ts:1830]: You dont need to pass moduleResolutionHost here but instead you want this to also handle trace (if logging enabled going to log) and currentDIrectory
ModuleResolutionHost = hostProject.projectService ?

Comment (andrewbranch) [reply src/server/project.ts:1831]: I don’t think I understand the suggestion—`ProjectService` isn’t assignable to `ModuleResolutionHost`.

Comment (andrewbranch) [reply src/server/project.ts:1831]: Merging for the beta, feel free to follow up with me

Comment (sheetalkamat) [reply src/server/project.ts:1831]: You want it to be {
boundMethods from hostProject.projectService.host
getCurrentDirectory : () => hostProject.getCurrentDirectory(),
trace: mayBeBind(hostProject, hostProject.trace)
}

Comment (andrewbranch) [reply src/server/project.ts:1831]: Is there a realistic example of why `hostProject` itself wouldn’t work? If it wants to mimic the existence of some files, why shouldn’t it be allowed to do that during type directive resolution?

**Comment by woodgear** [comment]
> After further thought, I do think devDependencies should be excluded by default (we could add a configuration option to include them if enough people really want them). Including them by default means that virtually every project written in TypeScript would get auto-imports for the compiler, which nobody wants. If you _do_ want to import the compiler API, `typescript` is either going to be in your `"dependencies"` or `"peerDependencies"`—and we _should_ include peer dependencies by default.

sometimes we do want to auto import in devDependencies, for example, some test only package. is there some better way to avoid the "typescript" problem? maybe some kind of filter?

**Comment by andrewbranch** [comment]
Once you manually import your devDependency once, it will be available for auto-import throughout the rest of your project. So... it's kind of already a reverse filter that you configure implicitly as you code.

**Comment by nandorojo** [comment]
Is there a way to specify _which_ `package.json` to use for this?

I have a monorepo, structured like this:

- `apps`
  - `nextjs`
- `packages` 
  - `components`

My `package.json` inside of `apps/nextjs` has all of my dependencies, such as `react`, etc.

However, VSCode only checks the **root** `package.json` of my monorepo, which has zero dependencies inside of it. **As a result, none of the monorepo `packages` get autoimport.** 

Is there a way to set the setting to specify a `packageJsonPath` or something like that?

```json
  "typescript.preferences.includePackageJsonAutoImports": "on",
  "typescript.preferences.packageJsonPath": "./apps/nextjs",
```

**Comment by andrewbranch** [comment]
@nandorojo are you primarily a TypeScript or JavaScript user? (Or more to the point, is this particular project written in TypeScript?) The expected structure is that each package of a monorepo should have a tsconfig.json file. As a JS user, you can still have a tsconfig.json or jsconfig.json file there, and even just putting `{}` as its contents should be enough for package.json auto-imports to work. Note that we have an open issue for investigating inferring this structure for JS users without any tsconfig/jsconfig files, but it’s complicated: #45558.

**Comment by nandorojo** [comment]
@andrewbranch really appreciate the fast reply.

I'm a TS user exclusively. I tried adding a `tsconfig.json` to each `packages/*` folder as well, but no dice on autoimports.

Interestingly, autoimport does get solved if I duplicate my `dependencies` from `apps/nextjs/package.json` → root `package.json`'s `peerDependencies`. But it's a definite antipattern to put dependencies in the root of a workspace like that.

I don't mind having a `tsconfig` in each `packages/*` and `apps/*` folder, but I don't think this solves it for me.

I am able to autoimport my monorepo packages (`@beatgig/components` does autoimport). But the dependencies from `apps/nextjs`, such as `react`, still don't autoimport inside of `packages/*`.

Let me know if you need me to clarify anything there, it might be a bit hard to follow.

**Comment by andrewbranch** [comment]
Are you able to either share the project you’re working in or reproduce this in a little example? The only possible explanation I can think of besides this being a bug is that if we discover too many unused dependencies, we disable the package.json auto imports:

VS Code preference TypeScript - Preferences: Include Package JSON Auto Imports

This would happen if you have a bunch of dependencies listed in a package.json but the project in question has not already imported them. You can try toggling this setting to `on` and see if that makes a difference. Otherwise, go ahead and open a new issue with repro steps. Thanks!

**Comment by nandorojo** [comment]
I did already set that to `on` inside `of `.vs-code/settings.json`, actually, but unfortunately it didn't help. I don't think I can share the current repo since it's private, but I'll try to reproduce it in one you can use and will post an issue. Thank you again!

**Comment by nandorojo** [comment]
@andrewbranch I have a repro here: https://github.com/nandorojo/vscode-monorepo-autoimport-repro

It's very minimal (these are all the dependencies):

Screen Shot 2021-11-16 at 1 56 15 PM

Do you need me to open an issue, or is this sufficient? I added a few comments in the only two `ts` files that should give you what you need.

**Comment by andrewbranch** [comment]
This is working as intended—`react` is not listed in _any_ package.json visible to `packages/components/index.ts`. We filter out transitive dependencies from auto-imports because importing from packages you don’t _explicitly_ depend on is fragile—see #30033 and #38768. You don’t need to add `react` to the _root_ package.json, but it should be in `packages/components/package.json`. I believe yarn/npm/lerna will all hoist this to the root node_modules so the dependency isn’t duplicated, so there’s no reason not to specify it as a dependency.

**Comment by nandorojo** [comment]
I see, thanks for clarifying. 

It works fine if I manually import it, though, so it's as if the autoimport doesn't match the actual behavior. Both the Next.js app and the type checker work without explicitly adding these dependencies to each package.

My hesitation with adding it to `packages/components/package.json` is that I'll have tons of duplicate items in each `package.json` when it isn't actually required, either at runtime or for types. I would only add these dependencies to each package to get auto-import to work.

Is there a way to possibly _extend_ the dependencies from `apps/nextjs`? (My guess is there isn't, but just in case...)

> I believe yarn/npm/lerna will all hoist this to the root node_modules so the dependency isn’t duplicated, so there’s no reason not to specify it as a dependency.

I agree that practically speaking, since they won't duplicate, there's no real downside to this.

But in a large monorepo with over a dozen `packages/*` folders and tons of dependencies, it's a pretty rough DX to copy every dependency into so many places, given that it's all only to get the auto-imports to work. 

If there are no intentions to allow transitive dependencies (even behind a flag) for autoimports, then I'll just add each dependency to each subpackage. My guess is, you've thought about the downsides more than I have. But I thought I would leave my thoughts on the DX.

**Comment by nandorojo** [comment]
I did try explicitly adding these to my monorepo packages, as recommended, and it does solve the autoimports.

However, to prevent duplicate dependencies, I have to fix the versions in `packages/components/package.json` to the same exact ones in `apps/nextjs/package.json`. If I don't do this, then my lockfile will reflect an additional dependency.

I was hoping this would result in no changes to my lockfile, but it seems it does:

```json
{
  "name": "@repo/components",
  "version": "0.0.0",
  "main": "index.ts",
  "devDependencies": {
    "moti": "*",
  }
}
```

For example, `moti` now has `0.16.1` released. Originally, `apps/nextjs` had version `0.16.0`. But now that I added it to `@repo/components`, I now have both versions installed:

image

I can put versions there explicitly instead to avoid duplication, but it makes updating a dependency a bit of a hassle. I now have to increment the version in 15+ folders each time I want to update.

I know this is intended, but I figured it would be useful to share the downside. Thanks again!

**Comment by andrewbranch** [comment]
I think package/workspace managers have tools for doing these kind of bulk install operations. I also think that if you’re not publishing these packages individually, but rather the monorepo structure is just for code organization, there’s no great downside to putting common dependencies in the root package.json. And if you _are_ publishing each package individually, then I think it _is_ an antipattern to import transitive dependencies. There are people who vehemently disagree with me on that point in #38768, but I’m pretty firm on it.

**Comment by nandorojo** [comment]
> I also think that if you’re not publishing these packages individually, but rather the monorepo structure is just for code organization, there’s no great downside to putting common dependencies in the root package.json.

Interesting, good to know. I'm only concerned for the times that I'm using this to organize shared packages across our internal apps. When it comes to open source monorepos I publish, I do in fact copy over the dependencies in each package. But for an app with code organization, I don't know why importing transitive dependencies would really be an issue. I suppose I'll just put the deps in the root package.json, and hopefully that works fine across the apps themselves.

> I think package/workspace managers have tools for doing these kind of bulk install operations.

Maybe lerna does this, I've only used it for publishable packages so I'm not sure. If there aren't downsides to using the root package on internal projects, I might just do that. But yarn workspaces warns against it whenever you install something on the fly, so I figured it wasn't a good pattern.
