### PR TITLE
Dont emit module resolution errors when looking up specifiers for container symbols

### LINKED ISSUE #28538: Side-effect imports are checked if file uses JSX: unintentional breaking change?
Commit 7a71887c23a110009bc974f626245f03066e6926 (#27340) appears to have introduced an unintentional breaking change: side-effect module imports are now checked, but only if the file uses JSX.  This is currently causing the DefinitelyTyped CI (which uses `typescript@next`) to fail on `@types/react-table`.

**TypeScript Version:**  7a71887c23a110009bc974f626245f03066e6926 (problem does not occur in 12e371beaaa67a65a79e18a3a20244c4cd102044)

**Search Terms:** side effect module import jsx

**Code**
```ts
// code.tsx
import * as React from "react";
import "nope";
<div/>;
// tsconfig.json
{
    "compilerOptions": {
        "jsx": "react",
        "strict": true
    }
}
// package.json
{
  "devDependencies": {
    "@types/react": "^16.7.6"
  }
}
```

**Expected behavior:** No compile error.

**Actual behavior:** `error TS2307: Cannot find module 'nope'.`  But if the JSX element is removed from the file, the error goes away.

**Playground Link:** N/A, React dependency

**Related Issues:** #28032, etc. for the previous behavior

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #28538

Although I really do think it's strange we don't error on these kinds of imports.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2238,8 +2238,8 @@ namespace ts {
             return initializer || decl;
         }
 
-        function resolveExternalModuleName(location: Node, moduleReferenceExpression: Expression): Symbol | undefined {
-            return resolveExternalModuleNameWorker(location, moduleReferenceExpression, Diagnostics.Cannot_find_module_0);
+        function resolveExternalModuleName(location: Node, moduleReferenceExpression: Expression, ignoreErrors?: boolean): Symbol | undefined {
+            return resolveExternalModuleNameWorker(location, moduleReferenceExpression, ignoreErrors ? undefined : Diagnostics.Cannot_find_module_0);
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: Do you need to handle this at https://github.com/Microsoft/TypeScript/pull/28558/files#diff-c3ed224e4daa84352f7f1abcd23e8ccaL2273 because it can result in suggestion?

Comment (weswigham) [reply src/compiler/checker.ts]: Is that supposed to be a link to the diff this comment is on? Because it seems to be.

Comment (sheetalkamat) [reply src/compiler/checker.ts]: Its line 2273 in the diff

Comment (weswigham) [reply src/compiler/checker.ts]: Ah, naw that position always passes `/*isError*/ false`, so only manufactures suggestions, anyway. Given that it doesn't check the `moduleNotFoundError` flag, I assume the intent is to always generate the suggestions.

Comment (sheetalkamat) [reply src/compiler/checker.ts]: So the suggestion is raised only when the container name? Seems flaky then.

Comment (weswigham) [reply src/compiler/checker.ts]: Yeah, it probably is. I assume it was written with the estimation that the module name is resolved for all imports, rather than only-imports-with-used-exports. I didn't add the suggestion, so I'm not sure myself, though.
