### PR TITLE
Ensure resolved signature is cached before processing call errors

### LINKED ISSUE #48636: Debug Failure. No error for last overload signature
# Bug Report

### 🔎 Search Terms

"Debug Failure. No error for last overload signature"

Also, for anyone in the future finding a minimal reproduction for an error like this: edit `node_modules/typescript/tsc.js` in order to find out which line is causing the crash

```diff
- ts.Debug.fail("No error for last overload signature");
+ ts.Debug.fail("No error for last overload signature. Call:\n" + ts.getTextOfNode(node));
```

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Workbench link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAIhFgEoQIYBMD2A7ANiAPACoB8UAvFAAxQQAewEWaAzlAIxQBkUhUA-DygAuKAG8AUFClQATqky4QUANoBpKAEssUANYQQGAGY8AuiLgJk6bHiJqTxANziAvs7QQAxjhRyohgFcsT2ANbFkvbE8NHAgiGnpGFigAVQAaVOIACgA3FBwAiBFCAEoRLOZgFAYRFJLyUkJncVBIKABlYAw5dohgBhkiUgosrLA5HM7qoth4JHkbAhJ6slILeetFIZLm1uhe4E7uiAAxIJCwrCHyKAq+gZEjnvuIQeWGqByMDTRmujBusB-OdQuE9sxPDINGBgABhGQoZgACyGWUk0jyBRm6ysClsJDS6KkzD6ADV8oVHn0nqcQZd4gAfKBYAI4HDEQn1CTSKAk4DkrFZOSeKIxCC5CkQEo7VxAA)

### 💻 Code

```ts
type DeepReadonly<T> = 0 extends 1 & T ? T : {
    readonly [K in keyof T]: DeepReadonly<T[K]>;
};
declare function reconcile<T extends U, U>(value: T): (state: U) => T;

type StoreSetter<T> = ((prevState: DeepReadonly<T>) => DeepReadonly<T>);

type SetStoreFunction<T> = (setter: StoreSetter<T>) => void;

export function typescriptCrash<T>(
    value: DeepReadonly<T>,
    setValue: SetStoreFunction<T | null>,
) {
    setValue(reconcile(value));
}
```

### 🙁 Actual behavior

Typescript crashed.

```
Debug Failure. No error for last overload signature

fail@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:2468:17
resolveCall@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:62458:27
resolveCallExpression@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:62780:16
resolveSignature@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:63097:20
…
```

### 🙂 Expected behavior

Typescript should not have crashed. Also, I think the code should compile with no errors, but I'm not sure.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #48636

Big thanks to @weswigham for sitting with me for 2 hours to debug this.

I couldn't move the caching code from `resolvedSignature` down into `resolveCall`; `getResolvedSignature` conditionally sets `resolvedSignature` before calling `resolveSignature`, and `resolveSignature` then calls a bunch of other functions which do other things before actually resolving the signature. If I move this caching downward where it seems like it should be, I break enough tests to crash the test host.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -30732,6 +30732,16 @@ namespace ts {
                 return result;
             }
 
+            result = getCandidateForOverloadFailure(node, candidates, args, !!candidatesOutArray, checkMode);
+            // Preemptively cache the result; getResolvedSignature will do this after we return, but
+            // we need to ensure that the result is present for the error checks below so that if
+            // this signature is encountered again, we handle the circularity (rather than producing a
+            // different result which may produce no errors and assert). Callers of getResolvedSignature
+            // don't hit this issue becuase they only observe this result after it's had a chance to
```
Comment (Andarist) [inline src/compiler/checker.ts:30740]: nit: 
```suggestion
            // don't hit this issue because they only observe this result after it's had a chance to

```

Comment (jakebailey) [reply src/compiler/checker.ts:30740]: I'm always doing that, sigh.

**Comment by jakebailey** [comment]
RWC shows one change, and it looks to me like an extra error that shouldn't have been there in the first place (an assignment error where it complains both on the right side, then again on the left side about the same thing), so that seems good.

**Review by nievesmiguel — COMMENTED** [review]
``
