### PR TITLE
Report every instance of TS1208

### LINKED ISSUE #49995: Report every instance of TS1208 (global scripts not allowed under `isolatedModules`)
# Bug Report

When more than one global script file is present within a project using `isolatedModules`, only one error is raised for one of the problematic files.

```
File(1,1): error TS1208: 'File.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file.
Add an import, export, or an empty 'export {}' statement to make it a module.

// No additional errors for File2.ts etc.
```

This behavior seems different from other errors that are logged when `isolatedModules` is enabled. It hides the extent to which a project is incompatible with `isolatedModules`.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `isolatedModules`

### 💻 Code

The behavior appears intentional in `program.ts`. It finds the first global script file and emits one diagnostic.

https://github.com/microsoft/TypeScript/blob/7b764164ede080afff02ec731dfea72b3f4f73f3/src/compiler/program.ts#L3512-L3517

### 🙁 Actual behavior

One error of this kind is logged per compile.

### 🙂 Expected behavior

Log all of the violations, so that the extent of the problem can be assessed easily.

I changed the logic in `program.ts` locally to be a for loop that logged each problematic file, and I found this helpful for assessing the effort required to implement `isolatedModules` compatibility in an existing codebase.

### PR DESCRIPTION
**Pull request by wnayes**
Fixes #49995

Previously, many files could be considered global scripts during a compile with `isolatedModules`, but only one TS1208 error would be generated.

Now, there is one TS1208 error raised per file.

This is a simple change to loop over each file and emit TS1208 if necessary. A new test was added to confirm that multiple TS1208 errors are generated. The test failed prior to this change.

### CODE REVIEW

File: tests/cases/compiler/isolatedModulesNoExternalModuleMultiple.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// @isolatedModules: true
+// @target: es6
```
Comment (Andarist) [inline tests/cases/compiler/isolatedModulesNoExternalModuleMultiple.ts:2]: Could you also add a test with `moduleDetection: force`? Optionally you could also try to add a test `moduleDetection: auto` and with `package.json` containing `{"type":"module"}`. Note that I'm not super familiar with this new option and the latter proposed test might also require `moduleResolution: node16` (but I'm not sure about it)

Comment (wnayes) [reply tests/cases/compiler/isolatedModulesNoExternalModuleMultiple.ts:2]: Added a test case with `isolatedModules` + `moduleDetection: force`. I don't expect a regression in this area from the primary fix here, but it seems like a good test to have.

Did not add other test cases beyond that; I am not too familiar with the newer Node-related resolution behaviors, and I don't expect any regression around those.

File: src/compiler/program.ts [hunk 2]
```diff
@@ -3509,11 +3509,12 @@ namespace ts {
                     createDiagnosticForOptionName(Diagnostics.Option_preserveConstEnums_cannot_be_disabled_when_isolatedModules_is_enabled, "preserveConstEnums", "isolatedModules");
                 }
 
-                const firstNonExternalModuleSourceFile = find(files, f => !isExternalModule(f) && !isSourceFileJS(f) && !f.isDeclarationFile && f.scriptKind !== ScriptKind.JSON);
-                if (firstNonExternalModuleSourceFile) {
-                    const span = getErrorSpanForNode(firstNonExternalModuleSourceFile, firstNonExternalModuleSourceFile);
-                    programDiagnostics.add(createFileDiagnostic(firstNonExternalModuleSourceFile, span.start, span.length,
-                        Diagnostics._0_cannot_be_compiled_under_isolatedModules_because_it_is_considered_a_global_script_file_Add_an_import_export_or_an_empty_export_statement_to_make_it_a_module, getBaseFileName(firstNonExternalModuleSourceFile.fileName)));
+                for (const file of files) {
+                    if (!isExternalModule(file) && !isSourceFileJS(file) && !file.isDeclarationFile && file.scriptKind !== ScriptKind.JSON) {
```
Comment (ProKashif) [inline src/compiler/program.ts:3513]:
```suggestion
const  isIsolatedModules = !isExternalModule(file) && !isSourceFileJS(file) && !file.isDeclarationFile && file.scriptKind !== ScriptKind.JSON;

                    if (isIsolatedModules) {

```

Comment (sandersn) [reply src/compiler/program.ts:3513]: I think the predicate indicates that the file is a global (non-module) file, not that it's building under isolated modules.
There's enough context that I don't really think the predicate needs a name at all, really, but if you want one, it should be `isNonModuleSourceFile`. ('External' is obsolete)

**Review by sandersn — APPROVED** [review]
