### PR TITLE
Omnibus fixes for telemetry-sourced crashes

### LINKED ISSUE #20475: TypeError: Cannot read property 'declarations' of undefined at addPrefixForAnyFunctionOrVar
Hits / session: 19.1

Stack:
```
TypeError: Cannot read property 'declarations' of undefined
    at addPrefixForAnyFunctionOrVar (tsserver.js:73228:40)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (tsserver.js:72988:29)
    at Object.getQuickInfoAtPosition (tsserver.js:81272:70)
    at IOSession.Session.getReferences (tsserver.js:87549:72)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:86812:61)
    at tsserver.js:88233:88
    at IOSession.Session.executeWithRequestId (tsserver.js:88224:28)
    at IOSession.Session.executeCommand (tsserver.js:88233:33)
    at IOSession.Session.onMessage (tsserver.js:88253:35)
    at Interface.<anonymous> (tsserver.js:89454:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### LINKED ISSUE #20520: Assert in inferFromUsages when typing function with rest args
Code:
```
function f(...
```

Trace:
```
Exception on executing command {"seq":403,"type":"request","command":"getCodeFixes","arguments":{"file":"c:/Throwaway/a.ts","startLine":1,"startOffset":12,"endLine":1,"endOffset":15,"errorCodes":[7019,1003]}}:

    Debug Failure. False expression: Found no references!

    Error: Debug Failure. False expression: Found no references!
    at getReferences (C:\github\TypeScript\built\local\tsserver.js:92872:26)
    at inferTypeForVariableFromUsage (C:\github\TypeScript\built\local\tsserver.js:92877:67)
    at C:\github\TypeScript\built\local\tsserver.js:92812:108
    at Object.map (C:\github\TypeScript\built\local\tsserver.js:1710:29)
    at getCodeActionForParameters (C:\github\TypeScript\built\local\tsserver.js:92812:24)
    at Object.getActionsForAddExplicitTypeAnnotation [as getCodeActions] (C:\github\TypeScript\built\local\tsserver.js:92771:28)
    at C:\github\TypeScript\built\local\tsserver.js:90978:33
    at Object.forEach (C:\github\TypeScript\built\local\tsserver.js:1511:30)
    at Object.getFixes (C:\github\TypeScript\built\local\tsserver.js:90977:16)
    at C:\github\TypeScript\built\local\tsserver.js:96798:35
    at Object.flatMap (C:\github\TypeScript\built\local\tsserver.js:1771:25)
    at Object.getCodeFixesAtPosition (C:\github\TypeScript\built\local\tsserver.js:96796:23)
    at IOSession.Session.getCodeFixes (C:\github\TypeScript\built\local\tsserver.js:104325:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\github\TypeScript\built\local\tsserver.js:103203:61)
    at C:\github\TypeScript\built\local\tsserver.js:104488:88
    at IOSession.Session.executeWithRequestId (C:\github\TypeScript\built\local\tsserver.js:104479:28)
    at IOSession.Session.executeCommand (C:\github\TypeScript\built\local\tsserver.js:104488:33)
    at IOSession.Session.onMessage (C:\github\TypeScript\built\local\tsserver.js:104508:35)
    at Interface.<anonymous> (C:\github\TypeScript\built\local\tsserver.js:105760:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
```

### LINKED ISSUE #20523: Assert in getCodeActionForParameters when typing incomplete function call
Code (noImplicitAny on):
```ts
function f(x) { }
f(
```

Stack:
```ts
     Error: Debug Failure. False expression.
      at Object.zipWith (src\compiler\core.ts:218:15)
      at getCodeActionForParameters (src\services\codefixes\inferFromUsage.ts:130:47)
      at Object.getActionsForAddExplicitTypeAnnotation [as getCodeActions] (src\services\codefixes\inferFromUsage.ts:67:24)
      at src\services\codeFixProvider.ts:40:35
      at Object.forEach (src\compiler\core.ts:174:32)
      at Object.getFixes (src\services\codeFixProvider.ts:39:13)
      at src\services\services.ts:1893:32
      at Object.flatMap (src\compiler\core.ts:463:27)
      at Object.getCodeFixesAtPosition (src\services\services.ts:1891:20)
      at Object.proxy.(anonymous function) [as getCodeFixesAtPosition] (src\harness\fourslash.ts:397:66)
      at src\harness\fourslash.ts:2499:45
      at Object.flatMap (src\compiler\core.ts:463:27)
      at TestState.getCodeFixActions (src\harness\fourslash.ts:2494:23)
      at TestState.verifyCodeFix (src\harness\fourslash.ts:2448:34)
      at VerifyNegatable.codeFix (src\harness\fourslash.ts:3906:24)
      at eval (eval at runCode (src\harness\fourslash.ts:3231:23), <anonymous>:7:8)
      at runCode (src\harness\fourslash.ts:3232:13)
      at runFourSlashTestContent (src\harness\fourslash.ts:3214:9)
      at Object.runFourSlashTest (src\harness\fourslash.ts:3199:9)
```

### LINKED ISSUE #20527: Crash in getCodeFixes when rest arg follows missing open paren
Trace
```ts
function ...q) {}} f(10);
```

Stack trace
```
   TypeError: Cannot read property 'kind' of undefined
      at Object.isGetAccessor (src\compiler\utilities.ts:5802:20)
      at Object.getActionsForAddExplicitTypeAnnotation [as getCodeActions] (src\services\codefixes\inferFromUsage.ts:72:24)
      at src\services\codeFixProvider.ts:40:35
      at Object.forEach (src\compiler\core.ts:174:32)
      at Object.getFixes (src\services\codeFixProvider.ts:39:13)
      at src\services\services.ts:1893:32
      at Object.flatMap (src\compiler\core.ts:463:27)
      at Object.getCodeFixesAtPosition (src\services\services.ts:1891:20)
      at Object.proxy.(anonymous function) [as getCodeFixesAtPosition] (src\harness\fourslash.ts:397:66)
      at src\harness\fourslash.ts:2499:45
```

### LINKED ISSUE #20542: Crash in writeType when getting codefixes for invalid code
Fourslash test:
```ts
/// <reference path="fourslash.ts" />

// @noImplicitAny: true
//// function f(y, z = { p: y[

verify.not.codeFixAvailable([]);
```

Stack trace:
```
     TypeError: Cannot read property 'flags' of undefined
      at writeType (src\compiler\checker.ts:3321:29)
      at buildTypeDisplay (src\compiler\checker.ts:3316:24)
      at buildIndexSignatureDisplay (src\compiler\checker.ts:3940:21)
      at writeObjectLiteralType (src\compiler\checker.ts:3664:21)
      at writeLiteralType (src\compiler\checker.ts:3647:21)
      at writeAnonymousType (src\compiler\checker.ts:3542:25)
      at writeType (src\compiler\checker.ts:3359:25)
      at Object.buildTypeDisplay (src\compiler\checker.ts:3316:24)
      at typeToString (src\services\codefixes\inferFromUsage.ts:268:47)
      at src\services\codefixes\inferFromUsage.ts:136:40
      at Object.zipWith (src\compiler\core.ts:220:25)
      at getCodeActionForParameters (src\services\codefixes\inferFromUsage.ts:134:47)
      at Object.getActionsForAddExplicitTypeAnnotation [as getCodeActions] (src\services\codefixes\inferFromUsage.ts:71:24)
      at src\services\codeFixProvider.ts:40:35
      at Object.forEach (src\compiler\core.ts:174:32)
      at Object.getFixes (src\services\codeFixProvider.ts:39:13)
      at src\services\services.ts:1893:32
      at Object.flatMap (src\compiler\core.ts:463:27)
      at Object.getCodeFixesAtPosition (src\services\services.ts:1891:20)
      at Object.proxy.(anonymous function) [as getCodeFixesAtPosition] (src\harness\fourslash.ts:397:66)
      at src\harness\fourslash.ts:2499:45
      at Object.flatMap (src\compiler\core.ts:463:27)
      at TestState.getCodeFixActions (src\harness\fourslash.ts:2494:23)
```

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #20523 - occurs when the number of references found didn't match the function arity
Fixes #20520 - "impossible" case as described by asserts actually does occur, but can be handled safely
Fixes #20527, #20474, #20472 - containing function may be undefined in the presence of syntax errors
Fixes #20542 - symbol writer may sometimes encounter index signature with no types
Fixes #20475 - symbol writer may sometimes encounter types with no symbol

Recommend reviewing commit-by-commit. Some of these crashes are from telemetry and we've been unable to reconstruct a repro for them.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
... we should turn on strict null checks 😠

File: src/services/codefixes/inferFromUsage.ts [hunk 1]
```diff
@@ -191,8 +200,9 @@ namespace ts.codefix {
             sourceFile,
             token.getStart(sourceFile));
 
-        Debug.assert(!!references, "Found no references!");
-        Debug.assert(references.length === 1, "Found more references than expected");
+        if (!references || references.length !== 1) {
```
Comment (billti) [inline src/services/codefixes/inferFromUsage.ts]: Is the `references.length !== 1` required? Seems weird to expect an array of exactly 1 object. If there are 2, is it better to return an empty array than ignore the 2nd unexpected element? Is it guaranteed/expected to always return 1 element in this context?

Comment (RyanCavanaugh) [reply src/services/codefixes/inferFromUsage.ts]: This variable is probably badly named. `references` is not an array of references to a symbol, it's (effectively) an array of arrays; each element of the outer array refers to a different symbol (as could occur if you had a type and a value with the same name used in a position where either meaning might be valid, such as an `import` statement), and each subelement is the references to that symbol. In this case it would be very unusual (IOW we have no idea what's going on or what the right thing to do is) if we found *more than one symbol* matching a certain property.

**Comment by RyanCavanaugh** [comment]
Looking at CI failures.

Some of the fixes were for crashes I found when trying to reconstruct repros for those stacks. I believe VS is the only place we get these stack traces from - @aozgaa ?

**Comment by aozgaa** [comment]
The stack traces are from vscode.

File: src/services/codefixes/inferFromUsage.ts [hunk 2]
```diff
@@ -148,6 +152,11 @@ namespace ts.codefix {
             containingFunction.parameters.map(p => isIdentifier(p.name) ? inferTypeForVariableFromUsage(p.name, sourceFile, program, cancellationToken) : undefined);
         if (!types) return undefined;
 
+        // We didn't actually find a set of type inference positions matching each parameter position
+        if (containingFunction.parameters.length !== types.length) {
+            return undefined;
+        }
+        
         const textChanges = arrayFrom(mapDefinedIterator(zipToIterator(containingFunction.parameters, types), ([parameter, type]) =>
```
Comment (aozgaa) [inline src/services/codefixes/inferFromUsage.ts]: Now that we are doing the `length` check above, can we unroll this to an index-based for-loop? the intermediate iterator and maps are unnecessary

File: src/services/codefixes/inferFromUsage.ts (hunk 1 above)
Comment (aozgaa) [reply src/services/codefixes/inferFromUsage.ts]: Is it better to remove the asserts or leave them? There is minimal user impact either way (though throwing errors probably isn't good for perf), since we merely end up swallowing the error and writing it as part of the failure response.

File: src/services/symbolDisplay.ts [hunk 3]
```diff
@@ -496,7 +496,7 @@ namespace ts.SymbolDisplay {
             addNewLineIfDisplayPartsExist();
             if (symbolKind) {
                 pushTypePart(symbolKind);
-                if (!some(symbol.declarations, d => isArrowFunction(d) || (isFunctionExpression(d) || isClassExpression(d)) && !d.name)) {
+                if (symbol && !some(symbol.declarations, d => isArrowFunction(d) || (isFunctionExpression(d) || isClassExpression(d)) && !d.name)) {
```
Comment (aozgaa) [inline src/services/symbolDisplay.ts]: So if `symbol === undefined` we will just leave the name blank? Is that desirable behavior? Should we perhaps instead fail to build the display completely?

Comment (RyanCavanaugh) [reply src/services/symbolDisplay.ts]: This code path builds either anonymous or non-anonymous declarations (e.g. `function (x)` or `function y(x)`), so it's already regularly producing non-named symbol displays. In the case where the originating type doesn't have a symbol, it's sort of de facto anonymous anyway so it seems like this won't ever produce any particularly weird output.

**Comment by RyanCavanaugh** [comment]
> Is it better to remove the asserts or leave them? 

I see this as a correctness thing - in an ideal world, a failing assert in TS Server would pop an assert dialog in VS in debug builds. Since we now know that these conditions (e.g. `references` being length non-1) under non-impossible situations, we should write the code accordingly
