### PR TITLE
Defer creation of node typings installer

### LINKED ISSUE #52705: TS Server stats files in ATA cache even if ATA is not being used
Related to #52695

# Bug Report

### 🔎 Search Terms

- fs.stat
- statSync
- performance

### Problem
Create a new project that has simple tsconfig and open a single `.ts` file with the contents:

```ts
import fs from 'fs';
```

After opening this project in VS Code, I notice a large number of fs.stat calls into `/Users/matb/Library/Caches/typescript/5.0/`, where automatically acquired types are stored. However according to the TS Server log, none of these files end up in the project

Here's a log of all the file stat calls when opening this one file:

 
[tsSyncCalls.txt](https://github.com/microsoft/TypeScript/files/10700536/tsSyncCalls.txt)

### PR DESCRIPTION
**Pull request by sheetalkamat**
Alternative suggestion by @sandersn in #52817
Fixes #52705

### CODE REVIEW

File: src/typingsInstaller/nodeTypingsInstaller.ts [hunk 1]
```diff
@@ -106,9 +106,9 @@ type ExecSync = (command: string, options: ExecSyncOptions) => string;
 export class NodeTypingsInstaller extends TypingsInstaller {
     private readonly nodeExecSync: ExecSync;
     private readonly npmPath: string;
-    readonly typesRegistry: Map<string, MapLike<string>>;
+    typesRegistry: Map<string, MapLike<string>> = undefined!;
```
Comment (jakebailey) [inline src/typingsInstaller/nodeTypingsInstaller.ts:109]: Does this need `undefined!`? It appears to be assigned in the constructor (otherwise I would personally prefer an assertDefined instead)

Comment (sheetalkamat) [reply src/typingsInstaller/nodeTypingsInstaller.ts:109]: oops thats from last change. it doesnt need to change ..

File: src/typingsInstaller/nodeTypingsInstaller.ts [hunk 2]
```diff
@@ -272,8 +227,50 @@ process.on("disconnect", () => {
     }
     process.exit(0);
 });
-const installer = new NodeTypingsInstaller(globalTypingsCacheLocation!, typingSafeListLocation!, typesMapLocation!, npmLocation, validateDefaultNpmLocation, /*throttleLimit*/5, log); // TODO: GH#18217
-installer.listen();
+let installer: NodeTypingsInstaller | undefined;
+process.on("message", (req: TypingInstallerRequestUnion) => {
+    installer ??= new NodeTypingsInstaller(globalTypingsCacheLocation!, typingSafeListLocation!, typesMapLocation!, npmLocation, validateDefaultNpmLocation, /*throttleLimit*/5, log); // TODO: GH#18217
```
Comment (jakebailey) [inline src/typingsInstaller/nodeTypingsInstaller.ts:232]: Rather than move this entire method body out + exposing a private property, can we instead move it to a method like `handleMessage`, and then at the bottom do something like:

```ts
let installer: NodeTypingsInstaller | undefined;
process.on("message", (req: TypingInstallerRequestUnion) => {
    installer ??= new NodeTypingsInstaller(globalTypingsCacheLocation!, typingSafeListLocation!, typesMapLocation!, npmLocation, validateDefaultNpmLocation, /*throttleLimit*/5, log); // TODO: GH#18217
    installer.handleMessage(req)
})
```

**Review by jakebailey — APPROVED** [review]
Viewing at https://github.com/microsoft/TypeScript/pull/52904/files?w=1, LGTM. Thanks!

**Comment by sheetalkamat** [comment]
@mjbvz  @zkat  with this change it also means that `ti.log` file wont be created unless typing installer is used. Will this break any of the error logging/telemetry or other test/log collection.

**Comment by mjbvz** [comment]
Not that I'm aware of on the VS Code side. I almost never look at or request users send the `ti.log`, just the `tsserver.log`

**Review by andrewbranch — APPROVED** [review]
