### PR TITLE
fix(45607): Snippet import statement completions don't work for 'import type' 

### LINKED ISSUE #45607: Snippet import statement completions don't work for 'import type'
```ts
// @filename: yadda.ts
export interface Yadda {
}

// @filename: badda.ts
import type /**/
```

Request completions at `/**/`

**Expected**

`Yadda` is a completion item.

**Actual**

`Yadda` is not a completion item.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45607

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@andrewbranch I think your review will be helpful 😄

File: src/services/completions.ts [hunk 1]
```diff
@@ -3385,4 +3390,18 @@ namespace ts.Completions {
...
+                return (node as ImportOrExportSpecifier).parent.parent.isTypeOnly;
+            case SyntaxKind.ImportClause:
+            case SyntaxKind.ImportEqualsDeclaration:
+                return (node as ImportClause | ImportEqualsDeclaration).isTypeOnly;
+            case SyntaxKind.NamespaceImport:
+                return (node as NamespaceImport).parent.isTypeOnly;
+            default:
+                return false;
+        }
+    }
```
Comment (andrewbranch) [inline src/services/completions.ts:3406]: You can just use `isTypeOnlyImportOrExportDeclaration` already defined in utilities since `importCompletionNode` will be undefined if you’re actually on an export specifier.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/completions.ts]: Oke, thanks

**Review by andrewbranch — APPROVED** [review]
Thanks!
