### PR TITLE
Check to make sure default npm exists at path before trying to use it

### LINKED ISSUE #30909: Automatic typings acquisition tries to uses non-existant version of npm if run from a version of node that does not include npm
**TypeScript Version:**  3.5.0-dev.20190412

**Repo**
1. On a machine that has a global version of node and npm installed
1. Spawn the TS Server using a version of node that does not include npm
1. Trigger automatic type acquisition

**Bug**
See ATA fail. This is because ATA will try to use the version of npm that is next to the version of node that it is being run by

### PR DESCRIPTION
**Pull request by mjbvz**
**Bug**
If the typings installer is run under a copy of node that does not include npm—but on a machine that does have npm installed—it will incorrectly try to use the npm that does not exist next to its running version of node

**Fix**
Make sure that we check that npm we select exists before trying to use it as the default. Otherwise, fall back to using plain old `npm`

Fixes #30909

### CODE REVIEW

File: src/typingsInstaller/nodeTypingsInstaller.ts [hunk 1]
```diff
@@ -29,13 +29,14 @@ namespace ts.server.typingsInstaller {
...
 
     /** Used if `--npmLocation` is not passed. */
-    function getDefaultNPMLocation(processName: string) {
+    function getDefaultNPMLocation(processName: string, host: InstallTypingHost): string {
         if (path.basename(processName).indexOf("node") === 0) {
-            return `"${path.join(path.dirname(process.argv[0]), "npm")}"`;
-        }
-        else {
-            return "npm";
+            const npmPath = path.join(path.dirname(process.argv[0]), "npm");
```
Comment (sheetalkamat) [inline src/typingsInstaller/nodeTypingsInstaller.ts]: Isnt this normally directory ? (and that resolving to `npm.cmd` or other depending on os) ?

Comment (mjbvz) [reply src/typingsInstaller/nodeTypingsInstaller.ts]: I don't understand. This was an extract constant of the existing value

Comment (sheetalkamat) [reply src/typingsInstaller/nodeTypingsInstaller.ts]: Eg. on windows using eg: `"c:\Program Files\nodejs\npm"` works because there is `"c:\Program Files\nodejs\npm.cmd"`. In your case the fileExists is going to fail because `"c:\Program Files\nodejs\npm"` isn't file but directory.

Comment (mjbvz) [reply src/typingsInstaller/nodeTypingsInstaller.ts]: I'm assuming there is always a npm executable based on usage. There seems to be one on windows and MacOs when I checked. If there is just npm dir, wouldn't running `/Users/matb/path/to/npm install ata-stuff` from the command line always fail?

Comment (sheetalkamat) [reply src/typingsInstaller/nodeTypingsInstaller.ts]: Oops my bad when I looked up I thought `npm` is folder and not file..

**Comment by amcasey** [comment]
@sheetalkamat I checked my mail box and chat histories but couldn't find anything about ATA from last May.  I'm not sure I was involved.
We changed node versions and install paths a few VS versions ago, so it's possible this is no longer an issue.

**Comment by mjbvz** [comment]
@amcasey Would old VS Versions still be broken though? Can we perhaps pass in a command line flag to enable this new behavior?

**Comment by amcasey** [comment]
@mjbvz Good catch - yes, it would have to be behind a flag (assuming it works now).
