### PR TITLE
Number and enum literal are assignable to enums, even inside unions

### LINKED ISSUE #10738: Assignability between number and enum type
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
enum E {
  A,
  B
}

let n: number = 0;

let y: E = n;
let z: E|boolean = n;  // ERROR(9,5): : Type 'number' is not assignable to type 'boolean | E'.

```

**Expected behavior:**

Either disallow assigning `number` to `E`, reasonable if one considers `E` equivalent to `0 | 1`. Or allow the assignment of `number` to `E | boolean`.

**Actual behavior:** 

let z: E|boolean = n;  // ERROR(9,5): : Type 'number' is not assignable to type 'boolean | E'.

### LINKED ISSUE #10776: Nominal enum assignability after union
**TypeScript Version:**  2.0 RC. This was working correctly in 2.0 beta.

**Code**

```ts
module X {
	export enum Foo {
		A, B
	}
}
module Y {
	export enum Foo {
		A, B
	}
}
const x: X.Foo = Y.Foo.A;
const y: X.Foo | undefined = Y.Foo.A;
```

**Expected behavior:**
Both assignments are valid.

**Actual behavior:** 
The first assignment is valid, the second throws an error saying "Type 'Foo' is not assignable to type 'Foo | undefined'."

This block a project that depends on the TypeScript api, and on some package that also depends on TypeScript. So TS is installed on `node_modules/typescript` and `node_modules/foo/node_modules/typescript`. (Normally NPM would install TypeScript only once, but `foo` is a symlink.) This causes that objects from one installation of TypeScript cannot be passed to the other. The following code illustrates that:
```typescript


import * as ts from "typescript";
import * as ts2 from "foo/node_modules/typescript";

const identifier: ts.Identifier = undefined as any;
const identifier2: ts2.Identifier = identifier;

const ok: ts.SyntaxKind = ts2.SyntaxKind.AbstractKeyword;
const error: ts.SyntaxKind | undefined = ts2.SyntaxKind.AbstractKeyword;
```
Error on the declaration of `identifier2`:
```
Type 'ts.Identifier' is not assignable to type 'ts.Identifier'.
  Types of property 'originalKeywordKind' are incompatible.
    Type 'SyntaxKind | undefined' is not assignable to type 'SyntaxKind | undefined'.
      Type 'SyntaxKind.Unknown' is not assignable to type 'SyntaxKind | undefined'.
```
And on `error`:
```
Type 'SyntaxKind' is not assignable to type 'SyntaxKind | undefined'.
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #10738
Fixes #10776

Enum literals are assignable to enum literals, but only if they come from non-const enums that share the same name. This is what we call "partially nominal" and was introduced in 1.8 or 1.7, but it got lost in the upgrade to enums-as-unions.

### CODE REVIEW

**Comment by sandersn** [comment]
@mhegazy @ahejlsberg I think you are the best people to review this fix.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6235,6 +6235,9 @@ namespace ts {
             if (relation === assignableRelation || relation === comparableRelation) {
                 if (source.flags & TypeFlags.Any) return true;
                 if (source.flags & (TypeFlags.Number | TypeFlags.NumberLiteral) && target.flags & TypeFlags.Enum) return true;
+                if (source.flags & (TypeFlags.Number | TypeFlags.NumberLiteral) &&
+                    target.flags & TypeFlags.Union &&
+                    forEach((target as UnionType).types, t => t.flags & TypeFlags.EnumLike)) return true;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `isTypeOfKind`

Comment (sandersn) [inline src/compiler/checker.ts]: Actually, this code shouldn't be checking for unions at all. The outer `isRelatedTo` machinery handles it. The much simpler fix is to just change the previous line from `TypeFlags.Enum` to `TypeFlags.EnumLike`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6234,8 +6234,15 @@ namespace ts {
             if (source.flags & TypeFlags.Null && (!strictNullChecks || target.flags & TypeFlags.Null)) return true;
             if (relation === assignableRelation || relation === comparableRelation) {
                 if (source.flags & TypeFlags.Any) return true;
-                if (source.flags & (TypeFlags.Number | TypeFlags.NumberLiteral) && target.flags & TypeFlags.Enum) return true;
+                if (source.flags & (TypeFlags.Number | TypeFlags.NumberLiteral) && target.flags & TypeFlags.EnumLike) return true;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This will allow a numeric literal with a particular value to be assigned to an enum literal with a different value. I don't think we want that.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6234,8 +6234,15 @@ namespace ts {
...
-                if (source.flags & (TypeFlags.Number | TypeFlags.NumberLiteral) && target.flags & TypeFlags.Enum) return true;
+                if (source.flags & (TypeFlags.Number | TypeFlags.NumberLiteral) && target.flags & TypeFlags.EnumLike) return true;
                 if (source.flags & TypeFlags.NumberLiteral && target.flags & TypeFlags.EnumLiteral && (<LiteralType>source).text === (<LiteralType>target).text) return true;
+                if (source.flags & TypeFlags.EnumLiteral &&
+                    target.flags & TypeFlags.EnumLiteral &&
+                    (<LiteralType>source).text === (<LiteralType>target).text &&
+                    (<EnumLiteralType>source).baseType.symbol.name === (<EnumLiteralType>target).baseType.symbol.name &&
+                    !isConstEnumSymbol((<EnumLiteralType>source).baseType.symbol) && !isConstEnumSymbol((<EnumLiteralType>target).baseType.symbol)) {
+                    return true;
+                }
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This entire test is different (and more permissive) from what we check in `isEnumTypeRelatedTo`. What we need to do here is first check that the base enums of the two literals are related (using `isEnumTypeRelatedTo`), and then check that they have the same value (by comparing their `text` properties).

Also, we really should cache the result of `isEnumTypeRelatedTo`. It's a very expensive check and we do it all over each time.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/checker.ts]: fixed

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/checker.ts]: fixed. I'm not sure I wrote the cache correctly, so you might want to check that -- I just stuck it right below assignableRelation, identityRelation, et al since it is used in the same region.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -6206,8 +6207,14 @@ namespace ts {
...
-            if (source.symbol.name !== target.symbol.name || !(source.symbol.flags & SymbolFlags.RegularEnum) || !(target.symbol.flags & SymbolFlags.RegularEnum)) {
-                return false;
+            const id = source.id + "," + target.id;
+            if (enumRelation[id] !== undefined) {
+                return enumRelation[id];
+            }
+            if (source.symbol.name !== target.symbol.name ||
+                !(source.symbol.flags & SymbolFlags.RegularEnum) || !(target.symbol.flags & SymbolFlags.RegularEnum) ||
+                !(source.flags & TypeFlags.Union) || !(target.flags & TypeFlags.Union)) {
+                return (enumRelation[id] = false);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: No need for parentheses here.

**Comment by sandersn** [comment]
Based on discussion with @ahejlsberg, I loosened number-to-enum assignability and tightened enum-to-enum assignability in the last commit.

1. All numbers and numeric literals are assignable to all enums and enum literals. This is for backward compatibility, because flag-style enums may get converted to a union-enum, and we want to preserve the `{ flags: 0 }` behaviour even when an enum doesn't have a `None = 0` entry.
2. Computed enums are only assignable to themselves, just like const enums. Only union enums are assignable "semi-structurally". This is stricter than before, but we don't expect that many people at all will have tried to assign different versions of a flag-style enum to each other.

**Comment by sandersn** [comment]
Never mind, (2) should be "Computed enums are only assignable to other computed enums". I updated the code to reflect the change.

**Comment by ahejlsberg** [comment]
:+1: Once my last code review comments are addressed.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -6206,8 +6207,14 @@ namespace ts {
...
-            if (source.symbol.name !== target.symbol.name || !(source.symbol.flags & SymbolFlags.RegularEnum) || !(target.symbol.flags & SymbolFlags.RegularEnum)) {
-                return false;
+            const id = source.id + "," + target.id;
+            if (enumRelation[id] !== undefined) {
+                return enumRelation[id];
+            }
+            if (source.symbol.name !== target.symbol.name ||
+                !(source.symbol.flags & SymbolFlags.RegularEnum) || !(target.symbol.flags & SymbolFlags.RegularEnum) ||
+                (source.flags & TypeFlags.Union) !== (target.flags & TypeFlags.Union)) {
+                return (enumRelation[id] = false);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Remove unnecessary parentheses here and two more places below.

Comment (sandersn) [inline src/compiler/checker.ts]: done

**Comment by sandersn** [comment]
@mhegazy do you want me to merge this into 2.0 too?

**Comment by mhegazy** [comment]
yes please.

**Comment by sandersn** [comment]
Done. Merged to 2.0 and 2.0.5

**Comment by mhegazy** [comment]
thanks!
