### PR TITLE
Fix getTypeFacts for pattern template literal types

### LINKED ISSUE #41651: RangeError: Maximum call stack size exceeded with template literal since 4.1.0-dev.20200923
## TypeScript Version:

`4.1.2`, `4.2.0-dev.20201123`

Oldest affected: `4.1.0-dev.20200923`
Newest non-affected: `4.1.0-dev.20200920`

## Search Terms:

RangeError, Maximum call strack size exceeded, getTypeFacts

## Code:

```
// The unused first parameter here is necessary. Without it, the bug is not triggered.
// The default `= string` here is necessary. Without it, the bug is not triggered.
export type Id<TA, TId extends string = string> = `${TId}-${TId}`;

export class A {}

export abstract class B {
    // When specifying the second type parameter here, the bug is not triggered.
    abstract get(id: Id<A>): void;

    // Both methods are needed to trigger the bug.
    update(id: Id<A>): void {
        // The Exclamation mark (`!`) below is needed to trigger the bug.
        this.get(id!);
    }
}
```

## Expected behavior:

Compiles without error or warning.

## Actual behavior:

Compiler crashes:

```
$ /home/prior/repositories/typescript-reproduce/node_modules/.bin/tsc reproduce.ts
/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:87210
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52147:30)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
    at getTypeFacts (/home/prior/repositories/typescript-reproduce/node_modules/typescript/lib/tsc.js:52207:24)
```

## Playground Link:

[here](https://www.typescriptlang.org/play?ts=4.2.0-dev.20201123#code/PTAEBUAsFNQVwHZwM7QCagGYEsBOyAXUABwENdSBbaA6XUGXWbZUBaAYw+mWXIE8AdKADq2ApAD2cIuIA0oCbABGcAOagWbSUQK5satXXSCAsACgQEGKDTRMpOABsiAAwC8oQvoRrXDY01Wdi4ePlwhUXEpGU0CBSVQVQ0tBB1FfUNjNDNzaAAPYklcXX5iWABJNAAecABBBXAq0ALaBDRWb2xfUE8u3wA+XtBXABIAbya0AF8AWgmp6dcAbgsLAqKS0A4nUl5QOtBx6bW8wuKiUmVvUg4iHb3WACEji1B30CsRGAQvco5sJh+N0NIlUBxJO1FGVYGQKNRaPRGNAEjZkkFtLpMkYmDk3h8rjc7qAjAQABTYNAALlAVWqdQGAEoaQA3SSU1bmfHvKxPHSQUAIqQdUDkWDsdDoRSSDIGHGKNHqXIfeDENCkWgU6m0moM5mgNmU17mFUqqxQWAAUXyD0oGuwkMF5AA1qAya4AISuRlJaBOSQAdwxErsGAIMr0croCpUSu5pokLEEpK1HsZnJVJ3M0yAA)

## Related Issues:

None

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes a stack overflow that occurs when calling `getTypeFacts` on a pattern template literal type (such as `` `foo${string}` ``). The PR also adds normalization of template literal types consisting of only `${string}` placeholders. Such template literal types are now reduced to just `string`.

Fixes #41651.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@RyanCavanaugh @DanielRosenwasser I think we should backport this. Currently `getTypeFacts` causes a stack overflow when invoked on a pattern template literal type (or a union containing a pattern template literal type). This for example happens with the `||`, `&&`, `??`, and postfix `!` operators.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13679,6 +13679,9 @@ namespace ts {
                 return getLiteralType(text);
             }
             newTexts.push(text);
+            if (every(newTexts, t => t === "") && every(newTypes, t => !!(t.flags & TypeFlags.String))) {
```
Comment (weswigham) [inline src/compiler/checker.ts:13682]: Can `newTypes` be somehow empty here? This is obviously incorrect if it can be (since the right result then is simply the empty string type). If we don't need to check for an empty type array here, we should probably at least have a comment indicating why we don't.

**Review by weswigham — COMMENTED** [review]
The facts changes look fine, small question about the simplification though.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:13682]: There's a check for `newTypes.length === 0` literally one line above the diff cutoff here, so that definitely can't happen. Not sure a comment is necessary, when you're looking at the actual source code it's pretty clear.

Comment (weswigham) [reply src/compiler/checker.ts:13682]: Hah, sorry, yeah, ok. Diffs don't really expand in `checker` and I was reading on mobile~

**Review by weswigham — APPROVED** [review]

**Comment by zoontek** [comment]
Will this be released before `4.3`? (ex: in `4.2.4`)

**Comment by ahejlsberg** [comment]
It should be fixed in all releases since `4.2`.

**Comment by zoontek** [comment]
@ahejlsberg Ok, so it's another issue: https://twitter.com/zoontek/status/1376606905729232897 (I use template string inference and recursive types - it doesn't happen on `4.3` dev version, so I will track commits to check what fixes it).

Sorry for the bothering!
