### PR TITLE
fix(38299): Bug in the __rest helper function for numeric properties

### LINKED ISSUE #38299: Bug in the __rest helper function for numeric properties
**TypeScript Version:** Nightly

**Search Terms:** namespace rest export number numeric object destructuring pattern

**Code**

```ts
namespace Foo { 
    export let { 0: a, ...b } = [0, 1]
    console.log(JSON.stringify({a, b}))
}
```

**Expected behavior:**

I expect this to log `{"a":0,"b":{"1":1}}` because that's what you get when you run the following JavaScript natively:

```js
let { 0: a, ...b } = [0, 1];
console.log(JSON.stringify({a, b}))
```

**Actual behavior:**

This actually logs `{"a":0,"b":{"0":0,"1":1}}`.

I'm working on my own TypeScript parser for [esbuild](https://github.com/evanw/esbuild), a JavaScript bundler, and I noticed that the code TypeScript generates for destructuring object properties has this bug. The generated code for the sample above looks like this:

```js
"use strict";
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
var Foo;
(function (Foo) {
    var _a;
    _a = [0, 1], Foo.a = _a[0], Foo.b = __rest(_a, [0]);
    console.log(JSON.stringify({ a: Foo.a, b: Foo.b }));
})(Foo || (Foo = {}));
```

The problem is that the numeric property is passed to `__rest` as a number, not as a string, but `__rest` is implemented using `indexOf` which doesn't consider `0` and `"0"` to be equal.

I think the most straightforward fix would be for the compiler to emit `__rest(_a, ["0"])` instead of `__rest(_a, [0])`.

**Playground Link:** https://www.typescriptlang.org/play/?ts=Nightly#code/HYQwtgpgzgDiDGEAEAxA9mpBvJAoJBSEAHjGgE4AuSANhNTgAwBcSIANEgHQ8BGSAXyQBeJAG1GnAIwBdfIXhpgUNHS400AcwAUAKQDKAeQByXKJXIBLYJssAzAJ7asHJLwEBKD7gG4gA

**Related Issues:** I couldn't find any existing issues about this.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #38299

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
cc @rbuckton

File: src/compiler/transformers/destructuring.ts [hunk 1]
```diff
@@ -562,7 +562,7 @@ namespace ts {
                     );
                 }
                 else {
-                    propertyNames.push(createLiteral(propertyName));
+                    propertyNames.push(createStringLiteral(getTextOfIdentifierOrLiteral(propertyName)));
```
Comment (rbuckton) [inline src/compiler/transformers/destructuring.ts:565]: That's what `createLiteral` does, except it also sets `textSourceNode` to try to preserve the source text. I think the bug is actually in emitter.ts in `getLiteralTextOfNode`. In that function we check `isIdentifier(textSourceNode)` to ensure we add quotes, but we really should be checking `isIdentifier(textSourceNode) || isNumericLiteral(textSourceNode)` instead, and possibly ensuring we use the canonical string for the numeric literal (from its `text` property), since `1.0` toStrings to `"1"`.

Comment (a-tarasyuk) [reply src/compiler/transformers/destructuring.ts]: @rbuckton Thanks for the feedback 👍. I was thinking about changing the `getLiteralTextOfNode` however decided to change part of code related only to `__rest` helper :confused:.

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -4487,7 +4487,7 @@ namespace ts {
         function getLiteralTextOfNode(node: LiteralLikeNode, neverAsciiEscape: boolean | undefined, jsxAttributeEscape: boolean): string {
             if (node.kind === SyntaxKind.StringLiteral && (<StringLiteral>node).textSourceNode) {
                 const textSourceNode = (<StringLiteral>node).textSourceNode!;
-                if (isIdentifier(textSourceNode)) {
+                if (isIdentifier(textSourceNode) || isNumericLiteral(textSourceNode)) {
                     return jsxAttributeEscape ? `"${escapeJsxAttributeString(getTextOfNode(textSourceNode))}"` :
                         neverAsciiEscape || (getEmitFlags(node) & EmitFlags.NoAsciiEscaping) ? `"${escapeString(getTextOfNode(textSourceNode))}"` :
                         `"${escapeNonAsciiString(getTextOfNode(textSourceNode))}"`;
```
[the remark this answers is not in the document]
Comment (a-tarasyuk) [reply src/compiler/emitter.ts]: @rbuckton Thanks for the clarification. 👍

**Comment by rbuckton** [comment]
Looks good, thanks!
