### PR TITLE
Elide re-exports of unresolved type-only imports

### LINKED ISSUE #56445: Invalid JavaScript output with re-exported  unresolved import types (regression)
### 🔎 Search Terms

export type invalid JavaScript

### 🕗 Version & Regression Information

- This changed between versions 5.1 and 5.2 

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.1.6#code/JYWwDg9gTgLgBDAnmApnA3nAyhEKAqyaAvnAGZS5wDkAdAPRKrUDcAsAFCcoAeksGbLgJE4cYuw5A)

### 💻 Code

```ts
import type { SomeType } from './type';

export { SomeType  };
```

### 🙁 Actual behavior

TypeScript will generate the following JS:

```js
export { SomeType };
```

This JS is invalid since `SomeType` is not defined. Basically the `import type` is removed, but the `export` of the type was not.

### 🙂 Expected behavior

Type should be removed from export as in 5.1

### Additional information about the issue

In the example above the source code has errors, so it could be argued that the output does not have to be valid. The issue was however discovered when using `transpileModule` . `transpileModule` similarly can't by design resolve the types and will preserve them in the output even though the types actually exist. 

This is going to block us at Bloomberg from fully adopting TS 5.2 as we have workflows that depend on `transpileModule`

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #56445

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -47581,7 +47581,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         }
         const target = getExportSymbolOfValueSymbolIfExported(resolveAlias(symbol));
         if (target === unknownSymbol) {
-            return true;
+            return !excludeTypeOnlyValues || !getTypeOnlyAliasDeclaration(symbol);
```
Comment (jakebailey) [inline src/compiler/checker.ts:47584]: Does this need a test for the other condition? I think the test covers the latter only.

**Review by jakebailey — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:47584]: `!excludeTypeOnlyValues` is never covered under any test because I’m pretty sure it’s never correct to pass `false` for that. I fixed one case that forgot to pass `true` for it in https://github.com/microsoft/TypeScript/pull/55097, and the last remaining caller didn’t change any baselines when I had it pass `true`. I made a note to look at it and probably remove the parameter altogether in a follow-up PR.

Comment (andrewbranch) [reply src/compiler/checker.ts:47584]: Oh yeah, the last place that doesn’t pass `true` is checking whether to elide an ImportEqualsDeclaration, which doesn’t strictly matter because it’s not a runtime error to `require()` a module that doesn’t export anything. But it should probably be elided anyway, so it’s likely that parameter will go away and we’ll treat it as if it’s always `true`.

Comment (jakebailey) [reply src/compiler/checker.ts:47584]: Sounds good, thanks!

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-5.3
