### PR TITLE
Don't report quickInfo inside a comment in a PropertyAccessExpression

### LINKED ISSUE #19984: Incorrect quickInfo span for comment in method chain
From https://github.com/Microsoft/vscode/issues/35597

**TypeScript Version:**  2.7.0-dev.20171112

**Code**

```ts
a
// *********************************************************
// MOUSEOVER ANYTHING IN THIS COMMENT
// *********************************************************
.b(() => {
})
```

Hover over the comment

**Expected behavior:**
No quick info returned

**Actual behavior:**
Quick info returned that includes both the comment and `.b`

```
[Trace  - 14:01:46] Sending request: quickinfo (86). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/file1.js",
    "line": 4,
    "offset": 15
}
[Trace  - 14:00:28] Response received: quickinfo (77). Request took 1 ms. Success: true 
Result: {
    "kind": "",
    "kindModifiers": "",
    "start": {
        "line": 1,
        "offset": 1
    },
    "end": {
        "line": 5,
        "offset": 3
    },
    "displayString": "any",
    "documentation": "",
    "tags": []
}
```

screen shot 2017-11-13 at 2 01 47 pm

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19984

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -1489,6 +1472,23 @@ namespace ts {
             };
         }
 
+        function shouldGetType(sourceFile: SourceFile, node: Node, position: number): boolean {
```
Comment (mhegazy) [inline src/services/services.ts]: this is purely stylistic. but i think it read better before. in general refactoring inner pieces of logic that are rather specific to a certain code path makes it harder to understand the flow.

Comment (andy-ms) [reply src/services/services.ts]: Previously we used switch-case fallthrough to determine whether to reach the last case. That was possible with only two cases, but it's not possible any more when we need two cases to both goto the same third case.
