### PR TITLE
Namespace before ambient derived class finds heritage

### LINKED ISSUE #4485: Instantiated namespace preceding ambient derived class ruins assignability
```TypeScript
declare class Base {
    public blah;
}

namespace Derived {
    var x;
}

declare class Derived extends Base {
}

var b: Base = new Derived
```

Error:

```
foo.ts(12,5): error TS2322: Type 'Derived' is not assignable to type 'Base'.
  Property 'blah' is missing in type 'Derived'.
```

If you remove the `var x` from the namespace, or move the namespace last, everything works.

### PR DESCRIPTION
**Pull request by sandersn**
This fixes #4485 by making `getBaseTypeNodeOfClass` look for the declaration that is a class instead of assuming that `valueDeclaration` is a class. In the test case, it's a namespace, which is correct since namespaces have a value side.

I'm not sure whether other places that reference `valueDeclaration` assume they are dealing with a class even when they have a merged namespace+class. I'll take a look. In the meantime, @ahejlsberg, can you take a look to see whether this localised fix is appropriate?

### CODE REVIEW

**Comment by sandersn** [comment]
Looks like there are some test failures, even though I was getting a clean run on my machine. The failures show up when I run `jake clean` before `jake runtests`. Is that required to get a valid test run?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2766,7 +2766,9 @@ namespace ts {
         }
 
         function getBaseTypeNodeOfClass(type: InterfaceType): ExpressionWithTypeArguments {
-            return getClassExtendsHeritageClauseElement(<ClassLikeDeclaration>type.symbol.valueDeclaration);
+            let classDeclaration =
+                getDeclarationOfKind(type.symbol, SyntaxKind.ClassDeclaration) || type.symbol.valueDeclaration;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Does `getDeclarationOfKind` ever actually fail?

Comment (sandersn) [inline src/compiler/checker.ts]: I didn't think so either, but it fails for symbols with `kind === SyntaxKind.ClassExpression` (among others). At any rate @ahejlsberg suggested a better way -- keep valueDeclaration correct when assigning it in the binder and when merging symbols.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: There's a function called `getClassLikeDeclarationOfSymbol`

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I don't actually see that as a better idea. The `valueDeclaration` is the first value declaration found, I don't think you should be changing how other code uses it as a form of convenience for this one case. Otherwise, you'll have to go through each use of valueDeclaration and check how it's being used.

Comment (ahejlsberg) [inline src/compiler/checker.ts]: There's nothing that says `valueDeclaration` has to be the first declaration. In fact, it's not even all that clear what "first one" means and ultimately might depend on the order in which files were specified on the command line. But was is clear is that in cases where a namespace is merged with a function, class, or enum, we always want to treat the combined entity as the non-namespace kind, and the purpose of `valueDeclaration` is (or should be) to be a reference to that "primary" declaration.

Comment (sandersn) [inline src/compiler/checker.ts]: But in the normal case (not the ambient declaration case), classes are required to be before namespaces already. Changing the binder/checker-merge to merge `valueDeclaration` from non-namespaces just makes ambient declarations behave the same way as the normal case, even if the namespace comes first. 

Besides, other uses of `valueDeclaration` very likely also assume that it is not a namespace since namespaces normally come last.

**Comment by danquirk** [comment]
No you shouldn't need to clean before running tests.

**Comment by sandersn** [comment]
ping @ahejlsberg -- how does the new commit look?

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -130,7 +130,10 @@ namespace ts {
                 symbol.members = {};
             }
 
-            if (symbolFlags & SymbolFlags.Value && !symbol.valueDeclaration) {
+            if (symbolFlags & SymbolFlags.Value &&
+                (!symbol.valueDeclaration ||
+                 (symbol.valueDeclaration.kind === SyntaxKind.ModuleDeclaration && node.kind !== SyntaxKind.ModuleDeclaration))) {
```
Comment (DanielRosenwasser) [inline src/compiler/binder.ts]: Could you rewrite this as:

```typescript
const valueDeclaration = symbol.valueDeclaration;
if (valueDeclaration && valueDeclaration.kind !== node.kind && valueDeclaration.kind === SyntaxKind.ModuleDeclaration) {
    // ...
}

Comment (sandersn) [inline src/compiler/binder.ts]: That's a nice rewording. I took the change except for inverting the predicate -- I can't do that without wrapping the whole thing in a `!` or having an empty `if` body and an extra `else`.

**Comment by sandersn** [comment]
@ahejlsberg can you take a look at the updated PR?
