### PR TITLE
Properly handle missingType in intersections

### LINKED ISSUE #46004: Unexpected TS2430 error with exactOptionalPropertyTypes enabled
# Bug Report

### 🔎 Search Terms

- exactOptionalPropertyTypes
- Interface incorrectly extends

### 🕗 Version & Regression Information

- This is a type issue which came with v4.4.2 and `"exactOptionalPropertyTypes": true`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.4.2#code/PTAEBcAsFMITwA7QM6gGYCcD2BbUABHAQ3GgwEsiAbAWgFdzgBjLDaAKHIDtSM0imsAArYEyAGLYcAJWgDwoAN7tQoLFwDCVckwDWAfgBcoABQBKUAF4AfKABuWcgBMA3OwC+7TjzL9BoESwxSVwAWRIySioAVQBJJRU1TW09I1NzK1sHZwsAH1A6LidoNG5oVw8vaAAPBFYFcERYABUYZqaQnHDeKLirANEJKW7I6j6AMgGgodxZeTd2EAgYeCRQblAcOFAEbAAraCZwdhq6jAVuXj9YADkiOwAhLHBwXAAZcmRwWNI8GtIiqhWtB2khOiMKGN4spVKo7NQ6NBjF8KFwAOZuTxAA)

### 💻 Code

```ts
// the types from @material-ui/core
interface PropsFromReact {
  onClick?: () => void;
}

interface PropsFromMaterialUI {
  onClick?: (() => void) | undefined;
}

export type TheTypeFromMaterialUI = PropsFromReact & PropsFromMaterialUI;

// the type from my project
// TS2430: Interface 'NavBottomListItem' incorrectly extends interface 'TheTypeFromMaterialUI'
// Types of property 'onClick' are incompatible.
// Even if I don't extend onClick here
export interface NavBottomListItem extends TheTypeFromMaterialUI {
    value: string;
}
```

### 🙁 Actual behavior

Got error
```
Interface 'NavBottomListItem' incorrectly extends interface 'TheTypeFromMaterialUI'.
  Type 'NavBottomListItem' is not assignable to type 'PropsFromReact'.
    Types of property 'onClick' are incompatible.
      Type '((() => void) & (() => void)) | undefined' is not assignable to type '() => void'.
        Type 'undefined' is not assignable to type '() => void'.
```

### 🙂 Expected behavior

There shouldn't be any error :)

First of all, there shouldn't be an error of incorrect extending, because I don't try to override `onClick` property in `NavBottomListItem`. As I see, the type `TheTypeFromMaterialUI` is calculated to `{ onClick?: () => void; }`, so `| undefined` is just removed from the intersection. This is an understandable behavior, so normally I should be able to extend this type with `{ value: string }`

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #46004.

### CODE REVIEW

File: tests/baselines/reference/strictOptionalProperties1.js [hunk 1]
```diff
@@ -353,103 +377,14 @@ a = e; // Error
...
-declare let tx4: [(string | undefined)?];
-declare function f11<T>(x: {
-    p?: T;
-}): T;
-declare function f12<T>(x: [T?]): T;
-declare function f13<T>(x: Partial<T>): T;
-declare type Undefinable<T> = T | undefined;
-declare function expectNotUndefined<T>(value: Undefinable<T>): T;
-interface Bar {
-    bar?: number;
```
Comment (andrewbranch) [inline tests/baselines/reference/strictOptionalProperties1.js:422]: Why did all this disappear from the declaration emit baseline when you only added to the test? I feel like GitHub must be trolling me or something...

Comment (ahejlsberg) [reply tests/baselines/reference/strictOptionalProperties1.js:422]: Oh, I see, it's because of the `export` specifiers turning the whole file into a module, and therefore *not* exporting all of the other stuff. I'll get rid of those.

File: src/compiler/types.ts [hunk 2]
```diff
@@ -5166,7 +5166,7 @@ namespace ts {
         IncludesMask = Any | Unknown | Primitive | Never | Object | Union | Intersection | NonPrimitive | TemplateLiteral,
         // The following flags are used for different purposes during union and intersection type construction
         /* @internal */
-        IncludesStructuredOrInstantiable = TypeParameter,
```
Comment (DanielRosenwasser) [inline src/compiler/types.ts:5169]: So we don't need this anymore? Was this just never used?

**Review by weswigham — APPROVED** [review]
This should be good once the declaration emit baselines are fixed.

File: src/compiler/types.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/types.ts:5169]: Right, there was code to set the flag, but we never examined it. We must have used it at some point, though I don't recall what for.
