### PR TITLE
Fix check for overwritten properties in object spreads

### LINKED ISSUE #44438: Object spread does not respect optional undefined union when strictOptionalProperties is on
# Bug Report
Another issue elated to #44421. This one seems to be more problematic due to runtime unsoundness.

### 🔎 Search Terms
strict optional properties, object spread, undefined

### 🕗 Version & Regression Information
Nightly, with strictOptionalProperties on

- I was unable to test this on prior versions because strictOptionalProperties is a new option

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210602&ssl=9&ssc=63&pln=1&pc=1&strict=true&strictOptionalProperties=true#code/G4QwTgBCBcEN4wgZwC5gJYDsDmBfCAvPIgOQm4BQokARrAgPyyoY75FyXUQDG9iLLNggAfCAFdMAEwCmAMywyp7YrEmyFmJV3AQp-JsjRDRE6fMXLCqsxsuUqukAEZrCWM4BMAZgA0EADogkHwAelCIGTAwAHswWAAiEATkAAcZHnQFJQgAWziZCBQACxBMCBjMHhlHWlcORC8-QKCaMIj3CExxXJookUE2Wt56myb-IICedsiAD3SeFEjouIgklKQFrPQc-LBCkrKKqpruKVHO8ZaAq3C5haXOwewRbt7+9QstZSA)

### 💻 Code

```ts
var a: {a: string} = {a: ''}
var b: {a?: string} = {}
var c: {a: string | undefined} = {a: undefined}
var d: {a?: string | undefined} = {a: undefined}

var a1 = {a: 123, ...a} // error: "a" specified more than once
var b1 = {a: 123, ...b} // {a: number|string}
var c1 = {a: 123, ...c} // expect error "a" specified more than once
var d1 = {a: 123, ...d} // expect {a: string|number|undefined}

d1.a.toString() // crash! should report error
```

### 🙁 Actual behavior

`c1` created without duplicate property error and `d1` is inferred as `{a: string | number}`

### 🙂 Expected behavior

TS should report error on `c1` and `d1` should be inferred as `{a: string|number|undefined}` to prevent runtime crash.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes two issues:

* Always error when non-optional properties in an object spread overwrite properties to the left. Previously we wouldn't error when the spread type included `undefined`.
* Don't remove an explicitly declared `undefined` from a spread property type in `--exactOptionalPropertyTypes` mode.

Fixes #44438.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -26627,11 +26625,12 @@ namespace ts {
 
         function checkSpreadPropOverrides(type: Type, props: SymbolTable, spread: SpreadAssignment | JsxSpreadAttribute) {
             for (const right of getPropertiesOfType(type)) {
-                const left = props.get(right.escapedName);
-                const rightType = getTypeOfSymbol(right);
-                if (left && !maybeTypeOfKind(rightType, TypeFlags.Nullable) && !(maybeTypeOfKind(rightType, TypeFlags.AnyOrUnknown) && right.flags & SymbolFlags.Optional)) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:26632]: @sandersn I'm not sure why we were checking nullable and any/unknown flags here. Seems to me any non-optional property that duplicates a property to the left should trigger the error.

Comment (sandersn) [reply src/compiler/checker.ts:26632]: I think there was a corner case where a type that included `undefined` was actually for an optional property, but wasn't marked as such. For the others, it might be that `unknown` and (sort of) `any` include `undefined`.

We can ship this in the beta and see if people complain. It's likely that with better optionality tracking, this is not a problem.

**Review by sandersn — APPROVED** [review]
I think it's fine to ship a stricter check to go with the stricter optional properties. If people complain in the beta we can revisit the decision.
