### PR TITLE
`deleteDeclaration`: don't crash on the top node.

### LINKED ISSUE #33726: TypeError: Cannot read property 'kind' of undefined in 'Object.isImportClause' during 'getCodeFixes'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.6.3
**VSCode version**: 1.39.0-insider
**Command requested**: getCodeFixes
**Hitting sessions**: 113
**Five line hash**: c7b31f0235de8b834885fd9d3296b6fc
**Stack**:
```
    at isImportClause (tsserver.js:14387:21)
    at deleteDeclaration (tsserver.js:115707:32)
    at _loop_9 (tsserver.js:115268:47)
    at ChangeTracker.finishDeleteDeclarations (tsserver.js:115275:21)
    at ChangeTracker.getChanges (tsserver.js:115295:22)
    at ChangeTracker.with (tsserver.js:114832:32)
    at getCodeActions (tsserver.js:119846:69)
    at <anonymous> (tsserver.js:115852:121)
    at flatMap (tsserver.js:583:25)
    at getFixes (tsserver.js:115852:23)
    at <anonymous> (tsserver.js:125866:35)
    at flatMap (tsserver.js:583:25)
    at getCodeFixesAtPosition (tsserver.js:125864:23)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at Session.getCodeFixes (tsserver.js:135063:64)
    at _a.<computed> (tsserver.js:133850:61)
    at <anonymous> (tsserver.js:135256:88)
    at Session.executeWithRequestId (tsserver.js:135247:28)
    at Session.executeCommand (tsserver.js:135256:33)
    at Session.onMessage (tsserver.js:135279:35)
    at <anonymous> (tsserver.js:136594:27)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
    at unknown (suppressed.js)
```

### PR DESCRIPTION
**Pull request by elibarzilay**
A misbehaved client can sometimes cause the server to reach
`deleteDeclaration` with the SourceFile, and it will crash due to no
`node.parent`.  I couldn't find a good way to create a test for it, but
I could trigger it manually by having a file with just a `,`, and
sending an explicit `getCodeFixes` command to the server with
`errorCodes: [6133]`.

Do three things to improve this:

1. `textChanges.ts`: if we get here with the root node, delete it
   instead of failing.

2. `fixUnusedIdentifier.ts`: check that we don't `delete` a node that is
   the whole source file, so the error is more focused (should have more
   similar failure stacks).

3. `session.ts`: when there was any failure in `getCodeFixes`, check if
   the input had a diag code that does not appear in the requested text
   range, and throw an error saying that the failure is probably a
   result of a bad request.

Closes #33726 (probably not fixing it, but making it easier to find the cause)

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -1361,7 +1361,10 @@ namespace ts.textChanges {
                     break;
 
                 default:
-                    if (isImportClause(node.parent) && node.parent.name === node) {
+                    if (node.parent === node) {
```
Comment (andrewbranch) [inline src/services/textChanges.ts:1364]: Huh? AFAIK this can never be true. The crash presumably happens when `node.parent` is `undefined`, which means you’re still going to get the same crash on the next `else if`.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
But moreover, we know that this is _not_ from Emacs or fringe editors or general API misuse, because the telemetry comes to us via VS Code. I’m generally not a fan of silencing bugs we don’t understand. I’m not sure this is any better than crashing, because either way, the result is that we don’t generate a codefix. In either case, the user experience is either broken or completely unnoticeable (hard to say which); the only thing this PR does is prevents us from getting telemetry for it anymore.

File: src/services/textChanges.ts (hunk 1 above)
Comment (elibarzilay) [reply src/services/textChanges.ts:1364]: Bah!  Sorry -- this was a debugging leftover that I should have removed.

File: src/server/session.ts [hunk 2]
```diff
@@ -2198,7 +2204,23 @@ namespace ts.server {
...
+            try {
+                codeActions = project.getLanguageService().getCodeFixesAtPosition(file, startPosition, endPosition, args.errorCodes, this.getFormatOptions(file), this.getPreferences(file));
+            }
+            catch(e) {
+                const existingDiagCodes = flatten((["getSyntacticDiagnostics", "getSemanticDiagnostics", "getSuggestionDiagnostics"] as const).map(getter =>
+                    this.getDiagnosticsWorker(args, /*isSemantic*/ getter !== "getSyntacticDiagnostics",
+                                              (project, file) => project.getLanguageService()[getter](file),
+                                              /*includeLinePosition*/ true)
+                        .filter(d => decodedTextSpanIntersectsWith(startPosition, endPosition - startPosition, d.start, d.length))
+                        .map(d => d.code)));
```
Comment (andrewbranch) [inline src/server/session.ts:2217]: It doesn’t seem like `this.getDiagnosticsWorker` is buying you anything (which makes its signature change unnecessary). You don’t use the line position or the formatting work done there. You can just use the diagnostics you get directly from the language service. Also, the inner `filter` and `map` can be replaced with a single `mapDefined` and the outer `flatten` and `map` can be replaced with a single `flatMap`. Alternatively, it may be clearer just to do

```ts
const existingDiagCodes = mapDefined([
  ...languageService.getSyntacticDiagnostics(file),
  ...languageService.getSemanticDiagnostics(file),
  ...languageService.getSuggestionDiagnostics(file)
], d => {
  // ... if intersecting, return code
});

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/server/session.ts (hunk 2 above)
Comment (elibarzilay) [reply src/server/session.ts]: * Re `flatMap` — I missed it, thanks!

* Re using `getDiagnosticsWorker` — it was certainly painful to go through it, but it has a suspicious use of `isDeclarationFileInJSOnlyNonConfiguredProject` which I thought would be good to preserve (not only for whatever it's doing now, but in case more such tweaks are added later on).  If it's fine to use the diagnostics directly, then it's definitely simplifying things.

* Re `definedMap` — I missed that one also, but actually there's no need for that since it's fine to just use an unfiltered `map`...

So the current version uses the diagnostics directly.

File: src/server/session.ts [hunk 3]
```diff
@@ -2198,7 +2198,22 @@ namespace ts.server {
...
+            let codeActions: readonly CodeFixAction[];
+            try {
+                codeActions = project.getLanguageService().getCodeFixesAtPosition(file, startPosition, endPosition, args.errorCodes, this.getFormatOptions(file), this.getPreferences(file));
+            }
+            catch(e) {
+                const ls = project.getLanguageService();
+                const existingDiagCodes =
+                    flatMap(["getSyntacticDiagnostics", "getSemanticDiagnostics", "getSuggestionDiagnostics"] as const,
+                            getter => ls[getter](file))
+                        .map(d => decodedTextSpanIntersectsWith(startPosition, endPosition - startPosition, d.start!, d.length!) && d.code); // TODO: GH#18217
```
Comment (andrewbranch) [inline src/server/session.ts:2210]: Maybe don’t add new `TODO`s

File: src/server/session.ts [hunk 4]
```diff
@@ -2198,7 +2198,22 @@ namespace ts.server {
...
-            const codeActions = project.getLanguageService().getCodeFixesAtPosition(file, startPosition, endPosition, args.errorCodes, this.getFormatOptions(file), this.getPreferences(file));
+            let codeActions: readonly CodeFixAction[];
+            try {
+                codeActions = project.getLanguageService().getCodeFixesAtPosition(file, startPosition, endPosition, args.errorCodes, this.getFormatOptions(file), this.getPreferences(file));
+            }
+            catch(e) {
+                const ls = project.getLanguageService();
+                const existingDiagCodes =
+                    flatMap(["getSyntacticDiagnostics", "getSemanticDiagnostics", "getSuggestionDiagnostics"] as const,
+                            getter => ls[getter](file))
```
Comment (andrewbranch) [inline src/server/session.ts:2209]: I won’t block on code style, but feel I should point out that this indirection is _more characters_ than just spreading the result of three function calls into an array...

```
flatMap(["getSyntacticDiagnostics", "getSemanticDiagnostics", "getSuggestionDiagnostics"] as const, getter => ls[getter](file)).map(...)
[...ls.getSyntacticDiagnostics(file), ...ls.getSemanticDiagnostics(file), ...ls.getSuggestionDiagnostics(file)].map(...)
```

**Review by andrewbranch — APPROVED** [review]

**Comment by janyawat** [comment]
leaves comment

File: src/server/session.ts (hunk 2 above)
Comment (janyawat) [reply src/server/session.ts]: ####- [ ] - _****_@_[]()_

**Comment by janyawat** [comment]
#- [ ] - **_[[@]()]()_**

File: src/server/session.ts (hunk 3 above)
Comment (elibarzilay) [reply src/server/session.ts:2210]: It's used elsewhere in this file, a reference to a catchall issue for getting rid of the `!`s that are used for `.start` and `.length`.  I don't know under what conditions it *can* be undefined, so I thought that its best to use the same comment for whenever this is resolved...

Comment (andrewbranch) [reply src/server/session.ts:2210]: I believe they were auto-inserted by a script when the codebase turned on `--strictNullChecks`. I believe any time you call `get*Diagnostics` with a `file` argument, the results will always have a location. But my suggestion is that we should either be confident about the non-nullness of them, or account for their nullness. (I’m fairly sure we can just be confident about these and delete the TODO.)

Comment (elibarzilay) [reply src/server/session.ts]: I was trying to follow the code to see if it's really always defined, but that was too much; removed the comment given that both of you are sure that it's ok...

File: src/server/session.ts (hunk 4 above)
Comment (elibarzilay) [reply src/server/session.ts]: (Switched this.)
