### PR TITLE
More precise property-overwritten-by-spread errors

### LINKED ISSUE #36779: 3.9 regression: bogus property-will-be-overwritten-by-spread errors
```ts
export class Terror extends Error {
    public get telemetry() {
        return { command: "bye", ok: "next" }
    }
}
function g(u: unknown, b: boolean, t: Terror) {
    return { command: "hi", ...(b ? t.telemetry : {}) }
}
```

**Expected behavior:**

No error; `command` is not necessarily overwritten, for example when `b=false`.

**Actual behavior:**

Error: 'command' is specified more than once, so this usage will be overwritten.

User tests vscode and office-fabric-ui have failures because of this.

### PR DESCRIPTION
**Pull request by sandersn**
Trying to do this check in getSpreadType just doesn't have enough information, so I moved it to checkObjectLiteral, which is a better place for issuing errors anyway.

Unfortunately, the approach is kind of expensive in that it

1. creates a new map for each property and
2. iterates over all properties of the spread type, even if it's a union.

I have some ideas to improve (1) that might work out. I'm not sure how bad (2) is since we're going to iterate over all properties of all
constituents of a union.

Fixes #36779

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22560,6 +22548,7 @@ namespace ts {
             let patternWithComputedProperties = false;
             let hasComputedStringProperty = false;
             let hasComputedNumberProperty = false;
+            const propertyDeclarations = createMap<Symbol>();
```
Comment (weswigham) [inline src/compiler/checker.ts]: `createSymbolTable` or `createUnderscoreEscapedMap` tbh

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
Perf seems OK as-is, so I'm going to skip any fanciness and just change the name and constructor of `propertyDeclarations`.

(I was going to try to spill from propertiesTable to propertyDeclarations, not creating propertyDeclarations in object literals with no spreads. Fancy, but takes more code and harder to read.)
