### PR TITLE
When building projects in watch mode, only schedule projects that need build or need update to bundle

### LINKED ISSUE #48187: [Build Performance] Additional Composite packages add fixed ~250ms watch build overhead
# Bug Report

### 🔎 Search Terms

composite project references watch build slow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link
Unfortunately, there's no playground link for this - but I have an example repo that demonstrates this: https://github.com/berickson1/project-references-demo

### Reproduction Steps
1) Run `yarn watch`
1) Edit and save a change in `core/utilities.ts` to the implementation of `makeRandomName`
1) Observe build time

### 🙁 Actual behavior

Build takes ~5 seconds for a 1 character implementation change
```
yarn watch --diagnostics
yarn run v1.22.17
$ tsc -b --watch --diagnostics
[12:58:11 PM] Starting compilation in watch mode...

[12:58:11 PM] Found 0 errors. Watching for file changes.
[12:58:16 PM] File change detected. Starting incremental compilation...

Files:              42
Lines:           49866
Nodes:          168828
Identifiers:     56933
Symbols:         32193
Types:              89
Instantiations:      1
Memory used:    74267K
I/O read:        0.01s
I/O write:       0.00s
Parse time:      0.35s
Bind time:       0.12s
Check time:      0.01s
Emit time:       0.01s
Total time:      0.49s
[12:58:22 PM] Found 0 errors. Watching for file changes.
```

### 🙂 Expected behavior

Build takes sub-1 seconds

Ran with patch suggestion below:
```
$ tsc -b --watch --diagnostics
[12:57:50 PM] Starting compilation in watch mode...
[12:57:50 PM] Found 0 errors. Watching for file changes.
[12:57:56 PM] File change detected. Starting incremental compilation...

Files:              42
Lines:           49866
Nodes:          168828
Identifiers:     56933
Symbols:         32193
Types:              89
Instantiations:      1
Memory used:    74514K
I/O read:        0.02s
I/O write:       0.00s
Parse time:      0.32s
Bind time:       0.12s
Check time:      0.01s
Emit time:       0.01s
Total time:      0.46s
[12:57:56 PM] Found 0 errors. Watching for file changes.

```

### My analysis
As additional projects are added, there appears to be a linear relationship between project count and incremental build time. A quick pass with a profiler shows long wait breaks of idle time between builds (~230ms long)
Screen Shot 2022-03-09 at 1 02 19 PM

The first call after idle time is `buildNextInvalidatedProject`, which lead me to find [this code](https://github.com/microsoft/TypeScript/blob/main/src/compiler/tsbuildPublic.ts#L1787), which puts spacing between building invalidated composite projects.

### Suggested Change

I was able to significantly shorten this timeout from `250`ms to `10`ms and see much faster build times and no JS output differences.  Upon searching git and PR history, I was able to find the original delay stemmed from filesystem change debouncing, but wasn't able to find any relevant context to the existence of this with respect to `tsc --build` mode. Perhaps @RyanCavanaugh or @sheetalkamat have some additional context. (Apologies if you'd rather me not @ folks in issues).

## Relevant PR history
Original implementation of `tsc -b --watch` that introduces this https://github.com/microsoft/TypeScript/pull/24465/files#diff-d5a1ad96c901f1ead7cb6ad4905b5713720a06dcc4bddb68cd882ef69d43cd2aR580
Extension of the timeout from 100 -> 250ms as a part of refactoring: https://github.com/microsoft/TypeScript/pull/26590/files#diff-d5a1ad96c901f1ead7cb6ad4905b5713720a06dcc4bddb68cd882ef69d43cd2aR807
Light refactoring https://github.com/microsoft/TypeScript/pull/31432/files#diff-d5a1ad96c901f1ead7cb6ad4905b5713720a06dcc4bddb68cd882ef69d43cd2aR1792

### PR DESCRIPTION
**Pull request by sheetalkamat**
Earlier we use to build single project at 250ms and the next project build or project time stamp updates happened after another 250ms. Now only build and update bundle is scheduled with reduced time gap (100ms) and update timestamps happens right after project build
Fixes #48187

### CODE REVIEW

File: tests/baselines/reference/tscWatch/watchEnvironment/watchFile/using-dynamic-priority-polling.js [hunk 1]
```diff
@@ -92,9 +92,9 @@ Input::
 
 Output::
 >> Screen clear
-[[90m12:00:22 AM[0m] File change detected. Starting incremental compilation...
+[[90m12:00:45 AM[0m] File change detected. Starting incremental compilation...
 
-[[90m12:00:26 AM[0m] Found 0 errors. Watching for file changes.
+[[90m12:00:49 AM[0m] Found 0 errors. Watching for file changes.
```
Comment (andrewbranch) [inline tests/baselines/reference/tscWatch/watchEnvironment/watchFile/using-dynamic-priority-polling.js:97]: How are the timestamps in tests generated? Many baselines incremented their timestamps by 1 second but this one appears much later.

Comment (sheetalkamat) [reply tests/baselines/reference/tscWatch/watchEnvironment/watchFile/using-dynamic-priority-polling.js:97]: 24a8affd30c3a117624092caab284449d97dc4a3 i made sure that timeout was reflected in time when we run timeout callbacks.. So that we can see changes when timeout time is reduced as well as number of timeouts set changes

Comment (andrewbranch) [reply tests/baselines/reference/tscWatch/watchEnvironment/watchFile/using-dynamic-priority-polling.js:97]: Oh, so it’s not really meaningful to compare the timestamps changing in _this_ diff, but it will be meaningful in future diffs?

Comment (sheetalkamat) [reply tests/baselines/reference/tscWatch/watchEnvironment/watchFile/using-dynamic-priority-polling.js:97]: If you go one commit at a time you should be able to see the difference.. So it was for this PR as well as for future

**Comment by sheetalkamat** [comment]
@andrewbranch can you please review.. would like to get this in early for 4.8

**Review by andrewbranch — APPROVED** [review]
