### PR TITLE
[Master] Type checking JSX children

### LINKED ISSUE #13618: Suggestion: type checking for JSX children
## Rationale
Props are an important part of a React component's interface, but children can be as well.
In applications it's not uncommon to want to restrict what kind of children a component will
accept. Currently this enforcement has to be done at runtime by throwing errors.

## The Goal
Components can specify allowed children as a union type. Each member would correspond to
the tag, or 'type' field, of the resulting Element. Ideally this could be plucked from
the type of props.children, which would satisfy both component classes and SFCs.

## Motivating Examples:
A modal component may want to make assumptions about its children to satisfy layout
constraints.
```jsx
interface IModalProps {
    children: ModalHeader | ModalBody | ModalFooter;
}

function Modal({ children }: IModalProps) { ... }
function ModalHeader(props) { ... }
function ModalBody(props) { ... }
function ModalFooter(props) { ... }

<Modal>
    <ModalHeader />
    <div /> { /* Desired error: type 'div' does not exist in type 'ModalHeader | ModalBody | ModalFooter' */ }
    <ModalBody />
    <ModalFooter />
</Modal>
```

Similarly...
```jsx
interface IButtonGroupProps {
    children: 'button';
}

function ButtonGroup({ children }: IButtonGroupProps) { ... }

<ButtonGroup>
    <button />
    <button />
    <a href='' /> { /* Desired error: type 'a' is not assignable to type 'button' */ }
</ButtonGroup>
```

An interesting emerging pattern is using JSX as a function call to turn imperative APIs into
declarative ones. Currently these 'render callbacks' can't be type-checked at all. A more complete
summary can be found at http://reactpatterns.com/#render-callback. A further example can be found at https://github.com/ReactTraining/react-media#usage.
```jsx
interface IUser {
    Name: string;
}

interface IFetchUserProps {
    children(user: IUser): any;
}

class FetchUser extends React.Component<IFetchUserProps, any> {
    render() {
        return this.state
            ? this.props.children(this.state.result)
            : null;
    }

    componentDidMount() {
        api.fetchUser().then(result => this.setState({ result }));
    }
}

function UserName() {
    return (
        <FetchUser>
            { user => (
                <h1>{ user.NAme }</h1> // Desired error: property 'NAme' does not exist on type 'IUser'
            ) }
        </FetchUser>
    );
}
```

Lastly, I don't *think* any of this is necessarily specific to React. Other libraries leveraging the JSX
specification for component structure should be able to leverage this as well. The crux of this lies at
the relationship between the type of the 'children' attribute of a given tag and the children actually
passed to it at usage sites.

### PR DESCRIPTION
**Pull request by yuit**
Fix #13618 : type checking children property (for examples and motivation see the original issue) Thanks @joelday  for prototyping the feature!

**Details**

- Look for "props" in JSX.ElementChildrenAttribute if there exist a property inside(by default in react.d.ts it is `children`) that property name will be used as a name of children property. If such property doesn't exist (e.g using older react.d.ts), we will just check all the children but will NOT attach the type as "children" property.

- If there existed children in the body of JSX expression, synthesize symbol presenting those children and add them as part of JSX attributes named `children`. If there already `children` specified as attribute of opening element there will be an error indicating that the attribute will get overwritten.

- When we check each child, we call into `checkExpression` what this mean is that all JSX Expression will have type JSX.Element. In the future, by treating as JSX.Element will allow us to easily extends for  doing these works #13746 or #14729..... 

**Examples**
```ts
interface Prop {
    a: number,
    b: string,
    children: string | JSX.Element
}

function Comp(p: Prop) {
    return <div>{p.b}</div>;
}

// Error: missing children
let k = <Comp a={10} b="hi" />;
// Error: type not match
// For this to work, "children: (string | JSX.Element)[]"
let k1 = <Comp a={10} b="hi">
    <h2>Hello</h2> "hi"
</Comp>

// OK
let k1 = <Comp a={10} b="hi">
    <h2>Hello</h2>
</Comp>
;
```

```ts
interface IUser {
    Name: string;
}

interface IFetchUserProps {
    children: (user: IUser) => JSX.Element;
}

class FetchUser extends React.Component<IFetchUserProps, any> {
    render() {
        return this.state
            ? this.props.children(this.state.result)
            : null;
    }
}

// Error
function UserName() {
    return (
        <FetchUser>
            { user => (
                <h1>{ user.NAme }</h1>   // This is actually an error now; see. tests/baselines/reference/checkJsxChildrenProperty4.errors.txt
            ) }
        </FetchUser>
    );
}
```

Note: with the `<Fetchuser>` example, we can now provide contextual type and give completion as well (see fourslash test)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -424,6 +424,8 @@ namespace ts {
             IntrinsicClassAttributes: "IntrinsicClassAttributes"
         };
 
+        const jsxChildrenPropertyName = "children";
```
Comment (mhegazy) [inline src/compiler/checker.ts]: i would say we should treat this the same way we do with `props` instead of hard coding it.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -8676,8 +8680,9 @@ namespace ts {
             function hasExcessProperties(source: FreshObjectLiteralType, target: Type, reportErrors: boolean): boolean {
                 if (maybeTypeOfKind(target, TypeFlags.Object) && !(getObjectFlags(target) & ObjectFlags.ObjectLiteralPatternWithComputedProperties)) {
                     const isComparingJsxAttributes = !!(source.flags & TypeFlags.JsxAttributes);
+                    const containsSynthesizedJsxChildren = !!(source.flags & TypeFlags.ContainsSynthesizedJsxChildren);
```
Comment (mhegazy) [inline src/compiler/checker.ts]: do not think we need this here

File: src/compiler/diagnosticMessages.json [hunk 3]
```diff
@@ -2099,6 +2099,10 @@
         "category": "Error",
         "code": 2707
     },
+    "props.children are specified twice. The attribute named 'children' will be overwritten.": {
```
Comment (mhegazy) [inline src/compiler/diagnosticMessages.json]: name for `children` should be variable, and i would not include `props` here.

**Comment by yuit** [comment]
ping @RyanCavanaugh  @mhegazy

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -423,6 +423,9 @@ namespace ts {
 
         let _jsxNamespace: string;
         let _jsxFactoryEntity: EntityName;
+        let _jsxElementAttribPropInterfaceSymbol: Symbol;  // JSX.ElementAttributesProperty [symbol]
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: A comment would be good here

Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: (A longer one explaining it, that is)

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -13420,41 +13474,85 @@ namespace ts {
...
+                const jsxElementAttribPropInterfaceType = jsxElementAttribPropInterfaceSym && getDeclaredTypeOfSymbol(jsxElementAttribPropInterfaceSym);
+                // The properties of JSX.ElementAttributesProperty
+                const propertiesOfJsxElementAttribPropInterface = jsxElementAttribPropInterfaceType && getPropertiesOfType(jsxElementAttribPropInterfaceType);
+
+                // if there is a property in JSX.ElementAttributesProperty
+                // i.e.
+                // interface ElementAttributesProperty {
+                //     props: {
+                //         children?: any;
+                //     };
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Let's figure out some other way to do this - this is too opaque and might not combine well with future work

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -13420,41 +13474,85 @@ namespace ts {
...
+                    else {
+                        error(jsxElementAttribPropInterfaceSym.declarations[0], Diagnostics.The_global_type_JSX_0_may_not_have_more_than_one_property, JsxNames.ElementAttributesPropertyNameContainer);
+                        _jsxElementPropertiesName = undefined;
+                    }
+                }
                 else {
-                    error(attribsPropTypeSym.declarations[0], Diagnostics.The_global_type_JSX_0_may_not_have_more_than_one_property, JsxNames.ElementAttributesPropertyNameContainer);
-                    return undefined;
+                    // No interface exists, so the element attributes type will be an implicit any
+                    _jsxElementPropertiesName = undefined;
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Doesn't this mean we'll keep doing this logic repeatedly?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -14574,7 +14672,7 @@ namespace ts {
             //         We can figure that out by resolving attributes property and check number of properties in the resolved type
             // If the call has correct arity, we will then check if the argument type and parameter type is assignable
 
-            const callIsIncomplete = node.attributes.end === node.end;  // If we are missing the close "/>", the call is incomplete
+            const callIsIncomplete = node.attributes.end === node.end;  // If we are missing the close "/>", the call is incoplete
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Undo spelling regression

File: src/compiler/scanner.ts [hunk 8]
```diff
@@ -366,7 +366,7 @@ namespace ts {
         return computeLineAndCharacterOfPosition(getLineStarts(sourceFile), position);
     }
 
-    export function isWhiteSpace(ch: number): boolean {
+    export function isWhiteSpaceLike(ch: number): boolean {
```
Comment (RyanCavanaugh) [inline src/compiler/scanner.ts]: Why the rename?

Comment (yuit) [inline src/compiler/scanner.ts]: Because it is not just WhiteSpace but Whitespace and empty line.

File: src/compiler/checker.ts (hunk 6 above)
Comment (yuit) [inline src/compiler/checker.ts]: Yep if we can't find the JSXElement. May be it is better to be empty string to indicate that we already done this

**Comment by RyanCavanaugh** [comment]
GTG after lint fixes

**Comment by yuit** [comment]
Thanks @RyanCavanaugh  for reviewing 🍰  🍰

**Comment by donaldpipowitch** [comment]
Thank you! This is a great feature.

**Comment by RyanCavanaugh** [comment]
@yuit can you write up some minimal docs? I can fill in some details but would like you to write down the basics

**Comment by radix** [comment]
The issue that this is meant to resolve has examples that restrict the type of the components in children, but I don't see an example in this PR that does that. Is it actually possible?

For example, in the linked issue there is a a use-case where a `Modal` component only allows `ModalHeader`, `ModalBody`, or `ModalFooter` components as children. Is that actually possible with this change?

**Comment by DanielRosenwasser** [comment]
I see you've also been checking on SO: https://stackoverflow.com/questions/44475309/how-do-i-restrict-the-type-of-react-children-in-typescript-using-the-newly-adde

I think that the issue here is that all you really get back from a rendered component is a JSX Element. There's not really any information in thre to specify where the element came from. I'm not sure if @yuit or @RyanCavanaugh have had any thoughts on this.

**Comment by radix** [comment]
yeah, I have become skeptical that what I'm trying to do is possible, which makes me think that #13618 should not have been closed, since it is specifically about getting type restrictions on what kind of components are used as children of a react component. But I could very well be missing something!

**Comment by donaldpipowitch** [comment]
> I think that the issue here is that all you really get back from a rendered component is a JSX Element. There's not really any information in thre to specify where the element came from.

Yeah, this is what I saw in [my tests](https://github.com/donaldpipowitch/typed-react-children-with-typescript), too. You can't say something like this:

```
import React, { Component } from 'react';
import { render } from 'react-dom';

class Foo extends Component<{}, void> {
  render() {
    return <p>Hello from Foo!</p>;
  }
}

interface BarProps {
  children?: Foo | Array<Foo>;
}

const Bar = ({ children }: BarProps) => <div>This must be Foo(s): {children}.</div>;

render(
  <div>
    <Bar>
      <Foo /> {/* invalid - is treated as `Element`*/}
    </Bar>
  </div>,
  document.getElementById('app')
);
```

**Comment by radix** [comment]
If this really can't be done, then I suggest re-opening #13618, since it's specifically about typing the components used as children (should I comment as such there?)

**Comment by Hotell** [comment]
any "last words" on this folks ?

> If this really can't be done, then I suggest re-opening #13618, since it's specifically about typing the components used as children (should I comment as such there?)

cc @yuit  @DanielRosenwasser @RyanCavanaugh  thx!

**Comment by zackify** [comment]
Would love to see support for typing children! 👍
