### PR TITLE
Report error only on local declaration with additional related information

### LINKED ISSUE #49739: Symbol Indexer Don't Work Properly using `--build` (Build Mode)
# Bug Report

### 🔎 Search Terms
  - build
  - `--build`
  - `-b`
  - Symbol
  - not assignable to symbol
  - not assignable
  - property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _symbols_
- I was unable to test this on versions prior to `4.4` because _the `symbol` type didn't exist back then_

### ⏯ Playground Link

_This issue can't be reproduced using the TypeScript Playground._

### 💻 Code

***tsconfig.json***
```json
{
    "compilerOptions": {
        "module": "CommonJS",
        "target": "ES2015"
    },
    "include": [
        "./index.ts"
    ]
}
```

***tsconfig.build.json***
```json
{
    "include": [],
    "references": [
        {
            "path": "."
        }
    ]
}
```

***index.ts***
```ts
class Test extends Array {
  [key: symbol]: string
}
```

Run the following commands:
```
npx tsc -b tsconfig.build.json
```

### 🙁 Actual behavior

Following errors are emitted:
```
node_modules/typescript/lib/lib.es2015.iterable.d.ts:60:5 - error TS2411: Property '[Symbol.iterator]' of type '() => IterableIterator<any>' is not assignable to 'symbol' index type 'string'.

60     [Symbol.iterator](): IterableIterator<T>;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:99:5 - error TS2411: Property '[Symbol.unscopables]' of type '() => { copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: boolean; values: boolean; }' is not assignable to 'symbol' index type 'string'.

 99     [Symbol.unscopables](): {
        ~~~~~~~~~~~~~~~~~~~~~~~~~
100         copyWithin: boolean;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
106         values: boolean;
    ~~~~~~~~~~~~~~~~~~~~~~~~
107     };
    ~~~~~~
```

However, `npx tsc -p .` works, so the TS code has to be correct.

### 🙂 Expected behavior

Just like `npx tsc -p .`, `npx tsc -b tsconfig.build.json` should run through successfully.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #49739

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Looking into  existing failures

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -39387,8 +39388,12 @@ namespace ts {
                 const errorNode = localPropDeclaration || localIndexDeclaration ||
                     (interfaceDeclaration && !some(getBaseTypes(type as InterfaceType), base => !!getPropertyOfObjectType(base, prop.escapedName) && !!getIndexTypeOfType(base, info.keyType)) ? interfaceDeclaration : undefined);
                 if (errorNode && !isTypeAssignableTo(propType, info.type)) {
-                    error(errorNode, Diagnostics.Property_0_of_type_1_is_not_assignable_to_2_index_type_3,
+                    const diagnostic = createError(errorNode, Diagnostics.Property_0_of_type_1_is_not_assignable_to_2_index_type_3,
                         symbolToString(prop), typeToString(propType), typeToString(info.keyType), typeToString(info.type));
+                    if (propDeclaration && errorNode !== propDeclaration) {
+                        addRelatedInfo(diagnostic, createDiagnosticForNode(propDeclaration, Diagnostics._0_is_declared_here, symbolToString(prop)));
+                    }
+                    diagnostics.add(diagnostic);
```
Comment (weswigham) [inline src/compiler/checker.ts:39396]:
```suggestion
                    const diagnostic = error(errorNode, Diagnostics.Property_0_of_type_1_is_not_assignable_to_2_index_type_3,
                        symbolToString(prop), typeToString(propType), typeToString(info.keyType), typeToString(info.type));
                    if (propDeclaration && errorNode !== propDeclaration) {
                        addRelatedInfo(diagnostic, createDiagnosticForNode(propDeclaration, Diagnostics._0_is_declared_here, symbolToString(prop)));
                    }
```
since `error` returns the diagnostic it made.

**Review by weswigham — APPROVED** [review]
