### PR TITLE
Fix duplicate errors in JSDoc function types with anon parameters

### LINKED ISSUE #6993: jsdoc error function as parameter for callback
I have object with function like this
```
db.query({ /* queryParameter */ },function(err,data) {  });
```

So I write jsdoc for pass this object in my function. And it got error

screen shot 2559-02-10 at 2 30 14 pm

Also jsdoc is not support both `@typedef` and `@callback` so I got stuck here

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #6993

### CODE REVIEW

File: tests/cases/fourslash/jsDocFunctionSignatures4.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+///<reference path="fourslash.ts" />
+
+// @allowNonTsExtensions: true
```
Comment (billti) [inline tests/cases/fourslash/jsDocFunctionSignatures4.ts]: `@allowJs: true` works fine too. (I know how much you hate typing :wink:)

**Comment by billti** [comment]
:+1:
