### PR TITLE
Resolve module specifier relative to moduleFile.originalFileName

### LINKED ISSUE #31696: Declaration file has wrong import path for compisite projects
**TypeScript Version:**  3.6.0-dev.20190531, 3.5.1

**Search Terms:** composite projects, declaration files, paths

**Code**

1. Download zip with the project [project.zip](https://github.com/microsoft/TypeScript/files/3241060/project.zip)
1. `npm install`
1. `npm run build`
1. `cat lib/src/sub-project-2/index.d.ts`
1. `cat lib-non-composite/src/sub-project-2/index.d.ts`
1. Compare these files. In my case it's:

**file from composite output (./lib)**:
```ts
declare const variable: {
    key: import("../../lib/src/common/nominal").Nominal<string, "MyNominal">;
};
export declare function getVar(): keyof typeof variable;
export {};
```

**file from non-composite output (./lib-non-composite)**:
```ts
declare const variable: {
    key: import("../common/nominal").Nominal<string, "MyNominal">;
};
export declare function getVar(): keyof typeof variable;
export {};
```

There we have 2 things:
1. Output from build mode (composite project) has invalid import path (`../../lib/src/common/nominal` in `lib/src/sub-project-2/index.d.ts` refers to `root/lib/lib/src/common/nominal`, but this file does not exist - there should be `../../../`, not `../..`). Output from non-composite project has valid path.
1. I don't know why, but the compiler adds `import()` and "inline" declaration instead of importing it from file where it declared for both composite and non-composite projects. Even if it works for non-composite project, it looks strange.

I'm not sure about 2, but the first looks like a bug because it produces invalid typings.

**Related Issues:** #25600

### PR DESCRIPTION
**Pull request by rbuckton**
Prior to this fix we would resolve the module specifier relative to the file name of the referenced project's output file, rather than its input file, possibly resulting in an incorrect path.

Fixes #31696

### CODE REVIEW

File: src/testRunner/unittests/tsbuild/moduleSpecifiers.ts [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        });
+        const sys = new fakes.System(fs, { executingFilePath: "/", newLine: "\n" });
+        const host = new fakes.SolutionBuilderHost(sys);
+        const builder = createSolutionBuilder(host, ["/tsconfig.json"], { dry: false, force: false, verbose: false });
+        builder.build("/tsconfig.json");
+
+        const data = host.vfs.readFileSync("/lib/src/sub-project-2/index.d.ts", "utf8");
+
+        // Prior to fixing GH31696 the import below was `import("../../lib/src/common/nonterminal")`
+        assert.equal(data, `declare const variable: {\n    key: import("../common/nominal").Nominal<string, "MyNominal">;\n};\nexport declare function getVar(): keyof typeof variable;\nexport {};\n`);
```
Comment (sheetalkamat) [inline src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: Instead of this can you baseline the change. Try `verifyTsbuildOutput` You can pass `baselineonly` option

Comment (rbuckton) [reply src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: I wanted to keep this simple. `verifyTsbuildOutput` seemed to do quite a bit more than was strictly necessary to test this.

Comment (rbuckton) [reply src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: It also emits quite a bit of excess information unrelated to what I'm actually trying to verify, since it emits the entire file system diff.

Comment (sheetalkamat) [reply src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: These kind of verification do not perform well when we change our emit. So baselines are better

Comment (rbuckton) [reply src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: I've switched to baselines, but still feel that `verifyTsbuildOutput` was too complex for what I needed to verify.

Comment (sheetalkamat) [reply src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: I disagree. With just `baselineOnly` option it just baselines the build. You can specify only initial build and it will baseline only that in a single file. Its like our compiler test runner that has complexities but does baseline outputs well. Having two types of baselines is just confusing and error prone later if we say want to add what happens in incremental scenario or something like that.

Comment (rbuckton) [reply src/testRunner/unittests/tsbuild/moduleSpecifiers.ts]: I looked into migrating it to `verifyTsbuildOutput` and I'm not convinced. The setup to use that function seems unnecessarily complicated and is undocumented. I'd much rather keep the test simple and switch to `verifyTsbuildOutput` if we ever need any of that added complexity. I can switch to emitting the single file patch using the same path format other tsbuild tests use, but I'd rather keep the test as focused as possible for the time being.
