### PR TITLE
Triple-slash reference type directives can override the import mode used for their resolution

### LINKED ISSUE #47795: Node 12 ESM reports different errors between editor and CLI
_Originally posted by @jaydenseric in https://github.com/microsoft/TypeScript/issues/47792#issuecomment-1032096501_

____

I've been using TypeScript v4.6-dev.x and the `node12` mode extensively for some time now. One of the things that makes it really confusing to work with the new `node12` mode is that often VS Code lies and is able to display types for imports ok within the editor (yes, with the local TypeScript installation selected in VS Code), when really `tsc` via the CLI can't resolve the types. You will see "has no exported member" type errors for the same imports, when the imported package doesn't support TypeScript v4.6 `node12` mode properly with correct package `exports`, `.d.mts` files, etc.

It makes it harder to evaluate as you are working what packages are ESM ready and to experiment with possible fixes for a PR by hacking them in `node_modules`, since you have to ignore what the editor is saying and keep running the `tsc` CLI for feedback.

An example of a package this happens with is `playwright@1.18.1`...

With this `.vscode/settings.json`:

```json
{
  "typescript.disableAutomaticTypeAcquisition": true,
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

And this `jsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "node12",
    "noEmit": true,
    "strict": true
  },
  "typeAcquisition": {
    "enable": false
  }
}
```

And this package `devDependency`:

```json
{
  "typescript": "^4.6.0-dev.20220207"
}
```

And this package `scripts`:

```json
{
  "types": "tsc -p jsconfig.json",
}
```

If you run:

```
npm run types
```

In `a.mjs`:

```js
// @ts-check

/** @typedef {import("playwright").chromium} A */
/** @typedef {import("playwright").Page} B */
```

In `b.mts`:

```ts
import { chromium } from "playwright";
import type { Page } from "playwright";
```

In the VS Code editor the imported `Page` type resolves for intellisense:

Screen Shot 2022-02-08 at 11 12 30 am
Screen Shot 2022-02-08 at 11 12 01 am

But via `tsc`:

Screen Shot 2022-02-08 at 11 13 01 am

The `playwright` package doesn't appear to be in the list of "popular" packages for this issue, but given it's pretty popular and also a Microsoft project that aims to support TypeScript it would really make sense for it to be fully compatible with TypeScript v4.6.

_Originally posted by @jaydenseric in https://github.com/microsoft/TypeScript/issues/47792#issuecomment-1032096501_

### LINKED ISSUE #47806: VS Code/language server doesn't properly detect `NodeNext` module kind based on `package.json`
# Bug Report

### 🔎 Search Terms

- `typescript nodenext errors only reported by tsc`
- `typescript nodenext errors not reported by vs code`

### 🕗 Version & Regression Information

I noticed this in `4.6.0-dev.20220208` and didn't try earlier versions because the `NodeNext` module kind hasn't been included in a stable release yet.

### ⏯ Playground Link

_Can't be reproduced in the Playground._

### 💻 Code

Reproducing the bug doesn't require specific code, but rather a specific TypeScript and VS Code setup, so I created a reproduction repo. Here's what's necessary to reproduce the issue:

- Clone [the repo](https://github.com/shroudedcode/ts-nodenext-issue-repro)
- Install the dependencies
- Open the project in VS Code
- Make VS Code use the workspace TypeScript version (`4.6.0-dev.20220208`)
- Compile the code with `yarn tsc` or `npx tsc`
- Open the `src/index.ts` file in VS Code

### 🙁 Actual behavior

`tsc` tells us about the ESM-specific `Relative import paths need explicit file extensions...` error in `src/index.ts` while VS Code doesn't. This is likely because `tsc` [correctly detects the file's module kind to be `NodeNext` based on the `package.json`](https://www.typescriptlang.org/tsconfig#node12nodenext-nightly-builds) while the language server doesn't for some reason.

### 🙂 Expected behavior

Both `tsc` and VS Code report the error because they both realize that the file is a `NodeNext` module.

### PR DESCRIPTION
**Pull request by weswigham**
They now use the file's default mode by default, rather than always using commonjs. The new arguments to the
reference directive look like:

```ts
///<reference types="pkg" resolution-mode="require" />
```

or

```ts
///<reference types="pkg" resolution-mode="import" />
```

We consider it an error to see these kinds of references outside of `node12` or `nodenext` resolution. This change is separate from the change adding similar configurability for type-only imports (and import types), as the plumbing work to support multi-modal type reference directives is much more extensive (since the API changes to support modality for them was not yet in place), so is probably best reviewed on its own.

Fixes #47795
Fixes #47806

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -3015,28 +3020,34 @@ namespace ts {
                 // store resolved type directive on the file
                 const fileName = toFileNameLowerCase(ref.fileName);
                 setResolvedTypeReferenceDirective(file, fileName, resolvedTypeReferenceDirective);
-                processTypeReferenceDirective(fileName, resolvedTypeReferenceDirective, { kind: FileIncludeKind.TypeReferenceDirective, file: file.path, index, });
+                const mode = ref.resolutionMode || file.impliedNodeFormat;
+                if (mode && getEmitModuleResolutionKind(options) !== ModuleResolutionKind.Node12 && getEmitModuleResolutionKind(options) !== ModuleResolutionKind.NodeNext) {
+                    programDiagnostics.add(createDiagnosticForRange(file, ref, Diagnostics.Resolution_modes_are_only_supported_when_moduleResolution_is_node12_or_nodenext));
```
Comment (andrewbranch) [inline src/compiler/program.ts:3025]: Hm, is this going to be problematic (though silenceable with `--skipLibCheck`) for library code? I guess all library code that’s written with nodenext can potentially present problems for consumers in a different resolution mode, so maybe this is nothing new.

**Review by andrewbranch — COMMENTED** [review]
Re emit: I’m in favor of what you have now, not changing what the user wrote in the directive. Looks good to me at a glance, will take a closer look tomorrow.

**Comment by weswigham** [comment]
> Re emit: I’m in favor of what you have now, not changing what the user wrote in the directive.

As-is, this _always_ emits the appropriate `resolution-mode` in the directive, weather it was originally explicitly written or not.

**Comment by andrewbranch** [comment]
Oh, I misunderstood. Hm, I’ll have to think about that. I think it complicates the library code problem more. If you happen to compile your library in nodenext but resolution would work for consumers under commonjs, it would be a shame to have errors on those references just for including superfluous syntax.

**Comment by andrewbranch** [comment]
I think on principle I lean toward leaving code the user wrote as-is unless there’s a good reason it needs to be changed.

**Comment by weswigham** [comment]
I now omit the `resolution-mode` override if it's unneeded in the resulting file, so they're not *usually* present. While preserving the input formatting where possible sounds nice, to do so needs context about where the original comment came from preserved (so we know when we have to change that formatting), which, since it's derived from a comment, is not the case right now (unlike nodes, which retain pointers back to their original source, `FileReference`s contain no such data and get copied around willy-nilly). It's probably doable, but'd complicate `FileReference`s a bit, since they'd need to somehow inherit their original file's applied resolution mode.

**Comment by weswigham** [comment]
I've mentioned it in some linked issues, but the cache changes in this PR also happen to fix some language service issues to do with format detection caching, and as such this now includes a test to that effect. ♥

**Review by andrewbranch — APPROVED** [review]
Would be good to get another set of eyes since it’s a big changeset, but looks good to me (for merging after 4.6 RC, I assume). Do you know where the bug in the caching code was that you accidentally fixed?

**Comment by weswigham** [comment]
In the `resolutionCache`, the `mode` wasn't consistently handed in by all callers before, which wasn't obvious prior to this PR because triple-slash references intentionally didn't pass a mode.

**Comment by weswigham** [comment]
Specifically, it wasn't being propagated [here](https://github.com/microsoft/TypeScript/pull/47732/files#diff-cb9561c40fa7f1bbefdfa8fa029b8e3d8e07908806ddcb1518f2b69be43e45ceR318).

File: tests/baselines/reference/nodeModulesTripleSlashReferenceModeDeclarationEmit5(module=node12).js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+//// [index.js]
+"use strict";
+Object.defineProperty(exports, "__esModule", { value: true });
+/// <reference types="pkg" resolution-mode="import"/>
+/// <reference types="pkg" resolution-mode="require"/>
+
+
+//// [index.d.ts]
+/// <reference types="pkg" resolution-mode="import"/>
+/// <reference types="pkg" />
```
Comment (sandersn) [inline tests/baselines/reference/nodeModulesTripleSlashReferenceModeDeclarationEmit5(module=node12).js:36]: I'm still a bit bothered by omitting something that people wrote, even if it's redundant. Do we do this elsewhere?

Edit: Oh, it's because of backward compatibility, isn't it -- we don't want to start emitting `resolution-mode="require"` in all d.ts files everywhere.

File: tests/cases/conformance/node/nodeModulesTripleSlashReferenceModeOverride3.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+}
+// @filename: /package.json
+{
+    "private": true,
+    "type": "module"
+}
+// @filename: /index.ts
+/// <reference types="pkg" resolution-mode="require" />
+foo;
+bar; // bar should resolve while foo should not, since even though index.js is esm, the refernce is cjs
```
Comment (sandersn) [inline tests/cases/conformance/node/nodeModulesTripleSlashReferenceModeOverride3.ts:31]:
```suggestion
bar; // bar should resolve while foo should not, since even though index.js is esm, the reference is cjs
```

**Review by sandersn — APPROVED** [review]
I think I basically get what's going on, but I don't think I can predict many of the ramifications. I'd vote that we merge this early enough for people to try it out.

File: tests/cases/fourslash/server/nodeNextModuleKindCaching1.ts [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+
+// @Filename: package.json
+////{
+////    "type": "module",
+////    "private": true
+////}
+
+// @Filename: src/index.ts
+////// The line below should show a "Relative import paths need explicit file
+////// extensions..." error in VS Code, but it doesn't. The error is only picked up
```
[the remark this answers is not in the document]
Comment (weswigham) [reply tests/cases/fourslash/server/nodeNextModuleKindCaching1.ts:23]: Yep - namely weather the services resolution cache actually uses the mode as part of the cache key or not.

File: tests/baselines/reference/nodeModulesTripleSlashReferenceModeDeclarationEmit5(module=node12).js (hunk 2 above)
Comment (weswigham) [reply tests/baselines/reference/nodeModulesTripleSlashReferenceModeDeclarationEmit5(module=node12).js:36]: Yeah, while there are upsides to making `resolution-mode="require"` explicit (being able to move the file between cjs/esm contexts and needing to change less), it's ugly and there are also downsides (it's behavior not changing to match the context it's moved to, as may be expected).
