### PR TITLE
Separate isGlobalCompletion from CompletionKind

### LINKED ISSUE #21790: TypeError: Cannot read property 'getChildren' of undefined in 'Object.findChildOfKind' during 'completions'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: completions
**hitting sessions**: 4208
**proportion of all sessions**: 0.015708936697614168
**five line hash**: ebebd291ec97e3f9774847e65d533f4c
**stack**
```
TypeError: Cannot read property 'getChildren' of undefined
    at Object.findChildOfKind (tsserver.js:64536:25)
    at createCompletionEntry (tsserver.js:66918:70)
    at getCompletionEntriesFromSymbols (tsserver.js:66957:29)
    at completionInfoFromData (tsserver.js:66870:17)
    at Object.getCompletionsAtPosition (tsserver.js:66834:28)
    at Object.getCompletionsAtPosition (tsserver.js:82839:35)
    at IOSession.Session.getCompletions (tsserver.js:89878:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88979:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by andy-ms**
Sequel to #21973 -- since we can have `isGlobalCompletion === false` for global completions, give it a different name `isInSnippetScope` and make unrelated to `CompletionKind`.
May also fix #21790 due to not returning `needsConvertPropertyAccess: true` on `CompletionKind.None`.

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -753,6 +754,7 @@ namespace ts.Completions {
         log("getCompletionData: Is inside comment: " + (timestamp() - start));
 
         let insideJsDocTagTypeExpression = false;
+        let isInSnippetScope = false;
```
Comment (mhegazy) [inline src/services/completions.ts]: should not this default to `true` then? it used to default to `Global` before. we do not want to change the behavior really since we have no test coverage here.

Comment (andy-ms) [reply src/services/completions.ts]: I think this is correct -- we only assigned `completionKind = CompletionKind.Global;` in one place before, and that location is now the only assignment to `isInSnippetScope`.
