### PR TITLE
Skip ambient modules in globalThis

### LINKED ISSUE #48147: Ambient external module name incorrectly appears in `keyof typeof globalThis`
# Bug Report

### 🔎 Search Terms

- `keyof typeof globalThis`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/PTAEFkHsBMFcBsCmpqIMbwIYCdMBcBLSAO1AApQBnAC0gWlGMj1DRLUW1IHN5IAjTPAAq1ApVAB+UAEoAsAChUGHMgC2MBMgBEAM0iRtoAN4BfRSEVWFivAE8ADsl4Chwx8gC8oe08i7QF0ERMUprX2c+YIBpRDtQbwBrOP9AqLcPayC3UIBtPQNtAF0LMAAFbEgnbHtQAHJ9SDqUSEQJJhZEAA9xFhIfD3qI1OyQ8TqAOms2YkoWXQAuNNd4WPjvAsNS0AB5aOtrEFAAcUQWTFAANyFYZF1KtR9qSJWqNidQRRm5wLPj9PgCVAAB5hKBunhEMRoBJRmsAHxkRJLYQyJajdxOXLCIoJeEmRSgImgbBnWBcZbBUTiXKJEoKcwKbh-AFkTbaeQKSw2HnbZl4f6vADuBDwtFgLGZxE4BDQYQU30lLJWACYgUj0QC1jI8QSFMSSWSKRi8nTCcSjhUqpxag0DM1oK12sxwT0fv0IkMPCMAdTKJNFIz+YLgiq2Y0OaUgA)

### 💻 Code

```ts
// Module declaration ( should not concern globalThis ? )
declare module "foo" {}

type globalType = typeof globalThis

type globalKey = keyof globalType

globalThis["foo"]
// Property 'foo' does not exist on type 'typeof globalThis'.

const f: globalKey = "foo"
// OK

// See playground for more examples
```

### 🙁 Actual behavior

"foo" is a valid key/property of `typeof globalThis`

### 🙂 Expected behavior

"foo" should not be a valid key/property of `typeof globalThis` as `globalThis["foo"]` is not valid

### PR DESCRIPTION
**Pull request by sandersn**
Previously, globalThis mistakenly included ambient modules, even though these are not values:

```ts
declare module "ambientModule" {
  export type typ = 1
  export var val: typ
}
type Oops = (typeof globalThis)[\"ambientModule\"]
```

This PR adds ambient modules to the kinds of things that are skipped when constructing `globalThis`' properties, along with block-scoped variables.

Fixes #48147

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11507,7 +11507,7 @@ namespace ts {
                 if (symbol === globalThisSymbol) {
                     const varsOnly = new Map<string, Symbol>() as SymbolTable;
                     members.forEach(p => {
-                        if (!(p.flags & SymbolFlags.BlockScoped)) {
+                        if (!(p.flags & SymbolFlags.BlockScoped) && !(p.flags & SymbolFlags.ValueModule && some(p.declarations, isAmbientModule))) {
```
Comment (gabritto) [inline src/compiler/checker.ts:11510]: some questions: 
- what's this `ValueModule` symbol flag/what is a value module?
- is it precise enough to check if some declaration is an ambient module? what if some of the other declarations are not ambient modules? (that question may be answered by the one above)

File: tests/cases/conformance/es2019/globalThisAmbientModules.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+namespace namespaceModule { export type typ = 1 }
+// should error
+type GlobalBad1 = (typeof globalThis)["\"ambientModule\""]
+type GlobalOk1 = (typeof globalThis)["valueModule"]
+type GlobalOk2 = globalThis.namespaceModule.typ
+const bad1: (typeof globalThis)["\"ambientModule\""] = 'ambientModule'
+
+type GlobalThis = keyof typeof globalThis
+// should error
+const bad2: GlobalThis = 'ambientModule'
```
Comment (gabritto) [inline tests/cases/conformance/es2019/globalThisAmbientModules.ts:15]: I'm not sure I understand what's being tested here, because the use of quotes makes it confusing for me. 
`const bad2: GlobalThis = 'ambientModule'` should error with or without this bug fix, no? Because the ambient module is `"ambientModule"`, with the quotes. Or am I misunderstanding something?

Comment (sandersn) [reply tests/cases/conformance/es2019/globalThisAmbientModules.ts:15]: This was the original test case, which was already confusing. I should probably just leave it out: it turns out that `keyof` turns `"\"foo\""` into just `"foo"`. But it's not relevant to whether `"\"foo\""` should be there in the first place.

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts:11510]: * A value module is a namespace OR `declare module "foo"` with values inside it. A namespace module is a namespace that has only types inside it. (Both kinds of module can contain other namespaces; any nested value turns the parent namespaces into value modules.)
* I think the binder only allows ambient modules to merge with ambient modules? I'll have to check.

Comment (sandersn) [reply src/compiler/checker.ts:11510]: Hm, the excludes are the same as other value modules: `Value & ~(Function | Class  | RegularEnum | ValueModule)`

I'll see if I can name a function, class or enum `"foo"`, but I don't think I can.

Comment (sandersn) [reply src/compiler/checker.ts:11510]: So, effectively only other ambient modules can merge with ambient modules.

Comment (weswigham) [inline src/compiler/checker.ts:11510]: `some`? What if you make a global named `"module"` that ?merges? with the ambient module named `"module"`? (Is such a merge even possible?)

Comment (weswigham) [reply src/compiler/checker.ts:11510]: > I'll see if I can name a function, class or enum "foo", but I don't think I can.

You can if you use a js merge, eg,

```ts
globalThis['"module"'] = function () {}
```

or similar.

Comment (sandersn) [reply src/compiler/checker.ts:11510]: How do you make a global named `"module"`?

**Review by gabritto — APPROVED** [review]
