### PR TITLE
Fix bad line number assertion in `ScriptInfo.positionToLineOffset`

### LINKED ISSUE #44518: TypeScript Server Error (4.3.2): False expression: Expected line to be non-zero
Steps:

1. Create a new TS file with the following contents:

```ts
function foo() {

dsa

}

fo(dsa


    
```

2. Save
3. Select All
4. <kbd>Delete</kbd>

🐛 Lots of spew in devtools:

```
log.js:206   ERR <syntax> TypeScript Server Error (4.3.2)
Debug Failure. False expression: Expected line to be non-zero
Error: Debug Failure. False expression: Expected line to be non-zero
    at failIfInvalidLocation (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:157261:22)
    at ScriptInfo.positionToLineOffset (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:157228:17)
    at toProtocolTextSpan (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165293:35)
    at /home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:164734:68
    at Array.map (<anonymous>)
    at IOSession.Session.toLocationNavigationTree (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:164734:39)
    at IOSession.Session.getNavigationTree (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:164745:32)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:163515:61)
    at /home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165205:88
    at IOSession.Session.executeWithRequestId (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165196:28)
    at IOSession.Session.executeCommand (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165205:33)
    at IOSession.Session.onMessage (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165231:35)
    at Interface.<anonymous> (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23): Error: <syntax> TypeScript Server Error (4.3.2)
Debug Failure. False expression: Expected line to be non-zero
Error: Debug Failure. False expression: Expected line to be non-zero
    at failIfInvalidLocation (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:157261:22)
    at ScriptInfo.positionToLineOffset (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:157228:17)
    at toProtocolTextSpan (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165293:35)
    at /home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:164734:68
    at Array.map (<anonymous>)
    at IOSession.Session.toLocationNavigationTree (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:164734:39)
    at IOSession.Session.getNavigationTree (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:164745:32)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:163515:61)
    at /home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165205:88
    at IOSession.Session.executeWithRequestId (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165196:28)
    at IOSession.Session.executeCommand (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165205:33)
    at IOSession.Session.onMessage (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:165231:35)
    at Interface.<anonymous> (/home/joao/Work/vscode/extensions/node_modules/typescript/lib/tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    at Function.create (/home/joao/Work/vscode/extensions/typescript-language-features/src/tsServer/serverError.ts:17:10)
    at ProcessBasedTsServer.dispatchResponse (/home/joao/Work/vscode/extensions/typescript-language-features/src/tsServer/server.ts:203:43)
    at ProcessBasedTsServer.dispatchMessage (/home/joao/Work/vscode/extensions/typescript-language-features/src/tsServer/server.ts:137:12)
    at /home/joao/Work/vscode/extensions/typescript-language-features/src/tsServer/server.ts:93:9
    at Emitter.fire (/home/joao/Work/vscode/out/vs/base/common/file:/home/joao/Work/vscode/src/vs/base/common/event.ts:634:16)
    at Reader.onLengthData (/home/joao/Work/vscode/extensions/typescript-language-features/src/tsServer/serverProcess.electron.ts:129:18)
    at Socket.<anonymous> (/home/joao/Work/vscode/extensions/typescript-language-features/src/tsServer/serverProcess.electron.ts:100:36)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

recording (2)

### PR DESCRIPTION
**Pull request by elibarzilay**
This is the line number side of ecddf8468f (from #21924, fixing #21818).
But the code is slightly improved for both cases: instead of testing
that `leaf` is defined, check whether `lineCount` is zero, and if it is,
return `〈1,0〉` for the one-based line and zero-based column numbers.
(The requirement of `lineCount > 0` is also seen in the fact
that `lineNumberToInfo` expects a "*One*BasedLine" argument.)

I've stared at this code way too much, since I think that there is
something more fundamentally wrong here.  E.g., `EditWalker` only
`push`es to `startPath` but never pops even a `children`-less node that
is left after deleting the whole contents.  But I can't figure out the
overall structure, which is also why the test that I added is not
great (see the comment there; also, #21924 is dealing with the same
problem and didn't add a test).

Fixes #44518.

Also, fix a random redundantly-nested `if` that I ran into in this file.

### CODE REVIEW

**Comment by elibarzilay** [comment]
@amcasey: I think that this is fine as is given the precedent of #21924, but I'd much rather add some tests and/or some explanations in the file.

File: src/server/scriptVersionCache.ts [hunk 1]
```diff
@@ -684,7 +682,8 @@ namespace ts.server {
 
             // Skipped all children
             const { leaf } = this.lineNumberToInfo(this.lineCount(), 0);
-            return { oneBasedLine: this.lineCount(), zeroBasedColumn: leaf ? leaf.charCount() : 0, lineText: undefined };
+            if (!leaf) return { oneBasedLine: 1, zeroBasedColumn: 0, lineText: undefined };
```
Comment (amcasey) [inline src/server/scriptVersionCache.ts:685]: Why 1 and not 0?  (Asking out of total ignorance, never having seen this code before.)

Comment (elibarzilay) [reply src/server/scriptVersionCache.ts:685]: Since the line number is one-based (hence the `oneBased*` vs `zeroBased*` property names).

File: src/server/scriptVersionCache.ts [hunk 2]
```diff
@@ -684,7 +682,8 @@ namespace ts.server {
 
             // Skipped all children
             const { leaf } = this.lineNumberToInfo(this.lineCount(), 0);
-            return { oneBasedLine: this.lineCount(), zeroBasedColumn: leaf ? leaf.charCount() : 0, lineText: undefined };
+            if (!leaf) return { oneBasedLine: 1, zeroBasedColumn: 0, lineText: undefined };
+            else return { oneBasedLine: this.lineCount(), zeroBasedColumn: leaf.charCount(), lineText: undefined };
```
Comment (amcasey) [inline src/server/scriptVersionCache.ts:686]: Personally, I don't think the `else` improves readability.

File: src/server/scriptVersionCache.ts (hunk 1 above)
Comment (amcasey) [reply src/server/scriptVersionCache.ts:685]: Also, what's in the tree?  I'm guessing it might be a way to reuse data from previous versions of the file?

Comment (amcasey) [reply src/server/scriptVersionCache.ts:685]: It feels like things are already off the rails once `this.lineCount()` is zero, so maybe put a kickout to that effect at the top?  Kind of feels like it's supposed to behave the same as having no children, but maybe that would make `lineNumberAccumulator` zero and cause the same issue?

Comment (elibarzilay) [reply src/server/scriptVersionCache.ts:685]: (Looks like either you posted these comments again, or the GH UI is confused, so I'm resolving this...)

File: src/server/scriptVersionCache.ts (hunk 2 above)
Comment (elibarzilay) [reply src/server/scriptVersionCache.ts]: Yeah, I debated whether to have it or not.  It's gone now.

**Comment by elibarzilay** [comment]
@amcasey: I'm not sure what should be in the tree or what it should represent.  I also guessed that it should never return the 0 line-count, since it should be equivalent to an empty node -- not only is this a vague guess, there seem to be very few tests for all of this, which is why I don't want to add things that might break in unexpected ways.

(Yeah, the GH UI was confusing.)

**Comment by amcasey** [comment]
@elibarzilay But this change already takes a dependency on the relationship between `leaf` and `lineCount`.  It seems like the minimal hack would be `oneBasedLine: this.lineCount() || 1` (or `max`, if you prefer).  In my view, that more transparently hacks around the assert.

Having said that, unless this concretely improves the user experience (and I'm not sure having fewer exceptions in the log counts) or reduces problematic noise in one of our processes, my inclination would be to do nothing until we understand it well enough to make a correct fix (which might be far in the future).

**Comment by elibarzilay** [comment]
Using `max(_, 0)` will resolve it, but will swallow potential bugs that
may return a negative result for whatever reason, therefore `_ || 0` is
better.

And by the same token, the fix here is better than `_ || 0`, since it is
more specific.

**Comment by elibarzilay** [comment]
@amcasey, so after even more quality time spent trying to get a test that works, I figured that the best approach is not to assert the value of `this.lineCount()`, but instead *use it as a test*, since if it's zero then `lineNumberToInfo` will fail to get a leaf, so this is now an improvement over the #21924 fix.  (My best guess is that these editor locations suffer from the common confusion of having a zero line count means that the position is on line 1.)

In any case, I did this improvement and in addition I also added a `Debug.checkDefined` around the leaf expression.

(And BTW, just to be clear, this is the exact same issue that #21924 resolved partially -- see the stack traces of #21818 and #44518: both are coming not from the edit operation itself but from the `getNavigationTree` that happens later.)

The test is not great -- see the comments in the test for that.  But it will still be useful to see if there's a deeper underlying problem here if there's a decision to invest time on that (but I'm more confident now that this is the right fix).

**Review by amcasey — APPROVED** [review]
Thanks!
