### PR TITLE
Limit "type guards as assertions" behavior

### LINKED ISSUE #9246: Incorrect discriminated union narrowing following exhaustive if/else
```ts
type Shape = { kind: "Circle"; radius: number }
           | { kind: "Rectangle"; width: number; height: number }


function area(s: Shape) {
    if (s.kind === "Circle") {
        return s.radius ** 2;
    }
    else if (s.kind === "Rectangle") {
        return s.width * s.height;
    }
    return assertNever(s);
}

function assertNever(x: never): never {
    return x;
}
```

**Expected:** No error
**Actual:** 

```text
test.ts(12,24): error TS2345: Argument of type '{ kind: "Circle"; radius: number; }' is not assignable to parameter of type 'never'.
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With #8548 we introduced the notion of "type guards as assertions". This has caused a steady stream issues as users are surprised by the arguably counter-intuitive effects. With this PR we limit type guards as assertions to only affect incomplete types in control flow analysis of loops. Effectively this makes type guards as assertions an implementation detail of the control flow analyzer that isn't observable in the final types computed by the checker, and #8548 is for all practical purposes revoked.

For example, we now handle the following from #9246 correctly:

```ts
type Shape =
    { kind: "Circle"; radius: number } |
    { kind: "Rectangle"; width: number; height: number };

function area(s: Shape) {
    if (s.kind === "Circle") {
        return Math.PI * s.radius ** 2;
    }
    else if (s.kind === "Rectangle") {
        return s.width * s.height;
    }
    return assertNever(s);  // No error here
}

function assertNever(x: never): never {
    return x;
}
```

Likewise we produce the expected `never` type in this example from #9869:

```ts
let stringOrNumber: string | number = 3 > 5 ? "a" : 7;

if (typeof stringOrNumber === "number") {
    if (typeof stringOrNumber !== "number") {
        stringOrNumber;  // never
    }
}
```

Fixes #9246, #9254, #9260, #9869, #10087. (Yeah, it's been causing some confusion!)

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -1606,6 +1606,16 @@ namespace ts {
         antecedent: FlowNode;
     }
 
+    export type FlowType = Type | IncompleteType;
+
+    // Incomplete types occur during control flow analysis of loops. An IncompleteType
+    // is distinguished from a regular type by a flags value of zero. Incomplete type
+    // objects are internal to the getFlowTypeOfRefecence function and never escape it.
+    export interface IncompleteType {
+        flags: TypeFlags;  // No flags set
```
Comment (weswigham) [inline src/compiler/types.ts]: Since we have numeric literal types and enum literal types now, shouldn't this just be `TypeFlags.None` or `0`? (Which would alleviate the need for the long explanatory comment above.)

Comment (ahejlsberg) [inline src/compiler/types.ts]: `TypeFlags` isn't a union enum type (because it contains non-literal initializers and is intended to be used as bit flags), so there is no `TypeFlags.None` type. I could use `0`, but then it would be less obvious that `flags` is overlaid on the similarly named property in `Type`. Either way, the comment is still necessary.

Comment (weswigham) [inline src/compiler/types.ts]: IDK, I think `0` carries more meaning; since you're using only a sentinel value for the member, encoding the sentinel value in the type seems like a good documentation choice. And `0` should still be assignable to `TypeFlags`, so it should still overlay just fine, right?

**Comment by RyanCavanaugh** [comment]
:+1:
