### PR TITLE
Fix of #58996

### LINKED ISSUE #58996: Filter with "something is smallerType" don't work as negative
### 🔎 Search Terms

filter is type narrow negative

### 🕗 Version & Regression Information

- This starts on version 5.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.2#code/C4TwDgpgBAggdgSwLYEMA2UC8UDeAoKKAIwCcIVgALALimBIFcIAaPAXwG489RIoAlAPYBjANZZcBYmQo0oAM3QBnFuy49w0AMqCkEKgjgBzCfGTooAHwEjR6+QzjDgCQXCgIlZ1GgAUS3X1KQyNaHT0DYwBKWgCI4OMPJVhEH0lCMmAGEnc4oJCAOlJyKnZuYTclYDoIKoBGMMDIk2x8QmLZWnomVjZyyurgWuAAJkb4kIk26RK5RTQVXvUKuCq6YKUASSUAeXFsAG0h+uYaqpGAXQL5BDQhkl9qzAA+JO90R6iorgB6H8IAYQAHoAfhS5jQBwu-VWgw22wA6iQ3C0oEdhnVTsdRlcbncIA8nq8AISed5+YBfX7-QHAsG+clWGxiKJQvBAA

### 💻 Code

```ts
type Animal = {
  breath: true,
};

type Rock = {
  breath: false,
};

type Something = Animal | Rock;

function isAnimal(something: Something): something is Animal {
  return something.breath
}

const test1: Something = {
  breath: true,
}

const test2: Something = {
  breath: false,
};

const thisIsOk = [test1, test2].filter(t => isAnimal(t));
//       ^? Animal[]

const thisIsWrong = [test1, test2].filter(t => !isAnimal(t));
//       ^? (Animal | Rock)[]

```

### 🙁 Actual behavior

```ts

const thisIsOk = [test1, test2].filter(t => isAnimal(t));
//       ^? Animal[]

const thisIsWrong = [test1, test2].filter(t => !isAnimal(t));
//       ^? (Animal | Rock)[]

```

### 🙂 Expected behavior

```ts

const thisIsOk = [test1, test2].filter(t => isAnimal(t));
//       ^? Animal[]

const thisIsShouldBe = [test1, test2].filter(t => !isAnimal(t));
//       ^? Rock[]

```

### Additional information about the issue

Filtering is working only if "positive", but if the "is" is used as a negative then it don't type narrow.

### PR DESCRIPTION
**Pull request by MichalMarsalek**
* [x] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `main` branch
* [x] You've successfully run `hereby runtests` locally
* [x] There are new or updated unit tests validating the change

Fixes #58996
The issue was that the type `Animal & Rock` was not getting reduced to `never` and therefore the check failed.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -38409,7 +38409,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         // "x is T" means that x is T if and only if it returns true. If it returns false then x is not T.
         // This means that if the function is called with an argument of type trueType, there can't be anything left in the `else` branch. It must reduce to `never`.
         const falseCondition = createFlowNode(FlowFlags.FalseCondition, expr, antecedent);
-        const falseSubtype = getFlowTypeOfReference(param.name, initType, trueType, func, falseCondition);
+        const falseSubtype = getReducedType(getFlowTypeOfReference(param.name, initType, trueType, func, falseCondition));
```
Comment (Andarist) [inline src/compiler/checker.ts:38412]: Nice find 👍

**Comment by jakebailey** [comment]
@typescript-bot test it

**Review by jakebailey — APPROVED** [review]
I believe this is correct, yes?

**Comment by jakebailey** [comment]
I think I meant to merge this back when I reviewed it; I can merge main if you'd like.
