### PR TITLE
Fix broken formatting rules around namespaced JSX attributes

### LINKED ISSUE #55293: Unwanted space after the colon of a namespaced JSX attribute
### 🔎 Search Terms

formatting jsx namespaced attribute extra space

### 🕗 Version & Regression Information

- This changed between versions v5.0.x and v5.1.0

### ⏯ Playground Link

https://www.typescriptlang.org/zh/play?#code/MYewdgzgLgBAhjAvDAPAEwJYDcBc8EBmIIMeMARnAE6IBEUAptLTESDpQF50CsLA9AD4A3EA

### 💻 Code

Paste this into a editor (like VSCode), then format it with default foramtter:

```
const a = <div: aa foo : bar="test" foo:baz="5" />;
```

### 🙁 Actual behavior

Outputs

```
const a = <div: aa foo: bar="test" foo: baz="5" />;
```

### 🙂 Expected behavior

Outputs

```
const a = <div:aa foo:bar="test" foo:baz="5" />;
```

### PR DESCRIPTION
**Pull request by lyonbot**
Fixes #55293

Formatting `const a = <div: aa foo : bar="test" foo:baz="5" />;` 

into `const a = <div:aa foo:bar="test" foo:baz="5" />;`

### CODE REVIEW

File: tests/cases/fourslash/formattingJsxTexts4.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+//// const a = <ns: foobar   x : test1   x :test2="string"  x:test3={true?1:0}  />;
+////
+//// return a;
+//// }
+
+format.document();
+
+verify.currentFileContentIs(
+`function foo() {
+    const a = <ns:foobar   x:test1   x:test2="string"  x:test3={true ? 1 : 0} />;
```
Comment (jakebailey) [inline tests/cases/fourslash/formattingJsxTexts4.ts:16]: Is it normal that these extra spaces are left inside this element? I would have guessed they'd be removed. Is there another rule that is missing the info about being able to remove spaces?

**Review by jakebailey — APPROVED** [review]
Seems fine to be but @andrewbranch may know any gotchas.

**Review by andrewbranch — APPROVED** [review]
