### PR TITLE
Fixed an issue with generic naked T not being allowed as async generator's return

### LINKED ISSUE #48966: Async generator functions plus generics cause confusing errors about Awaited on return
# Bug Report

### 🔎 Search Terms

"asyncgenerator"
"async generator awaited"

### 🕗 Version & Regression Information

When checking the Typescript playground, the behaviour exists in 4.5.5 but not 4.4.4 and is still present in Nightly as of 5 May 2022.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7&ts=4.6.2#code/IYZwngdgxgBAZgV2gFwJYHsICobIKYjIA8AKgDQwkBKeyCAThBSQHJ4AeyAfABQCUALhgBBcNADieCHnrBk6eqWY06jZm05cYAbwBQMGAHpDMKJkLx06IcIDuwVPgAmpFQwhaAvDAgIANn4woEEQYPqm5sgwAEbA9ELUtO4w3r4BQSAhYQb0SYwxcboAvrpAA)

### 💻 Code

```ts
async function* test<T, TReturn, TNext>(): AsyncGenerator<T, TReturn, TNext> {
  // const foo: Awaited<TReturn> = null as any // this would one be accepted as the return type in more recent typescript
  const bar: TReturn = null as any // Although this matches TReturn exactly, it is not accepted as a return value
  return bar
}
```

### 🙁 Actual behavior

Typescript rejects a return from an async generator that matches the return type argument from a generic AsyncGenerator, instead expecting an Awaited. This is confusing when creating generic helper methods dealing with generators, and also unexpected as presumably an async generator should be allowed to return both a T and Promise<T>.

### 🙂 Expected behavior

Returning with a value matching the generic return type from AsyncGenerator should be accepted as value.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #48966

Even though I've initially concluded that maybe wrapping is not good enough ([here](https://github.com/microsoft/TypeScript/issues/48966#issuecomment-1120422129))... I think this is actually the way to go here as I've found this pattern is already used in the codebase in a couple of places. Adding more assignability rules when the target type is conditional (which implies that it hasn't been resolved) is probably very hard.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -38905,9 +38905,14 @@ namespace ts {
...
             const isAsync = !!(functionFlags & FunctionFlags.Async);
-            return isGenerator ? getIterationTypeOfGeneratorFunctionReturnType(IterationTypeKind.Return, returnType, isAsync) || errorType :
-                isAsync ? getAwaitedTypeNoAlias(returnType) || errorType :
-                returnType;
+            if (isGenerator) {
+                const returnIterationType = getIterationTypeOfGeneratorFunctionReturnType(IterationTypeKind.Return, returnType, isAsync);
+                if (!returnIterationType) {
+                    return errorType;
+                }
+                return isAsync ? getAwaitedTypeNoAlias(unwrapAwaitedType(returnIterationType)) : returnIterationType;
```
Comment (Andarist) [inline src/compiler/checker.ts:38913]: this is the core of the change: `isAsync` check + `unwrapAwaitedType`, the `getAwaitedTypeNoAlias` here seems to be irrelevant though (tests pass without it). I've found this pattern to be used in the codebase (`getAwaitedTypeNoAlias(unwrapAwaitedType(t))`) so I've decided to use it but we might want to either:
- remove the `getAwaitedTypeNoAlias` call
- figure out a test case that would showcase its relevance here

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Probably not, but let me run a few extra tests.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
