### PR TITLE
Completion fixes

### LINKED ISSUE #2725: Crash when type "..." in empty file
Type ... causes visual studio throws  an error.
get_completion_at_position_after_dotdotdotdot

### PR DESCRIPTION
**Pull request by mhegazy**
Fixes #2725 and #2724

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9412,7 +9412,10 @@ module ts {
             }
             
             if (isArrayLikeType(inputType)) {
-                return getIndexTypeOfType(inputType, IndexKind.Number);
+                let indexType = getIndexTypeOfType(inputType, IndexKind.Number);
+                if (indexType) {
+                    return indexType;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: What were we getting before? `unknownType`?

File: tests/cases/fourslash/completionInIncompleteCallExpression.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+/// <reference path='fourslash.ts'/>
+
+////var array = [1, 2, 4]
+////function a4(x, y, z) { }
+////a4(...<crash>/**/
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionInIncompleteCallExpression.ts]: I don't think `<crash>` was meant to be included in this test.

File: tests/baselines/reference/assignmentLHSIsValue.errors.txt [hunk 3]
```diff
@@ -109,6 +110,8 @@ tests/cases/conformance/expressions/assignmentOperator/assignmentLHSIsValue.ts(7
     
     // array literals
     ['', ''] = value;
+    ~~~~~~~~
+!!! error TS2461: Type 'any' is not an array type.
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/assignmentLHSIsValue.errors.txt]: Weird

1. It should be okay with `any`, you shouldn't get an error from this, should you?
2. That shouldn't even be a valid LHS.

File: tests/cases/fourslash/completionInIncompleteCallExpression.ts (hunk 2 above)
Comment (mhegazy) [inline tests/cases/fourslash/completionInIncompleteCallExpression.ts]: still crashed for me with it :)

File: src/compiler/checker.ts (hunk 1 above)
Comment (mhegazy) [inline src/compiler/checker.ts]: undefined. causing a crash later on.

File: tests/baselines/reference/assignmentLHSIsValue.errors.txt (hunk 3 above)
Comment (mhegazy) [inline tests/baselines/reference/assignmentLHSIsValue.errors.txt]: we already have two others errors after that:
!!! error TS2364: Invalid left-hand side of assignment expression.
 !!! error TS2364: Invalid left-hand side of assignment expression.

Comment (DanielRosenwasser) [inline tests/baselines/reference/assignmentLHSIsValue.errors.txt]: Sorry, it's been a long day.

**Comment by DanielRosenwasser** [comment]
:+1:

File: tests/cases/fourslash/completionInIncompleteCallExpression.ts (hunk 2 above)
Comment (yuit) [inline tests/cases/fourslash/completionInIncompleteCallExpression.ts]: In the issue, it is to indicate that this will be a crash. Though it is still a nice test case to have :)

**Comment by yuit** [comment]
:+1:
