### PR TITLE
Ignore the directories or files in node_modules starting with "." and any file or directory starting with ".git" even in the recursive directory watching logic

### LINKED ISSUE #30004: TSServer high cpu usage
- VSCode Version: 1.31.1
- OS Version: Kubuntu 18.04

Steps to Reproduce:
These steps reproduce under heavy load:
1. Press Control + Space to trigger Intellisense to autocomplete something(Or any action that triggers a request to TSServer)
2. Cancel the request by moving the cursor somewhere else

I've also tested it with both with trace: verbose and off (thinking it might be just me having "typescript.tsserver.trace": "verbose" on TSServer)

TSServer creates an empty file under /tmp/vscode-typescript/tscancellation-*session*.tmp*LastFileNumber*

When files start to pile up, TSServer starts to lag/freeze, have very long delays in responding requests and making VSCode also unresponsive or slow and causing horrible CPU Spikes.

Removing those files restores VScode's speed and TSServer resolves requests under 200ms

Does this issue occur when all extensions are disabled?: Yes/No
Yes

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #30004 and #29782

### CODE REVIEW

File: src/compiler/sys.ts [hunk 1]
```diff
@@ -326,6 +326,9 @@ namespace ts {
                 : FileWatcherEventKind.Changed;
     }
 
+    /*@internal*/
+    export const ignoredPaths = ["/node_modules/.", "/.git"];
```
Comment (weswigham) [inline src/compiler/sys.ts]: Is there a reason we're special casing `.git` and not just ignoring all dotfolders?

Comment (sheetalkamat) [reply src/compiler/sys.ts]: Not sure if anything starting with "." is too aggressive but we definitely have reports about ".git" and hence added that one. We can relax this further later if needed.
