### PR TITLE
Fix import addition location

### LINKED ISSUE #17318: QuickFix adds import below comments which should be attached to declaration
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
/**
 * This is some comment to interface
 */
export interface AuthenticateResponse {
}

// Type this line assuming that there function getRequestInit in the helper.ts
getRequestInit();
```

**Expected behavior:**
```ts
import { getRequestInit } from "./helper";

/**
 * This is some comment to interface
 */
export interface AuthenticateResponse {
}

getRequestInit();
```

**Actual behavior:**
```ts
/**
 * This is some comment to interface
 */
import { getRequestInit } from "./helper";

export interface AuthenticateResponse {
}

getRequestInit();
```
I don't have copyright header in the code and TypeScript insert import before first comment ignoring fact that it is related to declaration which goes immediately after comment.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #17318

We now distinguish between pinned and jsdoc comments (and triple slash references) when looking for the start of the file for this quickfix. Namely, we not assume that jsdoc comments are meant to be after the import unless pinned.

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -284,7 +284,33 @@ namespace ts {
...
+            if (!ranges) return 0;
+            let position = 0;
+            // However we should still skip a pinned comment at the top
+            if (ranges.length && ranges[0].kind === SyntaxKind.MultiLineCommentTrivia && isPinnedComment(text, ranges[0])) {
+                position = ranges[0].end + 1;
+                ranges = ranges.slice(1);
+            }
+            // As well as any triple slash references
+            for (const range of ranges) {
+                if (range.kind === SyntaxKind.SingleLineCommentTrivia && (node as SourceFile).text.substring(range.pos, range.pos + 3) === "///") {
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: I think we have an isDirectiveComment or something

Comment (weswigham) [inline src/compiler/utilities.ts]: I'll search around for it later. I think its private to one of the emitters right now.

**Comment by weswigham** [comment]
@DanielRosenwasser would you update your review status?

**Comment by weswigham** [comment]
@paulvanbrenk It should only skip triple-slash and pinned comments now, but lemme add a test for a file with all 3.

Also, with `isRecognizedTripleSlashComment` now patched to recognize all the semantically meaningful triple slash comments we use, there's also a few changes in our baselines - since prior to this they were (unintentionally) skipped in our JS emit.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -654,6 +680,11 @@ namespace ts {
     export let fullTripleSlashReferencePathRegEx = /^(\/\/\/\s*<reference\s+path\s*=\s*)('|")(.+?)\2.*?\/>/;
     export let fullTripleSlashReferenceTypeReferenceDirectiveRegEx = /^(\/\/\/\s*<reference\s+types\s*=\s*)('|")(.+?)\2.*?\/>/;
     export let fullTripleSlashAMDReferencePathRegEx = /^(\/\/\/\s*<amd-dependency\s+path\s*=\s*)('|")(.+?)\2.*?\/>/;
+    export let defaultLibReferenceRegEx = /^(\/\/\/\s*<reference\s+no-default-lib\s*=\s*)('|")(.+?)\2\s*\/>/;
```
Comment (rbuckton) [inline src/compiler/utilities.ts]: Does this need to be exported?

Comment (weswigham) [inline src/compiler/utilities.ts]: We export the regexes for the rest of our matched triple-slash references, so I would assume so. Our triple-slash recognition functions are also currently all internal, so people need to replicate these regexes themselves if they're trying to emulate our behavior.

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -654,6 +680,11 @@ namespace ts {
     export let fullTripleSlashReferencePathRegEx = /^(\/\/\/\s*<reference\s+path\s*=\s*)('|")(.+?)\2.*?\/>/;
     export let fullTripleSlashReferenceTypeReferenceDirectiveRegEx = /^(\/\/\/\s*<reference\s+types\s*=\s*)('|")(.+?)\2.*?\/>/;
     export let fullTripleSlashAMDReferencePathRegEx = /^(\/\/\/\s*<amd-dependency\s+path\s*=\s*)('|")(.+?)\2.*?\/>/;
+    export let defaultLibReferenceRegEx = /^(\/\/\/\s*<reference\s+no-default-lib\s*=\s*)('|")(.+?)\2\s*\/>/;
+    /**
+     * Copy with new flags via RegExp constructor is ES6+, so this needs to be manually synced with the above
+     */
+    const defaultLibReferenceRegExGIM = /^(\/\/\/\s*<reference\s+no-default-lib\s*=\s*)('|")(.+?)\2\s*\/>/gim;
```
Comment (weswigham) [inline src/compiler/utilities.ts]: Should I use that within `getFileReferenceFromReferencePath`, instead, then? That aligns with the intent, so it seems good.
