### PR TITLE
Use `missingType` in `--noUncheckedIndexedAccess` mode

### LINKED ISSUE #43614: `noUncheckedIndexedAccess` does not narrow properly with `"prop" in obj`
# Bug Report

Apologies if this is a duplicate, but I wasn't able to find anything.

### 🔎 Search Terms

noUncheckedIndexedAccess property in object

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.3.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXy1QDdYspUMAKMPYLbPALngCMccIRyBKZqAZ34gYGfvBqo6DVAG4AUHJTppSdpRwsAVswBKXYHggBPADx6aMYCf4YYhAOYAaeDbup7APg-d4AbznwBMSk5FQARBggNmFB8Bqa3PKBAPTJGAAWCHgILCAQOADu8AU4MADWYgAOMDiVwsYB8KmEJHahlACEHfEA2hFRGGEAuokKgRI28AAe8AC8cVp9kdFDTckutg7wAD7waKCIhCDArMgYLuk4yBAnuRtu9nIAvkA)

### 💻 Code

```ts
declare function invariant(condition: boolean): asserts condition;

function foo(obj: Readonly<Record<string, string>>) {
  invariant(obj && "test" in obj);
  // this one below does narrow to `string`
  // invariant(!!obj["test"]);

  const x = obj["test"] // string | undefined but should be string
}
```

### 🙁 Actual behavior

`x` is typed as `string | undefined`

### 🙂 Expected behavior

`x` should be typed as `string`

### PR DESCRIPTION
**Pull request by ahejlsberg**
This implements what I discuss [here](https://github.com/microsoft/TypeScript/pull/50936#issuecomment-1328262514). I borrwed tests from that PR. Thanks @Andarist.

Fixes #43614.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by Andarist** [comment]
I love it when „in the next day or two” means „in the next half an hour” 😉

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+function f4(obj: Record<string, string>) {
+    obj.test;  // string | undefined
+    if (obj.hasOwnProperty("test")) {
+        obj.test;  // string
+    }
+    else {
+        obj.test;  // undefined
+    }
+}
```
Comment (Andarist) [inline tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: I've hoped that this solution would make it work (somehow through CFA) for at least the `in` variant:
```ts
function f5(obj: Record<string, string>, prop: string) {
    if (obj[prop]) {
        obj[prop]; // actual: string | undefined; expected: string
    }
    if (prop in obj) {
        obj[prop]; // actual: string | undefined; expected: string
    }
}
```

Is this kind of analysis ever supported?

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+function f4(obj: Record<string, string>) {
+    obj.test;  // string | undefined
+    if (obj.hasOwnProperty("test")) {
```
Comment (Andarist) [inline tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:31]: wow, how does this one work if `hasOwnProperty`'s signature is "just":
> hasOwnProperty(v: PropertyKey): boolean;

what kind of sorcery is going on here? :D does this method have some special support in the compiler itself?

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts (hunk 1 above)
Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: `obj[prop]` where `prop` isn’t a hardcoded literal can’t be narrowed in any way to my knowledge.  There are many, many issues attesting to that if you go looking, and it’s considered to be by design.

Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: Everything gets duped to #10530 which is kind of misleading since that issue was originally about bracketed access with a literal key (which has since been fixed), but the picture that develops after enough hunting is that it’s a performance sinkhole.  See e.g. https://github.com/microsoft/TypeScript/issues/25109#issuecomment-398926483

Comment (ahejlsberg) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: @Andarist It works when `prop` is declared as a `const` with a singleton literal type, e.g. `const prop = "foo"`, but no support beyond that. We could conceivably support non-singleton-literal-type const variables, but it isn't trivial.

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts (hunk 2 above)
Comment (ahejlsberg) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:31]: > does this method have some special support in the compiler itself?

It does indeed.

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts (hunk 1 above)
Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: Huh, I wasn’t even aware _that_ worked.

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts (hunk 2 above)
Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:31]: I’m going to assume that feature was implemented early on since nowadays feature requests to special-case built-in methods get rejected if the special case can’t be represented in the method signature.

Comment (Andarist) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:31]: For reference, I found the code related to `hasOwnProperty` [here](https://github.dev/microsoft/TypeScript/blob/f6628a4573cd37c26912f78de3d08cd1dbf687a5/src/compiler/checker.ts#L26781)

File: tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts (hunk 1 above)
Comment (tskj) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: > There are many, many issues attesting to that if you go looking, and it’s considered to be by design.

I understand that this seems difficult to implement and we might never get this feature, but I'm having a hard time understanding how this could be "by design". What I mean is, this seems like fairly straight forward JS and as far as I understand TypeScript's design goals, we really should be able to support (type correctly) this kind of code. I really am sympathetic to the fact that it might not be feasible to do in the current implementation, I'm just challenging the idea that we _want_ it to be this way.

Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: “By design” = ”intentional decision made during the design process”.  Some such decisions are known compromises.  I don’t use the phrase to imply it’s what the *user* wants, because nobody can even define that except for the individual users themselves, and the team can’t go around asking every single user before they’re allowed to label things “working as intended”. :wink:

Comment (tskj) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: Sure there always needs to be compromises made in the design of the language, but this isn't that. This seems to be a limitation of the current implementation (an implementation detail if you will), not some inherent limitation in the design of the language itself.

Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: I mean, the implementation is still part of the design *of the TypeScript compiler* in particular.  Obviously a *language* wouldn't be intentionally designed that way in isolation, but that's a moot point since there's no TypeScript language specification.  There used to be a formal spec a long time ago, but nowadays the implementation is the specification, and that's an entirely pragmatic design process.  If the implementation is designed a certain way, in practice that means the language is too.

Comment (fatcerberus) [reply tests/cases/compiler/inKeywordNarrowingWithNoUncheckedIndexedAccess.ts:37]: ...at least until someone gets fed up with the limitations and makes an alternative implementation. 😅

**Review by gabritto — APPROVED** [review]
