### PR TITLE
Infer contextual types from generic return types

### LINKED ISSUE #5487: Incorrect inferred return type when returning object literal from lambda bound to generic parameter
When passing a function as a generic type T, the compiler correctly infers the return type when passing a previously declared function, but not when the same function is passed as an inline lambda.  This seems to only happens with object literals.  Classes and builtin return types are inferred properly.

``` TypeScript
function wrapper<T>(fn: T): T { return fn };

var fn = function(x: number) { return { x } };

// Correct: type of fnWrapper is (x: number) => { x: number }
var fnWrapper = wrapper(fn);

// Incorrect: type of inlineWrapper is (x: number) => any 
var inlineWrapper = wrapper(function(x: number) { return { x } });
```

### LINKED ISSUE #11152: Use return type as an inference location
From https://github.com/Microsoft/TypeScript/issues/11054

``` ts
interface FolderContentItem{
    type: 'folder' | 'file';
}

let a:FolderContentItem[] = [];
a = [1,2,3,4,5].map(v=>({type:'folder'}))
```

Today this is an error without casting `"folder"` to the literal type. We have a contextual type coming from `a` that is not being used.

### PR DESCRIPTION
**Pull request by ahejlsberg**
When a generic method has one or more type parameters that appear in both parameter and return types and that method is called in a context where a contextual type exists, we now use inferences from the contextual type to the return type to produce contextual types for the argument expressions. Some examples:

```ts
type Box<T> = { value: T };

function box<T>(value: T): Box<T> {
  return { value }
}

let boxed: Box<'win' | 'draw'> = box('draw');  // Ok
```

```ts
let kinds: { kind: 'odd' | 'even' }[];
kinds = [0, 1, 2, 3].map(x => ({ kind: x % 2 ? 'odd' : 'even' }));  // Ok
```

```ts
let p: Promise<{ kind: 'odd' | 'even' }[]>;
p = Promise.all([{ kind: 'even' }, { kind: 'odd' }]);  // Ok
```

Previously, each of the examples above would error because, lacking a contextual type, the literals were widened to type `string`. With this PR, contextual types for the literals in the argument expressions are properly inferred from the intended return types.

Fixes #5487 and #11152 (and numerous duplicate issues).

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -17694,14 +17694,28 @@ namespace ts {
...
+            }
+        }
+
+        // If the given contextual type constains instantiable types and if a mapper representing
+        // return type inferences is available, instantiate those types using that mapper.
+        function instantiateContextualType(contextualType: Type | undefined, node: Expression): Type | undefined {
+            if (contextualType && maybeTypeOfKind(contextualType, TypeFlags.Instantiable)) {
+                const returnMapper = (<InferenceContext>getContextualMapper(node)).returnMapper;
+                if (returnMapper) {
+                    return mapType(contextualType, t => t.flags & TypeFlags.Instantiable ? instantiateType(t, returnMapper) : t);
```
Comment (weswigham) [inline src/compiler/checker.ts]: This `mapType` call should probably have it's third argument set since we're in contextual typing and preserving `string | "x"`'s literaliness is desirable.

Comment (weswigham) [reply src/compiler/checker.ts]: Also: I'm wondering why bother with the map type/instantiate flag check at all - `instantiateType` is only going to instantiate instantiable types anyway.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -22945,7 +22962,9 @@ namespace ts {
             context.contextualMapper = contextualMapper;
             const checkMode = contextualMapper === identityMapper ? CheckMode.SkipContextSensitive :
                 contextualMapper ? CheckMode.Inferential : CheckMode.Contextual;
-            const result = checkExpression(node, checkMode);
+            const type = checkExpression(node, checkMode);
+            const result = maybeTypeOfKind(type, TypeFlags.Literal) && isLiteralOfContextualType(type, instantiateContextualType(contextualType, node)) ?
```
Comment (weswigham) [inline src/compiler/checker.ts]: Why do you need to strip literal freshness here? Minimally that'd deserve a comment, IMO.

File: src/compiler/checker.ts (hunk 1 above)
Comment (jack-williams) [reply src/compiler/checker.ts]: If you change the `mapType` I think you can go ahead and close #29174

Comment (ahejlsberg) [reply src/compiler/checker.ts]: @weswigham Agreed, we should make sure we use `UnionReduction.None`. The reason we don't just call `instantiateType` is that `getContextualMapper` isn't a super cheap operation and also that we don't want to instantiate contained object types as it is unnecessary and can be expensive.

@jack-williams I'll fix it so we don't need #29174.

Comment (jack-williams) [reply src/compiler/checker.ts]: @ahejlsberg Grand, closing the PR. Might be worth adding the example from #29168 to this PR, just to make sure it’s fixed.

**Comment by cyrilletuzi** [comment]
Do we agree it fixes #29168?

As a reminder, #29168 is a **regression**, causing compilation errors. It's already quite difficult for me to understand that regressions are not fixed in the current branch in a project like TypeScript, so I would greatly appreciate that things are managed in a way so it's fixed in TS 3.3. I'm quite worried to see 3.3 planned for January. Time is needed after the PR is merged to check if the issue is solved.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg is this practical to port to the 3.3 branch?

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
@typescript-bot test this again

**Comment by ahejlsberg** [comment]
@RyanCavanaugh There are two new errors in the RWC baselines related to this PR. I have condensed them down to simple repros below.

First error:

```ts
declare function foldLeft<U>(z: U, f: (acc: U, t: boolean) => U): U;
let result: boolean = foldLeft(true, (acc, t) => acc && t);  // Error
```

This errors with `Type 'boolean' is not assignable to type 'true'`. Previously we would infer `boolean` for `U` because there was no contextual type for `z`. We now infer `true` (because the literal is contextually typed by the return type) which then gets fixed as we contextually type the `acc` parameter.

This issue is basically the opposite of the issue we currently have with `foldLeft`-like functions where the seed gets widened because there is no contextual type.

Second error:

```ts
enum State { A, B }
type Foo = { state: State }
declare function bar<T>(f: () => T[]): T[];
let x: Foo[] = bar(() => !!true ? [{ state: State.A }] : [{ state: State.B }]);  // Error
```

This errors with `Type '{ state: State.A; }[] | { state: State.B; }[]' is not assignable to type '{ state: State.A; }[]'`. Previously we'd infer `State` for `state` in each of the object literals. We now infer literal types and because the two array literals have no best common supertype we end up picking the first one.

I'm not sure there's much we can do in the PR to avoid the errors. Any further tweaks to inference are likely just going to produce more noise. I think it comes down to deciding whether we think they're acceptable breaks. I personally think the fixed scenarios outweigh the two new errors. That said, we may want to wait for 3.4, in which case we should revive the fix for #29168.

**Comment by RyanCavanaugh** [comment]
I agree the RWC breaks are acceptable

**Comment by weswigham** [comment]
> I agree the RWC breaks are acceptable

We should have a `Breaking Changes` entry for this ready and have a (general) workaround at the ready to tell people, since I'm sure we'll receive issue reports about this.
