### PR TITLE
fix(40994): Generate 'get' and 'set' accessors refactoring with optional property causes compiler error

### LINKED ISSUE #40994: Generate 'get' and 'set' accessors refactoring with optional property causes compiler error
**TypeScript Version:**  4.0.2

**Search Terms:** generate get, optional property, generate accessors

**Code**
Before:
```ts
class Class {
    [| optionalField?: string; |]
}
```
Apply "Generate 'get' and 'set' accessors" refactoring to `[|` selected range `|]`.
After:
```ts
class Class {
    private _optionalField?: string;
    public get optionalField(): string {
        return this._optionalField;
    }
    public set optionalField(value: string) {
        this._optionalField = value;
    }
}
```
**Actual behavior:**
Compiling with **`strictNullChecks: true`**  gives error TS2322: Type 'string | undefined' is not assignable to type 'string'. Type 'undefined' is not assignable to type 'string'.
Error happens because the getter generated has return type `string` but returns `_optionalField`, and `_optionalField`'s type is actually `string | undefined` because it is optional, which is not assignable to type `string`.

**Expected behavior:**
No type checking errors. Maybe the getter and setter functions should actually have type `string | undefined` instead of `string`?

**Playground Link:** [code before refactoring](https://www.typescriptlang.org/play?ts=4.0.2#code/MYGwhgzhAEDC5WgbwFDXdA9gBwC4EtMA7MEAMXwFMQATAfgC5oJcAnfIgcwG4UBfIA), [code after refactoring](https://www.typescriptlang.org/play?ts=4.0.2#code/MYGwhgzhAEDC5WgbwFDXdADgJwJYDcwAXAU2gH0B7TI3SgOzBADFcSQATAfgC5oIieegHMA3GgyYArgCMQuYNGEki0arQZNW7DgAoAlHwFDhyCRgzYVU7PWhEAFrggA6KjTqMWbTuIsBfcyxZeUUIFTUPTW8dXUIQKRIjQVwRfTMLC0dnN3VPLR8OaABeaHjEvwxA-yA)
**Related Issues:** -

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40994

### CODE REVIEW

File: src/services/codefixes/generateAccessors.ts [hunk 1]
```diff
@@ -251,6 +251,20 @@ namespace ts.codefix {
         });
     }
 
+    function getDeclarationType(declaration: AcceptedDeclaration, program: Program): TypeNode | undefined {
+        const typeNode = getTypeAnnotationNode(declaration);
+        const strictNullChecks = getStrictOptionValue(program.getCompilerOptions(), "strictNullChecks");
+        if (isPropertyDeclaration(declaration) && typeNode && declaration.questionToken && strictNullChecks) {
+            const typeChecker = program.getTypeChecker();
+            const type = typeChecker.getTypeFromTypeNode(typeNode);
+            if (!(type.flags & TypeFlags.AnyOrUnknown || typeChecker.getFalsyFlags(type) & TypeFlags.Undefined)) {
```
Comment (andrewbranch) [inline src/services/codefixes/generateAccessors.ts:260]: `getFalsyFlags()` is a really weird function, and it seems like you only need it for collecting the flags over possible unions... a couple options for doing the same thing without exporting this function:

- `typeChecker.getUnionType([type, typeChecker.getUndefinedType()], UnionReduction.Subtype) === type`
- `typeChecker.isTypeAssignableTo(typeChecker.getUndefinedType(), type)`
- Write a utility that combines _all_ the flags over union types, not the unintuitive mapping that `getFalsyFlags` does (I’m kind of surprised that doesn’t exist)

The first two are less efficient than what you have, but I think they’d be totally acceptable—IMO it’s worth it to keep the use of `getFalsyFlags` very limited.

Comment (a-tarasyuk) [reply src/services/codefixes/generateAccessors.ts]: @andrewbranch Thanks for the detailed feedback 👍🏻.

**Review by andrewbranch — APPROVED** [review]
