### PR TITLE
show completion in destructured parameter if containing function was contextually typed

### LINKED ISSUE #7558: Autocompletion does not work with destructured callback parameters
VS2015

**TypeScript Version:** 

1.8.6

**Code**

```ts
[<Event>null].reduce(({type}, b) => b); // should suggest properties
```

### PR DESCRIPTION
**Pull request by vladima**
Fixes #7558

### CODE REVIEW

**Comment by sandersn** [comment]
:+1:

File: src/services/services.ts [hunk 1]
```diff
@@ -3504,7 +3504,11 @@ namespace ts {
                         // We don't want to complete using the type acquired by the shape
                         // of the binding pattern; we are only interested in types acquired
                         // through type declaration or inference.
-                        if (rootDeclaration.initializer || rootDeclaration.type) {
+                        // Also proceed if rootDeclaration is parameter and if its containing function expression\arrow function is contextually typed -
+                        // type of parameter will flow in from the contextual type of the function
+                        if (rootDeclaration.initializer ||
+                            rootDeclaration.type ||
+                            (rootDeclaration.kind === SyntaxKind.Parameter && isExpression(rootDeclaration.parent) && typeChecker.getContextualType(<Expression>rootDeclaration.parent))) {
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: This isn't correct in the case of object literal methods. This will also break if @sandersn's work goes in to contextually type subclass properties.

Can't you just check if you're in a parameter and you have a contextual type? Why do you need to bring the parent into this?

**Comment by DanielRosenwasser** [comment]
Can you also add a test for an object binding pattern parameter in an object literal method which is contextually typed?

**Comment by mhegazy** [comment]
:+1:

File: src/services/services.ts (hunk 1 above)
Comment (vladima) [inline src/services/services.ts]: object literal properties are handled in the branch above.
The check if parent has contextual type is necessary to make sure that the type that we'll obtain from `getTypeAtLocation` is backed up by something (contextual type of the function) and not just implied by the shape of object binding pattern

Comment (vladima) [inline src/services/services.ts]: discussed offline: need to support cases when completion is requested at position `$`
```ts
interface Foo { m(x: { a: number, b: number }): void }
let x: Foo = {
    m({ $ }) {
    }
};
```

**Comment by vladima** [comment]
@DanielRosenwasser any other somments?

**Comment by DanielRosenwasser** [comment]
:+1:
