### PR TITLE
Remove undefined from optional properties when inferring to index signatures

### LINKED ISSUE #43045: Object spread incorrectly introduces undefined value type in TS 4.2
# Bug Report

This was the one type error I got when I updated my project from TS 4.1 → 4.2. It's a false positive so I figured I'd file an issue in case others run into it as well. I assume this is considered an acceptable loss from [this change](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#relaxed-optional-index-rules) in the release notes, but it is a false positive and regression from 4.1 nonetheless!

### 🔎 Search Terms

- object spread undefined 4.2 

Possibly related to #13195

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.2

### ⏯ Playground Link

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```
</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.2#code/MYewdgzgLgBADgQwE4ILYCYYF4YFkFQAWAdCmACYioAUAlDADwwAMxArDAPwwDkAbggA2AVwCm6HjABcMMMMGCA3AFgAUGtCRYIAEYArbDADeamGfjI0ARhn8hYqzwA0p88XfVEKDF2Ne06AC+0saBtGqBKuqqmtAwAI5iSACehgDy+qLAUMSiYFBIAJaiENS6erTEqAhw1K5m1ADaANZOMHwAuvRYAHwwAAYAJEbNgVjDeaDkogCqAEoAkgDCVHDgeVDUfLSB-fUwAPQH5ienZ+cXJwB++0cwAIJIAObCqBswIABmMFDJcKK8aBFMBPGAAHxgwgook+hTAonIkkKEFkIFgCAgEEKTzACB0ggBUBAFm8oigoiQH2+v3+gIKcNBELkqB0FPBMB0IBABIQYB4xFuxzMABU-gCeFDprD4YiYMjUejMdjcfjCcSaeKgQz2czWZSIZzuaJefzqOgAMwAFjY4VUlT0IDh1B4ADIeLQokA)

### 💻 Code

```ts
const param2 = Math.random() < 0.5 ? 'value2' : null;

const obj = {
    param1: 'value1',
    ...(param2 ? {param2} : {})
};

const query = Object.entries(obj).map(
    ([k, v]) => `${k}=${encodeURIComponent(v)}`
    //                                     ~
    // Argument of type 'string | undefined' is not assignable to parameter of type 'string | number | boolean'.
    //   Type 'undefined' is not assignable to type 'string | number | boolean'.(2345)
).join('&');
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const param2 = Math.random() < 0.5 ? 'value2' : null;
const obj = Object.assign({ param1: 'value1' }, (param2 ? { param2 } : {}));
const query = Object.entries(obj).map(([k, v]) => `${k}=${encodeURIComponent(v)}`
//                                     ~
// Argument of type 'string | undefined' is not assignable to parameter of type 'string | number | boolean'.
//   Type 'undefined' is not assignable to type 'string | number | boolean'.(2345)
).join('&');

```
</details>

### 🙁 Actual behavior

TypeScript says that `v` can be `undefined`, which it cannot. This leads to the type error in the call to `encodeURIComponent`.

### 🙂 Expected behavior

`v` can never be `undefined` at runtime, so the error is a false positive. This was not an error in TypeScript 4.1.

The root cause is that the type of `obj` is inferred as

```ts
const obj: {
    param2?: string | undefined;
    param1: string;
}
```

whereas in TS 4.1 the same inferred type shows up as:

```ts
const obj: {
    param2?: string;
    param1: string;
}
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #43045.

### CODE REVIEW

File: tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+declare const x1: { a: string, b: number };
+declare const x2: { a: string, b: number | undefined };
+declare const x3: { a: string, b?: number };
+declare const x4: { a: string, b?: number | undefined };
+
+let a1 = foo(x1);  // string | number
+let a2 = foo(x2);  // string | number | undefined
+let a3 = foo(x3);  // string | number
+let a4 = foo(x4);  // string | number
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js:12]: Hm - seems like this is the only questionable one.

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Check with @andrewbranch since he made the corresponding change.

File: tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js (hunk 1 above)
Comment (ahejlsberg) [reply tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js:12]: Effectively, because we don't have a separate `missing` type, `undefined` represents the missing state in optional properties, so we really should remove `undefined` when we're inferring to an index signature as index signatures represent the type of those properties that are present.

**Review by RyanCavanaugh — APPROVED** [review]

File: tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js (hunk 1 above)
Comment (RyanCavanaugh) [reply tests/baselines/reference/inferenceOptionalPropertiesToIndexSignatures.js:12]: Feels like things are getting a bit untenable without `missing`; any plausible implementation of `foo` with a legal `x4` could return `undefined`. We should revisit it.

**Review by weswigham — APPROVED** [review]
