### PR TITLE
Fix issue of program not being reused when host implements getSourceFileByPath

### LINKED ISSUE #27207: TS3.0 conditional slow performance with rollup: no program reuse with "redirect" source files
**TypeScript Version:**  3.0.1 through 3.1.0-dev.20180918

This bug does *not* manifest in TypeScript 2.9.2.

**Search Terms:**
Rollup slow performance perf
Program structure reuse
redirectInfo

**Code**

A repo reproducing the problem: https://github.com/AlexLandau/ts3-rollup-perf-bug

Note: This *only* happens when a feature in the TypeScript compiler is triggered that offers special handling for identical source files. In our case, we see this due to particular combinations of dependencies at certain versions.

I originally saw this in a proprietary monorepo where, upon switching from TypeScript 2.9.2 to 3.0.1, individual packages were taking up to 25 minutes (each) to build with [rollup](https://github.com/rollup/rollup) and [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2). After investigating, I believe typescript is the party not working as intended here, rather than rollup or the plugin. I think rollup is just hitting a particular performance regression over and over again, in a way that tsc wouldn't.

**Expected behavior:**
I expect the performance to be similar to that of 2.9.2.

In terms of what I've seen debugging the code: I expect tryReuseStructureFromOldProgram() to indicate that the program can be reused within rollup after it is first initialized.

**Actual behavior:**
In codebases where this is triggered, the performance of rollup is approximately 5-10 times worse than 2.9.2.

I see tryReuseStructureFromOldProgram() always indicating that the program cannot be reused due to [this check](https://github.com/Microsoft/TypeScript/blob/089b86af967ec0dcaa6d8d2ef6576e885605ecc5/src/compiler/program.ts#L1097) looking at the redirectInfo for the source files. At the point of failure, some of the relevant values are:

```
newSourceFile.fileName: /Users/alandau/repos/rollup-ts3-perf-bug/node_modules/@types/uglify-js/node_modules/source-map/source-map.d.ts
oldSourceFile.fileName: /Users/alandau/repos/rollup-ts3-perf-bug/node_modules/@types/webpack/node_modules/source-map/source-map.d.ts
oldSourceFile.redirectInfo.unredirected.fileName: /Users/alandau/repos/rollup-ts3-perf-bug/node_modules/@types/webpack/node_modules/source-map/source-map.d.ts
```

**Playground Link:** N/A

**Related Issues:** 
This PR introduced the redirectInfo construct in play here: https://github.com/Microsoft/TypeScript/pull/16274

### PR DESCRIPTION
**Pull request by sheetalkamat**
This was because redirect file didn't set `resolvedPath` which then would pick from redirected file. So when getting source file, instead of getting if for undirected path, we would end up getting source file for redirected file and then comparing wrong files together.
Fixes #27207

### CODE REVIEW

File: src/testRunner/unittests/reuseProgramStructure.ts [hunk 1]
```diff
@@ -117,55 +117,47 @@ namespace ts {
...
+            getCanonicalFileName,
+            useCaseSensitiveFileNames: () => useCaseSensitiveFileNames,
+            getNewLine: () => sys ? sys.newLine : newLine,
             fileExists: fileName => files.has(fileName),
             readFile: fileName => {
                 const file = files.get(fileName);
                 return file && file.text;
             },
         };
+        if (useGetSourceFileByPath) {
```
Comment (andy-ms) [inline src/testRunner/unittests/reuseProgramStructure.ts]: Might as well calculate `filesByPath` inside the `if`.
