### PR TITLE
fix(38138): Class field initialisation does not show completion list

### LINKED ISSUE #38138: Class field initialisation does not show completion list
**TypeScript Version:**  3.8

**Search Terms:**
field intellisense 

Resolving Edits3

**Expected behavior:**
When I type `private x = un...` I expect a completion list so that I can select `undefined`

**Actual behavior:**
There is no completion list.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200422#code/LAKAxgNghgzjAEAxA9s+BvUp4-mZAdjAC4BOArmMcqQBQCUGWIur8AblKfAB7wC88cgQAmAUwBmASwJiRAbngB6JfGQBrKAE9mrAL67cAB1JTOxMfAmoGTFmxydufQcPHTZC5ao3bsuAxB-HBMzKAt4ACMuASFg+FA9IA)

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/35180

**Backstory**
This has been a problem as long as I can remember. I've been too lazy to report it hoping it will get fixed by someone else.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #38138

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@typescript-bot pack this

File: tests/cases/fourslash/completionsClassPropertiesAssignment.ts [hunk 1]
```diff
@@ -1,29 +1,32 @@
...
 
 const exact = completion.globalsPlus(["Class1", "Class2", "Class3", "prop", "Class4"]);
-verify.completions({ marker: ["1"], exact });
-verify.completions({ marker: ["2"], exact });
-verify.completions({ marker: ["3"], exact });
-verify.completions({ marker: ["4"], exact: ['a', 'b', 'c', 'd'], isGlobalCompletion: false });
-verify.completions({ marker: ["5"], exact });
-verify.completions({ marker: ["6"], exact });
-verify.completions({ marker: ["7"], exact });
+const markers = ["1", "2", "3", "4", "5", "6"];
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionsClassPropertiesAssignment.ts:23]: You can always just use a `for` loop and convert each marker name with `"" + i`
