### PR TITLE
Fix duplicate errors in js special assignments

### LINKED ISSUE #24252: JS Class expression with js-valued return type methods cause duplicated errors
Found in #24247

**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// @ts-check
var A = {};
A.B = {};
A.B.C = [
    {
        o: "no",
        y: 42
    }
];

A.Foo = class {
    /**
     * @returns {?A}
     */
    foo() {
        return A.B.C.find(x => !!x);
    }
}
```

**Expected behavior:**
image

**Actual behavior:**
image
(2 errors instead of 1 - one without elaboration)
In trying to edit this down further, I've found that removing the nested namespace on `B` seems to remove the bug, as does changing the return type of `foo` to not reference `A`, or changing from a class to an object literal for `A.Foo` - so it seems a great deal of things must be kept in place to reproduce this error.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #24252 by not adding a deferred check in getWidenedTypeFromJSSpecialAssignment. This check will be duplicated by the normal checker's walk.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4627,7 +4628,7 @@ namespace ts {
             // function/class/{} assignments are fresh declarations, not property assignments, so only add prototype assignments
             const specialDeclaration = getAssignedJavascriptInitializer(symbol.valueDeclaration);
             if (specialDeclaration) {
-                return getWidenedLiteralType(checkExpressionCached(specialDeclaration));
+                return getWidenedLiteralType(checkExpressionCached(specialDeclaration, CheckMode.NoDeferredCheck));
```
Comment (weswigham) [inline src/compiler/checker.ts]: So. `CheckMode.NoDeferredCheck` isn't falsy. Which means this call to `checkExpressionCached` is really a roundabout call to `checkExpression`.

Comment (sandersn) [reply src/compiler/checker.ts]: Yes, nice catch. Fixed.

Aside: This means that, originally, the second check of the method body must have gone through checkExpression already or it would have gotten the resolved type and avoided it. This leads to an invariant: once you call checkExpressionCached you should only ever call checkExpressionCached afterward, not checkExpression. Or checkExpression should check links.resolvedType before doing any work.

What's more, it's not *in general* safe to check any node twice because of side effects to deferredNodes. Maybe expensive asserts in checkDeferredNodes would actually be worth it...

Later: I added the resolvedType check in checkExpression and the only change it makes to tests is the order that a couple of unions print in. So it might be a worthwhile change &mdash; even better than the current one, in fact.

**Comment by sandersn** [comment]
Reprinting my comment from above, because github attached it to a now-outdated line:

This means that, originally, the second check of the method body must have gone through checkExpression already or it would have gotten the resolved type and avoided it. This leads to an invariant: once you call checkExpressionCached you should only ever call checkExpressionCached afterward, not checkExpression. Or checkExpression should check links.resolvedType before doing any work.

What's more, it's not in general safe to check any node twice because of side effects to deferredNodes. Maybe expensive asserts in checkDeferredNodes would actually be worth it...

Later: I added the resolvedType check in checkExpression and the only change it makes to tests is the order that a couple of unions print in. So it might be a worthwhile change — even better than the current one, in fact.

**Comment by sandersn** [comment]
@weswigham @andy-ms let's talk about this after the standup today since I believe you both have spent more time thinking about deferred nodes than I have.

**Comment by sandersn** [comment]
We decided that nobody tests our test coverage to tell us if using the resolvedType from checkExpressionCached in checkExpression is safe. I'll leave the PR the way it is.

**Comment by sandersn** [comment]
@weswigham @mhegazy User tests are still moving duplicate errors around because of this bug. Mind taking another look?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -598,6 +598,7 @@ namespace ts {
             SkipContextSensitive = 1,  // Skip context sensitive function expressions
             Inferential = 2,           // Inferential typing
             Contextual = 3,            // Normal type checking informed by a contextual type, therefore not cacheable
+            NoDeferredCheck = 4,       // Don't add any nodes for deferred checking
         }
```
Comment (weswigham) [inline src/compiler/checker.ts]: The comment is a little misleading since it only disables deferred checking for class expressions - should probably mention that so someone doesn't come back later and because "it doesn't do what it says it does", "fix" it.

**Comment by sandersn** [comment]
Ah, I had forgotten (and didn't write down) your Map suggestion. I will try it and see how it goes.

I'm not sure it will work in this case, though, because I think there's one deferred check and one in-order check. Switching to Map is worthwhile just for the ability to add a cheap no-dupes assert, though.

**Comment by sandersn** [comment]
Looks like I was wrong -- switching to a map suffices to fix the bug. I'll just do that.
