### PR TITLE
fix export * as default syntax

### LINKED ISSUE #39769: `export * as default from "module"` syntax should work as per ECMA-262
**TypeScript Version:**  4.0.0-beta

**Search Terms:**
ESModule, export star as default, "export * as default from"

**Expected behavior:**
`export * as default from "module"` should export the namespace of "module" as the `default` export.
This is valid ES Module syntax from [this stage-4 proposal. ](https://github.com/tc39/proposal-export-ns-from) See the [test](https://github.com/tc39/test262/blob/e193b449d417c4fb7fc9b6f6b869fd55bca04372/test/language/module-code/export-star-as-dflt.js) in test-262.
I also tested this syntax in Chrome and it was supported.

**Actual behavior:**
You get the following errors:
- "Cannot find name 'from'."
- "Identifier expected. 'default' is a reserved word that cannot be used here."
- "';' expected."

**Code**
```ts
export * as default from "rollup";
```

<details><summary><b>Output</b></summary>

```ts
export * as  from ;
from;
"rollup";

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "Latest",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.staging-typescript.org/play?target=99&ts=4.0.0-beta#code/KYDwDg9gTgLgBAKjgQwM5wCbAGbIK4A282UEAtnAESkEF5iUDcQA)

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #39769

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
**\[\[Do not merge before Friday]]

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -6996,7 +6996,7 @@ namespace ts {
         }
 
         function parseNamespaceExport(pos: number): NamespaceExport {
-            return finishNode(factory.createNamespaceExport(parseIdentifier()), pos);
+            return finishNode(factory.createNamespaceExport(parseIdentifierName()), pos);
```
Comment (sandersn) [inline src/compiler/parser.ts:6999]: what does this change do?

File: src/compiler/transformers/module/module.ts [hunk 2]
```diff
@@ -1051,7 +1051,8 @@ namespace ts {
                                     factory.cloneNode(node.exportClause.name),
```
Comment (sandersn) [inline src/compiler/transformers/module/module.ts:1051]: it would be nice to update the explanatory comment at line 1045

File: src/compiler/parser.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/compiler/parser.ts:6999]: An *IdentifierName* is any valid user-declarable *Identifier* along with any reserved keywords.

Comment (rbuckton) [reply src/compiler/parser.ts:6999]: That's actually backwards: An _Identifier_ is any valid _IdentifierName_ **excluding** reserved keywords:

[Identifier Production](https://tc39.es/ecma262/#prod-Identifier)

Comment (DanielRosenwasser) [reply src/compiler/parser.ts:6999]: tomato / tomat + 0

Comment (DanielRosenwasser) [reply src/compiler/parser.ts:6999]: or maybe

tomato / tomatoo - o

File: src/compiler/transformers/module/module.ts (hunk 2 above)
Comment (Kingwl) [reply src/compiler/transformers/module/module.ts:1052]: Done.

**Comment by Kingwl** [comment]
> **[[Do not merge before Friday]]**

Maybe you need a label `Don't merge now`  :XD
