### PR TITLE
Use full `isReadonlySymbol` check rather than declaration flags

### LINKED ISSUE #47940: #47069 breaks narrowing in @types/has and @types/lodash
```ts
declare function hasOwnProperty<P extends PropertyKey>(target: {}, property: P): target is { [K in P]: unknown };
declare const arrayLikeOrIterable: ArrayLike<any> | Iterable<any>;
if (hasOwnProperty(arrayLikeOrIterable, 'length')) {
    arrayLikeOrIterable; // $ExpectType ArrayLike<any>
}
```

Expected: arrayLikeOrIterable narrows to `ArrayLike<any>`
Actual: It doesn't, so instead the compiler intersects the declared type with `{ length: unknown }`.

Broken by #47069

### PR DESCRIPTION
**Pull request by weswigham**
When comparing property readonly-ness for subtype checks. This fixes comparing a mapped type `readonly` prop (which gets a `Readonly` check flag) with a declared `readonly` prop (which has a `Readonly` modifier flag, but no check flag).

That alone fixes #47940 with the caveat that the type guard should look for a `readonly` field rather than a mutable one (since narrowing is by subtype and not assignability, and `ArrayLike` has a `readonly` length property).

In addition, I also limit the new subtype check to only the `strictSubtypeRelation`, as used by subtype reduction, so as to not change behavior in control flow, and thus fixes #47940 completely.

### CODE REVIEW

**Comment by jakebailey** [comment]
Testing on DT, this does fix the lodash issue, though I'm not sure if the test on the PR is comparable (it's the same as the `has` test in the original issue).

> with the caveat that the type guard should look for a readonly field rather than a mutable one (since narrowing is by subtype and not assignability, and ArrayLike has a readonly length property).

Would you suggest I un-draft (and retitle) this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58979

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19747,9 +19747,10 @@ namespace ts {
                 // This ensures the subtype relationship is ordered, and preventing declaration order
                 // from deciding which type "wins" in union subtype reduction.
                 // They're still assignable to one another, since `readonly` doesn't affect assignability.
+                // This is only applied during the strictSubtypeRelation for compatability's sake in control flow
```
Comment (sandersn) [inline src/compiler/checker.ts:19750]: It would probably be better to include which operations will use this, something like:

```suggestion
                // This is only applied during the strictSubtypeRelation -- currently used in subtype reduction
```

**Comment by weswigham** [comment]
Nah, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58979 shouldn't be needed with this with the change in this PR that limits the check to strict subtype only.

**Comment by jakebailey** [comment]
Thanks, I'll close it.

**Review by sandersn — APPROVED** [review]
Makes sense to me, although I'm not 100% sure how the updated comment should explain it.
