### PR TITLE
fix(53424): in code documentation is not working upon import if function expression reuse function type

### LINKED ISSUE #53424: in code documentation is not working upon import if function expression reuse function type
# Bug Report

### 🔎 Search Terms

documentation not working when function expression reuse function type

### 🕗 Version & Regression Information

tested on 5.0.2 but existed for long time

### ⏯ Playground Link

no playground link because this only happen upon import 

### 💻 Code

structure:
image

package.json
```json
{
  "devDependencies": {
    "typescript": "^5.0.2"
  }
}
```

abc.d.ts
```ts
/**
 * ok
 */
export declare const A: ()=>void

// ===================

export type Z = ()=>void
/**
 * not ok
 */
export declare const B: Z
```

index.ts
```ts
import {A,B} from './abc'

A()

B()
```
### 🙁 Actual behavior

`A` has documentation
image

`B` has no documentation
image

### 🙂 Expected behavior

Both `A` and `B` in code documentation should work

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #53424

### CODE REVIEW

File: src/services/symbolDisplay.ts [hunk 1]
```diff
@@ -836,6 +837,14 @@ export function getSymbolDisplayPartsDocumentationAndSymbolKind(typeChecker: Typ
             tags = allSignatures[0].getJsDocTags().filter(tag => tag.name !== "deprecated"); // should only include @deprecated JSDoc tag on the first overload (#49368)
         }
 
+        if (symbolFlags & SymbolFlags.Alias && documentation.length === 0 && tags.length === 0) {
```
Comment (sandersn) [inline src/services/symbolDisplay.ts:840]: I think it would be better to put this code inside the existing `if (symbolFlags & SymbolFlags.Alias)` block around line 536. It already sets documentationFromAlias/tagsFromAlias under other conditions, so it would be a good idea to make sure they all work together.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/services/symbolDisplay.ts (hunk 1 above)
Comment (sandersn) [reply src/services/symbolDisplay.ts:840]: What I ended up with was:

```ts
    if (symbol.flags & SymbolFlags.Alias) {
        prefixNextMeaning();
        const noDocumentation = documentation.length === 0 && tags.length === 0
        if (!hasAddedSymbolInfo || noDocumentation) {
            const resolvedSymbol = typeChecker.getAliasedSymbol(symbol);
            if (resolvedSymbol !== symbol && resolvedSymbol.declarations && resolvedSymbol.declarations.length > 0) {
                const resolvedNode = resolvedSymbol.declarations[0];
                const declarationName = getNameOfDeclaration(resolvedNode);
                if (noDocumentation) {
                    documentationFromAlias = resolvedSymbol.getContextualDocumentationComment(resolvedNode, typeChecker);
                    tagsFromAlias = resolvedSymbol.getJsDocTags(typeChecker);
                }
                else if (declarationName) {
```

from what was formerly

```ts
    if (symbol.flags & SymbolFlags.Alias) {
        prefixNextMeaning();
        if (!hasAddedSymbolInfo || noDocumentation) {
            const resolvedSymbol = typeChecker.getAliasedSymbol(symbol);
            if (resolvedSymbol !== symbol && resolvedSymbol.declarations && resolvedSymbol.declarations.length > 0) {
                const resolvedNode = resolvedSymbol.declarations[0];
                const declarationName = getNameOfDeclaration(resolvedNode);
                if (declarationName) {
```

**Review by sandersn — APPROVED** [review]
