### PR TITLE
Check return code paths on getters

### LINKED ISSUE #9671: Getters are not undefined checked on nullables
Below should give me an error:

```ts
class A {
   a(): string | null {
        if (Math.random() > 0.5) {
            return '';
        }

        // it does error here as expected
    }
}
class A {
    get a(): string | null {
        if (Math.random() > 0.5) {
            return '';
        }

        // it should error here because it returns undefined
    }
}
```

```shell
tsc -v
Version 2.1.0-dev.20160713
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #9671. I reuse `checkAllCodePathsInNonVoidFunctionReturnOrThrow` and remove a redundant check from `checkAccessorDeclaration`, however I can't quite seem to easily merge this block:
```ts
                // TODO (weswig): Consolidate the below into checkAllCodePathsInNonVoidFunctionReturnOrThrow
                if (node.kind === SyntaxKind.GetAccessor) {
                    if (!isInAmbientContext(node) && nodeIsPresent(node.body) && (node.flags & NodeFlags.HasImplicitReturn)) {
                        if (!(node.flags & NodeFlags.HasExplicitReturn)) {
                            error(node.name, Diagnostics.A_get_accessor_must_return_a_value);
                        }
                    }
                }
```
into `checkAllCodePathsInNonVoidFunctionReturnOrThrow` (likely because this error is getter-specific - it's perfectly valid to have a function which never returns, while a getter must always return in at least one branch, apparently.)

cc: @RyanCavanaugh

### CODE REVIEW

**Comment by weswigham** [comment]
Ping @ahejlsberg

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13916,14 +13916,10 @@ namespace ts {
 
                 checkDecorators(node);
                 checkSignatureDeclaration(node);
+                // TODO (weswig): Consolidate the below into checkAllCodePathsInNonVoidFunctionReturnOrThrow
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Does this imply there's more work to do?

Comment (weswigham) [inline src/compiler/checker.ts]: Mmmm... Maybe. I wanted a second opinion on that. The remaining code below
is getter-specific, so I'm unsure of weather or not it should be merged
into checkAllCodePathsInNonVoidFunction.

Comment (ahejlsberg) [inline src/compiler/checker.ts]: Looks like the remaining code is just cherry picking the case where the accessor has an implicit return and no explicit returns. Not sure why that case needs special treatmeant if it is already handled in the checkAllCodePathsEtcEtc function. What happens to the baselines if you remove it?

Comment (weswigham) [inline src/compiler/checker.ts]: The `checkAllCodePathsInNonVoidFunction` actually doesn't handle that case, because for a normal function it is allowed. Removing the below block literally just removes that error (that a `get` accessor must contain an explicit return value) from every baseline.

**Comment by weswigham** [comment]
@ahejlsberg I've decided to just remove the TODO and leave the block as-is rather than try and factor it into the other method. Is this fix :+1: 'able?

**Comment by mhegazy** [comment]
👍
