### PR TITLE
Fixes var declaration shadowing in async functions

### LINKED ISSUE #20461: Async function __awaiter allows var declarations to clobber function parameters
**TypeScript Version:**  2.6.2, 2.7.0-dev.20171203, target: es2015

**Code**

```ts
async function test(url) {
    console.log(url);
}
async function fn(url) {
    await test(url);
    var url;
}

fn("test");
```

**Expected behavior:**
"test" should be logged

**Actual behavior:**
undefined is logged

The generated code clobbers the var declaration in the outer function, by adding another function around the code:
```js
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
function test(url) {
    return __awaiter(this, void 0, void 0, function* () {
        console.log(url);
    });
}
function fn(url) {
    return __awaiter(this, void 0, void 0, function* () {
        yield test(url);
        var url;
    });
}
fn("test");
```

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes an issue where the downlevel emit for async functions to ES2015 can result in incorrect runtime semantics when the async function body contains a `var` declaration that shadows a parameter name.

Fixes #20461

### CODE REVIEW

File: src/compiler/transformers/es2017.ts [hunk 1]
```diff
@@ -83,6 +85,103 @@ namespace ts {
             }
         }
 
+        function asyncBodyVisitor(node: Node): VisitResult<Node> {
```
Comment (weswigham) [inline src/compiler/transformers/es2017.ts]: Is there a canonical source we can reference in a comment here for the list-of-things-which-may-contain-or-whose-children-may-contain-hoisted-declarations? It seems nonobvious which elements of [the statement and declaration list](https://tc39.github.io/ecma262/#sec-ecmascript-language-statements-and-declarations) need to be explicitly visited here.

Also: Does `LabeledStatement` need to be handled? eg `foo: {
  var a;
}`

File: src/compiler/transformers/es2017.ts [hunk 2]
```diff
@@ -83,6 +85,103 @@ namespace ts {
...
+                    return visitEachChild(node, asyncBodyVisitor, context);
+                case SyntaxKind.CatchClause:
+                    return visitCatchClauseInAsyncBody(<CatchClause>node);
+            }
+            return visitor(node);
+        }
+
+        function visitCatchClauseInAsyncBody(node: CatchClause) {
+            const catchClauseNames = createUnderscoreEscapedMap<true>();
+            recordDeclarationName(node.variableDeclaration, catchClauseNames);
```
Comment (ajafff) [inline src/compiler/transformers/es2017.ts]: variableDeclaration may be undefined

File: src/compiler/transformers/es2017.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/es2017.ts]: Good catch

File: src/compiler/transformers/es2017.ts (hunk 2 above)
Comment (rbuckton) [reply src/compiler/transformers/es2017.ts]: Actually, by the time we get to the `es2017` transform a `CatchClause` **must** have a catch variable, otherwise it's not valid ES2017. Assigning the catch variable is handled in the `esnext` transform before the `es2017` transform is run.

Comment (rbuckton) [reply src/compiler/transformers/es2017.ts]: I've added a test case in e655446 to verify this case.

File: src/compiler/transformers/es2017.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/es2017.ts]: I've added `isNodeWithPossibleVarDeclaration` in 2ba29d8 as a way to verify this list.

File: src/compiler/transformers/es2017.ts [hunk 3]
```diff
@@ -83,6 +85,105 @@ namespace ts {
...
+                case SyntaxKind.DefaultClause:
+                case SyntaxKind.TryStatement:
+                case SyntaxKind.DoStatement:
+                case SyntaxKind.WhileStatement:
+                case SyntaxKind.IfStatement:
+                case SyntaxKind.WithStatement:
+                case SyntaxKind.LabeledStatement:
+                    return visitEachChild(node, asyncBodyVisitor, context);
+            }
+            Debug.assert(!isNodeWithPossibleVarDeclaration(node), "Unhandled node.");
```
Comment (weswigham) [inline src/compiler/transformers/es2017.ts]: Why not make `isNodeWithPossibleVarDeclaration` into a type guard, start the function with it, the end with an `assertNever` to get the type checker to help out here?: 
```ts
if(!isNodeWithPossibleVarDeclaration(node)) {
  return visitor(node);
}
// ... switch block
Debug.assertNever(node, "Unhandled node.");
```
