### PR TITLE
Fix for __decorate emit on undecorated file following a decorated file

### LINKED ISSUE #2690: Importing files containing decorator invocations emits unnecessary __decorate helper
tsc 1.5.0-alpha emits an unnecessary `__decorate` helper when importing files which use decorators.

`decorated.ts`

```js
function decorate () { }

@decorate
export default class Decorated { }
```

`un-decorated.ts`

```js
import Decorated from 'decorated';
```

`tsc *.ts --target ES6` emits:

`un-decorated.js`

```js
var __decorate = this.__decorate || function (decorators, target, key, value) {
    var kind = typeof (arguments.length == 2 ? value = target : value);
    for (var i = decorators.length - 1; i >= 0; --i) {
        var decorator = decorators[i];
        switch (kind) {
            case "function": value = decorator(value) || value; break;
            case "number": decorator(target, key, value); break;
            case "undefined": decorator(target, key); break;
            case "object": value = decorator(target, key, value) || value; break;
        }
    }
    return value;
};
```

If I understand correctly it should only be necessary to add `__decorate` to files which use decorators directly.

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #2690

### CODE REVIEW

File: tests/cases/conformance/decorators/class/decoratedClassFromExternalModule.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+// @target: es6
```
Comment (mhegazy) [inline tests/cases/conformance/decorators/class/decoratedClassFromExternalModule.ts]: looks like you are missing the baselines

Comment (rbuckton) [inline tests/cases/conformance/decorators/class/decoratedClassFromExternalModule.ts]: Added in https://github.com/Microsoft/TypeScript/commit/d87e80b65b75eecbcd0e08a85b8a25abb28cae7a

**Comment by mhegazy** [comment]
:+1:
