### PR TITLE
Make `getSourceFileToImportFromResolved` prefer files in `program.getSourceFiles()`

### LINKED ISSUE #30550: Imports updated incorrectly for imported js file with extension
Steps to Reproduce:
```js
// app.js
const lib = require('./lib.js');
// lib.js
module.exports = 1;
```
Now rename `lib.js` to `myLib.js`:
```js
// app.js
const lib = require('./lib.js/index.js'); // => Expected: './myLib.js'
// myLib.js
module.exports = 1;
```
Now rename `myLib.js` to `myMyLib.js`:
```js
// app.js
const lib = require('./lib.js/index.js.js'); // => Expected: './myMyLib.js'
// myMyLib.js
module.exports = 1;
```
**This misbehavior appeared when I updated to 1.31.1
This misbehavior didn't exist in 1.30.2**

Thanks for your time, appreciate your work!

### PR DESCRIPTION
**Pull request by elibarzilay**
Fixes #30550

### CODE REVIEW

File: src/services/getEditsForFileRename.ts [hunk 1]
```diff
@@ -151,7 +151,8 @@ namespace ts {
                     const toImport = oldFromNew !== undefined
                         // If we're at the new location (file was already renamed), need to redo module resolution starting from the old location.
                         // TODO:GH#18217
-                        ? getSourceFileToImportFromResolved(resolveModuleName(importLiteral.text, oldImportFromPath, program.getCompilerOptions(), host as ModuleResolutionHost), oldToNew)
+                        ? getSourceFileToImportFromResolved(resolveModuleName(importLiteral.text, oldImportFromPath, program.getCompilerOptions(), host as ModuleResolutionHost),
```
Comment (sheetalkamat) [inline src/services/getEditsForFileRename.ts]: instead of passing array of paths pass in files themselves so that we don't need to allocate array everytime. 
You can use `find or contains` instead on array to do the search

File: src/services/getEditsForFileRename.ts [hunk 2]
```diff
@@ -207,13 +208,20 @@ namespace ts {
...
+            // Then failed lookups except package.json since we dont want to touch them (only included ts/js files)
+            || forEach(resolved.failedLookupLocations, tryChangeWithIgnoringPackageJson);
         if (result) return result;
 
         // If nothing changed, then result is resolved module file thats not updated
         return resolved.resolvedModule && { newFileName: resolved.resolvedModule.resolvedFileName, updated: false };
 
+        function tryChangeWithIgnoringPackageJsonExisting(oldFileName: string) {
+            const newFileName = oldToNew(oldFileName);
+            return newFileName && contains(sourcePaths, newFileName) ? tryChangeWithIgnoringPackageJson(oldFileName) : undefined;
```
Comment (sheetalkamat) [inline src/services/getEditsForFileRename.ts]: Here you are comparing Path with string.. You want to handle case sensistivity when doing this comparison since Path is canonical path while fileName is not

File: src/services/getEditsForFileRename.ts (hunk 1 above)
Comment (elibarzilay) [reply src/services/getEditsForFileRename.ts]: Done.

File: src/services/getEditsForFileRename.ts (hunk 2 above)
Comment (elibarzilay) [reply src/services/getEditsForFileRename.ts]: I switched to `fileName`, which seems like a better choice anyway...
