### PR TITLE
Fix path completions for typesVersions

### LINKED ISSUE #47952: Missing subfolder path completions with wildcard `typesVersions`
# Bug Report

Sub folders of a folder listed in `typeVersions`, do not resolve in VS Code's autocomplete. I originally believed the issue to be related to [Support for NodeJS 12.7+ package exports](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1043271180).

### 🔎 Search Terms

typeVersions
autocomplete

### 🕗 Version & Regression Information

This is using Visual Studio Code 1.64.2 and TypeScript 4.5.5. I believe this bug to not be a revision, and is not resolved in TypeScript 4.7.0.

### ⏯ Playground Link

Code required relationship between two projects, so used Github instead.

[Github repo](https://github.com/kim3er/type-version-sub-folder)

### 💻 Code

We have an internal package, written in TS, transpiled to a sub folder called 'dest'. The package.json of the package looks like:

```
{
  ...
  "type": "module",
  "exports": {
    "./*": "./dest/*"
  },
  "typesVersions": {
    "*": {
      "*": [
        "dest/*"
      ]
    }
  },
  ...
}
```

We're able to consume the package in our projects, like this:

```
import { something } from 'test-package/something'; // Actual file './dest/something.js'
```

This works. Our code is transpiled correctly. We get autocomplete on the import path, and typing on the imported whatever, within VS Code.

Until, we attempt to access a sub folder within the 'dest' folder. Within a subfolder, like:

```
import { somethingElse } from 'test-package/sub-folder/something-else'; // Actual file './js/sub-folder/something-else.js'
```

In this instance, we get everything from above, except autocomplete on the import path. The file still resolves, and we get typing. Our build script still runs, the files is just invisible.

This is using Visual Studio Code 1.64.2 and TypeScript 4.5.5. Both project and package have the following tsconfig.json:

```
{
  ...
    "target": "ES2016",
    "module": "ESNext",
  ...
}
```

### 🙁 Actual behavior

Autocomplete does not resolve the scripts with the sub folder.

Demo

### 🙂 Expected behavior

Autocomplete should resolve the scripts within a sub folder.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #47952

There were _many_ bugs with path completions for typesVersions; beyond fixing #47952, this improves many common cases.

### CODE REVIEW

File: src/services/stringCompletions.ts [hunk 1]
```diff
@@ -448,10 +448,27 @@ namespace ts.Completions.StringCompletions {
...
         fragment = ensureTrailingDirectorySeparator(fragment);
 
-        // const absolutePath = normalizeAndPreserveTrailingSlash(isRootedDiskPath(fragment) ? fragment : combinePaths(scriptPath, fragment)); // TODO(rbuckton): should use resolvePaths
         const absolutePath = resolvePath(scriptPath, fragment);
         const baseDirectory = hasTrailingDirectorySeparator(absolutePath) ? absolutePath : getDirectoryPath(absolutePath);
 
+        // check for a version redirect
+        const packageJsonPath = findPackageJson(baseDirectory, host);
+        if (packageJsonPath) {
+            const packageJson = readJson(packageJsonPath, host as { readFile: (filename: string) => string | undefined });
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:457]: What's the cast needed for?

File: src/services/stringCompletions.ts [hunk 2]
```diff
@@ -448,10 +448,27 @@ namespace ts.Completions.StringCompletions {
...
+            const typesVersions = (packageJson as any).typesVersions;
+            if (typeof typesVersions === "object") {
+                const versionResult = getPackageJsonTypesVersionsPaths(typesVersions);
+                const versionPaths = versionResult && versionResult.paths;
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:461]:
```suggestion
                const versionPaths = versionResult?.paths;
```

File: src/services/stringCompletions.ts [hunk 3]
```diff
@@ -505,37 +522,44 @@ namespace ts.Completions.StringCompletions {
...
-                for (const { name, kind, extension } of getCompletionsForPathMapping(path, patterns, fragment, baseDirectory, fileExtensions, host)) {
-                    // Path mappings may provide a duplicate way to get to something we've already added, so don't add again.
-                    if (!result.some(entry => entry.name === name)) {
-                        result.push(nameAndKind(name, kind, extension));
+                const pathPattern = tryParsePattern(path);
+                if (!pathPattern) continue;
+                const isMatch = typeof pathPattern === "object" && isPatternMatch(pathPattern, fragment);
+                const isLongestMatch = isMatch && (matchedPathPrefixLength === undefined || pathPattern.prefix.length > matchedPathPrefixLength);
+                if (isLongestMatch) {
+                    // If this is a higher priority match than anything we've seen so far, previous results from matches are invalid, e.g.
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:540]: Can you give a code example? I assume you're trying to explain completions for

```ts
import * as bar from "bar$";
```

in the presence of the below `paths` object

File: src/services/stringCompletions.ts [hunk 4]
```diff
@@ -505,37 +522,44 @@ namespace ts.Completions.StringCompletions {
...
-                }
-            }
-        }
-
         return result;
     }
 
     function addCompletionEntriesFromPaths(result: NameAndKind[], fragment: string, baseDirectory: string, fileExtensions: readonly string[], paths: MapLike<string[]>, host: LanguageServiceHost) {
+        let pathResults: { results: NameAndKind[], matchedPattern: boolean }[] = [];
+        let matchedPathPrefixLength: number | undefined;
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:530]: Nit: I might just initialize this to `-1` and just check for `< 0`.

File: src/services/stringCompletions.ts [hunk 5]
```diff
@@ -505,37 +522,44 @@ namespace ts.Completions.StringCompletions {
...
+                    // {
+                    //   "bar/*": ["bar/*"], // <-- 1. We add 'bar', but 'bar/*' doesn't match yet.
+                    //   "*": ["dist/*"],   //  <-- 2. We match here. 'bar' is still ok because it didn't come from a match.
+                    //   "foo/*": ["foo/*"] //  <-- 3. We matched '*' earlier and added results from dist, but if 'foo/*' also matches,
+                    // }                               results in dist are actually not visible. 'bar' still stands because it didn't come from a match.
+                    matchedPathPrefixLength = pathPattern.prefix.length;
+                    pathResults = pathResults.filter(r => !r.matchedPattern);
+                }
+                if (typeof pathPattern === "string" || matchedPathPrefixLength === undefined || pathPattern.prefix.length >= matchedPathPrefixLength) {
+                    const pathResult: typeof pathResults[number] = { results: [], matchedPattern: isMatch };
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:550]: [Wow, you are really trying to mess with me today, huh?](https://github.com/microsoft/TypeScript/issues/19707)

File: src/services/stringCompletions.ts [hunk 6]
```diff
@@ -505,37 +522,44 @@ namespace ts.Completions.StringCompletions {
...
+                    for (const { name, kind, extension } of getCompletionsForPathMapping(path, patterns, fragment, baseDirectory, fileExtensions, host)) {
+                        pathResult.results.push(nameAndKind(name, kind, extension));
                     }
+                    pathResults.push(pathResult);
                 }
             }
         }
+
+        pathResults.forEach(pathResult => pathResult.results.forEach(pathResult => pushIfUnique(result, pathResult, (a, b) =>
+            (host.useCaseSensitiveFileNames?.() ? equateStringsCaseSensitive : equateStringsCaseInsensitive)(a.name, b.name))));
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:560]: Hoist this out to `stringEquals`

File: src/services/stringCompletions.ts [hunk 7]
```diff
@@ -505,37 +522,44 @@ namespace ts.Completions.StringCompletions {
...
+
+        return matchedPathPrefixLength !== undefined;
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:562]: This now returns something - can you document what that is?

File: src/services/stringCompletions.ts [hunk 8]
```diff
@@ -505,37 +522,44 @@ namespace ts.Completions.StringCompletions {
...
+                    //   "foo/*": ["foo/*"] //  <-- 3. We matched '*' earlier and added results from dist, but if 'foo/*' also matches,
+                    // }                               results in dist are actually not visible. 'bar' still stands because it didn't come from a match.
+                    matchedPathPrefixLength = pathPattern.prefix.length;
+                    pathResults = pathResults.filter(r => !r.matchedPattern);
+                }
+                if (typeof pathPattern === "string" || matchedPathPrefixLength === undefined || pathPattern.prefix.length >= matchedPathPrefixLength) {
+                    const pathResult: typeof pathResults[number] = { results: [], matchedPattern: isMatch };
+                    for (const { name, kind, extension } of getCompletionsForPathMapping(path, patterns, fragment, baseDirectory, fileExtensions, host)) {
+                        pathResult.results.push(nameAndKind(name, kind, extension));
                     }
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:553]: Would this code be simpler if you turned this into a `map` call, then created `pathResult` out of it?

File: src/services/stringCompletions.ts [hunk 9]
```diff
@@ -659,11 +683,15 @@ namespace ts.Completions.StringCompletions {
 
         const pathPrefix = path.slice(0, path.length - 1);
         const remainingFragment = tryRemovePrefix(fragment, pathPrefix);
-        return remainingFragment === undefined ? justPathMappingName(pathPrefix) : flatMap(patterns, pattern =>
-            getModulesForPathsPattern(remainingFragment, baseUrl, pattern, fileExtensions, host));
+        if (remainingFragment === undefined) {
+            const starIsFullPathComponent = path[path.length - 2] === "/";
+            return starIsFullPathComponent ? justPathMappingName(pathPrefix) : flatMap(patterns, pattern =>
+                getModulesForPathsPattern("", baseUrl, pattern, fileExtensions, host)?.map(({ name, ...rest }) => ({ name: pathPrefix + name, ...rest })));
```
Comment (DanielRosenwasser) [inline src/services/stringCompletions.ts:689]: Pedantic: can you get away with `pathPrefix + name` or do you need to use `combinePaths`?

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

File: src/services/stringCompletions.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/stringCompletions.ts:461]: You might want to hide whitespace changes; you’re requesting changes on a lot of code I didn’t write 😑

File: src/services/stringCompletions.ts (hunk 9 above)
Comment (andrewbranch) [reply src/services/stringCompletions.ts:689]: It’s explicitly not combining paths; these might be two halves of a single directory name.

File: src/services/stringCompletions.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/services/stringCompletions.ts:461]: The whitespace-ignoring diff isn't that magical, these aren't in the same spot :D

In any case, we can make the changes now.

File: src/services/stringCompletions.ts (hunk 8 above)
Comment (andrewbranch) [reply src/services/stringCompletions.ts]: This is infinitely better. I was kind of on autopilot adapting old code rather than writing it how I would have written it.

File: src/services/stringCompletions.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/stringCompletions.ts:457]: I don’t know (this code just moved), but I’m not investigating this one right now because when I fix the same issue but for package.json `exports` I’m going to migrate this to use the PackageJsonCache. Did you know that `readJson` actually creates a JSON `SourceFile` object and fills it with parse diagnostics? 🙃 This is pretty much the least efficient way we could possibly get the contents of a package.json as an object.

**Review by sheetalkamat — APPROVED** [review]
