### PR TITLE
More permissive parsing of instantiation expressions

### LINKED ISSUE #48654: ASI not working after arguments-less new expression with type arguments
# Bug Report

### 🔎 Search Terms

asi new expression type arguments

### 🕗 Version & Regression Information

TypeScript 4.7 Nightly (tested with the playground). This syntax has never been valid before TS 4.7.

`new X<T>;` is valid syntax since https://github.com/microsoft/TypeScript/pull/47607 (cc @ahejlsberg)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/MYGwhgzhAECCA8AVAfNA3gXwFBYHYFMB3OeXAVwFsAjfAJ2RwEsAzaACgAYBKdDIA)

### 💻 Code

```ts
class A<T> {}

new A<number>

if (0) {}
```

### 🙁 Actual behavior

It's parsed as if it was
```ts
class A<T> {}

new A<number> if (0) {}
```
thus it reports a few errors (`number` is used in a value position, and `if` is a reserved word).

### 🙂 Expected behavior

I would expect ASI to kick, and that cause that code to be parsed as if it was
```ts
class A<T> {}

new A<number>;

if (0) {}
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #48654.

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -5735,34 +5735,10 @@ namespace ts {
...
-                case SyntaxKind.AmpersandToken:                 // foo<x> &
-                case SyntaxKind.BarToken:                       // foo<x> |
-                case SyntaxKind.CloseBraceToken:                // foo<x> }
-                case SyntaxKind.EndOfFileToken:                 // foo<x>
                     return true;
             }
-            // Treat anything else as an expression.
-            return false;
+            // Consider something a type argument list only if the following token can't start an expression.
+            return !isStartOfExpression();
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts:5741]: I'm always surprised that this function exists and doesn't fall out of date in some catastrophic way.

**Review by DanielRosenwasser — APPROVED** [review]

File: src/compiler/parser.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/parser.ts:5741]: Oh, we'd know right away. For example, in when parsing argument lists or array literal elements, we require it to return `true` before each element (it's called from `isListElement` which is called from `parseList`).
