### PR TITLE
fix(48487): "Unexpected PrivateIdentifier in name expression with literal-like access" being hit

### LINKED ISSUE #48487: "Unexpected PrivateIdentifier in name expression with literal-like access" being hit
# Bug Report

### 🔎 Search Terms

"Unexpected PrivateIdentifier in name expression with literal-like access."
"Private Identifier"
"isSameEntityName"
"isPrivateIdentifier"

### 🕗 Version & Regression Information

I noticed this bug today (3/30/2022), but we believe that this bug goes back to Typescript 3.8

- This changed between versions 3.7.5 and 3.8.3

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.8.3#code/C4TwDgpgBAyg9gWwgeQEYCsoF4oG8BmccAXFAM7ABOAlgHYDmAvgNwBQrAxgDYCGZZUAAo0Abj2AQAshASoIlAEIBXenlZQNUAMRhR4qTLmUA-KXhI06Nus1lEEAGJLaHABQBKNZu9QOcWhTk9pbYUMAAFtRkAHQ6ehLSsvJQAD4peCw2GoysjEA)

### 💻 Code

```ts
type SomeObj = {foo?: string};

class PrivateMemberBug {
    #privateMember?: SomeObj;

    someFunc() {
        const someObj = this.#privateMember || {};
    }
}
```

This is a workaround I found:
```ts
type SomeObj = {foo?: string};

class PrivateMemberBug {
    #privateMember?: SomeObj;

    someFunc() {
        const someObj: SomeObj = this.#privateMember || {};
    }
}
```

### 🙁 Actual behavior

Received cryptic error in console and no errors in vscode UI.

### 🙂 Expected behavior

No errors expected.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #48487

### CODE REVIEW

File: tests/cases/conformance/classes/members/privateNames/typeFromPrivatePropertyAssignment.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+class C {
+    #a?: Foo;
+    #b?: Foo;
+
+    m() {
+        const a = this.#a || {};
+        this.#b = this.#b || {};
+    }
+}
```
Comment (DanielRosenwasser) [inline tests/cases/conformance/classes/members/privateNames/typeFromPrivatePropertyAssignment.ts:13]: Let's add a `.js` file to this test, since that code path ideally wouldn't have occurred in a TS file in the first place.

```suggestion
// @filename: a.ts
type Foo = { foo?: string };

class C {
    #a?: Foo;
    #b?: Foo;

    m() {
        const a = this.#a || {};
        this.#b = this.#b || {};
    }
}

// @filename: b.js
class C {
    /** @type {{ foo?: string } | undefined } */
    #a;
    /** @type {{ foo?: string }| undefined } */
    #b;

    m() {
        const a = this.#a || {};
        this.#b = this.#b || {};
    }
}
```

**Review by sandersn — APPROVED** [review]
