### PR TITLE
Fix crash when circular reference in variance annotations

### LINKED ISSUE #48537: Some optional variance annotations cause a compiler crash
# Bug Report

Context: I am testing PR #48240 because of https://github.com/evanw/esbuild/pull/2102, which adds parser support for optional variance annotations to esbuild.

### 🔎 Search Terms

optional variance annotation compiler crash TypeError

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link 1 with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220403#code/C4TwDgpgBAKgPASwHZWQPigXlkA)
[Playground link 2 with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220403#code/C4TwDgpgBAKgPAewK7Cs4A+KBeWQ)

### 💻 Code

```ts
type T<in in> = T
```

```ts
type T<out out> = T
```

### 🙁 Actual behavior

```
Uncaught (in promise) TypeError: links.instantiations is undefined
    getTypeAliasInstantiation https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:49208
    createMarkerType https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:54916
    checkTypeParameter https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:65496
    checkTypeParameters https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:68524
    checkTypeAliasDeclaration https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:69111
    checkSourceElementWorker https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:70070
    checkSourceElement https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:69904
    forEach https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:483
    checkSourceFileWorker https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:70228
    checkSourceFile https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:70196
    checkSourceFileWithEagerDiagnostics https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:70289
    getDiagnosticsWorker https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:70297
    getDiagnostics https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:70271
    getBindAndCheckDiagnosticsForFileNoCache https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94412
    runWithCancellationToken https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94385
    getBindAndCheckDiagnosticsForFileNoCache https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94400
    getAndCacheDiagnostics https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94666
    getBindAndCheckDiagnosticsForFile https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94397
    getSemanticDiagnosticsForFile https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94394
    getDiagnosticsHelper https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94333
    getSemanticDiagnostics https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:94346
    getSemanticDiagnostics https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:136152
    getSemanticDiagnostics https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/language/typescript/tsWorker.js:164599
    fmr https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:14662
    _handleMessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:9957
    handleMessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:9942
    _handleRequestMessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:9746
    _handleMessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:9715
    handleMessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:9708
    onmessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:9947
    onmessage https://typescript.azureedge.net/cdn/4.7.0-dev.20220403/monaco/dev/vs/base/worker/workerMain.js:14770
```

### 🙂 Expected behavior

The TypeScript compiler should either produce valid code or generate an error diagnostic. I would expect `type T<in in> = T` to generate an error diagnostic because `in` is a keyword, not an identifier. I would expect `type T<out out> = T` to produce valid code because `out` is an identifier.

### PR DESCRIPTION
**Pull request by magic-akari**
- Fixes #48537

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20640,6 +20640,11 @@ namespace ts {
         function createMarkerType(symbol: Symbol, source: TypeParameter, target: Type) {
             const mapper = makeUnaryTypeMapper(source, target);
             const type = getDeclaredTypeOfSymbol(symbol);
+
+            if (isErrorType(type)) {
+                return type;
+            }
+
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:20647]: Very minor nit, remove the blank lines around the `if` statement.

**Review by ahejlsberg — COMMENTED** [review]
Approved with the suggested change. Thanks for catching this!

**Review by ahejlsberg — APPROVED** [review]
