### PR TITLE
Fix getTypeAtLocation for dotted implements clauses

### LINKED ISSUE #37901: `getTypeAtLocation` fails on a `PropertyAccessExpression` in a type position
**TypeScript Version:**  3.8.3

**Search Terms:**
`getTypeAtLocation`

**Code**

```ts
declare class SomeClass implements NodeJS.CallSite {
  //
}
```

**Expected behavior:**
`getTypeAtLocation` on the `PropertyAccessExpression` node for `NodeJS.CallSite` should return `CallSite`.

**Actual behavior:**
Instead, it returns `any` with intrinsic name `error`.

**Notes**
Note that `getTypeAtLocation` on the parent `ExpressionWithTypeArguments` does actually succeed.

**Playground Link:** N/A

**Related Issues:** #35233

Thanks to @bradzacher for finding this!

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37901

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14381,11 +14381,12 @@ namespace ts {
                     return getTypeFromInferTypeNode(<InferTypeNode>node);
                 case SyntaxKind.ImportType:
                     return getTypeFromImportTypeNode(<ImportTypeNode>node);
-                // This function assumes that an identifier or qualified name is a type expression
+                // This function assumes that an identifier, qualified name, or proprety access expression is a type expression
```
Comment (sandersn) [inline src/compiler/checker.ts:14384]:
```suggestion
                // This function assumes that an identifier, qualified name, or property access expression is a type expression
```

File: src/testRunner/unittests/publicApi.ts [hunk 2]
```diff
@@ -77,3 +77,31 @@ describe("unittests:: Public APIs:: isPropertyName", () => {
         assert.isTrue(ts.isPropertyName(prop), "PrivateIdentifier must be a valid property name.");
     });
 });
+
+describe("unittests:: Public APIs:: getTypeAtLocation", () => {
+    it("works on PropertyAccessExpression in implements clause", () => {
```
Comment (sandersn) [inline src/testRunner/unittests/publicApi.ts:82]: would this be easier as a fourslash test? I mean, the answer is probably No, but I thought that quickinfo used getTypeAtLocation.

Comment (andrewbranch) [reply src/testRunner/unittests/publicApi.ts:82]: Mmmmmaaybe? I didn’t think about quick info. I had hoped that the type baseliner would do the job, but it didn’t drill all the way down to the problematic node. Quick info also seems susceptible to future changes in which nodes it calls `getTypeAtLocation` on, even if it works now. I do wish it was easier to set up this kind of test.
