### PR TITLE
Fix up comments for super calls rewritten as returns

### LINKED ISSUE #12191: Compiler adds return before comment in constructor.
**TypeScript Version:**  2.1.1
It seems that version 2.1 of typescript changed subclass constructor compilation and it could potentially be a breaking change. I haven't seen it documented. 
'return' is injected at the beginning of a compiled constructor, even before comment, but super call is left out after comment and in result it's not executed. 

**Code**

```ts
class A {
    constructor(public text: string) { }
    print() {
        console.log(this.text);
    }
};

class B extends A {
    constructor(text: string) {
        // this is subclass constructor
        super(text)
     }
};
```

**Expected behavior:**
```ts
var B = (function (_super) {
    __extends(B, _super);
    function B(text) {
        // this is subclass constructor
        return _super.call(this, text) || this;
    }
    return B;
}(A));
;
```

**Actual behavior:** 
```ts
var B = (function (_super) {
    __extends(B, _super);
    function B(text) {
        return 
        // this is subclass constructor
        _super.call(this, text) || this;
    }
    return B;
}(A));
;
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #12191.

### CODE REVIEW

File: src/compiler/transformers/es2015.ts [hunk 1]
```diff
@@ -1011,7 +1011,20 @@ namespace ts {
 
             // Return the result if we have an immediate super() call on the last statement.
             if (superCallExpression && statementOffset === ctorStatements.length - 1) {
-                statements.push(createReturn(superCallExpression));
+                const returnStatement = createReturn(superCallExpression);
+
+                if (superCallExpression.kind !== SyntaxKind.BinaryExpression
+                    && (superCallExpression as BinaryExpression).left.kind !== SyntaxKind.CallExpression) {
```
Comment (mhegazy) [inline src/compiler/transformers/es2015.ts]: I think you mean `||` here.

**Comment by mhegazy** [comment]
@rbuckton can you take a look.
