### PR TITLE
Revert fix for intersections in template literals, fix differently

### LINKED ISSUE #52345: Performance regression from #48044
# Bug Report

It seems like a fairly significant performance regression was introduced in this https://github.com/microsoft/TypeScript/pull/48044, which was shipped in TS 4.7. In TS 4.6, it takes ~30 seconds to run `yarn tsc` in our repo, and the reported strict subtype cache size is 24_011. In TS 4.7, it takes 75+ seconds to run `yarn tsc` (~2.5x longer than previous), and the reported strict subtype cache size is 122_778 (~5x larger than previous).

I verified that it was that specific PR that regressed the performance by taking a locally-installed 4.6.4 and applying the changes from that PR directly.

Another symptom is that several types (mostly spreads of objects into others) are now reporting as "Expression produces a union type that is too complex to represent."

### 🔎 Search Terms

`Expression produces a union type that is too complex to represent`, `strict subtype cache size`

### 🕗 Version & Regression Information

- Regressed in https://github.com/microsoft/TypeScript/pull/48044
- This changed between versions 4.6.4 and 4.7.3

|Version|Time|Strict Subtype Cache Size|
|-------|-----|--------------------------|
|4.6.4  | 33s | 24011                                  |
|4.7.3  | 75s | 122778                                 |
|4.9.4  | 77s | 122869                                |
|5.0.0-dev.20230120 | 78s | 122869 |

### 💻 Code

I haven't been able to narrow down a minimal reproduction of this issue, but if someone points me in the right direction I'm happy to work on it.

### 🙁 Actual behavior

Running `yarn tsc --noEmit --extendedDiagnostics` takes ~75 seconds in our repo, with a Strict subtype cache size of 122778.

### 🙂 Expected behavior

Running `yarn tsc --noEmit --extendedDiagnostics` takes ~30 seconds in our repo, with a Strict subtype cache size of 24011.

### PR DESCRIPTION
**Pull request by jakebailey**
For #52345

This reverts #48044, which with nearly a year more experience no longer looks correct to my eyes (I regret merging it), and instead implements a different fix for the issue. This one instead avoids expanding out intersections, leaving them in place like the other non-string-y types.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
Well, this turned into a bit of a whack-a-mole, since the original PR I merged for this (sorry) was not complete and didn't add support for intersections in other places either, probably because it was missing tests and I never ran any extended tests (sorry x2)

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -17395,7 +17389,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             return (type as SubstitutionType).objectFlags & ObjectFlags.IsGenericType;
         }
         return (type.flags & TypeFlags.InstantiableNonPrimitive || isGenericMappedType(type) || isGenericTupleType(type) ? ObjectFlags.IsGenericObjectType : 0) |
-            (type.flags & (TypeFlags.InstantiableNonPrimitive | TypeFlags.Index | TypeFlags.TemplateLiteral | TypeFlags.StringMapping) && !isPatternLiteralType(type) ? ObjectFlags.IsGenericIndexType : 0);
+            (type.flags & (TypeFlags.InstantiableNonPrimitive | TypeFlags.Index | TypeFlags.StringMapping) && !isPatternLiteralType(type) ? ObjectFlags.IsGenericIndexType : 0);
```
Comment (jakebailey) [inline src/compiler/checker.ts:17392]: I feel like StringMapping / isPatternLiteralType could be dropped here, and instead just have `getGenericObjectFlags` return `getGenericObjectFlags((type as StringMappingType).type)` (as above), but I have been unable to find a bug that this fixes, even when combining the new intersection tests for the follow-up issues I found.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -17380,12 +17374,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     }
 
     function getGenericObjectFlags(type: Type): ObjectFlags {
-        if (type.flags & TypeFlags.UnionOrIntersection) {
-            if (!((type as UnionOrIntersectionType).objectFlags & ObjectFlags.IsGenericTypeComputed)) {
-                (type as UnionOrIntersectionType).objectFlags |= ObjectFlags.IsGenericTypeComputed |
-                    reduceLeft((type as UnionOrIntersectionType).types, (flags, t) => flags | getGenericObjectFlags(t), 0);
+        if (type.flags & (TypeFlags.UnionOrIntersection | TypeFlags.TemplateLiteral)) {
```
Comment (jakebailey) [inline src/compiler/checker.ts:17377]: It also occurs to me that `ObjectFlagsType` needs to be updated to say that TemplateLiteral might contain these too, though, I don't know what affect that'll have.

**Review by weswigham — APPROVED** [review]

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -17006,32 +17006,24 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
                 }
                 else if (t.flags & TypeFlags.TemplateLiteral) {
                     text += (t as TemplateLiteralType).texts[0];
                     if (!addSpans((t as TemplateLiteralType).texts, (t as TemplateLiteralType).types)) return false;
-                    text += addText;
-                    if (!isTextsArray) return true;
+                    text += texts[i + 1];
                 }
-                else if (isGenericIndexType(t) || isPatternLiteralPlaceholderType(t)) {
+                else if (isGenericIndexType(t) || isPatternLiteralPlaceholderType(t) || t.flags & TypeFlags.Intersection) {
```
Comment (weswigham) [inline src/compiler/checker.ts:17021]: Actually, on second thought, you should update `isPatternLiteralPlaceholderType` itself rather than this condition. That'll handle the string mapping types a bit more consistently without needing your other change to the function, and will fix nesting these inside one another. Moreover, you probably want to say only intersections which contain at least one valid pattern literal placeholder type. I don't really think `a${{x: number} & {y: string}}` should work.

**Review by weswigham — CHANGES_REQUESTED** [review]

**Comment by jakebailey** [comment]
@weswigham Do you have any commentary on this in general? I'm doubting my choice here; it does allow you to write template types that contain intersections, which, you can only use by creating more template literals (as in my Path example).

However, I'm somewhat wondering if I should instead be treating these like unions, i.e. expand them out at the top where if you have say `` `a${A & B}b` ``, that it turns into `` `a${A}b` & `a${B}b` ``.

File: src/compiler/checker.ts (hunk 3 above)
Comment (jakebailey) [reply src/compiler/checker.ts:17021]: Thanks for the tip, I'll take a look.

Comment (jakebailey) [reply src/compiler/checker.ts]: To clarify, what "other change to the function" are you referring to in the above? Just `|| t.flags & TypeFlags.Intersection`?

I have tried:

```ts
        if (type.flags & TypeFlags.Intersection) {
            return some((type as IntersectionType).types, isPatternLiteralPlaceholderType);
        }
```

But, I run into the problem that `isPatternLiteralPlaceholderType` is false for string literals as those are always handled before getting to a call to `isPatternLiteralPlaceholderType`, so maybe I have to also check those even if they need special handling most of the time.

Comment (jakebailey) [reply src/compiler/checker.ts]: I tried to make the change, but, maybe I went too far. Mainly, I had to make it handle literals too, and it seemed off to _not_ also allow other kinds of literals when I was already handling string literals.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -17404,7 +17398,19 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
     }
 
     function isPatternLiteralPlaceholderType(type: Type): boolean {
-        return !!(type.flags & (TypeFlags.Any | TypeFlags.String | TypeFlags.Number | TypeFlags.BigInt)) || isPatternLiteralType(type);
+        if (type.flags & TypeFlags.Intersection) {
+            return some((type as IntersectionType).types, isPatternLiteralPlaceholderType);
```
Comment (weswigham) [inline src/compiler/checker.ts:17402]: Hm, we don't want `"a"` to be a valid placeholder type, but we do want `"a" & {brand}` to be, so I'd move the `Primitive`-allowing check into the intersection check. So
```suggestion
            return some((type as IntersectionType).types, t => !!(t.flags & (TypeFlags.Literal | TypeFlags.Null | TypeFlags.Undefined)) || isPatternLiteralPlaceholderType(t));
```
(and also use `TypeFlags.Literal | TypeFlags.Null | TypeFlags.Undefined` instead of `Primitive` to match what we use within the other branch of `getTemplateLiteralType`.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -17404,7 +17398,19 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+
+        if (type.flags & (TypeFlags.TemplateLiteral | TypeFlags.StringMapping)) {
+            return isPatternLiteralType(type);
+        }
+
+        if (type.flags & TypeFlags.ESSymbolLike) {
+            return false;
+        }
+
+        return !!(type.flags & (TypeFlags.Any | TypeFlags.Primitive));
```
Comment (weswigham) [inline src/compiler/checker.ts:17413]: Then we can revert the rest to the original
```suggestion
return !!(type.flags & (TypeFlags.Any | TypeFlags.String | TypeFlags.Number | TypeFlags.BigInt)) || isPatternLiteralType(type);
```
so there's no surprising new behavior that doesn't involve intersections with literals in them.

**Review by weswigham — COMMENTED** [review]
> Do you have any commentary on this in general? I'm doubting my choice here; it does allow you to write template types that contain intersections, which, you can only use by creating more template literals (as in my Path example).

Hm, I think only being able to interact with branded holes with other branded types is kinda the point of branding your literal types. Simultaneously, today you can use a template literal to "unbrand" a branded type (I don't know how prevalent that is, and, obviously if you look at the prompting issue, it isn't desirable to some). I'm not crushed by replacing the "unbranding" behavior with respecting brands, though, since you can also "unbrand" a branded literal type with something like
```ts
type Unbrand<T, TBrand> = T extends infer Q & TBrand ? Q : never;

type Q = Unbrand<"a" & {ok: any}, {ok: any}>;
```
which is, IMO, better, since you have to specify what brands you're removing from the type.

> However, I'm somewhat wondering if I should instead be treating these like unions, i.e. expand them out at the top where if you have say `a${A & B}b`, that it turns into `a${A}b` & `a${B}b`.

No, I don't think that's right - intersected literals always become `never`, so the only meaningful intersections are branded literals. So if you split the brand and the literal apart, you'd have an object alone inside a template hole, like making `a/${"b" & {path:any}}/c` into `a/b/c & a/${{path:any}}/c`, and that later type has basically no meaning (in fact, by current rules, it just makes the type into `string`, which'll then evaporate entirely) - it's only useful when you consider it with what it's intersected with anyway.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts:17402]: Though the `Null` and `Undefined` may be unnecessary, since I think our construction rules mean you can't brand them like you can other literal types.

**Comment by jakebailey** [comment]
Thanks for the feedback! I've mad the changes.

**Review by weswigham — APPROVED** [review]
