### PR TITLE
Fix duplicate completions bugs

### LINKED ISSUE #23587: Duplicate completion entries for `undefined`
#23591 exposes more completions bugs. See the `// TODO: GH#23587` comment in `fourslash.ts`.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #23587

Will rebase against master after #23591 is in.
Also removes the "constructor", "get", "set", "private", "public", and "static" contextual keywords from global completions.
(Also removes two tests that are already covered by `completionListKeywords.ts`.)

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -2059,16 +2059,17 @@ namespace ts.Completions {
             const kind = stringToToken(entry.name);
             switch (keywordFilter) {
                 case KeywordCompletionFilters.None:
-                    // "undefined" is a global variable, so don't need a keyword completion for it.
-                    return kind !== SyntaxKind.UndefinedKeyword;
+                    // TODO: GH#23631 Includes type keywords because `Array<numb/**/` is treaded as a value location currently.
```
Comment (sheetalkamat) [inline src/services/completions.ts]: isPossiblyTypeArgumentPosition we have this function to check for type argument location

Comment (andy-ms) [reply src/services/completions.ts]: Thanks, added a note to #23631
