### PR TITLE
Fix emit for ES6 export default class with static initializers. 

### LINKED ISSUE #5136: Incorrect emit for ES6 export default class with static initializers
Given the following TypeScript:

```ts
export default class {
  static x = 1;
}
```

We emit the following JavaScript:

```ts
export default class {
}
default_1.x = 1; // TypeError: Cannot set property 'x' of undefined
```

Where we should emit the following instead:

```ts
export default class default_1 { // generated
}
default_1.x = 1;
```

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #5136.

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -4785,8 +4785,10 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
 
                 // emit name if
                 // - node has a name
-                // - this is default export and target is not ES6 (for ES6 `export default` does not need to be compiled downlevel)                
-                if ((node.name || (node.flags & NodeFlags.Default && languageVersion < ScriptTarget.ES6)) && !thisNodeIsDecorated) {
+                // - this is default export and target is not ES6 (for ES6 `export default` does not need to be compiled downlevel)
+                // - this is default export with static initializers
+                if ((node.name || (node.flags & NodeFlags.Default && (languageVersion < ScriptTarget.ES6
```
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts]: languageVersion should never be less than ES6 here since this is in `emitClassLikeDeclarationForES6AndHigher`

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -4785,8 +4785,10 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
 
                 // emit name if
                 // - node has a name
-                // - this is default export and target is not ES6 (for ES6 `export default` does not need to be compiled downlevel)                
-                if ((node.name || (node.flags & NodeFlags.Default && languageVersion < ScriptTarget.ES6)) && !thisNodeIsDecorated) {
+                // - this is default export and target is not ES6 (for ES6 `export default` does not need to be compiled downlevel)
```
Comment (mhegazy) [inline src/compiler/emitter.ts]: can you update the comment as well.

**Comment by mhegazy** [comment]
:+1:

File: src/compiler/emitter.ts (hunk 1 above)
Comment (rbuckton) [inline src/compiler/emitter.ts]: It looks like the previous version may have been a vestige of our class emit before we split the function.
