### PR TITLE
Disallow let in let/const declaration regardless of target

### LINKED ISSUE #3475: 'let' should not be allowed to be bound as a variable in a for-of loop or let/const decl
The following examples should trigger an early error in JS:

```TypeScript
let let = 10;
```

```TypeScript
const let = 10;
```

<sub>Note: a similar test exists in `tests/cases/conformance/es6/for-ofStatements/for-of56.ts`) for the following 3 examples</sub>
```TypeScript
for (var let of [1,2,3]) {
}
```

```TypeScript
for (let let of [1,2,3]) {
}
```

```TypeScript
for (const let of [1,2,3]) {
}
```

I'm not sure if the following should trigger an error:

```TypeScript
var let = 10;
for (let of [1,2,3]) {
}
```

-------
-------

> ### <span id="sec-13.2.1.1" class="secnum">[13.2.1.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations-static-semantics-early-errors "link to this section")</span> Static Semantics: Early Errors

> *LexicalDeclaration* <span class="geq">:</span> *LetOrConst* *BindingList* `;`

> -   It is a Syntax Error if the BoundNames of *BindingList* contains `"let"`.

-----------------

> ### <span id="sec-13.6.4.1" class="secnum">[13.6.4.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-in-and-for-of-statements-static-semantics-early-errors "link to this section")</span> Static Semantics: Early Errors

> *IterationStatement* <span class="geq">:</span>

> `for` `(` *ForDeclaration* `in` *Expression* `)` *Statement*

> `for` `(` *ForDeclaration* `of` *AssignmentExpression* `)` *Statement*

> -   It is a Syntax Error if the BoundNames of *ForDeclaration* contains `"let"`.

### PR DESCRIPTION
**Pull request by yuit**
fix #3475

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15974,17 +15974,26 @@ namespace ts {
...
-                            : Diagnostics.The_left_hand_side_of_a_for_of_statement_cannot_use_a_type_annotation;
-                        return grammarErrorOnNode(firstDeclaration, diagnostic);
+
+                    // firstDeclaration can be undefined if there is variable declaration in for-of or for-in
+                    // See http://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements for details
+                    // For example:
+                    //      var let = 10;
+                    //      for (let of [1,2,3]) {} // this is invalid ES6 syntax
+                    //      for (let in [1,2,3]) {} // this is invalid ES6 syntax
+                    if (firstDeclaration) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Consider making this a check on `variableList.declaration.length > 0`. @vladima might be able to weigh in on if this sort of thing causes de-opts.

**Comment by mhegazy** [comment]
LGTM
