### PR TITLE
handle block scoped binding in nested blocks

### LINKED ISSUE #6462: Block scope support is broken
TypeScript 1.7.5 does not support the block scope for y here when emitting code for ES5:
```typescript
function test() {
	let x = 42;
	{
		let x = 43;
		console.log(x);
	}

	{
		let y = 77;
		console.log(y);
	}
	{
		let y = 88;
		console.log(y);
	}
}
```
Compilation result:
```javascript
function test() {
    var x = 42;
    {
        var x_1 = 43;
        console.log(x_1);
    }
    {
        var y = 77;
        console.log(y);
    }
    {
        var y = 88;
        console.log(y);
    }
}
```
At least one of the y's should also have been renamed.

(In my "real" code instead of "console.log()" there are local functions that use y and are registered as callbacks. The first function incorrectly uses the value from the second block.)

Related to #1690

### PR DESCRIPTION
**Pull request by vladima**
fixes #6462

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -2030,7 +2030,7 @@ namespace ts {
         containingType?: UnionOrIntersectionType; // Containing union or intersection type for synthetic property
         resolvedExports?: SymbolTable;      // Resolved exports of module
         exportsChecked?: boolean;           // True if exports of external module have been checked
-        isNestedRedeclaration?: boolean;    // True if symbol is block scoped redeclaration
+        isDeclaratonWithCollidingName?: boolean;    // True if symbol is block scoped redeclaration
```
Comment (ahejlsberg) [inline src/compiler/types.ts]: Should be `isDeclarationWithCollidingName`.

Comment (vladima) [inline src/compiler/types.ts]: my bad, will fix

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -4025,22 +4025,56 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, ge
...
-                            (getCombinedFlagsForIdentifier(<Identifier>node.name) & NodeFlags.Let);
-
-                        // NOTE: default initialization should not be added to let bindings in for-in\for-of statements
-                        if (isLetDefinedInLoop &&
-                            node.parent.parent.kind !== SyntaxKind.ForInStatement &&
-                            node.parent.parent.kind !== SyntaxKind.ForOfStatement) {
+                    if (!initializer &&
+                        languageVersion < ScriptTarget.ES6 &&
+                        // for names - binding patterns that lack initializer there is no point to emit explicit initializer 
+                        // since downlevel codegen for destructuring will fail in the absence of initializer so all binding elements will say uninitialized
```
Comment (ahejlsberg) [inline src/compiler/emitter.ts]: I have a hard time parsing this comment.

Comment (vladima) [inline src/compiler/emitter.ts]: this comment is related to our emit in the presence of errors, should we emit zero initializers for cases like this one
```ts
let {a,b,c};
```
Currently we don't do this because main reason why it is done for identifiers is that we don't want old value to be observed. However for destructuring downlevel emit will always throw if initializer is omitted .

Comment (ahejlsberg) [inline src/compiler/emitter.ts]: I see. Agreed, we shouldn't emit initializers in the destructuring case.
