### PR TITLE
Change sortText for class member completions

### LINKED ISSUE #47852: Suggestions for method override snippets always have higher priority than keywords such as access modifiers, even when they'd be a better match.
# Bug Report

### 🔎 Search Terms

- suggestions
- method snippet
- method override completions
- access modifier/specifier
- vscode

### 🕗 Version & Regression Information

- Only applicable to >= 4.5.x with the addition of method override snippets.
- Still reproduces in 4.6.0-dev.20220211

### ⏯ Playground Link
N/A - As far as I can tell, playground doesn't seem to support the new method override snippets.

### 💻 Code

```ts
class A
{
	public methodA(){}
	public methodB(){}
	protected methodC(){}
	protected methodD(){}
}

class B extends A
{
	protected methodC(): void {}
}
```

### 🙁 Actual behavior

Parts of the method signatures other than the name seem to trigger override suggestions, regardless of how little the typed text matches the potential list of methods to override.  
In class B, attempt to add a new public or protected method that you don't want to be an override. As you start typing the public/protected keyword, the override snippts for the method(s) with whichever access modifier you chose show up with top priority in the suggestions.  
E.g. for protected, you can get all the way to "protecte" and still have the top suggestion in the above example be an override for methodD, when at this point the better suggestion is clearly the protected keyword itself. In TypeScript <4.5.x the protected keyword would've been top suggestion after only a couple of characters as no other member matches better. In 4.5.x the keyword only gets top priority once fully written out.

### 🙂 Expected behavior

I'd personally perfer that suggestions for method overrides should only match the method name, not other parts of the signature such as the access modifier. On the other hand, I can also see a use case for wanting to see all overridable methods by access modifier so other people may have a different opinion.

VSCode shows highlighted/matching letters in suggestion entries based on the currently typed text, if this functionality is provided by TypeScript rather than vscode, perhaps the suggestion priorities could be weighted similarly?  
E.g. say we have a base class method called "protectSomething", if the user's currently typed "protect" maybe the override snippet still has priority, as it's just as equal a fit as the protected keyword at this point, but if we then type the e, the protected keyword is now a better match than **protect**Som**e**thing (how vscode would probably highlight it), so the keyword should now get priority over the snippet.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #47852.

I've changed the `sortText` order of class member snippet completions to be lower priority than the `sortText` of keywords. This means that when a user is typing inside a class, if there is both a keyword and a class member completion that have the same score, the keyword appears first.

This score is something computed by vscode, based on how well the prefix (what the user has typed so far) matches the completion entry's text.
For instance, in the scenario below:
```ts
class A {
    protected foo(): void {
        return;
    }
}

class B extends A {
    pro|
}
```
The prefix is `pro`, and so this would match both an entry for the `protected` keyword, as well as a class member snippet entry for `protected foo(): void ...`. The score is the same because `pro` matches right at the beginning of both entries' text, but before this PR, `protected foo(): void ...` would appear first because its `sortText` was higher priority than the one for `protected`. After this PR, the opposite will happen: `protected` will appear before `protected foo(): void ...`.

The perhaps annoying counterpart to this change is that, if inside a class the user hasn't typed anything yet, the completion list will start with all the class keywords and only then show the methods.
But if we wanted a fix that had both the methods show up before the keywords when nothing is typed, *and* had the methods show up after the keywords if there's a partial prefix match, we'd probably need to tweak things on the vscode side.

### CODE REVIEW

File: tests/cases/fourslash/completionsOverridingMethod13.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+verify.completions({
+    marker: "",
+    isNewIdentifierLocation: true,
+    preferences: {
+        includeCompletionsWithInsertText: true,
+        includeCompletionsWithSnippetText: false,
+        includeCompletionsWithClassMemberSnippets: true,
+    },
+    exact: [
```
Comment (gabritto) [inline tests/cases/fourslash/completionsOverridingMethod13.ts:23]: honestly, I only added that test to showcase that inside a class (the only scenario we're concerned with), we only have to consider the class element keywords versus the class member completions, but I can get rid of the test if it seems superfluous

File: src/services/completions.ts [hunk 2]
```diff
@@ -769,6 +769,7 @@ namespace ts.Completions {
             isClassLikeMemberCompletion(symbol, location)) {
             let importAdder;
             ({ insertText, isSnippet, importAdder, replacementSpan } = getEntryForMemberCompletion(host, program, options, preferences, name, symbol, location, contextToken, formatContext));
+            sortText = SortText.AutoImportSuggestions; // sortText has to be lower priority than the sortText for keywords. See #47852.
```
Comment (andrewbranch) [inline src/services/completions.ts:772]: Let’s make a new SortText member for this.

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 2 above)
Comment (gabritto) [reply src/services/completions.ts:772]: do you mean a new enum member that also has value "16", or that has a new value? I think the value should be as high as possible while lower than the one for keywords, and it also has to be higher than the one for deprecated class members, but I want to check

Comment (gabritto) [reply src/services/completions.ts]: went ahead and created the enum member, please let me know if you meant something different.

Comment (andrewbranch) [reply src/services/completions.ts]: I meant you can bump the other numbers up so that each member gets its own value. The specific value of the number isn’t important but it seems best to avoid collisions.

Comment (gabritto) [reply src/services/completions.ts]: I bumped the other members down, that seemed better because otherwise the first sort text member would have to be "09", and its sort text id would be 9, and it would be wrong to just do `sortTextId.toString()` on it because we need the double digits.

**Review by andrewbranch — APPROVED** [review]

File: src/services/completions.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/completions.ts]: By “up” I meant a higher number so I think you did the thing I was poorly trying to describe 🙃
