### PR TITLE
Fix incorrectly looking for position in call/new expression arguments when looking for indentation of type arguments

### LINKED ISSUE #32487: argumentStartsOnSameLineAsPreviousArgument  crashes
```
 TypeScript Server Error (3.6.0-dev.20190719) Debug Failure. Error: Debug Failure.

at Object.assertDefined (tsserver.js:2080:24)
at Object.argumentStartsOnSameLineAsPreviousArgument (tsserver.js:113383:48)
at computeIndentation (tsserver.js:112413:55)
at processChildNode (tsserver.js:112599:44)
at processChildNodes (tsserver.js:112651:48)
at tsserver.js:112543:21
at visitNodes (tsserver.js:16716:24)
at Object.forEachChild (tsserver.js:16899:21)
at processNode (tsserver.js:112540:20)
at processChildNode (tsserver.js:112600:21)
at tsserver.js:112541:21
at visitNode (tsserver.js:16711:24)
at Object.forEachChild (tsserver.js:16805:21)
at processNode (tsserver.js:112540:20)
at processChildNode (tsserver.js:112600:21)
at processChildNodes (tsserver.js:112651:48)
at tsserver.js:112543:21
at visitNodes (tsserver.js:16716:24)
at Object.forEachChild (tsserver.js:16955:24)
at processNode (tsserver.js:112540:20..
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #32487

### CODE REVIEW

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -326,8 +326,9 @@ namespace ts.formatting {
         export function argumentStartsOnSameLineAsPreviousArgument(parent: Node, child: TextRangeWithKind, childStartLine: number, sourceFile: SourceFileLike): boolean {
             if (isCallOrNewExpression(parent)) {
                 if (!parent.arguments) return false;
-
-                const currentNode = Debug.assertDefined(find(parent.arguments, arg => arg.pos === child.pos));
+                const currentNode = find(parent.arguments, arg => arg.pos === child.pos);
+                // If its not one of the argument, dont look past this
```
Comment (sandersn) [inline src/services/formatting/smartIndenter.ts]:
```suggestion
                // If it's not one of the arguments, don't look past this
```

File: tests/cases/fourslash/formatTypeArgumentOnNewLine.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
+/// <reference path="fourslash.ts"/>
+
+////const genericObject = new GenericObject<
+////  /*1*/{}
```
Comment (sandersn) [inline tests/cases/fourslash/formatTypeArgumentOnNewLine.ts]: this is the important one, right? Has anything changed for 2 or 3?

Comment (sheetalkamat) [reply tests/cases/fourslash/formatTypeArgumentOnNewLine.ts]: No change for 2 or 3 (as they were also blocked by the crash (since type argument is on different line from arguments)  I just added another test when there are multiple type arguments..

**Comment by sheetalkamat** [comment]
@typescript-bot cherry-pick this to release-3.7
