### PR TITLE
Fix destructuring evaluation order for initializers

### LINKED ISSUE #39181: Syntax error when lowering object rest into Object.assign
**TypeScript Version:** Nightly

**Search Terms:** object rest property binding Object.assign

**Code**

```ts
var y
({ x: { ...y } } = { x: { z: 1 } })
console.log(y.z === 1) // true
```

**Expected behavior:**

The code above should print `true` without crashing.

**Actual behavior:**

The TypeScript compiler generates this code when targeting ES2017 or below, which is invalid JavaScript:

```js
var y;
({ x: Object.assign({}, y) } = { x: { z: 1 } });
console.log(y.z === 1); // true
```

Attempting to run this code gives `Uncaught SyntaxError: Invalid destructuring assignment target` in V8.

Babel roughly generates this code, which works correctly:

```js
var y;
var _x = { x: { z: 1 } };
y = Object.assign({}, _x.x);
console.log(y.z === 1); // true
```

This came up because I'm trying to implement the [rest/spread proposal](https://github.com/tc39/proposal-object-rest-spread) for [esbuild](https://github.com/evanw/esbuild) by following what the TypeScript compiler does. I logged this issue when I discovered the TypeScript compiler isn't a correct implementation.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=Nightly#code/G4QwTgBAngUAFAbwgDwFwSQOm1CBffCAXgxXSQC90BGQvAShgGMB7AOwGcWAbAU024sA5nCiYKxIiWr0IAejkQALmACuvGEA)

**Related Issues:**

### LINKED ISSUE #39205: Incorrect side effect ordering in destructuring transform
**TypeScript Version:** Nightly

**Search Terms:** side effect ordering destructuring transform lowering spread rest binding pattern

**Code**

I recently implemented object rest properties for [esbuild](https://github.com/evanw/esbuild), a new TypeScript transpiler. When doing this I noticed several bugs with TypeScript's destructuring transform.

These bugs were identified by a [fuzzer for JavaScript destructuring](https://github.com/evanw/js-destructuring-fuzzer) that I wrote while developing the transform code for esbuild. The fuzzer generates random test cases and compares the execution of the transpiled code with the execution of the original JavaScript. You can see example output from the fuzzer [here](https://github.com/evanw/js-destructuring-fuzzer/blob/df033ba6e6d084c7de72cdcba64078317c8bac87/sample-output.txt).

This issue is for tracking bugs where expressions with side effects are accidentally reordered. There may be more than one individual bug in this class of bugs, and the fuzzer could be a good tool for finding them all.

Here's an example ordering issue:

```ts
let trace = []
let order = n => trace.push(n)
let [{ [order(1)]: x } = order(0)] = []
console.log(trace)
```

**Expected behavior:**

This should always print `[0, 1]`. Default values must always be evaluated before computed property keys.

**Actual behavior:**

The TypeScript transpiler generates code that correctly prints `[0, 1]` when targeting ES6 and above but generates code that incorrectly prints `[1, 0]` when targeting ES5 and below.

**Playground Link:** [link](https://www.typescriptlang.org/play/?target=1&ts=4.0.0-dev.20200622#code/DYUwLgBGBOCGDGIIF4IG0C6BYAUKSA9tACYjQoQB2KAfFHIgHQAOArgM4AWAFJQJS586AN7oipaNwCMfDAC4IADwgBfCuLLcADLIqZc8ApXYFQjYAQDm3GAhACcQA)

**Related Issues:** 

This ordering issue can also come up when targeting ES6, although the reproduction is a little more complicated:

```ts
let trace = []
let order = n => trace.push(n)
let { [order(0)]: { [order(2)]: y } = order(1), ...z } = {}
console.log(trace)
```

This prints `[0, 1, 2]` when run natively and prints `[0, 2, 1]` when transpiled with TypeScript targeting ES6.

Another ordering bug was mentioned in #39181:

```ts
var [{ ...a }, b = a] = [{ x: 1 }]
console.log(b.x === 1) // true
```

This should print `true` but crashes with `Uncaught TypeError: Cannot read property 'x' of undefined` when transpiled with TypeScript targeting ES6.

As I mentioned above, there may also be more ordering bugs like this depending on if these all have the same root cause or not. Hopefully the fuzzer will be a useful tool for getting to the bottom of these bugs.

### PR DESCRIPTION
**Pull request by rbuckton**
This ensures we correctly follow the order of evaluation for destructuring (initializers are evaluated *before* computed property names in an object pattern), per the following algorithms (**emphasis added**):

Fixes #39205
Fixes #39181

### CODE REVIEW

**Comment by evanw** [comment]
Thanks for working on this! I'm excited that this is going to be fixed.

FWIW it could be useful to double-check this PR with the fuzzer I wrote: https://github.com/evanw/js-destructuring-fuzzer. For example, I just ran this branch through the fuzzer and I think there are still cases that result in generating code with syntax errors. Here's one such case:

```js
let a, b, c = {x: {a: 1, y: 2}};
({x: {a, ...b} = foo} = c);
console.log(a, b);
```

That should print out `1 { y: 2 }` but instead I get `SyntaxError: Invalid left-hand side in assignment` with the code generated by the TypeScript compiler, which looks like this:

```js
var _a;
var a, b, c = { x: { a: 1, y: 2 } };
((_a = foo.a, foo, b = __rest(foo, ["a"]), foo) = c.x);
console.log(a, b);
```

**Comment by rbuckton** [comment]
@evanw: Thanks, I'll take a look at that

**Comment by rbuckton** [comment]
@weswigham @sandersn, either of you have a moment to spare to take a look?

**Review by weswigham — APPROVED** [review]
This emit looks OK (it's admittedly dense), but should we also be testing that control for narrowing reflects this order of execution as well? (Eg, replace `order(0)` with `(x, x = 0)` and so on)

**Comment by rbuckton** [comment]
Looks like control-flow is wrong as well:

##### Case 1

image

`y` should be `0` because the default is evaluated before the computed property name. 

##### Case 2
image

Here `y` should be `9` because the default evaluates first.

##### Cases 3 & 4
We also don't seem to narrow when we know the default *won't* be evaluated:

image
image

In both cases above, `y` should be `8` because the default will never be evaluated.

**Comment by rbuckton** [comment]
I've updated the control flow for destructuring, though I've decided to leave cases 3 & 4 as is (you will still end up with the union of the assigned value and the default value).

**Comment by rbuckton** [comment]
@weswigham can you take a look at the binder changes?

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -791,6 +800,13 @@ namespace ts {
                     bindPostfixUnaryExpressionFlow(<PostfixUnaryExpression>node);
                     break;
                 case SyntaxKind.BinaryExpression:
+                    if (isDestructuringAssignment(node)) {
+                        // Carry over whether we are in an assignment pattern to
+                        // binary expressions that could actually be an initializer
+                        inAssignmentPattern = saveInAssignmentPattern;
+                        bindDestructuringAssignmentFlow(node);
+                        return;
```
Comment (weswigham) [inline src/compiler/binder.ts:808]: You probably don't want to *return* here, and should instead just pop off the work item, as if you have something like `{ x = 2 } = y = {x: 0}` it's going to fail the bind the last half of the outer expression here, no?

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -791,6 +800,13 @@ namespace ts {
                     bindPostfixUnaryExpressionFlow(<PostfixUnaryExpression>node);
                     break;
                 case SyntaxKind.BinaryExpression:
+                    if (isDestructuringAssignment(node)) {
```
Comment (weswigham) [inline src/compiler/binder.ts:803]: Doesn't this need to be a (bail) case within `bindBinaryExpressionFlow` to handle when an inner binary expression is a restructuring assignment?

Comment (rbuckton) [reply src/compiler/binder.ts:803]: I've updated to have `maybeBind` exclude destructuring assignments so that it goes through the regular `bind` flow (and thus hits the escape above).

Comment (rbuckton) [reply src/compiler/binder.ts:803]: I've also added test cases for the destructuring assignment appearing on either side of a binary expression.

**Review by weswigham — APPROVED** [review]
