### PR TITLE
Ensure generated property names for methods named "new" are quoted

### LINKED ISSUE #55075: Declaration for object with method named "new" incorrectly emitted with construct signature
# Bug Report

### 🔎 Search Terms
declaration emit; method named "new"; construct signature

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about declaration emit, construct signatures
(note: some of this actually changed between TS3.7 and TS3.8, but the behavior in TS3.7 still has the main problem)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230718#code/KYDwDg9gTgLgBAYwgOwM7wIZwLxwN4BQccywA7gBQgBcJArgLYBGwUAlPnFMDHVMnBBwA1HACMcAL4FpoSLEQp0cJjnxE4AIlJlNVWskYt2nbr36CR4qTIJzo8JGkdrCxANrbymgLr76zKwceFw8fAJCohLS0gQA9HFwACoAygDMAHQAHMLxAFRw9goAJsAIADYY3IrOcBi0bsQk5P6GgewGRqwA3DK9RfClFVXANcpMDRrEOq1dHQHGvZL94A5wQ5XVTsoIk03NlDQLQZ3tS71weXEE8YmpmQDsALT5haslZZuj25h7TTNHNrGNinRZ9OzvQafEZjeATdT7Ly6WbtEHHKDnCHyKHDLZKRx-DxI3wo4Ggnrg4hXAhAA)

### 💻 Code

```ts
export const a = {
  new(x: number) { return x + 1 }
}
export const b = {
  "new"(x: number) { return x + 1 }
}
export const c = {
  ["new"](x: number) { return x + 1 }
}
```

### 🙁 Actual behavior

The .d.ts file emitted is:
```ts
export declare const a: {
    new(x: number): number;
};
export declare const b: {
    new(x: number): number;
};
export declare const c: {
    new(x: number): number;
};
```
a construct signature that the actual object doesn't have.  (For TS 3.7 and below, `b` and `c` are emitted as-is with quotes/brackets so there's no problem there.  But `a` is still wrong.) If you consume this declaration weird things happen.

### 🙂 Expected behavior

Probably for this case `new` should be emitted as either `"new"` or `["new"]` or something for all three cases:
```ts
export declare const a: {
    "new"(x: number): number;
};
```

Cross-linking to [relevant Stack Overflow question](https://stackoverflow.com/q/76715399/2887218)

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #55075
Closes #55109

This effectively replaces #55109, instead using a fix in `createPropertyNameNodeForIdentifierOrLiteral` instead of the emitter. If you look at the last commit, you'll see that the only change to TS emit was removed, which I believe to be correct as the code was able to be written that way in the first place so should be legal.

While I was here, I made the parameters to `createPropertyNameNodeForIdentifierOrLiteral` required, which showed that there was an existing bug for this in a code fix. Likely I need a test for this. It also shows that this call doesn't respect `stringNamed` either, which unfortunately requires some type info I didn't look into getting quite yet.

cc @Andarist

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8213,16 +8213,17 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
                 return fromNameType;
             }
             const rawName = unescapeLeadingUnderscores(symbol.escapedName);
-            return createPropertyNameNodeForIdentifierOrLiteral(rawName, getEmitScriptTarget(compilerOptions), singleQuote, stringNamed);
+            return createPropertyNameNodeForIdentifierOrLiteral(rawName, getEmitScriptTarget(compilerOptions), singleQuote, stringNamed, isMethod);
         }
 
         // See getNameForSymbolFromNameType for a stringy equivalent
-        function getPropertyNameNodeForSymbolFromNameType(symbol: Symbol, context: NodeBuilderContext, singleQuote?: boolean, stringNamed?: boolean) {
+        function getPropertyNameNodeForSymbolFromNameType(symbol: Symbol, context: NodeBuilderContext, singleQuote: boolean, stringNamed: boolean, isMethod: boolean) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:8226]: Idle observation: Lint rule for functions with optional parameters which are never not supplied? 🤔

**Review by RyanCavanaugh — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/checker.ts:8226]: Probably better as some external pass, as ts-eslint doesn't really do stuff cross-project. Technically possible with the new ProjectService thing, maybe.
