### PR TITLE
Ensure parameters are in scope when converting parameter/return types to type nodes

### LINKED ISSUE #48783: `globalThis` sometimes being stripped from type emition can leads to errors in emited definition
# Bug Report

### 🔎 Search Terms

globalThis, removed, remove, stripped, 2502, own type annotation, referenced, definition, .d.ts

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, since 3.5.1, and I reviewed the FAQ for entries about globalThis, 2502, own type annotation

### ⏯ Playground Link

[Playground link with relevant code, mainly using the `D.TS` tab](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220420#code/PTAEDoBNwFwZ1AMwJYBsCmoDmyBu64AoEUAckXRgGMALU0ZBAJ3QpYDsr1JRJkWqMVAE9QAeyYN2fAUNHJ2DeOIDuimMIAOmAIbt2YmDpjIx7cKAAUAJgCsABmsBKYmHQAPTRJi90VVDosoFRmcD4U1DQAymIAtpQ0ClgAXFYRtKka2mKISJS0TqAAvAB8oFnoOXmRANyEHl5MPiHsYdW0MfEwiexYxVaEAJDpNJlalblYqGIARjqoACqJcOAjhE5j2ZPTc4vLq-k0xWVrrqBLjKAqEgDWgWIArtJXt3AANKAABlOz8xdwnwYCE0LDg6HYMHqnm8wVC4UOnQSSQA6rckqlLCNNhNsDs-vsRoVSuVxlUfrt-gdIv1MYciSdDnUzv9QDd0OhNAhkMpvni9oxASw2OCuFDGj4KqAAGIIuJI3r9ADeQyxJK2uN+-JWawAvoQxTD-Do4AgZZFEd0kgBhAIm0DK4aHAD82LJfMpuv1DRhkrNHTllt6UqeglMiiKaUOru2mo9dOOapx5PxjCptCAA)

### 💻 Code

```ts
export const fetchSomething = (
	fetch: typeof globalThis.fetch
): typeof globalThis.fetch => fetch
```

### 🙁 Actual behavior

This code will generate the following `.d.ts` file, which contains the `'fetch' is referenced directly or indirectly in its own type annotation. (2502)` error
```ts
export declare const fetchSomething: (fetch: typeof fetch) => typeof fetch;
```

### 🙂 Expected behavior

Generated d.ts file should keep the reference to `globalThis`
```ts
export declare const fetchSomething: (fetch: typeof globalThis.fetch) => typeof globalThis.fetch;
```
as it does when declaring a function, type or class:
```ts
export type FetchSomething = {
	fetch: typeof globalThis.fetch
}

export class FetchSomethingClass {
	fetch?: typeof globalThis.fetch
}

export type FetchSomethingFunction = (fetch: typeof globalThis.fetch) => typeof globalThis.fetch

// .d.ts
export declare type FetchSomething = {
    fetch: typeof globalThis.fetch;
};
export declare class FetchSomethingClass {
    fetch?: typeof globalThis.fetch;
}
export declare type FetchSomethingFunction = (fetch: typeof globalThis.fetch) => typeof globalThis.fetch;

```

### :thinking:  Workaround

Typing the const instead of the anonymous function works as expected.
```ts
export const fetchSomething: (fetch: typeof globalThis.fetch) => typeof globalThis.fetch = (fetch) => fetch;
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #48783

### CODE REVIEW

File: tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit1.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ declare const couldntThinkOfAny: {};
  * @param {InstanceType<BaseFactory["Base"]>} base
  * @returns {InstanceType<BaseFactory["Base"]>}
  */
-declare function test(base: InstanceType<BaseFactory["Base"]>): InstanceType<BaseFactory["Base"]>;
+declare function test(base: InstanceType<BaseFactory["Base"]>): {};
```
Comment (jakebailey) [inline tests/baselines/reference/jsDeclarationsParameterTagReusesInputNodeInEmit1.js:89]: This isn't quite right; will look.

File: tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.js [hunk 2]
```diff
@@ -96,4 +96,69 @@ export const testFnTypes: {
 export namespace testFnTypes {
     type input = boolean | myTypes.typeC;
 }
+export namespace testFnTypes {
+    type input = boolean | myTypes.typeC;
+}
 import { myTypes } from "./file.js";
+
+
+//// [DtsFileErrors]
```
Comment (jakebailey) [inline tests/baselines/reference/jsDeclarationsImportAliasExposedWithinNamespaceCjs.js:105]: This shouldn't have been turned into an error, will check.

File: tests/baselines/reference/jsDeclarationsFunctions.js [hunk 3]
```diff
@@ -173,6 +173,6 @@ export function g(a: {
 declare function hh(a: {
     x: string;
 }, b: {
-    y: typeof b;
+    y: typeof import(".").b;
```
Comment (jakebailey) [inline tests/baselines/reference/jsDeclarationsFunctions.js:176]: This is suspicious; the code above says defines param `b`'s type as `{y: typeof b}` , which is self referential and surely wrong.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this

File: tests/baselines/reference/blockScopedVariablesUseBeforeDef.types [hunk 4]
```diff
@@ -70,12 +70,12 @@ function foo5() {
     let x = () => y;
 >x : () => () => any
 >() => y : () => () => any
->y : () => () => any
+>y : () => any
```
Comment (jakebailey) [inline tests/baselines/reference/blockScopedVariablesUseBeforeDef.types:73]: This comes from:

```
function foo5() {
    let x = () => y;
    let y = () => x;
}
```

So, it's just where this infinite recursion ends; the tooltip says something else entirely too.

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
I haven't reviewed the code yet, but I am weirded out by the whitespace changes -- which are admittedly the same as in #37444. But why insert 3 more spaces in, say, `left` and `right` below? It doesn't correspond to initial 4-space indent -- `top` is indented 8 spaces -- and `left` and `right` are only preceded by one space in the source.

```ts
module A {

    class Point {
        constructor(public x: number, public y: number) { }
    }

    export var UnitSquare : {
        top: { left: Point, right: Point },
        bottom: { left: Point, right: Point }
    } = null;
}
```

**Comment by jakebailey** [comment]
I think before it was creating an all new type node and in doing so put the code onto one line. But after, it's reusing the node, and so it has the spacing as the original source. The baselines just remove the newlines so it looks awkwardly spaced.

I'd test on the above pack-this, but it looks like typescript-staging is down :(

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -5880,6 +5880,24 @@ namespace ts {
...
+                // us to believe that we can emit "typeof paramName" instead, even though that would refer to the parameter,
+                // not the global. Make sure we are in the right scope by changing the enclosingDeclaration to the function.
+                //
+                // We check that this signature's declaration is within the existing enclosing declaration so we don't pull
+                // in types from other files; if it is outside of the enclosing declaration, then we shouldn't be able to
+                // access those parameter types via typeof anyway. The declaration should also not be in a JS file; those can
+                // only be typed via JSDoc, but JSDoc annotations appear outside of the function and therefore are not in
+                // the function's scope, unlike true type annotations.
+                const saveEnclosingDeclaration = context.enclosingDeclaration;
+                if (signature.declaration && !isInJSFile(signature.declaration) && saveEnclosingDeclaration && findAncestor(signature.declaration, (n) => n === saveEnclosingDeclaration)) {
```
Comment (jakebailey) [inline src/compiler/checker.ts:5897]:
```suggestion
                if (signature.declaration && !isInJSFile(signature.declaration) && saveEnclosingDeclaration && findAncestor(signature.declaration, n => n === saveEnclosingDeclaration)) {
```

Comment (jakebailey) [reply src/compiler/checker.ts:5897]: ugh github never lets me apply these

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -5880,6 +5880,24 @@ namespace ts {
...
+                // us to believe that we can emit "typeof paramName" instead, even though that would refer to the parameter,
+                // not the global. Make sure we are in the right scope by changing the enclosingDeclaration to the function.
+                //
+                // We check that this signature's declaration is within the existing enclosing declaration so we don't pull
+                // in types from other files; if it is outside of the enclosing declaration, then we shouldn't be able to
+                // access those parameter types via typeof anyway. The declaration should also not be in a JS file; those can
+                // only be typed via JSDoc, but JSDoc annotations appear outside of the function and therefore are not in
+                // the function's scope, unlike true type annotations.
+                const saveEnclosingDeclaration = context.enclosingDeclaration;
+                if (signature.declaration && !isInJSFile(signature.declaration) && saveEnclosingDeclaration && findAncestor(signature.declaration, n => n === saveEnclosingDeclaration)) {
```
Comment (weswigham) [inline src/compiler/checker.ts:5897]: I don't really like using the declaration from the signature over the context passed in - it may be in an entirely different file from the context where the signature is being emitted to, so will have potentially entirely incorrect results for things-that-aren't-immediately-parameters/type-parameters-of-the-signature. Instead we probably need to track the parameters we're serializing as we recur through multiple signatures - we already do this for type parameters in some cases. Similarly, we manufacture a fake node to use as a context in some places in the JS declaration builder that handles blocking/preserving scope variables like you'd want, since the real node doesn't exist (like how a `module.export.x = expr` needs a fake `module.exports` namespace declaration - passing in better initial contexts like this also sometimes an option.

Comment (jakebailey) [reply src/compiler/checker.ts:5897]: I was also concerned about this (it felt wrong entirely ignoring the context), but wasn't sure what to do instead. I'll try to come up something more like those other methods.

Comment (jakebailey) [reply src/compiler/checker.ts:5897]: > it may be in an entirely different file from the context where the signature is being emitted to, so will have potentially entirely incorrect results for things-that-aren't-immediately-parameters/type-parameters-of-the-signature (meaning it may allow references to locals in a separate file as though they're locals in the emitted file!)

Actually, just to clarify this, it was my impression that the ancestor check I've done here avoided that problem because it verifies that the current signature is a descendent of the current enclosing declaration.

This behavior is already not legal for declarations in other files because this involves `typeof` on the function itself. You can't directly do a `typeof` for a parameter that comes from an entirely different file (or even a different scope). The `findAncestor` check is what fixed that bug when I was working on this particular fix as there were some tests that did exhibit the bad behavior.

Comment (weswigham) [reply src/compiler/checker.ts:5897]: If the function comes from within another function, but is being serialized in the top level scope of a js file, the scopes in between are still inaccessible. So some scope structure like
```
function f() {
  return g;
  /** @returns {typeof h} */
  function g() { return h; }
  function h() {}
}

module.exports = f;
```
Though probably with parameter references to inner functions in some way.

Comment (jakebailey) [reply src/compiler/checker.ts:5897]: I'm not sure if this is quite what you were suggesting, but the following doesn't work with my PR:

```ts
export function foo() {
    const bar = (isNan: typeof globalThis.isNaN): typeof globalThis.isNaN => isNan

    function baz() {
        return bar;
    }

    return baz;
}
```

[Playground Link](https://www.staging-typescript.org/play?ts=4.8.0-pr-49627-10&ssl=11&ssc=2&pln=3&pc=1#code/FAehAIHUCcHsDsDmAucBnAFrArgGwCboCGAnuAAYAuJADgKawBm4iusARkbgCoYCWaAHQCAckRHlwdAG51oJAO4Y5dcH3jhKy8PkGU0wOgA8asaJXCNs8AMaU+CS7FgAKAJTgA3sHC-wNhDQLTmhwAF5wF1EieFRqeiYWNk4efiFokTc42gZmVg4uXgFhNDERcIA+NVKY4B8-K1t7R04AL3cver8-aDpKbGgNEIBuLvAAXzru3v7B8DbRycMTMwsA+CDwIgBGcMiM7IS85MK0krKszRzE-JSi9JrysKqM0eNTc39AiyIAJj2oo9DrkkgVUsUMgAaeZEaAAfmBNxO4IeF0RxzB93O4kqMNCcLh1TKbxWn3WmyIAGYAQdwPBsABbdhyaEhdGgu5nDKXeIg26nCGPXEjZYfNbfLYAFhpQLpjOZ0B51wxnMFZVx-JR2JEwyAA)

I'm not sure I can actually produce a counterexample in JS, though; JSDoc is exempt from this PR just because the scope accessible in a JSDoc comment is outside the declaration, not inside of it.

Comment (jakebailey) [reply src/compiler/checker.ts:5897]: Hm, probably not what you meant; I think this just fails because the enclosing declaration is not a parent of the signature (which this PR used to work around things).

File: src/compiler/transformers/declarations.ts [hunk 7]
```diff
@@ -677,15 +677,20 @@ namespace ts {
...
-            return isSourceFile(node)
-                || isTypeAliasDeclaration(node)
-                || isModuleDeclaration(node)
-                || isClassDeclaration(node)
-                || isInterfaceDeclaration(node)
-                || isFunctionLike(node)
-                || isIndexSignatureDeclaration(node)
-                || isMappedTypeNode(node);
+        function isEnclosingDeclaration(_node: Node) {
+            // TODO(jakebailey): Clean this up. If we look at the way that the "types"
```
Comment (weswigham) [inline src/compiler/transformers/declarations.ts:681]: Just as an FYI, this list is the nodes our old declaration emitter captured as enclosing declarations while recurring, not many other reasons for it.

Comment (jakebailey) [reply src/compiler/transformers/declarations.ts:681]: Just to clarify, do you agree with removing this entirely or the opposite?

This is just a leftover now, I'll probably not touch this (I needed it in a previous iteration but haven't yet removed it, this branch is big WIP right now)

Comment (weswigham) [reply src/compiler/transformers/declarations.ts:681]: There's no documented logic for why it's only *these* nodes which are/were captured - these are simply the only ones that were way back when the declaration emitter was string-based.

File: tests/baselines/reference/leaveOptionalParameterAsWritten.js [hunk 8]
```diff
@@ -32,6 +32,4 @@ declare global {
     }
 }
 //// [c.d.ts]
-declare type Foo = teams.calling.Foo;
-export declare const bar: (p?: Foo) => void;
```
Comment (jakebailey) [inline tests/baselines/reference/leaveOptionalParameterAsWritten.js:36]: This is a case that I'm pretty sure only worked because of a fluke. It's desirable, but when we get the type from the annotation, we get the interface type `Foo` in another file (the symbol is correctly resolved), but then this gets handed down and the info about it being an alias is completely lost. I think this only worked due to assumptions about the enclosing declaration that now no longer hold.

**Comment by jakebailey** [comment]
I've gotten this PR pretty far but I'm going to stop working on it for a while because it's getting too frustrating. It seems like this part of the code is really fragile when it comes to what it considers to be reusable in ways that I can't seem to keep in my head at once. If fix one thing and break something I fixed earlier, because I forgot what I did and ended up undoing it, etc.

The whole enclosing declaration thing in general weirds me out; it doesn't seem consistent at all which enclosing declaration is used in what scenario, and yet the types baseline code just always uses the parent node, which would lead me to believe that it doesn't need to even exist at all, either, but I'm sure I'm missing something.

**Comment by weswigham** [comment]
To be fair, I think the primary reason they're different is that the declaration emitter is eliding or rewriting a lot of scopes, while the types baselines aren't.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -7139,6 +7139,42 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                    /*name*/ undefined,
+                    /*typeParameters*/ undefined,
+                    [],
+                    /*type*/ undefined,
+                    factory.createBlock([]),
+                );
+
+                // TODO(jakebailey): Can we skip this if there are no parameters?
+                // This seems to bring back desirable node reuse, but I'd want to see
+                // functions with parameters fixed too.
```
Comment (jakebailey) [inline src/compiler/checker.ts:7172]: The answer here is yes, but it does come at a const of inconsistency in emit because going from zero parameters to one (or vice versa) may change the emitted return type entirely, like:

```diff
+>d2 : { foo(): {    x: number;}; }
->d2 : { foo(): { x: number; }; }
```

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -7139,6 +7139,42 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            // We can't use the declaration directly; it may be in another file and so we may lose access to symbols
+            // accessible to the current enclosing declaration, or gain access to symbols not accessible to the current
+            // enclosing declaration. To keep this chain accurate, clone the function as a non-synthesized node (so that
+            // it can be used as an enclosing declaration) and make its parent the current enclosing declaration.
+            //
+            // If the declaration is in a JS file, then we don't need to do this at all, as there are no annotations besides
+            // JSDoc, which are always outside the function declaration, so are not in the parameter scope.
+            const saveEnclosingDeclaration = context.enclosingDeclaration;
+            if (saveEnclosingDeclaration && signature.declaration && signature.declaration !== saveEnclosingDeclaration && !isInJSFile(signature.declaration)) {
+                const fakeScope = parseNodeFactory.createFunctionExpression(
```
Comment (jakebailey) [inline src/compiler/checker.ts:7160]: While this method does work, it has the downside of introducing a synthetic node into the declaration chain, and so when this happens, the emit suffers. I'm not sure of a better way; `isSymbolAccessible` currently seems to only use the enclosing declaration and its parents, so I don't know how to get this info into its scope.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Cool, seems like no performance change. I was worried. I think this is back and probably ready for review.

I've managed to fix most cases where we were unable to reuse the existing node, but a few remain. It's really funky because given:

```ts
interface I {
    f: <T>(a: { /*1*/T: number }, b: T) => T;
    g: (a: { /*2*/a: number }) => void;
}
```

We walk down to `a` and then find that there's another `a` in scope via the enclosing declaration and so we don't think we can reuse the node. Except, there's no way to actually refer to that inner `a` so it's just waste. I'm not quire sure how to detect this case but I can't seem to actually find an example where this becomes harmful (even though the code says that it might affect quickinfo; testing says no).

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot pack this

**Comment by jakebailey** [comment]
Forgive the force push; this had so many commits that I wanted to still be able to see the test diffs.

I've updated the logic to share the same node within the same chain instead of repeating it multiple times; I think it's about as fast as it can get.

I also dropped the added property on the context; it turns out that wasn't safe because it's technically possible that another part of the code temporarily changes the enclosing declaration, but we could then accidentally inject new variables into a different chain. Now, we just walk up the ancestors to find an existing one, creating one if needed.

File: tests/baselines/reference/declarationEmitGlobalThisPreserved.js [hunk 11]
```diff
@@ -168,125 +168,3 @@ export declare class AsClassProperty {
     isNaN?: typeof globalThis.isNaN;
 }
 export type AsFunctionType = (isNaN: typeof globalThis.isNaN) => typeof globalThis.isNaN;
-
-
-//// [DtsFileErrors]
```
Comment (jakebailey) [inline tests/baselines/reference/declarationEmitGlobalThisPreserved.js]: Note the the errors going away here; I constructed these tests such that they will emit a d.ts error when they're wrong, rather than us having to figure out if the output looks right or not.

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -7276,6 +7276,82 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                // more and more scopes that need to be searched in isSymbolAccessible later. Since
+                // all we really want to do is to mark certain names as unavailable, we can just
+                // keep all of the names we're introducing in one large table and push/pop from it as
+                // needed; isSymbolAccessible will walk upward and find the closest "fake" scope,
+                // which will conveniently report on any and all faked scopes in the chain.
+                //
+                // It'd likely be better to store this somewhere else for isSymbolAccessible, but
+                // since that API _only_ uses the enclosing declaration (and its parents), this is
+                // seems like the best way to inject names into that search process.
+                const existingFakeScope = findAncestor(context.enclosingDeclaration, node => !!getNodeLinks(node).fakeScopeForSignatureDeclaration);
```
Comment (weswigham) [inline src/compiler/checker.ts:7315]: I struggle to think of when you'd have another synthetic scope set as the child scope of an existing fake scope now. Maybe this can just be `!!getNodeLinks(context.enclosingDeclaration).fakeScopeForSignatureDeclaration` ?

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -7996,13 +8073,17 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             return !(getObjectFlags(type) & ObjectFlags.Reference) || !isTypeReferenceNode(existing) || length(existing.typeArguments) >= getMinTypeArgumentCount((type as TypeReference).target.typeParameters);
         }
 
+        function getEnclosingDeclarationIgnoringFakeScope(enclosingDeclaration: Node) {
+            return findAncestor(enclosingDeclaration, n => !getNodeLinks(n).fakeScopeForSignatureDeclaration);
```
Comment (weswigham) [inline src/compiler/checker.ts:8077]: Likewise, I think this should only need to check the immediate `enclosingDeclaration` now.

File: src/compiler/checker.ts (hunk 12 above)
Comment (jakebailey) [reply src/compiler/checker.ts:7315]: The case I'm worried about is the other places we reassign `context.enclosingDeclaration` temporarily, which happens in `serializeTypeAlias`, `sanitizeJSDocImplements`, `serializeAsClass`, `addPropertyToElementList`, etc.

I'd have to come up with an example of this, though.

File: src/compiler/checker.ts (hunk 13 above)
Comment (jakebailey) [reply src/compiler/checker.ts:8077]: Could be, though if that's the case, it'll only walk one node upward so I'm not sure I want to write it less conveniently...

File: src/compiler/checker.ts (hunk 12 above)
Comment (jakebailey) [reply src/compiler/checker.ts:7315]: Okay, it does work to only ever check the most immediate enclosing declaration, at least in the the current tests. I would have thought it'd break, but examining things again, I can't actually figure out a counterexample here, so I'll switch things again.

Comment (jakebailey) [reply src/compiler/checker.ts:7315]: And to clarify, I did add an assert that verifies that there aren't more than 1 fake scope in a given chain, and it never fired, so that's proof enough I suppose.

Comment (jakebailey) [reply src/compiler/checker.ts:7315]: Switched to only check the current enclosingDeclaration.

File: src/compiler/checker.ts (hunk 13 above)
Comment (jakebailey) [reply src/compiler/checker.ts:8077]: Switched this to a simple ternary.

**Comment by jakebailey** [comment]
@typescript-bot perf test faster

**Review by weswigham — APPROVED** [review]

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -7276,6 +7276,86 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            //
+            // If the declaration is in a JS file, then we don't need to do this at all, as there are no annotations besides
+            // JSDoc, which are always outside the function declaration, so are not in the parameter scope.
+            let cleanup: (() => void) | undefined;
+            if (
+                context.enclosingDeclaration
+                && signature.declaration
+                && signature.declaration !== context.enclosingDeclaration
+                && !isInJSFile(signature.declaration)
+                && some(expandedParams)
```
Comment (sandersn) [inline src/compiler/checker.ts:7301]: getExpandedParameters looks like it always returns an array of length 1, at least unless the rest type is somehow a 0-constituent union, but I think those are always impossible.

If the check is there just because the types could allow an empty array, maybe it should be an assert in the body of the `if` instead.

File: src/compiler/checker.ts (hunk 12 above)
Comment (sandersn) [reply src/compiler/checker.ts:7315]: Just started reviewing this -- does this mean the comment block above also needs to be simplified?

**Review by sandersn — COMMENTED** [review]
I don't think I understand the overall flow of creating a signature declaration enough to properly sign off, but I did have a couple of questions after reading the code.

File: src/compiler/checker.ts (hunk 12 above)
Comment (jakebailey) [reply src/compiler/checker.ts:7315]: Yes, let me fix the wording. Most of it still applies but now there's only one fake scope.

File: src/compiler/checker.ts (hunk 14 above)
Comment (jakebailey) [reply src/compiler/checker.ts:7301]: Check above, and you'll see:

```ts
const expandedParams = getExpandedParameters(signature, /*skipUnionExpanding*/ true)[0];
```

Comment (jakebailey) [reply src/compiler/checker.ts:7301]: (Later I might see if we can avoid constructing a bunch of random arrays we don't need...
