### PR TITLE
Revise logic that computes the contextual type for a parameter

### LINKED ISSUE #26099: Incorrect parameter type inference when explicitly specifying type of `this` along with tuple params.
**TypeScript Version:**  3.0.1 & 3.1.0-dev.20180731

**Search Terms:** parameter type inference explicit this

**Code**

```ts
class Client {

    get(id: number) { return fetch(`/person/${id}`) }
    list() { return fetch("/person/list") }

    makeCaller<TArgs extends any[], TResult>(
        invoker: (this: any, client: this, ...args: TArgs) => Promise<Response>
    ): (...args: TArgs) => Promise<Response> {
        // Implementation omitted...
        return null as any as (...args: TArgs) => Promise<Response>
    }
}


class Module {
    // For each example, look at type of the parameters in the intellisense tooltip:

    // Incorrect: c typed as `number` (id is correct, though) in both 3.0.1 & 3.1.0-dev.20180731
    // Note that mousing over `.get` in the body correctly shows `Client.get` in the tooltip,
    // but does not show params or return type.
    caller1 = new Client().makeCaller(function (this: Module, c, id: number) {
        return c.get(id)
    })

    // Incorrect: c typed as `never` in 3.0.1 & as `any` in 3.1.0-dev.20180731
    // Note that mousing over `.list` in the body correctly shows `Client.list`, 
    // but does not show return type.
    caller2 = new Client().makeCaller(function (this: Module, c) {
        return c.list()
    })

    // Correct: c typed as `Client`, and `.list` correctly shows its return type in the tooltip.
    caller3 = new Client().makeCaller(function (c) {
        return c.list()
    })

    // Correct: c typed as `Client`, id as `number`, and `.get` correctly shows its return type in the tooltip.
    caller4 = new Client().makeCaller(function (c, id: number) {
        return c.get(id)
    })

    // Correct: c typed as `Client`, and `.list` correctly shows its return type in the tooltip.
    caller5 = new Client().makeCaller(c => c.list())
}
```

**Expected behavior:** In all 5 cases in class `Module`, parameter `c` should be inferred to be type `Client`

**Actual behavior:** In cases where the type of `this` is specified, the type of `c` is inferred incorrectly for tooltips. Only the functions which do not have an explicit `this` type declared are correct. Note that no compilations errors are present, and for example in `caller1`, TS does seem to understand at some level that `c` is of type `Client` - there's no error about trying to access member `get` on type `number`.

image

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=class%20Client%20%7B%0D%0A%0D%0A%20%20%20%20get(id%3A%20number)%20%7B%20return%20fetch(%60%2Fperson%2F%24%7Bid%7D%60)%20%7D%0D%0A%20%20%20%20list()%20%7B%20return%20fetch(%22%2Fperson%2Flist%22)%20%7D%0D%0A%0D%0A%20%20%20%20makeCaller%3CTArgs%20extends%20any%5B%5D%2C%20TResult%3E(%0D%0A%20%20%20%20%20%20%20%20invoker%3A%20(this%3A%20any%2C%20client%3A%20this%2C%20...args%3A%20TArgs)%20%3D%3E%20Promise%3CResponse%3E%0D%0A%20%20%20%20)%3A%20(...args%3A%20TArgs)%20%3D%3E%20Promise%3CResponse%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20Implementation%20omitted...%0D%0A%20%20%20%20%20%20%20%20return%20null%20as%20any%20as%20(...args%3A%20TArgs)%20%3D%3E%20Promise%3CResponse%3E%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aclass%20Module%20%7B%0D%0A%20%20%20%20%2F%2F%20For%20each%20example%2C%20look%20at%20type%20of%20the%20parameters%20in%20the%20intellisense%20tooltip%3A%0D%0A%0D%0A%20%20%20%20%2F%2F%20Incorrect%3A%20c%20typed%20as%20%60number%60%20(id%20is%20correct%2C%20though)%20in%20both%203.0.1%20%26%203.1.0-dev.20180731%0D%0A%20%20%20%20%2F%2F%20Note%20that%20mousing%20over%20%60.get%60%20in%20the%20body%20correctly%20shows%20%60Client.get%60%20in%20the%20tooltip%2C%0D%0A%20%20%20%20%2F%2F%20but%20does%20not%20show%20params%20or%20return%20type.%0D%0A%20%20%20%20caller1%20%3D%20new%20Client().makeCaller(function%20(this%3A%20Module%2C%20c%2C%20id%3A%20number)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20c.get(id)%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20%2F%2F%20Incorrect%3A%20c%20typed%20as%20%60never%60%20in%203.0.1%20%26%20as%20%60any%60%20in%203.1.0-dev.20180731%0D%0A%20%20%20%20%2F%2F%20Note%20that%20mousing%20over%20%60.list%60%20in%20the%20body%20correctly%20shows%20%60Client.list%60%2C%20%0D%0A%20%20%20%20%2F%2F%20but%20does%20not%20show%20return%20type.%0D%0A%20%20%20%20caller2%20%3D%20new%20Client().makeCaller(function%20(this%3A%20Module%2C%20c)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20c.list()%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20%2F%2F%20Correct%3A%20c%20typed%20as%20%60Client%60%2C%20and%20%60.list%60%20correctly%20shows%20its%20return%20type%20in%20the%20tooltip.%0D%0A%20%20%20%20caller3%20%3D%20new%20Client().makeCaller(function%20(c)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20c.list()%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20%2F%2F%20Correct%3A%20c%20typed%20as%20%60Client%60%2C%20id%20as%20%60number%60%2C%20and%20%60.get%60%20correctly%20shows%20its%20return%20type%20in%20the%20tooltip.%0D%0A%20%20%20%20caller4%20%3D%20new%20Client().makeCaller(function%20(c%2C%20id%3A%20number)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20c.get(id)%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20%2F%2F%20Correct%3A%20c%20typed%20as%20%60Client%60%2C%20and%20%60.list%60%20correctly%20shows%20its%20return%20type%20in%20the%20tooltip.%0D%0A%20%20%20%20caller5%20%3D%20new%20Client().makeCaller(c%20%3D%3E%20c.list())%0D%0A%7D)

**Related Issues:**  Found a few related to parameter type inference, but nothing at all that were specifically about breakages when explicitly specifying the type of `this`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #26099.

### CODE REVIEW

File: tests/cases/fourslash/contextuallyTypedParameters.ts [hunk 1]
```diff
@@ -0,0 +1,60 @@
+/// <reference path='fourslash.ts' />
+
+////declare function foo(cb: (this: any, x: number, y: string, z: boolean) => void): void;
+////
+////foo(function(this, a, ...args) {
```
Comment (sandersn) [inline tests/cases/fourslash/contextuallyTypedParameters.ts]: Why write this is a fourslash test? Wouldn't the type baselines provide enough information to tell what the contextual type was?

Comment (RyanCavanaugh) [reply tests/cases/fourslash/contextuallyTypedParameters.ts]: The problem only occurred when we were hovering in to get the type -- type baselines work "top down" like the commandline compiler and do not observe the problematic behavior
