### PR TITLE
Fix bug when name resolution fails in a @typedef: Don't set `lastLocation`

### LINKED ISSUE #24577: Debug Failure. False expression in TS 2.9
**TypeScript Version:**  2.9.1

**Search Terms:**  Module build failed: Error: Debug Failure. False expression. lastLocation.kind 273

**Code**

```ts
// hard to do a *self-contained* demonstration of the problem :(
```

**Expected behavior:**
Should compile without fail :)

**Actual behavior:**
Just updated typescript from 2.8.4 to 2.9.1 and got this error:

```
ERROR in ./node_modules/2gl/src/Buffer.js
Module build failed: Error: Debug Failure. False expression.
    at resolveNameHelper (path\node_modules\typescript\lib\typescript.js:27846:30)
    at resolveName (path\node_modules\typescript\lib\typescript.js:27600:20)
    at resolveEntityName (path\node_modules\typescript\lib\typescript.js:28415:26)
    at resolveEntityName (path\node_modules\typescript\lib\typescript.js:28423:35)
    at resolveTypeReferenceName (path\node_modules\typescript\lib\typescript.js:33678:20)
    at getTypeFromTypeReference (path\node_modules\typescript\lib\typescript.js:33839:30)
    at getTypeFromTypeNode (path\node_modules\typescript\lib\typescript.js:35132:28)
    at Object.map (path\node_modules\typescript\lib\typescript.js:2025:29)
    at getTypeFromUnionTypeNode (path\node_modules\typescript\lib\typescript.js:34271:54)
    at getTypeFromTypeNode (path\node_modules\typescript\lib\typescript.js:35144:28)
    at getTypeOfVariableOrParameterOrProperty (path\node_modules\typescript\lib\typescript.js:30950:41)
    at getTypeOfSymbol (path\node_modules\typescript\lib\typescript.js:31174:24)
    at checkPropertyAccessExpressionOrQualifiedName (path\node_modules\typescript\lib\typescript.js:42269:53)
    at checkPropertyAccessExpression (path\node_modules\typescript\lib\typescript.js:42224:20)
    at checkExpressionWorker (path\node_modules\typescript\lib\typescript.js:45590:28)
    at checkExpression (path\node_modules\typescript\lib\typescript.js:45536:42)
    at checkExpressionWithContextualType (path\node_modules\typescript\lib\typescript.js:45371:26)
    at checkApplicableSignature (path\node_modules\typescript\lib\typescript.js:43018:25)
    at chooseOverload (path\node_modules\typescript\lib\typescript.js:43510:26)
    at resolveCall (path\node_modules\typescript\lib\typescript.js:43420:26)
    at resolveCallExpression (path\node_modules\typescript\lib\typescript.js:43635:20)
    at resolveSignature (path\node_modules\typescript\lib\typescript.js:43871:28)
    at getResolvedSignature (path\node_modules\typescript\lib\typescript.js:43914:26)
    at checkCallExpression (path\node_modules\typescript\lib\typescript.js:44001:29)
    at checkExpressionWorker (path\node_modules\typescript\lib\typescript.js:45599:28)
    at checkExpression (path\node_modules\typescript\lib\typescript.js:45536:42)
    at path\node_modules\typescript\lib\typescript.js:42679:21
    at Object.forEach (path\node_modules\typescript\lib\typescript.js:1792:30)
    at resolveUntypedCall (path\node_modules\typescript\lib\typescript.js:42678:20)
    at resolveErrorCall (path\node_modules\typescript\lib\typescript.js:42685:13)
    at resolveCallExpression (path\node_modules\typescript\lib\typescript.js:43604:24)
    at resolveSignature (path\node_modules\typescript\lib\typescript.js:43871:28)
    at getResolvedSignature (path\node_modules\typescript\lib\typescript.js:43914:26)
    at checkCallExpression (path\node_modules\typescript\lib\typescript.js:44001:29)
    at checkExpressionWorker (path\node_modules\typescript\lib\typescript.js:45599:28)
    at checkExpression (path\node_modules\typescript\lib\typescript.js:45536:42)
     @ ./src/map/gpuStorage.ts 3:0-32 114:25-31 115:26-32
     @ ./src/map/index.ts
     @ ./src/map/ui.ts
     @ ./src/index.ts
```

We use webpack@4 with ts-loader@4 and got this error. It happens with node8 and node10 on windows, macos and linux. It compiles without error in typescript 2.8, 2.7 etc.

I went to `resolveNameHelper` (\node_modules\typescript\lib\typescript.js:27843) and find the assert line:

```js
 ts.Debug.assert(lastLocation.kind === 273 /* SourceFile */);
```

I've added a condition before it:

```js
if (lastLocation.kind !== 273) {
    console.log(lastLocation.kind);
}
```

And got `296`. I don't know what it means but tell me how I can help further.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #24577

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1458,9 +1458,8 @@ namespace ts {
                     case SyntaxKind.JSDocTypedefTag:
                     case SyntaxKind.JSDocCallbackTag:
                         // js type aliases do not resolve names from their host, so skip past it
-                        lastLocation = location;
-                        location = getJSDocHost(location).parent;
-                        continue;
+                        location = getJSDocHost(location);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Note: we still go to `.parent` a few lines down in the usual way, so the only effect is on `lastLocation`.

File: tests/baselines/reference/jsdocResolveNameFailureInTypedef.errors.txt [hunk 2]
```diff
@@ -0,0 +1,19 @@
+error TS5055: Cannot write file '/a.js' because it would overwrite input file.
```
Comment (sandersn) [inline tests/baselines/reference/jsdocResolveNameFailureInTypedef.errors.txt]: I usually add `@noEmit: true` to avoid this warning.
