### PR TITLE
Fix const enum comments

### LINKED ISSUE #47982: unexpected code generated from `const enum`
# Bug Report

The name of const enum is not escaped and is inserted directly into the output as a comment

### 🔎 Search Terms

- const enum
- comments

### 🕗 Version & Regression Information

N/A

### ⏯ Playground Link

- [Broken Code Playground]

- [Wrong Result Playground]

[broken code playground]: https://www.typescriptlang.org/play?target=99&jsx=0#code/MYewdgzgLgBApmArgWxgMRCGBvAUDAmAIgCoB6IgGn0KLJKNwF9ddRIQAbOAOk5ADmACgwgA2qQoBdAJS4gA
[wrong result playground]: https://www.typescriptlang.org/play?target=99&jsx=0#code/MYewdgzgLgBApmArgWxgMRCGBvAUDAmAIgCoB6AGgEYBKCmUSEAGzgDpmQBzACgHIAFnGac+NANwwyZIhXyFSZANQwALAAYyJIjAC8MAExyAvrlyMILdp14YQAbUXU6DcJdYdu-ISJBjJ0kQAujTmblaetpiO5CoaWsGhQA

### 💻 Code

[Broken Code Playground][broken code playground]

```typescript
const enum Foo {
  "*/",
  "/*",
}

console.log(Foo["*/"]);
```

---

[Wrong Result Playground][wrong result playground]

```typescript
const enum Foo {
  "*/,1), console.log('hello'); //",
  "*/+ 40/*" = 2,
}

console.log(Foo["*/,1), console.log('hello'); //"]);
console.log(Foo["*/+ 40/*"]);
```

### 🙁 Actual behavior

[Broken Code Playground][broken code playground]

```javascript
console.log(0 /* "*/" */);
```

---

[Wrong Result Playground][wrong result playground]

```javascript
console.log(0 /* "*/, 1), console.log("hello"); //" */);
console.log(2 /* "*/ + 40 /*" */);
```

### 🙂 Expected behavior

[Broken Code Playground][broken code playground]

```javascript
console.log(0);
```

[Wrong Result Playground][wrong result playground]

```javascript
console.log(0);
console.log(2);
```

It is OK to escape the enum name and use it as a comment.

### PR DESCRIPTION
**Pull request by magic-akari**
Fixes #47982

### CODE REVIEW

File: src/compiler/transformers/ts.ts [hunk 1]
```diff
@@ -3364,7 +3368,7 @@ namespace ts {
                         ? declarationNameToString(originalNode.name)
                         : getTextOfNode(originalNode.argumentExpression);
```
Comment (DanielRosenwasser) [inline src/compiler/transformers/ts.ts:3369]: Move the function call to this line so that the common case (where a user has written a property access and isn't trying to sabotage the emitter 😄) doesn't have to run through a regex

**Review by sandersn — APPROVED** [review]
