### PR TITLE
Don't error when function has an implicit return but its return type is assignable to `undefined`

### LINKED ISSUE #53473: TS2366: Function lacks ending return statement in function with `unknown` return type with implicit return on some code paths, despite `noImplicitReturns` turned off
# Bug Report

### 🔎 Search Terms

lacks ending

### 🕗 Version & Regression Information

- This changed between versions 5.0.2 and 5.1.0-dev.20230323

I believe [this](https://github.com/microsoft/TypeScript/pull/53092/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8L35565-R35570) caused it.

### ⏯ Playground Link

https://www.typescriptlang.org/play?noImplicitReturns=false&ts=5.1.0-dev.20230323#code/GYVwdgxgLglg9mABFApgZygCgJQC5HgDWYcA7kgN4CwAUAJAzCKYCyAhlABYB0ATm2AAmcALY5EAPkQAGbgFZsiXiigheSKLxAoA3LQC+QA

### 💻 Code

```ts
function test(): unknown {
	if (Math.random() > 0.5) return true;
}
```

### 🙁 Actual behavior

```
> tsc --noEmit

index.ts:1:18 - error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

1 function test(): unknown {
                   ~~~~~~~
```

### 🙂 Expected behavior

No error, if the function return type is `unknown` I'd expect that to allow implicit return of `undefined`.

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #53473

### CODE REVIEW

File: tests/cases/compiler/functionsWithImplicitReturnTypeAssignableToUndefined.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+// @noImplicitReturns: false
+// @strictNullChecks: false
```
Comment (jakebailey) [inline tests/cases/compiler/functionsWithImplicitReturnTypeAssignableToUndefined.ts:2]: FYI you can write:

```ts
// @strictNullChecks: true, false
```

To let the test runner test both cases for the same file.

Comment (MariaSolOs) [reply tests/cases/compiler/functionsWithImplicitReturnTypeAssignableToUndefined.ts:2]: Oh, @DanielRosenwasser did use that [here](https://github.com/microsoft/TypeScript/issues/53473#issuecomment-1482016108) but I didn't know that was an actual feature. Neat.

File: tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefinedStrictNullChecks.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
+//// [functionsWithImplicitReturnTypeAssignableToUndefinedStrictNullChecks.ts]
```
Comment (jakebailey) [inline tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefinedStrictNullChecks.js:1]: Note that old baselines are not deleted by default; you'll want to remove these baselines that no longer map to any test.

Comment (MariaSolOs) [reply tests/baselines/reference/functionsWithImplicitReturnTypeAssignableToUndefinedStrictNullChecks.js]: Ah, the more I learn. Hopefully the third time's the charm.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -35686,7 +35686,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                     error(errorNode, Diagnostics.A_function_whose_declared_type_is_neither_void_nor_any_must_return_a_value);
                 }
             }
-            else if (type && strictNullChecks) {
+            else if (type && strictNullChecks && !isTypeAssignableTo(undefinedType, type)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:35689]: Do we want to go with this, or do we want to go with expanding the checks above?

```ts
- if (type && maybeTypeOfKind(type, TypeFlags.Undefined | TypeFlags.Void | TypeFlags.Any)) {
+ if (type && maybeTypeOfKind(type, TypeFlags.Undefined | TypeFlags.Void | TypeFlags.Any | TypeFlags.Unknown)) {
```

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:35689]: The check would be faster slightly, and it allows all code to perform an earlier bail-out. I don't have a strong opinion, so let's see if Jake has a gut feel.

**Review by DanielRosenwasser — APPROVED** [review]

File: src/compiler/checker.ts (hunk 3 above)
Comment (MariaSolOs) [reply src/compiler/checker.ts:35689]: I'll wait for @jakebailey's final blessing then.

Comment (jakebailey) [reply src/compiler/checker.ts:35689]: Maybe both, so that this is handled too?

```ts
type MyUnknown = unknown

function test(): MyUnknown {
	if (Math.random() > 0.5) return true;
}
```

Comment (jakebailey) [reply src/compiler/checker.ts:35689]: I am assuming the above doesn't work before either and that we need the assignability check to cover it.

I do like sticking it up at the top at least for perf, but having both feels best to me.

Comment (jakebailey) [reply src/compiler/checker.ts:35689]: If so, that sounds good, and then the code can move up (I prefer that). Deserves a test at least.

Comment (jakebailey) [reply src/compiler/checker.ts:35689]: Yes, if it works.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:35689]: For clarity - we're talking about

https://github.com/microsoft/TypeScript/pull/53490/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R35663

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -35660,7 +35660,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             const type = returnType && unwrapReturnType(returnType, functionFlags);
 
             // Functions with an explicitly specified 'undefined, 'void' or 'any' return type don't need any return expressions.
-            if (type && maybeTypeOfKind(type, TypeFlags.Undefined | TypeFlags.Void | TypeFlags.Any)) {
+            // 'unknown' is also fine because it is always assignable to 'undefined'.
```
Comment (jakebailey) [inline src/compiler/checker.ts:35663]: I think this is flipped; anything is assignable to unknown.

Comment (jakebailey) [reply src/compiler/checker.ts:35663]: Maybe just add `unknown` to the previous comment.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -35686,7 +35687,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                     error(errorNode, Diagnostics.A_function_whose_declared_type_is_neither_void_nor_any_must_return_a_value);
                 }
             }
-            else if (type && strictNullChecks) {
+            else if (type && strictNullChecks && !isTypeAssignableTo(undefinedType, type)) {
```
[the remark this answers is not in the document]
Comment (MariaSolOs) [reply src/compiler/checker.ts:35690]: Oh I thought we wanted to keep both and use Daniel's early guard.

[the remark this answers is not in the document]
Comment (MariaSolOs) [reply src/compiler/checker.ts:35690]: The current tests do pass without it, so I guess it's fine to remove it.

[the remark this answers is not in the document]
Comment (jakebailey) [reply src/compiler/checker.ts:35690]: Yeah, I only wanted it if it was required for aliases, but Daniel clarified that it wasn't actually needed.

**Comment by ahejlsberg** [comment]
I don't think this is the right fix for the issue. The following now _doesn't_ error:

```ts
function foo(x: boolean): string | undefined {
}
```

This previously would report "A function whose declared type is neither 'void' nor 'any' must return a value."

**Comment by ahejlsberg** [comment]
The right fix is to put the assignability check back where it was originally.

**Comment by ahejlsberg** [comment]
Specifically, we need to undo the change I mention [here](https://github.com/microsoft/TypeScript/pull/53092#pullrequestreview-1361234573).

**Comment by ahejlsberg** [comment]
> Is this a fix or a bug?

Is what a fix or a bug?

**Comment by MariaSolOs** [comment]
> Is what a fix or a bug?

@ahejlsberg Sorry I wasn't clear, I was referring to this PR. The way I read Jake's comment, this change fixes the issue you brought up [here](https://github.com/microsoft/TypeScript/pull/53092#discussion_r1150710063), but you're suggesting we undo it.

**Comment by ahejlsberg** [comment]
Yes, I'm suggesting we undo this PR because, which it fixes the issue [here](https://github.com/microsoft/TypeScript/pull/53092#discussion_r1150710063), it causes a new issue that I mention [here](https://github.com/microsoft/TypeScript/pull/53490#issuecomment-1487305036).

The real fix is to revert the deletion of the assignability check I mention [here](https://github.com/microsoft/TypeScript/pull/53092#pullrequestreview-1361234573). Once that's done there is no need for this PR.

**Comment by MariaSolOs** [comment]
Got it, thanks for explaining! I can prepare that change.
