### PR TITLE
switch typeof any could be checked for unreachable

### LINKED ISSUE #39343: Switch exhaustiveness not working for `typeof any` and `typeof unknown`
**TypeScript Version:**  3.9.5, 4.0.0-dev.20200630

**Search Terms:** switch narrowing typeof any unknown

**Code**
Making `x` `unknown` also gives the same results.

```ts
const works = (x: any): number => {
  const type = typeof x
  switch (type) {
    case 'string': return 0
    case 'number': return 0
    case 'bigint': return 0
    case 'boolean': return 0
    case 'symbol': return 0
    case 'undefined': return 0
    case 'object': return 0
    case 'function': return 0
  }
}

const alsoWorks = (x: any): number => {
  switch (typeof x as 'string' | 'number' | 'bigint' | 'boolean' | 'symbol' | 'undefined' | 'object' | 'function') {
    case 'string': return 0
    case 'number': return 0
    case 'bigint': return 0
    case 'boolean': return 0
    case 'symbol': return 0
    case 'undefined': return 0
    case 'object': return 0
    case 'function': return 0
  }
}

const doesntWork = (x: any): number => {
  //                   ~~~
  // TS 2366: Function lacks ending return statement and return type does not include 'undefined'.
  switch (typeof x) {
    case 'string': return 0
    case 'number': return 0
    case 'bigint': return 0
    case 'boolean': return 0
    case 'symbol': return 0
    case 'undefined': return 0
    case 'object': return 0
    case 'function': return 0
  }
}
```

**Expected behavior:** No error in `doesntWork` as the switch is exhaustive. This should be the same as `works` (using a variable) and `alsoWorks` (using a type assertion).

**Actual behavior:** Error `TS 2366: Function lacks ending return statement and return type does not include 'undefined'.` with `strictNullChecks`.

[**Playground Link**](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200630&ssl=1&ssc=1&pln=84&pc=1#code/MYewdgzgLgBA7iATgawjAvDAFADwFwwCGYAngJQFgCuAtgEYCmiGAfDAN4CwAUDDKJFhQSABwYYYwsSABmMHDz4Q4ASyjAAFtikMyHRX36EI4gOTREKsAHNTBRAyhVEYGAAYDfYMbPV6TOxgHJxd3TyMTGFM6FWsrKEDg51cPXkNvSOiQEAAbBmJEx2SwtK8fKIgSelzCkJTwjLMqMAATBhkrBhba4tTDCLMQOgArBmAE+yLQvvTy0xlm8ZVwHumDAF8eTe4eHRgAFVEGWQlzKEsbUxgAHyi-RkQr2+jY+Keoumy8gpuKqs+cu9TM02h0wF0gUNRuMgQswEsVjweAJoEQchAQAB1JCoCS4AjEciUWgPVj6NLKNSabRHE44IhoQ7SGR6LilAYVc5WWyTOolfqNO4kgK83oNOYxOJgCZBKb1dmCrK5fJgVbygVzSrVQGitYKuYg9qdbq69WzTJQsYypJ6jWZOEI1Wm-kwbbbZHgVEIFAQTFqDQAVTAyDAIDgYAAjHj8DBmiGw2AKDB7kwyWyvJ6hEcJDo6QZKeotFgdKzxZkLNy1S6ypkU49nTMa2ZJW8G2Xm18VVXGxzzP8am39ZlDWCIYO7YMRlbu+2og6oMsnbK+TM3UjuCjYN7UH6oIHg6HwwAmaMEOOHxPE-zMdBsdMwAvU4u0uT04wHF+lodmCuXcfm3xhXrZcxW-D5XmlGcwKVb4lxtM0mz+bUoInKIR2NFCAKiS0YX-RD5kWBcVn-Ncdg3TMYBaEAGAgaVsRQABBUhTyIUgkzrNMDAAei4-o+P4gSAD9hO43j9gAZRgI8AGYADZZIIAAxQjFxgHJCGAXEGFabkQNCaBCCgBgaG02BiBaPTXD2KiaOTEBYCsYAcioNo0NaI1wW6AA6fNVELGlmXkL9ULOC4eUs6tezrTD8JbSC8N7T5lQKBLFS1AEYt7dDPMyxUcOtOVIsVedF0w0iPUESjqNoqB6OQIN43DFjzwTdigM4tIeIE7qer4YT+pEzqxMkmT5KUlTwDUjStJ0mwIoMoyTOlViLPgyRsxstBQwc+FnNc4F3NHbzfKpItc1fYKsNCytUrmaLbsyOKCpXWcYK7B6f37HUIp7RVsrHH7Xvy3K5hK4jAbSUigA)

**Related Issues:** #34661, #38136, #27180

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #39343

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
Not sure ablout "unknown" behaviour, is it the same? If so, it could be added easily, if not, what should it be?

**Comment by ShuiRuTian** [comment]
Why travis failed? Really strange.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -28194,6 +28195,10 @@ namespace ts {
                 // notEqualFacts states that the type of the switched value is not equal to every type in the switch.
                 const notEqualFacts = getFactsFromTypeofSwitch(0, 0, witnesses, /*hasDefault*/ true);
                 const type = getBaseConstraintOfType(operandType) || operandType;
+                // Take any as a specail condition. Maybe we could change type to a union containing all primitive types.
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:28198]: Fix spelling.
