### PR TITLE
Skip parens and non-null assertions when looking for this-context

### LINKED ISSUE #23040: Error using non-null-assertion on a method with a `this` parameter (regression)
I hit a regression trying to upgrade to the latest version.

**TypeScript Version:**  Tested with 2.8.1 and 2.9.0-dev.20180330

**Search Terms:**
* non null assertion
* The 'this' context of type 'void'

**Code**

```ts
interface Foo {
    required: ((this: Foo) => void);
    optional: ((this: Foo) => void) | null;
}

declare const foo: Foo;
foo.required();
foo.optional!();
```

**Expected behavior:**

Successful compilation

**Actual behavior:**

Error on the last line:

```
The 'this' context of type 'void' is not assignable to method's 'this' of type 'HTMLElement'.
```

**Playground Link:**  

https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20%20%20required%3A%20((this%3A%20Foo)%20%3D>%20void)%3B%0D%0A%20%20%20%20optional%3A%20((this%3A%20Foo)%20%3D>%20void)%20%7C%20null%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20foo%3A%20Foo%3B%0D%0Afoo.required()%3B%0D%0Afoo.optional!()%3B

**Related Issues:**

N/A

### PR DESCRIPTION
**Pull request by sandersn**
The check is syntactic and was previously very simple.

Fixes #23040

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -2022,7 +2022,17 @@ namespace ts {
...
     export function skipParentheses(node: Node): Node {
         while (node.kind === SyntaxKind.ParenthesizedExpression) {
-            node = (<ParenthesizedExpression>node).expression;
+            node = (node as ParenthesizedExpression).expression;
+        }
+
+        return node;
+    }
+
+    export function skipParenthesesAndNonNull(node: Expression): Expression;
```
Comment (weswigham) [inline src/compiler/utilities.ts]: Should probably just use `skipOuterExpressions`, which is all this and more.
