### PR TITLE
Skip overloads with too short function parameters

### LINKED ISSUE #11875: express.d.ts simple usage broken in latest bits
A basic Express 4 sample has errors with the latest bits. It appears to be a regression in TypeScript 2.1.

Below is how far I’ve managed to reduce the code into a standalone repro before heading home (from the definition currently in @types/express).

If I compile with the current bits in the “release-2.0.5” branch there is no error. This is specific to what is currently in “release-2.1”.

```
severity: 'Error'
message: 'Argument of type '(err: any, req: Response, res: NextFunction, next: any) => void' is not assignable to parameter of type 'PathParams'.
  Type '(err: any, req: Response, res: NextFunction, next: any) => void' is not assignable to type '(string | RegExp)[]'.
    Property 'push' is missing in type '(err: any, req: Response, res: NextFunction, next: any) => void'.'
```

```typescript
var app: myApp;

app.use((err: any, req, res, next) => { return; }); // <--- error on this call to 'use'


interface myApp {
    use: IRouterHandler<this> & IRouterMatcher<this>;
}
        
    interface IRouterHandler<T> {
        (...handlers: RequestHandler[]): T;
        (...handlers: RequestHandlerParams[]): T;
    }
    
    interface IRouterMatcher<T> {
        (path: PathParams, ...handlers: RequestHandler[]): T;
        (path: PathParams, ...handlers: RequestHandlerParams[]): T;
    }

    type PathParams = string | RegExp | (string | RegExp)[];
    type RequestHandlerParams = RequestHandler | ErrorRequestHandler | (RequestHandler | ErrorRequestHandler)[];

    interface RequestHandler {
        (req: Request, res: Response, next: NextFunction): any;
    }

    interface ErrorRequestHandler {
        (err: any, req: Request, res: Response, next: NextFunction): any;
    }

    interface Request {
        method: string;
    }

    interface Response {
        statusCode: number;
    }

    interface NextFunction {
        (err?: any): void;
    }
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #11875 

If the parameter of an overload is a function and the argument is also a
function, skip the overload if the parameter has fewer arguments than
the argument does. That overload cannot possibly apply, and should not
participate in, for example, contextual typing.

Example:

```ts
interface I {
  (a: number): void;
  (b: string, c): void;
}
declare function f(i: I): void;
f((x, y) => {});
```

This code now skips the first overload instead of considering it.

This was a longstanding bug but was only uncovered now that more function expressions are context sensitive.

@mhegazy @RyanCavanaugh do you mind taking a look? I need to skip `checkExpressionWithContextualType` so I think the code has to be here, but it seems like it is operating at the wrong level of abstraction overall.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11890,6 +11890,11 @@ namespace ts {
                     // If the effective argument type is 'undefined', there is no synthetic type
                     // for the argument. In that case, we should check the argument.
                     if (argType === undefined) {
+                        // If the parameter and argument are both functions and the parameter has fewer arguments than the argument,
+                        // then this signature is not applicable. Exit early.
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: "Exit early to avoid fixing incorrect contextual types to the function expression parameters"

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11904,6 +11909,21 @@ namespace ts {
             return true;
         }
 
+        function isAritySmaller(sourceType: Type, target: Expression) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Explicit `return false` at the bottom here

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -11904,6 +11909,21 @@ namespace ts {
             return true;
         }
 
+        function isAritySmaller(sourceType: Type, target: Expression) {
+            if (isFunctionExpressionOrArrowFunction(target) && isFunctionType(sourceType)) {
+                let targetParameterCount = 0;
+                for (; targetParameterCount < target.parameters.length; targetParameterCount++) {
+                    const param = target.parameters[targetParameterCount];
+                    if (param.initializer || param.questionToken || param.dotDotDotToken || isJSDocOptionalParameter(param)) {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: To be consistent, we should actually remove these checks. Optional parameters are considered to be present for the purposes of callback type checking.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/checker.ts]: added

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]: done

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/checker.ts]: This skips some additional overloads. It is not bad but it is worse than what we do today. Here's the test failure:

```ts
    function foo6<T>(cb: { (x: T): string; (x: T, y?: T): string }) {
        return cb;
    }
    var r11 = foo6(<T>(x: T, y?: T) => ''); // any => string (+1 overload)
```

Comment (sandersn) [inline src/compiler/checker.ts]: This gives `r11: any` instead of `r11: { (x: T): string; (x: T, y?: T): string }`

Comment (sandersn) [inline src/compiler/checker.ts]: I made the change; it's easy enough to revert if we decide against it.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -11904,6 +11910,16 @@ namespace ts {
             return true;
         }
 
+        function isAritySmaller(sourceType: Type, target: Expression) {
+            if (isFunctionExpressionOrArrowFunction(target) && isFunctionType(sourceType)) {
+                const sourceSignatures = getSignaturesOfType(sourceType, SignatureKind.Call);
+                const sourceLengths = sourceSignatures.map(sig => !sig.hasRestParameter ? sig.parameters.length : Number.MAX_VALUE);
+                return forEach(sourceLengths, len => len < target.parameters.length);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: A target with more parameters than the source might still be applicable if some of the target's parameters are optional. This doesn't appear to factor that in.

Comment (sandersn) [inline src/compiler/checker.ts]: The previous commit took optional parameters into account, but @RyanCavanaugh pointed out that optional parameters are considered to be present for checking function parameters. The change is in a single commit so it's easy to revert if you think that optionality should be taken into account, though.

**Comment by ahejlsberg** [comment]
I'm think a better approach would be to simply disqualify contextual signatures that have fewer parameters than the number of non-optional parameters in the function expression or arrow function. In other words, never contextually type from a signature that couldn't validly call the function. We already disqualify anything but a single non-generic signature, this could just be an additional check. I think it would solve the issue in #11875, but it would be a more local change with no effect on the overload resolution rules.

**Comment by sandersn** [comment]
Unfortunately, that results in `any` for both argument types below when the first overload is being explored. That's because `checkApplicableSignature` calls callExpressionWithContextualType on `(req, res) => {}`. Even if we now reject the contextual type from `handler1`, `callExpression` still ends up fixing the parameter types of `(req, res) => {}`. It would just fix them to `(any, any) => void`.

```ts
var use: Overload;
use((req, res) => {});

interface Overload {
    (handler1: (req1: string) => void): void;
    (handler2: (req2: number, res2: number) => void): void;
}
```

**Comment by ahejlsberg** [comment]
> Unfortunately, that results in `any` for both argument types below when the first overload is being explored.

Yes, but that example didn't work before the change either, and `(req: any, res: any)` actually seems preferable to the `(req: string, res: any)` that we would have produced earlier. In fact, it would make the example compile, but wouldn't give you the more specific parameter types.

It just never makes sense to contextually type part of a function expression's parameter list from a signature that couldn't actually call that function expression. Also, it is less of a breaking change to go from some specific type to `any` than the other way around.

The core issue here is that once we contextually type a parameter list, the assigned types are permanent. Changing *that* is much more involved and out of scope for this fix. Until then, I think what I'm proposing is the best we can do.

**Comment by sandersn** [comment]
OK, I moved the check to `getContextualSignature`.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -10343,6 +10343,10 @@ namespace ts {
             if (!type) {
                 return undefined;
             }
+            // If the contextual signature has fewer parameters than the function expression, do not use it
+            if (isFunctionExpressionOrArrowFunction(node) && isAritySmaller(type, node)) {
+                return undefined;
+            }
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This should be the last check you do. That way you only have to deal with a single signature as everything else will have been disqualified.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -10377,6 +10381,26 @@ namespace ts {
             return result;
         }
 
+        function isAritySmaller(sourceType: Type, target: FunctionExpression | ArrowFunction) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Change this to operate on a single source signature and call it as the last check.

File: src/compiler/checker.ts (hunk 5 above)
Comment (sandersn) [inline src/compiler/checker.ts]: I moved the check inside getNonGenericSignature so that it gets called in both the union and non-union paths. Let me know if that looks good to you.

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Done. The call is inside `getNonGenericSignature` now.
