### PR TITLE
🐛 Fix smart selection of propery signatures having JSDoc comments

### LINKED ISSUE #39618: Smart select does not select TypeScript object type
- VSCode Version: latest
- OS Version: macOS latest

Steps to Reproduce:

1. Paste this into a TypeScript file
   ```ts
   type Foo = {
     /** comment */
     status: number;
   };
   ```
2. Place cursor just before `status`
3. Run command "expand selection" 4 times

Expected:  only the object should be selected:

image

Actual: the whole type is selected:

image

gif

Does this issue occur when all extensions are disabled?: Yes

### LINKED ISSUE #49807: Smart selection acts weird when first function parameter has inline JSDoc
# Bug Report

### 🕗 Version & Regression Information

This is similar to #39618.

VS Code:
```
Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:49:57.055Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-41-generic
```

### 💻 Code

```ts
type B = {};
type A = {
    a(/** Comment */ p0: number, /** Comment */ p1: number): string;
};
```

### 🙁 Actual behavior

Having the caret at `p0` and repeated `Expand Selection` results in the wrong behavior we've already seen in #39618:
Recording 2022-07-06 at 15 51 04

### 🙂 Expected behavior

But with the caret at `p1` the behavior seems fine:
Recording 2022-07-06 at 15 52 50

### PR DESCRIPTION
**Pull request by babakks**
Fixes #39618
Fixes #49807

### CODE REVIEW

**Comment by andrewbranch** [comment]
Thank you! The result looks right and the code change is very simple so I’m happy to merge this. However, if you’re up for it, I would encourage you to see if there’s a more general solution in light of #49807. JSDoc can be attached to the beginning of nodes of all kinds and it seems like there may be a systemic failure to consider that in the smart select logic.

**Comment by babakks** [comment]
I've updated the fix. This now covers both cases mentioned in #49807. 

@andrewbranch Could you please review this again?

File: src/services/smartSelection.ts [hunk 1]
```diff
@@ -184,7 +195,7 @@ namespace ts.SmartSelectionRange {
         if (isPropertySignature(node)) {
             const children = groupChildren(node.getChildren(), child =>
                 child === node.name || contains(node.modifiers, child));
-            return splitChildren(children, ({ kind }) => kind === SyntaxKind.ColonToken);
+            return splitChildren(children, ({ kind }) => kind === SyntaxKind.ColonToken || kind === SyntaxKind.JSDoc);
```
Comment (andrewbranch) [inline src/services/smartSelection.ts:198]: This doesn’t work too well when the property signature has modifiers. Try adding `readonly` before `status` in smartSelection_JSDocTags11.ts and notice how the whole line appears at once since we were no longer able to pivot on the colon token. There needs to be another level in the hierarchy rather than just shifting the pivot point. It also seems like that should be happening for more than just property signatures. In other words, if we have a `children` like

```
[
  JSDoc,
  X,
  Y,
  Z
]
```

maybe it always makes sense to restructure it like

```
[
  JSDoc,
  SyntaxList([
    X,
    Y,
    Z
  ])
]
```

Comment (babakks) [reply src/services/smartSelection.ts]: Yes. You're right. I did as you suggested and it's working. Also, updated the test case to include the modifier (and a new cursor position at the start of it).

**Review by andrewbranch — APPROVED** [review]
Thank you!
