### PR TITLE
Filter out private fields in string literal property completions.

### LINKED ISSUE #36082: Incorrect string property suggestion for private field returned outside of class
**TypeScript Version:**  3.8.0-dev.20200108

**Search Terms:**
- private fields
- javascript
- string property accessor
- bracket accessor
- suggestions

**Code**
For the JavaScript:

```js
//@ts-check

class Prv {
    #value = 1;
}

new Prv()[''];
```

Trigger suggestions inside the string

**Expected behavior:**
No suggestions returned

**Actual behavior:**
A suggestion for `#value` is returned. This changes the code to:

```js
//@ts-check

class Prv {
    #value = 1;
}

new Prv()['#value'];
```

### PR DESCRIPTION
**Pull request by elibarzilay**
Also some minor simplifications.

Fixes #36082.

### CODE REVIEW

File: src/services/stringCompletions.ts [hunk 1]
```diff
@@ -154,7 +155,8 @@ namespace ts.Completions.StringCompletions {
                     // }
                     // let a: A;
                     // a['/*completion position*/']
-                    return stringLiteralCompletionsFromProperties(typeChecker.getTypeAtLocation(expression));
+                    const type = typeChecker.getTypeAtLocation(expression);
+                    return stringLiteralCompletionsFromProperties(type);
```
Comment (sandersn) [inline src/services/stringCompletions.ts]: this change seems unneeded.

File: src/services/stringCompletions.ts [hunk 2]
```diff
@@ -6,9 +6,10 @@ namespace ts.Completions.StringCompletions {
             return entries && convertPathCompletions(entries);
         }
         if (isInString(sourceFile, position, contextToken)) {
-            return !contextToken || !isStringLiteralLike(contextToken)
-                ? undefined
-                : convertStringLiteralCompletions(getStringLiteralCompletionEntries(sourceFile, contextToken, position, checker, options, host), sourceFile, checker, log, preferences);
+            if (!contextToken || !isStringLiteralLike(contextToken)) return undefined;
+            const stringLiteralCompletions =
```
Comment (sandersn) [inline src/services/stringCompletions.ts]: `entries` is a nicer name here: less redundancy, and less length.

Comment (elibarzilay) [reply src/services/stringCompletions.ts]: Much better...
