### PR TITLE
Fix resolving entity name of namespace member after alias is merged with type

### LINKED ISSUE #51975: Support a way to export `type X` and `* as X` as namespace with values and types
# Suggestion

## 🔍 Search Terms

- export
- namespace
- module

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to be able to easily export a whole module including types and values, and at the same time export a type with the same name.

## 📃 Motivating Example

I want to have a single import of `Something`, which represents both a type, and a namespace containing all types and values of the Something module.

Usage:
```ts
import { Something } from "./prelude"
export const myValue: Something<string> = Something.of("abc")
export type MyType = Something.SubType<string>
```

`prelude.ts`:

Option 1:
```ts
import * as S from "./Something"

// currently causes only the values of Something to be accessible via `Something.x`, but not the types like `Something.SubType`
export * as Something from "./Something"
export type Something<A> = S.Something<A>
```
The limitation seems strange. Perhaps just a bug?

Option 2:
```ts
import * as S from "./Something"

export namespace Something {
   // currently causes `Export declarations are not permitted in a namespace.ts(1194)`
   export * from "./Something"
}
export type Something<A> = S.Something<A>
```
The limitation seems arbitrary. We can already export from namespaces. Why not allow * exports for convenience?

Option 3:
```ts
// currently causes `Duplicate identifier 'Something'.ts(2300)`
export * as Something from "./Something"
export type { Something } from "./Something"
```
The limitation seems strange. As we already can create a type and value/namespace with same name, and export them together.

`Something.ts`:
```ts
export interface Something<A> {
   something: A
}

export const of = (a: A): Something<A> => ({ something: a })

export interface SubType<A> {
  subType: A
}
```

## 💻 Use Cases

The current approaches either mean I have to use `Something.Something<string>` and also see this `Something.` namespace in type errors and on hover in editor. It's verbose, and ugly.

Or I need to work around the issue in either of two ways, both of them require manual syncing of files, or individual exports:

Workaround 1:

Manually create:
Prelude.**d.ts**:
```ts
import * as S from "./Something"
export namespace Something {
  // in d.ts files it causes no error!
  export * from "./Something"
}
export type Something<A> = S.Something<A>
```

Prelude.**js**:
```js
export * as Something from "./Something"
```

Workaround 2: Manually alias all the exports in a namespace:

Prelude.ts:
```ts
import * as S from "./Something"
export namespace Something {
   export const of = S.of
   export type SubType<A> = S.SubType<A>
}
export type Something<A> = S.Something<A>
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #51975. The root cause of the bug is essentially the same as the ones described in #50455.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4683,6 +4683,10 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 }
             }
             symbol = getMergedSymbol(getSymbol(getExportsOfSymbol(namespace), right.escapedText, meaning));
+            if (!symbol && (namespace.flags & SymbolFlags.Alias)) {
+              // `namespace` can be resolved further if there was a symbol merge with a re-export
+              symbol = getMergedSymbol(getSymbol(getExportsOfSymbol(resolveAlias(namespace)), right.escapedText, meaning));
```
Comment (jakebailey) [inline src/compiler/checker.ts:4688]: Style nit:

```suggestion
                // `namespace` can be resolved further if there was a symbol merge with a re-export
                symbol = getMergedSymbol(getSymbol(getExportsOfSymbol(resolveAlias(namespace)), right.escapedText, meaning));

```

Comment (andrewbranch) [reply src/compiler/checker.ts:4688]: Weird, I wonder how that happened.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4683,6 +4683,10 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 }
             }
             symbol = getMergedSymbol(getSymbol(getExportsOfSymbol(namespace), right.escapedText, meaning));
+            if (!symbol && (namespace.flags & SymbolFlags.Alias)) {
+                // `namespace` can be resolved further if there was a symbol merge with a re-export
+                symbol = getMergedSymbol(getSymbol(getExportsOfSymbol(resolveAlias(namespace)), right.escapedText, meaning));
```
Comment (jakebailey) [inline src/compiler/checker.ts:4688]: Can this be simplified to just calling `resolveSymbol` on the original `symbol = ` above?

I feel like I fixed a bug like this recently that did something similar. That and there's `getExportSymbolOfValueSymbolIfExported` which I think is related and does some of this chain of calls. (I think we're somewhat inconsistent about it.)

Comment (andrewbranch) [reply src/compiler/checker.ts:4688]: No, because then we would fail to look up the property on the original value of `namespace`, which could very well be the one that has the export—it’s just not in _this_ case. You could make a (somewhat more contrived) test where the alias points to a type and the local declaration is the namespace containing the export we’re looking for.

**Review by jakebailey — APPROVED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:4688]: I think this also needs another condition, like
```suggestion
                if (!getMergedSymbol(getSymbol(getExportsOfSymbol(namespace), right.escapedText, SymbolFlags.All))) {
                    symbol = getMergedSymbol(getSymbol(getExportsOfSymbol(resolveAlias(namespace)), right.escapedText, meaning));
                }

```
since if that symbol exists in the original non-alias namespace (just with not the target meanings we're looking for), it should probably still block lookup in the alias target... right?

Comment (andrewbranch) [reply src/compiler/checker.ts:4688]: I’m not sure it should, but it’s worth noting that this scenario you describe would be a merge error. In the test given, the non-alias symbol meaning is the type alias `Something<A>`—not a namespace at all. If we change it to be a namespace and try to reason about which of the two namespaces we want to pull from:

image

Comment (weswigham) [reply src/compiler/checker.ts:4688]: Are you sure you can't manage a similar shape in JS that we don't _technically_ error on though? Something like
```ts;
// @Filename: usage.ts
import { Something } from "./prelude"
export const myValue: Something<string> = Something.of("abc")
export type MyType = Something.SubType<string>

// @Filename: Something.ts
export type Something<A> = { value: A }
export type SubType<A> = { value: A }
export declare function of<A>(value: A): Something<A>

// @Filename: prelude.js
import * as S from "./Something"
export * as Something from "./Something"
export type Something<A> = S.Something<A>;
module.exports.Something = 12;
```

Comment (andrewbranch) [reply src/compiler/checker.ts:4688]: In that example, we basically seem to ignore the `module.exports.Something` assignment, both before and after this change. But just imagine that the double-namespace example I gave was not an error, and our emit did something that would make the runtime merge work as expected. If that were possible, then the following would be true:

1. Exports declared in multiple locations of that merged namespace would need to be checked for mergeability the same way local namespace merges are checked, so duplicate values/types couldn’t clobber each other.
2. If two declarations of the same-named export are allowed to merge, since one is a type and one is a value, I don’t see why the local one should block the alias one.

Saying that the local should block the alias would be predicated on the runtime merge _not_ working, but there’s already a top-level error for that.

Comment (weswigham) [reply src/compiler/checker.ts:4688]: Yeah, I guess that's true; JS merges already let weird things with totally undefined behavior happen anyway, so it's not really important how they influence this.

**Review by weswigham — APPROVED** [review]
