### PR TITLE
`convertStringOrTemplateLiteral.ts`: Re-fix `escapeStringForTemplate`

### LINKED ISSUE #45278: Debug Failure. Invalid raw text
(Migrated from microsoft/tsserverfuzzer#334)

**Repo Name**: https://github.com/meteor/meteor.git

**Revision**: 6f7df8f35f1617b393a1d13c48f2bf70c2be31f6

**TypeScript Version**: 4.4.0-dev.20210801

**Commands**:

```
{"response":true,"responseRequired":true}
{"command":"format","arguments":{"endLine":3,"endOffset":72,"line":3,"offset":1,"file":"D:/local/Temp/fuzzerWorkingDir/meteor/packages/deprecated/facebook/deprecation_notice.js","options":{}},"type":"request","seq":26}
{"response":[{"start":{"line":3,"offset":1},"end":{"line":3,"offset":3},"newText":"    "}],"responseRequired":true}
{"command":"getCodeFixes","arguments":{"errorCodes":[1],"startLine":3,"startOffset":1,"endLine":3,"endOffset":72,"file":"D:/local/Temp/fuzzerWorkingDir/meteor/packages/deprecated/facebook/deprecation_notice.js"},"type":"request","seq":27}
{"response":[],"responseRequired":true}
{"command":"getApplicableRefactors","arguments":{"startLine":3,"startOffset":1,"endLine":3,"endOffset":72,"file":"D:/local/Temp/fuzzerWorkingDir/meteor/packages/deprecated/facebook/deprecation_notice.js"},"type":"request","seq":27}
{"response":[{"name":"Convert to template string","description":"Convert to template string","actions":[{"name":"Convert to template string","description":"Convert to template string","kind":"refactor.rewrite.string"}]}],"responseRequired":true}
{"command":"getApplicableRefactors","arguments":{"startPosition":63,"endPosition":135,"file":"D:/local/Temp/fuzzerWorkingDir/meteor/packages/deprecated/facebook/deprecation_notice.js"},"type":"request","seq":28}
{"response":[{"name":"Convert to template string","description":"Convert to template string","actions":[{"name":"Convert to template string","description":"Convert to template string","kind":"refactor.rewrite.string"}]}],"responseRequired":true}
{"command":"getEditsForRefactor-full","arguments":{"refactor":"Convert to template string","action":"Convert to template string","startPosition":63,"endPosition":135,"file":"D:/local/Temp/fuzzerWorkingDir/meteor/packages/deprecated/facebook/deprecation_notice.js"},"type":"request","seq":29}
(Showing last 10 of 84295 commands)
```

**Code** ([`packages\deprecated\facebook\deprecation_notice.js`](https://github.com/meteor/meteor/blob/6f7df8f35f1617b393a1d13c48f2bf70c2be31f6/packages/deprecated/facebook/deprecation_notice.js)):

```js
  console.warn(
    "The `facebook` package has been deprecated.\n" +
//                                                ^
    "\n" +
    "To use the `Facebook` symbol, add the `facebook-oauth` package\n" +
```

**Hash**: 852e880c70bfc938c26c5ca13a866a38

**Stack trace**:
```
Debug Failure. Invalid raw text
    at createTemplateLiteralLikeNodeChecked (tsserverlibrary.js:23682:37)
    at createNoSubstitutionTemplateLiteral (tsserverlibrary.js:23722:20)
    at nodesToTemplate (tsserverlibrary.js:155514:68)
    at getEditsForToTemplateLiteral (tsserverlibrary.js:155400:39)
    at getEditsForAction (tsserverlibrary.js:155392:41)
    at getEditsForRefactor (tsserverlibrary.js:143247:41)
    at getEditsForRefactor (tsserverlibrary.js:157975:32)
    at Session.getEditsForRefactor (tsserverlibrary.js:168544:59)
    at _a.<computed> (tsserverlibrary.js:167256:61)
    at <anonymous> (tsserverlibrary.js:168907:88)
```

### PR DESCRIPTION
**Pull request by elibarzilay**
Make it backslash-escape backticks too.  While I was there, remove the
use of this function for the text (which was the earlier confused
version that used only `text`), and rename it as
`escapeRawStringForTemplate` to clarify.

Added a test to the preivious pile of tests.

Fixes #45278 (and the original microsoft/tsserverfuzzer#334).

### CODE REVIEW

File: tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts [hunk 1]
```diff
@@ -94,3 +94,15 @@ edit.applyRefactor({
...
+// @Filename: /i.ts
+////let s = /*i1*/'$`' + text + "`\\"/*i2*/;
+
+goTo.select("i1", "i2");
+edit.applyRefactor({
+    refactorName: "Convert to template string",
+    actionName: "Convert to template string",
+    actionDescription: ts.Diagnostics.Convert_to_template_string.message,
+    // newContent is: let s = `\$\`${text}\`\\`;
+    newContent: 'let s = `\\$\\`${text}\\`\\\\`;'
```
Comment (rbuckton) [inline tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts:107]: There's no reason for the `$` to be escaped here, since it isn't immediately followed by a `{`.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts (hunk 1 above)
Comment (elibarzilay) [reply tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts:107]: @rbuckton: yeah, that was an intentional bit in the last PR: I think that people prefer to see escaped `$`s to make things clear, no?  (Especially in something confusing like `$${n}`.)  If you prefer the minimal route, then maybe I'll do that in a separate PR?  (The change is easy, and I have the minimal thing in a comment -- look for the "less-backslash-happy version" comment.)

Comment (rbuckton) [reply tests/cases/fourslash/refactorConvertStringOrTemplateLiteral_escapeSequences.ts:107]: I'd prefer the unescaped `$`, but since this isn't directly being used as the template for a tagged template expression, its probably fine? Again, I'm unsure whether this would affect anyone using custom transforms where they *wouldn't* want the extra `\`.

**Review by rbuckton — APPROVED** [review]
