### PR TITLE
Consistently propagate `intersectionState` in relations

### LINKED ISSUE #52252: Intersection types not merged in 4.9.4
# Bug Report

### 🔎 Search Terms

Intersection types not merged

### 🕗 Version & Regression Information

- This changed between versions 4.8.2 and 4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAigrhATiKBeKBvAUFKAbASwGdgCA7AcwC5MdcoAzCAQ2DkQiJu3vrEQIBbZsip1eGKAH0poSGWaCIAfhoByAGIs2HNVAC+4+gDJavXgGMA9niuIuZ870IUAFsBpk4ggEZIANEZOACYiANae3n6IgU64+rHmhrwJRhasEBR2BJw0AIKIiMwgADySRQDukb4BjHbCwMAQwTQkApQGAHx0yVCmGkUUSmTAWIZYctADzEMQI2iOTKzsuY64-EIiIGIS0rLgc4oq6lrLugZGpjzm1rb23EH0Lu7V0Y+98YmpuOlNWQKrApFUqSBj1VhNFpQNrkChdMZYLDWMgkKAcIhgKwoiA0eBIFDoa6EEiwh68JY6VbXXgbYSiNY3Gx2BzUuLPDxQACMiTiUFCiAiUAAzDykqLPkZvvRfplsqsANqPVm8So0ABM4voYMQDUh6gAqkRmmpNVLcABdL6BcZYIA)

### 💻 Code

```ts repro
type Query = {
  listing: {
    features: {
      primary:
      { __typename?: 'Feature' }
      & {
        colors: {
          light: number,
          dark: number,
        },
      }
    },
    categories: Array<{ raw: number, formatted: string }>
  }
  & Fragment
}

type Fragment = {
  features: {
    primary:
    { __typename?: 'Feature' }
    & {
      colors: {
        light: number
      }
    },
  },
  categories: Array<{ formatted: string }>
}

const response: Query = {
  listing: {
    features: {
      primary: {
        colors: {
          light: 1,
          dark: 3,
        },
      },
    },
    categories: [
      {
        raw: 2,
        formatted: 'Used',
      },
    ],
  },
}
```

### 🙁 Actual behavior

`colors.dark` and `categories.raw` are marked as errors as missing in the type definition.

### 🙂 Expected behavior

Errored fields are defined in the `Query` type and should be valid.
If I remove `{ __typename?: 'Feature' }` from `Fragment` the error goes away.

### LINKED ISSUE #52397: Deep intersections stopped working in 4.9
# Bug Report

### 🔎 Search Terms

Deep union no longer work

### 🕗 Version & Regression Information

- This is a crash: no
- This changed between versions ____4.8__ and ___4.9____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____yes_____
- I was unable to test this on prior versions because __tested on prior versions, is regression_____

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBA4lC8UDeUwCcD2YDOAuKAFAFBTJQCG+KAZhhvgIxQC+zJUAZGZWQEblp8AJhZsAlM05l0WPNypQAjgFcAHvgDMrNkQDGGAHbZgUAOb44iJOxk4q7Uj2ukXUWvSgMANA5f9BUEI+rqQq6lAawS5spGzMQA)

### 💻 Code

```ts
type G = { props: (
  { a: { foo: 1 }}
  & { a: { bar: 2 }}
)} & { props: { a: { qux: 3}}}

const g: G = {
  props: {
    a: {
      foo: 1,
      bar: 2,
      qux: 3,  // gives error in 4.9, not in 4.8
    }
  }
}
```

### 🙁 Actual behavior

qux gives error:
> Object literal may only specify known properties

### 🙂 Expected behavior

Continues working as it had before

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #52252.
Fixes #52397.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by RyanCavanaugh** [comment]
I suspect this might fix #52397?

**Comment by ahejlsberg** [comment]
> I suspect this might fix #52397?

It does indeed.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
Everything looks good with the latest commit to handle intersections in `isDeeplyNestedType`.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21811,7 +21813,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             // No array like or unmatched property error - just issue top level error (errorInfo = undefined)
         }
 
-        function propertiesRelatedTo(source: Type, target: Type, reportErrors: boolean, excludedProperties: Set<__String> | undefined, intersectionState: IntersectionState): Ternary {
+        function propertiesRelatedTo(source: Type, target: Type, reportErrors: boolean, excludedProperties: Set<__String> | undefined, optionalsOnly: boolean, intersectionState: IntersectionState): Ternary {
```
Comment (weswigham) [inline src/compiler/checker.ts:21816]: Rather than add a new boolean parameter to this function that we have to pass everywhere, could we not use the existing `excludedProperties` parameter to exclude all the non-optional properties at the single callsite we wanted to?

**Review by weswigham — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:21816]: Yeah, I considered that, but didn't want the overhead of constructing a new set, and the function is only called in three places.

**Review by jakebailey — APPROVED** [review]
