### PR TITLE
fix(47954): Auto implementation of interface with a constructor prop causes error

### LINKED ISSUE #47954: Auto implementation of interface with a `constructor` prop causes error
# Bug Report

### 🔎 Search Terms

auto implement constructor

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99#code/JYOwLgpgTgZghgYwgAgGJUWYB7EAZYAaxQG8BYAKGWpAFcBbaOMbKALmQCNgBzUMStWQATCCGz1QzVh259wg6glwBnMFFoIW7ZAEl69WmDicANhHSYcISgF9KlBKbgqVeg0ZPnLW68mD0AA7mjOBuPli4BMTI5FRKquqa2sgAFIG0ZsAIyHSMGNqyvPwANMgZWTmi4pIg0jpy-ACUsYpC-jBp1RJSKQC8A8gADCAtce0TYAAWUNgA7sgASnAgPBAAolCzUKkARAAiwABuwCp+nACeyABe0Ni7TW1C9vHIL7ZAA)

### 💻 Code

```ts
interface FractionLike {
   numerator: bigint
   denominator: bigint
   constructor: ImmutableFraction
}

class ImmutableFraction implements FractionLike {
   constructor (public numerator, public denominator) {
      if (denominator === 0n) {
         throw RangeError("Division by zero")
      }
   }
}
```

### 🙁 Actual behavior

Auto completes by adding `constructor: ImmutableFraction` to the class definition which is invalid

### 🙂 Expected behavior

Adds `["constructor"]: ImmutableFraction` which seems to work

#### Note

There's probably a better solution in my particular case

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47954

### CODE REVIEW

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -195,7 +195,10 @@ namespace ts.codefix {
             if (method) addClassElement(method);
         }
 
-        function createName(node: PropertyName) {
+        function createName(node: PropertyName, parent?: Declaration) {
+            if (parent && isPropertySignature(parent) && isIdentifier(node) && node.escapedText === "constructor") {
```
Comment (sandersn) [inline src/services/codefixes/helpers.ts:199]: why is it important to check the parent? It does restrict the change to fixing just #47954, but I don't think you ever want to emit `constructor` in a fix. I think this fix should apply to most or all of the places that `createName` is called, although that means a lot more testing.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/services/codefixes/helpers.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/codefixes/helpers.ts:199]: Do we need to handle `constructor` name for getters/setters too?

**Review by sandersn — APPROVED** [review]
