### PR TITLE
Binding element with parent type any is of type any

### LINKED ISSUE #12620: Default values + destructuring confuses CFA
**TypeScript Version:**  2.1.1 and nightly (2.2.0-dev.20161202)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
let node: {
    props: any;
};

const { props: { className = '' } = {} } = node;

if (className) {
    node.props.className = className.slice(0, 1); // error TS2339: Property 'slice' does not exist on type 'never'.
}
```

**Expected behavior:**
Code compiles without error as in TS 2.0.10

**Actual behavior:**
Error as commented.

Might be duplicate/related to #10065 and its linked issues somehow, but I'm not sure. Strict nullchecks is not enabled.

The following workarounds fix the error:
1. Change const to let
2. Use `if typeof className === 'string'` instead of `if (className)`
3. Take out the default values from the destructuring pattern

### PR DESCRIPTION
**Pull request by sandersn**
Previously if the binding element had an initializer, then that type would be used. But this is incorrect:

```ts
function f(x: any) {
  let { d = 1 } = x;
  // d should have type any not number.
  // f can be called with anything:
}
f({ d: 0 });
f({ d: 'hi' });
f({});
```

Fixes #12620

Also get rid of a useless call to `getContextualType`. I added it a year and a half ago and it just makes no sense.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4151,13 +4151,13 @@ namespace ts {
...
-            // If no type was specified or inferred for parent, or if the specified or inferred type is any,
-            // infer from the initializer of the binding element if one is present. Otherwise, go with the
-            // undefined or any type of the parent.
-            if (!parentType || isTypeAny(parentType)) {
-                if (declaration.initializer) {
-                    return checkDeclarationInitializer(declaration);
-                }
+            // If no type was specified or inferred for parent,
+            // infer from the initializer of the binding element if one is present.
+            // Otherwise, go with the undefined type of the parent.
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Doesn't it make sense to say "Otherwise, go with the any type of the parent"? We don't seem to do any checking for the `undefined` type here?

Comment (sandersn) [reply src/compiler/checker.ts]: This applies to the block immediately below the comment, which checks `if (!parentType)`. "The falsy type of the parent" would be more accurate, but isn't the intent.

Any is different in that (1) you can specify any and (2) it will override the initialiser. I decided not to comment this as it seemed pretty obvious.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4151,13 +4151,13 @@ namespace ts {
...
+            if (!parentType) {
+                return declaration.initializer ? checkDeclarationInitializer(declaration) : parentType;
```
Comment (weswigham) [inline src/compiler/checker.ts]: If there's no `parentType`, and no `declaration.initializer`, then we return `parentType` when we know it does not exist - it'd probably be nicer for future references to this code if it explicitly returned `undefined` and had `undefined` as part of it's return type signature, if you ever feel like coming back to this.
