### PR TITLE
fix(7410): Support JSX Element as JSX Attribute Value

### LINKED ISSUE #7410: Support JSX Element as JSX Attribute Value
**TypeScript Version:** 

1.8.2

**Background**:

I have been working on trying to get https://github.com/eslint/typescript-eslint-parser, a TypeScript parser plugin for ESLint, off the ground, and the job this weekend has been to begin adding JSX support.

ESLint uses espree and so the aim of the project is to convert the output of the tsc to an AST which espree expects. We already have a solid suite of JSX tests to develop against (taken from the espree project itself), but I have come up against a tsc error in one of them so far.

My issue is that it seems currently the tsc does not accept this "embedded-tags" JSX syntax:

**Code**

``` ts
<LeftRight left=<a /> right=<b>monkeys /> gorillas</b> />;

```

**Expected behavior:**
Please note the AST produced by espree (see in particular the `tokens` array): http://astexplorer.net/#/9WAjizSvbC

**Actual behavior:**
...compared to the one produced by the tsc (note the issues found in `parseDiagnostics`):
http://astexplorer.net/#/YehKzLJYMW

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #7410

```md
JSXAttributeValue:
    " JSXDoubleStringCharactersopt "
    ' JSXSingleStringCharactersopt '
    { AssignmentExpression }
    JSXElement
    JSXFragment
```

- [JSX spec](https://facebook.github.io/jsx/)
- https://github.com/babel/babel/pull/6006 / [Example](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DwEwlgbgfAUAkKSACAhgFzQJwLyIkgeikNgXH3S13KgDMB7e4AmkmZmoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D)

### CODE REVIEW

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
Waiting for final confirmation on https://github.com/facebook/jsx/issues/53 before merging/closing.

File: src/compiler/types.ts [hunk 1]
```diff
@@ -2590,9 +2590,16 @@ namespace ts {
         readonly parent: JsxAttributes;
         readonly name: Identifier;
         /// JSX attribute initializers are optional; <X y /> is sugar for <X y={true} />
-        readonly initializer?: StringLiteral | JsxExpression;
+        readonly initializer?: JSXAttributeValue;
     }
 
+    export type JSXAttributeValue =
```
Comment (j-f1) [inline src/compiler/types.ts:2596]: Should this be `JsxAttributeValue` to match the node types?

Comment (a-tarasyuk) [reply src/compiler/types.ts]: @j-f1 That makes sense. Thanks.

**Review by raghavthind2005 — APPROVED** [review]

**Comment by sandersn** [comment]
@RyanCavanaugh are we still waiting on confirmation from facebook/jsx to merge this?

**Comment by RyanCavanaugh** [comment]
Maybe let's just merge it. If the JSX spec changes, we'll have the same mess to clean up as Babel, which is fine
