### PR TITLE
Use proper method of not resolving alias

### LINKED ISSUE #6456: Quick info / Goto definition use alias as target even if it has incorrect meaning
Related to #6372.
```ts
// highcharts.d.ts
declare var Highcharts: HighchartsStatic;

interface HighchartsChart {
    /**
     * This is the constructor for creating a new chart object.
     * @param  {HighchartsOptions} options The chart options
     * @return {HighchartsChartObject}
     */
    new (): any;
}


interface HighchartsStatic {
    Chart: HighchartsChart;
}

declare module 'highcharts-release' {
    export = HighchartsStatic;
}
```
```ts
import Highcharts = require('highcharts-release');
var chart = new High/*1*/charts.Chart();
```

Quickinfo / Goto definition at position `/*1*/` will show information about `import Highcharts` but it should be `declare var Highcharts` instead

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #6456

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1207,7 +1207,7 @@ namespace ts {
         }
 
         // Resolves a qualified name and any involved aliases
-        function resolveEntityName(name: EntityName | Expression, meaning: SymbolFlags, ignoreErrors?: boolean, dontResolveAlias?: boolean): Symbol {
+        function resolveEntityName(name: EntityName | Expression, meaning: SymbolFlags, ignoreErrors = false, dontResolveAlias = false): Symbol {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: Do not see the reason for the initialization. two additional operations, not used for the commandline compilation scenarios.

**Comment by mhegazy** [comment]
just one comment about the initialization, and other than that looks good. thanks!

**Comment by sheetalkamat** [comment]
👍
