### PR TITLE
Clarified file-not-found error for reference paths without extensions

### LINKED ISSUE #5642: Need better error msg for error resulting from reference of file without extension
``` typescript
/// <reference path="x"/>
```

This results in error:
error TS6053: File 'x.ts' not found.

Given we support ts as well as tsx files we need better error msg here

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #5642.

I'm not sold on this phrasing, but spent the requisite 5 minutes trying to brainstorm something better. 🤷‍♂

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -2249,7 +2249,7 @@ namespace ts {
                 }
 
                 const sourceFileWithAddedExtension = forEach(supportedExtensions, extension => getSourceFile(fileName + extension));
-                if (fail && !sourceFileWithAddedExtension) fail(Diagnostics.File_0_not_found, fileName + Extension.Ts);
+                if (fail && !sourceFileWithAddedExtension) fail(Diagnostics.No_file_under_0_found_with_any_supported_extension, fileName);
```
Comment (sandersn) [inline src/compiler/program.ts]: Maybe: "Could not resolve the path 'x' with the extensions: [list extensions]."

File: tests/baselines/reference/project/invalidRootFile/node/invalidRootFile.errors.txt [hunk 2]
```diff
@@ -1,6 +1,8 @@
 error TS6053: File 'a.ts' not found.
 error TS6054: File 'a.t' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
+error TS6229: No file under 'a' found with any supported extension.
```
Comment (sandersn) [inline tests/baselines/reference/project/invalidRootFile/node/invalidRootFile.errors.txt]: seems like the error shouldn't happen in the 'a.t' case, since we think '.t' is an extension

Comment (JoshuaKGoldberg) [reply tests/baselines/reference/project/invalidRootFile/node/invalidRootFile.errors.txt]: @sandersn sorry, I'm not clear on the behavior change you're requesting. Only `'a'` is reported on right now - do you want others to have this error as well?

Alternately, in theory, some folks might be naming files like `contents.legacy.ts` and referring to them as `contents.legacy` - where `.legacy` could be misinterpreted as an extension... but the behavior now is to assume anything after a `.` is an extension.

Comment (sandersn) [reply tests/baselines/reference/project/invalidRootFile/node/invalidRootFile.errors.txt]: Well, looking back at it this week, I think I was confused and thought that both line 2 and 3 were new, but only line 3 is. So fixing an existing wrong error is out of scope for this PR -- sorry I suggested it.

**Comment by sandersn** [comment]
@JoshuaKGoldberg this is ready to go in after a merge. I'll do it next time I go through the Needs Merge column in the PR Backlog board, but if you have a chance before then, you are welcome to do so.
