### PR TITLE
Propagate constness of type parameters in variadic tuples

### LINKED ISSUE #52007: Preserve constness of generics with tuple types
# Bug Report

### 🔎 Search Terms

const modifier, generics, tuple types

### 🕗 Version & Regression Information

It shows up just in the nightly version because `const` modifiers for generics will be available from TS 5.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221223#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXy1VRBgGcAeMPUjeAFXhAA8MRVhT44pg8IBPeFFT8A2gF0AfAAoAdPNgBzUgC4uIHn0Gi0Aa1Q4A7qgA08ebLpm9B4+ICUaugG4AUK6qoa8Vt4C8BEQkpNIAjCYATCYAzCYALCYArPZuAPSp8JnwAHoA-EA)

### 💻 Code

```ts
declare function inners<const T extends readonly any[]>(...args: readonly [unknown, ...T, unknown]): T;

const test = inners(1,2,3,4,5);
```

### 🙁 Actual behavior

`T` is inferred as `[number, number, number]` instead of `readonly [2,3,4]`. There are other ways to write this function by avoiding tuple types at all, but it is a nice example to show that that the constness introduced by the `const` modifier seems to be lost when tuple types come into play, even with the `readonly` modifier.

### 🙂 Expected behavior

`T` inferred as `readonly [2,3,4]`

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #52007.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13213,6 +13213,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
 
     function isConstTypeVariable(type: Type): boolean {
         return !!(type.flags & TypeFlags.TypeParameter && some((type as TypeParameter).symbol?.declarations, d => hasSyntacticModifier(d, ModifierFlags.Const)) ||
+            isGenericTupleType(type) && findIndex(getTypeArguments(type), (t, i) => !!(type.target.elementFlags[i] & ElementFlags.Variadic) && isConstTypeVariable(t)) >= 0 ||
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:13216]: Can you use something like `find`, `some`, or `forEach` instead of `findIndex`?

Comment (jakebailey) [reply src/compiler/checker.ts:13216]: `some` doesn't have the `i` param but `find` seems like it should work without the >= 0 check.

**Review by RyanCavanaugh — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:13216]: In that case I'm probably fine with `findIndex` (or `findLastIndex` since variadics usually come at the end anyhow).

**Comment by jfet97** [comment]
Just a minor point:

```ts
declare function inners<const T extends readonly any[]>(...args: readonly [...T]): T;

const test = inners(1,2,3,4,5);
```

Shouldn't the type of `test` be `readonly [1,2,3,4,5]` instead of just `[1,2,3,4,5]`?
