### PR TITLE
Give cjs export assigned types an alias symbol

### LINKED ISSUE #49397: Incorrect d.ts for js project when module.exports an array
# Bug Report

### 🔎 Search Terms

module, module.exports, module exports, array, js, d.ts, declaration file

### 🕗 Version & Regression Information
Affected 3.7.5 and 4.7.2 and probably all of between them, did not test before 3.7.5.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about declaration

### ⏯ Playground Link
https://tsplay.dev/Wy4kJm

### 💻 Code
```ts
// Produces wrong d.ts
module.exports = [{ name: 'other', displayName: 'Other', defaultEnabled: true }];
```

```ts
// Produces right d.ts
const r = [{ name: 'other', displayName: 'Other', defaultEnabled: true }];
module.exports = r;
```

### 🙁 Actual behavior

Produces wrong declaration file and make a copy of all array methods in place.

### 🙂 Expected behavior

Produces correct declaration file using `T[]` syntax.

### PR DESCRIPTION
**Pull request by weswigham**
Because we structurally copy export assigned object types. We only give it the alias symbol when it looks like we haven't had to patch on additional exported members.

Fixes #49397

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5021,6 +5021,9 @@ namespace ts {
                 if (!inTypeAlias && type.aliasSymbol && (context.flags & NodeBuilderFlags.UseAliasDefinedOutsideCurrentScope || isTypeSymbolAccessible(type.aliasSymbol, context.enclosingDeclaration))) {
                     const typeArgumentNodes = mapToTypeNodes(type.aliasTypeArguments, context);
                     if (isReservedMemberName(type.aliasSymbol.escapedName) && !(type.aliasSymbol.flags & SymbolFlags.Class)) return factory.createTypeReferenceNode(factory.createIdentifier(""), typeArgumentNodes);
+                    if (length(typeArgumentNodes) === 1 && type.aliasSymbol === globalArrayType.symbol) {
```
Comment (weswigham) [inline src/compiler/checker.ts:5024]: This is technically a change that makes it so alias symbols to the global `Array` type are printed back as array types. But array types don't get alias symbols in usual circumstances (they're type references), so realistically this only affects the case I've just added where we create an array alias symbol. :)

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9376,6 +9379,17 @@ namespace ts {
                     exportedType.callSignatures,
                     exportedType.constructSignatures,
                     exportedType.indexInfos);
+                if (initialSize === members.size) {
+                    if (type.aliasSymbol) {
+                        result.aliasSymbol = type.aliasSymbol;
+                        result.aliasTypeArguments = type.aliasTypeArguments;
+                    }
+                    if (getObjectFlags(type) & ObjectFlags.Reference) {
```
Comment (weswigham) [inline src/compiler/checker.ts:9387]: Generally, arbitrary type reference types don't usually get alias symbols, but we transform it into an alias symbol here to improve printback, since our copy strips the reference-ness of the type.

**Review by andrewbranch — APPROVED** [review]

**Review by sandersn — APPROVED** [review]
