### PR TITLE
Missing import code fix - include export assignment properties when looking for module exports 

### LINKED ISSUE #13377: CodeFix import for lodash does not work
Not sure if it's the issue with lodash typings or something else, but CodeFix import for lodash does not work:

image

but if I import manually then it's ok

image

### PR DESCRIPTION
**Pull request by minestarks**
Fixes #13377

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1776,6 +1777,20 @@ namespace ts {
             }
         }
 
+        function tryGetMemberInModuleExportsAndProperties(memberName: __String, moduleSymbol: Symbol): Symbol | undefined {
+            const symbolTable = getExportsOfModule(moduleSymbol);
+            if (symbolTable) {
+                let symbol = symbolTable.get(memberName);
+                if (!symbol) {
+                    const exportEquals = resolveExternalModuleSymbol(moduleSymbol);
```
Comment (amcasey) [inline src/compiler/checker.ts]: The export properties don't obviously depend on `symbolTable`.  Is there a reason they're not checked if `symbolTable` is `undefined`?  It looks like `getExportsAndPropertiesOfModule`, above, doesn't have this restriction, but it may simply be missing an optimization.

Comment (amcasey) [inline src/compiler/checker.ts]: It also seems like the first attempt (i.e. the exports) could be attempted by calling `tryGetMemberInModuleExports`.

Comment (amcasey) [inline src/compiler/checker.ts]: Alternatively, we could merge the APIs and pass a flag.

File: src/compiler/types.ts [hunk 2]
```diff
@@ -2586,6 +2586,8 @@ namespace ts {
         getAmbientModules(): Symbol[];
 
         tryGetMemberInModuleExports(memberName: string, moduleSymbol: Symbol): Symbol | undefined;
+        /** Unlike `tryGetMemberInModuleExports`, this includes properties of an `export =` value. */
+        /* @internal */ tryGetMemberInModuleExportsAndProperties(memberName: string, moduleSymbol: Symbol): Symbol | undefined;
```
Comment (amcasey) [inline src/compiler/types.ts]: Why internal?

File: src/services/codefixes/importFixes.ts [hunk 3]
```diff
@@ -179,7 +179,7 @@ namespace ts.codefix {
             }
 
             // check exports with the same name
-            const exportSymbolWithIdenticalName = checker.tryGetMemberInModuleExports(name, moduleSymbol);
+            const exportSymbolWithIdenticalName = checker.tryGetMemberInModuleExportsAndProperties(name, moduleSymbol);
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Should this check be skipped if `name` is "default"?

File: tests/cases/fourslash/importNameCodeFixNewImportFile5.ts [hunk 4]
```diff
@@ -0,0 +1,16 @@
+/// <reference path="fourslash.ts" />
+
+//// [|bar/*0*/();|]
+
+// @Filename: foo.ts
+//// interface MyStatic {
+////     bar(): void;
```
Comment (amcasey) [inline tests/cases/fourslash/importNameCodeFixNewImportFile5.ts]: If I'm reading the code correctly, it seems like the case that distinguishes the two `tryGetMemberInModuleExports*` call-sites is a property named "default".  Would it be interesting to test that explicitly.

File: src/compiler/checker.ts (hunk 1 above)
Comment (minestarks) [inline src/compiler/checker.ts]: At this point, I'll keep the functions separate in the interest of keeping the public API stable. I am changing the code to have this one call ```tryGetMemberInModuleExports```

File: src/compiler/types.ts (hunk 2 above)
Comment (minestarks) [inline src/compiler/types.ts]: I feel that this goes hand in hand with ```getExportsAndPropertiesOfModule```  and that one's internal

File: src/services/codefixes/importFixes.ts (hunk 3 above)
Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: As discussed, I don't think ```name``` can legally be ```"default"```. Will add a comment to clarify.

File: tests/cases/fourslash/importNameCodeFixNewImportFile5.ts (hunk 4 above)
Comment (minestarks) [inline tests/cases/fourslash/importNameCodeFixNewImportFile5.ts]: Answered above.

File: src/services/codefixes/importFixes.ts [hunk 5]
```diff
@@ -178,6 +178,8 @@ namespace ts.codefix {
                 }
             }
 
+            Debug.assert(name !== "default");
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Can you please add a comment explaining why this is true?  Something like "default is a keyword and is not valid as an expression"?
