### PR TITLE
fix(57386): Invalid use of 'eval' when defining a namespaced eval function

### LINKED ISSUE #57386: Invalid use of 'eval' when defining a namespaced eval function
### 🔎 Search Terms

eval, strict mode, namespace

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBzCB7ARlC8DeAoeB8IAHgA4owAu8AdlALYgDOpUYCNIlAZhAJbEc+QiJLkq8bgFcaYSnxQ0iAN0wAKAJQAueMpR9gAbmEEAvrnO4xFatnNA

### 💻 Code

```ts
declare global {
    export namespace myNamespace {
        export function eval(): void;
    }
}

export {}
```

### 🙁 Actual behavior

Invalid use of 'eval'. Modules are automatically in strict mode.

### 🙂 Expected behavior

No error

### Additional information about the issue

I see in https://github.com/microsoft/TypeScript/issues/3036 that this behavior is by design as defining an 'eval' function is forbidden in strict mode. However, the namespace declaration above describes runtime code more like the following, which is perfectly valid in strict mode:

```ts
const myNamespace = {
    eval() {
        // ...
    }
}
```

Would it be possible to not fail on namespaced function declarations?

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #57386

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -2563,7 +2563,7 @@ function createBinder(): (file: SourceFile, options: CompilerOptions) => void {
     }
 
     function checkStrictModeFunctionName(node: FunctionLikeDeclaration) {
-        if (inStrictMode) {
+        if (inStrictMode && !(node.flags & NodeFlags.Ambient)) {
```
Comment (sandersn) [inline src/compiler/binder.ts:2566]: This will allow for un-namespaced `declare function eval(): void` too, right? Is there any legal strict-mode code that could be typed by that? I can't think of any.

Restricting this exemption to namespaces makes sense to me if there aren't any other examples with legal emit.

**Review by sandersn — CHANGES_REQUESTED** [review]
I think this should be restricted to namespaced-contained functions, or else have a lot more tests with examples of ambient variables, functions, etc named `eval`.

File: src/compiler/binder.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/binder.ts:2566]: > This will allow for un-namespaced declare function eval(): void too, right?

Yes, I've added tests to cover this case

Comment (sandersn) [reply src/compiler/binder.ts:2566]: I'd like to disallow `declare function eval(): void`. You can't write a matching `function eval() { }` or `var eval = function() { }`, can you?

Comment (RyanCavanaugh) [reply src/compiler/binder.ts:2566]: How do _we_ declare the global `eval` if that's illegal?

Comment (sandersn) [reply src/compiler/binder.ts:2566]: good point!

**Review by sandersn — APPROVED** [review]
