### PR TITLE
Always resetErrorInfo if structuredTypeRelatedTo succeeds

### LINKED ISSUE #49475: Discriminated unions behave inconsistently since v4.6
# Bug Report

### 🔎 Search Terms

Discriminated union

### 🕗 Version & Regression Information

- This changed between versions 4.5.5 and 4.6.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.4#code/MYGwhgzhAECyD2ATApiaBvAUNax4DsIAXAJwFdgj4SAKABzICMQBLYaAM3AHMAuaRvHghkYfAEoMAX0wzMRAJ51k0ACIsIwEiwC2LfGCLJEAVXwsC0ALwZOPfqTIqp0AD62uYPpzAgIzgG5MUEgYAEEAHgAVaGQADyN8RBh1TW09AyNTcwIAPgxsXAJickpqeiZWdh0kVH4oyXRoGTkAelboMzwdHWR8ImgiAAsVIgB3eGhWfGQYRlR4McHJ7mQB7URoeA5BkaKdOhYREliSEmpeTHbOMnxKC3xOIRoAfRqUEH5UrV19Q2MzA9Gs0rh0OM90C5IHBaiBxEFguAoNAAEKxBJ9ZLQSIID75JoyVoAKmwUSUKgA5LjUBToBpoPh4ANQixuAZmKNJoplNAKU1PN4OL5-AFmhSAHSFMnKGDbaB0c7KEiKXkC2lgEgqfTdOiGFgcyU4HDSymCYSifC0+mM5lQVnskTLQbk1XC5ASzBE1qYIA)

### 💻 Code

```ts
class Model {
  constructor(public flag: boolean) {}
}

type DiscriminatedUnion = { flag: true } | { flag: false };
class A<T extends DiscriminatedUnion> {
  constructor(public model: T) { }
}

// Uncomment the two lines below to get rid of the compiler error:
// function foo(_model: DiscriminatedUnion) { }
// foo({} as Model);

class B extends A<Model> { }    // Type 'Model' is not assignable to type '{ flag: false; }'.
```

### 🙁 Actual behavior

Class `A` doesn't accept `Model` as generic parameter with the following error:
```
Type 'Model' is not assignable to type '{ flag: false; }'.
  Types of property 'flag' are incompatible.
    Type 'boolean' is not assignable to type 'false'.
```
The basic example above hadn't emitted any errors prior to v4.6. Furthermore, if you uncomment the code that declares and executes function `foo`, the compiler error vanishes.

### 🙂 Expected behavior

The code is compilable in 4.6+ without any workarounds.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #49475

If `typeRelatedToDiscriminatedType` succeeds, then we have to clear the errors from previous steps as they are no longer true. Most of the previous steps do this too (but not all, confusingly).

This manifested as being "uncomment this code, and the error goes away" because the call expression's call to `isRelatedTo` had `reportErrors=false`, while the class' call had `reportErrors=true`. The class check is deferred, so the call expression happened first, and the successful relationship was cached, then the error didn't appear later. Without the call expression, the error was reported even though it shouldn't have been.

Rather than remembering to place those `resetErrorInfo` calls everywhere, turn the function into a worker and always reset if the relation succeeded.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline

**Comment by RyanCavanaugh** [comment]
I guess my question is whether there are other "missing" calls in this function, e.g. at https://github.com/microsoft/TypeScript/pull/49718/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8L19836

**Comment by jakebailey** [comment]
I totally agree, and so I made the change to wrap `structuredTypeRelatedTo` and _always_ restore on failure, but that seemed to break things in confusing ways. I'll go post that as a separate PR based on this one to show what I mean.

**Comment by jakebailey** [comment]
All of the differences were my mistake; I'll push the change here. But, I don't have any more tests for cases I'm missing. At least it'll feel like it won't be broken :D

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19287,13 +19287,21 @@ namespace ts {
...
             function structuredTypeRelatedTo(source: Type, target: Type, reportErrors: boolean, intersectionState: IntersectionState): Ternary {
+                const saveErrorInfo = captureErrorCalculationState();
+                const result = structuredTypeRelatedToWorker(source, target, reportErrors, intersectionState, saveErrorInfo);
+                if (result) {
+                    resetErrorInfo(saveErrorInfo);
+                }
+                return result;
+            }
+
+            function structuredTypeRelatedToWorker(source: Type, target: Type, reportErrors: boolean, intersectionState: IntersectionState, saveErrorInfo: ReturnType<typeof captureErrorCalculationState>): Ternary {
```
Comment (jakebailey) [inline src/compiler/checker.ts:19298]: `saveErrorInfo` is kept because there are still some calls which explicitly reset it in order to hide certain errors that would be less helpful than others.

**Review by weswigham — APPROVED** [review]
