### PR TITLE
Add quick fix to add missing 'await'

### LINKED ISSUE #30646: Better error and quick fix for missing await
## Search Terms

missing await error refactoring

## Suggestion

Missing an `await` can cause some confusion especially for people who haven't used async/await before. A helpful error message when you have a Promise\<T\> instead of T that suggests maybe an await is missing might help address this. There are at least a few common cases this comes up:

* Using operators, and T is a primitive type. If T were say an object type, it seems more likely something else is wrong with the code to me.
* Passing to a function, and T is a valid parameter at that position.
* for-of and T is some array type
* The target of a member expression and T has the member (or maybe the property name is not in Promise).

A quick fix could also be considered. When in an async function and an error such as above appears, a quick fix that adds an await before the source of the promise within that function.

## Use Cases

It helps people realize when they need an await.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #30646 

Most of this PR is not terribly interesting, so let me point out the interesting parts:

1. I’m currently _not_ limiting the quick fix to async functions, based on a couple things: a) our pre-existing usage of the message “Did you forget to use 'await'?” was not predicated on being in an async function, and b), if you add `await` inside a non-async function, we’ll immediately surface a subsequent code fix to add `async` to the function, which I predict will be a common and convenient sequence. So right now, I’ve limited the quick fix to appearing when the `await` would go inside a function/arrow/method body (something that can take `async`).
2. When problem-Promise is a variable who has a declaration with an initializer in the same file that is not exported, and that variable is not yet used anywhere else, and the variable does not have a declared type, we offer _two_ code fixes: the first in the list is to add `await` to the _initializer_ of the variable at the declaration site. The second is the standard insertion of `await` at the use site, as is available everywhere else. When applying “Fix all expressions possibly missing 'await',” the initializer fix is preferred if available.

add-await

### CODE REVIEW

File: src/services/codefixes/addMissingAwait.ts [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+        Diagnostics.Argument_of_type_0_is_not_assignable_to_parameter_of_type_1.code,
+        propertyAccessCode,
+        ...callableConstructableErrorCodes,
+    ];
+
+    registerCodeFix({
+        fixIds: [fixId],
+        errorCodes,
+        getCodeActions: getAllPossibleFixesForError,
+        getAllCodeActions: context => {
```
Comment (sandersn) [inline src/services/codefixes/addMissingAwait.ts]: why inline getAllCodeActions but not getCodeActions? They should probably be the same.

(I'd vote for both inline, but don't care too much.)

File: src/services/codefixes/addMissingAwait.ts [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+    const fixId = "addMissingAwait";
+    const propertyAccessCode = Diagnostics.Property_0_does_not_exist_on_type_1.code;
+    const callableConstructableErrorCodes = [
+        Diagnostics.This_expression_is_not_callable.code,
+        Diagnostics.This_expression_is_not_constructable.code,
+    ];
+    const errorCodes = [
+        Diagnostics.An_arithmetic_operand_must_be_of_type_any_number_bigint_or_an_enum_type.code,
+        Diagnostics.The_left_hand_side_of_an_arithmetic_operation_must_be_of_type_any_number_bigint_or_an_enum_type.code,
+        Diagnostics.The_right_hand_side_of_an_arithmetic_operation_must_be_of_type_any_number_bigint_or_an_enum_type.code,
```
Comment (sandersn) [inline src/services/codefixes/addMissingAwait.ts]: This will show for any old type combination, like `number + Event`, right? What happens in that case? Does it just fail to do anything when you try to "add missing await"?

**Comment by andrewbranch** [comment]
> Code looks good, but it looks like this fix shows for any incorrect addition, like number + HTMLElement, and then proceeds to do nothing when invoked. Did you think about making specific errors for + et al when one of the sides is a Promise? That would make the codefix suggestion quite a bit more accurate. What do you think?

Hum, yes, I did think about it, but it should be handled by `isMissingAwaitError`. Something is amiss. (Related, I had a discussion with Wes in Teams about how VS Code doesn’t request code fixes for related info error codes, which would make this much cleaner. I’m thinking about PRing them to suggest a change there.)

File: src/services/codefixes/addMissingAwait.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/codefixes/addMissingAwait.ts]: I think there was a transient reason which later got refactored away. Good call.

File: src/services/codefixes/addMissingAwait.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/codefixes/addMissingAwait.ts]: It's supposed to be filtered out further in `getCodeActions` (it doesn’t show anything if you return undefined / empty array in there). This is back to the tradeoffs we were discussing about using related info as a “bonus error message” vs. copying and pasting all these into new, unique messages. I wrote this down as a larger LS design/API change to consider at some later point.

**Comment by andrewbranch** [comment]
> but it looks like this fix shows for any incorrect addition, like `number` + `HTMLElement`

Ah, I thought you were saying you observed this happening, but I think you were just looking at the error codes? I believe it’s working correctly, but I just pushed a test for that negative case specifically. It’s a good thing to assert in the tests.

I gave some more context about what’s happening and why I took this approach in the inline comments, but TL;DR, the error codes are necessary but not sufficient to surface a quick fix. Once `getCodeActions` is invoked with a _possible_ candidate, it correlates the error with the related message `Did you forget to use 'await'?` that the checker added via semantic knowledge that there’s a strong chance `await` is appropriate (#32239). If it doesn’t find that, it bails, and a code fix doesn’t show.

**Comment by sandersn** [comment]
Nope, I didn't run it, just read the code. I think I was thinking of the refactor API instead of the codefix API? IIRC the refactor API is the one with two calls, and the first one has to be fast because it runs a lot.
