### PR TITLE
Use symlinks when looking for module names for declaration emit

### LINKED ISSUE #24829: TypeScript 2.9.x incorrectly emits relative imports for symbolically linked dependencies (lerna)
**TypeScript Version:**  2.9.x

2.8.x works fine. It starts to break with TypeScript 2.9.x. It's not fixed by the latest build (typescript@next).

**Search Terms:** 

import symbolic link lerna

**Code**

https://github.com/strongloop/loopback-next/blob/master/packages/core/src/keys.ts

**keys.ts**
```ts
import {Application, ControllerClass} from './application';

export const CONTROLLER_CLASS = BindingKey.create<ControllerClass>(
    'controller.current.ctor',
  );
```
Please note the `ControllerClass` is a type alias re-exported from another module `@loopback/next` which is symbolically linked to `@loopback/core` by `lerna`.

**application.ts**
```ts
import {Context, Binding, BindingScope, Constructor} from '@loopback/context';
export type ControllerClass = Constructor<any>;
```

**Expected behavior:**

TypeScript 2.8.x style:
**keys.d.ts** (emitted by tsc)
```ts
const CONTROLLER_CLASS: BindingKey<new (...args: any[]) => any>;
```
Or

```ts
import {Constructor} from '@loopback/context';

const CONTROLLER_CLASS: BindingKey<Constructor<any>>;
```

**Actual behavior:**

```ts
const CONTROLLER_CLASS: BindingKey<import("../../context/src/value-promise").Constructor<any>>;
```

Please note the relative link is only valid at development time. Once it's published as a npm module, the `import` cannot be resolved.

**Playground Link:**  

**Related Issues:** 

https://github.com/strongloop/loopback-next/issues/1405

### PR DESCRIPTION
**Pull request by weswigham**
Including indirect ones (ie, where the directory is linked and the module's resolution came in as anormal resolution through the parent), which previously we would have ignored, even had we used `getModuleSpecifiers`.

Fixes #24829

cc @rbuckton for the changes to the compiler harness to support directory/arbitrary symlinks

### CODE REVIEW

File: src/harness/harness.ts [hunk 1]
```diff
@@ -1897,10 +1910,16 @@ namespace Harness {
             let currentFileOptions: any = {};
             let currentFileName: any;
             let refs: string[] = [];
+            let symlinks: [string, string][] | undefined;
 
             for (const line of lines) {
                 const testMetaData = optionRegex.exec(line);
-                if (testMetaData) {
+                const linkMetaData = linkRegex.exec(line);
```
Comment (rbuckton) [inline src/harness/harness.ts]: Why match this as both and option and a link? I would recommend moving the `const testMetaData …` line into the else branch.

File: src/harness/harness.ts [hunk 2]
```diff
@@ -1244,6 +1247,14 @@ namespace Harness {
 
             const docs = inputFiles.concat(otherFiles).map(documents.TextDocument.fromTestFile);
             const fs = vfs.createFromFileSystem(IO, !useCaseSensitiveFileNames, { documents: docs, cwd: currentDirectory });
+            if (symlinks) {
```
Comment (rbuckton) [inline src/harness/harness.ts]: If `symlinks` were a `vfs.FileSet`, you could just call `fs.apply(symlinks)`.

File: src/harness/harness.ts [hunk 3]
```diff
@@ -1897,10 +1910,16 @@ namespace Harness {
             let currentFileOptions: any = {};
             let currentFileName: any;
             let refs: string[] = [];
+            let symlinks: [string, string][] | undefined;
 
             for (const line of lines) {
                 const testMetaData = optionRegex.exec(line);
-                if (testMetaData) {
+                const linkMetaData = linkRegex.exec(line);
+                if (linkMetaData) {
```
Comment (rbuckton) [inline src/harness/harness.ts]: If `symlinks` was a `vfs.FileSet`, you could just do:

```ts
if (!symlinks) symlinks = {};
symlinks[linkMetaData[2].trim()] = new vfs.Symlink(linkMetaData[1].trim());
```

File: src/harness/harness.ts (hunk 2 above)
Comment (weswigham) [reply src/harness/harness.ts]: Then I'd have to distinguish between weather the link is between files or directories, which I'm not bothering to do right now, as it really doesn't matter. It's be a lot more code to do that same thing 🤷‍♀️

**Comment by weswigham** [comment]
@rbuckton :+1: :-1:?

File: src/compiler/moduleSpecifiers.ts [hunk 4]
```diff
@@ -130,15 +133,57 @@ namespace ts.moduleSpecifiers {
...
+    }
+
+    function getAllModulePathsUsingIndirectSymlinks(files: ReadonlyArray<SourceFile>, target: string, getCanonicalFileName: (file: string) => string, host: ModuleSpecifierResolutionHost) {
+        const links = discoverProbableSymlinks(files);
+        const paths = arrayFrom(links.keys());
+        let options: string[] | undefined;
+        for (const path of paths) {
+            const resolved = links.get(path)!;
+            if (startsWith(target, resolved + "/")) {
+                const relative = getRelativePathFromFile(resolved + "/file.ts", target, getCanonicalFileName);
```
Comment (mhegazy) [inline src/compiler/moduleSpecifiers.ts]: i would create a new a new `getRelativePath` that takes two folders.

File: src/compiler/moduleSpecifiers.ts [hunk 5]
```diff
@@ -130,15 +133,57 @@ namespace ts.moduleSpecifiers {
...
+                const option = resolvePath(path, relative);
+                if (!host.fileExists || host.fileExists(option)) {
+                    if (!options) options = [];
+                    options.push(option);
+                }
+            }
+        }
+        const resolvedtarget = host.getCurrentDirectory ? resolvePath(host.getCurrentDirectory(), target) : target;
+        if (options) {
+            options.push(resolvedtarget); // Since these are speculative, we also include the original resolved name as a possibility
```
Comment (mhegazy) [inline src/compiler/moduleSpecifiers.ts]: not sure i understand why we are adding the original name?

Comment (weswigham) [reply src/compiler/moduleSpecifiers.ts]: When we find a symlinked path that we know is correct, we make a choice to ignore the original path and not present is as an option. Since the file in this case wasn't imported directly via a symlink in the compilation already, in this case I think it's more appropriate to keep it around, that way you can still get, eg `./foo` as an option even though `module/foo` is possible.

**Comment by mhegazy** [comment]
merge conflicts

**Comment by raymondfeng** [comment]
@mhegazy Is the fix released with typescript@2.9.2? If so, the problem is getting even worse:
```
const CONTROLLER_CLASS: BindingKey<import("../../../../../../../../Users/rfeng/Projects/loopback4/loopback-next/packages/core/node_modules/@loopback/context/src/value-promise").Constructor<any>>;
```

Please note the relative path has two issues:
- It's relative to the absolute root
- It's not correctly resolved to a module dependency `@loopback/context` which exports the `Constructor` type.

**Comment by weswigham** [comment]
Assuming all those leading `../`'s climb out of the directories I think they do, the entire leading part of that path, `../../../../../../../../Users/rfeng/Projects/loopback4/loopback-next/packages/core/node_modules/` is totally extraneous...

@raymondfeng do you have any other path-related settings enabled for your build? Are there any symlinks present other than `loopback-next/packages/context` being linked to `loopback-next/packages/core/node_modules/@loopback/context`?

**Comment by raymondfeng** [comment]
My repo is managed by `lerna` and the directory layout is illustrated below:

```
loopback-next
  > packages
    > context (npm module @loopback/context)
    > core (npm module @loopback/core)
      > node_modules/@loopback/context -> ../../../context (symbolic link to the @loopback/context module)
```

**Comment by weswigham** [comment]
Right, and your TS build settings?

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/blob/master/packages/core/tsconfig.build.json

**Comment by raymondfeng** [comment]
The `npm run build` command is basically running `/Users/rfeng/Projects/loopback4/loopback-next/packages/build/node_modules/typescript/lib/tsc.js -p tsconfig.build.json --outDir /Users/rfeng/Projects/loopback4/loopback-next/packages/core/dist8 --target es2017`.
