### PR TITLE
Fix `replacementSpan` for class member snippet completion entries

### LINKED ISSUE #52211: No completions for methods following property declaration
```ts
interface Interface {
    method(): void;
}

export class Class implements Interface {
    property = "yadda";

    /*$*/
}
```

Request completions at `/*$*/` with the following set to `true`

* `includeCompletionsWithSnippetText`
* `includeCompletionsWithClassMemberSnippets`

**Expected**: We should offer to auto-complete `method`.
**Actual**: Only keyword completions!

image

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #52211.

The problem was that the replacement span in the class member snippet completion entry was being wrongly computed. For instance, in the issue's example:
```ts
interface Interface {
    method(): void;
}

export class Class implements Interface {
    property = "yadda";

    /*$*/
}
```
The replacement span ended up being the range for `property = "yadda";`.

Because the replacement span was wrong (as in it didn't occur on the same line as the position where the completion was requested), vscode was marking it as invalid and filtering it out.

### CODE REVIEW

File: src/harness/fourslashImpl.ts [hunk 1]
```diff
@@ -984,15 +984,19 @@ export class TestState {
...
-        if (convertedReplacementSpan?.length) {
+        if (convertedReplacementSpan) {
             try {
                 assert.deepEqual(actual.replacementSpan, convertedReplacementSpan);
             }
             catch {
                 this.raiseError(`At entry ${actual.name}: Expected completion replacementSpan to be ${stringify(convertedReplacementSpan)}, got ${stringify(actual.replacementSpan)}`);
             }
         }
+        else if (ts.hasProperty(expected, "replacementSpan")) { // Expected `replacementSpan` is explicitly set as `undefined`.
```
Comment (gabritto) [inline src/harness/fourslashImpl.ts:997]: Turns out we weren't checking if the replacement span was `undefined`, and now we are, if the property is set in the expected completion.

File: src/harness/fourslashImpl.ts [hunk 2]
```diff
@@ -984,15 +984,19 @@ export class TestState {
         if (actual.insertText !== expected.insertText) {
             this.raiseError(`At entry ${actual.name}: Completion insert text did not match: ${showTextDiff(expected.insertText || "", actual.insertText || "")}`);
         }
+
         const convertedReplacementSpan = expected.replacementSpan && ts.createTextSpanFromRange(expected.replacementSpan);
-        if (convertedReplacementSpan?.length) {
+        if (convertedReplacementSpan) {
```
Comment (gabritto) [inline src/harness/fourslashImpl.ts:989]: We also weren't checking expected replacement spans that had a 0 length.

File: tests/cases/fourslash/importStatementCompletions1.ts [hunk 3]
```diff
@@ -20,7 +20,7 @@
 //// [|import f/*4*/ =|]
 
 // @Filename: /index5.ts
-//// import f/*5*/ from "";
+//// [|import f/*5*/ from "";|]
```
Comment (gabritto) [inline tests/cases/fourslash/importStatementCompletions1.ts:23]: This test was wrong before because it had a range missing, but we weren't catching it because the expected `replacementSpan` was `undefined`.

File: src/services/completions.ts [hunk 4]
```diff
@@ -1650,8 +1654,9 @@ function getEntryForMemberCompletion(
     return { insertText, isSnippet, importAdder, replacementSpan };
 }
 
-function getPresentModifiers(contextToken: Node | undefined): { modifiers: ModifierFlags, span?: TextSpan } {
-    if (!contextToken) {
+function getPresentModifiers(contextToken: Node | undefined, position: number): { modifiers: ModifierFlags, span?: TextSpan } {
+    if (!contextToken
+        || getLineAndCharacterOfPosition(contextToken.getSourceFile(), position).line > getLineAndCharacterOfPosition(contextToken.getSourceFile(), contextToken.getEnd()).line) {
```
Comment (sandersn) [inline src/services/completions.ts:1659]: this line is still a little too long -- it wraps on on a 1440px-wide screen at least.

**Review by sandersn — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

File: src/services/completions.ts (hunk 4 above)
Comment (DanielRosenwasser) [reply src/services/completions.ts]: You are also requesting the `SourceFile` several times, and that never gets cached across nodes. Fetch it once and pass the same value through (or use the available `sourceFile` that was declared above?)

**Review by DanielRosenwasser — APPROVED** [review]
