### PR TITLE
fix(47081): Autocomplete breaks in overloaded generic function

### LINKED ISSUE #47081: Autocomplete breaks in overloaded generic function
# Bug Report

Autocomplete doesn't work in an overloaded generic function. 

### 🔎 Search Terms

autocomplete vscode overload generic

### 🕗 Version & Regression Information

This is the behavior in every version I tried (4.1+ and nightly), and I reviewed the FAQ for entries about this.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=3&pc=1#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQALpAA4oDyoAvKAN6gBmccAXKAEZsA2SAQwB2oAL4BuIkWYBXITBIBLOCK68B+VAB4AKgD4AFJhwDKnKgEpOwyJNnylK7us27Dx00k4GLdPaEtrIVtpOQVlVRdUAw1UIMhfBiJQUEISGXwRWMlRKTVYgyZWDhJ8GRRRC3FQEFABGRI4eABbcn4SFAB3OHwAa2w8QiJ8zQMfP1BCljZOUvKxCyqasC4G0CE4ElwCJCA)

### 💻 Code

```ts
type Shape = { foo: boolean };

function blarg<T>(shape: Shape): any;
function blarg<T>(shape: () => Shape): any;
function blarg(arg: any) {
  return arg;
}

blarg({ foo:true }); // autocomplete works here
blarg(() => ({ foo:true })); // but not here
```

Note that both functions are generic. This behavior occurs even though the generic parameter is unused. After removing the generic, autocomplete works fine for both overloads.

### 🙁 Actual behavior

In the first call to `blarg` (which uses the overload that expects an object), when you start typing `f-o-o`, the key name `foo` will be autosuggested.

In the second call to `blarg` (which uses the overload that expects an object-returning function), `foo` doesn't autocomplete when you start typing it.

If that found autocompletion only works on the first overload, in order of how the overloads are defined. In the playground, if you reverse the order of the two overloads, you will see the behavior switch.

### 🙂 Expected behavior

Autocompletion should work in all overloads.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47081

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -3754,6 +3754,12 @@ namespace ts.Completions {
             // Object literal is assignment pattern: ({ | } = x)
             return typeChecker.getTypeAtLocation(node.parent);
         }
+        if (isParenthesizedExpression(node.parent)) {
+            const parent = walkUpParenthesizedExpressions(node.parent);
+            if (isExpression(parent)) {
```
Comment (sandersn) [inline src/services/completions.ts:3759]: I think it would be better to walk up parentheses at the beginning of the function, then run *both* of the existing checks.
At worst it's written the way the rest of the compiler is, at best it allows parentheses inside assignment pattern + future things that might be added here.

File: tests/cases/fourslash/completionListInObjectLiteral7.ts [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+////type Foo = { foo: boolean };
+////function f<T>(shape: Foo): any;
+////function f<T>(shape: () => Foo): any;
+////function f(arg: any) {
+////  return arg;
+////}
+////
+////f({ /*1*/ });
+////f(() => ({ /*2*/ }));
+////f(() => (({ /*3*/ })));
```
Comment (sandersn) [inline tests/cases/fourslash/completionListInObjectLiteral7.ts:12]: related to my other comment, do parenthesised object binding assignments still fail? If it is syntactically correct, I'd like to see a test for that too.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: tests/cases/fourslash/completionListInObjectLiteral7.ts (hunk 2 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/completionListInObjectLiteral7.ts:12]: I think that we cannot use `()` in object binding assignments

```ts
let x;
(({ x }) = { x: 1 })
  ^^^^^ Uncaught SyntaxError: Invalid left-hand side in assignment
```

File: src/services/completions.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/completions.ts:3759]: I've moved `walkUpParenthesizedExpressions`. Using parentheses inside assignment patterns is forbidden, so this is still more related to the second case where we need to get `contextualType` of expression.

File: tests/cases/fourslash/completionListInObjectLiteral7.ts (hunk 2 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/completionListInObjectLiteral7.ts:12]: @sandersn Do you have an example that I can use in a test?

Comment (sandersn) [reply tests/cases/fourslash/completionListInObjectLiteral7.ts:12]: You gave the one I was thinking about. If it's illegal then no need for a test.

**Review by sandersn — APPROVED** [review]
