### PR TITLE
Fix discriminant checking in contextual types

### LINKED ISSUE #23777: RangeError: Maximum call stack size exceeded with union type
**TypeScript Version:**  2.7.2 and 2.9.0-dev.20180430

**Search Terms:**
RangeError: Maximum call stack size exceeded

**Code**

* `git clone https://github.com/cyrilletuzi/angular-async-local-storage.git`
* `cd angular-async-local-storage`
* `git checkout newschema`
* `npm test` > OK
* Uncomment test in `src/lib/src/service/validation/json-validation.spec.ts` lines 570-576
* `npm test`

**Actual behavior:**
`RangeError: Maximum call stack size exceeded`

**Expected behavior:**
Should not crash.

**Context:**
Trying to do [an union type for JSONSchema](https://github.com/cyrilletuzi/angular-async-local-storage/blob/newschema/src/lib/src/service/validation/json-schema.ts).

When giving a wrong `type` value with a primitive, it's OK (error reported in VS Code but tsc not crashing):
```typescript
const test = jsonValidator.validate('test', { type: 1 });
```

But when giving a wrong `type` value with an array or object, no error is shown in VS Code (as if typings were valid) and `tsc` crashes with the error above:
  ```typescript
const test = jsonValidator.validate('test', { type: ['string', 'number'] });
```

What is strange is when doing the same in a [more simpler file](https://github.com/cyrilletuzi/angular-async-local-storage/blob/newschema/src/lib/src/service/validation/json-schema.test.ts) the typing error is reported.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #23777. Since the repro scenario is somewhat involved there is no regression test in this PR. However, I have manually verified that the issue is fixed for #23777.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15036,6 +15036,26 @@ namespace ts {
...
+        // recursive (and possibly infinite) invocations of getContextualType.
+        function isPossiblyDiscriminantValue(node: Expression): boolean {
+            switch (node.kind) {
+                case SyntaxKind.StringLiteral:
+                case SyntaxKind.NumericLiteral:
+                case SyntaxKind.NoSubstitutionTemplateLiteral:
+                case SyntaxKind.TrueKeyword:
+                case SyntaxKind.FalseKeyword:
+                case SyntaxKind.NullKeyword:
+                case SyntaxKind.Identifier:
```
Comment (weswigham) [inline src/compiler/checker.ts]: An identifier may end up being any type and cause a circularity still - while this change may happen to break the exact loop in the issue, there's _probably_ still a problem if you add an indirection.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -15049,8 +15069,8 @@ namespace ts {
             propLoop: for (const prop of node.properties) {
                 if (!prop.symbol) continue;
                 if (prop.kind !== SyntaxKind.PropertyAssignment) continue;
-                if (isDiscriminantProperty(contextualType, prop.symbol.escapedName)) {
-                    const discriminatingType = getTypeOfNode(prop.initializer);
+                if (isPossiblyDiscriminantValue(prop.initializer) && isDiscriminantProperty(contextualType, prop.symbol.escapedName)) {
+                    const discriminatingType = checkExpression(prop.initializer);
```
Comment (weswigham) [inline src/compiler/checker.ts]: I think it'd work much more uniformly to just check the initializer with the thus-far-known context, eg: `checkExpressionWithContextualType(prop.initializer, getTypeOfPropertyOfContextualType(contextualType, prop.symbol.escapedName), cloneTypeMapper(identityMapper))`, rather than a patchy syntactic kludge. Should also reduce how much work needs to be done.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: I'm not sure what you mean. The key here is that `checkIdentifier` will never ask for the contextual type of the identifier and therefore it can't cause a circularity issue.

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: I don't think so. There's nothing kludgy about this fix and it definitely reduces the amount of work more than what you suggest. When obtaining a contextual type we should *never* reach back down to the same type again unless we're absolutely sure that it won't again ask for a contextual type.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Also, literally any expression can be a discriminant here, see this, which works today and ths would break:
```ts
type A = {
    kind: "a",
    value: number
}

type B = {
    kind: "b",
    value: string
}

function getMode(): "a" {
    return "a";
}

const x: A | B = {
    kind: getMode(),
    value: 12
};

function needsNumber(x: number): void { }

needsNumber(x.value);
```
