### PR TITLE
Disallow line terminator after arrow function parameters, before =>

### LINKED ISSUE #2282: Arrow functions require no line terminator before arrow `=>` token
I just noticed this today while working on implementing rest parameters in arrow functions in v8. v8 and SpiderMonkey are both getting this wrong right now, but Traceur and Babel both get this right.

It's probably a pretty simple fix

### PR DESCRIPTION
**Pull request by caitp**
Closes #2282

### CODE REVIEW

**Comment by caitp** [comment]
quick attempt at a fix, some things are probably missing / test in wrong place / error messages not that helpful

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -3160,6 +3160,11 @@ module ts {
                 return undefined;
             }
 
+            // Must be no line terminator before token `=>`.
+            if (scanner.hasPrecedingLineBreak()) {
+                return undefined;
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: Wow, that was quick! I started a bit while I was in the office, but if you'd like to take this task on I wouldn't mind.

I actually had the idea of continuing to parse arrow functions exactly as before, but to report the error as part of our grammatical checking in `checker.ts`. Since `=> blah(blah, blahblah)` is not a valid expression in any context anyway, this should be acceptable, and it's ideal for language service scenarios.

However, the problem I ran into when I tried to fix this was that it's a real pain to work on the token-level in the checker.  So I wonder if the benefit of the idea is actually worth the cost. When I discussed with @CyrusNajmabadi, he seemed to favor the idea, but I'd like him to weigh in.

File: tests/cases/conformance/es6/arrowFunction/disallowLineTerminatorBeforeArrow.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+var f7 = (x: string, y: number, z = 10)
+    => { }
+var f8 = (x: string, y: number, z = 10) /*
+  */  => { }
+
+function foo(func: () => boolean) { }
+foo(()
+    => true);
+foo(()
+    => { return false; });
```
Comment (DanielRosenwasser) [inline tests/cases/conformance/es6/arrowFunction/disallowLineTerminatorBeforeArrow.ts]: Could we get a few more expression-bodied tests?

We should be testing different parsing contexts as well, so kill two birds with one stone:

```TypeScript
module m {
    class City {
        constructor(x: number, thing = ()
            => 100) {
        }
        
        public m = ()
            => 2 * 2 * 2
    }

    export enum Enum {
        claw = (()
            => 10)()
    }

    export var v = x
        => new City(Enum.claw);
}
```

**Comment by caitp** [comment]
> Could we get a few more expression-bodied tests?
>
> We should be testing different parsing contexts as well, so kill two birds with one stone:

Certainly

> However, the problem I ran into when I tried to fix this was that it's a real pain to work on the token-level in the checker. So I wonder if the benefit of the idea is actually worth the cost. 

Maybe it would be fine to flag whether a newline occured before the `=>` token and emit an error for that in the checker

**Comment by CyrusNajmabadi** [comment]
I agree with @DanielRosenwasser   We shoudl continue parsing these, but report an appropriate error (likely in the checker, when we do grammar checks) that the arrow function isn't legal.

File: src/compiler/parser.ts (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: Correct.  I would not do this here.  I would detect and parse out the arrow function, but then report later that it isn't valid.  This will help ensure that all the higher layers of the stack properly understand what's going on.

**Comment by caitp** [comment]
I'm not sure how to do this "work with tokens" thing in the checker, the approach I've taken is to add a boolean field to a new interface, and flag the error during parsing, but only report it during checking. It seemed like the simplest approach.

**Comment by CyrusNajmabadi** [comment]
Just add the equalsGreaterThanToken to the ArrowFunction interface.  You can see how we parse tokens into the tree with helpers like parseExpectedToken.  (If we don't have an ArrowFunction interface, then make one).  Thanks!

**Comment by caitp** [comment]
@CyrusNajmabadi how does the presence of the node in the interface make it easier to figure out if there was a line terminator or not? It looks like it could produce a better error message though (or at least the position of the error would be better). From a glance, I'd have to use `getLineAndCharacterOfPosition()`, and compare the computed line positions of the end of the parameters with the beginning of the arrow token. That seems like more work than is really needed. But, why not

**Comment by CyrusNajmabadi** [comment]
it doesn't necessarily make it easier.  But it's much more consistent with how we do the rest of our nodes.

>From a glance, I'd have to use getLineAndCharacterOfPosition(), and compare the computed line positions of the end of the parameters with the beginning of the arrow token. That seems like more work than is really needed. But, why not

That sounds right to me.

File: tests/baselines/reference/APISample_transform.js [hunk 3]
```diff
@@ -584,6 +584,9 @@ declare module "typescript" {
         name?: Identifier;
         body: Block | Expression;
     }
+    interface ArrowFunctionExpression extends FunctionExpression {
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/APISample_transform.js]: I think this should just be extending from `Expression` and `FunctionLikeDeclaration` (since it's not a `PrimaryExpression` nor does it have a name.

Comment (caitp) [inline tests/baselines/reference/APISample_transform.js]: Done

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -11225,7 +11225,18 @@ module ts {
 
         function checkGrammarFunctionLikeDeclaration(node: FunctionLikeDeclaration): boolean {
             // Prevent cascading error by short-circuit
-            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters);
+            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters) || checkGrammarArrowFunction(node);
+        }
+
+        function checkGrammarArrowFunction(node: FunctionLikeDeclaration): boolean {
+            if (node.kind === SyntaxKind.ArrowFunction && (<ArrowFunction>node).arrow) {
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: If you are an arrow function, i would assume you always have the .arrow.  Also, .arrow should be .equalsGreaterThanToken

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -11225,7 +11225,18 @@ module ts {
...
             // Prevent cascading error by short-circuit
-            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters);
+            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters) || checkGrammarArrowFunction(node);
+        }
+
+        function checkGrammarArrowFunction(node: FunctionLikeDeclaration): boolean {
+            if (node.kind === SyntaxKind.ArrowFunction && (<ArrowFunction>node).arrow) {
+                var arrowFunction = <ArrowFunction>node;
+                var sourceFile = getSourceFileOfNode(node);
+                if (getLineAndCharacterOfPosition(sourceFile, getTokenPosOfNode(arrowFunction.arrow, sourceFile)).line !== getLineAndCharacterOfPosition(sourceFile, arrowFunction.parameters.end).line) {
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: wrap after !==

File: src/compiler/parser.ts [hunk 6]
```diff
@@ -3008,7 +3009,9 @@ module ts {
             node.parameters.pos = parameter.pos;
             node.parameters.end = parameter.end;
 
-            parseExpected(SyntaxKind.EqualsGreaterThanToken);
+            if ((node.arrow = parseExpectedToken(SyntaxKind.EqualsGreaterThanToken, false, Diagnostics._0_expected, "=>"))) {
+                node.arrow.parent = node;
```
Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: You shouldn't set any parent explicitly while parsing.  It will happen during binding automatically.

File: src/compiler/types.ts [hunk 7]
```diff
@@ -652,6 +652,10 @@ module ts {
         body: Block | Expression;  // Required, whereas the member inherited from FunctionDeclaration is optional
     }
 
+    export interface ArrowFunction extends Expression, FunctionLikeDeclaration {
+        arrow: Node;
```
Comment (CyrusNajmabadi) [inline src/compiler/types.ts]: equalsGreaterThanToken

File: src/compiler/checker.ts (hunk 5 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I'd rather you just extracted the lines into individual variables and compared them

**Comment by CyrusNajmabadi** [comment]
Sorry.  That was a misreading on my part.  The change looks great.  Feel free to merge at any time.

**Comment by caitp** [comment]
hmm, I think it was slightly wrong though... the bottom branch won't ever be taken because a node is always created. I'll fix that.

File: src/compiler/parser.ts [hunk 8]
```diff
@@ -3035,9 +3036,10 @@ module ts {
                 return undefined;
             }
 
-            // If we have an arrow, then try to parse the body. Even if not, try to parse if we 
+            // If we have an arrow, then try to parse the body. Even if not, try to parse if we
             // have an opening brace, just in case we're in an error state.
-            if (parseExpected(SyntaxKind.EqualsGreaterThanToken) || token === SyntaxKind.OpenBraceToken) {
+            arrowFunction.equalsGreaterThanToken = parseExpectedToken(SyntaxKind.EqualsGreaterThanToken, false, Diagnostics._0_expected, "=>");
```
Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: parseExpectedToken will always return a token of type EqualsGreaterThanToken

Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: or

```typescript
var lastToken = token;
node.equalsGreaterThanToken = parseExpectedToken(...);
node.body = lastToken === SyntaxKind.EqualsGreaterThanToken || lastToken === SyntaxKind.OpenBraceToken
    ? parseArrowFunctionExpressionBody()
    : parseIdentifier();
```

**Comment by caitp** [comment]
done (I preferred the second approach). Sorry about the amended last commit, but it was a very minor change to use ternary instead of an if statement

**Comment by CyrusNajmabadi** [comment]
:+1:   Awesome job.  Thanks!

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -11246,7 +11246,20 @@ module ts {
...
-            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters);
+            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters) || checkGrammarArrowFunction(node);
+        }
+
+        function checkGrammarArrowFunction(node: FunctionLikeDeclaration): boolean {
+            if (node.kind === SyntaxKind.ArrowFunction) {
+                var arrowFunction = <ArrowFunction>node;
+                var sourceFile = getSourceFileOfNode(node);
+                var equalsGreaterThanLine = getLineAndCharacterOfPosition(sourceFile, getTokenPosOfNode(arrowFunction.equalsGreaterThanToken, sourceFile)).line;
+                var parametersLine = getLineAndCharacterOfPosition(sourceFile, arrowFunction.parameters.end).line;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Swap `parametersLine` and `equalsGreaterThanLine` parameters; also use the `end`s of `arrowFunction.equalsGreaterThanToken,` since the full start and end are on the same line.

**Comment by DanielRosenwasser** [comment]
Glad I realized it before signing off, but this is currently incorrect. We'll inappropriately give you an error in the following (I add the first just to iterate on):

```TypeScript 
// Should not be valid.
var func = (a: number): number
    => a;

// Should be valid.
var funk = (a: number
    ) => a;

// Should be valid.
var funkier = (a: number)
    : number => a;

// Should be valid.
var funkier = (a: number):
    number => a;
```

At least, I *think* these should be valid. @JsonFreeman and @CyrusNajmabadi can weigh in. Let's add that to the tests.

As for a fix, this is a bit of a hack - check whether or not the full start of the arrow (just `.start`) is on the same line as its end (`.end`).

**Comment by caitp** [comment]
you're right, I didn't consider the case with a type annotation for the return value at all (although I think the second case __should__ have worked, since I was using the "end" position for the parameters).

Anyways, yeah, the suggested fix solves that, and the extra tests with return value types are good.

**Comment by JsonFreeman** [comment]
Yes, @DanielRosenwasser is correct, those latter 3 should be valid. `funk` is allowed per the ES6 grammar, and the other two can be allowed by our grammar if we put `No LineTerminator Here` after the type annotation.

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -11357,7 +11357,20 @@ module ts {
...
         function checkGrammarFunctionLikeDeclaration(node: FunctionLikeDeclaration): boolean {
             // Prevent cascading error by short-circuit
-            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters);
+            return checkGrammarModifiers(node) || checkGrammarTypeParameterList(node, node.typeParameters) || checkGrammarParameterList(node.parameters) || checkGrammarArrowFunction(node);
+        }
+
+        function checkGrammarArrowFunction(node: FunctionLikeDeclaration): boolean {
+            if (node.kind === SyntaxKind.ArrowFunction) {
+                var arrowFunction = <ArrowFunction>node;
+                var sourceFile = getSourceFileOfNode(node);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I actually recall one of the other functions needing the sourceFile as well. Could we grab the sourceFile once in `checkGrammarFunctionLikeDeclaration` and pass it in as a parameter to these checkers?

**Comment by DanielRosenwasser** [comment]
I've made one last suggestion. After dealing with that and a merge conflict, I think this should be good to go.

**Comment by caitp** [comment]
done

File: src/compiler/parser.ts [hunk 11]
```diff
@@ -95,6 +95,7 @@ module ts {
                     visitNodes(cbNodes, (<FunctionLikeDeclaration>node).typeParameters) ||
                     visitNodes(cbNodes, (<FunctionLikeDeclaration>node).parameters) ||
                     visitNode(cbNode, (<FunctionLikeDeclaration>node).type) ||
+                    visitNode(cbNode, (<ArrowFunction>node).equalsGreaterThanToken) ||
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: This is weird, but I don't mind it terribly.

**Comment by DanielRosenwasser** [comment]
This looks great, thanks for the PR @caitp!
