### PR TITLE
Still generate signatures in SkipContextSensitive mode just to match on return types

### LINKED ISSUE #13118: Wrong inference from function return argument
**TypeScript Version:**  2.2.0-dev.20161221

**Code**

```ts
type SomeParams<A> = { a: A, enter: (a: A) => void }

function canYouInferThis<A>(fn: () => SomeParams<A>): { aa: A } {
  return { aa: fn().a }
}

const result = canYouInferThis(() => ({ a: { bla: 33 }, enter: a => undefined }))
result.aa.bla // Doesn't compile
```

**Expected behavior:**
The `A` parameter should be inferred to be `{ bla: number }`. It seems completely unambiguous to me.
Failing that, I would expect a warning about ambiguous inferred types.

**Actual behavior:**
The type of `A` is silently inferred to be `{}`

### PR DESCRIPTION
**Pull request by weswigham**
(during inference).

Fixes #13118

I've kept it minimal - we only dive into the return type if there's a contextual return type whose contextual checking could fix a type parameter before the second, context-sensitive pass. It's worth noting that this has inherited our current slightly flawed definition of a context sensitive function return - namely that only arrow return expressions can be context sensitive (`return` statements cannot). That `TODO` is probably worth fixing at some point.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20543,6 +20546,12 @@ namespace ts {
 
             // The identityMapper object is used to indicate that function expressions are wildcards
             if (checkMode === CheckMode.SkipContextSensitive && isContextSensitive(node)) {
+                // Skip parameters, return signature with return type that retains noncontextual parts so inferences can still be drawn in an early stage
+                if (!getEffectiveReturnTypeNode(node) && hasContextSensitiveReturnExpression(node)) {
+                    const returnType = getReturnTypeFromBody(node, checkMode);
+                    const singleReturnSignature = createSignature(undefined, undefined, undefined, emptyArray, returnType, /*resolvedTypePredicate*/ undefined, 0, /*hasRestParameter*/ false, /*hasLiteralTypes*/ false);
+                    return createAnonymousType(node.symbol, emptySymbols, [singleReturnSignature], emptyArray, undefined, undefined);
```
Comment (weswigham) [inline src/compiler/checker.ts]: Is it worth caching this type in some way? Like having an internal `() => T` that I simply instantiate here?

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
@typescript-bot test this now that RWC is clean _and_ I've merged master 🤦‍♂️
