### PR TITLE
Don't let the additional property setting on an object show up as a definition to tsserver

### LINKED ISSUE #30246: CTRL+Click -> go to file is weird
- VSCode Version: 1.32.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. CTRL+click a react component being used somewhere
2. Now CTRL+click on a TS definition in the same file.

No. 1 opens a definition thingy, which has begun to pop up almost all the time.
No. 2 opens the definition file and shifts focus.

I have no idea what has been changed or why. CTRL+clicking is not the same anymore and has gotten seriously frustrating. I've no idea what to do besides making this really bad issue that doesn't explain anything properly. I'm just sure something has changed and in my perception to the worse.. Atleast I'd like some better update messages for such core functionality.

I used to be able to CTRL+click and continue working. Now I have to spendd upwards of 30 seconds to figure everything out.

Here's what I think should happen: CTRL+click has the same functionality no matter where you do it... that's it. Make a setting to 'peek' definition or whatever you call it and an option to open the file in which the clicked entity exists.

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by orta**
Fixes #30246 by filtering out property setters. but also making sure that you can still jump to those field 
 definitions when the symbol you clicked on is specifically  targeted

Prior to this change, clicking on `Component` would show`const Component...` and `Component.displayName`. An initially over-eager implementation didn't allow for clicking the `displayName` - so I included a test for that too.

### CODE REVIEW

File: src/services/goToDefinition.ts [hunk 1]
```diff
@@ -233,20 +233,24 @@ namespace ts.GoToDefinition {
     }
 
     function getDefinitionFromSymbol(typeChecker: TypeChecker, symbol: Symbol, node: Node): DefinitionInfo[] | undefined {
-        return getConstructSignatureDefinition() || getCallSignatureDefinition() || map(symbol.declarations, declaration => createDefinitionInfo(declaration, typeChecker, symbol, node));
+        // There are cases when you extend a function by adding properties to it afterwards,
+        // we want to strip those extra properties
+        const filteredDeclarations = symbol.declarations && symbol.declarations.filter(d =>  !isAssignmentDeclaration(d) || d === symbol.valueDeclaration) || undefined;
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts]: Use filter(symbol.declarations, …)

File: tests/cases/fourslash/goToDefinitionPropertyAssignment.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+////
+//// [|/*FunctionClick*/Component|]
+////
+//// Component.[|/*PropertyClick*/displayName|]
+
+verify.goToDefinition("FunctionClick", "FunctionResult")
+
+verify.goToDefinition("PropertyClick", "PropertyResult")
+
+// export const Component = () => { return "OK"}
```
Comment (sheetalkamat) [inline tests/cases/fourslash/goToDefinitionPropertyAssignment.ts]: remove these extra statements?
