### PR TITLE
Fix meta property symbol lookup

### LINKED ISSUE #48731: [4.7 Beta/Dev] import.meta reports invalid "Cannot find name 'meta' ts(2304)" error
# Bug Report

### 🔎 Search Terms

"Cannot find name 'meta'" "2304"

### 🕗 Version & Regression Information

- This is an issue with new "nodenext" support

### ⏯ Playground Link

The issue doesn't present in the playground (however it has it's own issues with the code sample).

Instead [here is a repo with the issue](https://github.com/Jamesernator/ts-import-meta-issue).

### 💻 Code

```ts
const u = new URL(import.meta.url);
```

### 🙁 Actual behavior

It produces the error:

```
Cannot find name 'meta'.ts(2304)
```

The error vanishes if you edit `tsconfig` in any way, however if you then edit the file again it reappears.

Screenshot from 2022-04-17 05-23-48

While this error is shown, the rest of the behaviour of `import.meta` is still fine, like the type is correct and such.

### 🙂 Expected behavior

There should be no error.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #48731

Our tests never caught the bug before we merged the checkers because there's no difference to goto-def between an outright missing symbol and a symbol with no declarations.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -41972,15 +41972,20 @@ namespace ts {
...
                 }
-                else if (isMetaProperty(parent)) {
-                    const parentType = getTypeOfNode(parent);
-                    const propertyDeclaration = getPropertyOfType(parentType, (node as Identifier).escapedText);
-                    if (propertyDeclaration) {
-                        return propertyDeclaration;
-                    }
-                    if (parent.keywordToken === SyntaxKind.NewKeyword) {
+                else if (isMetaProperty(parent) && parent.name === node) {
+                    if (parent.keywordToken === SyntaxKind.NewKeyword && idText(node as Identifier) === "target") {
```
Comment (weswigham) [inline src/compiler/checker.ts:41976]: Driveby consistency fix for `new.target` as well - other `new.whatevers` no longer mistakenly have the `new.target` symbol (can be seen in some symbol baseline updates).

File: tests/cases/fourslash/goToDefinitionImportMeta.ts [hunk 2]
```diff
@@ -11,3 +11,5 @@
 ////}
 
 verify.goToDefinition("reference", []);
+
+verify.noErrors();
```
Comment (weswigham) [inline tests/cases/fourslash/goToDefinitionImportMeta.ts:15]: Yeah, other than the symbol baseline updates (which you could argue also showed the missing symbol problem, even if they don't call it out hard), this was all the new testing required to actually detect the issue.

**Review by andrewbranch — APPROVED** [review]
