### PR TITLE
Handle jsx runtime implicit synthetic import in find all references

### LINKED ISSUE #51221: Start < 0 in BuilderIO/qwik
Issue in [BuilderIO/qwik](https://github.com/BuilderIO/qwik) found in #51218

`Error: start < 0`

```
Req #6872 - references
    at createTextSpan (/typescript-4.9.0-dev.20221018/lib/tsserver.js:12557:19)
    at Object.createTextSpanFromBounds (/typescript-4.9.0-dev.20221018/lib/tsserver.js:12566:16)
    at getTextSpan (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140296:23)
    at entryToDocumentSpan (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140193:32)
    at toReferenceEntry (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140179:32)
    at toReferencedSymbolEntry (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140173:34)
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:140033:70
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:140033:44
    at Object.mapDefined (/typescript-4.9.0-dev.20221018/lib/tsserver.js:621:30)
    at Object.findReferencedSymbols (/typescript-4.9.0-dev.20221018/lib/tsserver.js:140028:85)
    at Object.findReferences (/typescript-4.9.0-dev.20221018/lib/tsserver.js:169125:41)
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:179297:53
    at searchPosition (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179494:38)
    at getPerProjectReferences (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179462:42)
    at getReferencesWorker (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179294:37)
    at IOSession.Session.getReferences (/typescript-4.9.0-dev.20221018/lib/tsserver.js:180901:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/typescript-4.9.0-dev.20221018/lib/tsserver.js:179734:61)
    at /typescript-4.9.0-dev.20221018/lib/tsserver.js:181869:96
    at IOSession.Session.executeWithRequestId (/typescript-4.9.0-dev.20221018/lib/tsserver.js:181860:28)
    at IOSession.Session.executeCommand (/typescript-4.9.0-dev.20221018/lib/tsserver.js:181869:41)
    at IOSession.Session.onMessage (/typescript-4.9.0-dev.20221018/lib/tsserver.js:181897:35)
    at Interface.<anonymous> (/typescript-4.9.0-dev.20221018/lib/tsserver.js:186023:31)
```

<details>
<summary><h3>Last few requests</h3></summary>

```json
{"seq":6869,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx","projectRootPath":"@PROJECT_ROOT@"}]}}
{"seq":6870,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx"}},"skipDestructiveCodeActions":true}}
{"seq":6871,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx"}}
{"seq":6872,"type":"request","command":"references","arguments":{"file":"@PROJECT_ROOT@/packages/qwik/src/core/render/ssr/render-ssr.unit.tsx","line":1,"offset":31}}

```

</details>

<details>
<summary><h3>Repro Steps</h3></summary>
<ol>
<li><code>git clone https://github.com/BuilderIO/qwik --recurse-submodules</code></li>
<li>In dir <code>qwik</code>, run <code>git reset --hard c41b93e6df23a72ab03eca29b44adbe94716c836</code></li>
<li>Back in the initial folder, download <code>RepoResults4/BuilderIO.qwik.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=136652&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./qwik ./BuilderIO.qwik.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #51221

### CODE REVIEW

File: src/services/findAllReferences.ts [hunk 1]
```diff
@@ -840,6 +840,14 @@ namespace ts.FindAllReferences {
                     // import("foo") with no qualifier will reference the `export =` of the module, which may be referenced anyway.
                     return nodeEntry(reference.literal);
                 }
+                else if (reference.kind === "implicit") {
+                    // Return either: The first JSX node in the file, the first statement of the file, or the whole file if neither of those exist
+                    const range = forEachChildRecursively(
+                        reference.referencingFile,
+                        n => isJsxElement(n) || isJsxSelfClosingElement(n) || isJsxFragment(n) ? n : undefined
```
Comment (DanielRosenwasser) [inline src/services/findAllReferences.ts:847]: Hm - in very large files, this could be a full tree-walk. I know it's a *transform* flag, but can you use `TransformFlags.ContainsJsx` to make this a little more clever?

File: src/services/findAllReferences.ts [hunk 2]
```diff
@@ -840,6 +840,14 @@ namespace ts.FindAllReferences {
                     // import("foo") with no qualifier will reference the `export =` of the module, which may be referenced anyway.
                     return nodeEntry(reference.literal);
                 }
+                else if (reference.kind === "implicit") {
+                    // Return either: The first JSX node in the file, the first statement of the file, or the whole file if neither of those exist
+                    const range = forEachChildRecursively(
+                        reference.referencingFile,
+                        n => isJsxElement(n) || isJsxSelfClosingElement(n) || isJsxFragment(n) ? n : undefined
+                    ) || reference.referencingFile.statements[0] || reference.referencingFile;
```
Comment (DanielRosenwasser) [inline src/services/findAllReferences.ts:848]: I thought a bit more about the `statements[0]` case. It would be very weird if the first statement in your file is an unrelated import...

Maybe we need to find the first statement that's not an import or an export with a module specifier?

File: src/services/findAllReferences.ts (hunk 1 above)
Comment (weswigham) [reply src/services/findAllReferences.ts]: Done

File: src/services/findAllReferences.ts (hunk 2 above)
Comment (weswigham) [reply src/services/findAllReferences.ts]: Not sure it matters - `import "./thing"` being the ref is probably just as odd as `var x = 1`. Point is really that the file itself is the reference, we just don't want to say "the whole file is the reference" because it'd be a really really big and useless usage highlight span.

**Review by DanielRosenwasser — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

File: src/services/findAllReferences.ts [hunk 3]
```diff
@@ -1126,6 +1130,14 @@ export namespace Core {
                 // import("foo") with no qualifier will reference the `export =` of the module, which may be referenced anyway.
                 return nodeEntry(reference.literal);
             }
+            else if (reference.kind === "implicit") {
+                // Return either: The first JSX node in the file, the first statement of the file, or the whole file if neither of those exist
+                const range = forEachChildRecursively(
+                    reference.referencingFile,
+                    n => !(n.transformFlags & TransformFlags.ContainsJsx) ? "skip" : isJsxElement(n) || isJsxSelfClosingElement(n) || isJsxFragment(n) ? n : undefined
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts:1137]: The implicit import can be for "tslib" as well right so dont we need to handle/ignore that

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

**Review by sheetalkamat — COMMENTED** [review]
Because tslib came up as synthesized node, can we add test for that.

File: tests/baselines/reference/tslibFindAllReferencesOnRuntimeImportWithPaths1.baseline.jsonc [hunk 4]
```diff
@@ -0,0 +1,38 @@
+// === findAllReferences ===
+// === /tests/cases/fourslash/project/src/foo.ts ===
+// [|<|import * as x from /*FIND ALL REFS*/"[|tslib|]";|]|>
```
Comment (sheetalkamat) [inline tests/baselines/reference/tslibFindAllReferencesOnRuntimeImportWithPaths1.baseline.jsonc:3]: Since we are already highlighting import do we really want first statement as well ?

Comment (weswigham) [reply tests/baselines/reference/tslibFindAllReferencesOnRuntimeImportWithPaths1.baseline.jsonc:3]: Yep - there's two references in this file, after all - the implicit one and the explicit one.

**Review by DanielRosenwasser — APPROVED** [review]
The behavior could be better, but I guess I just want the crash gone already.
