### PR TITLE
Missing import codefix: Take scoped packages (@foo/bar) into consideration

### LINKED ISSUE #15223: Auto-import quickfix : wrong strategy for import paths
**TypeScript Version:**  2.2.1

**Actual behavior:**
With the new auto-import quick fix in TS2.2 (usable in VS Code), the suggested paths for missing imports are behaving strangely.

If I already have something imported from one package, let's say : 
`import { Component } from '@angular/core';`
then the auto-import quick fix for next missing imports from the same package will suggest the good solution : 
`"Add OnInit from existing import declaration from @angular/core"`
resulting in : 
`import { Component, OnInit } from '@angular/core';`

But if nothing is yet imported from one package, the suggested auto-imports from quick fix will be : 
`"Import OnInit from @angular/core/src/metadata"`
`"Import OnInit from @angular/core/src/core"`
`"Import OnInit from @angular/core/public_api"`
`"Import OnInit from @angular/core/core"`
resulting for example in : 
`import { OnInit } from '@angular/core/core';`
which is wrong.

**Expected behavior:**
As it's a common pattern for a package to do a main entry file (index.ts), re-exporting all the public API, and for TypeScript to have a consistent behavior, the auto-import quick fix should suggest the top-level path only : 
`"Import OnInit from @angular/core"`
instead of low-level paths.

### PR DESCRIPTION
**Pull request by minestarks**
Fixes #15223

When a package name has a [scope](https://docs.npmjs.com/misc/scope), like ```@angular/core```, we weren't able to locate package.json correctly, only looking under the ```@angular``` directory. Which meant that we never read the 'main```/`typings``` property in package.json which would have helped us simplify the import module specifier. 

This fixes the parsing of the path so we can find package.json.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -592,6 +593,15 @@ namespace ts.codefix {
                                 }
                                 break;
                             case States.NodeModules:
+                                if (fullPath.charAt(partStart + 1) === "@") {
+                                    state = States.Scope;
+                                }
+                                else {
+                                    packageRootIndex = partEnd;
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: Another way to express this would be `goto case States.PackageContent`.  That would have the benefit of emphasizing that the two states are the same except for the initial check in `NodeModules`.

Comment (minestarks) [inline src/services/codefixes/importFixes.ts]: That's just what I was looking for thanks, I didn't know about that.

**Comment by aozgaa** [comment]
LGTM
