### PR TITLE
fix(54068): Organize Imports removes first deprecated JSDoc comment

### LINKED ISSUE #54068: Organize Imports removes first `@deprecated` JSDoc comment
# Bug Report

### 🔎 Search Terms

- jsdoc
- organize imports
- exports
- deprecated

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDeAoOcD0AqPOAAQBNgwpgBjAQxmBLgFUBnVAGQlpgEsIA7ACLAAZj349eAlnHEt6NRnhxY4nbnyGjxkzTJoyAgiRKUWLYWIlT+LADSr1dTZZ037q-IVLlK3BsxscAAKwFAsAq7WerK2Ckoq2KHhkdrR0nAGcAByNAC2wFG60g5JYRFaVsW2pbgExGQU1HQBrKjJFQAqkgA2hWnVMnLxcMqqHQLdMH1F7pkyuQVTMwPutRP8y-1VaxgAvnAiUBB5cADkAHQ4ZDt6ZwDcGKCQsAjIqJjYXg2+zfSMbTgAGFzAAxACu-CoNk671i8mAilGiWBYMh0M0sJQ82BAGVcRCoTZaiCWISMZN3rVvj4mv4AUFSbiwDQqMAsahhoiEqomSy2RycUD8czWcASeZRQKqftDsdTpccHkICRwX0WDgqBAetAHhggA)

### 💻 Code

```ts
export type {
  /** @deprecated Use LocationDefinitions instead */
  LocationDefinitions as AddressDefinitions,
  LocationDefinitions,
  /** @deprecated Use PersonDefinitions instead */
  PersonDefinitions as NameDefinitions,
  PersonDefinitions,
  /** @deprecated Use PersonTitleDefinitions instead */
  PersonTitleDefinitions as NameTitleDefinitions,
  PersonTitleDefinitions,
} from './definitions';
export type {
  /** @deprecated Use CssFunctionType instead */
  CssFunctionType as CSSFunction,
  CssFunctionType,
  /** @deprecated Use CssSpaceType instead */
  CssSpaceType as CSSSpace,
  CssSpaceType,
} from './modules/color';
```

### 🙁 Actual behavior

The first JSDoc comment gets removed when executing _Organize Imports_

```ts
export type {
  LocationDefinitions as AddressDefinitions,
  LocationDefinitions,
  /** @deprecated Use PersonDefinitions instead */
  PersonDefinitions as NameDefinitions,
  PersonDefinitions,
  /** @deprecated Use PersonTitleDefinitions instead */
  PersonTitleDefinitions as NameTitleDefinitions,
  PersonTitleDefinitions,
} from './definitions';
export type {
  /** @deprecated Use CssFunctionType instead */
  CssFunctionType as CSSFunction,
  CssFunctionType,
  /** @deprecated Use CssSpaceType instead */
  CssSpaceType as CSSSpace,
  CssSpaceType,
} from './modules/color';
```

### 🙂 Expected behavior

The comment should not get removed

```ts
export type {
  /** @deprecated Use LocationDefinitions instead */
  LocationDefinitions as AddressDefinitions,
  LocationDefinitions,
  /** @deprecated Use PersonDefinitions instead */
  PersonDefinitions as NameDefinitions,
  PersonDefinitions,
  /** @deprecated Use PersonTitleDefinitions instead */
  PersonTitleDefinitions as NameTitleDefinitions,
  PersonTitleDefinitions,
} from './definitions';
export type {
  /** @deprecated Use CssFunctionType instead */
  CssFunctionType as CSSFunction,
  CssFunctionType,
  /** @deprecated Use CssSpaceType instead */
  CssSpaceType as CSSSpace,
  CssSpaceType,
} from './modules/color';
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #54068

### CODE REVIEW

File: src/services/organizeImports.ts [hunk 1]
```diff
@@ -137,7 +136,7 @@ export function organizeImports(
         // on the first import because it is probably the header comment for the file.
         // Consider: we could do a more careful check that this trivia is actually a header,
         // but the consequences of being wrong are very minor.
```
Comment (sandersn) [inline src/services/organizeImports.ts:138]: this comment should probably be updated -- is this the more careful check it mentions? Is deleting the `@deprecated` a consequence of being wrong? (in which case it's 'minor' instead of 'very minor', or something like that)

Comment (a-tarasyuk) [reply src/services/organizeImports.ts:138]: I'm not entirely certain about the comment - whether it's considered minor or very minor 😄 . The issue lies in the usage of suppressLeadingTrivia, which employs `forEachChild` and navigates to the first export clause. However, what we actually need here is to omit comments related to the root of the `ImportDeclaration` node.

**Review by sandersn — APPROVED** [review]
