### PR TITLE
In import fixes, use a ".js" extension if other imports do

### LINKED ISSUE #19019: Add file extensions when auto-completing import paths
_From @Rich-Harris on October 6, 2017 14:58_

- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.2.0
vscode-eslint|dba|1.3.2
prettier-vscode|esb|0.24.0
vscode-import-cost|wix|2.5.0

---

Steps to Reproduce:

1. Open or create a JavaScript file
2. Start typing `import x from './` followed by the name of a sibling file

Reproduces without extensions: Yes

---

When you start writing a local `import` statement, the intellisense helper will offer up `foo` and `bar` rather than `foo.js` and `bar.js`. Extensionless imports is a Node idiom that is **incompatible with browser module loaders** — adding the file extension would increase browser compatibility with no ill-effect on Node apps (to the contrary, it speeds up [module resolution](https://nodejs.org/api/modules.html#modules_all_together), and I'd argue it makes code more explicit and readable).

I wonder if you would consider changing the behaviour to add file extensions by default?

_Copied from original issue: Microsoft/vscode#35730_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19019

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -598,9 +604,13 @@ namespace ts.codefix {
...
     }
 
-    function removeExtensionAndIndexPostFix(fileName: string, options: CompilerOptions): string {
+    function removeExtensionAndIndexPostFix(fileName: string, options: CompilerOptions, addJsExtension: boolean): string {
         const noExtension = removeFileExtension(fileName);
-        return getEmitModuleResolutionKind(options) === ModuleResolutionKind.NodeJs ? removeSuffix(noExtension, "/index") : noExtension;
+        return addJsExtension
+            ? noExtension + ".js"
+            : getEmitModuleResolutionKind(options) === ModuleResolutionKind.NodeJs
+            ? removeSuffix(noExtension, "/index")
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts]: I don't know the JS/TS convention, but I'm using to seeing these lines indented.

File: tests/cases/fourslash/importNameCodeFix_jsExtension.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+// @noLib: true
+
+// @Filename: /a.ts
+////export function a() {}
+
+// @Filename: /b.ts
+////export function b() {}
+
+// @Filename: /c.ts
+////import { a } from "./a.js";
```
Comment (amcasey) [inline tests/cases/fourslash/importNameCodeFix_jsExtension.ts]: For documentation purposes, it might be nice to add a test where some imports have extensions and others do not.  (It looks like absolute paths might also be treated specially.)

**Comment by andy-ms** [comment]
Ideally we would have an option for this (#20619) but yeah, for now we will rely on the user manually correcting the first import.
