### PR TITLE
Do not await iterated value in for-await-of

### LINKED ISSUE #21115: Using for-await-of should resolve the Promise?
**TypeScript Version:**
- typescript@2.6.2
- typescript@2.7.0-dev.20180110

**Code**

```ts
declare function require(name:string);

(<any> Symbol).asyncIterator = Symbol.asyncIterator || Symbol.for("Symbol.asyncIterator");

const fetchlike = function(url) {
  // return new pending promise
  return new Promise((resolve, reject) => {
    // select http or https module, depending on reqested url
    const lib = url.startsWith('https') ? require('https') : require('http');
    const request = lib.get(url, (response) => {
      // handle http errors
      if (response.statusCode < 200 || response.statusCode > 299) {
         reject(new Error('Failed to load page, status code: ' + response.statusCode));
       }
      // temporary data holder
      const body = [];
      // on every content chunk, push it to the data array
      response.on('data', (chunk) => body.push(chunk));
      // we are done, resolve promise with those joined chunks
      response.on('end', () => resolve(body.join('')));
    });
    // handle connection errors of the request
    request.on('error', (err) => reject(err))
    })
};

async function example() {
  const arrayOfFetchPromises = [
    fetchlike('http://example.com'),
    fetchlike('http://example.com'),
  ];

  // Regular iterator:
  for (const item of arrayOfFetchPromises) {
    console.log(item); // Logs a promise
  }

  // for-await-of iterator:  
  for await (const item of arrayOfFetchPromises) {
    console.log(item); // Logs a response
  }
}

example()
```

`tsc --lib es2017,esnext.asynciterable,dom Untitled-1.ts && node Untitled-1.js`

**Actual behavior:**

`item` is a Promise in the for-await-of iterator block

imgur

Doing this causes error:

```ts
  for await (const item of arrayOfFetchPromises) {
    console.log(item.length); // TS error
  }
```

```ts
  for await (const item of arrayOfFetchPromises) {
    console.log((item as any).length);
    // not error because typecasted to any, logs valid result
  }
```

**Expected behavior:**

In the for-await-of iterator block,`item` should not be a Promise, because it's the actual value instead of a Promise

### PR DESCRIPTION
**Pull request by rbuckton**
This change more closely aligns with the specified `for-await-of` semantics, per [13.7.5.13](https://tc39.github.io/ecma262/#sec-runtime-semantics-forin-div-ofbodyevaluation-lhs-stmt-iterator-lhskind-labelset), step 6.d-6.h. At no time during those steps is there an Await for _nextValue_.

Fixes #21115

### CODE REVIEW

File: src/harness/unittests/forAwaitOfEvaluation.ts [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+            const module = evaluate(compile(`
+            let i = 0;
+            const iterator = {
+                [Symbol.iterator]() { return this; },
+                next() {
+                    switch (i++) {
+                        case 0: return { value: 1, done: false };
+                        case 1: return { value: Promise.resolve(2), done: false };
+                        case 2: return { value: new Promise<number>(resolve => setTimeout(resolve, 100, 3)), done: false };
+                        default: return { value: undefined: done: true };
```
Comment (ajafff) [inline src/harness/unittests/forAwaitOfEvaluation.ts]: there is a typo on this line: `undefined:` should be `undefined,`
Same in all other test cases below

**Comment by rbuckton** [comment]
@mhegazy do you want this ported to `release-2.9` as well?

**Comment by mhegazy** [comment]
yes please.
