### PR TITLE
Infer fixed-size tuples from infer type parameters with extends clauses at variadic positions

### LINKED ISSUE #51138: Inferred subtuple types in `extends` expression not narrowed if variadic (i.e. has a rest element)
# Bug Report

Given the following behavior, which correctly narrows a subtuple:

Screen Shot 2022-10-10 at 11 02 28 AM

One would expect similar narrowing when a tuple involves a rest element, but no narrowing occurs:

Screen Shot 2022-10-10 at 11 02 40 AM

Fixing this bug would be useful as a non-recursive method of grabbing a subtuple of a predefined length, while also maintaining the subtuple's labels—which I think cannot be done today.

### 🔎 Search Terms

`narrowing, tuple, extend, variadic`

### 🕗 Version & Regression Information

Typescript `4.7`, `4.8`, and `4.9.0-dev.20221004`

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about tuples (and labeled tuples), conditional types, type inference.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEDkEMCdoewO4GdSRQUwB4Ad0GMAXdAEwCgCBPXUAZQFcAjAFTuwCYAxAS0xIBl0AOwDmBABYAeJqCxFBxFHUEBrQYkEBtALoA+UAF5S02UIWgNAOisAKLoIBm6aKABCMzHLMbIgigBpUXy0ASgCfCi1SAH5XUgAuUEF0ADcnAG5STMpqemZWTh5+IVExJnQkAgNaRhZ2bl5iARFxCW8EgAYAhgSARgC8BME6AFsGJ10MzJAIGHgEO2FEuEq4PDw6WAXUDBxCElBAXg3AcR3yKnRqvPYANRguSGIuPCl3T0UVNQRNXQMjF9MUSw2OyOZxuEzyAHhMJBUKgKwWcKRGIueKJFLpLJnC61Ng3aB3B54MoVKq5HF4gmPVqQDpdXoBeEDRIjMbQbQTIA)

### 💻 Code

```ts
// Narrows as expected
type SubTup2FixedLength<T extends unknown[]> =
T extends [...(infer B extends [any, any]), any]
? B
: never;


type SubTup2FixedLengthTest = SubTup2FixedLength<[a: 0, b: 1, c: number]>;


// Narrowing not occurring as expected 👇
type SubTup2Variadic<T extends unknown[]> =
T extends [...(infer B extends [any, any]), ...any]
? B
: never;

type SubTup2VariadicTest = SubTup2Variadic<[a: 0, b: 1, ...c: number[]]>;
```

### 🙁 Actual behavior

Screen Shot 2022-10-10 at 11 02 40 AM

### 🙂 Expected behavior

[a: 0, b: 1]
```

### PR DESCRIPTION
**Pull request by Andarist**
Fixes #51138

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -23326,13 +23326,39 @@ namespace ts {
...
+                                if (middleLength === 2) {
+                                    if (elementFlags[startLength] & elementFlags[startLength + 1] & ElementFlags.Variadic && isTupleType(source)) {
+                                        // Middle of target is [...T, ...U] and source is tuple type
+                                        const impliedArity = getInferenceInfoForType(elementTypes[startLength])?.impliedArity;
+                                        if (impliedArity !== undefined) {
+                                            // Infer slices from source based on implied arity of T.
+                                            inferFromTypes(sliceTupleType(source, startLength, endLength + sourceArity - impliedArity), elementTypes[startLength]);
+                                            inferFromTypes(sliceTupleType(source, startLength + impliedArity, endLength), elementTypes[startLength + 1]);
+                                        }
+                                    }
```
Comment (Andarist) [inline src/compiler/checker.ts:23338]: this case was already here, it just got indented more since I put all 3 cases (1 old, 2 new ones) within the `if (middleLength === 2)` block

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -23326,13 +23326,39 @@ namespace ts {
...
+                                        // if T is constrained by a fixed-size tuple we might be able to use its arity to infer T
+                                        const param = getInferenceInfoForType(elementTypes[startLength + 1])?.typeParameter;
+                                        const constraint = param && getBaseConstraintOfType(param);
+                                        if (constraint && isTupleType(constraint) && !constraint.target.hasRestElement) {
+                                            const impliedArity = constraint.target.fixedLength;
+                                            const endIndex = sourceArity - getEndElementCount(target.target, ElementFlags.Fixed);
+                                            const startIndex = endIndex - impliedArity;
+                                            const trailingSlice = createTupleType(getTypeArguments(source).slice(startIndex, endIndex), source.target.elementFlags.slice(startIndex, endIndex),
+                                                /*readonly*/ false, source.target.labeledElementDeclarations && source.target.labeledElementDeclarations.slice(startIndex, endIndex));
```
Comment (Andarist) [inline src/compiler/checker.ts:23359]: This is based on the content of the `sliceTupleType`. However, I wasn't able to reuse that function as the purpose of this slice is different here and `sliceTupleType` wouldn't work for it - I didn't find another instance of such a "trailing slice" in the codebase so I've just inlined the thing here and adjusted for the needs here.

**Review by weswigham — APPROVED** [review]
I think this looks pretty good, though it'll need a sync to `main`, and some extended test suites run, just in case.

**Comment by Andarist** [comment]
@weswigham I've synced this with main. You can trigger those extended test suites now.

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot user test this
@typescript-bot test this
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -23470,13 +23470,39 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                                }
+                                else if (elementFlags[startLength] & ElementFlags.Variadic && elementFlags[startLength + 1] & ElementFlags.Rest) {
+                                    // Middle of target is [...T, ...rest] and source is tuple type
+                                    // if T is constrained by a fixed-size tuple we might be able to use its arity to infer T
+                                    const param = getInferenceInfoForType(elementTypes[startLength])?.typeParameter;
+                                    const constraint = param && getBaseConstraintOfType(param);
+                                    if (constraint && isTupleType(constraint) && !constraint.target.hasRestElement) {
+                                        const impliedArity = constraint.target.fixedLength;
+                                        inferFromTypes(sliceTupleType(source, startLength, sourceArity - (startLength + impliedArity)), elementTypes[startLength]);
+                                    }
```
Comment (gabritto) [inline src/compiler/checker.ts:23491]: I believe we also need to infer into the rest element here, if the source arity allows (i.e. there are left over elements after inferring into the tuple constraint). Right now, we're only inferring into the variadic type, so we don't infer into the rest element in a case like this:
```ts
type SubTup2Variadic2<T extends unknown[]> = T extends [
    ...infer B extends [any, any],
    ...(infer C)[]
]
    ? [...B, ...[C]]
    : never;

type SubTup2Variadic2Test = SubTup2Variadic2<[a: 0, b: 1, ...c: number[]]>; // Currently [0, 1, unknown], should be [0, 1, number]
```

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -23470,13 +23470,39 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                                    const param = getInferenceInfoForType(elementTypes[startLength + 1])?.typeParameter;
+                                    const constraint = param && getBaseConstraintOfType(param);
+                                    if (constraint && isTupleType(constraint) && !constraint.target.hasRestElement) {
+                                        const impliedArity = constraint.target.fixedLength;
+                                        const endIndex = sourceArity - getEndElementCount(target.target, ElementFlags.Fixed);
+                                        const startIndex = endIndex - impliedArity;
+                                        const trailingSlice = createTupleType(getTypeArguments(source).slice(startIndex, endIndex), source.target.elementFlags.slice(startIndex, endIndex),
+                                            /*readonly*/ false, source.target.labeledElementDeclarations && source.target.labeledElementDeclarations.slice(startIndex, endIndex));
+                                                inferFromTypes(trailingSlice, elementTypes[startLength + 1]);
```
Comment (gabritto) [inline src/compiler/checker.ts:23504]: Indentation seems off here.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -23470,13 +23470,39 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                                    // Middle of target is [...rest, ...T] and source is tuple type
+                                    // if T is constrained by a fixed-size tuple we might be able to use its arity to infer T
+                                    const param = getInferenceInfoForType(elementTypes[startLength + 1])?.typeParameter;
+                                    const constraint = param && getBaseConstraintOfType(param);
+                                    if (constraint && isTupleType(constraint) && !constraint.target.hasRestElement) {
+                                        const impliedArity = constraint.target.fixedLength;
+                                        const endIndex = sourceArity - getEndElementCount(target.target, ElementFlags.Fixed);
+                                        const startIndex = endIndex - impliedArity;
+                                        const trailingSlice = createTupleType(getTypeArguments(source).slice(startIndex, endIndex), source.target.elementFlags.slice(startIndex, endIndex),
```
Comment (gabritto) [inline src/compiler/checker.ts:23502]: Is there some reason to use `createTupleType` instead of `sliceTupleType` here?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -23470,13 +23470,39 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                                            /*readonly*/ false, source.target.labeledElementDeclarations && source.target.labeledElementDeclarations.slice(startIndex, endIndex));
+                                                inferFromTypes(trailingSlice, elementTypes[startLength + 1]);
+                                    }
```
Comment (gabritto) [inline src/compiler/checker.ts:23505]: Same as in the case above, we should also infer into the rest type if possible, for cases like this:

```ts
type SubTup2TrailingVariadic2<T extends unknown[]> = T extends [
    ...(infer C)[],
    ...infer B extends [any, any],
]
    ? [C, ...B]
    : never;

type SubTup2TrailingVariadic2Test = SubTup2TrailingVariadic2<[...a: number[], b: 1, c: 2]>; // Currently [unknown, 1, 2], should be [number, 1, 2].
```

**Review by gabritto — CHANGES_REQUESTED** [review]
Thanks for the PR! I left some comments about missing things, but everything else looks great. If you can add what's missing, then I think we'll be good to merge this. 😊

File: src/compiler/checker.ts (hunk 5 above)
Comment (Andarist) [reply src/compiler/checker.ts:23502]: I've mentioned this [here](https://github.com/microsoft/TypeScript/pull/51157#discussion_r993899659) but perhaps without going much into the relevant details.

Right now... I'm not exactly sure why I had to do it but I had some reason as I've used `sliceTyupleType` in other branches and I've called it out in the comment that I wasn't able to use it here. I can try to refresh my memory on this one later and provide the appropriate details

**Comment by Andarist** [comment]
@gabritto thank you for the additional test cases! I will take a look into supporting them in the coming days.

File: src/compiler/checker.ts (hunk 2 above)
Comment (Andarist) [reply src/compiler/checker.ts]: To give more context behind this - I can't reuse `sliceTupleType` as it creates array types when `index > target.fixedLength`:
https://github.dev/microsoft/TypeScript/blob/acf854b636e0b8e5a12c3f9951d4edfa0fa73bcd/src/compiler/checker.ts#L15758-L15764

So it's not a literal "slice" - it's not just slicing between the `startIndex` and `endIndex` - it also performs a type conversion conditionally. 

If not that condition, I could reuse the `sliceTupleType` here as follows:

```ts
const impliedArity = constraint.target.fixedLength;
const targetEndLength = getEndElementCount(target.target, ElementFlags.Fixed);

inferFromTypes(sliceTupleType(source, sourceArity - targetEndLength - impliedArity, targetEndLength), elementTypes[startLength + 1]);
```

File: src/compiler/checker.ts (hunk 5 above)
Comment (Andarist) [reply src/compiler/checker.ts]: I've added the requested clarification here: https://github.com/microsoft/TypeScript/pull/51157#discussion_r1057206707

**Comment by Andarist** [comment]
@gabritto I pushed out the requested improvements (inferring for the rest elements appearing with the variadic elements with those fixed-size tuple constraints). Could you take another look and re-review it?

**Review by gabritto — APPROVED** [review]
