### PR TITLE
External runner fixes

### LINKED ISSUE #24104: User test baselines need to be capturable independently of platform case
Title. See #24100 for problems the difference causes.

### LINKED ISSUE #24105: User test baselines need to set `typeRoots`
To prevent our `@types` files from affecting their builds (since we're above them in the directory hierarchy), see [this comment](https://github.com/Microsoft/TypeScript/pull/24100#discussion_r188048377).

### PR DESCRIPTION
**Pull request by weswigham**
Follow up to #24100, which I'll now close.

Fixes #24104
Fixes #24105

The tests didn't need `typeRoots`, unfortunately (that only affects implicit inclusion) - they needed all parent `node_modules` fully removed from the tree. (Which then showed how we were failing to include `@types/node` actually in a bunch of projects, which now do.) Also, the diagnostics are now sorted in case-sensitive path order (if they have a path - otherwise they should stay wherever they are - usually at the top), so the baseline file should match between platforms. I hope.

### CODE REVIEW

File: src/harness/externalCompileRunner.ts [hunk 1]
```diff
@@ -27,9 +28,32 @@ abstract class ExternalCompileRunnerBase extends RunnerBase {
         const testList = this.tests && this.tests.length ? this.tests : this.enumerateTestFiles();
 
         describe(`${this.kind()} code samples`, () => {
+            const cwd = path.join(Harness.IO.getWorkspaceRoot(), this.testDir);
+            const placeholderName = ".node_modules";
```
Comment (mhegazy) [inline src/harness/externalCompileRunner.ts]: why not just add a `types: [..]` list?

Comment (weswigham) [reply src/harness/externalCompileRunner.ts]: They have one already. That only says which things get auto-included without even doing an `import`, but the issue here is when i say `const x = require("chalk")` and we walk up the tree and find ours when we can't find it locally. 🌞

File: src/harness/externalCompileRunner.ts [hunk 2]
```diff
@@ -27,9 +28,32 @@ abstract class ExternalCompileRunnerBase extends RunnerBase {
...
         describe(`${this.kind()} code samples`, () => {
+            const cwd = path.join(Harness.IO.getWorkspaceRoot(), this.testDir);
+            const placeholderName = ".node_modules";
+            const moduleDirName = "node_modules";
+            before(() => {
+                ts.forEachAncestorDirectory(cwd, dir => {
+                    try {
+                        fs.renameSync(path.join(dir, moduleDirName), path.join(dir, placeholderName));
+                    }
+                    catch {
```
Comment (sandersn) [inline src/harness/externalCompileRunner.ts]: why catch here, at least with nothing in the body?

File: src/harness/externalCompileRunner.ts [hunk 3]
```diff
@@ -2,6 +2,7 @@
 /// <reference path="runnerbase.ts" />
 const fs = require("fs");
 const path = require("path");
+const del = require("del");
```
Comment (sandersn) [inline src/harness/externalCompileRunner.ts]: why change this?

File: tests/baselines/reference/user/log4js.log [hunk 4]
```diff
@@ -0,0 +1,12 @@
+Exit Code: 1
+Standard output:
+node_modules/log4js/types/log4js.d.ts(4,2): error TS7008: Member 'getLogger' implicitly has an 'any' type.
```
Comment (sandersn) [inline tests/baselines/reference/user/log4js.log]: why did these error before?

File: src/harness/externalCompileRunner.ts [hunk 5]
```diff
@@ -91,7 +119,7 @@ class UserCodeRunner extends ExternalCompileRunnerBase {
         // tslint:disable-next-line:no-null-keyword
         return result.status === 0 && !result.stdout.length && !result.stderr.length ? null : `Exit Code: ${result.status}
 Standard output:
-${stripAbsoluteImportPaths(result.stdout.toString().replace(/\r\n/g, "\n"))}
+${sortErrors(stripAbsoluteImportPaths(result.stdout.toString().replace(/\r\n/g, "\n")))}
```
Comment (sandersn) [inline src/harness/externalCompileRunner.ts]: does this change address the path changes (eg from E:/... to /opt/...)?

File: src/harness/externalCompileRunner.ts (hunk 3 above)
Comment (weswigham) [reply src/harness/externalCompileRunner.ts]: So it's required before I renamed node_modules and make it unreachable.
