### PR TITLE
Fix control flow analysis for --noFallthroughCasesInSwitch

### LINKED ISSUE #34021: Bad interaction between allowUnreachableCode and noFallthroughCasesInSwitch
**TypeScript Version:**  typescript@3.7.0-dev.20191011

**Search Terms:** allowUnreachableCode, noFallthroughCasesInSwitch, unreachable code detected, fallthrough case in switch

**Code**

```json
{
  "compilerOptions": {
    "allowUnreachableCode": false,
    "noFallthroughCasesInSwitch": true,
  }
}
```

```ts
export type Behavior = 'SLIDE' | 'SLIDE_OUT'
export type Direction = 'LEFT' | 'RIGHT' | 'TOP' | 'BOTTOM'

export interface Transition {
  behavior: Behavior
  direction: Direction
}

function foo(transition: Transition): any {
    switch (transition.behavior) {
        case 'SLIDE':
            switch (transition.direction) {
                case 'LEFT':
                    return []
                case 'RIGHT':
                    return []
                case 'TOP':
                    return []
                case 'BOTTOM':
                    return []
            }
            break // <-------------- try commenting this out
        case 'SLIDE_OUT':
            switch (transition.direction) {
                case 'LEFT':
                    return []
                case 'RIGHT':
                    return []
                case 'TOP':
                    return []
                case 'BOTTOM':
                    return []
            }
            break
    }
}
```

**Expected behavior:**

Either
- Compilation succeeds, because this is not a case where "unreachable code detected" is helpful, **OR**
- Compilation succeeds after removing the `break` statement

**Actual behavior:**

Keeping the `break` statement gives `Unreachable code detected` pointing at the `break` statement, and removing it gives `Fallthrough case in switch`. In other words, there's no way to compile this code.

Unreachable code and fallthrough checks should probably be aware of each other. As a side note, I would argue that the unreachable code check is a tad aggressive with default break/return statements -- in production environments, it happens sometimes that type annotations are wrong and it's worth keeping an early return. But I can see how it might be hard to draw the line.

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we use the control flow analyzer to detect fall-through `case` clauses in `switch` statements. Now, a `case` clause isn't considered to fall through if it ends in call to a never-returning function or a nested exhaustive `switch` statement.

```ts
function foo(x: 0 | 1, y: 0 | 1) {
    switch (x) {
        case 0:
            switch (y) {
                case 0: return "00";
                case 1: return "01";
            }
        case 1:
            switch (y) {
                case 0: return "10";
                case 1: return "11";
            }
    }
}
```

Previously the example above would error with `--noFallthoughCasesInSwitch`. With this PR it doesn't.

Fixes #34021.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -31079,6 +31079,9 @@ namespace ts {
                     }
                 }
                 forEach(clause.statements, checkSourceElement);
+                if (compilerOptions.noFallthroughCasesInSwitch && clause.fallthroughFlowNode && isReachableFlowNode(clause.fallthroughFlowNode)) {
+                    grammarErrorOnFirstToken(clause, Diagnostics.Fallthrough_case_in_switch);
```
Comment (sheetalkamat) [inline src/compiler/checker.ts]: Should this be instead errorOnFirstToken or something similar since this is not error found through syntax walk but because of semantic analysis?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, probably.
