### PR TITLE
add fixAwaitInSyncFunction code fix

### LINKED ISSUE #21034: Quick fix at await to make current function async
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
function foo() {
  await/*1*/ bar();
}
```

**Expected behavior:**
At 1, offers a code action that converts the innermost function to async:

```ts
async function foo() {
  await bar();
}
```

**Actual behavior:**
Error at 1 with no quick fix offered

### PR DESCRIPTION
**Pull request by Mosho1**
Fixes #21034

This is pretty straightforward, replacing function expressions/declarations, method declarations and arrow functions with corresponding ones with the async modifier. 

There are 2 issues that I need some help with:

**1.** Replacing the entire node seems to omit the line break at the end of the replaced node. So that this:

```
class Foo {
    bar() {
        await Promise.resolve();
    }
}
```
Becomes:
```
class Foo {
    async bar() {
        await Promise.resolve();
    }}
```

This happens both in the unit tests, and in manual e2e testing with vscode.

**2.** `codeFixAwaitInSyncFunction7`, the test case of an `for-await-of` loop, fails - 

```
  tests/cases/fourslash/codeFixAwaitInSyncFunction7.ts
         fourslash test codeFixAwaitInSyncFunction7.ts runs correctly:
     Error: Debug Failure. False expression: Token end is child end
      at processChildNode (src\services\formatting\formatting.ts:704:27)
      at src\services\formatting\formatting.ts:629:21
      at visitNode (src\compiler\parser.ts:38:24)
      at Object.forEachChild (src\compiler\parser.ts:285:24)
      at processNode (src\services\formatting\formatting.ts:626:13)
      at processChildNode (src\services\formatting\formatting.ts:712:17)
      at processChildNodes (src\services\formatting\formatting.ts:767:44)
      at src\services\formatting\formatting.ts:632:21
      at visitNodes (src\compiler\parser.ts:44:24)
      at Object.forEachChild (src\compiler\parser.ts:253:24)
      at processNode (src\services\formatting\formatting.ts:626:13)
      at processChildNode (src\services\formatting\formatting.ts:712:17)
      at src\services\formatting\formatting.ts:629:21
      at visitNode (src\compiler\parser.ts:38:24)
      at Object.forEachChild (src\compiler\parser.ts:160:21)
      at processNode (src\services\formatting\formatting.ts:626:13)
      at formatSpanWorker (src\services\formatting\formatting.ts:416:13)
      at src\services\formatting\formatting.ts:346:108
      at Object.getFormattingScanner (src\services\formatting\formattingScanner.ts:41:21)
```

I tried to debug this for a while, but nothing conclusive. This does not happen when I use the compiled tsserver.js in vscode to test the code fix.

### CODE REVIEW

**Comment by andy-ms** [comment]
Hi @Mosho1, I've created a branch at https://github.com/Microsoft/TypeScript/commit/13195190fc53abed9b17e006cd5e5e39aeeac671 that would just add the keyword to the front of the function instead of replacing the node. That seems to fix the formatting problems since we're only inserting text now.

**Comment by Mosho1** [comment]
@andy-ms thanks, that is a lot better. I picked only the commit with the change, let me know if I should do it differently.

File: src/services/codefixes/fixAwaitInSyncFunction.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ namespace ts.codefix {
             doChange(changes, context.sourceFile, getNodeToInsertBefore(diag.file, diag.start!))),
     });
 
-    function getNodeToInsertBefore(sourceFile: SourceFile, pos: number): Node | undefined {//name
+    function getNodeToInsertBefore(sourceFile: SourceFile, pos: number): Node | undefined {// name
```
Comment (andy-ms) [inline src/services/codefixes/fixAwaitInSyncFunction.ts]: Whoops, I should have removed the comment before pushing.

**Comment by andy-ms** [comment]
We could also consider changing an explicit return type `T` to `Promise<T>` (if it's not already that way).

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -3843,6 +3843,10 @@
         "category": "Message",
         "code": 90028
     },
+    "Convert to async": {
```
Comment (mhegazy) [inline src/compiler/diagnosticMessages.json]: nit. `Add async modifier to containing function`

Comment (mhegazy) [reply src/compiler/diagnosticMessages.json]: @DanielRosenwasser any better suggestions for the message?

File: src/services/codefixes/fixAwaitInSyncFunction.ts [hunk 3]
```diff
@@ -9,19 +9,42 @@ namespace ts.codefix {
...
+        switch (containingFunction.kind) {
+            case SyntaxKind.MethodDeclaration:
+            case SyntaxKind.FunctionDeclaration:
+                return containingFunction.type;
+            case SyntaxKind.FunctionExpression:
+            case SyntaxKind.ArrowFunction:
+                if (isVariableDeclaration(containingFunction.parent) &&
+                    containingFunction.parent.type &&
+                    isFunctionTypeNode(containingFunction.parent.type)) {
+                    return containingFunction.parent.type.type;
```
Comment (andy-ms) [inline src/services/codefixes/fixAwaitInSyncFunction.ts]: Also check for a `.type` immediately on either of these, i.e. `function(): number { ... }` or `(): number => { ... }`.

File: src/services/codefixes/fixAwaitInSyncFunction.ts [hunk 4]
```diff
@@ -35,7 +58,13 @@ namespace ts.codefix {
         }
     }
 
-    function doChange(changes: textChanges.ChangeTracker, sourceFile: SourceFile, insertBefore: Node): void {
+    function doChange(changes: textChanges.ChangeTracker, sourceFile: SourceFile, insertBefore: Node, returnType: TypeNode | undefined): void {
+        if (returnType) {
+            const entityName = getEntityNameFromTypeNode(returnType);
+            if (!entityName || entityName.getText() !== "Promise") {
```
Comment (andy-ms) [inline src/services/codefixes/fixAwaitInSyncFunction.ts]: `if (!entityName || entityName.kind !== SyntaxKind.Identifier || entityName.text !== "Promise")`

File: src/services/codefixes/fixAwaitInSyncFunction.ts [hunk 5]
```diff
@@ -9,19 +9,42 @@ namespace ts.codefix {
...
+            const returnType = getReturnTypeNode(containingFunction);
+            if (!insertBefore) return undefined;
+            const changes = textChanges.ChangeTracker.with(context, t => doChange(t, sourceFile, insertBefore, returnType));
             return [{ description: getLocaleSpecificMessage(Diagnostics.Convert_to_async), changes, fixId }];
         },
         fixIds: [fixId],
-        getAllCodeActions: context => codeFixAll(context, errorCodes, (changes, diag) =>
-            doChange(changes, context.sourceFile, getNodeToInsertBefore(diag.file, diag.start!))),
+        getAllCodeActions: context => codeFixAll(context, errorCodes, (changes, diag) => {
+            const token = getTokenAtPosition(diag.file, diag.start!, /*includeJsDocComment*/ false);
```
Comment (andy-ms) [inline src/services/codefixes/fixAwaitInSyncFunction.ts]: Use a function `getNodes(...): { insertBefore: Node, returnType: Type | undefined } | undefined` to avoid repeating this. That would also let you combine the two switch statements from `getNodeToInsertBefore` and `getReturnTypeNode`.

File: src/services/codefixes/fixAwaitInSyncFunction.ts (hunk 3 above)
Comment (Mosho1) [reply src/services/codefixes/fixAwaitInSyncFunction.ts]: After adding this change I refactored `getReturnType` to not use a switch statement at all since with the added condition the two if statements handle all cases.
