### PR TITLE
Fix inference to indexed access type containing substitution type

### LINKED ISSUE #31086: Regression in 3.4: Type inference with generic type guard breaks
**TypeScript Version:**  3.5.0-dev.20190424

**Search Terms:**
generic type parameters broken, regression 3.4, type inference for mapped conditional types broken

**Code**

```ts
type UserArgs = {
  select?: boolean
}

type Subset<T, U> = { [key in keyof T]: key extends keyof U ? T[key] : never }

function withBoundary<T extends UserArgs>(args?: Subset<T, UserArgs>): T {
  return null as any
}

const boundaryResult = withBoundary({
  select: true,
})

// In TypeScript@3.3:
/**
 * typeof boundaryResult === {
 *   select: true
 * }
 */

// In TypeScript@3.4 @ TypeScript@next:
/**
 * typeof boundaryResult === UserArgs
 */

function withoutBoundary<T extends UserArgs>(args?: T): T {
  return null as any
}

const withoutBoundaryResult = withoutBoundary({
  select: true,
})

// In TypeScript@3.3:
/**
 * typeof withoutBoundaryResult === {
 *   select: true
 * }
 */

// In TypeScript@3.4 & TypeScript@next:
/**
 * typeof withoutBoundaryResult === {
 *   select: true
 * }
 */
```

**Expected behavior:**
I expect the return type of the `withBoundary` function to actually include the fine-grain information of which concrete boolean value is provided for the `select` property. It should have type `{select: true}`.

**Actual behavior:**
Instead, it's typecasted to `UserArgs`.

We need this behavior to work because we want to make sure that users of our library only pass in a "subset" and not a superset of the `UserArgs` type into the `withBoundary` function. As `T extends UserArgs` is not sufficient to narrow that down, we use `(args?: Subset<T, UserArgs>)`. This worked in 3.3 and is now broken in 3.4.

[**Playground Link**](https://www.typescriptlang.org/play/#src=type%20UserArgs%20%3D%20%7B%0D%0A%20%20select%3F%3A%20boolean%0D%0A%7D%0D%0A%0D%0Atype%20Subset%3CT%2C%20U%3E%20%3D%20%7B%20%5Bkey%20in%20keyof%20T%5D%3A%20key%20extends%20keyof%20U%20%3F%20T%5Bkey%5D%20%3A%20never%20%7D%0D%0A%0D%0Afunction%20withBoundary%3CT%20extends%20UserArgs%3E(args%3F%3A%20Subset%3CT%2C%20UserArgs%3E)%3A%20T%20%7B%0D%0A%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20boundaryResult%20%3D%20withBoundary(%7B%0D%0A%20%20select%3A%20true%2C%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20In%20TypeScript%403.3%3A%0D%0A%2F**%0D%0A%20*%20typeof%20boundaryResult%20%3D%3D%3D%20%7B%0D%0A%20*%20%20%20select%3A%20true%0D%0A%20*%20%7D%0D%0A%20*%2F%0D%0A%0D%0A%2F%2F%20In%20TypeScript%403.4%20%40%20TypeScript%40next%3A%0D%0A%2F**%0D%0A%20*%20typeof%20boundaryResult%20%3D%3D%3D%20UserArgs%0D%0A%20*%2F%0D%0A%0D%0Afunction%20withoutBoundary%3CT%20extends%20UserArgs%3E(args%3F%3A%20T)%3A%20T%20%7B%0D%0A%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20withoutBoundaryResult%20%3D%20withoutBoundary(%7B%0D%0A%20%20select%3A%20true%2C%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20In%20TypeScript%403.3%3A%0D%0A%2F**%0D%0A%20*%20typeof%20withoutBoundaryResult%20%3D%3D%3D%20%7B%0D%0A%20*%20%20%20select%3A%20true%0D%0A%20*%20%7D%0D%0A%20*%2F%0D%0A%0D%0A%2F%2F%20In%20TypeScript%403.4%20%26%20TypeScript%40next%3A%0D%0A%2F**%0D%0A%20*%20typeof%20withoutBoundaryResult%20%3D%3D%3D%20%7B%0D%0A%20*%20%20%20select%3A%20true%0D%0A%20*%20%7D%0D%0A%20*%2F%0D%0A) 

**Related Issues:** 
- https://github.com/Microsoft/TypeScript/issues/4742
- https://github.com/Microsoft/TypeScript/issues/30152
- https://github.com/Microsoft/TypeScript/issues/30708
- https://github.com/Microsoft/TypeScript/issues/30694

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #31086.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14860,6 +14860,14 @@ namespace ts {
                         target = removeTypesFromUnionOrIntersection(<UnionOrIntersectionType>target, matchingTypes);
                     }
                 }
+                else if (target.flags & TypeFlags.Substitution) {
+                    target = (target as SubstitutionType).typeVariable;
+                }
+                else if (target.flags & TypeFlags.IndexedAccess && (
+                    (<IndexedAccessType>target).objectType.flags & TypeFlags.Substitution ||
+                    (<IndexedAccessType>target).indexType.flags & TypeFlags.Substitution)) {
+                    target = getIndexedAccessType(getActualTypeVariable((<IndexedAccessType>target).objectType), getActualTypeVariable((<IndexedAccessType>target).indexType));
```
Comment (weswigham) [inline src/compiler/checker.ts]: What about a `Substitute<T[Substitute<K>]>`? Substitutes can in theory nest arbitrarily, provided they keep instantiating to type variables.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I've moved the logic to `getActualTypeVariable` and made it recurse appropriately.

**Comment by timsuchanek** [comment]
Just tried it out - I can confirm that it's now working 🎉 
Thanks for fixing this so quick!
