### PR TITLE
Ignore @private/@protected on constructor functions

### LINKED ISSUE #35766: @private on constructor function in a block causes crash
Crashes when inside a block, but not at toplevel.

```js
{
    /** @private */
    function C() {
        this.x = 1
    }
    new C()
}
```

Introduced in the recent PR that supports `@private` in jsdoc.
Behaviour is incorrect at top-level too; `@private` on a constructor function doesn't make sense, but the compiler gives an error on `new C()` saying that it can only be constructed inside the class itself. But there is nowhere else to construct the class?

### PR DESCRIPTION
**Pull request by sandersn**
This was incorrect in the best of circumstances and caused a crash when the parent of the function had no symbol, because the accessibility check assumed it was operating on a constructor and that the parent was always the containing class.

Fixes #35766

### CODE REVIEW

**Comment by sandersn** [comment]
This showed up in lodash because lodash uses `@private` to mean "do not export this", and therefore sticks it on almost everything in some files.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -24865,8 +24865,8 @@ namespace ts {
             const declaration = signature.declaration;
             const modifiers = getSelectedModifierFlags(declaration, ModifierFlags.NonPublicAccessibilityModifier);
 
-            // Public constructor is accessible.
-            if (!modifiers) {
+            // (1) Public constructors and (2) constructor functions are always accessible.
+            if (!modifiers || isFunctionLikeDeclaration(declaration)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: oops, isFunctionLikeDeclaration includes constructors. I think I'll flip the check and exclude SyntaxKind.Constructor explicitly.
