### PR TITLE
Fix name generation scoping

### LINKED ISSUE #57897: A shadowed variable is generated in a an async function with a default parameter declared as a static property of a class when targeting ES5.
### 🔎 Search Terms

"shadowed", "shadowed variable", "generator"

### 🕗 Version & Regression Information

- This changed in commit or PR #56296

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=1&ts=5.4.3#code/MYGwhgzhAEAa0G8BQ1oAcCuAjEBLY0EALmEftGNALwUQCeAdgQBQQD2AtgKYBqYATgC5oWNmxBcwDatCL8MXAJTUAfIhSpo-LkQz9pYAO5hcROADoszRQG4NAXzsbMOcsVLksMyIxbKqasiaWjp60gBEAOIA8tEAIuF2qI5I9khIACZcoAJc0DlQ6PxswFyFQYQkZARcAB6mzMBsWcIMGBxYXPyKrVwAbl12aUiw5mDWGuZEABZcDI1sDOwS5iBsAOaKk8CkwNPM1qrqwU1L4lzmXcX8zOEAQgCCCbYaqGjFpVCX9UTMAIwvZIvIA

### 💻 Code

```ts
class X {
  public static a = async (someVar: boolean = true) => {
    return await X.b();
  };

  public static b = async () => {
    return "GOOD";
  };
}

declare class process {
  static exit(code: number): never;
}

X.a()
  .then(console.log)
  .catch(() => {
    console.error("BAD");
    process.exit(1);
  });
```

### 🙁 Actual behavior

Between TS v5.4.2 and TS v5.3.3, the generated code from the above code sample changes to shadow the `_a` variable in the outer closure. See diff below:

```diff
var X = /** @class */ (function () {
    function X() {
    }
    var _a;
    _a = X;
-    X.a = function (someVar) {
-        if (someVar === void 0) { someVar = true; }
-        return __awaiter(_a, void 0, void 0, function () {
-            return __generator(_a, function (_b) {
-                switch (_b.label) {
+    X.a = function () {
+        var args_1 = [];
+        for (var _i = 0; _i < arguments.length; _i++) {
+            args_1[_i] = arguments[_i];
+        }
+        return __awaiter(_a, __spreadArray([], args_1, true), void 0, function (someVar) {
+            if (someVar === void 0) { someVar = true; }
+            return __generator(_a, function (_a) {
+                switch (_a.label) {
                     case 0: return [4 /*yield*/, _a.b()];
-                    case 1: return [2 /*return*/, _b.sent()];
+                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    X.b = function () { return __awaiter(_a, void 0, void 0, function () {
        return __generator(_a, function (_b) {
            return [2 /*return*/, "GOOD"];
        });
    }); };
    return X;
}());
X.a()
    .then(console.log)
    .catch(function () {
    console.error("BAD");
    process.exit(1);
});

```

Note that helpers have been omitted from this code sample.

Notice that in the context of the function, the class/function `X` is assigned to a variable `_a` in the "ambient" context of the class. In TS v5.3.3, the async state machine's state variable is declared as `_b`, but in TS v.5.4.2 is appears as if the context is lost when the state machine is generated, so the state is declared as `_a`, shadowing the earlier-declared `_a`.

### 🙂 Expected behavior

Expected that the async state machine's state variable does not shadow another variable.

### Additional information about the issue

_No response_

This issue was found by @ipip2005.

### PR DESCRIPTION
**Pull request by rbuckton**
There are a number of small oddities in the emitter regarding name generation for temp variables and private names. Despite using `reservedNames`/`reservedPrivateNames` to reserve names permanently within a scope, we weren't checking all reservations in the respective stacks. We also weren't consistent about name generation in a few places, so I've combined the private and temp variable name scopes so that we enter and exit both consistently.

I also removed a place where we exited and then reentered a private name generation scope when visiting a computed property name since both temp variables and private names should be generated immediately as we enter a declaration, not on-demand as we descend into and out of computed property names.

Fixes #57897

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -5372,7 +5349,30 @@ export function createPrinter(printerOptions: PrinterOptions = {}, handlers: Pri
...
+            stack = reservedNamesStack;
+        }
+
+        if (set?.has(name)) {
+            return true;
+        }
+        for (let i = stack.length - 1; i >= 0; i--) {
+            if (set === stack[i]) {
+                continue;
+            }
```
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts:5369]: This is partially off-topic, but is there any reason the current scope can't be stored separate of the stack itself? Or if it is possible, when is it the case that the current is not the same as the last in the stack?

Comment (rbuckton) [reply src/compiler/emitter.ts:5369]: The current scope is stored separate from the stack. The way push/pop works is that we don't reset the current scope until we actually record something so that we defer the cost of reassignment until the moment we actually need to record a name. This check here is an example of that. If the set for the current scope is also in the stack, then we can skip it as nothing else was actually recorded in that scope.

Comment (rbuckton) [reply src/compiler/emitter.ts:5369]: In other words, the algorithm favors code that requires no generated names so that we can avoid paying the cost for more recent `--target`s.

**Review by andrewbranch — APPROVED** [review]

**Comment by PhoebeSzmucer** [comment]
@rbuckton @andrewbranch this seems to be a regression in 5.4.x, and I've unfortunately hit this after upgrading a large codebase to 5.4.x. Is there any chance we can backport this fix, so that I don't have to revert the upgrade? I see the fix is on 5.5.x but that's not released yet.

**Comment by jakebailey** [comment]
TS 5.5 is coming out this week, so I wouldn't think we'd be patching 5.4 anymore.

**Comment by PhoebeSzmucer** [comment]
We have 5.5+ million lines of typescript code so it will probably take us a couple of weeks to get to 5.5 - if there is any chance this can be backported it would be a huge help.

No worries if not though!
