### PR TITLE
Unions and intersections of readonly properties are now also readonly

### LINKED ISSUE #9108: readonly modifier is ignored in unions
```typescript 
interface X {
    readonly value: 'x';
}
interface Y {
    value: 'y';
}
type Z = X | Y;
var z: Z = <Z>{ value: 'y' };
z.value = 'x'; // expected an error saying that value: 'x' is readonly and cannot be set, actual OK
```

UPDATE:

even this example doesn't work (with both possible options being `readonly`)

```typescript 
interface X {
    readonly value: 'x';
}
interface Y {
    readonly value: 'y';
}
type Z = X | Y;
var z: Z = <Z>{ value: 'y' };
z.value = 'x'; // expected an error saying that value: 'x' is readonly and cannot be set, actual OK
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #9108 

@ahejlsberg can you take a look to confirm that this is how readonly should work with unions and intersections of properties?

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11975,6 +11975,10 @@ namespace ts {
             // Variables declared with 'const'
             // Get accessors without matching set accessors
             // Enum members
+            // Unions and intersections of the above
+            if (symbol.flags & SymbolFlags.SyntheticProperty) {
+                return forEach(symbol.declarations, decl => isReadonlySymbol(getSymbolOfNode(decl)));
+            }
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This could probably be more efficient. When a symbol has multiple declarations (such as an overloaded method) we'll end up doing the same check multiple times even though the outcome is always false. Ideally we'd have a `SymbolFlags.Readonly` that we compute in the same way as `SymbolFlags.Optional`, but we're out of flag bits. Perhaps it would be better to compute the readonly state in `createUnionOrIntersectionProperty` (but calling `isReadonlySymbol` for each underlying symbol) and then record the result in an `isReadonly` property on the symbol itself.

Comment (sandersn) [inline src/compiler/checker.ts]: That sounds like a good idea. Done.

**Comment by aleksey-bykov** [comment]
> but we're out of flag bits

sounds like the saddest news ever, why wouldn't add an extra field with a whole bunch of fresh bits?
```
...
flags: number;
more_flags: number;
...
```

**Comment by sandersn** [comment]
@ahejlsberg can you take a look at the updated code?

**Comment by mhegazy** [comment]
👍
