### PR TITLE
Fix auto import completion inserting wrong module specifier

### LINKED ISSUE #41010: TypeScript suggests only first (default) import
**TypeScript Version:**  4.1.0 (current master)

**Search Terms:** auto completion, alias, export

**Code**

```ts
// a.d.ts
declare namespace foo { class Bar {} }
declare module 'path1' {
  import Bar = foo.Bar;
  export default Bar;
}
declare module 'path2longer' {
  import Bar = foo.Bar;
  export {Bar};
}
// b.ts

Ba|; // < auto complete here
```

**Expected behavior:**

TypeScript presents two import auto completions, one that chooses to import from 'path1', the other chooses 'path2longer'. I can select the second one and end up importing from 'path2longer'.

**Actual behavior:**

TypeScript does present two import auto completions, but both end up importing 'path1'.

I've debugged this a bit, TS produces the correct completions, and also displays one as "export default Bar" and the other as "export Bar", with correct `source` fields. However TypeScript displays the same module URI (path1) for both, and when creating the code fix actions, it sorts possible modules without taking the option the user chose into account. This means both import completions have the same code fix, they import the shorter path.

Given the import is different (different path, different import style), I think TypeScript should follow the user's selection here.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #41010

If the `source` of a completion item is a bare specifier (which I believe can only arise from ambient modules), there’s really no reason to consider other module specifiers. When `source` is a path to a module, we look at symlinks, `paths`, reëxports, etc. to find the best module specifier for that symbol. None of that is relevant for ambient modules, so we should just use exactly what the completion entry showed.

### CODE REVIEW

File: tests/cases/fourslash/completionsImport_ambient.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+////   export {Bar};
+//// }
+////
+
+// @Filename: b.ts
+//// Ba/**/
+
+verify.applyCodeActionFromCompletion("", {
+  name: "Bar",
+  source: "path2longer",
```
Comment (sandersn) [inline tests/cases/fourslash/completionsImport_ambient.ts:22]: I thought the desired behaviour in the bug was to provide both path1 and path2longer. Does that test show this?

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -228,6 +230,27 @@ namespace ts.codefix {
...
     }
 
+    function getSymbolExportInfoForSymbol(symbol: Symbol, moduleSymbol: Symbol, importingFile: SourceFile, program: Program, host: LanguageServiceHost): SymbolExportInfo {
+        const compilerOptions = program.getCompilerOptions();
+        const mainProgramInfo = getInfoWithChecker(program.getTypeChecker());
+        if (mainProgramInfo) {
+            return mainProgramInfo;
+        }
+        const autoImportProvider = host.getPackageJsonAutoImportProvider?.()?.getTypeChecker();
+        return Debug.checkDefined(autoImportProvider && getInfoWithChecker(autoImportProvider), `Could not find symbol in specified module for code actions`);
```
Comment (sandersn) [inline src/services/codefixes/importFixes.ts:240]: so this asserts if the host can't produce an auto import provider can't be produced or a type checker?

**Review by sandersn — CHANGES_REQUESTED** [review]
Couple of questions, mainly about providing 1 vs many results.

File: tests/cases/fourslash/completionsImport_ambient.ts (hunk 1 above)
Comment (andrewbranch) [reply tests/cases/fourslash/completionsImport_ambient.ts:22]: Both options were provided, it's just that both of them resulted in the same code action, despite presenting differently. This test shows that the one that resolved to the wrong code action now resolves to the right code action, but doesn’t actually demonstrate that both completions are offered—I’ll add that so it’s more clear.

File: src/services/codefixes/importFixes.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:240]: Not exactly; it asserts that the exported symbol was in fact found to be exported by its module symbol, according to either the main program checker or the AutoImportProvider checker. This is basically redoing work during the completions _details_ request that was done during the previous completions _list_ request, so it should always be found, but of course there’s no guarantee of that in the types, hence the assertion. (It’s also the sort of assumption that could plausibly be violated by a bizarre sequence of edits triggering some race condition, or just wrong code, so we do see assertions like this come up in telemetry every once in a while.)

**Review by sandersn — APPROVED** [review]
