### PR TITLE
Fix bug: ClassDeclaration not guaranteed to be first declaration of a class

### LINKED ISSUE #22479: Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isClassLike'. in 'Object.cast' during 'getCodeFixes'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.2
**VSCode Version** 1.20.1
**command requested**: getCodeFixes
**hitting sessions**: 162
**proportion of all sessions**: 0.007555617741709809
**stack**
```
Error: Debug Failure. Invalid cast. The supplied value did not pass the test 'isClassLike'.
    at Object.cast (tsserver.js:2443:15)
    at getClassAndMakeStatic (tsserver.js:77502:43)
    at getInfo (tsserver.js:77473:38)
    at Object.getCodeActions (tsserver.js:77431:28)
    at unknown (tsserver.js:77219:33)
    at Object.forEach (tsserver.js:1431:30)
    at Object.getFixes (tsserver.js:77218:16)
    at unknown (tsserver.js:83366:35)
    at Object.flatMap (tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (tsserver.js:83364:23)
    at IOSession.Session.getCodeFixes (tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89292:61)
    at unknown (tsserver.js:90553:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90544:28)
    at IOSession.Session.executeCommand (tsserver.js:90553:33)
    at IOSession.Session.onMessage (tsserver.js:90573:35)
    at Interface.<anonymous> (tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #22479

### CODE REVIEW

File: tests/cases/fourslash/codeFixAddMissingMember_classIsNotFirstDeclaration.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/// <reference path='fourslash.ts' />
+
+////interface C {}
+////class C {
+////}
+////new C().x = 0;
+
+verify.codeFix({
+    description: "Declare property 'foo'",
```
Comment (sheetalkamat) [inline tests/cases/fourslash/codeFixAddMissingMember_classIsNotFirstDeclaration.ts]: shouldnt this be "x" instead of "foo"

File: src/services/codefixes/fixAddMissingMember.ts [hunk 2]
```diff
@@ -89,9 +89,8 @@ namespace ts.codefix {
             if (!(symbol && leftExpressionType.flags & TypeFlags.Object && symbol.flags & SymbolFlags.Class)) {
                 return undefined;
             }
-            const classDeclaration = cast(first(symbol.declarations), isClassLike);
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: should we check that we found a class?

Comment (andy-ms) [reply src/services/codefixes/fixAddMissingMember.ts]: I think it should be guaranteed to exist if the symbol has `SymbolFlags.Class`.
