### PR TITLE
  Do not write files directly from builder when noEmitOnError is true 

### LINKED ISSUE #34823: --noEmitOnError doesn't work with --watch when including files outside of project
**TypeScript Version:**  3.6.4

**Search Terms:** noEmitOnError watch

**Code**

I have prepared a small repo that helps demonstrate the issue: https://github.com/rhyek/test-no-emit-on-error

Install the dependencies and run `npm run dev` which in essence does `tsc --noEmitOnError --watch`. The source code has a syntax error and therefore the build will fail.

**Expected behavior:**
Since there are errors in the build and I'm including the `noEmitOnError` cli option, no output should occur.

**Actual behavior:**
Output occurs. Without the `watch` option no output occurs, which is the correct behavior.

If I remove the `include` option in the `tsconfig.json`, or just remove the `../../shared` item, everything works as it should.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #34823

### CODE REVIEW

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -987,6 +987,8 @@ namespace ts {
         function emit(targetSourceFile?: SourceFile, writeFile?: WriteFileCallback, cancellationToken?: CancellationToken, emitOnlyDtsFiles?: boolean, customTransformers?: CustomTransformers): EmitResult {
             if (kind === BuilderProgramKind.EmitAndSemanticDiagnosticsBuilderProgram) {
                 assertSourceFileOkWithoutNextAffectedCall(state, targetSourceFile);
+                const result = handleNoEmitOptions(builderProgram, targetSourceFile, cancellationToken);
```
Comment (sheetalkamat) [inline src/compiler/builder.ts]: This is where we handle the noEmit options before writing the files.
