### PR TITLE
Cache accessibe symbol chains and serialized type parameter name generation

### LINKED ISSUE #42937: Extra long code compilation whitch finished with "memory leak" report after ~20min
This issue started here: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/569

## Current behavior

Make file: `Api.ts`

```typescript
/* eslint-disable */
/* tslint:disable */
import { HttpClient } from "./http-client";

export class Api<SecurityDataType = unknown> {
  constructor(private http: HttpClient<SecurityDataType>) {}

    abc1 = () => this.http.request();
    abc2 = () => this.http.request();
    abc3 = () => this.http.request();
}
```

and `http-client.ts`

```typescript
/* eslint-disable */
/* tslint:disable */

/** Overrided Promise type. Needs for additional typings of `.catch` callback */
type TPromise<ResolveType, RejectType = any> = Omit<Promise<ResolveType>, "then" | "catch"> & {
  then<TResult1 = ResolveType, TResult2 = never>(
    onfulfilled?: ((value: ResolveType) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: RejectType) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): TPromise<TResult1 | TResult2, RejectType>;
  catch<TResult = never>(
    onrejected?: ((reason: RejectType) => TResult | PromiseLike<TResult>) | undefined | null,
  ): TPromise<ResolveType | TResult, RejectType>;
};

export interface HttpResponse<D extends unknown, E extends unknown = unknown> extends Response {
  data: D;
  error: E;
}

export class HttpClient<SecurityDataType = unknown> {
  public request = <T = any, E = any>(): TPromise<HttpResponse<T, E>> => {
    return '' as any;
  };
}
```

try to compile, you will see that "Issues checking in progress..." process take extra long time ~15 sec.
I dont know why, but if you Copy-Paste `http-client.ts` to `Api.ts` directly this check take <1 sec.

This files make this lib https://github.com/acacode/swagger-typescript-api with ~1000 `this.http.request`, and each `this.http.request()` took ~7 sec of checking. When I do this in `intel i7` CPU, **after ~30 min of compiling I got error about `memory leak`.**

**Video:** https://user-images.githubusercontent.com/3511307/108701953-4a842480-7511-11eb-9924-7f3c0c60acd0.mp4

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.1.0
 - **typescript**: 3.9.9
 - **eslint**: 6.8.0
 - **webpack**: 4.46.0
 - **os**: Linux mint 18.3 KDE

**Tested on latest typescript 4.2.2** - same result.

Same with `tsc --watch --noEmit`.

**Video**: https://user-images.githubusercontent.com/3511307/108986783-2eac8a00-769b-11eb-9f9e-27f914830c8d.mp4

### PR DESCRIPTION
**Pull request by weswigham**
Which can improve declaration emit performance significantly in some edge cases. Together, these caches bring the example in the linked issue down from 20s to 5.5s on my machine, which is a pretty marked improvement.

Fixes #42937

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5823,8 +5833,11 @@ namespace ts {
                     if (text !== rawtext) {
                         result = factory.createIdentifier(text, result.typeArguments);
                     }
-                    (context.typeParameterNames || (context.typeParameterNames = new Map())).set(getTypeId(type), result);
-                    (context.typeParameterNamesByText || (context.typeParameterNamesByText = new Set())).add(result.escapedText as string);
+                    // avoiding iterations of the above loop turns out to be worth it when `i` starts to get large, so we cache the max
+                    // `i` we've used thus far, to save work later
+                    (context.typeParameterNamesByTextNextNameCount ||= new Map()).set(rawtext, i);
```
Comment (weswigham) [inline src/compiler/checker.ts:5838]: This is the "cache serialized type parameter name generation" part - this additional tiny bit of caching brought the runtime of the example down from 7s to 5.5s on my machine.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3995,13 +3995,23 @@ namespace ts {
             if (!(symbol && !isPropertyOrMethodDeclarationSymbol(symbol))) {
                 return undefined;
             }
+            const links = getSymbolLinks(symbol);
+            const cache = (links.accessibleChainCache ||= new Map());
+            // Go from enclosingDeclaration to the first scope we check, so the cache is keyed off the scope and thus shared more
+            const firstRelevantLocation = forEachSymbolTableInScope(enclosingDeclaration, (_, __, node) => node);
+            const key = `${useOnlyExternalAliasing ? 0 : 1}|${firstRelevantLocation && getNodeId(firstRelevantLocation)}|${meaning}`;
+            if (cache.has(key)) {
+                return cache.get(key);
```
Comment (weswigham) [inline src/compiler/checker.ts:4004]: This cache could probably be better - intelligently sharing results for commonish-`meaning`s and having a hierarchical cache both sound nice in theory, but are a pain to implement performantly (the last time I tried I ruined perf in the general case). This relatively simple cache was sufficient to bring the example runtime down from 20s to 7s on my machine, though is likely to only really effect really degenerate cases, like the one in the linked issue.

File: src/harness/compilerImpl.ts [hunk 3]
```diff
@@ -254,7 +254,11 @@ namespace compiler {
         if (compilerOptions.skipDefaultLibCheck === undefined) compilerOptions.skipDefaultLibCheck = true;
         if (compilerOptions.noErrorTruncation === undefined) compilerOptions.noErrorTruncation = true;
 
-        const preProgram = ts.length(rootFiles) < 100 ? ts.createProgram(rootFiles || [], { ...compilerOptions, configFile: compilerOptions.configFile, traceResolution: false }, host) : undefined;
+        // pre-emit/post-emit error comparison requires declaration emit twice, which can be slow. If it's unlikely to flag any error consistency issues
+        // and if the test is running `skipLibCheck` - an indicator that we want the tets to run quickly - skip the before/after error comparison, too
+        const skipErrorComparison = ts.length(rootFiles) >= 100 || (!!compilerOptions.skipLibCheck && !!compilerOptions.declaration);
```
Comment (weswigham) [inline src/harness/compilerImpl.ts:259]: Declaration emit for this test still takes 5s on my machine. `getPreEmitDiagnostics` invokes declaration emit to get declaration emit errors (for historical reasons they've been considered "preEmit" errors), meaning declaration emit had to run _twice_, so 10s.  Single-threaded, this was fine, but in high resource contention scenarios (ie, `runtests-parallel`) this was long enough to stretch to 40s and timeout. So I added an opt-out case to the preEmit/preEmit-after-emit error consistency check to keep this test runtime low (so it could pass without a timeout when running in parallel, and probably on CI).

File: tests/cases/compiler/declarationEmitPrivatePromiseLikeInterface.ts [hunk 4]
```diff
@@ -0,0 +1,34 @@
+// @declaration: true
+// @skipLibCheck: true
+// @noTypesAndSymbols: true
```
Comment (weswigham) [inline tests/cases/compiler/declarationEmitPrivatePromiseLikeInterface.ts:3]: And I've skipped the type/symbol baselines for this test, since they double again the test runtime (and also thus cause a timeout) by _essentially_ invoking the same logic as declaration emit for no real additional gain (compared to the declaration emit we're already running).

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot perf test this ? I'm not sure this'll affect anything - I don't know if any of our perf tests do declaration emit.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -3935,12 +3935,12 @@ namespace ts {
             return typeCopy;
         }
 
-        function forEachSymbolTableInScope<T>(enclosingDeclaration: Node | undefined, callback: (symbolTable: SymbolTable) => T): T {
+        function forEachSymbolTableInScope<T>(enclosingDeclaration: Node | undefined, callback: (symbolTable: SymbolTable, ignoreQualification?: boolean, scopeNode?: Node) => T): T {
```
Comment (sheetalkamat) [inline src/compiler/checker.ts:3938]: I dont see anywhere we are passing `ignoreQualification` true or false ? 
Also can we make these parameter nonOptional but type | undefined instead to ensure every call back considers what needs to be passed?

Comment (weswigham) [reply src/compiler/checker.ts:3938]: Inside _this_ function, it's not; however the function we often pass as a callback uses it as a second parameter (and it's optional there) for its' _other_ callsites, so this optional parameter is here so the callback parameter is compatible with both that usage and the node-finding usage.

**Comment by weswigham** [comment]
-3-5% check time in `material-ui`? Nice. I'm wondering what actually invoked symbol visibility logic without declaration emit, but am pleasantly surprised by the improvement.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -5823,8 +5833,11 @@ namespace ts {
                     if (text !== rawtext) {
                         result = factory.createIdentifier(text, result.typeArguments);
                     }
-                    (context.typeParameterNames || (context.typeParameterNames = new Map())).set(getTypeId(type), result);
-                    (context.typeParameterNamesByText || (context.typeParameterNamesByText = new Set())).add(result.escapedText as string);
+                    // avoiding iterations of the above loop turns out to be worth it when `i` starts to get large, so we cache the max
+                    // `i` we've used thus far, to save work later
+                    (context.typeParameterNamesByTextNextNameCount ||= new Map()).set(rawtext, i);
+                    (context.typeParameterNames ||= new Map()).set(getTypeId(type), result);
+                    (context.typeParameterNamesByText ||= new Set()).add(result.escapedText as string);
```
Comment (dmichon-msft) [inline src/compiler/checker.ts:5840]:
```suggestion
                    (context.typeParameterNamesByText ||= new Set()).add(rawtext);
```

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -3995,13 +3995,23 @@ namespace ts {
             if (!(symbol && !isPropertyOrMethodDeclarationSymbol(symbol))) {
                 return undefined;
             }
+            const links = getSymbolLinks(symbol);
+            const cache = (links.accessibleChainCache ||= new Map());
+            // Go from enclosingDeclaration to the first scope we check, so the cache is keyed off the scope and thus shared more
+            const firstRelevantLocation = forEachSymbolTableInScope(enclosingDeclaration, (_, __, node) => node);
+            const key = `${useOnlyExternalAliasing ? 0 : 1}|${firstRelevantLocation && getNodeId(firstRelevantLocation)}|${meaning}`;
+            if (cache.has(key)) {
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/compiler/checker.ts:4003]: Even better is to set the result as cache.set(result || false) and then get becomes:
```ts
const existing = cache.get(key);
if (existing !== undefined) return existing || undefined;
```

[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:4003]: Neither of these are particularly idiomatic (plus the first adds extra allocations and indirections while the second adds polymorphic accesses to avoid those), nor are they as likely to be optimized by the runtime in the future (a map `get` immediately following a checked `has` is enormously common). Moreover, even in this example where I know the cache is often hit, the difference doesn't result in any measurable performance improvement (I tried, and got the same overall times out). Given all that, I'd prefer not to change it.

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot perf test this

52499b1 added _another_ layer of caching, this one within `visitAndTransformType`, which is the recursive guard function in `typeToTypeNodeHelper`. That was able to bring the runtime of the example down to 3.7s on my machine (from 5.15s on the prior commit - moving the truncation cutoff counter in the prior commit got a 0.35s improvement form the previously stated 5.5s time) which, percentage-wise, is another substantial improvement. And with that, the new test is no longer our longest running test when running in parallel on my machine (which was my goal), so at this point I'm probably going to call this PR complete, barring any requested changes (or anomalous results from the above requested perf run). If `material-ui` is any indication, these changes could have some pretty positive real world impacts.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -4479,7 +4489,7 @@ namespace ts {
                     enclosingDeclaration,
                     flags: flags || NodeBuilderFlags.None,
                     // If no full tracker is provided, fake up a dummy one with a basic limited-functionality moduleResolverHost
-                    tracker: tracker && tracker.trackSymbol ? tracker : { trackSymbol: noop, moduleResolverHost: flags! & NodeBuilderFlags.DoNotIncludeSymbolChain ? {
+                    tracker: tracker && tracker.trackSymbol ? tracker : { trackSymbol: () => false, moduleResolverHost: flags! & NodeBuilderFlags.DoNotIncludeSymbolChain ? {
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts:4492]: Eh, while I understand we use `noop` to reduce memory load, this fallback tracker (along with the other host objects I adjusted) is constructed infrequently enough that it doesn't really matter, I think.
