### PR TITLE
When applying `// @ts-ignore` fix as a group, apply to a line only once.

### LINKED ISSUE #21378: Quick fix all for "Ignore this error message" can insert duplicate @ts-ignore comments if errors are on the same line
**TypeScript Version:**  2.7.0-dev.2018123

**Search Terms:** 
- Quick fix all
- JavaScript
- Ts-ignore

**Code**
Create a js file with two errors on the same line:

```ts
// @ts-check

const a = 1;
const b = 2;

a = 1; b = 1;
```

Trigger quick fix all to add `// @ts-ignore` before this line

**Expected behavior:**
Returned edit inserts a single `// @ts-ignore`

**Actual behavior:**

`getCombinedCodeFix ` returns two duplicate insertions for `// @ts-ignore`. This results in:

```js
// @ts-check

const a = 1;
const b = 2;

// @ts-ignore
// @ts-ignore
a = 1; b = 1;
```

```
[Trace  - 15:40:36] Response received: getCombinedCodeFix (2112). Request took 1 ms. Success: true 
Result: {
    "changes": [
        {
            "fileName": "/Users/matb/projects/san/b.js",
            "textChanges": [
                {
                    "start": {
                        "line": 6,
                        "offset": 1
                    },
                    "end": {
                        "line": 6,
                        "offset": 1
                    },
                    "newText": "// @ts-ignore\n"
                },
                {
                    "start": {
                        "line": 6,
                        "offset": 1
                    },
                    "end": {
                        "line": 6,
                        "offset": 1
                    },
                    "newText": "// @ts-ignore\n"
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #21378

### CODE REVIEW

File: src/services/codefixes/disableJsDiagnostics.ts [hunk 1]
```diff
@@ -35,15 +35,21 @@ namespace ts.codefix {
                 fixId: undefined,
             }];
         },
-        fixIds: [fixId], // No point applying as a group, doing it once will fix all errors
```
Comment (andy-ms) [inline src/services/codefixes/disableJsDiagnostics.ts]: This comment is better written a few lines up -- no point applying the `// @ts-nocheck` fix as a group. There *is* a point applying `// @ts-ignore` as a group.

File: src/services/codefixes/disableJsDiagnostics.ts [hunk 2]
```diff
@@ -35,15 +35,21 @@ namespace ts.codefix {
...
+                    if (addToSeen(seenLines, line)) {
+                        changes.push(change);
+                    }
+                }
+            });
+        },
     });
 
-    function getIgnoreCommentLocationForLocation(sourceFile: SourceFile, position: number, newLineCharacter: string): TextChange {
+    function getIgnoreCommentLocationForLocation(sourceFile: SourceFile, position: number, newLineCharacter: string): { line: number, change: TextChange } {
```
Comment (amcasey) [inline src/services/codefixes/disableJsDiagnostics.ts]: Unless there's an existing convention, I would be tempted to rename "line" to "lineNumber".  At the call site, I couldn't figure out whether it was the line text or the line number.  (Yes, I realize that using the line text would make no sense.)
