### PR TITLE
Fix inference to intersections

### LINKED ISSUE #30442: Type parameter inference regression in 3.4
**TypeScript Version:**  3.4.0-rc

**Search Terms:** Type parameters, generics, inference, regression

**Code**

```ts
const foo = <T>() => {};
const assign = <T, U>(a: T, b: U) => Object.assign(a, b);
const result: (() => void) & { foo: any } = assign(() => {}, { foo });
```

**Expected behavior:**

No error

**Actual behavior:**

```
Argument of type '{ foo: <T>() => void; }' is not assignable to parameter of type '(() => void) & { foo: any; }'.
  Type '{ foo: <T>() => void; }' is not assignable to type '() => void'.
    Type '{ foo: <T>() => void; }' provides no match for the signature '(): void'.
```

**Playground Link:**
https://www.typescriptlang.org/play/#src=const%20foo%20%3D%20%3CT%3E()%20%3D%3E%20%7B%7D%3B%0D%0Aconst%20assign%20%3D%20%3CT%2C%20U%3E(a%3A%20T%2C%20b%3A%20U)%20%3D%3E%20Object.assign(a%2C%20b)%3B%0D%0Aconst%20result%3A%20(()%20%3D%3E%20void)%20%26%20%7B%20foo%3A%20any%20%7D%20%3D%20assign(()%20%3D%3E%20%7B%7D%2C%20%7B%20foo%20%7D)%3B

**Related Issues:** 

---

Removing `<T>` from `foo` makes this code valid.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #30442.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14773,22 +14773,29 @@ namespace ts {
...
                     // less specific. For example, when inferring from Promise<string> to T | Promise<T>,
-                    // we want to infer string for T, not Promise<string> | string.
-                    const savePriority = priority;
-                    priority |= InferencePriority.NakedTypeVariable;
-                    for (const t of (<UnionOrIntersectionType>target).types) {
-                        if (getInferenceInfoForType(t)) {
-                            inferFromTypes(source, t);
+                    // we want to infer string for T, not Promise<string> | string. For intersection types
+                    // we only infer to single naked type variables.
+                    if (target.flags & TypeFlags.Union ? typeVariableCount !== 0 : typeVariableCount === 1) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: The old comment on this behavior was
```ts
                    // Next, if target containings a single naked type variable, make a secondary inference to that type
                    // variable. This gives meaningful results for union types in co-variant positions and intersection
                    // types in contra-variant positions (such as callback parameters).
```
should we perhaps be checking variance here, rather than (or perhaps alongside) count?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I don't think the `contravariant` flag is relevant here (or maybe I'm just not seeing how).

Comment (weswigham) [reply src/compiler/checker.ts]: The original in-code comment on this behavior said that it was inferences to intersections in contravariant positions (see above) that gave good results - it's possible that we could capture that sentiment by inferring to only one intersection parameter in covariant positions, but all of them in contravariant positions (and vice-versa for unions, I imagine?)

I dunno really; this is just speculation based on the text of a comment we removed, and assuming that there was insight in that comment which our tests didn't quite capture - without concrete examples, though, I'm not really sure.
