### PR TITLE
fix: add more strict type to Intl.CollatorOptions

### LINKED ISSUE #53507: Improve Intl.CollatorOptions type definitions
# lib Update Request

## Configuration Check

My compilation *target* is `ESNEXT` and my *lib* is `ESNEXT`.

## Missing / Incorrect Definition

Interface **CollatorOptions** in **Intl** module is not strict enough. It allows for any string to be passed to `localeMatcher`, `usage`, `sensitivity` and `caseFirst` properties, which should be restricted to their respective unions of possible values.

## Sample Code

This should complain, since every value in the options isn't usable per spec, but doesnt.

```typescript
const collator = new Intl.Collator(undefined, { 
  localeMatcher: 'custom',
  usage: 'my-use-case',
  sensitivity: 'very-sensitive',
  caseFirst: 'nope' 
});
```

## Documentation Link

[MDN Intl.Collator docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator)

### PR DESCRIPTION
**Pull request by Solo-steven**
Fixes #53507

### CODE REVIEW

File: src/lib/es5.d.ts [hunk 1]
```diff
@@ -4365,11 +4365,11 @@ declare var Float64Array: Float64ArrayConstructor;
...
-        usage?: string | undefined;
-        localeMatcher?: string | undefined;
+        usage?: "sort" | "search" | undefined;
+        localeMatcher?: "lookup" | "best fit" | undefined;
         numeric?: boolean | undefined;
-        caseFirst?: string | undefined;
-        sensitivity?: string | undefined;
+        caseFirst?: "upper" | "lower" | "false" | undefined;
+        sensitivity?: "base" | "accent" | "case" | "variant" | undefined;
         ignorePunctuation?: boolean | undefined;
```
Comment (nam-hle) [inline src/lib/es5.d.ts:4373]: What if adding `collation?: string | undefined` or even strictly its values?

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator

Comment (Solo-steven) [reply src/lib/es5.d.ts:4373]: Thanks for your advice !!

**Review by sandersn — APPROVED** [review]
