### PR TITLE
parse/check/emit shorthand property assignment in destructuring

### LINKED ISSUE #5035: Incorrectly parsed object destructuring assignment with short-hand properties
```typescript
function drawES5Chart(options) {
    options = options === undefined ? {} : options;
    var size: any,
        radius: any;
    let cords: any;
    ({size = "big", cords = { x: 0, y: 0 }, radius = 25} = options); // here
    console.log(size, cords, radius);
}
```

As far as I see in spec, that's allowed for object destructuring assignment, in form of:
```
AssignmentProperty[Yield] :
    IdentifierReference[?Yield] Initializer[In,?Yield]opt
```

### PR DESCRIPTION
**Pull request by vladima**
fixes #5035

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -562,6 +562,10 @@ namespace ts {
     export interface ShorthandPropertyAssignment extends ObjectLiteralElement {
         name: Identifier;
         questionToken?: Node;
```
Comment (JsonFreeman) [inline src/compiler/types.ts]: When would you have a question token in a shorthand?

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -800,6 +800,10 @@
         "category": "Error",
         "code": 1311
     },
+    "'=' can only be used in object literal properties inside destructuring assignment.": {
```
Comment (JsonFreeman) [inline src/compiler/diagnosticMessages.json]: "in an object literal property inside a destructuring assignment

File: src/compiler/types.ts (hunk 1 above)
Comment (vladima) [inline src/compiler/types.ts]: AFAIR we currently parse it and issue the grammar error later

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (vladima) [inline src/compiler/diagnosticMessages.json]: ok

**Comment by JsonFreeman** [comment]
Looks good, but probably someone on the team should sign off.

**Comment by vladima** [comment]
Thanks @JsonFreeman :)

**Comment by vladima** [comment]
@mhegazy can you take a look?

**Comment by DanielRosenwasser** [comment]
I actually posted comments earlier, but GitHub went down as I was posting them. Sorry about that @vladima

File: src/compiler/types.ts [hunk 3]
```diff
@@ -562,6 +562,10 @@ namespace ts {
     export interface ShorthandPropertyAssignment extends ObjectLiteralElement {
         name: Identifier;
         questionToken?: Node;
+        // used when ObjectLiteralExpression is used in ObjectAssignmentPattern
+        // it is grammar error to appear in actual object initializer
+        equalsToken?: Node;
```
Comment (DanielRosenwasser) [inline src/compiler/types.ts]: Why not just error on the `objectAssignmentInitializer`?

Comment (JsonFreeman) [inline src/compiler/types.ts]: I think the idea is to error on the first incorrect token. Also, this controls the span size so it is just 1.

Comment (vladima) [inline src/compiler/types.ts]: the comment is referring to both `equalsToken` and `objectAssignmentInitializer` - this pair matches `Initializer` part from `CoverInitializerName` [production](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer). My reasoning of reporting error on `=` instead of entire range `[equalsToken, objectAssignmentInitializer]` was:
- having large ranges of squigglies is annoying
- I can certainly see cases when by mistake people type `{x = 1}` instead of `{x: 1}` and personally for me it will look confusing if we squiggle `= 1` instead of just =`

Comment (vladima) [inline src/compiler/types.ts]: yes, @JsonFreeman is right

Comment (DanielRosenwasser) [inline src/compiler/types.ts]: Okay; in that case, can you amend the comment so it specifically says "The below are used". and just make it "It is a grammar error".

Other than that LGTM.
