### PR TITLE
Handle binding elements while looking for invalid `await` and `yield`

### LINKED ISSUE #18981: Await is allowed in object shorthand initializers in parameters
**TypeScript Version:**  2.5.1-insiders.20170825 (current playground version)

**Code**

```ts
async function foo({ foo = await import("bar") }) {
}
```

**Expected behavior:**
Error on `await import("bar")` as `foo = await import("bar")` is an error, so `{foo = await import("bar")}` should also be one.

**Actual behavior:**
No error, broken emit:
```ts
    function foo(_a) {
        var _b = _a.foo, foo = _b === void 0 ? yield new Promise(function (resolve_1, reject_1) { require(["bar"], resolve_1, reject_1); }) : _b;
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/];
            });
        });
    }
```

### PR DESCRIPTION
**Pull request by weswigham**
Also, handle omitting a node in the visitor passed into `addCustomPrologue`, fixing part of #19967, and account for binding elements in `isInParameterInitializerBeforeContainingFunction`, fixing #18981 and #19967.

Fixes #18981, #19967

### CODE REVIEW

File: src/compiler/factory.ts [hunk 1]
```diff
@@ -3707,9 +3707,14 @@ namespace ts {
     export function addCustomPrologue(target: Statement[], source: ReadonlyArray<Statement>, statementOffset: number, visitor?: (node: Node) => VisitResult<Node>): number {
         const numStatements = source.length;
         while (statementOffset < numStatements) {
-            const statement = source[statementOffset];
+            let statement = source[statementOffset];
             if (getEmitFlags(statement) & EmitFlags.CustomPrologue) {
-                target.push(visitor ? visitNode(statement, visitor, isStatement) : statement);
+                if (visitor) {
```
Comment (rbuckton) [inline src/compiler/factory.ts]: `append` checks if the value is `undefined`, so this could be written as:

```ts
append(target, visitor ? visitNode(statement, visitor, isStatement) : statement);
```
