### PR TITLE
Harden node builder APIs to no longer return `undefined` for a node when `NodeBuilderFlags.IgnoreErrors` is provided

### LINKED ISSUE #32864: TypeError: Cannot read property 'emitNode' of undefined in 'Object.getStartsOnNewLine' during 'signatureHelp'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 3.5.3
**VSCode version**: 1.37.0
**Command requested**: signatureHelp
**Hitting sessions**: 355
**Proportion of all sessions**: 0.907928388746803
**Five line hash**: 59b565e7ea447e9fba0c3f4dca390780
**Stack**:
```
TypeError: Cannot read property 'emitNode' of undefined
    at Object.getStartsOnNewLine (tsserver.js:64102:29)
    at shouldWriteSeparatingLineTerminator (tsserver.js:87446:27)
    at emitNodeList (tsserver.js:87231:29)
    at emitList (tsserver.js:87128:13)
    at Object.writeList (tsserver.js:84571:13)
    at unknown (tsserver.js:108011:29)
    at Object.mapToDisplayParts (tsserver.js:97547:13)
    at itemInfoForParameters (tsserver.js:108008:41)
    at getSignatureHelpItem (tsserver.js:107974:95)
    at unknown (tsserver.js:107947:79)
    at suppressed_frame()
    at createSignatureHelpItems (tsserver.js:107947:36)
    at unknown (tsserver.js:107539:23)
    at Object.runWithCancellationToken (tsserver.js:31649:28)
    at Object.getSignatureHelpItems (tsserver.js:107537:32)
    at Proxy.getSignatureHelpItems (tsserver.js:122266:37)
    at IOSession.Session.getSignatureHelpItems (tsserver.js:131224:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130124:61)
    at unknown (tsserver.js:131671:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:131662:28)
    at IOSession.Session.executeCommand (tsserver.js:131671:33)
    at IOSession.Session.onMessage (tsserver.js:131693:35)
    at Interface.<anonymous> (tsserver.js:132984:27)
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
    at suppressed_frame()
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #32864

The root cause of the crash in #32864 was a very trivial error - at a callsite in `signatureHelp.ts`, we neglected to pass in our normal set of `NodeBuilderFlags` that's supposed to guarantee we always get a node back. Upon seeing this, I've done two things:
* Changed the API so passing the `flags` parameter is required (it can still explicitly be `undefined`, and is such in many codefixes, which *hopefully* can handle the resulting possibly `undefined` result)
  * In doing so, I found a few more places in the symbol builder where we were neglecting to provide flags, where we now provide flags.
* Audited all usages of `context.encounteredError` in the node builder to ensure all places where we set it are guarded by a check of a flag included in `NodeBuilderFlags.IgnoreErrors`, this way we _know_ that if we provide that flag, even if the results might not be valid JS, they will, at least, _exist_ as a node tree

I've confirmed this fixes the repro provided in #32864, and have an appropriately similar fourslash test. Interestingly, it points out that our signature help in the presence of overloads is a little odd - the signature that is the currently "chosen" overload has its type parameters erased, while other overloads have their type parameters left in-place (a requirement for triggering the crash was that the signature must have had type parameters, which, because of this quirk, can only happen on overloaded signatures).

### CODE REVIEW

File: tests/baselines/reference/api/tsserverlibrary.d.ts [hunk 1]
```diff
@@ -2040,23 +2040,23 @@ declare namespace ts {
         getNonNullableType(type: Type): Type;
         getTypeArguments(type: TypeReference): readonly Type[];
         /** Note that the resulting nodes cannot be checked. */
-        typeToTypeNode(type: Type, enclosingDeclaration?: Node, flags?: NodeBuilderFlags): TypeNode | undefined;
+        typeToTypeNode(type: Type, enclosingDeclaration: Node | undefined, flags: NodeBuilderFlags | undefined): TypeNode | undefined;
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/api/tsserverlibrary.d.ts:2043]: This would be a break if we want it for 3.9.  Any way we can avoid it?

Comment (weswigham) [reply tests/baselines/reference/api/tsserverlibrary.d.ts:2043]: Easily - now that I've used it to audit our internal usages, swapping it back is pretty simple; changing it is just for safety at callsites.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4211,8 +4211,12 @@ namespace ts {
                 context.flags &= ~NodeBuilderFlags.InTypeAlias;
 
                 if (!type) {
-                    context.encounteredError = true;
-                    return undefined!; // TODO: GH#18217
+                    if (!(context.flags & NodeBuilderFlags.AllowEmptyUnionOrIntersection)) {
```
Comment (amcasey) [inline src/compiler/checker.ts:4214]: As we discussed offline, I think this (and below) would be clearer as `IgnoreErrors`, but I can live with this version if it's more idiomatic.

Comment (weswigham) [reply src/compiler/checker.ts:4214]: Ah, I struggled to enumerate it earlier, but if we check for `NodeBuilderFlags.IgnoreErrors`, then if _any_ of the `AllowX` flags are set, the error would be suppressed (as that's how binary `&` works) - it's much neater to tie it to a specific flag (I'd have been tempted to add new ones, but we're actually entirely our of flag space in this enum).

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this to release-3.9 (once the PR is up, I'll edit it to undo the API changes)

**Comment by rbuckton** [comment]
This may also fix #32851
