### PR TITLE
When there is no change in file text for program, no need to update program

### LINKED ISSUE #51611: Typescript watch compiles each edited file twice
# Bug Report

### 🔎 Search Terms

Typescript watch triggers multiple compilations

### 🕗 Version & Regression Information

This changed when moving from Typescript version 4.8.4 to 4.9.3

Reviewed: https://github.com/microsoft/TypeScript/issues/37994

### ⏯ Demonstration Video

https://user-images.githubusercontent.com/95563185/203037679-74cd13ca-db5b-4d02-bc14-41df238609d0.mov

### 💻 Code
package.json
==========
{
  "name": "testtsc",
  "version": "1.0.0",
  "description": "Test double compilation of TypeScript files",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Elad Stern",
  "license": "ISC",
  "dependencies": {
    "typescript": "^4.9.3"
  }
}

main.ts
======
let a: string = "123456790123";
alert(a.slice(0, 2));

### 🙁 Actual behavior

In terminal, invoking npx and then tsc main.ts --watch, changing the source code of main.ts triggers Typescript watch to compile the file again - not once, but twice. The same took place in larger projects - double compilation of changed files, with one or two seconds in between.

### 🙂 Expected behavior

Once a source code file has been changed, it should compile only once by tsc watch, not twice.

### PR DESCRIPTION
**Pull request by sheetalkamat**
There have been cases where file change notification is reported twice by the native node file system events. We have setup many optimizations for this. eg we schedule updates instead of updating right away so if the events occur before that scheduled update, the program gets updated only once. But if the repeat event is received after we have updated event, we recreate program where the structure is used completely but we still have new copy. This means we don't emit program but there is still cost incurrent with binding and creating type checker and more over user gets notified that file change was detected and program will be rebuilt. So, from user perspective we are doing double compilation even though we didn't really emit anything.  The main root cause for creating new program is that when getting new source file version, we don't read text and figure out if it has changed or not. We used to delay it to creating source files. 
With this change, we will read file if the sourceFile state is unknown (that is we received the file change event). So, if text has not changed, we won't create new program, not report file change detected either.
Also had to modify how we read file for the sourceFile so that we can use cached text because now there are two places where we are reading source file text.

Fixes #51611

### CODE REVIEW

File: src/compiler/watch.ts [hunk 1]
```diff
@@ -739,9 +739,9 @@ export function createWatchFactory<Y = undefined>(host: WatchFactoryHost & { tra
 export function createCompilerHostFromProgramHost(host: ProgramHost<any>, getCompilerOptions: () => CompilerOptions, directoryStructureHost: DirectoryStructureHost = host): CompilerHost {
     const useCaseSensitiveFileNames = host.useCaseSensitiveFileNames();
     const hostGetNewLine = memoize(() => host.getNewLine());
-    return {
+    const compilerHost: CompilerHost = {
         getSourceFile: createGetSourceFile(
-            (fileName, encoding) => host.readFile(fileName, encoding),
+            (fileName, encoding) => !encoding ? compilerHost.readFile(fileName) : host.readFile(fileName, encoding),
```
Comment (jakebailey) [inline src/compiler/watch.ts:744]: Odd to me that this looks like this, given `compilerHost` just defers to `host.readFile` too. Is it expected that `CompilerHost` is missing this parameter?

**Review by jakebailey — COMMENTED** [review]
Seems good to me, good baseline improvement. I am confused about `readFile` though.

File: src/compiler/watch.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/watch.ts:744]: I think we are suppose to deprecate the `encoding = charSet from compilerOptions` Our APIs dont have that consistent everywhere.

Comment (sheetalkamat) [reply src/compiler/watch.ts:744]: compilerHost.readFile is normally used for module resolution only and it doesnt support passing encoding...

**Review by andrewbranch — APPROVED** [review]
