### PR TITLE
fix(43359): Emit bug: default export is missing when exporting type+named+default

### LINKED ISSUE #43359: Emit bug: default export is missing when exporting type+named+default
# Bug Report

When using a single identifier to export three things (a _type_, a  _named export_, and a _default export_) the  _default export_ is dropped from the emitted JS.

### 🔎 Search Terms

"default export" skipped dropped elided omitted forgotten "JS emit" type "named export" "JS+types"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UB2BXAtgIwgJwLACgIAPMAe22CgGNSkBnSuRARgG4DiyKoATCAMwCGKADaNWQA)

### 💻 Code

```ts
type X = number;
export const X = 1;
export default X;
```

The problem is equally replicable with `interface` and object types.

### 🙁 Actual behavior

JS semantics are not preserved in the JS emit:

```js
export const X = 1;
```

### 🙂 Expected behavior

```js
export const X = 1;
export default X;
```

### Credit

This bug was discovered by @ollupac

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43359

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -39998,7 +39998,7 @@ namespace ts {
 
         function isAliasResolvedToValue(symbol: Symbol): boolean {
             const target = resolveAlias(symbol);
```
Comment (rbuckton) [inline src/compiler/checker.ts:40000]: I'd recommend this instead just to ensure we evaluate the conditions at the bottom of the function:
```suggestion
            const target = getExportSymbolOfValueSymbolIfExported(resolveAlias(symbol));
```

This will unwrap the `ExportValue` symbol to the underlying symbol

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -39998,7 +39998,7 @@ namespace ts {
 
         function isAliasResolvedToValue(symbol: Symbol): boolean {
             const target = resolveAlias(symbol);
-            if (target === unknownSymbol) {
+            if (target === unknownSymbol || (target.flags & SymbolFlags.ExportValue)) {
```
Comment (rbuckton) [inline src/compiler/checker.ts:40001]: (part of the previous suggestion, since GitHub won't allow me to create a suggestion that covers both lines due to the deleted line).
```suggestion
            if (target === unknownSymbol) {
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Thanks!

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: I tried to use that helper, however, there were two tests that failed. So I decided to use `ExportValue` instead. Especially I worry about that case - `https://github.com/microsoft/TypeScript/pull/44718/files#diff-d988b2b521a3b21ff40a4a21627ee0647acb2bbb0fe987d90a787c7e8b661cc4R12-R13

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: @rbuckton What do you think about the cases that I pointed above?

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: @rbuckton What do you think about the cases that I pointed above?

Comment (rbuckton) [reply src/compiler/checker.ts]: In what way did they fail?

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Tests fail with using ‘getExportSymbolOfValueSymbolIfExported‘ instead of ExportValue

Comment (rbuckton) [reply src/compiler/checker.ts]: Both 1 and 2 seem correct to me.

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Ok. Thanks for your review. Do you have any other remarks that I need to fix?

Comment (rbuckton) [reply src/compiler/checker.ts]: Actually, to clarify: 2 looks correct (the source uses `export =` so it shouldn't have `__esModule` in the emit). 1 looks strange, but we're also contending with errors in the checker due to duplicate conflicting declarations that would make any emit in 1 suspect, so I think its still an acceptable change.

**Review by rbuckton — APPROVED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Thanks for the detailed clarification. 👍🏻
