### PR TITLE
Static initializers may refer to later static methods

### LINKED ISSUE #14312: Regression: Initialization of static property with chained method call gives TS2448
**TypeScript Version:**  2.2.1 , installed via npm

**Code**

```ts
// Environment Summary:  Visual Studio Code 1.9.1 with the following installed:
//
//    > npm list
//    test@0.0.1 C:\Users\abrown\src\test
//    +-- @types/jquery@2.0.40
//    +-- jquery@3.1.1
//    `-- typescript@2.2.1
//
namespace TestNamespace {
    export class TestClass {
        // Contrived, just to support showing a minimal example:
        private static getTemplate(): JQuery { return $(document); }

        // TypeScript error:
        // test.ts(7,53): error TS2448: Block-scoped variable 'find' used before its declaration.
        private static jq = TestClass.getTemplate().find("whatever");

        // But OK here:
        private static test() {
            var jq = TestClass.getTemplate().find("whatever");
        }
    }
}

```

**Expected behavior:**
Compiles without error

**Actual behavior:**
test.ts(7,53): error TS2448: Block-scoped variable 'find' used before its declaration.

Both .getTemplate() and JQuery.find() return JQuery.  So I cannot see why chaining a call to .find() would give the error above.  Reviewed the TypeScript spec but could not locate anything that spoke to this.

**Notes:**
This compiled successfully in TypeScript 2.1.6

### PR DESCRIPTION
**Pull request by sandersn**
Static methods are created before static property initializers run, so static property initializers may refer to static methods. This was not allowed previously.

Fixes #14312

### CODE REVIEW

File: tests/cases/compiler/scopeCheckStaticInitializer.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+class X {
```
Comment (alexeagle) [inline tests/cases/compiler/scopeCheckStaticInitializer.ts]: The bug can also be observed on non-statics:

```
class Y {
  a = "" + this.b;
  b = "";
}
```

I'm not sure if your fix handles this case as well.

Comment (sandersn) [inline tests/cases/compiler/scopeCheckStaticInitializer.ts]: `this.b` is `undefined` in the expression `"" + this.b`, even though its initial value is supposed to be `""`. I think we want to error in this case.
