### PR TITLE
Fix completions crash on transient exported property named 'default'

### LINKED ISSUE #40991: esModuleInterop:true breaks intellisense
Issue Type: <b>Bug</b>

These tsconfig.json values are completely breaking intellisense for my project:
```ts
		"module": "commonjs",
		"moduleResolution": "node",
```

When I take these out, and restart ts server, it works fine, if i put them back in and restart ts server, it stops working.

**Observed result:**
When typing in something in code, such as `Time`, which vscode should be suggesting me to import from somewhere, no dropdown appears at all, and if I do `ctrl+space`, it says no suggestions. Again, I remove those 2 config options, restart ts server, and it works fine.

**Expected result:**
Should show a dropdown pretty much in 99% of cases when im typing, doesnt show a dropdown AT ALL.

**Reproduction:**
You could try use my repo to reproduce: https://github.com/oldschoolgg/oldschoolbot

Note that, these 2 config options come from the `eslint-config-bamboo` that im extending in the tsconfig.json there, **however** I am using these 2 tsconfigs locally for debugging this: https://gist.github.com/gc/fa1110fa28e7a66ac0b1ee42a73435a6

to test that its working, go to `index.ts` and type in the word `roll` and/or `Time` - both should definitely be giving suggestions.

removing these 2 options however breaks other stuff, and isnt a viable solution for me to use. hopefully someone canhelp me find the root cause.

**note:** I have tried completely, entirely nuking vscode (including all my settings) from my PC, clearing all node_modules and caches, and reinstalling - and that didnt fix it.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.45GB free)|
|Process Argv|--crash-reporter-id 693da592-757d-488c-9730-a967bac12a33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.7.1
vscode-styled-components|jpo|0.0.32
material-icon-theme|PKi|4.3.0
ayu|tea|0.20.1
material-theme|zhu|3.9.1

(1 theme extensions excluded)

</details>

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40991

Also includes a drive-by improvement to allow us to get a name for `default` or `export=` when the target is an identifier with parentheses, non-null assertions, type assertions, etc., instead of just a bare identifier.

### CODE REVIEW

File: tests/cases/fourslash/completionsImport_weirdDefaultSynthesis.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+//// Colle/**/
+
+verify.applyCodeActionFromCompletion("", {
+  name: "Collection",
+  source: "/collection",
+  description: `Import 'Collection' from module "./collection"`,
+  preferences: {
+    includeCompletionsForModuleExports: true
+  },
+  newFileContent: `import Collection = require("./collection");\n\nColle`
```
Comment (amcasey) [inline tests/cases/fourslash/completionsImport_weirdDefaultSynthesis.ts:19]: Possibly I'm misreading something, but shouldn't "Colle" be completed to "Collection"?

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -650,23 +650,21 @@ namespace ts.codefix {
                 //    but we can still offer completions for it.
                 // - `aliased.parent` will be undefined if the module is exporting `globalThis.something`,
```
Comment (amcasey) [inline src/services/codefixes/importFixes.ts:651]: Does this comment still matter?

**Review by amcasey — APPROVED** [review]
These all seem like sensible changes, but it's not immediately obvious to me what was actually crashing.  Maybe `aliased.parent` was undefined?

File: tests/cases/fourslash/completionsImport_weirdDefaultSynthesis.ts (hunk 1 above)
Comment (andrewbranch) [reply tests/cases/fourslash/completionsImport_weirdDefaultSynthesis.ts:19]: `applyCodeActionFromCompletion` only does what it says; it doesn’t apply the completion itself.

File: src/services/codefixes/importFixes.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:651]: Yes; this is a separate case where something is missing a parent.

**Comment by andrewbranch** [comment]
In this case `default` was an intersection property where the constituent properties had different parents. So on the intersection property, there is no `parent`, because it’s not clear why one parent would be favored over the other. A “real” default export should never be an intersection property, or transient at all (this was just manually named “default”), so there was no reason to treat it as an auto-importable export.
