### PR TITLE
Treat variable declaration as top-level if it has an important child.

### LINKED ISSUE #10558: JavaScript function is not listed in "ctrl+shift+o"
_From @qlqllu on August 24, 2016 8:16_

- VSCode Version:1.4.0
- OS Version: Windows10

Steps to Reproduce:

1.  Create a JS file with this content:
```
function f1(){};

var obj = f1({
    p1: function(){}
});

```
2.  Open this JS file and type "ctrl+shift+o", notice that the `p1` function is not listed in the symbols list.
3. However, `p1` can be listed in this file 
```
function f1(){};

var obj;
obj = f1({
    p1: function(){}
});

```

Please notice that the only difference is the place to declare the `obj` variable.

_Copied from original issue: Microsoft/vscode#10877_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #10558

I think a better long-term solution to this would be to avoid calling `topLevelItems` for vscode.
Currently we do this:

    map(topLevelItems(rootNavigationBarNode(sourceFile)), convertToTopLevelItem);

If a node isn't a top-level item or a child of one, it simply disappears from navigation.
In addition, the notion of top-level items are only used by visual studio anyway, so they waste time in vscode.
This also results in vscode counting a node twice if it is both a top-level item and also a child of one.
I think it would be better to do something like this:

    function getNavigationBarItemsForVsCode(sourceFile): VsCodeNavigationBarItem[] {
        return map(rootNavigationBarNode(sourceFile), convertToVsCodeItem);
    }

`VsCodeNavigationBarItem` could be simple: just `{ text, kind, kindModifiers, spans, indent }`.

### CODE REVIEW

File: tests/cases/fourslash/navigationBarAnonymousClassAndFunctionExpressions.ts [hunk 1]
```diff
@@ -91,6 +91,17 @@ verify.navigationBar([
         "indent": 2
     },
     {
+        "text": "y",
```
Comment (sandersn) [inline tests/cases/fourslash/navigationBarAnonymousClassAndFunctionExpressions.ts]: does the associated comment on the source line need to change? Currently it says "this is not a top-level function".

**Comment by sandersn** [comment]
:+1:

File: tests/cases/fourslash/navigationBarAnonymousClassAndFunctionExpressions.ts (hunk 1 above)
Comment (andy-ms) [inline tests/cases/fourslash/navigationBarAnonymousClassAndFunctionExpressions.ts]: No, it's still a childItem and not top-level, although `y` is now top-level.
