### PR TITLE
[Master] Emit parenthesis around propert/element access expression of casted object literal expression

### LINKED ISSUE #14895: cast and accessor with target es6 produces invalid code
**TypeScript Version:**  2.3.0-dev.20170328

**Code**

The following code produces wrong output, when run through tsc, only when target is es6, the "as"-cast exists and the accessor "[x]" exists.

```ts
(x) => ({ "1": "one", "2": "two" } as { [key: string]: string })[x];
```

**Expected behavior:**
Running "tsc -t es6" on the above code in a .ts file I expect to get a .js file containing:
(x) => ({ "1": "one", "2": "two" })[x];

**Actual behavior:**
(x) => { "1": "one", "2": "two" }[x];

### PR DESCRIPTION
**Pull request by yuit**
Fix #14895

### CODE REVIEW

File: src/compiler/transformers/ts.ts [hunk 1]
```diff
@@ -2324,14 +2324,19 @@ namespace ts {
...
                 // ParenthesizedExpression will be inserted if we remove parentheses too
                 // aggressively.
-                //
-                // To preserve comments, we return a "PartiallyEmittedExpression" here which will
-                // preserve the position information of the original expression.
-                return createPartiallyEmittedExpression(expression, node);
+                // However, auto-parenthesization will not preserve parenthesis for the following case: ({ "1": "one", "2": "two" } as { [key: string]: string })[x].
+                // so we have to manually preserve it here.
+                const shouldPreserveParen = (isPropertyAccessExpression(node.parent) || isElementAccessExpression(node.parent)) &&
+                    isObjectLiteralExpression((expression as PartiallyEmittedExpression).expression);
```
Comment (rbuckton) [inline src/compiler/transformers/ts.ts]: This is not the correct place to make a change. If we were to take this change, another feature at a later date could run into the same issue. Instead, we should make this change in the parenthesization logic in `factory.ts`.

If you look at [`parenthesizeExpressionForExpressionStatement`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/factory.ts#L3438), we check the kind of the left-most expression. However, in [`parenthesizeConciseBody`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/factory.ts#L3495) we are not performing the same check. 

I would recommend we modify `parenthesizeConciseBody` to call `getLeftmostExpression` instead of `skipParenthesizedExpressions`. That should correct this issue in a single place.

File: src/compiler/factory.ts [hunk 2]
```diff
@@ -3492,7 +3492,8 @@ namespace ts {
 
     export function parenthesizeConciseBody(body: ConciseBody): ConciseBody {
         const emittedBody = skipPartiallyEmittedExpressions(body);
-        if (emittedBody.kind === SyntaxKind.ObjectLiteralExpression) {
+        const leftMostExpression = isExpression(emittedBody) ? getLeftmostExpression(emittedBody) : undefined;
```
Comment (rbuckton) [inline src/compiler/factory.ts]: I think this could just be:

```ts
if (!isBlock(body) && getLeftmostExpression(body).kind === SyntaxKind.ObjectLiteralExpresion)
```

I suggest using `!isBlock(body)` here as there are fewer comparisons necessary than a full `isExpression` test.
