### PR TITLE
Detect comparisons between large unions or intersections

### LINKED ISSUE #41517: Slow compilation issues (40-50s) - --skipLibCheck not working
**TypeScript Version:**  3.8.3

**Search Terms:** --skipLibCheck slow compilation tsc

**Code**

Running tsc --listFiles --generateCpuProfile profile --skipLibCheck from the command line results in having the following output - which appears to be slowing compilation significantly. It appears as though it's including multiple .d.ts files from my @types node_modules in the compilation. What sort of time should I be expecting this amount of files to compile in? **Any help reducing the compilation time would also be greatly appreciated.**

```
/home/user1/projects/projectName/node_modules/@types/semantic-ui-form/global.d.ts
/home/user1/projects/projectName/node_modules/@types/jquery/JQueryStatic.d.ts
/home/user1/projects/projectName/node_modules/@types/moment-timezone/moment-timezone.d.ts
.....etc

Extended diagnostics are:
Files:                         3022
Lines:                       410050
Nodes:                      1604064
Identifiers:                 555657
Symbols:                     804555
Types:                       254555
Memory used:               1220647K
Assignability cache size:     95587
Identity cache size:          13620
Subtype cache size:         4718477
Strict subtype cache size:     6378
I/O Read time:                0.10s
Parse time:                   1.78s
Program time:                 3.22s
Bind time:                    1.45s
Check time:                  39.98s
transformTime time:           1.39s
commentTime time:             0.56s
I/O Write time:               0.20s
printTime time:               5.02s
Emit time:                    5.02s
Total time:                  49.68s
 
```

my tsconfig is as follows:
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "extendedDiagnostics": true,
    "baseUrl": "src/",
    "module": "commonjs",
    "target": "es6",
    "jsx": "react",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "lib": [
      "dom",
      "es2015",
      "scripthost",
      "es6",
      "es2016",
      "es2017"
    ]
  },
  "include": [
    "./src/**/*.ts",
    "./src/**/*.tsx"
  ],
  "exclude": [
    "node_modules",
    ".idea",
    ".storybook",
    ".git",
    "dist"
  ]
}

```

with my project folder structure being:
```
├── src
│   ├── folder1/....
│   └── folder2/.....
├── node_modules
│   ├── shouldNotBeCompiled1.d.ts
│   ├── shouldNotBeCompiled2.d.ts
│   └── shouldNotBeCompiled3.d.ts
├── dist
```

**Expected behavior:**
Should not type-check any of the files inside node_modules during compilation
**Actual behavior:**
Appears to be including node_modules/@types during compilation - which is causing a compilation time of ~50s for project.

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/37635
https://github.com/microsoft/TypeScript/issues/36103

### PR DESCRIPTION
**Pull request by amcasey**
If their multiplied size is greater than 1E7 (chosen based on the repro
in #41517), then we'll expend a large amount of time and memory
comparing them, so alert the user instead.

Fixes #41517

### CODE REVIEW

**Comment by amcasey** [comment]
@typescript-bot test this

**Comment by amcasey** [comment]
@typescript-bot pack this

**Comment by amcasey** [comment]
@NoPhaseNoKill the bot should post a link to a private build shortly.  If you have a minute, can you please confirm that this change correctly flags the problematic expression in your real code?  (I've already confirmed that it works in the toy repro.)

**Comment by NoPhaseNoKill** [comment]
The error I'm now seeing in the compiler is:

```
ERROR in /[redacted]src/app/ui/components/IconButton.tsx
ERROR in /[redacted]/src/app/ui/components/IconButton.tsx(23,17):
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<IconProps>): Icon', gave the following error.
    Expression requires comparison of excessively large unions or intersections.
  Overload 2 of 2, '(props: IconProps, context?: any): Icon', gave the following error.
    Expression requires comparison of excessively large unions or intersections.
```

Looks good to me :)

**Comment by NoPhaseNoKill** [comment]
Are there any places I can lodge/put in feedback for the help you've given me? I just want to say what an excellent experience this has been for me.

Normally, dealing with large companies/significant repo's it's an absolute nightmare. So thank you very much for all your help, you deserve to be recognised formally.

**Comment by amcasey** [comment]
Thanks for confirming!  I'm glad we could get that sorted out for you.  And, no, there won't be a satisfaction survey - if you're happy, I'm happy. :smile:

**Comment by NoPhaseNoKill** [comment]
Sounds good man, thanks for the help again. I'll reach out if we find any unusual behaviour in the future. Keep in touch, Tom

**Comment by amcasey** [comment]
@ahejlsberg pointed out that we probably want different limits for primitive and non-primitive unions/intersections.  I'll try to work some out empirically.

**Comment by amcasey** [comment]
@typescript-bot test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -17011,11 +17014,38 @@ namespace ts {
...
+                    const targetUnionOrIntersection = target as UnionOrIntersectionType;
+
+                    if (sourceUnionOrIntersection.objectFlags & targetUnionOrIntersection.objectFlags & ObjectFlags.PrimitiveUnion) {
+                        // There's a fast path for comparing primitive unions
+                        return false;
+                    }
+
+                    const sourceSize = sourceUnionOrIntersection.types.length;
+                    const targetSize = targetUnionOrIntersection.types.length;
+                    if (sourceSize * targetSize > 1E7) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:17029]: I think the limit should be 1000000 (1M). That's the limit we use for non-primitive unions in subtype reduction.

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -3059,6 +3059,10 @@
         "category": "Error",
         "code": 2796
     },
+    "Expression requires comparison of excessively large unions or intersections.": {
```
Comment (ahejlsberg) [inline src/compiler/diagnosticMessages.json:3062]: Change to "...excessively large union or intersection types."

File: tests/cases/compiler/largePrimitiveUnionComparisons.ts [hunk 3]
```diff
@@ -0,0 +1,106 @@
+type PrimitiveUnion =
```
Comment (ahejlsberg) [inline tests/cases/compiler/largePrimitiveUnionComparisons.ts:1]: You could simplify this to

```ts
type PrimitiveUnion =
    `x${0 | 1 | 2 | 3 | 4}${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}`;
```

**Review by ahejlsberg — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (amcasey) [reply src/compiler/checker.ts:17029]: Will do.

File: src/compiler/diagnosticMessages.json (hunk 2 above)
Comment (amcasey) [reply src/compiler/diagnosticMessages.json:3062]: Will do.

File: tests/cases/compiler/largePrimitiveUnionComparisons.ts (hunk 3 above)
Comment (amcasey) [reply tests/cases/compiler/largePrimitiveUnionComparisons.ts:1]: I was worried that, if I declared it as something other than an expanded union, we might change the representation in the future, silently invalidating the test.  For example, one can imagine specializing type comparison for string template types so that the union didn't have to be expanded.  TBH, string template types hadn't occurred to me, but I did specifically avoid using conditional spreads.

**Comment by amcasey** [comment]
RWC shows no instances of the new error text.

File: tests/cases/compiler/largePrimitiveUnionComparisons.ts (hunk 3 above)
Comment (amcasey) [reply tests/cases/compiler/largePrimitiveUnionComparisons.ts:1]: I tried it and learned that the baseline captures the expansion, so we'll know if it changes.

**Comment by amcasey** [comment]
@typescript-bot pack this

File: tests/baselines/reference/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.errors.txt [hunk 4]
```diff
@@ -0,0 +1,8018 @@
+tests/cases/compiler/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.ts(8011,26): error TS2797: Expression requires comparison of excessively large union or intersection types.
```
Comment (weswigham) [inline tests/baselines/reference/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.errors.txt:1]: I'm pretty sure adding an error into this test kinda invalidates it, since it was here to test that we could do a thing without timing out - not being able to do it _at all_ is kinda strictly worse (and, moreover, means we're no longer testing for a timeout). Is it just a matter of the limit being too low? #37749 made it so this is actually quite cheap for us (and this is just a simplified form of a common reactish pattern), so we shouldn't have an error here.

Comment (weswigham) [reply tests/baselines/reference/conditionalTypeDiscriminatingLargeUnionRegularTypeFetchingSpeedReasonable.errors.txt:1]: Specifically, regarding the limit, these kinda of errors are "hard blocks" in scenarios which may otherwise work, so we should ensure we only ever issue them them in cases where we'd either time out, stack out, or OOM without the error. If we can process the comparison without one of those three things occuring, we shouldn't be retiring, IMO.

**Comment by amcasey** [comment]
Force pushed a rebase, so that feedback-driven changes would show up cleanly in subsequent commits.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -17088,11 +17089,43 @@ namespace ts {
...
+
+                    if (sourceUnionOrIntersection.objectFlags & targetUnionOrIntersection.objectFlags & ObjectFlags.PrimitiveUnion) {
+                        // There's a fast path for comparing primitive unions
+                        return;
+                    }
+
+                    const sourceSize = sourceUnionOrIntersection.types.length;
+                    const targetSize = targetUnionOrIntersection.types.length;
+                    if (sourceSize * targetSize > 1E6) {
+                        if (reportErrors) {
```
Comment (weswigham) [inline src/compiler/checker.ts:17109]: This probably doesn't need to be guarded by `reportErrors` anymore, no?

**Review by weswigham — APPROVED** [review]
:+1: tracepoint

File: src/compiler/checker.ts (hunk 5 above)
Comment (amcasey) [reply src/compiler/checker.ts:17109]: I thought I should leave it so we didn't get a bunch of duplicate reports, but I may have misunderstood what the flag does.  I guess I should just test it.

Comment (weswigham) [reply src/compiler/checker.ts:17109]: You can still get duplicate reports with it in place if a comparison happens to show up multiple times in a program, and we do do some comparisons with `reportErrors` off only.

Comment (amcasey) [reply src/compiler/checker.ts:17109]: There are several duplicates without the check, but a bunch of valuable events are lost with it.  De-duping is easy, so I'll drop the check.
