### PR TITLE
fix jsx completions after attributes

### LINKED ISSUE #39530: No aria suggestions for on react element when suggestions are manually triggered
From https://github.com/microsoft/vscode/issues/97220
**TypeScript Version:**  4.0.0-dev.20200708

**Search Terms:**
- jsx
- react
- aria
- suggest / suggestions / completions

**Code**
For the TS

```ts
import * as React from 'react';

export const a = (<div className="fdsa"></div>)
```

After the classname attribute:

1. Manually trigger suggestions.
1. Type `aria`

**Expected behavior:**
Suggestions for aria show up

**Actual behavior:**
No suggestions.

In my testing, the suggestions do show up in a few different cases:

1. When you manually trigger suggestions before className
1. When you start typing to trigger suggestions

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #39530

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -1038,7 +1038,20 @@ namespace ts.Completions {
...
 
+                    case SyntaxKind.JsxExpression:
+                        // For `<div foo={true} [||] ></div>`, `parent` will be `{true}` and `previousToken` will be `}`
+                        if (previousToken.kind === SyntaxKind.CloseBraceToken && currentToken.kind === SyntaxKind.GreaterThanToken) {
+                            isJsxIdentifierExpected = true;
+                        }
+                        break;
+
                     case SyntaxKind.JsxAttribute:
+                        // For `<div className="x" [||] ></div>`, `parent` will be JsxAttribute and `previousToken` will be its initializer
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:1049]:
```suggestion
                        // For `<div className="x" [||] ></div>`, `parent` will be JsxAttribute and `previousToken` will be its initializer `"x"`
```
