### PR TITLE
Fix #15200: Query for semantic errors on .js files with '@ts-check' with no config file

### LINKED ISSUE #15200: @ts-check Not Working in Inferred Projects or in Project With JSConfig
**TypeScript Version:**  2.3.1-0414insiders

**Code**
In the JS file

```js
/// @ts-check
var x = "string";
x = 0;
```

With a `jsconfig.json`:

```json
{
     "compilerOptions": {
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "*.js"
    ]
}
```

**Expected behavior:**
In my understanding, the `/// @ts-check` directive should enable checks in the js file, even though `checkJs` is not set in the config

**Actual behavior:**
This directive does not seem have any effect. Enabling `checkJs` enables the js error reporting. When using a `tsconfig` with ` "allowJs": true`, I do see error reporting even when `checkJs` has not been set

Also, I'm unable to use `/// @ts-check` in javascript file that is part of an an inferred project in VSCode. Here are the options we send:

```
[Trace - 2:36:21 PM] Sending request: compilerOptionsForInferredProjects (1). Response expected: yes. Current queue length: 2
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve"
    }
}
```

### PR DESCRIPTION
**Pull request by mhegazy**
tsserver checks before calling `getSemanticDiagnostics` if this is a JS-only project first to avoid paying the cost of a semantic check on .d.ts files and second to avoid reporting errors that users do not care about (e.f. in .d.ts files auto-injected by ATA).

The check does not make sense in the presence of `// @ts-check` since every .js file now is a fair target for calling getSemanitcDiagnostics.

This change has two parts:
- Make the check on the tsserver work on the file-level instead of the project level, only skipping checking on .d.ts files but not .js files
- For configured projects, defer to the `program.getSemanticDiagnostics` instead of cutting it too early in the server, and instead make sure the program does not return bind diagnostics for .d.ts files if check diagnostics are not reported (i.e. `--skipLibCheck` or `--skipDefaultLibCheck` are set).

Fixes #15200

@billti can you please review this change. this touches on a change you have added recently.

### CODE REVIEW

File: src/compiler/program.ts [hunk 1]
```diff
@@ -908,6 +908,13 @@ namespace ts {
 
         function getSemanticDiagnosticsForFileNoCache(sourceFile: SourceFile, cancellationToken: CancellationToken): Diagnostic[] {
             return runWithCancellationToken(() => {
+                // If skipLibCheck is enabled, skip reporting errors if file is a declaration file.
+                // If skipDefaultLibCheck is enabled, skip reporting errors if file contains a
+                // '/// <reference no-default-lib="true"/>' directive.
```
Comment (billti) [inline src/compiler/program.ts]: This comment isn't making much sense to me as written. If you have no-default-lib set to true, then I assume there is no default lib to check - in which case, what difference does skipDefaultLibCheck make?

File: src/server/session.ts [hunk 2]
```diff
@@ -25,15 +25,17 @@ namespace ts.server {
...
+        // For inferred (e.g. miscellaneous context in VS) and external projects (e.g. VS .csproj project) with only JS files
+        // semantic errors in .d.ts files (e.g. ones added by automatic type acquisition) are not interesting.
+        // We want to avoid the cost of querying for these errors all together, even if 'skipLibCheck' is not set.
+        // We still want to check .js files (e.g. '// @ts-check' or '--checkJs' is set).
+        if ((project.projectKind === ProjectKind.Inferred || project.projectKind === ProjectKind.External) &&
+            project.isJsOnlyProject()) {
+            const scriptInfo = project.getScriptInfoForNormalizedPath(file);
+            return scriptInfo && !scriptInfo.isJavaScript();
         }
+        return false;
```
Comment (billti) [inline src/server/session.ts]: So this always returns false for configured projects (as the above `if` is only entered for inferred/external projects)?

File: src/server/session.ts [hunk 3]
```diff
@@ -25,15 +25,17 @@ namespace ts.server {
...
-        }
-        else {
-            // For configured projects, require that skipLibCheck be set also
-            const options = project.getCompilerOptions();
-            return options.skipLibCheck && !options.checkJs && project.isJsOnlyProject();
+    function shouldSkipSemanticCheck(project: Project, file: NormalizedPath) {
+        // For inferred (e.g. miscellaneous context in VS) and external projects (e.g. VS .csproj project) with only JS files
+        // semantic errors in .d.ts files (e.g. ones added by automatic type acquisition) are not interesting.
+        // We want to avoid the cost of querying for these errors all together, even if 'skipLibCheck' is not set.
+        // We still want to check .js files (e.g. '// @ts-check' or '--checkJs' is set).
```
Comment (billti) [inline src/server/session.ts]: This code always returns false for JavaScript files (due to `&& !scriptInfo.isJavaScript()`), so the comment about @ts-check / --checkJs is confusing. Where do these come into play then, if not taked into account in this method?

File: src/server/session.ts (hunk 2 above)
Comment (mhegazy) [inline src/server/session.ts]: yes. program.getSemanticDiagnostics should do the right thing for configured projects.

File: src/server/session.ts (hunk 3 above)
Comment (mhegazy) [inline src/server/session.ts]: we do not know here (in the server) if the .js file should be checked or not. we know that later on by inspecting the SourceFile object in the program. so what we are doing here is we are deferring the check to `program.getSemanticDiagnostics`

File: src/compiler/program.ts (hunk 1 above)
Comment (mhegazy) [inline src/compiler/program.ts]: `no-default-lib` is just a triple-slash directive. it can exist any where. 
We have two flags, for historic reasons:
1. skipDefaultLibCheck, only skips the checking of files that have `/// <reference no-default-lib="true"/>` in them. This flag is now deprecated, but we still honor it.
2. skipLibCheck, skips checking of all .d.ts files

File: src/server/session.ts (hunk 3 above)
Comment (billti) [inline src/server/session.ts]: Maybe a comment to that effect in this function then? It's confusing to have a function called `shouldSkipSemanticCheck` that takes a file, that doesn't actually check if it should skip the semantic check for that file 😕

File: src/server/session.ts (hunk 2 above)
Comment (billti) [inline src/server/session.ts]: OK. Again, maybe clarify in comments in the function then. It seems this only returns `true` for a narrow subset of files that may actually have semantic checking skipped eventually.

File: src/compiler/program.ts [hunk 4]
```diff
@@ -908,6 +908,13 @@ namespace ts {
 
         function getSemanticDiagnosticsForFileNoCache(sourceFile: SourceFile, cancellationToken: CancellationToken): Diagnostic[] {
             return runWithCancellationToken(() => {
+                // If skipLibCheck is enabled, skip reporting errors if file is a declaration file.
+                // If skipDefaultLibCheck is enabled, skip reporting errors if file contains a
+                // '/// <reference no-default-lib="true"/>' directive.
+                if (options.skipLibCheck && sourceFile.isDeclarationFile || options.skipDefaultLibCheck && sourceFile.hasNoDefaultLib) {
```
Comment (mhegazy) [inline src/compiler/program.ts]: yes, will get that fixed.

Comment (mhegazy) [inline src/compiler/program.ts]: I remember now why i did not do that, we call TypeChecker.getDiagnostics from the tests directly.
