### PR TITLE
Ensure that the comma is removed when all named imports are removed via moveToFile 

### LINKED ISSUE #31195: "Move to a new file" quick fix won't properly separate default and named imports and leaves dangling comma
- VSCode Version: 1.33.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Install the `debug` and `@types/debug` packages in a fresh typescript project.
2. Create a file with the following content:

```typescript
import debug, { Debugger } from "debug";

export const log = debug("app");
export const foo = (logger: Debugger = log) => 0;
```

3. Run the "Move to a new file" quick fix on the `foo` object.
4. You are left with a dangling comma in the first line:

```typescript
import debug, from "debug";

export const log = debug("app");
```

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by orta**
Fixes #31195

This one *feels* like I'm taking a shortcut, but it was definitely doing the right thing before. When I looked [in ast-explorer](https://astexplorer.net/#/gist/da52a3557b1ea5fc617f5514a6e7dd18/b137573b1f8a92a85ff3d6c49a4fea1937505e17) what `import defaultD, from "./has-exports";` looks, like the comma comes from a `NamedImports` with no elements inside a `ImportClause`- removing the comma completely removes the `NamedImports` node.

This AST change is actually happening in the current refactor as-is, however, deleting just that node doesn't include the comma (maybe the fix is instead to make the span for that node different?) but this will remove the comma either way. I don't believe there are ever cases where you need that comma.

### CODE REVIEW

File: src/services/refactors/moveToNewFile.ts [hunk 1]
```diff
@@ -351,6 +351,8 @@ namespace ts.refactor {
             if (namedBindings) {
                 if (namedBindingsUnused) {
                     changes.delete(sourceFile, namedBindings);
+                    // Also include the ", ":
+                    changes.replaceRangeWithText(sourceFile, { pos: namedBindings.pos - 1, end: namedBindings.pos }, "");
```
Comment (andrewbranch) [inline src/services/refactors/moveToNewFile.ts]: I would probably opt for

```ts
changes.replaceNode(
  sourceFile,
  importDecl.importClause,
  updateImportClause(importDecl.importClause, name, /*namedBindings*/ undefined));
```

(to replace both lines in this `if`)

Comment (andrewbranch) [reply src/services/refactors/moveToNewFile.ts]: I think the issue is that the comma token as a child of the ImportClause, and TextChanges only does the exact thing you tell it to do without being smart about the context it’s working in. As you discovered, deleting the named bindings node just removes the text from `pos` to `end`, which doesn’t include the comma. So really, it's the ImportClause that needs to change—it needs to drop its named bindings node _and_ its comma token. Replacing it with a new one will re-print its contents, which lets the emitter be smart about whether a comma is needed without requiring manual intervention.

Comment (orta) [reply src/services/refactors/moveToNewFile.ts]: Perfect, yep - moving up the AST makes a lot of sense. 

That change makes a lot of sense. Thanks 👯‍♂
