### PR TITLE
Fix crash on `addImportFromExportedSymbol` with default exported symbol

### LINKED ISSUE #52662: Assertion failure when class member snippet relies on default-exported type
```ts
// @filename: other.ts
export default class Other {}

// @filename: base.ts
import Other from "./other";

export class Base {
    foo(): Other {
        throw new Error("");
    }
}

// @filename: derived.ts
import { Base } from "./base";

export class Derived extends Base {
    /*$*/
}
```

Request completions with class member snippets and snippet completions enabled.

```
Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:156324:70)
    at /vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161889:63
    at Array.forEach (<anonymous>)
    at importSymbols (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161889:21)
    at createSignatureDeclarationFromSignature (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161567:25)
    at outputMethod (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161495:30)
    at Object.addNewNodeForMemberSymbol (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:161474:25)
    at getEntryForMemberCompletion (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135751:24)
    at createCompletionEntry (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135603:23)
    at getCompletionEntriesFromSymbols (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:136106:29)
    at completionInfoFromData (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135415:31)
    at Object.getCompletionsAtPosition (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:135275:36)
    at Object.getCompletionsAtPosition (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:169151:35)
    at IpcIOSession.Session.getCompletions (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:181300:64)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:179973:61)
    at /vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182034:96
    at IpcIOSession.Session.executeWithRequestId (/vscode/bin/linux-x64/some-id-insider/extensions/node_modules/typescript/lib/tsserver.js:182025:28)
```

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #52662.

The crash was happening because we were using a filename as the name of the default exported symbol when looking up its export info, and we couldn't find it in the export info map. We were using the filename as the name of the default exported symbol because we couldn't properly get its name from its declarations, so I fixed the logic of getting the symbol name for a default exported symbol.

### CODE REVIEW

File: src/compiler/utilitiesPublic.ts [hunk 1]
```diff
@@ -907,7 +907,8 @@ export function getNonAssignedNameOfDeclaration(declaration: Declaration | Expre
             return nameForNamelessJSDocTypedef(declaration as JSDocEnumTag);
         case SyntaxKind.ExportAssignment: {
             const { expression } = declaration as ExportAssignment;
-            return isIdentifier(expression) ? expression : undefined;
+            const skipExpression = skipOuterExpressions(expression);
+            return isIdentifier(skipExpression) ? skipExpression : undefined;
```
Comment (gabritto) [inline src/compiler/utilitiesPublic.ts:911]: I think this isn't a breaking change? We'll be able to get the name of a declaration in *more* cases than before.

File: src/compiler/utilitiesPublic.ts [hunk 2]
```diff
@@ -907,7 +907,8 @@ export function getNonAssignedNameOfDeclaration(declaration: Declaration | Expre
             return nameForNamelessJSDocTypedef(declaration as JSDocEnumTag);
         case SyntaxKind.ExportAssignment: {
             const { expression } = declaration as ExportAssignment;
-            return isIdentifier(expression) ? expression : undefined;
+            const skipExpression = skipOuterExpressions(expression);
```
Comment (DanielRosenwasser) [inline src/compiler/utilitiesPublic.ts:910]: Maybe

* `skippedExpression`
* `innerExpression`
* make `expression` a `let` variable and reassign
* use `const expression = skipOuterExpressions((declaration as ExportAssignment).expression);`

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by gabritto** [comment]
@typescript-bot user test tsserver
@typescript-bot test tsserver top100

File: src/compiler/utilitiesPublic.ts [hunk 3]
```diff
@@ -906,7 +906,7 @@ export function getNonAssignedNameOfDeclaration(declaration: Declaration | Expre
         case SyntaxKind.JSDocEnumTag:
             return nameForNamelessJSDocTypedef(declaration as JSDocEnumTag);
         case SyntaxKind.ExportAssignment: {
-            const { expression } = declaration as ExportAssignment;
+            const expression = skipOuterExpressions((declaration as ExportAssignment).expression);
```
Comment (gabritto) [inline src/compiler/utilitiesPublic.ts:909]: Apparently this change increases the bind time somewhat, because we use `getNameOfDeclaration` in the binder. I think I'll revert it then, but first I'm gonna try to figure out why that adjustment isn't needed in the binder's use cases.

Comment (jakebailey) [reply src/compiler/utilitiesPublic.ts:909]: There are so few changes in the benchmark that it could just be noise; I might try running it again (in faster mode) just to see.

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster
