### PR TITLE
Fix type parameters upon subsequent visits to a parameter that caused fixing the first time

### LINKED ISSUE #2378: Type parameters do not get fixed when the compiler visits the same signature multiple times
As of change #2356, the following code gives the correct result in the batch compiler:
```ts
declare function f<T>(x: T, y: (p: T) => T, z: (p: T) => T): T;
f(0, x => null, x => x.blahblah);
```
Namely, we infer T to be number, and we get an error on blahblah.

However, there are a few things still wrong:
* The language service does not show the correct result. It shows both x's to be number, but if you hover on f, you will see that it was instantiated to `any`, instead of `number`.
* If you add another overload, the wrong type argument gets inferred:
```ts
declare function f<T>(x: T, y: (p: T) => T, z: (p: T) => T): T;
declare function f();
f(0, x => null, x => x.blahblah);
```
Now suddenly blahblah is not an error, and the second x is `any`.
* In theory, if this overload is not assignable, but it has already fixed the type parameter T, and another overload comes along with a type parameter in the same position, that second type parameter will not get fixed. I don't have a good repro for this, but it is certainly a possibility in theory.

All of these issues happen because when a function expression parameter causes a type parameter to get fixed, it only does so if it is affected by the type of that type parameter. I believe the right thing here is that if a function parameter aligns with the type parameter, it should still fix it, even if it has already been assigned a type in the past. That way, it will fix the type parameter no matter which signature is being visited, or whether this signature has been visited before.

I consider this bug a followup to bugs #2127 and #2182.

### PR DESCRIPTION
**Pull request by JsonFreeman**
Fixes #2378.

The problem is that if a type parameter has already been given a type in the process of type argument inference, and caused type parameters to be fixed, we don't consistently fix the type parameters on a subsequent visit. See the bug for examples of how this can be observed.

The fix is that if a contextually typed parameter already has a type, we should still fix the type parameters that would have been fixed, had this been the first encounter of the given parameter.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9014,27 +9058,36 @@ namespace ts {
...
+                if (mightFixTypeParameters || !contextChecked) {
                     links.flags |= NodeCheckFlags.ContextChecked;
                     if (contextualSignature) {
                         let signature = getSignaturesOfType(type, SignatureKind.Call)[0];
-                        if (isContextSensitive(node)) {
+                        if (contextSensitive) {
                             assignContextualParameterTypes(signature, contextualSignature, contextualMapper || identityMapper);
                         }
-                        if (!node.type && !signature.resolvedReturnType) {
+                        if (mightFixTypeParameters || !node.type && !signature.resolvedReturnType) {
```
Comment (yuit) [inline src/compiler/checker.ts]: why you have to check ```mightFixTypeParameters``` again?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9014,27 +9058,36 @@ namespace ts {
...
+            // See the comment in assignTypeToParameterAndFixTypeParameters to understand why we need to
+            // check mightFixTypeParameters.
+            if (mightFixTypeParameters || !(links.flags & NodeCheckFlags.ContextChecked)) {
                 let contextualSignature = getContextualSignature(node);
                 // If a type check is started at a function expression that is an argument of a function call, obtaining the
                 // contextual type may recursively get back to here during overload resolution of the call. If so, we will have
                 // already assigned contextual types.
-                if (!(links.flags & NodeCheckFlags.ContextChecked)) {
+                let contextChecked = !!(links.flags & NodeCheckFlags.ContextChecked);
+                if (mightFixTypeParameters || !contextChecked) {
```
Comment (yuit) [inline src/compiler/checker.ts]: Same- Why you have to check ```mightFixTypeParameters``` again?

Comment (JsonFreeman) [inline src/compiler/checker.ts]: Because if I didn't check it, and we already checked this function expression, we would not go through this code path. We need to go through the code path in order to fix type parameters.

File: src/compiler/checker.ts (hunk 1 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Good question. In this case, I noticed that we are passing the contextualMapper into getReturnTypeFromBody. That indicates to me that we may fix some type parameters if the return expression contains a function expression. So I am ensuring that anywhere that it's possible to fix type parameters, we go through that code path.

**Comment by JsonFreeman** [comment]
@yuit any more feedback?

@DanielRosenwasser @ahejlsberg Do you have any feedback on this change?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6773,10 +6778,23 @@ namespace ts {
...
 
-        // Presence of a contextual type mapper indicates inferential typing, except the identityMapper object is
-        // used as a special marker for other purposes.
+        /**
+         * Detect if the mapper implies an inference context. Specifically, there are 4 possible values
+         * for a mapper. Let's go through each one of them:
+         *
+         *    1. undefined - this means we are not doing inferential typing, but we may do contextual typing,
+         *       which could cause us to assign a parameter type
+         *    2. identityMapper - means we want to avoid assigning a parameter type, whether or not we are in
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: a parameter a type

**Comment by DanielRosenwasser** [comment]
:+
