### PR TITLE
Fix merging of JS value & TS type decl

### LINKED ISSUE #38383: TypeError: Cannot read property 'kind' of undefined
**TypeScript Version:**  3.9.1-rc

**Search Terms:** typeerror kind

**Code**

Unknown

**Expected behavior:**

Compilation

**Actual behavior:**

```
TypeError: Cannot read property 'kind' of undefined
    at getErrorSpanForNode (.../node_modules/typescript/lib/typescript.js:13845:22)
    at createDiagnosticForNodeInSourceFile (.../node_modules/typescript/lib/typescript.js:13794:20)
    at Object.createDiagnosticForNode (.../node_modules/typescript/lib/typescript.js:13785:16)
    at .../node_modules/typescript/lib/typescript.js:41784:135
    at Map.forEach (<anonymous>)
    at getInitializerTypeFromAssignmentDeclaration (.../node_modules/typescript/lib/typescript.js:41766:52)
    at getWidenedTypeForAssignmentDeclaration (.../node_modules/typescript/lib/typescript.js:41660:123)
    at getTypeOfFuncClassEnumModuleWorker (.../node_modules/typescript/lib/typescript.js:42220:34)
    at getTypeOfFuncClassEnumModule (.../node_modules/typescript/lib/typescript.js:42199:51)
    at getTypeOfSymbol (.../node_modules/typescript/lib/typescript.js:42312:24)
```

**Playground Link:**

Unknown

**Related Issues:**

Unknown

### PR DESCRIPTION
**Pull request by elibarzilay**
Fixes #38383

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7870,7 +7870,7 @@ namespace ts {
                 (resolvedSymbol || symbol).exports!.forEach((s, name) => {
                     const exportedMember = members.get(name)!;
                     if (exportedMember && exportedMember !== s) {
-                        if (s.flags & SymbolFlags.Value) {
+                        if (s.flags & SymbolFlags.Value && exportedMember.flags & SymbolFlags.Value) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:7873]: @weswigham @sandersn when I was looking at this with Eli, this brought up a question as to why/how `exportedType` (defined a few lines above—the type of `require('./y.js')` in the test case) could have non-value members. In `resolveAnonymousTypeMembers`, it copies the exports of the symbol to the type, but of course, the `exports` of the .d.ts module includes a type symbol. It was surprising to me that `resolveStructuredTypeMembers` can return an anonymous object type that has members that are also types. Is that normal?

Comment (sandersn) [reply src/compiler/checker.ts:7873]: normal-ish -- it can easily happen when you merge a type-only namespace with an object literal:

```ts
var o = { x: 1 }
namespace o { export type y = number }
```

Comment (andrewbranch) [reply src/compiler/checker.ts:7873]: I realized I was confusing anonymous type _members_ with anonymous type _properties_, which are guaranteed to be values. With that confusion cleared up, this fix definitely looks correct. The possibility of type members was simply overlooked in the past.
