### PR TITLE
Don't crash on non-literal computed property names during getPropertyAssignment

### LINKED ISSUE #47989: TS Server fatal error:  Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.7.0-dev.20220219

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
Error: Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames
    at getTextOfPropertyName (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:14844:33)
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:15400:32
    at Array.filter (<anonymous>)
    at getPropertyAssignment (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:15398:41)
    at getTsConfigPropArray (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:15432:36)
    at Object.getTsConfigPropArrayElementValue (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:15423:32)
    at fileIncludeReasonToRelatedInformation (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:117131:41)
    at processReason (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:117071:58)
    at Array.forEach (<anonymous>)
    at createDiagnosticExplainingFile (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:117051:91)
    at addProgramDiagnosticExplainingFile (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:117088:36)
    at checkSourceFilesBelongToPath (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:116712:25)
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:115131:295
    at Object.getCommonSourceDirectory (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:108383:105)
    at getCommonSourceDirectory (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:115131:44)
    at verifyCompilerOptions (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:116946:27)
    at Object.createProgram (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:115043:9)
    at synchronizeHostData (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:161959:26)
    at Proxy.getProgram (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:162091:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:167138:53)
    at ConfiguredProject.Project.updateGraph (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:167067:42)
    at ConfiguredProject.updateGraph (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168102:63)
    at updateProjectIfDirty (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168591:45)
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:170922:33
    at callback (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168534:33)
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168517:186
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168549:30
    at Object.forEach (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:183:30)
    at forEachResolvedProjectReferenceProjectWorker (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168540:23)
    at forEachResolvedProjectReferenceProject (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:168517:34)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:170921:29)
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:171249:97
    at Object.flatMap (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:171249:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:172408:46)
    at /Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:174344:88
    at IpcIOSession.Session.executeWithRequestId (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:174335:28)
    at IpcIOSession.Session.executeCommand (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:174344:33)
    at IpcIOSession.Session.onMessage (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:174370:35)
    at process.<anonymous> (/Users/cleverboy/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220219/node_modules/typescript/lib/tsserver.js:177005:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:58.347Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.85GB free)|
|Process Argv|. --crash-reporter-id 5fd547a4-8095-4da3-b161-81501bd2f60f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mini-book|bao|0.0.13
vscode-styled-jsx|bla|2.1.1
simple-react-snippets|bur|1.2.6
gallery|byt|0.5.2
bytesec-vscode|byt|1.0.52
thief-book|C-T|0.0.9
thrift|cdu|0.0.1
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-css-modules|cli|0.4.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|11.7.0
tslint|eg2|1.0.47
vscode-highlight|fab|1.6.0
code-runner|for|0.11.7
anes|gam|0.0.2
lintlens|ghm|3.0.2
go|gol|0.31.1
format-modified|Gru|0.0.30
beautify|Hoo|1.5.0
juejin|luz|0.2.24
prettify-json|moh|0.0.3
vscode-docker|ms-|1.19.0
vscode-language-pack-zh-hans|MS-|1.64.7
python|ms-|2022.0.1814523869
vscode-pylance|ms-|2022.2.3
jupyter|ms-|2022.1.1301854968
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.217.4
vscode-typescript-next|ms-|4.7.20220219
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
vscode-jest|Ort|4.2.1
convert-css-in-js|pau|1.1.3
reader|ren|1.1.7
css-to-js|ris|0.2.1
vs-code-prettier-eslint|rve|3.1.0
stylelint|shi|0.51.0
code-spell-checker|str|2.1.7
sass-indented|syl|1.8.19
tabnine-vscode|Tab|3.5.25
vsprettier|tee|1.0.0
python|tht|0.2.3
react-redux-es6-snippets|tim|2.1.0
vscode-jsx-style-languageserver|upp|1.0.0
vscode-icons|vsc|11.10.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrt:30437039
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555:30436484
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

### PR DESCRIPTION
**Pull request by jakebailey**
`getPropertyAssignment` is searching for a property with a given text; when it encounters a bad property name, it crashes. Just skip over the bad property name, as it can't be equal to the key being searched for anyway.

This test is weird; the failure mode doesn't look like the bug in this particular harness (but it works).

```
Test failure:
fourslash-server test tsconfigComputedPropertyError.ts runs correctly
  [.................................................................]

  0 passing (2s)
  1 failing

  1) fourslash-server tests
       tests/cases/fourslash/server/tsconfigComputedPropertyError.ts
         fourslash-server test tsconfigComputedPropertyError.ts runs correctly:
     Error: Debug Failure. False expression: Malformed response: response sequence number did not match request sequence number.
```

Fixes #47989

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -987,7 +987,9 @@ namespace ts {
         return name.kind === SyntaxKind.ComputedPropertyName && !isStringOrNumericLiteralLike(name.expression);
     }
 
-    export function getTextOfPropertyName(name: PropertyName | NoSubstitutionTemplateLiteral): __String {
+    export function getTextOfPropertyName(name: PropertyName | NoSubstitutionTemplateLiteral): __String;
+    export function getTextOfPropertyName(name: PropertyName | NoSubstitutionTemplateLiteral, undefinedIfNotLiteral: boolean): __String | undefined;
+    export function getTextOfPropertyName(name: PropertyName | NoSubstitutionTemplateLiteral, undefinedIfNotLiteral?: boolean): __String | undefined {
```
Comment (andrewbranch) [inline src/compiler/utilities.ts:992]: Stylistic nit and maybe others disagree, but I think it’d be a bit cleaner to have `tryGetTextOfPropertName` which can always return `undefined` and `getTextOfPropertyName` which calls the former and asserts a result from it.

Comment (jakebailey) [reply src/compiler/utilities.ts:992]: That's not a bad idea, but I think if I do that, it'll end up not providing any info as to what part of the access went wrong, versus currently, it's asserting.

I'm not sure if it's a pattern to just try/catch/return undefined in this codebase, though, as that would be sort of the best of both worlds.

Comment (jakebailey) [reply src/compiler/utilities.ts:992]: Err, well, probably not the best, since you'd hit the assert when debugging.

**Comment by jakebailey** [comment]
With that change cherry-picked, I do get a reasonable error without the fix:

```
  1) fourslash-server tests
       tests/cases/fourslash/server/tsconfigComputedPropertyError.ts
         fourslash-server test tsconfigComputedPropertyError.ts runs correctly:
     Error Error processing request. Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames
Error: Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames
    at getTextOfPropertyName (E:\work\TypeScript\src\compiler\utilities.ts:1006:30)
    at E:\work\TypeScript\src\compiler\utilities.ts:1581:34
    at Array.filter (<anonymous>)
```

File: src/compiler/utilities.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/utilities.ts:992]: `getTextOfPropertyName` could preemptively check for non-literal computed properties and throw the same error, but I’m not sure there’s a ton of value in keeping the specific assertion. There’s currently no other way for it to fail and it should be pretty obvious what happened by the time one of us is checking out the source code.

Comment (jakebailey) [reply src/compiler/utilities.ts:992]: Fair enough, I'll do that.

Comment (andrewbranch) [reply src/compiler/utilities.ts:992]: It seems like we usually avoid try/catch when possible, probably due to lingering fears from old versions of v8 not being able to optimize functions containing try/catch.

**Review by andrewbranch — APPROVED** [review]
