### PR TITLE
Fixed find all references for private identifiers.

### LINKED ISSUE #35883: Find all references doesn't work with private fields
https://www.typescriptlang.org/play/index.html?ts=3.8.0-pr-30829-97&ssl=1&ssc=1&pln=6&pc=2#code/MYGwhgzhAEDC0G8BQ1XQMQDMD23oF5oBGABgG4U1hsA7CAFwCcBXYe7RgCgEpFK009ABYBLCADosuCgIC+SWUA

```ts
class C {
    [|#foo|] = 10;
    constructor() {
        this.[|#foo|] = 20;
    }
}
```

Expected: Find all references on each range contains all ranges.
Actual: Find all references returns no results.

### PR DESCRIPTION
**Pull request by dragomirtitian**
cc: @mheiber 
Fixes #35883

### CODE REVIEW

**Comment by mheiber** [comment]
Thanks so much for fixing this! I think it would be nice to have a fourslash test for this, similar to the go-to-definition tests.

**Comment by dragomirtitian** [comment]
@mheiber wops forgot to commit the file (fourslash tests is the way I tested it first 😊), fixed now. Also missed the `--light=false` flag 😒

**Comment by DanielRosenwasser** [comment]
Holy crap that was fast.

@typescript-bot pack this

**Comment by dragomirtitian** [comment]
@DanielRosenwasser  Fixed. Figuring out how to write the fourslash test.. 30 min.. figuring out the bug 10 min ... 😅

I fear there will be a lot more bugs relating to `identifier | private_identifier` in the codebase though. They are very easy to miss 😞

**Comment by mheiber** [comment]
@dragomirtitian , re

> I fear there will be a lot more bugs relating to identifier | private_identifier in the code-base though (not just find references). They are very easy to miss 😞.

I agree it's hard to catch all the cases where private identifiers need to be considered. If you have ideas for how to refactor so that the type system can help catch more of these cases, I'd be interested in trying the ideas out.

File: tests/cases/fourslash/findAllRefsPrivateProperties.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
+﻿/// <reference path='fourslash.ts'/>
```
Comment (mheiber) [inline tests/cases/fourslash/findAllRefsPrivateProperties.ts]: `privateProperties` to me seems ambiguous, given that we have `private` modifier and ES private fields (`#`).

Other ES private field tests have `privateName` in the name. I propose using `privateName` here for consistency, and perhaps a future PR to change the tests to `esPrivate` or `hashPrivate` or `privateIdentifier` or whatever works best.

**Comment by mheiber** [comment]
Re Daniel's comment:

> For some reason, find-all-refs at the end of the private name is failing.
> 
> ```ts
> class C {
>   #foo/*findAllRefs1*/: string;
> 
>   blah() {
>     this.#foo/*findAllRefs2*/;
>   }
> }
> ```

fwiw, I built the lang server from this PR locally and did some manual testing. I'm seeing public and private fields behave the same way when I right-click the end of a name in VS Code. Building on Daniel's example:

```ts
export default 3;

class C {
  #foo: string;
  bar: number;

  blah() {
    this.#foo/*loc1*/;
    this.bar/*loc2*/;
  }
}
```

- Right-clicking the final `o` in `#foo` and selecting `FindAllReferences` causes the references to show up.
- Right-clicking the `r` in `bar` and selecting `FindAllReferences` causes the references to show up

**Comment by dragomirtitian** [comment]
@mheiber Your last comment is not clear to me. Is there something that does not work in the current PR? Daniel reported the bug previously, but I since fixed it (I amended the original commit so you can't really see the fix separately, it was caused my a missing `|| privateIdentifier` in `getTouchingPropertyName`)

File: tests/cases/fourslash/findAllRefsPrivateProperties.ts (hunk 1 above)
Comment (dragomirtitian) [reply tests/cases/fourslash/findAllRefsPrivateProperties.ts]: Was not aware of the convention. Renamed the test file.

**Comment by dragomirtitian** [comment]
I am unsure why the tests CI/build fails for node12. I tried running `gulp runtests-parallel --light=false`  locally with node 12.6 and it succeeded without any issues.

**Comment by mheiber** [comment]
3 failing tests due to timeouts. Seems spurious to me, fwiw:

```
         fourslash-server tests
           tests/cases/fourslash/server/ngProxy2.ts
             fourslash-server test ngProxy2.ts runs correctly:
     Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at processImmediate (internal/timers.js:439:21)
```

What about retrying until it succeeds 😈 ?

File: src/services/findAllReferences.ts [hunk 2]
```diff
@@ -1231,6 +1237,8 @@ namespace ts.FindAllReferences {
         function isValidReferencePosition(node: Node, searchSymbolName: string): boolean {
             // Compare the length so we filter out strict superstrings of the symbol we are looking for
             switch (node.kind) {
+                case SyntaxKind.PrivateIdentifier:
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts]: I think this could be 
```
case SyntaxKind.PrivateIdentifier:
case SyntaxKind.Identifier:
      return (node as Identifier | PrivateIdentifier).text.length === searchSymbolName.length;
```

File: src/services/findAllReferences.ts [hunk 3]
```diff
@@ -920,12 +920,18 @@ namespace ts.FindAllReferences {
 
             /** @param allSearchSymbols set of additional symbols for use by `includes`. */
             createSearch(location: Node | undefined, symbol: Symbol, comingFrom: ImportExport | undefined, searchOptions: { text?: string, allSearchSymbols?: Symbol[] } = {}): Search {
+                // Symbols for private identifiers have a compound escaped name that includes the class symbol id
+                // This means that we need to take the original name of the symbol and search for it instead of the escaped name
+                function getSymbolName(s: Symbol) {
```
Comment (sheetalkamat) [inline src/services/findAllReferences.ts]: I think this needs to be in utitilities and called `getEscapedNameIOfSymbol` instead to make sure we don't confused with `symbol.name`

Comment (dragomirtitian) [reply src/services/findAllReferences.ts]: @sheetalkamat I checked again and found a utility called `symbolName` which does something similar, I will use that instead.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
Just as a heads up, I think you implemented the test correctly. In the future, I believe there are other helpers to make sure that all ranges in the test provide the same results to find-all-references.
