### PR TITLE
Change logic in identifying JSX React SFCs

### LINKED ISSUE #6349: TSX props of type `any` do not work for stateless components
Not that I want to do that. But just for creating a quick demo I did that and it fails to compile: 

```ts
const Foo = (props:any) => <div/>;
const foo = <Foo/>; // Error : render is missing
```

Of master from yesterday :rose:

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Our logic for detecting SFC vs Element Class had a few issues:
 * Object Type flag is not actually useful
 * Parameter arity isn't actually relevant
 * The check for Element Class should take priority

Fixes #6349 and #6353

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8248,27 +8248,31 @@ namespace ts {
...
+                        const callSignature = callSignatures && callSignatures.length > 0 && callSignatures[0];
+                        const callReturnType = callSignature && getReturnTypeOfSignature(callSignature);
+                        let paramType = callReturnType && (callSignature.parameters.length === 0 ? emptyObjectType : getTypeOfSymbol(callSignature.parameters[0]));
+                        if (callReturnType && isTypeAssignableTo(callReturnType, jsxElementType)) {
+                            // Intersect in JSX.IntrinsicAttributes if it exists
+                            const intrinsicAttributes = getJsxType(JsxNames.IntrinsicAttributes);
+                            if (intrinsicAttributes !== unknownType) {
+                                paramType = intersectTypes(intrinsicAttributes, paramType);
+                            }
+                            return paramType;
```
Comment (sandersn) [inline src/compiler/checker.ts]: all the other branches are assigning to `links.resolvedJsxType` on the way out. I think it should be:

```ts
return links.resolvedJsxType = paramType;
```

**Comment by RyanCavanaugh** [comment]
Bueller?

**Comment by sandersn** [comment]
Looks good as far as I understand JSX.
