### PR TITLE
fix autoimports crash: generate namespace and other module symbol imports 

### LINKED ISSUE #58740: Debug failure on paste with imports
### 🔎 Search Terms

- paste with imports

### 🕗 Version & Regression Information

5.5.0-dev.20240602

### ⏯ Playground Link

_No response_

### 💻 Code

Don't have a minimal repo yet but hitting this pretty consistently:

1. In https://github.com/microsoft/vscode-markdown-languageservice with VS Code
2. `"typescript.experimental.updateImportsOnPaste": true` with latest nightly TS
3. Copy the constructor here https://github.com/microsoft/vscode-markdown-languageservice/blob/7156aba6bdffef89b9210def0e0dda785569d1ab/src/languageFeatures/folding.ts#L26C1-L34C3
4. Paste it into a new file

### 🙁 Actual behavior

```
copyPasteController.ts:510 Error: <semantic> TypeScript Server Error (5.5.0-dev.20240602)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:154212:32)
    at /Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:144257:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:144251:17)
    at /Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:178190:7
    at ConfiguredProject2.runWithTemporaryFileUpdate (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:183844:5)
    at pasteEdits (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:178172:55)
    at /Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:178158:118
    at _ChangeTracker.with (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:174292:5)
    at Object.pasteEditsProvider (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:178158:60)
    at Object.getPasteEdits (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:149221:34)
    at IpcIOSession.getPasteEdits (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:191112:49)
    at getPasteEdits (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:189302:43)
    at /Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:191478:69
    at IpcIOSession.executeWithRequestId (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:191470:14)
    at IpcIOSession.executeCommand (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:191478:29)
    at IpcIOSession.onMessage (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/typescript.js:191520:51)
    at process.<anonymous> (/Users/matb/projects/vscode-markdown-languageservice/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:473136)
    at v.dispatchResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:467106)
    at v.dispatchMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:465950)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:465443)
    at ChildProcess.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
```

[tsserver.log](https://github.com/user-attachments/files/15527484/tsserver.log)

### 🙂 Expected behavior

No crash

### Additional information about the issue

_No response_

### LINKED ISSUE #59284: TS error moving a function to another file
1. Try to move [this function](https://github.com/microsoft/vscode-js-debug/blob/1d104b5184736677ab5cc280c70bbd227403850c/src/targets/node/subprocessProgramLauncher.ts) to [this file](https://github.com/microsoft/vscode-js-debug/blob/1d104b5184736677ab5cc280c70bbd227403850c/src/common/processUtils.ts)
2. Get a TS error notification containing

```
<semantic> TypeScript Server Error (5.5.2) Debug Failure. Error: Debug Failure. at Object.addImportFromExportedSymbol (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:154158:32) at c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:144203:19 at Map.forEach (<anonymous>) at addTargetFileImports (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:144197:17) at getNewStatementsAndRemoveFromOldFile (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:143427:3) at doChange3 (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:143411:3) at c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:143396:79 at _ChangeTracker.with (c:\Users\conno\Github\vscode-js-debug\node_modules\typescript\lib\typescript.js:174213:5) at Object.getRefactorEditsToMoveToFile [as getEditsForAction] (c:\Users\co...
```

TS Server Log https://gist.github.com/connor4312/080949221003eaed849afa685d48c0ae

### LINKED ISSUE #59650: Refactor: move to new file does not work
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: Version: 1.92.1 (Universal)
- OS Version: MacOS Sonoma 14.5 / Apple M1 Pro

Steps to Reproduce:

1. Refactor > move to new file

What I tried already:
1. Run with `--disable-extensions` to ensure it's not a problem with a package.
2. `typescript.tsserver.enableTrace`
3. find minimal examples
4. search for similar issues: https://github.com/microsoft/vscode/issues/51586, https://github.com/microsoft/vscode/issues/58711

It worked a few versions before. I don't know exactly what version was okay.

UPD: not working:
```ts
import { useLatest } from 'react-use';

export function useUseLatest (data: string) {
    return useLatest(data);
}
```

not working:
```ts
import { selectStore, useSelector } from '@proterm/core';

export function useOrders() {
    return useSelector(selectStore);
}
```

not working:
```ts
import { selectStore } from '@proterm/core';

export function useOrders() {
    return selectStore;
}
```

working:
```ts
import { AnyBaseOrder } from '@terminal/scalp/types';

export function useOrders(symbolId: string): AnyBaseOrder[] {}
```

working:
```ts
import { useSelector } from 'react-redux';

function useOrders() {
    return useSelector((state) => console.log(state));
}
```

working:
```ts
import { selectStore, useSelector } from '@proterm/core';
export function useOrders(symbolId: string): AnyBaseOrder[] {}
```

I though @ import aliases is a problem, however this works too:
```ts
import { FancyAlertCircleIcon } from '@terminal/icons';

export function useOrders() {
    return FancyAlertCircleIcon;
}
```

error:
```
2024-08-15 18:42:15.101 [error] <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.5.4)
```

### LINKED ISSUE #59651: typescript `Move to a new file` doesn't work when namespace import react
@mjbvz @justschen 

reproduce repo: https://github.com/tjx666/ts-move-to-new-file

## screen recoding

https://github.com/user-attachments/assets/fc2760b3-7674-4613-895b-52f2a899a69d

## versions

I use the empty profile

```json
{
	{
		"dependencies": {
	    "react": "^18.3.1",
	    "typescript": "^5.5.4"
	},
	"devDependencies": {
	    "@types/react": "^18.3.3"
	}
}
```

```node
Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

## devtools log

<details>
<summary>Details</summary>

```node
  ERR <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:154243:32)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:143512:3)
    at doChange4 (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144488:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:77
    at _ChangeTracker.with (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:144477:60)
    at Object.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:189305:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
	at n.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:474960)
	at v.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:468930)
	at v.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:467728)
	at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:467221)
	at ChildProcess.emit (node:events:519:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

</details>

### LINKED ISSUE #59701: Assertion failure when move-to-file code contains entities from ambient module
```ts
// @filename: src/globals.ts
declare module "ambient" {
    export interface Thing {}
}
```

```ts
// @filename: src/yadda.ts
import type * as ambient from "ambient";

export class Yadda {
  foo(): ambient.Thing {
    throw new Error("not implemented");
  }

  bar(): ambient.DoesNotExist {
    throw new Error("not implemented");
  }
}
```

```json5
// @filename: src/tsconfig.json
{
    "compilerOptions": {
        "moduleResolution": "bundler",
        "target": "esnext",
        "strict": true,
        "outDir": "dist"
    },
    "include": [
        "src"
    ]
}
```

Move to a new file on `Yadda`, and the following assertion error is issued from TSServer

```
Response received: getEditsForRefactor (729). Request took 2 ms. Success: false . Message: Error processing request. Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (node_modules/typescript/lib/typescript.js:154243:32)
    at node_modules/typescript/lib/typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (node_modules/typescript/lib/typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (node_modules/typescript/lib/typescript.js:143512:3)
    at doChange3 (node_modules/typescript/lib/typescript.js:143496:3)
    at node_modules/typescript/lib/typescript.js:143481:79
    at _ChangeTracker.with (node_modules/typescript/lib/typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToFile [as getEditsForAction] (node_modules/typescript/lib/typescript.js:143481:62)
    at Object.getEditsForRefactor (node_modules/typescript/lib/typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (node_modules/typescript/lib/typescript.js:149939:32)
    at IpcIOSession.getEditsForRefactor (node_modules/typescript/lib/typescript.js:191087:49)
    at getEditsForRefactor (node_modules/typescript/lib/typescript.js:189305:43)
    at node_modules/typescript/lib/typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (node_modules/typescript/lib/typescript.js:191483:14)
    at IpcIOSession.executeCommand (node_modules/typescript/lib/typescript.js:191491:29)
    at IpcIOSession.onMessage (node_modules/typescript/lib/typescript.js:191533:51)
    at process.<anonymous> (node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### LINKED ISSUE #59747: Cannot Move React Class Component To New File
### 🔎 Search Terms

After invoking the code action "Move To A New File" on a react class component, this error is printed to the dev console:

```
semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:154243:32)
    at c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:143512:3)
    at doChange4 (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144488:3)
    at c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144477:77
    at _ChangeTracker.with (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144477:60)
    at Object.getEditsForRefactor (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:149939:32)
    at decorator.<computed> [as getEditsForRefactor] (c:\Users\hdieterichs\.vscode-insiders\extensions\p42ai.refactor-3.0.1\node_modules\@p42\hide-typescript-refactors\build\index.js:28:36)
    at IpcIOSession.getEditsForRefactor (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191087:49)
    at getEditsForRefactor (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:189305:43)
    at c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191483:14)
    at IpcIOSession.executeCommand (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191491:29)
    at IpcIOSession.onMessage (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191533:51)
    at process.<anonymous> (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21): Error: <semantic> TypeScript Server Error (5.5.4)
Debug Failure.
Error: Debug Failure.
    at Object.addImportFromExportedSymbol (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:154243:32)
    at c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144288:19
    at Map.forEach (<anonymous>)
    at addTargetFileImports (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144282:17)
    at getNewStatementsAndRemoveFromOldFile (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:143512:3)
    at doChange4 (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144488:3)
    at c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144477:77
    at _ChangeTracker.with (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:174306:5)
    at Object.getRefactorEditsToMoveToNewFile [as getEditsForAction] (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:144477:60)
    at Object.getEditsForRefactor (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:142603:31)
    at Object.getEditsForRefactor2 [as getEditsForRefactor] (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:149939:32)
    at decorator.<computed> [as getEditsForRefactor] (c:\Users\hdieterichs\.vscode-insiders\extensions\p42ai.refactor-3.0.1\node_modules\@p42\hide-typescript-refactors\build\index.js:28:36)
    at IpcIOSession.getEditsForRefactor (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191087:49)
    at getEditsForRefactor (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:189305:43)
    at c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191491:69
    at IpcIOSession.executeWithRequestId (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191483:14)
    at IpcIOSession.executeCommand (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191491:29)
    at IpcIOSession.onMessage (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\typescript.js:191533:51)
    at process.<anonymous> (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:523:14)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Function.create (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:473974)
    at v.dispatchResponse (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:467944)
    at v.dispatchMessage (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:466742)
    at ChildProcess.<anonymous> (c:\Users\hdieterichs\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:466235)
    at ChildProcess.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

```json
{
	"compilerOptions": {
		"module": "ESNext",
		"target": "ESNext",
		"moduleResolution": "Bundler",
		"jsx": "react",
		"useDefineForClassFields": false,
		"experimentalDecorators": true,
		"strictNullChecks": true,
		"strictFunctionTypes": true,
		"exactOptionalPropertyTypes": false,
		"useUnknownInCatchVariables": false,
		"strict": true,
		"sourceMap": true,
		"noEmit": true,
		"skipLibCheck": true
	},
	"include": [
		"./src/**/*",
		"./node_modules/@types/wicg-web-app-launch/index.d.ts"
	]
}
```

### 🕗 Version & Regression Information

- This changed between versions 5.3 and 5.5.4 (VS Code's latest version)

Probably reproducible in newer and older versions within that range.

### ⏯ Playground Link

_No response_

### 💻 Code

```ts
import React from "react";

class MyComponent extends React.Component { // Call "Move to new file" here
    render() {
        return <div />;
    }
}
```

### 🙁 Actual behavior

The refactoring does not do anything.

### 🙂 Expected behavior

The refactoring should work.

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by iisaduan**
`MoveToFile`, `MoveToNewFile`, `PasteEdits`, and related refactors would crash due to autoimports being unable to resolve where module symbols should be imported from. 

This PR adds an `importAdder` function that will generate module imports based off an existing import. The existing import is used as a reference to determine what type of import is generated.

Fixes #58740
Fixes https://github.com/microsoft/TypeScript/issues/59240#issuecomment-2224079385 (unfortunately original js case still crashes)
Fixes #59284
Fixes #59650
Fixes #59651
Fixes #59701
Fixes #59747

#58897 stops crashing, but the resolution isn't quite correct

Closes #59004
Closes #59447
Closes #60302

### CODE REVIEW

File: src/services/refactors/helpers.ts [hunk 1]
```diff
@@ -80,6 +80,10 @@ export function addTargetFileImports(
         if (checker.isUnknownSymbol(targetSymbol)) {
             importAdder.addVerbatimImport(Debug.checkDefined(declaration ?? findAncestor(symbol.declarations?.[0], isAnyImportOrRequireStatement)));
         }
+        else if (targetSymbol.parent === undefined) {
+            Debug.assert(declaration !== undefined, "expected module symbol to have a declaration");
+            importAdder.addImportForModuleSymbol(symbol, isValidTypeOnlyUseSite, declaration);
+        }
```
Comment (navya9singh) [inline src/services/refactors/helpers.ts:86]: Is there a reason why we can't use `isExternalModuleSymbol()` as a check?

File: tests/cases/fourslash/server/pasteEdits_namespaceImport.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+//// const def = 20;
+//// export interface testInterface {
+////     abc: number;
+////     def: number;
+//// }
+
+// @Filename: /home/src/workspaces/project/b.ts
+//// import * as test from "./a";
+////
+//// [|function foo(abc: test.testInterface, def: test.testInterface) {
```
Comment (navya9singh) [inline tests/cases/fourslash/server/pasteEdits_namespaceImport.ts:18]:
```suggestion
//// [|function foo(abc: test.abc, def: test.def) {
```
to match the `pastesText` arguments

File: src/services/refactors/helpers.ts (hunk 1 above)
Comment (iisaduan) [reply src/services/refactors/helpers.ts:86]: Do you mean in the if statement or the debug statement? The debug is needed since the intent of the importAdder function is to copy from an existing declaration

Comment (iisaduan) [reply src/services/refactors/helpers.ts:86]: For the if statement, namespaces are specifically _not_ external module symbols, so `isExternalModuleSymbol` wouldn't work if trying to export something that was defined as a namespace (`React` for example)

File: src/services/codefixes/importFixes.ts [hunk 3]
```diff
@@ -1451,6 +1523,8 @@ export function getImportKind(importingFile: SourceFile | FutureSourceFile, expo
             return getExportEqualsImportKind(importingFile, program.getCompilerOptions(), !!forceImportKeyword);
         case ExportKind.UMD:
             return getUmdImportKind(importingFile, program, !!forceImportKeyword);
+        case ExportKind.Module:
+            return ImportKind.Namespace;
```
Comment (andrewbranch) [inline src/services/codefixes/importFixes.ts:1527]: I was concerned that there are times this should return `ImportKind.CommonJS`, but I think the critical cases are already covered by the condition at the top of this function. It’s probably fine.

**Review by andrewbranch — APPROVED** [review]

File: src/services/codefixes/importFixes.ts (hunk 3 above)
Comment (iisaduan) [reply src/services/codefixes/importFixes.ts:1527]: I think cases that should return `ImportKind.CommonJs` still crash. https://github.com/microsoft/TypeScript/pull/60333#issue-2610065620
> Fixes https://github.com/microsoft/TypeScript/issues/59240#issuecomment-2224079385 (unfortunately original js case still crashes)
