### PR TITLE
Fix newline issues when adding multiple imports

### LINKED ISSUE #38082: "Add all missing imports" adds them all in one line
**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
- fix all
- code action
- quick fix

**Code**
With `@types/node` installed, open a file:

```ts
join();
homedir()
```

1. Now trigger quick fixes and select `add all missing imports`

**Bug:**
The two imports are added on the same line:

```js
import { join } from "path";import { homedir } from "os";

join();
homedir()
```

Here's the edit that TS Server returns in this case

```
[Trace  - 23:52:04.985] <semantic> Response received: getCombinedCodeFix (72). Request took 13 ms. Success: true 
Result: {
    "changes": [
        {
            "fileName": "/Users/matb/projects/san/test.ts",
            "textChanges": [
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 1
                    },
                    "newText": "import { join } from \"path\";"
                },
                {
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 1
                    },
                    "newText": "import { homedir } from \"os\";\n"
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by andrewbranch**
The logic in `TextChanges` for determining whether statements added to the top of a file need newlines before and after doesn’t really work when there are already other pending insertions at the top of the file. Instead of calling `insertNodeAtTopOfFile` for each import added, just call it once with an array of all the imports to be added.

Fixes #38082

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -717,13 +720,13 @@ namespace ts.codefix {
             readonly name: string;
         };
     }
-    function addNewImports(changes: textChanges.ChangeTracker, sourceFile: SourceFile, moduleSpecifier: string, quotePreference: QuotePreference, imports: ImportsCollection, blankLineBetween: boolean): void {
+    function getNewImports(moduleSpecifier: string, quotePreference: QuotePreference, imports: ImportsCollection): Statement[] {
         const quotedModuleSpecifier = makeStringLiteral(moduleSpecifier, quotePreference);
+        const statements = [];
```
Comment (sheetalkamat) [inline src/services/codefixes/importFixes.ts:725]: if its rare to add multiple imports for same specifier, would it be better to return Statement | Statement[] instead so as to avoid having to allocate arrays for each module specifier if its not common?

File: src/services/textChanges.ts [hunk 2]
```diff
@@ -348,12 +348,18 @@ namespace ts.textChanges {
             this.replaceRangeWithNodes(sourceFile, createRange(pos), newNodes, options);
         }
 
-        public insertNodeAtTopOfFile(sourceFile: SourceFile, newNode: Statement, blankLineBetween: boolean): void {
+        public insertNodesAtTopOfFile(sourceFile: SourceFile, newNodes: Statement | readonly Node[], blankLineBetween: boolean): void {
```
Comment (amcasey) [inline src/services/textChanges.ts:351]: I'm not sure I understand why it's `Statement | Node[]` and not `Statement | Statement[]` or `Node | Node[]`.

Comment (amcasey) [reply src/services/textChanges.ts:351]: It looks like the other helpers use two separate functions, e.g. `insertNodeAfter` and `insertNodesAfter`.  Of course there's no reason both of those can't delegate to a shared impl.

File: src/services/codefixes/importFixes.ts (hunk 1 above)
Comment (amcasey) [reply src/services/codefixes/importFixes.ts:725]: I also find it confusing that the parameters accommodate this pattern but the arguments do not.

Comment (amcasey) [reply src/services/codefixes/importFixes.ts:725]: I think I've mentioned this before, but I'm kind of surprised that we don't have a type and a collection of helper functions for manipulating `T | T[]`.

File: src/compiler/core.ts [hunk 3]
```diff
@@ -844,6 +844,28 @@ namespace ts {
...
+     * T -> undefined -> T
+     * T -> T -> T[]
+     * T[] -> undefined -> T[] (no-op)
+     * T[] -> T -> T[]         (append)
+     * T[] -> T[] -> T[]       (concatenate)
+     * ```
+     */
+    export function combine<T>(xs: T | readonly T[] | undefined, ys: T | readonly T[] | undefined): T | readonly T[] | undefined;
+    export function combine<T>(xs: T | T[] | undefined, ys: T | T[] | undefined): T | T[] | undefined;
+    export function combine<T>(xs: T | T[] | undefined, ys: T | T[] | undefined) {
```
Comment (andrewbranch) [inline src/compiler/core.ts:861]: I’ll give everyone until EOD to bikeshed this horribly vague name.
