### PR TITLE
Check module.exports

### LINKED ISSUE #25533: `const x = require("m")` should create an alias symbol
**TypeScript Version:**  3.0.0-dev.20180707

**Code**

```ts
/// <reference path='fourslash.ts'/>

// @allowJs: true

// @Filename: /a.js
////function [|{| "isWriteAccess": true, "isDefinition": true |}x|]() {};
////module.exports = [|x|];

// @Filename: /b.js
////const [|x|] = require("./a");
////[|x|];

const [r0, r1, r2, r3] = test.ranges();
verify.referenceGroups(r2, [/*todo*/]);
```

**Expected behavior:**

`x` in `const x` is an alias of the `x` in `function x() {}`, so all references are found.

**Actual behavior:**

`x` is a variable that happens to be the same type as the other `x`. Only references in `b.js` are found.

### LINKED ISSUE #25621: `module.exports.property` results in a property of type any
```js
module.exports.y = "hi"
let u = module.exports.y/**/
```

Get quick info at position.

**Expected behavior:**

The type of `module.exports.y` is reported as string.

**Actual behavior:**

The type of `module.exports.y` is reported as any, and there aren't any completions, so it seems like it actually is any.

Edit:
1. Repros on 2.9.2 and master.
2. When imported, the type is correct

```js
var { y } = require('./mod')
y/**/
```

The declared type is used if there is one, even if it contradicts the initialiser (eg `/** @type {number} */ module.exports.y = 'hi'`).

### LINKED ISSUE #25687: In JS, aliasing `exports = {}` omits the expected string index signature
From adonis-framework in the user tests.

```js
// Filename: util.js
const util = exports = module.exports = {}
util.existy = function() { }
```

**Expected behavior:**

No error, and `import('util')` has a property `existy`. (Ideally `util` would also have a property `existy` inside util.js, but this is not true in 2.9.2 either.)

**Actual behavior:**

Error: Property 'x' does not exist on type '{}', but `require('util')` **does** have a property `existy: () => void`.

### PR DESCRIPTION
**Pull request by sandersn**
Create a unique symbol and type for `module` in each commonjs file. Previously, all references to `module` used the same symbol, which had type any. Now `module` has type `{ exports: typeof import("current-file") }`. This module symbol is no longer identified by identity but by CheckFlags.ModuleExports.

A few notes:

1. I'm not sure that getSourceFileOfNode is the best way to get the symbol of the source file.
2. `module` has a fresh anonymous type for each file. This may have to change in order to fix #25533, although the outline of the solution will remain the same.
3. module.exports assignment is now unconditionally a Special Property Assignment for the purposes of checking. That means assignments to module.exports (1) will not have assignability errors (2) return the type of module.exports, not its initializer. This should work fine because *references* to module.exports now refer to the source file's type.
4. In order to make control flow right for merged aliases, getExportSymbolOfValueSymbolIfExported needs to unconditionally get the merged symbol of its return. Previously it only merged `symbol.exportSymbol`.
5. Constructs like `exports.default = { blah: 1 }; module.exports = exports['default']` mean that `getTypeOfFuncClassEnumModule` now needs to use push/popTypeResolution to prevent infinite loops.

Fixes #25687 
Fixes #25621

### CODE REVIEW

**Comment by sandersn** [comment]
Looks like the build found some lint. I'll fix it in my next commit.

**Comment by sandersn** [comment]
Notes from user tests:

## Good

1. adonis-framework: Aliases of module.exports are now typed, so we find that Helpers._makePath should have its third parameter optional, but is not annotated as such in its jsdoc, and that Route.route should have it second parameter `verb: string | string[]` not just `string`.
2. assert: property assignments to an alias declaration (`var assert = module.exports = ok`) are now recognised. The type of `this` in those property assignments is still not right, but hasn't gotten worse at least.
3. npmlog: Same as assert, but the difference is much more dramatic. Also strict null checks catches a rogue undefined.

4. chrome-devtools-frontend: (1) includes a copy of assert (2) now has a contextual type for some assignments that sets `this: any`. This removes some errors! TODO: Finish later.

## Bad

1. axios: Assignment to the default property (ironically commented as "Support typescript") has an incorrect "variable 'axios' is used before being assigned error"

```js
var axios = {}
module.exports = axios // ok
module.exports.default = axios // should be ok, currently an error
```

2. npm: Alias of module.exports isn't callable in 3 different places. (Probably related to #25533).

```js
var npm = module.exports = function (tree) {
}
module.exports.asReadInstalled = function (tree) {
    npm(tree) // should be callable, but isn't
}
```

3. npmlog: The alias of module.exports is missing the properties from its initialiser.

```js
var EE = require('events').EventEmitter
var log = exports = module.exports = new EE()
log.on('error', function() { })
```

## Ugly

1. create-react-app: No more "can't find module 'browserslist'." I have no idea why.
2. graceful-fs: Duplicate assignability error trying to overwrite `fs.close`. Maybe because of the special handling in checkBinaryLikeExpression? But this should have *fewer* assignability checks.

**Comment by sandersn** [comment]
I fixed all the user test failures. The only incorrect change is to npm, which uses the same pattern as npmlog, but wrapped in an IIFE. Because the exports assignments aren't at top-level they aren't recognised. Now the error message is wrong as well &mdash it says `typeof EventEmitter` instead of `EventEmitter`. However, I don't think it's worth the additional effort to fix until we also make this pattern work inside an IIFE.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1412,6 +1411,14 @@ namespace ts {
                         return lastLocation.symbol;
                     }
                 }
+                if (originalLocation && isInJavaScriptFile(originalLocation) && originalLocation.parent) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: There are 7 conditions here -- why put 3 in one `if` and 4 in another?

Comment (andy-ms) [reply src/compiler/checker.ts]: Also, no need to test `&& originalLocation.parent` if we know it's an `Identifier`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -1412,6 +1411,14 @@ namespace ts {
                         return lastLocation.symbol;
                     }
                 }
+                if (originalLocation && isInJavaScriptFile(originalLocation) && originalLocation.parent) {
+                    if (isIdentifier(originalLocation) && isPropertyAccessExpression(originalLocation.parent) &&
+                        originalLocation.escapedText === "module" && originalLocation.parent.name.escapedText === "exports") {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: `isModuleExportsPropertyAccessExpression` does something similar to this.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -1412,6 +1411,14 @@ namespace ts {
                         return lastLocation.symbol;
                     }
                 }
+                if (originalLocation && isInJavaScriptFile(originalLocation) && originalLocation.parent) {
+                    if (isIdentifier(originalLocation) && isPropertyAccessExpression(originalLocation.parent) &&
+                        originalLocation.escapedText === "module" && originalLocation.parent.name.escapedText === "exports") {
+                        const moduleSymbol = createSymbol(SymbolFlags.FunctionScopedVariable, "module" as __String, CheckFlags.ModuleExports);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: I think the creation should be cached somewhere, since we base several other caches on the symbol. If we create 100 different symbols, we'll also create a new type for each of those symbols.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -4710,7 +4711,7 @@ namespace ts {
             return undefined;
         }
 
-        function getWidenedTypeFromJSSpecialPropertyDeclarations(symbol: Symbol) {
+        function getWidenedTypeFromJSSpecialPropertyDeclarations(symbol: Symbol, aliased: Symbol) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: This function's getting pretty big (over 120 lines), any way you could break it down in a future PR?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -4766,15 +4767,19 @@ namespace ts {
                 }
                 else if (!jsDocType && isBinaryExpression(expression)) {
                     // If we don't have an explicit JSDoc type, get the type from the expression.
-                    let type = getWidenedLiteralType(checkExpressionCached(expression.right));
+                    const isModuleExportsAlias = aliased !== symbol;
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Might be neater to make `aliased` optional.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -4766,15 +4767,19 @@ namespace ts {
...
                         symbol.escapedName === InternalSymbolName.ExportEquals) {
-                        const exportedType = resolveStructuredTypeMembers(type as AnonymousType);
+                        const exportedType = resolveStructuredTypeMembers(type as ObjectType);
                         const members = createSymbolTable();
                         copyEntries(exportedType.members, members);
-                        symbol.exports!.forEach((s, name) => {
+                        if (!aliased.exports) {
+                            aliased.exports = createSymbolTable();
+                        }
+                        (isModuleExportsAlias ? aliased : symbol).exports!.forEach((s, name) => {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: If `!isModuleExportsAlias`, `symbol` the same as `aliased`. So this should always equal `aliased`.
Tested with `Debug.assert((isModuleExportsAlias ? aliased : symbol) === aliased);`.

File: tests/baselines/reference/moduleExportAlias5.types [hunk 7]
```diff
@@ -5,18 +5,18 @@ const webpack = function (){
...
+>module.exports : { (): void; WebpackOptionsDefaulter: number; version: number; }
+>module : { "tests/cases/conformance/salsa/bug24754": { (): void; WebpackOptionsDefaulter: number; version: number; }; }
+>exports : { (): void; WebpackOptionsDefaulter: number; version: number; }
 >webpack : { (): void; WebpackOptionsDefaulter: number; }
 
 exports.version = 1001;
 >exports.version = 1001 : 1001
 >exports.version : number
->exports : typeof import("tests/cases/conformance/salsa/bug24754")
+>exports : { (): void; WebpackOptionsDefaulter: number; version: number; }
```
Comment (andy-ms) [inline tests/baselines/reference/moduleExportAlias5.types]: Seems like this was better before?

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -5217,16 +5228,31 @@ namespace ts {
...
+                    links.type = getWidenedTypeFromJSSpecialPropertyDeclarations(symbol, symbol);
                 }
                 else {
-                    const type = createObjectType(ObjectFlags.Anonymous, symbol);
-                    if (symbol.flags & SymbolFlags.Class) {
-                        const baseTypeVariable = getBaseTypeVariableOfClass(symbol);
-                        links.type = baseTypeVariable ? getIntersectionType([type, baseTypeVariable]) : type;
+                    if (symbol.flags & SymbolFlags.ValueModule && symbol.valueDeclaration && isSourceFile(symbol.valueDeclaration) && symbol.valueDeclaration.commonJsModuleIndicator) {
+                        if (!pushTypeResolution(symbol, TypeSystemPropertyName.Type)) {
+                            return errorType;
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Why not set `links.type` in this case?
This whole function might be neater if it just called `getTypeOfFuncClassEnumModuleUncached` which used `return x` instead of `links.type = x`. Then we would be sure to be setting the value and not forgetting some control flow path.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -19295,7 +19322,7 @@ namespace ts {
             if (node.expression.kind === SyntaxKind.SuperKeyword) {
                 const superType = checkSuperExpression(node.expression);
                 if (isTypeAny(superType)) {
-                    forEach(node.arguments, checkExpresionNoReturn); // Still visit arguments so they get marked for visibility, etc
+                    forEach(node.arguments, checkExpressionNoReturn); // Still visit arguments so they get marked for visibility, etc
```
Comment (andy-ms) [inline src/compiler/checker.ts]: This seems like a complex way to avoid writing a `for` loop...

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Oops, that's a symptom of the development history. It looks a lot better with `isModuleExportsPropertyAccessExpression`.

File: src/compiler/checker.ts (hunk 5 above)
Comment (sandersn) [reply src/compiler/checker.ts]: I agree. Done.

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [reply src/compiler/checker.ts]: This is now `aliased || symbol` now that aliased is optional instead of sometimes duplicated.

File: src/compiler/checker.ts (hunk 9 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Yep!

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Yikes! Good catch.

Comment (sandersn) [reply src/compiler/checker.ts]: This is equivalent to always binding `module` in `module.exports` to a specific symbol, so I just moved it to the binder and moved `ModuleExports` from CheckFlags to SymbolFlags.

File: src/compiler/checker.ts (hunk 8 above)
Comment (sandersn) [reply src/compiler/checker.ts]: The original reason is that getTypeOfVariableOrParameterOrProperty does. I think that's because you can call `getTypeOfSymbol` in situations that are speculative, and you may successfully be able to get the type at a later time.

I tried this and nothing broke, even when I changed the equivalent line in `getTypeOfVariableOrParameterOrProperty`. So it looks like my guess is wrong. I think I will merge this for now and try that refactor separately, for both.
