### PR TITLE
fix(42923): Provide go-to-definition on unresolved shorthand properties

### LINKED ISSUE #42923: Provide go-to-definition on unresolved shorthand properties
```ts
interface Foo {
    /**
     * Hallo this is docs
     */
    yadda(): void
}

let x: Foo = {
    yadda/**/
};
```

Imagine that I am typing some code. I realize I don't remember what `yadda` is supposed to look like, so I run go-to-definition on `yadda`.

## Problem

Go-to-definition doesn't work, because at this point `yadda` is a shorthand property, so go-to-definition tries to look for a local named `yadda` that doesn't exist.

As a workaround, I often end up writing

```ts
interface Foo {
    /**
     * Hallo this is docs
     */
    yadda(): void
}

let x: Foo = {
    yadda: undefined!
};
```

just so I can go-to-definiiton on `yadda`, which really sucks.

## Expected Behavior

We should resiliently try to pick up on the original definition and jump there.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #42923

### CODE REVIEW

**Review by DanielRosenwasser — COMMENTED** [review]
Can you rename the tests to be more specific? Either `goToDefinitionIncompleteProperty` or `goToDefinitionShorthandProperty`?

File: tests/cases/fourslash/goToDefinitionProperty3.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+////interface Foo {
+////    /*2*/foo(): void
+////}
+////const foo = 1;
+////let x: Foo = {
+////    [|f/*1*/oo|]()
+////}
+
+verify.goToDefinition("1", "2");
```
[the remark this answers is not in the document]
Comment (a-tarasyuk) [reply tests/cases/fourslash/goToDefinitionProperty3.ts]: @DanielRosenwasser I think in this test no, because refers to `[|f/*1*/oo|]()` function. However, I think [goToDefinitionShorthandProperty05.ts](https://github.com/microsoft/TypeScript/pull/42924/files#diff-42c73f9324ba8a9f30837c2fd3fc6a04509bbd3c08b8777ba051bd878636daffR4-R11) should include. What do you think?

**Review by andrewbranch — APPROVED** [review]

File: src/services/goToDefinition.ts [hunk 2]
```diff
@@ -51,7 +51,8 @@ namespace ts.GoToDefinition {
         // assignment. This case and others are handled by the following code.
         if (node.parent.kind === SyntaxKind.ShorthandPropertyAssignment) {
             const shorthandSymbol = typeChecker.getShorthandAssignmentValueSymbol(symbol.valueDeclaration);
-            return shorthandSymbol ? shorthandSymbol.declarations.map(decl => createDefinitionInfo(decl, typeChecker, shorthandSymbol, node)) : [];
+            const definitions = shorthandSymbol ? shorthandSymbol.declarations.map(decl => createDefinitionInfo(decl, typeChecker, shorthandSymbol, node)) : [];
+            return concatenate(definitions, getDefinitionFromObjectLiteralElement(typeChecker, node) || []);
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:55]:
```suggestion
            const definitions = shorthandSymbol ? shorthandSymbol.declarations.map(decl => createDefinitionInfo(decl, typeChecker, shorthandSymbol, node)) : emptyArray;
            return concatenate(definitions, getDefinitionFromObjectLiteralElement(typeChecker, node) || emptyArray);
```

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/goToDefinition.ts [hunk 3]
```diff
@@ -51,7 +51,8 @@ namespace ts.GoToDefinition {
         // assignment. This case and others are handled by the following code.
         if (node.parent.kind === SyntaxKind.ShorthandPropertyAssignment) {
             const shorthandSymbol = typeChecker.getShorthandAssignmentValueSymbol(symbol.valueDeclaration);
-            return shorthandSymbol ? shorthandSymbol.declarations.map(decl => createDefinitionInfo(decl, typeChecker, shorthandSymbol, node)) : [];
+            const definitions = shorthandSymbol ? shorthandSymbol.declarations.map(decl => createDefinitionInfo(decl, typeChecker, shorthandSymbol, node)) : [];
```
Comment (sheetalkamat) [inline src/services/goToDefinition.ts:54]: Need to use emptyArray here as well

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

**Review by sheetalkamat — APPROVED** [review]
