### PR TITLE
Fix emit issue regarding null/undefined in type annotations

### LINKED ISSUE #11295: Incorrect emits with function return type declarations
**TypeScript Version:**  master

**Code**

`$ node built/local/tsc.js -t es5 -m amd --moduleResolution node --lib es6 index.ts`

```ts
function f(): undefined {
  return;
}
```

**Expected behavior:**

```js
function f() {
    return;
}
```

**Actual behavior:** 

```js
function f():  {
    return;
}
```

### PR DESCRIPTION
**Pull request by rbuckton**
When we compute and aggregate transform flags for a node, we were not detecting `null` or `undefined` as a type. As a result, the TypeScript transformation did not remove the type annotation for several nodes.

This change fixes the detection logic to correct the emit.

Fixes #11295 

// CC: @mhegazy, @vladima

### CODE REVIEW

File: src/compiler/transformers/ts.ts [hunk 1]
```diff
@@ -287,7 +287,7 @@ namespace ts {
 
                 case SyntaxKind.Constructor:
                     // TypeScript constructors are transformed in `visitClassDeclaration`.
```
Comment (vladima) [inline src/compiler/transformers/ts.ts]: is comment above still relevant?

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -2461,13 +2483,12 @@ namespace ts {
...
-        }
-
-        // If the parameter's name is 'this', then it is TypeScript syntax.
-        if (subtreeFlags & TransformFlags.ContainsDecorators || isThisIdentifier(name)) {
+        // The '?' token, type annotations, decorators, and 'this' parameters are TypeSCript
+        // syntax.
+        if (node.questionToken
+            || node.type
+            || subtreeFlags & TransformFlags.ContainsDecorators
+            || isThisIdentifier(name)) {
```
Comment (vladima) [inline src/compiler/binder.ts]: can you add a test to check this condition?

File: src/compiler/emitter.ts [hunk 3]
```diff
@@ -1198,12 +1212,14 @@ const _super = (function (geti, seti) {
...
         function emitCallExpression(node: CallExpression) {
             emitExpression(node.expression);
+            emitTypeArguments(node, node.typeArguments);
             emitExpressionList(node, node.arguments, ListFormat.CallExpressionArguments);
         }
 
         function emitNewExpression(node: NewExpression) {
             write("new ");
             emitExpression(node.expression);
+            emitTypeArguments(node, node.typeArguments);
```
Comment (vladima) [inline src/compiler/emitter.ts]: I can see why this is necessary, but do we have cases today when we need to emit type arguments or type annotations - asking because It will be nice to test this functionality

File: src/compiler/binder.ts (hunk 2 above)
Comment (rbuckton) [inline src/compiler/binder.ts]: These are all either already tested, or covered by `transformsElideNullUndefinedType`

Comment (rbuckton) [inline src/compiler/binder.ts]: The only new functionality is the test for `node.type`, which is covered by `transformsElideNullUndefinedType`

**Comment by vladima** [comment]
:+1:

File: tests/cases/compiler/transformsElideNullUndefinedType.ts [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+
+var f4 = (): null => null;
+var f5 = (): undefined => undefined;
+
+function f6(p0: null) { }
+function f7(p1: undefined) { }
+
+class C<T> {
+    m0(): null { return null; }
+    m1(): undefined { return undefined; }
```
Comment (mhegazy) [inline tests/cases/compiler/transformsElideNullUndefinedType.ts]: can you also add tests for null and undefined in type position for parameters for methods, arrow functions, function expressions, and setters.

Comment (rbuckton) [inline tests/cases/compiler/transformsElideNullUndefinedType.ts]: That's what `transformsElideNullUndefinedType` does.
