### PR TITLE
In getSuggestionForNonexistentSymbol, guard name against undefined

### LINKED ISSUE #19002: Crash on unexpected undefined when getting suggestions for nonexistent symbol
**TypeScript Version**:
2.5.3-insiders.20170919
**VSCode Version**
1.17.0-insider
**command requested**
getCodeFixes
**hit count**
13128
**stack**
```
at Object.unescapeLeadingUnderscores in tsserver.js (line: 8560, column: 18)
at Object.getSuggestionForNonexistentSymbol in tsserver.js (line: 19551, column: 95)
at Object.getActionsForCorrectSpelling [as getCodeActions] in tsserver.js (line: 73149, column: 38)
at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:72873:3 in  (line: undefined, column: )
at Object.forEach in tsserver.js (line: 1294, column: 30)
at Object.getFixes in tsserver.js (line: 72872, column: 16)
at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:76664:3 in  (line: undefined, column: )
at Object.flatMap in tsserver.js (line: 1526, column: 25)
at Object.getCodeFixesAtPosition in tsserver.js (line: 76662, column: 23)
at IOSession.Session.getCodeFixes in tsserver.js (line: 82655, column: 64)
at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) in tsserver.js (line: 81577, column: 61)
at IOSession.Session.executeWithRequestId in tsserver.js (line: 82790, column: 28)
at IOSession.Session.executeCommand in tsserver.js (line: 82799, column: 33)
at IOSession.Session.onMessage in tsserver.js (line: 82819, column: 35)
at Interface.<anonymous> in tsserver.js (line: 83945, column: 27)
at emitOne in events.js (line: 96, column: 13)
at Interface.emit in events.js (line: 191, column: 7)
at Interface._onLine in readline.js (line: 241, column: 10)
at Interface._normalWrite in readline.js (line: 384, column: 12)
at Socket.ondata in readline.js (line: 101, column: 10)
at emitOne in events.js (line: 96, column: 13)
at Socket.emit in events.js (line: 191, column: 7)
at readableAddChunk in _stream_readable.js (line: 178, column: 18)
at Socket.Readable.push in _stream_readable.js (line: 136, column: 10)
at Pipe.onread in net.js (line: 560, column: 20)
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #19002 (probably)

This came from an aggregate of crash stacks, and from my reading of the code, it doesn't look like `name` can ever be null (see below for analysis). So:

1. I don't know how to repro this, except for a unittest that calls getSuggestionForNonexistentSymbol directly.
2. I decided to put the guard as close to the crash as possible.

I'll poke around the unit tests to see if there's a good place to write a test.

## Analysis

* The crash happens in `unescapeLeadingUnderscores(name)`, called from `getSuggestionForNonexistentSymbol`. 
* `name` is a parameter of an lambda, and is provided by `resolveNameHelper`.
* But `name` is an *argument* to `resolveNameHelper`, and is supposed to pass through unchanged.
* Looking at `resolveNameHelper`, I see no assignments to `name`, nothing that shadows `name`, and that the lambda is always called with `name` as its argument. So it looks like it does indeed pass through unchanged.
* The caller of `getSuggestionForNonexistentSymbol` is `fixSpelling.ts:getActionsForCorrectSpelling`.
* The argument for `name` is `getTextOfNode(node)`.
* `getTextOfNode` calls `getSourceTextOfNodeFromSourceFile`
* `getSourceTextOfNodeFromSourceFile` either returns `""` if the node is missing or calls `String.substring` otherwise. So it never returns `undefined`.

I might be missing some call locations, but they shouldn't matter since the call stack from #19002 follows the path that I laid out above.

### CODE REVIEW

**Comment by sandersn** [comment]
Unfortunately, the public API always calls `escapeLeadingUnderscores` before `getSuggestionForNonexistentSymbol`, so passing `undefined` crashes there first.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15064,7 +15064,10 @@ namespace ts {
 
         function getSuggestionForNonexistentSymbol(location: Node, name: __String, meaning: SymbolFlags): string {
             const result = resolveNameHelper(location, name, meaning, /*nameNotFoundMessage*/ undefined, name, /*isUse*/ false, (symbols, name, meaning) => {
-                // `name` from the callback === the outer `name`
+                // NOTE: `name` from the callback is supposed to  === the outer `name`, but is undefined in some cases
+                if (name === undefined) {
```
Comment (mhegazy) [inline src/compiler/checker.ts]: would not it be better to put this in getActionsForCorrectSpelling? i find it hard to see how resolveName can return `undefined`

**Comment by andy-ms** [comment]
That error looks like #18379, which was likely fixed by #18793. In other words, we have no evidence that this is a bug in master, and some evidence that it isn't.

**Comment by mhegazy** [comment]
I agree with @andy-ms, lets wait on this one and see if we get new reports post 2.6.0

**Comment by sandersn** [comment]
Looks like @aozgaa found post-2.6 crashes. Should I merge this? I could also ask him how to log so we could figure out how this happens.

**Comment by sandersn** [comment]
I switched to asserts instead of undefined checks, so we should be able to see whether the undefined is introduced.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -15290,9 +15290,9 @@ namespace ts {
             return suggestion && symbolName(suggestion);
         }
 
-        function getSuggestionForNonexistentSymbol(location: Node, name: __String, meaning: SymbolFlags): string {
-            const result = resolveNameHelper(location, name, meaning, /*nameNotFoundMessage*/ undefined, name, /*isUse*/ false, (symbols, name, meaning) => {
-                // `name` from the callback === the outer `name`
+        function getSuggestionForNonexistentSymbol(location: Node, outerName: __String, meaning: SymbolFlags): string {
+            const result = resolveNameHelper(location, outerName, meaning, /*nameNotFoundMessage*/ undefined, outerName, /*isUse*/ false, (symbols, name, meaning) => {
+                Debug.assert(name !== undefined, "name should always be defined, and equal to " + outerName);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: So assert `name === outerName`, and `Debug.assert(outerName !== undefined)` at the top

**Comment by andy-ms** [comment]
The original issue was confirmed fixed https://github.com/Microsoft/TypeScript/issues/18379#issuecomment-341949981

**Comment by mhegazy** [comment]
@aozgaa still see crash reports for it on 2.6.1

**Comment by mhegazy** [comment]
so we might have addressed some but not all cases (not sure how that would happen still though).

File: src/compiler/checker.ts (hunk 2 above)
Comment (andy-ms) [inline src/compiler/checker.ts]: `Debug.assertEqual(name, outerName)` and at the top `Debug.assert(outerName !== undefined)`

Comment (sandersn) [reply src/compiler/checker.ts]: Good idea.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -15290,9 +15290,10 @@ namespace ts {
             return suggestion && symbolName(suggestion);
         }
 
-        function getSuggestionForNonexistentSymbol(location: Node, name: __String, meaning: SymbolFlags): string {
-            const result = resolveNameHelper(location, name, meaning, /*nameNotFoundMessage*/ undefined, name, /*isUse*/ false, (symbols, name, meaning) => {
-                // `name` from the callback === the outer `name`
+        function getSuggestionForNonexistentSymbol(location: Node, outerName: __String, meaning: SymbolFlags): string {
+            Debug.assert(outerName !== undefined, "outername should always be defined");
```
Comment (andy-ms) [inline src/compiler/checker.ts]: The description is optional -- in this case you're simply repeating what the code says.

Comment (sandersn) [reply src/compiler/checker.ts]: Should make the assert less mysterious in logs, etc, though, since Javascript can only print `false`, not `outerName !== undefined`, otherwise.
