### PR TITLE
Instantiate constraints with type parameter as 'this'

### LINKED ISSUE #5525: Polymorphic 'this' not working with generic type parameter.
```typescript
class A {
	self(): this {
		return this;
	}
}

class T extends A {}

var t: T = new T().self(); // Here is fine.

class B<T extends A> {
	a: T;
	test(): T {
		return this.a.self(); // Here got error: "Type 'A' is not assignable to type 'T'".
	}
}

```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #5525.

### CODE REVIEW

File: tests/cases/conformance/types/thisType/thisTypeAndConstraints.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
+class A {
+    self() {
```
Comment (sandersn) [inline tests/cases/conformance/types/thisType/thisTypeAndConstraints.ts]: could you be explicit that `self(): this` here?

File: tests/baselines/reference/thisTypeInClasses.errors.txt [hunk 2]
```diff
@@ -1,57 +0,0 @@
-tests/cases/conformance/types/thisType/thisTypeInClasses.ts(4,20): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
-
-
-==== tests/cases/conformance/types/thisType/thisTypeInClasses.ts (1 errors) ====
-    class C1 {
-        x: this;
-        f(x: this): this { return undefined; }
-        constructor(x: this) { }
-                       ~~~~
-!!! error TS2526: A 'this' type is available only in a non-static member of a class or interface.
```
Comment (sandersn) [inline tests/baselines/reference/thisTypeInClasses.errors.txt]: Was this error unintended? It looks like the test meant to assert that 'this' is not accessible in statics. Why remove it with this change? I don't see any generics here.

File: src/compiler/types.ts [hunk 3]
```diff
@@ -1956,6 +1956,8 @@ namespace ts {
         target?: TypeParameter;  // Instantiation target
         /* @internal */
         mapper?: TypeMapper;     // Instantiation mapper
+        /* @internal */
+        resolvedApparentType: Type;
```
Comment (sandersn) [inline src/compiler/types.ts]: Who uses this or will use it?

File: tests/baselines/reference/thisTypeInClasses.errors.txt (hunk 2 above)
Comment (ahejlsberg) [inline tests/baselines/reference/thisTypeInClasses.errors.txt]: This particular test is supposed to have no errors. We generate .symbols and .types files only when there are no errors and part of this test is to check that those files remain constant.

File: src/compiler/types.ts (hunk 3 above)
Comment (ahejlsberg) [inline src/compiler/types.ts]: Look at the changes in checker.ts.

File: tests/cases/conformance/types/thisType/thisTypeAndConstraints.ts (hunk 1 above)
Comment (ahejlsberg) [inline tests/cases/conformance/types/thisType/thisTypeAndConstraints.ts]: I don't think there's a need to.

File: tests/baselines/reference/thisTypeInClasses.errors.txt (hunk 2 above)
Comment (sandersn) [inline tests/baselines/reference/thisTypeInClasses.errors.txt]: OK, I didn't know that .errors.txt and .symbols/.types were mutually exclusive.

File: src/compiler/types.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/types.ts]: Oh, I missed that it was doing caching. I expected some other code to read it but it looks like it's only to avoid re-computing the apparent type.

**Comment by sandersn** [comment]
:+1:
