### PR TITLE
Export declarations exporting aliases make the namespace instantiated

### LINKED ISSUE #54446: Import alias fails after being re-exported from another namespace via an export declaration when only import aliases are exported
# Bug Report

I found the using `import Something = Namespace.Something` then re-exporting that from a namespace leads to some strange behaviour, but only when import alises are the only things exported.

### 🔎 Search Terms

"Cannot use namespace" as value

### 🕗 Version & Regression Information

- This probably has existed for a while
- Tested in 5.2.0-dev.20230529

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=24&ssc=86&pln=2&pc=3#code/CYUwxgNghgTiAEBbA9sArhBAXEBnL8A3gLABQ8SqGCADlGANYCMRZFFYyAdvvDvkwBc8fDACWXAOYBuNu048C-LAGZhXNIgBGIGLPLsQADxrIYBQnzxYmAGiv4V8AL76KzuSnSZ4dRgCZWAwoxRFNzBxt4AF5femYAOmUmN3ZQ8KVrJ1i-ROUVVIpjDKJIu0inVzkPAy9qOMYnEmD4dLNMgRiGhn8k6xS5ELD2iq7c3vzC+GKRy2T7fJdUmrk2iNyAURN2lhz4pj6BVLWCTe3zQL2Aw5tj4fX4rYzs7pUbgYMT7qf2gBYx+ITfr6OQKXj5YRYACeNBAyAAZt9zqpUjMIpYzhkWFBcGV7Jj2oEcZF-AssvjHsj-sTlP8qqRnEA

### 💻 Code

```ts
declare module pack1 {
  const test1: string;
  const test3: number;
  export { test1, test3 };
}
declare module pack2 {
  import test1 = pack1.test1;
  import test3 = pack1.test3;
  export { test1, test3 };
}
declare module pack3 {
  import test1 = pack2.test1;
  import test3 = pack2.test3;
  export { test1, test3 };
}

import packExport1 = pack1.test1;
import packExport2 = pack2.test1;
import packExport3 = pack3.test1;
import packExport4 = pack2.test1;

declare const test3: typeof packExport3;
export { packExport1 as test1, packExport2 as test2, test3, packExport4 as test4 };
```

### 🙁 Actual behavior

The types are inferred correctly, but the type checker errors:

```
> npx tsc test.d.ts
test.d.ts:12:18 - error TS2708: Cannot use namespace 'pack2' as a value.

12   import test1 = pack2.test1;
                    ~~~~~

test.d.ts:13:18 - error TS2708: Cannot use namespace 'pack2' as a value.

13   import test3 = pack2.test3;
                    ~~~~~

test.d.ts:18:22 - error TS2708: Cannot use namespace 'pack2' as a value.

18 import packExport2 = pack2.test1;
                        ~~~~~


Found 3 errors in the same file, starting at: test.d.ts:12
```

### 🙂 Expected behavior

No errors.

### Workaround

Add some other declaration and export it from any namespace that only exports import aliases:

```ts
// no diagnostics, everything is fine now
declare namespace pack1 {
  const test1: string;
  const test3: number;
  export { test1, test3 };
}
declare namespace pack2 {
  import test1 = pack1.test1;
  import test3 = pack1.test3;
  export const __dummyExport: string; // edit: actually, i discovered this doesn't need to be exported
  export { test1, test3 };
}
declare namespace pack3 {
  import test1 = pack2.test1;
  import test3 = pack2.test3;
  export const __dummyExport: string;
  export { test1, test3 };
}

import packExport1 = pack1.test1;
import packExport2 = pack2.test1;
import packExport3 = pack3.test1;
import packExport4 = pack3.test3;

declare const test3: typeof packExport3;
export { packExport1 as test1, packExport2 as test2, test3, packExport4 as test4 };
```

### Workaround 2

Use `export import`:

```ts
// no errors
declare namespace pack1 {
  const test1: string;
  const test3: number;
  export { test1, test3 };
}
declare namespace pack2 {
  export import test1 = pack1.test1;
  export import test3 = pack1.test3;
}
declare namespace pack3 {
  export import test1 = pack2.test1;
  export import test3 = pack2.test3;
}

import packExport1 = pack1.test1;
import packExport2 = pack2.test1;
import packExport3 = pack3.test1;
import packExport4 = pack3.test3;

declare const test3: typeof packExport3;
export { packExport1 as test1, packExport2 as test2, test3, packExport4 as test4 };
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #54446

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -313,7 +313,7 @@ import {
     unusedLabelIsError,
     VariableDeclaration,
     WhileStatement,
-    WithStatement,
+    WithStatement
```
Comment (andrewbranch) [inline src/compiler/binder.ts:316]: Organize Imports 💀

Comment (jakebailey) [reply src/compiler/binder.ts:316]: Are you saying it removed the comma?

Comment (jakebailey) [reply src/compiler/binder.ts:316]: (dprint when?)

Comment (andrewbranch) [reply src/compiler/binder.ts:316]: ASAP please. I need something to auto-fix everything when I’m flailing around with vim

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -445,6 +445,14 @@ function getModuleInstanceStateForAliasTarget(specifier: ExportSpecifier, visite
                     if (found === ModuleInstanceState.Instantiated) {
                         return found;
                     }
+                    if (statement.kind === SyntaxKind.ImportEqualsDeclaration) {
+                        // Treat re-exports of import aliases as instantiated,
```
Comment (sandersn) [inline src/compiler/binder.ts:449]: this doesn't break a lot of existing tests? I remember looking at this or similar problem a few years ago and it looked very complex. *however*, I may have been making it more complicated than it needed to be.

**Comment by sandersn** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt

**Review by sandersn — COMMENTED** [review]
If this doesn't break anything in the user tests et al, it's likely that it's safe to ship.

**Review by sandersn — APPROVED** [review]

File: src/compiler/binder.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/binder.ts:449]: Maybe you were attempting to resolve whether the alias actually necessitates instantiating the namespace instead of doing it unconditionally? I don’t know; I was surprised this didn’t change existing baselines too.

**Comment by andrewbranch** [comment]
It looks like the DT tests aren’t quite running right?

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by jakebailey** [comment]
Seems like it might have just been a temporary fluke? I know that Nathan had been working to get DT fixed up recently...

**Comment by andrewbranch** [comment]
This can technically be a breaking change in a pretty contrived scenario. When a namespace goes from uninstantiated to instantiated, it can no longer merge with a variable declaration of the same name: https://www.typescriptlang.org/play?target=99#code/HYQwtgpgzgDiDGEAEBBJBvAUEpEAeMA9gE4AuSAlsKRMQGYLIAqGAvpu5gCYTwA2IYslCRYjJACEM2SmCJkkLALyoAdEwDcM-PPLpFSVls7xCwKOSkr0RzEA
