### PR TITLE
fix(396): (Dis)allow Octal and Bad Escape Sequences in String and (Tagged) Template Literals

### LINKED ISSUE #396: Octal escape sequences should be a lexical/syntactic error in strict mode and ES5
The following code should be disallowed in strict mode and ES5:

```
"\5";
"\05";
"\55";
"\055";
```

This is disallowed by Annex B.1.2 of the EcmaScript 5 spec.

### LINKED ISSUE #12700: Lift Template Literal Restriction on Backslashes
# Overview

Everyone loves L<sup>A</sup>T<sub>E</sub>X so ESNext will likely allow tagged template strings to contain backslashes on any sequence - even ones that look like they might contain an invalid Unicode escapes.

In other words, something like

```ts
let x = tag `\u{wat}`;
```

is now valid, whereas previously it would be considered an error.

Reference: https://tc39.github.io/proposal-template-literal-revision/

As of this writing, the linked proposal is at Stage 3.

# Notes

1. This restriction lift doesn't apply to *untagged* template strings. For example:

   ```ts
   // All of these are still invalid.
   let bad = `bad escape sequence: \unicode`;
   let bracingOurselves = `\u{shouldntDoThis}`;
   let theWorst = `\xtremely bad`;
   ```

2. Because there is no appropriate representation for a "cooked" string that contains one of these escapes, the returned value at a position on the top-level array will be `undefined`, but the raw representation will be available. For example:

   ```ts
   function tag(strs) {
     console.log(strs[0] === undefined);
     console.log(strs.raw[0] === "\\unicode and \\u{55}");
   }
  // Prints 'true' twice.
   tag`\unicode and \u{55}`

# Proposed Emit

Input:

```ts
let x = tag `\u{hello} ${ 100 } \xtraordinary ${ 200 } wonderful ${ 300 } \uworld`;
```

Output:

```js
var x = (
    _a = [undefined, undefined, " wonderful ", undefined],
    _a.raw = ["\\u{hello} ", " \\xtraordinary ", " wonderful ", " \\uworld"],
    tag(_a, 100, 200, 300)
);
```

### LINKED ISSUE #39038: octal escape sequence literal type
**TypeScript Version:**  3.9.4

**Search Terms:**
literal type, type inference
**Code**

```ts
const c :'Copyright ©'= "Copyright \251"
```

**Expected behavior:**

No error or warning for octal escape sequence

**Actual behavior:**

Type '"Copyright 251"' is not assignable to type '"Copyright ©"'.

**Playground Link:** 
[Playground Link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=1&pc=41#code/MYewdgzgLgBMMC4DkBhEAHAngJwJYHMALWASqQF4YAiNLPI2AHQCYBWARiqA)
**Related:** 

https://eslint.org/docs/rules/no-octal-escape

### LINKED ISSUE #39563: Numeric separated literals should disallow zero leading
**Search Terms:**
numeric separator

[spec test for checking leading zero separated literal](https://github.com/tc39/test262/blob/master/test/language/literals/numeric/numeric-separators/numeric-separator-literal-nzd-nsl-dds-leading-zero-err.js)

**Code**

These literals should be invalid: 
```ts
0_0
0_0.0
0_0e0_0
0_0_1
```

but this should valid:
```ts
1_0.0_1 // 10.01
1_0e0_1 // 100
```

**Expected behavior:**
SyntaxError: Numeric separator can not be used after leading 0.

**Actual behavior:**
```ts
0_0     // -> 0  valid but shouldn't
0_0.0   // -> 0  valid but shouldn't
0_0e0_0 // -> 0  valid but shouldn't
0_0_1   // -> 1  valid but shouldn't. Btw 001 is invalid in strict mode

1_0.0_1 // -> 10.01 ok
1_0e0_1 // -> 100 ok
```
[playground](https://www.typescriptlang.org/play/#code/PTAEGcAsHsFcBsAmoCWA7AbgQ3ixAuAKAAYB9Yk8gOgrOIFM7DCRRtdFCBGasr78o1JcgA)

### LINKED ISSUE #39715: raw tagged string doesn't support for `\x`
**TypeScript Version:**  3.9

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

function raw(x: TemplateStringsArray)
{
    return x.raw;
}
const originEnv =raw`\x`

```

**Expected behavior:**
```
Running and output
```
**Actual behavior:**
```
ts-node gen-env.ts

C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
gen-env.ts:6:24 - error TS1125: Hexadecimal digit expected.

6 const originEnv =raw`\x`


    at createTSError (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:434:12)
    at reportTSError (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:438:19)
    at getOutput (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:578:36)
    at Object.compile (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:775:32)
    at Module.m._compile (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\lygstate\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

```
**Playground Link:** 
https://www.staging-typescript.org/play?target=7#code/PTAEEFQKgZwUwDYDMC0BjA9gOwC4EMBLLOAEylBLgFtsYcAnPHA7UDJUHACzlAAd6GAEYJqoJBgQIMAdxgA6RQFgAUCFAAVOHU5cCMUEICeoegFcsWIgHNQAAxww0dtll29MVKniwkUCIjgAGlMmHnpdH11BM2suUB8MbjgIoTMCBBJODElQGDM0eLwDAHEzBD4QgHU4IT48NABrELgcNHlVVSQLNGZWRhkACgAPAC5Naj4EJjgAZQYbGHB6RiMASlUAb1VQXdNWs3o3YfkBgG5VAF9VTCwdDHoCayIAUSwAN1AAXgG7AB1hnZVEA

**Related Issues:**

### LINKED ISSUE #42887: `\u` in String.raw
# Bug Report

### 🔎 Search Terms

String.raw

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about String.raw

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MoFwTglgdg5gdGAhgdwAaICYGMA6GCmAZjjABYQ4BWA1gDY4C2UA9jgA4COYOAziDgFcAbshwAPAJ4AvVACggA)

### 💻 Code

```ts
String.raw`adc\def\ghi\jkl\mno\pqr\st\uvw\xyz`
```

### 🙁 Actual behavior

Error reported:  `error TS1125: Hexadecimal digit expected.`

### 🙂 Expected behavior

Complete transpile

### PR DESCRIPTION
**Pull request by graphemecluster**
#23801 makes bad escape sequences in tagged template allowable, but only in certain cases. #41030 aims to fix this but was closed.
In contrast, octal escape sequences in string literals (as in #396) should be disallowed.

Fully fixes #12700
Fixes #396
Fixes #39038
Fixes #39715
Fixes #42887
Fixes #39563 (#39698 attempts to fix this but was closed)

This PR currently disallow octal literals and escape sequences **regardless of the target, strict mode or not** as the Team is looking for simplicity (Refer to https://github.com/microsoft/TypeScript/issues/396#issuecomment-853564421).

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

File: tests/baselines/reference/api/typescript.d.ts [hunk 1]
```diff
@@ -4534,7 +4534,6 @@ declare namespace ts {
         reScanSlashToken(): SyntaxKind;
         reScanAsteriskEqualsToken(): SyntaxKind;
         reScanTemplateToken(isTaggedTemplate: boolean): SyntaxKind;
-        reScanTemplateHeadOrNoSubstitutionTemplate(): SyntaxKind;
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/api/typescript.d.ts:4537]: Feels like an unexpected breaking change.

File: src/compiler/factory/nodeFactory.ts [hunk 2]
```diff
@@ -1292,10 +1293,11 @@ export function createNodeFactory(flags: NodeFactoryFlags, baseFactory: BaseNode
     }
 
     // @api
-    function createStringLiteral(text: string, isSingleQuote?: boolean, hasExtendedUnicodeEscape?: boolean): StringLiteral {
+    function createStringLiteral(text: string, isSingleQuote?: boolean, hasExtendedUnicodeEscape?: boolean, rangesOfOctalSequences?: ReadonlyTextRange[]): StringLiteral {
         const node = createBaseStringLiteral(text, isSingleQuote);
         node.hasExtendedUnicodeEscape = hasExtendedUnicodeEscape;
         if (hasExtendedUnicodeEscape) node.transformFlags |= TransformFlags.ContainsES2015;
+        node.rangesOfOctalSequences = rangesOfOctalSequences;
```
Comment (DanielRosenwasser) [inline src/compiler/factory/nodeFactory.ts:1300]: We need to find a different way to issue errors - or only conditionally set this property. Most string literal nodes will never have these, and they shouldn't bloat up the node.

File: src/compiler/binder.ts [hunk 3]
```diff
@@ -2627,8 +2627,15 @@ function createBinder(): (file: SourceFile, options: CompilerOptions) => void {
         }
     }
 
+    function checkStrictModeStringLiteral(node: StringLiteral) {
+        if (languageVersion >= ScriptTarget.ES5 && inStrictMode && node.rangesOfOctalSequences) {
+            file.bindDiagnostics.push(...node.rangesOfOctalSequences.map(
```
Comment (DanielRosenwasser) [inline src/compiler/binder.ts:2632]: We try to avoid `.push(...thing)` to avoid weird worst-case stack overflow risks.

File: src/compiler/scanner.ts [hunk 4]
```diff
@@ -1340,12 +1345,17 @@ export function createScanner(languageVersion: ScriptTarget,
         }
 
         Debug.assert(resultingToken !== undefined);
+        if (shouldEmitInvalidEscapeError) {
+            rangesOfOctalSequences.forEach(range => {
```
Comment (DanielRosenwasser) [inline src/compiler/scanner.ts:1349]: Preference for a simple for loop here

File: src/compiler/scanner.ts [hunk 5]
```diff
@@ -1278,13 +1282,14 @@ export function createScanner(languageVersion: ScriptTarget,
...
      */
-    function scanTemplateAndSetTokenValue(isTaggedTemplate: boolean): SyntaxKind {
+    function scanTemplateAndSetTokenValue(shouldEmitInvalidEscapeError: boolean): SyntaxKind {
         const startedWithBacktick = text.charCodeAt(pos) === CharacterCodes.backtick;
 
         pos++;
         let start = pos;
         let contents = "";
         let resultingToken: SyntaxKind;
+        rangesOfOctalSequences = [];
```
Comment (DanielRosenwasser) [inline src/compiler/scanner.ts:1292]: To avoid an allocation unless necessary, set this to `undefined`. Then every `rangesOfOctalSequences.push(...)` can become `(rangesOfOctalSequences ??= []).push(...)`.

File: tests/baselines/reference/octalLiteralInStrictModeES3.errors.txt [hunk 6]
```diff
@@ -1,8 +1,11 @@
...
-==== tests/cases/conformance/parser/ecmascript5/StrictMode/octalLiteralInStrictModeES3.ts (1 errors) ====
+==== tests/cases/conformance/parser/ecmascript5/StrictMode/octalLiteralInStrictModeES3.ts (2 errors) ====
     "use strict";
     03;
     ~~
-!!! error TS1085: Octal literals are not available when targeting ECMAScript 5 and higher. Use the syntax '0o3'.
\ No newline at end of file
+!!! error TS1085: Octal literals are not available when targeting ECMAScript 5 and higher. Use the syntax '0o3'.
+    ~~
+!!! error TS1121: Octal literals are not allowed in strict mode.
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/octalLiteralInStrictModeES3.errors.txt:11]: Seems undesirable to give a double-error here.

**Review by DanielRosenwasser — COMMENTED** [review]
I'm not sure if this PR is the right place to discuss this - but as we consider deprecating ES3 targets, and as I've reviewed more and more parsing issues in TypeScript that make decisions based on the language target, it feels like we should start reconsidering our approach.

Language target is really not the same as the parsing language version; and we're not always emitting code either. I wonder if there are opportunities to simplify.

File: tests/baselines/reference/octalLiteralInStrictModeES3.errors.txt (hunk 6 above)
Comment (graphemecluster) [reply tests/baselines/reference/octalLiteralInStrictModeES3.errors.txt:11]: The target < ES5 check seems weird as there is no strict mode in ES3, so I assume that’s a mistake and reversed the condition. I actually did wonder if we should completely remove the number literal octal check in the binder since this is already covered in the checker.

File: tests/baselines/reference/api/typescript.d.ts (hunk 1 above)
Comment (graphemecluster) [reply tests/baselines/reference/api/typescript.d.ts:4537]: Is the scanner being used heavily externally? It is the same as `reScanTemplateToken(false)`, just without the assertion.

File: src/compiler/binder.ts (hunk 3 above)
Comment (graphemecluster) [reply src/compiler/binder.ts:2632]: I did find multiple use cases in src by searching `.push(...` – perhaps we should totally get rid of it?

**Comment by graphemecluster** [comment]
@DanielRosenwasser The point is whether the code is in strict mode, not the target.

We now have two options:
- Emit the error in the scanner, regardless of strict mode or not – i.e. completely disallow octal escape sequence
- Attempt to rescan the string in the binder if `tokenFlags` contains `Octal`

In either way I am going to root out `rangesOfOctalSequences` and remove the target check this time.

File: tests/cases/conformance/expressions/objectLiterals/objectLiteralErrors.ts [hunk 7]
```diff
@@ -15,7 +15,7 @@ var e11 = { 1.0: 0, '1': 0 };
 var e12 = { 0: 0, 0: 0 };
 var e13 = { 0: 0, 0: 0 };
 var e14 = { 0: 0, 0x0: 0 };
-var e14 = { 0: 0, 000: 0 };
+var e14 = { 0: 0, 0o0: 0 };
```
Comment (graphemecluster) [inline tests/cases/conformance/expressions/objectLiterals/objectLiteralErrors.ts:18]: This parser diagnostic will block the “Duplicate identifier” errors being appeared, which is the main interest of this file, thus the change.

Comment (graphemecluster) [inline tests/cases/conformance/expressions/objectLiterals/objectLiteralErrors.ts:18]: This parser diagnostic will block the “Duplicate identifier” errors from being appeared, which is the main interest of this file, thus the change.

**Comment by graphemecluster** [comment]
Could we get this fixed before the TS 5.0 release (#51362)? False-positive diagnostics are being reported for years. After the rewrite I could say that it’s my most confident PR I ever wrote after all.

**Comment by graphemecluster** [comment]
@DanielRosenwasser Could we get this fixed before the TS 5.0 release (#51362)? False-positive diagnostics are being reported for years. After the rewrite I could say that it’s my most confident PR I ever wrote after all.

File: src/compiler/scanner.ts [hunk 8]
```diff
@@ -1356,13 +1426,46 @@ export function createScanner(languageVersion: ScriptTarget,
...
+                    error(Diagnostics.Octal_escape_sequences_are_not_allowed_Use_the_syntax_0, start, pos - start, "\\x" + padLeft(code.toString(16), 2, "0"));
+                    return String.fromCharCode(code);
+                }
+                return text.substring(start, pos);
+            case CharacterCodes._8:
+            case CharacterCodes._9:
+                // the invalid '\8' and '\9'
+                tokenFlags |= TokenFlags.ContainsInvalidEscape;
+                if (shouldEmitInvalidEscapeError) {
+                    error(Diagnostics._0_is_not_allowed, start, 2, text.substring(start, pos));
```
Comment (DanielRosenwasser) [inline src/compiler/scanner.ts:1465]: How about

```
Escape sequences cannot start with '{0}'
```

Comment (DanielRosenwasser) [reply src/compiler/scanner.ts:1465]: Instead of hard-coding `2`, use `pos - start`.

File: src/compiler/scanner.ts [hunk 9]
```diff
@@ -1356,13 +1426,46 @@ export function createScanner(languageVersion: ScriptTarget,
         pos++;
         switch (ch) {
             case CharacterCodes._0:
-                // '\01'
-                if (isTaggedTemplate && pos < end && isDigit(text.charCodeAt(pos))) {
+                // '\08' is '\0' + '8' but is treated as an octal escape sequence, thus isDigit
```
[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/compiler/scanner.ts:1429]: Or you can use your shorthand notation and reference the spec as well.

File: src/compiler/scanner.ts [hunk 10]
```diff
@@ -1356,13 +1426,46 @@ export function createScanner(languageVersion: ScriptTarget,
         pos++;
         switch (ch) {
             case CharacterCodes._0:
-                // '\01'
-                if (isTaggedTemplate && pos < end && isDigit(text.charCodeAt(pos))) {
+                // '\08' is '\0' + '8' but is treated as an octal escape sequence, thus isDigit
+                if (!(pos < end && isDigit(text.charCodeAt(pos)))) {
```
[the remark this answers is not in the document]
Comment (DanielRosenwasser) [reply src/compiler/scanner.ts:1430]: Actually, I'm not totally against it.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
I think this is very close - I appreciate the work here. 

I don't think we can get this in for TS 5 Beta, but possibly the RC since I don't think we're seeing any real-world code being impacted and it's a correctness fix.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

File: src/compiler/scanner.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (graphemecluster) [reply src/compiler/scanner.ts]: Committed

File: src/compiler/scanner.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (graphemecluster) [reply src/compiler/scanner.ts]: OK I've put the spec extract right above the function.
Technically they are not being “allowed”, so I've rephrased the comment.

File: src/compiler/scanner.ts (hunk 8 above)
Comment (graphemecluster) [reply src/compiler/scanner.ts]: This is not correct, `\8` and `\9` are complete escape sequences. I've just prepended “Escape sequence” to the message.

**Comment by graphemecluster** [comment]
> since I don't think we're seeing any real-world code being impacted and it's a correctness fix.

At least people who like `String.raw` would love to see the error messages gone 🙂

**Comment by graphemecluster** [comment]
@DanielRosenwasser
> since I don't think we're seeing any real-world code being impacted and it's a correctness fix.

At least people who like `String.raw` would love to see the error messages gone 🙂

**Comment by sandersn** [comment]
From the most recent design meeting:

> Conclusion: Ship it!

@graphemecluster do you want to bring this up to date with main or do you want us to do it?

**Comment by graphemecluster** [comment]
@sandersn I've just done it for you. Please check if there are any problems.
P.S. The last CI checks I got took half an hour — now it's just 10 mins — a 3x boost!

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

File: tests/baselines/reference/api/typescript.d.ts (hunk 1 above)
Comment (graphemecluster) [reply tests/baselines/reference/api/typescript.d.ts:4444]: Now that many of the methods were deprecated by #53078, so I just deprecated it anyway.

File: src/compiler/scanner.ts [hunk 11]
```diff
@@ -1105,14 +1110,69 @@ export function createScanner(languageVersion: ScriptTarget,
...
+                // a single zero
+                mainFragment = "0";
+            }
+            else {
+                // LegacyOctalIntegerLiteral
+                tokenValue = "" + parseInt(tokenValue, 8);
+                tokenFlags |= TokenFlags.Octal;
+                const withMinus = token === SyntaxKind.MinusToken;
+                const literal = (withMinus ? "-" : "") + "0o" + (+tokenValue).toString(8);
+                start -= +withMinus;
```
Comment (sandersn) [inline src/compiler/scanner.ts:1168]: minor: `if (withMinus) start--` avoids a maybe (?) slow boolean->numeric conversion and is also way less surprising (I typically expect only strings containing numbers to be converted to numbers, and my brain is broken by learning that True coerces to -1 in Visual Basic [1] many many years ago, so I always have trouble reading boolean->numeric math.)

[1] -1 is all 1s in twos-complement binary representation, you see. It almost makes sense!

**Review by sandersn — CHANGES_REQUESTED** [review]
One last small change. Otherwise looks good.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
Deleted my last comment and cancelled the test runs - but there's some weird language service results in the last run that Jake kicked off. So let's try that once more.

@typescript-bot perf test this

File: src/compiler/scanner.ts (hunk 11 above)
Comment (graphemecluster) [reply src/compiler/scanner.ts]: Well, at least `Ternary.True` is still -1 😂

**Comment by gabritto** [comment]
@typescript-bot run DT

**Comment by gabritto** [comment]
@typescript-bot run DT

**Comment by gabritto** [comment]
@typescript-bot run DT

**Comment by gabritto** [comment]
@typescript-bot run DT

**Comment by gabritto** [comment]
@typescript-bot run DT

**Comment by sandersn** [comment]
That DT failure is weird, since the line before has `// @ts-expect-error`.

**Comment by jakebailey** [comment]
Are parse errors `@ts-expect-error`-silence-able?

**Review by sandersn — APPROVED** [review]

**Review by jakebailey — CHANGES_REQUESTED** [review]
I think we need to make sure that we aren't breaking the public API for those using the scanner; this changes the meaning of some scanner functions (and misses updating the public API to match).

File: tests/baselines/reference/api/typescript.d.ts [hunk 12]
```diff
@@ -4441,6 +4441,7 @@ declare namespace ts {
         reScanSlashToken(): SyntaxKind;
         reScanAsteriskEqualsToken(): SyntaxKind;
         reScanTemplateToken(isTaggedTemplate: boolean): SyntaxKind;
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply tests/baselines/reference/api/typescript.d.ts:4443]: Oh. I'm silly, this is a totally different function.

File: src/compiler/scanner.ts [hunk 13]
```diff
@@ -1292,7 +1363,7 @@ export function createScanner(languageVersion: ScriptTarget,
      * Sets the current 'tokenValue' and returns a NoSubstitutionTemplateLiteral or
      * a literal component of a TemplateExpression.
      */
-    function scanTemplateAndSetTokenValue(isTaggedTemplate: boolean): SyntaxKind {
+    function scanTemplateAndSetTokenValue(shouldEmitInvalidEscapeError: boolean): SyntaxKind {
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply src/compiler/scanner.ts:1366]: Bleh, ignore this; this function is internal!

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
@DanielRosenwasser Your review is the only red one; can you take another look to see if you see anything else?

**Comment by jakebailey** [comment]
So, this looks good to me, but I'm still worried about people using our parser on previously-valid code and now getting parse errors. I'd be interested to test out some users of our public API like ts-loader or rollup-typescript-plugin to see what happens.

**Comment by graphemecluster** [comment]
@sandersn Here is a clean commit to resolve the conflicts. Is there anything else I should do to facilitate merging?

**Comment by DanielRosenwasser** [comment]
Thank you @graphemecluster!
