### PR TITLE
Deeper type inference in context sensitive arguments

### LINKED ISSUE #1181: Regression in type resolution post-1.0
[Originally on CodePlex at http://typescript.codeplex.com/workitem/2510]

Dear TypeScript Team, 

The following code used to work - I believe as recently as TS 1.0 - but now fails. I'm using the latest Knockout.js with DefinitelyTyped declarations; however, the error occurred after I upgraded to VS 2013 Update 2 (I skipped the RC, although I kept TypeScript updated), and seems to have nothing to do with the 3rd-party library.

    private _quantity = ko.observable(0); // This is still correctly inferred as KnockoutObservable<number>.
    public quantity = ko.computed({ // ERROR: This is now incorrectly inferred as KnockoutComputed<any>.
        read: () => this._quantity(), // REGRESSION: This used to infer the type of 'read' as () => number, but now has only () => any.
        write: value => this._quantity(value),
        owner: this
    });

I'm sorry I don't know exactly which version(s) are affected; I may have skipped a minor version or two during the VS2013 Update 2 RC phase. 

Thanks! 
Lars

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #1181.

Previously, context sensitive arguments (arguments containing function expressions that are subject to contextual typing) would be completely ignored in the first round of type inference. With this change we instead infer from all arguments in the first round, but treat context sensitive function expressions as wildcards from which no inferences are made.
```typescript
interface Computed<T> {
    read(): T;
    write(value: T);
}

function foo<T>(x: Computed<T>) { }

var s: string;

foo({
    read: () => s,
    write: value => s = value
});
```
This example would previously infer `{}` for T because the object literal argument was excluded from the first round of type inference. We now include the argument in the first round, but treat the context sensitive arrow function `value => s = value` as a wildcard. That allows us to infer `string` for `T` from the (non-sensitive) arrow function `() => s`. In the second round of inference we then end up fixing `T` and assigning the inferred type `string` to the `value` parameter.

This also fixes a bug related to #1648 where the `contextualMapper` argument wasn't being propagated into a parenthesized expression, causing us to leak a type parameter.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5885,22 +5888,20 @@ module ts {
         function inferTypeArguments(signature: Signature, args: Expression[], excludeArgument?: boolean[]): InferenceContext {
             var typeParameters = signature.typeParameters;
             var context = createInferenceContext(typeParameters, /*inferUnionTypes*/ false);
-            var mapper = createInferenceMapper(context);
-            // First infer from arguments that are not context sensitive
+            var inferenceMapper = createInferenceMapper(context);
+
+            // First infer from all arguments using wildcards for all context sensitive function expressions
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Make this comment `First infer from all arguments, but use wildcards for all context sensitive expressions.`

The "but" actually would really help to point out that this is a special case.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -5885,22 +5888,20 @@ module ts {
...
-                        continue;
-                    }
-
-                    inferTypes(context, checkExpressionWithContextualType(args[i], parameterType, mapper), parameterType);
+                var parameterType = getTypeAtPosition(signature, i);
+                if (i === 0 && args[i].parent.kind === SyntaxKind.TaggedTemplateExpression) {
+                    inferTypes(context, globalTemplateStringsArrayType, parameterType);
+                    continue;
                 }
+                var mapper = !excludeArgument || excludeArgument[i] === undefined ? inferenceMapper : identityMapper;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Put parens around the condition expression, this almost looks like a null-propagation trick otherwise.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -5885,22 +5888,20 @@ module ts {
         function inferTypeArguments(signature: Signature, args: Expression[], excludeArgument?: boolean[]): InferenceContext {
             var typeParameters = signature.typeParameters;
             var context = createInferenceContext(typeParameters, /*inferUnionTypes*/ false);
-            var mapper = createInferenceMapper(context);
-            // First infer from arguments that are not context sensitive
+            var inferenceMapper = createInferenceMapper(context);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Technically, you may not use the inference mapper at if all your arguments are sensitive to contextual typing. This was already the case. I doubt it's a worthwhile optimization, but I'm just thinking out loud (in writing).

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -7283,7 +7285,7 @@ module ts {
                 case SyntaxKind.TypeAssertionExpression:
                     return checkTypeAssertion(<TypeAssertion>node);
                 case SyntaxKind.ParenthesizedExpression:
-                    return checkExpression((<ParenthesizedExpression>node).expression);
+                    return checkExpression((<ParenthesizedExpression>node).expression, contextualMapper);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: My bad!

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Ouch! Sorry about that.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can we get a test that would trigger this?

File: src/compiler/checker.ts (hunk 2 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Please put a comment explaining this line. Specifically, explain 2 things:

1. What does the undefined represent?
2. What consequence does the choice of mapper have for this argument?

Comment (JsonFreeman) [inline src/compiler/checker.ts]: Also, perhaps we should now address the issue of the subtlety of identityMapper to people reading the code. Is it ever used for anything other than avoiding contextual typing of context sensitive functions? If not, maybe call it avoidFunctionContextualTypingMapper. I think that is much more explicit.

File: tests/baselines/reference/parenthesizedContexualTyping1.types [hunk 5]
```diff
@@ -220,11 +220,11 @@ var l = fun(((Math.random() < 0.5 ? ((x => x)) : ((x => undefined)))), ((x => x)
...
->((x => x)) : (x: number) => number
->(x => x) : (x: number) => number
->x => x : (x: number) => number
->x : number
->x : number
+>((x => x)) : (x: any) => any
+>(x => x) : (x: any) => any
+>x => x : (x: any) => any
+>x : any
+>x : any
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/parenthesizedContexualTyping1.types]: Oh no - is this #241? This is definitely a regression.

To clarify in readability for anyone jumping in:

```TypeScript
function fun<T>(g: (x: T) => T, h: (y: T) => T, x: T): T;
```

Our parameters are

* `((Math.random() < 0.5 ? ((x => x)) : ((x => undefined))))`
* `((x => x))`
* `10`

Clearly this is not desirable.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -5912,10 +5913,11 @@ module ts {
                     // No need to special-case tagged templates; their excludeArgument value will be 'undefined'.
                     if (excludeArgument[i] === false) {
                         var parameterType = getTypeAtPosition(signature, i);
-                        inferTypes(context, checkExpressionWithContextualType(args[i], parameterType, mapper), parameterType);
+                        inferTypes(context, checkExpressionWithContextualType(args[i], parameterType, inferenceMapper), parameterType);
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: So the order is essentially still the same. We first do all the arguments (instead of just the ones that were never excluded). Then we come back and do the ones that were once excluded but no longer are.

I'm noticing two things:

1. For the arguments that do contain context sensitive expressions, we will end up visiting (inferring from) most of the argument twice. The only parts that will be new the second time are the context sensitive expressions. I guess it is not worth the complexity of trying to fish out just the context sensitive expressions for this second visit. After all, many arguments of this sort are likely to be lambdas, which only consist of a context sensitive expression.
2. We will visit each argument at most twice. So while this does improve things over what we had before, we will not be able to handle something like:
```ts
interface Computed<T, U> {
    read(): T;
    write(value: T): U;
    rewrite(value: U);
}

function foo<T, U>(x: Computed<T, U>) { }

var s: string;

foo({
    read: () => s,
    write: value => s = value,
    rewrite: value => s = value
});
```

For this to work, you'd have to visit the argument 3 times. I would be very surprised if this kind of thing ever comes up though.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -6609,7 +6611,7 @@ module ts {
             }
 
             // The identityMapper object is used to indicate that function expressions are wildcards
-            if (contextualMapper === identityMapper) {
+            if (contextualMapper === identityMapper && isContextSensitive(node)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I assume you're keeping the `contextualMapper === identityMapper` as a quick short-circuiting operation.

Comment (JsonFreeman) [inline src/compiler/checker.ts]: How was this not an issue before? Were we only passing identityMapper when the node was context sensitive?

File: src/compiler/checker.ts (hunk 4 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Good catch

File: src/compiler/checker.ts (hunk 2 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: I agree with the idea of being more explicit in this respect.

Also, maybe `excludeArguments` is not an accurate name anymore.

Also, can we split this line into 2 more lines?

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -4318,6 +4318,9 @@ module ts {
             }
 
             function inferFromTypes(source: Type, target: Type) {
+                if (source === anyFunctionType) {
+                    return;
+                }
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Add a simple comment above this and a newline below the body.

File: tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt [hunk 9]
```diff
@@ -10,8 +9,7 @@ tests/cases/compiler/contextualTypingWithFixedTypeParameters1.ts(3,32): error TS
...
     var r9 = f10('', () => (a => a.foo), 1); // error
-             ~~~
-!!! error TS2453: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
-!!! error TS2453:   Type argument candidate 'string' is not a valid type argument because it is not a supertype of candidate 'T'.
                                    ~~~
-!!! error TS2339: Property 'foo' does not exist on type 'T'.
\ No newline at end of file
+!!! error TS2339: Property 'foo' does not exist on type 'string'.
+                                         ~
+!!! error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
```
Comment (JsonFreeman) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: This seems incorrect. I think you want an error like the one that used to be there. It should read something like:
```
The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.

Type argument candidate 'string' is not a valid type argument because it is not a supertype of candidate 'number'.
```
What should happen is the middle argument is context sensitive, so we get no inferences from it initially, and the two candidates are string and number. Then we do the second pass, and it comes time to fix, and we error that 'T' cannot be inferred because candidate 'string' is not a supertype of candidate 'number'.

**Comment by DanielRosenwasser** [comment]
It is strange that we only have 2 affected baselines, and only in one of them did we see that leaked type parameter issue. This change really needs more test coverage.

File: tests/baselines/reference/parenthesizedContexualTyping1.types (hunk 5 above)
Comment (JsonFreeman) [inline tests/baselines/reference/parenthesizedContexualTyping1.types]: This also seems wrong. The first two arguments should be skipped the first time around, and number is inferred from the third argument. Then we come back to visit all the lambdas, and T gets fixed to number. It should be fixed to number in all 3 lambdas, but looks like it only worked for the first two.

File: src/compiler/checker.ts (hunk 2 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: +1 about excludeArguments

File: src/compiler/checker.ts (hunk 3 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: No, you will always use it on the second pass at least

**Comment by JsonFreeman** [comment]
Please add tests for this change.

File: src/compiler/checker.ts (hunk 3 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: My mistake, I see that now

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I'm going to leave the identityMapper and excludeArguments alone for now. We can clean that up in a separate PR, perhaps along with some optimizations around reusing type inferences from previous rounds.

File: src/compiler/checker.ts (hunk 4 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: contextualTypingWithFixedTypeParameters1.ts already tests it. The error message about a 'foo' property missing on type 'T' reveals the problem.

File: tests/baselines/reference/parenthesizedContexualTyping1.types (hunk 5 above)
Comment (ahejlsberg) [inline tests/baselines/reference/parenthesizedContexualTyping1.types]: The change in the test output is related to the missing contextualMapper argument for parenthesized expressions (and just brings the test in line with the non-parenthesized case), but the widening of the function result from `undefined` to `any` is real culprit. We've got that issue captured in #241.

File: src/compiler/checker.ts (hunk 6 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Yes, your observations are correct.

File: src/compiler/checker.ts (hunk 7 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Previously we would never pass identityMapper during inferential typing and it was fine to just treat *all* function expressions in the argument as wildcards. We now want a "hybrid" type constructed where only context sensitive function expessions are blanked out, such that we can infer from it in the first pass.

File: tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt (hunk 9 above)
Comment (ahejlsberg) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: We don't consider the outer arrow function to be context sensitive (it has no contextually typed parameters), but the contextual typing of the inner arrow function causes T to be fixed at its current set of inferences (string) during the initial pass. The later inference of number is ignored because T is already fixed.

The issue isn't related to this PR and I'm not sure that we want to fix it--nor am I sure how.

File: src/compiler/checker.ts (hunk 4 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I would still rather have a test that is explicitly designed to test this.

File: tests/baselines/reference/parenthesizedContexualTyping1.types (hunk 5 above)
Comment (JsonFreeman) [inline tests/baselines/reference/parenthesizedContexualTyping1.types]: I do not understand. Even if the lambda `x => undefined` gets widened, we should still fix T before trying to add 'any' as a candidate.

File: src/compiler/checker.ts (hunk 7 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I see. In other words, we only passed the identity mapper during the argument assignability check. And because that is a boolean check whose only side effects apply to context sensitive functions, it was impossible to observe the fact that context insensitive functions  were being skipped.

File: tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt (hunk 9 above)
Comment (JsonFreeman) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: But the inner arrow function is context sensitive, so shouldn't we skip it in the first pass, and thus not fix T?

File: tests/baselines/reference/parenthesizedContexualTyping1.types (hunk 5 above)
Comment (ahejlsberg) [inline tests/baselines/reference/parenthesizedContexualTyping1.types]: It's a subtle interplay between several things. Because we create a new inference type mapper each time we let in an excluded argument, we forget which type parameters were fixed the last time around. Combine that with the fact that once we assign parameter types to a contextually typed function expression, we keep those assignments and don't reassign again. This means that the parameter type assignments that caused type parameter fixing in the previous round don't occur again, and the type parameter now doesn't get fixed, causing us to make more inferences (in this case the `any` that came from the widened `undefined`).

The right thing to do would be to use a single inference mapper for all inferences related to a particular signature and incrementally build up more inferences in that mapper, but remembering which type parameters were already fixed. This would get us more consistent results and also be more efficient. But I'm not sure it needs to be part of this PR, it's really an orthogonal issue.

File: tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt (hunk 9 above)
Comment (ahejlsberg) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: Well, knowing that it is context sensitive (in the return type) would require us to analyze all return expressions in the function expression, which starts to get rather complicated.

Comment (JsonFreeman) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: I think we need to do that.

File: tests/baselines/reference/parenthesizedContexualTyping1.types (hunk 5 above)
Comment (JsonFreeman) [inline tests/baselines/reference/parenthesizedContexualTyping1.types]: Ah I see. That is really complicated and very hard for anybody to understand. I definitely think we need to make the inference context shared, and make it smarter. It has to distinguish between type parameters that were fixed because of contextual typing, versus type parameters that were just finalized because the inference round was over.

File: tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt (hunk 9 above)
Comment (ahejlsberg) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: I don't think we *need* to do it, but it certainly would be better. Either way, it's another orthogonal issue that isn't really related to the PR.

Comment (JsonFreeman) [inline tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt]: Fair, it would be better.

**Comment by JsonFreeman** [comment]
I'm fine with this code change, but it needs tests.
Also, I do think that the related issues we discussed should be addressed soon.

**Comment by JsonFreeman** [comment]
:+1:
