### PR TITLE
Fix #61098

### LINKED ISSUE #61098: Type containing templated, branded string is not assignable to itself
### 🔎 Search Terms

brand branded tag tagged template string not assignable extends different type name unrelated

### 🕗 Version & Regression Information

- This changed between versions 5.0.4 and 5.1.6

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/FAUwHgDg9gTgLgAgDYkQQwFwIBQB4AqAfNgJQIC8hC+C4cIAdgCYDOCABgCQDeA5GrwQAyBNwSYEARgQBfGewQB+KQiwAmMuQQMArkiQBCANyhIsRCkQAjLHiKkKVGnUasOPfoJFiJ0uQuVpdU1tPUMTYDQKBCsjIA

### 💻 Code

```ts
export let a: (<T>() => T extends `${'a' & { a: 1 }}` ? 1 : 2) = null!;
export let b: (<T>() => T extends `${'a' & { a: 1 }}` ? 1 : 2) = null!;

a = b; // ❌ Error!
```

### 🙁 Actual behavior

Typescript error:
> Type 
```'<T>() => T extends `${"a" & { a: 1; }}` ? 1 : 2'``` is not assignable to type 
```'<T>() => T extends `${"a" & { a: 1; }}` ? 1 : 2'```. 
Two different types with this name exist, but they are unrelated.

### 🙂 Expected behavior

No error

### Additional information about the issue

I would expect that, as a general principle, any type which is copy-and-pasted from one place to another should be assignable to itself. (With the exception of `unique symbol`, since by design it's supposed to _not_ do what I just said.) This is perhaps the most lax notion of assignability that could possibly exist, I would think.

Note that, as soon as I remove either the outer template or the inner brand, assignability works as expected once again.

### PR DESCRIPTION
**Pull request by HansBrende**
Fixes #61098

### CODE REVIEW

**Comment by HansBrende** [comment]
@microsoft-github-policy-service agree company="iMuto Software Solutions LLC"

**Comment by HansBrende** [comment]
Perhaps @jakebailey might be interested in reviewing this PR since it fixes a regression that was introduced in https://github.com/microsoft/TypeScript/pull/52836?

**Comment by jakebailey** [comment]
Some related code was all redone in #56434. I'll be honest when I say I don't know if my mental model of how this all is supposed to work is good enough to determine that this pure code addition is correct, or if there is something somewhere else that is what's supposed to be fixed.

**Comment by HansBrende** [comment]
@jakebailey from looking at the TS codebase, I believe that the only reason this was working before https://github.com/microsoft/TypeScript/pull/56434 was that primitive types that reached the _isTypeIdenticalTo_ block during _isTypeAssignableTo_ were quite simply cached so they compared as equal with `===`. Allowing tagged strings within template or mapped strings broke this memoization, so they no longer compared as equal with `===`, requiring explicit checks for the cases of template and mapped strings instead of the simple `===` check.

(FYI I used every-ts to bisect to https://github.com/microsoft/TypeScript/pull/56434).

Question: if you don't feel confident reviewing this, do you know anyone who would? I was told that if I submitted this PR,  someone would look at it, but I've heard radio silence. (Just hoping that the PR doesn't end up in a landfill somewhere, haha 🤞 ).

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -23003,6 +23003,24 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                    if (arrayIsEqualTo((source as TemplateLiteralType).texts, (target as TemplateLiteralType).texts)) {
+                        const sourceTypes = (source as TemplateLiteralType).types;
+                        const targetTypes = (target as TemplateLiteralType).types;
+                        result = Ternary.True;
+                        for (let i = 0; i < sourceTypes.length; i++) {
+                            if (!(result &= isRelatedTo(sourceTypes[i], targetTypes[i], RecursionFlags.Both, /*reportErrors*/ false))) {
+                                break;
+                            }
+                        }
+                        return result;
```
Comment (jakebailey) [inline src/compiler/checker.ts:23016]: All of the other cases in this identity branch seem to return only when the result is truthy; should that be done here?

Comment (jakebailey) [reply src/compiler/checker.ts:23016]: No, just checking based on the "vibes" the new code gave me compared the existing code.

**Review by jakebailey — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
LGTM; just looking at the way indexed, conditional, substitution types work in the lines above, it's clear to me that the new code is correct as it structurally checks the type in the same way.

**Comment by HansBrende** [comment]
@jakebailey quick follow-up question: I noticed in typescript-go, this bug would still be present: https://github.com/microsoft/typescript-go/blob/main/internal/checker/relater.go#L3296

Am I expected to open an equivalent PR/issue over there if I want it to be fixed in both places, or will all the bugfixes automatically get ported over there as well without my intervention?

**Comment by jakebailey** [comment]
We have months of PRs to port over, so don't worry about it quite yet until we point the TypeScript-go's target commit to one past this PR (and therefore tests will be present and be fixable).
