### PR TITLE
Use contextual parameter types over binding pattern initializer types

### LINKED ISSUE #28835: TS2322: inferred string instead value type since TS3.2
**TypeScript Version:** 

Errors: `3.3.0-dev.20181204`, `3.2.1`
Works: `3.1.6`

**Search Terms:**

3.2, SFC, React, default, params, value type, string

**Code**

```ts
import * as React from 'react';

type AorB = 'a' | 'b';

type Props1 = {
  aOrB: AorB;
}

type Props2 = {
  aOrB?: AorB;
}

export const Comp1: React.SFC<Props1> = () => null;

export const Comp2: React.SFC<Props2> = ({ aOrB = 'a' }) => <Comp1 aOrB={aOrB} />;
```

```
{
  "compilerOptions": {
    "jsx": "react",
    "noEmit": true
  }
}
```

```
{
  "name": "ts",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "type-check": "tsc"
  },
  "devDependencies": {
    "@types/react": "^16.7.13",
    "typescript": "3.x.x"
  }
}
```

**Expected behavior:**

For `3.1`:

```
$ yarn type-check
yarn run v1.12.3
$ tsc
✨  Done in 3.62s.
```

**Actual behavior:**

For `>=3.2`:

```
$ yarn type-check
yarn run v1.12.3
$ tsc
src/index.tsx:15:68 - error TS2322: Type 'string' is not assignable to type 'AorB'.

15 export const Comp2: React.SFC<Props2> = ({ aOrB = 'a' }) => <Comp1 aOrB={aOrB} />;
                                                                      ~~~~

  src/index.tsx:6:3
    6   aOrB: AorB;
        ~~~~
    The expected type comes from property 'aOrB' which is declared here on type 'IntrinsicAttributes & Props1 & { children?: ReactNode; }'


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Playground Link:** 

**Related Issues:**

### LINKED ISSUE #28963: Default values overwrite destructured function parameter type with basic type inference
**TypeScript Version:**  3.2.2 and 3.3.0-dev.20181211

**Search Terms:** destructure, parameters, default, assignment, overload, sfc, react, tsx

**Code**

```ts
interface SFC<P = {}> {
  (props: P & { children?: any }): any | null;
}

interface Props {
  name: "Apollo" | "Artemis" | "Dionysus" | "Persephone";
}

const Parent: SFC<Props> = ({
  children,
  name = "Artemis",
  ...props
}) => <Child name={name} {...props} />;

const Child: SFC<Props> = ({
  children,
  name = "Artemis",
  ...props
}) => <div {...props}>{name}</div>;
```

**Expected behavior:**
`name` should be type `"Apollo" | "Artemis" | "Dionysus" | "Persephone"`.

**Actual behavior:**
Assigning a default value for `name` overwrites the type to `string`.
```
index.tsx:13:23 - error TS2322: Type 'string' is not assignable to type '"Apollo" | 
"Artemis" | "Dionysus" | "Persephone"'.

13 }) => <Child name={name} {...props} />;
                ~~~~
```

**Playground Link:** 

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/27927 https://github.com/Microsoft/TypeScript/issues/28835 https://github.com/Microsoft/TypeScript/issues/18191

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #28963 
Fixes #28835

There were two issues at play. Contextual typing didn't recursively decompose types up the binding pattern tree, and `getTypeFromBindingPattern` didn't respect contextual types when deciding if it needed to union the initializer's type into the implied type of a binding element.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4849,7 +4849,7 @@ namespace ts {
             if (strictNullChecks && declaration.initializer && !(getFalsyFlags(checkDeclarationInitializer(declaration)) & TypeFlags.Undefined)) {
                 type = getTypeWithFacts(type, TypeFacts.NEUndefined);
             }
-            return declaration.initializer && !getEffectiveTypeAnnotationNode(walkUpBindingElementsAndPatterns(declaration)) ?
+            return declaration.initializer && !getEffectiveTypeAnnotationNode(walkUpBindingElementsAndPatterns(declaration)) && !getContextualTypeForVariableLikeDeclaration(walkUpBindingElementsAndPatterns(declaration)) ?
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Isn't the `!getEffectiveTypeAnnotationNode(...)` redundant here? It's the first thing checked in `getContextualTypeForVariableLikeDeclaration`.

Comment (weswigham) [reply src/compiler/checker.ts]: Mmm yes. I'll remove it.

Comment (weswigham) [reply src/compiler/checker.ts]: And it's gone~
