### PR TITLE
fix narrowTypeByDiscriminant for non null expression access

### LINKED ISSUE #52118: Minimum of 10 subtypes in union for correct type inferring with non-null assertion
# Bug Report

### 🔎 Search Terms

union type, limit, 10, optional, optional chaining, Non-null assertion, infer

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.5, but the root issue might be earlier

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.4.4&filetype=ts#code/C4TwDgpgBA6g9gJwNYEsB2BzAKuaBeKAbwCgopgALdDAfgC5SynCo0BDAWwjqgHIBRBAkQBGXgBooXAM7S2GblGnAE1KAF8oAH0ZMirTooFDEAJglSIs+YuWrMG7buYGuPY8IQBmCzLkKeOzVNHT0yFnY3PkFPABZfK39bFWCnMP1IoxjEAFYE6wClFIcQ53DXLJMEADZ8pMDijEdQsIjDd2yEAHY6mwb7JtL0tqiPRAAOXsKgkrTWio6qgE4p5IHmsoz2vgBhRAQIAGNgCxQAE37g4nUAbmJDuDRlKAB3RFRMHnhkahxIKAIREyi08Ykkfj6UAARBCFFDNGxpFAAK5oJBoOAvNBQRGwd6-XB3FAAMygAAo3j9MAA6SjUACE1MyUHpeAIUL2QiOwChAEoiIwHk84AAbCDUkVwDAU-E0umYRmwiC865QCAi6TQEhkIXSUXiyXSykfDC0qgK6nnXl3dTEO2gf4AIXeEDOf3wArI8toDGGC2iVTBlgKa1SLT0I0qnnM4MSkJmgzmEf9Y28q0us3DLmBAbi6aK6yG8xzqbysZDGcTWfKJc6tXL9QLYc2kZBiB6DfjjQ2ftrVUmnem3aLyZLnIOx1OFybJWud11wCgACMXdPnchXe6AUDtqmg0qeDC43CEUjUejMdjceukJvCcQSeSVxuzmaGUzDCy2dDx9y+Z6oF1fUJSlMln1vV9vUVY9lRtNUNS1QVHj1MUQOlcDXTfC0rRtO0IAADzARBFwdaAADEUHwu9-gIbVyHNH0WxTTp9xgyse2LXdOhjYNGwTDjRy4qofEHUNMyYvs81E9iR2zITPDLXiu0LJM5NGOt8342Sa3k9tNOHVSdPU-t9JU6stlGX9J0kc4ZKgZxbnuZDF2JSjXR4CiqLdXBtx3YzQXzI8Q3hHEzzRDEsVCqBPOoiA7gfUkyVcrysNoD8uC-dkrJ5fk6KA1DDSStzIIY6CQ2tVV1U1AD8oNUDksw71LTOCrbWIIA)

### 💻 Code

```ts
type MyType = {
  thing?:
      { name: 'Error1', message: string } |
      { name: 'Error2', message: string } |
      { name: 'Error3', message: string } |
      { name: 'Error4', message: string } |
      { name: 'Error5', message: string } |
      { name: 'Error6', message: string } |
      { name: 'Error7', message: string } |
      { name: 'Error8', message: string } |
//      { name: 'Error9', message: string } |
      { name: 'Correct', id: string }
};

const myObject: MyType =  {name: 'Error1', message: "message"} as unknown as MyType;
if (myObject.thing!.name !== "Correct") {
  console.log(myObject.thing!.message)
} else {
  console.log(myObject.thing!.id);
} 
```

The playground link contains a working example, broken example and workaround example.

### 🙁 Actual behavior

You get an error since the TS compiler is not able to infer from the first `if` that `myObject.thing` is either undefined or has a `message` field.

However, if you uncomment the 'Error9' line, which brings the items in the union to 10, the type inferring works correctly.
Also, if you change the non-null assertion of `myObject.thing` in the if statement to an optional chaining  operator, the inferring also works correctly.

I'm mainly surprised that it works in the case where the union exists of a lot of subtypes and not when it's simpler.

### 🙂 Expected behavior

The compiler can correctly infer types for smaller unions than of size 10.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #52118.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this faster
@typescript-bot user test this
@typescript-bot test top100

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -26299,7 +26300,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             if (propName === undefined) {
                 return type;
             }
-            const removeNullable = strictNullChecks && isOptionalChain(access) && maybeTypeOfKind(type, TypeFlags.Nullable);
+            const removeNullable = strictNullChecks && (isOptionalChain(access) || isNonNullAccess(access)) && maybeTypeOfKind(type, TypeFlags.Nullable);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:26303]: Here we remove `null` or `undefined` from the type, but then a few lines below we add back only an `undefined`. That reflects what happens in an optional chain, but the `!` operator never changes one to the other. It may not matter, but doesn't quite seem right.

Comment (gabritto) [reply src/compiler/checker.ts:26303]: I see, I had missed that. So I guess we shouldn't call `getOptionalType` below if it's a `!` operator, since `!` actually gets rid of `undefined` and `null`, unlike an optional chain.

Comment (gabritto) [reply src/compiler/checker.ts:26303]: @ahejlsberg I pushed the above change, let me know if it's not right or if there's something else missing.

**Review by ahejlsberg — APPROVED** [review]
