### PR TITLE
fix(46345): declare on computed class field with decorator makes invalid code that crashes due to missing _a

### LINKED ISSUE #46345: `declare` on computed class field with decorator makes invalid code that crashes due to missing `_a`
# Bug Report

### 🔎 Search Terms

decorator declare computed class field symbol

### 🕗 Version & Regression Information

- This is the behavior in every version I tried after the ability to add `declare` to class fields was introduced (so TypeScript 3.7+)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&emitDecoratorMetadata=false&ts=4.5.0-dev.20211013#code/GYVwdgxgLglg9mABAEwKYQBQGsA2BDAZwIC5E8wBPAGkTDwFtVTyKBKRAbwFgAoRRCAgJwcqAHQ44Acwx1GrXgF9egsASiIYBAMoV6AIxGIAvIl0GRGAORbzhnFYU8I+IogBicOJ178AAmgQKOj4AE6otHBQdiKkYCAGqKEA3L6IAejBLnjhiADatnr2ALpxCfpJqTzKPEA)

### 💻 Code

```ts
function dec(klass: any, name: any) {
  console.log(name)
}
const isSymbol = Symbol('isSymbol')
class Foo {
  @dec declare notSymbol: number;
  @dec declare [isSymbol]: number;
}
```

The context for this is that I recently became aware of the ability to add a decorator to a `declare` class field and I'm currently working on adding this feature to esbuild's TypeScript-to-JavaScript transformer, which doesn't currently support this feature. I discovered this bug in TypeScript while doing some reverse-engineering to figure out how the feature is supposed to work. See also https://github.com/evanw/esbuild/issues/1675.

### 🙁 Actual behavior

The code crashes when run with `Uncaught ReferenceError: _a is not defined`. This is because the TypeScript compiler transforms the input code into this:

```js
function dec(klass, name) {
    console.log(name);
}
const isSymbol = Symbol('isSymbol');
class Foo {
}
__decorate([
    dec
], Foo.prototype, "notSymbol", void 0);
__decorate([
    dec
], Foo.prototype, _a, void 0);
```

Notice how the declaration for the temporary variable `_a` was never actually generated.

### 🙂 Expected behavior

The code should print `notSymbol` followed by `Symbol(isSymbol)`. Presumably the generated code would need to look something like this:

```diff
+var _a;
 function dec(klass, name) {
     console.log(name);
 }
 const isSymbol = Symbol('isSymbol');
 class Foo {
 }
+_a = isSymbol;
 __decorate([
     dec
 ], Foo.prototype, "notSymbol", void 0);
 __decorate([
     dec
 ], Foo.prototype, _a, void 0);
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #46345

### CODE REVIEW

File: src/compiler/transformers/ts.ts [hunk 1]
```diff
@@ -1189,7 +1189,7 @@ namespace ts {
             //
 
             const prefix = getClassMemberPrefix(node, member);
-            const memberName = getExpressionForPropertyName(member, /*generateNameForComputedPropertyName*/ true);
+            const memberName = getExpressionForPropertyName(member, /*generateNameForComputedPropertyName*/ !hasSyntacticModifier(member, ModifierFlags.Ambient));
```
Comment (sandersn) [inline src/compiler/transformers/ts.ts:1192]: The test results look right to me, but I don't understand why non-ambient names need a generated name in the first place. Can you explain?

**Review by sandersn — CHANGES_REQUESTED** [review]
The test results look right to me, but I don't understand

File: src/compiler/transformers/ts.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/transformers/ts.ts:1192]: @sandersn If we're talking about _`ambient`_ context and decorators, I think we can avoid the new variables and use the original expression., because _`ambient`_ elements are skipped in JavaScript files. Maybe I'm wrong and we need to use a temp variable to store _computed property name for _`ambient`_ context  too 

Do you prefer to have the output for non-ambient names like this 

```ts
function dec(klass, name) {}
const isSymbol = Symbol('isSymbol');
class Foo {
}
__decorate([
    dec,
    __metadata("design:type", Number)
], Foo.prototype, isSymbol, void 0);
```

instead of 

```ts
var _a;
function dec(klass, name) {}
const isSymbol = Symbol('isSymbol');
class Foo {
}
_a = isSymbol;
__decorate([
    dec,
    __metadata("design:type", Number)
], Foo.prototype, _a, void 0);
```

Need to check this case, maybe there are cases in which a temporary variable is required to store a member name.

Comment (sandersn) [reply src/compiler/transformers/ts.ts:1192]: The first output looks better to me. But I'm not aware of complex emit cases the way @rbuckton is, so there might be some reason that the alias is needed.

Comment (rbuckton) [reply src/compiler/transformers/ts.ts:1192]: I think this is an acceptable change. There's no need to introduce a temp that is only used once.

**Review by rbuckton — APPROVED** [review]

**Review by sandersn — APPROVED** [review]
