### PR TITLE
Fix logic for determining whether to simplify keyof on mapped types

### LINKED ISSUE #44019: ConditionalRoot.isDistributive is buggy
# Bug Report

`ConditionalRoot.isDistributive` is a flag that indicates that a conditional "distributes" over union. Its set to true when the `checkType` is a `TypeParameter`. When its true, two main things happen:

 - `getIndexOfMappedType` converts `keyof { [ K in Keys as DistributiveConditional<K> ] : X }` to `DistributiveConditional<Keys>` which is clearly unsound in many cases (this is the bug reported in #43920).
 - `instantiateConditionalType` attempts to undo what it assumes `getIndexOfMappedType` did. This sometimes prevents bugs that `getIndexOfMappedType` would otherwise have introduced, but for other cases can break the conditional.

For the first case, here's a simplified version of the example from #43920

```
type KeysExtendedBy<T,U> = keyof {[K in keyof T as U extends T[K] ? K :never] : T[K]};
interface M {
  a: boolean;
  b: number;
}
function f(x : KeysExtendedBy<M,number>) {
  return x;
}
f("a"); // <- f should only accept "b" as a parameter.
```
Here, `getIndexOfMappedType` optimizes `KeysExtendedBy<T,U>` to `U extends T[keyof T] ? keyof T : never` (which is clearly wrong). And in this case, instantiateConditionalType can't fix it, because it only tries to spread on the checkType.

This can be fixed by adding a redundant guard:

```
type KeysExtendedBy<T,U> = keyof {[K in keyof T as T[K] extends unknown ? U extends T[K] ? K : never : never] : T[K]};
```

Now the top level conditional is not `isDistributive`, and we don't call `getIndexOfMappedType`.

For the second case:

```
type Bug<T, U> = U extends "a" ? T[U & keyof T] : never;
interface M {
  a: boolean;
  b: number;
}
function f(x : Bug<M, "a"|"b">) {
  return x;
}
f(false);
```

Clearly, `"a"|"b"` does not extend `"a"`, so `f`'s parameter type should be `never`. But `instantiateConditionalType` notes that `root.isDistributive` is set (since `U` is a `TypeParameter`), and that `checkType` is a union (the keys of M), and so it replaces the conditional with `("a" extends "a" ? M["a"] : never) | ("b" extends "a" ? M["b"] : never)` which reduces to `M["a"]` which is `boolean`.

I think these bugs show pretty conclusively that setting `isDistributive` whenever the `checkType` is a `TypeParameter` is broken. Perhaps only doing it when the checkType is a `MappedType`'s type parameter (ie the `K` above) would be safe; but even then I think it often relies on `instantiateConditionalType` to fix it. Consider eg:

```
type KeysExtendingLiteral<T> = keyof {
  [K in keyof T as K extends "b" ? K : never] : T[K];
}
interface M {
  a: boolean;
  b: number;
}
function f(x: KeysExtendingLiteral<M>) {
  return x;
}
f("b");
```

`KeysExtendingLiteral` gets converted to `keyof T extends "b" ? "b" & keyof T : never` (you can see this by hovering over KeysExtendingLiteral in line 8 of playground example 3) - which again, is not the same thing. The original should evaluate to "b" whenever T has a "b" field, and never otherwise. The modified version evaluates to never unless T has a "b" field, and no other fields. However, in this case, we *do* get the correct results - because `instantiateConditionalType` converts it back to a union of individual tests - ie `("a" extends "b" ? "b" & "a" : never)|("b" extends "b" ? "b" & "b" : never)`

My proposal is to rip out the isDistributive code altogether. The delicate dance where we first transform to an incorrect conditional, hope nobody notices, and then transform it back again at the end seems horribly unsound.

If this is really important for type inference, maybe the solution is to only call getIndexOfMappedType when the checkType is the MappedType's type parameter, and then set *another* flag to indicate the transformation was done, and have instantiateConditionalType check *that* flag. I'm not 100% convinced that's sound, but it should be much better than the current situation.

### 🔎 Search Terms

isDistributive

I found #43920 (my own report) which turns out to be a special case of the problems with isDistributive, and #30152 which appears to be a different problem.

### 🕗 Version & Regression Information

Its present on master, and has been since at least 4.1.5

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.

### ⏯ Playground Links

[Example 1](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIGcCiAPYEB2ATCWBCIAPACoA0AqgHxQC8UA1vAPYBmUA3gNoxQCWGDZm2JQAhgijkoENJiwTi3ALpQA-LCgAuDBABuEAE4rNURTCUBfANwBYAFD90BlqIDG0ALId7UMSYBGTEwANhCiGLZ2vv4mGACuALb+hpEW9ixxGK7AvEwCLAAUKFqw8Miy2LgEhB6k8UmGlACU3lFQBhDAcQYCKKnpBQBEooNNkUA)
[Example 2](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQgrgcwDwBUA0UCqA+KBeLKCAD2AgDsATAZygCIBDOqAfihQG1MoAyKAawggA9gDN2AXSgAuKOQgA3CACcA3AFgAUAEtyZZaIYBjaAFkoAby1QoDWQCNhwgDYQG5DZpv3Z5OAFt7FU8AXy1ROHIjYG1hcihRAApiGVhEJFMMRjoAHzp7OmwASktrKGUIYDhleOJQ8MTDZ2oIItUgA)
[Example 3](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIGcCiAPYEB2ATAlhg5gDI7oBOAhgDYA8AKgHxQC8UA1vAPYBmUA3gLAAoKFADaMKHjacetKOQSwoENJiyKARACMNUAPxKAXFAwQAbhFIBdKMdrirAbiEBfIXjJdyAY2gBZPiERcmMtDg5KCHIMZ2EoLWMMAFcAWy1LWLdBLiSMb2AcDgwoLgAKFGM4RFR0bDwiEksqaj96AEpAuNIIYCTSYpRMoTLtDTbYoA)

### 💻 Code

```
type KeysExtendedBy<T,U> = keyof {[K in keyof T as U extends T[K] ? K : never] : T[K]};
interface M {
  a: boolean;
  b: number;
}
function f(x : KeysExtendedBy<M,number>) {
  return x;
}
f("a");
```

### 🙁 Actual behavior

The call to f("a") is deemed correct

### 🙂 Expected behavior

It should fail because `number` does not extend `M["a"]` which is boolean, so "a" should not be included in the keys of the mapped type (and note that it *isn't* included in the mapped type itself).

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #44019.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14250,16 +14250,23 @@ namespace ts {
...
+        // introduced by the 'in' clause of the mapped type. Note that non-generic types are considered to be distributive because
+        // they're the same type regardless of what's being distributed over.
+        function hasDistributiveNameType(mappedType: MappedType) {
+            const typeVariable = getTypeParameterFromMappedType(mappedType);
+            return isDistributiveForTypeParameter(getNameTypeFromMappedType(mappedType) || typeVariable);
+            function isDistributiveForTypeParameter(type: Type): boolean {
+                return type.flags & TypeFlags.TypeParameter ? type === typeVariable :
+                    type.flags & TypeFlags.Conditional ? (<ConditionalType>type).root.isDistributive && isDistributiveForTypeParameter((<ConditionalType>type).checkType) :
+                    type.flags & (TypeFlags.UnionOrIntersection | TypeFlags.TemplateLiteral) ? every((<UnionOrIntersectionType | TemplateLiteralType>type).types, isDistributiveForTypeParameter) :
+                    type.flags & TypeFlags.IndexedAccess ? isDistributiveForTypeParameter((<IndexedAccessType>type).indexType) :
```
Comment (weswigham) [inline src/compiler/checker.ts:14264]: Can't the object type also essentially pass thru distrubutivity? Since `(A | B)["x"]` is identical to `A["x"] | B["x"]` (for reading, at least)?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14250,16 +14250,23 @@ namespace ts {
...
+                    type.flags & TypeFlags.Substitution ? isDistributiveForTypeParameter((<SubstitutionType>type).substitute) :
+                    type.flags & TypeFlags.StringMapping ? isDistributiveForTypeParameter((<StringMappingType>type).type) :
+                    type.flags & TypeFlags.Index ? false :
```
Comment (weswigham) [inline src/compiler/checker.ts:14267]: What about, eg, `keyof {[_ in T]: whatever}`? That's still essentially distributive over T since it should just be `T` (T just has to be constrained to valid key types).

**Comment by ahejlsberg** [comment]
Some background on the change in this PR...

For a type `keyof { [K in X as Y]: ... }` we want to determine if it is correct to simplify to an instantiation of `Y` with `X` substituted for `K`. Let's say `X` is a union type `'a' | 'b' | 'c'`. Without simplification, the `keyof` operation becomes a union of three instantiations of `Y` with `'a'`, `'b'`, and `'c'` respectively substituted for `K`. We want to determine if it is correct to simplify to a single instantiation of `Y` with `'a' | 'b' | 'c'` substituted for `K`, which it will be when `Y` distributes over union types in `K`. A complication is that we can't always inspect every constituent of `Y` because it might be circular or infinitely expanding. So, for some types we can't easily provide an answer. However, unless we can prove otherwise, it is reasonable to assume that `Y` depends on `K` _in some way_, or else the entire construct is just a needlessly complicated way of writing just `Y`. 

With that in mind, the best approach is to not simplify unless we can definitely prove a type to be distributive. Originally the code was doing it the other way around (assuming distributive and attempting to prove otherwise), but that meant we'd get it wrong in cases where the analysis was incomplete.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -14250,16 +14250,23 @@ namespace ts {
...
-                type.flags & TypeFlags.Substitution && maybeNonDistributiveNameType((<SubstitutionType>type).substitute)));
+        // that N distributes over union types, i.e. that N<A | B | C> is equivalent to N<A> | N<B> | N<C>. Specifically, we only
+        // want to perform the reduction when the name type of a mapped type is distributive with respect to the type variable
+        // introduced by the 'in' clause of the mapped type. Note that non-generic types are considered to be distributive because
+        // they're the same type regardless of what's being distributed over.
+        function hasDistributiveNameType(mappedType: MappedType) {
+            const typeVariable = getTypeParameterFromMappedType(mappedType);
+            return isDistributiveForTypeParameter(getNameTypeFromMappedType(mappedType) || typeVariable);
+            function isDistributiveForTypeParameter(type: Type): boolean {
+                return type.flags & TypeFlags.TypeParameter ? type === typeVariable :
```
Comment (markw65) [inline src/compiler/checker.ts:14261]: Not a bug per se, but isn't this check too strict? eg it causes

```
type NotDistributive<T, U, V = string> = keyof { [ K in keyof T as V & (K extends U ? K : never)]: T[K]};
```

to fail the `isDistributiveForTypeParameter`, because `V` is rejected by the `every` call.

Maybe add a flag to `isDistributiveForTypeParameter` saying whether or not you're under a checkType, default it to false (for the initial call, and the `every` call), pass true for the checkType call, and pass it through for the other cases?

File: src/compiler/checker.ts (hunk 1 above)
Comment (markw65) [reply src/compiler/checker.ts:14264]: Isn't that exactly what this does? It completely ignores the object type.

File: src/compiler/checker.ts (hunk 2 above)
Comment (markw65) [reply src/compiler/checker.ts:14267]: Isn't that handled by `getNameTypeFromMappedType(mappedType) || typeVariable` in the original call to `isDistributiveForTypeParameter`? If there's no NameType, `typeVariable` will immediately pass the check.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: With latest commit we now check both `objectType` and `indexType`.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -14250,16 +14250,23 @@ namespace ts {
...
+                    type.flags & TypeFlags.Conditional ? (<ConditionalType>type).root.isDistributive && isDistributiveForTypeParameter((<ConditionalType>type).checkType) :
+                    type.flags & (TypeFlags.UnionOrIntersection | TypeFlags.TemplateLiteral) ? every((<UnionOrIntersectionType | TemplateLiteralType>type).types, isDistributiveForTypeParameter) :
+                    type.flags & TypeFlags.IndexedAccess ? isDistributiveForTypeParameter((<IndexedAccessType>type).indexType) :
+                    type.flags & TypeFlags.Substitution ? isDistributiveForTypeParameter((<SubstitutionType>type).substitute) :
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Not necessary with the latest changes.

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: A `keyof { [_ in T]: xxx }` will, if possible, already have been simplified by `getIndexType`.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Agreed, fixed in the latest commit.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -14333,16 +14333,25 @@ namespace ts {
...
+                return type.flags & TypeFlags.Conditional ? (type as ConditionalType).root.isDistributive && isDistributiveCheckType((type as ConditionalType).checkType) :
+                    type.flags & (TypeFlags.UnionOrIntersection | TypeFlags.TemplateLiteral) ? every((type as UnionOrIntersectionType | TemplateLiteralType).types, isDistributive) :
+                    type.flags & TypeFlags.IndexedAccess ? isDistributive((type as IndexedAccessType).objectType) && isDistributive((type as IndexedAccessType).indexType) :
+                    type.flags & TypeFlags.Substitution ? isDistributive((type as SubstitutionType).substitute) :
+                    type.flags & TypeFlags.StringMapping ? isDistributive((type as StringMappingType).type) :
+                    true;
+            }
+            function isDistributiveCheckType(type: Type): boolean {
+                return !!(type.flags & TypeFlags.TypeParameter) && type === typeVariable ||
+                    !!(type.flags & TypeFlags.Conditional) && (type as ConditionalType).root.isDistributive && isDistributiveCheckType((type as ConditionalType).checkType);
```
[the remark this answers is not in the document]
Comment (markw65) [reply src/compiler/checker.ts:14353]: [Here's a full test case](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIglgZ2AHgKoBooDVMHVMAaAfFALxSpQQAewEAdgCYLZQD8UuUAXFAQNwBYAFChIUANIQQAewBmAWQCGYSI2QAVTKhLkA1tPlQA3lADakqHHpQDsuVA1QlLeEmQSqtBswrtHZhIAujxQ9BAAbhAATpgagUGYEpjhUdEkQbzxwVAAvkLC1nTRckoAxtAKJiJQzrwARjIyADYQSvQFtfW89ACuALb1MQW5InK99GXAcDI2cgAU1KFS9sqqEOoKmABESttEAJTVwrXREMC90TbUI2Pz2-XbB-xAA).

It *should* reject the call to f, but accepts it instead. The playground accepts it, and this fix also accepts it. If I remove line 14353 from your fix, it correctly rejects it.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -14333,16 +14333,25 @@ namespace ts {
...
+        function hasDistributiveNameType(mappedType: MappedType) {
+            const typeVariable = getTypeParameterFromMappedType(mappedType);
+            return isDistributive(getNameTypeFromMappedType(mappedType) || typeVariable);
+            function isDistributive(type: Type): boolean {
+                return type.flags & TypeFlags.Conditional ? (type as ConditionalType).root.isDistributive && isDistributiveCheckType((type as ConditionalType).checkType) :
+                    type.flags & (TypeFlags.UnionOrIntersection | TypeFlags.TemplateLiteral) ? every((type as UnionOrIntersectionType | TemplateLiteralType).types, isDistributive) :
+                    type.flags & TypeFlags.IndexedAccess ? isDistributive((type as IndexedAccessType).objectType) && isDistributive((type as IndexedAccessType).indexType) :
+                    type.flags & TypeFlags.Substitution ? isDistributive((type as SubstitutionType).substitute) :
+                    type.flags & TypeFlags.StringMapping ? isDistributive((type as StringMappingType).type) :
+                    true;
```
[the remark this answers is not in the document]
Comment (markw65) [reply src/compiler/checker.ts:14349]: In fact, [another test case](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIHsBmBZAhmSATAPAFQBooBVAPigF4oBreZKAbygG1YoBLAOxrqSjyhoAzj0R8AFA2YAFDtxiCReGQF0oEAB7AInLCOJQA-GwBcUThABuEAE4qzwGwFcIAXwCUUe-2Yw1rgG4AWAAoLm0bJDQAY2gURlCoQTMAIwQEABsINE5gkKSUs04nAFsU2zzXUKQnTmjgdgRuJHENMzgxdEwIXBQiNMzszlJPBkSoGwhgJxtuDUrq8QAiFKX3AKA). Again, it should reject the call to f, but fails to do so in the playground, and fails to do so after this fix.

Changing line 14349 to `!(type.flags & TypeFlags.Index)` fixes this particular test case, but if we're trying to be conservative `false` would be better. Or maybe `!!(type.flags & TypeFlags.Primitive)` to avoid being overly conservative

[the remark this answers is not in the document]
Comment (markw65) [reply src/compiler/checker.ts:14349]: Sorry, not sure what's going on with the playground links - they seem to randomly link to other test cases I've been playing with. In case its behaving in a similar way for you, here's the code I'm trying to link to:

```
type KeyofMapped<T, U> = keyof { [ K in keyof T as keyof ({[P in K as T[P] extends U ? K : never]: true}) ]: T[K] };
interface M {
  a: boolean;
  b: number;
}
function f(x: KeyofMapped<M, boolean>) {
  return x;
}
f("b");
```

File: src/compiler/checker.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (markw65) [reply src/compiler/checker.ts:14353]: Similarly, here's the code I'm trying to link to for this example:
```
type Dist<U, V, W, X> = U extends V ? W : X;
type KeyofMapped<T, U> = keyof { [ K in keyof T as Dist<K extends U ? T[K] : never, T[K], K, never> ]: T[K] };
interface M {
  a: boolean;
  b: number;
}
function f(x : KeyofMapped<M, "a">) {
  return x;
}
f("b");
```

**Review by markw65 — COMMENTED** [review]
I have a higher level question: why do this transformation at all?

If it's done correctly (and we seem to be seeing that that's actually quite hard), it won't change the behavior, so it doesn't appear to be *necessary*. Is it supposed to be speeding up the compilation step by simplifying the expression? In that case, its not clear to me that it's a win.

Typically I will have 

```
type MakeMappedType<Args> = { ... };
type KeyofMappedType<Args> = keyof MakeMappedType<Args>;
```

And then I will always use them in pairs - ie for every set of Args that I instantiate KeyofMappedType, I will also instantiate MakeMappedType (or I won't even bother with KeyofMappedType, and just use `keyof MakeMappedType` directly). Assuming my usage model is typical, there doesn't seem to be a win, since without the transformation, `keyof MakeMappedType` would just read the property keys from the already-instantiated mapped type.

File: src/compiler/checker.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts:14349]: With latest commits now errors as expected.

File: src/compiler/checker.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts:14353]: Similarly, with latest commits now errors as expected.

**Comment by ahejlsberg** [comment]
@markw65 Thanks for the latest tests which should now work as expected.

WRT why we do this transformation in the first place, the short answer is: In order to ensure types that are expected to be compatible actually are compatible. For example

```ts
type T1<T> = keyof T & string;
type T2<T> = keyof { [P in keyof T as P & string]: number };
```

You'd expect these two types to be compatible since they'll always have the same sets of properties, but they wouldn't be without the simplification.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by markw65** [comment]
> You'd expect these two types to be compatible since they'll always have the same sets of properties, but they wouldn't be without the simplification.

@ahejlsberg Sorry, would you mind clarifying that? Maybe with an example, or an explanation of what I'm doing wrong here:

```
type T1<T> = (keyof T) & string;
type T2<T> = keyof { [P in keyof T as P & string]: number };
//type T2<T> = keyof { [P in keyof T as [P] extends [P] ? P & string : never]: number };

interface M {
    a: number;
    b: number;
    [42]: number;
}

function f1(x: T1<M> extends T2<M> ? boolean : never) {
    return x;
}
function f2(x: T2<M> extends T1<M> ? boolean : never) {
    return x;
}
function f3(x: T1<M> extends T2<M> ? (T2<M> extends T1<M> ? boolean : never) : never) {
    return x;
}
f1(false);
f2(false);
f3(false);
```
In the above code, `f1` and `f2` both take `boolean` arguments, which *seems* to indicate that (as you said) T1 and T2 produce compatible types (each extends the other). But if I try to combine the tests, in `f3` it *doesn't* take boolean (it also doesn't tell me what it *does* take).

If I change the definition of `T2` so that the transformation doesn't happen, I get exactly the same behavior (ie, I believe, based on `f1` and `f2`, that the types are still compatible; but something odd happens in the `f3` case).

**Comment by ahejlsberg** [comment]
@markw65 It works because `T1<M>` and `T2<M>` both resolve to the union type `'a' | 'b'` in your example, so by the time we relate the types they're actually the same type. However, things don't work out if `M` is generic because the types are then preserved in their higher order form. So, adding to your example:

```ts
function foo1(x: T1<M>, y: T2<M>) {
    x = y;  // Ok
    y = x;  // Ok
}

function foo2<M>(x: T1<M>, y: T2<M>) {
    x = y;  // Error in non-simplified case
    y = x;  // Error in non-simplified case
}
```

**Comment by markw65** [comment]
@ahejlsberg Thanks. That makes sense. But in that case, it seems like its not really ok to be conservative about when to do the transformation? eg right now it would reject

```
type NotTransformed<T, U, V, W> = keyof { [K in keyof T as U extends V ? (K extends W ? K : never) : K]: T[K] }; 
```

even though it *is* distributive wrt K.

Can you explain what's going on with f3's parameter type? We know that `T1<M> extends T2<M>` and that `T2<M> extends T1<M>`, so the nested conditional *should* evaluate to `boolean`, but it doesn't seem to. Is that a bug? Or am I doing something stupid here? The really weird thing is that if I change it to `T1<M> extends T2<M> ? (T2<M> extends T1<M> ? true : false) : 42`, then f3 doesn't accept `true`, `false` *or* `42` as its parameter:

```
foo.ts:32:4 - error TS2345: Argument of type 'boolean' is not assignable to parameter of type '"a" | "b" extends T1<M> ? true : false'.
```
