### PR TITLE
#13063 Fix strictNullChecks breaking typeof

### LINKED ISSUE #13063: strictNullChecks breaks typeof
**TypeScript Version:**  2.1.4

**Code**
```ts
let a: number
let b: typeof a // [ts] Variable 'a' is used before being assigned.
```
tsconfig.json: 
```js
{ "compilerOptions": { "strictNullChecks": true } }
```
**Expected behavior:**
No errors, like `"strictNullChecks": false`
**Actual behavior:**
`typeof` wants variable to be assigned

### PR DESCRIPTION
**Pull request by slawomir**
Fixes #13063

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -10372,7 +10372,7 @@ namespace ts {
             // the entire control flow graph from the variable's declaration (i.e. when the flow container and
             // declaration container are the same).
             const assumeInitialized = isParameter || isOuterVariable ||
-                type !== autoType && type !== autoArrayType && (!strictNullChecks || (type.flags & TypeFlags.Any) !== 0) ||
+                type !== autoType && type !== autoArrayType && (!strictNullChecks || isInTypeQuery(node) || (type.flags & TypeFlags.Any) !== 0) ||
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Please put this condition last in the `||` chain - we want the faster checks first and `isInTypeQuery` has to walk up the entire tree

Comment (slawomir) [inline src/compiler/checker.ts]: @RyanCavanaugh updated pull request
