### PR TITLE
`this` in object literals intersects contextual type and literal type

### LINKED ISSUE #8191: Incorrect/overly strong `this` inference for POJOs
**TypeScript Version:** 

nightly (1.9.0-dev.20160419)

**Code**

```ts
Ember.Object.extend({
  init() {
    this._super();
//  ^~~~ error TS2339: Property '_super' does not exist on type '{ init(): void; }'.
    ...
  }
});
```

**Expected behavior:**

`this` should be inferred as `any`

**Actual behavior:**

`this` is inferred to be `{ init(): void; }`

* * *

This changed somewhere between `typescript@1.9.0-dev.20160319` and `typescript@1.9.0-dev.20160419`. I believe it is unsafe to assume anything about the `this` on the "methods" on a POJO, as there are several common patterns in JavaScript that breaks this assumption (using POJOs as an "options" or "extensions" dictionary).

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #8191 

1. If there is a contextual type and an object literal type for an object literal, intersect them.
2. If the contextual type of a function is `any`, its contextual `this` type is now `any` as well.
3. Make Salsa detection of `x.prototype.y = function () { ... }` pattern override the contextual type.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8450,6 +8453,12 @@ namespace ts {
             if ((isFunctionExpressionOrArrowFunction(func) || isObjectLiteralMethod(func)) &&
                 isContextSensitive(func) &&
                 func.kind !== SyntaxKind.ArrowFunction) {
+                const type = isObjectLiteralMethod(func)
```
Comment (mhegazy) [inline src/compiler/checker.ts]: this logic is duplicated between here and getContextualSignature. consider refactoring it.

File: tests/cases/conformance/types/thisType/thisTypeInFunctions2.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
+interface Arguments {
```
Comment (mhegazy) [inline tests/cases/conformance/types/thisType/thisTypeInFunctions2.ts]: can you add a test that does not have this, something with `[propName : string]:any`

Comment (mhegazy) [inline tests/cases/conformance/types/thisType/thisTypeInFunctions2.ts]: also a test for the contextual type of the object literal, without the `this:any`

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -8190,9 +8205,13 @@ namespace ts {
...
-                    const type = checkExpressionCached(<ObjectLiteralExpression>container.parent);
-                    if (type) {
-                        return type;
+                    const contextualType = getContextualType(container.parent as ObjectLiteralExpression);
+                    const literalType = checkExpressionCached(<ObjectLiteralExpression>container.parent);
+                    if (contextualType && literalType) {
+                        return getIntersectionType([contextualType, literalType]);
+                    }
+                    else if (contextualType || literalType) {
+                        return contextualType || literalType;
```
Comment (mhegazy) [inline src/compiler/checker.ts]: do not think we have a test for this.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -8190,9 +8205,13 @@ namespace ts {
                 if (container.parent && container.parent.kind === SyntaxKind.ObjectLiteralExpression) {
                     // Note: this works because object literal methods are deferred,
                     // which means that the type of the containing object literal is already known.
-                    const type = checkExpressionCached(<ObjectLiteralExpression>container.parent);
-                    if (type) {
-                        return type;
+                    const contextualType = getContextualType(container.parent as ObjectLiteralExpression);
+                    const literalType = checkExpressionCached(<ObjectLiteralExpression>container.parent);
+                    if (contextualType && literalType) {
+                        return getIntersectionType([contextualType, literalType]);
```
Comment (mhegazy) [inline src/compiler/checker.ts]: do we still need this?

Comment (mhegazy) [inline src/compiler/checker.ts]: what is the scenario that is not covered by the other change?

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]: done, although it still does the work twice in the case that there is no contextualSignature.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [inline src/compiler/checker.ts]: You're right, I can't write a test that actually gets the intersection any more. I'll remove it.

**Comment by sandersn** [comment]
OK, I changed the behaviour of contextual signatures that don't define `thisType`. Now an undefined `thisType` causes the contextual type of `this` to be `any`. Previously it would cause the contextual type to be undefined, so `checkThisExpression` would keep looking for a type for `this`.

@mhegazy I think this is a good compromise. Can you take a look?

**Comment by sandersn** [comment]
Also `npm install` failed in the Travis build. I guess npm is down? Or something?

**Comment by mhegazy** [comment]
@yuit published then unpublished a package.

**Comment by mhegazy** [comment]
:+1:
