### PR TITLE
Do not lowercase typeReference directive name

### LINKED ISSUE #45096: lowercase filename in triple slash directives
# Bug Report
Referencing a file name in triple slash directives automatically looks for the lower case filename

### 🔎 Search Terms
- triple slash directive
- lowercase filename

### 🕗 Version & Regression Information
have seen it since ts > 3.x

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about triple slash directives / lowercase filename

### ⏯ Playground Link
not sure how to reproduce it in the playground
This requires multiple files, and there is no easy way to verify

### 💻 Code
```
// fileOne.d.ts
...
...
```

```
// file2.d.ts
// <reference types="../fileOne.d.ts">
...
...
```

### 🙁 Actual behavior
on case sensitive OS, i got a warning from tscompiler about the casing being incorrect.

### 🙂 Expected behavior
should not get this warning

More Info:
I guess this is related to https://github.com/microsoft/TypeScript/issues/26948
and it seems this is correct behaviour.

If that is the case, it would be great to document it alongside triple slash directives or add it to FAQs
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

### PR DESCRIPTION
**Pull request by sheetalkamat**
As part of https://github.com/microsoft/TypeScript/issues/9824 all type reference directives are lower cased so type="somePackage" results in looking for type reference of somepackage instead.

We also did not lowercase file names found as part of auto type references. So there was always some descripency with how we handled typeRef. Now with this change, it's as written.

I reverted that part and only kept the jsTypings to do the lowercasing to find the `@types` packages to install. 
This fixes issues with `forceConsistentCasingInFileNames` esp when using relative paths in `types` reference. 

#26948 becomes absolute with this 
Fixes #45096

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot test tsserver top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

File: tests/baselines/reference/tsserver/typeReferenceDirectives/when-typeReferenceDirective-contains-UpperCasePackage.js [hunk 1]
```diff
@@ -117,7 +166,6 @@ Info seq  [hh:mm:ss:mss] 	Files (4)
 	  Matched by default include pattern '**/*'
 	../lib/@types/UpperCasePackage/index.d.ts
 	  Entry point for implicit type library 'UpperCasePackage'
-	  Type library referenced via 'UpperCasePackage' from file '../lib/@app/lib/index.d.ts'
```
Comment (sheetalkamat) [inline tests/baselines/reference/tsserver/typeReferenceDirectives/when-typeReferenceDirective-contains-UpperCasePackage.js:120]: This stops showing as this because of how this is processed. When the `UpperCasePackage` typings are already found and are primary then they are not processed again and hence the file reason for this is never added. Thats a separate issue and am looking into updating that code as well but its not related to this change. 

it just stopped showing because before this the package name by auto type ref was "UpperCasePackage" while by type Ref was "uppercasepackage" which made two distinct entries and hence processed again.

**Review by andrewbranch — APPROVED** [review]
This seems correct, but it also seems like a lot of people in the linked issue are misusing type reference directives. They’re not really supposed to resolve to files, right? They should be package directories in `typeRoots`?

**Comment by sheetalkamat** [comment]
Yes they are but given that we dont disallow relative names in the `type` it just seems like something we shouldnt do. I mean we shouldnt be in buisness of "lowercasing". Please write what you mean. So i feel like this is better change. 

We started doing this because of "Jquery.min" etc files and some other auto type Aquisition issues. But if you write "types" in your file, write it with correct casing is logical i think.
