### PR TITLE
Fix crash in getTextOfPropertyName

### LINKED ISSUE #29006: TypeError: Cannot read property 'charCodeAt' of undefined @ isLateBoundName
**TypeScript Version:**  3.3.2 (tried latest `next` and issue still existed)

**Search Terms:**
charCodeAt, isLateBoundName

**Code**
```ts
export interface A { type: 'a' }
export interface B { type: 'b' }
export type AB = A | B

const itemId = 'some-id'

// --- test on first level ---
const items: { [id: string]: AB } = {}
const { [itemId]: itemOk1 } = items
typeof itemOk1 // pass

// --- test on second level ---
interface ObjWithItems {
    items: {[s: string]: AB}
}
const objWithItems: ObjWithItems = { items: {}}

const itemOk2 = objWithItems.items[itemId]
typeof itemOk2 // pass

const {
    items: { [itemId]: itemWithTSError } = {} /*happens when default value is provided*/
} = objWithItems

// in order to re-produce the error, uncomment next line:
// typeof itemWithTSError // :(

// will result in:
// Error from compilation: TypeError: Cannot read property 'charCodeAt' of undefined  TypeError: Cannot read property 'charCodeAt' of undefined
```

**Expected behavior:**
No crash.

**Actual behavior:**
Crashes with TypeError mid-compilation:
```
TypeError: Cannot read property 'charCodeAt' of undefined
    at isLateBoundName (...\typescript.js:36537:25)
    at createUnionOrIntersectionProperty (...\typescript.js:37624:42)
    at getUnionOrIntersectionProperty (...\typescript.js:37690:28)
    at getPropertyOfUnionOrIntersectionType (...\typescript.js:37698:28)
    at getPropertyOfType (...\typescript.js:37731:24)
    at getTypeOfPropertyOfType (...\typescript.js:35017:24)
    at getTypeOfDestructuredProperty (...\typescript.js:44548:45)
    at getInitialTypeOfBindingElement (...\typescript.js:44613:17)
    at getInitialType (...\typescript.js:44641:17)
    at getInitialOrAssignedType (...\typescript.js:44645:17)
```
**Playground Link:** 
https://www.typescriptlang.org/play/#src=export%20interface%20A%20%7B%20type%3A%20'a'%20%7D%0D%0Aexport%20interface%20B%20%7B%20type%3A%20'b'%20%7D%0D%0Aexport%20type%20AB%20%3D%20A%20%7C%20B%0D%0A%0D%0Aconst%20itemId%20%3D%20'some-id'%0D%0A%0D%0A%2F%2F%20---%20test%20on%20first%20level%20---%0D%0Aconst%20items%3A%20%7B%20%5Bid%3A%20string%5D%3A%20AB%20%7D%20%3D%20%7B%7D%0D%0Aconst%20%7B%20%5BitemId%5D%3A%20itemOk1%20%7D%20%3D%20items%0D%0Atypeof%20itemOk1%20%2F%2F%20pass%0D%0A%0D%0A%2F%2F%20---%20test%20on%20second%20level%20---%0D%0Ainterface%20ObjWithItems%20%7B%0D%0A%20%20%20%20items%3A%20%7B%5Bs%3A%20string%5D%3A%20AB%7D%0D%0A%7D%0D%0Aconst%20objWithItems%3A%20ObjWithItems%20%3D%20%7B%20items%3A%20%7B%7D%7D%0D%0A%0D%0Aconst%20itemOk2%20%3D%20objWithItems.items%5BitemId%5D%0D%0Atypeof%20itemOk2%20%2F%2F%20pass%0D%0A%0D%0Aconst%20%7B%0D%0A%20%20%20%20items%3A%20%7B%20%5BitemId%5D%3A%20itemWithTSError%20%7D%20%3D%20%7B%7D%20%2F*happens%20when%20default%20value%20is%20provided*%2F%0D%0A%7D%20%3D%20objWithItems%0D%0A%0D%0A%2F%2F%20in%20order%20to%20re-produce%20the%20error%2C%20uncomment%20next%20line%3A%0D%0A%2F%2F%20typeof%20itemWithTSError%20%2F%2F%20%3A(%0D%0A%0D%0A%2F%2F%20will%20result%20in%3A%0D%0A%2F%2F%20Error%20from%20compilation%3A%20TypeError%3A%20Cannot%20read%20property%20'charCodeAt'%20of%20undefined%20%20TypeError%3A%20Cannot%20read%20property%20'charCodeAt'%20of%20undefined

**Related Issues:** 
Looks similar to https://github.com/Microsoft/TypeScript/issues/26321

### PR DESCRIPTION
**Pull request by rbuckton**
This addresses one of the instances of #18217 where we were returning `undefined!`.

Fixes #29006

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15059,7 +15066,10 @@ namespace ts {
         }
 
         function getTypeOfDestructuredProperty(type: Type, name: PropertyName) {
-            const text = getTextOfPropertyName(name);
+            const text = !isComputedNonLiteralName(name) ? getTextOfPropertyName(name) :
```
Comment (sandersn) [inline src/compiler/checker.ts]: Looks like there are now 2 positive uses of isComputedNonLiteralName to 4 negative uses. Since the name is already clunky, I think an inverted name like "isNormalName" or something is better. (We might need a new term for this kind of name.)

Comment (sandersn) [reply src/compiler/checker.ts]: It's unfortunate that getTextOfPropertyName can't delegate to getLateBoundName due to the variety of uses (at least in this PR). Maybe there is some way to unify them.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -22201,8 +22209,8 @@ namespace ts {
         function checkObjectLiteralDestructuringPropertyAssignment(objectLiteralType: Type, property: ObjectLiteralElementLike, allProperties?: NodeArray<ObjectLiteralElementLike>, rightIsThis = false) {
             if (property.kind === SyntaxKind.PropertyAssignment || property.kind === SyntaxKind.ShorthandPropertyAssignment) {
                 const name = property.name;
-                const text = getTextOfPropertyName(name);
```
Comment (sandersn) [inline src/compiler/checker.ts]: for example, it would be nice to not have to change this code, and get `undefined` for names for which isComputedNonLiteralName is true.

File: src/compiler/checker.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/checker.ts]: The big question is whether we always want to get the late bound name in these cases. One option we might have is to stop using `getTextOfPropertyName` altogether and instead use `getLiteralTypeFromPropertyName` and pass that through `getLateBoundNameFromType` (which would work for non-late-bound names as well, and could possibly be renamed).

**Comment by rbuckton** [comment]
@RyanCavanaugh do you want this in master ahead of the release-3.3 merge, or should I hold off until next week?

**Comment by weswigham** [comment]
I'd personally hope that since it's a crash fix that we can have it in 3.3.

**Comment by joshuaaron** [comment]
Looking forward to this. When could we expect a 3.3 release @weswigham? Currently holding off TS^3 due to this and causing issues with other packages.
