### PR TITLE
Fixes broken emit with useDefineForClassFields + private field

### LINKED ISSUE #35590: 3.7.3 regression: useDefineForClassFields + private = broken emit
**TypeScript Version:**  3.8.0-dev.20191207

**Search Terms:** `usedefineforclassfields` `private`

**Code**

```ts
// enable --useDefineForClassFields

class C {
    private foo: number;
    constructor() { this.foo = 0; }
}

new C();
```

**Expected behavior:**
Code works properly at runtime.

**Actual behavior:**
Code throws at runtime because the emit for an uninitialized private field is:
```ts
        Object.defineProperty(this, "foo", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: foo
        });
```

`foo` is being initialized to `foo`, which of course doesn't exist!

This is a regression in TypeScript 3.7.3, discovered after updating.  I spent about 10 minutes stepping through the debugger looking for the source of the runtime exception before I finally thought to check the emitted JS and discovered it was invalid.

**Playground Link:** 
https://www.typescriptlang.org/play/?useDefineForClassFields=true&ts=3.8.0-dev.20191207&ssl=1&ssc=1&pln=5&pc=1#code/PTAEFMDsEMCMBtygKoGdwBFwDMCWlwAxAewCcBheaVVQ3ceAE1QFgAoAYyptHNAG92oYaAAOpXADdoAFyTZixAFyhIAVwC2scKQDcQkR2KRUM0mo4yyACgCUA0DIAWuVADoFxUAF5QABl1QAF92ELZ2AgB3Xjt9NiA

**Related Issues:** 
Couldn't find anything that seemed relevant.

### PR DESCRIPTION
**Pull request by hikarinotomadoi**
Add check for whether the class property is originated from a parameter.
Fixes #35590

### CODE REVIEW

File: src/compiler/transformers/classFields.ts [hunk 1]
```diff
@@ -778,7 +778,7 @@ namespace ts {
             }
 
             const initializer = property.initializer || emitAssignment ? visitNode(property.initializer, visitor, isExpression)
-                : hasModifier(getOriginalNode(property), ModifierFlags.ParameterPropertyModifier) && isIdentifier(propertyName) ? propertyName
+                : hasModifier(getOriginalNode(property), ModifierFlags.ParameterPropertyModifier) && isIdentifier(propertyName) && isParameter(getOriginalNode(property)) ? propertyName
```
Comment (ajafff) [inline src/compiler/transformers/classFields.ts]: suggestion: you can replace the whole condition with `isParameterPropertyDeclaration(getOriginalNode(property))`

Comment (fatcerberus) [reply src/compiler/transformers/classFields.ts]: I'm not that familiar with the TS codebase but that sounds like it would be equivalent to `hasModifier(getOriginalNode(property), ModifierFlags.ParameterPropertyModifier)`?

Comment (ajafff) [reply src/compiler/transformers/classFields.ts]: It also checks that the parent is a constructor declaration.

**Comment by sandersn** [comment]
Thanks for the fix @hikarinotomadoi !
