### PR TITLE
Fix conditional type type parameter leak

### LINKED ISSUE #31402: Inference of constrained generic causes open generic to "escape"
**TypeScript Version:**  3.5.0-dev.20190514

**Search Terms:**
constrained generic inference infer keyword
infer open generic
infer constrained generic

**Code**

```ts
interface Synthetic<A, B extends A> {}
type SyntheticDestination<T, U> = U extends Synthetic<T, infer V> ? V : never;
type TestSynthetic = // Resolved to T
    SyntheticDestination<number, Synthetic<number, number>>;

const w: TestSynthetic = undefined // ✓
const x: TestSynthetic = null; // ✓

const y: TestSynthetic = 3; // Type '3' is not assignable to type 'T'.
const z: TestSynthetic = '3'; // Type '"3""' is not assignable to type 'T'.
```

**Expected behavior:**
- TestSynthetic resolved as number
- w, x, and z invalid with strict
- y valid

**Actual behavior:**
- TestSynthetic resolved as T -- an open generic from the underlying conditional type
- w and x valid, even with strict
- y and z error with commented errors

**Playground Link:** 
https://bit.ly/30lTSqk

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/31326

**Notes:**

- Removing the `extends A` constraint causes expected behavior, so that's likely involved somehow.
- Turning on all strict options in typescript playground causes all four example cases to be errors -- unclear why this is stricter than `strict: true` in my local tsconfig with @next.
- I'm not 100% sure if a conditional type that resolves to an open generic is allowed -- I was certainly surprised to see it. If it is, this still seems to be a bug in conditional type resolution.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #31402

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -10406,14 +10406,34 @@ namespace ts {
...
             if (root.inferTypeParameters) {
-                const context = createInferenceContext(root.inferTypeParameters, /*signature*/ undefined, InferenceFlags.None);
+                const freshParams = map(root.inferTypeParameters, cloneTypeParameter);
+                const freshMapper = createTypeMapper(root.inferTypeParameters, freshParams);
+                const context = createInferenceContext(freshParams, /*signature*/ undefined, InferenceFlags.None);
+                // We have three mappers that need applying:
+                //    * The original `mapper` used to create this conditional
+                //    * The mapper that maps the old root type parameter to the clone (`freshMapper`)
+                //    * The mapper that maps the clone to its inference result (`context.mapper`)
+                // When we're looking at making an inference for a clone, when we get its constraint, it's autmagically be
```
Comment (sandersn) [inline src/compiler/checker.ts]:
```suggestion
                // When we're looking at making an inference for a clone, when we get its constraint, it'll automagically be
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -10406,14 +10406,34 @@ namespace ts {
             const checkTypeInstantiable = maybeTypeOfKind(checkType, TypeFlags.Instantiable | TypeFlags.GenericMappedType);
             let combinedMapper: TypeMapper | undefined;
             if (root.inferTypeParameters) {
-                const context = createInferenceContext(root.inferTypeParameters, /*signature*/ undefined, InferenceFlags.None);
+                const freshParams = map(root.inferTypeParameters, cloneTypeParameter);
+                const freshMapper = createTypeMapper(root.inferTypeParameters, freshParams);
+                const context = createInferenceContext(freshParams, /*signature*/ undefined, InferenceFlags.None);
+                // We have three mappers that need applying:
```
Comment (sandersn) [inline src/compiler/checker.ts]: is there a more concise way to write this whole block? This right here is "here be dragons" commenting level Double Dragon. I expect demons to fly out of my nose after reading it.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -10406,14 +10406,34 @@ namespace ts {
...
+                // instantiated with the context, so it doesn't need that one - however the constraint may refer to another _root_, _uncloned_
+                // `infer` type parameter.
+                // Eg, if we have `Foo<T, U extends T>` and `Foo<number, infer B>` - `B` is constrained to `T`, which, in turn, has been instantiated
+                // as `number`
+                // Conversely, if we have `Foo<infer A, infer B>`, `B` is still constrained to `T` and `T` is instantiated as `A`
+                // So we need to:
+                //    * Clone the type parameters so their constraints can be instantiated in the context of `mapper`
+                //    * Set the clones to both map the context and the original params
+                //    * instantiate the extends type with the clones
+                //    * incorporate all of the component mappers into the combined mapper for the members
```
Comment (sandersn) [inline src/compiler/checker.ts]: oh no it happened 
:nose:
:imp:

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -10406,14 +10406,34 @@ namespace ts {
...
-                const context = createInferenceContext(root.inferTypeParameters, /*signature*/ undefined, InferenceFlags.None);
+                const freshParams = map(root.inferTypeParameters, cloneTypeParameter);
+                const freshMapper = createTypeMapper(root.inferTypeParameters, freshParams);
+                const context = createInferenceContext(freshParams, /*signature*/ undefined, InferenceFlags.None);
+                // We have three mappers that need applying:
+                //    * The original `mapper` used to create this conditional
+                //    * The mapper that maps the old root type parameter to the clone (`freshMapper`)
+                //    * The mapper that maps the clone to its inference result (`context.mapper`)
+                // When we're looking at making an inference for a clone, when we get its constraint, it's autmagically be
+                // instantiated with the context, so it doesn't need that one - however the constraint may refer to another _root_, _uncloned_
```
Comment (sandersn) [inline src/compiler/checker.ts]: "it doesn't need that one"

What doesn't need that one? This piece of code?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -10406,14 +10406,34 @@ namespace ts {
...
+                // `infer` type parameter.
+                // Eg, if we have `Foo<T, U extends T>` and `Foo<number, infer B>` - `B` is constrained to `T`, which, in turn, has been instantiated
+                // as `number`
+                // Conversely, if we have `Foo<infer A, infer B>`, `B` is still constrained to `T` and `T` is instantiated as `A`
```
Comment (sandersn) [inline src/compiler/checker.ts]: this sounds like two steps of unification. Is it guaranteed to be limited to two steps? What happens with the current code if it's not?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -10406,14 +10406,34 @@ namespace ts {
...
+                // So we need to:
+                //    * Clone the type parameters so their constraints can be instantiated in the context of `mapper`
```
Comment (sandersn) [inline src/compiler/checker.ts]: this list of steps should ideally go before the first code that implements the list

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts]: <The mapper for the inference context>

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts]: We don't actually do unification so yeah, it is limited to two steps, since those are the two steps we actually do. If there were more, that'd either be incorporated into one of these mappers (so effectively a sub-step), or be represented by another mapper which'd need to be passed in and incorporated here.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts]: unrelated, but frustrating: `suggestion`s on `checker.ts` look nice but can't be batched and applied on the web UI for github. F. Where do I go to submit this bug report, I wonder.

**Comment by weswigham** [comment]
@sandersn comment order and informational content altered~

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -10406,14 +10406,36 @@ namespace ts {
...
+                // So we need to:
+                //    * Clone the type parameters so their constraints can be instantiated in the context of `mapper` (otherwise theyd only get inference context information)
+                //    * Set the clones to both map the conditional's enclosing `mapper` and the original params
+                //    * instantiate the extends type with the clones
+                //    * incorporate all of the component mappers into the combined mapper for the true and false members
+                // This means we have three mappers that need applying:
+                //    * The original `mapper` used to create this conditional
+                //    * The mapper that maps the old root type parameter to the clone (`freshMapper`)
+                //    * The mapper that maps the clone to its inference result (`context.mapper`)
+                const freshParams = map(root.inferTypeParameters, cloneTypeParameter);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I'm concerned about all the new type identities created by _always_ cloning the type parameters here. Fresh type parameters mean more work and more bloat in relationship caches. I'm wondering if we can somehow realize that we don't need to clone as that clearly covers the vast majority of cases.

Comment (weswigham) [reply src/compiler/checker.ts]: We could avoid clone type parameters which aren't constrained to an instantiable type, for what that'd give us.

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot perf test this

**Comment by weswigham** [comment]
RWC failed because there was a small diff in `master` that needed accepting and is clean, DT is likewise as clean as `master`.

@ahejlsberg ?

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -10406,14 +10411,39 @@ namespace ts {
...
+                // So we need to:
+                //    * Clone the type parameters so their constraints can be instantiated in the context of `mapper` (otherwise theyd only get inference context information)
+                //    * Set the clones to both map the conditional's enclosing `mapper` and the original params
+                //    * instantiate the extends type with the clones
+                //    * incorporate all of the component mappers into the combined mapper for the true and false members
+                // This means we have three mappers that need applying:
+                //    * The original `mapper` used to create this conditional
+                //    * The mapper that maps the old root type parameter to the clone (`freshMapper`)
+                //    * The mapper that maps the clone to its inference result (`context.mapper`)
+                const freshParams = map(root.inferTypeParameters, maybeCloneTypeParameter);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Use `sameMap` and only create an additional mapper if something changed?

Comment (weswigham) [reply src/compiler/checker.ts]: @ahejlsberg done.

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by weswigham** [comment]
@ahejlsberg opted to reschedule this to 3.9 in person, but imma still need an updated review status at some point, thanks ❤️

**Comment by weswigham** [comment]
Man, I missed this one for a long time because it never got an updated github review status, but since it got an offline approval, 4.7 is kinda like 3.9 I guess. Once CI is green, I'll merge this.
