### PR TITLE
Fix and validate post-increment/decrement in module emit

### LINKED ISSUE #33044: ES6 export variable binding incorrect post increment
**TypeScript Version:**  3.5.1 (playground)

**Search Terms:**
export let binding variable reference

**Code**

```ts
let a = 1
export {a}
console.log(a++)
```

**Expected behavior:**
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAhhC8EEYBQIAeAHA9gJ0gbygF8kBjTAOwGdNQA6YTAcwAooBqNgSiSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.5.5&externalPlugins=

should output `1`

**Actual behavior:**
`2` is output
`a++` post-increment becomes `(a += 1)` pre-increment

**Playground Link:**
http://www.typescriptlang.org/play/?target=1#code/DYUwLgBAhhC8EEYCwAoEAPADgewE6QG8oBfVAY2wDsBnbUAOmGwHMAKKAag4EpUg

**Related Issues:**
https://github.com/microsoft/TypeScript/issues/33043

### PR DESCRIPTION
**Pull request by rbuckton**
This changes the emit for post-increment/decrement in our module emit for CommonJS, AMD, UMD, and System. This aligns with another recent change that fixed pre-/post-increment/decrement for private fields, and also ensures that pre-/post-increment/decrement work with `BigInt` values (our previous emit did not).

This also adds evaluation tests for pre-/post-increment/decrement in CommonJS and System (which required adding a mini System loader to the evaluator test framework). AMD and UMD are not included in the evaluation tests because that emit is covered by the CommonJS case.

Fixes #33044

### CODE REVIEW

**Comment by rbuckton** [comment]
Since this changes Prefix/PostfixUnaryExpression handling to occur during transformation instead of substitution (which was necessary due to the introduction of a possible temp variable), this could result in a performance regression.

@typescript-bot perf test

**Comment by rbuckton** [comment]
Surprisingly, emit time wasn't really affected by this, so I think this is ready for review.

File: src/compiler/transformers/module/module.ts [hunk 1]
```diff
@@ -604,16 +626,91 @@ namespace ts {
...
+            // - We do not transform generated identifiers for any reason.
+            // - We do not transform identifiers tagged with the LocalName flag.
+            // - We do not transform identifiers that were originally the name of an enum or
+            //   namespace due to how they are transformed in TypeScript.
+            // - We only transform identifiers that are exported at the top level.
+            if ((node.operator === SyntaxKind.PlusPlusToken || node.operator === SyntaxKind.MinusMinusToken)
+                && isIdentifier(node.operand)
+                && !isGeneratedIdentifier(node.operand)
+                && !isLocalName(node.operand)
+                && !isDeclarationNameOfEnumOrNamespace(node.operand)) {
```
Comment (sandersn) [inline src/compiler/transformers/module/module.ts:675]: why do you have to redo this check if the factory sets TransformFlags.ContainsUpdateExpressionForIdentifier?

File: src/compiler/transformers/module/module.ts [hunk 2]
```diff
@@ -604,16 +626,91 @@ namespace ts {
...
+                        if (!valueIsDiscarded) {
+                            temp = factory.createTempVariable(hoistVariableDeclaration);
+                            expression = factory.createAssignment(temp, expression);
+                            setTextRange(expression, node);
+                        }
+                        expression = factory.createComma(expression, factory.cloneNode(node.operand));
+                        setTextRange(expression, node);
+                    }
+
+                    for (const exportName of exportedNames) {
```
Comment (sandersn) [inline src/compiler/transformers/module/module.ts:694]: I don't understand what this loop is for. Is it doing something that the code path through visitEachChild would normally do?

File: src/compiler/transformers/module/module.ts [hunk 3]
```diff
@@ -537,26 +535,50 @@ namespace ts {
...
 
                 default:
-                    return visitEachChild(node, moduleExpressionElementVisitor, context);
+                    return visitor(node);
             }
         }
 
-        function moduleExpressionElementVisitor(node: Expression): VisitResult<Expression> {
+        function visitorWorker(node: Node, valueIsDiscarded: boolean): VisitResult<Node> {
             // This visitor does not need to descend into the tree if there is no dynamic import or destructuring assignment,
```
Comment (sandersn) [inline src/compiler/transformers/module/module.ts:543]: comment should mention update expressions

File: src/compiler/transformers/module/system.ts [hunk 4]
```diff
@@ -225,7 +223,7 @@ namespace ts {
 
             // Add any prologue directives.
             const ensureUseStrict = getStrictOptionValue(compilerOptions, "alwaysStrict") || (!compilerOptions.noImplicitUseStrict && isExternalModule(currentSourceFile));
-            const statementOffset = factory.copyPrologue(node.statements, statements, ensureUseStrict, sourceElementVisitor);
+            const statementOffset = factory.copyPrologue(node.statements, statements, ensureUseStrict, topLevelVisitor);
```
Comment (sandersn) [inline src/compiler/transformers/module/system.ts:226]: Is it possible to share code between module.ts and system.ts? They parts in this review look identical.

**Review by sandersn — CHANGES_REQUESTED** [review]
A few questions about how things work.

File: src/compiler/transformers/module/module.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/module/module.ts:675]: Because not every `PrefixUnaryExpression` or `PostfixUnaryExpression` is one we should transform, and the `TransformFlags.ContainsUpdateExpressionForIdentifier` flag could be set deeper in the parse tree:

```ts
let x;
({ get y() { return x++; }, set y(value) { x = value; }).y++;
export { x }
```
The `TransformFlags.ContainsUpdateExpressionForIdentifier` flag will be set on `x++` and every node that contains it, including the outer `({ ... }).y++`.

File: src/compiler/transformers/module/module.ts (hunk 2 above)
Comment (rbuckton) [reply src/compiler/transformers/module/module.ts:694]: Whenever a variable is exported using `export {}` it will have one or more additional exported names:

```ts
// source
// @target: esnext
// @module: commonjs
let x = 1;
x++;
export { x as a };
export { x as b };

// output
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.b = exports.a = void 0;
let x = 1;
exports.a = x;
exports.b = x;
exports.b = exports.a = (x++, x);
```

In the above case, `exportedNames` would contain `a` and `b`, so every time we change the value of `x` we also need to update the exports for `a` and `b`.

File: src/compiler/transformers/module/system.ts (hunk 4 above)
Comment (rbuckton) [reply src/compiler/transformers/module/system.ts:226]: Most of the sharing we do between these two module systems is in `collectExternalModuleInfo`. The problem with refactoring the similarities between the two is that in both cases they close over specific visitors for their individual cases. We could conceivably refactor module emit, but that's not a task I'd like to take on in this PR.

File: src/compiler/transformers/module/module.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/module/module.ts:675]: Many of the `Contains*` flags bubble up to the `SourceFile` so that we can accept an entire subtree if there's no work to be done. The few that don't are due to the specific needs of a transformation.

**Review by sandersn — APPROVED** [review]
