### PR TITLE
Don't add extra indentation for objects inside function parameters

### LINKED ISSUE #14589: Format document action is not working properly with objects in functions parameters
_From @micnic on March 9, 2017 10:6_

Format document action is not working properly when providing multiple objects as parameters to javascript functions.

- VSCode Version: 1.10.2
- OS Version: Linux Ubuntu 16.04 and Windows 10 tested

Steps to Reproduce:

1. Write the following lines in a `.js` file:
```js
someRandomFunction({
    prop1: 1,
    prop2: 2
}, {
    prop3: 3,
    prop4: 4
}, {
    prop5: 5,
    prop6: 6
});
```
2. Press the format document editor action keys (Ctrl + Shift + I)

3. See the following result:
```js
someRandomFunction({
    prop1: 1,
    prop2: 2
}, {
        prop3: 3,
        prop4: 4
    }, {
        prop5: 5,
        prop6: 6
    });
```

Expected result would be to keep the indentation of the objects.

_Copied from original issue: Microsoft/vscode#22285_

### PR DESCRIPTION
**Pull request by orta**
Fixes #14589

There was a test of the old behavior, but I think the new behavior is better, so I fixed that test.

### CODE REVIEW

**Comment by andrewbranch** [comment]
Maybe add a test for something like this, if one doesn’t already exist? I can’t tell what would happen without pulling your branch, so it’s worth checking:

```ts
someRandomFunction(
  { prop1: 1, prop2: 2 },
  { prop3: 3, prop4: 4 },
  {
    prop5: 5,
    prop6: 6
  }
);
```

**Comment by orta** [comment]
Thanks - that made it much easier to write this a second time though :D

File: src/services/formatting/smartIndenter.ts [hunk 1]
```diff
@@ -322,6 +322,26 @@ namespace ts.formatting {
             return false;
         }
 
+        export function childStartsInlineWithPreviousObject(parent: Node, child: TextRangeWithKind, childStartLine: number, sourceFile: SourceFileLike): boolean {
```
Comment (andrewbranch) [inline src/services/formatting/smartIndenter.ts]: Is the previous thing necessarily an object? If not, I’d probably call this `argumentStartsOnSameLineAsPreviousArgument` since this function is specific to call expressions.

File: src/services/formatting/smartIndenter.ts [hunk 2]
```diff
@@ -322,6 +322,26 @@ namespace ts.formatting {
             return false;
         }
 
+        export function childStartsInlineWithPreviousObject(parent: Node, child: TextRangeWithKind, childStartLine: number, sourceFile: SourceFileLike): boolean {
+            if (parent.kind === SyntaxKind.CallExpression) {
```
Comment (andrewbranch) [inline src/services/formatting/smartIndenter.ts]: Should probably check for `NewExpression` too—you can use `isCallOrNewExpression(parent)` which will also eliminate the need for the type assertion below.

File: src/services/formatting/smartIndenter.ts [hunk 3]
```diff
@@ -322,6 +322,26 @@ namespace ts.formatting {
             return false;
         }
 
+        export function childStartsInlineWithPreviousObject(parent: Node, child: TextRangeWithKind, childStartLine: number, sourceFile: SourceFileLike): boolean {
+            if (parent.kind === SyntaxKind.CallExpression) {
+                const parentCallExpression = <CallExpression>parent;
+                const currentNode = find(parentCallExpression.arguments, arg => arg.pos === child.pos);
+                if (!currentNode) return false; // Shouldn't happen
```
Comment (andrewbranch) [inline src/services/formatting/smartIndenter.ts]: If this is intended to be a guarantee, and you’d prefer to get a bug report instead of silently not working if the assumption doesn’t hold, you could consider doing `const currentNode = Debug.assertDefined(...)` (which also narrows the type to eliminate `undefined`). But for a boolean-returning helper function, I can see it either way—returning false sounds technically correct as well.

**Comment by orta** [comment]
Thanks! will merge on green
