### PR TITLE
fix(32341): Renaming class name switches up order in object literal shorthand

### LINKED ISSUE #32341: Renaming class name switches up order in object literal shorthand
From https://github.com/microsoft/vscode/issues/76482

**TypeScript Version:**  3.6.0-dev.20190710

**Search Terms:**
- rename
- object literal
- alias

**Code**

For the JS:

```ts
class A { }
module.export = { A };
```

1. Rename `A` in `class A {}`

**Expected behavior:**

```js
class B { }
module.export = { A: B };
```

**Actual behavior:**

```js
class B { }
module.export = { B: A };
```

The order in the exported object literal is swapped so we end up referencing  `A` which no longer exists

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #32341

### CODE REVIEW

File: tests/cases/fourslash/renameModuleExportsProperties3.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+﻿/// <reference path='fourslash.ts' />
+
+// @allowJs: true
+// @Filename: a.js
+////[|class [|{| "contextRangeIndex": 0 |}A|] {}|]
+////module.exports = { [|A|] }
+
+const [r0Def, r0, r1] = test.ranges();
+verify.renameLocations(r0, { ranges: [r0, { range: r1, prefixText: "A: " }], providePrefixAndSuffixTextForRename: true });
+verify.renameLocations(r1, { ranges: [r0, { range: r1, prefixText: "A: " }], providePrefixAndSuffixTextForRename: true });
```
Comment (andrewbranch) [inline tests/cases/fourslash/renameModuleExportsProperties3.ts:10]: Would you mind switching these tests from `verify.renameLocations` to `verify.baselineRename`? I find the former so difficult to parse.

Comment (a-tarasyuk) [reply tests/cases/fourslash/renameModuleExportsProperties3.ts:10]: I used `renameLocations`, to test `prefixText`., I'm not sure that `baselineRename` allows inserting `prefixText` to baseline file., for instance, the baseline for the `renameModuleExportsProperties3.ts` looks like so,

```ts
/*====== /tests/cases/fourslash/a.js ======*/

class [|RENAME|] {}
module.exports = { RENAME }
```
