### PR TITLE
Fix regression organize imports duplicates comments

### LINKED ISSUE #38507: source.organizeImports is replicating last comment line
Using `Code Insiders` build:
```
Version: 1.46.0-insider
Commit: 288852d8c26d797974bfb8aed06e1bff9b809223
Date: 2020-05-12T05:42:38.380Z (12 hrs ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Problem:  If you have `organizeImports` enabled, such as:
```
	"editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
```

and you save a file with comments in the import area, such as:

```
// comment1
import { Component, h, Prop, State } from "@stencil/core";
// comment2
import { CloudService } from "../../services/cloud";
```

and then save the file, it will replicate the last comment line under all of the imports like this:

### After first save
// comment1
import { Component, h, Prop, State } from "@stencil/core";
// comment2
import { CloudService } from "../../services/cloud";
// comment2

### After 2nd save
// comment1
import { Component, h, Prop, State } from "@stencil/core";
// comment2
import { CloudService } from "../../services/cloud";
// comment2
// comment2

#### Etc...

### PR DESCRIPTION
**Pull request by jessetrinity**
Fixes #38507 

#37467 started preserving comments when deleting unused declarations. When organize imports creates a sorted list of imports, it deletes the old imports in the same way. This caused us to start duplicating comments when organizing imports.

### CODE REVIEW

File: src/services/textChanges.ts [hunk 1]
```diff
@@ -286,6 +286,12 @@ namespace ts.textChanges {
             this.deletedNodes.push({ sourceFile, node });
         }
 
+        public deleteNode(sourceFile: SourceFile, node: Node, options: ConfigurableStartEnd = { leadingTriviaOption: LeadingTriviaOption.IncludeAll }): void {
+            const startPosition = getAdjustedStartPosition(sourceFile, node, options);
+            const endPosition = getAdjustedEndPosition(sourceFile, node, options);
```
Comment (sheetalkamat) [inline src/services/textChanges.ts:291]: use getAdjustedRange instead

**Comment by jessetrinity** [comment]
@typescript-bot cherry-pick this to release-3.9

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-3.9

I wonder if you need to be added to a list/role somewhere
