### PR TITLE
isValidMethodAccess: Instantiate signature this type if necessary

### LINKED ISSUE #21711: 2.7.1 regression: method doesn't show up in intellisense
**TypeScript Version:**  2.7.1 and typescript@next (2.8.0-dev.20180206)

**Code**

```ts
declare class Klass<A> {
  readonly value: A
  constructor(value: A)
  f<B extends number>(this: Klass<B>): void
}

const x = new Klass(1). // <= `f` is not suggested by intellisense
```

**Expected behavior:**

`f` should be listed in intellisense as happens with typescript v2.6.2

**Actual behavior:**

`f` doesn't show up in intellisense

**Playground Link:** 

[Playground repro](https://www.typescriptlang.org/play/#src=declare%20class%20Klass%3CA%3E%20%7B%0D%0A%20%20readonly%20value%3A%20A%0D%0A%20%20constructor(value%3A%20A)%0D%0A%20%20f%3CB%20extends%20number%3E(this%3A%20Klass%3CB%3E)%3A%20void%0D%0A%7D%0D%0A%0D%0Aconst%20x%20%3D%20new%20Klass(1).%20%2F%2F%20%3C%3D%20%60f%60%20is%20not%20suggested%20by%20intellisense%0D%0A)

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #21711

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11191,7 +11194,7 @@ namespace ts {
         }
 
         function createInferenceContext(signature: Signature, flags: InferenceFlags, compareTypes?: TypeComparer, baseInferences?: InferenceInfo[]): InferenceContext {
-            const inferences = baseInferences ? map(baseInferences, cloneInferenceInfo) : map(signature.typeParameters, createInferenceInfo);
+            const inferences = baseInferences ? baseInferences.map(cloneInferenceInfo) : signature.typeParameters.map(createInferenceInfo);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Looks like this function should never be called if `signature.typeParameters` is undefined, since we expect `inferences` to always be defined elsewhere.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16399,15 +16402,23 @@ namespace ts {
...
+                const signatureThisType = getThisTypeOfSignature(sig);
+                return !signatureThisType || isTypeAssignableTo(actualThisType, getInstantiatedSignatureThisType(sig, signatureThisType, actualThisType));
             });
         }
+        function getInstantiatedSignatureThisType(sig: Signature, signatureThisType: Type, actualThisType: Type): Type {
+            if (!sig.typeParameters) {
+                return signatureThisType;
+            }
+            const context = createInferenceContext(sig.typeParameters, sig, InferenceFlags.None);
+            inferTypes(context.inferences, actualThisType, signatureThisType);
```
Comment (sandersn) [inline src/compiler/checker.ts]: It's a little weird to do limited inference here, but *maybe* it makes sense because this is called solely for completions? The inference and instantiation will happen later, and lead to an error, in normal compilation.

Comment (andy-ms) [reply src/compiler/checker.ts]: Since the call expression doesn't actually exist (we're just considering adding the completion, all that exists so far is `obj.`), this won't have a corresponding normal compilation.
