### PR TITLE
Recreate program if baseUrl or paths changed in tsconfig

### LINKED ISSUE #9522: tsconfig changes to baseUrl, paths, etc require restart.
_From @aluanhaddad on July 4, 2016 5:49_

- VSCode Version: 1.3.0-insider, 1.2.1
- OS: Windows 10 Professional x64

Steps to Reproduce:

1. Install a nightly build of typescript supporting `baseUrl` and `paths`, anything since march should do.
2. Set `"typescript.tsdk": "C:/Users/user/AppData/Roaming/npm/node_modules/typescript/lib"`
3. Changes to paths and baseUrl are not reflected without reloading VSCode.

This is very frustrating as I am trying to determine a package install strategy which supports multi-versioned, non ambient external module resolution for jspm and I need to test changes manually. Each time I tweak any _tsconfig_ i must reload VSCode.

I was going to raise this issue with the TypeScript team but I have not been able to reproduce it in other editors, such as the VS 15 preview 2, which I have configured to use the new language service and supports these settings. I could not find any exact duplicates.

PS: Thank you for all the hard work you have put into VSCode, it keeps getting better and better :heart: 

_Copied from original issue: Microsoft/vscode#8705_

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #9522

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -3097,7 +3097,9 @@ namespace ts {
                  oldSettings.noResolve !== newSettings.noResolve ||
                  oldSettings.jsx !== newSettings.jsx ||
                  oldSettings.allowJs !== newSettings.allowJs ||
-                 oldSettings.disableSizeLimit !== oldSettings.disableSizeLimit);
+                 oldSettings.disableSizeLimit !== oldSettings.disableSizeLimit ||
```
Comment (vladima) [inline src/services/services.ts]: can you rename `changesInCompilationSettingsAffectSyntax` to `shouldCreateNewSourceFiles`?

**Comment by vladima** [comment]
:+1:  with a minor suggestion
