### PR TITLE
Call dynamic import transform on expression used by export equal statement

### LINKED ISSUE #16641: new import syntax incorrectly generating amd require on exported function compared to class member / exported function
**TypeScript Version:**  2.4.0 

The following things work as expected

```ts
export class Test 
{
    async LoadSomething() {
        const something = await import("./something");
    }
}

export async function LoadSomething() {
        const something = await import("./something");
}
```

which will generate

```js
new Promise(function (resolve_1, reject_1) { require(["./something"], resolve_1, reject_1); })];
```

whereas 

```ts
    export = async function() {
        const something = await import("./something");
    }
```

```ts
// A *self-contained* demonstration of the problem follows...

```

will generate 

```js
 import("./something")
```

**Expected behavior:**
Code which is emitted should be 

```js
new Promise(function (resolve_1, reject_1) { require(["./something"], resolve_1, reject_1); })];
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #16641

### CODE REVIEW

**Comment by mhegazy** [comment]
Please port this to release-2.5

File: src/compiler/transformers/module/module.ts [hunk 1]
```diff
@@ -430,26 +430,32 @@ namespace ts {
...
-                    const statement = createStatement(
-                        createAssignment(
-                            createPropertyAccess(
-                                createIdentifier("module"),
-                                "exports"
-                            ),
-                            currentModuleInfo.exportEquals.expression
-                        )
-                    );
+                const expressionResult = importCallExpressionVisitor(currentModuleInfo.exportEquals.expression);
```
Comment (rbuckton) [inline src/compiler/transformers/module/module.ts]: This should have been `visitNode(currentModuleInfo.exportEquals.expression, importCallExpressionVisitor, isExpression)` as it does the necessary validation you're doing on 435-437 for you.
