### PR TITLE
Fix convert to named parameters rest parameter tuple

### LINKED ISSUE #30264: 'Convert to named parameters' doesn't work with rest parameters of tuple type
**Code**
Original code:
```ts
function fn(a: number, b: number, ...args: [number, number]) { }
fn(1, 2, 3, 4);
```

**Expected behavior:**
```ts
function fn({ a, b, args }: { a: number; b: number; args: [number, number]; }) { }
fn({ a: 1, b: 2, args: [3, 4] });
```
**Actual behavior:**
After refactoring:
```ts
function fn({ a, b, args = [] }: { a: number; b: number; args?: [number, number]; }) { }
fn({ a: 1, b: 2, args: [3, 4] });
```

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/30113

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #30264.

This PR also restricts the availability of the named parameters refactor. The refactor will only be offered in a function with a rest parameter if the type of the rest parameter is either an array type or a tuple type. This is necessary because if a rest parameter is an array, the refactor needs to initialize the corresponding variable to preserve semantics:
```ts
function fn(a: boolean, ...b: number[]) {}
fn(true);
```
becomes:
```ts
function fn({ a, b = [] }: { a: boolean; b?: number[]; }) {}
fn({ a: true }); // b is not undefined in this call
```
If the rest parameter has a tuple type, then the parameter is not optional and providing an initializer is not necessary.
But in other cases it might not be possible to determine if the empty array initializer should be added (and adding the empty array as initializer might not even type check):
```ts
function /*a*/gen<T extends any[]>/*b*/(a: boolean, ...b: T): T {
    return b;
}
```

### CODE REVIEW

File: src/services/refactors/convertParamsToDestructuredObject.ts [hunk 1]
```diff
@@ -384,24 +415,17 @@ namespace ts.refactor.convertParamsToDestructuredObject {
...
-            getParameterName(parameterDeclaration),
-            isRestParameter(parameterDeclaration) ? createArrayLiteral() : parameterDeclaration.initializer);
-
-        suppressLeadingAndTrailingTrivia(element);
-        if (parameterDeclaration.initializer && element.initializer) {
-            copyComments(parameterDeclaration.initializer, element.initializer);
+        function isOptionalParameter(parameterDeclaration: ValidParameterDeclaration): boolean {
+            if (isRestParameter(parameterDeclaration)) {
+                const type = checker.getTypeAtLocation(parameterDeclaration);
+                return checker.isTupleType(type) ? false : true;
```
Comment (sandersn) [inline src/services/refactors/convertParamsToDestructuredObject.ts]: `return !checker.isTupleType(type)`
