### PR TITLE
Distribute indexed accesses when simplifying them

### LINKED ISSUE #25181: SpyObj<T>[keyof T] not resolving to the type SpyObj members (Jasmine typings)
**TypeScript Version:**  2.9.2

**Code**

```ts
interface Spy {
  (...params: any[]): any;

  identity: string;
  and: Function;
  mostRecentCall: {args: any[];};
  argsForCall: any[];
}

type SpyObj<T> = T&{
  [k in keyof T]: Spy;
}

declare function createSpyObj<T>(
    name: string, names: Array<keyof T>): SpyObj<T>;

/**
 * Creates a jasmine mock where every given method returns the spy object.
 */
function mock<T>(spyName: string, methodNames: Array<keyof T>): SpyObj<T> {
  const spyObj = createSpyObj<T>(spyName, methodNames);
  for (const methodName of methodNames) {
    spyObj[methodName].and.returnValue(1);  // fails, Property 'and' does not exist on type 'SpyObj<T>[keyof T]'.
  }
  return spyObj;
}
```

**Expected behavior:**

In TS2.8, `spyObj[methodName]` above was any, allowing `and` to be referenced on it.  Ideally, this would figure out that all members of `spyObj` must at least be a `Spy`.

**Actual behavior:**

In TS 2.9, there's a type `SpyObj<T>[keyof T]`, but apparently it does not resolve to `Spy`?

**Playground Link:** 

http://www.typescriptlang.org/play/#src=%0Ainterface%20Spy%20%7B%0A%20%20(...params%3A%20any%5B%5D)%3A%20any%3B%0A%0A%20%20identity%3A%20string%3B%0A%20%20and%3A%20Function%3B%0A%20%20mostRecentCall%3A%20%7Bargs%3A%20any%5B%5D%3B%7D%3B%0A%20%20argsForCall%3A%20any%5B%5D%3B%0A%7D%0A%0Atype%20SpyObj%3CT%3E%20%3D%20T%26%7B%0A%20%20%5Bk%20in%20keyof%20T%5D%3A%20Spy%3B%0A%7D%0A%0Adeclare%20function%20createSpyObj%3CT%3E(%0A%20%20%20%20name%3A%20string%2C%20names%3A%20Array%3Ckeyof%20T%3E)%3A%20SpyObj%3CT%3E%3B%0A%0A%2F**%0A%20*%20Creates%20a%20jasmine%20mock%20where%20every%20given%20method%20returns%20the%20spy%20object.%0A%20*%2F%0Afunction%20mock%3CT%3E(spyName%3A%20string%2C%20methodNames%3A%20Array%3Ckeyof%20T%3E)%3A%20SpyObj%3CT%3E%20%7B%0A%20%20const%20spy%20%3D%20createSpyObj%3CT%3E(spyName%2C%20methodNames)%3B%0A%20%20for%20(const%20methodName%20of%20methodNames)%20%7B%0A%20%20%20%20spy%5BmethodName%5D.and.returnValue(spy)%3B%0A%20%20%7D%0A%20%20return%20spy%3B%0A%7D%0A

### LINKED ISSUE #26274: Indexed Accesses Checking Allow Unsafe Assignments
**Code**

```ts
class Component<S> {
    state!: S; // assume a default state is provided in some way
    setState<K extends keyof S>(state: Pick<S, K>) { /*react-like setState*/ }
}
    
export interface State<T> {
    a: T;
}
    
class Foo {}
    
class Comp<T extends Foo, S> extends Component<S & State<T>>
{
    foo(a: T) {
        this.setState({ a: a });
    }
}
```

**Expected behavior:**
Error on `setState` - a `T` is not inherently comparable with a `S["a"]` - since `S` is unconstrained, so too is `S["a"]`.
For a concrete subtype which exposes the issue, consider:
```ts
class BrokenComponent extends Comp<Foo, { a: { x: number } }> {
    main() {
        const f = new Foo();
        this.foo(f); // allowed
        this.state.a.x; // According to the typesystem, this should exist, but it won't!
    }
}
```

**Actual behavior:**
No error.

### LINKED ISSUE #26608: Union of generic indexed types works incorrectly
I have two generic indexed types

```ts
type ExtendedService<T> = {
    [K in keyof T]: T[K] & {
        __$daemonMode?: string;
        __$action?: string;
    };
};

type Service<T> = {
    [K in keyof T]: T[K] & {id?: string};
};
```

And use them like this

```ts
export const createService = <T>(
    ServiceCtr: ExtendedService<T> & Service<T>
) => {
    ...
    Object.keys(ServiceCtr).forEach(key => {
        const method = (ServiceCtr)[key as keyof T];
        const {__$daemonMode, __$action, id} = method;
        ...
    }
}
```

VS Code output for `method` type is

```ts
const method: ({ [K in keyof T]: T[K] & {
    __$daemonMode?: string;
    __$action?: string;
}; } & Service<T>)[keyof T]
```

**Expected behavior:**

properties `__$daemonMode`, `__$action`, `id` exists on `method` variable;
`const {__$daemonMode, __$action, id} = method; ` has no errors;

**Actual behavior:**

I got an error
```
[ts] Type '(ExtendedService<T> & Service<T>)[keyof T]' has no property '__$daemonMode' and no string index signature.
```
`__$action` and `id` produces the same error;

P.S.

Expression

```ts
const x: (ExtendedService<{z: {}}> & Service<{z: {}}>)['z'];
const {__$daemonMode, __$action, id} = x;
```

works as expected

### PR DESCRIPTION
**Pull request by weswigham**
And use the `unknownType` instead of the `errorType` when checking for property types if there is no error node, so the types combine appropriately under intersection and union operations.

Sketch of a fix for #26274 - I mostly want to investigate this change's impact on RWC, since the changes to, eg, index signature handling in intersections (it's more correct!) could be breaky. It's also likely correct to simply distribute on initial construction, rather than waiting for simplification - but I haven't looked much into that approach yet.

Fixes #26274
Fixes #25181
Fixes #26608

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
Saw a pair of RWC breaks due to `any` as an index type not propagating (silently return the `errorType` had the effect of propagating it). Now `T[any]` is very explicitly also `any`. I think this is probably wrong, btw, but it's what we were doing before. It should _probably_ also be `unknown`, despite how that may break some people.

@typescript-bot test this again btw

File: tests/baselines/reference/varianceCallbacksAndIndexedAccesses.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    removeEventListener(type: "message", handler: Action1<MessageEventLike<T>>): void;
+    removeEventListener(type: string, handler: Action1<any>): void;
+}
+type Target = {
+    (type: "message", handler: Action1<MessageEventLike<any>>): void;
+    (type: string, handler: Action1<any>): void;
+};
+
+function f1(s: Source, t: Target) {
+    t = s;
```
Comment (weswigham) [inline tests/baselines/reference/varianceCallbacksAndIndexedAccesses.js]: I'm _pretty sure_ this assignment is actually unsafe. Like, callback variance checks should prevent this from succeeding because `Target`'s callbacks don't handle a wide enough range of things, but because we overwrite `K` with `any` and `WindowEventMap[any]` is `any` it succeeds.

**Comment by weswigham** [comment]
Last RWC break I saw had to do with flow control - we use `getConstraintAtLocation` to generate the initial type, but when we went to go look it up again to see if it differs, we weren't getting the locally constrained version anymore. This meant that types which simplified (which there are now more of, thanks to these identities) were narrowed against themselves (or rather: their simplified versions), resulting in somewhat incoherent results. Now we get the constraint at the referencing location whenever we lookup the initial or declared type again.

@typescript-bot test this again, since now there should be no new breaks 🤞

**Comment by weswigham** [comment]
@typescript-bot test this now that we've accepted RWC updates so hopefully they are passing now

**Comment by weswigham** [comment]
So, I've checked: This _also_ fixes #25181, which was also due to an issue with reasoning over an index on an intersection! This seems _way_ cleaner than my other candidate to fix that.

**Comment by weswigham** [comment]
We talked about this today a bit - we think this is good, but we wanna fix the generic assignability issue one of the tests shows (`T[K]` being constrained to `undefined` to anything is assignable to it) and possibly sketch a patch to cover up the change in behavior for index signatures.

**Comment by weswigham** [comment]
@typescript-bot test this again since I've fixed the constraint confusion issue

**Comment by weswigham** [comment]
So I'm in the middle of running this on DT, and I've found a somewhat legitimate bug in a dt package `activex-libreoffice` in the same vein as #26274. They have a test of a generic `createStruct` function which takes a `K extends keyof LibreOffice.StructNameMap`. They then create a reflector over that `K` and attempt to call a `createObject(obj: [(LibreOffice.ServicesNameMap & LibreOffice.StructNameMap)[K]]): void;` using a `[LibreOffice.StructNameMap[K]]` for the argument type. Today this doesn't error, but on inspection you can tell that should `ServicesNameMap` and `StructNameMap` happen to overlap for some value of `K`, `StructNameMap[K]` alone does _not_ satisfy the constraint (since it will be missing the `ServicesNameMap` bit).

I'm only 1/5th of the way done, so I can't say for certain just yet, but the DT changes have started off looking pretty good (given this is the only one thus far).

**Comment by RyanCavanaugh** [comment]
Please add repro from #26608 if it's not already covered by something representative

**Comment by weswigham** [comment]
@RyanCavanaugh added and confirmed for fixing #26608, too.

**Comment by weswigham** [comment]
@typescript-bot test this once more for a good ol' checkmark

**Comment by weswigham** [comment]
@ahejlsberg I know in person I spoke about how the one crash I found in DT while working on this was due to the recursion guard not being triggered due to simplified indexed accesses bypassing the types we guard against - rather than modify simplification further, I realized the issue was really that `isIdenticalTo` didn't shuffle nearly as many types through `recursiveTypeRelatedTo` as the paths for other relationships did, which is why the issue only occurred when identity got checked. So rather than doing the large improvement of merging simplification and constraint fetching, I've left that for a later date and simply fixed `isIdenticalTo` by moving most of it into an identity-only branch of `structuredTypeRelatedTo`.

@typescript-bot test this again now that I've fixed the redux crash from DT (there's a repro in the tests now), just in case.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -15167,14 +15141,14 @@ namespace ts {
             return type.flags & TypeFlags.InstantiableNonPrimitive && maybeTypeOfKind(getBaseConstraintOfType(type) || emptyObjectType, TypeFlags.Nullable);
         }
 
-        function getConstraintForLocation(type: Type, node: Node): Type;
-        function getConstraintForLocation(type: Type | undefined, node: Node): Type | undefined;
-        function getConstraintForLocation(type: Type, node: Node): Type | undefined {
+        function getConstraintForLocation(type: Type, node?: Node): Type;
+        function getConstraintForLocation(type: Type | undefined, node?: Node): Type | undefined;
+        function getConstraintForLocation(type: Type, node?: Node): Type | undefined {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Shouldn't this be `node: Node | undefined`, i.e. not an optional parameter? It seems pointless to make it optional since the function will never do anything if you don't pass an argument for it.

Also, when might `node` be `undefined`? Not clear to me what those changes are accomplishing.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -10532,8 +10496,13 @@ namespace ts {
             return false;
         }
 
+        function isOrHasGenericConditional(type: Type): boolean {
+            return !!(type.flags & TypeFlags.Conditional || (type.flags & TypeFlags.Intersection && some((type as IntersectionType).types, isOrHasGenericConditional)));
+        }
+
         function elaborateError(node: Expression | undefined, source: Type, target: Type): boolean {
             if (!node) return false;
+            if (isOrHasGenericConditional(target)) return false;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Combine this with line above and have a single if statement.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -9280,35 +9267,12 @@ namespace ts {
...
-                if (some((<IntersectionType>objectType).types, isMappedTypeToNever)) {
-                    const nonNeverTypes = filter((<IntersectionType>objectType).types, t => !isMappedTypeToNever(t));
-                    return type.simplified = getSimplifiedType(getIndexedAccessType(getIntersectionType(nonNeverTypes), type.indexType));
-                }
+            const indexType = getSimplifiedType(type.indexType);
+            if (objectType.flags & TypeFlags.Union) {
+                return type.simplified = mapType(objectType, t => getSimplifiedType(getIndexedAccessType(t, indexType)));
+            }
+            if (objectType.flags & TypeFlags.Intersection) {
+                return type.simplified = getIntersectionType(map((objectType as IntersectionType).types, t => getSimplifiedType(getIndexedAccessType(t, indexType))));
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I love how much simpler this is!

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Didn't need to be `undefine`'d-able at all. I probably factored the place where it may have been undefinable so it wouldn't be while I was working on it - fix't.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -14149,10 +14123,10 @@ namespace ts {
                 getInitialTypeOfBindingElement(node);
         }
 
-        function getInitialOrAssignedType(node: VariableDeclaration | BindingElement | Expression) {
-            return node.kind === SyntaxKind.VariableDeclaration || node.kind === SyntaxKind.BindingElement ?
+        function getInitialOrAssignedType(node: VariableDeclaration | BindingElement | Expression, reference: Node) {
+            return getConstraintForLocation(node.kind === SyntaxKind.VariableDeclaration || node.kind === SyntaxKind.BindingElement ?
                 getInitialType(<VariableDeclaration | BindingElement>node) :
-                getAssignedType(node);
+                getAssignedType(node), reference);
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: It doesn't now. ;) I think a prior iteration needed it. It's unchanged now.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -14149,10 +14123,10 @@ namespace ts {
                 getInitialTypeOfBindingElement(node);
         }
 
-        function getInitialOrAssignedType(node: VariableDeclaration | BindingElement | Expression) {
-            return node.kind === SyntaxKind.VariableDeclaration || node.kind === SyntaxKind.BindingElement ?
+        function getInitialOrAssignedType(node: VariableDeclaration | BindingElement | Expression, reference: Node) {
+            return getConstraintForLocation(node.kind === SyntaxKind.VariableDeclaration || node.kind === SyntaxKind.BindingElement ?
```
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: It is in the baselines - or rather, not doing this made the better distribution change some baselines, and then doing this changed them to the expected result.
