### PR TITLE
Fix renaming of node_modules

### LINKED ISSUE #45668: F2 renaming can cascade into node_modules .d.ts files for objects
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.1
- OS Version: Linux x64 5.13.12-1-MANJARO snap (This also happens on windows 10, so this part probably isn't important)

Steps to Reproduce:

```ts
// Have a file that exports an interface like this in node_modules (this is from react-bootstrap)
declare interface Form
  extends BsPrefixRefForwardingComponent<'form', FormProps> {
  Row: typeof FormRow;
  Group: typeof FormGroup;
  Input: typeof FormControl;
  Check: typeof FormCheck;
  File: typeof FormFile;
  Label: typeof FormLabel;
  Text: typeof FormText;
}
```
```ts
import { Form } from "react-bootstrap";

function Foo() {
     return <Form.Input />
}
```
Then, hit F2 on the `Input` part of the declaration - When you rename this, the rename will also apply into the `node_modules` .d.ts file, causing this file:

```ts
// Have a file that exports an interface like this in node_modules (this is from react-bootstrap)
declare interface Form
  extends BsPrefixRefForwardingComponent<'form', FormProps> {
  Row: typeof FormRow;
  Group: typeof FormGroup;
  WhateverYouRenamedInputTo: typeof FormControl;
  Check: typeof FormCheck;
  File: typeof FormFile;
  Label: typeof FormLabel;
  Text: typeof FormText;
}
```

**NOTE:** I am using the PNPM package manager, which might be why this interaction happens.

### LINKED ISSUE #48681: rename typescript default import will modify types under node_modules
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

image

- VS Code Version: 1.67.0-insider
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. set "typescript.preferences.useAliasesForRenames": false
2. install package highlight.js
3. write ts code : `import hljs from 'highlight.js/lib/core';`
4. rename `hljs` to `highlightJS`

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #45668.
I think it also fixes #48681.

The rule I'm trying to implement is the following:
1. If we try to rename from a project, and that would cause us to rename something in `node_modules/`, don't allow that rename.
2. If we try to rename from inside a `node_modules` package, only allow renames that would not affect a different package.

I'd like some feedback on the wording in the diagnostic message.
I'll update the tests' `verify.renameInfoFails()` calls once there's a definitive diagnostic message.

Note: I had to change `getRenameInfo` to take a user preferences parameter, because I needed to know if `providePrefixAndSuffixTextForRename` (surfaced as "Use Aliases For Renames" in vscode) is set or not. Since that function was already taking as parameter another option that comes from user preferences, it made sense to me to change that. A lot of the diff is refactoring related to that change.

### CODE REVIEW

File: src/compiler/types.ts [hunk 1]
```diff
@@ -8822,6 +8822,7 @@ namespace ts {
         readonly includeInlayPropertyDeclarationTypeHints?: boolean;
         readonly includeInlayFunctionLikeReturnTypeHints?: boolean;
         readonly includeInlayEnumMemberValueHints?: boolean;
+        readonly allowRenameOfImportPath?: boolean;
```
Comment (andrewbranch) [inline src/compiler/types.ts:8825]: Ironically, I think this always belonged in `UserPreferences`, and `providePrefixAndSuffixTextForRename` always should have been a per-request option. 🙃 Baby steps in the right direction...

**Review by andrewbranch — APPROVED** [review]

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -6276,6 +6276,11 @@
         "category": "Error",
         "code": 8034
     },
+    "You cannot rename elements that are defined in an external library inside `node_modules/`.": {
```
Comment (amcasey) [inline src/compiler/diagnosticMessages.json:6279]: Unless we use it elsewhere, I'm not sure the meaning of "external library" will be clear.  Personally, I'd probably split this into two messages along the lines of "you can't reach into node_modules" and "you can't reach into _other_ node_modules"

File: src/services/rename.ts [hunk 3]
```diff
@@ -60,6 +71,37 @@ namespace ts.Rename {
...
+        return some(declarations, declaration => {
+            const declPackage = getPackagePath(declaration.getSourceFile().path);
+            if (declPackage) {
+                return comparePaths(originalPackage, declPackage) !== Comparison.EqualTo;
+            }
+            return false;
+        });
+    }
+
+    function getPackagePath(filePath: Path): string | undefined {
```
Comment (amcasey) [inline src/services/rename.ts:96]: Nit: If string you search for `"node_modules"`, I think you'll find related helpers, one or more of which may already do this.

Nit: Converting strings to path components and back frequently shows up in profiles.  One way to make this cleaner might be to leave both of the paths being compared as components - I'm pretty sure that's what `comparePaths` is doing anyway.

File: tests/baselines/reference/api/typescript.d.ts [hunk 4]
```diff
@@ -5875,7 +5876,7 @@ declare namespace ts {
         getNameOrDottedNameSpan(fileName: string, startPos: number, endPos: number): TextSpan | undefined;
         getBreakpointStatementAtPosition(fileName: string, position: number): TextSpan | undefined;
         getSignatureHelpItems(fileName: string, position: number, options: SignatureHelpItemsOptions | undefined): SignatureHelpItems | undefined;
-        getRenameInfo(fileName: string, position: number, options?: RenameInfoOptions): RenameInfo;
+        getRenameInfo(fileName: string, position: number, preferences: UserPreferences): RenameInfo;
```
Comment (amcasey) [inline tests/baselines/reference/api/typescript.d.ts:5879]: It feels like we could keep the old signature as a deprecated overload if we wanted to avoid the API break.

File: src/services/rename.ts [hunk 5]
```diff
@@ -43,7 +48,13 @@ namespace ts.Rename {
         }
 
         if (isStringLiteralLike(node) && tryGetImportFromModuleSpecifier(node)) {
-            return options && options.allowRenameOfImportPath ? getRenameInfoForModule(node, sourceFile, symbol) : undefined;
+            return preferences.allowRenameOfImportPath ? getRenameInfoForModule(node, sourceFile, symbol) : undefined;
+        }
+
+        // Disallow rename for elements that would rename across `*/node_modules/*` packages.
+        if (wouldRenameAcrossExternalLibrary(sourceFile, symbol, typeChecker, preferences)) {
```
Comment (amcasey) [inline src/services/rename.ts:55]: As in the message, unless we use "external library" with the same meaning elsewhere, I'd say something like `wouldRenameInOtherNodeModules`.

**Review by amcasey — APPROVED** [review]
Minor suggestions, plus some thoughts on avoiding the breaking change, if we think that's worthwhile.

File: tests/baselines/reference/api/tsserverlibrary.d.ts [hunk 6]
```diff
@@ -5877,6 +5877,8 @@ declare namespace ts {
         getBreakpointStatementAtPosition(fileName: string, position: number): TextSpan | undefined;
         getSignatureHelpItems(fileName: string, position: number, options: SignatureHelpItemsOptions | undefined): SignatureHelpItems | undefined;
         getRenameInfo(fileName: string, position: number, preferences: UserPreferences): RenameInfo;
+        /** @deprecated */
```
Comment (amcasey) [inline tests/baselines/reference/api/tsserverlibrary.d.ts:5880]: Comment about using the other overload?

File: tests/baselines/reference/api/tsserverlibrary.d.ts [hunk 7]
```diff
@@ -6255,6 +6257,7 @@ declare namespace ts {
         Insert = "insert",
         Remove = "remove"
     }
+    /** @deprecated - consider using EditorSettings instead */
```
Comment (amcasey) [inline tests/baselines/reference/api/tsserverlibrary.d.ts:6260]: Could be a bad diff, but I'm seeing `EditorOptions` deprecated?  What changed?

File: src/services/services.ts [hunk 8]
```diff
@@ -2537,9 +2537,9 @@ namespace ts {
             }
         }
 
-        function getRenameInfo(fileName: string, position: number, preferences: UserPreferences): RenameInfo {
+        function getRenameInfo(fileName: string, position: number, preferences: UserPreferences | RenameInfoOptions | undefined): RenameInfo {
             synchronizeHostData();
-            return Rename.getRenameInfo(program, getValidSourceFile(fileName), position, preferences);
+            return Rename.getRenameInfo(program, getValidSourceFile(fileName), position, preferences || {});
```
Comment (amcasey) [inline src/services/services.ts:2542]: I thought you said we needed to handle old-style calls specially (probably by skipping the new `node_modules` checks)?

**Review by amcasey — CHANGES_REQUESTED** [review]

File: src/services/services.ts (hunk 8 above)
Comment (amcasey) [reply src/services/services.ts:2542]: We clarified offline that the scenario I had in mind doesn't really exist for API consumers.

**Review by amcasey — APPROVED** [review]

File: tests/baselines/reference/api/tsserverlibrary.d.ts (hunk 7 above)
Comment (gabritto) [reply tests/baselines/reference/api/tsserverlibrary.d.ts:6260]: It was marked deprecated before, but with a normal comment (`/* */`) as opposed to JSDoc (`/** */`), just a drive-by fix.
