### PR TITLE
Handle `!` following a keyword in isClassMemberStart

### LINKED ISSUE #20604: Using bang operator with a property named "type" causes errors
**TypeScript Version:** 2.7.0-dev.20171209

**Code**

```ts
class Foo {
    type!: number;
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

I get a number of errors, including "Cannot find name 'type'", an unexpected token error on the `!`, etc. 

This does not happen if I change `type` to any other word.

P.S. I've found I can work around this like so

```ts
class Foo {
    "type": number;
}
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20604

### CODE REVIEW

File: tests/cases/compiler/parserIsClassMemberStart.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+class C {
+    type: number;
```
Comment (weswigham) [inline tests/cases/compiler/parserIsClassMemberStart.ts]: This test is missing the `!`.
