### PR TITLE
Fix crash when `this` is typed as a generic `T` with no type constraints

### LINKED ISSUE #47965: Crash checking protected method accessibility: `Cannot read property 'target' of undefined`
# Bug Report

I'm getting a compiler crash. It looks like it's trying to verify the accessibility of a class's `protected` method. I'm accessing it from a method in another class, and am accessing it via the lexical scope. I think this is related to the fact that I've explicitly defined the type of `this` to be `T`, if I remove this it doesn't crash anymore. Surprisingly, if the member is either `private` or `public` the result is correct and it no longer crashes. Please see the code sample below.

### 🔎 Search Terms

I searched for issues tagged as "Crash", of which none seemed to match this issue. I also looked around using variants of `is:issue is:open "Cannot read property" "target" "of undefined"`, and I couldn't find a similar issue.

### 🕗 Version & Regression Information

- This is a crash visible on nightly, I tested today on `Version 4.7.0-dev.20220218`.

### ⏯ Playground Link

As requested, here is a [playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4FlgZQc2DgG8BYAKDirjCghmAQYBM41GpgYAKASgC44ANwgBLVsTgBfCjPIVQkWIlQZsuNAWAB1KCjBhgUEhWpwAthq2CceQgG5T1AO56wAHgAqAPj4nKZtRIXBZwALxwMAAWomgAdJZ2wI4BgXDB8ABm4XCZAK4AdkyiEAXc0bGCnrz+aWnmcewInDy8KXXSTlRyUkA), but it's not very useful as the website becomes unresponsive due to the `tsc` crash.

### 💻 Code

```ts
export class Message {
    protected secret(): void { }
}

export class MessageWrapper {
    message: Message;
    wrap<T>() {
        let m = this.message;
        let f = function(this: T) {
            m.secret();
        }
    }
}
```

### 🙁 Actual behavior

This input causes `tsc` to crash with the following error:

```
/c/work/tsc_crash$ npx tsc -v
Version 4.7.0-dev.20220218
/c/work/tsc_crash$ npx tsc ./message.ts
C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:95457
                throw e;
                ^

TypeError: Cannot read property 'target' of undefined
    at checkPropertyAccessibilityAtLocation (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:60898:114)
    at checkPropertyAccessibility (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:60839:20)
    at checkPropertyAccessExpressionOrQualifiedName (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:61159:17)
    at checkPropertyAccessExpression (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:60967:17)
    at checkExpressionWorker (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:65661:28)
    at checkExpression (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:65582:38)
    at resolveCallExpression (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:62615:28)
    at resolveSignature (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:62988:28)
    at getResolvedSignature (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:63008:26)
    at checkCallExpression (C:\work\tsc_crash\node_modules\typescript\lib\tsc.js:63117:29)
```

### 🙂 Expected behavior

Because this is a protected method, it shouldn't crash and instead return an error indicating such, ie:

```
message.ts:10:11 - error TS2445: Property 'secret' is protected and only accessible within class 'Message' and its subclasses.
```

### PR DESCRIPTION
**Pull request by jihndai**
Fixes #47965 

While checking a protected property's accessibility, the crash occurs because `getConstraintOfTypeParameter` can return `undefined` when `this` is typed as the generic `T` and `T` has no type constraints on it. The fix for this was to check for `undefined` and refuse access if it was, as we can't guarantee that an instantiation of a generic `T` can access protected properties when `T` isn't constrained to any class/type.

Additionally, the explicit `this` type was also skipping through derivation checks done by `isClassDerivedFromDeclaringClasses`, which led to some inconsistent behavior shown below, so changes were also made to address this, but please do correct me if I'm mistaken.

```typescript
class D {
  derived1(val: D1) {
    val.d1(); // currently shows an error, as expected
  }
  derived1ThisD(this: D, val: D1) {
    val.d1(); // should show the same error as above, but doesn't
  }
}
class D1 extends D {
  protected d1() {}
}

function thisString(this: string, d: D1) {
  /**
   * Error message seems misleading:
   * 
   * "Property 'd1' is protected and only accessible through an instance of class 'any'. This is an instance of class 'D1'"
   */
  d.d1();
}
```

### CODE REVIEW

**Comment by jihndai** [comment]
Just noticed that `private` fields ignores the `this` parameter, while `protected` fields take it into account. For example:
```typescript
class A {
  private privateMethod() {}
  protected protectedMethod() {}

  otherPrivate(other: A) {
    other.privateMethod(); // works
  }
  otherPrivateThis(this: A, other: A) {
    other.privateMethod(); // works
  }

  otherProtected(other: A) {
    other.protectedMethod(); // works
  }
  otherProtectedThis(this: A, other: A) {
    other.protectedMethod(); // works
  }
}

function otherPrivate(other: A) {
  other.privateMethod(); // doesn't work
}
function otherPrivateThis(this: A, other: A) {
  other.privateMethod(); // doesn't work
}

function otherProtected(other: A) {
  other.protectedMethod(); // doesn't work
}
function otherProtectedThis(this: A, other: A) {
  other.protectedMethod(); // works
}
```
This `private` behavior seems to be consistent with Javascript's `#` private fields, where `#` private fields cannot be used anywhere outside the declaring class declaration's scope. Is this working as intended (in regards to `protected` taking into account the `this` parameter) ?

**Comment by jihndai** [comment]
Nevermind, found the issues talking about [private's behavior](https://github.com/microsoft/TypeScript/issues/17694#issuecomment-321419410) and [protected's behavior](https://github.com/microsoft/TypeScript/issues/10302#issuecomment-241579000) in relation to `this`.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -28290,6 +28290,25 @@ namespace ts {
...
+            }
+
+            if (thisType && getObjectFlags(thisType) & (ObjectFlags.ClassOrInterface | ObjectFlags.Reference)) {
+                return getTargetType(thisType) as InterfaceType;
+            }
+
+            return undefined;
+        }
+
+        function getThisTypeFromNodeContext(node: Node) {
```
Comment (sandersn) [inline src/compiler/checker.ts:28307]: I think I would inline this since it's only two lines and only called once.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -28251,14 +28251,17 @@ namespace ts {
...
                 // allow PropertyAccessibility if context is in function with this parameter
-                // static member access is disallow
-                let thisParameter: ParameterDeclaration | undefined;
-                if (flags & ModifierFlags.Static || !(thisParameter = getThisParameterFromNodeContext(location)) || !thisParameter.type) {
+                // static member access is disallowed
+                if (
+                    flags & ModifierFlags.Static
+                    || !(enclosingClass = getEnclosingClassFromThisParameter(location))
+                    || !(enclosingClass = isClassDerivedFromDeclaringClasses(enclosingClass, prop, writing))
+                ) {
```
Comment (sandersn) [inline src/compiler/checker.ts:28264]: If it's OK to run the checks even for static methods (and I think it is), then the below is much less surprising to read:

```suggestion
                enclosingClass = getEnclosingClassFromThisParameter(location)) || isClassDerivedFromDeclaringClasses(enclosingClass, prop, writing);
                if (flags & ModifierFlags.Static || !enclosingClass) {
```

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -28290,6 +28290,25 @@ namespace ts {
             return true;
         }
 
+        function getEnclosingClassFromThisParameter(node: Node): InterfaceType | undefined {
+            let thisType = getThisTypeFromNodeContext(node);
+
```
Comment (sandersn) [inline src/compiler/checker.ts:28295]: extremely minor style preference: I think the blank lines in this function should be deleted.

**Review by sandersn — CHANGES_REQUESTED** [review]
I think the basic fixes are good. Just some minor style requests.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -28251,14 +28251,17 @@ namespace ts {
             // of the property as base classes
             let enclosingClass = forEachEnclosingClass(location, enclosingDeclaration => {
                 const enclosingClass = getDeclaredTypeOfSymbol(getSymbolOfNode(enclosingDeclaration)!) as InterfaceType;
-                return isClassDerivedFromDeclaringClasses(enclosingClass, prop, writing) ? enclosingClass : undefined;
+                return isClassDerivedFromDeclaringClasses(enclosingClass, prop, writing);
```
[the remark this answers is not in the document]
Comment (jihndai) [reply src/compiler/checker.ts:28254]: correct just a cleanup, shouldn't change the behavior at all.

File: src/compiler/checker.ts (hunk 2 above)
Comment (jihndai) [reply src/compiler/checker.ts:28264]: Yeah should be fine, at best it was just a very minor optimization to avoid fetching `this`'s parameter if the field was already static.

Comment (jihndai) [reply src/compiler/checker.ts:28264]: `getEnclosingClassFromThisParameter` can return `undefined` while `isClassDerivedFromDeclaringClasses` doesn't accept `undefined`, so I'll have to do some type checking with this style instead:
```typescript
enclosingClass = getEnclosingClassFromThisParameter(location);
enclosingClass = enclosingClass && isClassDerivedFromDeclaringClasses(enclosingClass, prop, writing);
if (flags & ModifierFlags.Static || !enclosingClass) {
```

Comment (jihndai) [reply src/compiler/checker.ts]: Also noticed that the name `isClassDerivedFromDeclaringClasses` may be a bit misleading, as it doesn't return a `boolean`, but instead it returns the first parameter if checks succeeds, otherwise it returns undefined.

Not sure if we'd prefer changing the name or not.

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Maybe as a follow-up, I'd rather get this change in.
