### PR TITLE
fix formatting for chained callbacks

### LINKED ISSUE #1917: TypeScript 1.4 indentation issue on chained function calls
Before we would have:

```ts
var doSomethingThatReturnsAPromise: any;
this.doSomethingThatReturnsAPromise()
    .then(() => {
        // more code
    })
    .then(() => {
        // even more code
    });
```

Now we have 
```ts
var doSomethingThatReturnsAPromise: any;
this.doSomethingThatReturnsAPromise()
    .then(() => {
    // more code
})
    .then(() => {
    // even more code
});
```

Raised from [SO](http://stackoverflow.com/questions/28298624/typescript-1-4-indentation-issue)

### PR DESCRIPTION
**Pull request by vladima**
fixes #1917, #1888

```typescript
foo
    .bar(() = {
     })
```
in cases like this nodes are processed in order: `CallExpresson` -> `PropertyAccess and its child nodes` -> `ParameterList and its child nodes`. Fact that indentation was inserted before the '.' during processing of `PropertyAccess` should be respected later when we return back to `CallExpression` and dive into `ParameterList` however this is something that was missed.

In this PR when token is indented we record line/indentation and later when computing indentation for the node check if current line was already indented and if yes - use actual indentation.

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -416,7 +419,7 @@ module ts.formatting {
                 // if node is located on the same line with the parent
                 // - inherit indentation from the parent
                 // - push children if either parent of node itself has non-zero delta
-                indentation = parentDynamicIndentation.getIndentation();
+                indentation =  startLine === lastIndentedLine ? indentationOnLastIndentedLine : parentDynamicIndentation.getIndentation();
```
Comment (DanielRosenwasser) [inline src/services/formatting/formatting.ts]: split into multiple lines

**Comment by DanielRosenwasser** [comment]
:+1:

File: src/services/formatting/formatting.ts [hunk 2]
```diff
@@ -416,7 +419,9 @@ module ts.formatting {
                 // if node is located on the same line with the parent
                 // - inherit indentation from the parent
                 // - push children if either parent of node itself has non-zero delta
-                indentation = parentDynamicIndentation.getIndentation();
+                indentation =  startLine === lastIndentedLine
```
Comment (DanielRosenwasser) [inline src/services/formatting/formatting.ts]: Stray space after `=`

**Comment by vladima** [comment]
@DanielRosenwasser any other notes?

**Comment by mhegazy** [comment]
:+1:

**Comment by Gitgiddy** [comment]
:+1:
