### PR TITLE
Optimize union type creation

### LINKED ISSUE #53761: Slow typings related to large enums
# Bug Report

### 🔎 Search Terms
Slow, enums, large. Related issue that looks similar: #42824

### 🕗 Version & Regression Information
Not sure when this started. I'm testing on 5.0.4

- This is a performance problem

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?target=9#code/KYDwDg9gTgLgBDAnmYcAKBDWBLDAbAJWAGNoATAHgGk5QZgA7MgZzgYFcBbAI2CgBo4ANQB8cALxwA3nADaAa2CI42BnCoBdAPwAuYXAC+AbgCwAKHOhIsWh05wAkvU4AVZKinm43uADkIDMD8Xj4A9KFs0Jz4Ks7MId4AwhBg+MFmPnAAggzY0XgAyvLseHjpmQDiUBi59FlQUBAA7uU+VTXYdQ3NABbAGGSt3mjYeMAA8gBmWcw9Q3AAQljyADLAAObrquvM80tQ8gU92MB4gwmLyy7sucR7AUEXC9UMxHMXiRjEMOzMBWCqYC7D49LCkNIXdq1YAAMTwEGg23myQgijIAFl+jB5gBRLAwHpNKLzGFYvoCC6knB4bAALz48wA6hh6FBmPJVFMCv0miyGZTsFBgGh4ex1u8Mj4Fht1vjsMRDsBgCwSRBmMxRvMKhAzslVMDJd5tWdGIlQTTiI9DXBjWRGAQkZCdWQCkSoOdre11dzlQbMg5GgxxkKmQi7QwACLNU5+tovTpWzJrDCTaVkRqlebJgl8AAS2DtWf6ADcgVm8kCYA8sxB1lr4-R0dAYFgcmQ0JWxnt2DAqwx0b8eo0IJxY95-KkyhcOyz5gUaiw+4mfCMxlN2qWp9bVxNU-03vOmKGIOH6o0WpCG8AsiBl94lkwMOs73BGRBSwwYRhuFB5civj8zC+EqZBdpeHT0Ec76nMe4b-P0FLWgUPbsCGFwECm2LoRgTSYrO2HMGAvANCcY5wHCiBZNEtQYPMBApC+6IYGAYw+iqTwDHaUDwgqZFHFgYAVHgGDqnOoJQIJV5zsUpTEMxc6cAiBJQgmc4QJq4HQvBWBzkuZEqfQzKZhcBQwL+DB1iZZnYGAKBkPs8jzC4NSBGQ2bkk5LmqPM6KjPILjHMwMCsSBZEuEKwAOfMuYPIgMI3OsvzImM0QwNgzBCICTlNNgOxMnybIcgwsGMGgOovjOMAPmQT4vgszT3E0Ea-sZ1owulxwWcBWHWhhTTJB6mQomiA31hBwCfJwYCTIKL6ZYEjLHGA8w7lyDANRxBwuNAbzllVVw7RKmS5guzWjFumQFPkeBLJZSHmi+-ESYwyr1YE9aqIu1bYU07WzKZ-SOR8CJon9PQAxgQPWsyrLspykwRkC+CqHyZAw-y1r1SymBkKBdUlDdED4b1wAza5h6DT4-yIOswmiehwBVrAdE4YkwmICz-Xsws8JNACKDJRgiA880-Mvu5fDSngPVJmSfDXLcRYsuS9UQDAZES1AnzLRcmvalAz4yz4muYAw6tKzmUBCdB+lXvFUAMF8j0LkFDxUKMxUXAGATbRZYX4HcFzOXgxBcGVTRcSVDAU58QVwiJUOywwZEijUMD0WrGsQAqAIKvcgTAcqYHboCzEsS+zm9nwypMTr1rJBC0ONGKPQwN7nvWisFau4E4eR17gYOBZat7F88ipHn6Fq-Q-ZYmN0InZwnAY5kfVmvKigd0NIPKuvCqMPPCY5MWGnQ2Gpp9EF8zt665DX4Gzz9EFLF8vfASq+bA8BLmpzL0b3jt31obN+DBEjsHSswMsX8GAVAwDcYKjMyLtx-gVOcLslxGQulTdBDw4QInMndS6AIuIFD8vMHIeR8Bfn-nAYOvNtpQF2h8dm8dFC2yVNHBc8xxhnCHkFKA7BvjYACPgAoxAMxYO8AUGky8KinBZN5EyMjgBCXYC+Yayp-gFj4HhGhWiuK6JASsbO48N50WntsIQGxGYKICMiY4pYkGBkXsvRC-pAzaTcT4G+PRoKSMcIGKM7BuBjBvC+duIwFQYFvNfBg8ggpmOBqQDgNDMB4E4MmSY3DJiTEbpkN6sJqjrGXmbDWnQypjAYUw+u09346n8ckXsAQ2JkUaX2L8P4-xPAeBUiuEBUK5AAI5qJoYyZu4o26BkifIaJL4xn9Ime3IJITrwxIuPMlukzmm+M3EycZrcb4oB0us-ZWyGAuJXj4DZizAzGJzokpuCyDkeOOKcSm3hrnPICLA+BYxP6PM2e3MBECoEApud86AwCTlPLOT-dJjM9kwvbh-MinyzmPxEjAF+9BEWAo8W6d5r5z4MEwVHPBiILJRyjNAEkHVtj0UJZidUtUh5ZHqr2YuQ0sDcACH3S5wxRi7mSFNNUNDMTS13ikPJVziX8RPn7Q+9BEYDFya1S6js0LQwKnDIMkxMRkHlCjPA6MvFJHEuCG6C5apR19nlaFeKfYBDtfdJUMB1x0z4jqLAplzqKuACan1aq4zjWQkwXA-iu4wDoc0KpR0qaAgvPdZs9VE1JidSm5EI5IAanoBm9Z2qipTDQKhbAM1lQwiFLME1+VYaFsmAAVQYGAEtZayAVqBD0atkIPXsoQZmg4Woe3TzXJMbkOFUHdpEswXtI7EbMGRo7egaMJ2eiHRy3c+rDWO2NSuyoa6EFFpbScNtlbO27raPukdjbm2-lbe2qt56PmnPbmeDa1oX3dFTcG6ECwCYIvteChgv7Sj-vfQ-P9NDNYAEVwGllNXAHE3wUh004D5J88p8A4nVIwS0ZKcPqKFCyVCwAHBkB1P2u0LoaSUt1nLKA0jHRgq+QwV9TQ+gDBAax9jhKXEmMzU0oDyoJEkjo2mYTP1nKqCXYY4GqJlSSbNjXOemkExUFyJMF8fUeafRmrMTNcn7LUbILpuNwxgBLww1vHwGj2zmc4JZtBp9LoYFGDy4mQ1jj7wYDiTY9xBVkD3pvHzhCqbscmFME6HMLi+ATPB+c0sUCsj2MJBUfL4NwikzxeQIxXb+IqNgFZ-zMg4nAPCDUpZwryRMooP5+AmLPmZEeH6bMhYACkxSC0QO1kLSR2bda5DyR9cAWtdbFFMOdC7UZdvrn1sberlRbvwNNoas31iHtvce+9Z6kvMLa3N69R7y2nuWz4Ne3NfyTxm0LZ4DyVtC1JbtuK8IKU9fQKXWyIVfQs0IsRKAiAWkrQu-IPAiAZz0dCslczCi-gQ+nMxPgRxXUrXh1AJsZw9gyjlLxHyfkArpQQXgpofAyLNRwv2Kr1pK6sl3vCAkRxBQ0Kp9XALtOejhX6ZAtkUdYE4unOpZgAQHDFkQMmRxK1+eC+FwDgDzGzSVhAXLq+JkcowDeOsao3pYfWiyB9x6xC+DBf9qMUkytifkN19L60Vj1qcCElwi4wZF3+uJYrmh9FShTCIAFgSoHMiO75NrF87UhQ804vym0zpGBUCUFHW+7pOvuzwFZ3rQtJrTVmp1+2jtcOPYDWlINUicGBDTzNTVzmmA91hAMp2aCK8YIKoGvLV5E-J9fM+wMx8nPeI7wwE+-j6vAHorwbhUBuBTCHpMPAajXgvgofkFrX7vBz-wB2aW5Dcj5HtnOOSYw+LiXkO1VvfUiBgHz8AGTNSDMn7PxfzILhGAtmILv-TaJ79my+M-9ZURb-WZ3mjb-ymnoV40ysyuKgGYSnGaybUfAZ+BQ6kTe40MUcy7e38EA4SziaBWYGAxYGA0ojMYwcKf8c4YAAiloyQ70JkJBgiwAluRCpBwAhceMrSyAlazA5B6iLBQIMOX2HwnB6oouoKssvY1BRYwhlotB1mDiNBWumQZULYVY4u8hEAEhSQWAjQNCnw3QMAKhw20A3mxyNSDsOhYCocPA4eJhXAxEOh20qUEATkI4LIyhMhK4XAYARUK0rhRUOhaAQOIOYOFa4CeiYoWAnwgQpk+A8Sc4wRWsNQ0hPBmMg4pwUwi0gBmQKR7mv+BmchjhL+kqDsyQ3A3YTAI6ronQauGurS8IkMUcTYsArYTAHYQUnK2CdeDwtRLYUAbYjRfaMuZy7R9RtmTR6BAQ-RnRDRnYmmrM7MoxXRExnWMx4xQxmatkfAwY6iKQKAUAQ86wI8wMKxUAIBUB28+xyyoSRxv++xUEuyexmxniyxmxFy8GyQ+xdypil2xxmxv6CoYwTxGxfAPyZsfyrSfxVshGYuNx-xkKvuFxDxv80JSQIJKK9xfAwKFRyJ9GBK6JtqwJ+xrG6JwGfy6JXG-QhKzxmxruRJveXeCJuJ5xNJDxmBEJqOzYAx3RzRHyBa8M2oLIvkeAic1mq264RMMAvJ-JRol6u43JIpZCDu3AGoBqNQI+TuPMaiqsYpcArW-SDs0q3gTY6oyQcGr0IMWoowlGXuap5Cn6-EkweiNIlsyE+88GWQv2acDG9pgiigcWZkOEJ0NCoeOcwkkE34jhycyWY82KkUhGz8gZdUKW48MZAJCCRWUocZEZQC8JiwqZCZYJghKZ4ZMZhBGZyqBIamuUrcEBFwTEocGAPQgR-i4wcpBYuALGn63CjZCpLZ543GbZ8pzZFZ1oDZvZNQpZGmPZTZNQVxMEspQ50cRy8G1wPAYwROmizhCJySPYuYvw6pHYpwkq65Gh2cAQPYP+a5R5MA5BLYgIUAUwyQ+5J2p5KSF5LmgQvx+5T5V5A246O2NSb5AQl5L542SM1GU2Q2t5Z575AF82BqxARq95uhv57+H5kwxaG2R2HacFYFj5f5z5qxDaTah2J66FoFh5WFiFkFUpop3CZwOIZAgiti26Yi4mSE1kKxbkdGnWMcmK8c7IteX0YRC4scMA3F6pBkNBAlXFdM6py+eAqi6xk4RAGoreBSeE-iq0CMQIMBFM8wmpsw7AGA4USoAhZEOltZ+lEUARnQ2laoplBlcR7El+aIJleltlFlNCTlZlSohOZuJkT4eljQnw3wvwrlaCiUWAEAAVgEOh84oV-lAEvwZoNwIlV4jIpw-iFMleKVBew27MmV-iWQ8IwAVi1QRl5CBVRVGAOhyqLopAEkwireVVzpfALw2hNVAIdismaIYi0AbVreNmjVDQrprVdV2+3VdVPqFk5hiJkM2wlWUWTG6K01Fks1ICSwRU6wy1lIoo8GQS4o0UWAZAj+6p+YqunU6wZUSu90QouMyomAmxnMA4LAHI+xnM-VzVD1cMz1HVNc7Aj1Nkd1X1ZAr1ac71T1-1vUOEXuBQjsn1DlyokN0NYNq8OEmCSg6xBmKNiAcysqry6OTJRAZM5mD+20OoqKKBDA+NgIJSUaCIeATiAQFNgQVNxNtN2++AkUpweiO+hV8uJkXNSJvNbN2srNYw0oxYNKAtYwawmw2wfEXN1s4JsNZA7lLlvM3lSEvlYVEVvwDocpYZdozA64aJFw0lzUGxMt6+lCeAEYCUWoel60nkpQb6d++AvMoReMe00a-UC47Jr46UYA1tF1mQ9WGGeAMwKA3wWoke0cdAacnMZofxbaHUuRAWvirFYMydYM0e3A345CswiQhNZsudPQ+dVNN27xPgMwxdBdQlz2BCRdJdD+D2764h4khKHYFk4C3mvm3S-m7diUqgwWnMfdndJ5uhWRjA-ds8GRSQ54v2pEydiQs9TV89HwS9DQ-2q5vtimo+y9uZHyUmfAv2G98RmQ9QQixAZUtkK92ujCaUF9Gxx99lshgofIvppVaB5V1U1qJk++xNBI6JI5yBSKgYgDICoDQcnIZePgLgqg2xuxlOqghxFcqgpxqyyD0cOyU5CDs5CETkqgjxeDDArxuc6pMDGDJwuN2D8te9tCqgZocC2GYUqgot4t2DhZjOqgMISkz4Bhd+dD4CRt2DcehKZD2JhDeJEDQGEG4jn63ZkjFJkjne-iZD-ZfD5yjJ2DCxgxPR2Dq1M11Qc1ajDN1dzNTDDA4DmMgY9IcDfpVjwoG8oBTwdjqDqjUodjk5-izwAQ9IdxTj3jwABDfjDA9IxDt2bj-j7skEONhKXjwTKicCgJiCewdjVQJYNDsT9ILD8GGTATcJtj-j-Nlj-jru9Qik2T7jmJQT9IYjVT14rZtTBJGZOTxJHGtTCjRTcTSjyT-jrj94djSB3TcTWjbJdUdjejS1Bjgz9IxjTNNNZEOTFj-oloZd6pUNzQKz18loTdSzsItdjG6qzQ2zVM60v0ezNG9cyMWw60vwjFFOQd6GO+JW3pEdP9eQri2w7UxEZEwdO+LgOUFB6trRgQgTgLfFkU0jPlQL14VJaVJzYiWAJA54JIjQ9In4u+pm2QG++A1wPF6yxw9AIwxe300M+L9jYRm9i0CYhLDBIEn+bUqEDcNC9svkVcoZlIqEhT+SgoZAptV9CqFwJ07oL0AW8BaGWwO+Cwn0+zFdUAZTmiXNZEfUpsOx1Go9NmyrOoqgo9pT0A8rbNUsNCOrV18LYwVigdMrcr1V+rSkZERrerYwi9zQredrVrItwAYtTpsrurrrE04CjDlplrJrKi8ICtajjBPtZJfA4bQDDqDA0bIC8btTiblO7ANpBtkwzkFkYwcjlONQtMwA3GOhjIftrKdu6oM6s+LpZsxbhEpbEpTIJbLGI23W5CVbMANbYArKzbHW6yjbWQmFPYEF4eQN1bfbA7552FV5DbtbLGJqOqrbTVacHbrKc77hVk1QTQ8LQo4iTt1mcVfwck27SLzCas4MxwzMJ7BI7OvwatmQjav4KAt1QstEcOqQiAL724zEz73h+AX7wk2AFaAQbdv7k4Lm-wur8zPYfYA4sww4nA4HlaJIIOVEEEFV1g6T1Qi5E0549VywzwGAWHjrTQvVtSreq78MroBHYAcFZb06w6u4lHU0GFgpo6vITHxFCF-5uFjH1HQ25Huq7UEqV1NHEpUwgn1Oy635d2o2a2kw4nzOGFJFg7k7kF8nwnoFLCowUnLRYLvTcA6VS4HjYkAkBnxLl0ikp7pnAL5eYLvjoLleizOnleSDvFleAzkLYLVVqqaVReNBNwCp-ib4J4pUwkcSUcKRWDaRxKN4PtQX4YvkgQh7oyxKGE1JRKwXDAlW5d3gZDEXyjqgMX6DCXJA+IhDqX+XmX1Q2Xuh+xeXRJIAEbIJxXSX6J5XWJVX6paK7cdXvRL6DXMbgGzXpXvXgYbXI3PsHXICPXYGAQhXICQ3F7M35NLm-i7cWX6pOT03+Sdjc3tTC3+TcTY3HT1Tk3HE860sEjmMIk+AMALTMT13a+Z3N3wzcxT3F3dJlw532hmDaV4kYASwX3CkSkPQAPN3o8X3dn+SD3Nd+C0r940PRz8PX3JeGeb3Ql1eOeV3X3ILUPX3XTaPXnLt4PN3eevqaPoaAXxP0sjTfp0PjnSPN3LeVPMALnaP7nWPN3nFccklzPuVNqHXPOjEzo-2O7WV6IiAQUfAwivwmAjCPQVNYrIdfC4iNkaU7VFzvYK3JVHwLIl5hQvimc-4mvxuqtXOOvxvhQm9BRKyle5Kdd+arIXcNINDD1xB2Anpg4iOysfEAIHv-0FLxKapckkCfqXcEyviN7rnS4YfrcEfIfj2MfBIHOdU0PifcfWNGXnwz4JIBMcXpo392DWfQeBMZDRf6JZf7LpQkbMR2f43oCBfmQ8UpQXXgYFfS3bfjfBMQKDf4TcTHfPgTfN0dj-fS+Zh85Wp+QWUQcUqtI3Ck4aCtk57GfZAxo5m7UiUUDKeiAq-nA6-xGfqO-e-m-+nvnh-uU+-aPZ-G-lbi71bYYV-F-2ubbI2D-x-I7MAolr-N-A1ZsVnKi5Uu-c-m-zbag9pYX-dIAYHMDmAD6UAXJJaEcD34go0gC4N6WTiTAogzAXQOgDlD4AiANVSgE4HMxuABYjgZwMQOAAiBTAZgSARYDMDJIkBCYTgHoAcCID4AkgTwNaFQHMB0BsrZgHoA4GZBMgsgQga4HcAAA6CMHh0w4rIiODADQMwLIHiCbM+iHRKkR8A0DjAUAugQEAYFxA9AsvNKLgJIDkAKAIg8gYIBYGVgxA7Ai4MIMUEoAxBf-XKvINiDmYIBVAywOAGbBwBJgNwIRAEAQCVhKsaAqIAAApGB5AgAIwKCiB7gQQBEPcAAAmGIaIJQAABKZAdaHCAIA+gcAXgLzDgDUZUA6UOAMwF5gXB6B8ADoobAkCuDRwsgBISgEiHaAxBXAngaOC0BiCGh9g4AIkI0AeDrQ9A8qGIPhDrBQhAAA0mCNB7AAAEikCNDgAkQgwAgAgBwA5hCwxIcsIAC0YgOYdUMZgGBxhaQqgTQKAA)

### 💻 Code
The code is in the playground link. The exact tsconfig.json that I'm testing with is:
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

### 🙁 Actual behavior / 🙂 Expected behavior

The code in the playground link has an enum containing 753 values and contains the following `ITest` interface:
```typescript
interface ITest {
    transforms?: PartialRecord<ItemType, ItemType>;
}
```
where `PartialRecord` is defined at the top of the file as:
```typescript
export type PartialRecord<K extends number, V> = { [key in K]?: V };
```

Running a trace build / analyze results in:
```powershell
PS Z:\Data\Downloads\test> tsc --generateTrace tstrace && npx analyze-trace tstrace --forceMillis 100
Hot Spots
└─ Check file z:\data\downloads\test\index.ts (259ms)
   └─ Check variable declaration from (line 777, char 11) to (line 777, char 61) (189ms)
      └─ Check expression from (line 777, char 20) to (line 777, char 61) (186ms)
```

The hotspot is line 777 - `const target = items[itemType1]?.transforms?.[itemType2];`

image

Now if I change the `ITest` interface to the following:
```typescript
interface ITest {
    transforms?: { [key in ItemType]?: ItemType };
}
```
(I'm essentially using the same typing that `PartialRecord<ItemType, ItemType>` provides)

The performance is improved now, it's 2.5x faster. The self-time for the expression on line 777 went from 171ms to 66ms -
```powershell
PS Z:\Data\Downloads\test> tsc --generateTrace tstrace && npx analyze-trace tstrace --forceMillis 100
Hot Spots
└─ Check file z:\data\downloads\test\index.ts (153ms)
```
image

My codebase has a lot of large enums, so this matters quite a bit to us in the overall scheme of things.

Is it possible to speed up the typing in the case when we use something like `PartialRecord` with large enums?

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements two optimizations to our union type creation logic:

* When resolving the type `Record<A, B>[A]`, where `A` and `B` are large union types, we end up creating a union type from a list of types `B`, `B`, ..., `B`, where `B` is repeated as many times as the size of `A`. The union type creation logic collects the constituent type list by "flattening" each `B`, which ends up generating a lot of useless work. We now detect that we've already processed `B` and ignore all but the first occurrence.
* We now cache the results of unioning a pair of types, where one or both are union types, by a key constructed from the two type identities. Previously, we'd first flatten all of the (non-union) types into a combined set, which is a lot more work for large unions. This in particular helps for repeated creations of `U | undefined` where `U` is some large union type.
 
The check time for the example in #53761 effectively drops to zero with these optimizations.

Fixes #53761.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Review by jakebailey — APPROVED** [review]
Very nice!

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16412,6 +16419,22 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         if (types.length === 1) {
             return types[0];
         }
+        // We optimize for the common case of unioning a union type with some other type (such as `undefined`).
+        if (types.length === 2 && !origin && (types[0].flags & TypeFlags.Union || types[1].flags & TypeFlags.Union)) {
+            const infix = unionReduction === UnionReduction.None ? "N" : unionReduction === UnionReduction.Subtype ? "S" : "L";
+            const index = types[0].id < types[1].id ? 0 : 1;
+            const id = types[index].id + infix + types[1 - index].id + getAliasId(aliasSymbol, aliasTypeArguments);
```
Comment (jakebailey) [inline src/compiler/checker.ts:16426]: Actually, now that I think about it, does this need to take `origin` into consideration? `getUnionTypeFromSortedList` seems to do a lot more for its cache key and it feels like it's possible to write `number | string` and `string | number` and now have the the way it's printed depend on the order in which the two are evaluated.

Comment (jakebailey) [reply src/compiler/checker.ts:16426]: Oh, nevermind, I just noticed the `origin` check above.

Should we just not pass `origin` to `getUnionTypeWorker` given we know it's undefined? That might help disambiguate things for later reading.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16412,6 +16419,22 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            if (!type) {
+                type = getUnionTypeWorker(types, unionReduction, aliasSymbol, aliasTypeArguments, origin);
+                unionOfUnionTypes.set(id, type);
+            }
+            return type;
+        }
+        return getUnionTypeWorker(types, unionReduction, aliasSymbol, aliasTypeArguments, origin);
+    }
+
+    function getUnionTypeWorker(types: readonly Type[], unionReduction: UnionReduction = UnionReduction.Literal, aliasSymbol?: Symbol, aliasTypeArguments?: readonly Type[], origin?: Type): Type {
```
Comment (jakebailey) [inline src/compiler/checker.ts:16437]: Should we make all of these parameters required? They always get their defaults from `getUnionTypeWorker`, so it seems like it may be less error prone to not double-write the defaults and also force callers to ensure all are passed.

(Then, maybe an explicit `/*origin*/ undefined` above?)

Comment (ahejlsberg) [reply src/compiler/checker.ts:16437]: Sure, I'll fix that.

**Review by jakebailey — APPROVED** [review]
Approved x2 😄
