### PR TITLE
Fix discriminant property narrowing through optional chain with null

### LINKED ISSUE #42480: Optional chaining does not narrow types in the `else` branch
# Bug Report

### 🔎 Search Terms

* `optional chaining`
* `optional chaining narrow`
* `optional chaining discriminated`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about:
  - optional chaining
  - type narrowing

Tested on all TS versions available in the playground that support optional chaining.
At the time of writing:
- 4.2.0-beta
- 4.1.3
- 4.0.5
- 3.9.7
- 3.8.3
- 3.7.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.3&ssl=6&ssc=1&pln=8&pc=1#code/C4TwDgpgBAglC8UDeVSQFxQOQywGigENMtCsoBfAKDWgCEFlVwIS78oAjEz86qgCYQAxgBtCAJ2jCA9gDsAzsCjDMcAD5QGmuQFdRoqgHojUIWMnT5SlWqibtUXXKEAzAJZyIA46fPipFWtlVVh7LSgTKAB3GQkAawUoDy9kuKg5eQBaPQNCTlFoZ3drKip3VygACmEAfgA6WgR4RBwsAEpkKigelQBuSNM5SQkZaO9UGSgAAxhpoiSIAA9IYWBvKgooCFEFaCRu3uEBqNn5pXcDKDApPbllT1QAC2haTaA)

### 💻 Code

```ts
type A = { type: 'A', a: 'a' }
type B = { type: 'B', b: 'b' }

declare const c: A | B | null
// declare const c: A | B | undefined
// declare const c: A | B // works fine for non-nullable unions

if (c?.type === 'A') {
    c; // narrowed to `A` as expected
} else {
    c; // `A` still present in the type
}
```

### 🙁 Actual behavior

In the second branch of the conditional statement the union type inferred for `c` still includes `A`. Same thing happens with ternary operator, functions with early returns, etc.

### 🙂 Expected behavior

In the second branch the type should be narrowed down by excluding `A`.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #42480

Got mixed up in #42450 thinking of `type` as the type of the discriminant property access, which would be `undefined` even if the union type included `null`. But `type` is the union, not the discriminant property, so we need to filter out both `null` and `undefined`, but then only mix back in `undefined` to the discriminant property type to model the behavior of an optional chain.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Need to accept baselines? https://github.com/microsoft/TypeScript/actions?query=workflow%3A%22Accept+Baselines+and+Fix+Lints%22

**Review by ahejlsberg — APPROVED** [review]
Funny, I was looking at this issue and came up with *exactly* the same fix. I had planned to add the following tests, I suggest you include them in this PR:

```ts
type U = { kind: undefined, u: 'u' }
type N = { kind: null, n: 'n' }
type X = { kind: 'X', x: 'x' }

function f1(x: X | U | undefined) {
    if (x?.kind === undefined) {
        x;
    }
    else {
        x;
    }
}

function f2(x: X | N | undefined) {
    if (x?.kind === undefined) {
        x;
    }
    else {
        x;
    }
}

function f3(x: X | U | null) {
    if (x?.kind === undefined) {
        x;
    }
    else {
        x;
    }
}

function f4(x: X | N | null) {
    if (x?.kind === undefined) {
        x;
    }
    else {
        x;
    }
}

function f5(x: X | U | undefined) {
    if (x?.kind === null) {
        x;
    }
    else {
        x;
    }
}

function f6(x: X | N | undefined) {
    if (x?.kind === null) {
        x;
    }
    else {
        x;
    }
}

function f7(x: X | U | null) {
    if (x?.kind === null) {
        x;
    }
    else {
        x;
    }
}

function f8(x: X | N | null) {
    if (x?.kind === null) {
        x;
    }
    else {
        x;
    }
}
```

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22624,13 +22624,13 @@ namespace ts {
...
-                const removeOptional = includesUndefined && isOptionalChain(access);
-                let propType = getTypeOfPropertyOfType(removeOptional ? getTypeWithFacts(type, TypeFacts.NEUndefined) : type, propName);
+                const includesNullable = strictNullChecks && maybeTypeOfKind(type, TypeFlags.Nullable);
+                const removeNullable = includesNullable && isOptionalChain(access);
+                let propType = getTypeOfPropertyOfType(removeNullable ? getTypeWithFacts(type, TypeFacts.NEUndefinedOrNull) : type, propName);
                 if (!propType) {
                     return type;
                 }
-                propType = removeOptional ? getOptionalType(propType) : propType;
+                propType = removeNullable ? getOptionalType(propType) : propType;
```
Comment (rbuckton) [inline src/compiler/checker.ts:22633]: Optional chaining leverages an `optionalType` marker type to indicate the type of an expression came from a `?.`. The `optionalType` marker is essentially `undefined`, but its presence has meaning to completions as well as within the checker itself. The code here (and from #42450), removes `undefined` (regardless of source), then mixes back in `undefinedType`. In functions like `checkPropertyAccessChain`, I use the function `propagateOptionalTypeMarker` to restore `optionalType` to the result if it was found in the source type to carry that marker forward.

I'm not certain yet whether this (or #42450) will cause problems as a result of not restoring the `optionalType` marker, as I need to consider if there is a test case that might trigger unwanted behavior.

**Comment by andrewbranch** [comment]
@rbuckton it sounds like any potential problem is already in master, so I’m going to go ahead and merge this. Let me know if you have a suggestion for a follow-up and I’ll be happy to add to it.
