### PR TITLE
Fix duplicate completions from two different copies of a node_modules package

### LINKED ISSUE #44172: Auto import provides multiple instances of the same package in monorepo
Issue Type: <b>Bug</b>

1. Have a monorepo that includes multiple versions of same @type package
2. Use auto import

Here is a [repository](https://github.com/aminpaks/typescript-monorepo-types-issue) to repo the issue.

Here is a animated gif to show the issue of having multiple imports for the same package by path:

ezgif com-gif-maker (1)

VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 0022c47a-4f46-441d-a819-669ad7e02cc7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.1.3
color-info|bie|0.6.0
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.6.3
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
go|gol|0.24.2
vscode-graphql|Gra|0.3.16
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|1.5.2
vscode-twined-components|low|0.0.4
change-string-case|max|1.1.2
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.12.1
python|ms-|2021.5.829140558
vscode-pylance|ms-|2021.5.1
jupyter|ms-|2021.6.832593372
js-debug-nightly|ms-|2021.5.1017
vsliveshare|ms-|1.0.4272
fix-json|oli|0.1.2
convert-css-in-js|pau|1.1.3
nginx-formatter|ray|0.0.13
vscode-commons|red|0.0.6
vscode-xml|red|0.16.0
bash-beautify|sha|0.1.1
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
bridgeflightcf:30299255

```

</details>

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #44172

### CODE REVIEW

File: src/services/exportInfoMap.ts [hunk 1]
```diff
@@ -77,6 +89,30 @@ namespace ts {
...
                     usableByFileName = importingFile;
                 }
+
+                let packageName;
+                if (moduleFile) {
+                    const nodeModulesIndex = moduleFile.fileName.indexOf(nodeModulesPathPart);
+                    if (nodeModulesIndex !== -1) {
+                        const isTypes = moduleFile.fileName.substring(nodeModulesIndex + nodeModulesPathPart.length).indexOf("@types/") === 0;
+                        const nextSlash = moduleFile.fileName.indexOf(directorySeparator, nodeModulesIndex + nodeModulesPathPart.length + (isTypes ? "@types/".length : 0) + 1);
+                        packageName = moduleFile.fileName.substring(nodeModulesIndex + nodeModulesPathPart.length + (isTypes ? "@types/".length : 0), nextSlash);
```
Comment (weswigham) [inline src/services/exportInfoMap.ts:99]: Namespaced `@types` package names would need further processing, no?

File: src/services/exportInfoMap.ts [hunk 2]
```diff
@@ -77,6 +89,30 @@ namespace ts {
                     cache.clear();
                     usableByFileName = importingFile;
                 }
+
+                let packageName;
+                if (moduleFile) {
+                    const nodeModulesIndex = moduleFile.fileName.indexOf(nodeModulesPathPart);
+                    if (nodeModulesIndex !== -1) {
+                        const isTypes = moduleFile.fileName.substring(nodeModulesIndex + nodeModulesPathPart.length).indexOf("@types/") === 0;
+                        const nextSlash = moduleFile.fileName.indexOf(directorySeparator, nodeModulesIndex + nodeModulesPathPart.length + (isTypes ? "@types/".length : 0) + 1);
```
Comment (weswigham) [inline src/services/exportInfoMap.ts:98]: Likewise, doesn't this need to handle package namespaces beyond @types?

File: src/services/exportInfoMap.ts (hunk 1 above)
Comment (andrewbranch) [reply src/services/exportInfoMap.ts:99]: No—the `packageName` doesn’t actually need to be unmangled because it’s only for comparing directory names to directory names. (I guess `packageName` is a slight misnomer in this way.) But you’re right that non-@types scopes need to be handled.

Comment (andrewbranch) [reply src/services/exportInfoMap.ts:99]: Weeeell, technically I guess you could end up with typings in `packages/a/node_modules/@types/foo__bar` shadowing typings in `node_modules/@foo/bar`. So yeah. Argh.

**Review by weswigham — APPROVED** [review]
