### PR TITLE
fix(50952): Can't infer from this type on static class method call in JS Doc

### LINKED ISSUE #50952: Can't infer from `this` type on static class method call in JS Doc
# Bug Report

### 🔎 Search Terms

- js inference
- javascript inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about differing type inference for JS and TS

### 💻 Code

**JavaScript:**

```js
/** @template R */
export class Action {
    /**
     * @returns {R}
     */
    action() {
        throw new Error("This method is abstract!")
    }

    /**
     * @template {new () => Action<any>} C
     * @this {C}
     * @return {C extends new () => Action<infer T> ? T : never}
     */
    static run() {
        return new this().action()
    }
}

/** @extends {Action<number>} */
export class Foo extends Action {
    action() {
        return 1
    }
}

const handle = Foo.run()
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?strictNullChecks=true&useUnknownInCatchVariables=false&ts=4.8.2&filetype=js#code/PQKhAIAEBcFMFsAOAbAhncAlcJgChYAPRAewCdpwBjNAZ1vAEEroBLEgO3AG89x-woEHwE4oZWNACuZDg26YAviIG4V4VC3YcAFAEoe60dAAWZEgHdwHWFYCiZc2R0AiAConWDeJJMkAJuBeGgBGtNBkmtAAhC566srqQkYQMAgo6LA8Nlb64AC8AHxMWpwAPKgcAJ6FiuAAwilQpsHc9cqiYpAS0rI89eBEcBz+DDngeUUlbOWsHABmsGTgbsUA-CvgAFzWsABuSx2iaqLh6KxU4GRSuga8nQI9MlzjLbT6AHRR2voJeIlCKBDWAjeTMGYcMocKTwEJLWo4fBEUgUah0BgAMRIJEGhGGo2m2kMom+nDy9weV0kz3AAEY-okqJxwuATJV-MgsvlwFiSB9rrcgA)
      

**TypeScript:**

```ts
export abstract class Action<R> {
    action(): R {
        throw new Error("This method is abstract!")
    }

    static run<C extends new () => Action<any>>(
        this: C,
    ): C extends new () => Action<infer T> ? T : never {
        return new this().action()
    }
}

export class Foo extends Action<number> {
    action() {
        return 1
    }
}

const handle = Foo.run()
```

<details><summary><b>Output</b></summary>

```ts
export class Action {
    action() {
        throw new Error("This method is abstract!");
    }
    static run() {
        return new this().action();
    }
}
export class Foo extends Action {
    action() {
        return 1;
    }
}
const handle = Foo.run();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?&filetype=ts#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAQWwEsIA7AHgCUA+OAbwCg53FyqAKASgC44tZmw5iYACygQA7nErA5AUSjSo3AEQAVCWSIBbYJIgATOHsSp0WGAEINvUewC+LJ3DQIYZTHCgBXGgBhOFAYYEoTIgU5PjgAXkZSbypqBEoAT3p6bndxXRRBIIAadwE4ELCIqPlFODjEki4aMkoAM2AoOC1GAH5uuEEFADdOkTExKCN-KEpauUk9PgA6GwpKPndXVxZQSFg4PAIiADEICFCQcMiiZPXqSn99JE7GVjE1nl5xifYpmBmcwAjFsWDtMFQ0HAJOkTLhgAk4GcIMsAhteEA)

### 🙁 Actual behavior

The inferred type for `handle` to in the JS version is `any`, and the `--noImplicitAny` option is not respected.

### 🙂 Expected behavior

The inferred type for `handle` to be `number` for both, as the types are fully equivalent.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #50952

--- 
Not sure if `TransientSymbol` can be used for `this` (jsdoc) in the `Signature` context. Or better get the type directly from `signature.declaration` in `getThisTypeOfSignature` and try to `instantiateType` there

```ts
function getThisTypeOfSignature(signature: Signature): Type | undefined {
    if (signature.thisParameter) {
        return getTypeOfSymbol(signature.thisParameter);
    }
   // getSignatureApplicabilityError
   //   > const thisType = getThisTypeOfSignature(signature); // requires instantiated type 
   // 
    if (isInJSFile(signature.declaration)) {
        const thisTag = getJSDocThisTag(signature.declaration);
        if (thisTag && thisTag.typeExpression) {
            // like so - instantiateType(getTypeFromTypeNode(thisTag.typeExpression), signature.mapper) ?
            return getTypeFromTypeNode(thisTag.typeExpression);
        }
    }
}
```

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13335,6 +13335,13 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 }
             }
 
+            if (isInJSFile(declaration)) {
+                const thisTag = getJSDocThisTag(declaration);
+                if (thisTag && thisTag.typeExpression) {
+                    thisParameter = createSymbolWithType(createSymbol(SymbolFlags.FunctionScopedVariable, InternalSymbolName.This), getTypeFromTypeNode(thisTag.typeExpression));
```
Comment (sandersn) [inline src/compiler/checker.ts:13341]: Would it be possible to add `bindJSDocThisTag` in the binder instead of creating a symbol here in the checker? 
I'm not sure what you'd use as the declaration -- I guess the tag name, or maaaybe the tag itself.

I'm not 100% sure it would work, but if it doesn't, this in an OK fallback.

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks pretty good, but can you try handling `@this` tags in the binder to see if it works?

File: src/compiler/checker.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:13341]: I was thinking about creating a symbol in a `binder`, and I struggled with several questions.

1. What do we need to use as a `parent`? Do we need it?
2. What do we need to use as a `declaration`?
    > I guess the tag name, or maaaybe the tag itself.

    I think we can only use `tagName`, the tag itself is not a _Declaration_. Or create a special kind of `Declaration` that will contain a `typeExpression` and `tagName`.
3. How to determine the type of this `symbol`?
    The `Declaration` of `tagName` doesn't refer to `typeExpression`. Therefore in the `checker`, we need to change `getTypeOfSymbol` to resolve the type from `typeExpression`. Something like so,
   
```ts
// binder
function bindJSDocThisTag() {
 // todo
}

// getSignatureFromDeclaration
if (isInJSFile(declaration)) {
    const thisTag = getJSDocThisTag(declaration);
    if (thisTag && thisTag.tagName.symbol) {
        thisParameter = thisTag.tagName.symbol;
    }
}

// getTypeOfVariableOrParameterOrPropertyWorker
const typeExpression = /*find typeExpression*/
if (symbol.escapedName === InternalSymbolName.This && typeExpression) {
     return getTypeFromTypeNode(typeExpression) 
}
```

Comment (a-tarasyuk) [reply src/compiler/checker.ts:13341]: @sandersn Could you look at my previous comment?

Comment (a-tarasyuk) [reply src/compiler/checker.ts:13341]: @sandersn Could you look at my previous comment?

Comment (sandersn) [reply src/compiler/checker.ts:13341]: From poking around the binder, I convinced myself that the symbol must be created in the checker.
It can't be created in the binder, because a parameter's symbol needs to have a parameter as a declaration, and there is no `this` parameter in a JS file.

The closest tag that does create a declaration is `@template {Constraint} T`, but `T` is not a type, it's a TypeParameterDeclaration, which is usable as a declaration. `@this` has only a type, as you point out.

Sorry for the delay on this one.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
Tests pass locally after merge from main.
