### PR TITLE
Don’t try to create auto import provider when host program doesn’t exist

### LINKED ISSUE #44849: TS Server fatal error:  Cannot read property 'getSourceFile' of undefined
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.3.2

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'getSourceFile' of undefined
    at Function.AutoImportProviderProject.getRootFileNames (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158954:38)
    at Function.AutoImportProviderProject.create (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158979:38)
    at ConfiguredProject.Project.getPackageJsonAutoImportProvider (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158787:77)
    at ConfiguredProject.Project.updateGraph (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:158217:26)
    at ConfiguredProject.updateGraph (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:159140:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:160855:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:161893:44)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162233:97
    at Object.flatMap (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:162233:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:163288:46)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165205:88
    at IOSession.Session.executeWithRequestId (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165196:28)
    at IOSession.Session.executeCommand (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165205:33)
    at IOSession.Session.onMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:165231:35)
    at Interface.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167833:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.29GB free)|
|Process Argv|--crash-reporter-id 261da1bc-e942-4094-8f7e-e281f9ea519b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.0.1
vscode-docker|ms-|1.14.0
remote-wsl|ms-|0.56.5
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.34.1
material-icon-theme|PKi|4.7.0
LiveServer|rit|5.6.1
vue-language-features|znc|0.7.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlang:30322306
binariesv615:30325510
aatestflightcf:30331712

```

</details>

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #44849

Looking at the error stack and the code path leading to the crash, I’m not sure how to produce this, but one user claimed that they had some reason to believe it was triggered by an unofficial Vue extension, and indeed both VS Code reports list that extension, but I couldn’t trigger it myself. At any rate, the auto import provider can be loaded lazily, and if someone somehow requests it before having a program, there’s no reason to crash; we can just return undefined.

### CODE REVIEW

File: src/server/project.ts [hunk 1]
```diff
@@ -1070,7 +1070,7 @@ namespace ts.server {
                 this.lastCachedUnresolvedImportsList = undefined;
             }
 
-            const isFirstLoad = this.projectProgramVersion === 0;
+            const isFirstLoad = this.projectProgramVersion === 0 && hasNewProgram;
```
Comment (amcasey) [inline src/server/project.ts:1073]: This appears to do the right thing, but it seems like the name and the meaning no longer agree (presumably, it's the first load whether or not there's a program).

**Review by amcasey — APPROVED** [review]

File: src/server/project.ts (hunk 1 above)
Comment (andrewbranch) [reply src/server/project.ts:1073]: Fair enough; I’ll make the name more specific.
