### PR TITLE
replace whole path if directory separator appears for import completion.

### LINKED ISSUE #41088: Autocomplete 'duplicates' path when typing part of the path and then autocomplete
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.3

**Search Terms**
- Suggestion / suggest / intellisense
- paths

---

- VSCode Version: 1.49
- OS Version: W10 - up to date

Steps to Reproduce:

1. Create a new typescript project (I have used a nrwl nx workspace)
2. Add a new path to the paths object in the tsconfig to map a path to a folder (I created a new nx library) and make sure the path alias is nested (see my video)
3. Try to import from the path, start with typing 2/3 of the path and then press tab to autocomplete
https://sharexx.blob.core.windows.net/sharex/sharex/2020_10_06_11_24_00_7b322a7d-7e30-4a01-afc6-3050399160db.mp4

Does this issue occur when all extensions are disabled?: **Yes**

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #41088 and #40572

### CODE REVIEW

File: src/services/stringCompletions.ts [hunk 1]
```diff
@@ -277,13 +277,14 @@ namespace ts.Completions.StringCompletions {
         return nameAndKind(name, ScriptElementKind.directory, /*extension*/ undefined);
     }
 
-    function addReplacementSpans(text: string, textStart: number, names: readonly NameAndKind[]): readonly PathCompletion[] {
+    function addReplacementSpans(text: string, textStart: number, names: readonly NameAndKind[], tsConfigPaths?: string[]): readonly PathCompletion[] {
         const span = getDirectoryFragmentTextSpan(text, textStart);
-        return names.map(({ name, kind, extension }): PathCompletion => ({ name, kind, extension, span }));
+        const pathSpan = getWholeFragmentTextSpan(text, textStart);
+        return names.map(({ name, kind, extension }): PathCompletion => tsConfigPaths?.some(path => path === name) ? { name, kind, extension, span: pathSpan } : { name, kind, extension, span });
```
Comment (andrewbranch) [inline src/services/stringCompletions.ts:283]:
```suggestion
        return names.map(({ name, kind, extension }): PathCompletion => contains(tsConfigPaths, name) ? { name, kind, extension, span: pathSpan } : { name, kind, extension, span });
```

Comment (andrewbranch) [reply src/services/stringCompletions.ts:283]: Would it also work just to say “if `name` contains a path separator, assume it’s a completion for the whole path, so replace everything”? That way if we introduce path completions for other full paths in the future, we don’t hit the same bug?

**Review by andrewbranch — APPROVED** [review]

File: src/services/stringCompletions.ts (hunk 1 above)
Comment (ShuiRuTian) [reply src/services/stringCompletions.ts]: !
Good point!
