### PR TITLE
Fix getChildCount/At methods in EndOfFileTokens

### LINKED ISSUE #44990: `getChildCount` returns 0 on `EndOfFileToken` with JSDoc
# Bug Report

### 🔎 Search Terms

- `getChildCount`
- `EndOfFileToken`

### 🕗 Version & Regression Information

Seems like the bug was introduced in #9529. A partial fix was implemented in #25015, but that only updated `getChildren`, not `getChildCount` or `getChildAt`.

### ⏯ Playground Link

N/A

### 💻 Code

https://github.com/microsoft/TypeScript/blob/main/src/services/services.ts#L261-L271

```ts
/** jsdoc comment at end of file */
```

### 🙁 Actual behavior

`getChildCount` is hardcoded to return 0

### 🙂 Expected behavior

`getChildCount` returns the same value as `getChildren().length`

### PR DESCRIPTION
**Pull request by tjjfvi**
Before, they were hardcoded to return `0` and `undefined!`, respectively, but that is inaccurate for `EndOfFileToken`s with attached jsdoc.

Fixes #44990

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -259,11 +259,11 @@ namespace ts {
         }
 
         public getChildCount(): number {
-            return 0;
+            return this.getChildren().length;
         }
 
-        public getChildAt(): Node {
-            return undefined!;  // TODO: GH#18217
+        public getChildAt(index: number): Node {
```
Comment (AviVahl) [inline src/services/services.ts:265]: Should return `Node | undefined`?
TypeScript's codebase chould use the stricter tsconfig flags...

Comment (tjjfvi) [reply src/services/services.ts:265]: Theoretically, yes, but that's somewhat tangential to this PR

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Is there a way to get a quick test added?

**Comment by tjjfvi** [comment]
I added a test to `src/testRunner/unittests/publicApi.ts`, as that seemed to be the most applicable place. All of the tests are passing, but afaict the "77248 passing" number did not go up, so I'm not sure if there's something else I need to do to add the test.

**Comment by DanielRosenwasser** [comment]
> but afaict the "77248 passing" number did not go up

You can try making the test fail locally as a sanity check which I'd appreciate - maybe each unittest only gets counted as its own test?

**Comment by tjjfvi** [comment]
Good point -- the test failed successfully.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
> You can try making the test fail locally as a sanity check which I'd appreciate - maybe each unittest only gets counted as its own test?

I'm pretty sure unit tests are not part of the 77248 total. They may also run on each process for a parallel test run.
