### PR TITLE
Fix/create element new jsx transform

### LINKED ISSUE #41146: [jsx-runtime] `createElement` fallback shoud from @jsxImportSource
if using `React.createElement`, it is a different results from babel, and will broken react-like lib.

__why  `createElement` fallback__: https://github.com/facebook/react/issues/20031#issuecomment-710346866

**TypeScript Version:**  4.1.0-dev.20201015

**Search Terms:**

**Code**

```ts
/** @jsxImportSource preact */

const keyBeforeSpread = <span key="a" {...props} />
const keyAfterSpread =<span {...props} key="das" />
```

**Expected behavior:**

```js
/** @jsxImportSource preact */
import { jsx } from "preact/jsx-runtime"
import { createElement } from "preact"

const keyBeforeSpread = jsx("span", Object.assign({}, props), "a");
const keyAfterSpread = createElement("span", Object.assign({}, props, { key: "das" }));
```

**Actual behavior:**

```js
/** @jsxImportSource preact */
const keyBeforeSpread = _jsx("span", Object.assign({}, props), "a");
const keyAfterSpread = React.createElement("span", Object.assign({}, props, { key: "das" }));
```

**Playground Link:** 
https://www.typescriptlang.org/play?ts=4.1.0-dev.20201015#code/PQKhAIAECsGcA8CSBbADgewE4BcDK6BXTAYwFNxVNSBDY7cEYAKCePQDtZ6BrUgTwBCpAGZZSuSjQAm4ALzgAPLFTV24Xn1kAialvABvAHTHK6VLAC+4YAD5WHLuv4BBYdlKYJVajNlKVakYmmGaWTppaUtSwerZAA

**Related Issues:**

### PR DESCRIPTION
**Pull request by Andarist**
Please verify that:
* [x] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `gulp runtests` locally
* [x] There are new or updated unit tests validating the change

Fixes #41146

cc @gaearon @lunaruan @weswigham 

I've first added a commit with tests covering the cases around `key` props and the new JSX transform as those were not covered by any tests I could find (no tests for this were introduced in #39199) and then I've implemented a fix that auto-inserts import for `createElement` from the `jsxImportSource` itself so it should be nicely visible what actual change this PR brings.

### CODE REVIEW

File: src/compiler/factory/utilities.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ namespace ts {
             );
     }
 
-    export function createExpressionForJsxElement(factory: NodeFactory, jsxFactoryEntity: EntityName | undefined, reactNamespace: string, tagName: Expression, props: Expression | undefined, children: readonly Expression[] | undefined, parentElement: JsxOpeningLikeElement, location: TextRange): LeftHandSideExpression {
+    export function createExpressionForJsxElement(factory: NodeFactory, callee: Expression, tagName: Expression, props: Expression | undefined, children: readonly Expression[] | undefined, location: TextRange): LeftHandSideExpression {
```
Comment (Andarist) [inline src/compiler/factory/utilities.ts:67]: the signature differs now from the accompanying `createExpressionForJsxFragment` but this is just a util file so I don't think it's particularly important but let me know if you'd like this to be refactored somehow.

File: src/compiler/transformers/jsx.ts [hunk 2]
```diff
@@ -40,17 +40,25 @@ namespace ts {
         }
 
         function getImplicitImportForName(name: string) {
-            const existing = currentFileState.utilizedImplicitRuntimeImports?.get(name);
+            const importSource = name === "createElement"
```
Comment (Andarist) [inline src/compiler/transformers/jsx.ts:43]: this is a special case for the `createElement` within this "generic" util, but in the name of KISS I think it's perfectly OK here. The transform is tied to the semantics defined by React anyhow, this won't change often and there is near-zero chance that `createElement` will get reintroduced in the future in some other entrypoint in JSX runtimes

**Review by weswigham — APPROVED** [review]
I pushed a merge for the conflicts introduced this morning, and plan to merge once CI is green, thanks!
