### PR TITLE
use sys based host for formatting diagnostics

### LINKED ISSUE #9749: "tsc --init" fails to complete successfuly
This does not occur in `2.1.0-dev.20160713`. Possibly related to #9713 or #9704.

**TypeScript Version:**  nightly (2.1.0-dev.20160714)

**Code**

```
tsc --init
```

**Expected behavior:**
`message TS6071: Successfully created a tsconfig.json file.`

**Actual behavior:** 
```
/home/seikho/node_modules/typescript/lib/tsc.js:36554
            output += category + " TS" + diagnostic.code + ": " + flattenDiagnosticMessageText(diagnostic.messageText, host.getNewLine()) + host.getNewLine();
                                                                                                                           ^

TypeError: Cannot read property 'getNewLine' of undefined
    at Object.formatDiagnostics (/home/seikho/node_modules/typescript/lib/tsc.js:36554:124)
    at reportDiagnosticSimply (/home/seikho/node_modules/typescript/lib/tsc.js:38582:25)
    at writeConfigFile (/home/carl/npm/global/lib/node_modules/typescript/lib/tsc.js:39090:13)
    at Object.executeCommandLine (/home/seikho/node_modules/typescript/lib/tsc.js:38711:13)
    at Object.<anonymous> (/home/carl/npm/global/lib/node_modules/typescript/lib/tsc.js:39131:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```

### PR DESCRIPTION
**Pull request by vladima**
fixes #9749

### CODE REVIEW

**Comment by wycats** [comment]
Heh. I just hit this!

File: src/compiler/tsc.ts [hunk 1]
```diff
@@ -6,9 +6,19 @@ namespace ts {
...
     }
 
-    let reportDiagnostic = reportDiagnosticSimply;
+    const defaultFormatDiagnosticsHost: FormatDiagnosticsHost = {
+        getCurrentDirectory: () => sys.getCurrentDirectory(),
+        getNewLine: () => sys.newLine,
+        getCanonicalFileName: createGetCanonicalFileName(sys.useCaseSensitiveFileNames)
+    };
+
+    let reportDiagnosticWorker = reportDiagnosticSimply;
```
Comment (yuit) [inline src/compiler/tsc.ts]: Question: why you are doing this instead of just call `reportDiagnosticSimply` directly

File: src/compiler/tsc.ts [hunk 2]
```diff
@@ -288,26 +298,26 @@ namespace ts {
 
         if (commandLine.options.project) {
             if (!isJSONSupported()) {
-                reportDiagnostic(createCompilerDiagnostic(Diagnostics.The_current_host_does_not_support_the_0_option, "--project"), /* compilerHost */ undefined);
+                reportDiagnostic(createCompilerDiagnostic(Diagnostics.The_current_host_does_not_support_the_0_option, "--project"), /* host */ undefined);
```
Comment (yuit) [inline src/compiler/tsc.ts]: nit: I think use /*formatDiagnosticsHost*/ will be more clear

**Comment by yuit** [comment]
lgtm with small comment & question.

File: src/compiler/tsc.ts (hunk 1 above)
Comment (vladima) [inline src/compiler/tsc.ts]: because `reportDiagnosticWorker` can be either `reportDiagnosticSimply` or `reportDiagnosticWithColorAndContext` if `pretty` option is set

File: src/compiler/program.ts [hunk 3]
```diff
@@ -991,7 +991,13 @@ namespace ts {
         return sortAndDeduplicateDiagnostics(diagnostics);
     }
 
-    export function formatDiagnostics(diagnostics: Diagnostic[], host: CompilerHost): string {
+    export interface FormatDiagnosticsHost {
```
Comment (mihailik) [inline src/compiler/program.ts]: Can you please clarify this interface? Thanks a lot!

It's a contract between what and what?
Who is meant to provide the implementation?
Do existing host scenarios need to do anything?
Maybe a use case please?

Sorry for being inquisitive, but there are a few other `*Host` interfaces at various levels of abstraction, it becomes harder to follow. Please give us a picture why `FormatDiagnosticsHost` is there, beyond self-evident 'to deal with diagnostic formatting'. I am sure others will benefit from the same, especially where TS is an embedded library.

Many thanks!

Comment (weswigham) [inline src/compiler/program.ts]: It's a subset of CompilerHost/sys functionality - specifically the minimal subset needed to properly format diagnostics. Like how use use ModuleResolutionHost to indicate where we need the minimal functionality for resolving modules. Grouping the methods needed into a "host" like this is simply cleaner than passing in a collection of arguments or closures directly.

Comment (mihailik) [inline src/compiler/program.ts]: Thanks @weswigham!

Although that sort of rephrases "Format Diagnostics Host" rather than answers any of the questions above ;-)
