### PR TITLE
fix(39346): Intelligent code completion not working in child class with composited base interface

### LINKED ISSUE #39346: Intelligent code completion not working in child class with composited base interface
**TypeScript Version:**  3.9.5

**Search Terms:**

- `auto completion`
- `code intelligence`

**Code**

_Base.ts_
```ts
interface ILifeCycle {
  onA(): void;
  onB(): void;
}

// 🚨 all of these breaks the intelligent code completion
// type ComposedType = Partial<ILifeCycle>;
// type ComposedType = Pick<ILifeCycle, "onA" | "onB">;

// ✅ this is okay
type ComposedType = ILifeCycle;

export interface Base extends ComposedType {
  onC(): void;
}

export class Base {}
```

_MyClass.ts_
```ts
import { Base } from "./Base";

class MyClass extends Base {
  on| // here we expect the auto completion shows
}

```

**Expected behavior:**

- the auto completion for parent methods `on*` shows

**Actual behavior:**

- the auto completion for parent methods `on*` does not showing

**Playground Link:** [👉 check it out](https://www.staging-typescript.org/play?#code/PTAECEEMGcFMDoAu0BQKQRg5aCWA7RWAJwDNIBjWUASQBldTYBhATwoBtqBvFUUAPb4AggAoAlAC5QANwG4AJgG4+g-OAnS5ilQF80GQLwbgCr3QkDh0GlQiABaw4oAEbFYkANbQb90ASIXcAHNYQlAKAQVqcIBbAAcuRFwhdDBEVljqZgE4gTgFABV06gBeUAAFSGJE8wAeekYWdi4APhUMNIzQLJy8ws7SstwKdzqGJjZOWAAaUAAiIWFZ0AAfOaFwWdaDMEBQcm9cLwPBd0hWFA7M7Njc2AKi0FL68abYFRRYAA9rqt9CEnIqJhHJ8iPgFF5utdevdePwhMxNLJ5MoUPp3l8BD9ODAvFBHNw0RgALKsZgcHFIVAobHQLwksk40AgkLgoE8VTJfRAA)

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39346

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -2432,7 +2432,7 @@ namespace ts.Completions {
                 !existingMemberNames.has(propertySymbol.escapedName) &&
                 !!propertySymbol.declarations &&
                 !(getDeclarationModifierFlagsFromSymbol(propertySymbol) & ModifierFlags.Private) &&
-                !isPrivateIdentifierPropertyDeclaration(propertySymbol.valueDeclaration));
+                !(propertySymbol.valueDeclaration && isPrivateIdentifierPropertyDeclaration(propertySymbol.valueDeclaration)));
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:2435]: Oof

Comment (a-tarasyuk) [reply src/services/completions.ts:2435]: @DanielRosenwasser I think, this condition need to move to a method :).
