### PR TITLE
Fix auto import crash due to difference in `paths` handling

### LINKED ISSUE #50392: Debug failure at `getCompletionEntryCodeActionsAndSourceDisplay`
# Bug Report

### 🔎 Search Terms

Debug Error False Expression applyCompletionCommand undefined failed

### 🕗 Version & Regression Information

This has been happening for me as long as I can remember - actb told me on github that I should maybe report it :sweat_smile: 

### 💻 Code

I cannot pinpoint this behaviour to any specific code base.

### 🙁 Actual behavior

Popup with autoimport appears, I select an entry, no import is added to the file. The following error in the extension host logs:

```
[2022-08-21 17:52:06.457] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2022-08-21 17:52:06.457] [exthost] [error] Error: <semantic> TypeScript Server Error (4.7.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getCompletionEntryCodeActionsAndSourceDisplay (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:132616:22)
    at Object.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:132554:30)
    at Object.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164645:35)
    at /nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176487:57
    at Object.mapDefined (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:605:30)
    at IpcIOSession.Session.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176485:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:175124:61)
    at /nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177198:35)
    at process.<anonymous> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
    at Function.create (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:718369)
    at p.dispatchResponse (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:712217)
    at p.dispatchMessage (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:711085)
    at ChildProcess.<anonymous> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:710570)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[2022-08-21 17:52:07.017] [exthost] [error] Error: <semantic> TypeScript Server Error (4.7.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getCompletionEntryCodeActionsAndSourceDisplay (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:132616:22)
    at Object.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:132554:30)
    at Object.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164645:35)
    at /nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176487:57
    at Object.mapDefined (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:605:30)
    at IpcIOSession.Session.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176485:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:175124:61)
    at /nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177198:35)
    at process.<anonymous> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
    at Function.create (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:718369)
    at p.dispatchResponse (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:712217)
    at p.dispatchMessage (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:711085)
    at ChildProcess.<anonymous> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:710570)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) _typescript.applyCompletionCommand {"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"}
[2022-08-21 17:52:07.017] [exthost] [error] Error: <semantic> TypeScript Server Error (4.7.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getCompletionEntryCodeActionsAndSourceDisplay (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:132616:22)
    at Object.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:132554:30)
    at Object.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:164645:35)
    at /nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176487:57
    at Object.mapDefined (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:605:30)
    at IpcIOSession.Session.getCompletionEntryDetails (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:176485:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:175124:61)
    at /nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:88
    at IpcIOSession.Session.executeWithRequestId (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177163:28)
    at IpcIOSession.Session.executeCommand (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177172:33)
    at IpcIOSession.Session.onMessage (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:177198:35)
    at process.<anonymous> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/node_modules/typescript/lib/tsserver.js:179833:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
    at Function.create (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:718369)
    at p.dispatchResponse (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:712217)
    at p.dispatchMessage (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:711085)
    at ChildProcess.<anonymous> (/nix/store/xxxl81wm2mgas7mlj671x0dwj0qjbyia-vscode-1.69.1/lib/vscode/resources/app/extensions/typescript-language-features/dist/extension.js:2:710570)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) _typescript.applyCompletionCommand undefined
```

### 🙂 Expected behavior

The selected entry should be imported.

(Sorry for my brevity - I'm on vacation, got a flight to catch tomorrow and it's already late at night - those timestamps show my home timezone, not my current timezone. Still wanted to file this Issue before I forget about it.)

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #50392

Auto-imports in completions does some work when you start typing for each item in the list (doing as little as possible for performance), and then does the rest of the work to compute the code change for an individual completion in a separate request when that item is highlighted. Synchronizing this two work streams to come up with the same answer has long been a source of bugs and crashes; #50392 is of this kind. This PR migrates the latter code path away from some very old code with some bad assumptions in favor of reusing the same `ExportInfoMap` cache structure that the former code path uses.

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -404,38 +418,6 @@ namespace ts.codefix {
...
-        const getModuleSpecifierResolutionHost = memoizeOne((isFromPackageJson: boolean) => {
-            return createModuleSpecifierResolutionHost(isFromPackageJson ? host.getPackageJsonAutoImportProvider!()! : program, host);
-        });
-
-        forEachExternalModuleToImportFrom(program, host, preferences, useAutoImportProvider, (moduleSymbol, moduleFile, program, isFromPackageJson) => {
-            const checker = program.getTypeChecker();
-            // Don't import from a re-export when looking "up" like to `./index` or `../index`.
-            if (moduleFile && moduleSymbol !== exportingModuleSymbol && startsWith(importingFile.fileName, getDirectoryPath(moduleFile.fileName))) {
-                return;
-            }
```
Comment (andrewbranch) [inline src/services/codefixes/importFixes.ts:419]: This was the problematic code in particular; the rationale in the comment doesn’t hold if this file is the target of a tsconfig `paths` alias, which we don’t know until later in the process. But there is not much need to fix it here when this code is completely duplicated by the `ExportMapCache`.

**Review by jakebailey — APPROVED** [review]
