### PR TITLE
Gabritto/semicolons

### LINKED ISSUE #46833: Class member snippet completions always have semicolon
# Bug Report

### 🔎 Search Terms

semicolon, class member snippets

### 🕗 Version & Regression Information

As of 4.5 when class member snippets for completions was enabled

### 💻 Code

Before completions:
```ts
interface Base {
    a: number
    b(a: string): string
    c(a: string): string
    c(a: number): number
}
class Sub implements Base {
    // Get completions here
}
```

After inserting every class member completion:
```ts
interface Base {
    a: number
    b(a: string): string
    c(a: string): string
    c(a: number): number
}
class Sub implements Base {
    a: number; // << semicolon
    b(a: string): string {
        
    }
    c(a: string): string; // << semicolon
    c(a: number): number; // << semicolon
    c(a: any): string | number {
        
    }
}
```

### 🙁 Actual behavior

When class member completions are offered for property declarations or method *signatures* (i.e. methods without bodies), they always have a trailing semicolon.

### 🙂 Expected behavior

No semicolons in the completion text if we determine there shouldn't be any, by means of either:
- preferences says we should remove semicolons (e.g. `SemicolonPreference` in `FormatCodeSettings` is set to `Remove`), or
- `probablyUsesSemicolons()` returns false

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #46833.

We now have precedent for calling the formatter in completions. ✨

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -4156,9 +4161,13 @@ namespace ts {
         }
 
         function emitModifiers(node: Node, modifiers: NodeArray<Modifier> | undefined) {
-            if (modifiers && modifiers.length) {
-                emitList(node, modifiers, ListFormat.Modifiers);
-                writeSpace();
+            if (modifiers) {
+                onBeforeEmitNodeArray?.(modifiers);
```
Comment (gabritto) [inline src/compiler/emitter.ts:4165]: I was getting an error previously because `onBeforeEmitNodeArray` (/`onAfter...`) was not called for an empty modifiers array. The problem is that the text changes printer uses those two handlers to set positions in synthetic nodes, when we are emitting, so empty modifier arrays were not having their positions set. In `emitNodeList`, we call those handlers even if the node array is empty, so it seemed to make sense to have the same behavior here, for consistency, instead of coming up with some alternative fix.

File: src/services/completions.ts [hunk 2]
```diff
@@ -852,15 +858,16 @@ namespace ts.Completions {
...
         let body;
         if (preferences.includeCompletionsWithSnippetText) {
             isSnippet = true;
             // We are adding a tabstop (i.e. `$0`) in the body of the suggested member,
             // if it has one, so that the cursor ends up in the body once the completion is inserted.
             // Note: this assumes we won't have more than one body in the completion nodes, which should be the case.
-            const emptyStatement = factory.createExpressionStatement(factory.createIdentifier(""));
-            setSnippetElement(emptyStatement, { kind: SnippetKind.TabStop, order: 0 });
-            body = factory.createBlock([emptyStatement], /* multiline */ true);
+            const emptyStmt = factory.createEmptyStatement();
```
Comment (gabritto) [inline src/services/completions.ts:868]: conceptually, it only makes sense for a tab stop snippet to be attached to a node that doesn't cause anything to be emitted. using an empty identifier, as I was before, was causing some troubles when setting positions for synthetic nodes, because we can't assume the identifier will be empty. an empty statement seemed more appropriate then.

File: src/services/textChanges.ts [hunk 3]
```diff
@@ -1052,15 +1052,6 @@ namespace ts.textChanges {
                     ? "" : options.suffix);
         }
 
-        function getFormatCodeSettingsForWriting({ options }: formatting.FormatContext, sourceFile: SourceFile): FormatCodeSettings {
```
Comment (gabritto) [inline src/services/textChanges.ts:1055]: moved to utilities

File: src/services/utilities.ts [hunk 4]
```diff
@@ -3306,5 +3306,17 @@ namespace ts {
             : getLocaleSpecificMessage(diag);
     }
 
+    /**
+     * Get format code settings for a code writing context (e.g. when formatting text changes or completions code).
+     */
+    export function getFormatCodeSettingsForWriting({ options }: formatting.FormatContext, sourceFile: SourceFile): FormatCodeSettings {
```
Comment (gabritto) [inline src/services/utilities.ts:3312]: moved here from textchanges

File: src/services/completions.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/completions.ts:868]: I can’t tell if you already got this, but an empty statement is _only_ parsable when terminated by a semicolon, so in the reverse, it’s impossible to emit an empty statement without emitting a semicolon. Is the formatter removing this semicolon or did you somehow get this to emit without one?

File: src/compiler/emitter.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/emitter.ts:4165]: Possibly dumb question, but when/why do we have empty modifier arrays?

Comment (gabritto) [reply src/compiler/emitter.ts:4165]: It's a bit of a messy situation: in this completion scenario, I was getting empty modifier array because I call `updateModifiers`, which in turns calls `createModifiersFromModifierFlags`, which always returns an array, even if empty.

File: src/services/completions.ts (hunk 2 above)
Comment (gabritto) [reply src/services/completions.ts:868]: I hadn't thought of that, I think. The semicolon doesn't exist in this case because the empty statement is never emitted -- when we call `emitTabStop`, it doesn't emit the node (empty statement) the tab stop is attached to. Do you think that could be a problem?

Comment (andrewbranch) [reply src/services/completions.ts:868]: Got it. I don’t think it’s a problem, it’s just a little weird to think about.

Comment (gabritto) [reply src/services/completions.ts:868]: it's definitely weird. I tried to go for the least weird option :/

File: src/compiler/emitter.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/emitter.ts:4165]: @rbuckton should `updateModifiers` pass through `undefined` instead of an empty array to represent no modifiers?

Comment (rbuckton) [reply src/compiler/emitter.ts:4165]: I think we generally expect modifiers to be either `undefined` or non-empty, though we mostly check for `node.modifiers?.length` (or `node.modifiers && node.modifiers.length`). There's no reason to have an empty array here, so it was probably an oversight when I added `createModifiersFromModifierFlags`. We should probably always put an `undefined` for empty modifiers, but always defensively check for `node.modifiers?.length` (or use `some(node.modifiers)`, which essentially does the same thing)

Comment (gabritto) [reply src/compiler/emitter.ts]: updated this to revert the emitter change to `emitModifiers` and to change `createModifiersFromModifierFlags` to return `undefined` instead of an empty array. this changed the API, since now `createModifiersFromModifierFlags` returns `Modifiers[] | undefined`.

**Review by andrewbranch — APPROVED** [review]
