### PR TITLE
Fix contextually typed object literal completions where the object being edited affects its own inference

### LINKED ISSUE #35702: Properties in object literal key completion list aren't filtered when a prior argument supplies a mapped type key
- VSCode Version: 1.41.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

\>\> [Playground Link](https://www.typescriptlang.org/play/index.html?ssl=23&ssc=1&pln=19&pc=1#code/JYOwLgpgTgZghgYwgAgMIFcDOYD2BbAUQBsI8JxNkBvAWAChlHkByBfABxxHLAFouIzAFzV6Tcchg4cAfhHYooAOYBuMUwC+AGnWNWHAeF5gA7jmGiGExgCM4UOcgXK1Vxhvoe69UJFiIUAHl2MGAuTAAeABVkCAAPSBAAE0oAawgATxwYNCxcQhIyCgA+S3F2KBx2TBEMbHxiUh5MAG0ogF1XL3oYdBAEUK5kBCgIOEho2ITyFOR0rJy6-MaisExigAoQODIRKK1kKsGQGuRg48io4oBKMqZRsHQoEGpkbbIDo7CT5A0u+noIzGkA2+jwnG4RgEzAOVGQFSqpzhv1+11cgPCYEOIVO52+kTBEJ4-G4zFKAF47owEdURMivF4gA)

```ts
interface CustomElements {
    'component-one': {
        foo?: string;
    },
    'component-two': {
        bar?: string;
    }
}

interface Options<T extends keyof CustomElements> {
    props: CustomElements[T];
}

function create<T extends keyof CustomElements>(name: T, options: Options<T>) {
    return { name, options };
}

create('component-one', { props: { /* trigger intellisense here */ } });

const opts: Options<'component-one'> = {
    props: { /* and here */ }
}
```

The type of `props` in the `create` call is correctly narrowed down to `CustomElements['component-one']` by the type system, however Intellisense suggests the props of all fields of `CustomElements`:

This does not happen when creating an object of that type:

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by andrewbranch**
This is Wes’s alternative to my PR #36364, which fixes #35702.

### CODE REVIEW

File: tests/cases/fourslash/completionsGenericIndexedAccess6.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
+// @Filename: component.tsx
```
Comment (weswigham) [inline tests/cases/fourslash/completionsGenericIndexedAccess6.ts]: Shouldn't this file have a `/// <reference path="fourslash.ts" />` at the top for completion support while editing?

File: tests/cases/fourslash/completionsGenericIndexedAccess5.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
+////interface CustomElements {
```
Comment (weswigham) [inline tests/cases/fourslash/completionsGenericIndexedAccess5.ts]: Same here, isn't this test missing a `/// <reference path="fourslash.ts" />`?

File: src/compiler/types.ts [hunk 3]
```diff
@@ -4249,6 +4249,7 @@ namespace ts {
         outerTypeParameters?: TypeParameter[];  // Outer type parameters of anonymous object type
         instantiations?: Map<Type>;         // Instantiations of generic type alias (undefined if non-generic)
         isExhaustive?: boolean;           // Is node an exhaustive switch statement
+        skipDirectInference?: true;         // Flag set by the API `getContextualType` call on a node when `BaseConstraint` is passed to force the checker to skip making inferences to a node's type
```
Comment (weswigham) [inline src/compiler/types.ts]: This comment needs to be updated with the new flag name.

File: src/compiler/types.ts [hunk 4]
```diff
@@ -3611,7 +3611,7 @@ namespace ts {
         None           = 0,
         Signature      = 1 << 0, // Obtaining contextual signature
         NoConstraints  = 1 << 1, // Don't obtain type variable constraints
-        BaseConstraint = 1 << 2, // Use base constraint type for completions
+        Completions    = 1 << 2, // Ignore inference to current node for completions
```
Comment (weswigham) [inline src/compiler/types.ts]:
```suggestion
        Completions    = 1 << 2, // Ignore inference to current node and parent nodes out to the containing call for completions

```

File: tests/cases/fourslash/completionsGenericIndexedAccess6.ts (hunk 1 above)
Comment (andrewbranch) [reply tests/cases/fourslash/completionsGenericIndexedAccess6.ts]: I often miss these because editor support works as long as you have another file open with the triple-slash 😦

Comment (weswigham) [reply tests/cases/fourslash/completionsGenericIndexedAccess6.ts]: hah, yeah.
