### PR TITLE
Fix crash when creating a union signature from signatures that do and don’t have `this` types

### LINKED ISSUE #31485: Crash involving union of function types
**TypeScript Version:**  3.5.0-dev.20190518

**Search Terms:**
Cannot read property 'flags' of undefined
createSymbolWithType

**Code**

```ts
interface A {
    (this: void, a: string, b: number, c?: string): void;
    (this: void, b: number, c?: string): void;
}
interface B {
    (i: number): number;
}
declare const fn: A | B;
fn(0);
```

**Expected behavior:**
Should not crash.

**Actual behavior:**
tsc crashes with the following output:
```
node_modules\typescript\lib\tsc.js:72973
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at createSymbolWithType (node_modules\typescript\lib\tsc.js:36787:46)
    at getUnionSignatures (node_modules\typescript\lib\tsc.js:30929:53)
    at resolveUnionTypeMembers (node_modules\typescript\lib\tsc.js:31021:34)
    at resolveStructuredTypeMembers (node_modules\typescript\lib\tsc.js:31330:21)
    at getSignaturesOfStructuredType (node_modules\typescript\lib\tsc.js:31782:32)
    at getSignaturesOfType (node_modules\typescript\lib\tsc.js:31788:20)
    at resolveCallExpression (node_modules\typescript\lib\tsc.js:42223:34)
    at resolveSignature (node_modules\typescript\lib\tsc.js:42494:28)
    at getResolvedSignature (node_modules\typescript\lib\tsc.js:42514:26)
    at checkCallExpression (node_modules\typescript\lib\tsc.js:42585:29)
```

**Playground Link:** 

**Related Issues:** 
#29884 may be related, as there's an example with a similar callstack, but it's closed as fixed already.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #31485 but not #31547 since that would be a breaking change

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7052,10 +7052,10 @@ namespace ts {
                             // Union the result types when more than one signature matches
                             if (unionSignatures.length > 1) {
                                 let thisParameter = signature.thisParameter;
-                                if (forEach(unionSignatures, sig => sig.thisParameter)) {
-                                    // TODO: GH#18217 We tested that *some* has thisParameter and now act as if *all* do
+                                const firstThisParameterOfUnionSignatures = forEach(unionSignatures, sig => sig.thisParameter);
+                                if (firstThisParameterOfUnionSignatures) {
                                     const thisType = getUnionType(map(unionSignatures, sig => sig.thisParameter ? getTypeOfSymbol(sig.thisParameter) : anyType), UnionReduction.Subtype);
-                                    thisParameter = createSymbolWithType(signature.thisParameter!, thisType);
+                                    thisParameter = createSymbolWithType(firstThisParameterOfUnionSignatures, thisType);
```
Comment (andrewbranch) [inline src/compiler/checker.ts]: It feels fairly arbitrary to just pick the first one of these as the source for the new transient symbol, but as far as I can tell it doesn't matter. I thought maybe it would cause an odd behavior for go-to-definition, but then I discovered that go-to-definition on union signatures is already arbitrarily limited to a single signature (#31559), and it doesn't seem to be affected by this change. I briefly experimented with doing a proper merge of every `thisParameter` symbol, but since I couldn't find any observable effect and go-to-definition on the call expression is already kinda broken, I opted not to use the extra memory and CPU cycles to perform a merge that you probably can't observe anyway. It might be worth revisiting this in #31547 or #31559.
