### PR TITLE
Handle merging unknownSymbol

### LINKED ISSUE #28380: Crash in `getRootDeclaration` when both global namespace and `export as namespace` exist
**TypeScript Version:**  3.2.0-dev.20181106

**Code**

```ts
declare global { namespace N {} }
export = N;
export as namespace N;
```

**Expected behavior:**

No crash.

**Actual behavior:**

```
TypeError: Cannot read property 'kind' of undefined
    at getRootDeclaration (typescript\lib\tsc.js:8182:21)
    at Object.isCatchClauseVariableDeclarationOrBindingElement (typescript\lib\tsc.js:6311:20)
    at getTypeOfVariableOrParameterOrPropertyWorker (typescript\lib\tsc.js:29148:20)
    at getTypeOfVariableOrParameterOrProperty (typescript\lib\tsc.js:29132:48)
    at getTypeOfSymbol (typescript\lib\tsc.js:29401:24)
    at checkIdentifier (typescript\lib\tsc.js:37975:49)
    at checkExpressionWorker (typescript\lib\tsc.js:42937:28)
    at checkExpression (typescript\lib\tsc.js:42913:42)
    at checkExpressionCached (typescript\lib\tsc.js:42796:38)
    at markAliasSymbolAsReferenced (typescript\lib\tsc.js:26588:21)
```

Discovered in `business-rules-engine` on DefinitelyTyped.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #28380

We handle `unknownSymbol` specially in many places. It looks like when we make a clone of it we undo some of that special handling, and end up crashing since its flags make it a `Property` but it has no `valueDeclaration` as expected.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -390,7 +390,7 @@ namespace ts {
         const evolvingArrayTypes: EvolvingArrayType[] = [];
         const undefinedProperties = createMap<Symbol>() as UnderscoreEscapedMap<Symbol>;
 
-        const unknownSymbol = createSymbol(SymbolFlags.Property, "unknown" as __String);
+        const unknownSymbol = createSymbol(SymbolFlags.Property, "<<unknown>>" as __String);
```
Comment (sandersn) [inline src/compiler/checker.ts]: This change doesn't seem necessary; I don't think we show this to the user much.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -877,7 +877,11 @@ namespace ts {
                 (source.flags | target.flags) & SymbolFlags.Assignment) {
                 Debug.assert(source !== target);
                 if (!(target.flags & SymbolFlags.Transient)) {
-                    target = cloneSymbol(resolveSymbol(target));
+                    const resolvedTarget = resolveSymbol(target);
```
Comment (sandersn) [inline src/compiler/checker.ts]: I'm not sure sure we should be merging unknownSymbol at all; I'll try to track down its origin to see whether there's some other symbol that should appear here.
