### PR TITLE
Fix compiler crash on property symbols without declarations

### LINKED ISSUE #44970: Crash report
# Bug Report
### 💻 Code

```sh
$ git clone https://github.com/devanshj/txstate.git
$ git checkout tsc-crash-1
$ yarn
$ yarn tsc --noEmit
```

You can check the last commit that caused the crash. The change is very minimal, so it'll be easier to debug.

### 🙁 Actual behavior

`tsc` exited with code 1, here's the stack trace
```
E:\txstate\node_modules\typescript\lib\tsc.js:92222
                throw e;
                ^

TypeError: Cannot read property 'length' of undefined
    at Object.first (E:\txstate\node_modules\typescript\lib\tsc.js:978:31)
    at addPropertyToElementList (E:\txstate\node_modules\typescript\lib\tsc.js:41273:35)
    at createTypeNodesFromResolvedType (E:\txstate\node_modules\typescript\lib\tsc.js:41243:29)
    at createTypeNodeFromObjectType (E:\txstate\node_modules\typescript\lib\tsc.js:41067:35)
    at visitAndTransformType (E:\txstate\node_modules\typescript\lib\tsc.js:41009:34)
    at createAnonymousTypeNode (E:\txstate\node_modules\typescript\lib\tsc.js:40952:36)
    at typeToTypeNodeHelper (E:\txstate\node_modules\typescript\lib\tsc.js:40853:28)
    at serializeTypeForDeclaration (E:\txstate\node_modules\typescript\lib\tsc.js:41979:30)
    at addPropertyToElementList (E:\txstate\node_modules\typescript\lib\tsc.js:41309:59)
    at createTypeNodesFromResolvedType (E:\txstate\node_modules\typescript\lib\tsc.js:41246:25)
```

### 🙂 Expected behavior

`tsc` should exit with code 0

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #44970

In short, the checker crash was caused by the fact that properties that go through a mapped type with an `as` clause don't have declarations attached to their symbols (#44609), but `addPropertyToElementList`, a function used for serializing type nodes, relied on late-bound property symbols having declarations (`propertySymbol.declarations`).

The fix here is to make the part of `addPropertyToElementList` that relies on `propertySymbol.declarations` actually check if declarations is defined before accessing it.
In addition, there is now a declaration emit reporter for when we reach a late-bound symbol that has no declarations attached, as that should be an error since we shouldn't serialize that property type for declaration emit purposes.

### CODE REVIEW

File: src/compiler/transformers/declarations.ts [hunk 1]
```diff
@@ -77,9 +77,10 @@ namespace ts {
             moduleResolverHost: host,
             trackReferencedAmbientModule,
             trackExternalModuleSymbolOfImportTypeNode,
-            reportNonlocalAugmentation
+            reportNonlocalAugmentation,
+            reportNonSerializableProperty
         };
-        let errorNameNode: DeclarationName | undefined;
+        let errorNameNode: DeclarationName | undefined; // What's this??
```
Comment (weswigham) [inline src/compiler/transformers/declarations.ts:83]: It's the closest `DeclarationName` the declaration emitter has recurred into. Might wanna remove this comment. :3

File: tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.errors.txt [hunk 2]
```diff
@@ -0,0 +1,11 @@
+tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty2.ts(1,14): error TS4118: The type of this node cannot be serialized because its property '__@iterator@8' cannot be serialized.
+tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty2.ts(1,14): error TS4118: The type of this node cannot be serialized because its property '__@unscopables@10' cannot be serialized.
+
+
+==== tests/cases/compiler/mappedTypeWithAsClauseAndLateBoundProperty2.ts (2 errors) ====
+    export const thing = (null as any as { [K in keyof number[] as Exclude<K, "length">]: (number[])[K] });
+                 ~~~~~
+!!! error TS4118: The type of this node cannot be serialized because its property '__@iterator@8' cannot be serialized.
```
Comment (weswigham) [inline tests/baselines/reference/mappedTypeWithAsClauseAndLateBoundProperty2.errors.txt:8]: Ack, this error leaks the internal symbol name structure. I'd prefer if we could print almost anything else (after all, it's not going to be clear to a user what `__@iterator@8` is) - `symbolToString`'s imprecise result `[iterator]` is probably better than `symbolName` here.

**Review by weswigham — CHANGES_REQUESTED** [review]

**Comment by RyanCavanaugh** [comment]
@weswigham gtg?

**Review by weswigham — APPROVED** [review]
