### PR TITLE
Only resolve symlinks in `node_modules`

### LINKED ISSUE #10364: Compiled folder structure wrong when using folder link
**TypeScript Version:** 2.0.0  (on Windows)

**Project structure**

```
|- shared
    |- abc.ts

|- src
    |- shared (link to ../shared, not real folder)
    |- app.ts
    |- tsconfig.json
```

**Code**

``` ts
//abc.ts
console.log('abc');

//app.ts
import './shared/abc.ts';
console.log('app')
```

**And run cmd on Windows to create folder link:**

```
mklink /J src\shared shared
```

**Finally run compile command:**

```
cd src
tsc -p . --outDir dist
```

**Expected behavior:**

file structure in folder dist as below:

```
|- shared
    |- abc.js
|- app.js
```

It works well on TypeScript@1.8.0,
and can't work after I updated it to 2.0.0.

**Actual behavior:** 

```
|- shared
    |- abc.js
|- src
    |- app.js
```

Note that [shared] and [src] were placed at different with it on 1.8.0

**The same problem on Linux**

using command below to create folder link

``` ts
ln -s $(pwd)/shared src/shared
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #10364 and #9552.
This is based on #11993 and will be rebased onto master once that is merged.

Based on the issues I've seen, the best heuristic to decide whether to resolve a symlink is whether it comes from `node_modules`. So we now do *not* resolve symlinks for ordinary files. (This is a breaking change.)

The change to `moduleNameResolver` is simple. However, our test harness did not accurately reflect what the command line compiler really did, so I had to change how it treated symlinks. I've tested the new tests with the command line compiler as well; instructions for doing so are at the bottom of each test file.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by mhegazy** [comment]
I thought we were not going to resolve symlinks in resolveModuleNames at all, so what is the reason for the change of strategy?

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -563,7 +563,8 @@ namespace ts {
                     trace(host, Diagnostics.Loading_module_0_from_node_modules_folder, moduleName);
                 }
                 const resolved = loadModuleFromNodeModules(extensions, moduleName, containingDirectory, failedLookupLocations, state, /*checkOneLevel*/ false);
-                return resolved && { resolved, isExternalLibraryImport: true };
+                // For node_modules lookups, get the real path so that multiple accesses to an `npm link`-ed module do not create duplicate files.
+                return resolved && { resolved: resolvedWithRealpath(resolved, host, traceEnabled), isExternalLibraryImport: true };
             }
```
Comment (mhegazy) [inline src/compiler/moduleNameResolver.ts]: you need to do the same for resolveTypeReferenceDirectives as well.

File: src/compiler/program.ts [hunk 2]
```diff
@@ -431,13 +431,14 @@ namespace ts {
         return program;
 
         function getCommonSourceDirectory() {
-            if (typeof commonSourceDirectory === "undefined") {
-                if (options.rootDir && checkSourceFilesBelongToPath(files, options.rootDir)) {
+            if (commonSourceDirectory === undefined) {
+                const emittedFiles = filterSourceFilesInDirectory(files, isSourceFileFromExternalLibrary);
```
Comment (vladima) [inline src/compiler/program.ts]: don't think that changes in the way how common subpath is computed should not be the part of this PR since it is not related to original issue

Comment (andy-ms) [inline src/compiler/program.ts]: Review #11993, then I'll rebase.

**Comment by devedse** [comment]
Can/will this fix be included in the next release of TypeScript (2.0.10)?

**Comment by mhegazy** [comment]
yes, and the next release is TypeScript 2.1.3

**Comment by andy-ms** [comment]
I think this was just the simplest place to do the resolving.
If the host doesn't define `realPath`, it's treated the same as `path => path`. In both cases, it means the compiler will always see a symlink as a different file from the original; since it can't resolve the symlink, it has no way of knowing they're the same file. See `function realPath` in `moduleNameResolver.ts`.

**Comment by timocov** [comment]
@andy-ms Thank you for clarification!

> it has no way of knowing they're the same file

What can happen in this case except getting multiple `SourceFile` instances for one real file but for each symlink (and, possibly, increasing memory usage or compilation time)? How it can affect on compilation?

**Comment by timocov** [comment]
Oh, I get it. Thank you!
