### PR TITLE
Refine extends-to-implements code fix

### LINKED ISSUE #18794: Bad formatting for codefix to change extends to implements
**TypeScript Version:**  nightly (2.6.0-dev.20170927)

See the fourslash test `codeFixChangeExtendsToImplementsAbstractModifier.ts` and `codeFixChangeExtendsToImplementsWithDecorator.ts`.

**Code**

```ts
abstract class A extends I1 implements I2 { }
```

**Expected behavior:**

```ts
abstract class A implements I1, I2 { }
```

**Actual behavior:**

```ts
abstract class A implements I1 , I2 { }
```

### PR DESCRIPTION
**Pull request by amcasey**
1. Retain surrounding trivia when swapping the keyword.
 2. Insert commas at the full-starts, rather than starts, of existing
 keywords when merging with existing implements clauses.

Fixes #18794

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @sandersn who periodically has to deal with trivia issues in code fixes and refactorings.

File: src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts [hunk 1]
```diff
@@ -27,11 +27,22 @@ namespace ts.codefix {
     }
 
     function doChanges(changes: textChanges.ChangeTracker, sourceFile: SourceFile, extendsToken: Node, heritageClauses: ReadonlyArray<HeritageClause>): void {
-        changes.replaceNode(sourceFile, extendsToken, createToken(SyntaxKind.ImplementsKeyword));
+        changes.replaceRange(sourceFile, { pos: extendsToken.getStart(), end: extendsToken.end }, createToken(SyntaxKind.ImplementsKeyword));
         // We replace existing keywords with commas.
         for (let i = 1; i < heritageClauses.length; i++) {
```
Comment (andy-ms) [inline src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts]: It was this way before, but shouldn't this only apply to `heritageClauses[1]` since the others will have commas already?

File: src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts [hunk 2]
```diff
@@ -27,11 +27,22 @@ namespace ts.codefix {
     }
 
     function doChanges(changes: textChanges.ChangeTracker, sourceFile: SourceFile, extendsToken: Node, heritageClauses: ReadonlyArray<HeritageClause>): void {
-        changes.replaceNode(sourceFile, extendsToken, createToken(SyntaxKind.ImplementsKeyword));
+        changes.replaceRange(sourceFile, { pos: extendsToken.getStart(), end: extendsToken.end }, createToken(SyntaxKind.ImplementsKeyword));
         // We replace existing keywords with commas.
         for (let i = 1; i < heritageClauses.length; i++) {
             const keywordToken = heritageClauses[i].getFirstToken()!;
```
Comment (andy-ms) [inline src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts]: Might want to assert that this is `SyntaxKind.ImplementsKeyword`.

Comment (amcasey) [reply src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts]: My thinking was that that assertion would fail in invalid code (e.g. multiple extends clauses or an out-of-order extends clause).  I'm not convinced it's worthwhile to harden a best-effort code fix against that sort of bad code (the user will already be getting a diagnostic and the change is undoable), but I don't feel strongly about it.  However, I'd only add the assert if we were also adding actual checks.

File: src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts (hunk 1 above)
Comment (amcasey) [reply src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts]: I thought that `implements I1, I2` counted as a single heritage clause (and that, in correct code, heritageClauses would have 0, 1, or 2 elements).

**Comment by amcasey** [comment]
@andy-ms I don't think I can use the `replaceNode` call you suggest because it will clobber the trivia of the replaced keyword.  I did consider updating the list of types in the existing implements clause, but it wasn't clear where all the trivia would go in that case.  @sandersn and I discussed it offline (before I implemented it) and concluded that this was the closest to what a user would do by hand.

File: src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts (hunk 1 above)
Comment (andy-ms) [reply src/services/codefixes/fixExtendsInterfaceBecomesImplements.ts]: OK, but then we don't need the loop, just an `if`.

**Comment by amcasey** [comment]
Good to go?
