### PR TITLE
Fix cross-file merge of assignment decl valueDeclaration

### LINKED ISSUE #26877: In JS, references to class type get static type, not instance type
Note that this bug depends on the order of the files in the file list. It is very likely in the merge code in the checker. Based on code in chrome-devtools-frontend.

```js
// @Filename: file1.js
var Em = {};
/** @type {number} */
Em.Cee._wrapperInstance;

// @Filename: file2.js
/** @param {Em.Cee} dmv */
function oops(dmv) {
    dmv._model           // should be ok
    // dmv._wrapperInstance // should be error
    new Em.Cee(); // ok?
}
Em.Cee = class {
  constructor() {
    this._model = 111
  }
};
```

**Expected behavior:**
Expressions `dmv._model` and `new Em.Cee()` should not be errors. `dmv._wrapperInstance` should be an error.

**Actual behavior:**
The opposite; "'_model' is not found on 'typeof Em.Cee'" and "Cannot new something that isn't callable or constructable."

### PR DESCRIPTION
**Pull request by sandersn**
Previously mergeSymbol in the checker always updated valueDeclaration if target.valueDeclaration was an assignment declaration. The binder only updates target.valueDeclaration if it is an assignment declaration and source.valueDeclaration is *not* an assignment declaration. 

Now the checker behaves the same way as the binder.

Fixes #26877

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Baseline diff in jsContainerMergeJsContainer on CI

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -923,6 +923,14 @@ namespace ts {
             return combined;
         }
 
+        /** CommonJS is *almost* a module -- no merges -- except that assignment declarations need to merge with globals. */
+        function mergeCommonJsSymbolTable(target: SymbolTable, source: SymbolTable) {
+            source.forEach((sourceSymbol, id) => {
+                if (target.has(id) && sourceSymbol.flags & SymbolFlags.Assignment) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: Talking with @weswigham, he pointed out that it would be better to store all the identifier-unbound declarations in a separate per-file commonJSGlobalAugmentations property that gets merged into globals instead of trying to filter here (there are plenty of symbols marked with Assignment that shouldn't necessarily merge with globals).

**Comment by sandersn** [comment]
All right, the new table is in. I dropped the "common" part since all JS files create global augmentations, and they all need to be merged, regardless of whether they are in a commonJS module.
