### PR TITLE
Clear ExportMapCache on cancellation requested

### LINKED ISSUE #48880: Auto-import consistently failing after a few minutes (happening in vscode, nightly ts)
# Bug Report

I'm sorry, this may not be a very good bug report, but auto-import consistently stops working after a few minutes. I have posted a bit of logging below.

### 🔎 Search Terms

Auto-import crashes, Auto import failing, Auto import broken
### 🕗 Version & Regression Information

- None of these are applicable. I am using typescript nightly in vscode, and it has happened on an off for a long time.

### 🙁 Actual behavior

After a few minutes of work, auto importing stops working. If restart the tsserver in vscode the auto imports work again on the same line of code. This happens repeatedly after 10-15 minutes of coding. Even when importing the same thing in a different file. I noticed this in this logs:

```
Info 737  [14:16:50.020] getCompletionData: Get current token: 0.011509895324707031
Info 738  [14:16:50.020] getCompletionData: Is inside comment: 0.0037658214569091797
Info 739  [14:16:50.020] getCompletionData: Get previous token: 0.04294610023498535
Info 740  [14:16:50.020] getCompletionsAtPosition: isCompletionListBlocker: 0.01444697380065918
Info 741  [14:16:50.025] AutoImportProviderProject: attempted to add more than 10 dependencies. Aborting.
Info 742  [14:16:50.026] getExportInfoMap: cache hit
Info 743  [14:16:50.027] AutoImportProviderProject: attempted to add more than 10 dependencies. Aborting.
Info 744  [14:16:50.034] collectAutoImports: resolved 0 module specifiers, plus 0 ambient and 0 from cache
Info 745  [14:16:50.034] collectAutoImports: response is complete
Info 746  [14:16:50.034] collectAutoImports: 6.69482684135437
Info 747  [14:16:50.034] getCompletionData: Semantic work: 14.261340141296387
Info 748  [14:16:50.045] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 11.098047971725464
```

As you can see, it does find results `attempted to add more than 10 dependencies`, but then it bails out with `no suggestions` in the vscode intellisense dropdown.

### 🙂 Expected behavior

Auto import works consistently.

### PR DESCRIPTION
**Pull request by andrewbranch**
Almost certainly fixes #48880

### CODE REVIEW

File: src/services/types.ts [hunk 1]
```diff
@@ -182,6 +182,10 @@ namespace ts {
         isCancellationRequested(): boolean;
     }
 
+    export interface CancellationToken {
+        throwIfCancellationRequested(cleanup?: () => void): void;
```
Comment (andrewbranch) [inline src/services/types.ts:186]: I added this instead of just asking `isCancellationRequested` and throwing on my own because I wanted to keep the built-in tracing.

File: src/services/exportInfoMap.ts [hunk 2]
```diff
@@ -382,7 +382,12 @@ namespace ts {
         const compilerOptions = program.getCompilerOptions();
         let moduleCount = 0;
         forEachExternalModuleToImportFrom(program, host, /*useAutoImportProvider*/ true, (moduleSymbol, moduleFile, program, isFromPackageJson) => {
-            if (++moduleCount % 100 === 0) cancellationToken?.throwIfCancellationRequested();
+            if (++moduleCount % 100 === 0) {
```
Comment (sheetalkamat) [inline src/services/exportInfoMap.ts:385]: passing cleanup callback might not be enough right? Cancellation can be done even in checker and dont you need to protect cache against that. 
May be have cache aware of checker used? or do in finally block of try catch ?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/exportInfoMap.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/exportInfoMap.ts:385]: Ah yeah, good point. I don’t think the checker actually cancels in practice with these calls, because otherwise I wouldn’t have had to check for cancellation out here. But theoretically you’re right, this could miss stuff.

**Review by sheetalkamat — APPROVED** [review]
