### PR TITLE
Never escape string literals from textChanges

### LINKED ISSUE #26967: Auto import unicode escapes characters in path
_From @rodrigojcmello on September 7, 2018 14:54_

 

- VSCode Version: 1.27.1
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Import some module with accent using "auto import"

Auto import with accent works fine but is ugly/annoying to see how is imported (In portuguese there are a lot of words with accents);

Before import the module looks ok in auto complete but it changes after importation.

Does this issue occur when all extensions are disabled?: Yes

captura de tela 2018-09-07 as 11 41 28
captura de tela 2018-09-07 as 11 41 52

_Copied from original issue: Microsoft/vscode#58200_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #26967
Does not fix issue #26972

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -3305,20 +3305,20 @@ namespace ts {
             return getSourceTextOfNodeFromSourceFile(currentSourceFile, node, includeTrivia);
         }
 
-        function getLiteralTextOfNode(node: LiteralLikeNode): string {
+        function getLiteralTextOfNode(node: LiteralLikeNode, neverAsciiEscape: boolean): string {
```
Comment (sheetalkamat) [inline src/compiler/emitter.ts]: Can you make neverAsciiEscape Boolean | undefined so that in above change you don't need to pass || false?

**Comment by andy-ms** [comment]
@sheetalkamat Please re-review
