### PR TITLE
Dom lib file bug fix

### LINKED ISSUE #3344: texImage2D broken as of tsc 1.5
Calling the base version of the webgl function texImage2D (taking an ArrayBufferView of pixel data) results in:

`error TS2346: Supplied parameters do not match any signature of call target.`

Looks like the lib.d.ts only includes the definition for the version taking 'ImageData' for pixels.

### PR DESCRIPTION
**Pull request by zhengbli**
Fix #3344; removed duplicated overloads for ``createEvent`` and some
minor fixes.

### CODE REVIEW

File: src/lib/dom.generated.d.ts [hunk 1]
```diff
@@ -12332,12 +12333,14 @@ interface DocumentEvent {
...
     createEvent(eventInterface:"BeforeUnloadEvent"): BeforeUnloadEvent;
+    createEvent(eventInterface:"ClipboardEvent"): ClipboardEvent;
     createEvent(eventInterface:"CloseEvent"): CloseEvent;
     createEvent(eventInterface:"CommandEvent"): CommandEvent;
     createEvent(eventInterface:"CompositionEvent"): CompositionEvent;
-    createEvent(eventInterface: "CustomEvent"): CustomEvent;
+    createEvent(eventInterface:"CustomEvent"): CustomEvent;
     createEvent(eventInterface:"DeviceMotionEvent"): DeviceMotionEvent;
     createEvent(eventInterface:"DeviceOrientationEvent"): DeviceOrientationEvent;
+    createEvent(eventInterface:"DocumentEvent"): DocumentEvent;
```
Comment (mhegazy) [inline src/lib/dom.generated.d.ts]: this is causing an error as DocumentEvent is not assignable to Event, as it does not inherit from it. is this by design?

Comment (zhengbli) [inline src/lib/dom.generated.d.ts]: This is not by design, it's because in the script I treated interfaces with a name ended with "Event" as event names. I added additional checking for the extended base interface to be 'Event', DocumentEvent turns out to be the only exception. Updating it soon.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
this needs to get into release-1.5 branch. We need to check RWC results first though.
