### PR TITLE
fix(45102): Refactor to convert to/from arrow function does not consider 'arguments'

### LINKED ISSUE #45102: Refactor to convert to/from arrow function does not consider 'arguments'
The returned functions in

```ts
function foo() {
    return () => { arguments; }
}
```

and

```ts
function foo() {
    return function () { arguments; }
}
```

mean different things, however, we provide refactorings to convert between them. Typically, we don't provide the option to convert between them if they use `this`, so we should probably do the same in the presence of the `arguments` object.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45102

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/refactors/convertArrowFunctionOrFunctionExpression.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ namespace ts.refactor.convertArrowFunctionOrFunctionExpression {
         const token = getTokenAtPosition(file, startPosition);
         const typeChecker = program.getTypeChecker();
         const func = tryGetFunctionFromVariableDeclaration(file, typeChecker, token.parent);
-        if (func && !containingThis(func.body)) {
+        if (func && !containingThis(func.body) && !typeChecker.containsArgumentsReference(func)) {
```
Comment (DanielRosenwasser) [inline src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:144]: Do these walk the function twice? Probably not a huge deal right now, but it would be smarter to use our find-all-references logic long-term.

Comment (a-tarasyuk) [reply src/services/refactors/convertArrowFunctionOrFunctionExpression.ts:144]: Oke. Will check it later.
