### PR TITLE
fix(36140): Implement interface does not respect quotePreference

### LINKED ISSUE #36140: Implement interface does not respect quotePreference
From https://github.com/microsoft/vscode/issues/87782

**TypeScript Version:**  3.8.0-beta

**Search Terms:**
- quick fix 
- implement interface
- configure
- quotePreference

**Code**
For the TS:

```ts
interface IFoo {
    prop: 'string';
}

class Foo implements IFoo {}
```

1. In VS Code set, `"typescript.preferences.quoteStyle": "single"`
1. Run the implement interface quick fix on `Foo`

**Expected behavior:**
Single quotes used for `prop`

**Actual behavior:**
Double quotes still used

```ts
interface IFoo {
    prop: 'string';
}

class Foo implements IFoo {
    prop: "string";
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #36140

### CODE REVIEW

File: src/services/codefixes/helpers.ts [hunk 1]
```diff
@@ -56,15 +56,21 @@ namespace ts.codefix {
...
         switch (declaration.kind) {
             case SyntaxKind.PropertySignature:
             case SyntaxKind.PropertyDeclaration:
-                const typeNode = checker.typeToTypeNode(type, enclosingDeclaration, /*flags*/ undefined, getNoopSymbolTrackerWithResolver(context));
+                const propName = isStringLiteral(name)
+                    ? createLiteral(name.text, /*isSingleQuote*/ isSingleQuote)
+                    : name;
+                const typeNode = type.isStringLiteral()
+                    ? createLiteralTypeNode(createLiteral(type.value, /*isSingleQuote*/ isSingleQuote))
+                    : checker.typeToTypeNode(type, enclosingDeclaration, /*flags*/ undefined, getNoopSymbolTrackerWithResolver(context));
```
Comment (sheetalkamat) [inline src/services/codefixes/helpers.ts]: This is not enough, since in interface if there is property `fooBar: { x: 'stringliteral' }` it wont get correctly quoted. We need to pass this to `typeToTypeNode` rather than doing it here.

Comment (a-tarasyuk) [reply src/services/codefixes/helpers.ts]: @sheetalkamat thanks for the feedback. will check.

File: src/compiler/types.ts [hunk 2]
```diff
@@ -3672,6 +3673,7 @@ namespace ts {
         OmitParameterModifiers                  = 1 << 13, // Omit modifiers on parameters
 
         UseAliasDefinedOutsideCurrentScope      = 1 << 14, // For a `type T = ... ` defined in a different file, write `T` instead of its value, even though `T` can't be accessed in the current scope.
+        UseSingleQuotesForStringLiteralType     = 1 << 28, // Use single quotes for string literal type
```
Comment (sheetalkamat) [inline src/compiler/types.ts]: You need this flag in `NodeBuilderFlagsMask`  as well.

**Comment by sheetalkamat** [comment]
@a-tarasyuk thank you for working on this.
