### PR TITLE
Emit fallback for decorator metadata for type only imports

### LINKED ISSUE #37672: emitDecoratorMetadata causes runtime errors by referencing type-only imports
**TypeScript Version:**  3.9.0-dev.20200329

**Search Terms:** emitDecoratorMetadata type import

When combining `emitDecoratorMetadata` with type-only imports, the generated code crashes at runtime. I've been unable to produce a repro on the playground, since it somehow adds another [undefined check](https://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&target=2&module=1#code/JYWwDg9gTgLgBDAnmApnA3nAYhCAhAQyjgF84AzKCEOAIhQA8DwAbFAWhAgBMBXN2gG4AUMPK8AdgGMYwCBLghEAERRToBGNAAUASgzC4RuFBQxeUBdqSoAXHAITE+gLwA+DKWElRAASWq6lCaOrrCjJCwcFIsBADOcXAAsoh4VADWKBIAwrEJBsbR8nEwULwyOuS49jj4RPqYPj5AA), so I'll show you real-world code where this happens:

1. clone `https://github.com/AlCalzone/node-zwave-js/tree/41da020d7515826e3e8fc2e0c3fc24a0d3c19355`
2. `npm i`
3. `npm i -D typescript@3.9.0-dev.20200329`
4. `npm run build`
5. look at the output file `build/lib/commandclass/MultiChannelCC.js`

**Code**
This is the core of the problem
```ts
import type { Driver } from "../driver/Driver";
// ...
export class MultiChannelCC extends CommandClass {
	// ...
	public constructor(driver: Driver, options: CommandClassOptions) {
		// ...
	}
}
```

**Expected behavior:**
like on the playground link above

**Actual behavior:**
```js
    MultiChannelCC = __decorate([
        CommandClass_1.commandClass(CommandClasses_1.CommandClasses["Multi Channel"]),
        CommandClass_1.implementedVersion(4),
        __metadata("design:paramtypes", [Driver, Object])
    ], MultiChannelCC);
```
Notice how the value side of `Driver` is referenced at runtime, although the import is type-only.

**Playground Link:** Playground does not allow relative imports

**Related Issues:** https://github.com/microsoft/TypeScript/issues/27519

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes our emit for decorator metadata when the referenced type comes from a type-only import.

Fixes #37672

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -36973,29 +36973,31 @@ namespace ts {
...
                 if (constructorType && isConstructorType(constructorType)) {
-                    return TypeReferenceSerializationKind.TypeWithConstructSignatureAndValue;
+                    return isTypeOnly ? TypeReferenceSerializationKind.TypeWithCallSignature : TypeReferenceSerializationKind.TypeWithConstructSignatureAndValue;
                 }
             }
 
             // We might not be able to resolve type symbol so use unknown type in that case (eg error case)
             if (!typeSymbol) {
-                return TypeReferenceSerializationKind.Unknown;
+                return isTypeOnly ? TypeReferenceSerializationKind.ObjectType : TypeReferenceSerializationKind.Unknown;
```
Comment (andrewbranch) [inline src/compiler/checker.ts:36996]: How do we know the type is objecty? You can `import type` a primitive.

Comment (rbuckton) [reply src/compiler/checker.ts:36996]: `TypeSerializationKind.ObjectType` tells the `ts` transform to emit `Object` for the type metadata (which essentially means `any`). `TypeSerializationKind.Unknown` means we should try to resolve a value at runtime using that name (by using `typeof` testing), which would be incorrect behavior. Consider the following using the current version of the compiler (without this change):

```ts
// ts
import { dec } from "./decorators";
import type { Map } from "./myMap";

@dec
export class C {
  constructor(map: Map) {}
}

// js
...
let C = /** @class */ (() => {
    var _a;
    let C = class C {
        constructor(map) { }
    };
    C = __decorate([
        dec,
        __metadata("design:paramtypes", [typeof (_a = typeof Map !== "undefined" && Map) === "function" ? _a : Object])
    ], C);
    return C;
})();
```

The `design:paramtypes` metadata for `C` will *incorrectly* use the global `Map` object.

For a type-only import we can be *certain* that the type cannot be referenced as a value, so we should emit `Object` instead of trying to resolve a value for it.

**Comment by liorcode** [comment]
Seems this problem still happens in typescript 4.1.3, when using a type which is nested inside a namespace.

For example:
```
// services.ts

export namespace Services {
  export class Service {}
}


// main.ts
import type { Services } from './services';

declare const decorator: any;
export class Main {
  @decorator()
  fieldTest: Services.Service;
}

```

JS output:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Main = void 0;
const tslib_1 = require("tslib");
class Main {
}
tslib_1.__decorate([
    decorator(),
    tslib_1.__metadata("design:type", Services.Service)
], Main.prototype, "fieldTest", void 0);
exports.Main = Main;

```
(`Services` is undefined)

**Comment by andrewbranch** [comment]
@liorcode would you mind filing a new issue? Thanks!
