### PR TITLE
Make getContextualTypeOfApparentType mapType over unions

### LINKED ISSUE #16817: Contextual typing not working on optional members
The following sample works perfectly in `noImplicitAny` *unless* I turn on `strictNullChecks`. In that event, the `s` parameter on `foo` seems to get an implicit `any`.

```ts
interface ActionsObject<State> {
    [prop: string]: (state: State) => State
}

interface Options<State, Actions> {
    state?: State;
    view?: (state: State, actions: Actions) => any;
    actions?: Actions;
}

declare function app<State, Actions extends ActionsObject<State>>(obj: Options<State, Actions>): void;

app({
    state: 100,
    actions: {
        foo: s => s
    },
    view: (s, a) => null as any,
})
```

If I make `actions` non-optional, then things work perfectly again.

Context: https://github.com/hyperapp/hyperapp/issues/87

### PR DESCRIPTION
**Pull request by weswigham**
This allows us to actually find member types for union-typed object members in the same way we do for non-unions.

Fixes #16817.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13119,12 +13119,23 @@ namespace ts {
...
             return type && getApparentType(type);
         }
 
         /**
+         * This must be called when a contextual type function is attempting to dig into a type to contextually type a subexpression
+         * Otherwise, contextual typing stops when a type argument is encountered, and `any` is ued instead.
+         */
+        function getInstantiatedContextualType(node: Expression, checkMode?: CheckMode): Type {
+            if (checkMode === CheckMode.Inferential && node.contextualType && node.contextualMapper) {
+                return instantiateType(node.contextualType, node.contextualMapper);
```
Comment (sandersn) [inline src/compiler/checker.ts]: don't you still need to get an apparent type in case the result is still a type parameter?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16844,7 +16855,7 @@ namespace ts {
 
             // Check if function expression is contextually typed and assign parameter types if so.
             if (!(links.flags & NodeCheckFlags.ContextChecked)) {
-                const contextualSignature = getContextualSignature(node);
+                const contextualSignature = getContextualSignature(node); // Intentionally do not pass check mode; resolve without instantiation
```
Comment (sandersn) [inline src/compiler/checker.ts]: why? Because it's not NodeCheckFlags.ContextChecked?

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [inline src/compiler/checker.ts]: Absolutely. I used to be doing it at use-site, but forgot to add it back when I decided not to. Good catch; that's actually why there were baseline changes, and why the build was broken. It's a much neater fix now. 🐱

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -4515,7 +4515,7 @@ namespace ts {
                 }
                 // Handle export default expressions
                 if (declaration.kind === SyntaxKind.ExportAssignment) {
-                    return links.type = checkExpression((<ExportAssignment>declaration).expression);
+                    return links.type = checkExpression((<ExportAssignment>declaration).expression, checkMode);
```
Comment (rbuckton) [inline src/compiler/checker.ts]: It doesn't seem like we should be holding on to the type here if this is not a normal check mode.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -13117,12 +13117,24 @@ namespace ts {
...
-        function getApparentTypeOfContextualType(node: Expression): Type {
-            const type = getContextualType(node);
+        function getApparentTypeOfContextualType(node: Expression, checkMode?: CheckMode): Type {
+            const type = getContextualType(node, checkMode);
             return type && getApparentType(type);
         }
 
         /**
+         * This must be called when a contextual type function is attempting to dig into a type to contextually type a subexpression
+         * Otherwise, contextual typing stops when a type argument is encountered, and `any` is ued instead.
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Nit: used

File: src/compiler/checker.ts (hunk 3 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts]: Will this ever be anything apart from normal?

Comment (weswigham) [reply src/compiler/checker.ts]: Inferential. The reason its even being threaded through here is to catch when it is set to inferential.

**Comment by DanielRosenwasser** [comment]
Do you happen to know if this fixes #16136?

**Comment by DanielRosenwasser** [comment]
Can you add the following simple test case since, as you mentioned, this isn't necessarily tied to optionality?

```ts
interface Bar {
    bar: (a: number) => void;
}

declare function foo<T extends Bar>(x: string | T): T

let x = foo({
    bar(x) {
    }
})
```

**Comment by weswigham** [comment]
@DanielRosenwasser Synced with master and updated tests. Also I've checked; this does not fix #16136 (though it may not be possible to fix that without this change done in conjunction with it).

**Comment by weswigham** [comment]
I've modified the solution to work for array literals in addition to object literals. Also theoretically JSX, but JSX apparently never does an inferential pass because it's "overload resolution" is not real overload resolution (but I've included a test showcasing the issue).

**Comment by ahejlsberg** [comment]
I'm concerned with the cost of instantiating contextual types. We don't cache contextual types, yet obtaining a contextual type is assumed to be cheap and we do it at will in a number of places. Furthermore, *if* we're going to instantiate contextual types, it seems like we should always do it and not just when obtaining a member of a contextual object type. Indeed, with the approach in this PR I think we potentially end up instantiating types that were already instantiated (e.g. if we have nested object literals).

**Comment by ahejlsberg** [comment]
I should add also that instantiation of contextual types is deferred by design such that we don't prematurely "pull" on type parameters for which we are currently performing inference. For example, when assigning contextual types to function expression or arrow function arguments, we *do* instantiate the contextual type, but only once we have drilled down to the corresponding part of the contextual type. Thus, we only fix type parameters if they are actually referenced in the (part of the) contextual type for the function.

**Comment by weswigham** [comment]
@ahejlsberg Implemented the waaaaay simpler fix we looked at today; which interestingly, still doesn't fix the JSX case.
