### PR TITLE
switch FileExtensionInfo to always mean .js file and deduplicate entries in getSupportedExtensions

### LINKED ISSUE #13950: VS 2017 compiles TS unexpectedly
I am running VS 2017, the Feb 7th update.

The IDE/Typescript insists on compiling and saving a `main.js` (when I open the solution, every time I change a file, e.g. when I delete `main.js` it instantly re-appears -- I have `allowJs: true`).

I can't figure out why it does or how to disable it.

I do have a `tsconfig.json`. I tried explicitely adding `compileOnSave: false`. Still compiles.
I couldn't find something relevant in the VS options.

I do not want VS to compile my code because I have a custom gulp build that does so.

### PR DESCRIPTION
**Pull request by vladima**
fixes #13950 

// @mhegazy this is alternative fix proposal, which one do you prefer?

### CODE REVIEW

File: src/server/protocol.ts [hunk 1]
```diff
@@ -1003,7 +1003,7 @@ namespace ts.server.protocol {
         /**
          * The host's additional supported file extensions
```
Comment (mhegazy) [inline src/server/protocol.ts]: should update the comment here to reflect that it is js only.
