### PR TITLE
module.exports aliases have correct flags

### LINKED ISSUE #27857: Code completion crashes when localStorage, postcss-object-fit-images, or gulp-watch packages are imported
**TypeScript Version:**  3.2.0-dev.20181011
**TypeScript Version:**  3.1.3

**Search Terms:** code completion, auto import, intellisense

**Code**
You can check out this repo to reproduce the issue: [repo link](https://github.com/zfeher/ts-import-suggestion-bug)
If any of the following dependencies are imported in the project the code completion feature crashes: `localStorage`, `postcss-object-fit-images` or `gulp-watch`. Without them the feature works just fine. 

**Expected behavior:** code completion works when the mentioned dependencies are imported

**Actual behavior:** code completion crashes if any of the following dependencies are imported in the project: `localStorage`, `postcss-object-fit-images` or `gulp-watch`

**Related Issues:**  #27640

### PR DESCRIPTION
**Pull request by sandersn**
They are marked both as (1) alias and (2) assignment declaration. This fixes alias resolution in cases where multiple module.exports assignments exist, but differ in whether they are aliases or not:

```js
function f() { }
module.exports = f
module.exports = 23
```

Previously, this construct would fail to resolve the alias `f` because the `export=` symbol would be marked as Alias | Value but not Assignment. This change just adds Assignment so that the assignment declaration alias-following rules apply: you should always follow the alias, regardless of other flags.

Also, isAliasSymbolDeclaration needed to be tightened up. Previously, I missed the condition that `module.exports =` aliases required an EntityNameDeclaration on right-hand-side, just like `export default` and `export =` aliases.

Fixes #27857

### CODE REVIEW

File: tests/cases/fourslash/importFixWithConditional.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
+/// <reference path="fourslash.ts" />
```
Comment (andy-ms) [inline tests/cases/fourslash/importFixWithConditional.ts]: File is misnamed as there's no conditional any more.

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -2416,7 +2416,7 @@ namespace ts {
 
             // 'module.exports = expr' assignment
             const flags = exportAssignmentIsAlias(node)
-                ? SymbolFlags.Alias // An export= with an EntityNameExpression or a ClassExpression exports all meanings of that identifier or class
+                ? SymbolFlags.Alias | SymbolFlags.Assignment // An export= with an EntityNameExpression or a ClassExpression exports all meanings of that identifier or class
```
Comment (andy-ms) [inline src/compiler/binder.ts]: So why is it not flagged as Assignment in the other case?

Comment (sandersn) [reply src/compiler/binder.ts]: No good reason! The other uses of Assignment are unconditional now as well. Nice catch.
