### PR TITLE
Use watch recursive directories instead of watchFile for node_modules and bower components

### LINKED ISSUE #23390: Constant cpu usage on windows caused by electron_node typingsInstaller.js tsserver.js typesMap.js
_From @zfeher on April 12, 2018 11:55_

- VSCode Version: 1.22.1
- OS Version: Windows 10 1709 16299.371

Steps to Reproduce:

This happens when I am opening our repo. I need to wait a while max 1-2 minutes and the process will be there and it will cause 10-17% constant cpu usage. My telemetry settings are turned off completely.

Opening an empty code instance doesn't produce this behavior.

The exported status: [vscode-status.txt](https://github.com/Microsoft/vscode/files/1902951/vscode-status.txt)

The command line of the process:
```
"C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/zfeher/AppData/Local/Microsoft/TypeScript/2.8 --enableTelemetry --typesMapLocation "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js/../typesMap.json" 
```

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#47735_

### PR DESCRIPTION
**Pull request by sheetalkamat**
This will help in reducing polling watches. 
Fixes #23390

### CODE REVIEW

File: src/server/typingsInstaller/typingsInstaller.ts [hunk 1]
```diff
@@ -367,51 +378,117 @@ namespace ts.server.typingsInstaller {
...
+
+                // path in global cache, watch global cache
+                if (containsPath(this.globalCachePath, filePath, projectRootPath, !this.installTypingHost.useCaseSensitiveFileNames)) {
+                    createProjectWatcher(this.globalCachePath, createProjectDirectoryWatcher);
+                    continue;
+                }
+
+                // Get path without node_modules and bower_components
+                let pathToWatch = getDirectoryPath(filePath);
+                while (isInNodeModulesOrBowerComponents(pathToWatch)) {
```
Comment (mhegazy) [inline src/server/typingsInstaller/typingsInstaller.ts]: `indexof("/node_modules/")`? we also have a function similar to that in `getNodeModulePathParts`

File: src/server/typingsInstaller/typingsInstaller.ts [hunk 2]
```diff
@@ -367,51 +378,117 @@ namespace ts.server.typingsInstaller {
...
+                }
+                const watcher = this.installTypingHost.watchDirectory(dir, f => {
+                    if (isLoggingEnabled) {
+                        this.log.writeLine(`DirectoryWatcher:: Triggered with ${f} :: WatchInfo: ${dir} recursive :: handler is already invoked '${watchers.isInvoked}'`);
+                    }
+                    if (watchers.isInvoked) {
+                        return;
+                    }
+                    f = this.toCanonicalFileName(f);
+                    if (isPackageOrBowerJson(f) && f !== this.toCanonicalFileName(combinePaths(this.globalCachePath, "package.json"))) {
```
Comment (mhegazy) [inline src/server/typingsInstaller/typingsInstaller.ts]: the globalCache path is not going to change, we can cache that.

File: src/server/typingsInstaller/typingsInstaller.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/server/typingsInstaller/typingsInstaller.ts]: i will inline ```isInNodeModulesOrBowerComponents``` which uses stringContains which is  ```str.indexOf(substring) !== -1;```

**Comment by sheetalkamat** [comment]
@amcasey can you please take a look. This helps in reducing 1200 odd files to single directory watcher for #23390

**Comment by sheetalkamat** [comment]
@mhegazy fixed all the comments.

**Comment by amcasey** [comment]
I'm looking, but you really want @RyanCavanaugh for the TI.

File: src/server/typingsInstaller/typingsInstaller.ts [hunk 3]
```diff
@@ -64,6 +64,20 @@ namespace ts.server.typingsInstaller {
         onRequestCompleted: RequestCompletedAction;
     }
 
+    function isPackageOrBowerJson(fileName: string) {
+        const base = getBaseFileName(fileName);
+        return base === "package.json" || base === "bower.json";
+    }
+
+    function getDirectoryExcludingNodeModulesOrBowerComponents(f: string) {
+        const indexOfNodeModules = f.indexOf("/node_modules/");
```
Comment (amcasey) [inline src/server/typingsInstaller/typingsInstaller.ts]: Don't we have helpers for this?  E.g. `commonPackageFolders` in core.ts.

File: src/server/typingsInstaller/typingsInstaller.ts [hunk 4]
```diff
@@ -64,6 +64,20 @@ namespace ts.server.typingsInstaller {
         onRequestCompleted: RequestCompletedAction;
     }
 
+    function isPackageOrBowerJson(fileName: string) {
+        const base = getBaseFileName(fileName);
+        return base === "package.json" || base === "bower.json";
```
Comment (amcasey) [inline src/server/typingsInstaller/typingsInstaller.ts]: Should this take a flag for case sensitivity?

File: src/server/typingsInstaller/typingsInstaller.ts [hunk 5]
```diff
@@ -367,51 +385,112 @@ namespace ts.server.typingsInstaller {
...
-                    onDeleteValue: closeFileWatcher
+            const createProjectWatcher = (path: string, createWatch: (path: string) => FileWatcher) => {
+                toRemove.delete(path);
+                if (watchers.has(path)) {
+                    return;
+                }
+
+                watchers.set(path, createWatch(path));
+            };
+            const createProjectFileWatcher = (file: string): FileWatcher => {
```
Comment (amcasey) [inline src/server/typingsInstaller/typingsInstaller.ts]: Is there a reason to prefer lambdas over functions or vice versa?

File: src/server/typingsInstaller/typingsInstaller.ts [hunk 6]
```diff
@@ -367,51 +385,112 @@ namespace ts.server.typingsInstaller {
...
                 watchers = createMap();
                 this.projectWatchers.set(projectName, watchers);
             }
+            else {
+                copyEntries(watchers, toRemove);
+            }
 
-            watchers.isInvoked = false;
             // handler should be invoked once for the entire set of files since it will trigger full rediscovery of typings
+            watchers.isInvoked = false;
```
Comment (amcasey) [inline src/server/typingsInstaller/typingsInstaller.ts]: This is probably a dumb question, but isn't `watchers` a map?  Why would it have an `isInvoked` property?

File: src/server/typingsInstaller/typingsInstaller.ts (hunk 4 above)
Comment (sheetalkamat) [reply src/server/typingsInstaller/typingsInstaller.ts]: the file here is always canonical file name

File: src/server/typingsInstaller/typingsInstaller.ts (hunk 5 above)
Comment (sheetalkamat) [reply src/server/typingsInstaller/typingsInstaller.ts]: lambdas are needed because we use ```this```

File: src/server/typingsInstaller/typingsInstaller.ts (hunk 6 above)
Comment (sheetalkamat) [reply src/server/typingsInstaller/typingsInstaller.ts]: its a expando on map.. This is so that we arent catching incorrect local variable. the state recides on the map (more on this https://github.com/Microsoft/TypeScript/pull/23438#discussion_r182237104)

File: src/server/typingsInstaller/typingsInstaller.ts (hunk 3 above)
Comment (sheetalkamat) [reply src/server/typingsInstaller/typingsInstaller.ts]: But TI uses only these two locations.

**Comment by sheetalkamat** [comment]
@RyanCavanaugh can you take a look.
