### PR TITLE
Do not incorrectly add line separators for non-synthetic nodes when emitting node list

### LINKED ISSUE #44068: Printer incorrectly adding line break when emitting node list with non-synthesized nodes as of TS 4.3
# Bug Report

### 🔎 Search Terms

printer, line break, ts 4.3, beta, for non-synthesized nodes, line separator, new line.

### 🕗 Version & Regression Information

Started as of v4.3-dev.

### ⏯ Playground Link

Specific to the compiler API; not reproduce in the playground.

### 💻 Code

Reproduction repository: https://github.com/devversion/ts-4.3-emitter-node-list-line-breaks

Consider an input file as the followed:

```ts
const FirstSymbol = Symbol();
const SecondSymbol = Symbol();
```

Assume we have the AST for this source file and have access to these variables. i.e. `firstVarNode` and `secondVarNode`. If we construct a new array literal containing the names of these variables and print the array literal, the array literal will be multi-line.

```ts
const arrayLiteral = ts.createArrayLiteral([
    firstVarNode.name,
    secondVarNode.name
]);

console.log(printer.printNode(ts.EmitHint.Unspecified, arrayLiteral, testFile));
```

the output will be:

```ts
[FirstSymbol,
    SecondSymbol]
```

while I'd expect it to be `[FirstSymbol, SecondSymbol]` unless I specify `multiLine = true` for the array literal expression.

### Additional information

This seems to have changed with https://github.com/microsoft/TypeScript/commit/3c32f6e154ead6749b76ec9c19cbfdd2acad97d6. The printer now checks if the non-synthesized nodes are on the same line, even if they do not have the same parent.

### PR DESCRIPTION
**Pull request by devversion**
As of 3c32f6e, a line separator is added between nodes if the nodes are
not synthetic and on separate lines. This is wrong and previously only
happened if the non-synthetic nodes were on different lines but had the same parent.

Fixes #44068.

### CODE REVIEW

File: tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNotUsingIdentifier.js [hunk 1]
```diff
@@ -35,7 +35,8 @@ var y = {
     "typeof": 
 };
 var x = (_a = {
-        a: a, : .b,
+        a: a,
+        : .b,
```
Comment (devversion) [inline tests/baselines/reference/objectLiteralShorthandPropertiesErrorFromNotUsingIdentifier.js:39]: It looks like these baseline changes are due to us no longer checking if previous and next nodes (when emitting the node list) are on the same line if either one does not have a parent set. We only check if nodes are on the same line if they have the same parent container. 

It looks like the logic for checking if there is a parent set has been introduced as part of the following refactoring (not sure if this was intentional; or if it's reasonable to continue doing that). https://github.com/Microsoft/TypeScript/commit/68b0323b72bf51236d8cd181ed94ba9a63f933fd.

File: src/compiler/emitter.ts [hunk 2]
```diff
@@ -4564,15 +4564,15 @@ namespace ts {
...
-                    return getEffectiveLines(
-                        includeComments => getLinesBetweenRangeEndAndRangeStart(
-                            previousNode,
-                            nextNode,
-                            currentSourceFile!,
-                            includeComments));
-                }
-                else if (!preserveSourceNewlines && !nodeIsSynthesized(previousNode) && !nodeIsSynthesized(nextNode)) {
+                else if (siblingNodePositionsAreComparable(previousNode, nextNode)) {
+                    if (preserveSourceNewlines) {
```
Comment (andrewbranch) [inline src/compiler/emitter.ts:4568]: To avoid incurring a performance penalty during normal program emit (i.e., via `tsc`), `siblingNodePositionsAreComparable` must not be called unless `preserveSourceNewlines` is true (which only happens in the language service for determining changes for codefixes and refactors).

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot perf test this — I know I made this code path cheaper than it used to be, but I think we still want to avoid it during regular emit.

**Comment by andrewbranch** [comment]
Hm, that actually seems ok.

**Comment by devversion** [comment]
@andrewbranch Thanks for reviewing. I've updated the logic to never call `siblingNodePositionsAreComparable` when `preserveSourceNewlines` is set to `false`. I've refactored the check slightly so that the intended behavior is more obvious. We still need the check to `getOriginalNode` but that shouldn't have a large impact on performance, but is needed for correctness.

Also I've explicitly added the fallback case for `PreferNewLine` instead of it magically being respected through the `synthesizedNodeStartsOnNewLine` else clause (which returns `true` even if the nodes are _not_ synthesized).

**Review by andrewbranch — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@rbuckton can you take a quick look?

@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
Here's what I'm thinking after chatting a bit with @andrewbranch: emit changes are hard a little bit risky. I think it's probably okay to bring this into our `master` branch, and create a cherry-pick into `release-4.3`. If we feel like this works well with nightlies for a while, we can publish a patch for 4.3. Does that sound reasonable?

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.3

**Review by rbuckton — APPROVED** [review]

**Comment by sandersn** [comment]
@DanielRosenwasser this is ready to go, right? From reading your comment, it sounds like we want to get this into the nightlies as soon as possible in order to decide whether to publish a 4.3 patch.

**Comment by devversion** [comment]
@DanielRosenwasser @sandersn Is there any update on this change? It would be great to see this change in the nightly builds, given it being a change that could be considered a regression (at least in perspective of the printer as it preserves non-existent lines between list items).

**Comment by andrewbranch** [comment]
Let’s do it 👍
