### PR TITLE
Fix for issue #32528: Prevent meta property from appearing twice

### LINKED ISSUE #32528: Bad completions for `import.meta`
```ts
let x = import.meta./**/
```

1. Go to `/**/` with an empty definition of the global `ImportMeta` type.
1. Request completions

**Expected**

No completion entry for `meta`

**Actual**

Completion entry for a bogus `meta` property.

### PR DESCRIPTION
**Pull request by sheonhan**
Fixes #32528

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Does this work when the ImportMeta interface has properties defined?

@typescript-bot pack this

Also, you may want to update your email information in git or GitHub since your commits don't seem to be associated with your account.

**Comment by sheonhan** [comment]
> Does this work when the ImportMeta interface has properties defined?

Hmm, I tried the case below, and it doesn't seem like it does. 
```
// @Filename: c.ts
////declare global {
////  interface ImportMeta {
////    url: string;
////  }
////}
////import.meta.u/*3*/
```

When I run the test in debugging mode, the parent of `import.meta` is a node of type `PropertyAccessExpression` (with `MetaProperty`, `DotToken`, and `Identifier` as its children) and `import.meta` itself is never of type `ImportMeta`.

Screenshot_2019-12-27 06 23 42_TYEtyv

Maybe I should be looking at the parser so that it could parse the `import.meta` token as `ImportMeta` (the same goes for `new.target`), but let me know.

(Thanks for pointing that out about GitHub. I was working from another machine and my `.gitconfig` was empty.)

**Comment by sheonhan** [comment]
I realized that I was still using the globally installed version, and I correctly changed `typescript.tsdk` to the one packed above. Following your example in [this issue](https://github.com/microsoft/TypeScript/pull/23327#issue-180757300), the current behavior is like this: 
```typescript
declare global  {
    interface ImportMeta {
        url: string;
        idx: number;
    }
}

import.meta.url // Has type "string"
import.meta.idx // Has type "number"
import.meta. // Doesn't show "meta"
```

File: src/services/completions.ts [hunk 1]
```diff
@@ -910,6 +910,9 @@ namespace ts.Completions {
                     case SyntaxKind.PropertyAccessExpression:
                         propertyAccessToConvert = parent as PropertyAccessExpression;
                         node = propertyAccessToConvert.expression;
+                        if (isMetaProperty(node)) {
```
Comment (sheetalkamat) [inline src/services/completions.ts]: This is incorrect change since this will return `undefined` for scenario that @DanielRosenwasser pointed out.. (that is when ImportMeta interface has some properties defined.)

Comment (sheonhan) [reply src/services/completions.ts]: ah I see. I changed it so that it would correctly handle cases where ImportMeta has properties defined and added a test case.

**Comment by sheonhan** [comment]
I see that linter is failing but just by looking at the error message (which points to `checker.ts`), I'm not sure what the issue is...

**Comment by sheonhan** [comment]
Never mind. Simply merging with master solved the issue.

File: src/services/completions.ts [hunk 2]
```diff
@@ -1144,9 +1144,13 @@ namespace ts.Completions {
             }
 
             if (isMetaProperty(node) && (node.keywordToken === SyntaxKind.NewKeyword || node.keywordToken === SyntaxKind.ImportKeyword)) {
-                const completion = (node.keywordToken === SyntaxKind.NewKeyword) ? "target" : "meta";
-                symbols.push(typeChecker.createSymbol(SymbolFlags.Property, escapeLeadingUnderscores(completion)));
-                return;
+                const metaPropertyAccessIdentifier = node.name.text;
+                // Check whether this MetaProperty node already had its metadata accessed
+                if (metaPropertyAccessIdentifier !== "target" && metaPropertyAccessIdentifier !== "meta") {
```
Comment (sheetalkamat) [inline src/services/completions.ts]: Again this is incorrect since even if you have code like: ```import./*completionhere*/meta``` should have meta as completion.

File: tests/cases/fourslash/completionImportMeta.ts [hunk 3]
```diff
@@ -1,5 +1,24 @@
 /// <reference path='fourslash.ts' />
 
-////import./**/
+// @Filename: a.ts
+////import./*1*/
 
-verify.completions({ marker: "", exact: "meta" });
+// @Filename: b.ts
```
Comment (sheetalkamat) [inline tests/cases/fourslash/completionImportMeta.ts]: As part of this PR I would like you to add another test case file where global doesn't have meta and you look for completions at `import.`, `import.meta.` and `import./*here*/meta` in both these test case files (the one currently here and one without global import meta declaration)

**Comment by sheonhan** [comment]
@typescript-bot pack this

File: src/services/completions.ts (hunk 2 above)
Comment (sheonhan) [reply src/services/completions.ts]: I changed it so that the conditional checks whether `MetaProperty`'s `dotToken` is the same one as the `dotToken` bound to `contextToken` variable.

Comment (sheonhan) [reply src/services/completions.ts]: I was trying to find a utility function to access `dotToken` but couldn't find any, so I used `getChildAt(1)` instead. But I assume this isn't ideal (It looks like that `getChildAt` function was never used with anything other than `0` as its argument.)

File: tests/cases/fourslash/completionImportMeta.ts (hunk 3 above)
Comment (sheonhan) [reply tests/cases/fourslash/completionImportMeta.ts]: Let me know if the most recent change is what you requested!

File: src/services/completions.ts [hunk 4]
```diff
@@ -1144,9 +1144,14 @@ namespace ts.Completions {
             }
 
             if (isMetaProperty(node) && (node.keywordToken === SyntaxKind.NewKeyword || node.keywordToken === SyntaxKind.ImportKeyword)) {
-                const completion = (node.keywordToken === SyntaxKind.NewKeyword) ? "target" : "meta";
-                symbols.push(typeChecker.createSymbol(SymbolFlags.Property, escapeLeadingUnderscores(completion)));
-                return;
+                const metaPropertyAccessIdentifier = node.name.text;
+                const dotToken = node.getChildAt(1);
+                // Check whether this MetaProperty node already had its metadata accessed
+                if (dotToken === contextToken || metaPropertyAccessIdentifier !== "target" && metaPropertyAccessIdentifier !== "meta") {
```
Comment (sheetalkamat) [inline src/services/completions.ts]: I don't think you need any of the text validation.. 
Just adding `contextToken === contextToken` should be sufficient. Also please include this by changing outer if statement as:
```ts
            if (isMetaProperty(node) &&
                (node.keywordToken === SyntaxKind.NewKeyword || node.keywordToken === SyntaxKind.ImportKeyword) &&
                contextToken === node.getChildAt(1)) {
```




```

File: src/services/completions.ts [hunk 5]
```diff
@@ -1143,10 +1143,10 @@ namespace ts.Completions {
                 }
             }
 
-            if (isMetaProperty(node) && (node.keywordToken === SyntaxKind.NewKeyword || node.keywordToken === SyntaxKind.ImportKeyword)) {
-                const completion = (node.keywordToken === SyntaxKind.NewKeyword) ? "target" : "meta";
-                symbols.push(typeChecker.createSymbol(SymbolFlags.Property, escapeLeadingUnderscores(completion)));
-                return;
+            if (isMetaProperty(node) && (node.keywordToken === SyntaxKind.NewKeyword || node.keywordToken === SyntaxKind.ImportKeyword) && contextToken === node.getChildAt(1)) {
+                    const completion = (node.keywordToken === SyntaxKind.NewKeyword) ? "target" : "meta";
```
Comment (sheetalkamat) [inline src/services/completions.ts]: Please correct the formatting. That should make it good to go.

Comment (sheonhan) [reply src/services/completions.ts]: Done! Thanks for reviewing this :)
