### PR TITLE
Correctly recognize value symbol presence of expressions in extends clauses

### LINKED ISSUE #5028: Variable in "extends" clause ignored by services
In the following code:
```
var base = class {};
class C extends base {}
```
services does not recognize that the `base` identifier in the second line refers to the variable declared in the first. Rename, find occurrences, etc do not work on it.

The same problem also occurs with JSX spread attributes in .tsx code:
```
var props = {};
var div = <div {...props}/>;
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #5028.

Basically we were failing to account for the fact that expressions in `extends` clauses are *expressions*...

*Edit*: But only in *class* extends clauses.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14054,7 +14054,10 @@ namespace ts {
             }
 
             if (isHeritageClauseElementIdentifier(<EntityName>entityName)) {
-                let meaning = entityName.parent.kind === SyntaxKind.ExpressionWithTypeArguments ? SymbolFlags.Type : SymbolFlags.Namespace;
+                let meaning = entityName.parent.kind === SyntaxKind.ExpressionWithTypeArguments ?
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: You should only add the `Value` flag if this is a heritage clause of a `class` expression (see other comment)

File: tests/baselines/reference/reboundBaseClassSymbol.symbols [hunk 2]
```diff
@@ -11,6 +11,6 @@ module Foo {
 
     interface B extends A { b: string; } 
 >B : Symbol(B, Decl(reboundBaseClassSymbol.ts, 2, 14))
->A : Symbol(A, Decl(reboundBaseClassSymbol.ts, 0, 0))
+>A : Symbol(A, Decl(reboundBaseClassSymbol.ts, 2, 7))
```
Comment (RyanCavanaugh) [inline tests/baselines/reference/reboundBaseClassSymbol.symbols]: This baseline change is incorrect -- `A` points to the type `A` at `0, 0` not the value `A` at `2, 7`. Should add a Fourslash test for this probably.

**Comment by DanielRosenwasser** [comment]
Addressed your feedback @RyanCavanaugh

**Comment by mhegazy** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
:+1:
