### PR TITLE
fix(25155): insertSpaceBeforeTypeAnnotation doesn't work with optional parameters / properties

### LINKED ISSUE #25155: insertSpaceBeforeTypeAnnotation doesn't work with optional parameters / properties
This is a follow up to #19493

**TypeScript Version:**  2.9.2

**Search Terms:** insertSpaceBeforeTypeAnnotation formatter

**Code**

```ts
function RGBtoHSB(param1 : Int, param2?: Int, param3?: Int)
{
}

interface SquareConfig
{
    color : string;
    width?: number;
}
```

**Expected behavior:**

With insertSpaceBeforeTypeAnnotation=true, I'd expect this to be formatted as:

```ts
function RGBtoHSB(param1 : Int, param2 ?: Int, param3 ?: Int)
{
}

interface SquareConfig
{
    color : string;
    width ?: number;
}
```
_Note the whitespace (` `) before the questionmark (`?`)_

**Actual behavior:**

But it gets formatted as:
```ts
function RGBtoHSB(param1 : Int, param2?: Int, param3?: Int)
{
}

interface SquareConfig
{
    color : string;
    width?: number;
}
```

**Playground Link:** http://www.typescriptlang.org/play/#src=function%20RGBtoHSB(param1%20%3A%20Int%2C%20param2%3F%3A%20Int%2C%20param3%3F%3A%20Int)%0D%0A{%0D%0A}%0D%0A%0D%0Ainterface%20SquareConfig%0D%0A{%0D%0A%20color%20%3A%20string%3B%0D%0A%20width%3F%3A%20number%3B%0D%0A}

**Related Issues:** #19493 #20466

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #25155

### CODE REVIEW

File: tests/cases/fourslash/formatTypeAnnotation1.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+////    y?: number;
+////}
+
+format.setOption("insertSpaceBeforeTypeAnnotation", true);
+format.document();
+verify.currentFileContentIs(
+`function foo(x : number, y ?: string) : number { }
+interface Foo {
+    x : number;
+    y ?: number;
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/formatTypeAnnotation1.ts:15]: Wait, really?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser ?

File: tests/cases/fourslash/formatTypeAnnotation1.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/formatTypeAnnotation1.ts:15]: https://github.com/microsoft/TypeScript/blob/d45f0d0c9fb933d49a01d41eaa465940cfd78be0/src/services/formatting/rules.ts#L318

https://github.com/microsoft/TypeScript/blob/d45f0d0c9fb933d49a01d41eaa465940cfd78be0/src/services/formatting/rules.ts#L492-L498

`y ?: number; <- SyntaxKind.PropertySignature`

Comment (a-tarasyuk) [reply tests/cases/fourslash/formatTypeAnnotation1.ts:15]: What do you mean? :confused:

Comment (a-tarasyuk) [reply tests/cases/fourslash/formatTypeAnnotation1.ts:15]: @DanielRosenwasser  What do you mean? 😕

File: tests/cases/fourslash/formatTypeAnnotation2.ts [hunk 2]
```diff
@@ -0,0 +1,17 @@
+/// <reference path='fourslash.ts' />
+
+////function foo(x : number, y ?: string) : number {}
+////interface Foo {
+////    x : number;
+////    y ?: number;
+////}
+
+//format.setOption("insertSpaceBeforeTypeAnnotation", false);
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/formatTypeAnnotation2.ts:9]: Do you want to remove this comment?

File: tests/cases/fourslash/formatTypeAnnotation1.ts (hunk 1 above)
Comment (DanielRosenwasser) [reply tests/cases/fourslash/formatTypeAnnotation1.ts:15]: It's a little weird... I guess I don't consider the `?` to be part of the type annotation, so I'm surprised that a person would have to turn off `NoSpaceBeforeQuestionMark` to avoid this behavior?

Comment (a-tarasyuk) [reply tests/cases/fourslash/formatTypeAnnotation1.ts:15]: @DanielRosenwasser Not sure that I correctly understood your concern. `NoSpaceBeforeQuestionMark` doesn't use any option to enable/disable it, this rule applies by default

The issue that `?` token can be used to define optional parameter/property,
```ts
function foo(x ?: number) {}
```
So `NoSpaceBeforeQuestionMark` conflicts with the `SpaceBeforeTypeAnnotation`/`NoSpaceBeforeTypeAnnotation`, therefore need to exclude checking type annotations context in `NoSpaceBeforeQuestionMark`. 

If the `insertSpaceBeforeTypeAnnotation` is not enabled then `NoSpaceBeforeTypeAnnotation` will be applied because this rule uses `isOptionDisabledOrUndefined`, which means that the user can set` false` or delete this rule, and in both cases, the spaces will be removed.

If a user enables the option `insertSpaceBeforeTypeAnnotation`, formatted will add space before `" :"` and `" ?:"` as _ColonToken_ and _ColonToken_ + _QuestionToken_ are valid tokens in type annotations.

Or #25155 is not a bug, and if a user the enables option `insertSpaceBeforeTypeAnnotation`, formatted has to add space only before `:` and ignore `?:`.

What do you think?

File: tests/cases/fourslash/formatTypeAnnotation2.ts (hunk 2 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/formatTypeAnnotation2.ts]: Yep, it is useless.

File: tests/cases/fourslash/formatTypeAnnotation1.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/formatTypeAnnotation1.ts:15]: @DanielRosenwasser What do you think, can we close the #25155 without fix?
