### PR TITLE
Handle case clause corner cases in extract symbol

### LINKED ISSUE #20559: Debug Failure. False expression. in `collectEnclosingScopes` during `getApplicableRefactors `
tsserver version: 2.6.1
hits: at least 773561
stack:
```
Error: Debug Failure. False expression.
    at Object.first (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1898:15)
    at collectEnclosingScopes (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:77840:65)
    at getPossibleExtractionsWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:77922:30)
    at getPossibleExtractions (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:77881:26)
    at Object.getAvailableActions (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:77514:35)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:75017:128
    at Object.flatMapIter (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1570:23)
    at Object.getApplicableRefactors (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:75016:23)
    at Object.getApplicableRefactors (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:80232:32)
    at IOSession.Session.getApplicableRefactors (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:86474:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:85436:61)
    at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:86660:28)
    at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:86669:33)
    at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:86689:35)
    at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by amcasey**
There's a utility method, `isBlockLike`, used to determine whether a node has a list of statements.  Unfortunately, the callers of that method assumed that all children were in the list of statements.  The expression of a `CaseClause` is not.

Fixes #20559

### CODE REVIEW

**Comment by amcasey** [comment]
@mhegazy Should this go in 2.7?

File: src/services/refactors/extractSymbol.ts [hunk 1]
```diff
@@ -235,6 +235,17 @@ namespace ts.refactor.extractSymbol {
...
                 }
             }
+
+            if (!statements.length) {
+                // https://github.com/Microsoft/TypeScript/issues/20559
+                // Ranges like [|case 1: break;|] will fail to populate `statements` because
+                // they will never find `start` in `start.parent.statements`.
+                // Consider: We could support ranges like [|case 1:|] by refining them to just
+                // the expression.
+                Debug.assert(isCaseClause(start.parent) && span.start < start.parent.expression.end);
```
Comment (amcasey) [inline src/services/refactors/extractSymbol.ts]: This assert is incorrect.  There are other ways this can arise.  I'm still trying to determine if a sensible assert is possible.  If not, deleting it should suffice - the only downside of returning early is not being able to extract a range.

Comment (amcasey) [reply src/services/refactors/extractSymbol.ts]: It looks like it can happen with any non-statement child of a block-like node (e.g. the lbrace in a block).  I'll just remove the assert.
