### PR TITLE
Fix crash in transformations

### LINKED ISSUE #33744: Optional chaining, CallChain error
**TypeScript Version:**  3.7.0-beta

**Search Terms:**
Optional chaining, CallChain

**Code**

```ts
function find<T>(fun: (_: T) => boolean) {
  return (arr: T[]) => arr.find(fun)
}

type Item = {
  label: string
  id: number
}

const items: Item[] = [
  { label: 'one', id: 1 },
  { label: 'two', id: 2
]

const upperCasedlabel = items.find(i => i.id === 1)?.label.toUpperCase() // ONE ✅

// despite the fact that I don't have any ts warning/error, the expression below fails at runtime.
// 👇 does not work, getting this error -> Debug Failure. False expression: Cannot update a CallChain using updateCall. Use updateCallChain instead.
const altUpperCasedlabel = find<Item>(i => i.id === 1)(items)?.label.toUpperCase() ❌

// When I break this into two steps, it works
const maybeItem = find<Item>(i => i.id === 1)(items)
const altUpperCasedlabel = maybeItem?.label.toUpperCase() // ONE ✅

// This also works
const altLabel = find<Item>(i => i.id === 1)(items)?.label // one ✅
```

**Expected behavior:**
I'm expecting the first expression `altLabel` to work, without the need to break the process into two steps

**Actual behavior:**

Getting an error, `Debug Failure. False expression: Cannot update a CallChain using updateCall. Use updateCallChain instead.`

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
Relaxing the assertions on `updateCall`/`updatePropertyAccess`/`updateElementAccess` when used with a `CallChain`/`PropertyAccessChain`/`ElementAccessChain` to fix a crash in the TS transform and to improve backwards/forwards compatibility with external consumers of the API.

If you call any of the three mentioned `updateX` functions on an `XChain` node, the corresponding `updateXChain` function is called instead with the current value of `node.questionDotToken` passed as the `questionDotToken` argument.

Fixes #33744

### CODE REVIEW

File: src/compiler/factory.ts [hunk 1]
```diff
@@ -1065,7 +1065,9 @@ namespace ts {
     }
 
     export function updatePropertyAccess(node: PropertyAccessExpression, expression: Expression, name: Identifier) {
-        Debug.assert(!(node.flags & NodeFlags.OptionalChain), "Cannot update a PropertyAccessChain using updatePropertyAccess. Use updatePropertyAccessChain instead.");
+        if (isOptionalChain(node)) {
+            return updatePropertyAccessChain(node, expression, node.questionDotToken, name);
```
Comment (weswigham) [inline src/compiler/factory.ts]: I imagine if we had a way to emit a deprecation warning, we'd do it here.

Comment (rbuckton) [reply src/compiler/factory.ts]: I'm working on that elsewhere...
