### PR TITLE
Defer types like `keyof (T & {})`

### LINKED ISSUE #49681: "cannot be used to index type" error when indexing `NonNullable` of a generic type in typescript 4.8
# Bug Report

### 🔎 Search Terms
4.8 nonnullable cannot be used to index type 

### 🕗 Version & Regression Information
4.8.0-dev.20220624
- This changed between versions 4.7.4 and 4.8-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220624#code/C4TwDgpgBAYg9nKBeKBvKBtA1hEAuKAZ2ACcBLAOwHMBdAgVwqwrgHcKoBfAWAChRIUAHL0ANqICGAI1ER4iFPKgAfKIwAmEAGaUI6vnwHQAQhJIAeACpQIAD2AQK6wsLGSZchAD5kwuBRFxaVkrLwxicmoaKAB6GIgSEjgSKH8oABYAOgAOABooFhtE5NSOLIB2A35wEwkALysbe0dnWG9fIX9A9xDLMIjKWliYgsQEpJJDGqgARXpbDq63YIhzbpX5ftJB6LjRoomgA)

### 💻 Code

```ts
type Foo = { [key: string]: unknown }
type NullableFoo = Foo | undefined

type Bar<T extends NullableFoo> = NonNullable<T>[string] //error on 4.8, no error on 4.7

type Baz<T extends Foo> = NonNullable<T>[string] // no error
type Qux = NonNullable<NullableFoo>[string] // no error
```

### 🙂 Expected behavior
no error

### PR DESCRIPTION
**Pull request by ahejlsberg**
Ordinarily, types of the form `keyof (A & B)` are normalized to `keyof A | keyof B`. However, for types like `keyof (T & {})`, this becomes `keyof T | keyof {}`, which becomes just `keyof T`, losing the fact that `undefined` and `null` have been removed from `T`. With this PR we defer the normalization for intersection types that include `{}`.

Fixes #49681.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

File: tests/cases/conformance/types/keyof/keyofAndIndexedAccess.ts [hunk 1]
```diff
@@ -31,8 +31,8 @@ type K01 = keyof string;  // "toString" | "charAt" | ...
 type K02 = keyof number;  // "toString" | "toFixed" | "toExponential" | ...
 type K03 = keyof boolean;  // "valueOf"
 type K04 = keyof void;  // never
-type K05 = keyof undefined;  // never
-type K06 = keyof null;  // never
+type K05 = keyof undefined;  // string | number | symbol
+type K06 = keyof null;  // string | number | symbol
```
Comment (Andarist) [inline tests/cases/conformance/types/keyof/keyofAndIndexedAccess.ts:35]: For me, as a user - this doesn't quite make any sense. It's super hard for me to reason about what kind of runtime behavior this is supposed to represent. I've also checked it with this PR and this creates an unsoundness and might lead to runtime errors like here:
```ts
function test<T, K extends keyof T>(t: T, k: K) {
    return t[k]; // oops, runtime error if we allow the call below
}

test(null, 'foo') // OK with this patch, error with 4.7
```

Comment (RyanCavanaugh) [reply tests/cases/conformance/types/keyof/keyofAndIndexedAccess.ts:35]: Given the new 4.8 behavior, `test` itself should have an error in its implementation due to not having a `{ }` constraint.

Comment (ahejlsberg) [reply tests/cases/conformance/types/keyof/keyofAndIndexedAccess.ts]: First experiment wasn't optimal, now deferring types like `keyof (T & {})` such that effects of removing `undefined` and `null` are properly reflected.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by Andarist** [comment]
I've noticed that this PR didn't introduce the reported issue from https://github.com/microsoft/TypeScript/issues/49681 as a test case. Is that alright? Or perhaps just an accidental omission?

File: tests/cases/conformance/types/unknown/unknownControlFlow.ts [hunk 2]
```diff
@@ -269,3 +269,35 @@ function foo<T>(x: T | null) {
         y;
     }
 }
+
+// We allow an unconstrained object of a generic type `T` to be indexed by a key of type `keyof T`
+// without a check that the object is non-undefined and non-null. This is safe because `keyof T`
+// is `never` (meaning no possible keys) for any `T` that includes `undefined` or `null`.
```
Comment (Andarist) [inline tests/cases/conformance/types/unknown/unknownControlFlow.ts:275]: Isn't this sort of an unusual thing to "defer" the error reporting to the call site? I'm not totally sure what I think about this yet but my first thought was that it's a special case in the algorithm that might be hard to explain to people.

Comment (Andarist) [reply tests/cases/conformance/types/unknown/unknownControlFlow.ts:275]: I guess this build on top of the fact that `T[never]` is always OK and `never` is always assignable to everything so perhaps this fits the existing rules just OK.

Comment (ahejlsberg) [reply tests/cases/conformance/types/unknown/unknownControlFlow.ts:275]: I added the test and the comment to capture the behavior for future reference. It's nothing new actually. We have the [same behavior in 4.7](https://www.typescriptlang.org/play?ts=4.7.4#code/GYVwdgxgLglg9mABMYBGAPAFQHwAooBcimANIgNZHkCmAnnMMQJSIDeAsAFCI+JQDa5ALoBuLgF8uXUJFgJkwAExY8hRADkE6kABsdAQwBGO6irKUKdBszZdefQaIlTOM6PCQoAzCvxFSFFRWjJpg2npGJiosHNy8AsIiPAD0yYgAogBOmXCZzpzS4O7yKAAsvmqh4QbGpjjmQfQhWro1UTgxdvGOYpySBa5ouGCtZADkwHBwY0y9KIrDo4gTUzNzwF6LeuOT07PSwKVbOjur+wNAA) with the old `NonNullable<T>` based on a conditional type. This PR ensures we carry it forward in 4.8 with `NonNullable<T>` based on `T & {}`.

Comment (Andarist) [reply tests/cases/conformance/types/unknown/unknownControlFlow.ts:275]: Sure - but I'm not thinking here from the PoV of `NonNullable` at all. My confusion/concern was solely about unconstrained generics and your changes from https://github.com/microsoft/TypeScript/pull/49119, I've assumed that given those changes this indexed access would error nowadays. Since the base constraint of unconstrained `T` is `unknown` it feels off that we can use indexed access on it without refining the type somehow first

Comment (ahejlsberg) [reply tests/cases/conformance/types/unknown/unknownControlFlow.ts:275]: It may seem surprising at first, but it is actually quite meaningful because we can permit `t[k]` _without_ requiring local proof that `t` is non-undefined and non-null. Such proof would add unnecessary overhead for instantiations where the type argument for `T` is already known not to be undefined or null.

**Review by RyanCavanaugh — APPROVED** [review]
