### PR TITLE
Defer resolution of indexed access types with reducible object types

### LINKED ISSUE #51161: Key that must exist on generic type T cannot be used to index type type T
# Bug Report

### 🔎 Search Terms

"Cannot be used to index", "generic conditional", "generic extends ternary branch"

Seems similar to #50462 and #50465 but both of those tickets have since been fixed in 4.8.1 and 4.9 respectively while my example is still broken in the playground using 4.8 or nightly (which as of writing this is v4.9.0-dev.20221013)

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCCA7RB5DwIBmcAvHAN5wR6EDSAlhgCYBccAzjFAwOYDccAbQDWrDlwzcAuqwCuGIRggB3DHAC+cAD7lK1AvSaymwAg2CN1vAFChIsBMlSYceg4wA8AFTigYwJmzoWLj4BAB8JHDevv6MgRRUoW6sQsCIhFHqVnA5cAD8UQIA5Im0DIxFknAA9NU+UFDQcACGBH5QcABuACwAdABsvd3Zuax4ncBQvEA)

### 💻 Code

```ts repro
export type AnyOneof = { oneofKind: string; [k: string]: unknown } | { oneofKind: undefined };
export type AnyOneofKind<T extends AnyOneof> = T extends { oneofKind: keyof T }
    ? T['oneofKind'] // error after v4.6.4
    : never;
```

### 🙁 Actual behavior

In TS versions greater than v4.6.4 (I've only tested versions available in the playground) the `T['oneofKind']` on line 3 is highlighted as an error: `Type '"oneofKind"' cannot be used to index type 'T'.(2536)`.

### 🙂 Expected behavior

No error on line 3 as `"oneofKind"` can in fact be used to index into type `T` since `T` must have property `"oneofKind"`.

### LINKED ISSUE #53030: Mapped type with union in value with data type accessing failing to strongly type
# Bug Report

### 🔎 Search Terms
mapped type, mapped object, unioned types 

### 🕗 Version & Regression Information

Observed issue on version 4.9.5 and sees that it also exists on Nightly
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gWAFBW1AggGkxygCFCscBhTAX00wEsQAXYAJwDMBDAY2QAUucADYB7LgBMAyszZgezMG2ToK2CV2Zd4SAFyxEwANxEcGrfrAgA1iFEB3ECYx0MjFu258ogkeIm4UMAAHqwgEgDOPkJikjJyCkoqpuqa2ob6OsAAdLjOxOZc+hGyTADmzq7urJy8AjH+JEGhoJHRfnGy8orKqClQhVmZhtkk+WZp+uAQAEbslfQYTDVe9R0SlM1hbb6x0l2JvaoFaUMGSNmU46kWfWrEUMFTkHNs1w9wz7Pz-TQLbhhmIZ2nsoABeEH+QIAH0hkiasN2-moAKBSCgAEkQBx2MAJEjJIEIQSJFAAGSoQYZc45XB-TA8UQgEpQIqY7G4-ENQngu4nW4AIgAFgwBeR+ek9DTcrRFgB6OVQSiiNjKBTCOBQBhRNHIEpscoMpksrgAEUm7Jxyi561wAG0BYUBQBdXnC0WLXVQACyXAQSBtewAjLzjjg7dZgJqmHCJA6qUgXc6APz6AAUhX0JPJlNO1MjcBoAEpwQA+KAAN1EDAksoBjOZzCgCG5kSD+l9-rxJJDELD2AVUHNWi1Ta9+vKrKiISQCjx-TtWVyzvTKEKxbLqAbEVEwhyYjKGbSRdcVUBwM7AZJACZQwuC1qQLH43nE86U+nM1A09mKWvX8A+gFsWL5aC6JZguWVY1nWRqNs2rYRNeHZ+lera3n2-SDhiUD2KIYDCKSM7AAoAxpFAzCiFAcxQKIHAUcCE4gGU+DUWATYMBxUQSEywALkuuArt+hQQeWKDbru+6iIeImnkAA)

### 💻 Code

```ts
enum Type {
    A,
    B,
    C
}

interface PayloadStructure {
    dataType: Type;
    data: unknown;
}

interface PayloadA extends PayloadStructure {
    dataType: Type.A;
    data: string;
}

interface PayloadB extends PayloadStructure {
    dataType: Type.B;
    data: number;
}

interface PayloadC extends PayloadStructure {
    dataType: Type.C;
    data: {
        x: number;
        y: number;
    };
}

type Payload = PayloadA | PayloadB | PayloadC

type MappedPayload2 = {
    //                                                                v - issue comes from selecting a type from property
    [key in Payload["dataType"]]?: (data: (Payload & {dataType: key})["data"]) => void
}

const payloads2: MappedPayload2 = {
    // [ISSUE]: I would expect data to be of type string, but it is every type from Payload's data property
    [Type.A]: (data) => {console.log(data)}
}
```

### 🙁 Actual behavior

Noting code snippet with comment prefixed with "[ISSUE]"
Using a mapped type then using the key to do an intersection with a type then getting a property, doesn't use the key to get the specific type from the property; however, if you do not get the type from a property, it does correctly type the values.

### 🙂 Expected behavior

Noting code snippet with comment prefixed with "[ISSUE]"
Using a mapped type then using the key to do an intersection with a type then getting a property, doesn't use the key to get the specific type from the property; however, if you do not get the type from a property, it does correctly type the values.

In the playground I put comments where when you are not accessing the property, it works, but when you do, it doesn't.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This reuses some of the machinery introduced in #46812 to also defer resolution of indexed access types with reducible object types. The additional issue I mention [here](https://github.com/microsoft/TypeScript/issues/53030#issuecomment-1454973382) is actually caused by #46812 _always_ deferring `keyof` for reducible types, making it impossible to explore their constraints. That's fixed in this PR by a new flag on `getIndexType` that disables deferral.

EDIT: Turns out the additional issue is a duplicate of #51161. This also means that this PR supercedes #51176.

Fixes #51161.
Fixes #53030.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
This reuses some of the machinery introduced in #46812 to also defer resolution of indexed access types with reducible object types. The additional issue I mention [here](https://github.com/microsoft/TypeScript/issues/53030#issuecomment-1454973382) is actually caused by #46812 _always_ deferring `keyof` for reducible types, making it impossible to explore their constraints. That's fixed in this PR by a new flag on `getIndexType` that disables deferral.

File: tests/cases/compiler/reducibleIndexedAccessTypes.ts [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    [K in Type]?: (data: (Payload & { dataType: K })["data"]) => void
+}
+
+const payloads2: MappedPayload2 = {
+    [Type.A]: data => { console.log(data) }
+}
+
+// Additional repro from 53030
+
+type GetPayload<P extends Payload, K extends keyof P> = P extends { dataType: K } ? P["data"] : never;
```
Comment (Andarist) [inline tests/cases/compiler/reducibleIndexedAccessTypes.ts:43]: perhaps it would still be worthwhile to include a test from #51161? that one was even more suspicious as the index access in the true branch was using the same property name as the one in the `extendsType`. This additional repro is using a different one

```suggestion
type GetPayload<P extends Payload, K extends keyof P> = P extends { dataType: K } ? P["data"] : never;

// repro from 51161

export type AnyOneof = { oneofKind: string; [k: string]: unknown } | { oneofKind: undefined };
export type AnyOneofKind<T extends AnyOneof> = T extends { oneofKind: keyof T }
    ? T['oneofKind']
    : never;

```

Comment (ahejlsberg) [reply tests/cases/compiler/reducibleIndexedAccessTypes.ts:43]: Sure, I'll add the extra test.

**Comment by seansfkelley** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Comment by seansfkelley** [comment]
Thanks! Looks like it doesn't resolve my issue, unfortunately. It looks like the same basic pattern to me -- is this expected after the fix?

```ts
const SomeRpcEndpointId = 'someRpcEndpoint' as const ;
type SomeRpcEndpointId = typeof SomeRpcEndpointId;

interface SomeRpcEndpointActions {
  doFoo: {
    in: string;
    out: number;
  };
  doBar: {
    in: boolean;
    out: boolean;
  };
}

type AllRpcEndpoints = {
  [SomeRpcEndpointId]: SomeRpcEndpointActions;
};

type InvokeRpc = <H extends keyof AllRpcEndpoints, A extends keyof AllRpcEndpoints[H]>(
  handler: H,
  action: A,
  payload: AllRpcEndpoints[H][A]['in'],
) => Promise<AllRpcEndpoints[H][A]['out']>;

declare const invokeRpc: InvokeRpc;
// Despite the compiler errors above, this does type-check correctly.
const result: boolean = await invokeRpc('someRpcEndpoint', 'doBar', true);

// Workaround inspired by https://github.com/microsoft/TypeScript/issues/53030#issuecomment-1448934975.
type GetIn<T> = T extends { in: any } ? T['in'] : never;
type GetOut<T> = T extends { out: any } ? T['out'] : never;

type InvokeRpcWorkaround = <H extends keyof AllRpcEndpoints, A extends keyof AllRpcEndpoints[H]>(
  handler: H,
  action: A,
  payload: GetIn<AllRpcEndpoints[H][A]>,
) => Promise<GetOut<AllRpcEndpoints[H][A]>>;

declare const invokeRpcWorkaround: InvokeRpcWorkaround;
// Type-checks as expected.
const resultWorkaround: boolean = await invokeRpcWorkaround('someRpcEndpoint', 'doBar', true);

export {}; // appease the compiler
```

[playground link for this PR](https://www.staging-typescript.org/play?ts=5.1.0-pr-53098-13#code/MYewdgzgLgBAyiAtgUwEoAdgFEwBN0gCWYUAkrjALwwDkESamO+RJNMAhhDKJLANwAoKAE90yeAwzY8BYmQrVR4kADNJKaczklyQwfOQAnVR2ASEmprNZQAgsCiFw3AN6CYMXCABiIEABcMO6ensRB0EbEAOZCoTAgAK5QQWCJiABGxnEwAL453gBCHEZBIaHhMBn+ADbIHGA5nkkpVbX1jR55QrmCwmISdjU1Wjby3NTlANqWjDIs8uQAukGzowskDk4uPfrKEqRgAG4gANZzVDAAPAASMMgAHlDIeNznImowQyPWG1AQABovvcni9cG9kB91N91jp-lMbksAHwACi6AAsGrg6qUYDcAV0zNswEE7ATPOgOCIaiAOLhScNYbYIAillM7GyaMQaEsCQBKKhImAABSMSEIEGQVxhvzhLMR7M5LR5SP0uGQwBqJQkvGgMGIJ3O0iCh0NcyEAHoLTAACLICDoQjPGBQdE6pCOnH3IxiozcDjVI7IIGuiVeED2l0DAC0wDdwFOPBAPo1UBqIgAdIJdbAjPbEjVWtUQHUGpcOAB3DhO-XHM5zFF0KSy2w0IE0IolNsuoyJZB8-RWmAAdWTpxKSTwtYdhDzFAyIhg6KgUHQEACVuiTvRiQyGdAiAtiEIwDF9FUUAtABUBnBT4R0JeJRA+xALQBWADMAAYfwBiZ8+wPFASGjABGAAWCCAA4AE5Pwg2CAHZ3yzfYYAAcWQMgwCuK8hWoK8QWeV5glrIIGkXXIYAAfhgK8pi5MAeRgVJkCDIwhHQrCoAAeWSPCCPo4iwTcBJkgosAqNo+jGOVJZWJgMB2OyPp0NNetpFHIxxzFRIp2oW4RNI95PhleY5SBOxjPBGBTOhRkW3GVlUQxLEcSCfFCUcZwSS+ckYEpalaXpTDsMOaVHIs5lWUVJF+UFEUxWPSUrh4-ioEin5ouchUOSRVU+nVTVtSTPhazNLSxwnfTQo0o1MG03TJ1wS1rRvcRY3jU5-W4R5xEcZBcCzHMYDzF9Cyamq8CCYtSzAcsqxrA1NMa6q9LwRt6CsHK2HbTsjG7KBe37fR+uTWBXHyGAhw4dBxC4CRXXdRBPWMIA)

**Comment by Andarist** [comment]
@seansfkelley you are looking for a fix for [this issue](https://github.com/microsoft/TypeScript/issues/21760).

**Review by weswigham — APPROVED** [review]
