### PR TITLE
Fix package.json auto imports for pnpm without project references

### LINKED ISSUE #42094: AutoImportProvider doesn’t work with pnpm unless there are project references
Discovered while investigating #40584, but is not directly related, and a fix for this is irrelevant to that issue on the whole. Fourslash server test:

```ts
/// <reference path="../fourslash.ts" />

// @Filename: /tsconfig.json
//// { "compilerOptions": { "module": "commonjs" } }

// @Filename: /package.json
//// { "dependencies": { "mobx": "*" } }

// @Filename: /node_modules/.pnpm/mobx@6.0.4/node_modules/mobx/package.json
//// { "types": "dist/mobx.d.ts" }

// @Filename: /node_modules/.pnpm/mobx@6.0.4/node_modules/mobx/dist/mobx.d.ts
//// export declare function autorun(): void;

// @Filename: /index.ts
//// autorun/**/

// @link: /node_modules/.pnpm/mobx@6.0.4/node_modules/mobx -> /node_modules/mobx

goTo.marker("");
verify.importFixAtPosition([`import { autorun } from "mobx";\r\n\r\nautorun`]);
```

The problem is that the pnpm symlink doesn’t make it into the symlink cache, which is coincidentally fixed if there are project references due to: https://github.com/microsoft/TypeScript/blob/8bbef818edfa7298fd25af94cddcbc36902667f3/src/compiler/program.ts#L3762-L3763

The proper fix would probably be to save an `originalPath` on `ResolvedTypeReferenceDirective` during module resolution, and then do something with it in `AutoImportProviderHost.getRootFileNames()`.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #42094—read about the reason for the symptom and the rationale behind the fix there. I’m not 100% confident this is the most direct way to fix the problem; open to other ideas if they’re not super complicated.

### CODE REVIEW

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -339,7 +339,13 @@ namespace ts {
         if (resolved) {
             const { fileName, packageId } = resolved;
             const resolvedFileName = options.preserveSymlinks ? fileName : realPath(fileName, host, traceEnabled);
-            resolvedTypeReferenceDirective = { primary, resolvedFileName, packageId, isExternalLibraryImport: pathContainsNodeModules(fileName) };
+            resolvedTypeReferenceDirective = {
+                primary,
+                resolvedFileName,
+                originalFileName: fileName === resolvedFileName ? undefined : fileName,
```
Comment (sheetalkamat) [inline src/compiler/moduleNameResolver.ts:345]: I think this should be `originalPath` just like in `ResolvedModuleFull`.. 
checkout createResolvedModuleWithFailedLookupLocations , you would want to do something similar

File: src/compiler/types.ts [hunk 2]
```diff
@@ -6458,6 +6458,8 @@ namespace ts {
         primary: boolean;
         // The location of the .d.ts file we located, or undefined if resolution failed
         resolvedFileName: string | undefined;
+        /** The location of the symlink to the .d.ts file we found, if `resolvedFileName` was the realpath. */
+        originalFileName: string | undefined;
```
Comment (sheetalkamat) [inline src/compiler/types.ts:6462]: You also want to make this optional esp given this is API...  might break if someone is setting these things manually..

File: src/compiler/utilities.ts [hunk 3]
```diff
@@ -6168,7 +6170,16 @@ namespace ts {
                     }
                     (symlinkedDirectories || (symlinkedDirectories = new Map())).set(symlinkPath, real);
                 }
-            }
+            },
+            setSymlinkedDirectoryFromSymlinkedFile(symlink, real) {
+                const [commonResolved, commonOriginal] = guessDirectorySymlink(real, symlink, cwd, getCanonicalFileName) || emptyArray;
```
Comment (sheetalkamat) [inline src/compiler/utilities.ts:6175]: Should you do this lazily to avoid having to do this by default?
Also dont you want to set `symlinkedFiles` ?

File: tests/cases/fourslash/server/autoImportProvider_pnpm.ts [hunk 4]
```diff
@@ -0,0 +1,21 @@
+/// <reference path="../fourslash.ts" />
+
```
Comment (sheetalkamat) [inline tests/cases/fourslash/server/autoImportProvider_pnpm.ts:2]: Definitely add test with preserveSymLink set to true ?

File: src/server/project.ts [hunk 5]
```diff
@@ -1901,16 +1901,20 @@ namespace ts.server {
...
+                const program = hostProject.getCurrentProgram()!;
+                const symlinkCache = hostProject.getSymlinkCache();
                 for (const resolution of resolutions) {
                     if (!resolution.resolvedTypeReferenceDirective?.resolvedFileName) continue;
-                    const { resolvedFileName } = resolution.resolvedTypeReferenceDirective;
-                    const fileName = moduleResolutionHost.realpath?.(resolvedFileName) || resolvedFileName;
-                    if (!hostProject.getCurrentProgram()!.getSourceFile(fileName) && !hostProject.getCurrentProgram()!.getSourceFile(resolvedFileName)) {
-                        rootNames = append(rootNames, fileName);
+                    const { resolvedFileName, originalFileName } = resolution.resolvedTypeReferenceDirective;
+                    if ((!originalFileName || !program.getSourceFile(originalFileName)) && !program.getSourceFile(resolvedFileName)) {
```
Comment (sheetalkamat) [inline src/server/project.ts:1909]: Given by default we dont have preserveSymlink set to true, do we want to first check `program.getSourceFile(resolvedFileName)` before doing anything with originalFileName?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: tests/cases/fourslash/server/autoImportProvider_pnpm.ts (hunk 4 above)
Comment (andrewbranch) [reply tests/cases/fourslash/server/autoImportProvider_pnpm.ts:2]: pnpm doesn’t work with `--preserveSymlinks`. package.json auto imports probably does need more testing with `--preserveSymlinks` in general, but I want it to be an actually realistic test.

File: src/compiler/utilities.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/utilities.ts:6175]: Is `symlinkedFiles` just a fast path for searching `symlinkedDirectories`? I was just copying what `discoverProbableSymlinks` does. `symlinkedFiles` is not used by module specifier resolution / auto imports, but from the one place that it is used, it seems like it might be beneficial to add to it whenever we can.

Comment (andrewbranch) [reply src/compiler/utilities.ts:6175]: Also, I’m not sure making this more lazy is worth the complexity. This method only gets called during the initialization/update of an AutoImportProviderProject, and is altogether a small part of the overhead of getting better auto imports. It seems like most users _would_ invoke this eventually.

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:345]: It is string and not Path, check in `nodeModuleNameResolverWorker`  though it seems like it should compare paths there and not strings as there could be case difference.( but thats separate issue that @amcasey might want to look in for his realpath fix he was working on )

File: src/compiler/utilities.ts (hunk 3 above)
Comment (sheetalkamat) [reply src/compiler/utilities.ts:6175]: i was just saying because if completions are not invoked, and program get disposed or changes it might be unnecessary but we can do that later if people report on it..

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts:345]: I think if it’s not going to be normalized into a `Path`, the property name should use `fileName` and not `path`. And if we don’t preserve the file name, I think test cases like https://github.com/microsoft/TypeScript/blob/master/tests/cases/fourslash/autoImportSymlinkCaseSensitive.ts will start having issues.

Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:345]: Sorry i wasnt very clear in my comment.. What i was saying was that comparison needs to be between `Path` but value needs to be string.

Comment (andrewbranch) [reply src/compiler/moduleNameResolver.ts:345]: Ah, I see, just for the equality comparison. It doesn’t look like I have easy access to the current directory or `getCanonicalFileName` (the latter is optional on `ModuleResolutionHost`) and this is public API. What do you suggest doing?

Comment (sheetalkamat) [reply src/compiler/moduleNameResolver.ts:345]: I dont think you need to fix it in this PR. But module resolution host has optional `getCurrentDirectory` so we can add `useCaseSensitiveFileNames?(): boolean`  and use Path if both methods exist and compare filenames otherwise. 
you would also want to make sure our all internal `moduleResolutionHosts` have these implemented. Again dont think this is part of your PR but needs to be handled at some point for @amcasey realpath native methods to be used

**Comment by sheetalkamat** [comment]
@andrewbranch you are doing change to use `originalPath` instead right?

**Comment by andrewbranch** [comment]
@sheetalkamat from the thread:

> I think if it’s not going to be normalized into a `Path`, the property name should use `fileName` and not `path`.

Since we agreed the type should be `string` and not `Path`, I was planning on keeping the name `fileName` to match. When I see a property/variable named `path` but its type is `string`, it looks to me like a mistake.

**Comment by sheetalkamat** [comment]
But you still need to copy `originalPath` from resolved instead of having to set it ?

File: src/server/project.ts [hunk 6]
```diff
@@ -1901,16 +1901,20 @@ namespace ts.server {
...
-                    if (!hostProject.getCurrentProgram()!.getSourceFile(fileName) && !hostProject.getCurrentProgram()!.getSourceFile(resolvedFileName)) {
-                        rootNames = append(rootNames, fileName);
+                    const { resolvedFileName, originalFileName } = resolution.resolvedTypeReferenceDirective;
+                    if (!program.getSourceFile(resolvedFileName) && (!originalFileName || !program.getSourceFile(originalFileName))) {
+                        rootNames = append(rootNames, resolvedFileName);
                         // Avoid creating a large project that would significantly slow down time to editor interactivity
                         if (dependencySelection === PackageJsonAutoImportPreference.Auto && rootNames.length > this.maxDependencies) {
                             return ts.emptyArray;
                         }
+                        if (originalFileName) {
```
Comment (sheetalkamat) [inline src/server/project.ts:1915]: Does `discoverProbableSymlinks` need to handle symlinks from type reference resolution now that it happens (we do for module resolution)

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
typeDirectiveIsEqualTo needs to be updated to take into account this new field

**Comment by andrewbranch** [comment]
> But you still need to copy `originalPath` from resolved instead of having to set it ?

@sheetalkamat I looked into this and `originalPath` is never set on `resolved` in this code path. The only place it’s set is in `nodeModuleNameResolverWorker` which isn’t part of the call hierarchy in `resolveTypeReferenceDirective`. I’m sorry, I’m just not familiar enough with module resolution to understand what you’re wanting to see without a lot more details.

**Comment by sheetalkamat** [comment]
>  looked into this and originalPath is never set on resolved in this code path. The only place it’s set is in nodeModuleNameResolverWorker which isn’t part of the call hierarchy in resolveTypeReferenceDirective. I’m sorry, I’m just not familiar enough with module resolution to understand what you’re wanting to see without a lot more details.

sorry about that , i missed the fact that realpath is called just above this and not coming from the resolved value. So your current change is right.

**Review by sheetalkamat — APPROVED** [review]
Not ideal that we have `originalPath` in resolvedModule and `originalFileName` in resolvedTypeReferenceDirective from consistency point of view but not stuck on that.

**Comment by andrewbranch** [comment]
I can change it to `originalPath` and put a warning doc comment on both. My main concern is how easy it is to determine the casing/normalization of the values contained by those properties, and a doc comment should handle that.

**Comment by andrewbranch** [comment]
Also just noticed that `originalPath` is `@internal`, so we could rename it if we ever feel like it.

**Review by sheetalkamat — APPROVED** [review]
