### PR TITLE
During uptodate ness check with buildInfo, check if there are errors explicitly with noEmit

### LINKED ISSUE #50959: 4.8 regression with `tsc --build`: error correctly reported, then another execution succeeds
# Bug Report

Since upgrading to TS4.8, we've seen some surprising behavior around `tsc --build` where rebuilds don't always seem to happen where we expect them to.

Notably, we've now run into an easy to reproduce case where running `tsc --build path/to/tsconfig.json` correctly fails with an error, but running the same command again exits 0 with no output.  Note that in this case, the project has `noEmit` and `composite` set to true (it's a Jest test project).

We have not yet had the opportunity to minimize our project (Apollo Server) but we at least have a commit which reproduces the issue consistently.

This appears to be a 4.8 regression: I can reproduce it with 4.8.2 and 4.8.3 but not 4.7.4.

I'm guessing it might be related to the huge amount of work done on improving these features by  @sheetalkamat in https://github.com/microsoft/TypeScript/pull/48784 ?

### 🔎 Search Terms

tsc noEmit error build twice second time

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.2

### Reproduction

```
$ git clone -b glasser/ts4.8-errors-inconsistent https://github.com/apollographql/apollo-server
$ cd apollo-server
$ npm i
$ npx tsc --build packages/server/src/__tests__/tsconfig.json
$ npx tsc --build packages/server/src/__tests__/tsconfig.json
```

### 🙁 Actual behavior

The first execution of `tsc`  displays this error and exits with status 1:

```
packages/server/src/__tests__/express/expressSpecific.test.ts:45:21 - error TS2345: Argument of type 'ApolloServer<{ x: number; }>' is not assignable to parameter of type 'ApolloServer<BaseContext>'.
  Property 'x' is missing in type 'BaseContext' but required in type '{ x: number; }'.

45   expressMiddleware(differentContextServer); // hi
                       ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

But the second execution of `tsc` exits with status 0 without printing anything.

### 🙂 Expected behavior

Both executions of `tsc` should display an error and exit with non-zero status.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #50959

### CODE REVIEW

File: src/compiler/tsbuildPublic.ts [hunk 1]
```diff
@@ -1609,8 +1609,14 @@ namespace ts {
 
             if (buildInfo.program) {
                 // If there are pending changes that are not emitted, project is out of date
+                // If noEmit, then explicitly check if there are semantic diagnostics
+                // affectedFilesPendingEmit is present in noEmit irrespective of errors to handle files to be emitted when noEmit is false,
```
Comment (andrewbranch) [inline src/compiler/tsbuildPublic.ts:1613]: This helps me understand why `affectedFilesPendingEmit` behaves differently under `noEmit`, but I don’t understand why that makes checking for the presence of semantic errors the correct fallback. Why does the presence of semantic errors definitely mean the buildinfo is out of date? Why isn’t the same true of syntactic errors?

Comment (sheetalkamat) [reply src/compiler/tsbuildPublic.ts:1613]: If program has syntactic errors the `changeFileSet` because semantic diagnostics are not even processed in that case and state remains same. (https://github.com/microsoft/TypeScript/pull/50974/files#diff-2461280d51916bf4023650d8950c0af3bf16011e3f0c8a290c7c9f70056147a0R77) I will update the comment

**Review by andrewbranch — APPROVED** [review]

**Comment by glasser** [comment]
Do we know when this fix will be released? Looks like it didn't quite make it into 4.8.4. We are stuck on 4.7 until it's out.
