### PR TITLE
Transform param patterns/initializers after object rest

### LINKED ISSUE #47079: Generated code is incorrect for function with destructuring and default parameter
# Bug Report

### 🔎 Search Terms

default destructuring scope parameter argument ReferenceError

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/GYVwdgxgLglg9mABMOcAUBvAhgGkQOkIA8BfPAI0QF5EsBKRDAKEUQCcBTKENpcpkkwgIAznAA2HfOLgBzNCnTYAXIgCMJOnSZA)

### 💻 Code

```ts
function foo({a, ...x}, b = a) {
  return b
}
console.log(foo({a: 1}))
```

### 🙁 Actual behavior

If you run TypeScript's output, you get `ReferenceError: a is not defined`. This is the problematic output:

```js
"use strict";
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
function foo(_a, b = a) {
    var { a } = _a, x = __rest(_a, ["a"]);
    return b;
}
console.log(foo({ a: 1 }));
```

Notice how `b = a` is evaluated before `{ a } = _a`.

### 🙂 Expected behavior

If you run the JavaScript directly you should get `1`, so TypeScript's output should do that too.

Additional context is here: https://github.com/evanw/esbuild/issues/1826. I got a report about this bug in esbuild and it turns out TypeScript has the same bug, so I'm filing it here too. My apologies if this is a duplicate (I couldn't find one that had already been filed).

### PR DESCRIPTION
**Pull request by rbuckton**
This performs a full transformation of parameters with binding patterns or initializers when a preceding parameter contains an object rest (`...`) destructuring.

Fixes #47079

### CODE REVIEW

File: src/compiler/transformers/es2018.ts [hunk 1]
```diff
@@ -59,6 +59,7 @@ namespace ts {
         let exportedVariableStatement = false;
         let enabledSubstitutions: ESNextSubstitutionFlags;
         let enclosingFunctionFlags: FunctionFlags;
+        let parameterHasPrecedingObjectRestOrSpread: Set<ParameterDeclaration> | undefined;
```
Comment (andrewbranch) [inline src/compiler/transformers/es2018.ts:62]: I don’t understand why this is shared state when every function that uses it carefully sets and resets it so as to pretend it’s local state. Can’t `visitConstructorDeclaration` etc. simply create this Set locally and pass it to `visitParameter`?

File: src/compiler/transformers/es2018.ts [hunk 2]
```diff
@@ -1018,25 +1069,76 @@ namespace ts {
...
+                        const block = factory.createBlock([factory.createExpressionStatement(assignment)]);
+                        setTextRange(block, parameter);
+                        setEmitFlags(block, EmitFlags.SingleLine | EmitFlags.NoTrailingSourceMap | EmitFlags.NoTokenSourceMaps | EmitFlags.NoComments);
+
+                        const typeCheck = factory.createTypeCheck(factory.cloneNode(parameter.name), "undefined");
+                        const statement = factory.createIfStatement(typeCheck, block);
+                        startOnNewLine(statement);
+                        setTextRange(statement, parameter);
+                        setEmitFlags(statement, EmitFlags.NoTokenSourceMaps | EmitFlags.NoTrailingSourceMap | EmitFlags.CustomPrologue | EmitFlags.NoComments);
+                        statements = append(statements, statement);
```
Comment (andrewbranch) [inline src/compiler/transformers/es2018.ts:1125]: It would be nice to add a comment demonstrating what code we’re generating here. It’s a lot of work to reproduce it mentally from the code.

File: src/compiler/transformers/es2018.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/es2018.ts:62]: We don't pass state through `visitParameterList`, so there's no way to pass it to `visitParameter` without duplicating the logic of `visitParameterList`.

Comment (rbuckton) [reply src/compiler/transformers/es2018.ts:62]: The only other alternative is to use an arrow function that creates a closure, and that would affect performance.

Comment (andrewbranch) [reply src/compiler/transformers/es2018.ts:62]: Does this even work correctly when there are parameters nested within parameters?

```ts
function f({ ...a, x }, b = (c, d) => {}) {}
```

Won’t `c` and `d` be added to the Set containing `b`? It looks to me like each function also needs to set it to `undefined` after saving it, which is even more bookkeeping ☹️

Comment (rbuckton) [reply src/compiler/transformers/es2018.ts:62]: While I don't disagree, it's a pattern we employ throughout the transformers. That said, you are correct that the child parameters are added to the set incorrectly. I've amended the logic to ensure the set is scoped to each function/method.

**Review by andrewbranch — APPROVED** [review]
