### PR TITLE
Fixup line and offset of rename location of refactor

### LINKED ISSUE #19116: renameLocation doesn't seem to be working for extract local
**TypeScript Version:**  2.6.0-dev.20171011

**Code**

```ts
// blank line
const x = 0;
```

Highlight `0`. Select "Extract to constant in enclosing scope".

**Expected behavior:**

Get to rename the newly created local.

**Actual behavior:**

Rename location doesn't work. Tested with vscode insiders. It does work for extract function.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19116
Tested by pointing vscode to the output of `gulp local`.

### CODE REVIEW

File: src/harness/unittests/session.ts [hunk 1]
```diff
@@ -661,4 +661,26 @@ namespace ts.server {
...
+                        span: { start: 0, length: 0 },
+                        newText: "const newLocal = 0;\n\n",
+                    },
+                    {
+                        span: { start: newLocation, length: 1 },
+                        newText: "newLocal",
+                    },
+                ],
+            };
+            fixupLineAndOffset({ line: 2, offset: 11 }, text, newLocation, fileName, [edits]);
```
Comment (amcasey) [inline src/harness/unittests/session.ts]: It looks like the output of `fixupLineAndOffset` is not consumed.  Am I missing something?

File: src/server/session.ts [hunk 2]
```diff
@@ -1506,16 +1506,19 @@ namespace ts.server {
...
 
             if (simplifiedResult) {
-                const file = result.renameFilename;
-                let location: protocol.Location | undefined;
-                if (file !== undefined && result.renameLocation !== undefined) {
-                    const renameScriptInfo = project.getScriptInfoForNormalizedPath(toNormalizedPath(file));
-                    location = renameScriptInfo.positionToLineOffset(result.renameLocation);
+                const { renameFilename, renameLocation, edits } = result;
+                let mappedRenameLocation: protocol.Location | undefined;
+                if (renameFilename !== undefined && result.renameLocation !== undefined) {
```
Comment (amcasey) [inline src/server/session.ts]: `result.renameLocation` -> `renameLocation`?

File: src/server/session.ts [hunk 3]
```diff
@@ -2015,4 +2018,40 @@ namespace ts.server {
...
+            }
+        }
+
+        return { line, offset };
+    }
+
+    function countNewlines(s: string): number {
+        let count = 0;
+        for (let i = 0; i < s.length; i++) {
+            if (s.charCodeAt(i) === CharacterCodes.lineFeed) {
```
Comment (amcasey) [inline src/server/session.ts]: It looks like this will do the wrong thing for CR-only files.  I assume we don't care.

File: src/server/session.ts [hunk 4]
```diff
@@ -2015,4 +2018,40 @@ namespace ts.server {
             }
         }
     }
+
+    /* @internal */ // exported for tests only
+    /** Since we will perform the rename in a changed document, line and offset information must be adjusted if the new text adds/deletes newlines. */
+    export function fixupLineAndOffset(oldPosition: protocol.Location, oldText: string, location: number, locationFileName: string, edits: ReadonlyArray<FileTextChanges>): protocol.Location {
+        let { line, offset } = oldPosition;
+        const lineStartOfLocation = location - (offset - 1); // offset is 1-based, location is 0-based
```
Comment (amcasey) [inline src/server/session.ts]: Will this value be incorrect if there's an edit on the same line, before `location`?

Comment (andy-ms) [reply src/server/session.ts]: This is meant to be the line start in the *old* document.

File: src/server/session.ts [hunk 5]
```diff
@@ -2040,4 +2043,50 @@ namespace ts.server {
...
+
+    function countNewlines(s: string): number {
+        let count = 0;
+        for (let i = 0; i < s.length; i++) {
+            switch (s.charCodeAt(i)) {
+                case CharacterCodes.carriageReturn:
+                    count++;
+                    i++;
+                    // Skip a "\n" after a "\r" because "\r\n" is only one newline. But "\r\r" is two.
+                    if (s.charCodeAt(i) === CharacterCodes.carriageReturn) {
```
Comment (amcasey) [inline src/server/session.ts]: Do you need a bounds check in case the last character is `\r`?

File: src/server/session.ts (hunk 4 above)
Comment (amcasey) [reply src/server/session.ts]: But isn't `location` in the new document?

File: src/server/session.ts [hunk 6]
```diff
@@ -2040,4 +2043,50 @@ namespace ts.server {
...
+        for (const { fileName, textChanges } of edits) {
+            if (fileName !== locationFileName) {
+                continue;
+            }
+
+            // Text change spans are in the *old* document. They apply all at once rather than sequentially.
+            for (const { newText, span: { start, length } } of textChanges) {
+                const newTextNewlines = countNewlines(newText);
+                line += newTextNewlines - countNewlines(oldText.slice(start, start + length));
+                if (start > oldLineStartOfLocation && start < location) {
```
Comment (amcasey) [inline src/server/session.ts]: `start >= oldLineStartOfLocation`?

File: src/server/session.ts [hunk 7]
```diff
@@ -2040,4 +2043,50 @@ namespace ts.server {
...
+    export function fixupLineAndOffset(oldPosition: protocol.Location, oldText: string, location: number, locationFileName: string, edits: ReadonlyArray<FileTextChanges>): protocol.Location {
+        let { line, offset } = oldPosition;
+        const oldLineStartOfLocation = location - (offset - 1); // offset is 1-based, location is 0-based
+
+        for (const { fileName, textChanges } of edits) {
+            if (fileName !== locationFileName) {
+                continue;
+            }
+
+            // Text change spans are in the *old* document. They apply all at once rather than sequentially.
```
Comment (amcasey) [inline src/server/session.ts]: Isn't it only the edits *before* the (old) position that apply?

**Comment by amcasey** [comment]
I think I must be missing something high-level, because the math isn't making sense to me.

File: src/server/session.ts (hunk 5 above)
Comment (andy-ms) [reply src/server/session.ts]: Should be fixed now

File: src/server/session.ts (hunk 7 above)
Comment (andy-ms) [reply src/server/session.ts]: Thanks, fixed
