### PR TITLE
Unwrap parens when checking for JSDocFunctionType in conditional expression

### LINKED ISSUE #46933: createSourceFile build wrong AST in some cases.
# Bug Report

### 🕗 Version & Regression Information

- This is a parsing error on 4.5(maybe lower), 4.6-dev

### ⏯ Playground Link

[AST Tree](https://astexplorer.net/#/gist/275f0b786568fff3172a590d680d9184/49214d505f07f8c48b6b2de668ecaa3c21c1cc3f)

### 💻 Code

Parsed JS
```ts repro
!a
    ? (a = (function () {})())
    : (function(a){})(a);
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?allowJs=true&ts=4.5.2#code/IQQwUABFEPwQFCCBeBAzArgOwMYBcBLAeywQEoIBvAXzPjLMmgC51t9itEya6QyA3EA)

```ts repro
import { createPrinter, createSourceFile, ScriptTarget } from "typescript";

const source = `!a
    ? (a = (function () {})())
    : (function(a){return !0})(a);`

console.log(
    createPrinter().printFile(
        createSourceFile(`test.js`, source, ScriptTarget.Latest)
    )
);
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?allowJs=true&ts=4.5.2#code/JYWwDg9gTgLgBAbzgYygUwIYzQBSsAO2ygBoV0s0BlCAVymTQDFgAbNMq1YMGAFQxQA5mngBfOADMoEEHABEMAJ5g0AZ2695AbgBQu5BAJr4augzRwAvHAAGAQgy64LuAH44ACgzWvk2gTIMMBGXgCUiGJhnmFhzq4AXH4BQSEE3mEI6DD0BHD2AAxRGdq2+obGEOwAdKwQQp7xLqiY2HiExDHVYPhELOyNrkPkrdTmjP1onrbYJtUAVmq2ZGb0jJya-IIiMNUAMpQmcUNxYXq6QA)

### 🙁 Actual behavior
Wrong JS/TS.
```js
!a
    ? (a = (function () { })()): (function(: a):) => { } : ;
(a);
```
Local tsc for example.ts code make 
```js
"use strict";
!a
    ? (a = (function () { })()) => { } : ;
(a);
```

### 🙂 Expected behavior

```js
!a
    ? (a = (function () { })()): (function (a) { })(a); ;
(a);
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #46933

This is a followup to #46960; I realized that these could be nested after merging.

`skipParentheses` is for `Expression` and doesn't work here. Other places do this loop, so I've copied the same pattern as other places and removed my use of `isParenthesizedTypeNode`. Seems like it'd be a good helper, but it's only two other places, somehow.

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -4539,10 +4539,17 @@ namespace ts {
             //  - "(x,y)" is a comma expression parsed as a signature with two parameters.
             //  - "a ? (b): c" will have "(b):" parsed as a signature with a return type annotation.
             //  - "a ? (b): function() {}" will too, since function() is a valid JSDoc function type.
-            //  - "a ? (b): (function() {})" as well, but inside of a parenthesized type.
+            //  - "a ? (b): (function() {})" as well, but inside of a parenthesized type with an arbitrary amount of nesting.
             //
             // So we need just a bit of lookahead to ensure that it can only be a signature.
-            const hasJSDocFunctionType = type && (isJSDocFunctionType(type) || isParenthesizedTypeNode(type) && isJSDocFunctionType(type.type));
+
+            let unwrappedType = type;
```
Comment (a-tarasyuk) [inline src/compiler/parser.ts:4546]: It seems you can use this helper

https://github.com/microsoft/TypeScript/blob/1ade73df2bf3e83085ca4647d0a3339abe3f869b/src/compiler/utilities.ts#L2918-L2920

Comment (jakebailey) [reply src/compiler/parser.ts:4546]: That walks upward, which is the wrong direction. I need to remove the parens, not walk up from the inside to the outermost parens.

Comment (a-tarasyuk) [reply src/compiler/parser.ts:4546]: Got it. Thanks for the clarification.

File: src/compiler/parser.ts [hunk 2]
```diff
@@ -4539,10 +4539,17 @@ namespace ts {
...
             // So we need just a bit of lookahead to ensure that it can only be a signature.
-            const hasJSDocFunctionType = type && (isJSDocFunctionType(type) || isParenthesizedTypeNode(type) && isJSDocFunctionType(type.type));
+
+            let unwrappedType = type;
+            while (unwrappedType?.kind === SyntaxKind.ParenthesizedType) {
+                unwrappedType = (unwrappedType as ParenthesizedTypeNode).type;  // Skip parens if need be
+            }
+
+            const hasJSDocFunctionType = unwrappedType && isJSDocFunctionType(unwrappedType);
+            // const hasJSDocFunctionType = type && isJSDocFunctionType(skipParentheses(type));
```
Comment (sandersn) [inline src/compiler/parser.ts:4552]: leftover comment

**Review by sandersn — APPROVED** [review]

File: src/compiler/parser.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/parser.ts:4552]: Aha, thank you.
