### PR TITLE
Fix parameter emit for synthetic function types

### LINKED ISSUE #15651: Printer doesn't parenthesize untyped rest arguments in function type literals
**TypeScript Version:**  2.3.2

**Code**

```ts
import ts = require("typescript");

function getAnyFunctionTypeNode() {
    const param = ts.createParameter(
        /*decorators*/ undefined,
        /*modifiers*/ undefined,
        ts.createToken(ts.SyntaxKind.DotDotDotToken),
        "args");

    const result = ts.createFunctionTypeNode(
            /*typeParameters*/ undefined,
            /*parameters*/[param],
            /*type*/ ts.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword));
    return result;
}

const node = getAnyFunctionTypeNode();
const file = ts.createSourceFile("foo.ts", "", ts.ScriptTarget.Latest, /*setParentNodes*/ false, ts.ScriptKind.TS);
const output = ts.createPrinter().printNode(ts.EmitHint.Unspecified, node, file);
console.log(output);
```

**Expected behavior:**

Console logs the following:

```
(...args) => any
```

**Actual behavior:**

Console logs the following:

```
...args => any
```

### PR DESCRIPTION
**Pull request by rbuckton**
Currently, the emitter determines whether to emit parentheses around the parameter purely based on the number of parameters and whether there are any parsed tokens between the parent node and the first parameter.  However, this logic is invalid if both the parent node and the parameter are both synthesized.

This change adds a few more additional tests to ensure its valid to emit the parameter list of an arrow function or function type.

Fixes #15651

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -2283,11 +2283,25 @@ namespace ts {
...
 
-        function emitParametersForArrow(parentNode: Node, parameters: NodeArray<ParameterDeclaration>) {
-            if (parameters &&
-                parameters.length === 1 &&
-                parameters[0].type === undefined &&
-                parameters[0].pos === parentNode.pos) {
+        function canEmitSimpleArrowHead(parentNode: FunctionTypeNode | ArrowFunction, parameters: NodeArray<ParameterDeclaration>) {
+            const parameter = singleOrUndefined(parameters);
+            return parameter
+                && parameter.pos === parentNode.pos // may not have parsed tokens between parent and parameter
```
Comment (DanielRosenwasser) [inline src/compiler/emitter.ts]: Is this for `async`?

**Comment by DanielRosenwasser** [comment]
👍

File: src/compiler/emitter.ts (hunk 1 above)
Comment (rbuckton) [inline src/compiler/emitter.ts]: This existed previously and was for handling source parsed as `(x) => x` vs `x => x`.
