### PR TITLE
Handle comment directives in incremental parsing

### LINKED ISSUE #37536: @ts-ignore stops in editing (regression)
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

1. clone https://github.com/falsandtru/spica
2. run `npm i`
3. launch VSCode
4. open src/supervisor.ts
5. remove the first @ts-ignore
6. redo
7. the error ignored by @ts-ignore is activated

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:** #32953

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #37536

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -7805,10 +7804,68 @@ namespace ts {
...
+
+            function addNewlyScannedDirectives() {
+                if (addedNewlyScannedDirectives) return;
+                addedNewlyScannedDirectives = true;
+                if (!commentDirectives) {
+                    commentDirectives = newDirectives;
+                }
+                else if (newDirectives) {
+                    commentDirectives.push(...newDirectives);
+                }
```
Comment (andrewbranch) [inline src/compiler/parser.ts]: I think `concatenate` in core can handle this in a single call, similarly to `append`

Comment (sheetalkamat) [reply src/compiler/parser.ts]: That one creates new array if both arrays are `!undefined` which is what this avoids since anyways we already have new array
