### PR TITLE
use separate process to probe if drive is safe to watch

### LINKED ISSUE #13997: TSServer Crashes when Opening file from Mapped Sharepoint Drive
From: https://github.com/Microsoft/vscode/issues/20445

**TypeScript Version:**  2.1.6

This issue is similar to #13874 but when opening a mapped sharepoint drive on windows instead of opening the WebDAV drive directly.

**Repo Steps**
* In windows, mount a sharepoint WebDAV drive by going to `This PC` ->  `map network drive`.
    * This should not be the root folder where the js/ts files are stored
    * I used https://microsoft.sharepoint.com/teams/DD_OTP/Documents/ mounted on the z drive
* Open a file on this drive in VSCode. For example: `Z:\Java and Open Tools\Node\test`

This produces the same symptoms as #13874 

```js
[Info  - 11:32:02 AM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Trace - 11:32:02 AM] Sending request: configure (33). Response expected: yes. Current queue length: 0
Arguments: {
    "hostInfo": "vscode"
}
[Trace - 11:32:03 AM] Response received: configure (33). Request took 467 ms. Success: true 
[Trace - 11:32:03 AM] Sending request: compilerOptionsForInferredProjects (34). Response expected: yes. Current queue length: 3
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve"
    }
}
[Trace - 11:32:03 AM] Response received: compilerOptionsForInferredProjects (34). Request took 483 ms. Success: true 
Result: true
[Trace - 11:32:03 AM] Sending request: open (35). Response expected: no. Current queue length: 2
Arguments: {
    "file": "z:/Java and Open Tools/Node/test/main.js",
    "fileContent": "console.log()\r\nfdsaf gdsczx"
}
[Trace - 11:32:03 AM] Sending request: geterr (36). Response expected: no. Current queue length: 1
Arguments: {
    "delay": 0,
    "files": []
}
[Trace - 11:32:03 AM] Sending request: geterr (37). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "z:/Java and Open Tools/Node/test/main.js"
    ]
}
[Error - 11:32:03 AM] TSServer exited with code: 3221226356
````

### PR DESCRIPTION
**Pull request by vladima**
fixes #13997

### CODE REVIEW

File: src/server/watchGuard/watchGuard.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+/// <reference types="node" />
+
+if (process.argv.length < 3) {
+    process.exit(1);
+}
+const directoryName = process.argv[2];
+const fs: { watch(directoryName: string, options: any, callback: () => {}): any } = require("fs");
+fs.watch(directoryName, { recursive: true }, () => ({})).close();
```
Comment (billti) [inline src/server/watchGuard/watchGuard.ts]: I could think of a number of scenarios where this might be more defensive (e.g. check it exists, check it is a dir, check fs.watch returned a watcher object, etc...), but in all those cases seems the resulting error would result in correct behavior anyway in the listening process. However, might be worth a comment to note that this is deliberately "loose" here.

File: src/server/server.ts [hunk 2]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
+        return undefined;
+    }
+
+    export function isUNCPath(s: string): boolean {
+        return s.length > 2 && s.charCodeAt(0) === CharacterCodes.slash && s.charCodeAt(1) === CharacterCodes.slash;
+    }
+
     const sys = <ServerHost>ts.sys;
+    // use watchGuard process on Windows when node version is 4 or later
+    const useWatchGuard = process.platform === "win32" && parseInt(process.version.charAt(1)) >= 4;
```
Comment (billti) [inline src/server/server.ts]: In about 18 months when Node.js releases v10, this charAt check is going to break.

File: src/server/server.ts [hunk 3]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
         }
     }
 
+    function extractWatchDirectoryCacheKey(path: string, currentDriveKey: string) {
+        path = normalizeSlashes(path);
+        if (isUNCPath(path)) {
+            // UNC path: extract server name
+            // //server/location
+            //         ^ <- from 0 to this position
+            const firstSlash = path.indexOf(directorySeparator, 2);
```
Comment (billti) [inline src/server/server.ts]: Any reason this might ever get a UNC path without the next separator (e.g. just "//someshare")? For safety, might want to check for indexOf returning -1 and return undefined.

File: src/server/server.ts [hunk 4]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
+
+    export function isUNCPath(s: string): boolean {
+        return s.length > 2 && s.charCodeAt(0) === CharacterCodes.slash && s.charCodeAt(1) === CharacterCodes.slash;
+    }
+
     const sys = <ServerHost>ts.sys;
+    // use watchGuard process on Windows when node version is 4 or later
+    const useWatchGuard = process.platform === "win32" && parseInt(process.version.charAt(1)) >= 4;
+    if (useWatchGuard) {
+        const currentDrive = extractWatchDirectoryCacheKey(sys.resolvePath(sys.getCurrentDirectory()), /*currentDriveKey*/ undefined);
```
Comment (billti) [inline src/server/server.ts]: If I'm following this logic correctly, then local files on a system that doesn't use drive letters (e.g. Mac/Linux with "/user/bill/documents" etc...) will never get a cache key, and thus will never use the cache, always taking the hit to spawn the guard process. Is that right?

Comment (billti) [inline src/server/server.ts]: ah.... but of course. "useWatchGuard" in only true it process.platform == "win32". Don't mind me :-)

File: src/server/watchGuard/watchGuard.ts (hunk 1 above)
Comment (vladima) [inline src/server/watchGuard/watchGuard.ts]: After thinking a bit more we should be more restrictive here. Will update

File: src/server/server.ts (hunk 2 above)
Comment (vladima) [inline src/server/server.ts]: fair enough, I'll update similar code in `sys` as well

File: src/server/server.ts (hunk 3 above)
Comment (vladima) [inline src/server/server.ts]: technically it might, will fix

File: src/server/server.ts (hunk 4 above)
Comment (vladima) [inline src/server/server.ts]: issue is specific to Windows version of libuv and does not exist on other platforms

File: src/server/server.ts (hunk 2 above)
Comment (vladima) [inline src/server/server.ts]: ✔️

File: src/server/server.ts [hunk 5]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
+            if (status === undefined) {
+                if (logger.hasLevel(LogLevel.verbose)) {
+                    logger.info(`${cacheKey} not found in cache...`);
+                }
+                try {
+                    const args = [combinePaths(__dirname, "watchGuard.js"), path];
+                    if (logger.hasLevel(LogLevel.verbose)) {
+                        logger.info(`Starting ${process.execPath} with args ${JSON.stringify(args)}`);
+                    }
+                    childProcess.execFileSync(process.execPath, args, { stdio: "ignore", env: { "ELECTRON_RUN_AS_NODE": "1" } });
```
Comment (billti) [inline src/server/server.ts]: Seems like it might be worth using the 'timeout' option on execFileSync. Seeing as 'fs.watch' by default will keep the process alive until 'close' has been called on the filewatcher, if the callback the calls 'close' doesn't run for some reason, this would effectively hang tsserver. Seems like 1000ms should be a generous worst-case choice.

File: Jakefile.js [hunk 6]
```diff
@@ -570,8 +572,11 @@ compileFile(cancellationTokenFile, cancellationTokenSources, [builtLocalDirector
 var typingsInstallerFile = path.join(builtLocalDirectory, "typingsInstaller.js");
 compileFile(typingsInstallerFile, typingsInstallerSources, [builtLocalDirectory].concat(typingsInstallerSources), /*prefixes*/ [copyright], /*useBuiltCompiler*/ true, { outDir: builtLocalDirectory, noOutFile: false });
 
+var watchGuardFile = path.join(builtLocalDirectory, "watchGuard.js");
+compileFile(watchGuardFile, watchGuardSources, [builtLocalDirectory].concat(watchGuardSources), /*prefixes*/ [copyright], /*useBuiltCompiler*/ true, { outDir: builtLocalDirectory, noOutFile: false });
+
 var serverFile = path.join(builtLocalDirectory, "tsserver.js");
-compileFile(serverFile, serverSources, [builtLocalDirectory, copyright, cancellationTokenFile, typingsInstallerFile].concat(serverSources), /*prefixes*/ [copyright], /*useBuiltCompiler*/ true, { types: ["node"], preserveConstEnums: true });
+compileFile(serverFile, serverSources, [builtLocalDirectory, copyright, cancellationTokenFile, typingsInstallerFile, watchGuardFile].concat(serverSources), /*prefixes*/ [copyright], /*useBuiltCompiler*/ true, { types: ["node"] });
```
Comment (billti) [inline Jakefile.js]: Was the removal of `preserveConstEnums: true` deliberate? Is it needed in this change?

File: src/server/watchGuard/watchGuard.ts (hunk 1 above)
Comment (vladima) [inline src/server/watchGuard/watchGuard.ts]: ✔️

File: Jakefile.js (hunk 6 above)
Comment (vladima) [inline Jakefile.js]: no, bad merge

Comment (vladima) [inline Jakefile.js]: ✔️

File: src/server/server.ts (hunk 5 above)
Comment (vladima) [inline src/server/server.ts]: `close` is not called inside the callback but rather on return value of `fs.watch`

File: src/server/watchGuard/watchGuard.ts (hunk 1 above)
Comment (billti) [inline src/server/watchGuard/watchGuard.ts]: Does the libuv bug definitely cause the process to crash synchronously on calling "fs.watch"? (i.e. it's not going to get to `process.exit(0)` before it the crash would occur).

Comment (vladima) [inline src/server/watchGuard/watchGuard.ts]: it is crashes synchronously when creating watcher

File: src/server/server.ts (hunk 5 above)
Comment (billti) [inline src/server/server.ts]: Actually, looking at `watchGuard.js` again, seem like it will always exit. The only risk being if `fs.watch` itself blocks for some reason, but then that's the same call that's going to run in tsserver anyway, so probably no value in the timeout.

File: src/server/server.ts (hunk 3 above)
Comment (vladima) [inline src/server/server.ts]: ✔️

File: src/compiler/sys.ts [hunk 7]
```diff
@@ -315,9 +330,8 @@ namespace ts {
             }
             const watchedFileSet = createWatchedFileSet();
 
-            function isNode4OrLater(): boolean {
-                return parseInt(process.version.charAt(1)) >= 4;
-            }
+            const nodeVersion = getNodeMajorVersion();
```
Comment (billti) [inline src/compiler/sys.ts]: Cool. `parseInt(process.versions.node)` would also have done the trick ;-)

Comment (vladima) [inline src/compiler/sys.ts]: good to know :) can change it to your proposal if you insist

File: src/server/server.ts [hunk 8]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
     }
 
+    function extractWatchDirectoryCacheKey(path: string, currentDriveKey: string) {
+        path = normalizeSlashes(path);
+        if (isUNCPath(path)) {
+            // UNC path: extract server name
+            // //server/location
+            //         ^ <- from 0 to this position
+            const firstSlash = path.indexOf(directorySeparator, 2);
+            return firstSlash !== -1 ? path.substring(0, firstSlash).toLowerCase() : undefined;
```
Comment (mhegazy) [inline src/server/server.ts]: `path` instead of `undefined`

File: src/server/server.ts [hunk 9]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
+        }
+        if (path.charCodeAt(0) === CharacterCodes.slash && path.charCodeAt(1) !== CharacterCodes.slash) {
+            // rooted path that starts with slash - /somename - use key for current drive
+            return currentDriveKey;
+        }
+        // do not cache any other cases
+        return undefined;
+    }
+
+    export function isUNCPath(s: string): boolean {
```
Comment (mhegazy) [inline src/server/server.ts]: no need for `export`

File: src/server/server.ts [hunk 10]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
+    if (useWatchGuard) {
+        const currentDrive = extractWatchDirectoryCacheKey(sys.resolvePath(sys.getCurrentDirectory()), /*currentDriveKey*/ undefined);
+        const statusCache = createMap<boolean>();
+        const originalWatchDirectory = sys.watchDirectory;
+        sys.watchDirectory = function (path: string, callback: DirectoryWatcherCallback, recursive?: boolean): FileWatcher {
+            const cacheKey = extractWatchDirectoryCacheKey(path, currentDrive);
+            let status = cacheKey && statusCache.get(cacheKey);
+            if (status === undefined) {
+                if (logger.hasLevel(LogLevel.verbose)) {
+                    logger.info(`${cacheKey} not found in cache...`);
```
Comment (mhegazy) [inline src/server/server.ts]: we should log the path as well.

File: src/server/server.ts [hunk 11]
```diff
@@ -576,7 +577,84 @@ namespace ts.server {
...
+                }
+                try {
+                    const args = [combinePaths(__dirname, "watchGuard.js"), path];
```
Comment (mhegazy) [inline src/server/server.ts]: make sure LKG has the file name.

File: src/server/server.ts (hunk 8 above)
Comment (vladima) [inline src/server/server.ts]: :heavy_check_mark:

File: src/server/server.ts (hunk 10 above)
Comment (vladima) [inline src/server/server.ts]: :heavy_check_mark:
