### PR TITLE
Increase selectivity of subtype relationship for signatures

### LINKED ISSUE #35414: Destructuring of optional fn + default function value gets signature from the value
**TypeScript Version:**  3.7.2 & 3.8.0-dev.20191128

**Search Terms:**
destructuring default value function

**Code**

```ts
interface ReturnVal {
    something(a: string): string // has one param
}

function getFn(): ReturnVal {
    return {
        something(a) { return a }
    }
}

interface PartialOptions {
    something?(a: string, b?: string): string // has two params
}

function run(options: PartialOptions) {
    const { something = getFn().something } = options;

    const something2 = options.something ?? getFn().something;

    return {
        method() {
            something('', '') // this should not error
            something2('', '') // also wrong?

            // and now the twist: hovering "something" and something2 (above) shows *correct* signatures. :)
        }
    }
}
```

**Expected behavior:**
Pick up the function signature of PartialOptions when checking the call.

**Actual behavior:**
Hover shows *correct* signature. Type check breaks saying single parameter is expected.

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=29&pc=1#code/JYOwLgpgTgZghgYwgAgEoTAVyiAanAG2QG8AoZC5AZwHsBbDAC1AHMAKOALmrClYEpuVXq2QB6MckZwqyGiBQAHOFDh1SAX1KkYmEAjDB5yFhgBiINoLQZseQiXKUotnI8ofq9Jqw78SyC5YbnDIWh5aWqSgkLCIKAAKKoaEAPKKhvKyZB60DGDMICwA-BxCIkUANMgARsXlfEXWwo0s4pLSsmAA7jTIyqp0VJrauvqZIIF6bDQZRiBU3ElQKQTpE1T+OZQIWWABeT5FyAC8JuaW-AB0hwWiGqdyc1kA3Noeuwv7t4UsAEyPWYbG7eO7HYrFc5gCxWEH5X5vJwUIJ2dyeCjwmgAEysaPRuVBvzYAHJidVSf4JMg7rIqIwaJgCFjkCAaPtoFAaFAkfiKD9WH8SWTkBT2shCLRkN1OUViu9eZQqXAQMzWd1qYwUD1gMJuPSAG7QUQAIn5RWN4pVXnhAuQHBqNEN-jpNG6sgAVLsoC4DO7qMAWCA4MEIFQrshOPweREeZFSEA

**Related Issues:** 
found many issues about destructuring, but couldn't identify an issue about default values for functions. some are about generics behaviour, etc.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR introduces a new strict subtype relationship and uses this relationship in union subtype reduction. The new strict subtype relationship increases selectivity for signatures which in turn increases the stability of subtype reduction in union types. Specifically

* the signature `() => void` is now always considered a strict subtype of `(x?: string) => void` (it previously was only for strictly checked function types, see #18654), and
* the signature `(x: string | undefined) => void` is now considered a strict subtype of `(x?: string) => void`.

Beyond these differences, the strict subtype relationship is the same as our existing subtype relationship. Ideally we'd use the new strict subtype relationship everywhere, but to reduce breaking changes we're only using it for union subtype reduction.

An example:

```ts
function f1(x: { f(): void }, y: { f(x?: string): void }) {
    let z = !!true ? x : y;
    z.f();
    z.f("hello");  // Previously error, now ok
}

function f2(x: { f(x: string | undefined): void }, y: { f(x?: string): void }) {
    let z = !!true ? x : y;
    z.f();         // Previously error, now ok
    z.f("hello");
}
```

Previously errors were reported in both functions above.

Fixes #35414.

### CODE REVIEW

**Comment by weswigham** [comment]
Do we likewise now consider `(x?: string | undefined) => void` to be a strict subtype of `(x: string | undefined) => void`?

**Comment by ahejlsberg** [comment]
@weswigham No, but it probably wouldn't be too hard to add.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by weswigham** [comment]
Hm, I think I misspoke earlier, though - since `(x?: string | undefined) => void` is logically equivalent to `(() => void) | ((x: string | undefined) => void)`, `(x: string | undefined) => void` is clearly a subtype of `(x?: string | undefined) => void`, not the other way around.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot user test this

**Comment by ahejlsberg** [comment]
Summary of impact on test suites:

* RWC suites have breaks in `Azure_Framework` and `Azure_Website`, all related to union subtype reduction (or lack thereof) between a local `Promise<T>` and `Q.Promise<T>`. It's actually a bit surprising that we previously reduced to the local `Promise<T>` and we certainly wouldn't have in `--strict` mode.
* Community test suites have breaks in `lodash` and `uglify-js`. Both a JavaScript code bases with JSDoc comments that already generate lots of errors. We now generate fewer errors overall, but a there are a couple of new ones. In general this PR is an improvement.
* DT test suites have a single break that appears unrelated to this PR.

Overall I think the breaks are acceptable.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15490,7 +15495,6 @@ namespace ts {
                     // to X. Failing both of those we want to check if the aggregation of A and B's members structurally
                     // relates to X. Thus, we include intersection types on the source side here.
                     if (source.flags & (TypeFlags.Object | TypeFlags.Intersection) && target.flags & TypeFlags.Object) {
-                        // Report structural errors only if we haven't reported any errors yet
```
Comment (weswigham) [inline src/compiler/checker.ts]: Did you mean to remove this comment?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14081,14 +14083,17 @@ namespace ts {
...
-                    !callbackCheck && !strictVariance && compareTypes(sourceType, targetType, /*reportErrors*/ false) || compareTypes(targetType, sourceType, reportErrors);
+                let related = callbacks ?
+                    compareSignaturesRelated(targetSig!, sourceSig!, (checkMode & SignatureCheckMode.StrictArity) | (strictVariance ? SignatureCheckMode.StrictCallback : SignatureCheckMode.BivariantCallback), reportErrors, errorReporter, incompatibleErrorReporter, compareTypes, reportUnreliableMarkers) :
+                    !(checkMode & SignatureCheckMode.Callback) && !strictVariance && compareTypes(sourceType, targetType, /*reportErrors*/ false) || compareTypes(targetType, sourceType, reportErrors);
+                // With strict arity, (x: number | undefined) => void is a subtype of (x?: number | undefined) => void
+                if (related && checkMode & SignatureCheckMode.StrictArity && i >= getMinArgumentCount(source) && i < getMinArgumentCount(target) && isTypeIdenticalTo(sourceType, targetType)) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: What's the `isTypeIdenticalTo` check here for?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: Without it a signature like `(x?: string | undefined) => void` wouldn't be a subtype of `(x: string) => void`. We want it to be such that we reduce a union to just `(x: string) => void`. It's basically a tiebreaker for positions with identical types but one with and one without the `?` modifier.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: No, I'll put it back.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: ...Mmm, but `isTypeIdenticalTo` doesn't seem quite right...? Shouldn't it be `compareTypes(sourceType, targetType, /*reportErrors*/ false)`? The difference, I think, should really only be visible, but from what I gather is important when callbacks with optional parameters are the parameter type of callbacks with optional parameters, eg `(x?: (x?: string | undefined) => void) => void` and `(x: (x: string | undefined) => void) => void` The first should be a subtype of the second because the second's parameter is a subtype of the first's.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, probably better to use `compareTypes`.
