### PR TITLE
Clamp calculated sourcemap positions rather than throwing

### LINKED ISSUE #25844: Debug failure in `computePositionOfLineAndCharacter` when decoding source map
**TypeScript Version:**  master

**Code**

```
    Debug Failure. False expression.

    Error: Debug Failure. False expression.
    at computePositionOfLineAndCharacter (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:5951:22)
    at Object.getPositionOfLineAndCharacter (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:5941:16)
    at getPositionOfLineAndCharacterUsingName (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:61580:27)
    at processPosition (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:61602:37)
    at Object.arrayFrom (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:1129:31)
    at calculateDecodedMappings (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:61647:32)
    at getDecodedMappings (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:61583:62)
    at getGeneratedOrderedMappings (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:61589:80)
    at Object.getOriginalPosition (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:61555:28)
    at Object.tryGetOriginalLocation (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:99306:63)
    at getMappedLocation (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:117884:52)
    at /home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:118484:34
    at Array.map (native)
    at IOSession.Session.mapDefinitionInfoLocations (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:118483:36)
    at IOSession.Session.getDefinitionAndBoundSpan (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:118511:40)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:117943:61)
    at /home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:119442:88
    at IOSession.Session.executeWithRequestId (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:119433:28)
    at IOSession.Session.executeCommand (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:119442:33)
    at IOSession.Session.onMessage (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:119462:35)
    at Interface.<anonymous> (/home/andy/.nvm/versions/node/v10.5.0/lib/node_modules/typescript/lib/tsserver.js:120735:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

I get this error when the build is slightly out-of-date. May not be possible to get a right answer here, but we should give up instead of crashing.

### PR DESCRIPTION
**Pull request by weswigham**
To allow the underlying file to drift out of date with the sourcemap without a crash. (This means declaration maps get more inaccurate the longer it's been since the sourcemap was updated)

As the `TODO` mentions, in an ideal world, I think we track edits to the sourcemapped file between when the sourcemap was generated and when we request positions in that file, and apply those edits to the linemap we generate for the mappings and the positions we generate from it; but I don't think we have much in place to do that efficiently right now (since it would require monitoring a file we otherwise wouldn't be looking at).

Fixes #25844

### CODE REVIEW

File: src/compiler/scanner.ts [hunk 1]
```diff
@@ -342,12 +342,23 @@ namespace ts {
...
     /* @internal */
-    export function computePositionOfLineAndCharacter(lineStarts: ReadonlyArray<number>, line: number, character: number, debugText?: string): number {
+    export function getPositionOfLineAndCharacterWithEdits(sourceFile: SourceFileLike, line: number, character: number): number {
+        return computePositionOfLineAndCharacter(getLineStarts(sourceFile), line, character, sourceFile.text, /*allowEdits*/ true);
+    }
+
+    /* @internal */
+    export function computePositionOfLineAndCharacter(lineStarts: ReadonlyArray<number>, line: number, character: number, debugText?: string, allowEdits?: true): number {
         if (line < 0 || line >= lineStarts.length) {
             Debug.fail(`Bad line number. Line: ${line}, lineStarts.length: ${lineStarts.length} , line map is correct? ${debugText !== undefined ? arraysEqual(lineStarts, computeLineStarts(debugText)) : "unknown"}`);
```
Comment (sheetalkamat) [inline src/compiler/scanner.ts]: I think you would need to allow this too ?

Comment (weswigham) [reply src/compiler/scanner.ts]: Mmm, it's probably a good idea to - more than just columns and end position can become out of date, so you're probably right.

Comment (weswigham) [reply src/compiler/scanner.ts]: Clamped.
