### PR TITLE
Fix expando handling in getTypeReferenceType

### LINKED ISSUE #34707: JSDoc type reference resolves incorrectly if checked before the constructor function it refers to
This issue tracks a better fix to https://github.com/microsoft/TypeScript/issues/34685, which just restores the old code for 3.7. See the [discussion from the fix](https://github.com/microsoft/TypeScript/pull/34706) for detail. The relevant part is excerpted here:

> getTypeReferenceType should instead detect a function-prototype merge, cause it to happen, and then run the rest of its code instead of relying on try-again logic at the very end.

### PR DESCRIPTION
**Pull request by sandersn**
getExpandoSymbol looks for the initialiser of a symbol when it is an expando value (IIFEs, function exprs, class exprs and empty object literals) and returns the symbol.

Previously, however, it returned the symbol of the initialiser without merging with the declaration symbol itself. This missed, in particular, the prototype assignment in the following pattern:

```js
var x = function x() {
  this.y = 1
}
x.prototype = {
  z() { }
}

/** @type {x} */
var xx;
xx.z // missed!
```

getJSDocValueReference had weird try-again code that relied on calling getTypeOfSymbol, which *does* correctly merge the symbols. This PR re-removes that code and instead makes getExpandoSymbol call mergeJSSymbols itself.

Fixes #34707

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -24997,7 +25001,7 @@ namespace ts {
         }
 
         function mergeJSSymbols(target: Symbol, source: Symbol | undefined) {
-            if (source && (hasEntries(source.exports) || hasEntries(source.members))) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: turns out we need to merge just for the flags sometimes.

File: tests/cases/conformance/jsdoc/jsdocTypeReferenceToMergedClass.ts [hunk 2]
```diff
@@ -3,14 +3,12 @@
 // @allowJs: true
 // @checkJs: true
 
-// @Filename: test.js
```
Comment (sandersn) [inline tests/cases/conformance/jsdoc/jsdocTypeReferenceToMergedClass.ts]: this is now a single-file repro. It is still written in such a way that `function wp` is checked *after* `p.isServiceProject`.
