### PR TITLE
A merged interface with an inherited member should satisfy an abstract base class member

### LINKED ISSUE #31905: Declaration merging of ancestor abstract types broken
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** Declaration interface abstract

## Background on usecase
For a project that requires obfuscation via closure compiler we avoid using class properties. This avoids the incompatibilities of the emitted code and closure's property mangling.

To workaround this issue, we define class properties via declaration merging and mixin the property declarations via `Object.defineProperties`

## Problem
The problem is around abstract base classes with abstract members that are mixed in.  Declaration merging fails to satisfy abstract members when the member comes from an ancestor in the interface hierarchy.

**Code**

```ts
abstract class BaseClass {
    abstract bar: number;
}

interface IGetters {
    bar: number;
}

class Broken extends BaseClass {

}
//declaration merging should satisfy abstract bar
interface Broken extends IGetters{}

class Works extends BaseClass{ }

//this works if defined inline
interface Works{
    bar: number;
}

```

**Expected behavior:**
The declaration merging to satisfy all abstract members present.
**Actual behaviour:**
Compile time error:
```sh
Non-abstract class 'Broken' does not implement inherited abstract member 'bar' from class 'BaseClass'.
```
**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=abstract%20class%20BaseClass%20%7B%0A%20%20%20%20abstract%20bar%3A%20number%3B%0A%7D%0A%0Ainterface%20IGetters%20%7B%0A%20%20%20%20bar%3A%20number%3B%0A%7D%0A%0Aclass%20Broken%20extends%20BaseClass%20%7B%0A%0A%7D%0A%2F%2Fdeclaration%20merging%20should%20satisfy%20abstract%20bar%0Ainterface%20Broken%20extends%20IGetters%7B%7D%0A%0A%0Aclass%20Works%20extends%20BaseClass%7B%20%7D%0A%0A%2F%2Fthis%20works%20if%20defined%20inline%0Ainterface%20Works%7B%0A%20%20%20%20bar%3A%20number%3B%0A%7D%0A
**Related Issues:**

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #31905

I kind of expected this to be fixed by a single insertion of `getMergedSymbol` somewhere, but it seems that `resolveObjectTypeMembers` (which is called by `getPropertyOfType`), when copying members from base types, just skips over any member with the same name as one that has already been resolved. In the linked issue / test case, the `abstract BaseClass` is closer than `IGetters`, so its members get copied to the type, and then when `IGetters`’ members get copied, it’s a no-op because `bar` already exists. So—is there an existing function that says “get me all the symbols that represent this property,” rather than just the closest?

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -29331,60 +29331,71 @@ namespace ts {
...
                             }
                         }
-                    }
-                    else {
-                        // derived overrides base.
-                        const derivedDeclarationFlags = getDeclarationModifierFlagsFromSymbol(derived);
-                        if (baseDeclarationFlags & ModifierFlags.Private || derivedDeclarationFlags & ModifierFlags.Private) {
-                            // either base or derived property is private - not override, skip it
-                            continue;
-                        }
```
Comment (andrewbranch) [inline src/compiler/checker.ts]: This diff is really wonky if you don’t have “Hide whitespace changes” turned on.

**Comment by andrewbranch** [comment]
@typescript-bot test this

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -29331,60 +29331,71 @@ namespace ts {
...
+                if (derived === base) {
+                    // derived class inherits base without override/redeclaration
+
+                    const derivedClassDecl = getClassLikeDeclarationOfSymbol(type.symbol)!;
+
+                    // It is an error to inherit an abstract member without implementing it or being declared abstract.
+                    // If there is no declaration for the derived class (as in the case of class expressions),
+                    // then the class cannot be declared abstract.
+                    if (baseDeclarationFlags & ModifierFlags.Abstract && (!derivedClassDecl || !hasModifier(derivedClassDecl, ModifierFlags.Abstract))) {
+                        // getPropertyOfObjectType will return a single symbol even if the property can be found
```
Comment (sandersn) [inline src/compiler/checker.ts]: I think this comment could be trimmed down if you focus on what is does rather than how/how you detect it.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -29331,60 +29331,71 @@ namespace ts {
...
+                        // on multiple declarations, so it’s possible for derived === base to be true even when
+                        // another base type introduced from declaration merging to contain the property as well,
+                        // which should satisfy the abstract member requirement.
+                        for (const otherBaseType of getBaseTypes(type)) {
+                            if (otherBaseType === baseType) continue;
+                            const baseSymbol = getPropertyOfObjectType(otherBaseType, base.escapedName);
+                            const derivedElsewhere = baseSymbol && getTargetSymbol(baseSymbol);
```
Comment (weswigham) [inline src/compiler/checker.ts]: Shouldn't this be
```suggestion
                            const derivedElsewhere = baseSymbol && getTargetSymbol(baseSymbol) || baseSymbol;
```

I just feel like `baseSymbol` might not always be an instantiated symbol (though it often is since a type reference in a base expression is pretty much always instantiated with a `this` type parameter, which forces symbol instantiation).

Comment (andrewbranch) [reply src/compiler/checker.ts]: I’m not 100% sure what that means... can you think of a test case that would show this? (Mostly so I can see it happen and internalize what you’re talking about.)

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -29331,60 +29331,71 @@ namespace ts {
 
                 Debug.assert(!!derived, "derived should point to something, even if it is the base class' declaration.");
 
-                if (derived) {
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply src/compiler/checker.ts]: Basically; it briefly confused me why there wasn’t an else, and then I looked above and realized it can’t happen.

File: src/compiler/checker.ts (hunk 3 above)
Comment (andrewbranch) [reply src/compiler/checker.ts]: @weswigham oh, I get what you’re saying now. But `getTargetSymbol` returns its argument if the symbol isn’t an instantiated symbol:

```ts
function getTargetSymbol(s: Symbol) {
  // if symbol is instantiated its flags are not copied from the 'target'
  // so we'll need to get back original 'target' symbol to work with correct set of flags
  return getCheckFlags(s) & CheckFlags.Instantiated ? (<TransientSymbol>s).target! : s;
}
``

Comment (weswigham) [reply src/compiler/checker.ts]: Oh, haaaaaah, so it already does that, duh.
