### PR TITLE
  Sort the paths for module specifier by closeness to importing file path

### LINKED ISSUE #32970: Type resolution in linked packages
This is essentially a duplicate issue however there has been no response on the existing issues which have been incorrectly closed so I am opening again. 

Related issues:
https://github.com/microsoft/TypeScript/issues/29221
https://github.com/microsoft/TypeScript/issues/29808

Merged PR which hasn't resolved the issue:
https://github.com/microsoft/TypeScript/pull/31571

Problem occurs when using `yarn link` for development purposes.
Window 10 Pro v1903
Typescript 3.5.3
yarn 1.17.3

I've created a repro and described steps over on #29808 but basic steps are below

If you clone https://github.com/simonfox/repro-plugin-one and https://github.com/simonfox/repro-plugin-two and run `yarn` for both. Then run `yarn link` in plugin two root, and then link one to the local two with `yarn link plugin-two` from one. Then you will see the issue in src/features/feature-one/actions.ts (you may need to reload the VS Code window after linking).

This results in ` error TS2742: The inferred type of 'actions' cannot be named without a reference to 'drive-common/node_modules/typescript-fsa'. This is likely not portable. A type annotation is necessary.`

image

**UPDATE** Should explicitly mention that this is in typings generation. With `"declaration": false` this error does not occur.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #32970

This uses #33566 to baseline `tsc --d`
Also added way to show redirects when listing files..

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@andrewbranch Not sure if its needed or not, since that kind of also iterates over result from different symbols..

File: tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js [hunk 1]
```diff
@@ -57,5 +57,8 @@ Object.defineProperty(exports, "__esModule", { value: true });
 __export(require("./keys"));
 
 
+//// [keys.d.ts]
+import { MetadataAccessor } from "@raymondfeng/pkg2";
+export declare const ADMIN: MetadataAccessor<boolean, import("../../pkg1/dist").IdType>;
```
Comment (sheetalkamat) [inline tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js]: I am not sure if this is better or not.. 
cc: @weswigham @DanielRosenwasser @RyanCavanaugh

Comment (weswigham) [reply tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js]: It's probably not... I mean, technically it's correct, but when your code is seen in a structure like this (monorepo-y), you're not supposed to access sibling packages with a relative path, since the packages won't be siblings when shipped... The error was good in this case, since it called out that your types depended on a package you didn't directly depend on, which meant you needed to fix it in some way. Like this, it's.... Eck.

Comment (sheetalkamat) [reply tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js]: Turns out we resolve that only because of how these tests run (all the sources are included irrespective of tsconfig file) when I add test using the tsc baseline I retain the error so should be ok? appending that test as a separate commit for reference 91c66a0

Comment (sheetalkamat) [reply tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js]: Ping So this PR is good to go?

Comment (weswigham) [reply tests/baselines/reference/declarationEmitReexportedSymlinkReference3.js]: I guess, yeah.

File: tests/baselines/reference/tsc/declarationEmit/initial-build/when-same-version-is-referenced-through-source-and-another-symlinked-package.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
+//// [/lib/initial-buildOutput.txt]
+/lib/tsc -p src/plugin-one --listFiles
+/lib/lib.d.ts
+/src/plugin-one/node_modules/typescript-fsa/index.d.ts
+/src/plugin-one/action.ts
+/src/plugin-one/node_modules/plugin-two/node_modules/typescript-fsa/index.d.ts -> /src/plugin-one/node_modules/typescript-fsa/index.d.ts
```
Comment (weswigham) [inline tests/baselines/reference/tsc/declarationEmit/initial-build/when-same-version-is-referenced-through-source-and-another-symlinked-package.js]: So, I didn't notice it before, but isn't `listFiles` consumed by some VS MSBuild API, and isn't this chance to include mappings with `->` probably going to break it?

Comment (weswigham) [reply tests/baselines/reference/tsc/declarationEmit/initial-build/when-same-version-is-referenced-through-source-and-another-symlinked-package.js]: cc ... @uniqueiniquity  ?

**Comment by ericmdantas** [comment]
Apparently the bug still occurs. See #32970.
