### PR TITLE
fix(51017): Make lineText in the references response opt-out

### LINKED ISSUE #51017: Make `lineText` in the `references` response opt-out
@navya9singh noticed that the latest version of VS Code doesn't actually consume it, so it's just making the response much longer for no reason.  We have to keep it for back compat, but let's add a `UserPreference` to allow VS Code to opt out.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51017

### CODE REVIEW

File: src/testRunner/unittests/tsserver/getFileReferences.ts [hunk 1]
```diff
@@ -54,5 +54,28 @@ namespace ts.projectSystem {
 
             assert.deepEqual(response, expectResponse);
         });
+
```
Comment (amcasey) [inline src/testRunner/unittests/tsserver/getFileReferences.ts:57]: We've been moving to baseline tests for FAR.  Would you mind adding one of those instead/as well?

File: src/server/protocol.ts [hunk 2]
```diff
@@ -3478,6 +3478,8 @@ namespace ts.server.protocol {
         readonly includeInlayFunctionLikeReturnTypeHints?: boolean;
         readonly includeInlayEnumMemberValueHints?: boolean;
         readonly autoImportFileExcludePatterns?: string[];
+
+        readonly disableLineTextInReferences?: boolean;
```
Comment (amcasey) [inline src/server/protocol.ts:3482]: I don't think we have a firm convention, but I think we usually use positive names (includeX) and then (potentially) treat `undefined` as the default value, rather than fals-y.  @DanielRosenwasser or @andrewbranch might have thoughts?  It's a little hard to find a precedent because we usually opt in to doing, rather than not doing, things.

**Review by amcasey — APPROVED** [review]
Some nits, but looks correct to me.

File: src/server/protocol.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/server/protocol.ts:3482]:
```ts
includeLineTextInReferences
```
?

Comment (amcasey) [reply src/server/protocol.ts:3482]: That sounds good to me, but I'd really like to hear from someone else so it's not just my intuition driving the change.

File: src/testRunner/unittests/tsserver/getFileReferences.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/testRunner/unittests/tsserver/getFileReferences.ts:57]: Do you mean to change `assert.deepEqual` to `Harness.Baseline.runBaseline`?

Comment (amcasey) [reply src/testRunner/unittests/tsserver/getFileReferences.ts:57]: `verify.baselineFindAllReferences`

**Review by mjbvz — APPROVED** [review]

File: src/testRunner/unittests/tsserver/getFileReferences.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/testRunner/unittests/tsserver/getFileReferences.ts:57]: Do you mean this [`baselineFindAllReferences`](https://github.com/microsoft/TypeScript/blob/d5f5c6d61e06717613286546f568e80c4a8775b4/tests/baselines/reference/findAllRefsExportDefaultClassConstructor.baseline.jsonc#L33-L46) test? 

https://github.com/microsoft/TypeScript/blob/58bae8db69b275a3efa57b14b486778c55185552/src/harness/fourslashImpl.ts#L1152

https://github.com/microsoft/TypeScript/blob/c18791ccf165672df3b55f5bdd4a8655f33be26c/src/services/types.ts#L490

https://github.com/microsoft/TypeScript/blob/c18791ccf165672df3b55f5bdd4a8655f33be26c/src/services/types.ts#L1076-L1079

https://github.com/microsoft/TypeScript/blob/c18791ccf165672df3b55f5bdd4a8655f33be26c/src/services/types.ts#L1081-L1083

https://github.com/microsoft/TypeScript/blob/c18791ccf165672df3b55f5bdd4a8655f33be26c/src/services/types.ts#L910-L913

Comment (amcasey) [reply src/testRunner/unittests/tsserver/getFileReferences.ts:57]: Interesting.  You might need to put it in the server fourslash tests (they look the same but behave differently - in particular, they cover session.ts).  When I may a dummy version of this change (always drop), it broke a bunch of baselines - that might be an easy way to find them.

Comment (a-tarasyuk) [reply src/testRunner/unittests/tsserver/getFileReferences.ts:57]: I've checked `fourslash`/`fourslash/server`, and it seems that `baselineFindAllReferences` doesn't cover `session.ts`.

>  it broke a bunch of baselines - that might be an easy way to find them.

Baseline changes related to [/unittests/tsserver/projectReferences](https://github.com/microsoft/TypeScript/blob/main/src/testRunner/unittests/tsserver/projectReferences.ts), which uses `baselineTsserverLogs`.

Comment (amcasey) [reply src/testRunner/unittests/tsserver/getFileReferences.ts:57]: Huh, I guess I misremembered.  Sorry about that.

File: src/server/protocol.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/server/protocol.ts:3482]: I think your intuition is right, except for the fact that dropping something information is out of the norm. I can go either way on this.

Comment (amcasey) [reply src/server/protocol.ts:3482]: @mjbvz seems happy and I don't expect anyone else to ever set it. 😆 

I'm fine with leaving it.  Thanks for your patience, @a-tarasyuk.

File: src/server/protocol.ts [hunk 3]
```diff
@@ -1163,7 +1163,7 @@ namespace ts.server.protocol {
          * to show text of reference line (the server already has
          * loaded the referencing files).
          */
-        lineText: string;
+        lineText?: string;
```
[the remark this answers is not in the document]
Comment (amcasey) [reply src/server/protocol.ts:1166]: I imagine you were probably waiting to resolve the name question, but now I think we can go ahead and add a comment.

**Review by amcasey — APPROVED** [review]
Still LGTM

**Comment by amcasey** [comment]
Awesome!  Thanks again!
