### PR TITLE
Fix completions of exports elsewhere in same file

### LINKED ISSUE #43289: Completions broken in module.exports object literal
# Bug Report

### 🔎 Search Terms

completions module exports

### 🕗 Version & Regression Information

- This changed between versions 4.0.5 and 4.1.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5&useJavaScript=true#code/GYVwdgxgLglg9mABMOcAUBKRBvAvgKFElgUQCMBDAJ0xwPwFs4ATEAGwFMA6DgDwAc4VKAGdEAXhz5EM5KgA002WUQB6VYgA8AWm2IoAT34dEAcgqnEQxNCpsA1CP4UIHfLgDc+IA)

### 💻 Code

```ts
function foo() {}
function bar() {}

module.exports = {
    foo,
    b // <-- type 'a' or ctrl+space
};
```

### 🙁 Actual behavior

Completions are “self-fulfilling”—you get a completion only for the partial identifier you’ve already typed so far, blocking out even VS Code’s “file identifiers” completions. See also #35709 fixing similar symptoms.

### 🙂 Expected behavior

You should get completions for in-scope identifiers via #41539. (In TS 4.0 and prior, you would get no completions, which was better than the current behavior, because at least VS Code would give you file identifiers.)

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #43289, along with another bug I found on the way:

```ts
module.exports = { a/**/ } // has a completion for itself
```

and

```ts
const c = 0;
export { c as something };
export * as somethingElse from "./other";

s/**/ // has completions for 'something' and 'somethingElse'
```

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -25106,8 +25106,8 @@ namespace ts {
         }
 
         function getContextualTypeForThisPropertyAssignment(binaryExpression: BinaryExpression, kind: AssignmentDeclarationKind): Type | undefined {
-            if (!binaryExpression.symbol) return getTypeOfExpression(binaryExpression.left);
-            if (binaryExpression.symbol.valueDeclaration) {
+            if (!binaryExpression.symbol && kind !== AssignmentDeclarationKind.ModuleExports) return getTypeOfExpression(binaryExpression.left);
```
Comment (sandersn) [inline src/compiler/checker.ts:25109]: Why can `kind` ever be `ModuleExports` in a function named getContextualTypeFor**ThisProperty**Assignment? Maybe the caller of this function needs the fix instead.

Also I can't figure out which test caused this change.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -38897,6 +38897,17 @@ namespace ts {
                     });
                 }
             }
+
+            function copyExportedSymbols(source: SymbolTable, meaning: SymbolFlags): void {
```
Comment (sandersn) [inline src/compiler/checker.ts:38901]:
```suggestion
            function copyNonExportedSymbols(source: SymbolTable, meaning: SymbolFlags): void {
```

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:38901]: Uh, this is only called for `sourceFileOrModuleDeclarationSymbol.exports`

File: src/compiler/checker.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:25109]: This was causing `module.exports = { ... }` to be contextually typed by its own initializer. I think the function probably just needs to be renamed to `getContextualTypeForSpecialPropertyAssignment`, but I’ll take another look.

Comment (andrewbranch) [reply src/compiler/checker.ts:25109]: Oof, this bug actually applies to [every kind of special property assignment](https://www.typescriptlang.org/play?useJavaScript=true#code/LYewJgrgNgpgdDAHgBxAJwC4GcAEBeHAbwCgcycBDAegCoariBfY4pVTLOAMxBHyNLlqdBs2JcIAOwDGGAJYhJOAGIAKAJQDyODAAs5nAEZQKu-iW3bh9QWUYBuJi2Xde525Vo2xL5GhAYAQCeyDDuVl6iznB+AcGhcIjhQpFOxEA).

The fix targeted by this particular change probably does need to move up a level.

File: src/compiler/checker.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:38901]: Ah, I understand the confusion based on the apparent disagreement between the name and the implementation of the function. The issue is that `a` and `b` are both in `exports`, but their local visibility is quite different:

```ts
export const a = 0;
export { a as b };
```

That does suggest some ideas for a better name 👍

**Comment by andrewbranch** [comment]
@sandersn I realized I couldn’t really fix the primary bug (#43289) without addressing the contextual typing thing head-on, which I think I’ve done now. `getContextualTypeForThisPropertyAssignment` is now only used for `this` (and aliased-`this`) property assignments. We now group `AssignmentDeclarationKind.ExportsProperty`, `.Prototype`, `.PrototypeProperty`, and `.ModuleExports` together as being the simpler cases where they can have a contextual type _only_ via a JSDoc type annotation, whereas `.Property` and `.ThisProperty` might be new declarations, might be immediately annotated with JSDoc, or might have a contextual type from the original declaration of the object. Some of the simpler cases were incorrectly being fed through that more complicated logic.

**Comment by andrewbranch** [comment]
@typescript-bot user test this

**Review by RyanCavanaugh — APPROVED** [review]

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -25081,9 +25080,15 @@ namespace ts {
...
                     }
+                case AssignmentDeclarationKind.ExportsProperty:
+                case AssignmentDeclarationKind.Prototype:
+                case AssignmentDeclarationKind.PrototypeProperty:
+                    let valueDeclaration = binaryExpression.left.symbol?.valueDeclaration;
+                    // falls through
                 case AssignmentDeclarationKind.ModuleExports:
-                case AssignmentDeclarationKind.ThisProperty:
-                    return getContextualTypeForThisPropertyAssignment(binaryExpression, kind);
+                    valueDeclaration ||= binaryExpression.symbol?.valueDeclaration;
```
Comment (sandersn) [inline src/compiler/checker.ts:25089]: `switch` scope rules are boooooooooo

**Review by sandersn — APPROVED** [review]
