### PR TITLE
Compute writeType from set accessors for union and intersection properties

### LINKED ISSUE #45376: Union of variant setters uses getter type for assignment
# Bug Report

### 🔎 Search Terms

variant accessor setter union

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because: variant accessors only landed in 4.3

### ⏯ Playground Link

[Example from below](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDyB2BTaBvAUNaBzRAXaADgE4D2BAFAJQBc0EuRAlvFqtEXgK5HzQBEfANzQAvhjp5CpChFr0mLaAB9o8TgFsARoiKU2YsWlCQYAFQDuJVOJz5iZKnIbNWKdlx78ho8REn2ZJwVWFTUtHT03AzQ0ABNEYw5oYBJ4emhOAEZaBEQlCxJBNCyAOgDoAF5oABYAJiKgA)

### 💻 Code

```ts
class One {
  get prop(): string { return ""; }
  set prop(s: string | number) { }
}

class Two {
  get prop(): string { return ""; }
  set prop(s: string | number) { }
}

declare const u1: One|Two;
u1.prop = 42; //Type 'number' is not assignable to type 'string'.(2322)
```

I didn't include it in the playground, but behavior is the same for `class` or `interface`.

### 🙁 Actual behavior

Assignment of number is flagged as an error, even though both sides of the union allow assignment of a number.

### 🙂 Expected behavior

Assignment should not be flagged.

----

Originally [reported by @ws93](https://github.com/microsoft/TypeScript/pull/42425#issuecomment-894715295)

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #45376

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -12149,6 +12185,9 @@ namespace ts {
                                 }
                             }
                         }
+                        if (prop.flags & SymbolFlags.SetAccessor) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:12188]: I guess this check is insufficient if `prop` itself is a union or intersection property with a `writeType` derived from one or more set accessors unless we propagate this flag to the union/intersection property. I initially tried an approach where we propagate `Accessor` flags and it didn’t seem to mess anything up, but later I changed my approach for other reasons and it seemed that propagation was no longer necessary, not thinking of the nested unions/intersections case until I published the PR. The other option would be to check if this property does have a cached writeType or deferred write type similar to `getWriteTypeOfSymbol` above. Thoughts?

Comment (weswigham) [reply src/compiler/checker.ts:12188]: Hm, I think we'd rather not expand how many places need to explicitly handle deferred Union calculation or other cached types; so it's probably better to propagate the flags if possible.

Comment (andrewbranch) [reply src/compiler/checker.ts:12188]: > if `prop` itself is a union or intersection property

@weswigham uh dumb question, but any idea how to construct such a test? Union normalization is thwarting my very simple attempts.

Comment (weswigham) [reply src/compiler/checker.ts:12188]: Ah, I think you might manage something by using the constraint of a conditional type to create a denormalized union or intersection? It's probably not particularly easy.

Comment (andrewbranch) [reply src/compiler/checker.ts:12188]: In that case, maybe this check is fine?

Comment (weswigham) [reply src/compiler/checker.ts:12188]: Couldn't we just always `getWriteTypeOfSymbol` (which should hopefully guarantee handling recursive processing of transient/deferred symbols) and assign the `writeType`-related fields any time they're different than the non-writing fields? Something like
```ts
const writeType = getWriteTypeOfSymbol(prop);
if (writeTypes || writeType !== type) {
  writeTypes = append(!writeTypes ? propTypes.slice() : writeTypes, writeType);
}
propTypes.push(type);
```
thus avoiding the upfront check for an accessor entirely?

Comment (andrewbranch) [reply src/compiler/checker.ts]: Yeah that works, thanks

**Review by weswigham — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9702,6 +9702,41 @@ namespace ts {
             return links.type;
         }
 
+        function getWriteTypeOfSymbolWithDeferredType(symbol: Symbol): Type | undefined {
+            const links = getSymbolLinks(symbol);
+            if (!links.writeType && links.deferralWriteConstituents) {
+                Debug.assertIsDefined(links.deferralParent);
+                Debug.assertIsDefined(links.deferralConstituents);
+                links.writeType = links.deferralParent.flags & TypeFlags.Union ? getUnionType(links.deferralWriteConstituents) : getIntersectionType(links.deferralWriteConstituents);
```
Comment (whzx5byb) [inline src/compiler/checker.ts:9710]: Shouldn't the write type of a union be resolved into an intersection type? Just like the way mentioned in https://github.com/microsoft/TypeScript/pull/30769

Comment (andrewbranch) [reply src/compiler/checker.ts:9710]: If you come up with a code example that doesn’t work the way you expect, feel free to file an issue.

Comment (whzx5byb) [reply src/compiler/checker.ts:9710]: > If you come up with a code example that doesn’t work the way you expect, feel free to file an issue.

Please have a look at the unsound behavior described in https://github.com/microsoft/TypeScript/issues/50142. [A comment](https://github.com/microsoft/TypeScript/issues/50142#issuecomment-1203042758) indicates that it should be treated using the same rule of https://github.com/microsoft/TypeScript/pull/30769.

I'm not quite sure but I guess it could have relation to this PR, where the write type of a union is not resolved into an intersection, but a union.

Comment (fatcerberus) [reply src/compiler/checker.ts:9710]: FWIW there’s a second complication in play in #50142: subtype reduction.  Subtype reduction means that `NullableProp | NonNullableProp` is likely to be reduced to just the former, making #30769 a moot point.
