### PR TITLE
Reorder LKG tasks so protocol build isn't using partial LKG

### LINKED ISSUE #40716: Nightly publishing is currently broken because our LKG fails
See [this log](https://github.com/microsoft/TypeScript/runs/1153500708?check_suite_focus=true). Specifically, the `buildProtocol` script (which is only executed during LKG) can't handle the `instrinsic` types. I think the issue may just be build ordering - the script runs as part of `produceLKG`, uses the `lib` version of TS, but after the `lib` is updated - so the new `lib` library `.d.ts` files are in place, but _not_ the accompanying source code.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #40716

### CODE REVIEW

File: scripts/produceLKG.ts [hunk 1]
```diff
@@ -15,10 +15,10 @@ async function produceLKG() {
     await copyLibFiles();
     await copyLocalizedDiagnostics();
     await copyTypesMap();
-    await buildProtocol();
     await copyScriptOutputs();
     await copyDeclarationOutputs();
     await writeGitAttributes();
+    await buildProtocol();
```
Comment (DanielRosenwasser) [inline scripts/produceLKG.ts:21]: I would swap these two lines just to group these closer by relevance.

```suggestion
    await buildProtocol();
    await writeGitAttributes();
```

**Review by DanielRosenwasser — APPROVED** [review]
I'd swap the lines, but other than that looks good.

File: scripts/produceLKG.ts (hunk 1 above)
Comment (weswigham) [reply scripts/produceLKG.ts:21]: Neither of those two truly have any relevance to the rest, their order doesn't matter, relatively speaking~ All the others are just grouped `copy`s.
