### PR TITLE
fix(41405): No 'async' conversion hint when using reference to class method as parameter to .then()

### LINKED ISSUE #41405: No 'async' conversion hint when using reference to class method as parameter to .then()
*TS Template added by @mjbvz*

**TypeScript Version**: 4.2.0-dev.20201103

**Search Terms**
- suggestion
- refactor
- quick fix

---

- VSCode Version:  Version: 1.50.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. See StackBlitz: https://stackblitz.com/edit/typescript-qv6hkq
Two scenarios, file level functions and class methods passed to `.then()`.
   - File level functions: No difference between `then(doSomething)` and `then(() => doSometing())`
   - Class level methods show difference:
      - No hint: `then(this.doSomething)`
      - With hint: `then(() => this.doSometing())`
2. Code of stackblitz:
```js
class SomeClass {
  doSomething() {}

  // Shows hint to convert to async
  usingFunctionExpression() {
    return Promise.resolve().then(() => this.doSomething());
  }

  // No hint   <------------------------------------------- expected to see a hint.
  usingFunctionReference() {
    return Promise.resolve().then(this.doSomething);
  }
}

function doSomething() {}

// Shows hint to convert to async
function usingFunctionExpression() {
  return Promise.resolve().then(() => doSomething());
}

// Shows hint to convert to async
function usingFunctionReference() {
  return Promise.resolve().then(doSomething);
}
```

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41405

### CODE REVIEW

File: src/services/suggestionDiagnostics.ts [hunk 1]
```diff
@@ -171,16 +171,30 @@ namespace ts {
...
             case SyntaxKind.NullKeyword:
-            case SyntaxKind.Identifier: // identifier includes undefined
                 return true;
+            case SyntaxKind.Identifier:
+            case SyntaxKind.PropertyAccessExpression: {
+                const symbol = checker.getSymbolAtLocation(arg);
+                if (!symbol) {
+                    return false;
+                }
+                if (checker.isUndefinedSymbol(symbol)) {
```
Comment (sandersn) [inline src/services/suggestionDiagnostics.ts:189]: how could a property access have the symbol of `undefined`? If it can't, why are some identifiers now not fixable?

File: src/services/suggestionDiagnostics.ts [hunk 2]
```diff
@@ -171,16 +171,30 @@ namespace ts {
...
+                    return true;
+                }
+                const declaration = first(skipAlias(symbol, checker).declarations);
+                if (declaration) {
+                    return isFunctionLikeDeclaration(hasInitializer(declaration) && declaration.initializer ? declaration.initializer : declaration);
```
Comment (sandersn) [inline src/services/suggestionDiagnostics.ts:194]: should this maybe be `skipAlias(symbol, checker).declarations.some(d => isFunctionLikeDeclaration(...`?

Comment (sandersn) [reply src/services/suggestionDiagnostics.ts:194]: nitpick: this kind of reads backwards to me; it would be easier to read as `isFunctionLike(declaration) || isFunctionLike(hasInitializer(declaration) && declaration.initializer)`, although that last bit doesn't type check I think.

If it's too hard to re-order, don't worry about it.

**Review by sandersn — CHANGES_REQUESTED** [review]
Couple of questions and one optional suggestion.

File: src/services/suggestionDiagnostics.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/suggestionDiagnostics.ts]: `property access` cannot be, however, Identifier can be., `case SyntaxKind.Identifier:` was used to identify `undefined`, which I replaced by `checker.isUndefinedSymbol(symbol))` (maybe there is better solution), because the following code can be converted to an async function

```ts
function f() {
    return fetch('https://typescriptlang.org').then(undefined);
}
```

However, `Identifier` should refer to function declaration, the following code should not be converted to an async function

```ts
const ref = 1 // or undefined
function f1() {
    return fetch('https://typescriptlang.org').then(ref);
}
```

That's because the following code is not valid 

```ts
function f2() {
    return fetch('https://typescriptlang.org').then(1);
}
```

If identifier/prop access refers to a function, the function can be converted to an async function

```ts
const ref = function ()  {}
function f1() {
    return fetch('https://typescriptlang.org').then(ref);
}
```

or 

```ts
const ref = { x: function ()  {} }
function f1() {
    return fetch('https://typescriptlang.org').then(ref.x);
}
```

@sandersn Does that make sense?

File: src/services/suggestionDiagnostics.ts [hunk 3]
```diff
@@ -171,16 +171,24 @@ namespace ts {
...
-            case SyntaxKind.Identifier: // identifier includes undefined
                 return true;
+            case SyntaxKind.Identifier:
+            case SyntaxKind.PropertyAccessExpression: {
+                const symbol = checker.getSymbolAtLocation(arg);
+                if (!symbol) {
+                    return false;
+                }
+                return checker.isUndefinedSymbol(symbol) ||
+                    some(skipAlias(symbol, checker).declarations, d => isFunctionLike(d) || hasInitializer(d) && !!d.initializer && isFunctionLike(d.initializer));
```
Comment (a-tarasyuk) [inline src/services/suggestionDiagnostics.ts:190]: Is it ok for you?

File: src/services/suggestionDiagnostics.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/suggestionDiagnostics.ts]: @sandersn done

Comment (a-tarasyuk) [reply src/services/suggestionDiagnostics.ts]: Changed.

**Review by sandersn — APPROVED** [review]
