### PR TITLE
Fixed a false positive "await has no effect on the type" diagnostic with mixed generic union

### LINKED ISSUE #50832: False positive "await has no effect on the type" diagnostic with mixed generic union
# Bug Report

### 🔎 Search Terms

await has no effect on type, 80007

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220918#code/IYZwngdgxgBAZgV2gFwJYHsLwgJgDwAqMApgB7LEQAmIMACgE7oC2qIxeAbuqlQHwwAPjG68+ACmAAuGAQCUMAN4AoGDGAB3YKmTqA3MoC+QA)

### 💻 Code

```ts
async function fn2<T extends Promise<void> | void>(a: T) {
  await a; // reports 80007
}
```

### 🙁 Actual behavior

It reports:
> 'await' has no effect on the type of this expression.(80007)

### 🙂 Expected behavior

No problem should be reported here.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #50832

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -36923,7 +36923,7 @@ namespace ts {
                 // We only need `Awaited<T>` if `T` is a type variable that has no base constraint, or the base constraint of `T` is `any`, `unknown`, `{}`, `object`,
                 // or is promise-like.
                 if (baseConstraint ?
-                    baseConstraint.flags & TypeFlags.AnyOrUnknown || isEmptyObjectType(baseConstraint) || isThenableType(baseConstraint) :
+                    baseConstraint.flags & TypeFlags.AnyOrUnknown || isEmptyObjectType(baseConstraint) || someType(baseConstraint, isThenableType) :
```
Comment (Andarist) [inline src/compiler/checker.ts:36926]: An alternative fix would be to move `someType` to `isThenableType`:
<details>
<summary>patch</summary>

```diff
diff --git a/src/compiler/checker.ts b/src/compiler/checker.ts
index 088ba325ec..89cfb6bcae 100644
--- a/src/compiler/checker.ts
+++ b/src/compiler/checker.ts
@@ -36884,8 +36884,10 @@ namespace ts {
                 return false;
             }
 
-            const thenFunction = getTypeOfPropertyOfType(type, "then" as __String);
-            return !!thenFunction && getSignaturesOfType(getTypeWithFacts(thenFunction, TypeFacts.NEUndefinedOrNull), SignatureKind.Call).length > 0;
+            return someType(type, t => {
+                const thenFunction = getTypeOfPropertyOfType(t, "then" as __String);
+                return !!thenFunction && getSignaturesOfType(getTypeWithFacts(thenFunction, TypeFacts.NEUndefinedOrNull), SignatureKind.Call).length > 0;
+            });
         }
 
         interface AwaitedTypeInstantiation extends Type {
@@ -36923,7 +36925,7 @@ namespace ts {
                 // We only need `Awaited<T>` if `T` is a type variable that has no base constraint, or the base constraint of `T` is `any`, `unknown`, `{}`, `object`,
                 // or is promise-like.
                 if (baseConstraint ?
-                    baseConstraint.flags & TypeFlags.AnyOrUnknown || isEmptyObjectType(baseConstraint) || someType(baseConstraint, isThenableType) :
+                    baseConstraint.flags & TypeFlags.AnyOrUnknown || isEmptyObjectType(baseConstraint) || isThenableType(baseConstraint) :
                     maybeTypeOfKind(type, TypeFlags.TypeVariable)) {
                     return true;
                 }
```
</details>

That would in turn impact the other call site to this util, [here](https://github.dev/microsoft/TypeScript/blob/ed7db78106664e52f00ec646ed6a05e079f433ca/src/compiler/checker.ts#L37082-L37108) and I'm not sure if that's desirable.

**Review by sandersn — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]
