### PR TITLE
check index access for fixed length tuple

### LINKED ISSUE #5203: out of range index in a tuple magically works
``` typescript

var x : [number, number] = [1, 2];
var y = x[2]; // expected a compile error, actual ok
```

By [design](https://github.com/aleksey-bykov/by-design-script), isn't it?

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #5203

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18293,6 +18293,13 @@ namespace ts {
                 error(indexExpression, Diagnostics.A_const_enum_member_can_only_be_accessed_using_a_string_literal);
                 return errorType;
             }
+            if (isTupleType(objectType) && !objectType.target.hasRestElement && isNumericLiteral(indexExpression)) {
+                const index = +indexExpression.text;
+                const maximumIndex = length(objectType.target.typeParameters);
```
Comment (IllusionMH) [inline src/compiler/checker.ts]: Looks like there should be `length(...) - 1` to get last available index. Otherwise errors looks off by 1 and confusing.

P.S. Thank you for PR. Glad to see that this will be in TS soon. 👍

File: src/compiler/diagnosticMessages.json [hunk 2]
```diff
@@ -2437,6 +2437,10 @@
         "category": "Error",
         "code": 2732
     },
+    "Indexed access '{0}' is out of range of tuple, the maximum of index is '{1}'.": {
```
Comment (RyanCavanaugh) [inline src/compiler/diagnosticMessages.json]: Proposed phrasing

> `Index '{0}' is out-of-bounds in tuple of length {1}`

cc @DanielRosenwasser

File: src/compiler/checker.ts (hunk 1 above)
Comment (Kingwl) [reply src/compiler/checker.ts]: sorry, my fault

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -18293,6 +18293,13 @@ namespace ts {
                 error(indexExpression, Diagnostics.A_const_enum_member_can_only_be_accessed_using_a_string_literal);
                 return errorType;
             }
+            if (isTupleType(objectType) && !objectType.target.hasRestElement && isNumericLiteral(indexExpression)) {
+                const index = +indexExpression.text;
+                const maximumIndex = length(objectType.target.typeParameters) - 1;
```
Comment (IllusionMH) [inline src/compiler/checker.ts]: Sorry, I had to remove my comments as soon as @RyanCavanaugh proposed to just change error message text (which I think better solution - it handled cases with empty tuples well without special treatment).
With new message - changes that I proposed earlier only [break stuff](https://github.com/Microsoft/TypeScript/pull/26292/files#diff-e03d8ed536fc4ddafec16efc8d311149R8) 😞  and should be reverted.
