### PR TITLE
fix(41244): Wrong quote type preference detection when importHelpers are set to true

### LINKED ISSUE #41244: Wrong quote type preference detection when importHelpers are set to true
**TypeScript Version:**  4.0.3

If `importHelpers` are set to `true`, setting `quotePreference` to `"auto"` doesn't result in choosing the correct quote type e.g. when using automatic imports.

Quote type preference should be obtained using the first import, yet it's always set to single quote.

My guess is that synthetic "tslib" import added due to `importHelpers` option set to `true`, results in wrong `getQuotePreference` behavior [here](https://github.com/microsoft/TypeScript/blob/417b8a94817b7930351eb696470a7583289d91f1/src/services/utilities.ts#L1830) (it is detected as the first import, and later isn't found in the source, which results in `isStringDoubleQuoted` returning false and always getting `QuotePreference.Single`).

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41244

### CODE REVIEW

File: src/services/utilities.ts [hunk 1]
```diff
@@ -1827,7 +1827,8 @@ namespace ts {
             return preferences.quotePreference === "single" ? QuotePreference.Single : QuotePreference.Double;
         }
         else {
-            const firstModuleSpecifier = sourceFile.imports && find(sourceFile.imports, isStringLiteral);
+            const firstModuleSpecifier = sourceFile.imports &&
```
Comment (jessetrinity) [inline src/services/utilities.ts:1830]:
```suggestion
            // ignore synthetic import added when importHelpers: true 
            const firstModuleSpecifier = sourceFile.imports &&

```

**Review by jessetrinity — APPROVED** [review]
