### PR TITLE
Fix emit for nested object rest in assignment pattern

### LINKED ISSUE #43400: Nested object rest in destructuring results in code with a syntax error
# Bug Report

### 🔎 Search Terms

array object assign destructuring invalid code syntax error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210326#code/G4QwTgBAHgNBCecRwEYG4BQGD02IGUALAewFcAbAEwgAcwBLAOwBcAuCAbwCIQUBjLqwCMAXwwBtDhAB0sqBBEBdCAF4IkiLz7shCxWgh9ijAM7FyAU2nliAcwAUAKXwB5AHLSTzBo1v0AZvD2UACUIZg4eERkVLQ+bJw8-IKiGP7EkPYastLwehDE-uoaWjp6iiGGxmaW1nZOrh5ePn6B9vBhEbgEJBTUdEwJ3CCCPFwwXCiC3EKjUxMATKMCImLpmVIADOzIMrIoChBMnJr8ZSKVRqbmVjYOzu6e3kytQRy7KBfhQA)

### 💻 Code

```ts
var x, y, a, b;

// Should print: {"abc":1}
[{ ...x }] = [{ abc: 1 }]; console.log(JSON.stringify(x));

// Should print: {"abc":1}
for ([{ ...y }] of [[{ abc: 1 }]]) console.log(JSON.stringify(y));

// Should print: {"a":"a","b":{"1":"b","2":"c"}}
for ({ 0: a, ...b } in { abc: 1 }) console.log(JSON.stringify({a, b}));
```

### 🙁 Actual behavior

Compiling this with a target of `ES2017` results in code with a syntax error:

```js
"use strict";
var x, y, a, b;
// Should print: {"abc":1}
[Object.assign({}, x)] = [{ abc: 1 }];
console.log(JSON.stringify(x));
// Should print: {"abc":1}
for ([Object.assign({}, y)] of [[{ abc: 1 }]])
    console.log(JSON.stringify(y));
// Should print: {"a":"a","b":{"1":"b","2":"c"}}
for (Object.assign({ 0: a }, b) in { abc: 1 })
    console.log(JSON.stringify({ a, b }));
```

The specific syntax error is `SyntaxError: Invalid destructuring assignment target`, and happens because of the call to `Object.assign` in assignment position.

### 🙂 Expected behavior

This should result in valid code, and that code should print this:

```
{"abc":1}
{"abc":1}
{"a":"a","b":{"1":"b","2":"c"}}
```

I have reported this same issue in the past: https://github.com/microsoft/TypeScript/issues/39181#issuecomment-647989968. It must be that either the fix has regressed or the fix was incomplete.

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes the downlevel emit for object rest destructuring when nested in an array destructuring, or in the _ForInitializer_ of a `for..of` loop. This does not fix the emit for `for..in`, however, as we currently report an error for that cases.

Fixes #43400

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test faster

File: src/compiler/transformers/es2018.ts [hunk 1]
```diff
@@ -713,6 +717,32 @@ export function transformES2018(context: TransformationContext): (x: SourceFile
         return result;
     }
 
+    /**
+     * Walk an AssignmentPattern to determine if it contains object rest (`...`) syntax. We cannot rely on
+     * propagation of `TransformFlags.ContainsObjectRestOrSpread` since it isn't propagated by default in
+     * ObjectLiteralExpression and ArrayLiteralExpression since we do not know whether they belong to an
+     * AssignmentPattern at the time the nodes are parsed.
+     */
+    function containsObjectRestOrSpread(node: AssignmentPattern): boolean {
```
Comment (jakebailey) [inline src/compiler/transformers/es2018.ts:726]: This function looks like a copy/paste of `propagateAssignmentPatternFlags` (I'm sure intentionally); is there any way we can share the code, or maybe run `propagateAssignmentPatternFlags` after the fact once we know how the nodes are being used?

Comment (rbuckton) [reply src/compiler/transformers/es2018.ts:726]: We don't want to mutate transform flags on existing nodes, though I can probably move `containsObjectRestOrSpread` out to `factory/utilities.ts` and have `propagateAssignmentPatternFlags` use it.

Comment (jakebailey) [reply src/compiler/transformers/es2018.ts:726]: That sounds good enough to me!

File: src/compiler/factory/utilities.ts [hunk 2]
```diff
@@ -1742,3 +1745,29 @@ export function flattenCommaList(node: Expression) {
...
     return expressions;
 }
+
+/**
+ * Walk an AssignmentPattern to determine if it contains object rest (`...`) syntax. We cannot rely on
+ * propagation of `TransformFlags.ContainsObjectRestOrSpread` since it isn't propagated by default in
+ * ObjectLiteralExpression and ArrayLiteralExpression since we do not know whether they belong to an
+ * AssignmentPattern at the time the nodes are parsed.
+ */
+export function containsObjectRestOrSpread(node: AssignmentPattern): boolean {
```
Comment (jakebailey) [inline src/compiler/factory/utilities.ts:1755]: I think this has to be `@internal`.

**Review by jakebailey — APPROVED** [review]
