### PR TITLE
JSDoc:positional matching of destructured params

### LINKED ISSUE #19645: JsDoc annotations don't play well with arguments destructuring
**Code**

As stated in [this comment](https://github.com/Microsoft/TypeScript/issues/19268#issuecomment-341109118) (I am afraid this won't be seen since the issue is closed, hence the issue):

```js
/**
 * @param {Object} args 
 * @param {string} args.prop1
 * @param {string} args.prop2
 */
function patate({ prop1, prop2 }) {

}
```

**Expected behavior:**

Type-checking this using `--allowJs` and `--checkJs` shouldn't result in an error but rather apply the right type-annotations to the both properties.

**Actual behavior:**
The compiler raises the following error:

```
error TS8024: JSDoc '@param' tag has name 'args', but there is no parameter with that name.
```

### PR DESCRIPTION
**Pull request by sandersn**
1. When looking up tags for a parameter whose name is a binding pattern, use the index of the parameter to get the type.
2. When reporting errors for `@param` tags with no matching parameter name, do not report the error for tags whose index in the `@param` tag list matches the index of a parameter whose name is a binding pattern.

Fixes #19645 

This is a small-ish change while we figure out how to make #18832 not hurt performance in the common case of Typescript code or non-destructuring parameters.

### CODE REVIEW

**Comment by sandersn** [comment]
Perf tests show everything about the same except Angular binding, which is slower. There's no change in the binder for this PR, so it makes me think the results for Angular when testing #18832 are not valid either.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21871,6 +21871,10 @@ namespace ts {
                 // and give a better error message when the host function mentions `arguments`
                 // but the tag doesn't have an array type
                 if (decl) {
+                    const i = getJSDocTags(decl).filter(isJSDocParameterTag).indexOf(node);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Maybe `getParameterSymbolFromJSDoc` should work for binding patterns too?

Comment (sandersn) [reply src/compiler/checker.ts]: There's no symbol on a binding pattern, though, so without adding something in the binder there's no benefit.
