### PR TITLE
Fixing JSX/TSX closing tag/attribute/expression formatting

### LINKED ISSUE #3838: Support TSX/JSX formatting
Right now formatting is supported or not right.

As you see below it just removes all indentation from JSX, i would prefer that we leave jsx code out of formatting if can't be supported right now, this makes formatting completely useless in TSX files.

If i understand this correctly then typescript has formatting capability and which is being used by atom-typescript in the sample below.

Original Code
image

Formatted Code 
image

### PR DESCRIPTION
**Pull request by SaschaNaz**
Closes #3838.

- [x] Wait #4757 (now merged into master)

Current:
```typescript
let x = <div>
<div>
    </div>
    </div>

let y = <div
    className="foo"
    id={
    3
    }>
</div>
```

Fix:
```typescript
let x = <div>
    <div>
    </div>
</div>

let y = <div
    className="foo"
    id={
        3
    }>
</div>
```

### CODE REVIEW

File: src/services/formatting/formatting.ts [hunk 1]
```diff
@@ -387,7 +389,10 @@ namespace ts.formatting {
 
             let indentation = inheritedIndentation;
             if (indentation === Constants.Unknown) {
-                if (isSomeBlock(node.kind)) {
+                if (isIndentPreventedChildNode(parent.kind, node.kind)) {
```
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: i would inline the body of isIndentPreventedChildNode, 
```ts
if (parent.kind === SyntaxKind.JsxElement && child.kind === SyntaxKind.JsxClosingElement)
```
it is more readable this way.

Comment (mhegazy) [inline src/services/formatting/formatting.ts]: this is similar to closing braces and parens, maybe we should add it to get indentation in token.

Comment (mhegazy) [inline src/services/formatting/formatting.ts]: possibly move getIndentationForToken to a new helper, call it in getIndentationForToken, and from here and add support for jsx elements in it as well.. possibly give the new helper a better name as getIndentationForNode.

File: src/services/formatting/formatting.ts [hunk 2]
```diff
@@ -360,7 +360,9 @@ namespace ts.formatting {
             range: TextRange, 
             inheritedIndentation: number): number {
             
-            if (rangeOverlapsWithStartEnd(range, startPos, endPos)) {
+            if (rangeOverlapsWithStartEnd(range, startPos, endPos) ||
+                rangeContainsStartEnd(range, startPos, endPos) /* Not to miss zero-range nodes e.g. JsxText */) {
```
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: > /* Not to miss zero-range nodes e.g. JsxText */

text can not be zero-length, is there an example that would trigger this?

Comment (SaschaNaz) [inline src/services/formatting/formatting.ts]: @mhegazy I've found that this code blocks autoformatting:

```typescript
let x = <div>
<span>
</span>
</div>
```

`<span>` won't be indented because by some reason a zero-length JsxText node before JsxElement node incorrectly sets indentation value to zero. An additional `rangeContainsStartEnd` check prevents this bug.

**Comment by SaschaNaz** [comment]
I have to figure out how can I merge getIndentationForToken and isIndentPreventedChildNode. A simple merge breaks indentation here:

```typescript
let x = <div>
</div>; // works well

let y = foo
(3); // should be indented but fails
```

File: src/services/formatting/formatting.ts (hunk 1 above)
Comment (SaschaNaz) [inline src/services/formatting/formatting.ts]: @mhegazy I currently have no idea so I just inlined it. I agree that the closing node is similar to closing tokens but I think nodes and tokens are being processed with some differences by different functions so a merged helper may not really simplify the code.

File: src/services/formatting/formatting.ts (hunk 2 above)
Comment (mhegazy) [inline src/services/formatting/formatting.ts]: looks like a parser bug then.

Comment (SaschaNaz) [inline src/services/formatting/formatting.ts]: Maybe related to #4332?

Comment (SaschaNaz) [inline src/services/formatting/formatting.ts]: #4596 didn't fix this zero-length problem. CC: @vladima

**Comment by kuon** [comment]
Will this cover the following (parenthesis and newline)?

```typescript
return (
    <div>
        <div />
    </div>
);
```

If yes, perhaps adding a test for this specific case.

**Comment by SaschaNaz** [comment]
@kuon Yes it does, and I think this PR already tests that case (where JsxElement is contained in parenthesis.)

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
can you please refresh this PR, i think we are ready to go. Thanks for your patience and sorry for the delay.

**Comment by DanielRosenwasser** [comment]
Thanks @SaschaNaz!
