### PR TITLE
Avoid the double-symbol trick for enums

### LINKED ISSUE #33575: jsdoc @enum with import/export
**TypeScript Version:**  3.6.3

**Code**

This works:
```ts
/** @enum {number} */
const MyEnum = {
  a: 1,
  b: 2
};

/** @type {MyEnum} */
const v = MyEnum.b;
```

This doesn't work (`MyEnum` imported from separate file):
```ts

// my-enum.js

/** @enum {number} */
const MyEnum = {
  a: 1,
  b: 2
};

export default MyEnum;

// main.js

import MyEnum from './my-enum.js';

/** @type {MyEnum} */ // ERROR: 'MyEnum' refers to a value, but is being used as a type here. ts(2749)
const v = MyEnum.b;
```

**Expected behavior:**

No type errors.

It did work fine in v2.8.3

### PR DESCRIPTION
**Pull request by elibarzilay**
Nameless jsdoc typedefs have their exportedness controlled by the
exportedness of the location they pull their name from.

Fixes #33575.

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -583,6 +583,21 @@ namespace ts {
             }
         }
 
+        function jsdocTreatAsExported(node: Node) {
+            if (!isJSDocTypeAlias(node)) return false;
+            // jsdoc typedef handling is a bit of a doozy, but to summarize, treat the typedef as exported if:
+            // 1. It has an explicit name (since by default typedefs are always directly exported, either at the top level or in a container), or
+            if (!isJSDocEnumTag(node) && !!node.fullName) return true;
```
Comment (sandersn) [inline src/compiler/binder.ts:590]: could this be written positively as

```suggestion
            if (isJSDocTypedefTag(node) && !!node.fullName) return true;
```
I think enum and typedef are the only two possibilities here. Oh wait, maybe callback is too.

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -583,6 +583,21 @@ namespace ts {
             }
         }
 
+        function jsdocTreatAsExported(node: Node) {
+            if (!isJSDocTypeAlias(node)) return false;
+            // jsdoc typedef handling is a bit of a doozy, but to summarize, treat the typedef as exported if:
+            // 1. It has an explicit name (since by default typedefs are always directly exported, either at the top level or in a container), or
+            if (!isJSDocEnumTag(node) && !!node.fullName) return true;
+            // 2. The thing a nameless typedef pulls its name from is implicitly a direct export (either by assignment or actual export flag).
+            const declName = getNameOfDeclaration(node);
```
Comment (sandersn) [inline src/compiler/binder.ts:592]: is the code below here only for nameless typedefs, or can `declName` be a node inside a jsdoc comment?
