### PR TITLE
Limit error reporting for methods to the method name

### LINKED ISSUE #5732: 'BestCommonType error' returns wrong error range inside class methods
I'm working on a JS project with ES6 syntax and today I tried out the latest VS Code release (0.10.1). Today I've also learned that the IntelliSense support in VS Code for JS is coming from TS, so I've been told to report it here (https://github.com/Microsoft/vscode/issues/230)

This is the result when there is a "BestCommonType" error inside a class method:
image

And for plain functions it looks like this:
image

### PR DESCRIPTION
**Pull request by reavowed**
Fixes #5732

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11175,7 +11175,7 @@ namespace ts {
             // Abstract methods cannot have an implementation.
             // Extra checks are to avoid reporting multiple errors relating to the "abstractness" of the node.
             if (node.flags & NodeFlags.Abstract && node.body) {
-                error(node, Diagnostics.Method_0_cannot_have_an_implementation_because_it_is_marked_abstract, declarationNameToString(node.name));
+                error(node.body, Diagnostics.Method_0_cannot_have_an_implementation_because_it_is_marked_abstract, declarationNameToString(node.name));
```
Comment (mhegazy) [inline src/compiler/checker.ts]: that is not much better than just node, the body could be a whole file. with the other change, the new range will be just the name, which is a better fit.

**Comment by mhegazy** [comment]
thanks @reavowed, i have one comment, other than that looks good to me.

File: src/compiler/checker.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Yes, just keep it as `node`
