### PR TITLE
fix(54458): The inlay hint does not handle TypeScript's spread operator well

### LINKED ISSUE #54458: The inlay hint does not handle TypeScript's spread operator well
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows11 Pro 22H2 22621.1778

inlay_bug

Steps to Reproduce:

1. type this code:
```
function foo( a : unknown, b : unknown, c : unknown ) {}

function bar( ... x : [ number, number ] )
{
	foo( ... x, 3 );
}
```
2. enable the settings:
    Editor > Inlay Hints
    TypeScript > Inlay Hints > Parameter Names

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #54458

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot pack this

File: src/services/inlayHints.ts [hunk 1]
```diff
@@ -226,14 +229,14 @@ export function provideInlayHints(context: InlayHintsContext): InlayHint[] {
...
-            const originalArg = args[i];
+        let pos = 0;
+        for (const originalArg of args) {
             const arg = skipParentheses(originalArg);
             if (shouldShowLiteralParameterNameHintsOnly(preferences) && !isHintableLiteral(arg)) {
                 continue;
             }
 
-            const identifierNameInfo = checker.getParameterIdentifierNameAtPosition(signature, i);
+            const identifierNameInfo = checker.getParameterIdentifierNameAtPosition(signature, pos++);
```
Comment (gabritto) [inline src/services/inlayHints.ts:239]: I think you also don't want to increment unconditionally here, since we could be passing an empty tuple. Like so:

```ts
function foo1(a: unknown, b: unknown, c: unknown) { }
function bar1(...x: []) { // Empty tuple
    foo1(...x, 3, 4, 5); // Wrong: currently `foo1(/*a*/...x, /*b*/3, /*c*/4, 5)`, should be `foo1(...x, /*a*/3, /*b*/4, /*c*/5)`
}
```

**Review by gabritto — CHANGES_REQUESTED** [review]
