### PR TITLE
Adjust TS2691 message for .ts import sources

### LINKED ISSUE #42151: TypeScript cannot emit valid ES modules due to file extension issue
# Bug Report
This report is based on the problem covered in #28288 and #16577, but intends to emphasize the fact that this explicitly precludes TS from emitting valid ECMAScript modules.

## Issue
Because TS imports do not allow file extensions, but imports in emitted ES modules are _not_ resolved to their relevant file extensions (`import ... from './myModule'` vs. `import ... from './myModule.js'`), this output is unusable unless transpiled *again* with Rollup + Babel or a similar toolkit, no matter how much active care is taken while authoring source code. Executing emitted modules will always throw `ERR_MODULE_NOT_FOUND` because these sources are not rewritten.

Switching to `"module": "commonjs"` is not a valid suggestion in this case, as the goal is to get valid ESM output.

### ⏯ Playground Link

Use `yarn test`: https://repl.it/@christiantjl/TSImportFileExtensions

#### `tsconfig.json`
```json
{
  "compilerOptions": {
    "outDir": "build/",
    
    "target": "esnext",
    "module": "esnext",

    "moduleResolution": "node",
    "esModuleInterop": true
  }
}
```

#### `index.ts`
```typescript
import { test } from './importMe';
console.log(test); 
```

#### `build/index.js`
```javascript
import { test } from './importMe';
console.log(test);
```

### 🙁 Actual behavior
The `import { test } from './importMe'` statement is not modified.

### 🙂 Expected behavior
`build/index.js` should contain:
```javascript
import { test } from './importMe.js';
console.log(test);
```

### PR DESCRIPTION
**Pull request by ctjlewis**
The advice given by error `TS2691` is confusing, and following its instructions produces output which throws `ERR_MODULE_NOT_FOUND` at runtime when outputting an ES module, i.e. when `moduleKind >= ModuleKind.ES2015`.

An import for a module located at `./test.ts` must be specified as `import ... from './test.js'` in order to get a valid ES module out, but users are directed to rename it to `./test`. This error message should be updated so users are given the correct advice based on their use case, and are not confused why their output throws despite the source being perfectly valid TS. (The `./test` format can be used to generate valid CommonJS modules, just not ES modules.)

Closes #42151.

### Current behavior
```typescript
import { test } from './test.ts'
```

Currently throws `TS2691` which says:

```none
An import path cannot end with a '.ts' extension. Consider importing './test' instead.ts(2691)
```

This adjustment does silence the compiler, but the compiled JS looks like:

```javascript
import { test } from './test';
console.log(test);
```

Which is not a valid ES module, as the import source is located at `./test.js`. Executing the output throws `ERR_MODULE_NOT_FOUND`.

### Suggested changes
This PR adjusts `checker.ts` to detect if the output is an ES module, and if so advises the user to replace `./import.ts` with `./import.js` instead of `./import`.

After these changes, trying to import `./test.js` while outputting an ES module throws:

```none
An import path cannot end with a '.ts' extension. Consider importing './test.js' instead.ts(2691)
```

Which will compile to a valid ES module that behaves as expected.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3309,7 +3309,18 @@ namespace ts {
...
-                        error(errorNode, diag, tsExtension, removeExtension(moduleReference, tsExtension));
+                        const importSourceWithoutExtension = removeExtension(moduleReference, tsExtension);
+                        let replacedImportSource = importSourceWithoutExtension;
+                        /**
+                         * Direct users to import source with .js extension if outputting an ES module.
+                         * @see https://github.com/microsoft/TypeScript/issues/42151
+                         */
+                        const target = getEmitScriptTarget(compilerOptions);
+                        const moduleKind = getEmitModuleKind(compilerOptions);
+                        if (target >= ScriptTarget.ES2015 && moduleKind >= ModuleKind.ES2015) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:3320]: I don’t think the script target is relevant independently of the module target.

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Can you add a test that shows this error? Thanks!

**Comment by ctjlewis** [comment]
Sure @andrewbranch - if you see this in time, is there a way to run just a single test in this workspace?

**Comment by andrewbranch** [comment]
`npx gulp runtests --tests substringOfTestFileName`

**Comment by ctjlewis** [comment]
@andrewbranch, so sorry to bug you again for such a low-priority PR, but I can't figure out how to do the equivalent of snapshot updating for these tests in `/tests/baselnes/reference`? I split the `moduleResolutionNoTs.ts` test into `moduleResolutionNoTsCJS.ts` and `moduleResolutionNoTsESM.ts`, but can't find out how to create corresponding files like `/tests/baseline/reference/moduleResolutionNoTsCJS.errors.txt`, `.symbols.txt`, etc.

Thank you so much for your help, super sorry for pinging you, did my best to search for context before asking.

**Comment by andrewbranch** [comment]
> super sorry for pinging you

Don’t be! Contributions are always appreciated and we expect first-time contributors to have some questions 👍

File: src/compiler/checker.ts (hunk 1 above)
Comment (ctjlewis) [reply src/compiler/checker.ts:3320]: Updated this to only depend on `moduleKind`.

File: tests/baselines/reference/moduleResolutionNoTsCJS.errors.txt [hunk 2]
```diff
@@ -0,0 +1,33 @@
+tests/cases/compiler/user.ts(1,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './x' instead.
```
Comment (ctjlewis) [inline tests/baselines/reference/moduleResolutionNoTsCJS.errors.txt:1]: Suggested change for CJS module target.

File: tests/baselines/reference/moduleResolutionNoTsCJS.errors.txt [hunk 3]
```diff
@@ -0,0 +1,33 @@
+tests/cases/compiler/user.ts(1,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './x' instead.
+tests/cases/compiler/user.ts(2,15): error TS2691: An import path cannot end with a '.tsx' extension. Consider importing './y' instead.
+tests/cases/compiler/user.ts(3,15): error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './z' instead.
```
Comment (ctjlewis) [inline tests/baselines/reference/moduleResolutionNoTsCJS.errors.txt:3]: Suggested change for CJS module target.

File: tests/baselines/reference/moduleResolutionNoTsESM.errors.txt [hunk 4]
```diff
@@ -0,0 +1,33 @@
+tests/cases/compiler/user.ts(1,15): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './x.js' instead.
+tests/cases/compiler/user.ts(2,15): error TS2691: An import path cannot end with a '.tsx' extension. Consider importing './y.js' instead.
+tests/cases/compiler/user.ts(3,15): error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './z.js' instead.
```
Comment (ctjlewis) [inline tests/baselines/reference/moduleResolutionNoTsESM.errors.txt:3]: Suggested change for ES module target.

**Review by andrewbranch — APPROVED** [review]
Thanks @ctjlewis!
