### PR TITLE
Parse jsdoc with normal TS type parser

### LINKED ISSUE #16550: JSDoc: support intersection types
**TypeScript Version:**  2.3.4

**Code**

In this example, the type def `Props` fails because of the intersection syntax, which is not supported by JSDoc:

```ts
{
  /** @typedef { { foo: number } & { bar: number } } Props */
  /** @type {function(Props): Props} */
  const fn = props => props;
  fn({ foo: 'x' }); // <-- expected error, got none
}
```

Is TypeScript planning to extend the JSDoc syntax to support TypeScript syntax within the comments, or is it only following the official JSDoc standard?

For context, this would be useful because we are gradually introducing TypeScript to our codebase via `checkJs`. As a workaround, I am putting these typings into a declaration file on a global namespace:

``` ts
declare namespace MyTypings {
  export type Props = { foo: number } & { bar: number }
}
```

``` js
{
  /** @type {function(MyTypings.Props): MyTypings.Props} */
  const fn = props => props;
  fn({ foo: 'x' }); // <-- error as expected
}
```

### PR DESCRIPTION
**Pull request by sandersn**
This means that JSDoc types can include the full range of Typescript types now. It also means that Typescript annotations can include JSDoc types. This is disallowed with a new error, however. But Typescript can still give the correct types to JSDoc that shows up in .ts files by mistake. This can easily happen, for example with types like:

```ts
var x: number? = null;
var y: ?string = null;
var z: function(string,string): string = (s,t) => s + t;

// less likely to show up, but still understood.
var ka: ? = 1;
```

This change saves around 300 lines of code and some of the confusion from having exact duplicate parsing and types for JSDoc vs normal types. Now only JSDoc types and syntax that differ from Typescript's need to be handled separately.

In the future, I will add a quick fix to convert these into the correct types.

Fixes #16550

### CODE REVIEW

**Comment by sandersn** [comment]
@andy-ms asked for fourslash tests for `function(this: T, string): string` and `function(new: T, string)` for the following areas:

* parameter help for these functions
* completions in the scope of these functions

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6339,7 +6339,7 @@ namespace ts {
                         const resolvedSymbol = resolveName(param, paramSymbol.name, SymbolFlags.Value, undefined, undefined);
                         paramSymbol = resolvedSymbol;
                     }
-                    if (i === 0 && paramSymbol.name === "this") {
+                    if (i === 0 && paramSymbol.name === "this" || (param.type && param.type.kind === SyntaxKind.JSDocThisType)) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: I'm not a fan of `JSDocThisType`. It looks like you would have a parameter with no name, and a type of kind `JSDocThisType`, where the type itself has a `.type` property storing the real type.
I think `this: T` should be parsed to the same AST whether we're in TypeScript or in JSDoc, so you don't need a condition for both here.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -3298,6 +3297,10 @@ namespace ts {
         return false;
     }
 
+    export function isJSDocTypeReference(node: TypeReferenceType): node is TypeReferenceNode {
```
Comment (andy-ms) [inline src/compiler/utilities.ts]: This is going to be super slow if we're not in jsdoc -- for any type reference *not* in jsdoc we will climb the whole tree looking for a JSDocTypeExpression that never comes.

Comment (sandersn) [inline src/compiler/utilities.ts]: That's correct. Any ideas for a better implementation?

Comment (andy-ms) [inline src/compiler/utilities.ts]: See edited comment.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -7852,16 +7842,18 @@ namespace ts {
                 case SyntaxKind.NeverKeyword:
                     return neverType;
                 case SyntaxKind.ObjectKeyword:
-                    return nonPrimitiveType;
+                    if (node.flags & NodeFlags.JavaScriptFile) {
+                        return anyType;
```
Comment (andy-ms) [inline src/compiler/checker.ts]: There seems to be duplicate code in `getPrimitiveTypeFromJSDocTypeReference`, are these both needed?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -18474,6 +18460,9 @@ namespace ts {
 
         function checkTypeReferenceNode(node: TypeReferenceNode | ExpressionWithTypeArguments) {
             checkGrammarTypeArguments(node, node.typeArguments);
+            if (node.kind === SyntaxKind.TypeReference && node.typeName.jsdocDot && !isInJavaScriptFile(node) && !findAncestor(node, n => n.kind === SyntaxKind.JSDocTypeExpression)) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Another `findAncestor` call here. We shouldn't be checking a type reference in a jsdoc comment if we're not in a JS file anyway, right?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -18474,6 +18460,9 @@ namespace ts {
 
         function checkTypeReferenceNode(node: TypeReferenceNode | ExpressionWithTypeArguments) {
             checkGrammarTypeArguments(node, node.typeArguments);
+            if (node.kind === SyntaxKind.TypeReference && node.typeName.jsdocDot && !isInJavaScriptFile(node) && !findAncestor(node, n => n.kind === SyntaxKind.JSDocTypeExpression)) {
+                grammarErrorOnNode(node, Diagnostics.JSDoc_types_can_only_be_used_inside_documentation_comments);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: So if I write: `let x: N.M.O.<P, Q>;` I'll get a grammar error on the whole node... it would be hard to spot the extra `.`. Could we try to calculate the range between `O` and `<` for the error, or use a more specific message?

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -19372,7 +19361,17 @@ namespace ts {
             }
         }
 
+        function checkJsDoc(node: FunctionDeclaration | MethodDeclaration) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: This could be inlined. `forEach(node.jsDoc, checkSourceElement)`.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -22030,6 +22045,26 @@ namespace ts {
...
+                    checkJSDocFunctionType(node as JSDocFunctionType);
+                    // falls through
+                case SyntaxKind.JSDocConstructorType:
+                case SyntaxKind.JSDocThisType:
+                case SyntaxKind.JSDocVariadicType:
+                case SyntaxKind.JSDocNonNullableType:
+                case SyntaxKind.JSDocNullableType:
+                case SyntaxKind.JSDocAllType:
+                case SyntaxKind.JSDocUnknownType:
+                    if (!isInJavaScriptFile(node) && !findAncestor(node, n => n.kind === SyntaxKind.JSDocTypeExpression)) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Another `findAncestor` here

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -19372,7 +19361,17 @@ namespace ts {
...
+            if (!node.jsDoc) {
+                return;
+            }
+            for (const doc of node.jsDoc) {
+                checkSourceElement(doc);
+            }
+        }
+
         function checkFunctionOrMethodDeclaration(node: FunctionDeclaration | MethodDeclaration): void {
+            checkJsDoc(node);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Seems silly to call this in a TS file if the checkers for every possible jsdoc element will test if we're in a TS file and then do nothing?

File: src/compiler/utilities.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/utilities.ts]: isInJavaScriptFile may not be sufficient because JSDoc types can appear anywhere in TS or JS files, inside or outside JSDoc. For example:

```js
/** @type {...number} */
var x;
var y: ...number; // annotations are errors in JS file, but still fully checked and treated as number[]
```

and 

```ts
/** @type {...number} */ // actually, this isn't checked.
var x;
var y: ...number; // ... is an error in TS file, but still fully checked and treated as number[]
```

File: src/harness/unittests/jsDocParsing.ts [hunk 9]
```diff
@@ -62,28 +62,26 @@ namespace ts {
                 parsesCorrectly("tupleType1", "{[number]}");
                 parsesCorrectly("tupleType2", "{[number,string]}");
                 parsesCorrectly("tupleType3", "{[number,string,boolean]}");
+                parsesCorrectly("tupleTypeWithTrailingComma", "{[number,]}");
+                parsesCorrectly("typeOfType", "{typeof M}");
+                parsesCorrectly("tsConstructoType", "{new () => string}");
```
Comment (sandersn) [inline src/harness/unittests/jsDocParsing.ts]: Fixed.

File: src/compiler/checker.ts (hunk 8 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Good point. I moved the check into `checkJSDoc`

File: src/compiler/checker.ts (hunk 6 above)
Comment (sandersn) [inline src/compiler/checker.ts]: I'd like to keep the function around for readability and because it may someday be used from more locations.

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/checker.ts]: `getPrimitiveTypeFromJSDocTypeReference` operates on TypeReferenceNode not on a TypeNode with SyntaxKind.Object. Actually, the "object" case there no longer applies since it `@param {object} x` is no longer parsed as a type reference.

File: src/compiler/utilities.ts (hunk 2 above)
Comment (andy-ms) [inline src/compiler/utilities.ts]: So if you have `let o: ...object;` in a JS file, you will see `object` and climb up the tree to determine whether it's in a JSDoc comment? Since that's a grammar error anyway, I don't think it's a big deal if we give the `object` there TS semantics instead of JSDoc semantics.

File: src/compiler/parser.ts [hunk 10]
```diff
@@ -1969,9 +1928,14 @@ namespace ts {
 
         // The allowReservedWords parameter controls whether reserved words are permitted after the first dot
         function parseEntityName(allowReservedWords: boolean, diagnosticMessage?: DiagnosticMessage): EntityName {
-            let entity: EntityName = parseIdentifier(diagnosticMessage);
+            let entity: EntityName = allowReservedWords ? parseIdentifierName() : parseIdentifier(diagnosticMessage);
```
Comment (andy-ms) [inline src/compiler/parser.ts]: Why this change? So we can write `const.const`?
Comment needs an update if so.

File: src/compiler/parser.ts [hunk 11]
```diff
@@ -2119,6 +2083,69 @@ namespace ts {
...
+            return finishNode(node);
+        }
+
+        function parseJSDocParameter(): ParameterDeclaration {
+            const parameter = <ParameterDeclaration>createNode(SyntaxKind.Parameter);
+            parameter.type = parseType();
+            return finishNode(parameter);
+        }
+
+        function parseJSDocNodeWithType(kind: SyntaxKind): TypeNode {
```
Comment (andy-ms) [inline src/compiler/parser.ts]: Could provide a more specific type to `kind`.

File: src/compiler/parser.ts [hunk 12]
```diff
@@ -2171,7 +2198,7 @@ namespace ts {
         }
 
         function isStartOfParameter(): boolean {
-            return token() === SyntaxKind.DotDotDotToken || isIdentifierOrPattern() || isModifierKind(token()) || token() === SyntaxKind.AtToken || token() === SyntaxKind.ThisKeyword;
+            return token() === SyntaxKind.DotDotDotToken || isIdentifierOrPattern() || isModifierKind(token()) || token() === SyntaxKind.AtToken || token() === SyntaxKind.ThisKeyword || token() === SyntaxKind.NewKeyword;
```
Comment (andy-ms) [inline src/compiler/parser.ts]: If JSDoc parameters can include any type, doesn't this leave out a lot of things?

File: src/compiler/parser.ts [hunk 13]
```diff
@@ -2538,10 +2567,14 @@ namespace ts {
             return finishNode(node);
         }
 
-        function parseFunctionOrConstructorType(kind: SyntaxKind): FunctionOrConstructorTypeNode {
+        function parseFunctionOrConstructorType(kind: SyntaxKind): FunctionOrConstructorTypeNode | JSDocConstructorType {
```
Comment (andy-ms) [inline src/compiler/parser.ts]: Could provide a more specific type to `kind`. I only see this being called with `kind` of `SyntaxKind.FunctionType` of `SyntaxKind.ConstructorType`, never `SyntaxKind.JSDocConstructorType`.

File: src/compiler/parser.ts [hunk 14]
```diff
@@ -2538,10 +2567,14 @@ namespace ts {
             return finishNode(node);
         }
 
-        function parseFunctionOrConstructorType(kind: SyntaxKind): FunctionOrConstructorTypeNode {
+        function parseFunctionOrConstructorType(kind: SyntaxKind): FunctionOrConstructorTypeNode | JSDocConstructorType {
             const node = <FunctionOrConstructorTypeNode>createNode(kind);
             if (kind === SyntaxKind.ConstructorType) {
                 parseExpected(SyntaxKind.NewKeyword);
+                if (token() === SyntaxKind.ColonToken) {
+                    // JSDoc -- `new:T` as in `function(new:T, string, string)`; an infix constructor-return-type
```
Comment (andy-ms) [inline src/compiler/parser.ts]: What happens if we see `new:T` and it's *not* inside of `function()`?

File: src/compiler/parser.ts [hunk 15]
```diff
@@ -2649,6 +2694,26 @@ namespace ts {
             return token() === SyntaxKind.CloseParenToken || isStartOfParameter() || isStartOfType();
         }
 
+        function parseJSDocPostfixTypeOrHigher(): TypeNode {
```
Comment (andy-ms) [inline src/compiler/parser.ts]: Move this next to (or into) `parseTypeOperatorOrHigher`.
Can we parse `foo?[]` or `foo![]`? Could merge with `parseArrayTypeOrHigher` (also only called in one place).
I took a stab at making this neater:
```ts
function parseJSDocPostfixTypeOrHigher(): TypeNode {
    const type = parseArrayTypeOrHigher();
    const kind = getKind(token());
    if (!kind) return type;

    const postfix = createNode(kind, type.pos) as JSDocOptionalType | JSDocNonNullableType | JSDocNullableType;
    postfix.type = type;
    return finishNode(postfix);

    function getKind(tokenKind: SyntaxKind): SyntaxKind | undefined {
        switch (tokenKind) {
            case SyntaxKind.EqualsToken:
                // only parse postfix = inside jsdoc, because it's ambiguous elsewhere
                return contextFlags & NodeFlags.JSDoc ? SyntaxKind.JSDocOptionalType : undefined;
            case SyntaxKind.ExclamationToken:
                return SyntaxKind.JSDocNonNullableType;
            case SyntaxKind.QuestionToken:
                return SyntaxKind.JSDocNullableType;
        }
    }
}
```

File: src/compiler/utilities.ts (hunk 2 above)
Comment (weswigham) [inline src/compiler/utilities.ts]: There's a JSDoc Parser context flag now, right? Can it not just be persisted into all nodes as a node flag when they are created within a jsdoc context? So you just check if your node has the flag, and if so, then its inside a jsdoc and has jsdoc semantics?

**Comment by sandersn** [comment]
If you're checking out this branch on windows, note that I inadvertently created a new test `jsdocInTypescript.ts` that differs only in case from an existing test `jsdocInTypeScript.ts`. I'll fix this in the next commit, but in the meantime, Wesley found that the tests are broken.

File: tests/cases/conformance/jsdoc/jsdocTypesInTypeAnnotations.ts [hunk 16]
```diff
@@ -0,0 +1,22 @@
+// @allowJs: true
+// @checkJs: true
+// @noEmit: true
+// @module: commonjs
+// @filename: node.d.ts
+// @noImplicitAny: true
+declare function require(id: string): any;
```
Comment (andy-ms) [inline tests/cases/conformance/jsdoc/jsdocTypesInTypeAnnotations.ts]: This doesn't seem relevant to the test?
Also, the test name seems to imply that jsdoc types will appear inside of type annotations.

**Comment by sandersn** [comment]
From in-person discussion with @andy-ms: I should maybe try to check JSDocFunctionType with checkFunctionLikeDeclaration in order to further reduce duplication and improve checking thoroughness.

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]: I removed JSDocThisType and -ConstructorType like you suggested.

File: src/compiler/utilities.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/utilities.ts]: Yep, I realised that last night. In fact, `finishNode` in the parser persists the context flag, so it was there all along.

File: src/compiler/checker.ts (hunk 5 above)
Comment (sandersn) [inline src/compiler/checker.ts]: I'll just save the dots as we parse them and retain it for this error in the jsdoc case.

Comment (sandersn) [inline src/compiler/checker.ts]: Actually, that creates additional garbage from the dots we *don't* use, which is all dots except the last one in a JSDoc-syntax generic. These dots are relatively very rare, so I will save the start and end instead and manually specify the error span.

File: src/compiler/parser.ts (hunk 10 above)
Comment (sandersn) [inline src/compiler/parser.ts]: Yes, you can say `@param {const} number` in JSDoc. I'll update the comment.

Comment (sandersn) [inline src/compiler/parser.ts]: Actually, without the "right hand side" qualification, it's a garbage comment ("allowReservedWords allows reserved words!"). I deleted it.

File: src/compiler/parser.ts (hunk 11 above)
Comment (sandersn) [inline src/compiler/parser.ts]: Sure.

File: src/compiler/parser.ts (hunk 12 above)
Comment (sandersn) [inline src/compiler/parser.ts]: isIdentifierOrPattern and isModifierKind cover a lot of things like `number`, `const`, etc. But they happen not to cover `this` or `new`.

Comment (andy-ms) [inline src/compiler/parser.ts]: Can we parse this?
```js
/** @type {function({ x: number }, 1 | 2): number} */
const f = (x, y) => x.x + y;
```

File: src/compiler/parser.ts (hunk 15 above)
Comment (sandersn) [inline src/compiler/parser.ts]: 1. No, `foo?[]` would need to parse inside parseArrayTypeOrHigher. That does seem like it should parse as `Array<foo | null>`.
2. I don't think we should merge functions that would map to individual rules in a grammar.
3. Thanks for the refactor.

File: src/compiler/parser.ts (hunk 12 above)
Comment (sandersn) [inline src/compiler/parser.ts]: not `1 | 2`. I will try adding `isStartOfType` to the end of `isStartOfParameter` but I'm not sure if it will be successful.

File: tests/cases/conformance/jsdoc/jsdocTypesInTypeAnnotations.ts (hunk 16 above)
Comment (sandersn) [inline tests/cases/conformance/jsdoc/jsdocTypesInTypeAnnotations.ts]: Actually, I don't think this test is testing anything unique. I'll just remove it.

File: src/compiler/parser.ts [hunk 17]
```diff
@@ -6839,6 +6581,18 @@ namespace ts {
 
                     return finishNode(typedefTag);
 
+                    function isObjectTypeReference(node: TypeNode) {
```
Comment (sandersn) [inline src/compiler/parser.ts]: Much better.

File: src/compiler/parser.ts (hunk 12 above)
Comment (sandersn) [inline src/compiler/parser.ts]: At least one test entered an infinite loop with `isStartOfType` inside `isStartOfParameter`. Instead I just added `StringLiteral` and `NumericLiteral` to the end.

File: tests/baselines/reference/initializerReferencingConstructorLocals.errors.txt [hunk 18]
```diff
@@ -1,18 +1,16 @@
 tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorLocals.ts(4,9): error TS2304: Cannot find name 'z'.
 tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorLocals.ts(5,15): error TS2304: Cannot find name 'z'.
 tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorLocals.ts(6,14): error TS2339: Property 'z' does not exist on type 'C'.
-tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorLocals.ts(7,15): error TS1003: Identifier expected.
-tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorLocals.ts(7,20): error TS2339: Property 'z' does not exist on type 'C'.
+tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorLocals.ts(7,15): error TS2304: Cannot find name 'this'.
```
Comment (sandersn) [inline tests/baselines/reference/initializerReferencingConstructorLocals.errors.txt]: That's because `parseEntityName` now allows reserved words anywhere, not just on the right of a dot. That affects even single identifiers, but in this case it now allows `this` in `this.x` to be parsed as an identifier.

Other callers that pass `allowReservedWords: true` are `parseTypeQuery` and `parseIsolatedEntityName`. Plus `parseTypeReference` in the case of JSDoc.

I think the change is fine in `parseTypeQuery` since this error is at least as easy to read as the old one. `parseIsolatedEntityName` just seems to be used for parsing `--jsxFactory`, so that change should be fine too (although I'm not sure why it allows reserved words at all).

**Comment by sandersn** [comment]
I think I've addressed all the comments up to this afternoon.

File: src/compiler/parser.ts (hunk 15 above)
Comment (andy-ms) [inline src/compiler/parser.ts]: Seems like solving 1 would require ditching 2. If we want to be able to parse `foo?[]?[]`, we would need to handle postfix types in a uniform way.

Comment (andy-ms) [inline src/compiler/parser.ts]: So now I can type syntactically valid jsdoc in place of swearing.

File: tests/baselines/reference/jsdocFunctionType.symbols [hunk 19]
```diff
@@ -61,3 +61,9 @@ z.length;
 >z : Symbol(z, Decl(functions.js, 26, 3))
 >length : Symbol(length, Decl(functions.js, 12, 27))
 
+/** @type {function ("a" | "b"): 1 | 2} */
```
Comment (andy-ms) [inline tests/baselines/reference/jsdocFunctionType.symbols]: This doesn't actually test the ability to parse a number literal as a parameter type, that would be `function("a" | "b", 1 | 2): whatever`.
