### PR TITLE
Fix printing and emit for definite assignment assertions

### LINKED ISSUE #35093: Definite assignment assertions are not emitted by printer
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
    const result = ts.transform(ts.createSourceFile("file.ts", `let content!: string;`, ts.ScriptTarget.ES2016), [() => f => f]);
    const printer = ts.createPrinter({}, {
        onEmitNode: result.emitNodeWithNotification,
        substituteNode: result.substituteNode
    });
    const txt = printer.printFile(result.transformed[0]);
```

**Expected behavior:**
`txt` has value `let content!: string;\r\n`.

**Actual behavior:**
`txt` has value `let content: string;\r\n`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #35093

We use definite assignment assertions in our own codebase, so the referenced bug is actually blocking me doing source to source transforms on our real codebase.

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -3807,7 +3807,7 @@ namespace ts {
         }
 
         // Type annotations are TypeScript syntax.
-        if (node.type) {
+        if (node.type || node.exclamationToken) {
```
Comment (ajafff) [inline src/compiler/binder.ts]: is this change related to the emitter?
If so, you probably also want to make the same change in `computePropertyDeclaration` (see #35097 which I erroneously opened)
