### PR TITLE
Handle when default project for file is solution with file actually referenced by one of the project references

### LINKED ISSUE #36708: "Cannot find module" when using project references
**TypeScript Version:**  3.7.5, 3.8.1-rc

Note: this was originally posted to https://github.com/microsoft/vscode/issues/80423. I was told there that https://github.com/microsoft/TypeScript/issues/30823 would fix this.

https://github.com/microsoft/TypeScript/issues/30823 was apparently fixed by https://github.com/microsoft/TypeScript/pull/33287, however this issue still remains.

---

Steps to Reproduce:

`./tsconfig-src.json`:

```json
{
    "compilerOptions": {
        "composite": true,
        "declarationMap": true,
        "outDir": "./target/",
        "baseUrl": "./src/"
    },
    "include": ["./src/**/*"]
}
```

`./tsconfig.json`:

```json
{
    "references": [{ "path": "./tsconfig-src.json" }],
    "files": []
}
```

`./src/main.ts`:

```ts
import { foo } from 'helpers/functions';

foo;
```

`./src/helpers/functions.ts`:

```ts
export const foo = 1;
```

When I run `tsc --build`, it builds with no errors.

When I navigate to a TS file in VS Code, e.g. `./src/main.ts`, I get errors: `Cannot find module 'helpers/functions'`

I expected this to work because VS Code would find the `./tsconfig.json` in the parent/root directory, and this references `./tsconfig-src.json` (the TS project which includes the file I'm looking at: `./src/main.ts`).

Repo including the above test case: https://github.com/OliverJAsh/unsplash-ts-project-references

I understand I could workaround this by moving `./tsconfig-src.json` into the `./src/` folder at `./src/tsconfig.json`, but I believe that shouldn't be necessary.

What's more, in my real world application the `./tsconfig-src.json` includes files in multiple root folders (`./src/`, `./client/`, `./server/`), not just `./src/`, so this workaround wouldn't help in that case. For an example, see https://github.com/OliverJAsh/unsplash-ts-project-references/tree/bad-workaround.

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #36708, #27372

Now when we find that the project is a solution project, we try to open referenced projects to see if we can find project that contains the opened file.

### CODE REVIEW

File: src/server/editorServices.ts [hunk 1]
```diff
@@ -2722,8 +2776,20 @@ namespace ts.server {
                         else {
                             // reload from the disk
                             this.reloadConfiguredProject(project, reason);
+                            if (!project.containsScriptInfo(info) && project.isSolution()) {
+                                forEachResolvedProjectReferenceProject(
+                                    project,
+                                    child => {
+                                        if (!updatedProjects.has(child.canonicalConfigFilePath)) {
+                                            updatedProjects.set(child.canonicalConfigFilePath, true);
+                                            this.reloadConfiguredProject(child, reason);
```
Comment (uniqueiniquity) [inline src/server/editorServices.ts]: I'm still trying to understand the implementation, so this might be a silly question... but here, it seems for a given file `f`, we start at a project and reload it. Then, if it's a solution project, we start looking for the project it's actually in, reloading projects as we go. Then, once we find it, we reload that project and stop looking. Why do we reload the projects it's not in before we find it, but not reload any other projects?

**Comment by amcasey** [comment]
A solution project is a composite project with references to other projects, but no files of its own?

**Comment by uniqueiniquity** [comment]
@amcasey That appears to be the case, but I would appreciate confirmation as well. Also, how common is that as a pattern?

File: src/server/editorServices.ts [hunk 2]
```diff
@@ -424,7 +424,48 @@ namespace ts.server {
         return !!(infoOrFileNameOrConfig as AncestorConfigFileInfo).configFileInfo;
     }
 
-    function forEachResolvedProjectReference<T>(
+    /*@internal*/
+    export enum ProjectReferenceProjectLoadKind {
```
Comment (amcasey) [inline src/server/editorServices.ts]: >ProjectReferenceProjectLoadKind [](start = 16, length = 31)

I would find explanatory comments helpful.

File: src/server/project.ts [hunk 3]
```diff
@@ -2164,6 +2164,24 @@ namespace ts.server {
...
         }
 
+        /* @internal */
+        isSolution() {
+            return this.getRootFilesMap().size === 0 &&
+                !this.canConfigFileJsonReportNoInputFiles;
+        }
+
+        /* @internal */
+        getDefaultChildProjectFromSolution(info: ScriptInfo) {
```
Comment (amcasey) [inline src/server/project.ts]: >getDefaultChildProjectFromSolution [](start = 8, length = 34)

I'm not sure I understand what this does.  I think it returns the first loaded (?) project (in tsconfig project-reference-list order?) that contains the ScriptInfo directly (i.e. not because it was pulled in from a referenced project?).

Comment (amcasey) [reply src/server/project.ts]: Does the answer change as more projects are loaded?

---
In reply to: [388677179](https://github.com/microsoft/TypeScript/pull/37239#discussion_r388677179) [](ancestors = 388677179)

File: src/server/editorServices.ts [hunk 4]
```diff
@@ -308,7 +308,7 @@ namespace ts.server {
     }
 
     interface AssignProjectResult extends OpenConfiguredProjectResult {
-        defaultConfigProject: ConfiguredProject | undefined;
+        retainProjects: readonly ConfiguredProject[] | ConfiguredProject | undefined;
```
Comment (amcasey) [inline src/server/editorServices.ts]: >retainProjects [](start = 8, length = 14)

Singleton and undefined are included because they're cheaper to store than the corresponding lists?  If so, we don't already have a helper type for that?

File: src/server/editorServices.ts [hunk 5]
```diff
@@ -2880,9 +2947,41 @@ namespace ts.server {
...
+                                // If script info belongs to this child project, use this as default config project
+                                if (projectContainsInfoDirectly(child, info)) {
+                                    configFileName = childConfigFileName;
+                                    configFileErrors = child.getAllProjectErrors();
+                                    this.sendConfigFileDiagEvent(child, info.fileName);
+                                    return child;
+                                }
+                            },
+                            ProjectReferenceProjectLoadKind.FindCreateLoad,
+                            `Creating project referenced in solution ${project.projectName} to find possible configured project for ${info.fileName} to open`
```
Comment (amcasey) [inline src/server/editorServices.ts]: >Creating project referenced in solution ${project.projectName} to find possible configured project for ${info.fileName} to open [](start = 29, length = 127)

Does this message ever find its way into telemetry or error messages?

File: src/server/editorServices.ts (hunk 4 above)
Comment (sheetalkamat) [reply src/server/editorServices.ts]: Havent found it in core so far

File: src/server/editorServices.ts (hunk 5 above)
Comment (sheetalkamat) [reply src/server/editorServices.ts]: Dont think so.. It is a part of event for `ProjectLoadStart` which helps display loading configured project..

**Comment by sheetalkamat** [comment]
A solution project is project with project referenes but no files on its own.. (Eg https://github.com/microsoft/TypeScript/blob/master/src/tsconfig.json)

**Comment by sheetalkamat** [comment]
Note that we already handle solutions for scenarios like our own repo.. Wherein  the tsconfig for compiler is in its own folder and named `tsconfig.json` so found for the file open in `src\compiler` ... This tries to solve cases if say that tsconfig was named `tsconfig.compiler.json` or was in `src\compiler` or `src` itself instead. Good repro scenario to look at would be the issues this PR is fixing.. #27372 has a link to https://github.com/OliverJAsh/jest-ts-project-references which demos the issue.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

File: src/server/editorServices.ts (hunk 1 above)
Comment (sheetalkamat) [reply src/server/editorServices.ts]: This is method that reloads the projects for open files (eg because user invoked that operation in vscode) 
What this does is, it finds config file for each open file.. which if turns out to be solution, we need to reload all projects till we find the project that open file belongs to.. (just like when we do for open file as part of this change)

File: src/server/project.ts (hunk 3 above)
Comment (sheetalkamat) [reply src/server/project.ts]: This tries to find the project that is a referenced project from the solution where the script info belongs (and not just referenced) eg. from project `src\tsconfig.json` for file `src\compiler.ts` it will find `src\compiler\tsconfig.json` and not `src\services\tsconfig.json`

Comment (amcasey) [reply src/server/project.ts]: And does the answer depend on which projects are loaded when the question is asked?

Comment (sheetalkamat) [reply src/server/project.ts]: Yes. Because it only finds the projects

File: src/server/editorServices.ts (hunk 4 above)
Comment (amcasey) [reply src/server/editorServices.ts]: There are helpers that operate on `T | readonly T[]`, but I also can't find an attempt to formalize the pattern.

File: src/server/editorServices.ts [hunk 6]
```diff
@@ -424,7 +424,52 @@ namespace ts.server {
...
 
-    function forEachResolvedProjectReference<T>(
+    /*@internal*/
+    /** Kind of operation to perform to get project reference project */
+    export enum ProjectReferenceProjectLoadKind {
+        /** Find existing project for project reference */
+        Find,
+        /** Find existing project or create one for the project reference */
+        FindCreate,
+        /** Find existing project or create and loas it for the project reference */
```
Comment (amcasey) [inline src/server/editorServices.ts]: >loas [](start = 48, length = 4)

Typo: "loas"

File: src/server/editorServices.ts [hunk 7]
```diff
@@ -424,7 +424,52 @@ namespace ts.server {
         return !!(infoOrFileNameOrConfig as AncestorConfigFileInfo).configFileInfo;
     }
 
-    function forEachResolvedProjectReference<T>(
+    /*@internal*/
+    /** Kind of operation to perform to get project reference project */
+    export enum ProjectReferenceProjectLoadKind {
+        /** Find existing project for project reference */
```
Comment (amcasey) [inline src/server/editorServices.ts]: >existing [](start = 17, length = 8)

Does "existing" imply "loaded"?

Comment (sheetalkamat) [reply src/server/editorServices.ts]: existing means preset

File: src/server/editorServices.ts [hunk 8]
```diff
@@ -2722,8 +2781,21 @@ namespace ts.server {
...
                             // reload from the disk
                             this.reloadConfiguredProject(project, reason);
+                            // If this is solution, reload the project till the reloaded project contains the script info directly
+                            if (!project.containsScriptInfo(info) && project.isSolution()) {
+                                forEachResolvedProjectReferenceProject(
+                                    project,
+                                    child => {
+                                        if (!updatedProjects.has(child.canonicalConfigFilePath)) {
+                                            updatedProjects.set(child.canonicalConfigFilePath, true);
+                                            this.reloadConfiguredProject(child, reason);
```
Comment (amcasey) [inline src/server/editorServices.ts]: Should `reason` be updated to reflect that it's a child project of a solution?

File: src/server/editorServices.ts [hunk 9]
```diff
@@ -2722,8 +2781,21 @@ namespace ts.server {
...
+                                        }
+                                        return projectContainsInfoDirectly(child, info);
+                                    },
+                                    ProjectReferenceProjectLoadKind.FindCreate
```
Comment (amcasey) [inline src/server/editorServices.ts]: Not `FindCreateLoad` because the callback's going to load it?

File: src/server/editorServices.ts [hunk 10]
```diff
@@ -1686,8 +1738,12 @@ namespace ts.server {
         findDefaultConfiguredProject(info: ScriptInfo) {
             if (!info.isScriptOpen()) return undefined;
             const configFileName = this.getConfigFileNameForFile(info);
-            return configFileName &&
+            const project = configFileName &&
                 this.findConfiguredProjectByProjectName(configFileName);
+
+            return project?.isSolution() ?
+                project.getDefaultChildProjectFromSolution(info) :
```
[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/server/editorServices.ts]: Yes.. this is when the project found by default config for a file is solution

File: src/server/editorServices.ts (hunk 9 above)
Comment (sheetalkamat) [reply src/server/editorServices.ts]: Because we are reloading it anyways.. so createAndLoad is not needed

File: src/server/editorServices.ts (hunk 8 above)
Comment (sheetalkamat) [reply src/server/editorServices.ts]: I think its fine.. Since its still loading project for that file and reason for now isnt specific to file or project

**Comment by sheetalkamat** [comment]
> How did you identify the code paths that needed to be updated (i.e. how do you know you didn't miss one)?

Well i looked at all the calls to `getConfigFileNameForFile` which is where after finding solution project, we are changing the behavior

**Comment by amcasey** [comment]
> > How did you identify the code paths that needed to be updated (i.e. how do you know you didn't miss one)?
> 
> Well i looked at all the calls to `getConfigFileNameForFile` which is where after finding solution project, we are changing the behavior

It sounds like anyone who calls `getConfigFileNameForFile` in the future will need to think about this as well.  Is there some way we could organize the code to guard against a new caller failing to do so?

**Comment by amcasey** [comment]
I tried the repro in https://github.com/microsoft/TypeScript/issues/36708 (GTD on `"helpers/functions"` in src/main.ts) and it reported that the module was not found.  Expected?

**Comment by amcasey** [comment]
Same for https://github.com/microsoft/TypeScript/issues/27372 (error expected after uncommenting designated line in src/sum.ts).

**Comment by amcasey** [comment]
Confirmed that https://github.com/microsoft/TypeScript/issues/36708 and https://github.com/microsoft/TypeScript/issues/27372 no longer repro.  The tests work better if I launch the version of VS Code running against this change. 😝

**Comment by kripod** [comment]
Can a solution `tsconfig.json` file contain solution-wide `compilerOptions`? Is the configuration below valid?

```json
// tsconfig.json
{
  "files": [],
  "references": [
    { "path": "./packages/client/tsconfig.json" },
    { "path": "./packages/server/tsconfig.json" },
  ],
  "compilerOptions": {
    "noEmit": true,
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "target": "ES2019",
    "module": "ESNext",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react"
  }
}
```

**Comment by amcasey** [comment]
@kripod I think you're asking whether your client and server projects will automatically pick up those compiler options - no, they won't.  If you want to inherit the configuration, you need to use `extends` in the derived/child projects.

**Comment by Martaver** [comment]
Is this patch available in `typescript@dev` or `typescript@next`...?

If so, then the use case described in: https://github.com/kulshekhar/ts-jest/issues/1698 isn't resolved by this PR.

This is relevant because `ts-jest` is dependent on this API for resolving modules that are project references, and if this PR is supposed to fix that - it hasn't.

**Comment by sheetalkamat** [comment]
@Martaver I am not sure what you are asking here. i cloned the repo, checkout branch and opened vscode and that seems to work without reporting errors.

The build steps do not use tsc so it would be hard to tell whats going on. you would need to seek help from the package that is building it.

image

**Comment by ahnpnl** [comment]
Hi, I want to implement the same behavior programmatically with `LanguageService` interface but I am kind of lost when reading this PR. Do you have any help documentation to implement similarly ?

**Comment by aleclarson** [comment]
> https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/src/tsconfig.json

How are "solution projects" useful in that example? Doesn't the language server look for `tsconfig.json` in each parent directory before compiling a module? In that example, the "solution project" seems superfluous.

PS: We would appreciate a response to #33407. I'd prefer to use an `overrides` key that can target specific globs, without the need to create a separate `.json` module.

```json5
{
	"include": ["src"],
	"compilerOptions": {
		// These options are inherited by override globs.
		"moduleResolution": "node",
		"strict": true 
	},
	"overrides": [
		{
			"include": ["**/__tests__"],
			"compilerOptions": {
				"types": ["jest", "node"]
			}
		}
	]
}
```

**Comment by aleclarson** [comment]
I've tried this approach without success. See anything wrong in this gist?
https://gist.github.com/aleclarson/6ae9a3b6b9d06c492fb9a3b6ec395411
