### PR TITLE
Fixes the issue with emit where in same file is emitted multiple times

### LINKED ISSUE #19253: 2.6 takes a very long time to --watch on large projects
**TypeScript Version:**  2.6.0-rc

**Code**

```shell
# Where tsconfig.json includes hundreds of .ts files (~400 on my smallest repro project)
tsc -w tsconfig.json
```

```json
{
    "compilerOptions": {
        "declaration": true,
        "experimentalDecorators": true,
        "jsx": "react",
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noResolve": true,
        "pretty": true,
        "sourceMap": true,
        "target": "es5"
    },
    "include": [...]
}

```

**Expected behavior:**

After adding an unused public method to a class, it should eventually finish compilation.

**Actual behavior:**

After >10 minutes of waiting a few times, I've terminated the process. I've also tried reinstalling 2.6.0-rc.

Side note: on a smaller project of 28 items, with identical tsconfig settings (except that `strictNullChecks` is on), recompilation from adding an unused public method to a class went from ~1000ms average over 5 runs to 1500ms average (measured from the time TS outputs the `File_change_detected_Starting_incremental_compilation` diagnostic to the time it outputs the `Compilation_complete_Watching_for_file_changes` diagnostic).

The code isn't open source so I can't post it here, but I have emailed a few TypeScript team members instructions on how to get to it before (Office Sway).

### PR DESCRIPTION
**Pull request by sheetalkamat**
Before this change, all the affected files list was emitted and the file write callback was used to ensure we mark duplicate source files that would result in computing same output file (eg with --out) The issue with this was that writeFileCallback doesn't list ```.d.ts``` files as computing to same output files, yet emit with that file as sourceFile emits the same --out file. This means whenever there are multiple d.ts files are present in affected file list, it would result in same file being emitted multiple times. 
The problem got worse since builder always created emit output in memory, which means till all the changed files are written to disk those huge strings and other data exists in memory. That means you can run out of memory pretty soon. (Resulting in #19253) 

This fix deals with this by:

- emitChangedFiles in the builder doesn't generate output in memory, instead it takes the writeFileCallback (just like program::emit method)
- Do not record deleted files in changedFileSet since they are anyways not going to result in any kind of emit
- With this, now if there there is even a single file in changedFilesSet, and emit is going to use single file to output, just emit it. since with any change in program file (whether it changes shape or not) same file is going to be emitted
-  Do not cache semantic diagnostics when --out or --outFile is specified since we would anyways need to remove the diagnostics for the files that result in this emit
- Also now store the files that have already computed if the shape was changed. This helps in not returning the file as updated shape multiple times. This is needed to ensure we don't compute same d.ts files again and again to see if signature is updated.
- For declaration file, use its version as the signature instead of text so that we don't need to compute hash for them.

Apart from this another TODO and to think in future to see if we can ensure that emitter always emits just declaration file without doing any additional diagnostics/no emit checks. This would help in figuring out dependencies correctly. Right now in all these cases (for some reason emit is skipped) shape is assumed to be Skipped.

Fixes #19253

### CODE REVIEW

File: src/compiler/builder.ts [hunk 1]
```diff
@@ -182,114 +165,95 @@ namespace ts {
...
             }
             return diagnostics || emptyArray;
         }
 
+        function getSemanticDiagnosticsOfFile(program: Program, sourceFile: SourceFile, cancellationToken?: CancellationToken): ReadonlyArray<Diagnostic> {
+            const path = sourceFile.path;
+            const cachedDiagnostics = semanticDiagnosticsPerFile.get(path);
+            // Report the semantic diagnostics from the cache if we already have those diagnostics present
+            if (cachedDiagnostics) {
+                cachedDiagnostics;
```
Comment (mhegazy) [inline src/compiler/builder.ts]: did you mean `return cachedDiagnostics` ?
