### PR TITLE
Fix string literal completions when a partially-typed string fixes inference to a type parameter

### LINKED ISSUE #43646: JavaScript - IntelliSense list doesn't display full suggestions list.
- VS Code Version: 1.55.1
- OS Version: Windows 20h2

cc/ @mjbvz 

### First Problem
---

```
const elementsContainer = document.querySelectorAll('ul');
elementsContainer.forEach((e) => {
    e.addEventListener('dragenter', (e) => {
       e.preventDefault();
    });
});
```

### Second Problem

Extracted to #43647

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #43646

Very involved with #36556

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -22662,7 +22675,7 @@ namespace ts {
                 const properties = getPropertiesOfObjectType(target);
                 for (const targetProp of properties) {
                     const sourceProp = getPropertyOfType(source, targetProp.escapedName);
-                    if (sourceProp) {
+                    if (sourceProp && !some(sourceProp.declarations, hasSkipDirectInferenceFlag)) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:22678]: Maybe it would be nice to skip this at least in non-services calls, but it would be a lot of plumbing to get `checkMode` through. I can make a local in `createTypeChecker` if it seems worthwhile.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -570,6 +555,8 @@ namespace ts {
             getFullyQualifiedName,
             getResolvedSignature: (node, candidatesOutArray, argumentCount) =>
                 getResolvedSignatureWorker(node, candidatesOutArray, argumentCount, CheckMode.Normal),
+            getResolvedSignatureForStringLiteralCompletions: (call, editingArgument, candidatesOutArray) =>
```
Comment (weswigham) [inline src/compiler/checker.ts:558]: Can't we just add an `@internal` overload for `getResolvedSignature` that allows `CheckMode` to be passed in?

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:22678]: I'm pretty sure you could translate the `CheckMode` to an `InferenceFlag` if you'd like.

File: src/compiler/checker.ts (hunk 2 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:558]: `editingArgument` is also needed, and `argumentCount` isn’t needed... and I like that the name implies the signature you’re going to get is in fact not at all the same signature you would get for normal checking purposes.

File: src/compiler/checker.ts (hunk 1 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:22678]: `inferTypes` doesn’t have access to the inference flags, so this doesn’t actually improve the plumbing situation 😕

Comment (weswigham) [reply src/compiler/checker.ts:22678]: A dummy `InferencePriority` that's unset by the start of inference then? 😅

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@weswigham the perf impact seems to be lost in the noise, so I’d rather not do something hacky to avoid the check.

File: tests/cases/fourslash/completionsLiteralOverload.ts [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+////
+//// addListener("/*ts*/");
+//// (<ListenerComponent type="/*tsx*/" />);
+
+// @Filename: /b.js
+//// addListener("/*js*/");
+
+verify.completions({ marker: ["ts", "tsx", "js"], exact: ["", "drag", "dragenter"] });
+edit.insert("drag");
+verify.completions({ marker: ["ts", "tsx", "js"], exact: ["", "drag", "dragenter"] });
```
Comment (weswigham) [inline tests/cases/fourslash/completionsLiteralOverload.ts:23]: Should we also have a test where `drag` is already entered and we check that we don't output `""`? I mean, I guess we should just so we know what our current behavior is, I suppose.

**Review by weswigham — APPROVED** [review]

File: tests/cases/fourslash/completionsLiteralOverload.ts (hunk 3 above)
Comment (andrewbranch) [reply tests/cases/fourslash/completionsLiteralOverload.ts:23]: (The test you’re suggesting is already what’s happening on this line)

Comment (weswigham) [reply tests/cases/fourslash/completionsLiteralOverload.ts:23]: Ahh, ok, I misread - thanks!
