### PR TITLE
Narrow generic conditional and indexed access return types when checking return statements

### LINKED ISSUE #33014: Suggestion for Dependent-Type-Like Functions: Conservative Narrowing of Generic Indexed Access Result Type
# Search Terms

generic indexed access type dependent function
generic narrowing

# Suggestion

TypeScript does not provide dependent types, but by combining various features such as unions, literal types and indexed access types we can obtain fairly similar behaviour to a dependent function from the caller point of view. Unfortunately, the implementer of such functions is faced with either the possibility of creating unsoundness (pre 3.5) or forced to assert the return type with unsound features (post 3.5). There are some differences with typical dependent functions, which is why we call these _dependent-type-like_ functions.

This suggestion proposes an addition to the typechecking part of TypeScript, which aids the programmer in writing dependent-type-like functions. The main attractive point of this suggestion is that it does not introduce any additional syntax, and is meant to be a conservative extension. Thus it is not a breaking change with regards to the changes introduced in 3.5, but it does enable certain sound scenarios to typecheck.

# Use Case

The main use case is dependent-type-like functions, the `depLikeFun` example is a minimalistic scenario showcasing such a situation. In this example, we have the `depLikeFun` function which returns `number` when its input is of type `"t"` and `boolean` when its input is of type `"f"`.

```ts
interface F {
  "t": number,
  "f": boolean,
}

function depLikeFun<T extends "t" | "f">(str: T): F[T] {
  if (str === "t") {
    return 1;
  } else {
    return true;
  }
}

depLikeFun("t"); // has type number
depLikeFun("f"); // has type boolean
```

This pattern occurs in various places, such as the [TypeScript dom bindings](https://github.com/microsoft/TypeScript/blob/ca00b3248b1af2263d0223d68e792b7ca39abcab/lib/lib.dom.d.ts#L11050), in issues such as [#31672](https://github.com/microsoft/TypeScript/issues/31672) and [#32698](https://github.com/microsoft/TypeScript/issues/32698), in comments of related issues such as [#13995](https://github.com/microsoft/TypeScript/issues/13995), or on [stackoverflow questions](https://stackoverflow.com/questions/56479117/how-to-fix-ts2322-when-using-a-case-switch-and-generics). This extension could serve as a workaround for related issues such as [#22609](https://github.com/microsoft/TypeScript/issues/22609) and [#23861](https://github.com/microsoft/TypeScript/issues/23861).

# Problem

The problem lies in the implementation of the function. The pre-3.5 behaviour enabled the creation of unsoundness in these type of functions. TypeScript checked the return value using the constraint of key type `T`, simplifying `F[T]` to `number | boolean`. However, this is unsound since the caller can provide a more specific type for `T` such as `"t"`.

```ts
// pre-3.5
function depLikeFun<T extends "t" | "f">(str: T): F[T] {
  if (str === "t") {
    return true; // should be error
  } else {
    return 1; // should be error
  }
}

depLikeFun("t"); // has type number, but is actually a boolean
depLikeFun("f"); // has type boolean, but is actually a number
```

The post-3.5 behaviour also isn't satisfactory for this use case. It disallows the `depLikeFun` to be implemented, which means the implementer needs to use unsafe type assertions. By [#30769](https://github.com/microsoft/TypeScript/pull/30769), assigning to type `F[T]` is interpreted as a write to `F` at key `T`. This means that the result type `F[T]` is checked against the _intersection_ of its possibilities, which is `number & boolean` and thus `never`. 

```ts
// post-3.5
function depLikeFun<T extends "t" | "f">(str: T): F[T] {
  if (str === "t") {
    return 1; // unexpected error: '1' is not assignable to never
  } else {
    return true; // unexpected error: 'true' is not assignable to never
  }
}
```

Mistakes are more likely to occur in complex situations, and thus aiding the user with these types of functions seems in line with TypeScript's design goals.

# Examples

In a dependently typed language `depLikeFun` would be modeled as `function depFun(str: "t" | "f"): F[str]`. There are meaningful differences between depending on the actual _value_ of the input versus the _type_ of an input. This distinction makes this issue more tricky to solve than appears on first sight. In this section we showcase the expected behaviour of the addition on certain representative examples.

The main idea behind the addition is as follows: in a dependent-type-like function we cannot narrow the type `T` of a variable when its value is checked. For example, if `str` has type `T extends "t" | "f"` and we check whether `str === "t"`, then it is unsafe to narrow `T` to `"t"` in that branch, since `T` could also be instantiated with the wider type `"t" | "f"`. Instead, we add knowledge about the type `T` within the branch which is more conservative, but makes it possible to allow the behaviour of dependent-type-like functions. In more traditional programming language theory, the knowledge added is very similar to adding a lower bound `"t" <: T` into the context.

## Basic Use Case

First we look at the `depLikeFun` example. In the `if`-branch, returning `1` is allowed since after checking `str === "t"` the type of `T` can only be `"t"` or `"t" | "f"`. Thus, the caller will expect either a `number` or `number | boolean`, and thus it is safe to return the value `1`.

Note: The claim above that `T` can only be `"t"` or `"t" | "f"` is not quite true due to branded types. For example, `T` could also be the type `Branded`, defined as `type Branded = "t" & {_branded?: any}`. In this case the caller expects a value of type `unknown`, so returning `1` is also safe.

```ts
function depLikeFun<T extends "t" | "f">(str: T): F[T] {
  if (str === "t") {
    return 1; // no error
  } else {
    return true; // no error
  }
}
```

An example which does not occur for dependent functions, but does occur in dependent-type-like functions, is the following. The type `T` can be attributed to _multiple_ inputs, this possibility is what makes it unsafe to fully narrow the type parameter based on a check of the input `str`. However, the reasoning above still holds since the added knowledge is true regardless of how many inputs `T` is linked to.

```ts
function depLikeFun<T extends "t" | "f">(str: T, str2: T): F[T] {
  if (str === "t") {
    return 1; // no error
  } else {
    return true; // no error
  }
}
```

The extension is conservative, and behaviour of other cases should be the same as in 3.5. However, what might change is the error message users see when implementing dependent-type-like functions. In the situation below, instead of comparing `true` / `1` to `never`, they get compared against the simplified indexed access type within each branch. This is `number` in the then branch and `boolean` in the else branch.

```ts
function depLikeFun<T extends "t" | "f">(str: T): F[T] {
  if (str === "t") {
    return true; // Type 'true' is not assignable to type 'number'
  } else {
    return 1; // Type '1' is not assignable to type 'boolean'
  }
}
```

## Non-Return Indexed Access

The type `F[T]` can occur elsewhere in the function. This extension retains the normal TypeScript behaviour in those cases, and is only enabled when checking the return type of a function. In the following example we have a value of type `F[T]` as second input to the function. Within the then branch, this type should not be simplified to `number`, since it can actually be of type `boolean`. Checking the first input value does not give us any information regarding the second input value, and thus we cannot do any more simplification.

```ts
function depLikeFun<T extends "t" | "f">(str: T, ft: F[T]): F[T] {
  if (str === "t") {
    const n: number = ft; // Type 'F[T]' is not assignable to type 'number'.
    return 1;
  } else {
    return true;
  }
}

let x: boolean = false;
depLikeFun<"t" | "f">("t", x); // ft can be of type 'boolean'
```

## Transitive Type Parameters

TypeScript allows an indexed access with a type parameter which has a _direct_ transitive line to a correct bound. For example, it allows `function depLikeFun<T extends "t" | "f", B extends T>(str: B): F[B]`, but disallows `function depLikeFun<T extends "t", F extends "f", B extends T | F>(str: B): F[B]`.

In these situation it seems safe to let information flow through the transitive chain in both directions. For example, when checking an input of type `B`, we can add knowledge about `T`. And vice versa for checking an input of type `T` and an input of type `B`.

```ts
function depLikeFun<T extends "f" | "t", B extends T>(str: B): F[T] {
  if (str === "t") {
    return true; // no error
  } else {
    return 1; // no error
  }
}

function depLikeFun<T extends "f" | "t", B extends T>(str: T): F[B] {
  if (str === "t") {
    return true; // no error
  } else {
    return 1; // no error
  }
}
```

## Consistency with Conditional Types

TypeScript provides alternative means of creating type-level functions by using conditional types. Instead of creating the record type `F`, we can create the type constructor `F` which provides a similar mapping.

```ts
type F<A extends "t" | "f"> =
  A extends "t" ? number :
  A extends "f" ? boolean :
  never;
```

Which can be used as seen below.

```ts
function depLikeFun<T extends "t" | "f">(str: T): F<T> {
  if (str === "t") {
    return true;
  } else {
    return 1;
  }
}
```

This raises the question whether the addition of typechecking for dependent-type-like functions should be added for type level functions created with conditional types too, for consistency purposes. Two points worth noting is that: users were never able to implement this behaviour using conditional types (even pre-3.5), and, type level functions with conditional types are not restricted to a domain of string keys which makes things more complex. Nevertheless, we feel it is a point worth bringing up for discussion.

## Behaviour with `any`

The result of instantiating a dependent-type-like function with the `any` type gives a result of `any`. This occurs, for example, when disabling `--strictNullChecks` and calling the function with `null`. Any behaviour related to interaction with `null`/`any` and dependent-type-like functions is supposed to be unchanged compared to 3.5.

# Compiler Changes

In this section we roughly outline the suspected changes to the compiler needed to implement this extension.

- The main change is an addition to the `checkReturnStatement` (checker.ts) function. When the criteria for enabling dependent-type-like function checking are true, we instantiate the type parameter based on a lookup of checks with literals in the control flow graph. These criteria are currently: the index type is a type parameter, this type parameter is declared in the enclosing function, the index type can be used to index the object type and the object type is concrete.
- To be able to check the control flow graph in return statements, the graph for return statements needs to be bound in the `bindWorker` function (binder.ts).

# Workaround

The current suggested workaround seems to be unsafe type assertions or overloaded signatures, both of which are unsafe features. Neither are satisfactory since the typechecker does not help in preventing programmer mistakes when implementing dependent-type-like functions.

# Related Suggestions

The following list gathers related suggestions.

1. extending the TypeScript syntax, such as a `oneof` generic constraint: [#25879](https://github.com/microsoft/TypeScript/issues/25879), [#27808](https://github.com/microsoft/TypeScript/issues/27808) or [#30284](https://github.com/microsoft/TypeScript/pull/30284)
2. dependent types in TypeScript, which would have a huge impact on the compiler and is possibly out of scope for the TypeScript project
3. this extension is a more refined idea based on previous ideas of narrowing types based on term-level checks such as [#21879](https://github.com/microsoft/TypeScript/issues/21879)

## Complementary to `oneof` constraints

This proposal has some overlapping use cases with proposals which propose to extend TypeScript with a form of `oneof` generic constraint, as mentioned in point 1. This proposal is not competing with these, but rather should be seen as complementary. The `oneof` proposals suggest a new generic constraint which is more restrictive in which instantiations it allows. However, for many of these use cases this is only part of the solution. In addition to adding this syntax, the typechecker must also take this restriction into account to typecheck the original use cases. This proposal kickstarts the implementation of this additional behaviour by focusing on a more constrained use case which does not need this new constraint. If a `oneof` generic constraint is added to TypeScript, the behaviour defined in this proposal can be extended to take this additional constraint into account.

# Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

NOTE: (Regarding bullet point 1) The goal of this proposal is to provide more _complete_ typechecking than 3.5, and thus we want to avoid breaking any code compared to 3.5.

### LINKED ISSUE #33912: Relate control flow to conditional types in return types
## Search Terms

control flow conditional return type cannot assign extends

## Suggestion

Developers are eager to use conditional types in functions, but this is unergonomic:
```ts
type Person = { name: string; address: string; };
type Website = { name: string; url: URL };
declare function isWebsite(w: any): w is Website;
declare function isPerson(p: any): p is Person;

function getAddress<T extends Person | Website>(obj: T): T extends Person ? string : URL {
  if (isWebsite(obj)) {
    // Error
    return obj.url;
  } else if (isPerson(obj)) {
    // Another error
    return obj.address;
  }
  throw new Error('oops');
}
```

The errors here originate in the basic logic:

 > `obj.url` is a `URL`, and a `URL` isn't a `T extends Person ? string : URL`

By some mechanism, this function should *not* have an error.

## Dead Ends

The current logic is that all function return expressions must be assignable to the explicit return type annotation (if one exists), otherwise an error occurs.

A tempting idea is to change the logic to "Collect the return type (using control flow to generate conditional types) and compare that to the annotated return type". This would be a bad idea because the function implementation would effectively reappear in the return type:
```ts
function isValidPassword<T extends string>(s: T) {
  if (s === "very_magic") {
    return true;
  }
  return false;
}

// Generated .d.ts
function isValidPassword<T extends string>(s: T): T extends "very_magic" ? true : false;
```
For more complex implementation bodies, you could imagine extremely large conditional types being generated. This would be Bad; in most cases functions don't intend to reveal large logic graphs to outside callers or guarantee that that is their implementation.

## Proposal Sketch

The basic idea is to modify the contextual typing logic for `return` expressions:
```ts
type SomeConditionalType<T> = T extends string ? 1 : -1;
function fn<T>(arg: T): SomeConditionalType<T> {
    if (typeof arg === "string") {
        return 1;
    } else {
        return -1;
    }
}
```

Normally `return 1;` would evaluate `1`'s type to the simple literal type `1`, which in turn is not assignable to `SomeConditionalType<T>`. Instead, in the presence of a conditional contextual type, TS should examine the control flow graph to find narrowings of `T` and see if it can determine which branch of the conditional type should be chosen (naturally this should occur recursively).

In this case, `return 1` would produce the expression type `T extends string ? 1 : never` and `return -1` would produce the expression type `T extends string ? never : -1`; these two types would both be assignable to the declared return type and the function would check successfully.

#### Challenges

Control flow analysis currently computes the *type of an expression* given some node in the graph. This process would be different: The type `1` does not have any clear relation to `T`. CFA would need to be capable of "looking for" `T`s to determine which narrowings are in play that impact the check type of the conditional.

#### Limitations

Like other approaches from contextual typing, this would not work with certain indirections:
```ts
type SomeConditionalType<T> = T extends string ? 1 : -1;
function fn<T>(arg: T): SomeConditionalType<T> {
    let n: -1 | 1;
    if (typeof arg === "string") {
        n = 1;
    } else {
        n = -1;
    }
    // Not able to detect this as a correct return
    return n;
}
```

Open question: Maybe this isn't specific to `return` expressions? Perhaps this logic should be in play for *all* contextual typing, not just `return` statements:
```ts
type SomeConditionalType<T> = T extends string ? 1 : -1;
function fn<T>(arg: T): SomeConditionalType<T> {
    // Seems to be analyzable the same way...
    let n: SomeConditionalType<T>;
    if (typeof arg === "string") {
        n = 1;
    } else {
        n = -1;
    }
    return n;
}
```

#### Fallbacks

The proposed behavior would have the benefit that TS would be able to detect "flipped branch" scenarios where the developer accidently inverted the conditional (returning `a` when they should have returned `b` and vice versa).

That said, if we can't make this work, it's tempting to just change assignability rules specifically for `return` to allow `return`s that correspond to either side of the conditional - the status quo of requiring very unsafe casts everywhere is not great. We'd miss the directionality detection but that'd be a step up from having totally unsound casts on all branches.

## Use Cases / Examples

TODO: Many issues have been filed on this already; link them

## Workarounds

```ts
// Write-once helper
function conditionalProducingIf<LeftIn, RightIn, LeftOut, RightOut, Arg extends LeftIn | RightIn>(
    arg: Arg,
    cond: (arg: LeftIn | RightIn) => arg is LeftIn,
    produceLeftOut: (arg: LeftIn) => LeftOut,
    produceRightOut: (arg: RightIn) => RightOut):
    Arg extends LeftIn ? LeftOut : RightOut
{
    type OK = Arg extends LeftIn ? LeftOut : RightOut;
    if (cond(arg)) {
        return produceLeftOut(arg) as OK;
    } else {
        return produceRightOut(arg as RightIn) as OK;
    }
}

// Write-once helper
function isString(arg: any): arg is string {
    return typeof arg === "string";
}

// Inferred type
// fn: (arg: T) => T extends string ? 1 : -1
function fn<T>(arg: T) {
    return conditionalProducingIf(arg, isString,
        () => 1 as const,
        () => -1 as const);
}

let k = fn(""); // 1
let j = fn(false); // -1
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
   * All of these are errors at the moment
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #33912.
Fixes #33014.

## Motivation

Sometimes we want to write functions whose return type is picked between different options, depending on the type of a parameter. For instance:

```ts
declare const record: Record<string, string>;
declare const array: string[];

function getObject(group) {
    if (group === undefined) {
        return record;
    }
    return array;
}

const arrayResult = getObject("group");
const recordResult = getObject(undefined);
```

If we want to precisely express this dependency between the return type and the type of `nameOrId`, we have a few options.
The first one is to use overloads:

```ts
declare const record: Record<string, string[]>;
declare const array: string[];

function getObject(group: undefined): Record<string, string[]>;
function getObject(group: string): string[];
function getObject(group: string | undefined): string[] | Record<string, string[]>;
function getObject(group: string | undefined): string[] | Record<string, string[]> {
    if (group === undefined) {
        return record;
    }
    return array;
}

const arrayResult = getObject("group");
const recordResult = getObject(undefined);
```

However, if you make a mistake in the implementation of the function and return the wrong type, TypeScript will not warn you. For instance, if instead you implement the function like this:

```ts
declare const record: Record<string, string[]>;
declare const array: string[];

function getObject(group: undefined): Record<string, string[]>;
function getObject(group: string): string[];
function getObject(group: string | undefined): string[] | Record<string, string[]>;
function getObject(group: string | undefined): string[] | Record<string, string[]> {
    if (!group) { // An empty string is falsy
        return record;
    }
    return array;
}

const badResult = getObject(""); // Type says this returns `string[]`, but actually it returns a record.
```
then your function implementation doesn't respect the overload signatures, but TypeScript will not error.

The alternative to overloads is to use conditional types, like so:

```ts
declare const record: Record<string, string[]>;
declare const array: string[];

function getObject<T extends string | undefined>(group: T):
    T extends string ? string[] : T extends undefined ? Record<string, string[]> : never {
    if (group === undefined) {
        return record; // Error! Type 'Record<string, string[]>' is not assignable to type 'T extends string ? string[] : T extends undefined ? Record<string, string[]> : never'.
    }
    return array; // Error! Type 'string[]' is not assignable to type 'T extends string ? string[] : T extends undefined ? Record<string, string[]> : never'
}

const arrayResult = getObject("group");
const recordResult = getObject(undefined);
```

However, while everything works out for the callers of `getObject`, in the implementation TypeScript errors on the return statements, because it compares the type of the return expression to the annotated conditional return type, and `Record<string, string[]>` is not assignable to `T extends undefined ? Record<string, string[]> : never`.

## Solution: conditional return type narrowing

For this PR, I propose a way of checking return statements that understands cases like above.
The idea is that, for the function above:

```ts
function getObject<T extends string | undefined>(group: T):
    T extends string ? string[] : T extends undefined ? Record<string, string[]> : never {
    if (group === undefined) {
        return record;
    }
    return array;
}
```

when checking the return statement `return record`, TS will know that `group` has type `undefined`. TS will also know that type parameter `T` corresponds exactly to the type of `group`. Combining those two pieces of information, TS will know that, inside that branch, the expected return type has to be `Record<string, string[]>` (or a supertype). Then, instead of checking `return record`'s type against `T extends string ? string[] : T extends undefined ? Record<string, string[]> : never`, it will check `return record`'s type against the `Record<string, string[]>` branch of the conditional, i.e. a narrowed version of the conditional type. Then there will be no error on the return statement. In the same manner, when checking the return statement `return array`, TS will know that `group` has type `string`, and that therefore it can check the type of the return statement against the `string[]` branch of the conditional return type.

For now, we can think of it like this: when we check return statement `return record`, we see that `group` has narrowed type `undefined`. Then, we plug that information back into the return type by instantiating `T extends string ? string[] : T extends undefined ? Record<string, string[]> : never` with `T` replaced by `undefined`.

### Conditional types

Reasoning about conditional types is pretty tricky. In general, given a function `f(...args): SomeConditionalType` whose return type is some (generic) conditional type, we are not able to do the special check proposed above, because it wouldn't be safe.
We need to place some restrictions on what the conditional return type looks like in order for TS to safely analyze it.

We can safely analyze a conditional return type that has the shape `T extends A ? AType : T extends B ? BType : never`.
This means the conditional type needs to be distributive (i.e. its check type is a naked type parameter `T`) and have `never` as its false-most type, and it cannot have `infer` type parameters (e.g. it cannot be `T extends [infer A] ? AType : T extends B ? BType : never`).

Intuitively, we can think of this conditional type shape as reflecting the kind of code one would write in the implementation of such a function.

In addition to the previous restrictions on the conditional type, the extends types of the conditional (`A` and `B` above), have to be constituents of the type parameter's constraint (`T` above), like so:
```ts
function fun<T extends A | B>(param: T): T extends A ? AType : T extends B ? BType : never {
    if (isA(param)) { ... }
    else { ... }
}
```
This is because, to narrow the return type, we first need to narrow the type of `param` (more on that below). When we narrow the type of `param`, in a lot of scenarios, we will start from its type, `T`, or in this case its type constraint, `A | B`. Then, we will further narrow that type based on information from control flow analysis, e.g. to pick either `A` or `B` (see `getNarrowableTypeForReference` in `checker.ts`).

Therefore, in this typical case, narrowing `param` means we will end up with a type that is either `A`, `B`, or a subtype of those. In turn, when we plug this narrowed type back into the conditional return type, this means we will be able to pick a branch of the conditional type and resolve it. e.g. if the narrowed type of `param` is `A`, the conditional type will resolve to `AType`.

This restriction also reinforces that you want your return type to closely match the structure of your implementation.

#### Aside: why `never`

A common way of trying to write a conditional return type is like the following:

```ts
function stringOrNumber<T extends string | number>(param: T): T extends string ? string : number {
  if (typeof param === "string") {
    return "some string";
  }
  return 123;
}

const num = stringOrNumber(123);
const str = stringOrNumber("string");
declare let strOrNum: string | number;
const both = stringOrNumber(strOrNum);
```

This example works fine and it would be safe for TS to allow that function implementation. However, in general, it is not safe to allow this pattern of conditional return type. Consider this case:

```ts
function aStringOrANumber<T extends { a: string } | { a: undefined }>(param: T): T extends { a: string } ? string : number {
  if (typeof param.a === "string") {
    return "some string";
  }
  return 123;
}

const aNum = aStringOrANumber({ a: undefined });
const aStr = aStringOrANumber({ a: "" });
// Bad! Type says `number`, but actually should say `string | number`
const aNotBoth = aStringOrANumber({ a: strOrUndef });
```
The problem boils down to the fact that, when a conditional return type resolves to its false branch, we can't know if the check type is related or not to the extends type. For the example above, when we plug in `{ a: undefined }` for `T` in `T extends { a: string } ? string : number`, then we fall into the false branch of the conditional, which is desired because `{ a: undefined }` does not overlap `{ a: string }`. However, when we plug in `{ a: string | undefined }` for `T` in `T extends { a: string } ? string : number`, we fall into the false branch of the conditional, but this is not desired because `{ a: string | undefined }` overlaps `{ a: string }`, and therefore the return type could actually be `string`.

Resolving a conditional type to its false-most branch of a conditional type doesn't provide TS with enough information to safely determine what the return type should be, and because of that, narrowing a conditional return type requires the false-most branch of the conditional to be `never`.

### Type parameter references

As hinted at above, to narrow a conditional return type, we first need to narrow a parameter, and we need to know that the type of that parameter uniquely corresponds to a type parameter.
Revisiting our example:
```ts
function getObject<T extends string | undefined>(group: T):
    T extends string ? string[] : T extends undefined ? Record<string, string[]> : never {
    if (group === undefined) {
        return record;
    }
    return array;
}
```

To narrow the return type `T extends string ? string[] : T extends undefined ? Record<string, string[]> : never`, we first narrow the type of `group` inside the `if` branch, and then we can use that information to reason about what type `T` could be replaced with. This only works because the declared type of `group` is exactly `T`, and also because there are no other parameters that use type `T`. So in the following cases, TS would not be able to narrow the return type, because there is no unique parameter to which `T` is linked:

```ts
function badGetObject1<T extends string | undefined>(group: T, someOtherParam: T):
    T extends string ? string[] : T extends undefined ? Record<string, string[]> : never {
    ...
}

function badGetObject2<T extends string | undefined>(group: T, options: { a: number, b: T }):
    T extends string ? string[] : T extends undefined ? Record<string, string[]> : never {
    ...
}
```

## Indexed access types

The reasoning explained above for conditional types applies in a similar manner to indexed access types that look like this:

```ts
interface F {
  "t": number,
  "f": boolean,
}

function depLikeFun<T extends "t" | "f">(str: T): F[T] {
  if (str === "t") {
    return 1;
  } else {
    return true;
  }
}

depLikeFun("t"); // has type number
depLikeFun("f"); // has type boolean
```
So cases like this, where the return type is an indexed access type with a type parameter index, are also supported by this PR. The thinking is similar: in the code above, when we are in the `if (str === "t") { ... }` branch, we know `str` has type `"t"`, and we can plug that information back into the return type `F[T]` which resolves to type `number`, and similarly for the `else` branch.

## Implementation

The implementation works roughly like this:
When checking a return statement expression:
- We check if the type of the expression is assignable to the return type. If it is, good, nothing else needs to be done. This makes sure we don't introduce new errors to existing code.
- If the type of the expression is not assignable to the return type, we might need to narrow the return type and check again. We proceed to attempt narrowing the return type.
- We check if the return type has the right shape, i.e. it has a shape of either `SomeType[T]` or `T extends A ? AType : T extends B ? BType : never`, and what parameters the type parameters are uniquely linked to, among other requirements. If any of those requirements is not met, we don't continue with narrowing.
- For every type parameter that is uniquely linked to a parameter, we obtain its narrowed type.
   + Say we have type parameter `T` that is uniquely linked to parameter `param`. To narrow the return type, we first need to obtain the narrowed type for `param` at the return statement position. Because, in the source code, there might not be an occurrence of `param` at the return statement position, we create a synthetic reference to `param` at that position and obtain its narrowed type via regular control-flow analysis. We then obtain a narrowed type `N` for `param`. (If we don't, we'll just ignore that type parameter).
- Once we have the narrowed type for each type parameter, we need to plug that information back into the return type. We do this by instantiating the return type with a substitution type. For instance, if the return type is `T extends A ? AType : T extends B ? BType : never`, `T` is linked to `param`, and `param` has narrowed type `N`, we will instantiate the return type with `T` replaced by `T & N` (as a substitution type).
- Once we obtain this narrowed return type, we get the type of the return expression, this time contextually checked by the narrowed return type, and then check if this type is assignable to the narrowed return type.

### Instantiation

As mentioned above, the process of narrowing a return type is implemented as instantiating that return type with the narrowed type parameters replaced by substitution types. Substitution types can be thought of as `T & A`, where `T` is the base type and `A` the constraint type. There are a few changes made to instantiation to make this work:

- There is now a new kind of substitution type, indicated by the `ObjectFlags.IsNarrowingType` flag, which corresponds to substitution types created by return type narrowing.
- These narrowing substitution types are handled in a special way by conditional type instantiation functions, i.e. `getConditionalTypeInstantiation`, and `getConditionalType`.
- `getConditionalTypeInstantiation` is responsible for distributing a conditional type over its check type. When instantiating a distributive conditional type in `getConditionalTypeInstantiation`, if the conditional's check type is a substitution type like `T & (A | B)`, the usual logic would not distribute over this type, because it's a substitution type and not a union type. So, for distribution to happen, we have to take apart the `T & (A | B)` into `(T & A) | (T & B)`, and distribute over that.
- The other special thing that we have to do in `getConditionalTypeInstantiation` is to take the intersection of the distribution result, as opposed to the union. This is because, if we narrow a type parameter `T` to `A | B`, and we have a conditional return type `T extends A ? R1 : T extends B ? R2 : T extends C ? R3 : never`, then we don't know which branch of the conditional return to pick, if branch `T extends A ? R1`, or branch `T extends B ? R2`, so we have to check whether the return expression's type is assignable to both, i.e. assignable to `R1 & R2`.
- Validating whether the conditional type has the right shape to be narrowed happens on-demand in `getConditionalTypeInstantiation` (and also at first as an optimization in `checkReturnExpression` when we're deciding whether to narrow the return type). This is because, as we instantiate a type, we may produce new conditional types that we need to then decide are safe to narrow or not (see [nested types case in `dependentReturnType6.ts` test](https://github.com/microsoft/TypeScript/pull/56941/files#diff-f40212beae0a9723380268c8a63a1560e91b9431a1fda539b2092cd4778e5fcfR28-R51)).

## Conditional expression checking

To support conditional expression checking in return statements, this PR changes how we check a conditional expression in a return statement. Before this PR, when checking a return statement `return cond ? exp1 : exp2`, we obtain the type of the whole expression `cond ? exp1 : exp2`, and then compare that type to the return type. With this PR, we now separately check each branch: we first obtain the type of `exp1`, and compare that type to the return type, then obtain the type of `exp2` and compare that type to the return type. This allows us to properly check a conditional expression when return type narrowing is needed.

This a breaking change, and the only change that affects existing code, but this change finds bugs. *Analysis of extended tests changes: https://github.com/microsoft/TypeScript/pull/56941#issuecomment-2406411716.*
This change also slightly affects performance because we do more checks. *Latest perf results here: https://github.com/microsoft/TypeScript/pull/56941#issuecomment-2403351320.*

## Performance results

This feature is opt-in. Currently, virtually no code has functions whose return types are conditional or indexed access types that satisfy the restrictions above, so no code goes down the new code path for narrowing return types. This means for existing code, there's no performance impact from the return type narrowing.  The only current performance impact is from the conditional expression checking change (see a version of this PR without the change for conditional expressions: https://github.com/microsoft/TypeScript/pull/60268#issuecomment-2421064260).

Assessing the performance of the new code path is tricky, as there are no baselines. The existing alternative to conditional return types is to use overloads. In one scenario I tested, checking a function written with conditional return types with this PR took ~+16% check time compared to the same function using overloads and the main branch. However, that's for checking the function declaration. In a different scenario where I included a lot of *function calls* though, the version with conditional return types + this PR took ~-15% compared to overloads + main branch. So I'd say the performance is acceptable, especially considering you get stronger checks when using conditional return types, and also only a small number of functions in a codebase should be written using this feature.

## Unsupported things

- Inference:
TS will not infer a conditional return type or an indexed access type for any function or expression. Inferring such a type is more complicated than checking, and inferring such a type could also be surprising for users. This is out of scope.

- Contextually-typed anonymous functions:

```ts
type GetObjectCallback = <T extends string | undefined>(group: T) => T extends string ? string[] : T extends undefined ? Record<string, string[]> : never;

const getObjectBad1: GetObjectCallback =
    (group) => { return group === undefined ? record : array }; // Error

declare function outerFun(callback: GetObjectCallback);
outerFun((group) => { return group === undefined ? record : array }); // Error
```
This is because, if your function does not have an explicitly annotated return type, we will infer one from the returns.

- Detection of link between parameter and type parameter in more complicated scenarios:
```ts
// All cases below are not recognized
// Type alias
type Id<X> = X;
function f2<T extends boolean>(arg: Id<T>): T extends true ? string : T extends false ? number : never {
  if (arg) {
    return "someString";
  }
  return 123;
}

// Property type
function f3<T extends boolean>(arg: { prop: T }): T extends true ? string : T extends false ? number : never {
  if (arg.prop) {
    return "someString";
  }
  return 123;
}

// Destructuring
function f4<T extends boolean>({ arg }: { arg: T }): T extends true ? string : T extends false ? number : never {
  if (arg.prop) {
    return "someString";
  }
  return 123;
}

// Combinations of the above, e.g.:
type Opts<X> = { prop: X };
function f5<T extends boolean>(arg: Opts<T>): T extends true ? string : T extends false ? number : never {
  if (arg.prop) {
    return "someString";
  }
  return 123;
}
```
This could be supported in the future.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test public

**Comment by gabritto** [comment]
@typescript-bot perf test this faster
@typescript-bot perf test this public

**Comment by gabritto** [comment]
I did local perf testing of this branch vs main (commit 1982349339b9c1fd78c93195d572ffc6fd5041b0). I ran tsc on a project with 10 copies of a file with the code in https://github.com/microsoft/TypeScript/blob/c73638300f2e4621cb0538fd1123f8a2fdf9e5ab/tests/cases/compiler/dependentReturnType3.ts, which is adapted from existing functions in some github repos, by changing the functions to instead of overloads, use conditional types as their return types.

Results were:
<details>
<summary>Run with errors</summary>

**Comparison Report - main..gabritto/d2-detect**  
<table border="0" cellpadding="0" cellspacing="0">
<thead>
<tr>
<th align="left">Metric</th>
<th align="right">main</th>
<th align=right>gabritto/d2-detect</th>
<th align="right">Delta</th>
<th align="right">Best</th>
<th align="right">Worst</th>
<th align="right">p-value</th>
</tr>
</thead>
<tr><th align="left" colspan="7">condperf - node (v20.11.0, x64)</th></tr>
<tbody><tr>
<td align="left" valign="middle"><nobr>Memory used</nobr></td>
<td align="right" valign="top">149,696k<br /><sup>±0.00%</sup></td>
<td align="right" valign="top">149,254k<br /><sup>±0.00%</sup></td>
<td align="right" valign="top">-442k<br /><sup>-0.30%</sup></td>
<td align="right" valign="top">149,254k</td>
<td align="right" valign="top">149,254k</td>
<td align="right" valign="top">p=0.000 n=10</td>
</tr><tr>
<td align="left" valign="middle"><nobr>Parse Time</nobr></td>
<td align="right" valign="top">0.91s<br /><sup>±0.33%</sup></td>
<td align="right" valign="top">0.91s<br /><sup>±0.41%</sup></td>
<td align="right" valign="top">-0.01s<br /><sup>-0.77%</sup></td>
<td align="right" valign="top">0.90s</td>
<td align="right" valign="top">0.91s</td>
<td align="right" valign="top">p=0.008 n=10</td>
</tr><tr>
<td align="left" valign="middle"><nobr>Bind Time</nobr></td>
<td align="right" valign="top">0.42s<br /><sup>±0.87%</sup></td>
<td align="right" valign="top">0.41s<br /><sup>±0.82%</sup></td>
<td align="right" valign="top">&#126;</td>
<td align="right" valign="top">0.41s</td>
<td align="right" valign="top">0.42s</td>
<td align="right" valign="top">p=0.204 n=10</td>
</tr><tr>
<td align="left" valign="middle"><nobr>Check Time</nobr></td>
<td align="right" valign="top">3.22s<br /><sup>±0.36%</sup></td>
<td align="right" valign="top">3.15s<br /><sup>±0.34%</sup></td>
<td align="right" valign="top">-0.07s<br /><sup>-2.17%</sup></td>
<td align="right" valign="top">3.13s</td>
<td align="right" valign="top">3.18s</td>
<td align="right" valign="top">p=0.000 n=10</td>
</tr><tr>
<td align="left" valign="middle"><nobr>Emit Time</nobr></td>
<td align="right" valign="top">0.00s<br /><sup>±0.00%</sup></td>
<td align="right" valign="top">0.00s<br /><sup>±0.00%</sup></td>
<td align="right" valign="top">&#126;</td>
<td align="right" valign="top">0.00s</td>
<td align="right" valign="top">0.00s</td>
<td align="right" valign="top">p=1.000 n=10</td>
</tr><tr>
<td align="left" valign="middle"><nobr>Total Time</nobr></td>
<td align="right" valign="top">4.55s<br /><sup>±0.24%</sup></td>
<td align="right" valign="top">4.47s<br /><sup>±0.31%</sup></td>
<td align="right" valign="top">-0.08s<br /><sup>-1.76%</sup></td>
<td align="right" valign="top">4.44s</td>
<td align="right" valign="top">4.50s</td>
<td align="right" valign="top">p=0.000 n=10</td>
</tr>
</tbody>
</table>  

**System**  
<table border="0" cellpadding="0" cellspacing="0">
<tbody>
<tr><th align="right">Machine Name</th><td>CPC-gabri-8SHBT</td></tr>
<tr><th align="right">Platform</th><td>linux 5.15.133.1-microsoft-standard-WSL2</td></tr>
<tr><th align="right">Architecture</th><td>x64</td></tr>
<tr><th align="right">Available Memory</th><td>31 GB</td></tr>
<tr><th align="right">CPUs</th><td>16 × AMD EPYC 7763 64-Core Processor</td></tr>
</tbody>
</table>  

**Hosts**  
* node (v20.11.0, x64)
  

**Scenarios**  
* condperf - node (v20.11.0, x64)
  

**Summary**  
<table cellspacing="0" cellpadding="0" border="0">
<tr>
<th align="left">Benchmark</th>
<th align="left">Name</th>
<th align="left">Iterations</th>
</tr>
<tr>
<td>Current</td>
<td>gabritto/d2-detect</td>
<td>10</td>
</tr>
<tr>
<td>Baseline</td>
<td>main</td>
<td>10</td>
</tr>
</table>

</details>

**Comment by gabritto** [comment]
Still regarding perf, I did some profiling of my PR running on the same input as the perf test described above (the original version, with conditional return types and no casts to any). Looks like the PR roughly doubles the time spent on `checkReturnStatementExpression` (which doesn't exist on main but corresponds to checking the return statement expression + checking if the return statement expression's type is assignable to the function's return type). From that extra time the PR spends on that function, half of it is on detection of which expression to use as base for return type narrowing.

**Comment by gabritto** [comment]
Update on perf tests:

There was an omission in the implementation that I tested in my previous comment: it didn't check if the return expression's type was already assignable to the original (unnarrowed) return type. I have added that check, which unfortunately means my PR does even more work now. I redid two of the same perf tests mentioned above:

<details>
<summary>main vs PR (test has `@ts-ignore` where main would error)</summary>
<b>Comparison Report - main..gabritto/d2-detect</b>
<table border="0" cellpadding="0" cellspacing="0" >
<thead>
<tr>
<th align=left><sub>Metric</sub></th>
<th align=right><sub>main</sub></th>
<th align=right><sub>gabritto/d2-detect</sub></th>
<th align=right><sub>Delta</sub></th>
<th align=right><sub>Best</sub></th>
<th align=right><sub>Worst</sub></th>
<th align=right><sub>p-value</sub></th>
</tr>
</thead>
<tr class="group"><th align=left colspan="7"><sub>condperfignore - node (v20.11.0, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>89,916k (± 0.00%)</sub></td>
<td align=right><sub>89,317k (± 0.00%)</sub></td>
<td align=right><sub>-599k (- 0.67%)</sub></td>
<td align=right><sub>89,317k</sub></td>
<td align=right><sub>89,317k</sub></td>
<td align=right><sub>p=0.000 n=10</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>0.93s (± 0.51%)</sub></td>
<td align=right><sub>0.92s (± 0.32%)</sub></td>
<td align=right><sub>-0.01s (- 1.29%)</sub></td>
<td align=right><sub>0.91s</sub></td>
<td align=right><sub>0.92s</sub></td>
<td align=right><sub>p=0.001 n=10</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>0.42s (± 0.53%)</sub></td>
<td align=right><sub>0.42s (± 0.70%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.42s</sub></td>
<td align=right><sub>0.43s</sub></td>
<td align=right><sub>p=0.583 n=10</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>0.44s (± 0.78%)</sub></td>
<td align=right><sub>0.39s (± 0.57%)</sub></td>
<td align=right><sub>🟩-0.05s (-10.98%)</sub></td>
<td align=right><sub>0.38s</sub></td>
<td align=right><sub>0.39s</sub></td>
<td align=right><sub>p=0.000 n=10</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>0.00s (± 0.00%)</sub></td>
<td align=right><sub>0.00s (± 0.00%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.00s</sub></td>
<td align=right><sub>0.00s</sub></td>
<td align=right><sub>p=1.000 n=10</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>1.79s (± 0.47%)</sub></td>
<td align=right><sub>1.73s (± 0.19%)</sub></td>
<td align=right><sub>🟩-0.06s (- 3.41%)</sub></td>
<td align=right><sub>1.72s</sub></td>
<td align=right><sub>1.74s</sub></td>
<td align=right><sub>p=0.000 n=10</sub></td>
</tr>
</tbody>
</table>
<div>
<b>System</b>
<table cellpadding="0" cellspacing="0" border="0" >
<tr><th align=right><sub>Machine Name</sub></th><td><sub>CPC-gabri-8SHBT</sub></td></tr>
<tr><th align=right><sub>Platform</sub></th><td><sub>linux 5.15.133.1-microsoft-standard-WSL2</sub></td></tr>
<tr><th align=right><sub>Architecture</sub></th><td><sub>x64</sub></td></tr>
<tr><th align=right><sub>Available Memory</sub></th><td><sub>31 GB</sub></td></tr>
<tr><th align=right><sub>Available Memory</sub></th><td><sub>30 GB</sub></td></tr>
<tr><th align=right><sub>CPUs</sub></th><td><sub>16 × AMD EPYC 7763 64-Core Processor</sub></td></tr>
</table>
</div>
<div>
<b>Hosts</b>
<ul>
<li>node (v20.11.0, x64)</li>
</ul>
</div>
<div>
<b>Scenarios</b>
<ul>
<li>condperfignore - node (v20.11.0, x64)</li>
</ul>
</div>
<div>
<table cellspacing="0" cellpadding="0" border="0" >
<tr>
<th align=left><sub>Benchmark</sub></th>
<th align=left><sub>Name</sub></th>
<th align=left><sub>Iterations</sub></th>
</tr>
<tr>
<td><sub>Current</sub></td>
<td><sub>gabritto/d2-detect</sub></td>
<td><sub>10</sub></td>
</tr>
<tr>
<td><sub>Baseline</sub></td>
<td><sub>main</sub></td>
<td><sub>10</sub></td>
</tr>
</table>
</div>

</details>

<details>
<summary>main on test with overloads vs PR on test with conditional types</summary>
<b>Comparison Report - main..gabritto/d2-detect</b>
<table border="0" cellpadding="0" cellspacing="0" >
<thead>
<tr>
<th align=left><sub>Metric</sub></th>
<th align=right><sub>main</sub></th>
<th align=right><sub>gabritto/d2-detect</sub></th>
<th align=right><sub>Delta</sub></th>
<th align=right><sub>Best</sub></th>
<th align=right><sub>Worst</sub></th>
<th align=right><sub>p-value</sub></th>
</tr>
</thead>
<tr class="group"><th align=left colspan="7"><sub>overloadperf - node (v20.11.0, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>89,903k (± 0.00%)</sub></td>
<td align=right><sub>89,321k (± 0.00%)</sub></td>
<td align=right><sub>-582k (- 0.65%)</sub></td>
<td align=right><sub>89,321k</sub></td>
<td align=right><sub>89,321k</sub></td>
<td align=right><sub>p=0.000 n=10</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>0.94s (± 0.36%)</sub></td>
<td align=right><sub>0.91s (± 0.44%)</sub></td>
<td align=right><sub>-0.03s (- 2.99%)</sub></td>
<td align=right><sub>0.90s</sub></td>
<td align=right><sub>0.92s</sub></td>
<td align=right><sub>p=0.000 n=10</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>0.42s (± 0.86%)</sub></td>
<td align=right><sub>0.42s (± 0.53%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.42s</sub></td>
<td align=right><sub>0.43s</sub></td>
<td align=right><sub>p=0.144 n=10</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>0.36s (± 0.62%)</sub></td>
<td align=right><sub>0.39s (± 0.57%)</sub></td>
<td align=right><sub>🔻+0.03s (+ 8.91%)</sub></td>
<td align=right><sub>0.39s</sub></td>
<td align=right><sub>0.40s</sub></td>
<td align=right><sub>p=0.000 n=10</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>0.00s (± 0.00%)</sub></td>
<td align=right><sub>0.00s (± 0.00%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.00s</sub></td>
<td align=right><sub>0.00s</sub></td>
<td align=right><sub>p=1.000 n=10</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>1.72s (± 0.32%)</sub></td>
<td align=right><sub>1.72s (± 0.34%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>1.71s</sub></td>
<td align=right><sub>1.74s</sub></td>
<td align=right><sub>p=0.755 n=10</sub></td>
</tr>
</tbody>
</table>
<div>
<b>System</b>
<table cellpadding="0" cellspacing="0" border="0" >
<tr><th align=right><sub>Machine Name</sub></th><td><sub>CPC-gabri-8SHBT</sub></td></tr>
<tr><th align=right><sub>Platform</sub></th><td><sub>linux 5.15.133.1-microsoft-standard-WSL2</sub></td></tr>
<tr><th align=right><sub>Architecture</sub></th><td><sub>x64</sub></td></tr>
<tr><th align=right><sub>Available Memory</sub></th><td><sub>31 GB</sub></td></tr>
<tr><th align=right><sub>Available Memory</sub></th><td><sub>30 GB</sub></td></tr>
<tr><th align=right><sub>CPUs</sub></th><td><sub>16 × AMD EPYC 7763 64-Core Processor</sub></td></tr>
</table>
</div>
<div>
<b>Hosts</b>
<ul>
<li>node (v20.11.0, x64)</li>
</ul>
</div>
<div>
<b>Scenarios</b>
<ul>
<li>overloadperf - node (v20.11.0, x64)</li>
</ul>
</div>
<div>
<table cellspacing="0" cellpadding="0" border="0" >
<tr>
<th align=left><sub>Benchmark</sub></th>
<th align=left><sub>Name</sub></th>
<th align=left><sub>Iterations</sub></th>
</tr>
<tr>
<td><sub>Current</sub></td>
<td><sub>gabritto/d2-detect</sub></td>
<td><sub>10</sub></td>
</tr>
<tr>
<td><sub>Baseline</sub></td>
<td><sub>main</sub></td>
<td><sub>10</sub></td>
</tr>
</table>
</div>

</details>

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
I think #58013 means I can't get away with traversing the control flow graph from the return statements backwards to collect all possible references to use for narrowing a conditional type.

**Comment by jakebailey** [comment]
We may be able to introduce a flow node at each return, which just walks back to every preceding node; theoretically that would be fine because the checker wouldn't normally walk it anyway?

**Comment by Andarist** [comment]
@gabritto @jakebailey would it be possible to build a playground for this one? it would be super interesting to play with it easily :)

**Comment by gabritto** [comment]
> @gabritto @jakebailey would it be possible to build a playground for this one? it would be super interesting to play with it easily :)

I'll push a bug fix today or Monday and create a playground for it then.

**Comment by gabritto** [comment]
@typescript-bot pack this

**Comment by gabritto** [comment]
> Hey @gabritto, I've packed this into [an installable tgz](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/163836/artifacts?artifactName=tgz&fileId=FCAF4D861595C4CFC28691516AC6B69F642BE546875C2ED181BAFB43ABAF547E02&fileName=/typescript-5.7.0-insiders.20241007.tgz). You can install it for testing by referencing it in your `package.json` like so:
> 
> ```
> {
>     "devDependencies": {
>         "typescript": "https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/163836/artifacts?artifactName=tgz&fileId=FCAF4D861595C4CFC28691516AC6B69F642BE546875C2ED181BAFB43ABAF547E02&fileName=/typescript-5.7.0-insiders.20241007.tgz"
>     }
> }
> ```
> 
> and then running `npm install`.
> 
> There is also a playground [for this build](https://www.typescriptlang.org/play?ts=5.7.0-pr-56941-53) and an [npm](https://www.npmjs.com/package/@typescript-deploys/pr-build/v/5.7.0-pr-56941-53) module you can use via `"typescript": "npm:@typescript-deploys/pr-build@5.7.0-pr-56941-53"`.;

@Andarist the playground, as requested

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by gabritto** [comment]
> @gabritto Here are the results of running the user tests with tsc comparing `main` and `refs/pull/56941/merge`:
> 
> Something interesting changed - please have a look.
> 
> Details

- adonis-framework: one of the conditional return expression branches has an `error` type, such that, if you check the whole expression, it has `error` type and it masks the error on the other branch that has type `null`.
- effect: error just moved to the specific conditional return expression branch that caused the old error
- webpack: breaking change, the cast that wraps the whole conditional expression is ignored, will fix.
- puppeteer: similar to adonis-framework, one of the conditional return expression branches has `any` type, so the whole expression has type `any` and it masks the error on the other branch that has non-`any` type.

**Comment by gabritto** [comment]
> @gabritto Here are the results of running the top 400 repos with tsc comparing `main` and `refs/pull/56941/merge`:
> 
> Something interesting changed - please have a look.
> 
> Details
> ## [antvis/G2](https://github.com/antvis/G2)

Good error, `any` masking.

> ## [cheeriojs/cheerio](https://github.com/cheeriojs/cheerio)

Good error, error type masking.

> ## [GrapesJS/grapesjs](https://github.com/GrapesJS/grapesjs)

Theoretically correct error, `any` masking, but probably inconsequential, cast is needed.

> ## [honojs/hono](https://github.com/honojs/hono)

Error position changed from expression to conditional branches, need to move the `@ts-expect-error` comment.

> ## [ionic-team/stencil](https://github.com/ionic-team/stencil)

Good error, `any` masking.

> ## [jupyterlab/jupyterlab](https://github.com/jupyterlab/jupyterlab)

Seem like existing errors.

> ## [microsoft/vscode](https://github.com/microsoft/vscode)

### [src\/tsconfig.tsec.json](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/tsconfig.tsec.json)
 - `error TS2322: Type 'T | undefined' is not assignable to type 'T'.`
   - [src\/vs\/platform\/configuration\/common\/configuration.ts\#L297](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/platform/configuration/common/configuration.ts#L297): Good error, `any` masking.
 - `error TS2322: Type 'ContextKeyValue' is not assignable to type 'T | undefined'.`
   - [src\/vs\/platform\/contextkey\/browser\/contextKeyService.ts\#L522](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/platform/contextkey/browser/contextKeyService.ts#L522): Theoretically correct error, `any` masking, but probably inconsequential, cast is needed.
 - `error TS2322: Type 'Result<TArgs>' is not assignable to type 'Result<GetLeadingNonServiceArgs<TArgs>>'.`
   - [src\/vs\/platform\/observable\/common\/wrapInHotClass.ts\#L23](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/platform/observable/common/wrapInHotClass.ts#L23): Theoretically correct error, `any` masking, but probably inconsequential, cast is needed.
   - [src\/vs\/platform\/observable\/common\/wrapInHotClass.ts\#L65](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/platform/observable/common/wrapInHotClass.ts#L65): Theoretically correct error, `any` masking, but probably inconsequential, cast is needed.
   - [src\/vs\/platform\/observable\/common\/wrapInReloadableClass.ts\#L17](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/platform/observable/common/wrapInReloadableClass.ts#L17): Theoretically correct error, `any` masking, but probably inconsequential, cast is needed.
 - `error TS2322: Type 'null' is not assignable to type 'IStringDictionary<IFilterMetadata>'.`
   - [src\/vs\/workbench\/services\/preferences\/common\/preferencesModels.ts\#L108](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/workbench/services/preferences/common/preferencesModels.ts#L108): Good error, `any` masking.
 - `error TS2322: Type 'undefined' is not assignable to type 'IExpression'.`
   - [src\/vs\/workbench\/services\/search\/common\/queryBuilder.ts\#L652](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/workbench/services/search/common/queryBuilder.ts#L652): Good error, `any` masking.

> ## [nextauthjs/next-auth](https://github.com/nextauthjs/next-auth)

Good error, `any` masking.

> ## [tailwindlabs/headlessui](https://github.com/tailwindlabs/headlessui)

Theoretically correct error, `any` masking, but probably inconsequential, cast is needed.

> ## [video-dev/hls.js](https://github.com/video-dev/hls.js)

???

> ## [vuejs/devtools-v6](https://github.com/vuejs/devtools-v6)

Error position changed from expression to conditional branches, need to move the `@ts-expect-error` comment.

> ## [vuejs/vue](https://github.com/vuejs/vue)

Error position changed from expression to conditional branches, need to move the `@ts-expect-error` comment.

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
## Conditional return expression state of affairs

### Summary of error changes in user tests + top400:

| Total error changes | New errors likely to be bugs | Theoretically correct but unlikely to be bugs | Change in error position |
|----------------------|---------------------------------|-------------------------------------------------|----------------------------|
|          21                  |                      10                      |                                      6                                |                     5                  |

### Representative reduced examples:

New errors likely to be bugs:
[cheerio](https://github.com/cheeriojs/cheerio/blob/6b3437d41fc5eea01fd5be77049e52fec516c3d8/src/api/attributes.ts#L241):
```ts
const rboolean =
  /^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i;

declare function getAttr(
  elem: any,
  name: string | undefined,
  xmlMode?: boolean,
): Record<string, string> | string | undefined;

function getProp(
  el: Element,
  name: string,
  xmlMode?: boolean,
): string | undefined | Element[keyof Element] {
  return name in el
    ? // @ts-expect-error TS doesn't like us accessing the value directly here.
      el[name]
    : !xmlMode && rboolean.test(name)
      ? getAttr(el, name, false) !== undefined
      : getAttr(el, name, xmlMode);
}
```
[playground](https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240826#code/MYewdgzgLgBATgIxCANgUwIZhgXgLABQMMA9AHoAUA-AFwYCuUIAZiMPRAD4NMAOKGAJ7cIgsME7AAFmmABrNABNJ4KHFRdFaZmjidFASwgYE6ZVIOKtYTimS9OAW3oooB-mk4heaG3EyK4CjC-gCO9Ab+yhCgPtFo6MBQSgCUACQkBgDchIRawAL+MMz04m7gMADmaFAAglBqFITECWiONDBYggA0zTBgGI5oHdBwBmCVMJwwpVrM40q9RDAAHo4oALIgWrQwSKiYYEspHQBKsiBwigA8o+OV3TB3EwB8U09q9++z2guKOQRCCUygYKtUoAAFdS8JrLBIdACi6CGYCgS2IAyGI0+E3Rq3WWx2HX26Cwx2xYwm3zAcz+7yRbV8UAA2gpBCwYAyUVAALowADefX8UHocGwmLQMHGMASfWIVFIJBgAAEoBAALRoFY+JKauDqOAwAAqAGUYIE0BAwAByWAoAwKGYQTrAYCWiBfKAyGAANwwKHoksM-iSwRgMn8ADo5cQZShmRKeTGOgBCNabbaSgBkWfgJMOkeS0AoEpSMflVRq9UaCUeEsezH9EDQKRgKZwOBmNN+YCU5ZgHXB1bgFFr-UGaEe6cJLYBAF9CEA)

[vscode](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/workbench/services/search/common/queryBuilder.ts#L652):
```ts
interface IExpression {
	[pattern: string]: boolean;
}

function patternListToIExpression(...patterns: string[]): IExpression {
	return patterns.length ?
		patterns.reduce((glob, cur) => { glob[cur] = true; return glob; }, Object.create(null)) :
		undefined;
}
```
[playground](https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240826&ssl=9&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIFEAeAHKEDO+wA9iMgN4CwAUAJADa2cYkUIAXMvmFKAOYBdTgCNixADYQ4IANw0AvjRowAriARgSZJi2ggAMsG4AVYhhx5CWgBQA6eztYh8nbrxB96AgJSdzuAiJSChpaPDAVNmRHPXxbSQ8wAAtkAH5Q2hi2OLwAExUka2s+cWJhABpkBEjvZABeAD4KZBKy+mqoAXrkHhUIGWRwyLJW4QH5SoB5YQArCA1bBDxmCGsQFXFxb1r2DLVciBhQCFy5ankgA)

New errors unlikely to be bugs:
[vscode](https://github.com/microsoft/vscode/blob/0b0a580fbb8cc1433bbb20f7ffbeca2b75b315cd/src/vs/platform/contextkey/browser/contextKeyService.ts#L522)
```ts
type ContextKeyValue = null | undefined | boolean | number | string
	| Array<null | undefined | boolean | number | string>
	| Record<string, null | undefined | boolean | number | string>;

interface IContext {
	getValue<T extends ContextKeyValue = ContextKeyValue>(key: string): T | undefined;
}

class OverlayContext implements IContext {
  private parent!: IContext;
  private overlay!: ReadonlyMap<string, any>;

	getValue<T>(key: string): T | undefined {
		return this.overlay.has(key)
      ? this.overlay.get(key)
      : this.parent.getValue(key); // The type of this call is `ContextKeyValue`, which is not assignable to `T`.
	}
}
```
[playground](https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240826#code/C4TwDgpgBAwg9gO2BAHsA0hEA1AhgGwFdoBeKBQ-fKAHykIQBMIAzASwQkdqgCM44+CLgQ8KAW14QATjwDOwaRwDmAWABQASDoBBadNwgAPBSo8Gzdp251+g4aLoSpsugqUJlAPg3aoAJQgAYzhpRiN3FQAackpqOgtWDi4eOyERMUJJGXlFFS8Abg0NDmRpFlwg6ABJeCRUYCgAb19lCGA8IggjABUoBogmOVhEZDRMHAJiKDI6sYwsTuIvAAoAaywALihIzwBKbb6EpiTrIvUAX2L1IPxcOWGAeQA3GTuQOYaoNnEwIXFBsBhrVRl8WuooFAwEpnrhkFDcNJAQBCbYg+poc6Q6FsWHwuCvaTvVEBYSMRD4EAAWVwYAieU8MREIEK100bQ6U26PVWGxA212ygOUCO9BOVhS4M0miRwEI0lEwAAFmw5AA6AlvQxqpX3dZYPYaSHGqAAfigytVGsJ7zVHP1IENEJNUG2lvVYERgLt7SWEAdewKUAA9MGRUroKBIFA4CwLSrhkECNRVVAAAafcaLLlpmIAdxVQSV32GCDgjXucjYygQuF4QgtcHTPTTat8V0uGiAA)

Position change:
[vue](https://github.com/vuejs/vue/blob/73486cb5f5862a443b42c2aff68b82320218cbcd/src/platforms/web/runtime/directives/show.ts#L10)
```ts
interface VNode {
  componentInstance?: { _node: VNode };
}
interface VNodeWithData extends VNode {
  data: object;
}

function locateNode(vnode: VNode | VNodeWithData): VNodeWithData {
  // @ts-expect-error
  return vnode.componentInstance // Error currently happens on this line and is supressed
    ? locateNode(vnode.componentInstance._node)
    : vnode // With change, error shifts to this line
}
```
[playground](https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240826&ssl=13&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgGoDkD2ATFBvAWAChlkFMBbAB0xAnAEkQBnMOEJAfgC5k9kA+iBwReGEcgC+AbmKTioSLEQpxuAOrAwACwAicNsggAPSCGzM0WXH2KlsBuL0wAjAFYQEYWUXlFiMACuHGDAtMgANpgIBhDWEAAUAG7CuGLxyAA+ViKaOvpsAJTpuVp6jrYkyAD01cgAAmDMALQmVJ5grVBQmFB2yFAQYIFQIMgpIgB05NS09GBMrOxINXUAot29ZCOD4BEAnsjacFTtLMjhOsCWEaAo7NjI18jMgVSDzMwQ2P2knJHRWLxZKpCDTSg0OiMFhsDhgoQiQq-ZC8CY2WrIPLaMjHEAAcwgABojJsoC9tMAYE1kGBMDSKTc7nIgA)

**Comment by gabritto** [comment]
@typescript-bot test this

**Comment by gabritto** [comment]
@typescript-bot user test this

**Comment by gabritto** [comment]
@typescript-bot test it

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -45578,6 +45637,297 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            const exprType = getTypeFromFlowType(flowType);
+            // Don't narrow the return type if narrowing didn't produce a narrower type for the expression.
+            if (isTypeAny(exprType) || isErrorType(exprType) || exprType === typeParam || exprType === mapType(typeParam, getBaseConstraintOrType)) {
+                return undefined;
+            }
+            const narrowedType = getSubstitutionType(typeParam, exprType, /*isNarrowed*/ true);
+            return [typeParam, narrowedType];
+        });
+
+        const narrowMapper = createTypeMapper(narrowed.map(([tp, _]) => tp), narrowed.map(([_, t]) => t));
```
Comment (sandersn) [inline src/compiler/checker.ts:45741]: I would either write unzip2 to do this, or turn narrowed+mapDefined into a `for` over narrowableTypeParameters that pushes into two arrays: typeParams and narrowedTypes. Then you can use them directly here.

**Review by sandersn — CHANGES_REQUESTED** [review]
I reviewed this for match to the description and for low-level code style and structure. It's been long enough since I worked with the checker that I don't have useful comments on how well it uses the existing checker code. It feels like it might be able to use some existing utilities and checks, so @weswigham should review this too (or somebody else who's recently spent a lot of time in the checker).

I still need to read the tests too.

File: tests/cases/compiler/dependentReturnType7.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+// @filename: file.js
+
+/** @type {Map<string, string>} */
+const sources = new Map();
+/**
+
+ * @param {string=} type the type of source that should be generated
+ * @returns {String}
+ */
+function source(type = "javascript") {
```
Comment (sandersn) [inline tests/cases/compiler/dependentReturnType7.ts:14]: what is this testing?

File: tests/cases/compiler/unusedLocalsInRecursiveReturn.ts [hunk 3]
```diff
@@ -0,0 +1,8 @@
+// @strict: true
+// @noEmit: true
+// @noUnusedLocals: true
+
+function recursive(arg: string, other: string) {
```
Comment (sandersn) [inline tests/cases/compiler/unusedLocalsInRecursiveReturn.ts:5]: this looks like it's testing something else

Comment (gabritto) [reply tests/cases/compiler/unusedLocalsInRecursiveReturn.ts:5]: In an earlier version, I was not unconditionally checking the return expression in `checkReturnStatement`. However, the expression should be checked even if we don't need to know its type, because it may contain errors and because we need to compute information for whether variables are used or not. The test shows the latter, and it's adapted from a break in the extended tests.

File: tests/cases/compiler/dependentReturnType7.ts (hunk 2 above)
Comment (gabritto) [reply tests/cases/compiler/dependentReturnType7.ts:14]: This is also from an earlier version of the code that had a bug that only showed in extended tests. The bug was looking inside a conditional return expression that has a JSDoc type cast, which we shouldn't do. But I should move this to a different test and add comments.

File: tests/baselines/reference/dependentReturnType1.errors.txt [hunk 4]
```diff
@@ -0,0 +1,645 @@
...
+            ~~~~~~
+!!! error TS2322: Type 'true' is not assignable to type 'T extends 1 | 2 ? T extends 1 ? string : T extends 2 ? boolean : never : T extends 3 ? number : never'.
+        }
+        return 3;
+        ~~~~~~
+!!! error TS2322: Type '3' is not assignable to type 'T extends 1 | 2 ? T extends 1 ? string : T extends 2 ? boolean : never : T extends 3 ? number : never'.
+    }
+    
+    
+    // Unsafe: check types overlap
```
Comment (sandersn) [inline tests/baselines/reference/dependentReturnType1.errors.txt:341]: why is this unsafe? Is it because objects of type T could have additional properties that aren't represented in the type?

Comment (sandersn) [reply tests/baselines/reference/dependentReturnType1.errors.txt:341]: oh, I didn't read all the way. Yes, that is it.

File: tests/baselines/reference/dependentReturnType2.errors.txt [hunk 5]
```diff
@@ -0,0 +1,314 @@
...
+                    return; // Ok
+                }
+    
+                return; // Ok, needed for exhaustiveness check
+            }
+    
+            if (!Meteor.settings) {
+                return undefined; // Error
+                ~~~~~~
+!!! error TS2322: Type 'undefined' is not assignable to type 'HelperCond<I, string, T | undefined, RegExp, SettingComposedValue<T>[]>'.
```
Comment (sandersn) [inline tests/baselines/reference/dependentReturnType2.errors.txt:163]: It's too bad we don't give any elaboration here.

Comment (gabritto) [reply tests/baselines/reference/dependentReturnType2.errors.txt:163]: Yes, I don't really know how we could provide more feedback when we can't narrow a return type. It's already not 100% clear whether the user is trying to narrow the return type or not, and even when we think they are, I can't think of a good mechanism to explain why we didn't narrow.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -45578,6 +45637,297 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        expr: ConditionalExpression,
+    ): void {
+        checkReturnExpression(container, returnType, node, expr.whenTrue, checkExpression(expr.whenTrue), /*inConditionalExpression*/ true);
+        checkReturnExpression(container, returnType, node, expr.whenFalse, checkExpression(expr.whenFalse), /*inConditionalExpression*/ true);
+    }
+
+    // Narrowable type parameters are type parameters that:
+    // (1) have a union type constraint;
+    // (2) are used as the type of a single parameter in the function, and nothing else
+    function getNarrowableTypeParameters(candidates: TypeParameter[]): [TypeParameter, Symbol, Identifier][] {
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/checker.ts:45779]: ESLint doesn't allow it, unfortunately.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -45578,6 +45637,297 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        const narrowableParams: [TypeParameter, Symbol, Identifier][] = [];
+        for (const typeParam of candidates) {
+            const constraint = getConstraintOfTypeParameter(typeParam);
+            if (!constraint || !(constraint.flags & TypeFlags.Union)) continue;
+            if (typeParam.symbol && typeParam.symbol.declarations && typeParam.symbol.declarations.length === 1) {
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/checker.ts:45784]: It can be > 1. If you have multiple declarations of an interface, e.g. `Array<T>` in the lib files, then a type parameter can have multiple declarations. Not sure if there are other ways, but there's at least that one.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -45578,6 +45637,297 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+                        ) {
+                            if (reference) {
+                                hasInvalidReference = true;
+                                break;
+                            }
+                            reference = candidateReference;
+                            continue;
+                        }
+                        hasInvalidReference = true;
+                        break;
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/checker.ts:45808]: I refactored this a bit but kept the `break`s. They are an optimization more than anything, because as soon as we know the type parameter has an invalid reference, we can stop looking through the parameters. But I could get rid of that optimization if the code is still too confusing.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -45578,6 +45637,297 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        const isValidTrueType = isConditionalType(trueType)
+            ? isNarrowableConditionalType(trueType)
+            : true;
+        const isValidFalseType = isConditionalType(falseType)
+            ? isNarrowableConditionalType(falseType)
+            : falseType === neverType;
+        return isValidTrueType && isValidFalseType;
+    }
+
+    function isConditionalType(type: Type): type is ConditionalType {
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/checker.ts:45927]: We usually just check `type.flags` and use type assertions, but I think the narrowing we get with the function is nice.

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -45578,6 +45637,297 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+    function isNarrowableReturnType(returnType: IndexedAccessType | ConditionalType): boolean {
+        return isConditionalType(returnType)
+            ? isNarrowableConditionalType(returnType)
+            : !!(returnType.indexType.flags & TypeFlags.TypeParameter);
+    }
+
+    function isNarrowableConditionalType(type: ConditionalType, mapper?: TypeMapper): boolean {
+        const typeArguments = mapper && map(type.root.outerTypeParameters, t => {
+            const mapped = getMappedType(t, mapper);
+            if (isNarrowingSubstitutionType(mapped)) {
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/checker.ts:45857]: I think it would be a bit weird to have this behavior built into the mapper instead. Here, we only care about the "original" (i.e. pre-narrowing) form of the conditional type because that's what matters for verifying if the conditional type is narrowable. So we discard the narrowed type/`.constraint` from the narrowing substitution type.
Elsewhere, e.g. in `getConditionalTypeInstantiation`, we will also use the narrowing substitution type's constraint.

Also, the behavior of the mapper/instantiation depends on where the type parameter being mapped occurs in a type: if we're mapping a `T` in `T extends A ? ...`, then we want a special behavior for narrowing substitution types. Otherwise, if the `T` is in `A extends B ? T : ...`, there's nothing special we need to do.

File: src/compiler/types.ts [hunk 11]
```diff
@@ -6501,6 +6506,8 @@ export const enum ObjectFlags {
     IsGenericIndexType = 1 << 23, // Union or intersection contains generic index type
     /** @internal */
     IsGenericType = IsGenericObjectType | IsGenericIndexType,
+    /** @internal */
+    IsNarrowedType = 1 << 24, // Substitution type that comes from type narrowing
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/types.ts:6510]: A `SubstitutionType` always has `ObjectFlags`. But the `constraint` of a substitution type can be anything, I think the name being `ObjectFlags` is just a historical artifact.

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -27789,7 +27844,12 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 }
             }
         }
-        return changed ? mappedTypes && getUnionType(mappedTypes, noReductions ? UnionReduction.None : UnionReduction.Literal) : type;
+        return changed
+            ? mappedTypes &&
+                (toIntersection
```
[the remark this answers is not in the document]
Comment (gabritto) [reply src/compiler/checker.ts:27849]: I don't like the inlining idea very much, I think it makes it less clear what's going on in `getConditionalTypeInstantiation`. Also, `mapType` is recursive. 

`mapTypeIntersection` would essentially be a copy of 90% of `mapType`, except for the `changed` variable and parameter `noReductions`, which wouldn't be needed. I am not opposed to this, because I think it is unlikely that we change the core logic of mapping over a type.

Refactoring the shared code into `mapTypeWorker` is kinda weird because of the special case for `changed`: in addition to returning `Type | Type[] | undefined`, `mapTypeWorker` would have to also return this `changed` flag so that the regular `mapType` can make an optimization. This actually made me realize there was a latent bug in my update: even if no type in the union type has changed after mapping, if `toIntersection` is true, we can't simply return the union type, but we have to convert it to an intersection. This doesn't matter for the single use of the function, because the types are guaranteed to change.

Let me know if I should keep the extra parameter to `mapType` or make a new `mapTypeToIntersection`, I don't have strong feelings either way.

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -19081,14 +19098,17 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
             if (checkType === wildcardType || extendsType === wildcardType) {
                 return wildcardType;
             }
+            const effectiveCheckType = forNarrowing && isNarrowingSubstitutionType(checkType)
```
Comment (andrewbranch) [inline src/compiler/checker.ts:19101]: Why do you need both `forNarrowing` and to check the flags of the check type?

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -20284,13 +20304,40 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
-                    mapTypeWithAlias(distributionType, t => getConditionalType(root, prependTypeMapping(checkType, t, newMapper), forConstraint), aliasSymbol, aliasTypeArguments) :
-                    getConditionalType(root, newMapper, forConstraint, aliasSymbol, aliasTypeArguments);
+                if (distributionType && checkType !== distributionType && distributionType.flags & (TypeFlags.Union | TypeFlags.Never)) {
+                    if (narrowingBaseType) {
+                        result = mapType(
+                            distributionType,
+                            (t: Type) =>
+                                getConditionalType(
+                                    root,
+                                    prependTypeMapping(checkType, getSubstitutionType(narrowingBaseType, t, /*isNarrowed*/ true), newMapper),
```
Comment (andrewbranch) [inline src/compiler/checker.ts:20324]: I think the changes here aren't mentioned in your implementation notes. Why do we need custom logic for distribution when we're narrowing?

**Review by andrewbranch — COMMENTED** [review]
Excellent write-up. I have a couple questions.

File: src/compiler/checker.ts (hunk 14 above)
Comment (gabritto) [reply src/compiler/checker.ts:20324]: Good question.

We are using substitution types (which can be thought of as `T & A`, where `T` is the base type and `A` the constraint) to convey a type parameter's narrowing. When instantiating a distributive conditional type in `getConditionalTypeInstantiation`, if the conditional's check type is a substitution type like `T & (A | B)`, the old logic would not distribute over this type, because it's a substitution type and not a union type. So, for distribution to happen, we have to take apart the `T & (A | B)` into `(T & A) | (T & B)`, and distribute over that.

The other special thing that we have to do is to take the intersection of the distribution result, as opposed to the union. This is because, if we narrow a type parameter `T` to `A | B`, and we have a conditional return type `T extends A ? R1 : T extends B ? R2 : T extends C ? R3 : never`, then we don't know which branch of the conditional return to pick, if branch `T extends A ? R1`, or branch `T extends B ? R2`, so we have to check whether the return expression's type is assignable to both, i.e. assignable to `R1 & R2`.

A semi-related note is that validating whether the conditional type has the right shape to be narrowed happens on-demand (and also at first as an optimization in `checkReturnExpression` when we're deciding whether to narrow the return type). This is because, as we instantiate a type, we may produce new conditional types that we need to then decide are safe to narrow or not (see [nested types case in `dependentReturnType6.ts` test](https://github.com/microsoft/TypeScript/pull/56941/files#diff-f40212beae0a9723380268c8a63a1560e91b9431a1fda539b2092cd4778e5fcfR28-R51)).

There's a bunch of details I haven't included in the implementation notes because I don't have a full list of them 😅. I'll add those.

File: src/compiler/checker.ts (hunk 13 above)
Comment (gabritto) [reply src/compiler/checker.ts:19101]: `forNarrowing = true` is passed by `getConditionalTypeInstantiation` when we validate the conditional type is safe to narrow. It could be that the check type is a narrowing substitution type, but we don't want to narrow the conditional type because it has an invalid shape.

File: src/compiler/checker.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/checker.ts:27849]: I guess I slightly prefer `mapTypeToIntersection`, although it's too bad that the return type `Type | IntersectionType` is nonsensical. But it does capture the difference between `mapType` returning `Type | UnionType` (also nonsensical).

File: src/compiler/checker.ts (hunk 14 above)
Comment (andrewbranch) [reply src/compiler/checker.ts:20324]: Would it make sense to always normalize union-containing substitution types into unions of substitution types before distributing?

File: src/compiler/checker.ts [hunk 15]
```diff
@@ -45578,6 +45639,305 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            result = isConditionalType(instantiatedType) && isNarrowableConditionalTypeWorker(instantiatedType);
+            narrowableReturnTypeCache.set(id, result);
+        }
+        return result;
+    }
+
+    // A narrowable conditional type is one that has the following shape:
+    // `T extends A ? TrueBranch<T> : FalseBranch<T>`, in other words:
+    // (0) The conditional type is distributive;
+    // (1) The conditional type has no `infer` type parameters;
```
Comment (weswigham) [inline src/compiler/checker.ts:45888]: Why's that? Is something like
```ts
function f<T extends [number, string] | [string, number]>(arg: T): T extends [number, infer U] ? U : never {
  if (typeof arg[0] === "number") {
    return arg[1];
  }
  throw new Error("Got non numeric tuple");
}
```
for some reason not feasible to check? Is it just because we'd have to do inference between the `true` branch type and the candidate return type to fill in the `infer` type variable, and that's not implemented yet? Because I could equivalently write
```ts
function f<T extends [number, U] | [string, number], U extends string>(arg: T): T extends [number, U] ? U : never {
  if (typeof arg[0] === "number") {
    return arg[1];
  }
  throw new Error("Got non numeric tuple");
}
```
which afaik is valid under these rules. I think all `infer` type parameters in types satisfying the rest of these rules can be rewritten like this pretty easily, which seems to imply the `infer` itself aughta work, but I could be wrong.

**Review by sandersn — APPROVED** [review]

File: src/compiler/checker.ts [hunk 16]
```diff
@@ -45578,6 +45639,305 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        // (4)
+        const trueType = getTrueTypeFromConditionalType(type);
+        const falseType = getFalseTypeFromConditionalType(type);
+        const isValidTrueType = isConditionalType(trueType)
+            ? isNarrowableConditionalType(trueType)
+            : true;
+        const isValidFalseType = isConditionalType(falseType)
+            ? isNarrowableConditionalType(falseType)
+            : falseType === neverType;
+        return isValidTrueType && isValidFalseType;
```
Comment (weswigham) [inline src/compiler/checker.ts:45934]: This is easier to read, but shouldn't this be two returns, to allow short-circuiting the logic?

```suggestion
        // (4)
        const trueType = getTrueTypeFromConditionalType(type);
        const isValidTrueType = isConditionalType(trueType)
            ? isNarrowableConditionalType(trueType)
            : true;
        if (!isValidTrueType) return false;
        const falseType = getFalseTypeFromConditionalType(type);
        const isValidFalseType = isConditionalType(falseType)
            ? isNarrowableConditionalType(falseType)
            : falseType === neverType;
        return isValidFalseType;
```

**Review by weswigham — COMMENTED** [review]
Just one question and one small suggestion - this looks good~

File: src/compiler/checker.ts (hunk 14 above)
Comment (gabritto) [reply src/compiler/checker.ts:20324]: I haven't thought about it, but I assume it would break something somewhere in weird ways.

Comment (Andarist) [reply src/compiler/checker.ts:20324]: it could help with some `NoInfer` problems: https://github.com/microsoft/TypeScript/pull/60271#discussion_r1806069774 :p

Comment (andrewbranch) [reply src/compiler/checker.ts:20324]: I have this vague sense that it would be nice if the conditional-narrowing-specific logic didn’t affect the implementation of `getConditionalTypeInstantiation`, but even if it always normalized substitution types, I don’t have a suggestion for how to extract `mapTypeToIntersection`, so I guess it’s moot.

File: src/compiler/checker.ts (hunk 15 above)
Comment (gabritto) [reply src/compiler/checker.ts:45888]: Basically I don't know how inference would work safely between the substitution type I'm using to represent a narrowed type parameter and the infer type parameters, given how inference works today.

In `T extends [number, infer U] ? U : never`, if we instantiate `T` with substitution type `T & [number, string]`, we would infer from `T & [number, string]` to `[number, infer U]`.
Now, we can't simply infer `string` for `U`, because it would not be sound to narrow the return type to `string`:
 the caller can specify that `T` is `[number, "foo"]` and then `U` is inferred to be `"foo"`, not `string`.
 We'd have to infer something like `T[1] & string` or simply `T[1]` for `U` for this to be safe, and I think we don't have the ability to do that.

**Review by andrewbranch — APPROVED** [review]

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by whalderman** [comment]
I've been waiting for this glorious feature, thank you @gabritto !

**Comment by dgreensp** [comment]
Pardon my ignorance but, this PR is merged, but the behavior doesn't seem to be there in the playground in 5.8.1-rc or Nightly, e.g.  using this example from above:

```ts
function getObject<T extends string | undefined>(group: T):
    T extends string ? string[] : T extends undefined ? Record<string, string[]> : never {
    if (group === undefined) {
        return {}; // error
    }
    return []; // error
}
```

What release is this feature coming in?  Thanks.

**Comment by gabritto** [comment]
The feature got pulled from 5.8 because we needed to fix some aspects of its design. See https://github.com/microsoft/TypeScript/pull/61136. The current plan is to implement the necessary fix and re-add this feature on 5.9.

**Review by king0920king0306 — COMMENTED** [review]
Ok

**Review by girlyagentwithnuts — COMMENTED** [review]
src/compiler/binder.ts bend me over and streach ur drive shaft in bothends

**Comment by mokhtarmoyy** [comment]
declare const record: Record<string, string>;
declare const array: string[];

function getObject(group) {
    if (group === undefined) {
        return record;
    }
    return array;
}

const arrayResult = getObject("group");
const recordResult = getObject(undefined);

**Comment by Rezazare113** [comment]
Blockchain bnb
