### PR TITLE
Fix completion lists for 'readonly' and 'const' keywords

### LINKED ISSUE #29658: completion list doesn't suggest 'const' in type assertion
**TypeScript Version:**  3.4.0-dev.20190131

**Search Terms:**

**Code**

```ts
1 as con/**/
```

**Expected behavior:**

Completion list should contain `const`

**Actual behavior:**

Completion list doesn't contain `const`.

In VSCode if the completion list is open, it automatically uses the first entry when typing certain characters like comma or semicolon. That's annoying as it replaces `const` with `ConstantSourceNode` or something like that.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by minajevs**
Fixes #29658 and #29666

**#29666:**
Added `readonly` keyword to "Type Keywords" list. It caused one test to fail, which I had to fix. That test was failing because it relied on existing behavior, but was not testing this behavior. 

**#29658:**
Added new `TypeAssertionKeywords` filter to `KeywordCompletionFilters`, which is resolved to type keyword + `const` keyword. `const` keyword is not valid type keyword, so I decided to have it in separate filter, instead of putting it into type keywords. 

**Formatting**
My autoformatter fixed some minor formatting errors. Hope it is OK to keep them in this PR :)

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -1211,6 +1216,10 @@ namespace ts.Completions {
             });
         }
 
+        function isInsideTypeAssertion(): boolean {
+            return isAsExpression(contextToken.parent);
```
Comment (sheetalkamat) [inline src/services/completions.ts]: Need to check `isAssertionExpression` instead.

File: tests/cases/fourslash/completionListAsConst.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+////const a = {
+////  b: 42 as con/*0*/
+////};
+////
+////1 as con/*1*/
+////
+////const b = 42 as /*2*/
+
+verify.completions({ marker: test.markers(), includes: [{ name: "const", sortText: completion.SortText.GlobalsOrKeywords }] });
```
Comment (sheetalkamat) [inline tests/cases/fourslash/completionListAsConst.ts]: Instead of this use `globalTypesPlus` or `add typeAssertionKeywords` to verify all the entries are exclusively assertion.

File: tests/cases/fourslash/completionListAsConst.ts [hunk 3]
```diff
@@ -0,0 +1,11 @@
+/// <reference path='fourslash.ts'/>
+
+////const a = {
+////  b: 42 as con/*0*/
```
Comment (sheetalkamat) [inline tests/cases/fourslash/completionListAsConst.ts]: Add tests for type assertion as well.

**Comment by minajevs** [comment]
@sheetalkamat Thanks! Improved `isTypeAssertion` check and widened tests.
