### PR TITLE
Fix crash on bad namespace parse

### LINKED ISSUE #35717: [3.7.3] TypeError: Cannot read property 'kind' of undefined
**TypeScript Version:**  3.7.3

**Code**

```ts
export class Foo extends Bar {
  global on
}
```

**Expected behavior:**

TypeScript should give a type or syntax error 

**Actual behavior:**

tsc crashes with the runtime TypeError.

**Playground Link:**

[playground](http://www.typescriptlang.org/play/?ssl=3&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITqGYAOwBNMAhFKOAbwCg44BzJCAIxSTgiLoF8gA)

See the console, and try writing anything after the `global on` to trigger the error.

If you delete the word `on`, then there's no more error.

**Related Issues:**

### PR DESCRIPTION
**Pull request by sandersn**
`global` inside a class body is parsed as a module declaration, and in
the following example has no body:

```ts
class C {
  global x
}
```

`x` is parsed as a separate ExpressionStatement. This caused a crash in
emit because the code didn't expect a module declaration with no body.

Fixes #35717

### CODE REVIEW

File: src/compiler/transformers/ts.ts [hunk 1]
```diff
@@ -2693,27 +2693,29 @@ namespace ts {
             const statements: Statement[] = [];
             startLexicalEnvironment();
 
-            let statementsLocation: TextRange;
+            let statementsLocation: TextRange | undefined;
             let blockLocation: TextRange | undefined;
             const body = node.body!;
```
Comment (sheetalkamat) [inline src/compiler/transformers/ts.ts]: Can we remove non null assertion here given that's what you are fixing.

Comment (sandersn) [reply src/compiler/transformers/ts.ts]: I just inlined the variable.
