### PR TITLE
Remove `undefined` from source type of renaming destructuring assignment with default

### LINKED ISSUE #37693: Destructuring assignment with default does not correctly remove `undefined` from type
**TypeScript Version:**  3.8.3

**Search Terms:** destructuring assignment default undefined

**Code**

```ts
// @strict: true
declare const r: Iterator<number>;
let done: boolean;
let value;
// (1) works
({ done = false, value } = r.next());

// (2) doesn't work
({ done: done = false, value } = r.next());
```

**Expected behavior:**

Assignment (1) should not error.
Assignment (2) should not error.

**Actual behavior:**

Assignment (1) does not error (correct behavior).
Assignment (2) errors:
```
Type 'boolean | undefined' is not assignable to type 'boolean'.
  Type 'undefined' is not assignable to type 'boolean'.(2322)
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=8&pc=44#code/CYUwxgNghgTiAEYD2A7AzgF3jAXPAkhiDFBkjADwoCuAtgEbEB8A3AFAQhbCoh71IknKCnacsANygRqIdgHp58AO7kA1mjYAKAN7weKBAF54AM2loQAGnhSZCAL7wTMAHSGAHhi0BKH+zZFfSQQNBQAcixVGDVtPQM+YMNnMwtrW2lZeCcXdxAvX38gA)

### PR DESCRIPTION
**Pull request by uhyo**
Happy hacktoberfest! 🎃🥳

Fixes #37693.

## Example

**Code**

```ts
const a: { x?: number; y?: number } = { };
let x: number;

({ x = 0 } = a);
({ x: x = 0} = a);
({ y: x = 0} = a);
```

**Current Behavior** (4.1.0-beta)

```
src/37693.ts:6:7 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

6 ({ x: x = 0} = a);
        ~

src/37693.ts:7:7 - error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

7 ({ y: x = 0} = a);
        ~


Found 2 errors.
```

**New Behavior**

(no errors)

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -32569,6 +32569,10 @@ namespace ts {
             if (target.kind === SyntaxKind.BinaryExpression && (target as BinaryExpression).operatorToken.kind === SyntaxKind.EqualsToken) {
                 checkBinaryExpression(target as BinaryExpression, checkMode);
                 target = (target as BinaryExpression).left;
+                // A default value is specified, so remove undefined from the final type.
+                if (strictNullChecks) {
+                    sourceType = getTypeWithFacts(sourceType, TypeFacts.NEUndefined);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:32574]: I think this may be broken if the default value is `undefined`—can you add a test?

**Review by andrewbranch — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 1 above)
Comment (uhyo) [reply src/compiler/checker.ts:32574]: @andrewbranch Thank you for review!
[I added test cases with `undefined` default value](https://github.com/microsoft/TypeScript/pull/41042/files#diff-a73e59ec2a2848f7dc24482ff7f07936d54425791ebd895a1b909b46b8de4c06R18-R30).
Fortunately the current implementation seems OK.

**Review by sandersn — APPROVED** [review]
