### PR TITLE
Fix circular constraint check

### LINKED ISSUE #25740: Compiler stack overflow with circular constraint and conditional type
I triggered this while trying to use the type system to verify that I was interning objects properly.  I can provide the real-world example code if it's of interest.

**TypeScript Version:** master (d9ed917)

**Search Terms:** "Maximum call stack size exceeded" and some of the function names from the stack trace below.

**Code**

```ts
type Foo<T> = [T] extends [number] ? {} : {};
function foo<S extends Foo<S>>() {}
```

**Expected behavior:** No compiler crash.

**Actual behavior:**
```
REDACTED/typescript/built/local/tsc.js:83260
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getSymbol (REDACTED/typescript/built/local/tsc.js:30038:27)
    at resolveNameHelper (REDACTED/typescript/built/local/tsc.js:30201:34)
    at resolveName (REDACTED/typescript/built/local/tsc.js:30187:20)
    at resolveEntityName (REDACTED/typescript/built/local/tsc.js:31026:26)
    at resolveTypeReferenceName (REDACTED/typescript/built/local/tsc.js:36544:20)
    at getTypeFromTypeReference (REDACTED/typescript/built/local/tsc.js:36706:30)
    at getTypeFromTypeNode (REDACTED/typescript/built/local/tsc.js:38062:28)
    at getConstraintFromTypeParameter (REDACTED/typescript/built/local/tsc.js:36389:72)
    at isUnconstrainedTypeParameter (REDACTED/typescript/built/local/tsc.js:40346:63)
    at REDACTED/typescript/built/local/tsc.js:40349:121
    at Object.some (REDACTED/typescript/built/local/tsc.js:626:25)
    at isTypeReferenceWithGenericArguments (REDACTED/typescript/built/local/tsc.js:40349:74)
    at getRelationKey (REDACTED/typescript/built/local/tsc.js:40387:17)
    at recursiveTypeRelatedTo (REDACTED/typescript/built/local/tsc.js:39623:26)
    at isRelatedTo (REDACTED/typescript/built/local/tsc.js:39305:38)
    at checkTypeRelatedTo (REDACTED/typescript/built/local/tsc.js:39096:26)
    at getConditionalType (REDACTED/typescript/built/local/tsc.js:37671:21)
    at instantiateConditionalType (REDACTED/typescript/built/local/tsc.js:38415:20)
    at getConditionalTypeInstantiation (REDACTED/typescript/built/local/tsc.js:38397:30)
    at instantiateType (REDACTED/typescript/built/local/tsc.js:38456:28)
    at getTypeAliasInstantiation (REDACTED/typescript/built/local/tsc.js:36500:62)
    at getTypeFromTypeAliasReference (REDACTED/typescript/built/local/tsc.js:36521:24)
    at getTypeReferenceTypeWorker (REDACTED/typescript/built/local/tsc.js:36598:24)
    at getTypeReferenceType (REDACTED/typescript/built/local/tsc.js:36551:24)
    at getTypeFromTypeReference (REDACTED/typescript/built/local/tsc.js:36707:28)
    at getTypeFromTypeNode (REDACTED/typescript/built/local/tsc.js:38062:28)
    at getConstraintFromTypeParameter (REDACTED/typescript/built/local/tsc.js:36389:72)
    at isUnconstrainedTypeParameter (REDACTED/typescript/built/local/tsc.js:40346:63)
    at REDACTED/typescript/built/local/tsc.js:40349:121
    at Object.some (REDACTED/typescript/built/local/tsc.js:626:25)
...
```

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=type%20Foo%3CT%3E%20%3D%20%5BT%5D%20extends%20%5Bnumber%5D%20%3F%20%7B%7D%20%3A%20%7B%7D%3B%0D%0Afunction%20foo%3CS%20extends%20Foo%3CS%3E%3E()%20%7B%7D)

**Related Issues:** #22950 conceivably but probably not.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR ensures that we consistently call `getConstraintOfTypeParameter` to obtain type parameter constraints. The `getConstraintOfTypeParameter` method protects against circular constraints, unlike the lower level `getConstraintFromTypeParameter` helper function.

Fixes #25740.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4356,28 +4356,22 @@ namespace ts {
...
             }
-            if (propertyName === TypeSystemPropertyName.ResolvedReturnType) {
-                return !!(<Signature>target).resolvedReturnType;
-            }
-            if (propertyName === TypeSystemPropertyName.ImmediateBaseConstraint) {
-                const bc = (<Type>target).immediateBaseConstraint;
-                return !!bc && bc !== circularConstraintType;
-            }
-
             return Debug.fail("Unhandled TypeSystemPropertyName " + propertyName);
```
Comment (weswigham) [inline src/compiler/checker.ts]: While you're here revising this, it might be worth replacing `Debug.fail(` with `Debug.asserNever(propertyName` to guarantee exhaustiveness. Just a nit.
