### PR TITLE
fix(40901): Variable arguments generated from JS although not applicable

### LINKED ISSUE #40901: Variable arguments generated from JS although not applicable
**TypeScript Version:**  4.0.3

**Search Terms:** arguments, var args

**Code**

I'm trying to produce a Typscript Declaration file for my JS project:

src/example.js
```js
class Example {
	/**
	 * Example
	 * 
	 * @param {object} [args={}]
	 */
	constructor(args = {}) {
		/**
		 * @type object
		 */
		this.arguments = args;
	}
}
```

tsconfig.json
```json
{
	"include": ["./src/"],
	"typeAcquisition": {
	  "enable": true
	},
	"compilerOptions": {
		"allowJs": true,
		"declaration": true,
		"emitDeclarationOnly": true,
		"moduleResolution": "node",
		"outFile": "openeo.d.ts",
		"target": "es2017"
	}
}
```

cmd line:
```
npx typescript --project tsconfig.json
```

**Expected behavior:**

```ts
declare module "builder/node" {
    export = Example;
    class Example {
        /**
         * Example
         *
         * @param {object} [args={}]
         */
        constructor(args?: object);
        /**
         * @type {object}
         */
        arguments: object;
    }
}
```

**Actual behavior:**

I get a constructor with two args parameters, which is invalid:
```ts
declare class Example {
    /**
     * Example
     *
     * @param {object} [args={}]
     */
    constructor(args?: object, ...args: any[]);
    /**
     * @type object
     */
    arguments: object;
}
```

Interestingly, if I change `this.arguments` to `this.xyz` in the JS code, it works properly and generates:

```ts
declare class Example {
    /**
     * Example
     *
     * @param {object} [args={}]
     */
    constructor(args?: object);
    /**
     * @type object
     */
    xyz: object;
}
```

It seems it thinks that `this.arguments` is a reference to `arguments`, but it is obviously not.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play?strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&checkJs=false&experimentalDecorators=false&emitDecoratorMetadata=false&jsx=0&module=0&useJavaScript=true#code/MYGwhgzhAECiAeYC2AHEBTaBvAsAKAEgB6AKhPwOhLkVQwqugeoAEUwAnZbAewCMAVumAAXAL7QA2pwDmEALxYxAXWZEKwHgDsIIjgFdRPDgApZMedjEBKbBWJl7jFiICeKTPyGinJdYQIRAAsASwgAOll9JHQtEQtocwBuCjF8MSA)

**Related Issues:** No

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40901

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -11656,7 +11656,7 @@ namespace ts {
                 if (!node) return false;
                 switch (node.kind) {
                     case SyntaxKind.Identifier:
-                        return (<Identifier>node).escapedText === "arguments" && isExpressionNode(node);
+                        return (<Identifier>node).escapedText === argumentsSymbol.escapedName && getResolvedSymbol(<Identifier>node) === argumentsSymbol;
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:11659]: I think it would be simpler to check that the parent node type isn't PropertyAccessExpression / ElementAccessExpression? Does that work?

Comment (a-tarasyuk) [reply src/compiler/checker.ts:11659]: Thanks for the review. Good point. Just to be sure, do we need to add `...args` for the this case: [argumentsReferenceInConstructor7_Js](https://github.com/microsoft/TypeScript/blob/75ed47c259884a48646b3a32139d20679f20c9b0/tests/baselines/reference/argumentsReferenceInConstructor7_Js.js) and omit `...args` for this case [argumentsReferenceInConstructor4_Js](https://github.com/microsoft/TypeScript/blob/75ed47c259884a48646b3a32139d20679f20c9b0/tests/baselines/reference/argumentsReferenceInConstructor4_Js.js)?

**Comment by m-mohr** [comment]
Please also check whether the additional code example in https://github.com/microsoft/TypeScript/issues/40901#issuecomment-703470150 is covered.

**Review by weswigham — APPROVED** [review]
I think the resolved symbol identity check makes sense.

**Comment by a-tarasyuk** [comment]
@weswigham thanks.
