### PR TITLE
Only perform async code fix if it can successfully refactor all parts

### LINKED ISSUE #26375: Async / Await Refactoring - Arguments in promise handlers that are not function type
**Search Terms:**
Async, Await, Refactoring, Code Fix, Expression, Arguments

**Code**

```ts
function f() {
	return Promise.resolve().then(f ? (x => 1) : (y => 2));
}
```

**Expected behavior:**
A refactoring is not offered.

**Actual behavior:**
A refactoring is offered and the following code is generated:
```ts
async function f() {
	await Promise.resolve();
}
```

### PR DESCRIPTION
**Pull request by uniqueiniquity**
Fixes #26375.
Currently, there's a limited set of syntax forms that we are able to refactor for the async code fix (namely, identifiers, arrow functions, and function expressions). If we try to refactor a promise operation (e.g., `.then`), with one of its arguments not in this form, we end up deleting that code.
This PR handles this more gracefully by not returning a code action if not all promise operations could be refactored successfully. Additionally, this PR introduces the ability to test for this situation (i.e., a diagnostic is produced but no action is available). 

Note that in VS, no suggestion diagnostic is shown due to the lack of available codefixes. However, in VS Code, the suggestion diagnostic is shown, but no lightbulb is offered.

### CODE REVIEW

File: src/services/suggestionDiagnostics.ts [hunk 1]
```diff
@@ -170,8 +170,39 @@ namespace ts {
...
+        while (isPromiseHandler(currentNode) || isPropertyAccessExpression(currentNode)) {
+            if (isCallExpression(currentNode) && !currentNode.arguments.every(isFixablePromiseArgument)) {
+                return false;
+            }
+            currentNode = currentNode.expression;
+        }
+        return true;
+    }
+
+    function isPromiseHandler(node: Node): node is CallExpression {
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts]: >node is CallExpression [](start = 43, length = 22)

I remember being told not to do this if it didn't accept all CallExpressions, but I may have misunderstood.

File: src/services/suggestionDiagnostics.ts [hunk 2]
```diff
@@ -170,8 +170,39 @@ namespace ts {
...
+        return isCallExpression(node) && (hasPropertyAccessExpressionWithName(node, "then") || hasPropertyAccessExpressionWithName(node, "catch"));
+    }
+
+    // should be kept up to date with getTransformationBody in convertToAsyncFunction.ts
+    function isFixablePromiseArgument(arg: Expression): boolean {
+        switch (arg.kind) {
+            case SyntaxKind.NullKeyword:
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts]: >NullKeyword [](start = 28, length = 11)

Null but not undefined?

File: src/services/suggestionDiagnostics.ts [hunk 3]
```diff
@@ -170,8 +170,39 @@ namespace ts {
...
+        }
+        return true;
+    }
+
+    function isPromiseHandler(node: Node): node is CallExpression {
+        return isCallExpression(node) && (hasPropertyAccessExpressionWithName(node, "then") || hasPropertyAccessExpressionWithName(node, "catch"));
+    }
+
+    // should be kept up to date with getTransformationBody in convertToAsyncFunction.ts
+    function isFixablePromiseArgument(arg: Expression): boolean {
```
Comment (amcasey) [inline src/services/suggestionDiagnostics.ts]: >isFixablePromiseArgument [](start = 13, length = 24)

I don't feel strongly about it but I thought we had concluded this belonged in the code fix (i.e. we could make suggestions more often than we offered fixes).  Did something change?

File: src/services/codefixes/convertToAsyncFunction.ts [hunk 4]
```diff
@@ -2,11 +2,13 @@
 namespace ts.codefix {
     const fixId = "convertToAsyncFunction";
     const errorCodes = [Diagnostics.This_may_be_converted_to_an_async_function.code];
+    let codeActionSucceeded = true;
```
Comment (amcasey) [inline src/services/codefixes/convertToAsyncFunction.ts]: >codeActionSucceeded [](start = 8, length = 19)

I assume this is the thing you were talking about when you asked about exceptions.  It's not what I would have done, but it sounds like you've already checked the local conventions.  I might change it to `codeActionFailed` though.  As long as we're going down this path, would it make sense to have an error code indicating how it went wrong and then send a telemetry event when we see a failure?

File: src/services/suggestionDiagnostics.ts (hunk 1 above)
Comment (uniqueiniquity) [reply src/services/suggestionDiagnostics.ts]: I'm not sure why that would be true...

File: src/services/suggestionDiagnostics.ts (hunk 2 above)
Comment (uniqueiniquity) [reply src/services/suggestionDiagnostics.ts]: Nope. From what I understand, `SyntaxKind.UndefinedKeyword` refers to only the `undefined` type keyword. `undefined` in the value space is an `Identifier` with the name `undefined`.

File: src/services/suggestionDiagnostics.ts (hunk 3 above)
Comment (uniqueiniquity) [reply src/services/suggestionDiagnostics.ts]: Yeah, I spoke to @RyanCavanaugh who felt strongly that the suggestion diagnostic should be equally conservative as the code fix.

File: src/services/codefixes/convertToAsyncFunction.ts (hunk 4 above)
Comment (uniqueiniquity) [reply src/services/codefixes/convertToAsyncFunction.ts]: I'm not sure this is an appropriate place to bubble up an error code given the change to be more conservative about offering the diagnostic. That is, we won't show the diagnostic if we know the code fix is going to fail.

File: src/services/suggestionDiagnostics.ts (hunk 3 above)
Comment (amcasey) [reply src/services/suggestionDiagnostics.ts]: Suits me.

File: src/services/suggestionDiagnostics.ts (hunk 2 above)
Comment (amcasey) [reply src/services/suggestionDiagnostics.ts]: Weird.
