### PR TITLE
Better error recovery for adjacent JSX elements in expression positions

### LINKED ISSUE #5286: Better error reporting/recovery for adjacent JSX elements
Currently code
```jsx
<p></p>
<p></p>
```
is effectively parsed as if it was a chain of binary operators
```typescript
(<p></p>) < p > </ p >
```

and errors that were reported are not very helpful
```
tt.tsx(2,4): error TS1109: Expression expected.
tt.tsx(2,8): error TS1109: Expression expected.
```

Incorrect AST later breaks other LS features like formatting (#5265).

Error in Babel for the same case is much more useful:
```
Adjacent JSX elements must be wrapped in an enclosing tag
```

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #5286

### CODE REVIEW

File: tests/baselines/reference/jsxEsprimaFbTestSuite.js [hunk 1]
```diff
@@ -72,8 +72,8 @@ baz
 <div>@test content</div>;
 <div><br />7x invalid-js-identifier</div>;
 <LeftRight left={<a />} right={<b>monkeys /> gorillas</b> /  > }/>
-    < a.b > ;
-a.b > ;
+    ,
```
Comment (vladima) [inline tests/baselines/reference/jsxEsprimaFbTestSuite.js]: is this `,` comes from synthesized missing node?

Comment (RyanCavanaugh) [inline tests/baselines/reference/jsxEsprimaFbTestSuite.js]: Correct

Comment (vladima) [inline tests/baselines/reference/jsxEsprimaFbTestSuite.js]: interesting, I didn't realize that we print missing nodes. In this case I'm not sure that user would expect to see it - this is our internal recovery strategy and I don' think it should leak outside. Maybe we should not emit missing nodes (since they are  ...missed in the source code)

Comment (RyanCavanaugh) [inline tests/baselines/reference/jsxEsprimaFbTestSuite.js]: This is consistent with what we've done for a while. For example if you write
```ts
var x = a b;
```
we emit
```ts
var x = a, b;
```

As I've said before, I don't think emitting in the presence of syntax errors is a rational thing to do, but since we're doing it anyway, I think the code we emit should at least be syntactically valid (even if it makes guesses at the intent).

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by vladima** [comment]
:+1:
