### PR TITLE
Fix index fallback of CJS package from ESM-mode import when `main` is present but does not resolve

### LINKED ISSUE #49326: ESM-mode default import does not resolve to old DT packages with no `"types"` field
# Bug Report

Reported in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60592

```ts
// @module: nodenext

// @Filename: /node_modules/@types/dedent/package.json
{ "name": "@types/dedent", "version": "1.0.0", "main": "" }

// @Filename: /node_modules/@types/dedent/index.d.ts
export {};

// @Filename: /index.mts
import dedent from "dedent";
```

Expected: import in index.mts resolves
Actual: `Cannot find module 'dedent' or its corresponding type declarations.`

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #49326

To check that this is consistent with Node’s behavior, I tried these package.json modifications in `@types/dedent` and added an `index.js` of `module.exports = "index.js"` and ran

```
node --input-type=module -e 'import dedent from "@types/dedent"; console.log(dedent)'
node -e 'console.log(require("@types/dedent"))'
```

and ensured both log `index.js`. If they did, I assumed that means we should be able to resolve to `index.d.ts`.

### CODE REVIEW

File: src/compiler/moduleNameResolver.ts [hunk 1]
```diff
@@ -2413,8 +2413,8 @@ namespace ts {
                 );
             if (
                 !pathAndExtension && packageInfo
-                && packageInfo.packageJsonContent.exports === undefined
-                && packageInfo.packageJsonContent.main === undefined
+                // eslint-disable-next-line no-null/no-null
+                && (packageInfo.packageJsonContent.exports === undefined || packageInfo.packageJsonContent.exports === null)
```
Comment (weswigham) [inline src/compiler/moduleNameResolver.ts:2417]: Double checking on https://nodejs.org/api/esm.html#resolution-algorithm, recognizing both null and undefined here for `exports` seems good (only one usage makes that explicit, but it should be fine), however ignoring `main` and looking up an index regardless is not what `PACKAGE_RESOLVE` describes for an `export`less package... it just says `Return the URL resolution of packageSubpath in packageURL.`, which doesn't imply any fallback to `index.js` lookup if the `main` fails. If in practice it is, the algorithm in the `node` docs may be wrong. (Which doesn't surprise me, if I'm honest, I think the people writing the code are more pragmatic than the people reviewing/writing the docs.)

Comment (weswigham) [reply src/compiler/moduleNameResolver.ts:2417]: Indeed, there's a large [legacy main resolution](https://github.com/nodejs/node/blob/d859e9e997a3de9bdd7e116b2878acc2a3cf4bd6/lib/internal/modules/esm/resolve.js#L280) code block which isn't included in the documented algorithm.

**Review by weswigham — APPROVED** [review]

File: src/compiler/moduleNameResolver.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/moduleNameResolver.ts:2417]: I've opened https://github.com/nodejs/node/issues/43269 for the docs issue on node.
