### PR TITLE
Fixed false positive errors in empty optional binding patterns in declaration signatures

### LINKED ISSUE #50791: Empty binding pattern in optional parameter declaration says "Object is possibly 'undefined'", while non-empty does not
# Bug Report

### 🔎 Search Terms

empty optional property binding pattern destructuring element

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQEYAKAbwF8B+ALnlPgA9aBnDGLVAc3nIEpaAbjizAA3PAD0E+CBgwcMALAAoFaEiwEKdNjwEATGUY8adRizYdufQcLGTpAeQDSlFWvDQ4SNJlz5EVABmYgBtAF1TUPN4VnYueHD+eCERcSkZOQV3ZXUvLV9dANQAFjDjSNpopljLBKTbNId4F0ogA)

### 💻 Code

```ts
declare function fn1({}?: { x: string }): void; // error

declare function fn2({ x }?: { x: string }): void; // OK?

declare function fn3([]?: [ x: string ]): void; // error

declare function fn4([ x ]?: [ x: string ]): void; // OK?
```

### 🙁 Actual behavior

An empty binding pattern gets the error `Object is possibly 'undefined'.`, but a non-empty one doesn't.

### 🙂 Expected behavior

Consistently no error; see also the discussion on #50707.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #50791

cc @jakebailey

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -38322,7 +38322,7 @@ namespace ts {
             // For a binding pattern, validate the initializer and exit
             if (isBindingPattern(node.name)) {
                 const needCheckInitializer = hasOnlyExpressionInitializer(node) && node.initializer && node.parent.parent.kind !== SyntaxKind.ForInStatement;
-                const needCheckWidenedType = !some(node.name.elements, not(isOmittedExpression));
+                const needCheckWidenedType = !!node.name.elements.length && !some(node.name.elements, not(isOmittedExpression));
```
Comment (Andarist) [inline src/compiler/checker.ts:38325]: actually - this is not a good fix, i need to check if this is contained in a declaration signature, gonna push out a proper fix some time later

Comment (jakebailey) [reply src/compiler/checker.ts:38325]: Yeah, I think if this is written outside of a declaration, it's always an error, because you can't have `{}?` or `{ x }?` without it crashing; the question token wouldn't be there if there were a default as that'd be `{} = {}` and so on.

Comment (Andarist) [reply src/compiler/checker.ts:38325]: Ye, i’m looking throughout the codebase to see how other places check if a thing is in a type declaration but surprisingly i didnt find many. Im gonna resort to a findAncestor check

Comment (Andarist) [reply src/compiler/checker.ts:38325]: Ok, I think I got it right now

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -38321,6 +38321,9 @@ namespace ts {
             }
             // For a binding pattern, validate the initializer and exit
             if (isBindingPattern(node.name)) {
+                if (findAncestor(node, n => isInterfaceDeclaration(n) || isTypeLiteralNode(n) || isTypeAliasDeclaration(n) || !!(n.flags & NodeFlags.Ambient))) {
```
Comment (Andarist) [inline src/compiler/checker.ts:38324]: The check is loosely~ based on this one [here](https://github.dev/microsoft/TypeScript/blob/a8e13f7340c5229426072d443fa511bba82a0054/src/compiler/checker.ts#L1656-L1658). I think that this other one is incomplete - and I'm also working on fixing it.

Comment (jakebailey) [reply src/compiler/checker.ts:38324]: Yeah, it might be worth pulling out that helper and fixing it.

Comment (Andarist) [reply src/compiler/checker.ts:38324]: Here is the fix: https://github.com/microsoft/TypeScript/pull/50824 . Once one of those PR lands I can rebase the other one to unify this helper

Comment (jakebailey) [reply src/compiler/checker.ts:38324]: Thanks for sending it!

**Comment by jakebailey** [comment]
Sorry, I completely forgot to come back to this one after #50824.

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Review by jakebailey — APPROVED** [review]
Tentatively LGTM
