### PR TITLE
Use correct program when checking for reexports from AutoImportProviderProject

### LINKED ISSUE #40223: TypeScript prefers deep paths for import quick fixes (and auto-imports?)
**TypeScript Version:**  4.0.2

**Search Terms:** Import

According to the [TypeScript 4 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#smarter-auto-imports) auto-imports should be improved, it is the case now imports are getting added automatically but it seems like the paths are not correct - to `/dist/` folder as opposed to what library is exposing.

This won't work in prod-ish environment, Node.js might not be able to resolve such paths. In the example below - paths are pointing at the d.ts files that has not meaning for Node.js

- This is the case for both single-import and "Add all missing imports" options.
- This happens during only the initial import, once the library imported once in a correct way - all dependencies are getting imported with correct paths.

Please see the example and comments:

- [GitHub repo with example](https://github.com/jazzfog/vscode-imports-issue-demo/blob/master/src/App.tsx)

**Code**

Following is a file from an app generated by `create-react-app`, TypeScript was manually updated to `4.0.2`, also added `react-hook-form` dependency.

```ts
import React, { ReactNode } from 'react';

// TypeScript 4 adds incorrect dependencies

// Correct imports, added manually
// ---
// import { useFieldArray, useForm } from "react-hook-form";

// Wrong imports (added by TypeScript 4 and VSCode),
// Node is not able to use these paths since they are pointing at d.ts files.
// ---
// import { useFieldArray } from 'react-hook-form/dist/useFieldArray';
// import { useForm } from 'react-hook-form/dist/useForm';

function App() {

  // Press `Ctrl + .` (Windows) or `Cmd + .` (macOS)
  // 
  // console.log(useForm, useFieldArray);

  return <>...</>;
}

export default App;
```

**Expected behavior:** Imports should point at the compiled code

**Actual behavior:** Imports point at the original TS code that node won't be able to execute once the project is compiled.

**Playground Link:** [GitHub repo with example](https://github.com/jazzfog/vscode-imports-issue-demo/blob/master/src/App.tsx)

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40223

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -521,29 +521,29 @@ namespace ts.codefix {
...
         // For each original symbol, keep all re-exports of that symbol together so we can call `getCodeActionsForImport` on the whole group at once.
         // Maps symbol id to info for modules providing that symbol (original export + re-exports).
         const originalSymbolToExportInfos = createMultiMap<SymbolExportInfo>();
-        function addSymbol(moduleSymbol: Symbol, exportedSymbol: Symbol, importKind: ImportKind): void {
+        function addSymbol(moduleSymbol: Symbol, exportedSymbol: Symbol, importKind: ImportKind, checker: TypeChecker): void {
             originalSymbolToExportInfos.add(getUniqueSymbolId(exportedSymbol, checker).toString(), { moduleSymbol, importKind, exportedSymbolIsTypeOnly: isTypeOnlySymbol(exportedSymbol, checker) });
         }
-        forEachExternalModuleToImportFrom(program, host, sourceFile, /*filterByPackageJson*/ true, useAutoImportProvider, moduleSymbol => {
+        forEachExternalModuleToImportFrom(program, host, sourceFile, /*filterByPackageJson*/ true, useAutoImportProvider, (moduleSymbol, _, program) => {
+            const checker = program.getTypeChecker();
```
Comment (andrewbranch) [inline src/services/codefixes/importFixes.ts:535]: When there’s an AutoImportProviderProject, these modules can come from different programs, but this was always asking for exports of module symbols with the same checker instance, which would be missing resolved exports cached on symbol links if the module was checked by a different checker. That’s why a `program` is passed to this callback, but I missed this usage of it in the original refactor.

**Review by sheetalkamat — APPROVED** [review]
