### PR TITLE
fix(37940): 'Move to new file' refactoring removes spaces between decorator and property modifiers

### LINKED ISSUE #37940: 'Move to new file' refactoring removes spaces between decorator and property modifiers
**TypeScript Version:**  3.9.0-dev.20200413

**Search Terms:**
- move to new file
- refactor / refactoring

**Code**
For the TS:
```ts
const dec: any = () => { };

class Foo {
    constructor(
        @dec private readonly bar: number
    ) { }
}
```

1. Run `move to new file` on `Foo`

**Bug:**

The space between `@dec` and `private` is removed

```ts
class Foo {
    constructor(
        @decprivate readonly bar: number
    ) { }
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37940

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
cc @andrewbranch

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -3902,6 +3902,9 @@ namespace ts {
 
         function emitDecorators(parentNode: Node, decorators: NodeArray<Decorator> | undefined) {
             emitList(parentNode, decorators, ListFormat.Decorators);
+            if (decorators && isParameter(parentNode)) {
```
Comment (andrewbranch) [inline src/compiler/emitter.ts:3905]: When the parent is not a parameter, where does the space come from?

Comment (andrewbranch) [reply src/compiler/emitter.ts:3905]: It’s notable that this is the _only_ reference to `ListFormat.Decorators` 🤔

Comment (a-tarasyuk) [reply src/compiler/emitter.ts:3905]: @andrewbranch I think there is no need to add space for cases like so

```ts
@decorator
class Foo {}
```

```ts
class Foo {
  @decorator
  fn() {}
}
```

Or am I wrong?
Do I need to add logic to writing space for decorators in `emitNodeList`?

Comment (andrewbranch) [reply src/compiler/emitter.ts:3905]: I’m unsure of the current behavior, but you could easily have

```ts
class Foo {
  @decorator fn() {}
}
```

as an input, and I’m curious what happens with that—something has to write either a newline or a space, and I was wondering if it would make sense to cover the parameter decorator in the same code path. But I’m genuinely unsure where that happens at the moment.

Comment (a-tarasyuk) [reply src/compiler/emitter.ts]: The following example has the same error as parameter decorator :(

Before
```ts
class Foo {
  @decorator fn() {}
}
```

After
```ts
class Foo {
  @decoratorfn() {}
}
```

Decorators processed as lists, however, if decorators are located on the same line, there is no option to add space after the last element

https://github.com/microsoft/TypeScript/blob/15c3e99cbd315629e8c2c1444ea879a75aa22d8a/src/compiler/emitter.ts#L4132

only if `format` has `ListFormat.SpaceBetweenBraces` option,
https://github.com/microsoft/TypeScript/blob/15c3e99cbd315629e8c2c1444ea879a75aa22d8a/src/compiler/emitter.ts#L4136
 however, `Decoratos` use only `MultiLine`, `Optional` options. 

What do you think about adding a new option for `Decorators` which will add space after a list?

**Comment by andrewbranch** [comment]
With your latest change, what happens to decorators on their own line?

```ts
@decorator // <-- is there a space here after a refactor?
class Foo {}
```

**Comment by a-tarasyuk** [comment]
This change related only for the case when decorators are allocated on the single line
```ts
@decorator class Foo {}
```

The following case handled by 
```ts
@decorator
class Foo {}
```
https://github.com/microsoft/TypeScript/blob/15c3e99cbd315629e8c2c1444ea879a75aa22d8a/src/compiler/emitter.ts#L4134

**Comment by andrewbranch** [comment]
Thanks @a-tarasyuk! 🌟
