### PR TITLE
Introduce ES2024 target and fix some types

### LINKED ISSUE #54636: fix(dts): Update type of `ArrayBuffer`
# lib Update Request

The problem is that proper types are not available when `Resizable ArrayBuffer` need to be created by passing `options` in the constructor.

## Configuration Check

My compilation *target* is `ESnext` and my *lib* is `the default`.

## Missing / Incorrect Definition

**`ArrayBuffer`** Constructor signature.

## Sample Code

```TypeScript
const buff = new ArrayBuffer(10, {
  maxByteLength: 100,
});

console.debug(buff.resizable);
console.debug(buff.byteLength);

buff.resize(100);
console.debug(buff.byteLength);
```

## Documentation Link

You can check the signature over here.

[ArrayBuffer() constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer)

### PR DESCRIPTION
**Pull request by petamoriken**
Fixes #54636
Past PRs #54637, #57858
Refs https://github.com/denoland/deno/issues/19191, https://github.com/denoland/deno/issues/24238

This PR includes the following changes:

## Introduce ES2024 target

* Introduce ES2024 target
* Move some ESNext types to ES2024
* **BREAKING**: Move `Atomics.waitAsync` types from ES2022 to ES2024
* Add Resizable/Transfer ArrayBuffer types to ES2024

## Fix some types

* Fix `ArrayBuffer.prototype.slice` types in ES5
* Fix `SharedArrayBuffer.prototype.slice` types in ES2017
* Add empty arguments of  `ArrayBuffer`/`SharedArrayBuffer` constructor types to ES2017

### CODE REVIEW

**Comment by petamoriken** [comment]
It is strange that ES2024 `Atomics.waitAsync` is defined in `es2022.sharedmemory.d.ts`, but probably cannot be fixed.

**Comment by jakebailey** [comment]
If it was a mistake, I don't think we'd be against fixing it. If you make that change, we can run the extended tests and see how bad it would be.

**Comment by petamoriken** [comment]
@sandersn Would you review this PR?

**Comment by petamoriken** [comment]
ES2024 released 
https://2ality.com/2024/06/ecmascript-2024.html

**Comment by petamoriken** [comment]
@DanielRosenwasser @RyanCavanaugh Would you review this PR?

File: src/lib/es2024.collection.d.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+interface MapConstructor {
+    /**
+     * Groups members of an iterable according to the return value of the passed callback.
+     * @param items An iterable.
+     * @param keySelector A callback which will be invoked for each item in items.
+     */
+    groupBy<K, T>(
+        items: Iterable<T>,
```
Comment (rbuckton) [inline src/lib/es2024.collection.d.ts:8]: Given #58243 has merged, this should probably be `Iterable<T, unknown, undefined>`.

```suggestion
        items: Iterable<T, unknown, undefined>,
```

File: src/lib/es2024.collection.d.ts
Comment (rbuckton) [inline src/lib/es2024.collection.d.ts:1]: Should we not also include [`Object.groupBy`](https://tc39.es/ecma262/#sec-object.groupby)?

File: src/compiler/commandLineParser.ts [hunk 2]
```diff
@@ -215,12 +218,18 @@ const libEntries: [string, string][] = [
     ["es2022.error", "lib.es2022.error.d.ts"],
     ["es2022.intl", "lib.es2022.intl.d.ts"],
     ["es2022.object", "lib.es2022.object.d.ts"],
-    ["es2022.sharedmemory", "lib.es2022.sharedmemory.d.ts"],
```
Comment (rbuckton) [inline src/compiler/commandLineParser.ts:218]: Do we have any tests showing what happens if you were using `"target": "es2022"` or `"lib": ["es2022"]` and `Atomics.waitAsync`?

File: src/lib/esnext.collection.d.ts [hunk 3]
```diff
@@ -1,15 +1,3 @@
-interface MapConstructor {
```
Comment (rbuckton) [inline src/lib/esnext.collection.d.ts:1]: We should probably include a lib reference to es2024.collection.d.ts so as to not break anyone currently using `"lib": [..., "esnext.collection.d.ts"]` for this.

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: src/lib/es2024.collection.d.ts
Comment (petamoriken) [reply src/lib/es2024.collection.d.ts:1]: It included by `es2024.object`.

File: src/compiler/commandLineParser.ts (hunk 2 above)
Comment (petamoriken) [reply src/compiler/commandLineParser.ts:218]: I will add it, as it is not there yet.

File: src/lib/es2024.collection.d.ts
Comment (rbuckton) [reply src/lib/es2024.collection.d.ts:1]: Ah, thanks. I'd missed that

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test top400
@typescript-bot test tsserver top100
@typescript-bot user test this
@typescript-bot user test tsserver

**Comment by rbuckton** [comment]
@typescript-bot: pack this

**Comment by rbuckton** [comment]
For the failing tests in top 400:

- `majodev/google-webfonts-helper` - In `jszip`, the `InputFileFormat` type only includes `ArrayBuffer` and not `SharedArrayBuffer` (or `ArrayBufferLike`), so either `majodev/google-webfonts-helper` needs to assert the buffer is an `ArrayBuffer` or `jszip` needs to be updated to allow `SharedArrayBuffer`. This error seems correct as we can only assume `jszip` did not expect `SharedArrayBuffer` inputs.

- `mapbox/mapbox-gl-js`, `pixijs` - It looks like the errors are expected as `ArrayBuffer` and `SharedArrayBuffer` now actually have divergent interfaces due to resizable/growable array buffers.

- `spacedriveapp/spacedrive` - The error comes from `ArrayBuffer` now differing sufficiently from `Buffer`. It looks like `archive-wasm` indicates that `extractTo` only accepts `ArrayBufferLike`, though if you follow the argument through it should probably also accept `Uint8Array`.

- `wandb/openui`
  - The first error is also probably correct given that `ArrayBuffer` now differs sufficiently from `Uint8Array`. 
  - The second error indicates a typo in the DOM types for `crypto.subtle.verify` in that `BufferSource` should also include `SharedArrayBuffer`, per:
    - https://w3c.github.io/webcrypto/#SubtleCrypto-method-verify
    - https://webidl.spec.whatwg.org/#dfn-get-buffer-source-copy
    - https://webidl.spec.whatwg.org/#dfn-buffer-source-type
    - https://webidl.spec.whatwg.org/#buffer-types

File: tests/cases/conformance/es2022/es2024SharedMemory.ts [hunk 4]
```diff
@@ -0,0 +1,26 @@
+// @target: esnext
+// @lib: es2022
+// @noemit: true
+// @strict: true
+
+// ES2024 Atomics.wait was included in the ES2022 type file due to a mistake.
```
Comment (rbuckton) [inline tests/cases/conformance/es2022/es2024SharedMemory.ts:6]:
```suggestion
// ES2024 Atomics.waitAsync was included in the ES2022 type file due to a mistake.
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

**Comment by rbuckton** [comment]
The only other change I see we need to make here is a small nit in the test comment. The fix for `SubtleCrypto` will likely need an update to https://github.com/microsoft/TypeScript-DOM-lib-generator, however.

**Comment by rbuckton** [comment]
> The second error indicates a typo in the DOM types for `crypto.subtle.verify` in that `BufferSource` should also include `SharedArrayBuffer`, per:
> * https://w3c.github.io/webcrypto/#SubtleCrypto-method-verify
> * https://webidl.spec.whatwg.org/#dfn-get-buffer-source-copy
> * https://webidl.spec.whatwg.org/#dfn-buffer-source-type
> * https://webidl.spec.whatwg.org/#buffer-types

Correction, `verify` is correctly typed, but runs afoul of every typed array having a `.buffer` that is potentially a `SharedArrayBuffer`.

File: tests/cases/conformance/es2022/es2024SharedMemory.ts (hunk 4 above)
Comment (rbuckton) [reply tests/cases/conformance/es2022/es2024SharedMemory.ts]: My apologies, this will also require re-running the tests to capture test outputs that include the comment.

**Comment by guest271314** [comment]
@petamoriken If I'm reading this correctly I can use https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/162976/artifacts?artifactName=tgz&fileId=9B134F6B73EF0334DC56B90577381A1DBB6A4FF614ECEFC5830AD3185B92A0C602&fileName=/typescript-5.6.0-insiders.20240723.tgz right now if I'm only concerned about resizable `ArrayBuffer` in TypeScript?

**Comment by petamoriken** [comment]
@guest271314 This PR has not yet been merged so probably is not available yet.

**Comment by rbuckton** [comment]
I'd hoped to get this in before the 5.6 beta cutoff, but it looks like there are some long-term concerns related to `ArrayBufferLike` and typed arrays we may need to address before this can go in.

**Comment by guest271314** [comment]
> This PR has not yet been merged so probably is not available yet.

I should be able to fork your code, build `tsc` and go on about my business, without waiting for an official merge in this repository, correct?

**Comment by DanielRosenwasser** [comment]
Yes, you can just use the following in your `package.json` for a mostly-up-to-date version of the PR.

```json
{
  "devDependencies": {
    "typescript": "npm:@typescript-deploys/pr-build@5.6.0-pr-58573-19"
  }
}
```

**Comment by guest271314** [comment]
@DanielRosenwasser 

```
bun install npm:@typescript-deploys/pr-build@5.6.0-pr-58573-19
```
without a `package.json` works, too.

Is there a "latest" or "nightly" URL?

**Comment by guest271314** [comment]
@DanielRosenwasser Got this working in Deno reading this https://docs.deno.com/runtime/manual/advanced/typescript/types/#using-ambient-or-global-types. Thanks.

`nm_host.ts`
```
#!/usr/bin/env -S /home/xubuntu/bin/deno run 
// https://www.codeconvert.ai/javascript-to-typescript-converter
// @ts-self-types="./lib.es2023.d.ts"
// @ts-self-types="./lib.es2024.arraybuffer.d.ts"

const runtime: string = navigator.userAgent;
const buffer: ArrayBuffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
```

or path `node_modules` of this PR source

```
// Convert JavaScript to TypeScript, no obvious equivalent with tsc
// https://www.codeconvert.ai/javascript-to-typescript-converter
//
// @ts-self-types="./node_modules/@typescript-deploys/pr-build/lib/lib.es2023.d.ts"
// @ts-self-types="./node_modules/@typescript-deploys/pr-build/lib/lib.es2024.arraybuffer.d.ts"

const runtime: string = navigator.userAgent;
const buffer: ArrayBuffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
```

File: src/lib/es2024.collection.d.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
+interface MapConstructor {
+    /**
+     * Groups members of an iterable according to the return value of the passed callback.
+     * @param items An iterable.
+     * @param keySelector A callback which will be invoked for each item in items.
+     */
+    groupBy<K, T>(
+        items: Iterable<T, unknown, undefined>,
```
Comment (petamoriken) [inline src/lib/es2024.collection.d.ts:8]: Should this be `Iterable<T>`?

File: src/lib/es2024.object.d.ts [hunk 6]
```diff
@@ -5,7 +5,7 @@ interface ObjectConstructor {
      * @param keySelector A callback which will be invoked for each item in items.
      */
     groupBy<K extends PropertyKey, T>(
-        items: Iterable<T>,
+        items: Iterable<T, unknown, undefined>,
```
Comment (petamoriken) [inline src/lib/es2024.object.d.ts:8]: ditto

**Comment by petamoriken** [comment]
Blocked by #59417

**Comment by rbuckton** [comment]
What we might want to do is to extract the interface changes for `ArrayBuffer` and `SharedArrayBuffer` to an independent PR so that we can merge the rest of this sooner. We can then take the `ArrayBuffer`/`SharedArrayBuffer` changes once #59417 has merged.

File: src/compiler/types.ts [hunk 7]
```diff
@@ -8379,13 +8381,14 @@ export type LanugageFeatures =
     | "RegularExpressionFlagsHasIndices"
     // ES2023 Features
     | "ShebangComments"
+    // ES2024 Features
+    | "RegularExpressionFlagsUnicodeSets"
     // Upcoming Features
     // NOTE: We must reevaluate the target for upcoming features when each successive TC39 edition is ratified in
     //       June of each year. This includes changes to `LanguageFeatureMinimumTarget`, `ScriptTarget`,
     //       transformers/esnext.ts, commandLineParser.ts, and the contents of each lib/esnext.*.d.ts file.
```
Comment (petamoriken) [inline src/compiler/types.ts:8389]: Oh, I should update this comment

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test top400

**Comment by rbuckton** [comment]
@typescript-bot: pack this

**Comment by guest271314** [comment]
> There is also a playground [for this build](https://www.typescriptlang.org/play?ts=5.7.0-pr-58573-47)

https://www.typescriptlang.org/play/?ts=5.7.0-pr-58573-47

> This version of TypeScript (5.7.0-pr-58573-47)
> has not been prepared for the Playground
> 
> Try [5.6.2](https://www.typescriptlang.org/play?ts=5.6.2) or [Nightly](https://www.typescriptlang.org/play?ts=next)

**Comment by rbuckton** [comment]
I think I found a few more things that need to be addressed in the NodeJS types that are affecting `Buffer` assignability to `Uint8Array<TArrayBuffer>` when using the types from this PR.

**Comment by rbuckton** [comment]
I have a fix up for `Buffer`: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70694. Hopefully that will address the remaining issues for the failing projects.

**Comment by rbuckton** [comment]
I am validating that updating @types/node to 22.7.4 in the remaining failing cases addresses those issues prior to merging. So far, I've verified that it does indeed fix the issues in `bokeh`.

**Comment by rbuckton** [comment]
I'm fairly certain the remaining failures are addressed by `@types/node@22.7.4`. I will file pull requests for each project to update their types.

**Review by rbuckton — APPROVED** [review]
