### PR TITLE
Constructor functions as classes

### LINKED ISSUE #23007: In JS, function declarations should allow subsequent prototype assignment
```js
// @allowJs: true
// @checkJs: true
// @Filename: a.js
function C(p) {
  this.p = p
}
C.prototype = {
  m() {
    console.log(this.p)
  }
}
C.prototype.q = function(r) {
  return this.p === r
}
var c = new C(1)
c.q(2)
c.m()
```

**Expected behavior:**
Both `q` and `m` are methods on `c`.

**Actual behavior:**
Only `q` is a method on `c`; `m` is not recognised.

Note that if the declaration is `var C = function(p) { this.p = p }`, everything works. This only happens when `C` is a function declaration instead of a variable declaration with a function initialiser.

### LINKED ISSUE #26833: getApplicableRefactors on file with recursive types freezes TSServer
**TypeScript Version:**  3.1.0-dev.20180901

**Search Terms:** none

When working on a file with several recursive types, the TSServer process got stuck in an endless loop and continued building up memory. Later this error showed up in the error console in VSCode:
```
[Info  - 10:12:55 AM] Using tsserver from: c:\Users\domin\Documents\Visual Studio 2017\Repositories\shared-utils\node_modules\typescript\lib
[Error  - 10:12:55 AM] 'getApplicableRefactors' request failed with error.
Error: Service died.
	at TypeScriptServiceClient.serviceExited (c:\Users\domin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\out\typescriptServiceClient.js:413:32)
	at ChildProcess.handle.onExit (c:\Users\domin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\out\typescriptServiceClient.js:326:30)
	at emitTwo (events.js:131:20)
	at ChildProcess.emit (events.js:214:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Related Issues:** #26155

### PR DESCRIPTION
**Pull request by sandersn**
In JS, constructor functions are now classes. That means:

1. They use the normal class type machinery for creation and caching.
2. `this` types work.
3. Generics work.

And it only adds about 40 lines of code!

Fixes #26833
Fixes #23007

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5970,19 +5974,10 @@ namespace ts {
             if (!links.type) {
                 const jsDeclaration = getDeclarationOfExpando(symbol.valueDeclaration);
                 if (jsDeclaration) {
-                    const jsSymbol = getSymbolOfNode(jsDeclaration);
-                    if (jsSymbol && (hasEntries(jsSymbol.exports) || hasEntries(jsSymbol.members))) {
-                        symbol = cloneSymbol(symbol);
+                    const merged = mergeJSSymbols(symbol, getSymbolOfNode(jsDeclaration));
+                    if (merged) {
                         // note:we overwrite links because we just cloned the symbol
-                        links = symbol as TransientSymbol;
```
Comment (sandersn) [inline src/compiler/checker.ts]: the code that's now in mergeJSSymbols is used both here, in getTypeOfFuncClassEnumModule, and in getDeclaredTypeOfClassOrInterface.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6157,6 +6152,16 @@ namespace ts {
         function getOuterTypeParameters(node: Node, includeThisTypes?: boolean): TypeParameter[] | undefined {
             while (true) {
                 node = node.parent; // TODO: GH#18217 Use SourceFile kind check instead
+                if (node && isBinaryExpression(node)) {
+                    // prototype assignments get the outer type parameters of their constructor function
+                    const assignmentKind = getAssignmentDeclarationKind(node);
+                    if (assignmentKind === AssignmentDeclarationKind.Prototype || assignmentKind === AssignmentDeclarationKind.PrototypeProperty) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: Object.defineProperty has a number of other limitations and bugs that make it not worthwhile to support yet.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6157,6 +6152,16 @@ namespace ts {
         function getOuterTypeParameters(node: Node, includeThisTypes?: boolean): TypeParameter[] | undefined {
             while (true) {
                 node = node.parent; // TODO: GH#18217 Use SourceFile kind check instead
+                if (node && isBinaryExpression(node)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: prototype assignments jump from the assignment location to the location of the constructor function and continues walking up the tree looking for type parameters. It does *not* fork and continue looking from the site of the assignment.

In a [hilarious tweet](https://twitter.com/sanders_n/status/1162131784009523202), I provided some code where this  difference could be observed, but it was clearly insane. I think this is a good solution, because it makes prototype assignments act as if they are effectively nested inside the constructor function, in the same way that methods are nested inside classes in modern JS.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -6244,7 +6250,7 @@ namespace ts {
                 const constraint = getBaseConstraintOfType(type);
                 return !!constraint && isValidBaseType(constraint) && isMixinConstructorType(constraint);
             }
-            return isJSConstructorType(type);
```
Comment (sandersn) [inline src/compiler/checker.ts]: The first case of this function now covers constructor functions.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -7504,12 +7512,18 @@ namespace ts {
                 // will never be observed because a qualified name can't reference signatures.
                 if (symbol.flags & (SymbolFlags.Function | SymbolFlags.Method)) {
                     type.callSignatures = getSignaturesOfSymbol(symbol);
-                    type.constructSignatures = filter(type.callSignatures, sig => isJSConstructor(sig.declaration));
```
Comment (sandersn) [inline src/compiler/checker.ts]: Construct signatures are now constructed just below here, for symbols marked `Class | Function` only, instead of running this on all functions.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -8744,7 +8758,6 @@ namespace ts {
                 let type = signature.target ? instantiateType(getReturnTypeOfSignature(signature.target), signature.mapper!) :
                     signature.unionSignatures ? getUnionType(map(signature.unionSignatures, getReturnTypeOfSignature), UnionReduction.Subtype) :
                     getReturnTypeFromAnnotation(signature.declaration!) ||
-                    isJSConstructor(signature.declaration) && getJSClassType(getSymbolOfNode(signature.declaration!)) ||
```
Comment (sandersn) [inline src/compiler/checker.ts]: this special case also moves into the `Class|Function` case of resolveAnonymousTypeMembers, where the correct answer is now just `classType`.

Note that call signatures of constructor functions now correctly fall through to `getReturnTypeFromBody`, where before they *also* claimed to return the class type from `getJSClassType`.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -11083,10 +11096,25 @@ namespace ts {
             const parent = container && container.parent;
             if (parent && (isClassLike(parent) || parent.kind === SyntaxKind.InterfaceDeclaration)) {
                 if (!hasModifier(container, ModifierFlags.Static) &&
-                    (container.kind !== SyntaxKind.Constructor || isNodeDescendantOf(node, (<ConstructorDeclaration>container).body!))) {
+                    (!isConstructorDeclaration(container) || isNodeDescendantOf(node, container.body))) {
                     return getDeclaredTypeOfClassOrInterface(getSymbolOfNode(parent as ClassLikeDeclaration | InterfaceDeclaration)).thisType!;
                 }
             }
+
+            // inside x.prototype = { ... }
```
Comment (sandersn) [inline src/compiler/checker.ts]: getThisType and checkThisExpression should use the same code to look up the class' `thisType`, but do not. In particular, checkThisExpression's code, while more complete, is less efficient than this code since it uses `checkExpressionCached` instead of just grabbing symbol.parent. Since it's a separate change, I'll fix it in a followup PR.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -12378,15 +12406,17 @@ namespace ts {
             }
 
             if (!ignoreReturnTypes) {
-                // If a signature reolution is already in-flight, skip issuing a circularity error
+                // If a signature resolution is already in-flight, skip issuing a circularity error
                 // here and just use the `any` type directly
-                const targetReturnType = isResolvingReturnTypeOfSignature(target) ? anyType : (target.declaration && isJSConstructor(target.declaration)) ?
-                    getJSClassType(target.declaration.symbol)! : getReturnTypeOfSignature(target);
+                const targetReturnType = isResolvingReturnTypeOfSignature(target) ? anyType
+                    : target.declaration && isJSConstructor(target.declaration) ? getDeclaredTypeOfClassOrInterface(target.declaration.symbol)
```
Comment (sandersn) [inline src/compiler/checker.ts]: this allows a constructor function to be assignable BOTH to `new (x: number) => C` and `(x: number) => void`. I left it in because it seems ... useful for JS, even if it's not particularly safe.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -22826,39 +22852,35 @@ namespace ts {
 
                 // If the symbol of the node has members, treat it like a constructor.
                 const symbol = getSymbolOfNode(func);
-                return !!symbol && (symbol.members !== undefined || symbol.exports !== undefined && symbol.exports.get("prototype" as __String) !== undefined);
```
Comment (sandersn) [inline src/compiler/checker.ts]: this diff sucks! isJSConstructor is now simpler -- it no longer has to check symbol.exports.get("prototype") since the symbols are merged. And isJSConstructorType is deleted.

**Comment by sandersn** [comment]
@andrewbranch @orta @PranavSenthilnathan I thought you might be interested in this too.

**Comment by sandersn** [comment]
@typescript-bot perf test this

File: src/compiler/binder.ts [hunk 10]
```diff
@@ -2558,11 +2571,18 @@ namespace ts {
             node.left.parent = node;
             node.right.parent = node;
             const lhs = node.left as PropertyAccessEntityNameExpression;
-            bindPropertyAssignment(lhs.expression, lhs, /*isPrototypeProperty*/ false);
+            const constructorSymbol = lookupSymbolForPropertyAccess(lhs.expression);
+            if (constructorSymbol) {
```
Comment (weswigham) [inline src/compiler/binder.ts]: I think this binding should be unconditional, so a merge cross-file can occur. Eg,
```js
// file1.js
function C() {
  this.a = 2;
}
// file2.js
C.prototype.foo = function() { return this.a; };
```

File: src/compiler/binder.ts [hunk 11]
```diff
@@ -2558,11 +2571,18 @@ namespace ts {
...
+                addDeclarationToSymbol(constructorSymbol, constructorSymbol.valueDeclaration, SymbolFlags.Class);
+            }
+            bindPropertyAssignment(constructorSymbol, lhs, /*isPrototypeProperty*/ false);
         }
 
         function bindObjectDefinePrototypeProperty(node: BindableObjectDefinePropertyCall) {
             const namespaceSymbol = lookupSymbolForPropertyAccess((node.arguments[0] as PropertyAccessExpression).expression as EntityNameExpression);
+            if (namespaceSymbol) {
+                addDeclarationToSymbol(namespaceSymbol, namespaceSymbol.valueDeclaration, SymbolFlags.Class);
```
Comment (weswigham) [inline src/compiler/binder.ts]: same here

File: src/compiler/binder.ts [hunk 12]
```diff
@@ -227,7 +227,8 @@ namespace ts {
             symbol.flags |= symbolFlags;
 
             node.symbol = symbol;
-            symbol.declarations = append(symbol.declarations, node);
+            // TODO: This is probably too slow to run on every call
```
Comment (sandersn) [inline src/compiler/binder.ts]: perf numbers seem fine, so I should remove this TODO

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -22826,39 +22852,35 @@ namespace ts {
...
+                return !!symbol && symbol.members !== undefined;
             }
             return false;
         }
 
-        function getJSClassType(symbol: Symbol): Type | undefined {
-            let inferred: Type | undefined;
-            if (isJSConstructor(symbol.valueDeclaration)) {
-                inferred = getInferredClassType(symbol);
+        function mergeJSSymbols(target: Symbol, source: Symbol | undefined) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: If `mergeJSSymbols` is called twice with the same pair of symbols, you'll get a new output symbol - I think the result of the merge needs to be stored, eg, on the symbol links of the target.

File: src/compiler/binder.ts (hunk 10 above)
Comment (sandersn) [reply src/compiler/binder.ts]: This is pretty complicated because of things like

```js
Outer.Inner = function() { this.a = 1 }
Outer.Inner.prototype = { ... }
```

Probably needs an iterated declareSymbol just like declarePossiblyMissingNamespace.

Comment (weswigham) [reply src/compiler/binder.ts]: Yep, that sounds about right.

File: src/compiler/binder.ts (hunk 11 above)
Comment (sandersn) [reply src/compiler/binder.ts]: As I originally suspected, bindPotentiallyMissingNamespaces overlaps a lot with lookupSymbolForPropertyAccess+addDeclarationToSymbol, so the right thing is to put it there. Couple of caveats:

1. bindObjectDefinePrototypeProperty doesn't call bindPropertyAssignment, so cross-file merges don't work for it currently anyway. I want to merge this PR soon, so I filed #32979 to track adding that (and testing it, which is the bigger task.)
2. The symbol binding is still technically conditional, but works in all the cases that cross-file binding does today.
3. I'm still working on making it *elegant*, which is why I didn't do it in the first place. Currently I'm passing two booleans, isPrototypeProperty and isClass, which Seems Bad. I'll push a commit after I figure out whether an enum can work well here.

File: src/compiler/checker.ts (hunk 13 above)
Comment (sandersn) [reply src/compiler/checker.ts]: It's not future-proof, but we both looked at the callers of mergeJSSymbols and they both cache immediately after calling it.
