### PR TITLE
Error if type node uses inaccessible type in isolated declarations

### LINKED ISSUE #58558: Isolated declarations allows return types that reference local expr or type
### 🔎 Search Terms

- isolated declarations
- typeof
- local types
- function return type

### 🕗 Version & Regression Information

5.5.0-dev.20240517

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&isolatedDeclarations=true&ts=5.5.0-dev.20240517#code/MYewdgzgLgBAHjAvDARCg3AKAKZwA4gBOsAZgK5jBQCW4M42AFAJQwDemMXMh2UZhMOwC+MAIYQYUAJ55sIEvCzDMOfEVIUqtIVADuIFu07dQkWNKSoMJrr36CR4yTLkKY05atwFiMcpQ0dFAAFrxMrBzcUrLYMABaVtCE1GAA5ljR9gJCbKISCV5AA

### 💻 Code

```ts
const x = "";
export function one() {
    return {} as typeof x;
}

export function two() {
    const y = "";
    return {} as typeof y;
}

export function three() {
    type Z = string;
    return {} as Z;
}
```

### 🙁 Actual behavior

No diagnostics are raised.

### 🙂 Expected behavior

An isolated declarations error is raised for function `two` and function `three` (missing explicit return type), because even though both return an "explicit" type (using `as` casting), neither can be emitted without using a type checker because the type / expression they reference are internal to the function.

### Additional information about the issue

I was looking for a case where this can happen top level, but I just ran into a different TypeScript error then: https://github.com/microsoft/TypeScript/issues/58557

cc @dragomirtitian

### PR DESCRIPTION
**Pull request by dragomirtitian**
Fixes #58558

### CODE REVIEW

File: tests/baselines/reference/transpile/declarationNotInScopeTypes.d.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        return {} as typeof y;
+                            ~
+!!! error TS9038: Type containing private name 'y' can't be used with --isolatedDeclarations.
+    }
+    
+    export function three() {
+        type Z = string;
+        return {} as Z;
+                     ~
+!!! error TS9038: Type containing private name 'Z' can't be used with --isolatedDeclarations.
```
Comment (weswigham) [inline tests/baselines/reference/transpile/declarationNotInScopeTypes.d.ts:46]: Q: Is there a reason this shouldn't get a "annotate this function return" related span?

**Review by weswigham — APPROVED** [review]

File: tests/baselines/reference/transpile/declarationNotInScopeTypes.d.ts (hunk 1 above)
Comment (dragomirtitian) [reply tests/baselines/reference/transpile/declarationNotInScopeTypes.d.ts:46]: It should. I'll add it

**Review by weswigham — APPROVED** [review]
