### PR TITLE
Fix broken user and docker tests

### LINKED ISSUE #42445: Maximum call stack size exceeded in isJSLiteralType
This was discovered in the docker tests run for office-ui-fabric:

image

The function in question is here: 
https://github.com/microsoft/TypeScript/blob/424b805d6166c5095be97d8328ebaf1968ec1028/src/compiler/checker.ts#L14088-L14105

```ts
        function isJSLiteralType(type: Type): boolean {
            if (noImplicitAny) {
                return false; // Flag is meaningless under `noImplicitAny` mode
            }
            if (getObjectFlags(type) & ObjectFlags.JSLiteral) {
                return true;
            }
            if (type.flags & TypeFlags.Union) {
                return every((type as UnionType).types, isJSLiteralType);
            }
            if (type.flags & TypeFlags.Intersection) {
                return some((type as IntersectionType).types, isJSLiteralType);
            }
            if (type.flags & TypeFlags.Instantiable) {
                return isJSLiteralType(getResolvedBaseConstraint(type));
            }
            return false;
        }
```

The `getResolvedBaseConstraint` function can return `type` in some cases, creating a circularity. 

I will be adding a fix as part of #42431.

### PR DESCRIPTION
**Pull request by rbuckton**
Fix failing user tests due to peer dependency issues.

Fixes #42445.

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot user test this

**Review by sandersn — COMMENTED** [review]
What about `--legacy-peer-deps`? That seems to be the intended workaround: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

If this works, though, it's fine to merge it.

**Comment by rbuckton** [comment]
I debated between that and `--force`. I think either will work for now, but you are probably correct (as long as `--legacy-peer-deps` isn't removed at some point in the future). I was mostly concerned about npm version differences (i.e., if the tests were for some reason run on an earlier version of npm that doesn't yet support `--legacy-peer-deps`).

**Comment by rbuckton** [comment]
Ok, I *think* that's all of them. Need to run tests and accept new baselines.

@typescript-bot user test this

**Comment by rbuckton** [comment]
@sandersn BTW, I switched to using `--legacy-peer-deps` but made it conditional on whether npm's major version is >= 7.

**Comment by rbuckton** [comment]
A few things:
There seems to be an error a the end of `runTests`: 
image

Also, `office-ui-fabric` has (expected) failures since they haven't updated their version of `tslib` to the latest version. @weswigham, is that something we should do manually in the Dockerfile (since we also are overriding the version of TypeScript), or should we just leave it until they update?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14099,7 +14099,8 @@ namespace ts {
                 return some((type as IntersectionType).types, isJSLiteralType);
             }
             if (type.flags & TypeFlags.Instantiable) {
-                return isJSLiteralType(getResolvedBaseConstraint(type));
+                const constraint = getResolvedBaseConstraint(type);
+                return constraint !== type && isJSLiteralType(constraint);
```
Comment (weswigham) [inline src/compiler/checker.ts:14103]: Should we have a compiler test for this crash fix?

File: src/testRunner/externalCompileRunner.ts [hunk 2]
```diff
@@ -68,31 +68,35 @@ namespace Harness {
...
                     args.push("--noEmit");
                     Baseline.runBaseline(`${cls.kind()}/${directoryName}.log`, cls.report(cp.spawnSync(`node`, args, { cwd, timeout, shell: true }), cwd));
 
-                    function exec(command: string, args: string[], options: { cwd: string, timeout?: number }): void {
+                    function exec(command: string, args: string[], options: { cwd: string, timeout?: number, stdio?: import("child_process").StdioOptions }): string | undefined {
                         const res = cp.spawnSync(isWorker ? `${command} 2>&1` : command, args, { shell: true, stdio, ...options });
                         if (res.status !== 0) {
                             throw new Error(`${command} ${args.join(" ")} for ${directoryName} failed: ${res.stdout && res.stdout.toString()}`);
                         }
+                        return options.stdio === "pipe" ? res.stdout.toString("utf8") : undefined;
```
Comment (weswigham) [inline src/testRunner/externalCompileRunner.ts:99]: We don't actually use this returned value anywhere, do we?

File: tests/cases/docker/xterm.js/Dockerfile [hunk 3]
```diff
@@ -1,5 +1,5 @@
 # node-pty doesn't build on node 12 right now, so we lock to 8 - the version xterm itself tests against :(
```
Comment (weswigham) [inline tests/cases/docker/xterm.js/Dockerfile:1]: Should probably update this comment, too.

File: tests/cases/docker/vscode/Dockerfile [hunk 4]
```diff
@@ -10,6 +10,7 @@ COPY --from=typescript/typescript /typescript/typescript-*.tgz /typescript.tgz
 WORKDIR /vscode/build
 RUN yarn add typescript@/typescript.tgz
 WORKDIR /vscode/extensions
+RUN yarn add rimraf
```
Comment (weswigham) [inline tests/cases/docker/vscode/Dockerfile:13]: Is this working around a bug in vscode's own build? Since we clearly don't sue rimraf here in the dockerfile.

File: tests/cases/docker/prettier/Dockerfile [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+WORKDIR /prettier
+RUN git pull
+COPY --from=typescript/typescript /typescript/typescript-*.tgz /typescript.tgz
+RUN mkdir /typescript
+RUN tar -xzvf /typescript.tgz -C /typescript
+RUN yarn add typescript@/typescript.tgz
+RUN yarn
+ENTRYPOINT [ "yarn" ]
+# Build
+CMD [ "build" ]
```
Comment (weswigham) [inline tests/cases/docker/prettier/Dockerfile:13]: Hm, so the user test previously just applied a custom tsconfig to the contents of the `src` directory and built it. That actually includes way more than they typecheck in their own build: https://github.com/prettier/prettier/blob/master/tsconfig.json Do we want to continue checking the whole src folder under our own rules like the `user` test used to, or should we use their build like this?

File: src/compiler/checker.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/checker.ts:14103]: I'm honestly not sure how to trigger it. It was triggered by something using typescript to parse just.config.ts in office-ui-fabric, and I'm not sure how deep the rabbit hole goes. At least its verified by the fact that office-ui-fabric is compiling again.

File: src/testRunner/externalCompileRunner.ts (hunk 2 above)
Comment (rbuckton) [reply src/testRunner/externalCompileRunner.ts:99]: I'm using it to test the npm version, since `--legacy-peer-deps` is new in npm 7, so if you're running tests on an older NodeJS/npm that flag would result in an error.

**Comment by weswigham** [comment]
> is that something we should do manually in the Dockerfile (since we also are overriding the version of TypeScript), or should we just leave it until they update? 

If it significantly blocks the baseline's usefulness, yeah, we can; otherwise I'd just accept the baseline with the errors until they patch the version themselves.

File: tests/cases/docker/vscode/Dockerfile (hunk 4 above)
Comment (rbuckton) [reply tests/cases/docker/vscode/Dockerfile:13]: Yes. The `vscode` build is failing because they have a postinstall.js script that runs rimraf to clean up TypeScript files they don't need, but we're running `yarn add` for our copy of TypeScript *before* all the dependencies are installed which triggers the postinstall script.

File: tests/cases/docker/prettier/Dockerfile (hunk 5 above)
Comment (rbuckton) [reply tests/cases/docker/prettier/Dockerfile:13]: I'd probably use their build, since that's what they're running.

**Comment by rbuckton** [comment]
> If it significantly blocks the baseline's usefulness, yeah, we can; otherwise I'd just accept the baseline with the errors until they patch the version themselves.

I'm unclear as to how I can accept user/docker test baselines. Can I do that from https://github.com/typescript-bot/TypeScript/pull/137? If so, I don't have permission to merge changes in that repo. Or do I need to run them all locally and accept?

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:14103]: Off the top of my head, I know pattern template literals are returned as their own constraint by computeBaseConstraint, and are.... Kinda recent? So maybe there's a situation with a template triggering it?

File: src/testRunner/externalCompileRunner.ts (hunk 2 above)
Comment (weswigham) [reply src/testRunner/externalCompileRunner.ts:99]: Ahhh, ok

File: tests/cases/docker/vscode/Dockerfile (hunk 4 above)
Comment (weswigham) [reply tests/cases/docker/vscode/Dockerfile:13]: Does yarn have a `--ignore-scripts` equivalent we should use instead?

**Comment by weswigham** [comment]
You can pick the change the bot generates into a PR of your choosing or generate the baselines locally, yeah.

File: tests/cases/docker/vscode/Dockerfile (hunk 4 above)
Comment (rbuckton) [reply tests/cases/docker/vscode/Dockerfile:13]: Nope, not according to the docs for `yarn add`.

**Comment by rbuckton** [comment]
@weswigham any other feedback? If not I'd like to merge this so we can get the user tests working again.

**Review by weswigham — APPROVED** [review]
An isolated test for that crash big would still be nice.

**Comment by rbuckton** [comment]
I'll look into a repro, though I haven't had much luck so far tracking down what specific effects triggered it for the office-ui-fabric project.
