### PR TITLE
Fixed JS completions type spread

### LINKED ISSUE #45436: Word based suggestions returned when starting to type spread
Discovered in https://github.com/microsoft/vscode/issues/130096

# Bug Report

### 🔎 Search Terms

-  word based suggestions
- javascript
- spread
- warning suggestions

### 🕗 Version & Regression Information

4.4.1-rc

### 💻 Code

1. In a JS file:

```ks
const abc = {};

({ })
```

2. Put cursor inside the object literal and type: `.`

### 🙁 Actual behavior

JS `warning` suggestions (word based suggestions) are returned:

```
[Trace  - 22:36:59.359] <semantic> Response received: completionInfo (308). Request took 7 ms. Success: true 
Result: {
    "isGlobalCompletion": false,
    "isMemberCompletion": true,
    "isNewIdentifierLocation": false,
    "entries": [
        {
            "name": "abc",
            "kind": "warning",
            "kindModifiers": "",
            "sortText": "17"
        }
    ]
}
```

### 🙂 Expected behavior

No suggestions should be returned in this case since the user is likely starting to type a spread operator

### PR DESCRIPTION
**Pull request by armanio123**
Fixed #45436.

Also, fixes a couple of tests that I believe are incorrect.

### CODE REVIEW

**Review by andrewbranch — CHANGES_REQUESTED** [review]
There is probably some room for debate here, but I think the expected behavior described in the bug is wrong. The completions offered here are arguably correct (the existing tests certainly weren’t written in error; they are clearly asserting the behavior that’s being reverted here); the problem is that `isNewIdentifierLocation` is `false` but should be `true`. Flipping it to `true` will keep the existing completions, but will prevent `.` from triggering them, _I think_ (needs to be manually tested).

**Comment by andrewbranch** [comment]
Also, `isMemberCompletion` seems possibly wrong, but I don’t know what that controls 🤔

**Comment by armanio123** [comment]
I checked on the `isNewIdentifierLocation` as well and I disagree it must be true. This issue only happens for `js` files and when comparing against `ts` files, `isNewIdentifierLocation` still remains as false. `symbols` and `keywordFilters` are the ones that avoid returning early.

In regards to the tests, the completions provided are actually incorrect as the code would be wrong and not really access the property. i.e. in `completionInUncheckedJSFile.ts`, hello and goodbye are not related to the console object or in `javaScriptPrototype2.ts` the example is not really able to access to ctor prototype attribute so completions would be incorrect in my opinion.

**Comment by DanielRosenwasser** [comment]
> In regards to the tests, the completions provided are actually incorrect as the code would be wrong and not really access the property

If I recall correctly, the point of `isNewIdentifierLocation` being true in JS cases is that we don't really have an authoritative view of the types, and can't let editors aggressively complete there; however, it's useful to leverage other words in the file or project, and so you still want to provide completion results (again, since we don't *know* that they're unrelated). To try to relay that they're unrelated, we deprioritize them compared to whatever else we're confident of.

**Comment by andrewbranch** [comment]
Discussed in the call, but to put in writing—the reason `isNewIdentifierLocation` should be true in this case is because

```ts
({ | })
```

at this point you very well may be writing a new property declaration or even binding pattern, which is exactly what `isNewIdentifierLocation` is for—_any_ time you could be writing a name not already in scope, that property must be set to `true` on any completion responses.

**Comment by DanielRosenwasser** [comment]
> I think the expected behavior described in the bug is wrong

I'm not sure I agree with this part. The thing that's really being complained about is the fact that we're providing completions after a `.` in a context where no completion item would be valid.

But otherwise, yes, the existing tests were written intentionally.

**Comment by andrewbranch** [comment]
> The thing that's really being complained about is the fact that we're providing completions after a `.` in a context where no completion item would be valid.

Yeah, I missed that in the bug because I wasn’t reproing it successfully, but Armando clarified for me—I was claiming that there should be completions at `({ | })` (with a manual trigger), not at `({ .| })`.

File: src/services/completions.ts [hunk 1]
```diff
@@ -1338,13 +1338,16 @@ namespace ts.Completions {
                     case SyntaxKind.PropertyAccessExpression:
                         propertyAccessToConvert = parent as PropertyAccessExpression;
                         node = propertyAccessToConvert.expression;
-                        if ((isCallExpression(node) || isFunctionLike(node)) &&
-                            node.end === contextToken.pos &&
-                            node.getChildCount(sourceFile) &&
-                            last(node.getChildren(sourceFile)).kind !== SyntaxKind.CloseParenToken) {
+                        const leftMostAccessExpression = getLeftmostAccessExpression(parent as Expression);
+                        if (leftMostAccessExpression.pos === leftMostAccessExpression.end ||
```
Comment (andrewbranch) [inline src/services/completions.ts:1342]: Equivalent simplifications:

```suggestion
                        const leftMostAccessExpression = getLeftmostAccessExpression(propertyAccessToConvert);
                        if (nodeIsMissing(leftMostAccessExpression) ||
```

**Review by andrewbranch — APPROVED** [review]
Nice work!

File: src/services/completions.ts [hunk 2]
```diff
@@ -1338,13 +1338,16 @@ namespace ts.Completions {
...
-                        if ((isCallExpression(node) || isFunctionLike(node)) &&
-                            node.end === contextToken.pos &&
-                            node.getChildCount(sourceFile) &&
-                            last(node.getChildren(sourceFile)).kind !== SyntaxKind.CloseParenToken) {
+                        const leftMostAccessExpression = getLeftmostAccessExpression(parent as Expression);
+                        if (leftMostAccessExpression.pos === leftMostAccessExpression.end ||
+                            ((isCallExpression(node) || isFunctionLike(node)) &&
+                                node.end === contextToken.pos &&
+                                node.getChildCount(sourceFile) &&
+                                last(node.getChildren(sourceFile)).kind !== SyntaxKind.CloseParenToken)) {
```
Comment (andrewbranch) [inline src/services/completions.ts:1346]: I actually wonder if this whole second condition is even needed now... seems like the examples in the comments would be covered by the new condition you added. It doesn’t hurt to leave it in, so I probably wouldn’t change it this close to a release, but it might be worth running tests with it removed just to see if it can be cleaned up and simplified in the future.

**Review by sandersn — APPROVED** [review]
+1 on @andrewbranch's nodeIsMissing check.

File: src/services/completions.ts (hunk 2 above)
Comment (armanio123) [reply src/services/completions.ts:1346]: I tried removing it as well and a couple of tests failed so I decided to leave it in place. Errors were related to writing syntax like 
```js
const foo = {
    bar: function (.| ) {}
}
```

File: src/services/completions.ts (hunk 1 above)
Comment (armanio123) [reply src/services/completions.ts]: Commited.

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.4
