### PR TITLE
Modify debug assertion to avoid crashing on SyntaxList

### LINKED ISSUE #21815: Error: Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement` in 'findRightmostChildNodeWithTokens' during 'quickinfo'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.0
**command requested**: quickinfo
**hitting sessions**: 494
**proportion of all sessions**: 0.0018441574925431082
**five line hash**: aa0b19994104f0573fb850c0e70e08e6
**stack**
```
Error: Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`
    at findRightmostChildNodeWithTokens (tsserver.js:64703:30)
    at find (tsserver.js:64695:33)
    at findPrecedingToken (tsserver.js:64661:22)
    at getTokenAtPositionWorker (tsserver.js:64624:41)
    at getTouchingToken (tsserver.js:64596:16)
    at Object.getTouchingPropertyName (tsserver.js:64592:16)
    at Object.getQuickInfoAtPosition (tsserver.js:82890:27)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:89819:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:88972:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### LINKED ISSUE #46946: Error in 'findRightmostChildNodeWithTokens' during 'quickinfo'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript version prefix**: 4.5.2
**VSCode version**: 1.63.0-insider
**Command requested**: quickinfo
**Hitting sessions**: 252
**Five line hash**: f56d3f7ffcdccb71556bd2cea00d6c77
**Stack**:
```
    at findRightmostChildNodeWithTokens (tsserver.js:123979:26)
    at find (tsserver.js:123953:29)
    at findPrecedingToken (tsserver.js:123903:22)
    at nodeContainsPosition (tsserver.js:123838:37)
    at <anonymous> (tsserver.js:123795:21)
    at binarySearchKey (tsserver.js:1200:21)
    at _loop_1 (tsserver.js:123770:24)
    at getTokenAtPositionWorker (tsserver.js:123820:27)
    at getTouchingToken (tsserver.js:123755:16)
    at getTouchingPropertyName (tsserver.js:123747:16)
    at getQuickInfoAtPosition (tsserver.js:160056:27)
    at Session.getQuickInfoWorker (tsserver.js:171406:62)
    at _a.<computed> (tsserver.js:170300:61)
    at <anonymous> (tsserver.js:172158:88)
    at Session.executeWithRequestId (tsserver.js:172149:28)
    at Session.executeCommand (tsserver.js:172158:33)
    at Session.onMessage (tsserver.js:172184:35)
    at <anonymous> (tsserver.js:174789:31)
    at unknown (suppressed.js:315:20)
    at unknown (suppressed.js:337:10)
    at unknown (suppressed.js:482:12)
    at unknown (suppressed.js:194:10)
    at unknown (suppressed.js:315:20)
    at unknown (suppressed.js:309:12)
    at unknown (suppressed.js:284:9)
    at unknown (suppressed.js:223:10)
    at unknown (suppressed.js:188:23)
```

### LINKED ISSUE #47446: Crash on quick info on `<` in JSX closing tag
Likely to be https://github.com/microsoft/TypeScript/issues/21815
Likely to be https://github.com/microsoft/TypeScript/issues/46946

```ts
let x = <div>
    /*$*/</div >
```

Request quick info on the `<`.

**Expected** I dunno, probably nothing!
**Actual**

```
Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`
Error: Debug Failure. False expression: `JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`
    at findRightmostChildNodeWithTokens ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124512:26)
    at find ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124486:29)
    at findPrecedingToken ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124436:22)
    at nodeContainsPosition ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124371:37)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124328:21
    at Object.binarySearchKey ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:1187:21)
    at _loop_1 ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124303:24)
    at getTokenAtPositionWorker ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124353:27)
    at getTouchingToken ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124288:16)
    at Object.getTouchingPropertyName ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:124280:16)
    at Object.getQuickInfoAtPosition ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:160763:27)
    at IOSession.Session.getQuickInfoWorker ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:172179:62)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:171070:61)
    at [USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:172931:88
    at IOSession.Session.executeWithRequestId ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:172922:28)
    at IOSession.Session.executeCommand ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:172931:33)
    at IOSession.Session.onMessage ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:172957:35)
    at Interface.<anonymous> ([USERDIR]\.vscode-insiders\extensions\ms-vscode.vscode-typescript-next-4.6.20220112\node_modules\typescript\lib\tsserver.js:175562:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Fourslash test

```ts
// @Filename: foo.tsx
////let x = <div>
////    /*$*/</div >

goto.marker("$");
verify.not.quickInfoExists();
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #47446
Fixes #21815
Fixes #46946

### CODE REVIEW

File: src/services/utilities.ts [hunk 1]
```diff
@@ -1332,19 +1332,20 @@ namespace ts {
...
         return candidate && findRightmostToken(candidate, sourceFile);
     }
 
     /**
-     * Finds the rightmost child to the left of `children[exclusiveStartPosition]` which is a non-all-whitespace token or has constituent tokens.
+     * Finds the rightmost child to the left of `n.children[exclusiveStartPosition]` which is a non-all-whitespace token or has constituent tokens.
      */
-    function findRightmostChildNodeWithTokens(children: Node[], exclusiveStartPosition: number, sourceFile: SourceFile): Node | undefined {
+    function findRightmostChildNodeWithTokens(n: Node, exclusiveStartPosition: number, sourceFile: SourceFile): Node | undefined {
+        const children = n.getChildren(sourceFile);
```
Comment (jakebailey) [inline src/services/utilities.ts:1343]: Not sure if I should bother leaving `children` as a parameter to save a little bit of processing; seemed more clear to me to just pass down the parent node and get the children, rather than passing the parent with its children (all call sites technically have the list).

Comment (amcasey) [reply src/services/utilities.ts:1343]: It looks like `n` is only needed for its kind and that kind is only needed for an assert so, personally, I'd add a new parameter for the kind to make it clear that it's "extra".

File: src/services/utilities.ts [hunk 2]
```diff
@@ -1332,19 +1332,20 @@ namespace ts {
...
         for (let i = exclusiveStartPosition - 1; i >= 0; i--) {
             const child = children[i];
 
-            if (isWhiteSpaceOnlyJsxText(child)) {
-                Debug.assert(i > 0, "`JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`");
+            if (i === 0 && isWhiteSpaceOnlyJsxText(child)) {
```
Comment (amcasey) [inline src/services/utilities.ts:1347]: Can you explain why the index check moved into the `if`?  That seems like a potentially big behavior change and I'm having trouble reasoning about its effect.

File: src/services/utilities.ts [hunk 3]
```diff
@@ -1332,19 +1332,20 @@ namespace ts {
...
+                Debug.assert(!(isJsxElement(n) || isJsxSelfClosingElement(n)), "`JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`");
             }
             else if (nodeHasTokens(children[i], sourceFile)) {
```
Comment (amcasey) [inline src/services/utilities.ts:1350]: Out of scope, but should `children[i]` be `child` here and below?

File: src/services/utilities.ts (hunk 2 above)
Comment (jakebailey) [reply src/services/utilities.ts:1347]: Shoot, you're right! I was trying to be too clever and optimize the assert, but I completely tunnel visioned away the code below. Will revert.

File: src/services/utilities.ts (hunk 3 above)
Comment (jakebailey) [reply src/services/utilities.ts:1350]: Yeah, this seems like an oops. I can fix this, if desired. Shouldn't change anything.

Comment (DanielRosenwasser) [reply src/services/utilities.ts:1351]: Maybe as a follow-up.

File: src/services/utilities.ts [hunk 4]
```diff
@@ -1332,19 +1332,21 @@ namespace ts {
...
      */
-    function findRightmostChildNodeWithTokens(children: Node[], exclusiveStartPosition: number, sourceFile: SourceFile): Node | undefined {
+    function findRightmostChildNodeWithTokens(children: Node[], exclusiveStartPosition: number, sourceFile: SourceFile, parentKind: SyntaxKind): Node | undefined {
         for (let i = exclusiveStartPosition - 1; i >= 0; i--) {
             const child = children[i];
 
             if (isWhiteSpaceOnlyJsxText(child)) {
-                Debug.assert(i > 0, "`JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`");
+                if (parentKind === SyntaxKind.JsxText || parentKind === SyntaxKind.JsxSelfClosingElement) {
+                    Debug.assert(i > 0, "`JsxText` tokens should not be the first child of `JsxElement | JsxSelfClosingElement`");
```
Comment (DanielRosenwasser) [inline src/services/utilities.ts:1348]: I might just fold the `i > 0` into the above condition and turn this into a `Debug.fail`, but this is fine.

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/utilities.ts (hunk 4 above)
Comment (jakebailey) [reply src/services/utilities.ts:1348]: Yeah, that's a reasonable change.

**Review by amcasey — APPROVED** [review]
Thanks!

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.5
