### PR TITLE
Conditional type simplifications & Globally cached conditional type instances

### LINKED ISSUE #28748: Unexpected error when using generic with Pick and Exclude
**TypeScript Version:**  3.2.1

**Search Terms:** generic pick exclude

**Code**

``` ts
//
// Example 1
//

const fn = <Params extends {}>(
    params: Pick<Params, Exclude<keyof Params, never>>,
): Params =>
    // Unexpected error
    /* Type 'Pick<Params, Exclude<keyof Params, never>>' is not assignable to type 'Params'. */
    params;

//
// Example 2
//

import * as React from 'react';
import { ComponentType, FunctionComponent } from 'react';

type User = { name: string };
type UserProp = { user: User };

export const myHoc = function<ComposedComponentProps extends UserProp>(
    ComposedComponent: ComponentType<ComposedComponentProps>,
) {
    // These two should be equivalent, but they're not?
    // Doesn't work:
    type Props = Pick<
        ComposedComponentProps,
        Exclude<keyof ComposedComponentProps, never>
    >;
    // Works:
    // type Props = ComposedComponentProps;

    const Component: FunctionComponent<Props> = props => (
        // Unexpected error
        /* Type 'PropsWithChildren<Pick<ComposedComponentProps, Exclude<keyof ComposedComponentProps, never>>>' is not assignable to type 'IntrinsicAttributes & ComposedComponentProps & { children?: ReactNode; }'.
            Type 'PropsWithChildren<Pick<ComposedComponentProps, Exclude<keyof ComposedComponentProps, never>>>' is not assignable to type 'ComposedComponentProps'. */
        <ComposedComponent {...props} />
    );

    return Component;
};
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #28748

Conditional types of the form `T extends U ? T : never` simplify to `T & U` if `T` always extends `U`, and `never` if `T` can never extend `U`.

Conditional types of the form `T extends U ? never : T` simplify to `T` (`T & not U` to be more precise, once those are available) if `T` never extends `U`, and `never` if `T` always extends `U`.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9982,6 +9982,26 @@ namespace ts {
             if (checkType === wildcardType || extendsType === wildcardType) {
                 return wildcardType;
             }
+            // Simplifications for types of the form `T extends U ? U : never` and `T extends U ? never : T`.
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: First form should be `T extends U ? T : never`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9982,6 +9982,26 @@ namespace ts {
             if (checkType === wildcardType || extendsType === wildcardType) {
                 return wildcardType;
             }
+            // Simplifications for types of the form `T extends U ? U : never` and `T extends U ? never : T`.
+            const originalCheckType = getActualTypeVariable(root.checkType);
+            const trueType = instantiateType(root.trueType, mapper);
+            const falseType = instantiateType(root.falseType, mapper);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: These instantiations were always deferred before. Now they're eager. I'm somewhat concerned this creates extra work that we don't need to do.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -9982,6 +9982,26 @@ namespace ts {
...
             }
+            // Simplifications for types of the form `T extends U ? U : never` and `T extends U ? never : T`.
+            const originalCheckType = getActualTypeVariable(root.checkType);
+            const trueType = instantiateType(root.trueType, mapper);
+            const falseType = instantiateType(root.falseType, mapper);
+            if (falseType.flags & TypeFlags.Never && getActualTypeVariable(root.trueType) === originalCheckType) {
+                if (isTypeAssignableTo(getRestrictiveInstantiation(checkType), getRestrictiveInstantiation(extendsType))) { // Always true
+                    return getIntersectionType([trueType, extendsType]);
+                }
+                else if (getUnionType([getIntersectionType([checkType, extendsType]), neverType]).flags & TypeFlags.Never) { // Always false
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Shouldn't this check the permissive form of the check and extends types? I'm not really following the logic here.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: I could defer them to only when simplified again, but then only types with a declared `never` would be simplifiable, whereas like this one brance can be instantiated to never, allowing a broader set of conditional types to be reduced.

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts]: So, the permissive form check returns `true` for `X extends never`, while this version of the check does not. We want to ignore the never extends never case here, since that will become a `never` result in both branches anyway (meaning we'd like x extends never of x extends something instantiable to never to simplify even when the permissive instantiation says there's technically one instantiatiom which'd give another result).

With negated types in place, I'd probably write the check as `isTypeAssignableTo(checkType, getNegatedType(extendsType))` instead, but without that in place, this accomplishes the same thing when only normal types exist.

**Comment by weswigham** [comment]
> Does this mean `Extract<number | string, any>` ~~> `any`?

Yeah - `number | string extends any` is trivially true, then we produce `(number | string) & any` which just becomes `any`. Specifically in the `extends any` case we maybe want to avoid making the intersection to avoid deleting information? We do this when calculating conditional constraints internally already.

**Comment by weswigham** [comment]
> I'll actually go extract the logic and reuse it.

Done~ `extends any` (and now things that instantiate to `any`) no longer create `any`'s in conditional type `true` branches (so they behave more like the `unknown` they're acting as).

**Comment by weswigham** [comment]
@ahejlsberg I've run this on user, RWC, and DT suites - there's no visible adverse effects. I think this is solid.

**Comment by fatcerberus** [comment]
> (number | string) & any which just becomes any

...wait, why?  Intuitively I expect that to simplify to `number | string`.  `any` is a really strange type isn’t it...

**Comment by jack-williams** [comment]
@fatcerberus It is best not to think of `any` as a type, but a set of types. I think current literature would have `(number | string) & any` be irreducible, but TypeScript predates that, and also has practical considerations. Reducing to any is probably the most sensible and conservative choice.

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt

**Comment by weswigham** [comment]
@typescript-bot run dt - I just made some changes after running into a manifestation of #30152 with the new simplifications on DT and included a small workaround.

**Comment by weswigham** [comment]
Sweet, the only change on DT is now a `NodePath<Identifier>` -> `NodePath<{ type: "Identifier"; } & Identifier>` in `babel`'s types inline with the baseline changes in this PR (which if supertype reduction was a thing would be a noop), so DT looks super clean now.

@ahejlsberg can we look at merging this again? #28748 is a pretty popular issue to fix and the global caching of conditionals should be a nice perf win.

**Comment by weswigham** [comment]
@ahejlsberg done.

**Comment by jcalz** [comment]
It's too bad that intersections of known concrete object types don't reduce to their mapped identity type automatically (e.g., `{a: string} & {b: number}` is not automatically collapsed to `{a: string, b: number}`, since this new behavior is going to take `Extract<T, U>` and turn it from a simple filtering of a union into a gnarly union-of-intersections.  I suppose one could get back something that looks like the old behavior via

```ts
type OldExtract<T, U> = T extends U ? { [K in keyof T]: T[K] } : never
```

maybe?

---

I'm also not sure how `T & U` is simpler than `T` if `T extends U` is known to be true.  If `T` extends `U` then `T & U` should be equivalent to `T` (except that the compiler probably won't notice it and will end up carrying around these vestigial intersections).  What am I missing?  Can someone give me an example of a type where `T extends U ? true : false` is `true` but `T & U` is not just a more complicated way of expressing `T`?

**Comment by Jessidhia** [comment]
`{} extends { a?: boolean } ? true : false` is `true`, but `{} & { a?: boolean }` is not the same as just `{}`

**Comment by jcalz** [comment]
Yeah, I'll buy that... optional properties are weird. (The value `{a: 1}` is assignable to type `{}` but not to type `{a?: boolean}`, so it's odd that `{} extends {a?: boolean}` is seen as true.)
