### PR TITLE
When the exported symbol is merged symbol from declaration use that name

### LINKED ISSUE #27880: Assert getImportCompletionAction
From 3.1.3 (completionEntryDetails)
```
Error: Debug Failure. False expression.
    at Object.getImportCompletionAction (tsserver.js:107970:22)
    at getCompletionEntryCodeActionsAndSourceDisplay (tsserver.js:94059:33)
    at Object.getCompletionEntryDetails (tsserver.js:94009:30)
    at Object.getCompletionEntryDetails (tsserver.js:114823:35)
    at tsserver.js:122634:57
    at Object.mapDefined (tsserver.js:578:30)
    at IOSession.Session.getCompletionEntryDetails (tsserver.js:122632:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:121674:61)
    at tsserver.js:123086:88
    at IOSession.Session.executeWithRequestId (tsserver.js:123077:28)
    at IOSession.Session.executeCommand (tsserver.js:123086:33)
    at IOSession.Session.onMessage (tsserver.js:123106:35)
    at Interface.<anonymous> (tsserver.js:124369:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #27880

### CODE REVIEW

File: src/services/codefixes/importFixes.ts [hunk 1]
```diff
@@ -445,9 +445,12 @@ namespace ts.codefix {
             const aliased = checker.getImmediateAliasedSymbol(defaultExport);
             return aliased && getDefaultExportInfoWorker(aliased, Debug.assertDefined(aliased.parent), checker, compilerOptions);
         }
-        else {
-            return { symbolForMeaning: defaultExport, name: moduleSymbolToValidIdentifier(moduleSymbol, compilerOptions.target!) };
+
+        if (defaultExport.escapedName !== InternalSymbolName.Default &&
+            defaultExport.escapedName !== InternalSymbolName.ExportEquals) {
```
Comment (weswigham) [inline src/services/codefixes/importFixes.ts]: I'd also check that that name `isIdentifierText`, just in case the name comes from, say, a jsdoc typedef or a js property assignment where the original declaration's name wasn't an identifier.

Comment (sheetalkamat) [reply src/services/codefixes/importFixes.ts]: @weswigham we don't need to check that since this is the name just to compare the defaultExportSymbol ==== symbol we are looking for and that symbol's name does default to symbol.name if its not `export=` or `default`. The actual text to be displayed is calculated later.
