### PR TITLE
add quick fix for add missing enum member

### LINKED ISSUE #25129: Allow "Declare property" quick fix for enums
_From @gbbarroso on June 21, 2018 1:29_

The same way there's a "declare property" suggestion for classes when you use quick fix, there should be one for enums as well. Often you just want to create a new constant for an existing enum and you don't even care about the order / value, having this quick fix would save a trip back to the file containing the enum declaration.

To be clear, that's what I'm talking about:

image

_Copied from original issue: Microsoft/vscode#52528_

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #25129

### CODE REVIEW

File: src/services/codefixes/fixAddMissingEnumMember.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
+/* @internal */
+namespace ts.codefix {
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingEnumMember.ts]: i would merge this with `fixAddMissingMember.ts` do not see why we need to separate code fixes here.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 2]
```diff
@@ -62,15 +79,21 @@ namespace ts.codefix {
...
-        const call = tryCast(parent.parent, isCallExpression);
-
-        return { token, classDeclaration, makeStatic, classDeclarationSourceFile, inJs, call };
+        const classDeclaration = find(symbol.declarations, isClassLike);
+        if (classDeclaration) {
+            const makeStatic = (leftExpressionType as TypeReference).target !== checker.getDeclaredTypeOfSymbol(symbol);
+            const classDeclarationSourceFile = classDeclaration.getSourceFile();
+            const inJs = isSourceFileJavaScript(classDeclarationSourceFile);
+            const call = tryCast(parent.parent, isCallExpression);
+            return { token, declaration: classDeclaration, makeStatic, classDeclarationSourceFile, inJs, call };
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: consider adding a discriminant here, e.g. `kind: "enum"` vs `kind: "class"`. this way you can skip the function `isEnumInfo`.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 3]
```diff
@@ -62,15 +79,21 @@ namespace ts.codefix {
...
+        }
+        const enumDeclaration = find(symbol.declarations, isEnumDeclaration);
+        if (enumDeclaration) {
+            return { token, declaration: enumDeclaration, enumDeclarationSourceFile: enumDeclaration.getSourceFile() };
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: why do you need the sourceFile? you can get that from the declaration easily.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 4]
```diff
@@ -188,6 +211,16 @@ namespace ts.codefix {
         return createCodeFixAction(fixName, changes, [makeStatic ? Diagnostics.Declare_static_method_0 : Diagnostics.Declare_method_0, token.text], fixId, Diagnostics.Add_all_missing_members);
     }
 
+    function getActionForEnumMemberDeclaration(
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: consider inlining this function in getCodeActions

File: src/services/codefixes/fixAddMissingMember.ts [hunk 5]
```diff
@@ -209,4 +242,32 @@ namespace ts.codefix {
...
+        if (firstMember && firstMember.initializer) {
+            const memberType = checker.getTypeAtLocation(firstMember.initializer);
+            if (memberType && memberType.flags & TypeFlags.StringLike) {
+                enumMemberInitializer = createStringLiteral(token.text);
+            }
+        }
+        return createEnumMember(token, enumMemberInitializer);
+    }
+
+    function addEnumMemberDeclaration(changes: textChanges.ChangeTracker, checker: TypeChecker, token: Identifier, enumDeclaration: EnumDeclaration, file: SourceFile) {
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: consider merging these two functions

Comment (mhegazy) [reply src/services/codefixes/fixAddMissingMember.ts]: i mean addEnumMemberDeclaration and createEnumMemberFromEnumDeclaration

File: src/services/codefixes/fixAddMissingMember.ts [hunk 6]
```diff
@@ -209,4 +242,32 @@ namespace ts.codefix {
...
         }
     }
+
+    function createEnumMemberFromEnumDeclaration(checker: TypeChecker, token: Identifier, enumDeclaration: EnumDeclaration) {
+        /**
+         * create initializer only string enum.
+         * value of initializer is a string literal that equal to name of enum member.
+         * literal enum or empty enum will not create initializer.
+         */
+        const firstMember = firstOrUndefined(enumDeclaration.members);
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: this should be `some`, and not `first`. a literal enum can have both members, e.g.:

```ts
enum E { 
    a,
    b = 1,
    c = "ss"
}
```

**Comment by Kingwl** [comment]
```ts
enum E {
   a,
   b = 1,
   c = "123"
}
enum A {
   a = E.c    
}
enum B {
   b = A.a
}
B.c

```
could we have some way to handle this case?

**Comment by mhegazy** [comment]
I do not think we will be able to get them all..  so for that one, my gut reaction is to make it `c`, and let the user handle the error.  another alternative is not to provide the quick fix.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 7]
```diff
@@ -23,31 +29,41 @@ namespace ts.codefix {
             const seenNames = createMap<true>();
             return codeFixAll(context, errorCodes, (changes, diag) => {
                 const { program, preferences } = context;
-                const info = getInfo(diag.file, diag.start, program.getTypeChecker());
-                if (!info) return;
-                const { classDeclaration, classDeclarationSourceFile, inJs, makeStatic, token, call } = info;
-                if (!addToSeen(seenNames, token.text)) {
+                const checker = program.getTypeChecker();
+                const info = getInfo(diag.file, diag.start, checker);
+                if (!info || !addToSeen(seenNames, info.token.text)) {
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: So... this is not really caused by your change, but was already there, but i think this is wrong.. the key to addToSeen should not be the name of the property, but rather the the pair [container symbol, property Name]. e.g. today this fails:

```ts
class C {
    method() { 
        this.a = 0;
    }
}


class D {
    method() {
        this.a = 0;
    } 
}   
```

it gets a bit more involved if one of the two classes inherit from each other.

Comment (mhegazy) [reply src/services/codefixes/fixAddMissingMember.ts]: I think we can handle that in a different change since it was not introduced by your change.

File: src/services/codefixes/fixAddMissingMember.ts [hunk 8]
```diff
@@ -209,4 +231,25 @@ namespace ts.codefix {
...
+
+    function addEnumMemberDeclaration(changes: textChanges.ChangeTracker, checker: TypeChecker, token: Identifier, enumDeclaration: EnumDeclaration) {
+        /**
+         * create initializer only literal enum that has string initializer.
+         * value of initializer is a string literal that equal to name of enum member.
+         * numeric enum or empty enum will not create initializer.
+         */
+        const hasStringInitializer = some(enumDeclaration.members, member => {
+            const type = checker.getTypeAtLocation(member);
+            return !!(type && type.flags & (TypeFlags.StringLike | TypeFlags.Enum));
```
Comment (mhegazy) [inline src/services/codefixes/fixAddMissingMember.ts]: i would just check for `stringLike` here, and not enum. it can be both string or number, and since we are not handling numbers, i would leave that part off.
