### PR TITLE
Fix conditional type resolution

### LINKED ISSUE #23843: Bug with conditional types and constraints
```ts
type Weird = (<U extends boolean>(a: U) => never) extends 
    (<U extends true>(a: U) => never) ? never : never;
```

This type puts the type checker in some sort of weird state where it's never narrowed into anything useful. I assume the proper type should be ~~`boolean`~~ `never`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR improves our logic for determining when to resolve conditional types. We previously used a special "definitely assignable" relation which ignored type parameter constraints, but that didn't correctly distinguish between type parameters referenced in the conditional type vs. type parameters local to contained members such as generic methods. The PR gets rid of this special relation and instead uses the regular assignable relation on a special restrictive form of each type parameter that has no constraint. Now, for a conditional type `T extends U ? X : Y`, the algorithm we use to determine whether to defer resolution of a conditional type is:

* we resolve to `Y` when `T` is not assignable to `U` _considering all type parameters referenced in `T` and `U` related_ (i.e. `T` is definitely not assignable to `U`),
* otherwise we resolve to `X` when `T` is assignable to `U` _considering all type parameters referenced in `T` and `U` unrelated_ (i.e. `T` is definitely assignable to `U`),
* otherwise we defer resolution.

Fixes #23843.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7413,7 +7409,7 @@ namespace ts {
             if (type.root.isDistributive) {
                 const simplified = getSimplifiedType(type.checkType);
                 const constraint = simplified === type.checkType ? getConstraintOfType(simplified) : simplified;
-                if (constraint) {
+                if (constraint && constraint !== type.checkType) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This particular change fixes an issue where a circularity resulted from the constraint of a conditional type being the conditional type itself. This can happen when a distributive conditional type is applied to an intersection of mapped types. The issue was uncovered because we now correctly defer resolution of conditional types involving generic mapped types.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9971,7 +9967,7 @@ namespace ts {
             if (checkType === wildcardType || extendsType === wildcardType) {
                 return wildcardType;
             }
-            const checkTypeInstantiable = maybeTypeOfKind(checkType, TypeFlags.Instantiable);
+            const checkTypeInstantiable = maybeTypeOfKind(checkType, TypeFlags.Instantiable | TypeFlags.GenericMappedType);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: We previously didn't defer resolution when the check or extends type was a generic mapped type. That definitely was not correct.

**Comment by weswigham** [comment]
@typescript-bot test this ❤️

File: src/compiler/types.ts [hunk 3]
```diff
@@ -3916,7 +3916,9 @@ namespace ts {
         aliasTypeArguments?: ReadonlyArray<Type>;     // Alias type arguments (if any)
         /* @internal */ aliasTypeArgumentsContainsMarker?: boolean;   // Alias type arguments (if any)
         /* @internal */
-        wildcardInstantiation?: Type;    // Instantiation with type parameters mapped to wildcard type
+        permissiveInstantiation?: Type;  // Instantiation with type parameters mapped to wildcard type
+        /* @internal */
+        restrictiveInstantiation?: Type; // Instantiation with type parameters mapped to unconstrained form
```
Comment (weswigham) [inline src/compiler/types.ts]: Should `permissiveInstantiation`s and `restrictiveInstantiation`s have pointers back to the original type, this way when we attempt to get them, if we already have one of them we can avoid bothering instantiating a new type (and often creating a new type identity)?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -10611,13 +10608,20 @@ namespace ts {
             return t => t === source ? target : baseMapper(t);
         }
 
-        function wildcardMapper(type: Type) {
+        function permissiveMapper(type: Type) {
             return type.flags & TypeFlags.TypeParameter ? wildcardType : type;
         }
 
+        function getRestrictiveTypeParameter(tp: TypeParameter) {
+            return !tp.constraint ? tp : tp.restrictiveInstantiation || (tp.restrictiveInstantiation = createTypeParameter(tp.symbol));
```
Comment (weswigham) [inline src/compiler/checker.ts]: This should be
```ts

        function getRestrictiveTypeParameter(tp: TypeParameter) {
            return tp.constraint === noConstraintType ? tp : tp.restrictiveInstantiation || (
                tp.restrictiveInstantiation = createTypeParameter(tp.symbol),
                (tp.restrictiveInstantiation as TypeParameter).constraint = noConstraintType,
                tp.restrictiveInstantiation
            );
        }
```
to align with the original intent - as is, since `constraint` is a lazily calculated field (and is calculated from the symbol), all this is doing right now is cloning the type parameter (constraint and all!) if it's constraint has been calculated already, or returning it as-is if it hasn't been calculated yet.

Fixing this, however, is not without warts. For example, take this type:
```ts
type IsDefinitelyDefined<T extends unknown> = [T] extends [{}] ? true : false;
```
when compared with an "unconstrained" `T` it's always _true_, but the `unknown` constraint makes it `false`. Maybe that's a good indicator that the constraint should be set as `unknownType` instead of `noConstraintType`?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: Agreed. The restrictive instantiation should be a type parameter with an `unknown` constraint.
