### PR TITLE
Don't capture type parameters defined inside the extraction range with "Extract to function"

### LINKED ISSUE #51827: "Extract to function" refactoring triggers an assertion failure
```ts
export function f() {
    let g = [|<B>(x: B) => x|];
    return g;
}
```

Run some sort of extract function on that range. It'll crash with:

```
Debug Failure. Did not expect FunctionDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (tsserverlibrary.js:168341:30)
    at createSyntaxList (tsserverlibrary.js:168357:13)
    at processNodes (tsserverlibrary.js:168320:27)
    at visitNodes (tsserverlibrary.js:31219:24)
    at forEachChildInFunctionDeclaration (tsserverlibrary.js:31404:17)
    at forEachChild (tsserverlibrary.js:31997:47)
    at NodeObject.forEachChild (tsserverlibrary.js:168295:23)
    at createChildren (tsserverlibrary.js:168329:14)
    at NodeObject.getChildren (tsserverlibrary.js:168272:56)
    at find (tsserverlibrary.js:130979:30)
```

Found from [this code in storybook](https://github.com/storybookjs/storybook/blob/ee0d2a128243974c95a821e6e4ae2618bc075d09/code/lib/core-common/src/utils/satisfies.ts):

```ts
export function satisfies<A>() {
  return <T extends A>(x: T) => x;
}
```

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #51827

### CODE REVIEW

File: src/services/refactors/extractSymbol.ts [hunk 1]
```diff
@@ -1547,13 +1548,13 @@ function getContainingVariableDeclarationIfInList(node: Node, scope: Scope) {
     }
 }
 
-function getFirstDeclaration(type: Type): Declaration | undefined {
+function getFirstDeclarationBeforePosition(type: Type, position: number): Declaration | undefined {
```
Comment (DanielRosenwasser) [inline src/services/refactors/extractSymbol.ts:1551]: What exactly was the problem? What is the thing that was captured before a specific position?

Comment (MariaSolOs) [reply src/services/refactors/extractSymbol.ts:1551]: The problem was that type variables declared inside the extraction range where used in the type parameter list of the new function, which isn't needed because the types will be declared in the function's body instead. So with this change I'm only including the type parameters in scope that are declared before the extraction's range.

As for the respective [crash](https://github.com/microsoft/tsserverfuzzer/issues/433), I'm not too sure. I debugged this a bit with @sandersn a few weeks ago and we suspect that there's an issue with the printer inserting trivia nodes in the incorrect places.

Comment (DanielRosenwasser) [reply src/services/refactors/extractSymbol.ts:1551]: *Okay*, so this is a really just a proxy/hack for saying "get me the free (captured) type variables" - because any captured/outer type parameter must occur strictly before the function itself.

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/refactors/extractSymbol.ts (hunk 1 above)
Comment (MariaSolOs) [reply src/services/refactors/extractSymbol.ts:1551]: Exactly.
