### PR TITLE
Fix `signatureToSignatureDeclarationHelper` wrt `SuppressAnyReturnType`

### LINKED ISSUE #35508: Implement interface drops any return type of callback
From https://github.com/microsoft/vscode/issues/85949

**TypeScript Version:** 3.8.0-dev.20191203

**Search Terms:**

**Code**
For the TS:

```ts
interface IFoo {
  parse(reviver: () => any): void;
}

class Foo implements IFoo {

}
```

1. Run implement interface on `Foo`

**Expected behavior:**

```ts
interface IFoo {
  parse(reviver: () => any): void;
}

class Foo implements IFoo {
  parse(reviver: () => any): void {
    throw new Error('Method not implemented.');
  }

}
```

**Actual behavior:**
`any` on return type of callback dropped:

```ts
interface IFoo {
  parse(reviver: () => any): void;
}

class Foo implements IFoo {
  parse(reviver: () => ): void {
    throw new Error('Method not implemented.');
  }

}
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by elibarzilay**
Fix `signatureToSignatureDeclarationHelper`: make `SuppressAnyReturnType` applicable only at the type's toplevel.

Fixes #35508.

### CODE REVIEW

**Comment by elibarzilay** [comment]
Two things that I'm not sure about:
1. Maybe there are other function-like `kind`s that should be included?  (Or maybe use some helper like `isFunctionLikeKind`)
2. Just after the change there is `else if (!returnTypeNode) {` -- the `else` looks fishy.

**Comment by elibarzilay** [comment]
To answer myself: need constructors too (+ add another test).

**Comment by elibarzilay** [comment]
I first fixed the previous commit with constructor types too, then removed the whole thing in a separate commit.

File: tests/cases/fourslash/codeFixClassImplementInterfaceMultipleMembersAndPunctuation.ts [hunk 1]
```diff
@@ -27,13 +27,13 @@ class C1 implements I1 {
...
-    f() {
+    f(): number {
         throw new Error("Method not implemented.");
     }
-    g() {
+    g(): any {
         throw new Error("Method not implemented.");
     }
-    h() {
+    h(): any {
```
Comment (RyanCavanaugh) [inline tests/cases/fourslash/codeFixClassImplementInterfaceMultipleMembersAndPunctuation.ts]: This isn't a desirable side effect of the fix. We should still be having these unannotated (by moving the logic to `undefined`-out the return type of the method node to the calling code in the refactor)

Comment (elibarzilay) [reply tests/cases/fourslash/codeFixClassImplementInterfaceMultipleMembersAndPunctuation.ts]: Resurrected `SuppressAnyReturnType` and made it used only at the toplevel.
