### PR TITLE
Avoid emitting temp variable in downleveled import()

### LINKED ISSUE #51554: 4.9.3 commonjs output regression: Dynamical path import()s inside sync for-of are all called with the same parameter
# Bug Report

### 🔎 Search Terms

4.9, compiler regression, for-of, import(), commonJS

### 🕗 Version & Regression Information

Works fine in 4.8.4 & 4.9.1-beta.
First saw this in the 4.9.2-rc & 4.9.3 and still exists in the current nightly 5.0.0-dev.20221116.

Please keep and fill in the line that best applies:
-->
- This changed between versions 4.9.1-beta and 4.9.2-rc

### ⏯ Playground Link

[v4.9.3 commonjs output with the issue](https://www.typescriptlang.org/play?target=9&jsx=0&module=1&ts=4.9.3#code/GYewTgBAFAxiB2BnALhYBLANgUwiYEA2gIwA0ATKQMwC6AlBAN4BQAkOgLYAO4yUABgDoA9ABJGGHAF9BAK0QJ+dANzMpQA)

[Properly working v4.8.4 commonjs output](https://www.typescriptlang.org/play?target=9&jsx=0&module=1&ts=4.8.4#code/GYewTgBAFAxiB2BnALhYBLANgUwiYEA2gIwA0ATKQMwC6AlBAN4BQAkOgLYAO4yUABgDoA9ABJGGHAF9BAK0QJ+dANzMpQA)

### 💻 Code

Compiling the following while targeting es2022 w/ commonjs output.

```js
for (const file of [1,2,3]) {
	import(`./${file}.json`);
}
```
PS: The actual code I'm using is storing the resulting promises, but didn't include it in the minimum reproduction code since it didn't make any difference.

### 🙁 Actual behavior

It imports file `3.json` three times, b/c of a new `var a_` outside the for-of scope is created and re-used across iterations.
```
var _a; // <-- was not emitted before 4.9.2-rc
for (const model of [1, 2, 3]) {
    _a = `./${model}.json`, Promise.resolve().then(() => __importStar(require(_a)));
}
```

### 🙂 Expected behavior

It should import files 1.json, 2.json & 3.json, just like up to 4.9.1-beta.

### PR DESCRIPTION
**Pull request by Josh-Cena**
Fixes #51554

### CODE REVIEW

File: tests/baselines/reference/importCallExpressionReturnPromiseOfAny.js [hunk 1]
```diff
@@ -42,23 +42,21 @@ class C {
...
 let j;
-var p3 = (_g = j = getSpecifier(), Promise.resolve().then(() => require(_g)));
+var p3 = Promise.resolve(`${j = getSpecifier()}`).then(s => require(s));
 function* loadModule(directories) {
-    var _a;
     for (const directory of directories) {
         const path = `${directory}\\moduleFile`;
-        _a = yield path, Promise.resolve().then(() => require(_a));
+        Promise.resolve(`${yield path}`).then(s => require(s));
     }
```
Comment (Josh-Cena) [inline tests/baselines/reference/importCallExpressionReturnPromiseOfAny.js:61]: The previous behavior here looked exactly like the bug because they would all import the same thing...

**Review by rbuckton — APPROVED** [review]
