### PR TITLE
fix(33286): Code folding fail for arrow function when param list has no parentheses

### LINKED ISSUE #33286: Code folding fail for arrow function when param list has no parentheses
**TypeScript Version:** ???

**VS Code version**: Code - OSS 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-05T13:09:16.557Z)

**OS version**: Linux x64 5.2.8-arch1-1-ARCH

**Search Terms:**
code fold
folding
arrow function
parenthesis

**Code**

```js
// expected
// curly block is foldable
testThing(
  (a) => {

  }
)

// unexpected
// curly block is **not** foldable 
testThing(
  a => {

  }
)
```

**Expected behavior:**
vscode let me fold the arrow function body.

**Actual behavior:**
It does not.

**Playground Link:**
Not applicable.

**Related Issues:** 
no

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #33286

### CODE REVIEW

File: tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+/// <reference path="fourslash.ts"/>
+
+////declare function foo(props: any);
+////foo(
+////    (a, b, c) =>[| {
```
Comment (sandersn) [inline tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts:5]: Do we already have tests for the multiline parameter list case, like

```ts
(a,
 b,
 c) => { }
```

Comment (sandersn) [reply tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts:5]: And I'm not sure whether folding should produce a span for `(a,b,c)` or not. Probably yes?

Comment (a-tarasyuk) [reply tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts:5]: > And I'm not sure whether folding should produce a span for (a,b,c) or not

If we are talking about the following example, I think no, because the parameter list is located on the same line 
```ts
(a, b, c) => {
}
```

However, if each parameter is located on a new line, I think it is useful to have folding. 

```ts
(a,
 b,
 c) => { }
```

> Do we already have tests for the multiline parameter list case, like

I couldn't find tests for this case, and it seems that it is not supported, only `{}` handled.

Comment (a-tarasyuk) [reply tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts]: I added additional tests. For the following case, _folding_ will be like this

```
[|(a,
 b,
 c) => { 
}|]
```
not 

```
[|(a,
 b,
 c)|] => [|{ 
}|]
```

There is no support _folding_ for parameter list., I'm not sure, maybe it because `) {` can be on the same line and as a result, it will not work correctly. Anyway, it seems better to create a new _feature_ issue and discuss that case there. @sandersn What do you think?

Comment (sandersn) [reply tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts]: That sounds like a god plan to me. Thanks for the additional analysis.

Comment (a-tarasyuk) [reply tests/cases/fourslash/getOutliningForArrowFunctionBody3.ts]: @sandersn thanks.
