### PR TITLE
Object spread

### LINKED ISSUE #2103: Support proposed ES Rest/Spread properties
es7 proposal : https://github.com/sebmarkbage/ecmascript-rest-spread
### Typing

In my opinion the goal of this method is to be able to duplicate an object and changing some props, so I think it's particularly important in this case to not check duplicate property declaration : 

``` typescript
var obj = { x: 1, y: 2};
var obj1 = {...obj, z: 3, y: 4}; // not an error
```

I have a very naive [type check algorithm](https://github.com/fdecampredon/jsx-typescript/blob/3c692cbb80622b74d1b308b3c5dcab6b993b4111/src/compiler/checker.ts#L5665-L5671) for a similar feature (`JSXSpreadAttribute`) in my little `jsx-typescript` fork: I just copy the properties of the _spread object_ in the properties table when I encounter a spread object, and override those property if I encounter a declaration with a similar name.
### Emitting

[jstransform](https://github.com/facebook/jstransform/) use `Object.assign`, [babel](https://babeljs.io/) introduce a shim: 

``` javascript
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
```

We could either force the presence of `assign` function on `ObjectConstructor` interface, or provide a similar function (with a different name).

I think that the optimal solution would be to not emit any helper in `es6` target (or if `Object.assign` is defined), and to emit an helper function for `es5`, `es3`.

``` javascript
var obj = { x: 1, y: 2};
var obj1 = {...obj, z: 3};

/// ES6 emit
var obj = {x: 1, y: 2};
var obj1= Object.assign({}, obj, { z: 3 });

//ES3 emit
var __assign = function (target) { 
    for (var i = 1; i < arguments.length; i++) { 
        var source = arguments[i]; 
        for (var key in source) { 
            if (Object.prototype.hasOwnProperty.call(source, key)) { 
                target[key] = source[key];
            } 
        } 
    } 
    return target; 
};

var obj = {x: 1, y: 2};
var obj1= __assign({}, obj, { z: 3 });
```
### Typing

For simple object the new type is a subtype of the assignation that does not contains properties that has been captured before the rest properties : 

``` typescript
var obj = {x:1, y: 1, z: 1};
var {z, ...obj1} = obj;
obj1// {x: number; y:number};
```

If the destructuring assignment has an index declaration, the result has also a similar index declaration: 

``` typescript
var obj: { [string: string]: string };
var {[excludedId], ...obj1} = obj;
obj1// { [string: string]: string };
```

new/call declarations are obviously not captured:

``` typescript
var obj: { (): void; property: string};
var { ...obj1} = obj;
obj1// { property: string };
```
### Emitting

It is not possible to emit _rest properties_ without an helper function, this one is from babel: 

``` typescript
var obj = {x:1, y: 1, z: 1};
var {z, ...obj1} = obj;
```

``` javascript
var __objectWithoutProperties = function(obj, keys) {
    var target = {};
    for (var i in obj) {
        if (keys.indexOf(i) >= 0) continue;
        if (!Object.prototype.hasOwnProperty.call(obj, i)) continue;
        target[i] = obj[i];
    }
    return target;
};

var obj = {x:1, y: 1, z: 1};
var z = obj.z;
var obj1 = __objectWithoutProperties(obj, ["z"]);
```

_Edit: added some little typing/emitting example_

### LINKED ISSUE #10727: Add spread/rest types to support proposed object spread/rest
The spread type is a new type operator that types the proposed (TS39 stage 2) object spread operator. Its counterpart, the subtraction type, will type the proposed object rest destructuring operator. The spread type `{ ...A, ...B }` combines the own, enumerable properties of entities A and B.

Unlike most type operators, spread is n-ary, not unary like `typeof` or binary like `&`. It takes one or many arguments.

Object rest and spread is experimental and will be available behind the flag `--experimentalObjectSpreadRest`. Work is happening at [the branch object-rest-spread-WIP](https://github.com/Microsoft/TypeScript/compare/master...object-rest-spread-WIP).

The meat of the definition is in the [Properties and Index Signatures](#properties-and-index-signatures) section. In the interests of brevity I only show the two-spread definition and the one-spread definition if it is interestingly different. Definitions for larger numbers of spreads can be derived easily.

## Non-spread elements

Non-spread elements can be treated as spread elements by grouping adjacent non-spread elements into a object literal and then spreading it. Like so:

```ts
{ ...a, b, c, ...d, e }
=>
{ ...a, ...{ b, c }, ...d, ...{ e } }
```

## Type Relationships

 * Identity: `{ ...A }` is equivalent to the *enumerable* and *own* properties of `A`. `{ ...A}` is equivalent to `{ ...A, ...A }` and `{ ...A, ...A, ...A }` and so on. 
 * Commutativity: `{ ...A, ...B }` is *not* equivalent to `{ ...B, ...A}`. Properties of `B` overwrite properties of `A` with the same name.
 * Associativity: `{ ...{ ...A, ...B }, ...C}` is equivalent to `{ ...A, { ...B, ...C } }`.
 * Supertype reconstruction: `{ ...A, ...B }` is equivalent to the enumerable properties of `A` if `B` is a supertype of `A`.

Note that methods are not enumerable, so the most noticeable effect of spreading a class instance is that the resulting object is missing all the original's methods.

## Assignment compatibility

 * `{ ...A, ...B }` is assignable to `X` if the properties and index signatures of `{ ...A, ...B }` are assignable to those of `X`, and `X` has no call or construct signatures.
 * `X` is assignable to `{ ...A, ...B }` if the properties and index signatures of `X` are assignable to those of `{ ...A, ...B }`.

## Properties and index signatures

The type `{ ...A }` has a property `P` if `A` has an own, enumerable property `P`. `{ ...A }.P` has the same type as `A.P`.

The type `{ ...A, ...B }` has a property `P` if `A` has an own, enumerable property `P` or `B` has an own, enumerable property `P`. In this case `{ ...A, ...B }.P` has the type 
 1. of `A.P` if `B` does not have an own, enumerable property `P`.
 2. Of `B.P` if `A` does not have an own enumerable property `P`.
 3. Of `B.P` if `B` has an own enumerable property `P` that is not optional.
 4. Of `A.P | B.P` if `B.P` is optional (and own enumerable). 

For larger numbers of spreads, we can extend rules (1) &ndash; (4) of the binary case:

The type `{ ...A, ...B, ...C }` has a property `P` if any of the spreads have a property `P`. The type of this property is the type of the first non-optional `P` in some spread *S*, looking from the end of the spread list, unioned with all optional properties `P` in spreads that follow *S*.

Index signatures spread the same way as properties. 

## Call and Constructor signatures

`{ ...A, ...B }` has no call signatures and no construct signatures, since these are not own enumerable properties.

## Precedence

Precedence doesn't matter since the spread syntax has required boundaries -- braces -- that aren't ambiguous with anything else.

## Problems
 1. Exceptions interrupt the copying task. This means things of type `never` might change the type to never.

## Examples
Taken from the [TC39 proposal](https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Spread.md) and given types.

### Shallow Clone (excluding prototype)

```ts
let aClone: { ...A } = { ...a };
```

### Merging Two Objects

```ts
let ab: { ...A, ...B } = { ...a, ...b };
```

### Overriding Properties

```ts
let aWithOverrides: { ...A, x: number, y: number } = { ...a, x: 1, y: 2 };
// equivalent to
let aWithOverrides: { ...A, ...{ x: number, y: number } } = { ...a, ...{ x: 1, y: 2 } };
```

### Default Properties

```ts
let aWithDefaults: { x: number, y: number, ...A } = { x: 1, y: 2, ...a };
```

### Multiple Merges

```ts
// Note: getters on a are executed twice
let xyWithAandB: { x: number, ...A, y: number, ...B, ...A } = { x: 1, ...a, y: 2, ...b, ...a };
// equivalent to
let xyWithAandB: { x: number, y: number, ...B, ...A } = { x: 1, ...a, y: 2, ...b, ...a };
```

### Getters on the Object Initializer

```ts
// Does not throw because .x isn't evaluated yet. It's defined.
let aWithXGetter: { ...A, x: never } = { ...a, get x() { throw new Error('not thrown yet') } };
```

### Getters in the Spread Object

```ts
// Throws because the .x property of the inner object is evaluated when the
// property value is copied over to the surrounding object initializer.
let runtimeError: { ...A, x: never } = { ...a, ...{ get x() { throw new Error('thrown now') } } };
```

### Setters Are Not Executed When They're Redefined

```ts
let z: { x: number } = { set x() { throw new Error(); }, ...{ x: 1 } }; // No error
```

### Null/Undefined Are Ignored

```ts
let emptyObject: {} = { ...null, ...undefined }; // no runtime error
```

### Updating Deep Immutable Object

```ts
let newVersion: { ...A, name: string, address: { address, zipCode: string }, items: { title: string }[] } = {
  ...previousVersion,
  name: 'New Name', // Override the name property
  address: { ...previousVersion.address, zipCode: '99999' } // Update nested zip code
  items: [...previousVersion.items, { title: 'New Item' }] // Add an item to the list of items
};
```

Note: If `A = { name: string, address: { address, zipCode: string }, items: { title: string }[] }`, then the type of newVersion is equivalent to `A`

# Subtraction types

The subtraction type is the opposite of the spread type. It types the proposed (TC39 stage 2) object-rest destructuring operator, along with similar type-shrinking operations.  The subtraction type `A - B` represents all of the enumerable, own properties of A that do not occur in B. 

Unlike the spread type, but like most other type operators, the subtraction type is binary. That's because the rest syntax only supports subtraction from a single object at a time. 

A short example illustrates the way this type is used:

```ts
/** JavaScript version */
function removeX(o) {
  let { x, ...rest } = o;
  return rest;
}

/** Typescript version */
function removeX<T extends { x: number, y: number }>(o: T) {
  let { x, ...rest }: T - { x: number } = o;
  return rest;
}
```

## Problems

The subtraction type proposal is not finished. It outlines subtraction types but they are not really a good fit for object rest destructuring.

 1. Subtraction types are not limited to own, enumerable properties. There are plenty of use cases besides object rest destructuring that do not need this limitation.
 2. Subtraction types are more generic than object rest destructuring needs in any case. For object rest, the right-hand-side of the subtraction type will always be a concrete type, never a type variable. That's because you have to subtract specific properties in the object rest destructuring syntax: in `{ x, y, z, ...rest}`, only `rest` can have a generic type. `{ x, y, z }` must be enumerated.
On the other hand, a separate rest type would still be very similar to a subtraction type. The difference is not observable in many uses. This is just like the difference between intersection types and spread types, but it feels wrong to introduce the more specific type earlier since people will try to use it more generally.

Perhaps the right answer is to introduce both types at once. Or introduce just subtraction types and find a way to adapt them to object rest destructuring.

## Type Relationships

 * Identity: `A - {}` is equivalent to the own, enumerable properties of `A`. However, `A - A` is always equivalent to `{}`.
 * Commutativity: `A - B` is *not* equivalent to `B - A`. The first removes own, enumerable properties of `A` and the second removes own, enumerable properties of `B`.
 * Associativity: `(A - B) - C` is *not* equivalent to `A - (B - C)`. (Consider the example where A, B, and C are all `{ x }`.)

## Assignment compatibility

 * `A - B` is assignable to `X` if the properties and index signatures of `A - B` are assignable to those of `X`, and `X` has no call or construct signatures.*
 * `X` is assignable to `A - B` if the properties and index signatures of `X` are assignable to those of `A - B`.

## Properties and index signatures

The type `A - B` has a property `P` if `A` has an own, enumerable property `P` and `B` does not have an own, enumerable property `P`. In this case `A - B.P` has the type of `A.P`.

## Call and Constructor signatures

`A - B` has no call signatures and no construct signatures. Since these are not own enumerable properties.

## Precedence

Subtraction types have similar precedence to `-` in the expression grammar, particularly compared to `&` and `|`. TODO: Find out what this precedence is.

### PR DESCRIPTION
**Pull request by sandersn**
Leaves #10727 still open
Fixes #2103
Leaves #11100 still open

## Important Update ##

The PR no longer contains a spread *type*, only spread *syntax*, which creates object types. I expect a spread type or something similar to be available in future versions of TypeScript.

### Updates to proposed semantics: type variable assignability

A spread type containing spread elements whose types are type variables is assignable to another spread type also containing type variables if the non-type-variable properties and index signatures are assignable as above and the the type variables are the same variables in the same order. 

For example: `{ a: number, ...T, b: number, ...U, ...x }` is assignable to `{ b: number, a: number, ...x ...T, ...U}` and vice versa. But the similar `{ a: number, ...T, b: number, ...U, ...x }` is not assignable to `{ b: number, a: number, ...x ...U, ...T}` because the order of `T` and `U` is reversed.

This rule is not strictly safe, since a type parameter could override any properties that precede it (see the rule for `private` below), but it would be odd if `{ ...T, ...U }` were not assignable to `{ ...T, ...U }`. Instead, this rule assumes that the contents of a type variable will not conflict with other properties.
### Important Implementation Details

Spread types use a binary representation to make recursive transformations easier. This matches the proposal but the syntax remains close to spread's expression syntax.

`getSpreadType` creates a spread only if the spread type contains a type parameter. Otherwise it will create an anonymous type, or union or intersection of anonymous types. The binary structure is left deep, so the left side of a spread type is either another spread (the recursive case) or an object type (the terminal case). The right side of spread type is either a type parameter or an object type. Adjacent object types are spread into a single object type, so the structure will never have two adjacent object types, only adjacent type parameters.
### Updated proposal

The spread part of #10727's updated proposal follows for convenience:

The spread type is a new type operator that types the [TC39 stage 3 object spread operator](https://github.com/sebmarkbage/ecmascript-rest-spread). Its counterpart, the difference type, will type the proposed object rest destructuring operator. The spread type `{ ...A, ...B }` combines the properties, but not the call or construct signatures, of entities A and B.

The original issue for spread/rest types is #2103. Note that this proposal deviates from the specification by keeping all properties except methods, not just own enumerable ones.
## Proposal syntax

The type syntax in this proposal differs from the type syntax as implemented in order to treat spread as a binary operator. Three rules are needed to convert the `{ ...spread }` syntax to binary syntax `spread1 ... spread2`.
1. `{ ...spread }` becomes `{} ... spread`.
2. `{ a, b, c, ...d}` becomes `{a, b, c} ... d`
3. Multiple spreads inside an object literal are treated as sequences of binary spreads: `{ a, b, c, ...d, ...e, f, g}` becomes `{a, b, c} ... d ... e ... { f, g }`.
## Type Relationships
- Identity: `{} ... A` is equivalent to the properties of `A`. `A ... A ... A` is equivalent to `A ... A` and `A ... A` is equivalent to `{} ... A`.
- Commutativity: `A ... B` is _not_ equivalent to `B ... A`. Properties of `B` overwrite properties of `A` with the same name.
- Associativity: `(A ... B) ... C` is equivalent to `A ... (B ... C)`. `...` is right-associative.
- Distributivity: Spread is distribute over both `|` and `&`, so `A ... (B | C)` is equivalent to `A ... B | A ... C` and `A ... (B & C)` is equivalent to `A ... B & A ... C`.
## Assignment compatibility
- `A ... B` is assignable to `X` if the properties and index signatures of `A ... B` are assignable to those of `X`, and `X` has no call or construct signatures.
- `X` is assignable to `A ... B` if the properties and index signatures of `X` are assignable to those of `A ... B`.
### Type variables

A spread type containing type parameters is assignable to another spread type if the the non-type-variable properties and index signatures are assignable as above and the type variables are the same variables in the same order. 

For example: `{ a: number, b: number } ... T` is assignable to `{ a: number } ...T` and to `T ... { a: number }`. But the similar `T ... U` is not assignable to `U ... T` because the order of `T` and `U` is reversed.
### Type inference

Type inference is allowed between an object type source and a spread type target with a type parameter as either the left or right side. If the type parameter is on the right, then its inferred type is the whole source type. If the type parameter is on the left, then its inferred type is the source type minus properties on the right side of the spread.

For example, if the target is `T ... { a: number }` and the source is `{ a: number, b: string }`, the inferred type for `T` is `{ b: string }`. Because spread types remove call and construct signatures, if the source were `{ a: number, b: string, (): void }`, the type inferred for `T` would still be `{ b: string }`.
## Properties and index signatures

In the following definitions, 'property' means either a property or a get accessor.

The type `A ... B` has a property `P` if `A` has a property `P` or `B` has a property `P`. In this case `(A ... B).P` has the type 
1. Of `B.P` if `B.P` is not optional.
2. Of `A.P | B.P` if `B.P` is optional and `A` has a property `P`.
3. Of `A.P` otherwise.

Index signatures spread the same way as properties.

`private`, `protected` and `readonly` behave the same way as optionality except that if `A.P` or `B.P` is `private`, `protected` or `readonly`, then `(A ...B).P` is `private`, `protected` or `readonly`, respectively.
## Call and Construct signatures

`A ... B` has no call signatures and no construct signatures, since these are not properties.
## Precedence

Precedence of `...` is higher than `&` and `|`. Since the language syntax is that of object type literals, precedence doesn't matter since the braces act as boundaries of the spread type.
## Examples

Taken from the [TC39 proposal](https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Spread.md) and given types.
### Shallow Clone (excluding prototype)

``` ts
let aClone: { ...A } = { ...a };
```
### Merging Two Objects

``` ts
let ab: { ...A, ...B } = { ...a, ...b };
```
### Overriding Properties

``` ts
let aWithOverrides: { ...A, x: number, y: number } = { ...a, x: 1, y: 2 };
// equivalent to
let aWithOverrides: { ...A, ...{ x: number, y: number } } = { ...a, ...{ x: 1, y: 2 } };
```
### Default Properties

``` ts
let aWithDefaults: { x: number, y: number, ...A } = { x: 1, y: 2, ...a };
```
### Multiple Merges

``` ts
// Note: getters on a are executed twice
let xyWithAandB: { x: number, ...A, y: number, ...B, ...A } = { x: 1, ...a, y: 2, ...b, ...a };
// equivalent to
let xyWithAandB: { x: number, y: number, ...B, ...A } = { x: 1, ...a, y: 2, ...b, ...a };
```
### Getters on the Object Initializer

``` ts
// Does not throw because .x isn't evaluated yet. It's defined.
let aWithXGetter: { ...A, x: never } = { ...a, get x() { throw new Error('not thrown yet') } };
```
### Getters in the Spread Object

``` ts
// Throws because the .x property of the inner object is evaluated when the
// property value is copied over to the surrounding object initializer.
let runtimeError: { ...A, x: never } = { ...a, ...{ get x() { throw new Error('thrown now') } } };
```
### Setters Are Not Executed When They're Redefined

``` ts
let z: { x: number } = { set x() { throw new Error(); }, ...{ x: 1 } }; // No error
```
### Null/Undefined Are Ignored

``` ts
let emptyObject: {} = { ...null, ...undefined }; // no runtime error
```
### Updating Deep Immutable Object

``` ts
let newVersion: { ...A, name: string, address: { address, zipCode: string }, items: { title: string }[] } = {
  ...previousVersion,
  name: 'New Name', // Override the name property
  address: { ...previousVersion.address, zipCode: '99999' } // Update nested zip code
  items: [...previousVersion.items, { title: 'New Item' }] // Add an item to the list of items
};
```

Note: If `A = { name: string, address: { address, zipCode: string }, items: { title: string }[] }`, then the type of newVersion is equivalent to `A`

### CODE REVIEW

**Comment by sandersn** [comment]
@ahejlsberg can you take a look?

**Comment by DanielRosenwasser** [comment]
> Identity

Is `{ ...number }` equivalent to `number`? I don't think that it should be.

**Comment by sandersn** [comment]
What are the properties of number? I don't think there are any, so `{ ... number }` is equivalent to `{}`, which is the properties of number.

This is based on experimentation with V8's implementation of `Object.assign`, where `Object.assign({}, 12)` returns `{}`.

**Comment by DanielRosenwasser** [comment]
> What are the properties of number? I don't think there are any,

Well....

Usually when we think about the properties of `number`, we think of its apparent type `Number`. [In the spec](http://sebmarkbage.github.io/ecmascript-rest-spread/#AbstractOperations-CopyDataProperties), before getting the property keys, the [ToObject](https://tc39.github.io/ecma262/2016/#sec-toobject) function is used on whatever value you're spreading in. So there's precedent for the same analogue here: to get the properties of `number`, we get the properties of `Number`.

However, you're right that the "correct" behavior will give you no properties because none of the properties of `Number` are "owned" by any instance. So it would be "wrong" to give that to users, though I can't imagine who would ever do that anyway.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -4273,6 +4319,21 @@ namespace ts {
             setObjectTypeMembers(type, emptySymbols, callSignatures, constructSignatures, stringIndexInfo, numberIndexInfo);
         }
 
+        function resolveSpreadTypeMembers(type: SpreadType) {
+            // The members and properties collections are empty for spread types. To get all properties of an
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: an -> a

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Looks like this should be JSDoc.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4273,6 +4319,21 @@ namespace ts {
             setObjectTypeMembers(type, emptySymbols, callSignatures, constructSignatures, stringIndexInfo, numberIndexInfo);
         }
 
+        function resolveSpreadTypeMembers(type: SpreadType) {
+            // The members and properties collections are empty for spread types. To get all properties of an
+            // spread type use getPropertiesOfType.
+            let stringIndexInfo: IndexInfo = getIndexInfoOfSymbol(type.symbol, IndexKind.String);
+            let numberIndexInfo: IndexInfo = getIndexInfoOfSymbol(type.symbol, IndexKind.Number);
+            for (let i = type.types.length - 1; i > -1; i--) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `>= 0`?

File: src/compiler/types.ts [hunk 3]
```diff
@@ -2504,17 +2517,27 @@ namespace ts {
...
+
+    /* @internal */
+    export interface SpreadType extends TypeOperatorType {
+        types: SpreadElementType[];       // Constituent types
+    }
 
-    export interface IntersectionType extends UnionOrIntersectionType { }
+    /* @internal */
+    export interface SpreadElementType extends ResolvedType {
+        isDeclaredProperty?: boolean;
```
Comment (DanielRosenwasser) [inline src/compiler/types.ts]: Can you add documentation about what this means?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -5589,15 +5729,67 @@ namespace ts {
         function getTypeFromTypeLiteralOrFunctionOrConstructorTypeNode(node: Node, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
             const links = getNodeLinks(node);
             if (!links.resolvedType) {
-                // Deferred resolution of members is handled by resolveObjectTypeMembers
-                const type = createObjectType(TypeFlags.Anonymous, node.symbol);
+                const isSpread = (node.kind === SyntaxKind.TypeLiteral &&
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: `hasSpread`

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Is there an `isTypeLiteral` s that you don't have to subsequently cast?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -5589,15 +5729,67 @@ namespace ts {
         function getTypeFromTypeLiteralOrFunctionOrConstructorTypeNode(node: Node, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
             const links = getNodeLinks(node);
             if (!links.resolvedType) {
-                // Deferred resolution of members is handled by resolveObjectTypeMembers
-                const type = createObjectType(TypeFlags.Anonymous, node.symbol);
+                const isSpread = (node.kind === SyntaxKind.TypeLiteral &&
+                                  find((node as TypeLiteralNode).members, elt => elt.kind === SyntaxKind.SpreadTypeElement));
+                let type: ObjectType;
+                if (isSpread) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Consider refactoring the entire body here into its own function to keep it clean.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -5589,15 +5729,67 @@ namespace ts {
         function getTypeFromTypeLiteralOrFunctionOrConstructorTypeNode(node: Node, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
             const links = getNodeLinks(node);
             if (!links.resolvedType) {
-                // Deferred resolution of members is handled by resolveObjectTypeMembers
-                const type = createObjectType(TypeFlags.Anonymous, node.symbol);
+                const isSpread = (node.kind === SyntaxKind.TypeLiteral &&
+                                  find((node as TypeLiteralNode).members, elt => elt.kind === SyntaxKind.SpreadTypeElement));
+                let type: ObjectType;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You never use `type` in the first branch, so do you really need to declare it up here?

**Comment by sandersn** [comment]
I updated the PR substantially in the last few days. Here's an overview. (I'll add more detail tomorrow.)

1. Spread types now use a binary representation. This simplifies lots of necessary transformations (see (3) and (4)) and makes a canonical representation much easier too.
2. Spread types are only created if they contain type parameters. If not, `getSpreadType` just returns an anonymous type (or union/intersection of anonymous types, see (3)).
3. Spread types lift unions and intersections out of themselves during creation. So T ... (U | V) is transformed to `T ... U | T ... V` and appropriate transformations are carried out separately for each union member.
4. Spread types are associative: `(T ... U) ... V` is equivalent to `T ... (U ... V)`. And they combine adjacent object type and adjacent type parameters that are identical: `T ... T ... { a } ... { b }` is equivalent to `T ... { a, b }`.
5. Spread types now support limited type inference. Specifically, you can infer from an object type to a spread type:

```ts
declare function f<T>(t: { ...T, x: number }): T;
f({ a: 1, x: 12}); // returns { a: number }
```

Even more limited inference from spread types to bare types is supported.
TODO: Explain later.

**Comment by sandersn** [comment]
More notes on type inference:

given

```ts
declare function f<T>(t: { ...T, x: number }): T;
f({ a: 1, x: 12 }); // returns { a: number }
```

Type inference will only destructure if it meets the following conditions:
1. The source type must be an object type.
2. The target type only uses the right-most type parameter as an inference target, and only the properties to the right of the right-most type parameter are removed.

For example, this function returns the same thing, although it additionally requires that `t` contain a property named `intermediate`:

```ts
declare function f<T, U>(t: { ...U, intermediate: string, ...T, x: number }): T;
```

Note that the first example is equivalent to `declare function f<T>(t: T & { x: number }): T` but I think this version is far more discoverable. I don't want to write another FAQ to go with "Why is T={} when I don't have a parameter of type T?". So I think this kind of destructuring should work.

Type inference works with a spread type source, with the additional limit that neither type parameter is followed by properties. Here's an example:

```ts
interface Congealed {
  kind: 0 | 1 | 2
}
class C implements Congealed {
  kind: 0
  method(): void { }
}
/** Re-add methods to a object that has been spread */
function revive<T extends Congealed>(t: { ...T }): T {
  if (kind === 0) {
    (t as any).method = C.prototype.method;
  }
  // other kinds go here ...
  return t;
}
function roundTrip<T extends Congealed>(t: T): T {
  let ts = { ...t };
  // do some things with ts ...
  return revive(ts);
}
let cs = { ...new C() };
(revive(cs)).method // error, T={kind: 0}, which still doesn't have `method`
(revive<C>(cs)).method; // ok, T=C, which now has method
roundTrip(new C()).method; // ok, C still has method
```

The justification here is that (1) if it works for concrete types, it should work for type parameters *if possible* (2) TypeScript already supports this kind of inference to impossible-to-produce types in other places. For example, in optional parameters with a type parameter:

```ts
declare function opt<T>(p?: T): T;
let t = opt();
let okIGuess = opt<number>();
```

If the user wants to short-circuit type inference to get the right answer, they are free to do so with an explicit type parameter.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/checker.ts]: This code no longer exists.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [inline src/compiler/checker.ts]: No, but it only saves a couple of casts anyway.

**Comment by sandersn** [comment]
@DanielRosenwasser I updated the PR with your refactoring suggestions.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+            Debug.assert(!!(right.flags & (TypeFlags.TypeParameter | TypeFlags.Intersection | TypeFlags.ObjectType)), "Right flags: " + right.flags.toString(2));
+            spread.left = left as SpreadType | ResolvedType;
+            spread.right = right as TypeParameter | IntersectionType | ResolvedType;
+            spread.aliasSymbol = aliasSymbol;
+            spread.aliasTypeArguments = aliasTypeArguments;
+            return spread;
+        }
+
+        function resolveObjectIntersection(intersection: IntersectionType): IntersectionType | ResolvedType {
+            if (find(intersection.types, t => !(t.flags & TypeFlags.ObjectType) || couldContainTypeParameters(t))) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: don't need couldcontaintypeparameters

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+        function getSpreadType(types: Type[], symbol: Symbol, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
+            if (types.length === 0) {
+                return emptyObjectType;
+            }
+            const id = getTypeListId(types);
+            if (id in spreadTypes) {
+                return spreadTypes[id];
+            }
+            let right = types.pop();
+            if (right.flags & TypeFlags.StringLike) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Why is this here?

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+                }
+            }
+            if (members || stringIndexInfo || numberIndexInfo) {
+                spreads.push(createAnonymousType(node.symbol, members || emptySymbols, emptyArray, emptyArray, stringIndexInfo, numberIndexInfo));
+            }
+            return getSpreadType(spreads, node.symbol, aliasSymbol, aliasTypeArguments);
+        }
+
+        function getSpreadType(types: Type[], symbol: Symbol, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
+            if (types.length === 0) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: instead of passing a types array, have the callers of getSpreadType call it repeatedly with left and right.

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+            }
+            if (left.flags & TypeFlags.Intersection) {
+                left = resolveObjectIntersection(left as IntersectionType);
+            }
+            if (left.flags & TypeFlags.Union) {
+                const spreads = map((left as UnionType).types,
+                                  t => getSpreadType(types.slice().concat([t, right]), symbol, aliasSymbol, aliasTypeArguments));
+                return getUnionType(spreads, /*subtypeReduction*/ false, aliasSymbol, aliasTypeArguments);
+            }
+            if (right.flags & TypeFlags.ObjectType && left.flags & TypeFlags.ObjectType) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: maybe move to separate function

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+                    members[symbol.name] = symbol;
+                }
+            }
+            if (members || stringIndexInfo || numberIndexInfo) {
+                spreads.push(createAnonymousType(node.symbol, members || emptySymbols, emptyArray, emptyArray, stringIndexInfo, numberIndexInfo));
+            }
+            return getSpreadType(spreads, node.symbol, aliasSymbol, aliasTypeArguments);
+        }
+
+        function getSpreadType(types: Type[], symbol: Symbol, aliasSymbol?: Symbol, aliasTypeArguments?: Type[]): Type {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I think this should just take a left and a right type. You can then worry about breaking sequences into discrete operations elsewhere (in either a left or right associative way).

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+                const simplified = getSpreadType([right, (left as SpreadType).right], symbol, aliasSymbol, aliasTypeArguments);
+                return getSpreadType([(left as SpreadType).left, simplified], symbol, aliasSymbol, aliasTypeArguments);
+            }
+            if (left.flags & TypeFlags.Intersection) {
+                left = resolveObjectIntersection(left as IntersectionType);
+            }
+            if (left.flags & TypeFlags.Union) {
+                const spreads = map((left as UnionType).types,
+                                  t => getSpreadType(types.slice().concat([t, right]), symbol, aliasSymbol, aliasTypeArguments));
+                return getUnionType(spreads, /*subtypeReduction*/ false, aliasSymbol, aliasTypeArguments);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Check out the similar code in `getIntersectionType`.

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+            }
+            if (right.flags & TypeFlags.ObjectType && left.flags & TypeFlags.ObjectType) {
+                const members = createMap<Symbol>();
+                const skippedPrivateMembers = createMap<boolean>();
+                let stringIndexInfo = unionIndexInfos(getIndexInfoOfType(left, IndexKind.String), getIndexInfoOfType(right, IndexKind.String));
+                let numberIndexInfo = unionIndexInfos(getIndexInfoOfType(left, IndexKind.Number), getIndexInfoOfType(right, IndexKind.Number));
```
Comment (sandersn) [inline src/compiler/checker.ts]: only union if BOTH have indexers. If only one does, then we can't tell. Also make indexers illegal on object literal types that have spreads in them.

File: src/compiler/checker.ts (hunk 8 above)
Comment (weswigham) [inline src/compiler/checker.ts]: @sandersn Does that mean that if the right type is a string literal type, rather than a generic `string`, wouldn't it be more accurate to expand to the full, correct, object then? (For example, `type NSEW= {..."NSEW"};` can be expanded to `{0: "N", 1:"S", 2:"E", 3:"W"}` rather than `{[index: number]: string}`?)

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -2312,6 +2316,46 @@ namespace ts {
...
+                    if (type.left.flags & TypeFlags.Spread) {
+                        writeSpreadTypeWorker(type.left as SpreadType, /*atEnd*/false, container);
+                    }
+                    else {
+                        const saveInObjectTypeLiteral = inObjectTypeLiteral;
+                        inObjectTypeLiteral = true;
+                        writeObjectLiteralType(resolveStructuredTypeMembers(type.left));
+                        inObjectTypeLiteral = saveInObjectTypeLiteral;
+                    }
+                    if (type.right.symbol === container) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: What does it mean for the `right` to be the given `container`?

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: (while I can guess, a comment is probably helpful)

File: src/compiler/checker.ts [hunk 15]
```diff
@@ -4450,6 +4518,10 @@ namespace ts {
             return type.resolvedApparentType;
         }
 
+        function getApparentTypeOfSpread(type: SpreadType) {
+            return getApparentType(type.right);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Can you explain the intuition here? Shouldn't the apparent type be the flattened object type that right side properties overlaid on left-side properties?

File: src/compiler/checker.ts (hunk 12 above)
Comment (sandersn) [inline src/compiler/checker.ts]: This code simpler now that it only has to deal with `left` and `right`

File: src/compiler/checker.ts (hunk 8 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Actually, after talking with @ahejlsberg about indexers in general, I'm inclined to leave off the indexer entirely and treat `string` like other primitives. It would be simpler but less correct. Anders, do you have an opinion either way?

File: src/compiler/checker.ts (hunk 7 above)
Comment (sandersn) [inline src/compiler/checker.ts]: done

File: src/compiler/checker.ts (hunk 9 above)
Comment (sandersn) [inline src/compiler/checker.ts]: It's easier to do it inside `checkObjectLiteral` and `getTypeFromTypeLiteral` because those bodies of code both have a for loop and would otherwise need to build up a list to hold the spread types. This way they can just keep a single spread type and manually fold in new spreads when needed, like `spread = getSpreadType(spread, newSpread)`

File: src/compiler/checker.ts [hunk 16]
```diff
@@ -5667,6 +5752,191 @@ namespace ts {
...
+                            if (parameter.type.kind === SyntaxKind.StringKeyword) {
+                                stringIndexInfo = indexInfo;
+                            }
+                            else {
+                                numberIndexInfo = indexInfo;
+                            }
+                        }
+                    }
+                }
+                else if (member.kind !== SyntaxKind.CallSignature && member.kind !== SyntaxKind.ConstructSignature) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Why not give an error?

Comment (sandersn) [inline src/compiler/checker.ts]: Good idea

Comment (sandersn) [inline src/compiler/checker.ts]: In fact, index signatures are illegal too, so I don't need the code to create those either. I added the error and got rid of the index signature code.

Comment (sandersn) [inline src/compiler/checker.ts]: Done

File: src/compiler/checker.ts (hunk 15 above)
Comment (sandersn) [inline src/compiler/checker.ts]: This implementation is simplified from reality, but probably not often enough to matter. First, remember that spread types are only created if there's an type parameter embedded in it [1]. So we're talking about types like `T ... U, { x } ... T or T ... { x }`

This code is correct for `T ... U and { x } ... T`. For example [2], if `*T = { x: string }` and `*U = { y: number }` then you can only say for sure that `*(T ... U) = { y: number }` because when `U` is instantiated, it might have `{ x: number }`, meaning that the instantiated type would actually be `{ x: number, y: number }`. And if `U` ends up with `{ x?: number }`, then the final type would have `x: number | string`.

Same reasoning applies to `{ x } ... T` &mdash; `T` might contain `x` with a different type.

That leaves `T ... { x }` which could actually distribute the apparent type down, but I don't think this case is worth enough in practise to justify the additional code. You can go back a few commits to see what the code looked like, although it would need to be surrounded with `if (type.right & TypeFlags.Object) ... else return getApparentType(type.right)`.

[1] Or an intersection with a type parameter embedded in *it*.
[2] I'll use the syntax `*T` to shorten `getApparentType(T)`.

**Comment by sandersn** [comment]
@ahejlsberg @DanielRosenwasser any more comments since I addressed the last round?

File: src/compiler/binder.ts [hunk 17]
```diff
@@ -1138,8 +1138,8 @@ namespace ts {
             }
             else if (node.kind === SyntaxKind.ArrayLiteralExpression) {
                 for (const e of (<ArrayLiteralExpression>node).elements) {
-                    if (e.kind === SyntaxKind.SpreadElementExpression) {
-                        bindAssignmentTargetFlow((<SpreadElementExpression>e).expression);
+                    if (e.kind === SyntaxKind.SpreadExpression) {
```
Comment (rbuckton) [inline src/compiler/binder.ts]: Why `SpreadExpression` here, but `SpreadElementExpression` on 1157?

File: src/compiler/binder.ts [hunk 18]
```diff
@@ -1154,6 +1154,9 @@ namespace ts {
                     else if (p.kind === SyntaxKind.ShorthandPropertyAssignment) {
                         bindAssignmentTargetFlow((<ShorthandPropertyAssignment>p).name);
                     }
+                    else if (p.kind === SyntaxKind.SpreadElementExpression) {
```
Comment (rbuckton) [inline src/compiler/binder.ts]: I've been debating renaming this to remove the "Expression" part, since the node itself is not an Expression, and can only be used in an array literal, argument list, or binding pattern.

File: src/compiler/types.ts [hunk 19]
```diff
@@ -246,7 +246,7 @@ namespace ts {
         ConditionalExpression,
         TemplateExpression,
         YieldExpression,
-        SpreadElementExpression,
+        SpreadExpression,
```
Comment (rbuckton) [inline src/compiler/types.ts]: I think the term `SpreadElement` made more sense, since we are spreading an array element. For object spread I think it would be more accurate to call it a `SpreadAssignment` (along with `PropertyAssignment` and `ShorthandPropertyAssignment`).

File: src/compiler/types.ts [hunk 20]
```diff
@@ -662,6 +662,7 @@ namespace ts {
         initializer?: Expression;           // Optional initializer
     }
 
+    // @kind(SyntaxKind.PropertyDeclaration)
```
Comment (rbuckton) [inline src/compiler/types.ts]: We don't really need these comments, since `kind` is now part of the declaration (on line 667).

File: src/compiler/types.ts [hunk 21]
```diff
@@ -694,6 +695,11 @@ namespace ts {
         objectAssignmentInitializer?: Expression;
     }
 
+    export interface SpreadElementExpression extends ObjectLiteralElement {
```
Comment (rbuckton) [inline src/compiler/types.ts]: See previous comment re: `SpreadAssignment`

File: src/compiler/types.ts [hunk 22]
```diff
@@ -1279,8 +1285,9 @@ namespace ts {
         multiLine?: boolean;
     }
 
-    export interface SpreadElementExpression extends Expression {
-        kind: SyntaxKind.SpreadElementExpression;
+    // @kind(SyntaxKind.SpreadExpression)
+    export interface SpreadExpression extends Expression {
```
Comment (rbuckton) [inline src/compiler/types.ts]: See previous comment re: `SpreadElement`

File: src/compiler/types.ts [hunk 23]
```diff
@@ -3472,39 +3488,42 @@ namespace ts {
...
+        ContainsCapturedLexicalThis = 1 << 19,
+        ContainsLexicalThisInComputedPropertyName = 1 << 20,
+        ContainsDefaultValueAssignments = 1 << 21,
+        ContainsParameterPropertyAssignments = 1 << 22,
+        ContainsSpreadExpression = 1 << 23,
+        ContainsComputedPropertyName = 1 << 24,
+        ContainsBlockScopedBinding = 1 << 25,
+        ContainsBindingPattern = 1 << 26,
+        ContainsYield = 1 << 27,
+        ContainsHoistedDeclarationOrCompletion = 1 << 28,
```
Comment (rbuckton) [inline src/compiler/types.ts]: We've officially run out of space. We may have to start another enum for any new flags, or find ways to consolidate.

File: src/compiler/visitor.ts [hunk 24]
```diff
@@ -267,9 +267,9 @@ namespace ts {
             case SyntaxKind.VoidExpression:
             case SyntaxKind.AwaitExpression:
             case SyntaxKind.YieldExpression:
-            case SyntaxKind.SpreadElementExpression:
+            case SyntaxKind.SpreadExpression:
```
Comment (rbuckton) [inline src/compiler/visitor.ts]: I don't see anything in here for your new `SpreadElementExpression`

File: src/compiler/visitor.ts [hunk 25]
```diff
@@ -870,9 +870,9 @@ namespace ts {
                 return updateYield(<YieldExpression>node,
                     visitNode((<YieldExpression>node).expression, visitor, isExpression));
 
-            case SyntaxKind.SpreadElementExpression:
-                return updateSpread(<SpreadElementExpression>node,
-                    visitNode((<SpreadElementExpression>node).expression, visitor, isExpression));
+            case SyntaxKind.SpreadExpression:
```
Comment (rbuckton) [inline src/compiler/visitor.ts]: I don't see anything in here for your new `SpreadElementExpression`

File: src/compiler/emitter.ts [hunk 26]
```diff
@@ -822,8 +822,8 @@ const _super = (function (geti, seti) {
                     return emitTemplateExpression(<TemplateExpression>node);
                 case SyntaxKind.YieldExpression:
                     return emitYieldExpression(<YieldExpression>node);
-                case SyntaxKind.SpreadElementExpression:
-                    return emitSpreadElementExpression(<SpreadElementExpression>node);
+                case SyntaxKind.SpreadExpression:
```
Comment (rbuckton) [inline src/compiler/emitter.ts]: I don't see anything in here for your new `SpreadElementExpression`

File: src/compiler/transformer.ts [hunk 27]
```diff
@@ -116,6 +117,7 @@ namespace ts {
             transformers.push(transformJsx);
         }
 
+        transformers.push(transformESNext);
```
Comment (rbuckton) [inline src/compiler/transformer.ts]: Do we plan on having a `--target esnext` to disable esnext transformations and emit as-is?

File: src/compiler/types.ts (hunk 20 above)
Comment (sandersn) [inline src/compiler/types.ts]: Should have gotten rid of these in the merge, sorry. Fixed.

File: src/compiler/types.ts (hunk 19 above)
Comment (sandersn) [inline src/compiler/types.ts]: Good idea. Done.

File: src/compiler/binder.ts (hunk 17 above)
Comment (sandersn) [inline src/compiler/binder.ts]: `[ x, ...y]` produces a `SpreadExpression` (now `SpreadElement`) for `...y`. `{ x: 1, ...y }` produces `SpreadElementExpression` (now `SpreadAssignment`) for `...y`. So the nodes are actually different for arrays vs objects.

File: src/compiler/visitor.ts (hunk 24 above)
Comment (sandersn) [inline src/compiler/visitor.ts]: Added

File: src/compiler/visitor.ts (hunk 25 above)
Comment (sandersn) [inline src/compiler/visitor.ts]: Added

File: src/compiler/emitter.ts (hunk 26 above)
Comment (sandersn) [inline src/compiler/emitter.ts]: Done

File: src/compiler/transformer.ts (hunk 27 above)
Comment (sandersn) [inline src/compiler/transformer.ts]: I hadn't planned on it, But it's a good idea. I suppose people may want Babel to manage the emit, for example.

Comment (sandersn) [inline src/compiler/transformer.ts]: Done

File: src/compiler/checker.ts [hunk 28]
```diff
@@ -4564,12 +4588,16 @@ namespace ts {
...
             result.containingType = containingType;
             result.hasNonUniformType = hasNonUniformType;
             result.isPartial = isPartial;
             result.declarations = declarations;
+            if (declarations.length) {
+                result.valueDeclaration = declarations[0];
+            }
             result.isReadonly = isReadonly;
-            result.type = containingType.flags & TypeFlags.Union ? getUnionType(propTypes) : getIntersectionType(propTypes);
+            result.type = containingType.flags & TypeFlags.Intersection ? getIntersectionType(propTypes) : getUnionType(propTypes);
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: Revert If you feel like it

File: src/compiler/checker.ts [hunk 29]
```diff
@@ -5851,6 +5879,67 @@ namespace ts {
...
+            }
+
+            const isFromSpread = right.symbol !== symbol;
+            for (const rightProp of getPropertiesOfType(right)) {
+                if (getDeclarationModifierFlagsFromSymbol(rightProp) & (ModifierFlags.Private | ModifierFlags.Protected)) {
+                    skippedPrivateMembers[rightProp.name] = true;
+                }
+                else if (!(rightProp.flags & SymbolFlags.Method && isFromSpread) &&
+                         !(rightProp.flags & SymbolFlags.SetAccessor && !(rightProp.flags & SymbolFlags.GetAccessor))) {
+                    // skip methods from spreads and accessors with setters but no getters
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: From offline, "hilariously yes"
.

File: src/compiler/checker.ts (hunk 28 above)
Comment (sandersn) [inline src/compiler/checker.ts]: done

File: src/compiler/checker.ts [hunk 30]
```diff
@@ -5851,6 +5879,67 @@ namespace ts {
             return links.resolvedType;
         }
 
+        /**
+         * Since the source of spread types are object literals and type literals, which are not binary,
```
Comment (sandersn) [inline src/compiler/checker.ts]: done

File: src/compiler/checker.ts [hunk 31]
```diff
@@ -5851,6 +5879,67 @@ namespace ts {
...
+         * and right = the new element to be spread.
+         */
+        function getSpreadType(left: Type, right: Type, symbol: Symbol): ResolvedType {
+            Debug.assert(!!(left.flags & TypeFlags.Object) && !!(right.flags & TypeFlags.Object), "Only object types may be spread.");
+            const members = createMap<Symbol>();
+            const skippedPrivateMembers = createMap<boolean>();
+            let stringIndexInfo: IndexInfo;
+            let numberIndexInfo: IndexInfo;
+            if (left === emptyObjectType) {
+                // for the first spread element, left === emptyObjectType, so take the right's string indexer
```
Comment (sandersn) [inline src/compiler/checker.ts]: It's treated like any other object type. `emptyObjectType` is only a marker of the start of the spread type because the `checkObjectLiteral` uses `getSpreadType` in a left fold manner, and `emptyObjectType` is initial value of the fold.

File: src/compiler/checker.ts [hunk 32]
```diff
@@ -5851,6 +5879,67 @@ namespace ts {
...
+                    // skip methods from spreads and accessors with setters but no getters
+                    members[rightProp.name] = rightProp;
+                }
+            }
+            for (const leftProp of getPropertiesOfType(left)) {
+                if (leftProp.flags & SymbolFlags.SetAccessor && !(leftProp.flags & SymbolFlags.GetAccessor)
+                    || leftProp.name in skippedPrivateMembers) {
+                    continue;
+                }
+                if (leftProp.name in members) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: Well, it's the members of the resulting spread. If `right` doesn't have a property that `left` does, then `members` will have `leftProp`. So calling it `rightProps` is not accurate.

File: src/compiler/types.ts (hunk 23 above)
Comment (ahejlsberg) [inline src/compiler/types.ts]: Please, no more properties in the base node!

File: src/compiler/checker.ts [hunk 33]
```diff
@@ -5860,6 +5888,70 @@ namespace ts {
             return links.resolvedType;
         }
 
+        /**
+         * Since the source of spread types are object literals, which are not binary,
+         * this function should be called in a left folding style, with left = previous result of getSpreadType
+         * and right = the new element to be spread.
+         */
+        function getSpreadType(left: Type, right: Type, symbol: Symbol): ResolvedType | IntrinsicType {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: The `symbol` parameter doesn't make sense. This should just create an anonymous type with no symbol.

File: src/compiler/checker.ts [hunk 34]
```diff
@@ -5860,6 +5888,70 @@ namespace ts {
...
+                // for the first spread element, left === emptyObjectType, so take the right's string indexer
+                stringIndexInfo = getIndexInfoOfType(right, IndexKind.String);
+                numberIndexInfo = getIndexInfoOfType(right, IndexKind.Number);
+            }
+            else {
+                stringIndexInfo = unionSpreadIndexInfos(getIndexInfoOfType(left, IndexKind.String), getIndexInfoOfType(right, IndexKind.String));
+                numberIndexInfo = unionSpreadIndexInfos(getIndexInfoOfType(left, IndexKind.Number), getIndexInfoOfType(right, IndexKind.Number));
+            }
+
+            const isFromSpread = right.symbol !== symbol;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: This is very subtle and there is no comment to explain it. I would have a discrete parameter for this with a comment that explains its purpose.

File: src/compiler/checker.ts [hunk 35]
```diff
@@ -5860,6 +5888,70 @@ namespace ts {
...
+                        const declarations: Declaration[] = concatenate(leftProp.declarations, rightProp.declarations);
+                        const flags = SymbolFlags.Property | SymbolFlags.Transient | SymbolFlags.SyntheticProperty | (leftProp.flags & SymbolFlags.Optional);
+                        const result = <TransientSymbol>createSymbol(flags, leftProp.name);
+                        result.syntheticKind = SyntheticSymbolKind.Spread;
+                        result.leftSpread = leftProp;
+                        result.rightSpread = rightProp;
+                        result.declarations = declarations;
+                        if (declarations.length) {
+                            result.valueDeclaration = declarations[0];
+                        }
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Again, any reason you're setting the `valueDeclaration` property?

File: src/compiler/checker.ts [hunk 36]
```diff
@@ -5860,6 +5888,70 @@ namespace ts {
...
+                        result.isReadonly = isReadonlySymbol(leftProp) || isReadonlySymbol(rightProp);
+                        members[leftProp.name] = result;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Just compute the type here and set it directly on the new symbol.

File: src/compiler/checker.ts [hunk 37]
```diff
@@ -15079,9 +15207,11 @@ namespace ts {
             forEach(node.members, checkSourceElement);
             if (produceDiagnostics) {
                 const type = getTypeFromTypeLiteralOrFunctionOrConstructorTypeNode(node);
-                checkIndexConstraints(type);
-                checkTypeForDuplicateIndexSignatures(node);
-                checkObjectTypeForDuplicateDeclarations(node);
+                if (type.flags & TypeFlags.Object) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: When would this not be an object?

File: src/compiler/checker.ts [hunk 38]
```diff
@@ -17140,7 +17270,7 @@ namespace ts {
                 // perform property check if property or indexer is declared in 'type'
                 // this allows to rule out cases when both property and indexer are inherited from the base class
                 let errorNode: Node;
-                if (prop.valueDeclaration.name.kind === SyntaxKind.ComputedPropertyName || prop.parent === containingType.symbol) {
+                    if (prop.valueDeclaration.name.kind === SyntaxKind.ComputedPropertyName || prop.parent === containingType.symbol) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Restore indentation.

File: src/compiler/checker.ts [hunk 39]
```diff
@@ -20412,8 +20547,11 @@ namespace ts {
             const GetOrSetAccessor = GetAccessor | SetAccessor;
 
             for (const prop of node.properties) {
+                if (prop.kind === SyntaxKind.SpreadAssignment) {
+                    continue;
+                }
                 const name = prop.name;
-                if (name.kind === SyntaxKind.ComputedPropertyName) {
+                if (name && name.kind === SyntaxKind.ComputedPropertyName) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Can `name` now be undefined where previously it couldn't?

File: src/compiler/checker.ts [hunk 40]
```diff
@@ -4479,7 +4499,10 @@ namespace ts {
 
         function getPropertiesOfType(type: Type): Symbol[] {
             type = getApparentType(type);
-            return type.flags & TypeFlags.UnionOrIntersection ? getPropertiesOfUnionOrIntersectionType(<UnionType>type) : getPropertiesOfObjectType(type);
+            if (type.flags & TypeFlags.UnionOrIntersection) {
+                return getPropertiesOfUnionOrIntersectionType(<UnionType>type);
+            }
+            return getPropertiesOfObjectType(type);
```
Comment (sandersn) [inline src/compiler/checker.ts]: With a separate spread type, I had more code in here that made the verbose style more readable. Restored.

File: src/compiler/checker.ts [hunk 41]
```diff
@@ -5041,7 +5069,7 @@ namespace ts {
             const declaration = getIndexDeclarationOfSymbol(symbol, kind);
             if (declaration) {
                 return createIndexInfo(declaration.type ? getTypeFromTypeNode(declaration.type) : anyType,
-                    (getModifierFlags(declaration) & ModifierFlags.Readonly) !== 0, declaration);
+                                       (getModifierFlags(declaration) & ModifierFlags.Readonly) !== 0, declaration);
```
Comment (sandersn) [inline src/compiler/checker.ts]: Fixed

File: src/compiler/checker.ts (hunk 36 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Done

File: src/compiler/checker.ts (hunk 37 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Left over from when `{ ...T }` syntax would produce a spread type. Removed.

File: src/compiler/checker.ts [hunk 42]
```diff
@@ -4564,10 +4588,14 @@ namespace ts {
...
             }
             const result = <TransientSymbol>createSymbol(SymbolFlags.Property | SymbolFlags.Transient | SymbolFlags.SyntheticProperty | commonFlags, name);
+            result.syntheticKind = SyntheticSymbolKind.UnionOrIntersection;
             result.containingType = containingType;
             result.hasNonUniformType = hasNonUniformType;
             result.isPartial = isPartial;
             result.declarations = declarations;
+            if (declarations.length) {
+                result.valueDeclaration = declarations[0];
+            }
```
Comment (sandersn) [inline src/compiler/checker.ts]: Checking index constraints in `checkIndexConstraints` relies on `valueDeclaration`. It's not needed now that we don't create synthetic symbols for spread any more, so I removed it. But in general `checkIndexConstraints` works on synthetic properties by mistake. If choosing an arbitrary valueDeclaration isn't right, the `checkIndexConstraints` needs to stop relying on it.

File: src/compiler/checker.ts (hunk 35 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Same as above. Removed.

File: src/compiler/checker.ts (hunk 38 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Fixed

File: src/compiler/checker.ts (hunk 39 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Not anymore. Removed.

File: src/compiler/checker.ts [hunk 43]
```diff
@@ -5860,6 +5888,70 @@ namespace ts {
             return links.resolvedType;
         }
 
+        /**
+         * Since the source of spread types are object literals, which are not binary,
+         * this function should be called in a left folding style, with left = previous result of getSpreadType
+         * and right = the new element to be spread.
+         */
+        function getSpreadType(left: Type, right: Type, symbol: Symbol): ResolvedType | IntrinsicType {
+            Debug.assert(!!(left.flags & (TypeFlags.Object | TypeFlags.Any)) && !!(right.flags & (TypeFlags.Object | TypeFlags.Any)), "Only object types may be spread.");
```
Comment (sandersn) [inline src/compiler/checker.ts]: I did, and it would be simple to restore the code I had there earlier. The reason I decided against is that it gets harder to issue a correct, understandable error in `checkObjectLiteral` because intersections that contain type parameters are still not allowed. And I assume that we'll have a good story for all kinds of type operators shortly after 2.1 ships, so a restriction on intersections won't have lasting problems.

**Comment by sandersn** [comment]
I just noticed that I forgot to comment on not allowing intersections. Here's the comment copied out of the original thread since github's UI collapses that one.

>> Did you consider permitting intersection types as well? I understand how union types are harder and would require "lifting" to produce a resulting union type, but it seems like intersections would just work.

> I did, and it would be simple to restore the code I had there earlier. The reason I decided against is that it gets harder to issue a correct, understandable error in checkObjectLiteral because intersections that contain type parameters are still not allowed. And I assume that we'll have a good story for all kinds of type operators shortly after 2.1 ships, so a restriction on intersections won't have lasting problems.

File: src/compiler/types.ts (hunk 23 above)
Comment (sandersn) [inline src/compiler/types.ts]: I think I can avoid the over-emit inside destructuring by checking whether the destructuring is happening for ESNext. If it's ESNext, then I can just do nothing to nodes that have ContainsSpreadElement if they are array rest rather than object rest.

File: src/compiler/checker.ts [hunk 44]
```diff
@@ -5860,6 +5872,67 @@ namespace ts {
...
+                }
+            }
+            for (const leftProp of getPropertiesOfType(left)) {
+                if (leftProp.flags & SymbolFlags.SetAccessor && !(leftProp.flags & SymbolFlags.GetAccessor)
+                    || leftProp.name in skippedPrivateMembers) {
+                    continue;
+                }
+                if (leftProp.name in members) {
+                    const rightProp = members[leftProp.name];
+                    if (rightProp.flags & SymbolFlags.Optional) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I think a more correct check here is whether the type of `rightProp` includes `undefined`. After all, that's how it works at runtime.

**Comment by whitecolor** [comment]
Is it possible to omit a property from object?

**Comment by MathieuLorber** [comment]
@whitecolor no, compiler complains

**Comment by alitaheri** [comment]
@whitecolor 

you mean:
```ts
const myObj = {a: 1, b:2, c:3};
const { a, ...myObjWithoutA} = myObj;

// myObjWithoutA has b and c but not a
```

**Comment by whitecolor** [comment]
@alitaheri that is intresting btw

What I meant a little bit different, though I probably do not refere to spread,

I wanted to make it with only types without objects

say from `interface {a: string, b: string}` get => `interface {b: string}`

**Comment by MathieuLorber** [comment]
@whitecolor it isn't relative to spread, from what I understand now. I first understood your question was relative to smthg like that :
```javascript
interface Foo {
    foo: string
    bar: string
}
let val = {foo: 'hello'};
let val2: Foo = {...val};
```
In that configuration, compiler complains.

**Comment by uxp** [comment]
I was looking to implement the emitted code from this patch into my project as a 'backport' utility until we can update to a released Typescript version that contains this operator, but I think I'm not understanding exactly what the patch does, because the way it seems to be implemented might have a bug?

Basically, if we look at the emitted code in isolation, the idea of what it's supposed to do is fairly obvious.
```
 +        const restHelper = `
 +var __rest = (this && this.__rest) || function (s, e) {
 +    var t = {};
 +    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && !e.indexOf(p))
 +        t[p] = s[p];
 +    return t;
 +};`;
 ```
Create new target object `t`, and for every owned property `p` of source `s` that is not specified as excluded in `e`, copy `s`'s property `p` to `t`, and then return target object `t`.

The only problem with this specifically is that javascript arrays are zero indexed, and the value of the expression `!0` is true, so a literal invocation of this function with a source object of `{ a: 1, b: 2, c: 3, d: 4, e: 5 }` such as: 
```
let obj = { a: 1, b: 2, c: 3, d: 4, e: 5 };
let { a, b, c } = obj;
let rest = __rest(obj, ['a', 'b', 'c']);
```
would result in the `rest` variable containing the values `{ a: 1, d: 4, e: 5 }`. I would expect the result to lack the keys `a`, `b`, and `c`, but it manages to include `a`, since it's index in the parameter array `e` is not greater than zero. In order to accomplish this desire, we could check to see if the index of the excluded key is `-1`, as that is the value that is returned from the `indexOf()` function when the value does not exist.

Unless I'm (likely) missing some essential context, it seems to me that there is an issue with the accepted solution.

Thanks for your time.

**Comment by wallverb** [comment]
@uxp - https://github.com/Microsoft/TypeScript/issues/12956 FYI
