### PR TITLE
Fix document registry cache key calculation for `paths` compiler option

### LINKED ISSUE #48278: DocumentRegistry bucket key contains `[object Object]`
As of 93c3a30edc7cc4be94bbeb3074a6a678ffd45d3b

[`getKeyForCompilationSetting`](https://github.com/microsoft/TypeScript/blob/93c3a30edc7cc4be94bbeb3074a6a678ffd45d3b/src/services/documentRegistry.ts#L360) joins compiler options as strings to form the key, but `paths` is an array.  There may be other non-primitive settings values.

Example value: `"1|99|true|1|true||2|c:/project|[object Object]||||true||||true||"`

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #48278

### CODE REVIEW

File: src/services/documentRegistry.ts [hunk 1]
```diff
@@ -357,7 +357,26 @@ namespace ts {
...
+            if (ts.hasOwnProperty.call(value, key)) { // eslint-disable-line @typescript-eslint/no-unnecessary-qualifier
+                str += `${key}: ${compilerOptionValueToString((value as any)[key])}`;
+            }
+        }
+        return str + "}";
+    }
+
     function getKeyForCompilationSettings(settings: CompilerOptions): DocumentRegistryBucketKey {
-        return sourceFileAffectingCompilerOptions.map(option => getCompilerOptionValue(settings, option)).join("|") as DocumentRegistryBucketKey;
+        return sourceFileAffectingCompilerOptions.map(option => compilerOptionValueToString(getCompilerOptionValue(settings, option), option.name === "paths" ? settings.configFilePath || "" : undefined)).join("|") as DocumentRegistryBucketKey;
```
Comment (sheetalkamat) [inline src/services/documentRegistry.ts:380]:
```suggestion
        return sourceFileAffectingCompilerOptions.map(option => compilerOptionValueToString(getCompilerOptionValue(settings, option)).join("|") + (settings.pathsBasePath ? `|${pathsBasePath}` : "") as DocumentRegistryBucketKey;
```

**Review by sheetalkamat — APPROVED** [review]
