### PR TITLE
Include source node inferences in string literal completions

### LINKED ISSUE #49680: with infer in template string, suggestion works in 4.6, but not work in 4.7
# Bug Report

### 🔎 Search Terms

suggestion pathof

### 🕗 Version & Regression Information

4.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.4#code/FAehAIHMFMBdwGYCcD2BbcALWsAOBnALjEgEtZMBXAIwDoBjdENU+1fFBWEAFQE9c0AMptSubqXz5K0fCABMABgAs8gMwBiSdOiM0aaADtYAWgAcARnkBWAGzKzq4LAHRwABQCGFAPIIAPDwANOAA0uDQAB6wRgAm+OD4sEikhpAh7hHRcQlJKWngALzgAEQlAHxFwOBhWTGG8eAABgAkAN6pCNBI4ACqAL607Z3d4ABq-U3VNeAA-H11OeAA1tB8nOA8cx7emH6BANq9ALohYyGtbe797QO0TZWEze3X7avrCJvgAGTgABR5VKQcAAH3AhkoaGo3QAlJNpjUnuEovVGu8Nlt5pdXm1QpNwE9sTc2ujPltfgDkkDQeDIdCkHCmgBuYCs2K6AA2niQbgQlEM9FgpBQhnAjEM0gMSH8yOyDVyVLS5T+uF2Ty8vgCbU8T0BaRC1CebXousVkH6-RCoXKMIJtKh3RZrPFku6fwA5HR3TDgEA)

### 💻 Code

```ts

// get from https://github.com/microsoft/TypeScript/issues/20423#issuecomment-812564842
type PathOf<T, K extends string, P extends string = ""> =
  K extends `${infer U}.${infer V}`
    ? U extends keyof T ? PathOf<T[U], V, `${P}${U}.`> : `${P}${keyof T & (string | number)}`
    : K extends keyof T ? `${P}${K}` : `${P}${keyof T & (string | number)}`;


declare function consumer<K extends string>(path: PathOf<{a: string, b: {c: string}}, K>) : number;

// suggestion works well in 4.6, and not work in 4.7
consumer('b.')
```

### 🙁 Actual behavior

image

### 🙂 Expected behavior

image

### PR DESCRIPTION
**Pull request by rbuckton**
This adopts the proposed fix mentioned in https://github.com/microsoft/TypeScript/issues/49680#issuecomment-1199933521. This is a different approach than the one taken by @Andarist in #52997, as that PR attempted to pre-filter results.

Fixes #49680
Supersedes #52997

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -2036,7 +2059,7 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         getGlobalIterableType: getGlobalAsyncIterableType,
         getGlobalIterableIteratorType: getGlobalAsyncIterableIteratorType,
         getGlobalGeneratorType: getGlobalAsyncGeneratorType,
-        resolveIterationType: getAwaitedType,
+        resolveIterationType: (type, errorNode) => getAwaitedType(type, errorNode, Diagnostics.Type_of_await_operand_must_either_be_a_valid_promise_or_must_not_contain_a_callable_then_member),
```
Comment (jakebailey) [inline src/compiler/checker.ts:2062]: Is this leftover from a change on main?

Comment (rbuckton) [reply src/compiler/checker.ts]: It's from #54107, which is merged in main. I rebased and it shouldn't be showing up now.

**Review by jakebailey — APPROVED** [review]
Code LGTM though I'll leave it to Andrew as to whether or not this is the better approach (I assume it is)

**Comment by Andarist** [comment]
A couple of my merged PRs related to completions are using a similar "double request" technique. One notable difference is that this PR here always performs the double request whereas those other PRs use the second request as a fallback - only if the first one didn't return anything useful.

Out of curiosity, I wonder if:
- this particular test case would work if "the second request" would be performed conditionally (in other words - is "the first request" returning anything here?)
- can we think of a good reason for this completion type here to always use results from both requests if other completion requests perform 2 requests conditionally?
- how does this PR compare with [this PR of mine](https://github.com/microsoft/TypeScript/pull/53996/files) that implements the "double request technique" around the same `getStringLiteralCompletionsFromSignature` (that is transitively touched here)?

**Comment by jakebailey** [comment]
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot pack this

**Comment by Andarist** [comment]
I kinda already answered my own questions:
1. the first request returns `'a' | 'b'` (although those don't end up being actually suggested to the user since they don't match the string in the argument) - so to satisfy this test case we kinda need the second request since it's that request that returns `'b.c'` here
2. I think that it's a valid concern that this PR here **always** performs the "double request" (unlike https://github.com/microsoft/TypeScript/pull/52875 https://github.com/microsoft/TypeScript/pull/53481 and https://github.com/microsoft/TypeScript/pull/53554 ). I'm not saying that it's incorrect - it's just inconsistent and might lead to different results based on the position associated with the request. This is actually shown in the expected results [here](https://github.com/microsoft/TypeScript/pull/54133/files#diff-4313ede2b6264dfd0889602e013c9181ef7fab479630d0aac2f718477649ceb0R20-R21) (I created a PR with extra tests that targets this PR here, you can also add https://github.com/microsoft/TypeScript/issues/53997 to the issues that this PR here fixes)
3. this is basically answered with 1. I think that my PR might have some nice refactors in it - but that's orthogonal to the issue fixed at hand. My PR doesn't fix the OP's case from https://github.com/microsoft/TypeScript/issues/49680 since it's doing the second request conditionally.

I think that there is a way to avoid the second request here by smartly providing `any` to conditional types (and thus probing both branches of the conditional type). Perhaps that wouldn't be ideal either so maybe "double request at all times" is the way to go here - but I feel like it's not perfect that it only happens here and not in other places.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -1839,17 +1838,41 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         typeHasCallOrConstructSignatures,
     };
 
+    function getCandidateSignaturesForStringLiteralCompletions(call: CallLikeExpression, editingArgument: Node) {
```
Comment (Andarist) [inline src/compiler/checker.ts:1841]: nit: other "double requests" are performed *outside* of the checker - it's the caller's responsibility to "probe" both type of contextual types (with and without inference blocking). Is this a problem? Perhaps that other code should be moved to the checker?

**Comment by rbuckton** [comment]
> * if this particular test case would work if "the second request" would be performed conditionally (in other words - is "the first request" returning anything here?)


> 1. the first request returns `'a' | 'b'` (although those don't end up being actually suggested to the user since they don't match the string in the argument) - so to satisfy this test case we kinda need the second request since it's that request that returns `'b.c'` here

Yes, the first request is returning candidates that result in `"a" | "b"`. It's not that they aren't suggested to the user, they *are* in the suggestions we provide to VS Code. However, it is the editor that is supposed to make the decision whether to filter out suggestions based on what has been typed, not the language service.

> * can we think of a good reason for this completion type here to always use results from both requests if other completion requests perform 2 requests conditionally?

This is the simplest solution to the problem. In essence, we want completions that take into account what the user has already typed, but not to the extent that we filter out valid completions such as those that #48410 addressed. We are also considering a more comprehensive solution long term, but that may require more in-depth change to inference and needs further time for consideration and discussion.

**Review by andrewbranch — APPROVED** [review]
Let’s pull in the extra test cases from @Andarist and then I’m good with this.

**Comment by Andarist** [comment]
@andrewbranch perhaps it would be good to pull this into 5.1? I have some further improvements in mind for this, my tests might very well just get merged as part of those - I'm just waiting for this one to land to start working on a follow-up

**Comment by andrewbranch** [comment]
5.2*

It’s @rbuckton’s PR to merge whenever he’s ready.

**Comment by Andarist** [comment]
Since this PR has conflicts and I was working on the code that created them, I resolved them cause I knew exactly how they should be resolved - but since I can't push to this branch I prepared a PR for you here: https://github.com/microsoft/TypeScript/pull/54668

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -1839,17 +1838,41 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        runWithoutResolvedSignatureCaching(editingArgument, () => getResolvedSignatureWorker(call, candidates, /*argumentCount*/ undefined, CheckMode.IsForStringLiteralArgumentCompletions));
+        for (const candidate of candidates) {
+            candidatesSet.add(candidate);
+        }
+
+        return arrayFrom(candidatesSet);
+    }
+
     function runWithoutResolvedSignatureCaching<T>(node: Node | undefined, fn: () => T): T {
         const containingCall = findAncestor(node, isCallLikeExpression);
```
Comment (Andarist) [inline src/compiler/checker.ts:1864]: This change here just changes the style~ and isn't strictly needed in this PR. I'm refactoring this function in [another  PR](https://github.com/microsoft/TypeScript/pull/54658/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R1830) so I'd like to propose reverting it from here so our PRs don't end up conflicting. In case, you'd be interested in reverting this I prepared a PR for you here: https://github.com/microsoft/TypeScript/pull/54669


```suggestion
        const containingCall = findAncestor(node, isCallLikeExpression);
        const containingCallResolvedSignature = containingCall && getNodeLinks(containingCall).resolvedSignature;
```

**Comment by Andarist** [comment]
@rbuckton friendly 🏓

**Comment by jakebailey** [comment]
Is there anything left to do here? It's got conflicts, but it's approved by two people.

**Comment by Andarist** [comment]
The conflicts are also already resolved [here](https://github.com/microsoft/TypeScript/pull/54668), so to resolve them u can just merge it into this one.

**Comment by andrewbranch** [comment]
I think I’d rather not merge it two days before the stable release. I’ll merge once main is open to 5.4-bound code if Ron doesn’t first.

**Comment by jakebailey** [comment]
Er, 5.2 has already branched off, and the tree is open for 5.3 development; we're in the early stage of the cycle, unless you're worried about cherry picking to the release branch for 5.2 fixes?

**Comment by andrewbranch** [comment]
Are we about to publish 5.2? I thought we were about to publish 5.3. Anyway, if we’ve already branched, we can go 😄

**Comment by andrewbranch** [comment]
> I’ll merge once main is open to 5.4-bound code if Ron doesn’t first

Wait, this is Ron’s PR. I was thinking this was @Andarist’s PR. I’m not going to merge Ron’s PR without Ron. Please ignore everything I’ve said on this thread 🤦

**Comment by Andarist** [comment]
> Wait, this is Ron’s PR. I was thinking this was @Andarist’s PR.

Well, it could have been my PR - if this PR would be a code review comment/request for change and not a competing PR to the one that I created earlier. 🤷‍♂️ I don't want to be snarky - it's just quite frustrating that an approved PR like this "missed the train" for the 5.2 release when it was already approved *before* 5.1 was even officially published.

**Comment by rbuckton** [comment]
I'm updating the PR, but it may have been broken by some of the changes in #53996 as it's no longer giving the expected results. I'm working out what the issue is and will post an update once that's been resolved.

**Comment by Andarist** [comment]
> That PR lists 5000+ file changes and is too large for GitHub to render in the UI, so I'm not sure what changes you may have made.

We can compare that branch directly against `main` ([diff](https://github.com/microsoft/TypeScript/compare/main...8a2405a7b1c65ae7ad4f95a16721746f823cf275)) and manually~/visually compare it with the diff visible here. I only focused on test cases and it seems actually they expected results there are slightly different than here.

The only difference is in [this expectation](https://github.com/microsoft/TypeScript/compare/main...8a2405a7b1c65ae7ad4f95a16721746f823cf275#diff-0ae733b6999a5dc6fc7eab9e21b4a0696ae994be34c4aef7e0f0cd1b07d1333bR34). This is basically the same test case that was introduced in https://github.com/microsoft/TypeScript/pull/53996 and it could be removed from this PR to avoid duplication.

I understand that perhaps the current expactation from this PR might be considered better but it isn't noticeable for the majority of end users. So maybe it's worth landing this PR without fixing it (as the PR's focus was to fix a different case anyway) and to open an issue about it? The expected results are at least consistent right now between both markers (see [here](https://github.com/microsoft/TypeScript/blob/dce7b6d2e7f5390e859ce45ae2bd50f1d68725c9/tests/cases/fourslash/stringCompletionsFromGenericConditionalTypesUsingTemplateLiteralTypes.ts#L31)) and I think that the ideal result is that they always should be the same. The only reason why they are different here is that the code path used for object property values completions is quite different from the code path used for string completions directly at argument positions. It's not because they *should* behave differently - they just happen to behave differently (maybe because it's a design limitation since it might be more complex to do what argument completions do within objects but still).

**Comment by rbuckton** [comment]
I had to make other changes than what you've illustrated to get the expectations from the tests I added to pass, reverting a number of places where `CheckMode.IsForStringLiteralArgumentCompletions` was dropped in checker, but I have something that's working now.

**Comment by rbuckton** [comment]
Or not, it looks like it's still not quite correct.

File: tests/cases/fourslash/stringLiteralCompletionsFromGenericConditionalTypesUsingTemplateLiteralTypes.ts
Comment (Andarist) [inline tests/cases/fourslash/stringLiteralCompletionsFromGenericConditionalTypesUsingTemplateLiteralTypes.ts:1]: this file can be removed since this test already got its way to the `main` branch:
https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/stringCompletionsFromGenericConditionalTypesUsingTemplateLiteralTypes.ts

**Comment by Andarist** [comment]
That's interesting! It turns out that for this one test the `wildcardType` used in place of a blocked string performed better. I had to replace it with `blockedStringType` just 4 days ago (and my merge didn't include this change), see https://github.com/microsoft/TypeScript/pull/55552 .

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -1834,22 +1831,47 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
 
-    function runWithoutResolvedSignatureCaching<T>(node: Node | undefined, fn: () => T): T {
-        const cachedSignatures = [];
-        while (node) {
-            if (isCallLikeExpression(node)) {
-                const nodeLinks = getNodeLinks(node);
-                const resolvedSignature = nodeLinks.resolvedSignature;
-                cachedSignatures.push([nodeLinks, resolvedSignature] as const);
-                nodeLinks.resolvedSignature = undefined;
+    function getCandidateSignaturesForStringLiteralCompletions(call: CallLikeExpression, editingArgument: Node, checkMode = CheckMode.IsForStringLiteralArgumentCompletions) {
```
Comment (Andarist) [inline src/compiler/checker.ts:1834]: This can be simplified a little because now this function is capable of doing the "double request" for completions but that has been conditionally already done in `stringCompletions.ts`. So now we can simplify the code in there and rely solely on what you introduced here.

To illustrate what I exactly mean I prepared a small PR targeting this one: https://github.com/microsoft/TypeScript/pull/55624

**Comment by Andarist** [comment]
> I had to make other changes than what you've illustrated to get the expectations from the tests I added to pass, reverting a number of places where CheckMode.IsForStringLiteralArgumentCompletions was dropped in checker, but I have something that's working now.

I managed to get it working again without those reverts. The proposed change also brings back your expected results for the 
[stringCompletionsFromGenericConditionalTypesUsingTemplateLiteralTypes](https://github.com/Andarist/TypeScript/commit/26c1127bff6bdb213ee2fd6a7eba9f17bc4eebae#diff-13616dfe7e35d3a34aa70b8e355f0780be2b218657e04c8561c3833a44733cd5R31-R32) test case. The changes can be found on my [Andarist:get-rid-off-for-string-literal-arg-completions](https://github.com/Andarist/TypeScript/tree/get-rid-off-for-string-literal-arg-completions) branch which is stacked on top of the simplification from https://github.com/microsoft/TypeScript/pull/55624 . It's best to see those changes in isolation though and this is the commit that tweaks the algorithm: https://github.com/Andarist/TypeScript/commit/26c1127bff6bdb213ee2fd6a7eba9f17bc4eebae#

That change is somewhat significant and perhaps bikesheddable so it might be best to leave it for a follow-up PR that I can open once this one lands.

**Comment by rbuckton** [comment]
@Andarist:
> That change is somewhat significant and perhaps bikesheddable so it might be best to leave it for a follow-up PR that I can open once this one lands.

The change in https://github.com/Andarist/TypeScript/commit/26c1127bff6bdb213ee2fd6a7eba9f17bc4eebae doesn't seem too complex, but I agree we can tackle it in a follow-on PR.

@andrewbranch can you take a quick look at this again before I merge?

**Comment by rbuckton** [comment]
@andrewbranch, @jakebailey can one of you take a look over the latest changes?

**Comment by rbuckton** [comment]
I'll fix the merge with checker shortly

**Review by jakebailey — APPROVED** [review]
Still seems good to me.

**Review by andrewbranch — APPROVED** [review]
