### PR TITLE
Fix formatting with non-null assertion operator

### LINKED ISSUE #11676: Incorrect formatting with non-null assertion operator
**TypeScript Version:**  2.0.3

**Expected behavior:**

``` ts
alert()!;
```

**Actual behavior:** 

``` ts
alert() !;
```

### PR DESCRIPTION
**Pull request by flowmemo**
Fixes #11676

Add a new rule `NoSpaceBeforeNonNullAssertionOperator`.

It seems like the rule `SpaceBetweenStatements` causes this bug. At first I tried to remove exclamation mark from RightTokenRange, but it changed the inserting order of rule and broke many tests.

### CODE REVIEW

File: tests/cases/fourslash/formattingNonNullAssertionOperator.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+/// <reference path='fourslash.ts' />
+
+/////*1*/'bar'!;
```
Comment (mhegazy) [inline tests/cases/fourslash/formattingNonNullAssertionOperator.ts]: you want the test input to be unformatted originally.

**Comment by mhegazy** [comment]
merged manually.

File: tests/cases/fourslash/formattingNonNullAssertionOperator.ts (hunk 1 above)
Comment (flowmemo) [inline tests/cases/fourslash/formattingNonNullAssertionOperator.ts]: yes, thanks!
