### PR TITLE
Fix getOccurrences for 'const' modifier with exported & ambient declarations

### LINKED ISSUE #2397: Crash in getOccurrences for const enum
```ts
module M {
    export const enum E { }
}
```
Try to find occurrences for the const keyword:

Error: Debug Failure. False expression: 
   at assert (:1190:17)
   at fail (:1195:13)
   at getFlagFromModifier (:30067:29)
   at getModifierOccurrences (:30022:17)
   at getOccurrencesAtPosition (:29752:25)
   at Anonymous function (:32234:17)
   at simpleForwardCall (:32043:9)
   at forwardJSONCall (:32057:13)
   at forwardJSONCall (:32088:13)
   at getOccurrencesAtPosition (:32233:13)

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #2397.

### CODE REVIEW

File: src/services/utilities.ts [hunk 1]
```diff
@@ -320,6 +320,17 @@ module ts {
             && (node.getStart() < position && position < node.getEnd()) || (!!node.isUnterminated && position === node.getEnd());
     }
 
+    export function isAccessibilityModifier(kind: SyntaxKind) {
```
Comment (CyrusNajmabadi) [inline src/services/utilities.ts]: @internal

**Comment by CyrusNajmabadi** [comment]
:+1:
