### PR TITLE
Fix for jsdoc modifiers on constructor params

### LINKED ISSUE #38401: Regression: JSDoc '@public' comment on constructor parameter affects JS emit
**TypeScript Version:**  3.9.1-rc, 4.0.0-dev

**Search Terms:** jsdoc comment parameter property modifier constructor public private protected readonly

**Code**

```ts
// @allowJS: true
// @checkJS: true
// @out: output.js
// @target: esnext
// @filename: input.js
class C {
	constructor(/** @public */ y) {
	}
}
```

**Expected behavior:**

The emit should be be the following:

```ts
class C {
    constructor(/** @public */ y) {
    }
}
```

**Actual behavior:**

The emit includes a `this` property assignment as if the above declaration was a TypeScript parameter property:

```ts
class C {
    constructor(/** @public */ y) {
        this.y = y;
    }
}
```

**Playground Link:** *NOTE: Cannot repro in the playground as the playground does not support JS output when using JS as the input language*

### PR DESCRIPTION
**Pull request by rbuckton**
When we added support for `@public`, `@private`, `@protected`, `@readonly` JSDoc-style modifiers, we inadvertently treated such modifiers on constructor properties as if they were TypeScript "parameter property modifiers", resulting in comments in a JS source file affecting JS emit.

This PR splits the various "modifier"-related functions into "syntactic" and "effective" forms, where "syntactic" modifiers are derived from syntax, and "effective" modifiers including both the syntactic modifiers as well as modifiers derived from "jsdoc" comments.

Fixes #38401

/cc @DanielRosenwasser, @RyanCavanaugh in case we decide to take this for 3.9.

### CODE REVIEW

File: src/compiler/transformers/declarations.ts [hunk 1]
```diff
@@ -487,7 +487,7 @@ namespace ts {
             | PropertySignature;
 
         function ensureType(node: HasInferredType, type: TypeNode | undefined, ignorePrivate?: boolean): TypeNode | undefined {
-            if (!ignorePrivate && hasModifier(node, ModifierFlags.Private)) {
+            if (!ignorePrivate && hasEffectiveModifier(node, ModifierFlags.Private)) {
```
Comment (sandersn) [inline src/compiler/transformers/declarations.ts:490]: I thought you said earlier that jsdoc wasn't always available during transforms. Did I get that wrong?

File: src/compiler/transformers/declarations/diagnostics.ts [hunk 2]
```diff
@@ -345,7 +345,7 @@ namespace ts {
 
                 case SyntaxKind.MethodDeclaration:
                 case SyntaxKind.MethodSignature:
-                    if (hasModifier(node.parent, ModifierFlags.Static)) {
+                    if (hasEffectiveModifier(node.parent, ModifierFlags.Static)) {
```
Comment (sandersn) [inline src/compiler/transformers/declarations/diagnostics.ts:348]: should this be syntactic like the others in this file? I didn't think that non-syntactic `static` marking was possible.

File: src/compiler/transformers/declarations/diagnostics.ts [hunk 3]
```diff
@@ -413,7 +413,7 @@ namespace ts {
...
```
Comment (sandersn) [inline src/compiler/transformers/declarations/diagnostics.ts:416]: same here

File: src/compiler/types.ts [hunk 4]
```diff
@@ -609,6 +609,7 @@ namespace ts {
         Async =              1 << 8,  // Property/Method/Function
         Default =            1 << 9,  // Function/Class (export default declaration)
         Const =              1 << 11, // Const enum
+        HasComputedJSDocModifiers = 1 << 12, // Indiciates the computed modifier flags include modifiers from JSDoc.
```
Comment (sandersn) [inline src/compiler/types.ts:612]:
```suggestion
        HasComputedJSDocModifiers = 1 << 12, // Indicates the computed modifier flags include modifiers from JSDoc.

```

File: src/services/codefixes/helpers.ts [hunk 5]
```diff
@@ -40,7 +40,7 @@ namespace ts.codefix {
         const scriptTarget = getEmitScriptTarget(context.program.getCompilerOptions());
         const declaration = declarations[0];
         const name = getSynthesizedDeepClone(getNameOfDeclaration(declaration), /*includeTrivia*/ false) as PropertyName;
-        const visibilityModifier = createVisibilityModifier(getModifierFlags(declaration));
+        const visibilityModifier = createVisibilityModifier(getSyntacticModifierFlags(declaration));
```
Comment (sandersn) [inline src/services/codefixes/helpers.ts:43]: this function only works for TS, right? Otherwise we'd need to accept declaration with JSDoc modifiers and produce a node with JSdoc annotations.

File: src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts [hunk 6]
```diff
@@ -34,7 +34,7 @@ namespace ts.codefix {
     }
 
     function symbolPointsToNonPrivateMember(symbol: Symbol) {
-        return !symbol.valueDeclaration || !(getModifierFlags(symbol.valueDeclaration) & ModifierFlags.Private);
+        return !symbol.valueDeclaration || !(getSyntacticModifierFlags(symbol.valueDeclaration) & ModifierFlags.Private);
```
Comment (sandersn) [inline src/services/codefixes/fixClassIncorrectlyImplementsInterface.ts:37]: shouldn't this apply to JSDoc privates too?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -37577,14 +37577,14 @@ namespace ts {
                         break;
 
                     case SyntaxKind.PropertyDeclaration:
-                        if (!hasModifier(parent, ModifierFlags.Static) ||
-                            !hasModifier(parent, ModifierFlags.Readonly)) {
+                        if (!hasSyntacticModifier(parent, ModifierFlags.Static) ||
+                            !hasSyntacticModifier(parent, ModifierFlags.Readonly)) {
```
Comment (sandersn) [inline src/compiler/checker.ts:37581]: shouldn't this check for jsdoc `@readonly`?

File: src/compiler/transformers/declarations.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/transformers/declarations.ts:490]: `parent` isn't always guaranteed during transformations so its unsafe to rely on. In this case, we are generating declarations directly from the parse tree, so `node` *should* have addressable jsdoc and that jsdoc (if it exists) will inform decisions about whether to include syntactic modifiers on the declaration output (which we would want in this case).

File: src/compiler/transformers/declarations/diagnostics.ts (hunk 2 above)
Comment (rbuckton) [reply src/compiler/transformers/declarations/diagnostics.ts:348]: It should be, but it doesn't matter too much here. "effective" modifiers include syntactic modifiers, though I've tried to limit the cases where I call `hasEffectiveModifier` et al when there's no need to do the extra computation for jsdoc modifiers. I'll fix this case.

File: src/services/codefixes/helpers.ts (hunk 5 above)
Comment (rbuckton) [reply src/services/codefixes/helpers.ts:43]: Its possible this could be used when implementing an interface inferred from a JS class:
```ts
// foo.js
export class C { /** @readonly */ x = 1; }
// bar.ts
import { C } from "./foo";
class D implements C { // <- code fix to implement interface should add `readonly`
}
```

I'll switch this to use `getEffectiveModifierFlags`.

File: src/compiler/checker.ts (hunk 7 above)
Comment (rbuckton) [reply src/compiler/checker.ts:37581]: This is a grammar check for `unique symbol`, which doesn't seem to be executed for this case anyways:
```ts
// @ts-check
class C {
    /** 
     * @type {unique symbol} // ERROR: 'unique symbol' types are not allowed here.
     */
    static x;
}
```

It doesn't work currently because `checkGrammarTypeOperatorNode` only walks up parenthesized types on the parent, but doesn't walk up JSDoc types currently. We might want to fix this but it may be in a separate issue/PR?

Comment (rbuckton) [reply src/compiler/checker.ts:37581]: The fix is small enough I can add it to this as well.

**Comment by rbuckton** [comment]
I've updated based on feedback.

**Comment by rbuckton** [comment]
@sandersn can you take another look?
