### PR TITLE
Fix super in down-level async method

### LINKED ISSUE #10862: Nightly: super calls are not working
**TypeScript Version:**  nightly (2.0.0-dev.20160912)

**Code**
```ts
class Base {
  protected frob() { }
}

class Derived extends Base {
  protected frob() {
    super.frob();
  }
}
```

**Expected behavior:** Working code ;)

**Actual behavior:** When compiled for ES5, crash with _Unable to get property 'call' of undefined or null reference._
Generated code in Derived:
```ts
  _super.frob.call(this);
```
The problem seems to be that `_super` is `Base` instead of `Base.prototype`, where `frob` is (correctly) found.

I don't know if this makes a difference, but `frob` actually was `async ` methods in our codebase.

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes an issue with the emit for super property calls in async methods for down-level (ES5/3) async functions.

Fixes #10862

// CC: @mhegazy, @vladima

### CODE REVIEW

File: src/compiler/transformers/es6.ts [hunk 1]
```diff
@@ -414,13 +420,16 @@ namespace ts {
...
+                    case SyntaxKind.FunctionExpression:
                     case SyntaxKind.Constructor:
                     case SyntaxKind.MethodDeclaration:
                     case SyntaxKind.GetAccessor:
                     case SyntaxKind.SetAccessor:
                     case SyntaxKind.FunctionDeclaration:
-                    case SyntaxKind.FunctionExpression:
                         containingNonArrowFunction = <FunctionLikeDeclaration>currentParent;
+                        if (!(containingNonArrowFunction.emitFlags & NodeEmitFlags.AsyncFunctionBody)) {
+                            superScopeContainer = containingNonArrowFunction;
```
Comment (mhegazy) [inline src/compiler/transformers/es6.ts]: we will have to do this for generators as well, correct?

Comment (rbuckton) [inline src/compiler/transformers/es6.ts]: We will cross that bridge when we get to it.

**Comment by vladima** [comment]
:+1:
