### PR TITLE
fix(50551): Destructuring assignment with var bypasses "variable is used before being assigned" check (2454)

### LINKED ISSUE #50551: Destructuring assignment with `var` bypasses "variable is used before being assigned" check (2454)
# Bug Report

### 🔎 Search Terms

- var destructuring used before being assigned
- 2454

### 🕗 Version & Regression Information

- This changed between versions 3.3.3 and 3.5.1
- This is still present for all versions `>= 3.5.1` on TS playground, including Nightly (4.9.0-dev.20220830).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220830#code/GYVwdgxgLglg9mABAcwKZQKoGdUCcAUwAhjADYBciARnHKakWAJSIDeAsAFCKIzCKESpFh249EUABa44Ad0RhU8gKK4ZBAES0ADlg1MA3Fx4BfRKlI42x8bnQhcSVohA5clDTlIwAthsQmRmImXCGcXFC4AJ7WYgBuRLhsLm4BiAC8KOjYePiRIKiGNglJSZlomG55uAVFnGYQRFAQkgJ46iI2EAhYdKgAdO1wBEO4dWHdYL30-TBgwHD4rnj9UHAY2tp4AMJEOPhMdZPTA3ML+GNBXFxAA)

### 💻 Code

```ts
declare function getUser(): {user: string};
try {
  var { user } = getUser();
} catch {
  console.error("error");
}
console.info(user.toUpperCase());
```

### 🙁 Actual behavior

Code above compiles without errors, but crashes at runtime if `getUser` throws since `user` will be `undefined` -- see TS playground for easy reproduction.

⚠️ Additionally, the behaviour is the same for array destructuring.

### 🙂 Expected behavior

I'd expect the following error on the last line:
```
Variable 'user' is used before being assigned. (2454)
```

As shown in the playground, this error is correctly raised if the variable (`r`) is initialized using "regular assigment" instead of destructuring assignment (`user`).

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #50551

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this
@typescript-bot test top100

**Comment by DanielRosenwasser** [comment]
Looks like this breaks valid code and needs some other checks as well. Why this was condition was accounted for, but not tested, is surprising. So we need a test like

```ts
declare const obj: { a?: string, b?: number };
const {
  a = "0",
  b = +a,
} = obj;
```

This should not trigger an error.

**Review by iisaduan — APPROVED** [review]

**Review by gabritto — CHANGES_REQUESTED** [review]
Still trying to figure out what is going on in the checker code to give more precise feedback, but for now maybe you know how to get rid of the error that shouldn't be there that I commented below.

**Comment by gabritto** [comment]
@typescript-bot user test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -26095,7 +26095,7 @@ namespace ts {
             // We only look for uninitialized variables in strict null checking mode, and only when we can analyze
             // the entire control flow graph from the variable's declaration (i.e. when the flow container and
             // declaration container are the same).
-            const assumeInitialized = isParameter || isAlias || isOuterVariable || isSpreadDestructuringAssignmentTarget || isModuleExports || isBindingElement(declaration) ||
+            const assumeInitialized = isParameter || isAlias || isOuterVariable || isSpreadDestructuringAssignmentTarget || isModuleExports ||
```
Comment (gabritto) [inline src/compiler/checker.ts:26098]: Ok, so I investigated  why there was a new error in the `controlFlowInitializedDestructuringVariables` test. What happens is that we're changing `assumeInitialized` from truthy to falsy for the case of `+a`. It used to be that `assumeInitialized` was truthy, because `a`'s declaration is a binding element, and so we didn't add an `| undefined` to `type` when initializing `initialType`... In the end, the type for `a` changed from `string` to `string | undefined` incorrectly. Now, it could be that a fix for this is to, instead of having the `&& !(isBindingElement(declaration) && findAncestor(node, isBindingElement))` below, have a condition in `assumeInitialized` to make it true if the declaration is a binding element with an initializer, but I'm not 100% sure yet if even having that is enough to prevent us from having incorrect errors based on us now thinking a variable in a binding element has type `T | undefined` instead of `T`.

Comment (a-tarasyuk) [reply src/compiler/checker.ts]: Thanks for your review/investigation.

> have a condition in assumeInitialized to make it true if the declaration is a binding element with an initializer

In this case, we will not handle cases like so
```ts
try {
    var [d = 1] = [];
} catch {}

d; // no error because it has an initializer
```

I followed the same logic that `checker` uses for variables because bindings are like variables.

```ts
try {
    var x = "";
} catch {}

x; 

-> assumeInitialized === false
-> type === string
-> initialType === string | undefined
-> flowType === string | undefined
-> !assumeInitialized && !containsUndefinedType(type) && containsUndefinedType(flowType)
    -> ERROR
```

The problem with binding elements is that they can be referenced in the same scope of binding pattern. I've moved that condition to `assumeInitialized`. I've added a custom utility to check this, however, if there is an existing utility to check the same binding scope that I can reuse, I'd be grateful if you could point me to it.

Comment (gabritto) [reply src/compiler/checker.ts]: Ah, I understand the problem now, thanks for explaining that. Yeah, I think your approach is correct then.

**Comment by gabritto** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this
@typescript-bot test top100

**Review by gabritto — APPROVED** [review]
Thanks!

**Comment by gabritto** [comment]
Let's see if the tests are all ok, and then we're good to merge I think.
