### PR TITLE
Fix import statement completions for export= in JS files

### LINKED ISSUE #44830: Inappropriate autocompleting of commonjs modules in React project
Creating a new JavaScript file and then starting to type the import statement autocompletes with commonjs syntax.

Screen Shot 2021-06-24 at 1 12 42 pm

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #44830

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -711,12 +711,12 @@ namespace ts.Completions {
...
             ExportKind.Named;
         const tabStop = preferences.includeCompletionsWithSnippetText ? "$1" : "";
-        const importKind = codefix.getImportKind(sourceFile, exportKind, options);
+        const importKind = codefix.getImportKind(sourceFile, exportKind, options, /*forceImportKeyword*/ true);
         const suffix = useSemicolons ? ";" : "";
         switch (importKind) {
             case ImportKind.CommonJS: return { replacementSpan, insertText: `import ${name}${tabStop} = require(${quotedModuleSpecifier})${suffix}` };
             case ImportKind.Default: return { replacementSpan, insertText: `import ${name}${tabStop} from ${quotedModuleSpecifier}${suffix}` };
-            case ImportKind.Namespace: return { replacementSpan, insertText: `import * as ${name}${tabStop} from ${quotedModuleSpecifier}${suffix}` };
+            case ImportKind.Namespace: return { replacementSpan, insertText: `import * as ${name} from ${quotedModuleSpecifier}${suffix}` };
```
Comment (andrewbranch) [inline src/services/completions.ts:719]: Drive by fix: tabstop is unnecessary in this snippet because you can’t add a comma and import more things after `import * as whatever`

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -564,17 +564,21 @@ namespace ts.codefix {
             : undefined;
     }
 
-    export function getImportKind(importingFile: SourceFile, exportKind: ExportKind, compilerOptions: CompilerOptions): ImportKind {
+    /**
+     * @param forceImportKeyword Indicates that the user has already typed `import`, so the result must start with `import`.
+     * (In other words, do not allow `const x = require("...")` for JS files.)
```
Comment (DanielRosenwasser) [inline src/services/codefixes/importFixes.ts:569]:
```suggestion
     * (In other words, do not provide `const x = require("...")` for JS files.)
```

Comment (DanielRosenwasser) [inline src/services/codefixes/importFixes.ts:569]:
```suggestion
     * @param forceImportKeyword Indicates that the user has already typed `import`, so the result must start with `import`.
     *                           For example, we should not provide `const x = require("...")` for JS files if it is clear that a user is writing an `import`.
```

**Review by DanielRosenwasser — APPROVED** [review]

File: src/services/codefixes/importFixes.ts (hunk 2 above)
Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:569]: I would apply this except it has a bunch of leading spaces?
