### PR TITLE
Skip outer expressions when checking for super keyword in binder

### LINKED ISSUE #20125: code gen depends on types
**TypeScript Version:**  2.6.1

**Code**

```ts
class Foo {
    bar(): void {
        console.log(this.x);
    }
}

class Bar extends Foo {
    x: Number;

    constructor() {
        super();
        this.x = 2;
    }

    bar() {
        super.bar();
        (super.bar as any)();
    }
} 

let b = new Bar();
b.bar()
```

**Expected behavior:**

I expect that the code generated for `super.bar()` and `(super.bar as any)()` behave the same - this code should console.log(2) twice.

**Actual behavior:**

The code logs 2, and then undefined.

The underlying issue is that `super.bar()` and `(super.bar as any)()` compile to different code.  the former compiles to `_super.prototype.bar.call(this);`, but the `as any` changes the compilation to `_super.prototype.bar();`, and so `super.bar` is called with the wrong `this` when the cast is in place.

I was generally under the impression that code generation should be the same whether or not casts were present in the code, so I found this a bit surprising.  that said, it was easy to change my code to avoid this pitfall.

### LINKED ISSUE #21081: Lexical this not captured for super element accessed calls
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
class A { x() {} }

class B extends A {
    constructor() {
        super();
    }
    foo() {
        return () => {
            super["x"]();
        }
    }
}
```

**Expected behavior:**
```js
var A = /** @class */ (function () {
    function A() {
    }
    A.prototype.x = function () { };
    return A;
}());
var B = /** @class */ (function (_super) {
    __extends(B, _super);
    function B() {
        return _super.call(this) || this;
    }
    B.prototype.foo = function () {
        var _this = this;
        return function () {
            _super.prototype["x"].call(_this);
        };
    };
    return B;
}(A));
```

**Actual behavior:**
```js
var A = /** @class */ (function () {
    function A() {
    }
    A.prototype.x = function () { };
    return A;
}());
var B = /** @class */ (function (_super) {
    __extends(B, _super);
    function B() {
        return _super.call(this) || this;
    }
    B.prototype.foo = function () {
        return function () {
            _super.prototype["x"].call(this);
        };
    };
    return B;
}(A));
```

**Related:**
Found while working on #20125; will likely be included in the fix.

### PR DESCRIPTION
**Pull request by weswigham**
This adds transform flags for tracking `Super` and property accesses/element accesses which contain `Super`; enabling us to not need to search the subtree while binding these expressions, but still know if the subtree contains the `super` reference that would indicate that the call expression needs to be sent through the ES2015 transformer (#20125). Additionally, this enabled me to shift which compute function had responsibility for setting the captures lexical this flag, allowing me to correct our behavior in a few cases (#21081).

Fixes #20125
Fixes #21081

### CODE REVIEW

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -2722,8 +2721,9 @@ namespace ts {
         return transformFlags & ~TransformFlags.ArrayLiteralOrCallOrNewExcludes;
     }
 
-    function isSuperOrSuperProperty(node: Node, kind: SyntaxKind) {
-        switch (kind) {
+    function isSuperOrSuperProperty(node: Node) {
+        node = skipOuterExpressions(node);
```
Comment (weswigham) [inline src/compiler/binder.ts]: @rbuckton According to the commit log, `kind` was being passed in here to avoid some kind of polymorphism. If that's the case; would it make sense to continue having `isSuperOrSuperProperty` take the `kind` and `node` directly, and move the call to `skipOuterExpressions` into `computeCallExpression`, or is what I have here (which is more idiomatic considering what we do elsewhere) fine?

Comment (rbuckton) [reply src/compiler/binder.ts]: We would want to have the call to `skipOuterExpressions` in `computeCallExpression`.

Comment (rbuckton) [reply src/compiler/binder.ts]: This was an optimization introduced after reviewing deoptimization data via IRHydra. By only digging into `node` when `kind` indicates a property or element access, we avoid a number of soft-deoptimization hits from looking at both `node.kind` and `node.expression` in the same function.

The most efficient approach which doesn't require traversing the subtree tree again would be to have a `TransformFlags.ContainsSuperOrSuperProperty`. We would then add the flag for `SuperKeyword` and for a property or element access whose `expression` is `SuperKeyword` and reset the flag for all nodes *except* `ParenthesizedExpression`, `AsExpression`, `TypeAssertionExpression`, or `PartiallyEmittedExpression` so that it doesn't leak out of the context where it needs to matter.

Then we only need to interrogate `subtreeFlags` for the answer, which avoids polymorphism and walking the subtree.

If we are running out of `TransformFlags` then it doesn't matter where we put it, since the cost of deoptimization is probably negligible compared to the cost of `skipOuterExpressions` (which likely ends up deoptimized in any case since it is highly polymorphic).

Comment (weswigham) [reply src/compiler/binder.ts]: We have two unused bits left in `TransformFlags`; `27` and `28`, so we can do it. But even as is the next new emit feature that seriously needs transform flags (like, say, proper lexical `arguments`) is already in for a bad time what with there not being enough flags. but I suppose that's a future problem.

**Comment by weswigham** [comment]
@rbuckton Done. This now uses transform flag aggregations for tracking subtrees that contain a `super` keyword or a property access/element access which uses a `super` keyword.

**Comment by mhegazy** [comment]
@rbuckton any more comments?
