### PR TITLE
Fix noUncheckedIndexedAccess with tuple rest types and generic index types

### LINKED ISSUE #40657: noUncheckedIndexedAccess and variadic tuples
**TypeScript Version:**  4.1.0-dev.20200920

**Search Terms:**
- noUncheckedIndexedAccess
- Pedantic Index Signatures
- variadic tuples

**Code**

```ts
type NonEmptyStringArray = [string, ...Array<string>]

const strings: NonEmptyStringArray = ['one', 'two', 'three']

strings[0].toUpperCase()
strings[99].toUpperCase()
```

**Expected behavior:**

`strings[99].toUpperCase()`  should type error

**Actual behavior:**

`strings[99].toUpperCase()` shows no type error

Please note that if you change `const strings` to `Array<string>`, every index access correctly yields a type error.

**Playground Link:**

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.1.0-dev.20200920#code/PTACDsHsFVwYwBYFM4GskBMCS4NIB6YCCccSAzuQFBUAuAngA5IAEAcpOAKIC2jDAZVoAnAJbgA5kWHCAhvRYBeFgG1yI8RIA0LAHT7pc+gB51YyQD4AujTid1LM5vIAudp1796Q81JnylVQByTiQgnSDaAHdIcJZIhGEkMJsqJ0lyFQAGK11aGEZmYQBhWXIkAAoASjSNDJUATgbc-OhCpBKyyqqgA

**Related Issues:**

https://github.com/microsoft/TypeScript/pull/39560

### LINKED ISSUE #40666: `noUncheckedIndexedAccess`: unexpected error when indexing with generic constrained to `keyof`
In the process of enabling the new `noUncheckedIndexedAccess` rule on my project, I came across this interesting error:

```ts
type MyRecord = { a: number; b: string };

declare const myRecord: MyRecord;

declare const key: 'a' | 'b';
const value = myRecord[key]; // string | number ✅

// ❌ Unexpected error
// Type 'MyRecord[Key] | undefined' is not assignable to type 'MyRecord[Key]'
const fn = <Key extends keyof MyRecord>(key: Key): MyRecord[Key] => myRecord[key];
```

In this case I did not expect `myRecord[key]` to return type `MyRecord[Key] | undefined`, because the `key` is constrained to `keyof MyRecord`.

_Originally posted by @OliverJAsh in https://github.com/microsoft/TypeScript/issues/13778#issuecomment-696024937_

### PR DESCRIPTION
**Pull request by andrewbranch**
(each commit fixes a separate bug)

Fixes #40657 
Fixes #40666

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14001,10 +13993,10 @@ namespace ts {
                 const id = objectType.id + "," + indexType.id;
                 let type = indexedAccessTypes.get(id);
                 if (!type) {
-                    indexedAccessTypes.set(id, type = createIndexedAccessType(objectType, indexType, aliasSymbol, aliasTypeArguments));
+                    indexedAccessTypes.set(id, type = createIndexedAccessType(objectType, indexType, aliasSymbol, aliasTypeArguments, accessFlags));
                 }
 
-                return shouldIncludeUndefined ? getUnionType([type, undefinedType]) : type;
+                return type;
```
Comment (andrewbranch) [inline src/compiler/checker.ts:13999]: At this point, we don’t yet know whether the index type will be constrained to something that resolves to property signatures or index signatures, so we can’t return a union with undefined. But when we come back to do the deferred checking of the indexed access type we saved, we’ve lost the `accessFlags` that indicate that this is a position where `undefined` should be included in the type.

As I’m writing this, I’m realizing that this is probably broken for generic indexed access types that get used both for reading and for writing, so converting back to draft.

Comment (andrewbranch) [reply src/compiler/checker.ts]: The only easy way I could find to fix this was creating separate IndexedAccessTypes (and keying the cache) depending on whether it was an expression where `--noUncheckedIndexedAccess` could have an effect or not. So in effect, in

```ts
function<T extends string>(key: T) {
  obj[key] = undefined;
  return obj[key];
}
```

the two usages of `obj[key]` have two separate types. (This only happens when the object type and/or the index type is generic.) I think this is technically possible to avoid, but would involve a _lot_ of inexpedient threading of `accessFlags` (or some parameter based on it) through a bunch of functions.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -13592,12 +13592,13 @@ namespace ts {
...
         }
 
-        function createIndexedAccessType(objectType: Type, indexType: Type, aliasSymbol: Symbol | undefined, aliasTypeArguments: readonly Type[] | undefined) {
+        function createIndexedAccessType(objectType: Type, indexType: Type, aliasSymbol: Symbol | undefined, aliasTypeArguments: readonly Type[] | undefined, shouldIncludeUndefined: boolean) {
             const type = <IndexedAccessType>createType(TypeFlags.IndexedAccess);
             type.objectType = objectType;
             type.indexType = indexType;
             type.aliasSymbol = aliasSymbol;
             type.aliasTypeArguments = aliasTypeArguments;
+            type.noUncheckedIndexedAccessCandidate = shouldIncludeUndefined;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:13601]: Maybe this should just be named `shouldIncludeUndefined`?

Comment (andrewbranch) [reply src/compiler/checker.ts:13601]: I did that at first, but I felt like it was confusing because that’s only true if the type resolves to an index signature. Indexed access types often resolve to an actual property, where they should _not_ include undefined. Happy to hear pithier suggestions that don’t imply the unconditional presence of `undefined` though.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -180,7 +180,7 @@ namespace ts {
         IsForSignatureHelp = 1 << 4,    // Call resolution for purposes of signature help
     }
 
-    const enum AccessFlags {
+    export const enum AccessFlags {
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts:183]: 👀

Comment (andrewbranch) [reply src/compiler/checker.ts]: I moved it to types.ts in one iteration and forgot to un-export it when I moved it back

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by sandersn** [comment]
@andrewbranch is this ready to merge, or is it waiting on a review from @weswigham? I guess it's the latter but I want to make sure.

**Comment by andrewbranch** [comment]
Ryan suggested waiting on a review from @weswigham if possible.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -13971,13 +13973,13 @@ namespace ts {
...
 
-        function getIndexedAccessTypeOrUndefined(objectType: Type, indexType: Type, accessNode?: ElementAccessExpression | IndexedAccessTypeNode | PropertyName | BindingName | SyntheticExpression, accessFlags = AccessFlags.None, aliasSymbol?: Symbol, aliasTypeArguments?: readonly Type[]): Type | undefined {
+        function getIndexedAccessTypeOrUndefined(objectType: Type, indexType: Type, noUncheckedIndexedAccessCandidate?: boolean, accessNode?: ElementAccessExpression | IndexedAccessTypeNode | PropertyName | BindingName | SyntheticExpression, accessFlags = AccessFlags.None, aliasSymbol?: Symbol, aliasTypeArguments?: readonly Type[]): Type | undefined {
             if (objectType === wildcardType || indexType === wildcardType) {
                 return wildcardType;
             }
 
-            const shouldIncludeUndefined =
-                compilerOptions.noUncheckedIndexedAccess &&
+            const shouldIncludeUndefined = noUncheckedIndexedAccessCandidate ||
```
Comment (weswigham) [inline src/compiler/checker.ts:13981]: I find the presedence of this a bit confusing - can we parenthesize the `&&` subexpression? Or am I missing something? I think this the the only place an initial `true` value can be introduced for `noUncheckedIndexedAccessCandidate`, right?

Comment (andrewbranch) [reply src/compiler/checker.ts:13981]: Yeah, it’s kind of weird, but here’s what’s happening: in the first pass of checking nodes in a source file, when we see an element access, we try to get its type with this function, passing `accessFlags` based on the syntax where we found it. If the `objectType` and `indexType` are non-generic, we can return a fully resolved type right away, and we can mix `undefined` into that if `accessFlags` said it was a reading operation in an expression position and the `indexType` matched an index signature on `objectType` (as opposed to a named property). But if the `objectType` or `indexType` is generic, all we can do is return an IndexedAccessType to be resolved later. The problem is that we don’t know _now_ whether the indexed access type will resolve to an index signature or a named property, and when we come back _later_ we won’t have the `accessFlags` that tell us whether this is a reading position. So we extract the relevant info from the `accessFlags` in the first pass and cache it on the IndexedAccessType. Later, when we have instantiations of the `objectType` and/or `indexType`, we actually call this _same function again_, except we’ve lost the `accessFlags`—but, standing in for them, we have the `noUncheckedIndexedAccessCandidate` property that we cached on the IndexedAccessType. So when this `noUncheckedIndexedAccessCandidate` parameter is true, it actually means “we don’t have the any/all the `accessFlags` anymore, but we previously extracted the relevant info from them, and they indicated that you should include `undefined`.”

This would probably be more clear if the first-pass checking and deferred checking bits were split into two separate function, but there are a good number of call sites so it would be kind of an unwieldy change.

Comment (weswigham) [reply src/compiler/checker.ts:13981]: Right, right - I just think that for this condition writing `a || (b && c)` is more clear than `a || b && c` - the explicit parenthesization (especially when split over 3 lines with a different operator at the end of each line like this) improves clarity, I think. I read this like 3 times and wasn't sure if it was equivalent to `(a || b) && c` (which didn't make sense) at first, before I remember that `&&` was, in fact, higher presedence than `||` (and not equivalent).

**Review by weswigham — APPROVED** [review]
My comment is mostly stylistic - this looks OK implementation-wise (`noUncheckedIndexedAccessCandidate` is super wordy, though 😛 )

**Comment by andrewbranch** [comment]
@weswigham and @DanielRosenwasser both expressed distaste toward the name; I don't like it either, but I like it better than `shouldIncludeUndefined` for the reason I outlined [here](https://github.com/microsoft/TypeScript/pull/40681#discussion_r492910064). Open to suggestions before merging.
