### PR TITLE
Fix incorrectly emitting underscore of imported property

### LINKED ISSUE #4867: Problem with transpiling underscore identifiers
When transpiled using TS 1.6.0-beta, the following ES6:

```javascript
import R from 'ramda/ramda';

const { __, arity, indexOf } = R;
```
...comes out to:

```javascript
var ramda_1 = require('ramda/ramda');
var __ = ramda_1["default"].___, // ...
```

There are two underscores on the left-hand side, but 3 on the right, hence the assignment is undefined.

### PR DESCRIPTION
**Pull request by yuit**
Fix #4867

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -230,9 +230,18 @@ namespace ts {
         return getSourceTextOfNodeFromSourceFile(getSourceFileOfNode(node), node, includeTrivia);
     }
 
+    function prefixWithUnderscoreUnderscore(identifier: string): boolean {
+        if (identifier.length <= 2) {
+            return false;
+        }
+        else {
+            return identifier.charCodeAt(0) === CharacterCodes._ && identifier.charCodeAt(1) === CharacterCodes._ ? true : false;
```
Comment (sandersn) [inline src/compiler/utilities.ts]: I liked the short form better, although putting it in its own function is nice.

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -230,9 +230,18 @@ namespace ts {
         return getSourceTextOfNodeFromSourceFile(getSourceFileOfNode(node), node, includeTrivia);
     }
 
+    function prefixWithUnderscoreUnderscore(identifier: string): boolean {
```
Comment (sandersn) [inline src/compiler/utilities.ts]: maybe name it `shouldPrefixWithUnderscoreUnderscore` instead?

**Comment by sandersn** [comment]
I don't see the tests yet.

File: src/compiler/emitter.ts [hunk 3]
```diff
@@ -3848,7 +3848,7 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
                         // We create a synthetic copy of the identifier in order to avoid the rewriting that might
                         // otherwise occur when the identifier is emitted.
                         index = <Identifier | LiteralExpression>createSynthesizedNode(propName.kind);
```
Comment (vladima) [inline src/compiler/emitter.ts]: add a comment why do we need to unescape the text here

File: src/compiler/utilities.ts (hunk 2 above)
Comment (vladima) [inline src/compiler/utilities.ts]: if you don't like long expression in original code i'd rather add a local variable instead of a function

File: src/compiler/utilities.ts [hunk 4]
```diff
@@ -232,7 +232,8 @@ namespace ts {
 
     // Add an extra underscore to identifiers that start with two underscores to avoid issues with magic names like '__proto__'
     export function escapeIdentifier(identifier: string): string {
-        return identifier.length >= 2 && identifier.charCodeAt(0) === CharacterCodes._ && identifier.charCodeAt(1) === CharacterCodes._ ? "_" + identifier : identifier;
+        const prefixWithUnderscore = identifier.length > 2 && identifier.charCodeAt(0) === CharacterCodes._ && identifier.charCodeAt(1) === CharacterCodes._;
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: prefixedWithUnderscores

Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: Below we use `identifier.length >= 3` so make these align.

**Comment by yuit** [comment]
@DanielRosenwasser @sandersn @vladima any comment?

File: src/compiler/utilities.ts [hunk 5]
```diff
@@ -232,7 +232,8 @@ namespace ts {
 
     // Add an extra underscore to identifiers that start with two underscores to avoid issues with magic names like '__proto__'
     export function escapeIdentifier(identifier: string): string {
-        return identifier.length >= 2 && identifier.charCodeAt(0) === CharacterCodes._ && identifier.charCodeAt(1) === CharacterCodes._ ? "_" + identifier : identifier;
+        const prefixedWithUnderscores = identifier.length >= 3 && identifier.charCodeAt(0) === CharacterCodes._ && identifier.charCodeAt(1) === CharacterCodes._;
```
Comment (rbuckton) [inline src/compiler/utilities.ts]: What is the purpose of changing the comparison from `identifier.length >= 2' to `identifier.length >= 3`? With this change, we won't escape `__a` to `___a`. Is that expected?

File: src/compiler/emitter.ts [hunk 6]
```diff
@@ -3848,7 +3848,11 @@ var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promi
                         // We create a synthetic copy of the identifier in order to avoid the rewriting that might
                         // otherwise occur when the identifier is emitted.
                         index = <Identifier | LiteralExpression>createSynthesizedNode(propName.kind);
-                        (<Identifier | LiteralExpression>index).text = (<Identifier | LiteralExpression>propName).text;
+                        // We need to escape identifier here because when parsing an identifier prefixing with "__"
```
Comment (rbuckton) [inline src/compiler/emitter.ts]: You wrote "escape" here, did you mean "unescape"?

File: src/compiler/utilities.ts (hunk 5 above)
Comment (yuit) [inline src/compiler/utilities.ts]: Thanks @rbuckton  for pointing this out. we don't really need the check any more since we will unescape anyway

**Comment by rbuckton** [comment]
:+1:

**Comment by sandersn** [comment]
:+!:
