### PR TITLE
Class expressions

### LINKED ISSUE #497: Class Expressions
# Introduction

Currently, in TypeScript, we support only one of the two styles of creating classes in ES6 - that of class declarations.  This proposal adds support for the other style, class expressions.  This will fill our support for classes in ES6 and help bring us in alignment with both styles.

# Class Expressions vs Class Declarations
Class expressions work a little differently than class declarations.  Here's a list of the highlights:

* Class expressions have an optional 'BindingIdentifier' or class name.  This allows them to create anonymous classes, or name them, as the programmer sees fit.
* Unlike class declarations, class expressions with a name do not introduce this name to the lexical scope outside of the class.  The class name of a class expression is only visible inside the body of the class expression.
* Unlike class declarations, class expressions would not create named types in the lexical scope outside of the class.  Instead, the named type would only be visible inside the class expression, bound to the class name.  Outside of the class expression, they would have anonymous types with the shape of the constructor function.

Just as with class declarations, class expressions would create a constructor function that can be used to construct instances.  Like class declarations, you may also declare property members and index members, as well as use the constructor parameters.

# Examples

```TypeScript
var Rect = class { 
  area: number;

  constructor(public length: number, public width: number) {
    this.area = this.length * this.width;
  }
}
var rect = new Rect(5, 10);
```
```TypeScript
var MyNode = class Node {
  next: Node;

  set nextNode(node: Node) {
    this.next = node;
  }
  constructor() {  }
}
var node = new MyNode();
var nextNode = new MyNode();
node.nextNode = nextNode;
```
# Emit

Class expressions, just like class declarations, create a constructor function.  We would emit them similarly to how we do now, with the exception that they are not immediately bound to a variable.  Instead, they create the function expression (IIFE) that builds the constructor function, and allows the developer to assign the result of this expression where appropriate.

# Emit of .d.ts

The type emitted for class expressions is the object literal representation of the constructor functions, just as with other anonymous types.  

Class expressions can also introduce recursion in the type literal.  Anonymous types that have possibly recursive components (like the Node example above) will need special treatment, which should be part of a related spec (**Edit:** #517).

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR adds type checking for class expressions, finishing the work started in #2567.

In a class expression, the class name is optional and, if specified, is only in scope in the class expression itself. This is similar to the optional name of a function expression. It is not possible to refer to the class instance type of a class expression outside the class expression, but the type can of course be matched structurally.

Class declarations and class expressions differ as follows:

* A class *declaration* of the form `class C { }` introduces an instance type named `C` and a constructor function named `C` with the type `new () => C`.
* A class *expression* of the form `class C { }` produces a constructor function value of type `new () => C` and introduces an instance type named `C` that is in scope only within the body of the class expression.
* A class *expression* of the form `class { }` produces a constructor function value of type `new () => { ... }` where `{ ... }` is the anonymous instance type of the class expression.

An example:

```typescript
let Point = class {
    constructor(public x: number, public y: number) { }
    public length() {
        return Math.sqrt(this.x * this.x + this.y * this.y);
    }
};
var p = new Point(3, 4);  // p has anonymous class type
console.log(p.length());
```

Fixes #497.

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -579,26 +580,15 @@ namespace ts {
...
-
-        return false;
+        return node && (node.kind === SyntaxKind.GetAccessor || node.kind === SyntaxKind.SetAccessor);
     }
 
     export function isClassLike(node: Node): boolean {
-        if (node) {
-            return node.kind === SyntaxKind.ClassDeclaration || node.kind === SyntaxKind.ClassExpression;
-        }
+        return node && (node.kind === SyntaxKind.ClassDeclaration || node.kind === SyntaxKind.ClassExpression);
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: Can you make this `!!node` so this never returns `undefined`?

File: src/compiler/utilities.ts [hunk 2]
```diff
@@ -579,26 +580,15 @@ namespace ts {
...
-                case SyntaxKind.SetAccessor:
-                    return true;
-            }
-        }
-
-        return false;
+        return node && (node.kind === SyntaxKind.GetAccessor || node.kind === SyntaxKind.SetAccessor);
     }
 
     export function isClassLike(node: Node): boolean {
```
Comment (DanielRosenwasser) [inline src/compiler/utilities.ts]: You can now make this return `node is ClassLikeDeclaration`

File: tests/baselines/reference/generatorTypeCheck55.errors.txt [hunk 3]
```diff
@@ -1,9 +1,12 @@
...
-==== tests/cases/conformance/es6/yieldExpressions/generatorTypeCheck55.ts (1 errors) ====
+==== tests/cases/conformance/es6/yieldExpressions/generatorTypeCheck55.ts (2 errors) ====
     function* g() {
         var x = class C extends (yield) {};
-                      ~
-!!! error TS9003: 'class' expressions are not currently supported.
+                                ~~~~~~~
+!!! error TS2507: Type 'any' is not a constructor function type.
+                                 ~~~~~
+!!! error TS1163: A 'yield' expression is only allowed in a generator body.
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: This appears to be incorrect.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -5939,7 +5949,7 @@ namespace ts {
                 captureLexicalThis(node, container);
             }
 
-            let classNode = container.parent && container.parent.kind === SyntaxKind.ClassDeclaration ? container.parent : undefined;
+            let classNode = isClassLike(container.parent) ? container.parent : undefined;
             if (classNode) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You don't need classNode anymore; just do

```TypeScript
if (isClassLike(container.parent)) {
    let classExprSymbol = getSymbolOfNode(container.parent);
    // ...
}

File: src/compiler/utilities.ts (hunk 1 above)
Comment (ahejlsberg) [inline src/compiler/utilities.ts]: There's no need to, `undefined` is just as good.

File: tests/baselines/reference/generatorTypeCheck55.errors.txt (hunk 3 above)
Comment (mhegazy) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: @DanielRosenwasser why are you saying this is not correct?

File: tests/baselines/reference/classExpression3.js [hunk 5]
```diff
@@ -0,0 +1,38 @@
+//// [classExpression3.ts]
+let C = class extends class extends class { a = 1 } { b = 2 } { c = 3 };
```
Comment (mhegazy) [inline tests/baselines/reference/classExpression3.js]: can we add a `--target ES6` for this one

**Comment by mhegazy** [comment]
:+1:

File: tests/baselines/reference/generatorTypeCheck55.errors.txt (hunk 3 above)
Comment (DanielRosenwasser) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: This is in a generator body, and I'm not seeing *Yield* getting turned off in this grammar:

> <span id="sec-14.5" class="secnum">[14.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions "link to this section")</span> Class Definitions
======================================================================================================================================================================

> Syntax
------

> *ClassDeclaration*<sub>\[Yield, Default\]</sub> <span class="geq">:</span>

> &nbsp;&nbsp;&nbsp;`class` *BindingIdentifier*<sub>\[?Yield\]</sub> *ClassTail*<sub>\[?Yield\]</sub>

> &nbsp;&nbsp;&nbsp;<span class="grhsannot">\[+Default\]</span> `class` *ClassTail*<sub>\[?Yield\]</sub>

> *ClassExpression*<sub>\[Yield\]</sub> <span class="geq">:</span>

> &nbsp;&nbsp;&nbsp;`class` *BindingIdentifier*<sub>\[?Yield\]opt</sub> *ClassTail*<sub>\[?Yield\]</sub>

> *ClassTail*<sub>\[Yield\]</sub> <span class="geq">:</span>

> &nbsp;&nbsp;&nbsp;*ClassHeritage*<sub>\[?Yield\]opt</sub> `{` *ClassBody*<sub>\[?Yield\]opt</sub> `}`

> *ClassHeritage*<sub>\[Yield\]</sub> <span class="geq">:</span>

> &nbsp;&nbsp;&nbsp;`extends` *LeftHandSideExpression*<sub>\[?Yield\]</sub>

Comment (DanielRosenwasser) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: We can always turn this into a separate issue.

Comment (DanielRosenwasser) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: Actually, we should error, but for a different reason (i.e. `yield` has type `any` here)

Comment (DanielRosenwasser) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: Actually, I think this is fine because we're only expecting a *LeftHandSideExpression* which doesn't seem to include yield expressions.

Comment (CyrusNajmabadi) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: This is an example where a class expression is extending a parenthesized expression, not a yield expression.

Also, I would expect this to work.  The grammar states this:

ClassHeritage[Yield] :

   extends LeftHandSideExpression[?Yield]
So in this case we are supposed to pass along the ‘yield context’ when parsing the extends expression.

        -- Cyrus

Comment (JsonFreeman) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: @DanielRosenwasser @mhegazy @CyrusNajmabadi 
You're correct that this is allowed in Ecmascript, but we explicitly decided to disallow it in Typescript because it doesn't seem like a good thing to do.

Comment (JsonFreeman) [inline tests/baselines/reference/generatorTypeCheck55.errors.txt]: And ditto for a class decorator like `@(yield)`

**Comment by xLama** [comment]
Should typeof operator works with class expressions?

```
var B = class {}
function foo(a:typeof B):void{} // Error
foo( new B() );
```

**Comment by ahejlsberg** [comment]
@xLama It works, but `typeof B` is the type of the constructor function, not the instance type that the constructor function returns. So:

```typescript
var B = class {}
function foo(a:typeof B):void{}
foo(B);  // Ok
```

**Comment by xLama** [comment]
@ahejlsberg 
So

```
var B = class {}
var b = new B();
function foo(a:typeof b):void{}
foo( new B() );  // Ok
```

**Comment by ahejlsberg** [comment]
@xLama Exactly.
