### PR TITLE
Consider a symbol visible for declaration emit when it is the target of an ambient module's export=

### LINKED ISSUE #47614: Error when generating definition from javascript (error TS9006)
# Bug Report
Hi,
our goal is to generate definition from javascript files.It will be helpful for checking types and have completion.

Our workspace environmnent is a multi project that declare project dependencies using references property in tsconfig. 

It is stopped in our case with this error TS9006: Declaration emit for this file requires using private name 'BaseClass'.

We couldn't find a satisfactory workaround. 

Can we say that it is a limitation of typescript ?

Thanks

### 🔎 Search Terms

 error TS9006: Declaration emit for this file requires using private name

Not sure if this is the same issue as #41672 

### 🕗 Version & Regression Information

No regression. It is something that we started to work on.
The issue is reproducible with typescript 4.5.5 and 4.6.0-beta.

### ⏯ Playground Link

This minimal repo illustrate our case and highlight the issue: 
https://github.com/llgcode/js-def-issue

### 💻 Code

```ts
declare module "deps/BaseClass" {
    class BaseClass {
        static extends<A>(a: A): new () => A & BaseClass;
    }
    export = BaseClass;
}
```
```ts
define("lib/ExtendedClass", ["deps/BaseClass"], 
/**
 * {typeof import("deps/BaseClass")}
 * @param  {typeof import("deps/BaseClass")} BaseClass 
 * @returns 
 */
(BaseClass) => {    
    
    const ExtendedClass = BaseClass.extends({
        f: function() {
            return "something";
        }
    });

    // Exports the module in a way tsc recognize class export 
    const module = {};
    module.exports = ExtendedClass
    return module.exports;
});

```

### 🙁 Actual behavior

```
ExtendedClass.js:1:1 - error TS9006: Declaration emit for this file requires using private name 'BaseClass' from module '"deps/BaseClass"'. An explicit type annotation may unblock declaration emit.

1 define("lib/ExtendedClass", ["deps/BaseClass"],
  ~~~~~~
```

### 🙂 Expected behavior

Generate the definition file.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #47614

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3981,8 +3981,15 @@ namespace ts {
...
             const candidates = mapDefined(symbol.declarations, d => {
-                if (!isAmbientModule(d) && d.parent && hasNonGlobalAugmentationExternalModuleSymbol(d.parent)) {
-                    return getSymbolOfNode(d.parent);
+                if (!isAmbientModule(d) && d.parent){
+                    // direct children of a module
+                    if (hasNonGlobalAugmentationExternalModuleSymbol(d.parent)) {
+                        return getSymbolOfNode(d.parent);
+                    }
+                    // export ='d member of an ambient module
+                    if (isModuleBlock(d.parent) && d.parent.parent && resolveSymbol(getSymbolOfNode(d.parent.parent).exports?.get(InternalSymbolName.ExportEquals)) === symbol) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:3990]: This is almost an inlining of `resolveExternalModuleSymbol`, but you omit `getMergedSymbol` (and some logic that I believe is JS-specific merging that wouldn’t run here). Do you need to get the merged symbol of any of these?

Comment (weswigham) [reply src/compiler/checker.ts:3990]: While you're right that some of that cjs stuff will never apply here, you're also right that it's probably better to just use `resolveExternalModuleSymbol`, which it now does.

**Review by andrewbranch — APPROVED** [review]
