### PR TITLE
Classes can extend Javascript constructor functions

### LINKED ISSUE #14253: [Salsa] Allow ES6 classes to extend ES5 constructor functions
```ts
// a.js
function LogicalException (message, status, code) {
  this.message = code ? `${code}: ${message}` : message
}
```

```ts
//b.ts
class DomainException extends LogicalException {} // Error Type (...)=> void is not a constructor function
```

### PR DESCRIPTION
**Pull request by sandersn**
Now ES6 classes can extend ES5 constructor functions, although only those written in a JS file.

Note that you cannot extend *generic* constructor functions, although I wrote a test for it. Making that work is, unfortunately, a lot of work, because construction of generic constructor functions is faked right now&mdash;when you call `new GenericThing(12)`, the checker manually creates a new object type from the one that getJavascriptClassType returns for `GenericThing`. We don't properly create an interface type with a list of inner and outer type parameters, instantiation cache, etc.

@jameskeane proposed that we refactor of javascript constructors to more closely align with the checker's TS use of constructor signatures. Doing this would also enable extension of generic constructor functions (along with more consistency in other places). But it's a big chunk of work, and the utility of this particular feature is only speculative.

Also note that this is *not* a new JSDoc tag to enable ES5 constructor functions to extend classes.

Fixes #14253

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -19952,14 +19958,25 @@ namespace ts {
             return false;
         }
 
-        function getJavaScriptClassType(symbol: Symbol): Type | undefined {
+        function isJavascriptConstructorType(type: Type) {
+            if (type.flags & TypeFlags.Object) {
+                const resolved = resolveStructuredTypeMembers(<ObjectType>type);
+                if (resolved.callSignatures.length === 1) {
+                    const call = resolved.callSignatures[0];
+                    return !!call && isJavascriptConstructor(call.declaration);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: `call` should be non-optional?

**Comment by sandersn** [comment]
CI failed because I need to merge from master and update new uses of some of the case changes I made.
