### PR TITLE
fix(54310): "Move to file" does not eliminate re-export

### LINKED ISSUE #54310: "Move to file" does not eliminate re-export
`greeting.ts`

```ts
export function getHello() {
    return "hello";
}

export function getWorld() {
    return "world";
}

export function getGreeting() {
    return `${getHello()} ${getWorld()}`;
}
```

`basics.ts`

```ts
export function goodbye() {
    return "goodbye!";
}

export {
    getHello,
    getWorld,
    getGreeting
} from "./greeting";
```

Move `getGreeting` to `basics.ts`:

Currently this generates something like this:

```ts
import { getHello, getWorld } from "./greeting";

export function goodbye() {
    return "goodbye!";
}

export {
    getHello,
    getWorld,
    getGreeting
} from "./greeting";
export function getGreeting() {
    return `${getHello()} ${getWorld()}`;
}
```

At this point, the re-export to `getGreeting` needs to be eliminated since it's an error. It's possible that because an import for `getHello` and `getWorld` are also generated, we could just eliminate the `from "./greeting"`, but that's fine if not too.

Ideally the generated code would look like this:

```ts
import { getHello, getWorld } from "./greeting";

export function goodbye() {
    return "goodbye!";
}

export function getGreeting() {
    return `${getHello()} ${getWorld()}`;
}

export {
    getHello,
    getWorld } from "./greeting"
```

or

```ts
import { getHello, getWorld } from "./greeting";

export function goodbye() {
    return "goodbye!";
}

export function getGreeting() {
    return `${getHello()} ${getWorld()}`;
}

export {
    getHello,
    getWorld
};
```

or something similar

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #54310

### CODE REVIEW

File: src/services/refactors/moveToFile.ts [hunk 1]
```diff
@@ -1109,4 +1114,45 @@ function isNonVariableTopLevelDeclaration(node: Node): node is NonVariableTopLev
...
+    const checker = program.getTypeChecker();
+    const sourceExports = new Set<TopLevelDeclarationStatement>();
+    for (const node of toMove.all) {
+        if (isTopLevelDeclarationStatement(node) && hasSyntacticModifier(node, ModifierFlags.Export)) {
+            sourceExports.add(node);
+        }
+    }
+
+    let lastReExport: ExportDeclaration | undefined;
+    for (const node of targetFile.statements) {
```
Comment (andrewbranch) [inline src/services/refactors/moveToFile.ts:1127]: I’m not sure, but I wonder if it would be more efficient to start from `targetFile.symbol.exports`

File: src/services/refactors/moveToFile.ts [hunk 2]
```diff
@@ -1109,4 +1114,45 @@ function isNonVariableTopLevelDeclaration(node: Node): node is NonVariableTopLev
...
+        if (isExportDeclaration(node) && node.moduleSpecifier && isStringLiteralLike(node.moduleSpecifier)) {
+            if (getResolvedModule(targetFile, node.moduleSpecifier.text, getModeForUsageLocation(targetFile, node.moduleSpecifier))
+                && node.exportClause && isNamedExports(node.exportClause) && length(node.exportClause.elements)) {
+                const elements = node.exportClause.elements;
+                const updatedElements = filter(elements, elem => {
+                    const symbol = checker.getSymbolAtLocation(elem.name);
```
Comment (andrewbranch) [inline src/services/refactors/moveToFile.ts:1133]: Pretty sure this is just `elem.symbol` since an `ExportSpecifier` is a `Declaration`

File: src/services/refactors/moveToFile.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/refactors/moveToFile.ts]: I've changed to `targetFile.symbol.exports`

Comment (andrewbranch) [reply src/services/refactors/moveToFile.ts]: What do you think? Does this seem better? Worse? About the same? 😄

Comment (a-tarasyuk) [reply src/services/refactors/moveToFile.ts]: While there are advantages to operating with precisely exported symbols, we still need to search for export declarations and avoid unnecessary repetition when navigating to the same declarations. This is particularly important in cases like this: `export { a, b, c } from './a'`;

Comment (andrewbranch) [reply src/services/refactors/moveToFile.ts]: I think we should optimize for the case where this new code does nothing—most of the time, move to file won’t need to delete a re-export. By starting from `targetFile.symbol.exports`, I feel like you can now add a fast path to do nothing by comparing string names, before needing to do alias resolution. If we look at Daniel’s test case again where we move `getGreeting` to `basics.ts`:

`greeting.ts`

```ts
export function getHello() {
    return "hello";
}

export function getWorld() {
    return "world";
}

export function getGreeting() {
    return `${getHello()} ${getWorld()}`;
}
```

`basics.ts`

```ts
export function goodbye() {
    return "goodbye!";
}

export {
    getHello,
    getWorld,
    getGreeting
} from "./greeting";
```

I would expect us to be able to do something like this:

1. Collect names that are exported in the code to move: `["getGreeting"]`
2. For each of those, check `!!targetFile.exports.get(exportName)`. If the name isn’t already exported, we don’t need to do anything. If it is, then we need to do alias resolution to see if it refers to the same thing we’re moving.

Does that make sense or am I forgetting something important?

**Review by andrewbranch — APPROVED** [review]
Thanks @a-tarasyuk!

**Comment by sandersn** [comment]
@andrewbranch are you waiting on a second reviewer to merge this?

**Comment by andrewbranch** [comment]
I think that would be good.

**Comment by a-tarasyuk** [comment]
@navya9singh Could you please review this PR?

**Review by jakebailey — APPROVED** [review]
