### PR TITLE
Unify JSX And Normal Call Checking Codepaths

### LINKED ISSUE #27385: JSX takes apparent type of props for SFCs but not for component classes??
This bug underlies some of the confusion in https://stackoverflow.com/q/52525133 .

**TypeScript Version:**  master (0a97663843e11f745d9998d54db0970ee3bfb748)

**Search Terms:** JSX props apparent type parameter constraint SFC stateless function component class

**Code**
```ts
import * as React from "react";

function test<P>() {
    let MySFC = function(props: P) {
        return <>hello</>;
    };
    class MyComponent extends React.Component<P> {
        render() {
            return <>hello</>;
        }
    }
    let x = <MySFC />;  // Actual: compiles OK, unsound
    let y = <MyComponent />;  // Actual: compile error
}
```

**Expected behavior:** Consistent behavior for `x` and `y`.

**Actual behavior:** As marked.

**Playground Link:** N/A, React dependency

**Related Issues:** Taking the apparent type for SFCs was introduced in #15789.  When I revert #15789, I get [a few test failures](https://github.com/Microsoft/TypeScript/compare/master...mattmccutchen:issue-27385) that look like they should be fixable other ways.  I might be willing to try my hand at a PR for this bug if you tell me the right approach.

### LINKED ISSUE #27425: Stateless components and defaultProps bug
**TypeScript Version:**  3.2.0-dev.20180927

**Search Terms:**

**Code**

```ts

interface Props {
  text: string;
}

function BackButton(props: Props) {
  return <div/>
}
BackButton.defaultProps = {
  text: 'Go Back',
};
let a = <BackButton /> // error: text is missing in type {}

```
It works ok with `React.Component`. Also I tried to make `LibraryManagedAttributes<C,P>={c: string}` . This changed checking for `Component`, but not for `SFC`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #27425
Fixes #27385

So. A long time ago, there existed only JSX class elements. Those elements were typechecked with special rules and behaved only slightly like calls - they were handled like any other expression with their own type checking code and everything. Then came stateless function components - these components behaved a lot more like function calls and merited even more special code to typecheck. Then the requests for correct behavior with respect to overloads, generic defaults, and type inference came, along with type arguments for both of the above, and by every metric, both class and stateless components acted very much like calls; but still, they were not checked as function calls (and indeed, they were not even treated similarly to one another).

Now, they are. This _greatly simplifies_ how we check JSX. No longer does JSX have its own unique call; resolution, overload resolution, excess property checking, and language service codepaths. Now all of the normal variants of those (`getResolvedSignature`, `chooseOverload`, `isRelatedTo`, and `getContextualType`) all handle a JSX tag (or JSX-style type/signature) as one might expect (that the tag as a whole is like a function call, while the attributes are like an object literal).

This fixes a few outstanding bugs (listed above) by unifying the class and sfc checking codepaths with the more general signature checking codepaths, however this was not without sacrifice (though warranted). SFCs had this unique ability that, given a tag of type `(props: A) => SFCComponent1 | (props: B) =>  SFCComponent2`, we would check the passed attributes against _every signature_, rather than issue an error on the dissimilar signatures (as we do for other kinds of calls). The functionality was removed, and I believe rightfully so. In the context of contextually typed parameters, this had great potential for breakage, as contextual parameter types are fixed to the nodes once inference is completed. rechecking the same "signature" under multiple types would undoubtedly fail to append any types beyond those from the first signature (see `checkFunctionExpressionOrObjectLiteralMethod` and how it stores a checked flag and fixes types). This functionality should be created via some means like a general solution to #7294 instead, rather than the ad-hoc union-breakdown we were doing before.

Generally, this should be backwards compatible in almost every way; but because I've swapped from ad-hoc-psuedo-overload-resolution to bonafide overload resolution, it's possible that some overload signatures may need to be reordered or modified to continue to function in the intended fashion (I doubt this affects many beyond our test suite, since anyone writing signatures affected by this would be confused as to why writing their SFC as a function call behaved differently than it did as a tag). Previously JSX both skipped the subtype pass _and_ had a strange arity-check-esque rule that wholly overlapped with excess property checking.

Additionally, this process uncovered a small bug in how weak types were checked that impacted some JSX tests once their checking was done correctly which required restructuring how the flag which skips the weak type check was passed down through `isRelatedTo`.

On the minor change list:
* This is technically a breaking API change because I've removed `getAllAttributesTypeFromJsxOpeningLikeElement` from the API, and it was publicly exposed (why?). Anyone using it should just be using `getContextualType` instead, and, if the _exact_ same behavior is needed, if they witness a union return type, convert it into an intersection instead (or, like our language service, handle unions intelligently).
  * The changes associated with this break should also allow prop types' completions to be discriminated, so this should improve the completion experience for JSX, too.
* SFC signature validity checking, by virtue of now using the normal call resolution paths, now uses `checkTypeRelatedToAndOptionallyElaborate`, meaning it can now have deep elaborations appear on SFC argument errors. Previously this'd only happen for class components.
* SFC target types once again include `IntrinsicAttributes` in error messages. They were removed by a small change a few weeks ago that moved where the SFC error was reported within the SFC checking codepath. If we want them gone again, we should implement the more general "skip intersections of only weak types when elaborating" kinda rule we were thinking about before.

### CODE REVIEW

**Comment by weswigham** [comment]
Fun fact: Excluding test changes and new tests, this PR now sits at 227 lines added and 569 lines removed. 😄

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by sandersn** [comment]
Once you fix the JSX excess property checking, it might help #27355 too? I'll try it out.

**Comment by weswigham** [comment]
Nah, #27355 is less an excess property error and more `"Property 'b' will always be overridden by the following spread."`, IMO. The spread type entirely comes from the declared parameter type in that issue, so an excess property error doesn't make too much sense. In any case, I've fixed excess property errors on spreads (namely: they no longer trigger them, as the intent in #19775 indicates).

**Comment by weswigham** [comment]
@typescript-bot test this - the baseline changes show now just be additional error lines (from the intersection returning) or moved errors from improved elaboration.

**Comment by weswigham** [comment]
The RWC changes look mostly known now. There's a few places where the extra line with the intersection of intrinsics was added back, one case where the error was moved to the containing tag name, and one case where someone was using the jsx-can-resolve-unions-of-signatures-unintentionally feature (which, as I stated, is now gone as it's very much not safe to do that way it was being done).

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6988,8 +6983,9 @@ namespace ts {
                 getPropertiesOfObjectType(type);
         }
 
-        function isTypeInvalidDueToUnionDiscriminant(contextualType: Type, obj: ObjectLiteralExpression): boolean {
-            return obj.properties.some(property => {
+        function isTypeInvalidDueToUnionDiscriminant(contextualType: Type, obj: ObjectLiteralExpression | JsxAttributes): boolean {
+            const list = obj.properties as NodeArray<ObjectLiteralElementLike | JsxAttributeLike>;
```
Comment (sandersn) [inline src/compiler/checker.ts]: can ObjectLiteralElementLike be expanded to include JsxAttributeLike, or could we introduce yet another union to unify the two?

Comment (weswigham) [reply src/compiler/checker.ts]: I only need to perform this cast because we can't resolve signatures of unions, so operating on a union of two arrays is impossible.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11547,15 +11540,16 @@ namespace ts {
                         return hasExcessProperties(source, discriminant, /*discriminant*/ undefined, reportErrors);
                     }
                     for (const prop of getPropertiesOfObjectType(source)) {
-                        if (!isPropertyFromSpread(prop, source.symbol) && !isKnownProperty(target, prop.escapedName, isComparingJsxAttributes)) {
+                        if (shouldCheckAsExcessProp(prop, source.symbol) && !isKnownProperty(target, prop.escapedName, isComparingJsxAttributes)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: I would name this Prop*erty*

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -11433,8 +11429,7 @@ namespace ts {
 
                 let result = Ternary.False;
                 const saveErrorInfo = errorInfo;
-                const saveIsIntersectionConstituent = isIntersectionConstituent;
-                isIntersectionConstituent = false;
+                let isIntersectionConstituent = !!isApparentIntersectionConstituent;
```
Comment (sandersn) [inline src/compiler/checker.ts]: I think the new distinction between `isIntersectionConstituent` and `isApparentIntersectionConstituent` is that `isIntersection` is not enclosed in checkTypeRelated, so it only propagates through passing to recursive calls. And `isApparentIntersectionConstituent` *is* enclosed in checkTypeRelated, but doesn't pass recursively.

Is that accurate? The distinction is subtle and warrants some explanation and/or renaming of variables because it'll be hard to reconstruct the design by reading the code later.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -20331,6 +19958,75 @@ namespace ts {
...
+                [createParameter(/*decorators*/ undefined, /*modifiers*/ undefined, /*dotdotdot*/ undefined, "props", /*questionMark*/ undefined, nodeBuilder.typeToTypeNode(result, node))],
+                returnNode ? createTypeReferenceNode(returnNode, /*typeArguments*/ undefined) : createKeywordTypeNode(SyntaxKind.AnyKeyword)
+            );
+            const parameterSymbol = createSymbol(SymbolFlags.FunctionScopedVariable, "props" as __String);
+            parameterSymbol.type = result;
+            return createSignature(
+                declaration,
+                /*typeParameters*/ undefined,
+                /*thisParameter*/ undefined,
+                [parameterSymbol],
```
Comment (sandersn) [inline src/compiler/checker.ts]: nitpick: This function has so many parameters, it would be easier for me to have a comment on *every* non-identifier argument. Well, at least `1` and `typeSymbol ? ...`.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -17075,7 +17029,7 @@ namespace ts {
                     const hostClassType = getReturnTypeOfSignature(sig);
                     apparentAttributesType = intersectTypes(
                         typeParams
-                            ? createTypeReference(<GenericType>intrinsicClassAttribs, fillMissingTypeArguments([hostClassType], typeParams, getMinTypeArgumentCount(typeParams), isJs))
+                            ? createTypeReference(<GenericType>intrinsicClassAttribs, fillMissingTypeArguments([hostClassType], typeParams, getMinTypeArgumentCount(typeParams), isInJSFile(context)))
```
Comment (sandersn) [inline src/compiler/checker.ts]: this line is too long!

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -17584,15 +17540,16 @@ namespace ts {
...
+        function checkJsxFragment(node: JsxFragment): Type {
+            checkJsxOpeningLikeElementOrOpeningFragment(node.openingFragment);
 
             if (compilerOptions.jsx === JsxEmit.React && (compilerOptions.jsxFactory || getSourceFileOfNode(node).pragmas.has("jsx"))) {
                 error(node, compilerOptions.jsxFactory
                     ? Diagnostics.JSX_fragment_is_not_supported_when_using_jsxFactory
                     : Diagnostics.JSX_fragment_is_not_supported_when_using_an_inline_JSX_factory_pragma);
             }
 
+            checkJsxChildren(node);
```
Comment (sandersn) [inline src/compiler/checker.ts]: so, uhh, we weren't checking children before?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -17929,232 +17836,53 @@ namespace ts {
...
                 //      <CustomTag> Hello World </CustomTag>
-                const intrinsicElementsType = getJsxType(JsxNames.IntrinsicElements, openingLikeElement);
+                const intrinsicElementsType = getJsxType(JsxNames.IntrinsicElements, location);
                 if (intrinsicElementsType !== errorType) {
-                    const stringLiteralTypeName = (<StringLiteralType>elementType).value;
+                    const stringLiteralTypeName = type.value;
                     const intrinsicProp = getPropertyOfType(intrinsicElementsType, escapeLeadingUnderscores(stringLiteralTypeName));
                     if (intrinsicProp) {
-                        return getTypeOfSymbol(intrinsicProp);
+                        const target = getTypeOfSymbol(intrinsicProp);
```
Comment (sandersn) [inline src/compiler/checker.ts]: you can collapse this back to one line, I think.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -19637,6 +19263,7 @@ namespace ts {
             const isTaggedTemplate = node.kind === SyntaxKind.TaggedTemplateExpression;
             const isDecorator = node.kind === SyntaxKind.Decorator;
             const isJsxOpeningOrSelfClosingElement = isJsxOpeningLikeElement(node);
+            const reportErrors = !candidatesOutArray;
```
Comment (sandersn) [inline src/compiler/checker.ts]: I know it's redundant, but it might be more readable to add a reportErrors parameter.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -20331,6 +19958,75 @@ namespace ts {
             return resolveCall(node, callSignatures, candidatesOutArray, isForSignatureHelp, headMessage);
         }
 
+        function createSignatureForJSXIntrinsic(node: JsxOpeningLikeElement, result: Type): Signature {
+            // TODO: Since this builds some nodes for the fake'd up signature, this might be worth caching on the node
+            const namespace = getJsxNamespaceAt(node);
+            const exports = namespace && getExportsOfSymbol(namespace);
+            // TODO: We fake up a SFC signature for each intrinsic, however a more specific per-element signature drawn from the JSX declaration
```
Comment (sandersn) [inline src/compiler/checker.ts]: I would decide what to do about these TODOs and remove them. (I suspect the best thing to do for the second one is just to note that the more-specific signature would be preferable.)

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts]: `isIntersectionConstituent` "propagates" through all calls, but is reset on every visit of `isRelatedTo`, while `isApparentIntersectionConstituent` is an argument used to prevent that reset

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts]: This function has so many parameters that it should just take a configuration object.

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts]: `fillMissingTypeArguments` call lines are _always_ long.

File: src/compiler/checker.ts (hunk 6 above)
Comment (weswigham) [reply src/compiler/checker.ts]: If the attributes type is non-any, they can get checked via their contributions to the attributes type; _however_ we need to ensure they get visited even in the any/error cases, so we do that here.

File: src/compiler/checker.ts (hunk 9 above)
Comment (weswigham) [reply src/compiler/checker.ts]: The TODOs are here to gather some remarks on what y'all think is appropriate. If I had a solid stance I'd have done it. See, I don't know if the nodes _need_ to be cached, since the _signature_ is already cached when this is called via `resolveSignature` and since that signature should be the only handle to those generated nodes, it might not be necessary.

File: tests/baselines/reference/checkJsxChildrenProperty14.errors.txt [hunk 10]
```diff
@@ -48,7 +49,8 @@ tests/cases/conformance/jsx/file.tsx(42,11): error TS2322: Type '{ children: Ele
     // Error
     let k5 = <SingleChildComp a={10} b="hi"><></><Button /><AnotherButton /></SingleChildComp>;
               ~~~~~~~~~~~~~~~
-!!! error TS2322: Type '{ children: Element[]; a: number; b: string; }' is not assignable to type 'SingleChildProp'.
-!!! error TS2322:   Types of property 'children' are incompatible.
-!!! error TS2322:     Type 'Element[]' is not assignable to type 'Element'.
-!!! error TS2322:       Property 'type' is missing in type 'Element[]'.
\ No newline at end of file
+!!! error TS2322: Type '{ children: Element[]; a: number; b: string; }' is not assignable to type 'IntrinsicAttributes & SingleChildProp'.
+!!! error TS2322:   Type '{ children: Element[]; a: number; b: string; }' is not assignable to type 'SingleChildProp'.
```
Comment (sandersn) [inline tests/baselines/reference/checkJsxChildrenProperty14.errors.txt]: I think it was special-case code that got rid of this line in the first place. Is it possible that it just needs to be moved or updated to work again?

File: tests/baselines/reference/contextuallyTypedStringLiteralsInJsxAttributes02.errors.txt [hunk 11]
```diff
@@ -37,26 +41,30 @@ tests/cases/conformance/types/contextualTypes/jsxAttributes/file.tsx(36,44): err
     
     const b0 = <MainButton {...{onClick: (k) => {console.log(k)}}} extra />;  // k has type "left" | "right"
                 ~~~~~~~~~~
-!!! error TS2322: Type '{ extra: true; onClick: (k: "left" | "right") => void; }' is not assignable to type 'LinkProps'.
-!!! error TS2322:   Property 'goTo' is missing in type '{ extra: true; onClick: (k: "left" | "right") => void; }'.
+!!! error TS2322: Type '{ extra: true; onClick: (k: "left" | "right") => void; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
```
Comment (sandersn) [inline tests/baselines/reference/contextuallyTypedStringLiteralsInJsxAttributes02.errors.txt]: same comment here, although I'm not as sure there actually was special-case code.

File: tests/baselines/reference/tsxElementResolution10.errors.txt [hunk 12]
```diff
@@ -18,9 +16,6 @@ tests/cases/conformance/jsx/file.tsx(19,2): error TS2322: Type '{ x: number; ren
     }
     var Obj1: Obj1type;
     <Obj1 x={10} />; // Error, no render member
```
Comment (sandersn) [inline tests/baselines/reference/tsxElementResolution10.errors.txt]: should this still be an error? The comment says so.

File: tests/baselines/reference/tsxElementResolution3.errors.txt [hunk 13]
```diff
@@ -17,4 +17,4 @@ tests/cases/conformance/jsx/file.tsx(12,2): error TS2322: Type '{ w: string; }'
     <span w='err' />;
      ~~~~
 !!! error TS2322: Type '{ w: string; }' is not assignable to type '{ n: string; }'.
-!!! error TS2322:   Property 'n' is missing in type '{ w: string; }'.
\ No newline at end of file
+!!! error TS2322:   Property 'w' does not exist on type '{ n: string; }'.
```
Comment (sandersn) [inline tests/baselines/reference/tsxElementResolution3.errors.txt]: The directionality of this error changed, meaning that maybe source swapped with target. Is that correct?

File: tests/baselines/reference/tsxGenericAttributesType2.errors.txt [hunk 14]
```diff
@@ -1,11 +0,0 @@
-tests/cases/conformance/jsx/file.tsx(4,45): error TS2339: Property 'y' does not exist on type 'IntrinsicAttributes & { x: number; } & { children?: ReactNode; }'.
-
-
-==== tests/cases/conformance/jsx/file.tsx (1 errors) ====
-    import React = require('react');
-    
-    const decorator4 = function <T extends { x: number }>(Component: React.StatelessComponent<T>): React.StatelessComponent<T> {
-        return (props) => <Component {...props} y={"blah"} ></Component>
-                                                ~~~~~~~~~~
-!!! error TS2339: Property 'y' does not exist on type 'IntrinsicAttributes & { x: number; } & { children?: ReactNode; }'.
```
Comment (sandersn) [inline tests/baselines/reference/tsxGenericAttributesType2.errors.txt]: shouldn't this still be an excess property error?

File: tests/cases/fourslash/tsxGoToDefinitionStatelessFunction2.ts [hunk 15]
```diff
@@ -31,10 +31,10 @@
...
 verify.goToDefinition({
-    firstTarget: "thirdSource",
-    secondTarget: "thirdSource",
+    firstTarget: "firstSource",
+    secondTarget: "firstSource",
     thirdTarget: "firstSource",
     fourthTarget: "firstSource",
     fifthTarget: "secondSource",
-    sixthTarget: "thirdSource"
+    sixthTarget: "firstSource"
```
Comment (sandersn) [inline tests/cases/fourslash/tsxGoToDefinitionStatelessFunction2.ts]: I'm probably super confused, but I thought normal overload resolution chose the last overload in error cases. Why does this switch to the first overload here?

File: src/compiler/checker.ts (hunk 8 above)
Comment (weswigham) [reply src/compiler/checker.ts]: It already has an optional `fallbackError` parameter that I'd then need to start providing (as `undefined`) at almost every callsite.

File: tests/baselines/reference/checkJsxChildrenProperty14.errors.txt (hunk 10 above)
Comment (weswigham) [reply tests/baselines/reference/checkJsxChildrenProperty14.errors.txt]: As I mentioned in person, this is a result of bringing SFC checking back into line and doing the right thing - there was no "special case" removing the jsx types from the errors; they just straight up weren't being checked against!

File: tests/baselines/reference/tsxElementResolution10.errors.txt (hunk 12 above)
Comment (weswigham) [reply tests/baselines/reference/tsxElementResolution10.errors.txt]: The argument assignability error suppresses the construction error now. Specifically, since no signature matched the arguments provided, an error signature is returned with an `any`ish return type, which _is_ assignable to `ElementClass`.

File: tests/baselines/reference/tsxElementResolution3.errors.txt (hunk 13 above)
Comment (weswigham) [reply tests/baselines/reference/tsxElementResolution3.errors.txt]: Ehhhhh, not quite. Previous JSX didn't use normal excess-property-checking, and so the normal assignability error would be reported. Excess property errors in the usual codepath are reported at a higher priority than typical assignability errors, while in the old JSX code, excess properties only got checked if the type was otherwise assignable.

File: tests/cases/fourslash/tsxGoToDefinitionStatelessFunction2.ts (hunk 15 above)
Comment (weswigham) [reply tests/cases/fourslash/tsxGoToDefinitionStatelessFunction2.ts]: Nope - when overload resolution completely fails we say the declaration is the first signature - see `createUnionOfSignaturesForOverloadFailure`.
