### PR TITLE
Do not do any reduction (even if it contains any) to the union type when getting contextual type

### LINKED ISSUE #27975: Fail to get contextual type when an index signature exists (2)
**TypeScript Version:**  3.2.0-dev.20181017 (and latest `master`)

**Code**

```ts
interface I {
    [index: number]: any;
    someOtherProperty: number;
}
function f(args: ["a"] | I) {}
f(["a"]);
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts:6:3 - error TS2345: Argument of type '[string]' is not assignable to parameter of type 'I | ["a"]'.
  Type '[string]' is not assignable to type '["a"]'.
    Type 'string' is not assignable to type '"a"'.

6 f(["a"]);
```

**Related Issues:** #27949

Discovered in `ember` on DefinitelyTyped.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #27975
Thanks @weswigham for point to this.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8964,24 +8971,26 @@ namespace ts {
...
+                    case UnionReduction.Literal:
+                        if (includes & TypeFlags.StringOrNumberLiteralOrUnique | TypeFlags.BooleanLiteral) {
+                            removeRedundantLiteralTypes(typeSet, includes);
+                        }
+                        break;
+                    case UnionReduction.Subtype:
+                        removeSubtypes(typeSet);
+                        break;
+                }
+                if (typeSet.length === 0) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: Shouldn't this branch still be outside the new `if (unionReduction !== UnionReduction.None) {` check?

Comment (sheetalkamat) [reply src/compiler/checker.ts]: If types = 0 then its never as done by getUnionTypeFromSortedList because we are adding all the types to typeset when there is no reduction (only removing duplicates)

Comment (weswigham) [reply src/compiler/checker.ts]: Hm, I guess so; only the `never` case can be triggered when there are no reductions going on, and `getUnionTypeFromSortedList` does have a check for exactly that, so I guess it's fine.
