### PR TITLE
Check getCurrentDirectory availability in getEffectiveTypeRoots 

### LINKED ISSUE #9186: Reference-types directive crashes TSServer
Create a TypeScript file with the following contents:
 
```ts
/// <reference types="foo" />
var x;
```

This seems to cause TSServer to crash.

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #9186 
The crash happened because the [`getEffectiveTypeRoots`](https://github.com/Microsoft/TypeScript/blob/a91978e4435a82b8d79405958ed63c2a835df3e6/src/compiler/program.ts#L191) assumes `getCurrentDirectory` for the host. Adding to `ServerHost` solves the problem.

### CODE REVIEW

File: src/server/editorServices.ts [hunk 1]
```diff
@@ -113,6 +113,7 @@ namespace ts.server {
             this.moduleResolutionHost = {
                 fileExists: fileName => this.fileExists(fileName),
                 readFile: fileName => this.host.readFile(fileName),
+                getCurrentDirectory: () => this.host.getCurrentDirectory(),
```
Comment (mhegazy) [inline src/server/editorServices.ts]: this is the tsserver install location, correct? do not see how this can be useful.

**Comment by mhegazy** [comment]
👍
