### PR TITLE
Optimize checking involving large discriminated union types

### LINKED ISSUE #42522: Unexpected slowness initializing large array with discriminated union constituents
# Bug Report

### 🔎 Search Terms

union array initialization performance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried since 3.3. No meaningful perf changes were observed depending on TS version

### ⏯ Playground Link

Too large; here's a spreadsheet

https://docs.google.com/spreadsheets/d/1mk6oEwD8YrycBeSNDX4gaM9rxVULgNB_ljAGrQkned8/edit?usp=sharing

### 💻 Code

Instead of 3 constituents, the actual repro has 500 (this is approximately the number found in the real repro) for each example.

Setup:
```ts
type Action =
 | Action1
 | Action2
 | Action3;

type Action1 = { type: 1, payload: number };
type Action2 = { type: 2, payload: number };
type Action3 = { type: 3, payload: number };
```

### 🙁 Actual behavior

Checking with `--skipLibCheck --strict --extendedDiagnostics`, we see some undesirable perf variances here.

The "`const`" version checks in **0.6s**:
```ts
const p1: Action = { type: 1, payload: 42 };
const p2: Action = { type: 2, payload: 42 };
const p3: Action = { type: 3, payload: 42 };
```

The "basic array" version checks in **1.0s**:
```ts
const test: Action[] = [
    { type: 1, payload: 42 },
    { type: 2, payload: 42 },
    { type: 3, payload: 42 }
];
```

The "poisoned array" version (which is closest to the customer repro) checks in **1.3s**:
```ts
declare const a: Action;
const test: Action[] = [
    a,
    { type: 1, payload: 42 },
    { type: 2, payload: 42 },
    { type: 3, payload: 42 }
];
```

The "array with extra target" version checks in **1.6s**:
```ts
const test: Array<Action | string> = [
    { type: 1, payload: 42 },
    { type: 2, payload: 42 },
    { type: 3, payload: 42 }
];
```

The "unannotated array" version checks in **0.07s** (obviously not a target, but shows that these perf numbers aren't cause by "other work):
```ts
const test = [
    { type: 1, payload: 42 },
    { type: 2, payload: 42 },
    { type: 3, payload: 42 }
];
```

### 🙂 Expected behavior

All of the array cases should be checked *approximately* as fast as the const version, not >2x slower.

Other notes:
 * Using a string discriminant in place of number doesn't change anything
 * The original repro is even larger
 * Timing numbers are on my i7-10700K (i.e. a *very* fast computer by 2021 standards)

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements multiple optimizations:

1) Use constituent maps when checking relations involving large discriminated union types on the target side.
2) Use constituent maps when reducing large discriminated union types that appear as contextual types.
3) Use constituent maps for in control flow analysis involving large discriminated union types.
4) Perform deduplication of structurally equivalent object and array literal element types in array literals.
5) Cache results of subtype reduction when constructing union types.
6) Use discriminant property checks to quickly disqualify types from subtype checks during subtype reduction.

When feasible, constituent maps that map from discriminant unit types to corresponding constituent types are constructed for large union types. These maps allow matching constituents to be quickly identified through simple lookups instead of expensive linear scans. Constituent maps are deemed feasible for unions with 10 or more constituents and less than 25% duplication in discriminant keys. The maps are purely a fast path optimization--all existing logic remains in place with unchanged semantics for cases where the maps don't apply.

The optimizations reduce the check time of the worst case examples from #42522 close to 10x (from 1.6s to 0.18s). Furthermore, the check times for the Compiler-with-unions and Monaco test cases are reduced by 32% and 6% respectively.

Fixes #42522.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this faster

**Comment by amcasey** [comment]
Yammer looks good 👍

**Comment by ahejlsberg** [comment]
Nice 10% reduction in compiler-with-unions check time from using discriminant maps in CFA. Other tests unaffected.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this one more time

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -25203,6 +25203,48 @@ namespace ts {
...
+                const key = getLiteralTypeKey(type);
+                return key ? typeMap.get(key) || (typeMap.set(key, type), type) : type;
+            }
+
+            function getLiteralTypeKey(type: Type): string | undefined {
+                const objectFlags = getObjectFlags(type);
+                if (objectFlags & ObjectFlags.ObjectLiteral) {
+                    const props = getPropertiesOfObjectType(type);
+                    const propTypes = map(props, p => getInternedType(getTypeOfSymbol(p)));
+                    const nameLengths = map(props, p => p.flags & SymbolFlags.Optional ? -(<string>p.escapedName).length : (<string>p.escapedName).length);
```
Comment (weswigham) [inline src/compiler/checker.ts:25232]: As-is, I think this'd intern `{ set a(x: string) {} }` and `{ get a(){ return ""; } }` to the same type, even though the later has a `readonly a`. Maybe just encoding the symbol flags wholesale in the key will be the most future proof thing, and then you can just join the names with `,` and not worry about the name length list thing.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -25203,6 +25203,48 @@ namespace ts {
...
+                    return newTypes !== (<UnionType>type).types ? getUnionType(newTypes) : type;
+                }
+                const key = getLiteralTypeKey(type);
+                return key ? typeMap.get(key) || (typeMap.set(key, type), type) : type;
+            }
+
+            function getLiteralTypeKey(type: Type): string | undefined {
+                const objectFlags = getObjectFlags(type);
+                if (objectFlags & ObjectFlags.ObjectLiteral) {
+                    const props = getPropertiesOfObjectType(type);
```
Comment (weswigham) [inline src/compiler/checker.ts:25230]: I'm *pretty sure* we should sort this in some way, since I think our array ordering will respect the input order (our maps all respect insertion order for iteration at least) - so `{a, b}` and `{b, a}` are going to yield props in differing orders, which'll in turn make differing keys here, but are... essentially the same type? The same as far as we actually reason about anyway.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -25203,6 +25203,48 @@ namespace ts {
...
+                    const propTypes = map(props, p => getInternedType(getTypeOfSymbol(p)));
```
Comment (weswigham) [inline src/compiler/checker.ts:25231]: This is going to more eagerly pull on symbols with deferred types; I'm unsure how often `SymbolFlags.Deferred` arises in places this interning occurs, but perhaps we should respect the deferral flag and, like, just use the symbol ID as the key in those scenarios?

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:25230]: Sorting wouldn't really make a difference because we'd sort by type ID and type IDs for literal types are assigned in order of appearance already. When types are structurally equivalent it's perfectly fine to just pick the first one.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:25231]: We won't pull on anything unless it is marked `ObjectFlags.ObjectLiteral` or `ObjectFlags.ArrayLiteral` and those are never deferred.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:25232]: Yeah, I'll look to make sure we properly preserve that distinction. The name length list is still needed since property names can contain any character, including any separator we might use to separate them.

**Comment by ahejlsberg** [comment]
With latest commits we no longer perform subtype reduction on union types with more than 100 distinct constituents. However, with changes in this PR and others, we _always_ perform primitive literal type reduction and object/array literal deduplication, so the change to not perform subtype reduction really only affects union types with large numbers of distinct object types--which are far less common than union types with large numbers of primitive literal types.

The check time of compiler-with-unions is now more than 30% faster and check time for the Monaco test drops by 6%. Other test suites appear unaffected. This may turn out to be a good change.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
Latest commits introduce caching and discriminant checks in subtype reduction and remove the 100 constituent limit I was experimenting with. Reduction in check time for Compiler-with-unions is now at 32%!

**Comment by armano2** [comment]
hello, i'd like to test this PR with with typescript-eslint can i request a tgz?

@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -21364,6 +21392,82 @@ namespace ts {
...
+                            else if (existing !== unknownType) {
+                                map.set(id, unknownType);
+                                duplicate = true;
+                            }
+                        });
+                        if (!duplicate) count++;
+                    }
+                }
+            }
+            return count >= 10 && count * 2 >= types.length ? map : undefined;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:21425]: To bring this in line with the comments above:

```suggestion
            return count < 10 || types.length < count * 2 ? undefined : map;
```

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -21364,6 +21392,82 @@ namespace ts {
             return result;
         }
 
+        // Given a set of constituent types and a property name, create and return a map keyed by the literal
+        // types of the property by that name in each constituent type. No map is returned if some key property
+        // has a non-literal type or if less than 10 or less than 50% of the constituents have a unique key.
+        // Entries with duplicate keys have unknownType as the value.
+        function mapTypesByKeyProperty(types: Type[], name: __String) {
+            const map = new Map<TypeId, Type>();
+            let count = 0;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:21401]:
```suggestion
            // The count of types with unique keys.
            let count = 0;
```

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -25110,6 +25233,48 @@ namespace ts {
...
+                }
+                const key = getLiteralTypeKey(type);
+                return key ? typeMap.get(key) || (typeMap.set(key, type), type) : type;
+            }
+
+            function getLiteralTypeKey(type: Type): string | undefined {
+                const objectFlags = getObjectFlags(type);
+                if (objectFlags & ObjectFlags.ObjectLiteral) {
+                    const props = getPropertiesOfObjectType(type);
+                    const propTypes = map(props, p => getInternedType(getTypeOfSymbol(p)));
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:25261]: Does this cause us to be any more eager in evaluating method types than before?

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -25110,6 +25233,48 @@ namespace ts {
             return literalType;
         }
 
+        /**
+         * Replaces all references to structurally equivalent object and array literal types in the given list
+         * with references to a single one of those types. The process is applied recursively to properties of
+         * object literals and elements of array literals.
+         */
+        function deduplicateObjectOrArrayLiteralTypes(types: Type[]) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts:25241]: We had discussed issues around circular types in object literal methods/getters in a past design meeting - do those concerns not apply here?

File: src/compiler/checker.ts (hunk 6 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:25261]: No. Method types aren't marked with `ObjectFlags.ArrayLiteral` or `ObjectFlags.ObjectLiteral` so they're not explored and therefore not resolved.

File: src/compiler/checker.ts (hunk 7 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts:25241]: They do not. See my reply above.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
Last commit removes the deduplication code for array literals. With the subtype reduction optimizations, deduplication is less impactful and only affects *very* large array literals of object literals. The Monaco RWC project has one such array literal (58K+ lines) the check time for which drops from 0.4s to 0.2s when deduplicated. That's nice, but given the rarity of array literals of that size, I don't think the added complexity of the deduplication code is justified and I'm merging this PR without it. We can always add it in a separate PR if people feel otherwise.
