### PR TITLE
Does not add a duplicate completion when offering an export which was re-declared as a global

### LINKED ISSUE #32675: Autocompletion doesn't suggest global variables exposed from dependent packages  (regression)
Hiding global variables from autocomplition is very annoying because other candidates make unnecessary import statements (We can't use autocompletion without making them).

**Search Terms:**

**Code**

1. clone https://github.com/falsandtru/spica
1. run `npm i`
1. open index.ts
1. type `asse`
1. suggests 2 candidates of `assert` but doesn't include global one.

Global `assert` is defined here: https://github.com/falsandtru/spica/blob/master/global.test.d.ts#L6

**Expected behavior:**

Suggests global assert and packaged assert.

**Actual behavior:**

Suggests packaged assert twice.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by orta**
Fixes #32675

There are no duplication checks for exported completions, which is typically not a problem, but turns out to be an issue when you are taking a umd global and re-exporting it as a global internally. 

Prior to my patch in completions.ts, this test would raise an error because of duplicate completions in the test. So the test verifies it doesn't crash and includes the assert.

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -1342,9 +1343,12 @@ namespace ts.Completions {
                     }
 
                     const symbolId = getSymbolId(symbol);
-                    symbols.push(symbol);
-                    symbolToOriginInfoMap[symbolId] = origin;
-                    symbolToSortTextMap[symbolId] = SortText.AutoImportSuggestions;
+                    const existingSymbol = findLast(symbols, symbol => symbol.id === symbolId);
```
Comment (orta) [inline src/services/completions.ts]: Maybe there is a better way than the linear lookup on the id of symbols? This is pretty late in the completions call, so it was about ~100 items long in this test. Didn't look like there was an easier way, though maybe I could misuse `symbolToOriginInfoMap` or `symbolToSortTextMap`?

Comment (andrewbranch) [inline src/services/completions.ts]: There’s existing deduplication logic in `getSymbolsFromOtherSourceFileExports` which IIRC maintains O(n) time complexity. I worry about introducing O(n^2) here—hopefully the logic in there can just be tweaked?

Comment (orta) [reply src/services/completions.ts]: Perfect, yes!

Comment (andrewbranch) [reply src/services/completions.ts]: Yeah, check the condition by the comment that says

```ts
// Don't add another completion for `export =` of a symbol that's already global.
// So in `declare namespace foo {} declare module "foo" { export = foo; }`, there will just be the global completion for `foo`.
```

The check that it’s doing isn’t good enough—just because the file is a module doesn’t mean the symbol can’t be global. It seems it doesn’t account for `declare global` _or_ `export as namespace`.

File: src/services/completions.ts [hunk 2]
```diff
@@ -1464,7 +1465,7 @@ namespace ts.Completions {
         }
 
         /**
-         * Gathers symbols that can be imported from other files, deduplicating along the way. Symbols can be “duplicates”
+         * Gathers symbols that can be imported from other files, de-duplicating along the way. Symbols can be "duplicates"
```
Comment (andrewbranch) [inline src/services/completions.ts]: 🤷‍♂ 

image

Comment (orta) [reply src/services/completions.ts]: Haha, I guess code-spell check doesn't have it

Comment (andrewbranch) [reply src/services/completions.ts]: I make up a lot of words but this wasn’t one of them! 😛
