### PR TITLE
Fix bugs: Replace SourceFile if '--noUnusedLabels' changed

### LINKED ISSUE #24292: Unused label error doesn't go away after editing tsconfig
**TypeScript Version:** 2.9.0-dev.20180519

**Code**

**a.ts**
```ts
foo: while (1) {}
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "strict": true,
        //"allowUnusedLabels": true,
    }
}
```

Open both files side-by-side in an editor and uncomment the line in `tsconfig.json`

**Expected behavior:**

The error in `a.ts` goes away.

**Actual behavior:**

The error in `a.ts` sticks around until `a.ts` is changed.
Intersetingly, *deleting* blank lines in `a.ts` doesn't make the error disappear, but *adding* new blank lines does.

### PR DESCRIPTION
**Pull request by andy-ms**
(or similar bindDiagnostics-affecting options)

Fixes #24292

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -8374,4 +8374,37 @@ namespace ts {
...
     }
+
+    export function isJsonEqual(a: unknown, b: unknown): boolean {
+        return a === b || typeof a === "object" && a !== null && typeof b === "object" && b !== null && equalOwnProperties(a as MapLike<unknown>, b as MapLike<unknown>);
+    }
+
+    export function getSourceFileAffectingCompilerOptions(compilerOptions: CompilerOptions): CompilerOptions {
+        const res: CompilerOptions = {};
+        for (const option of optionDeclarations) {
+            if (option.name in compilerOptions && isSourceFileAffectingCompilerOption(option)) {
```
Comment (sheetalkamat) [inline src/compiler/utilities.ts]: Like this! Can we instead put property on option declaration instead. Eg look at `affectsSemanticDiagnostics` in `CommandLineOptionBase`

Comment (sheetalkamat) [reply src/compiler/utilities.ts]: Also `noUnusedLabels` shouldnt need the new sourceFile. Instead it needs to set `affectsSemanticDiagnostics`

Comment (andy-ms) [reply src/compiler/utilities.ts]: It already had `affectsSemanticDiagnostics`, the problem is that the `--noUnusedLabels` error is attached to the `SourceFile#bindDiagnostics` directly during binding.  While `affectsSemanticDiagnostics` seems to only affect `semanticDiagnosticsPerFile`.

File: src/compiler/commandLineParser.ts [hunk 2]
```diff
@@ -441,6 +449,7 @@ namespace ts {
                 type: "string",
                 isFilePath: true
             },
+            affectsSourceFile: true,
```
Comment (sheetalkamat) [inline src/compiler/commandLineParser.ts]: Why ? RootDir and paths shouldn't affect syntaxTree or bindDiagnostics?
Same goes for lib, baseUrl, typeRoots, paths

Comment (andy-ms) [reply src/compiler/commandLineParser.ts]: Those all effect module resolution, and `SourceFile` stores `resolvedModules`.

File: src/compiler/program.ts [hunk 3]
```diff
@@ -490,23 +490,13 @@ namespace ts {
...
-            oldOptions.module !== newOptions.module ||
-            oldOptions.moduleResolution !== newOptions.moduleResolution ||
-            oldOptions.noResolve !== newOptions.noResolve ||
-            oldOptions.jsx !== newOptions.jsx ||
-            oldOptions.allowJs !== newOptions.allowJs ||
-            oldOptions.disableSizeLimit !== newOptions.disableSizeLimit ||
-            oldOptions.baseUrl !== newOptions.baseUrl ||
-            !equalOwnProperties(oldOptions.paths, newOptions.paths)
-        );
+        return !!oldOptions && !isJsonEqual(getSourceFileAffectingCompilerOptions(oldOptions), getSourceFileAffectingCompilerOptions(newOptions));
```
[the remark this answers is not in the document]
Comment (andy-ms) [reply src/compiler/program.ts]: Handled this by adding `affectsSourceFile` to both "alwaysStrict" and "strict".

[the remark this answers is not in the document]
Comment (sheetalkamat) [reply src/compiler/program.ts]: I don't think you need to create separate objects just for comparison, You should just iterate through options and achieve same thing.. Eg. ```compilerOptionsAffectSemanticDiagnostics```

File: src/compiler/commandLineParser.ts [hunk 4]
```diff
@@ -426,6 +434,7 @@ namespace ts {
             // use type = object to copy the value as-is
             name: "paths",
             type: "object",
+            affectsModuleResolution: true,
```
Comment (sheetalkamat) [inline src/compiler/commandLineParser.ts]: While you have added this, could you please change ```changesAffectModuleResolution``` as well to use this instead of manual checks.

File: src/compiler/program.ts (hunk 3 above)
Comment (sheetalkamat) [inline src/compiler/program.ts]: Btw you have option.type to determine if you want to do arrayIsEqualTo or equalOwnProperties or just direct equals check.

Comment (andy-ms) [reply src/compiler/program.ts]: Here's how far I got:
```ts
export function areCompilerOptionsEqual(option: CommandLineOption, a: unknown, b: unknown) {
    switch (option.type) {
        case "boolean":
        case "number":
        case "string":
            return a === b;
        case "list":
            return arraysEqual(a as unknown[], b as unknown[], (aa, bb) => areCompilerOptionsEqual((option as CommandLineOptionOfListType).element, aa, bb));
        case "object":
            return equalOwnProperties(a as MapLike<unknown>, b as MapLike<unknown>, isJsonEqual);
        default:
            something with maps;
    }
}
```
Doesn't seem worth it since I need to call `isJsonEqual` in the nested case anyway, and I need some casts which might not be valid if someone put a wrong value in their tsconfig.

File: src/compiler/commandLineParser.ts (hunk 4 above)
Comment (andy-ms) [reply src/compiler/commandLineParser.ts]: :+1:

File: src/testRunner/unittests/reuseProgramStructure.ts [hunk 5]
```diff
@@ -305,10 +305,10 @@ namespace ts {
             assert.equal(program1.structureIsReused, StructureIsReused.Not);
         });
 
-        it("fails if rootdir changes", () => {
+        it("succeeds if rootdir changes", () => {
```
Comment (andy-ms) [inline src/testRunner/unittests/reuseProgramStructure.ts]: I think this is correct? `rootDir` doesn't affect module resolution, it affects emit.

**Comment by andy-ms** [comment]
Note: Filed issue #27108
