### PR TITLE
fix(41078): Convert to ES6 Class Refactoring removes methods named with quoted properties

### LINKED ISSUE #41078: Convert to ES6 Class Refactoring removes methods named with quoted properties
**TypeScript Version:**  4.0.2

**Search Terms:**
refactoring, class, quoted property

**Code**

```ts
function Test() {
  this.a = 0;
}

Test.prototype["b"] = function () {
  console.log("test");
}
```

**Expected behavior:**
Click on the option to refactor the function to an ES2015 class. The result should be:
```ts
class Test {
  constructor() {
    this.a = 0;
  }
  b() {
    console.log("test");
  }
}
```

**Actual behavior:**
```ts
class Test {
  constructor() {
    this.a = 0;
  }
}
```
The `b` method is entirely gone from the code.

**Playground Link:**
[Minimum reproduction](https://www.typescriptlang.org/play?useJavaScript=true#code/GYVwdgxgLglg9mABAFQKYGcoAoCUiDeAUIiYlABYzoB0AhogLyIAMA3IQL6GFqbUAOAJzhQRAT36oA2gCIARjIC6jRKEiwEiXAWKkICdHAA2qakbgBzLDKgYoMnOy5A)

**Related Issues:** 
None.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41078

### CODE REVIEW

File: tests/cases/fourslash/convertFunctionToEs6Class11.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+////}
+
+verify.codeFix({
+    description: "Convert function to an ES2015 class",
+    newFileContent:
+`class Foo {
+    constructor() {
+        this.a = 0;
+    }
+    static 1() {
```
Comment (sandersn) [inline tests/cases/fourslash/convertFunctionToEs6Class11.ts:18]: TIL this is legal.

File: src/services/codefixes/convertFunctionToEs6Class.ts [hunk 2]
```diff
@@ -243,4 +247,25 @@ namespace ts.codefix {
...
+        if (isNumericLiteral(propName)) {
+            return propName;
+        }
+
+        if (isStringLiteralLike(propName)) {
+            return isIdentifierText(propName.text, compilerOptions.target)
+                ? factory.createIdentifier(propName.text)
+                : isNoSubstitutionTemplateLiteral(propName)
+                    ? factory.createStringLiteral(propName.text, quotePreference === QuotePreference.Single)
+                    : propName;
```
Comment (sandersn) [inline src/services/codefixes/convertFunctionToEs6Class.ts:266]:
```suggestion
            return isIdentifierText(propName.text, compilerOptions.target) ? factory.createIdentifier(propName.text)
                : isNoSubstitutionTemplateLiteral(propName) ? factory.createStringLiteral(propName.text, quotePreference === QuotePreference.Single)
                : propName;
```

File: tests/cases/fourslash/convertFunctionToEs6Class12.ts [hunk 3]
```diff
@@ -0,0 +1,22 @@
+/// <reference path='fourslash.ts' />
+
+// @allowNonTsExtensions: true
+// @Filename: foo.js
+////function Foo() {
+////    this.a = 0;
+////}
+////Foo[`a b c`] = function () {
```
Comment (sandersn) [inline tests/cases/fourslash/convertFunctionToEs6Class12.ts:8]: tryGetPropertyName produces a property name for other template strings with substitutions, right? If so, we need a test for that.

**Review by sandersn — CHANGES_REQUESTED** [review]
Request for a test and a small formatting change

File: tests/cases/fourslash/convertFunctionToEs6Class11.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/convertFunctionToEs6Class11.ts:18]: https://jsfiddle.net/w2htsgpn/

File: tests/cases/fourslash/convertFunctionToEs6Class12.ts (hunk 3 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/convertFunctionToEs6Class12.ts:8]: Do you mean `${x}${y}`?

File: tests/cases/fourslash/convertFunctionToEs6Class11.ts (hunk 1 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/convertFunctionToEs6Class11.ts:18]: https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oQC5iwS2GgEYAKAShQF9VKg

File: tests/cases/fourslash/convertFunctionToEs6Class12.ts (hunk 3 above)
Comment (a-tarasyuk) [reply tests/cases/fourslash/convertFunctionToEs6Class12.ts:8]: @sandersn `tryGetPropertyName` doesn't handle `TemplateExpression` (``${x}``), only `NoSubstitutionTemplateLiteral` (``). There are several reasons why I omitted `TemplateExpression`:
1. `TemplateExpression` is not a valid property/method name, so need to convert `TemplateExpression` to `StringLiteral` like `["text" + x + "text"]() {}`
2. `TemplateExpression` is not included in `symbol.members` ```(`Foo.prototype[`${1}`] = function () {}```, so there are no members to convert
3. Not sure that using expressions as a property/method name is very common.
4. I added handling `NoSubstitutionTemplateLiteral` because it is part of `StringLike`, it is absolutely valid to use ```Foo.prototype[`a b`] = function () {}``` and get method `static "a b"() {}`.

Does that make sense?

Comment (a-tarasyuk) [reply tests/cases/fourslash/convertFunctionToEs6Class12.ts:8]: @sandersn Can we move forward with these changes?

**Comment by sandersn** [comment]
Sorry, I don't think this should go into 4.1 -- I'll merge this on Monday after master switches to 4.2.

**Review by sandersn — APPROVED** [review]
