### PR TITLE
Replace `missingType` with `undefinedType` in the `IndexedAccessTypeNode`'s type

### LINKED ISSUE #51953: Error with `is` assertion when using `exactOptionalPropertyTypes` and indexed fields from another interface
# Bug Report

### 🔎 Search Terms

exactOptionalPropertyTypes
is
assertion

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDLKRYCeA-AFzJZSgDmA3HgL556iSyIoDyADmGAB7EBlwEimMFXRYA2gHJiYEgoC6TQgHotyEEOTQoQqMgDuACwghkAEyH0iV5DCEAbN0LP0JOyVioaek1kPxNfXWVKajBaEEYWNlsIBDc4KBQYAFcQBEERZFBUrOSMAEEPACUIAEcs4AzbfnzRAAohAWFRKgAFdME4NwAeZq6MAD4ASioOlrFgMVGRDCYgA)

### 💻 Code

```ts
interface Test {
  testy?: string;
}

interface Options {
  test: Test['testy'];
  // no error when doing the following
  // test: string;
  // or
  // test?: string;
}

declare function includesAllRequiredOptions(options: Partial<Options>): options is Options;
```

with tsconfig option `"exactOptionalPropertyTypes": true`

### 🙁 Actual behavior

Error:
```txt
src/test.ts:15:84 - error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'Options' is not assignable to type 'Partial<Options>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    Types of property 'test' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.

15 declare function includesAllRequiredOptions(options: Partial<Options>): options is Options;
```

### 🙂 Expected behavior

No error

---

i think this *may* be related to https://github.com/microsoft/TypeScript/issues/51638, though in this case it also happens on typescript 4.8 and nightly

Reproduction Repository & Branch: https://github.com/typegoose/typegoose-testing/tree/typescript49ErrorAssertion

### PR DESCRIPTION
**Pull request by Andarist**
fixes #51953

cc @sandersn

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16856,6 +16856,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 const propType = getTypeOfSymbol(prop);
                 return accessExpression && getAssignmentTargetKind(accessExpression) !== AssignmentKind.Definite ?
                     getFlowTypeOfReference(accessExpression, propType) :
+                    accessNode && isIndexedAccessTypeNode(accessNode) ?
+                    mapType(propType, type => type === missingType ? undefinedType : type) :
```
Comment (sandersn) [inline src/compiler/checker.ts:16860]: this is a good fix for the problem encountered here, and probably for most cases when referencing a single property, but I think it might have undesired effects for cases where the indexType is a union of property names, especially something like `keyof T`.

Am I wrong? Does it still make sense to turn missing into undefined there too? @weswigham I'd like your advice on this.

**Review by sandersn — CHANGES_REQUESTED** [review]
Looks like a good fix for the observed bug, but it might be have undesired effects for other indexTypes.

File: src/compiler/checker.ts (hunk 1 above)
Comment (Andarist) [reply src/compiler/checker.ts:16860]: But even in such cases - we just end up distributing~ the indexType over objectType. Essentially it's the same as `T['a'] | T['b'] | ...`. So the open question is - is there any case for which indexed access type should "transfer" the optionality~ into the target type? The only operation that should do it, that I know of, involved homomorphic mapped types - and in this case, indexed access types are not involved directly.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16856,6 +16856,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                 const propType = getTypeOfSymbol(prop);
                 return accessExpression && getAssignmentTargetKind(accessExpression) !== AssignmentKind.Definite ?
                     getFlowTypeOfReference(accessExpression, propType) :
```
Comment (sandersn) [inline src/compiler/checker.ts:16858]: now that this has multiple entries, can you format it cond-style? Like so:

```ts
return cond1 ? cons2
    : cond2 ? cons2
    : default;
````

Comment (Andarist) [reply src/compiler/checker.ts]: done #prettierwhereareyou 😉

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -16854,8 +16854,8 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
                     }
                 }
                 const propType = getTypeOfSymbol(prop);
-                return accessExpression && getAssignmentTargetKind(accessExpression) !== AssignmentKind.Definite ?
-                    getFlowTypeOfReference(accessExpression, propType) :
+                return accessExpression && getAssignmentTargetKind(accessExpression) !== AssignmentKind.Definite ? getFlowTypeOfReference(accessExpression, propType) :
+                    accessNode && isIndexedAccessTypeNode(accessNode) ? mapType(propType, type => type === missingType ? undefinedType : type) :
```
Comment (weswigham) [inline src/compiler/checker.ts:16858]:
```suggestion
                    accessNode && isIndexedAccessTypeNode(accessNode) && containsMissingType(propType) ? getUnionType([propType, undefinedType]) :

```
should save a lot of unneeded union traversals.

**Review by weswigham — APPROVED** [review]
This looks pretty reasonable to me, but @RyanCavanaugh should probably sign off, since he's probably got the most complete mental model for how `missingType` is supposed to work.

File: src/compiler/checker.ts (hunk 3 above)
Comment (Andarist) [reply src/compiler/checker.ts:16858]: thanks for the tip - I didn't realize that `getUnionType` might deduplicate `missingType` and `undefinedType` like this

**Comment by RyanCavanaugh** [comment]
Sorry, the bot is off the rails. We've asked the team owning it to investigate.

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Review by RyanCavanaugh — APPROVED** [review]
The code seems fine to me; if the test results come back clean we can merge this
