### PR TITLE
Normalize type references before relating them

### LINKED ISSUE #33872: Regression in variance measurements for aliased recursive types: not falling back to structural checks when measuring
### Version. 3.7-beta

**Code**

```ts
export interface CalcObj<O> {
    read: (origin: O) => CalcValue<O>;
}

export type CalcValue<O> = CalcObj<O>;

function foo<O>() {
    const unk: CalcObj<unknown> = { read: (origin: unknown) => unk }
    const x: CalcObj<O> = unk;
}
```

**Expected behavior:**

No error on the assignment to `x`.

**Actual behavior:**

Error. `unknown` is not assignable to `O`. The parameter `O` is being measured as invariant.

This works correctly on 3.6.3 and below. The usual tricks to avoid variance-based comparisons let the assignment pass.

Also, removing the type alias works too:
```ts
export interface CalcObj<O> {
    read: (origin: O) => CalcObj<O>;
}

function foo<O>() {
    const unk: CalcObj<unknown> = { read: (origin: unknown) => unk }
    const x: CalcObj<O> = unk; // fine!
}
```

Probably caused by #33050.

**Playground Link:** [link](https://www.typescriptlang.org/play/?ts=3.7-Beta&ssl=10&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYUwBtsB5AIwCsAeUgPjgG8AoONuKYTAEwApoEAc2QAuOKQCUYwiQBqxAK7BadANzMAvs2ahIsODACeYPDOzyiSlXAC8BYmSor1zdAqTYYCCEjjoIECq8Ekys7Ng+AM7w7gDW0g4UNHFIEADuSAx2jBxc3GL8UEKicCnpSCE2DHFwWuxwEUjRcCAJJEnWdnHqGkA)

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR changes `isRelatedTo` to normalize type references before relating them. This in particular means that deferred type references are be turned into equivalent non-deferred type references before being compared, which reduces the amount of work we do and fixes an issue related to variance measurement of aliased deferred type references.

Fixes #33872.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14240,6 +14240,14 @@ namespace ts {
             return getObjectFlags(source) & ObjectFlags.JsxAttributes && !isUnhyphenatedJsxName(sourceProp.escapedName);
         }
 
+        function getNormalizedType(type: Type, writing: boolean): Type {
```
Comment (weswigham) [inline src/compiler/checker.ts]: How will this function jibe with https://github.com/microsoft/TypeScript/issues/31804 and the associated fix https://github.com/microsoft/TypeScript/pull/32116 - does this function just become recursive?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: We should be able to just move the loop into `getNormalizedType`.

File: tests/baselines/reference/recursiveTypeReferences1.errors.txt [hunk 2]
```diff
@@ -60,7 +60,7 @@ tests/cases/conformance/types/typeRelationships/recursiveTypes/recursiveTypeRefe
     
     const b20: Box2 = 42;  // Error
           ~~~
-!!! error TS2322: Type '42' is not assignable to type 'Box2'.
+!!! error TS2322: Type '42' is not assignable to type 'Box<number | Box2>'.
```
Comment (weswigham) [inline tests/baselines/reference/recursiveTypeReferences1.errors.txt]: :( Is it possible we want to keep the pre-normalized form around for error reporting? Since it might have a nicer alias for us to use?

Comment (ahejlsberg) [reply tests/baselines/reference/recursiveTypeReferences1.errors.txt]: I looked at doing that, but I'm not sure it really is all that valuable. We still display the alias in all other situations, it's only when we're elaborating into the type that we now display structure one level earlier that we would before. I think the few places it affects are just as well served with the change in this PR (which, BTW, is what we used to always do).

**Comment by ahejlsberg** [comment]
RWC tests have a few error baseline changes that I think are fine. Community tests suite changes are preexisting conditions. DT tests suites are clean. No changes in performance. Overall, I think this one is good to do.

File: tests/baselines/reference/recursiveTypeReferences1.errors.txt (hunk 2 above)
Comment (weswigham) [reply tests/baselines/reference/recursiveTypeReferences1.errors.txt]: I know, but we acknowledged that these errors were _better_ - a nice side effect of the recursive alias change. it would be nice if we could keep them.

Comment (ahejlsberg) [reply tests/baselines/reference/recursiveTypeReferences1.errors.txt]: Ok, changed the code to preserve the original type and use it in error reporting if it has an alias.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by weswigham** [comment]
Looking at RWC, it looks like tuple aliases still aren't preserved in errors - is there an elaboration codepath the most recent change missed? (The elaboration in property relations, maybe?)

**Comment by ahejlsberg** [comment]
Actually, we're preserving type aliases in more situations than we did previously.
