### PR TITLE
Fix completion and quick info crash in type parameter in function in type alias

### LINKED ISSUE #4715: Get completions in type parameter of type alias cause an error
```typescript
type constructorType<T1,T2> = new <T1/*completion1*/, /*completion2*/
```
At ```completion1``` and ```completion2``` language service fails to get completions and throws below error messages:

fail_completions_type_alias

### PR DESCRIPTION
**Pull request by yuit**
Fix #4715 and #4616

### CODE REVIEW

File: src/services/services.ts [hunk 1]
```diff
@@ -4247,24 +4247,22 @@ namespace ts {
...
                     }
                     else {
-                        // Type  aliash type parameter
+                        // Type alias type parameter
                         // For example
                         //      type list<T> = T[];  // Both T will go through same code path
-                        let declaration = <TypeAliasDeclaration>getDeclarationOfKind(symbol, SyntaxKind.TypeParameter).parent;
                         displayParts.push(keywordPart(SyntaxKind.TypeKeyword));
                         displayParts.push(spacePart());
                         addFullSymbolName(declaration.symbol);
```
Comment (weswigham) [inline src/services/services.ts]: `declaration` may not be defined here

Comment (yuit) [inline src/services/services.ts]: that is a good point. I will have to come up with different test case when that can happen. My first intuition is that that case should not happen since when we get type parameter, it must be in a declaration. Regardless I will add the case for it

File: src/services/services.ts [hunk 2]
```diff
@@ -4247,28 +4247,30 @@ namespace ts {
...
                 else {
                     // Method/function type parameter
-                    let container = getContainingFunction(location);
-                    if (container) {
-                        let signatureDeclaration = <SignatureDeclaration>getDeclarationOfKind(symbol, SyntaxKind.TypeParameter).parent;
-                        let signature = typeChecker.getSignatureFromDeclaration(signatureDeclaration);
-                        if (signatureDeclaration.kind === SyntaxKind.ConstructSignature) {
-                            displayParts.push(keywordPart(SyntaxKind.NewKeyword));
-                            displayParts.push(spacePart());
+                    let declaration = <Node>getDeclarationOfKind(symbol, SyntaxKind.TypeParameter);
```
Comment (sheetalkamat) [inline src/services/services.ts]: When can declaration be undefined? Would it suffice to assert instead ?

**Comment by mhegazy** [comment]
:+1:

File: src/services/services.ts (hunk 2 above)
Comment (yuit) [inline src/services/services.ts]: I agree that it probably should be assert instead. I will update it

**Comment by weswigham** [comment]
@yuit the failing status on this PR was due to the issue in master - it's fixed now, however to update the status on your PR you'll need to refresh it.

File: src/services/services.ts [hunk 3]
```diff
@@ -4247,28 +4247,31 @@ namespace ts {
...
+                    Debug.assert(declaration !== undefined);
+                    declaration = declaration.parent;
+
+                    if (declaration) {
+                        if (isFunctionLikeKind(declaration.kind)) {
+                            let signature = typeChecker.getSignatureFromDeclaration(<SignatureDeclaration>declaration);
```
Comment (DanielRosenwasser) [inline src/services/services.ts]: This should probably be `

**Comment by yuit** [comment]
@weswigham Thanks for the head up!
