### PR TITLE
Fix class name emit in ES5

### LINKED ISSUE #14945: Incorrect emit es5 class
**TypeScript Version:**  2.3.0-dev.20170321

**Code**

```ts
let Foo: any;
if (1) {
   Foo = class Foo{};
}
```

**Expected behavior:**
```js
"use strict";
var Foo;
if (1) {
    Foo = (function () {
        function Foo() {
        }
        return Foo;
    }());
}
```

**Actual behavior:**
```js
"use strict";
var Foo;
if (1) {
    Foo = (function () {
        function Foo() {
        }
        return Foo_1; // Foo_1 is undefined
    }());
}

```

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes the emit for class names when emitting classes for ES5. 

Fixes #14945

### CODE REVIEW

File: src/compiler/transformers/es2015.ts [hunk 1]
```diff
@@ -3778,16 +3778,42 @@ namespace ts {
...
+            let currentNode = getParseTreeNode(node);
+            if (!currentNode || currentNode === declaration || currentNode.end <= declaration.pos || currentNode.pos >= declaration.end) {
+                // if the node has no correlation to a parse tree node, its definitely not
+                // part of the body.
+                // if the node is outside of the document range of the declaration, its
+                // definitely not part of the body.
+                return false;
+            }
+            const blockScope = getEnclosingBlockScopeContainer(declaration);
+            while (currentNode) {
```
Comment (rbuckton) [inline src/compiler/transformers/es2015.ts]: `findAncestor` doesn't do much to improve this. It's the same number of lines, introduces a new environment record for the closure each time it's called, and doesn't improve readability of the function. There's no apparent performance difference between the two, as far as I can tell.

```ts
        function isPartOfClassBody(declaration: ClassLikeDeclaration, node: Identifier) {
            node = getParseTreeNode(node, isIdentifier);
            if (!node || node.end <= declaration.pos || node.pos >= declaration.end) {
                // if the node has no correlation to a parse tree node, its definitely not
                // part of the body.
                // if the node is outside of the document range of the declaration, its
                // definitely not part of the body.
                return false;
            }
            const blockScope = getEnclosingBlockScopeContainer(declaration);
            return !!findAncestor(node, current => {
                if (current === blockScope || current === declaration) {
                    return "quit";
                }
                if (isClassElement(current) && current.parent === declaration) {
                    // we are in the class body, but we treat static fields as outside of the class body
                    return current.kind !== SyntaxKind.PropertyDeclaration
                        || (getModifierFlags(current) & ModifierFlags.Static) === 0 ? true : "quit";
                }
                return false;
            });
        }
```

Comment (sandersn) [inline src/compiler/transformers/es2015.ts]: Fair enough. If there's no readability benefit then there's no point introducing it.
