### PR TITLE
fix(47597): preProcessFile incorrectly identifies imports in comments after a template literal type

### LINKED ISSUE #30878: preProcessFile doesn't find other imports after template strings
**TypeScript Version:**  3.5.0-dev.20190411

**Search Terms:**
preProcessFile import

**Code**

```ts
const ts = require('typescript');
const output = ts.preProcessFile("`${foo}`; import './test';", true, true);
console.log(output.importedFiles);
```

**Expected behavior:**

`./test` should be listed in `importedFiles` as an entry to the array.

**Actual behavior:**

It doesn't. The array is empty.

Reversing the order works though.

```ts
const ts = require('typescript');
const output = ts.preProcessFile("import './test'; `${foo}`;", true, true);
console.log(output.importedFiles);
```

Note this also happens on dynamic imports too.

```ts
const ts = require("typescript");
const output = ts.preProcessFile("`${foo}`; import('./test');", true, true);
console.log(output.importedFiles);
```

Note that these repros are short for reproducability reasons. Yes, not doing static importing at the top is silly, but I found that from my use case of something similar to this:

```ts
const foo = `${someVariable}.${someOtherVariable}`;
import('./foo').then(m => m.callFunction());
```

You can drill down to having the issue also reproducible with static imports and dynamic imports with promise chaining or `async`, so anything import statement related?

**Playground Link:** 

Replicated in CodeSandbox: https://codesandbox.io/embed/5zqln3nn5n.

**Related Issues:**  None (?)

### LINKED ISSUE #47597: preProcessFile incorrectly identifies imports in comments after a template literal type
# Bug Report

### 🔎 Search Terms

preProcessFile, `ts.preProcessFile`, template literal types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (tried v4.1.5, v4.5.4 and nightly).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/PQKgUAKgEgkgygAnggwgeQEoYKIogGQE0kBxAOU2wBEwADesASwFsAHAewCcAXBEBAIYBnBJwCmAgMa8AZp3bMEAcnFTuSgNx0GIYGG4BPVmIQAxduwQBeBLQAkAbyHdOjAHYBzAL60tocNDIyBQQpBQ4NPS0TGxcvA4kYtxeCHIKyobGALQyYs6aMRw8fIIiADbsACbCABap8opKFdVCNQVRYLpAA)

### 💻 Code

`````ts
/*
THIS IS CORRECTLY IGNORED
```
import * as react from 'react';
```
*/
type Foo = `${string}`;
/**
THIS IS NOT IGNORED
```
import {Get} from 'type-fest';
import * as lodash from 'lodash';
```
*/
`````

Or, as a quick node example:
```
> ts.preProcessFile(`\
... type Foo = \`\${string}\`;
... /**
... \`\`\`
... import {Get} from 'type-fest';
... import * as lodash from 'lodash';
... \`\`\`
... */
... `)
{
  referencedFiles: [],
  typeReferenceDirectives: [],
  libReferenceDirectives: [],
  importedFiles: [
    { fileName: 'type-fest', pos: 50, end: 59 },
    { fileName: 'lodash', pos: 87, end: 93 }
  ],
  isLibFile: false,
  ambientExternalModules: undefined
}
```

### 🙁 Actual behavior

`ts.preProcessFile` parses the `import`s within comments after the template literal type.

### 🙂 Expected behavior

The `import`s within the comment are ignored correctly after the template literal type.

---

Might be related to #30878?
Original report: https://github.com/microsoft/TypeScript-Website/issues/2243

This causes issues with the TS playground because it will over-fetch types based on the pre-process result. This can cause startup delays, esp with packages like `lodash` which have a huge numbers of files to fetch.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47597
Fixes #30878

### CODE REVIEW

File: src/services/preProcess.ts [hunk 1]
```diff
@@ -345,6 +345,23 @@ namespace ts {
...
+                        }
+                        if (scanner.getToken() === SyntaxKind.ImportKeyword) {
+                            tryConsumeImport();
+                        }
+                        if (scanner.getToken() === SyntaxKind.CloseBraceToken) {
+                            scanner.reScanTemplateToken(/*isTaggedTemplate*/ false);
+                            break;
+                        }
+                        scanner.scan();
+                    }
```
Comment (DanielRosenwasser) [inline src/services/preProcess.ts:361]: It'd be good to handle arbitrary nesting of template string interpolations too.

```suggestion
                    let templateDepth = 1;
                    while (templateDepth) {
                        if (scanner.getToken() === SyntaxKind.EndOfFileToken) {
                            break;
                        }
                        else if (scanner.getToken() === SyntaxKind.ImportKeyword) {
                            tryConsumeImport();
                        }
                        else if (scanner.getToken() === SyntaxKind.TemplateHead) {
                            templateDepth++;
                        }
                        else if (scanner.getToken() === SyntaxKind.CloseBraceToken) {
                            const templateToken = scanner.reScanTemplateToken(/*isTaggedTemplate*/ false);
                            if (templateToken === SyntaxKind.TemplateTail) {
                                templateDepth--;
                            }
                        }
                        scanner.scan();
                    }
```

Also consider switching to a `switch`/`case` on `scanner.getToken()`.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

File: src/services/preProcess.ts (hunk 1 above)
Comment (a-tarasyuk) [reply src/services/preProcess.ts]: I’ve added this case to tests

File: src/services/preProcess.ts [hunk 2]
```diff
@@ -345,6 +345,24 @@ namespace ts {
...
+                    loop: while (true) {
+                        switch (scanner.getToken()) {
+                            case SyntaxKind.EndOfFileToken:
+                                break loop;
+                            case SyntaxKind.ImportKeyword:
+                                tryConsumeImport();
+                                break;
+                            case SyntaxKind.CloseBraceToken: {
+                                scanner.reScanTemplateToken(/*isTaggedTemplate*/ false);
+                                break loop;
```
Comment (DanielRosenwasser) [inline src/services/preProcess.ts:358]: Okay, here's where I think this won't work, and really a counter isn't technically enough.

```ts

foo `${ funcCall({ prop: 100 }, import("module")) }`

```

Comment (a-tarasyuk) [reply src/services/preProcess.ts]: @DanielRosenwasser I've added a test for this case
```ts
"foo`${ fn({ a: 100 }, import(\"a\"), `${import(\"b\")}`, import(\"c\"), `${import(\"d\")} foo`, import(\"e\")) }`"
```

Comment (a-tarasyuk) [reply src/services/preProcess.ts]: @DanielRosenwasser Do you have additional cases that need to be covered by tests? I would be grateful if you could point me to them.

File: src/services/preProcess.ts [hunk 3]
```diff
@@ -345,6 +345,42 @@ namespace ts {
                     break;
                 }
 
+                if (scanner.getToken() === SyntaxKind.TemplateHead) {
+                    const stack = [scanner.getToken()];
+                    loop: while (true) {
```
Comment (DanielRosenwasser) [inline src/services/preProcess.ts:350]: Shouldn't this loop be `while (length(stack))`? Otherwise is there a chance that you just start losing import statements?

```ts
let x = `hello ${await import("module").default}`;

import { y } from "some-other-module";
```

Comment (a-tarasyuk) [reply src/services/preProcess.ts:350]: Thanks for the review.

Comment (a-tarasyuk) [reply src/services/preProcess.ts]: @DanielRosenwasser I think the example works correctly for both cases `while (true) {` and `while(length(stack))`. Anyway, I changed to `while (length(stack))`, it looks safer.

Comment (a-tarasyuk) [reply src/services/preProcess.ts]: @DanielRosenwasser Do you have any concerns?

File: src/services/preProcess.ts [hunk 4]
```diff
@@ -345,6 +345,42 @@ namespace ts {
                     break;
                 }
 
+                if (scanner.getToken() === SyntaxKind.TemplateHead) {
+                    const stack = [scanner.getToken()];
+                    loop: while (length(stack)) {
+                        const token = scanner.getToken();
```
Comment (DanielRosenwasser) [inline src/services/preProcess.ts:351]: You're not advancing the scanner after your first call to `getToken()` so does that mean you always end up pushing 2 `TemplateHead`s?

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.6

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Review by andrewbranch — APPROVED** [review]
