### PR TITLE
Fill missing type arguments during error reporting

### LINKED ISSUE #18938: Generic function with default second type parameter -> Debug Failure. False expression.
**TypeScript Version:**  2.5.3

**Code**

```ts
interface ObjA {
  y?:string,
  // [key:string]:any, // correctly fails to compile with error "... and 'y' does not exist in type 'MyObjA'."
}

interface ObjB {[key:string]:any}

interface Opts<A, B> {a:A, b:B}

const fn = <
  A extends ObjA,
  // A, // correctly fails to compile with error "... and 'y' does not exist in type 'MyObjA'."
  B extends ObjB = ObjB
  // B extends ObjB // correctly fails to compile with error "Type 'MyObjA' has no properties in common with type 'ObjA'.", when `fn` is called with `fn<MyObjA, ObjB>(...`
>(opts:Opts<A, B>):string => 'Z'

interface MyObjA {
  x:string,
  // y:string, // correctly compiles without errors
}

fn<MyObjA>({
// fn({ // correctly compiles without errors
// fn<MyObjA, ObjB>({ // correctly fails to compile with error "Type 'MyObjA' has no properties in common with type 'ObjA'."
  a: {x: 'X', y: 'Y'},
  b: {},
})
```

**Expected behavior:**
Fail to compile with error "Type 'MyObjA' has no properties in common with type 'ObjA'."

**Actual behavior:**
"Error: Debug Failure. False expression."

### PR DESCRIPTION
**Pull request by sandersn**
Previously, only the success path did this; it was missing in the error reporting path in resolveCall. This resulted in crashes for unsupplied type arguments when the supplied type arguments were incorrect.

Fixes #18938

### CODE REVIEW

**Comment by sandersn** [comment]
The last commit makes checkTypeArguments a lot less error prone by reducing the number of parameters, always calling fillMissingTypeArguments and simplifying the internal code. It goes back to its old style of returning the array of type arguments, but now returns `false` if there was an error. This is trivial to give a type to now but wasn't possible in 2014 when the function was last rewritten.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15643,34 +15643,35 @@ namespace ts {
...
-                            mapper = createTypeMapper(typeParameters, typeArgumentTypes);
-                        }
-                        const typeArgument = typeArgumentTypes[i];
-                        typeArgumentsAreAssignable = checkTypeAssignableTo(
-                            typeArgument,
-                            getTypeWithThisArgument(instantiateType(constraint, mapper), typeArgument),
-                            reportErrors ? typeArgumentNodes[i] : undefined,
-                            typeArgumentHeadMessage,
-                            errorInfo);
+            for (let i = 0; i < typeArguments.length; i++) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: I liked the old name `typeArgumentNodes`, helps distinguish it from `typeArgumentTypes`.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -15643,34 +15643,35 @@ namespace ts {
...
+                const constraint = getConstraintOfTypeParameter(typeParameters[i]);
```
Comment (andy-ms) [inline src/compiler/checker.ts]: What if there are more nodes than type parameters? Won't this cause an error in `typeParameters[i]`?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -15643,34 +15643,35 @@ namespace ts {
...
+                if (constraint) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Nit: `if (!constraint) continue;`

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -15643,34 +15643,35 @@ namespace ts {
...
+                    let errorInfo: DiagnosticMessageChain;
+                    let typeArgumentHeadMessage = Diagnostics.Type_0_does_not_satisfy_the_constraint_1;
+                    if (reportErrors && headMessage) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Maybe you should just take `headMessage` but not `reportErrors` and have the caller pass in a message if they want errors?
`errorInfo` will definitely be undefined in the call to `chain`, so it's not really a chain...

Comment (sandersn) [reply src/compiler/checker.ts]: Good idea. 

I couldn't find another way to *start* a message chain, and `checkTypeAssignableTo` wants a message chain. But I did use constants as arguments to `chainDiagnosticMessages`, and removed some mutation.

Comment (sandersn) [reply src/compiler/checker.ts]: Actually, `reportErrors` turns out to be required because sometimes you want to report errors even without a different `headMessage`.

Comment (andy-ms) [reply src/compiler/checker.ts]: Do you know why `checkTypeRelatedTo` takes both `headMessage` and `containingMessageChain`?

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts]: If there are more nodes than type parameters, then we take other code paths that avoid `checkTypeArguments`. But I added an assert to make sure this continues to be the case.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -15643,34 +15643,32 @@ namespace ts {
...
         }
 
-        function checkTypeArguments(signature: Signature, typeArgumentNodes: ReadonlyArray<TypeNode>, typeArgumentTypes: Type[], reportErrors: boolean, headMessage?: DiagnosticMessage): boolean {
+        function checkTypeArguments(signature: Signature, typeArgumentNodes: ReadonlyArray<TypeNode>, reportErrors: boolean, headMessage?: DiagnosticMessage): Type[] | false {
+            const isJavascript = isInJavaScriptFile(signature.declaration);
             const typeParameters = signature.typeParameters;
-            let typeArgumentsAreAssignable = true;
+            const typeArgumentTypes = fillMissingTypeArguments(map(typeArgumentNodes, getTypeFromTypeNode), typeParameters, getMinTypeArgumentCount(typeParameters), isJavascript);
             let mapper: TypeMapper;
             for (let i = 0; i < typeArgumentNodes.length; i++) {
```
Comment (andy-ms) [inline src/compiler/checker.ts]: Could also use a `zip3` helper function that asserts lengths match.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [reply src/compiler/checker.ts]: I took a look at `checkTypeRelatedTo`. The intent is to pass a chain
`containingMessageChain=[e1, e2, e3]`, `headMessage=e6` such that, if `checkTypeRelatedTo` finds errors `e4` and `e5`, the resulting chain is `[e1, e2, e3, e4, e5, e6]`.

Only three uses exist as far as I can tell.
* checkTypeArguments -- singleton 'chain'
* checkTypePredicate -- singleton 'chain', but no headMessage
* checkDecorator -- singleton 'chain', headMessage *might* not be defined. I don't know whether `getDiagnosticHeadMessageForDecoratorResolution` is effectively total.

So the split functionality is used, but the requirement that containingMessageChain actually be a *chain* just makes writing `checkTypeRelatedTo` slightly simpler.

File: src/compiler/checker.ts (hunk 5 above)
Comment (sandersn) [reply src/compiler/checker.ts]: True, but I can't remember ever needing `zip3` before. I'll add it when I see it a second time.
