### PR TITLE
Unify contextual signature type parameter assignment

### LINKED ISSUE #28445: Regression bug - false typescript error with regards to generics and generics inference
Issue Type: <b>Bug</b>

I use a complex structure of classes, interfaces and generics.

The generic type is inferred by the first paramter of the class constructor.
In the current version I get a syntax highlight error that I did not receive in older versions (few month ago).

Here are some screenshots - and the code is below:
image

And the errors are:
image
and:
image

Here's the type script code with two members - one that get's the syntax error and one that works.

    class ClassA<classType>  {
      constructor(private entity?: classType, public settings?: SettingsInterface<classType>) {

      }
    }
    export interface valueInterface<classType> {
      func?: (row: classType) => any;
      value?: string;
    }
    export interface SettingsInterface<classType> {
      values?: (row: classType) => valueInterface<classType>[],
    }
    class myClass{
        theName='myClass';
    }

    var thisGetsTheFalseError = new ClassA(new myClass(), {
      values: o => [
        {
          value: o.theName,
          func: x => 'asdfkjhgfdfghjkjhgfdfghjklkjhgfdfghjklkjhgfghj'
        }
      ]
    });
    var thisIsOk = new ClassA<myClass>(new myClass(), {
      values: o => [
        {
          value: o.theName,
          func: x => 'asdfkjhgfdfghjkjhgfdfghjklkjhgfdfghjklkjhgfghj'
        }
      ]
    });

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.84GB (17.33GB free)|
|Process Argv|--folder-uri file:///c%3A/Repos/radweb|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
githistory|don|0.4.3
gitlens|eam|8.5.6
debugger-for-chrome|msj|4.11.0

</details>

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #28445

In `getTypeForVariableLikeDeclaration` (which was eventually called into by `getTypeOfSymbol`) we looked at the contextual signature for an unannotated parameter's type, but failed to look at the inference context's mapper, so we'd have uninstantiated context variables saved into the symbol type cache which'd pollute future results. With this, we instantiate and fix the same as we do via the `checkFunctionExpressionOrObjectLiteralMethod` entrypoint to parameter type calculation.

This exposed a small bug where we didn't consider function _declarations_ with jsdoc tags as potentially context sensitive in JS, which is also fixed.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18172,7 +18176,7 @@ namespace ts {
         }
 
         // Return contextual type of parameter or undefined if no contextual type is available
-        function getContextuallyTypedParameterType(parameter: ParameterDeclaration): Type | undefined {
+        function getContextuallyTypedParameterType(parameter: ParameterDeclaration, forCache?: boolean): Type | undefined {
```
Comment (sandersn) [inline src/compiler/checker.ts]: this function is only called twice so I would make `forCache` required.

monomorphism!

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11484,6 +11484,7 @@ namespace ts {
                 case SyntaxKind.FunctionExpression:
                 case SyntaxKind.ArrowFunction:
                 case SyntaxKind.MethodDeclaration:
+                case SyntaxKind.FunctionDeclaration: // Function declarations can have context when annotated with a jsdoc @type
```
Comment (sandersn) [inline src/compiler/checker.ts]: I couldn't find a test with an example, and couldn't come up with one myself. I didn't think `@type` was treated as a contextual type.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -22978,12 +22995,18 @@ namespace ts {
...
                 return type;
             }
 
+            contextuallyCheckFunctionExpressionOrObjectLiteralMethod(node, checkMode);
+
+            return type;
+        }
+
+        function contextuallyCheckFunctionExpressionOrObjectLiteralMethod(node: FunctionExpression | ArrowFunction | MethodDeclaration, checkMode?: CheckMode) {
+            const links = getNodeLinks(node);
```
Comment (sandersn) [inline src/compiler/checker.ts]: doesn't getTypeOfFunctionMethodModule muck with `links` for certain JS patterns? Is it possible to retrieve the incorrect  `links` here if `contextuallyCheckFuncti...` is called in the dynamic scope of `getTypeOfFunctionMethodOrModule` ?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -22993,6 +23016,10 @@ namespace ts {
                 if (!(links.flags & NodeCheckFlags.ContextChecked)) {
                     links.flags |= NodeCheckFlags.ContextChecked;
                     if (contextualSignature) {
+                        const type = getTypeOfSymbol(getMergedSymbol(node.symbol));
+                        if (isTypeAny(type)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: why any? Is that what we get when we call `getTypeOfSymbol` on a symbol that we're already trying to get the type of?

Comment (sandersn) [reply src/compiler/checker.ts]: Also, this idiom happens three times in this review -- twice more than before I think. Should it be part of some larger chunk of code?

Comment (weswigham) [reply src/compiler/checker.ts]: `any` because it's good form that when you get an `any` in you make an `any` out. Afaik in normal TS scenarios it's impossible since a new lazy object type is created for each functiony node. The jsdocy codepath there is less well-formed though, and seems perfectly capable of injecting an `any` - so we respect that here and propegate it as expected. I don't think the idiom can be extracted because bit involves control flow, namely a `return`. (And `getTypeOfMergedSymbol()` is almost as long as `getTypeOfSymbol(getMergedSymbol())`, so payoff there is low, imo)

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts]: It doesn't much with so much as assign to multiple links caches iirc.

Comment (weswigham) [reply src/compiler/checker.ts]: The code below ensures no reentry via the context checked flag and all of this is verbatim extracted from `getTypeOfFunctionExpressionOrObjectLiteralMethod`.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: There's a trio of jsdoc tests that demonstrate it which were borked with the better handling of contextual mappers and context checking (ie, they abused how the different entrypoint cached a different type to force a type to be cached from the jsdoc annotation) without proper handling here. The responsible codepath is definitely doing an unsafe cast, technically, since this function isn't even declared to accept a `FunctionDeclaration`, however checking it is perfectly reasonable when an annotated declaration is viewed in the same light as an annotated assigned expression.

**Comment by weswigham** [comment]
> Is it possible to early-detect this situation and use the normal code path instead of hacking the current code path to behave the same?

No - in fact, LS requests will _almost_ always come in via the `getTypeOfSymbol` route first, but if quickinfo for the containing object is asked for the other might be first. The context checked pattern forces us to take a single result now (that respects any contextual mappers applied), which is at least better. Tbh, there being a similar codepath between some of the respective `checkX` methods and `getTypeOfVariableParameterOrProperty` that can produce types for the same symbol for is probably always an error - but iirc contextual parameter assignment is literally the one place we assign to a symbol's type outside of symbol-based type lookuo caching. The symbol lookup is "designed" to be both highly polymorphic on symbol declaration and to have an output for every conceivable declaration kind, while the other is meant to simply handle a top-down walk of a node tree, and so can make many simplifying assumptions...

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [reply src/compiler/checker.ts]: :+1: perhaps via `/** @type {any} */` on a function declaration?

It might be true that getTypeOfSymbol should always call getMergedSymbol, but I was referring to `if(any)`.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts]: can you point me to the tests?
