### PR TITLE
Use type parameter constraints for computed property types

### LINKED ISSUE #14473: Generics and keyof does not work with computed properties
**TypeScript Version:**  2.2.0

Code with unexpected type error:
```ts
export function set<T, K extends keyof T>(obj: T, key: K, value: T[K]) {
    return Object.assign(obj, {
        [key]: value,
    });
}
```

**Expected behavior:**
No type errors because `K` should is a subtype of `keyof T`. It works if `key: keyof T` and even `key: K & keyof T`.

**Actual behavior:**
Type error:
`A computed property name must be of type 'string', 'number', 'symbol', or 'any'.`

### LINKED ISSUE #15501: Mapped type loses type bound when used with arithmetic operator
**TypeScript Version:**  nightly (2.4.0-dev.20170501)

**Code**

```ts
interface I { x: number; }

type IdentityMap<T> = {
    [P in keyof T]: T[P];
};

function f<T extends I>(i: IdentityMap<T>) {
    const n: number = i.x; // No error, good
    i.x * 2; // Error
}
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts(9,5): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.`

May be related to #14360.

### LINKED ISSUE #17069: Unable to add numeric types that are not simply 'number'
I'm trying to rewrite the signature of `sum` from `core.ts` in our compiler (see #16823), but I'm getting this error:

```ts
export function sum<T extends Record<K, number>, K extends string>(array: T[], prop: K): number {
    let result = 0;
    for (const v of array) {
        result += v[prop];
     // ~~~~~~~~~~~~~~~~~
     // Operator '+=' cannot be applied to types 'number' and 'T[K]'.
    }
    return result;
}
```

Note that I can't declare `sum` as

```ts
export function sum<K extends string>(array: Record<K, number>[], prop: K): number
```

because then TypeScript would infer *all* of the properties in each element for `K`. So I do need another type argument `T` for the indirection.

For a simpler repro:

```ts
function foo<T extends number>(x: T) {
    return 0 + x;
    //     ~~~~~
    // Operator '+' cannot be applied to types '0' and 'T'.

}
```

Related is #15645.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #14473
Fixes #15501
Fixes #17069

Note this code calls `getBaseConstraintOfType` the same way that `getApparentType` does. Calling `getApparentType` does not work here because it converts `string` to `String` and so on.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
Instead of this targeted change, it might make more sense to review all the uses of `isTypeAnyOrAllConstituentTypesHaveKind` function and replace then with calls to `isTypeAssignableTo` as appropriate. We have other similar issues, such as not being able to use arithmetic operators with `T extends number` values, and we might as well fix them all in one go.

**Comment by sandersn** [comment]
I replaced the body of `isTypeOfKind` (which `isTypeAnyOrAllConstituentsTypesHaveKind` immediately delegates to). The tests are passing but I still want to improve the any/null/undefined/void exclusion code since it's really the caller's responsibility.

**Comment by sandersn** [comment]
Note that this most recent commit improves the error message for expressions like `null + undefined` or `null + 1` considerably, in addition to allowing this:

```ts
function f<T extends number>(t: T) {
  return t + t
}
```

Here, the return type of `f` is `number`. That's still hard-coded in the checker code for binary expressions.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -16991,31 +16986,43 @@ namespace ts {
...
+                return false;
             }
-            if (type.flags & TypeFlags.Intersection) {
-                const types = (<UnionOrIntersectionType>type).types;
-                for (const t of types) {
-                    if (isTypeOfKind(t, kind)) {
-                        return true;
-                    }
-                }
+            const targets = [];
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Why are you building up a union type here? It causes allocations and ends up being broken down to discrete checks for each contained type anyway. I think it would be better to just have a sequence of conditional `isTypeAssignableTo` calls here, e.g.

```ts
return kind & TypeFlags.NumberLike && isTypeAssignableTo(source, numberType) ||
    kind & TypeFlags.StringLike && isTypeAssignableTo(source, stringType) ||
    kind & TypeFlags.BooleanLike && isTypeAssignableTo(source, BooleanType) ||
    ...
```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -16991,31 +16986,43 @@ namespace ts {
             return false;
         }
 
-        // Return true if type is of the given kind. A union type is of a given kind if all constituent types
-        // are of the given kind. An intersection type is of a given kind if at least one constituent type is
-        // of the given kind.
-        function isTypeOfKind(type: Type, kind: TypeFlags): boolean {
-            if (type.flags & kind) {
+        function isTypeOfKind(source: Type, kind: TypeFlags, excludeAny?: boolean) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I'm not sure I get why we need this `excludeAny` parameter?

**Comment by ahejlsberg** [comment]
@sandersn With the latest changes this also fixes #15501 and #17069.

**Comment by simonbuchan** [comment]
The errors also sound similar to the string enums as keys errors, eg #16687, #16760?

File: src/compiler/checker.ts (hunk 1 above)
Comment (sandersn) [inline src/compiler/checker.ts]:
```
var p1: number | string
var o = {
  [p1]() { }
  ~~~~ A computed property name must be of type 'string', 'number', ...
}
```

But I think I can fix that by adding a fallback to isTypeAssignableTo the union type in just the case of computed properties.

Comment (sandersn) [inline src/compiler/checker.ts]: Fixed. The computed property name type check now has a fallback call to `isTypeAssignableTo(links.resolvedType, getUnionType([numberType, stringType, esSymbolType])`. Everything else is fine with a sequence of `isTypeAssignableTo` calls.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/checker.ts]: `checkBinaryLikeExpression` has a complicated way of checking legal types for `+`:

1. It disallows `null + number` and `number + undefined`, even with `strictNullChecks` off. I like this check and want to keep it.
2. It gives a different types for `string + any ==> string` vs `T + any ==> any` and `T + unknown ==> unknown`.

It does this with the following (simplified) structure (using the abbreviation `tak` for `isTypeAssignableToKind`):

```ts
if (tak(left, NumberLike) && tak(right, NumberLike)) {
  return numberType;
}
else if (tak(left, StringLike) || tak(right, StringLike)) {
  return stringType;
}
else if (isTypeAny(left) || isTypeAny(right)) {
  return anyType;
}
else {
  returned undefined; // signal an error
}
```

Without `excludeAny` (now called `strict`), `isTypeAssignableTo(number, undefined)` is true, and `number + undefined/null` is now legal. Also, `isTypeAssignableTo(number, any)` is true, and `number + any ==> number` , and `any + any ==> number`.

I tried a few things to pull the `any` checks before the calls to `isTypeAssignableToKind`, but was not successful. If you see a way, let me know.

**Comment by sandersn** [comment]
@simonbuchan Your example #16687 has this error as a side effect, but this fix doesn't provide the type that you're looking for there.

**Comment by sandersn** [comment]
This PR is ready to look at again.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -17029,31 +17026,22 @@ namespace ts {
...
-                for (const t of types) {
-                    if (isTypeOfKind(t, kind)) {
-                        return true;
-                    }
-                }
+            if (strict && source.flags & (TypeFlags.Any | TypeFlags.Void | TypeFlags.Undefined | TypeFlags.Null)) {
+                return false;
             }
-            return false;
+            return kind & TypeFlags.NumberLike && isTypeAssignableTo(source, numberType) ||
```
Comment (rbuckton) [inline src/compiler/checker.ts]: Calling `isTypeAssignableTo` so many times seems fairly expensive if `source` is not a simple type. While the assignability check has a fast path for simple types via `isSimpleTypeRelatedTo`, if the relation doesn't hold we fall back to the more complex `checkTypeRelatedTo` function. I would recommend you determine if there is any additional check time overhead with this approach.

**Comment by sandersn** [comment]
Sure, I'll test it, although @ahejlsberg was confident that his changes to `isTypeAssignableTo` would make this cheap enough.

**Comment by sandersn** [comment]
Here are the ts-perf results (angular doesn't build on my installation of ts-perf). Total time goes down a tiny amount. Check time went up by 0.01s for TFS, and down 0.01s for Monaco. So I don't think there's any performance impact with this change.

```
┌─────────────┬─────────────────────┬─────────────────────┬───────────────────┬───────────┬────────────┐
│ Project     │            Baseline │             Current │             Delta │      Best │      Worst │
╞═════════════╧═════════════════════╧═════════════════════╧═══════════════════╧═══════════╧════════════╡
│ Monaco - node (v8.1.2, x64)                                                                          │
├─────────────┬─────────────────────┬─────────────────────┬───────────────────┬───────────┬────────────┤
│ Memory used │ 366,008k (±  0.00%) │ 366,041k (±  0.01%) │   +33k (+  0.01%) │  365,987k │   366,174k │
│ Parse Time  │    1.25s (±  0.70%) │    1.24s (±  0.28%) │ -0.00s (-  0.28%) │     1.23s │      1.25s │
│ Bind Time   │    0.60s (±  0.40%) │    0.60s (±  0.81%) │ +0.00s (+  0.75%) │     0.59s │      0.64s │
│ Check Time  │    3.10s (±  1.53%) │    3.09s (±  0.26%) │ -0.01s (-  0.48%) │     3.06s │      3.13s │
│ Emit Time   │    1.87s (±  0.85%) │    1.87s (±  0.48%) │ -0.00s (-  0.03%) │     1.84s │      1.91s │
├─────────────┼─────────────────────┼─────────────────────┼───────────────────┼───────────┼────────────┤
│ Total Time  │    6.82s (±  0.89%) │    6.80s (±  0.23%) │ -0.02s (-  0.25%) │     6.77s │      6.89s │
╞═════════════╧═════════════════════╧═════════════════════╧═══════════════════╧═══════════╧════════════╡
│ TFS - node (v8.1.2, x64)                                                                             │
├─────────────┬─────────────────────┬─────────────────────┬───────────────────┬───────────┬────────────┤
│ Memory used │ 319,284k (±  0.00%) │ 319,305k (±  0.00%) │   +21k (+  0.01%) │  319,282k │   319,363k │
│ Parse Time  │    0.91s (±  0.74%) │    0.91s (±  0.34%) │ -0.00s (-  0.16%) │     0.90s │      0.92s │
│ Bind Time   │    0.49s (±  3.23%) │    0.49s (±  2.17%) │ -0.01s (-  1.22%) │     0.47s │      0.58s │
│ Check Time  │    2.75s (±  0.94%) │    2.76s (±  0.81%) │ +0.01s (+  0.44%) │     2.58s │      2.83s │
│ Emit Time   │    1.77s (±  1.12%) │    1.76s (±  0.27%) │ -0.01s (-  0.82%) │     1.74s │      1.77s │
├─────────────┼─────────────────────┼─────────────────────┼───────────────────┼───────────┼────────────┤
│ Total Time  │    5.92s (±  0.36%) │    5.91s (±  0.22%) │ -0.01s (-  0.19%) │     5.84s │      5.95s │
└─────────────┴─────────────────────┴─────────────────────┴───────────────────┴───────────┴────────────┘
```

File: src/compiler/checker.ts (hunk 3 above)
Comment (sandersn) [inline src/compiler/checker.ts]: Also note that calls to `isTypeAssignableToKind` only ever pass 1-3 flags in, with 1 being the most common. So the expected perf hit would be just from calling `isTypeAssignableTo` *once* compared to the old logic.

**Comment by sandersn** [comment]
I'd like to get this into 2.5 RC so people can catch any lurking bugs. I'm on vacation starting Thursday, so let's leave this open until Friday to see if @ahejlsberg has a chance to look at this while he's gone too. I'll leave it up to you to merge or not at that point. @rbuckton.

I'll also try running ts-perf on a stress-test scenario that has lots of object type + string expressions.

**Comment by rbuckton** [comment]
I can see how `isTypeAssignableTo` has the same or better performance when the `source` type is simple enough (e.g. already a `number`, `string`, `enum`, or `union` as would generally be the case for our perf tests which have mostly _correct_ code), but if the `source` type is a structured type or a type variable we end up in `recursiveTypeRelatedTo` which has 3 array allocations per each call to `isTypeAssignableTo` and will inflate the size of the assignability cache by 9 entries. 

This may be acceptable overhead for cases where we are likely to fail, but something we should consider. It may be worthwhile for us to compose a performance benchmark against a scenario we tailor to be filled with _incorrect_ code so that we can watch for performance regressions in those cases.

**Comment by rbuckton** [comment]
After reviewing this further with @sandersn, I'm not too concerned about the performance since we don't dig into `target` since its a simple type. 👍
