### PR TITLE
Alias for commonjs require in JS

### LINKED ISSUE #25533: `const x = require("m")` should create an alias symbol
**TypeScript Version:**  3.0.0-dev.20180707

**Code**

```ts
/// <reference path='fourslash.ts'/>

// @allowJs: true

// @Filename: /a.js
////function [|{| "isWriteAccess": true, "isDefinition": true |}x|]() {};
////module.exports = [|x|];

// @Filename: /b.js
////const [|x|] = require("./a");
////[|x|];

const [r0, r1, r2, r3] = test.ranges();
verify.referenceGroups(r2, [/*todo*/]);
```

**Expected behavior:**

`x` in `const x` is an alias of the `x` in `function x() {}`, so all references are found.

**Actual behavior:**

`x` is a variable that happens to be the same type as the other `x`. Only references in `b.js` are found.

### LINKED ISSUE #37000: JS binding should create real aliases for module.exports
In JS, binding often puts symbols on things that should actually be aliases. Then there is ad-hoc alias-following code in the binder and checker that should really be consolidated with the real alias-handling code.

### LINKED ISSUE #38379: In JS, assertions imported via commonjs have bogus error
**Code**

```ts
// @filename: declares.d.ts
// this is the declaration for 'assert' from @types/node
export function art(value: any, message?: string | Error): asserts value;

// @filename: test.js
const { art } = require('./declares')
let x = 1
art(x)
```

**Expected behavior:**
No error.

**Actual behavior:**
Error: "Assertions require every name in the call target to be declared with an explicit type annotation."

There is no error when using ES imports:

```js
// @filename: test2.js
import { art } from './declares'
let x = 1
art(x)
```

### PR DESCRIPTION
**Pull request by sandersn**
This PR binds commonjs `const x = require('y')` statements the same way as TS `import x = require('y')`: as an alias. This improves the consistency of JS, and should fix a number of bugs that have been particularly hard to fix over the years. It should let us get rid of quite a bit of ad-hoc code too. See below for details.

Fixes #38379 and
Fixes #37000
Fixes #25533

Maybe also 
* #37832 - edit: doesn't fix this, probably because of the fallback to require-as-call type checking.
* #39895 - fixes the import half of this, but exports *also* need to be aliases for goto-def to work exactly the same as ES.
* #36830 - doesn't fix this -- it deals with the *other* branch of the ad-hoc code I want to get rid of
and some others I need to dig up, but I need to verify first.

Limitations and open questions:

1. There is special-case code in a few places for `const x = require('y').z` -- a `require` with a single suffix. But it doesn't work with `const x = require('y').z.more.nested.accesses` or `const { destructuring } = require('y').z`. This probably isn't much more, or much more *complicated* code -- I'm just not sure it's worth the effort, and I wanted to get an initial version done.
2. I didn't remove all of the existing special-case code. In particular, type checking of `const s = require('fs').readFileSync("foo", "utf8")` falls back to the old method of producing an anonymous type from `require('fs')` and then retrieving the property named `readFileSync` from that type.

The declaration emit change is easier to read with whitespace ignored because I indented a span of code without changing it.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -6208,43 +6223,60 @@ namespace ts {
...
                                             /*modifiers*/ undefined,
                                             /*isTypeOnly*/ false,
-                                            factory.createNamedExports([factory.createExportSpecifier(name, localName)])
+                                            factory.createNamedExports([factory.createExportSpecifier(alias, localName)])
                                         ),
                                         ModifierFlags.None
                                     );
-                                    needsExportDeclaration = false;
-                                    needsPostExportDefault = false;
+                                    serializeTypeForDeclaration(context, type, symbol, enclosingDeclaration, includePrivateSymbol, bundled);
```
Comment (sandersn) [inline src/compiler/checker.ts:6239]: `serializeTypeForDeclaration` makes sure to walk the rest of the symbol graph, but I don't use the return value, so I'd rather call something that just walks a symbol. I thought that was `includePrivateSymbol` but it doesn't seem to work. Thoughts?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -6611,17 +6643,45 @@ namespace ts {
                     const targetName = getInternalSymbolName(target, verbatimTargetName);
                     includePrivateSymbol(target); // the target may be within the same scope - attempt to serialize it first
                     switch (node.kind) {
+                        case SyntaxKind.VariableDeclaration:
+                            // commonjs require: const x = require('y')
+                            if (isPropertyAccessExpression((node as VariableDeclaration).initializer!)) {
+                                // const x = require('y').z
+                                const initializer = (node as VariableDeclaration).initializer! as PropertyAccessExpression; // require('y').z
+                                const uniqueName = factory.createUniqueName((getExternalModuleRequireArgument(node) as StringLiteral).text); // _y
+                                const specifier = getSpecifierForModuleSymbol(target.parent || target, context); // 'y'
```
Comment (sandersn) [inline src/compiler/checker.ts:6652]: Since this is `require('y').z`, `target` is `z` and `target.parent` is `require('y')`. I fall back to `target` because, um, it MIGHT be right? And the declaration emitter seems to try to emit things even if they're not correct? Probably this whole block should check that `target.parent` is defined before proceeding. @weswigham what do you think?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -12051,16 +12114,7 @@ namespace ts {
...
-                    let isRequireAlias = false;
-                    if (isVariableDeclaration(decl) && decl.initializer) {
-                        let expr = decl.initializer;
-                        // skip past entity names, eg `require("x").a.b.c`
-                        while (isPropertyAccessExpression(expr)) {
-                            expr = expr.expression;
-                        }
-                        isRequireAlias = isCallExpression(expr) && isRequireCall(expr, /*requireStringLiteralLikeArgument*/ true) && !!valueType.symbol;
-                    }
+                    const isRequireAlias = isRequireVariableDeclaration(symbol.valueDeclaration, /*requireStringLiteralLikeArgument*/ true);
```
Comment (sandersn) [inline src/compiler/checker.ts:12117]: another driveby simplification, this time to use isRequireVariableDeclaration. 

Also, `isRequireAlias` should never be true now, so I think this can be removed entirely. But I need to test it.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -2387,17 +2384,27 @@ namespace ts {
                     && node.parent.operatorToken.kind === SyntaxKind.EqualsToken
                     && isAliasableOrJsExpression(node.parent.right) ||
                 node.kind === SyntaxKind.ShorthandPropertyAssignment ||
-                node.kind === SyntaxKind.PropertyAssignment && isAliasableOrJsExpression((node as PropertyAssignment).initializer);
+                node.kind === SyntaxKind.PropertyAssignment && isAliasableOrJsExpression((node as PropertyAssignment).initializer) ||
+                isRequireVariableDeclaration(node, /*requireStringLiteralLikeArgument*/ true);
```
Comment (elibarzilay) [inline src/compiler/checker.ts:2388]: (Not really relevant, but this thing made me look at the diff in Emacs, since it's incomprehensible...  Would look much better if the `||`s were at the BOLs, and `()` around the conjunctions...)

**Comment by sandersn** [comment]
The latest merge from master shows that the nested-import generation in #39818 still does not work for `require`. I'll need to go find out why.

File: src/compiler/utilities.ts [hunk 5]
```diff
@@ -4726,6 +4732,13 @@ namespace ts {
         }
     }
 
+    export function getFirstPropertyAccessExpression(expr: Expression): Expression {
```
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/utilities.ts:4736]: so probably `getLeftmostPropertyAccessExpression` ?

File: tests/cases/fourslash/goToDefinitionJsModuleNameAtImportName.ts [hunk 6]
```diff
@@ -3,10 +3,11 @@
 // @allowJs: true
 
 // @Filename: /foo.js
-//// /*moduleDef*/class Blah {
+//// /*moduleDef*/function notExported() { }
```
Comment (sandersn) [inline tests/cases/fourslash/goToDefinitionJsModuleNameAtImportName.ts:6]: this gotoDef test 

appears to show that goto-def on the imported module symbol jumps to the single export of the module,
but actually shows that goto-def on the imported module symbol jumps to the very beginning of the module.

I added a non-exported function to make this clearer.

**Comment by sandersn** [comment]
@weswigham this should be ready to review now.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -2372,32 +2369,41 @@ namespace ts {
...
+                || node.kind === SyntaxKind.ExportAssignment && exportAssignmentIsAlias(<ExportAssignment>node)
+                || isBinaryExpression(node) && getAssignmentDeclarationKind(node) === AssignmentDeclarationKind.ModuleExports && exportAssignmentIsAlias(node)
+                || isPropertyAccessExpression(node)
                     && isBinaryExpression(node.parent)
                     && node.parent.left === node
                     && node.parent.operatorToken.kind === SyntaxKind.EqualsToken
-                    && isAliasableOrJsExpression(node.parent.right) ||
-                node.kind === SyntaxKind.ShorthandPropertyAssignment ||
-                node.kind === SyntaxKind.PropertyAssignment && isAliasableOrJsExpression((node as PropertyAssignment).initializer);
+                && isAliasableOrJsExpression(node.parent.right)
```
Comment (weswigham) [inline src/compiler/checker.ts:2385]: Is the indentation right on this line? On GH it looks like it's missing a level of indentation compared to the prior line.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -6630,17 +6662,45 @@ namespace ts {
...
                     switch (node.kind) {
+                        case SyntaxKind.VariableDeclaration:
+                            // commonjs require: const x = require('y')
+                            if (isPropertyAccessExpression((node as VariableDeclaration).initializer!)) {
+                                // const x = require('y').z
+                                const initializer = (node as VariableDeclaration).initializer! as PropertyAccessExpression; // require('y').z
+                                const uniqueName = factory.createUniqueName((getExternalModuleRequireArgument(node) as StringLiteral).text); // _y
+                                const specifier = getSpecifierForModuleSymbol(target.parent || target, context); // 'y'
+                                // import _y = require('y');
+                                addResult(factory.createImportEqualsDeclaration(
```
Comment (weswigham) [inline src/compiler/checker.ts:6673]: So, this always needs to get made in the outermost scope, rather than the current (potentially nested) one, since `import x = require('whatever')` isn't valid syntax within a namespace. `includePrivateSymbol` handles that for specific symbols now (by adding the symbol we want to serialize to the private symbol list for the outermost scope), however we don't have a good mechanism (currently) for adding parts of serialized results to differing scopes. You might just need a sidechannel in the `NodeBuilderContext` that you add this declaration do that you then grab and append to the start/end (probably doesn't matter which) of the file once you're doing serializing all symbols.

Comment (weswigham) [reply src/compiler/checker.ts:6673]: As for a test case for this... something like a `module.exports.A.B.C` export that relies on a `require`'d type alias?

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -6816,7 +6876,10 @@ namespace ts {
                             const statement = factory.createVariableStatement(/*modifiers*/ undefined, factory.createVariableDeclarationList([
                                 factory.createVariableDeclaration(varName, /*exclamationToken*/ undefined, serializeTypeForDeclaration(context, typeToSerialize, symbol, enclosingDeclaration, includePrivateSymbol, bundled))
                             ], NodeFlags.Const));
-                            addResult(statement, name === varName ? ModifierFlags.Export : ModifierFlags.None);
+                            addResult(statement,
+                                target && target.flags & SymbolFlags.Property && target.escapedName === InternalSymbolName.ExportEquals ? ModifierFlags.Ambient
```
Comment (weswigham) [inline src/compiler/checker.ts:6880]: Care to add an inline comment explaining why a `Property` symbol needs a `declare` modifier (and not `export`)?

**Comment by sandersn** [comment]
>  removing the value-side fallback lookup from the isJSDocTypeReference case in getTypeFromTypeReference - can we do that?

No, for two reasons. First, this doesn't make all exports into aliases.
Second, the value side fallback is inside of a module also used for things like

```js
var exports = {}
/** @typedef {string} */
exports.SomeName;
/** @type {exports.SomeName} */
const myString = 'str';

const o = { a: 1, b: 2, c: 3 }
/** @type {keyof o} */
var x

var Outer = function O() { this.y = 2 }
Outer.Inner = class I {
  constructor() {
    this.x = 1
  }
}
/** @type {Outer} */var z
/** @type {Outer.Inner} */var ka
```

It does fix about 20% of the 50-odd failures we used to get without this fallback, but that's probably because we're importing classes correctly now.

File: src/compiler/checker.ts (hunk 7 above)
Comment (sandersn) [reply src/compiler/checker.ts:2385]: it was definitely wrong. fixed.

File: src/compiler/checker.ts (hunk 9 above)
Comment (sandersn) [reply src/compiler/checker.ts:6880]: Yep, it's because JSON types exported with `[module.]export=` will already emit an `export = blah`, so the inlined JSON type itself doesn't need `export`, but `declare`.
