### PR TITLE
fix(43796): Sort @deprecated completions lower than others

### LINKED ISSUE #43796: Sort @deprecated completions lower than others
If we do #43710, the first thing you'll see every time you request completions on a string is a bunch of crossed-out properties. Ideally, we never would've shown these properties anyway, but we traditionally had to have them there because ES6.

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/43710#issuecomment-821708524_

__

`@deprecated` has its own NodeFlags entry right now, so you just have to use the rules from the checker to decide if the signature as a whole should be considered deprecated (basically, whether all the signature's declarations are deprecated). I don't know the sort order code but I assume it would be easy.

_Originally posted by @sandersn in https://github.com/microsoft/TypeScript/issues/43710#issuecomment-821708524_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #43796

### CODE REVIEW

File: src/services/completions.ts [hunk 1]
```diff
@@ -3051,4 +3054,9 @@ namespace ts.Completions {
             addToSeen(seenModules, getSymbolId(sym)) &&
             checker.getExportsOfModule(sym).some(e => symbolCanBeReferencedAtTypeLocation(e, checker, seenModules));
     }
+
+    function isDeprecated(symbol: Symbol, checker: TypeChecker) {
+        const declarations  = skipAlias(symbol, checker).declarations;
```
Comment (sheetalkamat) [inline src/services/completions.ts:3059]: I think we should move `isDeprecatedDeclaration` thats already in symbolDisplay.ts to utilities and use that...

File: src/services/completions.ts [hunk 2]
```diff
@@ -3051,4 +3054,9 @@ namespace ts.Completions {
             addToSeen(seenModules, getSymbolId(sym)) &&
             checker.getExportsOfModule(sym).some(e => symbolCanBeReferencedAtTypeLocation(e, checker, seenModules));
     }
+
+    function isDeprecated(symbol: Symbol, checker: TypeChecker) {
+        const declarations  = skipAlias(symbol, checker).declarations;
+        return length(declarations) && every(declarations, d => !!(getCombinedNodeFlagsAlwaysIncludeJSDoc(d) & ModifierFlags.Deprecated));
```
Comment (sheetalkamat) [inline src/services/completions.ts:3060]: Can this be?
```suggestion
        return skipAlias(symbol, checker).declarations?.every(isDeprecatedDeclaration );
```

File: src/services/completions.ts [hunk 3]
```diff
@@ -585,9 +586,11 @@ namespace ts.Completions {
             }
 
             const { name, needsConvertPropertyAccess } = info;
+            const sortText = isDeprecated(symbol, typeChecker) ? SortText.Deprecated :
+                symbolToSortTextMap && symbolToSortTextMap[getSymbolId(symbol)] || SortText.LocationPriority;
```
Comment (sheetalkamat) [inline src/services/completions.ts:590]: Should these be instead: 
DeprecatedLocalDeclarationPriority
        DeprecatedLocationPriority,
        DeprecatedOptionalMember,
        DeprecatedMemberDeclaredBySpreadAssignment,
        DeprecatedSuggestedClassMembers,
        DeprecatedGlobalsOrKeywords,
        DeprecatedAutoImportSuggestions,

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 3 above)
Comment (a-tarasyuk) [reply src/services/completions.ts:590]: @sheetalkamat Thanks for the review 👍🏻 . As I understood, the `SortText` need to change like so., Am I right?
```ts
export enum SortText {
   LocalDeclarationPriority = "0",
   DeprecatedLocalDeclarationPriority = "1",
   LocationPriority = "2",
   DeprecatedLocationPriority = "3",
   OptionalMember = "4",
   DeprecatedOptionalMember = "5",
   MemberDeclaredBySpreadAssignment = "6",
   DeprecatedMemberDeclaredBySpreadAssignment = "7",
   SuggestedClassMembers = "8",
   DeprecatedSuggestedClassMembers = "9",
   GlobalsOrKeywords = "10",
   DeprecatedGlobalsOrKeywords = "11",
   AutoImportSuggestions = "12",
   DeprecatedAutoImportSuggestions = "13",
   JavascriptIdentifiers = "14"
}
```

Comment (sheetalkamat) [reply src/services/completions.ts:590]: I am not sure about ordering... @RyanCavanaugh @DanielRosenwasser @uniqueiniquity @jessetrinity would be able to comment on the ordering but it seems we would want to prioritize say localtion priority deprecated over deprecated auto imports so i am not sure if all deprecated go in the end in the same order as their non deprecated ones or not. Also I think there is some issue with changing number for `JavascriptIdentifiers` that @uniqueiniquity is able to weigh in...

Comment (uniqueiniquity) [reply src/services/completions.ts:590]: The issue for us is changing the value of `GlobalsOrKeywords`, since we add global completions in on the editor side for snippets. So I have a slight preference for adding all the distinct deprecated categories at the end instead of interleaving them from that perspective as well as from a usability perspective. But we certainly can handle the change in the editor if we needed to interleave the new categories for some reason.

Comment (a-tarasyuk) [reply src/services/completions.ts:590]: @uniqueiniquity Thanks for the clarification. We need to add a new property _(DeprecatedGlobalsOrKeywords)_ to `SortText` and only sort the deprecated GlobalsOrKeywords entities. I'm right?
 
```ts
export enum SortText {
   LocalDeclarationPriority = "0",
   LocationPriority = "1",
   OptionalMember = "2",
   MemberDeclaredBySpreadAssignment = "3",
   SuggestedClassMembers = "4",
   GlobalsOrKeywords = "5",
   AutoImportSuggestions = "6",
   JavascriptIdentifiers = "7",
   DeprecatedGlobalsOrKeywords = "8"
}
```

Comment (uniqueiniquity) [reply src/services/completions.ts:590]: I apologize for not being clear. Here's what I think is correct, if others feel that the deprecated items need to be sorted within themselves:
```ts
export enum SortText {
   LocalDeclarationPriority = "0",
   LocationPriority = "1",
   OptionalMember = "2",
   MemberDeclaredBySpreadAssignment = "3",
   SuggestedClassMembers = "4",
   GlobalsOrKeywords = "5",
   AutoImportSuggestions = "6",
   DeprecatedLocalDeclarationPriority = "7",
   DeprecatedLocationPriority = "8",
   DeprecatedOptionalMember = "9",
   DeprecatedMemberDeclaredBySpreadAssignment = "10",
   DeprecatedSuggestedClassMembers = "11",
   DeprecatedGlobalsOrKeywords = "12",
   DeprecatedAutoImportSuggestions = "13",
   JavascriptIdentifiers = "14"
}
```
If the deprecated items do not need to be sorted within themselves, then I am fine with the PR as it currently is.

Comment (a-tarasyuk) [reply src/services/completions.ts:590]: @uniqueiniquity Thanks.

File: src/services/completions.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/services/completions.ts]: For an empty array, `every` returns `true` - for that reason need to check the `length` of an array. Does that make sense?

File: src/services/completions.ts (hunk 3 above)
Comment (a-tarasyuk) [reply src/services/completions.ts:590]: Do we need to sort the deprecated elements within ourselves?

/cc @RyanCavanaugh @DanielRosenwasser @jessetrinity @sandersn @sheetalkamat

Comment (sheetalkamat) [reply src/services/completions.ts:590]: We discussed this today and indeed we want the deprecated entries sorted among themselves.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

**Review by uniqueiniquity — APPROVED** [review]

File: src/services/completions.ts [hunk 4]
```diff
@@ -8,7 +8,14 @@ namespace ts.Completions {
...
         AutoImportSuggestions = "6",
-        JavascriptIdentifiers = "7"
+        DeprecatedLocalDeclarationPriority = "7",
+        DeprecatedLocationPriority = "8",
+        DeprecatedOptionalMember = "9",
+        DeprecatedMemberDeclaredBySpreadAssignment = "10",
+        DeprecatedSuggestedClassMembers = "11",
+        DeprecatedGlobalsOrKeywords = "12",
+        DeprecatedAutoImportSuggestions = "13",
+        JavascriptIdentifiers = "14"
```
Comment (sheetalkamat) [inline src/services/completions.ts:18]: Just wanted to make sure javascript identifiers are below deprecated ones?
Is this ok @DanielRosenwasser ?

File: src/services/completions.ts [hunk 5]
```diff
@@ -585,9 +592,11 @@ namespace ts.Completions {
             }
 
             const { name, needsConvertPropertyAccess } = info;
+            const sortText = symbolToSortTextMap && symbolToSortTextMap[getSymbolId(symbol)]
```
Comment (sheetalkamat) [inline src/services/completions.ts:595]: I think instead of spreading this code everywhere, (isDeprecatedSymbol), we should keep it same and change to deprecated sortText here. 
One change would be that we do is have SortTextId as number enum instead of `string`
```ts
const sortTextId = symbolToSortTextMap && symbolToSortTextMap[getSymbolId(symbol)] || SortTextId.LocationPriority;
const sortText = isDeprecated(symbol) ?  DeprecatedStart + sortTextId : sortTextId;
```

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: src/services/completions.ts (hunk 5 above)
Comment (a-tarasyuk) [reply src/services/completions.ts:595]: @sheetalkamat Thanks for the feedback. Not sure that I fully understood the idea. Correct me if I'm wrong., so need to do the following changes

1. `sortText` property in `CompletionEntry` need to change from `string` to `number` - is it ok to TSServer response?
2. Create a helper function to avoid `isDeprecated` conditions, and use it for all sort types., not only in `getCompletionEntriesFromSymbols`

Comment (sheetalkamat) [reply src/services/completions.ts:595]: No the type of property in completion entry does not change but sortTextMap use number enum and then convert those to string in one place without having to worry about deprecated sortText everywhere else.

Comment (a-tarasyuk) [reply src/services/completions.ts:595]: @sheetalkamat It looks like in `completions` there are places where `sortText` needs to be explicitly converted, like `createCompletionEntryForLiteral`, `getJSCompletionEntries`, etc. Is it ok to convert numbers to string in all of these cases?

Comment (sheetalkamat) [reply src/services/completions.ts:595]: I am not suggesting changing type of `CompletionEntry["sortText"]` type. I am suggesting that `SymbolSortTextMap` is enum with new enum that has entries without deperecated and numbers so you can do toString() and convert to actual sortText enum here depending on deprecated.

Comment (a-tarasyuk) [reply src/services/completions.ts]: @@sheetalkamat I didn't mean changing type of `CompletionEntry["sortText"]`. I mean, if we change the `SortText` to numbers then we need to explicitly convert the `sortText` in cases like this `sortText: SortText.JavascriptIdentifiers.toString();`.

I've pushed the draft to be sure that we on the same page because I'm not sure about the correctness of using the new enum for SortText.

File: src/services/completions.ts [hunk 6]
```diff
@@ -389,7 +401,7 @@ namespace ts.Completions {
 
     function createCompletionEntry(
         symbol: Symbol,
-        sortText: SortText,
+        sortText: string,
```
Comment (sheetalkamat) [inline src/services/completions.ts:404]:
```suggestion
        sortText: SortText
```

File: src/services/completions.ts [hunk 7]
```diff
@@ -10,7 +12,17 @@ namespace ts.Completions {
         AutoImportSuggestions = "6",
         JavascriptIdentifiers = "7"
```
Comment (sheetalkamat) [inline src/services/completions.ts:13]: Need `DeprecatedLocalDeclarationPriority ` and other deprecated enum values here,

File: src/services/completions.ts [hunk 8]
```diff
@@ -10,7 +12,17 @@ namespace ts.Completions {
...
+
+    enum SortTextId {
+        LocalDeclarationPriority,
+        LocationPriority,
+        OptionalMember,
+        MemberDeclaredBySpreadAssignment,
+        SuggestedClassMembers,
+        GlobalsOrKeywords,
+        AutoImportSuggestions,
+        Deprecated
```
Comment (sheetalkamat) [inline src/services/completions.ts:24]:
```suggestion
```

File: src/services/completions.ts [hunk 9]
```diff
@@ -10,7 +12,17 @@ namespace ts.Completions {
...
+    }
```
Comment (sheetalkamat) [inline src/services/completions.ts:26]:
```ts
    const DeprecatedSortTextStart = SortTextId.AutoImportSuggestion; + 2; // for Javascript identifiers since with this change they are preferred over deprecated symbols
```

File: src/services/completions.ts [hunk 10]
```diff
@@ -580,14 +592,16 @@ namespace ts.Completions {
...
             const origin = symbolToOriginInfoMap?.[i];
             const info = getCompletionEntryDisplayNameForSymbol(symbol, target, origin, kind, !!jsxIdentifierExpected);
-            if (!info || uniques.get(info.name) || kind === CompletionKind.Global && symbolToSortTextMap && !shouldIncludeSymbol(symbol, symbolToSortTextMap)) {
+            if (!info || uniques.get(info.name) || kind === CompletionKind.Global && symbolToSortTextIdMap && !shouldIncludeSymbol(symbol, symbolToSortTextIdMap)) {
                 continue;
             }
 
             const { name, needsConvertPropertyAccess } = info;
+            const sortTextId = symbolToSortTextIdMap && symbolToSortTextIdMap[getSymbolId(symbol)] || SortTextId.LocationPriority;
+            const sortText = (isDeprecated(symbol, typeChecker) ? sortTextId + SortTextId.Deprecated : sortTextId).toString();
```
Comment (sheetalkamat) [inline src/services/completions.ts:601]:
```suggestion
            const sortText = (isDeprecated(symbol, typeChecker) ? sortTextId + DeprecatedSortTextStart . : sortTextId).toString() as SortText;
```

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

**Review by sheetalkamat — APPROVED** [review]

File: src/services/completions.ts [hunk 11]
```diff
@@ -8,9 +10,27 @@ namespace ts.Completions {
...
+        LocationPriority,
+        OptionalMember,
+        MemberDeclaredBySpreadAssignment,
+        SuggestedClassMembers,
+        GlobalsOrKeywords,
+        AutoImportSuggestions
     }
-    export type Log = (message: string) => void;
+
+    const DeprecatedSortTextStart = SortTextId.AutoImportSuggestions + 2; // for Javascript identifiers since with this change they are preferred over deprecated symbols
```
Comment (DanielRosenwasser) [inline src/services/completions.ts:33]:
```suggestion
    // for JavaScript identifiers since with this change they are preferred over deprecated symbols
    const DeprecatedSortTextStart = SortTextId.AutoImportSuggestions + 2;
```

Not sure if anyone else has a preference for putting this one in the enum itself, but this is probably fine for now.

**Comment by DanielRosenwasser** [comment]
Thanks!
