### PR TITLE
fixAddMissingMember: Support interface and don't crash on type parameter

### LINKED ISSUE #25725: TypeError: Cannot read property 'symbol' of undefined
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:**

**Code**

```ts
TypeError: Cannot read property 'symbol' of undefined
    at getInfo (/usr/local/lib/node_modules/typescript/lib/tsserver.js:105474:44)
    at Object.getCodeActions (/usr/local/lib/node_modules/typescript/lib/tsserver.js:105371:28)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:103819:121
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:103819:23)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:111665:35
    at Object.flatMap (/usr/local/lib/node_modules/typescript/lib/tsserver.js:498:25)
    at Object.getCodeFixesAtPosition (/usr/local/lib/node_modules/typescript/lib/tsserver.js:111663:23)
    at IOSession.Session.getCodeFixes (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119225:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/usr/local/lib/node_modules/typescript/lib/tsserver.js:118099:61)
    at /usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:88
    at IOSession.Session.executeWithRequestId (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119380:28)
    at IOSession.Session.executeCommand (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119389:33)
    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:119409:35)
    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:120676:27)
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:** 

tsserver log id: 3897983895

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #25725

### CODE REVIEW

File: src/services/codefixes/fixAddMissingMember.ts [hunk 1]
```diff
@@ -80,37 +80,38 @@ namespace ts.codefix {
...
             const superDecl = superSymbol && find(superSymbol.declarations, isClassLike);
             if (superDecl) { res.push(superDecl); }
-            cls = superDecl;
+            decl = superDecl;
         }
         return res;
     }
 
+    type ClassOrInterface = ClassLikeDeclaration | InterfaceDeclaration;
     interface InfoBase {
```
Comment (amcasey) [inline src/services/codefixes/fixAddMissingMember.ts]: I'm not sure I understand the way the Info types are broken down.  Why isn't there a separate `InfoKind` for interface?  Is that uninteresting?  What's the advantage of having a base type if the members are redeclared in the subtypes?  Is there an advantage/disadvantage compared to just unioning the two subtypes?  Why does `EnumInfo` have fewer fields?

Comment (amcasey) [reply src/services/codefixes/fixAddMissingMember.ts]: Oh, I see that `Info` _is_ declared as a union type.  Why does `InfoBase` exist at all then?

File: src/services/codefixes/fixAddMissingMember.ts [hunk 2]
```diff
@@ -80,37 +80,38 @@ namespace ts.codefix {
...
         readonly kind: InfoKind;
         readonly token: Identifier;
-        readonly parentDeclaration: EnumDeclaration | ClassLikeDeclaration;
+        readonly parentDeclaration: EnumDeclaration | ClassOrInterface;
     }
     enum InfoKind { enum, class }
```
Comment (sheetalkamat) [inline src/services/codefixes/fixAddMissingMember.ts]: Do you really need this enum since you can do this check through parentDeclaration.kind ?

Comment (andy-ms) [reply src/services/codefixes/fixAddMissingMember.ts]: That currently wouldn't work to discriminate the union. See #18758.

File: src/services/codefixes/fixAddMissingMember.ts (hunk 1 above)
Comment (andy-ms) [reply src/services/codefixes/fixAddMissingMember.ts]: Having fewer cases in a union is better since each union type needs its own code to handle. `EnumInfo` has fewer fields because the code handling it is a completely separate path that does different things from the `ClassOrInterfaceInfo` case. That's necessary because enums work much differently than classes/interfaces, but for class/interface the handling is mostly the same and it's better to just test `isInterfaceDeclaration` when necessary.

**Comment by andy-ms** [comment]
@amcasey @sheetalkamat Please re-review
