### PR TITLE
Fix duplicated amd module comments in declaration bundle

### LINKED ISSUE #25588: Duplicated amd-module directives in tsc output when using outfile
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
duplicate amd module declarations
outFile produces duplicate module declarations

**Code**

tsconfig.json
```
{
    "compilerOptions":
    {
      "target": "es5",
      "module": "amd",
      "outFile": "build/index.js",
      "declaration" : true,
      "allowJs": false,
      "stripInternal": true,
      "emitDeclarationOnly": true
    },
    "include": [
      "src/SomeModule.ts"
    ]
}
```
SomeModule.ts
```ts
/// <amd-module name="mynamespace::SomeModule" />
export class SillyClass {
    private readonly _foo: string;
    constructor() {
        this._foo = "bar";
    }
}
```

after running tsc -p tsconfig.json, the generated typings file looks like this

build/index.d.ts (contains duplicated <amd-module> declaration)
```ts
/// <amd-module name="mynamespace::SomeModule" />
/// <amd-module name="mynamespace::SomeModule" />
declare module "mynamespace::SomeModule" {
    export class SillyClass {
        private readonly _foo;
        constructor();
    }
}
```

**Expected behavior:**
build/index.d.ts should look like
```ts
/// <amd-module name="mynamespace::SomeModule" />
declare module "mynamespace::SomeModule" {
    export class SillyClass {
        private readonly _foo;
        constructor();
    }
}
```

**Actual behavior:**
build/index.d.ts looks like 
```ts
/// <amd-module name="mynamespace::SomeModule" />
/// <amd-module name="mynamespace::SomeModule" />
declare module "mynamespace::SomeModule" {
    export class SillyClass {
        private readonly _foo;
        constructor();
    }
}
```

**Github example**  
https://github.com/bandersongit/typescript-duplicate-amd-module-name-issue/tree/master

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #25588

### CODE REVIEW

File: src/compiler/emitter.ts [hunk 1]
```diff
@@ -604,11 +604,13 @@ namespace ts {
...
         }
 
-        function setSourceFile(sourceFile: SourceFile) {
+        function setSourceFile(sourceFile: SourceFile | undefined) {
             currentSourceFile = sourceFile;
             currentLineMap = undefined;
             detachedCommentsInfo = undefined;
-            setSourceMapSource(sourceFile);
+            if (sourceFile) {
+                setSourceMapSource(sourceFile);
```
Comment (sheetalkamat) [inline src/compiler/emitter.ts]: Don't you need to reset it in sourceMap as well (to avoid accidental wrong sourceFile pick)?

Comment (weswigham) [reply src/compiler/emitter.ts]: `setSourceMapSource` very much does not handle `undefined` input. `sourceMapSource` is only used when emitting sourcemaps which is only used when descending into an actual file (emitting a node with a sourcemap pipeline phase, actually - versus printing comments at the top level of a bundle, where we set the current source file so we can get the text, and need to unset it before we call a function which uses it set-ed-ness to determine if it needs to print). It doesn't need to be unset partially because it expects to be defined in all places where it is used (unlike `currentSourceFile` which is actually checked).
