### PR TITLE
Instantiate this for contextually typed type parameters

### LINKED ISSUE #9673: Type inference error with generics and function 'this' typing
**TypeScript Version:**  typescript@2.1.0-dev.20160713

**Code**

```ts
interface JQuery {
    each<T>(
        collection: T[],
        callback: (this: T, indexInArray: number, valueOfElement: T) => any
    ): any;
}

let $: JQuery;
let list: string[];
$.each(list, function() {
    return this != 'abc';
});

```

**Expected behavior:**
No errors
**Actual behavior:** 
Operator '!=' cannot be applied to types 'T' and 'string'.

Notes:
- Explicit 'string' type parameter fixes the error: `$.each<string>(...)`, although the type is correctly inferred to string even without it.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #9673 

Previously `this` parameters were not instantiated when they came from a contextual signature. To fix this, I instantiate the signature in `getThisTypeOfSignature`. However, the mapper for the instantiation is only available much earlier, when checking the containing function. So I save the mapper on the containing function's signature &mdash; that signature is the one that will end up contextually typing `this` later.

This doesn't look right, though. The instantiation code is `signature = instantiateSignature(signature, signature.mapper);` and based on other instantiations in the code I don't think signatures with no target are even supposed to be instantiated, and not with their own mapper.

@ahejlsberg or @mhegazy any ideas on how to do this right? I thought about creating a new signature with the correct target/mapper setup, but I'm not sure how to make sure it gets used in place of the original one.

### CODE REVIEW

**Comment by sandersn** [comment]
@ahejlsberg can you look at this? I fixed this right before you got back from vacation, then went on vacation myself and forgot about it.

**Comment by sandersn** [comment]
The problem may actually be that thisParameter is instantiated too *early* compared to other parameters on the signature.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9082,15 +9082,15 @@ namespace ts {
...
-                const type = getContextuallyTypedThisType(container);
-                if (type) {
-                    return type;
-                }
 
                 const thisType = getThisTypeOfDeclaration(container);
                 if (thisType) {
                     return thisType;
                 }
+                const type = getContextuallyTypedThisType(container);
```
Comment (sandersn) [inline src/compiler/checker.ts]: I had to save this block for contextually-typed object literals like this:

```ts
interface CI {
  m: number
  method(this: this, n: number);
}
let o: CI = {
  m: 12,
  method(n) {
    return this.m + n;
  }
}
```

Comment (sandersn) [inline src/compiler/checker.ts]: Based on our in-person discussion, I checked on contextual typing for parameters. It's 1 of 9 cases in `getTypeForVariableLikeDeclaration`: 

```ts
                const type = declaration.symbol.name === "this"
                    ? getContextuallyTypedThisType(func)
                    : getContextuallyTypedParameterType(<ParameterDeclaration>declaration);
```

The contextual typing for an undeclared `this` is basically the same thing here in `checkThisExpression` since there is no parameter to get the type of.

**Comment by sandersn** [comment]
I tried moving the contextual typing out of `checkThisExpression` to `getSignatureFromDeclaration` and it passes our tests. @ahejlsberg how does it look to you?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9326,11 +9330,11 @@ namespace ts {
             }
         }
 
-        function getContextuallyTypedThisType(func: FunctionLikeDeclaration): Type {
+        function getContextuallyTypedThisParameter(func: FunctionLikeDeclaration): Symbol {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: I think a better name would be `getContextualThisParameter`.

**Comment by ahejlsberg** [comment]
:+1: Once you make the suggested name change.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [inline src/compiler/checker.ts]: done
