### PR TITLE
Remove redundant call to `checkNodeDeferred`

### LINKED ISSUE #22491: Block statement in arrow function is checked twice
**TypeScript Version:**  master

Enable the `Debug.fail()` in `registerForUnusedIdentifiersCheck` (added in #22361). We are checking it a second time via `checkDeferredNodes`.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #22491 
If I have this right, we will always do one more check after all `SkipContextSensitive` checks.
Before this PR, the assertion (also added in this PR) would have failed for most arrow functions in call expressions.

For posterity, a simple test case that failed was:
```ts
// @noUnusedLocals: true
// @noUnusedParameters: true
declare function f<T>(a: (s: string) => T): void;
f(s => s);
```
(we have lots of test cases like this already, so didn't see a need to add a new one.)

### CODE REVIEW

**Comment by andy-ms** [comment]
> It means we recheck the grammar during every every inference pass, which seems wasteful.

I wonder if it wouldn't impact performance to just move all the grammar checking out to its own tree walk -- would certainly make the code easier to read.

**Comment by weswigham** [comment]
@andy-ms We effectively already do js-only grammar checks in a separate tree walk in `program`, so it can't be _that_ bad.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21564,6 +21563,7 @@ namespace ts {
 
         function registerForUnusedIdentifiersCheck(node: Node) {
             if (deferredUnusedIdentifierNodes) {
+                Debug.assert(!contains(deferredUnusedIdentifierNodes, node), "Registering unused identifier twice");
```
Comment (sandersn) [inline src/compiler/checker.ts]: actually, isn't the contains call slow? I imagine the list gets long.

Comment (weswigham) [reply src/compiler/checker.ts]: Yeah `contains` is a linear search - `binarySearch` would be a bit better, but best would just be using a map instead.
