### PR TITLE
fix(sourcemap): accept a sourceMappingURL that ends with a newline

### LINKED ISSUE #45982: Cannot detect sourceMappingURL if there is a trailing newline
After I upgraded my TypeScript I noticed my sourcemaps broke. I bisected down to #44197, which
seem to subtly change the regex matching the sourceMappingURL so that it will not match
if the line ends with '\n'.

I generate my d.ts myself and they have a trailing newline.
```ts
export function foo(): number;
//# sourceMappingURL=/path/to/my/file.d.ts.map
<-- this line is blank
```

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Fixes #45982

After I upgraded my TypeScript I noticed my sourcemaps broke. I bisected down to #44197, which
seem to subtly change the regex matching the sourceMappingURL so that it will not match
if the line ends with '\n'.

The old regex ended with `\s*` to match and trim all whitespace.
The new regex doesn't have that I guess for performance? But because `.` does not match `\n`, and
getLineText preserves the ending `\n`, this does not match any line that isn't the last one in the
file.

I am happy to add a test if someone points me to the correct place for it. I tried to add
a fourslash test but I couldn't seem to create a file where the last line was a newline.

### CODE REVIEW

File: src/compiler/sourcemap.ts [hunk 1]
```diff
@@ -322,7 +322,7 @@ namespace ts {
     }
 
     // Sometimes tools can see the following line as a source mapping url comment, so we mangle it a bit (the [M])
-    const sourceMapCommentRegExp = /^\/\/[@#] source[M]appingURL=(.+)$/;
+    const sourceMapCommentRegExp = /^\/\/[@#] source[M]appingURL=(.+)\n?$/;
```
Comment (weswigham) [inline src/compiler/sourcemap.ts:325]: Also include `\r?`, just in case~

**Review by weswigham — CHANGES_REQUESTED** [review]

File: src/compiler/sourcemap.ts (hunk 1 above)
Comment (weswigham) [inline src/compiler/sourcemap.ts:325]:
```suggestion
    const sourceMapCommentRegExp = /^\/\/[@#] source[M]appingURL=(.+)\r?\n?$/;

```
