### PR TITLE
Fix auto imports in JS files in nodenext

### LINKED ISSUE #54350: Auto import suggests ES imports in JS file that uses CommonJS
# Bug Report

### 🔎 Search Terms

auto import require

### 💻 Code

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "checkJs": true,
    "noEmit": true,
    "resolveJsonModule": true
  }
}
```

```ts
// @Filename: matrix.js
exports.variants = [];

// @Filename: main.js
exports.dedupeLines = data => {
  variants/**/
};
```

### 🙁 Actual behavior

Suggests `import { variants } from "./matrix";`

### 🙂 Expected behavior

Suggests `const { variants } = require("./matrix")` since `exports.dedupeLines` indicates CJS

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #54350

### CODE REVIEW

File: tests/cases/fourslash/autoImportNodeNextJSRequire.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+// @Filename: /matrix.js
+//// exports.variants = [];
+
+// @Filename: /main.js
+//// exports.dedupeLines = data => {
+////   variants/**/
+//// }
+
+// @Filename: /totally-irrelevant-no-way-this-changes-things-right.js
+//// export default 0;
```
Comment (andrewbranch) [inline tests/cases/fourslash/autoImportNodeNextJSRequire.ts:17]: We were using the presence of ES module syntax in other files as an indicator of what to use, but `--module nodenext` is a stronger signal—we should default to syntax that won’t crash in Node.

**Review by jakebailey — APPROVED** [review]

File: src/services/codefixes/importFixes.ts [hunk 2]
```diff
@@ -803,14 +803,19 @@ function shouldUseRequire(sourceFile: SourceFile, program: Program): boolean {
...
+    // 4. In --module nodenext, assume we're not emitting JS -> JS, so use
+    //    whatever syntax Node expects based on the detected module kind
+    if (sourceFile.impliedNodeFormat === ModuleKind.CommonJS) return true;
+    if (sourceFile.impliedNodeFormat === ModuleKind.ESNext) return false;
+
+    // 5. Match the first other JS file in the program that's unambiguously CJS or ESM
     for (const otherFile of program.getSourceFiles()) {
         if (otherFile === sourceFile || !isSourceFileJS(otherFile) || program.isSourceFileFromExternalLibrary(otherFile)) continue;
         if (otherFile.commonJsModuleIndicator && !otherFile.externalModuleIndicator) return true;
         if (otherFile.externalModuleIndicator && !otherFile.commonJsModuleIndicator) return false;
```
Comment (sheetalkamat) [inline src/services/codefixes/importFixes.ts:815]: when checking with other file, would it be better to check their implied node format as well to determine what this file probably is supposed to be.

Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:815]: Because of the new checks I added, all files in the program are guaranteed to have an `undefined` `impliedNodeFormat`. `impliedNodeFormat` is always set to one of the two options I checked for, or else it’s not used at all in the program’s module mode.

Comment (sheetalkamat) [reply src/services/codefixes/importFixes.ts:815]: Isnt it set by looking up package.json in ancestor directory so is it not possible to have impliedNodeFormat not set on one file vs other ?

Comment (andrewbranch) [reply src/services/codefixes/importFixes.ts:815]: If no package.json is found, it defaults to CJS. (This reflect’s Node’s behavior too. The choice is binary; the field is only optional because it’s not used outside of `--module nodenext`.)
