### PR TITLE
fix(45233): export default can not be typed via jsdoc

### LINKED ISSUE #45233: export default can not be typed via jsdoc
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about jsdoc and export default

### ⏯ Playground Link

```ts
/**
 * The complete Triforce, or one or more components of the Triforce.
 * 
 * @typedef {Object} WishGranter
 * @property {boolean} hasCourage - Indicates whether the Courage component is present.
 * @property {boolean} hasPower - Indicates whether the Power component is present.
 * @property {boolean} hasWisdom - Indicates whether the Wisdom component is present.
 */

/** @type {WishGranter} */
const works = {
  hasCourage: true,
  foo: false // correctly errors
}

// does not work for export default

/** @type {WishGranter} */
export default {
  hasCourage: true,
  foo: false // no error
}

// workaround that "breaks" prettier e.g. you can't format anymore as it will remove the `()`
// https://github.com/prettier/prettier/issues/11279

///** @type {WishGranter} */
//export default ({
//  // type RocketCliConfig
//});
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?filetype=js#code/PQKhFgCgAIWgVAFgU2gYwPYFsAOAbZAF1XgCcBLAMw1LWQBpoamA7VZrG1TXDNlwgGcmlaIRQIK1WsgB0UWNAVwAAoQCeOZABNkogN4B5AEYArZGkIBfaAHVygxAHFSAQwHJSy6CpykMWqQa0PrGGBgE7jaIroIAwhgArm4A5qgAtNAAkiza5GiuxMIA7ijinmISCcmuaejYOHzIAtAO0H7Igs2E8jCqfgGewaHhkSzRsQAKGMUVmTl5BUXQpUQopJWo07MbPI38hK3CHV0CvYq+-oHDYRHIUdAxgvaC2tjQ87n5hZ0rZeubOwON5Yeq8A5HdqkTrdc4gYBQKCgVQaLQhF7ONweUg2eFQTAsQSHYo0ADWwgAvCEFI9YtVUsgAFxiUiJBg06gYZmUVx4LrQYDAeqkaGWPDqaCefykQRQKyIyCC6BvX4sDDEsnQaSSgAejSCyr0rkSeEICuRPlRqH0GJc7mIONgCMgyD1NEOuh5JsO+hpT3ptSZLLZ9A54W5vP5SrVkpFNDl5qFJNIpNc-kSuUqhWgACJjNDXOSc1CiIRyBU5ClZNB1El0O4AOSHaRYbPudScaHQWKtYnkPB4aDQzgAN1Q5WgAAMABQASknSKFiEIhBwgkZgpS5HEiWMsh4wA6K-LpEP0OPnmADkEbMEwAAjPeAEwAdgAnImLWpNNbbViHbizqCq6+oeka3rQNOvqKkKApCla0AAEoYGgpJEHEeDkAkLCUOQKSLlYs4ANxAA)
      

### 💻 Code

```ts
/** @type {import('rocket/cli').RocketCliConfig} */
export default {
  // "no" type - e.g. any
} 
```

### 🙁 Actual behavior

It does not put any type for export default.

### 🙂 Expected behavior

```ts
/** @type {import('rocket/cli').RocketCliConfig} */
export default {
  // type RocketCliConfig
} 
```

### 😅  Workaround

A possible workaround is to typecast via `()` but that "breaks" prettier as it will always remove it as "usless" brackets.
See https://github.com/prettier/prettier/issues/11279

```ts
/** @type {import('rocket/cli').RocketCliConfig} */
export default ({
  // type RocketCliConfig
})
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45233

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -38841,11 +38841,17 @@ namespace ts {
             if (!checkGrammarDecoratorsAndModifiers(node) && hasEffectiveModifiers(node)) {
                 grammarErrorOnFirstToken(node, Diagnostics.An_export_assignment_cannot_have_modifiers);
             }
+
+            const typeTag = isInJSFile(node) ? getJSDocTypeTag(node) : undefined;
+            if (typeTag) {
+                checkAssertionWorker(typeTag.typeExpression.type, typeTag.typeExpression.type, node.expression);
```
Comment (sandersn) [inline src/compiler/checker.ts:38847]: I think this annotation should be treated like a declaration, not a cast. Specifically, that means the assignability is stricter.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -38841,11 +38841,17 @@ namespace ts {
             if (!checkGrammarDecoratorsAndModifiers(node) && hasEffectiveModifiers(node)) {
                 grammarErrorOnFirstToken(node, Diagnostics.An_export_assignment_cannot_have_modifiers);
             }
+
+            const typeTag = isInJSFile(node) ? getJSDocTypeTag(node) : undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts:38845]: getEffectiveTypeAnnotation instead of getJSDocTypeTag? It probably does the same thing now, but might be more flexible later.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -38841,11 +38841,17 @@ namespace ts {
             if (!checkGrammarDecoratorsAndModifiers(node) && hasEffectiveModifiers(node)) {
                 grammarErrorOnFirstToken(node, Diagnostics.An_export_assignment_cannot_have_modifiers);
             }
+
+            const typeTag = isInJSFile(node) ? getJSDocTypeTag(node) : undefined;
+            if (typeTag) {
+                checkAssertionWorker(typeTag.typeExpression.type, typeTag.typeExpression.type, node.expression);
+                return;
```
Comment (sandersn) [inline src/compiler/checker.ts:38848]: I feel like we should add type checking to both TS and JS, and TS will never have a type annotation. In that case, returning is not correct; instead it should check the type and continue.

I'm not sure how to make sure that the type of `export default` is the annotation type instead of the expression type either.

File: tests/cases/compiler/checkJsdocTypeTagOnExportAssignment1.ts [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+// @filename: checkJsdocTypeTagOnExportAssignment1.js
+
+// @Filename: a.js
+/**
+ * @typedef {Object} Foo
+ * @property {boolean} a
+ * @property {boolean} b
+ */
+
+/** @type {Foo} */
```
Comment (sandersn) [inline tests/cases/compiler/checkJsdocTypeTagOnExportAssignment1.ts:13]: Please add another file that shows that the type of `import a from './a'` is `Foo` and not `{ c: boolean }`.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: tests/baselines/reference/checkJsdocTypeTagOnExportAssignment4.types [hunk 5]
```diff
@@ -0,0 +1,12 @@
+=== tests/cases/compiler/checkJsdocTypeTagOnExportAssignment4.js ===
+
+No type information for this code.=== tests/cases/compiler/a.js ===
+/**
+No type information for this code. * @typedef {number} Foo
+No type information for this code. */
+No type information for this code.
+No type information for this code./** @type {Foo} */
+No type information for this code.export default "";
```
Comment (sandersn) [inline tests/baselines/reference/checkJsdocTypeTagOnExportAssignment4.types:9]: wow, our baselining code sure doesn't expect `export default` to have a type, I see. =(

File: tests/baselines/reference/checkJsdocTypeTagOnExportAssignment3.types [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+/** @type {Foo} */
+export default bar;
+>bar : { c: number; }
+
+=== tests/cases/compiler/b.js ===
+import a from "./a";
+>a : { c: number; }
+
+a;
+>a : { c: number; }
```
Comment (sandersn) [inline tests/baselines/reference/checkJsdocTypeTagOnExportAssignment3.types:25]: This is wrong, it should be `Foo` or maybe `{ a: boolean, b: boolean }`

File: tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+
+// @Filename: a.ts
+export interface Foo {
+    a: number;
+    b: number;
+}
+
+// @Filename: b.js
+/** @type {import("./a").Foo} */
+export default { c: false };
```
Comment (sandersn) [inline tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts:14]: can you show that this only allows assignability in one direction with a supertype -> subtype assignment like `{ a: 1 }`?

(it doesn't have to be this test, it could be any of them or a new one)

**Review by sandersn — CHANGES_REQUESTED** [review]
I like the way the code looks now, although one of the type baselines is wrong.

File: tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts (hunk 7 above)
Comment (a-tarasyuk) [reply tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts:14]: I've added two additional tests (`checkJsdocTypeTagOnExportAssignment5/6.ts`), I hope I understand your point correctly.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -9349,6 +9349,10 @@ namespace ts {
             if (!links.type) {
                 const targetSymbol = resolveAlias(symbol);
                 const exportSymbol = symbol.declarations && getTargetOfAliasDeclaration(getDeclarationOfAliasSymbol(symbol)!, /*dontResolveAlias*/ true);
+                const declaredType = firstDefined(exportSymbol?.declarations, d => isExportAssignment(d) ? tryGetTypeFromEffectiveTypeNode(d) : undefined);
```
Comment (sandersn) [inline src/compiler/checker.ts:9352]: please inline this into the conditional expression, below the isDuplicatedCommonJSExport/autoType case.

File: tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts (hunk 7 above)
Comment (sandersn) [reply tests/cases/compiler/checkJsdocTypeTagOnExportAssignment2.ts:14]: I meant that I wanted to see an error for assigning `{ a } ==> { a, b }` but not for `{ a, b, c } ==> { a, b }`. Sorry about not being clearer.

**Review by sandersn — CHANGES_REQUESTED** [review]

File: src/compiler/checker.ts (hunk 8 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts:9352]: @sandersn Thanks for the feedback.

> I meant that I wanted to see an error for assigning { a } ==> { a, b } but not for { a, b, c } ==> { a, b }. Sorry about not being clearer.

Similar to variable assignments, like so [Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJwBcyIArgLYBG0A3LgL664A2EYRAjKRlgLw4ipLgBpk1EckZ1kAejnIAolCjooLdp2rJB2YcjESpMthyIAmXpl0TZC5AHkA1sgD8H3EA)?

Comment (sandersn) [reply src/compiler/checker.ts:9352]: More like [this Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJwBcyIArgLYBG0A3MtaRTdLgL664A2EYRARlIZ0PPkWQBeHEVIDknXvzjUEUmSWQCANIzm6EchXVxx50uAwD0V5AFEoUdFFPmiq67YDyAa2QB+QNwgA)

Comment (a-tarasyuk) [reply src/compiler/checker.ts:9352]: Does [`checkJsdocTypeTagOnExportAssignment6`](https://github.com/microsoft/TypeScript/blob/db74fad86556e37298ae3def41fbddec8e6f14ea/tests/baselines/reference/checkJsdocTypeTagOnExportAssignment6.errors.txt) cover that case partially?

Comment (a-tarasyuk) [reply src/compiler/checker.ts:9352]: I've updated tests [`checkJsdocTypeTagOnExportAssignment6`](https://github.com/microsoft/TypeScript/blob/0df00efba7fd2b55d227acbe544cc90ec056a9ad/tests/cases/compiler/checkJsdocTypeTagOnExportAssignment6.ts), [`checkJsdocTypeTagOnExportAssignment7`](https://github.com/microsoft/TypeScript/blob/eaa42398d2dd065741d9e0b5254099ac6172065f/tests/cases/compiler/checkJsdocTypeTagOnExportAssignment7.ts).

**Review by sandersn — APPROVED** [review]
