### PR TITLE
Fix for #5058 - Exclude implemented interface functions from autocompletion suggestions.

### LINKED ISSUE #5058: Method syntax not accounted for in object literal completion filtering
methodsnotaccountedfor

```
interface I {
    a(): void;
    b(): void;
}

var x: I {
    a: () => { },
    /**/
}
```

Request completion at the `/**/`. `a` should not appear in the list.

Now change the declaration of `a` to a method declaration:

```TypeScript
interface I {
    a(): void;
    b(): void;
}

var x: I {
    a() { },
    /**/
}
```

Request completion at the `/**/`. `a` now *does* appear in the completion list.

### PR DESCRIPTION
**Pull request by DanCorder**
This fixes the issue and doesn't break any other tests, however I don't understand the comment on line 3751. Hopefully I haven't missed anything.

____

*Edit by @DanielRosenwasser: Fixes #5058*

### CODE REVIEW

File: tests/cases/fourslash/completionListImplementingInterfaceFunctions.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+////    a() {},
+////    /*0*/
+////}
+////
+////interface I2 {
+////    a(): void;
+////    b(): void;
+////}
+////
+////var imp2: I2 {
```
Comment (DanielRosenwasser) [inline tests/cases/fourslash/completionListImplementingInterfaceFunctions.ts]: Can you get rid of `I2` and just use `I1` to keep the test minimal?

**Comment by DanielRosenwasser** [comment]
Thanks for the PR @DanCorder. I left some feedback but all else looks great.

As another heads up, GitHub doesn't link the issues unless the issue number is referenced in the PR body. I've gone ahead and added that for you.

**Comment by DanCorder** [comment]
Thanks for the heads up, I've updated the test.
