### PR TITLE
Make anonymous function formatting apply to anonymous generators too

### LINKED ISSUE #30675: VS Code incorrectly inserting spaces after function before parentheses
Issue Type: <b>Bug</b>

VS Code is incorrectly inserting a space between `function*` and `()` for anonymous functions.
The gif below shows the first function correctly being formatted with the space removed. The second function shows vscode incorrectly formatting the function with a space.
vscode_space_formatting

This is causing conflict when used with `prettier`.

I have all space formatters turned off in vscode and auto-format on save turned on.
image

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (4.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.25.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|0.3.1403
vscode-docker|Pet|0.6.1
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.4.0

</details>

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #30675

### CODE REVIEW

File: src/services/formatting/rules.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ namespace ts.formatting {
             rule("SpaceAfterConditionalClosingParen", SyntaxKind.CloseParenToken, SyntaxKind.OpenBracketToken, [isControlDeclContext], RuleAction.Space),
 
             rule("NoSpaceBetweenFunctionKeywordAndStar", SyntaxKind.FunctionKeyword, SyntaxKind.AsteriskToken, [isFunctionDeclarationOrFunctionExpressionContext], RuleAction.Delete),
-            rule("SpaceAfterStarInGeneratorDeclaration", SyntaxKind.AsteriskToken, [SyntaxKind.Identifier, SyntaxKind.OpenParenToken], [isFunctionDeclarationOrFunctionExpressionContext], RuleAction.Space),
+            rule("SpaceAfterStarInGeneratorDeclaration", SyntaxKind.AsteriskToken, SyntaxKind.Identifier, [isFunctionDeclarationOrFunctionExpressionContext], RuleAction.Space),
```
Comment (andrewbranch) [inline src/services/formatting/rules.ts]: Removed OpenParen from the list because that should be handled only by `SpaceBeforeOpenParenInFuncDecl` or `SpaceAfterAnonymousFunctionKeyword` to minimize the number of competing rules.

File: src/services/formatting/rules.ts [hunk 2]
```diff
@@ -241,8 +241,8 @@ namespace ts.formatting {
...
 
             // Insert space after function keyword for anonymous functions
-            rule("SpaceAfterAnonymousFunctionKeyword", SyntaxKind.FunctionKeyword, SyntaxKind.OpenParenToken, [isOptionEnabled("insertSpaceAfterFunctionKeywordForAnonymousFunctions"), isFunctionDeclContext], RuleAction.Space),
-            rule("NoSpaceAfterAnonymousFunctionKeyword", SyntaxKind.FunctionKeyword, SyntaxKind.OpenParenToken, [isOptionDisabledOrUndefined("insertSpaceAfterFunctionKeywordForAnonymousFunctions"), isFunctionDeclContext], RuleAction.Delete),
+            rule("SpaceAfterAnonymousFunctionKeyword", [SyntaxKind.FunctionKeyword, SyntaxKind.AsteriskToken], SyntaxKind.OpenParenToken, [isOptionEnabled("insertSpaceAfterFunctionKeywordForAnonymousFunctions"), isFunctionDeclContext], RuleAction.Space),
+            rule("NoSpaceAfterAnonymousFunctionKeyword", [SyntaxKind.FunctionKeyword, SyntaxKind.AsteriskToken], SyntaxKind.OpenParenToken, [isOptionDisabledOrUndefined("insertSpaceAfterFunctionKeywordForAnonymousFunctions"), isFunctionDeclContext], RuleAction.Delete),
```
Comment (andrewbranch) [inline src/services/formatting/rules.ts]: This rule is now a slight misnomer since we look at more than just `SyntaxKind.FunctionKeyword`, but I think it matches users' intuition (at least #30675 seems to support that theory).

File: tests/cases/fourslash/generatorDeclarationFormatting.ts [hunk 3]
```diff
@@ -7,4 +7,4 @@ format.document();
 goTo.marker('1');
 verify.currentLineContentIs("function* g() { }");
 goTo.marker('2');
-verify.currentLineContentIs("var v = function* () { };");
\ No newline at end of file
+verify.currentLineContentIs("var v = function*() { };");
```
Comment (andrewbranch) [inline tests/cases/fourslash/generatorDeclarationFormatting.ts]: 🚨 Note that treating `SpaceAfterAnonymousFunctionKeyword` differently actually changes the long-standing default for anonymous generators. If that's undesirable, I can probably add a FormattingContext filter, but personally I think this is probably more consistent.
