### PR TITLE
Rest of untyped binding pattern is { [s: string]: any }

### LINKED ISSUE #12519: Object rest destructuring parameter defaults to empty object, causing errors when untyped
Using the latest release-2.1 branch, I'm seeing the following behavior.

I'm writing some React/JSX code, and using a pattern often seen in code in the wild, namely:

```tsx
var fails = ({myId, ...others}) => <div id={myId}>{others.anything}</div>;
```

However, the above is in error, as the type inferred for `...others` is the empty object (`{}`). Thus the expression within the DIV tags gives the error `Property 'anything' does not exist on type '{}'`.

If I explicitly type the parameter then all is OK. Namely:

```tsx
interface Sample {
    myId: string;
    anything: number;
}

var works = ({myId, ...others}: Sample) => <div id={myId}>{others.anything}</div>;
```

It seems to me that for the ease of writing (and porting existing code), `...others` above should default to `any`, as other untyped parameters do.

This may have already been discussed in some of the other rest/spread discussions. I did trying to find a definitive explanation, but those threads were quite verbose. Apologies if already covered.

Ping @sandersn , @RyanCavanaugh , @mhegazy

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #12519 

Edit:
@mhegazy pointed out that (1) rest of an untyped binding pattern isn't really any since it's definitely not a function (2) adding an index signature results in a more straightforward fix. So the current version adds an index signature to the structurally inferred type of an untyped binding pattern.

### CODE REVIEW

File: tests/cases/conformance/types/rest/objectRest.ts [hunk 1]
```diff
@@ -36,3 +36,5 @@ let computed = 'b';
 let computed2 = 'a';
 var { [computed]: stillNotGreat, [computed2]: soSo,  ...o } = o;
 ({ [computed]: stillNotGreat, [computed2]: soSo, ...o } = o);
+
+var noContextualType = ({ aNumber = 12, ...notEmptyObject }) => aNumber;
```
Comment (mhegazy) [inline tests/cases/conformance/types/rest/objectRest.ts]: can you add a test where notEmptyObject.somePropoerty is used, to make sure we get an error if the behavior changes, instead of just the type-baseline changes.

Comment (mhegazy) [inline tests/cases/conformance/types/rest/objectRest.ts]: also can you add a test for `--noImplicitAny` error for this case.

**Comment by mhegazy** [comment]
I think this looks much better.

**Comment by mhegazy** [comment]
@ahejlsberg any comments?

File: tests/cases/conformance/types/rest/objectRest.ts (hunk 1 above)
Comment (sandersn) [inline tests/cases/conformance/types/rest/objectRest.ts]: Wait&mdash;actually this doesn't allow arbitrary access to properties, just indexed access.

Comment (sandersn) [inline tests/cases/conformance/types/rest/objectRest.ts]: OK, so I added back the special case. Which makes the two tests you asked for pass.
