### PR TITLE
Defer type comparability check for assertions

### LINKED ISSUE #52813: Inconsistent errors reported between `tsc` and VSCode
# Bug Report

The basic problem looks like this:

1) I run `tsc` directly from the command line and get **Set A** of errors.
2) VSCode instead shows **Set B** of errors which can be wildly different than **Set A**
3) If I issue the *TypeScript: Restart TS Server* command to VSCode, I will then start to just see **Set A** errors in my IDE
4) However... if I go and make a small change to a file I start only seeing **Set B** errors again.

**Set B** errors seem completely wrong since the `tsc` doesn't produce them. HOWEVER, a specfically unique error in **Set B** seems to be causing this weird behavior:

```
'Value' implicitly has type 'any' because it does not have a type annotation and is referenced directly
or indirectly in its own initializer.ts(7022)
```

If I solve this error with an explicit type assertion, the inconsistency goes away and I resume seeing **Set A** errors.

My project does rely on a deep set of types involving conditionals and generics. This seems to have something to do with causing this problem. I've provided a repository below with steps on how to reproduce. I would try to narrow the behavior down to a simpler project+repo but do not have the time at the moment.

[Original Discord discussion](https://discord.com/channels/508357248330760243/508357248330760249/1075837205261582346)

### 🔎 Search Terms

inconsistency, inconsistent, errors, ts language server,

### 🕗 Version & Regression Information
This issue was tested and occurs in TypeScript 4.9 and the latest nightly build as of this writing (5.0.0-dev.20230216).

### ⏯ Playground Link

Unfortunately I'm unable to reproduce this with the TS Playground

[Repo+Branch that reproduces the issue](https://github.com/frank-weindel/Lightning-ui/tree/ts-vscode-error-consistency-issue)

- Navigate to `Stepper.ts` line 77. See the TSDoc comment there for reproducibility steps. It can some times take a few file modifications to trigger the behavior.
- I was able to reproduce the same issue using GitHub Codespaces.

### 💻 Code

See Repo above.

### 🙁 Actual behavior

- TypeScript errors reported by VSCode are inconsistent with the ones reported by running `tsc` via the command line.
- VSCode can be temporarily made consistent by restarting the TS Server.
- A single error seems to be causing TS+VSCode to act in this way.

### 🙂 Expected behavior

- TypeScript errors reported by VSCode should always match with the ones reported by running `tsc` via the command line.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #52813.

This is the fix that is implemented as deferring the type comparability check we do for assertions, and it fixes the circularity case in the original issue.
However, we can still trigger circularity errors when computing variance, as one of the new tests shows, because we can't always defer the check that makes us compute variances.

I'll attempt a different fix next that involves "resetting" the type resolution stack when we start to compute variances.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this
@typescript-bot run DT
@typescript-bot test this
@typescript-bot user test this
@typescript-bot test top100

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

**Comment by gabritto** [comment]
@typescript-bot perf test this
@typescript-bot run DT
@typescript-bot test this
@typescript-bot user test this
@typescript-bot test top100
@typescript-bot test tsserver top100

**Comment by gabritto** [comment]
@typescript-bot perf test this faster

File: tests/cases/compiler/classVarianceCircularity.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// @strict: true
+
+// Issue #52813
```
Comment (gabritto) [inline tests/cases/compiler/classVarianceCircularity.ts:3]: This is an example where this PR's approach doesn't solve the circularity problem.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -34305,16 +34305,51 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        switch (node.kind) {
+            case SyntaxKind.AsExpression:
+            case SyntaxKind.TypeAssertionExpression:
+                type = node.type;
+                expression = node.expression;
+                break;
+            case SyntaxKind.ParenthesizedExpression:
+                type = getJSDocTypeAssertionType(node);
+                expression = node.expression;
+                break;
```
Comment (weswigham) [inline src/compiler/checker.ts:34320]: Maybe extract this into a helper?
```ts
function getTypeAndExpressionFromAssertion(node: AssertionExpression | JSDocTypeAssertion): { type: TypeNode, expression: Expression } {
        switch (node.kind) {
            case SyntaxKind.AsExpression:
            case SyntaxKind.TypeAssertionExpression:
                return node;
            case SyntaxKind.ParenthesizedExpression:
                return { type: getJSDocTypeAssertionType(node), expression: node.expression };
        }
}
```

So this and the other call site can just be
```ts
const {type, expression} = getTypeAndExpressionFromAssertion(node);
```

File: tests/cases/compiler/classVarianceCircularity.ts (hunk 1 above)
Comment (weswigham) [reply tests/cases/compiler/classVarianceCircularity.ts:3]: I assume you mean the other test with the function calls rather than expressions, since that's the one that still has an error. :) If you want, you should file an issue about the other form, so the issue can still get backlog'd, if you want to consider looking into a broader fix in the future after this PR marks the original issue as fixed.

**Review by weswigham — APPROVED** [review]
Looks good, just a small style suggestion to remove some duplication.

**Comment by gabritto** [comment]
It's kinda unfortunate that there seems to be a slight perf impact on check time, but I don't immediately see what could be done to improve this, since my previous attempts to either defer the call to `checkExpression` or to use `checkExpressionCached` led to bad results, so...
