### PR TITLE
goToDefinition: Use the name of a declaration (if possible) when creating DefinitionInfo

### LINKED ISSUE #12270: Go to Symbol should position text cursor on name of target
_From @chrmarti on October 31, 2016 14:48_

- VSCode Version: Code - Insiders 1.7.0-insider (0706b425537d8cfe2766eac00662ecf988c7ed7f, 2016-10-28T13:00:19.188Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.3|
|vscode-docker|PeterJausovec|0.0.6|
|regex|chrmarti|0.0.6|
|vscode-eslint|dbaeumer|1.0.7|
|ghlink|dt|0.0.4|
|gitlens|eamodio|0.5.5|
|tslint|eg2|0.5.39|
|PowerShell|ms-vscode|0.7.2|
|csharp|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|2.1.0|
|diff|rafaelmaiolla|0.0.1|
|kustovscode|seanmcbreen|0.0.1|
|vscode-open-in-github|sysoev|1.2.0|

---

Steps to Reproduce:

1. Go to Symbol that's a class or a class member (possibly others)
2. The text cursor is positioned on the first modifier before the name

This breaks the flow of keyboard navigation for actions like Find All References, Rename Symbol, etc., because the user now has to navigate the cursor to the symbol's name first.

_Copied from original issue: Microsoft/vscode#14759_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #12270

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -4318,6 +4318,10 @@ namespace ts {
         return createTextSpan(start, end - start);
     }
 
+    export function createTextSpanFromNode(node: Node, sourceFile?: SourceFile): TextSpan {
```
Comment (mhegazy) [inline src/compiler/utilities.ts]: wrong utlities.ts file, you probably want src/services/utilites.ts instead.
