### PR TITLE
Stricter criteria for eliminating types in unions during inference

### LINKED ISSUE #32752: Regression with `await` type extraction in strict mode
**TypeScript Version:** 3.6.0-dev.20190807 (worked up to 3.6.0-dev.20190804)

**Search Terms:** await type promise

**Code**

```ts
const containsPromises: unique symbol = Symbol();

type DeepPromised<T> =
    { [containsPromises]?: true } &
    {
        [TKey in keyof T]: T[TKey] | DeepPromised<T[TKey]> | Promise<DeepPromised<T[TKey]>>
    };

async function fun<T>(deepPromised: DeepPromised<T>) {

    const deepPromisedWithIndexer:
        DeepPromised<{ [name: string]: {} | null | undefined }> = deepPromised;

    for (const value of Object.values(deepPromisedWithIndexer)) {

        const awaitedValue = await value;

        if (awaitedValue)
            await fun(awaitedValue);
    }
}
```
(Compile with `--strict`!)

**Expected behavior:**
No compile error as in TS 3.5.3.

**Actual behavior:**

```plain
TypeScriptIssueNext.ts:21:23 - error TS2345: Argument of type '{} | ({ [containsPromises]?: true | undefined; } & {})' is not assignable to parameter of type 'DeepPromised<{ [containsPromises]?: undefined; }>'.
  Types of property '[containsPromises]' are incompatible.
    Type 'true | undefined' is not assignable to type '(true & Promise<never>) | undefined'.
      Type 'true' is not assignable to type '(true & Promise<never>) | undefined'.

21             await fun(awaitedValue);
                         ~~~~~~~~~~~~
```

**Playground Link:** [Here](https://www.typescriptlang.org/play/?target=6#code/MYewdgzgLgBKZQIYEtIAUBOIC2yIFMIAuGAVzGQEdT8YIBPbAIxABsYBeGAZUZdYAUASgDcAWABQkqPQAOtACL58szDjz4AJgB4AKgD5OkmCZgBvGAG14SVBDW4CEALoB+ElAw0YAXxgAyY1MzINNTS10AaXx6GFQYAGsYkAAzGF1nEl0I6PpnGAAfGCUVBw0dbKiY50MisoJtEtUsRy09HOr9fVDfcSkJRAYwYBgU8mAoZHBR8j19AU1lZvUCTRIm+raDIXNJHvhoGEXSlvKAdWQoAAsASTBFgA98DCIesI3T1e0LSzBEbHwJGgGFQAHNMuY-EUwKRWOwiuRFilUFpfIYuMdlq1NH0eikQBgYAIDrAAG6IVjeVIwADyTAAVvgJgA6cmUwgLJabTQXa53R7PIQ7EL9MJhEkwRAAdxQUC0ADUKd4uNLZTA2TRcRIxaZkGkBKrLgqlfghG8dZKZZcZmADVa5ZpFezRD0fJI3RIgA)
BTW: Please update the libs in the playground, `Object.values()` (ES2017) isn't available.

**Related Issues:** -

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #32752.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
This PR slightly tweaks the conditions under which we eliminate types in unions during type inference. Specifically, it modifies the last bullet relating to union types in #32558 to be:

* Finally, if there were source types from which no inferences or only lower priority inferences were made in the previous step, infer from a union of those source types to each naked type parameter in the target set. Give lower priority to these inferences if the target set contains more than one naked type parameter.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
DT run is clean, I think this one is ready to merge.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg did you specifically want this one in 3.6.1?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15905,7 +15901,7 @@ namespace ts {
                 const symbol = isNonConstructorObject ? target.symbol : undefined;
                 if (symbol) {
                     if (contains(symbolStack, symbol)) {
-                        inferenceIncomplete = true;
+                        inferencePriority = -1;
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: I can't tell if `-1` is being used here because it's lower than anything else, has all bits set, or both. A named enum member with the intended semantics of this would be clearer.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -15778,31 +15773,32 @@ namespace ts {
...
                             for (let i = 0; i < sources.length; i++) {
-                                const saveInferenceMatch = inferenceMatch;
-                                inferenceMatch = false;
+                                const saveInferencePriority = inferencePriority;
+                                inferencePriority = InferencePriority.MaxValue;
                                 inferFromTypes(sources[i], t);
-                                if (inferenceMatch) matched[i] = true;
-                                inferenceMatch = inferenceMatch || saveInferenceMatch;
+                                if (inferencePriority === priority) matched[i] = true;
+                                inferenceCircularity = inferenceCircularity || inferencePriority < 0;
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Is it possible for `inferencePriority` to be a negative value that isn't `-1` ?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -15694,19 +15693,15 @@ namespace ts {
...
-                    if (status & 2) inferenceIncomplete = true;
+                    inferencePriority = Math.min(inferencePriority, status);
                     return;
                 }
-                (visited || (visited = createMap<number>())).set(key, 0);
-                const saveInferenceMatch = inferenceMatch;
-                const saveInferenceIncomplete = inferenceIncomplete;
-                inferenceMatch = false;
-                inferenceIncomplete = false;
+                (visited || (visited = createMap<number>())).set(key, -1);
```
Comment (RyanCavanaugh) [inline src/compiler/checker.ts]: Is the `-1` here (used as `number`) the same `-1` lower in the file?

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: It's because `-1` is less than any normal priority value. I'll give it a symbolic name.

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: No

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yes

**Comment by ahejlsberg** [comment]
> did you specifically want this one in 3.6.1?

I think it is a very safe fix, so yes if possible.

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this into release-3.6
