### PR TITLE
Fix for crash on call expression with private identifiers.

### LINKED ISSUE #42860: Regression: Compiler crash on call expression with private identifier on an any typed variable in 4.2RC
# Bug Report

### 🔎 Search Terms

A call expression with a private identifier coming from an any typed variable crashes the compiler

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.1 and 4.2

```ts
class A {
    #m: () => void
    method(thing: any) {
        thing.#m();
    }
};

```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/MYGwhgzhAECC0G8BQ1XQMQFsCEAuaAFAJTQC8AfNAG4D2AlgCYpqYCmALgBY0MFd0A7AOb4wAgJ4lkaGdH7CAdFmIBuZqgC+SDWqA)
      
### 🙁 Actual behavior

Compiler crashes

### 🙂 Expected behavior

Compiler should not crash. 

Regression appears to have been introduced in fix for #42166 ([PR](https://github.com/microsoft/TypeScript/pull/42176/files))

### PR DESCRIPTION
**Pull request by dragomirtitian**
Fix for crash when using ca call expression on private identifier coming from an any typed variable.

Fixes #42860

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]
I'll do a cherry pick as soon as we're ready to merge. Looks good to me though.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -21978,7 +21978,16 @@ namespace ts {
                         const type = getTypeOfDottedName((<PropertyAccessExpression>node).expression, diagnostic);
                         if (type) {
                             const name = (<PropertyAccessExpression>node).name;
-                            const prop = getPropertyOfType(type, isPrivateIdentifier(name) ? getSymbolNameForPrivateIdentifier(type.symbol, name.escapedText) : name.escapedText);
+                            let prop: Symbol | undefined;
+                            if (isPrivateIdentifier(name)) {
+                                if (!type.symbol) {
```
Comment (weswigham) [inline src/compiler/checker.ts:21983]: Hm, I dislike relying on `type.symbol`, but it seems like we can only guarantee `getNodeLinks((<PropertyAccessExpression>node).expression).resolvedSymbol` exists for `Identifier` LHSs, since as `getTypeOfDottedName` recurs, it doesn't set it on other interesting LHS node kinds, like `checkPropertyAccessExpressionOrQualifiedName` sometimes does.

**Review by weswigham — APPROVED** [review]
This looks OK to me, my minor lament aside. @sandersn has a bit more context here though.

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-4.2

File: src/compiler/checker.ts (hunk 1 above)
Comment (dragomirtitian) [reply src/compiler/checker.ts:21983]: I initially had an `isAnyLike` check since I discovered the issue on  `any`, but `never` and `unknown` also trigger the issue.
