### PR TITLE
Give more helpful error when trying to set default values on an interface.

### LINKED ISSUE #5173: Give more helpful error when trying to set default values on an interface
Today I spent a moment scratching my head at the following snippet:

```
interface Foo {
	bar: number = 5;
}
```

*"Of course!"* I say now, I was trying to set a default value on an interface, which makes no sense. TypeScript didn't see that this might be something I would do, and instead gave me a syntax error:

```
Error TS1005: ';' expected.
Error TS1131: Property or signature expected.
Error TS1128: Declaration or statement expected.
```

Would it be possible to get a more useful error message for this case (and potentially cases like this?)

### PR DESCRIPTION
**Pull request by delta-nry**
Fixes #5173 - Give more helpful error when trying to set default values on an interface.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Hey @delta-nry - thanks for the PR. I notice that there's no test case affected - can you add a few tests [as per  our contribution guidelines](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#adding-a-test)?

**Comment by delta-nry** [comment]
Thanks for the quick reply @DanielRosenwasser. As I am part of a group of students from the University of British Columbia, I am waiting for my partners to implement the test case(s) you requested. Thus, we may get back to you sometime within two weeks. Thank you for your patience on resolving this PR.

**Comment by DanielRosenwasser** [comment]
No worries, just keep us posted since GitHub doesn't send updates for new commits.

**Comment by delta-nry** [comment]
I have implemented the required tests. In the interest of full disclosure, I am the sole person who implemented these tests and none of the content of these tests are original works of my partners. Thank you for your patience regarding this issue.

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -2247,6 +2247,13 @@ namespace ts {
                 property.name = name;
                 property.questionToken = questionToken;
                 property.type = parseTypeAnnotation();
+
+                // Although object type properties cannot not have initializers, we attempt to parse an initializer
+                // so we can report that an object type property cannot have an initializer.
+                if (token === SyntaxKind.EqualsToken && lookAhead(() => parseNonParameterInitializer()) !== undefined) {
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: You can just pass `parseNonParameterInitializer` to lookahead. Testing truthiness is fine here, and you'll avoid allocating a closure.

**Comment by DanielRosenwasser** [comment]
@CyrusNajmabadi can you take a quick look?

File: tests/baselines/reference/errorOnInitializerInObjectType.errors.txt [hunk 2]
```diff
@@ -0,0 +1,17 @@
+tests/cases/compiler/errorOnInitializerInObjectType.ts(2,17): error TS1246: An object type property cannot have an initializer.
+tests/cases/compiler/errorOnInitializerInObjectType.ts(6,17): error TS1246: An object type property cannot have an initializer.
+
+
+==== tests/cases/compiler/errorOnInitializerInObjectType.ts (2 errors) ====
+    interface Foo {
+        bar: number = 5;
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/errorOnInitializerInObjectType.errors.txt]: I'm surprised that we don't go off the rails here since you're not advancing the parser at all (i.e. you use `lookAhead`, not `tryParse`).

Comment (DanielRosenwasser) [inline tests/baselines/reference/errorOnInitializerInObjectType.errors.txt]: Actually, this is because the parser tries to be smart and avoids reporting more errors at the same start position. I'm not sure if that's the right thing to do because instead of gracefully parsing the invalid initializer, the parser can start going haywire down the line. Maybe `tryParse` would be better? What do you think @CyrusNajmabadi?

File: src/compiler/parser.ts (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: I would not do it this way.  I would just parse out an initialize for these properties.  Then, in the checker, detect that and report a nice error there.

We do not want random errors being produced the parser like this.

File: tests/baselines/reference/errorOnInitializerInObjectType.errors.txt (hunk 2 above)
Comment (CyrusNajmabadi) [inline tests/baselines/reference/errorOnInitializerInObjectType.errors.txt]: We should just allow initializers.  This is a pretty reasonable thing for a user to type, so the tree shoudl just be flexible enough to represent it.  We can hten have a simple grammar check in the type checker that reports that thsi isn't legal.

File: src/compiler/parser.ts (hunk 1 above)
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: So to summarize @delta-nry, just add an optional initializer onto each PropertySignature and perform a grammar check in `checker.ts` on each property. Report the error on the initializer itself.

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -16085,6 +16095,18 @@ namespace ts {
                 }
             }
 
+            if (node.type) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You should be performing this check in *any* type literal, not just those in variable like declarations.

I think you should just move the check into `checkGrammarProperty`, and discriminate on whether you have a `PropertySignature` with an initializer.

**Comment by DanielRosenwasser** [comment]
@delta-nry, I left some feedback. Basically, you should perform the grammar check in `checkGrammarProperty`.

File: tests/baselines/reference/objectTypeLiteralSyntax2.errors.txt [hunk 4]
```diff
@@ -15,4 +17,8 @@ tests/cases/conformance/types/objectTypeLiteral/objectTypeLiteralSyntax2.ts(12,2
     
     var z: { foo: string bar: string }
                          ~~~
+!!! error TS1005: '=' expected.
+                         ~~~
+!!! error TS2304: Cannot find name 'bar'.
+                            ~
```
Comment (delta-nry) [inline tests/baselines/reference/objectTypeLiteralSyntax2.errors.txt]: I'm not sure if we should accept these errors, as the ```'=' expected``` message implies that initializers are allowed in this case. Maybe we should spin this off into a new issue. @DanielRosenwasser @CyrusNajmabadi, what are your thoughts on this?

Comment (DanielRosenwasser) [inline tests/baselines/reference/objectTypeLiteralSyntax2.errors.txt]: It should be sufficient if you make it so that you only try to parse an initializer if you see a `=`.

**Comment by delta-nry** [comment]
@DanielRosenwasser, @CyrusNajmabadi how do these fixes look?

File: src/compiler/diagnosticMessages.json [hunk 5]
```diff
@@ -783,6 +783,14 @@
         "category": "Error",
         "code": 1245
     },
+    "An interface property cannot have an initializer.": {
+        "category": "Error",
+        "code": 1246
+    },
+    "An object type literal property cannot have an initializer.": {
```
Comment (DanielRosenwasser) [inline src/compiler/diagnosticMessages.json]: Sorry I didn't notice it earlier, but this should be "A type literal property"

File: src/compiler/parser.ts [hunk 6]
```diff
@@ -2247,6 +2247,14 @@ namespace ts {
                 property.name = name;
                 property.questionToken = questionToken;
                 property.type = parseTypeAnnotation();
+
+                if (token === SyntaxKind.EqualsToken) {
+                    // Although object type properties cannot not have initializers, we attempt
+                    // to parse an initializer so we can report in the checker that an interface
+                    // property or object type literal property cannot have an initializer.
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: type literal

File: src/compiler/parser.ts [hunk 7]
```diff
@@ -2247,6 +2247,14 @@ namespace ts {
                 property.name = name;
                 property.questionToken = questionToken;
                 property.type = parseTypeAnnotation();
+
+                if (token === SyntaxKind.EqualsToken) {
+                    // Although object type properties cannot not have initializers, we attempt
```
Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: type literal properties

**Comment by DanielRosenwasser** [comment]
I think this is great - just address the last comments I left and we should be good to merge. :smiley:

**Comment by DanielRosenwasser** [comment]
:100:
