### PR TITLE
Delay "File change detected" reporting until createProgram

### LINKED ISSUE #46949: `tsc -watch` should ignore files without extensions, pretends to hang during compilation instead
# Bug Report

### 🔎 Search Terms

* watch
* extension
* change
* detected

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ...watching files?
- I was unable to test this on prior versions because I haven't used typescript in a while
- This behavior is present in typescript nightly 4.6.0-dev.20211126

### ⏯ Playground Link

[mkhl/issue-tsc-watch-should-ignore-files-without-extension](https://github.com/mkhl/issue-tsc-watch-should-ignore-files-without-extension) (branch `next` for typescript nightly)

A playground won't work because it's not the handling of typescript code that's problematic but of other additional files

### 💻 Code

```ts

```

### 🙁 Actual behavior

1. `tsc -watch -p ./`
2. `touch foo` or `mkdir`
3. tsc output:
    > File change detected. Starting incremental compilation...

Note that touching a relevant file (like `index.ts` results in normal output resuming).
Note also that with this behavior, the user _and tools that scan tsc output, like visual studio code_, may assume that they have to wait for tsc to finish compilation.
(That's in fact what vscode does, which led me here.)

### 🙂 Expected behavior

Since a file without an extension or an empty directory don't require recompilation, tsc should ignore them and not output anything.
It already handles files with irrelevant extensions this way (like `foo.txt`).

### PR DESCRIPTION
**Pull request by jakebailey**
There are cases where the file/directory watching handler can't determine whether or not a change should be ignored or not. For files with unsupported extensions (like `.txt`), the watcher never calls the handler. However, extensionless files _do_ cause the watcher to call the handler (among other cases).

Rather than trying to perfect the watcher logic, delay printing of the "file change detected" message until we actually know we're going to create a new program (i.e. after it's determined that something important changed, and therefore a new program needs to be created).

Fixes #46949

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]
State management seems rough here. The solution seems okay, but maybe others on the team have better strategies.

**Comment by jakebailey** [comment]
If this is less desirable, an alternative change that I considered was to, in `watchWildcardDirectory`, pass the result of `addOrDeleteFileOrDirectory` to `isIgnoredFileFromWildCardWatching`, then have it explicitly ignore extensionless files (using the cached `stat`).

But, I feel like there are other cases that are not handled there either, e.g. consider a new file that _is_ supported, or a new _directory_, but that aren't actually in the program (thanks to `exclude` or not being in `include` or something). In that case, this same bug would happen, as the file watcher would trigger, but the program would not be recreated and never log the second message. To avoid that, I thought it would be a little better to just tie this to the actual thing that prints the second message, the creation of a new program.

File: src/compiler/watchPublic.ts [hunk 1]
```diff
@@ -273,6 +273,7 @@ namespace ts {
         let sharedExtendedConfigFileWatchers: ESMap<Path, SharedExtendedConfigFileWatcher<Path>>; // Map of file watchers for extended files, shared between different referenced projects
         let extendedConfigCache = host.extendedConfigCache;                 // Cache for extended config evaluation
         let changesAffectResolution = false;                                // Flag for indicating non-config changes affect module resolution
+        let reportWatchDiagnosticOnCreateProgram: DiagnosticMessage | undefined; // Diagnostic message to report in synchronizeProgram before new program creation
```
Comment (amcasey) [inline src/compiler/watchPublic.ts:276]: Personally, I would find a bool more readable - this creates the impression that multiple distinct messages are possible.

File: src/compiler/watchPublic.ts [hunk 2]
```diff
@@ -434,15 +435,22 @@ namespace ts {
             const hasInvalidatedResolution = resolutionCache.createHasInvalidatedResolution(userProvidedResolution || changesAffectResolution);
             if (isProgramUptoDate(getCurrentProgram(), rootFileNames, compilerOptions, getSourceVersion, fileExists, hasInvalidatedResolution, hasChangedAutomaticTypeDirectiveNames, getParsedCommandLine, projectReferences)) {
                 if (hasChangedConfigFileParsingErrors) {
+                    if (reportWatchDiagnosticOnCreateProgram) {
```
Comment (amcasey) [inline src/compiler/watchPublic.ts:438]: Seems like this has to be true?  How could the config file change without triggering a program refresh?

**Review by amcasey — COMMENTED** [review]
I don't use watch mode very often, so I may be out of touch, but I think I'd rather see "detected change... ignoring change" than nothing if it's actually doing work.

**Comment by amcasey** [comment]
@jakebailey Do you have a link to the kick-out that's causing the problem (i.e. preventing the second log message from being printed)?

**Comment by jakebailey** [comment]
I believe it's https://github.com/microsoft/TypeScript/blob/28c2084acad69c4c6b048326ee5190e10d162c57/src/compiler/watchUtilities.ts#L503.

(I can check when I have a chance and I'm back at my machine)

File: src/compiler/watchPublic.ts (hunk 1 above)
Comment (jakebailey) [reply src/compiler/watchPublic.ts]: Switched to a bool.

File: src/compiler/watchPublic.ts (hunk 2 above)
Comment (jakebailey) [reply src/compiler/watchPublic.ts]: Unless I'm mistaken, `hasChangedConfigFileParsingErrors` can be true if `hasChangedConfigFileParsingErrors` was called, which can happen if the refresh level was `ConfigFileProgramReloadLevel.Partial` (and then those call sites are outside of the watcher changes, entirely, I think). I'll remove the if and see if there are any tests for this, though.

Comment (jakebailey) [reply src/compiler/watchPublic.ts]: It seems like that if there's a case where `hasChangedConfigFileParsingErrors` is true but `reportWatchDiagnosticOnCreateProgram` is false, there's no test for it.

I can change this to unconditionally report the message, but I'm not entirely confident that there's no code path where this breaks.

Comment (amcasey) [reply src/compiler/watchPublic.ts]: I'm not familiar from this code - I'm just pointing out that, abstractly, it seems like a config file change will always be a relevant file change (i.e. will require the message to be printed).

**Comment by jakebailey** [comment]
> I think I'd rather see "detected change... ignoring change" than nothing if it's actually doing work.

This is a little tricky due to how this thing is printed; it goes via `afterProgramCreate` below which is a result of the `emitFilesAndReportErrors` callback.

**Comment by amcasey** [comment]
> I believe it's
> 
> https://github.com/microsoft/TypeScript/blob/28c2084acad69c4c6b048326ee5190e10d162c57/src/compiler/watchUtilities.ts#L503
> 
> .
> (I can check when I have a chance and I'm back at my machine)

`false` doesn't mean it's _not_ ignored?

File: src/compiler/watchPublic.ts [hunk 3]
```diff
@@ -434,15 +435,22 @@ namespace ts {
...
             }
             else {
+                if (reportFileChangeDetectedOnCreateProgram) {
+                    reportWatchDiagnostic(Diagnostics.File_change_detected_Starting_incremental_compilation);
+                }
                 createNewProgram(hasInvalidatedResolution);
             }
 
             changesAffectResolution = false; // reset for next sync
+            reportFileChangeDetectedOnCreateProgram = false;
```
Comment (amcasey) [inline src/compiler/watchPublic.ts:453]: Can this be cleared in `updateProgramWithWatchStatus`?  I think that would make its lifetime/scope much clearer.

File: src/compiler/watchPublic.ts [hunk 4]
```diff
@@ -434,15 +435,22 @@ namespace ts {
             const hasInvalidatedResolution = resolutionCache.createHasInvalidatedResolution(userProvidedResolution || changesAffectResolution);
             if (isProgramUptoDate(getCurrentProgram(), rootFileNames, compilerOptions, getSourceVersion, fileExists, hasInvalidatedResolution, hasChangedAutomaticTypeDirectiveNames, getParsedCommandLine, projectReferences)) {
                 if (hasChangedConfigFileParsingErrors) {
+                    if (reportFileChangeDetectedOnCreateProgram) {
+                        reportWatchDiagnostic(Diagnostics.File_change_detected_Starting_incremental_compilation);
```
Comment (amcasey) [inline src/compiler/watchPublic.ts:439]: How much work is done between where this used to be reported and here?  I'm concerned that it will look like the compiler is frozen if it reacts "late" to a file change.

**Review by amcasey — COMMENTED** [review]
> > I think I'd rather see "detected change... ignoring change" than nothing if it's actually doing work.
> 
> This is a little tricky due to how this thing is printed; it goes via `afterProgramCreate` below which is a result of the `emitFilesAndReportErrors` callback.

I might be missing something obvious, but wouldn't it just be a matter of updating `synchronizeProgram` to print "ignoring" in cases where this PR does _not_ print "change detected"?

**Comment by jakebailey** [comment]
> `false` doesn't mean it's _not_ ignored?

It does mean it's not ignored (so the watcher will emit the event), but in this case, adding the extensionless file doesn't actually cause the program to change.

I debugged and I did note the correct return statement.

It occurs to me that my alternative fix (using the stat info) is likely to not work right when that same extensionless file is deleted later, since we won't have any idea if that was a directory or not that changed.

File: src/compiler/watchPublic.ts (hunk 3 above)
Comment (jakebailey) [reply src/compiler/watchPublic.ts:453]: I can clear it there instead, but I had been modelling `changesAffectResolution`.

My main concern was a case where it may be left over for another synchronize later, but I don't know why I thought that.

File: src/compiler/watchPublic.ts (hunk 4 above)
Comment (jakebailey) [reply src/compiler/watchPublic.ts:439]: That's a good question; my skimming says that `isProgramUptoDate` will:

- Compare a few arrays for equality
- Check for not-up-to-date source files, which appears to be checking a number of caches
- Check for files that the program thought were missing on disk
- Compare compiler options
- Compare tsconfig contents by text for position changes for diagnostics

I'm not sure that it's a huge amount of work.

I could try and have it unconditionally run `afterProgramCreate`, but based on #37266, it seems like this was an intentional change (but, hard to tell entirely, given it's one part of a lot of other tweaks). I'll try it and see if anything breaks catastrophically, but I don't know exactly how to double check that I don't undo a perf fix.

**Comment by amcasey** [comment]
@jakebailey's offline explanation - we can't break existing consumers by changing our output - convinced me that printing an explicit ignore message would be worse.

File: src/compiler/watchPublic.ts (hunk 3 above)
Comment (amcasey) [reply src/compiler/watchPublic.ts:453]: Personally, I think it's clearer to set it and call it in the same place, but I'm also fine with following local conventions.  If this is where things are cleared after sync, then go for it.

File: src/compiler/watchPublic.ts (hunk 4 above)
Comment (amcasey) [reply src/compiler/watchPublic.ts:439]: I think we convinced ourselves that it should be cheap.  I'm fine bugging this into shape if we get complaints.

File: tests/baselines/reference/tscWatch/programUpdates/config-file-is-deleted.js [hunk 5]
```diff
@@ -84,9 +84,6 @@ Input::
 //// [/a/b/tsconfig.json] deleted
 
 Output::
->> Screen clear
-[[90m12:00:24 AM[0m] File change detected. Starting incremental compilation...
-
 [91merror[0m[90m TS5083: [0mCannot read file '/a/b/tsconfig.json'.
```
Comment (jakebailey) [inline tests/baselines/reference/tscWatch/programUpdates/config-file-is-deleted.js:87]: It's hard to tell in the diff here, but after this message is printed, the process exits (see exitCode below), so it's sort of pointless if this message is printed or not here other than to maybe indicate that we noticed because of a file watcher update.

This same error is printed if we start a missing config file in the first place.

**Review by amcasey — APPROVED** [review]
Thanks for investigating!
