### PR TITLE
fix(50188): "Declare missing function" codefix offered on arguments

### LINKED ISSUE #50188: "Declare missing function" codefix offered on arguments
# Bug Report

### 🔎 Search Terms

declare missing function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the moon

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAoAPALnlWQFsAjEGASjKlQE8BuAWAChECoBnYIgFCo9NkA)

### 💻 Code

```ts
declare function f(x: number): any;
f(asdfasdfa);
```

### 🙁 Actual behavior

We offer to declare `asdfasdfa` as a function

image

### 🙂 Expected behavior

No codefix—the fix is intended to be given only when the unresolved identifier is the _expression_ of the CallExpression, not an argument passed to it.

Noticed by @danay1999 while working on ts-fix

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #50188

### CODE REVIEW

File: src/services/codefixes/fixAddMissingMember.ts [hunk 1]
```diff
@@ -190,7 +190,7 @@ namespace ts.codefix {
             return { kind: InfoKind.JsxAttributes, token, attributes, parentDeclaration: token.parent };
         }
 
-        if (isIdentifier(token) && isCallExpression(parent)) {
+        if (isIdentifier(token) && isCallExpression(parent) && parent.expression === token) {
```
Comment (DanielRosenwasser) [inline src/services/codefixes/fixAddMissingMember.ts:193]: 😆
