### PR TITLE
fix(60908): Unexpected "'Type' is declared but its value is never read." error with jsdoc @import syntax

### LINKED ISSUE #58368: JSDoc @import not detecting use in @callback
### 🔎 Search Terms

jsdoc import @import callback lsp

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it's a new feature in 5.5. It was appearing in nightlies and I waited for the beta to confirm it's still there.

### ⏯ Playground Link

_No response_

### 💻 Code

```js
/**
 * @import {Checker, Passable} from '@endo/pass-style';
 */

/**
 * @callback GetChecker
 * @param {Passable} payload
 * @returns {Checker}
 */

/**
 * @typedef {object} Misc
 * @property {Passable} passable
 */
```

### 🙁 Actual behavior

The `Checker` import is dim in an IDE and hovering says,
```
'Checker' is declared but never used.ts(6196)
```

### 🙂 Expected behavior

LSP detects that `Checker` is in the return of `GetChecker`. 

### Additional information about the issue

The use is detected in `@typedef` and `@type`. E.g. as with `Passable` in the example code.

### LINKED ISSUE #60908: Unexpected "'Type' is declared but its value is never read." error with jsdoc @import syntax
### 🔎 Search Terms

jsdoc `@import` "is declared but its value is never read"

### 🕗 Version & Regression Information

I have seen this error since the introduction of `@import` in jsdoc comments (TS 5.5 if i recall correctly)

### ⏯ Playground Link

_No response_

### 💻 Code

I made a testcase repo https://github.com/DavidBruant/jsdoc-import-unused-testcase
It is as reduced as a managed to make it

The code : 

```js
/** @import {ImportedType} from './types.d.ts' */

function id() { return undefined }

/** @type {Set<ImportedType>} */
export const phases = new Set(['a', 'b'])

```

The types.d.ts file:
```ts
export type ImportedType = 'a' | 'b'
```

### 🙁 Actual behavior

`tsc` and VSCodium both say: 
```
code.js:1:5 - error TS6133: 'ImportedType' is declared but its value is never read.

1 /** @import {ImportedType} from './types.d.ts' */
```

### 🙂 Expected behavior

There shouldn't be an error because of the line using the type : `/** @type {Set<ImportedType>} */`

We've had this error in plently of places. It also seems like it occurs more regulary when the type is used within a generics

### Additional information about the issue

For some reason, removing `function id() { return undefined }` from the code solves the problem while it seems completely unrelated to the problem

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #60908 
Fixes #58368

### CODE REVIEW

**Comment by regseb** [comment]
Maybe this pull request also fixes the issue https://github.com/microsoft/TypeScript/issues/58368 (and its duplicate https://github.com/microsoft/TypeScript/issues/58969).

**Comment by jakebailey** [comment]
@typescript-bot test it
@typescript-bot pack this

**Comment by jakebailey** [comment]
Looking at the playground, I believe this does fix #58368, yes.

- Before: [Playground Link](https://www.typescriptlang.org/play/?filetype=js#code/PQKhCgAIUgBBLAtgBwPYCcAukDeA5VAEwFMBnAX0gDN1VFIByRQgQ1MwahgRQ2xwAKqeADtMAGkhDS8TPFQjKNOowCuI+O07Rg4cKAjRIAcWLZMAC2KRUVKqTM2qkFpGQt0DwpHWbsaUUwAOi4uOHd0FnpBYTFKALEwyEgAFSsfDXY3WOxbSAB3C3gAYwtITFRIAHNHS2tbezMQo1h0M1V0EVJcEVVEACNidHIk1PSGh1znOoy-bMDmkF1iAA80LGp1YrkFarMhQIB5O0mACgTMAEpcKEg2zA6RSAM4TABPZGscXoGhyiXIOcckEJmZLuARvowGFTOZ0uwPFNGlMXG4PF5ZlkLoswrAIlFcAQSBRICIiMRRmlrL4sTknAUiqVypUanDrAiNqDgrj7o9ut8+oNhpT4ZhEU5kfSZjT-MCuMs1nxNiJtvInqyicQAMpirDHZGnMkka44W68zp7TAHMT6s4vWDvT64aSyNX-YCAo3EIJoGQ7ESXIIcq4QvQGGG1dLEETeLn01wRDEy+ZiHEtfHRTUkr0i6mZWWBemFEplCqW8pRmMSyaLODmro9QV-XOQaOxk6OPLS-Mp7k6cCrdbYKhbf2WzUAURjtrMhvJJrN7QtrOtmBnmFO9sdXxd-vdnvJPtQfrVgbb4JGQA)
- After: [Playground Link](https://www.typescriptlang.org/play/?ts=5.8.0-pr-60921-3&filetype=js#code/PQKhCgAIUgBBLAtgBwPYCcAukDeA5VAEwFMBnAX0gDN1VFIByRQgQ1MwahgRQ2xwAKqeADtMAGkhDS8TPFQjKNOowCuI+O07Rg4cKAjRIAcWLZMAC2KRUVKqTM2qkFpGQt0DwpHWbsaUUwAOi4uOHd0FnpBYTFKALEwyEgAFSsfDXY3WOxbSAB3C3gAYwtITFRIAHNHS2tbezMQo1h0M1V0EVJcEVVEACNidHIk1PSGh1znOoy-bMDmkF1iAA80LGp1YrkFarMhQIB5O0mACgTMAEpcKEg2zA6RSAM4TABPZGscXoGhyiXIOcckEJmZLuARvowGFTOZ0uwPFNGlMXG4PF5ZlkLoswrAIlFcAQSBRICIiMRRmlrL4sTknAUiqVypUanDrAiNqDgrj7o9ut8+oNhpT4ZhEU5kfSZjT-MCuMs1nxNiJtvInqyicQAMpirDHZGnMkka44W68zp7TAHMT6s4vWDvT64aSyNX-YCAo3EIJoGQ7ESXIIcq4QvQGGG1dLEETeLn01wRDEy+ZiHEtfHRTUkr0i6mZWWBemFEplCqW8pRmMSyaLODmro9QV-XOQaOxk6OPLS-Mp7k6cCrdbYKhbf2WzUAURjtrMhvJJrN7QtrOtmBnmFO9sdXxd-vdnvJPtQfrVgbb4JGQA)

File: src/compiler/binder.ts [hunk 1]
```diff
@@ -1108,6 +1109,9 @@ function createBinder(): (file: SourceFile, options: CompilerOptions) => void {
             if (canHaveFlowNode(node) && node.flowNode) {
                 node.flowNode = undefined;
             }
+            if (isJSDocImportTag(node)) {
+                return;
+            }
```
Comment (jakebailey) [inline src/compiler/binder.ts:1114]: Why is the import tag special here?

Also, this early return will leave `inAssignmentPattern` in a bad state, so I think it's better to skip the steps below that are broken with import tags if needed, or maybe there's something else wrong otherwise.

Comment (a-tarasyuk) [reply src/compiler/binder.ts:1114]: @jakebailey thanks for the feedback. I found that in this case, the `finallyBlock` should not be handled as a child of the try block to ensure the correct delta calculation 

https://github.com/microsoft/TypeScript/blob/5170645f4e4b395891fad823bfe03ac628411afb/src/services/formatting/formatting.ts#L624

There are other places where we handle the `finallyBlock` in a similar way

https://github.com/microsoft/TypeScript/blob/5170645f4e4b395891fad823bfe03ac628411afb/src/services/outliningElementsCollector.ts#L259-L261

I hope that makes sense., if you have any thoughts or suggestions, I’d be grateful to hear them. thanks

Comment (a-tarasyuk) [reply src/compiler/binder.ts:1114]: @jakebailey thanks for the feedback. These changes are open for discussion :). This applies to the case when we have

```js
/** @import { Foo } from 'foo' */
function foo() {}
```
 
The function acts as a container that holds locals, including the symbol Foo. Since this symbol is unused (and doesn't have an `exportSymbol` like the `typedef` does), the checker triggers an error.

```ts
if (.... local.exportSymbol) {
    return;
}
```
 
Perhaps the container for the import tag should be treated like a `SourceFile`...

```ts
ContainerFlags.IsContainer | ContainerFlags.IsControlFlowContainer | ContainerFlags.HasLocals;
```

Anyway, I’d be grateful for any ideas or suggestions regarding this case. thanks

Comment (jakebailey) [reply src/compiler/binder.ts:1114]: Mainly, I'm trying to understand why import tags have to be special cased, but other JSDoc "declarations" don't.

Comment (a-tarasyuk) [reply src/compiler/binder.ts]: @jakebailey `JsDocImportTag` reuses `importClause`, however, it doesn't _bind_ it immediately, opting for a delayed binding instead

https://github.com/microsoft/TypeScript/blob/8da951cbb629b648753454872df4e1754982aef1/src/compiler/binder.ts#L1202-L1204

https://github.com/microsoft/TypeScript/blob/8da951cbb629b648753454872df4e1754982aef1/src/compiler/binder.ts#L2126-L2135

When the `binder` executes `bindChildren` and `bindEachChild`, it iterates through all child nodes, including `importClause`, and binds them

https://github.com/microsoft/TypeScript/blob/8da951cbb629b648753454872df4e1754982aef1/src/compiler/binder.ts#L3062-L3063

https://github.com/microsoft/TypeScript/blob/8da951cbb629b648753454872df4e1754982aef1/src/compiler/binder.ts#L3058-L3059

this creates incorrect locals for the parent container. Other tags, such as `@typedef` and `@callback`, don't rely on such nodes.

Comment (jakebailey) [reply src/compiler/binder.ts]: Hm, I see; this honestly makes me wonder why the code doesn't just fall through into the code below, which seems to have a lot more special cases that feel like they'd matter in the same way...

Comment (jakebailey) [reply src/compiler/binder.ts]: As in, be written:

```ts
// ...
if (checkUnreachable(node)) {
    if (canHaveFlowNode(node) && node.flowNode) {
        node.flowNode = undefined;
    }
} else if (node.kind >= SyntaxKind.FirstStatement && node.kind <= SyntaxKind.LastStatement && (!options.allowUnreachableCode || node.kind === SyntaxKind.ReturnStatement)) {
    (node as HasFlowNode).flowNode = currentFlow;
}
switch (node.kind) {
// ...
```

Comment (jakebailey) [reply src/compiler/binder.ts]: I mean it falls over, so that can't be right either

Comment (a-tarasyuk) [reply src/compiler/binder.ts]: I think _unreachable flow_ cannot be handled properly without

```js
bindEachChild(node);
bindJSDoc(node);
```

I'm exploring other options to skip processing child nodes for JSDoc imports...

Comment (a-tarasyuk) [reply src/compiler/binder.ts]: I think _unreachable flow_ can remain as is. Alternatively, an additional flag could be added to symbols bound from the JSDoc import (`ImportSpecifier`) to exclude them from the unused locals check. @sandersn @jakebailey what do you think?

Comment (sandersn) [reply src/compiler/binder.ts]: Two architecture questions:
- Why is importClause binding delayed? Could it be not delayed, so that the normal unreachable bind/bindChildren calls work?
- Why does checkUnreachable return/why doesn't Jake's idea work? That would be the least confusing fix, I think.

Otherwise .. the current code is the smallest fix, but it makes the code even more confusing to read.

**Comment by sandersn** [comment]
@typescript-bot test it

File: src/compiler/binder.ts [hunk 2]
```diff
@@ -3948,6 +3948,9 @@ export function getContainerFlags(node: Node): ContainerFlags {
         case SyntaxKind.ClassStaticBlockDeclaration:
             return ContainerFlags.IsContainer | ContainerFlags.IsControlFlowContainer | ContainerFlags.HasLocals | ContainerFlags.IsFunctionLike;
 
+        case SyntaxKind.JSDocImportTag:
+            return ContainerFlags.IsContainer | ContainerFlags.IsControlFlowContainer | ContainerFlags.HasLocals;
```
Comment (jakebailey) [inline src/compiler/binder.ts:3952]: Oh wow, this seems good

Comment (sandersn) [reply src/compiler/binder.ts:3952]: As I understand it, these 3 flags are to prevent mistakenly using a function host as the container for the imported bindings. Is that correct? Can you add a comment like that? I didn't naturally expect imports to be containers otherwise.

(This won't be a problem in Corsa since tags that generate statements won't even have hosts for the generated statements.)

Comment (a-tarasyuk) [reply src/compiler/binder.ts]: I’ve added the comment

**Review by sandersn — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
